### ISSUE TITLE
on tserver debug utilities page, add links for Cassandra & Redis API RPCs in progress

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#100]
In the TServer Debug Utilities handler (http://<host>:9000/utilz), we have the "RPCs in progress" link which displays the active TServer level RPCs. 

<img width="513" alt="screen shot 2018-03-16 at 10 27 23 pm" src="https://user-images.githubusercontent.com/13615376/37551994-4795fe48-2969-11e8-8499-1d33f4816f3e.png">

It'll be useful to: 
a) Rename the "RPCs in progress" to "TServer RPCs in progress". This is linked by default to http://<hostname>:9000/rpcz
b) Add a new link to "Redis API RPCs in progress" (linked to appropriate port - e.g., 11000/rpcz)
c) Add a new link to "Cassandra API RPCs in progress" (linked to appropriate port - e.g. 12000/rpcz)

**Comment by ayushsengupta1991** [comment]
Creating a JIRA for this: https://yugabyte.atlassian.net/browse/ENG-3115

**Comment by ayushsengupta1991** [comment]
Closed with https://github.com/YugaByte/yugabyte-db/commit/e0b4b5d742ff359a4f6c7922dc77b5d2d3c9c190
