### ISSUE TITLE
[docdb] Allow use of zlib compression in RocksDB

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#10019]

**Comment by bmatican** [comment]
Spoke to @robertsami , I think this could be another good rocksdb intro task + useful to do some investigation to highlight space amplification wins / perf impact, so passing to @rthallamko3 

Rob, can you add a link to the previous work to add in lz4 support? TK, feel free to sync with Rob on this.

**Comment by robertsami** [comment]
https://github.com/yugabyte/yugabyte-db/commit/38f306da873663b44d136b593212cab9e0e01afc

@rthallamko3 feel free to reach out with any questions!
