### ISSUE TITLE
[Docs] yb-ts-cli: add certs_dir_name flag

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#10017]
Add the `--certs_dir_name` flag to [yb-ts-cli](https://docs.yugabyte.com/latest/admin/yb-ts-cli/#flags). It's the same flag and meaning as the one for [yb-admin](https://docs.yugabyte.com/latest/admin/yb-admin/)

**Comment by ddorian** [comment]
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/13571
