### ISSUE TITLE
[CDCSDK] TRUNCATE TABLE - Query resulting in unexpected streamed records

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#10010]
Jira Link: [DB-3518](https://yugabyte.atlassian.net/browse/DB-3518)
Steps to reproduce:
- Execute the following queries:

  ```sql
  CREATE TABLE TEST (a INT PRIMARY KEY, b INT);
  
  INSERT INTO test VALUES (1, 2); --Query1
  INSERT INTO test VALUES (3, 4); --Query2
  
  BEGIN;
  INSERT INTO test VALUES (5, 6); --Query3
  COMMIT;
  
  TRUNCATE TABLE test;
  ```

- Run the Java client
- 7 records are streamed across CDC i.e.
  1. DDL (header)
  2. INSERT (from Query1)
  3. INSERT (from Query2)
  4. BEGIN
  5. COMMIT (resulting from commit after Query3)
  6. TRUNCATE
  7. DDL

The INSERT op inside the begin-commit block is not being streamed in this case.

**Comment by vaibhav-yb** [comment]
[UPDATE]
As of now, truncate has been disabled on tables if CDC is enabled for them. So suppose there is a table named `test` and CDC is enabled, and the user executes a command to truncate eg `TRUNCATE TABLE test;`, he will get an exception saying `Can't truncate a CDC enabled table : test [id=000030af000030008000000000004100]`

Now if the user actually wants to truncate the table, all he needs to do is delete all the streams attached to that table.

**Perform the following steps to delete all the streams:**
1. Use `yb-admin --master_addresses <master-addresses> list_cdc_streams` to get a list of all the streams. You will get an output like this:
    ```
    streams {
      stream_id: "74182f3e9e9048ff8fce6e9dfd6c37b9"
      table_id: "000033c0000030008000000000000000"
      options {
        key: "id_type"
        value: "NAMESPACEID"
      }
      options {
        key: "checkpoint_type"
        value: "IMPLICIT"
      }
      options {
        key: "source_type"
        value: "EXTERNAL"
      }
      options {
        key: "record_format"
        value: "PROTO"
      }
      options {
        key: "record_type"
        value: "CHANGE"
      }
      options {
        key: "state"
        value: "ACTIVE"
      }
    }
    ``` 
    Look for the stream ids one having `value: NAMESPACEID`, for the time being, let's call it `streamID`
2. Delete all such streams using `yb-admin --master_addresses <master-addresses> delete_db_cdc_stream streamID`
    A success message saying the stream id was deleted would be displayed.
3. The table can be truncated now.

**Comment by apatrida** [comment]
So the workaround is to stop a stream and have data loss in replication while truncating a table, or doing a slow delete all?  Is that correct?

**Comment by suranjan** [comment]
Yes. delete all should work.
For truncate, you can let the consumer consume all the changes, stop the stream and then truncate the table.
