### ISSUE TITLE
[YSQL] Add support for setval()

### ISSUE THREAD

**Issue by hectorgcr** [YugaByte/yugabyte-db#1003]
Currently we don't support the function setval() for setting the value in a sequence.

**Comment by ndeodhar** [comment]
pg_dump uses setval() to set the sequence value. Example snippet:
```
SELECT pg_catalog.setval('public.seq_a_seq', 5, true);
```

**Comment by georgeklees** [comment]
Because Postgres represents sequences as tables, should we also support the ability to do `UPDATE` on them? I'm not 100% sure if normal Postgres allows doing that but it seems pretty likely.
