### ISSUE TITLE
[docs] C# SSL documentation

### ISSUE THREAD

**Issue by Sfurti-yb** [yugabyte/yugabyte-db#10073]
[SSL Documentation](https://docs.google.com/document/d/1Dcg8yodQSdEtd5ObmYWbZreroffp3Syx7lll27qF4cQ/edit?usp=sharing) for C# getting started [page](https://docs.yugabyte.com/latest/quick-start/build-apps/csharp/ysql/#install-the-npgsql-c-driver)

**Comment by polarweasel** [comment]
Thanks @Sfurti-yb! PR is open now... Could you please review it?
