### ISSUE TITLE
[DST] Potential master follower deadlocks

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10071]
Found by @qvad 

Slack threadz dump: https://yugabyte.slack.com/files/U0YKAH8PP/F02EURL5DST/untitled.txt

TBD on order of operations, but we're seeing ~100% CPU usage on master followers, while the master leader is basically idle. In the threadz on one of the followers, you see a bunch of threads stuck in read locks
> yb::NonRecursiveSharedLock<>::NonRecursiveSharedLock()

but a handful of them stand out as potentially holding bigger locks, maybe stuck in some background work:
```
CatalogManagerBGTasks [worker]-32568
    @     0x7f96a769a11f  (unknown)
    @     0x7f96a801500c  __pthread_cond_wait
    @     0x7f96ad499e4f  yb::RWCLock::WriteLock()
    @     0x7f96b7993cac  yb::master::CatalogManager::DeleteYsqlDBTables()
    @     0x7f96b7994f2f  yb::master::CatalogManager::DeleteYsqlDatabaseAsync()
    @     0x7f96b79f35e1  yb::RunnableImpl<>::Run()
    @     0x7f96ad4be303  yb::ThreadPool::DispatchThread()
    @     0x7f96ad4baabe  yb::Thread::SuperviseThread()
    @     0x7f96a8010693  start_thread
    @     0x7f96a774d41c  __clone

CatalogManagerBGTasks [worker]-32570
    @     0x7f96a769a11f  (unknown)
    @     0x7f96a801846c  __GI___nanosleep
    @     0x7f96b79d97ea  yb::NonRecursiveSharedLock<>::NonRecursiveSharedLock()
    @     0x7f96b7993baa  yb::master::CatalogManager::DeleteYsqlDBTables()
    @     0x7f96b7994f2f  yb::master::CatalogManager::DeleteYsqlDatabaseAsync()
    @     0x7f96b79f35e1  yb::RunnableImpl<>::Run()
    @     0x7f96ad4be303  yb::ThreadPool::DispatchThread()
    @     0x7f96ad4baabe  yb::Thread::SuperviseThread()
    @     0x7f96a8010693  start_thread
    @     0x7f96a774d41c  __clone

CatalogManagerBGTasks [worker]-32571
    @     0x7f96a769a11f  (unknown)
    @     0x7f96a801846c  __GI___nanosleep
    @     0x7f96b79d6de9  yb::rw_semaphore::lock()
    @     0x7f96b79a4394  yb::master::CatalogManager::CreateYsqlSysTable()
    @     0x7f96b79a9f66  yb::master::CatalogManager::CopyPgsqlSysTables()
    @     0x7f96b79aa980  yb::master::CatalogManager::ProcessPendingNamespace()
    @     0x7f96b79de998  yb::RunnableImpl<>::Run()
    @     0x7f96ad4be303  yb::ThreadPool::DispatchThread()
    @     0x7f96ad4baabe  yb::Thread::SuperviseThread()
    @     0x7f96a8010693  start_thread
    @     0x7f96a774d41c  __clone

CatalogManagerBGTasks [worker]-32552
    @     0x7f96a769a11f  (unknown)
    @     0x7f96a7736516  __GI___sched_yield
    @     0x7f96b79d97b9  yb::NonRecursiveSharedLock<>::NonRecursiveSharedLock()
    @     0x7f96b7b4d584  yb::master::enterprise::CatalogManager::FindCDCStreamsForTable()
    @     0x7f96b7b50489  yb::master::enterprise::CatalogManager::DeleteCDCStreamsForTables()
    @     0x7f96b7994560  yb::master::CatalogManager::DeleteYsqlDBTables()
    @     0x7f96b7994f2f  yb::master::CatalogManager::DeleteYsqlDatabaseAsync()
    @     0x7f96b79f35e1  yb::RunnableImpl<>::Run()
    @     0x7f96ad4be303  yb::ThreadPool::DispatchThread()
    @     0x7f96ad4baabe  yb::Thread::SuperviseThread()
    @     0x7f96a8010693  start_thread
    @     0x7f96a774d41c  __clone
```

**Comment by tedyu** [comment]
In the above stack trace, CatalogManager::CreateYsqlSysTable() takes exclusive lock.
the other methods take shared lock.

Maybe we can get a bit clue (about order of attempted locks) if master log for this period was available.

**Comment by qvad** [comment]
@tedyu here is leader logs in fresh run

[master-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/7217225/master-logs.tar.gz)

**Comment by tedyu** [comment]
The stack trace in the description was for master.
The above tar ball contains tserver log (yb-tserver.ip-172-151-28-45.us-west-2.compute.internal.yugabyte.log.INFO.20210923-100159.18643).

**Comment by qvad** [comment]
@tedyu  Sorry, this one should be ok
[master-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/7225698/master-logs.tar.gz)

**Comment by qvad** [comment]
@tedyu Sorry, this one should be correct on
[yb-master.tar.gz](https://github.com/yugabyte/yugabyte-db/files/7225835/yb-master.tar.gz)
e

**Comment by tedyu** [comment]
Looking at yb-master.ip-172-151-56-8.us-west-2.compute.internal.yugabyte.log.INFO.20210924-113802.18575, there were 112 occurrences of log for CreateYsqlSysTable(). This was the latest one:
```
I0924 12:12:15.633850 29804 catalog_manager.cc:2493] CreateYsqlSysTable: sql_languages
```
For CatalogManager::FindCDCStreamsForTable(), the code doesn't have log.
For CatalogManager::DeleteYsqlDBTables(), there is only one log in the code:
```
    s = s.CloneAndPrepend(Substitute("An error occurred while updating sys tables: $0",
                                     s.ToString()));
    LOG(WARNING) << s.ToString();
```
which didn't show up in the master log.

From what I saw so far: it was not obvious which one, if any, of the CreateYsqlSysTable() calls got stuck.

Let me continue searching for clue in the log.

**Comment by tedyu** [comment]
I checked the attached master log but didn't see `Given incomplete Transaction`.
Didn't find create table related error either.

**Comment by tedyu** [comment]
Additional logging should give us more clue where the table deletion starts to get stuck:
```
diff --git a/src/yb/master/catalog_manager.cc b/src/yb/master/catalog_manager.cc
index 884da7a05..b4c97f792 100644
--- a/src/yb/master/catalog_manager.cc
+++ b/src/yb/master/catalog_manager.cc
@@ -6905,6 +6905,7 @@ Status CatalogManager::DeleteYsqlDBTables(const scoped_refptr<NamespaceInfo>& da
     // Populate tables and sys_table_ids.
     for (const TableInfoMap::value_type& entry : *table_ids_map_) {
       scoped_refptr<TableInfo> table = entry.second;
+      LOG(INFO) << "going to lock table " << table->name() << " for write";
       auto l = table->LockForWrite();
       if (l->namespace_id() != database->id() || l->started_deleting()) {
         continue;
```
In a reproduction of the hanging today, I found one CatalogManager::DeleteYsqlDatabaseAsync() call (while there were more than one in the stack trace of description).

**Comment by tedyu** [comment]
In a reproduction (via yb-sample-app), I saw the following in yb-master.ip-172-151-48-79.us-west-2.compute.internal.yugabyte.log.INFO.20210928-183337.18569 
```
I0928 19:13:09.629210 23266 raft_consensus.cc:1056] Sending NO_OP at op 3.18522
W0928 19:13:10.568645 23266 replica_state.cc:736] T 00000000000000000000000000000000 P 3781d15df64a4db8bb616422b9c11640 [term 4 LEADER]: Can't advance the committed index across term boundaries until operations from the current term are replicated. Last committed operation was: 3.18522, New majority replicated is: 3.18522, Current term is: 4
I0928 19:13:10.568637 21771 master_service.cc:548] Patching role from leader to follower because of: Leader not ready to serve requests. (yb/consensus/consensus.cc:117): Leader not yet replicated NoOp to be ready to serve requests [suppressed 2 similar messages]
```
It was a warning. Not sure whether it was critical.

Through additional logging in CatalogManager::DeleteYsqlDBTables()
```
I0928 18:54:20.946151 20174 catalog_manager.cc:6910] going to lock table pg_user_mapping_user_server_index for write
I0928 18:54:20.946197 20174 catalog_manager.cc:6910] going to lock table pg_foreign_data_wrapper_name_index for write
```
It seems we're (over) locking unnecessary tables.

**Comment by nspiegelberg** [comment]
The deadlock is in the stack
```
    @     0x7f96b7b4d584  yb::master::enterprise::CatalogManager::FindCDCStreamsForTable()
    @     0x7f96b7b50489  yb::master::enterprise::CatalogManager::DeleteCDCStreamsForTables()
    @     0x7f96b7994560  yb::master::CatalogManager::DeleteYsqlDBTables()
```
CDC grabs `mutex_` after grabbing `table->LockForWrite()` .  A second DeleteYsqlDBTables invocation has `mutex_` and is stuck waiting for `table->Lock`.  
```
    @     0x7f96ad499e4f  yb::RWCLock::WriteLock()
    @     0x7f96b7993cac  yb::master::CatalogManager::DeleteYsqlDBTables()
    @     0x7f96b7994f2f  yb::master::CatalogManager::DeleteYsqlDatabaseAsync()
```

In this use case, the Table lock isn’t necessary because it’s trying to delete a completely different namespace.

There are a couple areas where we do recursive locking between a Table and it's Index Table.  This potentially violates the table locking order, so it's a known deadlock issue.  In particular:
1. `CatalogManager::DeleteTableInMemory` : table->LockForWrite() then (**indexed_table).LockForRead();
2. `CatalogManager::DeleteTableInMemory` : Also grabs `mutex_` AFTER grabbing the table lock

**Comment by tedyu** [comment]
`trying to delete a completely different namespace.`
With #10139 fixed, the above wouldn't happen any more.
