### ISSUE TITLE
[DOC] Platform health check ysql connectivity fails when authentication is enabled

### ISSUE THREAD

**Issue by mastannpu87** [yugabyte/yugabyte-db#10095]
Mark worked with customer where he had enabled authentication on a platform universe by setting the ysql_auth tserver flag to true and changing their ysql_hba_conv_csv as appropriate. However, once he enabled health checks they started getting this error:

Error executing command ['ssh', 'yugabyte@<target IP>', '-p', '22', '-o', 'StrictHostKeyChecking no', '-o', 'ConnectTimeout=10', '-o', 'UserKnownHostsFile /dev/null', '-o', 'LogLevel ERROR', '-i', u'/opt/yugabyte/yugaware/data/keys/c7176111-373f-4909-9071-6e9d8a18e222/onpremises-key.pem', 'set -o pipefail; /app/yugabyte/tserver/bin/ysqlsh -h <target IP> -p 5433 -U yugabyte -c "\conninfo"']: timeout occurred

We asked them to modify ysql_hba_conv_csv to allow for local trust for user yugabyte and that solved the problem.

Can we do the following to avoid others from running into this:

- Update the documentation to reflect that changing ysql_hba_conv_csv can affect the health check working and list what local trust authentication they should have as the first entry for this flag.

**Comment by lizayugabyte** [comment]
@mastannpu87 We have the following articles that describe the mentioned security/authentication settings in detail:

- https://docs.yugabyte.com/latest/secure/tls-encryption/tls-authentication/
- https://docs.yugabyte.com/latest/secure/enable-authentication/ysql_hba_conf-configuration/

All flags in platform are set via the Flags dialog for master and t-server (name-value pairs). The Health check UI is not described in detail anywhere, as it's pretty intuitive. Would adding a note and providing links to the existing docs be sufficient, in your opinion?
