### ISSUE TITLE
pick better auto-defaults for max number of compactions

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#101]
On systems with few CPU cores, our defaults for number of concurrent compactions (4) is a bit too much.

Proposal: Unless explicitly overridden via `rocksdb_max_background_compactions` gflag, let's configure the default max for number of compactions to be something based on number of cores:

  ```
  if cpus <= 4, then  1;
  else if cpus <= 8 then 2;
  else if cpus <= 32 then  3;
  else 4
  ```

**Comment by bbaddepudi** [comment]
Fixed in [956deb2](https://github.com/YugaByte/yugabyte-db/commit/956deb2c1f4f1f4d1c6e360be8223af86f241b9b)
