### ISSUE TITLE
[YSQL] Support for Materialized Views

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10102]
Jira Link: [DB-745](https://yugabyte.atlassian.net/browse/DB-745)
This is a master issue for tracking the progress of MATERIALIZED VIEWS

### Phase 1 - Support create, drop, refresh materialized view

| Status | Feature        | GitHub Issue | Comments |
| :--: | --------------- | ------------------  | ------------------ |
| ✅ | CREATE, DROP Materialized View |  #10509 | Handled like any other YB relation |
| ✅ | REFRESH Materialized view (non-concurrent) | #10510 | We create a new relation which stores the updated data, and then we swap the storage of the old relation with that of the new relation |

### Phase 2 - Support concurrent refreshes 
| Status | Feature        | GitHub Issue | Comments |
| :--: | --------------- | ------------------  | ------------------ |
| ✅   | REFRESH Materialized View (concurrent) | #10511 | We load the data into a temporary relation, construct a diff relation of the new data and the old matview data, and perform deletes and inserts accordingly. |

### Phase 3 - Support alters

| Status | Feature        | GitHub Issue | Comments |
| :--: | --------------- | ------------------  | ------------------ |
| ⬜️   | ALTER Materialized View | #10512 | |

**Comment by fizaaluthra** [comment]
This is a master issue for tracking the progress of MATERIALIZED VIEWS

### Phase 1 - Support create, drop, refresh materialized view

| Status | Feature        | GitHub Issue | Comments |
| :--: | --------------- | ------------------  | ------------------ |
| ⬜️ | CREATE, DROP Materialized View |  #10509 | Handled like any other YB relation (in progress) |
| ⬜️ | REFRESH Materialized view (non-concurrent) | #10510 | We create a new relation which stores the updated data, and then we swap the storage of the old relation with that of the new relation (in progress) |

### Phase 2 - Support concurrent refreshes 
| Status | Feature        | GitHub Issue | Comments |
| :--: | --------------- | ------------------  | ------------------ |
| ⬜️   | REFRESH Materialized View (concurrent) | #10511 | In progress |

### Phase 3 - Support alters

| Status | Feature        | GitHub Issue | Comments |
| :--: | --------------- | ------------------  | ------------------ |
| ⬜️   | ALTER Materialized View | #10512 | |
