### ISSUE TITLE
[PITR][YCQL] Master-Leader is missing in Universe.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#10103]
**Universe**: http://10.9.137.216/universes/4c1b0cea-c10f-43d6-a2f0-8f23e1675dfa/nodes
**DB**: 2.6.2.0-b6
**Steps**:
1. Create keyspace(k2) and table(tab2) insert some data into table
2. Create a snapshot schedule - [ bin/yb-admin -master_addresses comma-separated-master-ips create_snapshot_schedule 2 6 ycql.k2 ]
3. Insert some data again into table(tab2) and restore back to 1 min - restore works fine
4. Create another table(tab3) and get the absolute time[abs-time]
5. Insert some data to table(tab3) and delete tab2 table
6. Wait for sometime(2min) Restore back to 20min - displays error message, which is expected. 
7. Then restore back to 5 min(with relative time), again restore back with absolute time [abs-time](which is collected at step4)

**Expected**: If user uses restore cmd multiple times, it should give proper error message instead of hitting into Master-Leader.

**Comment by sanketkedia** [comment]
This was fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/fd15c4eee179b0d4996392e1a25f31d41b2074b5) to actually allow for forward restores of the above type.
