### ISSUE TITLE
[Driver] YSQL server list refresh sequence/interval

### ISSUE THREAD

**Issue by srinivasa-vasu** [yugabyte/yugabyte-db#10128]
Jira Link: [DB-4782](https://yugabyte.atlassian.net/browse/DB-4782)
While testing the client-side resiliency from a driver standpoint, encountered the following case

**Initial configuration:**
- Connections per node limited to - 'X' (let's say 50)
- Steady-state would generate roughly 60-70% of the traffic continuously (60-70% out of the max connections would be active). Let's say in a cluster with 3 nodes - out of 150 connections, roughly 80-90 connections would be pre-initialized and kept active.
(assumed 3 node cluster here, but it could vary)

**Use case execution flow**

1. Steady-state

- all 3 nodes (node#1, node#2, node#3) were running 
- connections were distributed between 3 nodes

2. Isolate node#3

- connections served by node#3 became invalid 
- new compensating connections were distributed to the surviving nodes (node#1 and node#2). Since the two nodes can accommodate up to 100 connections, 80 was still within the upper threshold limit.

3. node#3 joins the cluster in a few mins (in 1-2 mins). Trigger a graceful shutdown of node#2.

Though we have 2 active nodes (node#1 and node#3), the smart driver active server list has only node#1 as it has already invalidated node#3 (when it got separated from the cluster) and node#2 (when it went down). This list takes some time to get refreshed. In this case, a single node couldn't accommodate the entire client traffic and ended up with a lot of connection exceptions for some time.

The exception encountered in this case didn't signify the real issue as it was momentarily and got eventually resolved after the next refresh.

It would be nice to refresh the active server list whenever there is a connection exception to validate whether it is to do with the outdated list or the cluster itself has really hit the max limit.

**Comment by kneeraj** [comment]
@srinivasa-vasu please test with the latest driver. This should be resolved:
Try this version:

<dependency>
      <groupId>com.yugabyte</groupId>
      <artifactId>jdbc-yugabytedb</artifactId>
      <version>42.3.0</version>
</dependency>

BTW a newer version which resolves this issue: https://github.com/yugabyte/yugabyte-db/issues/10894
will also be available soon.
