### ISSUE TITLE
[YSQL] yb-ctl should report the amount of time taken to run initdb

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1012]

**Comment by m-iancu** [comment]
Closing as no longer relevant. After https://github.com/yugabyte/yugabyte-db/commit/bdec7bdc2b48301c6b097cf7f54e5bb425bdc2e3 `intdb` no longer runs as part of `yb-ctl`. See also issues https://github.com/yugabyte/yugabyte-db/issues/1411 and https://github.com/yugabyte/yugabyte-db/issues/1158.
