### ISSUE TITLE
how to stop cluster?

### ISSUE THREAD

**Issue by warmbreeze33** [yugabyte/yugabyte-db#10124]
I have installed a cluster with three nodes in my vms,  use flowing commands:
./bin/yb-master \
  --master_addresses 192.168.55.1:7100,192.168.55.2:7100,192.168.55.3:7100 \
  --rpc_bind_addresses 192.168.55.1:7100 \
  --fs_data_dirs "/home/yuga/disk1,/home/yuga/disk2" \
  --placement_cloud aws \
  --placement_region us-west \
  --placement_zone us-west-2a \
  >& /home/yuga/disk1/yb-master.out &
....

but how can i stop the cluster?  which command can do this?

**Comment by ddorian** [comment]
> but how can i stop the cluster? which command can do this?

You can jus kill the processes.

**Comment by warmbreeze33** [comment]
@ddorian  Thanks
