### ISSUE TITLE
Allow for data directory changes post cluster creation

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#10137]
Jira Link: [DB-752](https://yugabyte.atlassian.net/browse/DB-752)
We currently do not support changing data directories after cluster creation (at runtime). Users that attempt to do so will run into issues for the nodes whose directories have moved. Data directory flags of interest:

- `data_dir` for **yugabyted**
- `data_dir `for **yb-ctl**
- `fs_data_dirs` for **yb-tserver**
- `fs_data_dirs` for **yb-master**

**Comment by rthallamko3** [comment]
@mrajcevic01 , What was the motivation of the ask above? It is hard to change the drives that are part of the data directory while the system is running. It needs to be done in a non-invasive way (cannot be runtime). I do believe we support adding new drives.

**Comment by mrajcevic01** [comment]
@rthallamko3 this was due to a user ask over community slack. Its been some time so I do not recall the details clearly. If we have not received additional asks for this and we have added the disclaimer I filed for [here](https://github.com/yugabyte/yugabyte-db/issues/10138) we can probably close this out

**Comment by rthallamko3** [comment]
Thanks @mrajcevic01 , Closing this for now.
