### ISSUE TITLE
[Docs] Async examples should include adding tables

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#10135]
The [Asynchronous Replication (2+ regions)](https://docs.yugabyte.com/latest/explore/multi-region-deployments/asynchronous-replication-ysql/) in YSQL section in our docs has an example of creating an initial async replication of tables across two regions, however does not call out how to add tables to that replication. I believe it would be helpful to users to add an additional subsection that shows an example of this, in context of the example in the current page. That would look like this:

`yb-admin -master_addresses <consumer-master-addresses> alter_universe_replication <producer-universe_uuid> add_table <producer-table-ids>`

This syntax can be found [here](https://docs.yugabyte.com/latest/admin/yb-admin/#alter-universe-replication) in the **yb-admin** section of the docs. I also suggest linking to the [Master Follower Deployment Commands](https://docs.yugabyte.com/latest/admin/yb-admin/#master-follower-deployment-commands) within the **yb-admin** section of the docs under the subsection [What's Next ](https://docs.yugabyte.com/latest/admin/yb-admin/#master-follower-deployment-commands)for additional commands regarding async.

**Comment by lizayugabyte** [comment]
@mrajcevic01 Is this applicable to the [YCQL page](https://docs.yugabyte.com/preview/explore/multi-region-deployments/asynchronous-replication-ycql/) as well?

**Comment by lizayugabyte** [comment]
Closed by https://github.com/yugabyte/yugabyte-db/pull/14300
(couldn't link these two tickets for some reason)

**Comment by mrajcevic01** [comment]
> @mrajcevic01 Is this applicable to the [YCQL page](https://docs.yugabyte.com/preview/explore/multi-region-deployments/asynchronous-replication-ycql/) as well?

@lizayugabyte Yes I believe so since all the xCluster commands are against table uuids and the master process
