### ISSUE TITLE
[doc] Yugabyted Reference doc improvement request

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#10132]
Marko Rajcevic - slack:
Our yugabyted docs https://docs.yugabyte.com/latest/reference/configuration/yugabyted/#examples have a section titled Examples where it walks through creating a single node cluster, destroying clusters etc. They have set the base directory as --base_dir=/Users/username/yugabyte-2.3.3.0/data1 however i think this is a bit misleading since the base directory houses the data, logs, and conf directories. When I was going through the docs I ended up deleting the data directory (using the destroy method called out) and wondering why the node was still up. It wasnt until I looked at the Examples section again that I realized that the called out data1 was really the base directory. Think our example in the fault tolerance section https://docs.yugabyte.com/latest/explore/fault-tolerance/macos/#6-optional-clean-up has a better naming convention for the base directory that we should use to eliminate confusion.

**Comment by polarweasel** [comment]
I really like how the fault-tolerance page skips from #4 to #6, too ;-)
