### ISSUE TITLE
[Docs] Call out YSQL Read Replicas as BETA for all Read Replica docs

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#10145]
Looking into Read Replica documentation I realized that YSQL Read Replicas are in BETA, however this was not realized until I stumbled upon it in [multi-region deployments subsection](https://docs.yugabyte.com/latest/explore/multi-region-deployments/read-replicas-ysql/) under EXPLORE. This is the only area in the docs where it is called out. It is not called out under the DEPLOY section [here](https://docs.yugabyte.com/latest/deploy/multi-dc/read-replica-clusters/#root) nor in the Platform docs [here](https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/read-replicas/#root). This issue is to add a disclaimer in any Read Replica docs to either direct back to the EXPLORE section or call out a NOTE that this feature is still in BETA for YSQL. Would be a good practice to do this for all features where at least one API is in BETA.

**Comment by lizayugabyte** [comment]
This also requires editing the platform page for clarity and updating screenshots

**Comment by lizayugabyte** [comment]
@sridhar-yb @ymahajan Is read replica still in Beta for Platform?   If so, which release is it going out with?

**Comment by mrajcevic01** [comment]
Looks like YSQL Follower Reads go hand in hand with YSQL Read Replicas. Both are required to have the functionality work, however the line separating the two seems blurry
