### ISSUE TITLE
geo: Add ability to create new txn status tables

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10157]
Context: #9980

We need to be able to create new txn status tables and set custom placement policies for them.
- For creating them, we already have `CatalogManager::CreateTransactionsStatusTableIfNeeded`, so we could figure out how to reuse that / retrofit that. Perhaps a new yb-admin command that creates a similar CreateTableRPC.
- For setting custom placement, we already have a yb-admin command to do just that, `modify_table_placement_info`, per table, which Deepthi added back when we added YCQL support for geo-partition.

**Comment by bmatican** [comment]
An easy way to test this locally could be by using custom placement info per tserver. We can start a 1 node cluster in zone A, then start 2 new TS, one in zone B and 3rd in zone C. Then we can update the cluster placement to RF3 across zones A,B,C. This will apply to all new tables by default. Finally, we can create 3 new txn tables and then set placement on them to RF1 and place them 1 each in zones A, B and C.

In a unit test, this should also be pretty easy to replicate, as there we have explicit ways to start tservers with custom flags. cc @sanketkedia maybe for an example of test with custom placement.

**Comment by deeps1991** [comment]
Small minor point: 
modify_table_placement_info basically calls AlterTable under the hood to change the placement policy. Maybe its an easier user workflow to make the new yb-admin command we are going to use to create the TransactionStatusTablet itself to take placement options for the new table. Code from modify_table_placement_info can be refactored and reused for this purpose.

**Comment by es1024** [comment]
Added with 10f931b.
