### ISSUE TITLE
geo: Ability to select local vs global txn requirements in the context of geopartitioning

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10159]
Context: #9980, #10158

As part of adding geopartitioning to the txn status tables, one requirement we want to uphold is that a transaction that needs to touch global data cannot be executed against a txn status tablet that is geo bound to a single fault domain.

What this translates to is
- We need a way to mark that a txn is global or local. We can start with a bool session variable for now.
- If the user starts a local txn, but then proceeds to do writes against global tables, we probably want to add and throw a new type of error.
- The PG layer needs to flow this local vs global information to the TS layer, at the time of picking the txn id, so we can select an appropriate tablet.

Open questions: For local txns, we also need to decide what the placement rules are:
  - We have 3 levels of placement: cloud/region/zone. Do we agree that the locality should be at the region level?
  - Do we need PG to send any info about the placement it wants, or can we just assume that it has already selected the correct TS and then we can use that TS's placement info?

**Comment by es1024** [comment]
Added with 17484ff.
