### ISSUE TITLE
[tools] `list_snapshots` should also print the time of each snapshot

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#10171]
Currently, the `list_snapshots` yb-admin command only prints the snapshot id and the state of the snapshot. It should also print more information such as the time of the snapshot. This is already tracked and filled for every snapshot in its state structure [see [snapshot_state.cc](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/snapshot_state.h)]. We just need to expose it.

**Comment by bmatican** [comment]
TL;DR update from @OlegLoginov 
```
list_snapshot has 2 output modes, tabular and JSON
in JSON mode, we can add more fields easily, without worrying about yb_backup, as it will just take out only the necessary fields! but we should be careful not to change or add unprintable symbols, as yb_backup can’t consume those
in the normal non-JSON mode, we don't have to worry about yb_backup
```

**Comment by kapilagrawal95** [comment]
Hi, I'd like to take up this issue. Can you help me get started? @bmatican , @sanketkedia

**Comment by viko600** [comment]
Hi @bmatican. I want to give it a go. #10854
