### ISSUE TITLE
Setup_universe_replication should check IDs

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#10185]
Currently in CatalogManager::ValidateTableSchema, the only schema checks we perform are auto result = info->schema.EquivalentForDataCopy(resp.schema()); as well as verifying that colocated tables have the same tableoids.

However there are some edge cases for schema changes that are not checked here, for example dropping a column and then adding it back:

// PRODUCER:
jhe=# create table test(i int primary key, b int);
CREATE TABLE

// CONSUMER:
jhe=# create table test(i int primary key, b int);
CREATE TABLE
jhe=# alter table test drop column b;
ALTER TABLE
jhe=# alter table test add column b int;
ALTER TABLE

// setup universe replication - succeeds

// PRODUCER:
jhe=# insert into test values (1,1);
INSERT 0 1

// CONSUMER:
jhe=# select * from test;
 i | b
---+---
 1 |
(1 row)

In this case, the name + type match but the ID #s don't. This is a subtle bug, because the schema can exactly match but still not work. Backup addresses this by running an ALTER table and forcing all the IDs to match. It also assumes an empty table. This would be pretty expensive in the active replication scenario.

1. We need to change the code to validate that all columns + ID#s match and return an error on `setup_replication` if not.  
2. We need to validate that performing an Import Snapshot from the Producer table (after getting ID mismatch error in step 1) readjusts all the IDs.  The `setup_replication` should succeed after that.

**Comment by dotyjim-work** [comment]
@nspiegelberg - This covers the setup case - do we have an issue (I was not successful in finding one) where we discuss checking schema's after we alter tables? I think I only see a reference to this idea [here](https://github.com/yugabyte/yugabyte-db/issues/4571#issuecomment-953300227), but its listed as "OP script".
