### ISSUE TITLE
[xCluster] Locality-Aware Placement for M:N tablet mapping in setup_replication

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#10186]
Currently, setup_replication only does tablet mapping between Consumer & Producer clusters in the 1:1 use case.  For the M:N use case, a naive round-robin strategy is used.  It would be useful to have a best-effort mapping instead.

In addition to getting the list of tablets on the Producer side, get the start & end rowkey. Compute the max overlap in a rowkey interval with a local tablet and assign accordingly (only assign RR on failure).
- Add an Interval Overlap Calculation
-- Calculate a set of candidate tablets on the Consumer that have their [StartKey_C, EndKey_C] within the Producer’s [StartKey_P, EndKey_P] range.
-- For each candidate, determine the overlap window
--  [StartKey_O, EndKey_O] == [ max(StartKey_C, StartKey_P), min (EndKey_C, EndKey_P) ].
-- Pick the candidate with max(EndKey_O - StartKey_O)

We might be able to approximate this faster using a middle key algorithm:

- For a Producer tablet, calculate the middle key.  Assign to the Consumer tablet that contains the middle key.
Use the logical MiddleKey, instead of GetEncodedMiddleSplitKey(), for a fully in-memory operation.

This task is the first step towards adding this heuristic to the xDC + tablet splitting use case to keep reasonably good locality while allowing their split keys to diverge.  See the Tablet Splitting + xDC Design Doc: https://docs.google.com/document/d/1MlhwjqSypnP8i6r7DJcm85GNIaguV51ZqiekRIyf0eU

**Comment by hulien22** [comment]
Some code pointers to help out, currently we process tablet mappings in two locations:

1. At the end of setting up replication, we initialize the consumer. As part of this, we fetch all the consumer table's tablets and compare with the producer tablets to create the tablet mapping. If it is a M:N setup, then this assignment is done round-robin: https://github.com/yugabyte/yugabyte-db/blob/b7d6a7d04190fbcebdc298913b266188155d5361/ent/src/yb/master/cdc_consumer_registry_service.cc#L83
2. For tablet splitting, when a consumer side tablet splits, we need to re-assign the parent tablet's pollers. This is currently also done in a naive round-robin fashion: https://github.com/yugabyte/yugabyte-db/blob/b7d6a7d04190fbcebdc298913b266188155d5361/ent/src/yb/master/cdc_consumer_registry_service.cc#L114-L130

Ideally we can use the same logic in both these cases, but tbd.. Tablet splitting already provides the start and end keys for all the producer tablets, but some work would be required if we want these keys for the setup case as well.

**Comment by bmatican** [comment]
@hulien22 to confirm, does this mapping also dynamically change, at runtime, based on consumer cluster changes, eg: add/remove nodes, LB moving tablets around, etc?

**Comment by hulien22** [comment]
The mapping won't change since its purely a tablet id : tablet id mapping. So moving tablets around won't change anything, but splitting tablets does as that is creating new tablets that need to be added/removed from the mapping
