### ISSUE TITLE
[docdb] Make read_buffer_memory_limit be a percentage of server memory rather than total RAM

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10207]
Currently `read_buffer_memory_limit=-5` defaults to 5% of total memory. However, for the master, our default is that it uses 10% of total memory. This means the read buffers could end up with 50% of total master memory! This would clearly lead to the master hitting its hard memory limit.

Likely this is the root cause for things like #9528 and other similar cloud reported issues.

Sergei's thought is that another contributing factor is the number of YSQL connections, which is probably fair, that we're now normally testing with more incoming connections!

**Comment by SrivastavaAnubhav** [comment]
Fixed by #10207

**Comment by SrivastavaAnubhav** [comment]
Fixed by #10207
