### ISSUE TITLE
Set statement_timeout on a per-user basis

### ISSUE THREAD

**Issue by dataindataout** [yugabyte/yugabyte-db#10205]
Postgres offers a way to set statement_timeout on a per-user basis through altering the role:
https://www.postgresql.org/docs/11/sql-alterrole.html

There is a known workaround to set the statement_timeout for a connection once it is established, but it would be helpful to set this at the role level.

**Comment by ddorian** [comment]
Hi @dataindataout 

This should be already possible like in normal PostgreSQL. Example:

```
yugabyte=# ALTER ROLE yugabyte SET statement_timeout = 5000;
```

And then open another shell and try doing:
```
yugabyte=# select pg_sleep(5);
ERROR:  canceling statement due to statement timeout
yugabyte=# select pg_sleep(4);
 pg_sleep 
----------
 
(1 row)

```

Tested on 2.9.0.0
