### ISSUE TITLE
Add Deadlock Detection to Sys Catalog Entities

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#10214]
Jira Link: [DB-1120](https://yugabyte.atlassian.net/browse/DB-1120)
For debug and SDET testing, it would be useful to have an assertion that fires when locks on Sys Catalog objects happen out of order.  In particular, Table and Tablet objects are regularly acquired in multiples and need to happen in ascending ID order.  This task would ential adding a debug class to `catalog_entity_info.h` that stores a thread-local set of locks and asserts if ReadLock or WriteLock is called for an ID that is not ascending.  This task is slightly different than a groupLock class because it will catch instances where locks are being acquired at different levels of the call stack.

**Comment by lingamsandeep** [comment]
TSAN deadlock detection was sufficient to catch a large set of issues, so for now this proposal has been abandoned.
