### ISSUE TITLE
[docdb] cluster balancer: lower x-AZ traffic when remote bootstrapping new nodes

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10217]
from @kmuthukk 
> In deciding which tablet to move.. today, on a per-table basis we pick the most loaded server for that table.. and then pick a random tablet to move from that server's most loaded disk. But what if we, in addition to above, took tablet leadership into consideration and picked a tablet whose current leader is in the same zone as the target node. That might be a fairly quick & safe enhancement , yet a useful change that should significantly help reduce the number of RBSes that have to go cross AZ in the common case.

**Comment by bmatican** [comment]
Anubhav, this is work on the master LB component. The code change might also not be too involved, but it will be a good opportunity to explore the test framework as well, for validating the change. Feel free to sync up with @sanketkedia or @hulien22 for this.

**Comment by SrivastavaAnubhav** [comment]
Closed by ea058ad
