### ISSUE TITLE
[PITR-YSQL]: Restore after drop table fails when the drop is preceded by DDL commands on the table

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10215]
Steps:
1. Create a table and insert data into it. 
2. Run DDL commands to Rename columns
3. Add a new column
4. Insert some data into the table
5. Dropped column
6. Did a restore to the state before Step 1
7. Dropped table.
8. Did a restore to the state in step 6
*Issue:* The restore fails and this is the error reported by the console: ERROR: catalog is missing 1 attribute(s) for relid 16439

[yugabyte@ip-x-x-x-x tserver]$ bin/yb-admin -master_addresses 1.1.1.1,1.1.1.1,1.1.1.1 restore_snapshot_schedule 20c9f115-209b-486a-863b-d593748077de 1633603219496575
{
    "snapshot_id": "e6bbc357-b18d-4f22-a6d7-127e6c992522",
    "restoration_id": "7b182447-5fbf-4ba4-91e5-af9f15eb2b78"
}

Timestamp attempted at: 1633603219496575

Universe ID: 9dd6f9b4-e9ce-4002-8765-7a1e56b42a6a

Please note that this bug can be reproduced with a single DDL command before the table drop.

**Comment by sanketkedia** [comment]
Closed by [commit](https://github.com/yugabyte/yugabyte-db/commit/ac351ab3e255a3e86fdb5632066be85fc8452ec2)
