### ISSUE TITLE
[docdb] PITR: Improve master and tserver admin UI to incorporate HIDDEN tables

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#10226]
HIDDEN tables were introduced in PITR. Basically they are normal running tables not exposed to the client. This means that while underneath, it will continue to heartbeat, be load balanced, etc. a user-facing query will not have this table. 

Currently, we don't have any visibility into these types of tables in the master/tserver admin. They just show up as Running tables in the UI with no information about their HIDDEN nature. To display them we might need some middle ground. For example, in the `/tablet-servers` UI, we need to keep showing all the tablets as they’re relevant for LB purposes, etc. but in the `/tables` endpoint, we could add some info that they are hidden for PITR, or hide them and show them only if using a URL param? 

Similarly, on the tservers page, we need to change `/tablets` and `/tables` endpoints to show some info about their HIDDEN nature. cc @bmatican as this could be another good starter task.

**Comment by bmatican** [comment]
This would be a great starter task, to try out PITR, get familiar with the information we display in our debug UIs, while also making some light changes to these UIs, on both the master side (`src/yb/master/master-path-handlers.cc`) and the tserver side (`src/yb/tserver/tserver-path-handlers.cc`).

Feel free to lean on @sanketkedia for more input.
