### ISSUE TITLE
PITR: Restore fails with restore followed by alter table add constraint 

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10237]
1. Create a table without any primary keys. Note the absolute time. This is the point we will revert to.
2. Execute alter table with add constraint PK on one of the columns.
3. Try to delete the column which has been made PK. (Will not be possible owing to the PK constraint- Expected)
4. Restore snapshot to end of step 1.
5. Try to delete the column which was made PK in step 3(Expected: This time around it should be possible since we have restored the DB to a point where the PK constraint does not exist)
Actual: It says the table does not exist. But on executing a \dt we realize table exists and restore has failed. 

Restoration ID: 
[yugabyte@ip-12-11-9-16 tserver]$ bin/yb-admin -master_addresses 12.11.29.16,12.11.40.14,12.151.9.75 restore_snapshot_schedule 974f0c29-e5de-4869-bed0-85c31f8cfe08 1633691018939149
{
    "snapshot_id": "ed4db102-b4f7-40eb-9a70-94d1329bb3d0",
    "restoration_id": "a885dad0-b377-4181-b27b-e6e9247eeae1"
}
Console Dump:
four=# \dt
          List of relations
 Schema |   Name   | Type  |  Owner
--------+----------+-------+----------
 public | orders   | table | yugabyte
 public | products | table | yugabyte
 public | reviews  | table | yugabyte
 public | users    | table | yugabyte
(4 rows)

four=# CREATE TABLE cancelled_orders(
four(#   id         bigserial ,
four(#   created_at timestamp,
four(#   reviewer   text,
four(#   product_id bigint,
four(#   rating     int,
four(#   body       text
four(# );

CREATE TABLE
four=#
four=# alter table cancelled_orders add primary key(product_id);
ALTER TABLE
four=# alter table cancelled_orders drop column product_id;
ERROR:  Invalid argument: cannot remove a key column
four=# \dt
              List of relations
 Schema |       Name       | Type  |  Owner
--------+------------------+-------+----------
 public | cancelled_orders | table | yugabyte
 public | orders           | table | yugabyte
 public | products         | table | yugabyte
 public | reviews          | table | yugabyte
 public | users            | table | yugabyte
(5 rows)

four=# alter table cancelled_orders drop column product_id;
ERROR:  relation "cancelled_orders" does not exist
four=# \dt
              List of relations
 Schema |       Name       | Type  |  Owner
--------+------------------+-------+----------
 public | cancelled_orders | table | yugabyte
 public | orders           | table | yugabyte
 public | products         | table | yugabyte
 public | reviews          | table | yugabyte
 public | users            | table | yugabyte
(5 rows)

Observed in build: 2.9.1.0 build 132

**Comment by sanketkedia** [comment]
Since adding a primary key involves creating a unique index underneath, I think this should be the same as Issue#10256.

**Comment by sanketkedia** [comment]
Actually, if I try to create and drop a unique constraint and then restore to a point before the constraint was dropped, it is successful with the unique index getting created successfully after restore.

**Comment by kripasreenivasan** [comment]
Unable to reproduce this issue any more. Looks like the universe on which the issue manifested initially was not in a good state. Closing the issue.
