### ISSUE TITLE
Tserver hyperlinks show non-clickable dns based links instead of ips.

### ISSUE THREAD

**Issue by bbaddepudi** [yugabyte/yugabyte-db#1023]
@kmuthukk wrote:
When I start a cluster this way, *where `IP` is the private IP and not the loop back address 127.0.0.1*

`
$ ./yb-master --master_addresses $IP:7100 --fs_data_dirs $DATA_DIR --rpc_bind_addresses=$IP:7100 --replication_factor 1 >& $DATA_DIR/master.out &

$ ./yb-tserver --tserver_master_addrs $IP:7100 --fs_data_dirs $DATA_DIR --rpc_bind_addresses=$IP:9100  --start_pgsql_proxy >& $DATA_DIR/tserver.out &
`
And go to:

`http://10.9.123.137:7000/tablet-servers`

Why do I get hyperlinks of this form which don't work:

`ip-10-9-123-137.us-west-2.compute.internal:9000`

instead of:

`10.9.123.137:9000`

CC: @spolitov @bmatican

**Comment by kmuthukk** [comment]
@bbaddepudi:

If I pass `--webserver_interface $IP` to yb-master/yb-tserver then the TServer hyperlinks work fine. But still, a links for say "Cassandra RPCs" on the http://10.9.123.137:9000/utilz page still goes to http://0.0.0.0:12000/rpcz instead of http://10.9.123.137:12000/rpcz

**Comment by bbaddepudi** [comment]
The CQL/Yedis rpcz related links are controlled by proxy specific flags as for today. For example `cql_proxy_bind_address` controls CQL's `12000/rpcz`.

Also, was able to repro the webserver showing non-private-ip issue with the local `yb-ctl` by removing the line `"--webserver_interface {}".format(daemon_id.get_ip_address()),` from the `submodules/yugabyte-installation/bin/yb-ctl` file.

Tserver http addr:
<img width="520" alt="Screen Shot 2019-04-30 at 12 43 38 PM" src="https://user-images.githubusercontent.com/6334739/56988730-99471a00-6b45-11e9-823a-615421005226.png">

From tserver registration info, noticed that `http_addresses` are bound to different ip configs and we just pick the first (index 0) one by default.
`I0430 12:16:58.171648 16359424 ts_manager.cc:142] Registered new tablet server { permanent_uuid: "4eb908dd224d449ba492e87641e122b8" instance_seqno: 1556651808149069 } with Master, full list: [{4eb908dd224d449ba492e87641e122b8, 0x0000000116eeb218 -> { permanent_uuid: 4eb908dd224d449ba492e87641e122b8 registration: 0x000000011700fc50 -> common { private_rpc_addresses { host: "127.0.0.1" port: 9100 } http_addresses { host: "fe80::1%lo0" port: 9000 } http_addresses { host: "172.27.71.184" port: 9000 } http_addresses { host: "fe80::84e2:57ff:fec3:9d1d%awdl0" port: 9000 } http_addresses { host: "fe80::3dcf:c905:8bf9:9028%utun0" port: 9000 } http_addresses { host: "192.168.99.1" port: 9000 } http_addresses { host: "10.160.0.62" port: 9000 } http_addresses { host: "10.8.0.26" port: 9000 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } placement_uuid: "" } capabilities: 2189743739 placement_id: cloud1:datacenter1:rack1 }}]
`
Did some quick digging and noticed `sq_get_bound_addresses` is providing this info. We need to see how to pick the private ip. For example showing `172.27.71.184:9000` for tserver link would work.

Master http addr also shows similar http link issue:
<img width="1071" alt="Screen Shot 2019-04-30 at 12 41 37 PM" src="https://user-images.githubusercontent.com/6334739/56988629-5e44e680-6b45-11e9-86b3-b88baab338fa.png">

@bmatican @spolitov

**Comment by bbaddepudi** [comment]
@spolitov - hope you can take over https://phabricator.dev.yugabyte.com/D6464 for RPC proxy chnaged and drive the web proxy side as well. Thanks!

cc: @bmatican
