### ISSUE TITLE
PITR: Restore failure on adding foreign key constraint and restoring to a point before key addition

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10238]
1. Create a table without any Foreign keys. Make a not of the absolute timestamp.
2. Add a foreign key constraint with ALTER TABLE cancelled_orders ADD FOREIGN KEY (id) REFERENCES orders (id);
List the set of foreign keys using either of the two commands mentioned at the end of the description. It will return output as 1 key.
3. Restore the state of the DB to end of step 1.
4. List the set of foreign keys in the table.
**Issue:** The Foreign key constraint does not get removed.

**Command to list foreign keys:**
1. SELECT
    tc.table_schema,
    tc.constraint_name,
    tc.table_name,
    kcu.column_name,
    ccu.table_schema AS foreign_table_schema,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name
FROM
    information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name='<table_name>';
2. \d+ <tablename>

**Console Dump:**
five=# \d+ cancelled_orders
                                                            Table "public.cancelled_orders"
   Column   |            Type             | Collation | Nullable |                   Default                    | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+----------------------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('cancelled_orders_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                              | plain    |              |
 reviewer   | text                        |           |          |                                              | extended |              |
 product_id | bigint                      |           |          |                                              | plain    |              |
 rating     | integer                     |           |          |                                              | plain    |              |
 body       | text                        |           |          |                                              | extended |              |

five=# SELECT
five-#     tc.table_schema,
five-#     tc.constraint_name,
five-#     tc.table_name,
five-#     kcu.column_name,
five-#     ccu.table_schema AS foreign_table_schema,
five-#     ccu.table_name AS foreign_table_name,
five-#     ccu.column_name AS foreign_column_name
five-# FROM
five-#     information_schema.table_constraints AS tc
five-#     JOIN information_schema.key_column_usage AS kcu
five-#       ON tc.constraint_name = kcu.constraint_name
five-#       AND tc.table_schema = kcu.table_schema
five-#     JOIN information_schema.constraint_column_usage AS ccu
five-#       ON ccu.constraint_name = tc.constraint_name
five-#       AND ccu.table_schema = tc.table_schema
five-# WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name='cancelled_orders';
 table_schema | constraint_name | table_name | column_name | foreign_table_schema | foreign_table_name | foreign_column_name
--------------+-----------------+------------+-------------+----------------------+--------------------+---------------------
(0 rows)

five=#
five=# ALTER TABLE cancelled_orders ADD FOREIGN KEY (id) REFERENCES orders (id);
ALTER TABLE
five=# SELECT
    tc.table_schema,
    tc.constraint_name,
    tc.table_name,
    kcu.column_name,
    ccu.table_schema AS foreign_table_schema,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name
FROM
    information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name='cancelled_orders';
 table_schema |     constraint_name      |    table_name    | column_name | foreign_table_schema | foreign_table_name | foreign_column_name
--------------+--------------------------+------------------+-------------+----------------------+--------------------+---------------------
 public       | cancelled_orders_id_fkey | cancelled_orders | id          | public               | orders             | id
(1 row)

five=# \d+ cancelled_orders
                                                            Table "public.cancelled_orders"
   Column   |            Type             | Collation | Nullable |                   Default                    | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+----------------------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('cancelled_orders_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                              | plain    |              |
 reviewer   | text                        |           |          |                                              | extended |              |
 product_id | bigint                      |           |          |                                              | plain    |              |
 rating     | integer                     |           |          |                                              | plain    |              |
 body       | text                        |           |          |                                              | extended |              |
Foreign-key constraints:
    "cancelled_orders_id_fkey" FOREIGN KEY (id) REFERENCES orders(id)

five=# \d+ cancelled_orders
                                                            Table "public.cancelled_orders"
   Column   |            Type             | Collation | Nullable |                   Default                    | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+----------------------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('cancelled_orders_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                              | plain    |              |
 reviewer   | text                        |           |          |                                              | extended |              |
 product_id | bigint                      |           |          |                                              | plain    |              |
 rating     | integer                     |           |          |                                              | plain    |              |
 body       | text                        |           |          |                                              | extended |              |
Foreign-key constraints:
    "cancelled_orders_id_fkey" FOREIGN KEY (id) REFERENCES orders(id)

five=# SELECT
    tc.table_schema,
    tc.constraint_name,
    tc.table_name,
    kcu.column_name,
    ccu.table_schema AS foreign_table_schema,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name
FROM
    information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name='cancelled_orders';
 table_schema |     constraint_name      |    table_name    | column_name | foreign_table_schema | foreign_table_name | foreign_column_name
--------------+--------------------------+------------------+-------------+----------------------+--------------------+---------------------
 public       | cancelled_orders_id_fkey | cancelled_orders | id          | public               | orders             | id
(1 row)

five=#

Observed in build: 2.9.1.0 build 132

**Comment by sanketkedia** [comment]
This also doesn't reproduce. I am guessing you had a cluster that was already inconsistent by the time you started performing these tests. Let's sync up offline @kripasreenivasan on this.
