### ISSUE TITLE
PITR: Restore fails with DDL(Alter table ADD COLUMN IF NOT EXISTS clause)

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10234]
**Observed in builds: 2.8.0.0 b5, 2.9.1.0 b 132**
1. Create a database, table with a few columns and insert data and make note of the absolute timestamp after this.
2. Add a column with the ADD [COLUMN] [IF NOT EXISTS] clause for an existing column in the above table.
2. Add a column with ADD [COLUMN] [IF NOT EXISTS] clause for a new column.
3. Insert data for the new column in step 3
4. Add a second new column with ADD [COLUMN] [IF NOT EXISTS] clause 
5. Insert data for the new column in step 4
6. Hit restore to the point in Step 1
**Issue:**  Post the restore, this error is shown on console: ERROR:  relation "products" does not exist
7. Run a \dt to check the tables present.
You will actually see that the table is present but yet we are unable to access it post the restore.

Restore Id:
[yugabyte@ip-a-b-c-d tserver]$ bin/yb-admin -master_addresses 12.11.29.163,172.151.0.14,172.51.49.75 restore_snapshot_schedule 974f0c29-e5de-4869-bed0-85c31f8cfe08 1633674559214783
{
    "snapshot_id": "5a648fda-eeec-458d-9359-138278d92219",
    "restoration_id": "4033223e-34b8-4be4-915a-1da9093871e6"
}

Console Dump:
four=# ALTER TABLE products ADD COLUMN IF NOT EXISTS title text;
NOTICE:  column "title" of relation "products" already exists, skipping
ALTER TABLE
four=# ALTER TABLE products ADD COLUMN IF NOT EXISTS Col1 text;
ALTER TABLE
four=# update products set Col1='A';
UPDATE 9
four=# select * from products;
 id |       created_at        | category  |      ean      |      price       | quantity | rating |           title            |           vendor           | col1
----+-------------------------+-----------+---------------+------------------+----------+--------+----------------------------+----------------------------+------
 19 | 2016-11-06 23:27:12.642 | Doohickey | 4307721071729 | 42.6711673170755 |     5000 |    4.2 | Rustic Concrete Bottle     | Gibson, Turner and Douglas | A
 14 | 2017-12-31 14:41:56.87  | Widget    | 8833419218504 | 25.0987635927189 |     5000 |      4 | Awesome Concrete Shoes     | McClure-Lockman            | A
 16 | 2017-01-30 22:00:25.015 | Gadget    | 9633135585459 | 44.0735330325154 |     5000 |      4 | Incredible Bronze Pants    | Okuneva, Kutch and Monahan | A
 20 | 2017-08-25 18:18:36.649 | Gizmo     | 5099742600901 | 24.8843308336438 |     5000 |      4 | Intelligent Wooden Gloves  | Ora Monahan and Sons       | A
 17 | 2017-01-31 11:05:14.863 | Doohickey | 6704641545275 | 53.2907203119518 |     5000 |    4.3 | Enormous Wool Car          | Hilpert, Jacobs and Hauck  | A
 21 | 2016-06-30 07:30:53.303 | Gadget    | 5856636800041 | 40.3833440630454 |     5000 |    4.1 | Lightweight Wool Bag       | Heaney-Windler             | A
 18 | 2017-02-11 03:45:40.957 | Gadget    | 8909358907493 | 54.6020474739819 |     5000 |    4.4 | Lightweight Paper Bottle   | Wilkinson-Gottlieb         | A
 13 | 2016-05-24 23:09:46.392 | Gizmo     | 399569209871  | 75.0861692740371 |     5000 |      0 | Synergistic Steel Chair    | Mr. Tanya Stracke and Sons | A
 15 | 2016-09-08 14:42:57.264 | Widget    | 5881647583898 | 25.0987635927189 |     5000 |      4 | Aerodynamic Paper Computer | Friesen-Anderson           | A
(9 rows)

four=# ALTER TABLE products ADD COLUMN IF NOT EXISTS Col2 text;
ALTER TABLE
four=# update products set Col2='B';
UPDATE 9
four=# select * from products;
 id |       created_at        | category  |      ean      |      price       | quantity | rating |           title            |           vendor           | col1 | col2
----+-------------------------+-----------+---------------+------------------+----------+--------+----------------------------+----------------------------+------+------
 19 | 2016-11-06 23:27:12.642 | Doohickey | 4307721071729 | 42.6711673170755 |     5000 |    4.2 | Rustic Concrete Bottle     | Gibson, Turner and Douglas | A    | B
 14 | 2017-12-31 14:41:56.87  | Widget    | 8833419218504 | 25.0987635927189 |     5000 |      4 | Awesome Concrete Shoes     | McClure-Lockman            | A    | B
 16 | 2017-01-30 22:00:25.015 | Gadget    | 9633135585459 | 44.0735330325154 |     5000 |      4 | Incredible Bronze Pants    | Okuneva, Kutch and Monahan | A    | B
 20 | 2017-08-25 18:18:36.649 | Gizmo     | 5099742600901 | 24.8843308336438 |     5000 |      4 | Intelligent Wooden Gloves  | Ora Monahan and Sons       | A    | B
 17 | 2017-01-31 11:05:14.863 | Doohickey | 6704641545275 | 53.2907203119518 |     5000 |    4.3 | Enormous Wool Car          | Hilpert, Jacobs and Hauck  | A    | B
 21 | 2016-06-30 07:30:53.303 | Gadget    | 5856636800041 | 40.3833440630454 |     5000 |    4.1 | Lightweight Wool Bag       | Heaney-Windler             | A    | B
 18 | 2017-02-11 03:45:40.957 | Gadget    | 8909358907493 | 54.6020474739819 |     5000 |    4.4 | Lightweight Paper Bottle   | Wilkinson-Gottlieb         | A    | B
 13 | 2016-05-24 23:09:46.392 | Gizmo     | 399569209871  | 75.0861692740371 |     5000 |      0 | Synergistic Steel Chair    | Mr. Tanya Stracke and Sons | A    | B
 15 | 2016-09-08 14:42:57.264 | Widget    | 5881647583898 | 25.0987635927189 |     5000 |      4 | Aerodynamic Paper Computer | Friesen-Anderson           | A    | B
(9 rows)

four=# select * from products;
ERROR:  relation "products" does not exist
LINE 1: select * from products;
                      ^
four=# \dt
          List of relations
 Schema |   Name   | Type  |  Owner
--------+----------+-------+----------
 public | orders   | table | yugabyte
 public | products | table | yugabyte
 public | reviews  | table | yugabyte
 public | users    | table | yugabyte
(4 rows)

**Comment by sanketkedia** [comment]
Fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/ac351ab3e255a3e86fdb5632066be85fc8452ec2)
