### ISSUE TITLE
PITR: Restore fails to restore the DB when drop constraint precedes the restore_snapshot command 

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10239]
1. Create a table with a Foreign Key and note the absolute time at this point to back up to this point.
2. Drop the Foreign Key  constraint created in step 1.
3. Restore the back up to the end of step 1
Expected: The Foreign Key  must be present since we have rolled back to the state of step 1.
Actual: The Foreign Key is not present. The Drop constraint alter statement executed prior to the backup is still reflecting and has not been un-done.

Console Dump:
yugabyte=# \d+ sale_orders;
                                                            Table "public.sale_orders"
   Column   |            Type             | Collation | Nullable |                 Default                 | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+-----------------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('sale_orders_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                         | plain    |              |
 reviewer   | text                        |           |          |                                         | extended |              |
 product_id | bigint                      |           |          |                                         | plain    |              |
 rating     | integer                     |           |          |                                         | plain    |              |
 body       | text                        |           |          |                                         | extended |              |
Foreign-key constraints:
    "sale_orders_id_fkey" FOREIGN KEY (id) REFERENCES orders(id)

yugabyte=#  ALTER TABLE sale_orders drop constraint sale_orders_id_fkey;
ALTER TABLE
yugabyte=# \d+ sale_orders;
                                                            Table "public.sale_orders"
   Column   |            Type             | Collation | Nullable |                 Default                 | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+-----------------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('sale_orders_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                         | plain    |              |
 reviewer   | text                        |           |          |                                         | extended |              |
 product_id | bigint                      |           |          |                                         | plain    |              |
 rating     | integer                     |           |          |                                         | plain    |              |
 body       | text                        |           |          |                                         | extended |              |

yugabyte=# \d+ sale_orders;
                                                            Table "public.sale_orders"
   Column   |            Type             | Collation | Nullable |                 Default                 | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+-----------------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('sale_orders_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                         | plain    |              |
 reviewer   | text                        |           |          |                                         | extended |              |
 product_id | bigint                      |           |          |                                         | plain    |              |
 rating     | integer                     |           |          |                                         | plain    |              |
 body       | text                        |           |          |                                         | extended |              |

Observed in build: 2.9.1.0 build 132

**Comment by sanketkedia** [comment]
This again doesn't reproduce. Adding to the queue of items to do a sync up with @kripasreenivasan
