### ISSUE TITLE
docdb: [PITR-YSQL] PITR not working with Drop Index; table not getting restored pre-index drop

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10256]
**Observed in builds: 2.9.1.0 build 132, 2.8.0.0-b5**
- Create a table with an index and note the absolute time post table creation as this is the point we would like to revert to.
- Drop the index with the equivalent of the ysql command: drop index order_index;
- Execute \d+ <table_name> and check if the index is dropped.
- Do a Point in time restore to the point after step 1.
**Expected result:**
The dropped index should be restored and the index should be present in the table.
**Actual Result:**
The index continues to remain dropped even after the PITR making PITR ineffective with the drop index command.

**Comment by Arjun-yb** [comment]
Validated in 2.11.1.0-b300 and works as expected, closing this issue @sanketkedia
