### ISSUE TITLE
PITR: Restore on Unique Index not working

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10258]
**Observed in builds: 2.8.0.0 b5, 2.9.1.0 b 132**
1. Create a table with a unique index
2. Note the absolute time for PITR
3. Drop the unique index created in step 1.
4. Do a PITR to step 2.
**Issue:**
The restore fails and the DB gets into a bad state
select user_id from users;
ERROR:  column "user_id" does not exist

ten=# select user_id from users;
ERROR:  column "user_id" does not exist
LINE 1: select user_id from users;
               ^
ten=# \d+ users
                                                            Table "public.users"
   Column   |            Type             | Collation | Nullable |              Default              | Storage  | Stats target | Description
------------+-----------------------------+-----------+----------+-----------------------------------+----------+--------------+-------------
 id         | bigint                      |           | not null | nextval('users_id_seq'::regclass) | plain    |              |
 created_at | timestamp without time zone |           |          |                                   | plain    |              |
 name       | text                        |           |          |                                   | extended |              |
 email      | text                        |           |          |                                   | extended |              |
 address    | text                        |           |          |                                   | extended |              |
 city       | text                        |           |          |                                   | extended |              |
 state      | text                        |           |          |                                   | extended |              |
 zip        | text                        |           |          |                                   | extended |              |
 birth_date | text                        |           |          |                                   | extended |              |
 latitude   | double precision            |           |          |                                   | plain    |              |
 longitude  | double precision            |           |          |                                   | plain    |              |
 password   | text                        |           |          |                                   | extended |              |
 source     | text                        |           |          |                                   | extended |              |
Indexes:
    "users_pkey" PRIMARY KEY, lsm (id HASH)

Observed in build: 2.9.1.0 build 132

**Comment by Arjun-yb** [comment]
Validated in **2.11.1.0-b300**. Works as expected.

**Comment by Arjun-yb** [comment]
closing this issue @sanketkedia
