### ISSUE TITLE
PITR: Restore is not working for ALTER TABLE name OWNER TO 

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10255]
- Create a table and note the user it is assigned to.
- Make a note of the timestamp, this is the point we will revert to.
- Create a new user and assign the table created in bullet 1 to the new user. 
create user ben;
alter table products OWNER TO ben;
Execute \dt and ensure the ownership has changed.
- Execute the restore command
bin/yb-admin -master_addresses 172.151.29.163,172.151.40.164,172.151.49.75 restore_snapshot_schedule 073a8b7d-e764-4ffa-86d3-ab7819022527 1634019887404724
{
    "snapshot_id": "ca1cb184-9282-4c9f-ac72-c733e33684ba",
    "restoration_id": "7dcf4e5c-d2b5-457d-a990-e75b6ed06d81"
}
- Execute \dt
Issue: The ownership is not restored to the user in step 1.

Observed in build: 2.9.1.0 build 132

**Comment by sanketkedia** [comment]
This also doesn't reproduce. @kripasreenivasan can you validate this as well?

**Comment by kripasreenivasan** [comment]
This issue is not reproducible on a new universe.
