### ISSUE TITLE
How many prepared statements does YugaByte DB keep on server side for YCQL? Does it age out/remove less used one?

### ISSUE THREAD

**Issue by kkwong90** [YugaByte/yugabyte-db#1026]

**Comment by robertpang** [comment]
The number of prepared statements a YugaByte cluster maintains on the server side is configurable by the `cql_service_max_prepared_statement_size_bytes` gflag. The amount of memory a prepared statement takes depends on the number of factors like the number of columns in the table, etc. and typically consumes low teens of kB of memory or less per statement.

The default value of the gflag is 0 which means there is no limit. If a non-zero limit is set, the less used prepared statements will be aged out as expected.

**Comment by kmuthukk** [comment]
While this may not be an issue in practice, we should still have some limit by default so that older statements can age out and memory usage is bounded.

**Comment by robertpang** [comment]
The default `cql_service_max_prepared_statement_size_bytes` is now set to 128 MB.

**Comment by kmuthukk** [comment]
Fixed in #1406 .
