### ISSUE TITLE
[PITR-YCQL] Restore dropped index is not restoring properly.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#10274]
**DB Version**: '2.6.2.0-b36' and '2.9.1.0-b133`
**Steps**:
 1. Create table and insert some rows 
 2. Create an index(idx_1)
3. Collect absolute time(t1)
4. Delete created index(idx_1)
5. Restore back to time(t1)

**Observations**: 
1. If user describe table it shows the index(which was deleted and restored back)
2. Initially(before delete and restore) index is being displayed as

```
 CREATE INDEX idx_1 ON pitr.employees (department, employee_no)      
   WITH transactions = {'enabled': 'true'};
 
```
  But after restore it is being displayed as
  
```
   CREATE INDEX idx_1 ON pitr.employees (department, employee_no     
     WITH CLUSTERING ORDER BY (employee_no ASC)     
       AND transactions = {'enabled': 'true'}; 
```
3. If user runs a query plan it does a **seq scan** instead of **index only scan**
```
ycqlsh:pitr> explain select department from employees where department='Sales';

 QUERY PLAN
----------------------------------
 Seq Scan on pitr.employees
   Filter: (department = 'Sales')

```

**Note**: If user creates index with same name again in same session(where create index->delete index->restore index happed) it shows 

```
ycqlsh:pitr> create index idx_1 on employees(department);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Duplicate Object. Object 'pitr.idx_1' already exists
create index idx_1 on employees(department);
```
And after this if user exits from session and reconnects it and executes query plan it shows index only scan

**Comment by sanketkedia** [comment]
If you run the explain statement after running any "non-explain" query (any dummy select is also fine), the cache is refreshed and it works. So this isn't a PITR issue but the caching semantics is such currently.
