### ISSUE TITLE
[PITR-YSQL] Restore deleted partial index is not working as expected.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#10271]
**DB Version**: `2.9.1.0-b133`

**Steps**:
1. Create a partial index
2. Collect absolute time(t1)
3. Delete created partial index and restore back to time t1 and observe the behaviour.

**Observations**:
1. restore is not working as mentioned above ( index name is not being displayed if user describes the table) but if user creates index with same name again it errors out - ex: **ERROR:  relation "sal_idx_2" already exists**
2. UI shows the index name even after it failed to restore the deleted partial index.
3. scan is not using the index
```
demo=# explain select * from employees where salary > 40000;
                          QUERY PLAN
---------------------------------------------------------------
 Seq Scan on employees  (cost=0.00..102.50 rows=1000 width=72)
   Filter: (salary > 40000)
```
   
then I created one more with different name and output is
```
demo=# create index sal_idx_3 on employees(salary) where salary > 40000;
CREATE INDEX
demo=# explain select * from employees where salary > 40000;
                                   QUERY PLAN
---------------------------------------------------------------------------------
 Index Scan using sal_idx_3 on employees  (cost=0.00..102.00 rows=1000 width=72)
```

**Comment by sanketkedia** [comment]
Fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/ac351ab3e255a3e86fdb5632066be85fc8452ec2)

**Comment by Arjun-yb** [comment]
Validated in **2.11.1.0-b300**. Works as expected.
