### ISSUE TITLE
[PITR-YCQL] Restore dropped partial index is not restoring properly

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#10276]
DB Version: `2.6.2.0-b36` and `2.9.1.0-b133`
**Steps**: 
1. Create table and insert some rows 
2. Create partial index(idx_1)
3. Collect absolute time(t1)
4. Delete created index(idx_1)
5. Restore back to time(t1)

**Observations**: 
1.  If user describe table it shows the index(which was deleted and restored back)
2. Initially(before delete and restore) index is being displayed as 

```
CREATE INDEX idx_1 ON pitr.employees (salary, employee_no) WHERE salary > 30000    
   WITH transactions = {'enabled': 'true'};
```
3. But after restore it is being displayed as 
```
CREATE INDEX idx_1 ON pitr.employees (salary, employee_no) WHERE salary > 30000     
  WITH CLUSTERING ORDER BY (employee_no ASC)     
  AND transactions = {'enabled': 'true'};
```
4. If user runs a query plan it does a seq scan instead of index only scan
```
ycqlsh:pitr> explain select salary from employees where salary>30000;

 QUERY PLAN
----------------------------
 Seq Scan on pitr.employees
   Filter: (salary > 30000)  
```
**Note**: If user creates index with same name again in same session(where create index->delete index->restore index happed) it shows 
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Duplicate Object. Object 'pitr.idx_1’ already exists
create index idx_1 on employees(salary) where salary>3000;
                      ^^^^^^^^^
 (ql error -202)"
```

**Comment by sanketkedia** [comment]
Closed by [commit](https://github.com/yugabyte/yugabyte-db/commit/ac351ab3e255a3e86fdb5632066be85fc8452ec2)
