### ISSUE TITLE
[PITR-YCQL] Restore dropped unique index is not restoring properly

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#10275]
**DB Version**: `2.6.2.0-b36` and `2.9.1.0-b133` 

**Steps**:
 1. Create table and insert some rows 2. Create unique index(idx_1)
3. Collect absolute time(t1)
4. Delete created index(idx_1)
5. Restore back to time(t1)

**Observations**: 
1.  If user describe table it shows the index(which was deleted and restored back)
2. If user runs a query plan it does a seq scan instead of index only scan
```
ycqlsh:pitr> explain select name from employees where name='Arjun';

 QUERY PLAN
----------------------------
 Seq Scan on pitr.employees
   Filter: (name = 'Arjun')

```

**Note**: If user creates index with same name again in same session(where create index->delete index->restore index happed) it gives timeout error
`OperationTimedOut: errors={'172.151.62.227': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=172.151.62.227`
And after this if user exits from session and reconnect it and execute query plan it shows

```
ycqlsh:pitr> explain select name from employees where name='Arjun';

 QUERY PLAN
----------------------------------------------------------
 Index Only Key Lookup using pitr.idx_1 on pitr.employees
   Key Conditions: (name = 'Arjun')

```

**Comment by sanketkedia** [comment]
Closed by [commit](https://github.com/yugabyte/yugabyte-db/commit/ac351ab3e255a3e86fdb5632066be85fc8452ec2)
