### ISSUE TITLE
[Docs][Platform] Configuration of the AWS and GCP cloud provider section needs updated screenshots.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#10289]
The pages below need updated sceenshots with the missing information. 
On the AWS page, SSH port and SSH user information needs to be added in the configs section
https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws/#configure-aws
On the GCP page , details about the credential type, air gap installation, SSH port and Firewall tags need to be included.
https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws/#configure-aws
While the rest of the cloud provider pages looked alright , it may be a good idea to get them verified.

**Comment by lizayugabyte** [comment]
This was done during the product name changes
