### ISSUE TITLE
01106f08-12ea-4900-a144-75a7753acab5 Conflicts with higher priority transaction

### ISSUE THREAD

**Issue by gopi18dba** [yugabyte/yugabyte-db#10283]
Jira Link: [DB-1024](https://yugabyte.atlassian.net/browse/DB-1024)
Got below error while running the benchmark  performance for yugabyte with tpcc and chbenchmark.

Caused by: org.postgresql.util.PSQLException: ERROR: Operation failed. Try again.: [Operation failed. Try again. (yb/docdb/conflict_resolution.cc:73): 01106f08-12ea-4900-a144-75a7753acab5 Conflicts with higher priority transaction: bce07dae-e544-41fa-a4c1-14767cf89a72 (transaction error 3)].

link: https://github.com/cmu-db/benchbase

**Comment by ddorian** [comment]
Hi @gopi18dba 

This is an error that occurs because of our locking mechanism for concurrency: https://docs.yugabyte.com/latest/architecture/transactions/explicit-locking/. 

In this case, the error query/transaction has to be retried from the client layer.

**Comment by sushantrmishra** [comment]
Please let us know if issue still exists.

We also have added support for Read Committed isolation level GH https://github.com/yugabyte/yugabyte-db/issues/13557 . Using Read committed isolation level will reduce the these errors as well. 

**Documentation**: 
https://docs.yugabyte.com/preview/architecture/transactions/read-committed/

Please reopen this issue if you are still facing the issue.
