### ISSUE TITLE
Running on docker+ZFS, wrong filesystem type error

### ISSUE THREAD

**Issue by everyonce** [YugaByte/yugabyte-db#103]
Trying to run on docker, on ZFS system, throws error immediately when container is started:

`IO error (yb/fs/block_manager_util.cc:113): Failed to load FS layout: Could not open /mnt/disk0/yb-data/master/data/block_manager_instance: Wrong filesystem block size: Expected 131072 but was 1024`

Command I ran:
`docker run --name yb-master-n1 --privileged -p 7000:7000 --net yb-net -it yugabytedb/yugabyte:latest /home/yugabyte/bin/yb-master --fs_data_dirs=/mnt/disk0,/mnt/disk1 --replication_factor=3 --master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 --rpc_bind_addresses=yb-master-n1:7100`

**Comment by kmuthukk** [comment]
Thanks for reporting; taking a look... will keep you posted.

**Comment by kmuthukk** [comment]
CC: @hectorgcr.

**Comment by kmuthukk** [comment]
@mbautin , @hectorgcr:

Looks like when we create the `block_manager_instance` file which contains a proto, we save the block size based on the directory the file is in:

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/fs/block_manager_util.cc#L77

```
uint64_t block_size = VERIFY_RESULT(env_->GetBlockSize(DirName(filename_)));
...
 new_instance.set_filesystem_block_size_bytes(block_size);
```

And when we load the file, we verify that this value save in the proto is the same as the block size of the file.

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/fs/block_manager_util.cc#L110
```
  uint64_t block_size = VERIFY_RESULT(env_->GetBlockSize(filename_));
  if (pb->filesystem_block_size_bytes() != block_size) {
    return STATUS(IOError, "Wrong filesystem block size", Substitute(
        "Expected $0 but was $1", pb->filesystem_block_size_bytes(), block_size));
  }
```

Perhaps on the ZFS the env_->GetBlockSize() doesn't produce the same answer when called in a directory vs. a file. It looks like when called on the directory it returns 1K, and when called later on the file it returns 128K.

In any case, we don't seem to be use the filesystem_block_size_bytes() field anywhere else in code. perhaps we should just get rid of this assert anyway.

**Comment by kmuthukk** [comment]
Hi @everyonce:

Could you please post the output of:
```
% stat /mnt/disk0/yb-data/master/data/block_manager_instance
```
and
```
% stat /mnt/disk0/yb-data/master/data
```
in your setup?

And until you have a fix, are you able to try with a different FS such as ext4? Or, are you particular about trying YugaByte on ZFS. We haven't tested YugaByte on ZFS yet.

**Comment by everyonce** [comment]
I'm running ZFS on my main file server, and using it to serve docker containers.  I would like to yugabyte on it :-)

I'm running it in a container, and at the point that it bombs (like my original issue says) - it hasn't yet created those folders, it has only created /mnt/disk0 within the container.  I went and grabbed the container after it had exited, and was able to run `stat /mnt/disk0`:

```[root@a6a9ada6fd7f yugabyte]# stat /mnt/disk0
  File: ‘/mnt/disk0’
  Size: 2               Blocks: 1          IO Block: 131072 directory
Device: 3ch/60d Inode: 39396       Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-03-18 19:56:55.938661721 +0000
Modify: 2018-03-18 19:56:55.938661721 +0000
Change: 2018-03-18 19:56:55.938661721 +0000
 Birth: -
[root@a6a9ada6fd7f yugabyte]#```

**Comment by kmuthukk** [comment]
That's odd. Did any of the other files get created in /mnt/disk0?

```
ls -lR /mnt/disk0
```

If there's a log file under /mnt/disk0/yb-data/master/logs/yb-master.INFO, would be interested in seeing if there were any errors leading up to it. We will also try to repro this locally.

**Comment by everyonce** [comment]
Nope, nothing created under /mnt/disk0
including log files or any directories

**Comment by everyonce** [comment]
unrelated (not sure where to ask this) - how do I build a new docker image from source?  I can't find a Dockerfile...

**Comment by rkarthik007** [comment]
@everyonce - Ah just realized we have it in an internal devops repo. Will add it to the public repo itself.

Here is the file we use:
```
FROM centos:7
MAINTAINER YugaByte
ENV container=yugabyte-db

ENV YB_HOME=/home/yugabyte
WORKDIR $YB_HOME

COPY packages/yugabyte*.tar.gz /tmp
RUN tar -xvf /tmp/yugabyte*.tar.gz --strip 1
RUN bin/configure

# Expose the required ports.
EXPOSE 7000 7100 9000 9100 12000 11000 6379 9042 10100

# Create the data directories.
VOLUME ["/mnt/disk0", "/mnt/disk1"]
```

**Comment by rkarthik007** [comment]
@everyonce - actually do you mind opening a github issue to add the Dockerfile to the repo? This would be generally useful for folks. Thanks!

**Comment by kmuthukk** [comment]
Fixed in: https://github.com/YugaByte/yugabyte-db/commit/e27d4296c6e9d62e446450f87b4b4321836b8807
