### ISSUE TITLE
[docs] typo on kafka sink create topic command line

### ISSUE THREAD

**Issue by markwjeske** [yugabyte/yugabyte-db#10313]
on this page https://docs.yugabyte.com/latest/reference/connectors/kafka-connect-yugabytedb/#root

Step 3 for create topic has this

"~/yb-kafka/kafka_2.12-2.5.0/bin/kafka-topics.sh --create --zookeeper localhost:2181--replication-factor 1 --partitions 1 --topic test"

Note that there's no space after localhost:2181.    Should be

"~/yb-kafka/kafka_2.12-2.5.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test"

**Comment by ddorian** [comment]
This is no longer necessary because docs have been updated.
