### ISSUE TITLE
[docs] Add docs for yugabyteDB upgrade feature

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#10318]
We recently added the framework for upgrading the yugabyteDB using `upgrade_ysql`.

Add corresponding documents to  give steps how to use this feature.

**Comment by polarweasel** [comment]
Initial doc: https://docs.google.com/document/d/16YY_6FdJreNGuNdVTxBCHqk2WwJRKFzN-ddDSfTy9SM/edit

**Comment by polarweasel** [comment]
Applies to 2.8 and 2.11

**Comment by polarweasel** [comment]
Relates to #10651 (thanks @soccerties!)
