### ISSUE TITLE
YCQL index name is optional in Cassandra

### ISSUE THREAD

**Issue by BevanR** [YugaByte/yugabyte-db#1031]
Index name is [required in YCQL](https://docs.yugabyte.com/latest/api/ycql/ddl_create_index/#semantics) but [optional in Cassandra CQL](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateIndex.html). This causes problems with tools like ORM; https://github.com/masumsoft/express-cassandra/issues/197

**Comment by OlegLoginov** [comment]
Fixed.
