### ISSUE TITLE
[docdb]Imperva Integration - Cluster Tagging

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10330]
As it stands, we'd like to link traffic coming in on our socket with the cluster(s) to which a given node belongs.

Having Yugabyte be able to add a user-defined cluster tag into each line of the Postgres audit would be ideal, but it can also be added by the client to the rsyslog prenorm.

@ymahajan is aware of this request and was on the call.

**Comment by m-iancu** [comment]
Addressed in 71704c1.
