### ISSUE TITLE
[docdb]Imperva Integration - Ability to suppress or flag messages

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10331]
Sonar/Imperva's agentless solution to auditing Yugabyte SQL:

We use rsyslog on the Yugabyte host to monitor and redirect the Postgres audit logs to the Sonar gateway for parsing and ingesting.

We ask the client to create the file:

/etc/rsyslog.d/yugabyte_postgresql.conf

with the following:

#######################

module(load="imfile")
template(name="imfile_fwd_t" type="list") {
    constant(value="{ \"Server Port\":\"5433\" }")
    constant(value="PR3N0RM")
    property(name="rawmsg")
}

ruleset(name="imfile_to_gateway") {
    if not re_match($rawmsg,'(^[FEWIDT][0-9]+\s+[0-9:.]+\s+[0-9]+\s+[a-z_-]+.[a-z]+:[0-9]+)') then {
        action(type="omfwd"
            keepalive="on"
            protocol="tcp"
            target="xxx.xxx.xxx.xxx"
            port="xxxx"
            template="imfile_fwd_t")
        stop
    }
}

input(type="imfile" file="/root/var/data/yb-data/tserver/logs/postgresql*" tag="imfile" ruleset="imfile_to_gateway")

######################

The regex is to filter out info, error, warning lines that don't appear to be coming from Postgres audit itself:

I1015 16:06:53.811100  1972 pggate.cc:157] Reset YSQL bind address to 0.0.0.0:5432
I1015 16:06:53.811406  1972 server_base_options.cc:137] Updating master addrs to {127.0.0.1:7100}
I1015 16:06:53.811662  1972 mem_tracker.cc:282] MemTracker: hard memory limit is 2.219378 GB
I1015 16:06:53.811682  1972 mem_tracker.cc:284] MemTracker: soft memory limit is 1.886471 GB
I1015 16:06:53.813295  1972 thread_pool.cc:171] Starting thread pool { name: pggate_ybclient queue_limit: 10000 max_workers: 1024 }
I1015 16:06:53.814734  1979 async_initializer.cc:82] Starting to init ybclient
I1015 16:06:53.814932  1979 client-internal.cc:2283] New master addresses: [127.0.0.1:7100]
I1015 16:06:53.825726  1979 async_initializer.cc:86] Successfully built ybclient

########################

As it stands, we can deal with a regex, but it would be preferred if we don't have to maintain this part, as it runs the risk of adjusting to any change in format that Yugabyte may make.

Instead, Yugabyte could perhaps offers a way to limit these lines from appearing in the Postgres native audit trail.

Also, we have the client set this up per node.

@ymahajan was on the call so is aware

**Comment by m-iancu** [comment]
Addressed in f425def.
