### ISSUE TITLE
Tablet Splitting: Failed to alter table during tablet splitting. Relation does not exists

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#10351]
Steps to reproduce:
1. Run universe with flags
```
master:
    tablet_split_low_phase_size_threshold_bytes = 1342177
    enable_automatic_tablet_splitting = true
    tablet_split_low_phase_shard_count_per_node = 16
tserver:
    yb_num_shards_per_tserver = 1
```
2. Run sample-app workload
```
java -jar yb-sample-apps.jar --workload SqlDataLoad  --num_value_columns 40 --create_table_name split_a9b349 --num_writes -1 --num_threads_write 10 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000000
```
4. Tablets starts splitting
5. Alter table with ysqlsh (`13:24:18.762` in logs)

Actual:
- column does not change
- exception was thrown
```
$ ./bin/ysqlsh -d postgres -h 172.151.19.0 -p 5433 -c "ALTER TABLE split_a9b349 ADD V99 TEXT;" -A
ERROR:  relation "split_a9b349" does not exist
```
Logs:
[postgresql.log](https://github.com/yugabyte/yugabyte-db/files/7374380/postgresql.log)
[yb-master.log](https://github.com/yugabyte/yugabyte-db/files/7374382/yb-master.log)
[yb-tserver.log](https://github.com/yugabyte/yugabyte-db/files/7374383/yb-tserver.log)

**Comment by bmatican** [comment]
Passing to @SrivastavaAnubhav also, to retest after the ALTER part is fixed.

**Comment by SrivastavaAnubhav** [comment]
See #11508 for a comment.
