### ISSUE TITLE
[YSQL] Unexpected 'Try again' message

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#10375]
Jira Link: [DB-4796](https://yugabyte.atlassian.net/browse/DB-4796)
In case of catalog changes while statement processing SQL error will be followed with the `Internal error: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.` message. This confuses a bit in case of non retryable errors like `unique constraint violation`

Test scenario:

```
-- Connection 1
create table t(k int primary key);
insert into t values(1);
begin;
```

```
--Connection 2
create table t1(k int primary key);
alter table t1 add column v int;
```

```
--Connection 1
ERROR:  duplicate key value violates unique constraint "t_pkey"
DETAIL:  Internal error: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

**Comment by m-iancu** [comment]
This seems to work in latest:
Connection 1
```
yugabyte=# create table t(k int primary key);
CREATE TABLE
yugabyte=# insert into t values(1);
INSERT 0 1
yugabyte=# begin;
BEGIN
yugabyte=# insert into t values(2);
INSERT 0 1
yugabyte=# commit;
COMMIT
```
Connection 2
```
yugabyte=# create table t1(k int primary key);
CREATE TABLE
yugabyte=# alter table t1 add column v int;
ALTER TABLE
```
Probably fixed by https://github.com/yugabyte/yugabyte-db/commit/76a39035a8c3aa3a4f0bd63f2aa43fe236135170 or a related diff. Closing.
