### ISSUE TITLE
detective: Delete redundant builds for the same Phabricator revision from the queue directly

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#10417]
Detective's background daemon looks at the Jenkins queue and at running builds to decide what builds to stop. It stops builds for diffs if a more recent diff for the same revision is already building or is in the queue.

Sample queue state:
https://gist.githubusercontent.com/mbautin/7fb6a241afd4ab27a024f7922e92f752/raw

It should delete redundant builds from the queue directly instead of waiting for those builds to start running and them stopping them.

**Comment by svarnau** [comment]
This should be logged in yugabyte/internal-devops repo.  Moving it there -- issue 199
