### ISSUE TITLE
[docdb] Make rocksdb_compact_flush_rate_limit_bytes_per_sec be shared across rocksdbs on a node

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10438]
### Description

Currently our disk throttle flag is independent per rocksdb, which makes it not be super useful, as we have 2 rocksdbs per tablet and can have thousand of tablets per server.

We should change the way we initialize rocksdb, so we have a shared throttle component, allowing us to use `rocksdb_compact_flush_rate_limit_bytes_per_sec` at a server level.

Code pointer: `src/yb/docdb/docdb_rocksdb_util.cc`
```
    if (FLAGS_rocksdb_compact_flush_rate_limit_bytes_per_sec > 0) {
      options->rate_limiter.reset(
          rocksdb::NewGenericRateLimiter(FLAGS_rocksdb_compact_flush_rate_limit_bytes_per_sec));
    }
```

Good people references: @ttyusupov @mbautin

**Comment by arybochkin** [comment]
Basing on test results default values have been changed for:
```
rocksdb_compact_flush_rate_limit_bytes_per_sec=1GB
rocksdb_compact_flush_rate_limit_sharing_mode=tserver
```
