### ISSUE TITLE
[yb-admin] Incorrect error message for list_tablets command

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#10432]
Jira Link: [DB-1289](https://yugabyte.atlassian.net/browse/DB-1289)
list_tablets (yb-admin) command returns incorrect message if user tries incorrect command

```
bin/yb-admin --master_addresses <master_addresses> list_tablets  demo_2 
Error running list_tablets: Invalid argument (yb/util/stol_utils.cc:28): demo_2 is not a valid number
```
**Expected**: table name is missing

AND
help section of yb-admin command shows as below,
`6. list_tablets <table> [max_tablets] (default 10, set 0 for max) [JSON]`

here, database/keyspace entry is missing.
**Expected**:` list_tablets <keyspace> <table_name> [max_tablets]`

**Comment by Arjun-yb** [comment]
By default, command takes YCQL type, so it is required to specify the type as well
if user tries with
`bin/yb-admin --master_addresses <master_ips> list_tablets test1`

It gives
`Error running list_tablets: Invalid argument (yb/tools/yb-admin_client.cc:363): Namespace 'test1' of type 'ycql' not found`

cmd should be 
`bin/yb-admin --master_addresses <master_ips> list_tablets type.dbname table/index name`

mentioning **type** in https://docs.yugabyte.com/latest/admin/yb-admin/#list-tablets helps to the end user.

And 
`6. list_tablets <table> [max_tablets] (default 10, set 0 for max) [JSON]`
here it is not taking 10 as default, it lists all tablets

**Comment by Simonliuwaterloo** [comment]
Resolved issues regarding default 10 tablets, missing table name error message, and add keyspace to the error message. Also added a follow up issue: https://github.com/yugabyte/yugabyte-db/issues/14326.
