### ISSUE TITLE
Start & stop docker database

### ISSUE THREAD

**Issue by BevanR** [YugaByte/yugabyte-db#1044]
Feature request for `yb-docker-ctl`.

- Stop and start the database without destroying it
  - E.g. to free up the port and avoid accidentally connecting to the wrong YB instance
  - Workaround; `docker stop yb-master-n1 yb-tserver-n1` and  `docker start yb-master-n1 yb-tserver-n1`
- Set `--use_cassandra_authentication` when starting
  - Workaround; use `--tserver_flags` when creating.
  

`yb-ctl` has both of these features.

**Comment by Arnav15** [comment]
To stop the whole cluster
`./yb-docker-ctl stop`
To start the whole cluster
`./yb-docker-ctl start`
To stop a particular container (specify the master flag in case the master with the specified node number needs to be stopped)
`./yb-docker-ctl stop_node <node-number> [--master]`
To start a particular container (specify the master flag in case the master with the specified node number needs to be stopped)
`./yb-docker-ctl start_node <node-number> [--master]`
Can also now specify cassandra authentication on create and add node
`./yb-docker-ctl create [--use_cassandra_authentication]`
`./yb-docker-ctl add_node [--use_cassandra_authentication]`
