### ISSUE TITLE
[Docs] Add docs for newly added yugabyteDB roles 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#10444]
Add documentation for new roles in YugabyteDB. This applies to v2.6, 2.8, 2.9, and later.

- yb_superuser
- yb_extension

**Comment by polarweasel** [comment]
https://docs.google.com/document/d/1RFp3G0Mw_eLcqS_hc6sOGkOJktvuKiAYdocUAnkMVGE/edit#heading=h.846ve86z74lw
