### ISSUE TITLE
[YSQL] Read Replica Cluster Modification

### ISSUE THREAD

**Issue by forrest-akin** [yugabyte/yugabyte-db#10461]
Jira Link: [DB-777](https://yugabyte.atlassian.net/browse/DB-777)
### Description

I'd like to understand if there are any risks or recommendations associated with modifying read replica cluster placement configuration. For example, if I have an existing read replica cluster and call `yb-admin delete_read_replica_placement_info` followed by `yb-admin add_read_replica_placement_info`. Assuming some of the same nodes are in both the previous and new read replica placements, is there any risk of data on the read replica nodes getting out of sync from the primary cluster between the time of calling `delete_read_replica_placement_info` and `add_read_replica_placement_info`, or will they simply be caught back up after the new replica placement is applied?

**Comment by rahuldesirazu** [comment]
@forrest-akin When we call `yb-admin delete_read_replica_placement_info`, the load balancer (LB) is then responsible for deleting the data from all the nodes present on this placement. Assuming we wait for the LB to finish all tasks before calling `yb-admin add_read_replica_placement_info`, the LB will have to re-add data to these nodes. If you want to keep data around on nodes but modify the placement, we have command `yb-admin modify_read_replica_placement_info` for this purpose. Hope this helps.
