### ISSUE TITLE
[DocDB] Change modify_placement_info of yb-admin to specify number of copies of each Cloud.Region.Zone

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#10467]
### Description

Currently, for e.g. say that out of 3 copies of a tablet, we want to have 2 copies in `C1.R1.Z1` and 1 copy in `C2.R2.Z2` then we would specify it as below:

```
./bin/yb-admin \
    -master_addresses $MASTER_RPC_ADDRS \
    modify_placement_info  \
    C1.R1.Z1,C1.R1.Z1,C2.R2.Z2 3
```

However, this is somewhat complex and hard to follow. We don't need to necessarily repeat `C1.R1.Z1` 2 times or any other placement block the number of times we want it to be replicated. Instead, the above example could become:

```
./bin/yb-admin \
    -master_addresses $MASTER_RPC_ADDRS \
    modify_placement_info  \
    C1.R1.Z1 2 C2.R2.Z2 1 3
```

This change is fairly simple and only involves changing the client interface. Underneath, even today we count the copies and store and use them, so server-side changes should be trivial.

**Comment by NitronR** [comment]
@sanketkedia Is someone working on this? If not, let me know if I can pick this.

**Comment by NitronR** [comment]
Also, I was thinking of the below format for better readability. Let me know your thoughts on below format:
```
./bin/yb-admin \
    -master_addresses $MASTER_RPC_ADDRS \
    modify_placement_info  \
    C1.R1.Z1:2,C2.R2.Z2:1 3
```
We can even have the count as optional, default being 1, example:
```
./bin/yb-admin \
    -master_addresses $MASTER_RPC_ADDRS \
    modify_placement_info  \
    C1.R1.Z1:2,C2.R2.Z2 3
```

**Comment by sanketkedia** [comment]
Hey @NitronR, Apologies for responding late, holidays! Are you still interested in working on this? If yes, let me know. Also, would be happy to share code pointers on how to get started, etc. LMK.

**Comment by NitronR** [comment]
@sanketkedia yes, interested in working on it. Sure, code pointers will be helpful.

**Comment by sanketkedia** [comment]
Got it. 

1. The entry point for the `modify_placement_info` command can be found in [yb_admin_cli.cc](https://github.com/yugabyte/yugabyte-db/blob/2523988859f2b891a6272a83cd22a34b901f51f4/src/yb/tools/yb-admin_cli.cc#L433). Here, partial parsing of the command is done. I don't anticipate any changes here but just make sure that everything is as expected.

2. [yb-admin_client.cc](https://github.com/yugabyte/yugabyte-db/blob/2523988859f2b891a6272a83cd22a34b901f51f4/src/yb/tools/yb-admin_client.cc#L1746) takes in the placement info string and parses it. You'll have to make changes to the parsing logic here in order to change the grammar.

3. The yb-admin client actually creates a new cluster config protobuf (it is an internal configuration structure from where the server reads information such as these) and then invokes RPC to the server to update the protobuf with this new one. The bulk of the code to set the placement info in the cluster config protobuf is present in [yb-admin_client.cc](https://github.com/yugabyte/yugabyte-db/blob/2523988859f2b891a6272a83cd22a34b901f51f4/src/yb/tools/yb-admin_client.cc#L1746). The Protobuf structure can be found in [catalog_entity_info.proto](https://github.com/yugabyte/yugabyte-db/blob/2523988859f2b891a6272a83cd22a34b901f51f4/src/yb/master/catalog_entity_info.proto#L302), the actual PlacementInfoPB block is present in the same file [catalog_entity_info.proto](https://github.com/yugabyte/yugabyte-db/blob/2523988859f2b891a6272a83cd22a34b901f51f4/src/yb/master/catalog_entity_info.proto#L45).

Feel free to ask questions.

**Comment by NitronR** [comment]
@sanketkedia  Thanks will give it a go. Is there a slack channel for contribution related help where we can post any issues such as local build/setup issue.

**Comment by sanketkedia** [comment]
@NitronR You can join our community Slack channel using this [invite link](https://join.slack.com/t/yugabyte-db/shared_invite/zt-xbd652e9-3tN0N7UG0eLpsace4t1d2A). Feel free to PM me directly on Slack also.

**Comment by NitronR** [comment]
@sanketkedia done with the changes, can you review please: https://github.com/yugabyte/yugabyte-db/pull/11037

Also, can you point me to the documentation source for this, will update in the same PR.

**Comment by sanketkedia** [comment]
@NitronR left some comments in the PR. Also, added a link to the doc file in the same PR. Reach out with questions.

**Comment by NitronR** [comment]
@sanketkedia Thanks for the review! Have updated the PR.
