### ISSUE TITLE
[YSQL] Implement follower reads for YSQL

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#10473]
### Description

Implement follower-reads for YSQL, such that if enabled, the reads would be directed to the closet replica/follower. The reads shall be done at a historic time, which is a few seconds behind from current time, so that the timestamp is already safe and available at the closest replica.

**Comment by jameshartig** [comment]
@amitanandaiyer I'm not privy to the details discussed internally but I'm curious why any time is being chosen for follower-reads instead of just letting it return whatever is the most recent data on that replica (which is how YCQL works iirc)? While there's no guarantees that the follower has the latest data, I'm concerned that if a specific time is configured, stale data might be returned despite newer data being available.

**Comment by amitanandaiyer** [comment]
@jameshartig We considered the alternative that you are suggesting. That would work fine if the read query is essentially only touching one tablet. However if you are to consider `select * from table` like queries where the read may be happening from multiple tablets, or even across tables, then allowing the tablet to choose a timestamp doesn't work as well. The timestamp chosen by the first tablet may not be available for the second tablet etc. 

I'm not saying that it cannot be made to work, but it will be at a cost of additional round trips/latency.

Hence the decision to go with a fixed delta such that the client can choose the timestamp and use it across all the different tablets.

**Comment by amitanandaiyer** [comment]
Also, even with this design, the user can choose the "staleness" on the fly by setting the session variable 
`yb_follower_read_staleness_ms`.

We plan to set this to 30s at a default. But you can set this to something lower. I'd set it to be at least a few seconds. So that it is larger than the a few times (ping_latency + raft_heartbeat_interval + max_clock_skew).

**Comment by jameshartig** [comment]
@amitanandaiyer thanks for the clarification that makes sense and I appreciate the option to configure it per session.

**Comment by jameshartig** [comment]
@amitanandaiyer can I get clarification on the staleness? The [docs](https://docs.yugabyte.com/preview/explore/ysql-language-features/going-beyond-sql/follower-reads-ysql/) say
> yb_follower_read_staleness_ms sets the maximum allowable staleness

But you made it seem like the staleness is fixed. When testing with something like:

```go
	_, err := db.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS t (t1 INT, PRIMARY KEY (t1))")
	if err != nil {
		panic(err)
	}
	_, err = db.Exec(context.Background(), "TRUNCATE TABLE t")
	if err != nil {
		panic(err)
	}

	go func() {
		t := time.NewTicker(time.Second)
		i := 0
		for range t.C {
			i++
			_, err := db.Exec(context.Background(), "INSERT INTO t (t1) VALUES ($1)", i)
			if err != nil {
				panic(err)
			}
			fmt.Println("set", i)
		}
	}()

	t := time.NewTicker(time.Second)
	for range t.C {
		i := new(int)
		err := db.QueryRow(context.Background(), "/*+ Set(transaction_read_only true) Set(yb_follower_read_staleness_ms 5000) */ SELECT MAX(t1) FROM t").Scan(&i)
		if err != nil {
			panic(err)
		}
		if i == nil {
			fmt.Println("get", "null")
		} else {
			fmt.Println("get", *i)
		}
	}
```
I get
```
set 1
get null
set 2
get null
get 2
set 3
get 3
set 4
get 4
set 5
set 6
get 5
get 6
set 7
get 7
set 8
get 8
set 9
get 9
set 10
```

Which makes it seem like its not fixed or I would expect the `get` values to be 5 values behind.

Also, I'm not sure why but I randomly get `get null` even after 5 seconds.

**Comment by jameshartig** [comment]
Ended up filing ^ as https://github.com/yugabyte/yugabyte-db/issues/12855
