### ISSUE TITLE
ARM Build: Unable to connect to ysqlsh , failing health checks on long running universe upon version upgrade.

### ISSUE THREAD

**Issue by kprashanti** [yugabyte/yugabyte-db#10470]
Jira Link: [DB-1284](https://yugabyte.atlassian.net/browse/DB-1284)
### Description

(Note: This was initially filed as platform issue which was triaged and moved to DB by platform team https://yugabyte.atlassian.net/browse/DB-216.   Re-filing as github issue for DB team.) 

Issue is on the Long Running Universe puppy-food-arm-1, http://portal.dev.yugabyte.com/universes/25c740bf-07ae-4cd1-adc8-d6a90f3f4d57/health.  Note: This universe uses an ARM build.

1: Unable to connect to YSQL shell
[yugabyte@ip-10-9-100-77 tserver]$ bin/ysqlsh -h 10.9.100.77ysqlsh: could not connect to server: Connection refused
Is the server running on host "10.9.100.77" and acceptingTCP/IP connections on port 5433?

2: Health check is failing with Error executing command ['ssh', 'yugabyte@10.9.100.77', '-p', '54422', '-o', 'StrictHostKeyChecking no', '-o', 'ConnectTimeout=10', '-o', 'UserKnownHostsFile /dev/null', '-o', 'LogLevel ERROR', '-i', '/opt/yugabyte/yugaware/data/keys/9a2457d1-f54f-46b6-94f6-8f1826de6d7c/yb-15-bogdan-arm-test_9a2457d1-f54f-46b6-94f6-8f1826de6d7c-key.pem', 'set -o pipefail; date +%s -d "$(ps -C yb-tserver -o lstart=)"']: b'date: invalid date \xe2\x80\x98Thu Oct 21 08:11:51 2021nThu Oct 21 08:11:57 2021\xe2\x80\x99\n'

3. The version health check YB Version is failing with this error, however, this should not be flagged as an error because this universe uses the ARM build(It is on the ARM equivalent of the latest version) Can we alter the YB Version health check to accommodate this and not throw a blanket failure?

Version from platform metadata 2.9.2.0-b47-ksreenivasan-arm, version reported by instance process 2.9.2.0-b47

Slack Thread: https://yugabyte.slack.com/archives/C4141D60H/p1634905697106000 
Notes from 's analysis:this might be an ARM bug worth looking at
The tserver attempted to launch postgres but somehow the launched process shows up as a tserver itself. It is as if only the fork part of the fork + exec worked.
tserver says
I1021 08:11:58.363227 3554572 pg_wrapper.cc:429] PostgreSQL server running as pid 3554620
ps shows
yugabyte 3554572       1 59 Oct21 ?        19:02:45 /home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/server.conf
yugabyte 3554572       1 59 Oct21 ?        19:02:45 /home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/server.conf
and no postgres processes
[yugabyte@ip-10-9-100-77 ~]$ ps -ef | grep postg
yugabyte 3807590 3806919  0 16:21 pts/1    00:00:00 grep --color=auto postg

**Comment by jatinbhowad** [comment]
Upgraded universes to 2.9.2.0-b90, still 1 node is in a failed state.

**Comment by rthallamko3** [comment]
@kprashanti , Am inclined to close this as this is a very old bug and the 2.9 version is not supported anymore.
