### ISSUE TITLE
[YSQL] get_clients.sh should use curl instead of wget

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#10472]
Jira Link: [DB-613](https://yugabyte.atlassian.net/browse/DB-613)
### Description

To connect to a Yugabyte Cluster using YugabyteDB Client Shell..., the get_clients.sh script requires wget .  Not everyone has package manager or xcode, so the wget on Mac OSX fails

@chirag-yb

**Comment by FranckPachot** [comment]
The [doc ](https://docs.yugabyte.com/preview/admin/ysqlsh/) should use `curl` then. It still shows `wget -q -O - https://downloads.yugabyte.com/get_clients.sh` but cloud connection guide shows `curl -sSL https://downloads.yugabyte.com/get_clients.sh | bash`

**Comment by iSignal** [comment]
@polarweasel : can we update the doc page for ysqlsh to use curl instead?

**Comment by polarweasel** [comment]
@iSignal Considering that the script in question gives you scripts from YugabyteDB v2.6, should we really be using it at all?
