### ISSUE TITLE
[DocDB] Multi-RAFT V0 - Batch Heartbeat Requests

### ISSUE THREAD

**Issue by nimwijetunga** [yugabyte/yugabyte-db#10479]
### Description

Part of the work for: https://github.com/yugabyte/yugabyte-db/issues/772

Currently heartbeats account for a significant portion of the CPU usage for an idle cluster (i.e a cluster with 1000 tablets will consume 0.4 vCPU). This can be attributed to work required to context switch (when sending/receiving RPC's), compute state and serialize/deserialize protobufs. We have experimentally determined that a there is a potential for reducing CPU consumption (upwards of 9-10% CPU usage saved) if we send out heartbeats in batches.

The first cut of work for batching heartbeats will have the following requirements:

- [x] Batch level RAFT protocol that wraps the existing protocol and builds a repeated field of ConsensusRequestPB/ConsensusResponsePB for heartbeats
- [x] Ability to bypass heartbeats that have been batched but not yet sent (as not add artificial latency to non-heartbeat ops)
- [x] Knobs to mitigate latency of batching endpoint at sender with the ability to control the max batch size and batch send interval
- [x] Top level flag to turn on/off new code path

The goal for this first cut of work will be to have a working version of batched heartbeats (with minimal changes to the existing protocol) which can be used for experimentation and measuring results so that we can gain insights for optimizations in V1.

For more details on design decisions please refer to this doc: https://docs.google.com/document/d/1uRE9PZBYDWVqREf21rR7LRcLyHIIv_TP1YaZtonPVfE/edit?usp=sharing

**Comment by nimwijetunga** [comment]
`8f0a8c2` and `8f1f945` finish the first cut of work for multi-raft. To enable the feature `FLAGS_enable_multi_raft_heartbeat_batcher` must be set to `true`

**Comment by robertsami** [comment]
re-opening to track enabling this by default
