### ISSUE TITLE
[YSQL] List partitioned table shows as hash or range partitioned in table UI

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10474]
Jira Link: [DB-876](https://yugabyte.atlassian.net/browse/DB-876)
### Description

A customer has been testing with list partitioned tables, after creating such a table, in the table UI via Master UI or Tserver UI, table is listed as hash partitioned.

Example
create table tlist (
id bigserial,
name varchar(100),
country varchar(100)
) partition by list(country);

See attached screensho
![Screenshot 2021-11-03 at 10 45 48](https://user-images.githubusercontent.com/86620340/140047721-bc54d696-1663-48d4-bba1-f77374a191d8.png)
t

**Comment by mheer9** [comment]
Also in the following example

Partition type shows as range

create table test2 ( 
id serial, 
name varchar(50), 
country varchar(100), 
primary key (country asc, id)
) partition by list(country)

See attached screen shot.
![Screenshot 2021-11-03 at 14 46 18](https://user-images.githubusercontent.com/86620340/140083097-31516762-8b25-47f7-ba17-b63c64960b06.png)

**Comment by tverona1** [comment]
This is by design: The "partition" information in the UI represents how the data is partitioned among tablets at the doc db level. This is not the Postgres concept of table partitioning.
