### ISSUE TITLE
[DocDB] Throttle Snapshot RPC tasks to TServers

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#10482]
### Description

When a Create/Delete/Restore Snapshot is executed on a large number of tables/tablets it results in too many RPC requests being sent to tservers that result in higher read/write latencies to the clients. We should have a way of rate-limiting these requests so that there is progress and at the same time the tservers don't get overwhelmed. Note that there is a scope to throttle other types of RPC requests too and a generic solution in the long term is expected but this issue tracks a short-term solution that for at-least snapshots.

**Comment by Tasneem9879** [comment]
bumping for automation
