### ISSUE TITLE
[UI] [docs] Yugabyte docs version dropdown fails to re-render when there is a value change for the version.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#10480]
### Description

If the Yugabyte docs version is changed from the dropdown list , it still displays the first index from the dropdown.

**Comment by rajmaddy89** [comment]
can I work on this issue ?

**Comment by rajmaddy89** [comment]
Can you assign this to me ?

**Comment by rajmaddy89** [comment]
https://github.com/yugabyte/yugabyte-db/pull/10481

**Comment by rajmaddy89** [comment]
<img width="508" alt="Screen Shot 2021-11-03 at 9 13 57 PM" src="https://user-images.githubusercontent.com/10095310/140242337-1197e5f0-45e4-44de-89b2-5fc4c72c4f37.png">

If you see the above image, even though the dropdown value was changed to `stable` version , its still pointing to `latest` version in the dropdown but the content on the right side displays the `stable` docs content accordingly

**Comment by polarweasel** [comment]
Closed by #10481
