### ISSUE TITLE
[Docs] Txn geo partition

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10508]
### Description

internal functional spec: https://docs.google.com/document/d/1gA-Eu_v9iQzDdVaA3ZW7XEJ5QXYvft4E4N6T00Ashls/edit#heading=h.mior1do4w7bm

in particular, there is
- one new YB admin command, `create_transaction_table`
- one gflag, `force_global_transactions`
- one YSQL session variable, `force_global_transaction`

cc @es1024 for any content questions

**Comment by pilshchikov** [comment]
@es1024 also needs to add a note about delete/update statements. Region column is required for this queries in geo transactions.
