### ISSUE TITLE
[DocDB] New TTL metadata needs special handling for tablet splitting

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10515]
### Description

The default way we are configuring the new TTL file based expiration, is by also limiting the max file size included in a compaction, via `rocksdb_max_file_size_for_compaction `. This allows us to not waste compaction cycles on files that could be completely discarded, due to all the data being outside of the TTL window. The user expectation is also then that they can control the space amplification, by ensuring that data that is outside of the TTL window, is expired in some controllable amount of time, eg: estimate how much data is generated in 1 day, set `rocksdb_max_file_size_for_compaction` to that, expect that you get about 1 day of space amplification

When a tablet splits though, we generate 2 child tablets, each initially holding hardlinks to the same parent data + some metadata to filter the upper or lower half of the data, on the next compaction (plus we schedule a compaction immediately). This compaction however could work in one of several ways
1. Despite setting `rocksdb_max_file_size_for_compaction`, we could squash all the files down to 1 single file and remove the unnecessary records. This however would nullify the file distribution, where we might have previously had N big "uncompactable" files, which we could expire, say, daily, now we will end up with a very large file, which we will not be able to fully expire until N days pass.
1. Alternatively, we could modify our compaction algorithm to go over these big files somehow 1 by 1, reading them independently and generating a new output file in their place, with filtered data. A couple of issues with this:
    1. This might require some net new rocksdb code, as our compactions right now do not operate on a file by file basis. 
    1. Each new output file shoudl be about half the initial input size, which is very likely to be lower than `rocksdb_max_file_size_for_compaction`. This could mean all of these files will get picked up by our regular compactions next time around! We might be able to address this by instead just marking these files somehow as not to be picked up by regular comapctions...
    1. There's also a subtle change now to user expectation. The guidance for setting `rocksdb_max_file_size_for_compaction` is to have it reflect, say, 1 day worth of data, per tablet, so that becomes the amount of overhead that each tablet generates. However, after a tablet splits, now each child should technically take in about half the traffic that the parent was taking. This means that the initial setting of `rocksdb_max_file_size_for_compaction` will account for 2 days worth of data for this tablet! Or in other words, instead of 1 tablet (parent) worth of `rocksdb_max_file_size_for_compaction` overhead, now you will have 2 tablets (children) worth of `rocksdb_max_file_size_for_compaction` overhead.

Perhaps we should consider a new way of configuring this feature, to better capture user intent, eg: switching from this raw max file size, to either a time based policy (eg: keep no more than 1 day of data), or some max percentage of overhead (eg: with 30 day TTL and 1 day overhead, you would have 1/30~=3.5%).

TODO: A natural question might be, why not pre-configure the system to 0 overhead and expire data ASAP. Would need some notes on data being grouped in bulk already, in SST files, plus read overhead of having too many very small SST files. Also some notes on the soft/hard limits on number of SST files and if we could somehow auto-tune those too.

**Comment by jmeehan16** [comment]
Closing this task for now, since we've opted to simply disable tablet splitting for TTL tables with file expiration for the time being (#10837 ).  If this becomes a priority in the future, we should reassess the best course of action, be it a) somehow incorporating a special case into `rocksdb_max_file_size_for_compactions`, b) creating a new one-to-one manual file compaction, c) embracing a time-window compaction strategy, or something else entirely.
