### ISSUE TITLE
[Docs] browsers and versions

### ISSUE THREAD

**Issue by kerneljake** [yugabyte/yugabyte-db#10525]
### Description

The docs should mention the browsers and versions that are supported when accessing the platform.  Searching the current docs for `browser` does not show hits for results like "chrome", "firefox", "opera", etc.

**Comment by lizayugabyte** [comment]
As per dev:

- >0.2% - all browsers that have at least 0,2% of global market share
- not dead - exclude browsers without official support in the last 24 months
- not op_mini all - exclude Opera Mini

So Platform should work on all modern desktop browsers. Tablets like iPad should also work, but that's not guaranteed.
