### ISSUE TITLE
user question: [YCQL] can prepared statements have map['?'], jsoninfo->'?' etc.

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#1057]
User question:

For JSONB and map<text, text> in prepared statements can we do something like this:

`select map_col['?'] from table where id = 1 `

or 

`select id from table where key = 'a' and map_column[?] = 'foo' `

or

`select id, json_column->'?' from table where id = 1`

**Comment by robertpang** [comment]
Currently, bind variables can only bind to table columns in a YCQL DML statement. For example,

```
select map_col['a'] from table where id = ?;
select json_column->'a' from table where id = ?;
```
or
```
update table set map_col['a'] = ? where id = ?;
```

We do not support binding to a map or JSON field as suggested.

**Comment by m-iancu** [comment]
Closing as the question is answered above.
