### ISSUE TITLE
YSQL/Spark Integration Content

### ISSUE THREAD

**Issue by dcomingore** [yugabyte/yugabyte-db#10583]
### Description

Content / how-to for integrating Spark with our YSQL API/JDBC. Today, we show YCQL integration only via https://docs.yugabyte.com/latest/integrations/apache-spark/java/

**Comment by dcomingore** [comment]
@polarweasel

**Comment by knicely87** [comment]
Question about this on the public #yb-users Slack channel:

https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1658858444508179

**Comment by aishwarya24** [comment]
This one is complete and the documentation is here : https://docs.yugabyte.com/preview/integrations/apache-spark/java-ysql/
