### ISSUE TITLE
[New Feature] Provide an ability to check status of long running DDLs like CREATE INDEX

### ISSUE THREAD

**Issue by ymahajan** [yugabyte/yugabyte-db#10595]
Jira Link: [DB-5116](https://yugabyte.atlassian.net/browse/DB-5116)
### Description

If you are adding a secondary index to a very large table, it might take a long time for the index creation process to complete. It depends on several factors, such as the size of the table, items in the table that qualify for inclusion in the index, and the attributes projected into the index.

This index backfill operation can take a long time so it would be useful to provide a way to get the status, which includes -

1. Still working on this DDL request?
2. How many seconds/minutes/hours are left to process this index creation?
3. If possible, provide info like total_work, start_time, time_remaining, elapsed_seconds, etc.

This could be applicable for other DDLs which can run for a longer duration.

[DB-5116]: https://yugabyte.atlassian.net/browse/DB-5116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ymahajan** [comment]
Also refer - https://github.com/yugabyte/yugabyte-db/issues/10338

**Comment by jaki** [comment]
Related issue #5504
