### ISSUE TITLE
[dst] Automatic tablet splitting should include in-progress splits in computing number of tablets 

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#10606]
Jira Link: [[DB-439]](https://yugabyte.atlassian.net/browse/DB-439)
We use the following method to compute the number of tablets in a table when determining whether to split tablets based on the low size threshold, high size threshold, etc:
```
std::size_t TableInfo::NumPartitions() const {
  SharedLock<decltype(lock_)> l(lock_);
  return partitions_.size();
}
```
But this does not include tablets which started to split but did not finish:
```
// Sorted index of tablet start partition-keys to TabletInfo.
// The TabletInfo objects are owned by the CatalogManager.
// At any point in time it contains only the active tablets.
std::map<PartitionKey, TabletInfo*> partitions_ GUARDED_BY(lock_);
```

If we've already started splitting our last tablet of the low-phase, we should start  considering new candidates using the high-phase. Therefore, we need to include these child subtablets that are not yet RUNNING in place of their RUNNING parents in our total tablet count, since it's presumed that it will split eventually

[DB-439]: https://yugabyte.atlassian.net/browse/DB-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
One important caveat -- if we're splitting tablet A, and we see it already has subtablets B, C in CREATING state, then we should NOT include B, C in the tablet count

**Comment by SrivastavaAnubhav** [comment]
Since we check `ShouldSplitValidCandidate` and add to `partitions_ ` under the same catalog manager lock in `CatalogManager::DoSplitTablet`, we should never hit this case. I.e. If we've started splitting the last tablet of the low-phase, all other outstanding DoSplit requests will check against the high phase threshold.
