### ISSUE TITLE
Guard against large hybrid clock jumps into the future compared to local wallclock time

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#10628]
Jira Link: [DB-1269](https://yugabyte.atlassian.net/browse/DB-1269)
When updating hybrid time on a node, we should reject updates that would result in hybrid time jumping into the future by too much (e.g. 60 seconds would be one "reasonable" definition of "too much"; we can replace it with a stricter threshold).

"Rejecting" a hybrid time update might be non-trivial. Crashing the server that has received an invalid update is one option and is much better than allowing an invalid hybrid time that is too far in the future to be stored persistently in the system. We should think about better mechanisms to reject invalid hybrid time updates.

Invalid hybrid times could originate at unsynchronized clocks on some servers in the cluster, or be result of internal memory corruption in a server. Because hybrid time only goes forward and is difficult or impossible to revert once a too-large value been persisted, we need to have some sanity checks when validating hybrid time updates.

**Comment by bmatican** [comment]
Protection added in #10571
