### ISSUE TITLE
Yugaware Register API parameter 'Code' can currently only support upto 5 chars length

### ISSUE THREAD

**Issue by sraghavan-eqix** [YugaByte/yugabyte-db#1062]
This puts a limitation to set a custom namespace name as this Code parameter is used while creating a namespace (while creating a new Universe). Kindly, extend support up-to 100 chars.

**Comment by rkarthik007** [comment]
Is this safe to just change @ramkumarvs? Or does this need a schema migration? cc @bmatican or @Arnav15 in case you know.

**Comment by WesleyW** [comment]
Kubernetes has a 63 character limitation on namespaces, so 100 chars isn't possible. We've updated the limit to 15 characters for the moment.

**Comment by rkarthik007** [comment]
@sraghavan-eqix - does 15 chars work for you? See @WesleyW's comment above - we try to keep this small because its used in k8s namespaces, which are max 63 chars.

**Comment by sraghavan-eqix** [comment]
make sense - yes 15 chars length must be ok. Thanks for the fix

**Comment by rkarthik007** [comment]
Closing out @sraghavan-eqix , please reopen if you need anything else. Thanks!
