### ISSUE TITLE
[New Feature] dsbulk support for jsonb columns

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10638]
Jira Link: [DB-884](https://yugabyte.atlassian.net/browse/DB-884)
### Description

Customer requires a data loading tool to load large data sets, one of the customers requirements is to load tables with jsonb columns.

Current version of dsbulk, dsbulk-1.6.0 does not support jsonb columns.

E.g. 
Error when loading a table
CQL type JSONB is not officially supported by this version of DSBulk;

**Comment by mheer9** [comment]
Here is an example table

CREATE TABLE demo.bulkdemo (
    id int,
    ts bigint,
    idx bigint,
    msginfo jsonb,
    fileid int,
    PRIMARY KEY (id, ts, idx)
) WITH CLUSTERING ORDER BY (ts ASC, idx ASC)
    AND default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
    
    
When loading via command, we get errors below
[centos@ip-172-204-36-63 yugabyte-client-2.6]$ dsbulk load -h 172.159.43.83 -k demo -t bulkdemo -url bulk.csv -delim '\t'
Operation directory: /home/centos/yugabyte-client-2.6/logs/LOAD_20211118-155555-831844
CQL type JSONB is not officially supported by this version of DSBulk; string literals will be parsed and formatted using registered codec StringCodec
total | failed | rows/s | p50ms | p99ms | p999ms | batches
    3 |      3 |      0 |  0.00 |  0.00 |   0.00 |    0.00
Operation LOAD_20211118-155555-831844 completed with 3 errors in .
Rejected records can be found in the following file(s): mapping.bad
Errors are detailed in the following file(s): mapping-errors.log
Last processed positions can be found in positions.txt

**Comment by mheer9** [comment]
Attached is the csv file used, plus logs

[bulk.csv](https://github.com/yugabyte/yugabyte-db/files/7564197/bulk.csv)

[positions.txt](https://github.com/yugabyte/yugabyte-db/files/7564201/positions.txt)
[mapping-errors.log](https://github.com/yugabyte/yugabyte-db/files/7564203/mapping-errors.log)
[operation.log](https://github.com/yugabyte/yugabyte-db/files/7564205/operation.log)

[mapping.txt](https://github.com/yugabyte/yugabyte-db/files/7564216/mapping.txt)

**Comment by priyanshi-yb** [comment]
The support for JSONB columns is now available in [this](https://github.com/yugabyte/dsbulk/releases/tag/v1.6.0-yb-1) release of dsbulk.
