### ISSUE TITLE
[YSQL] YugaByte storage sorting order must match ORDER BY

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#1065]
Although all SQL datatypes are supported in YugaBytes, we have to disallow indexing and partitioning on columns of some of the datatypes as listing on the following document. The storage layer needs to provide data format that can be sorted in the same order as ORDER BY operations.

https://docs.google.com/spreadsheets/d/1_xQfqakHetvBL1aHkU2ji00IYgv7WbXud4ZJpA2nOXg

**Comment by ndeodhar** [comment]
@OlegLoginov, can you help with this please? @nocaway will give you details on what needs to be done. This is his previous commit: https://github.com/YugaByte/yugabyte-db/commit/3927f286c6f95e5a2d8338dce950f7e51f1e5402

You will need to add tests like those for all datatypes that are supported in primary key columns.
