### ISSUE TITLE
[Docs] Add a link to API, remove Beta tag from page, and fix links

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#10678]
### Description

This page yugabyte-platform/create-deployments/async-replication-platform/ needs a link to the xcluster API.

Should be done post GA, when the new xcluster platform API is public.

API spec: https://docs.google.com/document/d/1P2apffLyl9BBZT6ZmFylog2LBpCJ3SuaRqyUbdDprMU/edit#heading=h.un3l8yk7ch03

API docs: https://api-docs.yugabyte.com/docs/yugabyte-platform/YXBpOjE4OTQ3NTE1-yugabyte-platform-ap-is

**Comment by lizayugabyte** [comment]
Blocked by https://yugabyte.atlassian.net/browse/PLAT-2255

**Comment by lizayugabyte** [comment]
@polarweasel When you hear anything about the updated API doc, could you, please, either add a link or reassign this ticket to me?

**Comment by polarweasel** [comment]
Not sure exactly what this is about. Can you elaborate? (ping me on slack)

**Comment by lizayugabyte** [comment]
@polarweasel Never mind
