### ISSUE TITLE
[Docs] Specify Subject Alternative Name(SAN) when creating server certificates in docs

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#10686]
### Description

The Common Name field for server certificates has been deprecated with some browsers not supporting it and other clients ignore the value checking the SAN field. Instead, the doc for creating node certificates should also mention creating certificates using the SAN extension.

Ref doc - https://docs.yugabyte.com/latest/secure/tls-encryption/server-certificates

From https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html 

```
 subjectAltName=@subject_alt_section

 [subject_alt_section]
 subjectAltName=URI:ldap://somehost.com/CN=foo,OU=bar
```

**Comment by adil246** [comment]
cc @polarweasel

**Comment by polarweasel** [comment]
Thanks @adil246! Can you provide details on this one?

**Comment by lizayugabyte** [comment]
@adil246  Would you be able to help with details on this one?

**Comment by lizayugabyte** [comment]
Addressed in https://github.com/yugabyte/yugabyte-db/pull/14577

**Comment by lizayugabyte** [comment]
@polarweasel Can we close this ticket?
