### ISSUE TITLE
[YSQL] Consider refactor to stop relying on pg_session for state

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#10696]
Jira Link: [DB-874](https://yugabyte.atlassian.net/browse/DB-874)
### Description

PgSession is used only for read/write operations.

We are using pgSession->ShouldUseFollowerReads which essentially is maintaining state (although at pgTxnManager)

We should consider refactoring it to avoid mix use.

**Comment by bmatican** [comment]
Re-opening for backports, as it seems to affect YSQL follower reads users.
