### ISSUE TITLE
🐞🤦‍♀️ `yb-ctl` usability bug; Global options don't work if they follow the command.

### ISSUE THREAD

**Issue by BevanR** [yugabyte/yugabyte-db#1070]
It's weird and annoying that `yb-ctl --replication_factor 1 create` works but `yb-ctl create --replication_factor 1` does not.

Global options should work either before or after the sub-command.

**Comment by ramkumarvs** [comment]
@WesleyW lets update our docs and confirm which version this change would be part of and close this issue?

**Comment by WesleyW** [comment]
Confirmed this is in 2.0.3.0 (and any patches after 2.0.1.0).
