### ISSUE TITLE
[DocDB] Restore and Database creation failing on cloud portal due to "Namespace Create Failed: not onlined"

### ISSUE THREAD

**Issue by kprashanti** [yugabyte/yugabyte-db#10716]
Jira Link: [DB-1177](https://yugabyte.atlassian.net/browse/DB-1177)
### Description

(Note: This was initially filed as Yugabyte Cloud issue https://yugabyte.atlassian.net/browse/CLOUDGA-3058 but later determined a DB issue. Hence filing a corresponding github issue for the DB team.)

On cloud portal, sometimes database creation and restore fails because of error "Namespace Create Failed: not onlined". The steps to repro vary - but it usually happens on a source cluster with a backup after a restore operation.  Sometimes, the failure is seen at the first restore, sometimes first succeeds but second fails, sometimes the first two succeed but third restore fails.

**Following are some scenarios involving restore**.
**Scenario 1**: 
1. Create a cluster
2. Create a sample data
3. Take a backup
4. Delete all the created data
5. Restore backup on a same cluster
6. Restore happened successfully.

**Scenario 2**:
1. Create a cluster
2. Run a sample apps
3. Access cloud shell 
4. Take a backup
5. Restore it on another cluster
6. Restore fails in this case.

**Scenario 3**:
DB version (from slack, adding here for completeness): 2.6.4.0-b3
Summary of sequence: First two restores succeed but third fails followed by no more DB operations succeeding
Duration of following sequence: 29 Oct, 11:40 am to 12:05 pm - PST. 
Datadog logs for this duration: https://app.datadoghq.com/logs?cols=host%2Cservice&from_ts=1635532800000&index=&live=false&messageDisplay=inline&query=40be5b3b-292b-48f0-b231-a02d6e1f4d33&stream_sort=desc&to_ts=1635534300000
Detailed sequence of steps: 29 Oct, 11:40 am to 12:05 pm - PST
1. create cluster;  from Client shell ysql: namespace and table - ybdemo.accounts
2. create backup b1
3. drop namespace ybdemo (Client shell ysql)
4. 1st restore from b1 - succeeds
5. cluster has ybdemo.accounts
6. drop namespace ybdemo (Client shell ysql)
7. 2nd restore from b1 - succeeds
8. cluster has ybdemo.accounts
9. drop namespace ybdemo (Client shell ysql)
10. 3rd restore from b1 - fails
11. Further operations on db  (Client shell ysql) cause errors
12. CREATE DATABASE fritest;
13. ERROR: Internal error: Namespace Create Failed: not onlined.

<img width="474" alt="Screen Shot 2021-10-29 at 4 22 03 PM" src="https://user-images.githubusercontent.com/19825073/143790502-67d18734-9736-4dae-bdce-829de55aa611.png">
![Screen Shot 2021-10-29 at 4 24 34 PM](https://user-images.githubusercontent.com/19825073/143790503-d78a0a4f-f438-4e61-b0d9-259638c548b9.png)

**Comment by def-** [comment]
Also seeing this on next run after #13539 occurred:
```
2022-08-05 23:24:38,144 MainThread INFO     Creating tables for database db_lst_399413
Traceback (most recent call last):
  File "/Users/deen/code/yb-long-system-test/./long_system_test.py", line 391, in <module>
    main()
  File "/Users/deen/code/yb-long-system-test/./long_system_test.py", line 382, in main
    lst.run()
  File "/Users/deen/code/yb-long-system-test/./long_system_test.py", line 269, in run
    self._create_tables()
  File "/Users/deen/code/yb-long-system-test/./long_system_test.py", line 198, in _create_tables
    self.database.create(cur)
  File "/Users/deen/code/yb-long-system-test/lst/dbobject.py", line 219, in create
    self.execute(cur, f'CREATE DATABASE {self.name()};')
  File "/Users/deen/code/yb-long-system-test/lst/dbobject.py", line 25, in execute
    raise e
  File "/Users/deen/code/yb-long-system-test/lst/dbobject.py", line 18, in execute
    cur.execute(query)
psycopg2.errors.InternalError_: Internal error: Namespace Create Failed: not onlined.
```
