### ISSUE TITLE
[YCQL] TestJsonIndex.testIndex flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10734]
Jira Link: [DB-1193](https://yugabyte.atlassian.net/browse/DB-1193)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=org.yb.cql.TestJsonIndex&name=testIndex

**Comment by OlegLoginov** [comment]
Fixed in the master branch.
