### ISSUE TITLE
[DocDB] NetworkFailureTest.DisconnectMasterLeader flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10736]
Jira Link: [DB-851](https://yugabyte.atlassian.net/browse/DB-851)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=NetworkFailureTest&name=DisconnectMasterLeader

**Comment by rthallamko3** [comment]
recent [execution trends ](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=NetworkFailureTest&name=DisconnectMasterLeader)indicate that the hinted leader fixes and other changes in the area could have helped resolve this.
