### ISSUE TITLE
[YSQL] Strict inequality conditions are pushed down as non-strict inequalities to DocDB

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#10738]
Jira Link: [DB-1170](https://yugabyte.atlassian.net/browse/DB-1170)
### Description

It seems that if a YSQL user requests a filter of the form `c < 3`, the corresponding request sent to DocDB will have `c <= 3`, causing an extra suite of seeks. The extra rows produced are filtered at the YSQL layer. However, this filtering is not reflected in the `EXPLAIN ANALYZE` output. 
Consider the following steps to reproduce this issue:
1) `CREATE TABLE rrr(r1 INT, r2 INT, v INT, PRIMARY KEY(r1 ASC, r2 ASC));`
2) `INSERT INTO rrr SELECT i/10, i%10, i FROM generate_series(1, 100) i;`
3) `set yb_debug_log_docdb_requests=true;`
4) `EXPLAIN ANALYZE SELECT * FROM rrr WHERE r1 < 2 and r2 = 1;`
5)  Observe how the RPC sent by this has a `QL_OP_LESS_THAN_EQUAL` operator in the condition specifier instead of `QL_OP_LESS_THAN`
6)  Observe, how `EXPLAIN ANALYZE SELECT * FROM rrr WHERE r1 <= 2 and r2 = 1;` also takes less time than the query in step 4 as no extra filtering has to be done.

In step 4, note that there were no displayed rows filtered by recheck in the output. You can also verify that rows were indeed filtered by putting a breakpoint on the codepath that returns false over [here](https://github.com/yugabyte/yugabyte-db/blob/0307f302e99737ad6cd0411657e593880bc53c10/src/postgres/src/backend/access/yb_access/yb_scan.c#L1303).

The extra seeks resulting from this become more non-negligible as you add more columns and strict inequality conditions.

**Comment by jaki** [comment]
See related issue #4746.
