### ISSUE TITLE
[xCluster] Add force option to delete_cdc_streams for streams that are a part of replication

### ISSUE THREAD

**Issue by hulien22** [yugabyte/yugabyte-db#10730]
Running `delete_cdc_stream` (instead of `delete_universe_replication`) on a currently running replication setup can result in a couple of issues:

 - Issues with `delete_universe_replication`, where we are unable to find the stream on the producer (can be bypassed with the `ignore-errors` option)
 - Issues with leftover dangling entries in the `cdc_state` table, which lead to incorrect high replication lag metrics
 

There should be a check in `delete_cdc_stream` to verify that a cdc stream is a part of replication (by checking the stream metadata this can be done by verifying that it is an xcluster stream, and that it is in the `ACTIVE` state - we still need to use `delete_cdc_stream` to cleanup any un-bootstrapped streams which would still be in a `INITIATED` state), AND then have an error for such streams (ideally mentioning that this is an xcluster stream, perhaps you meant to use `delete_universe_replication`?).

This check could then be bypassed with a force flag (similar to the one used for `delete_universe_replication`).

**Comment by nspiegelberg** [comment]
Remember to Add a CLI-level Unit Test to verify this change.
