### ISSUE TITLE
[DocDB] Automatic tablet splitting stuck on master-side

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#10747]
### Description

I was repeating the scenario from #10746 on the same RF=1 local cluster and dropping the table before each attempt and at some point, splitting stopped being triggered from the master, the master was adding a tablet to split in the queue, but wasn’t triggering the split.

I assume it can be due to `processing_tablets_to_split_children_` not getting cleared correctly in case of a `drop table` and being over the limit.

**Comment by SrivastavaAnubhav** [comment]
Fixed by 1d2bc92.
