### ISSUE TITLE
Master update fails due to footer magic, consecutive restarts also fail

### ISSUE THREAD

**Issue by tobiasmuehl** [YugaByte/yugabyte-db#1074]
Updating to 1.2.0.2 the update master node didn't boot up with this log:

```
W0324 15:48:14.677505 13044 log_util.cc:208] Could not read footer for segment: /home/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000.recovery/wal-000000002: Not found (yb/consensus/log_util.cc:443): Footer not found. Footer magic doesn't match
W0324 15:48:14.677822 13044 log_reader.cc:165] Log segment /home/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000.recovery/wal-000000002 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0324 15:48:14.896342 13053 catalog_manager.cc:695] Catalog manager background task thread going to sleep: Service unavailable (yb/master/catalog_manager.cc:6960): Catalog manager is not initialized. State: 1
```

After deleting the data dir the log changes to this:

```
W0324 16:09:58.486258 14441 service_util.h:67] Invalid argument (yb/tserver/service_util.h:66): UpdateConsensus: Wrong destination UUID requested. Local UUID: 7fa1f2bb240f48c3932b885f22a41b21. Requested UUID: 61cf89423d2f451dbe7bd081525a2ef4: from 144.76.xxxxxx:53982: tablet_id: "00000000000000000000000000000000" caller_uuid: "2b6ad8d304984ba1907356818e115ace" caller_term: 4 preceding_id { term: 4 index: 2736 } committed_index { term: 4 index: 2736 } dest_uuid: "61cf89423d2f451dbe7bd081525a2ef4" leader_lease_duration_ms: 2000 ht_lease_expiration: 1553443800485720 propagated_safe_time: 6362904805389639680 propagated_hybrid_time: 6362905798597509120
```

And later to this:

```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0325 01:45:40.606120 13757 master.cc:222] Master@176.xxxxxx:7100: Unable to init master catalog manager: Not found (yb/util/env_posix.cc:1013): Unable to initialize catalog manager: Failed to initialize sys tables async: Unable to load consensus metadata for tablet 00000000000000000000000000000000: /home/yb-data/master/consensus-meta/00000000000000000000000000000000: No such file or directory (error 2)
E0325 01:45:40.606400 13737 main_util.cc:22] Not found (yb/util/env_posix.cc:1013): Unable to initialize catalog manager: Failed to initialize sys tables async: Unable to load consensus metadata for tablet 00000000000000000000000000000000: /home/yb-data/master/consensus-meta/00000000000000000000000000000000: No such file or directory (error 2)
```

@bmatican assumed this is what happened:
> I believe we have a failure situation in the master where, the first time it starts up, it needs to setup some metadata and, if it does not generate all of it, and say, crashes, then the second time it starts up, it sees some being present, assumes all should be, then fails when it realizes it is not..

Wiping the whole cluster and re-initializing, the same node reported the same `Footer not found` as initially (first log file), but then sorted itself out automatically.

Action items:
- investigate the log replay master issue
- make the master startup atomic, so incomplete metadata being written does not prevent the next startup from working
- describe a manual heal in case of master data wipe, or, ideally, build automation for that

**Comment by mbautin** [comment]
One thing to note here is that currently we are using durable WAL implementation (O_DIRECT based) for the master but not for tserver. Cc @bmatican 

@tobiasmuehl: just to double-check, is the data directory located on a regular local disk, or on an NFS volume?

**Comment by bmatican** [comment]
Passed this to @bbaddepudi at least for the atomic startup + maybe documenting some simple `yb-admin` steps for replacing a dead master (we probably already have these as substeps in the full move documentation).

**Comment by tobiasmuehl** [comment]
@mbautin Regular local disk (XFS)

**Comment by bbaddepudi** [comment]
We are adding a check to make the first master start atomic using a `lock-file` to detect successful completion of the FS creation during startup. If there is any failure during the first startup involving the masters filesystem setup, then this lock file will remain. On any future startups of the same master (using same `fs_data_dirs` flag), if the lock file is present, the partially setup FS is deleted and is then recreated from scratch as if it is a first clean startup. Of course this does not protect the system hitting an OS-level or other lower level issue.

If there are cases where the above does not help (say, an older release), noting down the steps to remove a failed master (whose IP addr is `fix_ip`) and recreate it, assuming two other masters (in RF3 case) are fine. With sample commands for each step. Lets say that `$MASTER_IPS` is defined to `ip_1:7100,ip_2:7100,fix_ip:7100`.
1. First, check that the master quorum has a failed master, on a node that has master running
`~/master/bin/yb-admin -master_addresses $MASTER_IPS list_all_masters`
2. Force remove that failed master from the quorum, from a node that has master running
` ~/master/bin/yb-admin -master_addresses $MASTER_IPS change_master_config REMOVE_SERVER fix_ip 7100 1`
3. Ensure the master process is killed on that failed node `fix_ip`. Now start the master on that node in `shell` mode. This will use the same `yb-master` command as before (see https://docs.yugabyte.com/latest/admin/yb-master/ for samples), but *without* the `master_addresses` parameter.
4. Now add that newly started master to the quorum
`~/master/bin/yb-admin -master_addresses  $MASTER_IPS change_master_config ADD_SERVER fix_ip 7100`
5. Ensure that quorum has one leader and two followers using the same `list_all_masters` option of yb-admin.

**Comment by bbaddepudi** [comment]
Partial diff at (internal) https://phabricator.dev.yugabyte.com/D6565.

**Comment by bmatican** [comment]
We've since fixed the atomic restart issue and have documented steps on how to move masters. Closing this.
