### ISSUE TITLE
[DocDB] Long-running transaction is aborted if tablet is split or moved

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#10746]
### Description

1) Launch local cluster RF=1:
```
RF=1

THRESHOLD=100000
MASTER_FLAGS="enable_automatic_tablet_splitting=true","tablet_split_low_phase_size_threshold_bytes=0","tablet_split_high_phase_size_threshold_bytes=0","tablet_split_low_phase_shard_count_per_node=0","tablet_split_high_phase_shard_count_per_node=0","tablet_force_split_threshold_bytes=$THRESHOLD,process_split_tablet_candidates_interval_msec=1"

TSERVER_FLAGS="db_write_buffer_size=$THRESHOLD"

./bin/yb-ctl --rf=$RF create --num_shards_per_tserver=1 --ysql_num_shards_per_tserver=1 --master_flags "$MASTER_FLAGS" --tserver_flags "$TSERVER_FLAGS"
```

2) From ysqlsh:
```
yugabyte=# create table t(k int, v int);
CREATE TABLE
yugabyte=# insert into t select i*2+1, 1 from (select generate_series(1, 500000) i) t2;
```

3) Concurrent session from python script:
```
#!/usr/bin/env python3

import psycopg2

conn = psycopg2.connect("host=127.0.0.1 port=5433 dbname=yugabyte user=yugabyte password=yugabyte")
print("connected")

conn.set_session(autocommit=True)
cur = conn.cursor()

for i in range(0, 1000000):
  k = i * 2
  cur.execute("INSERT INTO t(k, v) VALUES (%s, 0)", (k,))
  if i % 1000 == 0:
    print("Inserted ", i)

conn.commit()
cur.close()
conn.close()
```

After inserting some data and splitting the tablet ysqlsh transaction is aborted with an error:
```
ERROR:  Operation failed. Try again.: [Operation failed. Try again. (yb/tablet/tablet.cc:1205): Transaction metadata missing: 172fc12a-f2af-41e2-a6fd-365c022c7884, looks like it was just aborted (pgsql error 40001)]
```

**Comment by robertsami** [comment]
when we split a tablet, we create two child subtablets, and we clean up the parent tablet. the parent tablet deletion is initiated from the tserver via RPC to yb-master (DeleteNotServingTabletRequest). yb-master then sends a request to each replica which triggers TabletPeer::Shutdown, and that calls AbortSQLTransactions, which actually aborts all pending transactions on the tablet's participant

a very easy way to confirm this -- try modifying the repro above by adding `TEST_skip_deleting_split_tablets=true` as a tserver flag and note that we dont hit the error anymore. i also confirmed by running the repro as-is above, while commenting out the call to `AbortSQLTransactions` in `TabletPeer::Shutdown`

i think there's a simple fix here -- we probably just dont want to abort pending transactions when shutting down a tablet in the case of shutting down a split tablet parent. there might be some subtlety in terms of interaction/racing with the ddl paths which maybe do need to abort pending transactions, in case a tablet is being deleted from both paths
