### ISSUE TITLE
Implement IsTabletServerReady on the Master side to ensure system tablet is ready to serve

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1076]
We have added an RPC mechanism for detecting if a particular TS has locally bootstrapped all of it's tablets and is fully ready to serve. We can extend this to also work on the Master service, so the interface is the same. Alternatively, we can see if `IsMasterLeaderServiceReady` on the actual `MasterService` can be leveraged for the same purpose (it is currently tagged for unit tests only)

**Comment by bbaddepudi** [comment]
`IsMasterLeaderServiceReady` checks if the master is the leader of the quorum also and might be overkill check as it does more work than needed to check if system tablet has completed bootstrap. Also, it would not work on the follower masters.

It would be cleaner to add a new `IsMasterReady` proto and check sys tablet is locally bootstrapped (after catalog manager has been initialized). Note that `IsTabletServerReady` directs to `TABLET_SERVER_SERVICE_NAME` service on tserver, and this case we would like it to go to `MASTER_SERVICE_NAME`.
