### ISSUE TITLE
[New Feature] Add load-balance feature to the Go YSQL driver

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#10760]
Jira Link: [DB-865](https://yugabyte.atlassian.net/browse/DB-865)
### Description

The feature should be similar to the one available in the YSQL JDBC driver as far as possible.

# Tasks
|Done|Name|Notes|Link|
| - | - | - | - |
| ✅ | Provide simple load balancing behaviour (cluster-aware) | | |
| ✅ | Provide topology aware load balancing behaviour | | |
| ✅ | Complete above two for pgxpool | | |
| ✅ | Provide sample examples using both: a) individual connection and b) pool | | |
| ✅ | Documentation (quickstart, explore sections, orm section, etc.) | | [quickstart](https://docs.yugabyte.com/latest/quick-start/build-apps/go/ysql-yb-pgx/) |
| (Tracked separately)| Make the feature work in a GORM application | | |
| (Tracked separately)| Automate tests | | |

[DB-865]: https://yugabyte.atlassian.net/browse/DB-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jameshartig** [comment]
@ashetkar this is great! We were considering writing this ourselves for pgxpool. Would love to test this out when it gets to that point.

**Comment by ashetkar** [comment]
The feature is now available in `github.com/yugabyte/pgx/v4`, see the [README](https://github.com/yugabyte/pgx#readme) for more details.
