### ISSUE TITLE
[DocDB] org.yb.loadtester.TestClusterWithHighLoadAndSlowSync.testClusterFullMoveWithHighLoadAndSlowSync flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10797]
Jira Link: [DB-1169](https://yugabyte.atlassian.net/browse/DB-1169)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=org.yb.loadtester.TestClusterWithHighLoadAndSlowSync&name=testClusterFullMoveWithHighLoadAndSlowSync

**Comment by m-iancu** [comment]
Closing as duplicate of #13889.
