### ISSUE TITLE
[YSQL] Support CREATE INDEX CONCURRENTLY

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#10799]
### Description

Currently we don't support creating index concurrently.

This issue tracks adding support for concurrent index creation.

**Comment by jasonyb** [comment]
We don't support the grammar "CONCURRENTLY" but we do concurrently by default.

**Comment by ymahajan** [comment]
CONCURRENTLY is optional, can we do this as no-op syntax for PostgreSQL compatibility, since all indexes are created concurrently in YugabyteDB.

**Comment by lnguyen-yugabyte** [comment]
> CONCURRENTLY is optional, can we do this as no-op syntax for PostgreSQL compatibility, since all indexes are created concurrently in YugabyteDB.

@ymahajan : There are certain cases that one needs to error (as Postgres don't support it):
* CREATE INDEX CONCURRENTLY inside a transaction block
* CREATE INDEX CONCURRENTLY for a partitioned table.

I added a change to address these differences.
