### ISSUE TITLE
[DocDB] Master leader UI should show encryption at rest status 

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#10794]
### Description

When encr at rest is enabled, the master leader UI does not show information related to this feature. The cluster could look perfectly healthy but when missing the encryption keys, other operations could fail. 

We could show whether the cluster is encr at rest enabled and whether the server has encr keys loaded in mem (for master and tserver). For more debugging, showing the specific key ids in memory could help, but that may require a separate details page for encr at rest.

We could've used this during a recent encr at rest debugging session.

@bmatican @rahuldesirazu

**Comment by rahuldesirazu** [comment]
A few notes to help get started:

- On the master side, the cluster config should have a field for whether encryption is enabled and which key id is being used. Additionally, we have an API HasUniverseKeyInMemory for determining whether a master has a key in memory
- Tserver is a bit tougher. I believe the tserver level Env has a method IsEncrypted which determines whether encryption is enabled but there is currently no mechanism for seeing tserver in-memory keys..
- For the master UI piece, I think the 3 states we'll want to display are [never enabled, disabled, enabled with key x]

**Comment by bmatican** [comment]
Passing this to Hari as a starter. I'd say even if we just get the master side done, that's a good starting point. We could do the tserver side as a follow up, or just cut a separate issue for it. Feel free to reach out to @rahuldesirazu for more input along the way!

Docs for enabling encryption at rest: https://docs.yugabyte.com/latest/secure/encryption-at-rest/#root

Note, that for a local test, eg via `yb-ctl`, your data path will be different, eg: `~/yugabyte-data/node-1/disk-1/yb-data/master/`

**Comment by hari90** [comment]
Instructions to enable encryption are: https://docs.yugabyte.com/latest/admin/yb-admin/#add-universe-keys-to-all-masters
