### ISSUE TITLE
[DocDB] TestRedisServiceExternal.TestSlowSubscribersCatchingUp flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10798]
Jira Link: [DB-1109](https://yugabyte.atlassian.net/browse/DB-1109)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=TestRedisServiceExternal&name=TestSlowSubscribersCatchingUp

**Comment by rthallamko3** [comment]
@bmatican , Can we disable Redis tests in master? Do we need to continue to support them?

**Comment by rthallamko3** [comment]
@yusong-yan , Can you check with @amitanandaiyer , If its ok to disable this Redis test?
