### ISSUE TITLE
Redis API SET NX option does not work after TTL expiration

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#108]
In order to add new key we should use "NX" option, but once the key is expired, we are getting error using "NX" option, but using "XX" option it works. But once we do flush operation, it works fine with "NX".

```
127.0.0.1:6379> set test 1 EX 5 NX
OK

127.0.0.1:6379> get test
"1"

127.0.0.1:6379> get test
"1"

127.0.0.1:6379> get test
(nil)

127.0.0.1:6379> set test 1 EX 5 NX
(error) Unknown error
```

The Redis options for set should behave as follows:
- NX – Only set the key if it does not already exist.
- XX – Only set the key if it already exist.

**Comment by pritamdamania87** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/a4498b4b344b7a04c64f09eaa30b7667040b3c8d
