### ISSUE TITLE
[DocDB] Code cleanup: RocksDB Lite specific should be removed

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#10802]
Jira Link: [DB-1250](https://yugabyte.atlassian.net/browse/DB-1250)
### Description

There are a lot of unused code as well as unnecessary pre-processor branches related to RocksDB Lite version, which is not supported: this specific should be cleaned from the sources. Good reference is to search for `ROCKSDB_LITE` macro.

**Comment by mbautin** [comment]
Removed as part of https://github.com/yugabyte/yugabyte-db/commit/d3d9bdb6e1573f0ff5fa5546ee8578a30286cdf6
