### ISSUE TITLE
[YSQL] Performance drop observed with  pg_monitor present in shared_preload_library 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#10805]
### Description

For various workloads,  based on the output of "_top -c_" command, we observe the PostgreSQL backends are showing in _bind_ state for longer duration then usual.

Further analysis shows that PostgreSQL backends are getting stuck in acquiring the  LW_EXCLUSIVE  lock in pg_stat_monitor. 

Example code where _LW_EXCLUSIVE_ is acquired in the common code path in pg_stat_monitor.

https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/contrib/pg_stat_monitor/pg_stat_monitor.c#L1233
https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/contrib/pg_stat_monitor/pg_stat_monitor.c#L561

**Output of PSTACK showing the backtrace of the stuck backend.** 

Thread 1 (process 15836):
#0  0x00007f465ee2c18a in futex_abstimed_wait_cancelable (private=128, abstime=0x0, expected=0, futex_word=0x7f4640501
238) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7f4640501238, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f465ee2c231 in __new_sem_wait_slow (sem=0x7f4640501238, abstime=0x0) at sem_waitcommon.c:181
#3  0x00000000007d1fe2 in PGSemaphoreLock (sema=0x7f4640501238) at pg_sema.c:316
#4  0x000000000086ab75 in LWLockAcquire (lock=0x7f4640512c00, mode=mode@entry=LW_EXCLUSIVE) at ../../../../../../../src/postgres/src/backend/storage/lmgr/lwlock.c:1243
#5  0x00007f4653a0a9e4 in pgss_store (error_info=0x0, kind=PGSS_EXEC, jstate=0x0, walusage=0x0, bufusage=0x0, rows=0,
total_time=0, sys_info=0x0, cmd_type=<optimized out>, plan_info=0x0, query=0x3c43d18 "SELECT timestamp, value FROM obj
ects2_hash WHERE id = $1", queryid=17834662014628932523) at ../../../../../src/postgres/contrib/pg_stat_monitor/pg_stat_monitor.c:1233
#6  pgss_ExecutorStart (queryDesc=<optimized out>, eflags=<optimized out>) at ../../../../../src/postgres/contrib/pg_stat_monitor/pg_stat_monitor.c:402
#7  0x00007f465380029e in ybpgm_ExecutorStart (queryDesc=0x3c43e68, eflags=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:470
#8  0x0000000000884331 in PortalStart (portal=portal@entry=0x38ea118, params=params@entry=0x3c43d88, eflags=eflags@entry=0, snapshot=snapshot@entry=0x0) at ../../../../../../src/postgres/src/backend/tcop/pquery.c:531
#9  0x000000000087f68b in exec_bind_message (input_message=0x7ffdd512e580) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1861
#10 PostgresMain (argc=<optimized out>, argv=argv@entry=0x377f548, dbname=0x377f530 "test", username=0x377f518 "admin") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5112
#11 0x000000000049dda3 in BackendRun (port=0x366a960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4446
#12 BackendStartup (port=0x366a960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4112
#13 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#14 0x00000000007e7dbf in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x351a6c0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#15 0x00000000007336da in PostgresServerProcessMain (argc=23, argv=0x351a6c0) at ../../../../../../src/postgres/src/backend/main/main.c:234
#16 0x00000000007338d9 in main ()

**Comment by kmuthukk** [comment]
nice work getting to the bottom of this regression, @sushantrmishra .

**Comment by ramsrivatsa** [comment]
Fixed the performance drop with this commit --> [bb3a3c4](https://github.com/yugabyte/yugabyte-db/commit/bb3a3c4c67c1a6e4a43b5c3e5b97dcad8c38ca18)
