### ISSUE TITLE
[YSQL] Compare write/copy performance for hash, range, and colocated tables

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#10806]
In theory, the copy and write performance of the following should be the same:
1. single-tablet hash-split table
2. single-tablet range-split table
3. A colocated table alone in a tablegroup

We should test the following scenarios:
1. COPY/insert large number of rows
2. Index backfill on a large table (create index duration on a table with a large data size)

Note: for apples-to-apples on number of splits, we might need to disable dynamic tablet splitting with the flag:
```
enable_automatic_tablet_splitting = false
```

cc @sushantrmishra jfyi

**Comment by emhna** [comment]
Based on the test of the three tables (single-tablet with hash-split, single-tablet with range-split, and colocated table alone  in a tablegroup), all reads and writes showed minimal difference in latency performance.

The test was conducted on 1gb file with the same table schema on the same computer. 
The latency performance was recorded for the following operations:
- COPY command with primary key
- COPY command with primary key and secondary index   
- Index backfill with primary key
- Read on primary key
- Read on secondary index

In the past, colocated table had the worst time performance compared to the other table types but from this test, we found that there was almost no difference.
