### ISSUE TITLE
YSQL: Cache sys catalog read request on local t-server side

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#10821]
Jira Link: [DB-3251](https://yugabyte.atlassian.net/browse/DB-3251)
After landing the #9936 it will be possible to cache sys catalog read request on a local t-server side to improve postgres catalog cache refresh process.

**Comment by patriknw** [comment]
Related to https://github.com/yugabyte/yugabyte-db/issues/11997

**Comment by sharkberto** [comment]
If there is still backport work pending for stable releases, can we leave this open and tag with 2.14 / 2.16 Backport Required @tverona1  @d-uspenskiy I understand this is not yet ported to stable for those asking for tserver catalog caching

**Comment by jameshartig** [comment]
@sharkberto is this still planning on being backported to 2.14?

**Comment by sharkberto** [comment]
@jameshartig Not planning to backport to 2.14 - Sorry for any confusion
