### ISSUE TITLE
[YSQL][Driver] Implement YSQL Smart driver for C#

### ISSUE THREAD

**Issue by soccerties** [yugabyte/yugabyte-db#10826]
Jira Link: [DB-864](https://yugabyte.atlassian.net/browse/DB-864)
### Description

The only available driver for c# is [Npgsql](https://docs.yugabyte.com/latest/reference/drivers/ysql-client-drivers/#npgsql).

A smart driver with load balancing and topology awareness should be built.

**Comment by kneeraj** [comment]
Thanks for filing this @soccerties . @Sfurti-yb is about to be done with Python soon. @ashetkar to be done with Go and @Sfurti-yb is going to take this up later this week.
