### ISSUE TITLE
Install docs incorrect 

### ISSUE THREAD

**Issue by DALDEI** [YugaByte/yugabyte-db#1082]
https://docs.yugabyte.com/latest/admin/docker-compose/#2-initialize-the-apis

Shows:

> 
docker exec -it yb-master-n1 --  -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-n1:7100 home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"

Probably should be: 

> docker exec -it yb-master-n1 **/bin/bash** -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-n1:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"

Note:  -- -> /bin/bash
    home/  ->  /home/

**Comment by schoudhury** [comment]
Fixed
