### ISSUE TITLE
[DocDB] Distributed raft metadata across disks

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10842]
### Description

Currently raft and tablet metadata lives on the first location / drive in `fs_data_dirs`, while the actual data is bound to 1 particular disk, but that is picked at tablet creation in a round robin across the available drives.

As a path towards allowing disk fault tolerance, we need to make sure all of a tablet's data and metadata is bound to the same drive, so we don't have a single point of failure, but instead could lose any 1 disk independently.

**Comment by mikhpolitov** [comment]
done as part #11816
