### ISSUE TITLE
[YSQL] Select better index for a simple query with two indexes

### ISSUE THREAD

**Issue by timothy-e** [yugabyte/yugabyte-db#10840]
Jira Link: [DB-1222](https://yugabyte.atlassian.net/browse/DB-1222)
### Description

Currently the query planner selects the most recent index created, even if it results in a much slower query. In the below case, we should use yy_index regardless of the order the indices were created in.  
```sql
CREATE TABLE tbl (x INT, y INT);

INSERT INTO tbl (x, y) 
     SELECT g/100::INT AS x, g AS y 
       FROM generate_series(1,10000) AS g;

CREATE INDEX yy_index ON tbl (y ASC); 
CREATE INDEX xx_index ON tbl (x ASC);
```
Right now, the most recently created index is used 
```sql
EXPLAIN ANALYZE SELECT * FROM tbl WHERE y < 40 AND x < 40;
                           QUERY PLAN
\-----------------------------------------------------------------------------------------------------------------------
 Index Scan using xx_index on tbl (cost=0.00..16.75 rows=100 width=8) (actual time=394.938..1382.765 rows=39 loops=1)
  Index Cond: (x < 40)
  Filter: (y < 40)
  Rows Removed by Filter: 3960
 Planning Time: 45.125 ms
 Execution Time: 1383.698 ms
(6 rows)
```
If we make yy_index the most recently created index
```sql
DROP INDEX yy_index; 
CREATE INDEX yy_index ON tbl (y ASC); 
```

And then run the same query again, it will use `yy_index` and create a much faster query.

```sql
EXPLAIN ANALYZE SELECT * FROM tbl WHERE y < 40 AND x < 40;
                           QUERY PLAN
\--------------------------------------------------------------------------------------------------------------------
 Index Scan using yy_index on tbl (cost=0.00..16.75 rows=100 width=8) (actual time=26.266..26.394 rows=39 loops=1)
  Index Cond: (y < 40)
  Filter: (x < 40)
 Planning Time: 0.189 ms
 Execution Time: 26.605 ms
(5 rows)
```

**Comment by jaki** [comment]
Nice find.

> query planner selects the most recent index created

This isn't true all the time.  For example,

```sql
SET enable_seqscan = off;
CREATE TABLE tab (t text);
CREATE EXTENSION pg_trgm;
CREATE INDEX first ON tab USING gin (t gin_trgm_ops);
CREATE INDEX second ON tab (t);
EXPLAIN SELECT * FROM tab WHERE t ~ 'abc'; -- uses first
DROP INDEX first;
EXPLAIN SELECT * FROM tab WHERE t ~ 'abc'; -- uses second
```

**Comment by tedyu** [comment]
In the example above, index `first` was dropped.

If index `first` is kept, it would be used for the query.

**Comment by jaki** [comment]
@tedyu, I don't see what point you are trying to make.

I proved that the query planner doesn't always select the most recently created index.  The EXPLAIN right before the DROP INDEX proves it.  The EXPLAIN after the DROP INDEX proves that the second index was a viable candidate.
