### ISSUE TITLE
[YSQL] Improve JSON parsing of placement information

### ISSUE THREAD

**Issue by thepinetree** [yugabyte/yugabyte-db#10869]
Jira Link: [DB-1059](https://yugabyte.atlassian.net/browse/DB-1059)
### Description

The `ParseReplicationInfo` function in `placement_info.cc` has room for improvement. Based on potential customer usage, it might make sense to allow misspellings of the option name of `replica_placement` as `replicate_placement`. There may also be room for improved escaping.

cc: @spolitov

**Comment by SrivastavaAnubhav** [comment]
Closing because this doesn't make sense.
