### ISSUE TITLE
[Docs] [YSQL] Documentation needed for the yb_fdw extension.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#10870]
### Description

`yb_fdw` is one of the default roles in YSQL and is a beta feature as of 2.11. At the moment , there is a simple description in this doc : https://docs.google.com/document/d/1RFp3G0Mw_eLcqS_hc6sOGkOJktvuKiAYdocUAnkMVGE/edit#heading=h.846ve86z74lw

**Comment by ddhodge** [comment]
Role described under RBAC and in YB Managed.
