### ISSUE TITLE
[YSQL] Upgrade did not clean up the old postgres process

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1089]
This was observed in an internal test system. Upgrade did not clean up the old postgres process .

**Comment by mbautin** [comment]
Some observations:
```
[yugabyte@ip-172-151-25-83 ~]$ ps -ef | grep postgres
yugabyte 11074 31432  0 02:00 ?        00:00:00 [postgres]
yugabyte 11076 10888  0 02:00 pts/0    00:00:00 grep --color=auto postgres
yugabyte 19255 25507 15 Mar27 ?        06:48:51 postgres: postgres postgres 172.151.30.86(50384) INSERT
yugabyte 19256 25507 15 Mar27 ?        06:49:36 postgres: postgres postgres 172.151.30.86(50386) INSERT
yugabyte 19273 25507 21 Mar27 ?        09:23:53 postgres: postgres postgres 172.151.30.86(50412) idle
yugabyte 25507     1  0 Mar27 ?        00:00:00 /home/yugabyte/yb-software/yugabyte-ee-1.2.2.0-b2-centos-x86_64/postgres/bin/postgres -D /mnt/d0/pg_data -p 5433 -h 172.151.25.83 -k  -c logging_collector=on -c log_directory=/mnt/d0/yb-data/tserver/logs
yugabyte 25518 25507  0 Mar27 ?        00:00:00 postgres: logger
yugabyte 25520 25507  0 Mar27 ?        00:00:00 postgres: checkpointer
yugabyte 25521 25507  0 Mar27 ?        00:00:31 postgres: stats collector
```
When we launch the postgres process from the tserver, we should store its pid somewhere (ideally independently from postgres's own pidfile), and then on tserver restart we need to kill the postgres process if it is still running.

**Comment by mbautin** [comment]
In the `ps` output above, pid `25507` is the old postgres process that was started by the old tserver.

**Comment by robertpang** [comment]
When yb-tserver terminates a child process on Linux (in this case the `postgres` subprocess), it just delivers a [`SIGTERM`](https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/util/subprocess.cc#L310) signal. `SIGTERM` is the same signal `pg_ctl stop` delivers in [`SMART`](https://www.postgresql.org/docs/11/app-pg-ctl.html) mode, which waits for clients to disconnect. To stop the `postgres` process without waiting for client to disconnect ([`FAST`](https://www.postgresql.org/docs/11/app-pg-ctl.html) mode), `pg_ctl` delivers [`SIGINT`](https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/bin/pg_ctl/pg_ctl.c#L1983) instead. We should switch to deliver the `SIGINT` signal to stop `postgres` instead.

**Comment by kmuthukk** [comment]
What about SIGKILL @robertpang ?

On slack channel, a user mentioned: 

<< hmm, something is keeping alive the process and restarting again it after the signal
even after a SIGKILL >>

**Comment by mbautin** [comment]
@ndeodhar: we need to parameterize the `Subprocess` class to be able to customize the signal that the child process would receive on parent process termination, and as @robertpang mentioned, we need to set that signal to `SIGINT` for the PostgreSQL child process.

See this in `subprocess.cc`:
```
    // TODO: prctl(PR_SET_PDEATHSIG) is Linux-specific, look into portable ways
    // to prevent orphans when parent is killed.
    prctl(PR_SET_PDEATHSIG, SIGTERM);
```
