### ISSUE TITLE
Implement TSCARD, TSFIRSTN, TSLASTN and other remaining TS commands

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#109]
Take the following TS example:
```
> TSAdd k 10 “ten”
“OK”
> TSAdd k 20 “twenty” 30 “thirty” 40 “forty”
“OK”
```

For FirstN or LastN like use cases we can efficiently use iterators to implement
- TSFirstN == ZRange 0 <x>
```
> TSFirstN k, 2
“ten”
“twenty”
```

- TSLastN == ZRange <x> -1 
```
> TSLastN k, 2
“thirty”
“forty”
```

- TSCard == ZCard
```
> TSCard k
4
```

**Comment by pritamdamania87** [comment]
Implemented in https://github.com/YugaByte/yugabyte-db/commit/29058a0006e3dd4d2344975bb355b4f6f58d22c1 and https://github.com/YugaByte/yugabyte-db/commit/907243ab26b68eed4e0b88a01e51f302a97591c4

**Comment by pritamdamania87** [comment]
TSFirstN not yet implemented since we don't have a use case for it yet.
