### ISSUE TITLE
[Platform][Backup] Backup is failing in itests

### ISSUE THREAD

**Issue by yorq** [yugabyte/yugabyte-db#10907]
### Description

Multiple tests are failing due to errors in backup functionality
Examples: 
1) https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-developer/2809/  - 2.11x build
2) https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-developer/2828/  - 2.6x build

Error looks like
`2021-12-17 12:53:54,319 ERROR: Failed to run command [[ scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /opt/yugabyte/yugaware/data/keys/0c53ead8-5a21-4982-81f8-d1ee0a4c709d/yb-itest-7b9dd2c6a4-20211217-123309_0c53ead8-5a21-4982-81f8-d1ee0a4c709d-key.pem -P 54422 -q /tmp/yb_backup_rflogzfcfxqstdgz/cloud_cfg yugabyte@10.9.203.45:/tmp/yb_backup_rflogzfcfxqstdgz ]]: code=1 output=scp: /tmp/yb_backup_rflogzfcfxqstdgz/cloud_cfg: Permission denied`

It happens probably because two upload processes are running simultaneously
`2021-12-17 12:53:53,158 INFO: Uploading /tmp/yb_backup_rflogzfcfxqstdgz/cloud_cfg to server 10.9.203.45
2021-12-17 12:53:53,538 INFO: Uploading /tmp/yb_backup_rflogzfcfxqstdgz/cloud_cfg to server 10.9.203.45`

**Comment by streddy-yb** [comment]
hi @OlegLoginov - Can you do the 2.8 backport asap? 2.8.1 release is going out later today. thanks
