### ISSUE TITLE
[YSQL] Add column to Partitioned Table

### ISSUE THREAD

**Issue by erosasmob** [yugabyte/yugabyte-db#10913]
### Description

Hi.
I am having an issue adding a column to an empty partitioned table.
Executing the following steps:

create table subscribers (id bigint not null, name varchar(2000) not null, constraint pk_subscribers primary key ( id )) partition by range (id);
create table p_subscribers_1 partition of subscribers for values from (minvalue) to (2) with (fillfactor=90);
alter table subscribers add if not exists age numeric(18);

select * from subscribers;

I get the error in the select statement:
SQL Error [XX000]: ERROR: Invalid argument: Invalid column number 3

Thank you and best regards.

**Comment by deeps1991** [comment]
The fix is work-in-progress and expected to be in soon. This is already being tracked here: https://github.com/yugabyte/yugabyte-db/issues/9547
