### ISSUE TITLE
[xCluster] Automatically Replicate the Indexes of a Table using xCluster Asynchronous Replication

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#10957]
Jira Link: [DB-801](https://yugabyte.atlassian.net/browse/DB-801)
### Description

While replicating tables using  xCluster Asynchronous Replication, indexes of the replicated table do not get replicated over. They have to be replicated as part of the initial `setup_universe_replication` command or added after the fact using `alter_universe_replication`. This is an issue for scenarios where a single table may have a large number of indexes. We should automatically replicate indexes of the replicated table to the target cluster without requiring users to have to call out the indexes themselves. 

[DB-801]: https://yugabyte.atlassian.net/browse/DB-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dotyjim-work** [comment]
[[docdb] xCluster Roadmap · Issue #10319 · yugabyte/yugabyte-db](https://github.com/yugabyte/yugabyte-db/issues/10319)

Has a section that talks about **DDLs**, but I don't see an item that talks specifically about flowing DDL changes, however platform has an issue that addresses this.

_[Platform] xCluster replication management through Platform_ · Issue #8963 [^1]

[^1]: [PLAT-580](https://yugabyte.atlassian.net/browse/PLAT-580)

> Allow safe DDL changes to be propagated automatically to target universes

But we do have some internal discussions taking place:
* [XCluster + Metadata Alters - Google Docs](https://docs.google.com/document/d/1tabzZy9pFuc6_-_OgzRs2IH6TpILqtdrjwqHa0jsr78/edit#)
* [Unidirectional 2dc + backfill proposals - Google Docs](https://docs.google.com/document/d/1ajCb-N0E1KprWZHhJdd_ZDkqIG6fTv3DLo1aKr7EoGQ/edit) (relevant for tables with data already - see https://github.com/yugabyte/yugabyte-db/issues/7613)
