### ISSUE TITLE
[yb-ctl] fails to create new cluster of rf3

### ISSUE THREAD

**Issue by pbharath** [YugaByte/yugabyte-db#1095]
YB Release: 1.2.2.0 COMMUNITY EDITION
Mac OS Mojave - 10.14.3
Hard Drive: SSD

**○ → ./bin/yb-ctl --data_dir $YB_DATA_DIR --replication_factor 3 create**
2019-03-29 20:10:25,357 INFO: Starting master-1 with:
/Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-master --fs_data_dirs "/Users/pbharath/Data/YugaByte/node-1/disk-1,/Users/pbharath/Data/YugaByte/node-1/disk-2" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root "/Users/pbharath/Soft/YugaByte/1.2.2.0/www" --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 >"/Users/pbharath/Data/YugaByte/node-1/disk-1/master.out" 2>"/Users/pbharath/Data/YugaByte/node-1/disk-1/master.err" &
2019-03-29 20:10:25,378 INFO: Starting master-2 with:
/Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-master --fs_data_dirs "/Users/pbharath/Data/YugaByte/node-2/disk-1,/Users/pbharath/Data/YugaByte/node-2/disk-2" --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root "/Users/pbharath/Soft/YugaByte/1.2.2.0/www" --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 >"/Users/pbharath/Data/YugaByte/node-2/disk-1/master.out" 2>"/Users/pbharath/Data/YugaByte/node-2/disk-1/master.err" &
2019-03-29 20:10:25,400 INFO: Starting master-3 with:
/Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-master --fs_data_dirs "/Users/pbharath/Data/YugaByte/node-3/disk-1,/Users/pbharath/Data/YugaByte/node-3/disk-2" --webserver_interface 127.0.0.3 --rpc_bind_addresses 127.0.0.3 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root "/Users/pbharath/Soft/YugaByte/1.2.2.0/www" --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 >"/Users/pbharath/Data/YugaByte/node-3/disk-1/master.out" 2>"/Users/pbharath/Data/YugaByte/node-3/disk-1/master.err" &
2019-03-29 20:10:25,422 INFO: Starting tserver-1 with:
/Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-tserver --fs_data_dirs "/Users/pbharath/Data/YugaByte/node-1/disk-1,/Users/pbharath/Data/YugaByte/node-1/disk-2" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root "/Users/pbharath/Soft/YugaByte/1.2.2.0/www" --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1 --cql_proxy_bind_address=127.0.0.1 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1 >"/Users/pbharath/Data/YugaByte/node-1/disk-1/tserver.out" 2>"/Users/pbharath/Data/YugaByte/node-1/disk-1/tserver.err" &
2019-03-29 20:10:25,441 INFO: Starting tserver-2 with:
/Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-tserver --fs_data_dirs "/Users/pbharath/Data/YugaByte/node-2/disk-1,/Users/pbharath/Data/YugaByte/node-2/disk-2" --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root "/Users/pbharath/Soft/YugaByte/1.2.2.0/www" --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.2 --cql_proxy_bind_address=127.0.0.2 --local_ip_for_outbound_sockets=127.0.0.2 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.2 >"/Users/pbharath/Data/YugaByte/node-2/disk-1/tserver.out" 2>"/Users/pbharath/Data/YugaByte/node-2/disk-1/tserver.err" &
2019-03-29 20:10:25,459 INFO: Starting tserver-3 with:
/Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-tserver --fs_data_dirs "/Users/pbharath/Data/YugaByte/node-3/disk-1,/Users/pbharath/Data/YugaByte/node-3/disk-2" --webserver_interface 127.0.0.3 --rpc_bind_addresses 127.0.0.3 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root "/Users/pbharath/Soft/YugaByte/1.2.2.0/www" --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.3 --cql_proxy_bind_address=127.0.0.3 --local_ip_for_outbound_sockets=127.0.0.3 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.3 >"/Users/pbharath/Data/YugaByte/node-3/disk-1/tserver.out" 2>"/Users/pbharath/Data/YugaByte/node-3/disk-1/tserver.err" &
2019-03-29 20:10:25,513 INFO: Waiting until we have enough tablet servers (currently 3)
2019-03-29 20:10:29,129 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:32,733 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:36,333 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:39,933 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:43,537 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:47,134 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:50,734 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:54,332 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:10:57,931 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:11:01,528 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:11:05,131 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:11:08,729 INFO: Waiting until we have enough tablet servers (currently 1)
2019-03-29 20:11:12,270 ERROR: Failed waiting for 1 tservers, got None
Traceback (most recent call last):
  File "./bin/yb-ctl", line 992, in <module>
    ClusterControl().run()
  File "./bin/yb-ctl", line 983, in run
    self.args.func()
  File "./bin/yb-ctl", line 840, in create
    self.run_cluster_wide_postgres_initdb()
  File "./bin/yb-ctl", line 943, in run_cluster_wide_postgres_initdb
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 783, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for Yugabyte cluster!")
RuntimeError: Timed out waiting for Yugabyte cluster!

**yb-tserver.ERROR Log File**
Log file created at: 2019/03/29 20:10:29
Running on machine: Bharaths-MacBook-Pro.local
Application fingerprint: version 1.2.2.0 build 2 revision 91b8a670728f0ec551ef494960aedc068c43abb5 build_type RELEASE built at 26 Mar 2019 11:17:57 PST
Running duration (h:mm:ss): 0:00:02
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0329 20:10:29.414355 95166464 async_initializer.cc:88] Failed to initialize client: Timed out (yb/rpc/outbound_call.cc:446): Could not locate the leader master: GetMasterRegistration RPC to 127.0.0.2:7100 timed out after 2.500s
E0329 20:10:29.488019 117166080 async_initializer.cc:88] Failed to initialize client: Timed out (yb/rpc/outbound_call.cc:446): Could not locate the leader master: GetMasterRegistration RPC to 127.0.0.3:7100 timed out after 2.500s
E0329 20:10:32.920395 95166464 async_initializer.cc:88] Failed to initialize client: Timed out (yb/rpc/outbound_call.cc:446): Could not locate the leader master: GetMasterRegistration RPC to 127.0.0.3:7100 timed out after 2.500s
E0329 20:10:32.991907 117166080 async_initializer.cc:88] Failed to initialize client: Timed out (yb/rpc/outbound_call.cc:446): Could not locate the leader master: GetMasterRegistration RPC to 127.0.0.2:7100 timed out after 2.500s
....

**○ → ps aux | grep yb-master**
pbharath          3280   0.0  0.1  4412280  25432 s001  S     8:10PM   0:00.99 /Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-master --fs_data_dirs /Users/pbharath/Data/YugaByte/node-1/disk-1,/Users/pbharath/Data/YugaByte/node-1/disk-2 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root /Users/pbharath/Soft/YugaByte/1.2.2.0/www --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100
pbharath          3693   0.0  0.0  4268060    824 s001  S+    8:14PM   0:00.00 grep --color=auto yb-master

**○ → ps aux | grep yb-tserver**
pbharath          3736   0.0  0.0  4268060    824 s001  S+    8:15PM   0:00.00 grep --color=auto yb-tserver
pbharath          3289   0.0  0.1  4442384  41736 s001  S     8:10PM   0:02.79 /Users/pbharath/Soft/YugaByte/1.2.2.0/bin/yb-tserver --fs_data_dirs /Users/pbharath/Data/YugaByte/node-1/disk-1,/Users/pbharath/Data/YugaByte/node-1/disk-2 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/pbharath/Soft/YugaByte/1.2.2.0 --webserver_doc_root /Users/pbharath/Soft/YugaByte/1.2.2.0/www --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1 --cql_proxy_bind_address=127.0.0.1 --local_ip_for_outbound_sockets=127.0

**Comment by pbharath** [comment]
UPDATE: 
I attempted multiple times (rf3 and rf5) after opening the issue. During one attempt, I was able to get the cluster up and running for rf3. I have no logical explanation as this was brute force attempt to install until success. 

My observations of two repeatable scenarios -
Case 1 - Log Error Message: Could not locate the leader master: GetMasterRegistration RPC to 127.0.0.3:7100 timed out after 2.500s
=> Based on CLI output and log error message, it appears as though the first tserver is unable to reach master and does not proceed to the next tservers.  CLI does not update status and process is frozen forever. Have to apply Ctrl+C to break.

Case 2. Log Error Message:   Network error (yb/util/net/socket.cc:369): Error binding socket to 127.0.0.3:9100: Can’t assign requested address.
=> Based on CLI output and log error message, probably (rf-1) tservers seem to be provisioned and fails with the last tserver.  

Both these scenarios were repeatable for rf3 and rf5 options.

You can decide whether to close or investigate the issue further.

**Comment by ttyusupov** [comment]
Hi @pbharath , probably issue you faced was fixed by this commit - https://github.com/YugaByte/yugabyte-db/commit/bdec7bdc2b48301c6b097cf7f54e5bb425bdc2e3, could you try again with a latest yugabyteDB version? https://docs.yugabyte.com/latest/quick-start/
