### ISSUE TITLE
[xCluster] Make xCluster replication APIs atomic 

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10977]
### Description

Currently, setup/modify/delete replication APIs are synchronous but not atomic, leading to cases where cdc_state and cluster config can have partially applied state from one of these calls.

**Comment by nspiegelberg** [comment]
Scoping:

1. Analyze all the failure points of SetupUniverseReplication.  All failure paths should move the Universe State to FAILURE.
2. Add a background GC function on the Consumer for Universes.  Add this into `CatalogManagerBgTasks::Run`.  See `FindCDCStreamsMarkedAsDeleting`.  This will handle any deletes on both the Producer & Consumer that are necessary for rolling back a Universe.
3. Repeat for AlterUniverseReplication.  The main difference here is Merging.
4. Handle DeleteUniverseReplication.  This should handle finishing a partial Delete that has started.
