### ISSUE TITLE
[xCluster] Create API to Wait for Replication Drain

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10978]
Jira Link: [DB-1155](https://yugabyte.atlassian.net/browse/DB-1155)
### Description

For XCluster, we don't have an explicit API to verify when the Producer & Consumer are in sync.  The normal mode of operation should include lag, since XCluster is asynchronous.  However, there are some use cases where we would want to understand if the Producer has completely sent all operations to the Consumer (drain).

1. Cluster Migration.  Stop writes on the old cluster (Producer).  Don't use the new cluster (Consumer) until all transactions are sent over.
2. Schema Alters.  Since we don't have full DDL support yet, it can be safer to just stop writes and change both sides before continuing.  When doing this, we need to ensure there are no outstanding OPs with the old schema.
3. Testing.  The customer is using synthetic data and wants to verify that XCluster works and is drained before continuing the next round of test data.
4. Truncates and PITR.  (@rahuldesirazu for more info)

Additionally, if we extended this "drain" API to include an OpID or Timestamp, we use this API to wait for a particular catch up window when bootstrapping XCluster.

---------------------------------------------------------------------------------
Implementation Notes:

1. Currently, the user can look at per-tablet metrics using Prometheus or Platform: "async_replication_committed_lag_micros", "last_checkpoint_opid_index".  
2. We need to aggregate into per-table or a more user-friendly abstraction and verify that all tablets in that schema are caught up.
3. To ensure that we don't have any new writes, we need to check the "current_term" or "last_appended" on each tablet.  Some clarification is here.
4. We need to think of some heuristic to verify drain and not additional writes.  Maybe query all tablets that are not caught up, then do one final query after we think we're caught up to verify?

**Comment by nspiegelberg** [comment]
This API would need to disable splitting while waiting for the drain or take that into account.

**Comment by bmatican** [comment]
@hari90 taking this one back for now, as it might be a bit more work than initially thinking.

I'll pass you a separate one as an intro to producer side code first, instead.
