### ISSUE TITLE
[xCluster] Support automatic detection of new masters in case of decomission or full move

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10979]
### Description

Currently the user has to call alter_universe_replication if there is a source side master full-move or decommission. Ideally, the target DB logic should automatically figure out these new addresses.

**Comment by dotyjim-work** [comment]
@rahuldesirazu - is this a duplicate of https://github.com/yugabyte/yugabyte-db/issues/9688?

**Comment by rahuldesirazu** [comment]
Yes this is a duplicate of #9688, I will close it.
