### ISSUE TITLE
[xCluster] Test xCluster with RPC Compression

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10985]
### Description

Steps for testing:

1. Setup xCluster replication (single table) on a release version without RPC compression.
2. Start a workload.
3. Upgrade the producer side to a release with RPC compression and verify that replication still flows.
4. Upgrade the consumer side as well and verify that replication flows.

**Comment by shashwat-yb** [comment]
Validated and landed itest-system testcase for xcluster with RPC compression.
https://bitbucket.org/yugabyte/internal-services/commits/a17be8cdbeec9ff9245bca864ddb6aa236eb9194
cc @VijiYB @Arjun-yb
