### ISSUE TITLE
[xCluster] Test PITR workflow

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10982]
### Description

Steps for testing:

1. Setup unidirectional xCluster replication with a single table.
2. Create a backup on the target cluster.
3. Drop the table on the source side to simulate a mistake.
4. Pause replication and perform a PITR on both clusters to the same timestamp to recover the table.
5. Resume replication and ensure that the target cluster is able to receive writes.
6. Pause replication, wait for lag to become 0, and do a select COUNT(*) on both sides to ensure that the clusters are consistent.

**Comment by Arjun-yb** [comment]
Validated with **2.11.2.0**
It works, Used steps are as below

**Steps**:

> Setup unidirectional xCluster replication with a single table.
> Start data loading to the table
> Create snapshot schedule on both universes(source and target)
> Collect the time
> Create a backup on the target cluster.
> Drop the table on the source side to simulate a mistake. - Here loading data errored out as there is not table( I was loading through .sql file, cmd: bin/ysqlsh -h <host> -d <database> -f <file.sql>).
> Pause replication and perform a PITR on both clusters to the same timestamp to recover the table. - Again I started data loading
> Resume replication and ensure that the target cluster is able to receive writes.
> Stop data loading process, Pause the replication, wait for lag to become 0, and do a select COUNT(*) on both sides to ensure that the clusters are consistent.
