### ISSUE TITLE
[xCluster] Document Flow For Geo-partitioning

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10983]
### Description

@Arjun-yb Would you mind sharing some of the steps you went through to setup replication on geo-partitions?

**Steps:**
1. Create 2 universes(**source** and **target**) with same configs(with same regions and zones as below)
Ex:
**Regions**: EU(Paris), Asia Pacific(Mumbai) and US West(Oregon)
**Zones**: eu-west-3a, ap-south-1a and us-west-2a

2. Create table, table spaces and partition tables at source and target
Ex:
**Main table**: transactions
**Table spaces**: eu_ts, ap_ts and us_ts
**Partition Tables**: transactions_eu, transactions_in and transactions_us

**Steps to create Replication(Unidirectional):**
1. Collect child table UUIDs from source universe (**partition tables**, here transactions_eu, transactions_in and transactions_us) - these will be used while setting up replication
2. Run replication setup cmd at source universe - 
`bin/yb-admin -master_addresses <consumer_master_addresses> setup_universe_replication <producer universe UUID> <producer_master_addresses> <comma_separated_table_ids>`
3. Observe replication setup in UI(Replication tab in source universe)
4. Do some DMLs(insert/update/delete) to parent table of source and observe the replication at target side(in parent table and partition tables).

**Comment by Arjun-yb** [comment]
@rahuldesirazu added steps to setup replication on geo-partitions in the description

**Comment by Arjun-yb** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/11568
Added instructions(Steps) in the doc and merged the PR
