### ISSUE TITLE
[YSQL] Expose function for hybrid clock time

### ISSUE THREAD

**Issue by patriknw** [yugabyte/yugabyte-db#10996]
Jira Link: [DB-696](https://yugabyte.atlassian.net/browse/DB-696)
### Description

Is there any API to retrieve a timestamp that is guaranteed to only move forward? We don't need it to have that property on a global level but would be nice per tablet.

I assume transaction_timestamp() doesn't have that property unless provided by the OS or NTP setup.

Would it be possible to add a function that returns the timestamp of the hybrid clock, which I think has this property?

**Comment by ddorian** [comment]
@patriknw can you explain the use case?

**Comment by ddorian** [comment]
Maybe you can use Twitter snowflake ids for this? That's why they were created for.

**Comment by ddorian** [comment]
> For event sourced entities we store the events with a strict monotonic increasing sequence number for each entity id. That sequence number is managed by the application layer. Each entity is single writer.

Maybe you can have a sequence for each entity here? How many entities do you have?

**Comment by rthallamko3** [comment]
Based on offline conversation. YCQL function that touches on somewhat relevant functionality: https://docs.yugabyte.com/preview/api/ycql/expr_fcall/#writetime-function, which allows you to select the write time of a particular column can be used.
