### ISSUE TITLE
"Operation timed out " exception when creating a table....

### ISSUE THREAD

**Issue by praneeth-nimmagadda** [YugaByte/yugabyte-db#11]
There is Operation timed out exception when performing "CREATE TABLE" as shown in the below image... But when running "DESCRIBE TABLES" , table is existing...

This is happening when I am running YB via "./yb-docker-ctl create" that is using docker...

![image](https://user-images.githubusercontent.com/8910583/34289741-f0da5eaa-e719-11e7-8c7e-3f14d24d6f40.png)

**Comment by ramkumarvs** [comment]
@praneeth-nimmagadda Thanks for reporting this, will triage this issue.

**Comment by kmuthukk** [comment]
@praneeth-nimmagadda : Perhaps the operation took just a little longer in your environment than the client timeout. But on the server side, the table creation might have gone through fine.

Can you do a describe on "table1" to make sure its schema was created just fine? Thanks!

**Comment by praneeth-nimmagadda** [comment]
@kmuthukk :   So yeah schema got created fine, but the error is thrown almost all the time when running CREATE statements via YB-Docker...

**Comment by kmuthukk** [comment]
We figured out the issue @praneeth-nimmagadda . The default tablets/shards we were starting off with for each table were a bit too high for docker/local dev test environment, causing the create table operation to take a bit longer.  We'll put out a fix for this soon to lower those defaults.

CC: @ramkumarvs

**Comment by ramkumarvs** [comment]
This issue is fixed, please download the latest yb-docker-ctl from https://downloads.yugabyte.com/yb-docker-ctl and run the containers.
