### ISSUE TITLE
Allow redis reads from followers

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#110]
Add a new tserver gflag.

When the flag is enabled for the tservers, it will allow the tserver's query layer to route a Redis read request to any tserver within the same DC/region/AZ even if that tserver is not the leader.

**Comment by hectorgcr** [comment]
Ran a redis workload in a real cluster (AWS, 3 nodes, multi-AZ)
With the flag set to false (default): Avg. latency with 2 reader threads: 0.84 ms
With the flag set to true: Avg. latency with 2 reader threads: .17 ms
