### ISSUE TITLE
[YCQL] Syntax change - remove "yet" from "changing the number of tablets is not supported"

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#11001]
Jira Link: [DB-756](https://yugabyte.atlassian.net/browse/DB-756)
### Description

```
ycqlsh> CREATE TABLE test.i ( i int, PRIMARY KEY (i) )  with default_time_to_live = 0 AND tablets = 48 AND transactions = {'enabled': 'false'};

ycqlsh> alter table test.i with tablets=50
   ... ;
SyntaxException: Feature Not Supported. Changing the number of tablets is not supported yet
alter table test.i with tablets=50
                        ^^^^^^^
;
 (ql error -14)
```

I understand we won't ever allow changing tablets from the ycqlsh shell - so this error message might ideally say just "Changing the number of tablets is not supported" or might note "changing the number of tablets is only supported using yb-admin" or similar.

**Comment by na6vj** [comment]
https://github.com/yugabyte/yugabyte-db/commit/75f74e1fcf567f2097d0fdeeedcbc7850fa74067

**Comment by na6vj** [comment]
Fixed unit test also:
https://github.com/yugabyte/yugabyte-db/commit/58765e397bc32b640e058abc6236f965418b6935
