### ISSUE TITLE
Master has durable_wal_write enabled by default in tests

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#11011]
This could be causing long fsync latencies and intermittent test failures.

**Comment by mbautin** [comment]
The test stability improvement from disabling durable_wal_write in tests is substantial. The "timed out waiting for master leader" errors are virtually nonexistent after this change.
![image](https://user-images.githubusercontent.com/552936/148459996-220f0f73-a19f-408f-9383-3ef8bae1a590.png)

**Comment by SrivastavaAnubhav** [comment]
Fixed by 282ecae.
