### ISSUE TITLE
[xCluster] Improve Table Alter Cutover

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#11017]
Jira Link: [DB-1075](https://yugabyte.atlassian.net/browse/DB-1075)
### Description

Currently, the flow for altering a table under xCluster replication is to stop writes to both Clusters, drain replication, manually verify the drain through metrics, then alter both sides.  If this is not done, then records from the old schema risk being applied to the new schema.  This is often not a practical issue with add or drop optional columns but can be a problem with updating existing columns, adding required columns, or verifying that the exact data stored is equivalent.

This process has many downsides.  The Producer cluster must take write downtime, the cutover process is unclear, and schema validation is absent (resulting in issues like #10185).  To improve alter cutover, we need:

1. Flow DDL change information to the Consumer & halt replication when a schema transition occurs on the Tablet.
2. Synchronously wait for all tablets in a Consumer table to receive the same write operation.
3. Validate that schemas on the both side match after Consumer alter.
4. Display schema differences / Repair column ID mismatches

**Comment by nspiegelberg** [comment]
There is an Alternative strategy being discussed with vendors who use 3rd party apps to apply DDls:

1. Stop Writes to Producer (from app)
2. Use XCluster command to wait for Producer Drain (#10978)
3. Validate that schemas on the both side match after Consumer alter.
4. Display schema differences / Repair column ID mismatches
