### ISSUE TITLE
[Docs] [Core] NOW() function should be taken out of the row-level geo-partitioning example

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#11025]
### Description

In the row-level geo-partitioning docs [here](https://docs.yugabyte.com/latest/explore/multi-region-deployments/row-level-geo-partitioning/#step-1-create-table-with-partitions)

we call out this example for the table schema:

`CREATE TABLE transactions (
    user_id   INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    geo_partition VARCHAR,
    account_type VARCHAR NOT NULL,
    amount NUMERIC NOT NULL,
    txn_type VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
) PARTITION BY LIST (geo_partition);
`

However using the NOW() function causes high latencies. I would recommend removing this function as it will cause inaccurate performance results for any users following this example. 

https://yugabyte.slack.com/archives/CDQB8MEAU/p1641577948011900

**Comment by aishwarya24** [comment]
The latency issue is now fixed in the code and here is the ticket : https://github.com/yugabyte/yugabyte-db/issues/5536 . 
Confirmed with @deeps1991 as well that latency will not be high anymore. So, the change is not required and I'm closing the issue.
