### ISSUE TITLE
[DocDB] Make the statistic log_bytes_logged include the header

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#11036]
Jira Link: [DB-1032](https://yugabyte.atlassian.net/browse/DB-1032)
### Description

Currently, the 12 byte header for WAL writes is not accounted in the statistic log_bytes_logged, which means the statistic does not actually represent the amount of bytes logged, instead it accounts the WAL data that is logged without the 12 byte header.

**Comment by Huqicheng** [comment]
@rthallamko3 Should have been fixed by @spolitov. Closing it.
