### ISSUE TITLE
[YSQL] CREATE TABLE without a primary key followed by ALTER TABLE adding a primary key should end up with one primary key

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1104]
1) Currently, the PK specification has to be done inline as part of the CREATE TABLE. In YugabyteDB, the PK columns  guides the primary dimension in which the table is laid out in storage (so that retrieval by those PK column lookups is as efficient).

2) Creating the PK afterwards using an ALTER is not just  syntax sugar work, but will actually involve reorganizing the on-disk structure of the table in a way that it is now organized by the PK as the primary dimension. So, with YugabyteDB it'll be advantageous if the system can be told upfront as part of the CREATE TABLE what the PK columns are.

Nevertheless, we should support ALTER TABLE to allow adding a PRIMARY KEY after the fact to be compatible with the broader ecosystem of tools.

**Comment by nocaway** [comment]
Once Hector completes the work on partitioning, this enhancement can be done.

**Comment by ndeodhar** [comment]
One possible approach can be to enhance index backfill for this: https://github.com/YugaByte/yugabyte-db/issues/448

Similar to creating index, when we run `ALTER TABLE ADD PRIMARY KEY`, we should:
1. Create a new table with the PK.
2. Any writes to old table should go to both old and new tables.
3. Backfill new table with entries from old table.
4. Switch all writes to only write to new table.
5. Drop old table.
cc: @amitanandaiyer

**Comment by ben-pr-p** [comment]
This currently makes restoring from `pg_dump` impossible, since `pg_dump` chooses to add all indexes and constraints (and therefore primary keys as well) in it's "post-data" phase, since they may slow down the copy that might be there

**Comment by ndeodhar** [comment]
@ben-pr-p You can use `ysql_dump` utility to create the database dump and then restore it. This will take care of ensuring that schema and constraints are in YB format.
Note that you can use `ysql_dump` to take a dump of vanilla postgres DB as well.

**Comment by ben-pr-p** [comment]
Oh, neat! I'm having difficulty finding installation instructions for `ysql_dump` – do you know where those are?

**Comment by ndeodhar** [comment]
It'll be in `<yugabyte_install_dir>/postgres/bin` folder. It's a modified version of `pgdump`, so usage will be similar.

**Comment by frozenspider** [comment]
> One possible approach can be to enhance index backfill for this: #448
> 
> Similar to creating index, when we run `ALTER TABLE ADD PRIMARY KEY`, we should:
> 
>     1. Create a new table with the PK.
> 
>     2. Any writes to old table should go to both old and new tables.
> 
>     3. Backfill new table with entries from old table.
> 
>     4. Switch all writes to only write to new table.
> 
>     5. Drop old table.
>        cc: @amitanandaiyer

We aren't planning to implement this - original PostgreSQL code takes `AccessExclusiveLock` on a table for `ALTER TABLE ADD PRIMARY KEY`, preventing concurrent writes.

**Comment by frozenspider** [comment]
Note that the current implementation has a few limitations. Specifically:
* We don't yet support concurrent DMLs while this ALTER is in progress.
* The following cases are not supported as of now:
  * Colocated tables (including tablegroups).
  * Partitioned tables and table partitions.
  * Table having rules.
  * `ALTER TABLE ADD CONSTRAINT PK USING INDEX`
* If the table was created using `WITH (table_old = x)` (beta feature), that OID is lost without notice.
* There are minor mismatches between YB and PG when migrating data fails (`SQLSTATE` is matching):
  * Null value in PK column
  * Duplicate PK

**Comment by uwejan** [comment]
Hello guys, good work. Is there an ETA for this feature? adding PK after column is really important with my project.

**Comment by frozenspider** [comment]
Sorry @uwejan, missed your comment. It's included in v2.6 onward.
