### ISSUE TITLE
[Docs] Update the docs to point to the stable/latest version of KairosDB

### ISSUE THREAD

**Issue by Anagha-Damodaran** [yugabyte/yugabyte-db#11057]
### Description

The document [KairosDB | YugabyteDB](https://docs.yugabyte.com/latest/integrations/kairosdb/#root) Docs suggests kairosDB 1.2 which is obsolete and not available in GIT repo, The current stable version is KairosDB 1.3. Can we please get this updated?

**Comment by polarweasel** [comment]
(Just waiting for confirmation from integrations team that this is a non-breaking change.)

**Comment by Anagha-Damodaran** [comment]
The below section also has issues. The links provided are also broken. 


https://docs.yugabyte.com/latest/integrations/kairosdb/#root

Push data
 
Push metric data into KairosDB as per the instructions [here](http://kairosdb.github.io/docs/build/html/PushingData.html).

Query data
 
Query metric data into KairosDB as per the instructions [here](http://kairosdb.github.io/docs/build/html/QueryingData.html).
