### ISSUE TITLE
[YCQL] currenttimestamp() stores the data in different format to that when queried

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#11052]
Jira Link: [DB-1000](https://yugabyte.atlassian.net/browse/DB-1000)
### Description

Customer is inserting data into a table using currenttimestamp(), but cannot query based on the value.
The workaround is to use totimestamp(now()), but customer wants to use currenttimestamp().

See test case.

cassandra@ycqlsh:myapp> CREATE TABLE myapp.nvbase (
         ... name text,
         ... createdon timestamp,
         ... id int,
         ... PRIMARY KEY ((name, createdon))
         ... ) WITH default_time_to_live = 0
         ... AND transactions = {'enabled': 'false'};
         

cassandra@ycqlsh:myapp> insert into myapp.nvbase(id,name,createdon) values(3,'atul',currenttimestamp());
cassandra@ycqlsh:myapp> select * from myapp.nvbase ;
 name | createdon                       | id
------+---------------------------------+----
 atul | 2022-01-11 15:21:38.117000+0000 |  3
(1 rows)

cassandra@ycqlsh:myapp> select * from myapp.nvbase where createdon = '2022-01-11 15:21:38.117000+0000';
 name | createdon | id
------+-----------+----
(0 rows)
cassandra@ycqlsh:myapp> select * from myapp.nvbase where createdon in ('2022-01-11 15:21:38.117000+0000');
 name | createdon | id
------+-----------+----
(0 rows)

As you can see the the rows can not be retrieved using the column in the way it is displayed.
It works with totimestamp(now())

cassandra@ycqlsh:myapp> insert into myapp.nvbase(id,name,createdon) values(5, 'john', totimestamp(now()));
cassandra@ycqlsh:myapp> select * from myapp.nvbase ;
 name | createdon                       | id
------+---------------------------------+----
 john | 2022-01-11 15:23:52.307000+0000 |  5
 atul | 2022-01-11 15:21:38.117000+0000 |  3
(2 rows)

cassandra@ycqlsh:myapp> select * from myapp.nvbase where createdon in ('2022-01-11 15:23:52.307000+0000');
 name | createdon                       | id
------+---------------------------------+----
 john | 2022-01-11 15:23:52.307000+0000 |  5
(1 rows)

**Comment by pgyogesh** [comment]
@mheer9 

Looks like this issue is resolved in recent version of YB. I tested it in 2.13.

```
ycqlsh> CREATE KEYSPACE myapp;
ycqlsh> CREATE TABLE myapp.nvbase ( name text, createdon timestamp, id int, PRIMARY KEY ((name, createdon)) ) WITH default_time_to_live = 0 AND transactions = {'enabled': 'false'};
ycqlsh> 
ycqlsh> 
ycqlsh> insert into myapp.nvbase(id,name,createdon) values(3,'atul',currenttimestamp());
ycqlsh> 
ycqlsh> 
ycqlsh> select * from myapp.nvbase ;

 name | createdon                       | id
------+---------------------------------+----
 atul | 2022-04-04 05:09:36.278000+0000 |  3

(1 rows)
ycqlsh> 
ycqlsh> 
ycqlsh> select * from myapp.nvbase where createdon = '2022-04-04 05:09:36.278000+0000';

 name | createdon                       | id
------+---------------------------------+----
 atul | 2022-04-04 05:09:36.278000+0000 |  3
```
