### ISSUE TITLE
use fast-path when possible even in presence of transaction_timestamp() expression 

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#11050]
Originally reported as part of #10995.. but there are two independent issues there:

a) One is when using distributed transactions.. there seem to be some outlier latencies (high p99). @rthallamko3 has been looking into that, and it will be tracked using #10995.
 
b) Since the test case involves a single-row insert on a table has no indexes.. we should be able make this case still go through the single-row fast-path instead of having to use the distributed transaction path. For some reason the presence of the transaction_timestamp() expression is causing it to use the distributed txn code path. We should optimize this case (for simple single rows inserts without any indexes etc.) cc: @m-iancu , @mbautin

Refer to #10995 for test case.

***Let's use this issue for optimization (b).***

_Originally posted by @kmuthukk in https://github.com/yugabyte/yugabyte-db/issues/10995#issuecomment-1005938295_

**Comment by andrei-mart** [comment]
The transaction_timestamp() no longer stops fast path.
```
yugabyte=# create table tstest(k int primary key, v text, ts timestamp);
CREATE TABLE
Time: 340.169 ms
yugabyte=# explain update tstest set v = 'foo', ts = transaction_timestamp() where k = 1;
                     QUERY PLAN                      
-----------------------------------------------------
 Update on tstest  (cost=0.00..4.12 rows=1 width=76)
   ->  Result  (cost=0.00..4.12 rows=1 width=76)
(2 rows)

Time: 107.894 ms
```

**Comment by andrei-mart** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/32007863a784e3d228a4e51709357f634ad12dc2
