### ISSUE TITLE
[Docs] Page not found 2.6 quick start/install

### ISSUE THREAD

**Issue by epratt-yb** [yugabyte/yugabyte-db#11067]
The following link is broken:
https://docs.yugabyte.com/v2.6/quick-start/install/

**Comment by epratt-yb** [comment]
So if you use the box under quick start to navigate that is what is broken.  If you use the explorer to the left and click on install that takes you to the correct page:

**Comment by aishwarya24** [comment]
This will be fixed in #11059

**Comment by aishwarya24** [comment]
This issue is fixed in #11059 . Thanks for pointing it out @epratt-yb.
