### ISSUE TITLE
[SQLancer] [YSQL] Select statement may return phantom value from failed insert statement if ORDER BY used in temporary tables

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#11077]
### Description

Insert statement results  may be partially applied into a temporary table while insert transaction itself failed.
Expected behaviour is that last SELECT statement will produce 0 rows - it is passed for non temporary tables. Also test is passed in Postgres 11.

```
DROP TABLE t1;

CREATE TEMP TABLE IF NOT EXISTS t1(c0 TEXT  DEFAULT '3.61.4.60' PRIMARY KEY NOT NULL, c1 DECIMAL);
INSERT INTO t1(c1) VALUES(0.835), (0.703);

SELECT t1.c0 FROM t1 ORDER BY t1.c0;
```

ysql console output:
```
yugabyte=# CREATE TEMP TABLE IF NOT EXISTS t1(c0 TEXT  DEFAULT '3.61.4.60' PRIMARY KEY NOT NULL, c1 DECIMAL);;
CREATE TABLE
yugabyte=# INSERT INTO t1(c1) VALUES(0.835), (0.703);
ERROR:  duplicate key value violates unique constraint "t1_pkey"
DETAIL:  Key (c0)=(3.61.4.60) already exists.
yugabyte=# SELECT t1.c0 FROM t1 ORDER BY t1.c0;
    c0
-----------
 3.61.4.60
(1 row)
```

**Comment by qvad** [comment]
Additional comment - if we remove ORDER BY condition `SELECT t1.c0 FROM t1;` then result is correct.

**Comment by kmuthukk** [comment]
Given that it is a correctness issue.. marking this as priority/high.. at least the investigation portion of it. And then we can make a further call on priority once we find out the reason.

**Comment by qvad** [comment]
Same behaviour for some statements in where clause: `SELECT t1.c0 FROM t1 where c0 in ('3.61.4.60');`

**Comment by qvad** [comment]
Also updates are affected, but this might be another issue. Although they are have a lot of common logic
```
CREATE temp TABLE t4(c0 DECIMAL NULL, UNIQUE(c0));
INSERT INTO t4(c0) VALUES(0.03);
UPDATE t4 SET c0 = (0.05) WHERE t4.c0 = 0.03;
SELECT ALL t4.c0 FROM t4 ORDER BY t4.c0 ASC;
```
