### ISSUE TITLE
[DocDB] Disable fsync / fdatasync in unit tests

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#11071]
Jira Link: [DB-1305](https://yugabyte.atlassian.net/browse/DB-1305)
fsyncs are interfering with test stability by creating unpredictable latencies on test runner VMs. We need to find all places we call fsync/fdatasync and put those under a flag so we can disable them in unit tests.

**Comment by SrivastavaAnubhav** [comment]
4c1d88d fixed a lot of the tests. The CLI tests and java tests still need to be examined.
