### ISSUE TITLE
Driver failed programming external connectivity on endpoint yb-master-n1

### ISSUE THREAD

**Issue by Sambeth** [YugaByte/yugabyte-db#1108]
I get this error when I try to create a node cluster;
`Error starting userland proxy: listen tcp 0.0.0.0:7000: bind: address already in use.`

Apparently port 7000 is in use, so is there a way to change the port of the `./yb-docker-ctl create` command?

**Comment by Arnav15** [comment]
We currently don't support custom ports through commands/args in yb-docker-ctl. But you can open the yb-docker-ctl script and modify all the ports that are in use/you do not want to use by special casing the default ports on Line 314 in the script. So something like:
Current code:
 ```
 314:       for port in exposed_ports:
 315:           docker_cmd.extend(['-p', '{}:{}'.format(port, port)])
```
Modified code:
```
 314:         for port in exposed_ports:
 315:            if port == <port you want to change>:
 316:                docker_cmd.extend(['-p', '{}:{}'.format(<port you want to change to>, port)])
 317:            else:
 318:                docker_cmd.extend(['-p', '{}:{}'.format(port, port)])
```
Hopefully this is helpful. Let me know if you need anything else.

**Comment by Sambeth** [comment]
Yeah it did. Thanks very much.
