### ISSUE TITLE
[DocDB] No tablet leader and TABLET_DATA_TOMBSTONED state after restart

### ISSUE THREAD

**Issue by rijulsudhir** [yugabyte/yugabyte-db#11088]
Jira Link: [DB-1201](https://yugabyte.atlassian.net/browse/DB-1201)
### Description

yugabytedb was deployed in docker swarm with stack file and was working fine for some time. Until I stopped and started again then tables don't have leader, tablets don't have leader and there are tablets with state TABLET_DATA_TOMBSTONED. Also now when tried to access through YSQL it says 
`ERROR: Query error: GetTransactionStatus: tablet_id: "98233319a15447ebb2ee5b57cc1c5bca" transaction_id: "\337\353\261[\243\005D\265\206I\257m\345\016\226Y" propagated_hybrid_time: 6726263061803053056, retrier: { task_id: -1 state: kRunning deadline: 10299.210s } passed its deadline 10299.210s (passed: 5.008s): Network error (yb/util/net/dns_resolver.cc:63): Resolve failed aa8c3a689b8a: Host not found (authoritative)`

Stack File
```
version: "3.8"

networks:
  local-net:
    
volumes:
  yb-master1-data1:
  yb-master2-data1:
  yb-master3-data1:
  yb-tserver1-data1:
  yb-tserver2-data1:
  yb-tserver3-data1:
  

services:
  yb-master1:
    image: yugabytedb/yugabyte:latest
    hostname: yb-master1
    volumes:
      - yb-master1-data1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master1:7001,yb-master2:7002,yb-master3:7003",
                "--rpc_bind_addresses=0.0.0.0:7001",
                "--replication_factor=2"]
    ports:
      - 7001:7000
    networks:
      - local-net
    environment:
      - SERVICE_7000_NAME=yb-master1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
  yb-master2:
    image: yugabytedb/yugabyte:latest
    hostname: yb-master2
    volumes:
      - yb-master2-data1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master1:7001,yb-master2:7002,yb-master3:7003",
                "--rpc_bind_addresses=0.0.0.0:7002",
                "--replication_factor=2"]
    ports:
      - 7002:7000
    networks:
      - local-net
    environment:
      - SERVICE_7000_NAME=yb-master2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
  yb-master3:
    image: yugabytedb/yugabyte:latest
    hostname: yb-master3
    volumes:
      - yb-master3-data1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master1:7001,yb-master2:7002,yb-master3:7003",
                "--rpc_bind_addresses=0.0.0.0:7003",
                "--replication_factor=2"]
    ports:
      - 7003:7000
    networks:
      - local-net
    environment:
      - SERVICE_7000_NAME=yb-master3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
  yb-tserver1:
    image: yugabytedb/yugabyte:latest
    volumes:
      - yb-tserver1-data1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=0.0.0.0:9011",
                "--tserver_master_addrs=yb-master1:7001,yb-master2:7002,yb-master3:7003"]
    ports:
      - 5434:5433
      - 9043:9042
      - 6380:6379
      - 9011:9000
    networks:
      - local-net
    environment:
      - SERVICE_5433_NAME=ysql
      - SERVICE_9042_NAME=ycql
      - SERVICE_6379_NAME=yedis
      - SERVICE_9000_NAME=yb-tserver1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure


  yb-tserver2:
    image: yugabytedb/yugabyte:latest
    volumes:
      - yb-tserver2-data1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=0.0.0.0:9012",
                "--tserver_master_addrs=yb-master1:7001,yb-master2:7002,yb-master3:7003"]
    ports:
      - 5435:5433
      - 9044:9042
      - 6381:6379
      - 9012:9000
    networks:
      - local-net
    environment:
      - SERVICE_5433_NAME=ysql
      - SERVICE_9042_NAME=ycql
      - SERVICE_6379_NAME=yedis
      - SERVICE_9000_NAME=yb-tserver2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  yb-tserver3:
    image: yugabytedb/yugabyte:latest
    volumes:
      - yb-tserver3-data1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=0.0.0.0:9013",
                "--tserver_master_addrs=yb-master1:7001,yb-master2:7002,yb-master3:7003"]
    ports:
      - 5436:5433
      - 9045:9042
      - 6382:6379
      - 9013:9000
    networks:
      - local-net
    environment:
      - SERVICE_5433_NAME=ysql
      - SERVICE_9042_NAME=ycql
      - SERVICE_6379_NAME=yedis
      - SERVICE_9000_NAME=yb-tserver3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

```

What is done wrong here? How can it be fixed without doing a new deploy?
Please help, Thank you

**Comment by ddorian** [comment]
What version are you using? Also what are the specs of the containers (cpus & memory)?

Can you upload some logs from the servers? Both yb-masters & yb-tservers?  ([how to get logs](https://docs.yugabyte.com/latest/troubleshoot/nodes/check-logs/))

**Comment by rijulsudhir** [comment]
Sorry for the late reply.
* Container was using version 2.9.1.0
* Containers run on a host with 4vCPU and 12GB RAM. As seen in the stack file, there are no container specific restrictions enforced .
* Deployed using docker swarm

To make things easier i have made a new deploy 

Steps followed:
1) Deployed new stack using the stack file shared in the issue. (version 2.11.1.0)
2) Stopped the stack.
3) Deployed again

![Screenshot at 2022-01-16 16-05-35](https://user-images.githubusercontent.com/42400713/149660464-b9bda21a-052e-4aca-8792-6fa299c23743.png)
as you can see no leader in raft config column.

Here are the logs
[new deploy log.zip](https://github.com/yugabyte/yugabyte-db/files/7876974/new.deploy.log.zip)

Thank you

**Comment by rijulsudhir** [comment]
> What version are you using? Also what are the specs of the containers (cpus & memory)?
> 
> Can you upload some logs from the servers? Both yb-masters & yb-tservers? ([how to get logs](https://docs.yugabyte.com/latest/troubleshoot/nodes/check-logs/))

**Comment by ddorian** [comment]
> Containers run on a host with 4vCPU and 12GB RAM.

You should have a single yb-master/yb-tserver with this amount of CPU https://docs.yugabyte.com/latest/deploy/checklist/#hardware-requirements

> --replication_factor=2
Replication factor must be an odd number https://docs.yugabyte.com/latest/deploy/checklist/#replication

In your case you need RF1 because even for testing you have very little server resources.

**Comment by rijulsudhir** [comment]
I can understand that as per the docs the server resource is too little. But I have been running it for one month with no issue. Here is a fresh deploy (I have updated the replication factor to 3)
![Screenshot_20220201_141358](https://user-images.githubusercontent.com/42400713/151937538-41d9e843-f779-40e1-b7e6-7900a384e260.png)
The issue i am facing is not because of the limitation of the server resource. 

As far as i can tell, the issue is that when redeploying with stack, services are deployed with a new uuid and the service is not electing a new leader. Issue can be replicated by following the steps below.

1) Deploy new stack (you can use the stack file shared in the issue)
2) Stop the stack.
3) Deploy again(dont remove the old volume)
4) Now you can see no leader in raft config column (screenshot already attached in previous comment)

Thank you

**Comment by rijulsudhir** [comment]
Screenshot after first deploy
![Screenshot at 2022-02-01 14-33-23](https://user-images.githubusercontent.com/42400713/151941396-d63a33a2-d5fd-4c1e-9cc4-081d9a38fc29.png)

Screenshot after redeploying (with previous volume)
![Screenshot at 2022-02-01 14-37-12](https://user-images.githubusercontent.com/42400713/151941245-1d993875-33a7-4bcd-9715-15abcce2d0f5.png)

**Comment by rijulsudhir** [comment]
@ddorian  how can i fix the above issue? please help

**Comment by ddorian** [comment]
@rijulsudhir do the nodes get new ips or ids when they get restarted?

**Comment by ddorian** [comment]
Closing as no reply from user.
