### ISSUE TITLE
[YSQL] Support INSERT INTO ... ON CONFLICT clause

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1109]

**Comment by nocaway** [comment]
When ON CONFLICT is present in an INSERT, the following query plan is generated.
- SELECT data whose values are CONFLICTing with inserting values.
- If CONFLICTed data exists, the DO command will be executed.
- If CONFLICTed data does not exist, the INSERT command will be executed.

Examples:
Suppose YugaByte receives the following commands.
```
CREATE TABLE tab(i int primary key, j int);
INSERT INTO tab VALUES (1, 1) ON CONFLICT (i) DO UPDATE SET j = excluded.j;
INSERT INTO tab VALUES (1, 10) ON CONFLICT (i) DO UPDATE SET j = excluded.j;
```
The following query plan is generated.
- Execute query "SELECT ybctid, * FROM tab WHERE i = 1;"
- In the first INSERT, the above query returns NOT-FOUND, INSERT VALUES (1, 1) is executed.
- In the second INSERT, data is found. The conflict occurs, and the statement "UPDATE SET j = 10" is executed.

**Comment by nocaway** [comment]
This issue has been resolved by commit https://github.com/YugaByte/yugabyte-db/commit/11001d370f5ee07284a169e02c6a1581aa8f97ff
