### ISSUE TITLE
[Docs] Rearrange content that compares Universe to Cluster

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yugabyte-db#11091]
### Description

[Here](https://docs.yugabyte.com/latest/architecture/concepts/universe/#universe-vs-cluster) we say the following - _"In most of the docs, the term cluster and universe are used interchangeably. However, the two are not always equivalent. The difference is described in a section below."_

But the paragraph that goes right after that statement doesn't explain the difference between the Universe vs. Cluster:
_The universe can be deployed in a variety of configurations depending on business requirements, and latency considerations. Some examples:
Single availability zone (AZ/rack/failure domain)_

The difference is explained at the end of the page:
https://docs.yugabyte.com/latest/architecture/concepts/universe/#universe-vs-cluster

I would rearrange the content.

**Comment by ddorian** [comment]
This has already been fixed by linking to the correct paragraph.
