### ISSUE TITLE
[Docs] Remove duplicate entries in left navigation

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#11113]
### Description

There are a number of places in the docs where the left navigation sections repeat. As an example:
![Screen Shot 2022-01-17 at 3 56 47 PM](https://user-images.githubusercontent.com/9641328/149849114-07d24fa3-e432-4c09-bc82-4a19c4ffcad1.png)

The other areas include:
* Yugabyte Cloud
* Integrations
* Reference
* Releases
* FAQ

It would be good to remove these and hoist the items inside these sections to the level above.

**Comment by rajmaddy89** [comment]
Can you please assign it to me

**Comment by rajmaddy89** [comment]
https://github.com/yugabyte/yugabyte-db/pull/11114
