### ISSUE TITLE
[DocDB] Flushes and compactions increase the size of manifest till next tablet bootstrap.

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#11117]
Jira Link: [DB-1026](https://yugabyte.atlassian.net/browse/DB-1026)
### Description

When implementing snapshot schedules, disk usage grows over time even without database activity.
The rocksdb mainfest file continues to grow as snapshots are created and purged. 
Upon re-start of Yugabyte processes it gets compacted, which re-claims some space, but continues to grow again.

The MANIFEST file is a combination of:

  - Initial set of SST files for the RocksDB (since the last process restart)
  - A log of all SST files added and removed from the RocksDB instance since the last restart.

Default max size of the MANIFEST is UINT64MAX, so the MANIFEST file never rolls over until there is a restart of the process when the rollover logic kicks in. 

  - With the introduction of packed rows, min/max schema versions for all the tables were added to flushed frontiers of the SST file and made it into the MANIFEST file. 
  - On colocated tables and on syscatalog tablet where multiple tables are on the same tablet, this data can increase the size of the MANIFEST file significantly with each compaction/flush. 
  - At ~50 bytes per table, and 24 flushes/compactions a day and 5k tables, the MANIFEST file could grow to 6MB within a day.
 - With no rollover, the size was observed to grow to a few GB in some cases
 - On syscatalog, where each database creates ~135 pgcatalog tables, every new database creation increases the size of manifest substantially.

Given the above, the rollover of this file is essential and is needed independent of PITR snapshots.

[DB-1026]: https://yugabyte.atlassian.net/browse/DB-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ttyusupov** [comment]
https://github.com/facebook/rocksdb/wiki/MANIFEST

1) Can we "compact" RocksDB manifest file before creating a snapshot?
2) Can we "compact" RocksDB manifest file inside the snapshot without changing the original RocksDB manifest file?
3) There is a `max_manifest_file_size` RocksDB option that could be used to force RocksDB manifest file "compaction".

**Comment by rthallamko3** [comment]
Per @arybochkin 

For every storage version change is being logged into manifest file, essentially every  flush and compaction causes disk space can leak slowly if a tablet is never restarted, it could be an issues for LRUs.

There’s a db option max_manifest_file_size , which can be changed to control the file size; it’s currently set to std::numeric_limits<uint64_t>::max()
