### ISSUE TITLE
[DocDB] Creating and dropping large number of tables can lead to master running out of memory

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#11140]
Jira Link: [DB-881](https://yugabyte.atlassian.net/browse/DB-881)
### Description

While creating and deleting a number of tables eventually hit there is a point where the masters crash from running out of memory.

**Comment by bmatican** [comment]
Note, this issue should be tracking the master-side memory issues. We're investigating that right now cc @shantanugupta-yb 

There's a corresponding bug we found recently for the TS side (https://github.com/yugabyte/yugabyte-db/issues/10709), which we'll be investigating.

**Comment by bmatican** [comment]
@tsmull-11 can we validate if this is still a problem on the latest release?
