### ISSUE TITLE
[Docs] Document PostgreSQL logging options

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#11158]
### Description

Postgres support https://www.postgresql.org/docs/13/runtime-config-logging.html#GUC-LOG-LINE-PREFIX 

We added more options for log_line_prefix 

%C = cloud name
%R = region / data center name
%Z = availability zone / rack name
%U = cluster UUID
%N = node and cluster name
%H = current hostname

We should add these options to our documentation.

**Comment by sushantrmishra** [comment]
In https://github.com/yugabyte/yugabyte-db/issues/10331 , Implemented logic for suppressing non-Postgres logs from the Postgres file. This is done using an environment variable FLAGS_suppress_nonpg_logs which, when set to true, will trigger the suppression

./bin/yb-ctl start --tserver_flags="ysql_pg_conf_csv=\"suppress_nonpg_logs=true\""

**Comment by polarweasel** [comment]
In sum, we have three logs we generate: master, t-server, and Postgres (which includes our client process output). Need to describe overall how YugabyteDB does its logging, the formats of our master and t-server logs, _and_ how our log-line prefix additions work.

**Comment by m-iancu** [comment]
Just fyi, this is the list of tserver flags that we have documented https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/

**Comment by polarweasel** [comment]
Also, update the descriptions for [--enable_ysql](https://docs.yugabyte.com/latest/reference/configuration/yb-master/#enable-ysql) in master and tserver to say they should always match.

**Comment by ddhodge** [comment]
#11869 for logging and logs
