### ISSUE TITLE
[YSQL] (Concurrent and non-concurrent)Refresh of materialized view is failing inside transaction block

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#11164]
### Description

Issue faced in  build **2.11.3.0-b31**

Steps to reproduce the issue:
- Create a table and insert data into it 
- Create a materialized view with a unique index on the above table
- Begin a transaction
- Insert rows into the table
- Refresh the materialized view
- view the result of the refresh 
-  commit the  transaction
**Issue:**
1. On refreshing the materialized view from inside the transaction it , the materialized view is not only not updated, its contents show as empty.
After committing the transaction and viewing the materialized view contents, the effect is as if the transaction block was rolled-back and not committed. 

Note: This scenario has been attempted with a concurrent and non-concurrent refresh. It is not working in both the cases.
In the concurrent refresh scenario, the views contents are empty during the transaction. 

Concurrent Refresh:
![image](https://user-images.githubusercontent.com/87007277/150509530-da6e81c4-7f0c-4f23-a390-38dd891e4b0c.png)

Non-Concurrent Refresh:
![image](https://user-images.githubusercontent.com/87007277/150511054-60291c8f-5097-45a6-8f8a-ca2d7e65b4e0.png)

**Comment by fizaaluthra** [comment]
This is a consequence of DDLs running in a separate transaction - the reads on the MV after a refresh (which runs in a separate transaction) will be reading an older snapshot
