### ISSUE TITLE
[docs] restructure the releases folder

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11160]
### Description

Cloud team is requesting a way to point a tool at a particular release's release notes, without having to know if that numbered release is `latest`, `stable`, or an older version.

I am inclined towards option 1, even though it's more work. It results in a cleaner structure, and I can imagine other situations in which it could be helpful.

## Option 1: rearrange the folder

With this option, we rearrange the folder to be flatter, and use an alias or server-side redirect so that existing links don't break.

- remove the `earlier-releases` folder, so `/latest/releases/earlier-releases/v*` becomes `/latest/releases/v*`
- remove the `whats-new` folder, so `/latest/releases/whats-new/latest-release` becomes `/latest/releases/v*` (and gets an alias to `/latest/releases/latest-release`)
- same as previous, for `stable-release`
- server-side 301 redirects for `/latest/releases/whats-new/latest-release` and `/latest/releases/whats-new/stable-release`, to not break links from blog posts and whatnot

## Option 2: server-side redirects

With this option, we leave the folder structure as-is, and set up server-side redirects. Assuming 2.11 is latest and 2.8 is stable, those would look like:

- `/latest/releases/v2.11` redirects to `/latest/releases/whats-new/latest-release`
- `/latest/releases/v2.8` redirects to `/latest/releases/whats-new/stable-release`

**Comment by polarweasel** [comment]
@daniel-yb as we were discussing today...

**Comment by daniel-yb** [comment]
Is there a rough ETA on when this will get done? Not to imply I need it done ASAP (I do not), but just so that I can plan for and scope out when we can integrate with these changes on the cloud side of things.

**Comment by polarweasel** [comment]
Addressed by #11621: path to all release notes is now `/latest/releases/release-notes/vX.Y/`, and the latest and stable versions are also aliased to /latest/releases/release-notes/latest-version/ and /latest/releases/release-notes/stable-version/ respectively.
