### ISSUE TITLE
[Docs] Docs landing page needs to be restored with the categorized tiles as before.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#11171]
### Description

- Docs latest landing page needs to be like before, use the stable page for reference : https://docs.yugabyte.com/stable/
- Fix the duplicate integrations entry.

**Comment by rajmaddy89** [comment]
Can you please assign it to me

**Comment by rajmaddy89** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/11183
