### ISSUE TITLE
[Docs] The KairosDB integrations page needs detailed instructions 

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#11172]
### Description

The current page needs to be more explicit. Adding some suggestions by @ddhodge as well to the list:
- Include a prerequisites section to mention which Java version and so on. 
- The Kairos version install instructions can be replaced by a [link](https://kairosdb.github.io/docs/GettingStarted.html) to the kairos page instructions rather than having to use and update the wget command.
- The  push and query instructions should have a step by step way with results/output.
- Steps to connect to a non-local cluster ( Mentioned by @Anagha-Damodaran )

**Comment by Sfurti-yb** [comment]
@aishwarya24 Wrote a detailed doc for KairosDB. Here is the [draft](https://docs.google.com/document/d/1SWGGaFCx7pzKZkGxSpMwkGQ4hbQjpCcaKg2KpPk0_tc/edit#). cc: @polarweasel @kneeraj
