### ISSUE TITLE
[DocDB] Include hostname, IP addresses, and uuid in log header for every log

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#11173]
Jira Link: [DB-758](https://yugabyte.atlassian.net/browse/DB-758)
### Description

When analyzing log files, it's very easy to generate a map of hostnames, IP addresses, and uuids from master logs because these rotate infrequently and this information is recorded in the log during process startup.

For tserver logs, this can be much more difficult since rotated logs do not contain this startup information and the tserver logs rotate frequently.

This issue is a request to add a log line to the header of each rotated log showing the hostname, IP addresses, and uuid of the node.

For example:

```
Node information: { "hostname": "yb-dev-az1", "rpc_ip": "10.1.1.1", "webserver_ip": "10.1.1.1", "uuid": "b151b16813461abc9862d614111307ef" }
```

**Comment by Gaunish** [comment]
Hello,
Has this issue been solved?

I am interested in solving this!

**Comment by rthallamko3** [comment]
@Gaunish , Feel free to pick it up. Let us know if you have any questions.

**Comment by Gaunish** [comment]
@rthallamko3 Sure!
