### ISSUE TITLE
Ebean ORM  Integration with YugabyteDB

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yugabyte-db#11186]
Jira Link: [DB-921](https://yugabyte.atlassian.net/browse/DB-921)
This issue tracks all the work related to [Ebean ORM tool] Integration with YugabyteDB.

# Tasks
|Done|Name|Notes|GitHub Issue|
| - | - | - | - |
|✅|Test [Ebean ORM tool]s quickstart example with YugabyteDB | | |
|✅| Run [Ebean ORM tool] test suite |[Test Errors Summary](https://docs.google.com/spreadsheets/d/1m_AeTq1CyRXoEDfPfootquQEEGN2V7JwVagw0TIRilk/edit?usp=sharing)| |
|✅ | Provide YugabyteDB-specific extension/plugin/etc. | Yugabyte is added as a separate database platform by EbeanORM team.| [GH Issue](https://github.com/ebean-orm/ebean/issues/2510) |
|✅| Documentation on Yugabyte site |[Ebean docs](https://docs.yugabyte.com/preview/drivers-orms/java/ebean/)| |
| ✅ | Documentation hosted on [Ebean ORM tool] site | [Docs](https://ebean.io/docs/database/yugabyte/) | |
| ✅| Blog on Yugabyte site | [Blog ](https://blog.yugabyte.com/ebean-orm-yugabytedb/)| |

**Comment by rbygrave** [comment]
I have noted a couple of issues:

## ... is of type json but expression is of type character varying...

Ebean test suite has tests failing with errors like:
- ERROR: column "plain_bean" is of type json but expression is of type character varying   Hint: You will need to rewrite or cast the expression.
- column "cidr" is of type cidr but expression is of type character varying   Hint: You will need to rewrite or cast the expression.

It seems that Yugabyte is needing explicit casts when Postgres does not? I need to look closer at this and/or see if this is a known issue with Yugabyte 2.11.2.0-b89

## pgp_sym_encrypt
- ERROR: function pgp_sym_encrypt(character varying, character varying) does not exist   Hint: No function matches the given name and argument types. You might need to add explicit type casts.

Ebean uses the pgp encrypt and decrypt functions to provide transparent database encryption on columns. This is typically used in Health systems that want to have HIPPA / PII data in encrypted form at runtime (transparently decrypted by Ebean at runtime).  Need to find out if these functions are available in Yugabyte and if so have to enable then (register extension with database?).

**Comment by priyanshi-yb** [comment]
### On pgp_sym_encrypt/decrypt,
Yugabyte supports pgp_sym_encrypt/decrypt, know it more [here](https://docs.yugabyte.com/latest/secure/column-level-encryption/#step-2-insert-using-pgp-sym-encrypt) and it needs to be enabled.

**Comment by rbygrave** [comment]
Note that the title of this issue does not mention "Ebean ORM" and it really should?  As in, Ebean ORM can be used by Play Framework but equally it is used with others like Spring (today I'd suggest it is probably more common that Ebean is used with Spring).

Ebean ORM is an independent project from Play Framework.
