### ISSUE TITLE
[Docs] Add beta flag along with current gaps to collocated tables feature

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#11197]
### Description

Currently [this](https://docs.yugabyte.com/latest/architecture/docdb-sharding/colocated-tables/) page for collocated tables shows as a full fledged and working feature however there are 2 issues with feature that make this more a beta feature.

1. You are unable to take backups of collocated tables
2. expanding the cluster fails (there is a workaround)

Until these 2 gaps are fixed we need to add a beta flag to this page and also add a notes section that calls out these to issues.

**Comment by ddorian** [comment]
The page is already updated with a BETA flag and link to limitations for backup.
