### ISSUE TITLE
[DocDB] Use single system call in `WritableLogSegment::WriteEntryBatch`

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#11191]
### Description

Currently, we call `writable_file_->Append` twice in `WritableLogSegment::WriteEntryBatch`. 
It could be replaced with `writable_file_->AppendSlices` to minimize the amount of system calls.

**Comment by kmuthukk** [comment]
@spolitov - @fritshoogland-yugabyte already created an issue for this (#11035). Perhaps we can mark this as duplicate and assign that one to you if you are planning to take a look.

**Comment by spolitov** [comment]
Duplicate of #11035
