### ISSUE TITLE
QLTabletTest_LeaderLease test fails intermittently in TSAN runs

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1119]
Jira Link: [DB-1275](https://yugabyte.atlassian.net/browse/DB-1275)

**Comment by rthallamko3** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=QLTabletTest&fail_tag=all&name=LeaderLease&platform=linux

**Comment by rthallamko3** [comment]
WAL op id check failure.
`
04/05/2023 12:48 | alma8-master-gcc11-fastdebug/2203/ | unknown file C++ exception with description "CHECK failed: (index) < (current_size_): " thrown in the test body. | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/2203/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-client__ql-tablet-test/QLTabletTest_LeaderLease.log  unknown file C++ exception with description "CHECK failed: (index) < (current_size_): " thrown in the test body. | ybd fastdebug --cxx-test client_ql-tablet-test --gtest_filter QLTabletTest.LeaderLease --gcc11 Copy
-- | -- | -- | -- | --


<br class="Apple-interchange-newline">04/05/2023 12:48	[alma8-master-gcc11-fastdebug/2203/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/2203/)	unknown file C++ exception with description "CHECK failed: (index) < (current_size_): " thrown in the test body.	Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/2203/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-client__ql-tablet-test/QLTabletTest_LeaderLease.log

unknown file
C++ exception with description "CHECK failed: (index) < (current_size_): " thrown in the test body.	
ybd fastdebug --cxx-test client_ql-tablet-test --gtest_filter QLTabletTest.LeaderLease --gcc11
`
