### ISSUE TITLE
[YSQL][chaos] YSQL performance degradation in case of VM stop and start 

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#11208]
Jira Link: [DB-1095](https://yugabyte.atlassian.net/browse/DB-1095)
### Description

Cluster with 3 nodes
SqlForeignKeysAndJoins sample-app workload w/o modifications

Scenario
1. Start workload and wait 10 minutes, collect BEFORE performance
2. Start single VM stop and start code (using AWS API)
3. Wait for 10 minutes (4 node starts and stops)
4. Stop nemesis code
5. Wait for up to 30 minutes for cluster to recover performance BEFORE test. If we reached time limit hen test is failed.

Overall operations performance before - ~4000 op/s, after nemesis end (30 mins) - 3200 op/s
Will provide logs if needed. 

|Stage| Operations per second (All DML)|	Latency|
|------|--------|---------|
|before|3995.8333333333335|	109.25|
|nemesis|2521.4166666666665|	2490.5833333333335|
|after|3220|	141.66666666666666|

Stages plot
<img width="1544" alt="Screenshot 2022-01-25 at 18 49 49" src="https://user-images.githubusercontent.com/5963536/151010477-48c4825c-57af-4513-b486-911b035e635d.png">

**Comment by qvad** [comment]
Same for SqlInserts workload, so it doesn't depends on index.

|Stage	|Operations per second (All DML)	|Latency|
|----|---|---|
|before	|12010	|32.916666666666664|
|chaos	|7466.5	|52.666666666666664|
|after	|10052.166666666666|	31.583333333333332|

**Comment by qvad** [comment]
In case of VM restart (not stop/start, but actually VM restart) performance may be dropped up to 7%. Also a reason may be in delay differences: in case of stop/start we wait 120 seconds till start VM, obviously restart happens almost simultaneously.

**Comment by qvad** [comment]
Also kill, partition scenario may provide performance drop.

**Comment by rthallamko3** [comment]
@qvad , Can you confirm if this still repros?
