### ISSUE TITLE
[DocDB][SQLsmith] util/uuid: ERROR:  Corruption: Invalid length of binary data with TransactionId '': 0 (expected 16)

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11213]
### Description

Found a sporadic failure, can be reproduced by running the query a few times:
```
select
  ref_0.mapcfg as c0
from
  pg_catalog.pg_ts_config_map as ref_0
where true
limit 108
 for share
;
```
Fails with
```
ERROR:  Corruption: Invalid length of binary data with TransactionId '': 0 (expected 16)
```
The expected failure that happens mostly is:
```
ERROR:  Not implemented: Read request with row mark types must be part of a transaction
```
Can anyone confirm that the Corruption is a bug? Based on the word "corruption", I assume it should be looked at.

Found with SQLsmith while looking for something unrelated.

**Comment by bmatican** [comment]
@sergei could this be related to #11066 ?

**Comment by sergei** [comment]
Wrong Sergei 😉

**Comment by bmatican** [comment]
sorry about that... *shame face*

**Comment by bmatican** [comment]
Since #11066 was fixed, can you still repro this @def- ?
If not, let's close this out.

**Comment by def-** [comment]
Yes, now I consistently get:
```
ERROR:  Not implemented: Read request with row mark types must be part of a transaction: OPERATION_NOT_SUPPORTED
```
