### ISSUE TITLE
[YCQL] C++ driver client fails with Cassandra error: All connections on all I/O threads are busy and does not recover

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#11241]
Jira Link: [DB-691](https://yugabyte.atlassian.net/browse/DB-691)
### Description

 clients fail with `Cassandra error: All connections on all I/O threads are busy when snapshotting` occurs
 
 Before the "all I/O threads are busy" failure, these show up in logs:
 
 ```
19:06:47.719588 Cassandra TRACE: Request or metadata is not available - child policy
will be used
```

I think whats happening is that all of the connections go down, and then the client tries to send a request after the connection go back up but before the hosts are added back into the load balancing policy (https://github.com/yugabyte/cassandra-cpp-driver/blob/2.9.0-yb/src/session.cpp#L843). 

I see logs like

```
Pool(0x55c2b52bf5c0) connected to host 10.16.201.38
```
but no logs like

```
Adding pool for host 10.16.201.231 io_worker(0x55c2b150cf70)
```
before the all I/O threads busy error occurs. i think someone whose more familiar with the client code should take a look at this

**Comment by pmb311** [comment]
We have also seen this issue occur when there are no snapshot operations in progress.

**Comment by tedyu** [comment]
@kneeraj 
Is there update from your investigation ?
