### ISSUE TITLE
[Docs] Collect feedback from Bugyard or similar service

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yugabyte-db#11247]
### Description

The current feedback process via GitHub is optimized for us (those who create and maintain documentation pages). But it's time-consuming for our end users who build apps daily and can come across misprints, ambiguous places, broken or missing code snippets, etc.

Consider the following example. Let's say I'm a developer who is reading a documentation page and finds a misprint, misleading paragraph or broken instruction. It will take me 2+ minutes to report such an issue through GitHub:

- Click the `Ask our community` menu and pick `GitHub`
- Sign in if needed.
- Try to figure out how to report. OK, I'll click the `Issues` tab and then will find the `Docs` template.
- Next, you ask me to come up with the issue title and fill out this description.
- The most challenging part! I need to share a page URL and the location of the misprint/broken instruction on the page.

Some end users can go through this process once but will be discouraged to repeat this in the future.

Compare this to the experience of [Bugyard](https://bugyard.io) or a similar widget that lets share feedback in a 1-click way:

- Click the button that opens the widget
- Point out a location on a page where you come across a misprint, broken instruction, etc. and fill in quick description
- Provide your email and click send

See how it's used by the Ignite community. Developers report issues weekly thanks to the simplicity of the feedback channel:
https://ignite.apache.org/docs/latest/

**Comment by polarweasel** [comment]
On our radar for this year. The site theme we're using (Docsy, a Google project) has good integration with Google Analytics (what a shock, that), and includes a feedback widget that sends data straight into GA.
