### ISSUE TITLE
[New Feature][YSQL] Provide option to default date/time fields as ASC/DESC range in indexes

### ISSUE THREAD

**Issue by ssherwood** [yugabyte/yugabyte-db#11246]
Jira Link: [DB-1096](https://yugabyte.atlassian.net/browse/DB-1096)
### Description

YugabyeDB defaults the first entry in an index to [HASH](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_index/#expression).

In practice this isn't very useful for additional indexes that are created specifically on date/timestamp fields.  Typically, indexes on date columns are used to improve performance when doing certain range queries and/or with ordering by.

e.g.
```
create table t1(id bigint primary key, value text, ts timestamptz);
create index on t1(ts);

yugabyte=# \d+ t1
                                             Table "public.t1"
 Column |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 id     | bigint                   |           | not null |         | plain    |              | 
 value  | text                     |           |          |         | extended |              | 
 ts     | timestamp with time zone |           |          |         | plain    |              | 
Indexes:
    "t1_pkey" PRIMARY KEY, lsm (id HASH)
    "t1_ts_idx" lsm (ts HASH)
```

It would desirable to not have to specify ASC/DESC for this use case as data migration tools do not currently include it (which leads to a lot of by hand configuration).  As an added bonus, this could also be implemented as a server side flag with given types specified to default to range indexes as well as include the desired ordering - example: `--yb_index_column_remap=typename:order,….`

**Comment by m-iancu** [comment]
Added a more general issue for this here: https://github.com/yugabyte/yugabyte-db/issues/19937
Closing this as subsumed by that since we don't plan to do type-based defaults but allow changing the defaults in general should address this reasonably well.
