### ISSUE TITLE
[Docs] Imrove the search experience

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yugabyte-db#11245]
### Description

Let's update the settings of our search widget/service in such a way that it provides an experience similar to the following docs (type in `sql` there and see how results are loaded dynamically):

- https://docs.singlestore.com/managed-service/
- https://www.gridgain.com/docs/index.html
- https://docs.confluent.io/home/overview.html

**Comment by polarweasel** [comment]
we implemented this a while back, actually :)
