### ISSUE TITLE
[YSQL] Feature Support - PARTITIONING

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#1126]
All partitioning features are not yet supported.

PARTITION BY RANGE is under consideration. See #1059

**Comment by dotyjim-work** [comment]
I can see that the `CREATE TABLE` bit seems to be working in  `2.5.1.0`

```
ysqlsh (11.2-YB-2.5.1.0-b0)
Type "help" for help.
yugabyte=# CREATE TABLE customers (id INTEGER, status TEXT, arr NUMERIC) PARTITION BY LIST(status);
CREATE TABLE
yugabyte=# CREATE TABLE cust_active PARTITION OF customers FOR VALUES IN ('ACTIVE');
CREATE TABLE
yugabyte=# CREATE TABLE cust_archived PARTITION OF customers FOR VALUES IN ('EXPIRED');
CREATE TABLE
yugabyte=# CREATE TABLE cust_others PARTITION OF customers DEFAULT;
```

Is there another place that I should look to see what's left to do on this feature? I see that there is https://github.com/yugabyte/yugabyte-db/issues/5310 tracking a specific needed improvement.

**Comment by m-iancu** [comment]
@dotyjim-work That's correct, thanks for pointing this out. 
955a872 implements most of the row-level partitioning (PARTITION BY clause) in YSQL.
Also, follow-up fixes for it will be tracked in standalone issues (like #5310) so closing this issue.

**Comment by dotyjim-work** [comment]
Thank you!
