### ISSUE TITLE
[DocDB] Tserver panic 

### ISSUE THREAD

**Issue by Anagha-Damodaran** [yugabyte/yugabyte-db#11275]
### Description

Tserver got crashed and restarted. stack as below:

`
#0  0x00007fe1ea0e631e in load (order=boost::acquire, storage=@0x2d0: <error reading variable>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v2.6-20210916160338-07ec4592b1-centos7-linuxbrew/installed/uninstrumented/include/boost/atomic/detail/ops_gcc_atomic.hpp:106
#1  load (order=boost::acquire, this=0x2d0)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v2.6-20210916160338-07ec4592b1-centos7-linuxbrew/installed/uninstrumented/include/boost/atomic/detail/atomic_template.hpp:221
#2  yb::log::Log::GetLatestEntryOpId (this=0x0) at ../../src/yb/consensus/log.cc:1082
#3  0x00007fe1ea7719e9 in yb::tablet::TabletPeer::GetEarliestNeededLogIndex (this=0xefbd8c00,
    details=details@entry=0x7fe06c918200) at ../../src/yb/tablet/tablet_peer.cc:793
#4  0x00007fe1eb0d9c13 in yb::tserver::(anonymous namespace)::HandleLogAnchorsPage (tablet_id=..., peer=...,
    req=..., resp=0x7fe06c918740) at ../../src/yb/tserver/tserver-path-handlers.cc:240
#5  0x00007fe1eb0dbedb in operator() (resp=0x7fe06c918740, req=..., __closure=<optimized out>, this=<optimized out>)
    at ../../src/yb/tserver/tserver-path-handlers.cc:337
#6  std::_Function_handler<void(const yb::WebCallbackRegistry::WebRequest&, yb::WebCallbackRegistry::WebResponse*), yb::tserver::(anonymous namespace)::RegisterTabletPathHandler(yb::Webserver*, yb::tserver::TabletServer*, const string&, const F&) [with F = void (*)(const std::__cxx11::basic_string<char>&, const std::shared_ptr<yb::tablet::TabletPeer>&, const yb::WebCallbackRegistry::WebRequest&, yb::WebCallbackRegistry::WebResponse*); std::__cxx11::string = std::__cxx11::basic_string<char>]::<lambda(const yb::WebCallbackRegistry::WebRequest&, yb::WebCallbackRegistry::WebResponse*)> >::_M_invoke(const std::_Any_data &, const yb::WebCallbackRegistry::WebRequest &, <unknown type in /opt/yugabyte/yb-software/yugabyte-2.6.6.0-b10-centos-x86_64/lib/yb/libtserver.so, CU 0x119fc0b, DIE 0x12c5dca>) (__functor=...,
    __args#0=..., __args#1=<optimized out>)
    at /opt/yugabyte/yb-software/yugabyte-2.6.6.0-b10-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#7  0x00007fe1e6c3ca3b in operator() (__args#1=0x7fe06c918740, __args#0=..., this=<optimized out>)
    at /opt/yugabyte/yb-software/yugabyte-2.6.6.0-b10-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#8  yb::Webserver::RunPathHandler (this=this@entry=0x265e000, handler=..., connection=connection@entry=0x21fff5000,
    request_info=request_info@entry=0x21fff5000) at ../../src/yb/server/webserver.cc:443
#9  0x00007fe1e6c3d7be in yb::Webserver::BeginRequestCallback (this=0x265e000, connection=0x21fff5000,
    request_info=0x21fff5000) at ../../src/yb/server/webserver.cc:381
#10 0x00007fe1e6c53fb6 in handle_request ()
   from /opt/yugabyte/yb-software/yugabyte-2.6.6.0-b10-centos-x86_64/lib/yb/libserver_process.so

`

**Comment by tedyu** [comment]
Do you happen to have /threadz dump around the time of crash ?

Thanks

**Comment by bmatican** [comment]
Thanks for the crash report @Anagha-Damodaran 

Can you confirm if there was a DROP TABLE in progress, on the tablet you were trying to look at?

It's possible that the tablet you were accessing in the UI got deleted and there might be a race in the UI code.

**Comment by Anagha-Damodaran** [comment]
We don't see a drop table request in the master logs

**Comment by bmatican** [comment]
@Anagha-Damodaran alternatively, could this have been on a server that was having tablets moved off of it? ie: a node you were removing from the cluster

It's possible that this tablet you were trying to view was moved out, which would similarly destroy the underlying tablet object (much like my initial assumption of a dropped table).

In either case, this looks like a race between tablet deletion and the UI accessing data for this tablet.

**Comment by jmeehan16** [comment]
Based on log examination, this appears to be a race condition between a node creation and being accessed before the tablet peer could be initialized. D16671 should resolve this issue.
