### ISSUE TITLE
[Yugabyte] Does yugabyte db support streaming with push model?

### ISSUE THREAD

**Issue by ethashamuddin-mohammed-kr** [yugabyte/yugabyte-db#11287]
### Description

[Here](https://forum.yugabyte.com/t/can-yugabytedb-be-used-for-storage-streaming/1427/4?u=sham_yuga) is the background for this query

We have GoLang backend services:

1.  Storing data in yugabyte DB
2. Publishing same data to Kafka

Step 2 was necessary so that multiple consumers can stream through kafka(uses push model)

Q1) Can yugabyteDB help stream data, once a new row created in a table? to avoid maintaining kafka…

Q2) Does yugabyte db support streaming with push model? so that multiple consumers can stream with database instead of Kafka...

**Comment by ddorian** [comment]
Can you ask on https://github.com/yugabyte/yugabyte-db/issues/11287 ? 
You should be able to have multiple consumers.
But at first only pull mode is being developed.
