### ISSUE TITLE
[Docs][PostGIS] Example postgis dataset does not exist anymore

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11288]
### Description

https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis

```
$ wget -O edmonton.zip "https://data.edmonton.ca/api/geospatial/jfvj-x253?method=export&format=Shapefile" && unzip edmonton.zip
--2022-01-31 15:00:57--  https://data.edmonton.ca/api/geospatial/jfvj-x253?method=export&format=Shapefile
Resolving data.edmonton.ca (data.edmonton.ca)... 52.206.140.205, 52.206.140.199, 52.206.68.26
Connecting to data.edmonton.ca (data.edmonton.ca)|52.206.140.205|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-31 15:00:58 ERROR 404: Not Found.
```

**Comment by def-** [comment]
Maybe there is a similar one in https://data.edmonton.ca/browse that we can use instead

**Comment by polarweasel** [comment]
@ashetkar any thoughts on a suitable replacement dataset?

**Comment by ddhodge** [comment]
PG Extensions page moved to [docs.yugabyte.com/latest/explore/ysql-language-features/pg-extensions/#postgis-example](https://docs.yugabyte.com/latest/explore/ysql-language-features/pg-extensions/#postgis-example) and issue raised again in #11837 closing this one

**Comment by def-** [comment]
Shouldn't we keep the older issue?

**Comment by ddhodge** [comment]
Whatever works. I kept the new one because it referenced the new page location. Either way, one is a duplicate.
