### ISSUE TITLE
[YSQL] [Doc] CREATE INDEX syntax diagram needs update

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#11283]
Jira Link: [DB-916](https://yugabyte.atlassian.net/browse/DB-916)
### Description

 create index documentation mentioned WHERE and SPLIT clauses but with no clue of the order. 
 A user tried CREATE INDEX ... WHERE ... SPLIT... which fails but CREATE INDEX ... SPLIT ... WHERE works. 
 SPLIT is not found in the syntax diagrams:
https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_index/

**Comment by ddorian** [comment]
@FranckPachot 

Looking at the docs this has been fixed. 
Please re-open otherwise.
