### ISSUE TITLE
[xCluster][tablet-splitting] Replication is misbehaving after enabling source side tablet splitting. 

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#11299]
DB Version: 2.11.3.0-b77

**Scenario-1**
1. Create 2 universes( source and target) with below gflags

```
* Master: 
enable_tablet_split_of_xcluster_replicated_tables = true 
enable_automatic_tablet_splitting = true
 tablet_split_low_phase_size_threshold_bytes = 13421        -  for aggressive splitting
 tablet_split_low_phase_shard_count_per_node = 16 
* Tserver: 
yb_num_shards_per_tserver=1 
```

2. Create db,table at both side and setup replication
3. Load 250K rows data
4. Validate data at both side - works fine - with some acceptable lag
5. Delete some data (around 40K rows) and validate data at both side
	At source, table has 210K rows but at target side there are 230K rows and there is lag around 4 min to 20 min (then there is no replication for deleted rows - count mismatch remains same and lag remains same 225685.045 )
6. Update some rows at source side(ex: update 50% of rows) and validate at both side 	
        At source side update went well, and data replication at target side is very slow (~1 row per ~10 min) some times that is also not happening[replication is not happening at target side])

**Note**: Same worked without tablet splitting

**Scenario-2**

1. Create 2 universes( source and target) without tablet splitting gflags
2. Create db,table at both side and setup replication
3. Load 250K rows data
4. Validate data at both side - works fine 
5. Delete some data(around 150K) and validate at both side - works fine - Observed 100k rows at both side. 
6. Enable source side tablet splitting gflags(add above mentioned(at scenario-1) gflags at both side) - Observed increase in tablets count at both side and Observed 100k rows at source side and around 104K rows at target side(4K rows increased at target side after enabling tablet splitting)

**Comment by hulien22** [comment]
Major issues have been fixed in 0f6a95c. 

There are additionally two follow up issues after this:
- #12164 - fix rare issue where the children tablet's checkpoint is significantly behind and gets GC-ed by the time we actually start polling for it
- #12162 - Improvement to the refresh partitions code in metacache
