### ISSUE TITLE
[Tablet-Splitting] Cleanup/Hide deleted tablets

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#11307]
Jira Link: [DB-2882](https://yugabyte.atlassian.net/browse/DB-2882)
Actual: Currently YB-Master Admin UI shows deleted tablets details.
Expected: We should either cleanup the deleted tablets or hide them if those are required.

**Comment by lingamsandeep** [comment]
@Arjun-yb - We do show them as "Hidden" with a hidden column. Isn't that enough ?

**Comment by ttyusupov** [comment]
From @bmatican : >Wondering what the right thing to do here is. Maybe by default we don’t show DELETED & HIDDEN tablets, but have a URL param to show them, for more advanced debugging?
