### ISSUE TITLE
[YSQL] Support Range partitioning for primary key and indexes

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1133]

**Comment by ddorian** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/issues/1134 ?

**Comment by kmuthukk** [comment]
Yes-- but dynamic tablet splitting for range partitioned tables is still being implemented. So such tables will start of with 1 tablet, but don't automatically split yet. Active development on this happening.

**Comment by ddorian** [comment]
@kmuthukk I only saw 2 commits for colocation of tablets. Guess it's not done yet, true ?

Have you thought of colocation of range-sharding ? If tablet becomes too big, split it (and split all colocated tables on the same keys even though they're small. And on tablet-distribution, move them together.)

**Comment by ndeodhar** [comment]
Hi @ddorian, yes range partitioning for primary key and indexes was done as part of https://github.com/YugaByte/yugabyte-db/issues/1134.
The work to split tablets dynamically is being tracked here: https://github.com/YugaByte/yugabyte-db/issues/1459.

Regarding colocated tables, it's on our roadmap (but not actively worked on right now) and we'll most likely pick it up later this year. It's being tracked here: https://github.com/YugaByte/yugabyte-db/issues/79. Thanks for your input on colocation of range sharding! I'm going to add your comments to #79 so it's tracked in one place.
