### ISSUE TITLE
[docs] Helm install: document how to specify a static load balancer IP

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11355]
### Description

This is documentation for #10804, required in https://docs.yugabyte.com/latest/deploy/kubernetes/single-zone/oss/helm-chart/ (and if you can find other places it fits, please add there, too!)

**Add to versions 2.12, 2.11, and 2.8.**

From @jvigil-yugabyte, who can help with this:

> The use case for specifying the load balancer IP is in case you want to use a pre-allocated / reserved IP for the exposed master/tserver services. Otherwise, it will allocate an “ephemeral”, semi-random IP.
>
> In this case, the customer would like to be able to specify that the db should use their fixed, predictable, pre-allocated IPs.
>
> The behavior is somewhat cloud / k8s platform specific also. So, I think we have only really tested this out on GKE. May need to be a bit careful to call that out in the docs.

**Comment by jvigil-yugabyte** [comment]
Also, according to this stackoverflow post, the Google Cloud reserved IP must be "regional" as opposed to "global": https://stackoverflow.com/questions/46944969/set-static-external-ip-for-my-load-balancer-on-gke
