### ISSUE TITLE
Add YB Partition Aware Policy for load balancing in the YCQL Go (gocql) driver

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#11376]
Jira Link: [DB-1042](https://yugabyte.atlassian.net/browse/DB-1042)
### Description

Add YB partition aware policy to YugabyteDB's fork of gocql driver.

| Done | Task | Note | Link |
| --- | --- | --- | --- |
|✅| Implement the policy |-| [#9](https://github.com/yugabyte/gocql/pull/9)|
|✅| Provide tests |-| [Tests](https://github.com/yugabyte/gocql/blob/master/policies_test.go#L63)|
|  | Provide documentation |-| [Doc](https://docs.yugabyte.com/preview/drivers-orms/go/ycql/)|

[DB-1042]: https://yugabyte.atlassian.net/browse/DB-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ethashamuddin-mohammed-kr** [comment]
@ashetkar 
[Documentation](https://pkg.go.dev/github.com/yugabyte/gocql#hdr-Data_center_awareness_and_query_routing) says: token aware feature is available

Implementation is in master branch: https://github.com/yugabyte/gocql/blob/master/policies.go#L354

Please clarify the status of this token aware policy feature

**Comment by HarshDaryani896** [comment]
Feature added with the PR : https://github.com/yugabyte/gocql/pull/9
