### ISSUE TITLE
[DocDB] Geo-Partitioned, Multi-Region Backup deletion doesn't cleanup data in S3

### ISSUE THREAD

**Issue by sridhar-yb** [yugabyte/yugabyte-db#11379]
### Description

Configured Geo-Partitioned universe and Multi-region Backup. Took Backup of the universe and try deleting the backup.
Issue:
Backup Log:
`2022-02-07 07:53:52,903 [DEBUG] from ShellProcessHandler in TaskPool-MultiTableBackup(ba7be653-7d7a-4669-8ed2-5b960d6cf624)-0 - Starting proc (full cmd) - 'bin/py_wrapper' 'bin/yb_backup.py' '--masters' '172.158.20.134:7100,172.158.32.219:7100,172.158.60.50:7100' '--ts_web_hosts_ports' '172.151.27.41:9000,172.152.29.245:9000,172.152.42.149:9000,172.158.20.134:9000,172.158.32.219:9000,172.158.60.50:9000' '--parallelism' '8' '--ysql_enable_auth' '--ysql_port' '5433' '--keyspace' 'ysql.yugabyte' '--no_auto_name' '--sse' '--region' 'eu-central-1' '--region_location' 's3://backups.yugabyte.com/GP1' '--region' 'us-west-2' '--region_location' 's3://backups.yugabyte.com/GP2' '--ssh_port' '54422' '--ssh_key_path' '/opt/yugabyte/yugaware/data/keys/305a147b-9ce5-4e84-9934-53eee637cb18/yb-dev-test-west2-east1-central1_305a147b-9ce5-4e84-9934-53eee637cb18-key.pem' '--backup_location' 's3://backups.yugabyte.com/s3Backup//univ-ba7be653-7d7a-4669-8ed2-5b960d6cf624/backup-2022-02-07T07:53:52-205247162/keyspace-yugabyte' '--storage_type' 's3' '--certs_dir' '/home/yugabyte/yugabyte-tls-config/' 'create' - logging stdout=/tmp/shell_process_out8825527620329444088tmp, stderr=/tmp/shell_process_err3946104187309733558tmp`

Geo-Partitioned, Multi-Region Backup deletion doesn't cleanup data in region locations configured.
"REGION_LOCATIONS": [
            {
                "REGION": "eu-central-1",
                "LOCATION": "s3://backups.yugabyte.com/GP1"
            },
            {
                "REGION": "us-west-2",
                "LOCATION": "s3://backups.yugabyte.com/GP2"
            }

**Comment by OlegLoginov** [comment]
Should be backported into 2.12 as the main diff (for geo-partitioned backup) was backported to 2.12:
https://github.com/yugabyte/yugabyte-db/issues/8732
