### ISSUE TITLE
[YSQL] Investigate schema mapping between YB and postgres

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1138]
Jira Link: [DB-1164](https://yugabyte.atlassian.net/browse/DB-1164)

**Comment by robertpang** [comment]
Currently, the source of truth of a table schema is stored in postgres' sys catalog tables. For YugaByte's operation, the catalog manager in yb-master and the tablet in yb-tserver also hold a subset of the schema (such as the column names/types and the primary key). We need to investigate if it is feasible to reduce the scope of copying the schema and how to keep them in-sync.

**Comment by deeps1991** [comment]
Tracked in https://github.com/yugabyte/yugabyte-db/issues/13358
