### ISSUE TITLE
[YSQL] Backup/Restore support for UDT/Enum types

### ISSUE THREAD

**Issue by myang2021** [yugabyte/yugabyte-db#11383]
### Description

Example 1:
In the source database, run the following SQL commands:

```
create type e_t as enum('c', 'b', 'a');
CREATE TYPE
create table t(id e_t);
CREATE TABLE
insert into t values ('a'), ('b'), ('c');
INSERT 0 3
select oid, * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16386 |     16385 |             1 | c
 16388 |     16385 |             2 | b
 16390 |     16385 |             3 | a
(3 rows)

select * from t order by id;
 id
----
 c
 b
 a
(3 rows)

```
Do database restore on the target database. After restoring, run the following commands in the
target database and observe the error:

```
select oid, * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16398 |     16396 |             1 | c
 16400 |     16396 |             2 | b
 16402 |     16396 |             3 | a
(3 rows)

select * from t order by id;
ERROR:  invalid internal value for enum: 16386

```
The last command select * from t order by id; failed because when trying to use OID 16386 as the primary key to lookup pg_enum table, it is not found. We can see that when the enum type e_t is recreated on the target cluster, its labels and itself are assigned new OIDs that are different from the old OIDs on the source cluster. The reason for 16386 showing up in the error is because YSQL backup/restore copies the underlying SST files in order to have better performance and 16386 comes from the copied SST files.

Example 2:
In the source database, run the following SQL commands:
```
create type udt1 as (f1 int, f2 text);
CREATE TYPE
create table t2(id udt1);
CREATE TABLE
insert into t2 values((1, '1')), ((1, '2')), ((1, '2'));
INSERT 0 3
select * from t2 order by id;
  id
-------
 (1,1)
 (1,2)
 (1,2)
(3 rows)

```
After restoring, run the following command on the target database:
```
select * from t2 order by id;
ERROR:  type with OID 16386 does not exist

```
In this example, there is no enum type used. However, the type udt1 has an old OID 16386, it is stored in the record values and in the restored database the type udt1 has a new OID 16396:

```
yb2=# select oid from pg_type where typname = 'udt1';
select oid from pg_type where typname = 'udt1';
  oid
-------
 16396
(1 row)

```
Example 3:
In the source database, run the following SQL commands:
```
CREATE DOMAIN postal_code AS TEXT
             CHECK(VALUE ~ '^\d{5}$'OR VALUE ~ '^\d{5}-\d{4}$');
CREATE DOMAIN
CREATE TABLE foo(postal postal_code[]);
CREATE TABLE
INSERT INTO foo values (array['32768', '65536']::postal_code[]);
INSERT 0 1
select * from foo;
    postal
---------------
 {32768,65536}
(1 row)
```

After restoring, we see
```
select * from foo;
ERROR:  cache lookup failed for type 16385

```
In this example, the array element type is a domain type postal_code and its OID is stored as part
of the array value.

**Comment by def-** [comment]
@myang2021 This is still broken in 2.6 itest, I see that it was only backported to 2.8:
```
testysqldatatypes-k8s-rf3: Start
	(     0.109s) User Login : Success
	(     0.030s) Refresh YB Version : Success
	(     0.070s) Setup Provider : Success
	(     0.014s) Updating Health Check Interval to 60000 sec : Success
	(   120.317s) Create universe dfel-isd1957-f449a4fcbe-20221005-224117 : Success
	(     0.710s) Updating Health Check Interval to 60000 sec : Success
	(   150.331s) Create universe dfel-isd1957-f449a4fcbe-20221005-224117-2 : Success
	(    88.682s) Creating table and Loading data : Success
	(    90.585s) Create Backups : Success
	(   151.156s) Restore Backup: None : Success
	(     0.568s) Restore Backup: None : >>> Integration Test Failed <<< 
Failed running ysqlsh command with error 'b'ERROR:  type with OID 16386 does not exist\n''
	(     7.261s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.6.20.0_testysqldatatypes-k8s-rf3_20221006_010154 : Success
	(    90.138s) Destroy universe : Success
	(     7.831s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.6.20.0_testysqldatatypes-k8s-rf3_20221006_010331 : Success
	(    90.152s) Destroy universe : Success
testysqldatatypes-k8s-rf3: End
```
Do we plan to also backport this fix to 2.6?

**Comment by myang2021** [comment]
@def- , we do not plan to backport this fix to 2.6, which I think should now be obsolete. In my opinion, unless we have some external customer request we'll just move on.

**Comment by def-** [comment]
We are still releasing 2.6 releases, which is why I was wondering.

**Comment by myang2021** [comment]
I see, @tverona1 @m-iancu , what do you think? What are the rules for us to make a backport to the old releases like 2.6? In addition to UDT/Enum, there are other bugs in the backup/restore area that @yifanguan has fixed. Those were only backported to newer releases as well not 2.6.
