### ISSUE TITLE
[YSQL] ysql_dump makes wrong statement for the index over HASH NULL FIRST key

### ISSUE THREAD

**Issue by skorobogatydmitry** [yugabyte/yugabyte-db#11382]
### Description

Backup taken from the Platform 2.6.6.0-b10 produces the following statement for the index:
```
CREATE INDEX some_index ON myschema.some_table USING lsm (r1 NULLS FIRST HASH, r2 ASC NULLS FIRST, r3 ASC) SPLIT INTO 4 TABLETS WHERE ((r4 = false) AND (r5 = false) AND (r6 = false));
```
Attempt to restore backup (Platform 2.11) with this statement fails due to non-existent index. Actual reason is that psql can't execute the above statement. Error message:
```
ERROR:  syntax error at or near "HASH"
LINE 1: ...myschema.some_table USING lsm (r1 NULLS FIRST HASH, r2...
```

If switch HASH and NULL FIRST  in the statement, restore works.

**Comment by yifanguan** [comment]
Issue solved by commit -> 025ea87
