### ISSUE TITLE
[docs] use CSS to style external links?

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11391]
### Description

Rather than using `render-link.html` to add a `_blank` target and do other styling on external links, could we move that logic into the site's CSS, instead? ([This post](https://davidwalsh.name/external-links-css) suggests an approach that might work.)

The rationale for this is that external links in admonitions (notes, etc.) do not get processed by that render hook. This is a known limitation of the `markdownify` function, and Hugo's recommended replacement, `RenderString`, doesn't work in shortcodes (also a known limitation, and not one that appears likely to be fixed anytime soon).

**Comment by polarweasel** [comment]
Related, that addresses the immediate problem: #11399

**Comment by lizayugabyte** [comment]
@polarweasel Was this taken care of by the doc site redesign?

**Comment by polarweasel** [comment]
Yup!
