### ISSUE TITLE
[DocDB] Better auto-tuning for tserver_tcmalloc_max_total_thread_cache_bytes : reduce minimum 

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#11398]
### Description

#7844 allows [t]server_tcmalloc_max_total_thread_cache_bytes to be set based on the memory available to the process. However, the minimum it uses is 256_MB, this is too huge for master process running on a 4GB machine where the whole process only gets about 400MB.

Dropping the minimum to something more reasonable. Say 32MB

**Comment by kmuthukk** [comment]
@amitanandaiyer - Did you mean tserver_tcmalloc_max_total_thread_cache_bytes or mem_tracker_tcmalloc_gc_release_bytes in the issue description?

**Comment by amitanandaiyer** [comment]
Thanks kannan. It's tserver_tcmalloc_max_total_thread_cache_bytes/server_tcmalloc_max_total_thread_cache_bytes
