### ISSUE TITLE
[Docs] [Platform] document universe filtering

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11394]
### Description

On the /universes page, the filter bar is not super-intuitive to use, and should be documented. For example, how do I filter my list of universes to show all universes _except_ those with a status of "Error"?

This feature is present in 2.11.x and 2.12.x.

**Comment by lizayugabyte** [comment]
Closing based on the following:
Sridhar Reddy
We intentionally skipped documenting universe listing feature. In general, we only document the Task oriented UIs and not dashboard style ones as they're supposed to be self documenting. We should include such improvements in release notes though.
