### ISSUE TITLE
Allow a DoNotRetry flag at the proxy layer

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#114]
For non-idempotent operations, it may be useful to expose a do-not-retry flag, so that we avoid the situation where we are not sure if the operation gets applied exactly-once or could possibly have been applied multiple times.

**Comment by kmuthukk** [comment]
@rkarthik007 , @ttyusupov :

I believe this is a duplicate of the already fixed issue - https://github.com/YugaByte/yugabyte-db/issues/537

Please confirm.

**Comment by rkarthik007** [comment]
Yup, this is fixed. Will close.
