### ISSUE TITLE
[docs] Deploy to two universes with asynchronous replication

### ISSUE THREAD

**Issue by pgyogesh** [yugabyte/yugabyte-db#11416]
https://docs.yugabyte.com/latest/deploy/multi-dc/async-replication/

## Issue description
`yb-admin` command requires master addresses.
## Suggested resolution

current command:

`yb-admin list_tables include_table_id`

Should be like below

`yb-admin -master_addresses=<master addresses> list_tables include_table_id`

**Comment by ddorian** [comment]
@pgyogesh can you make a pull request for the docs?

**Comment by pgyogesh** [comment]
@ddorian created PR #11444
