### ISSUE TITLE
[YSQL] Protobuf cleanup

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1141]
Jira Link: [DB-1025](https://yugabyte.atlassian.net/browse/DB-1025)

**Comment by nocaway** [comment]
Please consider splitting WriteOperator into INSERT, UPDATE, & DELETE operators as part of this work before 2.0 release to avoid future compatibility issues.

**Comment by sushantrmishra** [comment]
Closing this issue as this is quite old and likely not relevant anymore.
