### ISSUE TITLE
[Docs][Cloud] Update Security Architecture section 

### ISSUE THREAD

**Issue by proff4eg** [yugabyte/yugabyte-db#11427]
### Description

https://docs.yugabyte.com/latest/yugabyte-cloud/cloud-security/cloud-security-features/ 

New text below the image

All customer clusters are firewalled from each other. Outside connection are also firewalled according to the customer's IP allow list. For Yugabyte customers that take advantage of a free subscription, clusters are deployed in a shared VPC. Paid customers can additionally connect a VPC within their chosen public cloud provider

**Comment by proff4eg** [comment]
cc @kevincox @Arnav15

**Comment by kevincox** [comment]
LGTM.
