### ISSUE TITLE
[docs] Prepare the Google Cloud Platform (GCP) environment

### ISSUE THREAD

**Issue by don-bizzell** [yugabyte/yugabyte-db#11438]
https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/

## Issue description
I tried to follow this, and the actual google screen are different enough now that that this does not work.

## Suggested resolution
Re-do with new screen shots and directions for Google

Thanks, -- Don Bizzell. dbizzell@yugabyte.com

**Comment by polarweasel** [comment]
Thanks, @don-bizzell!
