### ISSUE TITLE
[docs] CREATE DATABASE statement [YSQL]

### ISSUE THREAD

**Issue by ajaysinha26** [yugabyte/yugabyte-db#11445]
https://docs.yugabyte.com/stable/api/ysql/the-sql-language/statements/ddl_create_database/

## Issue description
Incorrect CONNECTION_LIMIT syntax:  [ CONNECTION LIMIT [ = ] connlimit ] 
## Suggested resolution
Please put an underscore between CONNECTION and LIMIT

**Comment by polarweasel** [comment]
Good catch. Thank you! We'll get this corrected shortly.
