### ISSUE TITLE
[YCQL] TSAN race condition in yb::ql::ParseTree::clear_reparsed() in org.yb.cql.TestIndex#testDropDuringWrite.InsertUpdate

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1146]
https://gist.githubusercontent.com/mbautin/f9ee21cd23c6b06712241af0f5333c91/raw

**Comment by robertpang** [comment]
Resolved in commit [4d0f749](https://github.com/YugaByte/yugabyte-db/commit/4d0f7497ca7ad429b837957724b0e6b8a1a6fb1d).
