### ISSUE TITLE
[docs] Docs enhancement proposal - Command blocks with editable variable names. 

### ISSUE THREAD

**Issue by yogendra** [yugabyte/yugabyte-db#11475]
https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes/

## Issue description
Command blocks with editable variable names. Most of the time we have to copy the commands, paste in a text file and change it. In some cases, a value/text (Example: `<namespace>`) has to be typed more than once in a command, and also in multiple commands for same activity (Example: create sa and role bindings). Some of these commands do not show any errors right away, but cause a later step to fail. This can be eliminated with UX. 

## Suggested improvement

1. Please look at https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-zonal-cluster#gcloud for a very good example.

2. You could also consider using variables instead of placeholders.

**Comment by streddy-yb** [comment]
cc @baba230896 @bhavin192
