### ISSUE TITLE
[YSQL] Tablespace tests failing due to variations in error message

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#11496]
### Description

TablespaceProperties.testTablespaces and TestPgRegressTablespaces.testPgRegressTablespaces are both flaky due to expecting an error message of the form: `ERROR:  Invalid argument: Not enough tablet servers in nonexistent:nowhere:area51. Need at least 1 but only have 0.` but sometimes we return `ERROR:  Invalid argument: Not enough tablet servers in the requested placements. Need at least 1, have 0` instead.

**Comment by bmatican** [comment]
cc @deeps1991
cc @sanketkedia since you were recently working on the placement checks

**Comment by sanketkedia** [comment]
Fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/3a0d04bcf4ed9d2a697700f7333e53396b4407f0)
