### ISSUE TITLE
[dst] Transparently retry ChangeMetadataRequest to split subtablets during alter schema operation

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#11508]
During an AlterSchea operation, we modify a bunch of sys catalog metadata for the involved table and then send a ChangeMetadataRequest to every tablet in the table. It’s possible that a ChangeMetadataRequest RPC gets sent to a tablet at the same time a SplitTablet RPC is sent to it. If the tablet commits the split op first, then the catalog manager will receive an error response. This leaves the table in a state where only some of the tablets have altered metadata, and returns error to postgres. Instead we ought to be able to retry the ChangeMetadataRequest at the new child subtablets in this case and handle the situation transparently to the user.

Proposed solution:

1. If a tablet has already added a split op, respond to ChangeMetadataRequest RPC from tserver with a special failure type to ChangeMetadataOperation RPC, and IDs of the new children
2. Upon receiving this failure type, the catalog manager code can lookup the new children, confirm they are registered in the sys catalog with the same parent id, and replace the failed RPC task to the parent tablet with two new ones to the child task
3. IsAlterDone calls should return true only once the new children tablet tasks are also complete, and can ignore the status of the parent task

**Comment by robertsami** [comment]
Note that the following issues are probably symptoms of this issue:
https://github.com/yugabyte/yugabyte-db/issues/10351
https://github.com/yugabyte/yugabyte-db/issues/10947

We should verify that these issues don't reproduce once we fix this one

**Comment by SrivastavaAnubhav** [comment]
I don't think there is an issue. We can't seem to reproduce this error (even on older builds). Postgres will only get an error response if the table does not move out of the altering state, but it should. Once the split children are running, they will heartbeat their schema version to the master. If the schema version is out of date, the catalog manager will send a request to the new children to update their schema. Once they heartbeat the new schema, the table should move out of the altering state.
