### ISSUE TITLE
[Docs] Release notes: Equinix KMS support is deprecated in 2.12.1.0

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#11502]
### Description

Sridhar Reddy in https://yugabyte.atlassian.net/browse/PLAT-3003
February 7, 2022, 9:46 PM

As part of 2.12.1.0 release, we need to highlight that Equinix KMS support is deprecated in 2.12.1.0 release

**Comment by ddorian** [comment]
This has already been fixed, the note is in https://docs.yugabyte.com/preview/releases/release-notes/v2.12/
