### ISSUE TITLE
[YSQL] Endpoint does not match errors for internal calls

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#11503]
Jira Link: [DB-1023](https://yugabyte.atlassian.net/browse/DB-1023)
### Description

Customer is receiving the following errors in a k8 environment deployed on open shift with` use_node_to_node_encryption`, `use_client_to_server_encryption` set to true with TLS on, and `use_node_hostname_for_local_tserver` set to false where tablet sever and master configured to use DNS names in RPC bind and server broadcast. 

```
 ERROR: Network error: Handshake failed: Network error (yb/rpc/secure_stream.cc:875): Endpoint does not match, address: <removed ip>, hostname: <removed ip>

```

If this is the case where connections to local `tserver` using IP's on the cluster with TLS on, can `use_node_hostname_for_local_tserver` set to true by default be the solution?

Ref Ticket - https://yugabyte.zendesk.com/agent/tickets/2711

**Comment by rthallamko3** [comment]
Based on the support notes, this seems to be resolved by https://github.com/yugabyte/yugabyte-db/issues/9763
