### ISSUE TITLE
[Docs] Perfect Yugabyte Cloud Quick Start Section

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yugabyte-db#11512]
With the addition of the [Build an application](https://docs.yugabyte.com/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/) section, the Quick Start guide now looks complete. The next step is to review the quick start flow and perfect it from the developer experience standpoint. 

### Create a free cluster page
https://docs.yugabyte.com/latest/yugabyte-cloud/cloud-quickstart/qs-add/

The page is complete, but it lacks graphics. All the instructions are listed in plain text and force a developer to read every sentence line-by-line. 

How about adding an animated GIF that shows the whole process within 10 seconds and keeping the current text instructions (probably making them even shorter)? This is [a sample GIF](https://user-images.githubusercontent.com/1537233/154519540-d4c9e593-adce-47c2-8c28-18a1d0bfe9ef.gif). I can create a new one if necessary, or you can do it by yourself with [this free tool.](https://www.cockos.com/licecap/)

### Connect to the cluster page
https://docs.yugabyte.com/latest/yugabyte-cloud/cloud-quickstart/qs-connect/

1) Use Cloud Shell as the name instead of cloud shell. We use the Cloud Shell (product name) version on the cloud.yugabyte.com end.

2) The page talks a lot about `ysqlsh` and `ycqlsh` as shells. It's confusing, especially for new users - in the beginning, we talk about Cloud Shell but then have sentences introducing other shells.
-  `To use ysqlsh to create and manage YugabyteDB databases` change to ~ `To use Cloud Shell for SQL requests...`
-   `The ysqlsh shell prompt appears` change to ~ `The Cloud Shell starts the ysqlsh CLI for SQL queries`

3) Add an animated picture that shows how to launch the Cloud Shell. Again, I can record it, or you can practice doing that yourself with [this or a similar tool](https://www.cockos.com/licecap/).

### Create a database page
https://docs.yugabyte.com/latest/yugabyte-cloud/cloud-quickstart/qs-data/

With the addition of the `Build an application` section, the `Create a database` page should not be placed as a top-level one. Its current placement suggests that the database we create on that page will be reused in the `Build an application` section, which is false.

Let's do the following:

- Move the content of the `Create a database` page as a new section into the `Explore Distributed SQL` page. See how [these guys did that](https://www.cockroachlabs.com/docs/cockroachcloud/learn-cockroachdb-sql.html).
- Do we need to create 4 tables and insert dozens of records in each table? For instance, the `Reviews` table is never queried, but we request to add it to the database. How about removing the `Reviews` table and INSERTINg less `Users` and `Products` (just too many INSERTS that waste the space).

### Build an application section

The section is complete and looks great. And now we can elevate the developer experience.

We request the developer to update the Allow IP list as a prerequisite. We do this for the first time throughout the quick start flow forcing the developer to leave our Java/Go/etc.  app page and navigate to the Allow IP list page. Either a page needs to be added to the quick start hierarchy (after `Explore distributed SQL`), or we can add an animated picture near the line `Your computer added to the cluster IP allow list. Refer to Assign IP Allow Lists.` I like the latter because it's highly unlikely that the developer needs to open the `Assign IP Allow Lists` page at all with the picture. Here is a [sample animated picture for reference](https://user-images.githubusercontent.com/1537233/154529852-6ea41bd0-b495-4755-a7cb-7ded930af929.gif).

### Develop section

It's not really related to the Quick Start Guide, but the section's title is misleading. The section needs to be renamed the `Example Applications` and placed down the hierarchy (before `Troubleshooting`). It features some sample apps for Java developers (disregarding the other languages). It's not the best experience if a C#, Rust, Node, etc. developer finishes the Quick Start, then goes to Develop and sees some example apps in Java. If I were a JavaScript/etc. developer I would be pissed of and didn't get it.

**Comment by ddhodge** [comment]
This work has now been largely implemented
