### ISSUE TITLE
[TLS] Support for hot swapping of node certificates

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#11531]
Currently the following use cases require a rolling restart which is not ideal from operational perspective as rotating certs more frequently (ex: every 3-months) is becoming a standard practice.
- Rotating node certs: Node certs are about to expire and user needs to rotate the node certs. Root cert itself is valid.
- Rotating root & node certs: If root cert is expiring, then ability to rotate both hot swap root cert and node cert is required
- Rotating certs for cdc (i.e, certs placed for certs_for_cdc_dir): Source universe cert changes required updating these certs.

The ask is to support hot swapping certificates for the above scenarios without requiring a rolling restart. Expose a mechanism to trigger the hot swap via appropriate interfaces (yb-admin, RPC, etc).

There is a separate request to support multiple CA cert specifications for master/tserver (https://github.com/yugabyte/yugabyte-db/issues/5730) which is not related to this but that would also help managing multiple certs when integrating with 3rd party systems like ldap.

**Comment by spolitov** [comment]
We have the following related files: ent/src/yb/server/secure.cc/h and yb/rpc/secure_stream.cc/h
The easier way to rotate certificate and private key would be adding interface to SecureContext to update them.

**Comment by rthallamko3** [comment]
@es1024 , Can you get some context on this.

**Comment by es1024** [comment]
Added with 73a3ca4 and 1da19dc.
