### ISSUE TITLE
Cassandra bulk import - version 2 or 3 ? Fix broken link

### ISSUE THREAD

**Issue by sumitdatabase** [yugabyte/yugabyte-db#11546]
### Description

Looking at the  page for [bulk import](https://github.com/yugabyte/yugabyte-db/blob/master/docs/content/latest/manage/data-migration/ycql/bulk-import.md) for cassandra-loader ( Manage --> Migrate data --> Bulk import ), 

Under large datasets, it leads to a link to cassandra-loader github [repo](https://github.com/yugabyte/cassandra-loader/)
In that repo, it points to a pre-built java binary cassandra-loader [v.0.0.27-yb-3](https://github.com/YugaByte/cassandra-loader/releases/download/v0.0.27-yb-3/cassandra-loader)

This yb-3 does not exist - get an 404 error. 

On the same page for  [bulk import](https://github.com/yugabyte/yugabyte-db/blob/master/docs/content/latest/manage/data-migration/ycql/bulk-import.md) it points to the same cassandra-loader v2 - that adds to the confusion

**Comment by sumitdatabase** [comment]
@polarweasel - fyi.

**Comment by polarweasel** [comment]
@kneeraj is the bulk loader something your team maintains? (Also, looks like @hbhanawat was the last to touch the repo...)

**Comment by lizayugabyte** [comment]
@kneeraj @hbhanawat Could you take a look at this ticket, please?

**Comment by ddorian** [comment]
This has already been fixed in https://docs.yugabyte.com/stable/manage/data-migration/bulk-import-ycql/
