### ISSUE TITLE
[Core-YSQL] Performance on graviton instances is slower possible due to "__pread call from yb::PosixRandomAccessFile::Read"

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#11547]
Jira Link: [DB-1161](https://yugabyte.atlassian.net/browse/DB-1161)
### Description

Sysbench read workload was run on graviton c6g instances, and the performance was not good.
From analysis of the flame graphs of teh runs, it seems __pread call from yb::PosixRandomAccessFile::Read taking lot of time on c6g when compared against c5 flame graph. 
This is also reflected in our disk usage pattern. The disk utilization on c6g instances is a higher.

**Comment by bmatican** [comment]
This was triaged to disk block size options
