### ISSUE TITLE
[YSQL] Feature Support - EXTENSION

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#1154]
Extension is not yet supported.

**Comment by Negashev** [comment]
+

**Comment by dodilp** [comment]
This is needed for the AdventureWorks dataset

-- Support to auto-generate UUIDs (aka GUIDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

**Comment by m-iancu** [comment]
General issue fixed in 9f4c158. Specific extensions will be tracked in separate issues.
Currently opened #1867 to track `uuid-ossp` support. Note that `pgcrypto` is already supported and it has support for generating UUIDs (e.g. `gen_random_uuid()`). cc @dodilp

**Comment by shaunstoltz** [comment]
This is resolved by pr https://github.com/yugabyte/yugabyte-db/pull/9576
