### ISSUE TITLE
[YSQL] Make successive initdb runs no-op if initdb has already run

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1157]
Figure out if initdb has already run on the cluster and make any successive run a no-op.
For more context: https://github.com/YugaByte/yugabyte-db/issues/994

**Comment by m-iancu** [comment]
This is effectively addressed in https://github.com/yugabyte/yugabyte-db/commit/bdec7bdc2b48301c6b097cf7f54e5bb425bdc2e3. See also issue https://github.com/yugabyte/yugabyte-db/issues/1411.
