### ISSUE TITLE
[YSQL] Remove initdb run from yb-ctl, yb-docker-ctl

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1158]
Depends on https://github.com/YugaByte/yugabyte-db/issues/994
Once initdb is run as part of master raft group initialization, we should remove running it separately from yb-ctl, yb-docker-ctl
Also update docs for helm, KB to reflect this.

**Comment by bmatican** [comment]
@Arnav15 have we fully removed initdb from the k8s components? I know we did helm, but did we also do it for the stateful set files?

We changed yb-docker-ctl here: 9fbabf6d08bd6e64b98d64156b745abf7842d8ad

I think yb-ctl still needs to change though. @ndeodhar now that initdb is fine to run again over a cluster, do we need to worry about any backwards compatibility things for `yb-ctl` or is it good to port over to the new snapshot mechanic too?

**Comment by ndeodhar** [comment]
`yb-ctl` has been updated to move away from initdb in new create scenario as well. The only place where it still uses initdb is when we have an existing cluster with sql disabled and then we try to start that cluster with sql enabled. In that situation, we can't use snapshot loader and use initdb.

We just need to confirm whether we do it for stateful sets or not.

**Comment by ndeodhar** [comment]
Closing as this is done.
