### ISSUE TITLE
[docs] yb-admin - Links to bootstrap_cdc_producer are broken

### ISSUE THREAD

**Issue by aravind-nallan-yb** [yugabyte/yugabyte-db#11581]
https://docs.yugabyte.com/latest/admin/yb-admin/

## Issue description
There are several links to the bootstrap_cdc_producer command which point to https://docs.yugabyte.com/latest/admin/yb-admin/#bootstrap-cdc-producer but the section itself has the link https://docs.yugabyte.com/latest/admin/yb-admin/#bootstrap-cdc-producer-comma-separated-list-of-table-ids
## Suggested resolution

**Comment by ddorian** [comment]
Already been fixed.
