### ISSUE TITLE
[Docs] mark EOL releases as such

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11588]
### Description

Two requirements here:

1. Create a shortcode to output text saying that the release is EOL.
2. Add that shortcode to the release notes for every EOL release series.

**Comment by ddorian** [comment]
This has already been done in https://github.com/yugabyte/yugabyte-db/blob/ca6bc635c4644164e0b5ab68cf4539d8a8ada659/docs/layouts/shortcodes/yb-eol-dates.html
