### ISSUE TITLE
Pgsql/Follower Reads: Redirect follower reads to the leader if the follower is not caught up

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#11593]
Jira Link: [DB-1002](https://yugabyte.atlassian.net/browse/DB-1002)
### Description

If the follower receiving a follower read isn't caught up to serve the requested read, we currently wait for the follower to catch up and for the read time to become safe. This can take a large amount of time if the follower is partitioned. 

We could allow such lagging-followers to reject the read instead -- this ensures that the request will be retried and redirected to the leader, who may be able to serve the read in a more timely manner.

**Comment by jameshartig** [comment]
@amitanandaiyer should this be backported? If not, the docs for the versions where queries hang until the replica is caught up should be clarified as we would avoid using follower reads on those versions

**Comment by amitanandaiyer** [comment]
@jameshartig We should be able to backport this. What version are you guys using?

**Comment by jameshartig** [comment]
@amitanandaiyer we recent just finished upgrading to 2.12

**Comment by amitanandaiyer** [comment]
@jameshartig In the meanwhile, you can consider setting `max_stale_read_bound_time_ms` (which defaults to 60s) to get the same behavior. 

Setting this flag will enforce this functionality for the specified staleness at the cluster/global level. 

Once backported, you can get different sessions to have different staleness values.

**Comment by jameshartig** [comment]
@amitanandaiyer it doesn't seem like it make it into v2.12.8.0, maybe the one after that?
