### ISSUE TITLE
[Docs] Ordering of entries in the "Indexes and Constraints" section in explore

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#11606]
### Description

Wanted to fix the ordering to be more “most important & common” to “most advanced” order. 

Could we change the order to the following:
* Primary Keys
* Foreign Keys
* Overview --> Secondary Indexes (needs rename)
* Unique Indexes (this needs to have the UNIQUE CONSTRAINT content also, there is no difference between the two in YB)
* Partial Indexes
* Expression Indexes
* Generalized Inverted Indexes --> GIN Indexes
* Other Constraints --> CHECK, NOT NULL Constraints

cc @ymahajan - fyi

**Comment by ymahajan** [comment]
We can slice to following sections as well. 

- Multi-column indexes
- Covering indexes 
- Prefix indexes
