### ISSUE TITLE
[YCQL] Integreate CassandraUnit  with Yugabyte

### ISSUE THREAD

**Issue by Anagha-Damodaran** [yugabyte/yugabyte-db#11610]
Jira Link: [DB-994](https://yugabyte.atlassian.net/browse/DB-994)
### Description

Can we please officially Integrate CassandraUnit for Yugabyte

https://github.com/aravind-nallan-yb/cassandra-unit

If there is an OSS process that will allow publishing libraries to Maven Central (e.g. yugabyte-unit, then that will be helpful

**Comment by sushantrmishra** [comment]
Released version release the version [4.3.1.0-yb-1](https://mvnrepository.com/artifact/com.yugabyte/cassandra-unit/4.3.1.0-yb-1)
