### ISSUE TITLE
Add one more item in YugaWare API request header

### ISSUE THREAD

**Issue by Doug44444444** [YugaByte/yugabyte-db#1163]
Add 'X-AUTH-YW-API-TOKEN' in YugaWare internal API request header to avoid that 'X-AUTH-TOKEN' is overwritten by 3rd party authentication server, the value would be as same as 'X-AUTH-TOKEN'.

**Comment by WesleyW** [comment]
In the works right now. New API will be a PUT request to `/api_token`, which will set a non-expiring auth token.

**Comment by WesleyW** [comment]
The new token can be generated by calling `PUT /customers/:cUUID/api_token`. Validation will check the `api_token` cookie or `X-AUTH-YW-API-TOKEN` header for the token.

**Comment by ramkumarvs** [comment]
So the intended flow is this api is as follows.
Brand new YugaWare installation
- bring up new k8s based yugaware
- register your customer (get the customer uuid, auth token)
- call the api_token api with the customer uuid and auth token
- persist the api_token internally and subsequent calls just use the api_token in the headers (X-AUTH-YW-API-TOKEN), it wouldn't change at all.

Existing yugaware, when you want to reset the API token.
- call the api_token api with the customer uuid and current API token in the headers, this would generate a new api_token
- persit the new api_token internally and  subsequent calls just use the api_token in the headers (X-AUTH-YW-API-TOKEN), it wouldn't change at all.
