### ISSUE TITLE
[Phase 2][YSQL][Colocation] yb-admin create_database_snapshot can't deal with tablegroups

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#11632]
Jira Link: [DB-374](https://yugabyte.atlassian.net/browse/DB-374)
### Description

On latest master (1f88fc7929118228fb0e0213ec929c3c67eb441a):
```pgsql
CREATE DATABASE yb1;
\c yb1

CREATE TABLEGROUP tg1;
CREATE TABLEGROUP tg2;

CREATE TABLE test_tbl (
  h INT PRIMARY KEY,
  a INT,
  b FLOAT CONSTRAINT test_tbl_uniq UNIQUE
) TABLEGROUP tg1;

CREATE INDEX test_tbl_tg2_idx  ON test_tbl (a ASC) TABLEGROUP tg2;
CREATE INDEX test_tbl_notg_idx ON test_tbl (a ASC) NO TABLEGROUP;

INSERT INTO test_tbl (h, a, b) VALUES (1, 101, 3.14);
```
Now try to take a snapshot:
```
19:15 ~/code/yugabyte [master] $ ./build/latest/bin/yb-admin create_database_snapshot ysql.yb1
Error running create_database_snapshot: Not found (yb/master/catalog_manager.cc:4435): Unable to create snapshot of database: yb1: Table with identifier 00004000000030008000000000000000.colocated.parent.uuid not found: OBJECT_NOT_FOUND (master error 3)
```

[DB-374]: https://yugabyte.atlassian.net/browse/DB-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by def-** [comment]
Also seeing this with LST trying to test backup/restore.

**Comment by yifanguan** [comment]
Backup/restore of a database containing tablegroup fails due to the failure of `yb-admin create_database_snapshot <keyspace>`.
The above example can be simplified as:
```
CREATE TABLEGROUP tg1;

CREATE TABLE test_tbl (
  a INT
) TABLEGROUP tg1;

CREATE INDEX idx  ON test_tbl (a ASC);
```

**Comment by yifanguan** [comment]
@def- Do you still have the logs? When you disable tablegroups for LST, do you still enable colocated databases?
Does the table identifier end with `colocated.parent.uuid`, (e.g. Table with identifier 000033e8000030008000000000000000.colocated.parent.uuid)? Thanks!

**Comment by def-** [comment]
No colocation used currently, but this failure happened with tablegroups (as a consequence I disabled tablegroups in backup/restore tests). Logs should still be available at https://portal.dev.yugabyte.com/universes/edaf84f8-508e-4fc0-840f-6b91d37ad21c

**Comment by sanketkedia** [comment]
I think @msun07 is fixing it as part of https://phabricator.dev.yugabyte.com/D19398

**Comment by yifanguan** [comment]
@sanketkedia @msun07 I'm also working on this including the whole backup process (create_database_snapshot, import_snapshot, platform backup script change): https://phabricator.dev.yugabyte.com/D18820, not from PITR perspective though.
I see there are some similar overlap changes in the function `CollectTable()`. This is fine. I can rebase onto D19398 if it is landed soon.
