### ISSUE TITLE
[flaky test] org.yb.clientent.TestReadReplicas.testCreateTableWithAddRemoveNode

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11644]
Jira Link: [DB-818](https://yugabyte.atlassian.net/browse/DB-818)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.clientent.TestReadReplicas&name=testCreateTableWithAddRemoveNode&num_commits=100&platform=all

@sanketkedia could this be related to your recent DDL work?

**Comment by rthallamko3** [comment]
According to report(https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.clientent.TestReadReplicas&name=testCreateTableWithAddRemoveNode&num_commits=100&platform=all), its no longer flaky/failing/. Resolving the issue
