### ISSUE TITLE
[YSQL] Integrate YSQL follower reads feature with READ COMMITTED isolation level

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#11641]
Jira Link: [DB-903](https://yugabyte.atlassian.net/browse/DB-903)
### Description

This will involve picking (now - yb_follower_read_staleness_ms) as the read point for each query.

**Comment by jameshartig** [comment]
We just ran into this. I assume it'll be ported back to 2.12? I also know that 2.14 is coming up so we're also considering just turning off read committed for now until 2.14.

**Comment by amitanandaiyer** [comment]
@jameshartig I am planning on porting this to 2.12.

in the meanwhile, as a workaround you could explicitly set queries that use follower reads to use Read_repeatable.

(you can still use Read Committed for non-follower read queries/updates)
