### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgDdlFaultTolerance.testDocDBMetadataFailuresForTable

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11650]
Jira Link: [DB-933](https://yugabyte.atlassian.net/browse/DB-933)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgDdlFaultTolerance&name=testDocDBMetadataFailuresForTable&platform=centos

**Comment by tverona1** [comment]
Verified this test failure is no longer occurring:

```
Builds Ending Around | Commits | Number of Failures | Delta
-- | -- | -- | --
06/19/2023 18:18 | dc4781a33~..dc4781a33 | 0 | 0

Builds Ending Around	Commits	Number of Failures	Delta
06/19/2023 18:18	[dc4781a33~..dc4781a33](https://github.com/yugabyte/yugabyte-db/compare/dc4781a33a1fe5cbed87c3b5daca56b545d23560~...dc4781a33a1fe5cbed87c3b5daca56b545d23560)	0	0
```

**Comment by rthallamko3** [comment]
Closing the issue as the test is no longer flaky.
