### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgRegressContribPostgresFdw.schedule

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11656]
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressContribPostgresFdw&name=schedule&num_commits=25&platform=all

**Comment by def-** [comment]
I have a change ready to fix this, sorry for the test failures.
