### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgRegressAggregates.testPgRegressAggregates

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11661]
Jira Link: [DB-1118](https://yugabyte.atlassian.net/browse/DB-1118)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressAggregates&name=testPgRegressAggregates&platform=centos

**Comment by m-iancu** [comment]
Closing as tests looks pretty stable now, no failure in last 10 builds: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressAggregates&name=testPgRegressAggregates
