### ISSUE TITLE
[Docs] Missing Information about add node

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#11667]
### Description

In the below document the release point is clear, but we don't follow through that you'll have to add the node back manually

https://docs.yugabyte.com/latest/yugabyte-platform/manage-deployments/add-nodes/

**Comment by tylarb** [comment]
Here's the "eliminate unresponsive node" - this should follow up at the bottom with a "next steps" -> "add back a node" https://docs.yugabyte.com/latest/yugabyte-platform/manage-deployments/remove-nodes/

**Comment by lizayugabyte** [comment]
Also outdated screen shot needs to be replaced on this page
