### ISSUE TITLE
[docs]Add policies required to perform all the S3 backup operations from platform

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#11677]
https://docs.yugabyte.com/latest/yugabyte-platform/back-up-restore-universes/configure-backup-storage/

## Issue description
Update documentation to add S3 bucket policies on resources/sub-resources required to perform necessary actions for backup/restore from the Yugabyte platform. Examples of such platform actions are create, copy, delete, restore, etc.

## Suggested resolution
1. Documenting all the actions platform performs on S3 for backup/restore
2. Actual policy required

**Comment by polarweasel** [comment]
Moved to Jira, as PLAT-3308
