### ISSUE TITLE
[YSQL] Refresh materialized view not successful on mat views created out of colocated tables(residing in a colocated database)

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#11680]
Jira Link: [DB-980](https://yugabyte.atlassian.net/browse/DB-980)
### Description

- Create a colocated database.
- Create a colocated table.
- Insert data into the table
- Create a non-colocated materialized view out of the colocated table
- Insert data into the table
- Refresh the materialized view

**Issue:** Materialized view contains 0 rows

<img width="497" alt="image" src="https://user-images.githubusercontent.com/87007277/157202081-b29184cb-9592-4a06-9078-e5a3dfdc5f45.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/87007277/157202444-366e40a4-af0a-402b-9a08-990f38fa5929.png">
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/87007277/157202511-eb2221f3-f3b0-4c29-8c7b-8835f40be30d.png">

CC: @fizaaluthra

**Comment by def-** [comment]
> Refresh materialized view not successful

If the `refresh` just failed, this would not be so bad. But it doesn't throw an error and instead you get outdated results afterwards, which is pretty bad.
