### ISSUE TITLE
[YSQL] Protobuf Log Line Spamming (String field contains invalid UTF-8 data)

### ISSUE THREAD

**Issue by nathanhjli** [yugabyte/yugabyte-db#11693]
### Description

Running any operation (COPY, INSERT, UPDATE, CREATE) on latest master branch leads to a lot of the same log line being spammed:

```[libprotobuf ERROR google/protobuf/wire_format_lite.cc:629] String field 'yb.PgsqlWriteRequestPB.partition_key' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.```

We need to confirm if this is an issue or just spam.

Might be related to @spolitov 's recent changes to write/read operations.

**Comment by bmatican** [comment]
Fixed. Related to the work in #9936
