### ISSUE TITLE
[DocDB] create_database_snapshot with a large number of objects (>60000) can cause yb-master to OOM

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#11696]
### Description

When attempting to run a `yb-admin create_database_snapshot` on a YSQL database with a large number of objects (>60000) and roughly 3000/tablets per node causes yb-master to allocate a large block of heap memory in excess of 130GB. 

It should be reproducible by creating a large number of simple tables in a colocated database with a mix of ~100 tables that are split into 4 tablets / node. It likely could take less than 60000 tables to repro this.

**Comment by sanketkedia** [comment]
Closing this as #12782 tracks this issue
