### ISSUE TITLE
Support clustering in Redis

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#117]
This task involves the following:
1. Support for the Redis clustering commands (CLUSTER commands)
2. Detect move of a tablet and teach the Jedis client (or any Redis client for that matter) about the tablet move
3. Enhance the load tester to use the cluster commands.

**Comment by hectorgcr** [comment]
The most important command to work with redis cluster is CLUSTER SLOTS (commit https://github.com/YugaByte/yugabyte-db/commit/bd28d6ec506c3d97d68eb5c33a2bb70758463da7). This is what the jedis driver uses. If there is any other CLUSTER command that anyone else needs, let's open another issue with the specific command that is needed.
