### ISSUE TITLE
[docs] Configure the Amazon Web Services (AWS) cloud provider

### ISSUE THREAD

**Issue by skahler-yuga** [yugabyte/yugabyte-db#11708]
https://docs.yugabyte.com/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws/

## Issue description

All of the environment links point back to latest when in stable docs

## Suggested resolution

Stable docs should point only to stable links

**Comment by ddhodge** [comment]
This is fixed
