### ISSUE TITLE
[DocDB] Fix compilation for gcc9 release

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#11712]
### Description

Even after doing compilation fixes for gcc9 fastdebug (#11710), it fails for release:

    /-------------------------------------------------------------------------------
    | COMPILATION FAILED
    |-------------------------------------------------------------------------------
    In file included from src/postgres/src/include/postgres.h:47,
                     from src/postgres/src/backend/tcop/postgres.c:20:
    src/postgres/src/backend/tcop/postgres.c: In function ‘yb_exec_query_wrapper’:
    src/postgres/src/include/utils/elog.h:301:15: error: ‘save_exception_stack’ is used uninitialized in this function [-Werror=uninitialized]
      301 |   sigjmp_buf *save_exception_stack = PG_exception_stack; \
          |               ^~~~~~~~~~~~~~~~~~~~
    src/postgres/src/include/utils/elog.h:301:15: note: ‘save_exception_stack’ was declared here
      301 |   sigjmp_buf *save_exception_stack = PG_exception_stack; \
          |               ^~~~~~~~~~~~~~~~~~~~
    src/postgres/src/backend/tcop/postgres.c:4526:3: note: in expansion of macro ‘PG_TRY’
     4526 |   PG_TRY();
          |   ^~~~~~
    src/postgres/src/include/utils/elog.h:302:25: error: ‘save_context_stack’ is used uninitialized in this function [-Werror=uninitialized]
      302 |   ErrorContextCallback *save_context_stack = error_context_stack; \
          |                         ^~~~~~~~~~~~~~~~~~
    src/postgres/src/include/utils/elog.h:302:25: note: ‘save_context_stack’ was declared here
      302 |   ErrorContextCallback *save_context_stack = error_context_stack; \
          |                         ^~~~~~~~~~~~~~~~~~
    src/postgres/src/backend/tcop/postgres.c:4526:3: note: in expansion of macro ‘PG_TRY’
     4526 |   PG_TRY();
          |   ^~~~~~
    cc1: all warnings being treated as errors
    Input files:
      build/release-gcc9-dynamic-ninja/postgres_build/src/backend/tcop/postgres.c
    Output file (from -o): postgres.o
    \-------------------------------------------------------------------------------

Fix this.

**Comment by jaki** [comment]
The code in that commit matches https://www.postgresql.org/message-id/25875.1565275667%40sss.pgh.pa.us (Re: PG_TRY()/CATCH() in a loop reports uninitialized variables):

> I'd be inclined to say "so don't do that then".

cc: @andrei-mart

**Comment by andrei-mart** [comment]
The issue is much older than https://github.com/yugabyte/yugabyte-db/commit/5d1f26b0acb7200edfff686d981165e9c1c99375,
the problem there is PG_TRY/PG_CATCH block used in a loop, and it has been in a loop since https://github.com/yugabyte/yugabyte-db/commit/3212616e351647436f808d4963d229e7881996c8

**Comment by mbautin** [comment]
Can we move the loop body to a separate function?

**Comment by mbautin** [comment]
But let's do that after we see if this error goes away with GCC 10 or newer.

**Comment by mbautin** [comment]
The issue is present with GCC 10 too. But this seems to work:
```
static void
yb_exec_query_wrapper_one_attempt(
	MemoryContext exec_context,
	YBQueryRestartData* restart_data,
	YBFunctor functor,
	const void* functor_context,
	int attempt,
	bool* retry)
{
	elog(DEBUG2, "yb_exec_query_wrapper attempt %d for %s", attempt, restart_data->query_string);
	YBSaveOutputBufferPosition(
		!yb_is_begin_transaction(restart_data->command_tag));
	PG_TRY();
	{
		(*functor)(functor_context);
		/*
			* Stop retrying if successful. Note, break or return could not be
			* used here, they would prevent PG_END_TRY();
			*/
		*retry = false;
	}
	PG_CATCH();
	{
		YBResetOperationsBuffering();
		yb_attempt_to_restart_on_error(attempt, restart_data, exec_context);
	}
	PG_END_TRY();
}

static void
yb_exec_query_wrapper(MemoryContext exec_context,
					  YBQueryRestartData* restart_data,
					  YBFunctor functor,
					  const void* functor_context)
{
	bool retry = true;
	for (int attempt = 0; retry; ++attempt)
	{
		yb_exec_query_wrapper_one_attempt(
			exec_context, restart_data, functor, functor_context, attempt, &retry);
	}
}
```
