### ISSUE TITLE
[YCQL] Create Table Statement Causes Tserver to restart.

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#11713]
### Description

We have a customer who reported their tservers crashed when issuing the DDL below ion version 2.6.1.1

I have reproduced the error in 2.11

CREATE TABLE CompositionOverrides (
               ...     kind INT,                            -- Which of category/trovider/symbol.
               ...     key TEXT,                            -- Actual category/provider/symbol.
               ...     overridden TEXT,                     -- Underlier this applies to.
               ...     effective_start INT,                 -- Start of effective date range.
               ...     effective_end INT,                   -- End of effective date range.
               ...     asof_start INT,                      -- Start of asof range.
               ...     asof_end INT,                        -- End of asof time.
               ...     overriders SET<TUPLE<TEXT, DOUBLE>>, -- Resulting underliers and quantities
               ...     notes TEXT,                          -- Why was this override added?
               ... ) WITH CLUSTERING ORDER BY (asof_time DESC) AND
               ...        transactions = {'enabled': true};
NoHostAvailable:

Last thing in the tserver INFO and warnings logs below, nothing to indicate what caused the re-start.

W0310 15:40:27.853497 26633 process_context.cc:185] SQL Error: Feature Not Supported
CREATE TABLE CompositionOverrides (
    kind INT,                            -- Which of category/trovider/symbol.
    key TEXT,                            -- Actual category/provider/symbol.
    overridden TEXT,                     -- Underlier this applies to.
    effective_start INT,                 -- Start of effective date range.
    effective_end INT,                   -- End of effective date range.
    asof_start INT,                      -- Start of asof range.
    asof_end INT,                        -- End of asof time.
    overriders SET<TUPLE<TEXT, DOUBLE>>, -- Resulting underliers and quantities
               ^^^^^
    notes TEXT,                          -- Why was this override added?
) WITH CLUSTERING ORDER BY (asof_time DESC) AND
       transactions = {'enabled': true};

**Comment by mheer9** [comment]
We have a work around with User Defined Types

Example
CREATE TYPE overriders_tuple (underlier TEXT, quantity DOUBLE);

CREATE TABLE CompositionOverrides (
kind INT, -- Which of category/trovider/symbol.
key TEXT, -- Actual category/provider/symbol.
overridden TEXT, -- Underlier this applies to.
effective_start INT, -- Start of effective date range.
effective_end INT, -- End of effective date range.
asof_start INT, -- Start of asof range.
asof_end INT, -- End of asof time.
overriders set<frozen<overriders_tuple>>, -- Resulting underliers and quantities
notes TEXT, -- Why was this override added?
......

**Comment by paullee-yb** [comment]
It seems like we don't support `TUPLE`:

```
CREATE TABLE test(a INT PRIMARY KEY, b TUPLE<TEXT, DOUBLE>);
SyntaxException: Feature Not Supported
CREATE TABLE test2(a INT PRIMARY KEY, b TUPLE<TEXT, DOUBLE>);
                                        ^^^^^
 (ql error -14)
```

Our docs seem to also indicate this [here](https://docs.yugabyte.com/preview/api/ycql/):
![image](https://user-images.githubusercontent.com/97252550/164049839-8bc4419c-6ace-4149-9e8e-7027303f9ea9.png)

**Comment by paullee-yb** [comment]
Closing this issue as this is expected behavior.
