### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgRegressPlpgsql.testPgRegressPlpgsql

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11715]
Jira Link: [DB-969](https://yugabyte.atlassian.net/browse/DB-969)
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&buckets=20&build_type=all&class=org.yb.pgsql.TestPgRegressPlpgsql&name=testPgRegressPlpgsql&num_commits=25&platform=all

seems to point to https://github.com/yugabyte/yugabyte-db/commit/c5f512583fc7ecbc054584d59b19c584a94bd0ee

**Comment by m-iancu** [comment]
Fixed by [615bb75](https://github.com/yugabyte/yugabyte-db/commit/615bb758d8046d840f88a75612a507d4ede808a0).
