### ISSUE TITLE
[Docs] Sentence in "Restore data" is incomplete

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#11721]
### Description

https://docs.yugabyte.com/latest/manage/backup-restore/restore-data/

This sentence is incomplete:

"The ysqlsh -f command will read the SQL statements from the specified file and"

**Comment by aishwarya24** [comment]
Thanks @hari90 ! Will fix it.
Another issue on this page is to fix the link one the last line :

For details about using this command, see [-f, -file](https://docs.yugabyte.com/latest/admin/ysqlsh/#-f-filename-file-filename) in the [ysqlsh](https://docs.yugabyte.com/latest/admin/ysqlsh/) documentation.

The right link for [-f, -file] is https://docs.yugabyte.com/latest/admin/ysqlsh/#f-filename-file-filename
