### ISSUE TITLE
[docs] Explicit locking

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#11736]
https://docs.yugabyte.com/latest/architecture/transactions/explicit-locking/

> DocDB exposes the ability to write [provisional records](https://docs.yugabyte.com/latest/architecture/transactions/explicit-locking/) which is exercised by the query layer.

The link provided redirects to the same page

**Comment by polarweasel** [comment]
No dead links on explicit locking or distributed transactions (new home of provisional records) pages now.
