### ISSUE TITLE
[Docs] AWS Security group is missing ports

### ISSUE THREAD

**Issue by nzaporozhets** [yugabyte/yugabyte-db#11751]
AWS platform prep [page](https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws/#create-a-new-security-group-optional) (section about custom VPCs) as well as the Default ports [page](https://docs.yugabyte.com/latest/reference/configuration/default-ports/)  and [Ports part of On-prem page](https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes/#ports) are missing info about port `54422`. Platform installer is reconfiguring nodes to use it as a default SSH port, so if it's missing from the security group, the installation will fail due to nodes being unreachable.

**Comment by lizayugabyte** [comment]
@nzaporozhets Could you, please, let me know under which category I should add 54422 in https://docs.yugabyte.com/latest/reference/configuration/default-ports/ and https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes/#ports ?

**Comment by lizayugabyte** [comment]
@nzaporozhets Should the firewall rules section for GCP also have port 54422 added?   https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#create-a-firewall-rule

**Comment by nzaporozhets** [comment]
Sure! In my opinion, for https://docs.yugabyte.com/latest/reference/configuration/default-ports/ – it should go to the **Firewall rules** under something like "Custom SSH port for Universe nodes", for the https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes/#ports – the second list, talking about intra-cluster comms.
