### ISSUE TITLE
[docs] IAM role for AWS Platform is missing some permissions

### ISSUE THREAD

**Issue by nzaporozhets** [yugabyte/yugabyte-db#11750]
IAM role creation section of AWS platform prep [page](https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws/#create-an-iam-role-optional) is missing some of the required IAM role permissions. I was able to compile a list reiteratively, but this may need a better review and a more thorough testing. Absence of those definitely blocks the installation though:

``` "ec2:AcceptVpcPeeringConnection",
"ec2:AssociateRouteTable",
"ec2:AttachInternetGateway",
"ec2:CreateInternetGateway",
"ec2:CreateRoute",
"ec2:CreateSubnet",
"ec2:CreateVpc",
"ec2:CreateVpcPeeringConnection",
"ec2:DisassociateRouteTable",
"ec2:ModifyVpcAttribute"
```

**Comment by lizayugabyte** [comment]
When this is resolved, I'll also set https://yugabyte.atlassian.net/browse/PLAT-2739 to "done"
