### ISSUE TITLE
[YSQL] Table with identifier 000000010000300080000000000004ec not found

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#11763]
### Description

I did the following:

1. bin/yb-ctl destroy
2. ./yb_build.sh reinitdb
3. bin/yb-ctl create --replication_factor 1
4. bin/ysqlsh
```
ysqlsh: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
FATAL:  Not found: Table with identifier 000000010000300080000000000004ec not found: OBJECT_NOT_FOUND
```
As of commit cea30678aa1f557b59992dba06577a46357cc536

**Comment by tedyu** [comment]
If I back out D15799, the above procedure doesn't get error.

**Comment by frozenspider** [comment]
@tedyu there indeed is an issue introduced in D15799 (#7378, 71d527c6), but I can't reproduce it the way you listed.
```
git checkout cea3067
ybd
ybd reinitdb
./bin/yb-ctl destroy
./bin/yb-ctl create --rf=1
./bin/ysqlsh
```
```
ysqlsh (11.2-YB-2.13.1.0-b0)
Type "help" for help.

yugabyte=#
```
