### ISSUE TITLE
Limit the total amount of memory consumed by network read buffers

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#118]
When there are a very large number of outstanding operations (very large IO spikes), YugaByte DB could run out of memory a few times due to allocating too many read buffers. Limit the total amount of memory allocated by read buffers and slow down request processing in that case.

**Comment by rkarthik007** [comment]
Is this done @spolitov? If so could we please add the commit id and close... thanks!

**Comment by spolitov** [comment]
There is related diff, that allows to specify such limit based on available RAM.
So I think it would be better to close this issue when that diff is also landed.

**Comment by spolitov** [comment]
Done in 0fc413a1a905000649c3a1208af06f2362d63994
