### ISSUE TITLE
[YSQL] Presence of index affects update latency even though columns updated are not indexed

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#11806]
### Description

In the following test case, k is the PRIMARY KEY column, v1 is an indexed column and v2 is an ordinary column.

An UPDATE which is just updating column v2 (and not v1) should (ideally) not be affected by the presence or absence of an index on column v1. However, you can see in the test below that dropping the index on v1 helps improve the latency of the UPDATE operation to column v2 (from about 37ms to 23ms).

*Note: The latencies are higher that normal because this a RF=5 multi-region cluster in AWS across three regions - east1 (RF=2) / east2(RF=2) / west1(RF=1); and, east1 region is the preferred region in this test.*

```
$ ./ysqlsh -h  172.152.35.235 -f /tmp/c.sql -e
CREATE TABLE orders (
      k int PRIMARY KEY,
      v1 text,
      v2 int);

CREATE INDEX v1_idx ON orders(v1);

insert into orders(k, v1, v2) values (1, 'hello', 2);
INSERT 0 1
Timing is on.


update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 62.823 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 37.654 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 36.749 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 37.599 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 37.369 ms


drop index v1_idx;
DROP INDEX
Time: 297.396 ms


update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 23.286 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 23.228 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 24.080 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 23.252 ms
update orders set v2 = 3 where k = 1;
UPDATE 1
Time: 22.811 ms
```

**Comment by ramsrivatsa** [comment]
Fixed this issue with the following commit [4b5e59d](https://github.com/yugabyte/yugabyte-db/commit/4b5e59df3d98401fe736c53a0d6fa707381123b6).
