### ISSUE TITLE
[Docs] Document Diesel in Integrations

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yugabyte-db#11828]
### Description

Here is the link to the [initial documentation](https://docs.google.com/document/d/1tUbyw0nb0nXJLUWDRvnuAknAcsXsj6nkgvUnmEAh2PE/edit?usp=sharing) of Diesel to add in the [Integrations tab](https://docs.yugabyte.com/latest/integrations/) for rust. In case of any questions please let me know.

**Comment by aishwarya24** [comment]
@priyanshi-yb , Can we close this one , now that its landed in Drivers and ORMs ?

**Comment by priyanshi-yb** [comment]
@aishwarya24, yes please. Thanks!
