### ISSUE TITLE
[docs] document how to use a custom TLS certificate for Platform install on k8s

### ISSUE THREAD

**Issue by msyed30** [yugabyte/yugabyte-db#11838]
### Description

We don't have document on how to customize the certs instead of using  the default cert with the key on github

**Comment by tylarb** [comment]
The docs note that you can provide a customer cert using replicated workflow:
https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/install-software/default/

It's also noted that you can set the SSL protocol for kuberneted: https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes/

""" 
Optionally, set the TLS version for Nginx frontend by using ssl_protocols operational directive in the Helm installation, as follows:
```
helm install yw-test yugabytedb/yugaware --version 2.13.0 -n yb-platform --wait --set tls.sslProtocols="TLSv1.2"
```
"""

However, the docs do not demonstrate how to provide a custom TLS certificate for platform install in the helm chart.

The setting to set the TLS cert for Platform itself is here - https://github.com/yugabyte/charts/blob/470f0f4704b843978abb37230d3fb238e7f21d73/stable/yugaware/values.yaml#L109 

in the helm values and it makes its way to this nginx config at 
https://github.com/yugabyte/charts/blob/master/stable/yugaware/templates/configs.yaml#L161 

@iSignal  can provide more detail if required
