### ISSUE TITLE
[YEDIS] Support for SETNX

### ISSUE THREAD

**Issue by surculus12** [YugaByte/yugabyte-db#1183]
[YEDIS is not receiving new features, but as this is small addition I was told to open an issue.]

SETNX is not implemented in the YEDIS API. It is blocking use of YEDIS as a Celery broker.

It's also a useful and relatively simple extension of SET.

**Comment by OlegLoginov** [comment]
Fixed:   https://github.com/YugaByte/yugabyte-db/commit/48cedb3024552e462465592da3f0f2463fff89d4
