### ISSUE TITLE
[YSQL] Query latency increased on upgrade from 2.4.4 to 2.8.3

### ISSUE THREAD

**Issue by dataindataout** [yugabyte/yugabyte-db#11841]
Jira Link: [DB-713](https://yugabyte.atlassian.net/browse/DB-713)
### Description

Query latency increased on upgrade from 2.4.4 to 2.8.3.

Query involved joining two tables, with otherwise normal characteristics. On 2.4.4, the query used an index scan; post-upgrade to 2.8.3, the query used only a sequential scan.

Refer to internal ticket for specifics.

**Comment by CharlotteRose** [comment]
@dataindataout @sushantrmishra - is this still an issue? Do we need a JIRA for this?
