### ISSUE TITLE
[DocDB] PITR: Disable restoring to before a run of ysql_upgrade

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11846]
### Description

@frozenspider has introduced a framework for the YSQL side, to do system table upgrades (eg: add new system tables, update them, etc). This however might not always be safe to undo via PITR. As such, we could just disallow restoring to a time before the upgrade was performed.

Docs for `ysql_upgrade` usage: https://docs.yugabyte.com/latest/manage/upgrade-deployment/#upgrade-ysql-system-catalog

Recent commit that had to factor in `ysql_upgrade` and modify some of the relevant tests: https://github.com/yugabyte/yugabyte-db/commit/4c44705514f01e9135fc49b6912ad695f50d5d64

Can reach out to Alex for info on where we store the version info for each upgrade, ie: which system table stores the record of all migrations -- we'll need to query this before / after a PITR, to tell if we were asked to rollback to a point before a `ysql_upgrade`.

Can reach out to @sanketkedia for more info on where in `ent/src/yb/master/restore_sys_catalog_state.cc` to plug in and check for the version change + how to properly error out from this level, all the way back to the user.

**Comment by bmatican** [comment]
Switching this from Sandeep to Hari, so you both get some exposure to PITR + YSQL DDLs.

**Comment by sanketkedia** [comment]
Had a detailed conversation with @bmatican and @frozenspider , we've agreed to go with the following approach:

```
you do PITR from now to time T
if you don’t have pg_yb_migration now, then you definitely didn’t at time T and could not possible have schema changes — allow
if you have pg_yb_migration now, but didn’t at time T — reject
if you have pg_yb_migration now and also at time T — reject if version is different
```

**Comment by druzac** [comment]
[d94ebef4b2e78f08158c3bd734ec3e350ff922fa](https://github.com/yugabyte/yugabyte-db/commit/d94ebef4b2e78f08158c3bd734ec3e350ff922fa) will fail a PITR that would make any changes to the `pg_yb_migration` table. It also fails PITRs to a snapshot with any difference in the set of system catalog tables.
