### ISSUE TITLE
[DocDB] Throttle RestoreSnapshot requests

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11847]
### Description

As a followup to #10482, we should also add means to rate limit restore operations as well.
cc @spolitov

**Comment by sanketkedia** [comment]
In the committed diff above, the degree of restoration concurrency is controlled by master flags `max_concurrent_restoration_rpcs` and `max_concurrent_restoration_rpcs_per_tserver` which are a measure of the maximum number of restore requests that can be concurrent at any given point in time.

The following determine how to use them. If the value of max_concurrent_restoration_rpcs is:
```
> 0:  use max_concurrent_snapshot_rpcs value as #concurrent RPCs
= 0 : INT_MAX is the #concurrent RPCs
< 0 : #concurrent RPCs is num_servers * max_concurrent_restoration_rpcs_per_tserver
```
