### ISSUE TITLE
[YSQL] Operator pushdown to DocDB

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#11850]
Jira Link: [DB-846](https://yugabyte.atlassian.net/browse/DB-846)
### Description

This is roadmap tracking item to perform the operator pushdown to the docDB to more efficiently execute the queries.
Status | Feature | GitHub Issue | Comments
-- | -- | -- | --
✅  |Row Comparison Expressions don't get pushed down| #11463 | 
✅  |DocDB does not process lookups on a subset of range key| #8023 | 
✅  |Query with IN clause on clustering column causes wider range scan that needed| #11142 | 
✅  |Push down yb_hash_code function into DocDB| #8718 | 
✅  | Strict inequality conditions are pushed down as non-strict inequalities to DocDB| #10738 | 
✅  |Push down LIKE operator | #2970 | 
✅  |Push down regex matching | #2971 | 
| | SELECT/UPDATE with OR on primary key should use index | #3131 | 
✅  |Push down arithmetic operators to docDB | #2969 | 
| ✅ | Push down aggregate queries with WHERE clause | #2931 | 

[DB-846]: https://yugabyte.atlassian.net/browse/DB-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ymahajan** [comment]
@sushantrmishra - This Master issue is for YSQL but it looks like we are tracking YCQL issues like https://github.com/yugabyte/yugabyte-db/issues/11142 as part of this. Should we have a separate Master issue for CQL query optimization?
