### ISSUE TITLE
[YSQL] how to install extension oracle_fdw in yugabyte-db

### ISSUE THREAD

**Issue by TiannV** [yugabyte/yugabyte-db#11878]
### Description

How to install extension oracle_fdw in yugabyte-db

**Comment by ddorian** [comment]
@TiannV can you follow steps on https://docs.yugabyte.com/latest/explore/ysql-language-features/pg-extensions/ ?

**Comment by TiannV** [comment]
Successed after modified the post_install.sh and `post_install.sh -e`
```
supported_extensions="postgis oracle_fdw"
declare -A libfiles
libfiles["postgis"]="$(ls $lib_pg_dir/*postgis*.so 2>/dev/null || exit 0)"
libfiles["oracle_fdw"]="$(ls $lib_pg_dir/*oracle_fdw*.so 2>/dev/null || exit 0)"
```
