### ISSUE TITLE
CHECK(leader_state_cache_.is_lock_free()) fails in gcc 7

### ISSUE THREAD

**Issue by rajukumaryb** [YugaByte/yugabyte-db#1189]
Original description of the issue as filed by @rajukumaryb :
Master process does not start on Ubuntu 18.04 following a "destroy + create" sequence

**Comment by rajukumaryb** [comment]
Output of yb-master.raju-ubuntu1804.raju.log.INFO.20190402-234308.21926

Log file created at: 2019/04/02 23:43:08
Running on machine: raju-ubuntu1804
Application fingerprint: version 1.2.4.0 build PRE_RELEASE revision 2af8b68b360b90e8f8fa0b3b8db4d83f7c87d0e5 build_type DEBUG built at 02 Apr 2019 23:29:42 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0402 23:43:08.656505 21926 master_main.cc:93] NumCPUs determined to be: 8
I0402 23:43:08.658072 21926 mem_tracker.cc:240] MemTracker: hard memory limit is 0.778885 GB
I0402 23:43:08.658131 21926 mem_tracker.cc:242] MemTracker: soft memory limit is 0.662052 GB
I0402 23:43:08.668902 21926 master_main.cc:108] Initializing master server...
I0402 23:43:08.669593 21926 server_base.cc:411] Could not load existing FS layout: Not found (yb/util/env_posix.cc:1013): /home/raju/yugabyte-data/node-1/disk-1/yb-data/master/instance: No such file or directory (error 2)
I0402 23:43:08.669767 21926 server_base.cc:412] Creating new FS layout
I0402 23:43:08.679858 21926 fs_manager.cc:388] Generated new instance metadata in path /home/raju/yugabyte-data/node-1/disk-1/yb-data/master/instance:
uuid: "f67f97ddb95f43868d1a64d02b036bd5"
format_stamp: "Formatted at 2019-04-02 23:43:08 on raju-ubuntu1804"
I0402 23:43:08.687199 21926 fs_manager.cc:388] Generated new instance metadata in path /home/raju/yugabyte-data/node-1/disk-2/yb-data/master/instance:
uuid: "f67f97ddb95f43868d1a64d02b036bd5"
format_stamp: "Formatted at 2019-04-02 23:43:08 on raju-ubuntu1804"
I0402 23:43:08.692404 21926 fs_manager.cc:232] Opened local filesystem: /home/raju/yugabyte-data/node-1/disk-1,/home/raju/yugabyte-data/node-1/disk-2
uuid: "f67f97ddb95f43868d1a64d02b036bd5"
format_stamp: "Formatted at 2019-04-02 23:43:08 on raju-ubuntu1804"
I0402 23:43:08.694295 21926 server_base.cc:198] Auto setting FLAGS_num_reactor_threads to 8
I0402 23:43:08.707659 21926 master_main.cc:111] Starting Master server...
I0402 23:43:08.723924 21926 webserver.cc:147] Starting webserver on 127.0.0.1:7000
I0402 23:43:08.724134 21926 webserver.cc:152] Document root: /home/raju/code/yugabyte/www
I0402 23:43:08.725191 21926 webserver.cc:239] Webserver started. Bound to: http://127.0.0.1:7000/
I0402 23:43:08.729696 21926 rpc_server.cc:167] RPC server started. Bound to: 127.0.0.1:7100
I0402 23:43:08.729861 21926 server_base.cc:450] Using private ip address 127.0.0.1
I0402 23:43:08.731357 22007 sys_catalog.cc:261] Creating new SysCatalogTable data
I0402 23:43:08.746498 22007 sys_catalog.cc:311] Determining permanent_uuid for [127.0.0.1:7100]
I0402 23:43:08.758729 22008 server_base.cc:450] Using private ip address 127.0.0.1
I0402 23:43:08.761692 22007 sys_catalog.cc:326] Setting up raft configuration: opid_index: -1 peers { permanent_uuid: "f67f97ddb95f43868d1a64d02b036bd5" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } }
I0402 23:43:08.762526 22007 consensus_meta.cc:248] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Updating active role from UNKNOWN_ROLE to FOLLOWER. Consensus state: current_term: 0 leader_uuid: "" config { opid_index: -1 peers { permanent_uuid: "f67f97ddb95f43868d1a64d02b036bd5" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
I0402 23:43:08.772284 22007 server_base.cc:450] Using private ip address 127.0.0.1
I0402 23:43:08.772966 22007 tablet_peer.cc:963] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5 [state=BOOTSTRAPPING]: Changed state from NOT_STARTED to BOOTSTRAPPING
I0402 23:43:08.773701 22007 consensus_meta.cc:248] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Updating active role from UNKNOWN_ROLE to FOLLOWER. Consensus state: current_term: 0 leader_uuid: "" config { opid_index: -1 peers { permanent_uuid: "f67f97ddb95f43868d1a64d02b036bd5" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
I0402 23:43:08.774181 22007 tablet_bootstrap_if.cc:71] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Bootstrap starting.
I0402 23:43:08.778533 22007 docdb_rocksdb_util.cc:390] Auto setting FLAGS_rocksdb_max_background_flushes to 2
I0402 23:43:08.778910 22007 docdb_rocksdb_util.cc:409] Auto setting FLAGS_rocksdb_max_background_compactions to 2
I0402 23:43:08.778960 22007 docdb_rocksdb_util.cc:416] Auto setting FLAGS_rocksdb_base_background_compactions to 2
I0402 23:43:08.780329 22007 tablet.cc:421] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Creating RocksDB database in dir /home/raju/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000
I0402 23:43:08.808970 22007 tablet.cc:507] Opening RocksDB at: /home/raju/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000
I0402 23:43:08.815714 22007 db_impl.cc:478] T 00000000000000000000000000000000: Creating manifest 1
I0402 23:43:08.830760 22007 version_set.cc:2802] T 00000000000000000000000000000000: Recovered from manifest file:/home/raju/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/MANIFEST-000001 succeeded,manifest_file_number is 1, next_file_number is 3, last_sequence is 1125899906842624, log_number is 0,prev_log_number is 0,max_column_family is 0, flushed_values is <NULL>
I0402 23:43:08.831295 22007 version_set.cc:2810] T 00000000000000000000000000000000: Column family [default] (ID 0), log number is 0
I0402 23:43:08.844755 22007 db_impl.cc:5820] T 00000000000000000000000000000000: DB pointer 0x55d62c404000
I0402 23:43:08.845494 22007 tablet.cc:554] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Successfully opened a RocksDB database at /home/raju/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000, obj: 0x55d62c404000
I0402 23:43:08.845839 22007 tablet_bootstrap.cc:400] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Time spent opening tablet: real 0.068s      user 0.026s     sys 0.000s
I0402 23:43:08.846583 22007 tablet_bootstrap.cc:339] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: No blocks or log segments found. Creating new log.
I0402 23:43:08.848775 22007 log.cc:396] durable_wal_write is turned on.
I0402 23:43:08.858319 22007 tablet_bootstrap_if.cc:71] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: No bootstrap required, opened a new log
I0402 23:43:08.869271 22007 consensus_meta.cc:248] T 00000000000000000000000000000000 P f67f97ddb95f43868d1a64d02b036bd5: Updating active role from UNKNOWN_ROLE to FOLLOWER. Consensus state: current_term: 0 leader_uuid: "" config { opid_index: -1 peers { permanent_uuid: "f67f97ddb95f43868d1a64d02b036bd5" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
F0402 23:43:08.874306 22007 replica_state.cc:111] Check failed: leader_state_cache_.is_lock_free()

**Comment by rajukumaryb** [comment]
cc - @bmatican

**Comment by bmatican** [comment]
@spolitov does `CHECK(leader_state_cache_.is_lock_free());` have to be a check?

https://en.cppreference.com/w/cpp/atomic/atomic/is_lock_free
> All atomic types except for std::atomic_flag may be implemented using mutexes or other locking operations, rather than using the lock-free atomic CPU instructions. Atomic types are also allowed to be sometimes lock-free

**Comment by mbautin** [comment]
Moving comments from #1246 here:

From @d-uspenskiy :

It looks like g++-7 generates non-lock-free code for 128 bits atomic structures

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80878

as a result 
`
CHECK(leader_state_cache_.is_lock_free()); 
`
fails at runtime

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/consensus/replica_state.cc#L111



---

Some description about changes in g++-7

https://gcc.gnu.org/ml/gcc-patches/2017-01/msg02344.html

**Comment by mbautin** [comment]
Two more potentially relevant links:

http://gcc.1065356.n8.nabble.com/GCC-in-line-assembly-and-the-removal-of-mcx16-td1378660.html

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80878

**Comment by spolitov** [comment]
Could we just use `boost::atomic` for 16 bytes structures?

**Comment by mbautin** [comment]
From an offline discussion with @spolitov:
- boost::atomic also has an assertion to check if it is lock-free.
- We need to revisit all atomics in the codebase and add a check that they are lock-free.

**Comment by spolitov** [comment]
The check should be added for 16 bytes atomics, so to revisit we could use the following command:
`git grep 'std::atomic<' | grep -v -E 'std::atomic<(bool|int|.?int\d\d?_t|size_t|MonoTime|\w+\*|MonoDelta|double)>' | less`

It will give all suspicious usages of std::atomic, that should be checked. 
Most of them are for enums and other small types and could be skipped.

**Comment by mbautin** [comment]
BTW here is the patch that @rajukumaryb has been using locally: https://gist.githubusercontent.com/mbautin/bbb02cbf60df635b8a92a548789d54ed/raw

**Comment by mbautin** [comment]
@d-uspenskiy: we should be able to upgrade to gcc 7.x (the default version on Ubuntu 18.04) when we fix the lock-free/atomic-related issues mentioned above.

**Comment by d-uspenskiy** [comment]
> git grep 'std::atomic<' | grep -v -E 'std::atomic<(bool|int|.?int\d\d?_t|size_t|MonoTime|\w+\*|MonoDelta|double)>' | less

Sligtly updated regex
