### ISSUE TITLE
[DocDB] Switch update consensus to lightweight protobufs

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#11893]
Jira Link: [DB-943](https://yugabyte.atlassian.net/browse/DB-943)
### Description

Switch update consensus to lightweight protobufs, this reduces a bunch of CPU around additional memory allocations/deallocations, memory copies etc.

To begin with the Write and UpdateTransaction scenarios of UpdateConsensus can be tackled first, as they account for 99% of the UpdateConsensus RPCs.

The fix in https://github.com/yugabyte/yugabyte-db/issues/11720 can be used as the template.

**Comment by bmatican** [comment]
Done as part of #13703
