### ISSUE TITLE
[YSQL] Add UUID to yb_servers() function

### ISSUE THREAD

**Issue by xenown** [yugabyte/yugabyte-db#11906]
Jira Link: [DB-2753](https://yugabyte.atlassian.net/browse/DB-2753)
### Context

This is the 1st change in a series of diffs for porting the Postgres extension [pg_cron](https://github.com/citusdata/pg_cron) to yugabyte. The following summary assumes you understand how the original pg cron extension worked.

Unlike the original extension, we intend for this port to have all Postgres instances act as workers as opposed to a single worker which will complete the scheduled pg cron jobs. A job runs on one of the workers in a YB cluster. The `cron.job_run_details` table shows information about each individual job run. Example:

```
system_platform=# SELECT * from cron.job_run_details;
 jobid | runid | job_pid |    database     | username |        command         |  status   | return_message |          start_time           |           end_time            |  node_uuid        
-------+-------+---------+-----------------+----------+------------------------+-----------+----------------+-------------------------------+-------------------------------+-------------
     1 |   212 | 3820788 | system_platform | yugabyte | select pg_sleep(20), 1 | succeeded | SELECT 1       | 2022-07-21 19:36:02.241619+00 | 2022-07-21 19:36:24.754601+00 |  aedf2-dfs
     2 |   211 | 3820766 | system_platform | yugabyte | select pg_sleep(20), 1 | succeeded | SELECT 1       | 2022-07-21 19:36:02.069145+00 | 2022-07-21 19:36:24.712906+00 |  sedf7-bbs
```

The `cron.job_run_details` table exists in the original extension. However, we add a `node_uuid` column, which is the UUID of the node on which a job ran. The purpose behind this extra column is it'll be easier for the user to find which logs to look at in the case of a job failure/issue/debugging/etc. 

### Problem

However, the UUID field is currently not accessible in YB Managed. As an open-source feature, YB support for the pg_cron extension should be available across all tiers (YB OSS/Anywhere/Managed).

### Solution
We will add a node_uuid column to the `yb_servers()` function so users can map UUIDs to a specific node.

```
yugabyte=# select * from yb_servers();
   host    | port | uuid                                 | node_type | cloud  |   region    | zone  | public_ip 
-----------+------+--------------------------------------+-------------+-------+-------------------------------
 127.0.0.2 | 5433 | 123e4567-e89b-12d3-a456-426614174000 | primary   | cloud1 | datacenter1 | rack1 | 13.512.12
(3 rows)
```

**Comment by sushantrmishra** [comment]
Testing

**Comment by paullee-yb** [comment]
Resolved [here](https://github.com/yugabyte/yugabyte-db/commit/ff45d27295811c9e0bf411345095a7f504aa9c9c)
