### ISSUE TITLE
[Phase 2][YSQL] [Colocation + Materialized Views + PITR] crashes nodes in the cluster, takes leader down, generates core files

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#11951]
Jira Link: [[DB-379]](https://yugabyte.atlassian.net/browse/DB-379)
### Description

- Create a colocated database
- Set up PITR on the db
- Create a colocated table inside the colocated database
- Create a materialized view on the colocated table
- Create an index on the mat view.
- Insert rows into the table
- Refresh the mat view concurrently and non-concurrently
- Note down time
- Drop materialized view
- Execute a PITR
**Issue:**
1. Nodes in the cluster become unreachable
2. Core files are generated int he cluster
3. Leader is lost and leader is not re-elected

[DB-379]: https://yugabyte.atlassian.net/browse/DB-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@kripasreenivasan to confirm, do we see this on either of the 2 independent combos?
- colocation + PITR
- MV + PITR
- colocation + MV

**Comment by kripasreenivasan** [comment]
@bmatican 

colocation + MV, colocation + PITR are working. MV + PITR is working except for https://github.com/yugabyte/yugabyte-db/issues/11951.

This issue was filed 53 days back and there have hence been some fixes in the area of **colocation + PITR** and **mat views + colocation**. However, owing to https://github.com/yugabyte/yugabyte-db/issues/11951, I'm unable to restest the scenario outlined in this bug.

**Comment by msun07** [comment]
Follow the steps to reproduce the issue, the test has been done on both dev machine and cloud having RF=3 universe, [https://portal.dev.yugabyte.com/universes/ab6177a1-6c44-4149-9e99-c26fab0bb23c/overview] using 2.15.3.0-b77 DB version. The issue (node crash) is not shown up. Extra couple of operations has been done including multiple restoration, and the cluster is functioning normally. @lingamsandeep
