### ISSUE TITLE
Support checking both LocalStorage and Cookies for YugaWare authentication

### ISSUE THREAD

**Issue by Doug44444444** [YugaByte/yugabyte-db#1196]
In terms of YugaWare authentication, Could you support both LocalStorage and Cookies when user login? I tested YugaWare only support LocalStorage as of now. Since it's hard to share LocalStorage between sub domains, but we could use Cookies to solve this issue.

Thanks.

**Comment by WesleyW** [comment]
Both LocalStorage and Cookies should be supported now. If you have `customer_id` as well as either `customer_token` or `api_token` (#1163), YugaWare should skip the login page.

**Comment by ramkumarvs** [comment]
The way this feature works is:

For the first time you would make a PUT request to /api/v1/customers/<customer uuid>/api_token,  off-course this is an authenticated request which means you need to set the X-AUTH-TOKEN, but this endpoint would generated a API_TOKEN which wouldn't expire.

Then the next thing you do is set the browser cookie to have api_token and customer_id set. You also need to set the localStorage to have the customer_id. And then try to access the dashboard, it wouldn't redirect the user to the login page.
