### ISSUE TITLE
[Docs][CDCSDK]Add limitation in CDCSDK section about upgrade from pre 2.13 not supported

### ISSUE THREAD

**Issue by suranjan** [yugabyte/yugabyte-db#11978]
Jira Link: [DB-5381](https://yugabyte.atlassian.net/browse/DB-5381)
### Description

CDC is introduced in 2.13 and it requires certain metadata for it to decode the changes present in the WAL.
If a database has been upgraded from pre-2.13 YB to 2.13 YB, it doesn't have the metadata persent in the WAL file. So, even if CDC is enabled/stream is created, the CDC will not work.

The solution is to create the datbase afresh and re-create the tables and insert the data so that correct metadata is present in the WAL files.
We need to mention this limitation in our doc.

[DB-5381]: https://yugabyte.atlassian.net/browse/DB-5381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vaibhav-yb** [comment]
Closing as the support for CDC on upgrade from pre 2.13 was already added.
