### ISSUE TITLE
[docdb] Enforce consistency between in-memory locks acquired and intents written

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#11995]
Jira Link: [DB-4741](https://yugabyte.atlassian.net/browse/DB-4741)
In #11932, we found that `FOR UPDATE` queries would incorrectly allow simultaneous locking of the same row. This was because we were acquiring only `kStrongRead` in-memory locks on the specified rows fully qualified DocDB key. Still, the intents written at the full DocDB key correctly specified `[kStrongRead, kStrongWrite]`, so conflicts wouldn't be detected until at least one of the intents was written.

In general, there should never be a mismatch between the in-memory locks acquired during a `WriteQuery` vs. the intents written applying the same. We should add some debug-only logic or a series of tests to ensure this invariant is never violated.

**Comment by rthallamko3** [comment]
@robertsami , Can this be closed?
