### ISSUE TITLE
PITR | Document Correction

### ISSUE THREAD

**Issue by ankit-yb** [yugabyte/yugabyte-db#11991]
https://docs.yugabyte.com/latest/explore/cluster-management/point-in-time-recovery-ysql/

'-master_address < >' is missing from the commands. 

<img width="976" alt="Screenshot 2022-04-05 at 2 33 20 PM" src="https://user-images.githubusercontent.com/96438084/161917379-18e47464-602a-40ed-8cea-90d6b04a2d5f.png">

**Comment by ddorian** [comment]
This has already been fixed in a another issue.
