### ISSUE TITLE
[YSQL][LST] ERROR: Delete fails: Operation expired: Transaction 0a0ddb22-aa9a-4127-8714-3239133cad85 expired or aborted by a conflict: 40001

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11994]
Jira Link: [DB-1287](https://yugabyte.atlassian.net/browse/DB-1287)
### Description

This failure happened using the [Long-running System Test](https://github.com/yugabyte/yb-long-system-test/) framework I'm currently working on. Can be reproduced locally:
```
$ cd ~/code/yugabyte-db
$ bin/yb-ctl --replication_factor 3 create
$ cd ~/code/yb-long-system-test
$ git checkout 8c9c533d && ./long_system_test.py --threads=10 --complexity=full --seed=144814
[...]
2022-04-06 16:03:44,304 worker_4   ERROR    Unexpected query failure: SerializationFailureQuery: DELETE FROM t4 WHERE c4_int = -2147483648;
Action: SingleDeleteAction
Error class: SerializationFailure
Error code: 40001
Error message: ERROR:  Operation expired: Transaction 0a0ddb22-aa9a-4127-8714-3239133cad85 expired or aborted by a conflict: 40001
```
I am not entirely sure if this is an error or I should ignore this in the future. Can someone from YSQL team please advise?

**Comment by pkj415** [comment]
This is not a bug. You will see an expired or aborted transaction if that transaction was aborted by another conflict transactionl
