### ISSUE TITLE
Couldn't parse host home-linux warning

### ISSUE THREAD

**Issue by brianhks** [YugaByte/yugabyte-db#12]
Running yugabyte-0.9.1.0 on ubuntu.  I keep getting the following in the tserver log file

W1231 01:52:22.961686 11175 cql_server.cc:120] Couldn't parse host home-linux, error: Invalid argument

**Comment by schoudhury** [comment]
Seems you are listing the hostnames in the tserver config flags. We currently support only IP addresses as noted here: https://docs.yugabyte.com/deploy/multi-node-cluster/#step-3-start-yb-tservers

Could you retry with the IP addresses instead? We will work towards supporting hostnames soon.

**Comment by kmuthukk** [comment]
@robertpang : assigning this to you for initial look. Thanks!

**Comment by robertpang** [comment]
Fixed in commit [9ad424d](https://github.com/YugaByte/yugabyte-db/commit/9ad424d45ed51afaa2f68dd620ac1d354973283f).
