### ISSUE TITLE
[YSQL] ALTER table ALTER column

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1200]
Support variations of ALTER TABLE ALTER COLUMN like:

ALTER TABLE ALTER COLUMN SET/DROP NOT NULL
ALTER TABLE ALTER COLUMN SET/DROP default
ALTER TABLE ALTER COLUMN SET STORAGE (This should simply log a warning that storage params will be ignored, but the statement should succeed).

**Comment by ndeodhar** [comment]
This is needed by pg_dump, yugaware and graphql.

**Comment by georgeklees** [comment]
An example of why pg_dump needs this is in #1793. When we have a [table with a SERIAL key](http://www.postgresqltutorial.com/postgresql-serial/), the correct behavior (in vanilla Postgres, currently being fixed to occur in YugaByte also) is to make a table with an integer key, create a sequence for that key, and use ALTER TABLE ALTER COLUMN to make the default value of the integer key be the nextval() of that sequence.
