### ISSUE TITLE
[YSQL] Error starting yb-tserver while custom install: invalid locale settings

### ISSUE THREAD

**Issue by codeyrk** [YugaByte/yugabyte-db#1205]
Following steps: 
https://github.com/YugaByte/yugabyte-db/issues/1008#issuecomment-473481669
```
./yb-tserver --tserver_master_addrs $IP:7100 --fs_data_dirs $DATA_DIR --webserver_interface $IP --rpc_bind_addresses=$IP:9100  --start_pgsql_proxy
```
Fails with the following logs:
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: invalid locale settings; check LANG and LC_* environment variables
```
Env variable values:
```
$ echo $LANG
en_US.UTF-8

$printenv | grep LC_
<empty>
```

Before following these steps I stopped and destroyed a spawned instance via:
```
$ yb-docker-ctl stop 
$ yb-docker-ctl destroy
```

**Comment by kmuthukk** [comment]
Possibly related issues: 

https://github.com/YugaByte/yugabyte-db/issues/620

https://github.com/YugaByte/yugabyte-db/issues/582#issuecomment-472599605

CC: @m-iancu , @mbautin , @frozenspider in case you have more context.

**Comment by codeyrk** [comment]
LC_TYPE was set to UTF8. 
After unsetting, it worked.

**Comment by ndeodhar** [comment]
Note: yb-ctl takes care of unsetting LANG and LC_* environment variables before starting tserver. We need to update the steps in #1008 to take care of this.
