### ISSUE TITLE
Docs Page - Cloudflare and webserver connection issue

### ISSUE THREAD

**Issue by seethb** [yugabyte/yugabyte-db#12063]
### Description

while accessing https://docs.yugabyte.com/latest/explore/query-1-performance/query-tuning-intro/ Web server is returning an unknown error Ray ID: 6f807c8288563c07 • 2022-04-07 05:50:43 UTC getting the above error repeatedly while accessing our docs page.

Please find the message from the error screen:

What happened?
There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page). [Additional troubleshooting resources](https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520).

**Comment by ddorian** [comment]
I guess it was a temporary error while the webserver was offline for some reason, no?

**Comment by seethb** [comment]
Yes @ddorian its sometime coming
