### ISSUE TITLE
[YSQL] Set prefetch size to reasonable value instead of INT32_MAX

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#1206]
This is due to wrong prefetch limit.
- This default limit needs to be lower to "1024"

Coding-wise, In file "src/yb/yql/pggate/pg_doc_op.h"
```
  // Public constants.
  static const int64_t kPrefetchLimit = INT32_MAX;
```

_Originally posted by @nocaway in https://github.com/YugaByte/yugabyte-db/issues/1204#issuecomment-482867458_

**Comment by kmuthukk** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/4d5bdc7c090caed3bb847fcdf34adb0508391f40

**Comment by nocaway** [comment]
Lower limit to 1024
