### ISSUE TITLE
[YSQL] Return only the columns needed in index-only scan

### ISSUE THREAD

**Issue by robertpang** [yugabyte/yugabyte-db#1209]
Currently, we return all the columns from the index in an index-only scan because the index access method API does not include the target list. We should extend the API to pass the target list not to return columns not requested.

**Comment by m-iancu** [comment]
Should be addressed by commit https://github.com/yugabyte/yugabyte-db/commit/28f61faa5a8d860795708d577aa77d4c9c4ca810.
