### ISSUE TITLE
[Docs] Add necessary packages for airgapped installation

### ISSUE THREAD

**Issue by favre49** [yugabyte/yugabyte-db#12102]
### Description

During airgapped installation, we install certain packages using the package manager. Since the cluster nodes are airgapped, they do not have access to any package repositories, and hence airgapped cluster creation fails. For now, we should provide a list of packages that should be installed either on the AMI, or available on an accessible package repository, for installation to work. Below is a list of the necessary packages, along with some extra information about when it is necessary. All of this applies to 2.13.1.

1. Chrony (if the user toggles Use TimeSync on during universe creation)
2. Python-minimal (only on Ubuntu 18.04)
3. Python-setuptools (only on Ubuntu 18.04)
4. Python-six/Python2-six (the Python2 version of Six)
5. policycoreutils-python (only on CentOS 7 and Oracle Linux 8)
6. selinux-policy (only on Oracle Linux 8, **must be on an accessible package repository**)
7. locales (only on Ubuntu)

In 2.12, there is an additional requirement:
1. ntpd (if the user toggles Use TimeSync off during universe creation)

Some of these may change over time as we clean up some of these requirements like Python 2, I'll update accordingly.

**Comment by lizayugabyte** [comment]
@favre49 The current "Install YugabyteDB Anywhere - Prerequisites" page has a section on preparing airgapped hosts:
https://docs.yugabyte.com/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/#airgapped-hosts

One of the listed requirements is "Having YugabyteDB Anywhere airgapped install package. Contact Yugabyte Support for more information." 
Are you suggesting to add the list of packages instead of recommending to contact our Support?

**Comment by favre49** [comment]
This seems to have to do with installing Anywhere on an airgapped host, but you can create clusters without network access without Anywhere itself being airgapped. This error basically happens when you create a cluster with "Assign Public IP" off, not due to any issue with the install of Anywhere.

Do you think it would make sense to add in the "Troubleshoot" section, for when cluster creation fails because of this?

**Comment by lizayugabyte** [comment]
@favre49 Okay, thanks for your input.
