### ISSUE TITLE
[YSQL] Enable `yb_db_admin` role to set `session_replication_role`

### ISSUE THREAD

**Issue by paullee-yb** [yugabyte/yugabyte-db#12120]
### Description

`SET session_replication_role TO replica;`

**Comment by jaki** [comment]
yb_db_admin is not a superuser.  Those users can already set session variables with `PGC_USERSET`.  Did you specifically want to set `session_replication_role`, which has context `PGC_SUSET`, or set other variables with `PGC_SUSET` as well?  If you allow yb_db_admin to set _any_ session variable with `PGC_SUSET`, you run the risk of privilege escalation.  One example:

```
SET ysql_upgrade_mode = on;
SET yb_non_ddl_txn_for_sys_tables_allowed = on;
UPDATE pg_authid SET rolsuper = true WHERE rolname = 'yb_db_admin';
```

**Comment by paullee-yb** [comment]
@jaki Thanks for pointing this out. Reframed the issue such that we enable `yb_db_admin` to set certain `PGC_SUSET` variables in a fine-grained manner. This way we don't introduce those security issues from having `yb_db_admin` set any `PGC_SUSET` variable.
