### ISSUE TITLE
[YSQL] Support observability of actively held and contended locks via pg_locks

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#12168]
Jira Link: [DB-502](https://yugabyte.atlassian.net/browse/DB-502)
### Description

This [google doc](https://docs.google.com/document/d/1_KzoeH7P7DftyNVasZt1Evpoznq8U-IDwuZFh8CaO0w/edit#heading=h.4p1zl0z1krwh) is the the functional specification for this feature.

The functional specification and design document will be moved to a .md file once the design is finalized.

Postgres
- https://github.com/yugabyte/yugabyte-db/issues/15736
- https://github.com/yugabyte/yugabyte-db/issues/16918
- https://github.com/yugabyte/yugabyte-db/issues/16919
- https://github.com/yugabyte/yugabyte-db/issues/15726
- https://github.com/yugabyte/yugabyte-db/issues/16696

PG Client
- https://github.com/yugabyte/yugabyte-db/issues/16914
- https://github.com/yugabyte/yugabyte-db/issues/15648
- https://github.com/yugabyte/yugabyte-db/issues/16915
- https://github.com/yugabyte/yugabyte-db/issues/16916

Transaction Coordinator
- https://github.com/yugabyte/yugabyte-db/issues/16912
- https://github.com/yugabyte/yugabyte-db/issues/16913

Tablet
- #13540
- #15444 
- https://github.com/yugabyte/yugabyte-db/issues/16911
- https://github.com/yugabyte/yugabyte-db/issues/14850
- https://github.com/yugabyte/yugabyte-db/issues/16910

[DB-502]: https://yugabyte.atlassian.net/browse/DB-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
We've tentatively agreed on the following schema:
```
Important fields
----------------
locktype           | relation, keyrange
database           | oid
relation           | oid
pid                | will use 0 for remote backends
mode               | map YSQL modes into Pg modes as much as possible. Add new ones when not possible
granted            | true/ false
fastpath           | Reuse field to indicate whether this is a single shard transaction. In Pg, this has a different meaning which doesn't concern us.
waitstart          | when did this backend start waiting for the lock
waitend            | extra field in YB that also indicates when a particular lock was acquired
ybdetails          | {
                        "node": where does the lock reside?,
                        "transactionid": transaction that holds the lock,
                        "subtransactionid": subtransaction in which lock was acquired,
                        "isexplicit": is this an explicit lock such as `FOR UPDATE` or just an implicit one like one taken by `UPDATE`,
                        "tabletid": which tablet?,
                        "ybkeyrangedetails": {
                          "hash cols": [list of hash col values],
                          "range cols": [list of range col values],
                          "is_full_pk": true/ false
                          "column_id": column id if this is a col level lock
                        }
                     }

Unimportannt fields
-------------------

page               | ****Removed****
tuple              | ****Removed****
virtualxid         | ****Removed****. (In Pg this is not the current txn's xid, it is the virtualxid of the txn that is to be locked. We don't allow locking virtual txn ids in YSQL)
Transactionid      | ****Removed****. (In Pg this is not the current txn's id, it is the id of the txn that is to be locked. We don't allow locking txn ids in YSQL)
classid            | NULL in YSQL since we don't support locking db objects
objid              | NULL in YSQL since we don't support locking db objects
objsubid           | NULL in YSQL since we don't support locking db objects
virtualtransaction | ****Removed**** we decided to preserve this in the meeting for single shard transactions, but we can reuse "transactionid" of "ybdetails" field and ignore this field
```

**Comment by rthallamko3** [comment]
Created https://github.com/yugabyte/yugabyte-db/issues/18901 to track the remaining GA items, so that we can close this GH issue. cc @robertsami . This helps with tracking on the release side.
