### ISSUE TITLE
[Docs] Update Async Replication Lag Section

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#12202]
Jira Link: [DB-694](https://yugabyte.atlassian.net/browse/DB-694)
### Description

 
The `determine_repl_latency.sh` script should be removed from the docs, since it appears it has been broken for some time now. This script is called out in the **replication lag** section of our [async replication docs](https://docs.yugabyte.com/preview/deploy/multi-dc/async-replication/#replication-lag). 

We should also add how to accomplish a similar action. Checking `/metrics` or `/prometheus-metrics` just for `async_replication_sent_lag_micros` or `async_replication_committed_lag_micros` does work, but you need to take the max of these values across each producer tserver in order to get the overall max lag

**Comment by polarweasel** [comment]
Check this [relevant Slack thread](https://yugabyte.slack.com/archives/CHC5RSY74/p1650380816965229), too.
