### ISSUE TITLE
[YSQL] Prevent `ysql_max_in_flight_ops` from being smaller than batch size

### ISSUE THREAD

**Issue by nathanhjli** [yugabyte/yugabyte-db#12204]
### Description

Currently, if we set `ysql_max_in_flight_ops` to be smaller than the value for batch size, it will crash the program. Since it doesn't make sense to set in flight ops to be smaller than batch size in the first place, add a check to prevent this from happening.

**Comment by 12csw12** [comment]
Should this issue be labeled as priority/medium?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that 79 accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority/medium 
Could you please tell us whether it should be labeled as priority/medium?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
