### ISSUE TITLE
[docs] YugabyteDB Anywhere K8s Configuration wrong kubectl commands

### ISSUE THREAD

**Issue by xinghua0123** [yugabyte/yugabyte-db#12210]
https://docs.yugabyte.com/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes/

## Issue description
The command used in doc to validate service account should be corrected.

Current Documentation:
`kubectl auth can-i 
    --as yugabyte-platform-universe-management 
    {get|create|delete|list} 
    {namespaces|poddisruptionbudgets|services|statefulsets|secrets|pods|pvc}` 

## Suggested improvement

`kubectl auth can-i --as system:serviceaccount:<namespace>:yugabyte-platform-universe-management 
{get|create|delete|list} 
    {namespaces|poddisruptionbudgets|services|statefulsets|secrets|pods|pvc}`

**Comment by polarweasel** [comment]
@lizayugabyte pls triage...
