### ISSUE TITLE
[DocDB] deleted_cols does not respect entry cotable

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#12214]
### Description

During compaction we could drop record if appropriate column was deleted.
But deleted_cols is only valid for primary_table.
So deleting column from primary_table could result in data loss in cotables.
Also deleted_cols GC does not work for cotables.

**Comment by rthallamko3** [comment]
https://github.com/yugabyte/yugabyte-db/commit/5a4826ab0531003ac49496c3bdec331490eb6c11 introduced this. @jaki , can you take a stab at the fix?

**Comment by rthallamko3** [comment]
With https://github.com/yugabyte/yugabyte-db/issues/12092 being fixed in 2.13.2 timeframe, this issue can lead to data loss. in certain cases. cc @spolitov, who reported the issue and its severity.

**Comment by rthallamko3** [comment]
@es1024  to take a look.

**Comment by es1024** [comment]
Resolved in 96e88d2
