### ISSUE TITLE
[DocDB] Fatal when upgrading from 2.6 to master

### ISSUE THREAD

**Issue by hulien22** [yugabyte/yugabyte-db#12259]
### Description

After 5ce1473 (#11816) , when upgrading from 2.6 to a master build with that commit, we hit this fatal:
```
F0425 17:04:02.023068 32027 master_main.cc:122] Not found (yb/util/env_posix.cc:1000): Couldn't list tablets in metadata directory /mnt/d1/yb-data/master/tablet-meta: /mnt/d1/yb-data/master/tablet-meta: No such file or directory (system error 2)
```

Typically this directory is created in `RpcAndWebServerBase::Init()`, but in the upgrade flow, this does not happen as the base directories already exist and we don't check if the `tablet-meta` dir is also created.

**Comment by shashwat-yb** [comment]
Issue seems to persist in case of upgrade scenarios - 2.2 -> master and 2.4 -> master as well.

**Comment by rthallamko3** [comment]
Blocker for snap of 2.13.2 from master.
