### ISSUE TITLE
[YSQL] READ COMMITTED semantics should apply to all non-DDL statements (not just INSERT, UPDATE, DELETE, and SELECT)

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#12254]
Jira Link: [DB-498](https://yugabyte.atlassian.net/browse/DB-498)
### Description

Title is self-explanatory

**Comment by m-iancu** [comment]
Fixed by [a224db2](https://github.com/yugabyte/yugabyte-db/commit/a224db2230adf39206470a43b0f06ccd06376d06).
