### ISSUE TITLE
[DocDB] [xCluster] delete_universe_replication fails to remove Producer in a mixed version configuration

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#12255]
### Description

After #10730, we ran into a XCluster customer issue where the Producer Cluster was on a new version (2.12) with this safety check but the Consumer Cluster was on an old version (2.11).  The safety check requires an override flag to be set, but the older version does not have this check.  We need to default to the old behavior if this flag is unset.  In the new version, this flag is required.  

Note that there is an existing workaround:  after the `delete_universe_replication` fails, run `yb-admin list_cdc_streams` on the Producer to find the unremoved Producer stream ID, then run `yb-admin delete_cdc_stream <stream_id> force_delete` on the Producer to finish deletion.

Error Output:

> yb-admin -master_addresses 10.150.1.62:7100 delete_universe_replication 1eane6ab-d3ab-4137-89e3-4b1c47cacd63 ignore-errors
> Encountered the following warnings while running delete_universe_replication:
>  - Cannot delete an xCluster Stream in replication. Use ‘force_delete’ to override: stream_id: “d42a6bf1e8a64161b9923adb0bc30fa0” ignore_errors: true
> Replication deleted successfully

**Comment by 12csw13** [comment]
Should this issue be labeled as priority/high?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that 79 accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority/high
Could you please tell us whether it should be labeled as priority/high?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
