### ISSUE TITLE
Docs: Ambiguity on Xcluster yb-admin commands

### ISSUE THREAD

**Issue by Anagha-Damodaran** [yugabyte/yugabyte-db#12271]
### Description

The yb-admin command for [setup_universe_replication](https://docs.yugabyte.com/preview/admin/yb-admin/#setup-universe-replication) and [alter_universe_replication](https://docs.yugabyte.com/preview/admin/yb-admin/#alter-universe-replication) it is not clear on whether to use source master address or the target master address. This reference is ambiguous to the user. 
In the examples and syntax, can we please explicitly specify if its source or target master address

**Comment by polarweasel** [comment]
Closed with https://github.com/yugabyte/yugabyte-db/commit/76fe9484526d9e4c6716fb2c6017e4851b69f042
