### ISSUE TITLE
[YSQL] statistics collection during compaction

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#12290]
Jira Link: [DB-1904](https://yugabyte.atlassian.net/browse/DB-1904)
### Description

Improve performance of statistics collection by collecting the stats during compaction.

There are few different approaches available which needs to be evaluted. Some of the options listed below.

- During compactions DocDB accumulates a table sample which can be retrieved by the PG to populate the system tables.

- DocDB computes some actual statistics and DocDB directly updates PG system tables for stats .

**Comment by tverona1** [comment]
Closing this as a dup of the following: https://github.com/yugabyte/yugabyte-db/issues/14333
