### ISSUE TITLE
Add new command: tscard 

### ISSUE THREAD

**Issue by adarshash** [YugaByte/yugabyte-db#123]
Our use case needs to find out the number of items in a time series. So it would be nice to have tscard which can return the cardinality of the live items in the time series

**Comment by kmuthukk** [comment]
Thanks @adarshash for reporting this issue!

This is something that would be indeed useful to add - namely, a TSCard <key> operation to return the cardinality of the timeseries key.

CC: @pritamdamania87 .

**Comment by pritamdamania87** [comment]
Implemented in https://github.com/YugaByte/yugabyte-db/commit/907243ab26b68eed4e0b88a01e51f302a97591c4
