### ISSUE TITLE
[DocDB] Healthcheck errors and Soft memory limit exceeded error at log

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#12302]
Jira Link: [DB-1862](https://yugabyte.atlassian.net/browse/DB-1862)
### Description

Version: 2.13.2.0-b68

Healtcheck error
`Error executing command ['ssh', 'yugabyte@172.151.31.129', '-p', '54422', '-o', 'StrictHostKeyChecking no', '-o', 'ConnectTimeout=10', '-o', 'UserKnownHostsFile /dev/null', '-o', 'LogLevel ERROR', '-i', '/opt/yugabyte/yugaware/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.pem', 'set -o pipefail; /home/yugabyte/tserver/bin/cqlsh 172.151.31.129 9042 -e "SHOW HOST"']: b'Connection error: (\'Unable to connect to any servers\', {\'172.151.31.129\': <Error from server: code=1001 [Coordinator node overloaded] message="">})\n'
`
and
```
Rejecting CQL call: Soft memory limit exceeded (at 88.08% of capacity), score: 0.98 [suppressed 135 similar messages]
```
in tserver log file

Steps:

Create 2 universes(source and target)
Run workload at source
wait for some time(5-10 min)
Run bootstrap cdc cmd
take backup of tables and restore at target universe
Then I Observed these errors.

Source Universe:
http://portal.dev.yugabyte.com/universes/2cd656a8-981f-4130-8b04-6d2642a934ef/nodes

**Comment by suranjan** [comment]
@Arjun-yb This has been fixed. Please confirm.

**Comment by Arjun-yb** [comment]
Yes @suranjan, I have not observed this issue in latest builds.
