### ISSUE TITLE
[DocDB] UBSAN issue in AlterTableWithConcurrentTxnTest.TServerLeaderChange

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#12309]
Jira Link: [DB-1704](https://yugabyte.atlassian.net/browse/DB-1704)
### Description

Error: runtime error: member call on null pointer of type 'std::__assoc_state<yb::pggate::PerformResult>'
Top stack frames:
```
    #1 0x7fb6b04f04f0 in yb::pggate::PerformFuture::Get() $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/yql/pggate/pg_perform_future.cc:40:25
    #2 0x7fb6b0569c8d in yb::pggate::PgDocOp::~PgDocOp() $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/yql/pggate/pg_doc_op.cc:212:5
    #3 0x7fb6b057a3a6 in yb::pggate::PgDocReadOp::~PgDocReadOp() $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/yql/pggate/pg_doc_op.h:413:7
```
Full log: https://gist.githubusercontent.com/mbautin/eb32b8cdcdaf43fcb2277df02573a43d/raw
UBSAN issue only: https://gist.githubusercontent.com/mbautin/a6c1b0023cdff4021646d1378d08aeab/raw

**Comment by bmatican** [comment]
Fixed in #12490
