### ISSUE TITLE
Cannot connect to yugabyte on microk8s due to pending external ip

### ISSUE THREAD

**Issue by xieu90** [yugabyte/yugabyte-db#12316]
Jira Link: [DB-1614](https://yugabyte.atlassian.net/browse/DB-1614)
### Description

Hi, 

I have problem with yugabyte service gets pending external ip.

I'm trying to install yugabyte on microk8s (i would call it ubuntu's kubernetes which doesnt use docker)

I have enabled addon for microk8s like this
`microk8s enable dns registry ingress portainer dashboard helm3 storage   `
so I use helm3 (3.5 sth, as helm required 3.4+ so i think this one should be ok)

then I ran this to install yugabyte:
```
microk8s kubectl create namespace yb-demo
microk8s helm3 install yb-demo yugabytedb/yugabyte \
--set resource.master.requests.cpu=0.5,resource.master.requests.memory=0.5Gi,\
resource.tserver.requests.cpu=0.5,resource.tserver.requests.memory=0.5Gi,\
replicas.master=1,replicas.tserver=1 --namespace yb-demo

```

checked with:
`microk8s helm3 status yb-demo -n yb-demo`
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/3052/credentials/client.config
NAME: yb-demo
LAST DEPLOYED: Fri Apr 29 13:19:58 2022
NAMESPACE: yb-demo
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get YugabyteDB Pods by running this command:
  kubectl --namespace yb-demo get pods

2. Get list of YugabyteDB services that are running:
  kubectl --namespace yb-demo get services

3. Get information about the load balancer services:
  kubectl get svc --namespace yb-demo

4. Connect to one of the tablet server:
  kubectl exec --namespace yb-demo -it yb-tserver-0 bash

5. Run YSQL shell from inside of a tablet server:
  kubectl exec --namespace yb-demo -it yb-tserver-0 -- /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.yb-demo

6. Cleanup YugabyteDB Pods
  For helm 2:
  helm delete yb-demo --purge
  For helm 3:
  helm delete yb-demo -n yb-demo
  NOTE: You need to manually delete the persistent volume
  kubectl delete pvc --namespace yb-demo -l app=yb-master
  kubectl delete pvc --namespace yb-demo -l app=yb-tserver

seems like it managed to start STATUS: deployed

using command from 4.
`microk8s kubectl exec --namespace yb-demo -it yb-tserver-0 bash`
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "yb-tserver" out of: yb-tserver, yb-cleanup
[root@yb-tserver-0 cores]# ysqlsh
ysqlsh (11.2-YB-2.13.1.0-b0)
Type "help" for help.

yugabyte=# \c
You are now connected to database "yugabyte" as user "yugabyte".
yugabyte=#

so it seems i can connect to db via command.

further checking:
`microk8s kubectl get services --namespace yb-demo`
```
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                      AGE
yb-masters           ClusterIP      None            <none>        7000/TCP,7100/TCP                                                            29m
yb-tservers          ClusterIP      None            <none>        9000/TCP,12000/TCP,11000/TCP,13000/TCP,9100/TCP,6379/TCP,9042/TCP,5433/TCP   29m
yb-master-ui         LoadBalancer   10.152.183.84   <pending>     7000:31104/TCP                                                               29m
yb-tserver-service   LoadBalancer   10.152.183.4    <pending>     6379:32692/TCP,9042:32502/TCP,5433:31801/TCP                                 29m
```

the external-ip is pending whole time. I tried to connect to localhost:5443/yugabyte  , localhost:31801/yugabyte but all failed
if I installed yugabyte localy then i could connect to it via localhost:5443/yugabyte.
in case of kubernetes I guessed that i will have to use localhost:31801/yugabyte with default username, password = yugabyte (I'm a bit unsure here)

log from yb-tserver is in attachment
[logOfTServer.txt](https://github.com/yugabyte/yugabyte-db/files/8590649/logOfTServer.txt)

the yaml for service which i think there might be hint in it.
`microk8s kubectl get service --namespace yb-demo yb-tserver-service -o yaml`
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: yb-demo
    meta.helm.sh/release-namespace: yb-demo
  creationTimestamp: "2022-04-29T11:19:59Z"
  labels:
    app: yb-tserver
    app.kubernetes.io/managed-by: Helm
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: yb-demo
  name: yb-tserver-service
  namespace: yb-demo
  resourceVersion: "18148"
  selfLink: /api/v1/namespaces/yb-demo/services/yb-tserver-service
  uid: 05d5deff-910e-4425-8a42-c99c80d935a9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.152.183.4
  clusterIPs:
  - 10.152.183.4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-yedis-port
    nodePort: 32692
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: tcp-yql-port
    nodePort: 32502
    port: 9042
    protocol: TCP
    targetPort: 9042
  - name: tcp-ysql-port
    nodePort: 31801
    port: 5433
    protocol: TCP
    targetPort: 5433
  selector:
    app: yb-tserver
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

any help is appriciated.
Best regards.

**Comment by FranckPachot** [comment]
I think microk8s has no load balancer by default. Maybe enable this one: https://microk8s.io/docs/addon-metallb

**Comment by FranckPachot** [comment]
I got it with minikube on small laptop (https://dev.to/yugabyte/k8s-on-windows-virtualbox-1cj8) but 4 gb is really small, yes

**Comment by xieu90** [comment]
I gave up on installing yugabyte on kubernetes
so now i use the local version like this https://download.yugabyte.com/#linux

now i can access it via jdbc:postgresql://urlOfMyServer:5433/yugabyte
kind of naked but it works....

if it could run on kubernetes i could somehow use igress and have a real url like yugabyte.urlOfMyServer/yugabyte, but well naked like that should still be ok for now, let's hope that i wont be hacked in future ^^

**Comment by iSignal** [comment]
It is expected to need a loadbalancer controller in the k8s cluster to be able to expose the tserver endpoint outside the k8s cluster with the default helm chart options. For microk8s, metallb is one such option as shown at  https://microk8s.io/docs/addon-metallb. 

Other alternatives like exposing a node port service are documented at https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
