### ISSUE TITLE
[DocDB][xCluster] Deleting some tables throw an error - which were part of xCluster replication

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#12319]
Jira Link: [DB-1942](https://yugabyte.atlassian.net/browse/DB-1942)
### Description

DB Version: **2.13.2.0-b68**

Deleting some tables throw below error - Table was part of xCluster replication
**YCQL**:
ServerError: Server Error. Cannot delete a table in replication.: table { table_name: "t2" namespace { name: "demo1" database_type: YQL_DATABASE_CQL } } is_index_table: false (master error 29)
drop table t2;

**YSQL**:
WARNING:  Not implemented: Cannot delete a table in replication.: table { table_id: "00004000000030008000000000004006" } is_index_table: false
But it deletes the table

**Steps**:
Create 2 universes(source and target)
Create some tables(YSQL and YCQL) at both universes
Create replication(setup_universe_replication) - use some table UUIDs
Alter replication(alter_universe_replication) - use other table UUIDs
Delete replication(delete_universe_replication) 
Try to delete all created tables

**Actual**:
Some tables get deleted and some throw errors.
Strange part is, One time I observed that tables which are part of alter replication are not getting deleted.
But in one case even table which is part of setup replication is failed to delete and threw an error

**Comment by nspiegelberg** [comment]
A current workaround is to set the GFLAG `enable_delete_truncate_xcluster_replicated_table` to 1, which overrides this check.
