### ISSUE TITLE
[CDCSDK] Java unit tests fails intermittently due to checkpoint not being initialized in the some tests

### ISSUE THREAD

**Issue by suranjan** [yugabyte/yugabyte-db#12328]
Many Java test create stream, insert/update rows and expect the record to be fetched.
Sometimes they fail as records are missing. This is due to them being garbage collected. 

The expectation is that, user should set the initial checkpoint to (0,0). Many other tests do that but looks like some of the tests have missed doing it and they fail intermittently.

**Comment by vaibhav-yb** [comment]
Closing this as the issue has been fixed by the referenced commits.
