### ISSUE TITLE
Failed to create a series of tables from ddl

### ISSUE THREAD

**Issue by intellectcubed** [YugaByte/yugabyte-db#1236]
When I try to execute a ddl script that contains a few create_table commands, yugabyte times out with the below error: 

psql:/Users/xxx/Projects/yugabyte/yuga1/scripts/yugabyte-alchemy.ddl:31: ERROR:  Timed out: Read(tablet: 089f0f94923b4683acc5297de82297da, num_ops: 1, num_attempts: 343, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 32201.846s (now: 32201.908s): Leader not ready to serve requests. (yb/consensus/consensus.cc:137): Leader not yet replicated NoOp to be ready to serve requests (error 24)
psql (10.5, server 11.2)
[yugabyte-alchemy.txt](https://github.com/YugaByte/yugabyte-db/files/3104457/yugabyte-alchemy.txt)

If I run each of the statements from the command line client individually, they work fine and tables get created.

**Comment by bmatican** [comment]
Hey @intellectcubed, thanks for reporting this! Any change you can provide a bit more context around your environment, so we can try to repro this in house? Based on the path, it looks like this was on your mac? Was yugabyte running natively on mac, or through something like docker / k8s / vagrant?

Also, if you'd be ok sharing the yb-tserver.INFO and yb-master.INFO log files, those might help get a better picture of what was happening when you hit the issue. Thanks!

**Comment by intellectcubed** [comment]
Hi,
I was running Yugabyte using Docker on my Mac.  Following your instructions from your website, I started using the command: ./yb-docker-ctl create
I do not know where I can find the yb-tserver / yb-master logs.  If you tell me where I can find them, I'll send them to you.  
To create the issue, I just connect to yugabyte using the pg command line (psql -h 127.0.0.1 -p 5433 -U postgres  --echo-queries).  From there, I load the .ddl file using the \i command.
Regards,
George
    On Monday, April 22, 2019, 3:07:35 PM EDT, Bogdan Matican <notifications@github.com> wrote:  
 
 
Hey @intellectcubed, thanks for reporting this! Any change you can provide a bit more context around your environment, so we can try to repro this in house? Based on the path, it looks like this was on your mac? Was yugabyte running natively on mac, or through something like docker / k8s / vagrant?

Also, if you'd be ok sharing the yb-tserver.INFO and yb-master.INFO log files, those might help get a better picture of what was happening when you hit the issue. Thanks!

**Comment by kmuthukk** [comment]
hi @intellectcubed - short update - we were able to repro the problem internally, and its a timing/race condition that affects replication factor (RF) of 1 setup a bit more. We have identified the issue and are working to put out a fix quickly.

**Comment by m-iancu** [comment]
Closed in f3bf3f205f573193. Should be included in next release.
