### ISSUE TITLE
[YSQL] Automatically handle read restarts in YSQL

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1237]
We should automatically retry requests that resulted in a read restart in YSQL, if we have not yet started sending a response to the client.

**Comment by ndeodhar** [comment]
From an earlier discussion:
https://docs.google.com/document/d/1SwbIKfpAhy5zWYt1bUJy89lWpb3hfb2sh68O4ygFAqY/edit

**Comment by frozenspider** [comment]
For restarts at global limit we decided to track it separately: #2634

**Comment by frozenspider** [comment]
Addressed in 4c2b84b.

All `SELECT` queries can now be restart - as long as "restart read" conflict occurs before they fetch less than 8 KiB worth of data, after which point data is physically sent to the client - thus preventing us from doing a transparent restart.

We also plan a short subsequent change which will increase the buffer size.
