### ISSUE TITLE
[ASAN Unit Test Failure] ClientStressTest.TestLookupTimeouts

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12388]
Jira Link: [DB-1709](https://yugabyte.atlassian.net/browse/DB-1709)
### Description

The unit test ClientStressTest.TestLookupTimeouts is failing with asan issues.
Failure Stack Trace- https://gist.github.com/kripasreenivasan/5c67c9f217315ed9a016e997051784e1 

CC: @spolitov src/yb/rpc/serialization.cc:271:19

**Comment by bmatican** [comment]
Same issue as #12392
