### ISSUE TITLE
master/tserver startup should not fail if the data directory already exists but is empty, or only contains the logs directory

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1238]
E.g. we might want to pre-create the logs directory upfront.

**Comment by mbautin** [comment]
If there are only some empty directories (e.g. logs), we should also consider the directory empty.

**Comment by mbautin** [comment]
Also pidfile (that could be managed by an external supervisor process) should not be considered "existing data" for the purpose of master/tserver startup.

**Comment by mbautin** [comment]
Clarification based on an offline conversation with @georgeklees.
We have this logic in `fs_manager.cc`:
```
  // It's OK if a root already exists as long as there's nothing in it.
  for (const string& root : canonicalized_all_fs_roots_) {
    if (!env_->FileExists(GetServerTypeDataPath(root, server_type_))) {
      // We'll create the directory below.
      continue;
    }
    bool is_empty;
    RETURN_NOT_OK_PREPEND(IsDirectoryEmpty(GetServerTypeDataPath(root, server_type_), &is_empty),
                          "Unable to check if FSManager root is empty");
    if (!is_empty) {
      return STATUS(AlreadyPresent, "FSManager root is not empty", root);
    }
  }
```
That allows an empty data directory. But what we really want is to be able to create e.g. the logs directory in advance and still consider the data directory to be empty in that case.
Even that might already be working as expected:
```
Status FsManager::IsDirectoryEmpty(const string& path, bool* is_empty) {
  vector<string> children;
  RETURN_NOT_OK(env_->GetChildren(path, &children));
  for (const string& child : children) {
    // Excluding logs directory from the list of things to check for.
    if (child == "." || child == ".." || child == kLogsDirName) {
      continue;
    } else {
      LOG(INFO) << "Found data " << child;
      *is_empty = false;
      return Status::OK();
    }
  }
  *is_empty = true;
  return Status::OK();
}
```

**Comment by georgeklees** [comment]
After testing this, I have found that the desired behavior - not failing if the data directory exists but is empty, not failing if the logs directory exists but is empty, and not failing if the logs directory exists with files inside -- is already present as @mbautin suggests above. @WesleyW is there any additional behavior you need, or can this issue be closed?
