### ISSUE TITLE
[ASAN Unit Test Failure] MasterReplicationTest.TestMasterClusterCreate

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12389]
Jira Link: [DB-2464](https://yugabyte.atlassian.net/browse/DB-2464)
### Description

The unit test case MasterReplicationTest.TestMasterClusterCreate is failing with asan issues-
Failure stack trace: https://gist.github.com/kripasreenivasan/a46cb8fe9672e3b6099690dc6877bcf8 

CC: @spolitov src/yb/master/catalog_entity_info.cc:749:24

**Comment by bmatican** [comment]
Passing to Anubhav for a first pass -- I don't fully get why the split manager would hit this, shouldn't we be holding references to all the objects, during the loop?

**Comment by SrivastavaAnubhav** [comment]
Closing since this appears to no longer be failing in ASAN.
