### ISSUE TITLE
[DocDB] TabletPeer::tablet() may return nullptr and we are not checking for it

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#12400]
Jira Link: [DB-2443](https://yugabyte.atlassian.net/browse/DB-2443)
### Description

@hulien22 recently reported this.

**Comment by hulien22** [comment]
Relevant segfault: https://github.com/yugabyte/yugabyte-db/issues/12399

**Comment by rthallamko3** [comment]
@suranjan , Is this issue specific to CDC or more fundamental?

**Comment by mbautin** [comment]
This is an old issue. We need to return a weak pointer from TabletPeer::tablet() and convert it to a shared_ptr by calling lock() on it, checking if its nullptr every time we do so.
