### ISSUE TITLE
[Memory leak in Unit Test] CDCSDKYsqlTest.TestNoGarbageCollectionBeforeInterval

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12428]
### Description

The Unit test CDCSDKYsqlTest.TestNoGarbageCollectionBeforeInterval has a memory leak.

Stacktrace: https://gist.github.com/kripasreenivasan/49458aa0b6b4f1a39841c9bc6c2bba1d

CC: @spolitov 
0x7fbfb0d087a8 in yb::consensus::LeaderElection::LeaderElection(yb::consensus::RaftConfigPB const&, yb::consensus::PeerProxyFactory*, yb::consensus::VoteRequestPB const&, std::unique_ptr<yb::consensus::VoteCounter, std::default_delete<yb::consensus::VoteCounter> >, yb::MonoDelta, yb::StronglyTypedBool<yb::consensus::PreElection_Tag>, yb::StronglyTypedBool<yb::consensus::TEST_SuppressVoteRequest_Tag>, std::function<void (yb::consensus::ElectionResult const&)>) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/consensus/leader_election.cc:172:35

0x7fbf9d8aad24 in yb::rpc::Proxy::Proxy(yb::rpc::ProxyContext*, yb::HostPort const&, yb::rpc::Protocol const*, yb::MonoDelta const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/proxy.cc:85:7

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
