### ISSUE TITLE
[DocDB] Improve boundary values calculation

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#12425]
Jira Link: [DB-1867](https://yugabyte.atlassian.net/browse/DB-1867)
### Description

For each record in SST file we extract independent values for range columns and hybrid time.
When for each range column and time we pick min and max values and store them to SST file.
It allows us to filter SST files when range based request is being processed.

The extracted values are stored in small_vector and allocated objects that has buffered value.

Also those values are recalculated during compaction.

We could improve the following:
1) Change interface to operate on buffers directly, to avoid allocating intermediate object.
2) Right after value is extract, we could use just slice to it. And copy it to buffer only if this value extends stored bounds.
3) When compaction does not drop delete markers, we could take boundary values from original files, and avoid recalculating them to each independent record.
4) Don't recalculate boundary values when dockey was not changed during compaction.

**Comment by kmuthukk** [comment]
Tried out the before/after on test cluster with a IOT/timeseries like schema.  Note: The change sees most benefit when the primary key (PK) has range columns not just hash partition columns. This is pretty common with compound primary keys -- where say a device_id is the HASH portion of the key and timestamp is the ASC/DESC portion of the key.

The results are impressive in terms of speedup in compaction times.. and also we do see the related benefit of the workload running with higher ops, without latency spikes and lower CPU utilization. Basically, even though compactions are a background job, the lesser strain the put on CPU the better.

**Command Run:**

`% java -jar /home/yugabyte/yb-sample-apps.jar --workload CassandraBatchTimeseries --nodes $CIP_ADDR --num_threads_write 8 --num_threads_read 1 --min_metrics_count 500 --max_metrics_count 1000 -nouuid --num_unique_keys 10000000000000 --username cassandra --password 'xyzxyz' --num_writes 10000000000000`

The test was left to run for 12+ hrs.

**Cluster Setup**: c5.xlarge (4-core), RF=3, 3-node, 500GB storage/node clusters:
`2.13.3.0 build 44 (without change)`
vs.
`2.13.3.0 build 45 (contains change)`

**Key Observations**

* Ops/sec with the change holds a much more steady line without the periodic latency spikes as before.
* The area under the "compaction time" graphs shows that compactions take much lesser time (easily 2x lower there).
* User CPU is down from about 86% to 80%. System CPU was about the same in both cases.

**BEFORE/AFTER Graphs**

**Before ops/sec**
<img width="931" alt="before_ops_12hrs" src="https://user-images.githubusercontent.com/13615376/190880830-0641ee82-d15f-4b17-a73b-fe5afb7aaf39.png">

**After ops/sec**
<img width="929" alt="after_ops_12hrs" src="https://user-images.githubusercontent.com/13615376/190880836-595d8a55-9c52-4735-99ad-371993c5a380.png">

**Before compaction time graphs**
<img width="927" alt="before_compaction_time_12hrs" src="https://user-images.githubusercontent.com/13615376/190880841-a0f04eee-47ab-45cf-8e3c-a4b726670161.png">

**After compaction time graphs**
<img width="921" alt="after_compaction_time_12hrs" src="https://user-images.githubusercontent.com/13615376/190880850-3c788c0f-4bf0-4fec-b76d-daad3399aa95.png">

**Before CPU**
<img width="426" alt="before_cpu" src="https://user-images.githubusercontent.com/13615376/190880876-8874ef65-d3eb-486b-ad03-c59ff3fdc03a.png">

**After CPU**
<img width="487" alt="after_cpu" src="https://user-images.githubusercontent.com/13615376/190880879-39825c0e-0771-4973-b620-9ae10529668b.png">
