### ISSUE TITLE
[Memory leak in unit test] XClusterAdminCliTest_Large.TestBootstrapProducerPerformance

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12427]
### Description

The unit test XClusterAdminCliTest_Large.TestBootstrapProducerPerformance has a memory leak.
Leak stacktrace- https://gist.github.com/kripasreenivasan/ebb0d6bb6e8960039c013c98f0f433ac 

CC: @d-uspenskiy 0x7f82489cc380 in yb::rpc::ProxyCache::GetProxy(yb::HostPort const&, yb::rpc::Protocol const*, yb::MonoDelta const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/proxy.cc:375:14

CC: @spolitov src/yb/rpc/proxy.cc:85:7

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
