### ISSUE TITLE
[Memory Leak in Unit Test] CDCSDKYsqlTest.TestGarbageCollectionWithSmallInterval

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12426]
### Description

The unit test TCDCSDKYsqlTest.TestGarbageCollectionWithSmallInterval has memory leaks.

Memory Leak Stacktrace: https://gist.github.com/kripasreenivasan/1b2b3c6c465408e5751c7444cd8de09e 

CC: @spolitov src/yb/rpc/proxy.cc:85:7
 0x7f5046358eea in yb::consensus::ConsensusServiceProxy::ConsensusServiceProxy(yb::rpc::ProxyCache*, yb::HostPort const&, yb::rpc::Protocol const*, yb::MonoDelta const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/src/yb/consensus/consensus.proxy.cc:236:7
 
CC: @d-uspenskiy https://github.com/yugabyte/yugabyte-db/commit/4b8fa12543ed3696cd4c750d52b333df496d7fec src/yb/rpc/proxy.cc (Dmitry Uspenskiy 2021-04-07 10:52:36 +0300 375)
0x7f83f4789380 in yb::rpc::ProxyCache::GetProxy(yb::HostPort const&, yb::rpc::Protocol const*, yb::MonoDelta const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/proxy.cc:375:14

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
