### ISSUE TITLE
[Memory Leak in Unit Test] TwoDCTestParams/TwoDCTest.TestFailedDeleteOnRestart/2

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12424]
Jira Link: [[DB-281]](https://yugabyte.atlassian.net/browse/DB-281)
### Description

The unit test TwoDCTestParams/TwoDCTest.TestFailedDeleteOnRestart/2 has memory leaks.

Memory Leak Stacktrace: https://gist.github.com/kripasreenivasan/09cef3632b0441987aff066d44dc541d 

CC: @spolitov src/yb/rpc/proxy.cc:85:7 
CC: @d-uspenskiy 4b8fa12543e src/yb/rpc/proxy.cc   (Dmitry Uspenskiy    2021-04-07 10:52:36 +0300 375)
 0x7f83f4789380 in yb::rpc::ProxyCache::GetProxy(yb::HostPort const&, yb::rpc::Protocol const*, yb::MonoDelta const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/proxy.cc:375:14

[DB-281]: https://yugabyte.atlassian.net/browse/DB-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
