### ISSUE TITLE
[Memory leak in unit test] PgMiniTest.DuplicateUniqueIndexInsertSerializable

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12435]
### Description

Memory leak observed in unit test PgMiniTest.DuplicateUniqueIndexInsertSerializable

Stacktrace- https://gist.github.com/kripasreenivasan/55528162209bd7111bd44c6bb6947447

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
