### ISSUE TITLE
[Memory leak in unit test] PgMiniTest.DuplicateInsertSerializable

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12439]
### Description

Memory leak observed in unit test PgMiniTest.DuplicateInsertSerializable
Stack trace: https://gist.github.com/kripasreenivasan/98a6f21a568712d0c4e362b34a5419da

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
