### ISSUE TITLE
[Memory leak in unit test] TwoDCTestParams/TwoDCTest.TestFailedUniverseDeletionOnRestart/3

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12430]
### Description

Memory leak observed in unit test TwoDCTestParams/TwoDCTest.TestFailedUniverseDeletionOnRestart/3
Stack trace: https://gist.github.com/kripasreenivasan/7303eb4f1f6eb6f51765e633aea84e68

CC: @spolitov 
0x7f17bb47fe81 in yb::consensus::RaftConsensus::DoStartElection(yb::consensus::LeaderElectionData const&, yb::StronglyTypedBool<yb::consensus::PreElected_Tag>) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/consensus/raft_consensus.cc:627:18

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
