### ISSUE TITLE
[Memory leak in unit test] GeoTransactionsTest.TestPreferredZone

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12433]
### Description

Memory leak observed in unit test GeoTransactionsTest.TestPreferredZone

Stack trace- https://gist.github.com/kripasreenivasan/af18b1ee1f37295701dc091d385bfd58

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
