### ISSUE TITLE
[Memory Leak in Unit Test ] XClusterAutomaticTabletSplitITest.AutomaticTabletSplitting

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12431]
### Description

Memory leak observed in unit test XClusterAutomaticTabletSplitITest.AutomaticTabletSplitting.

memory leak stacktrace- https://gist.github.com/kripasreenivasan/6db4c26e7f5f2be399570b6bccebcbb1

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
