### ISSUE TITLE
[Memory leak in Unit Test] PgPackedRowTest.SchemaChange

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12434]
### Description

Memory leak observed in PgPackedRowTest.SchemaChange

Stacktrace- https://gist.github.com/kripasreenivasan/fd221fbcae5e89c684c56bdd564b1018

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
