### ISSUE TITLE
[Memory leak in unit test] PgMiniTest.DuplicateNonUniqueIndexInsertSerializable

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12437]
### Description

Memory leak observed in unit test PgMiniTest.DuplicateNonUniqueIndexInsertSerializable

Stacktrace- https://gist.github.com/kripasreenivasan/3c8deb73a9b82e52374582c70c15d214

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
