### ISSUE TITLE
[Memory Leak in Unit Test] PgPackedRowTest.Simple

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12436]
### Description

Memory leak observed in unit test PgPackedRowTest.Simple
StackTrace: https://gist.github.com/kripasreenivasan/b075a289d867f6e2be3f0702709f9eea

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
