### ISSUE TITLE
[Memory leak in unit test] TabletSplitITest.SplitClientRequestsClean

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12438]
### Description

Memory leak in unit test: TabletSplitITest.SplitClientRequestsClean
Stack trace: https://gist.github.com/kripasreenivasan/e1ea7e630131c4053b4282269c357adc

**Comment by bmatican** [comment]
Fixed by 528c4f23e604105d2702376345161b1d39acbfa1
