### ISSUE TITLE
[Materialized Views]  Backup and Restore of materialized views created on colocated tables failing

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12442]
Jira Link: [DB-2481](https://yugabyte.atlassian.net/browse/DB-2481)
### Description

Steps:
- Create a colocated database
- Create a colocated table inside the above database
- Inserts rows into the table
- Create two materialized views on the above table
- Insert more rows into the table
- Refresh both the above materialized views
- Verify that both the materialized views have all the data in the base table
- Create a backup of the colocated database
- Drop both the materialized views
- Restore the backup created
- select * from materialized views
**Issue:** The materialized view contents are not restored as part of the restore operation. Please note that the above scenario works in the case of a non-colocated database and non-colocated table. This bug was caught by itest-system automation test case - TestMatViewWithBackupRestoreWithCL

**Comment by Karvy-yb** [comment]
Observed this failure for `2.17.0.1-b4`. Reopening the bug.

**Comment by fizaaluthra** [comment]
Backported to 2.17.0 (commit a3f4cca2a03c8b949fdef94dbf417cb31c45b631) cc @Karvy-yb
