### ISSUE TITLE
[YSQL] Unique index involving custom FUNCTION results in ERRORDATA_STACK_SIZE

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#12451]
Jira Link: [[DB-296]](https://yugabyte.atlassian.net/browse/DB-296)
### Description

When porting commit 34ff15660b4f752e3941d661c3896fd96b1571f9 from upstream, we would see:
```
+CREATE MATERIALIZED VIEW sro_index_mv AS SELECT 1 AS c;
+CREATE UNIQUE INDEX ON sro_index_mv (c) WHERE unwanted_grant_nofail(1) > 0;
+WARNING:  AbortSubTransaction while in DEFAULT state
+WARNING:  AbortSubTransaction while in ABORT state
+WARNING:  AbortSubTransaction while in ABORT state
+WARNING:  AbortSubTransaction while in ABORT state
+ERROR:  Illegal state: Set active sub transaction 2, when not transaction is running
+ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
+ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
+ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
+ERROR:  Illegal state: Rollback sub transaction 2, when not transaction is running
+PANIC:  ERRORDATA_STACK_SIZE exceeded
+server closed the connection unexpectedly
+   This probably means the server terminated abnormally
+   before or while processing the request.
+connection to server was lost
```

[DB-296]: https://yugabyte.atlassian.net/browse/DB-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
@tedyu Can you please add the Link to commit 34ff15660b4f752e3941d661c3896fd96b1571f9.  I can only assume you are referring to  commit from upstream.

Why this commit 34ff15660b4f752e3941d661c3896fd96b1571f9 is required in YB ?

**Comment by tedyu** [comment]
Commit 34ff15660b4f752e3941d661c3896fd96b1571f9 was from upstream.

**Comment by m-iancu** [comment]
@tedyu is this still an issue. Can you share a standalone, minimal repro on latest YSQL version?

**Comment by tedyu** [comment]
Can reopen when this reproduces.
