### ISSUE TITLE
Build a Node.js API using Express & Prisma

### ISSUE THREAD

**Issue by sahilpatel09** [yugabyte/yugabyte-db#12473]
### Description

I would like to make some content on the Yugabyte connection and API. Express is an awesome framework but if there is some more documentation on getting started easily to build API then it will be good. 

I almost struggled a day to get Yugabyte database connected because I did not know the way to provide path in a node js app which uses express and also an ORM. 

I would like to add some basic documentation using which anyone can get started and to build an API with express and prisma.

**Comment by BrettHoyer** [comment]
Hi Sahil, 

Here is a sample application which uses Express, Prisma and YugabyteDB.
https://www.yugabyte.com/blog/building-simple-application-yugabytedb-prisma/
https://github.com/YugabyteDB-Samples/market-orders-app-nodejs

If you're still having issues connecting an ORM to YugabyteDB, I'd be happy to help you over in our community Slack channel. https://www.yugabyte.com/community/
