### ISSUE TITLE
[YSQL] Unique indexes with INCLUDE behave abnormally

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#12470]
Jira Link: [[DB-295]](https://yugabyte.atlassian.net/browse/DB-295)
Jira Link: [DB-295](https://yugabyte.atlassian.net/browse/DB-295)

### Description

We have customer whose plan was to add several covering indexes to improve performance, but the customer has highlighted 2 issues which has resulted them in reverting using some covering indexes as the behaviour is not what they expect.

1st issue, 2 tables both with covering indexes.
Customer requires the email_address column to be unique and allow no duplicates, so customer has added a UNIQUE constraint to both tables.

"emails_email_address_key" UNIQUE CONSTRAINT, lsm (email_address HASH) INCLUDE (id, person_id
"ec_digital_mapping_email_address_include_key" UNIQUE CONSTRAINT, lsm (email_address HASH) INCLUDE (digital_profile_id, ec_person_id, card_number)

first constraint does not allow duplicates on this column, the 2nd does,.
Only difference first constraint created as part of the CREATE TABLE, on the 2nd table created as part of an ALTER TABLE.

2nd Issue
On second table all UPDATES result in
ERROR: duplicate key value violates unique constraint

Below is a test case with DDL inserts, updates etc.. to Highlight the above issues

[DB-295]: https://yugabyte.atlassian.net/browse/DB-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mheer9** [comment]
DDL

test=# CREATE TABLE emails
test-# (
test(#     id varchar(36) PRIMARY KEY,
test(#     email_address varchar(320) NOT NULL,
test(#     created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
test(#     modified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
test(#     verified_date timestamp,
test(#     person_id varchar(36) NOT NULL,
test(#     CONSTRAINT emails_email_address_key UNIQUE (email_address)
test(#             INCLUDE(id, person_id)
test(# );

CREATE TABLE
test=# 
test=# CREATE INDEX IF NOT EXISTS emails_person_id_include_idx ON emails (person_id) INCLUDE (id, email_address, verified_date, created, modified);
CREATE INDEX
test=# CREATE TABLE ec_digital_mapping( 
test(# digital_profile_id varchar(50) PRIMARY KEY, 
test(# ec_person_id varchar(50), 
test(# card_number varchar(25), 
test(# email_address varchar(320) 
test(# );

CREATE TABLE
test=# 
test=# ALTER TABLE IF EXISTS ec_digital_mapping ADD CONSTRAINT ec_digital_mapping_card_number_include_key UNIQUE (card_number) INCLUDE (digital_profile_id,ec_person_id,email_address);
ALTER TABLE
test=# 
test=# ALTER TABLE IF EXISTS ec_digital_mapping ADD CONSTRAINT ec_digital_mapping_ec_person_id_include_key UNIQUE (ec_person_id) INCLUDE (digital_profile_id,card_number,email_address);
ALTER TABLE
test=# 
test=# ALTER TABLE IF EXISTS ec_digital_mapping ADD CONSTRAINT ec_digital_mapping_email_address_include_key UNIQUE (email_address) INCLUDE (digital_profile_id,ec_person_id,card_number);
ALTER TABLE

Correctly catches the duplicate

test=# INSERT  INTO emails (id, email_address, person_id) values ('004b9ba3-c0c7-4da1-95f2-c5375dc00111', 'duplicate@email.com', '004b9ba3-c0c7-4da1-95f2-c5375dc00222');
INSERT 0 1
test=# INSERT  INTO emails (id, email_address, person_id) values ('004b9ba3-c0c7-4da1-95f2-c5375dc00112', 'duplicate@email.com', '004b9ba3-c0c7-4da1-95f2-c5375dc00222');
ERROR:  duplicate key value violates unique constraint "emails_email_address_key"

Allows a duplicate to be inserted

test=# INSERT  INTO ec_digital_mapping (digital_profile_id , ec_person_id, email_address) values ('04bde1a2-e941-4920-bd7f-dee32b71e111', '04bde1a2-e941-4920-bd7f-dee32b71e222', 'duplicate@email.com');
INSERT 0 1
test=# INSERT  INTO ec_digital_mapping (digital_profile_id , ec_person_id, email_address) values ('04bde1a2-e941-4920-bd7f-dee32b71e112', '04bde1a2-e941-4920-bd7f-dee32b71e222', 'duplicate@email.com');
INSERT 0 1
test=# select * from ec_digital_mapping where email_address ='duplicate@email.com';
          digital_profile_id          |             ec_person_id             | card_number |    email_address    
--------------------------------------+--------------------------------------+-------------+---------------------
 04bde1a2-e941-4920-bd7f-dee32b71e112 | 04bde1a2-e941-4920-bd7f-dee32b71e222 |             | duplicate@email.com
 04bde1a2-e941-4920-bd7f-dee32b71e111 | 04bde1a2-e941-4920-bd7f-dee32b71e222 |             | duplicate@email.com
(2 rows)

Prevented from updating existing rows

test=# UPDATE ec_digital_mapping SET email_address = '7fc63c4e670810b2ba75ebc83efff72f4d896d3ae9bdd07c83' WHERE  email_address = 'duplicate@email.com';
ERROR:  duplicate key value violates unique constraint "ec_digital_mapping_ec_person_id_include_key"
test=# INSERT  INTO ec_digital_mapping (digital_profile_id , ec_person_id, email_address) values ('04bde1a2-e941-4920-bd7f-dee32b71e113', '04bde1a2-e941-4920-bd7f-dee32b71e222', 'updateme@email.com');
INSERT 0 1
test=# UPDATE ec_digital_mapping SET email_address = 'updated@email.com' WHERE  email_address = 'updateme@email.com';
ERROR:  duplicate key value violates unique constraint "ec_digital_mapping_ec_person_id_include_key"
test=# UPDATE ec_digital_mapping SET email_address = 'updated@email.com' WHERE  email_address = 'updateme@email.com' and digital_profile_id = '04bde1a2-e941-4920-bd7f-dee32b71e113' and ec_person_id = '04bde1a2-e941-4920-bd7f-dee32b71e222';
ERROR:  duplicate key value violates unique constraint "ec_digital_mapping_ec_person_id_include_key"

**Comment by tylarb** [comment]
We were able to reproduce the behavior in 2.8.3 and 2.13

**Comment by frozenspider** [comment]
Simplified test case for uniqueness violation:
```pgsql
CREATE TABLE test_table( 
    uniq_col int, 
    incl_col int
);
ALTER TABLE test_table ADD CONSTRAINT test_table_uniq UNIQUE (uniq_col) INCLUDE (incl_col);
INSERT INTO test_table (uniq_col) values (123);
INSERT INTO test_table (uniq_col) values (123);
SELECT * FROM test_table;
```
```
 uniq_col | incl_col
----------+----------
      123 |
      123 |
(2 rows)
```

**Comment by frozenspider** [comment]
Simplified test case for false-positive uniqueness hit:
```pgsql
CREATE TABLE test_table( 
  uniq_col int, 
  incl_col_1 int, 
  incl_col_2 int
);
ALTER TABLE test_table ADD CONSTRAINT test_table_uniq UNIQUE (uniq_col) INCLUDE (incl_col_1, incl_col_2);

INSERT INTO test_table (uniq_col, incl_col_2) values (123, 456);
UPDATE test_table SET incl_col_2 = 789 WHERE incl_col_2 = 456;
-- ERROR:  duplicate key value violates unique constraint "test_table_uniq"
```

**Comment by tedyu** [comment]
It seems PgsqlWriteOperation::ApplyInsert() doesn't get any row back from PgsqlWriteOperation::ReadColumns() when inserting subsequent row(s) (with the covering index setup).

**Comment by frozenspider** [comment]
For the fist case (uniqueness violation), the root cause seems to be our handling of nulls in unique indexes (as we initially suspected). When we implemented #1940 we didn't think there might be index columns not participating in a key, as INCLUDE as implemented later.

**Comment by frozenspider** [comment]
Fix for the first issue is done, let's see if I can squeeze in the second one as well...

**Comment by frozenspider** [comment]
Interestingly, second case has the same root cause underneath: index update is implemented as DELETE+INSERT, where DELETE part correctly identified not null values while INSERT part did not, so DELETE didn't remove the row.
