### ISSUE TITLE
[DocDB][PERF][Regression] Observed increase in latencies between 2.13.2.0-b90 to b112.

### ISSUE THREAD

**Issue by mangesh-at-yb** [yugabyte/yugabyte-db#12486]
Jira Link: [[DB-318]](https://yugabyte.atlassian.net/browse/DB-318)
### Description

Observed increase in latencies  between 2.13.2.0-b90 to b112 but major diff we found between  2.13.2.0-b106 and 2.13.2.0-b107. Majorly we have seen increase in multiple latencies. See below screen shot for ref.

Potential cause of this looks like:
https://phabricator.dev.yugabyte.com/D14326 : Which got Fixed in b107.

Google sheet for more details: https://docs.google.com/spreadsheets/d/1bUFlFBShxg2R4gc0p_bUBPXNazFHYmeAzQ_8glRk6AE/edit#gid=1132029887

<img width="658" alt="Screenshot 2022-05-12 at 12 33 12 PM" src="https://user-images.githubusercontent.com/98325393/168011266-e7dc96ae-cdc4-4417-b8a2-c71558c81d31.png">

[DB-318]: https://yugabyte.atlassian.net/browse/DB-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
The fix made it to the 2.14 snap.
