### ISSUE TITLE
[DocDB] Add tserver-side metrics for tablet splitting

### ISSUE THREAD

**Issue by jmeehan16** [yugabyte/yugabyte-db#12482]
Jira Link: [[DB-312]](https://yugabyte.atlassian.net/browse/DB-312)
### Description

We have low visibility into tablet splitting when evaluating performance issues. This is a problem as automatic tablet splitting becomes the default. We need to add some tserver-side metrics to indicate when a split is in progress. These include:

- successful SplitTablet RPC calls (i.e. tablet is in the process of splitting)
- raft apply of split op (indicates that splits are making progress)
- post-split compactions in progress/done (this may not be necessary, as we can correlate the splits to the existing tablet metrics)

[DB-312]: https://yugabyte.atlassian.net/browse/DB-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Open JIRA for platform changes.
