### ISSUE TITLE
[DocDB][PERF][Regression] Observed increase in latencies between 2.13.1.0-b1 and b2 builds.

### ISSUE THREAD

**Issue by mangesh-at-yb** [yugabyte/yugabyte-db#12485]
Jira Link: [[DB-317]](https://yugabyte.atlassian.net/browse/DB-317)
### Description

We have seen regression between 2.13.1.0-b1 and b2, where below marked latencies has increased, looks like potential check-in causing this is: https://phabricator.dev.yugabyte.com/D13244

Google sheet URL for detail comparison: https://docs.google.com/spreadsheets/d/1uVZwzSOc1choTuFL9hBQBB0LxY7wuvYuXxqkhR8mXok/edit#gid=135024746

<img width="618" alt="Screenshot 2022-05-12 at 12 25 24 PM" src="https://user-images.githubusercontent.com/98325393/168009981-c3a655ca-c2cf-4542-bcd4-db955925a920.png">

[DB-317]: https://yugabyte.atlassian.net/browse/DB-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
This was a regression in the 2.13.0 branch, that was fixed immediately.

**Comment by sharkberto** [comment]
@mangesh-at-yb Is this issue still needing a fix?

**Comment by rthallamko3** [comment]
@mangesh-at-yb , Can you clarify if the updates to the TPCC code was enough to resolve these?

**Comment by rthallamko3** [comment]
@hbhanawat , Do you think the updates to our TPCC code was enough to overcome this? Do we need this issue open?
