### ISSUE TITLE
[CDCSDK] Inconsistency in cdc_state table after dropping the table with CDCSDK enabled

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#12497]
**Steps to reproduce:**
1. Create table using ysqlsh: `CREATE TABLE test (id INT PRIMARY KEY, name TEXT);`
2. Create stream: `./yb-admin --master_addresses <master-addresses> create_change_data_stream ysql.yugabyte`
3. Connect to ycqlsh: `SELECT * FROM system.cdc_state;` If there are no entries, start debezium connector or  java console client to fill records in here.
4. `DROP TABLE test;`
5. ycqlsh: `SELECT * FROM system.cdc_state;` There will still be entries.
6. Delete the stream: `./yb-admin --master_addresses <master-addresses> delete_change_data_stream stream_id`
7. Got this error after executing step 6:

```
Error deleting stream: Did not find all requested CDC streams. Missing streams [3e6a5daaee0141aca89b83b422dbbfdd]. Request: stream_id: “3e6a5daaee0141aca89b83b422dbbfdd”: OBJECT_NOT_FOUND
Error running delete_change_data_stream: Not found (yb/master/catalog_manager_ent.cc:2807): Unable to delete CDC database stream id 3e6a5daaee0141aca89b83b422dbbfdd: Did not find all requested CDC streams. Missing streams: [3e6a5daaee0141aca89b83b422dbbfdd]. Request: stream_id: "3e6a5daaee0141aca89b83b422dbbfdd": OBJECT_NOT_FOUND (master error 3)
```

**Comment by sureshdash2022-yb** [comment]
This is fixed
