### ISSUE TITLE
[docs] Isolation Levels

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#12491]
https://docs.yugabyte.com/preview/explore/transactions/isolation-levels/

## Issue description

The [documentation](https://docs.yugabyte.com/preview/explore/transactions/isolation-levels/#read-committed-isolation) about READ  COMMITTED is not clear for users, according to questions, and was also my own experience when I tried it.
- the $ note in the matrix is too small to be visible
- mention of gflag: In don't think users really know what we mean by gflag. They are called "configuration flags" in the yb-tserver documentations. We should not expect users to know gflags (or GUC) acronyms in any doc.
- It is really confusing to understand what is set at cluster level (what we call gflags) and what is set at PostgreSQL aka YSQL level (what psottgres calls GUC ) . And there are two GUC about isolation levels as well, where read committed is the default.
the topic of isolation level in SQL databases is already too complex for many users. We need to make it simple

So, from a user point of view, when they look for READ COMMITTED, we are saying "it is the default but it is not the default" and the subtle difference is made by small lines with esoteric acronyms :joy:

## Suggested resolution

I understand the complexity given the layered architecture + compatibility with postgres + compatibility with our previous versions... but can we add a kind of TL;DR or top like: "to avoid serializable errors, i.e to run applications with no retry logic, you need to keep the default 'read committed' for the YSQL (PostgreSQL) default_transaction_isolation, and set the cluster level (all tservers) --yb_enable_read_committed_isolation flag to true which is called GFlag in YB Anywhere GUI

**Comment by m-iancu** [comment]
cc @pkj415 @polarweasel jfyi^
