### ISSUE TITLE
[YSQL] Unable to create index while creating a cluster with serializable isolation levels.

### ISSUE THREAD

**Issue by ramsrivatsa** [yugabyte/yugabyte-db#12517]
Jira Link: [[DB-360]](https://yugabyte.atlassian.net/browse/DB-360)
### Description

Create index fails with this error message on the latest master when a cluster is spawned with SERIALIZABLE isolation levels. 

Consider creating a local cluster with the following command. 
`./bin/yb-ctl create --tserver_flags "ysql_default_transaction_isolation=serializable" && ./bin/ysqlsh`

When we try to create an index on a table, we get the following error. 
```
yugabyte=# create table edges1( id1 bigint, id2 bigint, type smallint, timestamp bigint, value text, primary key (id1 , id2 , type ));
CREATE TABLE
yugabyte=# create index on edges1(id1, id2, type);
ERROR:  Aborted: ERROR:  Query error: Backfill request should already be using explicit read times.
```

This test fails more recently on master and 2.12, but is known to have passed on the following commit `17c0fa638ac7fc1da8cbac9905663ca9deb0630c`.  Note: This error does not originate with the commit mentioned. We just were trying to test an older commit and `17c0fa638ac7fc1da8cbac9905663ca9deb0630c` seem not to create this issue while 2.12 and the current master has this issue. 

[DB-360]: https://yugabyte.atlassian.net/browse/DB-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
Tried the test case mentioned in summary in the  latest preview build and it passed.

```
yugabyte=# select version();

        version

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
------------------------
 PostgreSQL 11.2-YB-2.19.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.7 (/opt/yb-build/llvm/y
b-llvm-v15.0.7-yb-1-1680596282-6b9d30d8-centos7-x86_64-build/src/llvm-project/clang 6b9d30d80f5cebc66c9fa46013
d18f125ea8ec0e), 64-bit
(1 row)

```
