### ISSUE TITLE
[YSQL] ERROR: Query error: Expected first value type to be primitive or GroupEnd, got kLowest in 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by APaape** [yugabyte/yugabyte-db#12543]
Jira Link: [[DB-412]](https://yugabyte.atlassian.net/browse/DB-412)
### Description

I try to migrate an existing Ruby on Rails application from Postgresql to Yugabyte. On the first glance it looked like this could be a drop in replacement, but I run into errors like the one above. I nailed it down to a SQL query. Maybe it is an overcomplicated way to check for a specific authorisation in the Rails application but I think that is not important here. I could reproduce the error with the SQL query outside of the Rails application using the psql/ysqlsh shell. The following query is running on Postgresql fine (I tested it with version 14.2 and 11.2) but I get the error on Yugabyte (11.2-YB-2.13.1.0-b0).
```
SELECT 1 AS one
FROM "authorisations"
INNER JOIN "groups" ON "authorisations"."group_id" = "groups"."id"
INNER JOIN "memberships" ON "groups"."id" = "memberships"."group_id"
WHERE "memberships"."user_id" = '9c7a6503-e013-42bc-87f7-9a18b0193893'
  AND "authorisations"."cluster_id" = '09a4684b-12c4-4f2b-99f5-1bc51d156cd6'
LIMIT 1;
```
I get the following error:
```
ERROR: Query error: Expected first value type to be primitive or GroupEnd, got kLowest in 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

I attached a dump of a test database “debug1” with the tables, indexes and test data to reproduce the error with the  exact select statement from above. 
[yb_debug1.sql.zip](https://github.com/yugabyte/yugabyte-db/files/8716089/yb_debug1.sql.zip)

[DB-412]: https://yugabyte.atlassian.net/browse/DB-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Was able to reproduce on 2.13.1.0

**Comment by APaape** [comment]
I wasn't able to reproduce it with 2.14.0.0-b0 or 2.15.0.1-b0 anymore. It might be already solved by some other task. Instead of the error I got the expected result now. Thanks!

**Comment by sushantrmishra** [comment]
Closed as no longer reproduces.
