### ISSUE TITLE
Enhance COPY .. FROM to accept an S3 URL just like it accepts a file path

### ISSUE THREAD

**Issue by ubendre** [yugabyte/yugabyte-db#12544]
Jira Link: [[DB-415]](https://yugabyte.atlassian.net/browse/DB-415)
### Description

Once https://github.com/yugabyte/yugabyte-db/issues/11453 is done, I guess we could point to any large csv/text file from any node, and initiate the COPY FROM which will distribute the workload internally. It would be great if instead of a file, we can supply an S3 location directly. 

[DB-415]: https://yugabyte.atlassian.net/browse/DB-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
This can still be done with some command line magic such as https://stackoverflow.com/questions/41696675/how-to-copy-a-csv-file-from-a-url-to-postgresql

**Comment by sushantrmishra** [comment]
We have launched schema and data migration tool [YugabyteDB Voyager](https://docs.yugabyte.com/preview/migrate/)

Support for data import  from S3 is on roadmap for `YugabyteDB Voyager` https://github.com/yugabyte/yb-voyager/issues/171
