### ISSUE TITLE
[Ossexp] Tracking issue for Yugabyted UI Work

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#12560]
### Description

As part of the OSS Database experience Project, this git issue lists the tasks required for implementinging a new UI for Yugabyted.

# Phase 1 - Yugabyted UI [ In-Progress ]

| Status | Tasks         | Github Issue |
| :-----: | ---------- | ------------- |
|   ✅  | Research on tech stack | |
|   ✅  | create a skeleton project using Yugabyte Cloud codebase | | 
|   ✅  | create go API project for implementing REST APIs for yugabyted UI | | 
| ✅  | Getting Started Page | |
|  ✅  | Overview tab | |
|  ✅  | Nodes tab | |
|   ✅ | Tables tab |  |
|  ✅  | Performace tab |  |
|  ✅ | Alerts Page | |
|  | Admin Page | |

# phase 2 - Improve capabilities of Yugabyted UI

| Status | UI tab | Tasks         | Github Issue |
| :-----: | ----- |  ---------- | ------------- | 
| ✅  | overview | Disk usage reporting similar to yb-anywhere on the overview page | |
| ✅ | overview | Cluster load balance information | |
| ✅ | overview | Health check equivalent of the yb-anywhere | |
| | overview | Nodes rendering on the global map | |
|✅  | overview | DB version on the overview page next to Cluster heading (preview/stable) |
| ✅ | overview | Tasks summary - current active tasks ( should navigate to activity tab) | |
|✅  | tables | Display the total number of tables for YSQL and YCQL on the tables page | |
|✅  | tables | a) Introduce a summary view for each table <br/> b) For each table we should display the tablet information, number of tablets and corresponding tablet leader and followers <br/> c) tablet placement information | |
| ✅ | Nodes | Nodes overview page should have the cloud information, DB release version | |
| ✅ | Nodes | a) Add a new summary view for a node when clicked on the node name <br/> b) Summary view should have details of node health, last updated, build version, logs <br/> c) Summary view should have details of the total number of tablets, system tablets, and user tablets | |
| | Nodes | Tserver clock information | |
| ✅ | Nodes | Nodes page should have a section for tablet-peer by availability zone cloud information | |
| ✅ | Nodes | Leaderless Tablets and under replicated tablets information | |
|✅  | Performance | support Perf advisor by seamlessly creating and migrating schema/data on a yb-managed cluster | | 
| | Admin | User tab - for the current set of users in YugabyteDB Cluster | |
| ✅ | Jobs (new) | Activity tab - Display the set of active tasks, previously run tasks | |

**Comment by sobhardwaj** [comment]
Hi ui made up with react js ?? In this repo

**Comment by nchandrappa** [comment]
Initial MVP of the Yugabyted-ui has landed in the main `yugabyte-db` repo. Refer github issue #12896

**Comment by nchandrappa** [comment]
The majority of the UI features mentioned in this EPIC will be available with YugabyteDB `2.19.2` preview release and will be available in the stable `2.20.0` release.

**Comment by nchandrappa** [comment]
All the features in this issue are GAed. We have de-prioritized the admin page, which will be taken up at a later date.
