### ISSUE TITLE
Test : [DocDB] TabletSplitITest.SplitClientRequests* test failures

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12578]
Jira Link: [[DB-449]](https://yugabyte.atlassian.net/browse/DB-449)
### Description

TabletSplitITest.SplitClientRequestsClean
TabletSplitITest.SplitClientRequestsIdsDepth2

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-449]: https://yugabyte.atlassian.net/browse/DB-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
https://detective.dev.yugabyte.com/stability/test?branch=master&class=TabletSplitITest&name=SplitClientRequestsClean
```


09/16/2022 14:48 | alma8-master-gcc11-fastdebug/766/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/766/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsClean.log    Unrecognized error type. Please see the error log for more information.
-- | -- | -- | --
09/15/2022 21:18 | alma8-master-clang12-debug-aarch64/829/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-debug-aarch64/829/artifact/build/debug-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsClean.log  ../../src/yb/integration-tests/tablet-split-itest.cc:702 Expected: peers.size() Which is: 3 To be equal to: 1 << i Which is: 4
09/09/2022 20:18 | centos-master-clang13-debug/281/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang13-debug/281/artifact/build/debug-clang13-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsClean.log  ../../src/yb/integration-tests/tablet-split-itest.cc:701 Expected: peers.size() Which is: 1 To be equal to: 1 << i Which is: 2

09/16/2022 14:48	[alma8-master-gcc11-fastdebug/766/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/766/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/766/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsClean.log



Unrecognized error type. Please see the error log for more information.

09/15/2022 21:18	[alma8-master-clang12-debug-aarch64/829/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-debug-aarch64/829/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-debug-aarch64/829/artifact/build/debug-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsClean.log

../../src/yb/integration-tests/tablet-split-itest.cc:702
Expected: peers.size()
Which is: 3
To be equal to: 1 << i
Which is: 4
09/09/2022 20:18	[centos-master-clang13-debug/281/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang13-debug/281/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang13-debug/281/artifact/build/debug-clang13-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsClean.log

../../src/yb/integration-tests/tablet-split-itest.cc:701
Expected: peers.size()
Which is: 1
To be equal to: 1 << i
Which is: 2
```

**Comment by rthallamko3** [comment]
https://detective.dev.yugabyte.com/stability/test?branch=master&class=TabletSplitITest&name=SplitClientRequestsIdsDepth2

`

09/16/2022 07:18 | centos-master-clang12-tsan/948/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/948/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsIdsDepth2.log    Unrecognized error type. Please see the error log for more information.
-- | -- | -- | --
09/15/2022 18:03 | centos-master-clang12-tsan/941/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/941/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsIdsDepth2.log    Unrecognized error type. Please see the error log for more information.
09/14/2022 14:03 | centos-master-clang12-tsan/930/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/930/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsIdsDepth2.log    Unrecognized error type. Please see the error log for more information.

<br class="Apple-interchange-newline">09/16/2022 07:18	[centos-master-clang12-tsan/948/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/948/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/948/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsIdsDepth2.log



Unrecognized error type. Please see the error log for more information.

09/15/2022 18:03	[centos-master-clang12-tsan/941/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/941/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/941/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsIdsDepth2.log



Unrecognized error type. Please see the error log for more information.

09/14/2022 14:03	[centos-master-clang12-tsan/930/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/930/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/930/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/TabletSplitITest_SplitClientRequestsIdsDepth2.log



Unrecognized error type. Please see the error log for more information.`
