### ISSUE TITLE
[DocDB] AutomaticTabletSplit*ITest.* test failures

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12573]
Jira Link: [[DB-444]](https://yugabyte.atlassian.net/browse/DB-444)
### Description

Tests failing in more than 10% of commits:

- AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted
- AutomaticTabletSplitITest.AutomaticTabletSplitting
- AutomaticTabletSplitITest.AutomaticTabletSplittingMovesToNextPhase
- AutomaticTabletSplitITest.AutomaticTabletSplittingWaitsForAllPeersCompacted
- AutomaticTabletSplitITest.DisableTabletSplitting
- AutomaticTabletSplitITest.IsTabletSplittingComplete
- AutomaticTabletSplitITest.PrioritizeLargeTablets
- AutomaticTabletSplitITest.TabletSplitHasClusterReplicationInfo

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-444]: https://yugabyte.atlassian.net/browse/DB-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SrivastavaAnubhav** [comment]
As of today (June 21st, 2022) the updated list from the same link is:
- AutomaticTabletSplitITest.AutomaticTabletSplitting
- AutomaticTabletSplitITest.AutomaticTabletSplittingMovesToNextPhase
- AutomaticTabletSplitITest.TabletSplitHasClusterReplicationInfo
- AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted
- AutomaticTabletSplitITest.PrioritizeLargeTablets
- AutomaticTabletSplitITest.IsTabletSplittingComplete

**Comment by SrivastavaAnubhav** [comment]
Fixed all but PrioritizeLargeTablets (tracked by #13102) and AutomaticTabletSplittingMovesToNextPhase (tracked by #13446).
