### ISSUE TITLE
[DocDB] CqlTabletSplitTest.* test failures

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12575]
Jira Link: [[DB-446]](https://yugabyte.atlassian.net/browse/DB-446)
### Description

Tests failing in more than 10% of commits:
CqlTabletSplitTest.BatchTimeseries
CqlTabletSplitTest.SecondaryIndex
CqlTabletSplitTest.SecondaryIndexWithDrop

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-446]: https://yugabyte.atlassian.net/browse/DB-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
reactivating for backport to 2.14 branch.
