### ISSUE TITLE
[DocDB] YbAdminSnapshotScheduleTest.RestoreAfterSplit test failures.

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12583]
Jira Link: [[DB-454]](https://yugabyte.atlassian.net/browse/DB-454)
### Description

Need to fix.

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-454]: https://yugabyte.atlassian.net/browse/DB-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
No failures since https://detective.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=YbAdminSnapshotScheduleTest&fail_tag=all&name=RestoreAfterSplit&platform=all
