### ISSUE TITLE
[DocDB] TabletSplitITest/TabletSplitITestWithIsolationLevel.SplitSingleTablet/*

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12581]
Jira Link: [[DB-452]](https://yugabyte.atlassian.net/browse/DB-452)
### Description

Need to fix.

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-452]: https://yugabyte.atlassian.net/browse/DB-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
No longer fails as per detective report - 
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TabletSplitITestWithIsolationLevel&fail_tag=all&name=SplitSingleTablet&platform=linux

**Comment by rthallamko3** [comment]
https://detective.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TabletSplitITest%2FTabletSplitITestWithIsolationLevel&fail_tag=all&name=SplitSingleTablet%2FREAD_COMMITTED&platform=all

**Comment by rthallamko3** [comment]
Doesn't seem to be an issue since 10/6.

**Comment by arybochkin** [comment]
This is a test-only issue and happening because cluster shutdown is happening faster then last bunch of WRITE ops got replicated, and after restart the test checks replicas data immediately without waiting for WRITE ops replication is completed.
