### ISSUE TITLE
[docdb] Slow DROP TABLE due to waiting on the background thread to finally mark it as DELETED

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1259]
Both on the YCQL and YSQL side, dropping tables involves ensuring all TS drop their respective data and destroy their raft groups. We've often seen operations here take multiple seconds, which does not seem too reasonable.

**Comment by sriki77** [comment]
I have system test that creates and drop tables dynamically; the slowness is a problem which kills the connection midway causing the tests to fail due to connection loss.
