### ISSUE TITLE
[ysql] [Bulk load] Index backfilling fails with timedout error after 3600secs.

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12625]
Jira Link: [DB-489](https://yugabyte.atlassian.net/browse/DB-489)
### Description

Data was loaded from a 200GB csv data in a table with primary key, the tablesize(from platform UI tables tab) was ~695GB. When we try to create an index on this table, we get a timedout error after 3600 seconds. This is observed in transactional mode. (yb_disable_transactional_writes=false)
The was observed on 8-core 3node universe.
YB version : 2.13.2.0-b32

Error message : 
```
CREATE INDEX idx1 on orders(col1);
ERROR:  Timed out: BackfillIndex RPC (request call id 306682) to 172.151.34.124:9100 timed out after 3600.000s
Time: 3602379.812 ms (01:00:02.380)
```

Script : 
```
\timing
SET ysql_max_in_flight_ops=20000;
SET ysql_session_max_batch_size=2000;

drop table if exists orders;
select (pg_sleep(30));
CREATE TABLE orders (id INT primary key, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, col5 TEXT, col6 TEXT, col7 TEXT, col8 TEXT, col9 TEXT, col10 TEXT);
select (pg_sleep(30));
\copy orders from '/home/ubuntu/csv_data/orders_10_650m.csv' with (FORMAT CSV, HEADER, ROWS_PER_TRANSACTION 20000);
select (pg_sleep(30));
CREATE INDEX idx1 on orders(col1);  _(<= this fails)_
select (pg_sleep(300));
CREATE INDEX idx2 on orders(col2);
```

Test environment : 
```
GFlags:
Tablet-spliting enabled 
max_packed_row_columns=1000
Session setting :
set ysql_max_in_flight_ops=20000;
set ysql_session_max_batch_size = 2000;

ROWS_PER_TRANSACTION 20000 (COPY command)
```

**Comment by sushantrmishra** [comment]
We will increase the backfill timeout to one week = 604800

**Comment by rthallamko3** [comment]
Need to backport to 2.15.0 branch too. @jasonyb

**Comment by sushantrmishra** [comment]
We refrained from increasing the default to 7 days but rather increased the default to 1 day.
