### ISSUE TITLE
[DocDB] Ensure we are using high-resolution timers in Linux

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#12635]
Jira Link: [DB-515](https://yugabyte.atlassian.net/browse/DB-515)
### Description

This might be relevant for consistent performance (latencies) across x86_64 and aarch64

/proc/timer_list on CentOS 7 x86_64 (GCP):
https://gist.githubusercontent.com/mbautin/5e6efd3afcafb51ca78a140b06b100fe/raw

/proc/timer_list on Ubuntu 20.04 aarch64 (AWS):
https://gist.githubusercontent.com/mbautin/c18f1fc1a5eecab46c2f554d829cdbd1/raw

**Comment by es1024** [comment]
Both moving to CLOCK_MONOTONIC and using an aarch64 kernel with CONFIG_HZ_1000/CONFIG_HZ=1000 separately result in an ~5% slowdown and increase in latencies, so closing this.
