### ISSUE TITLE
[DocDB] YSQL: Update PGTableDesc table cache when partition list version is outdated

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12631]
Jira Link: [DB-510](https://yugabyte.atlassian.net/browse/DB-510)
### Description

`PgTableDesc::GetPartitions()` is used by YSQL layer for preparing `YBOperation`s to send to the tserver.
Assume we initially had 1 tablet and it has been split into 8 tablets (after few split operations). When we are creating batch of `YBOperations`, one per partition, it will still get 1 partition from `PgTableDesc::GetPartitions()` and therefore we won’t get any concurrency during such statements execution until we restart PGConnection or table cache is invalidated.

We should add table cache invalidation on table partition list version update as well in addition to table schema version update.

This hurts query performance as the read requests might not parallelize to the tablets, once tablets split under the hood without a notification.

**Comment by arybochkin** [comment]
small update: @d-uspenskiy has no plans to update this part within his work for caches update.
possible solutions: to pass partition list version in a response for Write/Read ops back to pggate.
