### ISSUE TITLE
[YSQL] Bulk inserts to speed up DDL

### ISSUE THREAD

**Issue by robertpang** [yugabyte/yugabyte-db#1264]
As observed during initdb, each DDL operation incurs many inserts into the `pg_attribute` and `pg_depend` system catalog tables. We should consider bulk inserts into those 2 tables to speed up DDL

**Comment by robertpang** [comment]
A hurdle we face is that there are indexes on both `pg_attribute` and `pg_depend`. To insert index entries as each row is inserted to the base tables, we need the `ybctid` (the row id) of the row, which is normally returned from the storage layer (DocDB) after the row is inserted. If the base rows are buffered, the `ybctid` are not immediately available and the index entries cannot be prepared without significant rework.

In fact, the `ybctid` is a serialized form of the row's primary key but YSQL proxy does not have the knowledge of the format. A proper way to address this will be to send the `ybctid` in the form of the logical primary key, i.e. the individual primary key column values in `QLValue`.

**Comment by robertpang** [comment]
The above will also useful to bulk insert in the `COPY` statement.

**Comment by ndeodhar** [comment]
Depends on https://github.com/YugaByte/yugabyte-db/issues/1388

**Comment by m-iancu** [comment]
This should now be done as part or as follow-up of commit https://github.com/yugabyte/yugabyte-db/commit/8ff5c04b01acfae2dc178c2e951665b8b64bf417.
