### ISSUE TITLE
[YSQL] CLUSTER not supported yet

### ISSUE THREAD

**Issue by paullee-yb** [yugabyte/yugabyte-db#12656]
Jira Link: [DB-549](https://yugabyte.atlassian.net/browse/DB-549)
### Description

```
> CREATE INDEX sro_cluster_idx ON sro_tab ((sro_ifun(a) + sro_ifun(0)));
> CLUSTER sro_tab USING sro_cluster_idx;
ERROR:  CLUSTER not supported yet
```

**Comment by sushantrmishra** [comment]
In YB the rows are logically ordered   by Index already, so [cluster](https://www.postgresql.org/docs/current/sql-cluster.html) support is not required.
