### ISSUE TITLE
[OSSexp] Test the multi-node upgrade of the YugabyteDB cluster to enable multi-zone feature

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#12675]
### Description

We will need to test the upgrade scenario to enable the multi-zone feature, 

1. Start a 3-node YugabyteDB cluster using `2.13.2.0` release, the release which doesn't have multi-zone capabilities
2. Go to each node, download the new release `2.13.3.0` which has the multi-zone feature. 
3. Stop the yugabyted node using `yugabyted stop`
4. Start the node from the new release using `yugabyted start` giving the correction flags for `cloud_location` and `fault_tolerance`.

**Comment by gargsans-yb** [comment]
Testing :

- Downloaded and start cluster on 3 VMs using yugabyte-2.13.2.0 from https://download.yugabyte.com/#linux
```
./yugabyted start --listen=10.150.0.157
./yugabyted start --listen=10.150.3.223 --join=10.150.0.157
./yugabyted start --listen=10.150.2.159 --join=10.150.0.157
```
- Copied code of yugabyte-2.13.3.0 from master to yugabyted file.
- Stopped cluster using yugabyted stop.
- Started with cloud information - 
```
./yugabyted start --advertise_address=10.150.0.157 --cloud_location=gcp.us-west1.us-west1-b
./yugabyted start --advertise_address=10.150.3.223 --join=10.150.0.157 --cloud_location=gcp.us-west1.us-west1-a
./yugabyted start --advertise_address=10.150.2.159 --join=10.150.0.157 --cloud_location=gcp.us-west1.us-west1-c
```
- Configured cluster using ./yugabyted configure.


Output :

Multizone setup successfully.

**Comment by nchandrappa** [comment]
The Upgrade scenario has been tested.
