### ISSUE TITLE
[DocDB] Log spew on rocksdb init

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#12688]
Jira Link: [DB-581](https://yugabyte.atlassian.net/browse/DB-581)
### Description

As part of https://phabricator.dev.yugabyte.com/D10932 / c9aee058dde24a08d669a98e996b0f8368c6cd86, a probably unintended side effect is that we are no longer actually updating the default values of some auto-tune flags, such as compaction threads. This leads to some log spew on rocksdb init (eg: tablet creation / truncate / etc)

**Comment by rthallamko3** [comment]
@yusong-yan , Feel free to consult @robertsami and pick up this issue.
