### ISSUE TITLE
how does this compare to kappa-db?

### ISSUE THREAD

**Issue by whatsdis** [YugaByte/yugabyte-db#1269]
is this a similar concept like https://github.com/mafintosh/hyperdb? can multiple peers run a "private" database amongst themselves?

**Comment by kmuthukk** [comment]
hi @whatsdis 

Not too familiar off-hand with Kappa-DB/HyperDB. HyperDB seems to be a peer-to-peer KV store with somewhat lower level APIs.  YugaByte DB is a high-performance, distributed SQL database, with a underlying core/design inspired by Google Spanner.

Please see https://docs.yugabyte.com/latest/introduction/ for an overview of YugaByte DB, the APIs supported and also some  [comparisons](https://docs.yugabyte.com/latest/comparisons/) with other DBs.

regards
Kannan
