### ISSUE TITLE
Online upgrades

### ISSUE THREAD

**Issue by ddorian** [YugaByte/yugabyte-db#127]
Are they supported ? Cause I don't see anything in the docs. Or they'll be after 1.0 ?

**Comment by kmuthukk** [comment]
@ddorian : The script makes certain assumptions about where master/tserver software is installed on the node; and the master & tserver being deployed as services etc. It uses service start/stop commands and so on; so ybcontrol.py is meant to be just a sample.

But the basic idea is you would something along the lines of:
```
for each master
  stop master
  push the new software; run post_install.sh
  restart the master; 
  sleep for some time
```

and then something similar for each TServer.

**Comment by ddorian** [comment]
Thanks, makes sense.
