### ISSUE TITLE
[DocDB] [TPCC] TPCC 2700WH data loading failed as one of the tserver stopped due to disk full error

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12722]
Jira Link: [DB-611](https://yugabyte.atlassian.net/browse/DB-611)
### Description

YB version : 2.13.2.0-b18
YB universe : 3 node RF3 , AZ1 using c5d.4xlarge instances each consisting 1 x 400GB volume disk
Tablet splitting disabled.

During the TPCC 2700WH load phase, one of the tserver stopped as disk on that node went full, while there was about 100GB disk on other nodes.
Universe link : http://10.9.131.126/universes/5e8b2d13-32d8-4996-8a1a-020fc902e525

**Comment by mikhpolitov** [comment]
It is expected behavior for 3 tablets per table.

**Comment by rthallamko3** [comment]
@sonalsagarwal , Closing this for now. Let us know if this repros consistently.
