### ISSUE TITLE
[YSQL] Show transaction priority via a session variable

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#12731]
Jira Link: [DB-619](https://yugabyte.atlassian.net/browse/DB-619)
### Description

Currently we do not have a user facing function or session variable to show the priority for the current running transaction. This will be shown as a number between 0.0 and 1.0 similar to the two gucs we already have for setting a range for the priorities - yb_transaction_priority_lower_bound and yb_transaction_priority_upper_bound

**Comment by sushantrmishra** [comment]
closing as this is fixed by https://github.com/yugabyte/yugabyte-db/issues/13762 .
