### ISSUE TITLE
[YSQL] pg_hint_plan doesn't clean up its global hint state

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#12741]
Jira Link: [DB-627](https://yugabyte.atlassian.net/browse/DB-627)
### Description

pg_hint_plan doesn't clean up its global hint state variable `current_hint_retrieved` after execution. In effect, if a connection were to receive a hintless query and set `current_hint_retrieved` to `true`, any further queries would not have their hints parsed unless they were to reset this variable. ~~Non-utility queries using the extended query protocol only reset this in the Parse stage~~. (CORRECTION: Non-utility queries that are using custom plans with the extended query protocol only reset this in the parse stage). Therefore, any previous parsed query that tried to bind and replan when `current_hint_retrieved` has been set to `true` will not have their hints parsed, effectively ignoring the hint.

**Comment by kmuthukk** [comment]
We should provide the patch we are working on upstream as well - i.e. to the maintainers of pg_hint extenion.

**Comment by michaelpq** [comment]
> We should provide the patch we are working on upstream as well - i.e. to the maintainers of pg_hint extenion.

The patch has been received. It would have been nicer to see a pull request, but thanks for the report. I am going to take care of it in all the branches where this needs to be taken care of, mentioning what you have done here.
