### ISSUE TITLE
[CDCSDK] Remove connector dependency on one node while validating the JDBC connection

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#12751]
Jira Link: [DB-6894](https://yugabyte.atlassian.net/browse/DB-6894)
Currently, the Debezium Connector for YugabyteDB takes in a `database.hostname` which is the IP of a node where the connector performs a one time operation to validate the user authentication.

This can create a problem as the current setup leads to a hard dependency on the provided node i.e. in case the connector restarts and the DB node crashes at that time then the connector will not be able to validate the connection and as a result of this, it will not proceed forward and fail at the validation step itself.

[DB-6894]: https://yugabyte.atlassian.net/browse/DB-6894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mheer9** [comment]
Hi @vaibhav-yb 

Have you got an ETA on this, as customer has asked.
