### ISSUE TITLE
[YSQL] Occasionally getting "Not found: Missing metadata for transaction" error

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#1276]
Setup: RF=1, Version=1.2.6, Linux environment
Cluster started with:
bin/yb-ctl start --tserver_flags="yb_num_shards_per_tserver=2,leader_failure_max_missed_heartbeat_periods=2"

The following program tests serializable isolation using concurrent transactions that flip color of black/white items.

https://gist.github.com/kmuthukk/310a2199c8d0f8d2647510a1b47442f6

No correctness errors were found; but occasionally get two unexpected kinds of exceptions (which the program catches and ROLLsBACK):

`switch_colors_slave: Thread-2; Exception: Not found: Missing metadata for transaction: 94a2a059-05b3-467f-8106-fe098f71b991`

or

`switch_colors_slave: Thread-2; Exception: Error during commit: Operation expired: Transaction expired`

**Comment by rahuldesirazu** [comment]
@kmuthukk Server side txn conflict errors aren't normalized, which means that the client can see up to 3 different error messages. Follow up task is to do a little research on how other Postgres DBs are handling error codes/messages and try to follow suit with some kind of normalization so client doesn't have to case on 3 separate error messages.

**Comment by kmuthukk** [comment]
@mbautin mentioned he's working on normalizing the error codes related to this.

**Comment by bllewell** [comment]
`kmuthukk` said "client can see up to 3 different error messages". But `mbautin` tells me that there are at least _eight_. I've seen errors with all of these substrings in my tests:
```
Conflicts with higher priority transaction
Transaction expired
Missing metadata for transaction
Operation failed. Try again.: Value write after transaction start
Operation failed. Try again.: Transaction aborted
Query error: Restart read required
```
`mbautin` intends to map all of these to `error 40001` but to keep the error texts distinct. Fair enough. But the action for all flavors of serialization error is to retry the failed txn.

Notice that some of the texts include "Try again", one includes "Restart", and some don't even mention the retry advice.

Please update the error texts so the _each one_ begins thus:
```
Serialization error. Retry the transaction.
```
By all means then append wording to reflect the particular flavor of serialization error..

**Comment by m-iancu** [comment]
This works fine in latest, closing.
