### ISSUE TITLE
[YSQL] Compilation fails on Ubuntu 18.04 

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1277]
https://gist.github.com/mbautin/9e391c84c8b41a90fadf5f10c027042e

**Comment by mbautin** [comment]
https://circleci.com/gh/YugaByte/yugabyte-db/18?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by m-iancu** [comment]
Should be fixed by d1740de.
