### ISSUE TITLE
[DocDB] [PITR] [Tablet Splitting] After restore, select query returns Tablet not found error

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#12802]
Jira Link: [DB-685](https://yugabyte.atlassian.net/browse/DB-685)
### Description

Version: 2.14.0.0-b26

**Steps**:

1. Create database and table
2. Create snapshot schedule and collect time(time1) and tablets count(tn1)
3. Start workload
4. Observe increase in the tablet count and stop the workload.
5. Restore back to collected time time1
6. Connect to ysqlsh and run select count(*) from employees;

  Observed:
1. Tablets count decreasing and 

```
demo=# select count(*) from employees;
ERROR:  IO error: Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Not found (yb/tserver/read_query.cc:322): Tablet not found: 1d55e8526e524d1c9b83e8b8707266c6, Not found (yb/tserver/read_query.cc:322): Tablet not found: 9e585cb2a01a431c9ad1aabff6271a69, Not found (yb/tserver/read_query.cc:322): Tablet not found: e3319856973b4bfeb7aa033f24897609, Operation failed. Try again (yb/tserver/service_util.cc:222): The tablet 17f8192fa9474abc8b12e747e0964d1a is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT (tablet server error 28) (split child tablet IDs [60075a961757499181a00936b743b5d1, 35894da54dbe41e596ac6d41ff91a692])]
```

After some time if user executes same select query it returns correct result(0)
And increase in the tablets count.

Then 

1. Insert a row, collect time(time2) and tablets count(tn2).
2. Start the same workload
3. Observe increase in the tablet count and stop the workload.
4. Restore back to collected time time2
5. Connect to ysqlsh and run select count(*) from employees;

**Observed**:
1. Tablets count decreased to tn2 and 
```
demo=# select count(*) from employees;
ERROR:  Not found: [Not found (yb/tserver/read_query.cc:322): Tablet not found: 94f0f43991ec45b79186851bfe277114, Not found (yb/tserver/read_query.cc:322): Tablet not found: b3f0aa5ee8d94489adf52474de0e3b08, Not found (yb/tserver/read_query.cc:322): Tablet not found: d448caa023d64cb48e49054de4e01394]
```

After 5 min select query returned correct value(1)

**Comment by Arjun-yb** [comment]
It is not reproducible with above given steps. But I reproduced it with couple more restores.

Version: **2.14.0.0-b61**
**Steps**:

1. Create database and table(table_1)
2. Create snapshot schedule
3. collect time(t1) and tablets count(tc1)(count is 4)
4. Load data and observe increase it tablets
5. Stop workload and restore back to collected time(t1)
6. Validate data and tablets count
7. Observed restore went well and tablets count is 7
8. insert a row in table_1 and Follow step3 to step6
9. Observed restore went well and tablets count is 14
10. Collect time(t2)
11. Create 2 more tables(table_2 and table_3) and load some data to table_3
12. Observe increase in tablets count and stop the workload
13. Restore back to time t2
14. Observed restore went well
15. Collect time(t3) and load some more data to table_1
16. Observe increase in tablets count and stop the workload
17. Restore back to time(t3) and run select count(*) from employees, it returned

```
demo=# select count(*) from employees;
ERROR:  Not found: [Not found (yb/tserver/read_query.cc:322): Tablet not found: 9aee34fd51aa4b3ca03a8cabd74f8e1d, Not found (yb/tserver/read_query.cc:322): Tablet not found: b5152ad416624381a76e6c2cc4328958]

```
```
demo=# select count(*) from employees;
ERROR:  IO error: Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Not found (yb/tserver/read_query.cc:322): Tablet not found: 9aee34fd51aa4b3ca03a8cabd74f8e1d, Not found (yb/tserver/read_query.cc:322): Tablet not found: b5152ad416624381a76e6c2cc4328958, Operation failed. Try again (yb/tserver/service_util.cc:222): The tablet 3443c5153b5d4d12b2a3f88fa3450517 is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT (tablet server error 28) (split child tablet IDs [e3063cc6b8dd4e2c8f1150deff7b0c23, 457d839b6b874ea9855ddc39df6d3f9e]), Operation failed. Try again (yb/tserver/service_util.cc:222): The tablet f72cff1b24404a92aaf802be4a094c28 is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT (tablet server error 28) (split child tablet IDs [27167358dd814685afc3cc97d4de7285, f9d4bd2ad9a342dfa5705db8f22d32e7])]

```
and
After some time `select count(*) from employees;` query returned correct value

**Observations**:
Every time when I restore I saw different tablets count.
after 3-4 restores, select query returned - Tablet not found error

**Comment by Arjun-yb** [comment]
Version: **2.14.1.0-b21**

**Steps**:
Create database and table
```
create database demo;
create table employees(id int primary key, name text, age int, description text);
```
Collect tablets count
Create snapshot schedule and collect time
Load 100K rows
Observe increase in tablets count[Observed(30+ tablets) and stopped workload]
Restore back to collected time
Verify restored snapshot status
Connect to ysqlsh and execute `select count(*) from employees;`

Observed below error.
`ERROR:  IO error: Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Not found (yb/tserver/read_query.cc:322): Tablet not found: 150fa0d5db2944ef9610cd306995dd4c, Operation failed. Try again (yb/tserver/service_util.cc:222): The tablet 16a2ad1d76b2468dae01af05c9364fba is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT (tablet server error 28) (split child tablet IDs [8e1638b44b364bf5845360fb0038b55c, f906488b42e14c4e85a253c67e918c04]), Operation failed. Try again (yb/tserver/service_util.cc:222): The tablet 8ce7fa646123419fad4117daa60dd1cd is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT (tablet server error 28) (split child tablet IDs [e0cb41b936384b2c896ca04497be709f, 22d2660d05e648c792054cfb8997d4be])]`

in next run it gave
```
demo=# select count(*) from employees;
 count
-------
     0
(1 row)
```

**Comment by lingamsandeep** [comment]
This fix also addresses: https://github.com/yugabyte/yugabyte-db/issues/14222
