### ISSUE TITLE
[DocDB] Sample Traces at creation rather than at printing

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#12826]
Jira Link: [DB-732](https://yugabyte.atlassian.net/browse/DB-732)
### Description

Currently when traces are enabled,
* we collect traces for all incoming/outgoing RPCs and
* only print a sample of them based on sampling frequency (or latency outliers).

We should change this to support
* sampling incoming/outgoing RPCs
 
 such that we can enable sampled traces by default.

**Comment by rthallamko3** [comment]
Reopening it to track 2.14 backport.

**Comment by amitanandaiyer** [comment]
Results of testing the impact of enabling this feature at 2% sampling (1 in 50) for tserver and master on 2.17.3.0-b19 (job id 1164102)

<img width="1159" alt="Screenshot 2023-03-15 at 7 40 30 PM" src="https://user-images.githubusercontent.com/32495790/226792429-15be76f0-4fac-424f-882b-22165e7d0132.png">
<img width="1176" alt="Screenshot 2023-03-15 at 7 40 20 PM" src="https://user-images.githubusercontent.com/32495790/226792445-efa61e4d-9a38-4fd4-87e6-e82034cd51f9.png">
<img width="1190" alt="Screenshot 2023-03-15 at 7 40 09 PM" src="https://user-images.githubusercontent.com/32495790/226792449-cf106b3f-6d25-4750-a320-354fcf59c538.png">


```
{
  "test_id": 1164102,
  "type": "TPCC",
  "status": "COMPLETED",
  "payload": {
    "uuid": "443322450911712571",
    "execute": "true",
    "yb_owner": "amitanand",
    "portal_id": 301,
    "test-user": "amitanand",
    "db_provider": "YB",
    "warmup-time": "30",
    "masterGFlags": [
      {
        "name": "sampled_trace_1_in_n",
        "value": "50"
      }
    ],
    "storage_type": "S3",
    "loaderthreads": "10",
    "tserverGFlags": [
      {
        "name": "sampled_trace_1_in_n",
        "value": "50"
      }
    ],
```
