### ISSUE TITLE
[DevOps] Create a release pipeline for bundling Yugabyted-ui as part of the YugabyteDB release

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#12839]
### Description

As part of the Yugabyted UI project, we have a requirement to bundle the Yugabyted UI binary as part of the YugabyteDB release binary. The steps documents below need to incorporate as part of the release pipeline. 

### Build React.js application

`npm start` - runs the app in dev mode at http://localhost:3000

`npm run build` - builds the app in prod mode into `build/` dir, wiping the previous build if any

### Build Go API Server application

`go build -o yugabyted-ui` - builds the Go API Server of the Yugabyted UI.

`./yugabyted-ui` - Runs the app at http://localhost:1323                             |

**Comment by svarnau** [comment]
engineering devops issues go here: https://github.com/yugabyte/internal-devops/issues

**Comment by nchandrappa** [comment]
Move to internal-devops repo.
