### ISSUE TITLE
[YSQL] Very bad performance compared with Postgres

### ISSUE THREAD

**Issue by GiKyouGetsu** [yugabyte/yugabyte-db#12837]
Jira Link: [DB-2603](https://yugabyte.atlassian.net/browse/DB-2603)
### Description

Hi teams, we are now face a critical performance issue  for Yugabyte, we setup a Yugabyte(Macbook version) in my laptop with default configuration, and we have a table :refer this 
[hagent.txt](https://github.com/yugabyte/yugabyte-db/files/8869083/hagent.txt), there are 207 columns and without primary key but with 4 indexes,  and we insert more than 900K row to to this table(Via go application through 10 goroutines), and take 2000s, and I can monitor the TPS from PG Admin client is about 1500，during run batch sql, the PC's resource monitor:

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/39553517/172820484-92a2a497-5007-4ad1-a718-3f98cef7f667.png)

After finishing the data insert, we tested the query performance
we create a View:
```sql
CREATE VIEW cms_hagent AS
select * from
(select to_timestamp(a.starttime_utc)::timestamp without time zone row_start_time, * from hagent a
left join
(select agent_id,agent_name from du_agent) b
on a.logid = b.agent_id) c
```
and query with below sql:
```sql
select to_char(row_start_time, 'yyyy-MM-dd'),split,logid,acdcalls,i_stafftime
from cms_hagent where logid in ( '34062','34067') group by to_char(row_start_time, 'yyyy-MM-dd'),split,logid,acdcalls,i_stafftime
order by to_char(row_start_time, 'yyyy-MM-dd'),split,logid,acdcalls,i_stafftime
```
The query result is:
![image](https://user-images.githubusercontent.com/39553517/172818286-c9e205c9-80f3-4cb4-a84c-44a4ddddd232.png)
it take more about 30s, but is is totally different with Postgres DB, postgres just take no more than 2s
![image](https://user-images.githubusercontent.com/39553517/172818727-1f0974c4-34f9-4cd3-a34c-ff0bebf5b3c8.png)

And the PC resource is (Mackbook Pro 15-inch 2018)

CPU: Intel Core I7 2.2Hz 6Core
Memory: 16GB 2400Mhz DDR4

Can someone help ?

**Comment by ddorian** [comment]
Hi @GiKyouGetsu 

There are several things to note here:

1. We don't perform very well on OLAP scenarios: https://docs.yugabyte.com/preview/faq/general/#when-is-yugabytedb-not-a-good-fit
2. The table should have a primary-key (optional in PostgreSQL). If not, a hidden one gets created underneath. Is it possible to add a primary key and remove one of the indexes?
3. YugabyteDB starts as sharded by default, therefore things have higher overhead. A change that you can do is use a colocated database to better compare against PostgreSQL https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_database/
4. Currently we have higher overhead on tables with many columns but small values, this is being fixed in the next version in https://github.com/yugabyte/yugabyte-db/issues/3520
5. After doing these changes, can you do `explain analyze` on the queries in both PostgreSQL & YugabyteDB?

**Comment by GiKyouGetsu** [comment]
Thanks for your response @FranckPachot , Here is the different after running the explain sql that you provide

Run at PG: 
"Group (actual time=429.302..430.874 rows=698 loops=1)"
"  Output: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"  Group Key: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"  ->  Sort (actual time=429.298..429.584 rows=4935 loops=1)"
"        Output: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"        Sort Key: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"        Sort Method: quicksort  Memory: 578kB"
"        ->  Hash Left Join (actual time=2.679..416.362 rows=4935 loops=1)"
"              Output: to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text), a.split, a.logid, a.acdcalls, a.i_stafftime"
"              Hash Cond: (a.logid = (du_agent.agent_id)::bpchar)"
"              ->  Index Scan using hag_ndx3 on public.hagent a (actual time=1.678..397.644 rows=4935 loops=1)"
"                    Output: a.row_date, a.starttime, a.starttime_utc, a.intrvl, a.acd, a.split, a.extension, a.logid, a.loc_id, a.rsv_level, a.tenant, a.i_stafftime, a.ti_stafftime, a.i_availtime, a.ti_availtime, a.i_acdtime, a.i_acwtime, a.i_acwouttime, a.i_acwintime, a.ti_auxtime, a.i_auxouttime, a.i_auxintime, a.i_othertime, a.acwincalls, a.acwintime, a.auxincalls, a.auxintime, a.acwoutcalls, a.acwouttime, a.acwoutoffcalls, a.acwoutofftime, a.acwoutadjcalls, a.auxoutcalls, a.auxouttime, a.auxoutoffcalls, a.auxoutofftime, a.auxoutadjcalls, a.event1, a.event2, a.event3, a.event4, a.event5, a.event6, a.event7, a.event8, a.event9, a.assists, a.acdcalls, a.acdtime, a.acwtime, a.o_acdcalls, a.o_acdtime, a.o_acwtime, a.da_acdcalls, a.da_anstime, a.da_abncalls, a.da_abntime, a.holdcalls, a.holdtime, a.holdabncalls, a.transferred, a.conference, a.abncalls, a.abntime, a.i_ringtime, a.i_da_acdtime, a.i_da_acwtime, a.da_acdtime, a.da_acwtime, a.da_othercalls, a.da_othertime, a.ringcalls, a.ringtime, a.ansringtime, a.ti_othertime, a.da_acwincalls, a.da_acwintime, a.da_acwocalls, a.da_acwotime, a.da_acwoadjcalls, a.da_acwooffcalls, a.da_acwoofftime, a.noansredir, a.incomplete, a.acdauxoutcalls, a.i_acdaux_outtime, a.i_acdauxintime, a.i_acdothertime, a.phantomabns, a.i_auxtime, a.holdacdtime, a.da_release, a.acd_release, a.ti_auxtime0, a.ti_auxtime1, a.ti_auxtime2, a.ti_auxtime3, a.ti_auxtime4, a.ti_auxtime5, a.ti_auxtime6, a.ti_auxtime7, a.ti_auxtime8, a.ti_auxtime9, a.acdcalls_r1, a.acdcalls_r2, a.i_otherstbytime, a.i_auxstbytime, a.intrnotifies, a.acceptedintrs, a.rejectedintrs, a.intrdeliveries, a.ti_auxtime10, a.ti_auxtime11, a.ti_auxtime12, a.ti_auxtime13, a.ti_auxtime14, a.ti_auxtime15, a.ti_auxtime16, a.ti_auxtime17, a.ti_auxtime18, a.ti_auxtime19, a.ti_auxtime20, a.ti_auxtime21, a.ti_auxtime22, a.ti_auxtime23, a.ti_auxtime24, a.ti_auxtime25, a.ti_auxtime26, a.ti_auxtime27, a.ti_auxtime28, a.ti_auxtime29, a.ti_auxtime30, a.ti_auxtime31, a.ti_auxtime32, a.ti_auxtime33, a.ti_auxtime34, a.ti_auxtime35, a.ti_auxtime36, a.ti_auxtime37, a.ti_auxtime38, a.ti_auxtime39, a.ti_auxtime40, a.ti_auxtime41, a.ti_auxtime42, a.ti_auxtime43, a.ti_auxtime44, a.ti_auxtime45, a.ti_auxtime46, a.ti_auxtime47, a.ti_auxtime48, a.ti_auxtime49, a.ti_auxtime50, a.ti_auxtime51, a.ti_auxtime52, a.ti_auxtime53, a.ti_auxtime54, a.ti_auxtime55, a.ti_auxtime56, a.ti_auxtime57, a.ti_auxtime58, a.ti_auxtime59, a.ti_auxtime60, a.ti_auxtime61, a.ti_auxtime62, a.ti_auxtime63, a.ti_auxtime64, a.ti_auxtime65, a.ti_auxtime66, a.ti_auxtime67, a.ti_auxtime68, a.ti_auxtime69, a.ti_auxtime70, a.ti_auxtime71, a.ti_auxtime72, a.ti_auxtime73, a.ti_auxtime74, a.ti_auxtime75, a.ti_auxtime76, a.ti_auxtime77, a.ti_auxtime78, a.ti_auxtime79, a.ti_auxtime80, a.ti_auxtime81, a.ti_auxtime82, a.ti_auxtime83, a.ti_auxtime84, a.ti_auxtime85, a.ti_auxtime86, a.ti_auxtime87, a.ti_auxtime88, a.ti_auxtime89, a.ti_auxtime90, a.ti_auxtime91, a.ti_auxtime92, a.ti_auxtime93, a.ti_auxtime94, a.ti_auxtime95, a.ti_auxtime96, a.ti_auxtime97, a.ti_auxtime98, a.ti_auxtime99, a.icrpullcalls, a.icrpulltime, a.da_icrpullcalls, a.da_icrpulltime, a.attrib_id, a.partial_archive"
"                    Index Cond: (a.logid = ANY ('{34062,34067}'::bpchar[]))"
"              ->  Hash (actual time=0.303..0.304 rows=6 loops=1)"
"                    Output: du_agent.agent_id"
"                    Buckets: 1024  Batches: 1  Memory Usage: 9kB"
"                    ->  Seq Scan on public.du_agent (actual time=0.282..0.284 rows=6 loops=1)"
"                          Output: du_agent.agent_id"
"Planning Time: 5.375 ms"
"Execution Time: 431.300 ms"


Run at YB:
"Sort (actual time=33260.357..33260.394 rows=718 loops=1)"
"  Output: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"  Sort Key: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"  Sort Method: quicksort  Memory: 81kB"
"  ->  HashAggregate (actual time=33258.713..33258.823 rows=718 loops=1)"
"        Output: (to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text)), a.split, a.logid, a.acdcalls, a.i_stafftime"
"        Group Key: to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text), a.split, a.logid, a.acdcalls, a.i_stafftime"
"        ->  Merge Left Join (actual time=33253.586..33257.118 rows=5050 loops=1)"
"              Output: to_char((to_timestamp((a.starttime_utc)::double precision))::timestamp without time zone, 'yyyy-MM-dd'::text), a.split, a.logid, a.acdcalls, a.i_stafftime"
"              Merge Cond: (a.logid = (du_agent.agent_id)::bpchar)"
"              ->  Sort (actual time=33249.454..33249.766 rows=5050 loops=1)"
"                    Output: a.starttime_utc, a.split, a.logid, a.acdcalls, a.i_stafftime"
"                    Sort Key: a.logid"
"                    Sort Method: quicksort  Memory: 587kB"
"                    ->  Seq Scan on public.hagent a (actual time=29.016..33243.593 rows=5050 loops=1)"
"                          Output: a.starttime_utc, a.split, a.logid, a.acdcalls, a.i_stafftime"
"                          Filter: (a.logid = ANY ('{34062,34067}'::bpchar[]))"
"                          Rows Removed by Filter: 969579"
"              ->  Sort (actual time=1.838..1.838 rows=0 loops=1)"
"                    Output: du_agent.agent_id"
"                    Sort Key: du_agent.agent_id USING <"
"                    Sort Method: quicksort  Memory: 25kB"
"                    ->  Seq Scan on public.du_agent (actual time=1.764..1.764 rows=0 loops=1)"
"                          Output: du_agent.agent_id"
"Planning Time: 29.622 ms"
"Execution Time: 33263.736 ms"

**Comment by FranckPachot** [comment]
That's interesting. So PostgreSQL uses the `hag_ndx3 ON public.hagent (acd,row_date,starttime,logid)` for the predicate `(a.logid = ANY ('{34062,34067}'::bpchar[]))` . This is not really efficient, just a bit better that table scan, because it scans actually all the index (would be visible by adding `buffers` in `explain (costs off, analyze, verbose, buffers)` ) but still ok because it reads it from memory. Distributed databases are more sensitive to using the right indexes because they have to scale out, reading from many nodes.

For this query the best index would be
```
CREATE INDEX hag_ndx5 ON public.hagent ( logid, split, starttime_utc, i_stafftime, acdcalls); 
```

I think your four existing indexes are not optimal. Maybe good enough for postgres, but will not scale. You should think about indexes starting with the selective predicates that are used in where clauses (like `logid` here). That's sufficient for few rows, but when it reads thousands of rows (like `5050` here) you should also add all required columns (the ones visible in `Output: a.starttime_utc, a.split, a.logid, a.acdcalls, a.i_stafftime`) in the index, after the selective ones or in an [include](https://blog.yugabyte.com/how-a-distributed-sql-database-boosts-secondary-index-queries-with-index-only-scan/) clause, so that it does an `Index Only Scan` instead of `Index Scan`.

If you want to understand better how indexing works in YugabyteDB here is the related [YFTT episode](https://www.youtube.com/watch?v=TC1-BLqERH4&list=PL8Z3vt4qJTkLTIqB9eTLuqOdpzghX8H40&index=12)

**Comment by GiKyouGetsu** [comment]
Thanks for your advice @FranckPachot about the Index: hag_ndx5, since adding this index, the performance improved a lot, will learn how indexing works in YugabyteDB according to the Video that you provided,

But when I follow your article https://dev.to/yugabyte/1-million-rows-insert-59c8, run below

> drop table if exists demo;
create table demo (id int primary key, a int, b int, c int, d int);
set yb_disable_transactional_writes = on;
set yb_enable_upsert_mode = on;
set ysql_session_max_batch_size = 0;
set ysql_max_in_flight_ops = 10000;
explain (costs off, analyze) insert into demo select generate_series(1,100000),0,0,0,0;

when I set yb_disable_transactional_writes  to on, I will get an error like below: 

`ERROR:  Illegal state: Used read time is not set
SQL state: XX000`

Could you please advice some?

**Comment by FranckPachot** [comment]
For `yb_disable_transactional_writes` I got this errors sometimes, didn't get the full understanding why. I'll check with engineers behind this feature. But, you should leave it off as I don't see lot of improvement with it when other optimizations are on like upsert mode. By the way, it is still a beta feature and has to be set at cluster level but packed columns will be a game changer for your table with so many columns (too many actually, I'll never recommend hundreds of columns, better put that in a JSON, but that's what it is). 
So it is in beta but I'm interested by your feedback if you set `max_packed_row_columns=1000` when you start the cluster

**Comment by GiKyouGetsu** [comment]
Hi @FranckPachot , I tested the performance when insert 100000 rows (through 4 threads via go application) that is more than 200 columns with below scenarios:

`--tserver_flags=max_packed_row_columns=1000 & set yb_enable_upsert_mode = on;`

> take 109.3554435

`--tserver_flags=max_packed_row_columns=-1 & set yb_enable_upsert_mode = off;`

> take:  164.5195118

It improve a lot if set max_packed_row_columns=1000 and enable yb_enable_upsert_mode

**Comment by rthallamko3** [comment]
@GiKyouGetsu , The gflag for PackedColumns has changed recently. In order to use it going forward, you would need to use the 
`tserver_flags=ysql_enable_packed_row=true`

**Comment by GiKyouGetsu** [comment]
Thanks @rthallamko3 , will test with this GFlag

**Comment by FranckPachot** [comment]
@GiKyouGetsu The 2.15 release is out, with this new ` tserver_flags=ysql_enable_packed_row=true` syntax

**Comment by saurik** [comment]
I feel like, based on the subsequent discussion, maybe this can be closed?

**Comment by destitute507** [comment]
> Hi [@FranckPachot](https://github.com/FranckPachot) , I tested the performance when insert 100000 rows (through 4 threads via go application) that is more than 200 columns with below scenarios:
> 
> `--tserver_flags=max_packed_row_columns=1000 & set yb_enable_upsert_mode = on;`
> 
> > take 109.3554435
> 
> `--tserver_flags=max_packed_row_columns=-1 & set yb_enable_upsert_mode = off;`
> 
> > take:  164.5195118
> 
> It improve a lot if set max_packed_row_columns=1000 and enable yb_enable_upsert_mode





https://stackdev.space/questions/error-occurred-while-attempting-to-insert-data-into-the-sql-database
