### ISSUE TITLE
[YSQL] Document the behavior of "SHOW max_connections"

### ISSUE THREAD

**Issue by SteveXiSong** [yugabyte/yugabyte-db#12832]
Jira Link: [DB-2599](https://yugabyte.atlassian.net/browse/DB-2599)
### Description

With the latest YB changes for our cloud (#12737), the default behavior of `SHOW max_connections` will be depending on which role the user is.

More specifically, if the user has a `superuser` role, the output shows the actual `max_connections`, including connections reserved for superusers.

If the user is a non-superuser, the output shows only connections that can be used by a non-superuser. In this case, it will be `max_connections - reserved superuser connections - wal senders(not used by set)`.

Since this behavior will be different from original PG's, and it will be confusing to users if they have both access to the user roles, we should document the exact meaning of it in a public doc.

**Comment by polarweasel** [comment]
This was addressed in #13442. @sushantrmishra can you close this one if the docs are sufficient?

**Comment by sushantrmishra** [comment]
covered by #13442
