### ISSUE TITLE
[YSQL] Document exact definition of "Peak Memory Usage" in EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by SteveXiSong** [yugabyte/yugabyte-db#12834]
Jira Link: [DB-2600](https://yugabyte.atlassian.net/browse/DB-2600)
### Description

With changes (#12077), it will add a YB-added field to the output of EXPLAIN ANALYZE.
Without exact definition, the meaning of "Peak Memory Usage" will be vague to users.

We should document what is the exact definition of "Peak Memory Usage" to our public doc.

One sentence definition of this field is:
`The maximum memory allocated by the current statement since it is executed, including usage by both PG and pggate.`

**Comment by polarweasel** [comment]
Already covered by #13478. @sushantrmishra can you close this one if the docs are sufficient there?

**Comment by sushantrmishra** [comment]
covered by #13478.
