### ISSUE TITLE
[DevOps] Setup the user workstation for Yugabyted-UI development

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#12841]
### Description

For Yugabyted-UI development, developer workstations need to have Go lang binary installed.

**Comment by svarnau** [comment]
Please file this in https://github.com/yugabyte/internal-devops/issues
and please be specific if there are version requirements, or whether default for each OS version is okay.

**Comment by nchandrappa** [comment]
Moved to the internal-devops repo.
