### ISSUE TITLE
[DocDB] Enable https web UI for master/tserver when node-to-node encryption in transit is enabled

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#12861]
Jira Link: [DB-2622](https://yugabyte.atlassian.net/browse/DB-2622)
### Description

When node-to-node encryption is enabled, a server cert is provided to yugabyte for RPC communication. We can also use this certificate to enable a https web UI for the master and tserver. Typically these interfaces do not show sensitive data but in some specific scenarios like LDAP configuration, the gflags can contain sensitive information. 

@bmatican @es1024

**Comment by es1024** [comment]
There is the `webserver_certificate_file` gflag to enable https on the UI, but this must be set to point to the certificate manually.

**Comment by iSignal** [comment]
Thanks @es1024 . Will file a Platform issue for orchestrating both together.
