### ISSUE TITLE
[DocDB] Show encryption in transit status on master and tserver web UI

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#12860]
Jira Link: [DB-2621](https://yugabyte.atlassian.net/browse/DB-2621)
### Description

When TLS/encryption in transit is enabled, the master/tserver should show this in the web UI.

We should indicate the status of
1. Node to node encryption
2. Client to node encryption (for tservers only), and
3. Whether insecure conns are allowed.

The current footer could be one place to include this information. 

<img width="929" alt="image" src="https://user-images.githubusercontent.com/8207010/173289123-a676f894-fd9e-492a-ab18-1d24b7bcba07.png">

**Comment by karan-yb** [comment]
Added TLS page under Utilities which lists the configs set at node level and certificates being used. See sample screenshot below.
![image](https://user-images.githubusercontent.com/4623304/182227663-a8e5d76e-062d-4f9d-a447-1925cfa88944.png)
