### ISSUE TITLE
[CDCSDK] Deletion of xcluster stream entries from cdc_state table on dropping a table

### ISSUE THREAD

**Issue by isha-yb** [yugabyte/yugabyte-db#12877]

**Comment by isha-yb** [comment]
This issue was introduced by commit id 6f83b559791c3f35fe1080bf8410a7a1cee9d7b1
On forcefully dropping a table with xcluster stream, the corresponding entries from the cdc_state table get deleted

**Comment by sureshdash2022-yb** [comment]
This is fixed and closed
