### ISSUE TITLE
[YSQL] It is not safe to call YBOnPostgresBackendShutdown from quickdie

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#12884]
Jira Link: [DB-2635](https://yugabyte.atlassian.net/browse/DB-2635)
### Description

The `quickdie` function is called as a signal handler. As a result this function should call `async-signal-safe` functions only.
The `YBOnPostgresBackendShutdown` function is too complex to be called from signal handler as this function destroys the `pggate::PgApiImpl` object and the destructor of this object locks mutexes.

Also it is not safe to destroy the `pggate::PgApiImpl` object because YSQL is a multi-threaded process. As a result `quickdie` can be called from any of the thread. As a result `pggate::PgApiImpl` object can be destroyed while it is still in use by the YSQL main thread.

Example:

YSQL's main thread calls `YBCInsertSequenceTuple` function
```
...
if (IsYugaByteEnabled())
{
    HandleYBStatus(YBCInsertSequenceTuple(...)); // This function uses the `pggate::PgApiImpl` object
}
...
```

at same time another thread handles SIGQUIT signal by calling `quickdie`.

As a result it is possible that `quickdie` will delete the `pggate::PgApiImpl` object while it is still in use.

**Comment by mbautin** [comment]
Can we set a flag or enqueue a task in the signal handler that will then cause shutdown to happen in a regular thread?
