### ISSUE TITLE
Local cluster does not come up if PostgreSQL port is already being used

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#129]
A lot of developers run PostgreSQL on their laptops, and they might not even be trying to use the PostgreSQL API. YB should not fail to start up in those cases.
Reported by @mbautin.

**Comment by rkarthik007** [comment]
@mbautin - One option is we make a non-standard postgres port the default. Say something like `(postgres-default-port) + 1` or something like that for now. Does that work?

cc @nocaway, @robertpang

**Comment by nocaway** [comment]
At this moment, as a workaround we make 5433 (instead of 5432) as default port for PostgreSQL support. Once we have an actual fix to avoid port-conflict in our system-setup, this workaround can be removed from our source code, and 5432 would be our default port.
