### ISSUE TITLE
[xCluster][packed row/column] Replication is not working

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#12901]
Jira Link: [DB-2645](https://yugabyte.atlassian.net/browse/DB-2645)
### Description

**Version**: **2.15.0.0-b4**

**Steps**:
1. Create universes(source and target) with below GFLAGs(add in both master and tserver)
```
ysql_enable_packed_row=true
ycql_enable_packed_row=true

```
2. Create database(demo) and table(employees) on both sides.
3. Setup xCluster at source side with platform UI(Replication tab-> Configure replication -> Select target-> select table and setup)
4. Insert some rows at source side and validate data at target side.

**Expected**:
Replication should happen - Inserted data(at source side) should be present at Target side

**Actual**:
Replication is not happening and observed below error in tserver log
```
I0615 07:56:02.704607 19601 raft_consensus.cc:3371] T a53ac8f8e2c049dd94c7a81f70e70b4e P ea4b0bb33f1546e1bfde94486b88c679 [term 2 FOLLOWER]: NO_OP [1.1] replication failed: Aborted (yb/consensus/replica_state.cc:612): Operation aborted by new leader
    @          0x2db9825  yb::consensus::ConsensusRound::NotifyReplicationFinished()
    @          0x2e00f82  yb::consensus::ReplicaState::AbortOpsAfterUnlocked()
    @          0x2dee6aa  yb::consensus::RaftConsensus::UpdateReplica()
    @          0x2dd51cf  yb::consensus::RaftConsensus::Update()
    @          0x36d05e7  yb::tserver::ConsensusServiceImpl::MultiRaftUpdateConsensus()
    @          0x2e3b9ba  std::__1::__function::__func<>::operator()()
    @          0x2e3cec6  yb::consensus::ConsensusServiceIf::Handle()
    @          0x3447e43  yb::rpc::ServicePoolImpl::Handle()
    @          0x3397085  yb::rpc::InboundCall::InboundCallTask::Run()
    @          0x3456bdd  yb::rpc::(anonymous namespace)::Worker::Execute()
    @          0x3a15f84  yb::Thread::SuperviseThread()
    @     0x7f4c9d8dd694  start_thread
    @     0x7f4c9dddf41d  __clone
```

**Comment by bmatican** [comment]
Probably duplicate of #13084, maybe we can just re-validate this test, after @hari90 lands the fix.

**Comment by Arjun-yb** [comment]
Re-validated with fixed build and tests are running fine. Closing this issue
