### ISSUE TITLE
[PITR] [Packed Row Column] Restore fails when packed columns are enabled in the universe(2.15), fatal log files generated

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12903]
Jira Link: [DB-2646](https://yugabyte.atlassian.net/browse/DB-2646)
### Description

Steps to reproduce the issue:
- Create a universe on 2.15 with the below gflags set-
```
{ "ysql_enable_packed_row" : "true",
  "ycql_enable_packed_row" : "true"
}
```
- Create a database
- Setup snapshot schedule on the database
- Note down time
- Create a table
- Execute restore to the time noted in step 4.
**Issue:**
1. Restore fails with the error:
Error running restore_snapshot_schedule: Network error (yb/util/net/socket.cc:534): Failed to restore snapshot: recvmsg got EOF from remote (system error 108)

2. Several Fatal files are generated in the cluster.
FATAL, ERROR logs contain:
```
F0615 09:08:04.166016 25242 operation_driver.cc:399] T 00000000000000000000000000000000 P 26837d1049bc48b388764f92fc671983 S RD-P Ts { physical: 1655282936261741 } kSnapshot (0x0000000002aa0090): Apply failed: Not found (yb/docdb/packed_row.cc:199): Restore sys catalog failed: Schema packing not found: 0, request: operation: RESTORE_SYS_CATALOG snapshot_id: "\347P0\265\321\271OK\234\231Cl*x\303\014" snapshot_hybrid_time: 6780038727683112960 restoration_id: "7\212`\317\363\335M\377\220Csb\351\323\3642"
```

3. Post the restore, master process goes down in the nodes, ysql, ycql connectivity gets cut.

CC: @nmantrav2 , @bmatican , @sanketkedia , @rthallamko3 , @spolitov 

The scenario cited in the steps is a sample PITR scenario. 100% of itest system PITR tests are failing with packed rows enabled.

**Comment by rthallamko3** [comment]
@kripasreenivasan , resolving this based on the fixes that Sergei has made. Let us know if this is still an issue.
