### ISSUE TITLE
[DocDB] Intermittent Encryption at Rest Can't Find Key

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#12908]
Jira Link: [DB-2650](https://yugabyte.atlassian.net/browse/DB-2650)
### Description

After an upgrade from 2.15.1 b13 to b35, saw the following fatal logs:

```
tablet_server_main.cc:204] Invalid argument (yb/encryption/universe_key_manager.cc:75): Could not init Tablet Manager: Failed to open tablet metadata for tablet: 4190c0ff3df740b4900e567e5e4bb583: Failed to load tablet metadata for tablet id 4190c0ff3df740b4900e567e5e4bb583: Could not load Raft group metadata from /mnt/d0/yb-data/tserver/tablet-meta/4190c0ff3df740b4900e567e5e4bb583: Key with version number <version_id>
```

After a tserver restart, it was able to bootstrap normally.

**Comment by rthallamko3** [comment]
@rahuldesirazu , Do we plan to add any more instrumentation in this area to dig deeper? If not, should we close this, if this is not a recurrent problem?

**Comment by lingamsandeep** [comment]
The combination of https://github.com/yugabyte/yugabyte-db/commit/20ac611182c2a3172cbf7bc6562fc6f441bb2a59  and https://github.com/yugabyte/yugabyte-db/commit/8bb36ecd963c6770ac9604c168c1b19850127087 fixed this issue.
