### ISSUE TITLE
[YSQL] Add metrics to show queries terminated due to temp_file_limit reached

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#12919]
Jira Link: [DB-2656](https://yugabyte.atlassian.net/browse/DB-2656)
### Description

Currently when the queries breaches the temporary file size exceeds `temp_file_limit` then following error is returned. 

`"temporary file size exceeds temp_file_limit (%dkB)", temp_file_limit; `

**For better observability**

1. We could implement a metrics to push this data to prometheus to track the cumulative count of queries terminated due to `temp_file_limit` breached.
2. Capture all the queries and show in a view. Leaving the details to TBD and names suggested is just a hint.
     -  select * from yb_terminated_queries_temp_file_limit .

**Comment by ramsrivatsa** [comment]
Is there a test to reproduce this issue?

**Comment by sushantrmishra** [comment]
> We could implement a metrics to push this data to prometheus to track the cumulative count of queries terminated due to temp_file_limit breached.

Currently we do not plan to implement this as this info is available from the view itself.
