### ISSUE TITLE
[Docs] YSQL Create Index documentation missing a comma

### ISSUE THREAD

**Issue by phendric-uk** [yugabyte/yugabyte-db#12932]
### Description

https://docs.yugabyte.com/preview/api/ycql/grammar_diagrams/#create-index

There should be a comma in the diagram between partition_key_columns and clustering_key_columns

Doc states:

CREATE INDEX ac_scalar_bucket_ts_idx ON ac_scalar_bucket ((metadata_id, group_key)   ts)  WITH CLUSTERING ORDER BY (ts DESC);

But should be:

CREATE INDEX ac_scalar_bucket_ts_idx ON ac_scalar_bucket ((metadata_id, group_key),  ts)  WITH CLUSTERING ORDER BY (ts DESC);

**Comment by ddorian** [comment]
@phendric-uk 
I can't find the index on the page. 
Please reopen the issue with the correct link.

**Comment by phendric-uk** [comment]
Hi ddorian

In:
![image](https://user-images.githubusercontent.com/96289556/176737362-41f09a22-3869-43fc-8378-c33001c71fd0.png)

The extra comma should be inserted between the partition_key_columns and the clustering_key_columns roughly as shown below:
![image](https://user-images.githubusercontent.com/96289556/176738099-fd956b99-f9a3-4308-9ff6-88be2f3ccbc5.png)
Thanks

**Comment by phendric-uk** [comment]
@ddorian Do you need any more information regarding this?
Thanks,
Paul

**Comment by phendric-uk** [comment]
@ddorian Is there anything else you require for this?
Thanks,
Paul
