### ISSUE TITLE
[DocDB] [Packed Rows/Columns] Observed Fatal logs with YSQL DDLs in transaction blocks

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#12931]
Jira Link: [DB-2667](https://yugabyte.atlassian.net/browse/DB-2667)
### Description

Version: **2.15.1.0-b4**
Universe is created with below GFLAGs
```
ysql_enable_packed_row=true
ycql_enable_packed_row=true
```
Observed FATAL logs after execution of System-itest(TestYsqlDDLsInTxnBlk) - [Execution](https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/1056/console)
Tried manually and observed once in http://10.9.134.12/universes/35f7a537-2ef0-4181-8eb9-c036abbb4b05/health
Test does
Create normal database and tries DDLs(with split/alter clause) in transaction blocks
Create colocated database and tries DDLs(with split/alter clause) in transaction blocks

**Comment by bmatican** [comment]
@Arjun-yb can you clarify what the txns looked like? I thought we don't support DDLs in transactions?
Does this work with packed off?

**Comment by Arjun-yb** [comment]
@bmatican 

1. Txns look like
```
Begin
for n in range(100):
    delete table_n
    create table_n with 1 tablet
Commit
```
and
```
Begin
for n in range(100):
    delete table_n
    create table_n 
    alter table_n
Commit
```
2. Yes it was working fine without packed column.

**Comment by spolitov** [comment]
@Arjun-yb it would be nice to provide more reliable details on issues.
1) Provide exact FATAL failure message.
2) Avoid putting link to internal resources.
The first link does not work.
The second link requires credentials that I just don't know.

All provided repro statements does not work, because they fail in the step of deleting unknown table.
Also packed row support for YCQL is incomplete and should NOT be enabled even in tests.

**Comment by Arjun-yb** [comment]
FATAL log details:
`Application fingerprint: version 2.15.0.0 build 6 revision f59494efaecaf67bd4ae3d85ff5cbcfc3e2dc6e7 build_type RELEASE built at 15 Jun 2022 05:33:53 UTC`

```
F20220707 16:06:02 ../../src/yb/docdb/primitive_value.cc:1268] Invalid value of enum ValueEntryType (full enum type: yb::docdb::ValueEntryType, expression: value_type): 35.
    @     0x7f049e58ae1c  google::LogDestination::LogToSinks()
    @     0x7f049e58a844  google::LogMessage::SendToLog()
    @     0x7f049e58bfd8  google::LogMessage::Flush()
    @     0x7f049e58c7bf  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f049e75a70b  yb::FatalInvalidEnumValueInternal()
    @     0x7f04a00be980  yb::docdb::PrimitiveValue::DecodeFromValue()
    @     0x7f04a13f230d  yb::docdb::TryDecodeValue()
    @     0x7f04a13f214c  yb::docdb::DocDBTableReader::GetHelper::NextColumn()
    @     0x7f04a13f0671  yb::docdb::DocDBTableReader::GetHelper::Scan()
    @     0x7f04a13ef694  yb::docdb::DocDBTableReader::Get()
    @     0x7f04a1412655  yb::docdb::DocRowwiseIterator::HasNext()
    @     0x7f04a1413a53  yb::docdb::DocRowwiseIterator::SeekTuple()
    @     0x7f04a1444b53  yb::docdb::PgsqlReadOperation::ExecuteScalar()
    @     0x7f04a1442614  yb::docdb::PgsqlReadOperation::Execute()
    @     0x7f04a1595efb  yb::tablet::AbstractTablet::ProcessPgsqlReadRequest()
    @     0x7f04a15b8776  yb::tablet::Tablet::HandlePgsqlReadRequest()
    @     0x7f04a17ce434  yb::tserver::(anonymous namespace)::ReadQuery::Complete()
    @     0x7f04a17cb514  yb::tserver::PerformRead()
    @     0x7f04a17fe365  yb::tserver::TabletServiceImpl::Read()
    @     0x7f04a0298d36  std::__1::__function::__func<>::operator()()
    @     0x7f04a029ade6  yb::tserver::TabletServerServiceIf::Handle()
    @     0x7f049ebf152f  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f049eb9c045  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f049ebfdca5  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f049e815411  yb::Thread::SuperviseThread()
    @     0x7f049c944694  start_thread
    @     0x7f049c08141d  __clone
```
