### ISSUE TITLE
[DocDB] Observed Healthcheck errors and soft memory limit errors

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#12930]
Jira Link: [DB-2666](https://yugabyte.atlassian.net/browse/DB-2666)
### Description

**Version**: 2.15.1.0-b13
**LRU** : http://portal.dev.yugabyte.com/universes/d7f22cf3-1f3f-4795-9d2c-5a312abe0155/overview

**Steps to reproduce**: 
1. Create a universe - Instance type - c5.xlarge - auth enabled for both YSQL and YCQL
2. Run YSQL and YCQL workloads
    `nohup java -jar yb-sample-apps-1.8.0-sh.jar --workload CassandraDataLoad --num_writes -1 --num_reads 0 --num_threads_write 1 --num_threads_read 0 --num_unique_keys 2000000000000000 --num_value_columns 5000 --default_cassandra_keyspace yb_ycql_demo --create_table_name employees_1 --uuid <uuid> --nodes <YCQL_endpoints> --username <username> --password <password> >& log_file_ycql.log &`
    
    `nohup java -jar yb-sample-apps-1.8.6-dt.jar --workload SqlDataLoad --nodes <YSQL_endpoints> --num_threads_write 1 --num_unique_keys 2000000000000000 --num_writes -1 --num_value_columns 1500 --use_datatypes true --num_indexes 1  --password <password> --username <username> >& log_file_ysql.log &`
3. Wait for a day or 2 days and observe helathchecks or client logs

**Actual**:
1. Observed many errors like -  `Rejecting CQL call: Soft memory limit exceeded (at 87.51% of capacity)` in tserver log file
2. Healthcheck error 
`Error executing command timeout 20 bash -c 'set -o pipefail; /home/yugabyte/tserver/bin/cqlsh 172.151.31.150 9042 -e "SHOW HOST"': Connection error: ('Unable to connect to any servers', {'172.151.31.150': ConnectionException('Failed to initialize new connection to 172.151.31.150: Error from server: code=1001 [Coordinator node overloaded] message=""',)})`
3. Client log(Workload running log) shows 
`533460670 [Thread-2] INFO com.yugabyte.sample.apps.CassandraDataLoad  - Failed write with error: All host(s) tried for query failed (tried: /172.151.19.175:9042 (com.datastax.driver.core.exceptions.OverloadedException: Queried host (/172.151.19.175:9042) was overloaded: ), /172.151.30.251:9042 (com.datastax.driver.core.exceptions.OverloadedException: Queried host (/172.151.30.251:9042) was overloaded: ), /172.151.31.150:9042 (com.datastax.driver.core.exceptions.OverloadedException: Queried host (/172.151.31.150:9042) was overloaded: ))`
4. Not able to connect to YCQLSH - ` Connection error: ('Unable to connect to any servers', {‘X’.X.X.X: AuthenticationFailed('Failed to authenticate to X.X.X.X: Error from server: code=1001 [Coordinator node overloaded] message=""',)})`

**Note**:  current setup has xCluster and issue is not related to xCluster, So added repro steps only.

**Comment by Arjun-yb** [comment]
Observed same **Coordinator node overloaded** issue in another LRU

`Error executing command timeout 20 bash -c 'set -o pipefail; /home/yugabyte/tserver/bin/cqlsh 172.151.16.186 9042 -e "SHOW HOST"': Connection error: ('Unable to connect to any servers', {'172.151.16.186': ConnectionException('Failed to initialize new connection to 172.151.16.186: Error from server: code=1001 [Coordinator node overloaded] message=""',)})`

**Observed** 
`Rejecting CQL call: Soft memory limit exceeded (at 95.17% of capacity)` in tserver.log file.
added perf memory files(pf-3g-v2.*) in https://drive.google.com/drive/folders/1gZcYFI3S0wB-NfttW9LQSaG5oPfYcxK3

**Comment by rthallamko3** [comment]
Load balancing to Yusong as he is looking at memory related issues.

**Comment by rthallamko3** [comment]
@Arjun-yb , Do you know if this issue is still relevant? @yusong-yan  has made a few fixes around memory leaks in the master branch in the last month or so.

**Comment by Arjun-yb** [comment]
@rthallamko3 I have not observed this issue in recent testing, I will put it in slack and we will add a comment with details if any of us observed this again.

**Comment by rthallamko3** [comment]
Closing per @Arjun-yb 's comment.
