### ISSUE TITLE
[DocDB] [PITR] Output YSQL indexes that need to be recreated after restore

### ISSUE THREAD

**Issue by vkulichenko** [yugabyte/yugabyte-db#12940]
Jira Link: [DB-2674](https://yugabyte.atlassian.net/browse/DB-2674)
### Description

Currently, if restore points to a time in the middle of backfill for some index, the index becomes unusable. The only way to resurrect such an index is to manually drop it and recreate it again.

We should provide a clear way for a user to find out which indexes are affected. The best way is to add the list to the output of the `restore_snapshot_schedule` command.

**Comment by druzac** [comment]
Until we close this issue users can get a list of invalid indices (backfill in progress) in a db with this query:
```
select pg_class.relname
from pg_index
join pg_class
on pg_index.indexrelid = pg_class.oid
where not indisvalid;
```

This could be used to find indices to drop and re-create after doing a PITR.

**Comment by sanketkedia** [comment]
@druzac this will give a list of all indexes that are not valid even the ones that are untouched by PITR restore. Can we update the query to only filter indexes for the database on which restore was performed?
