### ISSUE TITLE
[DocDB] [UI] High range tablet for hash sharding displays hash_split: [0x0000, 0xFFFF)

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#12969]
Jira Link: [DB-2700](https://yugabyte.atlassian.net/browse/DB-2700)
### Description

The UI displays `0xFFFF)` instead of `0xFFFF]` for the last tablet of a hash-sharded table (65535 is included in this tablet)
https://yugabyte.slack.com/archives/C4K1838GL/p1655764304660999?thread_ts=1655753243.138179&cid=C4K1838GL

**Comment by hari90** [comment]
https://yugabyte.slack.com/archives/C4K1838GL/p1655753243138179

**Comment by bmatican** [comment]
@es1024 This seems like it should be a pretty simple starter task. Do you mind if I repurpose it for that?

**Comment by es1024** [comment]
@bmatican I already have a diff in flight that fixes this.

**Comment by bmatican** [comment]
@es1024 ah ok, no worries then, you can push that through then

**Comment by es1024** [comment]
Fixed with d32b788
