### ISSUE TITLE
[DocDB] Log spew whenever frontiers of sys catalog tablet are being dumped

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#12976]
Jira Link: [DB-2707](https://yugabyte.atlassian.net/browse/DB-2707)
### Description

Now that table schema versions are part of user frontiers in RocksDB manifest, dumping that data to the log clutters the log a lot.

Examples:

https://gist.githubusercontent.com/mbautin/e0fd8f7efcf12d50fd537c1051f100aa/raw

https://gist.githubusercontent.com/mbautin/555f2cce63d95e2735b3319133b87c24/raw

Potential solutions:
- Don't dump user frontiers to the log at all.
- Dump an abbreviated representation of the user frontiers that does not include schema versions.

**Comment by bmatican** [comment]
Handled in #15494
