### ISSUE TITLE
[DocDB] Packed columns? Corruption: Failed to load sys catalog: Corruption (yb/master/sys_catalog_writer.cc:207): Failed while visiting tables in sys catalog: System catalog snapshot is corrupted, or is built using different build type: 0 vs 10

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12973]
Jira Link: [DB-2702](https://yugabyte.atlassian.net/browse/DB-2702)
### Description

On my [puppy-food-arm-1](http://portal.dev.yugabyte.com/universes/f3b7be2c-0b8e-4183-a1ba-9d67b98d58dd/health) universe I am seeing a (new?) corruption on 2.15.1.0-b47-arm (does not yet contain b0dcb81db7f0793ab7e6278ec1f2e34d344d3a7c, which is only on b50, I can retry on that if that helps), database can't start up anymore as a consequence:
```
[yugabyte@ip-10-9-118-199 logs]$ cat yb-master.FATAL.details.2022-06-21T11_59_05.pid2632974.txt
F20220621 11:59:05 ../../src/yb/master/catalog_manager.cc:992] T 00000000000000000000000000000000 P e14a1704879c4cd697761839525101d1: Failed to load sys catalog: Corruption (yb/master/sys_catalog_writer.cc:207): Failed while visiting tables in sys catalog: System catalog snapshot is corrupted, or is built using different build type: 0 vs 10
    @     0xffff80eda9f4  (unknown)
    @     0xffff80ed4c2c  (unknown)
    @     0xffff80ed5564  (unknown)
    @     0xffff80ed8500  (unknown)
    @     0xffff85002950  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0xffff812a8608  yb::ThreadPool::DispatchThread()
    @     0xffff8129e4c4  yb::Thread::SuperviseThread()
    @     0xffff7fc87898  start_thread
    @     0xffff7fbd1ddc  thread_start
```
This happened on all maste rservers.
@spolitov I'm not sure if there is any relation to https://github.com/yugabyte/yugabyte-db/issues/12813
This happened after running 4 workloads with packed columns enabled against the universe with packed columns enabled for ysql and ycql:

CassandraUniqueSecondaryIndex
SqlSecondaryIndex
CassandraDataLoad
SqlDataLoad

I have left the universe in the broken state to collect data. If this is unrelated, please reassign it.

**Comment by rthallamko3** [comment]
@def- , Can you check if this is still an issue?

**Comment by def-** [comment]
This issue hasn't occurred again on my LRU since then.

**Comment by rthallamko3** [comment]
Looks like with all the fixes in the improvement, this is no longer an issue.
