### ISSUE TITLE
Scripts and supporting tools to validate YugaByte DB

### ISSUE THREAD

**Issue by RashmiPanthangi** [YugaByte/yugabyte-db#1298]
We would like to benchmark YB performance in our setup (on-prem). Could you please provide the scripts and supporting which we can use to run and validate the performance?

**Comment by ramkumarvs** [comment]
@RashmiPanthangi we have a whole section on benchmarks did you guys take a look at that?.

https://docs.yugabyte.com/latest/benchmark/

**Comment by rkarthik007** [comment]
Closing this issue out, please feel free to open a separate issue if you need anything @RashmiPanthangi!
