### ISSUE TITLE
[YSQL] Cluster may hit FATAL on data != nullptr failed to allocate while have OOM on YSQL process

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#12986]
Jira Link: [DB-2714](https://yugabyte.atlassian.net/browse/DB-2714)
### Description

1. Setup c5.large cluster
2. Start workload and wait for 600 seconds to have some data on cluster
3. At some point evaluate query that might cause OOM (use repeat function for that)
4. Check, /var/log/messages for OOM and that Postgres process killed

```
Log file created at: 2022/06/20 08:25:19
Running on machine: ip-172-151-24-109.us-west-2.compute.internal
Application fingerprint: version 2.15.1.0 build 47 revision a5edc3cbcde42b35c69e7e2b52d88dff462ee210 build_type RELEASE built at 17 Jun 2022 01:28:09 UTC
Running duration (h:mm:ss): 1:17:05
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0620 08:25:19.899902 19641 malloc.cc:53] Check failed: data != nullptr failed to allocate 411675 bytes
```

**Comment by sushantrmishra** [comment]
This is clearly scenario of malloc failing under low memory scenario.. So closing this.
