### ISSUE TITLE
[DocDB] Ensure that YB can tolerate partially written tablet-metadata

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#12995]
Jira Link: [DB-2719](https://yugabyte.atlassian.net/browse/DB-2719)
### Description

Have seen a recent case where it looks like a restart in the middle of applying changes to tablet-metadata is not handled gracefully.

The system accepts the partially written file, and responds with errors like
`Not found (yb/tablet/tablet_metadata.cc:350): Table <unknown_table_name> (000033e20000300080000000000004eb) not found in Raft group 00000000000000000000000000000000`

The issue was mostly seen on ubuntu machines, where something in the system caused the processes to be rebooted when they were just created.

From the docdb perspective, we should be able to handle process restarts, regardless of when/where it is done.

**Comment by Huqicheng** [comment]
Should be sys catalog according to the tablet id
`static const char* const kSysCatalogTabletId = "00000000000000000000000000000000";`

**Comment by Huqicheng** [comment]
Seems `PlayChangeMetadataRequest` doesn't handle ADD_TABLE case. If we restart from a snapshot, it might skip such an operation?

**Comment by bmatican** [comment]
@Huqicheng nice catch! I think @sanketkedia is taking care of that here: https://phabricator.dev.yugabyte.com/D19063

**Comment by rthallamko3** [comment]
@sanketkedia , Should we backport the change to 2.14, 2.12, 2.8 branches too?
