### ISSUE TITLE
[docs] Update Third Party Software page 

### ISSUE THREAD

**Issue by proff4eg** [yugabyte/yugabyte-db#12991]
https://docs.yugabyte.com/preview/legal/third-party-software/

## Issue description
Current page contains obsolete information.
## Suggested improvement 
I suggest we update [Third party software components](https://docs.yugabyte.com/preview/legal/third-party-software/#third-party-software-components) section and make it a "reference" list to the updated license files

Build: 2.12.5.0-b24

Third-party licenses: [YugabyteDB](https://downloads.yugabyte.com/releases/2.12.5.0/yugabytedb-2.12.5.0-b24-third-party-licenses.html), [YugabyteDB Anywhere](https://downloads.yugabyte.com/releases/2.12.5.0/yugabytedb-anywhere-2.12.5.0-b24-third-party-licenses.html) 

Build: 2.12.6.0-b26

Third-party licenses: [YugabyteDB](https://downloads.yugabyte.com/releases/2.12.6.0/yugabytedb-2.12.6.0-b26-third-party-licenses.html), [YugabyteDB Anywhere](https://downloads.yugabyte.com/releases/2.12.6.0/yugabytedb-anywhere-2.12.6.0-b26-third-party-licenses.html)

**Comment by polarweasel** [comment]
@proff4eg can you look at the current version of the page and see if it meets your needs?

**Comment by ddorian** [comment]
@proff4eg closing as already fixed. Please re-open with more details if you think otherwise.
