### ISSUE TITLE
[YSQL] Deferred FK constraints don't work properly

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#13009]
Jira Link: [DB-2726](https://yugabyte.atlassian.net/browse/DB-2726)

[issue-13009.zip](https://github.com/yugabyte/yugabyte-db/files/8963777/issue-13009.zip)

### Description

This use case:

> **the _optional_ (or _mandatory_) one-to-one relationship**

is a text-book scenario that calls for a deferrable FK constraint. An implementation _either_ in pure SQL _or_ in PL/pgSQL fails in YB. Each works fine in vanilla PG.

### Environment

I spotted the bug using YB-2.13.0.1 on my laptop (running macOS Big Sur Version 11.6.6.) I'm using a freshly-created single node cluster.

### Related Github Issues

[#4700](https://github.com/yugabyte/yugabyte-db/issues/4700) [YSQL] **Support DEFERRABLE constraints** — _open_

[#1709](https://github.com/YugaByte/yugabyte-db/issues/1709) [YSQL] **DEFERRABLE constraint should be supported** _open_

[#3995](https://github.com/yugabyte/yugabyte-db/issues/3995) [YSQL] **Support deferrable for foreign key constraints** — _closed_ 6-Jul-2020 with reference to this Gira master issue that keeps track of all deferrable constraint issues:

[DB-2213](https://yugabyte.atlassian.net/browse/DB-2213) [YSQL] **Support DEFERRABLE constraints**

### The optional (or mandatory) one-to-one relationship

The _optional_ and _mandatory_ flavors meet different use cases.

- The _optional_ one-to-one relationship approach is often used when what ordinarily would be a single table has many _nullable_ columns and these are very often _NULL_. This issue's testcase splits the table vertically into two, called _mains_ and _extras_ (short for "main facts" and "extra facts"). This case calls for the _optional_ one-to-one flavor. Here, many _mains_ rows would be without _extras_ partners.
- The _mandatory_ one-to-one flavor is often used when some of the nominal single table's columns are frequently updated by one use case and the remaining columns are frequently updated concurrently by another use case. Splitting the table vertically avoids row locks that one use case takes from inhibiting progress by the other use case—and _vice versa_.

The canonical implementation has a pair of FK constraints, one in each direction, between the two tables. This ensures, declaratively, that the relationship is indeed _one-to-one_.

The scheme implies a bootstrap proposition: you can't insert a new _mains_ row unless its _extras_ partner is in place; and you can't insert a new _extras_ row unless its _mains_ partner is in place.

In the _mandatory_ flavor of the use case, the _only_ way to sidestep this dilemma, is to use a single transaction and to take advantage of a deferred FK constraint on the _mains_ table. Even in the _optional_ flavor, proper practice demands using a single transaction to implement the business function « _create a new row which has an "extra facts" part_ ».

Proper practice, again, requires encapsulating a multi-statement business transaction in a PL/pgSQL subprogram with an exception section that will translate low-level exceptions (like _unique_violation_) into business-purpose oriented vocabulary (like _"this nickname is already taken"_). However, you cannot handle an exception that arises at _commit_ time in PL/pgSQL. The _"set constraints all immediate"_ SQL statement comes to the rescue here. (Because the bootstrap dilemma arises only on _insert_, there is no possibility of a race condition—so it's safe to anticipate _commit_ in this way.)

Usual practice also requires that:

- Deleting a _mains_ row cascade-deletes its _extras_ partner— if one exists.
- Attempting to delete an _extras_ row causes an error.

These three SQL statements are all that's needed to ensure that the business rules are enforced, for the _mandatory_ one-to-one case using generated surrogate PKs—and it does so _declaratively_.

```
create table mains(
  k           int  primary key
                   generated always as identity,  -- Generated PK
  main_fact   text unique
                   not null,
  extras_k    int  unique
                           );                     -- Optional 1:1

create table  extras(
  k           int  primary key
                   generated always as identity,  -- Generated PK
  extra_fact  text unique
                   not null,
  mains_k     int  unique
                   not null,

  constraint extras_fk
    foreign key(mains_k)
    references mains(k)
    match full on delete cascade
    not deferrable);

alter table mains add
  constraint mains_fk
    foreign key(extras_k)
    references extras(k)
    match full on delete restrict
    initially deferred;
```
(This script shows just one of the four variants that are explained in the _Code organization_ section below.)

### What the YSQL doc says

Notice that the [CREATE TABLE](https://docs.yugabyte.com/stable/api/ysql/the-sql-language/statements/ddl_create_table/) doc in the _stable_ version that's current at the time of creating this comment (v2.12) shows the full syntax specification for deferrability thus:

```
[ DEFERRABLE | NOT DEFERRABLE ] 
[ INITIALLY DEFERRED | INITIALLY IMMEDIATE ]
```

and it says this in the [Semantics](https://docs.yugabyte.com/stable/api/ysql/the-sql-language/statements/ddl_create_table/#deferrable-constraints) subsection:

> Constraints can be deferred using the `DEFERRABLE` clause. Currently, only foreign key constraints can be deferred in YugabyteDB... In the case of deferrable constraints, the checking of the constraint can be postponed until the end of the transaction... Constraints marked as `INITIALLY DEFERRED` will be checked at the end of the transaction.

This is at odds with what this issue shows. Deferred FK constraints show buggy behavior.

### Testcase

It turns out that _four_ distinct degrees of freedom determine the outcome. Each has two choices.

- YB _versus_ PG
- _optional_ one-to-one _versus_ _mandatory_ one-to-one
- _explicitly_ populated PK _versus_ automatically _generated_ PK
- pure _SQL_ implementation _versus_ _PL/pgSQL_ implementation

This code tests all _sixteen_ of the combinations. The outcomes are easily summarized thus:

- Every one of the _eight_ tests runs without error in PG and produces the expected results. Only _five_ of the _eight_ tests run faultlessly in YB. Of the remainder, _one_ pure _SQL_ tests brings a nonsensical error. And _two_ _PL/pgSQL_ tests cause drastic errors and the loss of the server connection.

The YB faults occur only with the _generated_ PK implementation. This differs from the implementation where the PKs are set _explicitly_, in that in the _generated_ case, the _inserts_ into each of the _mains_ and _extras_ tables use the _returning_ clause to discover the _generated_ PK values. The faulty cases are summarized thus:

````
               |  pure SQL                            |  PG/pgSQL        |
--------------------------------------------------------------------------
 optional 1:1  |  OK                                  |  faulty (crash)  |
---------------|----------------------------------------------------------
mandatory 1:1  |  faulty (nonsensical error message)  |  faulty (crash)  |
--------------------------------------------------------------------------
````

The error messages are reproduced below.

### Code organization

The attached [issue-13009.zip](https://github.com/yugabyte/yugabyte-db/files/8963777/issue-13009.zip) contains this file hierarchy:

```
optional-and-mandatory-one-to-one
├── 10-set-up-optional-with-explicit-pk.sql
├── 11-optional-with-explicit-pk-good
│   ├── 1-pure-sql.sql
│   ├── 2-plpgsql.sql
│   └── create-plpgsql-code.sql
├── 20-set-up-mandatory-with-explicit-pk.sql
├── 21-mandatory-with-explicit-pk-good
│   ├── 1-pure-sql.sql
│   ├── 2-plpgsql.sql
│   └── create-plpgsql-code.sql
├── 30-set-up-optional-with-generated-pk.sql
├── 31-optional-with-generated-pk-bad-only-in-plpgsql
│   ├── 1-pure-sql.sql
│   ├── 2-plpgsql.sql
│   └── create-plpgsql-code.sql
├── 40-set-up-mandatory-with-generated-pk.sql
├── 41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql
│   ├── 1-pure-sql.sql
│   ├── 2-plpgsql.sql
│   └── create-plpgsql-code.sql
├── do-mains-inner-join-extras.sql
└── do-mains-outer-join-extras.sql
```

Each of the combinations of:

- _optional_ or _mandatory_ for the kind of one-to-one relationship

with

- _explicit_ or _generated_ for how the PK is set

has its own appropriately named directory. And each has its own correspondingly-named script to create the tables. Use your favorite GUI diff tool to compare them pairwise. They differ only on the lines marked in the _optional_-_generated_ script shown above at the three lines marked with trailing comments.

The directory for each of the four table creation variants has a set of three files with the same names. Use the GUI diff tool, again, to compare each same-named pair across the directories.

##### 1-pure-sql.sql

This invokes the appropriate _set-up_ script and inserts a few rows within a transaction bounded by _start transaction_ and _commit_. The method is appropriate to the variant that the directory name expresses.
- In the two _optional_ cases, a row that has just a _mains_ row (with no partner _extras_ row) is inserted to prove the point. (Such a singleton is not allowed in the _mandatory_ case.)
- In the two cases where the PK is set _explicitly_, the approach is straightforward: manually determined unique values are used for the PKs—and these are used explicitly to set the FKs. In the two cases where the PK is _generated_, the approach is extended appropriately: first the _mains_ row is inserted (using a placeholder value for the FK to its still-to-be-inserted _extras_ partner). The _returning_ clause allows the generated PK value to be stored locally and used when the _extras_ partner is inserted. And the _returning_ clause here allows the generated PK value to be stored locally and used to revisit the _mains_ row and set its FK to its _extras_ partner properly.

Here, the` \gset`  metacommand is used to store values from the _returning_ clause as _psql_ "substitution directives"—then to be accessed using the _colon prefix_ notation.

##### create-plpgsql-code.sql

This creates a _do_inserts()_ procedure that, for each variant, does exactly what its pure _SQL_ partner does. But the coding is less obscure because ordinary _PG/plSQL_ variables are used instead of _psql colon-prefixed substitution directives_.

It also creates a _delete_outcome()_ function that, as just a sanity test, confirms that decorating the _mains_ FK with _"on delete restrict_" and decorating the _extras_ FK with _"on delete cascade_" meets the business requirements.

##### 2-plpgsql.sql

This invokes the appropriate _set-up_ script, invokes _create-plpgsql-code.sql_, and then invokes _do_inserts()_ a few times and then _delete_outcome()_ a few times.

### Vanilla PG results

Run the eight scripts (_1-pure-sql.sql_ and _2-plpgsql.sql_ on each of the four directories using vanilla PG to produce the following reference output.

##### 11-optional-with-explicit-pk-good

```
    For 1-pure-sql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 0 | main-0    | 
 1 | main-1    | extra-1
 2 | main-2    | extra-2
 3 | main-3    | extra-3
 
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
    For 2-plpgsql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-1    | 
 2 | main-2    | extra-2
 3 | main-3    | extra-3

 "foreign_key_violation" handled as expected

 k | main_fact | extra_fact 
---+-----------+------------
 3 | main-3    | extra-3
```

##### 21-mandatory-with-explicit-pk-good

```
    For 1-pure-sql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-1    | extra-1
 2 | main-2    | extra-2
 3 | main-3    | extra-3
 
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
    For 2-plpgsql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-1    | extra-1
 2 | main-2    | extra-2
 3 | main-3    | extra-3

 "foreign_key_violation" handled as expected

 k | main_fact | extra_fact 
---+-----------+------------
 3 | main-3    | extra-3
```

##### 31-optional-with-generated-pk-bad-only-in-plpgsql

```
    For 1-pure-sql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-0    | 
 2 | main-1    | extra-1
 3 | main-2    | extra-2
 4 | main-3    | extra-3
 
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
    For 2-plpgsql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 insert OK

 insert OK

 insert OK

 insert OK

 foreign_key_violation on insert

 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-0    | 
 2 | main-1    | extra-1
 3 | main-2    | extra-2
 4 | main-3    | extra-3

 delete OK

 delete OK

 foreign_key_violation on delete

 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-0    | 
 4 | main-3    | extra-3
```

##### 41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql

```
    For 1-pure-sql.sql
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-1    | extra-1
 2 | main-2    | extra-2
 3 | main-3    | extra-3
 
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
    For 2-plpgsql.sql
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 insert OK

 insert OK

 insert OK

 foreign_key_violation on insert

 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-1    | extra-1
 2 | main-2    | extra-2
 3 | main-3    | extra-3

 delete OK

 delete OK

 foreign_key_violation on delete

 k | main_fact | extra_fact 
---+-----------+------------
 3 | main-3    | extra-3
```

### Yugabyte DB results

Now run the eight scripts (_1-pure-sql.sql_ and _2-plpgsql.sql_ on each of the four directories using YugabyteDB. As mentioned, five of the scripts produce identical results in YB as in PG—so they aren't reproduced here. Only the results of the three faulty scripts are shown.

##### 31-optional-with-generated-pk-bad-only-in-plpgsql

```
    For 2-plpgsql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
ERROR:      XX000: could not find block containing chunk 0x11206f028
LOCATION:   AllocSetFree, aset.c:1026
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
  connection to server was lost
```
Step through _2-plpgsql.sql_ by hand. The error occurs here:

```
select insert_outcome('main-1', 'extra-1', 'good')  /*** Fails here on YB with fatal crash ***/;
```

This is the first invocation of _insert_outcome()_ that uses two _select_ statements with the _returning_ clause and then _update_ to the _mains_ table using the returned values.

##### 41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql

```
    For 1-pure-sql.sql
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 k | main_fact | extra_fact 
---+-----------+------------
 1 | main-1    | extra-1
 2 | main-2    | extra-2
 3 | main-3    | extra-3
```

So far so good. But when you step through _1-pure-sql.sql_ by hand, you'll see that the _inner join_ query to show the results is invoked _before_ the _commit_ that ends the transaction. When you issue _commit_, you'll see this error:

```
ERROR:   23503: insert or update on table "mains" violates foreign key constraint "mains_fk"
DETAIL:  Key (extras_k)=(0) is not present in table "extras".
SCHEMA NAME:  u1
TABLE NAME:  mains
CONSTRAINT NAME:  mains_fk
LOCATION:  ri_ReportViolation, ri_triggers.c:2887
```

This is clearly at odds with what the _inner join_ query showed just before you issued  _commit_.

```
    For 2-plpgsql.sql
    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
ERROR:      XX000: could not find block containing chunk 0x11206f028
LOCATION:   AllocSetFree, aset.c:1026
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
  connection to server was lost
```
Step through _2-plpgsql.sql_ by hand. The error occurs here:

```
select insert_outcome('main-1', 'extra-1', 'good')  /*** Fails here on YB with fatal crash ***/;
```

just as it did with the corresponding script on the _31-optional-with-generated-pk-bad-only-in-plpgsql_ directory. Notice that the wording of the crash report is the same.

[DB-2726]: https://yugabyte.atlassian.net/browse/DB-2726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DB-2213]: https://yugabyte.atlassian.net/browse/DB-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bllewell** [comment]
Here's a much shorter, self-contained, testcase. It produces what looks like the same crash as does the _issue-13009.zip_ testcase. But, different from that, it's the use of _"set constraints all immediate"_ that provokes the crash.

First, create a flavor of the _"mandatory one-to-many"_ setup. Here one among the many _details_ rows must have the special status that it's the parent for the _masters_ row that has these many details:

```
create table masters(
  id          int   primary key,
  details_id  int   not null,
  v           text  not null);

create table details(
  id          int primary key,
  masters_id  int,
  v           text not null,
  constraint details_fk foreign key(masters_id) references masters(id));

alter table masters add
  constraint masters_fk foreign key(details_id) references details(id)
  initially deferred;
```

The _masters_fk_ constraint must be _"initially deferred"_ to allow the bootstrap: you must insert a new _masters_ row and its minimal one _details_ row in a single transaction. This _do_ block inserts two _masters_ rows with two _details_ rows for each. Notice that the PK and FK values are set explicitly. (This makes the demo code as short as possible.)

```
do $body$
begin
  insert into masters values(10, 1, 'master one');
  insert into details values(1, 10, 'detail one');
  insert into details values(2, 10, 'detail two');

  insert into masters values(20, 3, 'master two');
  insert into details values(3, 20, 'detail three');
  insert into details values(4, 20, 'detail four');
end;
$body$;
```

Check the outcome thus:

```
select
  m.v                           as masters,
  array_agg(d.v order by d.id)  as details
from
  masters m
  left outer join
  details d
  on d.masters_id = m.id
group by m.id
order by m.id;
```

The query uses _array_agg()_ to make it easier to see at a glance which _details_ rows, and how many of them, belong to each _masters_ row. Save the query as _qry.sql_ for re-use.

This is the result:

```
  masters   |            details             
------------+--------------------------------
 master one | {"detail one","detail two"}
 master two | {"detail three","detail four"}
```

Now delete the "special" _details_ row _"detail one"_. It's special because its both a child of _"masters one"_ and its parent. This means that the remaining child of _"masters one"_, _"detail two"_, must become its new parent.

```
do $body$
begin
  delete from details
  where v = 'detail one';

  update details set id = (select details_id from masters where v = 'master one')
  where v = 'detail two';
end;
$body$;
```

The logic that this block uses isn't general. It relies on the human insight that the to-be-deleted _"detail one"_ is indeed the parent of _"master one"_. But it indicates how you could generalize the code to detect when the to-be-deleted _details_ row is the parent of its  own _masters_ parent.

It finishes without error—thanks to the _"initially deferred"_ status of _masters_fk_. Check the outcome with _\ir qry.sql_. this is the new result, as intended:

```
  masters   |            details             
------------+--------------------------------
 master one | {"detail two"}
 master two | {"detail three","detail four"}
```

Now attempt to violate the _"mandatory one-to-many"_ rule:

```
do $body$
begin
  delete from details
  where masters_id = (select id from masters where v = 'master one');

  set constraints all immediate;
exception when foreign_key_violation then
  declare
    msg text not null := '';
  begin
    get stacked diagnostics msg = message_text;
    raise info '%', msg;
  end;
end;
$body$;
```

Notice the use of _"set constraints all immediate;"_. Without this, the error happens at "commit" and is therefore unhandleable. But with this approach, the _"set constraints"_ causes the error. This allows it to be handled. However, using YB-2.15.0.1, this approach causes a fatal crash.

Try it first using vanilla PG. The _foreign_key_violation_ error is handled. And _"raise info"_ outputs this:

```
update or delete on table "details" violates foreign key constraint "masters_fk" on table "masters"
```

Now try it using YB-2.15.0.1. This is the outcome:

```
ysqlsh:demo.sql:75: INFO:  update or delete on table "details" violates foreign key constraint "masters_fk" on table "masters"
ysqlsh:demo.sql:75: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
ysqlsh:demo.sql:75: connection to server was lost
```

This seems to be the same error that was reported using the _issue-13009.zip_ testcase.

Commenting out _"set constraints all immediate;"_ (and re-establishing the context for executing the block) allows it to execute without a crash. But it brings the severe penalty that the _foreign_key_violation_ error cannot be handled—in other words, you can't report the outcome to the client as an ordinary return status using a procedure's _inout_ argument.

**Comment by bllewell** [comment]
@m-iancu, could you please as somebody to look at this—at least to see if it's obvious what the problem is? Notice the x-ref, above, to Issue #3995 which was closed by @d-uspenskiy—claiming that deferred FKs are working! Notice, too, the x-ref to Issue #4700—which also claims that deferred FKs are working!

**Comment by m-iancu** [comment]
Could not repro this FATAL issue locally. I tried multiple versions from 2.13 to 2.19, also testing on Mac as well.
However, the main example did find a real bug which is detailed in https://github.com/yugabyte/yugabyte-db/issues/17657.
This causes the results for `31-optional-with-generated-pk-bad-only-in-plpgsql/2-plpgsql.sql` and `41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql` to differ from Postgres.

Will track that issue separately, but keeping this open until we confirm the full example works correctly.

**Comment by foucher** [comment]
I spent some time figuring out the current status on the master branch. I'm unable to reproduce the FATAL issue locally using the repro in the comment, or using the scripts is the original report. I believe the remaining problems are all covered by #17657. Details below.

Regarding running the scripts, I think the proper sequence has a few more setup steps:
```
./bin/ysqlsh
\cd ../../issue-13009 
\i 10-set-up-optional-with-explicit-pk.sql
\cd 11-optional-with-explicit-pk-good
\i create-plpgsql-code.sql
\i 1-pure-sql.sql
\i 2-plpgsql.sql
\cd ../21-mandatory-with-explicit-pk-good
\i create-plpgsql-code.sql
\i 1-pure-sql.sql
\i 2-plpgsql.sql
\cd ../31-optional-with-generated-pk-bad-only-in-plpgsql
\i create-plpgsql-code.sql
\i 1-pure-sql.sql
\i 2-plpgsql.sql
\cd ../41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql
\i create-plpgsql-code.sql
\i 1-pure-sql.sql
\i 2-plpgsql.sql
```

I'm comparing the output to that of PG 14, the version that happens to be on my computer. I think it's good enough because it all looks like issue #17657.

The file `31-optional-with-generated-pk-bad-only-in-plpgsql/2-plpgsql.sql` has 3 extra of the following:
```
foreign_key_violation on insert
```

It's also **missing** a similar message for a delete, but maybe because of the prior errors. This one is probably #17657. According to the original report, this had a fatal crash previously.

There is an error in `41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql/1-pure-sql.sql`:
```
ERROR:  insert or update on table "mains" violates foreign key constraint "mains_fk"
DETAIL:  Key (extras_k)=(0) is not present in table "extras".
```
This is reported by Bryn in the script file, in a comment, verbatim with what I'm seeing. I think this is also #17657.

The file `41-mandatory-with-generated-pk-bad-in-both-sql-and-plpgsql/2-plpgsql.sql` also has 3 extra
```
foreign_key_violation on insert
```

It's also **missing** a similar message for a delete, but maybe because of the prior errors. This is also probably #17657. According to the original report, this had a fatal crash previously.
