### ISSUE TITLE
[docs][CDCSDK] Documentation addition for CDC

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#13012]
Jira Link: [DB-2729](https://yugabyte.atlassian.net/browse/DB-2729)
This is to track the requests to add/modify documentation related to the Debezium YugabyteDB Connector as well as general CDC related stuff. Please drop in a comment if you see anything missing or have a request to add something to our public docs.

Change Data Capture: https://docs.yugabyte.com/preview/explore/change-data-capture/

**Comment by arpang** [comment]
1. Added support for Enum user-defined types. Enum arrays are not supported.

**Comment by vaibhav-yb** [comment]
2. Add description for what happens if the SMT `YBExtractNewRecordState` is used on the source side vs what happens if we do not specify it.
