### ISSUE TITLE
[YSQL] Add metric for rejected connections due to CAC_TOOMANY

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#13017]
Jira Link: [DB-2734](https://yugabyte.atlassian.net/browse/DB-2734)
### Description

Track rejected connection due to max_connection limit reached and push them to prometheus.

**Comment by tedyu** [comment]
Currently `RegisterRpczEntries` is called by `webserver_worker_main`.

Connection rejection is handled in `ProcessStartupPacket`.

Trying to figure out how to hook up connection rejection with the other rpcz entries.

**Comment by tedyu** [comment]
We also need to decide how many counters are introduced for this issue.

Here are the reason codes for rejected connection:

CAC_STARTUP
CAC_SHUTDOWN
CAC_RECOVERY
CAC_TOOMANY
CAC_WAITBACKUP

If one counter is introduced, it may not convey the whole picture for rejected connections.

**Comment by tedyu** [comment]
[rejected-conn-metric.txt](https://github.com/yugabyte/yugabyte-db/files/9500124/rejected-conn-metric.txt)

**Comment by tedyu** [comment]
[rejected-conn-metric.txt](https://github.com/yugabyte/yugabyte-db/files/9500476/rejected-conn-metric.txt)

**Comment by SteveXiSong** [comment]
The approach looks good to me. BTW, I guess you should not declare the var `too_many_conn` to be static.
