### ISSUE TITLE
[DocDB] splitting: Incorrect split_encoded_key re-compute in case of child tablet already registered

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#13027]
Jira Link: [DB-2743](https://yugabyte.atlassian.net/browse/DB-2743)
### Description

The issue is related to #8148

There is a code path to re-compute `split_encoded_key` if the splitting was failed in the middle and is trying to continue when at least one child tablet already registered: https://github.com/yugabyte/yugabyte-db/blob/2e8c2fce3c6af3f967bf597ac2c44b004d9cf863/src/yb/master/catalog_manager.cc#L2699
Due to the chain of calls inside the method, one more byte `KeyEntryType::kGroupEnd` is appended to the end of hash value
```
void AppendDocKeyItems(const Collection& doc_key_items, KeyBytes* result) {
  for (const auto& item : doc_key_items) {
    item.AppendToKey(result);
  }
  result->AppendGroupEnd();
}
```
but `split_encoded_key` for hash partitioned tablets as well as hash value does not contain this `kGroupEnd` byte.

Looks like this inconsistency is not leading to any issue due to `kGroupEnd` is less then the most of key-types that can potentially follow hash column in a primary key, but the inconsistency is still potentially unsafe in terms of `key_bounds` creation and rocksdb iteration.

confirmed with @ttyusupov

**Comment by rthallamko3** [comment]
@arybochkin , Can we resolve this defect now?

**Comment by arybochkin** [comment]
@rthallamko3 sure, closing
