### ISSUE TITLE
[DocDB] "ntp package missing. We recommend installing ntp package." Centos8 Post Chrony

### ISSUE THREAD

**Issue by WarrenN1** [yugabyte/yugabyte-db#13035]
Jira Link: [DB-2765](https://yugabyte.atlassian.net/browse/DB-2765)
### Description

Centos8 moved to chrony over NTP. The problem is that after installing YugabyteDB and the chrony package as well as starting the chrony service, YugabyteDB still throws the following warning:
```
⚠ WARNING System checks. Following pre-reqs are not met:
- ntp package missing. We recommend installing ntp package.
```
1. How do I solve this problem and
2. Can the docs be updated to reflect this.

**Comment by ddorian** [comment]
@WarrenN1 this is when running `yugabyted` cli, correct?

**Comment by WarrenN1** [comment]
I follow the startup guide exactly. I run ./bin/yugabyted start and it starts the daemon.

**Comment by ddorian** [comment]
Note that this is only a warning. 
You can continue using it. 
We'll keep this issue open to fix the warning.

**Comment by nchandrappa** [comment]
We have made the necessary changes to validating framework. Yugabyted displays the following message when `ntp/chrony` packages are missing - 

```
ntp/chrony package is missing for clock synchronization. For centos 7, 
we recommend installing either ntp or chrony package and for centos 8, 
we recommend installing chrony package.
```

**Comment by LennyLip** [comment]
I've got the same issue (docker image image: yugabytedb/yugabyte:2.23.1.0-b220 ) and look like it do not work without ntp/chrony package. I got erros in tserver FATAL logs:
`Too big clock skew is detected`
and 5433 connection just drops long sql request (DB tables structure in my case).

start command like in docs:
```
bin/yugabyted start \
 --background=false
```

**Comment by LennyLip** [comment]
looks like thew same issue. any reason we do not have chrony in docker image?  https://support.yugabyte.com/hc/en-us/articles/4403707404173-Too-big-clock-skew-leading-to-error-messages-or-tserver-crashes

**Comment by ddorian** [comment]
@LennyLip NTP/chrony is better to be enabled on the host (once for all containers). 

Hugepages also needs to be enabled on the host.
