### ISSUE TITLE
[DocDB] Provide guidance on tablet splitting gflags for customers that will be using automatic_tablet_splitting

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#13047]
Jira Link: [DB-2773](https://yugabyte.atlassian.net/browse/DB-2773)
### Description

Provide documentation/guidance on tablet splitting gflags for customers that will be using automatic_tablet_splitting. Areas that are of interest:
1. Number of tablets per table (If automatic_tablet_splitting is true, this value is set to 1).
2. Split size threshold.

Other gflags that need fine tuning.

tablet_split_low_phase_shard_count_per_node = 8
tablet_split_high_phase_shard_count_per_node = 24
tablet_split_low_phase_size_threshold_bytes = 512_MB
tablet_split_high_phase_size_threshold_bytes = 10_GB
tablet_force_split_threshold_bytes = 500_GB

**Comment by rthallamko3** [comment]
Slack thread discussing the issue: https://yugabyte.slack.com/archives/C01HD5HPK8A/p1633542837254700

**Comment by ttyusupov** [comment]
Related blog post: https://www.yugabyte.com/blog/distributed-sql-sharding-how-many-tablets-size/
