### ISSUE TITLE
[DocDB] Add metrics to the RBS code path 

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#13051]
Jira Link: [DB-2776](https://yugabyte.atlassian.net/browse/DB-2776)
### Description

Add metrics for the time spent in RBS as well as the CRC checksum validation part, if the CRC time is a big factor of the total time for RBS, then potentially skip the CRC checksum as the tablet bootstrap will eventually do the validation.

**Comment by rthallamko3** [comment]
@basavaraj29 , Ping Bogdan/Amit for more details as necessary.

**Comment by bmatican** [comment]
@karan-yb , this is slightly more meaty work, can sync with Amit for more info and code pointers.
We'll also need a bit more data loaded into the cluster, in order to see the effects of the remote bootstrap and cost of checksuming.
