### ISSUE TITLE
[Packed Columns] Observed Fatal logs after Nodeops on Universe

### ISSUE THREAD

**Issue by shashwat-yb** [yugabyte/yugabyte-db#13061]
Jira Link: [DB-2785](https://yugabyte.atlassian.net/browse/DB-2785)
### Description

Fatal logs on db master nodes post Nodeops on Universe.

Master Fatals -
`F0624 10:30:21.218115 18603 master_main.cc:127] Illegal state (yb/master/catalog_manager.cc:1727): Unable to initialize catalog manager: Failed to initialize sys tables async: None of the local addresses are present in master_addresses 10.200.0.55:7100,10.200.0.73:7100,10.200.0.77:7100.`

Master Error -
`E0624 10:30:21.217751 18622 master.cc:301] Master@10.200.0.51:7100: Unable to init master catalog manager: Illegal state (yb/master/catalog_manager.cc:1727): Unable to initialize catalog manager: Failed to initialize sys tables async: None of the local addresses are present in master_addresses 10.200.0.55:7100,10.200.0.73:7100,10.200.0.77:7100.
F0624 10:30:21.218115 18603 master_main.cc:127] Illegal state (yb/master/catalog_manager.cc:1727): Unable to initialize catalog manager: Failed to initialize sys tables async: None of the local addresses are present in master_addresses 10.200.0.55:7100,10.200.0.73:7100,10.200.0.77:7100.`

Master Fatal Details -
`F20220624 09:13:56 ../../src/yb/master/master_main.cc:127] Illegal state (yb/master/catalog_manager.cc:1727): Unable to initialize catalog manager: Failed to initialize sys tables async: None of the local addresses are present in master_addresses 10.200.0.55:7100,10.200.0.73:7100,10.200.0.77:7100.
    @     0x7f864a6d6e1c  google::LogDestination::LogToSinks()
    @     0x7f864a6d6844  google::LogMessage::SendToLog()
    @     0x7f864a6d7fd8  google::LogMessage::Flush()
    @     0x7f864a6d87bf  google::LogMessageFatal::~LogMessageFatal()
    @           0x205c35  main
    @     0x7f8648107825  __libc_start_main
    @           0x204e99  _start`

Steps to reproduce -
1. Create Universe
2. Nodeops - remove/release/add
3. Check for fatal logs

**Comment by bmatican** [comment]
@shashwat-yb This seems like a configuration issue
> None of the local addresses are present in master_addresses 10.200.0.55:7100,10.200.0.73:7100,10.200.0.77:7100.
Are you running some itest with packed columns on vs off and this is only failing with the feature on?

**Comment by shashwat-yb** [comment]
yes @bmatican , we observed this issue while running iTest with [D17678](https://phabricator.dev.yugabyte.com/D17678) where we are trying to set packed columns gflags explicitly for all testcases.
