### ISSUE TITLE
[UI] [yugabyted] Failed to extract Yugabyted UI binaries

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#13076]
### Description

When starting `yugabyted start --ui true` the UI is not started, showing the following error

```
Run 'yugabyted [command] -h' for help with specific commands.
sh-4.2# yugabyted start --ui true
ERROR:root: | 4.6s | Failed to extract Yugabyted UI binaries: [Errno 2] No such file or directory: u'/home/yugabyte/bin/yugabyted-ui-1.0.0-linux-x86_64.tar.gz'
WARNING: UI disabled - Unable to download ui binaries.
Starting yugabyted...
```

Cause:
2.15 `yugabyted --ui true` downloads the yugabyted-ui tar in current directory ([here](https://github.com/yugabyte/yugabyte-db/blob/2.15.0/bin/yugabyted#L1818)) but untars it from the bin directory ([here](https://github.com/yugabyte/yugabyte-db/blob/2.15.0/bin/yugabyted#L1829))

Workaround:
Start from the bin directory: `( cd $(dirname $(which yugabyted)) && yugabyted start )`

**Comment by nchandrappa** [comment]
We don't download binaries any more, we are bundling the UI binaries along with the YugabyteDB binaries.
