### ISSUE TITLE
Jepsen failure scenarios - implement multiple faults

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#131]
Multiple failures are introduced into the cluster, without violating the fault-tolerance configuration. This may involve introducing more than one single faults in a multi-zone configuration:
- Two nodes in a zone for a multi-zone configuration
- Entire zone failure

**Comment by ttyusupov** [comment]
Commited - https://github.com/YugaByte/jepsen/commit/9ae2b18fe0f305a3c99da2038ebf5b9f86e26143

**Comment by ttyusupov** [comment]
Support for multiple nemeses was implemented in original Jepsen repo: https://github.com/jepsen-io/jepsen/commit/b6d1b632f68273dd0b7c435db248ff692026bc4b
