### ISSUE TITLE
[YCQL] TestExplainPlan.testSelectPlanWithBindVars fails with `Range Scan`

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#13105]
Jira Link: [DB-2814](https://yugabyte.atlassian.net/browse/DB-2814)
### Description

The test failure can be reproduced locally:
```
[ERROR]   TestExplainPlan.testSelectPlanWithBindVars:115->BaseCQLTest.assertQuery:583->BaseCQLTest.assertQuery:579 expected:<Row[[Index Scan using imdb.best_rated on imdb.movie_stats               ]Row[  Key Conditions: (user_rank = :5) AND (movie_genre = :movie_genre)]]> but was:<Row[[Range Scan on imdb.movie_stats                ]Row[  Key Conditions: (movie_genre = :movie_genre)]Row[  Filter: (user_rank = :5)                    ]]>
```

Seel also https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F205283%2Fartifact%2Fjava%2Fyb-cql%2Ftarget%2Fsurefire-reports_org.yb.cql.TestExplainPlan__testSelectPlanWithBindVars%2Forg.yb.cql.TestExplainPlan-output.txt.gz?class=org.yb.cql.TestExplainPlan&name=testSelectPlanWithBindVars

**Comment by tedyu** [comment]
Without commit 148d251ea3dfa289b9341f13cae96d1f900c2531, the test passes.

cc @amitanandaiyer

**Comment by m-iancu** [comment]
Seems to be fixed in latest based on the stability report: https://detective-gcp.dev.yugabyte.com/stability?num_commits=25. Closing.
