### ISSUE TITLE
Create Domain statement is not supported 

### ISSUE THREAD

**Issue by dodilp** [YugaByte/yugabyte-db#1310]
[root@yb-tserver-n1 AdventureWorksDemo]# ../../../yugabyte/postgres/bin/psql -h yb-tserver-n1 -U postgres -f install.sql AdventureWorks
psql:install.sql:62: ERROR:  CREATE DOMAIN not supported yet
LINE 1: CREATE DOMAIN "OrderNumber" varchar(25) NULL;
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues

**Comment by kmuthukk** [comment]
hi @dodilp -

We currently haven't enabled support for this yet. We'll discuss internally and figure out what/when we'll be able to enable this feature. 

regards,
Kannan

**Comment by kmuthukk** [comment]
hi @dodilp - this feature (support for DOMAIN) is in testing now. We hope to land the feature pretty soon.

**Comment by rahuldesirazu** [comment]
Implemented in fa96c6126e299449178ec45db2bd9dc3fe09b3ad.

**Comment by ndeodhar** [comment]
Hi @dodilp, this feature is now available in 1.2.9 version. You can get it using:
`docker pull yugabytedb/yugabyte:1.2.9.0-b14` for Docker or
`wget https://downloads.yugabyte.com/yugabyte-ce-1.2.9.0-darwin.tar.gz` for Mac or
`wget https://downloads.yugabyte.com/yugabyte-ce-1.2.9.0-linux.tar.gz` for Linux

**Comment by dodilp** [comment]
Thank you, @ndeodhar
