### ISSUE TITLE
[DocDB] Fix DoSplitTablet deadlock

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#13102]
Jira Link: [DB-2812](https://yugabyte.atlassian.net/browse/DB-2812)
### Description

We have a deadlock when registering new tablets. We should be locking in the following order:
 1. Catalog manager
 2. Any tables (ordered by id)
 3. Any tablets (ordered by id)

But we are currently locking the table and tablet first in `RegisterNewTabletForSplit`, then locking the catalog manager mutex.

This is causing `AutomaticTabletSplitITest.PrioritizeLargeTablets` and `CqlTabletSplitTest.SecondaryIndex` to fail occasionally.

**Comment by rthallamko3** [comment]
@SrivastavaAnubhav , Are we tracking additional fixes in the area? Would Timur's fixes be sufficient?

**Comment by SrivastavaAnubhav** [comment]
I have a diff out for this. It's been stuck in review for a while but I'm unblocked now so I should be able to get it in soon.
