### ISSUE TITLE
[CDCSDK] Transaction Intent loss after restart and compaction

### ISSUE THREAD

**Issue by adithya-yb** [yugabyte/yugabyte-db#13146]
Currently for tablets which have an active CDC stream, we do not directly remove the intents of an already committed transaction from Intents DB. But rather push it to the “immediate_cleanup_queue_” in TransactionParticipant. And when the cdcsdk checkpoint OpId becomes greater than the transaction’s appl record OpId, its intents get removed. 

But after any restart, if a compaction is triggered, we will call the below function: 

void TransactionParticipant::Cleanup(TransactionIdSet&& set)

Below is the function which decides which transactions we will try to abort after compaction:

Result<boost::optional<TransactionId>> DocDBIntentsCompactionFilter::FilterTransactionMetadata(
    const Slice& key, const Slice& existing_value) {
  TransactionMetadataPB metadata_pb;
  if (!metadata_pb.ParseFromArray(existing_value.cdata(), existing_value.size())) {
    return STATUS(IllegalState, "Failed to parse transaction metadata");
  }
  uint64_t write_time = metadata_pb.metadata_write_time();
  if (!write_time) {
    write_time = HybridTime(metadata_pb.start_hybrid_time()).GetPhysicalValueMicros();
  }
  if (compaction_start_time_ < write_time + FLAGS_aborted_intent_cleanup_ms * 1000) {
    return boost::none;
  }
  Slice key_slice = key;
  return VERIFY_RESULT_PREPEND(
      DecodeTransactionIdFromIntentValue(&key_slice), "Could not decode Transaction metadata");
}

As we can see, if write_time is very old (which can happen for transactions whose intents we have kept around for CDC), this will be part of the set sent to “TransactionParticipant::Cleanup”.

The Cleanup task eventually triggers: “CleanupAbortsTask::Run()” , which further calls “FilterTransactions()”. 
Below is the part of FilterTransactions which is supposed to filter out committed transactions, but this is not working after restarts.

// If transaction is committed, no action required
   auto commit_time = status_manager_.LocalCommitTime(transaction_id);
   if (commit_time.is_valid()) {
     auto warning_time = commit_time.AddMilliseconds(FLAGS_aborted_intent_cleanup_ms);
     if (now >= warning_time) {
       LOG_WITH_PREFIX(WARNING)
           << "Transaction Id: " << transaction_id << " committed too long ago.";
     }
     VLOG_WITH_PREFIX(2) << "Transaction committed, should not cleanup: " << transaction_id;
     erased_transactions_.push_back(transaction_id);
     --left_wait;
     continue;
   }

Thus as part of the fix, we introduced an OpId based check in this function: “FilterTransactions()” as well. We will now filter transactions whose APPLY Record’s OpID is lower than the CDCSDK checkpoint OpId.

**Comment by suranjan** [comment]
I think it is fixed, please close

**Comment by adithya-yb** [comment]
Landed in 2.12, 2.12.4, 2.14, 2.15
