### ISSUE TITLE
[Docs] Command blocks take multiple lines

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13155]
### Description

The commands look a bit strange here, I guess that’s a regression in the new design: https://docs.yugabyte.com/preview/migrate/manual-import/import-data/

With Firefox on macOS
![Screenshot 2022-07-05 at 18 02 30](https://user-images.githubusercontent.com/2335377/177381252-b076717d-91d3-4f49-81f7-8e993a1b8ba0.png)

**Comment by vkulichenko** [comment]
Here is another example (MacOS, Safari): https://deploy-preview-12764--infallible-bardeen-164bc9.netlify.app/preview/manage/backup-restore/point-in-time-recovery/#global-objects

<img width="1585" alt="Screen Shot 2022-07-05 at 10 58 52 AM" src="https://user-images.githubusercontent.com/1393668/177388063-68f3544b-662b-40a3-8fc7-6f4b768e6d2a.png">

**Comment by polarweasel** [comment]
We can't repro this so far. Working on it...

**Comment by def-** [comment]
![Screenshot 2022-07-06 at 01 08 12](https://user-images.githubusercontent.com/2335377/177431433-7398f5e5-7ec0-4ceb-8300-7b28683e380f.png)
If I remove the `overflow: auto` for `.td-content code` it looks fine for me:
![Screenshot 2022-07-06 at 01 09 05](https://user-images.githubusercontent.com/2335377/177431492-869742f7-80ed-41eb-b866-1cfb9ac0eee0.png)

**Comment by def-** [comment]
Yes, that looks fine.
