### ISSUE TITLE
[Docs] There is a Toggle switch to change the default color

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#13165]
### Description

There is an unnamed switch to change the color from blue to orange. I like it but i think it was added by mistake. It does not seem to do anything on the mobile site.

![image](https://user-images.githubusercontent.com/12418230/177434409-017e3e07-ffc4-4b8f-96b8-3bdfdfdc76e6.png)

**Comment by polarweasel** [comment]
That's a feature, not a bug...
