### ISSUE TITLE
[CDCSDK] CDC does not support adding new table columns

### ISSUE THREAD

**Issue by cdavid** [yugabyte/yugabyte-db#13201]
User creates a table
User creates a CDC stream that involves that table
User adds column to table (ALTER TABLE ADD COLUMN)

Expected:
CDC data now contains the new column

Reality:
CDC data does not contain the new column

**Comment by suranjan** [comment]
Please close it as duplicate and is already supported in 2.16

**Comment by sureshdash2022-yb** [comment]
As part of diff https://phabricator.dev.yugabyte.com/D19696 we have fixed this issue.
