### ISSUE TITLE
[DocDB] Reduce frequency/criticality of "log.cc:967] Time spent Fsync log took a long time" lines

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#13203]
Jira Link: [DB-2875](https://yugabyte.atlassian.net/browse/DB-2875)
### Description

1. Downgrade to INFO
2. use LOG_EVERY_N/sec of sorts

since this is indicative of a general slow-down and not just a specific rpc issue. We don't have to log it for every write-rpc that gets slowed down

**Comment by basavaraj29** [comment]
merged the [fix](https://github.com/yugabyte/yugabyte-db/commit/41ecfe62b5d50f0b11927d4e0380f9cbbda83a89), closing this issue.
