### ISSUE TITLE
[YSQL]  issues altering the partitioned table with 30+ Million data 

### ISSUE THREAD

**Issue by codesnail21** [yugabyte/yugabyte-db#13229]
Jira Link: [DB-2891](https://yugabyte.atlassian.net/browse/DB-2891)
### Issue

`SQL Error [XX000]: ERROR: Invalid argument: Invalid column number 16`

- I have partitioned the database based on `date` and around 15 Columns and I'm not able to alter the table on the large data set.
- In local of around 1000 rows of data I am able to alter the partitioned table, But in production, I have more than 25-30 million data of **a single day.**
- Actually in the case of production when I apply migration the `select *` query is also not working, but when I apply for the specific columns then I got the result though the added column is also not able to access.

 
- Here are my screenshots regarding that. ( BELOW SS SHOWS THE TEST IN LOCAL ) 
- ACTUAL IN PRODUCTION -> `SQL Error [XX000]: ERROR: Invalid argument: Invalid column number 16`

![image](https://user-images.githubusercontent.com/87218847/178242021-77a75e32-fe41-4d5b-b539-fb7e0fbe05d5.png)

### My Approach regarding this

- Very first I revert the migrations
- I detach the partition and try to alter the table 
- But after detaching and altering the table I'm not able to reattach the partition to the table.
- also not able to drop that column too.

 ERROR:  Invalid argument: Invalid column number 15

**Comment by codesnail21** [comment]
> Hi @codesnail21
> 
> What version of YugabyteDB are you using?

2.13.0.0

**Comment by codesnail21** [comment]
> Can you provide the full schema and including some partitions? @ddorian 

Sure

<hr>

### DB SCHEMA

>ID string
>ServerKey string
>BodyBytesSent int
>Hostname string
>HTTPReferer string
>HTTPUserAgent string
>RemoteAddr string
>RemoteUser string
>RequestType string
>RequestHTTPVersion string
>Status int
>Path string
>RequestTime int64
>Timestamp time.Time
>AccountSlug string
>Date string

<hr>

### Partition 

- Partition is based on the `Date`

**Comment by codesnail21** [comment]
> What errors are you getting here?
> 
> Can you show all cases separately, because you're hitting different errors in production/locally and different scenarios? Each one with the schema, changes you're doing and the errors that you're getting in each step.

**See The things is.**

#### LOCALLY
- In local sometimes it executes without any error or so...
But if I keep ingesting more and more data up to 25-30 Million 
Then it shows an error of altering the table (Conflict/aborted) 
That's not an issue.

#### PRODUCTION
- In the case of production it fails every time I tried a few times but it didn't work so I revert it back. 
- The thing is it is not able to work in large data sets I have data of around 8-9 GB with Partition. 
- Only the error is I'm not able to access the `SELECT * FROM TABLENAME` OR `SELECT ALTER_COLUMN FROM TABLENAME`

`SQL Error [XX000]: ERROR: Invalid argument: Invalid column number 17`

**Comment by codesnail21** [comment]
> Please paste the `create table` sql code, along with any indexes and partitions.

CREATE TABLE IF NOT EXISTS logs (
    id TEXT,
    server_key TEXT,
    body_bytes_sent INTEGER,
    hostname TEXT,
    http_referer TEXT,
    http_user_agent TEXT,
    remote_addr TEXT,
    remote_user TEXT,
    request_type TEXT,
    request_http_version TEXT,
    path TEXT,
    status INTEGER,
    request_time INTEGER,
    timestamp INTEGER,
    account_slug TEXT,
    date TEXT,
    PRIMARY KEY((id, date) HASH)
) PARTITION BY range (date);

**Comment by deeps1991** [comment]
@codesnail21 This looks like [#9547](https://github.com/yugabyte/yugabyte-db/issues/9547)
The fix is not in 2.13.0.0. Odd numbered releases are generally not recommended for production. But if you would like to test out the fix, you can upgrade to 2.13.2.0

**Comment by codesnail21** [comment]
> @codesnail21 This looks like [#9547](https://github.com/yugabyte/yugabyte-db/issues/9547) The fix is not in 2.13.0.0. Odd numbered releases are generally not recommended for production. But if you would like to test out the fix, you can upgrade to 2.13.2.0

But I tried latest too by doing so its still same 
then also I try it once more by applying patch/minor one too

**Comment by ddorian** [comment]
> But I tried latest too by doing so its still same

On 2.15.0.0?

**Comment by codesnail21** [comment]
> > But I tried latest too by doing so its still same
> 
> On 2.15.0.0?

YUP

**Comment by ddorian** [comment]
@codesnail21 yes, 2.14.x is a stable branch.

**Comment by deeps1991** [comment]
@codesnail21 Did you try the same test from scratch on 2.15? Or did you upgrade your existing cluster and try it on the upgraded cluster?
I ask because once the table is corrupted, upgrading to 2.15 will not fix the corruption, unfortunately. If this is a test that you can easily run, I would suggest dropping the table and recreating it with 2.15. Otherwise if the table is too large to copy again, I can try to provide a patched yb-admin tool that can fix the table.

**Comment by codesnail21** [comment]
@deeps1991 Firstly I'm trying on the updating the database to 2.13.2 if that's not gonna work then I'm gonna ask for your help 
meanwhile could you please tell me how to `Backup-Restore` the whole data from YUGADB

**Comment by ddorian** [comment]
@codesnail21 See https://docs.yugabyte.com/preview/manage/backup-restore/export-import-data/ and https://docs.yugabyte.com/preview/manage/backup-restore/snapshot-ysql/ for backup-restore

**Comment by codesnail21** [comment]
> @codesnail21 See https://docs.yugabyte.com/preview/manage/backup-restore/export-import-data/ and https://docs.yugabyte.com/preview/manage/backup-restore/snapshot-ysql/ for backup-restore

Okay thanks 👍

**Comment by codesnail21** [comment]
> @codesnail21 This looks like [#9547](https://github.com/yugabyte/yugabyte-db/issues/9547) The fix is not in 2.13.0.0. Odd numbered releases are generally not recommended for production. But if you would like to test out the fix, you can upgrade to 2.13.2.0

fixed with updating the database.
Thanks
