### ISSUE TITLE
[YSQL][Tablet splitting] Restore YSQL dump fails with tablet splitting

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#13233]
Jira Link: [DB-2892](https://yugabyte.atlassian.net/browse/DB-2892)
### Description

**Version**: 2.14.0.0-b84
**Steps**:
1. Create universe with below gflags
```
Master:
{"enable_automatic_tablet_splitting": "true", 
"tablet_split_high_phase_shard_count_per_node": 10000, 
"tablet_split_high_phase_size_threshold_bytes": 10485760, 
"tablet_split_low_phase_size_threshold_bytes": 1048576, 
"tablet_split_low_phase_shard_count_per_node": 16,
"db_write_buffer_size":102400}

Tserver:
{"enable_automatic_tablet_splitting":"true",
"yb_num_shards_per_tserver":1,
"ysql_num_shards_per_tserver":1,
"db_write_buffer_size":102400}
```
2. Create a database(demo) and create table and index
```
create table employees(id int primary key, name text, age int, description text);
create index idx_1 on employees(age);
```
3. Load 200K rows into table and take ysql_dump
`postgres/bin/ysql_dump -h <host> -d <database> -f db_data.sql`
4. Create database(demo1) and restore with
`postgres/bin/ysqlsh -h <host> demo1 < db_data.sql`
5. Observe the behaviour.

Actual:
It fails with
```
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
SET
CREATE TABLE
ALTER TABLE
COPY 199999
ERROR:  Aborted: failed
```
and if user describe the table it gives Index as INVALID
```
db_with_splitting_1=# \d employees;
                Table "public.employees"
   Column    |  Type   | Collation | Nullable | Default
-------------+---------+-----------+----------+---------
 id          | integer |           | not null |
 name        | text    |           |          |
 age         | integer |           |          |
 description | text    |           |          |
Indexes:
    "employees_pkey" PRIMARY KEY, lsm (id HASH)
    "idx_1" lsm (age HASH) INVALID
```

**Note**: Same steps are working fine without tablet splitting.

**Comment by bmatican** [comment]
@Arjun-yb Is this test still relevant? I thought we had agreed that we would not be using very aggressive flags, like <1MB flush size, etc

**Comment by Arjun-yb** [comment]
@bmatican I tried same validation(with 200K and 500K rows) with 2.14.14.0(with same GFLAGS) it is working without any errors.
