### ISSUE TITLE
Its not documented clearly as to where ysql_dump is avbl to be used. Details in the description

### ISSUE THREAD

**Issue by upenbendre** [yugabyte/yugabyte-db#13231]
### Description

https://download.yugabyte.com/local#linux - I am not able to find a download which contains ysql_dump for Linux. I need to run ysql_dump from a separate node, not from a TServer node. And I don’t want to install the whole Yugabyte server for the sake of ysql_dump.

https://docs.yugabyte.com/preview/admin/ysqlsh/ I see that the Mac client has ysql_dump but the CentOS Linux client does not have. Where do I get it from?

**Comment by ddorian** [comment]
Hi @upenbendre 

> I see that the Mac client has ysql_dump but the CentOS Linux client does not have.

Can you show the mac client having ysql_dump? And which install method you used? I think it also doesn't have it. I don't have a mac to test it myself, but looking at the source code of the docker container and get_clients.sh it shouldn't be there.

**Comment by ddorian** [comment]
The https://downloads.yugabyte.com/get_clients.sh script only lists `./bin` while `ysql_dump` is in `./postgres/bin/`.

The same for the docker-client source https://hub.docker.com/layers/yugabyte-client/yugabytedb/yugabyte-client/latest/images/sha256-a99a164c7183b72b71c8d3720cf7e227996ab902b4e6b25a40eb1ce72f2ea02d?context=explore

**Comment by ddorian** [comment]
@upenbendre closing this as `working as designed`. 

`ysql_dump` isn't included in the brew formula for `yugabytedb-client` https://github.com/yugabyte/homebrew-yugabytedb/blob/master/Formula/yugabytedb-client.rb.
