### ISSUE TITLE
YSQL_hba_conf vs T-Server flags

### ISSUE THREAD

**Issue by upenbendre** [yugabyte/yugabyte-db#13232]
### Description

There isn't documentation available in one place to indicate which T-Server flag has what effect on ysql_hba_conf. Also if a set of 3 lines is provided in ysql_hba_conf_csv parameter in a specific order, and if we have a T_Server flag (which influences ysql_hba.conf in addition to the ysql_hba_conf_csv, then the limitation is that the ysql_hba line inserted by the T-Server flag can only be at the bottom of the ysql_hba_conf (after the 3 lines given). There is no way to position a T_Server flag that influence ysql_hba at the top or in between the existing ysql_hba lines.

e.g. if a TServer flag for encryption adds a 'hostssl all all ..... " line to ysql_hba, it will only become the 4th line below all the ysql_hba_conf lines specified in the command, even if we want it to be at 1st or 3rd place.

**Comment by ddorian** [comment]
Hi @upenbendre 

Can you add the complete example that you're describing? With all gflags you mention and their values and the produced/expected ysql_hba file?

**Comment by ddorian** [comment]
Closing as the user is unresponsive. Please reopen with a complete example otherwise.
