### ISSUE TITLE
Ability to enable async replication between two clusters for an entire database or entire cluster in one command

### ISSUE THREAD

**Issue by upenbendre** [yugabyte/yugabyte-db#13237]
Jira Link: [DB-2954](https://yugabyte.atlassian.net/browse/DB-2954)
### Description

As of core v2.12, to enable async replication between two clusters for a database, the process is tedious. The entire list of tables to be replicated needs to be set up as a stream. every time a table is added or removed off the database, this needs to change. This makes it difficult to maintain the replication as the environment

**Comment by lingamsandeep** [comment]
Hi @upenbendre . This is on our roadmap as part of https://github.com/yugabyte/yugabyte-db/issues/10984.
