### ISSUE TITLE
[xCluster] yb-admin does not enforce naming convention for xcluster groups

### ISSUE THREAD

**Issue by yb-valerie** [yugabyte/yugabyte-db#13243]
Jira Link: [DB-2898](https://yugabyte.atlassian.net/browse/DB-2898)
### Description

The yb-admin setup_universe_replication command does not enforce the required naming format. If replication streams are set up with yb-admin and are not named correctly, the Platform API endpoint used for xCluster operations and tracking will not work.

Expected functionality: `yb-admin setup_universe_replication` will enforce required naming conventions for subsequent functionality.

Steps to reproduce:
- create xCluster replication stream via yb-admin using instructions at https://docs.yugabyte.com/preview/admin/yb-admin/#setup-universe-replication but do not follow `<source_universe_uuid>_<replication_name>` naming convention
- attempt to use Platform API endpoint (e.g., view replication status in Platform)

**Comment by rthallamko3** [comment]
This is not relevant as YBA support for xCluster is now added. cc @lingamsandeep
