### ISSUE TITLE
[docdb] Add API endpoint for returning software version information

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#1325]
```
[ec2-user@ip-172-152-52-145 ~]$ yugabyte-db/master/bin/yb-admin -master_addresses 127.0.0.1:7100 get_universe_config
I0507 18:42:43.189155 27787 mem_tracker.cc:241] MemTracker: hard memory limit is 6.203495 GB
I0507 18:42:43.189250 27787 mem_tracker.cc:243] MemTracker: soft memory limit is 5.272971 GB
Config:
version: 0
cluster_uuid: "d4de8c13-359d-484f-94be-eb88d883d537"
```
It would be helpful if this reflected the appropriate CE or EE version string.

**Comment by bmatican** [comment]
@ajcaldera1 this `version` field is not the YB version. It is the version of the actual `ClusterConfig` object (which keeps track of, for example, which placements the nodes should be in, what nodes are blacklisted, etc..). For the actual version, we have it in the UI footers, as well as through `yb-master --version` / `yb-tserver --version`, for programatic access.

What type of need did you have in mind, for wanting to access the version info via APIs? We could, for example, expose some endpoint to display a structured format for version metadata...

**Comment by ajcaldera1** [comment]
I think an API like /warez that has a json string with the version number and applicable components would be great. This would allow checking of version information w/o logging in to a machine.
E.g.
https://my-tserver-address:9000/warez

{ "version_info":  {
  "version_string" : "2.x.x.x-xx-bxx",
  "edition" : "ce",
  "version_major" : "2",
  "version_minor" : "x",
  "version_patch" : "x",
  "build_number" : "xx"
}
}

**Comment by sanketkedia** [comment]
![image](https://user-images.githubusercontent.com/14816236/101108940-864ec400-358a-11eb-8189-ae7e8e765d30.png)

**Comment by sanketkedia** [comment]
![image](https://user-images.githubusercontent.com/14816236/101720180-c49c2580-3a59-11eb-9ea8-a42bfa8877c8.png)

**Comment by sanketkedia** [comment]
![image](https://user-images.githubusercontent.com/14816236/102158280-f9cbbd80-3e35-11eb-91fc-cd7221a95f40.png)

**Comment by sanketkedia** [comment]
![image](https://user-images.githubusercontent.com/14816236/102158308-08b27000-3e36-11eb-9b27-263c7b221afa.png)

**Comment by sanketkedia** [comment]
/api/v1/version on master or tserver side returns now returns a PRETTY JSON displaying the version information as requested.
