### ISSUE TITLE
[DocDB] Changes to /prometheus-metrics endpoint for improving performance

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13265]
Jira Link: [DB-2912](https://yugabyte.atlassian.net/browse/DB-2912)
### Description

In light of #12539, had some discussions with @iSignal and we agreed on restructuring the DB endpoint and the Platform usage, in the following way
- **Server level aggregation.** At the DB level, we already aggregate tablet level data, to the table level. However, this can still generate a growing number of metrics, as the user creates more and more tables. So we should provide a flag to also aggregate all the way to server level instead, for these tablet level metrics.
- **Filtering by CSV rather than regex.** Currently, the DB supports a filter by random regex. However, complicated regex matching, for every single tablet name, is very expensive... Ideally, we switch Platform usage to a simple CSV of all the metrics they care about, so we reduce DB CPU usage.
- **Hard limit on number of metrics.** We currently have a url param to limit the number of metrics, for each table. We however need a hard global limit, to ensure that Platform doesn't get overwhelmed by the number of metrics pulled.

**Comment by rthallamko3** [comment]
Commit 3a06f13a added the capability to track intent metrics separately. Once the above optimizations are in and platform uses them, we can enable the intent metrics tracking in the engine as well. cc @yusong-yan , @bmatican

**Comment by rthallamko3** [comment]
Will be tracked by fixes in https://github.com/yugabyte/yugabyte-db/issues/18078
