### ISSUE TITLE
[DocDB] Remove "using std::string" from .h files

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#13288]
Jira Link: [DB-2925](https://yugabyte.atlassian.net/browse/DB-2925)
### Description

string -> std::string in header files (I think there might be a using std::string somewhere in a global header file if this compiles as is, which is wrong and should be fixed separately).

**Comment by mbautin** [comment]
A script that helps with automatically fixing compilation errors: https://gist.githubusercontent.com/mbautin/15cf3d9817a9cbc65915bc1cbc0bbcb8/raw
