### ISSUE TITLE
[CDCSDK][Kafka] Provide an option to send events to a single topic

### ISSUE THREAD

**Issue by cdavid** [yugabyte/yugabyte-db#13289]
Jira Link: [DB-3408](https://yugabyte.atlassian.net/browse/DB-3408)
From PRD: Allow sending change events to the same topic or create a topic per table

**Comment by vaibhav-yb** [comment]
Hi @cdavid Turns out, Debezium already has a transformer to do the same. Please take a look at https://debezium.io/documentation/reference/stable/transformations/topic-routing.html

**Comment by cdavid** [comment]
Hi @vaibhav-yb - I looked and it seems these configurations are for Kafka Connect. Are they available for CDCSDK as well? Are the names of the configurations changed for CDCSDK?

**Comment by vaibhav-yb** [comment]
Hi @cdavid I did test this in a unit test and it was working there so I am assuming the will also work with CDCSDK. You can try and let us know if you face any issues. The only thing which would be different I guess that you may need to add the prefix for `cdcsdk.server` in the property names.

**Comment by vaibhav-yb** [comment]
Marking it as closed with the details to specify what to do to send events to a single topic:

For Kafka Connect configuration, we just need to add the following configs:

```
"transforms":"Reroute",
"transforms.Reroute.topic.regex":"(.*)",
"transforms.Reroute.topic.replacement":"dbserver1_all_events",
"transforms.Reroute.type":"io.debezium.transforms.ByLogicalTableRouter",
"transforms.Reroute.key.field.regex":"dbserver1.public.(.*)",
"transforms.Reroute.key.field.replacement":"\\$1"
```

For cdcsdk-server, we will just need to add a prefix to these properties i.e. `cdcsdk-server`
