### ISSUE TITLE
[DocDB] Restore of tablet that has gone through tablet splitting should update TS side tablet metadata

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13294]
Jira Link: [DB-2927](https://yugabyte.atlassian.net/browse/DB-2927)
### Description

From a conversation on slack with @ttyusupov @arybochkin and @OlegLoginov , it turns out that we are missing some TS side metadata, on restore, for tablets that have gone through tablet splitting. In particular, we need a way to restore
- key bounds, ie: `KvStoreInfoPB::lower_bound_key` and `KvStoreInfoPB::upper_bound_key`
- compaction metadata, ie: `has_been_fully_compacted` boolean

However, since this is in the context of backup/restore, we need to be mindful of what data currently gets pulled into a backup and what happens if we restore existing data. As such, it would be ideal if we could compute these properties at runtime, on restore! It turns out, this should be possible and cheap.

For key bounds, as per Anton: `it’s literally mem copy operation only - for range-partitioned they exactly match with partition bounds, for hash-partitioned it’s one call per bound of decoding/encoding of hash value`.

For compaction, we need to figure out if this tablet has gone through the post-split compaction which is generally responsible for clearing the half of the data in SST files that is not relevant for this child tablet. One proxy for that is to look at every single SST file and confirm if any of the data in the file is outside the key bounds for this tablet:
- If yes, then we had not done the post-split compaction and we need to re-enqueue one.
- If no, then we can just as well mark the compaction as having been done, as we have no data we need to purge anymore.

As per Timur, this should also be cheap to compute (in-memory): `has_been_fully_compacted could be set based on smallest/largest key for rocksdb - if rocksdb (meaning all its SST files) has all keys within [smallest; largest] - we will set has_been_fully_compacted to true. Looks like this is per SST file, but this is inside FileMetaData struct that seems to be populated somehow on opening RocksDB based on this: VersionSet::GetLiveFilesMetaData`

Finally, the tserver also needs to know, on restore, if it needs to recompute this metadata! Currently, we do not flow information on restore, of whether or not this tablet had been split. That information is captured by the `split_depth` property on the master, per tablet. Conveniently this is also updated with backup metadata in `yb.master.SysTabletsEntryPB`! So we can also
- Ensure that on restore, we correctly update master metadata for `TabletInfo::split_depth`.
- When issuing restore RPCs to each tserver, we can also flow this `split_depth` info in the RPC, as the signal for the TS of whether it needs to recompute and update it's tablet meta.

So this translates into 4 work items
- Update TabletInfo on master, on restore, for all newly created tablets, with the `split_depth` from the backup.
- Enhance the RestoreTablet RPC to also flow `split_depth`, as the signal for TS to compute and update their TabletMetadata.
- TS side code to runtime compute and update key bounds metadata.
- TS side code to iterate through SST file metadata, compute if a post-split compaction is necessary, update metadata and schedule one as needed.

**Comment by druzac** [comment]
There's been a lot of internal discussion on this. The tl;dr is:

- We've identified two impacts of this, incorrect queries and failure to split child tablets
- This issue is tracking the incorrect query problem, there's a fix in flight we intend to land for 2.14.1
- #13444 tracks fixing the inability to split child tablets after a restore
