### ISSUE TITLE
Jepsen failure scenarios - implement majority ring partitions

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#133]
Partitions network in a way that every node can see a majority, but no node sees the same majority as any other. Nodes are arranged in a ring in a random order, and each node is connected to its nearest neighbors.

**Comment by ttyusupov** [comment]
Commit: https://github.com/YugaByte/jepsen/commit/94468a65b432dbc2da9d0afbcf5f0f211295240e
