### ISSUE TITLE
[YSQL] Table already exists when creating tables with HikariCP

### ISSUE THREAD

**Issue by m-iancu** [YugaByte/yugabyte-db#1333]
Running DDLs from multiple threads/nodes can lead to catalog version mismatch.
But internally retrying is not reliable for DDLs because system tables are not (yet) transactional. Therefore retrying can lead to the table already exists error.

**Comment by ndeodhar** [comment]
@georgeklees To clarify: Currently, YB client retries any requests that time out. Retrying is not reliable for DDLs, so as a first step, we should avoid retrying DDL requests in YB client.
