### ISSUE TITLE
[YSQL][Upgrade] Option to limit upgrade_ysql command to 1 connection

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#13364]
Jira Link: [DB-3003](https://yugabyte.atlassian.net/browse/DB-3003)
### Description

When a cluster is being upgraded we automatically run `upgrade_ysql` from YBAnywhere after the rest of the upgrade steps have completed. This command opens 1 client connection per DB in the cluster. In YBManaged, we limit free tier clusters to 13 connections (with 3 of those reserved for superuser). This means that there is a possibility where `num_active_client_connections + num_db_in_cluster > max_ysql_connections` which results in the upgrade failing.

It would be really useful to us on the YBManaged team for there to be some option (gflag?) to limit the `upgrade_ysql` command to only 1 client connection such that it's much less likely that we run into this issue in the future.

**Comment by frozenspider** [comment]
Another use case - one customer has ~360 DBs and that incurs a pretty high memory overhead on an upgrade.

**Comment by frozenspider** [comment]
Note: this was blocked by (now-fixed) #13796.

**Comment by frozenspider** [comment]
Implemented in 34d5910bbcadd372923d92101906f680c6d26eee, syntax being `yb-admin upgrade_ysql use_single_connection`
