### ISSUE TITLE
[DocDB] Block cache mem-tracker can disappear

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13379]
Jira Link: [DB-3014](https://yugabyte.atlassian.net/browse/DB-3014)
### Description

In older versions, eg: 2.4, we had this top-level view under the `server` tracker, clearly showing the biggest memory usage was the block cache:
```
server | 6.24G (6.26G) | 6.75G | none
BlockBasedTable | 4.85G | 5.35G | 5.27G
```
In future versions, sometimes, unclear how/why/when, this tracker is not present! Note the memory usage is likely still captured at the server level, as there's always a considerable discrepancy between server and its immediate children
```
server | 1.68G (1.69G) | 2.22G | none
CQL | 127.52M | 128.55M | none
...
```

**Comment by es1024** [comment]
This is very likely due to the block cache memtracker being deleted (no remaining shared_ptr left) -- assigning a copy of the pointer to a static variable to keep it alive appears to fix it. Unsure at the moment why there are sometimes no more references to the pointer.
