### ISSUE TITLE
[DocDB] Initial leader election frequently fails at table creation time

### ISSUE THREAD

**Issue by joe-maley** [yugabyte/yugabyte-db#13389]
Jira Link: [DB-3022](https://yugabyte.atlassian.net/browse/DB-3022)
### Description

I have observed that the master-initiated leader election consistently fails in the following scenario:
1. The master creates a table with 3 replicas per tablet.
2. The master issues AsyncCreateReplica request to the tservers for each replica.
3. Tservers {t1, t2, t3} begin the bootstrapping process for replicas {r1, r2, r3}.
4. Replica r1 completes the bootstrapping process. Replicas r2 and r3 have not completed.
5. Tserver t1 sends a heartbeat to the master. The heartbeat contains a tablet report for replica r1.
6. The master receives the heartbeat. It processes the tablet report and issues an AsyncStartElection task to the consensus proxy.
7. The leader election fails because it can not reach a quorum. It can not reach a quorum because replicas r2 and r3 and still bootstrapping and can not vote. Here an example log statement for the VoteRequest() failure.
```
Term 1 pre-election: Tablet error from VoteRequest() call to peer fe023ac25a2843f58105c393bb525546: Illegal state (yb/tserver/service_util.cc:253): Tablet d6b06e8557bb4da2a97d7229d381da95 not RUNNING: BOOTSTRAPPING (tablet server error 12) (raft group state error 0)
```
8. Eventually, the `RaftConsensus:failure_detector_` poll will detect the failure and retry election.

**Comment by joe-maley** [comment]
I don't know if this is the root cause, but we have a check today that attempts to delay the leader initial election until the majority of the replicas are "running".
```
if (running_voters < majority_size) {
  VLOG_WITH_PREFIX(4) << __func__ << ": Not enough voters";
  return;
}
```

However, this check does not work as expected in this scenario because the `num_voters` and `running_voters` used in this calculation are always the same.

The `num_voters` is populated by counting the number of VOTER peers in the consensus state.
```
int num_voters = 0;
for (const auto& peer : cstate.config().peers())
  if (peer.member_type() == PeerMemberType::VOTER)
    ++num_voters;
```

Likewise, the `running_voters` is also populated by counting the number of VOTER peers in the consensus state. However, this is calculation is not as direct.
```
int running_voters = 0;
for (const auto& replica : *replicas)
  if (replica.second.member_type == PeerMemberType::VOTER)
    ++running_voters;
```

The `replicas` container is populated in the following path:
```
CatalogManager::ProcessCommittedConsensusState
  CatalogManager::ReconcileTabletReplicasInLocalMemoryWithReport
    CatalogManager::CreateNewReplicaForLocalMemory
      GetConsensusMemberType
```

The `GetConsensusMemberType` populates the `replicas` container with the peers in the consensus state.
```
for (const RaftPeerPB& peer : cstate.config().peers())
  if (peer.permanent_uuid() == permanent_uuid)
    return peer.member_type();
```

I am not sure how we intended to differentiate between "non-running" and a "running" voters, but I suspect the fix for this issue is to change how we identify "non-running" voters.

**Comment by bmatican** [comment]
cc @Huqicheng as you were looking at something similar for triggering elections, after a split, maybe we need to unify how and when we trigger the election

**Comment by joe-maley** [comment]
I found that we have an existing `RaftGroupStatePB` associated with each tablet. In the scenario outlined in this ticket, the first replica is correctly reported in a `RaftGroupStatePB::RUNNING` state. However, the master uses this state for _all_ replicas. I've made the following local changes to fix the reported issue:
1. The master initializes unreported replicas in the `RaftGroupStatePB::UNKNOWN` state.
2. The master uses the `RaftGroupStatePB` instead of the `PeerMemberType` to determine whether or not a replica is in a running state.

I'll need to validate that this change is applicable for the split tablet path as well.

**Comment by rthallamko3** [comment]
@joe-maley , Can we backport this diff to 2.14 branch? A couple of tablet-splitting fixes need to be backported to that branch and your change is a pre-requisite.

**Comment by joe-maley** [comment]
@rthallamko3 Sure, I think this is safe for 2.14.

**Comment by rthallamko3** [comment]
Reactivating till the backport to 2.14 lands.

**Comment by joe-maley** [comment]
The fix for this issue provides a significant performance improvement for table creation. Under normal circumstances, this should provide about a 3-second decrease in the time it takes to create a table.

The fix was benchmarked on a 3-node cluster deployed on a public cloud:
```
Table Create Time (pre-patch) (SQL): 3.33 seconds
Table Create Time (post-patch) (SQL): 0.34 seconds

Table Create Time (pre-patch) (CQL): 4.09 seconds
Table Create Time (post-patch) (CQL): 0.31 seconds
```

This is a ~10x speedup for SQL tables and a ~12x speedup for CQL tables.
