### ISSUE TITLE
[Jepsen Testing] Single-key ACID

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#134]
## Scenario
There is a single table with exactly one row in it. The table has a hash column primary key, and one value column. Jepsen sends concurrent reads, writes and read-modify-write (UPDATE IF) operations to different nodes. Each operation is logged along with its results. The results can be one of the following:
- OK : the operation was successful
- FAIL: the operation failed
- UNKNOWN: we did not get a response (because there may have been a failure)

## Validation
At the end of the run a checker validates that the result of the sequence of reads recorded, which is the client observed view of the data, is linearizable across all the nodes.

**Comment by ttyusupov** [comment]
Commit: https://github.com/YugaByte/jepsen/commit/daca8f89e38d162a739b9a7055f6d4645beedfbf
