### ISSUE TITLE
[YSQL] Catalog Version change on no-op GRANT DDL statements

### ISSUE THREAD

**Issue by jameshartig** [yugabyte/yugabyte-db#13415]
Jira Link: [DB-3042](https://yugabyte.atlassian.net/browse/DB-3042)
### Description

I saw #11997 but it doesn't seem like that fixed it for `GRANT` DDLs:

Start a docker container:
```bash
docker run --rm -it --name yb yugabytedb/yugabyte:2.14.0.0-b94 bash -c "bin/yugabyted start --daemon=false"
```

Then observe:
```bash
$ docker exec -it yb ysqlsh -c "SELECT * FROM pg_yb_catalog_version;"
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               1 |                     1
(1 row)

$ docker exec -it yb ysqlsh -c "CREATE ROLE test;"
CREATE ROLE

$ docker exec -it yb ysqlsh -c "SELECT * FROM pg_yb_catalog_version;"
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               2 |                     1
(1 row)

$ docker exec -it yb ysqlsh -c "CREATE ROLE test;"
ERROR:  role "test" already exists

$ docker exec -it yb ysqlsh -c "SELECT * FROM pg_yb_catalog_version;"
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               2 |                     1
(1 row)

$ docker exec -it yb ysqlsh -c "CREATE DATABASE test;"
CREATE DATABASE

$ docker exec -it yb ysqlsh -c "SELECT * FROM pg_yb_catalog_version;"
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               2 |                     1
(1 row)

$ docker exec -it yb ysqlsh -c "GRANT CONNECT ON DATABASE test TO test;"
GRANT

$ docker exec -it yb ysqlsh -c "SELECT * FROM pg_yb_catalog_version;"
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               3 |                     1
(1 row)

$ docker exec -it yb ysqlsh -c "GRANT CONNECT ON DATABASE test TO test;"
GRANT

$ docker exec -it yb ysqlsh -c "SELECT * FROM pg_yb_catalog_version;"
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               4 |                     1
(1 row)
```

The last `GRANT CONNECT ON DATABASE test TO test;` did nothing and shouldn't have bumped the catalog version. We have various DDL statements as part of our bootstrapping process and whenever they run they end up causing a massive flood of traffic to masters when the catalog changes needlessly.

**Comment by myang2021** [comment]
GRANT is different from the CREATE in the example in that GRANT always causes a write to the pg_database table disregarding its old value. In contrast, CREATE will not overwrite the existing entry and will error out. The difference is that GRANT involves a write but CREATE does not. We do have an optimization saying that if no write is done then we skip increment catalog version. But in this case because GRANT did cause a write to pg_database table, as a result we think the catalog has changed even though GRANT could be smarter. I think it is the Postgres code does not do that optimization and always writes to pg_database. We can look to improve GRANT to make it skip the write if not needed.

**Comment by jameshartig** [comment]
@myang2021 thanks for the update and quick response! Given the large impact that a version bump does to the whole cluster I do think there's value in attempting to noop this case but I understand where you're coming from.

Separately I'll try to add some code to our bootstrapping process to check to see existing roles and only call GRANT if the privileges don't exist.

**Comment by tedyu** [comment]
One option is to add support for `IF NOT EXISTS` clause to `GRANT` so that the write to pg_database table becomes conditional.

**Comment by myang2021** [comment]
PG could have done the optimization by detecting no change and therefore skip the pg_database write. But I guess that effort to deduplicate itself may not worth it for PG compared to a simple overwrite of the old privileges. However, YB uses a different catalog version mechanism to replace PG's cache invalidation mechanism and this optimization is very much meaningful to do for YB to avoid unnecessary catalog version change which has very bad ripple effect. I will take a look at how to do this optimization.
