### ISSUE TITLE
Consider adding CLA for contributions

### ISSUE THREAD

**Issue by aegershman** [YugaByte/yugabyte-db#1343]
In order to prevent potential legal turmoil, you might consider [adding a CLA similar to how other projects like `spring` do for developer contributions](https://github.com/spring-projects/spring-framework/pull/22372#issuecomment-461343565)

Pivotal [requires contributors to sign a CLA](https://cla.pivotal.io/about) for certain legal reasons that I'm too dumb to understand, but it might be valuable to investigate why they do it / whether it's appropriate for YB.

Thanks /cc @ajcaldera1 @xyloman @dashaun

**Comment by kmuthukk** [comment]
hi @aegershman - yes, we have a CLA that we request folks to sign before accepting their contributions. I believe currently it is a google form. Will have someone update/provide that information. 

But, we need to make it available in the github README.md for the various projects (yugabyte-db, drivers, etc.).

**Comment by mbautin** [comment]
We currently have this form for singing CLAs: https://docs.google.com/forms/d/11hn-vBGhOZRunclC3NKmSX1cvQVrU--r0ldDLqasRIo/edit

**Comment by aegershman** [comment]
Cool beans, all good, just thought of it & figured I'd throw this out there 👍 thanks

**Comment by GWhiskas** [comment]
Do I need to sign this form?
https://docs.google.com/forms/d/11hn-vBGhOZRunclC3NKmSX1cvQVrU--r0ldDLqasRIo/edit

Corrections in this PR correctly?
https://github.com/spring-projects/spring-framework/pull/22372#issuecomment-461343565
Will it be merged?

**Comment by kmuthukk** [comment]
hi @GWhiskas - the CLA form that @mbautin shared is for contributions to the YugaByte repo. The link you point to seems to be a contribution to the spring-projects. I believe that's a different CLA form. Maybe it is the one posted in this comment: https://github.com/spring-projects/spring-framework/pull/22372#issuecomment-461343565?
