### ISSUE TITLE
[Docs] YB Anywhere UI port number issue [v2.15]

### ISSUE THREAD

**Issue by tense8** [yugabyte/yugabyte-db#13436]
### Description

In [prepare the environment](https://docs.yugabyte.com/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws/), it says that to access the YB anywhere UI from outside, user needs to open port 80.

However, when I tried to install YB anywhere v2.15 I noticed that port 80 is not being listened, instead YB anywhere UI is listening on port 443.

I am not sure whether this is a doc issue or a product issue, but I assume using secured port is a better idea.

This is also true for the [Create admin user ](https://docs.yugabyte.com/preview/yugabyte-platform/configure-yugabyte-platform/create-admin-user/) page, as in this page it asks user to access the http port (80).

**Comment by polarweasel** [comment]
@lizayugabyte Can you check into this one and see what's up? Is YBA SSL-only by default?

**Comment by lizayugabyte** [comment]
@tense8 This port needs to be configured via the security group, as described in the document. Did you do that and still coudn't get port 80 to work?

**Comment by lizayugabyte** [comment]
It doesn't look like the ticket creator is planning to get back to me on this. I'm assuming he/she didn't configure the security group prior to using port 80. When that's done, as per the instructions provided in the document, there are no issues, as indicated by the fact that we haven't seen similar complaints from other users.
I'm closing this ticket for now. If the original ticket creator provides the answer, we'll reopen the ticket.
