### ISSUE TITLE
[Docs] YB -Voyager Import Schema command needs fix

### ISSUE THREAD

**Issue by seethb** [yugabyte/yugabyte-db#13439]
### Description

Hi in this import schema section of YB Voyager document page. backward slash missing between Target_DB_NAME and TARGET_DB_USER which breaks the command if we supply Target_DB_User parameter.

__For Oracle, yb-voyager imports the source database into the public schema of the target database. By specifying --target-db-schema argument during import, you can instruct yb-voyager to create a non-public schema and use it for the schema/data import._

yb-voyager import schema --export-dir ${EXPORT_DIR} \
        --target-db-host ${TARGET_DB_HOST} \
        --target-db-user ${TARGET_DB_USER} \
        --target-db-password ${TARGET_DB_PASSWORD} \
        --target-db-name ${TARGET_DB_NAME} **<We need Slash here>** 
        --target-db-user ${TARGET_DB_USER}_

Kindly fix it.

Thanks,
Bala.S

**Comment by ddorian** [comment]
@seethb on which page?

**Comment by seethb** [comment]
Hi @ddorian  https://docs.yugabyte.com/preview/migrate/yb-voyager/migrate-steps/#import-data
