### ISSUE TITLE
[DocDB] Sort Gflag XML files by flag name

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#13431]
Jira Link: [DB-3054](https://yugabyte.atlassian.net/browse/DB-3054)
### Description

Please sort the Gflag XML files alphabetically by the `<name>` element.

(I think there's already a request outstanding to remove the TEST_* flags, but if not, can we please remove those?)

**Comment by hari90** [comment]
https://yugabyte.slack.com/archives/C4141D60H/p1658767945689409
