### ISSUE TITLE
[DocDB] Compact child tablets of a split after a restore

### ISSUE THREAD

**Issue by druzac** [yugabyte/yugabyte-db#13444]
Jira Link: [DB-3061](https://yugabyte.atlassian.net/browse/DB-3061)
### Description

When a tablet is split, the two child tablets are created by cloning the data underlying the parent tablet and setting some metadata to track what data is live in the child tablets. An asynchronous major compaction is also kicked off on both child tablets to delete the redundant data.

However, the snapshot mechanism currently doesn't save any tablet metadata. If a tablet split and snapshot are interleaved, it's possible a subsequent restore can yield two child tablets with default metadata. Without any indication of which rows should be live and which should be ignored in the child tablets, it's possible some queries will be incorrect. There's also a space leak.

#13294 tracks fixing the correctness issue by saving and restoring certain fields from tablet metadata in snapshots. This issue tracks kicking off a compaction after a restore, if necessary, to ensure the redundant data in child tablets is compacted. Some consequences of this issue:

- the redundant rows duplicated across both children are a waste of space until they are "organically" compacted
- subsequent split commands against these child tablets fail

**Comment by Huqicheng** [comment]
Backport to 2.14. Closing it.
