### ISSUE TITLE
[CDCSDK] The Java YBClient.listCDCStreams() does not populate namespaceId

### ISSUE THREAD

**Issue by cdavid** [yugabyte/yugabyte-db#13441]
Jira Link: [DB-3091](https://yugabyte.atlassian.net/browse/DB-3091)
When making a call to listCDCStreams(), the `namespaceId` field of each stream is not populated.

Sample result from the API:

```json
    "streams": [
        {
            "streamId": "98286df8633f4728a5145c644b8016d8",
            "tableIds": [
                "000033e1000030008000000000004009"
            ],
            "options": {
                "record_format": "PROTO",
                "checkpoint_type": "IMPLICIT",
                "source_type": "CDCSDK",
                "id_type": "NAMESPACEID",
                "state": "ACTIVE",
                "record_type": "CHANGE"
            },
            "namespaceId": ""
        }
    ]
```

**Comment by vaibhav-yb** [comment]
There's another API call, `getDBStreamInfo(String streamID)` - this will return the namespace ID in its response along with the details of the table IDs which are a part of the given stream ID.

However, the API needs a little change to do the same as of now, assigning @Sumukh-Phalgaonkar to work on the required modification.
