### ISSUE TITLE
[DocDB] AutomaticTabletSplitITest.AutomaticTabletSplittingMovesToNextPhase is flaky

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#13446]
Jira Link: [DB-3062](https://yugabyte.atlassian.net/browse/DB-3062)
### Description

It can probably be combined with AutomaticTabletSplittingMultiPhase.

**Comment by rthallamko3** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=AutomaticTabletSplitITest&fail_tag=all&name=AutomaticTabletSplittingMovesToNextPhase&platform=linux

**Comment by rthallamko3** [comment]
Detective report looks clean. Closing the defect.
