### ISSUE TITLE
The cluster config shows primary servers and read replicas created separately, but upon connection to 5433 neither allows creating a DB, and on the console they all show up as Read replicas 

### ISSUE THREAD

**Issue by upenbendre** [yugabyte/yugabyte-db#13460]
Jira Link: [DB-3070](https://yugabyte.atlassian.net/browse/DB-3070)
### Description

Trying to make a new cluster: I have 6 nodes (3 Masters & 3 Servers running on node yb1,yb2,yb3), And 3 Read Replicas running on ybr1, ybr2, ybr3 - i.e. The Read Replicas on different machines:

**Step 1: Below are the configurations created:**
Masters:
```
(MASTER=$ip; CLOUD=ssnc; REGION=us; AZ=kc; CONFIG_FILE=/yb-conf/master.conf ;\
 ssh $MASTER ”
  echo ‘--master_addresses=$MASTER_RPC_ADDRS’  > $CONFIG_FILE
  echo ‘--fs_data_dirs=$DATA_DIRS’       >> $CONFIG_FILE
  echo ‘--rpc_bind_addresses=$MASTER:7100’   >> $CONFIG_FILE
  echo ‘--webserver_interface=$MASTER’     >> $CONFIG_FILE
  echo ‘--placement_cloud=$CLOUD’        >> $CONFIG_FILE
  echo ‘--placement_region=$REGION’       >> $CONFIG_FILE
  echo ‘--placement_zone=$AZ’          >> $CONFIG_FILE
  echo ‘--max_clock_skew_usec=700000’      >> $CONFIG_FILE
”
)
```
Primary Servers:
```
(CLOUD=ssnc; REGION=us; AZ=kc; CONFIG_FILE=/yb-conf/tserver.conf; \
for ip in $ALL_TSERVERS; do \
  echo =======$ip=======; \
  ssh $ip ”
    echo ‘--tserver_master_addrs=$MASTER_RPC_ADDRS’      > $CONFIG_FILE
    echo ‘--fs_data_dirs=$DATA_DIRS’             >> $CONFIG_FILE
    echo ‘--rpc_bind_addresses=$ip:9100’           >> $CONFIG_FILE
    echo ‘--cql_proxy_bind_address=$ip:9042’         >> $CONFIG_FILE
    echo ‘--redis_proxy_bind_address=$ip:6379’        >> $CONFIG_FILE
    echo ‘--webserver_interface=$ip’             >> $CONFIG_FILE
    echo ‘--placement_cloud=$CLOUD’              >> $CONFIG_FILE
    echo ‘--placement_region=$REGION’             >> $CONFIG_FILE
    echo ‘--placement_zone=$AZ’                >> $CONFIG_FILE
    echo ‘--pgsql_proxy_bind_address=$ip:5433’        >> $CONFIG_FILE
    echo ‘--ysql_enable_auth=TRUE’              >> $CONFIG_FILE
    echo ‘--max_clock_skew_usec=700000’            >> $CONFIG_FILE
  ”
done
)
```
**Read Replicas:**
```
(CLOUD=ssnc; REGION=us; AZ=kcrr; CONFIG_FILE=/yb-conf/tserver.conf; \
for ip in $ALL_RRS; do \
  echo =======$ip=======; \
  ssh $ip ”
    echo ‘--tserver_master_addrs=$MASTER_RPC_ADDRS’      > $CONFIG_FILE
    echo ‘--fs_data_dirs=$DATA_DIRS’             >> $CONFIG_FILE
    echo ‘--rpc_bind_addresses=$ip:9100’           >> $CONFIG_FILE
    echo ‘--cql_proxy_bind_address=$ip:9042’         >> $CONFIG_FILE
    echo ‘--redis_proxy_bind_address=$ip:6379’        >> $CONFIG_FILE
    echo ‘--webserver_interface=$ip’             >> $CONFIG_FILE
    echo ‘--placement_cloud=$CLOUD’              >> $CONFIG_FILE
    echo ‘--placement_region=$REGION’             >> $CONFIG_FILE
    echo ‘--placement_zone=$AZ’                >> $CONFIG_FILE
    echo ‘--pgsql_proxy_bind_address=$ip:5433’        >> $CONFIG_FILE
    echo ‘--ysql_enable_auth=TRUE’              >> $CONFIG_FILE
    echo ‘--max_clock_skew_usec=700000’            >> $CONFIG_FILE
  ”
done
)
```
****Step 2: I started Masters at yb1, yb2, yb3** 

**Step 3: then ran the following commands:**
Placement info for T-Servers
```
ssh yb1.ssnc-corp.cloud ~/master/bin/yb-admin --master_addresses $MASTER_RPC_ADDRS modify_placement_info ssnc.us.kc:3 3 prim_uuid;
```
**Step 4: # Set Preferred placement zone:**
```
ssh yb1.ssnc-corp.cloud ~/master/bin/yb-admin -master_addresses $MASTER_RPC_ADDRS set_preferred_zones ssnc.us.kc:1
```
**Step 5: Placement info for Read replica**
```
ssh yb1.ssnc-corp.cloud ~/master/bin/yb-admin --master_addresses $MASTER_RPC_ADDRS add_read_replica_placement_info ssnc.us.kcrr:3 3 repl_uuid;
```

**Step 6:  Checked that the cluster config was:**
```
replication_info {
 live_replicas {
  num_replicas: 3
  placement_blocks {
   cloud_info {
    placement_cloud: “ssnc”
    placement_region: “us”
    placement_zone: “kc”
   }
   min_num_replicas: 3
  }
  placement_uuid: “prim_uuid”
 }
 read_replicas {
  num_replicas: 3
  placement_blocks {
   cloud_info {
    placement_cloud: “ssnc”
    placement_region: “us”
    placement_zone: “kcrr”
   }
   min_num_replicas: 3
  }
  placement_uuid: “repl_uuid”
 }
 multi_affinitized_leaders {
  zones {
   placement_cloud: “ssnc”
   placement_region: “us”
   placement_zone: “kc”
  }
 }
}
cluster_uuid: “9f8e60e1-8c39-4b5a-be33-5ad7952ba47c”
```
**Step 7: And then started T_Servers primary, followed by Read Replicas.**
But I see that all the Servers show up as Read Replicas, and the replica UUID repl_uuid does not show up on the console

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/11043998/181421834-8bc3bc85-b46b-42ef-b39c-3add6ed67ea3.png">
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/11043998/181421946-c525d532-4b17-460e-b1d4-26b013362f59.png">

**Step 8:** I also tried deleting the read replica placement and added again, but the config remains same.

**Core issue:** After each attempt, I also tried to create a database and to create a table on these servers. I tried from yb1 (intended primary) as well as ybr1 (intended replica). And in both cases I got the error : “ERROR: Not found: Table system.transactions not found: OBJECT_NOT_FOUND”. It feels like both are behaving as replicas.

So it seems like the UI is correct, but the cluster config is incorrect, since none of the servers I created, are allowing a CRUD.

**Comment by ddorian** [comment]
Why did you `set_preferred_zones` when you have only 1 zone/az/region in the primary cluster? Can you remove it and try again.

I'm assuming you followed this doc https://docs.yugabyte.com/preview/deploy/multi-dc/read-replica-clusters/, correct?


> Core issue: After each attempt, I also tried to create a database and to create a table on these servers. I tried from yb1 (intended primary) as well as ybr1 (intended replica). And in both cases I got the error : “ERROR: Not found: Table system.transactions not found: OBJECT_NOT_FOUND”. It feels like both are behaving as replicas.

You can also try creating a db/table with just the plain cluster, with no read-replicas configured yet.
