### ISSUE TITLE
[Docs] yb-tserver example includes a deprecated flag

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#13471]
### Description

The yb-tserver example in our documentation uses the `--start_pgsql_proxy` flag to enable YSQL.
https://docs.yugabyte.com/preview/reference/configuration/yb-tserver/#example

This flag is deprecated in favour of the `--enable_ysql` flag and should no longer be used.

**Comment by ddorian** [comment]
Fixed in https://github.com/yugabyte/yugabyte-db/commit/7a108f3640dd7271d7fa775a36a442c506cb7209
