### ISSUE TITLE
[DocDB] Master UI for encryption at rest breaks alignment

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13485]
Jira Link: [DB-3084](https://yugabyte.atlassian.net/browse/DB-3084)
### Description

<img width="827" alt="Screen Shot 2022-07-29 at 3 56 24 PM" src="https://user-images.githubusercontent.com/395011/181834423-411ea5a8-2245-4188-a1cd-0f4196b02967.png">

**Comment by Simonliuwaterloo** [comment]
Looks like this is already fixed. A scroller is added to the bottom so that the user can scroll horizontally.
![image](https://user-images.githubusercontent.com/40646603/189238228-596601de-322e-4c9c-86f5-990bd6ec6622.png)

**Comment by Simonliuwaterloo** [comment]
Looks like the intended problem this ticket was meant to document is:
From @bmatican:
> the slider is for the whole component, rather than just for the encryption status row… that leads to all the buttons on the previous rows floating to the right, so you have to scroll to click on things like See full config

Eg: 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/40646603/197826442-a63826f2-281e-4de0-9143-4336ab1be023.png">
