### ISSUE TITLE
[DocDB][xCluster] Add Packed Column Support

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#13523]
Jira Link: [DB-3115](https://yugabyte.atlassian.net/browse/DB-3115)
### Description

With #13084, we added the ability to parse a Packed Column WAL entry and send it to the consumer.  However, we have not solved Schema Compatibility issues between the Clusters.

#### Current State
1. PackedColumns performs Sparse Vector optimizations, so it needs ID/offset/len.  It stores this information in the Schema, so it just needs to reference Schema Version once then Packed_ID.
2. This information is not currently coordinated between clusters.  The existing requirements is only for coordinating set<pair<Col_ID, Type>>.  In addition to not propagating this new data structure, there are details that have lead us to keep the schema versions unaligned.  The Schema version could diverge due to internal work that is not applicable to normal data copying, like properties.  The current work can also support data copying from a Source to a Destination as long as the dest has all columns from the Source (e.g. upgrade flow).

#### Known Design Options
1. Unpack on Producer.  Easiest to implement if timing is an issue.  Performance issues may exist (given the success of Packed Column performance on normal WR path) or may be less substantial problems due to optimizations like network batching and more simplistic Consumer apply path.
2. Keep Packed.  Likely need to persist all CHANGE_METADATA OPs from the Producer on the Consumer for use in Packed Column lookup and reference as an external schema.  Will require some persistence and caching/state transition handling on the Consumer.  I’m assuming that this may be able to utilize some design patterns from thinking about this with XCluster’s safe_ht.

#### Initial "Keep Packed" Design Notes

- Packed Columns stores the Producer Table’s Schema Version.  PC users this version on decode for read. 
- Producer Version N is not necessarily related to Consumer Version N. 
- Version information is stored unencoded, so it should be easy to modify.
- If we have both cluster versions on the TServer cache, then instead of needing an explicit mapping, we just need to replace Producer Schema version with Consumer Schema version on apply.  No need to have an explicit mapping data structure.
-- With the new DDL changes (https://phabricator.dev.yugabyte.com/D17570), we will now stop replication if the Producer has columns that the Consumer does not.
-- Also with the new DDL changes, the current Producer Schema is stored in the ClusterConfig and cached in all Consumers.  The Tablet class has the current Consumer Schema.  That means, for any given point in time, we know that those two version are “data copy” compatible.

### Pending Investigations
- Verify whether “data copy” compatible has the same meaning compressed & uncompressed is the crux of the assumption we need to verify/investigate.  I explicitly asked this question in the meeting and Sergei replied that set<ID+Type> was the important overlap characteristics, which is the same for uncompressed.
- Verify/Investigate if Column Drops are an issue, specifically on Schema catchup.  We may need to tombstone dropped columns in the schema instead of removing them for this feature.  It wasn’t an issue on uncompressed because we would store the ID and any compaction of unused column IDs needed to follow the PITR retention.
- Note that this also “should” work when the Producer schema is BEHIND the Consumer Schema, since the Consumer Schema still contains the entire set<ID+Type> that we need.  Think if there are other non-add modifications to handle.

### Current Behavior

Version: `2.15.2.0-b58`

Steps:
1. Create universe(RF3)(let's say this universe as source) with Auth enabled and run **SqlDataLoad**(with 1500 columns) and **CassandraDataLoad** (with 10 columns) [ This universe is created with **2.15.2.0-b40** ]
4. Next day Upgrade to **2.15.2.0-b58** and follow bootstrap flow to create xCluster setup ( create target universe(RF3)(let's say this universe as target) with Auth enabled, take tables backup at source and restore at target and setup xCluster replication)
5. Enable packed column(add **ysql_enable_packed_row** gflag at both universes)
6. Observed the FATAL logs at Target universe

`F0804 12:53:04.257485 6905 tablet.cc:1354] T 368cd92d9905482ba212a4e632d77e7f P b9574e7e3dfc4663998cf6574d97ed2e: Failed to write a batch with 28198 operations into RocksDB: Corruption (yb/tablet/tablet_metadata.cc:245): Cannot find packing for table: 000033e6000030008000000000004005, schema version: 2`

**Comment by rthallamko3** [comment]
DUP of https://github.com/yugabyte/yugabyte-db/issues/14674
