### ISSUE TITLE
[Docs] The "rename_id" subcommand for "yb-admin alter_universe_replication" is undocumented

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#13530]
### Description

A subcommand for renaming xcluster replication streams was added in [10563](https://github.com/yugabyte/yugabyte-db/issues/10563) but was never added to the documentation.

This subcommand should be documented here:
https://docs.yugabyte.com/preview/admin/yb-admin/#alter-universe-replication

Example:

```
yb-admin -master_addresses <target_master_addresses> \
    alter_universe_replication <source_universe_uuid>_<replication_name> \
    rename_id <source_universe_uuid>_<new_replication_name>
```

*target_master_addresses*: Comma-separated list of target YB-Master hosts and ports. Default value is localhost:7100.
*source_universe_uuid*: The UUID of the source universe.
*replication_name*: The name of the replication to be altered.
*new_replication_name*: The new name of the replication stream

This subcommand is available starting in version 2.6.

**Comment by aishwarya24** [comment]
@ddorian Thank you for working on this. But I'm closing this one because the one I created addresses some other minor reorganization of sections.
