### ISSUE TITLE
Add Keyspace and Table type for each backup in the Backup tab

### ISSUE THREAD

**Issue by Arnav15** [YugaByte/yugabyte-db#1354]
<img width="1692" alt="Screen Shot 2019-05-10 at 4 47 42 PM" src="https://user-images.githubusercontent.com/14933889/57563410-76d9ab80-7352-11e9-9204-582b4eb60e1f.png">
Add columns showing the keyspace and the table type in the backup UI. We already have this information in the metadata for the backups, just need to update the UI to get the additional fields.

**Comment by yb-andrew** [comment]
@Arnav15 The UI now displays the KEYSPACE, however, I don't see any table type in the backup API call response, is this issue resolved already?
