### ISSUE TITLE
[Docs] Downgrade support

### ISSUE THREAD

**Issue by zamazan4ik** [yugabyte/yugabyte-db#13545]
### Description

Hi.

After reading the documentation it is not clear for me, how downgrade process should be performed over the solution. Could you please describe somewhere in the documentation:

- How to downgrade YugabyteDB to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by ddorian** [comment]
Hi @zamazan4ik 

Downgrades are not supported at this time.

> Maybe some compatibility policies and notes between versions

You can read the release notes between versions: https://docs.yugabyte.com/preview/releases/

**Comment by zamazan4ik** [comment]
> Downgrades are not supported at this time.

Could you please add this information into the documentation?
