### ISSUE TITLE
[YSQL] Transient error during manual rolling upgrade 

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#13552]
Jira Link: [DB-3133](https://yugabyte.atlassian.net/browse/DB-3133)
### Description

On an upgrade based on instructions from docs.
Seems to happen both for `2.8 -> 2.14` upgrade as well as `2.6 -> 2.12`.

To be investigated if this is a docs issue (wrong or missing step in the upgrade causing the problem) or a DB issue.

From @frozenspider's repro:

> I tried creating cluster on 2.8.2.0, killing master and starting master from 2.14.0.0 instead, and ysqlsh gave me an error:
> 
> 17:59 ~/apps/yugabyte-2.14.0.0 $ ./bin/ysqlsh
> ysqlsh: FATAL:  catalog is missing 7 attribute(s) for relid 2608
> 
> However, restarting 2.8's tserver didn't really help:
> 
> 18:01 ~/apps/yugabyte-2.14.0.0 $ ./bin/ysqlsh
> ysqlsh: FATAL:  catalog is missing 1 attribute(s) for relid 2672
> 
> Only after starting 2.14's master did ysqlsh manage to connect.
> 
> Just tried the same when going from 2.6.15 to 2.12.5 - and got the same error.

**Comment by yifanguan** [comment]
Issue resolved by commit: 117b2da39708b6977fd5d81145dfcf9bd318bb49.
