### ISSUE TITLE
[DocDB] Master metric 'is_load_balancing_enabled' displays inconsistent statistic value

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#13574]
Jira Link: [DB-3153](https://yugabyte.atlassian.net/browse/DB-3153)
### Description

In version 2.15.2.0-b83, when using the `/metrics` endpoint for the master server, the statistic `is_load_balancing_enabled ` shows the value: false.

However, the values for name/value combinations are always numeric, and therefore is inconsistent with other name/value statistics.

This is an excerpt from the /metrics page:
```
        "type": "cluster",
        "id": "yb.cluster",
        "attributes": {},
        "metrics": [
            {
                "name": "is_load_balancing_enabled",
                "value": false
            }
```
In general false should be '0' and true should be '1'.

**Comment by bmatican** [comment]
Hey @msun07 , hopefully small tweak to your recent work to add this metric -- let's make it a 0/1 metric, rather than true/false

I honestly didn't even know it's possible to setup a boolean metric, but I suspect some of our tooling would not be prepared for that.

**Comment by msun07** [comment]
Right, even for the `is_raft_leader_metric_`, we use a numeric metric.
Is "cluster" the right type for this metric? @fritshoogland-yugabyte @bmatican

**Comment by bmatican** [comment]
@msun07 I don't think we use many cluster type metrics, so a-ok to have this be server and we can standardize on tablet/table/server.

The problem here is more `METRIC_DEFINE_gauge_bool` so bool instead of int

**Comment by fritshoogland-yugabyte** [comment]
Yes, the name/value combinations always show a numeric value, like is_raft_leader.
I cannot answer the question about type.

Frits Hoogland | Developer Advocate
Mobile: +31-6-14180860
https://www.yugabyte.com
