### ISSUE TITLE
[DocDB] The statistic threads_running_thread_pool for YCQL shows incorrect value

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#13575]
Jira Link: [DB-3154](https://yugabyte.atlassian.net/browse/DB-3154)
### Description

When querying the metrics for the YCQL (12000) endpoint, I get the following values:
- metrics endpoint: 18446744073709551609
- prometheus-metrics endpoint: -7

These do not seem like realistic numbers to me, and therefore give the impression this statistic is broken.
I now find this value with version 2.15.2.0-b83, but witnessed this value for quite some time.

**Comment by bmatican** [comment]
@rthallamko3 , something to add to the tooling bucket. I'm also intrigued this shows up now, but didn't before, perhaps some components were moved around, leading to some reporting on the YCQL webserver?

**Comment by fritshoogland-yugabyte** [comment]
I noticed this for a very long time, but forgotten about it.
When I created yb_stats, I had a hard time dealing with it, and was glad I found a way to ignore this.
I guess this is showing these values as long as I know...

Frits Hoogland | Developer Advocate
Mobile: +31-6-14180860
https://www.yugabyte.com

**Comment by rthallamko3** [comment]
@yusong-yan , This is a good ramp up item about metrics.

**Comment by yusong-yan** [comment]
> This seems to have gone silent?

I already have the fix, and it is in the process of reviewing. Sorry for the delay!

**Comment by bmatican** [comment]
@fritshoogland-yugabyte For work in progress, you'd have to check Phabricator, or be explicitly added on those diffs as a subscriber. See https://phabricator.dev.yugabyte.com/D19359
