### ISSUE TITLE
First call with Spring data app (with JPA/Hibernate) fails

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#1358]
followed instructions in https://docs.yugabyte.com/latest/develop/build-apps/java/ysql-spring-data/

however, the very first curl command to create the first user always fails. retrying the operation succeeds. supposedly, this is because of a catalog version mismatch error.

**Comment by srhickma** [comment]
Fixed by https://github.com/YugaByte/yugabyte-db/commit/c7b3b0dae4e17ba56ea3a23e39fc21a474acdf3a. Tested locally with a hikari pool size of 8.
