### ISSUE TITLE
[DocDB] Inconsistent throughput of yb_sample_apps on Azure environment.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#13593]
Jira Link: [DB-3168](https://yugabyte.atlassian.net/browse/DB-3168)

**Description**: Per Jake's experiments: Azure's Hyper-V protocol for system clock ([TSC page](https://opensource.com/article/17/6/timekeeping-linux-vms))  is different than KVM's pvclock used in other cloud providers.  When you look at YugabyteDB platform's clock skew metric on GCP or AWS, it's always flat.  And chronyc sources output is nice and consistent:
```
#* PHC0            0   3   377     4    -24ns[ -166ns] +/-   37ns
#* PHC0            0   3   377     6    +13ns[  +49ns] +/-   32ns
#* PHC0            0   3   377     8    +49ns[ +182ns] +/-   28ns
#* PHC0            0   3   377    11    -43ns[ -113ns] +/-   24ns
#* PHC0            0   3   377     4    +60ns[ +152ns] +/-   18ns
```
but when you examine it on Azure, it's skewed all over the place:

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
```
MS Name/IP address         Stratum Poll Reach LastRx Last sample

===============================================================================
#* PHC0                          2   3     7     5   +283ns[+5543us] +/-  126us
#* PHC0                          2   3    17     7    +89ns[  +12us] +/- 3902ns
#* PHC0                          2   3    37     9  -2921ns[  +12us] +/- 4703ns
#* PHC0                          2   3    77    11  -1290ns[  -33us] +/- 4077ns
#* PHC0                          2   3   377     6  -3256ns[  -16us] +/- 3638ns
#* PHC0                          2   3   377     8    +18us[  +48us] +/- 3682ns
#* PHC0                          2   3   377     8    +19us[  +31us] +/- 4985ns
#* PHC0                          2   3   377    12  +1157ns[+4808ns] +/- 3184ns
#* PHC0                          2   3   377     5    +17us[  +30us] +/- 3686ns
```
I think this is causing inconsistent throughput for Azure workloads due to unnecessary leader elections; I can even see it with yb_sample_apps.  I feel like this issue should be elevated since customers will see this in our future managed Azure offering.

**Comment by robertsami** [comment]
captured the root cause here: https://github.com/yugabyte/yugabyte-db/issues/13637
