### ISSUE TITLE
[Docs] [API] Need SQL syntax for "Create tablespace" similar to "Create Table/Index" Under YSQL reference

### ISSUE THREAD

**Issue by sumitdatabase** [yugabyte/yugabyte-db#13614]
Jira Link: [DB-6388](https://yugabyte.atlassian.net/browse/DB-6388)
### Description

Copy from slack [discussion](https://yugabyte.slack.com/archives/CDQB8MEAU/p1660274313230269) 

In YSQL, we use tablespace for geo-locality and fault tolerance, this is documented as part of [geo-partitioning](https://docs.yugabyte.com/preview/explore/multi-region-deployments/row-level-geo-partitioning/#step-1-create-tablespaces) and [replica-placement](https://docs.yugabyte.com/preview/explore/ysql-language-features/going-beyond-sql/tablespaces/).

But what we need is a generic guides for create tablespace command under this path

Reference --> APIs --> YSQL --> The SQL language --> SQL statements section

Similar to what we have create database syntax for [example](https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_database/#syntax)

create_database ::= CREATE DATABASE name [ create_database_options ]

create_database_options ::= [ WITH ] [ OWNER [ = ] user_name ]  
                            [ TEMPLATE [ = ] template ]  
                            [ ENCODING [ = ] encoding ]  
                            [ LC_COLLATE [ = ] lc_collate ]  
                            [ LC_CTYPE [ = ] lc_ctype ]  
                            [ ALLOW_CONNECTIONS [ = ] allowconn ]  
                            [ CONNECTION LIMIT [ = ] connlimit ]  
                            [ IS_TEMPLATE [ = ] istemplate ]  
                            [ COLOCATED [ = ] { 'true' | 'false' } 

[DB-6388]: https://yugabyte.atlassian.net/browse/DB-6388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddhodge** [comment]
Also: DROP TABLESPACE, ALTER TABLESPACE; instructions/tutorial for dropping (ie, how to remove objects from tablespace before dropping)
And is [pg_tablespace](https://www.postgresql.org/docs/11/catalog-pg-tablespace.html) system catalog supported?
