### ISSUE TITLE
[DocDB] Disable enable_lease_revocation by default

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#13611]
Jira Link: [DB-3184](https://yugabyte.atlassian.net/browse/DB-3184)
### Description

To temporary work around the issue in #12758, we should disable the enable_lease_revocation flag.

**Comment by bmatican** [comment]
@yusong-yan note, we should backport this also to 2.14 and 2.12 (at least), as we saw this issue in 2.12. cc @rthallamko3

**Comment by rthallamko3** [comment]
@yusong-yan , Please backport this and then resolve the item.

**Comment by sharkberto** [comment]
@bmatican @rthallamko3 Didn't see the 2.14 backport which is why it's reopened

**Comment by bmatican** [comment]
That just landed, so closing back again
