### ISSUE TITLE
[DocDB] Do not add WAL entries larger than the amount that can be successfully replicated to tablet peers.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#13610]
Jira Link: [DB-3183](https://yugabyte.atlassian.net/browse/DB-3183)
### Description

We have seen cases where in large WAL entries are persisted on the tablet leader but cannot be successfully replicated to followers, leading to tablets getting into unhealthy/unusable state. Example customer issue - https://yugabyte.zendesk.com/agent/tickets/3861 

The fix in https://phabricator.dev.yugabyte.com/D16842 doesn't seem to handle the case where in a single WAL is larger than the limit.

**Comment by Huqicheng** [comment]
Backport to 2.6, 2.8, 2.12, 2.14
