### ISSUE TITLE
[DocDB] Load balancing after tablet splitting in clusters with more than RF # of nodes may cause excessive remote bootstrap

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#13637]
Jira Link: [DB-3201](https://yugabyte.atlassian.net/browse/DB-3201)
In a single region, 3 AZ, 6 node cluster, with automatic tablet splitting enabled, we notice intermittent bursts of remote bootstraps which impact user-facing throughput. We should consider strategies for mitigating the overhead of automatic tablet splitting. For example, maybe we should block the LB from adding/removing new nodes to a raft group for a tablet which was recently split, with the assumption being that raft groups in the same table with non-equal peer groups will split at a roughly similar rate in a hash-partitioned table.

**Comment by SrivastavaAnubhav** [comment]
Was not able to repro this.
 - I started an RF3 GCP universe 4 n1-standard-16 nodes (started with enable_tablet_splitting off for both tserver and master -> 32 tablets per tserver)
 - Preloaded data until we had 1GB compacted SSTs per tablet (5GB uncompacted) with CassandraBatchTimeseries
 - Enabled automatic tablet splitting
 - Observed remote bootstraps, but no drop in performance
