### ISSUE TITLE
[DocDB] Some client connections hang after master leader is restarted

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#13659]
Jira Link: [DB-3224](https://yugabyte.atlassian.net/browse/DB-3224)
### Description

Steps to repro (From Stepan):
run 20 nodes cluster with RF=5 (i think we can reproduce with less RF and nodes amount)
start sample-apps load - just inserts in SQL table with 20 columns, batch_size=700
java  -jar yb-sample-apps-1.8.15-b3.jar --workload SqlDataLoad  --num_writes -1 --num_threads_write 5 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000000 --batch_size 774 --num_value_columns 8
after 10 min stop AWS instance manually in AWS console
wait several minutes and then start it back
go in live queries tab on portal and see stuck query
Here is running universes with CDC configured (connector is killed right now, load is going) - http://10.9.66.35/universes/45a79116-0925-4e80-ac2a-f43c9ef254a0
Here is running universe without CDC - http://10.9.66.35/universes/38479ee9-3a1f-45fb-af1f-432be47fdf75
creds: [demo@yugabyte.com](mailto:demo@yugabyte.com) Password#123

The backtrace of the hang:

Thread 1 (LWP 23845):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fc045ac6748 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) ()
   from /home/yugabyte/yb-software/yugabyte-2.12.9.1-b1-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#2  0x00007fc046265d42 in _M_load_and_test_until (__ns=..., __s=..., __has_timeout=<optimized out>, __mo=<optimized out>, __equal=<optimized out>, __operand=<optimized out>, __assumed=<optimized out>, this=<optimized out>)
    at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/atomic_futex.h:104
#3  _M_load_and_test (__mo=<optimized out>, __equal=<optimized out>, __operand=<optimized out>, __assumed=<optimized out>, this=<optimized out>)
    at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/atomic_futex.h:122
#4  _M_load_when_equal (__mo=std::memory_order_acquire, __val=1, this=0x2bf3c10) at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/atomic_futex.h:162
#5  wait (this=0x2bf3c00) at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/future:322
#6  _M_get_result (this=0x7fff096b71d0) at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/future:681
#7  get (this=0x7fff096b71d0) at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/future:760
#8  yb::pggate::PgSession::FlushOperations (this=0x2422c40, ops=..., transactional=...) at ../../src/yb/yql/pggate/pg_session.cc:987
#9  0x00007fc046266209 in operator()<std::vector<yb::pggate::BufferableOperation>, yb::StronglyTypedBool<yb::pggate::IsTransactionalSession_Tag> > (txn=..., 
    ops=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __closure=<optimized out>) at ../../src/yb/yql/pggate/pg_session.cc:870
#10 std::_Function_handler<yb::Status(std::vector<yb::pggate::BufferableOperation, std::allocator<yb::pggate::BufferableOperation> >, yb::StronglyTypedBool<yb::pggate::IsTransactionalSession_Tag>), yb::pggate::PgSession::FlushBufferedOperations()::<lambda(auto:6, auto:7)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/yugabyte/yb-software/yugabyte-2.12.9.1-b1-centos-x86_64/lib/yb/libyb_pggate.so, CU 0x39f473, DIE 0x47889b>, <unknown type in /home/yugabyte/yb-software/yugabyte-2.12.9.1-b1-centos-x86_64/lib/yb/libyb_pggate.so, CU 0x39f473, DIE 0x4788a0>) (__functor=..., __args#0=<optimized out>, __args#1=<optimized out>)
    at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1857
#11 0x00007fc0462621ba in operator() (__args#1=..., __args#0=..., this=0x7fff096b7370) at /tmp/core/yugabyte-2.12.9.1/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#12 yb::pggate::PgSession::FlushBufferedOperationsImpl(std::function<yb::Status (std::vector<yb::pggate::BufferableOperation, std::allocator<yb::pggate::BufferableOperation> >, yb::StronglyTypedBool<yb::pggate::IsTransactionalSession_Tag>)> const&) (
    this=0x2422c40, flusher=...) at ../../src/yb/yql/pggate/pg_session.cc:898
#13 0x00007fc046262454 in yb::pggate::PgSession::FlushBufferedOperations (this=<optimized out>) at ../../src/yb/yql/pggate/pg_session.cc:870
#14 0x00007fc0462624c1 in yb::pggate::PgSession::StopOperationsBuffering (this=<optimized out>) at ../../src/yb/yql/pggate/pg_session.cc:860
#15 0x00007fc04624b218 in yb::pggate::PgApiImpl::StopOperationsBuffering (this=<optimized out>) at ../../src/yb/yql/pggate/pggate.cc:1078
#16 0x00007fc04623e63c in yb::pggate::YBCPgStopOperationsBuffering () at ../../src/yb/yql/pggate/ybc_pggate.cc:652
#17 0x0000000000a3b7d9 in YBEndOperationsBuffering () at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:1409
#18 0x00000000006d03c9 in standard_ExecutorFinish (queryDesc=0x34fdc38) at ../../../../../../src/postgres/src/backend/executor/execMain.c:447
#19 0x00007fc03a589875 in pgss_ExecutorFinish (queryDesc=0x34fdc38) at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:970
#20 0x00007fc03a3822b3 in ybpgm_ExecutorFinish (queryDesc=0x34fdc38) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:519
#21 0x0000000000888550 in ProcessQuery (isSingleRowModifyTxn=<optimized out>, completionTag=<optimized out>, dest=<optimized out>, queryEnv=<optimized out>, params=<optimized out>, sourceText=<optimized out>, plan=<optimized out>)
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:217
#22 PortalRunMulti (portal=portal@entry=0x26e4118, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0xed2760 <donothingDR>, dest@entry=0x25dc558, altdest=0xed2760 <donothingDR>, altdest@entry=0x25dc558, 
    completionTag=completionTag@entry=0x7fff096b78c0 "INSERT 0 1") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1331
#23 0x00000000008893f2 in PortalRun (portal=portal@entry=0x26e4118, count=count@entry=1, isTopLevel=isTopLevel@entry=true, run_once=<optimized out>, dest=dest@entry=0x25dc558, altdest=altdest@entry=0x25dc558, 
    completionTag=0x7fff096b78c0 "INSERT 0 1") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:811
#24 0x0000000000882a3c in exec_execute_message (max_rows=1, portal_name=0x25dc118 "") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:2066
#25 yb_exec_execute_message_impl (raw_ctx=raw_ctx@entry=0x7fff096b7c10) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4564
#26 0x0000000000881875 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x25dc000, restart_data=restart_data@entry=0x25dc528, functor=functor@entry=0x882760 <yb_exec_execute_message_impl>, 
---Type <return> to continue, or q <return> to quit---
    functor_context=functor_context@entry=0x7fff096b7c10) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4517
#27 0x0000000000886536 in yb_exec_execute_message (exec_context=0x25dc000, restart_data=0x25dc528, max_rows=<optimized out>, portal_name=<optimized out>) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4581

**Comment by bmatican** [comment]
Seems like the 2.12 base backport also landed 0a9521a0366c903b6476c25faa8bfde5269a448d, so good to close this
