### ISSUE TITLE
[Docs] Add documentation for pg_stat_progress_copy

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#13675]
Jira Link: [DB-3523](https://yugabyte.atlassian.net/browse/DB-3523)
### Description

We added [pg_stat_progress_copy](https://www.postgresql.org/docs/current/progress-reporting.html#COPY-PROGRESS-REPORTING) view in the YB. Mostly it is same as PostgreSQL with the following changes 

- tuples_processed  are the tuples which are already persisted in a transaction during the copy command.
- Retains copy command information in the view after the copy has finished. Though for specific session only the issued copy command status is retained.
- Add a status column to indicate the status of the copy command.

**Comment by polarweasel** [comment]
@sushantrmishra which database versions does this apply to? (In other words, how far back does this go in the docs?)

**Comment by polarweasel** [comment]
Sushant replied: 2.14 and 2.15
