### ISSUE TITLE
expose number of dead/unresponsive tservers as yb-master metric

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#1367]
The yb-master leader tracks yb-tserver heartbeats and knows which TServers haven't been able to heartbeat/have been unresponsive (determined by the`tserver_unresponsive_timeout_ms` setting).

The yb-master process exposes (via http://\<master-ip\>:7000/prometheus-metrics) a `num_tablet_servers_live` metric:

```
num_tablet_servers_live{ \
exported_instance="yb-1-xdc-user-identity-n1",\
metric_type="cluster",metric_id="yb.cluster"} \
<n> \
<timestamp> \
```

But a `num_tablet_servers_dead` (the inverse metric) might be more useful/easier for setting up alerts.  This number being greater than 0 could be set to result in an alert rather than basing the alert on the live number of nodes. The latter needs the alerting to be based on number of nodes in the system, and that itself could change over time.

Note: On yb-master followers this metric should simply return 0.

**Comment by bmatican** [comment]
One note on this is that we also need a way to GC information about old TS that maybe have just been removed. Right now, our TSDescriptor info sticks around for the duration of a master being a leader, so if a TS is decomissioned and replaced, we might still have a reference to the old TS in our memory for a while. cc @kmuthukk

**Comment by deeps1991** [comment]
@kmuthukk and @bmatican I was looking for a good first issue to get familiar with the contributing process, and this caught my eye. If this is not being actively worked on yet, please could you let me know if I could start on this one?

**Comment by bmatican** [comment]
@deeps1991 Happy to see you excited about YugaByte! You are correct, this is not actively being worked on. Would definitely love having you contribute, if you're interested!

Let me know if you need any more pointers about how to approach this task.

Also, in case you have not already signed our CLA, please use https://cla-assistant.io/YugaByte/yugabyte-db?pullRequest=1638 cc @mbautin

**Comment by kmuthukk** [comment]
+1 to what @bmatican said. Thanks @deeps1991 !

**Comment by deeps1991** [comment]
@bmatican From @kmuthukk's snippet above, I found the code that creates and updates this metric. So I can try to figure out the rest from there, will get back if I have questions. But what would be the best way for me to test this out? I was thinking to setup a local cluster, simulate a node failure (or maybe there is a unit test that does this as well?) and monitor the metrics page.

**Comment by kmuthukk** [comment]
@deeps1991 - that might sufficient for this metrics change. Your test plan looks good to me.

**Comment by bmatican** [comment]
Hey @deeps1991, wanted to circle back and just see if you needed any more input from our end on this?

Also, feel free to join us in our community slack channel if you'd like to sync up in real time: https://www.yugabyte.com/slack
