### ISSUE TITLE
[YSQL] Upsert throws incorrect unique key violation 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#13687]
Jira Link: [DB-3232](https://yugabyte.atlassian.net/browse/DB-3232)
### Description

Tested with YB version:

```
yugabyte=# select version();

               version

--------------------------------------------------------------------------
--------------------------------------------------------------------------
-------------------------------------
 PostgreSQL 11.2-YB-2.15.2.0-b0 on x86_64-pc-linux-gnu, compiled by clang
version 13.0.1 (https://github.com/yugabyte/llvm-project.git 191e3a05a55c8
671bcc88d7387c04c55a4310500), 64-bit
(1 row)
```

```
create table person (id int PRIMARY KEY,
first_name VARCHAR (50),
last_name  VARCHAR (50),
email      VARCHAR (50),
        UNIQUE(email)
);
CREATE TABLE
yugabyte=# INSERT into person values(1,'dasda','dasdas','s@yb');
INSERT 0 1
yugabyte=# INSERT into person values(1,'dasda','dasdas','s@yb');
ERROR:  duplicate key value violates unique constraint "person_pkey"
yugabyte=# set yb_enable_upsert_mode to true;
SET
yugabyte=# show yb_enable_upsert_mode;
 yb_enable_upsert_mode
-----------------------
 on
(1 row)

yugabyte=# INSERT into person values(1,'dasda','dasdas','s@yb');
ERROR:  duplicate key value violates unique constraint "person_email_key"
yugabyte=# INSERT into person values(1,'dasda','dasdas','s@yb');
yugabyte=# INSERT into person values(1,'dasda','dasdas','s@yba');
INSERT 0 1
yugabyte=# table person
yugabyte-# ;
 id | first_name | last_name | email
----+------------+-----------+-------
  1 | dasda      | dasdas    | s@yba
(1 row)
```
Through COPY also same observation.
The expected behaviour should be that if the value is in the same row which is being upserted then it should not throw error. Perhaps primary key can be checked. If they are same then ignore the constraint violation.

**Comment by lnguyen-yugabyte** [comment]
The following case illustrates why adding support for upsert on non unique index is non trivial:

```
create table t(v1 unique index int, v2 unique index char);

insert into t(v1, v2) values (1, 'a'), (2, 'b');

set yb_enable_upsert_mode to true;
insert into t(v1, v2) values (1, 'b');  <----- Unclear behavior
```

When inserting a row, we check the index table one at a time for each index. In this case, the index table contains:
idx1:
(1) -> (1, 'a')
(2) -> (2, 'b')

idx2:
('a') -> (1, 'a')
('b') -> (2, 'b')

On the upsert mode, we would end up with deleting both the (1, 'a') row (on the unique condition of idx1) and (2, 'b') row (on the unique condition of idx2). From the usability's perspective, this is not acceptable as it surprisingly deletes other rows in the table.

### Alternatives

We could add support for checking if a row matches exactly an existing row in the table; however, as it stands, it currently involves a lot of roundtrips to DocDB and defeats the purpose of upsert (which is to provide performance gain).

We could also disable upsert mode when inserting to table containing non unique index.

**Comment by tedyu** [comment]
Currently there is very terse description for the guc:
```
        {"yb_enable_upsert_mode", PGC_USERSET, CLIENT_CONN_STATEMENT,
            gettext_noop("Sets the boolean flag to enable or disable upsert mode for writes."),
```
We should either add a more detailed description or add a link to blog explaining the potential pitfall for this GUC.
Otherwise it is very easy to incur data loss when this GUC is enabled.

**Comment by tedyu** [comment]
Currently the GUC is marked with PGC_USERSET.

We should consider introducing another enum, named e.g. PGC_EXPERIMENTAL, which signifies that there may be certain pitfall when the GUC is enabled.

This (along with detailed description) would give users some awareness.

**Comment by kneeraj** [comment]
Thanks for explaining it @lnguyen-yugabyte and @tedyu.
I think a clear cut message saying that `upsert is not supported on tables with unique key constraint` is preferable in this case as otherwise the meaning of upsert is lost if we don't support this case.
