### ISSUE TITLE
[YSQL] Detect and mask uuid4s in result files of tests in the isolation regress suite

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#13690]
Jira Link: [DB-3235](https://yugabyte.atlassian.net/browse/DB-3235)
### Description

This is required because some isolation regress tests have results with error messages (like transaction conflicts) containing randomly generated transaction uuids. These need to be masked out to reliably compare against the expected test results.

**Comment by tedyu** [comment]
Does the uuid4s in the title mean uuids ?

**Comment by pkj415** [comment]
@tedyu yes it means uuids but the version 4 uuid specifically - refer https://datatracker.ietf.org/doc/html/rfc4122.html
