### ISSUE TITLE
[DocDB] Log leader uuid when denying a vote to a pre-election

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#13699]
Jira Link: [DB-3239](https://yugabyte.atlassian.net/browse/DB-3239)
### Description

We have the following log:
```
std::string msg = Format(
    "$0: Denying vote to candidate $1 for term $2 because replica is either leader or believes a "
    "valid leader to be alive. Time left: $3",
    GetRequestVoteLogPrefix(*request), request->candidate_uuid(), request->candidate_term(),
    withhold_votes_until_.load(std::memory_order_acquire) - MonoTime::Now());
```
We should log which replica we think is the leader.

**Comment by devnamrits** [comment]
Hi @SrivastavaAnubhav, @rthallamko3, Is anyone working on this? I would like to start my contribution to yugabyte. Can I pick this up?

**Comment by SrivastavaAnubhav** [comment]
Hi @devnamrits, welcome! Yes you can pick this up. I recommend you join the community slack channel, if you haven't already. It'll be easy to ask any questions you have there.

**Comment by devnamrits** [comment]
Hi @SrivastavaAnubhav, Thank you for assigning this to me. I will be setting up the project and picking this up. Also, I'll join the slack channel.

**Comment by devnamrits** [comment]
Hi @SrivastavaAnubhav , I've set up the project in my local. Can you please help me to reproduce this bug?

**Comment by SrivastavaAnubhav** [comment]
Hi @devnamrits , I've messaged you on Slack. Let's continue there.
