### ISSUE TITLE
[YSQL] Improve Index scan performance

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#13715]
Jira Link: [DB-3250](https://yugabyte.atlassian.net/browse/DB-3250)
### Description

Profile Index scan performance to find opportunities for optimizations. 

[DB-3250]: https://yugabyte.atlassian.net/browse/DB-3250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mtakahar** [comment]
The Apple Instrument CPU Profiler stats show that yb::docdb::QLRocksDBStorage::GetIterator is dominant in Index Scan with table row fetches whereas yb::docdb::DocRowwiseIterator::HasNext in Index Only Scan:

| | Index Only Scan | Index Scan |
| --- | --- | --- |
| yb::docdb::QLRocksDBStorage::GetIterator (*1) | 0.4% | 38.5% |
| yb::docdb::DocRowwiseIterator::DoInit (*1) | 0.4% | 28.3% |
| rocksdb::DBImpl::NewIterator (*1) | 0.2% | 10.4% |
| yb::docdb::DocRowwiseIterator::HasNext (*2) | 77.1% | 43.3% |
| yb::docdb::SeekForward (*2) | 10.0% | 9.6% |
| rocksdb::DBIter::Seek | 0.2% | 10.6% |
| rocksdb::DBIter::Next (*2) | 5.5% | 6.0% |
| yb::docdb::ScanChoices::DecodeKeyEntryValue | 23.8% | 6.8% |

*1 … Appears in the heaviest stack trace of Index Scan

*2 … Appears in the heaviest stack trace of Index Only Scan

The test data/queries/plans:
* Single node local cluster on a MacBook Pro (8-core).
* The EXPLAIN outputs using a prototype feature printing the RPC stats.
* Recorded 5 executions each with Apple Instruments CPU Profiler after a dummy run to avoid influence of system catalog loading.
```
CREATE TABLE t1(k1 int,
                k2 text,
                v1 int,
                v2 text,
                PRIMARY KEY(k1 ASC, k2 ASC));
CREATE INDEX ON t1(v1 ASC, k2 ASC);

INSERT INTO t1
SELECT
  i/4, rpad(i::text, 20, '-'),
  i/4, rpad(i::text, 20, '-')
FROM generate_series(1, 200000) i;
```
Index Only Scan:

```
explain (analyze, rpc) select v1, k2 from t1 where v1 <= 10000;
                                                           QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------
 Index Only Scan using t1_v1_k2_idx on t1  (cost=0.00..15.25 rows=100 width=36) (actual time=12.895..338.909 rows=40003 loops=1)
   Index Cond: (v1 <= 10000)
   Heap Fetches: 0
 Planning Time: 0.045 ms
 Execution Time: 341.737 ms
 Peak Memory Usage: 0 kB
(9 rows)
```
Index Scan:
```
explain (analyze, rpc) select k1, k2 from t1 where v1 <= 10000;
                                                         QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------
 Index Scan using t1_v1_k2_idx on t1  (cost=0.00..16.25 rows=100 width=36) (actual time=33.638..670.148 rows=40003 loops=1)
   Index Cond: (v1 <= 10000)
 Planning Time: 0.050 ms
 Execution Time: 672.888 ms
 Peak Memory Usage: 8 kB
(10 rows)
```

**Comment by mtakahar** [comment]
Table row fetches by ybctid is executed in batches, and unlike Postgres' ctid, which is a direct row locator by (block id, offset), ybctid is a unique key.  This is similar to `SELECT ... FROM t WHERE ybctid IN (...)` but executed in a dedicated code path via [yb::docdb::PgsqlReadOperation::ExecuteBatchYbctid](https://github.com/yugabyte/yugabyte-db/blob/a6078d00c4f46f195c0b0fea77238bd7b4dfe7e3/src/yb/docdb/pgsql_operation.cc#L1292) instead of [yb::docdb::PgsqlReadOperation::ExecuteScalar](https://github.com/yugabyte/yugabyte-db/blob/a6078d00c4f46f195c0b0fea77238bd7b4dfe7e3/src/yb/docdb/pgsql_operation.cc#L1097).

**ExecuteBatchYbctid**:
* For each ybctid in the batched request, it calls `yb::docdb::QLRocksDBStorage::GetIterator` then fetches the row.
* A `yb::docdb::DocRowwiseIterator` is instantiated and destroyed as many times as the number of ybctid in the batch.

**IN-list search via ExecuteScalar**:
* The IN-list items are sorted by pggate before sending the request to docdb.
* A `yb::docdb::DocRowwiseIterator` is instantiated with `HybridScanChoices` only once.
* After finding each matching row, HybridScan seeks to the next item in the IN-list.

In addition to the repeated iterator re-instantiation/destruction overhead, `ExecuteBatchYbctid`'s access pattern of "seeking" to each individual ybctid has to perform binary search against the entire range every time.

In case of Hybrid Scan using the same iterator for the sorted values, the search range is narrowed in each iteration.

**Comment by mtakahar** [comment]
Did additional experiments to see:
* How the Hybrid Scan compares against `ExecuteBatchYbctid`.
* How the index key order to table row order correlations affect the performance and the heaviest code paths. (The previous experiment was using fully correlated data.)


Test Method
-----------
* Measure the remote execution timing using the experimental change that shows the RPC read request wait time in EXPLAIN ANALYZE.
* Run the queries 6 times each and take average of the 2nd ... 6th execution.
* Capture the heaviest stack traces with the Apple Instrument counter-based CPU profiler. Execute each query 5 times each, separately from the time measuring sessions.

The data & the queries used in these experiments:
```
DROP TABLE t1;
CREATE TABLE t1(k1 int, k2 int, k3 int, v1 char(20), v2 char(20), PRIMARY KEY(k1 ASC));

-- the values in i2 prefixed with hash values to randomize the table row order
INSERT INTO t1
  SELECT i2, i, i2, rpad(i2::text, 20, '-'), rpad(i2::text, 20, '-')
    FROM (SELECT i, i|(yb_hash_code(i)<<18) as i2 FROM generate_series(1, 200000) i) v;

-- index key order does not match the table row order
CREATE INDEX i_t1_k2 on t1 (k2 ASC, v1 ASC);

-- index key order matches the table row order
CREATE INDEX i_t1_k3 on t1 (k3 ASC, v1 ASC);

-- for comparison against hybrid scan (IN-list)
CREATE INDEX i_t1_v1 on t1 (v1 ASC);
```


1024 row test:
```
-- index only scan with IN-list
-- the IN-list generated by: SELECT ' IN ('''||string_agg(v1,''',''')||''')' FROM t1 WHERE k2 <= 1024;
SELECT v1 FROM t1 WHERE v1
  IN ('1212153857----------','51380226------------','-226492413----------',
      '2059141124----------','701235205-----------',
      ...
      '-1563950083---------','-1440218114---------','780141567-----------',
      '-1964506112---------'
      );

-- index scan with IN-list + unordered table fetches
-- the IN-list generated by: SELECT ' IN ('||string_agg(k2::text,',')||')' FROM t1 WHERE k2 <= 1024;
SELECT v2 FROM t1 WHERE k2
IN (1,2,3,4,5,6,7,8,9,10,
    ...
    1021,1022,1023,1024
);

-- index scan with IN-list + ordered table fetches
-- the IN-list generated by: SELECT ' IN ('||string_agg(k3::text,',')||')' FROM t1 WHERE k2 <= 1024;
SELECT v2 FROM t1 WHERE k3
IN (1212153857,51380226,-226492413,
    2059141124,701235205,
    ...
    -1563950083,-1440218114,780141567,
    -1964506112
);

```

20480 row test:
```
-- index only scan
SELECT v1 FROM t1 WHERE k2 <= 20480;

-- index scan, unordered table row fetches
SELECT v2 FROM t1 WHERE k2 <= 20480;

-- index scan, ordered table rows
-- (-1704810723 is the 20480th largest value of k3, i.e.: select max(k3) from (select k3 from t1 order by k3 limit 20480) v1;)
SELECT v2 FROM t1 WHERE k3 <= -1704810723;
```

Results
-------
* The full execution log and the heaviest stack traces attached.


1. Compare the remote execution time of Index Only Scan with IN-list and unordered/ordered Table row fetches. Fetch 1024 rows (1 batch).

||Index Only|Index + Unordered Table Fetches|Index + Ordered Table Fetches|
| --- | ---: | ---: | ---: |
|Overall Exec Time (ms)|19.774|28.822|29.886|
|Remote Index Exec Time (ms)|**10.118**|8.166|10.302|
|Remote Table Exec Time (ms)|n/a|**17.559**|**16.428**|

2. Compare the remote execution time of Index Only Scan and unordered/ordered Table row fetches for range query. Fetch 20480 rows (20 batches).

||Index Only|Index + Unordered Table Fetches|Index + Ordered Table Fetches|
| --- | ---: | ---: | ---: |
|Overall Exec Time (ms)|150.949|373.558|332.574|
|Remote Index Exec Time (ms)|**142.163**|7.432|7.368|
|Remote Table Exec Time (ms)|n/a|**352.93**|**317.195**|


Takeaways
---------
* Although not a perfect apple-to-apple comparison, the Hybrid Scan is noticeably faster than `ExecuteBatchYbctid`. (~10 vs. ~16 .. 17 ms)
* The difference between unordered vs. ordered table row fetches is not much but measurable in this experiment. (unordered cases ~7 .. 10% slower)

Next Step
---------
* Modify the code to use Hybrid Scan for table row fetches by ybctid and compare the performance.
* Make sure possible optimizations using the knowledge of uniqueness are in place in the Hybrid Scan code path. Implement them if not done yet. e.g.: (there may be more)
  * Don't try to find another match of the same value.
  * Stop looking for a match in multiple places (memtable, multiple SST files) as soon as finding a match.
[heaviest-stack-1024rows-index-only.txt](https://github.com/yugabyte/yugabyte-db/files/9590697/heaviest-stack-1024rows-index-only.txt)
[heaviest-stack-1024rows-index-scan-ordered-table-fetches.txt](https://github.com/yugabyte/yugabyte-db/files/9590698/heaviest-stack-1024rows-index-scan-ordered-table-fetches.txt)
[heaviest-stack-1024rows-index-scan-unordered-table-fetches.txt](https://github.com/yugabyte/yugabyte-db/files/9590699/heaviest-stack-1024rows-index-scan-unordered-table-fetches.txt)
[heaviest-stack-20480rows-index-only.txt](https://github.com/yugabyte/yugabyte-db/files/9590700/heaviest-stack-20480rows-index-only.txt)
[heaviest-stack-20480rows-index-scan-ordered-table-fetches.txt](https://github.com/yugabyte/yugabyte-db/files/9590701/heaviest-stack-20480rows-index-scan-ordered-table-fetches.txt)
[heaviest-stack-20480rows-index-scan-unordered-table-fetches.txt](https://github.com/yugabyte/yugabyte-db/files/9590702/heaviest-stack-20480rows-index-scan-unordered-table-fetches.txt)
[test2a.log](https://github.com/yugabyte/yugabyte-db/files/9590706/test2a.log)

**Comment by mtakahar** [comment]
Potential Solutions
---
* There are several properties specific to table row fetch by ybctid from secondary index:
  * Must return the rows in the secondary index key order if Postgres optimizer have eliminated explicit sort and/or chosen some execution nodes that require sorted input for ORDER BY, GROUP BY/DISTINCT, MergeJoin, etc.
  * Each ybctid is guaranteed to exist uniquely in the table.
  * Single key item (no composite access key)


A) Use the IN-list search code path (DocRowwiseIterator with either HybridScanChoices or DiscreteScanChoices):
  * This approach requires sorting the incoming ybctid values before scanning. In order to satisfy the output row order, scanned rows must be sorted by the secondary index key order.
    * The post-scan sort should be performed against each batch instead of the entire results in order to minimize the cost.
    * Post-scan sort can be omitted if the plan does not require sorted output.
  * HybridScanChoices vs. DiscreteScanChoices:
    * DiscreteScanChoices would be faster than HybridScanChoices because of the limited feature and simpler implementation.
    * DiscreteScanChoices is currently disabled by default along with RangeBasedScanChoices in favor of HybridScanChoices, and removing those ScanChoices in the future helps simplify the HybridScanChoices logic and the code. Re-purposing DiscreteScanChoices limits such opportunity.

B) Change ybctid from index lookup key to direct access by row locator:
  * This approach should bring our table fetch performance nearly on par with Aurora.
  * This would require:
    * Changing the underlying table data structure from primary key index to a simple heap table so that the row do not move around with table data modifications.
    * Upgrade considerations - table & ybctid format conversions, rolling upgrade, etc.

**Comment by tanujnay112** [comment]
For solution A, we wouldn't have to create a separate ScanChoices as we can repeatedly invoke [this](https://github.com/yugabyte/yugabyte-db/blob/ff79b5c7aba5f430986a7cb989f62fd9bfe49783/src/yb/docdb/doc_rowwise_iterator.cc#L1631) method right here.

**Comment by mtakahar** [comment]
@tanujnay112 put together a prototype that reuses the iterator as he pointed out. The change is much simpler than rewiring the code to use the full-blown HybridScan, but it works pretty similar.

Here's the results I tried on my MacBook Pro:

Correlated Index-Table Rows
---
1-node:
|Rows fetched|Index (ms)(before)|Table (ms)(before)|Index (ms)(after)|Table (ms)(after)|
| ---: | ---: | ---: | ---: | ---: |
|10|0.4|0.5|0.4|0.4|
|100|0.8|1.8|0.8|1.1|
|1000|4.8|20.3|5.5|13.4|
|10000|5.5|154.5|5.4|78.7|
|100000|5.2|1468.4|5.1|712.6|
|1000000|5.4|14748.6|5.3|7051.7|

3-node:
|Rows fetched|Index (ms)(before)|Table (ms)(before)|Index (ms)(after)|Table (ms)(after)|
| ---: | ---: | ---: | ---: | ---: |
|10|0.4|0.8|0.4|0.6|
|100|0.8|2.0|0.8|1.3|
|1000|4.9|22.0|5.6|14.5|
|10000|5.6|165.3|5.5|81.9|
|100000|5.2|1552.0|5.1|803.9|
|1000000|5.5|15536.4|5.3|7970.7|

Uncorrelated Index-Table Rows
---
1-node:
|Rows fetched|Index (ms)(before)|Table (ms)(before)|Index (ms)(after)|Table (ms)(after)|
| ---: | ---: | ---: | ---: | ---: |
|10|5.9|24848.8|5.6|13880.5|
|100|6.1|24365.4|6.2|13936.4|
|1000|5.9|24366.8|6.4|13924.3|
|10000|5.8|24444.3|6.2|13827.6|
|100000|6.0|24330.8|6.3|13786.3|
|1000000|6.0|24353.0|6.0|13822.2|

3-node:
|Rows fetched|Index (ms)(before)|Table (ms)(before)|Index (ms)(after)|Table (ms)(after)|
| ---: | ---: | ---: | ---: | ---: |
|10|6.6|25973.9|5.8|16690.0|
|100|6.1|26032.7|6.6|16531.8|
|1000|6.0|26016.8|6.6|16634.0|
|10000|6.4|26034.3|6.6|16557.7|
|100000|6.1|26005.3|6.7|16564.6|
|1000000|5.9|26012.7|6.7|16552.5|

Apple Instrument
---
*The heaviest stack now shows the Seek methods at each layer instead of `yb::docdb::QLRocksDBStorage::GetIterator`.
```
  44  28745.0  yb-tserver (66590) :0
  43 libsystem_pthread.dylib 28744.0  thread_start
  42 libsystem_pthread.dylib 28744.0  _pthread_start
  41 libyb_util.dylib 28681.0  yb::Thread::SuperviseThread(void*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/util/thread.cc:776
  40 libyb_util.dylib 28681.0  std::__1::function<void ()>::operator()() const [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/functional:2560
  39 libyb_util.dylib 28681.0  std::__1::__function::__value_func<void ()>::operator()() const [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/functional:1885
  38 libyrpc.dylib 28204.0  yb::rpc::(anonymous namespace)::Worker::Execute() /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rpc/thread_pool.cc:104
  37 libyrpc.dylib 28121.0  yb::rpc::InboundCall::InboundCallTask::Run() /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rpc/inbound_call.cc:241
  36 libyrpc.dylib 28120.0  yb::rpc::ServicePoolImpl::Handle(std::__1::shared_ptr<yb::rpc::InboundCall>) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rpc/service_pool.cc:270
  35 libtserver_service_proto.dylib 27155.0  yb::tserver::TabletServerServiceIf::Handle(std::__1::shared_ptr<yb::rpc::InboundCall>) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/src/yb/tserver/tserver_service.service.cc:531
  34 libtserver_service_proto.dylib 27155.0  std::__1::function<void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/functional:2560
  33 libtserver_service_proto.dylib 27155.0  std::__1::__function::__value_func<void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) const [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/functional:1885
  32 libtserver_service_proto.dylib 27154.0  std::__1::__function::__func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1, std::__1::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/functional:1732
  31 libtserver_service_proto.dylib 27154.0  std::__1::__function::__alloc_func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1, std::__1::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/functional:1558
  30 libtserver_service_proto.dylib 27154.0  void std::__1::__invoke_void_return_wrapper<void, true>::__call<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, std::__1::shared_ptr<yb::rpc::InboundCall> >(yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, std::__1::shared_ptr<yb::rpc::InboundCall>&&) [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__functional_base:348
  29 libtserver_service_proto.dylib 27154.0  decltype(std::__1::forward<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&>(fp)(std::__1::forward<std::__1::shared_ptr<yb::rpc::InboundCall> >(fp0))) std::__1::__invoke<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, std::__1::shared_ptr<yb::rpc::InboundCall> >(yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, std::__1::shared_ptr<yb::rpc::InboundCall>&&) [inlined] /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/type_traits:3694
  28 libtserver_service_proto.dylib 27154.0  yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/src/yb/tserver/tserver_service.service.cc:561
  27 libtserver_service_proto.dylib 27154.0  auto yb::rpc::HandleCall<yb::rpc::RpcCallPBParamsImpl<yb::tserver::ReadRequestPB, yb::tserver::ReadResponsePB>, yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)>(std::__1::shared_ptr<yb::rpc::InboundCall>, yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)) [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rpc/local_call.h:117
  26 libtserver_service_proto.dylib 27150.0  yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)::operator()(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) const [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/src/yb/tserver/tserver_service.service.cc:563
  25 libtserver.dylib 27150.0  yb::tserver::TabletServiceImpl::Read(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/tablet_service.cc:1897
  24 libtserver.dylib 27150.0  yb::tserver::PerformRead(yb::tserver::TabletServerIf*, yb::tserver::ReadTabletProvider*, yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/read_query.cc:734
  23 libtserver.dylib 27138.0  yb::tserver::(anonymous namespace)::ReadQuery::Perform() [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/read_query.cc:107
  22 libtserver.dylib 27138.0  yb::tserver::(anonymous namespace)::ReadQuery::DoPerform() /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/read_query.cc:446
  21 libtserver.dylib 27061.0  yb::tserver::(anonymous namespace)::ReadQuery::Complete() /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/read_query.cc:504
  20 libtserver.dylib 26552.0  yb::tserver::(anonymous namespace)::ReadQuery::DoRead() [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/read_query.cc:587
  19 libtserver.dylib 26540.0  yb::tserver::(anonymous namespace)::ReadQuery::DoReadImpl() [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tserver/read_query.cc:697
  18 libtablet.dylib 26478.0  yb::tablet::Tablet::HandlePgsqlReadRequest(std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, bool, yb::PgsqlReadRequestPB const&, yb::TransactionMetadataPB const&, yb::SubTransactionMetadataPB const&, yb::tablet::PgsqlReadRequestResult*, unsigned long*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tablet/tablet.cc:1552
  17 libtablet.dylib 26468.0  yb::tablet::AbstractTablet::ProcessPgsqlReadRequest(std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, bool, yb::PgsqlReadRequestPB const&, std::__1::shared_ptr<yb::tablet::TableInfo> const&, yb::TransactionOperationContext const&, yb::tablet::PgsqlReadRequestResult*, unsigned long*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/tablet/abstract_tablet.cc:104
  16 libyb_docdb.dylib 26416.0  yb::docdb::PgsqlReadOperation::Execute(yb::docdb::YQLStorageIf const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, bool, yb::docdb::DocReadContext const&, yb::docdb::DocReadContext const*, yb::faststring*, yb::HybridTime*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/docdb/pgsql_operation.cc:960
  15 libyb_docdb.dylib 16766.0  yb::docdb::PgsqlReadOperation::ExecuteBatchYbctid(yb::docdb::YQLStorageIf const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, yb::docdb::DocReadContext const&, yb::faststring*, yb::HybridTime*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/docdb/pgsql_operation.cc:1348
  14 libyb_docdb.dylib 14433.0  yb::docdb::DocRowwiseIterator::SeekTuple(yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/docdb/doc_rowwise_iterator.cc:1660
  13 libyb_docdb.dylib 9837.0  yb::docdb::IntentAwareIterator::Seek(yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/docdb/intent_aware_iterator.cc:289
  12 libyb_docdb.dylib 9816.0  yb::docdb::PerformRocksDBSeek(rocksdb::Iterator*, yb::Slice const&, char const*, int) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/docdb/docdb_rocksdb_util.cc:308
  11 libyb_docdb.dylib 5367.0  yb::docdb::SeekPossiblyUsingNext(rocksdb::Iterator*, yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/docdb/docdb_rocksdb_util.cc:289
  10 librocksdb.dylib 4970.0  rocksdb::DBIter::Seek(yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/db/db_iter.cc:759
   9 librocksdb.dylib 4874.0  rocksdb::MergingIterator::Seek(yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/merger.cc:150
   8 librocksdb.dylib 4793.0  rocksdb::IteratorWrapper::Seek(yb::Slice const&) [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/iterator_wrapper.h:126
   7 librocksdb.dylib 4699.0  rocksdb::(anonymous namespace)::TwoLevelIterator::Seek(yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/two_level_iterator.cc:115
   6 librocksdb.dylib 2087.0  rocksdb::IteratorWrapper::Seek(yb::Slice const&) [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/iterator_wrapper.h:126
   5 librocksdb.dylib 2084.0  rocksdb::BlockIter::Seek(yb::Slice const&) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/block.cc:190
   4 librocksdb.dylib 1190.0  rocksdb::BlockIter::BinarySeek(yb::Slice const&, unsigned int, unsigned int, unsigned int*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/block.cc:390
   3 librocksdb.dylib 1096.0  rocksdb::DecodeRestartEntry(rocksdb::KeyValueEncodingFormat, char const*, char const*, char const*, unsigned int*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/block.cc:118
   2 librocksdb.dylib 1087.0  rocksdb::DecodeEntryThreeSharedParts(char const*, char const*, char const*, unsigned int*, unsigned int*, long long*, bool*, unsigned int*, long long*, unsigned int*, unsigned long long*, unsigned int*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/table/block_internal.h:135
   1 librocksdb.dylib 1060.0  rocksdb::GetVarint64Ptr(char const*, char const*, unsigned long long*) [inlined] /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/util/coding.h:171
   0 librocksdb.dylib 11.0  rocksdb::GetVarint64PtrFallback(char const*, char const*, unsigned long long*) /Users/mtakahara/code/yugabyte-db5/build/release-clang-dynamic-ninja/../../src/yb/rocksdb/util/coding.cc:87
```
