### ISSUE TITLE
Create scheduled backup for YB tables

### ISSUE THREAD

**Issue by hlinhz** [yugabyte/yugabyte-db#1371]
We need to create weekly scheduled backups for our YB tables, this will be a workaround until YB launch official automatic backup feature in the future.

**Comment by rkarthik007** [comment]
@ramkumarvs / @Arnav15 - ask here is the following:
- How to create a backup using a script (say in python). We can share a snippet in this issue comments itself, and then consolidate into docs.
- How to add that into the cron so that a "nightly" backup can be automated.

**Comment by ramkumarvs** [comment]
Assign this to @stevebang for the documentation.

**Comment by rkarthik007** [comment]
> Assign this to @stevebang for the documentation.

This seems to be tracked here: https://github.com/yugabyte/yugabyte-db/issues/1579

Closing this issue.
