### ISSUE TITLE
Add support for jsonb datatype in the YCQL go driver

### ISSUE THREAD

**Issue by sanjimoh** [YugaByte/yugabyte-db#1373]
My table has a jsonb type column onto which while trying to insert a value is resulting an error with message "**can not marshal string into unknown_type_128**".

I'm trying to pass a json string through gocql apis, something like this. Is there something I'm not doing causing this or this is some bug? How do I resolve this? Unfortunately not enough example in yugabyte documentations from a gocql client perspective in such use cases.

`		b := bw.session.NewBatch(gocql.LoggedBatch)
		for i := 0; i < 1000; i++ {
			id := bw.rand.Int63()
                        //jsondata is a json string
			jsondata := generateJsonContents()
			b.Query(insertStmt, id, jsondata)
		}
		_ := bw.session.ExecuteBatch(goCqlbatch);
`
Table definition in yugabyte -
`cqlsh:sanjit> DESCRIBE abcd_tbl;

CREATE TABLE sanjit.abcd_tbl (
    id bigint PRIMARY KEY,
    attr jsonb
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
`

**Comment by rkarthik007** [comment]
Hi @sanjimoh,

We have been enhancing the vanilla cql drivers to add support for the `JSONB` datatype. We have not yet done this for the `gocql` driver, will use this issue to track that work. Thanks for filing!

Do you mind changing the title of the issue to `Add support for jsonb datatype in the YCQL go driver`.

**Comment by sanjimoh** [comment]
Thanks! Updated the subject as requested.

**Comment by rajukumaryb** [comment]
@sanjimoh - Please use YugaByte's fork of gocql - "github.com/yugabyte/gocql" in place of "github.com/gocql/gocql" in the example. You will have to "go get github.com/yugabyte/gocql".

JSONB related documentation is available at - https://docs.yugabyte.com/latest/api/ycql/type_jsonb/
