### ISSUE TITLE
Add a Health Check to detect under replicated tablets

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1374]
Add a Health Check to detect under replicated tablets.
We should ignore the transient state and report only when the cluster is at risk when you lose an additional replica.

**Comment by bmatican** [comment]
One component of #1834 will involve figuring out how to query this from the various TS, or how to tell if this is an issue. Once we bubble this up in, say, the master leader UI, then we can route our devops health checker to that and augment it.

cc @ramkumarvs @nspiegelberg

**Comment by psudheer21** [comment]
Commited with the commit:bc35d5c
