### ISSUE TITLE
[YSQL] YSQL does not support PG 11's "recursive" view

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#13751]
Jira Link: [DB-3279](https://yugabyte.atlassian.net/browse/DB-3279)
### Description

The PostgreSQL Version 11 documentation for [create view](https://www.postgresql.org/docs/11/sql-createview.html) describes the meaning of the _recursive_ keyword. Here's a simple example:

```
\c postgres postgres
set client_min_messages = warning;
drop database if exists play;
create database play owner postgres;
--------------------------------------------------------------------------------

\c play postgres
set search_path = public;

-- "recursive" view demo.
create recursive view r(n) as
values(1)
union all
select n + 1
from r
where n < 5;

select n from r order by n;

-- Workaround
create or replace view r(n) as
with
  recursive c(n) as (
    values(1)
    union all
    select n + 1
    from c
    where n < 5
  )
select n from c;

select n from r order by n;
--------------------------------------------------------------------------------

\c postgres postgres
set client_min_messages = warning;
drop database if exists play;
```

It runs without error using PG Version 11. Each execution of _"select n from r order by n"_  produces the same result, thus:

```
 n 
---
 1
 2
 3
 4
 5
```

The same testcase using 11.2-YB-2.15.0.1 fails at this attempt:

```
create or replace recursive view r(n) as ...
```

It causes this warning:

```
CREATE RECURSIVE VIEW not supported yet
```

And the hint says to file a GitHub issue. This is that issue.

The workaround is trivial: simply define the view like the "Workaround" _"create view"_ statement in the example does. But the absence of YB support for this ordinary PG feature will harm migration attempts when the feature has been used in the to-be-migrated PG env.

### Short term ask

In the short term, please change the "hint" text to refer to this issue and to recommend upvoting it.

**Comment by tedyu** [comment]
It seems by dropping the unsupported restriction, the recursive view above works as expected:
```
yugabyte=# create recursive view r(n) as
yugabyte-# values(1)
yugabyte-# union all
yugabyte-# select n + 1
yugabyte-# from r
yugabyte-# where n < 5;
CREATE VIEW
yugabyte=# select n from r order by n;
 n
---
 1
 2
 3
 4
 5
(5 rows)
```
@nocaway Can you let me know if there is some reason recursive view is disabled in YB ?

cc @sushantrmishra

**Comment by def-** [comment]
> In the short term, please change the "hint" text to refer to tis issue and to recommend upvoting it.

I'll provide a change for that.
