### ISSUE TITLE
[DocDB] Master UI page fails when https is enabled and node is not master leader 

### ISSUE THREAD

**Issue by charleswang234** [yugabyte/yugabyte-db#13779]
Jira Link: [DB-3298](https://yugabyte.atlassian.net/browse/DB-3298)
### Description

See image below. The Master UI page works fine when the current master UI we are visiting is the master leader. Otherwise, we will fail to get the correct information.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/25140554/186754023-e670bade-70d9-4728-b6b7-501cce74b4a1.png">

**Comment by es1024** [comment]
Fixed with b737017
