### ISSUE TITLE
[ThreadSanitizer Data Race] Observed in CppCassandraDriverTest.TestTableBackfillWithLeaderMoves

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#13794]
Jira Link: [DB-3310](https://yugabyte.atlassian.net/browse/DB-3310)
### Description

Log https://gist.github.com/kripasreenivasan/0aebc02546f55ac891bbaa1e9fe097c1 
Suspected commit: aca442b37c068e22f600cf3af1f5e94aef207622 
CC: @mbautin

**Comment by druzac** [comment]
This test is no longer flaky on TSAN.
