### ISSUE TITLE
[ThreadSanitizer UT failure] CqlTabletSplitTest.SecondaryIndexWithDrop failing with thread sanitizer issue

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#13792]
Jira Link: [DB-3308](https://yugabyte.atlassian.net/browse/DB-3308)
### Description

Log: https://gist.github.com/kripasreenivasan/82faa79d48fc7c6bfd420da2ef02b3a1 

Suspected commit: aca442b37c068e22f600cf3af1f5e94aef207622

Ran a git blame on the files in the stack trace and the commits seem very old.

CC: @mik

**Comment by bmatican** [comment]
Hey Oleg, are you familiar with the `CQLNodeListRefresh` codepath? seems there's a race condition between that and shutdown, might be easy to fix, with context.

**Comment by m-iancu** [comment]
Closing, this test looks reasonable stable now: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CqlTabletSplitTest&fail_tag=all&name=SecondaryIndexWithDrop&platform=all
