### ISSUE TITLE
TLS specific UI changes in YugaWare

### ISSUE THREAD

**Issue by ramkumarvs** [YugaByte/yugabyte-db#1379]
We have bunch of API's built around enabling TLS for YugaByte in YugaWare platform, we need to make these available in the UI

- Give user to view all the certificates in YugaWare
- Give user the option to pick a existing certificate while universe creation
- Give user option to upload their own root certificate.

discuss with @ivanjovanic and @vitpankin on then design and upload the finalized design in the github issue.

**Comment by ramkumarvs** [comment]
Implementation:

List Certificates:
 In YugaWare we need to have a page to list all the certificates, this would similar to our tasks page.
you would hit /customers/:cUUID/certificates endpoint and render it here.

Create Universe:
You have to give user the list of certificates that they already have in the system via a select box, and either they can pick one from the list or the default option would be `Create new certificate`. if the pick this option create universe call we will set the rootCA to be null, if not we would set the appropriate certificate uuid in the rootCA param.

We only need to show this option to the user if they pick either one of the TLS option.

**Comment by yb-andrew** [comment]
Merged to master 6fb7e5a1e1f86888f37df023d51916e239fa5fca
