### ISSUE TITLE
[ThreadSanitizer Data Race] Observed in CqlTabletSplitTest.SecondaryIndex

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#13793]
Jira Link: [DB-3309](https://yugabyte.atlassian.net/browse/DB-3309)
### Description

Log: https://gist.github.com/kripasreenivasan/fef668975c332a8ca65d5ca43b9f5340 
Suspected commit: aca442b37c068e22f600cf3af1f5e94aef207622 
src/yb/util/threadpool.h:249:12 (CC: @spolitov )

CC: @mbautin

**Comment by Huqicheng** [comment]
Should be duplicate with GH issue #13826 : post-split compaction cause server crash

**Comment by Huqicheng** [comment]
Fixed by reverting https://github.com/yugabyte/yugabyte-db/commit/4f2781bc566ceb17aebbf75c158ee5f5f97fdb92 which introduced the issue.
