### ISSUE TITLE
[yugabyted]  ./bin/yugabyted configure --fault_tolerance=zone [error]

### ISSUE THREAD

**Issue by zuohuadong** [yugabyte/yugabyte-db#13801]
Jira Link: [DB-3316](https://yugabyte.atlassian.net/browse/DB-3316)
### Description

`./bin/yugabyted start --advertise_address=10.1.1.XXX  --base_dir=/home/yugabyte --cloud_location=scc.cn-shaanxi.cn-xian-2a --fault_tolerance=zone
`

Starting yugabyted...
✅ System checks           
✅ YugabyteDB Started                  
⚠ WARNING: Cluster started in an insecure mode without authentication and encryption enabled. For non-production use only, not to be used without firewalls blocking the internet traffic.

+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 3                                                                                  |
| Web console         : http://10.1.1.XXX:7000                                                             |
| JDBC                : jdbc:postgresql://10.1.1.XXX:5433/yugabyte?user=yugabyte&password=yugabyte         |
| YSQL                : bin/ysqlsh -h 10.1.1.XXX  -U yugabyte -d yugabyte                                  |
| YCQL                : bin/ycqlsh 10.1.1.XXX 9042 -u cassandra                                            |
| Data Dir            : /home/yugabyte/data                                                                |
| Log Dir             : /home/yugabyte/logs                                                                |
| Universe UUID       : dba2360b-de54-45f9-afb7-XXXXX                                             |
+----------------------------------------------------------------------------------------------------------+

### THEN:

`./bin/yugabyted configure --fault_tolerance=zone`

yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 2271, in run
    args.func()
  File "./bin/yugabyted", line 572, in configure
    current_masters = self.get_all_masters()
  File "./bin/yugabyted", line 1318, in get_all_masters
    raise RetryableError()
RetryableError

For more information, check the logs in /root/var/logs

### is:

[yugabyted configure] 2022-08-29 13:09:23,542 INFO:  | 0.0s | cmd = configure using config file: /root/var/conf/yugabyted.conf (args.config=None)
[yugabyted configure] 2022-08-29 13:09:23,542 INFO:  | 0.0s | Found directory /root/yugabyte-2.15.1.0/bin for file yb-admin
[yugabyted configure] 2022-08-29 13:09:23,542 INFO:  | 0.0s | run_process: cmd: ['/root/yugabyte-2.15.1.0/bin/yb-admin', '--master_addresses', '127.0.0.1:7100', 'list_all_masters']
[yugabyted configure] 2022-08-29 13:09:33,554 INFO:  | 10.0s | run_process: ['/root/yugabyte-2.15.1.0/bin/yb-admin', '--master_addresses', '127.0.0.1:7100', 'list_all_masters'] timeout expired for command: 
[yugabyted configure] 2022-08-29 13:09:33,554 INFO:  | 10.0s | Got all masters: []
[yugabyted configure] 2022-08-29 13:09:33,556 ERROR:  | 10.0s | Traceback (most recent call last):
  File "./bin/yugabyted", line 2271, in run
    args.func()
  File "./bin/yugabyted", line 572, in configure
    current_masters = self.get_all_masters()
  File "./bin/yugabyted", line 1318, in get_all_masters
    raise RetryableError()
RetryableError

For more information, check the logs in /root/var/logs

[DB-3316]: https://yugabyte.atlassian.net/browse/DB-3316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nchandrappa** [comment]
Hi @zuohuadong, we are looking into the issue, can you also provide the YugabyteDB version and the operating system you were using when you hit this issue?

Also, Wondering if you're trying a multi-node deployment or just testing out the `conifgure` command with single node?

We ran the same  yugabyted commands with YugabyteDB 2.15.1.0 release and MacOS catalina, getting the following output -
 
```
./bin/yugabyted start --advertise_address=127.0.0.1 --cloud_location=scc.cn-shaanxi.cn-xian-2a --fault_tolerance=zone
./bin/yugabyted configure --fault_tolerance=zone
FAILED: Invalid number of placement constraint specified.
For more information, check the logs in /Users/nikhil/var/logs
```
As you can see it gives a valid output since only one node is the cluster.

**Comment by zuohuadong** [comment]
@nchandrappa 

>  AlmaLinux 8 / Almalinux 9  
> python 3.6 / python 3.9

node1: 
`./bin/yugabyted start --advertise_address=10.1.1.xxx  --base_dir=/home/yugabyte --cloud_location=scc.cn-shaanxi.cn-xian-2a --fault_tolerance=zone`

node2:
`./bin/yugabyted start --advertise_address=10.1.1.xx2 --join=10.1.1.xxx  --base_dir=/home/yugabyte --cloud_location=scc.cn-shaanxi.cn-xian-2b --fault_tolerance=zone`

node3:
`./bin/yugabyted start --advertise_address=10.1.1.xx3 --join=10.1.1.xxx  --base_dir=/home/yugabyte --cloud_location=scc.cn-shaanxi.cn-xian-2c --fault_tolerance=zone`


THEN:
`./bin/yugabyted configure --fault_tolerance=zone`

......

**Comment by gargsans-yb** [comment]
Hi @zuohuadong, as I can see that while starting the nodes in their respective VMs, `--base_dir` flag was also used. 
This caused all the data, configs and logs to be stored at the given location. 
Then while running `./bin/yugabyted configure` command, the `--base_dir` wasn't provided, so it tried to check the default directory, which is `~/var`. 
You should run the configure command along with the `--base_dir`.
Try:
```
./bin/yugabyted configure --base_dir=/home/yugabyte --fault_tolerance=zone
```

**Comment by nchandrappa** [comment]
When configuring a RF-5 cluster, configure command fails with the following error message - `FAILED: Invalid number of placement constraint specified.`
