### ISSUE TITLE
Segmentation fault on macOS in the org.yb.pgsql.TestPgDepend#testTableWithSequenceDeletion test

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1382]
ybd --java-test org.yb.pgsql.TestPgDepend#testTableWithSequenceDeletion

Segmentation fault:
https://gist.githubusercontent.com/mbautin/f273458a43325efd303008ee8d96b437/

**Comment by rthallamko3** [comment]
[Detective report](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TestPgDepend&fail_tag=all&name=testTableWithSequenceDeletion&platform=linux) looks good. Closing the ticket.
