### ISSUE TITLE
Long (22 seconds) CreateNamespace call in initdb in PgWrapperTest.TestStartStop

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1384]
https://gist.githubusercontent.com/mbautin/5f2d09c73e6469d74bc4126e7cf9529e/raw#

Full test log: https://gist.githubusercontent.com/mbautin/4c715e9cdfe9389225c8b9e37a0e4b6c/raw

**Comment by bmatican** [comment]
creating a YSQL database is just inherently slow, due to copying lots of data
we have however done a bunch of work to speed it up + have a master task tracking future work for speeding it up, so closing this
