### ISSUE TITLE
[Docs] Data manipulation

### ISSUE THREAD

**Issue by vrbilgi** [yugabyte/yugabyte-db#13841]
### Description

**Back up a database:**
I am executing below two commands in docker instance of yugabyte# 
ysql_dump mydb > mydb.sql
\i mydb

```
\i mydb
mydb: No such file or directory'
\i mydb.sql
mydb: No such file or directory
```

**Question:**
where exactly mydb.sql is stores ?
When loading should we mention mydb.sql or mydb

**Note:I** am using docker yugabyte cluster in local mac machine

**Comment by ddorian** [comment]
> where exactly mydb.sql is stores ?

Do you see the file if you do `ls` after the command runs?

**Comment by ddorian** [comment]
Closing because user is unresponsive.
