### ISSUE TITLE
[DocDB] flaky test: CppCassandraDriverTest.ManyTables

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13849]
Jira Link: [DB-3348](https://yugabyte.atlassian.net/browse/DB-3348)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=CppCassandraDriverTest&fail_tag=all&name=ManyTables&platform=linux

**Comment by rthallamko3** [comment]
seems like it fails quite frequently
`

09/17/2022 01:48 | alma8-master-gcc11-fastdebug/771/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/771/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log  ../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032 Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.002s vs 0.001s
-- | -- | -- | --
09/17/2022 01:48 | alma8-master-clang12-debug-aarch64/842/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-debug-aarch64/842/artifact/build/debug-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log  ../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032 Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.006s vs 0.003s
09/16/2022 19:03 | centos-master-clang13-debug/319/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang13-debug/319/artifact/build/debug-clang13-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log  ../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032 Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.006s vs 0.004s
09/16/2022 19:03 | alma8-master-clang12-release-aarch64/900/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-release-aarch64/900/artifact/build/release-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log  ../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032 Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.001s vs 0.001s

09/17/2022 01:48	[alma8-master-gcc11-fastdebug/771/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/771/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/771/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log

../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032
Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.002s vs 0.001s
09/17/2022 01:48	[alma8-master-clang12-debug-aarch64/842/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-debug-aarch64/842/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-debug-aarch64/842/artifact/build/debug-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log

../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032
Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.006s vs 0.003s
09/16/2022 19:03	[centos-master-clang13-debug/319/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang13-debug/319/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang13-debug/319/artifact/build/debug-clang13-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log

../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032
Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.006s vs 0.004s
09/16/2022 19:03	[alma8-master-clang12-release-aarch64/900/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-release-aarch64/900/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-release-aarch64/900/artifact/build/release-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ManyTables.log

../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:3032
Expected: (read_times.front() * 2) <= (read_times.back()), actual: 0.001s vs 0.001s`

**Comment by rthallamko3** [comment]
cc @lingamsandeep , this is the system table cache issue. Can you see if this performance test is still relevant?

**Comment by bmatican** [comment]
Not showing up in top 20% anymore
