### ISSUE TITLE
[DocDB] Terminate webserver's last line with newline

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13844]
Jira Link: [DB-3343](https://yugabyte.atlassian.net/browse/DB-3343)
### Description

To confirm to the standard definition of a line on POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

Makes it more convenient to use with POSIX tools, for example `curl`ing the page will not mess up the next terminal prompt.

**Comment by rthallamko3** [comment]
@def- , Do you plan to backport it to stable branches? If not, can we close this issue now?

**Comment by def-** [comment]
Wasn't planning to backport, thus closing.
