### ISSUE TITLE
[DocDB] flaky test: QLTabletTest.DoubleFlush

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13854]
Jira Link: [DB-3354](https://yugabyte.atlassian.net/browse/DB-3354)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=QLTabletTest&fail_tag=all&name=DoubleFlush&platform=linux

**Comment by rthallamko3** [comment]
@es1024 , looks like the failures are only happening on alma8 builds
<img width="1723" alt="Screen Shot 2022-09-06 at 2 19 56 PM" src="https://user-images.githubusercontent.com/17170123/188740390-2257a629-9a76-4be1-9242-d2ce52ee4598.png">
