### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgRegressTablegroup.testPgRegressTablegroup

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#13888]
Jira Link: [DB-3387](https://yugabyte.atlassian.net/browse/DB-3387)
### Description
[org.yb.pgsql.TestPgRegressTablegroup.testPgRegressTablegroup](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressTablegroup&fail_tag=all&name=testPgRegressTablegroup&platform=all)

Looks like most common failure is `yb_tablegroup_colocation_id` but `yb_tablegroup` seems to also fail occasionally.

**Comment by bmatican** [comment]
Putting this back on Fizaa, as it's likely an LRT issue.
