### ISSUE TITLE
[flaky test] Several org.yb.loadtester.* test suites

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#13889]
Jira Link: [DB-3388](https://yugabyte.atlassian.net/browse/DB-3388)
### Description

[org.yb.loadtester.TestClusterWithHighLoadAndSlowSync.testClusterFullMoveWithHighLoadAndSlowSync](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestClusterWithHighLoadAndSlowSync&fail_tag=all&name=testClusterFullMoveWithHighLoadAndSlowSync&platform=all)

[org.yb.loadtester.TestFullMoveWithHeartBeatDelay.testClusterFullMoveWithHeartbeatDelay](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestFullMoveWithHeartBeatDelay&fail_tag=all&name=testClusterFullMoveWithHeartbeatDelay&platform=all)

[org.yb.loadtester.TestMasterLeaderDecommission.testMasterLeaderDecommission](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestMasterLeaderDecommission&fail_tag=all&name=testMasterLeaderDecommission&platform=all)

[org.yb.loadtester.TestClusterFullMove.testClusterFullMove](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestClusterFullMove&fail_tag=all&name=testClusterFullMove&platform=all)

[org.yb.loadtester.TestRF1Cluster.testDefaultTTLWithChangedRF](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestRF1Cluster&fail_tag=all&name=testDefaultTTLWithChangedRF&platform=all)

[org.yb.loadtester.TestRF1Cluster.testRF1toRF3](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestRF1Cluster&fail_tag=all&name=testRF1toRF3&platform=all)

Looks like they all significantly increased the failure rate recently -- regression was introduced in this range for all of them: https://github.com/yugabyte/yugabyte-db/compare/34ca65fd605a95173ed7ffabdf2ee14e86757585~...c1d676580933d34bd34fcbb7e86099dcd9e0eb99

From the detective diff results looks like this diff might be the cause: https://github.com/yugabyte/yugabyte-db/commit/9c8e831302822a18170ed5f7c5a4350fb4472f32

**Comment by bmatican** [comment]
This one seems to have been failing indeed for some time

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.loadtester.TestClusterWithHighLoadAndSlowSync&fail_tag=all&name=testClusterFullMoveWithHighLoadAndSlowSync&platform=linux

**Comment by tedyu** [comment]
With this change
```
diff --git a/src/yb/docdb/deadlock_detector.cc b/src/yb/docdb/deadlock_detector.cc
index 06a0864f05..9482833a55 100644
--- a/src/yb/docdb/deadlock_detector.cc
+++ b/src/yb/docdb/deadlock_detector.cc
@@ -72,6 +72,7 @@ class ProbeTracker {
   void UpdateMinProbeNo(uint32_t min_probe_num) EXCLUDES(mutex_) {
     UniqueLock<decltype(mutex_)> l(mutex_);
     DCHECK(IsFirstProbeNumValid());
+    if (min_probe_num <= min_probe_num_) return;

     auto it = probes_.begin();
     while (it != probes_.end() && it->first < min_probe_num) {
```
It seems the tests are more stable.

**Comment by bmatican** [comment]
Not showing up in top 20% failure rate anymore
