### ISSUE TITLE
[flaky test] TestPgSelect.testInequalitiesRangePartitioned

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#13899]
Jira Link: [DB-3397](https://yugabyte.atlassian.net/browse/DB-3397)
### Description

[org.yb.pgsql.TestPgSelect.testInequalitiesRangePartitioned](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgSelect&fail_tag=all&name=testInequalitiesRangePartitioned&platform=all)

Looks like it failed fairly regularly since it has been added.
Errors are assertion errors so looks like a legitimate code or test issue:
```
java.lang.AssertionError: expected:<66> but was:<1>
```

**Comment by ramsrivatsa** [comment]
Fixed flaky test with this commit --> https://github.com/yugabyte/yugabyte-db/commit/c1b214b0314ae2fa802f62f1ba3ed77c7ba32234.
