### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgTransactions.testTableWithoutPrimaryKey

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#13892]
Jira Link: [DB-3391](https://yugabyte.atlassian.net/browse/DB-3391)
### Description

[org.yb.pgsql.TestPgTransactions.testTableWithoutPrimaryKey](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgTransactions&fail_tag=all&name=testTableWithoutPrimaryKey&platform=all) 

Looks like it's been failing for a while.

The error is a failing assert (probably assertEquals):
```
java.lang.AssertionError: expected:<33686116> but was:<33686023>
```
(But both the numbers vary across runs).

**Comment by lnguyen-yugabyte** [comment]
The error appears when a thread is has updated v to the new value, but subsequently still reads an old value.
