### ISSUE TITLE
[DocDB] flaky test: AutoFlagsExternalMiniClusterTest.UpgradeCluster

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13897]
Jira Link: [DB-3395](https://yugabyte.atlassian.net/browse/DB-3395)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=AutoFlagsExternalMiniClusterTest&fail_tag=all&name=UpgradeCluster&platform=all

likely traces back to https://github.com/yugabyte/yugabyte-db/commit/bee83b9ba3f272462f02d7cc237597db9fe338f3

**Comment by bmatican** [comment]
Lowering pri, this might be due to some recent infra issues.

**Comment by karan-yb** [comment]
Fixed as part of [13911](https://github.com/yugabyte/yugabyte-db/issues/13911) fix.
