### ISSUE TITLE
[DocDB] [Packed Columns] System catalog snapshot is corrupted, or is built using different build type: 0 vs 10

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#13909]
Jira Link: [DB-3406](https://yugabyte.atlassian.net/browse/DB-3406)
### Description

On @Arpit-yb 's LRU [puppy-food-4s-3](https://portal.dev.yugabyte.com/universes/0fbf3ea9-af88-4d00-b486-e4a937915932) with 2.15.3.0-b77 version. 

Here is what has happened:

1. Glags has been set on Friday, basically 'ycql_enable_packed_row' has been enabled

![Screenshot 2022-09-07 at 2 30 31 PM](https://user-images.githubusercontent.com/109518123/188840959-4c9a0c7f-f769-400e-bb24-76d0734d45f9.png)

2. Left the workloads to run over the weekend

3. On Monday there were failures

`F0905 06:19:29.113543 21595 hybrid_clock.cc:177] Too big clock skew is detected: 12231.994s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000
F0905 06:19:29.116254 21406 hybrid_clock.cc:177] Too big clock skew is detected: F0912231.992s, while max allowed is: 5 06:19000000
k:29.116258 21407 hybrid_clock.cc:177] Too big clock skew is detected: 12231.992s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000F0905 06:19:29.120676 21405 hybrid_clock.cc:177] Too big clock skew is detected: F12231.987s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000905 06:19:29.120679 21408 hybrid_clock.cc:177] Too big clock skew is detected: 12231.987s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000`

`F20220904 11:13:19 ../../src/yb/server/hybrid_clock.cc:177] Too big clock skew is detected: 6489.815s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000
    @          0x2a74fc8  google::LogMessage::SendToLog()
    @          0x2a75e73  google::LogMessage::Flush()
    @          0x2a763ff  google::LogMessageFatal::~LogMessageFatal()
    @          0x356e0f8  yb::server::HybridClock::NowWithError()
    @          0x356c6e1  yb::server::HybridClock::NowRange()
    @          0x366c5d9  yb::tablet::TransactionCoordinator::Impl::Poll()
    @          0x3494db1  yb::rpc::Poller::Poll()
    @          0x34bf3cf  _ZN5boost4asio6detail18completion_handlerIZN2yb3rpc9Scheduler4Impl11HandleTimerERKNS_6system10error_codeEEUlvE_NS0_10io_context19basic_executor_typeINSt3__19allocatorIvEELm0EEEE11do_completeEPvPNS1_19scheduler_operationESA_m
    @          0x2a47355  boost::asio::detail::scheduler::run()
    @          0x34842b5  yb::rpc::IoThreadPool::Impl::Execute()
    @          0x3b3d9a1  yb::Thread::SuperviseThread()
    @     0x7eff7fb92694  start_thread
    @     0x7eff8009441d  __clone`

**Note: Introspecting: on one node which is in stopping status, system time is different than other 2, also same node has NTP synchronized: no**

4. Then tried to restart on Tuesday:

Observation: Crashes are seen with FATAL logs.

```
F20220906 10:15:55 ../../src/yb/master/master_main.cc:132] Corruption (yb/master/sys_catalog_writer.cc:207): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: System catalog snapshot is corrupted, or is built using different build type: 0 vs 10
    @     0x7f50780aec1b  google::LogMessage::SendToLog()
    @     0x7f50780afcd8  google::LogMessage::Flush()
    @     0x7f50780b015f  google::LogMessageFatal::~LogMessageFatal()
    @           0x20585b  main
    @     0x7f5075d3a825  __libc_start_main
    @           0x204b59  _start


```
![Screenshot 2022-09-07 at 2 56 00 PM](https://user-images.githubusercontent.com/109518123/188843292-ecabc08b-e9d8-477c-9db4-0862db1d0fcc.png)

![Screenshot 2022-09-07 at 2 57 14 PM](https://user-images.githubusercontent.com/109518123/188843484-2f5ad2ca-e63a-44ed-88d8-8a489b23b47a.png)

@Arpit-yb please add if anything is missing here.

**Comment by kripasreenivasan** [comment]
@shamanthchandra-yb , Please check if we still run into this issue with https://phabricator.dev.yugabyte.com/D19684 ?

**Comment by shamanthchandra-yb** [comment]
@kripasreenivasan I am not seeing FATAL message like in this ticket in my case.
There are some differences though, I have only enabled packed columns flag on tserver for both ysql and ycql. Where as I see @Arpit-yb had enabled on master as well.

But, in my case nodes went into unreachable state. I restarted all EC2 instances now, they are all LIVE again.

Though I got this message in ERROR: 
E1013 06:58:13.007556  1484 hybrid_clock.cc:181] Too big clock skew is detected: 0.532s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000`

I read it will eventually be sync'd and observed this ERROR is not printing now.

But, after restart in one of the node, observed a tserver crash:
`F20221013 07:11:03 ../../src/yb/util/malloc.cc:53] Check failed: data != nullptr failed to allocate ^@^@^@^@^@^@^@^@^@^@^@failed to allocate ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@19288451964110 bytes
^@^@^@^@^@
    @          0x2a88df8  google::LogMessage::SendToLog()
    @          0x2a89cb3  google::LogMessage::Flush()
    @          0x2a8a1af  google::LogMessageFatal::~LogMessageFatal()
    @          0x3af51de  yb::malloc_with_check()
    @          0x348042b  yb::rpc::OutboundCall::SetRequestParam()
    @          0x3485bfc  yb::rpc::Proxy::PrepareCall()
    @          0x3485414  yb::rpc::Proxy::DoAsyncRequest()
    @          0x348459c  yb::rpc::Proxy::AsyncRequest()
    @          0x38c70d1  yb::tserver::TabletServerServiceProxy::WriteAsync()
    @          0x2c44448  yb::client::internal::WriteRpc::CallRemoteMethod()
    @          0x2cec445  yb::client::internal::TabletInvoker::Execute()
    @          0x2c401a3  yb::client::internal::AsyncRpc::SendRpc()
    @          0x349be21  yb::rpc::RpcRetrier::DoRetry()
    @          0x349662b  ev::base<>::method_thunk<>()
    @          0x345804c  ev_invoke_pending
    @          0x345b31d  ev_run
    @          0x3491c5a  yb::rpc::Reactor::RunThread()
    @          0x3b4c972  yb::Thread::SuperviseThread()
    @     0x7f68be9f2694  start_thread
    @     0x7f68beef441d  __clone

which looks like https://github.com/yugabyte/yugabyte-db/issues/14461

**Comment by bmatican** [comment]
@shamanthchandra-yb as in the other GH issue, this error you're getting is a running out of memory issue. Please reduce your workload to use fewer threads, so we don't overload the server.

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , @kripasreenivasan , Can you confirm if this happens with ycql only, if so can you update the title with the same?

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , @kripasreenivasan , Can you confirm if this happens with ycql only, if so can you update the title with the same?

**Comment by kripasreenivasan** [comment]
Unable to hit this issue with the initial set of tests performed. Will allow the fix to soak in in the long running universes over more rolling restarts, upgrades while workloads are executing for another week before closing the issue.
CC: @rthallamko3
