### ISSUE TITLE
[Docs] Write IO path

### ISSUE THREAD

**Issue by balasubram** [yugabyte/yugabyte-db#13901]
### Description

This link https://docs.yugabyte.com/stable/architecture/concepts/sharding/ is missing in the document https://docs.yugabyte.com/stable/architecture/core-functions/write-path/. It seems the link https://docs.yugabyte.com/stable/architecture/concepts/sharding/ is not found and it returns 404. Even the link https://docs.yugabyte.com/stable/develop/client-drivers/java/ is missing

**Comment by ddorian** [comment]
Both links are already fixed in the latest version.
