### ISSUE TITLE
[yugabyted] Encryption-at-rest experience through yugabyted

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#13910]
## Enable encryption at rest in a multi-node cluster

1. Start a multi-node using yugabyted. Reference: https://docs.yugabyte.com/preview/reference/configuration/yugabyted/#create-a-multi-zone-cluster
2. Enable encryption at rest
```
./yugabyted configure encrypt-at-rest --enable --master=<master_ips>
```
***<master_ips>*** is comma seperated all current master IPs with port

Example:
```
./yugabyted configure encrypt-at-rest --enable –masters=10.150.0.157:7100,10.150.1.100:7100,10.150.3.223:7100
```

## Disable encryption at rest:

1. Disable encryption at rest using yugabyted
```
./yugabyted configure encrypt-at-rest --disable --masters=<master_ips>
```

**Comment by gargsans-yb** [comment]
Do not introduce `--master` flag. Toggle encryption-at-rest without requiring masters from the user.
To enable encryption at rest, Use:
```
./yugabyted configure encrypt-at-rest --enable
```

**Comment by gargsans-yb** [comment]
Change the sub-command from `encrypt-at-rest` to `encrypt_at_rest`.
To enable encryption at rest, Use:
```
./yugabyted configure encrypt_at_rest --enable
```

**Comment by nchandrappa** [comment]
Code changes landed.
