### ISSUE TITLE
[DocDB] UndefinedBehavior in TwoDCTestParams/TwoDCYsqlTest.DeleteTableChecks and TwoDCTestParams/TwoDCTest.DeleteTableChecksCQL

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13929]
Jira Link: [DB-3426](https://yugabyte.atlassian.net/browse/DB-3426)
### Description

It seems we end up with a null tablet peer, while calling GetChanges, so there's probably some shutdown or cleanup logic, that's not thread safe.

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-asan/1258/artifact/build/asan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__twodc-test/TwoDCTestParams__TwoDCTest_DeleteTableChecksCQL__3.log

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-asan/1255/artifact/build/asan-clang12-dynamic-ninja/yb-test-logs/tests-integration-tests__twodc_ysql-test/TwoDCTestParams__TwoDCYsqlTest_DeleteTableChecks__1.log

```
../../ent/src/yb/cdc/cdc_service.cc:658:16: runtime error: member call on null pointer of type 'yb::tablet::TabletPeer'
    #0 0x7f825c51e3e6 in yb::cdc::(anonymous namespace)::IsTabletPeerLeader(std::__1::shared_ptr<yb::tablet::TabletPeer> const&) ${BUILD_ROOT}/../../ent/src/yb/cdc/cdc_service.cc:658:16
    #1 0x7f825c522447 in yb::cdc::CDCServiceImpl::GetChanges(yb::cdc::GetChangesRequestPB const*, yb::cdc::GetChangesResponsePB*, yb::rpc::RpcContext) ${BUILD_ROOT}/../../ent/src/yb/cdc/cdc_service.cc:1272:31
...
```

**Comment by lingamsandeep** [comment]
This seems to be a regression from the commit :  https://github.com/yugabyte/yugabyte-db/commit/d4df77709fc39c3cf2fca4d907c6a094898ff2df

With this commit out of 25 runs of the test we consistently see ~10 failures. Without it, we see 0.
