### ISSUE TITLE
[DocDB] Segfault when setting rpc_dump_all_traces=1 if tracing is not enabled

### ISSUE THREAD

**Issue by jteplitz** [yugabyte/yugabyte-db#13938]
Jira Link: [DB-3435](https://yugabyte.atlassian.net/browse/DB-3435)
### Description

**Overview**

If you set rpc_dump_all_traces=1 without setting enable_tracing=1, the tablet server will segfault here:
*** Aborted at 1662672392 (unix time) try "date -d @1662672392" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x10) received by PID 7 (TID 0x7f466f200700) from PID 16; stack trace: ***
    @          0x3aff9d1 yb::Trace::Dump()
    @          0x345f203 yb::rpc::OutboundCall::~OutboundCall()
    @          0x345d616 yb::rpc::InvokeCallbackTask::Done()
    @          0x351ed6d yb::rpc::(anonymous namespace)::Worker::Execute()
    @          0x3af3ec1 yb::Thread::SuperviseThread()
    @     0x7f4a58f64694 start_thread
    @     0x7f4a5946641d __clone

**Steps to reproduce**
Make sure the enable_tracing glfag is **not** set. Run with your tablet servers IP and port:
yb-ts-cli --server_address=$ip:$port set_flag rpc_dump_all_traces 1

** Result **
Segfault. This is 100% reproducible.

** Notes **
I think the issue is [here](https://github.com/yugabyte/yugabyte-db/blob/11f564f91a71d2c28fc0bfae7eef0a1c2c286c57/src/yb/rpc/outbound_call.cc#L185). OutboundCall is calling a trace method on a NULL pointer. In addition to skipping the call when the pointer is NULL, it'd be nice to get a warning in the logs that rpc_dump_all_traces is being ignored because tracing is not enabled.

**Comment by tedyu** [comment]
Another option is to treat enable_tracing as true when rpc_dump_all_traces is set:
```
diff --git a/src/yb/util/trace.cc b/src/yb/util/trace.cc
index e22c9dafd5..0a8fc747eb 100644
--- a/src/yb/util/trace.cc
+++ b/src/yb/util/trace.cc
@@ -193,7 +193,8 @@ int64_t GetCurrentMicrosFast(CoarseTimePoint now) {
 } // namespace

 ScopedAdoptTrace::ScopedAdoptTrace(Trace* t)
-    : old_trace_(Trace::threadlocal_trace_), is_enabled_(GetAtomicFlag(&FLAGS_enable_tracing)) {
+    : old_trace_(Trace::threadlocal_trace_),
+      is_enabled_(GetAtomicFlag(&FLAGS_enable_tracing)||GetAtomicFlag(&FLAGS_rpc_dump_all_traces)) {
   if (is_enabled_) {
     trace_ = t;
     Trace::threadlocal_trace_ = t;
@@ -280,7 +281,7 @@ ThreadSafeArena* Trace::GetAndInitArena() {
 }

 scoped_refptr<Trace> Trace::NewTrace() {
-  if (GetAtomicFlag(&FLAGS_enable_tracing)) {
+  if (GetAtomicFlag(&FLAGS_enable_tracing) || GetAtomicFlag(&FLAGS_rpc_dump_all_traces)) {
     return scoped_refptr<Trace>(new Trace());
   }
   const int32_t sampling_freq = GetAtomicFlag(&FLAGS_sampled_trace_1_in_n);
```
