### ISSUE TITLE
[YSQL] Add support for `ALTER TABLE .. ADD CONSTRAINT .. UNIQUE`

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1394]
We already support unique indexes and UNIQUE clause in CREATE TABLE statement. We should also support it in ALTER TABLE.

**Comment by dodilp** [comment]
Can you please confirm which build this will be in?

Will it work for statements like the below -
ALTER TABLE ONLY addresses
	    ADD CONSTRAINT addresses_id_key UNIQUE (id)

**Comment by rkarthik007** [comment]
@m-iancu - could you please answer @dodilp's question?

**Comment by kmuthukk** [comment]
@dodilp - 1.2.11 release has this fix. [CC: @m-iancu ].

**Comment by dodilp** [comment]
Thank you, @kmuthukk. Will try out this new build

**Comment by srhickma** [comment]
@dodilp I checked and can confirm that the statement you wrote should work in 1.2.11.
