### ISSUE TITLE
[Docs] Mailto link for security team is incorrect on the vulnerability disclosure page

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#13958]
### Description

The mailto link for security@yugabyte.com has a typo on the Vulnerability disclosure policy page:
https://docs.yugabyte.com/preview/secure/vulnerability-disclosure-policy/#the-process

Instead of security@yugabyte.com, the link points to securit@yugabyte.com.

**Comment by polarweasel** [comment]
Fixed in commit ccfb2b55b1423833131c862c622f7da0ed6671c3
