### ISSUE TITLE
[YSQL] Processed tuples are not reported correctly when copy terminates due to error

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#13978]
Jira Link: [DB-3462](https://yugabyte.atlassian.net/browse/DB-3462)
### Description

copy command is broken into multiple smaller transaction as indicated by ROWS_PER_TRANSACTION.  Each transaction copies the  `rows == ROWS_PER_TRANSACTION`. 

The number of processed tuple count is increased before the transaction can commit. 

https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/commands/copy.c#L3146

If the copy command gets aborted due to error in middle to transaction then the  processed tuple can be wrong reported in return value of the copy command.

**Comment by lnguyen-yugabyte** [comment]
On error, we are not reporting the number of copied rows (although rows are still persisted correctly). Closed as no-op.

```
yugabyte=# copy t from stdin with (rows_per_transaction 2, format csv);
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 1,1
>> 3,3
>> 5,5
>> 7,7
>> 9,9
>> ^CERROR:  COPY from stdin failed: canceled by user
CONTEXT:  COPY t, line 6
yugabyte=#
```
