### ISSUE TITLE
[DocDB] flaky test: QLTabletTest.WaitFlush flaky in TSAN only

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13976]
Jira Link: [DB-3460](https://yugabyte.atlassian.net/browse/DB-3460)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=QLTabletTest&fail_tag=all&name=WaitFlush&platform=linux

Perhaps missing some time multiplier?

**Comment by Huqicheng** [comment]
Noticed warning message: `Skipping flush on memtable with ops ahead of log. Memtable index: 233 - log index: 211`

In which cases the log index can be less than the memtable op index?

**Comment by Huqicheng** [comment]
For the issue,
```cpp
  while (std::chrono::steady_clock::now() <= deadline) {
    for (const auto& peer : peers) {
      auto flushed_op_id = ASSERT_RESULT(peer->tablet()->MaxPersistentOpId()).regular;
      auto latest_entry_op_id = peer->log()->GetLatestEntryOpId();
      ASSERT_LE(flushed_op_id.index, latest_entry_op_id.index);
    }
  }
```
Checking in this while loop is too frequent, seems to block the write thread. We need some Sleep here.
