### ISSUE TITLE
[YSQL] Ghost column

### ISSUE THREAD

**Issue by williamoliveira** [yugabyte/yugabyte-db#13993]
Jira Link: [DB-3492](https://yugabyte.atlassian.net/browse/DB-3492)
### Description

I created a column that I cant select or drop: 

`ALTER TABLE users ADD COLUMN "phoneNumber" varchar(255);`
[XX000] ERROR: Already present: The column already exists: phoneNumber

`SELECT "phoneNumber" FROM users;`
[42703] ERROR: column "phoneNumber" does not exist Position: 8

`ALTER TABLE users DROP COLUMN "phoneNumber";`
[42703] ERROR: column "phoneNumber" of relation "users" does not exist

**Comment by tedyu** [comment]
```
yugabyte=# ALTER TABLE t ADD COLUMN "phoneNumber" varchar(255);
ALTER TABLE
yugabyte=# \d t;
                           Table "public.t"
   Column    |          Type          | Collation | Nullable | Default
-------------+------------------------+-----------+----------+---------
 i           | integer                |           |          |
 j           | text                   |           |          |
 phoneNumber | character varying(255) |           |          |
```
Can you give DDL statements w.r.t. `users` table ?

**Comment by williamoliveira** [comment]
Unfortunately as I was playing around with the cluster trying to solve it I accidentally corrupted the installation and had to reset everything. If I find this problem again I will post here.

The extra information I have right now  is that the column appeared on YugabyteDB dashboard at http://127.0.0.1:7000/tables but did not appear on column listing inside my database management tool (Datagrip). Also restarting the tservers or master did not help.

**Comment by ddorian** [comment]
@williamoliveira please re-open if you hit it again.
