### ISSUE TITLE
Timezone issue with java.util.Date and cassandra driver

### ISSUE THREAD

**Issue by nickhristov** [YugaByte/yugabyte-db#14]
Hello.

I am seeing an unpleasant problem which have also now seen in mongo as well :) It is possible that I am wrong, but please bear with me.

In java the `java.util.Date` class represents an instant in time. It has no notion of a timezone, it is effectively a wrapper of the timestamp since the beginning of the Epoch. So, for example: a timestamp with the format of `2018-01-08T00:15:13Z` appears in java like this (in the debugger):

![screen shot 2018-01-11 at 11 57 57 am](https://user-images.githubusercontent.com/42384/34844588-d7c147c8-f6c6-11e7-84a7-3425beab062f.png)

The greatest sin of the `java.util.Date` is that its `toString()` implementation prints the LOCAL timezone instead of UTC. However, if one were to take the date object, issue a `getTime()`, they get the timestamp in milliseconds, which quickly produces the correct result when converted to human readable format:

![screen shot 2018-01-11 at 11 32 14 am](https://user-images.githubusercontent.com/42384/34844671-1eacfd94-f6c7-11e7-8708-abca7a38cb24.png)

Unfortunately, when this is sent for writing to yugabyte, yugabyte records wrong time. You will see that the results are stored like this:

![screen shot 2018-01-11 at 12 04 04 pm](https://user-images.githubusercontent.com/42384/34844822-952ca762-f6c7-11e7-8c0c-5be0858389f9.png)

You can see that the time has now shifted with 8 hours and the timezone stored is UTC, i.e. the driver or yugabyte interpreted my date as if the date is set in PST (eight hours behind UTC, and added 8 hours to make it UTC).

**Comment by nickhristov** [comment]
So, looks like `java.util.Date` is serialized via a TimestampCodec.

![screen shot 2018-01-11 at 12 14 34 pm](https://user-images.githubusercontent.com/42384/34845244-120c55ec-f6c9-11e7-8b2f-fb833fcf72d7.png)

Which then internally gets converted in a long value and sent over like that over the wire.

![screen shot 2018-01-11 at 12 14 59 pm](https://user-images.githubusercontent.com/42384/34845260-2363f322-f6c9-11e7-825b-3030ca028b62.png)

So, I am starting to wonder if this is a driver problem, as it does not seem to do anything irrational.

**Comment by nickhristov** [comment]
Hmmm, apparently cassandra does exactly the same thing. I am still rather confused.

**Comment by m-iancu** [comment]
Hi @nickhristov, this is indeed the Cassandra behavior. When the timezone is not explicitly given, the local timezone of the node handling the request is used. For compatibility reasons, we replicate this behavior in YugaByte DB.
You can give the timezone explicitly in the date string to avoid defaulting to the local one: e.g. `2018-01-08T00:15:13 UTC`.

**Comment by nickhristov** [comment]
"When the timezone is not explicitly given, the local timezone of the node handling the request is used."

But the whole point is that there is no timezone in a timestamp? Why would a timezone be relevant to the request. It's just an absolute offset from the epoch.

Quoting the cassandra documentation:

> Values of the timestamp type are encoded as 64-bit signed integers representing a number of milliseconds since the standard base time known as “the epoch”: January 1 1970 at 00:00:00 GMT.
> Timestamp can be input in CQL as simple long integers, giving the number of milliseconds since the epoch, as defined above.

There is no timezone at all. The only timezone which would be relevant when querying happens, i.e. one could return the data with an offset of the timezone in which the client is set, but obviously then the time must be shifted as well.

The behavior that I am seeing across the board, and which is baffling to me is that I give a timestamp, and my current timezone offset is added to it.

Regardless, I don't think there is anything that can be done here, since this is basically cassandra behavior as well.

**Comment by m-iancu** [comment]
Hi @nickhristov, in the internally stored timestamp value there is indeed no timezone. It is, as you mentioned, just a 64-bit signed integer value. 

But, when the timestamp literal is given as a date string (not an integer) it needs to be interpreted into an actual date-time value and converted into milliseconds from the epoch (GMT).
This conversion step is where the timezone comes in, and it effectively functions as an offset when interpreting the date string to generate the actual integer value that is stored internally.

When you query it (e.g. with `cqlsh`) you will get the epoch value formatted in GMT time, since the original user-specified or node-inferred timezone is not stored in the timestamp value. So if a non-GMT timezone was used to interpret the date string, this can be confusing.
That's why we recommend explicitly passing the timezone for date strings.
