### ISSUE TITLE
[DocDB] Upgrade failure due to lack of disk space

### ISSUE THREAD

**Issue by Arpit-yb** [yugabyte/yugabyte-db#14002]
Jira Link: [DB-3502](https://yugabyte.atlassian.net/browse/DB-3502)
### Description

**Steps to repro**

- Create a cluster
- Run some workloads to fill the disk completely
- Trigger software upgrade

We recently upgraded a universe on the system-test platform from 2.12.6 -> 2.14.1. The initial upgrade failed due to lack of memory. After increasing the disk size, we retried the process but that too failed with error - 
`java.lang.RuntimeException: Follower lag timeout reached: ip=10.152.0.22, port=9000, followerLagMs=1077667.000000`

Master logs - 
`Log file created at: 2022/09/13 08:47:37
Running on machine: yb-dev-system-test-target-gcp-n1
Application fingerprint: version 2.14.1.0 build 36 revision aa9d62a52c7e83c77ca90e35c0652b1842bc3398 build_type RELEASE built at 08 Aug 2022 08:45:12 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0913 08:47:37.902777  3734 async_initializer.cc:95] Failed to initialize client: Illegal state (yb/client/client-internal.cc:2314): Could not locate the leader master: Unable to determine master addresses
E0913 08:47:37.917387  3740 async_initializer.cc:95] Failed to initialize client: Illegal state (yb/client/client-internal.cc:2314): Could not locate the leader master: Unable to determine master addresses`

master.err file - 
`*** Aborted at 1663049709 (unix time) try "date -d @1663049709" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x412000046bc) received by PID 15670 (TID 0x7fb7270781c0) from PID 18108; stack trace: ***
    @     0x7fb729cc846d __GI___nanosleep
    @     0x7fb72a4b00ca  std::__1::this_thread::sleep_for()
    @     0x7fb72d72959e  yb::server::TotalMemWatcher::MemoryMonitoringLoop()
    @           0x205964 main
    @     0x7fb729337825 __libc_start_main
    @           0x204e99 _start
*** Aborted at 1663058706 (unix time) try "date -d @1663058706" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x4120000089e) received by PID 18184 (TID 0x7f8d485931c0) from PID 2206; stack trace: ***
    @     0x7f8d4b1e346d __GI___nanosleep
    @     0x7f8d4b9cb0ca  std::__1::this_thread::sleep_for()
    @     0x7f8d4ec4459e  yb::server::TotalMemWatcher::MemoryMonitoringLoop()
    @           0x205964 main
    @     0x7f8d4a852825 __libc_start_main
    @           0x204e99 _start
*** Aborted at 1663135678 (unix time) try "date -d @1663135678" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x41200003a25) received by PID 3721 (TID 0x7f9ec17aa1c0) from PID 14885; stack trace: ***
    @     0x7f9ec43fa46d (/home/yugabyte/yb-software/yugabyte-2.14.1.0-b36-centos-x86_64/linuxbrew/lib/libpthread-2.23.so (deleted)+0x1046c)
    @     0x7f9ec4be20cb (/home/yugabyte/yb-software/yugabyte-2.14.1.0-b36-centos-x86_64/lib/yb-thirdparty/libc++.so.1.0 (deleted)+0x740ca)
    @     0x7f9ec7e5b59f (/home/yugabyte/yb-software/yugabyte-2.14.1.0-b36-centos-x86_64/lib/yb/libserver_process.so (deleted)+0x5c59e)
    @           0x205964 (/home/yugabyte/yb-software/yugabyte-2.14.1.0-b36-centos-x86_64/bin/yb-master (deleted)+0x205963)
    @     0x7f9ec3a69825 (/home/yugabyte/yb-software/yugabyte-2.14.1.0-b36-centos-x86_64/linuxbrew/lib/libc-2.23.so (deleted)+0x20824)
    @           0x204e99 (/home/yugabyte/yb-software/yugabyte-2.14.1.0-b36-centos-x86_64/bin/yb-master (deleted)+0x204e98)`

**Comment by Arpit-yb** [comment]
Internal slack link - https://yugabyte.slack.com/archives/C01CB38CZHU/p1663048341830219

**Comment by arybochkin** [comment]
Important note. The cluster has a lot of tablets with 3 of 5 peers failed. Refer to this [message](https://yugabyte.slack.com/archives/C01CB38CZHU/p1663149341170569?thread_ts=1663048341.830219&cid=C01CB38CZHU) for logs details.

**Comment by rthallamko3** [comment]
@Arpit-yb , Can you clarify if you are able to repro this on 2.16 at all or not? If not, can we close this?

**Comment by Arpit-yb** [comment]
We can close this one, we have another ticket in YBA to add the preflight check for this

**Comment by rthallamko3** [comment]
Please close it with a reference to the other one.

**Comment by Arpit-yb** [comment]
Closing this in favour of another ticket in YBA - https://yugabyte.atlassian.net/browse/PLAT-5480
