### ISSUE TITLE
[DocDB] Speedup local bootstrap by persisting the retryable request structure

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14013]
Jira Link: [DB-3510](https://yugabyte.atlassian.net/browse/DB-3510)
### Description

Followup conversation with @ttyusupov , around #14005, about persisting the retryable write request structure, to speed up local bootstrap as well. Two options we were discussing
- On every WAL rollover, persist the whole structure to a file, one single file per tablet. On local bootstrap, read this file into memory + replay any last WAL segments still needed. This is more write heavy (full write each time), but faster on read.
- On every WAL rollover, persist just the elements relevant for this WAL file. On local bootstrap, figure out which pieces are needed, to respect the time window requirements and stitch these together, This is less write heavy (incremental write), but more logically complex (tracking per file) & maybe more read heavy (read N smaller files instead of 1).

Note: This would help even outside of tablet splitting, as right now, local bootstrap is slowed down, by us having bumped the retryable request time from 120s to 660s, so we need to replay potentially up to 660s worth of WAL data...

**Comment by Huqicheng** [comment]
The first version of enhancement will be in memory. Child tablets can copy retryable requests from the parent, this can avoid replaying through bootstrap.

**Comment by Huqicheng** [comment]
<img width="1218" alt="iops_write_concurrency" src="https://user-images.githubusercontent.com/31775227/194799694-70d1f1ce-12cb-493a-a9b0-004b68c4cc2e.png">

**Comment by rthallamko3** [comment]
Backporting the #14265 to 2.14 is sufficient. This is not needed to be backported.
