### ISSUE TITLE
[Docs] YugabyteDB Quick start

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#14051]
### Description

This page: https://docs.yugabyte.com/preview/quick-start/docker/
pulls the latest preview tag: `2.15.2.0-b87`
but runs the `latest` tag which is an older version

👉🏻 documentation should be consistent using either the tag for the latest preview or `latest` (but then it should be really the latest one on the docker hub)

**Comment by polarweasel** [comment]
The `docker run` commands should be using the same `yb-version` shortcode as the rest are...
