### ISSUE TITLE
[YCQL] A default value for FLAGS_cql_service_max_prepared_statement_size_bytes

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1406]
If the app is preparing a lot of unique statements, the tablet server might run out of the memory. We need to set the default value of FLAGS_cql_service_max_prepared_statement_size_bytes based on the total available memory, similarly to how we set other memory limits.

**Comment by kmuthukk** [comment]
Issue related to/duplicate of: https://github.com/YugaByte/yugabyte-db/issues/1026

**Comment by robertpang** [comment]
The default `cql_service_max_prepared_statement_size_bytes` is set to 128 MB by commit c5cef2a.
