### ISSUE TITLE
[DocDB] Packed Row: SST dump doesn't work well with packed row format rows.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#14063]
Jira Link: [DB-3558](https://yugabyte.atlassian.net/browse/DB-3558)
### Description

Steps to repro:

1. Enable packed rows on the tservers - ysql_enable_packed_row
2. Run a ysql workload.
3. Flush the table(s) on which the workload was run.
4. Pick a tablet, try to dump the contents of the SST file using sst_dump. The sst_dump fails with the error as mentioned in the example below.

Example: 

```
./sst_dump --file=/mnt/d0/yb-data/tserver/data/rocksdb/table-000033e1000030008000000000004005/tablet-e4360d38f5e64d8e9741cad04b0c5188/000010.sst --output_format=decoded_regulardb --command=scan
from [] to []
Process /mnt/d0/yb-data/tserver/data/rocksdb/table-000033e1000030008000000000004005/tablet-e4360d38f5e64d8e9741cad04b0c5188/000010.sst
Sst file format: block-based
Not found (yb/docdb/packed_row.cc:199): Schema packing not found: 0: . Key: SubDocKey(DocKey(0x1210, [1], []), [HT{ physical: 1655318451663257 }])
```

**Comment by rthallamko3** [comment]
With the above fix, the sst_dump would be able to dump debug information for PackedRows, using the new argument
--formatter_tablet_metadata=<path_to_tablet_metadata>

cc @kripasreenivasan , @fritshoogland-yugabyte

**Comment by mdbridge** [comment]
fixes for packed rows in colocated tablets backported to 2.18.2

**Comment by mdbridge** [comment]
from @rthallamko3:
> Backport to 2.16 is risky due to additional dependencies. We decided to use the sst_dump tool from 2.18 branch if needed. Thanks @mdbridge for driving the discussions around this.

**Comment by mdbridge** [comment]
fixing this for 2.16 requires also fixing https://github.com/yugabyte/yugabyte-db/issues/16665 for 2.16; some partial work was done but abandoned there.

**Comment by dataindataout** [comment]
The gflag `ysql_enable_packed_row` is on by default in 2.20.3, and this causes the problem above.

The error message itself observed in this case is different than reported above, but the solution is the same.

Error message in sst_dump output:
`...Not found (yb/docdb/kv_debug.cc:114): No packing information available'

Solution:
Use flag in sst_dump command `--formatter_tablet_metadata=<path_to_tablet_metadata>`. The tablet metadata can be found in the data directory tserver/table-metadata/[tablet ID] folder (e.g., --formatter_tablet_metadata=/mnt/d0/yb-data/tserver/tablet-meta/c4bdc46c359c4e6fafab8b3e1d87e03d).

**Comment by mdbridge** [comment]
see https://github.com/yugabyte/yugabyte-db/issues/18202, which is
explicitly to improve the usage message in this case so it will be obvious
to the user what to do
