### ISSUE TITLE
[YSQL] Batch parameters that are input into subplans

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#14071]
Jira Link: [DB-3566](https://yugabyte.atlassian.net/browse/DB-3566)
### Description

We can look into batching subplan input parameters similar to how we batch nested loop joins. For example, we can look into batching instances of `c.oid` for the subquery here:
`select c.oid, (select indexrelid from pg_index where indrelid = c.oid limit 1) from pg_class c;`

**Comment by sushantrmishra** [comment]
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/18417
