### ISSUE TITLE
[xCluster] Handle uneven transaction status tablets

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#14075]
Jira Link: [DB-3569](https://yugabyte.atlassian.net/browse/DB-3569)
### Description

Handle multiple transaction status tablets, related to https://github.com/yugabyte/yugabyte-db/issues/14105

[DB-3569]: https://yugabyte.atlassian.net/browse/DB-3569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hulien22** [comment]
Closed by [d861713](https://github.com/yugabyte/yugabyte-db/commit/d86171311229c60c2891fd6fee19316fc792cd98)
