### ISSUE TITLE
[DocDB][Backup][Tablegroup][Materialized View] Create backup on a database containing tablegroups fails with OBJECT_NOT_FOUND (master error 3)

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14081]
Jira Link: [DB-3575](https://yugabyte.atlassian.net/browse/DB-3575)
### Description

Steps:
- Create a database, tablegroups and tables opted in and out of the tablegroup and insert data
- Create a materialized view combining tables in different tablegroups
- Create a backup of the DB.
**Issue:**
Backup creation fails with 
```
running create_database_snapshot: Not found (yb/master/catalog_manager.cc:4912): Unable to create snapshot of database: tg_db: Table with identifier 00004005000030008000000000000000.colocated.parent.uuid not found: OBJECT_NOT_FOUND (master error 3)
```

```
RROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o 'ControlPath=~/.ssh/ssh-%r@%h:%p' -o ControlPersist=1m -i /opt/yugabyte/yugaware/data/keys/ce82c126-7204-4dce-af28-7830d9f1f34c/yb-itest-fcd33772e2-20220919-163334_ce82c126-7204-4dce-af28-7830d9f1f34c-key.pem -p 22 -q yugabyte@10.9.210.94 'cd / &&  bash -c '"'"'/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.142.69:7100,10.9.192.70:7100,10.9.210.94:7100 create_database_snapshot ysql.tg_db --never_fsync=false'"'"'' ]]: code=1 output=Error running create_database_snapshot: Not found (yb/master/catalog_manager.cc:4912): Unable to create snapshot of database: tg_db: Table with identifier 00004005000030008000000000000000.colocated.parent.uuid not found: OBJECT_NOT_FOUND (master error 3)
```
This was caught by itest-system automation and is a 100% reproducible with `testbackupwithtablegroupscompressionandpackedcolumns`
CC: @sanketkedia

**Comment by def-** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/11632 I believe.

**Comment by sanketkedia** [comment]
I think @msun07 is fixing it as part of https://phabricator.dev.yugabyte.com/D19398

**Comment by bmatican** [comment]
@def- @kripasreenivasan could we retest this, since the above fix from @msun07 landed?

**Comment by def-** [comment]
@kripasreenivasan I'm not seeing a test named testbackupwithtablegroupscompressionandpackedcolumns in itest*, is it TestBackupWithCompressionAutomaticTSAndPackedColumns (submitted) or TestTablegroupsWithCompressionAndPackedColumns (https://phabricator.dev.yugabyte.com/D19633)? The former is green in master, the latter I have retriggered on master to check.
Edit: Just saw D19633 refers to this bug, so that's it.

**Comment by def-** [comment]
There is now a different failure. @kripasreenivasan can you check? Looks to me like this bug is fixed.
```
	(    12.842s) Verify colocation for tables in tablegroup : >>> Integration Test Failed <<< 
Different Tablegroups are colocated in the same tablet ['7554ed0458ae4031b918e670c99e9afc']
```

**Comment by kripasreenivasan** [comment]
Sure, this looks like a test failure. I will rerun my test and debug.

**Comment by kripasreenivasan** [comment]
The backup creation does not fail after @msun07 's fix. CC @lingamsandeep , @bmatican , @sanketkedia
