### ISSUE TITLE
Invalid option: --with-assembly

### ISSUE THREAD

**Issue by swayamraina** [YugaByte/yugabyte-db#1408]
Hi, 

I cloned the source code and was trying to build it. I followed the steps for building code for Mac. I get the following error,

> Invalid option: '--with-assembly'

`yb_build.sh` file no longer contains this option. 
I wanted to contribute to certain (good-first) issues, how should I proceed?

**Comment by kmuthukk** [comment]
hi @swayamraina 

I believe you are following the steps here:

https://github.com/YugaByte/yugabyte-db#building-the-code

I think the README.md is out of sync.  As it mentions, 

<<  The --with-assembly flag tells the build script to build the yb-sample-apps.jar file containing sample Java apps. >>

But the sample apps have now been moved to a separate github project: 

https://github.com/YugaByte/yb-sample-apps

So, please just try the build thus:

```
./yb_build.sh release
```

We will update the docs soon.

**Comment by kmuthukk** [comment]
Fixed the docs to remove the stale --with-assembly option.
