### ISSUE TITLE
using docker, can't run yedis

### ISSUE THREAD

**Issue by hiqbn** [YugaByte/yugabyte-db#1409]
after

./yb-docker-ctl create --rf 3

Could not open YBTable

it says it's automatically initialized but doesnt work. how to resolve?

**Comment by kmuthukk** [comment]
@hiqbn - 

not sure if this was resolved (didn't fully catchup on the slack discussion). Is this still an issue? if so, could you kindly share the output of the create step please.

**Comment by hiqbn** [comment]
won't be using yedis for yugabyte. it's ok. thx
