### ISSUE TITLE
API: Provide API to specify custom Instance types

### ISSUE THREAD

**Issue by RashmiPanthangi** [YugaByte/yugabyte-db#1410]
We should have the ability to override the Instance Types values displayed in the create universe page.

**Comment by ramkumarvs** [comment]
@RashmiPanthangi as per Pallavi's email, here is the list of instance types you guys wanted 
```
Small – 4 cores, 7.5GB RAM, 50 GB storage
Medium – 8 cores, 15 GB RAM, 50 GB storage
Large – 16 cores, 30 GB RAM, 50 GB storage
```

**Comment by ramkumarvs** [comment]
Currently for kubernetes we create 5 different instance types (xsmall, small, medium, large and xlarge). For your use case looks like you have to disable two instance types (xsmall, xlarge). And update the other three instance types (small, medium and large).

To disable a instance type (lets say xsmall) you can use this curl, make sure to update the correct _customer_uuid_ and _provider_uuid_ 
```
curl -X DELETE \
  http://127.0.0.1:80/api/v1/customers/*customer-uuid*/providers/_provider-uuid_/instance_types/xsmall \
  -H 'Accept: */*' \
  -H 'Content-Type: application/json' \
  -H 'Host: 127.0.0.1:80' \
  -H 'X-AUTH-TOKEN: 1234-1235-2445-31324-23322222'
```

To update a existing instance type, with different specifications you can run the below curl
```
curl -X POST \
  http://127.0.0.1:80/api/v1/customers/*customer_uuid*/providers/*provider_uuid*/instance_types \
  -H 'Content-Type: application/json' \
  -H 'Host: 127.0.0.1:80' \
  -H 'X-AUTH-TOKEN: 12343-44-444-453-33344' \
  -d '{
	"numCores": 4,
	"memSizeGB": 7.5,
	"idKey": {
            "providerCode": "kubernetes",
            "instanceTypeCode": "small"
        },
    "instanceTypeDetails": {
        "volumeDetailsList": [
            {
                "volumeSizeGB": 50,
                "volumeType": "SSD",
                "mountPath": "/mnt/d0"
            }
        ]
    }
}

'
```

To get the provider uuid for the above api's you can call the below api
```
curl -X GET \
  http://127.0.0.1:80/api/v1/customers/*customer_uuid*/providers \
  -H 'X-AUTH-TOKEN: 123-444-55-555-5555' \
  -H 'cache-control: no-cache'
```

Feel free to close this issue if the above information is gives you want you guys wanted.

**Comment by sraghavan-eqix** [comment]
Adding instance type seems to be fine. Was able to add a new instance type and it was showing up while creating Universe.

Deletion:
 The curl command worked fine. Saw the response like below;
  {"success":true}

However - the actual instance did not get deleted. It is still appearing in the drop down while creating Universe.

**Comment by sraghavan-eqix** [comment]
Did the above 2 steps after cloud provider registration. Gott the provider UUID first with the GET call

**Comment by ramkumarvs** [comment]
@RashmiPanthangi @sraghavan-eqix filtering deleted instance type is fixed as of 1.2.11.0-b11. Please test the same and confirm

**Comment by sraghavan-eqix** [comment]
@ramkumarvs Ran a quick test with the new tag mentioned above. Now it filters out the deleted instances in the Universe Creation page and also we are able to post a custom instance.

**Comment by ramkumarvs** [comment]
@RashmiPanthangi closing this issue. Since you have the necessary instructions.
