### ISSUE TITLE
[YSQL] Throw the same error message as Pg when a deadlock is detected

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#14114]
Jira Link: [DB-3597](https://yugabyte.atlassian.net/browse/DB-3597)
### Description

Pg throws a detailed error message when a deadlock is detected as shown below:

<img width="1792" alt="Screen Shot 2022-09-21 at 9 57 52 AM" src="https://user-images.githubusercontent.com/12711838/191566034-1b6d6024-0e1a-46cc-a462-8da53ecade66.png">

We should improve our error message to similarly convey that a transaction was cancelled due to deadlock. We can also include a list of transactions involved and IDs of nodes serving those transactions

[DB-3597]: https://yugabyte.atlassian.net/browse/DB-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
Ideally we would also display the node_id of clients involved in the deadlock along with the transaction_id in the error message

**Comment by robertsami** [comment]
As a first cut, even simply returning the fact that a deadlock was detected, rather than a generic error message as we display today, would be a useful improvement
