### ISSUE TITLE
[YSQL] Non-key columns in unique index affect constraint enforcement

### ISSUE THREAD

**Issue by srhickma** [YugaByte/yugabyte-db#1412]
**Summary:** Adding INCLUDE (non-key) columns in a unique index affects the enforcement of uniqueness on the key columns. This should not be the case.

**Reproduction Steps:**
```
postgres=# CREATE TABLE tst (c1 int, c2 int);
CREATE TABLE
postgres=# INSERT INTO tst (c1, c2) VALUES
postgres-# (1, 1),
postgres-# (1, 2);
INSERT 0 2
postgres=# CREATE UNIQUE INDEX tst_uidx ON tst USING lsm (c1) INCLUDE (c2);
CREATE INDEX
```
**Expected Results:** It is expected that the CREATE INDEX statement will produce an error, since there are duplicate values in `c1`.

Note: If `INCLUDE (c2)` is removed, then the correct error is displayed:
```
postgres=# CREATE UNIQUE INDEX tst_uidx2 ON tst USING lsm (c1);
ERROR:  duplicate key value violates unique constraint "tst_uidx2"
```

**Comment by robertpang** [comment]
This issue is fixed in commit 3de20a3.
