### ISSUE TITLE
[DocDB] Track ql_read_latency for SQL too

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#14128]
Jira Link: [DB-3608](https://yugabyte.atlassian.net/browse/DB-3608)
### Description

For cql/redis reads into Docdb, we have ql_read_latency and redis_read_latency. But, no such tracking for pgsql.

We should just unify all of these into `ql_read_latency`. No need to have 3 separate metrics, as only one of them can be non-zero for any given Table type.  See: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tablet/tablet.cc#L1392

Also enable similar tracking in the PgSql code path [here](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tablet/tablet.cc#L1486)

**Comment by daligrim** [comment]
Can I have this assigned?

**Comment by bmatican** [comment]
Hey @daligrim @UtR491 , actually, @yusong-yan already has a WIP diff internally and we'll be pushing that out soon.
If either of you are interested in other contributions to YB, feel free to join our public slack channel and hop onto the #contributors channel!

**Comment by rthallamko3** [comment]
reactivating for 2.14 backport
