### ISSUE TITLE
[YSQL][PessimisticLocking] Transaction is being aborted even after deadlock resolution

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14134]
Jira Link: [DB-3611](https://yugabyte.atlassian.net/browse/DB-3611)
### Description

I observed the following error which seems very vague:
`ERROR: Operation expired: Heartbeat: Transaction 63ef23f4-ec83-47a8-9e76-5f8ce634ad1a expired or aborted by a conflict: 40001`

Steps to reproduce:

1. Create a table with min 3 rows in it.
2. Explicit lock the R1 in T1; R2 in T2; R3 in T3
3. Try accessing R3 in T1; R1 in T2; R2 in T3
4. T3 will be aborted immediately due to deadlock with error `ERROR: Internal error: Transaction 06b6b2db-e3f2-41c0-b14d-57bbada4b5ce was aborted while waiting for locks`
5. After that the locks would be released and wit will be over for T1 & T2
6. Wait for some time and try to commit T1/T2
7. This will throw the above mentioned error.

The error doesn't clearly mention the reason why transaction got aborted and is a little vague. From my observation, it is because of the wait time in step 6 as I didn't face this issue when I commit the transactions as soon as the waiting command gets executed. There are a couple of issues here:
1. We shouldn't be aborting >1 transactions during deadlock as the transaction leading to deadlock is being aborted immediately, leading to no deadlock after that. So, no more transactions should be aborted.
2. The error thrown for the later transaction (in step 7) abortion is not very specific as to why was that particular transaction aborted. The error message needs to be improved.

**Comment by Karvy-yb** [comment]
Discussed this with @robertsami and @pkj415 over slack who said that this fix is not very simple and would take time. Thus logging a low priority bug.

**Comment by robertsami** [comment]
I created https://github.com/yugabyte/yugabyte-db/issues/14165 to track issue 1., and issue 2. is covered by https://github.com/yugabyte/yugabyte-db/issues/14114, so closing this one
