### ISSUE TITLE
[xCluster]  Ensure we can PITR to xCluster safe time

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#14131]
Jira Link: [DB-3610](https://yugabyte.atlassian.net/browse/DB-3610)
### Description

Ensure we can PITR to xCluster safe time

**Comment by kripasreenivasan** [comment]
@hari90 , @lingamsandeep ,

Would the following scenario get covered when this is taken up?

- Create a source and target universe with packed columns enabled
- Create identical schemas on both sides
- Setup unidriectional Xcluster replication from source to target
- Create a snapshot_schedule at the source side and collect time(A) after various operations
- Load data and validate the replication
- Restore source to timestamp A.
**Observation:**  Restore is successful but replication stops post restore. Note no DDL has been executed.

**Comment by hari90** [comment]
This has been validated
