### ISSUE TITLE
[YSQL] Import ALTER obj fix

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#14146]
Jira Link: [DB-3622](https://yugabyte.atlassian.net/browse/DB-3622)
### Description

Import ALTER obj fix

**Comment by paullee-yb** [comment]
Abandoning this diff since it's dependent on `ALTER <object> DEPENDS ON EXTENSION`, which isn't supported in YB yet. Filed GH issue here: https://github.com/yugabyte/yugabyte-db/issues/14340.
