### ISSUE TITLE
[YSQL] flaky test: org.yb.pgsql.TestPgRegressJson.testPgRegressJson

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14176]
Jira Link: [DB-3648](https://yugabyte.atlassian.net/browse/DB-3648)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressJson&fail_tag=all&name=testPgRegressJson&platform=linux

**Comment by tedyu** [comment]
This is dup of #14183
