### ISSUE TITLE
[YSQL] flaky test: org.yb.pgsql.TestPgRegressExtension.testPgRegressExtension

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14177]
Jira Link: [DB-3649](https://yugabyte.atlassian.net/browse/DB-3649)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressExtension&fail_tag=all&name=testPgRegressExtension&platform=linux

seems flaky in several build types, but clearly broken in ASAN since https://github.com/yugabyte/yugabyte-db/commit/388ae9def67cd91527b5968f58b7fe1e8b6e7766

**Comment by tedyu** [comment]
This error doesn't affect the functionality of hypopg.

I will fix it later.

**Comment by tedyu** [comment]
@bmatican 
I think this should be medium priority.

**Comment by bmatican** [comment]
@tedyu this is failing in almost every commit, so it is adding noise to every diff!
> ==73225==AddressSanitizer: WARNING: unexpected format specifier in printf interceptor: %hc (reported once per process)
