### ISSUE TITLE
[backups] Backup/restore needs to handle retrieving credentials when IMDSv2 is set on EC2 instance

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#14175]
Jira Link: [DB-3647](https://yugabyte.atlassian.net/browse/DB-3647)
### Description

When IMDSv2 is enabled in a customers environment on their EC2 nodes, the traditional `get_instance_metadata` call will fail with empty {}. This causes a blank file to be written for the `cloud_cfg` file. 

Steps to reproduce:
```
$ aws ec2 modify-instance-metadata-options --instance-id <your_instance_id> --http-tokens required  --http-endpoint enabled
```

Run a normal platform backup to S3.
It will fail with a 78 error code indicating a malformed file.

**Comment by rthallamko3** [comment]
The corresponding plat item is closed.
