### ISSUE TITLE
[DocDB] flaky test: CDCSDKYsqlTest.TestEnumWithMultipleTablets

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14171]
Jira Link: [DB-3642](https://yugabyte.atlassian.net/browse/DB-3642)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestEnumWithMultipleTablets&platform=linux

**Comment by arpang** [comment]
@sureshdash2022-yb Please take a look at this test.
