### ISSUE TITLE
[Thread Sanitizer] check failed in UT- EncryptionTest.AllMastersRestart

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14187]
Jira Link: [DB-3655](https://yugabyte.atlassian.net/browse/DB-3655)
### Description

EncryptionTest.AllMastersRestart is failing with this Thread sanitizer stacktrace in 2.15.3.0-b227 - https://gist.github.com/kripasreenivasan/511aba39bc129c7beea7a520fe8da87b

**Comment by bmatican** [comment]
Another instance of #14098
