### ISSUE TITLE
[YCQL] Thread Sanitizer data race observed in TestJsonIndex__testIndexEscapeName

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14189]
Jira Link: [DB-3657](https://yugabyte.atlassian.net/browse/DB-3657)
### Description

Thread Sanitizer data race observed in TestJsonIndex__testIndexEscapeName 
Stacktrace- https://gist.github.com/kripasreenivasan/da9a472bdb1dda973561df2c7c3ede9a

**Comment by bmatican** [comment]
Seems like a race on drop keyspace vs ycql system query read
