### ISSUE TITLE
[DocDB] Thread Sanitizer check failed in UT XClusterAdminCliTest_TestRenameUniverseReplication

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14188]
Jira Link: [DB-3656](https://yugabyte.atlassian.net/browse/DB-3656)
### Description

Thread Sanitizer check failed in UT XClusterAdminCliTest_TestRenameUniverseReplication- https://gist.github.com/kripasreenivasan/978d8a25340628564416eb6ae4779865

**Comment by mbautin** [comment]
Some more occurrences of this error: 

https://gist.githubusercontent.com/mbautin/7fd4ccda0ca874bb0719e730163c41fc/raw

**Comment by mbautin** [comment]
Duplicate of #14098.
