### ISSUE TITLE
[YSQL]  Test  TestPgRegressJson.testPgRegressJson fails Master

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#14183]
Jira Link: [DB-3653](https://yugabyte.atlassian.net/browse/DB-3653)
### Description

**Detective link** -- https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressJson&fail_tag=all&name=testPgRegressJson&platform=linux

**Comment by tedyu** [comment]
I tried the statement on local cluster:
```
yugabyte=# SELECT '"abc'::json;
ERROR:  invalid input syntax for type json
LINE 1: SELECT '"abc'::json;
               ^
DETAIL:  Token ""abc" is invalid.
CONTEXT:  JSON data, line 1: "abc
yugabyte=# ^D\q
```
Didn't reproduce the wrong output shown in (some) test output.

**Comment by tedyu** [comment]
Ran the following locally:
```
ybd --java-test 'org.yb.pgsql.TestPgRegressJson#testPgRegressJson' -n 21
```
No single failure.

**Comment by tedyu** [comment]
commit 6a47b19e1f3542f4bebab4a44bbe6d90ddee882b
Author: Ted Yu <yuzhihong@gmail.com>
Date:   Tue Sep 27 07:55:49 2022 -0700

    [#13782] Revert Import Build de-escaped JSON strings in larger chunks during lexing
