### ISSUE TITLE
Add some unique identifier for the form elements in Create Universe form

### ISSUE THREAD

**Issue by ramkumarvs** [YugaByte/yugabyte-db#1419]
In order to make YugaWare whitelabling work, we need to add some unique identifiers for the form elements in Create Universe form and Edit flows, so we can override the values via css overrides when doing custom theme.

**Comment by ramkumarvs** [comment]
Implementation: We introduce data attributes at some top level components like Label, Input etc, and we can use that data attribute to narrow down the element we want to style in the CSS, this is really helpful when we want to apply custom theme/white label YugaWare.

Example Overrides would look something like this
To change the label name you can do something like this in the css override
```
[data-yb-label="Name"] > label:before {
    content: "DB Name";
    font-size: 14px;
}
[data-yb-label="Name"] > label {
    font-size: 0;
}
```

To hide a component completely you can do something like this.
```
[data-yb-label="Replication Factor"] {
    visibility: hidden;
}
```

If you want to hide sections in the create universe you can do that simply with css like this.
```
[data-yb-section="advanced"] {
    display: none;
}

[data-yb-section="g-flags"] {
    display: none;
}
```
If you want to hide all the beta features, you can do that with the following css.
```
[data-yb-beta="true"] {
    display: none !important;
}
```

**Comment by yb-andrew** [comment]
Fixed on master
