### ISSUE TITLE
[DocDB] Further optimize storage efficiency of Packed Row format for small types & nulls

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#14203]
Jira Link: [DB-3667](https://yugabyte.atlassian.net/browse/DB-3667)
### Description

We tested storage efficiency of packed row format on a table with 1000 integer columns and compared that with the option of storing the same data in a UDT column where the UDT type has 1000 attributes.

Note that compared to non-packed row format, the packed row format's in memory usage is about 5x better.  However, compared to the format in which this data is stored in a single UDT column, there's still a 2x gap.

*Scripts used for the experiment:*

[wide_rows.py](https://gist.github.com/kmuthukk/6280d3e0a88ee7ef4b352912d7720a49) to create a table with desired number of columns per row (into a 1 tablet table).
[packed.sh](https://gist.github.com/kmuthukk/5cd2525d220fabd6b6ef6e1ff05bc2f5) driver shell script to repeat experiment with different settings, load data using above script, flush/compact the 1 tablet, and extract sizes.
Sample invokation:
`sh ~/notes/packed.sh | grep -E "(Results|rocksdb)"`

**Results**

*Test Case:*
```
number of columns=1000 or 1000 attrs packed in UDT type
rows=2000
```

*UNPACKED Results*
```
packed_row=false;compression=Snappy
rocksdb_current_version_sst_files_size =              22,477,061
rocksdb_current_version_sst_files_uncompressed_size = 93,121,132

packed_row=false;compression=Snappy; --use_udt
rocksdb_current_version_sst_files_size =               8,169,008
rocksdb_current_version_sst_files_uncompressed_size =  8,279,399

```

*PACKED Results*
```
packed_row=true;compression=Snappy
rocksdb_current_version_sst_files_size              = 10,513,304 (snappy + packed nearly as good as snappy + udt)
rocksdb_current_version_sst_files_uncompressed_size = 18,152,291 (in-memory size is about 2x compared to UDT format;
                                                                  any potential optimizations to look at?)


```

*Observations:*

* On-disk sizes are about 2x better for Packed vs. Unpacked  (10M vs. 22M) 
* In memory (block cache) usage is 5x better with packed row format compared to unpacked (93M vs. 18M); this doesn't depend on compression type.
* UDT vs. Packed -- uncompressed sizes about 2x better with UDT than packed format (8.2MB vs. 18MB)

*Analysis/Suggestions for further improvement*

Note: This section is based on notes from (& some discussion) with @spolitov.

There are examples of postgres UDT encoding for type that consists only from ints:
```
udt of 9 ints:
(1,2,3,4,5,6,7,8,9)
73FFFFFFFF42400000FFFFFFFF0000090000001800010000000200000003000000040000000500000006000000070000000800000009000000
(1,NULL,3,NULL,5,NULL,7,NULL,9)
63FFFFFFFF42400000FFFFFFFF000009000100205501000000000000000100000003000000050000000700000009000000

udt of 8 ints:
(1,2,3,4,5,6,7,8)
6BFFFFFFFF3A400000FFFFFFFF00000800000018000100000002000000030000000400000005000000060000000700000008000000
(1,NULL,3,NULL,5,NULL,7,NULL)
4BFFFFFFFF3A400000FFFFFFFF000008000100185501000000030000000500000007000000
```

For our packed rows format we have the following “issues” that could be improved:

* we always use 4 bytes to encode column offset. Could introduce extra packing formats, that will use 1 or 2 bytes, depending on row size
* we always put value type at the start of the column value, since it is not trivial to extract actual value type in our code base.
so for particular example we could win 4 bytes per column. 3 bytes in offset and 1 byte in value type.
* also, Postgres uses bit map for nulls, while we use 0 bytes length columns as nulls. So could migrate fixed length nullable columns to bit mask also. it will give extra 7/8 bytes per column.
* For packed rows we also have value type - kPackedRow. Could just introduce new values type. For instance rename kPackedRow to kObsoletePackedRow and add 3 more types - kPackedRow1, kPackedRow2, kPackedRow4. Depending on number of bytes used for offset enoding.

**Comment by rthallamko3** [comment]
https://github.com/yugabyte/yugabyte-db/issues/25366 tracks enabling the gflag ysql_use_packed_row_v2  on by default.
