### ISSUE TITLE
[YSQL] Database crashed during import of 400+ objects schema

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#14208]
Jira Link: [DB-3673](https://yugabyte.atlassian.net/browse/DB-3673)
### Description

Using YugabyteDB 2.15.0.0.

```
./bin/yugabyted start
./bin/ysqlsh

CREATE DATABASE restore_1;
```
And then a simple import:
```
pg_restore -h 127.0.0.1 -p 5433 -U yugabyte -d restore_1 -v db.bkp
```
Results in the following log import.
[yuga_import_log.txt](https://github.com/yugabyte/yugabyte-db/files/9652741/yuga_import_log.txt)

The import script will be uploaded in jira so it's not public.

The logs from `./bin/yugabyted collect_logs`
[yugabyted-2022-09-27-09:21:08.977777.tar.gz](https://github.com/yugabyte/yugabyte-db/files/9652763/yugabyted-2022-09-27-09.21.08.977777.tar.gz)

The generated core dump 
[core dump.zip](https://github.com/yugabyte/yugabyte-db/files/9652813/core.dump.zip)

**Comment by def-** [comment]
The FATAL.details files show this error:
```
F20220927 07:20:30 ../../src/yb/consensus/log_util.cc:176] Check failed: _s.ok() Bad status: IO error (yb/util/env_posix.cc:1506): /home/guru/var/data/yb-data/tserver/wals/table-00004000000030008000000000004519/tablet-b313810ceb4d4d64858f18d17de0090d/wal-000000039: Too many open files (system error 24)
```
`sudo ulimit -n 1048576` can be used to increase the number of open file descriptors.

**Comment by ddorian** [comment]
@def- yes, my bad. Fixing ulimits made it work https://docs.yugabyte.com/preview/deploy/manual-deployment/system-config/#ulimits
