### ISSUE TITLE
[DocDB] flaky test: TabletSplitITest.TestInitiatesCompactionAfterSplit

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14211]
Jira Link: [DB-3676](https://yugabyte.atlassian.net/browse/DB-3676)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&buckets=20&build_type=all&class=TabletSplitITest&fail_tag=all&name=TestInitiatesCompactionAfterSplit&platform=linux

Most likely related to enable_lease_revocation, as the test doesn't seem to cover for LEADER_NOT_READY_TO_SERVE

**Comment by rthallamko3** [comment]
https://detective.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TabletSplitITest&fail_tag=all&name=TestInitiatesCompactionAfterSplit&platform=all
