### ISSUE TITLE
ThreadSanitizer check failure in LinkedListTest_TestLoadAndVerify

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14243]
Jira Link: [DB-3702](https://yugabyte.atlassian.net/browse/DB-3702)
### Description

ThreadSanitizer check failure in LinkedListTest_TestLoadAndVerify in latest master - 2.15.4.0-b40
Stacktrace https://gist.github.com/kripasreenivasan/1d02024584306497c2170a2bb27822e4

**Comment by bmatican** [comment]
Duplicate of #14098
