### ISSUE TITLE
Thread Sanitizer check failed in TsRecoveryITest_TestCrashDuringLogReplay

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14244]
Jira Link: [DB-3703](https://yugabyte.atlassian.net/browse/DB-3703)
### Description

Thread Sanitizer check failed in TsRecoveryITest_TestCrashDuringLogReplay in latest master - 2.15.4.0-b40
Stacktrace- https://gist.github.com/kripasreenivasan/57f78ab5730ed4a10691f6f667785578

**Comment by bmatican** [comment]
Duplicate of #14098
