### ISSUE TITLE
unable to create the tables in postgres api

### ISSUE THREAD

**Issue by lokeshlal** [YugaByte/yugabyte-db#1424]
Hello, I am getting following error while creating the table using psql cli.

DDL:
CREATE TABLE products( id  bigint PRIMARY KEY, created_at timestamp, category text);

ERROR:
ERROR:  Invalid argument: Invalid table definition: Timed out (yb/client/client-internal.cc:153): Timed out waiting for Table Creation

Thanks,

**Comment by lokeshlal** [comment]
however, tables are getting created in db.

**Comment by nocaway** [comment]
- The error message "Invalid table definition" in class PgCreateTable is misleading.  We'll update our error message and error code.

- The timed-out message showed up most likely because the network had unexpectedly slowdown. We use the execution-time of the previous statements to predict how long it takes to execute the current statement. When the network slows down at certain point in time, the timed-out error would show up, and user would need to recreate the table with the statement "CREATE IF NOT EXIST".

**Comment by ndeodhar** [comment]
Hi @lokeshlal, thanks for reporting this issue. Can you please provide some more details on your setup so we can help you better?
- Is this a local setup? Are you using SSD or HDD? We recommend that YugaByte be used with SSDs.
- What is your replication factor? Note that if you used yb-ctl to create this cluster, then by default, it will be 1.
- Any error or warning messages in tserver or master logs? You can find the logs at `$data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO` and `$data_dir/node-1/disk-1/master/logs/yb-master.INFO`.

Like @nocaway mentioned, this error is most likely due to slow network and you can create the table using `CREATE IF NOT EXISTS`.

**Comment by lokeshlal** [comment]
@nocaway seems like you are correct. In tables tab on admin console I can see tablet state as creating...and a lot of create tablet tasks in waiting state.

I will add more details in some time

**Comment by lokeshlal** [comment]
I am seeing this error message repeatedly in tserver.info logs

`
W0524 05:23:18.467655 34119 acceptor.cc:158] Acceptor: accept failed: Network error (yb/util/net/socket.cc:395): accept4(2) error: Too many open files (error 24)
`


I can always create first 2 tables and after that when i try to create the third table i get this error.

this is what I am trying to create

```
CREATE TABLE products( id  bigint PRIMARY KEY, created_at timestamp, category text);

CREATE TABLE users( id  bigint PRIMARY KEY, created_at timestamp,name  text,email text, city text, state text);

CREATE INDEX users_by_state_and_city ON users (state) include (city);

CREATE TABLE items ( id bigint PRIMARY KEY, created_at timestamp, user_id bigint, product_id bigint, quantity int, total float);

```
I am running on three F4s machines on azure with premium ssd 200 gb and accelerated networking on. all machines in same subnet and region. setup is using private ips.

steps to create the setup

```
wget https://downloads.yugabyte.com/yugabyte-ce-1.2.6.0-linux.tar.gz

tar xvfz yugabyte-ce-1.2.6.0-linux.tar.gz && cd yugabyte-1.2.6.0/

./bin/post_install.sh

./bin/yb-master --master_addresses 10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100 --rpc_bind_addresses 10.0.4.4 --fs_data_dirs "/home/company/datadrive" >& /home/company/datadrive/yb-master.out &

./bin/yb-master --master_addresses 10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100 --rpc_bind_addresses 10.0.4.5 --fs_data_dirs "/home/company/datadrive" >& /home/company/datadrive/yb-master.out &

./bin/yb-master --master_addresses 10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100 --rpc_bind_addresses 10.0.4.6 --fs_data_dirs "/home/company/datadrive" >& /home/company/datadrive/yb-master.out &


./bin/yb-tserver   --tserver_master_addrs 10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100   --rpc_bind_addresses 10.0.4.4   --start_pgsql_proxy   --pgsql_proxy_bind_address=10.0.4.4:5433   --cql_proxy_bind_address=10.0.4.4:9042   --fs_data_dirs "/home/company/datadrive"   >& /home/company/datadrive/yb-tserver.out &


./bin/yb-tserver   --tserver_master_addrs 10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100   --rpc_bind_addresses 10.0.4.5   --start_pgsql_proxy   --pgsql_proxy_bind_address=10.0.4.5:5433   --cql_proxy_bind_address=10.0.4.5:9042   --fs_data_dirs "/home/company/datadrive"   >& /home/company/datadrive/yb-tserver.out &

  
./bin/yb-tserver   --tserver_master_addrs 10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100   --rpc_bind_addresses 10.0.4.6   --start_pgsql_proxy   --pgsql_proxy_bind_address=10.0.4.6:5433   --cql_proxy_bind_address=10.0.4.6:9042   --fs_data_dirs "/home/company/datadrive"   >& /home/company/datadrive/yb-tserver.out &


YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=10.0.4.4:7100,10.0.4.5:7100,10.0.4.6:7100 /home/company/yugabyte-1.2.6.0/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres
```


Thanks

**Comment by lokeshlal** [comment]
to test further I also opened all incoming and outgoing request on firewall.

**Comment by ndeodhar** [comment]
Thanks for the information @lokeshlal.
For the `too many open files` error, we suggest changing ulimit settings to these:
https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/#checking-ulimits
Note in particular `open files   (-n) 1048576`

**Comment by lokeshlal** [comment]
After setting open file limit I am able to run the cluster successfully. noticed that table creation time reduced as well.

However while inserting test data got following error (program ran for some time like couple of minutes)

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (XX000: Query error: Restart read required at: { read: { physical: 1558687072336821 logical: 2 } local_limit: { physical: 1558687072356882 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }) (0A000: DISCARD not supported yet) (XX000: Query error: Restart read required at: { read: { physical: 1558687071590403 logical: 2 } local_limit: { physical: 1558687071600136 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }) (XX000: Query error: Restart read required at: { read: { physical: 1558687076851450 logical: 2 } local_limit: { physical: 1558687076853418 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }) (XX000: Query error: Restart read required at: { read: { physical: 1558687117126321 logical: 7 } local_limit: { physical: 1558687117127125 logical: 1 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }) (XX000: Query error: Restart read required at: { read: { physical: 1558687124779366 } local_limit: { physical: 1558687124782699 logical: 2 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }) (XX000: Query error: Restart read required at: { read: { physical: 1558687081609648 } local_limit: { physical: 1558687081611108 logical: 2 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }) ---> Npgsql.PostgresException: XX000: Query error: Restart read required at: { read: { physical: 1558687072336821 logical: 2 } local_limit: { physical: 1558687072356882 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at PostgresYugaByte.Program.GenerateUserAndOrders(Int32 threadId, String hostName) in D:\Projects\CitixSys\ConsoleApp1\PostgresYugaByte\Program.cs:line 87
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PostgresYugaByte.Program.Main(String[] args) in D:\Projects\CitixSys\ConsoleApp1\PostgresYugaByte\Program.cs:line 64
Aborted

```

**Comment by lokeshlal** [comment]
Another quick question... is there a concept of data collocation to improve the join performance?

Thanks,

**Comment by kmuthukk** [comment]
Hi @lokeshlal 

1) There was an issue with inserts to a table with a secondary index that we were flagging some inserts incorrect as requiring an internal restart. And looks your table does have a secondary index from the schema you shared above.

https://github.com/YugaByte/yugabyte-db/issues/1233

This issue was fixed in 1.2.9 release. (wget https://downloads.yugabyte.com/yugabyte-ce-1.2.9.0-linux.tar.gz). Could you kindly give it a try please?

2) No - we don't yet have a notion of co-partitioned tables. But that's something on our roadmap for sure. Would love to learn a bit more about your use case, and take that into account when prioritizing work on this feature.

regards,
Kannan

**Comment by lokeshlal** [comment]
Thanks for the response.

We are working on a solution where we need to have data of 350 customers. We need oltp as well as olap on the data as our customer is into retail auditing business. The user will be internal analyst (not exactly a SaaS solution). Hence we would need oltp + olap features in a single db.

 I tried the current version with 200 products, 40,000 users and 2m orders. It works well when I do very small range queries (that too parallel read n writes) however when entire set is being considered query takes lot if time... That may be because you only have hash based partitioning (read it in blog: DocDB currently supports the hash partitioning scheme, with range-partitioning support actively in the works.). 

In our case entire set will be queried at many steps (considering this is an auditing application and data coming in from customer will be of ~3 months).

We can leverage spark connectors for batch processing. However when analyst will be working, response time required has to be under few seconds for aggregate queries, which I believe can only be achieved if there is an option of ranged partitioning. 
 
The number of customers will eventually grow and we need a single point to manage all data (in terms of clustering, HA and ACLs) rather than having different databases for every customer. And avoiding challenges such as data on a single server grow beyond expectation (due to many reason) and then either migrate a customer to new server or vertical scale a server.

Please let know if there is a way to achieve this ybdb.

**Comment by kmuthukk** [comment]
hi @lokeshlal - which release of YB were you using. We had one important fix go into 1.2.9 which could explain the long delays with larger data sets (https://github.com/YugaByte/yugabyte-db/issues/1206).

**Comment by lokeshlal** [comment]
I am using 1.2.6. I will try with the latest version and update.

**Comment by ttyusupov** [comment]
Hi @lokeshlal , did you have a chance to try with the latest version?

**Comment by ttyusupov** [comment]
Hi @lokeshlal , just checking if you were able to get up and running. Please feel free to reach out, someone from our side will be happy to help. I am closing this issue for now, please feel free to open a new issue or reopen this one.

**Comment by frafra** [comment]
I tried YugabyteDB 2.1.2.0 on Fedora 31, single node, and I run the Django 3.0.4 test suite, getting the same error:

```
Traceback (most recent call last):
  File "/home/frafra/Downloads/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InternalError_: Invalid argument: Invalid table definition: Timed out waiting for Table Creation
```

**Comment by frafra** [comment]
YugabyteDB also filled all the free space on the disk with 182 GB of logs, saying that there were too many files opened.

**Comment by kmuthukk** [comment]
@frafra - 

Can you please check what `ulimit -n` reports for number of open files allowed (for the user you are running the YugabyteDB processes as). Also refer to:

https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/

**Comment by frafra** [comment]
@kmuthukk
Sure; it is 1024, which is the default on Fedora.
I followed the documentation and I did not get the same error, thank you :)

I still wonder if YugabyteDB should avoid to fill up the entire disk with logs if that limit is hit and if a different issue should be opened.

**Comment by rkarthik007** [comment]
> YugabyteDB should avoid to fill up the entire disk with logs if that limit is hit and if a different issue should be opened.

Hi @frafra - yes please, would be great if you could open another issue for this!
