### ISSUE TITLE
[Memory_Leak] Objects leaking memory in TestQLCreateIndex_TestQLCreateIndexExpr

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14241]
Jira Link: [DB-3700](https://yugabyte.atlassian.net/browse/DB-3700)
### Description

Objects leaking memory in TestQLCreateIndex_TestQLCreateIndexExpr in master 2.15.4.0-b40

Memory leak stacktrace- https://gist.github.com/kripasreenivasan/f2361f054d33b3f27bcc6151b1917be2 

CC: @tverona1

**Comment by bmatican** [comment]
Tracked in #14228
