### ISSUE TITLE
[DocDB] flaky test: CdcTabletSplitITest.GetChangesOnSplitParentTablet

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14268]
Jira Link: [DB-3719](https://yugabyte.atlassian.net/browse/DB-3719)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&buckets=20&build_type=all&class=CdcTabletSplitITest&fail_tag=all&name=GetChangesOnSplitParentTablet&platform=linux

seems likely due to https://github.com/yugabyte/yugabyte-db/commit/150e6f710cdb79878a499b68ddfbb16607ba9df8

**Comment by NatashaSerebryanaya** [comment]
The test is [flaky](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&class=CdcTabletSplitITest&name=GetChangesOnSplitParentTablet) again.
Reopen the issue so that the test can be muted.
