### ISSUE TITLE
[docdb] Send accurate error in case of failed cql unique index insertion

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#14264]
Jira Link: [DB-4893](https://yugabyte.atlassian.net/browse/DB-4893)
https://github.com/yugabyte/yugabyte-db/blob/af6d2a05a5b32ac0c2a56c9435cabab10908c4a8/src/yb/tablet/write_query.cc#L695

If this condition is hit, we send the same error message to the client, indicating that `Duplicate value disallowed by unique index`. but any failure to insert this value would produce this error message, which is misleading. we should have more precise and useful logic here by:
1. only sending this `Duplicate value disallowed by unique index` error if this is in fact the origin of the insertion error
2. sending a more accurate message in all other cases
3. in all cases, having some VLOG (not DVLOG) to indicate precise error details

[DB-4893]: https://yugabyte.atlassian.net/browse/DB-4893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DB-4893]: https://yugabyte.atlassian.net/browse/DB-4893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
It looks like we were able to debug the issue with additional vlogs and tserver restarts. Closing this as not needed as of now. @robertsami , Feel free to reactivate if additional info needs to be added in the area.
