### ISSUE TITLE
[DocDB] Tablet-splitting - Inserts fail after splitting a tablet

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#14298]
Jira Link: [DB-3737](https://yugabyte.atlassian.net/browse/DB-3737)
### Description

1. Create an RF1 (I created 3 masters and 1 TS but it shouldn't matter). Also, set the value of `cleanup_split_tablets_interval_sec` gflag to 1, to speed up deletions of parent
2. Create a YCQL table with 1 tablet
3. Insert 10k rows
4. Issue the yb-admin split command to manually split the tablet into 2 tablets
5. Sleep for 5 secs
6. Insert a row in the table, it times out

To repro it with an existing unit-test, check `YbAdminRestoreDuringSplit.RestoreBeforeParentHidden`. Just comment out the `ASSERT_OK(cluster_->SetFlagOnTServers("TEST_skip_deleting_split_tablets", "true"));`
line. You can also comment out parts of the test that performs a restore subsequently although it does not matter, it fails much before that.

```
TEST_F(YbAdminRestoreDuringSplit, RestoreBeforeParentHidden) {
  const int kNumRows = 10000;

  // Create exactly one tserver so that we only have to invalidate one cache.
  SetRf1Flags();

  auto schedule_id = ASSERT_RESULT(PrepareCql());

  auto conn = ASSERT_RESULT(CqlConnect(client::kTableName.namespace_name()));

  // Insert enough data to cause splitting.
  ASSERT_RESULT(CreateTableAndInsertData(&conn, kNumRows));

  **// Set flag to disable hiding parent. [Comment this out]**
  **// ASSERT_OK(cluster_->SetFlagOnTServers("TEST_skip_deleting_split_tablets", "true"));**

  ASSERT_OK(TriggerManualSplit());

  std::this_thread::sleep_for(kCleanupSplitTabletsInterval * 5);

  // Restore time is after split completes but parent does not hide.
  Timestamp time(ASSERT_RESULT(WallClock()->Now()).time_point);
  LOG(INFO) << "Restore time " << time.ToHumanReadableTime();

  
...
}
```

**Comment by rthallamko3** [comment]
@arybochkin , Can you take this over? Let me know if it needs to be load balanced.

**Comment by arybochkin** [comment]
@rthallamko3 sure, I'm on it.

**Comment by rthallamko3** [comment]
@sanketkedia , Reminder to backport this to 2.14 branch after a few days of baking in master.
