### ISSUE TITLE
[DocDB] Packed: Restore should update table schema_version to the one in the backup

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14296]
Jira Link: [DB-3735](https://yugabyte.atlassian.net/browse/DB-3735)
### Description

For packed, we keep a reference to the older schemas, by versioning them in a SchemaPacking version on the tserver + keeping a schema_version ID in the row itself.

However, on restore, when we create tables, we just leave them at their default schema_version=0, without updating to the correct version from the backup. This breaks packed, if the data has any extra schemas, ie: if any Alters were run on the original data...

Master
On restore, we need to modify `CatalogManager::ImportTableEntry`, to also patch the schema version and send the corresponding Alters to the tservers.

Tserver
Similar to aef944a1830e9b4c01423897371144b5f084f977, we need to patch the tablet metadata to pick up the SchemaPacking from the backup as well.

Note: Since we caught this via manual testing, this suggests we do not have an in-repo test that does this workload + alter + backup/restore. We should make sure we add this, as a regression test, as part of this work!

cc @spolitov @OlegLoginov @rthallamko3

**Comment by rthallamko3** [comment]
@sanketkedia , reopening for backports to 2.16 and 2.17.0 branches.
