### ISSUE TITLE
[Docdb] [PITR] Kill all inflight transactions when starting a restore

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14290]
Jira Link: [DB-3731](https://yugabyte.atlassian.net/browse/DB-3731)
### Description

Steps followed:

1. Create universe with pessimistic locking enabled, deadlock detection enabled and consistent restore enabled.
2. Create a database
3. Create a table with multiple rows in the database
4. Create a schedule on the created database
5. Note down time
6. Start transaction T1 and UPDATE R1
7. Start another shell session and try to access R1 FOR UPDATE. This command will wait for T1 to complete.
8. Restore to time stamp noted in step 5.

The restore was successful but I was able to commit T1 after the restore and even though the commit went through, the data wasn't updated in the table.

cc: @pkj415 @bmatican @rthallamko3 @lingamsandeep 

[DB-3731]: https://yugabyte.atlassian.net/browse/DB-3731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@Karvy-yb , based on the time you restored to, it looks like the update should not be done either. What is the expection of the restore, do you expect the transaction to be rolled back?

**Comment by bmatican** [comment]
@Karvy-yb is this test automated? are we still seeing this issue? does it consistently repro?

**Comment by Karvy-yb** [comment]
@bmatican this isn't an automated test. I can validate manually to see if we are still hitting the issue here.

**Comment by Karvy-yb** [comment]
@rthallamko3 if i am able to commit the transaction after restore, I was expecting it to make the changes I made in the transaction.

**Comment by lingamsandeep** [comment]
@Karvy-yb now that consistent_restore is enabled by default, I am expecting this to work correctly. Could you retry and let us know ?

**Comment by Karvy-yb** [comment]
@lingamsandeep I tried the scenario again on latest master but I see no change in the behaviour.

Another observation is that if I wait for some time T2 will throw :
```
ERROR:  Transaction metadata missing: e01f9ba4-edee-40b4-8f03-514e249c6e2a, looks like it was just aborted
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```
But even after this I am able to commit T1 successfully but no updates actually take place in the DB.

cc: @bmatican

**Comment by lingamsandeep** [comment]
Thanks @Karvy-yb . Given the nature of this bug, where the customer is performing a restore to a time before the update, we do expect the row to be invisible - so the behavior in terms of data visibility itself is correct, however the fact that we are letting the transaction COMMIT without any errors is not desirable.

We'll use this bug to kill all inflight transactions when starting a PITR to avoid this issue - at a lower priority.
