### ISSUE TITLE
[Docs] Atomicity Limitations of xCluster Need to be Clearer

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#14294]
### Description

I have created this issue [in response to a conversation](https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1664344982472359?thread_ts=1664267918.003609&cid=CG0KQF0GG) with a user that was confused by the documentation below. 

Currently in our xCluster documentation we have [a section called Limitations](https://docs.yugabyte.com/preview/architecture/docdb-replication/async-replication/#limitations) that calls out the current limitations of the feature. 

In the [Transactional semantics](https://docs.yugabyte.com/preview/architecture/docdb-replication/async-replication/#transactional-semantics-10976-https-github-com-yugabyte-yugabyte-db-issues-10976) subsection we see:

"Transactions from the source are not applied atomically on the target. That is, some changes in a transaction may be visible before others."

However further down in the [Atomicity of Transactions](https://docs.yugabyte.com/preview/architecture/docdb-replication/async-replication/#atomicity-of-transactions) subsection under [Transactional guarantees](https://docs.yugabyte.com/preview/architecture/docdb-replication/async-replication/#transactional-guarantees) we see:

"This implies one can never read a partial result of a transaction on the sink cluster."

This is confusing for users as Atomicity is only guaranteed on the target side if a transaction impacts a single shard/tablet. If the transaction touches multiple shards or multiple tables, then currently atomicity across shards/tables is not guaranteed on the target side. We are addressing this as part of [Issue #10976](https://github.com/yugabyte/yugabyte-db/issues/10976) and it will be part of our upcoming release which should be available in Nov.

**Comment by lizayugabyte** [comment]
@mrajcevic01 I removed the "Atomicity of Transactions" section. And issue 10976 is already mentioned in [Transactional semantics](https://docs.yugabyte.com/preview/architecture/docdb-replication/async-replication/#transactional-semantics)
