### ISSUE TITLE
[YSQL] [PITR]: Unable to acquire lock on a particular row after PITR restore

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14291]
Jira Link: [DB-3732](https://yugabyte.atlassian.net/browse/DB-3732)
### Description

Steps followed: 

1. Create universe with pessimistic locking enabled, deadlock detection enabled and consistent restore enabled.
2. Create a database
3. Create a table with multiple rows in the database
4. Create a schedule on the created database
5. Note down time
6. Start transaction T1 and acquire FOR UPDATE lock on R1 of table.
7. Start another shell session and try to access R1 FOR UPDATE. This command will wait for T1 to complete.
8. Restore to time stamp noted in step 5.
9. Commit T1

Now if I try to acquire lock on R1 (update R1) then the command waits as if the row is locked by some transaction and then eventually times out.

**Comment by bmatican** [comment]
@Karvy-yb Was this with consistent restore enabled? Otherwise, behavior with ongoing transactions might not be well described. Also, how long does it take to timeout? And will a 2nd attempt, after that timeout, actually work?
cc @lingamsandeep

**Comment by bmatican** [comment]
@Karvy-yb can you clarify if this is still a problem? was this an issue with consistent restore only, or even without it?

**Comment by Karvy-yb** [comment]
@bmatican Let me get back to you post validating this on latest master.

**Comment by Karvy-yb** [comment]
@bmatican Unable to reproduce this issue on latest master (2.21.0.0-b70)
