### ISSUE TITLE
[docdb] Support Savepoints with xcluster transactional replication

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#14308]
Jira Link: [DB-3745](https://yugabyte.atlassian.net/browse/DB-3745)
### Description

A savepoint is a special mark inside a transaction that allows all commands that are executed after it was established to be rolled back, restoring the transaction state to what it was at the time of the savepoint.

In Yugabyte, Savepoints are implemented using sub-transactions which are either committed or rolled back depending on whether user rollsback or releases savepoint.

As part of transactional xcluster replication, the WAL records from the system.transactions are replicated from the producer to the consumer universe, however the list of aborted/committed sub-transactions is currently not propagated.

To support SAVEPOINTs, changes will be needed to propagate the list of aborted sub-transactions from the Producer->Consumer and propagate that forward to the corresponding transaction coordinator and participants as part of UpdateTransaction.

[DB-3745]: https://yugabyte.atlassian.net/browse/DB-3745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mdbridge** [comment]
backported to 2.18.1
