### ISSUE TITLE
[YSQL] Garbage collector needs to delete system catalog table

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#1430]
When a YSQL Database is dropped, all system tables that belong to that database must be removed from the sys_catalog tablet.  However, catalog_manager only removes the entries in the tablet_metadata.  As a result, the garbage collector needs to remove the actual table entries in system_catalog_tablet. That is, the tables whose ids are not listed in the tablet_metadata must be removed from the tablet.

Background
- The system tables such as "pg_class" are YugaByte implementation of the Postgres system catalogs.  Their contents are all stored in system_catalog_tablet.
- Different from system tables, the user-defined objects in the database are already dropped by catalog_manager when drop-database command is processed.

**Comment by ndeodhar** [comment]
Fixed as part of #2997. 
@jaki Please confirm.
