### ISSUE TITLE
[YCQL] Fix misleading errors when failing to insert into a unique index

### ISSUE THREAD

**Issue by lnguyen-yugabyte** [yugabyte/yugabyte-db#14317]
Jira Link: [DB-3751](https://yugabyte.atlassian.net/browse/DB-3751)
### Description

https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tablet/write_query.cc#L690-L707

Specifically 
`/ If this is an insert into a unique index and it fails to apply, report duplicate value err.`

We should check what kind of error we are getting here, and report it accordingly.

**Comment by ionthegeek** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/14163
