### ISSUE TITLE
[YSQL] Add tests and docs for partial index 

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1432]
1. Update yb_create_index tests to include tests for partial index.
2. Update CREATE INDEX api documentation. https://github.com/yugabyte/yugabyte-db/issues/3573

**Comment by m-iancu** [comment]
Both are now added. For docs see #3573, for tests there are multiple changes, for instance https://github.com/YugaByte/yugabyte-db/issues/3329.
