### ISSUE TITLE
[YSQL] "ERROR:  Invalid argument: Invalid column number 2" after adding a new column

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#14327]
Jira Link: [DB-3756](https://yugabyte.atlassian.net/browse/DB-3756)
### Description

Steps to reproduce:

1) Connect to one host, say 127.0.0.1:
```
yugabyte=# CREATE TABLE t (id int);
yugabyte=# INSERT INTO t VALUES (1), (2);
```
This populates the table caches for table "t" in TServer 1
End this connection

2) Connect to another host: ysqlsh -h 127.0.0.2
```
yugabyte=# ALTER TABLE t ADD COLUMN col1 TEXT;
```

3) Start a new connection to TServer1: ysqlsh -h 127.0.0.1
```
yugabyte=# INSERT INTO t VALUES (1);
ERROR:  Invalid argument: Invalid column number 2
yugabyte=# INSERT INTO t VALUES (1);
ERROR:  Invalid argument: Invalid column number 2
yugabyte=# INSERT INTO t VALUES (1);
ERROR:  Invalid argument: Invalid column number 2
yugabyte=# INSERT INTO t VALUES (1);
```
This is because the new connection has the latest catalog version. Hence there is no cache refresh instigated by this connection. However TServer1 does not have the latest schema version in its table cache. The cached schema version does not have the new column, and thus the above error is thrown.

4) Start another connection in some other node (127.0.0.2 or 127.0.0.3). This succeeds:
```
yugabyte=# INSERT INTO t VALUES (1);
INSERT 0 1
```

**Comment by jteplitz** [comment]
I'm currently hitting this on v2.14.3.1. Is there a workaround /  way to force a refresh of the schema cache?

**Comment by jteplitz** [comment]
I was able to force a refresh by restarting yugabyte on the impacted tablet server

**Comment by m-iancu** [comment]
Does not repro anymore in latest. Closing as fixed.

**Comment by m-iancu** [comment]
Most likely fixed by https://github.com/yugabyte/yugabyte-db/commit/7583bcc0ea272ef8742adff796b36e354f9b6767 (see also issue https://github.com/yugabyte/yugabyte-db/issues/12802).
