### ISSUE TITLE
[DocDB] flaky test: YBBackupTest.TestYSQLManualTabletSplitRangeTable and YBBackupTest.TestYSQLManualTabletSplit

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14344]
Jira Link: [DB-3771](https://yugabyte.atlassian.net/browse/DB-3771)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=YBBackupTest&fail_tag=all&name=TestYSQLManualTabletSplitRangeTable&platform=linux

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=YBBackupTest&fail_tag=all&name=TestYSQLManualTabletSplit&platform=linux

Seem to fail only in release, so I wonder if it's related to enabling LTO for yb-master, somehow.

**Comment by SrivastavaAnubhav** [comment]
It looks like this has become much less flaky after commit 894d3871150c8830741977ddb309d143994deda1.

**Comment by bmatican** [comment]
Closing for now, as per Anubhav, it's far less flaky.
