### ISSUE TITLE
[YSQL][Pessimistic Locking][Savepoints] : Unable to run the same statement again in the transaction after rollback to savepoint

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14350]
Jira Link: [DB-3776](https://yugabyte.atlassian.net/browse/DB-3776)
### Description

Steps to reproduce:

1. Create universe with `enable_deadlock_detection`, `enable_wait_queue_based_pessimistic_locking` flags enabled and `auto_promote_nonlocal_transactions_to_global` flag disabled.
2. Create a table and load multiple rows to it.
3. T1: `begin;`
4. T2: `begin;`
5. T1: `savepoint s;`
6. T1: `select * from test1 where k=1 for update;`
7. T2: `select * from test1 where k=1 for update;`
8. T1: `rollback to savepoint s;`
9. Lock is released for T2 and thus waiting command runs on T2.
10. T1: `select * from test1 where k=1 for update;`
11. T1 throws error: `ERROR:  Operation failed. Try again: Unknown transaction, could be recently aborted: 38325b1a-85ca-404d-a51b-fe66210d6365`

If we commit T2 after sometime then it also throws error: `ERROR:  Operation expired: Heartbeat: Transaction [16, 39, 72, 173, 212, 34, 71, 46, 162, 220, 79, 75, 81, 60, 119, 183] expired or aborted by a conflict: 40001`

Tried the same scenario with pessimistic locking disabled and error persists but the error message is different : `ERROR:  Operation expired: Heartbeat: Transaction [207, 143, 101, 177, 249, 94, 70, 94, 149, 21, 154, 68, 244, 33, 13, 45] expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_coordinator.cc:1557): Heartbeat: Transaction [207, 143, 101, 177, 249, 94, 70, 94, 149, 21, 154, 68, 244, 33, 13, 45] expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)]`

**Comment by pkj415** [comment]
I did some debugging and the reason for this is that a false deadlock is detected between T1 and T2 which aborts T1.

The fix would be to remove the wait-for relationship from T2->T1 once T2 is unblocked after `rollback to savepoint s;` is executed in T1.

cc @robertsami
