### ISSUE TITLE
[DocDB] flaky test: YBBackupTest.TestYSQLTabletSplitRangeUniqueIndexOnHiddenColumn

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14365]
Jira Link: [DB-3788](https://yugabyte.atlassian.net/browse/DB-3788)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&buckets=20&build_type=all&class=YBBackupTest&fail_tag=all&name=TestYSQLTabletSplitRangeUniqueIndexOnHiddenColumn&platform=linux

Traces back to https://github.com/yugabyte/yugabyte-db/commit/7583bcc0ea272ef8742adff796b36e354f9b6767

**Comment by sanketkedia** [comment]
Discussed with @yifanguan. In fact, my commit has helped uncover an edge case that wasn't getting hit before and is now hit very frequently. From Yifan's notes:

> The edge case is related to null value.
> In this testcase:
> I created an index with partition bounds as:
>   // tablet-1 boundaries: [ "", (null, <ybctid-1>) )
>   // tablet-2 boundaries: [ (null, <ybctid-1>), (null, <ybctid-2>) )
>   // tablet-3 boundaries: [ (null, <ybctid-2>), "" )
> However, when decoding these partition bounds into postgres value, I didn’t handle null value…
> Also, our current syntax doesn’t allow specify null values for split points as well…
> yugabyte=# create table tbl(k int, primary key (k asc)) split at values ((null));
> ERROR:  cannot specify NULL in range bound

Before this commit, ysql dump of backup used to pick up the stale cache more often and this stale cache had partitions corresponding to pre-split values which works fine. After this commit, it picks up the latest cache corresponding to post-split more often which has nulls thus we see it more often now.

**Comment by yifanguan** [comment]
Issue resolved by commit: 8eac4e461e9d1513811c2046268d99df780c5d1a.
Backported to branch 2.16 as well.
Branch 2.14 doesn't have the original commit: b16653e05c0a625fd5771a8255dc9a7953a26f4b, so I didn't backport to it.
