### ISSUE TITLE
[YSQL] redundant memset call in ybcBeginScan

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#14397]
Jira Link: [DB-3817](https://yugabyte.atlassian.net/browse/DB-3817)
### Description

```
    YbScanDesc ybScan = (YbScanDesc) palloc0(sizeof(YbScanDescData));
    memset(ybScan->keys, 0, sizeof(ybScan->keys));
```
The call to `memset` is not needed since the YbScanDescData struct is cleared by the statement above it.

**Comment by sushantrmishra** [comment]
Not clear which memset call is being referred to.
