### ISSUE TITLE
Jedis driver should be able to round-robin between a list of nodes

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#144]
Currently, the Jedis driver can only talk to one ip address. We need to enhance this so that:
- we can specify a list of ip addresses, a list of hostnames or a kubernetes-style service DNS name
- the Jedis driver should round-robin between the various hosts
- upon error, it should refresh this list
- periodically in the background, it should refresh this list - so that node adds and removals can be discovered

**Comment by m-iancu** [comment]
Fixed by eb2a6d37c0b81382166ff7a84f7270069a88b3b8 (and corresponding Jedis driver diff https://github.com/YugaByte/jedis/commit/56693ebe877e237aec2acd78fb34099bdbc9ab1b)
