### ISSUE TITLE
[DocDB] [xCluster] Index operations are not working as expected at Target side.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#14409]
Jira Link: [DB-3828](https://yugabyte.atlassian.net/browse/DB-3828)
### Description

**Version**: `2.15.4.0-b77`

**Steps**:
1. Create database and table at Source and Target sides.
create database demo;
\c demo;
create table test1(id int primary key, name text);
2. Setup replication
3. Insert 20 rows at source side and validate data at both sides.
4. Alter table at both sides.
 Alter table test1 add column age int;
5. Create partial index at target side.
  create index idx_1 on test1(age) where age < 15;
6. Validate the data at target.
7. Create partial index at target side
   create index idx_2 on test1(age) > 25;
8. Create unique index at target side.
   create unique index idx_3 on test1(name);
9. Insert 20 more rows at source side(name should be same(duplicate) in all rows and id should be in incremental way)
10. Validate data at target side
    a. select * from test1 where id>25;
    b. select count(*) from test1 where name='inserted same name';
    c. select * from test1;
    
**Actual**:
Step#6: Works as expected;
After Step#10:
    a. Returns empty results;
    b. Returns 1 row
    c: Returns all replicated rows
    
**Expected**:
a. It should returns the all matching rows.
b and c: Do we need to allow user to create unique indexes at Target side ? As it is not known what type of data is being inserted by user at source side. Here in above scenario user inserted same(duplicate) name and it collides with unique index but there is no error at target side.

**Comment by nspiegelberg** [comment]
We don't have additional Index Table support outside of the existing functionality.  Admins still need to create the Index on the Source, B/R, then create the replication stream.  Having better flexibility for Index Support is part of #13488

**Comment by lingamsandeep** [comment]
This was fixed by https://github.com/yugabyte/yugabyte-db/commit/da128595cf2d63805c1a7edd45166e465a67c132
