### ISSUE TITLE
[YCQL] Aggregate over 7 crores records query timeout 

### ISSUE THREAD

**Issue by sibitha-bijesh** [yugabyte/yugabyte-db#14405]
Jira Link: [DB-3825](https://yugabyte.atlassian.net/browse/DB-3825)
### Description

We have a table with 7 crores records.  When doing aggregate count result in timeout .  

** We have indexed the table fields and analyze report give index scan.  

select count(*) from tn table .  

Could you please suggest a solution

**Comment by ddorian** [comment]
> with 7 crores records

1 crores = 10million

> select count(*) from tn table .

What is the exact error that you get? Can you paste the results of `analyze select count(*) from tn table;` ?

For distributed counts, you should probably use something like https://support.yugabyte.com/hc/en-us/articles/360060685992-How-to-run-count-query-in-Yugabyte-DB-

**Comment by sibitha-bijesh** [comment]
Aggregate  (cost=136.50..136.51 rows=1 width=32)
  ->  Subquery Scan on "_root.base"  (cost=0.00..124.00 rows=1000 width=20)
        ->  Index Only Scan using tn_timestamp_idx on tn  (cost=0.00..114.00 rows=1000 width=200)

**Comment by sibitha-bijesh** [comment]
@ddorian 
The query is timeout after sometime.  So the frontend hanging...

**Comment by sibitha-bijesh** [comment]
The approaches mentioned in the link you shared doesn't work in our case since we have to apply the filters in the select count(*) queries.

**Comment by ddorian** [comment]
> The approaches mentioned in the link you shared doesn't work in our case since we have to apply the filters in the select count(*) queries.

@sibitha-bijesh what do you mean? Can you write your full query with filters?

**Comment by sibitha-bijesh** [comment]
@ddorian 
```
select count(*) from tn WHERE  
          (
            (
              ("public"."tn"."sent_account_id") = (('accountId') :: text)
            )
            OR (
              ("public"."tn"."receiver_account_id") = (('accountId') :: text)
            )
          ) 
          ```

**Comment by ddorian** [comment]
@sibitha-bijesh is that the full query? I'm curious why it's using an ` -> Index Only Scan using tn_timestamp_idx on tn (cost=0.00..114.00 rows=1000 width=200)` ? Can you paste the full schema and full query?

**Comment by sibitha-bijesh** [comment]
```
CREATE TABLE tn (
  tn_hash TEXT NOT NULL,  
  tn_timestamp NUMERIC(20, 0) NOT NULL, 
  sent_account_id TEXT NOT NULL,   
  receiver_account_id TEXT NOT NULL,   
  PRIMARY KEY (tn_hash)
);


CREATE INDEX tn_sent_account_id_idx ON transactions(sent_account_id);
CREATE INDEX tn_receiver_account_id_idx ON tn (receiver_account_id);
CREATE INDEX tn_timestamp_idx ON tn(tn_timestamp DESC);  



```

**Comment by sibitha-bijesh** [comment]
@ddorian

**Comment by ddorian** [comment]
@sibitha-bijesh and the full query please?

**Comment by sibitha-bijesh** [comment]
@ddorian 

```
select count(*) from tn WHERE  
          (
            (
              ("public"."tn"."sent_account_id") = (('accountId') :: text)
            )
            OR (
              ("public"."tn"."receiver_account_id") = (('accountId') :: text)
            )
          ) 
          ```

**Comment by sibitha-bijesh** [comment]
@ddorian any help on this. 
We have swithed to yugabyte from otherDB, for performance enhancement. But we couldn't still provide a pagination due to the aggregate queries issue. The API for getting count will be timeout after long time of processing.   We have to provide number based pagination (Offset based ).  Please help me to sort out this issue

**Comment by ddorian** [comment]
Note that you can do the distributed-count using your query above,  see https://docs.yugabyte.com/preview/api/ycql/expr_fcall/#parallel-full-table-scans.


> We have to provide number based pagination (Offset based ).

Can you explain the query for this? Note that offset pagination is hard to scale, it's better to do range-query pagination https://dev.to/yugabyte/efficient-pagination-in-yugabytedb-postgresql-4h5a


> -> Index Only Scan using tn_timestamp_idx on tn (cost=0.00..114.00 rows=1000 width=200)

I still don't understand why it's using this index. Are you also filtering on the timestamp? cc @FranckPachot

**Comment by ddorian** [comment]
Closing as no response from user.
