### ISSUE TITLE
[Docs] YugabyteDB tserver configuration xcluster gflag

### ISSUE THREAD

**Issue by shah-naitik** [yugabyte/yugabyte-db#14412]
### Description

There seems to be no documentation reference for this tserver xcluster RPC gflag svc_queue_length_default
I see a github issue [here](https://github.com/yugabyte/yugabyte-db/issues/11781) but unable to find it within the tserver configuration docs. 
Could someone from the Docs team pls verify and add this in our docs? (https://docs.yugabyte.com/stable/reference/configuration/yb-tserver/)
We are working on a customer deliverable runbook and xCluster replication setup and documentation reference for the gflag would be helpful.

**Comment by ronpcohen** [comment]
According to https://github.com/yugabyte/yugabyte-db/issues/11781. the correct xCluster RPC flag is now a new flag, xcluster_svc_queue_size and is set to 5000.
