### ISSUE TITLE
[YugabyteD] [QA] [Enhancement] Give option to change cert generation path

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14427]
### Description

The certs are automatically placed in path <base_dir>/generated_certs/<hostname>

`Server node certs path     : Certs can be found at: /Users/mzafar/var/generated_certs/<hostname> `

We can give an option to change this path

**Comment by nchandrappa** [comment]
This is working as designed.

**Comment by zlareb1-yb** [comment]
As discussed with @nchandrappa in call today this won't be fixed as this is as per design. Closing this
