### ISSUE TITLE
[Docs] ConnectionString with multiple node cluster

### ISSUE THREAD

**Issue by alidehghan** [yugabyte/yugabyte-db#14430]
### Description

In every parts of documents and sample, connectionString provided with just one hostname while in real world applications there are multiple tserver nodes available and connecting to just one server of them risks high-availability, my question is how I can specify a list of tserver nodes (such schema defined at MONGODB) in which if one server is down, connect to next one?

**Comment by ddorian** [comment]
@alidehghan what language are you using in your client?

**Comment by alidehghan** [comment]
golang with pg-go orm

**Comment by ddorian** [comment]
You can use our smart driver https://docs.yugabyte.com/preview/reference/drivers/go/yb-pgx-reference/

**Comment by ddorian** [comment]
For multiple hosts in connection string, you can use something like explained here: https://paquier.xyz/postgresql-2/postgres-10-multi-host-connstr/

**Comment by alidehghan** [comment]
thanks for your reply and answer, but what is your recommendation for c#.net?

**Comment by ddorian** [comment]
We don't yet have a smart driver for c# , you can use the normal driver https://docs.yugabyte.com/preview/reference/drivers/csharp/postgres-npgsql-reference/

The multi-host connection string will still work. Just that it will try them in sequential order.
So either put a load balancer in front, or randomize the list of hosts before every new connection.

**Comment by ddorian** [comment]
Smart driver for C# has been added in https://docs.yugabyte.com/preview/reference/drivers/csharp/yb-npgsql-reference/.
