### ISSUE TITLE
[YugabyteD] [QA] Can't restart yugabyted if yugabyted process was killed because tserver, master are still running

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14435]
### Description

Can't restart yugabyted if yugabyted process was killed because tserver, master are still running

```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ps -ef | grep yugabyted
  503 44764     1   0  6:11PM ??         0:00.09 /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python ./bin/yugabyted start --base_dir=/Users/mzafar/ybd/test/
  503 44831 89824   0  6:13PM ttys027    0:00.00 grep yugabyted
```

Kill yugbabyted process:
`MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ kill -9 44764
`

Try starting yugabyted process again
```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted start --base_dir=/Users/mzafar/ybd/test/
WARNING: UI disabled - Java 1.8 or higher is required.
Starting yugabyted...
tserver is already running... Is there an existing yugabyted process?
Shutting down...
```

Can the yugabyted connect to existing tserver, master?

**Comment by zlareb1-yb** [comment]
1. Stopping Yugabyted doesn't kill stop the tserver, master processes
2. Destroy of the cluster also doesn't kill the tserver, master processes. 
3. If we try to start the destroyed cluster again. We would not be able to do so because the address:port will already be in use.

**Comment by gargsans-yb** [comment]
Using `kill -9` to kill a process is not the right way to go. `-9` is the `SIGKILL` signal which is immediate termination and cannot be blocked or trapped. SIGKILL doesn't termiate the processes gracefully. 
Using `-15` or the `SIGTERM` signal is the right kill signal. This terminates the processes gracefully, so the child processes of the process will also be terminated.
