### ISSUE TITLE
[DOCDB]  Failure testcase CompactionAfterDBDrop

### ISSUE THREAD

**Issue by sureshdash2022-yb** [yugabyte/yugabyte-db#14443]
Jira Link: [DB-3845](https://yugabyte.atlassian.net/browse/DB-3845)
During analysis we found after diff D19696 landed into master CompactionAfterDBDrop testcase is consistently failing.

**Comment by rthallamko3** [comment]
PgMiniTest.CompactionAfterDBDrop is failing? @sureshdash2022-yb , Are you planning to fix this?

**Comment by sureshdash2022-yb** [comment]
Hi @rthallamko3 i have fixed the issue as part of https://phabricator.dev.yugabyte.com/D20149, did still see the failure?

**Comment by sureshdash2022-yb** [comment]
Hi @rthallamko3 , just now in the latest master code i have run the same testcase 50 times, it's passing 

git_diff_sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
env_vars_sha256=70584e660e6a0c0e86076f55414a1085c1b873eafb73a0df0e8ab05446ae7bc7
[build_postgres.py:845] 2022-10-18 05:31:12,655 INFO: PostgreSQL is already up-to-date in directory /home/sureshdash_yb/code/yugabyte-db-master/build/debug-clang14-dynamic-ninja/postgres_build, skipping the 'make' step.
[5/5] cd /home/sureshdash_yb/code/yugabyte-db-master/build/debug-clang14-dynamic-ninja/...sureshdash_yb/code/yugabyte-db-master/build/debug-clang14-dynamic-ninja/auto_flags.json
[gen_auto_flags_json.py:88] 2022-10-18 05:31:12,885 INFO: Generated AutoFlags JSON in 0.1 sec

real	0m0.934s
user	0m0.933s
sys	0m0.381s
[2022-10-18T05:31:12 yb_build.sh:526 run_cxx_build] C++ build finished with exit code 0 (build type: debug, compiler: clang14). Timing information is available above.
+ /home/sureshdash_yb/code/yugabyte-db-master/bin/repeat_unit_test.sh debug pg_mini-test --build-type debug --num-iter 50
[2022-10-18T05:31:12 repeat_unit_test.sh:389 main] Using test parallelism of 4 by default (build type: debug)
[2022-10-18T05:31:12 repeat_unit_test.sh:395 main] YB_COMPILER_TYPE env variable was set to 'clang14' by the caller.
[2022-10-18T05:31:12 repeat_unit_test.sh:397 main] gtest_filter is PgMiniTest.CompactionAfterDBDrop (from the YB_GTEST_FILTER env var)
[2022-10-18T05:31:12 repeat_unit_test.sh:403 main] Saving repeated test execution logs to: /home/sureshdash_yb/logs/repeat_unit_test/pg_mini-test/PgMiniTest.CompactionAfterDBDrop/2022-10-18T05_31_12
PASSED: iteration 3, 78 sec
PASSED: iteration 1, 79 sec
PASSED: iteration 2, 79 sec
PASSED: iteration 4, 80 sec
PASSED: iteration 5, 78 sec
PASSED: iteration 8, 78 sec
PASSED: iteration 7, 79 sec
...
PASSED: iteration 44, 80 sec
PASSED: iteration 45, 79 sec
PASSED: iteration 46, 80 sec
PASSED: iteration 47, 79 sec
PASSED: iteration 48, 79 sec
PASSED: iteration 49, 77 sec
PASSED: iteration 50, 79 sec

==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : debug
C/C++ compiler                   : clang14
Build architecture               : x86_64
Build directory                  : /home/sureshdash_yb/code/yugabyte-db-master/build/debug-clang14-dynamic-ninja
Third-party dir                  : /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235442-8f0b4a580c-centos7-x86_64-clang14
Targets                          : pgwrapper_pg_mini-test
C++ compilation time             : 1 seconds
C++ (one test program) time      : 1026 seconds
------------------------------------------------------------------------------------------
[sureshdash_yb@dev-server-yb-sureshdash-2 yugabyte-db-master]$
