### ISSUE TITLE
[DocDB] flaky test: MetricsTest.TestStreamLevelAggregation

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14447]
Jira Link: [DB-3848](https://yugabyte.atlassian.net/browse/DB-3848)
### Description

[MetricsTest.TestStreamLevelAggregation](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=MetricsTest&fail_tag=all&name=TestStreamLevelAggregation&platform=linux)

**Comment by rthallamko3** [comment]
@Sumukh-Phalgaonkar , Can we resolve this defect now?

**Comment by Sumukh-Phalgaonkar** [comment]
Yes, the issue has been fixed.
