### ISSUE TITLE
[DocDB] flaky test: CDCSDKYsqlTest.TestTransactionInsertAfterTabletSplit

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14448]
Jira Link: [DB-3849](https://yugabyte.atlassian.net/browse/DB-3849)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestTransactionInsertAfterTabletSplit&platform=linux

**Comment by adithya-yb** [comment]
Now fixed with: https://phabricator.dev.yugabyte.com/D20165
