### ISSUE TITLE
[DocDB] flaky test: PgIndexBackfillTest.Permissions

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14454]
Jira Link: [DB-3854](https://yugabyte.atlassian.net/browse/DB-3854)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&buckets=30&build_type=all&class=PgIndexBackfillTest&fail_tag=all&name=Permissions&platform=linux

seems to point to https://github.com/yugabyte/yugabyte-db/commit/2e1650427649c324ef470a95decf8e7839df802a

**Comment by joe-maley** [comment]
Leaving this open until I've verified that the flakiness has been fixed on the detective stability report.
