### ISSUE TITLE
[YSQL] Optimize for index scan for colocated database

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#14458]
Jira Link: [DB-3858](https://yugabyte.atlassian.net/browse/DB-3858)
### Description

For index scan we make RPC call to the docDB for index scan and then for returned rows from index scan we make RPC call to get the full row from the main table. 
For colocated database, we should be able to perform the index scan and main table scan under one RPC.

```
create table index_test (h int, r int, v1 int, v2 int);
create index on index_test (v1);
```

explain (analyze, rpc, docdb) select * from index_test where v1 = 1;
                                                           QUERY PLAN

--------------------------------------------------------------------------------------------------------------
------------------
 Index Scan using index_test_v1_idx on index_test  (cost=0.00..5.22 rows=10 width=16) (actual time=1.865..1.86
7 rows=1 loops=1)
   Index Cond: (v1 = 1)
   Read RPC: 1
   Read RPC Wait Time: 1.000 ms
   Table Read RPC: 1
   Table Read RPC Wait Time: 0.000 ms
   DocDB Scanned Index Rows: 1
   DocDB Scanned Table Rows: 1
 Planning Time: 3.213 ms
 Execution Time: 1.983 ms
 Total Read RPC Wait Time: 1.000 ms
 DocDB Scanned Rows: 2
 Peak Memory Usage: 0 kB
(13 rows)

**Comment by karthik-ramanathan-3006** [comment]
Fixed as part of #16294
