### ISSUE TITLE
[YW]: Wrong Health Check Updated time.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#1445]
The universe was created ~1 hour ago (at 2:18 PM, now 3:30 PM), but YW shows that the health-check was updated 10 hours ago. See the screenshot.
<img width="1332" alt="Screenshot 2019-05-27 at 15 26 10" src="https://user-images.githubusercontent.com/31254529/58420630-78b3a680-8096-11e9-84fa-9cf0af08629b.png">

**Comment by OlegLoginov** [comment]
![Screenshot 2019-05-27 at 15 26 10](https://user-images.githubusercontent.com/31254529/58420673-997bfc00-8096-11e9-946a-279e3c71a922.png)

**Comment by yb-andrew** [comment]
@sunilsutarDCE Can you check if this is still an issue? Should be timezone related.

**Comment by sunilsutarDCE** [comment]
@yb-andrew : It looks like it is working . Whenever health check happened , its shows correctly in overview tab .
<img width="1423" alt="Screenshot 2021-02-17 at 1 51 33 PM" src="https://user-images.githubusercontent.com/39611171/108186033-f05f1a00-7132-11eb-8229-cb5860c4db02.png">
<img width="1423" alt="Screenshot 2021-02-17 at 2 05 03 PM" src="https://user-images.githubusercontent.com/39611171/108186049-f3f2a100-7132-11eb-8c51-7c07dae8b751.png">

**Comment by sunilsutarDCE** [comment]
This issue looks fixed .
