### ISSUE TITLE
[DocDB] Metric 'is_load_balancing_enabled' is boolean, should be numeric/integer 64

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#14469]
Jira Link: [DB-3868](https://yugabyte.atlassian.net/browse/DB-3868)
### Description

Yugabyte version: 192.168.66.80:9000   2.15.2.0        87         RELEASE    07 Sep 2022 15:52:16 UTC f7228331f0838e45f85c14f6591d167124eb5db7

Recently a statistic for the type cluster a value is added:
```
    {
        "type": "cluster",
        "id": "yb.cluster",
        "attributes": {},
        "metrics": [
            {
                "name": "is_load_balancing_enabled",
                "value": false
            },
            {
                "name": "num_tablet_servers_dead",
                "value": 0
            },
            {
                "name": "num_tablet_servers_live",
                "value": 0
            }
        ]
    }
```
The problem with it is that the 'is_load_balancing_enabled' statistic is a boolean, while all other name/value metrics in YugabyteDB are signed 64 bit integers. 
Please change this statistic to 0=false and 1=true, like for example 'is_raft_leader'.

**Comment by tedyu** [comment]
cc @msun07

**Comment by msun07** [comment]
This metric has already changed to numeric, https://phabricator.dev.yugabyte.com/D18900. @tedyu

**Comment by msun07** [comment]
https://yugabyte.atlassian.net/browse/DB-3153 @fritshoogland-yugabyte

**Comment by bmatican** [comment]
Done in 9a1f56df4e1296ff04b94be4ecd1f8467dc7d4e5, as per Mingda above
