### ISSUE TITLE
[YSQL] Add SQL RPCs to tserver utilz page

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1446]

**Comment by WesleyW** [comment]
Closed by fa64ee7409fb829830ddabdc5daf557ee56bea89

**Comment by WesleyW** [comment]
closed by fa64ee7409fb829830ddabdc5daf557ee56bea89

**Comment by bmatican** [comment]
Opening this back up. @WesleyW can we follow up on this with 2 small things:
- we didn't actually add the button in /utilz to point to the /rpcz, like the other 3 (tserver/cassandra/redis)
- let's also rename cassandra->ycql and redis->yedis

cc @kmuthukk

**Comment by WesleyW** [comment]
<img width="2900" alt="Screen Shot 2019-06-27 at 12 21 38 PM" src="https://user-images.githubusercontent.com/2791412/60294439-34563900-98d6-11e9-8f57-2e5cab9c59f1.png">
