### ISSUE TITLE
[YSQL] Index scan should use consistent read snapshot for operations within a SQL statement

### ISSUE THREAD

**Issue by robertpang** [yugabyte/yugabyte-db#1447]
Jira Link: [DB-2597](https://yugabyte.atlassian.net/browse/DB-2597)
Related to commit dd31dd7, the index scan s use consistent read snapshot for operations like how the foreign scan path uses it.

**Comment by m-iancu** [comment]
This issue is obsolete this has been fixed in an old release. Closing.
