### ISSUE TITLE
[DocDB] yb_build.sh fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by jteplitz** [yugabyte/yugabyte-db#14484]
Jira Link: [DB-3878](https://yugabyte.atlassian.net/browse/DB-3878)
### Description

**Overview**

When following the steps outlined [here](https://docs.yugabyte.com/preview/contribute/core-database/build-from-src-ubuntu/) to build from source on Ubuntu, the build script downloads the dependencies for almalinux and then fails.

**Steps to reproduce**

These steps are taken directly from the docs:
1. Install prerequisites
```
sudo apt-get update
sudo apt-get install uuid-dev libbz2-dev libreadline-dev maven ninja-build \
                     cmake curl rsync python3-pip python3-venv zip autoconf libtool \
                     pkg-config libssl1.0-dev libicu-dev bison flex \
                     libncurses5-dev
```

Clone the repo and run `./yb_build.sh release`

**Results**

Initially the build scripts failed to find my C compiler:
```-- Check for working C compiler: /opt/yugabyte-db/build-support/compiler-wrappers/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/opt/yugabyte-db/build-support/compiler-wrappers/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /opt/yugabyte-db/build/release-clang12-linuxbrew-dynamic-ninja/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_1cab4 && [1/2] Building C object CMakeFiles/cmTC_1cab4.dir/testCCompiler.c.o
    FAILED: CMakeFiles/cmTC_1cab4.dir/testCCompiler.c.o
    /opt/yugabyte-db/build-support/compiler-wrappers/cc    -o CMakeFiles/cmTC_1cab4.dir/testCCompiler.c.o   -c testCCompiler.c
    /opt/yugabyte-db/build-support/compiler-wrappers/../common-build-env.sh: line 1102: cc_executable: unbound variable
    ninja: build stopped: subcommand failed.
```
Despite clang and gcc being in `/usr/bin`
```
root@208d3277a61c:/opt/yugabyte-db# which clang
/usr/bin/clang
root@208d3277a61c:/opt/yugabyte-db# which gcc
/usr/bin/gcc
```
After explicitly pointing yb_build at clang12, I get this error with boost:
```
root@208d3277a61c:/opt/yugabyte-db#  ./yb_build.sh release --compiler-type clang12
...
-- Could NOT find Threads (missing: Threads_FOUND)
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: thread) (found version "1.78.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  cmake_modules/YugabyteFindThirdParty.cmake:273 (find_package)
  CMakeLists.txt:698 (include)


-- Configuring incomplete, errors occurred!
See also "/opt/yugabyte-db/build/release-clang12-linuxbrew-dynamic-ninja/CMakeFiles/CMakeOutput.log".
See also "/opt/yugabyte-db/build/release-clang12-linuxbrew-dynamic-ninja/CMakeFiles/CMakeError.log".

==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : release
C/C++ compiler                   : clang12
Build architecture               : x86_64
Build directory                  : /opt/yugabyte-db/build/release-clang12-linuxbrew-dynamic-ninja
Third-party dir                  : /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew
Linuxbrew dir                    : /opt/yb-build/brew/linuxbrew-20181203T161736v9
Exit code                        : 1
------------------------------------------------------------------------------------------
```

The third-party dir line is suspicious. Why did the script download the almalinux archive?

**Comment by jteplitz** [comment]
I was able to workaround this by disabling linux brew. Specifically this command is working for me `YB_USE_LINUXBREW=0 ./yb_build.sh --compiler-type clang12 release`

**Comment by ddorian** [comment]
cc @svarnau

**Comment by ddorian** [comment]
Closing as fixed in https://github.com/yugabyte/yugabyte-db/issues/14484#issuecomment-1280074793

**Comment by jteplitz** [comment]
@ddorian Does that mean `YB_USE_LINUXBREW=0 ./yb_build.sh --compiler-type clang12 release` is the recommended way to build on Ubuntu? And if so, can we re-open this as a docs issue? The documentation specifically says to run `./yb_build.sh release`, which does not work. So I don't think this is really "fixed".

**Comment by ddorian** [comment]
> The documentation specifically says to run ./yb_build.sh release, which does not work. So I don't think this is really "fixed".

This has worked for me on ubuntu 18.04

my guess is you're using a new ubuntu os

And most developers are on CentOS :

>  CentOS 7 is the recommended Linux development and production platform for YugabyteDB. 

cc @svarnau

**Comment by svarnau** [comment]
We are currently using clang14 on ubuntu20.04. The OS/compiler combinations we are verifying can be found in ./jenkins_jobs.yml file

**Comment by mbautin** [comment]
@jteplitz thanks for reporting this issue!
@svarnau @ddorian: please take a look at https://github.com/yugabyte/yugabyte-db/pull/14602/files.

**Comment by ddorian** [comment]
Closing as fixed by https://github.com/yugabyte/yugabyte-db/pull/14602
