### ISSUE TITLE
[DocDB] Docker Swarm Sample

### ISSUE THREAD

**Issue by alidehghan** [yugabyte/yugabyte-db#14481]
Jira Link: [DB-3877](https://yugabyte.atlassian.net/browse/DB-3877)
### Description

I am using yugabytedb in docker swarm with 10-node cluster, but nowhere in the documents I found an official document or sample to do this. may you please provide one? Also I donno how to access dashboard in such situation. I exposed port 7000 on one tserver node but could see the dashboard.

**Comment by ddorian** [comment]
Hi @alidehghan 

> Also I donno how to access dashboard in such situation. I exposed port 7000 on one tserver node but could see the dashboard.

7000 is for yb-master. 9000 is for yb-tserver. See more on default ports page https://docs.yugabyte.com/preview/reference/configuration/default-ports/#admin-web-server

**Comment by alidehghan** [comment]
thanks for your reply, 

yes, my bad, I meant 9000 on yserver and 7000 on master. Actually I exposed these 7000 on one master node and 9000 on one tserver, but nothing replied at that node on specified port (when curl http://localhost:7000, **connection refused** responded).

I am using docker swarm

**Comment by soletan** [comment]
Just wildly guessing: [yugabytedb reference](https://docs.yugabyte.com/preview/reference/configuration/yugabyted/#start) is stating option **--ui** being **false** by default. Have you adjusted that?

**Comment by soletan** [comment]
I doubt the docker support is reliable at all. Trying to set up cluster myself, but yugabyted in docker container e.g. is complaining about missing ntp, though it's a just warning ... but after that the container keeps crashing with exit code 137 which is OOM. My docker host has 4GB RAM which is twice the minimum as given in hardware requirements and the host isn't doing anything else, consuming just 240 MB RAM. 

In addition, the advertise-address I'm providing is an address available at host level. When using listen option in addition, yugabyted is stating "listen" option to be deprecated for "listen" and "advertise-address" "are the same", which is expressing a limitation on behalf of yugabyte. It definitely can't bind itself to the host's IP when running in container. If that IP is actually about _advertising_ itself e.g. in a Raft consensus protocol, "listening to an IP" and "advertising my IP to the cluster" are two different things. yugabyted is obviously disagreeing on this which is just feeding my doubts on yugabyte failing to support containers and their isolations properly.

Have you tried using host network driver to prevent the bridging?

**Comment by alidehghan** [comment]
I am using docker swarm and using overlay network

**Comment by ddorian** [comment]
Note that `-ui` is a different thing from what I said about port 9000,7000

> yugabyted also provides a UI similar to the YugabyteDB Anywhere UI, with a data placement map and metrics dashboard.
> https://dev.to/yugabyte/beta-yugabyted-gui-3i4m


> I doubt the docker support is reliable at all. Trying to set up cluster myself, but yugabyted in docker container e.g. is complaining about missing ntp, though it's a just warning ... but after that the container keeps crashing with exit code 137 which is OOM. My docker host has 4GB RAM which is twice the minimum as given in hardware requirements and the host isn't doing anything else, consuming just 240 MB RAM.

Maybe this is getting the hardware from your host and trying to apply it to your container? Can you create an issue regarding this?
Also, in production you should be using `yb-tserver` & `yb-master` binaries directly.

> UPDATE 2: That "binding every thing to the advertisement address" is a pretty limited approach. I'm trying to have a private network for the server-to-server communication and while trying to expose client-facing ports on the public NIC of either node ... ain't working with this "one IP is used for everything approach" ...

See https://www.yugabyte.com/blog/yugabyte-db-1-1-new-feature-public-ips-to-simplify-multi-or-hybrid-cloud-database-deployments/
And https://docs.yugabyte.com/preview/reference/configuration/yb-tserver/#pgsql-proxy-bind-address

**Comment by soletan** [comment]
> Also, in production you should be using yb-tserver & yb-master binaries directly.

Yeah, that's what I figured out myself shortly after posting this. Will focus on that one ...

**Comment by ddorian** [comment]
Closing as completed.
