### ISSUE TITLE
[Docs] Yb-Voyager: Unsupported Features and Data Modeling sub-sections should be moved to Migration Steps section

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#14499]
### Description

We call out **[Unsupported Features](https://docs.yugabyte.com/preview/migrate/yb-voyager-cli/#unsupported-features)** and **[Data Modeling](https://docs.yugabyte.com/preview/migrate/yb-voyager-cli/#data-modeling)** sub-sections for YB-Voyager at the very end of the **[yb-Voyager CLI](https://docs.yugabyte.com/preview/migrate/yb-voyager-cli/)** section of the YugabyteDB Voyager documentation. 

This is not very intuitive to find as it has little to do with the CLI itself. As a user I would look for this information in a separate section, or under **[Migration Steps](https://docs.yugabyte.com/preview/migrate/migrate-steps/)** (If I had to choose an existing section).

**Comment by aishwarya24** [comment]
I have moved Unsupported Features to [Troubleshoot](https://docs.yugabyte.com/preview/migrate/troubleshoot/#unsupported-features) . Will move the data modelling section to a more visible place.
