### ISSUE TITLE
[DocDB] flaky test: CDCSDKYsqlTest.TestAddMultipleTableToNamespaceWithActiveStream

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14494]
Jira Link: [DB-3885](https://yugabyte.atlassian.net/browse/DB-3885)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&buckets=20&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestAddMultipleTableToNamespaceWithActiveStream&platform=linux

**Comment by adithya-yb** [comment]
Fixed with commit: https://phabricator.dev.yugabyte.com/D20174
