### ISSUE TITLE
[backup] scp xxhsum_x86 to yugabyte/bin/xxhash failed on backup creation with nemesis and without

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#14492]
Jira Link: [DB-3884](https://yugabyte.atlassian.net/browse/DB-3884)
### Description

Env:
- RF=3 3 nodes universe
- platform/cluster version:  2.17.1.0-b46

Steps:
1. creates sql 10 tables and fill it with data (any tables with any data) till tables will be 2gb each - clearly it needs for longer backup creation time, not for some special case
2. Create backup:
2.1. start random nemesis in background
2.2. wait for 3 min
2.3. create backup from UI with 30 parallelism with nemesis on background
3. When task is failed we try to create once again without nemesis in background

And creation also failed with error on UI:
```
Failed to execute task {"sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"8d207bb0-4213-412d-89df-8c60e6633e1d","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisS..., hit error:

{"error": "Exception: Command '['scp', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/data/keys/9a40df64-ba88-4a91-8c93-2abc27eb751b/yb-dev-aws-2.pem', '-P', '22', '-q', '/usr/bin/xxhsum_x86', 'yugabyte@172.151.16.122:/home/yugabyte/bin/xxhash']' returned non-zero exit status 1."}.
```

In logs it shows 
[partial_application.log](https://github.com/yugabyte/yugabyte-db/files/9801732/partial_application.log)

All details can be found here: http://stress.dev.yugabyte.com/stress_test/c1b60964-32fe-4b4f-a62b-bc57d59d6325
Attachments -> Universe logs - all universe log
Attachments -> Universe logs -> portal - full application.log

**Comment by Vars-07** [comment]
Corresponding change was reverted [here](https://github.com/yugabyte/yugabyte-db/commit/542db794db61f202d65793defebb8d2240dc231f). Closing the issue.
