### ISSUE TITLE
Optimize master leader handling of system queries for new connections

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1450]

**Comment by bmatican** [comment]
We seem to have 2 types of issues here:
- New CQL connections need to execute system queries (to our `yql_*_vtable` virtual tables), such as `select * from system.peers` or from `system.partition`. These are currently actually doing work, of looping through `TSDescriptor` data and `TabletInfo` data.
- The `YBClient` / `MetaCache` also query the master, through `GetTabletLocations`, per tablet. This also does work of going over the `TabletInfo` objects and building responses for the queries. This is an issue on just starting with an empty cold cache, as well as, probably during partition events, both likely triggering a storm of requests to the master for all the tablets that require updates.
