### ISSUE TITLE
[Docs] Make note so that users are aware YB-Voyager does not migrate over USER or GRANT statements

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#14500]
### Description

`USER` and `GRANT` are not supported in PG to YB migration by voyager. Users should be made aware of this in the [Migration Steps](https://docs.yugabyte.com/preview/migrate/migrate-steps/) as the YB-voyager user will be required to recreate the users manually, or using something like `pgdumpall --roles-only`. 

It might make sense to add this into the [unsupported features](https://github.com/yugabyte/yugabyte-db/issues/14499) section of the [YugabyteDB Voyager](https://docs.yugabyte.com/preview/migrate/) documentation as well. I have filed a [separate GH issue](https://github.com/yugabyte/yugabyte-db/issues/14499) to get this section moved over to the [Migration Steps](https://docs.yugabyte.com/preview/migrate/migrate-steps/) section.

**Comment by aishwarya24** [comment]
This has been called out - https://github.com/yugabyte/yugabyte-db/commit/b609d3f4d71231bc4e6c33cef777aed649e65a40 . Closing the issue.
