### ISSUE TITLE
[DocDB][xCluster] Observed org.yb.client.ConnectionResetException while creating xCluster replication

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#14525]
### Description

Version: `2.15.4.0-b72`

Configure Replication step failed with `org.yb.client.ConnectionResetException` error and universes go to ERROR state.
tserver logs are filled with `W0921 13:35:56.113915  7532 cdc_service.cc:2056] LookupTabletByKey took long time: 1.005s ms`

slack discussion: https://yugabyte.slack.com/archives/CHC5RSY74/p1663768133735139

**Comment by nspiegelberg** [comment]
Primarily a Platform issue.  This issue is due to configuring the Master Timeout value where this specific command uses the TServer Timeout.  Also would be good to add a Master API as a proxy to get rid of Public TServer APIs.

**Comment by lingamsandeep** [comment]
Closing as we have a platform issue corresponding to this.
