### ISSUE TITLE
[YCQL&YSQL] Quantile metrics missing from new universes on versions >= 2.13

### ISSUE THREAD

**Issue by vmallepalli** [yugabyte/yugabyte-db#14531]
Jira Link: [DB-3914](https://yugabyte.atlassian.net/browse/DB-3914)
### Description

All the handler_latency metrics on both ports 12000 and 9000 are missing the quantile metrics — i.e. for every variant of handler_latency-* I see only the _sum and _count metrics in the metrics output by tserver.

This has been reproduced on our internal portal environment. 
We can see the YCQL P99 metric graph for this universe: 
https://portal.dev.yugabyte.com/universes/25bb1fc6-d74c-41ec-afa0-b0b331bdecc8/metrics
but not for this one: 
https://portal.dev.yugabyte.com/universes/2965792c-f913-4c14-89ba-22dac0e5751a/metrics

In general, we see the metrics are missing from many clusters 2.13 and newer. This looks like a regression!

Internal slack thread: https://yugabyte.slack.com/archives/C4K1838GL/p1664466730801269

**Comment by rthallamko3** [comment]
@vmallepalli , the universe https://portal.dev.yugabyte.com/universes/75ab7b1d-b724-44e2-b9f3-1993fe94e624/metrics is no longer around. Can you provide the steps to repro the problem. Which build is this on etc?

**Comment by rthallamko3** [comment]
The specified universe has no ycql workload running. I don't see anything that is problematic. <img width="1315" alt="Screen Shot 2022-10-18 at 4 35 08 PM" src="https://user-images.githubusercontent.com/17170123/196564401-8ca65ff2-e24b-468d-9f0e-40b8e93f2245.png">

**Comment by rthallamko3** [comment]
It does look like the issue repros on 2.14.3, investigating.

**Comment by bmatican** [comment]
Should be fixed by f8ff462bf530feaca733fba1f3c0fc12029ea1ca and was backported down to 2.14

**Comment by aravind-nallan-yb** [comment]
@bmatican @rthallamko3 How come i don't see a backport commit linked in this issue?

**Comment by rthallamko3** [comment]
The fix is tracked on the parent GH -
https://github.com/yugabyte/yugabyte-db/issues/14643. It has the details of
the backports too.

TK

**Comment by rthallamko3** [comment]
The fix is tracked on the parent GH - https://github.com/yugabyte/yugabyte-db/issues/14643. It has the details of the backports too.
