### ISSUE TITLE
Table with identifier 000000010000300080000000000004ec not found: OBJECT_NOT_FOUND

### ISSUE THREAD

**Issue by 88899** [yugabyte/yugabyte-db#14549]
Jira Link: [DB-3930](https://yugabyte.atlassian.net/browse/DB-3930)
### Description

Same issue as I found In the issue #11763, I am using the latested src of 2.17.0 branch

I did the following:

1. bin/yb-ctl destroy
2. ./yb_build.sh reinitdb
3. bin/yb-ctl create --replication_factor 1
4. bin/ysqlsh

The result:
ysqlsh: FATAL:  Not found: Table with identifier 000000010000300080000000000004ec not found: OBJECT_NOT_FOUND

**Comment by ddorian** [comment]
@88899 why are you doing this step: `./yb_build.sh reinitdb`? 

I don't see it in the docs.

**Comment by 88899** [comment]
> @88899 why are you doing this step: `./yb_build.sh reinitdb`?
> 
> I don't see it in the docs.

I initially built debug from the source. And deploied the master and tserver with replication factor 1. Then I tried to test the system using the ysqlsh, then this problem appeared. And I find  out there is another issue already closed with the same error information.  And then I tried these commands. I think this comman only rebuild the c++ src.

**Comment by ddorian** [comment]
Why are you building from source? Are you looking to contribute in c++?

**Comment by 88899** [comment]
> Why are you building from source? Are you looking to contribute in c++?

Out of interest I want to learn some thing about distributed database system.  I am not sure if I am capable to contribute.

**Comment by ddorian** [comment]
> Out of interest I want to learn some thing about distributed database system. I am not sure if I am capable to contribute.

Why not use the releases we distribute?

**Comment by 88899** [comment]
No worries, I used another clean virtual machine, everthing works fine.
