### ISSUE TITLE
[DocDB] Operation should hold a shared or weak pointer to Tablet instead of raw pointer

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#14546]
Jira Link: [DB-3927](https://yugabyte.atlassian.net/browse/DB-3927)
### Description

Operation should hold a shared or weak pointer to Tablet instead of raw pointer.

**Comment by rthallamko3** [comment]
@mbautin , Should we resolve his defect or were you anticipating additional changes to be made?
