### ISSUE TITLE
[DocDB] Flaky test 2.12 : org.yb.pgsql.TestPgSavepoints.testSavepointCommitWithAbort

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#14628]
Jira Link: [DB-3999](https://yugabyte.atlassian.net/browse/DB-3999)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=2.12&class=org.yb.pgsql.TestPgSavepoints&name=testSavepointCommitWithAbort

**Comment by bmatican** [comment]
Discussed offline with Piyush, we'll focus on backports for test fixes, down to 2.14, but no further for now.
Product fixes, that stem from tests, should still be backported as far as necessary!
