### ISSUE TITLE
[DocDB] Disallow packed row for co-located tables

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#14632]
Jira Link: [DB-4002](https://yugabyte.atlassian.net/browse/DB-4002)
### Description

Disallow packed row for co-located tables, while we identify and fix the backup-restore and xcluster integration with packed row feature to be stable.

**Comment by Huqicheng** [comment]
Introduce a new flag to indicate if packed row for colocated table is enabled. default false
