### ISSUE TITLE
Build fails on Ubuntu in file_numbers.h

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1464]
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
In file included from src/yb/rocksdb/db/memtable.h:37:0,
                 from src/yb/rocksdb/db/memtable_list.h:33,
                 from src/yb/rocksdb/db/column_family.h:34,
                 from src/yb/rocksdb/db/flush_job.h:38,
                 from src/yb/rocksdb/db/flush_job.cc:24:
src/yb/rocksdb/db/file_numbers.h: In member function ‘yb::Result<rocksdb::FileNumbersHolder> rocksdb::FlushJob::Run(rocksdb::FileMetaData*)’:
src/yb/rocksdb/db/file_numbers.h:64:33: error: ‘<anonymous>’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       : adder_remover_(std::move(rhs.adder_remover_)), file_numbers_(std::move(rhs.file_numbers_)) {
                        ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Input files:
  src/yb/rocksdb/CMakeFiles/rocksdb.dir/db/flush_job.cc.o
  src/yb/rocksdb/db/flush_job.cc
Output file (from -o): src/yb/rocksdb/CMakeFiles/rocksdb.dir/db/flush_job.cc.o
\-------------------------------------------------------------------------------
ninja: build stopped: subcommand failed.

real	9m44.691s
user	8m42.382s
sys	1m2.020s
[c30f1e328fbf 2019-05-31T06:44:24 yb_build.sh:394 run_cxx_build] C++ build finished with exit code 1 (build type: debug, compiler: gcc). Timing information is available above.

**Comment by mbautin** [comment]
https://circleci.com/gh/YugaByte/yugabyte-db/110?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ttyusupov** [comment]
Fixed in commit https://github.com/YugaByte/yugabyte-db/commit/ec45286f21e9e744cf4eacb18e9d4c442d643052
