### ISSUE TITLE
[DocDB] flaky test: AutoFlagsMiniClusterTest.Promote

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14653]
Jira Link: [DB-4019](https://yugabyte.atlassian.net/browse/DB-4019)
### Description

[AutoFlagsMiniClusterTest.Promote](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=AutoFlagsMiniClusterTest&fail_tag=tsan&name=Promote&platform=linux)

Is auto-flag promotion supposed to be thread safe? Or not anymore than using yb-ts-cli? If the latter, then we might want to annotate it as unprotected writes, for TSAN, as we’re getting ThreadSanitizer warnings in

**Comment by hari90** [comment]
This will be fixed by https://phabricator.dev.yugabyte.com/D20310

**Comment by hari90** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/6062ca87abec9133ae077695d9ee6f0021dd9b62
