### ISSUE TITLE
[Docs] Manual remote bootstrap of failed peer

### ISSUE THREAD

**Issue by pgyogesh** [yugabyte/yugabyte-db#14654]
### Description

`remote_bootstrap` is not available in 2.15.x

Link: https://docs.yugabyte.com/preview/troubleshoot/cluster/replace_failed_peers/

**Comment by ddorian** [comment]
Only the `preview` version for 2.17 is available for that page and that command is available in 2.17.

So I guess this is fixed? Or can you provide an alternative fix?
