### ISSUE TITLE
[DocDB] Introduce macros for deprecating gflags

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#14661]
Jira Link: [DB-4024](https://yugabyte.atlassian.net/browse/DB-4024)
### Description

Introduce a graceful way to remove flags from code by deprecating them. When customers try to set Deprecated flags we will print a warning in the logs but not crash the process.

**Comment by robertsami** [comment]
resolved by 7d1988ac165a7aa0cb28aede44053a4916008122. unfortunately did not tag that commit with this issue
