### ISSUE TITLE
[YSQL] Reduce cache-refresh per-connection memory utilization	

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#14666]
Jira Link: [DB-4029](https://yugabyte.atlassian.net/browse/DB-4029)
### Description

Details analyzed in this doc: [YSQL connection memory utilization breakdown](https://docs.google.com/document/d/1JK8nG785WPICzcuq5BOyLqELAbFifiEFxEkzABcTZLs/edit#) 

Related issue: https://github.com/YugaByte/yugabyte-db/issues/14212

**Comment by SteveXiSong** [comment]
This issue is resolved by https://github.com/YugaByte/yugabyte-db/issues/14212.
