### ISSUE TITLE
system.local always returns 0 token

### ISSUE THREAD

**Issue by spolitov** [YugaByte/yugabyte-db#1467]

**Comment by kmuthukk** [comment]
This causes the issue described in C# driver: https://forum.yugabyte.com/t/can-only-connect-to-1-box-in-a-3-box-cluster/361/9

**Comment by kmuthukk** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/e2ae8ede9ab89b2efa33c5df05cef8dd7fb6a0d5
