### ISSUE TITLE
Support fallback options in topology-aware load balancing of the YSQL Go smart driver

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#14707]
Jira Link: [DB-4054](https://yugabyte.atlassian.net/browse/DB-4054)
### Description

Provide a mechanism to specify a fallback server or servers in the pgx smart driver when using topology aware connection load balancing feature.

**Comment by HarshDaryani896** [comment]
Feature integrated with this [PR](https://github.com/yugabyte/pgx/pull/5) and corresponding tests added with this [PR](https://github.com/yugabyte/driver-examples/pull/5).
