### ISSUE TITLE
[DocDB] LDB tool is crashing while trying to dump manifest file

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#14716]
Jira Link: [DB-4061](https://yugabyte.atlassian.net/browse/DB-4061)
### Description

The following command core dumps:
`./build/latest/bin/ldb manifest_dump --path=/home/centos/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-00004000000030008000000000000000.colocated.parent.uuid/tablet-22f26f331667477685603fefc585444e/MANIFEST-000013`

Confirmed on different local machines, does not depend on tablet type.

Logs:

> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I1028 07:26:12.126197 21952 docdb_rocksdb_util.cc:393] FLAGS_rocksdb_max_background_flushes was not set, automatically configuring 1 max background flushes
> I1028 07:26:12.126426 21952 docdb_rocksdb_util.cc:428] FLAGS_rocksdb_max_background_compactions was not set, automatically configuring 1 background compactions.
> I1028 07:26:12.126437 21952 docdb_rocksdb_util.cc:441] FLAGS_rocksdb_base_background_compactions was not set, automatically configuring 1 base background compactions.
> I1028 07:26:12.126492 21952 docdb_rocksdb_util.cc:601] FLAGS_priority_thread_pool_size was not set, automatically configuring to 2.
> Error in processing file /home/centos/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-00004000000030008000000000000000.colocated.parent.uuid/tablet-22f26f331667477685603fefc585444e/MANIFEST-000013 Illegal state (yb/rocksdb/db/version_edit.cc:190): Boundary values contains user frontier but extractor is not specified: key: "0\313(\242\177S\235\321\ny)\354E\317\234\202\221S\236\305\317\327\000\000!J\200#\200\001h5\277\203\276\314\200J\001\001\000\000\000\000\000\004" seqno: 1125899906842625 user_values { tag: 10 data: "S\235\321\ny)\354E\317\234\202\221S\236\305\317\327\000\000" } user_frontier { [type.googleapis.com/yb.docdb.ConsensusFrontierPB] { op_id { term: 1 index: 3 } hybrid_time: 6827601596714790912 history_cutoff: 18446744073709551614 max_value_level_ttl_expiration_time: 18446744073709551614 table_schema_version { table_id: "\001@\000\000\000\000\000\200\0000\000\000\000@\000\000" schema_version: 0 } } }
> F1028 07:26:12.131892 21952 column_family.cc:479] Check failed: dummy_versions_->TEST_Next() == dummy_versions_ (0x55e58e925800 vs. 0x55e58e924c00) 
> *** Check failure stack trace: ***
> Aborted (core dumped)

**Comment by rthallamko3** [comment]
This test needs a unit test too.

**Comment by rthallamko3** [comment]
@arybochkin , lets backport https://github.com/yugabyte/yugabyte-db/issues/14716 all the way to 2.12?
