### ISSUE TITLE
[YSQL] Create a master-level flag for enabling/disabling YSQL

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1473]
Currently we have a tserver-level flag, `--start_pgsql_proxy`, but no master-level flag to enable/disable YSQL.

This new master-level flag should eventually supersede the tserver flag, as tserver should get its configuration from the master.

Also we should make `yb-ctl` set this master-level flag based on whether YSQL is enabled or disabled there.

**Comment by bmatican** [comment]
We now have an `--enable_ysql` flag
