### ISSUE TITLE
[New Feature] [Smart Driver] Limiting Connection to Read Replicas co-located (zone) with Primary Cluster 

### ISSUE THREAD

**Issue by yogendra** [yugabyte/yugabyte-db#14743]
Jira Link: [DB-4081](https://yugabyte.atlassian.net/browse/DB-4081)
### Description

I am requesting enhancement to smart driver to connect to read-replicas only. 

**Describe the issue**

Working with read replicas and smart driver, I noticed that smart driver will connect to any node (including ones in primary cluster) in the same zone as read replicas. Ideally I want to limit the connections to only the read replica nodes.

**Driver Version?** 
42.3.0

**Java Version?**
17

**OS Version?**
Mac OS, Linux

**PostgreSQL Version?**
N/A

**To Reproduce**
1. Create a yb cluster (cloud1.region1.zone1,cloud1.region1.zone2,cloud1.region1.zone3
2. Add a read replica in the same zone as primary cluster (cloud1.region1.zone3)
3. Run sample app with jdbc url pointing to read-replica nodes, set appropriate `topology-keys=cloud1.region1.zone3` and `load-balance=true`

**Expected behaviour**
I expect the app/driver to only access read-replicas. But I observe that the driver will connect to nodes on primary cluster as well as read-replica cluster

**Logs**
If possible PostgreSQL logs surrounding the occurrence of the issue

**Comment by ashetkar** [comment]
Completed with Driver version 42.3.5-yb-8
