### ISSUE TITLE
[YugabyteD] [QA] [Enhancement] Better informative message in case of invalid fault_tolerance/rf

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14742]
### Description

Error message in case of single node cluster:
```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted configure --base_dir=/Users/mzafar/yy --fault_tolerance=zone
FAILED: Invalid number of placement constraint specified.
```

We should give more informative message here for new Users.

**Comment by zlareb1-yb** [comment]
We also give below INFO msg in the logs. This is given even if the fault_tolerance is being changed to something else:
`[yugabyted configure] 2022-10-29 20:10:34,052 INFO:  | 0.5s | Desired fault tolerance is already setup. No Masters to move.`

**Comment by nchandrappa** [comment]
As part of #16208 more informative status message will displayed for the `configure` command of RF-3,5,7 deployments, when there aren't enough availability zones/regions to satisfy the data placement policy.
