### ISSUE TITLE
[DocDB] /tablet-replication does not account for custom table level RF

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#14754]
Jira Link: [DB-4086](https://yugabyte.atlassian.net/browse/DB-4086)
### Description

The `/tablet-replication` end point displays all leaderless and under-replicated tablets. When determining the under-replicated tablets, we compare the active replica count with the replication factor to decide if a tablet is below the expected replica count. With custom RF set via tablespaces, we have the ability to override the global cluster wide RF with a different RF for the specific table. However, we don't account for this table-level RF in the above logic.

**Comment by bmatican** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/17867
