### ISSUE TITLE
[YSQL] Catalog manager namespace and table name maps to contain YSQL tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1476]
Currently, YSQL table information is maintained in namespace and table ID maps instead of namespace and table name maps and this causes problems while trying to look up tables by their names. YSQL table maps also need to store schema since the same database can have same table name in different schemas.

This is needed by CDC as well as some yb-admin commands.

**Comment by m-iancu** [comment]
Related issue is that those maps need to be updated when the relevant metadata is altered.
For instance, currently, after running:
```
postgres=# create table foo(a int);
CREATE TABLE
postgres=# alter table foo rename to bar;
ALTER TABLE
postgres=# select * from bar;
 a
---
(0 rows)

postgres=# \d
        List of relations
 Schema | Name | Type  |  Owner
--------+------+-------+----------
 public | bar  | table | postgres
(1 row)

The UI will still show the old name:
```
![image](https://user-images.githubusercontent.com/4038003/61404852-47cd4200-a88d-11e9-9336-b2e34203e8d0.png)

**Comment by d-uspenskiy** [comment]
Phase 1 is completed. `yb-admin` is able to operate on YSQL tables.
Phase 2 is in progress. YSQL has no table schema yet as a result multiple tables can has same name and `yb-admin` can't distinguish them

**Comment by kmuthukk** [comment]
@d-uspenskiy -- increasing priority on this to help address issues like #1991.

**Comment by d-uspenskiy** [comment]
yb-admin command for YSQL tables are now supported by https://github.com/yugabyte/yugabyte-db/commit/e6318c0b3711bbacc7c1503029e28fd776c3b30b
