### ISSUE TITLE
[YSQL][Test] TestPgTransparentRestarts.selectStarShortPreparedParameterized is broken

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#14772]
Jira Link: [DB-4097](https://yugabyte.atlassian.net/browse/DB-4097)
### Description

In #14467 we found a bug in `TestPgTransparentRestarts.selectStarShortPreparedParameterized` which was mixing up `REPEATABLE READ` and `SERIALIZABLE` isolations. After fixing it, this test started is now failing consistently with errors like
```
SELECT (single-stmt): unexpected 4 conflict errors at SERIALIZABLE level
```
This might indicate a real issue.

**Comment by kripasreenivasan** [comment]
Observing address sanitizer errors in TestPgTransparentRestarts#selectStarShortPrepared_simpleQueryMode :
https://gist.github.com/kripasreenivasan/2676a350398371df86a7b8cbcadfdfe7
