### ISSUE TITLE
[YW] RemoveNode stops the TS process before draining the data

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1478]
The current RemoveNode task in YW first stops ths TS process, then updates the blacklist, then waits for data to move. The correct logic should be a more graceful operation, where we wait for data to move first and only then stop the process...

cc @ramkumarvs @Arnav15 @WesleyW

**Comment by Arnav15** [comment]
Looks like a regression caused due to https://phabricator.dev.yugabyte.com/D5262
cc @kmuthukk
