### ISSUE TITLE
[CDCSDK] Regression with colocated table support

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#14788]
Jira Link: [DB-4106](https://yugabyte.atlassian.net/browse/DB-4106)
After compiling the code from master branch and running the Debezium connector there, as soon as I insert a record in one of the tables, I get this error from the connector:
```
2022-10-30 17:12:00,494 INFO   YugabyteDB|dbserver1|streaming  Schema for table 'public.test' is missing   [io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter]
```

Steps to reproduce:
1. Create database: `CREATE DATABASE testdb colocated = true;`
2. Create tables: `create table test (id int primary key) with (colocated=true);` and `create table test2 (name text primary key) with (colocated=true);`
3. Create stream and run the CDC pipeline
4. Insert a record in any of the tables, the above mentioned error is produced.

After printing the DDL record, it looked something like:
```
row_message {
  table: "test2"
  op: DDL
  schema {
    column_info {
      name: "parent_column"
      type {
        main: BINARY
      }
      is_key: true
      is_hash_key: false
      is_nullable: false
      oid: 0
    }
    tab_info {
      default_time_to_live: 0
      num_tablets: 0
      is_ysql_catalog_table: false
    }
  }
  schema_version: 0
  pgschema_name: ""
}

row_message {
  table: "test"
  op: DDL
  schema {
    column_info {
      name: "parent_column"
      type {
        main: BINARY
      }
      is_key: true
      is_hash_key: false
      is_nullable: false
      oid: 0
    }
    tab_info {
      default_time_to_live: 0
      num_tablets: 0
      is_ysql_catalog_table: false
    }
  }
  schema_version: 0
  pgschema_name: ""
}
```

There seem to be 2 things wrong with the above DDL record:
1. `pgschema_name` is missing
2. Column name is coming out as `parent_column` instead of what the actual value is

**Comment by sureshdash2022-yb** [comment]
We have have fixed the issue in the above described diff.
