### ISSUE TITLE
[Docs] Connect an application

### ISSUE THREAD

**Issue by Lilley-Peter** [yugabyte/yugabyte-db#14799]
### Description

There are a couple of issues with this doc.
1. postgres needs to be above version 11, so 12 or higher.

2.You can not install the yugabyte driver on top of the current psycopg2 driver. You need to uninstall the pyscopg2 driver. Remove the cache then install the driver(this **didnt** work for me but was recommended by a software engineer)

3. The instructions this doc forwards you to says you should install the binary package, this will cause errors when trying to install the yugabyte version

4.I installed successfully on Ubuntu 20.04 with  following commands

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3-dev
sudo apt-get install libpq-dev
sudo apt-get update
sudo apt-get upgrade
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get install postgresql-12
export PATH=/usr/lib/postgresql/12/bin/:$PATH
sudo apt-get install python-is-python3
sudo apt install python3-pip
pip3 install psycopg2-yugabytedb

5. I am currently working with 2 customers who are experiencing issues with this driver documentation

6. Maybe we can advise in the doc to not install the binary driver or to remove the psycopg2 driver if already installed for customers?

7.Maybe we can have a short script available like above for different OS?

**Comment by ddorian** [comment]
> There are a couple of issues with this doc.

Please mention the link of the doc.

> postgres needs to be above version 11, so 12 or higher.

Why? 

>  sudo apt-get install python-is-python3

This may break the system if it expects the default to be python 2.7
```
$ pip install psycopg2-yugabytedb
Collecting psycopg2-yugabytedb
  Downloading psycopg2-yugabytedb-2.9.3.post0.tar.gz (386 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.2/386.2 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: psycopg2-yugabytedb
  Building wheel for psycopg2-yugabytedb (setup.py) ... done
  Created wheel for psycopg2-yugabytedb: filename=psycopg2_yugabytedb-2.9.3.post0-cp311-cp311-linux_x86_64.whl size=519678 sha256=8971e9ec437924df83766543df243e9c62b9a1756fe0dd00676a43953ca59dfb
  Stored in directory: /home/guru/.cache/pip/wheels/3d/64/a5/e0b7b4c105f4f6c11e7c852169d65aefa00f986c7d54dc3d47
Successfully built psycopg2-yugabytedb
Installing collected packages: psycopg2-yugabytedb
Successfully installed psycopg2-yugabytedb-2.9.3.post0
```

Worked on the first try for me on Python 3.11 virtualenv.

**Comment by Lilley-Peter** [comment]
There are a couple of issues with this doc.

Please mention the link of the doc.

postgres needs to be above version 11, so 12 or higher.

Why? As instructed to me by Sfurti because "PQHostadddr is not defined in previous versions."

sudo apt-get install python-is-python3

This may break the system if it expects the default to be python 2.7: Docs here https://www.psycopg.org/docs/install.html#prerequisites state 3.6 to 3.11

$ pip install psycopg2-yugabytedb
Collecting psycopg2-yugabytedb
  Downloading psycopg2-yugabytedb-2.9.3.post0.tar.gz (386 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.2/386.2 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: psycopg2-yugabytedb
  Building wheel for psycopg2-yugabytedb (setup.py) ... done
  Created wheel for psycopg2-yugabytedb: filename=psycopg2_yugabytedb-2.9.3.post0-cp311-cp311-linux_x86_64.whl size=519678 sha256=8971e9ec437924df83766543df243e9c62b9a1756fe0dd00676a43953ca59dfb
  Stored in directory: /home/guru/.cache/pip/wheels/3d/64/a5/e0b7b4c105f4f6c11e7c852169d65aefa00f986c7d54dc3d47
Successfully built psycopg2-yugabytedb
Installing collected packages: psycopg2-yugabytedb
Successfully installed psycopg2-yugabytedb-2.9.3.post0
Worked on the first try for me on Python 3.11 virtualenv.

Yes install is fine and says success...did you try running the QuickStartApp? Two other engineers and I have faced the same issue over the past few days. If its easier ping me on slack for clarification. I was testing on amazon linux, another engineer was using ubuntu, and the 3rd was using centos. 

Are you using postgres or yugabyte as your DB?

**Comment by ddorian** [comment]
Please format the response because it was hard to read (I formatted it for clarity)

> Are you using postgres or yugabyte as your DB?

I have PostgreSQL 14 installed locally. And of course YugabyteDB in multiple versions.
I already had the `*-dev` packages though.
And https://docs.yugabyte.com/preview/drivers-orms/python/yugabyte-psycopg2/#step-3-write-your-application worked for me.

> sudo apt-get install python-is-python3
> pip3 install psycopg2-yugabytedb

This shouldn't be done. On python you should be using a virtualenv and running all code inside it instead of changing the system python.

**Comment by ddorian** [comment]
> I am currently working with 2 customers who are experiencing issues with this driver documentation

Please write also the errors that they're experiencing.

**Comment by Lilley-Peter** [comment]
My apologies on the formatting issues.
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/78859174/199705392-36335213-c582-45df-8188-1c1243063b63.png">
Theres an issue I was facing when running the QuickStartApp.py from a python venv (test). I think the biggest issue with the documentation is that it points you here:

> https://www.psycopg.org/docs/install.html#build-prerequisites

So like me, and our colleagues, the customer either installed the binary package as instructed by the prerequisites, or installed the *.dev packages on their own, then installed the pyscopg2 driver, as instructed by the documentation. However according to Sfuri if you install the pyscopg2 driver before the yuagbyte driver you'll have to uninstall both packages then reinstall the yugabyte driver. However as you can see from the screenshot above that was unsuccessful. Our documentation also gives no warning about this.

I have tested both these drivers in 4 different venvs, running the QuickStartApp.py from our documentation 

> https://docs.yugabyte.com/preview/drivers-orms/python/yugabyte-psycopg2/#step-3-write-your-application

My findings are if I just install the psycopg2 driver, the code runs fine. 
If I just install the yugabyte driver the code runs fine. 
However the issues arise when I install the yugabyte driver after the pyscopg2 driver, the customer I am working with already has psycopg2 installed on their system(Linux). I think the frustration from the customer comes from the fact our documentation doesn't have the correct version of postgres, and doesn't have a warning about the overlap of the installed drivers, nor does it provide a solution or recommendation on how to successfully remove the driver to then reinstall ours. Concurrently You can install both packages back to back on a system and they both show success, even though they seem to throw errors when importing the driver in the code and screenshot above.

> sudo apt-get install python-is-python3
> pip3 install psycopg2-yugabytedb
> This shouldn't be done. On python you should be using a virtualenv and running all code inside it instead of changing the system python.

Okay, I just did it because out documentation shows here:
>https://docs.yugabyte.com/preview/quick-start/linux/
`python --version`
`Python 3.7.3`
and on Ubuntu that command will return Python 2.X.X. My apologies if this is incorrect. 

>I am currently working with 2 customers who are experiencing issues with this driver documentation
>Please write also the errors that they're experiencing.
Both customers just said it didnt work. I have calls with one of them today and I can dig deeper into the issue, and report my findings. 
Thank you for your time and concern in this matter, again if you want to ping me on slack or check out the conversation Sfuri and I had its in the ecosystems channel.

**Comment by Sfurti-yb** [comment]
@aishwarya24 , the following changes are to be made in the psycopg2 doc:
1. Change the Postgresql version required from "11 and above" to "12 and above"
2. Add the following limitation - "Currently, the postgres driver, psycopg2, and the YugabyteDB smart driver cannot be used in the same environment."
