### ISSUE TITLE
[docdb] Load Balancer should continue doing work if a DEAD node is actually BlackListed

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1479]
Noticed this in a customer cluster while doing some maintenance:
- used YW to remove a node
- YW set the BlackList for this node and the LoadBalancer proceeded to move load off of the node
- due to a YW issue (#1478), the TS process was also stopped, so it stopped heartbeating to the master
- after 60s, the TS was naturally marked as DEAD in the master
- at this point, the LB stopped actually doing balancing work, due to the condition that all TS present in raft groups must be ALIVE!

Under normal circumstances, this might be fine, as we want to be conservative around node deaths and we can also just have the raft groups heal themselves. However, in an explicit user action scenario, like using the BlackList, we should respect that and do the work.

cc @rajukumaryb @rahuldesirazu @kmuthukk

**Comment by rahuldesirazu** [comment]
@bmatican Question, if a TS that is blacklisted is stopped, who is then responsible for draining the data? Or do you mean continue LB operations for all alive tservers?

**Comment by bmatican** [comment]
@rahuldesirazu well, technically, we can do ChangeConfig operations even if the node is dead! I think a good part of stopping the LB from acting on DEAD servers was that it might consider doing AddServer operations TO that server, which would yield a lot of failed RPCs, as we would not be able to talk to it. For Remove however, Raft just needs a majority to kick out a server...

**Comment by rahuldesirazu** [comment]
@bmatican Do we still need a fix for this after we fixed #1478.
