### ISSUE TITLE
[DocDB] Execute after restoring data(from s3) on 2.14.5.0 b8 is failing with schema version mismatch

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#14800]
Jira Link: [DB-4114](https://yugabyte.atlassian.net/browse/DB-4114)
### Description

```
java.lang.RuntimeException: Unexpected fatal, error in 'Worker<4790>' when executing 'Delivery/04'
    at com.oltpbenchmark.api.Worker.doWork(Worker.java:584)
    at com.oltpbenchmark.api.Worker.run(Worker.java:368)
    at java.lang.Thread.run(Thread.java:750)
Caused by: org.postgresql.util.PSQLException: ERROR: Query error: schema version mismatch for table 000033e8000030008000000000004029: expected 1, got 0
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse
```

https://phabricator.dev.yugabyte.com/D20627 : This change has been backported to 2.14.5.0 in b8 and may be causing the failure.

**Comment by rthallamko3** [comment]
@arybochkin , Are we planning to address this?

**Comment by arybochkin** [comment]
@rthallamko3, I think no action is required. I believe this error can appear only for transactional requests and the request should be repeated manually to resolve this error -- transparent retry for schema version mismatch is not supported for transactional blocks (cc @deeps1991).

**Comment by rthallamko3** [comment]
closing this issue as per @arybochkin 's comment.
