### ISSUE TITLE
[Docs] yb-admin - command line tool for advanced YugabyteDB administration

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14821]
### Description

The command for list_tablets doesn't specify all the arguments correctly. Running that command throws 
`Error running list_tablets: Invalid argument (yb/tools/yb-admin_client.cc:360): Namespace '<namespace name>' of type 'ycql' not found
Usage: bin/yb-admin list_tablets  <keyspace_type>.<keyspace_name> (keyspace_type is ysql or ycql) <table> [<max_tablets>]` error.

**Comment by ddorian** [comment]
Has been fixed in https://github.com/yugabyte/yugabyte-db/pull/17183
