### ISSUE TITLE
[DocDB] Correct timeout error message on issuing compact_table on a large table

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14844]
Jira Link: [DB-4141](https://yugabyte.atlassian.net/browse/DB-4141)
### Description

- Issued a flush_table followed by a compact_table on a YSQL table whose SST size is 27.85 GB and WAL size is 4.5 GB
- The flush succeeded however the compact failed due to a timeout.
Issue: The compact_table command timeour error message reads `Timed out waiting for FlushTables`. This needs to be corrected.
```
[yugabyte@ip-172-151-38-207 master]$ ./bin/yb-admin --master_addresses 172.151.38.207,172.151.27.95,172.151.57.239 flush_table  ysql.postgres sqldataload
Flushed [postgres.sqldataload] tables.
[yugabyte@ip-172-151-38-207 master]$ ./bin/yb-admin --master_addresses 172.151.38.207,172.151.27.95,172.151.57.239 compact_table ysql.postgres sqldataload
Error running compact_table: Timed out (yb/util/backoff_waiter.cc:50): Unable to compact table postgres.sqldataload: Timed out waiting for FlushTables
```

**Comment by jmeehan16** [comment]
Closing this as duplicate work of https://github.com/yugabyte/yugabyte-db/issues/16230
