### ISSUE TITLE
[YSQL] Create a virtual transaction uuid for tracking shared memory locks taken by single shard transactions

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#14852]
Jira Link: [DB-4149](https://yugabyte.atlassian.net/browse/DB-4149)
### Description

Sub task of #12168

**Comment by robertsami** [comment]
No longer relevant as we will not track these locks in pg_locks and we don't expect them to be long held. We should still safeguard against bugs which may cause them to be long held: https://github.com/yugabyte/yugabyte-db/issues/16920
