### ISSUE TITLE
[Docs] Add documentation for LDAP authentication enhancement

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#14857]
### Description

We added enhancement for LDAP authentication to avoid providing plain text password for K8 environment (GH 
 https://github.com/yugabyte/yugabyte-db/issues/13367 ). We should update the docs page for [LDAP authentication ](https://docs.yugabyte.com/preview/secure/authentication/ldap-authentication-ysql/) with this enhancement.

**Comment by ddhodge** [comment]
See https://yugabyte.slack.com/archives/CDQB8MEAU/p1667582052477249
