### ISSUE TITLE
[DocDB] The throughput of the workload drops due to leader elections post split.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#14859]
Jira Link: [DB-4152](https://yugabyte.atlassian.net/browse/DB-4152)
### Description

Universe:
https://portal.dev.yugabyte.com/universes/5eb924e2-a7ce-4b9f-aab7-157bd59e779b/metrics?endDate=1666627200&filterType=custom&nodeName=all&nodePrefix=yb-15-qhu-splitting-retryablerequest&startDate=1666616400 

We observed that the workload throughput (YCQL ops/sec) drops by 25-30% during a two minute window (during which tablet splits happen, and as a result new leaders are elected). Is it possible to minimize the leader changes so as to not impact the throughput of the workload.

[DB-4152]: https://yugabyte.atlassian.net/browse/DB-4152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Huqicheng** [comment]
```
java -jar yb-sample-apps.jar --workload CassandraBatchTimeseries --nodes 10.150.1.91:9042 --num_threads_read 4 --num_threads_write 20 --nouuid --min_metrics_count 10000 --max_metrics_count 20000 --num_unique_keys 1000000000
```

We can try with --enable_lease_revocation=true to see if mitigate it.

**Comment by arybochkin** [comment]
`enable_lease_revocation=true` is now set as default.

**Comment by arybochkin** [comment]
I've made several tests and actually I've got a more % of drop within two minutes and in general.
Workload:
> java -jar /nfusr/dev-server/arybochkin/app/yb-sample-apps.jar --nodes 10.150.4.29:9042,10.150.4.32:9042,10.150.4.28:9042 --workload CassandraBatchTimeseries --num_threads_read 3 --num_threads_write 10 --nouuid --min_metrics_count 10000 --max_metrics_count 20000 --num_unique_keys 500000000

Table was created before workload execution:
> CREATE TABLE batch_ts_metrics_raw (metric_id varchar, ts bigint, value varchar, primary key (metric_id, ts));

I've been told the following GFlags were used:
> Master: {
>   "tablet_split_high_phase_shard_count_per_node": 10000,
>   "tablet_split_high_phase_size_threshold_bytes": 10485760,
>   "tablet_split_low_phase_size_threshold_bytes": 1048576,
>   "tablet_split_low_phase_shard_count_per_node": 16,
>   "enable_automatic_tablet_splitting": true,
>   **"db_write_buffer_size": 102400**
> }
> Tserver: {
>   "enable_automatic_tablet_splitting": true,
>   **"db_write_buffer_size": 102400**
> }

Graphs:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/79331145/222168326-8e8623b4-6535-4945-a78c-886e5c6fd76c.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/79331145/222168668-ac07f020-d07b-4459-8de6-938e8873b5fa.png">

**Comment by arybochkin** [comment]
The suspicious thing from the previous run is why `db_write_buffer_size` set to 100 KB was used. It gives more SST files, flushes, compactions (paused and queued) and disk IOPS
<img width="572" alt="image" src="https://user-images.githubusercontent.com/79331145/222170885-5a27565e-b698-42a1-a46f-f9366fed4aa7.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/79331145/222170749-6f598c8d-670c-4453-a8a2-5fd37cd979ca.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/79331145/222170620-48843ca2-e213-4041-9238-2e468117d4c0.png">

**Comment by arybochkin** [comment]
Running the workload without `db_write_buffer_size` gives stable ops/node as well as other metrics.
Workload:
> java -jar /nfusr/dev-server/arybochkin/app/yb-sample-apps.jar --nodes 10.150.4.29:9042,10.150.4.32:9042,10.150.4.28:9042 --workload CassandraBatchTimeseries --num_threads_read 3 --num_threads_write 10 --nouuid --min_metrics_count 10000 --max_metrics_count 20000 --num_unique_keys 500000000

Table was created before workload execution:
> CREATE TABLE batch_ts_metrics_raw (metric_id varchar, ts bigint, value varchar, primary key (metric_id, ts));

I've been told the following GFlags were used:
> Master: {
>   "tablet_split_high_phase_shard_count_per_node": 10000,
>   "tablet_split_high_phase_size_threshold_bytes": 10485760,
>   "tablet_split_low_phase_size_threshold_bytes": 1048576,
>   "tablet_split_low_phase_shard_count_per_node": 16,
>   "enable_automatic_tablet_splitting": true,
> }
> Tserver: {
>   "enable_automatic_tablet_splitting": true,
> }

<img width="570" alt="image" src="https://user-images.githubusercontent.com/79331145/222172032-c04fb7ca-1754-4f36-9d9b-0c16d6e21381.png">

**Comment by rthallamko3** [comment]
@arybochkin made some very good breakthrough in his investigations. Here are some observations:

1. The CassandraBatchTimeseries workload works well even with tablet-splitting enabled (for default split thresholds and default IO limits etc). 
2. However, when the workload is run with tserver gflag - _db_write_buffer_size_ set to 100 KB, the number of SSTs in the tablet is high, which leads to write rejections, and thus reduced throughput. If the _db_write_buffer_size_ is low, then the flush is aggressively called in the system, which generates a new SST file => Rate of SST file generation is artificially high in that configuration. If the rate of SST compaction is not caught up (which is the case - as there are limits to the number of compactions on a node), the number of SST file limit is going to be hit at some point, impacting the workload.

(2) can be handled by an adaptive throttling scheme - Do not throttle writes on a tablet if the tablet is already being compacted or a compaction is scheduled and is not active yet. This is the fix that will be help with cases like https://github.com/yugabyte/yugabyte-db/issues/16091 too. Closing this bug in favor of https://github.com/yugabyte/yugabyte-db/issues/16091. cc @arybochkin , @bmatican

**Comment by bmatican** [comment]
Oh I didn't realize the db_write_buffer_size was so low! I thought we had discussed several times that these splitting & memstore gflags should not be set to such extremely small values...

Given this, then in steady state, I wouldn't worry about compactions even in the case of #16091 , unless we get some signal that these are problematic. Arguably, for such gargantuan tablets, of 100GB+, we should bump the soft/hard limits in the first place instead... Or, more practically, we should split them down to 10-20GB, so compactions don't take forever...
