### ISSUE TITLE
[YSQL] Populate shared memory locks information from tservers in pg_locks

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#14851]
Jira Link: [DB-4148](https://yugabyte.atlassian.net/browse/DB-4148)
### Description

Sub task of #12168

**Comment by robertsami** [comment]
these locks are too ephemeral to be worthy of tracking. if observability is needed here it should take another form, like a LOG(WARNING/ERROR) in case these latches are held too long
