### ISSUE TITLE
[YSQL] Tablegroup child table not found in parent table tablet

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#14873]
Jira Link: [DB-4157](https://yugabyte.atlassian.net/browse/DB-4157)
### Description
Update:
This issue is more like a dst issue. The beta colocated database doesn't have this issue.
A simple example with replication factor 3 could reproduce this error with around a 5% chance.
```
./bin/yb-ctl destroy && ./bin/yb-ctl create --rf=3 && ./bin/ysqlsh
CREATE TABLEGROUP tg1;
-- Sleep here for 30 seconds. Giving enough time for bootstrap solve this issue.
CREATE TABLE test_tbl (
  h INT PRIMARY KEY,
  a INT,
  b FLOAT CONSTRAINT test_tbl_uniq UNIQUE WITH (colocation_id=654321)
) WITH (colocation_id=123456) TABLEGROUP tg1;
CREATE INDEX test_tbl_idx ON test_tbl (a ASC) WITH (colocation_id=11223344);
```
The error is somehow one tserver `x` is bootstraping a tablegroup parent table tablet `t` for a long time so that the tablet `t` raft group on tserver `x` doesn't properly replicate all states. An error occurs: `[ts-2] F1106 21:16:12.204051 17945 tablet.cc:3979] Check failed: _s.ok() Bad status: Not found (yb/tablet/tablet_metadata.cc:529): Table <unknown_table_name> (000033e8000030008000000000004001) not found in Raft group 8c7c16280c7d4a2bb9ee1f18f039c404`
Sleeping 30 seconds after creating the tablegroup gives enough time for bootstrapping seems to solve this issue (no issue happened in 1000 runs).
My test log link: https://drive.google.com/file/d/15yIQj77umkBHEBOtNYtXOM5nLkDiLcD_/view?usp=share_link
The error I describe here is the same as the error showed in the flaky test: `ybd release --cxx-test pgwrapper_pg_index_backfill-test --gtest_filter PgIndexBackfillTest.Tablegroup --clang15` and `PgLibPqTest.ColocatedTablegroups`

**Comment by Huqicheng** [comment]
It's failing at ChangeMetadataOperation::Prepare -> Tablet::CreatePreparedChangeMetadata
The failing follower should have replicated the operation to add table, but not applied. When replicating the alter schema operation, inside CreatePreparedChangeMetadata, it's doing some check, including GetKeySchema. Since the previous operation is not done yet, it fails to get it.

**Comment by yifanguan** [comment]
Seems to be a duplicate of GitHub issue #10100
