### ISSUE TITLE
[YugabyteD] [QA] [Minor Enhancement] Remove -h flag as it is not consistent with other tools

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14884]
### Description

-h is not supported by other tools like "yb-master" and only --help is supported.
We should remove -h option from YugabyteD as well for consistency.

**Comment by nchandrappa** [comment]
We want to follow what the industry is doing, `-h` is generally supported by all major CLIs like kubectl, aws cli etc. 

Also, yugabyted will be the only customer-facing CLI once its feature is complete. We should have a requirement for other CLIs to support `-h`.
