### ISSUE TITLE
Metrics: SST file size incorrectly shown in some cases

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#1488]
The YW graph for SST Table Size can be wrong. This is because it adds up the `rocksdb_total_sst_file_size` metric shown in `/metrics` (handler of each tserver) and adds it up. 

However, there are a few issues here

A) Tablets that have been deleted on the tserver, still have their entries in the metrics registry and show up on /metrics. This causes the size reported by metrics to be larger than the on-disk size (which is 0 for those tablets)

B) Some Tablets seem to have the metric_key for sst_files twice. This could also lead to double counting.

On the cluster we investigated (A) was the more dominant problem, since had tablets from deleted tables as well as tablets which had moved to other newly added nodes.

We'll need to identify what's causing the double key in the metrics. And also ensure that when a tablet is deleted/tombstoned, the metrics registry entry for that tablet is removed on the specific TServer.

Repro'ing this (at least A) should be pretty easy -- create a table, load some data (check the `rocksdb_total_sst_file_size` metric in the `/metrics` handler for tablets of this table. Now delete the table, and check the same metrics again.

**Comment by bmatican** [comment]
@rajukumaryb if you can sync up with @amitanandaiyer or @kmuthukk for a repro, this might be good to go over, to see how metadata, like data size, gets propagated from rocksdb up!

This might be a signal we can eventually use for better data placement from the master.

**Comment by bmatican** [comment]
Closing this as likely due to #5640 which was recently fixed.
