### ISSUE TITLE
[Unit Test]: ThreadSanitizer check failed in XClusterAdminCliTest.TestDeleteCDCStreamWithAlterUniverse

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14914]
Jira Link: [DB-4185](https://yugabyte.atlassian.net/browse/DB-4185)
### Description

ThreadSanitizer check failed in XClusterAdminCliTest.TestDeleteCDCStreamWithAlterUniverse for `2.17.0.0-b17` build type centos-master-clang14-tsan
Stacktrace: https://gist.github.com/Karvy-yb/42d13db08c53a7fb6a98b24c327f024f

**Comment by NatashaSerebryanaya** [comment]
This issue was fixed starting from `v14.0.6-yb-2`.
