### ISSUE TITLE
[Unit Test] ThreadSanitizer check failed in AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14912]
Jira Link: [DB-4183](https://yugabyte.atlassian.net/browse/DB-4183)
### Description

ThreadSanitizer check failed in AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted for `2.17.0.0-b17`
Stacktrace: https://gist.github.com/Karvy-yb/056b51de4ea41f2ae96b2c7cc9c31a62

**Comment by arybochkin** [comment]
Hello @Karvy-yb, I do not see any failures from 09/15/2022 for master branch and from 11/08/2022 for 2.17.0 branch. Also I've run the test for tsan build with 1000 iteration on my dev server from 2.17.0 branch and it's had 100% passes, command:
`ybd tsan --cxx-test integration-tests_tablet-split-itest --gtest_filter AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted -n 1000`

Would you please try to reproduce the issue once again?

**Comment by rthallamko3** [comment]
detective [link](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=AutomaticTabletSplitExternalMiniClusterITest&fail_tag=all&name=CrashedSplitIsRestarted&platform=linux) looks clean

**Comment by rthallamko3** [comment]
recent run [history](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=AutomaticTabletSplitExternalMiniClusterITest&fail_tag=all&name=CrashedSplitIsRestarted&platform=linux) also looks good.

**Comment by rthallamko3** [comment]
Failed once in 2.17 branch, but the logs are gone.

`

Date / Time | Build Link | Error | Stack Trace | Test Run Command
-- | -- | -- | -- | --
11/08/2022 09:27 | centos-master-clang14-tsan/226/ |   | Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang14-tsan/226/artifact/build/tsan-clang14-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/AutomaticTabletSplitExternalMiniClusterITest_CrashedSplitIsRestarted.log    Unrecognized error type. Please see the error log for more information. | ybd tsan --cxx-test integration-tests_tablet-split-itest --gtest_filter AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted Copy

<br class="Apple-interchange-newline">Date / Time	Build Link	Error	Stack Trace	Test Run Command
11/08/2022 09:27	[centos-master-clang14-tsan/226/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang14-tsan/226/)		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang14-tsan/226/artifact/build/tsan-clang14-dynamic-ninja/yb-test-logs/tests-integration-tests__tablet-split-itest/AutomaticTabletSplitExternalMiniClusterITest_CrashedSplitIsRestarted.log



Unrecognized error type. Please see the error log for more information.


ybd tsan --cxx-test integration-tests_tablet-split-itest --gtest_filter AutomaticTabletSplitExternalMiniClusterITest.CrashedSplitIsRestarted`
