### ISSUE TITLE
[DocDB] Master not reading up-to-date contents when reading YSQL system tables.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#14926]
Jira Link: [DB-4194](https://yugabyte.atlassian.net/browse/DB-4194)
### Description

Master not reading up-to-date contents when reading YSQL system tables. There are several places in
master that directly read YSQL system tables, like reading tablespace info or catalog version. Just search for "sys_catalog_->Read" in catalog_manager.cc for some examples. While these are not exposed to users, it can provide an inconsistent view. 

Slack discussion: https://yugabyte.slack.com/archives/C03ULJYE0KG/p1663356281778909

**Comment by jasonyb** [comment]
This includes issue #5030.
