### ISSUE TITLE
Test: [DocDB] AutomaticTabletSplitITest.AutomaticTabletSplittingWaitsForAllPeersCompacted failures

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#14934]
Jira Link: [DB-4200](https://yugabyte.atlassian.net/browse/DB-4200)
### Description

Test intermittently fails with the same pattern

> ../../src/yb/integration-tests/tablet-split-itest.cc:1261 Failed Bad status: Timed out (yb/util/backoff_waiter.cc:50): Timed out waiting for FlushTables

Probably, the flush is happening before WRITE_OP was applied.

Source: https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=AutomaticTabletSplitITest&fail_tag=all&name=AutomaticTabletSplittingWaitsForAllPeersCompacted&num_commits=500&platform=all

**Comment by basavaraj29** [comment]
similar issue where `truncate` times out. there is a test in the description that reproduces the error consistently. 
https://github.com/yugabyte/yugabyte-db/issues/16610
