### ISSUE TITLE
[DocDB] Handle rolling restart situations when the gflag enable_wait_queues is modified

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#14935]
Jira Link: [DB-4201](https://yugabyte.atlassian.net/browse/DB-4201)
### Description

Right now, when the TServer gflag enable_wait_queues is modified from false -> true, some transactions might fail when a YSQL with the flag set to true sends an explicit row lock RPC with WAIT_BLOCK to a TServer still with the value set as false (and hence not having wait queues).

**Comment by rthallamko3** [comment]
@pkj415 , @robertsami , Can we scope the feature under AutoFlags to resolve this problem? cc @hari90
