### ISSUE TITLE
[DocDB] [Backup and Restore][Presplit-range tablet splitting] [DDL] [Intermittent] Rows missing in the backup and hence in the restored table

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14949]
Jira Link: [DB-4208](https://yugabyte.atlassian.net/browse/DB-4208)
### Description

1. Create a universe with packed columns disabled on 2.16.0 or latest master 2.17.1.0-b138 with tablet splitting enabled by default on the universe.
2. Create a range sharded table in database range_sharded_db
3. Trigger a workload to populate the table.
4. Trigger a rolling restart on the universe.
5. Ensure the workload continues
6. Once the gflag edit completes, stop the workload, note down the no. of rows and create a backup of the database- BKUP001;
7. Create a PITR snapshot schedule (Note- No restores executed, Adding this line for documentation sake)
8. Execute alter table DDLs' on the table and change the schema a bit- I added 5 new columns
9. Insert more data into the table
10. Create a backup of the database- BKUP002.
11. Restore the backup created pre-DDL execution - BKUP001 on to a new database (Restore on the same database is not possible owing to the PITR schedule)
12. Verify if the no. of rows restored from BKUP001 matches the count in step 6. 
**Issue:** I found that about 0.15 million rows were missing.
This issue does not reproduce easily. I have been able to reproduce it twice so far.

Reproduced in master 2.17.1.0-b138 once and in 2.16.0.0-b26 the second time

[yb-support-bundle-ksreenivasan-4131-repro-20221110114746.893-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/9980583/yb-support-bundle-ksreenivasan-4131-repro-20221110114746.893-logs.tar.gz)

**Comment by kripasreenivasan** [comment]
@lingamsandeep Logs from the repro created today- 
[yb-support-bundle-ksreenivasan-216-blocker-test-20221128104933.582-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/10102931/yb-support-bundle-ksreenivasan-216-blocker-test-20221128104933.582-logs.tar.gz)

**Comment by kripasreenivasan** [comment]
Issue seen another 2 times after what is reported in the main description.

**Comment by sanketkedia** [comment]
@kripasreenivasan do you have an automated test that can be run to repro? Or were you reproducing it manually?

Also, when the first backup was taken, were there any inflight transactions? Is stopping the workload equivalent to finishing all pending ops?
