### ISSUE TITLE
[YSQL] Allow to add negative cache entries in case of cache refresh

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#14962]
Jira Link: [DB-4215](https://yugabyte.atlassian.net/browse/DB-4215)
### Description

On cache refresh YB calls the YBPreloadRelCache function which loads lots of the caches. Some of this caches allows negative cache entry. But nowadays these entries can't be created as at cache load time it is not possible to predict which id will be used in future to read from this cache. As a result reading from this caches may lead to RPC calls to a master. Result of these RPC will always be empty.

To avoid such useless RPCs the `negative cache entries mechanism` should be enhanced (i.e. new mechanism should allow to "add" negative cache entries without knowing its ids at loading time).

**Comment by m-iancu** [comment]
This is now done under a tserver gflag `ysql_catalog_preload_additional_tables` (`false` by default).
Mainline commit: https://github.com/yugabyte/yugabyte-db/commit/9f6235004f459c43dafa18d38af4c582fafc2cb4.
