### ISSUE TITLE
[YSQL] New connections doesn't call the YBPreloadRelCache

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#14961]
Jira Link: [DB-4214](https://yugabyte.atlassian.net/browse/DB-4214)
### Description

In case of creating new connection the `YBPreloadRelCache` function is not called as relations cache is taken from a local file.
As a result multiple catalog caches are not filled with data. Reading data from this caches will cause individual RPCs to a master.

After solving the #10821 issue it is reasonable to call the `YBPreloadRelCache` function and ignore using local file for relation cache.

**Comment by m-iancu** [comment]
This is now done under a tserver gflag `ysql_catalog_preload_additional_tables` (`false` by default).
