### ISSUE TITLE
[xCluster] Add unit testing of existing xcluster functionality with changes for consistent transactions enabled

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#14989]
Jira Link: [DB-4238](https://yugabyte.atlassian.net/browse/DB-4238)
### Description

With flag `--enable_replicate_transaction_status_table=true`, ensure that there are no breakages to twodc-test and twodc_ysql-test

**Comment by hari90** [comment]
Not needed anymore. The flag has been removed
