### ISSUE TITLE
[DocDB] flaky test: YbAdminSnapshotScheduleTest.CacheRefreshOnNewConnection

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15006]
Jira Link: [DB-4249](https://yugabyte.atlassian.net/browse/DB-4249)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=YbAdminSnapshotScheduleTest&fail_tag=all&name=CacheRefreshOnNewConnection&platform=linux

Bunch of failures of this form, so maybe just overloaded server in the test
> ERROR: Already present: Duplicate request 8 from client 6307025e-51a7-4a50-8c09-de3a13eb8609 (min running 8))

**Comment by sanketkedia** [comment]
Based on slack conversation seems like caused due to https://github.com/yugabyte/yugabyte-db/commit/5a0915512bf05f96cf49d170aee4eca863afb320

**Comment by Huqicheng** [comment]
Look at the detective trend: https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=YbAdminSnapshotScheduleTest&name=CacheRefreshOnNewConnection

The test is passing all builds after the fix is in.

Also need to back port this to 2.16 2.17.0
