### ISSUE TITLE
[DocDB] flaky test: RaftConsensusITest.TestAddRemoveNonVoter

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15008]
Jira Link: [DB-4251](https://yugabyte.atlassian.net/browse/DB-4251)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=RaftConsensusITest&fail_tag=all&name=TestAddRemoveNonVoter&platform=linux

> Bad status: Timed out (yb/integration-tests/cluster_itest_util.cc:887): Replica TabletServer: 9998809bbedb49639c64f4fff896d0d9, Rpc address: host: "127.127.5.0" port: 17693 is not leader after waiting for 10.000s: Not found (yb/integration-tests/cluster_itest_util.cc:848): Error connecting to replica: Timed out (yb/rpc/outbound_call.cc:546): Call timed out before sending

Seems to be failing for a while in centos-clang15-debug, but more recently started being flaky in a couple of other build types.

**Comment by Huqicheng** [comment]
seems the test itself is falky caused by delayed stepdown
