### ISSUE TITLE
change default behavior of num_reserved_small_compaction_threads 

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#1500]
By default, the gflag `num_reserved_small_compaction_threads` has a -1 value.
```
DEFINE_int32(num_reserved_small_compaction_threads, -1, "Number of reserved small compaction "
             "threads. It allows splitting small vs. large compactions.");
```

And this later gets essentially interpreted to being 'total compaction threads - 1'
```
  if (result.num_reserved_small_compaction_threads == -1 ||
        result.num_reserved_small_compaction_threads >= result.base_background_compactions) {
    result.num_reserved_small_compaction_threads = result.base_background_compactions - 1;
  }
```

Reserving all but 1 compactions threads for small compactions and only 1 thread for large compactions doesn't seem to be a good default (especially for write intensive phase of workloads or write heavy workloads). 

*Proposal:*

We should change the interpretation of the -1 setting to reserve only 1 of the compactions threads for smaller compactions. So something like:

```
  if (result.num_reserved_small_compaction_threads == -1 ||
        result.num_reserved_small_compaction_threads >= result.base_background_compactions) {
   if (result.base_background_compactions > 1) {
      result.num_reserved_small_compaction_threads = 1;
   } else {
      result.num_reserved_small_compaction_threads = 0;
   }
 }

```

**Comment by bmatican** [comment]
Passing this to @spolitov as we had the internal meeting on automatically handling compactions better. Can see if this is worth as a short term stop gap. cc @kmuthukk

**Comment by spolitov** [comment]
This flag is useless in the case of multiple RocksDB instances.
For instance, we have 3 compaction threads. 2 reserved for small compactions and 1 for large.
So we will have a thread pool of 3 threads and each RocksDB would schedule at most 1 large compaction. But since we have multiple RocksDB instances, three of them could schedule large compaction. So all threads would perform large compactions.

We discussed the new design for the compactions thread pool. And it will be implemented in the near future.

**Comment by kmuthukk** [comment]
I don't believe the current scheme works the way you describe @spolitov. At most one thread would perform the large compaction is my understanding (of this work --https://github.com/YugaByte/yugabyte-db/commit/dde2ecd5ddf4b01879e32f033e0a80e37e18341a).

While the threadpool is common, there are 2 queues - one for large and one for small compactions; and the implementation keeps track of ensuring that the specified number of threads reserved for small compactions is indeed respected.

**Comment by spolitov** [comment]
As I could see those queues are per RocksDB instance. 
So I don't see a mechanism that could prevent 2 large compactions from being submitted into thread pool by different RocksDB instances.
And thread pool operates only on tasks, so it doesn't even know whether it is compaction or not.

**Comment by kmuthukk** [comment]
While there are multiple instances of RocksDB, they share some things -- e.g., a common block cache, and common queues (a small and large queue) for compactions.

**Comment by spolitov** [comment]
This feature is not required anymore since we have a priority thread pool with a pause for compactions.
