### ISSUE TITLE
[YugabyteD] [QA] UI URL doesn't work with full path to the page and gives 404

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#15013]
### Description

If we give full path of the page we get 404 error

For example, 
Works -> http://127.0.0.1:15433/

Doesn't work -> http://127.0.0.1:15433/cluster/tabOverview 
We get 404 page not found.

**Comment by nchandrappa** [comment]
Code changes landed to support providing the full URL path.
