### ISSUE TITLE
[DocDB] log-dump should be able to print out decoded UUIDs

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#15024]
Jira Link: [DB-4259](https://yugabyte.atlassian.net/browse/DB-4259)
### Description

We currently cannot print out decoded UUIDs (txn-id) and hybrid times for operations in log-dump

`./build/latest/bin/log-dump {path/to/walfile} --print_entries=pb`

produces output like:
```
29.3884@6827544771715375113	REPLICATE UPDATE_TRANSACTION_OP
	id { term: 29 index: 3884 } hybrid_time: 6827544771715375113 op_type: UPDATE_TRANSACTION_OP committed_op_id { term: 29 index: 3884 } monotonic_counter: 0 transaction_state { transaction_id: "1\366*\022\215\221@\361\205m\315\317\322\306Vg" status: APPLYING tablets: "abcdefghij..." commit_hybrid_time: 6827544771460087808 sealed: false aborted { } }
```

**Comment by ttyusupov** [comment]
`log-dump -print_entries=pb <path-to-WAL-file>` will print entries in protobuf text format

**Comment by yamen-haddad** [comment]
As @ttyusupov said, when using the option `--print_entries=pb`, the WAL entry is being printed using the `DebugString()` of `google::protobuf::Message` class. Which prints the object without decoding the fields of type `bytes` and the `transaction_id ` is of type `bytes` and hence it is printed this way.
In this case, maybe we cannot use the `DebugString()` of protobuf and instead have our own implementation for it which should traverse recursively all the fields/subfields in the `LogEntryPB ` object. The problem with that solution is that it will be coupled with the current structure of `LogEntryPB` message and any change on the message definition might cause the new function to break. I am not sure if this is the best way to move forward or you propose something else?
cc @rthallamko3

**Comment by yamen-haddad** [comment]
So what @rthallamko3 and I concluded is that if we want to print the UUIDs in human readable format even in the case of choosing   `--print_entries=pb` we need to traverse ourselves the fields of the `entry` object and decode the UUIDs which takes us back to almost doing the same thing as with the option `--print_entries=decoded` (with the slight difference that maybe one field is not printed in the decoded option).
@robertsami : So my question is, why do we have these two different printing options? Maybe there is some context in the past that might be useful to know.
Thanks for your feedback.

**Comment by robertsami** [comment]
@yamen-haddad i think you're absolutely right -- there wouldn't be a strong reason to modify the behavior with `--print_entries=pb` since it will be effecitvely the same as `--print_entries=decoded` at that point. the additional field that is printed is the operation type, which is already implied by the name of the field that is displayed when using `--print_entries=decoded` (e.g. if `type: REPLICATE`, then the decoded message will output the contents of the `replicate` field)

so i think we can close this!
