### ISSUE TITLE
[xCluster] Automatically synchronize oid

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#15035]
Jira Link: [DB-4270](https://yugabyte.atlassian.net/browse/DB-4270)
### Description

As we have just seen in https://phabricator.dev.yugabyte.com/D21141 and previously in https://github.com/yugabyte/yugabyte-db/issues/13217 oid has to be set manually in our tests when using xcluster and creating a custom type. This appears to be a known limitation.

It seems kind of intended, but I’d consider it a QoL improvement if the oid was synchronized automatically for xcluster, so that we as testers, and other users too, don't have to keep it in mind and set it manually.

**Comment by lingamsandeep** [comment]
Replicating DDL from source to target cluster would alleviate this class of problems. We'll revisit this as part of that.
