### ISSUE TITLE
[DocDB][xCluster] ERROR:  invalid internal value for enum at Target side

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15038]
Jira Link: [DB-4272](https://yugabyte.atlassian.net/browse/DB-4272)
### Description

**Version**: **2.17.0.0-b22**

**Steps**:
1. Create database, enum type and table at both Source and Target sides.
```
create database db1;
\c db1;
SET yb_binary_restore = true;
SELECT pg_catalog.binary_upgrade_set_next_pg_type_oid('16492'::pg_catalog.oid);
SELECT pg_catalog.binary_upgrade_set_next_array_pg_type_oid('16493'::pg_catalog.oid);
CREATE TYPE e_details AS ENUM ('Email', 'Sms', 'Phone');
SET yb_binary_restore =false;
create table test(id int, name text, enum_c e_details);
```
2. Setup Replication from Source to Target.
3. At Source:
`insert into test values(1,'name-1','Email');`

4. At Target:
```
select * from test;
ERROR:  invalid internal value for enum: 16504
```

**Comment by lingamsandeep** [comment]
@Arjun-yb - Can you check the output of "`select * from pg_enum;`" The enum typeid should match on both source and target. You should see this issue only if that happens. I could not repro it with the above steps because they match unless some new types get created that used up the OID that the source is using.

**Comment by def-** [comment]
I'm seeing the same failure in https://phabricator.dev.yugabyte.com/D21141 when trying to use the same oid for creating a type on source and target side. Is that wrong?

**Comment by Arjun-yb** [comment]
@lingamsandeep I observed this issue even though the ENUM typeids are matching.
At Source:
```
demo2=# select * from pg_enum;
 enumtypid | enumsortorder | enumlabel
-----------+---------------+-----------
     17000 |             1 | Email
     17000 |             2 | Sms
     17000 |             3 | Phone
(3 rows)

demo2=# insert into test values(1,'name-1','Email');
INSERT 0 1
demo2=# select * from test;
 id |  name  | enum_c
----+--------+--------
  1 | name-1 | Email
```

At Target:
```
demo2=#  select * from pg_enum;
 enumtypid | enumsortorder | enumlabel
-----------+---------------+-----------
     17000 |             1 | Email
     17000 |             2 | Sms
     17000 |             3 | Phone
(3 rows)

demo2=# select * from test;
ERROR:  invalid internal value for enum: 16390
```

**Comment by lingamsandeep** [comment]
It is complaining about the enum 16390. Which enum is this ? Does that match between source/target ? @Arjun-yb could you check that ?

`ERROR:  invalid internal value for enum: 16390`

**Comment by Arjun-yb** [comment]
@lingamsandeep, validated enum at both sides, sometimes ENUM value differs at both sides and throws above error, it is not consistent.
