### ISSUE TITLE
[DDL + YSQL] Timed out waiting for all pending operations to complete, FATAL seen

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15053]
Jira Link: [DB-4281](https://yugabyte.atlassian.net/browse/DB-4281)
### Description

Packed columns toggle off and on testcase on master (2.17.1.0-b204) issue

FATALs seen is different than one seen in 2.16 (https://github.com/yugabyte/yugabyte-db/issues/15051 )

`F1116 11:50:54.526480 27612 operation_driver.cc:398] T 1add15f89bb5464cbf472dfd1fc65808 P 5ab9b2ded1d2457dbda84d0d8c19e7ed S RD-P Ts { physical: 1668599394522426 } kChangeMetadata (0x000055f41c7d50e0): Apply failed: Timed out (yb/util/operation_counter.cc:166): Timed out waiting for all pending operations to complete`

Workload which was run:
`java -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.8.23.jar --workload SqlDataLoadWithDDL --uuid 3c26ecdb-c0ab-465a-bb41-a066b425fdcb --create_table_name test_packed_columns_sql_efcce6 --num_writes -1 --num_threads_write 20 --num_reads -1 --num_threads_read 20 --num_unique_keys 10000000000 --num_value_columns 100 --batch_size 10 --num_indexes 2 --use_unique_index true --ddl_operations DELETE_ROW,UPDATE_ROW,DELETE_ROWS,UPDATE_ROWS,ADD_COLUMN,DROP_COLUMN --uuid_marker 90c42f17-a58c-45c6-869b-75c6c0fac226 --nodes 172.151.20.125:5433,172.151.20.237:5433,172.151.27.174:5433`

Links:
[run_report](http://stress.dev.yugabyte.com/stress_test/0c8faf3a-3e3c-4de0-b69b-c4b381905c17)
[fatal_log](http://stress.dev.yugabyte.com/files/get?name=e5120a7e-a013-4ba8-9172-9c4f11ad5724-yb-tserver.ip-172-151-20-237.us-west-2.compute.internal.yugabyte.log.FATAL.20221116-115054.23494)

If these are unreachable by the time of access, downloading and attaching universe logs complete here as well:
[Universe_logs_and_test_logs.zip](https://github.com/yugabyte/yugabyte-db/files/10030123/Universe_logs_and_test_logs.zip)

![Profile](https://user-images.githubusercontent.com/109518123/202415168-d1867797-8467-44a6-b518-f3c18a2c9631.png)

[DB-4281]: https://yugabyte.atlassian.net/browse/DB-4281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
cc: @kripasreenivasan

**Comment by shamanthchandra-yb** [comment]
After discussion with @bmatican concluded its not to do with packed columns, and its generic ALTER TABLE (DDLs). Hence changed title. To be linked with other issues known prior.

**Comment by qvad** [comment]
Reproduced w/o packed columns on our YSQL + PITR tests

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , Is this issue still relevant?

**Comment by shamanthchandra-yb** [comment]
@rthallamko3 I haven't seen this again. Good to close.
I believe this is because of fix https://phabricator.dev.yugabyte.com/D22005 ([slack](https://yugabyte.slack.com/archives/C03ULJYE0KG/p1674221143370009))

Few more issues we can see similar to this, which are still in open.
https://github.com/yugabyte/yugabyte-db/issues/12926
https://github.com/yugabyte/yugabyte-db/issues/15220

**Comment by rthallamko3** [comment]
Thanks @shamanthchandra-yb , The other bug is still open as we are waiting for the backports to stable branch to complete.
