### ISSUE TITLE
[Packed columns + YSQL] Failed to write a batch with 0 operations into RocksDB: Corruption (yb/tablet/tablet_metadata.cc:269) FATALs seen in toggling off and on with tserver restart and manual compaction

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15051]
Jira Link: [DB-4279](https://yugabyte.atlassian.net/browse/DB-4279)
### Description

Tried in 2.16.0.0-b46. The testcase case was configured to run for 4 hours and this issue was seen after about 3 and half hours.

Below is the FATAL log:

`
F1116 18:11:46.422570  5951 tablet.cc:1406] T b253bb4c591c4b57b422d94bd359cb0f P cf99f07cac3a4b04b8fd4fb953cdf28a: Failed to write a batch with 0 operations into RocksDB: Corruption (yb/tablet/tablet_metadata.cc:269): Cannot find packing for table: 000033e6000030008000000000004000, schema version: 15
`

Run: [run link](http://stress.dev.yugabyte.com/stress_test/0c8a6dab-c810-4e94-ac2c-f8c9cb42e621)

fatal logs can be seen here: [http://stress.dev.yugabyte.com/files/get?name=bfba3ca8-f462-4665-94b0-a2e6f9f41ef0-yb-t[…].compute.internal.yugabyte.log.FATAL.20221116-181146.4144](http://stress.dev.yugabyte.com/files/get?name=bfba3ca8-f462-4665-94b0-a2e6f9f41ef0-yb-tserver.ip-172-151-19-135.us-west-2.compute.internal.yugabyte.log.FATAL.20221116-181146.4144)

Here is steps sequence:
<img width="1582" alt="Screen Shot 2022-11-16 at 2 01 05 PM" src="https://user-images.githubusercontent.com/109518123/202409537-31f6091b-3d49-4f84-93c9-a81c2de74db2.png">

Below is the indicated graph, where I have selected only time frame when issue was seen i.e. when FATALs were found. We can see.
We are checking fatals and core in regular intervals (in each iteration).
So, it might be anytime between 2 checks. We have tserver restart multiple times, compaction is done, disable packed row and did rolling restart as well.

![Screenshot 2022-11-17 at 12 35 20 AM](https://user-images.githubusercontent.com/109518123/202409637-f0bc20e9-a8c2-4055-8282-62f5f8a7a304.png)

![Screenshot 2022-11-17 at 12 33 08 AM](https://user-images.githubusercontent.com/109518123/202409649-41c01a9b-2f40-4939-a827-ce2d65c239b0.png)

Workload is:

`
java -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.8.23.jar --workload SqlDataLoadWithDDL --uuid be0bf2b2-9115-4ab4-995e-5b1224568587 --create_table_name test_packed_columns_sql_03ef29 --num_writes -1 --num_threads_write 20 --num_reads -1 --num_threads_read 20 --num_unique_keys 10000000000 --num_value_columns 100 --batch_size 10 --num_indexes 2 --use_unique_index true --ddl_operations DELETE_ROW,UPDATE_ROW,DELETE_ROWS,UPDATE_ROWS,ADD_COLUMN,DROP_COLUMN --uuid_marker 00186a7a-6e91-4690-acfc-ce14ff7eaadb --nodes 172.151.19.135:5433,172.151.16.85:5433,172.151.17.197:5433
`

All logs: Universe logs and Framework logs: 
[172.151.17.197.zip](https://github.com/yugabyte/yugabyte-db/files/10029979/172.151.17.197.zip)
[172.151.19.135.zip](https://github.com/yugabyte/yugabyte-db/files/10029985/172.151.19.135.zip)
[172.151.16.85.zip](https://github.com/yugabyte/yugabyte-db/files/10029977/172.151.16.85.zip)

[test.log](https://github.com/yugabyte/yugabyte-db/files/10029983/test.log)

**Comment by shamanthchandra-yb** [comment]
cc: @kripasreenivasan

**Comment by bmatican** [comment]
Some further debugging. Fatal details: http://stress.dev.yugabyte.com/files/get?name=80ba832d-d554-4742-853f-56cb04abfc38-yb-tserver.FATAL.details.2022-11-16T18_11_46.pid4144.txt, seems to point to the intents -> regular apply path.
```
F20221116 18:11:46 ../../src/yb/tablet/tablet.cc:1406] T b253bb4c591c4b57b422d94bd359cb0f P cf99f07cac3a4b04b8fd4fb953cdf28a: Failed to write a batch with 0 operations into RocksDB: Corruption (yb/tablet/tablet_metadata.cc:269): Cannot find packing for table: 000033e6000030008000000000004000, schema version: 15
    @     0x56212ea06447  google::LogMessage::SendToLog()
    @     0x56212ea0738d  google::LogMessage::Flush()
    @     0x56212ea07899  google::LogMessageFatal::~LogMessageFatal()
    @     0x56212f5aa694  yb::tablet::Tablet::WriteToRocksDB()
    @     0x56212f5a68b7  yb::tablet::Tablet::ApplyIntents()
    @     0x56212f5a74f2  yb::tablet::Tablet::ApplyIntents()
    @     0x56212f656134  yb::tablet::TransactionParticipant::Impl::ProcessReplicated()
    @     0x56212f58d851  yb::tablet::UpdateTxnOperation::DoReplicated()
    @     0x56212f5820cf  yb::tablet::Operation::Replicated()
    @     0x56212f583d45  yb::tablet::OperationDriver::ReplicationFinished()
    @     0x56212ee0c91a  yb::consensus::ConsensusRound::NotifyReplicationFinished()
    @     0x56212ee5636b  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @     0x56212ee55819  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x56212ee3dd0a  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x56212ee22b07  yb::consensus::RaftConsensus::Update()
    @     0x56212f7e922c  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x56212ee92f82  std::__1::__function::__func<>::operator()()
    @     0x56212ee93a0f  yb::consensus::ConsensusServiceIf::Handle()
    @     0x56212f4ef42e  yb::rpc::ServicePoolImpl::Handle()
    @     0x56212f43553f  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x56212f4fdf93  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x56212fb3114f  yb::Thread::SuperviseThread()
    @     0x7f8e1e8bc694  start_thread
    @     0x7f8e1edbe41d  __clone
```

The test was crash looping with this though, but the stack is not from the bootstrap path, so would this be the follower side apply, of an actual in flight RPC? Not sure I understand how this would fail on the RPC apply, but not on the bootstrap apply, after restart.

**Comment by shamanthchandra-yb** [comment]
Still saw this issue on **2.17.1.0-b357**

Hence reopening. 

```
F1222 09:55:06.115607 30960 tablet.cc:1426] T ed418c41e1854713b2cc2fe3ca8f01de P 4e5c01904f0b4182b2562c60c33f6ba5: Failed to write a batch with 0 operations into RocksDB: Corruption (yb/tablet/tablet_metadata.cc:283): Cannot find packing for table: 000033e6000030008000000000004000, schema version: 21 
```

**Comment by sharkberto** [comment]
Awaiting also 2.16 backport, next release from that branch is 2.16.1.0. 2.16.0 branch is for patch release 2.16.0.1 only. @spolitov @rthallamko3

**Comment by rthallamko3** [comment]
@shamanthchandra-yb  has validated the fix on master, we had 2 runs of 12+ hours of stress tests. Closing this.

**Comment by shamanthchandra-yb** [comment]
Observed this on 2.16.8.0-b14. Hence reopening.[http://stress.dev.yugabyte.com/stress_test/0b5b9115-c9af-4003-ad37-eef4b7077574]( http://stress.dev.yugabyte.com/stress_test/0b5b9115-c9af-4003-ad37-eef4b7077574)

**Comment by rthallamko3** [comment]
```
F20231007 09:58:14 ../../src/yb/tablet/tablet.cc:1463] T 296401a9578a470c8a22f93f56ab011b P 42671850e1a84e8885457d3d5a8167fc: Failed to write a batch with 0 operations into RocksDB: Corruption (yb/tablet/tablet_metadata.cc:293): Cannot find packing for table: 000033e9000030008000000000004000, schema version: 51
    @     0x55dc2248c3f7  google::LogMessage::SendToLog()
    @     0x55dc2248d33d  google::LogMessage::Flush()
    @     0x55dc2248d849  google::LogMessageFatal::~LogMessageFatal()
    @     0x55dc23061483  yb::tablet::Tablet::WriteToRocksDB()
    @     0x55dc2305d68e  yb::tablet::Tablet::ApplyIntents()
    @     0x55dc2305e302  yb::tablet::Tablet::ApplyIntents()
    @     0x55dc23100ad4  yb::tablet::TransactionParticipant::Impl::ProcessReplicated()
    @     0x55dc23041ea1  yb::tablet::UpdateTxnOperation::DoReplicated()
    @     0x55dc2303523f  yb::tablet::Operation::Replicated()
    @     0x55dc23036ec5  yb::tablet::OperationDriver::ReplicationFinished()
    @     0x55dc228a3cea  yb::consensus::ConsensusRound::NotifyReplicationFinished()
    @     0x55dc228f0898  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @     0x55dc228efd59  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x55dc228d7faa  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x55dc228bbea9  yb::consensus::RaftConsensus::Update()
    @     0x55dc232b547c  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x55dc2292e1a2  std::__1::__function::__func<>::operator()()
    @     0x55dc2292ec2f  yb::consensus::ConsensusServiceIf::Handle()
    @     0x55dc22fa20aa  yb::rpc::ServicePoolImpl::Handle()
    @     0x55dc22ee5f9f  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x55dc22fb0c23  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x55dc23600d7c  yb::Thread::SuperviseThread()
    @     0x7f34cf249694  start_thread
    @     0x7f34cf74b41d  __clone

```

**Comment by bmatican** [comment]
Closing this back, filed #19507 to track the newly found issue.
