### ISSUE TITLE
[CDCSDK] Differentiate between Update and Insert records in case of packed row

### ISSUE THREAD

**Issue by adithya-yb** [yugabyte/yugabyte-db#15062]
In cdc, we decode intents to form records, and we have made an assumption that if an intent's type is packed column (docdb::ValueEntryType::kPackedRow), it came from an insert operation. But some of the test cases failing are because we are updating all non-key columns of a table with packed row enable, and we wrongly assume it is an insert operation. We essentially need to distinguish between intent's belonging to an update operation (all non-key columns updated) vs intents belonging to an insert operation, in case of packed rows .
How we find out weather an intent is of type packed row is:
we decode the intent, from which we get a DecodedIntentValue object. And on DecodedIntentValue.body we call
docdb::DecodeValueEntryType("DecodedIntentValue.body")
 which will be equal to docdb::ValueEntryType::kPackedRow
And in non packed row intents, we use the below logic to distinguish between update and insert records:
value_type = docdb::DecodeValueEntryType("DecodedIntentValue.body")

if (column_id_opt && column_id_opt->type() == docdb::KeyEntryType::kSystemColumnId &&
            value_type == docdb::ValueEntryType::kNullLow) {
    // We know the record is of insert type   
}  else {
    // We know the records is of update type
}

**Comment by sureshdash2022-yb** [comment]
We have fixed this issue and landed it
