### ISSUE TITLE
[Docs] Provide similar version selector behavior like PostgreSQL.org

### ISSUE THREAD

**Issue by lonedevel** [yugabyte/yugabyte-db#15079]
### Description

For the YDB documentation, the version dropdown resets to the top level page which sometimes makes it hard to find the specific topic for a given version when switching between versions.  It it possible to keep the topic static when switching the version?

For example, with the documents page on PostgreSQL.org you can pick a given topic, say (https://www.postgresql.org/docs/15/performance-tips.html) and then a the top change the version to adjust the content for that version without having the page reset to the top level page.

**Comment by ddhodge** [comment]
See also #10790

**Comment by polarweasel** [comment]
The site works like this now.
