### ISSUE TITLE
[YSQL] Add PG backend memory usage values to pg_stat_activity view

### ISSUE THREAD

**Issue by rachelphan1508** [yugabyte/yugabyte-db#15085]
Jira Link: [DB-4301](https://yugabyte.atlassian.net/browse/DB-4301)
### Description

#14066 introduced two new functions yb_pg_stat_get_backend_allocated_mem_bytes(beid) and yb_pg_stat_get_backend_rss_mem_bytes(beid) that return backend allocated memory and rss memory usage accordingly.

We need to create a new view yb_pg_stat_activity which includes pg_stat_activity columns and 2 new columns yb_allocated_mem_bytes and yb_rss_mem_bytes whose values are retrieved from the 2 functions mentioned above. We can do this after #12307 is resolved.

[DB-4301]: https://yugabyte.atlassian.net/browse/DB-4301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vrajat** [comment]
The following view adds the two columns to `pg_stat_activity`


```
CREATE VIEW yb_stat_activity AS
    SELECT
            pg.datid,
            pg.datname,
            pg.pid,
            pg.usesysid,
            pg.usename,
            pg.application_name,
            pg.client_addr,
            pg.client_hostname,
            pg.client_port,
            pg.backend_start,
            pg.xact_start,
            pg.query_start,
            pg.state_change,
            pg.wait_event_type,
            pg.wait_event,
            pg.state,
            pg.backend_xid,
            pg.backend_xmin,
            pg.query,
            pg.backend_type,
            yb.rss_mem_bytes,
            yb.allocated_mem_bytes
    FROM pg_stat_activity AS pg
            JOIN (SELECT pg_stat_get_backend_pid(s.backendid) AS pid,
                    yb_pg_stat_get_backend_rss_mem_bytes(s.backendid) as rss_mem_bytes,
                    yb_pg_stat_get_backend_allocated_mem_bytes(s.backendid) as allocated_mem_bytes
                  FROM (SELECT pg_stat_get_backend_idset() AS backendid) AS s
                ) as yb on yb.pid=pg.pid
```
