### ISSUE TITLE
[Docs] YB-Anywhere Document changing password

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#15099]
### Description

We don't document (that I could find) how to change user passwords or super-admin passwords.

We have a support article on how to change superadmin passwords if it's been forgotten but the "I know my password" steps should be documented in core documentation.

Ideally I think that the superuser should be able to change non-super user passwords also - not sure if that's a feature but if so we should document it too

**Comment by lizayugabyte** [comment]
@tylarb I'm not sure I have access to support articles (have never seen them). Could you, please, include a link?

**Comment by lizayugabyte** [comment]
@tylarb In YBA, the user can change password from his profile:

![Screen Shot 2022-11-23 at 10 45 52 AM](https://user-images.githubusercontent.com/77016159/203589791-e7633d9e-4032-4724-b0d3-aad7340a9a42.png)

This seems pretty intuitive; it's unlikely that someone would need detailed instruction on how to do it. But it's mentioned at the end of https://docs.yugabyte.com/preview/yugabyte-platform/configure-yugabyte-platform/create-admin-user/

**Comment by tylarb** [comment]
@lizayugabyte   - I see

Here's the support article - https://support.yugabyte.com/hc/en-us/articles/6889156888717-How-to-reset-password-for-yb-anywhere-Yugaware-platform-superuser-account

---

It would be great to have a sub-header "changing password" at the bottom of the page you linked - I did find that page, but did not realize there were any instructions about changing password as they aren't really prominent. I might expect password changing (for super user or non-superusers) would be under "administer"

**Comment by lizayugabyte** [comment]
Thanks, @tylarb. I'll add a subsection at the end
