### ISSUE TITLE
Bootstrapping failed for tserver on 0.9.10.0-b8

### ISSUE THREAD

**Issue by mchang31415** [YugaByte/yugabyte-db#151]
```W0410 22:53:10.696588 243181 ts_tablet_manager.cc:1475] T 558385cc942c422ea12ddd47708ff1ff P be24348f79724d9ca3d931722eb7232a: Remote bootstrap: Unable to fetch data from remote peer 47d0d16e227949daa155af9defd86306 ({ip}:{port}): Invalid argument (yb/rpc/connection.cc:409): Unable to download ROCKSDB_FILE file /home/y/var/data/yb-data/tserver/data/rocksdb/table-a709a47a0a5143bcbddff1c8a76cacda/tablet-558385cc942c422ea12ddd47708ff1ff/038599.sst.sblock.0: Unable to fetch data from remote: Command is greater than read buffer: 266583439```

One tserver stuck trying to bootstrap tablets after rolling restart, left with only one tablet out of its expected 12.
Tablet(s) stuck in copying state

```
redis | 558385cc942c422ea12ddd47708ff1ff | hash_split: [5632, 6144) | TABLET_DATA_COPYING | 0B
```

**Comment by mbautin** [comment]
Fixed by 8ccc0420216ff653abcae978174b89eb501e769d
