### ISSUE TITLE
[Docs][yugabyted] update the yugabyted reference section to reflect the latest features.

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#15105]
### Description

We have made several changes to the yugabyted commands as part of the 2.17.0 release, we will have to update the yugabyted reference section to cover the latest features and command updates.

- yugabyted secure phase 2
- yugabyted data at rest encryption
- updates to command flags

**Comment by gargsans-yb** [comment]
Docs changes landed.
