### ISSUE TITLE
Auto-analyze: ANALYZE service logic / RPC definitions

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#15110]
Jira Link: [DB-4320](https://yugabyte.atlassian.net/browse/DB-4320)
### Description

This item tracks implementing a stateful ANALYZE service and associated RPC definitions. This service will receive table mutation counts from tservers. It will maintain aggregate mutation counts per table. When a table's mutation counts exceed the analyze threshold for that table, this service will trigger analyze asynchronously on some node's YSQL.

[DB-4320]: https://yugabyte.atlassian.net/browse/DB-4320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
This part has been implemented.
