### ISSUE TITLE
Create a kubernetes provider, doesn't copy the kubeconfig to the zone level

### ISSUE THREAD

**Issue by ramkumarvs** [YugaByte/yugabyte-db#1511]
When you create a kubernetes provider, we default the provider level kubeconfig to the zone level, but this default logic is not working properly. We seem to be copying the pull secret instead of the actual kubeconfig.

Repro Steps:
- Create a provider with kubeconfig uploaded only at the provider level and zone level just enter overrides and other fields.
- When creating universe you will have issue stating the kubeconfig is invalid, because what is actually copied is the pull secret.

**Comment by yb-andrew** [comment]
Merged to master 9e199b1b9e85a84b3084985f124f8c1e75704113
