### ISSUE TITLE
After back to back successful PITR restores, unable to connect to the database on any node of the universe via ysqlsh shell with error "server closed the connection unexpectedly This probably means the server terminated abnormally before or while processi

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#15125]
Jira Link: [DB-4330](https://yugabyte.atlassian.net/browse/DB-4330)
### Description

**[Packed Columns] [DDLs][PITR][Tablet Splitting][Materialized Views]** scenario attempted on **2.16.0.0-b56**

- On a cluster with automatic tablet splitting, YSQL packed columns enabled, create a database, tables inside the database(I used (~/share/schema.sql) and populate the tables with 0.5 million rows. Create materialized views of each table and refresh the views..
- Create a snapshot schedule
- Attempt a series of DDLs and DMLs'. I added 4 new text columns to the tables, and add another 0.3 million rows, Refresh materialized views noting down the timestamp between each of these activities.
- Execute three point in time restores to the timestamps noted in the above steps, ensure successful restore after each execution.
**Observation:**
After the 3rd PITR, I'm unable to connect to the database from any one of the nodes in the cluster. 
```
yugabyte=# \l
                                   List of databases
      Name       |  Owner   | Encoding | Collate |    Ctype    |   Access privileges
-----------------+----------+----------+---------+-------------+-----------------------
 db_001          | yugabyte | UTF8     | C       | en_US.UTF-8 |
 postgres        | postgres | UTF8     | C       | en_US.UTF-8 |
 system_platform | postgres | UTF8     | C       | en_US.UTF-8 |
 template0       | postgres | UTF8     | C       | en_US.UTF-8 | =c/postgres          +
                 |          |          |         |             | postgres=CTc/postgres
 template1       | postgres | UTF8     | C       | en_US.UTF-8 | =c/postgres          +
                 |          |          |         |             | postgres=CTc/postgres
 yugabyte        | postgres | UTF8     | C       | en_US.UTF-8 |
(6 rows)

yugabyte=# \c db_001 ;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Previous connection kept
```

Universe logs- 
[yb-support-bundle-ksreenivasan-14486-WithCL-20221123103239.350-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/10074793/yb-support-bundle-ksreenivasan-14486-WithCL-20221123103239.350-logs.tar.gz)

Universe- https://10.9.139.108/universes/17c20b88-76ee-426b-86a5-2a3395e12a89/overview 

CC: @sanketkedia

**Comment by lingamsandeep** [comment]
I am unable to repro this despite multiple retries. Resolving this bug.
