### ISSUE TITLE
[DocDB][PITR] PITR restore times out when used with Materialized view + Indexes + Alter

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#15139]
Jira Link: [DB-4337](https://yugabyte.atlassian.net/browse/DB-4337)
### Description

**Description**
The 2nd PITR restore times out when 100K+ rows are present, although no such error is observed with small amount of data(ex >=1000 rows)
Version: 2.17.0.0-b24
`Error running restore_snapshot_schedule: Timed out (yb/rpc/outbound_call.cc:486): Failed to restore snapshot from schedule: 03e207c6-397e-4de0-80e5-3fb770d84724: RestoreSnapshotSchedule RPC (request call id 2) to 172.151.30.100:7100 timed out after 60.000s`

**Steps**:
        1) Create a  table
        2) Create index and  Materialized view on the table
        3) Insert 100k rows and refresh the view
        4) Note down the time(1)
        5) Insert rows 100k rows and refresh the view
        6) Note down the time(2)
        7) Drop the Materialized view
        8) Perform a PITR at the noted time (2)->(Success)
        9) Perform a PITR at the noted time (1) [[------------------------>**Failure**]]

**Note**: No error is observed in 2.15.1.0-b1 and below version.
Logs:
[172.151.30.100-logs.tar.gz.zip](https://github.com/yugabyte/yugabyte-db/files/10083324/172.151.30.100-logs.tar.gz.zip)

[DB-4337]: https://yugabyte.atlassian.net/browse/DB-4337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@shishir2001-yb is this test automated? is it still failing? is it failing consistently?
