### ISSUE TITLE
[CDCSDK] Flaky testcase CDCSDKYsql.ModifyPrimaryKeyBeforeImage

### ISSUE THREAD

**Issue by sureshdash2022-yb** [yugabyte/yugabyte-db#15137]
Jira Link: [DB-4606](https://yugabyte.atlassian.net/browse/DB-4606)
https://yugabyte.slack.com/archives/C01NT25S79A/p1668707420369459

**Comment by mbautin** [comment]
This is still happening now. That the test passed locally does not mean it is not "a code or test issue".

**Comment by mbautin** [comment]
A few different tests are failing in ASAN build type with errors similar to this.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/552936/209453291-942c837f-82af-4620-a09c-bd65014c7c4a.png">

**Comment by mbautin** [comment]
A few different tests are failing in ASAN build type with errors similar to this.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/552936/209453291-942c837f-82af-4620-a09c-bd65014c7c4a.png">

**Comment by sureshdash2022-yb** [comment]
Hi @mbautin @suranjan I will check it now
