### ISSUE TITLE
[DocDB][xCluster][DR] Unable to find intent: 210D032380016619F217E14D803DCB (HT{ physical: 1669213354843826 w: 16 }) for 78D7F124A996BF480582CF0E4DF5B4AB91DC7FFE99E60DE81EB27FC234(Corruption (yb/common/doc_hybrid_time.cc:117): Negative decoded_shifted_wri

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15140]
Jira Link: [DB-4338](https://yugabyte.atlassian.net/browse/DB-4338)
### Description

**Version**: `2.17.1.0-b238`

While validating DR scenario,
Observed errors in **yb-tserver.ERROR** log file
```
E1123 14:22:36.849362 21658 rocksdb_writer.cc:514] Unable to find intent: 210D032380016619F217E14D803DCB (HT{ physical: 1669213354843826 w: 16 }) for 78D7F124A996BF480582CF0E4DF5B4AB91DC7FFE99E60DE81EB27FC234(Corruption (yb/common/doc_hybrid_time.cc:117): Negative decoded_shifted_write_id: -95726481. Was trying to decode from: F5B4AB91DC7FFE99E60DE81EB27FC234)
E1123 14:22:36.854964 21658 rocksdb_writer.cc:514] Unable to find intent: 210D032380016619F217E14D803DCB (HT{ physical: 1669213354843826 w: 16 }) for 7836DFD5BAA2B149AD9DF4286CA7E19089DC7FFE99E60DE81EB27FC234(Corruption (yb/util/checked_narrow_cast.h:29): Bad narrow cast -102537 < 0)

E1123 14:33:09.656775 22414 twodc_output_client.cc:705] Error while applying replicated record: Timed out (yb/rpc/rpc.cc:222): UpdateTransaction: tablet_id: "08e8953ac42b4de4b4d4f488f981ea2e" state { transaction_id: "\026X%#\224\300F\333\261/Q\244\377\271\334\344" status: CREATED external_hybrid_time: 6837098102206623744 } propagated_hybrid_time: 6837100476554870784 is_external: true, retrier: { task_id: -1 state: kRunning deadline: 1701.205s } passed its deadline 1701.205s (passed: 6.120s): Remote error (yb/rpc/local_call.cc:117): Local call error: Service unavailable (yb/rpc/service_pool.cc:227): UpdateTransaction request on yb.tserver.TabletServerService from 0.0.0.0:0 dropped due to backpressure. The service queue is full, it has 5000 items. (rpc error 4), consumer tablet: 08e8953ac42b4de4b4d4f488f981ea2e
```

At Source:
```
demo=# select count(*) from employees;
 count
--------
 286582
```

At Target:
```
demo=# select count(*) from employees;
 count
-------
 17266
(1 row)

demo=# select count(*) from employees;
ERROR: Query error: Call timed out before sending
demo=# select count(*) from employees;
ERROR: Query error: GetTransactionStatus RPC (request call id 1370327) to A.B.C.D:9100 timed out after 0.068s
```
and
```
get_xcluster_estimated_data_loss
[
  {
    "namespace_id": "00000000000000000000000000000001",
    "data_loss_sec": "293"
  }
]
```
Observed 
1. Healthcheck errors at Target side(YSQLSH connectivity issues)
2. And replication was too slow.

**Comment by lingamsandeep** [comment]
A variant of this that we are seeing is: 

F20221201 07:44:06 ../../src/yb/tablet/tablet.cc:1409] T 47467da5ab1e4e929ae91a013e930693 P e1858277d0e4467999a9b772a8cad126: Failed to write a batch with 0 operations into RocksDB: Corruption (yb/docdb/rocksdb_writer.cc:534): Unexpected write id. Expected: 4994, found: 3971, raw value: 782FEA9531B572408393AE72142764A1327700000F8358: 3971 vs 4994
    @     0x5599e7752a47  google::LogMessage::SendToLog()
    @     0x5599e775398d  google::LogMessage::Flush()
    @     0x5599e7754009  google::LogMessageFatal::~LogMessageFatal()
    @     0x5599e86ff374  yb::tablet::Tablet::WriteToRocksDB()
    @     0x5599e86fb5c7  yb::tablet::Tablet::ApplyIntents()
    @     0x5599e86fc1b2  yb::tablet::Tablet::ApplyIntents()
    @     0x5599e87ae79f  yb::tablet::TransactionParticipant::Impl::ProcessReplicated()
    @     0x5599e86e14ff  yb::tablet::UpdateTxnOperation::DoReplicated()
    @     0x5599e86d5e70  yb::tablet::Operation::Replicated()
    @     0x5599e86d7df5  yb::tablet::OperationDriver::ReplicationFinished()
    @     0x5599e7b8b49a  yb::consensus::ConsensusRound::NotifyReplicationFinished()
    @     0x5599e7bd351b  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @     0x5599e7bd29e9  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x5599e7bb1284  yb::consensus::RaftConsensus::UpdateMajorityReplicated()
    @     0x5599e7b826b1  yb::consensus::PeerMessageQueue::NotifyObserversOfMajorityReplOpChangeTask()
    @     0x5599e8caf792  yb::ThreadPool::DispatchThread()
    @     0x5599e8caba1f  yb::Thread::SuperviseThread()
    @     0x7f03c9b69694  start_thread
    @     0x7f03ca06b41d  __clone


**Deterministic repro for this issue:**

./bin/ysqlsh -h 127.0.0.1 -c "insert into ordering_test values(generate_series(1,5000));"
./bin/ysqlsh -h 127.0.0.1 -c "delete from ordering_test"
