### ISSUE TITLE
[DocDB] Optimize wait for IsCreateTableDone

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#15146]
Jira Link: [DB-4344](https://yugabyte.atlassian.net/browse/DB-4344)
### Description

As part of create table experiments, it was observed that with the default exponential backoff policy and jitter values, we are waiting for unnecessary long periods for create table operation to complete.
This task is to optimize the backoff policy by removing jitter and starting backoff with a much lower value like 2ms for create tables.

**Comment by arpang** [comment]
Closing as there's any issue for the same task: https://github.com/yugabyte/yugabyte-db/issues/15060
