### ISSUE TITLE
[Automatic Tablet Splitting][Backup And Restore][Materialized view] Failed to restore database containing table, materialized views in a universe with automatic tablet splitting 

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#15143]
Jira Link: [DB-4342](https://yugabyte.atlassian.net/browse/DB-4342)
### Description

Build: 2.16.0.0-b64
- Deterministic repro available with automation script `TestSelfUniverseBackupWithMatViewAutomaticTSCompressionAndPackedColumns`

**Note:** Though YSQL packed columns is enabled in the above scenario, it has no bearing on the end result. If YSQL packed columns is disabled, we see the same bug manifest. Adding it just for documentation sake.

**Steps for manual repro:**

Create a universe with automatic tablet splitting, RPC Compression(3), YSQL packed columns enabled.
Source universe flags:
```
   master_flags = {
                    "enable_automatic_tablet_splitting": "true",
                    "tablet_split_low_phase_size_threshold_bytes": "13421",
                    "tablet_split_low_phase_shard_count_per_node": "16",
                    "ysql_enable_packed_row": "true"
                }
            tserver_flags = {
                    "yb_num_shards_per_tserver": "1",
                    "ysql_enable_packed_row": "true",
                    "enable_stream_compression": "true",
                    "stream_compression_algo": "3"
                }
```

1. Create a database, create a table in the database- Note that the table has 13 data types including sequences, enums, user defined data types
2. Insert 5k rows in the table
3. Create a materialized view of the table
4. Insert another 5k rows
5. Refresh materialized view
6. Create a backup of the database created in step 1
7. Drop materialized view
8. Restore dropped materialized view in the same universe
**Issue:**
Restore fails.

Logs- 
[2.16.0.0_testselfuniversebackupwithmatviewautomatictscompressionandpackedcolumns-aws-rf3_20221125_103922.zip](https://github.com/yugabyte/yugabyte-db/files/10092334/2.16.0.0_testselfuniversebackupwithmatviewautomatictscompressionandpackedcolumns-aws-rf3_20221125_103922.zip)

**Comment by yamen-haddad** [comment]
@kripasreenivasan I need more clarification about step 8.
Are we restoring the backup to a new database in the same cluster or we are restoring to the same database where the materialized view was deleted?

**Comment by bmatican** [comment]
@kripasreenivasan as per your note above, this test is automated, correct? is it deterministically failing?

**Comment by rajapriya371** [comment]
Observing this issue on 2.21.0.0-b186, 2.19.3.0-b140, 2.16.9.0-b29.

**Comment by Arjun-yb** [comment]
Fixed test (restore was happening to the same database) and now it is working fine
