### ISSUE TITLE
unknown field "metadata" in io.k8s.api.core.v1.Container

### ISSUE THREAD

**Issue by eskuai** [YugaByte/yugabyte-db#1515]
[root@k8s-master helm]# helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
[root@k8s-master helm]#

[root@k8s-master helm]#  helm install yugabyte -f expose-all.yaml --namespace yb-demo --name yb-demo --wait
Error: validation failed: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "metadata" in io.k8s.api.core.v1.Container
[root@k8s-master helm]#

--  installation for k8s plain, no gke no aws, failed to created pvc using the standard association labels

**Comment by Arnav15** [comment]
https://github.com/YugaByte/charts/pull/9 Addressed and fixes the issue.
