### ISSUE TITLE
[DocDB] Stress tests run into FATAL: Check failed: !is_registered Attempted to destruct a registered LogAnchor

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15166]
Jira Link: [DB-4362](https://yugabyte.atlassian.net/browse/DB-4362)
### Description

![Profile (1)](https://user-images.githubusercontent.com/109518123/204468150-597140f9-3a2b-4d8d-9f9a-3b63842790c5.png)

Found below issue in FATAL log:
```
Log file created at: 2022/11/29 06:24:40
Current UTC time: 2022/11/29 06:24:40
Running on machine: ip-172-151-26-227.us-west-2.compute.internal
Application fingerprint: version 2.17.1.0 build 257 revision c7674e8645a6b7c1736439e808b461f63da19c13 build_type RELEASE built at 27 Nov 2022 05:06:51 UTC
Node information: { hostname: 'ip-172-151-26-227.us-west-2.compute.internal', rpc_ip: '172.151.26.227', webserver_ip: '172.151.26.227', uuid: 'ace2c21ac502444591576119f6c7dd63' }
Running duration (h:mm:ss): 0:08:26
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1129 06:24:40.601609  2080 log_anchor_registry.cc:157] Check failed: !is_registered Attempted to destruct a registered LogAnchor
```

```
F20221129 06:24:40 ../../src/yb/consensus/log_anchor_registry.cc:157] Check failed: !is_registered Attempted to destruct a registered LogAnchor
    @     0x55a092b98ff7  google::LogMessage::SendToLog()
    @     0x55a092b99f3d  google::LogMessage::Flush()
    @     0x55a092b9a5b9  google::LogMessageFatal::~LogMessageFatal()
    @     0x55a093078c50  yb::log::LogAnchor::~LogAnchor()
    @     0x55a093b492be  yb::tablet::Tablet::~Tablet()
    @     0x55a093d3170c  yb::tserver::(anonymous namespace)::ReadQuery::~ReadQuery()
    @     0x55a093d2a9c7  yb::tserver::PerformRead()
    @     0x55a093d720b3  yb::tserver::TabletServiceImpl::Read()
    @     0x55a093e7007b  std::__1::__function::__func<>::operator()()
    @     0x55a093e71b2f  yb::tserver::TabletServerServiceIf::Handle()
    @     0x55a093a87ece  yb::rpc::ServicePoolImpl::Handle()
    @     0x55a0939c9a6f  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x55a093a96983  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x55a0940f839f  yb::Thread::SuperviseThread()
    @     0x7f5a9fab1694  start_thread
    @     0x7f5a9ffb341d  __clone
```

Universe logs: 
[OSoxzJSIVv.zip](https://github.com/yugabyte/yugabyte-db/files/10110807/OSoxzJSIVv.zip)

[DB-4362]: https://yugabyte.atlassian.net/browse/DB-4362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by VijayShinde** [comment]
Hi,
any fixes releases for this issue?

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , I updated the title to reflect the issue. Based on offline conversations with @ttyusupov , this is an issue with the lifetime of the read query and tablet shutdown (Chances of this is higher with automatic tablet splitting). This is not an issue with PackedRow feature per se. I have moved it to the Automatic-Tablet-Splitting epic.

**Comment by rthallamko3** [comment]
@VijayShinde , Which release did you find the issue in?

**Comment by VijayShinde** [comment]
Hi @rthallamko3 ,

I am using yugabyte-2.15.3.2 version.

**Comment by rthallamko3** [comment]
@VijayShinde , We have identified the cause for this and are actively working on it. cc @ttyusupov , as it might need to be backported to older stable releases.

**Comment by rthallamko3** [comment]
We will consider backports to 2.16 and 2.14 if the conflicts are not too many.
