### ISSUE TITLE
[YSQL] Check constraints might be violated with concurrent transactions

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#15196]
Jira Link: [DB-4381](https://yugabyte.atlassian.net/browse/DB-4381)
### Description

Currently, we don't take shared "read" locks on the data that is read as part of CHECK constraints. This results in a scenario where -

(1) Two concurrent transactions might update different columns that are part of a CHECK constraint such that the constraints is violated and
(2) Both might commit because they check that the constraint is satisfied on an inconsistent view of the data - new data written by that transaction and older data for the other columns as per the snapshot being used for the transaction.

The fix is to take shared "read" locks that block concurrent writing similar to as done in reads in `SERIALIZABLE` isolation level. This is also similar to the weaker "FOR KEY SHARE" row-level lock taken for foreign key checks to ensure that the pk isn't deleted/updated.

```
CREATE TABLE products (
 product_no integer,
 name text,
 price numeric,
 CHECK (price > 0),
 discounted_price numeric,
 CHECK (discounted_price > 0),
 CHECK (price > discounted_price)
);

insert into products values (1, 'oats', 10, 1);

TX #1                                TX #2

begin;                               begin;

update products 
set price = 3 
where product_no = 1;

                                     update products 
                                     set discounted_price = 4 
                                     where product_no = 1;

commit;
                                     commit;
```

Both transactions commit successfully violating the  check (price > discounted_price) constraint:
yugabyte=# select * from products;

```
 product_no | name | price | discounted_price 
------------+------+-------+------------------
          1 | oats |     3 |                4
          
```

The fact that no shared read lock is taken can be confirmed by visiting the /intentsdb page on a debug build with the Tserver gflag `enable_intentsdb_page=true`.

[DB-4381]: https://yugabyte.atlassian.net/browse/DB-4381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
currently blocked on an issue with some CDC-related behavior. cc @tvesely to link that here
