### ISSUE TITLE
[YSQL] Add gflags to control beta features: colocated DB and tablegroup

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#15192]
Jira Link: [DB-4378](https://yugabyte.atlassian.net/browse/DB-4378)
### Description

Beta features like colocated DB and tablegroup are not controlled by gflag.
As a result, they can be accidentally used by users.
We should add gflags for them.

**Comment by tverona1** [comment]
Resolving this as won't fix, since colocation is now GA.
