### ISSUE TITLE
[DocDB] Expose metrics for master load balancing operations

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#15218]
Jira Link: [DB-4398](https://yugabyte.atlassian.net/browse/DB-4398)
### Description

We would like to see more prometheus metrics for the master load balancing operations that show what's happening internally

1. Rate of different kinds of operations being performed by the master cluster load balancer
2. Count of imbalanced tablets of different kinds (leader tablets, tablet counts)
3. Any load balancing errors
4. Ability to detect a "stuck" load balancing operation

This would help both with display in graphs and with alerting

**Comment by MDK8888** [comment]
Hey, I would love to take this on!
