### ISSUE TITLE
Yugaware run sample apps line for k8s shows incorrect namespace for multi-AZ deployment

### ISSUE THREAD

**Issue by ramkumarvs** [YugaByte/yugabyte-db#1521]
The run sample apps model needs to show the correct namespace for multi-az deployments
A multi-AZ universe was created in YW 1.2.7.0-b7 and the user attempted to run the sample apps command line string as projected:

```
kubectl run --image=yugabytedb/yb-sample-apps yb-sample-apps -n yb-dev-yugabyte-multi-az – --workload CassandraKeyValue --nodes yb-tserver-0.yb-tservers.yb-dev-yugabyte-multi-az-us-central1-b.svc.cluster.local:9042,yb-tserver-0.yb-tservers.yb-dev-yugabyte-multi-az-us-central1-a.svc.cluster.local:9042,yb-tserver-0.yb-tservers.yb-dev-yugabyte-multi-az-us-central1-c.svc.cluster.local:9042
```
Error:
```
Error from server (NotFound): namespaces "yb-dev-yugabyte-multi-az" not found
```

Looks like YW should either create a namespace without the region name or select the first one from the list. E.g. yb-dev-yugabyte-multi-az-us-central1-a.

Options

**Comment by yb-andrew** [comment]
Fixed in 5651f2b6231d1a8c83a615e6d2bc308350a65f8a
