### ISSUE TITLE
[YSQL] flaky test: CreateTableITest.TableColocationRemoteBootstrapTest	

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15231]
Jira Link: [DB-4407](https://yugabyte.atlassian.net/browse/DB-4407)
### Description

Should be disabled in TSAN, as per most of our YSQL tests.

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CreateTableITest&fail_tag=all&name=TableColocationRemoteBootstrapTest&platform=linux

**Comment by yifanguan** [comment]
Closed with 77738f3.
