### ISSUE TITLE
[CDC] Provide interface to set the WAL retention time

### ISSUE THREAD

**Issue by hectorgcr** [YugaByte/yugabyte-db#1524]
Currently the WAL retention time is being controlled by FLAGS_log_min_seconds_to_retain, but we need a way to change this for each table without restarting the tservers.

**Comment by amitanandaiyer** [comment]
src/yb/consensus/log.cc:DEFINE_int32(log_min_seconds_to_retain, 300,
src/yb/consensus/log.cc:TAG_FLAG(log_min_seconds_to_retain, runtime);
src/yb/consensus/log.cc:TAG_FLAG(log_min_seconds_to_retain, advanced);

Couldn't you update this on the fly using ts-cli?

**Comment by hectorgcr** [comment]
@amitanandaiyer I should have been more explicit, but we want this retention to be different for each table
