### ISSUE TITLE
[DocDB][xCluster-Atomicity] Replication is not happened fully at once(all changes inside transactions) and got 'Transaction in wrong state during heartbeat: COMMITTED' in log file

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15248]
Jira Link: [DB-4419](https://yugabyte.atlassian.net/browse/DB-4419)
### Description

**Steps:**

1. Create 2 universes(Source and Target) with Turn ON the GFlag `enable_replicate_transaction_status_table` on master of both universes
2. Create database and table at both sides
```
create table table1(id int primary key, description text);
create table table2(id int primary key, description text);
```
3. Setup replication from **Source to Target**
4. Change the xCluster role at Target
`yb-admin -master_addresses <master-address> change_xcluster_role STANDBY`
5. Load some data(75K)(**transactional workload**) at **source** and validate at both sides
6. Setup replication from **Target to Source**
7. Load some data(25K)(**transactional workload**) at **target** and validate

**Observations**
1. Replication(from Target to Source) is not happened fully at once(partially happened) and non-replicated rows are being replicating very slowly.
2. Observed below errors in **yb-tserver.ERROR** log file
`E1207 11:00:05.599262 25562 twodc_output_client.cc:714] Error while applying replicated record: Timed out (yb/rpc/rpc.cc:222): UpdateTransaction: tablet_id: "37a21accd59143f4b2b902a0a0178cef" state { transaction_id: "\005\035\210\321\242MCU\202\215\"Ba\026\230\225" status: CREATED external_hybrid_time: 6841995484586176512 } propagated_hybrid_time: 6842002535231602688 is_external: true, retrier: { task_id: -1 state: kRunning deadline: 10688.896s } passed its deadline 10688.896s (passed: 30.396s): Illegal state (yb/tablet/transaction_coordinator.cc:653): Transaction in wrong state during heartbeat: COMMITTED, consumer tablet: 37a21accd59143f4b2b902a0a0178cef
`

**Comment by lingamsandeep** [comment]
Fixed by 64a7b3aa96894604689ed7f7a1f74e52078b1c57.
