### ISSUE TITLE
[YSQL] If multiple schemas have the same table name, master UI cannot distinguish between those and only shows one table

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1525]
```
create table public.foo(a int primary key);
create schema schema1;
create table schema1.foo(a int primary key, b int);
```

http://127.0.0.1:7000/tables will only show one table foo.

**Comment by bmatican** [comment]
Wanted to get @Marionumber1 started on something. @ndeodhar suggested this might be a good one, but @m-iancu was mentioning that schemas might be a bit tricky to handle, as that info might not be properly exposed atm...

In the meantime, I think a similar vein worth of issue happens on the TS UI (see http://localhost:9000/tablets) if we have 2 tables with same name, it is hard to tell which tablet belong to which table, as the keyspace is not reported there.

**Comment by ndeodhar** [comment]
@bmatican @m-iancu There are two parts to this:
(1) Making sure that we show all tables. In such a case, both tables should show up on master UI page but with different table IDs.
(2) Adding schema information to be able to easily identify between tables with same name but different schemas.

Right now, we don't even do (1) which is wrong. We should at least show both tables and UUID column will be different for the two. Clicking on the table will show more information like schema, tablets etc. for each.
Showing both tables should be a fairly straightforward fix in `master-path-handlers.cc`.

**Comment by YourTechBud** [comment]
@ndeodhar displaying the schema information won't help a lot. In my use case, two schemas can have the same table with the same fields. Maybe we can show a tables `oid` for the table `pg_class` on the ui?
