### ISSUE TITLE
[DocDB] Enable pg isolation regress tests which exercise wait queue based locking

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#15267]
Jira Link: [DB-4430](https://yugabyte.atlassian.net/browse/DB-4430)
### Description

Pulling out a separate issue from https://github.com/yugabyte/yugabyte-db/issues/12637 to track specifically those tests which exercise and depend on wait queue based locking

insert-conflict-do-nothing-2

[DB-4430]: https://yugabyte.atlassian.net/browse/DB-4430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
@robertsami @rthallamko3 I'm assuming the new test doesn't need to be backported to 2.20/2024.1?
