### ISSUE TITLE
[YW] Change the metric displayed for Remote Bootstraps in YugaWare

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1527]
At the moment we display all the retries for pending remote bootstraps and as a result the metric is not very useful. @hectorgcr , please list the metric that should be used instead.

**Comment by yb-andrew** [comment]
Fixed in 83ee7882d13538307ecc7d879408c2566bb97759

**Comment by rao-vasireddy** [comment]
Please review and see if we are using the correct metric now

**Comment by yb-andrew** [comment]
Talked to Hector a month ago and he said he does not know why the metric was not working. Closing this issue.
