### ISSUE TITLE
[YSQL] Premature return in PG_TRY block in relcache.c

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#15286]
Jira Link: [DB-4444](https://yugabyte.atlassian.net/browse/DB-4444)
### Description

We return from that function within a try block [here](https://github.com/yugabyte/yugabyte-db/blob/51bf3e2ce0407067ac61a5571b0f7392b2edfd51/src/postgres/src/backend/utils/cache/relcache.c#L1907) before we hit PG_END_TRY()  where we’d restore the previous jump buffer, mistakenly leaving PG_exception_stack  with a bad jump buffer pointer.

Through tracing through the debugger we can see that `PG_exception_stack` changes in value before and after this PG_TRY block.

**Comment by m-iancu** [comment]
re-opening to track backports to 2.16 and 2.14.
