### ISSUE TITLE
[YSQL] SELECT Support in PostgreSQL

### ISSUE THREAD

**Issue by hlliu1994** [YugaByte/yugabyte-db#1531]
postgres=# select * from test1 where id in (1232,12321,1,4343,3536,64564,23424,53453,63453,643535,23424,2524,2345);
ERROR:  Snapshot too old: Snapshot too old. Read point: { physical: 1560268996924365 }, earliest read time allowed: { physical: 1560269384896049 }, delta (usec): 387971684
Time: 398010.983 ms (06:38.011)
postgres=# 

maybe ,it doesn't support in clause

**Comment by kmuthukk** [comment]
hi @hlliu1994 - can you also share which version of YB you are running?

**Comment by kmuthukk** [comment]
hi @hlliu1994 - can you also share your table schema please (the CREATE TABLE statement and any indexes)? Thanks a lot.

**Comment by ndeodhar** [comment]
Hi @hlliu1994, we do support IN clause and this may be something else. Can you give some more details on your setup?
1. Is this a local cluster?
2. What is the replication factor?
3. Any error or warnings in the logs? Log files can be found at `$data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO`, `$data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.WARNING` and `$data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.ERROR`

**Comment by rkarthik007** [comment]
Hi @hlliu1994 - closing this issue for now, please feel free to reopen if something does not work for you.
