### ISSUE TITLE
[YugabyteD] [QA] Cluster creation not giving any errors if we pass wrong location syntax. (flag --cloud_location)

### ISSUE THREAD

**Issue by ankit-yb** [yugabyte/yugabyte-db#15331]
### Description
version: 2.16.0.0-b90
Start a node with --cloud_location=aws.us-east+us-east.2a (wrong syntax) but it successfully started.
Correct way -> --cloud_location=aws.us-east.us-east-2a

**Comment by ShikharSahay** [comment]
Currently, we only perform a length check on the cloud location. As part of the migration of the yugabyted codebase to Go, we will introduce a syntax check for the cloud location.
