### ISSUE TITLE
[k8s][YSQL] PgSQL proxy may not need full hostname

### ISSUE THREAD

**Issue by m-iancu** [YugaByte/yugabyte-db#1533]
Currently this hits the 64 char limitations on some clusters (if names are very long).
We should investigate if we can replace the following line to use some local IP:
https://github.com/YugaByte/yugabyte-db/blob/master/cloud/kubernetes/helm/yugabyte/templates/service.yaml#L243

**Comment by Arnav15** [comment]
Addressed in https://github.com/YugaByte/charts/pull/5
