### ISSUE TITLE
[YugabyteD] [QA] Multi region/zone can't be created if master_rpc_port is overwritten on 1st node (masters are not reachable)

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#15334]
### Description

**Use below config:**
```
{
    "tserver_webserver_port": 9005,
    "webserver_port": 7205,
    "use_cassandra_authentication": false,
    "master_webserver_port": 7005,
    "ycql_port": 9045,
    "tserver_flags": "",
    "tserver_rpc_port": 9105,
    "master_rpc_port": 7105,
    "ysql_enable_auth": false,
    "callhome": true,
    "master_flags": "",
    "ysql_port": 5435,
    "initial_scripts_dir": ""
}
```

**Start 1 node with this config:**
`cd /home/centos/ce_tests; ./yugabyte-*/bin/yugabyted start --advertise_address=10.152.0.215 --base_dir=$HOME/node1 --cloud_location=aws.us-east.us-east-1a --config=$HOME/yugabyted_test.conf --data_dir=$HOME/data1 --log_dir=$HOME/log1 --ui=True
`

**Start 2nd node and join to first node:**
`./yugabyte-*/bin/yugabyted start --advertise_address=10.152.0.222 --base_dir=$HOME/node2 --cloud_location=aws.us-east.us-east-2a --config=$HOME/yugabyted_test.conf --data_dir=$HOME/data2 --join=10.152.0.215 --log_dir=$HOME/log2 --ui=True
`

We will get below error:
`ERROR:master at the join ip provided is not reachable.`

We are getting this error because we are trying to check master (in condition for secure/insecure nodes) and the port for that is hardcoded. We need to change that to support dynamic nature.

**Question:**
Should all nodes joining a cluster use same Config (with updating ports) or different configs are allowed?

**Comment by ShikharSahay** [comment]
Code changes landed.
