### ISSUE TITLE
[YSQL] Umbrella issue to track format-related things before YSQL on-disk format is finalized

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1535]
- Ordering of NULLs vs. regular values
- String collation
- Locale-related issues

**Comment by kmuthukk** [comment]
Adding things that I can remember:

* Handling of NULL in unique indexes (?)
* Transactional DDL

**Comment by rkarthik007** [comment]
Folks - can this issue now be closed?

**Comment by m-iancu** [comment]
Closing now as the format was finalized back around 2.0 release.
