### ISSUE TITLE
337 YSQL tables are displayed on a newly created cluster

### ISSUE THREAD

**Issue by pallavisreerama** [YugaByte/yugabyte-db#1537]
On a newly created cluster with YSQL enabled, 337 tables tables are created. It is displaying the system tables that should not be visible to the user

![image](https://user-images.githubusercontent.com/36684364/59314649-15676e00-8c6b-11e9-836c-dc684c566e16.png)

**Comment by bmatican** [comment]
@m-iancu any input on best way to filter these out? Trying to figure out if we can do it in YW, after getting the list of tables, or in YB, when responding to a `ListTables` RPC.

For doing it at the higher level, we have template0, template1 and postgres as databases/keyspaces, but I think we default to `postgres` as the DB to drop the default session in, so we probably don't want to just filter these out in the UI. I notice there's basically `pg_*` and `sql_*` tables, but is there any limitation that the user cannot create tables with those prefixes?

**Comment by m-iancu** [comment]
_[Discussed offline with @bmatican but posting conclusion here]_
`ListTables` request proto has a field `relation_type_filter` that can be used to select which of system tables, user tables, and indexes to return. In theory, excluding system tables (setting only the other two) should be enough. (That would also mean no extra sys-table filtering needs to be done on the UI side for YCQL either).

**Comment by WesleyW** [comment]
<img width="2017" alt="Screen Shot 2019-07-01 at 12 10 48 PM" src="https://user-images.githubusercontent.com/2791412/60460740-6c70bb00-9bf9-11e9-8ddb-84f657770498.png">
