### ISSUE TITLE
[CDC + Tablet Splitting] CDC has stopped with tablet splitting ON: tablet = null (Intermittent) (Seen on both 2.16 and master)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15385]
Jira Link: [DB-4521](https://yugabyte.atlassian.net/browse/DB-4521)
### Description

Here is the history of it:

![Screenshot 2022-12-20 at 6 29 35 PM](https://user-images.githubusercontent.com/109518123/208673228-5302105b-8e5e-4480-b000-af2bfd88bdcd.png)

I see:

`
WARN   YugabyteDB|db_cdc|streaming|0  Error while trying to get the changes from the server for tablet: f106995178b84101affeac575a09a08c; will attempt retry 1 of 10 after 60000 milli-seconds. Exception message: Too many attempts: YRpc(method=GetTabletListToPollForCDC, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=58)   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
`

http://stress.dev.yugabyte.com/stress_test/04c58770-92ec-45bb-9f7a-baa5e41789f2

![Profile (1)](https://user-images.githubusercontent.com/109518123/208673383-b6d46c73-63c1-4e75-8ec1-512a6913c769.png)

[DB-4521]: https://yugabyte.atlassian.net/browse/DB-4521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
Seen on 2.16 with latest connector, hence modified title.

**Comment by vaibhav-yb** [comment]
On investigation, it is found that the flow is going something like this:

1. Connector detects a tablet split
2. `TABLET_SPLIT` error is handled gracefully
3. Connector calls `GetTabletListToPollForCDC` on the parent tablet to get the children
4. The RPC in step 3 times out with the `TIMED_OUT` error
5. `YBClient` then internally tries to handle the `TIMED_OUT` error and sends the RPC to the tserver again, which then fails with the error `NOT_FOUND` and a message saying the the tablet has been deleted.
6. The `NOT_FOUND` error in step 5 causes the tests to fail ultimately.

**Note:** The error can't be reproduced in a test locally as of now, it is only observed in the LRU runs.
