### ISSUE TITLE
[Docs] IP allow lists

### ISSUE THREAD

**Issue by tichimura** [yugabyte/yugabyte-db#15380]
### Issues
Could not find the feature as documentation in IP allow list

### Background

HI team, 
It seems the feature of `Enable public access` is documented but is not implemented in cloud.yugabyte.com.
https://github.com/yugabyte/yugabyte-db/commit/2bd3100f9a1c85bb7b7f3112ec4323abf876677e

I wonder it will be released soon, but could you please check for it?
https://docs.yugabyte.com/preview/yugabyte-cloud/cloud-secure-clusters/add-connections/#enabling-public-access

### Expectation

Removed or updated the doc once the feature is implemented.

**Comment by ddorian** [comment]
@tichimura can you update the status of this?

**Comment by tichimura** [comment]
@ddorian sorry for late, as it has been implemented, let me close it.

**Comment by tichimura** [comment]
close
