### ISSUE TITLE
[Docs] hide H4 in SQL statement reference page right-side TOCs

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#15408]
### Description

All pages under /api/ysql/the-sql-language/statements/ should have H4s hidden in their right nav.

Add the following to the **end of the frontmatter**:

```yaml
rightNav:
  hideH4: true
```

**Comment by ddorian** [comment]
cc @ddhodge @aishwarya24 

Is this issue still relevant?

**Comment by aishwarya24** [comment]
> ```yaml
> rightNav:
>   hideH4: true
> ```

Yes @ddorian , it is relevant. If you look at the index on the right nav of a page , it breaks down the items from the Syntax section which gets hidden if we add the suggested content to the frontmatter.
