### ISSUE TITLE
[docs] Restructure, fix formatting, and do an editorial overhaul of the new troubleshooting page for YBA k8s installation

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#15419]
### Description

This page was created by dev. It needed too many non-content-related changes, so I'm creating this ticket to fix everything once the main PR (https://github.com/yugabyte/yugabyte-db/pull/15395) gets merged.

**Comment by baba230896** [comment]
@lizayugabyte Please refer the point 5 from the following [comment](https://github.com/yugabyte/yugabyte-db/pull/15395#pullrequestreview-1268750643) during updating the troubleshooting doc. 
cc @bhavin192
