### ISSUE TITLE
[YSQL] insert into temp table in FUNCTION body causes assertion fail

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#1541]
The following commands 

```
CREATE TEMP TABLE sometable(f1 int);

CREATE FUNCTION voidtest3(a int) RETURNS VOID LANGUAGE SQL AS
$$ INSERT INTO sometable VALUES(a + 1) $$;
SELECT voidtest3(17);
```

causes assertion fail

```
node-1/disk-1/yb-data/tserver/logs/postgresql-2019-06-12_222334.log:TRAP: FailedAssertion("!(!((allPgXact[proc->pgprocno].xid) != ((TransactionId) 0)))", File: "../../../../../../../src/postgres/src/backend/storage/ipc/procarray.c", Line: 441)
```

**Comment by d-uspenskiy** [comment]
Root cause of the problem is this line

https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/backend/parser/analyze.c#L121

when value is inserted into `temp` table directly condition is `true` and `SetTxnWithPGRel();` is called

but in case function is called instead (i.e. statement is `SELECT voidtest3(17)`) condition is `false`, `SetTnxWithPGRel();` is not called, and flag `isYBTxnWithPostgresRel` is not set

Later without this flag `InvalidTransactionId` will be returned here

https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/backend/access/transam/xact.c#L1158

**Comment by jj-kim** [comment]
To clarify, nothing gets inserted into the table.  The expected behavior is
```
postgres=# SELECT * FROM sometable;
 f1
----
 18
(1 row)
```
whereas the actual behavior is
```
postgres=# SELECT * FROM sometable;
 f1
----
(0 rows)
```
I haven't been able to reproduce the assertion fail.

**Comment by jj-kim** [comment]
I get the assertion fail on CentOS debug build.  I do not get the assertion fail on macOS release build nor on CentOS release build.  The actual behavior I describe in the previous comment comes from macOS release build.
