### ISSUE TITLE
[YSQL] Support for Foreign Keys on partitioned tables

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#15424]
Jira Link: [DB-4542](https://yugabyte.atlassian.net/browse/DB-4542)
### Description

YugabyteDB is based off of PostgreSQL 11.2 where there is no support for foreign keys on partitioned tables. As a result this functionality has not yet been added to YugabyteDB. I have had numerous asks for this feature from users of row-level geo-partitioning. All requests so far have been from users migrating existing applications. As such there is no way to develop around the limitation. We currently have two avenues around this lack of support:

1. We have created a function, using triggers, that accomplishes FK like behavior, however it is not recommended for production. It also cannot work with third party tools as they will not be referencing the function, and users have not access to the tools to change that. This function has not been performance tested at scale. 
2. If you are referencing a partitioned table from another partitioned table you can set up the FK relation on a partition by partition level. Meaning instead of a single FK from referencing table to referenced table, you will have separate FKs from each referencing partition to referenced partition. 

Neither option above is ideal as it requires additional action/changes by the user.

**Comment by arpang** [comment]
Support added in feddbabf1c87f8c1337cde01f3226933dac68d48.
