### ISSUE TITLE
[YSQL] Upgrading FROM 2.0.11.0_23 TO 2.16.0.1-b1, 2.16.1.0-b20 and latest master(2.17.1.0)) is generating core files, crashing master processes, cutting ysql, ycql connectivity

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#15443]
Jira Link: [DB-4554](https://yugabyte.atlassian.net/browse/DB-4554)
### Description

- Create a universe in using build 2.0.11.0-b23 
- Run sample app workloads in the universe
- Upgrade to 2.16.0.1-b1 or master 2.17.1.0-b381 
**Issue:** This generates core files in the universe, crashes master process in 2/3 nodes, ysql, ycql connectivity is broken in all 3 nodes.
Note: This test last passed in  2.17.1.0-b275)
A deterministic repro is available with the automation test testupgrade-aws-rf3-upgrade-2.0.11.0_23
Logs:
[2.16.0.1_testupgrade-aws-rf3-upgrade-2.0.11.0_23_20221227_085035.zip](https://github.com/yugabyte/yugabyte-db/files/10307460/2.16.0.1_testupgrade-aws-rf3-upgrade-2.0.11.0_23_20221227_085035.zip)

FATALS:
```
F20221228 07:03:03 ../../../../../../src/yb/yql/pggate/ybc_pggate.cc:76] void yb::pggate::YBCDestroyPgGate() can only be called once
    @     0x7f78b67ee56c  yb::LogFatalHandlerSink::send()
    @     0x7f78b2116336  google::LogMessage::SendToLog()
    @     0x7f78b211379a  google::LogMessage::Flush()
    @     0x7f78b2116869  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f78b6425417  YBCDestroyPgGate
    @           0x95f9db  YBOnPostgresBackendShutdown
    @     0x7f78b5828ba0  (unknown)
    @     0x7f78b4f5d9f3  __GI_epoll_wait
    @     0x7f78b68164bf  boost::asio::detail::epoll_reactor::run()
    @     0x7f78ae5c1ba1  yb::rpc::IoThreadPool::Impl::Execute()
    @     0x7f78b687be0f  yb::Thread::SuperviseThread()
    @     0x7f78b5820694  start_thread
    @     0x7f78b4f5d41d  __clone
    @              (nil)  (unknown
```
This bug is not observed in 2.17.0.1, 2.14.6.0, 2.12.11.0, 2.8.12.0

CC: @sharkberto , @rao-vasireddy, @renjith-yb (Tagging in the light of the 2.16.0.1 hot patch release)

[DB-4554]: https://yugabyte.atlassian.net/browse/DB-4554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment]
CC: @sushantrmishra

**Comment by def-** [comment]
I'll give it a try.

**Comment by rthallamko3** [comment]
`Cannot decode value type kObsoleteIntentPrefix from the key encoding format: "\x0a!pg_user_mapping_user_server_index\x10<...290 bytes skipped>" (aux msg FATAL:  Query error: Error when decoding range components of a document key: while consuming primitive values from 0A2170675F757365725F6D617070696E675F757365725F7365727665725F696E64657810001AA5010A1A08001206756D757365721A0208662001300038004000480360010A1C08011208756D7365727665721A0208662001300038004000480360020A31080212147962756E697175656964786B65797375666669781A02080920013000380040004801609AFFFFFFFFFFFFFFFF010A2A0803120D796269647862617365637469641A02080920003001380040004800609BFFFFFFFFFFFFFFFF01120A10001801280130004001300240014A02120050045A2030303030303030313030303033303030383030303030303030303030303030306A20303030303030303130303030333030303830303030303030303030303035386170007801B20124380142203030303030303031303030303330303038303030303030303030303030353861: Cannot decode value type kObsoleteIntentPrefix from the key encoding format: "\x0a!pg_user_mapping_user_server_index\x10<...290 bytes `

**Comment by def-** [comment]
I have to rerun my test runs with an older charts repo branch (2.17.0), hope to have results later today.

**Comment by rthallamko3** [comment]
@def- , Is there a local repro that @spolitov can use?

**Comment by rthallamko3** [comment]
@def- , @kripasreenivasan , Do we have other upgrade tests that fail with the same issue? Like does the upgrade from 2.14 to 2.16.1 fail with the same issue?

**Comment by def-** [comment]
@rthallamko3 @spolitov I have bisected and this problem started with https://phabricator.dev.yugabyte.com/D21726 (2.17.1.0-b346: https://jenkins.dev.yugabyte.com/job/itest-system-developer/2888/), while b345 was still fine: https://jenkins.dev.yugabyte.com/job/itest-system-developer/2886/

**Comment by spolitov** [comment]
@def- could you please check if D22220 solves the issue?

**Comment by def-** [comment]
@spolitov Confirmed, D22220 fixes this issue.
