### ISSUE TITLE
[Docs] Use YugabyteDB Anywhere to edit a universe

### ISSUE THREAD

**Issue by mohansoundar-yb** [yugabyte/yugabyte-db#15442]
### Description

In the [page](https://docs.yugabyte.com/preview/yugabyte-platform/manage-deployments/edit-universe/)

the last link `For details, see [How to Expand the Universe](https://docs.yugabyte.com/preview/yugabyte-platform/security/enable-encryption-in-transit#how-to-expand-the-universe) .`

points to an non-existing location. Instead the link should have been 
https://docs.yugabyte.com/preview/yugabyte-platform/security/enable-encryption-in-transit/#expand-the-universe

**Comment by ddorian** [comment]
This has already been fixed.
