### ISSUE TITLE
[YSQL] Address Sanitizer failure in unit test TestPgAnalyze#testUniformRandomSamplingWithPaging in master b383

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#15453]
Jira Link: [DB-4562](https://yugabyte.atlassian.net/browse/DB-4562)
### Description

Address Sanitizer failure in unit test TestPgAnalyze#testUniformRandomSamplingWithPaging in master b383
**Log:**
https://gist.github.com/kripasreenivasan/45d5aec7b9cb1860b021d2598be9b08c

**Comment by yifanguan** [comment]
Close this issue since I cannot reproduce this issue on the latest master ASAN build.
`./yb_build.sh asan --java-test org.yb.pgsql.TestPgAnalyze#testUniformRandomSamplingWithPaging`
