### ISSUE TITLE
[Backup + Compactions + DDL] [Stress] Backup is failing with returned non-zero exit status 1

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15470]
Jira Link: [DB-4767](https://yugabyte.atlassian.net/browse/DB-4767)
### Description

I have put quite a few variables: like YSQL packed columns enabled, Both DDL and DMLs were performed, compactions running in parallel, materialized views created for database, 100 tables created in database

http://stress.dev.yugabyte.com/stress_test/6e0283d1-644b-49cf-a8be-9fc3264c942f

Below is the steps performed 
![Profile (3)](https://user-images.githubusercontent.com/109518123/210068772-5c2f39f4-fe23-4132-9d01-be63d5c1ac45.png)

**Please Note:** Backup has failed in second backup creation itself. Its just assertion was missing in testcase

This is what I see error from PLAT UI:

```
Failed to execute task {"sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"9e40693b-40a3-488e-8dfb-846642e35af6","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisS..., hit error:

{"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/data/keys/0de20df6-fc09-4b12-bac8-f4cfbcb1260e/key-052f72caf8ca500c4.pem', '-p', '22', '-q', 'yugabyte@172.151.21.18', \"cd / &&  bash -c 'set -ex; /home/yugabyte/bin/xxhash/xxhsum_x86 /mnt/d0/yb-data/tserver/data/rocksdb/table-00004000000030008000000000004005/tablet-ef934bec94b44c0badac02ef6b3d7c16.snapshots/af798c42-9b63-48fe-8a81-2066f0322f27/[!i]* > /mnt/d0/yb-data/tserver/data/rocksdb/table-00004000000030008000000000004005/tablet-ef934bec94b44c0badac02ef6b3d7c16.snapshots/af798c42-9b63-48fe-8a81-2066f0322f27.xxh64;s3cmd --force --no-check-certificate --config=/tmp/yb_backup_lfkfbxdsxidrovpy/cloud_cfg put /mnt/d0/yb-data/tserver/data/rocksdb/table-00004000000030008000000000004005/tablet-ef934bec94b44c0badac02ef6b3d7c16.snapshots/af798c42-9b63-48fe-8a81-2066f0322f27.xxh64 s3://stress-team-bucket/portal-backups/univ-9e40693b-40a3-488e-8dfb-846642e35af6/backup-2022-12-29T18:19:16-1033157457/multi-table-db_7b22f4/tablet-ef934bec94b44c0badac02ef6b3d7c16.xxh64 --server-side-encryption;s3cmd --force --no-check-certificate --config=/tmp/yb_backup_lfkfbxdsxidrovpy/cloud_cfg sync --no-check-md5 /mnt/d0/yb-data/tserver/data/rocksdb/table-00004000000030008000000000004005/tablet-ef934bec94b44c0badac02ef6b3d7c16.snapshots/af798c42-9b63-48fe-8a81-2066f0322f27/ s3://stress-team-bucket/portal-backups/univ-9e40693b-40a3-488e-8dfb-846642e35af6/backup-2022-12-29T18:19:16-1033157457/multi-table-db_7b22f4/tablet-ef934bec94b44c0badac02ef6b3d7c16/ --server-side-encryption;'\"]' returned non-zero exit status 1."}.
```

I see logs like this in tserver WARN:

![Screenshot 2022-12-30 at 4 39 50 PM (1)](https://user-images.githubusercontent.com/109518123/210068898-703eab60-42b2-41f8-ad22-b0e5aab48510.png)

**Few more details from universe:**

<img width="1392" alt="Screenshot 2022-12-30 at 5 34 01 PM" src="https://user-images.githubusercontent.com/109518123/210068929-f15bc3dd-baaa-41ae-b6f4-2a48ff95fdf5.png">

<img width="1608" alt="Screenshot 2022-12-30 at 5 34 41 PM" src="https://user-images.githubusercontent.com/109518123/210068955-b71331ac-bb48-467f-ac7b-1d1f5162c3d4.png">

**Logs:**
[Framework_logs.zip](https://github.com/yugabyte/yugabyte-db/files/10324629/Framework_logs.zip)
[172.151.21.18.zip](https://github.com/yugabyte/yugabyte-db/files/10324630/172.151.21.18.zip)
[172.151.21.247.zip](https://github.com/yugabyte/yugabyte-db/files/10324632/172.151.21.247.zip)
[172.151.29.108.zip](https://github.com/yugabyte/yugabyte-db/files/10324634/172.151.29.108.zip)

cc: @kripasreenivasan

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , Does it happen with packed row disabled too?

**Comment by rthallamko3** [comment]
Waiting on Shamanth to see if this repros consistently.

**Comment by shamanthchandra-yb** [comment]
Closing it because the issue didn't seem to repro. Will reopen if I see this again.
