### ISSUE TITLE
[Docs] Explore YugabyteDB - something confusing - after creating a local multi-node cluster using these docs (https://docs.yugabyte.com/preview/explore/#set-up-your-yugabytedb-cluster), I was surprised that typing "yugabyted status" fails

### ISSUE THREAD

**Issue by yushenng** [yugabyte/yugabyte-db#15476]
### Description

After following the instructions on this page for "Use a local cluster" and "Multi-node cluster", I was surprised that typing "yugabyted status" fails as shown below:

I copy & paste the commands verbatim, and they all succeeded with no error messages.  Also, the cluster started responding to SQL requests.  

However, upon running "yugabyted status", I saw the below error.  This seemed extremely weird to me, because I had been trained by the earlier docs (about single node clusters) that I could simply type the phrase "yugabyted status" and get some positive feedback that my cluster was running. 
		yng@H70VYJRM6F yugabyte-2.17.0.0 % ./bin/yugabyted status
yugabyted is not running.

About 15 minutes later, when going to other demos described in the "Explore" section of the docs, I realized that yugabyted requires some special syntax for multi-node clusters.   Instead of "yugabyted status", I had to enter another parameter with the path to the config file for each node, as shown below. 

       yng@H70VYJRM6F yugabyte-2.17.0.0 % ./bin/yugabyted status --base_dir=/tmp/ybd1
       yng@H70VYJRM6F yugabyte-2.17.0.0 % ./bin/yugabyted status --base_dir=/tmp/ybd2
       yng@H70VYJRM6F yugabyte-2.17.0.0 % ./bin/yugabyted status --base_dir=/tmp/ybd3

Please add this information to this particular doc page.   Reason: it's pretty typical that a user will want to validate the health of his cluster... via something like "yugabyte status"... and we ought to provide a one-liner statement along lines of "Validate that your cluster node is running with the following command:
          % ./bin/yugabyted status --base_dir=/tmp/ybd1
"

**Comment by ddorian** [comment]
> About 15 minutes later, when going to other demos described in the "Explore" section of the docs, I realized that yugabyted requires some special syntax for multi-node clusters.

Isn't it normal in command line apps that when something doesn't work you do `app command --help` ?
In that case, the instructions should help?

cc @ddhodge please reopen if you think differently and we can add an example. We do explain it in https://docs.yugabyte.com/preview/reference/configuration/yugabyted/#status
