### ISSUE TITLE
[Docs] YugabyteDB Quick Start - the Yugabyted status" command's output tells me to visit an incorrect port of http://127.0.0.1:15433… which contradicts the port that the docs page tells me to use (of port 9999 for Mac OS Montery+)

### ISSUE THREAD

**Issue by yushenng** [yugabyte/yugabyte-db#15473]
### Description

There seems to be a contradiction, and it left me confused:
   a) the Yugabyted status" command's output tells me to visit an incorrect port of http://127.0.0.1:15433… 
   b) this contradicts the port that the docs page tells me to use (port 9999 when I selected the Mac OS Monterey option)

**Details about a):**
yng@H70VYJRM6F yugabyte-2.17.0.0 % ./bin/yugabyted status                                                     

+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 1                                                                                  |
| YugabyteDB UI       : http://127.0.0.1:15433/                                                             |
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=yugabyte          |
| YSQL                : bin/ysqlsh   -U yugabyte -d yugabyte                                               |
| YCQL                : bin/ycqlsh   -u cassandra                                                          |
| Data Dir            : /Users/yng/var/data                                                                |
| Log Dir             : /Users/yng/var/logs                                                                |
| Universe UUID       : cf12cb90-9ab4-44d1-84b2-9d81d4927a18                                               |
+----------------------------------------------------------------------------------------------------------+

**Other notes**
Interestingly, this page  http://127.0.0.1:15433/ does show something… but the page shown has lots of "Something is wrong. Please try again" messages.

Note: the [Mac QuickStart instructions](https://docs.yugabyte.com/preview/quick-start/) correctly tell me to visit ports http://127.0.0.1:9999/ and http://127.0.0.1:9000/, 

Below is a screenshot of the incorrect page shown when I visit the :15433 URL

![image](https://user-images.githubusercontent.com/5713777/210100674-d14d2703-0551-488a-b7d1-bae5a42bab0e.png)

**Comment by ddorian** [comment]
@yushenng 

Does this issue still happen to you?

**Comment by ddhodge** [comment]
127.0.0.1:15433 is the address of the new yugabyted UI - there was a bug previously where this didn't work very well, however more recent releases work correctly, and the Quick Start has been updated in both cases to reflect the (now functional) UI.
For example: https://docs.yugabyte.com/preview/quick-start/#monitor-your-cluster
Closing this on the assumption it is fine now.
