### ISSUE TITLE
[Docs] xCluster replication (2+ regions) in YSQL

### ISSUE THREAD

**Issue by yushenng** [yugabyte/yugabyte-db#15480]
### Description

To follow the instructions on this page, we need to add a step for local clusters.   (Not sure if this step needs to be added for YBM clusters).

Specifically, between steps 1 and 2 of "Create tables", the user needs to type 
    \c yugabyte
... to connect to the database named "yugabyte"

**Details:**
Step 1: Open ysqlsh by specifying the host IP address of 127.0.0.1, as follows:
    ./bin/ysqlsh -h 127.0.0.1

Step 2: Create the table users, as follows:

**Comment by ddorian** [comment]
@yushenng 

can you link to the page and section?

**Comment by yushenng** [comment]
https://docs.yugabyte.com/preview/explore/multi-region-deployments/asynchronous-replication-ysql/#create-tables

**Comment by ddorian** [comment]
> Specifically, between steps 1 and 2 of "Create tables", the user needs to type
> \c yugabyte
> ... to connect to the database named "yugabyte"

The default database is `yugabyte`, unless you've changed it when running `ysqlsh` command. 

And should also be in your case. What is it in your case? And which version are you using?

**Comment by yushenng** [comment]
I'm using 2.17.0.0

Yes, I'm using the default database of yugabyte

The main point of my bug report is:   
   * the docs mistakenly omit the instruction to type "\c <database_name>"

And, BTW, I think this problem is recurrent throughout many examples in the docs.

**Comment by ddorian** [comment]
> the docs mistakenly omit the instruction to type "\c <database_name>"

I don't personally believe this to be a problem. cc @polarweasel

**Comment by yushenng** [comment]
While it's fairly minor for folks who are reading the docs sequentially, it
may affect / afflict people who skip to a particular example in the docs
and try to run the example.   They may get stuck.

**Comment by ddorian** [comment]
Closing as we do the same thing on all docs, implicit database name.
