### ISSUE TITLE
[docs] Does Yugabyte support Common Table Expressions (CTE)

### ISSUE THREAD

**Issue by AmirAbrams** [yugabyte/yugabyte-db#1549]
If not, are there any plans to support SQL CTE.  Without CTE, what is the best alternatives to keep temporary result sets and sub-queries on the server so there isn't unnecessary traffic for the client?  Maybe I can use views.
[PostgreSQL CTE Documentation](https://www.postgresql.org/docs/9.1/queries-with.html)

Same question regarding SQL stored procedures. I know you have plans but any timeline on when Yugabyte will support stored procedures?

**Comment by ndeodhar** [comment]
Hi @AmirAbrams , thanks for your interest in YugaByteDB!
We do support CTE and examples listed in PostgreSQL CTE Documentation should work. Here is more information about supported syntax:
https://docs.yugabyte.com/latest/api/ysql/commands/dml_select/
We'll improve our documentation to add some examples for CTE.

Procedures and functions are actively being worked on currently and Beta version will be available in the next couple of weeks. We will support SQL and PLPGSQL languages for procedures in the Beta version.

**Comment by rkarthik007** [comment]
@bllewell - could you please help out with the missing documentation for CTE in YSQL? Thanks!

**Comment by bllewell** [comment]
PR # 7217 and some follow-ups fixed this. See:

[The WITH clause and common table expressions](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/with-clause/)
