### ISSUE TITLE
[Docs] Synchronous replication (3+ regions) in YSQL

### ISSUE THREAD

**Issue by yushenng** [yugabyte/yugabyte-db#15502]
### Description

I reached this page 
       https://docs.yugabyte.com/preview/explore/multi-region-deployments/synchronous-replication-ysql/
after reading (and working through the examples) of the standard YBDB docs sequentially.   I got stuck on this doc page due to due errors described on this Slack thread: https://yugabyte.slack.com/archives/C4141D60H/p1672383131912579

The key / root cause problem was that: our docs lack commands to setup loopback for nodes 4 and 5... and this web page requires such loopback to be setup.

That is, we must provide instructions somewhere (if not on this page, then elsewhere earlier in the docs when we first set up loopback) to add the following additional commands:
     % sudo ifconfig lo0 alias 127.0.0.4
     % sudo ifconfig lo0 alias 127.0.0.5

**Comment by ddorian** [comment]
This has already been fixed since yb-ctl has been replaced with `yugabyted` on that docs page.
