### ISSUE TITLE
[YEDIS] ERR MGET: MGET command not yet supported

### ISSUE THREAD

**Issue by Exocomp** [yugabyte/yugabyte-db#1551]
Any timeline when MGET will be added ?

**Comment by kmuthukk** [comment]
hi @Exocomp

(Similar to previous reply).

While we don't yet support MGET, we do support pipelined GETs to achieve a similar effect of reducing number of roundtrips to DB when retrieving multiple keys.

Also, please see our note on prioritization of YEDIS enhancements and plans here: https://docs.yugabyte.com/latest/yedis/.

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
