### ISSUE TITLE
[YEDIS] ERR MSET: MSET command not yet supported

### ISSUE THREAD

**Issue by Exocomp** [yugabyte/yugabyte-db#1552]
Any timeline when MSET will be added ?

**Comment by kmuthukk** [comment]
hi @Exocomp 

While we don't yet support MSET, we do support pipelined SETs to achieve a similar effect of reducing number of roundtrips to DB when setting multiple keys.

Also, please see our note on prioritization of YEDIS enhancements and plans here: https://docs.yugabyte.com/latest/yedis/.

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
