### ISSUE TITLE
[DocDB] TSAN issue with Connection::outbound_data_being_processed_

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#15528]
Jira Link: [DB-4917](https://yugabyte.atlassian.net/browse/DB-4917)
### Description

Connection::outbound_data_being_processed_ is being used without any locks causing race during shutdown

[DB-4917]: https://yugabyte.atlassian.net/browse/DB-4917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@hari90 , reactivating this issue to backport it to stable brances.
