### ISSUE TITLE
[YSQL] Flakiness in org.yb.pgsql.TestPgAnalyze.testUniformRandomSampling

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#15520]
Jira Link: [DB-4911](https://yugabyte.atlassian.net/browse/DB-4911)
### Description

Flakiness can be seen in centos-clang15-debug builds for 2 tests -
1. org.yb.pgsql.TestPgAnalyze.testUniformRandomSamplingWithPaging
2. org.yb.pgsql.TestPgAnalyze.testUniformRandomSampling

[DB-4911]: https://yugabyte.atlassian.net/browse/DB-4911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shishir2001-yb** [comment]
@m-iancu @pkj415, Both test are failing on master
https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgAnalyze&fail_tag=all&name=testUniformRandomSampling&num_commits=500&platform=linux
https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgAnalyze&fail_tag=all&name=testUniformRandomSamplingWithPaging&platform=linux
