### ISSUE TITLE
[DocDB] xCluster Prioritize WAL retention of the transaction status table

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#15523]
Jira Link: [DB-4913](https://yugabyte.atlassian.net/browse/DB-4913)
### Description

Given that there is no backup/ restore for transaction status table which spans multiple databases, we need to prioritize WAL retention of this over WAL of individual databases due to broader impact in case of GC.

[DB-4913]: https://yugabyte.atlassian.net/browse/DB-4913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by UtR491** [comment]
Hi @lingamsandeep I would like to work on this issue. Can you provide some more information?
