### ISSUE TITLE
[CDCSDK] Long term retention of intents

### ISSUE THREAD

**Issue by adithya-kb** [yugabyte/yugabyte-db#15533]
Jira Link: [DB-4923](https://yugabyte.atlassian.net/browse/DB-4923)
Currently we are retaining intents by controlling GC of the transaction's metadata based on the apply record's OpId , 
But this causes longer memory footprints in the cluster, especially if we plan to allow longer periods of intent retention (in the order of weeks) 

[DB-4923]: https://yugabyte.atlassian.net/browse/DB-4923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by adithya-yb** [comment]
Following are the subtasks: 

- Remove transactionId based removal from CDC -> Retain only intents , correctness
- Verify long term Intent retention works, in extreme cases like connector down
- Measure xImpact on read 
- Just store TxnId of latest file, for others just frontier information

**Comment by rthallamko3** [comment]
Closing this as we created individual items - 
1. Memory issue - https://github.com/yugabyte/yugabyte-db/issues/21290
2. Performance issue - https://github.com/yugabyte/yugabyte-db/issues/21580
