### ISSUE TITLE
[DocDB] [xCluster][Atomicity and Ordering] Data loss (replication stops) after replication resume operation.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15542]
Jira Link: [DB-4939](https://yugabyte.atlassian.net/browse/DB-4939)
### Description

**Steps**:
1. Create 2 universes(Source and Target) with Turn ON the GFlag **enable_replicate_transaction_status_table** on master of both universes and disable automatic tablet splitting
2. Create database and 3 tables at both sides
3. Setup replication from source to target
4. Change the xCluster role at Target
`yb-admin -master_addresses <master-address> change_xcluster_role STANDBY`
5. Updates(within transaction) are happening in one table
6. Inserts(within transactions) are happening in other 2 tables
7. After sometime pause the replication

**Observations**,
1. After pausing the replication observed Data inconsistency,
> Update transaction partially replicated at target.
> Insert transaction partially replicated at target.

8. After resuming the replication(after 2 min)
> Partially un-replicated data(which was within transactions) is replicated for all 3 tables
> And data loss (next ran transactions’ data is not replicated)

9. Observed below logs in source’s tserver log file
`I0106 07:55:38.122043 24527 tablet_rpc.cc:458] Operation failed. Try again (yb/tserver/tablet_service.cc:1070): Failed UpdateTransaction: tablet_id: "aae7e35e001d4fc6ab1def3bc3d06f0b" state { transaction_id: "\301\341\326\010+\354D\022\237\210\\\3439\236\331\017" status: APPLYING tablets: "de5564bbee144b7fa635f06cf5fb2b2d" commit_hybrid_time: 6852572107115016192 sealed: false aborted { } external_hybrid_time: 6852572107115016192 } propagated_hybrid_time: 6852574159347347456 is_external: true, retrier: { task_id: -1 state: kIdle deadline: 6806.796s } to tablet aae7e35e001d4fc6ab1def3bc3d06f0b on tablet server { uuid: 725e7ad0b47649be9ce0c6491e03098b private: [host: "172.161.59.194" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-east-2" placement_zone: "us-east-2c" after 1 attempt(s): XCluster safe time not found for namespace 00004005000030008000000000000000`

[DB-4939]: https://yugabyte.atlassian.net/browse/DB-4939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Related to #15543
