### ISSUE TITLE
[xCluster] Handle any issues due to replication repeating changes

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#15547]
Jira Link: [DB-4942](https://yugabyte.atlassian.net/browse/DB-4942)
### Description
Originally: [xCluster] Ignore Incoming Records at a Lower Timestamp than the Tablet's xCluster Safetime

After a restart or bootstrap, it is possible that replication starts at some timestamp earlier than xcluster safe time because the producer updates the last checkpoint asynchronously. As a result, it is possible that an update can come in at a lower timestamp than the safe time, causing potential data inconsistencies. Fix this by ignoring incoming writes/updates with timestamp lower than the xcluster safe time.

[DB-4942]: https://yugabyte.atlassian.net/browse/DB-4942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UPDATE 4/10/2023:  after discussion we realized the real issue here is that replication can repeat changes due to failures (aka, at least one semantics).  This issue is to figure out how that can cause problems and fix them.  

So far we have identified a issue with historical retention possibly  blocking replication -- writes to times before  history retention period are silently dropped.    To fix this, we need to make sure we retain at least a history after the xCluster safe time.  Issue to fix this: #16551

It is unclear if the original possibility -- incoming records below xCluster safe time -- is actually a problem at this time.

**Comment by hari90** [comment]
There is the question "does this tserver have the correct safe time". But the solution to https://github.com/yugabyte/yugabyte-db/issues/16355 will involve Pollers waiting to know the current safe time before calling GetChanges so it should be safe after this task is completed.

**Comment by mdbridge** [comment]
depends on #16551

**Comment by hari90** [comment]
Ignore GetChanges response records with HT < xcluster safe time

**Comment by mdbridge** [comment]
The investigation here is done; see list of issues above as the generated action items from the investigation.

**Comment by mdbridge** [comment]
Internal Yugabyte investigation document: https://docs.google.com/document/d/1RkIEojAnsT4qP2T5Yvf6kUnklUqYJmqM-IX5fywP2_0
