### ISSUE TITLE
[YSQL] Index is not dropped properly

### ISSUE THREAD

**Issue by frozenspider** [YugaByte/yugabyte-db#1555]
```
postgres=# CREATE TABLE t1(id int PRIMARY KEY, val int, grp int);
CREATE TABLE
postgres=# CREATE INDEX i ON t1 (val);
CREATE INDEX
postgres=# DROP INDEX i;
ERROR:  Invalid argument: Primary key must be fully specified for modifying table
postgres=# DROP INDEX i;
ERROR:  catalog is missing 1 attribute(s) for relid 16389
```

**Comment by georgeklees** [comment]
Can you provide more information on your environment and what exactly your database setup was like when this bug occurred? I have created a simple YB environment with just 1 node and executed these commands in `ysqlsh` within a test database, and the bug does not reproduce.

**Comment by frozenspider** [comment]
Turns out this was caused by the build issue, I'm no longer seeing this. Closing.
