### ISSUE TITLE
[YSQL] Null value in added non-null column with default value

### ISSUE THREAD

**Issue by korotky** [yugabyte/yugabyte-db#15553]
Jira Link: [DB-4946](https://yugabyte.atlassian.net/browse/DB-4946)
### Description

2.17.0.0-b24:
```
begin;
drop table if exists test;
create table if not exists test( id uuid not null primary key);
insert into test(id) values('10000000-0000-0000-0000-000000000000');
ALTER TABLE test ADD COLUMN IF NOT EXISTS test BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE test ADD COLUMN IF NOT EXISTS test2 BOOLEAN NOT NULL DEFAULT FALSE;
update test set id=id where id='10000000-0000-0000-0000-000000000000';
end;
```
```
[40001] ERROR: Operation failed. Try again: Unknown transaction, could be recently aborted: 57816617-1068-4a58-b2a3-64f7ca7184e7
```
If I run it in a separate transactions, I get an error:
```
[23502] ERROR: null value in column "test" violates not-null constraint
```

[DB-4946]: https://yugabyte.atlassian.net/browse/DB-4946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
@korotky 

Note that we don't have transactional DDL yet. 

In your case, ran until at least the first alter table ran. Then your second error makes sense.
