### ISSUE TITLE
[CDCSDK] CDC to downstream Data warehouses (Redshift, Snowflake, BigQuery)

### ISSUE THREAD

**Issue by adithya-kb** [yugabyte/yugabyte-db#15598]
Jira Link: [DB-4982](https://yugabyte.atlassian.net/browse/DB-4982)

[DB-4982]: https://yugabyte.atlassian.net/browse/DB-4982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by adithya-yb** [comment]
Only needed for YB Managed
