### ISSUE TITLE
Check failed: state.prev_op_id.term() >= state.committed_op_id.term() && state.prev_op_id.index() >= state.committed_op_id.index()

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1560]
https://gist.githubusercontent.com/mbautin/693c5bae34bcc74214967098db45f86c/raw

Repro:
./yb_build.sh --cxx-test integration-tests_encryption-test --gtest_filter EncryptionTest.AddServer

**Comment by rkarthik007** [comment]
Hit this when running a 100 node cluster as well:

```
F0911 23:05:04.387091  7355 tablet_bootstrap.cc:990] Check failed: state.prev_op_id.term() >= state.committed_op_id.term() && state.prev_op_id.index() >= state.committed_op_id.index() Last: term: 1 index: 14639, committed: 1.94691
```

**Comment by hectorgcr** [comment]
This issue seems to happen when a FOLLOWER received a TABLET DELETE request while it's in the middle of a RBS for the same tablet.

**Comment by hectorgcr** [comment]
The name of state has been changed to replay_state_, so the new fatal is:
```
Check failed: replay_state_->prev_op_id.term() >= replay_state_->committed_op_id.term() && replay_state_->prev_op_id.index() >= replay_state_->committed_op_id.index()
```
