### ISSUE TITLE
[Docs] Build a PHP application that uses YSQL

### ISSUE THREAD

**Issue by AyushPlaksha** [yugabyte/yugabyte-db#15620]
### Description

While providing all credentials and following tutorials on running the application it shows an exception could not find driver.Please reply I am using windows.

**Comment by ddorian** [comment]
Hi @AyushPlaksha 

You should include much more details:

1. What steps exactly did you follow
2. where/when did you get the error
3. what's your code
4. what's the full error log.

**Comment by ddorian** [comment]
Closing as no response from user.
