### ISSUE TITLE
[Docs] Change the Akka integration

### ISSUE THREAD

**Issue by patriknw** [yugabyte/yugabyte-db#15634]
### Description

Regarding https://docs.yugabyte.com/preview/integrations/akka/

Lightbend's Akka Tech Lead here. I would like to point out that Yugabyte is not officially supported by Lightbend with the Akka Persistence Cassandra plugin.

Lightbend officially support Yugabyte with the Akka Persistence R2DBC plugin, i.e. the Postgres flavor of Yugabyte. https://doc.akka.io/docs/akka-persistence-r2dbc/current/overview.html

I can provide a PR changing that page to use the the R2DBC plugin if you like?

**Comment by polarweasel** [comment]
@patriknw Thanks for this! If you'd like to provide a PR, that would be great. We're also discussing with the ecosystem team to see what they were up to with this one.

**Comment by ashetkar** [comment]
Hi @patriknw 
Yes, a PR for YugabyteDB support with R2DBC plugin would be really awesome. Thanks!

On a side note, about the Akka Persistence Cassandra doc, we did basic testing and added the documentation above. We plan to do further validation in this regard and any help/guidance would be greatly appreciated.

**Comment by aishwarya24** [comment]
This is addressed in #15899
