### ISSUE TITLE
[DocDB][xCluster][Atomicity] Data loss at Target Universe 

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15659]
Jira Link: [DB-5025](https://yugabyte.atlassian.net/browse/DB-5025)
### Description

**Steps**:
Create 2 universes(Source and Target) with Turn ON the GFlag `enable_replicate_transaction_status_table` on master of both universes and disable automatic tablet splitting
Create database and table at both sides
Setup replication from source to target
Change the xCluster role at Target
`yb-admin -master_addresses <master-address> change_xcluster_role STANDBY`
Run simple insert workload(tried with 500K inserts)
After sometime kill the workload wait for some time(let Lag shows 0)
Run select query at both sides and observe the count

**Observations**:
Data at Target is less than the data at Source.
Observed below errors in tserver log at Target
```
E0112 15:10:15.907948 12775 docdb_compaction_filter_intents.cc:205] T 75f20707d3b24d3ca1967448b0c7fb10: Corruption (yb/docdb/doc_kv_util.cc:194): Could not decode hybrid time: Invalid prefix of doc hybrid time in reverse intent record decoded suffix: 4B
E0112 15:10:15.912343 12775 docdb_compaction_filter_intents.cc:205] T 75f20707d3b24d3ca1967448b0c7fb10: Corruption (yb/docdb/doc_kv_util.cc:194): Could not decode hybrid time: Invalid prefix of doc hybrid time in reverse intent record decoded suffix: FE
E0112 15:10:15.919576 12775 docdb_compaction_filter_intents.cc:205] T 75f20707d3b24d3ca1967448b0c7fb10: Corruption (yb/docdb/doc_kv_util.cc:194): Could not decode hybrid time: Invalid prefix of doc hybrid time in reverse intent record decoded suffix: 9B
```

[DB-5025]: https://yugabyte.atlassian.net/browse/DB-5025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
Source and Target have different number of tablets which is not yet a supported scenario and seems to be causing this issue.
