### ISSUE TITLE
[Docs] Persistence in YugabyteDB

### ISSUE THREAD

**Issue by HuoHuaSai** [yugabyte/yugabyte-db#15657]
In the section of "YCQL - Collection type example", for the definition of table msg's primary key, it seems that there miss a left bracket of the column msg_id:
CREATE TABLE msgs (user_id text,
                   msg_id int,
                   msg text,
                   msg_props map<text, text>,
      PRIMARY KEY ((user_id), msg_id));  <===here is the issue(miss a left bracket of the column msg_id???)

**Comment by ddorian** [comment]
@HuoHuaSai 

I just tried it on ycqlsh and it works fine for me:
```cql
ycqlsh> create keyspace ybdemo;
ycqlsh> use ybdemo;
ycqlsh:ybdemo> CREATE TABLE msgs (user_id text,
          ...                    msg_id int,
          ...                    msg text,
          ...                    msg_props map<text, text>,
          ...       PRIMARY KEY ((user_id), msg_id));
ycqlsh:ybdemo> describe msgs;

CREATE TABLE ybdemo.msgs (
    user_id text,
    msg_id int,
    msg text,
    msg_props map<text, text>,
    PRIMARY KEY (user_id, msg_id)
) WITH CLUSTERING ORDER BY (msg_id ASC)
    AND default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
```

What would be your fix?
