### ISSUE TITLE
Throttle auto-ANALYZE invocations

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15663]
Jira Link: [DB-5029](https://yugabyte.atlassian.net/browse/DB-5029)
### Description

This task tracks throttling the ANALYZE service to ensure that only one ANALYZE is executed for a table at a given time.

[DB-5029]: https://yugabyte.atlassian.net/browse/DB-5029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
This part has been implemented.
