### ISSUE TITLE
Auto-analyze: TServer service for executing ANALYZE against local PG backend

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15665]
Jira Link: [DB-5031](https://yugabyte.atlassian.net/browse/DB-5031)
### Description

This task tracks implementation of a TServer service for executing ANALYZE against local PG backend. When a tserver receives the request from the analyze service to trigger ANALYZE, it will establish a local PG backend connection to invoke ANALYZE.

[DB-5031]: https://yugabyte.atlassian.net/browse/DB-5031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Feature implemented in commit [9df2d82](https://github.com/yugabyte/yugabyte-db/commit/9df2d82b7086349076cd83a9c57df8f14ef0d3f7)
