### ISSUE TITLE
ANALYZE catalog tables as part of initdb

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15660]
Jira Link: [DB-5026](https://yugabyte.atlassian.net/browse/DB-5026)
### Description

ANALYZE catalog tables as part of initdb

[DB-5026]: https://yugabyte.atlassian.net/browse/DB-5026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Supported by commit ccc3f8e
