### ISSUE TITLE
Auto-analyze: Introduce yb_auto_analyze, yb_analyze_threshold and yb_analyze_scale_factor as tserver gflags

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15671]
Jira Link: [DB-5037](https://yugabyte.atlassian.net/browse/DB-5037)
### Description

This task is tracking introducing yb_auto_analyze, yb_analyze_threshold and yb_analyze_scale_factor as tserver gflags

[DB-5037]: https://yugabyte.atlassian.net/browse/DB-5037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/9df2d82b7086349076cd83a9c57df8f14ef0d3f7.
