### ISSUE TITLE
[Docs] Add documentation for password checker extension

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#15681]
### Description

We have enhanced the password checker extension with following additional capabilities. 

- Minimum length of password allowed
- Enforce use of special characters
- Enforce use of numbers
- Enforce use of upper-case characters
- Enforce use of lower-case characters
- Special characters defined

The PostgreSQL configuration variable which controls the capabilities:
https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/contrib/passwordcheck/passwordcheck.c#L222 

YB commit which added the  enhancement: 
https://github.com/yugabyte/yugabyte-db/commit/e05a448cfbdff6b88a2d767113a8e885a8f3b591 

We should enhance  docs for [passwordchecker](https://docs.yugabyte.com/preview/explore/ysql-language-features/pg-extensions/#passwordcheck-example) with it.

**Comment by polarweasel** [comment]
Note: This is present in 2.17.0.0 and 2.16.0.0, so we can publish as soon as we've got the docs ready.
