### ISSUE TITLE
[Docs] Document packed_row feature limitations

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#15691]
### Description

Document packed_row feature limitations

**Comment by ddorian** [comment]
@rthallamko3 what are they? Or where to find them?

**Comment by rthallamko3** [comment]
We have documented the existing ones in https://docs.yugabyte.com/preview/architecture/docdb/persistence/#limitations . One of them is closed, the other one is referencing a different issue. We can remove them as they are no longer relevant.
