### ISSUE TITLE
Support multiple passwords for the Redis password-based security in YugaByte DB

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#157]
The use-case is when the end user needs to perform a graceful change of password without experiencing any app outage. The preferred sequence is:
- add a new password in addition to the existing one for a username in yugabyte db
- change the password used by the app tier by pushing a new config/code
- drop the old password in the db for the username

**Comment by amitanandaiyer** [comment]
Addressed in #283
