### ISSUE TITLE
[DocDB] Deleted tablets should not be displayed on Underreplicated Tablets page for master UI

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#15714]
Jira Link: [DB-5066](https://yugabyte.atlassian.net/browse/DB-5066)
### Description

During investigation of https://github.com/yugabyte/yugabyte-db/issues/14980 it turns out that DELETED tablets are still displayed on "Underreplicated Tablets" page for master UI: https://user-images.githubusercontent.com/2335377/211612394-83410c5f-7bbe-48a7-ad50-d73d4552877b.png

This is happening because the endpoint request all tablets including inactive tablets to build a list of underreplicated tablets, refer to `MasterPathHandlers::GetUnderReplicatedTablets()`. Thus, additional condition should be added to exclude DELETED tablets from the list (please pay attention HIDDEN tablets may be still wanted for the display).

Some context: the deleted tablet may become under-replicated if it lost one replica (e.g. due to connectivity issue) during tablet splitting execution; in this case tablet leader will kick a replica from raft config and complete splitting with two replicas only, the tablet is being deleted after the splitting is done but will be still persisted in `TableInfo::tablets_` (currently it is kept forever, but the time period of persistence will be changed in the context of related issue https://github.com/yugabyte/yugabyte-db/issues/15043).

[DB-5066]: https://yugabyte.atlassian.net/browse/DB-5066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by omkaark** [comment]
Hello! How can we know if the table is deleted? The underreplicated check is simple as it checks if current size is less than replication_factor. Wondering if you can provide any extra insights.

**Comment by omkaark** [comment]
Ignoring hidden tablets is quite easy, so @sanketkedia @lingamsandeep let me know if that is needed. We can also give the GetUnderReplicatedTablets a default parameter like `showHiddenTables = false` as input. That way when no input is provided, they are not shown!

**Comment by arybochkin** [comment]
Hey @SrivastavaAnubhav, do we want this issue be backported to 2.18 and other stable branches?

**Comment by SrivastavaAnubhav** [comment]
@arybochkin no I think we can just close this.

**Comment by rthallamko3** [comment]
@SrivastavaAnubhav , Did the commit land on master? Reactivating this one as I do not see the above commit in master branch. cc @lingamsandeep

**Comment by SrivastavaAnubhav** [comment]
@rthallamko3 Yes this was landed: https://github.com/yugabyte/yugabyte-db/pull/16953. The commit did not reference this issue so it didn't show up here.
