### ISSUE TITLE
[YSQL] Delete query takes more time for foreign key referenced table 

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15711]
Jira Link: [DB-5064](https://yugabyte.atlassian.net/browse/DB-5064)
### Description

DB Version: `2.17.1.0-b432`

**Steps**:
1. Create universe with Turn ON the GFlag enable_replicate_transaction_status_table on master and disable automatic tablet splitting
2. Create database and 2 tables and 3 indexes
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE complex AS (re float8, im float8);

CREATE TABLE table1 (id text, uuid_col uuid DEFAULT uuid_generate_v4 (), name text, f_name text, c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, age int, collated_data text collate "POSIX",date DATE,n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], primary key (id ASC));

CREATE TABLE table2 (id text, uuid_col uuid DEFAULT uuid_generate_v4 (), name text primary key, f_name text, c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, age int, collated_data text collate "POSIX",date DATE,n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], CONSTRAINT fk_table1 FOREIGN KEY(id) REFERENCES table1(id)) SPLIT INTO 8 TABLETS;

create index idx_1 on table1(age) where age>10 and age< 50;
create index idx_2 on table2(f_name);
create index idx_3 on table1(created_at) include(uuid1);
```
3. Run transactional workload(load 100K+ rows in each table)
4. Stop workload, wait for some time 
5. Run bootstrap_cdc_producer command     # not necessary step, mentioned as I used
6. Run delete queries
`delete from table1 where age>15 and age<20;`   -  Fails with `ERROR:  update or delete on table "table1" violates foreign key constraint "fk_table1" on table "table2”. ` —— expected
`delete from table2 where age>15 and age<20;`   -  Works(takes < 5 seconds)
`delete from table1 where age>15 and age<20; `   -  takes more than 10 min to complete for 7K rows

[DB-5064]: https://yugabyte.atlassian.net/browse/DB-5064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
This is expected. Table2 does not have an index on **id** so delete of each row of table1 will do a full scan of table2 to make sure the FK constrain is not violated.

**Comment by m-iancu** [comment]
Correct, this is not a YSQL but, rather a result of the schema modelling. The recommendation is to add that index/pkey on id if deletes on table1 are a common pattern.
