### ISSUE TITLE
[DocDB] Enable manually cancelling transaction

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#15726]
Jira Link: [DB-5081](https://yugabyte.atlassian.net/browse/DB-5081)
### Description

We should provide some means for users to manually cancel a transaction. E.g. suppose transaction T1 is stuck on some statement. If we check the lock status and find that T1 is waiting on a lock held by T2, and we want to cancel T2 immediately to unblock T1, we should be able to do this. Postgres has `pg_cancel_backend(...)` and `pg_terminate_backend(...)`

We would like to offer `yb_cancel_transaction(transaction_id)` which can simply hit the endpoint exposed by https://github.com/yugabyte/yugabyte-db/issues/16696

This should be accessible only to superuser or db admin users

[DB-5081]: https://yugabyte.atlassian.net/browse/DB-5081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
Note: maybe instead of cli, this should be available via ysqlsh

**Comment by rthallamko3** [comment]
Load balancing to @basavaraj29  for now. cc @sushantrmishra  to share sample diffs to use as a template.
