### ISSUE TITLE
[Docs] Quickstart page redirects to preview when clicking on stable version

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#15722]
### Description

Steps to reproduce:

1. Go to https://docs.yugabyte.com/stable/quick-start/linux/
2. It redirects to https://docs.yugabyte.com/preview/quick-start/linux/

This seems to only happen on quickstart for me. Tested some other pages and it worked fine.

**Comment by polarweasel** [comment]
There are several areas of the docs that are "unversioned", including this one — which for the moment means they redirect to /preview. We've removed the version selector from those pages. Eventually, they'll be in their own directory hierarchy to remove the implication of versioning entirely.
