### ISSUE TITLE
[YSQL] DB enters bad state on executing sub-partitions schema

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yugabyte-db#15724]
Jira Link: [DB-5080](https://yugabyte.atlassian.net/browse/DB-5080)
### Description

Hi Team,
On running the following sub-partitioning schema on a database, it enters a bad state and we aren't able to reconnect to it.
The schema executes perfectly fine and we can use the DB until we disconnect from it/switch to a different database. Then if we try to reconnect, it errors out.

Schema:

```
CREATE TABLE subpartitioning_test (
        bill_no bigint,
        sale_date timestamp,
        cust_code varchar(15),
        amount decimal(8,2)
) PARTITION BY LIST ((extract(month from date(sale_date))::integer)) ;

CREATE TABLE subpartitioning_test_p0 PARTITION OF subpartitioning_test
FOR VALUES IN (1,2)
PARTITION BY HASH ((((sale_date)::date - '0001-01-01bc')::integer));
```

Corresponding error on 2.16.0.1

```
connection to server at "172.151.50.74", port 5433 failed: SSL SYSCALL error: EOF detected
Previous connection kept
```

cc: @kneeraj 

[DB-5080]: https://yugabyte.atlassian.net/browse/DB-5080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
Tested in latest and I get this error on the second connection:
```
ysqlsh: FATAL:  Illegal state: GetData for { database_oid: 13288 object_oid: 1255 } table failed: : Request table differs from prefetch table: { database_oid: 0 object_oid: 0 } vs { database_oid: 13288 object_oid: 2691 }
LINE 1: select pg_catalog.date_part($1, cast($2 as timestamp without...
               ^
QUERY:  select pg_catalog.date_part($1, cast($2 as timestamp without time zone))
```

**Comment by myang2021** [comment]
I have checked that this bug is fixed by the diff https://phabricator.dev.yugabyte.com/D22340.

**Comment by myang2021** [comment]
duplicate #15743
