### ISSUE TITLE
[DocDB] Add tserver UUID to consensus information in debug UIs

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15735]
Jira Link: [DB-5090](https://yugabyte.atlassian.net/browse/DB-5090)
### Description

When a tserver gets its disk wiped, on restart, it will get a new UUID, as it will be starting up with an empty filesystem. However, this tserver will still be in the raft groups for all the tablets it used to be serving.

To even triage such instances, we generally need to look at the consensus config of the tablet and validate both the hostnames and the UUIDs in the config. However, both the master (:7000/table view) and the tserver (:7000/tablet view) only show the hostnames. The only exception is the tserver-side, per tablet, only on the leader side!

For the master side, we have access to the consensus config, from the heartbeat, so we have the UUIDs as well.
For the tserver side, followers also have access to the consensus config, so we should augment the consensus UI to showcase this for followers as well.

[DB-5090]: https://yugabyte.atlassian.net/browse/DB-5090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Master per-table view `/table?id=xxx` -- we need some way to also showcase the UUIDs here

<img width="1521" alt="Screen Shot 2023-01-18 at 5 08 25 PM" src="https://user-images.githubusercontent.com/395011/213306070-5c04759e-2581-4114-b697-0dd751b65aeb.png">

Tserver leader view, on the `/tablet-consensus-status?id=xxx` endpoint -- we need some way to showcase the hostname/IP in there as well
<img width="1618" alt="Screen Shot 2023-01-18 at 5 09 56 PM" src="https://user-images.githubusercontent.com/395011/213306315-93e73e23-d4ef-4231-8dab-1645ecbaf172.png">

Tserver follower view, on the`/tablet-consensus-status?id=xxx` endpoint -- we should show at least the raft config, with uuid and hostname/ip in, even if we can't show the whole queue like on the leader page (since followers don't have an active queue)
<img width="943" alt="Screen Shot 2023-01-18 at 5 11 35 PM" src="https://user-images.githubusercontent.com/395011/213306574-87224c64-d0b1-4077-8934-29dc4afed29f.png">

**Comment by yamen-haddad** [comment]
- For the Tserver leader view, on the `/tablet-consensus-status?id=xxx` endpoint, this is how it looks like after printing the Hostname (in addition to the already printed UUIDs) of tservers in the Peer column.

![tserver-ui-leader-after](https://user-images.githubusercontent.com/22749018/220526387-71f0d334-df58-4d17-9503-f1a19e803a92.png)

- For the Tserver follower view, on the `/tablet-consensus-status?id=xxx` endpoint, this is how it looks like after printing the Raft Config (the list of peers hostnames and UUIDs).

![tserver-ui-follower-after](https://user-images.githubusercontent.com/22749018/220526661-d17d5542-d0cc-4095-a70b-9730e8096e7f.png)

**Comment by rthallamko3** [comment]
Waiting on the backport to 2.14 to complete before we can close this defect.

**Comment by yamen-haddad** [comment]
So when trying to backport to 2.14, the build failed mainly because of `last_known_private_addr` in `yb::consensus::PeerMessageQueue::TrackedPeer`
has not been defined prior to 2.16.
This is the error message I am getting:
```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/yb/consensus/consensus_queue.cc:1340:63: error: no member named 'last_known_private_addr' in 'yb::consensus::PeerMessageQueue::TrackedPeer'
               EscapeForHtmlToString("Host: " + entry.second->last_known_private_addr[0].host()),
                                                ~~~~~~~~~~~~  ^
1 error generated.

Input files:
  src/yb/consensus/CMakeFiles/consensus.dir/consensus_queue.cc.o
  src/yb/consensus/consensus_queue.cc
Output file (from -o): src/yb/consensus/CMakeFiles/consensus.dir/consensus_queue.cc.o
```

After discussing with Basava who introduced `last_known_private_addr`, It appears that it is non trivial to get this info and thus it is non trivial backport to 2.14.
So not sure if it is worth searching how to get the address in order to backport to 2.14 or we should be good of backporting to 2.16 only.
cc @bmatican

**Comment by rthallamko3** [comment]
IMO, Its ok to keep this to 2.16.x+, especially if the backport cost to 2.14 is very high.
