### ISSUE TITLE
[CDCSDK] Before image + packed row causing issues

### ISSUE THREAD

**Issue by adithya-yb** [yugabyte/yugabyte-db#15740]
Jira Link: [DB-5095](https://yugabyte.atlassian.net/browse/DB-5095)

[DB-5095]: https://yugabyte.atlassian.net/browse/DB-5095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sureshdash2022-yb** [comment]
With packed row enabled, if the current schema version is different than before the image schema version, DocDB will fail to decode the packed row.

Here are the steps to reproduce it:- 

1. Table with 5 columns(c1, c2, c3, c4, c5) → 9 AM   —> V1
2. Insert record →9:05
3. Stream is created at  → 9:07
4. Update record c3 → 9:10
5. Alter table drop column c4  —> 9:15     → V2
6. Update record c3 → 9:17
7. Alter table Adding column c8 —> 9:20    → V3
8. Update record  c5 and c8 → 9:22
9. Alter table Adding column c9 —> 9:25   —> V4
10. Update a record c2 and c9  →9:30

GetChanges is failing in after step-10

**Comment by rthallamko3** [comment]
@rknsai-yb , Can you backport the fix to 2.16 branch too? Packed row is GA in 2.16.

**Comment by rthallamko3** [comment]
Did we land the 2.16 backport? cc @rknsai-yb
