### ISSUE TITLE
[DocDB] Harden master leaderless tablet endpoint

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15746]
Jira Link: [DB-5103](https://yugabyte.atlassian.net/browse/DB-5103)
### Description

Currently, the leaderless tablet endpoint could have a high false negative rate, ie: there might be broken tablets in the cluster, which are not reflected in the master's view. This is because practically, the master will only update it's view, if quorums undergo any configuration changes. However to do that, they would need a majority of peers to be alive and able to replicate writes. In the case of majority failures, complex network partitions, or bugs which stall replication, we would not be able to make progress on a change config, leading to a broken quorum, but without reflecting this in the master's view.

Moreover, the semantics of this endpoint should also be tweaked somewhat. Ideally, it should capture any quorum that cannot make progress. It is possible for a tablet to be elected leader, but then fail to replicate it's noop and thus acquire a lease. Related usability/visibility issue: #13700

To that end, we could augment
- TS heartbeat logic, to report the GetConsensusState state and in particular, if the leader has a lease, or what the leader lease is -- we could also piggyback on the metrics heartbeat payload, to regularly send the per-tablet lease information, so the master can known, within some time (5s default), if any leader is not able to replicate its lease!
- Master heartbeat processing logic, to record the leader lease information
- Master leaderless endpoint, to showcase
  - tablets that do not have a leader
  - tablets that have a leader, but it reported it does not have a lease
  - tablets that have a leader, with a valid lease, but we haven't heard since some time T >> lease expiration time

cc @amitanandaiyer @Huqicheng @rthallamko3 @fritshoogland-yugabyte 

[DB-5103]: https://yugabyte.atlassian.net/browse/DB-5103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Huqicheng** [comment]
We can also have last_received_op_id, committed_op_id, etc.

**Comment by druzac** [comment]
Is this supposed to replace the `yugatool` workflow for identifying leaderless tablets? I'm finding very different results vs. that tool. In particular, for a user table with all 6 tablets broken, tablet-replication only reports two leaderless tablets while the `yugatool` reports all 6.

All 6 user tablets are:
```
d168c5021486417f850793a4428b47c2
ae7089feddc84f9a9d025573d1d90ab0
377daf7dab3c4325a1948f14409d63b5
4eba51732dae4c8491ebe13cb8deb888
0aedbec98b1b43dcb8dce94a24c2fb76
c2901e62bdb94b8386e99202c9171a5b
```

tablet-replication only reports `d168c5021486417f850793a4428b47c2` and `0aedbec98b1b43dcb8dce94a24c2fb76`:
<img width="1797" alt="Screenshot 2023-05-24 at 17 52 49" src="https://github.com/yugabyte/yugabyte-db/assets/865068/9c1f9894-be69-426a-afd8-d9d162047a08">

yb version:
```
version 2.19.1.0 build PRE_RELEASE revision f3b24b19d029bc29a2f3638e8be30d169c436426 build_type DEBUG built at 24 May 2023 15:43:20 EST
server uuid 4167bd88c57d49c4b6cdce5f0e1f9792 local time 2023-05-24 16:22:33.029521
```

Yugatool output:
```
% yugatool cluster_info -m 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --show-tableid --tablet-report > tablet_report.txt
% cat tablet_report.txt | grep TABLET_DATA_READY | awk '{print $1}' | sort | uniq > all_tablets
% cat tablet_report.txt | grep HAS_LEASE | awk '{print $1}' | sort | uniq > tablets_with_leaders
% cat all_tablets tablets_with_leaders| sort | uniq -c | sort -rn |awk '$1 < 2 {print $2}' > leaderless_tablets
% cat leaderless_tablets
e7b894d134864f99922d310e71d014c5
d168c5021486417f850793a4428b47c2
d0e5eec61a7341c1b34891b5f6664c35
ce201099a6f941a88f6a5191a42982fd
c8c59045601142229ac3f5cbdd78ec2a
c7060b0b9785478fb7822fcfed53453a
c3dbb70301d840f78ef7e7e585d22ae0
c2901e62bdb94b8386e99202c9171a5b
b41789798d4e454d94823b56ce9be1e4
afb7be4112364e678e53ef072ff2ed5f
ae7089feddc84f9a9d025573d1d90ab0
a74697afab2449ee809eedf93d81ba37
a06fcfb59e4a4ec2a3ca406ecca9d0a5
94496354018947a690a9c76daac4a906
8fa7f0db912c459ca053f446f95fd3ea
7fc258d424bb4f129c1208ef0eca30e3
5a369d24fbd94513883fa2b482aca880
4eba51732dae4c8491ebe13cb8deb888
4a062cbe61354c27a488207bd75d6d95
44f1dbf7511043c392a0fe669326f3cd
3db654a081fb40a1bcea57a828e0d214
3c41fc63eceb40c29bb62b0f33d03e22
3972392ef38d4506a3f95efe98399539
377daf7dab3c4325a1948f14409d63b5
361c1929b4cf423d8c56c28d5a924b1b
2dbd3747183b49be8959f160884a0aea
254a2e20d4ae4fa78a2e80bb083af431
215686223ed54a3887a156dad545f856
1a2a5a0f4d544828b09b89e4ce835f15
0aedbec98b1b43dcb8dce94a24c2fb76
```

Experiment setup:
```
yb-ctl --rf 3 create
ysqlsh -h 127.0.0.1 -p 5433 -c "CREATE TABLE tt (k int primary key, v text); INSERT INTO tt SELECT i, CAST(i as TEXT) FROM generate_series(0, 1000000) AS i;"
for i in $(seq 1 3); do yb-ts-cli --server_address=127.0.0.${i}:9100 flush_all_tablets; done
yb-admin --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_all_tablet_servers
yb-ctl stop_node 2
yb-ctl stop_node 3
rm ~/yugabyte-data/node-2/disk-1/{tserver.err,tserver.out,pg_data,yb-data/tserver}
rm ~/yugabyte-data/node-3/disk-1/{tserver.err,tserver.out,pg_data,yb-data/tserver}
yb-ctl start_node 2
yb-ctl start_node 3
yb-admin --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_all_tablet_servers
```
