### ISSUE TITLE
Make master startup atomic as far as files created on the filesystem

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1575]
Right now, we've had a number of situations in which users are trying us out and hit a master initialization issue, where, due to issues in a previous run/startup, a new start will fail.

During startup, the master code decides if to go in create vs normal restart mode, based on some FS structure and set of files. If during create, not all of these were generated, say due to a crash or some error happening, the master might generate enough metadata to think next time it's in restart mode, but not enough to properly be able to start...

One such example was #1074.

cc @kmuthukk

**Comment by JDNdeveloper** [comment]
Addressed by 483430fdb725a468bdd22eefbedb628c503ed4ba.
