### ISSUE TITLE
[DocDB] Auto trigger major compactions on tablet when overwritten/deleted records hurt performance

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#15776]
Jira Link: [DB-5131](https://yugabyte.atlassian.net/browse/DB-5131)
### Description

**Background**: In use cases involving range scans, if there are several deleted/overwritten records in the range, we can benefit from automatically triggering major compactions (on the tablet/shard). This issue is not specific to tables, but can happen with indexes also. While yb-admin is a manual way of forcing this compaction, we should automatically handle detection of this condition and just automatically handle this internally, rather than rely on diagnosis/human intervention.

**Suggestion**:

In addition to DocDB level `seek, next & prev` metrics, let us also also track `next_expired` & `prev_expired` metrics - these new metrics are meant to represent the number of deleted/expired KVs encountered during a forward or backward scan.

And, if the ratio `next_expired/next` is more than say 0.95 (configurable flag), meaning 95% of the KVs we are stepping over are expired entries (i.e 20x wasteful next operations) and the absolute volume of this is also greater than some threshold to avoid being too trigger happy to initiate a major compaction (say 5000 next's at least), then we schedule this tablet for a full-major compaction.

**Scenarios**
Scenarios where this type of problem can happen includes:

Example 1)  https://github.com/yugabyte/yugabyte-db/issues/15098

Example 2) Say you had an `Offers` table and index `IDX` with schema something like:

`Offers(offer_id PRIMARY KEY, status text, details text)`

`IDX(status)`

And suppose that an offer's `status` column has a lifecyle of moving through three states (like NOT_PUBLISHED --> PUBLISHED --> EXPIRED, etc.). As records (offers) move from one state to the other.. DocDB will leave deleted entries in the index (until major compactions run). And queries to get all offers in a particular status, say NOT_PUBLISHED, keep getting slower and slower.. because we are doing a range scan on the index but it now contains lots of delete tombstones/expired KVs since things have moved from NOT_PUBLISHED to say PUBLISHED state.

[DB-5131]: https://yugabyte.atlassian.net/browse/DB-5131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jmeehan16** [comment]
This issue is tackled in https://github.com/yugabyte/yugabyte-db/commit/e9c9f74dc46f631ce6fd291d7699739405e36046

Planned backport to 2.18, 2.16, and 2.14.

**Comment by rthallamko3** [comment]
@jmeehan16 , Would it make sense to track the backports in the original GH #13786  instead of on this one? So keep the original one active and close this instead?

**Comment by jmeehan16** [comment]
We are taking a "wait and see" approach for backports to 2.14 and 2.16.
If backported, https://github.com/yugabyte/yugabyte-db/commit/bc6682c0229447cfffc7bf8aa6c9d5deb7802ff2 and https://github.com/yugabyte/yugabyte-db/commit/bc6682c0229447cfffc7bf8aa6c9d5deb7802ff2 need to be included as well.
Closing this issue for now.
