### ISSUE TITLE
[DocDB] QLTabletTest.VerifyIndexRange is flaky

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#15771]
Jira Link: [DB-5122](https://yugabyte.atlassian.net/browse/DB-5122)
### Description

[Detective report - Execution history](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=QLTabletTest&name=VerifyIndexRange ) indicates the test is flaky.

[Detective report](https://detective-gcp.dev.yugabyte.com/stability/test?class=QLTabletTest&name=VerifyIndexRange)

[DB-5122]: https://yugabyte.atlassian.net/browse/DB-5122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Was the same issue as #15786, closing for now, can track backports in the other issue.

**Comment by rthallamko3** [comment]
Seems like this is different from https://github.com/yugabyte/yugabyte-db/issues/15786
