### ISSUE TITLE
[YSQL][Unit Test] Failure in org.yb.pgsql.TestPgRegressIndex.testPgRegressIndex: yb_index_scan

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#15785]
Jira Link: [DB-5139](https://yugabyte.atlassian.net/browse/DB-5139)
### Description

Started with change https://phabricator.dev.yugabyte.com/D19273 (https://github.com/yugabyte/yugabyte-db/commit/d7cb73e56fc53c3af39e33806fb22378e65dbbc1) in master.

Example failure: https://detective.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release-aarch64%2F407%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgRegressIndex__testPgRegressIndex%2Forg.yb.pgsql.TestPgRegressIndex-output.txt.gz?class=org.yb.pgsql.TestPgRegressIndex&name=testPgRegressIndex

@tanujnay112 Can you take a look please? It also failed in your change in Detective view (https://detective-gcp.dev.yugabyte.com/D19273), I'm wondering how that slipped through.

```
*** ${TEST_TMPDIR}/pgregress_output/yb_index_serial_schedule/expected/yb_index_scan.out	2023-01-22 05:52:24.494099700 +0000
--- ${TEST_TMPDIR}/pgregress_output/yb_index_serial_schedule/results/yb_index_scan.out	2023-01-22 05:52:24.444099829 +0000
***************
*** 369,375 ****
   1 | 3 | 3
   1 | 2 | 2
   1 | 1 | 1
! (3 rows)
  
  SELECT * FROM sc_desc_nl WHERE yb_hash_code(h) = yb_hash_code(1) AND r < 4;
   h | r | v
--- 369,376 ----
   1 | 3 | 3
   1 | 2 | 2
   1 | 1 | 1
!  1 |   | 6
! (4 rows)
  
  SELECT * FROM sc_desc_nl WHERE yb_hash_code(h) = yb_hash_code(1) AND r < 4;
   h | r | v

======================================================================

05:52:56.909 (Time-limited test) [WARN - org.yb.pgsql.PgRegressRunner.run(PgRegressRunner.java:124)] Failed tests: [yb_index_scan]
```

[DB-5139]: https://yugabyte.atlassian.net/browse/DB-5139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tanujnay112** [comment]
Fixed in 407db566273a28f5a56aab56865e2b0aa99b1d6c
