### ISSUE TITLE
[DocDB] [xCluster DR] Failback step failed and observed core files and unreachable nodes

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15791]
Jira Link: [DB-5154](https://yugabyte.atlassian.net/browse/DB-5154)
### Description

Version: `2.17.1.0-b435`

**Steps**:
1. Executed DR Unplanned failover steps
2. Worked well until Failback step and found below observations when I run the setup replication using bootstrap ids

i. New Source(old Target) is in good condition.
ii. New Target(old Source) : Found below errors in ERROR log
`E0123 12:09:08.519778 25349 tablet_metadata.cc:618] T 8f7d7182e87a4690987f12149e1e3881 P db24261f426e457899d271778e205cd8: Failed to destroy regular DB at: /mnt/d0/yb-data/tserver/data/rocksdb/table-00004005000030008000000000004036/tablet-8f7d7182e87a4690987f12149e1e3881: IO error (yb/rocksdb/util/env_posix.cc:320): /mnt/d0/yb-data/tserver/data/rocksdb/table-00004005000030008000000000004036/tablet-8f7d7182e87a4690987f12149e1e3881/LOCK: No such file or directory`
iii. Found core file in 172.161.42.151
iv. Health check issues- YSQLSH and YCQLSH connectivity issues
v. 2 Nodes are in unreachable state.

[DB-5154]: https://yugabyte.atlassian.net/browse/DB-5154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/9445017eb04643f8cd288c9e9543d21559829dfa

**Comment by ankit-yb** [comment]
Found similar errors in my LRU - 
`E0503 07:26:51.932160  2051 tablet_metadata.cc:675] T b2184a35070a4ca19f9e13e3c282c3cd P c7bfe45e6f234973a6a9ea9563008287: Failed to destroy regular DB at: /mnt/d0/yb-data/tserver/data/rocksdb/table-000033ef000030008000000000004105/tablet-b2184a35070a4ca19f9e13e3c282c3cd: IO error (yb/rocksdb/util/env_posix.cc:320): /mnt/d0/yb-data/tserver/data/rocksdb/table-000033ef000030008000000000004105/tablet-b2184a35070a4ca19f9e13e3c282c3cd/LOCK: No such file or directory
E0503 07:26:51.937772  2051 tablet_metadata.cc:675] T 71db29aee07c4927b5798012a9e4b0de P c7bfe45e6f234973a6a9ea9563008287: Failed to destroy regular DB at: /mnt/d0/yb-data/tserver/data/rocksdb/table-000033ef000030008000000000004105/tablet-71db29aee07c4927b5798012a9e4b0de: IO error (yb/rocksdb/util/env_posix.cc:320): /mnt/d0/yb-data/tserver/data/rocksdb/table-000033ef000030008000000000004105/tablet-71db29aee07c4927b5798012a9e4b0de/LOCK: No such file or directory`
