### ISSUE TITLE
[DocDB] AreLeadersOnPreferredOnly doesn't properly handle row level geopartitioning.

### ISSUE THREAD

**Issue by charleswang234** [yugabyte/yugabyte-db#15794]
Jira Link: [DB-5155](https://yugabyte.atlassian.net/browse/DB-5155)
### Description

Create a 6 node universe with 2 regions (3 nodes in us-east-1 / us-east-1f and 3 nodes in eu-west-1 / eu-west-1b) with leader preferred on all azs).

Add row level geopartitioning.
i.e.
```
CREATE TABLESPACE eu_west_1_tablespace WITH (
  replica_placement='{"num_replicas": 3, "placement_blocks":
  [{"cloud":"aws","region":"eu-west-1","zone":"eu-west-1b","min_num_replicas":3}]}'
);

CREATE TABLESPACE us_east_1_tablespace WITH (
  replica_placement='{"num_replicas": 3, "placement_blocks":
  [{"cloud":"aws","region":"us-east-1","zone":"us-east-1f","min_num_replicas":3}]}'
);

CREATE TABLE bank_transactions (
    user_id   INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    geo_partition VARCHAR,
    account_type VARCHAR NOT NULL,
    amount NUMERIC NOT NULL,
    txn_type VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
) PARTITION BY LIST (geo_partition);

CREATE TABLE bank_transactions_eu
    PARTITION OF bank_transactions
      (user_id, account_id, geo_partition, account_type,
      amount, txn_type, created_at,
      PRIMARY KEY (user_id HASH, account_id, geo_partition))
    FOR VALUES IN ('EU') TABLESPACE eu_west_1_tablespace;

CREATE INDEX ON bank_transactions_eu(account_id) TABLESPACE eu_west_1_tablespace;


CREATE TABLE bank_transactions_us
    PARTITION OF bank_transactions
      (user_id, account_id, geo_partition, account_type,
      amount, txn_type, created_at,
      PRIMARY KEY (user_id HASH, account_id, geo_partition))
    FOR VALUES IN ('US') TABLESPACE us_east_1_tablespace;

CREATE INDEX ON bank_transactions_us(account_id) TABLESPACE us_east_1_tablespace;
```

Expand universe from 6 nodes to 9 nodes (adding 3 nodes in ap-northeast-1 / ap-northeast-1c with leader pref)

In YBA, when checking for `areLeadersOnPreferredOnly`, it fails the check. 
Sample example in logs:
```
org.yb.client.MasterErrorException: Server[YB Master - 172.159.41.234:7100] ILLEGAL_STATE[code 9]: Tserver 49b1028765864270a4cfded8aaa28c15 expected to have at least 18 txn status leader(s), but has 6..
```

Quoting @hulien22 : Transaction status tablet leaders should be evenly distributed across all tablets, which is not the case for these tablespace transaction tables

Slack issue: https://yugabyte.slack.com/archives/C4K1838GL/p1674256662160489

cc @sanketh @Arnav15 

[DB-5155]: https://yugabyte.atlassian.net/browse/DB-5155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hulien22** [comment]
Also worth mentioning that `FLAGS_transaction_tables_use_preferred_zones` is set to `false` which causes issues for `AreLeadersOnPreferredOnly` as that function expects that in this case all txn status tablet leaders are evenly distributed - however tablespaces and their transaction status tables don't follow this flag, thus breaking that logic and causing the error:

```
Tserver 49b1028765864270a4cfded8aaa28c15 expected to have at least 18 txn status leader(s), but has 6.
```
