### ISSUE TITLE
[YSQL] Fix ANALYZE after DROP COLUMN

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#15821]
Jira Link: [DB-5214](https://yugabyte.atlassian.net/browse/DB-5214)
### Description

ANALYZE fails after dropping a column on that table:

    ERROR:  cache lookup failed for type 0

Simple repro:

```sql
create table analyzetest (i int, j int);
alter table analyzetest drop j;
analyze analyzetest;
```

See also issue #15820.

[DB-5214]: https://yugabyte.atlassian.net/browse/DB-5214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by qvad** [comment]
We have a duplicate for this case https://github.com/yugabyte/yugabyte-db/issues/13467
