### ISSUE TITLE
[YSQL] Flaky test: org.yb.pgsql.TestPgCatalogConsistency.testAlterTable

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15832]
Jira Link: [DB-5222](https://yugabyte.atlassian.net/browse/DB-5222)
### Description

Test case org.yb.pgsql.TestPgCatalogConsistency.testAlterTable has been consistently failing, mostly on MacOS.

Error: java.lang.AssertionError

[DB-5222]: https://yugabyte.atlassian.net/browse/DB-5222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by emhna** [comment]
Test is sometimes reproducible when ran on 100 iterations.
Closing the case as the test failure happens on rare occasions.
