### ISSUE TITLE
[YSQL] Flaky test: PgMiniTest.NonRespondingMaster

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15830]
Jira Link: [DB-5220](https://yugabyte.atlassian.net/browse/DB-5220)
### Description

The test case PgMiniTest.NonRespondingMaster has been flaky since at least 10/2022, mostly on alma8-clang15-debug-aarch64 but also less frequently on other build types. Starting with backup / restore team.

Error: yb_backup.py error: Backup exception: No Live Tserver exists. Check the tserver nodes status & try again.

[DB-5220]: https://yugabyte.atlassian.net/browse/DB-5220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
Reproduced. This happens because `yb-admin list_all_tablet_servers` returns an empty list of TSes.

**Comment by OlegLoginov** [comment]
Fixed. Backports are not needed because the fix is entirely in `yb_backup.py`.

**Comment by OlegLoginov** [comment]
(The mentioning in https://github.com/yugabyte/yugabyte-db/issues/16163 was by mistake.)
