### ISSUE TITLE
[DocDB] Flaky test: TestRpcSecureCompression.CantAllocateReadBuffer

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15833]
Jira Link: [DB-5223](https://yugabyte.atlassian.net/browse/DB-5223)
### Description

Test case TestRpcSecureCompression.CantAllocateReadBuffer has been failing since at least 10/2022, mostly on MacOS builds

Error: Bad status: Timed out (yb/util/backoff_waiter.cc:75): Operation 'Waiting until memory consumption is less than 60.00M ...' didn't complete within 10023ms

[DB-5223]: https://yugabyte.atlassian.net/browse/DB-5223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Doesn't show up at all in last 25 commits in /stability: https://detective-gcp.dev.yugabyte.com/stability?branch=master&num_commits=25&platform=linux&sort=default&threshold=0
