### ISSUE TITLE
[DocDB] flaky test: org.yb.cql.TestTransaction.testTimeout

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15839]
Jira Link: [DB-5236](https://yugabyte.atlassian.net/browse/DB-5236)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.cql.TestTransaction&fail_tag=all&name=testTimeout&platform=linux

[DB-5236]: https://yugabyte.atlassian.net/browse/DB-5236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
test
