### ISSUE TITLE
Confusing Add Universe GUI

### ISSUE THREAD

**Issue by stevenarvar** [YugaByte/yugabyte-db#1583]
There is this large Add Universe button which is divided into top and bottom part. The top part is create new universe and the bottom part is import universe. Excepted that there is no visual indication to their meaning. First time user as I was find it confusing as I hit the bottom part all the time at first but I needed the top part.

Feature Request
When mouse hover over top part, the top part gets high lighted and a text displays create and when hover over bottom text shows import.

Though I still don’t like that button with the feature request. The graphics suggest a single action, but it is actually two different actions.

**Comment by stevenarvar** [comment]
https://forum.yugabyte.com/t/add-universe-gui-is-confusing/414

**Comment by yb-andrew** [comment]
@rkarthik007 Why not make the create universe buttons consist with the list universe page?
Example:
![dashboard-create-universe](https://user-images.githubusercontent.com/50115930/60748260-cbf40100-9f40-11e9-93b1-c9cbaf5e80d5.png)

**Comment by rkarthik007** [comment]
Sounds directionally right! I think we may need some design work on that.

cc @ivanjovanic @ramkumarvs.

**Comment by stevenarvar** [comment]
That looks good to me as well.

**Comment by ivanjovanic** [comment]
To be implemented:
![Add Universe - A@2x](https://user-images.githubusercontent.com/47860492/62136075-ad84e980-b2e3-11e9-8b6e-8f536f8a41a7.png)
