### ISSUE TITLE
[Docs] Update python code used for connecting sample python application using YCQL

### ISSUE THREAD

**Issue by Nithinignatius** [yugabyte/yugabyte-db#15836]
### Description

Doc URL: https://docs.yugabyte.com/preview/drivers-orms/python/ycql/

Version of doc affected:  v2.17, v2.16

Issue: 

If TLS and password auth is on then the python code in the doc does not work for a user as we are not passing parameters like password, username and path to cert file. So we should document the additional code used for passing these parameters.

Code which adds the extra parameters:
```
from cassandra.cluster import Cluster
from ssl import SSLContext, PROTOCOL_TLS_CLIENT, CERT_REQUIRED
from cassandra.auth import PlainTextAuthProvider

ssl_context = SSLContext(PROTOCOL_TLS_CLIENT)
ssl_context.load_verify_locations(‘path to certs file’)
ssl_context.verify_mode = CERT_REQUIRED

cluster = Cluster(contact_points=['ip address’],
    ssl_context=ssl_context,
    ssl_options={'server_hostname': 'ip address’},
    auth_provider=PlainTextAuthProvider(username=‘username’, password=‘password’))
session = cluster.connect()
```

**Comment by polarweasel** [comment]
We can do this like the YSQL python drivers: just add a sub-section for SSL, and show how the connection differs. It's just two more imports and three extra arguments on the Cluster() creation.

**Comment by Nithinignatius** [comment]
That works fine.
