### ISSUE TITLE
[YSQL] Flaky test: org.yb.pgsql.TestPgRegressTypesMisc.testPgRegressTypes - yb_pg_inet_ipv4only

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#15831]
Jira Link: [DB-5221](https://yugabyte.atlassian.net/browse/DB-5221)
### Description

The yb_pg_inet_ipv4only test in the test suite org.yb.pgsql.TestPgRegressTypesMisc.testPgRegressTypes as been consistently failing on MacOS.

Error: 
java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb_pg_inet_ipv4only]

[DB-5221]: https://yugabyte.atlassian.net/browse/DB-5221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
YB output
https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/test/regress/expected/inet.out#L46-L66
PG output

https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/test/regress/expected/yb_pg_inet_ipv4only.out#L33-L51

**Comment by myang2021** [comment]
On centos:

```
$ $TOP/bin/ysqlsh -X -a -q -d "yugabyte" < $TOP/src/postgres/src/test/regress/sql/yb_pg_inet_ipv4only.sql > /tmp/centos.out 2>& 1
$ sha1sum /tmp/centos.out
bbd575532e24905643dc179497876172870d2759  /tmp/centos.out

```

On mac:

```
$TOP/bin/ysqlsh -X -a -q -d "yugabyte" < $TOP/src/postgres/src/test/regress/sql/yb_pg_inet_ipv4only.sql > /tmp/mac.ysqlsh.out 2>& 1
$ sha1sum /tmp/mac.ysqlsh.out
bbd575532e24905643dc179497876172870d2759  /tmp/mac.ysqlsh.out
```
We can see that the two output files are identical.

Now compare PG output:

```
$ psql --version
psql (PostgreSQL) 14.7 (Homebrew)
$ psql -h localhost -U postgres -X -a -q -d "yugabyte" < $TOP/src/postgres/src/test/regress/sql/yb_pg_inet_ipv4only.sql > /tmp/mac.pg.out 2>& 1
$ diff /tmp/mac.pg.out /tmp/mac.ysqlsh.out
345,346c345,346
<                   QUERY PLAN
< -----------------------------------------------
---
>                       QUERY PLAN
> ------------------------------------------------------
350c350
<          Filter: (i << '192.168.1.0/24'::inet)
---
>          Remote Filter: (i << '192.168.1.0/24'::inet)
478,479c478,479
<                   QUERY PLAN
< -----------------------------------------------
---
>                       QUERY PLAN
> ------------------------------------------------------
483c483
<          Filter: (i << '192.168.1.0/24'::inet)
---
>          Remote Filter: (i << '192.168.1.0/24'::inet)

```

The output is changed from `Filter` to `Remote Filter`, seems expected.

My conclusion is that this is a test log update.

**Comment by m-iancu** [comment]
@myang2021 Thanks for checking. Interestingly on my Mac the results are significantly different -- see the diff here: https://gist.github.com/m-iancu/19df184cb394e3ad41ebfe7a02fcc7b0

Also, if the difference is between Filter and Remote Filter, then why does it only fail on Mac -- do we have any os-specific logic at the query processing layer? See: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.pgsql.TestPgRegressTypesMisc&name=testPgRegressTypes

**Comment by myang2021** [comment]
@m-iancu We run `yb_pg_inet.sql` on Linux but `yb_pg_inet_ipv4only.sql` on mac:

From java/yb-pgsql/src/test/java/org/yb/pgsql/PgRegressBuilder.java:
```
          if (line.equals("test: yb_pg_inet") && !SystemUtil.IS_LINUX) {
            // We only support IPv6-specific tests in yb_pg_inet.sql on Linux,
            line = "test: yb_pg_inet_ipv4only";
          
```

**Comment by myang2021** [comment]
@m-iancu what version of psql does your mac has? Mine is

```
$ psql --version
psql (PostgreSQL) 14.7 (Homebrew)
```
And this version produced output identical to that of ysqlsh except for the `Remote Filter` change.

**Comment by m-iancu** [comment]
@myang2021 I'm testing with 11 for compatibility:
```
$ psql --version
psql (PostgreSQL) 11.20
```
However this may be a build/configuration issue on my side -- I had a few other issues and needed to update some packages previously.

> @m-iancu We run yb_pg_inet.sql on Linux but yb_pg_inet_ipv4only.sql on mac:

Got it, this explains a lot!

**Comment by m-iancu** [comment]
@myang2021 Just as a minimal repro on my Mac. For the following:
```
CREATE TABLE INET_TBL (c cidr, i inet);
INSERT INTO INET_TBL (c, i) VALUES ('10', '9.1.2.3/8');
SELECT '' AS ten, c AS cidr, i AS inet FROM INET_TBL;
```
the select returns:
```
 ten |    cidr    |   inet
-----+------------+-----------
     | 10.0.0.0/8 | 9.1.2.3/8
(1 row)
```
This works the same for me in both Yugabyte (both build locally and downloaded from https://download.yugabyte.com/#/) and in Postgres 11. This also seems consistent with PG docs. But it seems our test expects:
```
 ten |      cidr      |       inet
-----+----------------+------------------
     | 10/8           | 9/8
```
for that row -- based on: https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/test/regress/expected/yb_pg_inet_ipv4only.out#L37

I am sure I'm missing something, but not sure yet what it is :)

**Comment by myang2021** [comment]
@m-iancu I think that log isn't right and needs to be updated because it is not consistent with what PG produces. I have no idea how that test log was initially generated and has the test ever passed on Mac historically.
