### ISSUE TITLE
[DocDB] Fix TransactonParticipant Poller deadlock

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15849]
Jira Link: [DB-5245](https://yugabyte.atlassian.net/browse/DB-5245)
### Description

In a recent incident, we uncovered a deadlock on the master side. From the raft perspective, the masters were able to elect a leader. However, once elected leader, the CatalogManager component needs to go through a Loading phase, before it can start serving RPC traffic. As part of the Loader code, we can sometimes execute some migration code, if we detect inconsistencies for the on disk data.

One example of such inconsistency would be a crash during a DROP TABLE command. We might have persisted a change to the TableInfo objects to move to DELETING state, but then crashed before persisting the changes to the constituent tablets, to also move them to DELETED state. Then on the new master leader, we would try to migrate the tablets forward to the DELETED state.

This lead to the following deadlock
- Thread1: TabletLoader code triggering a state transition write
```
    @     0x7f0be53c56e2  __GI___pthread_mutex_lock
    @     0x7f0be5ba8478  std::__1::mutex::lock()
    @     0x7f0bea184d6b  yb::tablet::TransactionParticipant::RegisterRequest()
    @     0x7f0bea11d1f0  yb::RequestScope::Create()
    @     0x7f0bea1d978b  yb::tablet::WriteQuery::DoExecute()
    @     0x7f0bea1d91e5  yb::tablet::WriteQuery::Execute()
    @     0x7f0bea11d4a5  yb::tablet::Tablet::AcquireLocksAndPerformDocOperations()
    @     0x7f0bea1591c9  yb::tablet::TabletPeer::WriteAsync()
    @     0x7f0bea793298  yb::master::SysCatalogTable::SyncWrite()
    @     0x7f0bea640a10  yb::master::SysCatalogTable::Mutate&lt;&gt;()
    @     0x7f0bea6d70e2  yb::master::TabletLoader::Visit()
    @     0x7f0bea6dc726  yb::master::Visitor&lt;&gt;::Visit()
    @     0x7f0bea7984de  std::__1::__function::__func&lt;&gt;::operator()()
    @     0x7f0bea7adfd8  yb::master::EnumerateSysCatalog()
    @     0x7f0bea7ada85  yb::master::EnumerateSysCatalog()
```
- Thread2: Background thread starting txn resolution for the sys_catalog tablet
```
    @     0x7f0be5ba6930  std::__1::__assoc_sub_state::__sub_wait()
    @     0x7f0bea0f1dba  std::__1::__assoc_state&lt;&gt;::copy()
    @     0x7f0bea195c1b  yb::tablet::TransactionStatusResolver::Impl::Execute()
    @     0x7f0bea19572f  yb::tablet::TransactionStatusResolver::Start()
    @     0x7f0bea178f3f  yb::tablet::TransactionParticipant::Impl::Poll()
    @     0x7f0be763950f  yb::rpc::Poller::Poll()
    @     0x7f0be7664772  _ZN5boost4asio6detail18completion_handlerIZN2yb3rpc9Scheduler4Impl11HandleTimerERKNS_6system10error_codeEEUlvE_NS0_10io_context19basic_executor_typeINSt3__19allocatorIvEELm0EEEE11do_completeEPvPNS1_19scheduler_operationESA_m
    @     0x7f0be76224fc  boost::asio::detail::scheduler::run()
    @     0x7f0be7621f24  yb::rpc::IoThreadPool::Impl::Execute()
    @     0x7f0be7299000  yb::Thread::SuperviseThread()
    @     0x7f0be53c3693  start_thread
    @     0x7f0be4b0041c  __clone
```

Breaking down the steps
- Thread2 needs to start txn resolution for the txn participant of the sys_catalog tablet.
- This requires an instance of yb-client.
- To fully initialize the client, it must be able to contact the masters and find a leader, via a GetMasterRegistration RPC.
- While the masters had a leader, at raft level, said leader was not ready to serve RPCs, as it was still busy executing the loading code.
- Finally, thread1, which is doing the loading, is stuck trying to execute a write, which requires to register a txn with the participant, of the same sys_catalog tablet.

**Operational solution**: On the masters, we can temporarily disable the part of txn resolution which needs a yb-client, which is the aborted txn polling, by setting `transactions_poll_check_aborted=false`.

**Incoming code fix**: We discussed internally, that we should move the migration writes, outside of the CatalogLoader code. Aside from this deadlock risk, these writes also would delay the master leader starting to serve RPCs, by adding network & disk IO in the critical path.

[DB-5245]: https://yugabyte.atlassian.net/browse/DB-5245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Related to #14995
