### ISSUE TITLE
[DocDB] txn_slow_op_threshold_ms includes time spent waiting in transaction pool

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#15842]
Jira Link: [DB-5240](https://yugabyte.atlassian.net/browse/DB-5240)
### Description

The txn_slow_op_threshold_ms gflag includes time the transaction spent in the transaction pool before being taken. This results in "slow" transactions being logged that merely spent a long time waiting for a transaction to be needed, regardless of whether or not it actually took a long time to execute.

This flag should be changed to only start counting time from when the transaction was actually taken.

[DB-5240]: https://yugabyte.atlassian.net/browse/DB-5240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
Changed with 2928196.

**Comment by rthallamko3** [comment]
Reactivating for backports to stable branches.
