### ISSUE TITLE
[DocDB] flaky test: SnapshotTest.SnapshotRemoteBootstrap

### ISSUE THREAD

**Issue by yusong-yan** [yugabyte/yugabyte-db#15846]
Jira Link: [DB-5242](https://yugabyte.atlassian.net/browse/DB-5242)
### Description

Test SnapshotTest.SnapshotRemoteBootstrap is flaky. 

[Detective report](https://detective-gcp.dev.yugabyte.com/stability/test?class=SnapshotTest&name=SnapshotRemoteBootstrap)

[Trends](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=SnapshotTest&name=SnapshotRemoteBootstrap)

[DB-5242]: https://yugabyte.atlassian.net/browse/DB-5242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Seems like a test issue, where we're not accounting for tablets that are shutting down correctly.
```
Bad status: Illegal state (yb/tablet/tablet_peer.cc:662): The tablet is already shutting down or shutdown. State: QUIESCING
Google Test trace:
../../ent/src/yb/integration-tests/snapshot-test.cc:317: Tablet: {snapshot_test_table_tablet_id1}
../../ent/src/yb/integration-tests/snapshot-test.cc:312: TServer: 0
Test failure stack trace:
@ 0xffffaebe0494 testing::internal::TestEventRepeater::OnTestPartResult()
@ 0xffffaebe72c8 testing::UnitTest::AddTestPartResult()
@ 0xffffaebe6aec testing::internal::AssertHelper::operator=()
@ 0xaaaac01b3780 _ZNSt3__110__function6__funcIZN2yb12SnapshotTest19VerifySnapshotFilesERKNS2_17StronglyTypedUuidINS2_17TxnSnapshotId_TagEEEEUlvE0_NS_9allocatorIS9_EEFNS2_6ResultIbEEvEEclEv
@ 0xffffaea183fc yb::Wait()
@ 0xaaaac01b0640 yb::SnapshotTest::VerifySnapshotFiles()
@ 0xaaaac01af6a8 yb::SnapshotTest_SnapshotRemoteBootstrap_Test::TestBody()
@ 0xffffaebff070 testing::internal::HandleExceptionsInMethodIfSupported<>()
@ 0xffffaebfef34 testing::Test::Run()
@ 0xffffaebffdd8 testing::TestInfo::Run()
@ 0xffffaec0058c testing::TestSuite::Run()
@ 0xffffaec0e5d0 testing::internal::UnitTestImpl::RunAllTests()
@ 0xffffaec0deb0 testing::UnitTest::Run()
@ 0xffffb3ca2c68 (unknown)
@ 0xffffad27485c __libc_start_main
@ 0xaaaac019ee54 (unknown)
```
Given how the test is structured, where an RBS will start once the old TS is started back up, we should probably harden the test code to expect that tablets might be in transition (ie: LB might move them off of some nodes and we can have races in the validation code).

**Comment by bmatican** [comment]
Hey @yamen-haddad , I passed this to you, as it should be an easy test fix, but get you familiar with how to run the tests, as well as some of the logic around tablet movement, RBS, tablet state machine, etc.
