### ISSUE TITLE
[YCQL] CQL query from driver fails with Wrong Metadata Version after 5k records

### ISSUE THREAD

**Issue by dr0pdb** [yugabyte/yugabyte-db#15874]
Jira Link: [DB-5279](https://yugabyte.atlassian.net/browse/DB-5279)
Jira Link: [DB-4997](https://yugabyte.atlassian.net/browse/DB-4997)
### Description

While running the select queries etc from the cassandra driver version: '3.8.0-yb-7' on YB DB version 2.14.x it throws an error below. 

```
Exception in thread "main" com.datastax.driver.core.exceptions.InvalidQueryException: Wrong Metadata Version: Table has been altered. Execute the query again. Requested schema version 0, got 20. (ql error -303)
```

This issue is not happening in older YB versions i.e 2.6.x. 

[DB-5279]: https://yugabyte.atlassian.net/browse/DB-5279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DB-4997]: https://yugabyte.atlassian.net/browse/DB-4997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by muralisrini** [comment]
We are seeing error very similar to this one (select query without index, apperently on 5000 records boundary) in 2.20.7.2-b1. Is this expected to be fixed in that version ?
