### ISSUE TITLE
[DocDB] Secondary index range scan latencies with bigint datatype for the same number of rows filtered are 2x Pkey range scan latencies. Whereas for postgres the difference in latencies are within 5% range. (ScanG2 vs ScanG3)

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#15875]
Jira Link: [DB-5281](https://yugabyte.atlassian.net/browse/DB-5281)
### Description

Secondary index range scan latencies with bigint datatype for the same number of rows filtered are 2x Pkey range scan latencies. Whereas for postgres the difference in latencies are within 5% range. (ScanG2 vs ScanG3)

Goals | Query | Postgres 14.4 (r6i- 8 cores)Single(ms)Encryption: Enabled | Regular tables | Colocated tables | PG vs YB - Regular table ratio | PG vs YB - Colocated table ratio
-- | -- | -- | -- | -- | -- | --
Primary key range scan - Varying number of rows | Range scan time to fetch 100k rows | 228 | 507 | 1,011.36 | 2.22 | 4.44
Primary key range scan - Varying number of rows | Range scan time to fetch 500k rows | 1139 | 2542 | 5,261.15 | 2.23 | 4.62
Primary key range scan - Varying number of rows | Range scan time to fetch 1M rows | 2249 | 5268 | 10,637.18 | 2.34 | 4.73
Indexed column range scan - Varying number of rows | Range scan time to fetch 100k rows | 221 | 947 | 1928 | 4.29 | 8.72
Indexed column range scan - Varying number of rows | Range scan time to fetch 500k rows | 1151 | 5208 | 9589.86 | 4.52 | 8.33
Indexed column range scan - Varying number of rows | Range scan time to fetch 1M rows | 2393 | 10788 | 19170 | 4.51 | 8.01

Schema Details:

- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG2_yb_pkey_rangeScan_increasingRows.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG3_yb_index_rangeScan_increasingRows.yaml

[DB-5281]: https://yugabyte.atlassian.net/browse/DB-5281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Here are the numbers from a more recent master build, the difference is no longer 2x.

Scan G2 plan: scanG2_pkey_rangescan_varying_rows_1Mrows_(scanG2_pkey_rangeScan_increasingRows(v1.0))
```
Index Scan using pkey_rangescan_tbl_1_pkey on public.pkey_rangescan_tbl_1  (cost=0.00..4.11 rows=1 width=8) (actual time=1.051..998.248 rows=999999 loops=1)
  Output: col_bigint_id_1
  Index Cond: (pkey_rangescan_tbl_1.col_bigint_id_1 > 1)
  Storage Index Read Requests: 978
  Storage Index Execution Time: 656.997 ms
Planning Time: 0.050 ms
Execution Time: 1051.507 ms
Storage Read Requests: 978
Storage Write Requests: 0
Storage Execution Time: 656.997 ms
Peak Memory Usage: 8 kB

```

Scan G3 plan: scanG3_indx_rangescan_varying_rows_1Mrows_(scanG3_index_rangeScan_increasingRows(v1.0))
```
Index Only Scan using indx_rangescan_tbl_1_col_bigint_id_1_idx on public.indx_rangescan_tbl_1  (cost=0.00..5.12 rows=10 width=8) (actual time=0.851..670.078 rows=999999 loops=1)
  Output: col_bigint_id_1
  Index Cond: (indx_rangescan_tbl_1.col_bigint_id_1 > 1)
  Heap Fetches: 0
  Storage Index Read Requests: 977
  Storage Index Execution Time: 487.998 ms
Planning Time: 0.039 ms
Execution Time: 721.885 ms
Storage Read Requests: 977
Storage Write Requests: 0
Storage Execution Time: 487.998 ms
Peak Memory Usage: 0 kB

```

**Comment by rthallamko3** [comment]
@shantanugupta-yb , Can you check if this is still relevant?

**Comment by rthallamko3** [comment]
Recent [report](https://perf.dev.yugabyte.com/report/view/W3siZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQiIsInRlc3RfaWQiOjQ5OTgwMDJ9LHsiZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQi1DT0xPIiwidGVzdF9pZCI6NDk5ODgwMn0seyJkZXNjcmlwdGlvbiI6IiIsImlzQmFzZWxpbmUiOnRydWUsImpzb24iOiIiLCJuYW1lIjoiUEciLCJ0ZXN0X2lkIjo0Njg4NTAyfV0=) from master do not show this discrepancy. The scan improvements has resolved this.
