### ISSUE TITLE
[DocDB] Pkey/Secondary index range scan latencies with bigint datatype on a co-located table is 2X of regular YB tables (ScanG2) (ScanG3)

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#15876]
Jira Link: [DB-5282](https://yugabyte.atlassian.net/browse/DB-5282)
### Description

Pkey range scan latencies with bigint datatype on a co-located table is 2X of regular YB tables (ScanG2)
Secondary index range scan latencies with bigint datatype on a co-located table is 2X of regular YB tables (ScanG3)

Goals | Query | Regular tables | Colocated tables | PG vs YB - Regular table ratio | PG vs YB - Colocated table ratio
-- | -- | -- | -- | -- | --
Primary key range scan - Varying number of rows | Range scan time to fetch 100k rows | 507 | 1,011.36 | 2.22 | 4.44
Primary key range scan - Varying number of rows | Range scan time to fetch 500k rows | 2542 | 5,261.15 | 2.23 | 4.62
Primary key range scan - Varying number of rows | Range scan time to fetch 1M rows | 5268 | 10,637.18 | 2.34 | 4.73
Indexed column range scan - Varying number of rows | Range scan time to fetch 100k rows | 947 | 1928 | 4.29 | 8.72
Indexed column range scan - Varying number of rows | Range scan time to fetch 500k rows | 5208 | 9589.86 | 4.52 | 8.33
Indexed column range scan - Varying number of rows | Range scan time to fetch 1M rows | 10788 | 19170 | 4.51 | 8.01

YB release: (2.17.1.0-b44)
Cluster details: m6i 2xlarge | packedColumns | tabletSpliting | leader affinity | 1 AZ
Schema details:

- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG2_yb_pkey_rangeScan_increasingRows.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yb_colocated/scanG2_colo_pkey_rangeScan_increasingRows.yaml

- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG3_yb_index_rangeScan_increasingRows.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yb_colocated/scanG3_colo_index_rangeScan_increasingRows.yaml

[DB-5282]: https://yugabyte.atlassian.net/browse/DB-5282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lnguyen-yugabyte** [comment]
Could you check if in both cases the table is created with a single shard only?

**Comment by rthallamko3** [comment]
@sushantrmishra , The index scan issues should correspond to LRT right? Assigning it to you for now.

**Comment by rthallamko3** [comment]
@shantanugupta-yb , The colocated latencies being 2x is due to the lack of parallelism, when compared to regular tables. Can you update this issue to track the secondary index scan issue only?

**Comment by rthallamko3** [comment]
@shantanugupta-yb , The colocated latencies being 2x is due to the lack of parallelism, when compared to regular tables. Can you update this issue to track the secondary index scan issue only? cc @hbhanawat

**Comment by rthallamko3** [comment]
Based on the [report](https://perf.dev.yugabyte.com/report/view/W3siZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQiIsInRlc3RfaWQiOjQ5OTgwMDJ9LHsiZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQi1DT0xPIiwidGVzdF9pZCI6NDk5ODgwMn0seyJkZXNjcmlwdGlvbiI6IiIsImlzQmFzZWxpbmUiOnRydWUsImpzb24iOiIiLCJuYW1lIjoiUEciLCJ0ZXN0X2lkIjo0Njg4NTAyfV0=) from master builds 2.23.1.0, this is no longer relevant.
