### ISSUE TITLE
[DocDB] Pkey/Secondary index range scan latencies with bigint datatype are ~35%/~25% higher than varchar datatype of 100 character length.

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#15880]
Jira Link: [DB-5285](https://yugabyte.atlassian.net/browse/DB-5285)
### Description

Pkey/Secondary index range scan latencies with bigint datatype are ~35%/~25% higher than varchar datatype of 100 character length.

<google-sheets-html-origin><style type="text/css"></style>

Query | Datatype | Regular tables | Colocated tables
-- | -- | -- | --
Impact on range lookups using single primary key of bigint vs varchar datatype | Bigint | 2,249.00 | 10,637.18
Impact on range lookups using single primary key of bigint vs varchar datatype | Varchar(100) | 2,428.94 | 6,970.67
Impact on range lookups using single secondary key of bigint vs varchar datatype | Bigint | 2,393.00 | 19,436.54
Impact on range lookups using single secondary key of bigint vs varchar datatype | Varchar(100) | 2,436.38 | 14,239.87

YB release: (2.17.1.0-b44)
Cluster details: m6i 2xlarge | packedColumns | tabletSpliting | leader affinity | 1 AZ
Schema details:

- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG2_yb_pkey_rangeScan_increasingRows.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG3_yb_index_rangeScan_increasingRows.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workload_varchar/yb_colocated/scanVG2_ybc_pkey_rangeScan_increasingRows.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workload_varchar/yb_colocated/scanVG3_ybc_index_rangeScan_increasingRows.yaml

[DB-5285]: https://yugabyte.atlassian.net/browse/DB-5285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Checked the [report](https://perf.dev.yugabyte.com/report/view/W3siZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQiIsInRlc3RfaWQiOjQ5OTgwMDJ9LHsiZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQi1DT0xPIiwidGVzdF9pZCI6NDk5ODgwMn0seyJkZXNjcmlwdGlvbiI6IiIsImlzQmFzZWxpbmUiOnRydWUsImpzb24iOiIiLCJuYW1lIjoiUEciLCJ0ZXN0X2lkIjo0Njg4NTAyfV0=) on master. This is no longer relevant with the scan improvements in place.
