### ISSUE TITLE
[docdb] Sync rocksdb files for newly bootstrapped files.

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1588]
Jira Link: [DB-2003](https://yugabyte.atlassian.net/browse/DB-2003)
Some of the tablets are in a bad state with this error in the tablets page of the tserver after a stress test pushed the memory usage beyond the normal usage on one of the nodes.

**FAILED (TABLET_DATA_READY): Illegal state (yb/tablet/tablet.cc:535): (yb/rocksdb/db/version_set.cc:2519): CURRENT file does not end with newline**

**Comment by bmatican** [comment]
@spolitov @ttyusupov @mbautin seeing as this leads to not being able to open the tablet, should we consider writes to this, going through fsync?

**Comment by kutayzorlu** [comment]
I got the same error also,  After incident shutdown of the tserver. 

Also this makes to many logs at server side,

**Comment by likenamehaojie** [comment]
The same error 

when i use helm3 install on k8s 

Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6576): Node c30585a740464ce78188a9bbf20ba308 peer not initialized.
I0722 09:04:55.189481    33 db_impl.cc:751] T 00000000000000000000000000000000 P c30585a740464ce78188a9bbf20ba308 [R]: Shutdown done
E0722 09:04:55.189956    33 master.cc:241] Master@10.244.1.163:7100: Unable to init master catalog manager: IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /mnt/disk0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0
W0722 09:04:55.435078    34 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6576): Node c30585a740464ce78188a9bbf20ba308 peer not initialized.
F0722 09:04:55.547295     1 master_main.cc:118] IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /mnt/disk0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0
Fatal failure details written to /mnt/disk0/yb-data/master/logs/yb-master.FATAL.details.2020-07-22T09_04_55.pid1.txt
F20200722 09:04:55 ../../src/yb/master/master_main.cc:118] IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /mnt/disk0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0
    @     0x7f26c666de6c  yb::LogFatalHandlerSink::send()
    @     0x7f26c583f346  google::LogMessage::SendToLog()
    @     0x7f26c583c7aa  google::LogMessage::Flush()
    @     0x7f26c583f879  google::LogMessageFatal::~LogMessageFatal()
    @           0x408ddd  yb::master::MasterMain()
    @     0x7f26c1447825  __libc_start_main
    @           0x4082b9  _start
    @              (nil)  (unknown)
*** Check failure stack trace: ***
W0722 09:04:55.581420    34 scoped_leader_shared_lock.cc:114] Long lock of catalog manager: 0.112s
    @     0x7f26d0568490  yb::master::ScopedLeaderSharedLock::Unlock()
    @     0x7f26d05a8bd1  yb::master::ScopedLeaderSharedLock::~ScopedLeaderSharedLock()
    @     0x7f26d05a59e1  yb::master::MasterServiceImpl::TSHeartbeat()
    @     0x7f26c9e74f96  yb::master::MasterServiceIf::Handle()
    @     0x7f26c7eafcf9  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f26c7e53e04  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f26c7ebb948  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f26c66fc7af  yb::Thread::SuperviseThread()
    @     0x7f26c1dd7694  start_thread
    @     0x7f26c150d41d  __clone
    @              (nil)  (unknown)
    @     0x7f26c666c251  yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7f26c583cc5d  google::LogMessage::Fail()
    @     0x7f26c583edcd  google::LogMessage::SendToLog()
    @     0x7f26c583c7aa  google::LogMessage::Flush()
    @     0x7f26c583f879  google::LogMessageFatal::~LogMessageFatal()
    @           0x408ddd  yb::master::MasterMain()
    @     0x7f26c1447825  __libc_start_main
    @           0x4082b9  _start
    @              (nil)  (unknown)
*** Aborted at 1595408696 (unix time) try "date -d @1595408696" if you are using GNU date ***
PC: @     0x7f26c145b5a6 __GI_abort
*** SIGSEGV (@0x0) received by PID 1 (TID 0x7f26d0d8ab40) from PID 0; stack trace: ***
    @     0x7f26c1ddfba0 (unknown)
    @     0x7f26c145b5a6 __GI_abort
    @     0x7f26c666c2a4  yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7f26c583cc5c  google::LogMessage::Fail()
    @     0x7f26c583edcc  google::LogMessage::SendToLog()
    @     0x7f26c583c7a9  google::LogMessage::Flush()
    @     0x7f26c583f878  google::LogMessageFatal::~LogMessageFatal()
    @           0x408ddc  yb::master::MasterMain()
    @     0x7f26c1447825 __libc_start_main
    @           0x4082b9 _start
    @                0x0 (unknown)

**Comment by Huqicheng** [comment]
SetCurrentFile has applied rename + fsync to protect CURRENT file.

Suspecting RemoteBootstrapDownloader is related to this issue

**Comment by Huqicheng** [comment]
> The same error
> 
> when i use helm3 install on k8s
> 
> Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6576): Node c30585a740464ce78188a9bbf20ba308 peer not initialized. I0722 09:04:55.189481 33 db_impl.cc:751] T 00000000000000000000000000000000 P c30585a740464ce78188a9bbf20ba308 [R]: Shutdown done E0722 09:04:55.189956 33 master.cc:241] Master@10.244.1.163:7100: Unable to init master catalog manager: IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /mnt/disk0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0 W0722 09:04:55.435078 34 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6576): Node c30585a740464ce78188a9bbf20ba308 peer not initialized. F0722 09:04:55.547295 1 master_main.cc:118] IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /mnt/disk0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0 Fatal failure details written to /mnt/disk0/yb-data/master/logs/yb-master.FATAL.details.2020-07-22T09_04_55.pid1.txt F20200722 09:04:55 ../../src/yb/master/master_main.cc:118] IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /mnt/disk0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0 @ 0x7f26c666de6c yb::LogFatalHandlerSink::send() @ 0x7f26c583f346 google::LogMessage::SendToLog() @ 0x7f26c583c7aa google::LogMessage::Flush() @ 0x7f26c583f879 google::LogMessageFatal::~LogMessageFatal() @ 0x408ddd yb::master::MasterMain() @ 0x7f26c1447825 __libc_start_main @ 0x4082b9 _start @ (nil) (unknown) *** Check failure stack trace: *** W0722 09:04:55.581420 34 scoped_leader_shared_lock.cc:114] Long lock of catalog manager: 0.112s @ 0x7f26d0568490 yb::master::ScopedLeaderSharedLock::Unlock() @ 0x7f26d05a8bd1 yb::master::ScopedLeaderSharedLock::~ScopedLeaderSharedLock() @ 0x7f26d05a59e1 yb::master::MasterServiceImpl::TSHeartbeat() @ 0x7f26c9e74f96 yb::master::MasterServiceIf::Handle() @ 0x7f26c7eafcf9 yb::rpc::ServicePoolImpl::Handle() @ 0x7f26c7e53e04 yb::rpc::InboundCall::InboundCallTask::Run() @ 0x7f26c7ebb948 yb::rpc::(anonymous namespace)::Worker::Execute() @ 0x7f26c66fc7af yb::Thread::SuperviseThread() @ 0x7f26c1dd7694 start_thread @ 0x7f26c150d41d __clone @ (nil) (unknown) @ 0x7f26c666c251 yb::(anonymous namespace)::DumpStackTraceAndExit() @ 0x7f26c583cc5d google::LogMessage::Fail() @ 0x7f26c583edcd google::LogMessage::SendToLog() @ 0x7f26c583c7aa google::LogMessage::Flush() @ 0x7f26c583f879 google::LogMessageFatal::~LogMessageFatal() @ 0x408ddd yb::master::MasterMain() @ 0x7f26c1447825 __libc_start_main @ 0x4082b9 _start @ (nil) (unknown) *** Aborted at 1595408696 (unix time) try "date -d @1595408696" if you are using GNU date *** PC: @ 0x7f26c145b5a6 __GI_abort *** SIGSEGV (@0x0) received by PID 1 (TID 0x7f26d0d8ab40) from PID 0; stack trace: *** @ 0x7f26c1ddfba0 (unknown) @ 0x7f26c145b5a6 __GI_abort @ 0x7f26c666c2a4 yb::(anonymous namespace)::DumpStackTraceAndExit() @ 0x7f26c583cc5c google::LogMessage::Fail() @ 0x7f26c583edcc google::LogMessage::SendToLog() @ 0x7f26c583c7a9 google::LogMessage::Flush() @ 0x7f26c583f878 google::LogMessageFatal::~LogMessageFatal() @ 0x408ddc yb::master::MasterMain() @ 0x7f26c1447825 __libc_start_main @ 0x4082b9 _start @ 0x0 (unknown)



@likenamehaojie Can you still remember the database option? Was disableDataSync set to true?
