### ISSUE TITLE
[DocDB] Count(*) aggregate on a non indexed bigint datatype on a co-located table is 2X of regular YB tables (ScanG9)

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#15882]
Jira Link: [DB-5287](https://yugabyte.atlassian.net/browse/DB-5287)
### Description

Count(*) aggregate on a non indexed bigint datatype on a co-located table is 2X of regular YB tables (ScanG9)

Query | Regular tables | Colocated tables
-- | -- | --
Time to scan a table with 1 million rows | 505 | 1097
Time to scan a table with 5 million rows | 3233 | 6974
Time to scan a table with 10 million rows | 6208 | 14232

YB release: (2.17.1.0-b44)
Cluster details: m6i 2xlarge | packedColumns | tabletSpliting | leader affinity | 1 AZ
Schema details:

- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yugabyte/scanG9_yb_count_nonIndexed_rangescan_fullTableScan_increasingRow.yaml
- https://github.com/yugabyte/benchbase/blob/main/config/yugabyte/scan_workloads/yb_colocated/scanG9_colo_count_nonIndexed_rangescan_fullTableScan_increasingRow.yaml

[DB-5287]: https://yugabyte.atlassian.net/browse/DB-5287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lnguyen-yugabyte** [comment]
Can you confirm that both are created with a single tablet only? By default, hash sharded table might be created with 2 tablets.

**Comment by rthallamko3** [comment]
@shantanugupta-yb , This is by design as the regular tables get higher degree of parallelism compared to colocated tables, leading to lower latencies.


Here are the plans from the [microbenchmark run](http://perf.dev.yugabyte.com/report/view/W3siZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQiIsInRlc3RfaWQiOjE3MjE4MDJ9LHsiZGVzY3JpcHRpb24iOiIiLCJpc0Jhc2VsaW5lIjpmYWxzZSwianNvbiI6IiIsIm5hbWUiOiJZQi1DT0xPIiwidGVzdF9pZCI6MTcyMTQwMn0seyJkZXNjcmlwdGlvbiI6IiIsImlzQmFzZWxpbmUiOnRydWUsImpzb24iOiIiLCJuYW1lIjoiUEciLCJ0ZXN0X2lkIjoxMTc0ODAyfV0=)

Plan for regular tables

```
Finalize Aggregate  (cost=102.50..102.51 rows=1 width=8) (actual time=2883.909..2883.910 rows=1 loops=1)
  Output: count(col_bigint_id_1)
  ->  Seq Scan on public.count_noindex_fulltable_seqscan_10m_rows_1  (cost=0.00..100.00 rows=1000 width=8) (actual time=788.194..2883.881 rows=24 loops=1)
        Output: col_bigint_id_1, col_bigint_1, col_bigint_2, col_bigint_3, col_bigint_4, col_bigint_5, col_float2_1, col_float2_2, col_float5_1, col_float5_2, col_boolean_1, col_varchar10_1, col_varchar100_1, col_varchar100_2, col_varchar500_1
        Partial Aggregate: true
        Storage Table Read Requests: 4
        Storage Table Execution Time: 2883.991 ms
Planning Time: 0.041 ms
Execution Time: 2883.970 ms
Storage Read Requests: 4
Storage Write Requests: 0
Storage Execution Time: 2883.991 ms
```

Plan for colocated 
```

Finalize Aggregate  (cost=102.50..102.51 rows=1 width=8) (actual time=9700.960..9700.960 rows=1 loops=1)
  Output: count(col_bigint_id_1)
  ->  Seq Scan on public.count_noindex_fulltable_seqscan_10m_rows_1  (cost=0.00..100.00 rows=1000 width=8) (actual time=9700.946..9700.949 rows=1 loops=1)
        Output: col_bigint_id_1, col_bigint_1, col_bigint_2, col_bigint_3, col_bigint_4, col_bigint_5, col_float2_1, col_float2_2, col_float5_1, col_float5_2, col_boolean_1, col_varchar10_1, col_varchar100_1, col_varchar100_2, col_varchar500_1
        Partial Aggregate: true
        Storage Table Read Requests: 1
        Storage Table Execution Time: 9701.050 ms
Planning Time: 0.039 ms
Execution Time: 9701.026 ms
Storage Read Requests: 1
Storage Write Requests: 0
Storage Execution Time: 9701.050 ms
```
