### ISSUE TITLE
[Docs] Add documentation for `pg_stat_progress_create_index` view

### ISSUE THREAD

**Issue by fizaaluthra** [yugabyte/yugabyte-db#15902]
### Description

Document the `pg_stat_progress_create_index` view that was added in ced7c32846e4adbe2a93ca20fc64fd648bec8851

**Comment by polarweasel** [comment]
Spec: https://docs.google.com/document/d/1lQeX9naJYpvBRCWMWQR2PWtPt5adMivIU-1UBXKU8Qc/

**Comment by polarweasel** [comment]
Need to link this from the CREATE INDEX docs page (https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_index/), and the doc should be in Explore > Query tuning.
