### ISSUE TITLE
[DocDB] Reword header in operations endpoint 

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15917]
Jira Link: [DB-5331](https://yugabyte.atlassian.net/browse/DB-5331)
### Description

Currently, on the main page of the TS UI, eg: `IP:9000/` there's an `/operations` endpoint, which shows all operations in the server, across tablets. These are single tablet, raft-level operations. However, since this is a relic from Kudu times, they're still named `Transactions`, which is confusing because in YB terminology, Transactions are different (complex, cross tablet work).

We should rename the title and Type header column to Operations / Operation Type respectively.
cc @spolitov 

[DB-5331]: https://yugabyte.atlassian.net/browse/DB-5331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
The first screen shot is the state of the `IP:9000/operations` end point before the fix:

<img width="1617" alt="Screenshot 2023-02-06 at 12 29 09 PM" src="https://user-images.githubusercontent.com/22749018/217081422-491b7af7-baad-4cfa-a9da-b8a10e36538d.png">

The second screenshot is state of the `IP:9000/operations` end point after the fix:
<img width="1609" alt="Screenshot 2023-02-06 at 12 29 36 PM" src="https://user-images.githubusercontent.com/22749018/217081548-58ba2d63-faf0-47a4-8058-fb0eb1e71fd2.png">
