### ISSUE TITLE
[YSQL] Aggregate on varchar column is 16x slower in YB colocated than PG.

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#15914]
Jira Link: [DB-5323](https://yugabyte.atlassian.net/browse/DB-5323)
### Description

Performance of avg on varchar column type is 5x slower in YB regular tables than PG. But yb_colocated it is more than 16x slower. The YB query plan shows that max time is spent in the storage layer.

[DB-5323]: https://yugabyte.atlassian.net/browse/DB-5323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
@sonalsagarwal 

How many tablets did the table  in regular YB table scenario ? 
Likely if the regular YB table has 3 tablets then that would explain the 3X difference in performance .

**Comment by rthallamko3** [comment]
@hbhanawat , @sonalsagarwal , Which microbenchmark captures this? cc @shantanugupta-yb .

**Comment by sonalsagarwal** [comment]
Based on the query plan we have following benchmarks:
