### ISSUE TITLE
[YSQL]  Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequenceVerifyPartialRestore/1 fails with "Don't have value for fixed size column"

### ISSUE THREAD

**Issue by NatashaSerebryanaya** [yugabyte/yugabyte-db#15937]
Jira Link: [DB-5350](https://yugabyte.atlassian.net/browse/DB-5350)
### Description

The fatal
```
[ts-1] F0126 16:19:09.578989 14964 docdb_compaction_context.cc:309] Check failed: column_data.varlen() Don't have value for fixed size column: 12, in , schema_version: 4294967295
[ts-1] Fatal failure details written to ${BUILD_ROOT}/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSequenceVerifyPartialRestore__1.fatal_failure_details.ts-1.2023-01-26T16_19_09.pid13922.txt
[ts-1] F20230126 16:19:09 ../../src/yb/docdb/docdb_compaction_context.cc:309] Check failed: column_data.varlen() Don't have value for fixed size column: 12, in , schema_version: 4294967295
```
Full log can be found [here](https://storage.googleapis.com/test-results.yugabyte.com/jenkins/job/github-yugabyte-db-centos-master-clang15-debug/570/artifact/build/debug-clang15-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSequenceVerifyPartialRestore__1.log?GoogleAccessId=detective-service-acct%40yugabyte.iam.gserviceaccount.com&Expires=1675282245&Signature=kD6vPsXsXo7Y34OJDnY2OO5gV4SOAHk86zamuSPVLuefO8jha0l57R2f2uCM8aYHEf757WfPfDSNK0j%2FV6Wu68LXhhdW8NxUJj01Z7JxkXTapZUYB1OHNv5vkOWmN6w164wVVu9BIaTcI2l752Gp%2BwkNcNuJSlGC0%2BQPcknKWw5Qwsx7PIB9Ra6wSsXCDTujZBzhHNtThKFez82kt%2B0k7DkwDTdP5S%2FWkHBlZFsBGesvsTF44gzQDrSu7Mnret7uyozu%2BVMLC7gvl2G%2FFLSHvPXvp7o9HY7a21Aq7HVyWEG0nq5ozLdyTyTDDv7Rr2ZGCK4PYJWvG3OZma1dUruPrg%3D%3D)

```
ybd --cxx-test tools_yb-admin-snapshot-schedule-test --gtest_filter Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequenceVerifyPartialRestore/1 --clang15
```

Might need to run multiple times to reproduce the error.

The first debug build where it was seen was #548-master-9765a42, but since the test fails not always might be earlier.

[DB-5350]: https://yugabyte.atlassian.net/browse/DB-5350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@lingamsandeep , Do you think this might be addressed by Zach's changes to handling schema changes with Packed and Backup Restore? cc @druzac
