### ISSUE TITLE
[DocDB] Master is displaying incorrect tablet counts after splitting tablets in the master leader UI

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#15935]
Jira Link: [DB-5348](https://yugabyte.atlassian.net/browse/DB-5348)
### Description

Master is displaying incorrect tablet counts after splitting tablets in the master leader UI. We need to check master's table page which lists individual tablets and also the counts in the Tablet Servers page of master leader UI.
Most probably pre-split parent tablets that were deleted were not accounted correctly

[DB-5348]: https://yugabyte.atlassian.net/browse/DB-5348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment]
https://yugabyte.slack.com/archives/C01CB38CZHU/p1675278535115939

**Comment by SrivastavaAnubhav** [comment]
Closing as duplicate of #11307
