### ISSUE TITLE
[DocDB] FATAL log - Failed to load tablet metadata for tablet id 7b771b38883746889757965eb565e7b6: Could not load Raft group metadata

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#15953]
Jira Link: [DB-5364](https://yugabyte.atlassian.net/browse/DB-5364)
### Description

**Version** : 2.17.1.0-b437
**Setup** - TLS and EAR(Encryption at REST) enabled setup

**Steps**:
1. Executed xCluster DR unplanned Failover/Failback flow
2. Kill/Stop one AZ -  New Source(Old Target)(master leader node) and Start again 
Observed FATAL -
`F0202 13:00:44.710155  9469 hybrid_clock.cc:177] Too big clock skew is detected: 0.566s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000F0202 13:00:44.714437  9470 hybrid_clock.cc:177] Too big clock skew is detected: 0.561s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000F0202 13:00:44.719449  9467 hybrid_clock.cc:177] Too big clock skew is detected: 0.565s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000`

After sometimes(10 min) healthcheck looks good.

3. Kill/Stop AZ - New Target(Old Source)(master leader node) and start again
Observed FATAL - 
`F0202 13:32:28.356715  2474 tablet_server_main_impl.cc:223] Invalid argument (yb/encryption/universe_key_manager.cc:75): Could not init Tablet Manager: Failed to open tablet metadata for tablet: 7b771b38883746889757965eb565e7b6: Failed to load tablet metadata for tablet id 7b771b38883746889757965eb565e7b6: Could not load Raft group metadata from /mnt/d0/yb-data/tserver/tablet-meta/7b771b38883746889757965eb565e7b6: Key with version number AQIDAHghroMcj5xS1PqSQkDOc+Xk0rtzHDzSg2bRaL5p1M+cjgEWIeTFrEzsNnEMc5igBp6sAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMMMQsW2dbtkbox7WAgEQgDv9wNULB16IEdaNMdNGSLUNlB4zPau6zDn3tdpaEmU2nN8JJTluMtS0FYiRX5VnBc/tAfmwFt6nhLJ4Zw== does not exist`

After sometimes(10 min) healthcheck looks good.

[DB-5364]: https://yugabyte.atlassian.net/browse/DB-5364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@Arjun-yb This is explicitly with encryption at rest enabled? We should clarify that in the setup, in the summary...

**Comment by akshita-yg** [comment]
we are facing similar issue in this universe which is EAR enabled but not xcluster. 
https://10.9.135.115/universes/a80d7ad1-cd41-4e61-aae8-85b304c9207f/overview
tserver logs- 
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0517 11:23:24.585471  4635 tablet_server_main_impl.cc:224] Invalid argument (yb/encryption/universe_key_manager.cc:75): Could not init Tablet Manager: Failed to open tablet metadata for tablet: 10d12cebf8ef48a69132cb26105820cc: Failed to load tablet metadata for tablet id 10d12cebf8ef48a69132cb26105820cc: Could not load Raft group metadata from /mnt/d0/yb-data/tserver/tablet-meta/10d12cebf8ef48a69132cb26105820cc: Key with version number AQIDAHiqbx9shjV6wcw8auEoMK8rfgx7a8vlrABjeCeRGgjP8QFhjegvpCTYIPpRvrsUhsecAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiHiSqJOhFcqRZvEJAgEQgDszw+mzRsJoProyIY1xbSaX36COgSbeBCx+VyxTd27pYlO4WT+03ShILrP2aEhTLzD/IawLHQ8H7Q7fBw== does not exist
