### ISSUE TITLE
[YSQL] YSQL tests fail on Detective due to process_tree_supervisor.py failing to reclaim all processes

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#15962]
Jira Link: [DB-5371](https://yugabyte.atlassian.net/browse/DB-5371)
### Description

Code in process_tree_supervisor
```
def handle_termination(self):
    def handle_termination(self):
        killed_pids = []
        for pid in self.pid_set:
            if pid != self.ancestor_pid:
                process = get_process_by_pid(pid)
                if process is None:
                    logging.info("Child pid %d seems to have terminated on its own", pid)
                else:
                    self.report_stray_process(process, will_kill=self.args.terminate_subtree)
                    if self.args.terminate_subtree:
                        os.kill(process.pid, signal.SIGKILL)
                        killed_pids.append(process.pid)
```
Process tree supervisor makes a list of stray processes that have not died when the test ended. It then reports these stray processes and tries to kill them. However, sometimes, the os.kill command crashes with exception because the process is no longer found. It can happen that the process can die in the time gap between being detected as a stray process and actually getting killed. 

This issue was seen quite often while running YSQL tests with TSAN. The fix is simple:

```
                    if self.args.terminate_subtree:
                        try:
                            os.kill(process.pid, signal.SIGKILL)
                            killed_pids.append(process.pid)
                        except ProcessLookupError:
                            logging.info("Child pid %d seems to have terminated on its own", pid)
```

[DB-5371]: https://yugabyte.atlassian.net/browse/DB-5371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
See also related issue #14102.
