### ISSUE TITLE
[YSQL] Core dump tserver occurs in long running bank workload

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#15981]
Jira Link: [DB-5389](https://yugabyte.atlassian.net/browse/DB-5389)
### Description

We use improved bank workload with insert, deletes and insert-delete operations in addition to updates.
Currently all variations of this workload are failed because of core dump on tserver side.

Test timeline:
<img width="1542" alt="Screenshot 2023-02-06 at 12 07 52" src="https://user-images.githubusercontent.com/5963536/216917989-b761eb01-b57b-4e2d-9d44-7b44df13af8a.png">

[core_rpc_tp_TabletSe.1303.backtrace.txt](https://github.com/yugabyte/yugabyte-db/files/10660897/core_rpc_tp_TabletSe.1303.backtrace.txt)

[DB-5389]: https://yugabyte.atlassian.net/browse/DB-5389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Based on the core stack, likely traces to 9765a42806c616c975262c9b9b38ba22b0becfa8
