### ISSUE TITLE
Give yugaware ability to assign multiple security groups to new yuga nodes

### ISSUE THREAD

**Issue by rokruzic** [yugabyte/yugabyte-db#1598]
Yugaware has the ability to attach only one security group to new yuga nodes. Where security groups are configured very precisely, it is a necessity to attach several security groups to a yuga node.

Please give yugaware the ability, to accept a list of security groups to attach to new yuga nodes. #

**Comment by rkarthik007** [comment]
Makes sense @rokruzic!

**Comment by rokruzic** [comment]
Was just wondering, is this being considered for inclusion in future releases?

**Comment by bmatican** [comment]
This was addressed by 99daa7447ad39e0b0d7221f8815dca6e85499588
