### ISSUE TITLE
[PITR] x [Materialized Views] x [Tablet Splitting] x [Indexes] x [DDL] 2nd PITR Restore times out 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#16002]
Jira Link: [DB-5411](https://yugabyte.atlassian.net/browse/DB-5411)
### Description

On version **2.17 and 2.16**
 The second PITR restore fails with the below error when used with Materialized Views, Tablet Splitting and Indexes
 
 **ERR=Error running restore_snapshot_schedule: Timed out (yb/rpc/outbound_call.cc:488): Failed to restore snapshot from schedule: 896ddb4a-ff85-4c9b-84a2-4b652dc93602: RestoreSnapshotSchedule RPC (request call id 4) to 10.9.125.132:7100 timed out after 60.000s**
 
 
Steps to repro:
> 1. Create a universe with RPC, Packed row and Tablet splitting enabled
> 2. Create a colocated database, create a table and opt it out of colocation, create secondary index (On column “name”) and create a Materialized View on the table
> 3. Create Snapshot schedule
> 4. Load 1000 rows and note down the time(1)
> 5. Delete some data and note down time(2)
> 6. Update Data
> 7. Note down time(3)
> 8. Drop “name” column using cascade
> 9. Restore to noted time(3)
> 10. Restore to noted time(2) ----> **Fails**

Note: 
**Restore to time(3) then Restore to time(1) ---->Works
           Restore to time(2) then restore to time(1) ---->Works
           Restore to time(3) then restore to time(2) ---->Fails**

Logs 
[logs.zip](https://github.com/yugabyte/yugabyte-db/files/10673155/logs.zip)

[DB-5411]: https://yugabyte.atlassian.net/browse/DB-5411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@kripasreenivasan is this something we have automated? does this still fail, or can we close this?
