### ISSUE TITLE
[PITR] x [Materialized Views] x [Tablet Splitting] x [Indexes] x [DDL] Fatals observed during PITR Restore and PITR restore fails

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#16003]
Jira Link: [DB-5412](https://yugabyte.atlassian.net/browse/DB-5412)
### Description

**Observed only on version **2.14****
 The PITR restore fails with the below error when used with Materialized Views, Tablet Splitting and Indexes, also fatals are observed
 
 **ERR=Error running restore_snapshot_schedule: Timed out (yb/rpc/outbound_call.cc:488): Failed to restore snapshot from schedule: 896ddb4a-ff85-4c9b-84a2-4b652dc93602: RestoreSnapshotSchedule RPC (request call id 4) to 10.9.125.132:7100 timed out after 60.000s**
 
 
Steps to repro:
> 1. Create a universe with RPC and Tablet splitting enabled
> 2. Create a database, create a table and opt it out of colocation and create secondary index (On column “name”), create a Materialized View on the table
> 3. Create Snapshot schedule
> 4. Load 1000 rows and note down the time(1)
> 5. Delete some data and note down time(2)
> 6. Update Data
> 7. Note down time(3)
> 8. Drop “name” column using cascade
> 9. Restore to noted time(3) ----> **Fails**

Logs 
[logs](https://github.com/yugabyte/yugabyte-db/files/10673377/itest-system-developer.3315.-.2.14.7.0-b5.zip)

[DB-5412]: https://yugabyte.atlassian.net/browse/DB-5412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
@kripasreenivasan Can you confirm that this issue is still happening? and if yes can you send me the exact constructions to reproduce it.
I tried to repro using 2.14 and 2.16 by running the following instructions:

```
CREATE DATABASE coldb WITH colocated = true;
\connect coldb
-- create a table optted out of colocation:
CREATE TABLE t3 (k VARCHAR, v TEXT, PRIMARY KEY (k)) WITH (colocated = false);

CREATE INDEX ON t3 (v);

--create schedule
./build/latest/bin/yb-admin -master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 create_snapshot_schedule 3 60 ysql.coldb

--back to ysqlsh
INSERT INTO t3 (k, v)
    SELECT i::text, left(md5(random()::text), 4)
    FROM generate_series(1, 1000) s(i);
select now();
--t1 =    2023-03-06 23:22:31

DELETE FROM t3 WHERE k::Integer>900;
select now();
--t2 =  2023-03-06 23:22:57

UPDATE t3
SET v='aaaa'
where k::INTEGER<100;
select now();
--t3 = 2023-03-06 23:23:19

ALTER TABLE t3 DROP COLUMN v;

--testing the table does not have column v
select * from t3 where v='aaaa';
ERROR:  column "v" does not exist

--restore snapshot
./build/latest/bin/yb-admin -master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 restore_snapshot_schedule 81c3934b-9f85-4f37-a95b-1d13ea2ac633 '2023-03-06 23:23:19'

--back to the shell
select * from t3 where v='aaaa';
The restore worked just fine.
```

**Comment by yamen-haddad** [comment]
@shishir2001-yb It would be great if you can send me the exact set of instruction that I can use to reproduce the issue.
In all cases, I am checking the `itest.log` that you shared. I am wondering why I could not find the log of `Creating a colocated table`. [This](https://bitbucket.org/yugabyte/internal-services/src/9082b047a211abd01092fd9337ebcf0279f2ea13/itest/src/universe_tests/system_tests/pitr/test_pitr_with_tablet_splitting.py#lines-173) is the line of code that should generate the log.
Although I found the log of creating the non-colocated table: `2023-02-06 09:14:35,569 database_operations.py:767 INFO testysqlpitrwithnewnodeautomatictabletsplitting-aws-rf3 Create table query: CREATE TABLE non_colocated_table (id text primary key, uuid_col uuid DEFAULT uuid_generate_v4 (), name text, c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, details e_details, age int, collated_data text collate "POSIX",date DATE,n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], zip postal_code) WITH (colocated = False)`.
Am I missing something here? I am debugging the `TestYSQLPITRWithNewNodeAutomaticTabletSplitting` class found [here](https://bitbucket.org/yugabyte/internal-services/src/9082b047a211abd01092fd9337ebcf0279f2ea13/itest/src/universe_tests/system_tests/pitr/test_pitr_with_tablet_splitting.py#lines-52).
I will keep extracting the sql commands from the logs/code. However, if you can provide me with a direct set of instructions to repro that would be great.
cc @kripasreenivasan @lingamsandeep

**Comment by yamen-haddad** [comment]
@shishir2001-yb So I realized that the test is being modified in the past weeks. This explains the difference between the test [code](https://bitbucket.org/yugabyte/internal-services/src/master/itest/src/universe_tests/system_tests/pitr/test_pitr_with_tablet_splitting.py) and the [logs](https://github.com/yugabyte/yugabyte-db/files/10673377/itest-system-developer.3315.-.2.14.7.0-b5.zip).
So if you can add a fresh logs that would be great.

**Comment by shishir2001-yb** [comment]
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE complex AS (re float8, im float8);
CREATE DOMAIN postal_code AS TEXT CHECK(VALUE ~ '^\\d{5}$'OR VALUE ~ '^\\d{5}-\\d{4}$');
CREATE TYPE e_details AS ENUM ('Email', 'Sms', 'Phone');


CREATE TABLE test1 (id text primary key, uuid_col uuid DEFAULT uuid_generate_v4 (), name text, c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial,i3 bigserial, val smallint, details e_details, age int, collated_data text collate "POSIX",date DATE,n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL ,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], zip postal_code);

CREATE INDEX idx ON test1(name);

CREATE MATERIALIZED VIEW mat_view1 AS SELECT * FROM test1;

-> Create a snapshot schedule with interval=1min and retention=60 min

-> Load 1000 rows and note down time(1)

-> Delete few rows and note down time(2)

-> Update some data

-> Note down time(3)

ALTER TABLE test1 DROP COLUMN name CASCADE         ----->(Note: As we are using CASCADE this will drop Mat view)

-> Restore to time(3) ------> Fails
```

**Comment by yamen-haddad** [comment]
Is the database colocated or not? Is test1 colocated or not?

**Comment by shishir2001-yb** [comment]
I have tried it with both colocated database(with non-colocated tables) and normal database(with normal tables), same error is observed.
We don't usually print insert/delete/update commands because it fills the jenkins console output(~50k commands) and then console output fails to load.Although, for this this test have I started a jenkins job with print all commands [here](https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/4077/console)
