### ISSUE TITLE
[YSQL] [Read committed] [Pessimistic Locking] : Waiting behaviour is observed for transactions with read committed isolation level even when wait queues is disabled

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#16001]
Jira Link: [DB-5410](https://yugabyte.atlassian.net/browse/DB-5410)
### Description

Steps to reproduce:

1. Create universe with `yb_enable_read_committed_isolation=true`
2. Create table
```
test=# create table tb(k int primary key, v int);
CREATE TABLE
test=# insert into tb values(1,1),(2,2),(3,3);
INSERT 0 3
```
3. T1:
```
test=# begin transaction isolation level read committed;
BEGIN
test=# select;
--
(1 row)

test=# select * from tb where k=1 for update;
 k | v 
---+---
 1 | 1
(1 row)
```
4. T2: 
```
begin transaction isolation level read committed;
BEGIN
test=# select;
--
(1 row)

test=# select * from tb where k=1 for share;
```
Notice that T2 waits for T1 even when wait queues is not enabled. Version: 2.17.2.0-b109

[DB-5410]: https://yugabyte.atlassian.net/browse/DB-5410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Karvy-yb** [comment]
My understanding is that this is the read committed isolation level behaviour and might be expected, if that is the case then please close the issue. But I would like to understand the difference between behaviour of read committed with wait queues enabled  & read committed with wait queues disabled.

**Comment by pkj415** [comment]
You are right @Karvy-yb! Read committed provides Wait-on-Conflict concurrency control semantics even without wait queues. I have recently added a new docs section to detail the reasoning for this here - https://docs.yugabyte.com/preview/architecture/transactions/read-committed/#interaction-with-concurrency-control
