### ISSUE TITLE
[YSQL] creation of a FUNCTION is not transactional

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#1601]
In case function creation ends with error it is still exists. There is a record in `pg_proc` table and it is not possible to recreate function with same name. Explicit call of `DROP FUNCTION` is required

Steps to reproduce:
```
postgres=# CREATE FUNCTION new_function_name()
  RETURNS trigger AS
$BODY$
BEGIN
   RETURN NEW;
END;
$BODY$ language sql;
ERROR:  SQL functions cannot return type trigger
postgres=# SELECT COUNT(*) FROM pg_proc WHERE proname = 'new_function_name';
 count 
-------
     1
(1 row)
```

Probably issue relates not only to functions creation but all modifications of system catalog

**Comment by ndeodhar** [comment]
Related issue: https://github.com/YugaByte/yugabyte-db/issues/1383
Fixing #1383 will likely take care of this too.

**Comment by m-iancu** [comment]
Should have been fixed by https://github.com/yugabyte/yugabyte-db/issues/3108. #1383 referenced above is already closed.
