### ISSUE TITLE
[YSQL] Colocation GA: The parent table created upon creation of the first colocated table needs to be renamed from catalog to something more appropriate

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#16029]
Jira Link: [DB-5431](https://yugabyte.atlassian.net/browse/DB-5431)
### Description

- Create a colocated database in the new implementation by turning the flag ysql_legacy_colocated_database_creation=false
- Create a colocated table under this colocated db
- There is a parent table created on creation of the first colocated table.
**Issue:** This parent table is incorrectly named as "catalog"
```
[yugabyte@ip-172-151-37-247 master]$ bin/yb-admin --master_addresses 172.151.28.87,172.151.37.247,172.151.51.156 -certs_dir_name /home/yugabyte/yugabyte-tls-config/ list_tables include_db_type include_table_id include_table_type | grep "colocation.parent.tablename"
ysql.cl_new_implementation.0000435900003000800000000000437b.colocation.parent.tablename 0000435900003000800000000000437b.colocation.parent.uuid catalog
ysql.cl_old_implementation.0000435a0000300080000000000043a3.colocation.parent.tablename 0000435a0000300080000000000043a3.colocation.parent.uuid catalog
```

[DB-5431]: https://yugabyte.atlassian.net/browse/DB-5431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Improvement is added by commit 0bfe8c4
