### ISSUE TITLE
[YSQL] [Unit Test] testPgRegressExtension is failing on multiple builds

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#16033]
Jira Link: [DB-5435](https://yugabyte.atlassian.net/browse/DB-5435)
### Description

Test case org.yb.pgsql.TestPgRegressExtension.testPgRegressExtension is failing on atleast 3 builds with error:

`java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb_pgaudit]`

It seems yb_pgaudit is failing.

Stability: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.pgsql.TestPgRegressExtension&name=testPgRegressExtension

It started failing with yb_pgaudit with commit: [6abc1af5af26b3236c751c9eed153cfd9c0d5de8](https://github.com/yugabyte/yugabyte-db/commits/6abc1af5af26b3236c751c9eed153cfd9c0d5de8)

[DB-5435]: https://yugabyte.atlassian.net/browse/DB-5435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by NatashaSerebryanaya** [comment]
org.yb.pgsql.TestPgRegressTable.testPgRegressTable too:
https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.pgsql.TestPgRegressTable&name=testPgRegressTable

**Comment by bmatican** [comment]
Fixed by eca5c13e26a30735741df1f8fe97d821f72f9307
