### ISSUE TITLE
[Docs] Read replicas

### ISSUE THREAD

**Issue by msyed30** [yugabyte/yugabyte-db#16036]
### Description

[Docs Changes](https://docs.yugabyte.com/preview/yugabyte-cloud/cloud-clusters/managed-read-replica/#limitations)

Please add this under the Limitations for the read-replicas

you can have either a geo-partitioned cluster or a synchronously replicated cluster (single or multi-region) with read replicas.

**Comment by msyed30** [comment]
Geo-partitioned clusters do not support read replicas

**Comment by polarweasel** [comment]
Thanks @msyed30! I've added this to Jira as DOC-10.
