### ISSUE TITLE
[YSQL] Test org.yb.pgsql.TestPgExplainAnalyze.testNoTiming fails in 7 builds

### ISSUE THREAD

**Issue by NatashaSerebryanaya** [yugabyte/yugabyte-db#16050]
Jira Link: [DB-5447](https://yugabyte.atlassian.net/browse/DB-5447)
### Description

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.pgsql.TestPgExplainAnalyze&name=testNoTiming
starting the commit https://github.com/yugabyte/yugabyte-db/commits/c3aa5d4ba618e0a849b3d796434466fc7d892832

https://detective.dev.yugabyte.com/?commits=7afad15ef2b6348dfecac903939e5077090cd8a4

The error:
```
java.lang.AssertionError: 
Json conflicts:
"Storage Write Requests": '1' is not == '206'
```

[DB-5447]: https://yugabyte.atlassian.net/browse/DB-5447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by NatashaSerebryanaya** [comment]
Also
org.yb.pgsql.TestPgExplainAnalyze.testUpdateReturning
org.yb.pgsql.TestPgExplainAnalyze.testUpdateUsingIndex

**Comment by andrei-mart** [comment]
Broken by #15881
