### ISSUE TITLE
[YSQL] TRUNCATE does not reset pg_class.reltuples counts

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#16052]
Jira Link: [DB-5448](https://yugabyte.atlassian.net/browse/DB-5448)
### Description

TRUNCATE does not reset pg_class.reltuples back to 0. Vanilla PG behaves correctly.

Repro:
```
create table t as select generate_series(1,10000);
analyze t;
select count(*) from t; -- returns 1000 as expected
select reltuples from pg_class where relname = 't'; -- returns 1000 as expected

truncate t;

select count(*) from t; -- returns 0 as expected
select reltuples from pg_class where relname = 't'; -- return 1000, not expected
```

[DB-5448]: https://yugabyte.atlassian.net/browse/DB-5448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by karthik-ramanathan-3006** [comment]
Root cause: As part of truncate, Postgres updates the storage container (RelFileNode). This update also triggers a pg_class and Catalog Tuple Update. Truncation of Yugabyte managed relations bypasses the above flow.
Fix: Replicating the necessary book-keeping for the Yugabyte TRUNCATE flow.
