### ISSUE TITLE
[CQL] Endless node restarts after intensive CQL batch inserts load with more then 1k connections

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#16054]
Jira Link: [DB-5449](https://yugabyte.atlassian.net/browse/DB-5449)
### Description

env: RF=3, 3 nodes, c5.2xlarge, aws provider

steps:
- Run cluster with default gflags
- Run workload:
```
java  -jar yb-sample-apps-1.9.3-cpr-4.jar \
    --workload CassandraDataLoad  \
    --num_writes -1 \
    --num_reads -1 \
    --num_threads_write 100 \
    --concurrent_clients 1500 \
    --num_threads_read 1 \
    --num_unique_keys 999000000000 \
    --num_value_columns 30 \
    --large_value_multiplier 10 \
    --large_key_multiplier 10 \
    --batch_size 1000 \
    --create_table_name test_backup_5eaed5 \
    --uuid 46a6b0fb-8a11-44c1-a923-d713e7135625 \
    --nodes [nodes ips]
```
sample-apps you can take from https://github.com/yugabyte/yb-stress-test/releases/tag/sa_1.9.3-cpr-4
- watch how nodes starts restarting constantly
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/30021057/217927016-4a2c7f35-b324-4af8-b469-de5e335f4b8d.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30021057/217927051-e05b857a-b7b5-4721-a683-efcdd65dc8d5.png">
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/30021057/217927114-d7fc8c69-7eff-4139-9bdb-20f728518244.png">
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/30021057/217927155-71a55bbd-7242-4409-987f-ba76eb8a0555.png">
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/30021057/217927235-cea3c740-ef12-4c73-8f0b-04e7e1938c99.png">
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/30021057/217927276-2e6ae05f-de07-4ef9-808e-064bd44daf30.png">
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/30021057/217927307-d227141e-4930-4730-86df-34bca6d50696.png">
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/30021057/217927400-5c52417f-171a-45f5-baf5-ddfb8e745efb.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/30021057/217927437-ab665634-a031-44c5-b840-2950e1bc5477.png">
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/30021057/217927490-f5dfbe56-8d4d-46f2-acf4-06b134349e27.png">
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/30021057/217927529-e5e86c79-e044-4b34-921e-677bce095c00.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/30021057/217927582-980276b1-6759-4853-bfc7-aeb058fbd18f.png">
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/30021057/217927615-c5025253-1677-44d3-8099-99a49a534163.png">

[DB-5449]: https://yugabyte.atlassian.net/browse/DB-5449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@pilshchikov , Can you share the logs for the above issue? What made you realize that the nodes are restarting?

**Comment by pilshchikov** [comment]
@rthallamko3 
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/30021057/221666797-1389345c-76c2-43cb-8749-b7b7d18f21bd.png">
This

**Comment by pilshchikov** [comment]
@rthallamko3 i have 1GB of logs, just ping me if you need them

**Comment by bmatican** [comment]
Closing this, as it was likely related to the memory bloat issues we've seen with sample apps and fixed recently.
@pilshchikov feel free to open again, if you are still able to repro in master.
