### ISSUE TITLE
checkpoints dir not cleaned up after drop table

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1605]
[yugabyte@ip-172-151-29-141 logs]$ ls -la  /mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/*
/mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/2738932_797078.991s:
total 8872848
drwxr-xr-x. 2 yugabyte yugabyte       4096 Jun 11 04:42 .
drwxr-xr-x. 5 yugabyte yugabyte         87 Jun 11 19:35 ..
-rw-r--r--. 3 yugabyte yugabyte   12485648 Jun 11 02:03 004439.sst
-rw-r--r--. 3 yugabyte yugabyte 8097371489 Jun 11 02:03 004439.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     953851 Jun 11 03:34 004499.sst
-rw-r--r--. 1 yugabyte yugabyte  705538455 Jun 11 03:34 004499.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     223189 Jun 11 04:06 004523.sst
-rw-r--r--. 1 yugabyte yugabyte  118880976 Jun 11 04:06 004523.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     160167 Jun 11 04:32 004540.sst
-rw-r--r--. 1 yugabyte yugabyte   68407811 Jun 11 04:32 004540.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      87159 Jun 11 04:40 004545.sst
-rw-r--r--. 1 yugabyte yugabyte   13157949 Jun 11 04:40 004545.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      83850 Jun 11 04:42 004546.sst
-rw-r--r--. 1 yugabyte yugabyte   10884099 Jun 11 04:42 004546.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     140893 Jun 11 04:42 004547.sst
-rw-r--r--. 1 yugabyte yugabyte   53386475 Jun 11 04:42 004547.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      72878 Jun 11 04:42 004548.sst
-rw-r--r--. 1 yugabyte yugabyte    3907377 Jun 11 04:42 004548.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte         16 Jun 11 04:42 CURRENT
-rw-r--r--. 1 yugabyte yugabyte       9439 Jun 11 04:42 MANIFEST-004525

/mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/2782721_803500.087s:
total 9646704
drwxr-xr-x. 2 yugabyte yugabyte       4096 Jun 11 06:29 .
drwxr-xr-x. 5 yugabyte yugabyte         87 Jun 11 19:35 ..
-rw-r--r--. 3 yugabyte yugabyte   12485648 Jun 11 02:03 004439.sst
-rw-r--r--. 3 yugabyte yugabyte 8097371489 Jun 11 02:03 004439.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte    1886775 Jun 11 05:56 004609.sst
-rw-r--r--. 1 yugabyte yugabyte 1463089226 Jun 11 05:56 004609.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     390857 Jun 11 06:22 004632.sst
-rw-r--r--. 1 yugabyte yugabyte  255382764 Jun 11 06:22 004632.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      90262 Jun 11 06:25 004633.sst
-rw-r--r--. 1 yugabyte yugabyte   15412573 Jun 11 06:25 004633.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      86292 Jun 11 06:27 004634.sst
-rw-r--r--. 1 yugabyte yugabyte   12652915 Jun 11 06:27 004634.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      87702 Jun 11 06:29 004635.sst
-rw-r--r--. 1 yugabyte yugabyte   13606385 Jun 11 06:29 004635.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      75264 Jun 11 06:29 004636.sst
-rw-r--r--. 1 yugabyte yugabyte    5528821 Jun 11 06:29 004636.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte         16 Jun 11 06:29 CURRENT
-rw-r--r--. 1 yugabyte yugabyte      34647 Jun 11 06:29 MANIFEST-004561

/mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/2927228_850650.431s:
total 12200928
drwxr-xr-x. 2 yugabyte yugabyte       4096 Jun 11 19:35 .
drwxr-xr-x. 5 yugabyte yugabyte         87 Jun 11 19:35 ..
-rw-r--r--. 3 yugabyte yugabyte   12485648 Jun 11 02:03 004439.sst
-rw-r--r--. 3 yugabyte yugabyte 8097371489 Jun 11 02:03 004439.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte    3506889 Jun 11 09:03 004742.sst
-rw-r--r--. 1 yugabyte yugabyte 2800453237 Jun 11 09:03 004742.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte    1105920 Jun 11 11:36 004831.sst
-rw-r--r--. 1 yugabyte yugabyte  826855669 Jun 11 11:36 004831.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     624314 Jun 11 15:30 004872.sst
-rw-r--r--. 1 yugabyte yugabyte  441469861 Jun 11 15:30 004872.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     340951 Jun 11 19:11 004892.sst
-rw-r--r--. 1 yugabyte yugabyte  214884910 Jun 11 19:11 004892.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     144064 Jun 11 19:24 004897.sst
-rw-r--r--. 1 yugabyte yugabyte   55874388 Jun 11 19:24 004897.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      88109 Jun 11 19:28 004898.sst
-rw-r--r--. 1 yugabyte yugabyte   13893317 Jun 11 19:28 004898.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      88239 Jun 11 19:32 004899.sst
-rw-r--r--. 1 yugabyte yugabyte   13914504 Jun 11 19:32 004899.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      83129 Jun 11 19:35 004900.sst
-rw-r--r--. 1 yugabyte yugabyte   10470559 Jun 11 19:35 004900.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte         16 Jun 11 19:35 CURRENT
-rw-r--r--. 1 yugabyte yugabyte      38195 Jun 11 19:35 MANIFEST-004820
[yugabyte@ip-172-151-29-141 logs]$ ls -la  /mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/
total 4
drwxr-xr-x.  3 yugabyte yugabyte   25 Jun 21 22:36 .
drwxr-xr-x. 26 yugabyte yugabyte 4096 Jun 21 22:36 ..
drwxr-xr-x.  5 yugabyte yugabyte   87 Jun 11 19:35 checkpoints
[yugabyte@ip-172-151-29-141 logs]$  ls -la  /mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/*
/mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/2738932_797078.991s:
total 8872848
drwxr-xr-x. 2 yugabyte yugabyte       4096 Jun 11 04:42 .
drwxr-xr-x. 5 yugabyte yugabyte         87 Jun 11 19:35 ..
-rw-r--r--. 3 yugabyte yugabyte   12485648 Jun 11 02:03 004439.sst
-rw-r--r--. 3 yugabyte yugabyte 8097371489 Jun 11 02:03 004439.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     953851 Jun 11 03:34 004499.sst
-rw-r--r--. 1 yugabyte yugabyte  705538455 Jun 11 03:34 004499.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     223189 Jun 11 04:06 004523.sst
-rw-r--r--. 1 yugabyte yugabyte  118880976 Jun 11 04:06 004523.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     160167 Jun 11 04:32 004540.sst
-rw-r--r--. 1 yugabyte yugabyte   68407811 Jun 11 04:32 004540.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      87159 Jun 11 04:40 004545.sst
-rw-r--r--. 1 yugabyte yugabyte   13157949 Jun 11 04:40 004545.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      83850 Jun 11 04:42 004546.sst
-rw-r--r--. 1 yugabyte yugabyte   10884099 Jun 11 04:42 004546.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     140893 Jun 11 04:42 004547.sst
-rw-r--r--. 1 yugabyte yugabyte   53386475 Jun 11 04:42 004547.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      72878 Jun 11 04:42 004548.sst
-rw-r--r--. 1 yugabyte yugabyte    3907377 Jun 11 04:42 004548.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte         16 Jun 11 04:42 CURRENT
-rw-r--r--. 1 yugabyte yugabyte       9439 Jun 11 04:42 MANIFEST-004525

/mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/2782721_803500.087s:
total 9646704
drwxr-xr-x. 2 yugabyte yugabyte       4096 Jun 11 06:29 .
drwxr-xr-x. 5 yugabyte yugabyte         87 Jun 11 19:35 ..
-rw-r--r--. 3 yugabyte yugabyte   12485648 Jun 11 02:03 004439.sst
-rw-r--r--. 3 yugabyte yugabyte 8097371489 Jun 11 02:03 004439.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte    1886775 Jun 11 05:56 004609.sst
-rw-r--r--. 1 yugabyte yugabyte 1463089226 Jun 11 05:56 004609.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     390857 Jun 11 06:22 004632.sst
-rw-r--r--. 1 yugabyte yugabyte  255382764 Jun 11 06:22 004632.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      90262 Jun 11 06:25 004633.sst
-rw-r--r--. 1 yugabyte yugabyte   15412573 Jun 11 06:25 004633.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      86292 Jun 11 06:27 004634.sst
-rw-r--r--. 1 yugabyte yugabyte   12652915 Jun 11 06:27 004634.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      87702 Jun 11 06:29 004635.sst
-rw-r--r--. 1 yugabyte yugabyte   13606385 Jun 11 06:29 004635.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      75264 Jun 11 06:29 004636.sst
-rw-r--r--. 1 yugabyte yugabyte    5528821 Jun 11 06:29 004636.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte         16 Jun 11 06:29 CURRENT
-rw-r--r--. 1 yugabyte yugabyte      34647 Jun 11 06:29 MANIFEST-004561

/mnt/d1/yb-data/tserver/data/rocksdb/table-6a68beffef2c40afb3bd8a5134e10e38/tablet-fc1cbf98ef4e48af80f4035e76fdc22a/checkpoints/2927228_850650.431s:
total 12200928
drwxr-xr-x. 2 yugabyte yugabyte       4096 Jun 11 19:35 .
drwxr-xr-x. 5 yugabyte yugabyte         87 Jun 11 19:35 ..
-rw-r--r--. 3 yugabyte yugabyte   12485648 Jun 11 02:03 004439.sst
-rw-r--r--. 3 yugabyte yugabyte 8097371489 Jun 11 02:03 004439.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte    3506889 Jun 11 09:03 004742.sst
-rw-r--r--. 1 yugabyte yugabyte 2800453237 Jun 11 09:03 004742.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte    1105920 Jun 11 11:36 004831.sst
-rw-r--r--. 1 yugabyte yugabyte  826855669 Jun 11 11:36 004831.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     624314 Jun 11 15:30 004872.sst
-rw-r--r--. 1 yugabyte yugabyte  441469861 Jun 11 15:30 004872.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     340951 Jun 11 19:11 004892.sst
-rw-r--r--. 1 yugabyte yugabyte  214884910 Jun 11 19:11 004892.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte     144064 Jun 11 19:24 004897.sst
-rw-r--r--. 1 yugabyte yugabyte   55874388 Jun 11 19:24 004897.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      88109 Jun 11 19:28 004898.sst
-rw-r--r--. 1 yugabyte yugabyte   13893317 Jun 11 19:28 004898.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      88239 Jun 11 19:32 004899.sst
-rw-r--r--. 1 yugabyte yugabyte   13914504 Jun 11 19:32 004899.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte      83129 Jun 11 19:35 004900.sst
-rw-r--r--. 1 yugabyte yugabyte   10470559 Jun 11 19:35 004900.sst.sblock.0
-rw-r--r--. 1 yugabyte yugabyte         16 Jun 11 19:35 CURRENT
-rw-r--r--. 1 yugabyte yugabyte      38195 Jun 11 19:35 MANIFEST-004820

**Comment by bmatican** [comment]
Duplicate of #498 and fixed recently.
