### ISSUE TITLE
[YSQL][Unit Test] Very Flaky test XClusterYSqlTestConsistentTransactionsTest.RestartServer

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#16084]
Jira Link: [DB-5472](https://yugabyte.atlassian.net/browse/DB-5472)
### Description

Following test case TwoDCYSqlTestConsistentTransactionsTest.RestartServer has been very flaky across builds. It has been failing with error:

```
../../ent/src/yb/integration-tests/twodc_ysql-test.cc:771
Failed
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:342): Fetch 'select count(*) from test_table_0' failed: 7, message: ERROR:  GetTransactionStatus: tablet_id: "6e53215f4e3d490281dee302291df5c8" transaction_id: ")\216h\212\020\333DY\225\273\t\222\2031\\\355" propagated_hybrid_time: 6865258475355488256, retrier: { task_id: -1 state: kRunning deadline: 10703.214s } passed its deadline 10703.214s (passed: 5.079s): Network error (yb/util/net/socket.cc:540): recvmsg error: Connection refused (system error 111) (pgsql error XX000) (aux msg ERROR:  GetTransactionStatus: tablet_id: "6e53215f4e3d490281dee302291df5c8" transaction_id: ")\216h\212\020\333DY\225\273\t\222\2031\\\355" propagated_hybrid_time: 6865258475355488256, retrier: { task_id: -1 state: kRunning deadline: 10703.214s } passed its deadline 10703.214s (passed: 5.079s): Network error (yb/util/net/socket.cc:540): recvmsg error: Connection refused (system error 111))
```

Stability trend:https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=TwoDCYSqlTestConsistentTransactionsTest&name=RestartServer

Complete logs: https://gist.github.com/rjalan-yb/fb418a825281e42c94aaf0bbaeedc016

[DB-5472]: https://yugabyte.atlassian.net/browse/DB-5472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=XClusterYSqlTestConsistentTransactionsTest&name=RestartServer

**Comment by bmatican** [comment]
Closing for now, as it's far less flaky, so presumably was fixed as part of other test stability work.
