### ISSUE TITLE
Encryption Key support for Fortanix HSM / Equinix SmartKey

### ISSUE THREAD

**Issue by mrpanda** [yugabyte/yugabyte-db#1609]
Hi,
I saw on the Slack channel to open issues for seeking compatible encryption key HSMs. We are exploring the possibility of using Equinix's SmartKey service.

More info here
https://www.equinix.com/resources/data-sheets/smartkey-data-sheet/ 

Regards,
Stephen.

**Comment by rkarthik007** [comment]
Thanks for posting details @mrpanda, will start looking at this.
