### ISSUE TITLE
[DocDB] Splitting huge tablet in YCQL workload leads to 95% performance drop

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#16091]
Jira Link: [DB-5485](https://yugabyte.atlassian.net/browse/DB-5485)
### Description

Original performance was about 300k Tops and after enabling splitting it's dropped to 15k Tops.

`java -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.9.5.jar --workload CassandraBatchTimeseries --num_writes -1 --num_threads_write 400 --num_threads_read 1 --num_reads -1 --num_unique_keys 300000000000000 --table_ttl_seconds -1 --create_table_name table_0 --uuid_marker a7f933bb-4c55-49df-808d-d0f6ca8142ae --nodes ...`

Workload history for a testing day, table had 2+TB size, tablet splitting is enabled around 2pm (note UTC+4 timezone).
<img width="1234" alt="Screenshot 2023-02-14 at 16 39 02" src="https://user-images.githubusercontent.com/5963536/218741021-dc28eeae-0790-4f85-8720-5529157b26d5.png">

YCQL performance metrics:
<img width="578" alt="Screenshot 2023-02-13 at 20 12 59" src="https://user-images.githubusercontent.com/5963536/218552139-69bb8ce4-3f87-46aa-be7f-a748b2d024dc.png">

Original gflags:
```
instance_type="c5.4xlarge",
master_gflags={
    "enable_automatic_tablet_splitting": "false",
    "ysql_num_shards_per_tserver": "1",
    "yb_num_shards_per_tserver": "1",
    "ycql_num_tablets": "1",
},
tserver_gflags={
    "enable_automatic_tablet_splitting": "false",
    "ysql_num_shards_per_tserver": "1",
    "yb_num_shards_per_tserver": "1",
    "ycql_num_tablets": "1",
}
```

Upgraded to:
```
master_gflags={
    "enable_automatic_tablet_splitting": "true"
},
tserver_gflags={
    "enable_automatic_tablet_splitting": "true"
}
```

[DB-5485]: https://yugabyte.atlassian.net/browse/DB-5485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@arybochkin made some very good breakthrough in his investigations. Here are some observations:

For large tablets, that undergo compaction for the first time, the compaction can take a very long time. For example, in the above case, post split compaction took 12+ hours. In the meantime, the workload continued to write to the tablet. The presence of post split compaction (major compaction), blocked regular compactions from getting scheduled on that tablet. However, the workload continued to generate data in that 12 hour duration, which ended up creating new SST files. As a result, the system tips over - SST files reaches the limit of 50 files and writes are rejected after that.

This can be handled by an adaptive throttling scheme - Do not throttle writes on a tablet if the tablet is already being compacted or a compaction is scheduled and is not active yet.  cc @arybochkin , @bmatican

**Comment by arybochkin** [comment]
Added `tablet_exclusive_post_split_compaction` with `false` as default, unit test and additional investigations are tracked by #16772. Backported to 2.14 and 2.16.
