### ISSUE TITLE
support C++ and C# clients

### ISSUE THREAD

**Issue by justinsanciangco** [YugaByte/yugabyte-db#161]
Currently yugabyte does not offer any driver support for C++ and C# applications

**Comment by kmuthukk** [comment]
YugaByte supports drivers in variety of languages including C++, C#. See docs here:

https://docs.yugabyte.com/latest/develop/client-drivers/

Some driver extensions for YCQL JSON type support & partition aware load balancing have already been implemented for the Java drivers, and are planned for C++  & C# drivers also.  See tracking issues for the same:
 
https://github.com/YugaByte/yugabyte-db/issues/512
https://github.com/YugaByte/yugabyte-db/issues/513
https://github.com/YugaByte/yugabyte-db/issues/514
https://github.com/YugaByte/yugabyte-db/issues/515
