### ISSUE TITLE
[YSQL] flaky test: PgLibPqTest.TablegroupCreationFailureWithRestart

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16101]
Jira Link: [DB-5506](https://yugabyte.atlassian.net/browse/DB-5506)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgLibPqTest&fail_tag=all&name=TablegroupCreationFailureWithRestart&platform=linux

seems to have broken since https://github.com/yugabyte/yugabyte-db/commit/47d4d9797918bcf354d19da179ff7b3ec0ca7463

[DB-5506]: https://yugabyte.atlassian.net/browse/DB-5506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
When restarting a cluster, the selected master leader fails to get transaction status hence failed CREATE TABELGROUP DDL doesn't get cleaned up.

**Comment by yifanguan** [comment]
@bmatican This is not a tablegroup specific issue but does look like an actual product issue which can happen if we restart a node. I started one slack thread for this issue: https://yugabyte.slack.com/archives/C03ULJYE0KG/p1677192114545119.

**Comment by bmatican** [comment]
Putting it back in your queue Sandeep, as it seems after last back and forth, now it's down to some master level failures.

**Comment by yifanguan** [comment]
This flaky test issue should be fixed by commit 3986b9e
