### ISSUE TITLE
[DocDB] flaky test: PgIndexBackfillTest.MasterLeaderStepdown and PgIndexBackfillTest.DropAfterFail

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16102]
Jira Link: [DB-5507](https://yugabyte.atlassian.net/browse/DB-5507)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgIndexBackfillTest&fail_tag=all&name=MasterLeaderStepdown&platform=linux

Seems to have regressed in ASAN after c05ae4d985f297c4ff080b2818a7dce5097f937a

[DB-5507]: https://yugabyte.atlassian.net/browse/DB-5507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Seems to also apply to this test: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgIndexBackfillTest&fail_tag=all&name=DropAfterFail&platform=linux

**Comment by hari90** [comment]
The tasks_tracker_ is leaked:

> 
> [m-1] Indirect leak of 72 byte(s) in 1 object(s) allocated from:
> [m-1] #0 0x55dc751eaead in operator new(unsigned long) /opt/yb-build/llvm/yb-llvm-v15.0.3-yb-1-1667030060-0b8d1183-almalinux8-x86_64-build/src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/1 0x7f3d62dacb35 in yb::master::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:895:22
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/2 0x7f3d63138a68 in yb::master::enterprise::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../ent/src/yb/master/catalog_manager.h:34:9
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/3 0x7f3d6312a126 in yb::master::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../src/yb/master/master.cc:155:28
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/4 0x7f3d634d8eed in yb::master::enterprise::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../ent/src/yb/master/master_ent.cc:39:45
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/5 0x55dc751ee341 in yb::master::MasterMain(int, char**) ${BUILD_ROOT}/../../src/yb/master/master_main.cc:133:22
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/6 0x55dc751ee341 in main ${BUILD_ROOT}/../../src/yb/master/master_main.cc:191:12
> [m-1] https://github.com/yugabyte/yugabyte-db/issues/7 0x7f3d501e3d84 in __libc_start_main (/lib64/libc.so.6+0x3ad84) (BuildId: d18afae5244bc9c85026bd7d64b276d51b452d93)

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-asan/457/artifact/build/asan-clang15-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_index_backfill-test/PgIndexBackfillTest_MasterLeaderStepdown.log

**Comment by hari90** [comment]
related to #16064
