### ISSUE TITLE
[DocDB] Transaction not found when local transaction requires promotion on first operation

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#16108]
Jira Link: [DB-5512](https://yugabyte.atlassian.net/browse/DB-5512)
### Description

When a local transaction requires promotion on the first batch of operations, and the first batch is received before the transaction is ready (CREATED heartbeat sent to local transaction tablet), we send an UpdateTransactionStatusLocation RPC to the tablets to be written to by that first batch after promotion. Since we have yet to do the actual write, these participant tablets return `Update transaction status location for unknown transaction` which causes the transaction to abort.

[DB-5512]: https://yugabyte.atlassian.net/browse/DB-5512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
Fixed with 571d485.

**Comment by rthallamko3** [comment]
Reactivating till the 2.16 backport is done.
