### ISSUE TITLE
[DocDB] Expose aborted transactions counter to prometheus

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16126]
Jira Link: [DB-5564](https://yugabyte.atlassian.net/browse/DB-5564)
### Description

Expose aborted transactions counter to prometheus. It is useful to look at the metric when the system runs into issues like lot of intents left behind not being reclaimed/ lots of unnecessary memory usage by aborted transactions. Each aborted transaction can consume at least 700 bytes. When the system accumulates millions of them, the memory footprint adds up to , to cause writes to be rejected in the system.

[DB-5564]: https://yugabyte.atlassian.net/browse/DB-5564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Will consider backport if needed.

**Comment by yusong-yan** [comment]
The test is flaky, and it is tracked in https://github.com/yugabyte/yugabyte-db/issues/17394
