### ISSUE TITLE
[DocDB] PITR doesn't clear sequence cache on connections.

### ISSUE THREAD

**Issue by mislam-yb** [yugabyte/yugabyte-db#16137]
Jira Link: [DB-5576](https://yugabyte.atlassian.net/browse/DB-5576)
### Description

If a set of values from a sequence is cached on a connection, and then a PITR is performed that changes the current value of the sequence, the connection's cache is not cleared. This leads to duplicate values.

Below is a minimal reproduction. Use 2 shells, one for yb-admin and one for ysqlsh:

```
$ ./bin/yb-ctl start --tserver_flags="ysql_sequence_cache_minval=2"
```

```
$ ./bin/ysqlsh
ysqlsh# CREATE DATABASE test;
ysqlsh# exit
$ ./bin/ysqlsh -d test
test# CREATE SEQUENCE s;
test# SELECT nextval('s');
nextval 
---------
       1
(1 row)
```

```
$ ./bin/yb-admin -master_addresses 127.0.0.1:7100 create_snapshot_schedule 2 10 ysql.test
# keep track of the schedule id returned
```

```
test# SELECT nextval('s');
nextval 
---------
       2
(1 row)

test# SELECT nextval('s');
nextval 
---------
       3
(1 row)
```

```
# wait 1 minute to pass from the time you created the schedule
./bin/yb-admin -master_addresses 127.0.0.1:7100 restore_snapshot_schedule [schedule id from above] minus 1m
```

```
test# SELECT nextval('s');
nextval 
---------
       4
(1 row)

test# SELECT nextval('s');
nextval 
---------
       3
(1 row)
```

Notice the duplicate value; we've already retrieved 3.

[DB-5576]: https://yugabyte.atlassian.net/browse/DB-5576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sanketkedia** [comment]
2.14 backport is more complicated and needs some infrastructure introduced by packed rows, so we decided that we won't backport to 2.14 for now and will keep the option open if needed in future.
