### ISSUE TITLE
[YSQL][PITR][Tablegroups]: Invalid value of enum SysSnapshotEntryPB::State

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#16131]
Jira Link: [DB-5569](https://yugabyte.atlassian.net/browse/DB-5569)
### Description

PITR of table creation (~100 tables) in tablegroup is failing with following error:
`ERR=Error running restore_snapshot_schedule: Timed out (yb/rpc/outbound_call.cc:488): Failed to restore snapshot from schedule: c43048b7-85cd-4ba2-af73-0e3a6c9ce363: RestoreSnapshotSchedule RPC (request call id 4) to 10.9.193.37:7100 timed out after 60.000s`

Observed FATALs when tried to repro manually. Steps followed:
```
1. create universe with packed rows enabled
2. create database
3. create snapshot schedule on created database
4. create tablegroup
5. create 100 tables inside tablegroup
6. restore to time 2
```
FATAL details:
```
F20230215 18:40:59 ../../src/yb/master/state_with_tablets.cc:49] Invalid value of enum SysSnapshotEntryPB::State (full enum type: yb::master::SysSnapshotEntryPB_State, expression: state): RESTORED (8).
    @     0x56282cd59e27  google::LogMessage::SendToLog()
    @     0x56282cd5ad6d  google::LogMessage::Flush()
    @     0x56282cd5b3e9  google::LogMessageFatal::~LogMessageFatal()
    @     0x56282e27aea1  yb::FatalInvalidEnumValueInternal()
    @     0x56282d7f1224  yb::master::(anonymous namespace)::InitialStateToTerminalState()
    @     0x56282d7f0e81  yb::master::StateWithTablets::AggregatedState()
    @     0x56282d7e9c83  yb::master::RestorationState::ToEntryPB()
    @     0x56282d7e9c36  yb::master::RestorationState::ToPB()
    @     0x56282d5349ba  yb::master::enterprise::CatalogManager::ListSnapshotRestorations()
    @     0x56282d5b5751  yb::master::MasterBackupServiceImpl::ListSnapshotRestorations()
    @     0x56282d8d626a  std::__1::__function::__func<>::operator()()
    @     0x56282d8d7cef  yb::master::MasterBackupIf::Handle()
    @     0x56282dc7d8ce  yb::rpc::ServicePoolImpl::Handle()
    @     0x56282dbbec8f  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x56282dc8c243  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x56282e305c7f  yb::Thread::SuperviseThread()
    @     0x7fc19e5d4694  start_thread
    @     0x7fc19ead641d  __clone
```

The FATALs issue wasn't reproable and might be intermittent but I was able to reproduce timeout issue, 8/10 times.
Version: 2.17.2.0-b109
Logs from automation: [2.17.2.0_testpitrwithtablegroups-aws-rf3_20230215_143100.zip](https://github.com/yugabyte/yugabyte-db/files/10752201/2.17.2.0_testpitrwithtablegroups-aws-rf3_20230215_143100.zip)
I can share the sql file used to create tables, it used complex datatypes.

[DB-5569]: https://yugabyte.atlassian.net/browse/DB-5569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sanketkedia** [comment]
Steps to reproduce the fatal (one such scenario):
1. Create a snapshot schedule on a database
2. Note down time t1
3. Create any object in this database for e.g. a table, tablegroup, etc
4. Restore to time t1 noted in step(2)
5. Failover the master leader
6. Issue a `yb-admin list_snapshots` or `yb-admin list_snapshot_restorations` and the master leader process will crash

**Comment by sanketkedia** [comment]
The timeout on the other hand is due to slow sys catalog restoration on the master. In particular, the pg_catalog restore step has become time consuming due to 100 objects and it takes a long time to perform IO on so many pg_catalog tables and rows. This is a known limitation and I will start another conversation to see how we can speed it up/remove the sync restore from the apply path of the snapshot operation
