### ISSUE TITLE
[Docs] Enable high availability

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#16133]
### Description

In the page describing [YBA high availability](https://docs.yugabyte.com/preview/yugabyte-platform/manage-deployments/high-availability/), it mentions "xCluster replication". The HA feature does not use xCluster replication - xCluster is a YugabyteDB feature. This should probably say "asynchronous replication" instead.

**Comment by sb-yb** [comment]
Yes. That is wrong. Good catch and thanks for reporting.
"YugabyteDB Anywhere's high availability is an active-standby model for multiple YBA instances."

This is done using periodic pg_backup/restore FWIW. But no need to give details about how we do it.
