### ISSUE TITLE
[YCQL] Add workaround flag for PREPARE performance degradation

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#16135]
Jira Link: [DB-5574](https://yugabyte.atlassian.net/browse/DB-5574)
### Description

During YB upgrade from v2.8.9 to v2.14.5 for a customer the following issue was faced:
Post upgrade we are started observing increasing query latency for writes.
Below query writes to YB DB
```
INSERT INTO tbl (v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) IF (NOT EXISTS OR v8 < ?)
```
In the tserver logs we are observing the error:
```
I0131 04:26:21.943362 10124 mem_tracker.cc:923] Rejecting CQL call: Soft memory limit exceeded (at 85.02% of capacity), score: 1.00
```
We are still seeing the error  Rejecting CQL call: `Soft memory limit exceeded`.

**Root cause**: we have a PREPARE call for every INSERT.
Each PREPARE (on every TS) sends RPC to the Master to get up-to-date table schema version. This is the root cause of the latency issue.

This regression was introduced by the previous fix: https://github.com/yugabyte/yugabyte-db/commit/06f5be74e44c4409913c8caa6f33c6832b64ab3a
See: https://github.com/yugabyte/yugabyte-db/issues/10774

[DB-5574]: https://yugabyte.atlassian.net/browse/DB-5574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
The main proposal to fix this issue: under a new g-flag let's get latest schema version from the internal TS Table Metadata cache. It's much quicker that RPC to the Master.
But with the flag enabled the returned (by PREPARE) table schema can be stale and the user application cannot encode/decode column values correctly. Due to some limitations in the driver implementation the issue workaround is to restart the user application several times (Number of TSes +1 times). Actually we need a failed EXECUTE request to reset the internal TS Table Metadata cache.

Internal design doc:  https://docs.google.com/document/d/10ZrMEtoIKq4AFQD_Nw3UjQ8pYxjusuxnvidL74OfO2o

**Comment by OlegLoginov** [comment]
The main proposal to fix this issue: under a new g-flag let's get latest schema version from the internal TS Table Metadata cache. It's much quicker than RPC to the Master.

But with the flag enabled the returned (by PREPARE) table schema can be stale and the user application cannot encode/decode column values correctly. Due to some limitations in the driver implementation the issue workaround is to restart the user application (or driver instance) several times (Number of TSes +1 times). Actually we need a failed EXECUTE request to reset the internal TS Table Metadata cache in 1 TS. So, in the worst case we need (N+1) reruns to reset cache in all TSes.

Alternative proposal: replace the RPC to the Master by a READ RPC to a local Tablet for this table. But this approach needs partial redesign of the PREPARE handler code.

Internal design doc: https://docs.google.com/document/d/10ZrMEtoIKq4AFQD_Nw3UjQ8pYxjusuxnvidL74OfO2o

**Comment by rthallamko3** [comment]
But for any customer that use prepared statement for every DML (anti-pattern) the flag `cql_use_metadata_cache_for_schema_version_check` should be set to `true`. Its a runtime flag.

**Comment by OlegLoginov** [comment]
In the current version the default value for `cql_use_metadata_cache_for_schema_version_check` is `false`.
If a user application uses prepared statement for every DML (anti-pattern), it's recommended to set `cql_use_metadata_cache_for_schema_version_check` into `true`, otherwise performance degradation can be experienced.
