### ISSUE TITLE
[YSQL] DocDB is asked to project a lot more columns than what is needed for the range tables

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16141]
Jira Link: [DB-5580](https://yugabyte.atlassian.net/browse/DB-5580)
### Description

DocDb is asked to project a lot more columns that what is needed for the range tables/indexes, which results in unnecessary copy of a bunch of columns, that slows down the query significantly

Here is one such example from the aggregate microbenchmark queries.

**YAML**: AGGRG6_sum_bigint_1L_table_rows_(AGGRG6_impact_of_sum_on_increasing_row)

**Query**: `select sum(col_bigint_id_1) from pkeyBigint1L_1`

**Explain Analyze:**

```
Aggregate  (cost=102.50..102.51 rows=1 width=32) (actual time=123.465..123.465 rows=1 loops=1)
  Output: sum(col_bigint_id_1)
  ->  Seq Scan on public.pkeybigint1l_1  (cost=0.00..100.00 rows=1000 width=8) (actual time=1.309..115.795 rows=100000 loops=1)
        Output: col_bigint_id_1, col_bigint_1, col_bigint_2, col_bigint_3, col_bigint_4, col_bigint_5, col_float2_1, col_float2_2, col_float5_1, col_float5_2, col_boolean_1, col_varchar10_id_1, col_varchar100_id_1, col_varchar100_id_2, col_varchar500_id_1
Planning Time: 0.046 ms
Execution Time: 123.532 ms
Peak Memory Usage: 30 kB
```

Other examples can be found in the scan benchmarks as well:
YAML: scanG2_pkey_rangescan_varying_rows_100Krows_

[DB-5580]: https://yugabyte.atlassian.net/browse/DB-5580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
We have fixed the explain output, snapshot from latest perf run. 

```
Aggregate  (cost=102.50..102.51 rows=1 width=32) (actual time=44.042..44.042 rows=1 loops=1)
  Output: sum(col_bigint_id_1)
  ->  Seq Scan on public.pkeybigint1l_1  (cost=0.00..100.00 rows=1000 width=8) (actual time=0.472..21.327 rows=100000 loops=1)
        Output: col_bigint_id_1
        Storage Table Read Requests: 98
        Storage Table Read Execution Time: 12.673 ms
Planning Time: 0.017 ms
Execution Time: 44.065 ms
Storage Read Requests: 98
Storage Read Execution Time: 12.673 ms
Storage Write Requests: 0.000
Catalog Read Requests: 0
Catalog Write Requests: 0.000
```
