### ISSUE TITLE
[YSQL Packed rows] Enabling packed rows, testcase resulted in FATAL: Check failed: closing_ Should have already shut down

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16159]
Jira Link: [DB-5593](https://yugabyte.atlassian.net/browse/DB-5593)
### Description

```
F20230219 06:21:21 ../../src/yb/rpc/messenger.cc:589] Check failed: closing_ Should have already shut down
    @     0x7f7438f8a4fa  google::LogMessage::SendToLog()
    @     0x7f7438f8b730  google::LogMessage::Flush()
    @     0x7f7438f8bc39  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f74393f313c  yb::rpc::Messenger::~Messenger()
    @     0x7f74393f2b5e  yb::rpc::Messenger::~Messenger()
    @     0x7f74393f0276  yb::rpc::MessengerBuilder::Build()
    @     0x7f743ac9254a  yb::client::CreateClientMessenger()
    @     0x7f743daa0570  yb::pggate::PgApiContext::PgApiContext()
    @     0x7f743da97ed1  yb::pggate::YBCInitPgGateEx()
    @     0x558b49bbad3f  YBInitPostgresBackend
    @     0x558b49b98b2b  InitPostgresImpl
    @     0x558b49b986e5  InitPostgres
    @     0x558b499d5e26  PostgresMain
    @     0x558b49918c7e  BackendRun
    @     0x558b49917d40  ServerLoop
    @     0x558b49913295  PostmasterMain
    @     0x558b49818e4f  PostgresServerProcessMain
    @     0x558b494e8aa2  main
    @     0x7f743cd3b825  __libc_start_main
    @     0x558b494e89b9  _start
```
![Profile (2)](https://user-images.githubusercontent.com/109518123/220039760-2bb874bf-cda4-40c9-a771-ff4ee9ed9f4e.png)

http://stress.dev.yugabyte.com/stress_test/d8b9d6a6-06a4-4210-9ae9-3b894441b30f

**Logs:**
[node1_and_node2.zip](https://github.com/yugabyte/yugabyte-db/files/10780833/node1_and_node2.zip)
[node3.zip](https://github.com/yugabyte/yugabyte-db/files/10780837/node3.zip)
[Framework_logs.zip](https://github.com/yugabyte/yugabyte-db/files/10780836/Framework_logs.zip)

[DB-5593]: https://yugabyte.atlassian.net/browse/DB-5593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , Did this happen only one or happens regularly in stress runs?

**Comment by shamanthchandra-yb** [comment]
@rthallamko3 haven't seen this regularly.

**Comment by bmatican** [comment]
@rthallamko3 @Huqicheng Btw, based on the shutdown stack here, I think this is not a packed related issue, but rather some YSQL shutdown issue.
