### ISSUE TITLE
[DocDB] Cluster creation is failing on Mac

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#16173]
Jira Link: [DB-5604](https://yugabyte.atlassian.net/browse/DB-5604)
### Description

Cluster creation is failing on Mac OS of specific versions (Ventura 13.1) with the following error:

> F0220 12:56:49.512884 181301248 replica_state.cc:217] Invalid value of enum LeaderStatus (full enum type: yb::consensus::LeaderStatus, expression: cache.status()): 5.

The failure is happening intermittently both for tests execution and creating cluster via `yb-ctl`

[DB-5604]: https://yugabyte.atlassian.net/browse/DB-5604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@arybochkin , Let me know if this needs to be backported to other braches.
