### ISSUE TITLE
[DocDB] Investigate why intent cleanup is not happening aggressively enough in versions >2.14.x

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16175]
Jira Link: [DB-5606](https://yugabyte.atlassian.net/browse/DB-5606)
### Description

More details to follow, as investigation is still ongoing. But after some upgrades to 2.14.x, we've seen cases of unaccounted memory growth, traced back to TransactionParticipant transaction metadata being held in memory due to intents not being cleaned up properly or aggressively enough.

[DB-5606]: https://yugabyte.atlassian.net/browse/DB-5606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Closing this out in favor of the follow up items like https://github.com/yugabyte/yugabyte-db/issues/16127, https://github.com/yugabyte/yugabyte-db/issues/16351 that came out of this investigation.
