### ISSUE TITLE
[yugabyted] Invoking openssl_proxy.sh in systems that do not soft link sh to bash

### ISSUE THREAD

**Issue by awangc** [yugabyte/yugabyte-db#16182]
Jira Link: [DB-5615](https://yugabyte.atlassian.net/browse/DB-5615)
### Description

Not strictly yugabyted related, but yugabyted calls openssl_proxy.sh, and openssl_proxy.sh is calling for `sh` https://github.com/yugabyte/yugabyte-db/blob/master/bin/openssl_proxy.sh#L1 but using `bash` constructs (`[[ ]]`) https://github.com/yugabyte/yugabyte-db/blob/master/bin/openssl_proxy.sh#L141

This will error out for systems that do not soft link `sh` to `bash`

[DB-5615]: https://yugabyte.atlassian.net/browse/DB-5615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

```
//home/ubuntu/yugabyte-2.17.1.0# ./bin/openssl_proxy.sh
./bin/openssl_proxy.sh: 141: ./bin/openssl_proxy.sh: [[: not found
```

**Comment by gargsans-yb** [comment]
Code fix landed.
