### ISSUE TITLE
[YSQL] flaky test: org.yb.pgsql.TestPgRegressPgMisc.testPgRegressPgMisc

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16188]
Jira Link: [DB-5620](https://yugabyte.atlassian.net/browse/DB-5620)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressPgMisc&fail_tag=all&name=testPgRegressPgMisc&platform=linux

seems to point to d050f04f8a75b7c5da83e6153b7d8182c751957e

[DB-5620]: https://yugabyte.atlassian.net/browse/DB-5620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@jason-yb seems this test is still failing consistently in ASAN. Is that some timing issue, or some legitimate memory issue?

**Comment by jasonyb** [comment]
@bmatican, it's an ASAN issue `stack depth limit exceeded` related to #15682.

**Comment by OlegLoginov** [comment]
Reopening due to the reproducible test failure:
`ybd asan --java-test org.yb.pgsql.TestPgRegressPgMisc#testPgRegressPgMisc`
the error is:
```
-- Check that stack depth detection mechanism works and                         -- Check that stack depth detection mechanism works and
-- max_stack_depth is not set too high                                          -- max_stack_depth is not set too high
create function infinite_recurse() returns int as                               create function infinite_recurse() returns int as
'select infinite_recurse()' language sql;                                       'select infinite_recurse()' language sql;
\set VERBOSITY terse                                                            \set VERBOSITY terse
select infinite_recurse();                                                      select infinite_recurse();
ERROR:  stack depth limit exceeded                                            | server closed the connection unexpectedly
                                                                              >         This probably means the server terminated abnormally
                                                                              >         before or while processing the request.
                                                                              > connection to server was lost
```
It should be investigated & fixed in another GHI.

**Comment by d-uspenskiy** [comment]
ASAN failure is fixed in context of https://github.com/yugabyte/yugabyte-db/commit/c2e13ef7168f815f5b99a31e43614e462a128c23
