### ISSUE TITLE
[DocDB] Add per-tablet memory overhead to the MemTracker

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16196]
Jira Link: [DB-5627](https://yugabyte.atlassian.net/browse/DB-5627)
### Description

As a followup to https://github.com/yugabyte/yugabyte-db/issues/7998, we should go further and add this memory overhead explicitly into the MemTracker handling.

For metrics, we need to be careful about per-table vs per-tablet metrics, as @amitanandaiyer did some refactoring of those, to better aggregate. So we'd need to consider the tablet lifecycle on these.

For the rocksdb arena, we likely need to consider the lifecycle of the memstores and/or rocksdbs themselves (eg: truncate / drop resetting rocksdbs).

[DB-5627]: https://yugabyte.atlassian.net/browse/DB-5627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yusong-yan** [comment]
I will create a separate Github issue for adding Rocksdb arena overhead.

**Comment by rthallamko3** [comment]
Given that the per tablet overhead is fixed, we decided to not backport the fix to stable branches.
