### ISSUE TITLE
Improve failed local tablet bootstrap handling

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1620]
We've had a number of situations where a TS would fail to open a tablet, yet would continue to be part of the Raft group, just unable to do much. This can happen, for example, due to corrupted or missing files, such as rocksdb current, manifest or SST files, or raft wal or cmeta files.

There's various things we can do to address these types of situations, some proactive, some reactive and some more self-healing, however most have their own tradeoffs.

On the aggressive side, we could have the TS mark its tablet as failed and ask its leader to do a remote bootstrap, to bring in the latest leader approved files. However, this has both some safety concerns (don't want to risk data loss), as well as performance issues (network transfer of relatively large tablets). For perf, we might be able to alleviate the problem though, with features such as #1217.

On the self healing side, we might be able to add defensive code to either ensure we do not get corruption (atomic FS commands for metadata files), or rebuilding code (some metadata files might be a perf considerations and could be rebuilt from data files). However, this requires significant work and likely across varied components, as well as a systematic audit to be comfortable with having caught all failure modes.

An intermediate approach could be slightly more operational. We can easily detect this situation and augment health checking and overall error reporting to bubble this up to the users. If we have the ability to repair corruption, we can turn this into tooling. If we cannot repair corruption, we might still want to leave it up to an operator to intervene.

As such, we should do the following:
- build the capability to tombstone a tablet, via RPC, but do not enable it automatically on tablet bootstrap failure!
- build tooling, say a yb-admin command, to trigger this on demand, by an operator
- enhance error reporting to bubble this info up through alerting
- out of band investigate issues one at a time, for implementing automatic fixes on corruption

cc @mbautin @spolitov @hectorgcr

**Comment by rajukumaryb** [comment]
`FAILED` tablets on a tserver can be found by using `grep -w FAILED` on - 
    `yb-admin -master_addresses <master_addresses> list_tablets_for_tablet_server <ts_uuid>`

A `FAILED` tablet can be tombstoned by using -
    `yb-ts-cli --server_address=<tserver_ip>:9100 delete_tablet <tablet_id> <log_msg>`

NOTE: in spite of the keyword `delete_tablet` in the command above, the `delete_type` is `tablet::TABLET_DATA_TOMBSTONED` - the tablet is hence tombstoned, not deleted.
