### ISSUE TITLE
[DocDB] Unable to establish replica leadership after cluster expansion

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#16236]
Jira Link: [DB-5658](https://yugabyte.atlassian.net/browse/DB-5658)
### Description

```
Failed to execute task {"platformVersion":"2.17.2.0-b151","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"99a6846a-dbc2-425b-9a88-a7bac71c3697","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"y..., hit error:

WaitForLeadersOnPreferredOnly(99a6846a-dbc2-425b-9a88-a7bac71c3697) did not complete..
```

Steps to repro:
1. Create a YCQL table and set up PITR
2. Insert data into the table
3. Delete data from the table
4. Add 3 nodes ------> Fails
Note: No issue is observed if any one of the above parameter is removed

https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/3754/consoleFull

[DB-5658]: https://yugabyte.atlassian.net/browse/DB-5658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
Looks like master leader cannot be established:
```
E0224 11:05:27.236269 20430 async_initializer.cc:95] Failed to initialize client: Timed out (yb/rpc/rpc.cc:222): Could not locate the leader master: GetLeaderMasterRpc(addrs: [10.9.136.193:7100, 10.9.192.144:7100, 10.9.82.217:7100, 10.9.136.193:7100, 10.9.192.144:7100, 10.9.82.217:7100], num_attempts: 51) passed its deadline 381.430s (passed: 1.517s): Not found (yb/master/master_rpc.cc:288): no leader found: GetLeaderMasterRpc(addrs: [10.9.136.193:7100, 10.9.192.144:7100, 10.9.82.217:7100, 10.9.136.193:7100, 10.9.192.144:7100, 10.9.82.217:7100], num_attempts: 1)
```
But also some issues at tservers:
```
 W0224 11:44:43.292068 20479 raft_consensus.cc:1373] Leader lease expiration was not set: Illegal state (yb/consensus/replica_state.cc:1353): NoOp of current term is not committed (majority_replicated_lease_expiration_ = <uninitialized>, majority_replicated_ht_lease_expiration_ = 0)
```

**Comment by robertsami** [comment]
Looks like automatic tablet splitting is enabled as well

**Comment by rthallamko3** [comment]
The test was using the following aggressive gflags: 
m_flags = {"enable_automatic_tablet_splitting" = "true",
        "tablet_split_high_phase_shard_count_per_node" = 100000,
        "tablet_split_high_phase_size_threshold_bytes" = 1048576,  # 1 MB
        "tablet_split_low_phase_size_threshold_bytes" = 10240,  # 10 KB
        "tablet_split_low_phase_shard_count_per_node" = 1000,
        "enable_stream_compression" = "true",
        "stream_compression_algo" = 1,
        "enable_truncate_on_pitr_table": "true"
}
t_flags={
        "yb_num_shards_per_tserver" = 1,
        "ycql_enable_packed_row": "true"
        "enable_automatic_tablet_splitting" = "true"
}
(edited)


With input from @hulien22 , bumping up some of the load balancer flags (from 1 to 3 helped improve the load balancer speed):
load_balancer_max_over_replicated_tablets
load_balancer_max_concurrent_adds
load_balancer_max_concurrent_removals
load_balancer_max_concurrent_moves_per_table
