### ISSUE TITLE
[DocDB] ldb manifest_dump fails in 2.12

### ISSUE THREAD

**Issue by jmeehan16** [yugabyte/yugabyte-db#16235]
Jira Link: [DB-5657](https://yugabyte.atlassian.net/browse/DB-5657)
### Description

In version 2.12, the `ldb manifest_dump` command fails when accessing a rocksdb MANIFEST file. The same file will open fine in the 2.17.1 version of the tool.

Run on a 2.12.10 cluster using the 2.12.10 version of the tool:

`./ldb manifest_dump --path=/mnt/d0/yb-data/tserver/data/rocksdb/table-8b2ad5af47ef46aabff43d2ad48bde03/tablet-0c19c426a5dc4123b577a319d4d9ba5c/MANIFEST-000013`

> Error in processing file /mnt/d0/yb-data/tserver/data/rocksdb/table-8b2ad5af47ef46aabff43d2ad48bde03/tablet-0c19c426a5dc4123b577a319d4d9ba5c/MANIFEST-000013 Illegal state (yb/rocksdb/db/version_edit.cc:180): Boundary values contains user frontier but extractor is not specified: key: "G\000\000S980a5363-2996-4c58-b5ab-b008f76c4362:1054314\000\000!!J\200#\200\001^\354B:\254\216\200J\0017\256\002\000\000\000\004" seqno: 1125899906842625 user_values { tag: 1 data: "\200\001^\354\206-\242\342\200J" } user_frontier { [type.googleapis.com/yb.docdb.ConsensusFrontierPB] { op_id { term: 1 index: 2 } hybrid_time: 6869422163067260928 history_cutoff: 18446744073709551614 max_value_level_ttl_expiration_time: 18446744073709551614 } }

Same command using the 2.17.1 tool:

> --------------- Column family "default"  (ID 0) --------------

> log number: 4
> comparator: leveldb.BytewiseComparator
> --- level 0 --- version# 1 ---
> { number: 10 total_size: 5420804 base_size: 205661 being_compacted: 0 smallest: { seqno: 1125899906842625 user_frontier: 0x000055a8b9b0a2a0 -> { op_id: 1.2 hybrid_time: { physical: 1677105020280093 } history_cutoff: <invalid> hybrid_time_filter: <invalid> max_value_level_ttl_expiration_time: <invalid> primary_schema_version: <NULL> cotable_schema_versions: [] } } largest: { seqno: 1125899907132804 user_frontier: 0x000055a8b9b0aaf0 -> { op_id: 2.145092 hybrid_time: { physical: 1677106773197952 } history_cutoff: <invalid> hybrid_time_filter: <invalid> max_value_level_ttl_expiration_time: <initial> primary_schema_version: <NULL> cotable_schema_versions: [] } } } 
> next_file_number 15 last_sequence 1125899907132838 prev_log_number 0 max_column_family 0 flushed_values 0x000055a8b9b0ab60 -> { op_id: 2.145092 hybrid_time: { physical: 1677106773197952 } history_cutoff: <invalid> hybrid_time_filter: <invalid> max_value_level_ttl_expiration_time: <initial> primary_schema_version: <NULL> cotable_schema_versions: [] }

[DB-5657]: https://yugabyte.atlassian.net/browse/DB-5657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment]
There's a fix for 2.17 https://github.com/yugabyte/yugabyte-db/issues/14716. It should be a DEBUG-build problem only. @jmeehan16 could you please confirm you use debug version for 2.12?
Is it OK to backport #14716 to 2.12-2.16 and close this GH as duplicated, cc @rthallamko3?

**Comment by rthallamko3** [comment]
@arybochkin , Since its a debug only issue, I agree to resolve this as DUP. I don't see a strong reason to backport debug only failures, unless we use this tool quite frequently.

**Comment by jmeehan16** [comment]
@arybochkin @rthallamko3 I can confirm that this is not just a DEBUG problem. We just attempted an `ldb manifest_dump` on 2.12 with a customer, and the dump was unsuccessful - in this case, the error was slightly different (didn't get to screencap, but it was something along the lines of something not being a directory).

I can also confirm that the 2.17.1 version of `ldb manifest_dump` worked as expected on the same 2.12 manifest files.

**Comment by arybochkin** [comment]
@rthallamko3 I'm reopening to track backports as @jmeehan16 confirms the issue can appear in release version.

**Comment by arybochkin** [comment]
Backports are going to be done within #14716.
