### ISSUE TITLE
[YSQL] yb_enable_expression_pushdown for GIN index scan can yield incorrect results

### ISSUE THREAD

**Issue by sbalasubramaniam-yb** [yugabyte/yugabyte-db#16253]
Jira Link: [DB-5677](https://yugabyte.atlassian.net/browse/DB-5677)
### Description

yb_enable_expression_pushdown does not seem to work correctly. Refer to the slack thread - https://yugabyte.slack.com/archives/CAR5BCH29/p1677518458483219

The test case to reproduce the error is below: 
 ```
drop table demo;

CREATE TABLE demo(
     demo_id varchar(255) not null,
     guid varchar(255) not null unique,
     status varchar(255),
     json_content jsonb not null,
  primary key (demo_id)
);

CREATE INDEX ref_idx ON demo USING ybgin (json_content jsonb_path_ops) ;

insert into demo select x::text, x::text, x::text, ('{"externalReferences": [{"val":"'||x||'"}]}')::jsonb
   from generate_series (1, 10) x;

-- wrong answer
set yb_enable_expression_pushdown=on;
select * from demo where json_content @> '{"externalReferences": [{"val":"9"}]}' and demo_id <> '9';
demo_id | guid | status |              json_content
---------+------+--------+----------------------------------------
 9       | 9    | 9      | {"externalReferences": [{"val": "9"}]}

-- correct answer
set yb_enable_expression_pushdown=off;
select * from demo where json_content @> '{"externalReferences": [{"val":"9"}]}' and demo_id <> '9';
yugabyte=#  demo_id | guid | status | json_content
---------+------+--------+--------------
(0 rows)
```

[DB-5677]: https://yugabyte.atlassian.net/browse/DB-5677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
The bug was effectively introduced by 3ca3ac8f38efd580704ae55ea364a4bf868f83ff which never made it to any stable branch. No backports needed.

**Comment by andrei-mart** [comment]
My bad https://github.com/yugabyte/yugabyte-db/commit/3ca3ac8f38efd580704ae55ea364a4bf868f83ff made it to 2.15-2.17, need to backport

**Comment by andrei-mart** [comment]
Backport has been completed
