### ISSUE TITLE
[YSQL] flaky test: PgTxnTest.ReadRecentSet

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16263]
Jira Link: [DB-5689](https://yugabyte.atlassian.net/browse/DB-5689)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgTxnTest&fail_tag=all&name=ReadRecentSet&platform=linux

Seems to trace to either c5f22319c2b77de0f2ebeeb797791d925dfd070d or 57a7d98afb2c4335f7f08b3c7ef3ad299ebcd4e8

[DB-5689]: https://yugabyte.atlassian.net/browse/DB-5689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
3 flaky failures in last 100 commits (800 test runs across 8 builds). Closing as fixed for now.
