### ISSUE TITLE
Unable to Open yugabyte ui from Kubernetes Cluster (Rancher)

### ISSUE THREAD

**Issue by prasannavasan** [yugabyte/yugabyte-db#16281]
### Description

I am facing an issues in setting up yb-demo following [[https://docs.yugabyte.com/preview/quick-start/kubernetes](https://docs.yugabyte.com/preview/quick-start/kubernetes)/] on rancher v2.6.10 3 node cluster. 

3 nodes are EC2 instances of 4 cpu cores 16GB memory and 100GB disk each. I have 2 nodes with all roles and 1 node with just worker node. Has anyone set up yugabyte db on a rancher cluster before? If so any recommendation on the cni and configs? (Suspected to be a DNS issue)

I have tried to open the Yugabyte UI via port forwarding mentioned in the docs and running to the error.

`kubectl --namespace yb-demo port-forward svc/yb-master-ui 7000:7000`

![image](https://user-images.githubusercontent.com/8968433/222429742-4ff4e88c-015b-4b3b-8ffc-0dbfc86177fc.png)

I ran the following command on my cluster to install 
`helm install yb-demo yugabytedb/yugabyte --version 2.17.1 --set resource.master.requests.cpu=0.5,resource.master.requests.memory=0.5Gi,resource.tserver.requests.cpu=0.5,resource.tserver.requests.memory=0.5Gi,resource.master.limits.cpu=1,resource.master.limits.memory=1Gi,resource.tserver.limits.cpu=1,resource.tserver.limits.memory=1Gi,storage.ephemeral=true --namespace yb-demo`

I see the below errors when I log a master pod (yb-master-0)

> consensus_peers.cc:727] Retrying to get permanent uuid for remote peer: [yb-master-1.yb-masters.yb-demo.svc.cluster.local:7100] attempt: 13
> W0302 10:31:05.974820    43 proxy.cc:305] Resolve yb-master-1.yb-masters.yb-demo.svc.cluster.local failed: Network error (yb/util/net/dns_resolver.cc:65): Resolve failed yb-master-1.yb-masters.yb-demo.svc.cluster.local: Host not found (authoritative)
> client-internal.cc:2314] New master addresses: [yb-master-0.yb-masters.yb-demo.svc.cluster.local:7100,yb-master-1.yb-masters.yb-demo.svc.cluster.local:7100,yb-master-2.yb-masters.yb-demo.svc.cluster.local:7100]
> 3 proxy.cc:305] Resolve yb-master-1.yb-masters.yb-demo.svc.cluster.local failed: Network error (yb/util/net/dns_resolver.cc:65): Resolve failed yb-master-1.yb-masters.yb-demo.svc.cluster.local: Host not found (non-authoritative), try again later

Appreciate any help on this.

![image](https://user-images.githubusercontent.com/8968433/222429213-fb329464-72ac-4eac-8e73-9a498d80206a.png)
![image](https://user-images.githubusercontent.com/8968433/222429317-30b885de-f730-48ae-b601-40c28049ad16.png)

**Comment by DJAlPee** [comment]
Is there a solution for this issue?
I have the same issue (with almost the same helm settings) on Talos.

**Comment by DJAlPee** [comment]
I have found the cause for this issue:
https://github.com/yugabyte/charts/blob/master/stable/yugabyte/templates/service.yaml#L82-L91
The `Service` resources are **always** created in the default namespace. I'm wondering, that nobody else deployed yugabyte in a non-default namespace using helm

**Comment by prasannavasan** [comment]
@DJAlPee Thanks!
