### ISSUE TITLE
[YSQL] flaky test: org.yb.pgsql.TestPgMisc.testBatchedNestLoopExtendedQuery

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16304]
Jira Link: [DB-5727](https://yugabyte.atlassian.net/browse/DB-5727)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgMisc&fail_tag=all&name=testBatchedNestLoopExtendedQuery&platform=linux

[DB-5727]: https://yugabyte.atlassian.net/browse/DB-5727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tanujnay112** [comment]
Seems to be fixed now by d494baf9aec8bf4642b3ced7c02db655b01a62d0
