### ISSUE TITLE
[YSQL] flaky test: PgMiniTest.ConcurrentSingleRowUpdate

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16305]
Jira Link: [DB-5728](https://yugabyte.atlassian.net/browse/DB-5728)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgMiniTest&fail_tag=all&name=ConcurrentSingleRowUpdate&platform=linux

traces to https://phabricator.dev.yugabyte.com/D23045 or https://phabricator.dev.yugabyte.com/D23044

[DB-5728]: https://yugabyte.atlassian.net/browse/DB-5728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=PgMiniTest&name=ConcurrentSingleRowUpdate

No failures in last 100 commits. Closing as fixed.
