### ISSUE TITLE
[DocDB] Packed rows uses wrong system catalog schema version

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#16314]
Jira Link: [DB-5742](https://yugabyte.atlassian.net/browse/DB-5742)
### Description

System catalog schema version does not change during lifetime.
But packed rows uses value 1 for schema version, while it is should be 0.

[DB-5742]: https://yugabyte.atlassian.net/browse/DB-5742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Relevant for CQL workloads only.
