### ISSUE TITLE
[DocDB] Insert with timestamp ignores expired packed row

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#16333]
Jira Link: [DB-5758](https://yugabyte.atlassian.net/browse/DB-5758)
### Description

When inserting row with specified timestamp, we should check whether there was row with greater timestamp.
In case of packed row it was ignored if such row already expired because of TTL.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5758]: https://yugabyte.atlassian.net/browse/DB-5758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
The issue is relevant for CQL workloads only.
