### ISSUE TITLE
Yugaware helm chart needs ability to reference alternate repositories

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#1634]
To support customers who are seeking a more "airgapped" installation experience with kubernetes, we need to allow the specification of alternate repositories for YW dependencies such as prometheus, dnsmasq and our own third-party dependencies image. We probably should also extend this support for nginx / postgres as well.

**Comment by iSignal** [comment]
The ask is for us to support a base repo like quay.io that will then apply to all images in the chart. Unlike Image.repository currently which only applies to yugabyte/yugaware repo.

**Comment by iSignal** [comment]
Fixed in https://github.com/yugabyte/charts/commit/7e7857bc904cb9335bd4a175f872d9501c5e9d24

Will keep this issue open to also provide a similar solution for the db image.

**Comment by iSignal** [comment]
Platform image repos are configurable via helm chart. 

DB image still needs configurability for the busybox repo - https://github.com/yugabyte/yugabyte-db/issues/6964
