### ISSUE TITLE
[DocDB] Include Table type as part of metrics exposed by DB

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#16343]
Jira Link: [DB-5761](https://yugabyte.atlassian.net/browse/DB-5761)
### Description

It would be nice if the DB exported metrics for number of tables per DB and number of tablets per DB.

Alternatively if TableType is exported as part of Table and replication metrics, then those can be leveraged for better reporting and alerting.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5761]: https://yugabyte.atlassian.net/browse/DB-5761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by omkaark** [comment]
Can I please get some more info into where DB metrics are exported in the codebase?
