### ISSUE TITLE
[DocDB] Secondary index update request gets stuck with no callback

### ISSUE THREAD

**Issue by yusong-yan** [yugabyte/yugabyte-db#16351]
Jira Link: [DB-5765](https://yugabyte.atlassian.net/browse/DB-5765)
### Description

We have seen an issue with the secondary index update request in WriteQuery gets stuck with no callback. This caused the WriteQuery object never get destroyed, and its RequestScope that reserved in TransactionParticipant holds transactions cleaned up for a long time. Thus, many transactions in memory lead to soft memory limit issue.
 - We can create an artificial test gflag to miss the callback until we found the actual condition of the missing callback.
 - Releasing RequestScope before the index update request can mitigate the issue.

[DB-5765]: https://yugabyte.atlassian.net/browse/DB-5765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
reopening to backport [0aec96a](https://github.com/yugabyte/yugabyte-db/commit/0aec96a854babfabeb0de9ab1d3c60b5ea26384d) to 2.14 and 2.16 as that commit has useful telemetry, that can be used.
