### ISSUE TITLE
[DocDB] Enable packed row in backup restore unit tests

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16369]
Jira Link: [DB-5786](https://yugabyte.atlassian.net/browse/DB-5786)
### Description

Commit f7e8c29e disabled packed row in Backup restore unit tests. This should be undone.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5786]: https://yugabyte.atlassian.net/browse/DB-5786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Passing to Sandeep for now. I assume some of these are disabled for the x-feature tests, so might be xcluster/colocation/cdc
