### ISSUE TITLE
[k8s] Consider keeping helm fork's master in sync with upstream

### ISSUE THREAD

**Issue by aegershman** [YugaByte/yugabyte-db#1636]
In order to keep `helm/charts` forks more manageable, it would be beneficial if the `yugabyte/charts` fork kept it's `master` branch up to date with the upstream && perhaps kept chart development workloads in separate branches.

This way when someone forks the yugabyte/charts repo to submit PRs, it doesn't conflict as much with other forks that the PR author might have on other charts in the upstream helm/charts repo

**Comment by ramkumarvs** [comment]
Not sure forking our repo would have any issues for other committers but we can certainly keep the fork upto date with upstream repo.
