### ISSUE TITLE
[CDCSDK] Enable Paced Row feature in CDC unit tests 

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16368]
Jira Link: [DB-5785](https://yugabyte.atlassian.net/browse/DB-5785)
### Description

Commit f7e8c29e disabled Packed Row in CDC tests due to integration issues. Enable Paced Row feature in CDC unit tests, once the integration aspects are resolved.

### Source connector version

N/A

### Connector configuration

N/A

### YugabyteDB version

2.17.2

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5785]: https://yugabyte.atlassian.net/browse/DB-5785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rknsai-yb** [comment]
Done as part of https://phabricator.dev.yugabyte.com/D22697
