### ISSUE TITLE
[DocDB] Ensure promoted waiter transaction gets to see its updated transaction state

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#16375]
Jira Link: [DB-5791](https://yugabyte.atlassian.net/browse/DB-5791)
### Description

**Description**

Area: Wait-queues / Deadlock detection

When a transaction gets promoted to global, it's old status tablet reflects kAborted state. In wait-queue, we periodically poll the transaction participant on waiter txn(s) status. If a transaction has not yet done any operation at the tablet, it isn't registered with the txn participant. In such a case, the txn participant returns status NOT_FOUND when polled for waiter transaction status. We then directly poll the status tablet. 

It could happen that a waiter gets promoted to global and the we poll the old status tablet in the wait-queue, and get to see a kAborted state. Instead, we should query the latest status tablet when we see kAborted state, to ensure that the transaction is really aborted. 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5791]: https://yugabyte.atlassian.net/browse/DB-5791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
This is a follow up to https://github.com/yugabyte/yugabyte-db/issues/16612

**Comment by basavaraj29** [comment]
now that https://github.com/yugabyte/yugabyte-db/issues/16612 is fixed, we could miss detecting real deadlocks. closing this current issue as we have https://github.com/yugabyte/yugabyte-db/issues/17009 tracking the bug.
