### ISSUE TITLE
[Docs] Kafka Connect YugabyteDB

### ISSUE THREAD

**Issue by phendric-uk** [yugabyte/yugabyte-db#16387]
### Description

In section 'Setup and use' of https://docs.yugabyte.com/preview/reference/connectors/kafka-connect-yugabytedb/ , step 2 shows:

Start Zookeeper and Kafka server.
```
~/yb-kafka/kafka_2.12-2.5.0/bin/zookeeper-server-start.sh config/zookeeper.properties &
~/yb-kafka/kafka_2.12-2.5.0/bin/kafka-server-start.sh config/server.properties &

```
This fails as you need to be in the ~/yb-kafka/kafka_2.12-2.5.0 directory

We could either:
Add '~/yb-kafka/kafka_2.12-2.5.0/' before 'config/zookeeper.properties' and before 'config/server.properties'
or
Add 'cd ~/yb-kafka/kafka_2.12-2.5.0' as the first command.

So it could read:

Start Zookeeper and Kafka server.
```
cd ~/yb-kafka/kafka_2.12-2.5.0
~/yb-kafka/kafka_2.12-2.5.0/bin/zookeeper-server-start.sh config/zookeeper.properties &
~/yb-kafka/kafka_2.12-2.5.0/bin/kafka-server-start.sh config/server.properties &
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by phendric-uk** [comment]
On the same page, there is another issue:

`~/yb-kafka/kafka_2.12-2.5.0/bin/kafka-topics.sh --create --zookeeper localhost:2181--replication-factor 1 --partitions 1 --topic test`

fails because there is no space before --replication-factor.

It should read:

`~/yb-kafka/kafka_2.12-2.5.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test`

**Comment by phendric-uk** [comment]
One more in step 7:

```
demo=# CREATE TABLE demo.test_table (key text, value bigint, ts timestamp, PRIMARY KEY (key));
ERROR:  schema "demo" does not exist
LINE 1: CREATE TABLE demo.test_table (key text, value bigint, ts tim...
```
fails

```
demo=# CREATE TABLE test_table (key text, value bigint, ts timestamp, PRIMARY KEY (key));
CREATE TABLE
```
works

**Comment by ddorian** [comment]
Internal thread https://yugabyte.slack.com/archives/CDHEH3N64/p1678981693973399

**Comment by phendric-uk** [comment]
@ddorian Can we remove this page so that it is no longer available?

Thanks

**Comment by ddorian** [comment]
@phendric-uk the page has been removed and redirected to newer docs. Closing as fixed.
