### ISSUE TITLE
[yugabyted] placement hardcoded to `cloud1.datacenter1.rack1` even when `cloud_location` is defined

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#16403]
Jira Link: [DB-5812](https://yugabyte.atlassian.net/browse/DB-5812)
### Description

When starting `yugabyted start` with a `--cloud_location` the configuration is still set to: `cloud1.datacenter1.rack1` in https://github.com/yugabyte/yugabyte-db/blob/master/bin/yugabyted#L4006 which leaves the cluster in an inconsistent state. This can lead to data loss because of https://github.com/yugabyte/yugabyte-db/issues/16402

I guess the `set_rf()` should define one placement block for each item in `placement_locations`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5812]: https://yugabyte.atlassian.net/browse/DB-5812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nchandrappa** [comment]
Originally, On `yugabyted start` of the first node, yugabyted applied RF-1 configuration along with default placement location of `cloud1.datacenter1.rack1`. We have made changes not to apply the default placement info, `cloud_location` values will be considered now without needing to run `yugabyted configure data_placement` command. 

@FranckPachot Issue you reported above regarding the cluster being in an inconsistent state is no longer applicable. Please review the latest release and let us know.

**Comment by nchandrappa** [comment]
yugabyted behavior is updated to apply a data placement policy when the 3rd node joins the cluster. Data placement policy will be based on the `--cloud_location` provided in the 3 nodes that join to form a cluster. The implied data placement policy can be updated using `yugabyted configure data_placement` command.
