### ISSUE TITLE
[yugabyted] `configure data_placement` fails with uppercase placement info

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#16401]
Jira Link: [DB-5810](https://yugabyte.atlassian.net/browse/DB-5810)
### Description

In https://github.com/yugabyte/yugabyte-db/blob/master/bin/yugabyted#L2176 the placement constraint is transformed to lowercase to be compared with the `placement_locations` array. However, we can set placement locations with uppercase and then it fails.

Example:
```
yugabyted start --cloud_location Cloud.Region.Zone
yugabyted configure data_placement --constraint_value=Cloud.Region.Zone
```
fails with:
```
FAILED: Invalid number of placement constraint specified.
For more information, check the logs in /root/var/logs
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5810]: https://yugabyte.atlassian.net/browse/DB-5810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Code Fix Landed.
