### ISSUE TITLE
[YSQL] [DocDB] Upgrade OpenSSL to 3.0.8 from 1.1.1

### ISSUE THREAD

**Issue by timothy-e** [yugabyte/yugabyte-db#16407]
Jira Link: [DB-5816](https://yugabyte.atlassian.net/browse/DB-5816)
### Description

Upgrade the OpenSSL version from 1.1.1 to 3.0.8, as 1.1.1 version support is ending.

Advantages of upgrading to OpenSSL 3.0.8:
* The failure logs will give the failure reason as well (https://postgrespro.com/list/thread-id/2585389)
* Version 1.1.1 will be supported until 2023-09-11
* 3.0+ also has a new trace API to help with debugging. 

[OpenSSL migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html)

- Import required upstream PG commits
  - [x] #19732
  - [x] #19733
  - [x] #19734
- [x] #19737  - Imported PG commits depend on it
- [x] #19727 - Triggered when there are no available protocols - relevant with 3.0.8 version.
- [x] #19736

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5816]: https://yugabyte.atlassian.net/browse/DB-5816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mbautin** [comment]
Recommendation from @proff4eg : upgrade to OpenSSL 3.1.0 (fips 140-3 certification).

**Comment by bmatican** [comment]
Notes for future: https://www.openssl.org/docs/man3.0/man7/migration_guide.html#:~:text=Applications%20written%20to%20work%20with,concepts%20introduced%20in%20OpenSSL%203.0.
>Upgrading from OpenSSL 1.1.1
