### ISSUE TITLE
Is there a way to separately configure/override just the port used for YSQL/YCQL/YEDIS instead of coupling the port with these gflags.

### ISSUE THREAD

**Issue by ajaxdone** [YugaByte/yugabyte-db#1641]
--redis_proxy_bind_address
--cql_proxy_bind_address
--pgsql_proxy_bind_address

fyi - issue was resolved after we did a destroy, and then for the port override, changed bin/yb-ctl

from:
       `"--redis_proxy_bind_address=" + daemon_ip_address_str,`
to:
       `"--redis_proxy_bind_address=" + daemon_ip_address_str + ":6123"`

Please do support the port overrides by a separate control rather than via these
--redis_proxy_bind_address
--cql_proxy_bind_address
--pgsql_proxy_bind_address

**Comment by mbautin** [comment]
Almost done with adding support for this to yb-ctl, will post a pull request shortly.

**Comment by mbautin** [comment]
Pull request: https://github.com/YugaByte/yugabyte-installation/pull/12
@bmatican -- could you take a look when you have a chance?

**Comment by bmatican** [comment]
Took a first pass.

**Comment by mbautin** [comment]
@ajaxdone: I've merged a fix for this issue: https://github.com/YugaByte/yugabyte-installation/pull/12/commits/fa4155bd3c909b9439e5dfc670c5c8c4dd293f35

While this is not yet in an official release of YugaByte DB, you can grab the yb-ctl script from https://raw.githubusercontent.com/YugaByte/yugabyte-installation/master/bin/yb-ctl and put it into your YugaByte DB installation's `bin` directory, and then you can use `--ysql_port`, `--ycql_port`, and `--yedis_port` command line flags. Please let me know if anything is not working as expected.
