### ISSUE TITLE
[DocDB] Master leader election failure - leader never acquired lease

### ISSUE THREAD

**Issue by vmallepalli** [yugabyte/yugabyte-db#16416]
Jira Link: [DB-5829](https://yugabyte.atlassian.net/browse/DB-5829)
### Description

Ran into `WaitForMasterLeader hit error : Timed out waiting for Master Leader after 300000 ms` when performing an instance resize via YBA. 

6 node, single region, RF3 cluster running db version `2.14.6.0-b30`. 

During the instance resize on node -n1, it added node -n1 to the leader blacklist.
Then, it stopped the master processes on the node.
Then, it waited for the master leader — which timed out and failed.
Since there were 6 nodes in the same region, RF3, there should have been 2 other masters that could reach quorum and perform the election. But that’s not what happened. Logs from -n2 show issues with heartbeating / not being able to find the master leader. [Logs](https://app.datadoghq.com/logs?query=cluster-id%3A4a1270ab-2f8a-4d04-a490-a6663e896c54%20name%3A%2A-n2%20-status%3A%28notice%20OR%20info%29&additional_filters=%5B%7B%7D%5D&agg_q=name&cols=&index=%2A&messageDisplay=inline&sort_m=&sort_t=&stream_sort=time%2Casc&top_n=10&top_o=top&viz=pattern&x_missing=true&from_ts=1678132980000&to_ts=1678133700000&live=false).

Please help identify the root cause of the leader election failure. Thanks!

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.

[DB-5829]: https://yugabyte.atlassian.net/browse/DB-5829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by druzac** [comment]
Root cause was a full disk on a node hosting a master.
