### ISSUE TITLE
[CDCSDK] Need to support multiple tasks (parallelism of streaming) with colocation tables

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16479]
Jira Link: [DB-5884](https://yugabyte.atlassian.net/browse/DB-5884)
### Description

As of now:

If more than 1 tasks is configured with single connector and multiple colocated tables, CDC fails. Tracking it with https://github.com/yugabyte/yugabyte-db/issues/16462

As per discussion with @vaibhav-yb , there is a fix he is working on which basically ignores more than 1 tasks and have only 1 task for this type of connector.

But parallelism will not be achieved with this. Hence this ticket tracks the support of multiple tasks (parallel) streaming from colocated tables. 

### Source connector version

1.9.5.y.16

### Connector configuration

```
add connector connector_name='ybconnector_cdc_62aae3_test_cdc_8e3398_test_cdc_60b303' stream_id='40d2e3c6c0c246139c03e029bc22c3ab' db_name='cdc_62aae3' connector_host='172.151.17.222' table_list=['test_cdc_8e3398', 'test_cdc_60b303'] {'name': 'ybconnector_cdc_62aae3_test_cdc_8e3398_test_cdc_60b303', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.19.15', 'database.master.addresses': '172.151.19.15:7100,172.151.25.254:7100,172.151.25.170:7100', 'database.port': 5433, 'database.masterhost': '172.151.19.15', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_62aae3', 'database.server.name': 'db_cdc', 'database.streamid': '40d2e3c6c0c246139c03e029bc22c3ab', 'snapshot.mode': 'never', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_8e3398,public.test_cdc_60b303'}}
```

### YugabyteDB version

2.17.3.0-b93

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5884]: https://yugabyte.atlassian.net/browse/DB-5884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by suranjan** [comment]
There is no immediate plan to support multiple tasks for colocated tables. We have done basic validation with TPCC to see if single task hampers performance and did not see any limitations as such.

**Comment by suranjan** [comment]
@shamanthchandra-yb Please raise it with perf ticket and track it as perf issue if you observe a lag.

**Comment by shamanthchandra-yb** [comment]
Raised https://github.com/yugabyte/yugabyte-db/issues/16484 to document.
