### ISSUE TITLE
[YSQL] Tablet splitting: select from yb_table_properties() returns stale number of tablets

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#16492]
Jira Link: [DB-5894](https://yugabyte.atlassian.net/browse/DB-5894)
### Description

Selection from yb_tablet_properties() returns incorrect number of tablets after tablet splitting.
Steps:
1) `./bin/yb-ctl --rf=1 start`
2) Execute `# create table test (k int, v int, primary key (k asc));`
3) Execute `# insert into test select i, i from generate_series(1,100) as i;`
4) Get table properties
```
# select * from yb_table_properties((select oid from pg_class WHERE relname='test'));

 num_tablets | num_hash_key_columns | is_colocated | tablegroup_oid | colocation_id 
-------------+----------------------+--------------+----------------+---------------
           1 |                    0 | f            |                |              
(1 row)
```
5) Get range clause
```
# select range_split_clause from yb_get_range_split_clause((select oid from pg_class WHERE relname='test'));

 range_split_clause 
--------------------
 
(1 row)
```
6) Keep `ysqlsh` session active, do not close ysql shell.
7) Flush tablet
> ./bin/yb-ts-cli flush_tablet 3506e4b42b2e41c9a7bd2fc51554b9b5

8) Split tablet
> ./bin/yb-admin split_tablet -master_addresses localhost:7100 3506e4b42b2e41c9a7bd2fc51554b9b5

9) Make sure there are 2 tablets:
```
./bin/yb-admin -master_addresses localhost:7100 list_tablets ysql.yugabyte test

Tablet-UUID                      	Range                                                    	Leader-IP       	Leader-UUID
edb5ef98b9f84850860ca5a05a2ff633 	partition_key_start: "" partition_key_end: "H\200\000\0001!" 	127.0.0.1:9100  	4c72286173c248e6af1e37681480677b
cc48baea186d4380b53433af8548cfe7 	partition_key_start: "H\200\000\0001!" partition_key_end: "" 	127.0.0.1:9100  	4c72286173c248e6af1e37681480677b
```
10) Execute simple command to update table's partitioning at pggate side:
```
# select count(*) from test;

 count 
-------
   100
(1 row)
```
11) Get range clause, it should reflect new table partitioning
```
# select range_split_clause from yb_get_range_split_clause((select oid from pg_class WHERE relname='test'));

   range_split_clause   
------------------------
 SPLIT AT VALUES ((49))
(1 row)
```
12) Get table properties again
```
# select * from yb_table_properties((select oid from pg_class WHERE relname='test'));

 num_tablets | num_hash_key_columns | is_colocated | tablegroup_oid | colocation_id 
-------------+----------------------+--------------+----------------+---------------
           1 |                    0 | f            |                |              
(1 row)
```

It should return `2` in `num_tablets` column. The same behaviour is observed for HASH partitioning.

The issue happens because `YbTableProperties` got [cached](https://github.com/yugabyte/yugabyte-db/blob/15387b6613a2aae0b2799bfea22c315638b31432/src/postgres/src/backend/utils/misc/pg_yb_utils.c#L1848) after first access.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5894]: https://yugabyte.atlassian.net/browse/DB-5894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment]
`yb_table_properties` is cached as part of relcache entries and would only be invalidated on cache refresh. Since pg backend is unaware of table splitting, we end up with stale data.

```
typedef struct YbTablePropertiesData {
  uint64_t num_tablets;
  uint64_t num_hash_key_columns;
  bool is_colocated; /* via database or tablegroup, but not for system tables */
  YBCPgOid tablegroup_oid; /* InvalidOid if none */
  YBCPgOid colocation_id; /* 0 if not colocated */
  size_t num_range_key_columns;
} YbTablePropertiesData;
```

To fix this, in general, we would need to invalidate relcache after splitting - i.e. bump catalog version from docdb side.
Currently, `num_tablets` is the only property that can be changed once created. So, for a more targeted fix, we could query master specifically for the `yb_table_properties()`  function.

Note the other place where we use cached `num_tablets` is add/drop PK (to preserve # of tablets) - but it’s probably unlikely to hit this issue given the use case (ORM, setting up initial schema).

**Comment by myang2021** [comment]
In fact without step 10, `yb_get_range_split_clause` also returns stale cached value. So even if we make `yb_table_properties` behaves like `yb_get_range_split_clause`, we have not solved the stale cache problem even for both of them. If we change the semantics of both to mean the latest metadata, then both of them should be modified/rewrite to issue a `client->GetTablePartitionList` to get the latest metadata from master, then derive whatever attribute the function is to return.

**Comment by arybochkin** [comment]
> In fact without step 10, yb_get_range_split_clause also returns stale cached value.
yes, but this is expected with current implementation.

**Comment by arybochkin** [comment]
> then it will be accepted as a valid fix that is expected with the current implementation?

I'm not sure what fix is considered valid, I guess you need to converge on this with the team, cc @tverona1 @d-uspenskiy @deeps1991 

> I assume it must be relevant to test but just want to confirm.

It must be a call for the relevant table, I confirm.
