### ISSUE TITLE
[DocDB] PITR + Packed : Incorrect merge logic for sys catalog restore

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#16507]
Jira Link: [DB-5907](https://yugabyte.atlassian.net/browse/DB-5907)
### Description

Consider the following scenario with packed columns enabled:

For illustration, consider a ysql system table table `t` with three columns. This is hypothetical but serves to illustrate the point that any ysql system table is prone to this:

```
c1 -> INT PARTITION KEY
c2 -> INT NOT PARTITION KEY
c3 -> INT NOT PARTITION KEY
```

1. Say I insert (c1 = 1, c2 = 2, c3 = 3) into t, note down time
2. Now the kv for this row is: 1 => [2, 3]
3. Now I update c2 and c3 for the same row (i.e. c1 = 1) to 4 and 5
4. We'll have two more entries now: [1, column_id(c2)] => 4 and [1, column_id(c3)] => 5
5. Now, perform PITR to time noted in (1) - we'll end up deleting [1, column_id(c2)] => DEL and [1, column_id(c3)] => DEL since they were not present in the restoring state but present in the existing state
6. Because they were written at a more recent time if we do a `select *` for c1 = 1, we will get c2 and c3 as DEL

Because this logic is applicable to all the ysql system tables, they are susceptible to the above scenario. Also, the `sequences_data` table also re-uses the same merge technique so it is also prone.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5907]: https://yugabyte.atlassian.net/browse/DB-5907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sanketkedia** [comment]
Steps to repro:
1. Create a snapshot schedule on a database
2. `CREATE SEQUENCE seq_1 INCREMENT 5 START 10`
3. Note down time t
4. `SELECT nextval('seq_1')`- you will get 10
5. Restore to time t (noted in (3))
6. In a new terminal, run `SELECT nextval('seq_1')` - you will get 0 but should have gotten 10

**Comment by rthallamko3** [comment]
@sanketkedia , Can we close the defect, now that the fix has landed. Were you planning any follow up fixes? We should backport any ysql PackedRows issues to 2.16 branch.
