### ISSUE TITLE
[YSQL] [Unit Test] Continuous test failure in org.yb.pgsql.TestYsqlUpgrade.upgradeIsIdempotent

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#16505]
Jira Link: [DB-5905](https://yugabyte.atlassian.net/browse/DB-5905)
### Description

Unit Test org.yb.pgsql.TestYsqlUpgrade.upgradeIsIdempotent is constantly failing on build: **alma8-clang15-debug-aarch64**. It is failing with AssertionError because of time out:

```
13:21:36.120 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
java.lang.AssertionError: Process exited with code 1, message: <Error running upgrade_ysql: Timed out (yb/rpc/outbound_call.cc:488): Unable to upgrade YSQL cluster: UpgradeYsql RPC (request call id 6) to 127.13.76.225:21708 timed out after 360.000s>
```

Complete Jenkins log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-debug-aarch64/665/testReport/junit/org.yb.pgsql/TestYsqlUpgrade/upgradeIsIdempotent/

Stability Page: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.pgsql.TestYsqlUpgrade&name=upgradeIsIdempotent

It is failing so frequently after this commit: [fc576653](https://github.com/yugabyte/yugabyte-db/commits/fc57665374b7249724790c1d62f05f395ff18b99)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5905]: https://yugabyte.atlassian.net/browse/DB-5905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Seems to also affect TestYsqlUpgrade.migratingIsEquivalentToReinitdb, I'll mute both.

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestYsqlUpgrade&fail_tag=all&name=migratingIsEquivalentToReinitdb&platform=linux

**Comment by vrajat** [comment]
I am going to close this issue as the stability of the tests is rock solid now. FYI: Other than investigating logs regularly, I did not take any action. Also a ASAN error was fixed in upgrade logic which was independent of the stability.
