### ISSUE TITLE
[DocDB] GFlags for experimental/beta features

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#16511]
Jira Link: [DB-5910](https://yugabyte.atlassian.net/browse/DB-5910)
### Description

Some features like tablet splitting, catalog connection caching, etc. are initially done under a gflag, and they are off by default - because they still need soak time (from internal testing). To be safe, we also don't document the gflag when it is still in this dev/beta phase, because we don't want a user (OSS or otherwise) to accidentally turn it on.
However, we have had multiple instances where users have turned on these gflags, but might not have done so if it was somehow made abundantly clear to them that this is still in beta. So can we find a more explicit way to warn the users that this is a beta gflag.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5910]: https://yugabyte.atlassian.net/browse/DB-5910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
The developer will use the new BETA macro to define beta flags

> DEFINE_RUNTIME_BETA_bool(ysql_enable_read_request_caching, false, "Enable read request caching");

Once the feature moves out of beta they can move the flag to the regular macro

> DEFINE_RUNTIME_bool(ysql_enable_read_request_caching, false, "Enable read request caching");

Both would produce only one gFlag `--ysql_enable_read_request_caching`
There will be a new gFlag `--acknowledge_beta_flags_csv` which accepts a comma separated list of gFlag names.
Users would set BETA features via the regular `--flag=value` argument, but they will also have to add the flag name to `acknowledge_beta_flags_csv`. The yb process will crash if any BETA flags have been changed without being added to `acknowledge_beta_flags_csv`.
ex:
> yb-tserver --ysql_enable_read_request_caching --row_packing=“ultra_packed” --acknowledge_beta_flags_csv=“ysql_enable_read_request_caching,row_packing”

Once the feature has moved out of BETA the flag name can be removed from `acknowledge_beta_flags_csv` lazily. The csv allows beta, stable, deprecated and even non existent flags.
YBA will show UI warnings\prompts and update both flags. It will also perform appropriate cleanup of `acknowledge_beta_flags_csv` when the override is removed, or the flag moves out of BETA.
In addition we should improve `yb-tserver --help` to show flag tags\BETA, and improve YBA flags UI to make it more obvious to the user that these flags come with a risk.
BETA flags may not be upgrade-safe. When a customer decides to set these flags, they are accepting the risks and limitations.

**Comment by rkarthik007** [comment]
+1 to this proposal. One comment:

> There will be a new gFlag `--acknowledge_beta_flags_csv` which accepts a comma separated list of gFlag names.
The verb "acknowledge" does not explain the purpose of this list. Perhaps a slightly different naming like `--enable_beta_flags_csv` or `--beta_flags_whitelist_csv`
