### ISSUE TITLE
[DocDB] Flaky test: CreateTableStressTest.TestConcurrentCreateTableAndReloadMetadata 

### ISSUE THREAD

**Issue by yusong-yan** [yugabyte/yugabyte-db#16526]
Jira Link: [DB-5922](https://yugabyte.atlassian.net/browse/DB-5922)
### Description

CreateTableStressTest.TestConcurrentCreateTableAndReloadMetadata is flaky:
[Stability History](https://detective-gcp.dev.yugabyte.com/stability/test?class=CreateTableStressTest&name=TestConcurrentCreateTableAndReloadMetadata)
[Analyze trends](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=CreateTableStressTest&name=TestConcurrentCreateTableAndReloadMetadata)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5922]: https://yugabyte.atlassian.net/browse/DB-5922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
>I0329 15:11:29.556672 2581707 catalog_loaders.cc:342] Loaded metadata for tablet {test-12_tablet_id1} (first table test-12 [id=2e5de9a79f4d4237a674494889612004])

@druzac Interesting, so the master leader changes mid-test? can you confirm that's a load for a new term, eg: term 2?

**Comment by druzac** [comment]
Follow up discussion on slack, but for posterity:
The master leader wasn't changing, there were no term changes. This test repeatedly reloads the sys catalog. When the sys catalog is loaded, all pending tasks are aborted. This includes the async `CreateTabletReplica` tasks. So some tablet replicas were not created. This test uses RF=3, and there's logic when a majority of tablet replicas are created for a tablet peer to elect itself leader and use remote bootstrap to create any missing tablet replicas. This test explicitly disables remote bootstrap, so this logic wasn't firing hence the flakiness.
