### ISSUE TITLE
[YSQL] Queries to information_schema.element_types intermittently errors out

### ISSUE THREAD

**Issue by mislam-yb** [yugabyte/yugabyte-db#16528]
Jira Link: [DB-5924](https://yugabyte.atlassian.net/browse/DB-5924)
### Description

When querying `information_schema.element_types` the query intermittently errors out. When the issue occurs, the cluster will continue to hit this issue for all queries to this table. However, re-building and creating a new cluster can fix the issue. This was observed on debug builds on clusters with replication factors of both 3 and 1.

Minimal reproduction:

```
yugabyte=# select * from information_schema.element_types;
ERROR:  Key 790E1040000000008000300000F13300004F00000070488000000121 is not table tombstone key.
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5924]: https://yugabyte.atlassian.net/browse/DB-5924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Closing it as not repro as I am not able to repro it on my universe. The query takes a long time to run - 700+ seconds on my universe.
