### ISSUE TITLE
[DocDB][xCluster][Tablet Splitting] YCQL - Automatic tablet splitting is not happening at target side

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#16532]
Jira Link: [DB-5928](https://yugabyte.atlassian.net/browse/DB-5928)
### Description

**Version**: `2.17.3.0-b123`

**Steps**:
1. Create 2 universes with below GFLAGs
```
m_flags = {
            "enable_automatic_tablet_splitting": "true",
            "enable_tablet_split_of_xcluster_replicated_tables": "true",
            "tablet_split_high_phase_shard_count_per_node": 576,
            "tablet_split_high_phase_size_threshold_bytes": 102400,  # 100 KB
            "tablet_split_low_phase_size_threshold_bytes": 10240,  # 10 KB
            "tablet_split_low_phase_shard_count_per_node": 96,
        }
t_flags = {
    "enable_automatic_tablet_splitting": "true",
    "yb_num_shards_per_tserver": 1,
     "scheduled_full_compaction_frequency_hours": "12",
     "scheduled_full_compaction_jitter_factor_percentage": "100",
     "scheduled_full_compaction_check_interval_min": "5",
    }
```
2. Create keyspace, tables and indexes at both universes
3. Collect tablets count(initial tablets count)
4. Create xCluster replication from source to target
5. Load data at source(100K)
6. Collect tablets count and validate data at both sides (Replication is happening)
7. Validate increase in tablets count at both sides.

**Actual**: 
1. At step#7 validation is failing as tablets splitting is happening at source and it not happening at target

Ran flush and compact commands manually at target and splitting is happening after running flush and compact cmds

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5928]: https://yugabyte.atlassian.net/browse/DB-5928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@Arjun-yb , Based on Julien's response on the thread, I am assigning this back to you as it looks like a test issue. Can you take a look and let us know if the test fixes unblocks you or not. cc @hulien22

**Comment by Arjun-yb** [comment]
@rthallamko3 I have re-validated the test with required changes and the issue is still persistent, Added details in respective JIRA([DB-5928](https://yugabyte.atlassian.net/browse/DB-5928))

**Comment by rthallamko3** [comment]
@Arjun-yb , Can you check if the issue continues to repro with 200K rows. We were wondering if the batch writes on the xCluster target might not have crossed the thresholds for flush on the target side.

**Comment by bmatican** [comment]
@Arjun-yb @rthallamko3 @hulien22 is this still relevant? was this an automated test that we have signal from?

**Comment by kripasreenivasan** [comment]
@bmatican , yes this is automated- TestYCQLXClusterWithTabletSplitting

**Comment by Arjun-yb** [comment]
Validated with more data and it is working as expected(tablets are splitting at both source and target sides), closing this.
