### ISSUE TITLE
Default database and user is postgres -- enhance to yugabyte

### ISSUE THREAD

**Issue by mrpanda** [yugabyte/yugabyte-db#1654]
Jira Link: [DB-2573](https://yugabyte.atlassian.net/browse/DB-2573)
An enhancement request to make the default database and user account "yugabyte". It is possible that this might cause problems for existing tools that will attempt to access yugabyte as a postgresql system -- and whilst these tools should cater for non-default users and databases, it is possible for legacy purposes to keep the postgres db and user.

Therefore, consider as a first step that 2 initial databases and users are used -- "postgres" for legacy purposes, and "yugabyte" for everything else. Your documentation could reference the "yugabyte" db & user thus reinforcing your unique identity -- and postgres could remain for tool compatibility.

Developers can decide in the future if they wanted to drop their instance of postgres db and user if their testing reveals that they don't require it.

I would only consider implementing this enhancement after you have implemented the CREATE USER and row level security capability. Thanks.

**Comment by rkarthik007** [comment]
Thanks for the clarity in the request @mrpanda, love it!!

**Comment by sushantrmishra** [comment]
closing this issue, as yugabyte as been used as default user and postgres user exist for backward compatibility.
