### ISSUE TITLE
[YugabyteD] [QA] [Improvement] Show EAR status on <./bin/yugabyted status>

### ISSUE THREAD

**Issue by ankit-yb** [yugabyte/yugabyte-db#16541]
Jira Link: [DB-5934](https://yugabyte.atlassian.net/browse/DB-5934)
### Description

Currently, we show Encryption In Transit status on the details but Encryption At Rest could also be a part of that if needed.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5934]: https://yugabyte.atlassian.net/browse/DB-5934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Code fix Landed
