### ISSUE TITLE
[DocDB] The return value of OutboundCall::SetState is not being checked

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#16547]
Jira Link: [DB-5955](https://yugabyte.atlassian.net/browse/DB-5955)
### Description

SetState returns false if the call is already finished. We need to check the return value from each call site as well as mark the function as "must use result".

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5955]: https://yugabyte.atlassian.net/browse/DB-5955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Must have been fixed in another commit
>MUST_USE_RESULT bool SetState(State new_state);
