### ISSUE TITLE
[xCluster] History retention should account for xCluster safe time

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#16551]
Jira Link: [DB-5957](https://yugabyte.atlassian.net/browse/DB-5957)
### Description

We should make sure the history retention is at least xcluster safe time. Safe time may not move due to issues with even a single tablet so until it recovers reads will be as of the stuck xcluster safe time only.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5957]: https://yugabyte.atlassian.net/browse/DB-5957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
https://yugabyte.slack.com/archives/C01CR9897A5/p1679106232167849

**Comment by mdbridge** [comment]
this is needed for #15547

**Comment by mdbridge** [comment]
This issue was identified as important as part of the investigation done in [xCluster] Handle any issues due to replication repeating changes #15547
