### ISSUE TITLE
[YSQL] Do block (a.k.a. anonymous block) not supported

### ISSUE THREAD

**Issue by bllewell** [YugaByte/yugabyte-db#1656]
Using v1.2.11. Try this simple test of the postgreSQL so-called `DO` block (in plainEnglish, anonymous block):
```
do $$
begin
  raise notice 'Hello';
end
$$;
````
It works in vanilla PostgreSQL (of course). In YugaByte DB it causes this error:
```
ERROR:  DO not supported yet
...
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
```
This is critical functionality for users who want, for example, to implement a business function that requires more than one `insert`, `update`, or `delete` as an atomic unit in a single server call but don’t (yet, at least) want to implement a stored procedure.

**Comment by lukaseder** [comment]
This would be a very useful feature to have in third party libraries, to create compound statements, e.g. to emulate missing support for `IF [ NOT ] EXISTS` clauses of various DDL statements. In the meantime, even `DO` can be emulated as follows using a statement batch like this that can be sent to the server using a single JDBC statement:

```sql
create procedure p() as $$
begin
  -- procedural content
end;
$$ language plpgsql;
call p();
drop procedure p();
```
