### ISSUE TITLE
[YCQL] unit test TestCreateTable.testCreateTableNumTablets is not pass.

### ISSUE THREAD

**Issue by WangPingGang** [yugabyte/yugabyte-db#16561]
Jira Link: [DB-5966](https://yugabyte.atlassian.net/browse/DB-5966)
### Description

When i execute 
`./bi_build.sh release --clang12 --java-test 'org.bi.cql.TestCreateTable#testCreateTableNumTablets'`
the test is passed.
When i execute
`./bi_build.sh release --clang12 --java-test 'org.bi.cql.TestCreateTable'`
the testCreateTableNumTablets is not passed.
It seems failed in `assertFalse(miniCluster.getClient().tableExists("system", "transactions"));`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5966]: https://yugabyte.atlassian.net/browse/DB-5966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @WangPingGang 

Can you upload the full text log?
What version/commit are you using of the repo?

**Comment by dr0pdb** [comment]
Reopening since we do need to fix this test in master.

**Comment by dr0pdb** [comment]
@WangPingGang Are you interested in fixing the issue as well?

**Comment by dr0pdb** [comment]
@WangPingGang Yeah, something similar should help.

```
restartClusterWithTSFlags(new HashMap<String,String>());
```
