### ISSUE TITLE
[DocDB] TEST_docdb_log_write_batches fails with ysql_enable_packed_row=true

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16665]
Jira Link: [DB-6045](https://yugabyte.atlassian.net/browse/DB-6045)
### Description

When running with --tserver_flags TEST_docdb_log_write_batches=true, it fails with
`schema_packing.cc:200] Check failed: _s.ok() Bad status: Not found (yb/docdb/schema_packing.cc:197): Schema packing not found: 0, available_versions: [] 
`
This doesn't happen if ysql_enable_packed_row=false.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6045]: https://yugabyte.atlassian.net/browse/DB-6045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Got the same message on sst_dump:

```sql
CREATE TABLE t (i int);
INSERT INTO t VALUES (1);
```

```sh
build/latest/bin/yb-admin flush_table ysql.yugabyte t
build/latest/bin/yb-admin list_tablets ysql.yugabyte t | tail -n +2 | awk '{print $1}' | while read -r line; do build/latest/bin/sst_dump --command=scan --output_format=decoded_regulardb --file=~/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-$(build/latest/bin/yb-admin list_tables include_table_id | grep yugabyte.t\  | awk '{print$2}')/tablet-$line/; done
```

```
from [] to []
from [] to []
from [] to []
Process build/latest/cluster_data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-000033f100003000800000000000400a/tablet-89d5f551030a4f079fc3777b5e7bfdb0//000010.sst
Sst file format: block-based
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0510 18:15:53.555102 2819367 schema_packing.cc:219] Check failed: _s.ok() Bad status: Not found (yb/dockv/schema_packing.cc:214): Schema packing not found: 0, available_versions: []
*** Check failure stack trace: ***
```

This was alma8, fastdebug, gcc11, recent master commit 5a0324ff33a17b530f63b5c1d67cfe64684df5e2.

**Comment by mdbridge** [comment]
Note: need to remove workarounds in code base when this is fixed; see src/yb/integration-tests/xcluster_ysql-test.cc

**Comment by mdbridge** [comment]
https://phorge.dev.yugabyte.com/D26682 will remove the workaround among other things

**Comment by rthallamko3** [comment]
Reactivating for 2.18 and 2.16 backports, if possible.

**Comment by mdbridge** [comment]
backported to 2.18.2

**Comment by rthallamko3** [comment]
@mdbridge , Can we backport to 2.16 branch as well?

**Comment by mdbridge** [comment]
I have been trying to do that.  Ran into some issues that require more debugging then got pulled into the high priority Amex investigation.  Hope to get back to this next week.

**Comment by rthallamko3** [comment]
Backport to 2.16 is risky due to additional dependencies. We decided to use the sst_dump tool from 2.18 branch if needed

**Comment by mdbridge** [comment]
for the record, a partially completed backport for 2.16 was https://phorge.dev.yugabyte.com/D28519
