### ISSUE TITLE
[DocDB] All RPC threads stuck in YBMetaDataCache::GetTable

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16697]
Jira Link: [DB-6073](https://yugabyte.atlassian.net/browse/DB-6073)
### Description

In one of our 2.12 customers, observed all RPC threads being stuck in this stack, during a rather bursty workload:
```
yb::tserver::TabletServiceImpl::Write();
yb::tablet::TabletPeer::WriteAsync();
yb::tablet::Tablet::AcquireLocksAndPerformDocOperations();
yb::tablet::WriteQuery::Execute();yb::tablet::WriteQuery::DoExecute();
yb::tablet::WriteQuery::CompleteExecute();
yb::tablet::WriteQuery::ExecuteDone();yb::tablet::WriteQuery::CqlExecuteDone();
yb::tablet::WriteQuery::UpdateQLIndexes();
yb::client::YBMetaDataCache::GetTable();
yb::client::YBClient::OpenTable();
yb::client::YBClient::Data::GetTableSchema();
yb::Synchronizer::WaitUntil();
std::condition_variable::wait();__pthread_cond_wait;(unknown)
```

Based on code inspection, this points to the following code
```
      // TODO create async version of GetTable.
      // It is ok to have sync call here, because we use cache and it should not take too long.
      auto status = metadata_cache->GetTable(
          index_info->table_id(), &index_table, &cache_used_ignored);
```

Which digging further, shows that, in theory, we do have a per-table cache, but in practice, the very first time we try to fill that cache, we do not have a barrier, to ensure 1 and only 1 thread goes out to fetch the metadata, but instead, all threads could end up in the `client_->OpenTable` call below:
```
Status YBMetaDataCache::GetTable(const TableId& table_id,
                                 std::shared_ptr<YBTable>* table,
                                 bool* cache_used) {
  {
    std::lock_guard<std::mutex> lock(cached_tables_mutex_);
    auto itr = cached_tables_by_id_.find(table_id);
    if (itr != cached_tables_by_id_.end()) {
      *table = itr->second;
      *cache_used = true;
      return Status::OK();
    }
  }

  RETURN_NOT_OK(client_->OpenTable(table_id, table));
  {
    std::lock_guard<std::mutex> lock(cached_tables_mutex_);
    cached_tables_by_name_[(*table)->name()] = *table;
    cached_tables_by_id_[table_id] = *table;
  }
  *cache_used = false;
  return Status::OK();
}
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6073]: https://yugabyte.atlassian.net/browse/DB-6073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dr0pdb** [comment]
Filed #17038 for the long term solution i.e. the async callback queue approach
