### ISSUE TITLE
Jepsen failure scenarios - implement network failures

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#167]
This covers a class of network failures such as:
- Flaky network where some packets get dropped
- Slow network
- Duplication of some network packets

**Comment by ttyusupov** [comment]
Comment from https://github.com/jepsen-io: 
> Almost every system we test uses TCP, which tends to turn slow/duplicate/dropped packets into plain old stream latency. None of the tests where I've experimented with packet loss or reorderings have found anything.

https://github.com/jepsen-io/jepsen/issues/254
