### ISSUE TITLE
[Docs] ysqlsh - YSQL shell for YugabyteDB

### ISSUE THREAD

**Issue by rangasayeelc-yb** [yugabyte/yugabyte-db#16701]
### Description

Couldn’t open the YSQL shell; saw the error shown in screenshot.

The fix was to set hostname to YB-Master Server IP (172.17.0.2 in my case) instead of localhost (127.0.0.1). Please update documentation to reflect the same

![Screenshot 2023-03-30 at 6 58 34 PM](https://user-images.githubusercontent.com/10994207/229985929-124dade5-539b-4c4c-9622-fd7f258b46f9.png)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
@rangasayeelc-yb on which page? can you paste the URL?

**Comment by ddorian** [comment]
@rangasayeelc-yb please reopen the issue with more details so I can make the fix.
