### ISSUE TITLE
Timeout and replication factor to 1 from 3 in 1.2.11

### ISSUE THREAD

**Issue by dodilp** [YugaByte/yugabyte-db#1671]
Hi, I'm using 1.2.11.

Issue : Facing a timeout error when creating a 3 cluster configuration using yugabyte-1.2.11

Operating System- 7.6
Kernel- 3.10.0-957
Memory- 8GB
Yugabyte Version- 1.2.11

Steps to reproduce- Simple run ./bin/yb-ctl --rf3 create.

I have tried to create the configuration multiple times and this timeout issue keeps happening. Attaching the log file. Another thing I saw is that after the timeout. ./bin/yb-ctl status shows replication factor as 1.
[yb-ctl_create_1-2-11-latest.txt](https://github.com/YugaByte/yugabyte-db/files/3347884/yb-ctl_create_1-2-11-latest.txt)

**Comment by kmuthukk** [comment]
@dodilp - Are you possibly hitting the issue that the cleanup of previous cluster was not done correctly?

See issue here, and suggested temporary workaround: https://github.com/YugaByte/yugabyte-db/issues/1643

**Comment by dodilp** [comment]
Ok, thank you @kmuthukk . Closing this issue for now.
