### ISSUE TITLE
[DocDB] Use Tablespace Config during GetTabletLocations

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#16716]
Jira Link: [DB-6087](https://yugabyte.atlassian.net/browse/DB-6087)
### Description

On the catalog manager's GetTabletLocations path, we WARN if the number of replicas doesn’t match the cluster config RF. This becomes an issue when we have tablespaces, as we always do this comparison using the global config. So we can end up logging unnecessarily when the tablespace RF doesn't match the cluster config RF.

Fix this by using the tablespace RF on the GetTabletLocations when a table is part of a tablespace.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6087]: https://yugabyte.atlassian.net/browse/DB-6087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by omkaark** [comment]
Can you please share some insight on how to check if a tablespace is part of a table?

**Comment by lucaswangyb** [comment]
Resolved in this commit `b639dc19d1fadf4746ea7b32ef9e663ed92ca977`
