### ISSUE TITLE
Docs for getting started with Gorm

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#1673]
## Goal

Document how to get started writing a Gorm app (Golang based ORM).

## Details

* Here is the example repo for a simple getting started app: https://github.com/YugaByte/orm-examples
* Here is the build instructions for Go: https://github.com/YugaByte/orm-examples/tree/master/golang/gorm

The explanation should use the above example to explain how an end user can get started building a Gorm app on top of YugaByte DB. The following high level topics should be covered (not an exhaustive list):

* Directory structure
* Basic code fragments with explanations
* Building and running
* Customizing the deployment

**Comment by stevebang** [comment]
I think this is done -- close?

See https://docs.yugabyte.com/latest/quick-start/build-apps/go/ysql-gorm/

**Comment by rkarthik007** [comment]
Yes, this can be closed.
