### ISSUE TITLE
Docs for getting started with Diesel/Rust

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#1674]
## Goal

Document how to get started writing a Diesel app (Rust based ORM).

## Details

* Here is the example repo for a simple getting started app: https://github.com/YugaByte/orm-examples
* Here are the build instructions: https://github.com/YugaByte/orm-examples/tree/master/rust/diesel

The explanation should use the above example to explain how an end user can get started building a Diesel app on top of YugaByte DB. The following high level topics should be covered (not an exhaustive list):

* Directory structure
* Basic code fragments with explanations
* Building and running
* Customizing the deployment

**Comment by polarweasel** [comment]
https://docs.yugabyte.com/preview/drivers-orms/rust/diesel/
