### ISSUE TITLE
[xCluster] Rename yb-admin get_estimated_data_loss

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#16756]
Jira Link: [DB-6116](https://yugabyte.atlassian.net/browse/DB-6116)
### Description

The current yb-admin `get_estimated_data_loss`  is reporting the skew in xClusterSafetime between the laggiest tablet and the most caught up tablet. As a result of this, it is quite possible that there is no skew in xClusterSafetime, but there is genuine replication lag between source and target. In such cases, the API return 0 as the estimated_data_loss as it doesn't account for replication_lag between source and target.

As such, this API should be renamed to `get_xcluster_safe_time_skew` to match the metric. Additionally, we can report the xcluster_safe_time_lag similar to the metric which reports the (current_time - xcluster_safe_time_lag) similar to the consumer_safe_time_lag metric.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6116]: https://yugabyte.atlassian.net/browse/DB-6116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hulien22** [comment]
closed in [cb9a520](https://github.com/yugabyte/yugabyte-db/commit/cb9a520f3016469a174405b095f55916a9799ace)

functionality has been moved to ybadmin `get_xcluster_safe_time`
