### ISSUE TITLE
[DocDB] Update tablet metrics at the end of the RPC

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16782]
Jira Link: [DB-6136](https://yugabyte.atlassian.net/browse/DB-6136)

[DB-6136]: https://yugabyte.atlassian.net/browse/DB-6136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
Added with d72b9a0
