### ISSUE TITLE
[docs] Getting started with docker-based YugaByte DB on Windows

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#1679]
## Goal

Document how to get started with YugaByte DB on windows using Docker.

## Details

The current documentation assumes docker works on windows, and thus YugaByte DB setup would succeed. This should be verified.

There have also been issues such as the following that might need to be addressed:
https://stackoverflow.com/questions/54282077/how-to-install-yugabyte-on-docker-for-windows

**Comment by Cloudmersive** [comment]
Any update on this?

**Comment by lizayugabyte** [comment]
@polarweasel Really old ticket. Not sure if it's still relevant.
