### ISSUE TITLE
[YSQL] Warn user if setting/ using READ COMMITTED in syntax without setting yb_enable_read_committed_isolation

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#16799]
Jira Link: [DB-6148](https://yugabyte.atlassian.net/browse/DB-6148)
### Description

Self-explanatory

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6148]: https://yugabyte.atlassian.net/browse/DB-6148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
We should also crash if yb_enable_read_committed_isolation=true and enable_pg_savepoints=false

**Comment by pkj415** [comment]
"We should also crash if yb_enable_read_committed_isolation=true and enable_pg_savepoints=false"

Created #20918 to track this
