### ISSUE TITLE
Jepsen failure scenarios - implement clock skew

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#168]
This covers a range of issues related to the clock synchronization across different machines, with a range of skew values:
- small skew: ~ 100ms
- medium skew: ~ 250ms
- large skews: ~ 500ms
- xlarge skews: ~ 1 secs

**Comment by ttyusupov** [comment]
Commit: https://github.com/YugaByte/jepsen/commit/6c8a38ffdbcd64a441b66c8b69a5aee5ad3321e7
