### ISSUE TITLE
[DocDB] flaky test: LockfreeTest.QueuePerformance

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16813]
Jira Link: [DB-6160](https://yugabyte.atlassian.net/browse/DB-6160)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=LockfreeTest&fail_tag=all&name=QueuePerformance&platform=linux

Seems to trace to a78bf1afb355cef85321519375bddcf9c93dacb8

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6160]: https://yugabyte.atlassian.net/browse/DB-6160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@SrivastavaAnubhav , Should we disable the performance test in fastdebug mode as thats the only build type its failing in? Not sure if it is worthwhile debugging performance tests in fastdebug builds.
<img width="2042" alt="Screenshot 2023-05-02 at 5 12 21 PM" src="https://user-images.githubusercontent.com/17170123/235811085-030d53db-742a-4bc2-9562-ff941048d92c.png">

**Comment by SrivastavaAnubhav** [comment]
I plan on taking a look at this test. It's failing because the new tcmalloc is running on fastdebug builds.
