### ISSUE TITLE
[DocDB] Expose rocksdb metric of data size on disk across active rocksdb and all snapshot dirs

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16854]
Jira Link: [DB-6200](https://yugabyte.atlassian.net/browse/DB-6200)
### Description

We need a version of rocksdb_current_version_sst_files_size that includes size across all snapshots as well, but not double counting hard linked data.
cc @jmeehan16 @ttyusupov @sanketkedia 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6200]: https://yugabyte.atlassian.net/browse/DB-6200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
This ended up getting done as part of https://github.com/yugabyte/yugabyte-db/issues/22909.
