### ISSUE TITLE
[YSQL][Colocation][Read committed isolation]: Getting serialization error while running contentious transactions in read committed isolation level on colocated tables

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#16866]
Jira Link: [DB-6209](https://yugabyte.atlassian.net/browse/DB-6209)
### Description

        1. Create a universe with RPC, YSQL Packed row and Tablet splitting and read committed
           isolation level enabled
        2. Create a colocated database, create 2 colocated and a non colocated table
        3. Create Snapshot schedule
        4. Insert 10 rows to all tables
        5. Note down time(1)
        6. Create all types of indexes on the table
        7. Create Materialized views on both the table
        8. Create unique index on both the Materialized views
        9. Load 100 rows in colocated tables and 40k rows in non colocated table
           and note down the time(2), validate tablets count
        10. Delete few rows from all the tables and note down the time(3)
        11. Update data in all the tables
        12. Run contentious transactions on the 1st colocated table and non colocated table
        13. Add 3 nodes to the universe and load more data in both the tables
        14. Restore to time(3) with new node
        15. Alter tables, Flush and compact tables
        16. Restore to time(2) with new node
        17. Insert data in non-colocated table and validate tablets count
        18. Restore to time(1)
        19. Run contentious transactions on the colocated table
        
The test fails due to serialization error.
Logs: https://drive.google.com/file/d/1Llo5F_50LlsmbrqDx_8SznNFg2FyeSO3/view?usp=sharing

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6209]: https://yugabyte.atlassian.net/browse/DB-6209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Karvy-yb** [comment]
Strangely enough, I didn’t get any issues while running the test without non-colocated table.
Post which I created non-colocated table but didn’t do any operations over it -> No error
Then I created index on non-colocated table and I see SE while attempting contentious transactions on colocated table (original issue)

FYI, wait queues is disabled

**Comment by Karvy-yb** [comment]
The test is passing on 2.19.2.0-b14 but failing with same issue on 2.19.1.0-b397.
Jenkins failure on 2.19.1: https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/7958/console

cc: @sushantrmishra @pkj415

**Comment by robertsami** [comment]
```
1. Create universe 
2. Create colocated database
3. Create 2 colocated tables: colocated_table, colocated_table_2 
4. Create a non-colocated table non_colocated_table
5. Create Snapshot schedule
6. Expand universe : Add 3 nodes to the universe
7. Execute flush and compact tables
8. Attempting Contentious transactions on colocated_table_2 table : >>> Integration Test Failed <<< 
Heartbeat: Transaction edcf8bd7-7511-4dab-9c5c-fb48c92daa9c expired or aborted by a conflict: 40001
```
https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/8071/console

**Comment by Karvy-yb** [comment]
@arybochkin 
We run yb_admin commands to flush and compact both the colocated tables. Eg:
`...flush_table ysql.db table`
`...compact_table ysql.db table`

**Comment by robertsami** [comment]
does not reproduce with the following flags in the first run:
```
{"name": "wait_queue_poll_interval_ms", "value": "5"},
    {"name": "ysql_pg_conf_csv", "value": "yb_lock_pk_single_rpc=true"}
```
next steps:
1. re-run 4 times and see if it still does not reproduce
2. re-run without wait_queue_poll_interval change
3. re-run without yb_lock_pk_single_rpc change

**Comment by robertsami** [comment]
we are sending read RPCs with the following contents:
```
I0922 15:21:23.728442 48341 read_query.cc:214] Received Read RPC: tablet_id: "487c02239f4a4ba2943698c2088adb4b"
include_trace: false
consistency_level: STRONG
transaction {
  transaction_id: "\341\277Q!l\021@\037\263\234\255\342\350\270\3767"
  isolation: SNAPSHOT_ISOLATION
  status_tablet: "25649648e47c44619ffa80c5e787b054"
  priority: 18446744072590538369
  start_hybrid_time: 6944342358937178112
  locality: GLOBAL
}
propagated_hybrid_time: 6944342358950834176
read_time {
  read_ht: 6944342358937178112
  DEPRECATED_max_of_read_time_and_local_limit_ht: 6944342358937178112
  global_limit_ht: 6944342360985182208
  in_txn_limit_ht: 6944342358935982080
  local_limit_ht: 6944342358937178112
}
pgsql_batch {
  client: YQL_CLIENT_PGSQL
  stmt_id: 25200717652224
  schema_version: 0
  column_refs {
  }
  is_aggregate: false
  limit: 1
  return_paging_state: true
  table_id: "0000400000003000800000000000402c"
  ybctid_column_value {
    value {
      binary_value: "S1\000\000!"
    }
  }
  row_mark_type: ROW_MARK_EXCLUSIVE
  wait_policy: WAIT_ERROR
  size_limit: 0
}
proxy_uuid: "021ac91611f7486fb62c8f31a515baf3"
DEPRECATED_may_have_metadata: true
rejection_score: 0
batch_idx: 0
I0922 15:21:23.728529 48341 write_query.cc:490] e1bf5121-6c11-401f-b39c-ade2e8b8fe37: effective conflict_management_policy=2
I0922 15:21:23.728538 48341 conflict_resolution.cc:1298] ResolveTransactionConflicts: conflict_management_policy=2, resolution_ht: { physical: 1695396083728538 }, read_time: { physical: 1695396083724897 }
```

so we end up using WAIT_ERROR, even though wait queues are enabled, and we abort a transaction unexpectedly

it is probably an error for the query layer to be sending WAIT_ERROR in these read RPCs

**Comment by pkj415** [comment]
After be6909b774, we can set `log_min_messages=debug5` and view log lines in Pg that indicate the final wait policy chosen by Pg. This might help debug the issue.

**Comment by robertsami** [comment]
it looks like one of the pg processes is behaving as if wait queues are not enabled:
```
I1023 21:52:21.407567 53966 pg_client.cc:165] Session id 17: Session id acquired. Postgres backend pid: 53966
2023-10-23 21:52:21.537 UTC [53966] LOG:  YBSetRowLockPolicy() called - case 1
2023-10-23 21:52:21.537 UTC [53966] STATEMENT:  SELECT val FROM colocated_table_2 WHERE id='1' FOR UPDATE;
2023-10-23 21:52:21.537 UTC [53966] LOG:  YBSetRowLockPolicy() pg_wait_policy=0
2023-10-23 21:52:21.537 UTC [53966] STATEMENT:  SELECT val FROM colocated_table_2 WHERE id='1' FOR UPDATE;
2023-10-23 21:52:21.537 UTC [53966] LOG:  Falling back to LockWaitError since wait-queues are not enabled
2023-10-23 21:52:21.537 UTC [53966] STATEMENT:  SELECT val FROM colocated_table_2 WHERE id='1' FOR UPDATE;
2023-10-23 21:52:21.537 UTC [53966] LOG:  docdb_wait_policy=2 pg_wait_policy=0
2023-10-23 21:52:21.537 UTC [53966] STATEMENT:  SELECT val FROM colocated_table_2 WHERE id='1' FOR UPDATE;
I1023 21:52:23.416672 53977 mem_tracker.cc:254] Creating root MemTracker with garbage collection threshold 
```

this causes the RPC to be sent with `WAIT_ERROR`, and therefore we see a conflict when we expect the statement to wait

**Comment by robertsami** [comment]
This was failing due to a bug in the YBA API used by the test, which caused newly added nodes to not have enable_wait_queues=true, so PG ends up sending RPCs with WAIT_ERROR

@Karvy-yb has fixed the test and verified that it now works
