### ISSUE TITLE
[Jepsen Testing] Multi-key ACID

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#169]
## Scenario

There is one table in the system. The table’s primary key has one hash column. There is one value column in the table. Each operation writes two key-values, both with the same value. Note that these represent distributed transactions. Each operation is logged along with its results. The results can be one of the following:
- OK : the operation was successful
- FAIL: the operation failed
- UNKNOWN: we did not get a response (because there may have been a failure)

## Validation

At the end of the run a checker validates that the set of keys written respects snapshot isolation with respect to the operations performed.

**Comment by ttyusupov** [comment]
Commit: https://github.com/YugaByte/jepsen/commit/28e1205666b705449df976b594627cfc747753cf
