### ISSUE TITLE
[DocDB][xCluster][Atomicity] Data is duplicated after adding table(with data) to existing replication

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#16908]
Jira Link: [DB-6237](https://yugabyte.atlassian.net/browse/DB-6237)
### Description

**Version**: `2.17.3.0-b145`

**Steps**:
Same steps as in the 2.17.3 run-book(`Add table with data to the replication` section)

1. Create database and tables at both sides
`create table account_balance(id int, name text, salary int);`
2. Setup replication (A-to-B) using YBA UI
3. Change target role to STANDBY 
4. Get get_xcluster_safe_time at target
5. Create snapshot schedule at both sides
6. Load data and observe the replication -works fine
7. Create table at source and run some transactions 
`create table account_balance1(id int, name text, salary int);`
8. Stop any transactions on the Primary-A (which has table with data) (stopped transactions for all tables)
9. Get table ID of account_balance1 to be added
10. Use the bootstrap_cdc_producer API to bootstrap the replication stream on Primary
11. Resume transactions on Primary
12. Copy the source table(account_balance1) data to the target table.
	Ran `ysql_dump` at source - `postgres/bin/ysql_dump -h <source_host_ip> -d demo1 -t account_balance1 -f sql_data.sql
	and at target - `postgres/bin/ysqlsh -h <target_host_ip> -d demo1 < sql_data.sql`
```
demo1=# select * from account_balance1 ;
 id |  name   | salary
----+---------+---------
  1 | CCC    |  985500
  7 | CCC    |  985500
 12 | AAA | 1029000
  5 | BBB  |  985500
  2 | BBB  |  985500
  4 | CCC    |  985500
  9 | AAA | 1029000
 11 | BBB  |  985500
  8 | BBB  |  985500
  3 | AAA | 1029000
 10 | CCC    |  985500
  6 | AAA | 1029000
(12 rows)
```
13. Add the table to the existing replication on the Standby. Use the bootstrap Ids
14. Get current time
15. Wait for xCluster safe time to advance beyond time from previous step(14)
16. Validate data at target

```
demo1=# select * from account_balance1;
 id |  name   | salary
----+---------+---------
  7 | CCC    |  649500
 10 | CCC    |  649500
    |         | -179000
  4 | CCC    |  649500
    |         | -179000
  9 | AAA | 1701000
  8 | BBB  |  649500
  1 | CCC    |  650500
    |         | 3358000
  3 | AAA | 1701000
 12 | AAA | 1701000
    |         | -179000
    |         | -179000
  2 | BBB  |  649500
    |         | -179000
    |         | 3358000
    |         | -179000
  5 | BBB  |  649500
6 | AAA |  1701000
11 | BBB  | 649500
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6237]: https://yugabyte.atlassian.net/browse/DB-6237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Setps 11 and 12 need to be swapped

**Comment by Arjun-yb** [comment]
@hari90 I tried with updated steps and it is still repro-able
