### ISSUE TITLE
[DocDB] Ensure locks from aborted subtransactions are excluded from pg_locks

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#16910]
Jira Link: [DB-6239](https://yugabyte.atlassian.net/browse/DB-6239)
### Description

We can ensure that transaction_coordinator response which indicates which tablets should be queried in GetLockStatus includes aborted subtransaction info as well

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6239]: https://yugabyte.atlassian.net/browse/DB-6239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Should get resolved once fix for https://github.com/yugabyte/yugabyte-db/issues/16914 lands.

**Comment by robertsami** [comment]
main support was added in 320cffba64ac0fe642f93bc7691341215e7626a1
