### ISSUE TITLE
Initdb: Invalid locale name "en_US.UTF-8" in release build

### ISSUE THREAD

**Issue by srhickma** [YugaByte/yugabyte-db#1692]
When building master (@`5d35d6a55dcea4960f00e7fa0a16df039cd3e70a`) on centos using `bin/remote_release.py` and attempting to start a cluster using this build (again on centos), I am seeing the following error from initdb:
```
initdb: invalid locale name "en_US.UTF-8"
```
**Reproduction Steps:**
Locally:
```
$ bin/remote_release.py
```
On the remote server:
```
$ tar xvzf [location of tar.gz from remote build]
$ cd yugabyte-1.*
$ bin/configure
$ bin/yb-ctl destroy && bin/yb-ctl create
```

**Comment by mbautin** [comment]
@srhickma : are you sure that commit 5d35d6a55dcea4960f00e7fa0a16df039cd3e70a is correct?

**Comment by mbautin** [comment]
OK, I can see it is correct because it is clickable above.

**Comment by srhickma** [comment]
This issue was not seen in official release `1.2.11.0`, only in builds of the latest master.

**Comment by srhickma** [comment]
It looks like this was an issue related specifically to my dev server. Building a release using the distributed GCP infrastructure worked without issue.

**Comment by srhickma** [comment]
Closing for now, since this issue shouldn't affect any normal releases.
