### ISSUE TITLE
[xCluster] Switch transactional xCluster tests to FLAGS_xcluster_consistent_wal

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#16943]
Jira Link: [DB-6279](https://yugabyte.atlassian.net/browse/DB-6279)
### Description

Make tests run with FLAGS_xcluster_consistent_wal instead of FLAGS_enable_replicate_transaction_status_table

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6279]: https://yugabyte.atlassian.net/browse/DB-6279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mdbridge** [comment]
this is blocking https://github.com/yugabyte/yugabyte-db/issues/16750
