### ISSUE TITLE
[YSQL][Unit Test] ColocationConcurrencyTest.CreateAndTruncateOnSeparateTables is flaky on master

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#16956]
Jira Link: [DB-6285](https://yugabyte.atlassian.net/browse/DB-6285)
### Description

Unit test **ColocationConcurrencyTest.CreateAndTruncateOnSeparateTables**  has been flaky on master after this [commit](https://github.com/yugabyte/yugabyte-db/commits/a1729c352896e919f462c614770da443b9982c0a), it fails with below error

> Value of: __extension__ ({ auto&& __result = (conn1.HasIndexScan(query)); static_assert(yb::IsNonConstResultRvalue<decltype(__result)>::value, "only non-const Result<T> rvalue reference is allowed"); do { auto&& _assert_status = (__result); if (_assert_status.ok()) { ::testing::internal::AssertHelper(::testing::TestPartResult::kSuccess, "../../src/yb/yql/pgwrapper/colocation-test.cc", 318, "Succeeded") = ::testing::Message(); } else { return ::testing::internal::AssertHelper(::testing::TestPartResult::kFatalFailure, "../../src/yb/yql/pgwrapper/colocation-test.cc", 318, "Failed") = ::testing::Message() << "Bad status: " << StatusToString(_assert_status); } } while (0); WrapMove(std::move(__result)); })   Actual: false Expected: true

Stability trend:
[https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=ColocationConcurrencyTest&fail_tag=all&name=CreateAndTruncateOnSeparateTables&platform=linux](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=ColocationConcurrencyTest&fail_tag=all&name=CreateAndTruncateOnSeparateTables&platform=linux)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6285]: https://yugabyte.atlassian.net/browse/DB-6285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
According to the logs, this looks like a test framework issue.  The test should not assume the index will be immediately public because of heartbeat delay (part 1 of issue #13369).  The most plausible explanation for why it became flaky is that the CREATE INDEX got faster by that commit.

I believe some tests already do `WaitFor` or similar on the HasIndexScan.  Also, I notice this bad assumption in other tests in that file, so they should also be fixed.
