### ISSUE TITLE
[Docs] Document yb_locks view 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#16961]
### Description

yb_locks view is equivalent of [pg_locks](https://www.postgresql.org/docs/current/view-pg-locks.html) from PostgreSQL. It will be used to find the issues related to waiting due to conflict.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
Looks to be resolved by #21231
