### ISSUE TITLE
[YCQL] GetColocatedTabletSchema rpc does not return colocated tables for new 'colocation' naming style when passed in colocated parent table id

### ISSUE THREAD

**Issue by charleswang234** [yugabyte/yugabyte-db#16975]
Jira Link: [DB-6299](https://yugabyte.atlassian.net/browse/DB-6299)
### Description

Steps to reproduce:

Create a universe (rf3) with db version `2.17.4.0-b8` with colocated db.
Ex:
-- Generate colocated database.
create database col_true_db with colocation = true;

-- Connect to colocated db
\c col_true_db

-- Create colocated tables.
CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL
);

CREATE TABLE CUSTOMER(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL
);

-- Create table with colocation = false.
CREATE TABLE NOTCOLOCATEDTABLE(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL
) with (colocation=false);

Pass in the colocated parent uuid to `GetColocatedTabletSchemaRequestPB`, for example: `00004110000030008000000000004114.colocation.parent.uuid` as this have the new colocation naming schema. 

Perform the rpc call. The `GetColocatedTabletSchemaResponsePB` will return a MasterErrorPB with error code of `INVALID_TABLE_TYPE` and error message: `Table provided is not a parent colocated table`.

Looking at the db code, https://github.com/yugabyte/yugabyte-db/blob/14b205afadd21e89b00a80c0a07277e4408374f5/src/yb/master/catalog_manager.cc#L7184, I see we only check for  `*.colocated.parent.uuid` suffix.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6299]: https://yugabyte.atlassian.net/browse/DB-6299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment]
For colocation GA, GetTablegroupSchema RPC should be used instead of GetColocatedTableSchema to retrieve the list of tables associated with the colocated tablet. This is because colocation GA is implemented by creating a default tablegroup internally. (Note, we can add an API, i.e. GetColocationTabletSchema, that is an alias to GetTablegroupSchema if needed for clarity but have not done so yet). Resolving this as by-design.
