### ISSUE TITLE
Visually distinguish YSQL and YCQL api docs pages

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#1698]
Right now, especially when coming from an external search engine (or even our internal search tool) it's easy to confuse which API a page documents.
The main (only) visual distinction right now is the one letter `YSQL/YCQL` in the breadcrumb.

e.g:
<img width="829" alt="Screen Shot 2019-06-10 at 11 48 39 AM" src="https://user-images.githubusercontent.com/4038003/59218773-db687000-8b75-11e9-9c23-886e752fe995.png">
cc @schoudhury @rkarthik007

**Comment by ivanjovanic** [comment]
Maybe we can keep the YSQL/YCQL icon on the left side for all the datatypes? cc @yb-andrew
