### ISSUE TITLE
[YSQL] Experiencing data loss on rolling back to savepoint, with Tablet Splitting enabled

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#16988]
Jira Link: [DB-6309](https://yugabyte.atlassian.net/browse/DB-6309)
### Description

Scenario attempted on build `2.18.0.0-b17`
It is also seen in master.

This scenario is automated and it is reproducible 100% of the time.
This issue is observable with 2.18.* only, test passing with `2.17.*, 2.16.*, 2.14.* `, Tablet splitting enabled
Test was run tablet-splitting disabled and the test passed
### Steps to reproduce issue:
YSQL:

    1. Create Universe with tablet splitting enabled
    2. Create database
    3. Create table with extra extensions (earthdistance, pgcrypto, fuzzystrmatch, btree_gist,
    citext, hstore, uuid-ossp)
    4. Create complex table(hash and range sharded) with tablespace
    5. Load data validate tablet splitting
    6.  Create index(unique, partial , secondary) and views and Materialized views
    7.  Create Triggers ( after update insert)
    8. Execute Triggers
    9. Validate table data
    10. Create snapshot
    11. Load data to tables
    12. Validate tablet splitting after load data
    13. Create Joins(inner, right, left)
    14. Note time(1)
    15. Delete data from tables
    16. PITR to time(1)
    17. Create transactions with [ISOLATION LEVEL SERIALIZABLE(update insert delete)]
    18. Insert data
    19. Collect data
    20. Create savepoint s1
    21. Execute DMLs(Insert/delete/update) and validate the data
    22. Rollback to savepoint s1
    23. Collect data and validate with data at step#18
    
#### Issue: Observed : Data mis-match(Data Loss) with data in step#19 and data in step#23
This can be seen when execution of DML's(INSERT | UPDATE | DELETE) 100 or more than 100 rows take place, in step#19
Around 20 rows are missing it ranges between 2-50 rows with 1200-1300 rows present in table, not specific 

  
Attached  log files:  
[archive (1).zip](https://github.com/yugabyte/yugabyte-db/files/11306264/archive.1.zip)

    
#### G-Flags:
   Master Value
    
    `m_flags = {
            "enable_stream_compression": "true",
            "stream_compression_algo": "2",
            "enable_automatic_tablet_splitting": "true",
            "tablet_split_high_phase_shard_count_per_node": 200,
            # high_phase_size 2MB
            "tablet_split_high_phase_size_threshold_bytes": 2097152,
            # low_phase_size 100KB
            "tablet_split_low_phase_size_threshold_bytes": 102400,
            "tablet_split_low_phase_shard_count_per_node": 16,
            "ysql_enable_packed_row": "true"
        }
        `
        
   T-SERVER VALUE
        
        `t_flags = {
            "enable_automatic_tablet_splitting": "true",
            "ysql_num_shards_per_tserver": 1,
            "ysql_enable_packed_row": "true",
            "scheduled_full_compaction_frequency_hours": "12",
            "scheduled_full_compaction_jitter_factor_percentage": "100",
             "scheduled_full_compaction_check_interval_min": "5",
        }`
  
Schema used:     
```
CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
CREATE EXTENSION IF NOT EXISTS pgcrypto;  CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;        CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp”;

CREATE TYPE complex AS (re float8, im float8);
CREATE TYPE e_details AS ENUM ('Email', 'Sms', 'Phone');
CREATE DOMAIN postal_code AS TEXT CHECK(VALUE ~ '^\d{5}$'OR VALUE ~ '^\d{5}-\d{4}$');

 Table-
CREATE TABLE co_tab (
  id TEXT PRIMARY KEY, 
  uuid_col uuid DEFAULT uuid_generate_v4(), 
  name text COLLATE "en_US.utf8", 
  c complex, 
  info json, 
  contact JSONB, 
  arr smallint[], 
  cash money, 
  i inet, 
  m macaddr, 
  i2 serial, 
  i3 bigserial, 
  val smallint, 
  details e_details, 
  age int, 
  collated_data text collate "POSIX", 
  date DATE, 
  n NUMERIC (3, 2), 
  r real, 
  c1 CHAR(1), 
  created_at timestamptz, 
  uuid0 uuid DEFAULT uuid_nil(), 
  uuid1 uuid DEFAULT uuid_generate_v1(), 
  p1 POINT, 
  t1 TIME, 
  ts1 TIMESTAMP, 
  i4 INTERVAL, 
  p2 path, 
  p3 polygon, 
  b box, 
  c2 circle, 
  l line, 
  l1 lseg, 
  a2 text[][], 
  zip postal_code,
  user_handle citext,
  location point,
  fuzzy_str text,
  profile_data hstore
);
```
Load data --
```
DO $do$ BEGIN FOR i IN 1..10000 LOOP INSERT INTO tab_hash(
  id, name, c, info, contact, arr, cash, 
  i, m, i2, i3, val, details, age, collated_data, 
  date, n, r, c1, created_at, p1, t1, ts1, 
  i4, p2, p3, c2, l, l1, a2, zip
) 
VALUES 
  (
    i, 
    'Hermione', 
    (1, 2), 
    '{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}', 
    '{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}', 
    '{1, 2, 3}', 
    '$99.99', 
    '1.1.1.1', 
    '00:00:00:00:00:00', 
    i, 
    i + 1, 
    666, 
    'Sms', 
    15, 
    md5(
      random():: text
    ), 
    current_timestamp, 
    5.36, 
    2147483647, 
    'G', 
    now(), 
    point(3, 4), 
    LOCALTIME(0), 
    current_timestamp(0), 
    '00:25:00', 
    '(1,3), (4,12)', 
    '(1,3),(4,12), (2,4)', 
    '10, 4, 10', 
    '{1,2,3}', 
    '(0, 4), (2,8)', 
    '{{"b1", "c"}, {"m1", "l"}}', 
    89000
  );
END LOOP;
END $do$;
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6309]: https://yugabyte.atlassian.net/browse/DB-6309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Starting with @robertsami , we might need to involve PITR team if this has anything to do with PITR in step 16. cc @sanketkedia , @robertsami

**Comment by agsh-yb** [comment]
Narrowed this issue by removing certain steps which might not affecting the same 
```
1. Create Universe with tablet splitting enabled
2. Create database
3. Create table with extra extensions (earthdistance, pgcrypto, fuzzystrmatch, btree_gist,
citext, hstore, uuid-ossp)
4. Create complex table(hash and range sharded) with tablespace
5. Load data validate tablet splitting
6. Create snapshot
7. Load data to tables
8. Note time(1)
9. Delete data from tables
10. PITR to time(1)
11. Create transactions with [ISOLATION LEVEL SERIALIZABLE(update insert delete)]
12. Insert data
13. Collect data
14. Create savepoint s1
15. Execute DMLs(Insert/delete/update) and validate the data
16. Rollback to savepoint s1
17. Collect data and validate with data at step#13
```
**`2.17.4.0-b80`** is the first build where we can see this data loss issue
Same test is passing on **`2.17.4.0-b77`** and previous builds
cc: @rthallamko3, @robertsami
