### ISSUE TITLE
[YSQL] Irregular performance drops in queries with stream_compression_algo=3 (LZ4)

### ISSUE THREAD

**Issue by ssherwood** [yugabyte/yugabyte-db#16999]
Jira Link: [DB-6318](https://yugabyte.atlassian.net/browse/DB-6318)
### Description

When researching a performance related issue, I was able to reproduce an unusual performance anomaly (>5 seconds) involving a specific type of query that relies on a local geo covering index.  While attempting to isolate the root cause, I discovered that the issue went away when I changed `stream_compression_algo=3` to `stream_compression_algo=2`.  The problem resurfaced when I set it back to 3 (LZW).

This has been reproduced in multiple environments but here is the typical configuration.

- RF5, 3 regions (East, Central, and West).  East and Central and preferred leaders.

I have 4 key tables and 5 table spaces covering the 5 region/zones.  For each of the tables, I am creating 5 "local" geo covering indexes each table.  The query being run requires that the session temporarily disables nested loop and sequential scan (e.g. `set enable_nestloop to off` and `set enable_seqscan to off`) and use a PK match using an IN clause between two of the tables.  Effectively, `select * from t1 where t1.value = false and t1.pk in (select t2.t1_pk from t2);`

The performance anomaly does not occur consistently but depending on the environment may happen 1-in-3, 1-in-5 or 1-in-10 times.

Initial tracing has shown that the RPC completed 5 seconds before the reactor on the Postgres process finished receiving its response.

### Update: 

While the issue is specific to LZ4 compression setting, it turned out not be specific to geo-covering indexes or multi-region deployments. It is payload size dependent. To hit the latency issue..  the RPC response size needs to meet this criteria `compressed response size < internal buffer size < decompressed response size`.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6318]: https://yugabyte.atlassian.net/browse/DB-6318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
We suspect its caused by #16034. cc @es1024 , who is in the process of confirming this.
