### ISSUE TITLE
[yugabyted] yugabyted demo connect creating relations in yugabyte DB than yb_demo_northwind

### ISSUE THREAD

**Issue by pgyogesh** [yugabyte/yugabyte-db#16994]
Jira Link: [DB-6314](https://yugabyte.atlassian.net/browse/DB-6314)
### Description

I tried to use yugabyted demo connect --base_dir yugadata/node-1/. It created yb_demo_northwind database but relations were created in yugabyte database.

### How to re-produce?

- Try loading demo data

```
yugabyted demo connect
```

- List objects in `yb_demo_northwind` DB.
    - You won't find any relations.

- List objects in `yugabyte` DB.
   -  You will find the demo relations.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6314]: https://yugabyte.atlassian.net/browse/DB-6314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nchandrappa** [comment]
Code changes have landed.
