### ISSUE TITLE
[Docs] Deployment checklist for YugabyteDB clusters

### ISSUE THREAD

**Issue by szbyb** [yugabyte/yugabyte-db#17004]
### Description

https://docs.yugabyte.com/preview/deploy/checklist/

If should be specifically mentioned that at this stage only x86-64 arch is supported. We received a number of questions regarding YB's availability on ARM arch. It is understood that ARM support is on the roadmap; but it is not available yet.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by szbyb** [comment]
Acknowledging that Graviton is now used in YBM. Still ARM based deployment is not available for the masses.

**Comment by ddorian** [comment]
@szbyb 

do we have an issue for tracking official arm support?

**Comment by ddhodge** [comment]
@szbyb According to https://docs.yugabyte.com/stable/deploy/manual-deployment/install-software/#download-yugabytedb ARM is officially supported now.
Maybe supported architectures should be listed here https://docs.yugabyte.com/stable/deploy/checklist/#basics
but close this issue if the matter is moot
