### ISSUE TITLE
[xCluster] Remove leader_only flag from xcluster test suite

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#17000]
Jira Link: [DB-6319](https://yugabyte.atlassian.net/browse/DB-6319)
### Description

Investigate the use of `leader_only` in test suite and if it doesn't serve a purpose, see if we can remove it.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6319]: https://yugabyte.atlassian.net/browse/DB-6319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sraos88** [comment]
Hi Rahul,

Trying to understand it better.
Are you talking about the below in xcluster_test_base.h ?

  struct SetupReplicationOptions {
    SetupReplicationOptions() {}
    SetupReplicationOptions(LeaderOnly leader_only_, Transactional transactional_) {
      **leader_only** = leader_only_;
      transactional = transactional_;
    }
    LeaderOnly leader_only = LeaderOnly::kTrue;
    // Support consistent transactions for the replication group.
    Transactional transactional = Transactional::kFalse;
  };

I do see that its being used as part of SetupNSUniverseReplication ?
