### ISSUE TITLE
Change detected, rebuilding site not working on latest version of hugo

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#1701]
Not sure if this is hugo side of issue or our docs issue, but apparently watch functionality not working on the latest version of hugo

repo steps:
Upgrade hugo to 0.55+
npm start
and change any file, you would see the console wouldn't print
`Change detected, rebuilding site`

**Comment by stevebang** [comment]
Closing — no longer an issue.
