### ISSUE TITLE
Update the README.md for local development

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#1702]
We need to have folks use `npm ci` instead of `npm i` since the latter would update the `package-lock.json` forcing them to commit it.

**Comment by mbautin** [comment]
@ramkumarvs -- has this been addressed?
This is a docs issue, not YugaWare, right?
cc @bmatican

**Comment by stevebang** [comment]
@ddorian This has probably been fixed -- please check. Close if not an issue now.

**Comment by ddorian** [comment]
Docs uses `npm ci`.
