### ISSUE TITLE
Create separate repo for some removed sample apps

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#1703]
Some of the sample apps (e.g. Spark) were not included in the port to the Sample-Apps repo. However, we still reference them in our Apache Spark docs. We should create new repo to handle them.

**Comment by lizayugabyte** [comment]
The Spark content has been re-written (see #8720 ). Links to sample apps are valid.

**Comment by polarweasel** [comment]
The https://github.com/YugabyteDB-Samples org is the home for sample apps these days. Closing.
