### ISSUE TITLE
[DocDB] Export metrics help/units in /prometheus-metrics

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#17032]
Jira Link: [DB-6345](https://yugabyte.atlassian.net/browse/DB-6345)
### Description

Prometheus format suppors #HELP and #TYPE comments to pass the description/help of the metrics and the type to prometheus.

Our current output format in `/prometheus-metrics` does not export any of this. However, we do have this as part of the metric-prototype.

We should support exporting these details (preferably, guarded by a flag/url-parameter) so that customers who want/need them can find help for a give metric, without having to do a `git-grep` on our codebase.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6345]: https://yugabyte.atlassian.net/browse/DB-6345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Example from https://sysdig.com/blog/prometheus-metrics/

```
# HELP metric_name Description of the metric
# TYPE metric_name type
# Comment that's not parsed by prometheus
http_requests_total{method="post",code="400"}  3   1395066363000
```

**Comment by yusong-yan** [comment]
This GitHub issue is duplicate with https://github.com/yugabyte/yugabyte-db/issues/17016
