### ISSUE TITLE
[YSQL] Extend existing unit tests to run for READ COMMITTED isolation level

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#17052]
Jira Link: [DB-6361](https://yugabyte.atlassian.net/browse/DB-6361)
### Description

Run existing unit tests which are relevant for READ COMMITTED isolation level as well. This might require some changes to tests.

This will also help towards enabling read committed by default.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6361]: https://yugabyte.atlassian.net/browse/DB-6361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/18462
