### ISSUE TITLE
[YSQL] Many Core Files seen for system-itest test TestYSQLPITRWithNewNodeAutomaticTabletSplitting

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#17066]
Jira Link: [DB-6371](https://yugabyte.atlassian.net/browse/DB-6371)
### Description

  On version: 2.14.9.0-b23
  Many Core files are seen while running test TestYSQLPITRWithNewNodeAutomaticTabletSplitting 
Core files were not seen on 2.14.7 and 2.14.8
```
        1. Create a universe with RPC, YSQL Packed row and Tablet splitting and read committed
           isolation level enabled
        2. Create a colocated database, Create Snapshot schedule and note down time(0)
        3. Create 2 colocated and a non colocated table
        4. Insert 10 rows to all tables
        5. Note down time(1)
        6. Create all types of indexes on the table
        7. Create Materialized views on both the table
        8. Create unique index on both the Materialized views
        9. Refresh both Materialized views 
        10. Load 1000 rows in both colocated tables and 40k rows in non colocated table
           and validate tablets count
        11. Refresh both Materialized views and note down the time(2), 
        12. Delete few rows from all the tables 
        13. Refresh both Materialized views and note down the time(3)
        14. Update data in all the tables
        15. Refresh both Materialized views
        16. Run contentious transactions on the 1st colocated table and non colocated table
        17. Add 3 nodes to the universe and load more data in both the tables
        18. Restart one of the node(this should restart a tserver)
        19. Restore to time(3) 
        20. Alter all tables, Flush and compact tables
        21. Restore to time(2) -----> Fails here 
    
Failed to get restoration status(RESTORED) in list snapshots output for be559acd-8440-47f4-8380-35094fd4a1d0 
         restoration id, Status: RESTORING
```
Please find all the logs here 
        [Logs](https://drive.google.com/file/d/1xBTdhrrdLBTmrMv3tAYIHWdLFjs9T6J9/view?usp=sharing)
       [Core Files-Jenkins]( https://jenkins.dev.yugabyte.com/job/itest-system-developer/5678/artifact/logs/2.14.9.0_testysqlpitrwithnewnodeautomatictabletsplitting-aws-rf3_20230427_103916/10.9.139.83/)
       [Jenkins run](https://jenkins.dev.yugabyte.com/job/itest-system-developer/5678/)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6371]: https://yugabyte.atlassian.net/browse/DB-6371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shishir2001-yb , Can you share the backtrace from the core dumps?

**Comment by rthallamko3** [comment]
[https://jenkins.dev.yugabyte.com/job/itest-system-developer/5678/artifact/logs/2.14.9.0_t[…]atictabletsplitting-aws-rf3_20230427_103916/10.9.139.83/](https://jenkins.dev.yugabyte.com/job/itest-system-developer/5678/artifact/logs/2.14.9.0_testysqlpitrwithnewnodeautomatictabletsplitting-aws-rf3_20230427_103916/10.9.139.83/)

**Comment by shishir2001-yb** [comment]
As colocation is a beta feature in 2.14.9 so we are not backporting the [fix](https://phabricator.dev.yugabyte.com/D17864 )
