### ISSUE TITLE
[YSQL][Unit Test] Test CreateTableITest.LazySuperblockFlushSingleTablePersistence and CreateTableITest.LazySuperblockFlushMultiTablePersistence fails on ASAN build 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#17106]
Jira Link: [DB-6393](https://yugabyte.atlassian.net/browse/DB-6393)
### Description

Unit test **CreateTableITest.LazySuperblockFlushSingleTablePersistence** and **CreateTableITest.LazySuperblockFlushMultiTablePersistence** started failing on **_ASAN_** build after this [commit](https://github.com/yugabyte/yugabyte-db/commits/3d75fd5a081d1170289398022348df546c3969fe) 

Stability Trend 
[CreateTableITest.LazySuperblockFlushSingleTablePersistence](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CreateTableITest&fail_tag=all&name=LazySuperblockFlushSingleTablePersistence&num_commits=500&platform=linux)
[CreateTableITest.LazySuperblockFlushMultiTablePersistence](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CreateTableITest&fail_tag=all&name=LazySuperblockFlushMultiTablePersistence&platform=linux)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6393]: https://yugabyte.atlassian.net/browse/DB-6393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arpang** [comment]
Fixed as https://github.com/yugabyte/yugabyte-db/issues/17104
