### ISSUE TITLE
[YSQL] pg_hint syntax for follower reads does not work with prepared statements.

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#17135]
Jira Link: [DB-6417](https://yugabyte.atlassian.net/browse/DB-6417)
### Description

Reported by @FranckPachot  in https://github.com/yugabyte/yugabyte-db/issues/17024#issuecomment-1522891905

Pg_hint syntax to enable follower reads for prepared statements does not work once the statement plan has been generated and cached.

more discussion at https://yugabyte.slack.com/archives/CAR5BCH29/p1683044734561099?thread_ts=1682098927.326419&cid=CAR5BCH29

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6417]: https://yugabyte.atlassian.net/browse/DB-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
Documentation bug. We should not recommend using pg_hint_plan to set transaction_read_only, it only works because of a Postgres bug.
