### ISSUE TITLE
[YSQL] NULL values should be stored after non-null values to match PostgreSQL's default sort order

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1715]
https://www.postgresql.org/docs/11/queries-order.html

> By default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

**Comment by mbautin** [comment]
See value_type.h, kNull and kNullDescending.

**Comment by d-uspenskiy** [comment]
Fixed in  context of #1760
