### ISSUE TITLE
[ycql] Change the default for cql_use_metadata_cache_for_schema_version_check to true

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#17163]
Jira Link: [DB-6439](https://yugabyte.atlassian.net/browse/DB-6439)
### Description

Change the default for `cql_use_metadata_cache_for_schema_version_check` to `true`

If customers use an anti-pattern (large number of prepared statements), are upgrading from a build that doesn’t have the gflag definition - cql_use_metadata_cache_for_schema_version_check , then they cannot set the override to true before the upgrade and as a result run into performance regression in 2.14.5+ builds. 

A better strategy would be to use   cql_use_metadata_cache_for_schema_version_check with default to true in the code to begin with.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6439]: https://yugabyte.atlassian.net/browse/DB-6439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
This g-flag `cql_use_metadata_cache_for_schema_version_check` was introduced here: https://github.com/yugabyte/yugabyte-db/issues/16135
