### ISSUE TITLE
[YCQL] Flaky test TestJsonIndex.testIndexEscapeName

### ISSUE THREAD

**Issue by dr0pdb** [yugabyte/yugabyte-db#17161]
Jira Link: [DB-6437](https://yugabyte.atlassian.net/browse/DB-6437)
### Description

The `TestJsonIndex.testIndexEscapeName` test is flaky on master.

`./yb_build.sh --clang15 --java-test 'org.yb.cql.TestJsonIndex' -n 10` fails 3 times for me on my local machine.

Error
```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 60.792 s <<< FAILURE! - in org.yb.cql.TestJsonIndex
[ERROR] testIndexEscapeName(org.yb.cql.TestJsonIndex)  Time elapsed: 13.185 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Row[100[0]Row[1001]Row[1002]Row[1003]Row[1004]Row[1005]Row[1006]Row[1007]Row[1008]Row[1009]]> but was:<Row[100[5]Row[1001]Row[1006]Row[1007]Row[1009]Row[1004]Row[1000]Row[1002]Row[1008]Row[1003]]>
	at org.yb.cql.TestJsonIndex.testIndexEscapeName(TestJsonIndex.java:252)
```

Seems like this is just a different order.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6437]: https://yugabyte.atlassian.net/browse/DB-6437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
No backports planned because this is a flaky test fix only.
