### ISSUE TITLE
Compilation fails on Ubuntu 19.04

### ISSUE THREAD

**Issue by deeps1991** [YugaByte/yugabyte-db#1719]
I have a brand new virtual machine running Ubuntu 19.04.

I've been following the instructions here:
https://docs.yugabyte.com/latest/contribute/core-database/build-from-src/

And on running ./yb_build.sh release, I get the following build failure:
```
raceback (most recent call last):
  File "/home/osboxes/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 786, in <module>
    main()
  File "/home/osboxes/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 783, in main
    builder.run()
  File "/home/osboxes/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 224, in run
    self.build(BUILD_TYPE_UNINSTRUMENTED)
  File "/home/osboxes/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 601, in build
    self.build_dependency(dep)
  File "/home/osboxes/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 651, in build_dependency
    self.download_dependency(dep)
  File "/home/osboxes/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 366, in download_dependency
    subprocess.check_call(dep.post_patch)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
CMake Error at CMakeLists.txt:578 (message):
  Thirdparty was built unsuccessfully, terminating.


-- Configuring incomplete, errors occurred!
See also "/home/osboxes/yugabyte-db/build/release-gcc-dynamic-community-ninja/CMakeFiles/CMakeOutput.log".
```

Please can someone help me out here? Please do let me know what additional information I should be attaching here.

**Comment by mbautin** [comment]
@deeps1991: thank you for your interest in YugaByte DB! Could you please try installing the following packages and re-running the build?

```
    sudo apt-get install -y \
      apt-file \
      apt-utils \
      automake \
      bison \
      cmake \
      curl \
      flex \
      git \
      golang \
      less \
      libbz2-dev \
      libicu-dev \
      libreadline-dev \
      libssl-dev \
      libtool \
      maven \
      ninja-build \
      openjdk-8-jdk-headless \
      pkg-config \
      python-dev \
      python-pip \
      rsync \
      sudo \
      unzip \
      uuid-dev \
      wget
```

Also if you are using GCC 8 on Ubuntu 19.04, you might hit a few more issues, so it is currently recommended to use GCC 7. You can try installing the `gcc-7` package ( https://packages.ubuntu.com/search?keywords=gcc-7 ).

**Comment by deeps1991** [comment]
Hi @mbautin , thanks for taking a look!
I followed both of your steps outlined above, and ran into another build failure:

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
In file included from src/yb/rocksdb/slice_transform.h:34:0,
                 from src/yb/rocksdb/util/slice_transform_test.cc:24:
src/yb/util/slice.h: In member function ‘virtual void rocksdb::SliceTransformTest_CapPrefixTransform_Test::TestBody()’:
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                      ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
src/yb/util/slice.h:64:57: error: array subscript is below array bounds [-Werror=array-bounds]
   Slice(const uint8_t* d, size_t n) : begin_(d), end_(d + n) {}
                                                       ~~^~~
cc1plus: all warnings being treated as errors
Input files:
  src/yb/rocksdb/CMakeFiles/slice_transform_test.dir/util/slice_transform_test.cc.o
  src/yb/rocksdb/util/slice_transform_test.cc
Output file (from -o): src/yb/rocksdb/CMakeFiles/slice_transform_test.dir/util/slice_transform_test.cc.o
\-------------------------------------------------------------------------------
ninja: build stopped: subcommand failed.

real    15m36.919s
user    12m5.706s
sys     0m53.845s
[osboxes 2019-07-06T21:44:06 yb_build.sh:396 run_cxx_build] C++ build finished with exit code 1 (build type: release, compiler: gcc). Timing information is available above.
```
I removed
```
ADD_CXX_FLAGS("-Werror")
```
 from CMakeLists.txt to unblock myself for the time being, and see that the build has been progressing now. The comments in the CMakeLists.txt suggest that the -Werror does not apply to src/rocksdb, but I somehow still hit the above issue. Is there anything else I could try out?

**Comment by rajukumaryb** [comment]
@deeps1991 : Instead of removing "-Werror", the following is a narrower workaround for the same problem -

```
diff --git a/src/yb/rocksdb/CMakeLists.txt b/src/yb/rocksdb/CMakeLists.txt
index d5610f5a9..288b9d6cc 100644
--- a/src/yb/rocksdb/CMakeLists.txt
+++ b/src/yb/rocksdb/CMakeLists.txt
@@ -198,7 +198,7 @@ set(ROCKSDB_SRCS
 set(CMAKE_CXX_FLAGS
   "${CMAKE_CXX_FLAGS} \
    -Wextra -Wsign-compare -Wshadow -Woverloaded-virtual \
-   -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-variable")
+   -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-variable -Wno-array-bounds")

 if (IS_CLANG)
   set(CMAKE_CXX_FLAGS
```

**Comment by d-uspenskiy** [comment]
This compilation problem is fixed with the following commit https://github.com/YugaByte/yugabyte-db/commit/3b90e8560b8d8bc81fba6ba9b9f2833e83e2244e Please sync your source code to latest master

**Comment by mbautin** [comment]
@deeps1991: have you been able to give the build another try by any chance?

**Comment by deeps1991** [comment]
@mbautin Yes I did. In fact I notice @d-uspenskiy 's commit went in a week before I checked the code, so that commit isn't helping. As a paranoia check, I retried building the code after rebasing to latest master, and removing the contents of build/release-gcc-dynamic-community.
I hit the selfsame issue again.

**Comment by deeps1991** [comment]
Also just FYI, (if needed for documentation) I'd also needed to install pip2
and zlib1g-dev packages to get past a couple of build failures.

**Comment by d-uspenskiy** [comment]
@deeps1991 Thanks for report the problem, compilation issue was re-fixed here https://github.com/YugaByte/yugabyte-db/commit/d7fd901cd7a9140300bb113bd0394269631f1ce3

**Comment by deeps1991** [comment]
Thanks @d-uspenskiy !! 
I rebased to latest master and the compilation went through fine.
It does take 6-7 hours to complete though.

@mbautin Are the packages you listed above a mandatory pre-build step? if so, I can add them to the docs  for ubuntu installation

**Comment by d-uspenskiy** [comment]
@deeps1991 
Great! Compilation time can be significantly reduced by avoiding unit test compilation. The following command will build all the required components to start the cluster:
```
./yb_build.sh daemons --target yb-admin --sjb
```
But never the less 6-7 hours is too much. Modern laptop with 6 cores i7 + SSD completes full rebuild in about 15 min on Linux

**Comment by mbautin** [comment]
@deeps1991: yes, it would be good if you could add those packages to build instructions in the docs! Thank you!

**Comment by sragavendraselvam** [comment]
> @deeps1991: thank you for your interest in YugaByte DB! Could you please try installing the following packages and re-running the build?
> 
> ```
>     sudo apt-get install -y \
>       apt-file \
>       apt-utils \
>       automake \
>       bison \
>       cmake \
>       curl \
>       flex \
>       git \
>       golang \
>       less \
>       libbz2-dev \
>       libicu-dev \
>       libreadline-dev \
>       libssl-dev \
>       libtool \
>       maven \
>       ninja-build \
>       openjdk-8-jdk-headless \
>       pkg-config \
>       python-dev \
>       python-pip \
>       rsync \
>       sudo \
>       unzip \
>       uuid-dev \
>       wget
> ```
> 
> Also if you are using GCC 8 on Ubuntu 19.04, you might hit a few more issues, so it is currently recommended to use GCC 7. You can try installing the `gcc-7` package ( https://packages.ubuntu.com/search?keywords=gcc-7 ).

I too got the same issue and it got fixed after I installed rsync. please update the [documentation ](https://docs.yugabyte.com/latest/contribute/core-database/build-from-src/) with this install command.

**Comment by rkarthik007** [comment]
cc @stevebang 

@sragavendraselvam - please let me know if there is any interest in contributing to our docs, would really appreciate it (and its pretty simple) 😄

**Comment by sragavendraselvam** [comment]
> cc @stevebang
> 
> @sragavendraselvam - please let me know if there is any interest in contributing to our docs, would really appreciate it (and its pretty simple) 😄

@rkarthik007 Sure. Would love to contribute. What should I do?

**Comment by kmuthukk** [comment]
Thx @sragavendraselvam!

You can submit a pull request on the yugabyte-db repo. The docs sub-directory is here:

`https://github.com/YugaByte/yugabyte-db/tree/master/docs`

and there you'll find a [README.md](https://github.com/YugaByte/yugabyte-db/blob/master/docs/README.md) with instructions.
