### ISSUE TITLE
[YCQL] Flaky test o.y.cql.PrepareExecute.AlterDropAdd

### ISSUE THREAD

**Issue by dr0pdb** [yugabyte/yugabyte-db#17219]
Jira Link: [DB-6470](https://yugabyte.atlassian.net/browse/DB-6470)
### Description

The test `o.y.cql.PrepareExecute.AlterDropAdd` sometimes fails on Jenkins. 

Attempt fixing it if possible. There is a `Thread.sleep(3000);` statement in the test, so that might be the culprit but not sure.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6470]: https://yugabyte.atlassian.net/browse/DB-6470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
The fixed test should be backported into 2.18, 2.16, 2.14.
See backports for the source fix in https://github.com/yugabyte/yugabyte-db/issues/17163
