### ISSUE TITLE
[YSQL] Query layer and DocDB ordering of nulls differs [format change]

### ISSUE THREAD

**Issue by m-iancu** [YugaByte/yugabyte-db#1723]
In DocDB nulls sort lower than non-null values by default, while in YSQL they sort higher.
That leads to unnecessary additional sorting at the query layer when using `ORDER BY` clauses.

We should also support `NULLS LAST` clauses (`NULLS FIRST` is already supported) in `SELECT` and, if possible, in `CREATE INDEX`.

Note: We already have two nulls for DocDB: `kNull` (lowest possible value) and `kNullDescending` (highest possible value -- currently used for DESC-ordered columns).
We should be able to re-use these constants accordingly (and possibly rename them for clarity).

See also #1535.

**Comment by ndeodhar** [comment]
Related issue: https://github.com/YugaByte/yugabyte-db/issues/1715

**Comment by d-uspenskiy** [comment]
Fixed in  context of #1760
