### ISSUE TITLE
[Docs] Update tablet splitting documentation

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#17254]
### Description

- On https://docs.yugabyte.com/preview/reference/configuration/yb-master/#tablet-splitting-flags --enable_automatic_tablet_split is documented as default: false  which is correct for stable version however it show the same for v2.17 preview, which is incorrect since the default is true from 2.13 preview version and further.
- With 2.18.0, there were changes to the flags like the number of tablets for low cores etc. The documentation needs to be updated for that.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by arybochkin** [comment]
2.18.0 is not yet released. The latest available is preview version 2.17.
