### ISSUE TITLE
[DocDB] Fix AutoFlagsExternalMiniClusterTest.NewCluster in TSAN

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#17264]
Jira Link: [DB-6499](https://yugabyte.atlassian.net/browse/DB-6499)
### Description

Test only broken in TSAN

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6499]: https://yugabyte.atlassian.net/browse/DB-6499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Duplicate of #17262, used the other one to mute the test
