### ISSUE TITLE
[YSQL] flaky test: PgCatalogVersionTest.IncrementAllDBCatalogVersions

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17263]
Jira Link: [DB-6498](https://yugabyte.atlassian.net/browse/DB-6498)
### Description

Traces to https://github.com/yugabyte/yugabyte-db/commit/da3e29ee6e518cf41d5a47e3dd8092bf8cbd3a58, where it was introduced

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgCatalogVersionTest&fail_tag=all&name=IncrementAllDBCatalogVersions&platform=linux

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6498]: https://yugabyte.atlassian.net/browse/DB-6498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=PgCatalogVersionTest&name=IncrementAllDBCatalogVersions&num_commits=50

Only 1 failure in last 50 commits (400 test runs across 8 builds). Closing as fixed.
