### ISSUE TITLE
[YSQL] "Alter sequence" to change name, schema, and owner seem to work but cause warnings

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#17271]
Jira Link: [DB-6505](https://yugabyte.atlassian.net/browse/DB-6505)

### Background

See [Issue #1002](https://github.com/yugabyte/yugabyte-db/issues/1002). It already had status "closed" when [lukaseder](https://github.com/lukaseder) commented that _alter sequence... rename_ draws a warning that references Issue #1002. This has only just come to my attention because of [Doc issue #9952](https://github.com/yugabyte/yugabyte-db/issues/9952) — also filed by _lukaseder_. This complains that _"cycle / no cycle"_ isn't doc'd. But (strangely) this Doc issue doesn't mention the fact that _alter sequence_ variants to change a sequence's _name_, _schema_, or _owner_ are not doc'd. (See the [PG doc](https://www.postgresql.org/docs/11/sql-altersequence.html).)

### Testcase

The tests that are described in this report were run after starting my YB cluster with this YSQL configuration parameter setting:

```
ysql_suppress_unsupported_error=true
```

The default for this parameter is _false_. And when the default setting is used, every _0A000_ occurrence, that in my tests is a _warning_ and that I suppress by setting _client_min_messages_ to _error_, is a genuine **error**—meaning that any statement that causes _0A000_ rolls back and has no effect.

I did the tests using _YB-2.17.0.0_ (in a Ubuntu 22.04 VM). The _alter sequence_ functionality splits into two groups:

- Changing the attributes that the _pg_sequence_ catalog table shows:
  ```
  seqtypid
  seqstart
  seqincrement
  seqmax
  seqmin
  seqcache
  seqcycle
  ```
  
  These work without error or warning.
- Altering the sequence's _name_, _schema_, or _owner_. These all draw a warning with the same wording:
  ```
  0A000: ALTER SEQUENCE not supported yet
  See https://github.com/yugabyte/yugabyte-db/issues/1002. React with thumbs up to raise its priority
  ```
  But if you suppress the warnings (to remove the distracting noise), you see that these _alter_ variants all seem to work as described in the PG doc.

Notice that I didn't check the _owned by_ functionality. But the YB doc does explain this.

In order to show all of these attributes of a sequence in a single query, you need to join _pg_sequence_ with _pg_class_, _pg_namespace_, and _pg_roles_ thus:

```
-- Save this as "show_sequence-metadata.sql"
\t on
\x on
select
  c.relname                             as name,
  n.nspname                             as "schema",
  rpad(r.rolname, 8)                    as "owner",
  t.typname                             as "data type",
  s.seqstart                            as "start with",
  s.seqincrement                        as "increment by",
  s.seqmax                              as "maxval",
  s.seqmin                              as "minval",
  s.seqcache                            as "vals to cache",
  s.seqcycle::text                      as "cycle"
from
  pg_class as c
  inner join pg_namespace as n
  on c.relnamespace = n.oid
  inner join
  pg_roles as r
  on c.relowner = r.oid
  inner join
  pg_sequence as s
  on c.oid = s.seqrelid
  inner join pg_type as t
  on s.seqtypid = t.oid
where c.relname ~ '^seq_' and c.relkind = 'S';
\x off
\t off
```

Notice that, because of the possibility to cache a set of next and next consecutive sequence values for a particular session, you cannot expect the _pg_sequence_ table to have a column for the current value. I used this pragmatic approach in stead:
```
create function s0.the_nextval()
  returns bigint
  set search_path = pg_catalog, pg_temp
  language plpgsql
as $body$
declare
  schema   text not null := '';
  seq_name text not null := '';
  s bigint not null := 0;
begin
  select c.relname, n.nspname
  into strict seq_name, schema
  from pg_class as c inner join pg_namespace as n on c.relnamespace = n.oid
  where c.relname ~ '^seq_' and c.relkind = 'S';

  execute format($$select nextval('%I.%I')$$, schema, seq_name) into s;
  return s;
end;
$body$;
```

This test shows that every single _alter_ operation seems to work.

```
/*
  Ensure that the sandbox database "d0" exists and the schemas "s0" and "s1"
  exist within it. Ensure that an ordinary role, say "d0$u1", exists in the cluster
  and that it has "connect" and "create" on database "d0".

  Connect as a superuser like "yugabyte".
*/;
\c d0 yugabyte
\i cr-the-nextval.sql
set client_min_messages = warning;

-- Silly parameterization, just to demo that is produces the expected metadata.
create sequence s0.seq_0 as smallint
  start with 42
  increment by 17
  maxvalue 999
  minvalue 42
  cache 111
  cycle;

\i show_sequence-metadata.sql
select s0.the_nextval();

-- Sensible parameterization.
alter sequence s0.seq_0 as bigint
  start with 1
  restart
  increment by 1
  no maxvalue
  minvalue 1
  cache 120
  no cycle;

set client_min_messages = error;
alter sequence s0.seq_0 rename to seq_1;
alter sequence s0.seq_1 set schema s1;
alter sequence s1.seq_1 owner to d0$u1;

\i show_sequence-metadata.sql
select s0.the_nextval();
```

Here's what the first invocation of _"show_sequence-metadata.sql"_ and _the_nextval()_ show:

```
name          | seq_0
schema        | s0
owner         | yugabyte
data type     | int2
start with    | 42
increment by  | 17
maxval        | 999
minval        | 42
vals to cache | 111
cycle         | true

 the_nextval 
-------------
          42
```

And here's what the second invocation of _"show_sequence-metadata.sql"_ and _the_nextval()_ show:

```
name          | seq_1
schema        | s1
owner         | d0$u1   
data type     | int8
start with    | 1
increment by  | 1
maxval        | 9223372036854775807
minval        | 1
vals to cache | 120
cycle         | false

 the_nextval 
-------------
           1
```

The results are identical in vanilla PG.

### Recommendation

Confirm by more testing and reading of the implementation that the present _"0A000: ALTER SEQUENCE not supported yet"_ warnings are superfluous and then remove them. File a new doc issue to request that the _altering sequence_ variants to change the _name_, _schema_, or _owner_ be included in the syntax diagram and be described.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6505]: https://yugabyte.atlassian.net/browse/DB-6505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
@bllewell 

On 2.17.3.0 (ubuntu 22.04), this doesn't work:
```sql
create sequence s1;
set client_min_messages = error;
alter sequence s1 rename to s2;
```
```sql
ERROR:  ALTER SEQUENCE not supported yet
LINE 1: alter sequence s1 rename to s2;
        ^
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/1002. React with thumbs up to raise its priority
```

I don't understand why it worked for you?

**Comment by ddorian** [comment]
@bllewell 

The `RENAME TO` syntax is not explained on the grammar/diagram.

So maybe this isn't supported in YSQL, and the correct fix would be to create a new issue that "RENAME TO" is not supported and change the YSQL error to point to it instead of #1002 ?

**Comment by bllewell** [comment]
I said at the start that I tested using _YB-2.17.0.0_ (in a Ubuntu 22.04 VM). If you see a different outcome in _2.17.3.0_ (ubuntu 22.04), then this must because an engineer did a code change. Either way, this is a bug if you use the criterion "YSQL is fully PostgreSQL compatible" — and so it needs proper investigation and diagnosis.

Until this is done, everything else is moot.

_p.s._ Notice that this concerns not only _rename to_ but also _set schema_ and _owner to_.

**Comment by ddorian** [comment]
@bllewell 

The reason I tested with a newer 2.17.3.0 is because it usually has fewer bugs than a 2.x.0.0 release.

Now I tested with 2.17.0.0 and still see the same error (and created a new cluster just for it):
```sql
 ./bin/ysqlsh -h 127.0.1.1
ysqlsh (11.2-YB-2.17.0.0-b0)
Type "help" for help.

yugabyte=# create sequence s1;
CREATE SEQUENCE
yugabyte=# set client_min_messages = error;
SET
yugabyte=# alter sequence s1 rename to s2;
ERROR:  ALTER SEQUENCE not supported yet
LINE 1: alter sequence s1 rename to s2;
        ^
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/1002. React with thumbs up to raise its priority
yugabyte=# \d
          List of relations
 Schema | Name |   Type   |  Owner   
--------+------+----------+----------
 public | s1   | sequence | yugabyte
(1 row)

yugabyte=# \d
          List of relations
 Schema | Name |   Type   |  Owner   
--------+------+----------+----------
 public | s1   | sequence | yugabyte
(1 row)

yugabyte=# create schema sch1;
CREATE SCHEMA
yugabyte=# alter sequence s1 set schema sch1;
ERROR:  ALTER SEQUENCE SET SCHEMA not supported yet
LINE 1: alter sequence s1 set schema sch1;
        ^
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/1002. React with thumbs up to raise its priority

```

> p.s. Notice that this concerns not only rename to but also set schema and owner to.

I agree. Those also don't work (see above for `set schema`).

**Comment by bllewell** [comment]
I just re-tested in my env. for the Nth time. All three _alter sequence _ flavors_ (_rename to_, _set schema_, and _owner to_) run silently with _client_min_messages_ set to _error_. And my catalog queries show that they get the right results.

Here's what my _select version()_ shows:

```
 PostgreSQL 11.2-YB-2.17.0.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 14.0.6 (https://github.com/yugabyte/llvm-project.git 4047555d02fa41c8dbfc8a8f529680276af9742e), 64-bit
```

What does yours show? (You show only the message that the _ysqlsh_ client shows at start-up.)

**Comment by ddorian** [comment]
@bllewell 

Note that [lukaseeder comment](https://github.com/yugabyte/yugabyte-db/issues/1002#issuecomment-915119268) said "it should work because docs said so, but I'm still getting an error, BUT even the docs never mentioned `rename to`". 

Even the commit to enable the feature has no reference to "rename to" or changing schema https://github.com/yugabyte/yugabyte-db/commit/c6ddd7d133023f93378c06fbf2c00e7ac49ad246

**Comment by bllewell** [comment]
In response to @ddorian's comment... yes, by all means. But that doesn't detract from my point. This is a product bug, and not a doc bug. My tests seem to show that we're tantalizingly close to supporting the full _alter seqence_ functionality as described in the[ PG doc](https://www.postgresql.org/docs/11/sql-altersequence.html). I'd like to hear from YB Development whether my surmise is right.

**Comment by bllewell** [comment]
@ddorian's comment, posted on 10-May-2023, finished with _"I don't understand why it worked for you"_. The reason is that I'd restarted my YB cluster with _"ysql_suppress_unsupported_error=true"_.  I've just added a note to this effect at the start of this report.
