### ISSUE TITLE
[yugabyted] How to create a spatial index on a PostgreSQL GEOMETRY field?

### ISSUE THREAD

**Issue by julor** [yugabyte/yugabyte-db#17316]
Jira Link: [DB-6536](https://yugabyte.atlassian.net/browse/DB-6536)
### Description

I installed postgis extension.
Using a  spatial index on geometry field will greatly  increase the performance of spatial query，and many GIS softwares require  spatial indexing to work.How do I create a spatial index？

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6536]: https://yugabyte.atlassian.net/browse/DB-6536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by julor** [comment]
Will there be any development plans recently？

**Comment by ddorian** [comment]
It's on the roadmap, see https://github.com/yugabyte/yugabyte-db#current-roadmap
