### ISSUE TITLE
[Docs] Better spacing on `create table` diagram on YSQL

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#17324]
### Description

From this [comment](https://github.com/yugabyte/yugabyte-db/pull/17215#issuecomment-1546516063):

On the `create table` for YSQL page: https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_table/

1. The railroad diagram for the create_table rule is hard to read because the font is too small. Suggest adding a backslash in the EBNF just before the "WITH / WITHOUT" alternatives.

2. Same story for the table_constraint rule. Recommend backslash before the "DEFERRABLE / NOT DEFERRABLE" portion.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by bllewell** [comment]
Thanks for making this change. It's a big improvement. You didn't assign this PR to me for approval—but if you were to, then I'd approve it. Else just go ahead and squash and merge.

**Comment by ddorian** [comment]
@bllewell I did ask you for review on the pull request https://github.com/yugabyte/yugabyte-db/pull/17325
