### ISSUE TITLE
[DocDB] Flaky test: QLTransactionTest.IntentsCleanupAfterRestart

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#17330]
Jira Link: [DB-6541](https://yugabyte.atlassian.net/browse/DB-6541)
### Description

Seems to trace to https://github.com/yugabyte/yugabyte-db/commit/3272f36005a58aee4b6b1bf395cf575e433279d6

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=QLTransactionTest&fail_tag=all&name=IntentsCleanupAfterRestart&platform=linux

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6541]: https://yugabyte.atlassian.net/browse/DB-6541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
`../../src/yb/client/ql-transaction-test.cc:948 Failed Bad status: Timed out (yb/util/backoff_waiter.cc:78): Operation 'Enough compactions happen' didn't complete within 10000ms`

**Comment by bmatican** [comment]
@arybochkin is this still flaky? Did it indeed trace back to the change to enable splitting?

**Comment by arybochkin** [comment]
@bmatican, yes it is flaky and it is not related to enabling of splitting, it started failing with changing thresholds for low CPU number, but this change is just a marker and the test itself is not stable and the params/constants are not accurate enough (confirmed with Sergey), the test requires deeper analysis (already done) and additional tuning (in progress) to make it stable.

**Comment by bmatican** [comment]
Ah sorry, yes, I confused the commit! I recall now you had a separate commit for auto-tune by # cpus.
Thanks for the update! Glad to hear it's a test only change, rather than a product issue!
