### ISSUE TITLE
[YSQL] BNLJ is slower when inner table is hash sharded, than when inner table is range sharded

### ISSUE THREAD

**Issue by gauravk-in** [yugabyte/yugabyte-db#17357]
Jira Link: [DB-6550](https://yugabyte.atlassian.net/browse/DB-6550)
### Description

In colocated scenario, we tried joining following tables. In each case CBO picked Batch Nested Loop Join with smaller table as the outer table. 

However, it turns out that the when the inner table is hash sharded, BNLJ performs much slower compared to if the inner table is range sharded. 

When the inner table is hash sharded, Hash Join is infact the best plan. When the inner table is range sharded, BNLJ is still the best plan. The attached graph shows the run times for various joins.

```
SET yb_bnl_batch_size=1024;
CREATE TABLE t_range_pk_50k as SELECT
    s*2 id,
    s*2 v1,
    s*2 v2
    FROM generate_series(1, 50000) s;
ALTER TABLE t_range_pk_50k ADD PRIMARY KEY (id ASC);

CREATE TABLE t_hash_pk_50k WITH (COLOCATED=false) as SELECT
    s*2 id,
    s*2 v1,
    s*2 v2
    FROM generate_series(1, 50000) s;
ALTER TABLE t_hash_pk_50k ADD PRIMARY KEY (id HASH);

CREATE TABLE t_range_pk_20k as SELECT
    s*5 id,
    s*5 v1,
    s*5 v2
    FROM generate_series(1, 20000) s;
ALTER TABLE t_range_pk_20k ADD PRIMARY KEY (id ASC);

CREATE TABLE t_hash_pk_20k WITH (COLOCATED=false) as SELECT
    s*5 id,
    s*5 v1,
    s*5 v2
    FROM generate_series(1, 20000) s;
ALTER TABLE t_hash_pk_20k ADD PRIMARY KEY (id HASH);

SELECT *FROM   t_hash_pk_20k join t_hash_pk_50k ON t_hash_pk_20k.id = t_hash_pk_50k.id
SELECT *FROM   t_range_pk_20k join t_hash_pk_50k ON t_range_pk_20k.id = t_hash_pk_50k.id
SELECT *FROM   t_hash_pk_20k join t_range_pk_50k ON t_hash_pk_20k.id = t_range_pk_50k.id
SELECT *FROM   t_range_pk_20k join t_range_pk_50k ON t_range_pk_20k.id = t_range_pk_50k.id
```

![BNLJ slower when inner table is hash sharded (2)](https://github.com/yugabyte/yugabyte-db/assets/564644/39dd9c50-2e9d-4734-bac7-0175404e3835)

Query | YB Plan | YB Cost | YB Time | YB Best Plan | YB Best Time
-- | -- | -- | -- | -- | --
SELECT *FROM   t_hash_pk_20k join t_hash_pk_50k        ON t_hash_pk_20k.id = t_hash_pk_50k.id | YB Batched Nested Loop Join  (cost=0.00..2252.26 rows=20000 width=24)  Join Filter: (t_hash_pk_20k.id = t_hash_pk_50k.id)  ->  Seq Scan on t_hash_pk_20k  (cost=0.00..2000.00 rows=20000 width=12)  ->  Index Scan using t_hash_pk_50k_pkey on t_hash_pk_50k  (cost=0.00..0.11 rows=1 width=12)        Index Cond: (id = ANY (ARRAY[t_hash_pk_20k.id, $1, $2, ..., $1023])) | 2252.26 | 688.57 | Hash Join  (cost=2250.00..7637.50 rows=20000 width=24)  Hash Cond: (t_hash_pk_50k.id = t_hash_pk_20k.id)  ->  YB Seq Scan on t_hash_pk_50k  (cost=0.00..5000.00 rows=50000 width=12)  ->  Hash  (cost=2000.00..2000.00 rows=20000 width=12)        ->  YB Seq Scan on t_hash_pk_20k  (cost=0.00..2000.00 rows=20000 width=12) | 90.7
SELECT *FROM   t_range_pk_20k join t_hash_pk_50k        ON t_range_pk_20k.id = t_hash_pk_50k.id | YB Batched Nested Loop Join  (cost=0.00..2252.26 rows=20000 width=24)  Join Filter: (t_range_pk_20k.id = t_hash_pk_50k.id)  ->  Seq Scan on t_range_pk_20k  (cost=0.00..2000.00 rows=20000 width=12)  ->  Index Scan using t_hash_pk_50k_pkey on t_hash_pk_50k  (cost=0.00..0.11 rows=1 width=12)        Index Cond: (id = ANY (ARRAY[t_range_pk_20k.id, $1, $2, ..., $1023])) | 2252.26 | 671.32 | Hash Join  (cost=2250.00..7637.50 rows=20000 width=24)  Hash Cond: (t_hash_pk_50k.id = t_range_pk_20k.id)  ->  YB Seq Scan on t_hash_pk_50k  (cost=0.00..5000.00 rows=50000 width=12)  ->  Hash  (cost=2000.00..2000.00 rows=20000 width=12)        ->  YB Seq Scan on t_range_pk_20k  (cost=0.00..2000.00 rows=20000 width=12) | 91.41
SELECT *FROM   t_hash_pk_20k join t_range_pk_50k        ON t_hash_pk_20k.id = t_range_pk_50k.id | YB Batched Nested Loop Join  (cost=0.00..2252.26 rows=20000 width=24)  Join Filter: (t_hash_pk_20k.id = t_range_pk_50k.id)  ->  Seq Scan on t_hash_pk_20k  (cost=0.00..2000.00 rows=20000 width=12)  ->  Index Scan using t_range_pk_50k_pkey on t_range_pk_50k  (cost=0.00..0.11 rows=1 width=12)        Index Cond: (id = ANY (ARRAY[t_hash_pk_20k.id, $1, $2, ..., $1023])) | 2252.26 | 79.9 | YB Batched Nested Loop Join  (cost=0.00..2252.26 rows=20000 width=24)  Join Filter: (t_hash_pk_20k.id = t_range_pk_50k.id)  ->  Seq Scan on t_hash_pk_20k  (cost=0.00..2000.00 rows=20000 width=12)  ->  Index Scan using t_range_pk_50k_pkey on t_range_pk_50k  (cost=0.00..0.11 rows=1 width=12)        Index Cond: (id = ANY (ARRAY[t_hash_pk_20k.id, $1, $2, ..., $1023])) | 79.9
SELECT *FROM   t_range_pk_20k join t_range_pk_50k        ON t_range_pk_20k.id = t_range_pk_50k.id | YB Batched Nested Loop Join  (cost=0.00..2252.26 rows=20000 width=24)  Join Filter: (t_range_pk_20k.id = t_range_pk_50k.id)  ->  Seq Scan on t_range_pk_20k  (cost=0.00..2000.00 rows=20000 width=12)  ->  Index Scan using t_range_pk_50k_pkey on t_range_pk_50k  (cost=0.00..0.11 rows=1 width=12)        Index Cond: (id = ANY (ARRAY[t_range_pk_20k.id, $1, $2, ..., $1023])) | 2252.26 | 67.42 | YB Batched Nested Loop Join  (cost=0.00..2252.26 rows=20000 width=24)  Join Filter: (t_range_pk_20k.id = t_range_pk_50k.id)  ->  Seq Scan on t_range_pk_20k  (cost=0.00..2000.00 rows=20000 width=12)  ->  Index Scan using t_range_pk_50k_pkey on t_range_pk_50k  (cost=0.00..0.11 rows=1 width=12)        Index Cond: (id = ANY (ARRAY[t_range_pk_20k.id, $1, $2, ..., $1023])) | 67.42

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6550]: https://yugabyte.atlassian.net/browse/DB-6550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tanujnay112** [comment]
Addressed by d87a628c61d07de4dc31a4f045133b0cd82a1bc1
