### ISSUE TITLE
[Yugabyted][QA][2.18.0.0-b65] Enable EAR command is failing on Mac builds

### ISSUE THREAD

**Issue by ankit-yb** [yugabyte/yugabyte-db#17351]
Jira Link: [DB-6546](https://yugabyte.atlassian.net/browse/DB-6546)
### Description

Steps: 1. Create a cluster with basic configuration using `./bin/yugabyted start` and then execute `./bin/yugabyted configure encrypt_at_rest --enable` and observe it fails with 

`yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/./bin/yugabyted", line 3699, in run
  args.func()
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/./bin/yugabyted", line 948, in configure_encrypt_at_rest
  if not self.is_key_in_all_masters(key_id=key_id):
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/./bin/yugabyted", line 863, in is_key_in_all_masters
  if masters_with_key < len(master_ips):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'list' and 'int'
For more information, check the logs in /Users/ysharmaryugabyte.com/var/logs`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6546]: https://yugabyte.atlassian.net/browse/DB-6546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Code Changes Landed and Backported to 2.18.
