### ISSUE TITLE
[DocDB] Dynamically set the db_block_cache_num_shard_bits based on the number of cores

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#17360]
Jira Link: [DB-6553](https://yugabyte.atlassian.net/browse/DB-6553)
### Description

`db_block_cache_num_shard_bits` is used to specify the number of bits to use for sharding the block cache (defaults to 4 bits). We should auto-tune this gflag on larger core machines - instead of user having to bump this up. Basically, initialize to -1, and if number of cores is less than 16 -- leave it at 4... but other wise use 5 for 17 to 32 cores, 6 for 33-64 cores, and so on.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6553]: https://yugabyte.atlassian.net/browse/DB-6553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by appleconda** [comment]
If the issue is still not resolved I would like to address the issue. I am thinking of writing a function which uses <thread> to get the number of cores and this function will rturn the appropriate shard bits which then can be assigned to db_block_cache_num_shard_bits

**Comment by rthallamko3** [comment]
@appleconda , We already have something in review. If you are interested, I can assign something else to you.

**Comment by rthallamko3** [comment]
Reactivating for 2.18 backport. cc @chinmay291

**Comment by rthallamko3** [comment]
@es1024 , Can you complete the backport for 2.18, as chinmay's internship is done.
