### ISSUE TITLE
[DocDB] flaky test: PgMiniTest.BigInsertWithAbortedIntentsAndRestart

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17394]
Jira Link: [DB-6579](https://yugabyte.atlassian.net/browse/DB-6579)
### Description

Seems to trace to https://github.com/yugabyte/yugabyte-db/commit/3aae60d000142607fc62bb898c1f56ffa8e9a62f

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgMiniTest&fail_tag=all&name=BigInsertWithAbortedIntentsAndRestart&platform=linux

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6579]: https://yugabyte.atlassian.net/browse/DB-6579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@yusong-yan is this still an issue? do you know if it's a legitimate product issue, or just a test only problem?

**Comment by yusong-yan** [comment]
I'm still investigating the issue. I will have a sync with Rob to discuss
this.

I was under the impression that an aborted transaction cannot be committed.
However, from test PgMiniTest.BigInsertWithAbortedIntentsAndRestart , I
observed a RunningTransaction’s last_known_status_ change to ABORTED, then
the server shut down. Later after it gets rebooted, this transaction’s
status gets updated as COMMITTED status
by RunningTransaction::SetLocalCommitData().
