### ISSUE TITLE
[Docs] Colocated tables

### ISSUE THREAD

**Issue by KavyaShivashankar** [yugabyte/yugabyte-db#17430]
### Description

`CREATE TABLE <name> WITH COLOCATION = false` is not supported and gives syntax error

COLOCATION = false has to be enclosed within parantheses for above stmt to work.   `CREATE TABLE <name> <columns> WITH (COLOCATION = false)`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
Please always put at least a link on where the problem is.
