### ISSUE TITLE
[DocDB] Restore fails at import_snapshot phase 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#17457]
Jira Link: [DB-6624](https://yugabyte.atlassian.net/browse/DB-6624)
### Description

On version: **2.18.1.0-b18**
Restore of a backup which was taken on 2.18.0.0-b63 fails with below error
```
java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/yb_backup_ycgdzzxpvudasvvg/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/data/yb-platform/keys/d0d65a40-957d-4849-a225-5791ae09b426/yb-dev-aws-2.pem', '-p', '22', '-q', 'yugabyte@172.161.42.136', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 172.150.29.152:7100,172.151.55.209:7100,172.161.42.136:7100 list_tablet_servers ec12509ee880411ab52a081179b4a947 --never_fsync=false'\"]' returned non-zero exit status 1."}.
```
Test Details:
```
1. Created 100 tables with 100k rows in each on a 2.18.0.0-b63 universe, took a backup 
2. Restored the backup on a 2.18.1.0-b18 universe which only had a single preferred zone(Overall 3 nodes in different region) -> Failed
Note: If nodes are present in the same region it works fine
```
Universe logs:
[172.151.16.54-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/11519768/172.151.16.54-logs.tar.gz)
[172.151.17.201-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/11519769/172.151.17.201-logs.tar.gz)
[172.151.18.49-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/11519770/172.151.18.49-logs.tar.gz)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6624]: https://yugabyte.atlassian.net/browse/DB-6624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@yamen-haddad double checking, will we need to backport this fix to older releases?
