### ISSUE TITLE
[Docs] Fix unterminated comment marker

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#17497]
### Description

`docs/content/preview/quick-start/_index.md` (docs.yugabyte.com/preview/quick-start) has an unterminated comment marker, leading to all text after that point to be commented out.  I trace this back to commit 554528dff4e9aa37cdf088113bc5552531811d65 which is several months ago (Nov 22, 2022).  It hides important details such as `ifconfig` commands for mac.

```
diff --git a/docs/content/preview/quick-start/_index.md b/docs/content/preview/quick-start/_index.md
index fcf1e622ec..1dc841a12a 100644
--- a/docs/content/preview/quick-start/_index.md
+++ b/docs/content/preview/quick-start/_index.md
@@ -285,6 +285,19 @@ yugabyte=#
 
 To load sample data and explore an example using ysqlsh, refer to [Retail Analytics](../sample-data/retail-analytics/).
 
+## Build an application
+
+Applications connect to and interact with YugabyteDB using API client libraries (also known as client drivers). This section shows how to connect applications to your cluster using your favorite programming language.
+
+### Choose your language
+
+{{< readfile "/preview/quick-start-yugabytedb-managed/quick-start-buildapps-include.md" >}}
+
+## Next step
+
+[Explore YugabyteDB](../explore/)
+
+<!--
 ## Build a Java application
 
 The following tutorial shows a small Java application that connects to a YugabyteDB cluster using the topology-aware YugabyteDB JDBC driver and performs basic SQL operations.
@@ -368,7 +381,7 @@ Perform the following to create a sample Java project:
     </dependency>
 
     <!-- https://mvnrepository.com/artifact/com.zaxxer/HikariCP -->
-    <dependency>
+<!--    <dependency>
```

@lucaswangyb is the original reporter.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
@jasonyb The entire section after "Explore YugabyteDB" is deliberately commented out. The quickstart uses 'yugabyted start' to create a single node cluster, so the loopbacks are not needed; the Choose your language section includes multiple language versions of a basic application, replacing the Build a Java application section. I probably should have deleted the commented out part, but maybe left it in as a temporary reference for the Java example used in the Develop - Drivers and ORMs section.
