### ISSUE TITLE
[DocDB] Add memory cleanup to FullCompactionManager

### ISSUE THREAD

**Issue by jmeehan16** [yugabyte/yugabyte-db#17494]
Jira Link: [DB-6652](https://yugabyte.atlassian.net/browse/DB-6652)
### Description

In the case where a tablet peer moves nodes or is deleted, the FullCompactionManager has the potential to hold onto entries that no longer exist. Over time, this is will leak memory. Specifically, the `next_compact_time_per_tablet_` and `tablet_stats_window_` in-memory maps hold entries that may no longer be relevant.

Implement a cleanup function to compare against active TabletPeers and remove any entries that are no longer in TsTabletManager.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6652]: https://yugabyte.atlassian.net/browse/DB-6652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Reactivating for 2.19.0 backport.
