### ISSUE TITLE
[YSQL] pg_stat_user_indexes.idx_scan incremented too early

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#17495]
Jira Link: [DB-6653](https://yugabyte.atlassian.net/browse/DB-6653)
### Description

Commit cf99487cdffb6e08a25e340197d7edf7a29c0e58 supports pg_stat_user_indexes idx_scan column for lsm index, but it deviates from the status quo: rather than incrementing on amgettuple or amgetbitmap, it increments on ambeginscan, which is earlier.  In case an error is hit between ambeginscan and amgettuple/amgetbitmap, it would increment the stat when the expectation is to not.  An example is the "cannot use more than %d predicates in a table or index scan" error message called by amrescan, which is in between ambeginscan and amgettuple/amgetbitmap.  I believe the stat bump for lsm should be moved to `ybcingettuple` using `!ybScan->is_exec_done` as a marker for whether it is the first time we ran `ybcingettuple`, similar to how `btgettuple` uses `!BTScanPosIsValid(so->currPos)`.

Unpolished repro that hits that error:

```sh
bin/ysqlsh -c "create table many ($(for i in {1..99}; do echo -n "c$i int,"; done) k int primary key)"
bin/ysqlsh -c "create index on many ($(for i in {1..30}; do echo -n "c$i,"; done) c1 asc)"
bin/ysqlsh -c "select * from many where $(for i in {1..30}; do echo -n "c$i = 1 and c$i < 2 and c$i > 0 and "; done) true"
```

```
ERROR:  cannot use more than 64 predicates in a table or index scan
```

Each time the erroring `select` is run, observe the `idx_scan` count go up in `pg_stat_user_indexes`: `select * from pg_stat_user_indexes;`.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6653]: https://yugabyte.atlassian.net/browse/DB-6653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by akash-ind** [comment]
Hi Team, 
Can anyone assign me this issue?

**Comment by jasonyb** [comment]
> Hi Team, Can anyone assign me this issue?

@akash-ind Feel free to submit a PR.  It's open for anyone, so no assignment.

**Comment by davixiao** [comment]
Left a PR, let me know if it works!
