### ISSUE TITLE
[DocDB] Test PgsqlCreateTable in YbAdminSnapshotSchedule always fails for colocated DBs in 2.14

### ISSUE THREAD

**Issue by yamen-haddad** [yugabyte/yugabyte-db#17500]
Jira Link: [DB-6657](https://yugabyte.atlassian.net/browse/DB-6657)
### Description

The test `YbAdminSnapshotScheduleTestWithYsqlColocatedParam.PgsqlCreateTable` is always failing in the case of colocated databases. The failure is due to a time out while the test is waiting for the restore to complete. The test waits for all the tablets to be market as hidden, which works fine for non colocated database. However, for colocated databases, the tablet of the parent table `id.colocated.parent` will never be marked as hidden. The bug only exists in 2.14 as the test has been modified in newer releases.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6657]: https://yugabyte.atlassian.net/browse/DB-6657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@yamen-haddad , Can we close this defect now?
