### ISSUE TITLE
[DocDB] flaky test: RaftConsensusITest.TestExpiredOperationWithSchemaChange in gcc

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17526]
Jira Link: [DB-6679](https://yugabyte.atlassian.net/browse/DB-6679)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=RaftConsensusITest&fail_tag=all&name=TestExpiredOperationWithSchemaChange&platform=linux

seems to trace to https://github.com/yugabyte/yugabyte-db/commit/d5552063ae6138433056dc1e5c642bab9f94b5d4, when introduced

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6679]: https://yugabyte.atlassian.net/browse/DB-6679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@yusong-yan was your original diff backported? if so, would it make sense to also backport this test fix, so we reduce noise?

**Comment by yusong-yan** [comment]
Yes, I'm backporting this with the original diff to 2.18 and 2.16

**Comment by rthallamko3** [comment]
Reopening for the 2.16 backport.
