### ISSUE TITLE
[CDCSDK] Fix delay in cdc in case of aborted transactions

### ISSUE THREAD

**Issue by nishantwrp** [yugabyte/yugabyte-db#17546]
With the consistent streaming fix for cdc, we observe a delay in streaming in case there are aborted transactions. This is because we use the cached status of transactions in `transactions_` to calculate the consistent stream safe time. For aborted transactions this is not updated immediately, so we do not stream any records until the cache gets updated.

After this issue is fixed, we can safely enable the flag `cdc_enable_consistent_records` in test `TestCDCSDKConsistentStreamWithAbortedTransactions`.

**Comment by adithya-yb** [comment]
Tracked through: https://github.com/yugabyte/yugabyte-db/issues/18445
