### ISSUE TITLE
[YSQL] Incorrectly picking local_limit during paging read

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#17558]
Jira Link: [DB-6704](https://yugabyte.atlassian.net/browse/DB-6704)
### Description

TO BE UPDATED

#### Investigation
This started as an investigation into a test failure:

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressTypesNumeric&fail_tag=all&name=testPgRegressTypes&platform=all

Seems like most failures are on mac build so there may be something mac-specific in the test ouput.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6704]: https://yugabyte.atlassian.net/browse/DB-6704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Passing to @pkj415 for now, for last mile investigation into some increased test failures on `org.yb.pgsql.TestPgTransparentRestarts.*`

**Comment by rthallamko3** [comment]
@pkj415 , Are the failures in org.yb.pgsql.TestPgTransparentRestarts.* related to the above fix? Do you know if we can backport the commit [428b1c5](https://github.com/yugabyte/yugabyte-db/commit/428b1c508527a8f64ae54e0e04ff1063156b5e57) safely to stable branches, all the way to 2.14?
