### ISSUE TITLE
[DocDB] Improve Leader Blacklisting speed

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#17560]
Jira Link: [DB-6706](https://yugabyte.atlassian.net/browse/DB-6706)
### Description

Currently the defaults for `load_balancer_max_concurrent_moves_per_table` and `load_balancer_max_concurrent_moves` are set very conservatives to ensure that leader blacklisting operation does not adversely impact the workload due to leader moves.

However these significantly slow down rolling upgrades. These also do not account for cases where moves might be on completely disjoint set of nodes/tables and therefore we could let a lot more of these proceed in parallel.

The goal is to increase these thresholds and optimize the leader blacklisting speed

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6706]: https://yugabyte.atlassian.net/browse/DB-6706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SrivastavaAnubhav** [comment]
**Images referenced in commit description**
2-core leader move times
![image](https://github.com/yugabyte/yugabyte-db/assets/17299377/c3f62354-a122-4787-8bb6-8aa9c8dbd6e3)

4-core leader move times
![image](https://github.com/yugabyte/yugabyte-db/assets/17299377/81e3fa6d-0c23-46c8-93af-1aca68bfea66)

Single availability zone leader moves
![image](https://github.com/yugabyte/yugabyte-db/assets/17299377/98fc3b6e-e047-41a9-a293-7d256552c62b)

Geodistributed leader moves
![image](https://github.com/yugabyte/yugabyte-db/assets/17299377/24bfaeeb-f06e-4554-94db-30558056a0f7)
