### ISSUE TITLE
[DocDB] Reuse computed safe-time instead of making a duplicate call.

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#17581]
Jira Link: [DB-6724](https://yugabyte.atlassian.net/browse/DB-6724)
### Description

```
    HybridTime current_safe_time = HybridTime::kMin;
    if (IsPgsqlFollowerReadAtAFollower()) {
      auto current_safe_time = VERIFY_RESULT(abstract_tablet_->SafeTime(
          require_lease_, HybridTime::kMin, context_.GetClientDeadline()));
      if (GetAtomicFlag(&FLAGS_ysql_follower_reads_avoid_waiting_for_safe_time) &&
          current_safe_time < read_time_.read) {
        // We are given a read time. However, for Follower reads, it may be better
        // to redirect the query to the Leader instead of waiting on it.
        return STATUS(IllegalState, "Requested read time is not safe at this follower.");
      }
    }
    safe_ht_to_read_ =
        (current_safe_time > read_time_.read
             ? current_safe_time
             : VERIFY_RESULT(abstract_tablet_->SafeTime(
                   require_lease_, read_time_.read, context_.GetClientDeadline())));
```
current_safe_time inside the block should be used outside the block to prevent making another call to SafeTime

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6724]: https://yugabyte.atlassian.net/browse/DB-6724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Since it looks like a performance fix, closing this out without additional backport labels.
