### ISSUE TITLE
[DocDB] automatic tablet splitting can create too many tablets, failing later backups

### ISSUE THREAD

**Issue by druzac** [yugabyte/yugabyte-db#17603]
Jira Link: [DB-6734](https://yugabyte.atlassian.net/browse/DB-6734)
### Description

Automatic tablet splitting can schedule too many splits, breaking the backup/restore feature on the same cluster.

```
# create table with 3 tablets
I0530 09:36:57.933198 62394 catalog_manager.cc:3571] CreateTable from <ip>:
name: "non_colocated_employees"
num_tablets: 3
table_id: "0000400600003000800000000000406d"

# split table 156 times:
I0530 09:51:15.508164 98225 catalog_manager.cc:2899] Starting tablet split: 0147e96710194a4c97e25c3ea9af7949 (table non_colocated_employees [id=0000400600003000800000000000406d]) by partition key: 4A69
...

# when performing the restore, fail the create table request because it requests 159 tablets which is over the cluster limit:
I0530 11:38:45.815685 62350 catalog_manager.cc:3571] CreateTable from <ip>:
name: "non_colocated_employees"
num_tablets: 159
table_id: "000040c90000300080000000000040d7"
I0530 11:38:45.815843 62350 partition.cc:631] Creating partitions with num_tablets: 159
I0530 11:38:45.815853 62350 catalog_manager.cc:11610] Set number of tablets: 159
W0530 11:38:45.815866 62350 catalog_manager.cc:3549] The requested number of tablets (159) is over the permitted maximum (150)
```

This warning message indicates the create table request fails. `CheckNumReplicas` fails the request if the number of tablets is over the number of configured tablets per tserver, multipled by the number of tservers: 
`FLAGS_max_create_tablets_per_ts * ts_descs.size()`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6734]: https://yugabyte.atlassian.net/browse/DB-6734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@druzac , Given that the user can manually split the tablet too. Shouldn't restore ignore tablet count limits and enforce that for post-restore time? cc @lingamsandeep , @bmatican

**Comment by SrivastavaAnubhav** [comment]
It looks like `FLAGS_max_create_tablets_per_ts` is meant to limit the number of tablets at creation time, but not the total number of tablets, which is limited by `FLAGS_tablet_split_limit_per_table`. I think restore should be allowed to bypass the `FLAGS_max_create_tablets_per_ts` limit.

**Comment by SrivastavaAnubhav** [comment]
After some discussion, we decided to limit automatic splitting by `FLAGS_max_create_tablets_per_ts` and remove the fixed limit on `FLAGS_tablet_split_limit_per_table`.
