### ISSUE TITLE
[YSQL] Avoid n^2 complexity when loading catalog cache with default column values

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#17621]
Jira Link: [DB-6747](https://yugabyte.atlassian.net/browse/DB-6747)
### Description

Currently, when loading the catalog cache, we enumerate `pg_attribute` (in `YBUpdateRelationsAttributes`). Per table, we then enumerate `pg_attrdef` (in `AttrDefaultFetch`), filtered by `adrelid` (table oid), to fetch the default value. The filter is done at ysql layer rather than being pushed down to doc db (in `ybc_getnext_heaptuple`). So, we effectively end up scanning all rows of `pg_attrdef`. Assuming 10k tables with 5 default columns each, this ends up being  (5 columns * 10000 tables) per outer loop (10000 tables).

We should avoid this n^2 complexity when loading columns with default values, as it may consume significant CPU.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6747]: https://yugabyte.atlassian.net/browse/DB-6747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SteveXiSong** [comment]
Duplicated to #17509

**Comment by tverona1** [comment]
Duplicate of #17509 .
