### ISSUE TITLE
[YSQL] DROP CONSTRAINT IF EXISTS parses but isn't implemented correctly

### ISSUE THREAD

**Issue by lukaseder** [yugabyte/yugabyte-db#17659]
Jira Link: [DB-6777](https://yugabyte.atlassian.net/browse/DB-6777)
### Description

Try this:

```sql
create table t (i int, constraint u unique (i));
alter table t drop constraint if exists u;
alter table t drop constraint if exists u;
```

The second execution should simply be ignored, but it fails with:

> [42704]: ERROR: constraint "u" for table "t" does not exist

If it's not implemented, I think it shouldn't parse

I'm using the latest version from docker: https://hub.docker.com/r/yugabytedb/yugabyte:

```sql
select version();
```

Producing:

```
PostgreSQL 11.2-YB-2.18.0.1-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.3 (https://github.com/yugabyte/llvm-project.git 0b8d1183745fd3998d8beffeec8cbe99c1b20529), 64-bit
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6777]: https://yugabyte.atlassian.net/browse/DB-6777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Resolved with commit 831e600
