### ISSUE TITLE
[DocDB] Enable flag partition_vtable_cache_refresh_secs by default

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#17656]
Jira Link: [DB-6774](https://yugabyte.atlassian.net/browse/DB-6774)
### Description

The flag `partition_vtable_cache_refresh_secs` introduced in 2.4 is disabled by default at present. When the cluster has too many tablets and there is a churn to the leader/tablet location, with this flag being disabled, it can lead to a significant increase in the latency of master queries eventually causing the cluster to get into an unstable state.

CC: @rao-vasireddy , @rthallamko3 , @Arjun-yb , @agsh-yb, @nmantrav2 , @m-iancu  

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6774]: https://yugabyte.atlassian.net/browse/DB-6774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Fixed and enabled as part of #17683
