### ISSUE TITLE
[yugaware] Import universe does not allow custom ports

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1766]
When using the import universe feature, we have some hardcoded checks in the code for explicitly having the defaults for master RPC on 7100 and tserver RPC on 9100.

We've also hit this issue trying to demo Import in a customer setup..

cc @ramkumarvs @rkarthik007 @Arnav15

**Comment by WesleyW** [comment]
fixed in 98dcc5ba3cbcfdca5ee437e445b266bb06595384
