### ISSUE TITLE
Make sure we abort the transaction in case commit failed

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1767]
Jira Link: [DB-2351](https://yugabyte.atlassian.net/browse/DB-2351)
YBTransaction::Commit currently just returns the failure state to the caller. We need to make sure we also try to abort a transaction that failed to commit, so that all the intents are cleaned up.

**Comment by bmatican** [comment]
Not sure if this is still an issue, but adding some folks for tracking / FYI

**Comment by es1024** [comment]
This was fixed in 70e3768a2acb2826f6c735ac8eb95c0fdb718b1d.
