### ISSUE TITLE
[YCQL] Support CONTAINS KEY expression for collections

### ISSUE THREAD

**Issue by RahulBiju315** [yugabyte/yugabyte-db#17676]
Jira Link: [DB-6788](https://yugabyte.atlassian.net/browse/DB-6788)
### Description

Cassandra supports an expression `CONTAINS KEY` which can check if a MAP contains a particular key or not.

**Syntax**
`SELECT <select_clause> FROM <table_name> WHERE <column_name> CONTAINS KEY <value>`
Here `<column_name>` must be of MAP datatype and `<value>` must have the same type as the key of the MAP

**Example:**
```
CREATE TABLE k1.t1 (a INT PRIMARY KEY, b MAP<INT, INT>);
INSERT INTO k1.t1(a, b) VALUES (1, {1:1, 2:2});
INSERT INTO k1.t1(a, b) VALUES (2, {1:3});
INSERT INTO k1.t1(a, b) VALUES (3, {2:4});
SELECT * FROM k1.t1 WHERE b CONTAINS KEY 2;
```

The above query will return:
```
a, b
1, {1:1, 2:2}
3, {2:4}
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6788]: https://yugabyte.atlassian.net/browse/DB-6788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dr0pdb** [comment]
Reopening for backports
