### ISSUE TITLE
[DocDB] Large amount of memory not reflected in memtrackers when running CassandraBatchKeyValue

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#17726]
Jira Link: [DB-6825](https://yugabyte.atlassian.net/browse/DB-6825)
### Description

Build code as of commit: abee6b20cf2a254519b06e9f088ae51fecc87100 (debug build) with https://phorge.dev.yugabyte.com/D26019 on top of it.

Run workload:

java -jar ~/yb-sample-apps.jar  --workload CassandraBatchKeyValue --nodes 127.0.0.1:9042 --num_threads_read 16 --num_threads_write 16 --num_reads 1000000000000 --num_writes 1000000000000

Look at memtrackers:

http://localhost:9000/mem-trackers

<img width="2593" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/552936/f2f205cc-ccbf-4b61-9ae3-c860214f3a7c">

As text: https://gist.githubusercontent.com/mbautin/d227720ac0f36b6c86cce41201dbfbb7/raw

Notice the huge discrepancy between root memtracker (calculated based on tcmalloc stats, not including pagecache free lists or unmapped free lists) and server root tracker.

Capture pprof: http://localhost:9000/pprof/heap?seconds=2

Top allocated call stack is frequently a write buffer : https://gist.githubusercontent.com/mbautin/bbce7ffe5dc5d254129c8bb45d293a25/raw

Sometimes it is a RocksDB arena-wrapped iterator: https://gist.githubusercontent.com/mbautin/b85434988e9c9b95d75cbdd722977ae6/raw

(The above code includes a local patch to use libbacktrace for symbolization).

These profiles include allocations but do not include deallocations. We need to find a way to subtract deallocations to find what data stays in memory over time.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6825]: https://yugabyte.atlassian.net/browse/DB-6825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
>These profiles include allocations but do not include deallocations. We need to find a way to subtract deallocations to find what data stays in memory over time.

@SrivastavaAnubhav I thought the new sampled allocation mode would do just that? Can you share with @mbautin the flags to enable and configure it?

**Comment by mbautin** [comment]
Yes, only_growth worked for me.

**Comment by rthallamko3** [comment]
@mbautin , Were you planning additional changes to this? If not, can we close this GH?
