### ISSUE TITLE
[YSQL] Update pgbench to create primary keys for tables up front

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1774]
YB does not allow primary keys to be added to tables after they are created.
pgdump currently does the following:
```
create table pgbench_branches ...
create table pgbench_tellers ...
create table pgbench_accounts ...
alter table pgbench_branches add primary key (bid)
alter table pgbench_tellers add primary key (tid)
alter table pgbench_accounts add primary key (aid)
```
This does not work with YB.
We should change pgbench.c to setup PK while creating the table itself.

**Comment by ndeodhar** [comment]
@kmuthukk FYI.

**Comment by kmuthukk** [comment]
These might be the places where it is doing DDLs, that need slight changes:

https://github.com/YugaByte/yugabyte-db/blob/3e3002ebdcd52a4f6224281d185732af2673b072/src/postgres/src/bin/pgbench/pgbench.c#L3512

and later doing this:

https://github.com/YugaByte/yugabyte-db/blob/3e3002ebdcd52a4f6224281d185732af2673b072/src/postgres/src/bin/pgbench/pgbench.c#L3732
https://github.com/YugaByte/yugabyte-db/blob/3e3002ebdcd52a4f6224281d185732af2673b072/src/postgres/src/bin/pgbench/pgbench.c#L3767

**Comment by nspiegelberg** [comment]
https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1562817662244400?thread_ts=1562720912.221200&cid=CG0KQF0GG
