### ISSUE TITLE
[DocDB] Do not retain weak pointers to InboundCall in ServicePool until the deadline

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#17759]
Jira Link: [DB-6855](https://yugabyte.atlassian.net/browse/DB-6855)
### Description

Related to the memory leak seen in #17203. ServicePool should destruct weak pointers to InboundCalls that have already completed and not keep them around until the deadline, so we can safely use make_shared to allocate InboundCall objects.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6855]: https://yugabyte.atlassian.net/browse/DB-6855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
@mbautin @rthallamko3 Was this meant to be closed?

The commit landed only refers to a work around (11726).
