### ISSUE TITLE
[YSQL] ALTER TABLE ALTER COLUMN TYPE fails when on range key table with split options

### ISSUE THREAD

**Issue by fizaaluthra** [yugabyte/yugabyte-db#17756]
Jira Link: [DB-6853](https://yugabyte.atlassian.net/browse/DB-6853)
### Description

yugabyte=# CREATE TABLE x (key char, notkey varchar(10), PRIMARY KEY (key ASC)) SPLIT AT VALUES (('m'));
yugabyte=# ALTER TABLE x ALTER COLUMN notkey TYPE varchar(1);
ERROR:  HASH columns must be present to split by number of tablets

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6853]: https://yugabyte.atlassian.net/browse/DB-6853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by agsh-yb** [comment]
Reoping issue due to #19382
