### ISSUE TITLE
[DocDB] Tablet failed due to bad magic number

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#17760]
Jira Link: [DB-6856](https://yugabyte.atlassian.net/browse/DB-6856)
### Description

If an issue occurs where a bad magic number is written to the header of a WAL segment (e.g. due to a tserver crash mid-write), subsequent attempts to bootstrap the affected tablet will fail.

If this affects replicas of the same tablet on multiple nodes, the tablet will be rendered leaderless, causing an outage for the affected tablet.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6856]: https://yugabyte.atlassian.net/browse/DB-6856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
#17592 tracks the backport. Closing this.
