### ISSUE TITLE
[YCQL] Unit test TestCQLServiceWithCassAuth.TestReadSystemTableAuthenticated is failing

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#17779]
Jira Link: [DB-6873](https://yugabyte.atlassian.net/browse/DB-6873)
### Description

**Test**: `TestCQLServiceWithCassAuth.TestReadSystemTableAuthenticated`
**Stability**: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=TestCQLServiceWithCassAuth&fail_tag=all&name=TestReadSystemTableAuthenticated&platform=linux
**Jenkins**
https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang15-tsan/1534/artifact/build/tsan-clang15-dynamic-ninja/yb-test-logs/tests-cqlserver__cqlserver-test/TestCQLServiceWithCassAuth_TestReadSystemTableAuthenticated.log

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6873]: https://yugabyte.atlassian.net/browse/DB-6873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hbhanawat** [comment]
https://github.com/yugabyte/yugabyte-db/commit/1100f04cb12825a94f10ce2653a27d9b952cc3c7
