### ISSUE TITLE
[yugaware] Add ability to get a client cert when using TLS

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1778]
We should have a clear UI `Connect` option when using TLS for a client to be able to obtain a cert to connect to their cluster with.

cc @rkarthik007 @ramkumarvs @Arnav15 @yb-andrew

**Comment by bmatican** [comment]
Passing to @yb-andrew as he's looking at a couple of Edit related issues.

**Comment by streddy-yb** [comment]
This was added in 2.2 release.
