### ISSUE TITLE
[DocDB] initdb fails with SIGSEGV on GCC 11

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#17787]
Jira Link: [DB-6878](https://yugabyte.atlassian.net/browse/DB-6878)
### Description

https://gist.githubusercontent.com/mbautin/aa584887a306277ca9adb89ce9aa3e7b/raw

Full initdb log: https://[gist.githubusercontent.com/mbautin/d5bd8c77546442176aa159c90ade6713/raw](https://gist.githubusercontent.com/mbautin/d5bd8c77546442176aa159c90ade6713/raw)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6878]: https://yugabyte.atlassian.net/browse/DB-6878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Would have saved me some time if the problem commit were mentioned.  It seems to be 44cd82dd4ab631999dc8ef77d8b77bd4cfbf45af.

**Comment by mbautin** [comment]
@jasonyb I think the build was broken as part of 44c7e12f0fe0287f136aebf8c4f605f1bbc08073 and @dr0pdb fixed it in e56c0eeeb7a703f9fab8be69fdd9f083bccb36bd
