### ISSUE TITLE
[YSQL] Make IncreaseMutationCounts and GetTableMutationCounts thread-safe

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#17782]
Jira Link: [DB-6876](https://yugabyte.atlassian.net/browse/DB-6876)
### Description

The handling in `IncreaseMutationCounts()` and `GetTableMutationCounts()` are not thread-safe. We need to add synchronization around access to the mutation counter map.

Also, move this from YBTransaction to `struct SessionData` as per slack discussion with @d-uspenskiy and @spolitov. Maybe something like this -
```
struct SessionData {
    client::YBSessionPtr session;
    std::pair<client::YBTransactionPtr, MutationCounters> transaction_info;
  };
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6876]: https://yugabyte.atlassian.net/browse/DB-6876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Resolved by commit ed60b30
