### ISSUE TITLE
[YSQL] Connecting to the ysql shell of a universe which has errored during node upgrade returns "ysqlsh: FATAL:  Invalid number of bytes for a INT64: 0 vs 8"

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#17844]
Jira Link: [DB-6932](https://yugabyte.atlassian.net/browse/DB-6932)
### Description

- Connect to the YSQl shell of a universe which has failed during node upgrade(2.19.1.0-b149->2.19.1.0-b159)
**Issue:**
```
[yugabyte@ip-172-151-27-57 master]$ pwd
/home/yugabyte/master
[yugabyte@ip-172-151-27-57 master]$ ./bin/ysqlsh -h 172.151.27.57
ysqlsh: FATAL:  Invalid number of bytes for a INT64: 0 vs 8
[yugabyte@ip-172-151-27-57 master]$ ./bin/ysqlsh -h 172.151.55.246
ysqlsh: FATAL:  Invalid number of bytes for a INT64: 0 vs 8
[yugabyte@ip-172-151-27-57 master]$ ./bin/ysqlsh -h 172.151.41.133
ysqlsh: FATAL:  Invalid number of bytes for a INT64: 0 vs 8
```
This is seen on trying to connect to any node in the universe.
Seen in https://portal.dev.yugabyte.com/universes/a85b5b01-6e0b-4a24-b088-478dafff94e4/overview 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6932]: https://yugabyte.atlassian.net/browse/DB-6932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nmantrav2** [comment]
Universe upgrade from 2.19.1.0-b149 to 2.19.1.0-b159 failed and connectivity alerts "Error executing command timeout 20 bash -c 'set -o pipefail; /home/yugabyte/tserver/bin/ysqlsh -h /tmp/.yb.172.151.27.57:5433 -p 5433 -U yugabyte -d system_platform -c "\\conninfo"': ysqlsh: FATAL: Invalid number of bytes for a INT64: 0 vs 8" are being thrown.

**Comment by rthallamko3** [comment]
Per Sergei, Since the tombstone check was removed in pretty recent diff: c307d13d1b64bd6d100240898972fe827c128a57, this need not be backported to 2.16 or 2.18 branches.
