### ISSUE TITLE
[YCQL] Unit test: org.yb.cql.TestIndex.testOptimizedIndexUpdate_Transactional is flaky

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#17850]
Jira Link: [DB-6938](https://yugabyte.atlassian.net/browse/DB-6938)
### Description

Test: `org.yb.cql.TestIndex.testOptimizedIndexUpdate_Transactional`

Analyse trends: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.cql.TestIndex&name=testOptimizedIndexUpdate_Transactional
ERROR: `org.yb.client.MasterErrorException: Server[YB Master - 127.150.48.238:30358] NOT_FOUND[code 1]: Table cql_test_keyspace.i7 not found: OBJECT_NOT_FOUND`
**Jenkins**: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang16-debug-aarch64/194/testReport/junit/org.yb.cql/TestIndex/testOptimizedIndexUpdate_Transactional/

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6938]: https://yugabyte.atlassian.net/browse/DB-6938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.cql.TestIndex&name=testOptimizedIndexUpdate_Transactional&num_commits=50

Closing as there are no failures in past 50 commits (400 runs across 8 builds).
