### ISSUE TITLE
[YSQL] The number of rows that could be fetched by setting a "prefetch size" seems to be much lesser than the actual rows read.

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#17852]
Jira Link: [DB-6940](https://yugabyte.atlassian.net/browse/DB-6940)
### Description

There seems to be some overhead of reading a row in a prefetch size based buffer.

Below table has only one column of bigint type so an average size of 1row of bigint type will be 8bytes and for a table with 10k rows the total size should be 80KB. I validated above using below commands
```
yugabyte=# select pg_size_pretty(sum(pg_column_size(col_bigint_id_1))) as total_size,pg_size_pretty(avg(pg_column_size(col_bigint_id_1))) as average_size from pkey_rangescan_fullTable_1column_1;
total_size |  average_size
------------+--------------------------
78 kB | 8.0000000000000000 bytes
(1 row)

yugabyte=# select count(*) from pkey_rangescan_fullTable_1column_1;
count
-------
10000
(1 row)
```
Based on above, 1M rows will result in less than 8MB so to read all 1M rows should result in 

- 8 RPCs with a prefetch size of 1MB but actually 27 RPCs are required 
- 1 RPC with prefect size of 10MB but actually 3 RPCs are required 

Similar observations are for reading 1M rows from table with 10columns and 100columns
<img width="766" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/85676531/d66c8471-1463-4722-9b89-cf043694436f">

For plan and query details refer to scanG7 workload from below reports

- http://perf.dev.yugabyte.com/report/view/W3sibmFtZSI6IllCUl9EZWZhdWx0IiwidGVzdF9pZCI6IjE4OTk4MDIiLCJpc0Jhc2VsaW5lIjp0cnVlfSx7Im5hbWUiOiJQcmVmZXRjaF8xTSIsInRlc3RfaWQiOiIxOTAxMDAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9LHsibmFtZSI6IlByZWZldGNoXzEwTSIsInRlc3RfaWQiOiIxOTAxMjAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9XQ==

- http://perf.dev.yugabyte.com/report/view/W3sibmFtZSI6IllCQ19ERUZBVUxUIiwidGVzdF9pZCI6IjE4OTkxMDIiLCJpc0Jhc2VsaW5lIjp0cnVlfSx7Im5hbWUiOiJQcmVmZXRjaF8xTSIsInRlc3RfaWQiOiIxODc2NDAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9LHsibmFtZSI6IlByZWZldGNoXzEwTSIsInRlc3RfaWQiOiIxOTAxNDAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9XQ==

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6940]: https://yugabyte.atlassian.net/browse/DB-6940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment]
On ysqlsh: 
```sql
CREATE TABLE t (b bigint) SPLIT INTO 1 TABLETS;
INSERT INTO t SELECT g FROM generate_series(1, 1000000) g;
SELECT 
	pg_size_pretty(sum(pg_column_size(b))) AS total_size,
	pg_size_pretty(avg(pg_column_size(b))) AS average_size,
	COUNT(*) AS count
FROM t;
 total_size |       average_size       |  count
------------+--------------------------+---------
 7813 kB    | 8.0000000000000000 bytes | 1000000
(1 row)

CREATE INDEX ON t(b ASC);

SET yb_fetch_row_limit TO 0;
SET yb_fetch_size_limit TO '1MB';
EXPLAIN (ANALYZE, DIST) SELECT * FROM t WHERE b > 1; -- 9 RPCs (should be 8, but not hugely off)
SET yb_fetch_size_limit TO '10MB';
EXPLAIN (ANALYZE, DIST) SELECT * FROM t WHERE b > 1; -- 1 RPC
```

If the table is created without the `SPLIT INTO 1 TABLETS` clause, I get 10 and 2 RPCs for the two scans, respectively. 

I'm guessing this was fixed by D28206 / 2375a8e930e4a7047c78347371352947447302e1 (see the changes to `yb_fetch_limits.out` for an example). 

Also see the [report](http://perf.dev.yugabyte.com/report/view/W3sibmFtZSI6InRlc3QtaWQiLCJpc0Jhc2VsaW5lIjp0cnVlLCJ0ZXN0X2lkIjoyNzQ2MjAyfV0=) created from a recent release, testing a 1MB size limit. It shows 9, 86, 859 RPCs for 1, 10, 100 columns, which is much closer to the theoretical perfect.
