### ISSUE TITLE
[YSQL] Latency increases when yb_fetch_size_limit is increased from 1MB to 10MB

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#17851]
Jira Link: [DB-6939](https://yugabyte.atlassian.net/browse/DB-6939)
### Description

**ISSUE1**
To fetch 1M rows with with prefetch size of
1. 1MB resulted in 9 RPC requests with a latency of 279.99ms
2. Where as with 10MB prefetch size only 1 RPC request was required with latency of 444.99ms.
3. Even though with 10MB prefetch size resulted in reduced RPCs to 1 from 9 for 1MB prefetch size the Storage Read Execution Time for single RPC of 10MB is higher than 9 RPC requests of 1MB.

**ISSUE2**
Single RPCs is required to fetch 1M rows with prefetch size set to either 10M or 1GB but the storage read latency for 10M prefetch buffer is 444ms where as for 1GB is 502ms.

<img width="1327" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/85676531/fd5d5188-eed3-4e83-966c-0d1cf8fe85d6">

Microbenchmark reports:

Scan Regular tables | http://perf.dev.yugabyte.com/report/view/W3sibmFtZSI6IllCUl9EZWZhdWx0IiwidGVzdF9pZCI6IjE4OTk4MDIiLCJpc0Jhc2VsaW5lIjp0cnVlfSx7Im5hbWUiOiJQcmVmZXRjaF8xTSIsInRlc3RfaWQiOiIxOTAxMDAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9LHsibmFtZSI6IlByZWZldGNoXzEwTSIsInRlc3RfaWQiOiIxOTAxMjAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9XQ==
-- | --
Scan Colocated tables | http://perf.dev.yugabyte.com/report/view/W3sibmFtZSI6IllCQ19ERUZBVUxUIiwidGVzdF9pZCI6IjE4OTkxMDIiLCJpc0Jhc2VsaW5lIjp0cnVlfSx7Im5hbWUiOiJQcmVmZXRjaF8xTSIsInRlc3RfaWQiOiIxODc2NDAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9LHsibmFtZSI6IlByZWZldGNoXzEwTSIsInRlc3RfaWQiOiIxOTAxNDAyIiwiaXNCYXNlbGluZSI6ZmFsc2V9XQ==

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6939]: https://yugabyte.atlassian.net/browse/DB-6939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment]
**Issue 1 Local Repro**

```sql
CREATE TABLE t (b bigint);
INSERT INTO t SELECT g FROM generate_series(1, 1000000) g;
SELECT 
	pg_size_pretty(sum(pg_column_size(b))) AS total_size,
	pg_size_pretty(avg(pg_column_size(b))) AS average_size,
	COUNT(*) AS count
FROM t;

SET yb_fetch_row_limit TO 0;
SET yb_fetch_size_limit TO '1MB';
EXPLAIN (ANALYZE, DIST) SELECT * FROM t;
SET yb_fetch_size_limit TO '10MB';
EXPLAIN (ANALYZE, DIST) SELECT * FROM t;
```

With the 1MB limit, I consistently get 330-340ms latency. With the 10MB limit, I consistently get 380-390ms latency, even though there's 1 RPC instead of 9. I'll look into this further. 

**Issue 2**
Doesn't reproduce for me locally. Using the perf tool, I see [identical performance](http://perf.dev.yugabyte.com/report/view/W3sibmFtZSI6IkRlZmF1bHQiLCJ0ZXN0X2lkIjoiMjczMDAwMiIsImlzQmFzZWxpbmUiOnRydWV9LHsibmFtZSI6IjFNQiBTaXplIExpbWl0IiwidGVzdF9pZCI6IjI3NDU5MDIiLCJpc0Jhc2VsaW5lIjpmYWxzZX0seyJuYW1lIjoiMTBNQiBTaXplIExpbWl0IiwidGVzdF9pZCI6IjI3Mjk4MDIiLCJpc0Jhc2VsaW5lIjpmYWxzZX0seyJuYW1lIjoiMUdCIFNpemUgTGltaXQiLCJ0ZXN0X2lkIjoiMjc0NjQwMiIsImlzQmFzZWxpbmUiOmZhbHNlfV0=) for 1M rows between 10MB and 1GB fetch size.

**Comment by timothy-e** [comment]
```
yugabyte=# SET yb_fetch_size_limit = '1MB';
SET
yugabyte=# EXPLAIN (ANALYZE, DIST, DEBUG) SELECT * FROM t;
                                               QUERY PLAN
---------------------------------------------------------------------------------------------------------
 Seq Scan on t  (cost=0.00..100.00 rows=1000 width=8) (actual time=52.431..132.253 rows=1000000 loops=1)
   Storage Table Read Requests: 10
   Storage Table Read Execution Time: 94.308 ms
   Metric rocksdb_number_db_seek: 10.000
   Metric rocksdb_number_db_next: 1000008.000
   Metric rocksdb_number_db_seek_found: 10.000
   Metric rocksdb_number_db_next_found: 1000006.000
   Metric rocksdb_iter_bytes_read: 73,822,644.000
   Metric docdb_keys_found: 1000008.000
 Planning Time: 0.079 ms
 Execution Time: 245.944 ms
 Storage Read Requests: 10
 Storage Read Execution Time: 94.308 ms
 Storage Write Requests: 0.000
 Catalog Read Requests: 0
 Catalog Write Requests: 0.000
 Storage Flush Requests: 0
 Metric rocksdb_number_db_seek: 10
 Metric rocksdb_number_db_next: 1000008
 Metric rocksdb_number_db_seek_found: 10
 Metric rocksdb_number_db_next_found: 1000006
 Metric rocksdb_iter_bytes_read: 73822644
 Metric docdb_keys_found: 1000008
 Storage Execution Time: 94.308 ms
 Peak Memory Usage: 8 kB
(25 rows)

yugabyte=# SET yb_fetch_size_limit = '10MB';
SET
yugabyte=# EXPLAIN (ANALYZE, DIST, DEBUG) SELECT * FROM t;
                                                QUERY PLAN
----------------------------------------------------------------------------------------------------------
 Seq Scan on t  (cost=0.00..100.00 rows=1000 width=8) (actual time=121.820..175.822 rows=1000000 loops=1)
   Storage Table Read Requests: 2
   Storage Table Read Execution Time: 138.901 ms
   Metric rocksdb_number_db_seek: 2.000
   Metric rocksdb_number_db_next: 1000000.000
   Metric rocksdb_number_db_seek_found: 2.000
   Metric rocksdb_number_db_next_found: 999998.000
   Metric rocksdb_iter_bytes_read: 73,821,527.000
   Metric docdb_keys_found: 1000000.000
 Planning Time: 0.068 ms
 Execution Time: 287.326 ms
 Storage Read Requests: 2
 Storage Read Execution Time: 138.901 ms
 Storage Write Requests: 0.000
 Catalog Read Requests: 0
 Catalog Write Requests: 0.000
 Storage Flush Requests: 0
 Metric rocksdb_number_db_seek: 2
 Metric rocksdb_number_db_next: 1000000
 Metric rocksdb_number_db_seek_found: 2
 Metric rocksdb_number_db_next_found: 999998
 Metric rocksdb_iter_bytes_read: 73821527
 Metric docdb_keys_found: 1000000
 Storage Execution Time: 138.901 ms
 Peak Memory Usage: 8 kB
(25 rows)
```

The number of bytes read is nearly identical, and the number of seeks and nexts seems logical for each one.

**Comment by timothy-e** [comment]
![Screenshot 2023-09-14 at 4 45 39 PM](https://github.com/yugabyte/yugabyte-db/assets/26841748/dee0db95-fc48-4114-a59a-1e07bc3949bb)

It looks like this problem existed in yb_fetch_row_limit as well. As the number of rows in each response increases, the time to send increases as well. 

The ideal fetch size limit seems to be around 500-1000kB. 

![Screenshot 2023-09-14 at 4 45 32 PM](https://github.com/yugabyte/yugabyte-db/assets/26841748/482e231d-4492-41e8-aa73-f7d89db627cc)
