### ISSUE TITLE
[YSQL] Support distinct pushdown in YSQL

### ISSUE THREAD

**Issue by vbalvida** [yugabyte/yugabyte-db#17872]
Jira Link: [DB-6955](https://yugabyte.atlassian.net/browse/DB-6955)
#### Context

YB LSM indexes support skipping over duplicate values of the leading column(s). This results in an efficient execution of distinct queries since the scan needs only fetch distinct tuples from the index. The list of leading columns over which the index skips is called the prefix and it is uniquely identified by its length, hereby referred to as the prefix length. This access pattern is colloquially called loose index scan or skip scan.

While the storage layer supports such an access pattern using the Hybrid Scan module, YSQL support is still lacking. Currently, we compute the prefix and make the decision to pushdown distinct during execution. Such an approach is less than ideal and here we make a case for moving this task to the planner. See issues #14559 and #16257 for more information on how the pushdown is currently implemented.

#### Objective

Making the decision to pushdown distinct in the planner as opposed to PgGate lets us avoid several correctness issues. In summary, distinct should not be pushed down if the distinct operation does not commute/distribute with other operations in the query. This commutativity is better checked in the planner.

##### Aggregate and Windowing Functions

Aggregation and Windowing operations require that we do not skip over duplicate rows since aggregation happens over even duplicate tuples in the group. See #17648 for more information.

As an example, consider a query such as

```sql
SELECT DISTINCT COUNT(r1) FROM t WHERE r1 = 1;
```

where r1 is the leading range column of t. Fatal to skip over duplicate rows of r1 here.

##### Volatile targets or predicates

Similar reasoning applies to volatile targets and predicates. Volatile functions have side effects and hence need to be executed for each tuple. This property makes them inherently incompatible with distinct pushdown.

Example

```sql
SELECT DISTINCT r1 * RANDOM() FROM t WHERE r1 = 1;
```

Pushing down distinct here is a mistake since RANDOM() can take different values for different duplicate values of r1.

---

Other than such correctness issues, making the planner aware of distinct pushdown helps it generate and select better plans overall.

##### Inaccurate plan selection

Imagine that we have a table `t` setup using the following commands

```
CREATE TABLE t (r1 INT, r2 INT, PRIMARY KEY(r1 ASC, r2 ASC));
INSERT INTO t (SELECT 1, i FROM GENERATE_SERIES(1, 10000) AS i);
```

Now, getting the distinct elements of the first column executes the following plan

```
EXPLAIN ANALYZE SELECT DISTINCT r1 FROM t;
                                                QUERY PLAN                                                 
-----------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=102.50..102.51 rows=1 width=4) (actual time=80.961..80.962 rows=1 loops=1)
   Group Key: r1
   ->  Seq Scan on t  (cost=0.00..100.00 rows=1000 width=4) (actual time=9.449..76.847 rows=10000 loops=1)
 Planning Time: 5.901 ms
 Execution Time: 81.103 ms
 Peak Memory Usage: 14 kB
(6 rows)
```

Forcing an index scan yields

```
EXPLAIN ANALYZE SELECT DISTINCT r1 FROM t WHERE r1 <= 10000;
                                                    QUERY PLAN                                                     
-------------------------------------------------------------------------------------------------------------------
 Unique  (cost=0.00..15.50 rows=1 width=4) (actual time=1.711..1.717 rows=1 loops=1)
   ->  Index Scan using t_pkey on t  (cost=0.00..15.25 rows=100 width=4) (actual time=1.709..1.715 rows=1 loops=1)
         Index Cond: (r1 <= 10000)
 Planning Time: 0.128 ms
 Execution Time: 1.808 ms
 Peak Memory Usage: 8 kB
(6 rows)
```

As can be seen from the differences in the reported execution times, a wildly inaccurate plan is being picked. The primary reason is that the planner is unaware that fewer rows are being fetched.

##### Redundant Unique Node

In the above plan, observe that the planner creates an Unique node on top of the index scan. In the provided example, we already receive distinct elements from the first column by virtue of pushing down the distinct operation. This makes the unique node redundant and can thus be removed safely. Keep in mind that, the distinctness does not hold true when the referenced columns are a strict subset of the minimal encompassing prefix. For example, if the table contains three range columns instead of 2 where really only the second column is varying across the rows. Requesting distinct rows of keys r1 and r3 will lead to returning all the rows since the second key column is the effective primary key. Hence, the postgres layer still needs to de-duplicate these rows. Note that this behavior also applies when the keys are hash partitioning as opposed to range partitioning.

##### DISTINCT ON queries

Use a shorter prefix with DISTINCT ON queries by only including vars from the clause.

##### Set operations

Since UNION implicitly involves de-duplication of rows, this is a great fit for prefix based skips scans. Same for INTERSECT operator.

##### Semi-joins and Anti-joins

Some joins require distinct elements from inner tables such as

Semi-join Query

```
EXPLAIN SELECT r2 FROM tr12 WHERE r2 IN (SELECT r1 FROM tr12);
```

Anti-join query

```
EXPLAIN SELECT r2 FROM tr12 WHERE r2 NOT IN (SELECT r1 FROM tr12);
```

##### Equivalent Columns

Consider a query such as

```
SELECT DISTINCT r1, r2 FROM tr12 WHERE r1 = r2;
```

Since r1 and r2 are equal, the prefix length can be 1.

##### Better control over DISTINCT pushdown applicability

The issue https://github.com/yugabyte/yugabyte-db/issues/17648 lays out some bugs encountered in the current implementation. These issues naturally occur because the prefix is being calculated after all the planning is done and during the execution time. For example, the query layer inaccurately pushes down DISTINCT even in the presence of aggregation queries. This is inaccurate since the de-duplication must happen after aggregation. This is not the case even when aggregation is pushed down to the storage layer because DISTINCT is pushed past even aggregation at the storage layer. Making the planner aware of DISTINCT pushdown, allows handling such cases more cleanly.

##### More optimization opportunities

The previous issue lends itself to the next question of whether the storage layer can de-duplicate rows after aggregation and other operations. See issues #17741, #17607, and #18004 for more information. Implementing these tasks is easier when the prefix length is computed in the planning phase since the decision to pushdown predicates happens in the planning phase.

### Low-level details

XXX: Make it easier to read after all the work on the project is complete

#### PathKey's purpose and behavior

PathKey's are keys that store information about the ordering of the query. See the class definition in pathkeys.c.

##### Generating query pathkeys

For the unintiated, the PlannerInfo datastructure contains all the query-level information required for the planning/optimization phase. See relation.h for more information. The query level information for what keys need to be sorted for the query are stored in query_pathkeys.

query_pathkeys is initialized in standard_qp_callback along with other query level keys such as group_pathkeys (corresponds to GROUP BY clause), distinct_pathkeys (corresponds to DISTINCT/DISTINCT ON clause), sort_pathkeys(corresponds to ORDER BY clause), etc. The query_pathkeys is the minimal all inclusive set of PathKey's. See planner.c:standard_qp_callback.

##### Generating index paths

When generating index paths, they have a natural ordering and the ordering depends on how the keys in the index are ordered according to the specification of the index. The ordering can also be reversed using a backwards scan (all key orderings are reversed; can't be selective about individual keys).

These implicit orderings over the complete index is then stored in the generated Path node. Observe that this is largely independent of the sort ordering as required by the query. In fact, the backwards scan is generated using new paths and is not immediately inferred from query. This is not an issue since it is alright to sort on more keys than necessary. The planner rejects any paths that have fewer or different orderings. See indxpath.c:build_index_paths and pathkeys.c:build_index_pathkeys

Same cannot be said about the distinct index scan. The planner needs to compute the minimal prefix that works. Compute a prefix that is too long and we lose on efficiency, while shorter prefixes are rejected altogether since a shorter distinct prefix has fewer tuples from the table.

One approach to handle this is to generate a path for each size of the prefix and reject paths that do not satisfy the requirements in upper layers. There are a couple issues with such an approach. A multiplicative number of distinct index paths are created for each ordered path which increases the planning time. The second more important issue is that the merge sort only considers the total cheapest path for its outer and inner relations. The cheapest paths here would be ones with prefix 1. Thus making it pretty unlikely for any distinct index scan to be considered. In theory, this logic can be changed to generate sort merge joins with different prefix values for its child relations, however, it is better to look for easier solutions at the moment. See the comment below from joinpath.c:sort_inner_and_outer

```c
/*
* We only consider the cheapest-total-cost input paths, since we are
* assuming here that a sort is required.  We will consider
* cheapest-startup-cost input paths later, and only if they don't need a
* sort.
*
* This function intentionally does not consider parameterized input
* paths, except when the cheapest-total is parameterized.  If we did so,
* we'd have a combinatorial explosion of mergejoin paths of dubious
* value.  This interacts with decisions elsewhere that also discriminate
* against mergejoins with parameterized inputs; see comments in
* src/backend/optimizer/README.
*/
outer_path = outerrel->cheapest_total_path;
inner_path = innerrel->cheapest_total_path;
```

Another approach is to consider the query level distinct pathkeys and base our prefix on the intersection of these path keys and the key columns in our table. Such an approach is not accurate since consider a query such as

```sql
SELECT DISTINCT r1 FROM t
  WHERE r1 <= 1000 AND r1 * r2 = 500;
```

The intersection will only contain r1 while the distinct index scan may not necessarily return a tuple with `r1*r2 = 500`. It is better to scan with a prefix length of 2. including both r1 and r2. See issue #17741 for more information.

Can we distribute the set of unique keys down to reloptinfo? potentially duplicate work with predicates.

Index Scan with target list + qpquals + joinclauses works? TBD

#### Proposed Approach

Here, is an outline of the proposed approach to solve the above problems.

- [x] Determine the set of distinct pathkeys required.
- [x] Remove redundant pathkeys from the required list. Done by checking equivalence classes
- [x] Before generating a Distinct Index Scan path, collect what index keys must be available in the output. These include all distinct targets, keys referenced in non-index clauses such as join clauses, remote filters, and local filters.
- [x] When the distinct index scan cannot be served by the collected keys above, do not use the index to generate a distinct index path
- [x] Store the collected unique keys inside the created distinct index scan path. The distinct index path is simply a copy of the normal ordered index path with additional information on unique keys
- [x] Adjust the cost of this copy of index path. The cost is represented by the number of distinct rows times the startup cost (if we assume startup cost for each seek).
- [x] Store such paths with unique keys in a separate unique pathlist so that the planner does not pick these paths unless explicitly added to the usual pathlist by the unique path creator. The creator chooses to either add the path to the main list or discard it entirely on the basis of whether the set of unique keys of the path is sufficient.
- [x] Propagate the unique keys upwards along supported plan tree branches.
- [x] Introduce a new field representing the length of the prefix in distinct index scans
- [x] Show the value in explain statements
- [x] Set the computed prefix value in outbound protobuf for index scan read from pggate
- [x] Currently, we generate the set of keys required at the query level. This is incomplete. Generate the set of distinct keys required while generating the unique path
- [x] When two distinct expressions belong to the same equivalence class, pick the one with shorter prefix
- [x] Collect key references for non-index clauses as well
- [x] Pg does not consider index paths if leading columns are not part of the sort clauses. While, we still need to add a sort node, generating an index path can still be helpful with non-leading distinct keys.
- [x] Currently, only projections propagate unique keys. See if some joins can propagate them upwards along the path as well.

##### New Data Fields

- RelOptInfo::yb_uniq_pathlist
  - Stores all the distinct index scan paths generated on the relation (base or join)
  - Provide an example where simply generating the paths in the pathlist is not sufficient and we need a separate list
- Path::yb_uniqkeys
  - Stores all the unique keys for the path to be matched against the query. Need to propagate these keys upward during the recursion when generating various nodes in postgres bottom up approach
  - Can either be an expression or an eclass

##### Control Flow

build_index_paths should generate additional index paths for prefix based scans. For this, first compute useful unique keys and if appropriate add an unique path. Generate the list of unique keys using yb_uniq_prefix. Generate the path using a new function yb_create_prefixscan_path. Define a function add_unique_path for same. Follows closely with add_path and adds to path's yb_uniquekeys. Do these only when yb_enable_distinct_pushdown is true.

Creating the scan path requires create a scan node which in turn requires computing the prefix length. The prefix length can be computed by checking the references.

We propagate the set of unique keys across projections as is. TBD: what do we do in case of joins?

We only add uniquepaths when creating distinct paths. And that too when the indexes can satisfy the distinctness requirements. We update the cheapest path if the unqiueness requirements are superfluous.

##### Hash Column Support

Currently, YB postgres layer avoids generating ordered paths for hash columns for good reason.

#### Tentative Test Plan

- [x] Should not choose sequential scan when distinct index scan is better
- [ ] Should not add a redundant unique node
- [x] Investigate interference with parallel queries. We do not support parallel queries, see #17987
- [x] Regression tests
- [x] Regression - both hash and range key columns
- [ ] Regression - columns belonging to secondary indexes (NULL values)
- [x] Regression - ORDER BY DESC clauses
- [ ] Regression - DISTINCT ON clauses (include constant reductions)
- [ ] Regression - UNION clauses
- [ ] Regression - GROUP BY clauses
- [ ] Regression - DISTINCT target expressions that preserve the sort order and uniqueness + otherwise
- [ ] Regression - distinct joins (both base rels unique/not unique)
- [x] Regression - volatile clauses
- [x] Regression - equivalent keys
- [x] Regression - LIMIT clauses
- [x] Regression - non-LSM indexes

#### Perf Plan

- [ ] Seq Scan vs Distinct Index Scan
- [ ] With and without unique node
- [ ] With and without hash aggregate node
- [ ] Small groups of equal values
- [ ] Wider data types
- [ ] Regression
- [ ] Regression - planning time
- [ ] Regression - execution time
- [ ] Regression - interesting data has repeat count much lower than the average

###### Example

```sql
EXPLAIN
  SELECT DISTINCT ON(r1) *
  FROM t;
```

###### Expected behavior

Use distinct index scan with prefix 1

###### Challenge

Retrieve the necessary information required at the indexpath/baserel level from the DISTINCT ON clause
Also, support non-index only scan for distinct queries (hopefully not too difficult).

###### Example

```sql
EXPLAIN
  SELECT r1 FROM t
  UNION
  SELECT r1 FROM t;
```

###### Expected behavior

Push down distinct into each subquery to use a distinct index scan of prefix 1.

###### Challenge

Pushing down distinct might require changes to how the paths are generated for each arm thus having unintended consequences.

###### Example

```sql
EXPLAIN
  SELECT r1 FROM t GROUP BY r1;
```

###### Expected behavior

In absence of aggregate functions, grouping selects are equivalent to distinct selects.

###### Challenge

Add a rewrite rule thats applicable to the above scenario to turn grouping clauses to distinct clauses.

###### Example

```sql
EXPLAIN
  SELECT DISTINCT 2 * r1
  FROM t;
```

###### Expected Behavior

Some operations such as scalar multiplication preserve uniqueness since they cannot cause duplicates unless the scalar is zero.

###### Challenge

Analyzing scenarios where this is applicable is beyond the scope of this ticket. Keep in mind that not all operations that preserve sort order preserve uniqueness (example: scalar multiplication by 0). Moreover, some operations preserve uniqueness but do not preserve sort order or even reverse it (example: scalar multiplication by -1). Finally, postgres currently does not generate index paths for more involved orderings. Hence, solving this problem requires introducing a new framework of sorts to identify equivalent expressions in terms of uniqueness.

##### Expression Indexes and more

Simply wanted to keep the scope of the ticket small.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6955]: https://yugabyte.atlassian.net/browse/DB-6955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Can you fix the TBD/TODO?

What is "prefix"?  "prefix computation", "prefix index scan"

**Comment by vbalvida** [comment]
The basic framework has landed. Any extensions or future work will be done as separate tasks.
