### ISSUE TITLE
[DocDB] Enhance GetTransactionStatus rpc to return involved tablets info 

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#17886]
Jira Link: [DB-6966](https://yugabyte.atlassian.net/browse/DB-6966)
### Description

If the request from Pg, `PgGetLockStatusRequestPB` contains a transaction(s), we restrict the lock info to the specified set of transactions. Else, we get the old transactions and return the lock info of these transactions.

In the former case, we broadcast the request to all Tablet Servers. We could optimize this by querying only the involved tablets, and hence sending the request to only Tablet Servers hosting these involved tablets. For this to be feasible, we should make the transaction coordinator return involved tablets info as part of `GetTransactionStatus` rpc. So in `GetLockStatus`, we would first fetch the involved tablets by calling `GetTransactionStatus`, and then fetch the lock info of the given transaction.

cc: @robertsami 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6966]: https://yugabyte.atlassian.net/browse/DB-6966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
https://github.com/yugabyte/yugabyte-db/issues/16913
