### ISSUE TITLE
[DocDB] flaky test: XClusterTestParams/XClusterTest.LeaderFailoverTest/0 and /1

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17897]
Jira Link: [DB-6979](https://yugabyte.atlassian.net/browse/DB-6979)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=XClusterTestParams%2FXClusterTest&fail_tag=all&name=LeaderFailoverTest%2F1&platform=linux

Seems flaky since introduced and 100% failing in TSAN.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6979]: https://yugabyte.atlassian.net/browse/DB-6979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Fixed by commit https://github.com/yugabyte/yugabyte-db/commit/803d5d6d73033f8a57d28aa996afca3089becb6e
