### ISSUE TITLE
[DocDB] xCluster apply runs into deadlock when using DirectWriter

### ISSUE THREAD

**Issue by karan-yb** [yugabyte/yugabyte-db#17890]
Jira Link: [DB-6970](https://yugabyte.atlassian.net/browse/DB-6970)
### Description

In the pause-resume XCluster replication test, after resume, we saw cases where replication lag was continuously increasing. The continuous increase was caused because of deadlock between IntentsDB and RegularDB.

When flushing IntentsDB, we have introduced a callback which checks whether regular db is caught up or not. If its not caught up, then we block the IntentsDB flush; and if the regular db instance was not flushed in 2 seconds (controlled by  `intents_flush_max_delay_ms` gflag), then we will try to flush the regular db in this callback. This RegularDB flush operation ensures that there are no write operations active in the system.

During apply of external write op, we create RegularDB DirectWriter, which reads the intents for external committed transactions and copies them to regular db. To read the records, we create IntentsDB iterator as part of it. This is similar to how single cluster copies data from intents to regular db during flush.

If we try to queue the RegularDB flush from IntentsDB filter callback when there is an active direct writer in the system, then we will run into a deadlock. Because -
* Releasing of the iterator owned by DirectWriter requires the same lock which is hold by thread which calls IntentsDB filter callback.
* For regularDB flush to make progress, we need to ensure that this DirectWriter operation completes.

Possible short team solutions (for XCluster only)
* Avoid using DirectWriter for XCluster apply. 
* Create the intent iterator outside and pass it as input to DirectWriter -- this will remove the dependency of releasing iterator to finish the direct writer.

Long term solutions -
1. Introduce a callback right before IntentsDB flush to see if regular DB needs to be flushed — this essentially means that we are calling the callback without holding the rocksdb mutex.
2. Instead of flushing rocksdb inline, we could move this to a different thread of queue a signal to flush after all operations complete.
3. Do not continue with IntentsDB flush if we need regular DB flush to proceed. Downsides is that memory usage might continue to increase if large number ops are in progress.

As per the slack thread, 2nd long term option is preferred to fix both single cluster and XCluster problem.

Stack traces -
```
rocksdb:high:1x-29966	284.770s	0.000s	0.000s	
    @     0x7fb214e6a00c  __pthread_cond_wait
    @     0x560d31c7c6fa  rocksdb::WriteThread::AwaitState()
    @     0x560d31c7cdbe  rocksdb::WriteThread::EnterUnbatched()
    @     0x560d31bfede4  rocksdb::DBImpl::FlushMemTable()
    @     0x560d31bd69ec  rocksdb::DBImpl::Flush()
    @     0x560d31baadc4  rocksdb::DB::Flush()
    @     0x560d31eb716f  yb::tablet::Tablet::IntentsDbFlushFilter()
    @     0x560d31eb7339  std::__1::__function::__func<>::operator()()
    @     0x560d31c1f4bf  rocksdb::FlushJob::Run()
    @     0x560d31bfa300  rocksdb::DBImpl::BackgroundCallFlush()
    @     0x560d31d00b92  std::__1::__function::__func<>::operator()()
    @     0x560d324c3d91  yb::Thread::SuperviseThread()
    @     0x7fb214e65693  start_thread
    @     0x7fb21536741c  __clone

consensus [worker]-164797	1.780s	0.000s	0.000s	
    @     0x7fb214e6cb39  __lll_lock_wait
    @     0x7fb214e676e2  __GI___pthread_mutex_lock
    @     0x560d31cdb4d9  rocksdb::InstrumentedMutex::Lock()
    @     0x560d31bfdc8b  rocksdb::(anonymous namespace)::CleanupIteratorState()
    @     0x560d31cb85f1  rocksdb::MergingIterator::~MergingIterator()
    @     0x560d31c17ef8  rocksdb::DBIter::~DBIter()
    @     0x560d31c188cf  rocksdb::ArenaWrappedDBIter::~ArenaWrappedDBIter()
    @     0x560d3146fe20  yb::docdb::ExternalIntentsBatchWriter::Apply()
    @     0x560d31c73f68  rocksdb::WriteBatch::Iterate()
    @     0x560d31c79369  rocksdb::WriteBatchInternal::InsertInto()
    @     0x560d31be1e7a  rocksdb::DBImpl::WriteImpl()
    @     0x560d31bd0850  rocksdb::DBImpl::Write()
    @     0x560d31eae80d  yb::tablet::Tablet::WriteToRocksDB()
    @     0x560d31ebe3c9  yb::tablet::Tablet::ApplyOperation()
    @     0x560d31ebcf46  yb::tablet::Tablet::ApplyRowOperations()
    @     0x560d31e8e73a  yb::tablet::WriteOperation::DoReplicated()
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6970]: https://yugabyte.atlassian.net/browse/DB-6970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@karan-yb , Do we need to backport to 2.18 ? If not, can we close this? cc @lingamsandeep

**Comment by karan-yb** [comment]
Closing the issue as current solution is sufficient for XCluster, and we don't run into the problem in single cluster mode since the iterator is created outside of DirectWriter execution.
