### ISSUE TITLE
[YSQL] Investigate and speed up scan performance

### ISSUE THREAD

**Issue by JDNdeveloper** [yugabyte/yugabyte-db#1789]
Jira Link: [DB-2382](https://yugabyte.atlassian.net/browse/DB-2382)
When running a sample workload that inserts 10M rows, a full scan (`select count(*)`) is taking around 70 seconds to complete.

This issue tracks investigating the performance of this query and comparing against a similar YCQL workload, and speeding up the performance where possible.

Sample workload was generated using this script: https://gist.github.com/kmuthukk/fa9fd54278c91aba14979fd8ba8d4973

**Comment by bmatican** [comment]
#2136 was a great find from analyzing `perf` during a run.

@JDNdeveloper Let's use this as a master task and link in any other optimizations findings we see along the way!

**Comment by rthallamko3** [comment]
We have made a bunch of improvements in the scan area in 2.16, 2.18 and upcoming 2.20 release.
