### ISSUE TITLE
[YSQL] Cannot see tables after ingesting schema dumped using pg_dump

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1792]
After ingesting schema that was dumped using pg_dump, we cannot the tables using `\d`. However, `select * from table` works fine. If we reconnect to the database and run `\d` again, we are able to see the tables.

To reproduce:
1. Run pg_dump on an existing database and save the schema file.
2. Connect to ysqlsh:
```
postgres=# create database copy;
postgres=# \c copy;
You are now connected to database "copy" as user "postgres".
copy=# \i schema.sql;
copy=# \d
Did not find any relations.
copy=# \c postgres;
You are now connected to database "postgres" as user "postgres".
postgres=# \c copy;
You are now connected to database "copy" as user "postgres".
copy=# \d
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | base | table | postgres
 public | ref  | table | postgres
(2 rows)
```

**Comment by georgeklees** [comment]
It should be noted that I tried this on vanilla Postgres and it behaved exactly the same way. So it is unlikely that this is because of anything YugaByte-specific that we did. However, we can still fix this if we want, or report it to the Postgres team to try and get them to.

**Comment by georgeklees** [comment]
The cause of the issue is this line in the pg_dump output: `SELECT pg_catalog.set_config('search_path', '', false);` Commenting it out leads everything to work fine.

**Comment by georgeklees** [comment]
Because this all stems from default Postgres behavior, and we probably don't want to change `psql` to save the search path as it will break compatibility if a user *expects* search path changes to stick when ingesting a schema, this issue will be closed for now pending further discussion.
