### ISSUE TITLE
[DocDB] Key 07B521D8EE3D3C42E2A6859268286D72C421 is not table tombstone key

### ISSUE THREAD

**Issue by vbalvida** [yugabyte/yugabyte-db#17944]
Jira Link: [DB-7016](https://yugabyte.atlassian.net/browse/DB-7016)
## Steps to reproduce

Setup

```
CREATE TABLE t (r1 INT, r2 INT, PRIMARY KEY (r1 ASC, r2 ASC));
INSERT INTO t (SELECT 1, i FROM GENERATE_SERIES(1, 100000) AS i);
```

Query

```
SELECT r2 FROM t WHERE r2 <= 1;
```

should return 1 row containing 1 but instead raises an error

```
ERROR:  Key 07B521D8EE3D3C42E2A6859268286D72C421 is not table tombstone key.
```

Tserver Log

```
I0626 14:57:31.704208 175411200 scan_choices.cc:287] Result<bool> yb::docdb::HybridScanChoices::SkipTargetsUpTo(yb::Slice) Updating current target to be >= DocKey([], [TransactionId(cf2822e0-708a-4812-ae38-98b99516dd79)])
I0626 14:57:31.704864 175411200 scan_choices.cc:369] Failed to decode the key: Corruption (yb/dockv/primitive_value.cc:777): Cannot decode a primitive value in the key encoding format from an empty slice: ""
```

Code Version: Master branch commit: d1e3aa6d1e

The issue is not reproducible in 2.18 (only the master branch).

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7016]: https://yugabyte.atlassian.net/browse/DB-7016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@vbalvida , Which version of Yugabyte did you face the issue on? Similar issues have been resolved as part of https://github.com/yugabyte/yugabyte-db/issues/16257 cc @tanujnay112

**Comment by vbalvida** [comment]
@rthallamko3 I faced this on the latest master commit that I pulled today (6/26).

**Comment by rthallamko3** [comment]
The regression was introduced by https://github.com/yugabyte/yugabyte-db/commit/10a97cc48ab25e638d97103f742731c057df1ab1 and is now fixed in master.
