### ISSUE TITLE
[Docs] Steps to migrate your database using YugabyteDB Voyager

### ISSUE THREAD

**Issue by szbyb** [yugabyte/yugabyte-db#17950]
### Description

https://docs.yugabyte.com/preview/migrate/migrate-steps/#prepare-the-source-database

**Prepare the source database**, bottom of section (just before **Prepare the target database** section): there is a note box with the title **Connecting to Oracle instances**. This seems to be irrelevant in case of *MySQL* and *PostgreSQL*, yet it is shown for both databases. This note box should probably be moved "up" to the *Oracle* tab container.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by aishwarya24** [comment]
Fixed this as part of live migration docs. Thanks @szbyb
