### ISSUE TITLE
Unexpected postmaster exit on Mac - version 1.2.12

### ISSUE THREAD

**Issue by dodilp** [YugaByte/yugabyte-db#1797]
[postgresql-2019-07-13_150525.log](https://github.com/YugaByte/yugabyte-db/files/3389134/postgresql-2019-07-13_150525.log)

Steps to reproduce - 
Run some of the first few statements from 
https://github.com/prisma/database-schema-examples/blob/master/postgres/sportsdb/schema.sql

**Comment by dodilp** [comment]
1.2.12 is not very stable on mac. 

My full OS name with version is - 
MacBook-Pro:logs don$ uname -a
MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by ndeodhar** [comment]
Hi @dodilp, I tried this on a newly created RF=1 cluster using 1.2.12 on Mac, and it worked fine. Can you give some more details about your setup?
1. Is your cluster a new cluster or did you use 1.2.12 on a cluster that was created using a previous version of YB?
2. Is it RF=1 or 3?
3. Do you see any errors in tserver logs? You can find these at `$data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO`.

**Comment by dodilp** [comment]
[yb-tserver.Dons-MacBook-Pro.local.don.log.INFO.20190713-150525.33423.txt](https://github.com/YugaByte/yugabyte-db/files/3390649/yb-tserver.Dons-MacBook-Pro.local.don.log.INFO.20190713-150525.33423.txt)

**Comment by dodilp** [comment]
Hi @ndeodhar - I've attached the tserver log file. It is a fresh cluster created after dropping the data files. Started it with RF=1.

**Comment by ndeodhar** [comment]
@dodilp I'm seeing a lot of such errors:
`Too many open files (error 24)`
We recommend updating your ulimits for open files. See details and recommendations here:
https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/#checking-ulimits

Let me know if that works.

**Comment by dodilp** [comment]
Thanks @ndeodhar. Let me get back on this if it errors out again.

**Comment by dodilp** [comment]
Hi @ndeodhar,

I'm still hitting the issue after the restart - 

Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0714 23:17:27.634340 45469696 async_initializer.cc:83] Failed to initialize client: Timed out (yb/rpc/outbound_call.cc:461): Could not locate the leader master: GetMasterRegistration RPC to 127.0.0.3:7100 timed out after 2.500s

**Comment by dodilp** [comment]
In the master node, the error is - 
W0714 23:19:51.360918 238305280 consensus_peers.cc:609] Error getting permanent uuid from config peer [127.0.0.2:7100]: Timed out (yb/rpc/outbound_call.cc:461): GetNodeInstance RPC to 127.0.0.2:7100 timed out after 10.000s
W0714 23:20:09.757233 239378432 master_service.cc:102] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:5567): Node c3e1b9737e294b0f84d3f0675e6cf6cb peer not initialized.

**Comment by ndeodhar** [comment]
Does RF=1 work? Also, does your machine have SSD or HDD? We don't recommend running YB on HDDs.

**Comment by dodilp** [comment]
**RF = 1** (This seems to work fine, atleast system starting up)

$ ./yb-ctl --rf 1 create
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /Users/dodil/yugabyte-data                                                   |
----------------------------------------------------------------------------------------------------

For more info, please use: yb-ctl status

$ ./yb-ctl status
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /Users/dodil/yugabyte-data                                                   |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 1: yb-tserver (pid 9469), yb-master (pid 9466)                                              |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| data-dir[0]         : /Users/dodil/yugabyte-data/node-1/disk-1/yb-data                             |
| yb-tserver Logs     : /Users/dodil/yugabyte-data/node-1/disk-1/yb-data/tserver/logs                |
| yb-master Logs      : /Users/dodil/yugabyte-data/node-1/disk-1/yb-data/master/logs                 |
----------------------------------------------------------------------------------------------------

----
In terms of storage - I am using flash storage

**Comment by rkarthik007** [comment]
Is rf=3 still failing for you @dodilp? Are you blocked on that?

**Comment by dodilp** [comment]
RF=3 is still failing, and I'm pretty much blocked on Mac with 1.2.12. If there is a more recent build to try out, please let me know

**Comment by ndeodhar** [comment]
@dodilp You can try 1.3 release. If that still doesn’t work for you, then we can debug over a zoom call.

**Comment by dodilp** [comment]
Thank you, @ndeodhar. Let me check if I can get unblocked with 1.3.

**Comment by dodilp** [comment]
We can close this now. 1.3 is pretty good on Mac OS

**Comment by ndeodhar** [comment]
Glad to hear, thanks for the update @dodilp!
