### ISSUE TITLE
[Docs] New docs proposal

### ISSUE THREAD

**Issue by phendric-uk** [yugabyte/yugabyte-db#17989]
### Description

https://docs.yugabyte.com/v2.16/explore/change-data-capture/debezium-connector-yugabytedb/#release-series-1-9-5-y shows the following:

> Release series 1.9.5.y
> 
> Tested versions

It doesn't clarify that this is a minimum pre-requisite - can a note be added to clarify that the versions shown are pre-requisite minimums rather than just those versions the connecter was tested with?

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
cc @ymahajan
