### ISSUE TITLE
[DocDB] Track all IOs by stack trace

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17993]
Jira Link: [DB-7054](https://yugabyte.atlassian.net/browse/DB-7054)
### Description

As part of building a full picture of disk IO and improving our visibility, we could do something similar to what we have for memory, eg via the Google tcmalloc heap_snapshot view, where we get the stacks of memory allocations.

However, while memory access is very perf sensitive and requires sampling, disk IO should be far less frequent and far less sensitive to introducing a `GetStackTrace()` and some light accounting, into the flow!

Assuming all our disk IO is not done via direct syscalls, but rather through our Env/File abstractions, we should be able to have a small utility which captures a stack trace on every read/write/fsync(?) operation and then aggregates across them. At the minimum, we could use this to make sure we fully understand
1. All the types of IO that happens in our system? eg: are we missing some particular types of file access, in our accounting, such as tablet metadata, consensus metadata, rocksdb manifest / metadata, etc
1. Are the access paths inline with what we expect? eg: WAL reads should only happen for fallen behind followers, unless you have xcluster / cdc enabled, case in which those now also will consume

Over time, we can use this information to make sure we have complete metrics coverage across all disk IO locations. This is similar to how, for memory, we use the MemTracker to increase coverage of "known" memory allocations, trying to cover the gap of "untracked memory" up to `root` (total heap usage).

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7054]: https://yugabyte.atlassian.net/browse/DB-7054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
Server UI for I/O stack trace tracking:  ![I/O stack trace endpoint UI](https://github.com/yugabyte/yugabyte-db/assets/6742815/5d29a85c-ba7d-40b3-b306-4655ca34d15c)
