### ISSUE TITLE
Automatically detect if data/logs/wals are pointing to tmpfs and soft disable O_DIRECT instead of crashing

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#18]
Recently we had a report (https://github.com/YugaByte/yugabyte-db/issues/17) of a docker run which has the data dirs pointing to a tmpfs path and ultimately crashed the masters:
`F0123 07:19:33.281553    44 master_main.cc:82] Check failed: _s.ok() Bad status: IO error (yb/util/env_posix.cc:202): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed to open new log: Call to mkstemp() failed on name template /yuga/mem/yb-master/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/.tmp.newsegmentXXXXXX: Invalid argument (error 22)`

The crash happens because O_DIRECT is not actually supported on tmpfs!

As a proposed fix, we'll add some defensive code in our servers such that, if any of the paths pointed to for data/logs/wals are on a file system we cannot open a file with O_DIRECT, then we softly downgrade the `durable_wal_write` flag to false and print out a notice about this.

**Comment by mbautin** [comment]
@bmatican: perhaps we could have two modes for durable WAL writes: the current behavior, in which we refuse to start in case we can't use O_DIRECT, and a "prefer durable WAL write" / "autodetect" mode (which could be the default) with the graceful downgrade logic you're describing.

**Comment by ayushsengupta1991** [comment]
Closed with https://github.com/YugaByte/yugabyte-db/commit/4c5813a9d8d518cc3cf5fdcba38f52fd846f6c7c
