### ISSUE TITLE
[Docs] Clarify which extensions are supported in YBM free/paid tiers

### ISSUE THREAD

**Issue by jasonriddell** [yugabyte/yugabyte-db#18009]
### Description

Please clarify which extensions are supported in YBM and whether there is any difference between the free and the paid tier of YBM regarding extension support.

I believe that for YBM free only the pre-bundled extensions are supported and that for paid, the installed extensions need to be arranged with the YBM team (though please clarify this with them). Having this clearer would prevent support tickets.

Thanks.
Jason.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
Extensions in YBM are described [here](https://docs.yugabyte.com/preview/yugabyte-cloud/cloud-clusters/add-extensions/)
