### ISSUE TITLE
[DocDB] Add Node task fails after Backup/Restores with EAR rotations

### ISSUE THREAD

**Issue by yusong-yan** [yugabyte/yugabyte-db#18001]
Jira Link: [DB-7062](https://yugabyte.atlassian.net/browse/DB-7062)
### Description

The Update Universe Task fails after the following operations on a EAR Enabled universe:

Create a 3 RF and 4 node universe

Run Sample Apps

Take Backup

Rotate KMS key

Restore in the same universe by renaming the keyspace

Take backup of the new keyspace

Disable EAR

Restore in the same universe by renaming the keyspace

Take Backup of the new keyspace

Enable EAR

Restore in the same universe by renaming the keyspace

Take Backup of the new keyspace

Restore in the same universe by renaming the keyspace (without any rotations)

Add node (Update Universe) task will fail with the following logs:

```
Failed to execute task {"platformVersion":"2.19.1.0-b189","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"7e756665-30e5-419e-9284-a3ec33a3cd82","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"y..., hit error:

 WaitForServer(7e756665-30e5-419e-9284-a3ec33a3cd82, yb-dev-ui-auto-aws-21910-b189-kms-114-n5, type=TSERVER) did not respond in the set time..
```

```
W0627 18:17:42.236019 65736 tablet_server.cc:417] Getting full universe key registry from master Leader failed: 'Not found (yb/master/encryption_manager.cc:246): Could not find key with version '. Attempts: 2294, Total Time: 6859638200092ms. Retrying...
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7062]: https://yugabyte.atlassian.net/browse/DB-7062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yusong-yan** [comment]
This can simply repro by creating a universe with EAR enabled, then do following tasks:
<img width="519" alt="Screenshot 2023-06-28 at 8 01 30 PM" src="https://github.com/yugabyte/yugabyte-db/assets/46516278/23d7014a-c431-4f26-a780-ad4233ef88c7">
<img width="1225" alt="Screenshot 2023-06-28 at 8 01 57 PM" src="https://github.com/yugabyte/yugabyte-db/assets/46516278/0f305e0e-d022-49e0-bd80-191f2cd28f2d">

**Comment by rthallamko3** [comment]
Related to https://github.com/yugabyte/yugabyte-db/issues/17078.
