### ISSUE TITLE
initdb takes a very long time to run

### ISSUE THREAD

**Issue by chibicitiberiu** [YugaByte/yugabyte-db#1802]
Hello, I'm new to YugaByte and I'm attempting to create a simple 3-node cluster using Docker, in order to evaluate if this database system would work for us.

So far, I haven't been successful due to the fact that the `initdb` command takes a huge amount of time to run. I've attempted this on 2 different computers, and after more than 2 hours, it's still not done. 

At first, I tried it on my main workstation where I am using Docker for Windows, and tried to set it up using docker-compose. When this didn't work, I tried to simply use `yb-docker-ctl create --rf 3` on a fresh Ubuntu 18.04 machine with latest docker installed (18.09.7 build 2d0083d). On both the machines, I encountered the same problem.

On the fresh Ubuntu machine, it hasn't completed yet, but on my main workstation, after 2 hours I got the following output:

```
db-tserver-1_1  | I0715 10:55:30.530870   204 meta_cache.cc:553] Got resp error 7, code=OK
db-tserver-1_1  | W0715 10:55:30.532256   204 meta_cache.cc:567] Leader Master has changed, re-trying...
db-tserver-1_1  | I0715 10:55:30.533715   205 meta_cache.cc:553] Got resp error 7, code=OK
<..... a lot more of these resp error 7 ...>
db-tserver-1_1  | I0715 10:55:30.537092   204 meta_cache.cc:553] Got resp error 7, code=OK
db-tserver-1_1  | W0715 10:55:31.149008   367 outbound_call.cc:368] RPC callback for RPC call yb.master.MasterService.GetTabletLocations -> { remote: 172.22.0.3:7100 idx: 0 protocol: 0x00007f072592a8d8 -> tcp } , state=FINISHED_SUCCESS.
took 0.038s
db-tserver-1_1  | I0715 10:55:31.210631   204 tablet_rpc.cc:325] Already present (yb/consensus/retryable_requests.cc:238): Failed Write(tablet: 00000000000000000000000000000000, num_ops: 1, num_attempts: 5, txn: 00000000-0000-0000-0000-000000000000) to tablet 00000000000000000000000000000000 on tablet server { uuid: 3ee05aaf792d48f399bc178f1a990484 private: [host: "d337873c4314" port: 7100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 5 attempt(s): Duplicate request
db-tserver-1_1  | 2019-07-15 10:55:31.211 UTC [195] FATAL:  duplicate key value violates unique constraint "pg_depend"
db-tserver-1_1  | child process exited with exit code 1initdb: removing data directory "/tmp/yb_pg_initdb_tmp_data_dir"
db-tserver-1_1  | Running initdb finished.
```

After getting these errors, I couldn't run any command using `psql`, I would get an error that the "postgres" database doesn't exist.

Is this normal, or am I doing something wrong?

**Comment by kmuthukk** [comment]
hi @chibicitiberiu 

a) Are you on a setup with HDD (hard-disk drives) or SSD? We don't really support HDDs and that could some of this.

b) Also, the yb-docker-ctl flow has not yet been switched over to use the fast "initdb" (from snapshot) flow. That fix (https://github.com/YugaByte/yugabyte-db/issues/1772) should be available in the next release. But if you want to pick up the patch to the yb-docker-ctl file - here it is: https://github.com/YugaByte/yugabyte-db/pull/1796/commits/275099a6ce62386e264c122f0b22ac75369380b6

regards,
Kannan

**Comment by chibicitiberiu** [comment]
I am using HDDs. The odd thing is that there's no HDD or CPU activity while initdb is running, so I doubt this is the problem.

I tested with the yb-docker-ctl from master, and it works properly.

**Comment by kmuthukk** [comment]
Thx for update. Glad to hear things are working fine with the latest yb-docker-ctl which does the fast initdb.

**Comment by ndeodhar** [comment]
@chibicitiberiu Glad to see that yb-docker-ctl patch worked for you. Your earlier error about `psql` not working was because initdb didn't complete successfully.

Since the patch worked for you, I'm closing this issue. Feel free to reopen if you need further assistance. Thanks!
