### ISSUE TITLE
[yw][metrics] Enhance the rocksdb stall panel to also show stops

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1806]
Ideally, we should expose both stalling and stopping at the rocksdb level into the metrics dashboard.

The stall metric we're using is `rocksdb_stall_micros`. cc @spolitov on if we currently have a stop metric

**Comment by yb-andrew** [comment]
The stall metric is already exposed in the DocDB metrics. Closing issue.
