### ISSUE TITLE
[DocDB] Emit server level aggregates for metrics not in the table-level whitelist

### ISSUE THREAD

**Issue by yusong-yan** [yugabyte/yugabyte-db#18078]
Jira Link: [DB-7120](https://yugabyte.atlassian.net/browse/DB-7120)
### Description

- YBA uses URL param priority_regex as a table whitelist to reduce the amount of output, and the downside is, for those tablet or table metrics that are not in the regex list, the endpoint will not scrape them at all. As we keep adding metrics in the future, new metrics will never get returned from the endpoint unless YBA modify the priority_regex. This causes trouble for debugging in many situations.
- Currently, we have server aggregation code, but it is not being used due to its performance issue. It requires two scrapes to fetch all server-level metrics + table-level metrics. It also has some consistency errors – the server-level aggregation is done at a separate time from the normal metrics and thus may not actually be an aggregation of the returned table-level metrics.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7120]: https://yugabyte.atlassian.net/browse/DB-7120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Evaluating backports for this diff. 2.20 backport is a must. 2.18 is optional (depending on the complexity of the backport).
