### ISSUE TITLE
[YSQL][Read committed][Geo-partitioning] Encountering 40001 transaction abortion errors while running conflicting transactions that do not result in deadlock

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18081]
Jira Link: [DB-7123](https://yugabyte.atlassian.net/browse/DB-7123)
### Description

This is a geo_partitoned universe (regions: us-west-2, us-east-1, ap-south-1) has `yb_enable_read_committed_isolation`, `enable_deadlock_detection` and `enable_wait_queues` gflags. While running contentious transactions the test starts 4 threads in parallel all trying to acquire different types of lock on the same row. From logs we know that waiting is happening properly and there is no deadlock yet after 1 or more transactions (out of the 4) are committed, some of the other remaining transaction encounters following error:
```
Move transaction status: Transaction 8bc626a9-de15-4b49-8d14-dcb8ddde47e1 expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_participant.cc:1202): Move transaction status: Transaction 8bc626a9-de15-4b49-8d14-dcb8ddde47e1 expired or aborted by a conflict: 40001 (pgsql error 40001)]
```
The test started failing recently on master (failing consistently on `2.19.1.0-237`). Test summary:
```
testysqlrlgpwithtransactiontablesandwaitqueues-aws-rf3-geo-partition-multiregion: Start
	(     0.547s) User Login : Success
	(     0.187s) Refresh YB Version : Success
	(   120.519s) Setup Provider : Success
	(     0.048s) Updating Health Check Interval to 60000 sec : Success
	(  1781.252s) Create universe kmoh-6da6167592-20230704-063225 : Success
	(   101.247s) Create database transactions_db : Success
	(   208.163s) Create tablespace, parent table and geo partitioned tables : Success
	(     2.387s) Verify cluster is load balanced : Success
	(     2.471s) Verify geo partitioned transaction tables are created automatically : Success
	(    17.412s) Insert rows into the table : Success
	(     0.000s) Start running contentious transactions with Read committed isolation level : Success
	(     0.000s) Attempting Contentious transactions on transactions table : Success
	(    93.101s) Attempting Contentious transactions on transactions table : >>> Integration Test Failed <<< 
Move transaction status: Transaction 8bc626a9-de15-4b49-8d14-dcb8ddde47e1 expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_participant.cc:1202): Move transaction status: Transaction 8bc626a9-de15-4b49-8d14-dcb8ddde47e1 expired or aborted by a conflict: 40001 (pgsql error 40001)]

	(    55.005s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.19.1.0_testysqlrlgpwithtransactiontablesandwaitqueues-aws-rf3-geo-partition-multiregion_20230704_080548 : Success
	(   127.644s) Destroy universe : Success
	(     0.252s) Check and stop workloads : Success
testysqlrlgpwithtransactiontablesandwaitqueues-aws-rf3-geo-partition-multiregion: End
```

P.S. The same scenario passes for repeatable read isolation level

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7123]: https://yugabyte.atlassian.net/browse/DB-7123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
cc @es1024

**Comment by rthallamko3** [comment]
@Karvy-yb , Can we enable verbose gflags before running the 4 threads that contend on the same row. cc @es1024 to provide the set of files that can help.

**Comment by Karvy-yb** [comment]
@rthallamko3 sure, let me know the gflags. I'll trigger a run for the test with those gflags and keep_universe

**Comment by es1024** [comment]
@Karvy-yb `vmodule` gflag set to `transaction=2,transaction_coordinator=4,conflict_resolution=4`

**Comment by Karvy-yb** [comment]
@es1024 this needs to be set on master/tserver?

**Comment by es1024** [comment]
@Karvy-yb just tserver is fine

**Comment by bmatican** [comment]
@Karvy-yb @es1024  were we ever able to get more signal on this?

**Comment by Karvy-yb** [comment]
@bmatican this is on my TO-DO for this week. Will share the results here soon. (cc: @es1024 )
My apologies for the delay in respose, i missed this notification when I cam back from my PTO.

**Comment by Karvy-yb** [comment]
@rthallamko3 tracking it here: https://yugabyte.atlassian.net/browse/YQ-1226

**Comment by Karvy-yb** [comment]
@rthallamko3 @es1024 The test is failing on master due to some other issue and I am unable to repro this issue now (with the flags) on the original version mentioned in the ticket. Trying couple of other things. Will update the thread as soon as I have some conclusion.

**Comment by Karvy-yb** [comment]
I was able to reproduce the issue with given vmodule gflags on `2.20.0.0-b14`
Run:https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/8842/testReport/junit/(root)/TestYsqlRLGPWithTransactionTablesAndWaitQueues/testysqlrlgpwithtransactiontablesandwaitqueues_aws_rf3_geo_partition_multiregion/
