### ISSUE TITLE
[DocDB] Avoid Prometheus metric regex match by adding cache

### ISSUE THREAD

**Issue by yusong-yan** [yugabyte/yugabyte-db#18090]
Jira Link: [DB-7130](https://yugabyte.atlassian.net/browse/DB-7130)
### Description

Currently, Prometheus metric scrape is done by sending a request to the DB Prometheus endpoints every 10s. For example,
`http://127.0.0.1:9000/prometheus-metrics?priority_regex=<metrics that we want>`.
URL param `priority_regex` is used as a filter, so the user can customize what metrics to export. And on the DB side, when it receives the request, it will do the regular expression match on every metric name for one Prometheus metric scrape. 

Normally, the 10s periodic scrapes send requests with same regex string. Therefore, it is unnecessary to repeatedly do the regex match for every 10s. We can avoid this by adding a cache, which will boost performance because regex matches can be expensive when there are a lot of tablets.
Moreover, we might add more regex URL params in the future, so this caching functionality really makes the Prometheus metrics scrape more scalable.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7130]: https://yugabyte.atlassian.net/browse/DB-7130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yusong-yan** [comment]
@mdbridge and I verified that adding cache doesn't provide as much improvement as we thought. Tested with 2000 tables, the improvement is less than 0.1 seconds by using cache.

**Comment by rthallamko3** [comment]
Per @yusong-yan , We do not need this anymore. Closing it.
