### ISSUE TITLE
[YSQL] Support for PostgreSQL parallelism for IndexScan/IndexOnlyScans 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#18094]
Jira Link: [DB-7134](https://yugabyte.atlassian.net/browse/DB-7134)
### Description

Support for PostgreSQL parallelism for IndexScan/IndexOnlyScans.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7134]: https://yugabyte.atlassian.net/browse/DB-7134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
Handled by [2f91e3e](https://github.com/yugabyte/yugabyte-db/commit/2f91e3ef37754c96d5074cd33fa2e4c401c52513)
