### ISSUE TITLE
[YSQL] Support for PostgreSQL parallelism for Aggregation plan node

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#18093]
Jira Link: [DB-7133](https://yugabyte.atlassian.net/browse/DB-7133)
### Description

Add support for PostgreSQL parallelism for Aggregation plan node. 
https://www.postgresql.org/docs/11/parallel-plans.html#PARALLEL-AGGREGATION 

Add support for pushdown of aggregates with PG parallelism.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7133]: https://yugabyte.atlassian.net/browse/DB-7133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
The same as #19839, but other ticket has more detailed explanation.
Fixed by [fd5136c](https://github.com/yugabyte/yugabyte-db/commit/fd5136c6822d9b8d6053c25eb4360d886630f43d)
