### ISSUE TITLE
[YSQL] Support for PostgreSQL parallelism for Parallel Append plan node

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#18092]
Jira Link: [DB-7132](https://yugabyte.atlassian.net/browse/DB-7132)
### Description

Support for PostgreSQL parallelism for Parallel Append. 

https://www.postgresql.org/docs/11/parallel-plans.html#PARALLEL-APPEND 
This feature should also be controllable using [enable_parallel_append](https://www.postgresql.org/docs/11/runtime-config-query.html#GUC-ENABLE-PARALLEL-APPEND) . 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7132]: https://yugabyte.atlassian.net/browse/DB-7132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
Append does not require any extra effort, it works as soon as generic parallel query works.
Handled by [2f91e3e](https://github.com/yugabyte/yugabyte-db/commit/2f91e3ef37754c96d5074cd33fa2e4c401c52513), closing.
