### ISSUE TITLE
[DocDB] Transaction Participant not tracking recently removed transactions centrally

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#18100]
Jira Link: [DB-7138](https://yugabyte.atlassian.net/browse/DB-7138)
### Description

When a transaction is aborted due to involvement in a deadlock, we might return a status ok for the last executed statement since the write doesn't check with the transaction coordinator on the latest status. 
But if the subsequent statements end up at a different tablet, the corresponding transaction participant doesn't recognize that the transaction has been aborted, and ends up tracking it.

here's a test that introduces cyclic deadlocks. There should be at least k-1 deadlocks observed, but it isn't the case.
```
TEST_F(PgWaitQueuesTest, YB_DISABLE_TEST_IN_TSAN(TestDeadlockErrorMessage)) {
  constexpr int kNumTxns = 3;

  auto setup_conn = ASSERT_RESULT(Connect());
  ASSERT_OK(setup_conn.Execute("CREATE TABLE foo (k INT PRIMARY KEY, v INT)"));
  ASSERT_OK(setup_conn.ExecuteFormat(
      "INSERT INTO foo SELECT generate_series(0, $0), 0", kNumTxns));

  CountDownLatch num_keys_locked(kNumTxns);
  CountDownLatch did_deadlock(kNumTxns - 1);
  TestThreadHolder thread_holder;
  for (auto i = 0; i < kNumTxns ; i++) {
    thread_holder.AddThreadFunctor([this, &num_keys_locked, &did_deadlock, i] {
      auto conn = ASSERT_RESULT(Connect());
      ASSERT_OK(conn.StartTransaction(IsolationLevel::SNAPSHOT_ISOLATION));
      ASSERT_OK(conn.ExecuteFormat("UPDATE foo SET v=v+10 WHERE k=$0", i));
      num_keys_locked.CountDown();
      num_keys_locked.WaitFor(3s * kTimeMultiplier);
      for (auto j = 1 ; j < kNumTxns ; j++) {
        auto s = conn.ExecuteFormat("UPDATE foo SET v=v+10 WHERE k=$0", (i + j) % kNumTxns);
        if (!s.ok()) {
          LOG(INFO) << "Thread " << i << " aborted due to a deadlock";
          did_deadlock.CountDown();
          return;
        }
      }
    });
  }

  ASSERT_TRUE(did_deadlock.WaitFor(25s * kTimeMultiplier));
  thread_holder.WaitAndStop(15s * kTimeMultiplier);
}
```

cc: @robertsami 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7138]: https://yugabyte.atlassian.net/browse/DB-7138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@basavaraj29 , This is with wai-on-conflict feature right? Do we need it for EA/GA timeframe?

**Comment by basavaraj29** [comment]
> @basavaraj29 , This is with wai-on-conflict feature right? Do we need it for EA/GA timeframe?

In my opinion, we do require it. But will defer to @robertsami for thoughts in this.

**Comment by basavaraj29** [comment]
updated the summary to reflect the latest findings.

**Comment by basavaraj29** [comment]
update - the participant polls for all managed transactions to check if any of them have been aborted periodically. so even if a participant starts tracking an already aborted transaction (due to involvement in a deadlock), it realizes this soon and removes it.

It could still happen that the transaction doesn't error on the newer statements that hit new tablets, and only does error during commit. But that should be okay, else the participant will need to check with the transaction coordinator every time it starts to track a new transaction (which would add in-line latency).
