### ISSUE TITLE
[YSQL] No results are returned for yb_lock_status() when UPDATE lock is waiting for another lock

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18149]
Jira Link: [DB-7189](https://yugabyte.atlassian.net/browse/DB-7189)
### Description

Steps to repro:
```
1. Create universe with enable_wait_queues, enable_deadlock_detection and enable_pg_locks flags. (Created on custom build)
2. Create database
3. Connect to database
4. create table tb(k int primary key, v int);
5. insert into tb values (1,1), (2,2);
6. txn_1: begin; select * from tb where k=1 for update;
7. On 2nd session: select * from yb_lock_status();
8. Notice that results are returned
9. On another session: update tb set v=11 where k=1; (This will wait for txn_1)
10. On 2nd session: select * from yb_lock_status();
11. Notice that no rows are returned
```
The issue is only observed when UPDATE lock is waiting for another lock (be it in fastpath or begin/commit transaction)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7189]: https://yugabyte.atlassian.net/browse/DB-7189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
Tested it latest master + get lock status patch. I can see an error being returned. 
```
yugabyte=# select * from yb_lock_status(null, null);
ERROR:  While decoding SubDocKey "G\x12\x10H\x80\x00\x00\x01!!J\x80!": Cannot decode value type kGroupEnd from the key encoding format: "!"
```

there seems to be an issue while decoding a few lock types at the wait-queue level. will look into it.
