### ISSUE TITLE
[YCQL] PITR Failed at Restore after triggering manual split with FATALs and Master is down when YCQL packed enabled

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#18146]
Jira Link: [DB-7186](https://yugabyte.atlassian.net/browse/DB-7186)
### Description

Test name: `testycqlpitrwithmanualtabletsplitting`

- Test failing 2.16.6.0-b18 onwards
- Scenario attempted on 2.16.6.0-b34
- 100% repro-able
- It is observed that this issue was not observed when `ycql_enable_packed_row` was disabled

When we try to restore PITR  
`Failed to restore snapshot from schedule: 622eff0b-03c4-4476-a508-685b0b29af3a: recvmsg got EOF from remote (system error 108) `

FATAL
```
Log file created at: 2023/07/09 18:42:12
Current UTC time: 2023/07/09 18:42:12
Running on machine: ip-10-9-120-253.us-west-2.compute.internal
Application fingerprint: version 2.16.6.0 build 34 revision 6a711defaba6ce4dd88d33ac0465a4e0d30723bd build_type RELEASE built at 08 Jul 2023 04:57:27 UTC
Node information: { hostname: 'ip-10-9-120-253.us-west-2.compute.internal', rpc_ip: '10.9.120.253', webserver_ip: '10.9.120.253', uuid: 'd849fb64d6724580900970265f468be3' }
Running duration (h:mm:ss): 0:00:03
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0709 18:42:12.086946 21047 operation_driver.cc:398] T 00000000000000000000000000000000 P d849fb64d6724580900970265f468be3 S RD-P Ts { physical: 1688928110982145 } kSnapshot (0x000055c09f46c7e0): Apply failed: Not found (yb/docdb/schema_packing.cc:180): Restore sys catalog failed: Schema packing not found: 0, available_versions: [1], request: operation: RESTORE_SYS_CATALOG snapshot_id: "g\272yC6\220D\014\265Gls\220\251\237\310" snapshot_hybrid_time: 6917848416404856832 restoration_id: "\252\013\307/^#D\205\202\331_\234\366\021\314\257"
```

Steps:
```
        1. Create a Universe
        2. Create a Keyspace, table
        3. Create a snapshot schedule
        4. Insert 5k rows
        5. Collect Absolute time
        6. Trigger a manual split on the tablets of the above table
        7. Insert another 6k rows
        8. Restore to the collected time in #5
```
Issue observed at step#8

Attached logs: https://drive.google.com/file/d/1t-S0ZhUBaLOdERReO_ck-FwE65fQaw73/view?usp=sharing

G-Flags:
Master Value
```
{
     "callhome_enabled": "false",
     "ycql_enable_packed_row": "true"
}
```
Tserver Value
```
{
     "callhome_enabled": "false",
     "ycql_enable_packed_row": "true"
}
```
cc: @Arjun-yb , @kripasreenivasan 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7186]: https://yugabyte.atlassian.net/browse/DB-7186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment]
FYI: @zlareb1-yb . This was before you landed https://phorge.dev.yugabyte.com/D26787

**Comment by bmatican** [comment]
@agsh-yb @kripasreenivasan can we close this then? was this testing YCQL packed on 2.16?
