### ISSUE TITLE
[DocDB] Flaky unit test: CDCServiceTestThreeServers.TestNewLeaderUpdatesLogCDCAppliedIndex

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18156]
Jira Link: [DB-7196](https://yugabyte.atlassian.net/browse/DB-7196)
### Description

Unit test `CDCServiceTestThreeServers.TestNewLeaderUpdatesLogCDCAppliedIndex` started failing after this commit https://github.com/yugabyte/yugabyte-db/commit/9b22962fdb04120c98b590446892e62ee4edc6c2

[Test Stability Report](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCServiceTestThreeServers&fail_tag=all&name=TestNewLeaderUpdatesLogCDCAppliedIndex&num_commits=500&platform=all)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7196]: https://yugabyte.atlassian.net/browse/DB-7196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/3085/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-integration-tests__cdc_service-int-test/CDCServiceTestThreeServers_TestNewLeaderUpdatesLogCDCAppliedIndex.log

../../src/yb/integration-tests/cdc_service-int-test.cc:2292
Expected equality of these values:
  tablet_peer->log()->cdc_min_replicated_index()
    Which is: 9223372036854775807
  5

**Comment by hari90** [comment]
The issue is that the cdc_state table tablet did not get a new leader in time.

Test has the following comment which does not appear to be true

  // Wait until GetChanges doesn't return any errors. This means that we are able to write to
  // the cdc_state table.
