### ISSUE TITLE
[YSQL] Flaky unit test: XClusterTopologiesTestClusterFailure.TestBroadcastWithConsumerFailure

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18154]
Jira Link: [DB-7194](https://yugabyte.atlassian.net/browse/DB-7194)
### Description

Unit test `XClusterTopologiesTestClusterFailure.TestBroadcastWithConsumerFailure` has been flaky on master.
[Stability Report](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=XClusterTopologiesTestClusterFailure&fail_tag=all&name=TestBroadcastWithConsumerFailure&num_commits=500&platform=linux)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7194]: https://yugabyte.atlassian.net/browse/DB-7194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mdbridge** [comment]
fixed via D27215 / xCluster: fix flaky XClusterTopologies tests

**Comment by mdbridge** [comment]
note that as of today (7/25/2023) a related test, TestBroadcastWithProducerFailure,  is occasionally detecting a real bug which qhu  is actively working on fixing.  That is not a case of a flaky test.
