### ISSUE TITLE
Ability to copy data between tables

### ISSUE THREAD

**Issue by nickhristov** [yugabyte/yugabyte-db#1819]
One of the current limitations of YB is that there is no way to add a secondary index to a table after the table has been created.

One of the ways to address this issue is to create a new table and copy the existing data in that table. This process in not very simple in a system where data is constantly being inserted, and there are no commands native to YB which can do this at the moment.

In order for this use case to be solved fully, one would need to:

1. set up data mirroring between the old table and the new table (which will hold the next index). this will handle any new inserts which are coming in the old table and insert them in the new table as well as the old table.
1. copy the old table in the new table
1. disable the mirroring in step 1
1. drop old table, rename new table to old table

Step 4 cannot really happen without some assistance from an external client application, unless YB supports some form of table aliases (like a symbolic link).

The most practical step to solve in this problem is to implement a command for step 2 above, and leave the rest to the client applications to manage.

**Comment by amitanandaiyer** [comment]
@nickhristov  We are working on a "backfill index" feature that will allow users to add an index after the table has been created -- and will take care of regenerating the index entries for the data that is already present. That I think would be the cleanest way to handle the issue.

**Comment by ndeodhar** [comment]
@nickhristov To add to what @amitanandaiyer said, if you're interested, you can track the index backfill feature here: https://github.com/YugaByte/yugabyte-db/issues/448

**Comment by rthallamko3** [comment]
DUP of https://github.com/yugabyte/yugabyte-db/issues/448
