### ISSUE TITLE
[DocDB] 2.16.6.0  'Query error: Schema packing not found' in the source universe of an Xcluster replication setup containing a colocated schema with YSQL packed rows enabled

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#18209]
Jira Link: [DB-7229](https://yugabyte.atlassian.net/browse/DB-7229)
### Description

Note:
- Issue observed in 2.16.6.0-b20 onwards. The test last passed in b19.
- 100% deterministic repro available with automation- TestYSQLXClusterWithColocation.testysqlxclusterwithcolocation-aws-rf3
- The issue is seen only in 2.16.6 and not in 2.18 and master.

**Steps:**
1. Create a source and target universe with the following gflags-
```
"scheduled_full_compaction_frequency_hours": "12",
"scheduled_full_compaction_jitter_factor_percentage": "100",
"scheduled_full_compaction_check_interval_min": "5",
"ysql_enable_packed_row_for_colocated_table": "true",
"ysql_enable_packed_row": "true"
```
2. Create a colocated database, 10 colocated tables, 1 non-colocated table inside the database at the source universe
3. Create a backup of the source universe
4. Restore the backup to the target universe
5. Setup xcluster replication from source to target.
6. Setup xcluster replication from target to source.
7. Insert rows in all the colocated tables in the  source universe 
8. Collect data in the colocated tables in source and target universe
**Issue:** 
On executing a select * on one of the colocated tables in the source universe, this error is returned and this error does not go away-
```
xcluster_with_colocation=#  select * from colocated_table_0;
ERROR:  Query error: Schema packing not found: 3, available_versions: [0]
```

**Please note that the issue is not reproducible with YSQL packed rows turned off.**

Logs: https://drive.google.com/drive/folders/1ScgefIsvhOSqpAfIWmPypaGgzpHLpuzN?usp=sharing  

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7229]: https://yugabyte.atlassian.net/browse/DB-7229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@kripasreenivasan , There are two aspects here: 
1. Colocation GA happened in 2.18.0 timeframe.
2. The support for PackedRow + xCluster + colocation support is also in 2.18.0 branch onwards only.

As such, we should not be testing xCluster + Packed + colocation in branches below 2.18. cc @lingamsandeep 

Can we close this issue?

**Comment by rthallamko3** [comment]
@kripasreenivasan  to follow up on updating the test to run on 2.18 branches onwards.
