### ISSUE TITLE
[YSQL] currently, the PRIMARY KEY constraint has to be specified as part of the CREATE TABLE itself (inline). 

### ISSUE THREAD

**Issue by ramanans** [yugabyte/yugabyte-db#1822]
Support ALTER TABLE with ADD CONSTRAINT for PRIMARY KEY
ERROR: This ALTER TABLE command is not yet supported. [Failed SQL: ALTER TABLE public.DATABASECHANGELOG ADD CONSTRAINT PK_DATABASECHANGELOG PRIMARY KEY (ID, FILENAME, AUTHOR)]

**Comment by ndeodhar** [comment]
Thanks for reporting this @ramanans. Related issue: https://github.com/YugaByte/yugabyte-db/issues/1104

**Comment by bllewell** [comment]
See also Issue #3163.

**Comment by m-iancu** [comment]
Closing as this was mostly addressed as part of #1104.
