### ISSUE TITLE
[YSQL] Create Index failing in Geo-Partitioned cluster

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#18228]
Jira Link: [DB-7238](https://yugabyte.atlassian.net/browse/DB-7238)
### Description

While creating a secondary index for a colocated table in a geo-partitioned setup, it is sometimes giving out this error:

```
psycopg2.errors.InternalError_: timed out waiting for postgres backends to catch up
DETAIL:  -1 backends on database 16385 are still behind catalog version 43.
HINT:  Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE catalog_version < 43 AND datid = 16385;
```

Detailed logs: [https://jenkins.dev.yugabyte.com/job/itest-system-developer/7280/artifact/logs/2.19.1.0_t[…]layer-aws-rf3-geo-partition-multiregion_20230712_192843/](https://jenkins.dev.yugabyte.com/job/itest-system-developer/7280/artifact/logs/2.19.1.0_testgeopartitioningwithysqllanguagelayer-aws-rf3-geo-partition-multiregion_20230712_192843/)

Steps done before creation of indexes:

> 1. Created Geo-Partitioned universe, colocated table
> 2. Loaded 3000 rows
> 3. A flush and compaction
> 4. Create index and materialized view.
> 5. Create colocated database
> 6. Create colocated table
> 7. repeat step 2 and 3
> 8. Create index then fails sometimes fail with above mentioned error. A very basic create index:  CREATE INDEX table_range_secondary_index ON employees_col(i3 )

Create index is waiting for more than 5 minutes.

```
2023-07-12 21:25:42,139 system_utils.py:935 INFO testgeopartitioningwithysqllanguagelayer-aws-rf3-geo-partition-multiregion Create YSQL secondary index: table_range_secondary_index
INFO:root:Create index query: CREATE INDEX table_range_secondary_index ON employees_col(i3 )
2023-07-12 21:25:42,139 database_operations.py:1458 INFO testgeopartitioningwithysqllanguagelayer-aws-rf3-geo-partition-multiregion Create index query: CREATE INDEX table_range_secondary_index ON employees_col(i3 )
INFO:root:Closing <connection object at 0x7f27b00b4040; dsn: 'user=yugabyte dbname=gp_language_layer_col host=172.151.26.110 port=5433 options='-c statement_timeout=800000'', closed: 0> connection.
2023-07-12 21:30:43,233 database_operations.py:43 INFO testgeopartitioningwithysqllanguagelayer-aws-rf3-geo-partition-multiregion Closing <connection object at 0x7f27b00b4040; dsn: 'user=yugabyte dbname=gp_language_layer_col host=172.151.26.110 port=5433 options='-c statement_timeout=800000'', closed: 0> connection.
INFO:root:Connection closed to <connection object at 0x7f27b00b4040; dsn: 'user=yugabyte dbname=gp_language_layer_col host=172.151.26.110 port=5433 options='-c statement_timeout=800000'', closed: 1>
2023-07-12 21:30:43,233 database_operations.py:48 INFO testgeopartitioningwithysqllanguagelayer-aws-rf3-geo-partition-multiregion Connection closed to <connection object at 0x7f27b00b4040; dsn: 'user=yugabyte dbname=gp_language_layer_col host=172.151.26.110 port=5433 options='-c statement_timeout=800000'', closed: 1>
ERROR:root:ITEST FAILED testgeopartitioningwithysqllanguagelayer-aws-rf3-geo-partition-multiregion : InternalError_('timed out waiting for postgres backends to catch up\nDETAIL:  -1 backends on database 16390 are still behind catalog version 43.\nHINT:  Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE catalog_version < 43 AND datid = 16390;\n')
```

Test Case Steps:
```
(  1697.012s) Create universe rjal-74308d9a2f-20230712-192511 : Success
(   135.547s) Create Database gp_language_layer : Success
(    67.145s) Create Colocated Database gp_language_layer : Success
(  1662.079s) Create tablespace, parent table and geo partitioned tables : Success
(     2.776s) Verify geo partitioned transaction tables are created automatically : Success
(  4077.452s) Load data to transactions : Success
(   147.405s) Verify tablet count for copy table: transactions_temp : Success
(    72.740s) Create Secondary Index. : Success
(    75.296s) Create Unique Index. : Success
(    75.129s) Create Partial Index. : Success
(    72.752s) Create Secondary Index. : Success
(    74.223s) Create Unique Index. : Success
(    70.340s) Create Partial Index. : Success
(    63.735s) Create indexes and materialized view : Success
(    27.672s) Create Functions, Triggers : Success
(    52.049s) Execute Triggers : Success
(  4455.914s) Load data to employees_col : Success
(   119.957s) Verify tablet count for copy table: employees_col_temp : Success
(   318.091s) Create indexes and materialized view : >>> Integration Test Failed <<< 
timed out waiting for postgres backends to catch up
DETAIL:  -1 backends on database 16385 are still behind catalog version 43.
HINT:  Run the following query on all tservers to find the lagging backends: SELECT * FROM pg_stat_activity WHERE catalog_version < 43 AND datid = 16385;
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7238]: https://yugabyte.atlassian.net/browse/DB-7238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
(Old internal discussion follows)

The reason is lots of catalog requests, such as pg_operator.  Only this node has the issue because it is in ap-south and the other nodes are in US, master leader also US.  It could be considered the user's responsibility to turn on flags such as ysql_enable_read_request_caching and ysql_catalog_preload_additional_tables: this will probably make the issue go away.  Things we can do:

- Preferred: Give a different errhint that suggests turning on these flags when -1 backends is detected (-1 backends suggests master-tserver RPC never properly communicated).
- Increase the timeout: Since catalog RPCs are likely to be constant for all clusters, the upper bound for this is likely around 1m.  Then, the master-tserver RPC timeout could be increased from 20s to 1m, and the problem will likely disappear.  A disadvantage is that this can hide future problems about long RPCs.
- Use a single (or pool of) dedicated connection(s) for tserver-local-postgres queries: This can avoid the connection-startup lag in most cases.  It is still going to have lag whenever catalog version bump happens, which forces cache refresh.

**Comment by Karvy-yb** [comment]
I am observing this error 100% of the times when trying to create (non-colocated) tables and indexes on a geopartitioned universe running SqlGeoTransactions workload. Do we have an ETA for the resolution as it blocks automation development for wait-on-conflict stress test cases?

**Comment by jasonyb** [comment]
@Karvy-yb, according to the above comment, a plan is to change an error message and nothing more.  Are those flags turned on or not?

**Comment by Karvy-yb** [comment]
@jasonyb I did enable those flags and am still running into this error.

**Comment by Karvy-yb** [comment]
The issue I am running into is a different one. The error reports positive number backends behind catalog version.
cc: @jasonyb
