### ISSUE TITLE
[YSQL] DELETE ... WHERE NOT EXISTS throws system column id -1 not supported error

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1828]
To reproduce:
1. Create database exercises.

2. Create DDLs and load data using these:
[clubdata_ddl.sql](https://raw.githubusercontent.com/YugaByte/yugabyte-db/master/sample/clubdata_ddl.sql) which creates tables and other database objects
[clubdata_data.sql](https://raw.githubusercontent.com/YugaByte/yugabyte-db/master/sample/clubdata_data.sql) which loads the sample data into the exercises database

3. Now that you have the database and data, run this (from https://pgexercises.com/questions/joins/simplejoin2.html)

```
delete from cd.members mems where not exists (select 1 from cd.bookings where memid = mems.memid);
```

Note that replacing `delete` with `select` works as expected:
```
select * from cd.members mems where not exists (select 1 from cd.bookings where memid = mems.memid);
 memid | surname | firstname |            address             | zipcode |   telephone    | recommendedby |      joindate       
-------+---------+-----------+--------------------------------+---------+----------------+---------------+---------------------
    37 | Smith   | Darren    | 3 Funktown, Denzington, Boston |   66796 | (822) 577-3541 |               | 2012-09-26 18:08:45
(1 row)
```

**Comment by srhickma** [comment]
This should be fixed by 9f4c158 (tested locally with a couple cases).
