### ISSUE TITLE
Authentication and authorization in YB

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#183]
Reported by @rkarthik007.

**Comment by rkarthik007** [comment]
This is a master task with the following sub-tasks:

## Cassandra API

- [#360] Add username/password based authorization for YCQL
- [#72] Add Cassandra ROLE support
- [#73] Add Cassandra Permissions support

## Redis API

- [#156] Basic password-based authentication
- [#157] Support multiple password support for Redis authentication

**Comment by hectorgcr** [comment]
We have added these features to YB.
