### ISSUE TITLE
[DocDB] During bootstrap, read entries from last flushed op id offset instead of the beginning of the segment

### ISSUE THREAD

**Issue by Huqicheng** [yugabyte/yugabyte-db#18312]
Jira Link: [DB-7302](https://yugabyte.atlassian.net/browse/DB-7302)
### Description

The bootstrap process is:
1. Bootstrap optimizer to get the first segment to start replaying.
2. Replaying all segments in order from the first segment:
         Read all entries from the segment
         Traverse the entries and replay them

For non-colocated tables, op ids <= last flushed op id (min between RocksDB and retryable requests) can be skipped, so it's unnecessary to read them.

For colocated tables, if lazy_flush_superblock is enabled, it needs at least two segments to replay change metadata ops, so if the min id between RocksDB and retryable requests is newer than the first op in the penultimate segment, it should still replay from the beginning of the penultimate segment. (TODO: leverage the last flushed op id in superblock, consider about flushing the last committed op id instead of the last change metadata op id).

To achieve this, when doing clean shutdown, log index should also be flushed to disk. During restart, the offset of the last op id could be read from LogIndex and ReadEntries can read starting from there.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7302]: https://yugabyte.atlassian.net/browse/DB-7302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Closing this for now. If necessary, we can backport to 2.20 branch.
