### ISSUE TITLE
[YSQL] YugabyteDB locks nonexistent rows where PostgreSQL doesn't

### ISSUE THREAD

**Issue by foucher** [yugabyte/yugabyte-db#18320]
Jira Link: [DB-7309](https://yugabyte.atlassian.net/browse/DB-7309)
### Description

Setup:
```
CREATE TABLE t (k int PRIMARY KEY);
```
Session 1:
```
BEGIN ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM t WHERE k=1 FOR UPDATE;
```
Session 2:
```
BEGIN ISOLATION LEVEL SERIALIZABLE;
INSERT INTO t VALUES (1);
```

PG behavior: The insert completes, both transactions can commit.
YB behavior: The insert blocks.

Due to #18316, this currently happens in other isolation modes as well, but I believe the behavior in isolation level SERIALIZABLE was preexisting.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7309]: https://yugabyte.atlassian.net/browse/DB-7309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment]
If we match Pg semantics for this case in serializable, we will end up breaking serializability. Pg uses SSI for implementing serializability which catches cases that might break serializability by a specific r-w cycle detection algorithm. This algorithm is better (i.e., causes lesser conflicts) than two-phase locking that YugabyteDB uses for serializable isolation. That is the reason this behaviour is seen in Pg. If we match that, we would break our serializability.
