### ISSUE TITLE
[YSQL][pg_locks] : subtransactionid is populated with '0' instead of null for waiting transactions

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18337]
Jira Link: [DB-7325](https://yugabyte.atlassian.net/browse/DB-7325)
### Description

Subtransactionid is not being populated yet for waiting transactions. In such a case we should be populating the result with null, like other unpopulated columns, instead of a zero.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7325]: https://yugabyte.atlassian.net/browse/DB-7325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
Resolved by:
https://github.com/yugabyte/yugabyte-db/issues/18355

note that we should not populate null but instead should always populate the subtransaction_id of the waiter correctly
