### ISSUE TITLE
[YSQL] : Locks don't get released even after termination of session with transaction holding the lock 

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18336]
Jira Link: [DB-7324](https://yugabyte.atlassian.net/browse/DB-7324)
### Description

Steps to repro:
1. create universe on 2.19.1.0-b337 DB version with read committed, wait queues and deadlock detection enabled (pg-locks is enabled by default).
2. create table tb (k int primary key, v int);
3. insert into tb values(1,1), (2,2), (3,3);
4. S1: begin;
5. S1: select;
6. S1: select * from tb where k=1 for update;
7. S2: select * from pg_locks; -- Entries from transaction triggered in S1 will be there
8. Close/kill terminal running S1 
9. S2: select * from pg_locks;

Notice that the entries from transaction in S1 will still be displayed. Querying pg_locks after ~2hrs still results in the same output. 
Also, if we try to acquire lock on the same row in a different session at this point, the statements will conflict and wait for the transaction from S1 which has already been killed.

Another thing to note here is that we don't see similar behaviour for locks that haven't been granted yet, i.e. this only happens for locks that have been granted.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7324]: https://yugabyte.atlassian.net/browse/DB-7324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Karvy-yb** [comment]
I did some debugging and turns out this only happens for universe on k8s platforms so, probably the process running inside the pod don’t get terminated when we close the terminal which is why i think we are observing this issue.

**Comment by robertsami** [comment]
@Karvy-yb is the session itself running in a k8s container? did you confirm the pg process is still running after the ysqlsh session is killed?

**Comment by Karvy-yb** [comment]
The issue occurs because the processed aren't killed for within k8s container once we close the connection to it. Closing the issue as this isn't related to DB.
