### ISSUE TITLE
Cannot change listen_addresses to '*'

### ISSUE THREAD

**Issue by realyota** [YugaByte/yugabyte-db#1833]
I'm editing postgresql.conf file in node-1:

`listen_addresses = '*'`

After restarting the cluster giving the sql command:

`show listen_addresses`

is still 127.0.01. How can I fix it?

**Comment by d-uspenskiy** [comment]
It looks like `listen_addresses` parameter from `postgresql.conf` is not used.
Listen address is provided to `postgresql` process via command line argument by `t-server` process.

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/tserver/tablet_server_main.cc#L163

`t-server` gets it from gflag. And it can be set with the following arguments while starting cluster

```
yb-ctl start --tserver_flags "pgsql_proxy_bind_address=*"
```

**Comment by realyota** [comment]
That's fixing the issue. Thank you.
