### ISSUE TITLE
[YSQL] [pg_locks] : Locks are still being listed in pg-locks even after being rolledback to a savepoint

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18338]
Jira Link: [DB-7326](https://yugabyte.atlassian.net/browse/DB-7326)
### Description

Steps to repro:
1. Create universe on 2.19.1.0-b337 DB version with read committed, wait queues and deadlock detection enabled (pg_locks is enabled by default)
2. create table tb(k int primary key, v int);
3. insert into tb values(1,1), (2,2), (3,3);
4. S1: begin;
5. S1: select;
6. S1: select * from tb where k=1 for update;
7. S1: savepoint sp1;
8. S1: select * from tb where k=2 for update;
9. S1: select * from tb where k=3 for update;
10. S2: begin;
11. S2: select;
12. S2: select * from tb where k=3 for update; -- this will wait for transaction in S1
13. S3: select * from pg_locks; -- All expected rows will be present
14. S1: rollback to sp1; -- Notice that transaction in S2 will stop waiting and get the lock
15. S3: select * from pg_locks;

Notice that the results will still show the entries from lock in step 8 and 9 which have been released due to rollback to savepoint.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7326]: https://yugabyte.atlassian.net/browse/DB-7326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
dupe: https://github.com/yugabyte/yugabyte-db/issues/18415
