### ISSUE TITLE
[YSQL] [pg_locks] : subtransactionid for statements followed by a savepoint are not same

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18339]
Jira Link: [DB-7327](https://yugabyte.atlassian.net/browse/DB-7327)
### Description

My understanding is that subtransaction ids for all statements followed by a savepoint should be same. Discussed the same with @basavaraj29 and he concurs, but the behaviour I see is contrary.

Steps to repro:
1. Create universe on version 2.19.1.0-b337 with read committed, wait queues and deadlock detection enabled (pg_locks is enabled by default)
2. create table tb(k int primary key, v int);
3. insert into tb values(1,1), (2,2), (3,3);
4. begin;
5. select;
6. select * from tb where k=1 for update;
7. savepoint sp1;
8. select * from tb where k=2 for update;
9. select * from tb where k=3 for update;
10. New session: select * from pg_locks;

Notice that entries corresponding to locks acquired in steps 8 and 9, both of them will have different subtransaction ids.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7327]: https://yugabyte.atlassian.net/browse/DB-7327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
turns out this is expected behavior when `yb_enable_read_committed_isolation` is enabled, each statement is treated as an internal subtxn.
