### ISSUE TITLE
[YSQL] WARNING:  'vacuum' is a beta feature!

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#18330]
Jira Link: [DB-7316](https://yugabyte.atlassian.net/browse/DB-7316)
### Description

Currently, running vacuum shows the following message:
```
WARNING:  'vacuum' is a beta feature!
WARNING:  VACUUM will be ignored
VACUUM
```
This is misleading for users coming from PostgreSQL as they may think that we don't garbage collect the dead tuples.
Can we have another message here that says explicitly that VACUUM is a no-op in YugabyteDB because there's no need for vaccuum.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7316]: https://yugabyte.atlassian.net/browse/DB-7316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vrmamukul** [comment]
Hi @FranckPachot, I Mukul here and currently starting my journey with open source. I found this issue to be a perfect way to begin with. Let me know if I can work on this.

**Comment by FranckPachot** [comment]
Hi Mukul, yes, great idea!

**Comment by vrmamukul** [comment]
I am not able to access the Jira Ticket link above. Will it be possible for you to add me (email: vmukul044@gmail.com)?

**Comment by FranckPachot** [comment]
@vrmamukul JIRA tickets are opened automatically but there's no more information (I'll check with colleagues to be sure)

**Comment by FranckPachot** [comment]
I confirm there's nothing more in JIRA. This is used only with bugs that contain customer private information but not the case here.
All is in github, and you can also ask question in the `#contributors` channel of the [community slack](https://join.slack.com/t/yugabyte-db/shared_invite/zt-xbd652e9-3tN0N7UG0eLpsace4t1d2A)
