### ISSUE TITLE
Add a native health checking endpoint

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1834]
Jira Link: [DB-2553](https://yugabyte.atlassian.net/browse/DB-2553)
Currently, there's a handful of things we check across the board, for telling if a server is in good condition. Many of these are logical level stats, such as:
- are any of the TS is marked dead in the master
- have any of the servers restarted lately
- is the load balancer busy moving tablets/leaders around
- are any tablets currently underreplicated
- do any of the TS have tablets they were not able to start up
- can we talk to the TS on YEDIS/YCQL/YSQL
- are any of the threads stuck
- are we our hitting our MemTracker memory limits

Other stats are more physical node level (disk usage, cpu, memory), and might be harder to get explicitly within the server.

It would be nice if we could have a JSON returning endpoint that we could query about all of this, returning decently structured data. Bonus points if we also get that into a UI page where we can quickly examine all of these.

This is also needed by load balancers so they can forward requests when the tserver is ready to serve queries. 

Something like `:9000/status?ready=1`.

**Comment by bmatican** [comment]
Discussed offline with @JDNdeveloper that it's ok to pass this to @nspiegelberg .

**Comment by bmatican** [comment]
Note: Should probably integrate with the `/status` introduced by @ttyusupov since https://github.com/YugaByte/yugabyte-db/issues/142.

**Comment by ddorian** [comment]
Yes. This is also needed by load balancers so they can forward requests when the tserver is ready to serve queries. Something like `:9000/status?ready=1`.

**Comment by ddorian** [comment]
A scenario is: `can the node serve a query` which can be used as a health check for a load balancer. Even if there are 0 tablets inside.

On upgrade scenario: You run `drain_all_leaders` from a node, which is resetted on yb-tserver restart. Then you can ask `can I take down this node to upgrade it`.

**Comment by ddorian** [comment]
Another way is to use port 5433 to see if YSQL is ready to accept connection/queries.
