### ISSUE TITLE
[YSQL] Incorrect behavior of yb_lock_status()

### ISSUE THREAD

**Issue by foucher** [yugabyte/yugabyte-db#18343]
Jira Link: [DB-7331](https://yugabyte.atlassian.net/browse/DB-7331)
### Description

I was unable to reproduce this issue locally, but on Jenkins, "permutation 4" in `src/postgres/src/test/isolation/specs/yb-lock-status.spec` was consistently unreliable. The series of operations is this:

Session 3: (the session that queries the lock status)
1. Set the yb_locks parameter to return results for max 1 transaction. (max transactions)
2. Set the yb_locks parameter to return results that are at least 0 seconds old. (min txn age)

Session 1: (the session that takes a lock on k=1)
```
BEGIN;
SELECT * FROM lock_status_test WHERE k = 1 FOR UPDATE; [row exists]
```
Session 2: (the session that takes a lock on k=2)
```
BEGIN;
SELECT * FROM lock_status_test WHERE k = 2 FOR UPDATE; [row exists]
```
Session 3:

1. Wait 5 seconds
2. Get the total rows and total distinct transactions from `yb_lock_status`

On Mac using ybd release on this file and expected result from `yb_lock_status`:
- 2 total rows
- 1 distinct transaction

On Jenkins, actual results:
- 0 total rows (hence, 0 distinct transactions)

Taylor pointed out there is some hacking in the isolation test framework to wait for a few seconds after a statement has started to determine that it's blocked/waiting. Nothing should be blocked here however. Sessions 1 and 2 just took some locks. There should be 4 total `yb_lock_status` rows for 2 transactions, cut down to 2 & 1 because of the flag max_transactions = 1.

Note that at present, all these tests are commented out of `yb_pg_isolation_schedule` due to issue #18324. So you will have to uncomment that as well as the individual permutation in `yb-lock-status.spec`, which is also commented.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7331]: https://yugabyte.atlassian.net/browse/DB-7331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
passes consistently on alma8, both in debug and asan. (running the first 4 permutations). will check how it goes on mac.

**Comment by rthallamko3** [comment]
@sushantrmishra , Should we track this as a 2.19.1 blocker?

**Comment by basavaraj29** [comment]
fix landed. but the test is still commented out as we have an open investigation for memory leak https://github.com/yugabyte/yugabyte-db/issues/18787
