### ISSUE TITLE
[DocDB] Can do better while decoding lock entires from wait queue

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#18356]
Jira Link: [DB-7342](https://yugabyte.atlassian.net/browse/DB-7342)
### Description

As part of https://github.com/yugabyte/yugabyte-db/issues/18149, we put together a workaround for decoding lock entries from wait-queue that end with a column id. 

Currently we rely on the fact the `DocKey::EncodedSize` goes through without failure if the lock entry ends with a column id. If the above operation fails, we assume that the doc key is partial (as `kGroupEnd` gets stripped while forming the locks as part of conflict resolution), and add `kGroupEnd`. We pass this doc key to `PopulateLockInfoFromParsedIntent` in `conflict_resolution.cc`.

Check if we can do better over here as failure of `DocKey::EncodedSize` could imply other things as well.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7342]: https://yugabyte.atlassian.net/browse/DB-7342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Might not be relevant with the fix for #18399

**Comment by rthallamko3** [comment]
No longer relevant after the latest discussions on https://github.com/yugabyte/yugabyte-db/issues/18399. Closing this for now. cc @basavaraj29 , @robertsami
