### ISSUE TITLE
[YSQL] Wrong results for IndexScan yb_hash_code(i) > -1

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#18360]
Jira Link: [DB-7345](https://yugabyte.atlassian.net/browse/DB-7345)
### Description

Yet another yb_hash_code bug (see issue #18347).

Using same schema as before,

```sql
CREATE TABLE tt (i int, j int);
CREATE INDEX ON tt (i, j);
INSERT INTO tt VALUES (1, 2);
```

Index scan selects of the form `yb_hash_code(i) > <negative_number>` fail.

```sql
EXPLAIN /*+IndexScan(tt)*/ SELECT * FROM tt WHERE yb_hash_code(i) > -1;
```

```
                                QUERY PLAN
--------------------------------------------------------------------------
 Index Scan using tt_i_j_idx on tt  (cost=0.00..129.00 rows=1000 width=8)
   Index Cond: (yb_hash_code(i) > '-1'::integer)
(2 rows)
```

```sql
/*+IndexScan(tt)*/ SELECT * FROM tt WHERE yb_hash_code(i) > -1;
```

```
 i | j
---+---
(0 rows)
```

IndexOnlyScan fails, too.  Other negative numbers also fail.  Zero and positive numbers work fine.  `>= 0` works; `>= -1` doesn't.  `yb_hash_code` should always return a non-negative number since it returns 16-bit uint values.

Sequential scan is fine:

```sql
/*+SeqScan(tt)*/ SELECT * FROM tt WHERE yb_hash_code(i) > -1;
```

```
 i | j
---+---
 1 | 2
(1 row)
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7345]: https://yugabyte.atlassian.net/browse/DB-7345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by parkhi** [comment]
Looking into this issue.

**Comment by parkhi** [comment]
The issue seems to be happening here at this line https://github.com/yugabyte/yugabyte-db/blob/0ee77be23078517871825b6e7928ae688fbddccb/src/postgres/src/backend/access/yb_access/yb_scan.c#L2278

ListCell type accepts signed integer as cell's data however when the conversion happens to ScanKey type at the line mentioned above , -1 converts into unsinged int of type uint64_t as 18446744073709551615 which results in wrong output.

**Comment by andrei-mart** [comment]
There's general problem with yb_hash_code result compared to a constant outside of the hash range [0..65535]:
```
yugabyte=# /*+IndexScan(tt)*/ SELECT * FROM tt WHERE yb_hash_code(i) <= 65536;
 i | j 
---+---
(0 rows)
```
