### ISSUE TITLE
[YSQL][DocDB][Read Committed]: The tablet 0ff3a179e7774ad8a21525b738c16348 is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18387]
Jira Link: [DB-7379](https://yugabyte.atlassian.net/browse/DB-7379)
### Description

Tried on version **2.19.1.0-b327**:
While running 4 parallel transactions(Read committed isolation level) which executes update and select(*) on a bunch of rows, one of the Transaction ended up with the below error:
```
psycopg2.errors.InternalError_: The tablet 0ff3a179e7774ad8a21525b738c16348 is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT
```
```
Steps to repro:
1. Create a cluster with enable_wait_queues, enable_deadlock_detection and yb_enable_read_committed_isolation enabled
2. Insert 10k rows
3. Start 4 parallel Threads with different connection:
     i.   BEGIN TRANSACTION;
     ii.  set local retry_backoff_multiplier=1.2;, set local retry_max_backoff='250ms';, set local retry_min_backoff='1ms';
     iii. SELECT * FROM table WHERE ID LIKE '{thread_id+1}%' or ID LIKE '{thread_id+2}%'
     iv.  UPDATE table SET name="UPDATED_" WHERE ID LIKE '{4-thread_id+1}%' or ID LIKE '{4-thread_id+2}% '
     v.   COMMIT;
4. Sleep for 20 mins and let the threads run.
```
[Universe and test logs ](https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/7506/)

G-flags
Master:
```
"yb_enable_read_committed_isolation": "true",
"enable_wait_queues": "true",
 "enable_deadlock_detection": "true",
 "enable_automatic_tablet_splitting": "true",
 "tablet_split_high_phase_shard_count_per_node": 200,
 # high_phase_size 2MB
"tablet_split_high_phase_size_threshold_bytes": 2097152,
 # low_phase_size 100KB
"tablet_split_low_phase_size_threshold_bytes": 102400,
"tablet_split_low_phase_shard_count_per_node": 16,
"enable_stream_compression": "true",
"stream_compression_algo": "1"
```
Tserver:
```
{               "yb_enable_read_committed_isolation": "true",
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "enable_automatic_tablet_splitting": "true",
                "ysql_num_shards_per_tserver": 1,
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "scheduled_full_compaction_frequency_hours": "12",
                "scheduled_full_compaction_jitter_factor_percentage": "100",
                "scheduled_full_compaction_check_interval_min": "5",
 }
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7379]: https://yugabyte.atlassian.net/browse/DB-7379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shishir2001-yb** [comment]
Added more details in [JIRA](https://yugabyte.atlassian.net/browse/DB-7379)

**Comment by Arjun-yb** [comment]
**Version**: `2.19.1.0-b397`
Observed below error while reading data(while testing xCluster + automatic tablet splitting)
`demo1=# select count(*) from employees;
ERROR: The tablet be5ce198a6f9419f8fea373ae5bbf80e is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT

demo1=# select count(*) from employees;
ERROR: The tablet 3038845b67b24eaeacf992cc1e90e6b8 is in TABLET_DATA_SPLIT_COMPLETED state: TABLET_SPLIT`
cc: @hulien22

**Comment by arybochkin** [comment]
The real error is not seen due to this [commit](https://github.com/yugabyte/yugabyte-db/commit/ee9500464ff47a2e727f98161018f3fb9c89f3fd). The commit introduces new `error_status` parameter of repeatable type, but this parameter is not cleaned during operation retries and thus it contains the collection of all errors met during retries. However the session returns the only first error back to PG layer, even if that error has been already resolved and the corresponding retry has happened.
Possible error for that case could be
```
code: TRY_AGAIN_CODE message: "Restart read required at: { read: { physical: 1691770359060375 } local_limit: { physical: 1691770359060375 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }"
```
at least this is the real error for @Arjun-yb case.

**Comment by bmatican** [comment]
@arybochkin @andrei-mart Is the repeated expected then? Why are we collecting multiple errors, if we're only returning the first one?

**Comment by andrei-mart** [comment]
repeated was used for future development.
There's current problem that if Postgres code invoked by tserver generates some NOTICE or WARNING messages they can not be delivered to client, we currently just log them. The idea was to accumulate them in error_status and make sure they are transported to Postgres, as only Postgres knows how to handle them.
Before error_status there was set set of plain fields for code, message, etc., those could hold only one status, and I did not find any case where there would be multiple statuses. More than that, if there multiple statuses it is not clear how to handle that.
In this particular case response with "retry" status is retried, but status is not cleared, and new status is appended. Following old logic new status would overwrite "retry". So we will either clear existing statuses before adding new on sending end, or if multiple statuses are present take last on receiving end, or both.

**Comment by bmatican** [comment]
Makes sense @andrei-mart ! Are you taking point on the follow then, or is @arybochkin ?

**Comment by andrei-mart** [comment]
@arybochkin has a fix pending, I'll review. We've synced up on that and seem to be on the same page.

**Comment by rthallamko3** [comment]
@arybochkin , Can you backport this fix to 2.19.2 branch as well? As Shishir is running a bunch of these tests for 2.19.2 signoff?

**Comment by bmatican** [comment]
@rthallamko3 @arybochkin do we also need this in 2.16 for splitting?

**Comment by rthallamko3** [comment]
My understanding from Anton was that this is an issue starting 2.18 due to [commit](https://github.com/yugabyte/yugabyte-db/commit/ee9500464ff47a2e727f98161018f3fb9c89f3fd). @arybochkin , Can you confirm?

**Comment by arybochkin** [comment]
The issue was starting from 2.17.2, but as we're not backporting to 2.17, the first target is 2.18. I'll prepare a backport to 2.19.2.
