### ISSUE TITLE
[YSQL] Inconsistency may occur in tablet splitting tests on only load test in 2.14/2.16 versions

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#18380]
Jira Link: [DB-7373](https://yugabyte.atlassian.net/browse/DB-7373)
### Description

Test evaluated sample-apps workload with node restarts
```
        "instance_type": "c5.2xlarge",
        "master_gflags": {
            "tablet_split_low_phase_size_threshold_bytes": "20971520",
            "tablet_split_limit_per_table": "512",
            "enable_automatic_tablet_splitting": "true",
            "tablet_split_low_phase_shard_count_per_node": "134217728",
            "ysql_num_shards_per_tserver": "1",
            "yb_num_shards_per_tserver": "1",
        },
        "tserver_gflags": {
            "enable_automatic_tablet_splitting": "true",
            "ysql_num_shards_per_tserver": "1",
            "yb_num_shards_per_tserver": "1",
        }
```

Fix is available in 2.18.0.0-b1 version and 2.17.1.0-b160

```
AssertionError: Failed to check query layer consistency
Previous:{"postgresqlkeyvalue": {"count": 50036
Latest:{"postgresqlkeyvalue": {"count": 50031, 
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7373]: https://yugabyte.atlassian.net/browse/DB-7373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Arjun-yb** [comment]
Observed inconsistency in 2.18.3.0-b3 as well, added the run details in JIRA- https://yugabyte.atlassian.net/browse/DB-7373
