### ISSUE TITLE
[YSQL] [Read Committed]: Deadlocks reported as serialization errors

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18384]
Jira Link: [DB-7377](https://yugabyte.atlassian.net/browse/DB-7377)
### Description

Tried on version: **2.19.1.0-327**:
While running 4 parallel transactions(Read committed isolation level) which executes update and select(*) on a bunch of rows, one of the Transaction ended up with the below Serialization error
```
psycopg2.errors.SerializationFailure: Transaction 71fba304-160e-422f-8ca0-05bf8bab4a3c expired or aborted by a conflict: 40001
```
Note: Updates happen in such a way that one of the 4 Transaction always ends up with a Deadlock which gets detected because enable_deadlock_detection is enabled .

G-flags used:
```
"yb_enable_read_committed_isolation": "true",
"enable_wait_queues": "true",
 "enable_deadlock_detection": "true",
 "enable_automatic_tablet_splitting": "true",
 "tablet_split_high_phase_shard_count_per_node": 200,
 # high_phase_size 2MB
"tablet_split_high_phase_size_threshold_bytes": 2097152,
 # low_phase_size 100KB
"tablet_split_low_phase_size_threshold_bytes": 102400,
"tablet_split_low_phase_shard_count_per_node": 16,
"enable_stream_compression": "true",
"stream_compression_algo": "1"
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7377]: https://yugabyte.atlassian.net/browse/DB-7377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment]
Another flavour of serialization errors I observed in transactions using read committed isolation level.
```
yugabyte=# select sum(v) from test;
ERROR:  Heartbeat: Transaction 94fbc31e-ddb6-4597-a6aa-18306efa590e expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_coordinator.cc:1791): Heartbeat: Transaction 94fbc31e-ddb6-4597-a6aa-18306efa590e expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)]
```
