### ISSUE TITLE
[yugaware] Dashboard UI for an imported universe does not render

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1838]
@WesleyW can you fill in some more details for this, thanks.

**Comment by WesleyW** [comment]
After importing a universe, going to the dashboard for that universe crashes YW. This seems to be a problem with `ybSoftwareVersion` not being set for imports. This issue could potentially have other problems, such as the UI referencing the `pricePerHour` variable when it might not be set.
