### ISSUE TITLE
[yb-master graceful stop and start] Failed to load sys catalog: Corruption (yb/master/sys_catalog_writer.cc:71): Failed while visiting tables in sys catalog

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#18389]
Jira Link: [DB-7381](https://yugabyte.atlassian.net/browse/DB-7381)
### Description

Brought down my **yb-master** using  `systemctl --user stop yb-master ` and then brought it back up. 

Since then all my **yb-masters** are going down on other nodes. 

I observed below log in yb-master.ERROR on [this](https://portal.yba-installer.dev.yugabyte.com/universes/94a626fa-5a58-4f94-8931-9f3a8dfffedc/nodes) LRU
```
E0721 14:17:38.258836 3887513 async_initializer.cc:95] Failed to initialize client: Timed out (yb/rpc/outbound_call.cc:489): Could not locate the leader master: GetMasterRegistration RPC (request call id 128) to 10.150.2.219:7100 timed out after 0.202s
F0721 14:17:40.597069 3887539 catalog_manager.cc:1151] T 00000000000000000000000000000000 P b96869e323b04d54849f90f022cdef15: Failed to load sys catalog: Corruption (yb/master/sys_catalog_writer.cc:71): Failed while visiting tables in sys catalog: System catalog snapshot is corrupted or built using different build type: Unexpected value type for metadata: 0, row: { 0 => { value: int8_value: 1 ttl_seconds: 0 write_time: kUninitializedWriteTime } 1 => { value: binary_value: "000033f3000030008000000000004000" ttl_seconds: 0 write_time: kUninitializedWriteTime } 2 => { value: ttl_seconds: -1 write_time: 1689317914886266 } }, type: 1, id: 3030303033336633303030303330303038303030303030303030303034303030
```

Details to connect and further discussion in [this](https://yugabyte.slack.com/archives/C01CB38CZHU/p1690001511993289?thread_ts=1690001461.625709&cid=C01CB38CZHU) Slack Thread

cc: @renjith-yb @kripasreenivasan @Arjun-yb 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7381]: https://yugabyte.atlassian.net/browse/DB-7381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@zlareb1-yb Did we ever manage to get more info as part of this?

**Comment by zlareb1-yb** [comment]
Have not been able to reproduce this till now @bmatican

**Comment by bmatican** [comment]
Ok closing then, as we might have fixed this a while back.
