### ISSUE TITLE
[DocDB] GetLockStatus shows in memory locks, and not the locks for conflict resolution in waiters

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#18399]
Jira Link: [DB-7389](https://yugabyte.atlassian.net/browse/DB-7389)
### Description

GetLockStatus always returns column_id 0 when returning wait queue waiters. The attnum field is NULL as well.

```
yugabyte=# select locktype, relation::regclass, mode, granted, hash_cols, attnum, column_id from yb_lock_status(null,null) where granted = false;
 locktype | relation |            mode            | granted | hash_cols | attnum | column_id 
----------+----------+----------------------------+---------+-----------+--------+-----------
 relation | foo      | {WEAK_READ,WEAK_WRITE}     | f       |           |        |          
 row      | foo      | {WEAK_READ,WEAK_WRITE}     | f       | {1}       |        |          
 column   | foo      | {STRONG_READ,STRONG_WRITE} | f       | {1}       |        |         0
(3 rows)
```

Reproduction:

```sql
CREATE TABLE foo(a int primary key, b int);
INSERT INTO foo VALUES(1,1);

-- S1
BEGIN; SELECT * FROM foo FOR UPDATE;
-- S2
BEGIN; UPDATE foo SET b=2 where a=1;

-- S3
SELECT locktype, mode, granted, hash_cols, attnum, column_id FROM yb_lock_status(null,null) WHERE granted = false;
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7389]: https://yugabyte.atlassian.net/browse/DB-7389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tvesely** [comment]
This is actually displaying the doc path of in-memory locks, not the paths to be used for conflict resolution. We should think about which paths ones we actually wish to display in pg_locks.

**Comment by basavaraj29** [comment]
Elaborating on what Taylor quoted above, for a given doc path, there are two modes using which we retrieve the paths to be locked in-memory/checked for during conflict resolution - `kLock` and `kIntents`.

For acquiring the shared in-memory locks, we use the `kLock` mode. and for conflict resolution, we use the `kIntents` mode.

for statements like `UPDATE ... SET v=1 WHERE ...`, we seem to acquire an in-memory lock on `SystemColumnIds::kLivenessColumn` (column 0) so as to temporarily prevent other simultaneous operations on the same key (trying to modify other columns). once the update makes it to the intentsdb, the other operations progress.

When we query pg_locks, for the awaiting locks, we seem to display the awaiting in-memory lock info for the waiters. Instead, we could go with displaying the doc paths being used for in conflict resolution (which would match that of granted locks of other transactions with intents).

**Comment by basavaraj29** [comment]
backport to 2.20 blocked on backport of commit https://github.com/yugabyte/yugabyte-db/commit/6de97906f7730fdca6b64809b9080d2eed960707
