### ISSUE TITLE
[YSQL] select version() should return YB information instead of postgres version

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1841]
Currently, running `select version()` in ysqlsh shows postgres version information:
```
postgres=# select version();
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.2 on x86_64-apple-darwin17.7.0, compiled by Apple LLVM version 10.0.0 (clang-1000.11.45.5), 64-bit
(1 row)
```

This should be changed to show YB version.

Dependent issue: https://github.com/YugaByte/yugabyte-db/issues/1256

**Comment by nspiegelberg** [comment]
The various ways that you can get the pgsql version.  Not sure the right place to document this: https://www.2ndquadrant.com/en/blog/finding-postgresql-version/

**Comment by bmatican** [comment]
@nspiegelberg @ndeodhar we already have something for internal version management, `src/yb/util/version_info.cc`, which we should be able to leverage. It should be the same thing that's used in the UI footer as well as in `yb-master --version`.
