### ISSUE TITLE
[DocDB] Filter locks corresponding to aborted subtransactions from pg_locks

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#18415]
Jira Link: [DB-7404](https://yugabyte.atlassian.net/browse/DB-7404)
### Description

In GetLockStatus, we query the coordinators for old transactions and then forward lock status requests to the old transactions' involved tablets. 

In the results, we should remove locks corresponding to aborted subtransactions of all transactions. Currently, we receive this info from the coordinator (as part of fetching old transactions), but never use this.  

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7404]: https://yugabyte.atlassian.net/browse/DB-7404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
See https://github.com/yugabyte/yugabyte-db/issues/18338 for repro steps
