### ISSUE TITLE
[YSQL] [pg_locks] : Same subtransactionid being populated for different commands with a transaction in RR and Serializable isolation

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18419]
Jira Link: [DB-7408](https://yugabyte.atlassian.net/browse/DB-7408)
### Description

Steps to repro:
1. Create universe on `2.19.1.0-b367` with wait_queues, deadlock detection, read committed enabled (pg_locks enabled by default)
2. create table tb(k int primary key, v int);
3. insert into tb values(1,1), (2,2), (3,3);
4. begin transaction isolation level repeatable read/serializable;
5. select;
6. select * from tb where k=1 for update;
7. select * from tb where k=2 for share;
8. select * from pg_locks;

Notice that all the entries will have same subtransactionid. This behaviour is not observed for read committed isolation level.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7408]: https://yugabyte.atlassian.net/browse/DB-7408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
@Karvy-yb this is expected behavior. within a given transaction, the subtransactionid is assigned in an ascending manner to each new subtransaction. in read committed, we implicitly create a new subtransaction for each statement
