### ISSUE TITLE
[docdb] Create endpoint for retrieving YB version

### ISSUE THREAD

**Issue by WesleyW** [YugaByte/yugabyte-db#1842]
As follow up to #1838 , we should create an endpoint in YBClient that exposes the current version of YB. We'll need to also update the YW's import universe flow to use that.

**Comment by bmatican** [comment]
Passing this to @iSignal for starting up in the code.

We have a couple of API endpoints exposed at the YB level as simple JSON returning HTTP endpoints. We should expose one for version info, returning it as structured JSON so YW can use it to figure out what version is running on a cluster.

Example diff adding a new api endpoint + some simple test around it: fa83b17707502415ed5e8ad7e809d833a4ac6eb3 cc @nspiegelberg 

As for where to get the version info, in the path handlers, we already put the info as a footer in every page, see `src/yb/util/version_info.cc` and `VersionInfoPB`.
