### ISSUE TITLE
[xCluster] Add index to the colocated table halts the replication

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#18427]
Jira Link: [DB-7414](https://yugabyte.atlassian.net/browse/DB-7414)
### Description

**Version**: `2.18.2.0-b65`
**Steps**

1. Create colocated DB and table at source
2. Take backup of DB and restore at target
3. Setup replication from source to target
4. Run workload and validate the replication - it works fine

5. Create index at source and wait until index backfill to complete
6. Then Create same index at target and wait until backfill to complete
7. Then check the data at source and target - There will be **data mismatch** and **replication will halt when the index is being created at source**

**Transactional setup**
Same steps as above and run transactional Workload
Here while creating same index at target it got stuck and create index operation didn’t finish at all

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7414]: https://yugabyte.atlassian.net/browse/DB-7414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Index needs to be created with colocation id manually set.
This doc needs to be updated to include index:
https://docs.yugabyte.com/preview/architecture/docdb-sharding/colocated-tables/#xcluster-and-colocation

**Comment by hari90** [comment]
Doc GH #19641
