### ISSUE TITLE
[DocDB] Flaky unit test: CDCServiceTest.TestGetChangesWithDeadline

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18424]
Jira Link: [DB-7411](https://yugabyte.atlassian.net/browse/DB-7411)
### Description

Unit test **`CDCServiceTest.TestGetChangesWithDeadline`** has been flaky since a long time.
[Stability Trend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCServiceTest&fail_tag=all&name=TestGetChangesWithDeadline&num_commits=500&platform=linux)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7411]: https://yugabyte.atlassian.net/browse/DB-7411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Not seeing this as flaky in master anymore.
