### ISSUE TITLE
[Docs] systemd service for master and tserver

### ISSUE THREAD

**Issue by pablopla** [yugabyte/yugabyte-db#18438]
### Description

Docs are missing examples for master and tserver [here](https://docs.yugabyte.com/preview/deploy/manual-deployment/start-masters/), [here](https://docs.yugabyte.com/preview/deploy/manual-deployment/start-tservers/) and [here](https://docs.yugabyte.com/preview/quick-start/linux/).
There are services files for [master](https://github.com/yugabyte/yugabyte-db/blob/master/managed/devops/roles/provision-cluster-server/templates/yb-master.service) and [tserver](https://github.com/yugabyte/yugabyte-db/blob/master/managed/devops/roles/provision-cluster-server/templates/yb-tserver.service) under devops in the repo but they have ansible syntax and not documented.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by pablopla** [comment]
@ddorian It will be great to have the systemd service as part of the official docs.

**Comment by Shekelme** [comment]
@ddorian It doesn't work, I was busy with it all night yesterday.
```
Aug 22 18:40:24 lenovo1 kernel: bash[72928]: segfault at 7ffcafdd4eec ip 00007f66c3eb4425 sp 00007ffcafdd4ee0 error 6 in ld-linux-x86-64.so.2[7f66c3eac000+2a000]
Aug 22 18:40:24 lenovo1 kernel: Code: 4c 8d 25 4e 60 02 00 e9 4c fc ff ff 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 81 ec c8 03 00 00 <89> 54 24>
Aug 22 18:40:24 lenovo1 systemd[1]: yb-master.service: Main process exited, code=dumped, status=11/SEGV
░░ Subject: Unit process exited
░░ Defined-By: systemd
```
