### ISSUE TITLE
[YSQL] Extend existing unit tests to run for READ COMMITTED isolation level

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#18462]
Jira Link: [DB-7436](https://yugabyte.atlassian.net/browse/DB-7436)
### Description

We should extend the  unit test coverage for  Read committed isolation level and add more test as required.

Also specifically consider following scenarios. 

- Table with  primary key 
- ~Table with check constraints~ (covered by [#15196](https://github.com/yugabyte/yugabyte-db/issues/15196))
- Table with unique and non unique  Index
- Aggregate functions
-  Enable Colocation for the tables 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7436]: https://yugabyte.atlassian.net/browse/DB-7436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment]
Closing this gh issue since existing unit tests cover this for RC after b4861652916553b5f681b77826236f48d03d006e
