### ISSUE TITLE
Yugabyte 2DC implementation production->DR

### ISSUE THREAD

**Issue by ram66jet** [yugabyte/yugabyte-db#1849]
One of the challenges with with traditional databases like Oracle is the complex setup (though automated) for non critical/(non CAF applications) with many touch points to implement DR. It would be great to offer two options like Oracle physical standby and logical standby. Since you are planning to implement the 2DC and publication/subscription option, I suppose this can be extended with a managed fail-over between DC's with 1 copy of the database per datacenter. And to load balance and implement managed switchover for the application with implementations like pgpool-II.

**Comment by ndeodhar** [comment]
Hi @ram66jet , thanks for your input! We have recently started developing an initial version of 2DC for YugaByte. 

You can read this for more details: https://github.com/YugaByte/yugabyte-db/blob/master/architecture/design/multi-region-2DC-deployment.md
