### ISSUE TITLE
[Docs] Title for ysql, does creating more databases help with partitioning or creating more tables help?

### ISSUE THREAD

**Issue by hiqsociety** [yugabyte/yugabyte-db#18534]
### Description

[Docs] Title for ysql, does creating more databases help with partitioning or creating more tables help?

possible to show how the internal mechanism of YSQL layer works?

at petabyte scale db, what's the performance impact of splitting up YSQL data into more db shards or more tables?

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
Closing as no reply from user.
