### ISSUE TITLE
[xCluster][YCQL][Tablet Splitting] Data validation is failing and noticed 1 or 2 nodes go to unreachable state

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#18540]
Jira Link: [DB-7489](https://yugabyte.atlassian.net/browse/DB-7489)
### Description

Version: 2.19.1.0
Test: `testycqlxclusterwithtabletsplitting`
Initially it was failing with `data mismatch` issue https://github.com/yugabyte/yugabyte-db/issues/17544
Then it started failing at data validation step where we observed 1 or 2 nodes go to unreachable state

Observed only in master: 2.19.1.0
Related details are added in JIRA

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7489]: https://yugabyte.atlassian.net/browse/DB-7489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hulien22** [comment]
Closed by [53c6b6f](https://github.com/yugabyte/yugabyte-db/commit/53c6b6f094632245ef01dd828a824708ec88d6d6)
