### ISSUE TITLE
[Docs] [YSQL] The "CREATE TABLESPACE" statement isn't described in the "Categorized list of SQL statements" section.

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#18573]
### Description

Look at the section **[Categorized list of SQL statements](https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/)** and its per-starement child subsections. The _CREATE TABLESPACE_ statement isn't found.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
Duplicate of #13614
