### ISSUE TITLE
libev: internal timer heap corruption during tablet deletion

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#1859]
https://gist.githubusercontent.com/mbautin/6cc4dac7f61c2101250c347db89cb9b2/raw

**Comment by mbautin** [comment]
Full dump of all threads: https://gist.githubusercontent.com/mbautin/92344f5a095063e4d28e6e6531335177/raw

**Comment by mbautin** [comment]
1.3.0.0-b1 corresponds to this commit: https://github.com/YugaByte/yugabyte-db/commits/1baa47a7cc3d6372f64073fe3aad252d8a4bd9f7

**Comment by spolitov** [comment]
`ev::timer` should be destroyed from the appropriate reactor thread.
We should provide custom deleter for connection, that will check the current thread and redirect deletion to reactor thread in necessary.
