### ISSUE TITLE
[DocDB] Wait on Conflict - 99%+ transactions are failing with "Unexpected SQL Errors" with featurebench causing the variation in throughput and latency

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#18598]
Jira Link: [DB-7527](https://yugabyte.atlassian.net/browse/DB-7527)
### Description

For the report shared by @robertsami [http://perf.dev.yugabyte.com/report/view/W3siaXNCYXNlbGluZSI6ZmFsc2UsIm5hbWUiOiJTZWxlY[…]oiTGF0ZXN0IE1hc3RlciBCcmFuY2giLCJ0ZXN0X2lkIjoyMjU5NjAyfV0=](http://perf.dev.yugabyte.com/report/view/W3siaXNCYXNlbGluZSI6ZmFsc2UsIm5hbWUiOiJTZWxlY3RlZCBUZXN0LWlkIiwidGVzdF9pZCI6MjIzNjcwMn0seyJpc0Jhc2VsaW5lIjp0cnVlLCJuYW1lIjoiTGF0ZXN0IE1hc3RlciBCcmFuY2giLCJ0ZXN0X2lkIjoyMjU5NjAyfV0=)

Currently in featurebench the Throughput achieved for a given workload is "Total measured requests" achieved in the total execution time (does not include warmup and cooldown period. 120sec). Also "Total measured requests" is addition of all the transaction status like Completed, Rejected, Zero, Aborted and Unexpected SQL Errors.

**Reason for variations:**
For the test LATEST MASTER BRANCH (TEST_ID: 2259602) workload update_key_from_multiple_threads_with_weights_* with 60/100 weights, 99.5%+ of "Total measured requests" are of "Unexpected SQL Errors" state which completed within very less latencies compared to completed transactions i.e. for 100 weight test out of 27683795 "Total measured requests" transactions 27634531 transaction are of "Unexpected SQL Errors"  which is why the overall throughput is absurdly high where as the test with 20 weight none of the transactions are of "Unexpected SQL Errors" status and the "Total measured requests" achieved are 176642 which comprise of completed and rejected transactions.

So for same test I tried to calculate the throughput by removing the "Unexpected SQL Errors" from "Total measured requests" which essentially leaves with completed and rejected transactions achieved in complete test duration:
Throughput Test with 100 weight: (27683795 - 27634531)/120(execution time) = 410.53
Throughput Test with 20 weight: (176642-2)/120 = 1472
Post removal of Unexpected SQL Error, the test with absurdly high throughput and low latencies are in ballpark range of corresponding workload of  SELECTED TEST-ID (TEST_ID: 2236702).

Slack thread for detailed discussion:
https://yugabyte.slack.com/archives/C027QFMTPA8/p1690705598703589?thread_ts=1690397439.597299&cid=C027QFMTPA8

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7527]: https://yugabyte.atlassian.net/browse/DB-7527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
should no longer happen with the following fixes:
https://github.com/yugabyte/yugabyte-db/issues/17936
https://github.com/yugabyte/yugabyte-db/issues/10429
and we should update the following flags:
```
wait_queue_poll_interval_ms=5
ysql_pg_conf_csv=yb_lock_pk_single_rpc=true
```
