### ISSUE TITLE
[YSQL] [pg_locks] : pg_locks view is displaying locks acquired inside system_platform

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18602]
Jira Link: [DB-7531](https://yugabyte.atlassian.net/browse/DB-7531)
### Description

Automation is running into this issue intermittently where entries from `system_platform` database are being published in pg_locks view. DB version: `2.19.1.0-b397`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7531]: https://yugabyte.atlassian.net/browse/DB-7531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
intended behavior
