### ISSUE TITLE
TServer start failed with error:  postgres/bin/initdb failed with exit code 256

### ISSUE THREAD

**Issue by gdyang1990** [YugaByte/yugabyte-db#1860]
I am trying to deploy a yb cluster under linux(centos).
But when I try to start TServer, I got an error: 
Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:143): /xxx/yugabyte/yugabyte-1.3.0.0/postgres/bin/initdb failed with exit code 256 

And I do not know what does that mean...

Anyone can help？

**Comment by frozenspider** [comment]
Hi @gdyang1990 

First please make sure you're using latest version of YB (v1.3.0 at the moment).
If your cluster has no meaningful data yet, the simplest solution would be to destroy and recreate it:
```
./bin/yb-ctl destroy
./bin/yb-ctl create
```
Given current defaults, this should initialize PG system tables using initdb snapshot supplied within YB, as opposed to attempting to run initdb against the cluster. This should avoid the error, whichever it is.

If that's not an option for you (or even if it is), could you please post a full log output of the said error?

**Comment by gdyang1990** [comment]
hi @frozenspider 
I do not have old datas. I just try to build a YB cluster from empty.
The error seems to be caused by locale when running initdb of postgres. I saw that YB will set LC_COLLATE=C and other locale setting to en_US.UTF-8 by default. 
And an error msg is reported: initdb: _invalid locale name "en_US.UTF-8"_
and then : _E0722 16:25:12.533330 130312 main_util.cc:22] Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:143): /home/tafdb/yugabyte/yugabyte-1.3.0.0/postgres/bin/initdb failed with exit code 256_

**Comment by d-uspenskiy** [comment]
@gdyang1990 
Could you please try this solution

https://stackoverflow.com/questions/49783108/postgresql-10-on-linux-lc-collate-locale-en-us-utf-8-not-valid

**Comment by gdyang1990** [comment]
@d-uspenskiy thanks for your reply.
Finally, I managed to build the cluster successfully.
The reason for the problem is that the OS I am using is centos6. When I upgraded OS to centos7, the setup was successful.
