### ISSUE TITLE
[YSQL][pg_locks] : Transactions very younger than yb_locks_min_txn_age show up in pg_locks view

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18625]
Jira Link: [DB-7552](https://yugabyte.atlassian.net/browse/DB-7552)
### Description

Steps to repro:

1. Create universe on version 2.19.1.0-b397 with read committed, wait queues and deadlock detection enabled (pg_locks is enabled by default)
2. create table tb(k int primary key, v int);
3. insert into tb values(1,1), (2,2), (3,3);
4. S1: set yb_locks_min_txn_age=600;
5. S2: begin; select; select * from tb where k=1 for update;
6. S1: select distinct (ybdetails->'transactionid') as txn_id, waitstart, waitend, database, relation from pg_locks; 

Notice that lock acquired in step 5 will show up even when it hasn't been 600 seconds

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7552]: https://yugabyte.atlassian.net/browse/DB-7552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
@Karvy-yb Were you able try out with higher value for yb_locks_min_txn_age . As discussed,  the unit is ms for yb_locks_min_txn_age.

**Comment by robertsami** [comment]
closing -- @Karvy-yb feel free to re-open if this is still an issue with "600s"
