### ISSUE TITLE
[2DC] Modify WAL to Contain Metadata about Source

### ISSUE THREAD

**Issue by rahuldesirazu** [YugaByte/yugabyte-db#1863]
Add a flag to WAL record to indicate whether the record came from an external or local source. In a master <-> master setup, we wan't to filter out records that came in externally when returning a set of new changes.

**Comment by ndeodhar** [comment]
Duplicate: https://github.com/YugaByte/yugabyte-db/issues/1824.

**Comment by rahuldesirazu** [comment]
Closing duplicate.
