### ISSUE TITLE
[YSQL] Login Profile attempts increase by 2 when failure in login using JWT

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#18644]
Jira Link: [DB-7568](https://yugabyte.atlassian.net/browse/DB-7568)
### Description

When a user attempts failure login to a cluster with JWT enabled, the failedloginattempt count is increasing by 2. 

Steps:
1. Enable JWT on the tserver of cluster.
2. Create a role.
3. Attach it to profile.
4. Try login with password
5. Pass invalid token andAttempt failure
6. Validate attempt increases by 2.

Before:
```
yugabyte=# SELECT oid from pg_roles where rolname='testuser'
yugabyte-# ;
  oid
-------
 16389
(1 row)

yugabyte=# select rolprffailedloginattempts from pg_yb_role_profile where rolprfrole=16389;
 rolprffailedloginattempts
---------------------------
                         0
(1 row)
```

Invalid login:

```
[yugabyte@yb-yugabyte-hba-conf-n3 ~]$  tserver/bin/ysqlsh -h 127.0.0.1 -U testuser
Password for user testuser:
ysqlsh: FATAL:  JWT authentication failed for user "testuser"
FATAL:  JWT authentication failed for user "testuser"
```
After count:
```
yugabyte=# select rolprffailedloginattempts from pg_yb_role_profile where rolprfrole=16389;
 rolprffailedloginattempts
---------------------------
                         2
(1 row)
```

hba_conf: 
```
host all yugabyte 0.0.0.0/0 password
host all all 0.0.0.0/0 jwt map=map1 jwt_jwks_path="/home/yugabyte/jwt_key.json" jwt_audiences="<audience>" jwt_issuers="<issuer>" jwt_matching_claim_key=groups
local all yugabyte trust
hostssl all all all md5
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7568]: https://yugabyte.atlassian.net/browse/DB-7568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dr0pdb** [comment]
@rjalan-yb What was the command you used to open ysqlsh?

Please make sure to use the `-W` option while opening ysqlsh. Something like `./bin/ysqlsh -W`.

This double count issue was discussed on the login profile implementation diff and the justification given is as follows:
> -W forces a password prompt. Without it, any time you attempt to change the connection, it tries to login with the current password first, and if that fails, it will prompt for a password. This means that if you enter the wrong password, it fails twice.
> If you use -W, it will not try to reuse the old password. So all attempts are explicitly requested by the user.

Diff: https://phorge.dev.yugabyte.com/D21043

If the issue persists even after using `-W` option, please let me know.
