### ISSUE TITLE
[YSQL] Server crashes when setting GFLAGS "ysql_prefetch_limit" to small number

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#1865]
To reproduce:
- Start server with small setting for prefetch limit.  For example, ``` yb-ctl start --tserver_flags="ysql_prefetch_limit=2" ```
- Run ysqlsh command.

Crash happens right away.

It appears that the prefetch limit must be at least equal to the number of tablet-servers to avoid the crash.
```
ysql_prefetch_limit >= "number of tablet servers"
```

**Comment by rajukumaryb** [comment]
Another set of steps to recreate the issue -

1. `./bin/yb-ctl --replication_factor 3 create --tserver_flags "yb_num_shards_per_tserver=2,leader_failure_max_missed_heartbeat_periods=60,ysql_prefetch_limit=4"`

2. In `./bin/ysqlsh` - 
    `create table tab(h int, ri int, rt text, rd double precision, v text, primary key(h, ri, rt, rd));`


Note: different errors on `ysql_prefetch_limit` = `2 | 4 | 6 | 8`

**Comment by ndeodhar** [comment]
Recording some offline conversations here (to help debugging):
Per @rajukumaryb's test, this is the request proto that was logged:
```
I0730 01:00:33.838732 26901 abstract_tablet.cc:78] PgsqlReadRequestPB: client: YQL_CLIENT_PGSQL
schema_version: 0
hash_code: 57005
targets {
  column_id: 10
}
targets {
  column_id: 11
}
targets {
  column_id: 12
}
targets {
  column_id: 13
}
targets {
  column_id: 14
}
targets {
  column_id: 15
}
targets {
  column_id: -8
}
column_refs {
  ids: 10
  ids: 11
  ids: 12
  ids: 13
  ids: 14
  ids: 15
}
is_forward_scan: true
limit: 1
paging_state {
  next_partition_key: "\336\255"
  next_row_key: "y\005\360\240\000\000\000\000\200\0000\000\000\2450\000\000O\000\000&\274O\000\000\000\023O\000\000\000\023H\200\000\000\002$!#\200\001\305bm\376\306X\200J"
  total_num_rows_read: 1
}
return_paging_state: true
table_id: "000030a5000030008000000000000a2b"
index_request {
  targets {
    column_id: 15
  }
  column_refs {
    ids: 15
  }
  range_column_values {
    value {
      uint32_value: 9916
    }
  }
  range_column_values {
    value {
      uint32_value: 19
    }
  }
  range_column_values {
    value {
      uint32_value: 19
    }
  }
  table_id: "000030a5000030008000000000000a5f"
}
```

Error seen:
```
./bin/ysqlsh
ysqlsh: FATAL:  Query error: Invalid start_doc_key: "y\x05\xf0\xa0\x00\x00\x00\x00\x80\x000\x00\x00\xa50\x00\x00O\x00\x00&\xbcO\x00\x00\x00\x13O\x00\x00\x00\x13H\x80\x00\x00\x02$!". Range: "y\x02\xb0\xa0\x00\x00\x00\x00\x80\x000\x00\x00\xa50\x00\x00G\xde\xad\x00!!", "y\x02\xb0\xa0\x00\x00\x00\x00\x80\x000\x00\x00\xa50\x00\x00~!"
```

Per @m-iancu,
It’s a table with a nested index request — We have this optimization for system tables to do the table and index lookup in one request (since they are guaranteed to both be in one tablet — the master tablet).
In that case, if we need to do paging, we need to make sure whether we need the main table or index row key.

**Comment by nocaway** [comment]
This error occurs when selecting from large system table that has secondary index.
- For this select statement, YugaByte send nested queries to DocDB (storage layer), when the result set is larger than prefetch-limit, DocDB sent back a paging state for the subsequent fetches.
- The returned paging state is for the innermost query (the last operation node), but it is kept in the outermost query / node, and that causes a crash.

**Comment by nocaway** [comment]
This bug has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/8e712d8a49bae01a9a66e1374c7459ef1887e520
