### ISSUE TITLE
[test] Flaky test PgWaitQueuesTest.TestDeadlock

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#18659]
Jira Link: [DB-7581](https://yugabyte.atlassian.net/browse/DB-7581)
### Description

Fails with the following once every few days.

```
../../src/yb/yql/pgwrapper/pg_wait_on_conflict-test.cc:152
Value of: done.WaitFor(5s * kTimeMultiplier)
  Actual: false
Expected: true
```

Fails on alma8-master-clang15-release-aarch64 and alma8-master-clang15-asan most often.

internal link: https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=PgWaitQueuesTest&name=TestDeadlock&num_fails=100

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7581]: https://yugabyte.atlassian.net/browse/DB-7581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
seems to be passing reliably now
