### ISSUE TITLE
[YSQL] Support row level security (RLS) as per Postgres

### ISSUE THREAD

**Issue by shrumm** [yugabyte/yugabyte-db#1870]
About the feature
=============
Row level security in PostreSQL allows the DBA to set 'row security policies that restrict, on a per-user basis, which rows can be returned by normal queries or inserted, updated, or deleted by data modification commands. '

Use case
=======

Many use cases come to mind, but for multi-tenant SaaS apps this is a critical feature. It allows the app to store data of multiple clients in the same table and greatly minimizes/eliminates the chance of interference.

The feature is described very well in the PostgreSQL docs -> https://www.postgresql.org/docs/11/ddl-rowsecurity.html. Other RDBMs like SQL Server, Oracle etc also support it and most likely in more advanced forms.

The order is pretty simple:

A policy is created for a table using syntax like

```sql
CREATE POLICY user_sel_policy ON users
    FOR SELECT
    USING (true);
CREATE POLICY user_mod_policy ON users
    USING (user_name = current_user);
```

then the table must be altered to enable RLS like so

```sql
ALTER TABLE ... ENABLE ROW LEVEL SECURITY
```

now the user / session MUST match the policy of the table to be permitted to see rows / modify data.

**Comment by kmuthukk** [comment]
Implemented as part of https://github.com/yugabyte/yugabyte-db/commit/d87ecbc3d46dac0fc00d90eedd0923b070ab36d7 and available in 2.0.6.
