### ISSUE TITLE
[YSQL] [Unit Test] Test testInsertBatching failing with assertion error

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#18730]
Jira Link: [DB-7626](https://yugabyte.atlassian.net/browse/DB-7626)
### Description

Unit Test [org.yb.pgsql.TestPgForeignKeyBatching.testInsertBatching](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgForeignKeyBatching&fail_tag=all&name=testInsertBatching&num_commits=500&platform=linux) has been failing with assertion error and started failing more frequently after this commit: [d5d8298](https://github.com/yugabyte/yugabyte-db/commit/d5d82981079b8217388076b43d0cb791d893ef59)

Error:
```
05:51:12.702 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.initPostgresBefore(BasePgSQLTest.java:306)] Waiting for initdb to complete on master
05:51:12.703 (Time-limited test) [DEBUG - org.yb.client.AsyncYBClient.clientFor(AsyncYBClient.java:2245)] We know the leader.
05:51:12.709 (Time-limited test) [DEBUG - org.yb.client.AsyncYBClient.clientFor(AsyncYBClient.java:2245)] We know the leader.
05:51:12.711 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.initPostgresBefore(BasePgSQLTest.java:321)] initdb has completed successfully on master
05:51:13.604 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
java.lang.AssertionError: expected:<21> but was:<20>
```

Logs: 
https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release-aarch64/1880/testReport/junit/org.yb.pgsql/TestPgForeignKeyBatching/testInsertBatching/

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7626]: https://yugabyte.atlassian.net/browse/DB-7626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by d-uspenskiy** [comment]
Duplicate #17776
