### ISSUE TITLE
How can I specify the num of partitions when creating table

### ISSUE THREAD

**Issue by gdyang1990** [YugaByte/yugabyte-db#1873]
I noticed that a table will be partitioned into 32 tablets by default.
But how can I specify the num of partitions when creating a postgres table?
Is there any way?

And can partitions be adjusted automatically  like range split in CockroachDB?

**Comment by schoudhury** [comment]
Thanks for the question. You can specify the number of tablets (aka partitions/shards) only at a cluster level today and not at an individual table level (this is something we will enhance in the future).

The config flag that controls the number of tablets at cluster level is `num_shards_per_tserver`

You can set the flag directly on [yb-server](https://docs.yugabyte.com/latest/deploy/manual-deployment/start-tservers/#run-yb-tserver-with-command-line-params) or via the [yb-ctl](https://docs.yugabyte.com/latest/explore/linear-scalability/) local cluster utility.

**Comment by gdyang1990** [comment]
@schoudhury  thanks for reply.
And I want to know that can partitions be adjusted automatically like range split in CockroachDB?

**Comment by ttyusupov** [comment]
@gdyang1990 , currently the number of partitions couldn't be adjusted after the table is created. But we have a splitting feature in WIP: https://github.com/YugaByte/yugabyte-db/issues/1004
