### ISSUE TITLE
[DocDB][Unit Test] Test PgsqlAddColumnCompactWithPackedRow fails on release builds

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#18740]
Jira Link: [DB-7634](https://yugabyte.atlassian.net/browse/DB-7634)
### Description

Unit Test [YbAdminSnapshotScheduleTest.PgsqlAddColumnCompactWithPackedRow ](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=YbAdminSnapshotScheduleTest&fail_tag=all&name=PgsqlAddColumnCompactWithPackedRow&num_commits=500&platform=linux) has been failing on alma8-clang15-release build since commit: [fbd090e3](https://github.com/yugabyte/yugabyte-db/commits/fbd090e37c1389bce96eb69917873c9605ee8d5b)

It is failing with error:
```
../../src/yb/tools/yb-admin-snapshot-schedule-test.cc:1703
Expected equality of these values:
  res
    Which is: "1, one, NULL; 2, two, NULL"
  "1, one, NULL; 2, two, dva"

```

Complete Log:
https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release/2295/artifact/build/release-clang15-linuxbrew-full-lto-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_PgsqlAddColumnCompactWithPackedRow.log

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7634]: https://yugabyte.atlassian.net/browse/DB-7634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SrivastavaAnubhav** [comment]
This appears to be fixed by or around commit 13c0ced9fad39ae4eb120eb8d896f3173dac3c2d
