### ISSUE TITLE
[DocDB] Change the default threshold for reuse_unclosed_segment_threshold_bytes to always reuse the last segment

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#18757]
Jira Link: [DB-7645](https://yugabyte.atlassian.net/browse/DB-7645)
### Description

Change the default threshold for reuse_unclosed_segment_threshold_bytes to 70MB (value greater than the WAL segment size), to help alleviate the following problem:

Every time we stop the process or crash, the WAL active segment is not closed, thus it has no footer and thus no index. So on tablet bootstrap, in order to scan the WAL entires, we need to pay the cost of indexing it. 

In practice, a crash will create this problem for every tablet. This is exacerbated in Xcluster pause resume scenarios - calls GetChanges across all tablets, they might all have to re-index at the same time, leading to a performance issue. Reusing the active WAL segment ensures that it will have a valid footer, which ensures that the WAL segment has the index (which speeds up the access to the various WAL entries).

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7645]: https://yugabyte.atlassian.net/browse/DB-7645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@rthallamko3 @yusong-yan Instead of bumping the flag to 70MB, should we instead add some auto-tune type semantics? eg
- -1 means reuse regardless of size
- 0 means never reuse
- fixed value means reuse up to that explicit size

**Comment by yusong-yan** [comment]
https://github.com/yugabyte/yugabyte-db/issues/18757 is a duplicated issue.

**Comment by rthallamko3** [comment]
@yusong-yan , We wanted to backport to 2.19.2 and 2.18 right?

**Comment by rthallamko3** [comment]
We would need to update the documentation cc @yusong-yan
