### ISSUE TITLE
[YSQL][Unit Test] Flaky Test TabletPeerTest.MaxRaftBatchProtobufLimit 

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#18771]
Jira Link: [DB-7654](https://yugabyte.atlassian.net/browse/DB-7654)
### Description

Following test [TabletPeerTest.MaxRaftBatchProtobufLimit](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=TabletPeerTest&name=MaxRaftBatchProtobufLimit) has been failing with corruption issue very frequently in build alma8-clang15-release-aarch64:

```
I0818 18:49:34.502067 22725 log.cc:769] T test_tablet_id P 4a523e18011747d0b1830e78b5000a28: Rolled over to a new segment: ${TEST_TMPDIR}/tablet_peer-test.TabletPeerTest.MaxRaftBatchProtobufLimit.1692384574436816-22715/fs_root/yb-data/tserver_test/wals/table-YBTableTest/tablet-test_tablet_id/wal-000000002
W0818 18:49:34.537151 22715 log_util.cc:672] Found a corruption in a closed log segment: OK
../../src/yb/tablet/tablet_peer-test.cc:565: Failure
Failed
Bad status: Corruption (yb/consensus/log_util.cc:966): Log file corruption detected.: Failed to parse PB at offset: 1165483, length: 9321640. Cause: Corruption (yb/rpc/lightweight_message.cc:377): Failed to parse 'entry': Failed trying to read batch #4 at offset 1165471 for log segment ${TEST_TMPDIR}/tablet_peer-test.TabletPeerTest.MaxRaftBatchProtobufLimit.1692384574436816-22715/fs_root/yb-data/tserver_test/wals/table-YBTableTest/tablet-test_tablet_id/wal-000000001: Prior batch offsets: 158 212 240 1165471; Last log entries read: [REPLICATE (1.1)] [REPLICATE (1.2)]
Test failure stack trace:
    @     0xffff89cb07d4  testing::internal::TestEventRepeater::OnTestPartResult()
    @     0xffff89cb7608  testing::UnitTest::AddTestPartResult()
    @     0xffff89cb6e2c  testing::internal::AssertHelper::operator=()
    @     0xaaaad85fa4c8  yb::tablet::TabletPeerTest_MaxRaftBatchProtobufLimit_Test::TestBody()
    @     0xffff89ccf4d0  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0xffff89ccf394  testing::Test::Run()
    @     0xffff89cd0238  testing::TestInfo::Run()
    @     0xffff89cd09ec  testing::TestSuite::Run()
    @     0xffff89cdead4  testing::internal::UnitTestImpl::RunAllTests()
    @     0xffff89cde330  testing::UnitTest::Run()
    @     0xffff8f0a2cbc  (unknown)
    @     0xffff89a94384  __libc_start_main
    @     0xaaaad85ee474  (unknown)
```

Full log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release-aarch64/1893/artifact/build/release-clang15-full-lto-ninja/yb-test-logs/tests-tablet__tablet_peer-test/TabletPeerTest_MaxRaftBatchProtobufLimit.log

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7654]: https://yugabyte.atlassian.net/browse/DB-7654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yusong-yan** [comment]
The corruption error is related to the LightweightMessage using the gflag `rpc_max_message_size` instead of the intended `protobuf_message_total_bytes_limit`. https://github.com/yugabyte/yugabyte-db/issues/21352 is tracking this issue.
