### ISSUE TITLE
[Docs] `./bin/post_install.sh` is obsolete in `Quick start: Create a local cluster on a single host`

### ISSUE THREAD

**Issue by erikschul** [yugabyte/yugabyte-db#18829]
### Description

https://docs.yugabyte.com/preview/quick-start/linux/

Guide instructs:
```
To configure YugabyteDB, run the following shell script:
./bin/post_install.sh
```

but the file does nothing:

```
#!/usr/bin/env bash
# For backward-compatibility only. We do not need this script anymore.
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by aishwarya24** [comment]
@erikschul - Which version of YugabyteDB did you try? The output that I saw is:

**Comment by erikschul** [comment]
Closing as unimportant.
It could be relevant to keep the post_install.sh script for later use, and to ensure that the practice of calling the script is maintained.
