### ISSUE TITLE
[YSQL] Select from pg_stat_statements may return inconsistent results depending on hosts sent

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#18839]
Jira Link: [DB-7712](https://yugabyte.atlassian.net/browse/DB-7712)
### Description

Example of calling select statement against pg_stat_statements table in the test:

1. We select all current rows:
```
select query, calls, total_time, min_time, max_time, mean_time, rows, yb_latency_histogram 
from pg_stat_statements;

query|calls|total_time|min_time|max_time|mean_time|rows|yb_latency_histogram
select from write_read_test where id = $1|10|3.025252|0.260038|0.396283|0.3025252|10|[{"[0.2,0.3)": 5}, {"[0.3,0.4)": 5}]
delete from write_read_test where id = $1|10|7.575764|0.709629|0.914914|0.7575764|10|[{"[0.7,0.8)": 9}, {"[0.9,1.0)": 1}]
SELECT jsonb_agg(x) FROM (SELECT version()) as x|1|0.0312|0.0312|0.0312|0.0312|1|[{"[0.0,0.1)": 1}]
insert into write_read_test values ($1) on conflict do nothing|10|53.42914|2.51402|7.957288|5.342914|10|[{"[2.4,2.6)": 1}, {"[4.0,4.4)": 1}, {"[4.4,4.8)": 1}, {"[4.8,5.2)": 1}, {"[5.2,5.6)": 2}, {"[5.6,6.0)": 2}, {"[6.4,7.2)": 1}, {"[7.2,8.0)": 1}]
(4 rows)
```

2. Next call we try to get testing query and it wasn't in the table 6 seconds ago
```
query|calls|total_time|min_time|max_time|mean_time|rows|yb_latency_histogram
select .... for update|177921|204594.267284999|0.843289|48.732094|1.14991635211694|177921|[{"[0.8,0.9)": 448}, {"[0.9,1.0)": 25183}, {"[1.0,1.1)": 55601}, {"[1.1,1.2)": 47761}, {"[1.2,1.3)": 22473}, {"[1.3,1.4)": 14205}, {"[1.4,1.5)": 7348}, {"[1.5,1.6)": 2998}, {"[1.6,1.8)": 1353}, {"[1.8,2.0)": 253}, {"[2.0,2.2)": 94}, {"[2.2,2.4)": 44}, {"[2.4,2.6)": 22}, {"[2.6,2.8)": 23}, {"[2.8,3.0)": 12}, {"[3.0,3.2)": 10}, {"[3.2,3.6)": 9}, {"[3.6,4.0)": 6}, {"[4.0,4.4)": 7}, {"[4.4,4.8)": 3}, {"[4.8,5.2)": 4}, {"[5.2,5.6)": 3}, {"[5.6,6.0)": 3}, {"[6.0,6.4)": 4}, {"[6.4,7.2)": 2}, {"[7.2,8.0)": 5}, {"[8.0,8.8)": 3}, {"[8.8,9.6)": 1}, {"[9.6,10.4)": 2}, {"[10.4,11.2)": 5}, {"[12.0,12.8)": 3}, {"[12.8,14.4)": 1}, {"[14.4,16.0)": 2}, {"[16.0,17.6)": 1}, {"[17.6,19.2)": 5}, {"[19.2,20.8)": 8}, {"[20.8,22.4)": 6}, {"[22.4,24.0)": 2}, {"[24.0,25.6)": 2}, {"[25.6,28.8)": 3}, {"[28.8,32.0)": 1}, {"[32.0,35.2)": 1}, {"[48.0,51.2)": 1}]
(1 row)
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7712]: https://yugabyte.atlassian.net/browse/DB-7712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
The issue is not on DB side but rather on the APP side. Query to select all the rows from `pg_stat_statements` is not getting sent to the DB. same issue was observed from pg_stat_statements_reset query as well.
@qvad   is going to follow up and look in to the application side of the issue.

**Comment by qvad** [comment]
Reopening issue, since it is looks like a ysqlsh issue. Problems solved after `-h` argument was tuned.

Issue reproduced with:
`/home/yugabyte/tserver/bin/ysqlsh  -h 172.151.31.44,172.151.22.130,172.151.21.15 -d yugabyte -f ../path-to.sql`
Not reproduced:
`/home/yugabyte/tserver/bin/ysqlsh  -h 172.151.31.44 -d yugabyte -f ../path-to.sql`

**Comment by qvad** [comment]
pg_stat_statements is a local table for node, we have few tables that are located per node and these results are expected
