### ISSUE TITLE
[YSQL] Add user-facing documentation for pg_locks/yb_lock_status

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#18845]
Jira Link: [DB-7716](https://yugabyte.atlassian.net/browse/DB-7716)
### Description

Probably makes sense to put this in https://docs.yugabyte.com/preview/api/ysql/exprs/ for yb_lock_status() and include information about pg_locks as well. Maybe there is a better place to put info about pg_locks though

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7716]: https://yugabyte.atlassian.net/browse/DB-7716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
not sure if all of these caveats are still relevant, but some we noted before which may want to call out:

- is_explicit field for prefix locks of explicit locks set to false?
- single-shard-txns caveat (https://github.com/yugabyte/yugabyte-db/issues/18195)
- Missing “blocked_by” field
- Wait_start is not populated

**Comment by sushantrmishra** [comment]
Tracked by https://github.com/yugabyte/yugabyte-db/pull/21231 and changes has landed.
