### ISSUE TITLE
Allow storing multiple columns in one RocksDB value

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1887]
Currently DocDB encoding for a row is like this:

```
DocKey1 LivenessInfoColId ht1 -> (empty)
DocKey1 ColId1 ht2 -> col1value
DocKey1 ColId2 h3 -> col2value
```

If the entire row is being inserted at the same hybrid time, or after we compact the data and the differences between the timestamps at which the original columns were written don't matter anymore, we could change the structure to the following:

```
DocKey1 ht -> {ColId1 -> col1value, ColId2 -> col2value}
```

For this to work we would need to come up with some encoding format for the "packed" representation that would still allow efficient extraction of individual columns' values. This could be based on or similar to:
- The existing "frozen" encoding in YCQL
- The JSON encoding used in YCQL or YSQL

Note that the liveness info column is not needed anymore in this representation, because the row existence is established by the presence of the "packed row" record even if the individual columns are all set to NULL and omitted.

**Comment by bmatican** [comment]
Closing in favor of #3520
