### ISSUE TITLE
[DocDB] Table <unknown_table_name> (0000400000003000800000000000401c) not found in Raft group 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18887]
Jira Link: [DB-7748](https://yugabyte.atlassian.net/browse/DB-7748)
### Description

Tried on a version **2.19.3.0-b2**
Executing count(*) on some of the non-colocated tables throws below error

`
ERROR:  Table <unknown_table_name> (0000400000003000800000000000402b) not found in Raft group a4145a88a06e4a30aea0be17c51cad7c
`
Test details:
```
1. Restore a backup with 1k colocated tables.
2. Delete 990 table(so only 10 colocated table are presen) and delete all the data present in the table.
3. Create 10 non-colocated tables on the same database.
4. Create Index on all the tables.
5. Create a PITR snapshot schedule.
6. Add one column in 10 colocated table and drop one column 5 colocated table.
7. Execute count(*) on some tables. (No issue was observed in that table).
8. Drop one column in 5 colocated table.
9. Execute count(*) on some tables  ----------------------> Issue occurs here
```

G-flags used:
```
tserver_gflags={
                "ysql_enable_packed_row": "true",
                "ysql_enable_packed_row_for_colocated_table": "true",
                "enable_automatic_tablet_splitting": "true",
                "ysql_max_connections": "500",
                "backfill_index_client_rpc_timeout_ms": "180000",
                'client_read_write_timeout_ms': str(30 * 60 * 1000),
                'yb_client_admin_operation_timeout_sec': str(30 * 60),
                "lazily_flush_superblock": "true"
            },
master_gflags={
                "ysql_enable_packed_row": "true",
                "ysql_enable_packed_row_for_colocated_table": "true",
                "enable_automatic_tablet_splitting": "true",
                "tablet_split_low_phase_size_threshold_bytes": "2097152",
                "tablet_split_limit_per_table": "8172",
                "consistent_restore": "true",
                "enable_truncate_on_pitr_table": "true",
                "lazily_flush_superblock": "true",
              }
```
[Logs](https://github.com/yugabyte/yugabyte-db/files/12460899/IwqthBIpkr.zip)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7748]: https://yugabyte.atlassian.net/browse/DB-7748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shishir2001-yb , Can you confirm if things look fine after step 1? Trying to figure out if this is an issue with restore or something later?

**Comment by rthallamko3** [comment]
Per Anton: These [logs](https://yugabyte.slack.com/archives/C4K1838GL/p1693328617344049?thread_ts=1693290614.813179&cid=C4K1838GL) are looking similar to the logs in [this](https://github.com/yugabyte/yugabyte-db/issues/18891#issuecomment-1697347383) comment (mentioned [here](https://yugabyte.slack.com/archives/C027QFMTPA8/p1693312059110809?thread_ts=1693307681.776759&cid=C027QFMTPA8)). It looks like a different variation of https://github.com/yugabyte/yugabyte-db/issues/16130
