### ISSUE TITLE
undefined symbol: _ZTIN7rocksdb6LoggerE

### ISSUE THREAD

**Issue by halleyshx** [yugabyte/yugabyte-db#1888]
The all error is：/export/App/yugabyte-1.3.0.0/bin/yb-master: symbol lookup error: /export/App/yugabyte-1.3.0.0/lib/yb/libyb_rocksutil.so: undefined symbol: _ZTIN7rocksdb6LoggerE

I wget the binary file and installed, when I run the command：/export/App/yugabyte-1.3.0.0/bin/yb-master \
  --master_addresses 192.168.224.23:7100,192.168.224.41:7100,192.168.224.36:7100 \
  --rpc_bind_addresses 192.168.224.23 \
  --fs_data_dirs "/export/data/ybdisk1,/export/data/ybdisk2" \
  \>& /export/data/ybdisk1/yb-master.out &

environment：
CentOS Linux release 7.2.1511 (Core) x86_64 GNU/Linux

**Comment by ttyusupov** [comment]
Hi @halleyshx , could you, please, share steps you used to install yugabyteDB? Have you used this instruction exactly ? https://docs.yugabyte.com/latest/quick-start/install/#linux

**Comment by halleyshx** [comment]
Hi @ttyusupov , my steps are same to https://docs.yugabyte.com/latest/quick-start/install/#linux 
1、wget https://downloads.yugabyte.com/yugabyte-1.3.0.0-linux.tar.gz
2、tar xvfz yugabyte-1.3.0.0-linux.tar.gz && cd yugabyte-1.3.0.0/
3、./bin/post_install.sh
4、/export/App/yugabyte-1.3.0.0/bin/yb-master 
--master_addresses 192.168.224.23:7100,192.168.224.41:7100,192.168.224.36:7100 
--rpc_bind_addresses 192.168.224.23 
--fs_data_dirs "/export/data/ybdisk1,/export/data/ybdisk2" 
\>& /export/data/ybdisk1/yb-master.out &
5、show  Exit 
6、cat /export/data/ybdisk1/yb-master.out
7、show the error：/export/App/yugabyte-1.3.0.0/bin/yb-master: symbol lookup error: /export/App/yugabyte-1.3.0.0/lib/yb/libyb_rocksutil.so: undefined symbol: _ZTIN7rocksdb6LoggerE

Newest：I had installed rocksdb program in my machines long ago，I suspect that ”rocksdb6Logger“ is influenced by my local rocksdb? I close the LD_LIBRARY_PATH（It have the rocksdb path） in the /etc/profile and source it .  Then,I try again with the master command , but It doesn't work.
Then I use a pure docker to do this，It don't have the error，but the new error appeared，I will write in the new issue to show

**Comment by ttyusupov** [comment]
Hi @halleyshx ,

>4、/export/App/yugabyte-1.3.0.0/bin/yb-master
--master_addresses 192.168.224.23:7100,192.168.224.41:7100,192.168.224.36:7100
--rpc_bind_addresses 192.168.224.23
--fs_data_dirs "/export/data/ybdisk1,/export/data/ybdisk2"
>& /export/data/ybdisk1/yb-master.out &

Does it work if you start local cluster using `yb-ctl` instead as described in https://docs.yugabyte.com/latest/quick-start/create-local-cluster/ ? 

Also, what was the output of `./bin/post_install.sh`?

**Comment by halleyshx** [comment]
Hi,  @ttyusupov ,
I used yb-ctl command to run in localhost,the return like this :

> # ./bin/yb-ctl create
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1797, in <module>
    control.run()
  File "./bin/yb-ctl", line 1770, in run
    self.args.func()
  File "./bin/yb-ctl", line 1560, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1405, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
2019-07-26 18:43:02,734 INFO: Starting master-1 with:
/export/App/yugabyte-1.3.0.0/bin/yb-master --fs_data_dirs "/root/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/export/App/yugabyte-1.3.0.0 --webserver_doc_root "/export/App/yugabyte-1.3.0.0/www" --replication_factor=1 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100 --use_initial_sys_catalog_snapshot >"/root/yugabyte-data/node-1/disk-1/master.out" 2>"/root/yugabyte-data/node-1/disk-1/master.err" &
2019-07-26 18:43:02,759 INFO: Starting tserver-1 with:
/export/App/yugabyte-1.3.0.0/bin/yb-tserver --fs_data_dirs "/root/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/export/App/yugabyte-1.3.0.0 --webserver_doc_root "/export/App/yugabyte-1.3.0.0/www" --tserver_master_addrs=127.0.0.1:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1:5433 >"/root/yugabyte-data/node-1/disk-1/tserver.out" 2>"/root/yugabyte-data/node-1/disk-1/tserver.err" &
2019-07-26 18:43:02,762 INFO: Waiting for master leader election and tablet server registration.
2019-07-26 18:43:47,509 ERROR: Failed too many times. CMDLINE=['/export/App/yugabyte-1.3.0.0/bin/yb-admin', '--master_addresses', '127.0.0.1:7100', 'list_all_tablet_servers'] RETCODE=127 OUTPUT=
/export/App/yugabyte-1.3.0.0/bin/yb-admin: symbol lookup error: /export/App/yugabyte-1.3.0.0/lib/yb/libyb_rocksutil.so: undefined symbol: _ZTIN7rocksdb6LoggerE

2019-07-26 18:43:48,511 ERROR: Failed waiting for None tservers, got None
^^^ Encountered errors ^^^

**Comment by ttyusupov** [comment]
@halleyshx , can you share `ldd ./bin/yb-master` output?

**Comment by halleyshx** [comment]
@ttyusupov ,the return like this：

> \# ldd ./bin/yb-master
> 	linux-vdso.so.1 =>  (0x00007ffef19a9000)
> 	libatomic.so.1 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libatomic.so.1 (0x00007fb481e65000)
> 	libmaster.so => /export/App/yugabyte-1.3.0.0/lib/yb/libmaster.so (0x00007fb48196f000)
> 	libunwind.so.8 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libunwind.so.8 (0x00007fb481755000)
> 	libtserver.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtserver.so (0x00007fb4813fc000)
> 	libcdc.so => /export/App/yugabyte-1.3.0.0/lib/yb/libcdc.so (0x00007fb4811d2000)
> 	libtablet.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtablet.so (0x00007fb480e61000)
> 	libyb_docdb.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_docdb.so (0x00007fb480b09000)
> 	libyb_pggate_util.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_pggate_util.so (0x00007fb4808f0000)
> 	libyb_client.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_client.so (0x00007fb4804d7000)
> 	libmaster_rpc.so => /export/App/yugabyte-1.3.0.0/lib/yb/libmaster_rpc.so (0x00007fb4802ba000)
> 	libyb_docdb_encoding.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_docdb_encoding.so (0x00007fb480071000)
> 	libyb_rocksutil.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_rocksutil.so (0x00007fb47fe5d000)
> 	librocksdb.so => /export/servers/rocksdb/librocksdb.so (0x00007fb47f62c000)
> 	libsnappy.so.1 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libsnappy.so.1 (0x00007fb47f420000)
> 	libbz2.so.1.0 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libbz2.so.1.0 (0x00007fb47f20e000)
> 	libz.so.1 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libz.so.1 (0x00007fb47eff8000)
> 	libtserver_util.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtserver_util.so (0x00007fb47edf1000)
> 	libserver_process.so => /export/App/yugabyte-1.3.0.0/lib/yb/libserver_process.so (0x00007fb47eb3f000)
> 	libprofiler.so.0 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libprofiler.so.0 (0x00007fb47e929000)
> 	libserver_base_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libserver_base_proto.so (0x00007fb47e6e8000)
> 	libconsensus.so => /export/App/yugabyte-1.3.0.0/lib/yb/libconsensus.so (0x00007fb47e3f6000)
> 	liblog.so => /export/App/yugabyte-1.3.0.0/lib/yb/liblog.so (0x00007fb47e18a000)
> 	libserver_common.so => /export/App/yugabyte-1.3.0.0/lib/yb/libserver_common.so (0x00007fb47df72000)
> 	libyb_fs.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_fs.so (0x00007fb47dd53000)
> 	liblog_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/liblog_proto.so (0x00007fb47db3c000)
> 	libcdc_service_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libcdc_service_proto.so (0x00007fb47d8ed000)
> 	libtserver_service_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtserver_service_proto.so (0x00007fb47d67f000)
> 	libremote_bootstrap_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libremote_bootstrap_proto.so (0x00007fb47d431000)
> 	libconsensus_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libconsensus_proto.so (0x00007fb47d197000)
> 	libbackup_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libbackup_proto.so (0x00007fb47cf79000)
> 	libtserver_admin_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtserver_admin_proto.so (0x00007fb47cd2d000)
> 	libmaster_util.so => /export/App/yugabyte-1.3.0.0/lib/yb/libmaster_util.so (0x00007fb47cb1a000)
> 	libmaster_backup_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libmaster_backup_proto.so (0x00007fb47c8bd000)
> 	libmaster_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libmaster_proto.so (0x00007fb47c45f000)
> 	libyrpc.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyrpc.so (0x00007fb47c0fe000)
> 	librpc_introspection_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/librpc_introspection_proto.so (0x00007fb47bed5000)
> 	libev.so.4 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libev.so.4 (0x00007fb47bcc5000)
> 	libssl.so.1.0.0 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libssl.so.1.0.0 (0x00007fb47ba4d000)
> 	libtserver_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtserver_proto.so (0x00007fb47b7ee000)
> 	libtablet_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libtablet_proto.so (0x00007fb47b5b9000)
> 	libyb_common.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_common.so (0x00007fb47b232000)
> 	libwire_protocol_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libwire_protocol_proto.so (0x00007fb47b01a000)
> 	libredis_protocol_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libredis_protocol_proto.so (0x00007fb47adb4000)
> 	libpgsql_protocol_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libpgsql_protocol_proto.so (0x00007fb47ab80000)
> 	libql_protocol_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libql_protocol_proto.so (0x00007fb47a952000)
> 	libyb_bfql.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_bfql.so (0x00007fb47a697000)
> 	libyb_bfpg.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_bfpg.so (0x00007fb47a43c000)
> 	libuuid.so.1 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libuuid.so.1 (0x00007fb47a236000)
> 	libconsensus_metadata_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libconsensus_metadata_proto.so (0x00007fb47a01e000)
> 	libfs_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libfs_proto.so (0x00007fb479e07000)
> 	libdocdb_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libdocdb_proto.so (0x00007fb479bf5000)
> 	libyb_common_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_common_proto.so (0x00007fb47995c000)
> 	libopid_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libopid_proto.so (0x00007fb479752000)
> 	libyb_pgwrapper.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_pgwrapper.so (0x00007fb47953c000)
> 	librpc_header_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/librpc_header_proto.so (0x00007fb479325000)
> 	libyb_pggate_flags.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_pggate_flags.so (0x00007fb47911f000)
> 	libyb_util.so => /export/App/yugabyte-1.3.0.0/lib/yb/libyb_util.so (0x00007fb478c73000)
> 	libtcmalloc.so.4 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libtcmalloc.so.4 (0x00007fb478872000)
> 	libboost_system.so.1.69.0 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libboost_system.so.1.69.0 (0x00007fb47866e000)
> 	libboost_thread.so.1.69.0 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libboost_thread.so.1.69.0 (0x00007fb478443000)
> 	libgutil.so => /export/App/yugabyte-1.3.0.0/lib/yb/libgutil.so (0x00007fb4781e8000)
> 	libglog.so.0 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libglog.so.0 (0x00007fb477fb2000)
> 	libgflags.so.2 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libgflags.so.2 (0x00007fb477d90000)
> 	libversion_info_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libversion_info_proto.so (0x00007fb477b85000)
> 	libcrypto.so.1.0.0 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libcrypto.so.1.0.0 (0x00007fb477706000)
> 	librt.so.1 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/librt.so.1 (0x00007fb4774fd000)
> 	libcds.so.2.3.3 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libcds.so.2.3.3 (0x00007fb4772f0000)
> 	libicui18n.so.61 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libicui18n.so.61 (0x00007fb476d6b000)
> 	libicuuc.so.61 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libicuuc.so.61 (0x00007fb476967000)
> 	libcrcutil.so.0 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libcrcutil.so.0 (0x00007fb476752000)
> 	libhistogram_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libhistogram_proto.so (0x00007fb47653f000)
> 	libpb_util_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libpb_util_proto.so (0x00007fb476334000)
> 	libencryption_proto.so => /export/App/yugabyte-1.3.0.0/lib/yb/libencryption_proto.so (0x00007fb47610f000)
> 	libprotobuf.so.15 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libprotobuf.so.15 (0x00007fb475bd8000)
> 	libbacktrace.so.0 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libbacktrace.so.0 (0x00007fb4759cd000)
> 	libcurl.so.4 => /export/App/yugabyte-1.3.0.0/lib/yb-thirdparty/libcurl.so.4 (0x00007fb475789000)
> 	libdl.so.2 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libdl.so.2 (0x00007fb475583000)
> 	libstdc++.so.6 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libstdc++.so.6 (0x00007fb475185000)
> 	libm.so.6 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libm.so.6 (0x00007fb474e80000)
> 	libgcc_s.so.1 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libgcc_s.so.1 (0x00007fb474c66000)
> 	libpthread.so.0 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libpthread.so.0 (0x00007fb474a47000)
> 	libc.so.6 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libc.so.6 (0x00007fb4740a6000)
> 	/export/App/yugabyte-1.3.0.0/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007fb482070000)
> 	libicudata.so.61 => /export/App/yugabyte-1.3.0.0/linuxbrew/lib/libicudata.so.61 (0x00007fb4724f5000)

**Comment by ttyusupov** [comment]
That confirm that it picks up different `librocksdb.so` instead of distributed with YB:
```
librocksdb.so => /export/servers/rocksdb/librocksdb.so (0x00007fb47f62c000)
```
The workaround is to unset `LD_LIBRARY_PATH` as I believe you already did. 

We will look into how to make it always pick up our version of `librocksdb`.

**Comment by halleyshx** [comment]
You are right.Thanks!

**Comment by ttyusupov** [comment]
As an option, we can unset `LD_LIBRARY_PATH` in `yb-ctl` for better control of dependent libraries, what do you think @mbautin ?

**Comment by mbautin** [comment]
Setting LD_LIBRARY_PATH might break a lot of different applications that rely on shared libraries, and I am not sure how we can make YugabyteDB work if LD_LIBRARY_PATH provides libraries with the same names that interfere with YugabyteDB's own shared libraries. Inside YugabyteDB, we have no need for setting LD_LIBRARY_PATH as we set RPATH / RUNPATH properly so that all executables and shared libraries can find their dependencies.
