### ISSUE TITLE
[Transactional xCluster][Automatic Tablet Splitting][PITR] Observed duplicate rows at target with atomicity validation

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#18897]
Jira Link: [DB-7756](https://yugabyte.atlassian.net/browse/DB-7756)
### Description

Version: **2.19.3.0-b26**
GFLAGs:
```
Master:
"tablet_split_high_phase_shard_count_per_node": 576,
"tablet_split_high_phase_size_threshold_bytes": 102400,
"tablet_split_low_phase_size_threshold_bytes": 10240,
"tablet_split_low_phase_shard_count_per_node": 96,

Tserver:
"ysql_num_shards_per_tserver": 1
```
Steps:
1. Create DB and tables at source, same DB at Target
2. Create snapshot schedule for the DB at both sides
3. Create replication from A-to-B(source to target)
4. Collect time(t1)
5. Load data and validate atomicity and ordering - both are working fine
6. Restore to time t1(restore at both sides) - restores were successful
7. Reload data and validate atomicity
It failed with duplicate data at target(there are 12 records at Source and 24 records at Target)
```
demo1=# select * from account_balance order by id;
 id | name  | salary
----+---------+---------
 1 | AAA  | 675000
 1 | AAA  | 1000000
 2 | BBB | 675000
 2 | BBB | 1000000
 3 | CCC | 1000000
 3 | CCC | 1650000
 4 | AAA  | 1000000
 4 | AAA  | 675000
 5 | BBB | 675000
 5 | BBB | 1000000
 6 | CCC | 1000000
 6 | CCC | 1650000
 7 | AAA  | 1000000
 7 | AAA  | 675000
 8 | BBB | 1000000
 8 | BBB | 675000
 9 | CCC | 1000000
 9 | CCC | 1650000
 10 | AAA  | 675000
 10 | AAA  | 1000000
 11 | BBB | 1000000
 11 | BBB | 675000
 12 | CCC | 1000000
 12 | CCC | 1650000
(24 rows)
```
If I delete all records(12 rows) at source, I see there are old records present at target
```
demo1=# select * from account_balance order by id;
 id |  name   | salary
----+---------+---------
  1 | AAA    |  675000
  2 | BBB  |  675000
  3 | CCC | 1650000
  4 | AAA    |  675000
  5 | BBB  |  675000
  6 | CCC | 1650000
  7 | AAA    |  675000
  8 | BBB  |  675000
  9 | CCC | 1650000
 10 | AAA    |  675000
 11 | BBB  |  675000
 12 | CCC | 1650000
(12 rows)
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7756]: https://yugabyte.atlassian.net/browse/DB-7756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hulien22** [comment]
@Arjun-yb Please list all the gflags used for this test - is `enable_tablet_split_of_xcluster_replicated_tables` also set on these clusters?

**Comment by lingamsandeep** [comment]
This is an issue with the test automation. For PITR to work correctly with XCluster when both sides are being restored, the following is the recommended sequence:

1. Stop application workloads and make sure there are no active transactions.
1. Wait for replication to complete.
1. Delete xCluster replication from both sides.
1. Restore both clusters to the exact same time.
1. Re-establish xCluster replication.
1. Resume the application workloads.
