### ISSUE TITLE
[DocDB] PG_locks GA items

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#18901]
Jira Link: [DB-7759](https://yugabyte.atlassian.net/browse/DB-7759)
### Description

This github tracks the longer term items for the PG_locks feature.

Postgres
- [ ] https://github.com/yugabyte/yugabyte-db/issues/16919

Transaction Coordinator

- [ ] https://github.com/yugabyte/yugabyte-db/issues/16913

See https://github.com/yugabyte/yugabyte-db/issues/12168 for tech preview items.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7759]: https://yugabyte.atlassian.net/browse/DB-7759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
closing this umbrella task as both of these items are individually tracked
