### ISSUE TITLE
[DocDB]  ALTER TYPE data got corrupted with UNIQUE with TEMP table

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#18909]
Jira Link: [DB-7764](https://yugabyte.atlassian.net/browse/DB-7764)
### Description

Executed this on `2.19.3.0-b26`

it is reproducible 100% of the time.It is observed only with `TEMP` table

```
db=# CREATE TEMP TABLE test_table (col1 text UNIQUE);
CREATE TABLE
db=# INSERT INTO test_table VALUES ('1'), ('01');
INSERT 0 2
db=# select * from test_table;
 col1 
------
 1
 01
(2 rows)

db=# \d test_table
          Table "pg_temp_2.test_table"
 Column | Type | Collation | Nullable | Default 
--------+------+-----------+----------+---------
 col1   | text |           |          | 
Indexes:
    "test_table_col1_key" UNIQUE CONSTRAINT, btree (col1 ASC)

db=# ALTER TABLE test_table ALTER COLUMN col1 TYPE integer using col1::int;
ALTER TABLE
db=# select * from test_table;
ERROR:  could not read block 0 in file "base/16640/t2_16508": read only 0 of 8192 bytes
```
cc: @fizaaluthra @kripasreenivasan 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7764]: https://yugabyte.atlassian.net/browse/DB-7764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
If this is TEMP TABLE only, it is not a docdb issue.  Please specify build platform, build type (release, debug), compiler.

**Comment by agsh-yb** [comment]
@jasonyb it is observed with `TEMP` TABLE only
