### ISSUE TITLE
[YSQL] ALTER TABLE on temp table: Not NULL condition is ignored with boolean

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#18911]
Jira Link: [DB-7766](https://yugabyte.atlassian.net/browse/DB-7766)
### Description

Executed this on `2.19.3.0-b26`

it is reproducible 100% of the time.
```
db=# CREATE TEMP TABLE test_table (col1 integer NOT NULL);
CREATE TABLE
db=# INSERT INTO test_table VALUES (0);
INSERT 0 1
db=# ALTER TABLE test_table ALTER COLUMN col1 TYPE boolean USING (CASE WHEN col1 = 0 THEN NULL ELSE TRUE END);
ALTER TABLE
db=# select * from test_table;
 col1 
------
 f
(1 row)
```

Without `TEMP TABLE` it shows different behaviour
```
db1=# CREATE TABLE test_table (col1 integer NOT NULL);
CREATE TABLE
db1=# INSERT INTO test_table VALUES (0);
INSERT 0 1
db1=# ALTER TABLE test_table ALTER COLUMN col1 TYPE boolean USING (CASE WHEN col1 = 0 THEN NULL ELSE TRUE END);
ALTER TABLE
db1=# select * from test_table;
 col1 
------
 
(1 row)
```
cc: @fizaaluthra @kripasreenivasan 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7766]: https://yugabyte.atlassian.net/browse/DB-7766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
If this is TEMP TABLE only, it is not a docdb issue.  Please specify build platform, build type (release, debug), compiler.

**Comment by agsh-yb** [comment]
@jasonyb Without temp table a different behaviour is observed I have added the observation above
