### ISSUE TITLE
[DocDB] Alter type Data inconsistency with text->date seen with TEMP TABLE

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#18910]
Jira Link: [DB-7765](https://yugabyte.atlassian.net/browse/DB-7765)
### Description

Executed this on 2.19.3.0-b26

it is reproducible 100% of the time.It is observed with `TEMP` table only
```
db=# CREATE TEMP TABLE temp (col1 text);;
CREATE TABLE
db=# INSERT INTO temp values ('2023-13-39');
INSERT 0 1
db=# ALTER TABLE temp ALTER COLUMN col1 TYPE date USING to_date(col1, 'YYYY-MM-DD');
ALTER TABLE
db=# SELECT * FROM temp;
     col1      
---------------
 2307370-09-06
(1 row)
```
cc: @fizaaluthra @kr

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7765]: https://yugabyte.atlassian.net/browse/DB-7765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
If this is TEMP TABLE only, it is not a docdb issue.  Please specify build platform, build type (release, debug), compiler.

**Comment by agsh-yb** [comment]
@jasonyb it is observed with TEMP TABLE only.
