### ISSUE TITLE
[YSQL][Read Committed] Improve error reporting when multiple writes are batched into one request

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18968]
Jira Link: [DB-7811](https://yugabyte.atlassian.net/browse/DB-7811)
### Description

Tried on version 2.19.3.0-b27
Currently, when multiple writes are batched into one request, we merge errors and report it and the end user experience is confusing. 
For example, the below error:
```
ERROR: Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Internal error (yb/docdb/deadlock_detector.cc:634): Transaction 406147b2-638e-4312-9eae-69e9c4ceaeac aborted due to a deadlock.
               406147b2-638e-4312-9eae-69e9c4ceaeac -> 0d6acc52-59f9-4813-a5b8-6f1e24088007 -> 406147b2-638e-4312-9eae-69e9c4ceaeac : kDeadlock (transaction error 6),
 Operation failed. Try again (yb/docdb/conflict_resolution.cc:84): 406147b2-638e-4312-9eae-69e9c4ceaeac conflicts with committed transaction: 5edcbb9b-e00d-4ea3-8102-1ebd62738696 (transaction error 3)]
```
Transaction 1 = **406147b2-638e-4312-9eae-69e9c4ceaeac**
Transaction 2 = **0d6acc52-59f9-4813-a5b8-6f1e24088007**
There was deadlock between T1 and  T2  so T1 was aborted which is expected (1st part of the error message)
Transaction 3 = **5edcbb9b-e00d-4ea3-8102-1ebd62738696**
But in the 2nd part of the error,  we see T1 conflicts with T3, which is a committed transaction.
In the first part of the error, we are saying T1 was aborted, and in the second part of the error, we are saying it conflicts with some other transaction(T3). Wouldn’t this confuse the user?

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7811]: https://yugabyte.atlassian.net/browse/DB-7811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment]
I think this is not an issue now, after some fixes including the likes of 60ac2325
