### ISSUE TITLE
[docs] YCSB benchmark can not work

### ISSUE THREAD

**Issue by gdyang1990** [yugabyte/yugabyte-db#1897]
I tried  to run the YCSB benchmark following the steps in  https://docs.yugabyte.com/latest/benchmark/ycsb/, but failed.

The script _**run-yb-ycsb.sh**_  has an error that there is no _**load_data**_ command.
So can someone fix that error ?

**Comment by m-iancu** [comment]
@gdyang1990 Thanks for reporting this!
I had a quick look and looks like an error in our docs. The data loading now happens inside the `run_workload` function so we should remove the two lines calling `load_data`.
Can you try if it works for you to just change the bottom part of the script to:
```
setup

run_workload workloada
run_workload workloadb
run_workload workloadc
run_workload workloadd
run_workload workloade
run_workload workloadf

cleanup
```

We will make sure to double-check and update our docs soon.

**Comment by ttyusupov** [comment]
@gdyang1990 , did this help?

**Comment by ajcaldera1** [comment]
I verified that this suggestion does work. We should update our docs and close.

**Comment by stevebang** [comment]
@psudheer21 Is this still an issue? If not, close.

**Comment by psudheer21** [comment]
We can close this issue as we are now using a fork of the upstream branch that works properly with us.
The docs have been changed to reflect how to correctly run the benchmark.
