### ISSUE TITLE
Failed to run benchmark(CassandraTransactionalKeyValue)

### ISSUE THREAD

**Issue by GOGOYAO** [yugabyte/yugabyte-db#1898]
Jira Link: [DB-4722](https://yugabyte.atlassian.net/browse/DB-4722)
OS version: centos 7.6
db version: 1.3.0.0
node num: 3

I run benchmark following steps in https://docs.yugabyte.com/latest/benchmark/performance/. My os is centos 7.6 and I can succeed to get the benchmark result of CassandraKeyValue. But when I run it again for CassandraTransactionalKeyValue app, I can not get benchmark result and I can see many error messages such as `com.datastax.driver.core.exceptions.OperationTimedOutException: [/xxxxxx:9042] Timed out waiting for server response`.

Any ideas?

**Comment by ndeodhar** [comment]
@GoGoYao Can you check if there are any errors in tserver logs? You can find the logs at `$data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO`.

Also check if there are messages like `Soft memory limit exceeded` in the logs.

**Comment by GoGoYao** [comment]
@ndeodhar There is no `Soft memory limit exceeded` in the logs. I will try rebuild the cluster with 3 nodes and try CassandraTransactionalKeyValue again.

**Comment by ttyusupov** [comment]
@GoGoYao , were you able to run `CassandraTransactionalKeyValue` workload?
What is the hardware configuration for each node? Are you using HDD or SSD for the data?

**Comment by murugesan70** [comment]
+1

**Comment by abhinavswami** [comment]
It throws the exact same error for me. I looked into $data_dir/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO and a table creation query fails and below error is logged. Can you please help?

```
E0918 15:10:14.948055 57982976 ts_tablet_manager.cc:1114] T 5e8c392df5b04301b100e8731ed03bf1 P f122e840c20b4ff486a2feaec3e88e38: Tablet failed to bootstrap: Illegal state (yb/tablet/tablet.cc:564): IO error (yb/rocksdb/util/env_posix.cc:653): /Users/XXX/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-872afe0a666c4cd9a5199966181b0eb2/tablet-5e8c392df5b04301b100e8731ed03bf1/MANIFEST-000001: Too many open files
```

**Comment by ndeodhar** [comment]
@abhinavswami The `Too many open files` error that you're seeing is related to system ulimits. You'll need to increase the limit for open files. See this for more details:
https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/#setting-ulimits

**Comment by rthallamko3** [comment]
Closing this as the error seems to be related to system ulimits.
