### ISSUE TITLE
[YSQL] Script for updating schema to be YB-compatible

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1901]
Jira Link: [DB-1321](https://yugabyte.atlassian.net/browse/DB-1321)
There are some flavors of `ALTER TABLE` that are still not supported by YSQL. A common workaround is to update `CREATE TABLE` statement with these variations. For example, we don't yet support
`ALTER TABLE ALTER COLUMN SET DEFAULT`
The workaround to this is to change the `CREATE TABLE` statement to include the default.

We should create a script that can be used to create a YB-compatible schema from a postgres schema.

**Comment by sushantrmishra** [comment]
We have added the support for [yb-voyager](https://docs.yugabyte.com/preview/migrate/yb-voyager-cli/)  which can be used to migrate schema from PostgreSQL to YugabyteDB.
