### ISSUE TITLE
[DocDB] PITR failing with Timed out waiting for inflight tablet splitting to complete

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#19028]
Jira Link: [DB-7849](https://yugabyte.atlassian.net/browse/DB-7849)
### Description

PITR take more than usual time and fails with error on `2.19.*` and `2.18.*`

Steps in test:
```
        1. Create a cluster with nodes enable enable_automatic_tablet_splitting,
        yb_num_shards_per_tserver=32, set tablet split high phase and low phase shard count,
        2. Create 10 tables, start a workload to tablets to split
        3. Create Backup
        4. Update Gflags set yb_num_shards_per_tserver=1
        5. Create Snapshot
        6. Note time(x)
        7. Start a Loop
            a. Set up parallel connections (1k-2k) randomly
            b. Create 10 temp tables & load data(10 mb), Start a workload
            c. Restore Snapshots to some random time
            d. Load data to previous Tables
            e. Restore snapshot to time(x)
```
Issue: Test failing on step 7c on second iteration 

GFlags:
```
master_gflags={
            "enable_automatic_tablet_splitting": "true",
            "yb_num_shards_per_tserver": "32",
            "tablet_split_high_phase_shard_count_per_node": 200,
            "tablet_split_high_phase_size_threshold_bytes": 2097152,
            "tablet_split_low_phase_size_threshold_bytes": 102400,
            "tablet_split_low_phase_shard_count_per_node": 98,
            "inflight_splits_completion_timeout_secs": 3600000,
            "pitr_max_restore_duration_secs": 3600000
        },
        tserver_gflags={
            "enable_automatic_tablet_splitting": "true",
            "yb_num_shards_per_tserver": "32",
        }
```
[**Logs**](https://drive.google.com/file/d/1YSUTG9gfo5xDJTkLszLCR-AMpDx0LZZu/view?usp=sharing) attached

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7849]: https://yugabyte.atlassian.net/browse/DB-7849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
@agsh-yb - Is this a PITR or Restore ? Are you running a workload during PITR ? How long did it take before vs now ? What is it failing with ? Where is the snippet of the error ?

**Comment by agsh-yb** [comment]
@lingamsandeep This is a Restore issue, No workloads were stopped before restore. 
I was unable to restore this snapshot it failed after 
### Error:
```
2023-08-16 03:20:09,333: INFO: start step Restore Snapshot to a random time(f2c18bca-d0cd-4064-8cfd-53164e63a12c) Cycle=0 name=Restore Snapshot to a random time
2023-08-16 03:21:09,333: INFO: elapsed_time:2, end_time1692156069.3333597,start_timestart_time1692155901.1011455 
2023-08-16 03:21:09,333: INFO: restore from schedule 61cacd64-b2d4-4382-b658-8c5ee6c841da at 1m
2023-08-16 03:21:09,333:DEBUG: > 172.151.26.186 > /home/yugabyte/tserver/bin/yb-admin --master_addresses 172.151.26.186,172.151.25.54,172.151.31.207  -timeout_ms 3600000 restore_snapshot_schedule 61cacd64-b2d4-4382-b658-8c5ee6c841da minus 1m 2>&1
2023-08-16 03:31:10,410:DEBUG: < 172.151.26.186 < Error running restore_snapshot_schedule: Timed out (yb/master/catalog_manager_ext.cc:2938): Timed out waiting for inflight tablet splitting to complete.

2023-08-16 03:31:10,410:ERROR: failed to run restoration: 
Error running restore_snapshot_schedule: Timed out (yb/master/catalog_manager_ext.cc:2938): Timed out waiting for inflight tablet splitting to complete.
```

<img width="1725" alt="Screenshot 2023-09-28 at 11 42 06 AM" src="https://github.com/yugabyte/yugabyte-db/assets/121818428/0aa125e8-0790-409e-956c-e98d716b688f">

**Comment by lingamsandeep** [comment]
The tablet-splitting knobs are too aggressive here. Moreover, we should wait for inflight tablet splits to complete before issuing PITR otherwise PITR times out by design. 
It is ok to do PITR to a time when tablet-splits were inflight. Restore time can be in the middle of a split.
However when a PITR is being performed, we need to make sure splits are not running - otherwise the command will timeout waiting depending on how long splits take.
