### ISSUE TITLE
[DocDB] Statement timeout is not honored in certain cases, leading to failures with error - Failed to obtain locks until deadline: 33135.898s

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#19032]
Jira Link: [DB-7851](https://yugabyte.atlassian.net/browse/DB-7851)
### Description

Tried on version **2.19.3.0-b67**
One of the transaction with read committed isolation level failed with the below error.

`
Errors from tablet servers: [Operation failed. Try again (yb/docdb/lock_batch.cc:42): Flush: Failed to obtain locks until deadline: 33135.898s, batch: [{ key:  intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A31343630320000 intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438 382D3561663165623834386433363A3134363032000021214A80 intent_types: [kStrongRead, kStrongWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A3135313031380000 intent_types: [kWeakRead, kWeakWrite] }, { key: 
.
.
.`

```
Steps to repro:
Use SqlReadCommitted sample app(Connect with @shishir2001-yb for more details) 

Execute the below steps in a loop, the above error will occur in 5-6 hours.
1. Start 40 parallel thread and start one Transaction in each thread.
2. In each transaction execute the following
    a. Insert 10 rows.
    b. One out of every 100 Transaction executes `UPDATE table1 SET V1='be8ef4cb-ec72-4679-a488-5af1eb848d36:1' 
         WHERE k like %s or k like .%s.........(100 times)`. %s-> Is some random alphabetical character example 'a'
    c.  Execute SELECT k FROM table WHERE k=be8ef4cb-ec72-4679-a488-5af1eb848d36:1 or k= ...... 100 Ids
    d.  Commit the transactions
```
```
G-flags

"enable_wait_queues":"true",
"enable_deadlock_detection": "true",
"yb_enable_read_committed_isolation": "true",
"ysql_output_buffer_size": "162144000", #160MB
```
[Logs](https://drive.google.com/drive/folders/1tnPUa2GLh-R9aSU3YmEvSkL71oz72Sk3?usp=sharing) 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7851]: https://yugabyte.atlassian.net/browse/DB-7851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
looks like the workload is genuinely quite contentious, and this error may be expected

we should confirm that the error code returned to the client is still correct

**Comment by robertsami** [comment]
we should also follow-up on adjusting this workload to be more realistic (ie contention within realistic bounds)

**Comment by shishir2001-yb** [comment]
@robertsami,  I agree the workload was quite contentious but showing the below part to the user doesn't make sense, please correct me if I am wrong.

`
batch: [{ key:  intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A31343630320000 intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438 382D3561663165623834386433363A3134363032000021214A80 intent_types: [kStrongRead, kStrongWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A3135313031380000 intent_types: [kWeakRead, kWeakWrite] }, { key:  . . .
`

**Please note:** I have only pasted >2% of the whole error message. 

Also, the workload has been updated now and it doesn't perform such unrealistic operation :)

**Comment by basavaraj29** [comment]
When we explicitly set a flag to skip printing the locks in the error messages, here's what wee see in the postgres logs.
```
yb-dev-ssharma-test-source10-n1/tserver/logs/postgresql-2023-09-08_213752.log.gz:2023-09-08 21:53:22.577 UTC [252366] ERROR:  Flush: Failed to obtain locks until deadline: 13578.348s: . Errors from tablet servers: [Operation failed. Try again (yb/docdb/lock_batch.cc:42): Flush: Failed to obtain locks until deadline: 13578.348s]
yb-dev-ssharma-test-source10-n1/tserver/logs/postgresql-2023-09-08_213752.log.gz-2023-09-08 21:53:22.577 UTC [252366] STATEMENT:  UPDATE tbl_no_explicit_lock SET V1='be8ef4cb-ec72-4679-a488-5af1eb848d36:403146' WHERE k like 'e%' or k like 'v%' or k like 'm%' or k like 'c%' or k like 'l%' or k like 'k%' or k like 't%' or k like 'h%' or k like 'w%' or k like 'x%' or k like 'g%' or k like 'e%' or k like 't%' or k like 's%' or k like 'e%' or k like 'z%' or k like 'y%' or k like 'h%' or k like 'e%' or k like 'y%' or k like 'o%' or k like 'c%' or k like 'g%' or k like 'h%' or k like 'd%' or k like 'c%' or k like 'o%' or k like 'd%' or k like 'c%' or k like 'm%' or k like 's%' or k like 'a%' or k like 'v%' or k like 'e%' or k like 'x%' or k like 't%' or k like 'm%' or k like 'd%' or k like 's%' or k like 'u%' or k like 'g%' or k like 'r%' or k like 'u%' or k like 'e%' or k like 'v%' or k like 'd%' or k like 'u%' or k like 'd%' or k like 'n%' or k like 'c%' or k like 'c%' or k like 'k%' or k like 'a%' or k like 'n%' or k like 'o%' or k like 'j%' or k like 'm%' or k like 'l%' or k like 'u%' or k like 'x%' or k like 'y%' or k like 'm%' or k like 'z%' or k like 'f%' or k like 'g%' or k like 'd%' or k like 'b%' or k like 'e%' or k like 't%' or k like 'u%' or k like 'd%' or k like 'l%' or k like 'f%' or k like 't%' or k like 'm%' or k like 't%' or k like 'a%' or k like 'p%' or k like 'k%' or k like 'u%' or k like 'g%' or k like 'a%' or k like 'o%' or k like 'g%' or k like 'd%' or k like 's%' or k like 's%' or k like 'x%' or k like 'z%' or k like 'x%' or k like 'v%' or k like 'c%' or k like 'm%' or k like 'g%' or k like 'y%' or k like 'q%' or k like 'r%' or k like 'e%' or k like 'w%' or k like 'a%' 
```

TBD if we are okay with this format, or if we should be explicitly returning a `Timeout` or something similar.

**Comment by robertsami** [comment]
TBD, one of two approaches (or both) should be considered:
1. Retry mechanism in wait queue to acquire shared in-memory locks
2. Query layer should retry RPCs when receiving this failure, with some backoff

**Comment by robertsami** [comment]
we are not currently planning to backport this to 2.20

**Comment by rthallamko3** [comment]
Per recent conversations, it seems like this will impact test stability of unit tests. Pasting @basavaraj29 's message here

[org.yb.pgsql.TestPgTransparentRestarts.selectStarShortPreparedParameterized failures](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgReadTimeTest&fail_tag=all&name=TestConflictRetriesOnDocdb&num_commits=500&platform=linux)
[PgReadTimeTest.TestConflictRetriesOnDocdb failures](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgTransparentRestarts&fail_tag=all&name=selectStarShortPreparedParameterized&platform=all)

All of the test failures are in tsan mode. Could do either of two things -
1.  Backporting #19032
2. Re-architect the tests to allow other categories of errors without strictly asserting for one error type alone.

**Comment by basavaraj29** [comment]
the above commit (https://github.com/yugabyte/yugabyte-db/commit/7d7a6363db0cdee35a4819927e9941d925dd0c65) introduced a bug which is fixed by commit https://github.com/yugabyte/yugabyte-db/commit/bf593a87b9739c5d4d0241201cc006c8e17eab1d. when backporting the above commit, we should backport the fix as well.
