### ISSUE TITLE
[DocDB][Tablet splitting] PGSQL operation triggered during parent tablet shutting down may be not retried

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#19033]
Jira Link: [DB-7852](https://yugabyte.atlassian.net/browse/DB-7852)
### Description

A Pgsql operation, triggered during parent tablet shutting down may be not retried and return an error back to PG layer in some rare cases. The issue was seen once during local testing on a dev server and was related to select statement:
```
[ts-1] W0904 21:41:31.858565 16536 tablet_rpc.cc:464] Not found (yb/tablet/tablet_peer.cc:1366): Failed Read(tablet: 0ed5e8c690a7451bb42b3c71c8c7aa55, num_ops: 1, num_attempts: 1, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) to tablet 0ed5e8c690a7451bb42b3c71c8c7aa55 on tablet server { uuid: e35f1a6355214712953a70c3616f32a7 private: [host: "127.0.0.2" port: 23080] public: [host: "127.0.0.3.ip.yugabyte" port: 23080] cloud_info: placement_cloud: "cloud1" placement_region: "rack1" placement_zone: "zone" after 1 attempt(s): Tablet peer T 0ed5e8c690a7451bb42b3c71c8c7aa55 P e35f1a6355214712953a70c3616f32a7 [state=QUIESCING]:  is shutting down (tablet server error 12)
...
[ts-1] I0904 21:41:31.861160 16401 raft_consensus.cc:2765] T 0ed5e8c690a7451bb42b3c71c8c7aa55 P e35f1a6355214712953a70c3616f32a7 [term 1 LEADER]: Shutdown.
../../src/yb/yql/pgwrapper/pg_tablet_split-test.cc:535: Failure
Failed
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:355): Fetch 'SELECT * FROM t ORDER BY k ASC' failed: 7, message: ERROR:  Tablet peer T 0ed5e8c690a7451bb42b3c71c8c7aa55 P e35f1a6355214712953a70c3616f32a7 [state=QUIESCING]:  is shutting down (pgsql error XX000) (aux msg ERROR:  Tablet peer T 0ed5e8c690a7451bb42b3c71c8c7aa55 P e35f1a6355214712953a70c3616f32a7 [state=QUIESCING]:  is shutting down)
```
It is expected that the error should be handled correctly on tserver's yb-client side and there's a sufficient handling of ShutdownInProgress status which is expected to be returned by a tablet in QUIESCING state.

But it turns out consensus logic returns `NotFound` status for the shutting down case, and later the status is extended with `TabletServerErrorPB::TABLET_NOT_RUNNING` error code (seen from the logs, tablet server error 12). Such combination is not expected and is not considered as retryable operation by yb-client.

In theory the issue can be seen in production, but I'm not recalling any recent reports with similar errors.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7852]: https://yugabyte.atlassian.net/browse/DB-7852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment]
This [commit](https://github.com/yugabyte/yugabyte-db/commit/7d534832403c848666041508411b6f4e623ac0ee) refactored and unified access to a consensus internal data, but as a result changed the statuses returned in some cases. Before that change yb-client may get IllegalState and ServiceUnavailable statuses in most case which are handled correctly in terms of operation retrying.

**Comment by bmatican** [comment]
cc @hari90 ^^^

**Comment by bmatican** [comment]
@arybochkin Do we not have tests for these? I'm surprised the commit above made it through and broke this parent retry logic, without us catching it deterministically...

**Comment by arybochkin** [comment]
@bmatican, we might have some tests for general cases, but there is a really huge variety of possible places and status why the operation's RPC may fail. This particular case looks too rare, I was able to capture it 1 out of 2000 runs and only locally. We generally getting shutting down in a couple of different places.

**Comment by arybochkin** [comment]
While investigating another issue found this issue and failure for `PgTabletSplitTest/PgPartitioningVersionTest.ManualSplit/0` run on centos-clang16-debug:
```
[ts-1] W0906 01:48:47.481269 15717 tablet_rpc.cc:464] Not found (yb/tablet/tablet_peer.cc:1366): Failed Read(tablet: {t1_tablet_id1}, num_ops: 1, num_attempts: 1, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) to tablet {t1_tablet_id1} on tablet server { uuid: {ts1_peer_id} private: [host: "127.0.0.2" port: 15473] public: [host: "127.0.0.3.ip.yugabyte" port: 15473] cloud_info: placement_cloud: "cloud1" placement_region: "rack1" placement_zone: "zone" after 1 attempt(s): Tablet peer T {t1_tablet_id1} P {ts1_peer_id} [state=QUIESCING]:  is shutting down (tablet server error 12)
...
[ts-1] I0906 01:48:47.491936 15622 ts_tablet_manager.cc:3074] Deleted transition in progress deleting tablet for tablet {t1_tablet_id1}
../../src/yb/yql/pgwrapper/pg_tablet_split-test.cc:851: Failure
Failed
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:359): Fetch 'SELECT COUNT(*) FROM t1' failed: 7, message: ERROR:  Tablet peer T {t1_tablet_id1} P {ts1_peer_id} [state=QUIESCING]:  is shutting down (pgsql error XX000) (aux msg ERROR:  Tablet peer T {t1_tablet_id1} P {ts1_peer_id} [state=QUIESCING]:  is shutting down)
```
Will try to repro with this tests in a series of runs on a dev server.

**Comment by arybochkin** [comment]
It turns out the issue is [met](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=PgTabletSplittingWaitQueuesTest&name=SplitTablet) for `PgTabletSplittingWaitQueuesTest.SplitTablet` in alma8-clang16-asan
