### ISSUE TITLE
[YSQL] [Unit Test] Flaky test CppCassandraDriverTest.BatchWriteDuringSoftMemoryLimit

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#19052]
Jira Link: [DB-7868](https://yugabyte.atlassian.net/browse/DB-7868)
### Description

CppCassandraDriverTest.BatchWriteDuringSoftMemoryLimit test became a lot flaky and constantly failing for last 3 builds on alma builds with process crash error:

```
../../src/yb/integration-tests/external_mini_cluster.cc:1547
Value of: d->IsProcessAlive()
  Actual: false
Expected: true
At least one process crashed. viz: ts-1
```
Complete logs: https://gist.github.com/rjalan-yb/8d0f73a8c72660b9da9dc4faf6bb6617
Stability trend: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=CppCassandraDriverTest&name=BatchWriteDuringSoftMemoryLimit

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7868]: https://yugabyte.atlassian.net/browse/DB-7868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Fixed by 0f02496e56489d77f32b067eb14233c16696edb9, but commit issue # was typo-ed
