### ISSUE TITLE
[docdb] Handle copartitioned tables whenever doing an AlterTable request with wal retention secs

### ISSUE THREAD

**Issue by hectorgcr** [yugabyte/yugabyte-db#1905]
Jira Link: [DB-1823](https://yugabyte.atlassian.net/browse/DB-1823)
As part of the changes for #1524, we need to be able to handle co-partitioned tables. Currently the catalog manager doesn't have enough information to determine when a table is co-partitoined,  so during an AlterRequest, the SysTablesEntryPB wal retention field will only get changed for the requested table, even though at the raft level, the change will take effect for all the co-partitioned tables since they share the same raft group.

Since currently, only system tables are co-partitioned, it's not necessary to make the change now, but once #79 gets implemented, we will have to address this issue.

**Comment by hectorgcr** [comment]
Again, it's probably better to get rid of the automatic increase of log retention time, and we can close this issue once that has been done

**Comment by bmatican** [comment]
Passing this to @hulien22 as a note for when he starts implementation work for 2dc+colocation

**Comment by druzac** [comment]
We abandoned the co-partitioning feature.
