### ISSUE TITLE
Large transactional writes leave large memtables

### ISSUE THREAD

**Issue by JDNdeveloper** [yugabyte/yugabyte-db#1906]
After inserting 1M rows using a single distributed transaction (e.g. YSQL COPY) it was observed that the IntentsDB and RegularDB memtables were much larger than the configured memstore size limit. The memstore size limit was 128MB, but the IntentsDB memtable was 793MB and the RegularDB memtable was 477MB. 

The issue has two causes:
1. Intents are applied in a single rocksdb write batch, meaning the memtable can grow as large as the size of the write batch which could exceed the memstore size limit. The fix for this will be to batch the regular record writes when intents are applied, and similarly to batch the deletion of the intents on distributed txn cleanup.
1. Memtables are only checked for whether they exceed the memstore size limit (forcing a flush) before a write is performed, meaning if a large single write is processed it could leave the memtables larger than the configured maximum memstore size until another write on the rocksdb is processed. The fix for this will be to move this check until after the write is performed, to ensure it is flushed if the current write exceeded the memstore size limit.

**Comment by bmatican** [comment]
Closing this as after #1923, this should not be a problem anymore, as we should not reach really large memstore sizes (ie: outside out global limit of memstore memory).
