### ISSUE TITLE
[YSQL] record type has not been registered occur while selecting data_type_privileges table with batched nested loop join

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#19094]
Jira Link: [DB-7901](https://yugabyte.atlassian.net/browse/DB-7901)
### Description

Does not reproduced if `yb_bnl_batch_size = 1`

```
set yb_bnl_batch_size = 1024;

yugabyte=# EXPLAIN select * from information_schema.data_type_privileges;
ERROR:  record type has not been registered
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7901]: https://yugabyte.atlassian.net/browse/DB-7901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
Not able to repro in 2.21.
