### ISSUE TITLE
[YSQL] Assertion failure with yb_enable_base_scans_cost_model on

### ISSUE THREAD

**Issue by andrei-mart** [yugabyte/yugabyte-db#19104]
Jira Link: [DB-7909](https://yugabyte.atlassian.net/browse/DB-7909)
### Description

Assertion:
https://github.com/yugabyte/yugabyte-db/blob/4b00015225d6c6d924b13d0a1a4cea44e32798b3/src/postgres/src/backend/optimizer/path/costsize.c#L6122
Query: `select count(*) from lineitem where yb_hash_code(l_orderkey) > 512;`
Table:
```
CREATE TABLE LINEITEM ( L_ORDERKEY    INTEGER NOT NULL,
                             L_PARTKEY     INTEGER NOT NULL,
                             L_SUPPKEY     INTEGER NOT NULL,
                             L_LINENUMBER  INTEGER NOT NULL,
                             L_QUANTITY    DECIMAL(15,2) NOT NULL,
                             L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
                             L_DISCOUNT    DECIMAL(15,2) NOT NULL,
                             L_TAX         DECIMAL(15,2) NOT NULL,
                             L_RETURNFLAG  CHAR(1) NOT NULL,
                             L_LINESTATUS  CHAR(1) NOT NULL,
                             L_SHIPDATE    DATE NOT NULL,
                             L_COMMITDATE  DATE NOT NULL,
                             L_RECEIPTDATE DATE NOT NULL,
                             L_SHIPINSTRUCT CHAR(25) NOT NULL,
                             L_SHIPMODE     CHAR(10) NOT NULL,
                             L_COMMENT      VARCHAR(44) NOT NULL,
                             PRIMARY KEY(L_ORDERKEY, L_LINENUMBER ASC) );
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7909]: https://yugabyte.atlassian.net/browse/DB-7909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gauravk-in** [comment]
Assert was removed as part of another commit, and the issue cannot be reproduced anymore.
