### ISSUE TITLE
[Docs] 10% increase in latencies for aggregate(count) queries 

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#19112]
Jira Link: [DB-7919](https://yugabyte.atlassian.net/browse/DB-7919)
### Description

There is a 10% regression in the latencies for test in the AGGRG8_composite_key_impact.yaml, between YB builds 2.19.3.0-b79 to b87 :
AGGRG8_count_bigint_comp_pkey_withfilter_second_ele
AGGRG8_count_bigint_comp_pkey_project_first_ele_withfilter_sec_ele

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7919]: https://yugabyte.atlassian.net/browse/DB-7919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
2.19.3.0-b73 onwards had Mikhail’s changes with the memory leak, since that impacted Sysbench numbers, Now that the memory leak is fixed and the 10% spike doesn't seem to stick around, closing this issue for now. cc @bmatican
