### ISSUE TITLE
[DocDB][ActiveHistory] RPC call to fetch the AUH metadata from TServer

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#19139]
Jira Link: [DB-7937](https://yugabyte.atlassian.net/browse/DB-7937)
### Description

    - Create a TServer API so that PG can fetch AUH metadata from TServer
    - Allow collecting of Read/Write/CQL/Compaction

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7937]: https://yugabyte.atlassian.net/browse/DB-7937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Completed as part of #19143
