### ISSUE TITLE
[DocDB][ASH] Random number generator for AUH

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#19149]
Jira Link: [DB-7946](https://yugabyte.atlassian.net/browse/DB-7946)
### Description

Random number generator for AUH

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7946]: https://yugabyte.atlassian.net/browse/DB-7946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by abhinab-yb** [comment]
Not needed anymore
