### ISSUE TITLE
PgLibPqTest.MultiBankAccountSerializable frequently failing due to timeout

### ISSUE THREAD

**Issue by georgeklees** [yugabyte/yugabyte-db#1914]
Jira Link: [DB-2534](https://yugabyte.atlassian.net/browse/DB-2534)
Many of the Jenkins build tests have a failure for `PgLibPqTest.MultiBankAccountSerializable`, which looks like [this](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-debug/34/testReport/junit/(root)/PgLibPqTest/MultiBankAccountSerializable/):

```
## Error Message

../../src/yb/yql/pgwrapper/pg_libpq-test.cc:483 Failed Bad status: Timed out (yb/util/test_util.cc:281): Operation 'At least 5 reads and 1000 writes' didn't complete within 180001ms

## Stacktrace

Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-debug/34/artifact/build/debug-clang-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_libpq-test/PgLibPqTest_MultiBankAccountSerializable.log

../../src/yb/yql/pgwrapper/pg_libpq-test.cc:483
Failed
Bad status: Timed out (yb/util/test_util.cc:281): Operation 'At least 5 reads and 1000 writes' didn't complete within 180001ms
```

Copy of the log: https://gist.github.com/georgeklees/ee02ad266c02e7c088856869d79d4a06

This looks like it's due to timeout rather than any inconsistency, so it's not as worrying as it could be, but this should still be investigated.

**Comment by rthallamko3** [comment]
No longer repros in master branch - https://detective-gcp.dev.yugabyte.com/stability/?branch=master
