### ISSUE TITLE
[DocDB][ActiveHistory] Instrument Read/Write code paths

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#19143]
Jira Link: [DB-7941](https://yugabyte.atlassian.net/browse/DB-7941)
### Description

    - Instrument Consensus/RocksDB/YBClient

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7941]: https://yugabyte.atlassian.net/browse/DB-7941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Sysbench performance with and without enabling ash seems comparable to the baseline.
<img width="1262" alt="Screenshot 2023-12-20 at 8 27 58 AM" src="https://github.com/yugabyte/yugabyte-db/assets/32495790/20370c54-8cf7-40cc-8fbd-ad7668a2b7b3">

Comparing with baseline when ASH is disabled
<img width="1498" alt="Screenshot 2023-12-20 at 8 27 41 AM" src="https://github.com/yugabyte/yugabyte-db/assets/32495790/de6ba3f2-4079-4962-a761-c94167fe112a">


Comparing with baseline when ASH is enabled

<img width="1498" alt="Screenshot 2023-12-20 at 8 27 47 AM" src="https://github.com/yugabyte/yugabyte-db/assets/32495790/1153fb81-d7a5-4907-862e-d6c763f5ed6f">
