### ISSUE TITLE
[YSQL] Support for "select for"

### ISSUE THREAD

**Issue by rhzs** [yugabyte/yugabyte-db#1918]
Does Yugabyte provide "select for" grammar for YSQL? If not, any plan or release ETA?

I have looked at the docs, it doesn't seem support one

<img width="896" alt="Screen Shot 2019-07-27 at 11 52 30 PM" src="https://user-images.githubusercontent.com/5300674/61997294-af736080-b0c9-11e9-8616-b8f317486f11.png">

<img width="727" alt="Screen Shot 2019-07-27 at 11 56 12 PM" src="https://user-images.githubusercontent.com/5300674/61997328-2d376c00-b0ca-11e9-87b7-6bd1db9eb732.png">

While Postgres 11 is ...

<img width="1066" alt="Screen Shot 2019-07-27 at 11 53 55 PM" src="https://user-images.githubusercontent.com/5300674/61997311-e21d5900-b0c9-11e9-9e3a-b0f45e4c9127.png">

Thank you, you guys built amazing products!

----

EDIT 1: Add current (27/07/2019) yugabyte select support docs

**Comment by rkarthik007** [comment]
Thanks for the question @incubus8! `SELECT FOR` has a dependency on [#1199] `[YSQL] Support locking options in SELECT statement (SELECT FOR UPDATE etc.)`

@m-iancu or @ndeodhar would be the best folks to answer if there are any additional dependencies on top of the one above.

> Thank you, you guys built amazing products!
Glad you like it 🙏

**Comment by ndeodhar** [comment]
Hi @incubus8, glad to hear that you like YugaByte DB!
We're going to start working on locking options for `SELECT` soon and plan to do it in two phases:
1. Support `FOR SHARE` and `FOR KEY SHARE`: This should be available by end of August.
2. Support `FOR UPDATE` and `FOR NO KEY UPDATE`: This will most likely be 1-2 months after that.

Let me know if you have any feedback about the timeline and/or any use cases that are dependent on this.

**Comment by incubus8** [comment]
> Thanks for the question @incubus8! `SELECT FOR` has a dependency on [#1199] `[YSQL] Support locking options in SELECT statement (SELECT FOR UPDATE etc.)`
> 
> @m-iancu or @ndeodhar would be the best folks to answer if there are any additional dependencies on top of the one above.
> 
> > Thank you, you guys built amazing products!
> 
> Glad you like it 🙏

Sorry for double posting, I was searching the issue but I couldn't find it. 




> Hi @incubus8, glad to hear that you like YugaByte DB!
> We're going to start working on locking options for `SELECT` soon and plan to do it in two phases:
> 
> 1. Support `FOR SHARE` and `FOR KEY SHARE`: This should be available by end of August.
> 2. Support `FOR UPDATE` and `FOR NO KEY UPDATE`: This will most likely be 1-2 months after that.
> 
> Let me know if you have any feedback about the timeline and/or any use cases that are dependent on this.

Thank you so much @rkarthik007 @ndeodhar 

The use case will be using most of database migration tools, in which most of Java app use it.. 

For example:
https://github.com/flyway/flyway/blob/eb14b2d84f37a7396e30fbc4da285959ea50512c/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLTable.java#L60

**Comment by rkarthik007** [comment]
I believe most of this is done and now available in YugabyteDB, here is the GitHub issue that ended up tracking this: https://github.com/yugabyte/yugabyte-db/issues/1199

The docs are not yet updated. That is being tracked here: https://github.com/yugabyte/yugabyte-db/issues/2987

@jj-kim - could you please add any comments if needed and close the issue? Thanks!

**Comment by jj-kim** [comment]
Besides docs, this is done.  Additional details are in #1199.
