### ISSUE TITLE
Manual Deploy 3  physics node ，when run ysqlsh error

### ISSUE THREAD

**Issue by qinzl1** [YugaByte/yugabyte-db#1919]
./bin/ysqlsh -e -h xxx.xxx.xxx
ysqlsh: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

why this error happen ，how to solve it
how to restart the ysql api

**Comment by ndeodhar** [comment]
Hi @qinzl1, what version of YB are you using?
Did you have an older version of YB and then upgrade/install a newer version? We've had a backward incompatible change in our recent version for YSQL and the error you're seeing above is a typical symptom when you upgrade.

If this is a fresh install (and not an upgrade), then you can try this to debug:
1. Update postgresql.conf file located in `$data_dir/disk-1/pg_data/postgresql.conf` and add the line `log_statement='all'`. Please do this on the node you're connecting to with `ysqlsh`.
2. Restart tserver on that node
3. Run `./bin/ysqlsh` and check any errors in `$data_dir/disk-1/yb-data/tserver/logs/postgresql*.log`

**Comment by qinzl1** [comment]
@ndeodhar thanks for response
YB version is 1.3.0 , this my first install yb. 
log have no useful information
![image](https://user-images.githubusercontent.com/20242930/62021337-4f7bd780-b1f9-11e9-8229-9dba52dd86d4.png)

**Comment by ndeodhar** [comment]
@qinzl1 Can you try giving the full path for `tserver.conf` while starting yb-tserver?
After that, also make sure that YSQL is enabled by following these instructions:
https://docs.yugabyte.com/latest/deploy/manual-deployment/start-tservers/#initialize-ysql

Let me know if that works.

**Comment by qinzl1** [comment]
@ndeodhar ths
it works

**Comment by ndeodhar** [comment]
Glad to hear, thanks for confirming!

**Comment by qinzl1** [comment]
Hi  @ndeodhar 
Can official YCQL jdbc driver be provided
i find YSQL jdbc only，At this time YSQL is beta version

**Comment by qinzl1** [comment]
Hi  @ndeodhar 
Can official YCQL jdbc driver be provided
i find YSQL jdbc only，At this time YSQL is beta version

**Comment by schoudhury** [comment]
@qinzl1 YCQL has its own Java driver (but it is not based on JDBC). You can find the instructions here: https://docs.yugabyte.com/latest/quick-start/build-apps/java/ycql/

**Comment by qinzl1** [comment]
Hi @schoudhury 
I find that tables created by ycql and ysql are isolated from each other。Is any difference performance in tables between these two locations

**Comment by schoudhury** [comment]
@qinzl1 yes, the two APIs are completely independent of each other. Given that YCQL explicitly avoids multi-row operations (that can involve the network) such as foreign keys and JOINs, YCQL would generally be of higher performance than YSQL. YSQL is meant for fully relational apps where the developer would like to use YBDB as a massively-scalable, highly-available RDBMS. More here: https://docs.yugabyte.com/latest/introduction/#what-client-apis-are-supported-by-yugabyte-db

**Comment by qinzl1** [comment]
@schoudhury 
Hi， 
insert through ysql，i found the throughput not ideal，Each batch of 1000 rows takes 5 seconds
![image](https://user-images.githubusercontent.com/20242930/62510987-0d2f4780-b844-11e9-9545-6a210c3b5904.png)
