### ISSUE TITLE
[DocDB] flaky test: PgGetLockStatusTest.TestLocksOfColocatedTables

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#19197]
Jira Link: [DB-7994](https://yugabyte.atlassian.net/browse/DB-7994)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=false&branch=master&build_type=all&class=PgGetLockStatusTest&fail_tag=all&name=TestLocksOfColocatedTables&platform=linux

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7994]: https://yugabyte.atlassian.net/browse/DB-7994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
Observation: latest failures seem to be around table creation, and exclusively in release mode

**Comment by rthallamko3** [comment]
reactivating for 2.20 backport.
