### ISSUE TITLE
Turn follower reads off temporarily when a tserver joins the cluster and there is a valid leader

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#192]
A new tserver joining the cluster, or an old tserver being restarted after being kept down for a while, already has to accept remote bootstrap data and a lot of replication traffic to catch up. Also it is probably very out-of-date. So even if the app is fine with follower reads, a new tserver probably should not serve them for a while for tablets that it is still bootstrapping.

**Comment by hectorgcr** [comment]
We now have protection against this issue as long as `max_stale_read_bound_time_ms` is greater than 0 (default 60 seconds)
