### ISSUE TITLE
[YSQL] Invalid Argument: Unknown session reported for PostgreSQL connections

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#19218]
Jira Link: [DB-8014](https://yugabyte.atlassian.net/browse/DB-8014)
### Description

Few times following error has been observed for YB Cluster.

`Invalid Argument: Unknown session` 
In one specific scenario this happened after cluster has multiple  OOM's. 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8014]: https://yugabyte.atlassian.net/browse/DB-8014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jameshartig** [comment]
Can the "Unknown session" be a Postgres fatal severity error? Then drivers (like pgx) will automatically close the connection. Otherwise the connection essentially unusable and the caller has to check for this specific error everywhere and know to close the connection.

**Comment by jasonyb** [comment]
> Can the "Unknown session" be a Postgres fatal severity error?

I don't see this message in postgres code, and it seems to be understood already according to https://github.com/yugabyte/yugabyte-db/issues/16445#issuecomment-1487721547.

```
$ git grep 'Unknown session' src/postgres
$ git grep 'Unknown session' src/yb
src/yb/tserver/pg_client_service.cc:1328:    SCHECK(it != sessions_.end(), InvalidArgument, "Unknown session: $0", session_id);
```

**Comment by jameshartig** [comment]
@jasonyb I meant when the error eventually gets sent over the wire can the Severity level be set to `FATAL`. See the Error Message fields: https://www.postgresql.org/docs/current/protocol-error-fields.html. Currently the Severity field is being set to `ERROR`. If the severity was correctly set to FATAL (since there's no way for the client to recover) then the Yugabyte Go driver would close the connection automatically https://github.com/jackc/pgconn/blob/e82f7d1fadf5970c308d0502d196783e72467178/pgconn.go#L573.

**Comment by karthik-ramanathan-3006** [comment]
@jameshartig - I'm currently working on a change to do precisely this: changing the severity of the "Unknown Session" error from `ERROR` to `FATAL` so that the driver can terminate what is already a dead connection.

**Comment by jameshartig** [comment]
@karthik-ramanathan-3006 I saw it was just closed. Can you clarify what's happening with this? Are you still working on making it fatal?

**Comment by jasonyb** [comment]
@jameshartig, I don't know what that is, but the work is likely still ongoing.

**Comment by karthik-ramanathan-3006** [comment]
@jameshartig - I'm still working on this one. Internally, we marked this issue as a duplicate of an older issue (#16445).
I imagine that the tracker has a policy of closing the ones marked as a duplicate. Sorry about the confusion.
