### ISSUE TITLE
[docdb] Support for large treansactions

### ISSUE THREAD

**Issue by JDNdeveloper** [yugabyte/yugabyte-db#1923]
Currently large transactional writes are handled the same as small transactional writes. Each operation in the transactional write path blocks the Raft log for the involved tablet, which means that a very long operation (like applying 1GB of write intents) will block the tablet for the duration of the operation. Another problem is that the memory used by each operation is unbounded, which could lead to OOM for large write transactions.

We currently use large distributed writes for the YSQL `COPY` command.

This issue tracks breaking applying of large transactional writes into smaller apply batches to minimize the blocking time and allow for progress of other operations that involve the Raft log, and also to minimize the maximum memory size used by a large write transaction to avoid OOM issues. This will require a change to the frontier checkpointing mechanism to support partially applied intents, as well as changes to Raft update processing to apply pending intents when idle.

**Comment by JDNdeveloper** [comment]
Wanted to add we also have an unbounded memory usage issue on the Postgres side (for both transactional and non-transactional COPY): #2303 .

**Comment by mbautin** [comment]
Perhaps we could explore an alternative mechanism to support large transactions. Once we determine that a transaction is about to load a lot of data, maybe we could create a separate RocksDB for that transaction alone, with a slightly different key format (no timestamps at the end of keys), and modify the read path to query those special "large transaction" RocksDB instances instead. The "apply" operation for the committed transaction would then install SSTable files from this separate per-transaction RocksDB into the main RocksDB of the tablet with a special metadata (manifest) record that includes the commit timestamp and destroy the per-transaction RocksDB database. This would solve both the issue described above, and will solve the write amplification part of large transactions.

Cc @bmatican @spolitov
