### ISSUE TITLE
[YSQL] [FORMAT CHANGE] Use string storage for TEXT data type

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1924]
Currently, we store TEXT data type as binary. From `ybctype.c`:
```
{ TEXTOID, YB_YQL_DATA_TYPE_BINARY, true, -1,                                                
                (YBCPgDatumToData)YBCDatumToBinary,                                                  
                (YBCPgDatumFromData)YBCBinaryToDatum }
```
We should change this to string to be compatible with postgres.

**Comment by nocaway** [comment]
This has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/e10a60583ce49205e932d888e45494bf059168d9

**Comment by nocaway** [comment]
The fix in https://github.com/YugaByte/yugabyte-db/commit/e10a60583ce49205e932d888e45494bf059168d9 only fixed one of scenarios.  There are other scenarios that should must be worked out also.

**Comment by nocaway** [comment]
This has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/4d2f2f97fa46da5bd1e4a42e29b92f079d767fb8
