### ISSUE TITLE
[YSQL][xCluster] Alter table with add colum, Default value NOW() shows discrepancy in data in xcluster setup

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#19259]
Jira Link: [DB-8055](https://yugabyte.atlassian.net/browse/DB-8055)
### Description

Version: observed on master
Observed a discrepancy in the values of the generated_at column between the source and target databases. The value at the source side is different from the value at the target side.

### Steps:

1. Create table at both source 
`CREATE TABLE tab(id int, name text)`
2. Restore database at target
3.  Setup replication
4. ALTER table with default value at source
`ALTER TABLE tab ADD COLUMN generated_at timestamp DEFAULT NOW()`
5. Load data to table tab at source (REPLICATION is paused)
6.  ALTER table with default value at Target
`ALTER TABLE tab ADD COLUMN generated_at timestamp DEFAULT NOW()`
7. Wait for few mins data to replicate

**Issue**: Value of  generated_at column at source is different from value at Target
QA: automation added to test TestYSQLXClusterWithColocation (unmute after issue is resolved)
cc: @kripasreenivasan 
### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8055]: https://yugabyte.atlassian.net/browse/DB-8055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by fizaaluthra** [comment]
This is expected behaviour as the value of `NOW()` will be different on the target. User would have to execute the `ADD COLUMN ... DEFAULT` command with the computed default.
Added a note in xCluster docs in commit 24323a9d5b059d16db86bdca98f6ed131f38cf6e
