### ISSUE TITLE
[docs] Review and update manual deployment docs for YSQL

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1925]
A couple of users have noted that our manual deployment instructions (https://docs.yugabyte.com/latest/deploy/manual-deployment/start-tservers/) don't work as expected and they see an error like below while connecting to `ysqlsh`:
```
ysqlsh: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```

One reason seems to be `tserver.conf` file not found (this error gets logged in postgres log). We should review these instructions and update them as needed.

**Comment by ddorian** [comment]
Closing as cannot replicate. This is an old issue, and I haven't seen anything like this in the past several months in the community.
