### ISSUE TITLE
[DocDB] Probable leak of ConflictResolver object blocks transaction participant shutdown

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#19272]
Jira Link: [DB-8065](https://yugabyte.atlassian.net/browse/DB-8065)
### Description

As part of conflict resolution, we either create `WaitOnConflictResolver` or `FailOnConflictResolver` based on the set conflict management policy, both of which extend `ConflictResolver`. `ConflictResolver` stores a `request_scope_` which is set in the initial phase on conflict resolution and gets reset either when the request enters the wait-queue or when the `ConflictResolver` object gets destroyed. 

For wait-on-conflict scenario, the `request_scope_` is reset before entering the wait-queue, and we obtain another request id when the waiter is resumed from the wait-queue. The wait-queue holds shared_ptrs to the `ConflictResolver` callback at a couple of places. 

It seems like there is some leak of `ConflictResolver` objects. The participant shutdown gets blocked waiting for `running_requests_` to be empty, and the clean-up for one of the request ids held in a `ConflictResolver` never arrives. 

Steps to repro the issue. 
- Checkout `7530ac04e734cd8d354ffd2e5326d41fd9655509`
- set `ysql_client_read_write_timeout_ms` to 120000.
- ./yb_build.sh release --java-test org.yb.pgsql.TestPgTransparentRestarts#selectCountPrepared -n 50 --tp 1 -- -k

Can see that few of the runs take > 2 mins because the delete table operation times out. One simple way to fix this is to explicitly reset the request scope after the underlying write query's callback is executed. But we should take a look why the `ConflictResolver` object isn't being destroyed at the first place.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8065]: https://yugabyte.atlassian.net/browse/DB-8065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mbautin** [comment]
Could there be a shared_ptr cycle here? A lot of these issues could be fixed by changing one of the shared_ptr to weak_ptr to break the cycle.
