### ISSUE TITLE
Document PostgreSQL tools that YSQL works with

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#1928]
Jira Link: [DB-2125](https://yugabyte.atlassian.net/browse/DB-2125)
YSQL already works with a number of PostgreSQL compatible tools, these should be added to the [tools page in our docs](https://docs.yugabyte.com/latest/tools/).

Here are some tools that are currently supported but not documented:

## psql
YugaByte DB works well with `psql` which is the default shell. In fact, `ysqlsh` is a derivative of `psql`. Here is a handy guide: http://postgresguide.com/utilities/psql.html

## DBeaver:
DBeaver is a free multi-platform database management tool for developers, SQL programmers, DBA’s and analysts. Here is a blog about working with it: https://blog.yugabyte.com/getting-started-with-dbeaver-on-a-distributed-sql-database/

**Comment by stevebang** [comment]
@rkarthik007 @schoudhury 

Close? 

- DBeaver is documented in the "Third party tools" section.
- Do we still want to document `psql`?
  - If yes, then add to "Third party tools"? Short page pointing out that it can be used, limitations (if any), and pointer to the PostgreSQL docs for it?

**Comment by schoudhury** [comment]
@stevebang yes the above plan works for `psql`
