### ISSUE TITLE
Document the various standard datasets that work with YSQL

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#1929]
Let's add "Sample Datasets" section in either the `Reference` section of the docs or under `Reference -> Tools` (or some other appropriate location). Here are some datasets we support along with instructions on how to use them:
* [Northwind](https://github.com/YugaByte/yugabyte-db/wiki/Northwind-Sample-Database)
* [Club data](https://github.com/YugaByte/yugabyte-db/wiki/PGExercises)
* [Sports DB](https://github.com/YugaByte/yugabyte-db/wiki/SportsDB-Sample-Database)

The sample datasets are located in the [sample directory of the codebase](https://github.com/YugaByte/yugabyte-db/tree/master/sample).

**Comment by stevebang** [comment]
Looked at the current structure — I'll add the content to the Tools section for now (renaming the page to "Tools and resources").  

@jguerreroyb I'll also plan on adding the Chinook SQL scripts to this section when ready.

**Comment by rkarthik007** [comment]
Chinook has landed, find the data files here: https://github.com/YugaByte/yugabyte-db/tree/master/sample

**Comment by stevebang** [comment]
Closing -- all of the sample databases have been doc'ed.
