### ISSUE TITLE
[xCluster][Unit Test] Flaky unit test XClusterYSqlTestConsistentTransactionsTest.UnevenTxnStatusTablets

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#19302]
Jira Link: [DB-8111](https://yugabyte.atlassian.net/browse/DB-8111)
### Description

Test XClusterYSqlTestConsistentTransactionsTest.UnevenTxnStatusTablets failing with error accross the builds
```
Execute of 'delete from test_table_0;' failed: 7, message: ERROR:  Tablet 91f16c90239b4fb7851aeb9506172b4e not running: . Errors from tablet servers: [Service unavailable (yb/master/catalog_manager.cc:11734): Tablet 91f16c90239b4fb7851aeb9506172b4e not running] (pgsql error XX000) (aux msg ERROR:  Tablet 91f16c90239b4fb7851aeb9506172b4e not running: . Errors from tablet servers: [Service unavailable (yb/master/catalog_manager.cc:11734): Tablet 91f16c90239b4fb7851aeb9506172b4e not running])
```

Test failure stack trace:
```

${BUILD_ROOT}/../../src/yb/integration-tests/xcluster/xcluster_ysql-test.cc:1550:     @     0x5605156b039d  yb::XClusterYSqlTestConsistentTransactionsTest_UnevenTxnStatusTablets_Test::TestBody()
I0926 04:52:37.071481  6914 xcluster_test_base.cc:109] Destroying CDC Clusters
2023-09-26 04:52:37.071 UTC [7763] LOG:  received fast shutdown request
2023-09-26 04:52:37.089 UTC [7763] LOG:  aborting any active transactions
2023-09-26 04:52:37.089 UTC [7777] FATAL:  terminating background worker "YSQL webserver" due to administrator command
2023-09-26 04:52:37.094 UTC [7763] LOG:  background worker "YSQL webserver" (PID 7777) exited with exit code 1
2023-09-26 04:52:37.095 UTC [7780] LOG:  shutting down
2023-09-26 04:52:37.144 UTC [7763] LOG:  database system is shut down
[C] I0926 04:52:37.148180  7764 process_wrapper.cc:67] PostgreSQL exited normally
[C-ts-1] I0926 04:52:37.151134  6914 tablet_server.cc:673] TabletServer shutting down...
```
Stability: [https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=XClusterYSqlTestConsistentTransactionsTest&name=UnevenTxnStatusTablets](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=XClusterYSqlTestConsistentTransactionsTest&name=UnevenTxnStatusTablets)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8111]: https://yugabyte.atlassian.net/browse/DB-8111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Test was not waiting for tablet to be ready before performing write ysql statements.

This test is not needed since we no longer replicate transactions table in xcluster and will be removed.
