### ISSUE TITLE
New yb-admin command to set the wal retention time of a table

### ISSUE THREAD

**Issue by hectorgcr** [yugabyte/yugabyte-db#1931]
We need a way to manually set the wal retention time of a specific table through yb-admin

**Comment by SteveXiSong** [comment]
Per discussion with Nicolas, this is a user interface to update the WAL retention time and collect the following information.

1. The first straightforward task is to add it to our yb-admin, which will be used by xCluster project by March. (The backend API has been implemented. )
2. To make it fully compatible with PG (give a PG user-friendly interface), we may need to study how PG does such operations similarly and implement our user interface in ysqlsh to update metadata like this. Metadata may include:

    * WAL retention time
    * TTL / expiration properties cc @John Meehan
    * tablet splitting properties cc @timur
    * generic rocksdb properties (as we add more / explore existing ones) cc @Raghavendra T.K.
    * HRT had some asks for per-table qos / rate limiting

    We can also confirm the PG user interface with @Franck Pachot.
This is a little more ambiguous task and needs some time to research. I will create another issue to track this once the use case is confirmed.

3. Besides ysql, we might also need user interfaces in ycql as completeness. This will also be tracked in another issue.

Reference discussion in slack: https://yugabyte.slack.com/archives/C027M2T0W8Z/p1641254306045600

**Comment by SteveXiSong** [comment]
Close this issue as Item 1 is finished. For items 2 and 3, this is a long-term discussion and we don't have a clear vision so far.
