### ISSUE TITLE
[YSQL] SQLSTATE[XX000] ERROR:  Attempted to restart when session does not require restart

### ISSUE THREAD

**Issue by WhiteWind** [yugabyte/yugabyte-db#19332]
Jira Link: [DB-8135](https://yugabyte.atlassian.net/browse/DB-8135)
### Description

Sometimes pretty usual query fails with this error. Most of the time query runs normally. 
tserver and master logs doesn't print anything, postgresql log prints the same:

`2023-09-27 20:01:03.985 UTC [1709500] ERROR:  Attempted to restart when session does not require restart`

yugabyte_version: "2.18.1.0"
yugabyte_build: "b84"

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8135]: https://yugabyte.atlassian.net/browse/DB-8135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Seems like #12071. Can we close this as duplicate and reply there?
