### ISSUE TITLE
test yugabyteDB with workload 'SqlInserts' by yb-sample-apps,there are some errors.

### ISSUE THREAD

**Issue by halleyshx** [YugaByte/yugabyte-db#1933]
I run the test command `nohup java -jar yb-sample-apps.jar --workload SqlInserts --nodes 10.xxx.xxx.2:5433,10.xxx.xxx.8:5433,10.xxx.xxx.9:5433 --nouuid --num_unique_keys 50000000 --num_writes 50000000 --num_threads_write 356 --num_threads_read 0 2>&1 | tee /export/App/yb-sample-apps/result/pure-inserts-yb.log &`, there are some errors like this:

> Jul 29, 2019 6:09:08 PM **org.postgresql.core.v3.ConnectionFactoryImpl log
> WARNING: SQLException occurred while connecting to 10.xxx.xxx.2:5433
> org.postgresql.util.PSQLException: FATAL: Timed out: Read RPC to 10.xxx.xxx.8:7100 timed out after 0.114s**
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
>         at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
>         at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
>         at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
>         at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
>         at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
>         at org.postgresql.Driver.makeConnection(Driver.java:452)
>         at org.postgresql.Driver.connect(Driver.java:254)
>         at java.sql.DriverManager.getConnection(DriverManager.java:664)
>         at java.sql.DriverManager.getConnection(DriverManager.java:208)
>         at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
>         at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
>         at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
>         at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
>         at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
>         at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> Jul 29, 2019 6:09:08 PM **org.postgresql.Driver connect
> SEVERE: Connection error:
> org.postgresql.util.PSQLException: FATAL: Timed out: Read RPC to 10.xxx.xxx.8:7100 timed out after 2.401s**
> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
> at org.postgresql.core.v3.QueryExecutorImpl.(QueryExecutorImpl.java:131)
> at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
> at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> at org.postgresql.jdbc.PgConnection.(PgConnection.java:195)
> at org.postgresql.Driver.makeConnection(Driver.java:452)
> at org.postgresql.Driver.connect(Driver.java:254)
> at java.sql.DriverManager.getConnection(DriverManager.java:664)
> at java.sql.DriverManager.getConnection(DriverManager.java:208)
> at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> 
> 289840 [Thread-135] FATAL **com.yugabyte.sample.apps.SqlInserts - Failed writing key: key:732
> org.postgresql.util.PSQLException: FATAL: Timed out: Read RPC to 10.xxx.xxx.8:7100 timed out after 2.401s**
> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
> at org.postgresql.core.v3.QueryExecutorImpl.(QueryExecutorImpl.java:131)
> at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
> at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> at org.postgresql.jdbc.PgConnection.(PgConnection.java:195)
> at org.postgresql.Driver.makeConnection(Driver.java:452)
> at org.postgresql.Driver.connect(Driver.java:254)
> at java.sql.DriverManager.getConnection(DriverManager.java:664)
> at java.sql.DriverManager.getConnection(DriverManager.java:208)
> at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> Jul 29, 2019 6:09:09 PM **org.postgresql.core.v3.ConnectionFactoryImpl log
> WARNING: SQLException occurred while connecting to 10.xxx.xxx.8:5433
> org.postgresql.util.PSQLException: FATAL: Timed out: Read(tablet: 00000000000000000000000000000000, num_ops: 1, num_attempts: 76, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 55295441.703s (passed: 59.899s): Illegal state (yb/master/scoped_leader_shared_lock.cc:76): Not the leader. Local UUID: 7da68350e45b413a9479e8f8f98a49e2, Consensus state: current_term: 1 leader_uuid: "45f57795ef0547e49595ceb2879fb8c6" config { opid_index: -1 peers { permanent_uuid: "7da68350e45b413a9479e8f8f98a49e2" member_type: VOTER last_known_private_addr { host: "10.xxx.xxx.2" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "45f57795ef0547e49595ceb2879fb8c6" member_type: VOTER last_known_private_addr { host: "10.xxx.xxx.8" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "048ae2842da749b6b798726e3587aea0" member_type: VOTER last_known_private_addr { host: "10.xxx.xxx.9" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }**
> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
> at org.postgresql.core.v3.QueryExecutorImpl.(QueryExecutorImpl.java:131)
> at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
> at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> at org.postgresql.jdbc.PgConnection.(PgConnection.java:195)
> at org.postgresql.Driver.makeConnection(Driver.java:452)
> at org.postgresql.Driver.connect(Driver.java:254)
> at java.sql.DriverManager.getConnection(DriverManager.java:664)
> at java.sql.DriverManager.getConnection(DriverManager.java:208)
> at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)

**Comment by d-uspenskiy** [comment]
@halleyshx  Could you please provide the output of `yb-ctl start` command.
It must be something like this
```
==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : debug
C/C++ compiler                   : gcc
Build directory                  : /home/duspensky/code/yugabyte-db/build/debug-gcc-dynamic-ninja
Third-party dir                  : /home/duspensky/code/yugabyte-db/thirdparty
Targets                          : yb-master yb-tserver postgres yb-admin initial_sys_catalog_snapshot
C++ compilation time             : 161 seconds
------------------------------------------------------------------------------------------
```

If you have `debug` build please retry your workload on `release`

**Comment by halleyshx** [comment]
@d-uspenskiy I run the `yb-ctl start` command and the returns are different of yours.

> \# ./yb-ctl start
> Creating cluster.
> Waiting for cluster to be ready.
> ----------------------------------------------------------------------------------------------------
> | Node Count: 1 | Replication Factor: 1                                                            |
> ----------------------------------------------------------------------------------------------------
> | JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
> | YSQL Shell          : ysqlsh                                                                     |
> | YCQL Shell          : cqlsh                                                                      |
> | YEDIS Shell         : redis-cli                                                                  |
> | Web UI              : http://127.0.0.1:7000/                                                     |
> | Cluster Data        : /root/yugabyte-data                                                        |
> ----------------------------------------------------------------------------------------------------
> 
> For more info, please use: yb-ctl status
> [root@d bin]# ./yb-ctl status
> ----------------------------------------------------------------------------------------------------
> | Node Count: 1 | Replication Factor: 1                                                            |
> ----------------------------------------------------------------------------------------------------
> | JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
> | YSQL Shell          : ysqlsh                                                                     |
> | YCQL Shell          : cqlsh                                                                      |
> | YEDIS Shell         : redis-cli                                                                  |
> | Web UI              : http://127.0.0.1:7000/                                                     |
> | Cluster Data        : /root/yugabyte-data                                                        |
> ----------------------------------------------------------------------------------------------------
> ----------------------------------------------------------------------------------------------------
> | Node 1: yb-tserver (pid 97088), yb-master (pid 97085)                                            |
> ----------------------------------------------------------------------------------------------------
> | JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
> | YSQL Shell          : ysqlsh                                                                     |
> | YCQL Shell          : cqlsh                                                                      |
> | YEDIS Shell         : redis-cli                                                                  |
> | data-dir[0]         : /root/yugabyte-data/node-1/disk-1/yb-data                                  |
> | yb-tserver Logs     : /root/yugabyte-data/node-1/disk-1/yb-data/tserver/logs                     |
> | yb-master Logs      : /root/yugabyte-data/node-1/disk-1/yb-data/master/logs                      |
> ----------------------------------------------------------------------------------------------------

My yugabyteDB was downloaded with the command `wget https://downloads.yugabyte.com/yugabyte-1.3.0.0-linux.tar.gz`,I haven't build the program.

**Comment by halleyshx** [comment]
That's why? I run the command in a new docker.
```
# ./yb-ctl start
Starting cluster with base directory /root/yugabyte-data
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "./yb-ctl", line 1797, in <module>
    control.run()
  File "./yb-ctl", line 1770, in run
    self.args.func()
  File "./yb-ctl", line 1579, in start_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./yb-ctl", line 1404, in wait_for_cluster_or_raise
    if not self.wait_for_cluster():
  File "./yb-ctl", line 1350, in wait_for_cluster
    raise ValueError("Cannot wait for cluster without knowing master addresses")
ValueError: Cannot wait for cluster without knowing master addresses
^^^ Encountered errors ^^^
```

**Comment by rkarthik007** [comment]
Hi @halleyshx,

A few questions:
* Are you doing a single node install or a multi-node install?
* Can you post the screenshot of the web ui http://127.0.0.1:7000

It feels like the cluster did not startup properly.

**Comment by d-uspenskiy** [comment]
@halleyshx Could you please describe a little PC configuration where you start YB cluster? Number of CPU, RAM, SSD or HDD, is it virtual host or physical etc.

**Comment by d-uspenskiy** [comment]
Hello @halleyshx 
Have you solved the issue by your own?
Or problem is still present on your setup?

**Comment by d-uspenskiy** [comment]
@halleyshx please re-open issue if you still have a problem and update logs and scenario
