### ISSUE TITLE
[DocDB] Select rows count inconsistency after bulk load

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#19359]
Jira Link: [DB-8159](https://yugabyte.atlassian.net/browse/DB-8159)
### Description

We can have inconsistency in selecting rows count in debug build in the following scenario:
```
./bin/yb-ctl start
./bin/ysqlsh -c "CREATE DATABASE db WITH colocation = true;"
./bin/ysqlsh -d db -f ~/code/tpch-dbgen/yugabyte_colocated.ddl

./bin/ysqlsh -d db -c "select count(*) from lineitem;"

./bin/yb-ctl restart

./bin/ysqlsh -d db -c "select count(*) from lineitem;"
```

`select count(*)` sometimes returns less rows after restart. We were only able to reproduce this in debug build and this is reproducible on master branch (commit 710d94d005d92baa449c4af7f1ba8488f8003e91). 

Content of `yugabyte_colocated.ddl` is just creating some tables and using `\copy` command to load data into these tables from files.

I’ve did some investigation and was able to reduce the dataset reproducing scenario, so load only takes ~15 minutes instead of original ~3 hours. Also I confirmed that missing rows are present in WAL files even after restart, but they absent in RocksDB SST files even before restart.

Looks like the issue is related to replay of applying of intents/distributed transactions during local tablet bootstrap.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8159]: https://yugabyte.atlassian.net/browse/DB-8159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Removing 2.16 backport label as it is out of support.

**Comment by rthallamko3** [comment]
2.20 backport has landed. closing the issue.
