### ISSUE TITLE
[YSQL] Creating a temp index with tablespace should not be allowed

### ISSUE THREAD

**Issue by kai-franz** [yugabyte/yugabyte-db#19368]
Jira Link: [DB-8167](https://yugabyte.atlassian.net/browse/DB-8167)
### Description

Temporary indexes (created by creating an index on a temp table) are not backed by DocDB storage, so specifying a tablespace for them is not meaningful.

Currently, creating a temporary index with tablespace results in a confusing error message:
```
yugabyte=# CREATE TABLESPACE regress_tblspace LOCATION '/data';
yugabyte=# CREATE TEMPORARY TABLE temptest (a INT);
yugabyte=# CREATE INDEX temp_idx_tblspc ON temptest(a) TABLESPACE regress_tblspace;
ERROR:  could not create directory "pg_tblspc/16384/PG_11_201809051/13301": No such file or directory
```

Attempting to drop the tablespace after this causes the client to hang:
```
yugabyte=# DROP TABLESPACE regress_tblspace;
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8167]: https://yugabyte.atlassian.net/browse/DB-8167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment]
Fixed
