### ISSUE TITLE
[YSQL] T-server catalog cache serves stale version of pg_database

### ISSUE THREAD

**Issue by kai-franz** [yugabyte/yugabyte-db#19363]
Jira Link: [DB-8163](https://yugabyte.atlassian.net/browse/DB-8163)
### Description

When a Postgres backend starts, it prefetches these 3 shared tables:
```	
        YbRegisterTable(prefetcher, YB_PFETCH_TABLE_PG_AUTH_MEMBERS);
	YbRegisterTable(prefetcher, YB_PFETCH_TABLE_PG_DATABASE);
	YbRegisterTable(prefetcher, YB_PFETCH_TABLE_PG_DB_ROLE_SETTINGS);
```

When the T-server cache is enabled, this request is cached there. When another backend process starts up, it will issue the same prefetch request, which will result in a hit in the T-server cache (assuming the catalog version has not changed). 

This becomes a problem in the following scenario:
1. Backend 1 is started and it connects to database `db1`. 
2. Backend 1 prefetches the above shared tables. This request is cached in the T-server cache.
3. Backend 1 executes `CREATE DATABASE db2`, which does not increment the catalog version.
4. Backend 2 is started and it connects to database `db2`.
5. Backend 2 prefetches the shared tables, hitting the T-server cache. Since the cached request was made before `db2` was created, backend 2 now has a stale version of pg_database.
6. Backend 2 tries to `CheckMyDatabase` and fails, because it does not see `db2` in the pg_database table.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8163]: https://yugabyte.atlassian.net/browse/DB-8163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment]
Fixed
