### ISSUE TITLE
[YSQL][MV] Restart read on create/refresh materialized view under load

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#19400]
Jira Link: [DB-8193](https://yugabyte.atlassian.net/browse/DB-8193)
### Description

Steps:
1. Start sample-apps workload against 50 tables (test_1, test_2,...test_50)
2. Stop workload
3. Create materialized view `create materialized view mv_1 AS SELECT * FROM test_1` for all tables `mv_1`, `mv_2`, `mv_3` ... `mv_50`
4. Continue workload against same 50 tables
5. wait for 1 minute and refresh views `refresh materialized view mv_1` and it throw this error
```
com.yugabyte.util.PSQLException: ERROR: Restart read required at: { read: { physical: 1696370754799290 } local_limit: { physical: 1696370754799290 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```

Commands:
Run workload:
```bash
java  -jar yb-stress-sample-apps-1.1.23.jar --workload SqlDataLoad  --num_writes -1 --num_reads -1 --num_threads_write 10 --num_threads_read 10 --num_unique_keys 999999999 --num_tables 50 --use_datatypes true --num_value_columns 30 --create_table_name test --uuid 3f90fda7-9b50-4e91-b98a-fcdaa5506c16 --uuid_marker 9a3d6dac-86c1-45d0-906d-b735a494e96e  --nodes
```
Continue workload:
```bash
java  -jar yb-stress-sample-apps-1.1.23.jar --workload SqlDataLoad  --num_writes -1 --num_reads -1 --num_threads_write 10 --num_threads_read 10 --num_unique_keys 999999999 --num_tables 50 --use_datatypes true --num_value_columns 30 --create_table_name test --uuid 9cceac5e-05e7-4d76-b948-3379f19042c8 --skip_ddl --uuid_marker db75c5c4-a93f-482e-8e9a-fcdd38dc90cc  --nodes
```

Links:
https://github.com/yugabyte/yb-stress-test/releases/download/ssa_1.1.24-con-b1/yb-stress-sample-apps-1.1.24-con-b1.jar - have a pool of connections that reuses each query
https://github.com/yugabyte/yb-stress-test/releases/download/ssa_1.1.23/yb-stress-sample-apps-1.1.23.jar - each query creates new connection
All logs (universe logs, workload logs, framework logs) in attachments

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8193]: https://yugabyte.atlassian.net/browse/DB-8193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment]
Observed this issue again on Oct 6th with the test_mat_views_loading on 2.16

**Comment by kripasreenivasan** [comment]
Failed in 2.20 with the same error- http://stress.dev.yugabyte.com/stress_test/18e0fa91-3767-4cd1-973f-9036e2342c3e

**Comment by kripasreenivasan** [comment]
Failed in 2.21 with the same error- http://stress.dev.yugabyte.com/stress_test/4a3716a3-993b-487e-8ac1-428a6d94e4f6

**Comment by kripasreenivasan** [comment]
Failed in 2.21.0.0-b42 with the same error- http://stress.dev.yugabyte.com/stress_report/smoke%20core%20master;page=2.21.0.0-b42

**Comment by kripasreenivasan** [comment]
Failed in 2.18.4 with the same error- http://stress.dev.yugabyte.com/stress_test/e7779cdd-628d-4089-ad6c-db692508d6a4
