### ISSUE TITLE
[yugabyted] Provide support for setting preferred regions using yugabyted CLI

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#19415]
Jira Link: [DB-8206](https://yugabyte.atlassian.net/browse/DB-8206)
### Description

Leader pinning allows users to assign AZsa preference orders to have low latencies for their apps. Tablet leaders are placed in alive and healthy nodes of AZs in order of preference. 

### CLI 

- Yugabyted CLI should provide an easy and intuitive way of setting preferred regions in a YugabyteDB Cluster
- CLI should provide support for applying a new preference order and also support modifying an existing preference order

### UI

- Nodes page of the Yugabyted UI should display the order of preference for AZs
- show a cluster-wide activity after a successful application of the preference order on the cluster

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8206]: https://yugabyte.atlassian.net/browse/DB-8206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ShikharSahay** [comment]
Code changes landed.
