### ISSUE TITLE
[DocDB] Support tracing UpdateConsensus calls

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#19417]
Jira Link: [DB-8207](https://yugabyte.atlassian.net/browse/DB-8207)
### Description

Support tracing UpdateConsensus calls

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8207]: https://yugabyte.atlassian.net/browse/DB-8207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Consider backporting all the way to 2.14 after a weeks worth of bake time.
