### ISSUE TITLE
[CDCSDK] Avoid updating WAL retention of table if it is already large enough

### ISSUE THREAD

**Issue by dr0pdb** [yugabyte/yugabyte-db#19429]
Jira Link: [DB-8223](https://yugabyte.atlassian.net/browse/DB-8223)
### Description

Upon a CDC stream creation (both xCluster and CDCSDK), we issue an AlterTable call to update its WAL retention time.

We can skip doing that if the WAL retention time of the table is already high enough.

Note that there are xCluster tests which assume that there will always be an AlterTable, so those tests would also need to be updated according. Example - `CDCServiceTestDurableMinReplicatedIndex.TestBootstrapProducer`.

### Source connector version

NA

### Connector configuration

NA

### YugabyteDB version

NA

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8223]: https://yugabyte.atlassian.net/browse/DB-8223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dr0pdb** [comment]
@hari90 Lets only do this for xCluster and not for CDCSDK. We plan on performing other steps as part of AlterTable for consistent snapshot, so we must always make the AlterTable.

cc: @asrinivasanyb

**Comment by hari90** [comment]
Fixed in https://github.com/yugabyte/yugabyte-db/commit/2d742eb1582713af67319ce8e9688f14abc69f74
