### ISSUE TITLE
[YSQL] About ybctid

### ISSUE THREAD

**Issue by suppersam1** [yugabyte/yugabyte-db#19439]
Jira Link: [DB-8231](https://yugabyte.atlassian.net/browse/DB-8231)
### Description

Hi, I want to know if there is a maximum length for ybctid? What is the composition of ybctid and is it consistent in efficiency with querying with index fields.

### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8231]: https://yugabyte.atlassian.net/browse/DB-8231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
> I want to know if there is a maximum length for ybctid?

`ybctid` is used to lookup the original row. What do you mean by max length? Meaning, in what scenario?

> What is the composition of ybctid

It should be the primary-keys.

> is it consistent in efficiency with querying with index fields.

Can you be more explicit about comparing these two?

**Comment by suppersam1** [comment]
>> `ybctid` is used to lookup the original row. What do you mean by max length? Meaning, in what scenario?
> I found that ybctid is a variable length string when trying to develop plugins, so I want to know if it has the longest length so that it can be conveniently stored using char [YBCTIDMAXLENG].

>> It should be the primary-keys.
> Can you elaborate on it in more detail, because when I looked at the code, I found that it is composed of hashkey+rangekey, which seems to be the encoding of the dockey? What is the composition of ybctid when a table does not have a primary key？

>> Can you be more explicit about comparing these two?
> Ybctid is a tid used to replace pg. The tid of pg is the physical position of the row, so using tid to query rows can be very fast. Therefore, I would like to know if ybctid can have the efficiency of tid. According to your description above, using ybctid is equivalent to querying with a primary key?

**Comment by ddorian** [comment]
> What is the composition of ybctid when a table does not have a primary key？

A table ALWAYS has a primary key. When you don't define one, a hidden one is created by the db and used.

> According to your description above, using ybctid is equivalent to querying with a primary key?

They should be the same thing. `hashkey+rangekey` should be the whole primary key. 

cc @sushantrmishra

**Comment by ddorian** [comment]
> According to your description above, using ybctid is equivalent to querying with a primary key?

See this issue as example https://github.com/yugabyte/yugabyte-db/issues/3574. ytctid should have the primary-key-values inside.

**Comment by suppersam1** [comment]
Ty. I have solved my doubts.

**Comment by ddorian** [comment]
> when trying to develop plugins

Feel free to ask any questions about the plugin you're working on.

I am closing this as fixed.
