### ISSUE TITLE
[docdb] Leader step down in RF2 succeeds but new leader fails to replicate op

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1945]
Jira Link: [DB-1830](https://yugabyte.atlassian.net/browse/DB-1830)
When trying to step down the leader of a tablet down to 2 replicas (so essentially RF2), actively taking traffic, we were seeing essentially the vote succeeding and the new leader getting elected, however when replicating it's noop, the old leader would report:
```
Log matching property violated. Preceding OpId in replica: term X, op id Y+1. Preceding OpId from leader: term X+1, op id Y (index mismatch)
```

Where I marked the terms and op ids with X/X+1 and Y/Y+1 respectively.

@spolitov Any thoughts on this and if it is actually expected? We were confused since the vote passed and we were able to transfer leadership, but failed to replicate the NOOP so ultimately the old leader triggered a new election and got leadership again.

cc @ttyusupov @hectorgcr @amitanandaiyer

**Comment by spolitov** [comment]
Such log is impossible from our core, follower would accept update in such case.
Do you have original log to check?
