### ISSUE TITLE
[YSQL][PG15] Failed assertion running a complex SQL statement

### ISSUE THREAD

**Issue by foucher** [yugabyte/yugabyte-db#19488]
Jira Link: [DB-8285](https://yugabyte.atlassian.net/browse/DB-8285)
### Description

This issue is not 100% repro, and so far I haven't been able to find a simpler repro, though I've tried. In particular, how can step #4 make any difference? Yet I haven't noticed it happen without step #4, and it happens with step #4 for me much of the time. Also, there is some chance it happens only/more frequently on an M1MBP.

I originally discovered it when running `ysql_dump`, but at the moment there are other issues preventing people from just running that tool. This repro worked for me even on the trunk build.

Steps to repro:
1. Sync to latest pg15 (there have been fixes recently) & build
2. `bin/yb-ctl wipe_restart --tserver_flags="ysql_pg_conf_csv=checkpoint_timeout=1d"`
   * (The flag works around another bug.)
3. `bin/ysqlsh < src/postgres/src/test/regress/sql/yb_ysql_dump.sql`
4. `bin/ysqlsh < src/postgres/src/test/regress/sql/yb_ysql_dump_describe.sql`
5. Start `ysqlsh` and run the following query:
```
WITH RECURSIVE w AS ( SELECT d1.objid, d2.refobjid, c2.relkind AS refrelkind FROM pg_depend d1 JOIN pg_class c1 ON c1.oid = d1.objid AND c1.relkind = 'm' JOIN pg_rewrite r1 ON r1.ev_class = d1.objid JOIN pg_depend d2 ON d2.classid = 'pg_rewrite'::regclass AND d2.objid = r1.oid AND d2.refobjid <> d1.objid JOIN pg_class c2 ON c2.oid = d2.refobjid AND c2.relkind IN ('m','v') WHERE d1.classid = 'pg_class'::regclass UNION SELECT w.objid, d3.refobjid, c3.relkind FROM w JOIN pg_rewrite r3 ON r3.ev_class = w.refobjid JOIN pg_depend d3 ON d3.classid = 'pg_rewrite'::regclass AND d3.objid = r3.oid AND d3.refobjid <> w.refobjid JOIN pg_class c3 ON c3.oid = d3.refobjid AND c3.relkind IN ('m','v') ) SELECT 'pg_class'::regclass::oid AS classid, objid, refobjid FROM w WHERE refrelkind = 'm';
```

Result:
```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

On Mac, the postgres log shows a [regular stack trace](https://github.com/yugabyte/yugabyte-db/files/12873543/mac_stack_trace.txt). On a Linux dev server the stack trace is strange-looking, but that's another issue.

The failed assertion looks like this:
```
TRAP: FailedAssertion("ItemPointerIsValid(&scan->xs_heaptid)", File: "../../../../../../../src/postgres/src/backend/access/index/indexam.c", Line: 604, PID: 9034)
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8285]: https://yugabyte.atlassian.net/browse/DB-8285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Could not repro, alma8 fastdebug gcc11 b374032e43ffa8ad90d0ea9d239f98f89394e78f:

- Did not set `--tserver_flags="ysql_pg_conf_csv=checkpoint_timeout=1d"`, and `yb_ysql_dump.sql` still runs fine.  What was the bug?
- `yb_ysql_dump_describe.sql` crashed, but I don't see how it is necessary for the repro since it is read-only
- The query succeeds and returns zero rows

**Comment by foucher** [comment]
Regarding checkpoint timeout, it's issue #19377 which is hard to repro but you may have more luck reproducing that bug with the repro steps in that issue.

This issue is hard to repro also. I think there might be a timing-related component. I was only able to repro when including the describe sql file, but I agree it's weird that it would be necessary. I made a number of attempts to reduce the repro case but failed.

**Comment by foucher** [comment]
This is probably the same failure as in `TestPgRegressTypesUDT#testPgRegressTypesUDT`

**Comment by foucher** [comment]
Mihnea had a suggestion to have an early assert on this function entirely (`index_getnext_tid()`), and run all the tests on Jenkins, to see where this function is run. He also suggested to check for ybctid instead of tid, but I believe the structure we're asserting on is actually implemented as ybctid.
