### ISSUE TITLE
Bundle YugaByte and UI packages into one binary

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#1950]
Right now we have two separate release for YugaByte and the management UI, add a option in the yb_build to support bundling the UI binaries which would be needed for `yugabyte-db`

**Comment by iSignal** [comment]
Related diffs:

f1f2adb5fa824781ea01e238ffd3e5c6c5e547e9
1f80c00dbb45a30481c9ce36252921f9b34e23ed
ae82d8bf35d79218410a16c2cfc09a30747df216
e499023830aa82b5a7fc2ba8eaeed8091cee9537
e29613c3ed2b2ec9879c6285a8fbe8b9b9bad7e6
