### ISSUE TITLE
[yugabyted] Add a pre-req check to verify if the default ports used by yugabyted are open

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#19504]
Jira Link: [DB-8299](https://yugabyte.atlassian.net/browse/DB-8299)
### Description

When a new user starts a node of the YugabyteDB cluster using the `yugabyted start` command, the command may wait indefinitely when 7000(master) or 9000(tserver) API ports are used by some other process. I found a behavior where port forwarding on 9000 port caused the yugabyted.setup_master() hung and didn't return even after 5 minutes.  

### Tasks 

- Add a pre-req check for default ports `7000,9000,7100,9100,15433,5433,9042,13000,12000`
- Add timeout for `get_current_masters_from_api` and find other API call methods where the timeout is absent.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8299]: https://yugabyte.atlassian.net/browse/DB-8299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ShikharSahay** [comment]
Code changes landed.
