### ISSUE TITLE
[DocDB] SchemaPacking updates could be missed during remote bootstrap race

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#19507]
Jira Link: [DB-8303](https://yugabyte.atlassian.net/browse/DB-8303)
### Description

Spinning off from #15051, as a net new issue. cc @shamanthchandra-yb 

As per discussion with @spolitov , there seems to be a race on remote bootstrap (RBS). We can have a concurrent schema change and a remote bootstrap. During RBS, we first copy the tablet metadata, then we create a rocksdb snapshot and copy that. So we could end up in a situation where the tablet meta is consistent as of op id X (not including the schema change), but the rocksdb gets flushed as of op id X+1, which includes the schema change. Then on the remote peer, after RBS, we do not replay the schema change, due to the rocksdb flushed op id metadata.

As per discussion with Sergei, this is only an issue in 2.16, because from 2.18 onwards, we had this work in: 065f0d3fa5c789122be0d94cdc5c2b29fa9ec196, which would ensure we capture the last ChangeMetadata op_id in the TabletMetadata and replay them accordingly on the newly bootstrapped peer, thus not missing out on any SchemaPackings anymore. Sadly, that work itself apparently has a bug, which we are tracking independently in #19546.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8303]: https://yugabyte.atlassian.net/browse/DB-8303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
This is fixed by the commit [975b0d5](https://github.com/yugabyte/yugabyte-db/commit/975b0d560b0921cfd2ab0d370de6c086ce540a13) made as part of https://github.com/yugabyte/yugabyte-db/issues/19546 . The backports are tracked in the other GH itself. Closing this one.
