### ISSUE TITLE
[DocDB] All nodes in universe became unreachable while adding nodes during high write workload and a vm restart

### ISSUE THREAD

**Issue by archit-rastogi** [yugabyte/yugabyte-db#19545]
Jira Link: [DB-8332](https://yugabyte.atlassian.net/browse/DB-8332)
### Description

Description:
![Screenshot 2023-10-16 at 6 01 30 PM](https://github.com/yugabyte/yugabyte-db/assets/24272073/eae794f3-47fd-411f-a928-db25d81545eb)

Universe: RF5

Stress run scenario:
http://stress.dev.yugabyte.com/stress_test/5546f00e-1208-46b9-959a-0234535eedf6

![Screenshot 2023-10-16 at 11 29 30 PM](https://github.com/yugabyte/yugabyte-db/assets/24272073/1e00a4ba-cdbd-4e76-a51f-9a995f9c3256)

Support bundle:
[yb-support-bundle-auto-stress-arastogi-45780-20231016121358.002-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/12920325/yb-support-bundle-auto-stress-arastogi-45780-20231016121358.002-logs.tar.gz)

cc: @basavaraj29 @rthallamko3 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8332]: https://yugabyte.atlassian.net/browse/DB-8332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by archit-rastogi** [comment]
Observed Multiple Error entries logged like below:
 ```
17876:I1016 12:03:01.900718 17221 tablet_service.cc:2408] Leader stepdown request tablet_id: "bbcb9e6cb7694c4e850f93dfaa13333f" dest_uuid: "c19cdc7a465c490fb529372d1fc9000f" new_leader_uuid: "2adf67dd1d9e4b7ab3a3598548417a86" failed. Resp code=UNKNOWN_ERROR
```

**Comment by rthallamko3** [comment]
@archit-rastogi , Can you clarify if this is a recent regression or a new test? cc @Huqicheng

**Comment by archit-rastogi** [comment]
@rthallamko3 this is a new test. so cannot confirm if this is a regression.

**Comment by rthallamko3** [comment]
@archit-rastogi , Does this issue repro even now? Wondering if this was something on the platform side that got fixed.
