### ISSUE TITLE
[DocDB] TServer may crash when replaying alter schema during local bootstrap

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#19546]
Jira Link: [DB-8334](https://yugabyte.atlassian.net/browse/DB-8334)
### Description

It could happen that server will have to replay alter schema during local bootstrap.

But commit 065f0d3fa5c789122be0d94cdc5c2b29fa9ec196/D19063 added regression, when Prepare is not called on `ChangeMetadataOperation` in `PlayChangeMetadataRequest`.

It results in failure of this check:
```  
RSTATUS_DCHECK_NE(operation->schema(), static_cast<void*>(nullptr), InvalidArgument,
                  "Schema could not be null");
```
in `Tablet::AlterSchema`.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8334]: https://yugabyte.atlassian.net/browse/DB-8334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Related to https://github.com/yugabyte/yugabyte-db/issues/19507

**Comment by rthallamko3** [comment]
Reactivating for the 2.16 backport to land.
