### ISSUE TITLE
[DocDB] Add remote bootstrap debug UI to tserver debug UI

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#19568]
Jira Link: [DB-8349](https://yugabyte.atlassian.net/browse/DB-8349)
### Description

We should add a page dedicated to showing all of the remote bootstraps occurirng on a tserver at a given time, including start time, progress, remote source, and other relevant information

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8349]: https://yugabyte.atlassian.net/browse/DB-8349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mdbridge** [comment]
this might be a subset of the work  proposed in https://github.com/yugabyte/yugabyte-db/issues/19570

**Comment by mdbridge** [comment]
see also https://github.com/yugabyte/yugabyte-db/issues/19567

**Comment by bmatican** [comment]
@basavaraj29 I was also thinking we could use this as a precursor / pre-req for making this info available to the master as well. @SrivastavaAnubhav was saying that we're missing this info in the LB, for being able to tie it to your other work, or RBS from closer follower.

So I am thinking of two followup improvements on top of this
- On the tserver side, have a dedicated page for RBS sessions, showing a clear breakdown of source vs target side. For each side, we know and could show the exact set of files to be transferred (eg: TabletMeta, WALs, rocksdb SST files) and the progress through them. This would allow us to know cleanly if a particular session is making progress and how effectively.
- We could also flow this, to the master side, via the metrics heartbeat path, thus allowing the master to also be aware of the ongoing RBS sessions and even the progress, should we choose to have a similar, centralized view. Most importantly though, the LB would now become aware of the source/dest pairs.
