### ISSUE TITLE
Please explain the inscrutable rules for when "commit" in a stored proc succeeds or causes a run-time error

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#1957]
People have blogged about the fact that `commit` is legal in a PostgreSQL stored proc, starting with version 11—which is what yugabyteDB Version 1.3.0 uses. Here’s an example:

> https://www.2ndquadrant.com/en/blog/postgresql-11-server-side-procedures-part-1/

However, these blogs forget that `psql` (and therefore `ysqlsh`) have `AUTOCOMMIT` set to `True` by default. They seem to do their tests in that mode and forget that  the `AUTOCOMMIT` mode might be `False`. However, things change when the `AUTOCOMMIT` mode is `False`. See the following testcase.

I would like to hear the explanation for this weird behavior. It’s add odds with the definition of autocommitting: if the insert has autocommitted, then by definition there’s nothing to `commit` or` rollback`.

Following on from this, I see no reason why `call my_proc()` has to start a txn. It might do no more than a calculation. As I see it, it’s the first SQL statement that’s executed from the stored proc that should start a txn. Notice that within the present regime, and given that the weakest isolation level in yugabyte DB is `repeatable read`, you cannot implement a stored proc to watch a table in an infinite loop and to respond when it suffers an interesting change. Unless, that is, the non-intuitive workaround that I show below helps there.

> Note: this remains to be tested.

```
\i psqlrc
\set AUTOCOMMIT False
begin;
drop table if exists marbles;
commit;

begin;
create table marbles(
  pk integer
    constraint t_pk primary key,
  color text
    constraint t_c1_nn not null
    constraint t_c1_chk check(color in ('black', 'white'))
  );
commit;

begin;
insert into marbles(pk, color) values
  (1, 'black'),
  (2, 'white');
commit;

begin;
drop procedure if exists set_all_marbles_black();
commit;

begin;
create procedure set_all_marbles_black()
  language plpgsql
as $$
  begin
    -- The "start transaction" and "set transaction" errors can be
    -- understood in the context that "call" starts a transaction, if
    -- one isn't already ongoing.

    -- Commented out 'cos causes run-time error
    -- "0A000: unsupported transaction command in PL/pgSQL".
    -- start transaction;

    -- Commented out 'cos causes run-time error
    -- "25001: SET TRANSACTION ISOLATION LEVEL must be called before any query"
    -- Yet, as a top-level command, it *does* start a txn.
    -- set transaction isolation level serializable;

    update marbles set color = 'black' where color = 'white';

    -- It's hard to understand the thinking that requires this error.
    -- Especially given that it occurs when AUTOCOMMIT is False
    -- but not when it's True.
    -- Causes "2D000: invalid transaction termination"
    rollback;
  end;
$$;
commit;

select pk, color from marbles order by pk;
rollback;

\set AUTOCOMMIT True
-- Runs OK, and the "rollback" has its effect.
call set_all_marbles_black();
select pk, color from marbles order by pk;

\set AUTOCOMMIT False
-- This causes:
--   ysql:plpgsql_proc_txn_control.sql:63: ERROR:  invalid transaction termination
--   CONTEXT:  PL/pgSQL function set_all_marbles_black() line 21 at ROLLBACK
call set_all_marbles_black();

-- Must rollback before trying anything else.
rollback;
```
Here, for completeness, is another manifestation of the same issue. This quietly succeeds:
```
\set AUTOCOMMIT True
do $$
begin
  update marbles set color = 'black' where color = 'white';
  commit;
end
$$;
```
But this fails with `"ERROR: invalid transaction termination"`:
```
\set AUTOCOMMIT False
do $$
begin
  update marbles set color = 'black' where color = 'white';
  commit;
end
$$;
```

**Comment by bllewell** [comment]
[2ndQuadrant_Testcase.zip](https://github.com/YugaByte/yugabyte-db/files/3463146/2ndQuadrant_Testcase.zip)

Here is a cosmetically massaged version of the code example from the 2ndQuadrant blog post. Unzip it and start `2ndQuadrant_Testcase.sql` with `\i` in the `psql` shell using a PostgreSQL database. Same outcome with the `ysqlsh` using a YB database.

It shows that, though `AUTOCOMMIT` is `True` at the top level, and though `call p()` starts a txn, we can repeatedly issue `commit` or 'rollback` inside the procedure and implicitly start a new txn with the next `insert` statement.

**Comment by FranckPachot** [comment]
Hi Bryn,
Here is the summary of my observations. Actually, even if it sounds counterintuitive, in AUTOCOMMIT OFF psql adds a BEGIN transaction before the call and then the procedure is run in an atomic context, where commit is not allowed. In AUTOCOMMIT ON, the client psql adds nothing and it is the server backend that starts the implicit transaction, there allowing transaction management in the procedure. I've posted my investigation [Here](https://medium.com/@FranckPachot/postgresql-transaction-management-in-procedures-9b57cb909067?source=friends_link&sk=e63badc990867560b73a3256d9e1c331).

**Comment by kmuthukk** [comment]
@FranckPachot -- thx for your detailed post! Will take a more careful read. 

But your summary explanation seems to fit what Bryn and I speculated on the whiteboard (when he raised the issue) that with autocommit off, for some reason the procedure is expected to behave as one atomic thing and the transaction control is taken away from it. 

But will read your post in detail later for the full / internal scoop.

**Comment by bllewell** [comment]
See [THIS TWEET](https://twitter.com/petereisentraut/status/1158802910865756160) from Peter Eisentraut in response to “Why must `AUTOCOMMIT` be `on` to do txn control in a PL/pgSQL procedure?” 

> It’s an implementation restriction, for the most part.

**Comment by wiwwo** [comment]
I am afraid all those assumptions break if PROCEDURE has an `exception` block where you call `get stacked diagnostics`...

```
\set AUTOCOMMIT True
do $$
declare
  err_text1 text;
  err_text2 text;
  err_text3 text;
begin
  update marbles set color = 'black' where color = 'white';
  commit;
exception when others then 
    get stacked diagnostics err_text1 = MESSAGE_TEXT,
                            err_text2 = PG_EXCEPTION_DETAIL,
                            err_text3 = PG_EXCEPTION_HINT;
    raise notice 'MESSAGE_TEXT: %', err_text1;
end
$$;
NOTICE:  00000: MESSAGE_TEXT: invalid transaction termination
LOCATION:  exec_stmt_raise, pl_exec.c:3803
DO
Time: 82.609 ms

```

**Comment by bllewell** [comment]
Yes, I later discovered that executing "commit" or "rollback" a block statement that has an exception section also causes the "invalid transaction termination". See my issue # #2464. I also discovered (and this is documented at https://www.postgresql.org/docs/current/sql-createprocedure.html) that "A SECURITY DEFINER procedure cannot execute transaction control statements."

**Comment by bllewell** [comment]
A long time has gone by and I don't expect to get any more answers. I'll close this now. Presently, I'll revisit the topic and look to designing more useful experiments.
