### ISSUE TITLE
[yugabyted] Handling upgrades for YugabyteDB gracefully using yugabyted CLI.

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#19581]
Jira Link: [DB-8362](https://yugabyte.atlassian.net/browse/DB-8362)
### Description

The current way to do upgrades using yugabyted is: 
1. Stop all nodes using older YugabyteDB version.
2. Restart the nodes using the newer version.
Docs Link: https://docs.yugabyte.com/preview/reference/configuration/yugabyted/#upgrade-a-yugabytedb-cluster

In this setup, yugabyted stops `master` and `tserver` processes for each node and restarts the processes for each node in a sequential order of nodes.

This is not the correct way to handle upgrades according to core-db: https://docs.yugabyte.com/preview/manage/upgrade-deployment/

Slack discussion thread: https://yugabyte.slack.com/archives/C02T5NUTAPM/p1690498568625459

Add the feature to handle upgrading a cluster using yugabyted according to the officially supported upgrade process.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8362]: https://yugabyte.atlassian.net/browse/DB-8362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ShikharSahay** [comment]
The findings and steps for handling upgrades through yugabyted have been updated in this [jira ticket.](https://yugabyte.atlassian.net/browse/DB-8755)
