### ISSUE TITLE
Doc support for index attributes in JSONB columns

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#1960]
Answer by @rkarthik007 here, but GitHub issue was never filed by the user:
https://stackoverflow.com/questions/56610522/does-yugabyte-s-sql-support-index-attributes-inside-a-jsonb-column?rq=1

**Comment by bllewell** [comment]
The documentation for this topic has been in place since 19-Mar-2020. It was brought by [PR #4011](https://github.com/yugabyte/yugabyte-db/pull/4011).
