### ISSUE TITLE
[YSQL][PG15] "COPY <table> TO stdout" returns no results

### ISSUE THREAD

**Issue by foucher** [yugabyte/yugabyte-db#19603]
Jira Link: [DB-8383](https://yugabyte.atlassian.net/browse/DB-8383)
### Description

```
yugabyte=# CREATE TABLE t (a int);
CREATE TABLE
yugabyte=# INSERT INTO t VALUES (1);
INSERT 0 1
yugabyte=# COPY t TO stdout;
yugabyte=# COPY (SELECT * FROM t) TO stdout;
1
```

The first `COPY` should return the same thing as the second `COPY`.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8383]: https://yugabyte.atlassian.net/browse/DB-8383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arpang** [comment]
I am not sure who fixed it, but this is no longer reproducible.
