### ISSUE TITLE
[DocDB] Bootstrap of tablet takes several seconds after node restart during rolling restart 

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#19615]
Jira Link: [DB-8393](https://yugabyte.atlassian.net/browse/DB-8393)
### Description

Restarted a node on a 8 core RF-3, 3 node cluster, with a constantly running workload (user CPU over 60%). Noticed a bunch of tablets whose bootstrap took over 10 seconds. 

Since platform evicts leaders before restarting a node, Consider flushing the data corresponding to tablets, when the raft role is changed from leader to follower, so that there are fewer WALs to replay when the tablet bootstraps.

[Universe]( https://portal.dev.yugabyte.com/universes/31093fbb-28a2-4608-9ad4-4a1bff636756/) on version  2.21.0.0 build 99 (So it has persisted retryable requests).

One set of logs from yb-15-rthallam-test-n1 [yb-tserver.INFO.txt](https://github.com/yugabyte/yugabyte-db/files/13048647/yb-tserver.INFO.txt)

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8393]: https://yugabyte.atlassian.net/browse/DB-8393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
cc @bmatican

**Comment by bmatican** [comment]
Checking one of the really slow tablets (20s+ to bootstrap)
```
I1019 23:41:58.279273  2806 retryable_requests.cc:258] Initialized RetryableRequestsManager, found a file ? yes, wal dir=/mnt/d0/yb-data/tserver/wals/table-000033f5000030008000000000004069/tablet-7c22afe87a9a4aaaaaa0250200346d45
I1019 23:41:58.279284  2806 ts_tablet_manager.cc:1603] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Failed to get tablet retryable requests: Not found (yb/tserver/ts_tablet_manager.cc:1959): Tablet 202bc63dec9246f68a4581b18c8f63b3 not found
```
Does this mean we didn't find the persisted file? cc @Huqicheng 
```
I1019 23:41:59.132726  2806 tablet.cc:896] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Successfully opened a RocksDB database at /mnt/d0/yb-data/tserver/data/rocksdb/table-000033f5000030008000000000004069/tablet-7c22afe87a9a4aaaaaa0250200346d45, obj: 0x352f6831b480
I1019 23:41:59.132756  2806 tablet_bootstrap.cc:610] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Time spent opening tablet: real 0.853s▸ user 0.003s▸sys 0.005s
```
It took us almost 1s to open regular and intents rocksdb, that sounds really high! Is this common? Is this specific to this particular tablet? Was the system overloaded (as there's some slow fsync messages before)?
```
I1019 23:41:59.191023  2806 retryable_requests.cc:298] Loaded tablet (7c22afe87a9a4aaaaaa0250200346d45) retryable requests (max_replicated_op_id_=term: 12 index: 22995349) from /mnt/d0/yb-data/tserver/wals/table-000033f5000030008000000000004069/tablet-7c22afe87a9a4aaaaaa0250200346d45/retryable_requests
```
This is confusing, so did we or did we not use the retryable request persisted file?
```
I1019 23:41:59.191143  2806 tablet_bootstrap.cc:1188] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Flushed DocDB OpIds: { regular: 12.23195876 intents: 12.23195505 }
I1019 23:41:59.277590  2806 tablet_bootstrap.cc:1352] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Bootstrap optimizer (skip_flushed_entries): found first mandatory segment op id: 12.22701263, op_id_replay_lowest=12.23195505, last_op_id_in_retryable_requests=12.22995349, first_op_time=92532.884s, const_min_duration_to_retain_logs=0.000s, retryable_requests_retain_interval=660.000s, *retryable_requests_replay_from_this_or_earlier_time=93549.563s, *replay_from_this_or_earlier_time=94209.563s, number of segments to be skipped: 0
...
I1019 23:42:09.385277  2806 tablet_bootstrap_if.cc:96] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Bootstrap replayed 1/2 log segments. Read operations: 294089, overwritten operations: 0. Pending: 3 replicates. Last read committed op id: 12.22995348, last entry metadata: { entry_time: 94209.560s offset: 67108862 active_segment_sequence_number: 88 }, last read entry op id: 12.22995351
...
I1019 23:42:16.894529  2806 tablet_bootstrap_if.cc:96] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Bootstrap replayed 2/2 log segments. Read operations: 535874, overwritten operations: 0. Pending: 2 replicates. Last read committed op id: 12.23237134, last entry metadata: { entry_time: 95587.644s offset: 55047919 active_segment_sequence_number: 89 }, last read entry op id: 12.23237136
...
I1019 23:42:16.895114  2806 tablet_bootstrap.cc:1162] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Log entries applied to RocksDB: 535872
...
I1019 23:42:18.942899  2806 ts_tablet_manager.cc:1615] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Time spent bootstrapping tablet: real 20.664s▸user 3.626s▸sys 1.063s
```
So about 10s for each WAL that we replay.
But I don't understand why we replayed >500k items? Why was this the mandatory minimum: `found first mandatory segment op id: 12.22701263, op_id_replay_lowest=12.23195505, last_op_id_in_retryable_requests=12.22995349`

**Comment by Huqicheng** [comment]
@bmatican 
According to the log, tablet 7c22afe87a9a4aaaaaa0250200346d45 has a parent tablet 202bc63dec9246f68a4581b18c8f63b3, it firstly try to copy the retryable requests from the parent tablet but it failed because the parent is not alive so it printed log `I1019 23:41:58.279284  2806 ts_tablet_manager.cc:1603] T 7c22afe87a9a4aaaaaa0250200346d45 P 352aeb94ee62476d9fb51df30d35df24: Failed to get tablet retryable requests: Not found (yb/tserver/ts_tablet_manager.cc:1959): Tablet 202bc63dec9246f68a4581b18c8f63b3 not found`

But a persisted file was found so that it loaded the file and started with this file.

**Comment by ajd12342** [comment]
Hi @rthallamko3 !
I am Anuj Diwan, a Computer Science PhD student at UT Austin. I am part of a team along with @arjunrs1 (Arjun Somayazulu) and we're taking a graduate [Distributed Systems course](https://github.com/vijay03/cs380d-f23). For our course project, we are interested in contributing to Yugabyte. This issue is related to our course material. Could we work on this issue? Any pointers for us to get started would be appreciated as well. 

Thanks and regards,
Anuj.

**Comment by rthallamko3** [comment]
@ajd12342 , Refer to Yugabyte contribution page for instructions - https://docs.yugabyte.com/preview/contribute/core-database/checklist/ Feel free to take up this issue. cc @Huqicheng in case you need references to this particular issue. If you get past the initial aspects, we can identify a couple more items in this area.

**Comment by rthallamko3** [comment]
Recent bootstrap improvements in 2024.1 timeframe should have addressed this. Closing this for now.
