### ISSUE TITLE
[YCQL] Failed to drop index with tserver restarts

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#19628]
Jira Link: [DB-8414](https://yugabyte.atlassian.net/browse/DB-8414)
### Description

Case:
1. Start univers, 3 nodes, RF=3, 4 CPU 8 GB RAM
2. Start workload with only inserts and selects ```yb-stress-sample-apps-1.1.24.jar --workload CassandraDataLoad  --num_writes -1 --num_reads -1 --num_unique_keys 10000000000 --num_value_columns 15 --num_indexes 10 --uuid dc03d3a0-a3e9-42c6-97e6-69c790e1af75 --retry_primary_key true --create_table_name test_indexes_d3d7e2 --num_threads_write 4 --num_threads_read 10 --batch_size 10 --uuid_marker 74ad0772-de2e-4e80-b9e8-e3dc028db120  --nodes```
3. Start loop:
3.1. Drop index on  `test_indexes_d3d7e2` table (it already has 10) for v1,v2,v3,.....v10 columns
3.2. Wait 20 sec
3.3. Create index back
3.4. Check that index created

After 1 hour of this loop it failed to drop index
```
> /home/yugabyte/tserver/bin/ycqlsh -e "drop index    test_indexes_d3d7e2byvaluev7_idx7" --request-timeout 10800 -k ybdemo_keyspace 172.151.20.85 9042
< <stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Object Not Found. Table ybdemo_keyspace.test_indexes_d3d7e2byvaluev7_idx7 not found: OBJECT_NOT_FOUND (master error 3)
drop index    test_indexes_d3d7e2byvaluev7_idx7;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 (ql error -301)"
```
[All universe and framework logs](https://drive.google.com/file/d/1hqy8e59-19Rw-3ijK5CTWCShQUmG-VLP/view?usp=sharing)
Report link in jira ticket

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8414]: https://yugabyte.atlassian.net/browse/DB-8414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pilshchikov** [comment]
@rthallamko3 it's a same case as https://github.com/yugabyte/yugabyte-db/issues/15374 but issue different

**Comment by lingamsandeep** [comment]
Create index is failing on the backfill step which causes the index to never get created fully and so drop fails. Index creation is failing with “Table metadata cache is not present for index update”

1. Test issued a create index here: 

```
2023-10-23 17:48:36,176: INFO: attachment Workload logs/172.151.22.67/workload-74ad07-CassandraDataLoad.20231023164616.log(de026e55-31f7-4b12-a7d9-cf3ebf766797-workload-74ad07-CassandraDataLoad.20231023164616.log) added
2023-10-23 17:48:49,653:DEBUG: > 172.151.20.129 > /home/yugabyte/tserver/bin/ycqlsh -e "create index    test_indexes_d3d7e2byvaluev7_idx7 on test_indexes_d3d7e2(v7)" --request-timeout 10800 -k ybdemo_keyspace 172.151.20.129 9042  2>&1
```

2.  Index backfill failed here:

```
W1023 17:49:28.614101 78844 backfill_index.cc:1549] TS 726520cdb1444814b3924b879b53179d: backfill failed for tablet 187030b0ee70416fb9158620f3c071db (table test_indexes_d3d7e2 [id=5301ef1a60bd4e58b75ad86e6a098d0e]) no further retry: Illegal state (yb/tablet/tablet.cc:2693): Table metadata cache is not present for index update response was error { code: OPERATION_NOT_SUPPORTED status { code: ILLEGAL_STATE message: "Table metadata cache is not present for index update" source_file: "../../src/yb/tablet/tablet.cc" source_line: 2693 errors: "\000" } } propagated_hybrid_time: 6955349477840584704 backfilled_until: "G\343\307Sdc03d3a0-a3e9-42c6-97e6-69c790e1af75:82002\000\000!!" number_rows_processed: 108799
I1023 17:49:28.614185 78844 async_rpc_tasks.cc:365] Backfilling indexes { test_indexes_d3d7e2byvaluev7_idx7 } for tablet 187030b0ee70416fb9158620f3c071db from key '47ce5f5364633033643361302d613365392d343263362d393765362d3639633739306531616637353a33323237323700002121' (task=0x000055904ff67218, state=kFailed): No reschedule for this task: kFailed
I1023 17:49:28.614202 78844 backfill_index.cc:1301] Failed to backfill the tablet 0x0000559050b22580 -> 187030b0ee70416fb9158620f3c071db (table test_indexes_d3d7e2 [id=5301ef1a60bd4e58b75ad86e6a098d0e]): Illegal state (yb/tablet/tablet.cc:2693): Table metadata cache is not present for index update
Failed_indexes are [4985b91af481490baea71b0a2f4e70b5]
E1023 17:49:28.614212 78844 backfill_index.cc:971] Backfill Index Table(s) { test_indexes_d3d7e2byvaluev7_idx7 } failed to backfill the index: [4985b91af481490baea71b0a2f4e70b5] due to Illegal state (yb/tablet/tablet.cc:2693): Table metadata cache is not present for index update
```

3. As a result of the above the index is eventually deleted without the create completing successfully:

`I1023 17:49:28.836943 78847 catalog_manager.cc:6345] Marking table as DELETED: test_indexes_d3d7e2byvaluev7_idx7 [id=4985b91af481490baea71b0a2f4e70b5]`

4. Because the index creation does not complete succesfully, eventually the delete fails:

```
I1023 17:52:26.117554 50604 catalog_manager.cc:5874] Servicing DeleteTable request from 172.151.20.85:44773: table { table_name: "test_indexes_d3d7e2byvaluev7_idx7" namespace { name: "ybdemo_keyspace" database_type: YQL_DATABASE_CQL } } is_index_table: true
I1023 17:52:26.121932 50544 catalog_manager.cc:5874] Servicing DeleteTable request from 172.151.20.85:42473: table { table_name: "test_indexes_d3d7e2byvaluev7_idx7" namespace { name: "ybdemo_keyspace" database_type: YQL_DATABASE_CQL } } is_index_table: true
```

**Comment by rthallamko3** [comment]
Per Amit's analysis, this should not be an issue with #17359 . cc @amitanandaiyer

**Comment by rthallamko3** [comment]
Seems like it is happening on master. @amitanandaiyer  taking a closer look.

**Comment by pilshchikov** [comment]
Test issue, need to track index backfill progress and then drop it
