### ISSUE TITLE
Whether to support upgrades across major versions ?

### ISSUE THREAD

**Issue by cevin** [YugaByte/yugabyte-db#1967]
like 1.0 master x2, 2.0 masterx1 , 1.0 tserver * X, 2.0 tserver * N

**Comment by kmuthukk** [comment]
For features in beta (e.g., YSQL is still in beta prior to the upcoming 2.0), upgrades might not be seamless (as there might be disk format changes).

But for features that are already in GA (Generally Available) such as YCQL we will support upgrade compatibility. You should be able to do a rolling restart of the cluster from 1.0 -> 2.0 -> etc. without having to do any data format changes.
