### ISSUE TITLE
[docs] Document how to use snapshot primitives to execute backup/restore operations

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1970]
Top level goal would be to run through the motions of doing various backup/restore operations and then documenting this for the community. A nice (local) demo, could be something as simple as:
- creating a local RF1 cluster using yb-ctl
- write some fixed data that you can query for later
- backup the data from it
- destroy the cluster and recreate it empty but as RF3
- restore the previous data into it
- query for all the relevant data and confirm it’s there, as expected
---
To begin with, you will need to familiarize yourself a bit with 3 aspects of running and operating YB:
1) running a cluster
2) using yb-admin to inspect the cluster or trigger some admin operations on it
3) understanding a bit of the file system structure of how YB lays out files
---
1) For running a cluster, I believe you’ve done this before, but even just a simple yb-ctl setup will be good enough to test backup/restore procedures.
2) For yb-admin, there will be a number of commands that will be useful:
- list_all_masters — figure out the master leader
- list_tablets — list all the tablets and their replica locations for a particular table; useful to find out who the LEADER of a tablet is
- create_snapshot — trigger the async task of creating a snapshot for a given table and get back a snapshot_id
- list_snapshots — check the status of the currently available snapshots (current one likely not yet COMPLETE)
- export_snapshot — generated a metadata file for the given snapshot, listing all the relevant internal UUIDs for various objects (table, tablet, etc)
- import_snapshot — given a snapshot metadata file, imports it into YB and lists a bunch of metadata like mapping from old UUIDs to new ones
- restore_snapshot — once all the data files are put in place as well, finalize the restore procedure
- delete_snapshot — delete the snapshot information, usually cleanup at the end, since this is supposed to be transient state
3) Finally, for the filesystem information, these are loosely the types of paths you will need to look at:
- exported snapshot file — this is normally a user provided path
- tablet snapshot data — a simple regex for this would be “/yb-data/tserver/data/rocksdb/table-/tablet-.snapshots/“, looking over all of the dirs in fs_data_dirs, all of the tables, all their tablets, all their snapshot files
---
Now to string this together, the 2 processes should look something like the following:

Backup
- trigger a snapshot
- wait for it to be complete
- export the snapshot metadata to a file (this will normally be created on the master leader file system)
- copy the snapshot metadata to an external location
- copy the data file for all the tablets
- cleanup at the end by deleting the snapshot

Restore
- copy the snapshot metadata (on a distributed cluster, on the master leader, so it has access to it during the import)
- trigger a snapshot import
- download all the tablet data in all the relevant TSs (listing the TS for this table will tell you all the locations of where this data should live)
- once all the data files have been copied over, issue the final restore_snapshot and wait for it to be complete
- cleanup at the end by deleting the snapshot

cc @OlegLoginov @kmuthukk @rkarthik007

**Comment by ddorian** [comment]
Commenting for assignment.

**Comment by ddorian** [comment]
this is merged
