### ISSUE TITLE
[YCQL] Please support JSON processing functions

### ISSUE THREAD

**Issue by nodakai** [yugabyte/yugabyte-db#19711]
Jira Link: [DB-8512](https://yugabyte.atlassian.net/browse/DB-8512)
### Description

Example: "For each bank, return the names of all depositors having > 10k USD and > 20k EUR in their balance"

```
| bank | data |

"FooBank" | {"accounts": [
  {"name": "alex",
    "balances": [
      {"ccy": "USD", "balance": 12345},
      {"ccy": "EUR", "balance": 0},
      {"ccy": "JPY", "balance": 0}
    ]
  },
  {"name": "bob",
    "balances": [
      {"ccy": "USD", "balance": 0},
      {"ccy": "EUR", "balance": 23456},
      {"ccy": "JPY", "balance": 0}
    ]
  }
]}

"BarBank" | {"accounts": [
  {"name": "chelsea",
    "balances": [
      {"ccy": "USD", "balance": 22334},
      {"ccy": "EUR", "balance": 33445},
      {"ccy": "JPY", "balance": 0}
    ]
  },
  {"name": "denji",
    "balances": [
      {"ccy": "USD", "balance": 0},
      {"ccy": "EUR", "balance": 0},
      {"ccy": "JPY", "balance": 5000}
    ]
  }
]}
```

If I were using Postgres, I'd write a query like

```
SELECT a->>'name'
FROM mytable t, jsonb_array_elements(t.data->'accounts') a
WHERE EXISTS (
  SELECT * 
  FROM jsonb_array_elements(a->'balances') b 
  WHERE b->>'ccy' = 'USD' AND (b->>'balance')::float8 > 10000
)
AND EXISTS (
  SELECT * 
  FROM jsonb_array_elements(a->'balances') b 
  WHERE b->>'ccy' = 'EUR' AND (b->>'balance')::float8 > 20000
);
```

However I believe this is not currently possible with YCQL.

Porting some of these functions would be awesome
https://www.postgresql.org/docs/16/functions-json.html#FUNCTIONS-JSON-PROCESSING-TABLE

Especially,

https://docs.yugabyte.com/preview/develop/learn/data-modeling-ycql/#comparison-with-apache-cassandra-s-json-support

> Cassandra developers needing native JSON support previously had no choice but to add a new document database such as MongoDB or Couchbase into their data tier.

Both document databases allow users to write complex queries that examine nested sub-documents, similar to the one above.

I'll be shedding tears of joy the moment YCQL becomes as adept as they are.

That's when I could truly consider migrating away from document databases.

### Issue Type

kind/new-feature

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8512]: https://yugabyte.atlassian.net/browse/DB-8512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @nodakai 

> If I were using Postgres, I'd write a query like

You can use that query in YSQL.

> I'll be shedding tears of joy the moment YCQL becomes as adept as they are.

Why not use YSQL?

**Comment by nodakai** [comment]
> You can use that query in YSQL.

Yeah that's a viable option indeed.

> Why not use YSQL?

YCQL is like, 2x more performant than YSQL? https://docs.yugabyte.com/preview/benchmark/ycsb-ycql/

It's true it can be seen as a marginal difference given all the strong guarantees offered by RDBMS (YSQL).

Well, in fact, I plan to add many columns to my "table". Imagine various versions of (sparse) generated columns derived from a single JSONB column. (YCQL currently doesn't support generated columns or material views, my program will take care of it during the INSERT process). I'm not an expert, but from what I understand, Apache Cassandra, a wide-column store, is specifically designed to manage scenarios with a large number of columns more efficiently than traditional RDBMS.

https://stackoverflow.com/questions/4229805/how-much-disk-space-is-needed-to-store-a-null-value-using-postgresql-db 

https://aiven.io/blog/an-introduction-to-apache-cassandra#the-wide-column-store-and-how-data-is-modelled

I'm not sure if this same trend applies between YSQL and YCQL (when both are backed by the same storage layer, called DocDB). I just assumed it would be similar.

**Comment by ddorian** [comment]
> YCQL is like, 2x more performant than YSQL? https://docs.yugabyte.com/preview/benchmark/ycsb-ycql/

I don't know if it's 2x if we use the same semantics (inserts as upserts, etc).

> I'm not an expert, but from what I understand, Apache Cassandra, a wide-column store, is specifically designed to manage scenarios with a large number of columns more efficiently than traditional RDBMS.

It's actually not. Cassandra has large overhead by storing each column separately (we used to do this too). The reason we introduced "Packed Row".

There is a pretty big misconception that Cassandra is columnar or column oriented or more efficient.

> Imagine various versions of (sparse) generated columns derived from a single JSONB column.

You should store them as normal columns usually (see link below).

--------

Between adding features to YCQL vs making YSQL faster, we'll chose to make YSQL faster.


Please read this page https://docs.yugabyte.com/preview/develop/best-practices-ysql/.

**Comment by ddorian** [comment]
Closing this as not planned & available in YSQL with the reasoning explained above.
