### ISSUE TITLE
[DocDB][ActiveHistory]Track calls to local tserver in the list of RPCs 

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#19750]
Jira Link: [DB-8596](https://yugabyte.atlassian.net/browse/DB-8596)
### Description

The calls to local tservers needs to be added to the list of RPCs before it is fetched by AUH.  

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8596]: https://yugabyte.atlassian.net/browse/DB-8596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Addressed as part of #19697
