### ISSUE TITLE
Document location of yugabyte-client for every major release in the ysqlsh and ycqlsh reference

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#1978]
There have been a few requests for a location to download a ysqlsh client independently of the db package. It might be beneficial to release a binary package / installer that packages ysqlsh with common drivers.

**Comment by schoudhury** [comment]
@stevebang  every major release we are building these 2 tar.gzs. The ones for 2.2 are not yet built but are being tracked via https://github.com/yugabyte/yugabyte-db/issues/5131

After the above issue is closed, pls add the following to the 2 reference pages.

binary files
https://downloads.yugabyte.com/yugabyte-client-2.2-linux.tar.gz
https://downloads.yugabyte.com/yugabyte-client-2.2-darwin.tar.gz

docker images
docker run -it yugabytedb/yugabyte-client ysqlsh
docker run -it yugabytedb/yugabyte-client ycqlsh

**Comment by iSignal** [comment]
Published https://hub.docker.com/layers/yugabytedb/yugabyte-client/2.2/images/sha256-634a9cdf7d31a72e72e40ec911f0e03ec3744cacd740400988462cd9334ae80a?context=explore 

Updated http://downloads.yugabyte.com/get_clients.sh to point to 2.2

Download locations:

https://downloads.yugabyte.com/yugabyte-client-2.2-linux.tar.gz
https://downloads.yugabyte.com/yugabyte-client-2.2-darwin.tar.gz

**Comment by iSignal** [comment]
Updated the client packages for 2.4

https://downloads.yugabyte.com/yugabyte-client-2.4-linux.tar.gz
https://downloads.yugabyte.com/yugabyte-client-2.4-darwin.tar.gz

Updated http://downloads.yugabyte.com/get_clients.sh to point to 2.4

https://hub.docker.com/layers/yugabytedb/yugabyte-client/2.4/images/sha256-0f6790b670ecb1c29c858d2c82dc288341555d8b1240d6754bbbf9ffcba5b84c?context=explore
