### ISSUE TITLE
[YSQL] flaky test: PgMiscConflictsTest.TablegroupFKDelete

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#19824]
Jira Link: [DB-8757](https://yugabyte.atlassian.net/browse/DB-8757)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgMiscConflictsTest&fail_tag=all&name=TablegroupFKDelete&platform=linux

seems mostly failing in release

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8757]: https://yugabyte.atlassian.net/browse/DB-8757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
Closing this issue as this test has been passing now across all build types.
