### ISSUE TITLE
Intermittent bad behavior when running two plpgsql procs concurrently and a serialization error occurs.

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#1983]
The tests were done on macOS Mojave Version 10.14.6.

**Preamble**

You need to accept that a plpgsql proc written as follows is written correctly and that the behavior is reliable. It relies on a table created with `create table t(n integer)`.
```
create or replace procedure p2()
  language plpgsql
as $$
  declare
    levl_1 varchar(20);
    levl_2 varchar(20);
  begin
    -- This "rollback" is critical.
    -- Else "SET TRANSACTION ISOLATION LEVEL must be called before any query".
    rollback;

    set transaction isolation level repeatable read;
    show transaction isolation level into levl_1;
    insert into t(n) values(17);
    rollback;

    set transaction isolation level serializable;
    show transaction isolation level into levl_2;
    insert into t(n) values(42);
    commit;

    raise notice 'isolation level #1: %', levl_1;
    raise notice 'isolation level #2: %', levl_2;
  end;
$$;
```
I've run it in both PostgreSQL and YugaByte DB. It behaves the same in each env. It must be run with `AUTOCOMMIT on`. This might seem paradoxical. But experts from the PostgreSQL community promise me that doing this is expected and proper. It outputs this:
```
NOTICE:  isolation level #1: repeatable read
NOTICE:  isolation level #2: serializable
```
And then `select n from t order by n` shows this:
```
 n  
----
 42
```
In others, `p2()` executed two separate transactions after the initial rollback. The first was done with `repeatable read` isolation level—and it rolled back the `17` that it inserted. And the second was done with `serializable` isolation level and it committed the `42` that it inserted.

**The substantive problem**

I rely on a table created and populated thus:
```
create table marbles(
  pk integer
    constraint t_pk primary key,
  color text
    constraint t_c1_nn not null
    constraint t_c1_chk check(color in ('black', 'white')));
insert into marbles(pk, color) values
  (1, 'black'),
  (2, 'white');
```
I'm using this proc:
```
create or replace procedure set_marbles_to_black()
  language plpgsql
as $$
declare
  one_second constant interval  not null := interval '1 second';
  trunc_now  constant timestamp not null := date_trunc('minute', clock_timestamp());
  t1         constant timestamp not null := trunc_now + 65*one_second;
  t2         constant timestamp not null := trunc_now + 75*one_second;
begin
  rollback;
  set transaction isolation level serializable;
  call sleep_until(t1);
  update marbles set color = 'black' where color = 'white';
  call sleep_until(t2);
  commit;
end;
$$;
```
and a partner `set_marbles_to_white()` that waits for 70 seconds before doing its `update marbles set color = 'white' where color = 'black'` and for 80 seconds before doing its `commit`. The idea is that the `update` and the `commit` commands from the two sessions are nicely interleaved at 5 second intervals to provoke a serialization error.

The implementation of `sleep_until()` is obvious. You can read it in the attached `Plpgsql_Two_Session_Correctness_Demo_Using_Serializable.zip`. Unzip it and run `cr_concurrent_procs.sql` to do the setup. At the end it prompts you to call `set_marbles_to_black()` in one session and to call `set_marbles_to_white()` in a second session, doing your best to start them immediately one after the other.

The outcome is always well behaved using PostgreSQL Version 11.2. One call finishes without error and the other reports the _"cannot serialize"_ error from the `commit` statement. Of course, the final state of the table is the same in both sessions and it reflects the `update` done by the session that didn't error.

The outcome is sometimes well-behaved using YugaByte DB Version 1.3.0. There's a subtle difference w.r.t. PostgreSQL in that the serialization error occors on the `update` attempt rather than the `commit` attempt, and the error is _“Operation failed. Try again.: Conflicts with higher priority transaction”_. This difference is understood and is inessential. After this outcome, the state can be observed with `select` in each session without error.

However, in about 50% of the test runs, the YugaByte DB is behavior bad as follows. This error is reported:
```
ERROR:  Error during commit: Operation expired: Transaction expired
CONTEXT:  PL/pgSQL function set_marbles_to_black() line 13 at COMMIT
```
and then a `select` in the session that suffered the error causes this:
```
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```
Of course, this "cannot" happen when `AUTOCOMMIT` is `on`.

[Plpgsql_Two_Session_Correctness_Demo_Using_Serializable.zip](https://github.com/YugaByte/yugabyte-db/files/3474831/Plpgsql_Two_Session_Correctness_Demo_Using_Serializable.zip)

**Comment by ndeodhar** [comment]
This is probably related to how we handle and reset postgres commit status in the case of the error `ERROR:  Error during commit: Operation expired: Transaction expired`.

**Comment by ndeodhar** [comment]
This seems to have been fixed and is no longer reproducible. Tried it multiple times and saw the two errors mentioned above. The `select` statement after both worked as expected.

Example 1:
```
yugabyte=# call set_marbles_to_black();
ERROR:  Operation expired: Transaction expired or aborted by a conflict: 40001
yugabyte=# select pk, color from marbles order by pk;
 pk | color 
----+-------
  1 | white
  2 | white
(2 rows)
```

Example 2:
```
yugabyte=# call set_marbles_to_white();
ERROR:  Operation failed. Try again.: 4f3cb47d-282f-4839-b4c8-f913e0278c9b Conflicts with higher priority transaction: f92394f8-2675-4b81-8cef-af27fc05c63d
yugabyte=# select pk, color from marbles order by pk;
 pk | color 
----+-------
  1 | black
  2 | black
(2 rows)
```
