### ISSUE TITLE
[DocDB] Better drive selection during tablet creation

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#19846]
Jira Link: [DB-8787](https://yugabyte.atlassian.net/browse/DB-8787)
### Description

Our drive selection for tablets tries to load balance across drives per table. However, in doing so, it goes through the drives in a deterministic order. Thus, amongst the lightly loaded drives, the first one always gets picked. 

This may be more severe with automatic-tablet-splitting where because initially the number of tablets created is low, they would all land up on the first few drives. We could do a better job at these assignments.

We could 
 a ) randomize the selection of the drive, amongst ones that are equally loaded. or
 b)  use the total number of tablets assigned to a drive (across all tables) to break ties,  so we can even have some worst-case guarantees that the tablets are evenly distributed.
 
 This should allow us to use the available disk bandwidth across disks better while remote-bootstrapping multiple tablets.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8787]: https://yugabyte.atlassian.net/browse/DB-8787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
This issue impacts clusters that have automatic_tablet_splitting on by default - 2.18 onwards, so Amit and I discussed that we should backport this to 2.18, 2.20.
