### ISSUE TITLE
Beta or Alpha Version of Change Data Capture

### ISSUE THREAD

**Issue by fabiocmazzo** [yugabyte/yugabyte-db#1987]
Jira Link: [DB-4720](https://yugabyte.atlassian.net/browse/DB-4720)
Hello, 

    Are there any Alpha or Beta versions that support Change Data Capture already?
Even if I have to compile? I am starting a project that should go into production only at the end of the year, and already having these features (even with problems) during development would be great.

Thank you very much,

**Comment by ndeodhar** [comment]
Hi @fabiocmazzo,
This feature is in the initial stages of development and we hope to have a beta version that you can try by first week of September. In the meantime, I can point you to some docs and code to help you get started:

CDC design: https://github.com/YugaByte/yugabyte-db/blob/master/architecture/design/docdb-change-data-capture.md
2DC design (which uses CDC with the sink being a second YB data center): https://github.com/YugaByte/yugabyte-db/blob/master/architecture/design/multi-region-2DC-deployment.md

Code samples:
https://github.com/YugaByte/yugabyte-db/tree/master/src/yb/cdc
https://github.com/YugaByte/yugabyte-db/tree/master/ent/src/yb/cdc

Sample integration test:
https://github.com/YugaByte/yugabyte-db/blob/master/ent/src/yb/integration-tests/cdc_service-txn-test.cc

You can track on-going work with this:
https://github.com/YugaByte/yugabyte-db/projects/6?card_filter_query=label%3Aarea%2Fcdc

Hope this helps!
