### ISSUE TITLE
[DocDB] Repro / RCA for hung drop database command when CDC streams are active on a database

### ISSUE THREAD

**Issue by druzac** [yugabyte/yugabyte-db#19879]
Jira Link: [DB-8822](https://yugabyte.atlassian.net/browse/DB-8822)
### Description

A customer ran `ysqlsh# drop database` on a YSQL database with CDC streams configured. The command timed out, and subsequent attempts to drop the database failed. On the yb-master side the namespace was stuck in the `DELETING` state. This state is transient and the async job which tries to delete a database should terminate in a finite period of time, updating the namespace state to `DELETED` if the deletion was successful and `FAILED` if it was not.

See CE-257 for logs and additional information.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8822]: https://yugabyte.atlassian.net/browse/DB-8822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by druzac** [comment]
Calling the `DeleteNamespace` RPC on a YSQL db w/ a namespace-level CDC stream configured on the db reliably deadlocks the background thread running `CatalogManager::DeleteYsqlDatabaseAsync()`. The only way to avoid this deadlock is if the number of tables in the db is 1 or less. The thread deadlocks with itself. Stack trace:

```
    @        0x11f307243  yb::RWCLock::WriteLock()
    @        0x106f4393b  yb::CowObject<>::StartMutation()
    @        0x106f4390f  yb::CowWriteLock<>::CowWriteLock()
    @        0x106f438d3  yb::CowWriteLock<>::CowWriteLock()
    @        0x106f43803  yb::master::MetadataCowWrapper<>::LockForWrite()
    @        0x10736e3db  yb::master::CatalogManager::MarkCDCStreamsForMetadataCleanup()
    @        0x10736ebc3  yb::master::CatalogManager::DeleteCDCStreamsMetadataForTables()
    @        0x106d3398f  yb::master::CatalogManager::DeleteYsqlDBTables()
    @        0x106d2d347  yb::master::CatalogManager::DeleteYsqlDatabaseAsync()
```

The `DeleteCDCStreamsMetadataForTables` and `MarkCDCStreamsForMetadataCleanup` functions are broken. `DeleteCDCStreamsMetadataForTables` computes a vector of streams for `MarkCDCStreamsForMetadataCleanup` to clean up, but this vector contains duplicates. Then `MarkCDCStreamsForMetadataCleanup` tries to acquire the write locks for all streams in a loop, but since the loop contains duplicates and our COW locks are not re-entrant, the function deadlocks itself.

**Comment by dr0pdb** [comment]
Reopening for backports
