### ISSUE TITLE
[DocDB] style: rename AsyncClientInitialiser to AsyncClientInitializer

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#19920]
Jira Link: [DB-8863](https://yugabyte.atlassian.net/browse/DB-8863)
### Description

There's already

- async_initializer.cc
- MakeClientInitializer

so "AsyncClientInitialiser" using an 's' is off.  Change it to 'z'.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8863]: https://yugabyte.atlassian.net/browse/DB-8863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by maximilian0101** [comment]
Hello! I would like to work on this issue. Where in the docs can I find the mistake?

**Comment by davixiao** [comment]
Apologies, didn't notice Max's comment. Feel free to disregard my PR if Max ends up making his own!

**Comment by jasonyb** [comment]
I'm not going to throw away already-done work, so I will review @davixiao's PR.  Thank you both.
