### ISSUE TITLE
[DocDB] pg_locks result set could cause OOM on pg process

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#19934]
Jira Link: [DB-8892](https://yugabyte.atlassian.net/browse/DB-8892)
### Description

When we execute something like 
```
insert into t(k, v) select i, i from generate_series(1, 1000000)  i;
```
and query `pg_locks` simultaneously, we could end up seeing lots of rows. In one specific reported instance, the below returned about 3K+ rows (all corresponding to the internal transaction that the above `insert` creates).
```
select * from pg_locks;
```

Since we currently limit the output only based on the below,
i. transaction age 
ii. total number of transactions involved in the locks output 

It is possible that we could return large number of results corresponding to a single transaction alone. 

Seems like this shouldn't be a problem in practice, but need to check if it has the capability to cause OOM issues. If so, we need to look at restricting the results (returned lock count) of a specific transaction to a default value, and only return the full results when explicitly queried for.

cc: @Karvy-yb @shis

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8892]: https://yugabyte.atlassian.net/browse/DB-8892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@pkj415 , @basavaraj29 , Can we track the backports for this?
