### ISSUE TITLE
[DocDB] Exclude details of timeout error when timing out from wait-queue while trying to re-acquire shared in-memory locks 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#19947]
Jira Link: [DB-8911](https://yugabyte.atlassian.net/browse/DB-8911)
### Description

We currently concatenate the below message to the main error message. We're unsure if we should display this to the client, considering that the error content can be quite lengthy.

```
key:  intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A31343630320000 intent_types: [kWeakRead, kWeakWrite] },
```

`
Errors from tablet servers: [Operation failed. Try again (yb/docdb/lock_batch.cc:42): Flush: Failed to obtain locks until deadline: 33135.898s, batch: [{ key:  intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A31343630320000 intent_types: [kWeakRead, kWeakWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438 382D3561663165623834386433363A3134363032000021214A80 intent_types: [kStrongRead, kStrongWrite] }, { key: 4755555362653865663463622D656337322D343637392D613438382D3561663165623834386433363A3135313031380000 intent_types: [kWeakRead, kWeakWrite] }, { key:  . . .
.
.
`

When we explicitly set a flag to skip printing the locks in the error messages, here's what wee see in the postgres logs.

```
yb-dev-ssharma-test-source10-n1/tserver/logs/postgresql-2023-09-08_213752.log.gz:2023-09-08 21:53:22.577 UTC [252366] ERROR:  Flush: Failed to obtain locks until deadline: 13578.348s: . Errors from tablet servers: [Operation failed. Try again (yb/docdb/lock_batch.cc:42): Flush: Failed to obtain locks until deadline: 13578.348s]
yb-dev-ssharma-test-source10-n1/tserver/logs/postgresql-2023-09-08_213752.log.gz-2023-09-08 21:53:22.577 UTC [252366] STATEMENT:  UPDATE tbl_no_explicit_lock SET V1='be8ef4cb-ec72-4679-a488-5af1eb848d36:403146' WHERE k like 'e%' or k like 'v%' or k like 'm%' or k like 'c%' or k like 'l%' or k like 'k%' or k like 't%' or k like 'h%' or k like 'w%' or k like 'x%' or k like 'g%' or k like 'e%' or k like 't%' or k like 's%' or k like 'e%' or k like 'z%' or k like 'y%' or k like 'h%' or k like 'e%' or k like 'y%' or k like 'o%' or k like 'c%' or k like 'g%' or k like 'h%' or k like 'd%' or k like 'c%' or k like 'o%' or k like 'd%' or k like 'c%' or k like 'm%' or k like 's%' or k like 'a%' or k like 'v%' or k like 'e%' or k like 'x%' or k like 't%' or k like 'm%' or k like 'd%' or k like 's%' or k like 'u%' or k like 'g%' or k like 'r%' or k like 'u%' or k like 'e%' or k like 'v%' or k like 'd%' or k like 'u%' or k like 'd%' or k like 'n%' or k like 'c%' or k like 'c%' or k like 'k%' or k like 'a%' or k like 'n%' or k like 'o%' or k like 'j%' or k like 'm%' or k like 'l%' or k like 'u%' or k like 'x%' or k like 'y%' or k like 'm%' or k like 'z%' or k like 'f%' or k like 'g%' or k like 'd%' or k like 'b%' or k like 'e%' or k like 't%' or k like 'u%' or k like 'd%' or k like 'l%' or k like 'f%' or k like 't%' or k like 'm%' or k like 't%' or k like 'a%' or k like 'p%' or k like 'k%' or k like 'u%' or k like 'g%' or k like 'a%' or k like 'o%' or k like 'g%' or k like 'd%' or k like 's%' or k like 's%' or k like 'x%' or k like 'z%' or k like 'x%' or k like 'v%' or k like 'c%' or k like 'm%' or k like 'g%' or k like 'y%' or k like 'q%' or k like 'r%' or k like 'e%' or k like 'w%' or k like 'a%' 
```

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8911]: https://yugabyte.atlassian.net/browse/DB-8911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
I don't see anything specific to wait-queues here. when `FLAGS_dump_lock_keys` is set, it is intended that we dump the keys that the request is attempting to lock. 

That being said, the frequency with which we see this error could be a bit higher in case of a contentious workload due to https://github.com/yugabyte/yugabyte-db/issues/19032. Once it is resolved, we would only see the above error when the request times out past the actual connection deadline. Note that we would still dump the locks based on the flag value.
