### ISSUE TITLE
[YSQL] "Remaining connection slots reserved..." encountered far below connection limit with no killed processes

### ISSUE THREAD

**Issue by timothy-e** [yugabyte/yugabyte-db#19944]
Jira Link: [DB-8908](https://yugabyte.atlassian.net/browse/DB-8908)
### Description

There were no terminated backends reported by the postmaster, so no known chance of corruption like some of the other cases. 

A third of the connections were terminated with `FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0`
A third of the connections were terminated with `FATAL:  remaining connection slots are reserved for non-replication superuser connections`

The max connections issue may be related to the large number of FATALs happening during process initialization? 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8908]: https://yugabyte.atlassian.net/browse/DB-8908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
Later investigation found, this was related to OOM, so closing this issue.
