### ISSUE TITLE
multiple HDDs I/O

### ISSUE THREAD

**Issue by shreklei** [yugabyte/yugabyte-db#200]
1) If there are multiple HDDs per node, are the tablets for a given table evenly distributed across different HDDs on different nodes?
2) Does a table have only one WAL or one WAL for each tablet?
3) Is there only one RocksDB instance for a node? Does RocksDB manage multiple local HDDs?

**Comment by kmuthukk** [comment]
hi @shreklei 

Excellent question.

First, one clarification - we are primarily optimized to run on SSDs (and not HDDs).

1. Yes, we do per-table load balancing. And we distribute the tablets of a table uniformly across the multiple disks on the node. We do not require a software/hardware raid across these disks, and YugaByte automatically handles multi-disk configuration well.

2. There is a WAL per tablet. The RAFT-log itself servers the purpose of the WAL. The RAFT-log (WAL) of the tablets of a table are also uniformly balanced across the multiple disks of a node. Note:

> YugaByte is a distributed database that uses Raft for replication. Changes to the distributed system are already recorded/journalled as part of Raft logs. When a change is accepted by a majority of peers, it is applied to each tablet peer’s DocDB, but the additional WAL mechanism in RocksDB (under DocDB) is unnecessary and adds overhead. For correctness, in addition to disabling the WAL mechanism in RocksDB, YugaByte tracks the Raft “sequence id” up to which data has been flushed from RocksDB’s memtables to SSTable files. This ensures that we can correctly garbage collect the Raft WAL logs as well as replay the minimal number of records from Raft WAL logs on a server crash or restart.

3. There is one DocDB (which is YugaByte's highly customized version of RocksDB) instance per tablet. The YugaByte tablet-server layer manages what goes on what disk (i.e. it manages multiple disks), and not the DocDB/RocksDB sub-component.

To read more about YugaByte's DocDB (key to document store) subcomponent see: https://docs.yugabyte.com/latest/architecture/concepts/persistence/

**Comment by shreklei** [comment]
If a DocDB serves a Tablet, then a node with 1000 or 10000 Tablets is not a strange phenomenon, does it mean that there will be 1000 or 10000 DocDB instances?

If so, it will be a disaster for memory and CPU resources.

**Comment by kmuthukk** [comment]
@shreklei  - the number of tablets being this high should not be a very common phenomenon. Unless you have have 100s or 1000s of tables. You can also control the initial number of tablets a table is created with, and there isn't much advantage of setting this number so high that you end up with 1000s of tablets per node. Each YugaByte tablet can get pretty big. Another reason you don't want too many tablets is because each tablet has its own RAFT group, and 10000s of RAFT groups add overhead-- and again, you don't gain much by micro-splitting your tables into too many small tablets. 

Having said that, YugaByte does keep the overhead of each tablet very low. Resources such as block cache, compaction threads, total memstore resources etc. are shared across all the DocDB instances. Read more here:  https://docs.yugabyte.com/latest/architecture/concepts/persistence/. Copy pasting a few relevant points:

> Server-global block cache across multiple DocDB instances: A shared block cache is used across the DocDB/RocksDB instances of all the tablets hosted by a YB-TServer. This maximizes the use of memory resources, and avoids creating silos of cache that each need to be sized accurately for different user tables.

> Server-global memstore limits across multiple DocDB instances: While per-memstore flush sizes can be configured, in practice, because the number of memstores may change over time as users create new tables, or tablets of a table move between servers, we have enhanced the storage engine to enforce a global memstore threshold. When such a threshold is reached, selection of which memstore to flush takes into account what memstores carry the oldest records (determined using hybrid timestamps) and therefore are holding up Raft logs and preventing them from being garbage collected.

**Comment by dlessner** [comment]
Can you add more drives to the docker image or does it need to be redone?

**Comment by kmuthukk** [comment]
cc: @rkarthik007 , @Arnav15, @ramkumarvs  -- is the number of data drives presented to the yb-tserver or yb-master pods already configurable in the Kubernetes based install?

**Comment by rkarthik007** [comment]
@dlessner - yes the number of disks are configurable. You have to manually edit the yaml files, but I can add instructions if you can use our helm chart. We have tested creating clusters from 1 to 5 disks of varying sizes attached (of course the underlying IaaS should be able to support the sizes for the pv).
