### ISSUE TITLE
support Arch Linux

### ISSUE THREAD

**Issue by sain801028** [yugabyte/yugabyte-db#2000]
support Arch Linux

**Comment by ttyusupov** [comment]
Hi @sain801028 , could you, please, add more details to the ticket description?

**Comment by sain801028** [comment]
![螢幕快照_2019-08-10_21-35-09](https://user-images.githubusercontent.com/17377422/62822476-e6ac3c00-bbb6-11e9-83b7-a5b2ce30af9c.png)

**Comment by bmatican** [comment]
Hello @sain801028 and thank you for trying out yugabyte! It looks like the tablet server is dead. This might be related to a failure to bind on one of the ports we require for communication. Could you please share the following 2 files:
- `/home/sain/yugabyte-data/node-1/disk-1/tserver.err`
- `/home/sain/yugabyte-data/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO`

Thank you.

**Comment by sain801028** [comment]
yb-tserver.ERROR

Log file created at: 2019/08/10 13:32:51
Running on machine: sain-pc
Application fingerprint: version 1.3.1.0 build 16 revision f10e23d319a5e5df008467d19ebab95ce631a977 build_type RELEASE built at 31 Jul 2019 06:43:06 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0810 13:32:51.597227 16107 main_util.cc:22] Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:143): /home/sain/桌面/yugabyte-1.3.1.0/postgres/bin/initdb failed with exit code 256

============
tserver.err

In YugaByte DB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/YugaByte/yugabyte-db/issues/1557initdb: invalid locale name "en_US.UTF-8"

**Comment by bmatican** [comment]
@sain801028 Do you also have a `yb-tserver.INFO` file? Also, since that error seems to be pg related, there should also be, in the `tserver/logs/` directory, a postgres related log file, if you don't mind attaching that too.

**Comment by sain801028** [comment]
yb-tserver.INFO

Log file created at: 2019/08/10 13:32:51
Running on machine: sain-pc
Application fingerprint: version 1.3.1.0 build 16 revision f10e23d319a5e5df008467d19ebab95ce631a977 build_type RELEASE built at 31 Jul 2019 06:43:06 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0810 13:32:51.460187 16107 tablet_server_main.cc:134] NumCPUs determined to be: 4
I0810 13:32:51.460391 16107 tablet_server_main.cc:144] Setting tcmalloc max thread cache bytes to: 268435456
I0810 13:32:51.460614 16107 mem_tracker.cc:250] MemTracker: hard memory limit is 13.213874 GB
I0810 13:32:51.460624 16107 mem_tracker.cc:252] MemTracker: soft memory limit is 11.231793 GB
I0810 13:32:51.461938 16107 shared_mem.cc:133] Using memfd_create as a shared memory provider
I0810 13:32:51.462033 16107 encrypted_file_factory.cc:66] Created encrypted file factory
E0810 13:32:51.597227 16107 main_util.cc:22] Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:143): /home/sain/桌面/yugabyte-1.3.1.0/postgres/bin/initdb failed with exit code 256
I0810 13:32:51.597482 16107 tablet_server.cc:323] TabletServer shutting down...
I0810 13:32:51.597494 16107 tablet_server.cc:343] TabletServer shut down complete. Bye!

**Comment by ttyusupov** [comment]
HI @sain801028 , I saw you've closed the ticket, how did you resolve the issue?

**Comment by sain801028** [comment]
I didn't solve this problem. I didn't use your tools inside the company, but later I discussed using your tools, but this problem still exists. I am thinking about whether my system language setting problem.

**Comment by bmatican** [comment]
@sain801028 based on the previous logging:
> In YugaByte DB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/YugaByte/yugabyte-db/issues/1557
> initdb: invalid locale name "en_US.UTF-8"

You are correct, it is likely to do with the locale setting! That log line references: https://github.com/YugaByte/yugabyte-db/issues/1557

cc @m-iancu @ndeodhar

**Comment by ndeodhar** [comment]
@sain801028 Can you try the suggestions mentioned here: https://bbs.archlinux.org/viewtopic.php?id=203629:
Uncomment or ensure that `/etc/locale.gen` has `en_US.UTF-8` and then run `locale-gen`.

Some other links that may help:
https://wiki.archlinux.org/index.php/Locale
https://stackoverflow.com/questions/50746147/postgresqls-initdb-fails-with-invalid-locale-settings-check-lang-and-lc-e

**Comment by sain801028** [comment]
I later modified the system into
en_US.UTF-8 , can run normally in YugaByte DB 2.0.0
