### ISSUE TITLE
[DocDB][Read Committed] Multiple Transaction Aborts during Deadlock may lead to 'Transaction Metadata Missing' error

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20016]
Jira Link: [DB-8983](https://yugabyte.atlassian.net/browse/DB-8983)
### Description

Tried on version: **2.21.0.0-b238**

Multiple Transaction Aborts during Deadlock may lead to 'Transaction Metadata Missing' error in some of the tranaction, while reporting such error we should make sure that we report deadlock specific errors

T1: `0a4967de-f902-47bb-b6e2-f22e89b35ded`
T2: `36547a99-60f8-4c43-bf90-568a308eabe8`

T1 got aborted with a deadlock error:
`
2023-11-22 11:21:31,055: DETAIL:  Transaction 0a4967de-f902-47bb-b6e2-f22e89b35ded aborted due to a deadlock.
0a4967de-f902-47bb-b6e2-f22e89b35ded -> 36547a99-60f8-4c43-bf90-568a308eabe8 -> 0a4967de-f902-47bb-b6e2-f22e89b35ded : kDeadlock
`

T2 got aborted with Transaction metadata missing error:
`
2023-11-22 11:21:32,066 psycopg2.errors.SerializationFailure: Transaction metadata missing: 36547a99-60f8-4c43-bf90-568a308eabe8, looks like it was just aborted
`

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8983]: https://yugabyte.atlassian.net/browse/DB-8983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
commit https://github.com/yugabyte/yugabyte-db/commit/2195ad47141323392db9000f8e909fed87538cdc
