### ISSUE TITLE
add support mysql sql query language  just like pg  sql query 

### ISSUE THREAD

**Issue by Bmixo** [yugabyte/yugabyte-db#20036]
### Description

i am thinking this project is written in C++, i wonder it can support MySQL SQL like pg SQL,
Because there are already tidb and crdb, I don’t feel that there is any bright spot in having another database. If it can support two database query languages ​​​​at the same time, I feel that this will be a selling point for ybdb. I feel that supporting an incomplete mysql protocol is not for c++. It’s a difficult thing. Even if you simply execute the mysql command in pg sql, it will be compatible with some functions and facilitate migration. At the same time, we also hope to support a script-based language and programming query language similar to mongodb. Mongodb uses A language similar to javascript, maybe ybdb supports python script or lua query?

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
Hi @Bmixo 

Actually, the reverse of everything you've written is true. 

1. We support PostgreSQL reusing the same source code (no duplication)
2. Cockroachdb doesn't reuse the same source code, so they're re-creating the db (missing many features along the way)
3. Cockroachdb is not fully open source (see enterprise edition features) while we are.
4. Tidb isn't also reusing the source code of MySQL (say, like ndb cluster does)

There is no intention as of now to support MySQL protocol. You should investigate, and learn, that supporting the protocol & supporting the database for real are orders of magnitude of difference. The protocol is pretty simple relatively, but the features are hard and require multi-year effort.
