### ISSUE TITLE
[YSQL] publication for all tables may cause ysql upgrade to fail

### ISSUE THREAD

**Issue by myang2021** [yugabyte/yugabyte-db#20085]
Jira Link: [DB-9035](https://yugabyte.atlassian.net/browse/DB-9035)
### Description

This is a follow up issue for #19965 , the relevant code is in function `CheckCmdReplicaIdentity`:
```
    /*
     * In per-database catalog version mode at the end of a global-impact
     * DDL statement, we internally call yb_increment_all_db_catalog_versions
     * which sets yb_non_ddl_txn_for_sys_tables_allowed to true in order to
     * update pg_yb_catalog_version table. More generally, a user may want
     * to manually set yb_non_ddl_txn_for_sys_tables_allowed to true and then
     * perform an update on pg_yb_catalog_version table to force catalog cache
     * refresh.
     * NOTE: we may need to allow more system tables in YB context.
     */
    if (IsYugaByteEnabled() &&
        yb_non_ddl_txn_for_sys_tables_allowed &&
        RelationGetRelid(rel) == YBCatalogVersionRelationId)
        return;
```
In #19965 , I made a special case for `pg_yb_catalog_version` table. However in YSQL migration scripts, we have similar situation such as:
```
  SET LOCAL yb_non_ddl_txn_for_sys_tables_allowed TO true;

  -- Add a column for stream ID in pg_get_replication_slots
  -- TODO: As a workaround for GHI #13500, we perform a delete + insert instead
  -- of an update into pg_proc. Restore to UPDATE once fixed.
  DELETE FROM pg_catalog.pg_proc WHERE proname = 'pg_get_replication_slots' AND
    pronamespace = 'pg_catalog'::regnamespace;
```
Let's say in a cluster where the user has executed:

```
    yugabyte=# CREATE PUBLICATION testpub_foralltables FOR ALL TABLES;
    CREATE PUBLICATION
```

Then when running the above YSQL migration command `DELETE` can fail because of `CheckCmdReplicaIdentity`. As I understand, in YSQL we use `pg_publication` table but repurpose it for YSQL replication which does not use the same mechanism as PG's replication. In such a case, I am wondering whether the PG logic in `CheckCmdReplicaIdentity` still applies in Yugabyte context. In other words, can we simplify the above special case code to:

```
    if (IsYugaByteEnabled())
        return;
```

Or a bit more conservatively:

```
    if (IsYugaByteEnabled() &&
        yb_non_ddl_txn_for_sys_tables_allowed)
        return;
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9035]: https://yugabyte.atlassian.net/browse/DB-9035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dr0pdb** [comment]
@myang2021 Thanks for filing.

The proposed change to disable the check seems safe to me because we don't use replica identity in YSQL. So the check doesn't apply to YSQL.

I'll make the change.
