### ISSUE TITLE
[YSQL] Microbenchmark Aggr queries shows regression on 2.21.0.0-b260

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#20098]
Jira Link: [DB-9041](https://yugabyte.atlassian.net/browse/DB-9041)
### Description

Between YB builds 2.21.0.0-b253 and 2.21.0.0-b260, there is a 10%-15% increase in avg latency observed for aggr workloads in microbenchmark tests. This is across different workloads :

For YB regular and YB colocated
AGGRG3_count_bigint_on_indexed (320ms to 370ms).
AGGRG1_count_bigint_non_indexed_column (320ms to 360ms)
AGGRG1_count_bigint_secondary_indexed_column (318-360ms)

Only in YB colocated :
AGGRG9_count_bigint_hash_secondary_indexed_column
AGGRG9_count_bigint_non_indexed_column
AGGRG9_count_bigint_range_secondary_indexed_column

Please refer page : http://perf.dev.yugabyte.com/plot-microbenchmark-yb/branch/master/50

Suspected commit that might have caused this : https://phorge.dev.yugabyte.com/D29129

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9041]: https://yugabyte.atlassian.net/browse/DB-9041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
False positive based on offline discussion.
