### ISSUE TITLE
Crash during flush triggered by memory monitor

### ISSUE THREAD

**Issue by ttyusupov** [YugaByte/yugabyte-db#2010]
From core file:
```
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal 11, Segmentation fault.
#0  GetSmallestFrontierLocked (this=<optimized out>) at ../../src/yb/rocksdb/db/memtable.h:354
354    ../../src/yb/rocksdb/db/memtable.h: No such file or directory.
```

```
  UserFrontierPtr GetSmallestFrontierLocked() const {
    std::lock_guard<SpinMutex> l(frontiers_mutex_);
354:    return frontiers_->Smallest().Clone(); 
  }
```

Here `frontiers_` maybe not yet initialized. `GetSmallestFrontierLocked` is only called from code path flushing when we hit global memtable memory limit and there is a check above that call for `!mem->IsEmpty()`, so memtable shouldn’t be empty. 

Checked the core file and confirmed that there was non-empty memtable for intents DB with not initialized frontiers.

By design `frontiers_` should be initialized when memtable is not empty, so there is some bug in `frontiers_` initialization which leads to crash together with missed check for `frontiers_` to be initialized inside `GetSmallestFrontierLocked()`.

**Comment by spolitov** [comment]
This bug is related to 1.2.
Remove intents of aborted transaction could result in non empty memtable of intents DB.
D6860 (#1240) changed logic of remove intents, so this issue does not exist in 1.3.
