### ISSUE TITLE
[DocDB] Remove noisy trace - "No active snapshot"

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#20111]
Jira Link: [DB-9050](https://yugabyte.atlassian.net/browse/DB-9050)
### Description

When a CreateSnapshot response is received on the catalog manager, if a non-transactional snapshot is not in progress, then the following message is logged.

`W1129 xxxxx catalog_manager_ent.cc:2920] No active snapshot:`

This unfortunately happens for every tablet during a transactional snapshot and therefore is a lot of noise, especially if the number of tablets is high.

This trace should be removed completely for transactional snapshots.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9050]: https://yugabyte.atlassian.net/browse/DB-9050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by eafdeafd** [comment]
Hi, I'd like to take this issue. I'm new to yugabyte so is there any more information I could get - such as how to reproduce, where the trace is, etc.? Thanks!

**Comment by eafdeafd** [comment]
What would be the correct way to check if the snapshot is transactional or non transactional? It seems like there's no meta data I can use besides FindPtrOrNull(non_txn_snapshot_ids_map_, current_snapshot_id_) to determine whether the snapshot is non-txn or not. But, if it's empty, it'll always return a null so there's no good way to distinguish txn vs. non txn snapshot

**Comment by lingamsandeep** [comment]
@eafdeafd - In this specific case, I would suggest removing that log message completely regardless of whether its transactional or non-transactional snapshot. The log message by itself does not add any value. The current_snapshot_id_ being empty is an indication that it is a non-transactional snapshot.

**Comment by eafdeafd** [comment]
@lingamsandeep Cool thanks - simple enough. Pushed a PR for it.

**Comment by SrivastavaAnubhav** [comment]
Seems like this is fixed
