### ISSUE TITLE
[DocDB] Use RPC start time of waiters to generate pg_locks wait_time

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#20120]
Jira Link: [DB-9056](https://yugabyte.atlassian.net/browse/DB-9056)
### Description

Once https://github.com/yugabyte/yugabyte-db/issues/18195 lands, we would start seeing single shard waiters as part of `pg_locks`. In general, we have some mechanisms which cause waiters to re-enter the wait queue. We currently use wait queue entry time to generate pg_locks wait_time. We should instead use `start_time_micros` from the write query

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9056]: https://yugabyte.atlassian.net/browse/DB-9056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
i think this would be resolved with [#16286](https://github.com/yugabyte/yugabyte-db/issues/16286)

**Comment by robertsami** [comment]
if we removed all motivating issues for retrying conflict resolution, this would be solved:
https://github.com/yugabyte/yugabyte-db/issues/17009
https://github.com/yugabyte/yugabyte-db/issues/16286
https://github.com/yugabyte/yugabyte-db/issues/16389

OTOH, we should consider instead just using statement start time from pg (propagate from query layer with tserver RPCs) and display that in pg_locks
