### ISSUE TITLE
[YSQL] Remove retries for timed out queries

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#2012]
In YSQL, when a query times out, client retries that query. For single-insert statements, since we don't follow distributed transactions, the original request can succeed and subsequent re-tried requests can end up throwing "unique constraint violation" type of errors.

With upcoming changes to skip distributed transaction path for updates, we might end up hitting this issue more frequently.

We should avoid retrying timed out requests in the PG client layer.

**Comment by kmuthukk** [comment]
@ndeodhar 

When you say: "We should avoid retrying timed out requests in the client."

By "client", are you referring to the PG layer that talks to DocDB or you mean the application program/client?  If the former, then I believe we have a mechanism to catch duplicate requests and make the subsequent request a no-op.

**Comment by ndeodhar** [comment]
@kmuthukk I'm referring to the PG layer. Will need to look into the existing mechanism - it doesn't seem to work as expected for YSQL.
