### ISSUE TITLE
[VirtualBox] Error while creating a local cluster on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by ntilotta** [YugaByte/yugabyte-db#2013]
I got this error while trying to create a local cluster (Virtualbox) same problem with the command: _./bin/yb-ctl --rf 3 create_

> dbuser@db0:~/yugabyte-1.3.1.0$ python --version
Python 2.7.15+

> dbuser@db0:~/yugabyte-1.3.1.0$ ./bin/yb-ctl create
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1874, in <module>
    control.run()
  File "./bin/yb-ctl", line 1851, in run
    self.args.func()
  File "./bin/yb-ctl", line 1641, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1487, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
Viewing file /tmp/tmpJf7_ZB:
2019-08-10 15:55:50,727 INFO: Starting master-1 with:
/home/dbuser/yugabyte-1.3.1.0/bin/yb-master --fs_data_dirs "/home/dbuser/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/dbuser/yugabyte-1.3.1.0 --webserver_doc_root "/home/dbuser/yugabyte-1.3.1.0/www" --replication_factor=1 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100 --use_initial_sys_catalog_snapshot >"/home/dbuser/yugabyte-data/node-1/disk-1/master.out" 2>"/home/dbuser/yugabyte-data/node-1/disk-1/master.err" &
2019-08-10 15:55:50,734 INFO: Starting tserver-1 with:
/home/dbuser/yugabyte-1.3.1.0/bin/yb-tserver --fs_data_dirs "/home/dbuser/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/dbuser/yugabyte-1.3.1.0 --webserver_doc_root "/home/dbuser/yugabyte-1.3.1.0/www" --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1:5433 >"/home/dbuser/yugabyte-data/node-1/disk-1/tserver.out" 2>"/home/dbuser/yugabyte-data/node-1/disk-1/tserver.err" &
2019-08-10 15:55:50,735 INFO: Waiting for master and tserver processes to come up.
2019-08-10 15:55:50,748 INFO: Waiting for master leader election and tablet server registration.
2019-08-10 15:56:52,238 ERROR: Failed waiting for None tservers, got None
^^^ Encountered errors ^^^

**Comment by ramkumarvs** [comment]
@ntilotta I am assuming you brought up Ubuntu on a virtualbox/docker. And tried to run `./bin/yb-ctl --rf 3 create`. That command is supposed to be run on a VM not a VirtualBox. If your goal is to test it inside a VirtualBox environment, I recommend you run RF=1 instead for RF=3. 

This is how I would bring it up
`docker run --name demo -it ubuntu`
`apt update && apt install python2.7 python-pip wget -y`
`wget https://downloads.yugabyte.com/yugabyte-1.3.1.0-linux.tar.gz`
`tar xvfz yugabyte-1.3.1.0-linux.tar.gz && cd yugabyte-1.3.1.0/`
`./bin/post_install.sh`
`./bin/yb-ctl create`

Let me know if that helps. Again if your goal is to run in a docker environment, my recommendation would be to run `yb-docker-ctl` instead of `yb-ctl` the documentation for that is here.
https://docs.yugabyte.com/latest/quick-start/create-local-cluster/#docker

**Comment by ntilotta** [comment]
@ramkumarvs thank you for your reply, as I wrote above, I have installed it on VirtualBox and tried to create a local cluster with RF=1, I will try to running it on docker, even if my goal was to avoid docker or install the cluster locally on my development machine.

I think that it should be able to running inside a VirtualBox environment too, I will leave this issue open.

**Comment by ntilotta** [comment]
> dbuser@db0:~/yugabyte$ ./yb-docker-ctl create --rf 1
> WARNING: No swap limit support
> docker run --name yb-master-n1 --hostname yb-master-n1 --privileged -p 7000:7000 --net yb-net --detach yugabytedb/yugabyte:latest /home/yugabyte/bin/yb-master --replication_factor=1 --master_addresses=yb-master-n1:7100 --rpc_bind_addresses=yb-master-n1:7100 --use_initial_sys_catalog_snapshot=true --fs_data_dirs=/mnt/disk0,/mnt/disk1 --yb_num_shards_per_tserver=2 --v=0
> Adding node yb-master-n1
> docker run --name yb-tserver-n1 --hostname yb-tserver-n1 --privileged -p 9000:9000 -p 9042:9042 -p 6379:6379 -p 5433:5433 --net yb-net --detach yugabytedb/yugabyte:latest /home/yugabyte/bin/yb-tserver --tserver_master_addrs=yb-master-n1:7100 --rpc_bind_addresses=yb-tserver-n1:9100 --memory_limit_hard_bytes=1073741824 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address yb-tserver-n1:5433 --fs_data_dirs=/mnt/disk0,/mnt/disk1 --yb_num_shards_per_tserver=2 --v=0
> Adding node yb-tserver-n1
> Timed out waiting for YugaByte clusters to come up. Please use --timeout_in_sec to increase timeout. Please also ensure that you have at least YugaByte version 1.1.2.0-b10.

**Comment by ntilotta** [comment]
@ramkumarvs thank you for your reply, apparently the problem (at least with docker instructions) is to increate the timeout with _./yb-docker-ctl create --timeout_in_sec 1000000_ so I presume the problem stills the same without involving docker.

**Comment by ntilotta** [comment]
@ramkumarvs thank you for your reply, apparently the problem (at least with docker instructions) is to increase the timeout with _**./yb-docker-ctl create --timeout_in_sec 1000000**_ so I presume the problem stills the same without involving docker.
