### ISSUE TITLE
[YCQL] Flaky tests org.yb.loadtest.TestReadReplica

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#20142]
Jira Link: [DB-9078](https://yugabyte.atlassian.net/browse/DB-9078)
### Description

Tests `org.yb.loadtest.TestReadReplica.readfromReadReplica` and `org.yb.loadtest.TestReadReplica.readfromReadReplicawithpreferredLeader` are constantly failing with the following pattern:
```
java.lang.AssertionError: expected:<0> but was:<17>
```

Tests have started failing from commit https://github.com/yugabyte/yugabyte-db/commit/53b14122007c48397ee196f52a7421e93c6c856c

Stability history [one](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=org.yb.loadtest.TestReadReplica&name=readfromReadReplica), [two](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=org.yb.loadtest.TestReadReplica&name=readfromReadReplicawithpreferredLeader).
Trends [one](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=org.yb.loadtest.TestReadReplica&name=readfromReadReplica), [two](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=org.yb.loadtest.TestReadReplica&name=readfromReadReplicawithpreferredLeader).

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9078]: https://yugabyte.atlassian.net/browse/DB-9078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@Sfurti-yb , This seems to be a regression from https://github.com/yugabyte/yugabyte-db/commit/53b14122007c48397ee196f52a7421e93c6c856c , per Anton's analysis. Can you fix the tests? Is this on your radar?

**Comment by Sfurti-yb** [comment]
@rthallamko3 yes this is on my radar, will analyse and fix the issue in the next week and will keep the ticket updated.
