### ISSUE TITLE
[question or feature request] CQL: what if additional indexes added after some INSERTs?

### ISSUE THREAD

**Issue by pashinin** [YugaByte/yugabyte-db#2019]
I was following this example https://github.com/YugaByte/yugabyte-db/issues/919#issuecomment-468923609

But I created secondary indexes **after** I inserted some data. And I was like: "ok, I'll wait, it will reindex it, fill it with data". Apparently that was a mistake - `cqlsh` always gave 0 rows.

Maybe a new index should work on existing data as well, not only on new INSERTs?

By the way thank you for this project!

**Comment by amitanandaiyer** [comment]
@pashinin  This feature is currently being worked on. 

It is being tracked in https://github.com/YugaByte/yugabyte-db/issues/448

I'll mark this as a duplicate.
