### ISSUE TITLE
Load balancer does not respect replication factor

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#202]
Reported by @amitanandaiyer.

Running on 
version <some_ip_address> build 12 revision ccc53917b899d341d81ceb28307acdd950ef14c6 build_type RELEASE built at 12 Apr 2018 15:27:17 UTC
server uuid 9935b5e2576545e2beca5bd80975f03f

Created a 4 node cluster with a redis table consisting of 32 tablets. Each server consisting of 24 tablets.

Upon removing one node (tserver stop) for 10 mins ... it was noted that the remaining nodes still had only 24 tablets. (no tablets were reassigned after the 5 min delay of considering the 4th node dead.)

Upon bringing back the dead node, it started getting some tablets. But instead of getting back to the original state with 24 tablets each. We are stuck with some tablets being under replicated.

Here are the relavant v=4 logs at the master leader:
I0413 22:59:52.834019 24054 cluster_balance.cc:295] Total running tablets: 87. Total overreplication: 0. Total starting tablets: 0. Wrong placement: 0. BlackListed: 0.
I0413 22:59:52.848403 24054 cluster_balance.cc:415] Cannot find any more tablets to move, under current constraints.
I0413 22:59:52.848428 24054 cluster_balance.cc:434] Table load: bc3c7c1c2f074dabb4a34abd10ae7c18:21 1a8cb19e6f6448739a470a78c46a87af:22 9935b5e2576545e2beca5bd80975f03f:22 cc57716677b84b71b5d172cd39578d7b:22

This seems to happen pretty consistently. Had run into a similar situation a few hours ago. that time the total number of tablets got stuck at 81 (20+20+20+21) instead of 96 (24 x 4).

**Comment by rahuldesirazu** [comment]
Fixed in 3cdeecf0778bb953a68f70e7d0f3ef04e8f92a3f.
