### ISSUE TITLE
YugaWare tables should count as system tables

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#2023]
Jira Link: [DB-2250](https://yugabyte.atlassian.net/browse/DB-2250)
Currently, when YugaWare starts up with YB as its backing database, we manually create a `system_platform` database to store its data. Tables created in this database should not count towards system tables so that the UI will show the proper number of user tables. An optional, but nice feature, would be if YSQL is initialized with a `system_platform` database pre-existing.

One solution @m-iancu proposed is creating a `yugaware` user where every table created by them would be a system table.

**Comment by ndeodhar** [comment]
We already have a notion of `system namespaces` which include namespaces like `system`, `system_schema`, `system_auth` etc. We can add `system_platform` to this list.

**Comment by sushantrmishra** [comment]
closing this issue as per comment https://github.com/yugabyte/yugabyte-db/issues/2023#issuecomment-530954723
