### ISSUE TITLE
[YSQL][ASH] Add session ID to the ASH metadata and view

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#20242]
Jira Link: [DB-9203](https://yugabyte.atlassian.net/browse/DB-9203)
### Description

- Session ID for the current session should be added while sending the metadata to the tserver. This will help in doing aggregations for the tserver wait events based on the session id of the client. 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9203]: https://yugabyte.atlassian.net/browse/DB-9203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pdvmoto** [comment]
From using ASH, I would suggest to add the PID of the calling process or possibly some other data that allows to find the process of the originator. 
to this end I've created : https://github.com/yugabyte/yugabyte-db/issues/23070
