### ISSUE TITLE
[doc] [YSQL] Interval datatype

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2026]
Jira Link: [DB-1760](https://yugabyte.atlassian.net/browse/DB-1760)
Add documentation for interval data type.

[DB-1760]: https://yugabyte.atlassian.net/browse/DB-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bllewell** [comment]
I fixed this doc issue a long time ago. (I didn't know that this doc issue existed. until the date of this comment.) I'm closing this issue with this comment.

See the section **[The interval data type](https://docs.yugabyte.com/preview/api/ysql/datatypes/type_datetime/date-time-data-types-semantics/type-interval/)**, It's a subsection under [Date and time data types and functionality](https://docs.yugabyte.com/preview/api/ysql/datatypes/type_datetime/) under [Data types](https://docs.yugabyte.com/preview/api/ysql/datatypes/).

The main bulk of the work was merged into "master" in the summer of 2021. See [PR #8397](https://github.com/yugabyte/yugabyte-db/pull/8397) and (many) others before it. Some minor bug fixes within [Date and time data types and functionality](https://docs.yugabyte.com/preview/api/ysql/datatypes/type_datetime/) have been made after publishing the content as the need has arisen.)
