### ISSUE TITLE
[YSQL] Cannot colocate hash partitioned table

### ISSUE THREAD

**Issue by KyleMaas** [yugabyte/yugabyte-db#20260]
Jira Link: [DB-9218](https://yugabyte.atlassian.net/browse/DB-9218)
### Description

I have a small dataset that of existing data and wanted to try colocation to see if it would help speed things up - reading about how it works, I'm pretty sure it would.  (My current cluster shows 339 tablet peers for a dataset which, when dumped to SQL, is <140MB.)  However, when I try to load data from my existing cluster onto a new one with `ysql_colocate_database_by_default` enabled, I get the following errors:

```
ERROR:  Invalid table definition: Error creating table (table name redacted) on the master: Cannot colocate hash partitioned table
```

As I understand it, from both of these:

https://www.yugabyte.com/blog/differences-primary-key-usage-colocated-noncolocated-tables/

https://stackoverflow.com/questions/69499426/cannot-colocate-hash-partitioned-table-in-yugabytedb

This is a known artificial restriction.  Is there a way to get this to work, or if not, is the table groups feature that's being worked on intended to do the same thing but without this restriction?

### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9218]: https://yugabyte.atlassian.net/browse/DB-9218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
> Is there a way to get this to work, or if not

How are you dumping the schema? You can do a search-replace on it only once.

> is the table groups feature that's being worked on intended to do the same thing but without this restriction?

Tablegroups isn't being worked on at the moment.

**Comment by KyleMaas** [comment]
> > Is there a way to get this to work, or if not
> 
> How are you dumping the schema? You can do a search-replace on it only once.

`ysql_dumpall` - I could try replacing in the dump, but there are a lot of tables and the schema is not my own but is one from a Django project, so I don't really want to risk breaking compatibility with future updates by going too far outside of the stock schema.

**Comment by KyleMaas** [comment]
Looking through the original Joomla schema, it doesn't actually specify hash indices.  So maybe replacing it in the schema is worth a try and won't break compatibility as badly as I feared.

**Comment by ddorian** [comment]
> I could try replacing in the dump, but there are a lot of tables and the schema is not my own but is one from a Django project, so I don't really want to risk breaking compatibility with future updates by going too far outside of the stock schema.

It won't break anything with future updates.

> So maybe replacing it in the schema is worth a try and won't break compatibility as badly as I feared.

It shouldn't break at all.

**Comment by KyleMaas** [comment]
Gave it a try, and it does seem to be working okay.
