### ISSUE TITLE
[YSQL][Cross-DB-DDL] Improve DDL failure messages when user fails to SET yb_non_ddl_txn_for_sys_tables_allowed=true and  SELECT yb_fix_catalog_version_table(true);

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20300]
Jira Link: [DB-9266](https://yugabyte.atlassian.net/browse/DB-9266)
### Description

Tried on version: **2.21.0.0-b320**

I created a universe with `ysql_enable_db_catalog_version_mode=true `, `allowed_preview_flags_csv=ysql_enable_db_catalog_version_mode` g-flags but I didn’t execute  SET `yb_non_ddl_txn_for_sys_tables_allowed=true;` and `SELECT yb_fix_catalog_version_table(true);`
 Index creation failed with the below error.

In cases like above we should report a more helpful error message, so that user has a clue on what the cause of the DDL failure is.

```
yugabyte=# create table t(id int);
CREATE TABLE

yugabyte=# insert into t values(1);
INSERT 0 1

yugabyte=# CREATE TABLE tempTable AS SELECT * FROM t limit 1000000;
SELECT 1

yugabyte=# CREATE INDEX idx2 ON tempTable(id);
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req version 2, master version 0
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req version 2, master version 0
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req version 2, master version 0
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req version 2, master version 0
ERROR:  Requested catalog version is too high: req version 2, master version 0
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9266]: https://yugabyte.atlassian.net/browse/DB-9266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment]
@shishir2001-yb FYI, I have reworked the fix, reverted the original fix which disallowed CREATE INDEX with a more helpful error message. Rather, I made a new fix that now does support CREATE INDEX in the situation described in this bug.
