### ISSUE TITLE
[YSQL][Cross-DB-DDL] Cross DB Concurrent DDLs fails with ERROR: Restart read required at: { read: { physical: 1702489614501399 } local_limit: { physical: 1702489614501399 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20303]
Jira Link: [DB-9269](https://yugabyte.atlassian.net/browse/DB-9269)
### Description

Tried on version: **2.21.0.0-320**

While performing Cross-DB Concurrent DDLs, some DDLs failed with the below error, 

`ERROR: Restart read required at: { read: { physical: 1702489614501399 } local_limit: { physical: 1702489614501399 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }`.

Some DDLs were 
```
CREATE INDEX ON tb_0(k);
ALTER TABLE tb_0 ADD newColumn3 TEXT DEFAULT 'Lorem Ipsum is simply dummy text of the printing and industry'
CREATE VIEW view1_tb_0 AS SELECT k from tb_0
CREATE TABLE tempTable2 AS SELECT * FROM tb_0

```
Note: 

1. We were not running  DDL and DMLs concurrently on the same database
2. We were not running Global DDLs

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9269]: https://yugabyte.atlassian.net/browse/DB-9269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment]
@shishir2001-yb , let me know if you still see this error after the recent change by https://phorge.dev.yugabyte.com/D24075. If not, then we can keep the other ticket (https://github.com/yugabyte/yugabyte-db/issues/20341)) and close this one as cannot repro.
