### ISSUE TITLE
[YSQL] [Cross-DB-DDL] Request id 464130 from client e12324b7-d448-4c21-8653-008081c8be1f is too old

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20330]
Jira Link: [DB-9316](https://yugabyte.atlassian.net/browse/DB-9316)
### Description

Tried on version: **2.21.0.0-b368**

While running the sample app for Cross-Database Concurrent DDL, some DDLs failed with the below error
```ERROR: [Operation expired (yb/consensus/retryable_requests.cc:511): Request id 464130 from client e12324b7-d448-4c21-8653-008081c8be1f is too old (now=1702590098633262, start_time=1702589836709751, request timeout 60.000s, max clock skew 0.500s): Min running request ID: 464130 (min running request ID 464130)]```

DDLs where this error occurred:
```
ALTER TABLE tb_0 ADD newColumn1 TEXT DEFAULT 'dummyString'
DDL query DROP VIEW view1_tb_0
 ALTER TABLE tb_0 ALTER newColumn3 TYPE VARCHAR(1000)
```
**Note**: No data is present inside the table

Context:

1. We are concurrently executing Cross-DB DDLs Sample app with multiple threads. Notably, we ensure there is no simultaneous execution of DDL and DML operations within the same database.
2. The table doesn't contains any data.
3. No Global DDLs are being executed.

Test Details:
```
Initiate 40 Threads, each tasked with performing DDLs and DMLs on a table within a specific database. These threads follow a sequence:
a. Establish a connection.
b. Execute 'SELECT * FROM tb_0'.
c. Start a loop and execute DDLs continuously 
```
List of DDLs that we perform in the test  :
```
private static List<List<String>> ddlList = List.of(
            List.of("CREATE INDEX idx1 ON ? (k)", "DROP INDEX idx1"),
            List.of("CREATE TABLE tempTable1 AS SELECT * FROM ? limit 1000000", "ALTER TABLE tempTable1 RENAME TO tempTable1_new", "DROP TABLE tempTable1_new"),
            List.of("CREATE MATERIALIZED VIEW mv1 as SELECT k from ? limit 10000", "REFRESH MATERIALIZED VIEW mv1", "DROP MATERIALIZED VIEW mv1"),
            List.of("ALTER TABLE ? ADD newColumn1 TEXT DEFAULT 'dummyString'", "ALTER TABLE ? DROP newColumn1"),
            List.of("ALTER TABLE ? ADD newColumn2 TEXT NULL", "ALTER TABLE ? DROP newColumn2"),
            List.of("CREATE VIEW view1_? AS SELECT k from ?", "DROP VIEW view1_?"),
            List.of("ALTER TABLE ? ADD newColumn3 TEXT DEFAULT 'dummyString'", "ALTER TABLE ? ALTER newColumn3 TYPE VARCHAR(1000)", "ALTER TABLE ? DROP newColumn3"),
            List.of("CREATE TABLE tempTable2 AS SELECT * FROM ? limit 1000000", "CREATE INDEX idx2 ON tempTable2(k)", "ALTER TABLE ? ADD newColumn4 TEXT DEFAULT 'dummyString'", "ALTER TABLE tempTable2 ADD newColumn2 TEXT DEFAULT 'dummyString'", "TRUNCATE table ? cascade", "ALTER TABLE ? DROP newColumn4", "ALTER TABLE tempTable2 DROP newColumn2", "DROP INDEX idx2", "DROP TABLE tempTable2"),
            List.of("CREATE VIEW view2_? AS SELECT k from ?", "CREATE MATERIALIZED VIEW mv2 as SELECT k from ? limit 10000", "REFRESH MATERIALIZED VIEW mv2", "DROP MATERIALIZED VIEW mv2", "DROP VIEW view2_?")
 );
```

Logs: [https://drive.google.com/drive/folders/1NrVGnHxQD5_p4HJJKxZYgqycrgaT23j-?usp=sharing](https://drive.google.com/drive/folders/1NrVGnHxQD5_p4HJJKxZYgqycrgaT23j-?usp=sharing)

G-flags:
```
ysql_enable_db_catalog_version_mode=true,
allowed_preview_flags_csv=ysql_enable_db_catalog_version_mode 
"tablet_split_high_phase_shard_count_per_node": 5000,
# high_phase_size 2MB
"tablet_split_high_phase_size_threshold_bytes": 2097152,  # 2MB
# low_phase_size 100KB
"tablet_split_low_phase_size_threshold_bytes": 102400,  # 100 KB
"tablet_split_low_phase_shard_count_per_node": 1000,
```
### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9316]: https://yugabyte.atlassian.net/browse/DB-9316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Huqicheng** [comment]
syscatalog tablet is in YQL table type and its retryable requests retain duration is 60s (after fix of #18736), YSQL DDL queries can be rejected by this error.

Since syscatalog will process both YQL and YSQL catalog changes, I think it should retain retryable requests for FLAGS_retryable_request_timeout_secs (the maximum duration to retain retryable requests).

cc: @ttyusupov @bmatican @rthallamko3
