### ISSUE TITLE
[DocDB] Bad narrow cast FATAL occurred in the tserver, caused by CoarseMonoClock() going back in time.

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#20335]
Jira Link: [DB-9320](https://yugabyte.atlassian.net/browse/DB-9320)
### Description

We have sample app workload that evaluate batched nested loop selects 
Also nemesis may occur during the workload

During the test in 2.20.0.2-b1 following FATAL observed in tserver logs

```
F20231216 07:22:59 ../../src/yb/gutil/casts.cc:21] Bad narrow cast: -1 < 0
    @     0x55da53a12997  google::LogMessage::SendToLog()
    @     0x55da53a138fd  google::LogMessage::Flush()
    @     0x55da53a13f79  google::LogMessageFatal::~LogMessageFatal()
    @     0x55da5425f32a  yb::BadNarrowCast()
    @     0x55da54c7e6ce  std::__1::__function::__func<>::operator()()
    @     0x55da54b902a8  yb::tablet::Operation::Replicated()
    @     0x55da54b91fc0  yb::tablet::OperationDriver::ReplicationFinished()
    @     0x55da53e8e1cd  yb::consensus::ConsensusRound::NotifyReplicationFinished()
    @     0x55da53edb61f  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @     0x55da53eda9d9  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x55da53eb7975  yb::consensus::RaftConsensus::UpdateMajorityReplicated()
    @     0x55da53e81f31  yb::consensus::PeerMessageQueue::NotifyObserversOfMajorityReplOpChangeTask()
    @     0x55da55261f5c  yb::ThreadPool::DispatchThread()
    @     0x55da5525e124  yb::Thread::SuperviseThread()
    @     0x7fbc3283c694  start_thread
    @     0x7fbc32b3941d  __clone
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9320]: https://yugabyte.atlassian.net/browse/DB-9320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
similar to https://github.com/yugabyte/yugabyte-db/issues/19574, Maybe caused by nemesis. FYI, @Huqicheng

**Comment by rthallamko3** [comment]
Based on offline discussions, this fatal can happen if the RAFT payload is corrupted by some form of Nemesis.  The tserver recovers fine, after the Fatal. 

Based on offline discussions, the test can add this to the list of expected fatals (as the test is injecting failures), and increase the time to wait for tservers to come back up, if they are impacted by this issue. cc @qvad .
