### ISSUE TITLE
[yugabyted] yugabyted UI support for K8s helm chart

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#20344]
Jira Link: [DB-9334](https://yugabyte.atlassian.net/browse/DB-9334)
### Description

YugabyteDB Helm charts are used to deploy the OSS YugabyteDB cluster in the K8s environment. Currently, the OSS Helm chart involves bringing up `yb-master` and `yb-server` pods and their respective UIs on the `7000` and `9000` ports. 

In addition to the master and tserver UI, OSS Helm chart should bring up the new yugabyted-ui on `15433` port. 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9334]: https://yugabyte.atlassian.net/browse/DB-9334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by williamoliveira** [comment]
What would be a workaround for this?

**Comment by nchandrappa** [comment]
We have made the required [changes](https://github.com/yugabyte/yugabyte-db/commit/b5ed6bba721bf3102d513ee31a39745443fd4a18) to support yugabyted UI in the YugabyteDB helm chart. If you use the latest YugabyteDB helm chart for DB version 2.21.0.0 you should be able to see the yugabyted UI.

**Comment by nchandrappa** [comment]
Corresponding code changes in the YugabyteDB charts repo - https://github.com/yugabyte/charts/commit/144210b62a24c8296f9e09110beb72b557cec0a7

**Comment by nchandrappa** [comment]
code changes have landed.
