### ISSUE TITLE
Can't get a Yugabyte platform download link and evaluation guide if a personal (non-work) email is specified

### ISSUE THREAD

**Issue by sain801028** [yugabyte/yugabyte-db#2039]
![螢幕快照_2019-08-13_14-26-35 (1)](https://user-images.githubusercontent.com/17377422/62921572-b72a4900-bddb-11e9-96c6-6b6c7df71355.png)

**Comment by jguerreroyb** [comment]
Are you registering with a company email or free email service like gmail, yahoo or similar? If so, we do require that individuals use a company email address to start a trial of YugaByte DB Platform.

**Comment by sain801028** [comment]
Can't I get it using my personal email?

**Comment by jguerreroyb** [comment]
Send an email to sales at yugabyte dot com to request a trial.

**Comment by mbautin** [comment]
@sain801028 -- thank you for your interest in YugaByte DB! Have you been able to request a trial by sending an email to our sales team?

**Comment by sain801028** [comment]
Thank you, I've now understood

**Comment by sain801028** [comment]
How do I get it
Yugabyte platform
I want to try yugabyte platform inside, I am always confused about your application on the official website
