### ISSUE TITLE
[YSQL] [DocDB] Unexpected reads on index during data load on table with a non-unique index

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#20398]
Jira Link: [DB-9391](https://yugabyte.atlassian.net/browse/DB-9391)
### Description

When doing data load into a table with a non-unique index, we do expect to see reads against main table to check for PK constraint check violation. Few observations/things to investigate:

a) There are a high number of reads as part of the writes to the index (see rocksdb_block_cache_miss & rocksdb_block_cache_hit metric for the index). If the index had a UNIQUE constraint that's expected, but it is not clear why we are seeing index reads on non-UNIQUE indexes during data load.

b) Even if such reads where to exist the `rocksdb_block_cache_miss` metric is an order of magnitude higher on the index than on the main table. 

c) For main table as well, it not clear why `rocksdb_bloom_filter_useful` metric stays 0. 

**Test Case:**

```
drop table if exists test_table;
create extension if not exists pgcrypto;
create table test_table(k text, v text, PRIMARY KEY(k ASC));
create index index_v_test_table on test_table(v);

-- Load 10M rows
do $$
begin
  for counter in 1..1000 loop
    raise notice 'counter: %', (counter * 10000);
    insert into test_table (select gen_random_uuid(), gen_random_bytes(50)::text
                        from generate_series(1, 10000) i);
    commit;
  end loop;
end $$;
```

This test was run on a 2.20.0, RF=1 setup, these were the relevant metrics after loading 10M rows using script above:

**Metrics**

```
$ curl -s http://localhost:9000/prometheus-metrics | grep -E "test_table" | grep -wE "rocksdb_block_cache_miss"
rocksdb_block_cache_miss{table_name="index_v_test_table"} 4727173 <ts>
rocksdb_block_cache_miss{table_name="test_table"} 94131 <ts>
```

```
$ curl -s http://localhost:9000/prometheus-metrics | grep -E "test_table" | grep -wE "rocksdb_block_cache_hit"
rocksdb_block_cache_hit{table_name="index_v_test_table"} 4452798 <ts>
rocksdb_block_cache_hit{table_name="test_table"} 26029174 <ts>
```

Bloom useful metric stays 0 for main table and index!

```
$ curl -s http://localhost:9000/prometheus-metrics | grep -E "test_table" | grep -wE "rocksdb_bloom_filter_useful"
rocksdb_bloom_filter_useful{table_name="index_v_test_table"} 0 <ts>
rocksdb_bloom_filter_useful{table_name="test_table"} 0 <ts>
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9391]: https://yugabyte.atlassian.net/browse/DB-9391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kmuthukk** [comment]
Don't see the same behavior in 2.18.2.1
```
curl -s http://localhost:9000/prometheus-metrics | grep -E "test_table" | grep -wE "rocksdb_bloom_filter_useful|rocksdb_block_cache_data_hit|rocksdb_block_cache_data_miss"  | sed 's/expo.*9000..//'
rocksdb_block_cache_data_miss{table_name="test_table"} 141475 <ts>
rocksdb_block_cache_data_miss{table_name="index_v_test_table"} 121243 <ts>

rocksdb_block_cache_data_hit{table_name="test_table"} 139053 <ts>
rocksdb_block_cache_data_hit{table_name="index_v_test_table"} 41512 <ts>

rocksdb_bloom_filter_useful{table_name="test_table"} 10980619 <ts>
rocksdb_bloom_filter_useful{table_name="index_v_test_table"} 9141243 <ts>
```

**Comment by mbautin** [comment]
Problematic commits identified by @ttyusupov:


The result is that there were two separate breaking changes. First of them made index table bloom filters to be not checked: https://github.com/yugabyte/yugabyte-db/commit/beeebbe873bef97561427bc13f4906d607340ba9

And the second one made also main table bloom filters to be not checked: https://github.com/yugabyte/yugabyte-db/commit/7b582dd6edf1d764292ca69d8bcb323f5e8c5db4

**Comment by mbautin** [comment]
Running the bulk load test:

On commit 32e25daac25dedda6d7bcfc3315ca00d5d73e477 : https://gist.githubusercontent.com/mbautin/28c57195cf5acde9d8ca27b41cc292c8/raw
25170.170 ms

On commit beeebbe873bef97561427bc13f4906d607340ba9 (the next commit): https://gist.githubusercontent.com/mbautin/4d3dbb0534fa7dbe5eb974e668760a55/raw
31654.053 ms

Slower by a factor of 1.257

**Comment by mbautin** [comment]
Here is a more systematic re-run of the bulk load test on four consecutive commits:
https://gist.githubusercontent.com/mbautin/860eea004685dec4c7629fe822bc7a80/raw

Filtered to just commits and run times:
https://gist.githubusercontent.com/mbautin/4e4a14563e5df4b89e14ac030c30d832/raw

The regression from 32e25daac25dedda6d7bcfc3315ca00d5d73e477 to beeebbe873bef97561427bc13f4906d607340ba9 seems less significant in this test (25 to 26 seconds).

A more significant regression happens from 9a63e5bda217550befbf5e7a2b31ef2acb858a45 to 7b582dd6edf1d764292ca69d8bcb323f5e8c5db4 (25 to 29-33 seconds) so this is where we should focus first.

**Comment by mbautin** [comment]
Re-running the test on commit 7b582dd6edf1d764292ca69d8bcb323f5e8c5db4 but now with 10M keys (the VM is a 8 GB 4 vcpu GCP server, Intel(R) Xeon(R) CPU @ 2.80GHz):

https://gist.githubusercontent.com/mbautin/42c9fd03382e50777ba9f3c6064ce24b/raw

Running time of the load step: 583.6 sec

**Comment by mbautin** [comment]
Time: 591906.737 ms (09:51.907)
+ curl -s http://localhost:9000/prometheus-metrics
+ grep -E test_table
+ grep -wE 'rocksdb_bloom_filter_useful|rocksdb_bloom_filter_checked|rocksdb_block_cache_data_hit|rocksdb_block_cache_data_miss'
+ tr ' ' '\n'
+ sed 's/[0-9]*$//'
+ sed 's/expo.*9000..//'
rocksdb_bloom_filter_useful{metric_type="table",table_type="PGSQL_TABLE_TYPE",namespace_name="yugabyte",table_name="test_table",table_id="000033f5000030008000000000004025"}
12662051

rocksdb_bloom_filter_useful{table_id="000033f500003000800000000000402a",table_name="index_v_test_table",namespace_name="yugabyte",table_type="PGSQL_TABLE_TYPE",metric_type="tablet",
0

rocksdb_block_cache_data_miss{metric_type="table",table_type="PGSQL_TABLE_TYPE",namespace_name="yugabyte",table_name="test_table",table_id="000033f5000030008000000000004025"}
2297302

rocksdb_block_cache_data_miss{table_id="000033f500003000800000000000402a",table_name="index_v_test_table",namespace_name="yugabyte",table_type="PGSQL_TABLE_TYPE",metric_type="tablet",
3285013

rocksdb_bloom_filter_checked{metric_type="table",table_type="PGSQL_TABLE_TYPE",namespace_name="yugabyte",table_name="test_table",table_id="000033f5000030008000000000004025"}
12761566

rocksdb_bloom_filter_checked{table_id="000033f500003000800000000000402a",table_name="index_v_test_table",namespace_name="yugabyte",table_type="PGSQL_TABLE_TYPE",metric_type="tablet",
0

rocksdb_block_cache_data_hit{metric_type="table",table_type="PGSQL_TABLE_TYPE",namespace_name="yugabyte",table_name="test_table",table_id="000033f5000030008000000000004025"}
5206287

rocksdb_block_cache_data_hit{table_id="000033f500003000800000000000402a",table_name="index_v_test_table",namespace_name="yugabyte",table_type="PGSQL_TABLE_TYPE",metric_type="tablet",
2306044

+ echo 'Saved log to /net/dev-server-mbautin/share/logs/regr_bulk/regr_bulk_10m2024-01-08T23_17_37.log'

**Comment by mbautin** [comment]
Results of re-running the 10M test on commit 9a63e5b

https://gist.githubusercontent.com/mbautin/cb5a8aa2cdd9e22b7d94b9db194cf812/raw

Time: 591.9 sec (even slower than commit 7b582dd). So, with the 10M test, we have to look at other commits for a possible regression.

**Comment by mbautin** [comment]
Result of the 10M test for commit beeebbe873bef97561427bc13f4906d607340ba9:

https://gist.githubusercontent.com/mbautin/ad50de9139fd0b75f19f9719d65d65a3/raw

Time: 580.3 sec
