### ISSUE TITLE
[DocDB] Skip conflict resolution during insert to non unique index

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#20486]
Jira Link: [DB-9491](https://yugabyte.atlassian.net/browse/DB-9491)
### Description

Every entry in non unique index has unique key.
So we could avoid doing conflict resolution when inserting to non unique index.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9491]: https://yugabyte.atlassian.net/browse/DB-9491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment]
Committed a test that would fail if we skip conflict resolution for writes to non-unique index tables.
