### ISSUE TITLE
[yugabyted] Fix for connection management in yugabyted-ui backend

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#20494]
Jira Link: [DB-9502](https://yugabyte.atlassian.net/browse/DB-9502)
### Description

Currently, the yugabyted-ui uses the connection management api endpoint at `:13000/connections` to get connection stats if connection manager is enabled. There have been some changes to the output of this api, so the yugabyted-ui backend needs to be updated.
The JIRA link for the connection management changes: https://yugabyte.atlassian.net/browse/DB-8527. In summary, the changes to connection manager:
The `pool_name` in the previous stats format is removed and two new fields `database_name` and `user_name` is added.
```
{
    "database_name": "yugabyte",
    "user_name": "postgres",
    "active_logical_connections": 0,
    "queued_logical_connections": 0,
    "idle_or_pending_logical_connections": 1,
    "active_physical_connections": 0,
    "idle_physical_connections": 0,
    "avg_wait_time_ns": 0,
    "qps": 0,
}
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9502]: https://yugabyte.atlassian.net/browse/DB-9502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nchandrappa** [comment]
Code changes landed.
