### ISSUE TITLE
[YSQL] test: fix improper usage of Thread.sleep

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#20503]
Jira Link: [DB-9511](https://yugabyte.atlassian.net/browse/DB-9511)
### Description

`Thread.sleep` takes milliseconds, but some tests pass in seconds.  The tests should be fixed to use the proper numbers or rewritten to avoid sleeps.  Lines from `TestTablespaceProperties.java`:

```
private static final int MASTER_REFRESH_TABLESPACE_INFO_SECS = 2;
Thread.sleep(5 * MASTER_REFRESH_TABLESPACE_INFO_SECS);
Thread.sleep(2 * MASTER_REFRESH_TABLESPACE_INFO_SECS);
```

I do not know whether these tests fail or not.

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9511]: https://yugabyte.atlassian.net/browse/DB-9511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kai-franz** [comment]
Fixed in 3eeaab46369882d5d619fcbcc313e1a792d8885b.
