### ISSUE TITLE
[DocDB] flaky test: GeoTransactionsPromotionConflictAbortTest.TestConflictAbortBeforeNewHeartbeat

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20518]
Jira Link: [DB-9524](https://yugabyte.atlassian.net/browse/DB-9524)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=GeoTransactionsPromotionConflictAbortTest&fail_tag=all&name=TestConflictAbortBeforeNewHeartbeat&num_commits=500&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9524]: https://yugabyte.atlassian.net/browse/DB-9524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
Fixed in 0214819
