### ISSUE TITLE
[DocDB] flaky test: ClusterAdminClientTest.CreateSnapshotAfterMultiNamespaceCreateIssuedWithSameName

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20516]
Jira Link: [DB-9522](https://yugabyte.atlassian.net/browse/DB-9522)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=ClusterAdminClientTest&fail_tag=all&name=CreateSnapshotAfterMultiNamespaceCreateIssuedWithSameName&num_commits=500&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9522]: https://yugabyte.atlassian.net/browse/DB-9522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
d557250c29e759332e01351b586cbd21beb0089a fixed this issue.
