### ISSUE TITLE
[YSQL] style: fix typo PgDdlAtomiPgDdlAtomicityTablegroupTest

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#20525]
Jira Link: [DB-9530](https://yugabyte.atlassian.net/browse/DB-9530)
### Description

Commit a4170bc9c2c94af88394d0c469b0cb1da7e8b6cd does

```
-class PgDdlAtomicityNegativeTestTablegroup : public PgDdlAtomicityNegativeTestBase {
+class PgDdlAtomiPgDdlAtomicityTablegroupTest : public PgDdlAtomicityColocatedTestBase {
```

"PgDdlAtomiPgDdlAtomicityTablegroupTest" looks like a typo.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9530]: https://yugabyte.atlassian.net/browse/DB-9530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by deeps1991** [comment]
This was fixed in [74cb39dae19a](https://phorge.dev.yugabyte.com/rYBDB74cb39dae19af35ee8fa7d483975ad97550d7644)
