### ISSUE TITLE
[DocDB] Race in tablet shutdown and tablet restart blocks tserver shutdown

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20587]
Jira Link: [DB-9589](https://yugabyte.atlassian.net/browse/DB-9589)
### Description

Race in tablet shutdown and tablet restart blocks tserver shutdown, which can cause tests to be flaky - FailOnConflict/SnapshotTxnTest.DeleteOnLoad/0 and SnapshotTxnTest.DeleteOnLoad/0

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=SnapshotTxnTest&fail_tag=all&name=DeleteOnLoad%2F0&platform=linux

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=FailOnConflict%2FSnapshotTxnTest&fail_tag=all&name=DeleteOnLoad%2F0&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9589]: https://yugabyte.atlassian.net/browse/DB-9589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
from the initial analysis,  I see a couple of issues
1. tsan race on [LOG(DFATAL)](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tablet/transaction_status_resolver.cc#L71), not sure why, but don't think it is critical.
2. hard coded wait time [here](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tablet/transaction_status_resolver.cc#L68), followed by a dfatal which causes crash only in debug. isn't a problem in release mode. will create a fix. 
3. looks like a blocking timeout issue where we end up waiting for a mutex. in one of the runs, we can see that the data blocks and everything get deleted, but then we end up blocking and I don't see a corresponding Deleted transition in progress  log for the delete operation. It seems to be blocked [here](https://github.com/yugabyte/yugabyte-db/blob/7d7a6363db0cdee35a4819927e9941d925dd0c65/src/yb/tserver/ts_tablet_manager.cc#L1581) trying to acquire the lock. here are the log lines I see from the last in-progress delete which never finishes
```
[ts-1] I0122 16:33:21.324695 34781 tablet_service.cc:1651] T {ql_client_test_table_tablet_id1} P {ts1_peer_id}: Processing DeleteTablet with delete_type ...
...
[ts-1] I0122 16:33:22.674739 34781 consensus_meta.cc:126] T {ql_client_test_table_tablet_id1} Deleting consensus metadata
[ts-1] I0122 16:33:22.674818 34781 tablet_bootstrap_if.cc:96] T {ql_client_test_table_tablet_id1} P {ts1_peer_id}: Deleted tablet blocks from disk
```
but nothing post this, which implies that the delete could have been blocked [here](https://github.com/yugabyte/yugabyte-db/blob/7d7a6363db0cdee35a4819927e9941d925dd0c65/src/yb/tserver/ts_tablet_manager.cc#L1581). seems to be reproducible with good frequency.
