### ISSUE TITLE
[DocDB] flaky test: PgNamespaceTest.CreateNamespaceFromTemplateLeaderFailover

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20592]
Jira Link: [DB-9594](https://yugabyte.atlassian.net/browse/DB-9594)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgNamespaceTest&fail_tag=all&name=CreateNamespaceFromTemplateLeaderFailover&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9594]: https://yugabyte.atlassian.net/browse/DB-9594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SrivastavaAnubhav** [comment]
Fixed by commit 86136b4e2aa54e80d98840345043297a7fc2adc4
