### ISSUE TITLE
Segfault while handling pgbench workload

### ISSUE THREAD

**Issue by nspiegelberg** [YugaByte/yugabyte-db#2060]
The PgBench tool has 2 modes: Initialize (delete old table, create new tables, add rows) and benchmark (core functionality).   I've been running pgbench in the Initialize state in a loop and caught a DROP TABLES crash.  You should be able to reproduce this with master, but it takes a handful of back-to-back runs:

> 17:51 $ time ./build/latest/postgres/bin/pgbench -i -s 10 postgres
> dropping old tables...
> creating tables (with primary keys)...
> generating data...
> 100000 of 1000000 tuples (10%) done (elapsed 1.71 s, remaining 15.35 s)
> 200000 of 1000000 tuples (20%) done (elapsed 4.88 s, remaining 19.50 s)
> 300000 of 1000000 tuples (30%) done (elapsed 8.49 s, remaining 19.81 s)
> 400000 of 1000000 tuples (40%) done (elapsed 11.59 s, remaining 17.38 s)
> 500000 of 1000000 tuples (50%) done (elapsed 15.22 s, remaining 15.22 s)
> 600000 of 1000000 tuples (60%) done (elapsed 18.37 s, remaining 12.25 s)
> 700000 of 1000000 tuples (70%) done (elapsed 21.99 s, remaining 9.42 s)
> 800000 of 1000000 tuples (80%) done (elapsed 25.08 s, remaining 6.27 s)
> 900000 of 1000000 tuples (90%) done (elapsed 28.73 s, remaining 3.19 s)
> 1000000 of 1000000 tuples (100%) done (elapsed 32.23 s, remaining 0.00 s)
> done.
> 
> real	1m57.506s
> user	0m0.182s
> sys	0m0.013s
> Nicolass-MacBook-Pro.local:~/code/yugabyte-db [pgbench_alter L|…6]
> 17:53 $ time ./build/latest/postgres/bin/pgbench -i -s 10 postgres
> dropping old tables...
> FATAL:  terminating connection due to unexpected postmaster exit
> ERROR:  Timed out: Timed out waiting for Table Deletion
> 
> real	1m1.750s
> user	0m0.002s
> sys	0m0.005s

Debugged this with @bmatican and we found the following under ~/yugabyte-data/node-1/disk-1/tserver.err

>   1 In YugaByte DB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/YugaByte/y
>   2 2019-08-13 16:13:39.661 PDT [29837] LOG:  listening on IPv4 address "127.0.0.1", port 5433
>   3 2019-08-13 16:13:39.669 PDT [29837] LOG:  redirecting log output to logging collector process
>   4 2019-08-13 16:13:39.669 PDT [29837] HINT:  Future log output will appear in directory "/Users/nicolas/yugabyte-data/node-1/disk-1/yb-data/tserver/logs".
>   5 *** Aborted at 1565744068 (unix time) try "date -d @1565744068" if you are using GNU date ***
>   6 PC: @        0x10dceef58 yb::tablet::Tablet::WriteBatch()
>   7 *** SIGSEGV (@0x0) received by PID 29823 (TID 0x70000a123000) stack trace: ***
>   8     @     0x7fff6b971b5d _sigtramp
>   9     @        0x110e06788  std::__1::__compressed_pair<>::first()
>  10     @        0x10dcf4a67  yb::tablet::Tablet::RemoveIntentsImpl<>()
>  11     @        0x10dcf4939  yb::tablet::Tablet::RemoveIntents()
>  12     @        0x10dcf4b11  yb::tablet::Tablet::RemoveIntents()
>  13     @        0x10dd9575f  yb::tablet::(anonymous namespace)::RemoveIntentsTask::Run()
>  14     @        0x112e7e48f  yb::rpc::(anonymous namespace)::Worker::Execute()
>  15     @        0x114490cc3  yb::Thread::SuperviseThread()
>  16     @     0x7fff6b97a2eb _pthread_body
>  17     @     0x7fff6b97d249 _pthread_start
>  18     @     0x7fff6b97940d thread_start

**Comment by bmatican** [comment]
@spolitov is this some unsafe interaction between in memory cleanup of intents and shutdown of rocksdb?

**Comment by kmuthukk** [comment]
nice find @nspiegelberg. Once fixed, let's try to add this into the "ptest" suite.
