### ISSUE TITLE
[Docs] New docs proposal

### ISSUE THREAD

**Issue by MauroCL75** [yugabyte/yugabyte-db#20621]
### Description

Please also link this page to a CLI/ysql implementation of this.
The page is https://docs.yugabyte.com/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-geopartition/
Thanks!

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
Hi @MauroCL75 

What do you mean by `CLI/ysql` ?

Also, please write a better title.

**Comment by MauroCL75** [comment]
CLI=command line interface
YSQL=Yugabyte Structured Query Language
Sorry, the title was automatically added. 
So it would be nice to also have a link on how to do the same with command line, via ysqlsh.

**Comment by ddorian** [comment]
See https://docs.yugabyte.com/preview/explore/multi-region-deployments/row-level-geo-partitioning/
