### ISSUE TITLE
Do not run unit-tests when only files from directories not participating in tests are changed

### ISSUE THREAD

**Issue by ttyusupov** [YugaByte/yugabyte-db#2062]
We need to update `python/yb/dependency_graph.py`, to not consider changes to `managed/*` and `www/*` as other type, which trigger all unit-tests.

**Comment by bmatican** [comment]
Looking at our dir structure, I think we should probably exclude:
```
architecture
cloud
community
docs
managed
sample
www
```

In particular, we can tweak this so that changes to `managed` and `managed/devops` could trigger their own sets of tests.

cc @mbautin
