### ISSUE TITLE
[YSQL] Disable Parallel query for Hash sharded tables

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#20637]
Jira Link: [DB-9635](https://yugabyte.atlassian.net/browse/DB-9635)
### Description

Disable Parallel query for Hash sharded tables.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9635]: https://yugabyte.atlassian.net/browse/DB-9635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
Disabled parallel query for all relation distribution types except colocated (hash, range, system).
