### ISSUE TITLE
[docdb] Test FATAL: Transaction should not have metadata but present

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2065]
Saw this failure in this java test: `SimpleQueryTest#test2ndaryIndexes`

```
12092 | [ts-1] | W | 8.637159 | 20477 | yb_rpc.cc:362 | Call yb.tserver.TabletServerService.Write 127.55.80.17:53179 => TS-1_RPC_HOST_PORT (request call id 229) took 2699ms (client timeout 2500ms).
-- | -- | -- | -- | -- | -- | --
12093 | [ts-1] | F | 8.638961 | 20447 | transaction_participant.cc:789 | T TABLET27 P PEER_TS-1: Transaction should not have metadata but present: 865bf497-7030-452d-8a66-2eb2a547ff5b
```

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F2884%2Fartifact%2Fjava%2Fyb-cql%2Ftarget%2Fsurefire-reports_org.yb.cql.SimpleQueryTest__test2ndaryIndexes%2Forg.yb.cql.SimpleQueryTest-output.txt?max_lines=3000&start_line=12001

**Comment by spolitov** [comment]
Fixed as part of D7212
