### ISSUE TITLE
[DocDB] PgFKeyTest tests fail when run with pg_client_use_shared_memory gflag

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#20669]
Jira Link: [DB-9667](https://yugabyte.atlassian.net/browse/DB-9667)
### Description

PgFKeyTest tests fail when run with pg_client_use_shared_memory gflag.

Fix the tests to either disable the gflag explicitly within the test, as the tests count the exact number of RPCs, or fix the validation using metrics.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9667]: https://yugabyte.atlassian.net/browse/DB-9667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by spolitov** [comment]
@rthallamko3 those tests check number of RPCs. So there is no issue. If we will set `pg_client_use_shared_memory` to `true` by default, then we could just disable this flag for particular tests.

**Comment by rthallamko3** [comment]
@spolitov , This GH is to track the updates to the test to set `pg_client_use_shared_memory` to `false` , so that we can get on the path to enable the feature on by default. 

Also, Mihnea is validating a diff - https://phorge.dev.yugabyte.com/D31628 with all the PG parity features and without the test updates, he would see the failures. cc @bmatican

**Comment by rthallamko3** [comment]
This was done as part of #21348
