### ISSUE TITLE
[DocDB] Couldn't find connection for any index FATAL occured in tserver restart scenario

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#20661]
Jira Link: [DB-9657](https://yugabyte.atlassian.net/browse/DB-9657)
### Description

We have a scenario where during YSQL workload `kill -9` command send against tserver process in selected node every second.

Eventually test failed with FATAL:
```
F20240117 16:03:22 ../../src/yb/rpc/reactor.cc:861] Check failed: erased Couldn't find connection for any index to Connection (0x0000249df10beb58) client 172.151.23.201:37163 => 172.151.27.63:9100
    @     0x55b6dc600a47  google::LogMessage::SendToLog()
    @     0x55b6dc60196d  google::LogMessage::Flush()
    @     0x55b6dc601fe9  google::LogMessageFatal::~LogMessageFatal()
    @     0x55b6dd7da579  yb::rpc::Reactor::DestroyConnection()
    @     0x55b6dd79aebd  yb::rpc::FunctorReactorTaskWithWeakPtr<>::Run()
    @     0x55b6dd7d3dab  ev::base<>::method_thunk<>()
    @     0x55b6dc95ccab  ev_invoke_pending
    @     0x55b6dc95ffb7  ev_run
    @     0x55b6dd7d64b7  yb::rpc::Reactor::RunThread()
    @     0x55b6de06f354  yb::Thread::SuperviseThread()
    @     0x7f4625d641cf  start_thread
    @     0x7f4625fb5e73  __GI___clone
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9657]: https://yugabyte.atlassian.net/browse/DB-9657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
It looks like an aggressive check that fails, if the tservers are killed and not brought down gracefully. cc @amitanandaiyer , for context on why the check was added in the first place.

**Comment by rthallamko3** [comment]
DUP of https://github.com/yugabyte/yugabyte-db/issues/21738
