### ISSUE TITLE
[yugabyted] Restarting a second node of the cluster with `--join` flag throws an error.

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#20684]
Jira Link: [DB-9684](https://yugabyte.atlassian.net/browse/DB-9684)
### Description

Steps to reproduce:

Start a 3 node cluster (Using local cluster for reporting the issue):
```
./yugabyted start \
--advertise_address 127.0.0.1 \
--base_dir ~/yb-cluster/node1

./yugabyted start \
--advertise_address 127.0.0.2 \
--base_dir ~/yb-cluster/node2 \
--join 127.0.0.1

./yugabyted start \
--advertise_address 127.0.0.3 \
--base_dir ~/yb-cluster/node3 \
--join 127.0.0.1
```

Stop all the nodes:
```
./yugabyted stop --base_dir ~/yb-cluster/node1

./yugabyted stop --base_dir ~/yb-cluster/node2

./yugabyted stop --base_dir ~/yb-cluster/node3
```

Restart the nodes:
```
./yugabyted start \
--advertise_address 127.0.0.1 \
--base_dir ~/yb-cluster/node1

./yugabyted start \
--advertise_address 127.0.0.2 \
--base_dir ~/yb-cluster/node2 \
--join 127.0.0.1
```

The last command gives the following error:
```
Fetching configs from join IP...
ERROR: Node at the join ip provided is not reachable.
For more information, check the logs in /home/gargsans/yb-cluster/node2/logs
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9684]: https://yugabyte.atlassian.net/browse/DB-9684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ShikharSahay** [comment]
Code changes landed.
