### ISSUE TITLE
[DocDB] flaky test: PgWaitQueuesAggressiveWaitingRegistryReporter.TestStatusTabletDataCleanup

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20691]
Jira Link: [DB-9695](https://yugabyte.atlassian.net/browse/DB-9695)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgWaitQueuesAggressiveWaitingRegistryReporter&fail_tag=all&name=TestStatusTabletDataCleanup&platform=linux

Seems to start from https://phorge.dev.yugabyte.com/D29796

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9695]: https://yugabyte.atlassian.net/browse/DB-9695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
https://github.com/yugabyte/yugabyte-db/commit/bf593a87b9739c5d4d0241201cc006c8e17eab1d fixes and issue with commit https://github.com/yugabyte/yugabyte-db/commit/7d7a6363db0cdee35a4819927e9941d925dd0c65 and also stabilizes the above test.
