### ISSUE TITLE
[DocDB] Enabling WaitOnConflict leads to ERROR:  schema version mismatch for table 00004000000030008000000000004000: expected 16, got 15 in select query

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#20730]
Jira Link: [DB-9736](https://yugabyte.atlassian.net/browse/DB-9736)
### Description

Please find run report in JIRA description.

This was observed in the packed stress testcase, where we toggle off and on, only in master branch.

_This is what testcase does:_

1. Start workload SqlDataLoadWithDDL
2. Wait for number of rows to cross 100000
3. Then start toggle off/on packed gflag

To check step 2, we sleep 60s and do select count(*) from table, and validate if it crossed the threshold mark.
And while doing this we observed error:
`
2024-01-22 05:53:57,962:DEBUG: > 172.151.25.62 > /home/yugabyte/tserver/bin/ysqlsh --c "select count(*) from test_packed_columns_9418c7" -h 172.151.26.99,172.151.24.90,172.151.25.62 -d db -A 2>&1
2024-01-22 05:53:58,624:DEBUG: < 172.151.25.62 < ERROR:  schema version mismatch for table 00004000000030008000000000004000: expected 16, got 15
`

Below is the workload we have

`
nohup java  -jar /tmp/tests/artifacts/stress-sample-app-tool/yb-stress-sample-apps-1.1.37.jar --workload SqlDataLoadWithDDL  --uuid 54696edc-65f8-44d4-ab86-bce31cf38cc8 --create_table_name test_packed_columns_9418c7 --num_writes -1 --num_threads_write 20 --num_reads -1 --num_threads_read 20 --num_unique_keys 999000000000 --num_value_columns 150 --batch_size 10 --num_indexes 2 --use_unique_index true --ddl_operations DELETE_ROW,UPDATE_ROW,UPDATE_ROWS,ADD_COLUMN,DROP_COLUMN,INSERT_ROW --ddl_weights 100,100,10,1,1,10000 --exceptions_distance 0.15 --default_cassandra_keyspace db --default_postgres_database db --use_datatypes true --uuid_column --random_int_column --large_key_multiplier 5 --large_value_multiplier 5 --null_possibility_percentage 15 --uuid_marker 6107394a-7309-4165-b76b-935a5aaf41a0  --nodes 172.151.24.90:5433,172.151.25.62:5433,172.151.26.99:5433
`

We started observing, once we added **large_key_multiplier**, **large_value_multiplier**, **null_possibility_percentage**

Seeing this on latest master: 2.21.0.0-b496

I also performed same test on 2.20.2.0-b91, but could n't find it hitting there.

Therefore, I initiated a git bisect for the problem on the master branch. It appears that the issue was introduced by https://phorge.dev.yugabyte.com/D29841 on the master branch, specifically on commit b298. This issue came to light as I had made a test-related change, as mentioned above, last week. (git range in JIRA comments)

Setting enable_wait_queues to false, the test went fine without hitting this issue.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9736]: https://yugabyte.atlassian.net/browse/DB-9736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
I think it is reasonable that we see version mismatch errors when DDLs are run concurrently with DMLs. Was trying to repro this locally when I found the below anomaly.

case 1. 
with wait on conflict disabled,
```
create table test(k int primary key, v int) split into 1 tablets;
insert into test select generate_series(1,11), 0;

                                                                        begin;
                                                                        select * from test where k=1; // see k, v
alter table test add column "v1" text default 'def';
                                                                        select * from test where k=1; // errors out as expected
                                                                        rollback;
                                                                        begin;
alter table test add column "v2" text default 'def';                        
                                                                        select * from test where k=1; // goes through, but sees k,v,v1. doesn't see v2? <- step 'x'
                                                                        select * from test where k=1 for update;
                                                                        update test set v=v+1 where k=1;
                                                                        commit; // goes through
                                                                        select * from test where k=1; // sees the update as well as v2
```

case 2. 
but with WoC enabled, step `x` fails with schema version mismatch error. 

I think the same is happening in the stress test above. 

digging into the logs, I see a few additional `PgClientSession::Perform` calls in case 1 (for step `x`) that seem to fetch the latest schema version, and the last incoming `PgPerformRequestPB` (corresponding to the actual read for step `x`) has the latest schema version. Not sure why the new column isn't shown as part of the response though. 

for case 2, I don't see those additional few `PgClientSession::Perform` calls for the step `x` and the incoming read request arrives with the old schema number, which causes the schema error mismatch as expected. 

Will need to explore YB-PG backend to see why case 2 doesn't make those additonal `PgClientSession::Perform` calls that fetch the latest schema version.
