### ISSUE TITLE
[DocDB] Add ability to limit the number of rows sent by tserver for pg_locks

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#20765]
Jira Link: [DB-9762](https://yugabyte.atlassian.net/browse/DB-9762)
### Description

This is the prerequisite for [#19934](https://github.com/yugabyte/yugabyte-db/issues/19934)

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9762]: https://yugabyte.atlassian.net/browse/DB-9762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
we should probably introduce a GUC to modulate this behavior

**Comment by robertsami** [comment]
open question: how do we inform the user that result set was capped?
