### ISSUE TITLE
[DocDB] Investigate test failure PgGetLockStatusTest.TestPgLocksWhileDDLInProgress

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#20768]
Jira Link: [DB-9766](https://yugabyte.atlassian.net/browse/DB-9766)
### Description

from one of the asan failures,
```
../../src/yb/yql/pgwrapper/pg_get_lock_status-test.cc:606 Failed Bad status: Network error
(yb/yql/pgwrapper/libpq_utils.cc:359): Fetch 'SELECT * FROM pg_locks' failed: 7, message: 
ERROR:  Bad intent key, intent type set type expected in 78000ABECD98D44306860849A73988383DDC7FFEBB5008C451EA7FE11A33, 
transaction from: 47092C5307BB5422A8EE4D709F59CE4D0D6AA021000021214A800D0C23800144AFF73BAE15801EE5CC: 
6 vs 13 (pgsql error XX000) (aux msg ERROR:  Bad intent key, intent type set type expected in 
78000ABECD98D44306860849A73988383DDC7FFEBB5008C451EA7FE11A33, transaction from: 
47092C5307BB5422A8EE4D709F59CE4D0D6AA021000021214A800D0C23800144AFF73BAE15801EE5CC: 6 vs 13)
```

while fetching the locks from intentsdb at the tablet, we seem to be processing a txn rev record as opposed to a provisional record. and the downstream function errors out complaining that it isn't able to find the intent type set in `78000ABECD98D44306860849A73988383DDC7FFEBB5008C451EA7FE11A33` and the corresponding transactional source being `47092C5307BB5422A8EE4D709F59CE4D0D6AA021000021214A800D0C23800144AFF73BAE15801EE5CC`.

But we can observe that `47092C5307BB5422A8EE4D709F59CE4D0D6AA021000021214A800D0C23800144AFF73BAE15801EE5CC` is in fact the key that we should have processed, and `78000ABECD98D44306860849A73988383DDC7FFEBB5008C451EA7FE11A33` is nothing but a txn rev record, as it starts with `kTransactionId` (ASCII code 120 => 0x78). Still need to investigate how we end up processing this record.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9766]: https://yugabyte.atlassian.net/browse/DB-9766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Failed 1/1000 times on almalinux 8, fastdebug, gcc11, ba3761c73a7db1473141cc86c7a1fd033755102d (master).

```
./yb_build.sh fastdebug --gcc11 --cxx-test pgwrapper_pg_get_lock_status-test --gtest_filter PgGetLockStatusTest.TestPgLocksWhileDDLInProgress -n 1000 --tp 1
```

Since the test is relatively fast, total time took 7610 seconds.  There was no other significant load on the system.

```
2024-01-29 10:33:03.188 PST [1199822] ERROR:  Bad intent key, intent type set type expected in 7824DB19738BB1428FAC4AC7DEADFA8BC7DC7FFEBBDBE9175B2F7FE06193, transaction from: 474C30534ED7F64CFE834B64B7A118C4286E21BD000021214B8C0D0C238001442416E8A4D0801F9E6C: 143 vs 13
2024-01-29 10:33:03.188 PST [1199822] STATEMENT:  SELECT * FROM pg_locks
../../src/yb/yql/pgwrapper/pg_get_lock_status-test.cc:596: Failure
Failed
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:375): Fetch 'SELECT * FROM pg_locks' failed: 7, message: ERROR:  Bad intent key, intent type set type expected in 7824DB19738BB1428FAC4AC7DEADFA8BC7DC7FFEBBDBE9175B2F7FE06193, transaction from: 474C30534ED7F64CFE834B64B7A118C4286E21BD000021214B8C0D0C238001442416E8A4D0801F9E6C: 143 vs 13 (pgsql error XX000) (aux msg ERROR:  Bad intent key, intent type set type expected in 7824DB19738BB1428FAC4AC7DEADFA8BC7DC7FFEBBDBE9175B2F7FE06193, transaction from: 474C30534ED7F64CFE834B64B7A118C4286E21BD000021214B8C0D0C238001442416E8A4D0801F9E6C: 143 vs 13)
[m-1] W0129 10:33:03.625022 1199716 outbound_call.cc:480] RPC callback for RPC call 0x000025d476f3f600: yb.tserver.TabletServerService.GetTransactionStatus -> { remote: 127.0.0.2:18464 idx: 7 protocol: 0x00007fc50ab437c0 -> tcpc }, id: 1596, state: FINISHED_SUCCESS, transfer_state: FINISHED took 0.405s
[m-1] I0129 10:33:03.628875 1199854 catalog_manager.cc:4450] T 00000000000000000000000000000000 P 39af9d7a2f2540648002694ce86b115a: Table transaction succeeded: foo [id=000033c0000030008000000000004000]
```

Also hit this on pg15 branch fb3db0087ffeac09e050b122d72e65e83e31faaa.
