### ISSUE TITLE
[YSQL] Rename pgbench to ysql_bench

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#2078]
cc @schoudhury @rkarthik007 for your input on the name.

**Comment by rkarthik007** [comment]
My suggestion would be to make it `ysql_bench` to keep similarity with `pgbench`.

**Comment by nspiegelberg** [comment]
@rkarthik007, @ndeodhar : What are we planning to rename pg_dump to?  ysql_dump? Maybe we should follow a similar model everywhere.

**Comment by ndeodhar** [comment]
@nspiegelberg , yes `ysql_dump`
