### ISSUE TITLE
[YSQL] flaky test: PgBackendsTestRf3BlockNoLeaderLock.LeaderChangeInFlightNegative/0 and PgBackendsTestRf3BlockNoLeaderLock.LeaderChangeInFlightNegative/1

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20795]
Jira Link: [DB-9789](https://yugabyte.atlassian.net/browse/DB-9789)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=PgBackendsTestRf3BlockNoLeaderLock&fail_tag=all&name=LeaderChangeInFlightNegative%2F1&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9789]: https://yugabyte.atlassian.net/browse/DB-9789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
According to internal link https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgBackendsTestRf3BlockNoLeaderLock&fail_tag=all&name=LeaderChangeInFlightNegative%2F0&num_commits=500&platform=linux, the failure rate got worse and worse over time.  The failure reason I have diagnosed to be based on timing: the slower the execution of one thread, the more likely the failure.  It appears to be passing much more often in 2.20 branch's centos-clang16-tsan compared to alma8-clang17-tsan on master: only one failure (internal link https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=2.20&build_type=all&class=PgBackendsTestRf3BlockNoLeaderLock&fail_tag=all&name=LeaderChangeInFlightNegative%2F0&num_commits=500&platform=linux).  The difference in build types might play a role, but I think a bad commit in master is more likely.  This test could be used to find that bad commit, but it would take a lot of time.

The first failure on master in the last 500 commits is 05e1d44e.  I would pick a modest lower bound of 67ebdfb7 and upper bound of that 30d4173d (second failure) for a potential performance degradation that happened in master.

There was a second spike in failure rate increase around af01dc07.  I would pick a lower bound of e29e50fe for that.

There appears to be a third increase at around 4e7ddc1b, lower bound f900ea5b.

And a fourth around 03c9c4ca.
