### ISSUE TITLE
[YSQL] flaky test: org.yb.pgsql.TestPgRegressMatview.testPgRegressMatview	

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20796]
Jira Link: [DB-9790](https://yugabyte.atlassian.net/browse/DB-9790)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressMatview&fail_tag=all&name=testPgRegressMatview&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9790]: https://yugabyte.atlassian.net/browse/DB-9790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
According to internal link https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressMatview&fail_tag=all&name=testPgRegressMatview&num_commits=1000&num_fails=100&platform=all, this test started failing nearly 100% on alma8-clang17-tsan and alma8-gcc11-debug likely between 4ead4bb934..e75e20d386 (higher confidence interval is ad87ceb1..e75e20d386).  alma8-clang17-asan is also somewhat impacted.  It seems the impact is on slow-running builds.  The error is "test timed out after 1800 seconds".

Besides that, this test has been flaky for other reasons for a very long time.
