### ISSUE TITLE
[DocDB] RBS speed is 10x slower when gzip RPC compression is enabled

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#20848]
Jira Link: [DB-9835](https://yugabyte.atlassian.net/browse/DB-9835)
### Description

Unexpectedly slow RBS throughput, at 15-20mbps, despite cluster being single region multi az and using default 256mbps throttle.

```
T 5d8145aedb6b4c7d91101c79d97bab30 P 453d0ca9b25848f89242f431a2ce15cd: Remote client base: Downloaded file: 021050.sst.sblock.0; Stats: Total time: 411140.620 ms, iterations: 166, Transmission rate: 10806190, RateLimiter total time slept: 0 ms, Total bytes: 4442500401, CRC/verify rate: 12678155.106 bytes/msec (total_ms: 350.406), Append rate 1266725.210 bytes/msec (total_ms: 3507.075), File sync time 658.349ms
```

Nodes did not seem CPU or Disk overloaded.

After further investigation, this turned out to be specific to RPC compression being enabled, specifically, gzip compression made RBS about 10x slower!

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9835]: https://yugabyte.atlassian.net/browse/DB-9835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
We will follow up on the perf impact of setting smaller RBS chunk size and file new items based on that.
