### ISSUE TITLE
[YSQL/YCQL] Consistent multi-tablet snapshot

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#2086]
Doing #1970 and talking with @OlegLoginov , snapshots where created before distributed transactions. 

So multiple tablets(inside 1 table) may not be consistent with each other when doing a snapshot.

**Comment by kmuthukk** [comment]
yes - this is a known current limitation; we plan to work on it post 2.0.

**Comment by ddorian** [comment]
fixed in [2.2](https://docs.yugabyte.com/latest/manage/backup-restore/snapshot-ysql/) .
