### ISSUE TITLE
[DocDB][ASH] YBClient wait events are needed for YCQL but not for YSQL

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#20868]
Jira Link: [DB-9857](https://yugabyte.atlassian.net/browse/DB-9857)
### Description

Currently, we are showing YBClient wait events for YSQL workload as well. This is not necessary as we have PGGate calls as part of the wait event framework. 

However, YBClient events are needed for YCQL where we need to show the time that was spent in docDB layer. Refactor the code to ensure that YBClient events are not shown for YSQL but are shown for YCQL. 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9857]: https://yugabyte.atlassian.net/browse/DB-9857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Fixed as part of #21222
