### ISSUE TITLE
it forces to resolve master's hostnames instead of configured ip addresses 

### ISSUE THREAD

**Issue by mehrdadrad** [yugabyte/yugabyte-db#2087]
Jira Link: [DB-2446](https://yugabyte.atlassian.net/browse/DB-2446)
Once I configure the master addresses w/ their IP address as you can see at below but it tries to resolve master's hostname instead of the IP addresses which already configured at master.conf or tserver.conf
Looks it happens at some functionalities, not all connectivities. for example CSQL query.

```
E0808 17:43:24.921059 25456 process_context.cc:180] SQL Error: Execution Error. Read(tablet: 0f42388549d24b01ae52e52df66fda56, num_ops: 1, num_attempts: 329, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 2057688.671s (passed: 60.266s): Network error (yb/util/net/dns_resolver.cc:137): Resolve failed ip-10-2-0-243.us-west-1.compute.internal: Host not found (authoritative)
SELECT * FROM system.peers
```

root@ip-10-0-0-82:/home/ubuntu/yugabyte-1.3.0.0# cat etc/master.conf
```
--master_addresses=10.2.0.243:7100,10.0.0.82:7100,10.0.0.224:7100
--fs_data_dirs=/root/yugabyte-data
--webserver_interface=0.0.0.0 
--rpc_bind_addresses=0.0.0.0 
--replication_factor=3
--yb_num_shards_per_tserver=2
--placement_region=us-east
```
root@ip-10-0-0-82:/home/ubuntu/yugabyte-1.3.0.0# cat etc/tserver.conf 
```
--tserver_master_addrs=10.2.0.243:7100,10.0.0.82:7100,10.0.0.224:7100
--fs_data_dirs=/root/yugabyte-data
--webserver_interface=0.0.0.0
--placement_region=us-east
```
Version: 1.3.0.0

**Comment by kmuthukk** [comment]
hi @bmatican , @spolitov --

is this because the rpc_bind_addresses is specified as 0.0.0.0 instead of IP address?

**Comment by mbautin** [comment]
@mehrdadrad thank you for reporting this issue! Would you mind also sharing the yb-master / yb-tserver logs?

**Comment by mehrdadrad** [comment]
@mbautin I don't think so still I have a log but you can duplicate it at AWS from two diff region, for example, west and east.
try csql (bin/cqlsh) from one of follower not leader then you will see: 
```
csql couldn't connect on the follower hosts.
Connection error: ('Unable to connect to any servers', {'127.0.0.1': OperationTimedOut('errors=None, last_host=None',)})
```
the log line that i captured is only: 
```
E0808 17:43:24.921059 25456 process_context.cc:180] SQL Error: Execution Error. Read(tablet: 0f42388549d24b01ae52e52df66fda56, num_ops: 1, num_attempts: 329, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 2057688.671s (passed: 60.266s): Network error (yb/util/net/dns_resolver.cc:137): Resolve failed ip-10-2-0-243.us-west-1.compute.internal: Host not found (authoritative)
SELECT * FROM system.peers
```

**Comment by mehrdadrad** [comment]
1- removed the below line from /etc/hosts 
10.0.0.82       ip-10-0-0-82.us-east-2.compute.internal

2- ran cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': OperationTimedOut('errors=None, last_host=None',)})

3- the below line added to logs/yb-tserver.ERROR after step 2

E0819 21:07:31.923660  7743 process_context.cc:180] SQL Error: Execution Error. Read(tablet: 4ec7b118bad047fa92a4c43991c39ff9, num_ops: 1, num_attempts: 330, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 2079898.895s (passed: 60.215s): Network error (yb/util/net/dns_resolver.cc:137): Resolve failed ip-10-0-0-82.us-east-2.compute.internal: Host not found (authoritative)
SELECT * FROM system.peers
^^^^^^

Once I revert the /etc/hosts then everything works.

Note: I'm on a follower host and the below IP address is the leader:
10.0.0.82
