### ISSUE TITLE
[docs] Search results do not handle tabs well

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#2090]
Search results will lead to an empty page if that page has multiple tabs.
e.g. searching for `ulimit`, I can click on “Amazon Web Services”, which will lead me to https://docs.yugabyte.com/latest/deploy/public-clouds/aws/#create-aws-ec2-instances

`#create-aws-ec2-instances` is extra and screws up the display

**Comment by polarweasel** [comment]
Search works a lot better now :)
