### ISSUE TITLE
[DocDB] ThreadPool's signal on not_empty_ condition takes a long time

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#20912]
Jira Link: [DB-9894](https://yugabyte.atlassian.net/browse/DB-9894)
### Description

When adding a new task to ThreadPool, not_empty_.Signal() takes a long time. pthread_cond_signal shows up in thread stacks. This manifests as higher latency in WAL "commit" operation that cannot be attributed to fsync. This is most likely due to the new condition variable logic introduced in glibc 2.25 and manifests in non-Linuxbrew builds running on AlmaLinux 8.

![image (3)](https://github.com/yugabyte/yugabyte-db/assets/552936/6020db3c-c73b-45b0-8784-6e1b3bd32172)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9894]: https://yugabyte.atlassian.net/browse/DB-9894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mbautin** [comment]
One option for solving this is to instead of using a Raft thread pool token, use a Strand with an RPC thread pool, in hope it would not have the same Signal problem.

**Comment by mbautin** [comment]
Here is a screenshot of callsite profiling with D32353 applied on top of 9f3fe0bf47fba317650fb253ae169cd78b538300. Note that `not_empty_.Signal()` in `ThreadPool::DoSubmit` still shows up at the top, because there are still major uses of this ThreadPool class left, but the TPCC NewOrder latency should be largely resolved.
<img width="2516" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/552936/5ff310c5-880d-47d2-b60e-ab0d10682fb7">

**Comment by mbautin** [comment]
Metrics from the TPCC experiment above:

<img width="2230" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/552936/0ef4c868-f5c9-4090-8744-70eaa2654a01">

<img width="2371" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/552936/a6e64eb4-d042-4122-b893-5d131d693c57">

<img width="2328" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/552936/b85a19a0-8a57-483a-a39c-97295980beda">

**Comment by mbautin** [comment]
TPCC report from the above experiment:
<img width="1389" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/552936/443d452f-45f7-429a-b0b1-fce23fb2fa93">

**Comment by rthallamko3** [comment]
@mbautin , I am closing this as the backports have landed.
