### ISSUE TITLE
[YSQL] SPLIT AT should have a max limit

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2092]
Add a gflag based max limit for number of tablets that a table can be pre-split into.

**Comment by georgeklees** [comment]
Commit 35f3316e66346647ac56a28d64cc2b6195a8614f has landed the `SPLIT (INTO num_tablets TABLETS)` functionality. Currently it just hardcodes the limit as 50, but as explained above, we probably want to base it on a gflag.

**Comment by ndeodhar** [comment]
This is available using gflag `--max_num_tablets_for_table`
