### ISSUE TITLE
[DocDB] Tablet may stuck on shutting down in case of errors during bootstrapping

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#20977]
Jira Link: [DB-9953](https://yugabyte.atlassian.net/browse/DB-9953)
### Description

The user was complaining about the table is not completely deleted and there's one remaining tablet. Manual deletion failed with an error:
```
$ yb-ts-cli delete_tablet -force 2f03b94cbf464d05a298ebc31e592c69 "test"
Unable to delete tablet: IO error (yb/tools/ts-cli.cc:505): Failed to delete tablet: : code: TABLET_NOT_RUNNING status { code: ALREADY_PRESENT message: "State transition of tablet 2f03b94cbf464d05a298ebc31e592c69 already in progress: {2f03b94cbf464d05a298ebc31e592c69, opening tablet}" source_file: "../../src/yb/tserver/ts_tablet_manager.cc" source_line: 1617 errors: "\000" }
```
From the message and tablet report it was seen that the tablet had been stuck at the bootstrapping stage.
The following stack was observed in the threads dump:
```
Threads
 @ 0x7ffff66e300c __pthread_cond_wait
 @ 0x35cef9c yb::tablet::TransactionParticipant::Impl::StartS
 @ 0x353cd4f yb::tablet::Tablet::StartShutdown()
 @ 0x3532cf5 yb::tablet::Tablet::~Tablet()
 @ 0x3568c23 yb::tablet::TabletBootstrap::Bootstrap()
 @ 0x356531c yb::tablet::BootstrapTabletImpl()
 @ 0x357965b yb::tablet::BootstrapTablet()
 @ 0x374677d yb::tserver::TSTabletManager::OpenTablet()
 @ 0x3a7000d yb::ThreadPool::DispatchThread()
 @ 0x3a6b4f3 yb::Thread::SuperviseThread()
 @ 0x7ffff66de693 start_thread
 @ 0x7ffff6be041c __clone
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9953]: https://yugabyte.atlassian.net/browse/DB-9953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment]
The initial analysis:
The problem comes from this [thing](https://github.com/yugabyte/yugabyte-db/blob/916da9e6e35dcff2eb4dc1fcb53414b3328b93b2/src/yb/tablet/transaction_participant.cc#L2017) in `TransactionParticipant::Impl`
```
CountDownLatch shutdown_latch_{1};
```
When the transaction participant is created the mentioned latch is set to `1`, but on destroying a tablet we are [waiting](https://github.com/yugabyte/yugabyte-db/blob/916da9e6e35dcff2eb4dc1fcb53414b3328b93b2/src/yb/tablet/transaction_participant.cc#L224) for it to become `0`, and the only [place](https://github.com/yugabyte/yugabyte-db/blob/916da9e6e35dcff2eb4dc1fcb53414b3328b93b2/src/yb/tablet/transaction_participant.cc#L1337C8-L1337C20) where it can be set to `0` is `LoadFinished` of `TransactionParticipant::Impl`. However, there’s several scenarios when [this](https://github.com/yugabyte/yugabyte-db/blob/916da9e6e35dcff2eb4dc1fcb53414b3328b93b2/src/yb/tablet/tablet_bootstrap.cc#L623) method will not be triggered at all. If any error is happening between this line (after std::shared_ptr<Tablet> tablet(new Tablet(data_.tablet_init_data));) and [this](https://github.com/yugabyte/yugabyte-db/blob/916da9e6e35dcff2eb4dc1fcb53414b3328b93b2/src/yb/tablet/transaction_loader.cc#L450) check in `TransactionLoader::FinishLoad`, then the latch’s value will never go down and we will stuck until the tserver restart. And the stuck is happening in the underline call of the mentioned shared ptr destructor of the local variable.
I’d say it is a regression brought by [this](https://github.com/yugabyte/yugabyte-db/issues/10735) issue, and partially by [this](https://github.com/yugabyte/yugabyte-db/issues/16565) issue as it extended the number of scenarios where we can end up in the stuck state (by adding additional status ok-check in `TransactionLoader::Executor`).

**Comment by arybochkin** [comment]
Possible fix is to check the status of `tablet->Open()` and notify transaction participant about the error with further correct handling of the latches states:
```
    std::shared_ptr<Tablet> tablet(new Tablet(data_.tablet_init_data));
    // Doing nothing for now except opening a tablet locally.
    LOG_TIMING_PREFIX(INFO, LogPrefix(), "opening tablet") {
      RETURN_NOT_OK(tablet->Open());
    }
```

**Comment by rthallamko3** [comment]
A tablet can stay stuck in bootstrapping state till the next tserver restart. So it is worthwhile backporting the fix to stable branches.

**Comment by basavaraj29** [comment]
@rthallamko3 this issue exists in 2.18 as well. should we backport this fix to 2.18 too?

**Comment by rthallamko3** [comment]
@basavaraj29 , For high priority bugs, if the work is not too much, then yes please do.

**Comment by basavaraj29** [comment]
backport to 2.18 blocked on the following backports
1. https://github.com/yugabyte/yugabyte-db/issues/19359 (tried backporting it to 2.18, had other conflicts)
2. https://github.com/yugabyte/yugabyte-db/issues/18902 (this is straightforward once 1. is addressed)

so holding off on the backport for now.

**Comment by rthallamko3** [comment]
We discussed offline and determined that it is not worth backporting to 2.18 branch as it is STS and the odds of this issue happening is very low.
