### ISSUE TITLE
Document how to create read replicas

### ISSUE THREAD

**Issue by fastest963** [yugabyte/yugabyte-db#2097]
I can't find any documentation on how to create read replicas if you aren't using Platform. It looks like the universe config contains read replica configuration but I don't see any way to change that part of the config.

**Comment by rahuldesirazu** [comment]
Hi @fastest963. As of now, the only way to change the read replicas config is through the platform. We have a yb-admin command `modify_placement_info`, but this only changes the live replica placement info. Will add support to this command for read replicas and get back with steps needed to set up.

**Comment by rahuldesirazu** [comment]
Spec for a new yb-admin command to support adding, modifying, and deleting read replica placement infos:

// Add a new read replica cluster to the master config.
// Returns the placement uuid of the new cluster.
`add_read_replica_placement_info <placement_info> <replication_factor>`
`<placement_info> : "cloud1.region1.zone1,cloud2.region2.zone2,cloud3.region3.zone3 ..."`
'<replication_factor> : int (even or odd fine)`

// Modify an existing read replica placement info.
`modify_read_replica_placement_info <placement_uuid> <placement_info> <replication_factor>`
`<placement_uuid> : placement uuid from the add step`

// Delete a read replica placement info.
`delete_read_replica_placement_info <placement_uuid>`

cc: @kmuthukk

**Comment by kmuthukk** [comment]
@rahuldesirazu -- have we just just landed the code-commit, or the doc update has also landed? If the latter hasn't been done, we should either keep the issue open, or track it separately. Thanks!

**Comment by rahuldesirazu** [comment]
@kmuthukk Just the code commit, ill re-open the issue.

**Comment by rahuldesirazu** [comment]
@stevebang Wrote up docs for creating read replicas, closing this issue.
