### ISSUE TITLE
Terraform AWS deployment - issues adding additional instance

### ISSUE THREAD

**Issue by christopa** [yugabyte/yugabyte-db#2098]
I am deploying a 3 node instance cluster to AWS, and then after initial deployment I am adding a 4th node (with the intent on adding it as a master after removing existing node as master).  I've attached log files showing the 2 different deployment steps.

Issue 1: 
The new (4th) node does not have the cron job auto-scheduled....crontab is empty.

Issue 2:
I would expect that the new server would have the master and yserver processes setup as detailed in steps 2 & 3 on the following page:https://docs.yugabyte.com/latest/manage/change-cluster-config/
However, the yserver script does not contain the --tserver_master_addrs flag with the node settings.

Additional Question:
Is it possible in a terraform script to change the instance type and volume size and have that ONLY apply to new instances being setup, and not existing?

[add_1_additional_node_config.txt](https://github.com/YugaByte/yugabyte-db/files/3513403/add_1_additional_node_config.txt)
[initial_universe_3_node_config.txt](https://github.com/YugaByte/yugabyte-db/files/3513404/initial_universe_3_node_config.txt)

**Comment by christopa** [comment]
I also noticed, but didn't document this specifically, that the 4th node showed its location as datacenter -> rack1, rather than an actual zone, even though it ended up in us-east-1a.

**Comment by kmuthukk** [comment]
Thx for reporting this issue @christopa.

**Comment by ramkumarvs** [comment]
@christopa hey so looked into this issue, yeah we currently don't support change config from within terraform. As you pointed out in Issue 2. But Issue 1: is something will have a fix out today.

**Comment by ramkumarvs** [comment]
@christopa can you let us know if the terraform issues you faced are resolved now and we can close this issue?

**Comment by ramkumarvs** [comment]
Closing this issue, we have done quite a bit of improvements to our terraform scripts.
