### ISSUE TITLE
TestTimeuuidFunctions.testToTimestampFunction broken in CentOS

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#210]
Reported by @hectorgcr.

Consistently reproducing this error in my dev machine:

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.yb.cql.TestTimeuuidFunctions
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.332 s <<< FAILURE! - in org.yb.cql.TestTimeuuidFunctions
[ERROR] testToTimestampFunction(org.yb.cql.TestTimeuuidFunctions)  Time elapsed: 11.145 s  <<< FAILURE!
java.lang.AssertionError
	at org.yb.cql.TestTimeuuidFunctions.checkTimestampIsCloseToExpected(TestTimeuuidFunctions.java:67)
	at org.yb.cql.TestTimeuuidFunctions.testToTimestampFunction(TestTimeuuidFunctions.java:170)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestTimeuuidFunctions.testToTimestampFunction:170->checkTimestampIsCloseToExpected:67
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by ayushsengupta1991** [comment]
Closed by commit: https://github.com/YugaByte/yugabyte-db/commit/f3990b7ea1ab71d05f2545e50502008ca8d0fe37
