### ISSUE TITLE
[docdb] Add admin operations to facilitate maintenance operations

### ISSUE THREAD

**Issue by fastest963** [yugabyte/yugabyte-db#2105]
For rolling upgrades/restarts, admin operations are needed to flush the memstores and switch the leaders away from the soon-to-be-restarted tablet server. 

Ideally the restarts should be as less disruptive as possible and the restart (and associated replay of the write-ahead-txn/raft log) should be as quick as possible.

**Comment by fastest963** [comment]
This might be partially solved by https://github.com/yugabyte/yugabyte-db/commit/3561e4c4aee1311862a42995525fcc3c8b8a5d42 ?

**Comment by bmatican** [comment]
@fastest963 you're correct, the leader blacklisting functionality should cover one part of this. We need to do some more in house testing for that and document it.

Separately, we only have functionality now to flush an entire table. Having something like that, but for all the tablets on a TS, sounds like a good idea.

**Comment by bmatican** [comment]
Filed #2785 to work on per-TS flushes. Will close this for now @fastest963.
