### ISSUE TITLE
[DocDB] Drop database is failing due to replication checks on a deleted table.

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#21070]
Jira Link: [DB-10033](https://yugabyte.atlassian.net/browse/DB-10033)
### Description

Drop database is failing with the following error on a deleted table with the following error:

`Error ERROR:  Table: 00004008000030008000000000004000 is under replication. Cannot delete a database that contains tables under replication. ' occurred while cleaning up DB db4 .`

The issue seems to be the checks are being performed for dropped tables as well. The checks should have been only for live tables.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10033]: https://yugabyte.atlassian.net/browse/DB-10033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
.
