### ISSUE TITLE
[YSQL][doc] Document pgcrypto extension

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2108]

**Comment by stevebang** [comment]
@ndeodhar @m-iancu Is this considered documented? 
- The `pgcrypto` extension is included here: https://docs.yugabyte.com/latest/api/ysql/extensions/#pgcrypto
- Do we want more extensive documentation on this?

**Comment by ndeodhar** [comment]
This is good enough, thanks @stevebang. Closing this out.
