### ISSUE TITLE
[DocDB] Write Request check guarding against schema version changes doesn't work for colocated tablets.

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#21113]
Jira Link: [DB-10418](https://yugabyte.atlassian.net/browse/DB-10418)
### Description

This below check in `write_query.cc` is supposed to catch schema changes committed amidst write requests replication. But this doesn't work in the intended manner for colocated tablets.
```
CHECK_LE(metadata.schema_version(), sv.schema_version()) << ", status: " << status;
```

We need to fetch the corresponding table info of the colocated table before fetching its version.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10418]: https://yugabyte.atlassian.net/browse/DB-10418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@basavaraj29 , Can you elaborate what user behavior does this break? Is this limited to any feature in particular?

**Comment by basavaraj29** [comment]
> Can you elaborate what user behavior does this break
I don't see it breaking any feature for now, but we wouldn't know even if it did. 

here's what the check is supposed to do - it crashes the tserver IF the schema version changes amidst replication of a write. 
A write acquires the token `write_ops_being_submitted_counter_` after conflict resolution and moves on to the replication phase. Post successful replication, the check is supposed to make sure that there weren't any schema changes that bumped up the version in the meanwhile.

For colocated tablets, the check doesn't perform the above assertion (since we fetch the schema version of the host tablet and not the actual table being written to).

>  Is this limited to any feature in particular?
This is in the core write path.

**Comment by rthallamko3** [comment]
Will be covered as part of https://github.com/yugabyte/yugabyte-db/issues/22222.
