### ISSUE TITLE
[DocDB][ASH] Empty yql_endpoint_tserver_uuid for consensus, flushes and compactions

### ISSUE THREAD

**Issue by abhinab-yb** [yugabyte/yugabyte-db#21123]
Jira Link: [DB-10098](https://yugabyte.atlassian.net/browse/DB-10098)
### Description

Query id 1, 2, 3 and 4 correspond to internal background jobs which can have the `yql_endpoint_tserver_uuid` set.

```
yugabyte=# select query_id, yql_endpoint_tserver_uuid, count(*) from ash where yql_endpoint_tserver_uuid='00000000-0000-0000-0000-000000000000' group by query_id, yql_endpoint_tserver_uuid;
 query_id |      yql_endpoint_tserver_uuid       | count 
----------+--------------------------------------+-------
        3 | 00000000-0000-0000-0000-000000000000 | 15150
        2 | 00000000-0000-0000-0000-000000000000 |  2199
        4 | 00000000-0000-0000-0000-000000000000 |  1753
        0 | 00000000-0000-0000-0000-000000000000 |   584
        1 | 00000000-0000-0000-0000-000000000000 | 44892
(5 rows)

```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10098]: https://yugabyte.atlassian.net/browse/DB-10098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Fixed in https://github.com/yugabyte/yugabyte-db/issues/21167
