### ISSUE TITLE
[DocDB] Expose master's raft heartbeat delay for each follower as a metric

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#21178]
Jira Link: [DB-10113](https://yugabyte.atlassian.net/browse/DB-10113)
### Description

#18788  added a new RPC to expose the RAFT heartbeat delay for masters. Could we also expose this as a metric so that it can be alerted on?

@lingamsandeep @PrarabdhGarg 

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10113]: https://yugabyte.atlassian.net/browse/DB-10113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
@druzac - assigned this to you since you added the API. Ask is metric for the same issue.
