### ISSUE TITLE
[DocDB] flaky test: MemoryContextTypesTest.TestMCStl and MemoryContextTypesTest.TestMCTreeNode

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#21172]
Jira Link: [DB-10109](https://yugabyte.atlassian.net/browse/DB-10109)
### Description

Since upgrading to clang17 for ASAN

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=MemoryContextTypesTest&fail_tag=all&name=TestMCStl&platform=linux

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=MemoryContextTypesTest&fail_tag=all&name=TestMCTreeNode&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10109]: https://yugabyte.atlassian.net/browse/DB-10109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Looks to be fixed by Mikhail's change. The latest [report](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=MemoryContextTypesTest&fail_tag=all&name=TestMCStl&platform=linux) looks clean
