### ISSUE TITLE
[YSQL] Enable single-row optimizations for valid RETURNING expressions

### ISSUE THREAD

**Issue by JDNdeveloper** [yugabyte/yugabyte-db#2122]
Jira Link: [DB-2310](https://yugabyte.atlassian.net/browse/DB-2310)
In the fix for #1028 we are adding support for single-row optimization on UPDATE/DELETEs, however currently it only allows for simple RETURNING clauses that just specify columns. 

However this is too conservative, as there are valid single-row returning expressions (i.e. those that only use column values included in the query itself) that are more complex than just a standalone column.

Example of query that is currently (once diff lands) optimized:
`DELETE FROM t WHERE a = 1 RETURNING a;`

Example of query that is valid but is not optimized:
`DELETE FROM t WHERE a = 1 RETURNING a + 1`

This issue tracks adding optimization support for the latter case and all general expressions that only involve column values that are included in the query.

**Comment by sushantrmishra** [comment]
Tried the test in 2.17.2 -

```
yugabyte=# delete from t where a  =4 returning a+1;                                                            
----------
        5
(1 row)

DELETE 1
Time: 3.574 ms
```

**RPC Request:** 


`I0224 05:59:31.789927 29096 pg_session.cc:214] Applying operation: { WRITE active: 1 read_time: { read: <invalid> local_limit: <invalid> global_limit: <invalid> in_txn_limit: <invalid> serial_no: 0 } request: client: YQL_CLIENT_PGSQL stmt_id: 94902385901824 stmt_type: PGSQL_DELETE table_id: "000033eb000030008000000000004096" schema_version: 0 hash_code: 40623 ybctid_column_value { value { binary_value: "479EAF48800000042121" } } column_refs { } ysql_catalog_version: 23 partition_key: "9EAF" }`
