### ISSUE TITLE
[Docs] Update the documentation of EXPLAIN

### ISSUE THREAD

**Issue by abhinab-yb** [yugabyte/yugabyte-db#21225]
### Description

7df8abd1a2db3e2d8c6d7b9eac49d948617065cc updated some of the terminology for the EXPLAIN field names. The documentation should be updated to reflect the same.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by IshanChhangani** [comment]
9401342feee3138af05143dd26954509d5aa9453 updates the docs.
