### ISSUE TITLE
[docdb] Speedup local bootstrap: do not do LogReader::Open twice

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2124]
<img width="810" alt="Screen Shot 2019-08-21 at 8 42 20 PM" src="https://user-images.githubusercontent.com/395011/63484445-72925380-c454-11e9-9a6c-6b87620d1a3f.png">

Did a perf record/report during local bootstrap and noticed the above picture.

It seems that we are opening a `LogReader` instance twice and taking about the same time under it (whooping ~20%). I suspect we could unify that into one single instance, created in the `TabletBootstrap::OpenLogReader` path and then passed into the new `Log` instance explicitly...

cc @kmuthukk @rahuldesirazu @hectorgcr

**Comment by kmuthukk** [comment]
@bmatican - 
Nice find! Guessing this is an older issue and not related[ to recent optimization work](https://github.com/YugaByte/yugabyte-db/issues/1468) of trying to optimize which WALs to replay (and in the process somehow ending up opening the WAL twice)?

**Comment by bmatican** [comment]
Forgot to reply to this @kmuthukk , it's not related to that optimization work, nor a regression from @rahuldesirazu 's work on not rebuilding indexes, as much as before that, the code would need 2 passes to open the logs (rebuild, actually read) and we just never removed that, since his work was still under a feature flag.
