### ISSUE TITLE
[YSQL] Test org.yb.pgsql.TestPgParallelReadIsolation fails in release builds

### ISSUE THREAD

**Issue by andrei-mart** [yugabyte/yugabyte-db#21267]
Jira Link: [DB-10185](https://yugabyte.atlassian.net/browse/DB-10185)
### Description

The test requires Read Committed isolation, but it is disabled by default in release builds.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10185]: https://yugabyte.atlassian.net/browse/DB-10185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Still failing 100% in TSAN
