### ISSUE TITLE
[YW] version the Postgres container

### ISSUE THREAD

**Issue by aegershman** [yugabyte/yugabyte-db#2132]
Currently the YW postgres container is pulling `latest` (configured without a tag) so it could either get cached as "latest" and never be updated even if there's an actual upstream latest change, or more importantly, it could break existing implementation

https://github.com/YugaByte/charts/blob/master/stable/yugaware/templates/service.yaml#L87

**Comment by aegershman** [comment]
We just got bit by this because postgres 12 was released a few days ago. https://hub.docker.com/_/postgres?tab=tags

Now our yugaware is trying to be initialized with postgres 12

```sh
kubectl -n yugaware logs -f yugaware-yugaware-0 -c postgres
2019-10-15 16:51:24.592 UTC [1] FATAL:  database files are incompatible with server
2019-10-15 16:51:24.592 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.0 (Debian 12.0-2.pgdg100+1).
```

**Comment by rkarthik007** [comment]
Sorry to hear that @aegershman 😞
@ramkumarvs - can we please prioritize this fix, should be a quick one?

**Comment by aegershman** [comment]
All good, it can be mitigated with `kubectl edit sts yugaware` & changing `postgres` to `postgres:11`, but in the future having the `image`/`imageTag`, etc. being configurable/override-able and shipped with pinned defaults will prevent this. s'all good though 👌

**Comment by Arnav15** [comment]
Closed by: https://github.com/yugabyte/charts/pull/35
