### ISSUE TITLE
[Docs] Deploy to two data centers with xCluster replication

### ISSUE THREAD

**Issue by jasonriddell** [yugabyte/yugabyte-db#21335]
### Description

Broken image in the 2.14 version of this page.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
@jasonriddell Can you provide URL and heading, I can't find it...

**Comment by ddhodge** [comment]
LGTM possibly fixed in some other PR
