### ISSUE TITLE
[YSQL] The transaction is being committed though the client registers it as failed transaction (BankWorkload with VM restart)

### ISSUE THREAD

**Issue by SarveshKesharwani01** [yugabyte/yugabyte-db#21346]
Jira Link: [DB-10246](https://yugabyte.atlassian.net/browse/DB-10246)

Please find run report in JIRA description
### Description

testname: test_cdc_with_consistency_bank_tx_before_image

what we are doing:
- Running bank workloads, in parallel to nemesis [The team is running 5 basic BankTx workloads on 5 different tables]

observation:
- Bank workload stopped writing
- Workload log: http://stress.dev.yugabyte.com/files/get?name=f4f61e13-61ac-4bb6-a5c2-971ad4f88029-workload-73c3c8-SqlBankTransfer.20240307065159.log

initial analysis:
- The issue is most likely a severe consistency problem.

- 29365 2024-03-07 07:05:03.958 UTC [39165] LOG:  Restart isn't possible, data was already sent. Txn error code=3
29366 2024-03-07 07:05:03.958 UTC [39165] STATEMENT:  INSERT INTO test_cdc_ca0308 (id, balance) VALUES (12175, 5)
29367 2024-03-07 07:05:03.958 UTC [39165] FATAL:  terminating connection due to administrator command
29368 2024-03-07 07:05:03.965 UTC [38955] FATAL:  terminating connection due to administrator command

- 172.151.16.233 -> 07:05:03, restarted VM

- So, when restart VM happened, this tx,most likely "failed, but committed". From test, since it failed, we are trying to insert after that, which is resulting in duplicate constraint violation.
- This is not a regression or so, and this should be existing from a long time.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10246]: https://yugabyte.atlassian.net/browse/DB-10246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by qvad** [comment]
Transaction failed on client side during tserver restart - in this case client will get "Operation expired" error, which can mean that transaction is actually successful. 
In old version of workload any error meant that transaction is failed.

Issue is no longer reproducible after fixing workload.
