### ISSUE TITLE
[YSQL][Stress] WaitOnConflictBankWorkload reporting data inconsistencies for geo-partitioned universe in read committed isolation level

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#21359]
Jira Link: [DB-10255](https://yugabyte.atlassian.net/browse/DB-10255)
### Description

The workload runs fine for repeatable read and serializable isolation level

DB version: `2.21.1.0-b74`
Stress test run: http://stress.dev.yugabyte.com/stress_test/bb86d0df-9044-4dbc-9cc4-37d992ee627e
Logs: [xitJhlZNEI.zip](https://github.com/yugabyte/yugabyte-db/files/14533528/xitJhlZNEI.zip)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10255]: https://yugabyte.atlassian.net/browse/DB-10255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Based on @basavaraj29 's analysis, this is a test issue

The reader transaction is reading balance from multiple tables (across different statements).
```
            for (int table_id = 0; table_id < appConfig.numTablesToCreate; table_id++) {
                statement.execute(String.format("SELECT sum(balance) FROM %s;",
                        getTableName(table_id)));

                try (ResultSet rs = statement.getResultSet()) {
                    rs.next();
                    sum += rs.getInt(1);
                }
            }
```
and there are writer transactions updating values of these tables in parallel.
```
                    firstOpResult = evaluateUpdate(connection, String.format("UPDATE %s SET balance = balance - %s WHERE id = %s;",
                            getTableNameByKey(accFrom), balance, accFrom), timeout);
                    secondOpResult = evaluateUpdate(connection, String.format("UPDATE %s SET balance = balance + %s WHERE id = %s;",
                            getTableNameByKey(accTo), balance, accTo), timeout);
```
with RC, we shouldn't expect to see a consistent snapshot of the database, so the assertion logic in the test is expected to fail.
consider the below, with v for both keys a (tab1) ,b (tab2) - 1000
```
UPDATE tab1 SET v=v-100 WHERE k=a;
                                                                 SELECT sum(balance) FROM tab1; // will read 1000 for key a.
UPDATE tab2 SET v=v+100 WHERE k=b;
COMMIT;
                                                                 SELECT sum(balance) FROM tab2; // will read 1100 for key b.
```
and the assertion logic will fail. this is totally possible with RC. but the same cannot happen with RR/Serialization isolation levels.
