### ISSUE TITLE
[yugabyted][UI] List the Scheduled PITR on yugabyted UI

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#21355]
Jira Link: [DB-10252](https://yugabyte.atlassian.net/browse/DB-10252)
### API

Create a new `/pitr` endpoint for sending the list of scheduled PITRs.

### UI

Create a new screen in the `database` page for listing the scheduled PITRs.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10252]: https://yugabyte.atlassian.net/browse/DB-10252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ShikharSahay** [comment]
Code changes landed.

**Comment by ShikharSahay** [comment]
Completed.
