### ISSUE TITLE
Change number of tablets per tserver for localhost installs

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#2137]
Change `yugabyte-db`, `yb-ctl` and `yb-docker-ctl` to pass 2 tablets per tserver explicitly for YSQL installs.

**Comment by rkarthik007** [comment]
@d-uspenskiy - could you please add the flags that need to be passed for this.

**Comment by kmuthukk** [comment]
@rkarthik007 is referring the new ysql* specific gflag.
