### ISSUE TITLE
Change the default_transaction_isolation to 'repeatable read'

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#2140]
Jira Link: [DB-1803](https://yugabyte.atlassian.net/browse/DB-1803)
Because `repeatable read` is the least strict isolation level that YugaByte DB supports, this command:
```
show default_transaction_isolation
```
should show that value. In Version 1.3.1 it shows `read committed` — which value is inherited from PostgreSQL where it means what it says.

Please change this shipped file:
```
/<wherever>/yugabyte-data/<some node>/disk-1/pg_data/postgresql.conf
```
accordingly.

Notice that, just as in PostgreSQL, `repeatable read` produces the semantic effect that the literature calls "snapshot".

**Comment by m-iancu** [comment]
See also #5683. We plan to address this by making READ COMMITTED isolation our actual default after pessimistic locking is done. @pkj415 We should create an issue for that and close this one.

**Comment by robertsami** [comment]
https://github.com/yugabyte/yugabyte-db/issues/15272
