### ISSUE TITLE
[DocDB] flaky test: XClusterTopologiesTestClusterFailure.TestBroadcastWithConsumerFailure

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#21424]
Jira Link: [DB-10306](https://yugabyte.atlassian.net/browse/DB-10306)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=XClusterTopologiesTestClusterFailure&fail_tag=all&name=TestBroadcastWithConsumerFailure&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10306]: https://yugabyte.atlassian.net/browse/DB-10306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Test Passed last 100 runs
