### ISSUE TITLE
[YCQL] Index backfill not happening automatically when index is created on a table which has transactions enabled = false

### ISSUE THREAD

**Issue by KavyaShivashankar** [yugabyte/yugabyte-db#21431]
Jira Link: [DB-10313](https://yugabyte.atlassian.net/browse/DB-10313)
### Description

 Index backfill not happening when index is created on a table which has transactions enabled = false.  As a result, all the existing records that were present in the table before the index was created,  are not accessible with the indexed column.

```
ycqlsh> CREATE KEYSPACE ks;
ycqlsh> USE ks;
ycqlsh:ks> CREATE TABLE orders (id int PRIMARY KEY, warehouse int);
ycqlsh:ks> INSERT INTO orders (id, warehouse) VALUES (1, 1);
ycqlsh:ks> select * from orders;

 id | warehouse
----+-----------
  1 |         1

(1 rows)
ycqlsh:ks> select * from orders where id = 1;

 id | warehouse
----+-----------
  1 |         1

(1 rows)
ycqlsh:ks> select * from orders where warehouse = 1;

 id | warehouse
----+-----------
  1 |         1

(1 rows)
ycqlsh:ks> CREATE INDEX ON orders (warehouse) WITH transactions = { 'enabled' : false, 'consistency_level' : 'user_enforced' };
ycqlsh:ks> EXPLAIN SELECT * FROM orders WHERE warehouse = 1;

 QUERY PLAN
------------------------------------------------------------
 Index Only Scan using ks.orders_warehouse_idx on ks.orders
   Key Conditions: (warehouse = 1)

ycqlsh:ks> select * from orders;

 id | warehouse
----+-----------
  1 |         1

(1 rows)
ycqlsh:ks> select * from orders where id = 1;

 id | warehouse
----+-----------
  1 |         1

(1 rows)
ycqlsh:ks> EXPLAIN SELECT * FROM orders WHERE warehouse = 1;

 QUERY PLAN
------------------------------------------------------------
 Index Only Scan using ks.orders_warehouse_idx on ks.orders
   Key Conditions: (warehouse = 1)

ycqlsh:ks> SELECT * FROM orders WHERE warehouse = 1;

 id | warehouse
----+-----------

(0 rows)
ycqlsh:ks> INSERT INTO orders (id, warehouse) VALUES (2, 2);
ycqlsh:ks> SELECT * FROM orders WHERE warehouse = 2;

 id | warehouse
----+-----------
  2 |         2

(1 rows)
ycqlsh:ks> SELECT * FROM orders WHERE warehouse = 1;

 id | warehouse
----+-----------

(0 rows)
ycqlsh:ks> SELECT * FROM orders ;

 id | warehouse
----+-----------
  1 |         1
  2 |         2

```

If the index is dropped and recreated, both the records are not accessible by the indexed column which is ```warehouse```.   The records are accessible when column ```id``` is used.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10313]: https://yugabyte.atlassian.net/browse/DB-10313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
The documentation `docs/content/preview/api/ycql/ddl_create_index.md` says

> An error is raised if transactions have not be enabled using the `WITH transactions = { 'enabled' : true }` clause on the table to be indexed. This is because secondary indexes internally use distributed transactions to ensure ACID guarantees in the updates to the secondary index and the associated primary key. More details [here](https://www.yugabyte.com/blog/yugabyte-db-1-1-new-feature-speeding-up-queries-with-secondary-indexes/).
