### ISSUE TITLE
[YSQL] Do not query DocDB when range column condition is `IN (NULL, NULL)`

### ISSUE THREAD

**Issue by rajukumaryb** [yugabyte/yugabyte-db#2143]
create table tab(i int, j int, k int, primary key(i, j));
insert into tab values(1, 1, 1), (1, 2, 2), (1, 3, 3), (1, 4, 4);
select * from tab where i = 1 and j in (null, null);

The current implementation didn't optimize this case.  It does a FULL scan on the table when it should have just return 0 row right away.

**Comment by tedyu** [comment]
As of commit 95b9358d91b0e06358ddde5be197dda32f032865 :
```
yugabyte=# explain analyze select * from tab where i = 1 and j in (null);
                                     QUERY PLAN
-------------------------------------------------------------------------------------
 Result  (cost=0.00..0.00 rows=0 width=12) (actual time=0.003..0.004 rows=0 loops=1)
   One-Time Filter: false
 Planning Time: 0.126 ms
 Execution Time: 0.055 ms
(4 rows)
```
