### ISSUE TITLE
[YSQL] Wrong query result with JSONB column and index

### ISSUE THREAD

**Issue by fhchen3** [yugabyte/yugabyte-db#21451]
Jira Link: [DB-10335](https://yugabyte.atlassian.net/browse/DB-10335)
### Description

My coworker (JB) discovered this Yugabyte YSQL bug (yugabyte-2.20.1.3for linux-x86_64) and was able to come out the minimal test case (shown below) to demonstrate it:

"The IndexScan hint is not really part of the bug itself, but is needed for the test case to get the optimizer to use the index without the partial index filter in the original scenario.  The JSONB column is required to cause the bug.  Normal columns in the index/query do not seem to trigger the issue" - JB

*****  test case  starts  ******
```sql
drop table IF EXISTS t1;
create table t1 (
c1 bigint,
c2 jsonb,
primary key ((c1))
);
insert into t1 (c1,c2) values (1,'{"c3":1,"c4":1}');
insert into t1 (c1,c2) values (2,'{"c3":2,"c4":2}');
create index t1_idx on t1 (
((c2->>'c3'),
(c2->>'c4')) hash
);
```
Table rows:
```sql
select * from t1;
 c1 |         c2         
----+--------------------
  2 | {"c3": 2, "c4": 2}
  1 | {"c3": 1, "c4": 1}
(2 rows)

```
Fails by returning rows:
```sql
/*+IndexScan(t1 t1_idx)*/
--explain
select * from t1
where (c2->>'c3') = '4';

c1 |         c2        
----+--------------------
  2 | {"c3": 2, "c4": 2}
  1 | {"c3": 1, "c4": 1}
(2 rows)

```
Works correctly:

```sql
/*+IndexScan(t1 t1_idx)*/
--explain
select * from t1
where (c2->>'c3') = '4'
and (c2->>'c4') = '4';

c1 | c2
----+----
(0 rows)
```
**** test case ends******

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10335]: https://yugabyte.atlassian.net/browse/DB-10335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Thank you @fhchen3 

I was able to replicate it and fixed a little bit the body of the issue to make it more clear. 

We'll look into it.
