### ISSUE TITLE
[DocDB] SELECT fails with ERROR: UpdateTransaction: tablet_id: "5d94f5de25cc4bb4bfc2d0b0d7117457" state .....passed its deadline 74303.900s (passed: 6.524s): Aborted (yb/tablet/transaction_coordinator.cc:349): Replication failed

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#21453]
Jira Link: [DB-10336](https://yugabyte.atlassian.net/browse/DB-10336)
### Description

Tried on version: **2.21.0.0-b540**

Logs: [https://drive.google.com/file/d/1WSdc9G2pKx4HbhdFyEjJfQlA0_4YpbNv/view?usp=sharing](https://drive.google.com/file/d/1WSdc9G2pKx4HbhdFyEjJfQlA0_4YpbNv/view?usp=sharing)
Encountered the following errors during a SELECT:
 Note: This issue was seen only 2-3 times in a total run of run 50+ hours
`
ERROR: UpdateTransaction: tablet_id: "5d94f5de25cc4bb4bfc2d0b0d7117457" state { transaction_id: "\021\205\265*k\343E\344\246*\245m\274.\251\265" status: COMMITTED tablets: "09f5fac7fae94a47a65286091673c235" tablets: "af45529e203b4de888ab16e843dbd628" aborted { } } propagated_hybrid_time: 7003773860988100608, retrier: { task_id: -1 state: kRunning deadline: 74303.900s } passed its deadline 74303.900s (passed: 6.524s): Aborted (yb/tablet/transaction_coordinator.cc:349): Replication failed
`

`
ERROR: UpdateTransaction: tablet_id: "5d94f5de25cc4bb4bfc2d0b0d7117457" state { transaction_id: "\024\314\r\272n\274HJ\277\004\022\277U\311\210\314" status: COMMITTED tablets: "12fbebb4f3eb477a8ace3865cdbb0cf7" tablets: "a79adb2ba97449e98382e0142315d001" tablets: "274e8a2df721431c960caaf73ec6622d" tablets: "ef5315d8168842f68af3b4ac42f203c7" tablets: "93b86ad45f3e4dc78dfaec8f497b96d9" tablets: "efc30e5d62de42369e55528a27671f53" tablets: "b653cd20dde7425d8fedeef8f21d9893" tablets: "9cd781575d7c4558a824199138cbfb26" tablets: "63bf26017fc241b08ea88a12257fa66d" tablets: "b79db8c5ca744ca1acf871dbb1d937b1" tablets: "b5c58cbe670f439199dc64706cce1d80" tablets: "cbefc446e5fe4befb64a50025e29dd06" aborted { } } propagated_hybrid_time: 7003773860070961152, retrier: { task_id: -1 state: kRunning deadline: 74303.677s } passed its deadline 74303.677s (passed: 6.750s): Aborted (yb/consensus/replica_state.cc:641): Operation aborted by new leader
`

Sample app details:
```
80 parallel write threads
10 inserts, 4 updates, 2 selects and 2 deletes in each transaction
```

G-flags:
Tserver:
```
--consistent_restore=true
--enable_automatic_tablet_splitting=true
--enable_deadlock_detection=true
--enable_stream_compression=true
--enable_wait_queues=true
--scheduled_full_compaction_check_interval_min=5
--scheduled_full_compaction_frequency_hours=12
--scheduled_full_compaction_jitter_factor_percentage=100
--stream_compression_algo=1
--yb_enable_read_committed_isolation=true
--ysql_num_shards_per_tserver=1
--ysql_output_buffer_size=16214400
```
Master:
```
--consistent_restore=true
--enable_automatic_tablet_splitting=true
--enable_deadlock_detection=true
--enable_stream_compression=true
--enable_wait_queues=true
--stream_compression_algo=1
--tablet_split_high_phase_shard_count_per_node=200000
--tablet_split_high_phase_size_threshold_bytes=2097152
--tablet_split_low_phase_shard_count_per_node=160000
--tablet_split_low_phase_size_threshold_bytes=102400
--yb_enable_read_committed_isolation=true
--ysql_output_buffer_size=16214400
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10336]: https://yugabyte.atlassian.net/browse/DB-10336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by basavaraj29** [comment]
the error here is not on SELECT(s) but on COMMIT(s).
```
2024-03-08 13:48:54.313 UTC [1299497] ERROR:  UpdateTransaction: tablet_id: "5d94f5de25cc4bb4bfc2d0b0d7117457" ... Aborted (yb/consensus/replica_state.cc:641): Operation aborted by new leader
2024-03-08 13:48:54.313 UTC [1299497] STATEMENT:  COMMIT

2024-03-08 13:48:54.314 UTC [1299875] ERROR:  UpdateTransaction: tablet_id: "5d94f5de25cc4bb4bfc2d0b0d7117457" ... Replication failed
2024-03-08 13:48:54.314 UTC [1299875] STATEMENT:  COMMIT
```
looks like there is a status tablet leader change due to which the queued commit operations get aborted. In normal path, they do get retried, but looks like the deadline for these statements too has passed, and hence we stream back the error to the user without any further retries.
