### ISSUE TITLE
[DocDB] Fix Flaky test GeoTransactionsPromotionConflictAbortTest.TestConflictAbortBeforeNewHeartbeat

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#21456]
Jira Link: [DB-10338](https://yugabyte.atlassian.net/browse/DB-10338)
### Description

The test tries to simulate a race between transactions and assert that the high pri txn successfully aborts the low pri txn. But there is no proper synchronization between these sessions, and the low pri txn could commit in the meanwhile. Fix this.

Note: This is a test only issue. The test is supposed to catch a data inconsistency problem with txn promotion, but the test failures have nothing to do with that.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10338]: https://yugabyte.atlassian.net/browse/DB-10338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
There is indeed a chance of test failing due to the low priority transaction committing early, but this requires the high priority starting + inserting triggering the abort taking longer than 1 second (non-TSAN)/3 seconds (TSAN); looking at test history it consistently takes less than that, and the current flakiness (~5%) is pretty much entirely due to a more general issue with either geo transaction tests or mini cluster tests not shutting down properly after the test has finished.

**Comment by es1024** [comment]
Related: #20518 where the time needed to trigger the described failure were increased.

**Comment by basavaraj29** [comment]
@es1024, I observed that the lower pri txn commits and the high pri txn errors out on the first insert for 2.21.0 backport. 

The test failed on both debug and tsan builds. here's the detective [link](https://detective-gcp.dev.yugabyte.com/D33080/). is it that we are missing some relevant backport on 2.21.0 then?

**Comment by es1024** [comment]
@basavaraj29 https://github.com/yugabyte/yugabyte-db/commit/0214819b324e165c98e9cb5e0a8ff4f0526ebe7a is indeed not in 2.21.0, it's present in 2.21.1+

**Comment by basavaraj29** [comment]
ah, makes sense. since the test flags a crucial consistency issue, would be nice to have the timing fix in 2.21.0 and 2.20 as well I guess, your call. 

closing this issue then, thanks Eric.
