### ISSUE TITLE
[DOCS] Missing yb-admin reference page

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#2152]
Missing a reference doc page for `yb-admin` like https://docs.yugabyte.com/latest/admin/yb-ctl/

**Comment by stevebang** [comment]
@ramkumarvs The files in the repo are correct -- is this a caching issue?

**Comment by ddorian** [comment]
@stevebang this is for `yb-admin`, I don't see anything on the docs.

**Comment by stevebang** [comment]
Closing -- yb-admin page has been added to the CLI reference here: https://docs.yugabyte.com/latest/admin/yb-admin/

https://github.com/yugabyte/yugabyte-db/pull/2652
