### ISSUE TITLE
[YSQL] Incorrect rows returned during  sql query

### ISSUE THREAD

**Issue by archit-rastogi** [yugabyte/yugabyte-db#21529]
Jira Link: [DB-10411](https://yugabyte.atlassian.net/browse/DB-10411)
### Description

Stress run: 
http://stress.dev.yugabyte.com/stress_test/43b89ebe-0c5c-498e-954c-96066b959631

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10411]: https://yugabyte.atlassian.net/browse/DB-10411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment]
Query: https://github.com/yugabyte/yb-stress-test/blob/pq_perf_lst/src/apps/tpcc/yb/queries/2.sql
Query plan: http://stress.dev.yugabyte.com/files/get?name=18a4499e-64e7-480d-92b0-8e56a12aca8e-analyze_without_pq_workers_2.sql.out

BNL there is incorrectly planned.
There are two nested BNLs, outer one sets partkey, and inner one sets suppkey.
The Index Scan using partsupp_pkey on partsupp correctly updates the index filter, however it also has a regular filter with a SubPlan which also depends on the partkey, but the reference in the subplan is not batched.

It seems that dependency of that kind should prevent BNL.

**Comment by rthallamko3** [comment]
Can we check if 2.20 backport is needed as well. cc @tanujnay112

**Comment by tanujnay112** [comment]
I think this was fixed by db8eb2596daa8150b03d67b7e3595cd300d169d9
@archit-rastogi  Can you confirm this on a more recent release?

**Comment by sushantrmishra** [comment]
@archit-rastogi Were you able to verify this issue as per @tanujnay112 's [suggestion](https://github.com/yugabyte/yugabyte-db/issues/21529#issuecomment-2021686816) ?

**Comment by archit-rastogi** [comment]
Confirmed in stress run http://stress.dev.yugabyte.com/stress_test/a59b848d-bc85-466c-a0f0-0fce2d731194
on build 2.23.0.0-b141 above bug did not reproduce.

**Comment by rthallamko3** [comment]
@archit-rastogi , Then should we close the issue?
