### ISSUE TITLE
[YSQL] flaky test: org.yb.ysqlconnmgr.TestSessionParameters.testSessionParameters

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#21523]
Jira Link: [DB-10407](https://yugabyte.atlassian.net/browse/DB-10407)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.ysqlconnmgr.TestSessionParameters&fail_tag=all&name=testSessionParameters&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10407]: https://yugabyte.atlassian.net/browse/DB-10407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Fixed by ed0c69e1f40ef15116c1b3e4d1faa3279b7f257b
