### ISSUE TITLE
[2DC] Add metrics for 2DC replication

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2154]
- Replication lag for tablets and tables (for table, it'll be max(replication lag) across all tablets).
- Replication Lag in terms of time.
- Replication Lag in terms of number of pending operations.

**Comment by nspiegelberg** [comment]
Metric Design Considerations:
 - Rollup Granularity: (server, table) or (cdcstream_id)
 - TServer Metrics Sink: master or prometheus
 - Definition of lag: hybrid_time, txn_id, committed(txn_id)

System Considerations:
 - Idle Tablet won't have updated transactions, so min(hybrid_time) won't work trivially
 - src_table_name/id and dst_table_name/id could be different

**Comment by nspiegelberg** [comment]
Producer / Consumer / Both???

Granularity = ProducerTabletInfo{consumer_uuid, stream_id, producer_tablet_id}
Metrics
  - stream_replication_lag
  - stream_rpc_latency
  - stream_rpcs_responded
  - stream_bytes_responded
  - stream_rpcs_proxy_forwarded [Producer Only]

**Comment by bmatican** [comment]
Adding @rahuldesirazu as well, to figure out how we want to expose these in YW. Two thoughts:
- Special metrics row for CDC related metrics, but this feels like it would lose a lot of granularity (multiple CDC streams?). Could be a cheap way to start though.
- New universe tab, maybe after `Metrics`, related to 2DC, if we want to expose more data, like what streams are available, to what clusters and also metrics...

cc @ndeodhar

**Comment by apatrida** [comment]
Is there any way programmatically to see the replication lag metric outside of monitoring tools?

**Comment by hari90** [comment]
@apatrida not in the regular non-transactional xCluster.
Transactional xCluster has a yb-admin command [get-xcluster-safe-time](https://docs.yugabyte.com/preview/admin/yb-admin/#get-xcluster-safe-time) with the `include_lag_and_skew` option
