### ISSUE TITLE
[DocDB] flaky test: CDCSDKYsqlTest.TestAtomicDDLRollback

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#21558]
Jira Link: [DB-10442](https://yugabyte.atlassian.net/browse/DB-10442)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestAtomicDDLRollback&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10442]: https://yugabyte.atlassian.net/browse/DB-10442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
`o.y.pg.PgRegrMisc.PgRegrMiscSerial3` also started failing after this diff cc @tverona1 , TBD if you want a diff GH issue for it

**Comment by myang2021** [comment]
I will create a separate issue for PgRegrMiscSerial3 failure.
