### ISSUE TITLE
[DocDB] flaky test: GeoPartitionedReadCommiittedTest.TestPromotionAmidstConflicts

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#21557]
Jira Link: [DB-10441](https://yugabyte.atlassian.net/browse/DB-10441)
### Description

```
[ts-1] WARNING: ThreadSanitizer: data race (pid=92444)
[ts-1]   Write of size 4 at 0x7b60000e5140 by thread T114 (mutexes: write M0):
[ts-1]     #0 yb::client::YBSubTransaction::SetActiveSubTransaction(unsigned int) ${BUILD_ROOT}/../../src/yb/client/transaction.cc:207:30 (libyb_client.so+0x485576)
...
[ts-1]   Previous read of size 4 at 0x7b60000e5140 by thread T92:
[ts-1]     #0 yb::client::YBSubTransaction::active() const ${BUILD_ROOT}/../../src/yb/client/transaction.h:198:12 (libyb_client.so+0x488803)
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10441]: https://yugabyte.atlassian.net/browse/DB-10441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
We discussed that backports are not be needed as of the moment.
