### ISSUE TITLE
Paths to clients mentioned in yb-ctl status are incorrect

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#2157]
build/latest/bin/cqlsh 
build/latest/bin/ysqlsh  
build/latest/bin/redis-cli   

mentioned in yb-ctl status 
are not really present at these paths

12:25 $ ./bin/yb-ctl status
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : build/latest/bin/ysqlsh                                                    |
| YCQL Shell          : build/latest/bin/cqlsh                                                     |
| YEDIS Shell         : build/latest/bin/redis-cli                                                 |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /Users/sanketh/yugabyte-data                                               |
----------------------------------------------------------------------------------------------------

**Comment by schoudhury** [comment]
@iSignal this does not seem accurate in the context of the release build -- can you pls clarify?
