### ISSUE TITLE
[yugabyted] Docker image won't start second time when there are more than one databases saved in the volume

### ISSUE THREAD

**Issue by sillen102** [yugabyte/yugabyte-db#21584]
Jira Link: [DB-10475](https://yugabyte.atlassian.net/browse/DB-10475)
### Description

Attemting to run Yugabyte with docker compose but the container cannot be restarted once there is more than one database created.

I ran YugabyteDB and created two logical databases. I use docker volumes to persist data between runs.

The problem is the second run, when I stop the container without removing the volumes and try starting again, the container won't start properly. It keeps running (it doesn't die) but is stuck. The log outputs `UI ready` but the expected `Data placement constraint successfully verified` is never displayed in the logs and the database isn't reachable.

This makes it virtually impossible to run YugabyteDB locally on my machine and do testing.

My system:

M1 MacBook Pro with Sonoma 14.4 (I have had this issue on previous versions of MacOS as well before upgrading)

Images tried:

2.20.2.0-b145 (amd64 using Rosetta)
2.18.6.0-b73 (arm64)
2.20.1.3-b3 (arm64)
2.20.1.3-b3 (amd64 using Rosetta)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10475]: https://yugabyte.atlassian.net/browse/DB-10475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
@sillen102 can you get some logs from the db? Using `yugabyted collect_logs` ?

And whats your docker compose file?

> but the container cannot be restarted once there is more than one database created

Can you explain what commands you're running here?

**Comment by cjbottaro** [comment]
I have something similar, but not exact the same. When the Yugabyte container is first created, it runs fine. But if I restart my computer and then try to startup the container again, it fails with exit 137.

Docker logs show all good though:
```
$ docker logs aw-yugabyte
Starting yugabyted...
✅ YugabyteDB Started
✅ UI ready
✅ Data placement constraint successfully verified
```

But Docker Compose shows that it exits immediately.
```
$ docker compose up -d
[+] Running 12/13
 ✔ Container aw-elasticsearch7  Healthy                                                                                  0.6s
 ✔ Container aw-statsd          Healthy                                                                                  0.6s
 ✔ Container aw-scylla          Healthy                                                                                  0.6s
 ✔ Container aw-postgres        Healthy                                                                                  0.6s
 ✔ Container aw-faktory         Healthy                                                                                  0.6s
 ✔ Container aw-nats            Healthy                                                                                  0.6s
 ✔ Container aw-localstack      Healthy                                                                                  0.6s
 ✔ Container aw-memcached       Healthy                                                                                  0.6s
 ✔ Container aw-scylla-old      Healthy                                                                                  0.6s
 ✔ Container aw-redis           Healthy                                                                                  0.6s
 ✔ Container aw-elasticsearch5  Healthy                                                                                  0.6s
 ✔ Container aw-mailhog         Healthy                                                                                  0.6s
 ⠧ Container aw-yugabyte        Waiting                                                                                  0.7s
container aw-yugabyte exited (137)
```

I'm also using Docker volumes.

**Comment by ddorian** [comment]
@cjbottaro you need to get the logs like I described in https://github.com/yugabyte/yugabyte-db/issues/21584#issuecomment-2008834778

**Comment by cjbottaro** [comment]
I'm not sure how to run `yugabyted collect_logs` without exec'ing into the container which is not possible because the container won't stay running.

**Comment by ddorian** [comment]
@cjbottaro it should be in `~/var/logs`. You can mount the filesystem & zip manually and upload.

**Comment by cjbottaro** [comment]
The logs don't exist at that location.
```
$ docker cp aw-yugabyte:/home/yugabyte/var/log .
Error response from daemon: Could not find the file /home/yugabyte/var/log in container aw-yugabyte
```

I poked around in a running container and couldn't find the logs anywhere either.
```
[root@7e7559b8232b yugabyte]# ls
auto_flags.json  cores	master		  openssl-config  pylib  tools	  tserver_flags.xml	 www
bin		 lib	master_flags.xml  postgres	  share  tserver  version_metadata.json
```

I tried looking in some of those dirs, like `lib`, `postgres`, `master`, and `tserver`. I found some broken links.
```
[root@7e7559b8232b yugabyte]# head master/logs
head: cannot open 'master/logs' for reading: No such file or directory

[root@7e7559b8232b yugabyte]# ls -l master/logs
lrwxrwxrwx 1 root root 30 Aug 29 16:50 master/logs -> /mnt/disk0/yb-data/master/logs
```

Maybe that's a hint? Thanks for the help.

**Comment by cjbottaro** [comment]
Oh, I was wrong. We've not using volumes. Here's our docker compose.
```
  yugabyte:
    profiles: ["datastores"]
    container_name: aw-yugabyte
    image: yugabytedb/yugabyte:2024.1.2.0-b77
    command:
      - bin/yugabyted
      - start
      - --background=false
```

So yeah, when the container gets stopped or the computer/vm restarted, then the container won't come back up.

**Comment by ddorian** [comment]
@cjbottaro  So, can you get the logs?

**Comment by cjbottaro** [comment]
The logs do not exist in the location you specified. I tried looking in other locations and couldn't find anything either. See my previous comment for more details: https://github.com/yugabyte/yugabyte-db/issues/21584#issuecomment-2492114485

**Comment by ddorian** [comment]
Then you've lost the data somehow?  Since there's no data even in /mnt/disk0/yb-data/ like you mentioned in your comment.
