### ISSUE TITLE
[CDCSDK] Catchup on lagging CDC stream takes a long time

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#21611]
Jira Link: [DB-10504](https://yugabyte.atlassian.net/browse/DB-10504)
### Description

CDC can take a very long time to catch up a lagging stream, to the point where it catching up takes longer than executing the transactions that it's catching up; it will then be permanently behind if the workload is not paused or reduced.

This is easier to reproduce after fixes for #21290 and #21580, where we are now able to let large amounts of intents build up with minimal performance impact on the normal read/write paths.

Example workload to reproduce:
- RF3 3x c5.4xlarge, single AZ, 4m row table, WAL/intent retention set to 20 days
- CDC stream created and bootstrapped, but client is blocked and not requesting/accepting any CDC updates
- 10 hours of 6 threads doing pure single-row updates wrapped in full transactions
- After updates finish, CDC client is unblocked

For over 11 hours afterwards, CDC is stuck reading from WALs only (no intentsdb reads), with very low CPU activity (<100% on one core) and low disk active I/O time (~5%). All read I/Os are from the following codepath:
```
    @     0x56428c8b36ae  yb::PosixRandomAccessFile::Read()
    @     0x56428b3b4c0e  yb::log::ReadableLogSegment::ReadEntryBatch()
    @     0x56428b2e5873  yb::consensus::LogCache::ReadOps()
    @     0x56428b2d630b  yb::consensus::PeerMessageQueue::ReadFromLogCache()
    @     0x56428b306246  yb::consensus::RaftConsensus::ReadReplicatedMessagesForCDC()
    @     0x56428afb0440  yb::cdc::GetConsistentWALRecords()
    @     0x56428afbae5c  yb::cdc::GetChangesForCDCSDK()
    @     0x56428af6e941  yb::cdc::CDCServiceImpl::GetChanges()
    @     0x56428b067983  std::__1::__function::__func<>::operator()()
    @     0x56428b06a0af  yb::cdc::CDCServiceIf::Handle()
    @     0x56428c143a0f  yb::rpc::ServicePoolImpl::Handle()
    @     0x56428c0607af  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x56428c1531b3  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x56428c959223  yb::Thread::SuperviseThread()
    @     0x7f5257cbf1ca  start_thread
    @     0x7f5257f10e73  __GI___clone
```

There are only 252 GB WALs on one node, but >700 GB in read syscalls from the above codepath (and still increasing at time test was stopped).

### Source connector version

n/a

### Connector configuration

n/a

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10504]: https://yugabyte.atlassian.net/browse/DB-10504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Per Suranjan, there is a config in connector 'polling.interval' that can increase the rate of polling. We can make it 0 ms to catch up. By default it is 500 ms or so.
