### ISSUE TITLE
[CDCSDK] Enforce relationship between CDC retention gflags

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#21610]
Jira Link: [DB-10503](https://yugabyte.atlassian.net/browse/DB-10503)
### Description

We currently have a pair of gflags: cdc_wal_retention_time_secs and cdc_intent_retention_ms, but implicitly require that cdc_intent_retention_ms <= cdc_wal_retention_time_secs. This should be made explicit in code (error check/using appropriate values when not true).

### Source connector version

n/a

### Connector configuration

n/a

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10503]: https://yugabyte.atlassian.net/browse/DB-10503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
cc @hari90 , @suranjan

**Comment by hari90** [comment]
This needs a flag callback on both flags that will FATAL if the incorrect value is set. cc @suranjan as its cdcsdk only
