### ISSUE TITLE
Possible issue with concurrent updates to a CQL list

### ISSUE THREAD

**Issue by iSignal** [YugaByte/yugabyte-db#2162]
Simplified version of the issue:

CREATE TYPE bar (
   start bigint
);

CREATE TABLE test {
  id UUID PRIMARY KEY,
  foo LIST<FROZEN<bar>>
} with transactions = { 'enabled' : true };

with a query that looks like

UPDATE test SET foo = foo + [{start:111}] WHERE id = F8B9FF57-5DFB-4DB3-B2FA-5EDC99A626DC;
 
that was executed concurrently from multiple threads.

The reported bug was that the latest thread overwrites the data inserted by previous threads.

**Comment by iSignal** [comment]
https://phabricator.dev.yugabyte.com/differential/diff/34557/

**Comment by kmuthukk** [comment]
Closing as this is a duplicate of #2163.
