### ISSUE TITLE
[DocDB][DB Clone][YSQL] Read/Write fails in cloned DB's table if db clone is happened in between 2 alter table commands

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21629]
Jira Link: [DB-10524](https://yugabyte.atlassian.net/browse/DB-10524)
### Description

**Version**: **2.23.0.0-b36**
**Steps**:

1. Create database(demo1) and create snapshot schedule
2. Create table
3. Alter table and drop a column
4. Collect time(t1)
5. Alter same table and add same column
6. Clone demo1 to demo2 at time t1

**Observations**:
1. Clone happens and if user tries to read/write to the cloned table(demo2's table) then it throws
`ERROR:  schema version mismatch for table 00004029000030008000000000004000: expected 2, got 1`

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10524]: https://yugabyte.atlassian.net/browse/DB-10524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
Closing as it has been fixed as part of fixing #21016
