### ISSUE TITLE
[YW] latest YW has kubectl 1.10, incompatible with k8s 1.14+

### ISSUE THREAD

**Issue by aegershman** [yugabyte/yugabyte-db#2166]
Using YW chart 1.3.2
kubernetes 1.14.5 on PKS on Amazon

After upgrading from Kubernetes 1.13.5 to 1.14.5, during universe provisioning, we get the following error:

```
Failed to execute task java.util.concurrent.FutureTask@1762de0e, hit error java.lang.RuntimeException: error: SchemaError(io.k8s.api.extensions.v1beta1.RollbackConfig): invalid object doesn't have additional properties.
```

[From some googling](https://stackoverflow.com/questions/55417410/kubernetes-create-deployment-unexpected-schemaerror/56578732) this appears to be because of skew in the version of `kubectl` used. 

[Kubectl has a guaranteed version skew of +/- 1 minor version, and best effort beyond that](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl)

The version packaged with the latest YW is `1.10.2`. From the yugaware container:

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

I verified this by getting the latest `kubectl` version available onto the yugaware container like so:

```sh
kubectl -n yugaware exec -it yugaware-yugaware-0 -c yugaware -- /bin/bash

# while kube exec'd into yugaware...

wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl

chmod +x kubectl

mv kubectl $(which kubectl)

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

I then tried provisioning a new universe, and it worked just fine.

I also tried using `kubectl-1.11.0` and it also worked fine. But even so, kubectl 1.10.2 is 4 minor versions behind; we are fortunate that it was working with 1.13.5 because it was technically unsupported. At the cost of increasing the size of the yugaware container, multiple `kubectl` versions should be included as drivers that YW can use to communicate with the cluster.

**Comment by Arnav15** [comment]
Bumped kubernetes version to 1.15.2
