### ISSUE TITLE
[YSQL] Enhancements to 13000/statements 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#21735]
Jira Link: [DB-10606](https://yugabyte.atlassian.net/browse/DB-10606)
### Description

We should add following columns to 13000/statements page. 

Column name | Type | References | Description
-- | -- | -- | --
userid | oid | pg_authid.oid | OID of user who executed the statement
dbid | oid | pg_database.oid | OID of database in which the statement was executed
local_blks_hit | bigint |   | Total number of local block cache hits by the statement
local_blks_read | bigint |   | Total number of local blocks read by the statement
local_blks_dirtied | bigint |   | Total number of local blocks dirtied by the statement
local_blks_written | bigint |   | Total number of local blocks written by the statement
temp_blks_read | bigint |   | Total number of temp blocks read by the statement
temp_blks_written | bigint |   | Total number of temp blocks written by the statement

userid	oid	[pg_authid](https://www.postgresql.org/docs/11/catalog-pg-authid.html).oid	OID of user who executed the statement
dbid	oid	[pg_database](https://www.postgresql.org/docs/11/catalog-pg-database.html).oid	OID of database in which the statement was executed

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10606]: https://yugabyte.atlassian.net/browse/DB-10606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by anmalysh-yb** [comment]
Seems like this ticket is about the same: 

https://github.com/yugabyte/yugabyte-db/issues/14612
