### ISSUE TITLE
[DocDB] Unexpected new leader in same term FATAL in unmount/mount scenario

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21808]
Jira Link: [DB-10702](https://yugabyte.atlassian.net/browse/DB-10702)
### Description

noticed new FATAL with mount/unmount scenario for data dir
**Versions**: `2024.1.0.0-b28` and `2.23.0.0-b68`

```
F20240401 09:58:23 ../../src/yb/consensus/raft_consensus.cc:1846] T c0b03355f35245d29e9d9ead3b572c5e P ce201f258ac44093ac8f606474dcd16d [term 2 FOLLOWER]: Unexpected new leader in same term! Existing leader UUID: 859333d2378347e3a3e7ab4fb8967136, new leader UUID: efb17ac83e36401e89ac14d1be4a29bc
  @   0xaaaab8f14a7c google::LogMessage::SendToLog()
  @   0xaaaab8f15920 google::LogMessage::Flush()
  @   0xaaaab8f15fbc google::LogMessageFatal::~LogMessageFatal()
  @   0xaaaab9427da4 yb::consensus::RaftConsensus::CheckLeaderRequestUnlocked()
  @   0xaaaab9423624 yb::consensus::RaftConsensus::UpdateReplica()
  @   0xaaaab9406e34 yb::consensus::RaftConsensus::Update()
  @   0xaaaaba57ec24 yb::tserver::ConsensusServiceImpl::UpdateConsensus()
  @   0xaaaab949877c std::__1::__function::__func<>::operator()()
  @   0xaaaab9499484 yb::consensus::ConsensusServiceIf::Handle()
  @   0xaaaaba1a4014 yb::rpc::ServicePoolImpl::Handle()
  @   0xaaaaba0f2d40 yb::rpc::InboundCall::InboundCallTask::Run()
  @   0xaaaaba1b3248 yb::rpc::(anonymous namespace)::Worker::Execute()
  @   0xaaaaba99ca98 yb::thread::SuperviseThread()
  @   0xffff9d3078b8 start_thread
  @   0xffff9d363afc thread_start
```

**Steps**:
1. Create universe with multiple volumes
2. Run workload for some time
3. Unmount one of the volume in any one node
4. Wait for some time(let workload run for some time)
5. Restart tserver and then noticed above mentioned FATAL

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10702]: https://yugabyte.atlassian.net/browse/DB-10702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Since the crash is a result of in-memory state, the state gets cleared after tserver restart. As such, it is not important to backport to older stable releases.
