### ISSUE TITLE
[DocDB] Do not count UNKNOWN tablet replicas as RUNNING for load balancing

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#21840]
Jira Link: [DB-10740](https://yugabyte.atlassian.net/browse/DB-10740)
### Description

The `UNKNOWN` tablet replica state is used for tablets that have not reported in the current term. We currently treat `UNKNOWN` tablets as `RUNNING` in the load balancer to "maintain the existing behavior":
```
    // The 'UNKNOWN' tablet state was introduced as a pre-'RUNNING' state. Treat 'UNKNOWN' as a
    // 'RUNNING' state to maintain the existing behavior.
    if (tablet_state == tablet::UNKNOWN || tablet_state == tablet::RUNNING) {
      RETURN_NOT_OK(AddRunningTablet(tablet_id, ts_uuid, replica.fs_data_dir));
```
This seems incorrect, because the tablet replica could actually be `BOOTSTRAPPING`. If we had 3 `RUNNING` replicas and one `UNKNOWN` (actually `BOOTSTRAPPING`), we currently count this as over-replication and would try to remove a replica, causing under-replication.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10740]: https://yugabyte.atlassian.net/browse/DB-10740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by druzac** [comment]
Addressed by 68f1e4de438aa69f2dd085790e9326da0e77ab5c.
