### ISSUE TITLE
[Docs][Clone DB] Document the Lightweight local cluster writeable clone as of time feature details

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21867]
### Description

Document the Clone DB/ Lightweight local cluster writeable clone as of time feature details
1. How feature works
2. All yb-admin commands with parameter details with examples
3. Limitations and pre-requisites 
4. Roadmap/planned tasks details

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by yamen-haddad** [comment]
A public-facing doc about instant database cloning has been written and is accessible [here](https://docs.yugabyte.com/preview/manage/backup-restore/instant-db-cloning/).
