### ISSUE TITLE
[DocDB][DB Clone] Read/Write to Cloned DB fails if clone happened while index backfill is running on source DB

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21868]
Jira Link: [DB-10766](https://yugabyte.atlassian.net/browse/DB-10766)
### Description

**Version**: `2.23.0.0-b97`

**Steps**:
1. Create database demo1 and create snapshot schedule
2. Create table(table_1) and load more data
3. Collect time t1
4. Start a workload to load some more data to table(table_1)
5. Create an index to the table_1 and Clone DB(demo1) to demo2 while index backfill is in progress

**Observations**:
1. Clone DB command works
2. If user tries to read/write to the Cloned DB table then it throws below error
`ERROR:  schema version mismatch for table 00004104000030008000000000004000: expected 8, got 2`

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10766]: https://yugabyte.atlassian.net/browse/DB-10766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
Fixed as a result of fixing #21016
