### ISSUE TITLE
[docs] install doc is not completed 

### ISSUE THREAD

**Issue by rogerlzp** [yugabyte/yugabyte-db#2187]
hey guys, 
i follow the document https://docs.yugabyte.com/latest/contribute/core-database/build-from-src.
after build successfully, what else can I do?

first I setup a cluster and meet the issue  [#2082](https://github.com/YugaByte/yugabyte-db/issues/2082), from the comments in the related issues, it is fixed but not yet published.
so I tried to build it from the code.

after build successfully, the whole release directory is not quite the same as download 1.3.1 directly. 
can I just copy the files needed to the 1.3.1 dir or what else should I can do from here?

any help is highly appreciated.

**Comment by kmuthukk** [comment]
@mbautin, @bmatican :

Looks like the docs cover up to the step: 

./yb_build.sh release

which is good for running local tests and such.

Can we share with @rogerlzp the subsequent steps needed to then prepare the release artifacts (including the ysql initdb snapshot) similar to how a release that we build and post, such as https://downloads.yugabyte.com/yugabyte-1.3.1.0-linux.tar.gz, might look like.

**Comment by rogerlzp** [comment]
@kmuthukk , thanks very much.
that's exactly what I want.

Or with another, just showing us on how to replace the old part (take 1.3.1 for example) with  newly built part is enough for us to try the fix in our env.

**Comment by ttyusupov** [comment]
@rogerlzp , you can run `./yb_release --force` to prepare release build archive. Since commit https://github.com/YugaByte/yugabyte-db/commit/ed20a0ccc8465cbdd6c9147c5a3b13d87517013d it also takes care of recreating initdb snapshot, so no need to do it manually.

**Comment by bmatican** [comment]
Thanks for jumping in @ttyusupov !

We should definitely add a section in that side of the docs for this! cc @stevebang
