### ISSUE TITLE
[yugabyted] Support for YugabyteDB version upgrades using yugabyted CLI

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#21888]
Jira Link: [DB-10790](https://yugabyte.atlassian.net/browse/DB-10790)
### Description

Current user journey -

1. Stop the yugabyted node one at a time
2. restart the yugabyted node with the new YB release
3. run the post-upgrade tasks using `yugabyted configure admin_operations` (wrapper for yb-admin) or directly execute `yb-admin` commands.

For the 3rd step, yugabyted should perform `finalize upgrade` natively without having to use the `yb-admin` commands. 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10790]: https://yugabyte.atlassian.net/browse/DB-10790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ShikharSahay** [comment]
Code changes landed.
