### ISSUE TITLE
[YSQL] Catalog_manager creates duplicate table in case `CREATE TABLE` fails with "relation already exists" error

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#2192]
Jira Link: [DB-4838](https://yugabyte.atlassian.net/browse/DB-4838)
In case of creating duplicate table `CREATE TABLE` fails with "relation already exists" but catalog_manager creates a table

Steps to reproduce:
- create table twice, check second attempt fails 
```
postgres=# create table my_tbl(i int);
CREATE TABLE
postgres=# create table my_tbl(i int);
ERROR:  relation "my_tbl" already exists
postgres=# 
```
- check list of tables on WebUI or call `yb-admin list_tables | grep my_tbl`. There are two occurrence of `my_tbl`
- try create table once again and check the catalog_manager now have three occurrence of `my_tbl`

**Comment by m-iancu** [comment]
Closing, this has been fixed in latest.
