### ISSUE TITLE
[DocDB][ASH] Enhance the test framework to catch unset ASH metadata

### ISSUE THREAD

**Issue by abhinab-yb** [yugabyte/yugabyte-db#21941]
Jira Link: [DB-10857](https://yugabyte.atlassian.net/browse/DB-10857)
### Description

The existing ASH testing framework should catch unset (zero) ASH metadata

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10857]: https://yugabyte.atlassian.net/browse/DB-10857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
@abhinab-yb  We already do this for some of the ash-metadata fields : See https://phorge.dev.yugabyte.com/diffusion/YBDB/browse/master/src/yb/integration-tests/wait_states-itest.cc$209 for top_level_node_id.

Are there any specific fields that you had in mind to ensure they are not empty? `WaitStateTestCheckMethodCounts::VerifyRowsFromASH() ` could be extended to verify the same for other fields as well.

**Comment by abhinab-yb** [comment]
The other fields could be zero, if field has not been set yet and we capture a sample, or intentionally, e.g. the client node ip for internal tasks, or if some code path has not been instrumented yet.
