### ISSUE TITLE
ERROR: Failed waiting for None tservers, got None

### ISSUE THREAD

**Issue by rava-dosa** [YugaByte/yugabyte-db#2194]
I tried the getting started guide. I closed the existing redis server running on port 6379. OS :- Ubuntu 18.04.1, linux kernel :- 4.15.0-58-generic. 
**Error**
user@user-Aspire-E5-575G:~/Downloads/yugabyte-1.3.1.0$ ./bin/yb-ctl create
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1874, in <module>
    control.run()
  File "./bin/yb-ctl", line 1851, in run
    self.args.func()
  File "./bin/yb-ctl", line 1641, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1487, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
Viewing file /tmp/tmp28nJ7i:
2019-08-30 15:48:57,506 INFO: Starting master-1 with:
/home/user/Downloads/yugabyte-1.3.1.0/bin/yb-master --fs_data_dirs "/home/user/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/user/Downloads/yugabyte-1.3.1.0 --webserver_doc_root "/home/user/Downloads/yugabyte-1.3.1.0/www" --replication_factor=1 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100 --use_initial_sys_catalog_snapshot >"/home/user/yugabyte-data/node-1/disk-1/master.out" 2>"/home/user/yugabyte-data/node-1/disk-1/master.err" &
2019-08-30 15:48:57,524 INFO: Starting tserver-1 with:
/home/user/Downloads/yugabyte-1.3.1.0/bin/yb-tserver --fs_data_dirs "/home/user/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/user/Downloads/yugabyte-1.3.1.0 --webserver_doc_root "/home/user/Downloads/yugabyte-1.3.1.0/www" --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1:5433 >"/home/user/yugabyte-data/node-1/disk-1/tserver.out" 2>"/home/user/yugabyte-data/node-1/disk-1/tserver.err" &
2019-08-30 15:48:57,526 INFO: Waiting for master and tserver processes to come up.
2019-08-30 15:48:58,600 INFO: Waiting for master leader election and tablet server registration.
2019-08-30 15:49:43,509 ERROR: Failed too many times. CMDLINE=['/home/user/Downloads/yugabyte-1.3.1.0/bin/yb-admin', '--master_addresses', '127.0.0.1:7100', 'list_all_tablet_servers'] RETCODE=1 OUTPUT=
I0830 10:19:43.502635  5601 mem_tracker.cc:250] MemTracker: hard memory limit is 6.512537 GB
I0830 10:19:43.502740  5601 mem_tracker.cc:252] MemTracker: soft memory limit is 5.535656 GB
Error: Leader not ready to serve requests. (yb/master/scoped_leader_shared_lock.cc:92): Unable to list tablet servers: Leader not yet ready to serve requests: leader_ready_term_ = -1; cstate.current_term = 1

2019-08-30 15:49:44,510 ERROR: Failed waiting for None tservers, got None
^^^ Encountered errors ^^^
**df -h**
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           785M  2.1M  783M   1% /run
/dev/sda6       405G  248G  137G  65% /
tmpfs           3.9G  133M  3.8G   4% /dev/shm

**/proc/meminfo**
MemTotal:        8033988 kB
MemFree:          253264 kB
MemAvailable:    3456512 kB
Buffers:         1301620 kB
Cached:          2229364 kB
SwapCached:        27632 kB
Active:          4760112 kB

**sudo netstat -pnltu | grep yb**
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      5105/yb-tserver     
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      5105/yb-tserver     
tcp        0      0 127.0.0.1:9042          0.0.0.0:*               LISTEN      5105/yb-tserver     
tcp        0      0 127.0.0.1:11000         0.0.0.0:*               LISTEN      5105/yb-tserver     
tcp        0      0 127.0.0.1:7000          0.0.0.0:*               LISTEN      5102/yb-master      
tcp        0      0 127.0.0.1:7100          0.0.0.0:*               LISTEN      5102/yb-master      
tcp        0      0 127.0.0.1:12000         0.0.0.0:*               LISTEN      5105/yb-tserver     
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      5105/yb-tserver 

**yb-tserver logs**
Log file created at: 2019/08/30 10:19:30
Running on machine: user-Aspire-E5-575G
Application fingerprint: version 1.3.1.0 build 16 revision f10e23d319a5e5df008467d19ebab95ce631a977 build_type RELEASE built at 31 Jul 2019 06:43:06 UTC
Running duration (h:mm:ss): 0:00:10
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0830 10:19:30.485718  5341 call_home.cc:208] Unable to read url http://127.0.0.1:9000/rpcz

[t server logs](https://gist.github.com/rava-dosa/97daaf17bac4264127f28565f51556c3)

**yb-master logs**
[yb master logs](https://gist.github.com/rava-dosa/46eb872bf16b602c70cb25de4cf0039d)

**Comment by ttyusupov** [comment]
Hi @rava-dosa , seems it takes more than 2 minutes for yb-master to fully start, which is most probably caused by using HDD. Can you try using `--timeout-yb-admin-sec` and `--timeout-processes-running-sec` options with for example `1000` as a value?

**Comment by rava-dosa** [comment]
It worked. Thanks @ttyusupov
