### ISSUE TITLE
[DocDB] Aborted Transaction Due to Deadline Exceeded and Planned Step Down

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#22025]
Jira Link: [DB-10942](https://yugabyte.atlassian.net/browse/DB-10942)
### Description

Tried on version **2.23.0.0-b127**

Logs: [https://drive.google.com/file/d/15mqU4GcPGUcHAI4qFaSrcTNnA7EWNTP0/view?usp=sharing](https://drive.google.com/file/d/15mqU4GcPGUcHAI4qFaSrcTNnA7EWNTP0/view?usp=sharing)
Encountered the following error while running a test with aggressive conflicts.
`
ERROR: UpdateTransaction: tablet_id: "22dec840262941a7b17b5d50898c5b52" state { transaction_id: "o\\250R\\024\\035\\224At\\260Y\\326\\372\\360RP#" status: COMMITTED tablets: "76972154d781476cb64906178b245fe6" aborted { } } propagated_hybrid_time: 7017608876808302592, retrier: { task_id: -1 state: kRunning deadline: 2076.470s } passed its deadline 2076.470s (passed: 5.629s): Aborted (yb/consensus/raft_consensus.cc:1207): Rejecting because of planned step down
`

Table details:
```
private static final Map<String, WocTable> testTables = Map.of(
            "many_columns_large_rows", new WocTable(table_name="many_columns_large_rows", db_name="db1", num_of_coulmns=500, is_colocated=true),
            "less_columns_small_values", new WocTable(table_name="less_columns_small_values", db_name="db1", num_of_coulmns=300, is_colocated= true),
            "less_columns_large_rows", new WocTable(table_name="less_columns_large_rows", db_name="db2", num_of_coulmns=50, is_colocated=false)
    );
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10942]: https://yugabyte.atlassian.net/browse/DB-10942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Doesn't look like a problem. @basavaraj29 to close it out after verification.

**Comment by basavaraj29** [comment]
The above failure happens on the commit path. for failed commit rpcs, we do retry the operation with a default deadline of 5 secs controlled by `transaction_rpc_timeout_ms`, and in this case the deadline seems to have passed.
