### ISSUE TITLE
[YSQL][ASH] Track system catalog requests

### ISSUE THREAD

**Issue by abhinab-yb** [yugabyte/yugabyte-db#22021]
Jira Link: [DB-10938](https://yugabyte.atlassian.net/browse/DB-10938)
### Description

Currently, the system catalog requests are not instrumented, so we see the ASH metadata fields for some samples in TServer as zeroed out.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10938]: https://yugabyte.atlassian.net/browse/DB-10938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hbhanawat** [comment]
Duplicate of #20676
