### ISSUE TITLE
[YSQL] Allow non-superuser to undo the impact of Analyze

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#22028]
Jira Link: [DB-10945](https://yugabyte.atlassian.net/browse/DB-10945)
### Description

Currently when we run analyze, then `pg_class.reltuples` gets updated and this info  is used for query planning. 
To undo the side effects of  analyze , we need to reset the reltuples count in pg_class. 

```
yugabyte=# update pg_class set reltuples = 0 where relname = 'foo';
UPDATE 1
```

This operation is only allowed for superuser though in YBM since we do not give superuser access, hence for YBM cluster customers are not able to do this by themselves. 

One possible solution is :  we can create function with security definer function which can take relations Name as input and set relutples for that relation.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10945]: https://yugabyte.atlassian.net/browse/DB-10945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mtakahar** [comment]
The undo analyze command/function should follow the same rules what the current user can analyze.

Non-superusers can analyze any table they they own or in the database they own with an exception of shared tables. `reltuples` of indexes are populated when ANALYZE is run against the underlying table except for the indexes on TOAST relations.

| | tables in the databases owned by the user | tables in other databases |
|--|--|--|
|tables owned by the user| Yes | Yes |
|pg_toast.*| no | no |
|pg_toast_temp.*| no | no |
|pg_catalog.*| Yes | no |
|information_schema.*| Yes | no |
|tables in other schemas| Yes | no |
|shared tables| no | no |


* tables owned by the user: pg_class.relowner = current_user::regrole
* tables in the databases owned by the user: pg_database.datdba = current_user::regrole
* shared tables: pg_class.relisshared = true
* Even a superuser cannot create an analyze-able relation in the pg_toast or the pg_toast_temp schemas at the first place.
* Only a superuser can analyze shared tables.
