### ISSUE TITLE
[YCQL] get error when trying to select data with ycqlsh

### ISSUE THREAD

**Issue by zeinali-ali** [yugabyte/yugabyte-db#22022]
Jira Link: [DB-10939](https://yugabyte.atlassian.net/browse/DB-10939)
### Description

hi
I'm trying to use ycqlsh inside a cqlsh-shell inside Kubernetes and I'm getting this error:

`SELECT * FROM messaging_db.messages limit 10;
`
> 'ascii' codec can't encode characters in position 559-563: ordinal not in range(128)

uisng `kubectl run cqlsh-shell -it --rm  --image yugabytedb/yugabyte-client --command -- ycqlsh yb-tservers.yb-demo.svc.cluster.local 9042` to connect to cluster

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.

[DB-10939]: https://yugabyte.atlassian.net/browse/DB-10939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @zeinali-ali ,

What version of yugabytedb & os are you using?
Can you provide a sample table + row so we can reproduce?

**Comment by zeinali-ali** [comment]
I'm using yugabyte helm-chart
Image: `yugabytedb/yugabyte:2.20.0.0-b76`
kube-engine : `RKE2`
OS: `CentOS Stream`

```
CREATE TABLE IF NOT EXISTS messaging_db.messages (
	pId TEXT,
	id BIGINT,
	message TEXT,
	PRIMARY KEY((pId), id)
) WITH CLUSTERING ORDER BY (id DESC) AND transactions = { 'enabled' : true };

INSERT INTO TABLE messaging_db.messages VALUES ("test@1", 1, "تست");

SELECT * FROM messaging_db.messages;
```

**Comment by ddorian** [comment]
> OS: CentOS Stream

Please specify a version?

I fixed a bit your code above.

Can you try this workaround https://stackoverflow.com/a/68888460/12118516 ?
Or this https://stackoverflow.com/a/68284037/12118516 ?

Does any of those make it work for you?

**Comment by zeinali-ali** [comment]
> Can you try this workaround https://stackoverflow.com/a/68888460/12118516 ?
this one worked, thanks.
