### ISSUE TITLE
[2DC] Add ability to bootstrap consumers from previously existing data on producers

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2206]
[Placeholder task for now, design will follow]

This is necessary both on initial Stream creation, as well as on the fault tolerance path, if a tablet falls behind.

cc @ndeodhar @nspiegelberg @hectorgcr @rahuldesirazu

**Comment by nspiegelberg** [comment]
Duplicate of #3319, #3036
