### ISSUE TITLE
[DocDB] GFlag 'enable_automatic_tablet_splitting' class is incorrect

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#22088]
Jira Link: [DB-11007](https://yugabyte.atlassian.net/browse/DB-11007)
### Description

While trying to Setup XCluster config observing following error from YBA: Create Cluster config request failed: Auto Flags: Configure Replication [enable_automatic_tablet_splitting] set on universe puppyfood-2024-xcluster-source are not set on universe puppyfood-2024-xcluster-target

This is happening because only flags with class 3 and class 4 are considered for XCluster, but the target has that flag's class set to 4 and thus the source and the target are not compatible.

The issue started from 2.20.2 with additional QA itests. 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11007]: https://yugabyte.atlassian.net/browse/DB-11007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Reopening for 2.20 backport.

**Comment by arybochkin** [comment]
Backported to 2.20, hence closing
