### ISSUE TITLE
[DocDB] Conflicting query fails with Write/ Read RPC timeout 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#22096]
Jira Link: [DB-11022](https://yugabyte.atlassian.net/browse/DB-11022)
### Description

Tried on version: **2024.1.0.0-b92**

Logs: [https://drive.google.com/file/d/1U3s1xXxS8_0TL6gK-wKF4anXvberyLzg/view?usp=sharing](https://drive.google.com/file/d/1U3s1xXxS8_0TL6gK-wKF4anXvberyLzg/view?usp=sharing)

Encountering the below issue while running a test which has aggressive conflicts(15-25 threads trying to acquire the lock on the same row). So we may be running same queries concurrently or DMLs on the same row concurrently . 

```
05:59:55.343 Query: INSERT INTO many_columns_large_rows VALUES('6') on CONFLICT DO NOTHING;

ERROR: Read RPC (request call id 1032805) to 172.151.26.80:9100 timed out after 21.827s
```

In another run we also saw the below error 

```
13:56:32.011 Query: INSERT INTO less_columns_large_rows VALUES('9') on CONFLICT DO NOTHING;

ERROR: Write RPC (request call id 1015200) to 172.151.26.36:9100 timed out after 12.046s"
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11022]: https://yugabyte.atlassian.net/browse/DB-11022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@robertsami , Can you make a pass to see if this is expected?

**Comment by robertsami** [comment]
i'm seeing the following in the logs:
```
W0422 06:05:04.477146 31800 yb_rpc.cc:363] Call yb.tserver.TabletServerService.Read 172.151.16.162:45755 => 172.151.26.80:9100 (request call id 1032805) took 23263ms (client timeout 21826ms).
```

which suggests to me that the client timeout is genuinely being set to 21826
