### ISSUE TITLE
[2DC] Config to stop polling for changes / raise alerts

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2211]
Currently in 2DC, we continuously keeping polling for changes from producer cluster even when we keep receiving errors. Similarly, we repeatedly try to apply changes even after failure to apply. We need to configure:
1. Some upper bound on the amount of time for which we poll (or apply changes) after which we either stop trying or reduce the frequency.
2. Raise alerts for a tablet that's failing to poll or apply.

**Comment by hari90** [comment]
We now have exponential backoff, and taste limiting on both poll and apply paths.
