### ISSUE TITLE
[DocDB] Add schema version check to UsedSchemaVersion and UpdateSchemaVersion

### ISSUE THREAD

**Issue by Huqicheng** [yugabyte/yugabyte-db#22222]
Jira Link: [DB-11141](https://yugabyte.atlassian.net/browse/DB-11141)
### Description

To identify and address the "Schema packing not found" issues (#21699 #21244  #20638) resulting from incorrect handling of the tables and colocation_to_table map, it is recommended to implement additional instrumentation in this specific area. This added instrumentation will help detect and expose any corruptions promptly, enabling timely resolution of such problems.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11141]: https://yugabyte.atlassian.net/browse/DB-11141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
We detemined that it is sufficient to make the fix in master branch.
