### ISSUE TITLE
[Docs]  scale down tserver method not found in DOC.

### ISSUE THREAD

**Issue by frg01** [yugabyte/yugabyte-db#22323]
### Description

Hello, I didn’t find the command to scale down tserver in your doc. Does cluster scaling require restarting?

![image](https://github.com/yugabyte/yugabyte-db/assets/107344363/33f014e0-7ce6-40c7-a192-b093dbc3e140)
I tried it, and expansion can expand the master and tserver, but shrinking can only shrink the master, not the tserver. Is there any way to shrink tserver?
I've been looking for a long time but haven't found the command to shrink tserver. I don't know how to handle it.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
Hi @frg01 

There is https://docs.yugabyte.com/preview/manage/change-cluster-config/ to change yb-tservers or yb-masters. You only follow the steps to remove an yb-tserver

**Comment by frg01** [comment]
> Hi @frg01
> 
> There is https://docs.yugabyte.com/preview/manage/change-cluster-config/ to change yb-tservers or yb-masters. You only follow the steps to remove an yb-tserver

thanks

**Comment by frg01** [comment]
sloved

**Comment by frg01** [comment]
> Hi @frg01
> 
> There is https://docs.yugabyte.com/preview/manage/change-cluster-config/ to change yb-tservers or yb-masters. You only follow the steps to remove an yb-tserver

I have another question, that is what is the standard process for scaling down tserver.
I didn't find any standard tserver process in the article you replied. What I know now is that tserver can only be stopped through pkill -15. At this time, the status of tserver is dead, but it is still in the cluster. It shows that the master must be restarted before it will be removed.
