### ISSUE TITLE
[docdb] Master heartbeat writes should be batch written to raft

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2236]
When the master is processing heartbeats from TS, it will write to raft for each individual tablet reported in the heartbeat. For cases with lots of tablets, this will lead to a lot of wasted time and work on the master leader.

There is some worthwhile work in Kudu that might be worth checking: https://github.com/apache/kudu/commit/29a7568ddb5d24b1faf583b45d38884bfeb2b260, but it both has some other upstream code changes that will not make it a clean apply, as well as have to consider some of our changes around updating the TabletReplica map.

cc @hectorgcr @rahuldesirazu @rao-vasireddy

**Comment by nspiegelberg** [comment]
Looking into also grabbing the Updated sys_catalog API for clarity: https://github.com/apache/kudu/commit/626c3a83988efe2de4dcdaccafe71742a37af9c6

**Comment by nspiegelberg** [comment]
The main logical conflict in applying the diff is how to handle ResetTabletReplicasFromReportedConfig().  It looks like this was removed in Kudu as redundant, but it also looks like we made some modifications here that need to be understood: https://github.com/apache/kudu/commit/5f7823fe7f94edeb0f8dbb2b9d7a2201614e5e16

**Comment by nspiegelberg** [comment]
Client.BasicAlterOperations is failing due to https://issues.apache.org/jira/browse/KUDU-1539
