### ISSUE TITLE
[DocDB] Change delete snapshot so it does not block writes

### ISSUE THREAD

**Issue by mdbridge** [yugabyte/yugabyte-db#22369]
Jira Link: [DB-11270](https://yugabyte.atlassian.net/browse/DB-11270)
### Description

We recently discovered that delete snapshot blocks writes.  More precisely, it does 2 asynchronous flushes of the relevant tablet replica in a row; this has the effect of blocking writes until the first flush is finished.  (We block writes when there are two pending flushes as a disk back pressure mechanism.)

The second flush occurs at the very end:
```
~/code/yugabyte-db/src/yb/tablet/operations/snapshot_operation.cc:214:
Status SnapshotOperation::DoReplicated(int64_t leader_term, Status* complete_status) {
  RETURN_NOT_OK(Apply(leader_term, complete_status));
  // Record the fact that we've executed the "create snapshot" Raft operation. We are not forcing
  // the flushed frontier to have this exact value, although in practice it will, since this is the
  // latest operation we've ever executed in this Raft group. This way we keep the current value
  // of history cutoff.
  if (FLAGS_TEST_modify_flushed_frontier_snapshot_op) {
    docdb::ConsensusFrontier frontier;
    frontier.set_op_id(op_id());
    frontier.set_hybrid_time(hybrid_time());
    LOG(INFO) << "Forcing modify flushed frontier to " << frontier.op_id();
    return VERIFY_RESULT(tablet_safe())->ModifyFlushedFrontier(
        frontier, rocksdb::FrontierModificationMode::kUpdate);
  }
  return Status::OK();
}
```
The test flag here is on by default:
```
~/code/yugabyte-db/src/yb/tablet/operations/snapshot_operation.cc:30:
DEFINE_test_flag(bool, modify_flushed_frontier_snapshot_op, true,
                 "Whether to modify flushed frontier after "
                 "a create snapshot operation.");
```
ModifyFlushedFrontier in turn flushes asynchronously:
```
~/code/yugabyte-db/src/yb/tablet/tablet.cc:3294:
  return Flush(FlushMode::kAsync, flags);
```

The first flush occurs at the end of `Apply` here in the delete snapshot case:
```
~/code/yugabyte-db/src/yb/tablet/tablet_snapshots.cc:521:
  RETURN_NOT_OK(tablet().ModifyFlushedFrontier(
      frontier, rocksdb::FrontierModificationMode::kUpdate));
```

We thus call ModifyFlushedFrontier twice in a row, which causes to asynchronous flushes in a row, blocking writes.

We are calling ModifyFlushedFrontier as an optimization so we don't do the work of delete snapshot twice if we crash before the relevant Raft record (delete snapshot is a Raft operation) becomes durable.  I believe this is strictly an optimization because we can always crash before the first ModifyFlushedFrontier step, requiring the work to be repeated.

The use of ModifyFlushedFrontier for other snapshot operations like create snapshot may be needed for correctness and not just optimization.

For this task, it should suffice to not do the first flush (the one inside the delete snapshot code) as it is not needed given the flush in DoReplicated.  Be careful to check if there are other code paths that call delete snapshot that do not go through DoReplicated.

[stretch] find a way to avoid the second flush for delete snapshot as well.  Be careful not to remove flushs needed by other snapshot operations.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11270]: https://yugabyte.atlassian.net/browse/DB-11270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mdbridge** [comment]
note the other reason it would be good to avoid flushes: flushes can set off compactions due to the new SST file produced by the flush

**Comment by rthallamko3** [comment]
Per Sergei, looks like we don’t need this code in TabletSnapshots::Delete:
```
  docdb::ConsensusFrontier frontier;
  frontier.set_op_id(operation.op_id());
  frontier.set_hybrid_time(operation.hybrid_time());
  // Here we are just recording the fact that we've executed the "delete snapshot" Raft operation
  // so that it won't get replayed if we crash. No need to force the flushed frontier to be the
  // exact value set above.
  RETURN_NOT_OK(tablet().ModifyFlushedFrontier(
      frontier, rocksdb::FrontierModificationMode::kUpdate));
```
because this code in SnapshotOperation::DoReplicated is executed right after that:
```
  if (FLAGS_TEST_modify_flushed_frontier_snapshot_op) {
    docdb::ConsensusFrontier frontier;
    frontier.set_op_id(op_id());
    frontier.set_hybrid_time(hybrid_time());
    LOG(INFO) << "Forcing modify flushed frontier to " << frontier.op_id();
    return VERIFY_RESULT(tablet_safe())->ModifyFlushedFrontier(
        frontier, rocksdb::FrontierModificationMode::kUpdate);
  }
```

**Comment by rthallamko3** [comment]
Reactivating for 2.18 backports
