### ISSUE TITLE
[YCQL] JSONB change the order of stored json element on SELECT

### ISSUE THREAD

**Issue by zeinali-ali** [yugabyte/yugabyte-db#22365]
Jira Link: [DB-11267](https://yugabyte.atlassian.net/browse/DB-11267)
### Description

Hi `JSONB` columns change the order of key-values inside json

We expect `$type` always be first element of each json-object and that's how we store json but when we query the column the order of element change
```
{
    "$type": "Pezhvak.Messaging.Core.Abstraction.Messages.ExtraProperties, Pezhvak.Messaging.Core.Abstraction",
    "MessageStyles": {
        "$type": "Pezhvak.Messaging.Core.Abstraction.Messages.MessageStyleList, Pezhvak.Messaging.Core.Abstraction",
        "$values": []
    }
}
```
query would be like this:
```
{
    "MessageStyles": {
        "$type": "Pezhvak.Messaging.Core.Abstraction.Messages.MessageStyleList, Pezhvak.Messaging.Core.Abstraction",
        "$values": []
    },
    "$type": "Pezhvak.Messaging.Core.Abstraction.Messages.ExtraProperties, Pezhvak.Messaging.Core.Abstraction"
}
```

using yugabyte helm-chart:
Image: `yugabytedb/yugabyte:2.20.0.0-b76`

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11267]: https://yugabyte.atlassian.net/browse/DB-11267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
> We expect $type always be first element of each json-object and that's how we store json but when we query the column the order of element change

Hi @zeinali-ali 

Are you saying that the order is not consistent when you query it (order changes on each query)?

Or that the order is different (but consistent) from what you inserted?

Looking at PostgreSQL docs https://www.postgresql.org/docs/11/datatype-json.html: 

> By contrast, jsonb does not preserve white space, does not preserve the order of object keys, and does not keep duplicate object keys. If duplicate keys are specified in the input, only the last value is kept.

> In general, most applications should prefer to store JSON data as jsonb, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys.

**Comment by zeinali-ali** [comment]
the order is different (but consistent) from what we inserted.

Yes I know `JSONB` in PostgreSQL change the order of object keys and should use `JSON` if order is important, but it seems new version of yugabyte(YCQL) does not have `JSON` type anymore, it only support `JSONB`.

**Comment by ddorian** [comment]
> but it seems new version of yugabyte(YCQL) does not have JSON type anymore, it only support JSONB.

I don't think we ever had plain JSON type in YCQL? Maybe you were using plain TEXT column and dumping the JSON into that?

It's also explained in the docs that it's stored as ordered: https://docs.yugabyte.com/preview/api/ycql/type_jsonb/

> This is achieved by storing all the JSON keys in sorted order, which allows for efficient binary search of keys.

**Comment by zeinali-ali** [comment]
Thanks for time and answers. After exact check, it turned out that our earlier version of JSON library wasn't relay on `$type` to be first element of object, this condition added in newer version of library du performance optimization, as we update both YugaByte version and our JSON library at same time we thought YugaByte JSONB behavior changed in newer version.
