### ISSUE TITLE
[docs] StateFullSets Readme: $Using the Redis API

### ISSUE THREAD

**Issue by mrsirsh** [yugabyte/yugabyte-db#2242]
The command in the readme
```
kubectl exec -it yb-master-0 /home/yugabyte/bin/yb-admin -- --master-addresses yb-master-0.yb-masters.default.svc.cluster.local:7100,yb-master-1.yb-masters.default.svc.cluster.local:7100,yb-master-2.yb-masters.default.svc.cluster.local:7100 setup_redis_table
```
does not seem to work. I suspect if I better knew how to pass args via kubectl and/or had experience with YugaByte directly, I would know how to resolve this but I do not and the few combinations I tried failed me. Can the Readme be updated with the correct command?

**Comment by mrsirsh** [comment]
[Hyphens and underscores in flags]: With fresher eyes I realized this merely requires the change of `master-addresses` to `master_addresses` to fix.

**Comment by kmuthukk** [comment]
Thx @mrsirsh !

Would you mind/be interested in submitting a pull request? The docs is a sub-directory in the yugabyte-db repo, and the README.md here has the instructions. 

https://github.com/YugaByte/yugabyte-db/tree/master/docs

Thx.
