### ISSUE TITLE
[DocDB] Redundant RPCs in conflicting workloads caused due to current approach of tracking wait-for dependencies

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#22426]
Jira Link: [DB-11334](https://yugabyte.atlassian.net/browse/DB-11334)
### Description

https://github.com/yugabyte/yugabyte-db/commit/cd5905e11a399503d9da33a73797cb20870dd444 seems to have caused a regression in case of conflicting workloads. 

<img width="682" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/17742021/7cc99b37-c2be-4560-b62a-0b52b86ccab3">

In one of the locking benchmarks, we can see that the average latency is close to 3x of what it was earlier. The spike is first observed between 2.23.0.0-b189 and 2.23.0.0-b190. 

Upon looking at the grafana metrics, we observed increased number of `TabletServerService` RPCs. Needs additional investigation on where the additional RPCs got introduced.

<img width="1651" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/17742021/7a2bce5b-5466-45e0-a34f-08a14e4d5f4a">

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11334]: https://yugabyte.atlassian.net/browse/DB-11334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Reactivating for 2.20 backport.
