### ISSUE TITLE
[YSQL] tpc-h  run test Q20 take 52968.38s, too long

### ISSUE THREAD

**Issue by rxzhao00** [yugabyte/yugabyte-db#22451]
Jira Link: [DB-11368](https://yugabyte.atlassian.net/browse/DB-11368)
### Description

node:3
ver: 2.20
CPU | Mem | Disk | NetWork | 
-- | -- | -- | -- | --
Node1 | AMD Ryzen 9 7950X：16-Core Processor 32 4.5GHz | BL.9BWWR.352：64GB DDR5 | Samsung SSD 990 PRO 2TB *1 | Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE

Q20：
```sql
select
        s_name,
        s_address
from
        supplier,
        nation
where
        s_suppkey in (
                select
                        ps_suppkey
                from
                        partsupp
                where
                        ps_partkey in (
                                select
                                        p_partkey
                                from
                                        part
                                where
                                        p_name like 'forest%'
                        )
                        and ps_availqty > (
                                select
                                        0.5 * sum(l_quantity)
                                from
                                        lineitem
                                where
                                        l_partkey = ps_partkey
                                        and l_suppkey = ps_suppkey
                                        and l_shipdate >= date '1994-01-01'
                                        and l_shipdate < date '1994-01-01' + interval '1' year
                        )
        )
        and s_nationkey = n_nationkey
        and n_name = 'CANADA'
order by
        s_name;
```
```sql
Explain:
------------------------------------------------------------------
 Sort  (cost=112823.00..112824.25 rows=500 width=202)
   Sort Key: supplier.s_name
   ->  Nested Loop  (cost=112725.00..112800.58 rows=500 width=202)
         ->  Nested Loop  (cost=112725.00..112749.33 rows=500 width=206)
               ->  HashAggregate  (cost=112725.00..112727.00 rows=200 width=4)
                     Group Key: partsupp.ps_suppkey
                     ->  Nested Loop  (cost=0.00..112722.50 rows=1000 width=4)
                           ->  Seq Scan on partsupp  (cost=0.00..112620.00 rows=1000 width=8)
                                 Filter: ((ps_availqty)::numeric > (SubPlan 1))
                                 SubPlan 1
                                   ->  Aggregate  (cost=112.50..112.52 rows=1 width=32)
                                         ->  Seq Scan on lineitem  (cost=0.00..110.00 rows=1000 width=18)
                                               Remote Filter: ((l_shipdate >= '1994-01-01'::date) AND (l_shipdate < '1995-01-01 00:00:00'::timestamp without time zone) AND (l_part
key = partsupp.ps_partkey) AND (l_suppkey = partsupp.ps_suppkey))
                           ->  Index Scan using part_pkey on part  (cost=0.00..0.12 rows=1 width=4)
                                 Index Cond: (p_partkey = partsupp.ps_partkey)
                                 Remote Filter: ((p_name)::text ~~ 'forest%'::text)
               ->  Index Scan using supplier_pkey on supplier  (cost=0.00..0.13 rows=1 width=210)
                     Index Cond: (s_suppkey = partsupp.ps_suppkey)
         ->  Index Scan using nation_pkey on nation  (cost=0.00..0.12 rows=1 width=4)
               Index Cond: (n_nationkey = supplier.s_nationkey)
               Remote Filter: (n_name = 'CANADA'::bpchar)
(21 rows)
```
```sql
----------------------------QUERY PLAN  postgres (pg 12: 3609.01s)----------------------------------------------------------------------------------
Sort  (cost=706634537.40..706634537.44 rows=16 width=51)
   Sort Key: supplier.s_name
   ->  Nested Loop Semi Join  (cost=1.13..706634537.08 rows=16 width=51)
         ->  Nested Loop  (cost=0.29..657.56 rows=59 width=55)
               Join Filter: (supplier.s_nationkey = nation.n_nationkey)
               ->  Index Scan using supplier_pkey on supplier  (cost=0.29..495.43 rows=10000 width=59)
               ->  Materialize  (cost=0.00..12.13 rows=1 width=4)
                     ->  Seq Scan on nation  (cost=0.00..12.12 rows=1 width=4)
                           Filter: (n_name = 'CANADA'::bpchar)
         ->  Nested Loop  (cost=0.84..11976845.41 rows=1 width=4)
               ->  Index Scan using partsupp_pkey on partsupp  (cost=0.42..11976831.64 rows=27 width=8)
                     Index Cond: (ps_suppkey = supplier.s_suppkey)
                     Filter: ((ps_availqty)::numeric > (SubPlan 1))
                     SubPlan 1
                       ->  Aggregate  (cost=149635.28..149635.29 rows=1 width=32)
                             ->  Bitmap Heap Scan on lineitem  (cost=19153.71..149635.27 rows=1 width=5)
                                   Recheck Cond: ((l_shipdate >= '1994-01-01'::date) AND (l_shipdate < '1995-01-01 00:00:00'::timestamp without time zone))
                                   Filter: ((l_partkey = partsupp.ps_partkey) AND (l_suppkey = partsupp.ps_suppkey))
                                   ->  Bitmap Index Scan on i_l_shipdate  (cost=0.00..19153.71 rows=898928 width=0)
                                         Index Cond: ((l_shipdate >= '1994-01-01'::date) AND (l_shipdate < '1995-01-01 00:00:00'::timestamp without time zone))
               ->  Index Scan using part_pkey on part  (cost=0.42..0.51 rows=1 width=4)
                     Index Cond: (p_partkey = partsupp.ps_partkey)
                     Filter: ((p_name)::text ~~ 'forest%'::text)
 JIT:
   Functions: 31
   Options: Inlining true, Optimization true, Expressions true, Deforming true
(26 rows)
```

#data -s 1 (1.1G)
nation COPY 25    
region COPY 5
part COPY 200000
supplier COPY 10000

partsupp COPY 800000
customer COPY 150000
orders COPY 1500000

lineitem COPY 6001215

ddl:
```sql
-- Sccsid:     @(#)dss.ddl	2.1.8.1
CREATE TABLE NATION  ( N_NATIONKEY  INTEGER NOT NULL,
                            N_NAME       CHAR(25) NOT NULL,
                            N_REGIONKEY  INTEGER NOT NULL ,
                            N_COMMENT    VARCHAR(152)) ;

CREATE TABLE REGION  ( R_REGIONKEY  INTEGER NOT NULL,
                            R_NAME       CHAR(25) NOT NULL,
                            R_COMMENT    VARCHAR(152)) ;

CREATE TABLE PART  ( P_PARTKEY     INTEGER NOT NULL,
                          P_NAME        VARCHAR(55) NOT NULL,
                          P_MFGR        CHAR(25) NOT NULL,
                          P_BRAND       CHAR(10) NOT NULL,
                          P_TYPE        VARCHAR(25) NOT NULL,
                          P_SIZE        INTEGER NOT NULL,
                          P_CONTAINER   CHAR(10) NOT NULL,
                          P_RETAILPRICE DECIMAL(15,2) NOT NULL,
                          P_COMMENT     VARCHAR(23) NOT NULL, 
						  PRIMARY KEY (p_partkey)) ;

CREATE TABLE SUPPLIER ( S_SUPPKEY     INTEGER NOT NULL,
                             S_NAME        CHAR(25) NOT NULL,
                             S_ADDRESS     VARCHAR(40) NOT NULL,
                             S_NATIONKEY   INTEGER NOT NULL,
                             S_PHONE       CHAR(15) NOT NULL,
                             S_ACCTBAL     DECIMAL(15,2) NOT NULL,
                             S_COMMENT     VARCHAR(101) NOT NULL,
							 PRIMARY KEY (s_suppkey)) ;

CREATE TABLE PARTSUPP ( PS_PARTKEY     INTEGER NOT NULL,
                             PS_SUPPKEY     INTEGER NOT NULL,
                             PS_AVAILQTY    INTEGER NOT NULL,
                             PS_SUPPLYCOST  DECIMAL(15,2)  NOT NULL,
                             PS_COMMENT     VARCHAR(199) NOT NULL,
                             PRIMARY KEY (ps_partkey, ps_suppkey) ) ;

CREATE TABLE CUSTOMER ( C_CUSTKEY     INTEGER NOT NULL,
                             C_NAME        VARCHAR(25) NOT NULL,
                             C_ADDRESS     VARCHAR(40) NOT NULL,
                             C_NATIONKEY   INTEGER NOT NULL,
                             C_PHONE       CHAR(15) NOT NULL,
                             C_ACCTBAL     DECIMAL(15,2)   NOT NULL,
                             C_MKTSEGMENT  CHAR(10) NOT NULL,
                             C_COMMENT     VARCHAR(117) NOT NULL,
							 PRIMARY KEY (c_custkey)) ;

CREATE TABLE ORDERS  ( O_ORDERKEY       INTEGER NOT NULL,
                           O_CUSTKEY        INTEGER NOT NULL,
                           O_ORDERSTATUS    CHAR(1) NOT NULL,
                           O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
                           O_ORDERDATE      DATE NOT NULL,
                           O_ORDERPRIORITY  CHAR(15) NOT NULL,  
                           O_CLERK          CHAR(15) NOT NULL, 
                           O_SHIPPRIORITY   INTEGER NOT NULL,
                           O_COMMENT        VARCHAR(79) NOT NULL,
						   PRIMARY KEY (o_orderkey)) ;

CREATE TABLE LINEITEM ( L_ORDERKEY    INTEGER NOT NULL,
                             L_PARTKEY     INTEGER NOT NULL,
                             L_SUPPKEY     INTEGER NOT NULL,
                             L_LINENUMBER  INTEGER NOT NULL,
                             L_QUANTITY    DECIMAL(15,2) NOT NULL,
                             L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
                             L_DISCOUNT    DECIMAL(15,2) NOT NULL,
                             L_TAX         DECIMAL(15,2) NOT NULL,
                             L_RETURNFLAG  CHAR(1) NOT NULL,
                             L_LINESTATUS  CHAR(1) NOT NULL,
                             L_SHIPDATE    DATE NOT NULL,
                             L_COMMITDATE  DATE NOT NULL,
                             L_RECEIPTDATE DATE NOT NULL,
                             L_SHIPINSTRUCT CHAR(25) NOT NULL,
                             L_SHIPMODE     CHAR(10) NOT NULL,
                             L_COMMENT      VARCHAR(44) NOT NULL,
							 primary key(l_orderkey, l_linenumber));

create index I_L_ORDERKEY on lineitem(l_orderkey) ;
create index I_L_SHIPDATE on lineitem(l_shipdate) ;
create index I_O_ORDERDATE on orders(o_orderdate);		
```
### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11368]: https://yugabyte.atlassian.net/browse/DB-11368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Is this account a bot?

**Comment by ddorian** [comment]
Can you fix the indexes and try again with explain analyze of both cases?

```
create index I_L_SHIPDATE on lineitem(l_shipdate ASC) ;
create index I_O_ORDERDATE on orders(o_orderdate ASC);		
```

**Comment by rxzhao00** [comment]
with new index:
create index I_L_SHIPDATE on lineitem(l_shipdate ASC) ;
create index I_O_ORDERDATE on orders(o_orderdate ASC);	

YB:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=5964.18..5970.43 rows=2500 width=202)
   Sort Key: supplier.s_name
   ->  Hash Join  (cost=5630.58..5823.08 rows=2500 width=202)
         Hash Cond: (nation.n_nationkey = supplier.s_nationkey)
         ->  Seq Scan on nation  (cost=0.00..102.50 rows=1000 width=4)
               Remote Filter: (n_name = 'CANADA'::bpchar)
         ->  Hash  (cost=5624.33..5624.33 rows=500 width=206)
               ->  Nested Loop  (cost=5600.00..5624.33 rows=500 width=206)
                     ->  HashAggregate  (cost=5600.00..5602.00 rows=200 width=4)
                           Group Key: partsupp.ps_suppkey
                           ->  Nested Loop  (cost=0.00..5597.50 rows=1000 width=4)
                                 ->  Seq Scan on partsupp  (cost=0.00..5495.00 rows=1000 width=8)
                                       Filter: ((ps_availqty)::numeric > (SubPlan 1))
                                       SubPlan 1
                                         ->  Aggregate  (cost=5.38..5.39 rows=1 width=32)
                                               ->  Index Scan using i_l_shipdate on lineitem  (cost=0.00..5.35 rows=10 width=18)
                                                     Index Cond: ((l_shipdate >= '1994-01-01'::date) AND (l_shipdate < '1995-01-01 00:00:00'::timestamp without time zone))
                                                     Remote Filter: ((l_partkey = partsupp.ps_partkey) AND (l_suppkey = partsupp.ps_suppkey))
                                 ->  Index Scan using part_pkey on part  (cost=0.00..0.12 rows=1 width=4)
                                       Index Cond: (p_partkey = partsupp.ps_partkey)
                                       Remote Filter: ((p_name)::text ~~ 'forest%'::text)
                     ->  Index Scan using supplier_pkey on supplier  (cost=0.00..0.13 rows=1 width=210)
                           Index Cond: (s_suppkey = partsupp.ps_suppkey)
(23 rows)

postgres 12:
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=705281691.00..705281691.04 rows=16 width=51)
   Sort Key: supplier.s_name
   ->  Nested Loop Semi Join  (cost=1.13..705281690.68 rows=16 width=51)
         ->  Nested Loop  (cost=0.29..657.56 rows=59 width=55)
               Join Filter: (supplier.s_nationkey = nation.n_nationkey)
               ->  Index Scan using supplier_pkey on supplier  (cost=0.29..495.43 rows=10000 width=59)
               ->  Materialize  (cost=0.00..12.13 rows=1 width=4)
                     ->  Seq Scan on nation  (cost=0.00..12.12 rows=1 width=4)
                           Filter: (n_name = 'CANADA'::bpchar)
         ->  Nested Loop  (cost=0.84..11953915.81 rows=1 width=4)
               ->  Index Scan using partsupp_pkey on partsupp  (cost=0.42..11953902.04 rows=27 width=8)
                     Index Cond: (ps_suppkey = supplier.s_suppkey)
                     Filter: ((ps_availqty)::numeric > (SubPlan 1))
                     SubPlan 1
                       ->  Aggregate  (cost=149348.66..149348.67 rows=1 width=32)
                             ->  Bitmap Heap Scan on lineitem  (cost=18866.17..149348.65 rows=1 width=5)
                                   Recheck Cond: ((l_shipdate >= '1994-01-01'::date) AND (l_shipdate < '1995-01-01 00:00:00'::timestamp without time zone))
                                   Filter: ((l_partkey = partsupp.ps_partkey) AND (l_suppkey = partsupp.ps_suppkey))
                                   ->  Bitmap Index Scan on i_l_shipdate  (cost=0.00..18866.17 rows=898974 width=0)
                                         Index Cond: ((l_shipdate >= '1994-01-01'::date) AND (l_shipdate < '1995-01-01 00:00:00'::timestamp without time zone))
               ->  Index Scan using part_pkey on part  (cost=0.42..0.51 rows=1 width=4)
                     Index Cond: (p_partkey = partsupp.ps_partkey)
                     Filter: ((p_name)::text ~~ 'forest%'::text)
 JIT:
   Functions: 31
   Options: Inlining true, Optimization true, Expressions true, Deforming true
(26 rows)

**Comment by ddorian** [comment]
Please post `explain analyze` and not just `explain`.

**Comment by FranckPachot** [comment]
Hi, here are a few things to look at

About the data model:
- It would help to compare same datatypes, quantity is `DECIMAL` on one side and `INTEGER` on the other
- indexes are hash sharded by default if not mentioning ASC/DESC and are not used for range queries (like `ps_availqty >`)


About YugabyteDB version / settings
- you can `set yb_use_hash_splitting_by_default=off` before creating the tables and indexes to default to ASC 
- Running with the latest YugabyteDB version should show `YB Batched Nested Loop Join` rather than `Nested Loop`. If not on the latest version, you can set `set yb_bnl_bath_size=1024`
- for analytic queries, better ANALYZE the tables and set `set yb_enable_base_scans_cost_model=on` to get the cost based optimizer aware of the distribution of data

About the query
- `Filter: ((ps_availqty)::numeric > (SubPlan 1))` will not scale on distributed tables. 
Should be better to transform the correlated subquery `ps_availqty > ( select 0.5 * sum(l_quantity)` with a join and window function. Something like:
```
where
        s_suppkey in (
           select ps_suppkey from (
                select
                        p_name, ps_suppkey , ps_availqty, sum(l_quantity) over keys as sum_qty
                from
                        partsupp
                        join lineitem on (l_partkey = ps_partkey  and l_suppkey = ps_suppkey)
                        join part on (p_partkey=ps_partkey)
                window keys as (partition by l_partkey,l_suppkey)
            ) suppkeys
            where p_name like 'forest%' and ps_availqty > 0.5 * sum_qty
        )
        and s_nationkey = n_nationkey
        and n_name = 'CANADA'
```
