### ISSUE TITLE
[DocDB] ASH: Ignore Ash calls

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#22465]
Jira Link: [DB-11382](https://yugabyte.atlassian.net/browse/DB-11382)
### Description

After https://phorge.dev.yugabyte.com/rYBDBde9fd5d5d43eb2afa34701bb951c3e3fd0fde7c8 ash calls seem to be included.

This is a regression and needs to be fixed. 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11382]: https://yugabyte.atlassian.net/browse/DB-11382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@amitanandaiyer , Do you plan to backport this to 2024.1 branch?
