### ISSUE TITLE
[DocDB] [Unit Test] Flaky test XClusterTestParams/XClusterTest.SetupNamespaceReplicationWithBootstrapFailRestoreSnapshot/1 and XClusterTestParams/XClusterTest.SetupNamespaceReplicationWithBootstrapFailRestoreSnapshot/0

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#22470]
Jira Link: [DB-11387](https://yugabyte.atlassian.net/browse/DB-11387)
### Description

Version: 2.23.0.0-b357

Following unit tests have been flaky for quite a while
`
XClusterTestParams/XClusterTest.SetupNamespaceReplicationWithBootstrapFailRestoreSnapshot/1 and XClusterTestParams/XClusterTest.SetupNamespaceReplicationWithBootstrapFailRestoreSnapshot/0: 
`

```
../../src/yb/integration-tests/xcluster/xcluster-test.cc:785 Failed Bad status: Illegal state (yb/integration-tests/xcluster/xcluster-test.cc:461): Expected 0 snapshots but received 1: 1 vs 0

```
[Analyse Trend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=XClusterTestParams%2FXClusterTest&fail_tag=all&name=SetupNamespaceReplicationWithBootstrapFailRestoreSnapshot%2F0&num_commits=500&platform=linux)
[Analyse Trend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=XClusterTestParams%2FXClusterTest&fail_tag=all&name=SetupNamespaceReplicationWithBootstrapFailRestoreSnapshot%2F1&num_commits=500&platform=linux)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11387]: https://yugabyte.atlassian.net/browse/DB-11387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Tests have been disabled. Will be removed later.
