### ISSUE TITLE
[DocDB] Fix build after 21985

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#22501]
Jira Link: [DB-11430](https://yugabyte.atlassian.net/browse/DB-11430)
### Description

https://github.com/yugabyte/yugabyte-db/commit/cf0c09b945488ea46d596b38c6191bb564579c4c 
broke one of the builds.  GCC 12, debug AlmaLinux 9

https://github.com/yugabyte/yugabyte-db/actions/runs/9185098435/job/25258478418 :

```
 /-------------------------------------------------------------------------------
  | COMPILATION FAILED
  |-------------------------------------------------------------------------------
  ../../src/yb/consensus/log.cc: In member function 'yb::Status yb::log::Log::Close()':
  ../../src/yb/consensus/log.cc:1662:1: error: control reaches end of non-void function [-Werror=return-type]
   1662 | }
        | ^
  cc1plus: all warnings being treated as errors
  
  Input files:
    src/yb/consensus/CMakeFiles/log.dir/log.cc.o
    /opt/yb-build/yugabyte-db/src/yb/consensus/log.cc
  Output file (from -o): src/yb/consensus/CMakeFiles/log.dir/log.cc.o
  \-------------------------------------------------------------------------------
  [822/2654] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/consensus.cc.o
  [823/2654] Building CXX object src/yb/consensus/CMakeFiles/log.dir/log_reader.cc.o
  [824/2654] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/consensus_meta.cc.o
  ninja: build stopped: subcommand failed.
  ```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11430]: https://yugabyte.atlassian.net/browse/DB-11430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@amitanandaiyer , Do we need to backport this fix to other branches?
