### ISSUE TITLE
[YSQL] How is data sharded?

### ISSUE THREAD

**Issue by suppersam1** [yugabyte/yugabyte-db#22549]
Jira Link: [DB-11477](https://yugabyte.atlassian.net/browse/DB-11477)
### Description

If a table has both hash and range keys, How is data sharded?

### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11477]: https://yugabyte.atlassian.net/browse/DB-11477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
@suppersam1 

Please read https://docs.yugabyte.com/preview/architecture/docdb-sharding/tablet-splitting/.

Or please specify the exact schema.

**Comment by suppersam1** [comment]
> @suppersam1
> 
> Please read https://docs.yugabyte.com/preview/architecture/docdb-sharding/tablet-splitting/.
> 
> Or please specify the exact schema.

I have read the relevant content, but I still have doubts.
Like using create index on table (A, B) To establish an index, the results on the document is that column A will be used as the hash key, Column B will be used as the range key. I would like to know how the data in the index table created in this way is distributed across various tablets?

**Comment by ddorian** [comment]
An index is a virtual table. So the index will be sharded just like you'd shard a separate table with the same columns as the one you defined in the index. 

Again, please specify the exact details of the index.

**Comment by FranckPachot** [comment]
@suppersam1 if the table has both, it is hash shared on the shard key only, and then within each shard, the rows are ordered on the full key prefixed by the hash code. So in your example with an index on `(A, B)` which, given the defaults is `(A HASH, B ASC)`, a hash function is applied on A to give a value between 0 and 65535, and it is shared ranges of this key. Then, within this shard, the order is `(yb_hash_code(A), A, B)`
This means that HASH sharding is suitable only to columns with lot of different values, because it is not split further on other columns.

**Comment by suppersam1** [comment]
> @suppersam1 if the table has both, it is hash shared on the shard key only, and then within each shard, the rows are ordered on the full key prefixed by the hash code. So in your example with an index on `(A, B)` which, given the defaults is `(A HASH, B ASC)`, a hash function is applied on A to give a value between 0 and 65535, and it is shared ranges of this key. Then, within this shard, the order is `(yb_hash_code(A), A, B)` This means that HASH sharding is suitable only to columns with lot of different values, because it is not split further on other columns.

So if both hash and range exist, it is still based on hash to determine which tablet the data falls on. And when I create a hash index for the gender column, there are only three values (male, female, unknown), so the index data will only fall on three tables.

**Comment by ddorian** [comment]
> So if both hash and range exist, it is still based on hash to determine which tablet the data falls on.

Range is not based on hash. Hash is based on hash. Please specify the index/primary key exactly so we can describe it. 

> And when I create a hash index for the gender column, there are only three values (male, female, unknown), so the index data will only fall on three tablets.

Yes.

**Comment by suppersam1** [comment]
> > So if both hash and range exist, it is still based on hash to determine which tablet the data falls on.
> 
> Range is not based on hash. Hash is based on hash. Please specify the index/primary key exactly so we can describe it.
> 
> > And when I create a hash index for the gender column, there are only three values (male, female, unknown), so the index data will only fall on three tablets.
> 
> Yes.



> > So if both hash and range exist, it is still based on hash to determine which tablet the data falls on.
> 
> Range is not based on hash. Hash is based on hash. Please specify the index/primary key exactly so we can describe it.
> 
> > And when I create a hash index for the gender column, there are only three values (male, female, unknown), so the index data will only fall on three tablets.
> 
> Yes.

Based on my previous example of creating an index (A hash, B asc), according to your description, the data in the index table will first be hashed based on column A to determine which table to place on, and then arranged in the order of (hash_code, A, B) on this tablet. So I think when Hash and Range coexist, first determine the position of the tablet based on the Hash column, and then sort it according to A and B?

**Comment by ddorian** [comment]
> So I think when Hash and Range coexist, first determine the position of the tablet based on the Hash column, and then sort it according to A and B?

Yes. On the tablet it is stored as full primary key, so (hash_code, A, B ASC)

**Comment by suppersam1** [comment]
Thank you for your reply. My question has been resolved!

**Comment by suppersam1** [comment]
> > So I think when Hash and Range coexist, first determine the position of the tablet based on the Hash column, and then sort it according to A and B?
> 
> Yes. On the tablet it is stored as full primary key, so (hash_code, A, B ASC)

Sorry to reopen the issue. May I ask how the data is distributed when there are two hash columns in the case of create index (A hash, B hash)?

**Comment by ddorian** [comment]
> May I ask how the data is distributed when there are two hash columns in the case of create index (A hash, B hash)?

It will be sharded only on hash(A). It doesn't make sense to store B as HASH, you can store it ranged ASC/DSC.

You can do ((A, B) HASH), which means it will be sharded on HASH(a,b). 

https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_table/#primary-key

**Comment by suppersam1** [comment]
> > May I ask how the data is distributed when there are two hash columns in the case of create index (A hash, B hash)?
> 
> It will be sharded only on hash(A). It doesn't make sense to store B as HASH, you can store it ranged ASC/DSC.
> 
> You can do ((A, B) HASH), which means it will be sharded on HASH(a,b).
> 
> https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_table/#primary-key

thanks!
