### ISSUE TITLE
[YW] "Edit Universe" is failing when full move is needed in 1.3.3.0-b11

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2254]
Failed to execute task java.util.concurrent.FutureTask@3d19ab84, hit error java.lang.RuntimeException: Error Server[YB Master - 172.151.33.108:7100] NOT_FOUND[code 1]: Server with UUID bea526dd75754292bcd47dfcdefb2ed6 not a member of the config. RaftConfig: opid_index: 885 peers { permanent_uuid: "ada48b1d706b4281bcae66721b16485a" member_type: VOTER last_known_private_addr { host: "172.151.33.108" port: 7100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2b" } } peers { permanent_uuid: "8dccc071cc2042c88e2738ac1ed36817" member_type: VOTER last_known_private_addr { host: "172.151.58.180" port: 7100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2c" } } peers { permanent_uuid: "10938c4ecf82485f987dd86a2be3ec2a" member_type: VOTER last_known_private_addr { host: "172.151.18.200" port: 7100 } } peers { permanent_uuid: "6b50564cb371410c8f6c1603de7a07a4" member_type: VOTER last_known_private_addr { host: "172.151.29.87" port: 7100 } } peers { permanent_uuid: "bf84cd21a12647ab828487dc54090d77" member_type: VOTER last_known_private_addr { host: "172.151.39.67" port: 7100 } } while performing change config on node yb-15-rao-test-13-n3, host:port = 172.151.18.234:7100.

**Comment by rao-vasireddy** [comment]
the correct sequence to repro the issue is the following
1. Create a 3 node multi AZ universe (A,B,C)
2. add a node in zone B 
3. Now try to make it a 3 node universe in zone A (zone B, and C to have 0 nodes in this Edit)

**Comment by rao-vasireddy** [comment]
Please see if the number of nodes also changing from 4 to 3 at the same time as a full move of the universe is the specific scenario for this failure. Normal full move seems to work fine,

**Comment by rao-vasireddy** [comment]
Here's another sequence that failed -
1. expand a 3 node multi AZ cluster to 4 nodes.
2. move all the nodes to a single AZ (the same AZ that has 2 nodes). this will trigger a full move

this full move failed with the error (on the added node)

Failed to execute task java.util.concurrent.FutureTask@6bad58e0, hit error java.lang.RuntimeException: Error Invalid master host/port of 172.151.31.19/7100 - could not get it's uuid. while performing change config on node yb-15-rao-test20-n4, host:port = 172.151.31.19:7100.

**Comment by ramkumarvs** [comment]
@rao-vasireddy with recent fixes i put in to placement info, can we verify if this issue is still happening?

**Comment by ramkumarvs** [comment]
Closing this issue.
