### ISSUE TITLE
[yugabyted] [QA] [2.21.1]Enable EAR command is failing

### ISSUE THREAD

**Issue by yogesh-yb** [yugabyte/yugabyte-db#22552]
Jira Link: [DB-11479](https://yugabyte.atlassian.net/browse/DB-11479)
### Description

Steps: 1. Create a cluster with basic configuration using ./bin/yugabyted start and then execute ./bin/yugabyted configure encrypt_at_rest --enable and observe it fails with
<< ERR >>

<<
[yugabyted encrypt_at_rest] 2024-05-27 19:13:23,991 ERROR:  | 0.4s | Traceback (most recent call last):
  File "/Users/ysharmaryugabyte.com/yugabyte-2.21.1.0/./bin/yugabyted", line 6671, in run
    args.func()
  File "/Users/ysharmaryugabyte.com/yugabyte-2.21.1.0/./bin/yugabyted", line 1580, in configure_encrypt_at_rest
    if self.check_openssl():
       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ysharmaryugabyte.com/yugabyte-2.21.1.0/./bin/yugabyted", line 1883, in check_openssl
    return find_executable('openssl') == None
           ^^^^^^^^^^^^^^^
NameError: name 'find_executable' is not defined

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11479]: https://yugabyte.atlassian.net/browse/DB-11479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Adding a little more info on this:
The commit https://github.com/yugabyte/yugabyte-db/commit/c1e156da3f0114b417472b6dc5925805a7263fd6 deprecates the use of Python 2 from yugabyted.
The commit https://github.com/yugabyte/yugabyte-db/commit/1df93932490bdd193915baabc9a58ed24d8e766c fixes a code which was present as part of Python2 support. This fix was not backported causing the failure.
