### ISSUE TITLE
[YW] Retry failed health checks to avoid raising alerts for transient issues

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2256]

**Comment by iSignal** [comment]
https://github.com/yugabyte/yugabyte-db/commit/9afecb71b2619cdad6a939b9c25ebc4072d89cef 

Will keep this open until we can verify that the transient errors do disappear.

**Comment by iSignal** [comment]
Closing original issue for now because we have a basic retry mechanism and it seems to iron out basic ssh connectivity issues. We have a couple of follow ups to further refine this in #2507 and #2526
