### ISSUE TITLE
[DocDB][TSAN] Test:PgIndexBackfillTest.RetainDeleteMarkersRecovery is flaky in 2024.1

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#22593]
Jira Link: [DB-11501](https://yugabyte.atlassian.net/browse/DB-11501)
### Description

Test:PgIndexBackfillTest.RetainDeleteMarkersRecovery is flaky in 2024.1

Detective: https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=2024.1.0&class=PgIndexBackfillTest&name=RetainDeleteMarkersRecovery

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11501]: https://yugabyte.atlassian.net/browse/DB-11501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
The test is stable on master ([Report](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=PgIndexBackfillTest&name=RetainDeleteMarkersRecovery)). @arybochkin , Is there a missing backport in 2024.1 branch that is making this test flaky?

**Comment by arybochkin** [comment]
The test is stable starting form 2024.1.1 ([report](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=2024.1.1&class=PgIndexBackfillTest&name=RetainDeleteMarkersRecovery)) and is stable in 2024.2 ([report](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=2024.2&class=PgIndexBackfillTest&name=RetainDeleteMarkersRecovery&num_commits=500)). Hence closing.
