### ISSUE TITLE
[DocDB] Fix flaky test PgGetLockStatusTestRF3.TestLocksOfSingleShardWaiters

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#22619]
Jira Link: [DB-11527](https://yugabyte.atlassian.net/browse/DB-11527)
### Description

The above test fails with the following in asan
```
Bad status: Runtime error (yb/yql/pgwrapper/libpq_utils.h:215): Unexpected number of rows: 0 vs 1
```

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=PgGetLockStatusTestRF3&name=TestLocksOfSingleShardWaiters

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11527]: https://yugabyte.atlassian.net/browse/DB-11527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
On Almalinux 8, master 7217b58e18b7a99e3d06b6ce5de191a7362f18e0,

`./yb_build.sh fastdebug --gcc11 --cxx-test pgwrapper_pg_get_lock_status-test --gtest_filter PgGetLockStatusTestRF3.TestLocksOfSingleShardWaiters -n 50`

gave only one failure

```
../../src/yb/yql/pgwrapper/pg_get_lock_status-test.cc:971: Failure
Expected equality of these values:
  waiter1_start_time
    Which is: 772078263.102s
  __extension__ ({ auto&& __result = (setup_conn.FetchRow<MonoDelta>( "SELECT DISTINCT(waitstart) FROM pg_locks WHERE fastpath" )); static_assert(yb::IsNonConstResultRvalue<decltype(__result)>::value, "only non-const Result<T> rvalue reference is allowed"); do { auto&& _assert_status = (__result); if (_assert_status.ok()) { ::testing::internal::AssertHelper(::testing::TestPartResult::kSuccess, "../../src/yb/yql/pgwrapper/pg_get_lock_status-test.cc", 971, "Succeeded") = ::testing::Message(); } else { return ::testing::internal::AssertHelper(::testing::TestPartResult::kFatalFailure, "../../src/yb/yql/pgwrapper/pg_get_lock_status-test.cc", 971, "Failed") = ::testing::Message() << "Bad status: " << StatusToString(_assert_status); } } while (0); WrapMove(std::move(__result)); })
    Which is: 772078263.104s
```

pg15 branch has also been hitting rare failures.
