### ISSUE TITLE
[YSQL] Testing and hardening for Early Access of the Bitmap Scans

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#22692]
Jira Link: [DB-11600](https://yugabyte.atlassian.net/browse/DB-11600)
### Description

Testing and hardening for Early Access of the Bitmap Scans

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11600]: https://yugabyte.atlassian.net/browse/DB-11600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment]
Tested with randgen with a modified grammar, TAQO
