### ISSUE TITLE
[docs] Document app consistent secondary indexes

### ISSUE THREAD

**Issue by jameshartig** [yugabyte/yugabyte-db#2271]
Documentation is needed on how to use `app consistent secondary indexes` in YCQL

**Comment by stevebang** [comment]
Slack discussion added to a Google Doc: https://docs.google.com/document/d/1s9tth9aeVWy3mvSLklCZgjh0vRu2Vf7G3w63YDha0R8/edit#

**Comment by ddorian** [comment]
closing as duplicate of #6082
