### ISSUE TITLE
[CDCSDK] Performance Degradation and Memory Pressure Rejections with CDC Long Retention Changes

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#22761]
Jira Link: [DB-11664](https://yugabyte.atlassian.net/browse/DB-11664)
### Description

Performance degradation and memory pressure rejections are observed when long retention changes are applied. Please find slack thread in JIRA.

Below are the experiments by which we confirmed:

**Happy Path Run without Long Retention Changes (Version 2024.1.1.0-b57)**
- Running fine without perf degrade issues

**Happy Path Run with Long Retention Changes (Default 4 Hours Retention) (Version 2024.1.1.0-b67)**
- Sharp decline in throughput observed after 2 hours.

**Happy Path Run with Long Retention Changes (12 Hours Retention) (Version 2024.1.1.0-b67)**
- Similarly, with 12 Hours Retention as well, throughput decline was seen after an hour or so.

**2 hrs only connector downtime, with 12 hrs retention (Version 2024.1.1.0-b67)**
- 2 nodes became unreachable when the connector was brought up after 2 hours.
- Memory pressure rejection occurred only when the connector was brought up in this run.

**Summary:**
So, Performance drops are consistently observed with long retention changes. Memory Pressure rejections are seen.
The baseline run without long retention changes showed stable performance.

![Screenshot 2024-06-06 at 8 29 13 PM](https://github.com/yugabyte/yugabyte-db/assets/109518123/7a6f1989-cc1b-4d69-a2a4-c768f4a264ba)
![Screenshot 2024-06-06 at 8 29 54 PM](https://github.com/yugabyte/yugabyte-db/assets/109518123/e0cdd2ad-78f2-4ff9-961a-56e431769129)

Also attaching screenshots of memory increase and memory pressure rejections when connector was brought up again:

<img width="667" alt="Screenshot 2024-06-06 at 9 50 03 PM" src="https://github.com/yugabyte/yugabyte-db/assets/109518123/7064f808-cab4-4845-85d7-d128fb0ad29a">

<img width="667" alt="Screenshot 2024-06-06 at 9 51 09 PM" src="https://github.com/yugabyte/yugabyte-db/assets/109518123/1b102362-b544-4d2a-81bc-c048e5694fd1">

### Source connector version

YB connector latest

### Connector configuration

NA

### YugabyteDB version

2024.1.1.0-b67

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11664]: https://yugabyte.atlassian.net/browse/DB-11664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
https://github.com/yugabyte/yugabyte-db/issues/22227 is supposed to cover the performance fixes for this scenario. Closing this as DUP of https://github.com/yugabyte/yugabyte-db/issues/22227
