### ISSUE TITLE
[DocDB] CDC happy path performance regresses when cdc_immediate_transaction_cleanup is enabled

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#22778]
Jira Link: [DB-11679](https://yugabyte.atlassian.net/browse/DB-11679)
### Description

CDC happy path performance regresses when cdc_immediate_transaction_cleanup is enabled

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11679]: https://yugabyte.atlassian.net/browse/DB-11679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by rthallamko3** [comment]
DUP of #22761 . @es1024 , Lets use #22761 to track the file level cleanup fix.
