### ISSUE TITLE
[DocDB] Create a button in the Tserver UI to access the io-stack-traces

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#22842]
Jira Link: [DB-11739](https://yugabyte.atlassian.net/browse/DB-11739)
### Description

- Create a button in the Tserver UI to access the io-stack-traces

- Also include a button to reset the io-stats /reset-stack-traces

- Include a note on the timestamp, when the tracking started.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11739]: https://yugabyte.atlassian.net/browse/DB-11739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by es1024** [comment]
![Screenshot from 2024-06-26 15-24-28](https://github.com/yugabyte/yugabyte-db/assets/6742815/9de9f5f0-b63e-4618-bafb-cb89f01ea4ec)
![Screenshot from 2024-06-26 15-24-52](https://github.com/yugabyte/yugabyte-db/assets/6742815/c3db1e87-a0f2-4fb7-8aa2-bff65638220d)
