### ISSUE TITLE
[DocDB] Fix DFATAL in WaitQueue::Impl::HandleWaiterStatusRpcResponse

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#22840]
Jira Link: [DB-11737](https://yugabyte.atlassian.net/browse/DB-11737)
### Description

Test `PgWaitQueuesTest.DeadlockResolvesYoungestTxn` in debug builds sometimes runs into the following DFATAL
```
[ts-1] F0612 05:43:10.533767 1065683 wait_queue.cc:1871] Waiting transaction ab9adb28-a017-4278-a58e-aa7ac7380783 found in unexpected state 4
```

[commit](https://github.com/yugabyte/yugabyte-db/commit/2896530b3a9eb209ecb79d4665c0ffb4b10bd52a) refactored the way we maintain waiters at the waut-queue, changing waiter_status_ to track `WaitingTxn` which internally stores all waiting rpc requests corresponding to the transaction at the tablet. 

Earlier, we used to remove the waiter from `waiter_status_` when executing its callback, but now we only erase the waiter either on processing the txn status response or when we see that all rpc requests of this waiter have been resolved.

the following could happen 
```
1. Poll sees a waiting request for the `WaitingTxn`, and launches a status request
2. The blocker for the rpc request resolves, and the waiting rpc request's callback is executed
3. The waiter txn (which is no longer blocker) commits.
4. The txn coordinator processes the status response and returns COMMITTED
5. HandleWaiterStatusRpcResponse process the response and DFATAL seeing COMMITTED status
```

With the current state of the code, it should be totally okay to see `COMMITTED` for a waiter (which is no longer blocked). We could just skip processing the txn status response if `waiting_txn->GetNumWaiters() == 0`.

This isn't an issue in release mode anyways since the next iteration of `Poll` would purge the `WaitingTxn`

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11737]: https://yugabyte.atlassian.net/browse/DB-11737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
`./yb_build.sh fastdebug --gcc11 --cxx-test pgwrapper_pg_wait_on_conflict-test --gtest_filter PgWaitQueueContentionStressTest.TestResumeWaitersOnScheduler -n 50` also on 7217b58e18b7a99e3d06b6ce5de191a7362f18e0 (master) and 2722fc51c3bf93fc6cc950b57a7bfa7c6715e567 (pg15)

**Comment by basavaraj29** [comment]
opening for backport to 2024.1
