### ISSUE TITLE
Revisist table level metrics

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#2284]

**Comment by amitanandaiyer** [comment]
I downloaded the prometheus metrics from one of our installations at X. It has about `11K` metrics being exported.

A few of them are of the form 
`mem_tracker_BlockBasedTable_RegularDB_d7703de183ed4860a7eb7b7695a758b6`
`mem_tracker_BlockBasedTable_IntentsDB_17f62bbd4eb04919b830d3329c8266f6`

These grow linearly with the number of tablets on the node/cluster. And will add 2 * RF * <num_tablets> data points per tablet.

We have about 200 metrics that are exported per table. 

 and about 100 metrics that are exported at the tserver level.

**Comment by amitanandaiyer** [comment]
most of our graphs on the yugaware side end up aggregating the metrics across all the tablets and/or tables, so if we have that be done in the tserver itself we can export a lot less metrics.

**Comment by amitanandaiyer** [comment]
Each tablet creates its own version of metrics for RocksDB. 
https://github.com/yugabyte/yugabyte-db/blob/00dfbd97acdea9f21bf4953dcdb54ed53d2adf4b/src/yb/tablet/tablet.cc#L358

We typically end up aggregating them in yugaware 
https://github.com/yugabyte/yugabyte-db/blob/00dfbd97acdea9f21bf4953dcdb54ed53d2adf4b/managed/src/main/resources/metrics.yml#L1088

We could reduce some metrics here by creating a common rocksb metrics instance to be used across tablets.

**Comment by bmatican** [comment]
Solved in #7805
