### ISSUE TITLE
[YSQL] Does yb support adjusting memtable to hashlinklist?

### ISSUE THREAD

**Issue by suppersam1** [yugabyte/yugabyte-db#22885]
Jira Link: [DB-11791](https://yugabyte.atlassian.net/browse/DB-11791)
### Description

Hi, my table only needs point queries. Is it more efficient to adjust RocksDB's default SkipList to HashSkipList or HashLinkList?

### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11791]: https://yugabyte.atlassian.net/browse/DB-11791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @suppersam1 

We don't support changing the memtable backend.

Note that even if you do point queries the db underneath might do scans https://docs.yugabyte.com/preview/architecture/docdb/ .

**Comment by suppersam1** [comment]
> Hi @suppersam1
> 
> We don't support changing the memtable backend.
> 
> Note that even if you do point queries the db underneath might do scans https://docs.yugabyte.com/preview/architecture/docdb/ .

It seems that YB's RocksDB can only be queried using an iterator and not with RocksDB's Get() for point lookups. This is because the value of the dockey contains hybrid time, and during queries, it can only be filtered through the iterator's prefix search.

**Comment by ddorian** [comment]
@suppersam1 correct.

**Comment by suppersam1** [comment]
I noticed that you also have a packed row design, which means subkeys might have multiple column IDs. If there are updates, the new columns are stored in an unpacked format.

for example:

table { id int(hash), data1 varchar(255), data2 varchar(255)) }
insert (0, 'aaa', 'bbb'), the pack key 0 | 1,2 | ht1-> 'aaa' , 'bbb'  
update 'aaa' -> 'ccc' , the new key 0 | 1 | ht2 -> 'ccc'

we use select * from table;
the iterator will search this two records and combine them?

**Comment by ddorian** [comment]
> the iterator will search this two records and combine them?

Yes. Rows are merged on read or on compaction.

**Comment by suppersam1** [comment]
thanks! I have resolved my problems.
