### ISSUE TITLE
YSQL at serializable level causes spurious serialization error

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#2290]
Jira Link: [DB-2543](https://yugabyte.atlassian.net/browse/DB-2543)
Using YB Version 1.3.1 downloaded from the Internet. Running on my macOS Mojave Version 10.14.6. Using a single node RF=1 cluster created with bare "yb-ctl create".

Here's the setup.
```
drop table if exists t;
create table t(k int primary key, v int not null unique);
with s as (select generate_series(1, 3) as a)
insert into t(k, v) select a as k, a*2 as v from s;
```
Do it in a dedicated ysqlsh session and exit.

**FIRST TESTCASE**

Then start two ysqlsh sessions and run the steps in the left-hand column in one and those in the right hand column in the other. Interleave them as the rule-offs indicate.
```
SESSION ONE                             SESSION TWO
________________________________________________________________________________
start transaction
  isolation level serializable;
________________________________________________________________________________
                                        start transaction
                                          isolation level serializable;
________________________________________________________________________________
                                        insert into t(k, v) values(17, 34);
________________________________________________________________________________
                                        update t set v = 7 where k = 3;
________________________________________________________________________________
insert into t(k, v) values(42, 84);
________________________________________________________________________________
                                        delete from t where k = 1;
________________________________________________________________________________
                                        select k, v from t order by v;
                                            2    4
                                            3    7
                                           17   34
________________________________________________________________________________
                                        commit;
________________________________________________________________________________
commit;
ERROR 40001: Error during commit: Operation expired: Transaction expired...
```
Exit both sessions. Then start a brand new session to see the final outcome:
```
select k, v from t order by v;
    2    4
    3    7
   17   34
```
The serialization error is spurious because there exists a serial order of execution that's consistent with the effects (data changes and results reported by "select" executions) that each has when executed concurrently. Run the right-hand txn first. And then run the left-hand txn. This would be the final result seen by the  brand new reporting session:
```
select k, v from t order by v;
    2    4
    3    7
   17   34
   42   84
```
Now re-run the test using PostgreSQL. No serialization error is reported. And the final status is indeed the 4 rows that are shown immediately above.

NOTE: This is an example from a larger test suite for my "Transaction Isolation" blog post. (See Test_04 in the output from `basic_tests.py`.) The test suite shows fifteen cases of spurious serialization error. See issue #2443 that asks to include all the tests in YB's regression suite.

**SECOND TESTCASE**

This differs from the first one only in that Session Two's final "select" is omitted. Set up the same table and starting data as the first testcase uses.

This one isn't shown by the output from my test suite (see Test_03 in the output from `basic_tests.py` — and see Issue #2443) because to see the problem you have to change these two statements:
```
update t set v = 7 where k = 3
```
and
```
delete from t where k = 1
```
to these:
```
update t set v = 7 where v = 6
```
and
```
delete from t where v = 2
```
Notice that each "update"-"delete" pair identifies the same two rows.

Here is the test case using the original statements that restrict by the column `t.k`:
```
SESSION ONE                             SESSION TWO
________________________________________________________________________________
start transaction
  isolation level serializable;
________________________________________________________________________________
                                        start transaction
                                          isolation level serializable;
________________________________________________________________________________
                                        insert into t(k, v) values(17, 34);
________________________________________________________________________________
                                        update t set v = 7 where k = 3;
________________________________________________________________________________
insert into t(k, v) values(42, 84);
________________________________________________________________________________
                                        delete from t where k = 1;
________________________________________________________________________________
                                        commit;
________________________________________________________________________________
commit;
________________________________________________________________________________
```
Exit both sessions. Then start a brand new session to see the final outcome:
```
select k, v from t order by v;
    2    4
    3    7
   17   34
   42   84
```
There's nothing to be concerned about here because the two concurrent transactions are indeed serializable and there's no serialization error. Now change the "update" and "delete" statements to restrict by the column `t.v` and re-run the test. This time we see this error:
```
ERROR 40001:  Operation failed. Try again.: Conflicts with higher priority transaction...
```
Notice that the error occurs when the table is created with `v int not null unique` as shown above. Not surprisingly, the error occurs in the same way when the unique constraint on `t.v` is absent.

**Comment by pkj415** [comment]
The behavioral difference stems from difference in implementation between Pg and YB. SSI (Serializable Snapshot Isolation) in postgres helps avoid certain serialization errors. To better understand the difference, I will add a brief snippet here with the exact details of which SIREAD locks are taken by Pg in this case and how a "dangerous" structure of two R-W dependencies is not detected.

**Comment by sushantrmishra** [comment]
Closed based on @pkj415 explanation in https://github.com/yugabyte/yugabyte-db/issues/2290#issuecomment-902811028
