### ISSUE TITLE
[YSQL] Fix Server's System Clock in XLogData from the logical replication stream

### ISSUE THREAD

**Issue by fivetran-lingyizhao** [yugabyte/yugabyte-db#22929]
Jira Link: [DB-11846](https://yugabyte.atlassian.net/browse/DB-11846)
### Description

Received either `0` or some random time as Server's System Clock of XLogData retrieved from the logical replication stream.
Created replication slot with test_decoding plugin. Trying to retrieve XLogData from logical replication stream, and the timestamp of Server's System Clock always give `0`. 

Structure of XLogData ('w') - containing a piece of WAL data.
- Message Type: 'w'
- Start LSN: 8 bytes
- End LSN: 8 bytes
- Server's System Clock: 8 bytes
- WAL Data: Variable length

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11846]: https://yugabyte.atlassian.net/browse/DB-11846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @fivetran-lingyizhao 

What version are you using?

Can you provide some steps to replicate?

**Comment by fivetran-lingyizhao** [comment]
Hi @ddorian @Sumukh-Phalgaonkar 
I am using master branch build YugaByte - here is more specific with everything `PostgreSQL 11.2-YB-2.23.0.0-b0 on arm-apple-darwin23.5.0, compiled by Apple clang version 15.0.0 (clang-1500.3.9.4), 64-bit`.

Steps:
I created replication slot with `test_decoding` plugin. 
Then created a Streaming Replication Protocol connection to YB. 
Next `START_REPLICATION XXX/XXX` start streaming replication. 
Then getting CopyData messages via PQgetCopyData(). And the payload XLogData contains `Server's System Clock` that I need to keep track of timestamps of data changes.

**Comment by Sumukh-Phalgaonkar** [comment]
Hey @fivetran-lingyizhao I have identified the bug here. This bug was inherited from Postgres code and was fixed in this [commit](https://github.com/postgres/postgres/commit/5f6b1eb0cf4b0fb101478da51c294a63fd4726ef). We will import this fix into YB shortly. I will let you know once this import lands.
