### ISSUE TITLE
[YSQL] insert drop create insert causes current transaction is expired or aborted

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#22949]
Jira Link: [DB-11863](https://yugabyte.atlassian.net/browse/DB-11863)
### Description

In all transaction isolation level cases, the following repro fails (though the message for read committed is slightly different).  This repro is derived from the `transactions` regress test.  All testing was done on YB master (7217b58e18b7a99e3d06b6ce5de191a7362f18e0) and pg15 (fedbdac1c20d8301b63860041835f001bfb33118), the following output being from master.  Almalinux 8, fastdebug, gcc11 build.

```sql
drop table if exists repro;
create table repro (a int unique);
begin isolation level read committed;
insert into repro values (1);
drop table repro;
create table repro (a int unique);
insert into repro values (2);
commit;
```

```
ERROR:  current transaction is expired or aborted (query layer retry isn't possible, READ COMMITTED transaction was aborted  and some data was already sent to the user)
DETAIL:  Heartbeat: Transaction e10048be-ddd3-4cd2-b66e-41faaa3b71c7 expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_coordinator.cc:1760): Heartbeat: Transaction e10048be-ddd3-4cd2-b66e-41faaa3b71c7 expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)]
ROLLBACK
```

```sql
drop table if exists repro;
create table repro (a int unique);
begin isolation level repeatable read;
insert into repro values (1);
drop table repro;
create table repro (a int unique);
insert into repro values (2);
commit;
```

```
ERROR:  current transaction is expired or aborted (query layer retry isn't possible because data was already sent, if this is the read committed isolation (or) the first statement in repeatable read/ serializable isolation transaction, consider increasing the tserver gflag ysql_output_buffer_size)
DETAIL:  Heartbeat: Transaction c57b6c62-2bba-4859-a4b6-893ca8c3ab69 expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_coordinator.cc:1760): Heartbeat: Transaction c57b6c62-2bba-4859-a4b6-893ca8c3ab69 expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)]
ROLLBACK
```

```sql
drop table if exists repro;
create table repro (a int unique);
begin isolation level serializable;
insert into repro values (1);
drop table repro;
create table repro (a int unique);
insert into repro values (2);
commit;
```

```
ERROR:  current transaction is expired or aborted (query layer retry isn't possible because data was already sent, if this is the read committed isolation (or) the first statement in repeatable read/ serializable isolation transaction, consider increasing the tserver gflag ysql_output_buffer_size)
DETAIL:  Heartbeat: Transaction b139c33a-f6bf-4049-900b-5c638852c3af expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_coordinator.cc:1760): Heartbeat: Transaction b139c33a-f6bf-4049-900b-5c638852c3af expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)]
ROLLBACK
```

The first insert has to be within the transaction block for the repro to work.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11863]: https://yugabyte.atlassian.net/browse/DB-11863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
On pg15 43a9d6b6e69b44b12769e8b02b151ffa4457825f and recent master (don't know which commit), all repros have nondeterministic behavior.  It either fails on `insert into repro values (2);` with (the following example is read committed)


```
ERROR:  current transaction is expired or aborted (query layer retry isn't possible, READ COMMITTED transaction was aborted  and some data was already sent to the user)
DETAIL:  Heartbeat: Transaction 03c36c6f-4354-4cfc-9eaa-d9cf8f322ab5 expired or aborted by a conflict: 40001: . Errors from tablet servers: [Operation expired (yb/tablet/transaction_coordinator.cc:1760): Heartbeat: Transaction 03c36c6f-4354-4cfc-9eaa-d9cf8f322ab5 expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)]
```

or fails on `commit;` with (the following example is read committed)

```
ERROR:  current transaction is expired or aborted (query layer retry isn't possible, READ COMMITTED transaction was aborted  and some data was already sent to the user)
DETAIL:  Transaction 9c9515e5-c97b-41a6-976e-dd9843831a22 expired or aborted by a conflict: 40001
```

Not sure if this was the case previously as well, but I highly doubt it as commit 475dbd9f03583b5d9abff51046539a102266f31a indicates the yb_pg_transactions regress test (holding a similar test) passed 50/50 times.  My guess is that pg15 merge commit 7aa29f52f8d5c764b6ba6d5266e5b6dc87a20118 caused this test to start becoming inconsistent, which would mean the behavior change happened in this range of master commits: 7358cd113ecbcb710e365c6ef8299fc7b72b9193..d55f7689adaeec2f5616592cccb34d6892021e2f.

**Comment by jasonyb** [comment]
The change in behavior appears to be by commit 60ac2325a90d4a5ce7f964da435accc2f8d4825c, having tested before and after that commit.

**Comment by pao214** [comment]
DROP and CREATE patterns leads to the non-deterministic output. Removed the CREATE statatement to solve the issue.
