### ISSUE TITLE
[YSQL] flaky test CDCSDKConsumptionConsistentChangesTest.TestCDCSDKMakesProgressWithLongRunningTxn

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#22977]
Jira Link: [DB-11891](https://yugabyte.atlassian.net/browse/DB-11891)
### Description

On YB master 7217b58e18b7a99e3d06b6ce5de191a7362f18e0 and pg15 b766d913e0b4d3d8926eb110107d1f06f31024ed, this test is flaky

```
./yb_build.sh fastdebug --gcc11 --gtest_filter CDCSDKConsumptionConsistentChangesTest.TestCDCSDKMakesProgressWithLongRunningTxn -n 50
```

When it fails, it's always

```
../../src/yb/integration-tests/cdcsdk_consumption_consistent_changes-test.cc:1107: Failure
Expected equality of these values:
  seen_insert_records
    Which is: 99
  0
```

Saw this at least 5 of 5 times.

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11891]: https://yugabyte.atlassian.net/browse/DB-11891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by siddharth2411** [comment]
This test doesnt seem to fail on latest master as well as the commit 7217b58e18b7a99e3d06b6ce5de191a7362f18e0. Ran it for 100 iterations on fastdebug & gcc11 and no failures were reported.
