### ISSUE TITLE
[CDC] Unable to remove dead universe from replication

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#2299]
If one side of the CDC becomes inoperable or is removed, you cannot remove the replication setup because it tries to contact the peers master which may no longer exist.

You get a message similar to the following:
```
[yugabyte@ip-172-152-17-54 ~]$ master/bin/yb-admin -master_addresses 172.152.17.54:7100,172.152.94.196:7100,172.152.97.186:7100 delete_universe_replication f20d0f7a-940e-4324-908f-9785c188d5cc
I0913 14:44:45.362396 19172 mem_tracker.cc:250] MemTracker: hard memory limit is 6.074074 GB
I0913 14:44:45.362480 19172 mem_tracker.cc:252] MemTracker: soft memory limit is 5.162963 GB
Error deleting universe replication: Could not locate the leader master: GetMasterRegistration RPC to 172.152.53.106:7100 timed out after 2.500s
Error: Timed out (yb/rpc/outbound_call.cc:510): Unable to delete replication for universe f20d0f7a-940e-4324-908f-9785c188d5cc: Could not locate the leader master: GetMasterRegistration RPC to 172.152.53.106:7100 timed out after 2.500s
```
In this case, the universe `f20d0f7a-940e-4324-908f-9785c188d5cc` that contains the 172.152.53.106 address was destroyed. A possible solution might be to add a --force argument.

**Comment by ndeodhar** [comment]
Makes sense. Currently, the steps involved in deleting universe replication are:
1. Delete CDC consumers.
2. Delete CDC streams setup on producer cluster.
3. Delete replication from master maps.

Step (2) is what fails here. We should just go ahead and delete the replication from master anyway. Producer cluster won't be impacted by CDC streams lying around. And in future, we can have some mode to cleanup old, inactive CDC streams.

**Comment by ndeodhar** [comment]
@hectorgcr Can you confirm that this is fixed by https://github.com/yugabyte/yugabyte-db/commit/d6ad9e440a58a010320570a8387a981c8a7e40bd and close the issue?
