### ISSUE TITLE
[YSQL] Enable support for ALTER TABLE IF EXISTS t RENAME command

### ISSUE THREAD

**Issue by fizaaluthra** [yugabyte/yugabyte-db#23011]
Jira Link: [DB-11940](https://yugabyte.atlassian.net/browse/DB-11940)
### Description

ALTER TABLE IF_P EXISTS relation_expr RENAME opt_column name TO name

### Note: the following syntax is already supported
ALTER TABLE relation_expr RENAME opt_column name TO name

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11940]: https://yugabyte.atlassian.net/browse/DB-11940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
Moving `ALTER TABLE ... SET SCHEMA ...` into https://github.com/yugabyte/yugabyte-db/issues/23114
