### ISSUE TITLE
[DocDB] ASAN test failures due to insufficient disk space

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#23035]
Jira Link: [DB-11967](https://yugabyte.atlassian.net/browse/DB-11967)
### Description

Many tests are failing in ASAN because of insufficient disk space. This is likely caused by the recent commit to reject writes if disks have insufficient space: f32d9ec42421d5c892d2cc61a04dcc1e1cc34b7d

```
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:412): Execute of 'CREATE DATABASE test_namespace' failed: 7, message: ERROR:  Write to tablet 00000000000000000000000000000000 rejected. Node 04c9204ef2784cd6852304fabd15f6c7 has insufficient disk space (pgsql error XX000) (aux msg ERROR:  Write to tablet 00000000000000000000000000000000 rejected. Node 04c9204ef2784cd6852304fabd15f6c7 has insufficient disk space)
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11967]: https://yugabyte.atlassian.net/browse/DB-11967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
m-1] E0627 03:15:33.434794 145211 log.cc:2164] Not enough disk space available on ${TEST_TMPDIR}/pg_index_backfill-test.PgIndexBackfillTest.Tablegroup.1719458115031959-144873/minicluster-data/master-0/yb-data/master/wals/table-sys.catalog.uuid/tablet-{sys_catalog_tablet_id}/wal-000000001. Free space: 1910415360 bytes
