### ISSUE TITLE
[DocDB] Analyze is running faster right after restore than subsequent attempts

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#23058]
Jira Link: [DB-11991](https://yugabyte.atlassian.net/browse/DB-11991)
### Description

I've loaded a data into fresh universe using https://github.com/yugabyte/benchbase/blob/retention_pd/config/yugabyte/regression_pipelines/retention_impact/yugabyte/retention_impact.yaml and then created a backup.
Running `analyze nets_1` on the loaded data takes about 20 minutes and "Disk Bytes / Node" read metric is about 17MB/sec, CPU load is less than 2% (and close to the background CPU load without analyze).
But if I restore the data from this backup, the first time I am running `analyze nets_1` it takes about 2.5 minutes and the "Disk Bytes / Node" read metric is up to ~160MB/sec with CPU load around 5-6%.
Next executions of `analyze nets_1` take around 20 minutes with 17 MB/node/sec disk read load and ~2% CPU load.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11991]: https://yugabyte.atlassian.net/browse/DB-11991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
This is resolved by https://github.com/yugabyte/yugabyte-db/issues/23069
