### ISSUE TITLE
[CDC] Fix CDCService checkpoints cache to take both stream and tablet

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#2305]
Currently the checkpoints cache takes in only a tablet id. When we have multiple streams on a table, this wont work.

**Comment by ndeodhar** [comment]
Fixed as part of https://github.com/yugabyte/yugabyte-db/commit/16b79e0ef8bf1a0a97b8c0fa0c8f189663178529.
