### ISSUE TITLE
[YSQL][ASH] Include PID in yb_active_session_history view

### ISSUE THREAD

**Issue by pdvmoto** [yugabyte/yugabyte-db#23070]
### Description

 Asking to include PID in yb_active_session_history. This field is already present in pg_stat_activity, which seems to contain similar data. the current ysql_session_id is just a local-counter, and is not much use "externally", wheras the linux-PID will allow linkup to an actual process.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by hbhanawat** [comment]
@pdvmoto Thanks for submitting the issue. Can you elaborate on the use case when PID will help and ysql_session_id will not? Since the PID is not available for sessions that have ended, I am not sure how to correlate that.

**Comment by FranckPachot** [comment]
I can add some cases where PID may be helpful:
- OOM killer killed a process. It is visible in the trace. Then, it can be helpful to know what this process was doing before
- a long query is running. It is visible in pg_stat_activity (with its PID) and looking at ASH may help understand (queryid is not always set and not unique)
- OS reports high CPU usage in TOP for a Postgres backend, may be good to look at ASH to understand what it is doing

**Comment by pdvmoto** [comment]
What Franck Said.
first use would be for "immediate viewing" and troubleshooting.
plus: I am already working to save some of the data from ahs and pg_stat_activity. This will allow after-the-fact investigation to put together the activity of a given session (pid + startdate).

The "problem" I have with sql_session_id: it doesnt seem to link to anything (yet) ?

**Comment by abhinab-yb** [comment]
Hi @pdvmoto @FranckPachot, thanks for raising this issue, we have replaced the ysql_session_id with pid. cc: @hbhanawat

**Comment by abhinab-yb** [comment]
@pdvmoto I pushed a custom docker image with this change [here](https://hub.docker.com/layers/abhinabsaha/yugabytedb/latest_with_pid/images/sha256-ed814350693bcdc35304cb48234b3971034cd7e786b2ceaf71113eb4b087968a?context=explore). Please note that it's not an official release and only meant for testing

**Comment by pdvmoto** [comment]
Thx, only see this now. Will check ASAP, early next week.

**Comment by pdvmoto** [comment]
Positive! First Tests done. It Works Fine. I can identify processes from ash, and I can find ash-data per-process.

**Comment by pdvmoto** [comment]
I am happily using this new PID. more to follow.
