### ISSUE TITLE
[docs] Use = over ::= for EBNF

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2308]
According to [Wikipedia][wikipedia-ebnf], `=` is used for definitions over `::=`.  Our `.ebnf` files have a majority of the rules using `::=` and a few rules using `=`.  They both work, and the generator converts them to `::=`.  Therefore, there is currently no difference to the end user.  But to those looking at the source EBNF file, using `=` could make syntax highlighting work properly.

[wikipedia-ebnf]: https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form

**Comment by bllewell** [comment]
Fixed a long time ago. Forgot to close this until now.
