### ISSUE TITLE
[YSQL] Enable support for ALTER VIEW

### ISSUE THREAD

**Issue by fizaaluthra** [yugabyte/yugabyte-db#23117]
Jira Link: [DB-12050](https://yugabyte.atlassian.net/browse/DB-12050)
### Description

Parser change + import tests.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12050]: https://yugabyte.atlassian.net/browse/DB-12050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
Reopening the issue to complete the backports to 2024.1
