### ISSUE TITLE
 [YSQL] Enable support for ALTER TABLE .. SET SCHEMA commands

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#23114]
Jira Link: [DB-12047](https://yugabyte.atlassian.net/browse/DB-12047)
### Description

ALTER TABLE relation_expr SET SCHEMA name
ALTER TABLE IF_P EXISTS relation_expr SET SCHEMA name

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12047]: https://yugabyte.atlassian.net/browse/DB-12047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DB-11940]: https://yugabyte.atlassian.net/browse/DB-11940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
Fixed in the `master` branch.
(Let me know if we need any backports. Backports are not planned for now.)

**Comment by OlegLoginov** [comment]
NOTE: the next commit breaks the functionality by mistake:
https://github.com/yugabyte/yugabyte-db/commit/3d4bc2ab9b008d57915b102809e522996c6bb833#diff-f8d636ae673f702b8477da50fe7f6b8cdc9c5ad10d54a6e10bbcc0ce1eb1c51eL10063-R10074

Fix: `[#23457] YSQL: Revert bad grammar changes`
Diff:    D37210

**Comment by sushantrmishra** [comment]
Reopening the issues to complete the backport for 2024.1
