### ISSUE TITLE
[YSQL] Read Only Deferrable in Serializable isolation is waiting for concurrent write transactions to commit

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#23120]
Jira Link: [DB-12053](https://yugabyte.atlassian.net/browse/DB-12053)
### Description

Consider the following steps in order:

```
Session 1:

yugabyte=# BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE READ ONLY DEFERRABLE;
BEGIN

Session 2:
yugabyte=# BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
yugabyte=# UPDATE test SET v=v+1 WHERE k=1;
UPDATE 1

Session 1:
yugabyte=# SELECT * FROM test;
<waits for the concurrent transaction in Session 2 to commit>
```

The SELECT in Session 1 shouldn't really wait. SERIALIZABLE READ ONLY internally uses snapshot isolation as an optimization, so no read locks are taken by the SELECT in this case (unlike any regular read in serializable isolation level).

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12053]: https://yugabyte.atlassian.net/browse/DB-12053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pao214** [comment]
Landed on master, 2024.1, and 2.20.
