### ISSUE TITLE
[YSQL] Logical replication streams duplicate rows of data

### ISSUE THREAD

**Issue by fivetran-lingyizhao** [yugabyte/yugabyte-db#23174]
Jira Link: [DB-12113](https://yugabyte.atlassian.net/browse/DB-12113)
### Description

Perform a certain amount of rows(starting around ~25k) of DML within one transaction, and `pg_recvlogical` gets duplicate rows of data.

Step to reproduce:
- create a table `tbl1` with `id` integer primary key and column `t` text
- create a logical replication slot with `test_decoding` plugin on the table
- run cmd `pg_recvlogical -d ybsrc -h 127.0.0.1 -p 5433 --start -f - --username yugabyte -w --slot <slot_name> > logs/ins_25000_rows.txt`
- perform `insert into tbl1 (id, t) select generate_series(1,25000),'ins row';`

By examining the log txt file, there are 50000 rows of data + 2 lines(BEGIN+COMMIT).
Please note, the result may not be exactly 2 times the rows sometimes.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12113]: https://yugabyte.atlassian.net/browse/DB-12113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @fivetran-lingyizhao 

What version are you using?

**Comment by fivetran-lingyizhao** [comment]
Here are the logs from master, tserver and yugabyed. (added `.log` extension to make `.err` and `.out` files able to be updated here):
[master.err.log](https://github.com/user-attachments/files/16182118/master.err.log)
[master.out.log](https://github.com/user-attachments/files/16182119/master.out.log)
[tserver.err.log](https://github.com/user-attachments/files/16182120/tserver.err.log)
[tserver.out.log](https://github.com/user-attachments/files/16182121/tserver.out.log)
[yugabyted.log](https://github.com/user-attachments/files/16182122/yugabyted.log)

Here are the logs from `pg_recvlogical`:
[ins25000.txt](https://github.com/user-attachments/files/16182156/ins25000.txt)
[upd25000.txt](https://github.com/user-attachments/files/16182157/upd25000.txt)
[del25000.txt](https://github.com/user-attachments/files/16182155/del25000.txt)

**Comment by fivetran-lingyizhao** [comment]
Hi @ddorian my build is on master branch up to commit `56ee97`.
show server_version would get `11.2-YB-2.23.0.0-b0`.

**Comment by siddharth2411** [comment]
Hi @fivetran-lingyizhao, we observed from the logs that two clients were attempting to consume changes simultaneously using the same replication slot. This is a restriction defined for replication slots in Postgres itself.

From [documentation](https://www.postgresql.org/docs/11/logicaldecoding-explanation.html),

> Only one receiver may consume changes from a slot at any given time.

Currently, Yugabyte does not enforce this restriction, but it is expected that applications will adhere to it.

**Comment by siddharth2411** [comment]
As discussed offline, after ensuring only one consumer per slot at a given time, things are working as expected. Therefore marking this ticket as closed. 

Note, the limitation of Yugabyte not enforcing the restriction of only one consumer per slot at a given time is being tracked in https://github.com/yugabyte/yugabyte-db/issues/20755
