### ISSUE TITLE
[docs][YSQL] Change username to yugabyte

### ISSUE THREAD

**Issue by jj-kim** [yugabyte/yugabyte-db#2319]
cc: @schoudhury

Commit 713233ad6 changes the default username from `postgres` to `yugabyte`.  The current YSQL API docs have `postgres` hard-coded to prompts.  Either update them to `yugabyte` or find a better solution to eliminate hard-coding.  This issue may be present in other docs pages outside of YSQL API docs.

**Comment by stevebang** [comment]
Closed by fix in https://github.com/yugabyte/yugabyte-db/pull/2409.
