### ISSUE TITLE
Math Issues with MonoDelta

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#2320]
SnapshotTxnTest.HotRow is intermittently failing in tests.  When debugging why, I ran into these interesting lines:

I0912 22:15:36.925714 295585216 snapshot-txn-test.cc:539] Written: 7000 for 12.595s
...
I0912 22:15:48.377612 295585216 snapshot-txn-test.cc:539] Written: 8000 for 11.452s
... 
I0912 22:16:06.821135 295585216 snapshot-txn-test.cc:539] Written: 9000 for 18.443s
../../src/yb/client/snapshot-txn-test.cc:541: Failure
Expected: (passed) <= (block_time * 2), actual: 18.443s vs 18.280s

block_time should be 11.452, so (block_time * 2) == 22.904, not 18.280

I've tried to repeat this issue with sleep_for() but have not been successful.

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F8365%2Fartifact%2Fbuild%2Fdebug-clang-dynamic-ninja%2Fyb-test-logs%2Ftests-client__snapshot-txn-test%2FSnapshotTxnTest_HotRow.log?max_lines=3000&start_line=3001   (attached in case this expires)

[SnapshotTxnTest_HotRow.log](https://github.com/YugaByte/yugabyte-db/files/3612264/SnapshotTxnTest_HotRow.log)

**Comment by spolitov** [comment]
Why do you think that it should be 22.904? We take block_time from the first block.
Here we have
```
Written: 1000 for 9.140s
```
So is it correct to see 18.280s.
