### ISSUE TITLE
[DocDB] Only show relevant flags in /varz endpoint

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#23223]
Jira Link: [DB-12163](https://yugabyte.atlassian.net/browse/DB-12163)
### Description

`yb-tserver` and `yb-master` use the same executable file (`yb-server`) when built in release mode, so the endpoint that shows the list of flags (`/varz`) displays the flags for both processes, even if a flag is only relevant to one of them.

We should filter this endpoint to only show the flags listed in `master.xml` / `tserver.xml`.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12163]: https://yugabyte.atlassian.net/browse/DB-12163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
<img width="946" alt="image" src="https://github.com/user-attachments/assets/cc594257-f03e-4fcc-ac6b-47e38e8c383e">
