### ISSUE TITLE
[YSQL] Incorrect permission check logic

### ISSUE THREAD

**Issue by andrei-mart** [yugabyte/yugabyte-db#23266]
Jira Link: [DB-12192](https://yugabyte.atlassian.net/browse/DB-12192)
### Description

https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/utils/adt/yb_lockfuncs.c#L59

Trivial bug in the permission check condition, permission denied if user is (not superuser **and** not yb_db_admin), not if user is (not superuser **or** not yb_db_admin). Or means user has to be both to pass.
The  superuser is a yb_db_admin, that's why the bug went undiscovered for so long.

In fact, since superuser is a yb_db_admin, it is sufficient to check if user is (not yb_db_admin) to deny the permission.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12192]: https://yugabyte.atlassian.net/browse/DB-12192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pao214** [comment]
Landed on master, 2024.1, 2.20.
