### ISSUE TITLE
[YSQL] TestPgAuthorization full test fails

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#23295]
Jira Link: [DB-12216](https://yugabyte.atlassian.net/browse/DB-12216)
### Description

`./yb_build.sh fastdebug --gcc11 --java-test org.yb.pgsql.TestPgAuthorization` gets

```
ERROR: role "yb_db_admin_member" already exists
```

because commit 399f165cc4ca15bbd605c4560df6f24406518349 introduces test testPgLocksAuthorization that creates yb_db_admin_member when there already exists another test testSessionAuthorization that creates that role and doesn't drop it.

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12216]: https://yugabyte.atlassian.net/browse/DB-12216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pao214** [comment]
Landed the change on master, 2024.1, and 2.20.
