### ISSUE TITLE
[YSQL] Unexpected termination of replication stream with ERR: "Catalog Version Mismatch: A DDL occurred while processing this query"

### ISSUE THREAD

**Issue by fivetran-lingyizhao** [yugabyte/yugabyte-db#23310]
Jira Link: [DB-12235](https://yugabyte.atlassian.net/browse/DB-12235)
### Description

Error with unexpected termination of the logical replication stream:
```
pg_recvlogical: unexpected termination of replication stream: ERROR:  Stream ID ad98d87f7f2435a99a455e8df44ab723 is expired for Tablet ID cd3756a1e2a54d7da1847a3b438f3386
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```

Steps to reproduce:
- create replication slot with decoding plugin `test_decoding`
`SELECT * FROM pg_create_logical_replication_slot('slotname', 'test_decoding');`

- perform DML, DDL(add/drop columns), DML, DDL interleavedly

- getting the above error, but not always, not finding an exact pattern yet; once get the error, will have to drop the slot and re-create one.

[postgresql-2024-07-29_215127.log](https://github.com/user-attachments/files/16422451/postgresql-2024-07-29_215127.log)
All logs collected from `yugabyted collect_logs` are too large to upload here so I upload the one contains the error.

### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12235]: https://yugabyte.atlassian.net/browse/DB-12235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @fivetran-lingyizhao 

What version are you using?

Note that you can also upload compressed files. Or upload them in your google drive compressed temporarly.
