### ISSUE TITLE
[CDC] GetChanges crashes when non-existant stream id used

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#2336]
When running the kafka app with a stream id that doesn't exist, the RPC call GetChanges crashes the tserver.

**Comment by ndeodhar** [comment]
This is likely fixed by commit https://github.com/yugabyte/yugabyte-db/commit/4df1b94bb708552027b4e3865553327ae0e13789.

I've added a unit test for this scenario as well. But @rahuldesirazu, can you please try via kafka app and confirm that you don't see this anymore?

**Comment by ndeodhar** [comment]
Got a confirmation from @rahuldesirazu that this no longer reproduces with Kafka app.
