### ISSUE TITLE
ysqlconnmgr tests are failing

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#23458]
Jira Link: [DB-12378](https://yugabyte.atlassian.net/browse/DB-12378)
### Description

Found some detective warnings!
        5 builds with failed tests:  o.y.ysqlconnmgr.DropAndRenameDb.DropDbFail, o.y.ysqlconnmgr.DropAndRenameDb.RenameDbFails, o.y.ysqlconnmgr.SessionParameters, o.y.ysqlconnmgr.SessionParameters.StartupParameters, o.y.ysqlconnmgr.StatsAndMetrics.Connections, o.y.ysqlconnmgr.StatsAndMetrics.SingleStickyConnectionClose, o.y.ysqlconnmgr.UnstickyConnections.RolledBackTransactions, o.y.ysqlconnmgr.UnstickyConnections, o.y.ysqlconnmgr.UserLoginLimit

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12378]: https://yugabyte.atlassian.net/browse/DB-12378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by manav-yb** [comment]
This issue is handled in [23422](https://github.com/yugabyte/yugabyte-db/issues/23422) and gets all above mentioned tests pass successfully.
