### ISSUE TITLE
[docs] Document "Distributed backups" backup and restore

### ISSUE THREAD

**Issue by lhotari** [yugabyte/yugabyte-db#2349]
There's currently no documentation for the "Distributed backups" feature.
atm, https://docs.yugabyte.com/latest/manage/backup-restore/backing-up-data/ mentions "Distributed backups", but doesn't contain any content.

**Comment by lhotari** [comment]
#1970 is related, but it's not covering documenting the higher level "distributed backups" feature.

**Comment by ddorian** [comment]
Closing as already done.
