### ISSUE TITLE
[DocDB] PgMiniTest.FollowerReads unit test failure

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#23646]
Jira Link: [DB-12557](https://yugabyte.atlassian.net/browse/DB-12557)
### Description

 This test started failing in **alma8-clang17-tsan** after this [commit](https://github.com/yugabyte/yugabyte-db/commit/79888cf12d5eceb58c30a2934222499cc71fa237)
 
 PgMiniTest.FollowerReads:
[ Analyze Trends](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgMiniTest&fail_tag=all&name=FollowerReads&num_commits=500&platform=linux)
 
 `
../../src/yb/yql/pgwrapper/pg_mini-test.cc:422 Expected equality of these values:   value     Which is: "NEW"   (short_staleness || expect_old_behavior_before_20482) ? "NEW" : "old"     Which is: "old"
`

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12557]: https://yugabyte.atlassian.net/browse/DB-12557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amitanandaiyer** [comment]
Fixed with da6274e15426576ab88fae03950b39ef691de5c9
