### ISSUE TITLE
[YSQL] PgAutoAnalyzeTest.TriggerAnalyzeTableRenameAndDelete- Unit test failure

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#23656]
Jira Link: [DB-12567](https://yugabyte.atlassian.net/browse/DB-12567)
### Description

**_PgAutoAnalyzeTest.TriggerAnalyzeTableRenameAndDelete_**:  
This test is failing consistently in  alma8-clang17-tsan. 
[Analyze Trends](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgAutoAnalyzeTest&fail_tag=all&name=TriggerAnalyzeTableRenameAndDelete&num_commits=2000&platform=linux)
```
Failed
Bad status: Timed out (yb/util/backoff_waiter.cc:78): Operation 'Check expected reltuples vs actual reltuples' didn't complete within 210015ms
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12567]: https://yugabyte.atlassian.net/browse/DB-12567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Issue fixed by commit 475d76c
