### ISSUE TITLE
[2DC] Handle producer cluster changes

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2365]
Today, we get a copy of the producer's cluster while setting up replication. Later, when producer cluster changes (say, nodes are added/removed), consumer's view of the producer cluster is not updated.

We should modify CDC consumer to periodically get a copy of producer cluster.

**Comment by rahuldesirazu** [comment]
I feel like this should come for free when we have a meta cache implementation on the consumer side. That should automatically figure out new tablet locations when we add/remove servers on the producer cluster.

**Comment by nspiegelberg** [comment]
This is a low priority feature until tablet splitting is added to YBase.  The number of tablets is currently static, so producer cluster would need to have all 3 replicas as dead nodes with no proxy redirection before we would have connectivity issues.
