### ISSUE TITLE
Copy back pg_regress output files to regress build dir

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2368]
Commit 045c79a001 sets the output directory of pg_regress to a temporary directory.  It would be nice to get the output files back to the regress build directory: build/latest/postgres_build/src/test/regress.  This would enable users to access the sql, expected, and results files, all of which are valuable for testing and debugging.

**Comment by jj-kim** [comment]
It also seems that the files in the temporary directory are removed by the end of a testing session (e.g. `yb_build.sh asan --java-test foo`).  This appears to happen in `MiniYBCluster.shutdown`.  Any copying back could be placed close to this.

**Comment by jaki** [comment]
Closed by commit 7fba1a859a262067a8a3717a447c5cc5099fd75a (above).
