### ISSUE TITLE
[YSQL] ybgin Index Performance for Exact Match Queries on JSONB Fields with Recheck Overhead

### ISSUE THREAD

**Issue by ucguy4u** [yugabyte/yugabyte-db#23703]
Jira Link: [DB-12612](https://yugabyte.atlassian.net/browse/DB-12612)
### Description

I am experiencing performance degradation when using the `ybgin` index in YugabyteDB for exact match queries on JSONB fields. Specifically, the index recheck process seems to cause significant overhead, particularly in cases where the JSONB data contains similar key-value pairs across rows.

Despite creating the GIN index, the query execution time is higher with the index than without it. The query is performing a large number of rechecks, as seen in the query execution plan.

## Steps to Reproduce

Below is a simple simulation to reproduce the issue using a table with JSONB data and queries on exact matches.

### Reproducible Script

1. **Create Table and Insert Sample Data**

   The table is created with a primary key and a JSONB column, and 10,000 rows are inserted with a similar structure.

   ```sql
   -- Create the documents table
   CREATE TABLE IF NOT EXISTS documents (
       doc_id BIGINT PRIMARY KEY,
       content JSONB
   );

   -- Insert 10,000 rows with similar key-value pairs in the JSONB field
   DO $$
   DECLARE i INT;
   BEGIN
     FOR i IN 1..10000 LOOP
       INSERT INTO documents (doc_id, content)
       VALUES (i, ('{"title": "PostgreSQL Tutorial ' || i || '", "author": "Author ' || i || '", "tags": ["database", "sql", "postgresql"]}')::jsonb);
     END LOOP;
   END $$;
   ```

2. **Run Query Without Index**

   First, test the query performance without the `ybgin` index. This query should scan the entire table.

   ```sql
   -- Run the query without an index
   EXPLAIN ANALYZE SELECT * FROM documents WHERE content @> '{"title": "PostgreSQL Tutorial 1"}';
   ```

   Expected result (example):
   ```plaintext
   Seq Scan on documents (cost=0.00..102.50 rows=1000 width=40) (actual time=10.331..10.335 rows=1 loops=1)
   Storage Filter: (content @> '{"title": "PostgreSQL Tutorial 1"}'::jsonb)
   Planning Time: 7.257 ms
   Execution Time: 10.647 ms
   ```

3. **Create the `ybgin` Index and Re-run the Query**

   Now create the `ybgin` index and re-run the query. This is where performance issues are observed due to recheck overhead.

   ```sql
   -- Create the GIN index using ybgin
   CREATE INDEX idx_jsonb_content ON documents USING ybgin (content);

   -- Re-run the query with the GIN index
   EXPLAIN ANALYZE SELECT * FROM documents WHERE content @> '{"title": "PostgreSQL Tutorial 1"}';
   ```

   Observed result:
   ```plaintext
   Index Scan using idx_jsonb_content on documents (cost=8.00..16.01 rows=1000 width=40) (actual time=34.485..34.742 rows=1 loops=1)
   Index Cond: (content @> '{"title": "PostgreSQL Tutorial 1"}'::jsonb)
   Rows Removed by Index Recheck: 9999
   Planning Time: 8.733 ms
   Execution Time: 35.060 ms
   ```

   **Note**: Despite using the `ybgin` index, the query execution time increases significantly due to the recheck phase, where 9999 rows are removed by the index recheck.

4. **Proposed Solution: B-tree Index**

   Since the `ybgin` index is struggling with exact matches, a B-tree index on the extracted `title` field in the JSONB can be used for better performance:

   ```sql
   -- Create a B-tree index on the title field within the JSONB
   CREATE INDEX idx_title_btree ON documents ((content->>'title'));

   -- Run the query using the B-tree index
   EXPLAIN ANALYZE SELECT * FROM documents WHERE content->>'title' = 'PostgreSQL Tutorial 1';
   ```

## Expected Behavior

The `ybgin` index should perform more efficiently, especially when querying JSONB fields with exact match conditions. The recheck overhead is causing significant delays, even when the exact match should be straightforward.

## Environment Details

- **Database**: YugabyteDB (version 2.21.1.0 build 271 revision d65732c66a715227027f3052472cd8d0844d3d4b build_type RELEASE built at 04 Jun 2024 18:27:43 UTC)
- **Extension**: `ybgin`
- **OS**: [MAC 14.6.1 (23G93)]
- **Replication Factor**: 1 (or any replication setup you're using)

## Additional Context

I have also tested larger datasets with similar results. The index recheck phase always results in significantly higher execution times, especially when the JSONB field contains similar structures across rows.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12612]: https://yugabyte.atlassian.net/browse/DB-12612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @ucguy4u 

This is a bit expected from the current design https://docs.yugabyte.com/preview/explore/ysql-language-features/indexes-constraints/gin/#timing:

> Therefore, a GIN index scan can be more costly than a sequential scan straight to the main table if the index scan does not filter out many rows.

cc @jasonyb

**Comment by ucguy4u** [comment]
Thanks for the response

> Hi @ucguy4u
> 
> This is a bit expected from the current design https://docs.yugabyte.com/preview/explore/ysql-language-features/indexes-constraints/gin/#timing:
> 
> > Therefore, a GIN index scan can be more costly than a sequential scan straight to the main table if the index scan does not filter out many rows.
> 
> cc @jasonyb
