### ISSUE TITLE
[docs] Document that YCQL role is given full permissions on objects it creates

### ISSUE THREAD

**Issue by jameshartig** [yugabyte/yugabyte-db#2374]
When a role creates a keyspace it is given full permissions: `['ALTER', 'AUTHORIZE', 'CREATE', 'DROP', 'MODIFY', 'SELECT']` on that keyspace. That's not documented anywhere on the docs sites as far as I can tell and was originally confusing to me since I didn't give the role any other permissions besides `CREATE`.

**Comment by ddorian** [comment]
This is mentioned in https://docs.yugabyte.com/latest/api/ycql/ddl_grant_permission/:

> When a database object is created (keyspace, table, or role), an automatic and explicit grant of all the permissions relevant to the object are granted to the role creating it.
