### ISSUE TITLE
[DOC] tiny mistake in an image

### ISSUE THREAD

**Issue by amitlan** [yugabyte/yugabyte-db#2376]
Hello,

This is my first contact with the YugaByte community. :)

While going through:
https://docs.yugabyte.com/latest/architecture/core-functions/table-creation

I noticed that the image shown in the example:
https://docs.yugabyte.com/images/architecture/tserver_tablet_assignment.png

contains a tiny mistake --  tablet 16 apparently consists of only 1 peer, whereas it should have 3 like other tablets.

**Comment by kmuthukk** [comment]
@amitlan --

yes tablet 16 should also say peer 1, peer 2, peer3 instead of peer 1, peer 1, peer 1.

Could catch!
