### ISSUE TITLE
I want to try Yugaware but I have been unable to get Yugabyte license file.

### ISSUE THREAD

**Issue by sain801028** [yugabyte/yugabyte-db#2377]
My team recently rigorously evaluated whether YugaByte DB is used in production.

I don't do any special use under normal use. "For example, software is used in auctions." Can I always use Yugaware?

I need help

**Comment by ramkumarvs** [comment]
@sain801028 hey let us know if you wanted to try our YugaByte DB Platform, we can connect with you and understand your use case and recommend accordingly.

**Comment by sain801028** [comment]
Ok

**Comment by ameyb** [comment]
@sain801028 whats the best way to connect with you and schedule a meeting to discuss the use-case and YugaByteDB platform license? Can you provide email/contact details?

**Comment by sain801028** [comment]
The things I ask for are actually very simple. 
The YugaByte DB Platform is kept in a certain range of use and should not be completely commercialized. 
After all, YugaByte DB Platform is the main tool of YugaByte DB.
