### ISSUE TITLE
[DocDB] UpdateTransactionWaitingForStatus could execute rpc callback twice

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#23808]
Jira Link: [DB-12709](https://yugabyte.atlassian.net/browse/DB-12709)
### Description

When a node with wait-queue/deadlock detection disabled receives a UpdateTransactionWaitingForStatus probe (as other nodes might have the feature on), we detect that the feature is disabled, log a warning, and execute the callback. 

We should return at this point, but seems like we don't, leading to the below errors. These errors are benign (but might cause confusion in general) and do not cause transactions to fail. The errors should be seen only during the window when the feature is off on some set of nodes and ON in the other, and shouldn't happen after all the nodes have the wait-queues feature on. 

```
E0905 09:29:14.733906 311925 inbound_call.cc:239] 0x00000413bdbee700 -> Call yb.tserver.TabletServerService.UpdateTransactionWaitingForStatus 172.151.23.227:33073 => 172.151.20.110:9100 (request call id 1129328): Already marked as completed
E0905 09:29:14.734081 311925 inbound_call.cc:269] 0x00000413bdbee700 -> Call yb.tserver.TabletServerService.UpdateTransactionWaitingForStatus 172.151.23.227:33073 => 172.151.20.110:9100 (request call id 1129328): Response already queued
E0905 09:29:14.752063 311925 inbound_call.cc:239] 0x00000413bc68aa80 -> Call yb.tserver.TabletServerService.UpdateTransactionWaitingForStatus 172.151.23.227:39555 => 172.151.20.110:9100 (request call id 1129398): Already marked as completed
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12709]: https://yugabyte.atlassian.net/browse/DB-12709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Deciding to backport the fix for the unnecessary logging to 2024.1 (as wait-queues is enabled by default in that release), so as to avoid confusion (especially when someone is looking at logs).
