### ISSUE TITLE
[YSQL] LDAP Integration for YugabyteDB

### ISSUE THREAD

**Issue by AmirAbrams** [yugabyte/yugabyte-db#2393]
Jira Link: [DB-2197](https://yugabyte.atlassian.net/browse/DB-2197)
Support LDAP authorization and authentication.

## YSQL
For YSQL, this would be similar to the [PostgreSQL LDAP authentication support](https://www.postgresql.org/docs/12/auth-ldap.html). This is tracked in #6088

## YCQL

Similar to YSQL, LDAP should also be supported for YCQL. This is tracked in #4421 

[![Analytics](https://yugabyte.appspot.com/UA-104956980-4/issues/2393/ldap-integration?pixel&useReferer)](https://github.com/yugabyte/ga-beacon)

**Comment by ajcaldera1** [comment]
On which API are you seeking this support - YCQL or YSQL?

**Comment by AmirAbrams** [comment]
YSQL. Thanks again.

**Comment by ajcaldera1** [comment]
We haven't formally tested it yet, but it should be enabled already. We re-use the top 80% of the PG distribution in our code, so postmaster should work out of the box. To pass the pg_hba.conf settings you need for LDAP, use the flag `--ysql_hba_conf="<comma separated list of pg_hba.conf entries>"` on your yb-tserver invocation either on the command line or in the flag file as documented.
We are based on PG 11.2, so use the appropriate docs for that release. If you could, please reply to this thread with your results, positive or negative.
Thanks.

**Comment by sushantrmishra** [comment]
LDAP integration is currently supported in YugabyteDB . 

YSQL-  https://github.com/yugabyte/yugabyte-db/issues/6088
YCQL -- https://github.com/yugabyte/yugabyte-db/issues/4421
