### ISSUE TITLE
[YSQL] Replace copyright string YugaByteDB with YugabyteDB

### ISSUE THREAD

**Issue by pao214** [yugabyte/yugabyte-db#23940]
Jira Link: [DB-12838](https://yugabyte.atlassian.net/browse/DB-12838)
### Description

Linter gives up with an internal offset error.

```
arc lint                                                       
 Exception 
Undefined offset: -1
(Run with `--trace` for a full exception trace.)
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12838]: https://yugabyte.atlassian.net/browse/DB-12838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pao214** [comment]
Landed on master.

**Comment by pao214** [comment]
Many instances of YugaByte still remaining. Those were not replaced because changing them leads to large change.

**Comment by jasonyb** [comment]
Linter should be changed to disallow everything else except YugabyteDB
