### ISSUE TITLE
Wrong results from plpgsql procedure because YB doesn’t implement “savepoint”

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#2397]
Testcase: [issue_2397.zip](https://github.com/yugabyte/yugabyte-db/files/3640860/issue_2397.zip)

Using YB Version 2.0.0 downloaded from the Internet. Running on macOS Mojave Version 10.14.6. Using a single node RF=1 cluster created with bare “yb-ctl create”.

In plpgsql, a block statement that has an “exception” section, inside a stored proc, has a special implementation: the block statement’s “begin” (probably it’s the execution of the first SQL statement that follows it) implicitly creates an anonymous savepoint. And entry into a handler in the block statement’s “exception” section implicitly causes a rollback to the anonymous savepoint.

This is, in fact, a very useful model. And it’s the same model that, for example, Oracle Database uses. The following code demonstrates this vividly. It’s the defining code from the PostgreSQL plpgsql stored procedure attached as `issue_2397.zip`. But it happens to be identical (with one spelling difference) to the corresponding code for an Oracle PL/SQL procedure.
````
  curr_k int not null := 0;
begin
  -- Self-doc of proper practice.
  -- Crazy to call a stored proc when a txn is ongoing.
  rollback;

  for i in 1..2 loop
    for j in 1..5 loop

      <<"Block with handler">>declare --------------------------------
        curr_v constant int not null := (
          case i
            when 1 then j  -- OK
            when 2 then 42 -- collides
          end);
      begin
        curr_k := curr_k + 1;
        insert into t1(k, v) values(curr_k, curr_v);
      exception
        when unique_violation then
          insert into t2(k, v) values(curr_k, curr_v);
      end "Block with handler"; ---------------------------------------

    end loop;
  end loop;
  commit;
end
````
The spelling difference is that the exception named `unique_violation` in plpgsql is named `dup_val_on_index`	 in PL/SQL.

The tables are created thus:
````
create table t1(k int primary key, v int not null unique)
````
and thus:
````
create table t2(k int primary key, v int not null)
````
Notice that the only difference is that `t1.v` has a unique constraint but `t2.v` does not. The procedure models a common use case—but, for clarity, no attempt is made here to use bulk insert. “Slow by slow” single row inserts are sufficient to show the bug. The use case is the bulk load of dirty data into target table `t1`. It ought to satisfy various constraints (modeled here by the unique constraint on `t1.v`). When a dirty row violates any constraint,  it is inserted instead into an errors table (modeled here by `t2`) for later manual scrutiny and clean-up.

The use case demands that successful inserts into `t1` survive and that any unsuccessful insert attempt into `t1` must be individually rolled back in the exception handler (leaving the successfully inserted rows intact). Then the failing row is inserted into the errors table `t2` where, because this doesn’t have the constraints that cause the failure on insert attempt into `t1`, it can be inserted without error.

Notice that the test procedure simulates dirty rows, after inserting only clean rows, by the simple device of causing the unique constraint on `t1.v` to be violated by inserting a row with `v = 42` five times. Here is the result, when the procedure finishes, using the vanilla PostgreSQL Version 11.2. This query:
````
select k, v from t1 order by k
````
shows this result:
````
 k | v  
---+----
 1 |  1
 2 |  2
 3 |  3
 4 |  4
 5 |  5
 6 | 42
````
This query:
````
select k, v from t1 where v = 42 order by k
````
shows this result:
````
 k | v  
---+----
 6 | 42
````
And this query:
````
select k, v from t2 order by k
````
shows this result:
````
 k  | v  
----+----
  7 | 42
  8 | 42
  9 | 42
 10 | 42
````
I ran the Oracle version using Oracle Database 18cXE. The output was identical to the PostgreSQL output.

Look at the YB output for the same queries:
````
 k  | v  
----+----
  1 |  1
  2 |  2
  3 |  3
  4 |  4
  5 |  5
  6 | 42
  7 | 42
  8 | 42
  9 | 42
 10 | 42
````
and:
````
 k | v  
---+----
 6 | 42
````
and:
````
 k  | v  
----+----
  7 | 42
  8 | 42
  9 | 42
 10 | 42
````
We see that, because YB doesn’t yet implement `savepoint`, the rows that violate the unique constraint on `t1.v` nevertheless end up in the table `t1`. We also see a shocking downstream error. The unique constraint is still in place. (Test this with an ad hoc insert attempt that will vviolateiloate it.) Yet that table has rows that violate the constraint. Further, the `select` restricted by `v = 42` finds only the first row that was inserted because the unique index that implements the constraint cannot represent two or more values for the same key. This is "wrong results" deluxe.

**NOTE:** There’s a different common use-case: the implementation of a business transaction that must fail or succeed atomically when, typically, its implementation requires several different SQL statements. Here, you write “rollback” in the exception handler(s) and either abort or (for example for a serialization error) retry. For this use case, the fact that YB doesn’t implement `savepoint` is of no consequence.

**Comment by bllewell** [comment]
Here's the simplest test that I can imagine. I used a single-node cluster on my MacBook with _YB-2.4.0.0-b0_. 

 First do this:

```
do $body$
begin
  raise info '%', (99.9/0.0);
exception when others then
  raise info 'Exception handled.';
end;
$body$;
```

It works as expected in both PG (of course) and in YB: the exception is caught.

Now do this. Start by setting up table that can be used to provoke a _23505_ error:

```
drop table if exists t1 cascade;
create table t1(k int primary key, v text);
insert into t1(k, v) values(1, 'dog');
```
Now provoke it from a PL/pgSQL block:

```
do $body$
begin
  insert into t1(k, v) values(1, 'cat');
exception when others then
  raise info 'Exception handled.';
end;
$body$;
```

In PG, the exception is caught as expected. In YB, it isn't caught—and this error bubbles up on completion of the anonymous block's execution:

```
-- "duplicate key value violates unique constraint "t1_pkey"
```

**Comment by bmatican** [comment]
As per @robertsami , even with the current savepoints work, the above example still does not work as expected. cc @m-iancu

**Comment by bllewell** [comment]
@robertsami, do you have an ETA for when this might be fixed?

**Comment by robertsami** [comment]
@bllewell no ETA at the moment, will update as i have more clarity

**Comment by robertsami** [comment]
Latest update here is that when running the following, we have the following error:

```
➜  bin/ysqlsh
ysqlsh (11.2-YB-2.7.3.0-b0)
Type "help" for help.

yugabyte=# create table t1(k int primary key, v text);
CREATE TABLE
yugabyte=# insert into t1(k, v) values(1, 'dog');
INSERT 0 1
yugabyte=# do $body$
yugabyte$# begin
yugabyte$#   insert into t1(k, v) values(2, 'cat');
yugabyte$#   begin
yugabyte$#     insert into t1(k, v) values(1, 'frog');
yugabyte$#   exception when unique_violation then
yugabyte$#     null;
yugabyte$#   end;
yugabyte$# end;
yugabyte$# $body$;
FATAL:  RollbackAndReleaseCurrentSubTransaction: unexpected state STARTED
CONTEXT:  PL/pgSQL function inline_code_block line 4 during exception cleanup
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

It looks like whatever path is calling `RollbackAndReleaseCurrentSubTransaction` on the exception triggered by duplicate insert is doing so when `CurrentTransactionState->blockState` is in the wrong state

note that from `RollbackAndReleaseCurrentSubTransaction` it's expected we're in either `TBLOCK_SUBINPROGRESS` or `TBLOCK_SUBABORT` state before this is called

**Comment by tedyu** [comment]
On master, as of commit bb660828cff4ec3ab8fee9ced156f7323bf3b446, I got:
```
yugabyte=# create table t1(k int primary key, v text);
CREATE TABLE
yugabyte=# insert into t1(k, v) values(1, 'dog');
INSERT 0 1
yugabyte=# do $body$
yugabyte$# begin
yugabyte$#   insert into t1(k, v) values(2, 'cat');
yugabyte$#   begin
yugabyte$#     insert into t1(k, v) values(1, 'frog');
yugabyte$#   exception when unique_violation then
yugabyte$#     null;
yugabyte$#   end;
yugabyte$# end;
yugabyte$# $body$;
ERROR:  duplicate key value violates unique constraint "t1_pkey"
```

**Comment by robertsami** [comment]
@tedyu to reproduce the issue i described, make sure you're running your cluster with `enable_pg_savepoints=true`

**Comment by tedyu** [comment]
Here is slightly modified version of the above test (using a temp table):
```
yugabyte=#  create temp table t1(k int primary key, v text);
CREATE TABLE
yugabyte=#  insert into t1(k, v) values(1, 'dog');
INSERT 0 1
yugabyte=#  do $body$
yugabyte$# begin
yugabyte$#   insert into t1(k, v) values(2, 'cat');
yugabyte$#   begin
yugabyte$#     insert into t1(k, v) values(1, 'frog');
yugabyte$#   exception when unique_violation then
yugabyte$#     null;
yugabyte$#   end;
yugabyte$# end;
yugabyte$# $body$;
DO
yugabyte=# ^D\q
```
No fatal error. I started local cluster this way:
```
bin/yb-ctl start --tserver_flags 'enable_pg_savepoints=true'
```

**Comment by tedyu** [comment]
```
yugabyte=# create table bdt (a int primary key);
CREATE TABLE
yugabyte=# insert into bdt values (1),(2);
INSERT 0 2
yugabyte=# create table bdt2 (a int);
CREATE TABLE
yugabyte=# insert into bdt2 values (1);
INSERT 0 1
yugabyte=# DO $$
yugabyte$# BEGIN
yugabyte$#    FOR i IN 1..2 LOOP
yugabyte$#      BEGIN
yugabyte$#        INSERT INTO bdt (a) VALUES (i);
yugabyte$#         exception when unique_violation then update bdt2 set a = i;
yugabyte$#       COMMIT;
yugabyte$#      END;
yugabyte$#    END LOOP;
yugabyte$# END;
yugabyte$# $$;
FATAL:  RollbackAndReleaseCurrentSubTransaction: unexpected state STARTED
CONTEXT:  PL/pgSQL function inline_code_block line 4 during exception cleanup
server closed the connection unexpectedly
```
It seems unique_violation can often trigger the assertion.

**Comment by bllewell** [comment]
What is the design philosophy of your test, @tedyu? I re-wrote it to use names that seemed more to reflect a possible design philosophy:

```
drop table if exists t cascade;
drop table if exists log cascade;

create table t(k int primary key);
insert into t(k) values (1),(2);

create table log(k int);
insert into log values (1);

do $body$
begin
  for j in 1..2 loop
    begin
      insert into t(k) values (j);
    exception when unique_violation then
      update log set k = j;
      --commit;
    end;
  end loop;
end;
$body$;

select k from t order by 1;
select k from log order by 1;
```

And I ran it on PG Version 13.4—where I assume that the behavior is exactly as intended. Notice that I commented out "commit". The results are identical, whether or not "commit" is active—thus:

```
 k 
---
 2
```

This is exactly what I expect. In other words, and with this code as presented, "commit" has no semantic effect and serves only to slow down execution (at least, in principle). In other words, the _log_ table records just the value of the _most recent_ violating key.

Notice that I called the second table _log_ — because this seems to be the table's purpose. Why did you _update_ its singleton row to log the value most recent key that violates the unique constraint in the main table, _t_? It would be far more natural to use _insert_ into an error log table like this in order to record the values of _all_ violating keys:

```
drop table if exists t cascade;
drop table if exists log cascade;

create table t(k int primary key);
insert into t(k) values (1),(2);

create table log(k int);

do $body$
begin
  for j in 1..2 loop
    begin
      insert into t(k) values (j);
    exception when unique_violation then
      insert into log(k) values(j);
    end;
  end loop;
end;
$body$;

select k from t order by 1;
select k from log order by 1;
```

I ran this on PG 13.4 too. It produces the expected content in the _log_ table:

```
 k 
---
 1
 2
```

So... to repeat the question, what does your _most recent_ notion aim to tell us?

**Comment by tedyu** [comment]
Edited my previous comment.

**Comment by mtakahar** [comment]
The reason why unique_violation is not getting caught by the PL/pgSQL exception handler is that the error from INSERT operation by DocDB is received and handled asynchronously after the entire procedure is finished. In the following code snippet, the PL/pgSQL procedure block is executed under standard_ProcessUtility. There, the INSERT statement is eventually sent to DocDB as an RPC request but it doesn't wait there unless the RETURNING clause is specified.
(I haven't seen the FATAL error that @robertsami yet in my environment (master c3f6f6c98, macOS 11.6 debug or release build), though.)
```
void
YBProcessUtilityDefaultHook(PlannedStmt *pstmt,
                            const char *queryString,
                            ProcessUtilityContext context,
                            ParamListInfo params,
                            QueryEnvironment *queryEnv,
                            DestReceiver *dest,
                            char *completionTag)
{
	if (IsYugaByteEnabled() && !(IsA(pstmt->utilityStmt, ExecuteStmt) ||
			IsA(pstmt->utilityStmt, PrepareStmt) || IsA(pstmt->utilityStmt, DeallocateStmt) ||
			IsA(pstmt->utilityStmt, ExplainStmt))) {
		YBBeginOperationsBuffering();
		standard_ProcessUtility(pstmt, queryString, context, params, queryEnv, dest, completionTag);
		YBEndOperationsBuffering();
  } else {
		standard_ProcessUtility(pstmt, queryString, context, params, queryEnv, dest, completionTag);
	}
}
```

Adding the RETURNING clause to the INSERT statement causes the PostgreSQL side to wait the response from DocDB and the unique key violation is handled as expected:
```
yugabyte(90809)# do $body$
begin
  insert into t1(k, v) values(1, 'cat') returning *;
exception when others then
  raise info 'Exception handled.';
end;
$body$;

do $body$
yugabyte$# begin
yugabyte$#   insert into t1(k, v) values(1, 'cat') returning *;
yugabyte$# exception when others then
yugabyte$#   raise info 'Exception handled.';
yugabyte$# end;
yugabyte$# $body$;
INFO:  00000: Exception handled.
LOCATION:  exec_stmt_raise, pl_exec.c:3827
ERROR:  23505: duplicate key value violates unique constraint "t1_pkey"
LOCATION:  HandleYBStatusAtErrorLevel, pg_yb_utils.c:367
yugabyte(90809)# 
```

However, adding the RETURNING clause doesn't seem to fix the incorrect results from the testcase.sql. I'll keep looking into this.

**Comment by bllewell** [comment]
Please confirm that the observation

> the error from INSERT operation by DocDB is received and handled asynchronously after the entire procedure is finished

is no more than an account of the current state of the YB implementation—and that this cannot be considered to be a good thing.

The aim is that any use of exception handling in a PL/pgSQL program will behave identically in YugabyteDB (YSQL) to how it behaves in PostgreSQL (at least comparing YB with the PG Version upon which the YSQL implementation depends).

**Comment by mtakahar** [comment]
@bllewell I am still trying to understand what is goin on. I was merely stating the facts that I found so far.

**Comment by mtakahar** [comment]
@bllewell the current behavior is not good for sure. I defer criticizing or commenting the implementation until I gather more facts.

**Comment by mtakahar** [comment]
The latest update:
* I can confirm that A) the originally reported wrong results issue and B) the transaction state inconsistency error (FATAL:  RollbackAndReleaseCurrentSubTransaction: unexpected state STARTED) are **two separate issues caused by different root causes**. And C) the unique constraint violation error not being caught by the exception handler, is a different manifestation of the problem B).
* A) the wrong results is because an API call, YBCRollbackSubTransaction, is not called when an exception happens. As a result, the violating row is rejected by the unique index itself but the one already inserted into the underlying table stays there without getting rolled back.
  * Less obvious with the rows that violates the primary key constraint because they get rejected without getting inserted into the table.
  * Calling YBCRollbackSubTransaction from AbortSubTransaction (xact.c) address this issue.
  * Reproducible with out without enabling the savepoint feature. Here is a somewhat simplified test case. **The behavior is the same with or without enabling the savepoint feature:**
```
drop table if exists t1;
DROP TABLE
create table t1(k int primary key, v int not null unique);
CREATE TABLE

do $body$
declare
  row record;
begin
  insert into t1(k, v) values(1, 42);

  begin
    insert into t1(k, v) values(2, 42);
    select * into row from t1;  -- flush buffered ops
  exception
    when unique_violation then
      raise notice 'unique violation 1';
  end;

  begin
    insert into t1(k, v) values(3, 42);
    select * into row from t1;  -- flush buffered ops
  exception
    when unique_violation then
      raise notice 'unique violation 2';
  end;
end;
$body$;
ysqlsh:wrong-results-simple.sql:28: NOTICE:  unique violation 1
ysqlsh:wrong-results-simple.sql:28: NOTICE:  unique violation 2
DO


-- full table scan - WRONG

select /*+ SeqScan(t1) */ * from t1 where k > 0 and v > 0 order by k;
 k | v  
---+----
 1 | 42
 2 | 42
 3 | 42
(3 rows)

explain select /*+ SeqScan(t1) */ * from t1 where k > 0 and v > 0 order by k;
                         QUERY PLAN                         
------------------------------------------------------------
 Sort  (cost=64.83..67.33 rows=1000 width=8)
   Sort Key: k
   ->  Seq Scan on t1  (cost=0.00..15.00 rows=1000 width=8)
         Filter: ((k > 0) AND (v > 0))
(4 rows)


-- pk scan - WRONG

select /*+ IndexScan(t1 t1_pkey) */ * from t1 where k > 0 and v > 0 order by k;
 k | v  
---+----
 1 | 42
 2 | 42
 3 | 42
(3 rows)

explain select /*+ IndexScan(t1 t1_pkey) */ * from t1 where k > 0 and v > 0 order by k;
                                 QUERY PLAN                                  
-----------------------------------------------------------------------------
 Sort  (cost=171.33..173.83 rows=1000 width=8)
   Sort Key: k
   ->  Index Scan using t1_pkey on t1  (cost=0.00..121.50 rows=1000 width=8)
         Index Cond: (k > 0)
         Filter: (v > 0)
(5 rows)


-- index scan with the secondary index triggering unique violation - CORRECT

select /*+ IndexScan(t1 t1_v_key) */ * from t1 where k > 0 and v > 0 order by k;
 k | v  
---+----
 1 | 42
(1 row)

explain select /*+ IndexScan(t1 t1_pkey) */ * from t1 where k > 0 and v > 0 order by k;
                                 QUERY PLAN                                  
-----------------------------------------------------------------------------
 Sort  (cost=171.33..173.83 rows=1000 width=8)
   Sort Key: k
   ->  Index Scan using t1_pkey on t1  (cost=0.00..121.50 rows=1000 width=8)
         Index Cond: (k > 0)
         Filter: (v > 0)
(5 rows)
```
* B) is because buffered operation flushing is performed in the middle of transaction state change, causing an interruption when an exception is thrown from an operation.  I'll file a separate issue and put more details there.

**Comment by mtakahar** [comment]
With both fixes for missing YBCRollbackSubTransaction call (wrong results) and the crash (#10303), @bllewell's test case produces the same output as postgres 11.2 and oracle:
```
CREATE PROCEDURE
CALL
 k | v  
---+----
 1 |  1
 2 |  2
 3 |  3
 4 |  4
 5 |  5
 6 | 42
(6 rows)

 k | v  
---+----
 6 | 42
(1 row)

 k  | v  
----+----
  7 | 42
  8 | 42
  9 | 42
 10 | 42
(4 rows)
```

**Comment by bllewell** [comment]
This is excellent news. Thanks.
