### ISSUE TITLE
[YSQL] pgwrapper_pg_libpq-test failed。

### ISSUE THREAD

**Issue by frg01** [yugabyte/yugabyte-db#24087]
Jira Link: [DB-12980](https://yugabyte.atlassian.net/browse/DB-12980)
### Description

[ts-1] 2024-09-21 15:37:29.650 CST [1097081] ERROR:  could not serialize access due to concurrent update
[ts-1] 2024-09-21 15:37:29.650 CST [1097081] DETAIL:  ca665a3b-ef19-4b7e-9399-4da34c32d264 conflicts with higher priority transaction: 7cab1fc1-405c-4c46-8d33-0b6902fcd588
[ts-1] 2024-09-21 15:37:29.773 CST [1097186] ERROR:  Unknown transaction, could be recently aborted: 0a7d9138-a0f6-4727-9182-4dca76c00c87
[ts-1] 2024-09-21 15:40:21.977 CST [1171152] ERROR:  All transparent retries exhausted. could not serialize access due to concurrent update
DETAIL:  273bb661-06bd-4709-986e-bc5f8c8318d5 conflicts with higher priority transaction: 35c99287-754a-41e5-8f3f-475806389624 (pgsql error 40001) (aux msg ERROR:  All transparent retries exhausted. could not serialize access due to concurrent update
DETAIL:  273bb661-06bd-4709-986e-bc5f8c8318d5 conflicts with higher priority transaction: 35c99287-754a-41e5-8f3f-475806389624)

[ts-1] 2024-09-21 15:40:22.055 CST [1179597] ERROR:  Transaction 1aa9cf19-de01-4369-8901-841c78dcfcd5 expired or aborted by a conflict: 40001
I0921 15:40:22.055716 1131155 pg_libpq-test.cc:247] Read: Network error (yb/yql/pgwrapper/libpq_utils.cc:341): Execute of 'COMMIT' failed: 7, message: ERROR:  Transaction 1aa9cf19-de01-4369-8901-841c78dcfcd5 expired or aborted by a conflict: 40001 (pgsql error 40001) (aux msg ERROR:  Transaction 1aa9cf19-de01-4369-8901-841c78dcfcd5 expired or aborted by a conflict: 40001), write: OK

[ts-1] 2024-09-21 15:45:45.831 CST [1324959] ERROR:  Resource unavailable: null
[ts-1] 2024-09-21 15:45:45.831 CST [1324959] STATEMENT:  INSERT INTO t2 VALUES (625850, 486757)
[ts-1] 2024-09-21 15:45:45.832 CST [1324955] ERROR:  Resource unavailable: null
[ts-1] 2024-09-21 15:45:45.832 CST [1324955] STATEMENT:  INSERT INTO t2 VALUES (83024, 824870)
[ts-2] I0921 15:45:45.841933 1321615 tablet_service.cc:373] T dc24f4003ed44581b446acfb78763657 P d9e69b7557a2441daf48383f0e75225f [state=RUNNING]: Write failed: Operation failed. Try again (yb/util/operation_counter.cc:261): Resource unavailable: null
[ts-3] I0921 15:45:45.843325 1321616 tablet_service.cc:373] T 00e8034ddca64446947bb56ef1035b10 P 24ba1ee7c39449f4a775e7e91f07053d [state=RUNNING]: Write failed: Operation failed. Try again (yb/util/operation_counter.cc:261): Resource unavailable: null
[ts-1] 2024-09-21 15:45:45.843 CST [1324959] ERROR:  Resource unavailable: null
[ts-1] 2024-09-21 15:45:45.843 CST [1324959] STATEMENT:  INSERT INTO t1 VALUES (253384, 116866)
[ts-1] 2024-09-21 15:45:45.844 CST [1324955] ERROR:  Resource unavailable: null
[ts-1] 2024-09-21 15:45:45.844 CST [1324955] STATEMENT:  INSERT INTO t1 VALUES (166893, 568847)
[m-1] I0921 15:45:45.864328 1319186 catalog_manager.cc:5707] Servicing IsTruncateTableDone request for table id 000033bd000030008000000000004000

[ts-1] 2024-09-21 15:45:45.883 CST [1324959] ERROR:  Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Operation failed. Try again (yb/tablet/transaction_participant.cc:283): Transaction was recently aborted: fabf7735-3fd3-4121-a942-4a1d067b2b18: 40001 (pgsql error 40001) (transaction error 1), Operation failed. Try again (yb/util/operation_counter.cc:261): Resource unavailable: null]

[ts-1] 2024-09-21 15:45:45.883 CST [1324955] ERROR:  Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Operation failed. Try again (yb/tablet/transaction_participant.cc:283): Transaction was recently aborted: 9f5cfd1e-21ea-49a6-a206-31988fd14e6a: 40001 (pgsql error 40001) (transaction error 1), Operation failed. Try again (yb/util/operation_counter.cc:261): Resource unavailable: null]

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12980]: https://yugabyte.atlassian.net/browse/DB-12980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @frg01 

Please add more info?

**Comment by frg01** [comment]
i am wrong
