### ISSUE TITLE
[CDCSDK] Snapshot Consistency taking much longer time after enabling CDC immediate transaction cleanup

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#24096]
Jira Link: [DB-12989](https://yugabyte.atlassian.net/browse/DB-12989)
### Description

Please refer slack thread in JIRA

We have `test_cdc_with_snapshot_consistency` test which does below 

```

        1 multi table Bank workload, involving 5 tables. Transactions could happen between tables randomly.
        Create tables only first, both source and target
        Start Bank workload with 5 write threads, which inserts/distributes 1000 accounts to 5 tables. 200 each.
        In loop:
            Create CDC stream and deploy in initial_only
            Deploy sink connector
            Give max 30 minutes and check if it balances initially i.e. sum(balance) to reach expected value
            Start PG sample app to keep verifying sum(balance) via reads
            Delete source connector
            Delete sink connector
            Delete kafka topic
            Deploy source connector with consistency in 'never' mode
            Deploy sink connector  with consistency mode
            Keep verifying log_end_offset is increasing always
            Verify the streaming mode, consistency i.e. sum(balance) for 5 mins (i.e. via sample apps on PG sink)
            Delete source connector
            Delete sink connector
            Delete kafka topic
            Create sink target
``` 

In the step `Give max 30 minutes and check if it balances initially i.e. sum(balance) to reach expected value`, the test fails after some hours because its taking longer than 30 mins.

We have same run on 2.20.6 and 2.20.7, where its much smaller time.

![Profile (3)](https://github.com/user-attachments/assets/d367e5ab-7331-4a8a-8086-611d5d134319)

vs

![Profile (2)](https://github.com/user-attachments/assets/e79ec57c-8952-4406-8a70-94fe4c587a1c)

You can find both runs in JIRA.

### Source connector version

quay.io/yugabyte/debezium-connector:dz.1.9.5.yb.grpc.2024.1

### Connector configuration

```
add connector connector_name='yugabyte_connector0' stream_id='c38df7dfc3b7ffa28c4c2f51c95c6a5a' db_name='cdc_de184f' connector_host='172.151.25.155' table_list=['test_cdc_ddc036_1', 'test_cdc_ddc036_2', 'test_cdc_ddc036_3', 'test_cdc_ddc036_4', 'test_cdc_ddc036_5'] {'name': 'yugabyte_connector0', 'config': {'database.master.addresses': '172.151.20.137:7100,172.151.28.22:7100,172.151.24.91:7100', 'database.hostname': '172.151.20.137:5433,172.151.28.22:5433,172.151.24.91:5433', 'database.port': 5433, 'database.masterhost': '172.151.24.91', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_de184f', 'snapshot.mode': 'initial_only', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 1, 'topic.creation.default.replication.factor': '1', 'tasks.max': '1', 'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector', 'database.server.name': 'db_cdc', 'database.streamid': 'c38df7dfc3b7ffa28c4c2f51c95c6a5a', 'table.include.list': 'public.test_cdc_ddc036_1,public.test_cdc_ddc036_2,public.test_cdc_ddc036_3,public.test_cdc_ddc036_4,public.test_cdc_ddc036_5'}}
```

### YugabyteDB version

Starts from 2.23.0.0-b325. Backtraced to this commit after we ran for 16 hrs : https://github.com/yugabyte/yugabyte-db/commit/414a10a14fecdced87565713dec6e4f00298f8e7

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12989]: https://yugabyte.atlassian.net/browse/DB-12989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , There is a possibility that the change as part of https://github.com/yugabyte/yugabyte-db/issues/22227 would help with the performance of the happy path. Can you run the test with the diff associated with https://github.com/yugabyte/yugabyte-db/issues/22227 and get us the data point? cc @es1024

**Comment by shamanthchandra-yb** [comment]
@rthallamko3 in latest runs I see its working as expected and I don't see above behaviour. Commenting stress runs in JIRA.
