### ISSUE TITLE
Segmentation fault in TSAN test

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#241]
Reported by @rahuldesirazu.

Running 

./yb_build.sh tsan --cxx-test integration-tests_delete_table-test --gtest_filter FaultFlags/DeleteTableDeletedParamTest.TestRollForwardDelete/0 -n 10 --tp 2

produces a SIGSEGV error.

**Comment by rthallamko3** [comment]
Per [detective link](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=DeleteTableDeletedParamTest&fail_tag=all&name=TestRollForwardDelete&platform=linux), It doesn't seem to be a problem anymore.
