### ISSUE TITLE
 operation memory consumption (1073651421) has exceeded its limit (1073741824) or the limit of an ancestral tracker

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2412]
Saw this error on one of the stress clusters. We need to see why that operation used that memory.

E0914 05:30:07.968583 12058 process_context.cc:180] SQL Error: Execution Error. Write(tablet: 637f57984fb449bcbb891aee77c672af, num_ops: 500, num_attempts: 9, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 2780815.162s (passed: 65.301s): Remote error (yb/rpc/local_call.cc:96): Local call error
INSERT INTO batch_ts_metrics_raw (metric_id, ts, value) VALUES (:metric_id, :ts, :value);
       ^^^^
I0914 05:30:07.970216 15831 raft_consensus.cc:1743] T a7b72ef848ba4a93893af1fbd248cba0 P 110bfdd115f24969b9e3338cf3de50e1 [term 568 FOLLOWER]: Rejecting Update request from peer 1e23843b89c849b9a1c71580205d67d9 for term 568. Could not prepare a single operation due to: Service unavailable (yb/tablet/operations/operation_tracker.cc:155): Operation failed, tablet a7b72ef848ba4a93893af1fbd248cba0 operation memory consumption (1073651421) has exceeded its limit (1073741824) or the limit of an ancestral tracker
E0914 05:30:07.981568 12058 process_context.cc:180] SQL Error: Execution Error. Write(tablet: 637f57984fb449bcbb891aee77c672af, num_ops: 500, num_attempts: 9, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 2780815.162s (passed: 65.301s): Remote error (yb/rpc/local_call.cc:96): Local call error

**Comment by spolitov** [comment]
Here we have 2 long-running compactions (40+mins), that took all available compaction slots.
No other compactions could take place, so some tablets collected a lot of SST files and stopped applying write operations.
That resulted in an unlimited operation tracker memory consumption.

**Comment by kmuthukk** [comment]
hi @spolitov --

once we reach this limit, do we cleanly rate limit/reject new requests, and stay under soft memory limit (i.e. avoid OOMs), and recover when the compactions finish?

**Comment by spolitov** [comment]
No, it happens in the follower. Also, I don't think that it is a good idea to block writes to 40 minutes.
There are several issues (discussed with @mbautin):
1) Long-running compactions. Should be handled using preemption and dynamic priorities.
2) When follower stops to apply writes operations he could release operations from memory. Since they are already stored on the disk.

**Comment by mbautin** [comment]
Closing this as we now throttle write requests by rejecting writes at the leader based the Raft watermark of the number of SSTable files (c5def0b90973c8c26cb8c2aefb45d7f9189ea915). cc @spolitov
