### ISSUE TITLE
expand universe stuck w/ error "Cannot add replicas. Currently have a total overreplication of 1, when max allowed is 1"

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2419]
I0924 23:16:30.415344 31175 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
W0924 23:16:30.475926 28436 cluster_balance.cc:227] Skipping add replicas for f82ba4833ca84441a1e9c029cb8f6b16: Operation failed. Try again. (yb/master/cluster_balance.cc:496): Cannot add replicas. Currently have a total overreplication of 1, when max allowed is 1
W0924 23:16:30.476302 28436 cluster_balance.cc:227] Skipping add replicas for ac0fde3d26154bfeac8907db5e9d9333: Operation failed. Try again. (yb/master/cluster_balance.cc:496): Cannot add replicas. Currently have a total overreplication of 1, when max allowed is 1
W0924 23:16:30.476490 28436 cluster_balance.cc:227] Skipping add replicas for 1bb8fa98e52d4c03858c26db15d9a42c: Operation failed. Try again. (yb/master/cluster_balance.cc:496): Cannot add replicas. Currently have a total overreplication of 1, when max allowed is 1
W0924 23:16:30.476698 28436 cluster_balance.cc:227] Skipping add replicas for 4b16781ced584cd8b4ab3e9ba2615f1c: Operation failed. Try again. (yb/master/cluster_balance.cc:496): Cannot add replicas. Currently have a total overreplication of 1, when max allowed is 1
W0924 23:16:30.476940 28436 cluster_balance.cc:227] Skipping add replicas for 49f88693648d414ca916836624bcd675: Operation failed. Try again. (yb/master/cluster_balance.cc:496): Cannot add replicas. Currently have a total overreplication of 1, when max allowed is 1
I0924 23:16:30.517088 31174 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:30.618432 31176 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:30.719528 31173 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:30.820840 31175 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:30.922178 32067 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:31.023317 31174 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:31.124646 31173 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:31.226512 28500 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360
I0924 23:16:31.327718 31175 catalog_manager.cc:6196] Blacklisted count 360 in 353 tablets, across 3 servers, with initial load 360

**Comment by ddorian** [comment]
@rahuldesirazu this is docummented here: https://docs.yugabyte.com/latest/troubleshoot/nodes/trouble-common/#skipping-add-replicas

Should we close this ?

**Comment by rahuldesirazu** [comment]
Yes I believe this is fine to close.
