### ISSUE TITLE
[xCluster] yb-admin SetupUniverseReplication command should take in table name

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2421]
Jira Link: [DB-7175](https://yugabyte.atlassian.net/browse/DB-7175)
Now that yb-admin can work with table names for YSQL, we should change `SetupUniverseReplication` command to take in table names instead of table IDs.

[DB-7175]: https://yugabyte.atlassian.net/browse/DB-7175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ajcaldera1** [comment]
I think its important to distinguish between the different APIs in case of namespace/keyspace/table_name collisions between APIs. So I would propose that a qualifier be added in `setup_universe_replication` to distinguish the different types of objects being replicated.

Current form:
`yb-admin -master_addresses master1,master2,master3 setup_universe_replication <target_uuid> <target_master1,target_master2,target_master3> <replicate_target_tablet_list>`

We should leave this primitive in place but add to it a qualifier on the replicate_target_list: `ycql_table: keyspace.table_name`,`ycql_keyspace:keyspace_name`,`ysql_table:database.schema.table`,`ysql_schema:database.schema`,`ysql_database:database`

If the item does not have a qualifier, it should be processed as a tablet_id.

Note that until DDL can be processed by 2DC, only tables that currently exist in a given keyspace, schema, database will be processed. Future tables that are added to these spaces, will have to be processed by `alter_universe_replication` in #2051.
