### ISSUE TITLE
[YW] Yugaware should list all the nodes public IP information

### ISSUE THREAD

**Issue by lvchaw** [yugabyte/yugabyte-db#2430]
For now, it only has private IP.

![image](https://user-images.githubusercontent.com/20410734/65626951-54ac9700-df9c-11e9-8802-f65b5f8a06b3.png)

![image](https://user-images.githubusercontent.com/20410734/65626968-5c6c3b80-df9c-11e9-807c-fd6744f1091a.png)

**Comment by ramkumarvs** [comment]
@yb-andrew i think we have fixed this issue, can you verify and close.

**Comment by ddorian** [comment]
Confirm that it's fixed.
