### ISSUE TITLE
backup or snapshot of system tables should raise an error

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2432]

**Comment by bmatican** [comment]
@rao-vasireddy Is this still relevant? I think YW does not display PG system tables anymore, right?

**Comment by ajcaldera1** [comment]
I think it's still relevant because YW may not be in control of the backup / snapshot creation. Perhaps some tooling enhancement to identify catalog tables via `yb-admin` would be helpful.

**Comment by bmatican** [comment]
#5492 probably duplicates this and @ramsrivatsa is looking at that
