### ISSUE TITLE
Add the ability to collapse/expand groups in the tserver Memory Breakdown page

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#2433]
Jira Link: [DB-2131](https://yugabyte.atlassian.net/browse/DB-2131)
It would be very convenient to be able to collapse/expand nested groups like server, BlockBasedTable, etc:
![image (18)](https://user-images.githubusercontent.com/903044/65644708-adf8e280-dffd-11e9-906f-9e8fc49e8957.png)

**Comment by chinmay291** [comment]
This is how the current fix in review would look.

![Screenshot 2023-06-06 at 11 19 30 AM](https://github.com/yugabyte/yugabyte-db/assets/31536945/c26b4c84-82a1-4e59-a6ad-9001ff4a625b)
