### ISSUE TITLE
[DocDB] Load balancer should prioritize fixing the most under-replicated tablets first

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#24341]
Jira Link: [DB-13251](https://yugabyte.atlassian.net/browse/DB-13251)
### Description

In an RF5 cluster where some tablets have 3 peers and some have 4 peers, the load balancer should prioritize adding replicas to tablets with 3 peers before adding replicas tablets with 4 peers.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13251]: https://yugabyte.atlassian.net/browse/DB-13251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by acube123** [comment]
related https://github.com/yugabyte/yugabyte-db/issues/20263. May close it as a dup, if the fix addresses both.

**Comment by SrivastavaAnubhav** [comment]
Thanks Amit. Closing this one as a duplicate.
