### ISSUE TITLE
[DocDB] Advisory lock: Infrastructure to support advisory lock acquisition

### ISSUE THREAD

**Issue by Huqicheng** [yugabyte/yugabyte-db#24357]
Jira Link: [DB-13269](https://yugabyte.atlassian.net/browse/DB-13269)
### Description

#25127 implemented the creation of system table pg_advisory_locks.

This issue tracks the changes to:

1. Store the lock record in the system table when the advisory lock is acquired.
2. Support conflict resolution of advisory locks.

Releasing the locks at end of the transaction is relying on the existing transaction commit/rollback path.

### Issue Type

kind/new-feature

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13269]: https://yugabyte.atlassian.net/browse/DB-13269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
The tserver gflag `yb_enable_advisory_lock` can be used to enable the feature.
