### ISSUE TITLE
[DocDB] Reduce boilerplate for gflag validators

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#24368]
Jira Link: [DB-13280](https://yugabyte.atlassian.net/browse/DB-13280)
### Description

Code for validating gflag values is fairly verbose, e.g.
```
namespace {

bool RpcMaxMessageSizeValidator(const char* flag_name, uint64_t value) {
  // This validation depends on the value of: protobuf_message_total_bytes_limit.
  DELAY_FLAG_VALIDATION_ON_STARTUP(flag_name);

  if (value >= FLAGS_protobuf_message_total_bytes_limit) {
    LOG_FLAG_VALIDATION_ERROR(flag_name, value)
        << "Must be less than protobuf_message_total_bytes_limit "
        << FLAGS_protobuf_message_total_bytes_limit;
    return false;
  }

  return true;
}

} // namespace

DEFINE_validator(rpc_max_message_size, &RpcMaxMessageSizeValidator);
```
It's also fairly repetitive (e.g. flag A < flag B, flag > 0 checks are done in multiple places) and could be reduced.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13280]: https://yugabyte.atlassian.net/browse/DB-13280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Lets backport to 2024.2 as we plan to backport the CDC fix that needs this.
