### ISSUE TITLE
[docs] Broken link to docker quick start

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#2445]
On: https://docs.yugabyte.com/latest/deploy/docker/docker-compose/#2-initialize-the-apis
the quickstart link is broken.

**Comment by ddorian** [comment]
Probably should link to https://docs.yugabyte.com/latest/quick-start/explore-ysql/#docker ?

**Comment by ndeodhar** [comment]
This was fixed yesterday. Latest doc has the correct link: https://docs.yugabyte.com/latest/deploy/docker/docker-compose/#3-test-the-apis.
