### ISSUE TITLE
ysql version should match that of yugabytedb

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#2447]
Jira Link: [DB-2571](https://yugabyte.atlassian.net/browse/DB-2571)
In v2.0, the following is observed from `ysqlsh`. 

```
yugabyte=# select version();
select version();
                                                  version                                                   
------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.2-YB-2.0.0.0-b0 on x86_64-pc-linux-gnu, compiled by gcc (Homebrew gcc 5.5.0_4) 5.5.0, 64-bit
(1 row)
```

2 issues.
1. The above version string should not start with PostgreSQL and should start with YB.
2. The exact version of YB should be displayed. The version here is `2.0.0.0-b16`

So the correct representation would be `YB-2.0.0.0-b16`. If we want to also communicate the PostgreSQL version that is compatible with this version then the version string would be `YB-2.0.0.0-b16-PostgreSQL 11.2`

**Comment by ndeodhar** [comment]
There may be tools/client drivers that depend on "PostgreSQL" string from `select version()`. For example, I know that TablePlus uses it.
So, we need to do more investigation on compatibility before changing that.
