### ISSUE TITLE
TestLogCopySetsCloseTimestampInFooter unit test failing with high frequency

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#24518]
Jira Link: [DB-13553](https://yugabyte.atlassian.net/browse/DB-13553)
### Description

TabletSplitITest.TestLogCopySetsCloseTimestampInFooter starts failing recently on alma8-clang17-release-aarch64 [Analyze_trend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=TabletSplitITest&name=TestLogCopySetsCloseTimestampInFooter) with flakiness 

```
../../src/yb/integration-tests/tablet-split-itest.cc:966 Expected equality of these values:   has_replicated_entries     Which is: false   segment->footer().has_close_timestamp_micros()     Which is: true T d56728bc9fd04f1fa976653786bb78a1 P 745637836d2b45fbbd3344379de6bc09: Expected valid close timestamp for segment with replicated entries.



Expected equality of these values:
  has_replicated_entries
    Which is: false
  segment->footer().has_close_timestamp_micros()
    Which is: true
T d56728bc9fd04f1fa976653786bb78a1 P 745637836d2b45fbbd3344379de6bc09: Expected valid close timestamp for segment with replicated entries.

```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13553]: https://yugabyte.atlassian.net/browse/DB-13553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Backporting till 2024.2 might be sufficient.
