### ISSUE TITLE
[DocDB][Wait on Conflict] Unexpected resume_ht in conflict resolution error seen while updating a row

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#24556]
Jira Link: [DB-13592](https://yugabyte.atlassian.net/browse/DB-13592)
### Description

Version: **2.25.0.0-b90**
Logs: Added in Jira

One of the geo-partitioned test encountered the following issue while running contentious transaction.

**2024-10-21 12:49:30.989 UTC [74546] ERROR:  Unexpected resume_ht in conflict resolution: <min>**
2024-10-21 12:49:30.989 UTC [74546] STATEMENT:  UPDATE transactions SET val = 16 WHERE id='1' ;

Test details:
```
       (  1307.678s) Create universe rsak-isd14977-57b16900be-20241021-111946 : Success
	(    96.702s) Create database transactions_db : Success
	(   220.515s) Create tablespace, parent table and geo partitioned tables : Success
	(     2.431s) Verify cluster is load balanced : Success
	(     2.541s) Verify geo partitioned transaction tables are created automatically : Success
	(    16.738s) Insert rows into the table : Success
       
    Start a few threads to run parallel transactions and verify that the deadlock error occurs as expected.
	(   386.056s) Deadlock-1 encountered : Success
	(  1390.600s) Deadlock-2 encountered : Success
	(     0.000s) Deadlock-3 encountered : Success
	(   316.238s) Deadlock-4 encountered : Success
	(   807.416s) Deadlock-5 encountered : Success
	(   263.276s) Deadlock-6 encountered : Success
	(   206.166s) Start running contentious transactions with Read committed isolation level : >>> Integration Test Failed <<< 
Unexpected resume_ht in conflict resolution: <min>
```

Also saw the following health check errors
```

FailedSystemd unit preexec check
yb-master.service has no clock_sync script ExecStartPre
yb-tserver.service has no clock_sync script ExecStartPre
```
<img width="1608" alt="Screenshot 2024-10-22 at 5 28 39 PM" src="https://github.com/user-attachments/assets/768fdaa8-71a7-44de-ac31-080d101e3fd1">

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13592]: https://yugabyte.atlassian.net/browse/DB-13592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shishir2001-yb , lowering the priority to medium. Let us know if you are able to hit it on a build with Eric's recent fix for https://github.com/yugabyte/yugabyte-db/issues/21116

**Comment by rthallamko3** [comment]
Unable to repro after https://github.com/yugabyte/yugabyte-db/issues/21116. Closing it for now.
