### ISSUE TITLE
[YSQL][Query Diagnostics] Improve formatting of schema_details output

### ISSUE THREAD

**Issue by IshanChhangani** [yugabyte/yugabyte-db#24562]
Jira Link: [DB-13597](https://yugabyte.atlassian.net/browse/DB-13597)
### Description

The requirement is to make the formatting of schema_details.txt to be closer to ysqlsh. Sample output is available at `java/yb-pgsql/src/test/resources/expected/schema_details.out`

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13597]: https://yugabyte.atlassian.net/browse/DB-13597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment]
And address the multi-line string printing, e.g.:
```
|View Definition                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------+
| SELECT table_referenced_by_view.id,
    table_referenced_by_view.name
   FROM table_referenced_by_view
  WHERE table_referenced_by_view.id >= 0; |
```
