### ISSUE TITLE
Tserver unavailable due to soft memory limit

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#2458]
Jira Link: [DB-2539](https://yugabyte.atlassian.net/browse/DB-2539)
Seeing a lot of such messages on one of the nodes:
 I0926 03:54:54.280252 415972 tablet_service.cc:239] Rejecting Write request: Soft memory limit exceeded (at 88.60% of capacity), score: 0.79 [suppressed 66 similar messages]
client write ops dropped to 0 during the ~30 mins that the server was under this.

W0926 03:45:07.477324 413861 kernel_stack_watchdog.cc:139] Thread 179337 stuck at ../../src/yb/consensus/log.cc:283 for 3004ms:
 Kernel stack:
 (could not read kernel stack)
 User stack:
     @     0x7fe95793a11e  (unknown)
     @     0x7fe961f451eb  base::internal::SpinLockDelay()
     @     0x7fe961f450f4  SpinLock::SlowLock()
     @     0x7fe95d205b66  tcmalloc::CentralFreeList::InsertRange()
     @     0x7fe95d209ae5  tcmalloc::ThreadCache::ReleaseToCentralCache()
     @     0x7fe95d209e63  tcmalloc::ThreadCache::ListTooLong()
     @     0x7fe95f43d6c0  yb::docdb::KeyValueWriteBatchPB::~KeyValueWriteBatchPB()
     @     0x7fe95f43d79f  yb::docdb::KeyValueWriteBatchPB::~KeyValueWriteBatchPB()
     @     0x7fe95f671ff4  yb::tserver::WriteRequestPB::SharedDtor()
     @     0x7fe95f672071  yb::tserver::WriteRequestPB::~WriteRequestPB()
     @     0x7fe95f6721ff  yb::tserver::WriteRequestPB::~WriteRequestPB()
     @     0x7fe962acee83  yb::consensus::ReplicateMsg::SharedDtor()
     @     0x7fe962acef7d  yb::consensus::ReplicateMsg::~ReplicateMsg()
     @     0x7fe962acefcf  yb::consensus::ReplicateMsg::~ReplicateMsg()
     @     0x7fe96407668e  yb::consensus::LogCache::EvictSomeUnlocked()
     @     0x7fe964076a81  yb::consensus::LogCache::EvictThroughOp()

**Comment by amitanandaiyer** [comment]
![Screen Shot 2019-09-27 at 4 40 40 PM](https://user-images.githubusercontent.com/32495790/65807878-a5abbf00-e145-11e9-85f6-157fe7fcba76.png)
![Screen Shot 2019-09-27 at 4 36 58 PM](https://user-images.githubusercontent.com/32495790/65807879-a5abbf00-e145-11e9-9b2f-fa610dc1f402.png)
![Screen Shot 2019-09-27 at 4 36 44 PM](https://user-images.githubusercontent.com/32495790/65807880-a5abbf00-e145-11e9-8fcc-f2357430e5cb.png)

**Comment by amitanandaiyer** [comment]
Looking at the Peak Consumption, it looks like the Call/Inbound RPCs were consuming 36.2G 

The tablets collectively only used a peak of 7.31 G.

**Comment by amitanandaiyer** [comment]
@spolitov @kmuthukk  ^^

**Comment by amitanandaiyer** [comment]
> <@U1QNBKFHP> mem tracker htmls
<sub>[View in Slack](https://yugabyte.slack.com/archives/CN0T60H2R/p1569974548131400)</sub>

**Comment by rthallamko3** [comment]
@amitanandaiyer , Is this still an issue? Was this from a sample apps workload?
