### ISSUE TITLE
[DocDB] Remove protransform column of pg_proc from ysql migration script in pg 15 

### ISSUE THREAD

**Issue by yamen-haddad** [yugabyte/yugabyte-db#24593]
Jira Link: [DB-13631](https://yugabyte.atlassian.net/browse/DB-13631)
### Description

As Yugabyte codebase now uses Postgres 15, writing ysql migration scripts in pg15 has some differences to take into consideration the new pg_catalog schema as of pg version 15. One such pg_catalog table is `pg_proc`. For this table, the column `protransform` has been removed and a new row 'prosupport' has been added in pg 15.

`yb_database_clones` is the first internal function we added after the new upgrade to pg 15. However, the ysql migration script didn't take that into consideration. This should be fixed.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13631]: https://yugabyte.atlassian.net/browse/DB-13631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@yamen-haddad , Closing this out as it looks like the fix has landed. cc @lingamsandeep
