### ISSUE TITLE
TabletSplitITest.TestLogCopySetsCloseTimestampInFooter failing on alma8-clang17-release-aarch64 and alma8-clang17-release builds

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#24677]
### Description

TabletSplitITest.TestLogCopySetsCloseTimestampInFooter failing on alma8-clang17-release-aarch64 and alma8-clang17-release builds

#### ERROR:
```
../../src/yb/integration-tests/tablet-split-itest.cc:966 Expected equality of these values:   has_replicated_entries     Which is: false   segment->footer().has_close_timestamp_micros()     Which is: true T 50ede5a9a45f4c0b8d6050e5f6619438 P 92b1466a0cbf40febbe10ebfe837408b: Expected valid close timestamp for segment with replicated entries.


Expected equality of these values:
  has_replicated_entries
    Which is: false
  segment->footer().has_close_timestamp_micros()
    Which is: true
T 50ede5a9a45f4c0b8d6050e5f6619438 P 92b1466a0cbf40febbe10ebfe837408b: Expected valid close timestamp for segment with replicated entries.

```

[Analyze trends](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=TabletSplitITest&name=TestLogCopySetsCloseTimestampInFooter)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by rthallamko3** [comment]
DUP of https://github.com/yugabyte/yugabyte-db/issues/24518
