### ISSUE TITLE
RemoteBootstrapITest.IncompleteWALDownloadDoesntCauseCrash failing on alma8-clang17-tsan and alma8-clang17-asan	

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#24685]
Jira Link: [DB-13758](https://yugabyte.atlassian.net/browse/DB-13758)
### Description

RemoteBootstrapITest.IncompleteWALDownloadDoesntCauseCrash failing on alma8-clang17-tsan and alma8-clang17-asan	
probably after the [commit](https://github.com/yugabyte/yugabyte-db/commits/7ce6dab12a7fa1f421e35ea6847ac5cf038d759e)

[Analyze trend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=RemoteBootstrapITest&name=IncompleteWALDownloadDoesntCauseCrash)
#### Error:
```
../../src/yb/integration-tests/remote_bootstrap-itest.cc:301 Failed Bad status: Timed out (yb/util/backoff_waiter.cc:78): Operation 'Wait checkpoints empty' didn't complete within 29992ms Google Test trace: ../../src/yb/integration-tests/remote_bootstrap-itest.cc:282: Tablet: ca7c140c8bf34ea0904b6d0e1723ee2c ../../src/yb/integration-tests/remote_bootstrap-itest.cc:278: Data dir: /tmp/yb_test.tests-integration-tests__remote_bootstrap-itest___RemoteBootstrapITest.IncompleteWALDownloadDoesntCauseCrash.20241029013814608465.3063930831/remote_bootstrap-itest.RemoteBootstrapITest.IncompleteWALDownloadDoesntCauseCrash.1730165894880837-497333/minicluster-data/ts-2/yb-data/tserver ../../src/yb/integration-tests/remote_bootstrap-itest.cc:277: UUID: 2f1c3367395f4c03a81e1bf3fb41fd6b ../../src/yb/integration-tests/remote_bootstrap-itest.cc:276: Index: 1
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13758]: https://yugabyte.atlassian.net/browse/DB-13758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Resolved by #24638
