### ISSUE TITLE
[YSQL][Colocation] Underreplicated Tablets for Colocated Tables with Single Replica Tablespaces in RF=3 Cluster

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#24766]
Jira Link: [DB-13856](https://yugabyte.atlassian.net/browse/DB-13856)
### Description

Version: **2024.2.0.0-b116**

Currently, if we set up a cluster with a replication factor (RF) of 3 on 3 nodes and create tablespaces with num_replicas set to 1, any colocated partitioned tables created with these tablespaces fall into the **underreplicated category**. YBA detects this status via the endpoint:
`http://node:port/api/v1/tablet-under-replication`

**Note**: This issue doesn’t occur with normal partition tables on the same tablespace.

Also, if we create a universe with RF=3 on 9 nodes (3 nodes in each zone) and set tablespaces with num_replicas as 3, this setup appears to work fine.

```
CREATE TABLESPACE us_west_2a_tablespace WITH (
    replica_placement='{
        "num_replicas": 1,
        "placement_blocks": [
            {"cloud": "aws", "region": "us-west-2", "zone": "us-west-2a", "min_num_replicas": 1}
        ]
    }'
);

CREATE TABLESPACE eu_central_1a_tablespace WITH (
    replica_placement='{
        "num_replicas": 1,
        "placement_blocks": [
            {"cloud": "aws", "region": "eu-central-1", "zone": "eu-central-1a", "min_num_replicas": 1}
        ]
    }'
);

CREATE TABLESPACE ap_south_1a_tablespace WITH (
    replica_placement='{
        "num_replicas": 1,
        "placement_blocks": [
            {"cloud": "aws", "region": "ap-south-1", "zone": "ap-south-1a", "min_num_replicas": 1}
        ]
    }'
);

create table t(id int, region varchar, PRIMARY KEY(id, region)) partition by list(region);

create table t_0 partition of t(id, region) FOR VALUES IN ('US') TABLESPACE us_west_2a_tablespace;


create table t_1 partition of t(id, region) FOR VALUES IN ('EU') TABLESPACE eu_central_1a_tablespace;

create table t_2 partition of t(id, region) FOR VALUES IN ('IND') TABLESPACE ap_south_1a_tablespace;
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13856]: https://yugabyte.atlassian.net/browse/DB-13856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SrivastavaAnubhav** [comment]
Fixed by 24ed6701ec7b9d48b4bc605cd684185f92caf3e2
