### ISSUE TITLE
Unit Test SnapshotTest.HideTablesCoveredBySnapshot failing across the builds

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#24772]
Jira Link: [DB-13862](https://yugabyte.atlassian.net/browse/DB-13862)
### Description

Test HideTablesCoveredBySnapshot failing with high flakiness [Analyze trend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=SnapshotTest&name=HideTablesCoveredBySnapshot) Across the builds

#### Error:
```
../../src/yb/integration-tests/snapshot-test.cc:555 Failed Bad status: Illegal state (yb/integration-tests/snapshot-test.cc:440): Tablet 523034277d1e45178a9f6a2c5a2e09e1 of table d9578c3c6d634532881f639a9039f8d8 not hidden on tserver

```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13862]: https://yugabyte.atlassian.net/browse/DB-13862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@druzac , The test flakiness could be related to the commit - https://github.com/yugabyte/yugabyte-db/commit/286687127fadfbcb7b8ef9310698e087c6b13289 , Can you take a look?

**Comment by druzac** [comment]
Yeah, this looks like a regression. Taking a look.
