### ISSUE TITLE
Seeing lots of Blocked reactor thread in hmget/hmset workload repro cluster.

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#248]
Jira Link: [DB-5939](https://yugabyte.atlassian.net/browse/DB-5939)
Reported by @amitanandaiyer.

W0218 03:29:54.922190 17703 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 3 } , state=FINISHED_SUCCESS. blocked reactor thread for 85638.8us
W0218 03:29:55.548702 17698 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 1 } , state=FINISHED_SUCCESS. blocked reactor thread for 47721.3us
W0218 03:29:55.793146 17698 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 1 } , state=FINISHED_SUCCESS. blocked reactor thread for 63806.1us
W0218 03:29:55.989804 17698 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 1 } , state=FINISHED_SUCCESS. blocked reactor thread for 45961.2us
W0218 03:29:56.801096 17699 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 2 } , state=FINISHED_SUCCESS. blocked reactor thread for 61071.4us
W0218 03:29:57.810474 17699 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 2 } , state=FINISHED_SUCCESS. blocked reactor thread for 53034.2us
W0218 03:29:57.982434 17698 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 1 } , state=FINISHED_SUCCESS. blocked reactor thread for 46277.2us
W0218 03:30:03.658303 17693 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 0 } , state=FINISHED_SUCCESS. blocked reactor thread for 56029.5us
W0218 03:30:04.092541 17703 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 3 } , state=FINISHED_SUCCESS. blocked reactor thread for 49053.1us
W0218 03:30:07.274572 17699 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 2 } , state=FINISHED_SUCCESS. blocked reactor thread for 49668us
W0218 03:30:07.482434 17698 outbound_call.cc:340] RPC callback for RPC call yb.tserver.TabletServerService.Read -> { remote: <some_ip_address>:9100 idx: 1 } , state=FINISHED_SUCCESS. blocked reactor thread for 63506us

[DB-5939]: https://yugabyte.atlassian.net/browse/DB-5939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@amitanandaiyer , Resolving old bugs that look stale. Let me know if we have a concrete repro.
