### ISSUE TITLE
[CDCSDK] Data loss observed on CDC run on 2.23.1.0-b217 (gRPC)

### ISSUE THREAD

**Issue by ShikharSahay** [yugabyte/yugabyte-db#24812]
Jira Link: [DB-13918](https://yugabyte.atlassian.net/browse/DB-13918)
### Description

Test `test_cdc_lru_snapshot_master` on version `2.23.1.0-b217` failed due to data loss issue. 
Stress run - http://stress.dev.yugabyte.com/stress_test/6a256797-9a58-4722-b395-803c074d9c55
Slack link - https://yugabyte.slack.com/archives/C03H4D4EVC6/p1730871899786119

### Source connector version

quay.io/yugabyte/debezium-connector:dz.1.9.5.yb.grpc.2024.1

### Connector configuration

`add connector connector_name='ybconnector_cdc_f12e78_test_cdc_8c3cdb' stream_id='b933b512c36df2953f46b83e53f8c1bd' db_name='cdc_f12e78' connector_host='172.151.19.15' table_list=['test_cdc_8c3cdb'] {'name': 'ybconnector_cdc_f12e78_test_cdc_8c3cdb', 'config': {'database.master.addresses': '172.151.28.229:7100,172.151.31.38:7100,172.151.18.231:7100', 'database.hostname': '172.151.28.229:5433,172.151.31.38:5433,172.151.18.231:5433', 'database.port': 5433, 'database.masterhost': '172.151.31.38', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_f12e78', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector', 'database.server.name': 'ybconnector_cdc_f12e78_test_cdc_8c3cdb', 'database.streamid': 'b933b512c36df2953f46b83e53f8c1bd', 'table.include.list': 'public.test_cdc_8c3cdb', 'database.sslrootcert': '/kafka/ca.crt'}}`

### YugabyteDB version

2.23.1.0-b217

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13918]: https://yugabyte.atlassian.net/browse/DB-13918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Commit 6acbaf12 addresses this issue. cc @es1024
