### ISSUE TITLE
[YSQL] Key is not tablet tombstone error occurs in tables with rows >= 100000 upon select query (order by id)

### ISSUE THREAD

**Issue by dhruva4869** [yugabyte/yugabyte-db#24824]
Jira Link: [DB-13928](https://yugabyte.atlassian.net/browse/DB-13928)
### Description

**Description**
Version: 2.25.0.0-b91
Steps:
1. Create database and Create table with rows >= 100000
2. Make table with primary keys ASC
3. Load data
4. Do select query with order by id DESC

Observed Error:
`ERROR:  Key 072CDC47C0006B40BF9736686584C894C621 is not table tombstone key.`

Steps:
Create required table with load data
```
CREATE TABLE customer_accounts (
    account_id bigint,
    customer_id bigint,
    account_balance bigint,
    account_number bigint,
    account_type varchar(20),
    currency varchar(5),
    status varchar(10),
    country varchar(20),
    created_at bigint,
    updated_at bigint,
    PRIMARY KEY(customer_id ASC, account_id ASC)
);
INSERT INTO customer_accounts (account_id, customer_id, account_balance, account_number, 
                               account_type, currency, status, country, created_at, updated_at)
SELECT 
    i,                            
    i,                       
    i * 1000,                     
    i * 100000::bigint,           
    CASE WHEN i % 2 = 0 THEN 'Savings' ELSE 'Checking' END,  
    CASE WHEN i % 3 = 0 THEN 'USD' ELSE 'EUR' END,  
    CASE WHEN i % 5 = 0 THEN 'Active' ELSE 'Inactive' END,  
    'Country_' || (i % 10),       
    i * 10000::bigint,            
    (i * 10000 + 1000)::bigint    
FROM generate_series(1, 100000) AS i;  
```
Query giving error:
```
EXPLAIN ANALYZE SELECT account_id FROM customer_accounts
WHERE account_id > 1 ORDER BY customer_id DESC;
```
Query that passes:
```
EXPLAIN ANALYZE SELECT account_id FROM customer_accounts
WHERE account_id > 1 ORDER BY customer_id DESC LIMIT 10000;
```

**Other observations**
Initially was facing this while testing fast backward scan, but then observed the same error with fast_backward_scan turned off. After talking with @arybochkin he could reproduce same issue on the commit before the fast_backward_scan commit. This means that this error is unrelated to fast backward scan.

Also do not get same error with 99999 rows but get with 100000 rows.
Also do not get error when I LIMIT the select query.
Details with queries on JIRA.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13928]: https://yugabyte.atlassian.net/browse/DB-13928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Per @dhruva4869 , This is reproducible in 2024.1.3.0-b105 and v2.20.0.0-b76 as well.
