### ISSUE TITLE
[DocDB] The latency to update rows on colocated tables is higher than hash partitioned tables. 

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#24838]
Jira Link: [DB-13948](https://yugabyte.atlassian.net/browse/DB-13948)
### Description

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/7c40f391-559e-4dad-aced-60bc39b3ae2a">

Below are some of high level observation post comparing the flamegraphs for updating 1M rows from hash and colocated tables:

- In colocated tables we are spending lot more time in below stacks:
  - `yb::docdb::DocRowwiseIteratorBase::GetTableTombstoneTime`
  - `yb::docdb::DocRowwiseIterator::FetchNextImpl<yb::dockv::PgTableRow*>`
- Also in hash partitioned tables `yb::docdb::(anonymous namespace)::FilteringIterator::FetchTuple` is called from `yb::docdb::PgsqlReadOperation::ExecuteBatchKeys` where as in colocated it is called from `yb::docdb::(anonymous namespace)::FetchTableRow`

[Perf flamegraph for updating 1M rows on hash partitioned tables](https://drive.google.com/file/d/1p3vaepoGMU_WHdMNFi0_zw-O9eNGNPja/view?usp=sharing)
hnode2.svg 
![hnode2](https://github.com/user-attachments/assets/dc3e4cc1-edec-4e79-80ce-92380643a174)

[Perf flamegraph for updating 1M rows on colocated tables](https://drive.google.com/file/d/12imE3Ks6SgOJLsmh-FwHt0Y5M0iygUC0/view?usp=drive_link)
node2.svg
![node2](https://github.com/user-attachments/assets/11599075-6bcc-444d-96a5-87fb99742201)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13948]: https://yugabyte.atlassian.net/browse/DB-13948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
This is being addressed by #21561 . Closing this as duplicate for now.
