### ISSUE TITLE
[YSQL] Use default db as yugabyte irrespective of user name

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2484]
If I connect to yugabyteDB via ysqlsh using a user name that's not `yugabyte`, I see this error:
```
13:40 $ ./bin/ysqlsh  -U neha
ysqlsh: FATAL:  database "neha" does not exist
```
Looks like it's using the user name as the default DB name. We should change this to always use yugabyte as the default database.

**Comment by manhhiep92** [comment]
Hi @ndeodhar, I just opened a PR to fix this issue. Can you help to take a look? Thanks!
