### ISSUE TITLE
DISCARD ALL Not implemented 

### ISSUE THREAD

**Issue by msfeghouli** [yugabyte/yugabyte-db#2491]
When i tried to use application framework using psycopg2 , an issue arise on the connection cnx reset fonction , telling that 
DISCARD ALL Not implemented yet 

psycopg2.NotSupportedError: DISCARD not supported yet
LINE 1: DISCARD ALL
 
best regards

**Comment by ndeodhar** [comment]
Hi @msfeghouli, can you try the workaround suggested in #1512? Specifically,
```
I believe it's related to how Npgsql attempts to clear session variables: https://www.npgsql.org/doc/performance.html#pooled-connection-reset

You can disable it by adding the following to your connection string: No Reset On Close=true;
```
