### ISSUE TITLE
[Docs] Remove 9000 port from --yba_url of provision_instance.py

### ISSUE THREAD

**Issue by nkhogen** [yugabyte/yugabyte-db#24971]
### Description

The doc says 

`--yba_url - enter the URL of the machine where you are running YugabyteDB Anywhere, with port 9000. For example, https://ybahost.company.com:9000. The node must be able to communicate with YugabyteDB Anywhere at this address.`

It should simply be
`--yba_url - enter the URL of the machine where you are running YugabyteDB Anywhere. For example, https://ybahost.company.com. The node must be able to communicate with YugabyteDB Anywhere at this address.`

9000 is for local development testing and does not apply to prod environment.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by aishwarya24** [comment]
This ticket is created in JIRA - https://yugabyte.atlassian.net/browse/DOC-558. So closing the issue and it will be addressed via JIRA.
