### ISSUE TITLE
Fix node blacklist sequence as we keep the tserver up during "Remove Node" operation in YW

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2499]
If we do a "Remove Node" on a 3 node RF-3 cluster, get_load_move_completion keeps returning 0 and master leader log has lines like

"I1002 23:28:22.393823 25884 catalog_manager.cc:6172] Blacklisted count 12 in 29 tablets, across 1 servers, with initial load 12
I1002 23:28:22.509527 26115 catalog_manager.cc:6172] Blacklisted count 12 in 29 tablets, across 1 servers, with initial load 12 "

I guess the "Remove Node" task finished in the past as we were killing the tserver. With the tserver staying up now, master leader needs to figure out what tasks need to be performed in terms of leader movement and tablet movement for the node blacklist. 

Right now Remove Node is getting stuck in YW. One workaround is to stop the tserver and in 5 mins the YW task will complete.

**Comment by rahuldesirazu** [comment]
Another option is to use IsLoadBalanceIdle as part of blacklist definition, so if we have Rf=3 3 node case, the load balancer cant do anything and returns.

**Comment by bmatican** [comment]
@rao-vasireddy If I recall, this used to be gated in YW, so it would not wait, when we are at such edge conditions cc @Arnav15 

Also wasn't sure about the sequencing on this part:
> Right now Remove Node is getting stuck in YW. One workaround is to stop the tserver and in 5 mins the YW task will complete.

However, I also like @rahuldesirazu 's suggestion, if we could enhance the current query API to maybe return status / error codes and YW could do something based on those. But this would have to be done a bit careful, as newer YWs might not get these codes from older YBs.

**Comment by bmatican** [comment]
@Arnav15 I think you fixed this in YW, right? Can you confirm that and maybe close out this task too, thanks.

**Comment by Arnav15** [comment]
Fixed by commit: https://github.com/yugabyte/yugabyte-db/commit/927393334310a2f71fc98804df5b736e64f10193#diff-924ea6ba3555fbd8f890b6e3b5778eaf
