### ISSUE TITLE
Have number of leaders per tablet server on /tablet-servers page

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#250]
Reported by @pritamdamania87.

Right now the /tablet-servers endpoint has load in terms of number of tablets. It would be nice to also add the number of leaders per tablet server there as well so its easy to know that after an admin operation, the cluster has been rebalanced correctly.

I was playing around with a cluster and took down a node and brought it back up and although the number of tablets were equal on all nodes the read and write ops/s per node took a while to be spread evenly. Just thought it would be nice to have number of leaders per tablet server as well on this page.

**Comment by bmatican** [comment]
Duplicated and fixed by #412 by @vitsai .
