### ISSUE TITLE
[YSQL] flaky test TestPgDdlConcurrency#testModifiedTableWrite

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#25062]
Jira Link: [DB-14193](https://yugabyte.atlassian.net/browse/DB-14193)
### Description

example: `./yb_build.sh fastdebug --gcc11 --java-test 'org.yb.pgsql.TestPgDdlConcurrency#testModifiedTableWrite'`

This Java test is flaky on many build types alma8-gcc11-fastdebug, alma8-clang17-tsan, alma8-clang17-release, mac13-clang-release-arm64 despite 25dcd64c657d80c7e1cde5dbdb66f134f1a01e04 closing issue #8096.  See also related issue #25053.

Example failures:

fastdebug/release:

```
02:51:37.088 (Thread-23) [ERROR - org.yb.pgsql.TestPgDdlConcurrency.lambda$testModifiedTableWrite$1(TestPgDdlConcurrency.java:102)] Unexpected exception
com.yugabyte.util.PSQLException: ERROR: ybctid DocKey([], [16450]) not found in indexed table. index table id is 000034cb000030008001000000000a60
```

tsan:

```
02:34:35.218 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:41)] Assertion error:
java.lang.AssertionError: Expected 0 to be greater than 0
```

Internal link: https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=org.yb.pgsql.TestPgDdlConcurrency&name=testModifiedTableWrite

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14193]: https://yugabyte.atlassian.net/browse/DB-14193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Could be resolved by [25072](https://github.com/yugabyte/yugabyte-db/issues/25072)

**Comment by rthallamko3** [comment]
Should be resolved by [25072](https://github.com/yugabyte/yugabyte-db/issues/25072)
