### ISSUE TITLE
Enable the flag --use_cassandra_authentication in master as well as in Yugabyte.

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#251]
Reported by @ayushsengupta1991.

Currently when we pass down the --use_cassandra_authentication flag in master, the server just crashes. This is not the correct behavior and it would be great to have this fixed.

**Comment by bmatican** [comment]
Closing this for now, some of our flags are really cluster level settings and we should move towards something like https://github.com/yugabyte/yugabyte-db/issues/5985
