### ISSUE TITLE
We need a mechanism to query the database, schema and table size via SQL

### ISSUE THREAD

**Issue by YourTechBud** [yugabyte/yugabyte-db#2512]
Jira Link: [DB-1693](https://yugabyte.atlassian.net/browse/DB-1693)
Currently there is no way to retrieve the raw data size via a SQL query. Postgres has a bunch of functions which we can use to get this info.

It would be great if we could get a SQL based API to retrieve this information. While a REST endpoint will also do the trick, a SQL api would be way more convenient.

**Comment by sushantrmishra** [comment]
We have added the size of the tables in the output of \d+ .

GH issue: https://github.com/yugabyte/yugabyte-db/issues/11131

Please reopen the issue if this does not satisfy the requirement.
