### ISSUE TITLE
[YSQL] Enable create or replace trigger 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#25128]
Jira Link: [DB-14278](https://yugabyte.atlassian.net/browse/DB-14278)
### Description

Vanilla PostgreSQL allows  CREATE OR REPLACE TRIGGER which will either create a new trigger, or replace an existing trigger.
Adding the same functionality in YB.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14278]: https://yugabyte.atlassian.net/browse/DB-14278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arpang** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/24941
