### ISSUE TITLE
[DocDB] Failing tests due to a deadlock because of Messenger::lock_

### ISSUE THREAD

**Issue by abhinab-yb** [yugabyte/yugabyte-db#25132]
Jira Link: [DB-14282](https://yugabyte.atlassian.net/browse/DB-14282)
### Description

There is a possible deadlock between Messenger::TEST_ShouldArtificiallyRejectOutgoingCallsTo and Messenger::DumpRunningRpcs on the Messenger::lock_

The sequence of events for the deadlock are -
- RPC X is being processed by a reactor thread Y
- ASH collector tries to fetch tserver wait events, which calls DumpRunningRpcs
- DumpRunningRpcs takes the lock and schedules tasks on each reactor and waits until they are done
- Reactor thread Y eventually calls TEST_ShouldArtificiallyRejectOutgoingCallsTo
- TEST_ShouldArtificiallyRejectOutgoingCallsTo waits for the lock which is taken by DumpRunningRpcs
- DumpRunningRpcs waits for reactor thread Y to finish the task so it can release the lock and return

ASH was enabled by default recently (85247b4813553921db6ec2faf7154247e17873e8) which calls the DumpRunningRpcs code every second, that's why these tests have started to fail more now

Failing tests (not an exhaustive list) -
- [PgAnalyzeReadTimeTest.InsertRowsConcurrentlyWithAnalyze](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=PgAnalyzeReadTimeTest&name=InsertRowsConcurrentlyWithAnalyze)
- [PgMiniTest.TablegroupCompactionWithRestart](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=PgMiniTest&name=TablegroupCompactionWithRestart)
- [GeoTransactionsPromotionTest.TestOldRegionFailBeforeRPCSend](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=GeoTransactionsPromotionTest&name=TestOldRegionFailBeforeRPCSend)
- [GeoTransactionsPromotionTest.TestOldRegionExpiredAndRestarted](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=GeoTransactionsPromotionTest&name=TestOldRegionExpiredAndRestarted)
- [GeoTransactionsPromotionTest.TestRestartAfterCommit](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=GeoTransactionsPromotionTest&name=TestRestartAfterCommit)
- [GeoTransactionsPromotionTest.TestOldRegionFailAfterRPCBeforeAbortSentEarly](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=GeoTransactionsPromotionTest&name=TestOldRegionFailAfterRPCBeforeAbortSentEarly)
- [GeoTransactionsPromotionTest.TestOldRegionFailBeforeAbortSentEarly](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=GeoTransactionsPromotionTest&name=TestOldRegionFailBeforeAbortSentEarly)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14282]: https://yugabyte.atlassian.net/browse/DB-14282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by spolitov** [comment]
There is already fix in review: https://phorge.dev.yugabyte.com/D40377

**Comment by abhinab-yb** [comment]
Closing as duplicate of #25135
