### ISSUE TITLE
[DocDB] Failed to start thread tserver FATAL in long running tests in master branch

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#25146]
Jira Link: [DB-14306](https://yugabyte.atlassian.net/browse/DB-14306)
### Description

Similar to the behaviot in https://github.com/yugabyte/yugabyte-db/issues/24841, We observe similar behavior in 2024.2 branch, but it is much less thread leakage. (~5000 per 3 hours)

Number of threads in latest master build:
![Uploading Screenshot 2024-12-02 at 1.26.05 PM.png…]()

2.20.8 version in same test e.g.
![Screenshot 2024-12-02 at 1 37 36 PM](https://github.com/user-attachments/assets/da613b16-b309-4da3-b6e2-ae84bba15b58)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14306]: https://yugabyte.atlassian.net/browse/DB-14306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
There seems be an increase in the SharedExchange threads (leak of some sort). 
<img width="425" alt="Screenshot 2024-12-03 at 2 50 09 PM" src="https://github.com/user-attachments/assets/42f84e50-0943-4e31-a01c-7fd443dcc84f">

cc @spolitov

**Comment by rthallamko3** [comment]
Reactivating for 2.25 backport.
