### ISSUE TITLE
[DocDB] Implement tooling to report tasks that blocks reactor for a long time

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#25180]
Jira Link: [DB-14350](https://yugabyte.atlassian.net/browse/DB-14350)
### Description

It is critical to avoid running long tasks in Reactor threads, otherwise all network traffic that goes via this reactor could be blocked.
Need a way to detect such long running tasks.

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14350]: https://yugabyte.atlassian.net/browse/DB-14350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Reactivating for 2024.2 backport.
