### ISSUE TITLE
Support compiling YB v2.0 for arm64 arch

### ISSUE THREAD

**Issue by giminni** [yugabyte/yugabyte-db#2519]
@mbautin I am trying to compile YB v2.0 natively on an arm64 based single board computer.

```bash
$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1296.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

```bash
$ uname -a
Linux bms128svrp01 4.4.132-powder-rockchip-ayufan-g #1 SMP Wed Aug 1 07:29:55 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```
```bash
$ dpkg -l | grep -E "4.4.132|gcc-7|g\+\+-7|cpp-7|m4|python2|make|automake|autoconf|bison|ccache|libtool|maven|jdk|uuid|libbz|libreadline|ninja|flex|zlib" | grep -vE "xxd|flash" | awk '{print $2,$3}'
autoconf 2.69-11
automake 1:1.15.1-3ubuntu2
bison 2:3.0.4.dfsg-1build1
ccache 3.4.1-1
cmake 3.10.2-1ubuntu2.18.04.1
cmake-data 3.10.2-1ubuntu2.18.04.1
cpp-7 7.4.0-1ubuntu1~18.04.1
flex 2.6.4-6
g++-7 7.4.0-1ubuntu1~18.04.1
gcc-7 7.4.0-1ubuntu1~18.04.1
gcc-7-base:arm64 7.4.0-1ubuntu1~18.04.1
jq 1.5+dfsg-2
libbison-dev:arm64 2:3.0.4.dfsg-1build1
libbz2-1.0:arm64 1.0.6-8.1ubuntu0.2
libbz2-dev:arm64 1.0.6-8.1ubuntu0.2
libgcc-7-dev:arm64 7.4.0-1ubuntu1~18.04.1
libjq1:arm64 1.5+dfsg-2
libltdl7:arm64 2.4.6-2
libmaven-parent-java 31-2~18.04
libmaven-resolver-java 1.3.1-1~18.04
libmaven-shared-utils-java 3.3.0-1~18.04
libmaven3-core-java 3.6.0-1~18.04.1
libpython2.7:arm64 2.7.15-4ubuntu4~18.04.1
libpython2.7-dev:arm64 2.7.15-4ubuntu4~18.04.1
libpython2.7-minimal:arm64 2.7.15-4ubuntu4~18.04.1
libpython2.7-stdlib:arm64 2.7.15-4ubuntu4~18.04.1
libreadline-dev:arm64 7.0-3
libreadline6:arm64 6.3-8ubuntu2
libreadline7:arm64 7.0-3
libtool 2.4.6-2
libuuid1:arm64 2.31.1-0.4ubuntu3.4
linux-firmware-image-4.4.132-powder-rockchip-ayufan-g 4.4.132-powder-rockchip-ayufan
linux-headers-4.4.132-powder-rockchip-ayufan-g 4.4.132-powder-rockchip-ayufan
linux-image-4.4.132-powder-rockchip-ayufan-g 4.4.132-powder-rockchip-ayufan
m4 1.4.18-1
make 4.1-9.1ubuntu1
makedev 2.3.1-93ubuntu2
maven 3.6.0-1~18.04.1
ninja-build 1.8.2-1
openjdk-11-jre-headless:arm64 11.0.4+11-1ubuntu2~18.04.3
python2.7 2.7.15-4ubuntu4~18.04.1
python2.7-dev 2.7.15-4ubuntu4~18.04.1
python2.7-minimal 2.7.15-4ubuntu4~18.04.1
uuid-dev:arm64 2.31.1-0.4ubuntu3.4
uuid-runtime 2.31.1-0.4ubuntu3.3
zlib1g:arm64 1:1.2.11.dfsg-0ubuntu2
zlib1g-dev:arm64 1:1.2.11.dfsg-0ubuntu2
```

Here my issues and corrections:

1) I changed the library libunwind1.1a to libunwind1.3.1 because the ELF target was not recognis
ed (See below)

Here the emitted error:
`[libunwind (common)] checking for ELF helper width... configure: error: Unknown ELF target: aarch64`

2) Stuck compiling crc-util for arm64 arch
- Removed -msse2 while not supported on arm64 arch
- Explicit setting of march by adding -march=armv8-a+crypto+crc -mtune=cortex-a53 -Wno-error=unused-function tuned for cortex-a53 SOCs

Here the emitted error:
`[crcutil (uninstrumented)] g++: error: unrecognized command line option ‘-mcrc32’; did you mean ‘-march=’?`

Here the library config flags:
`-DCRCUTIL_USE_MM_CRC32=1 -Wall -Icode -Iexamples -Itests -march=armv8-a+crypto+crc -mtune=cortex-a53 -Wno-error=unused-function -O3 -mcrc32`

How can I patch `crcutil-440ba7babeff77ffad992df3a10c767f184e946e` ?

Thx for support

**Comment by ddorian** [comment]
Hi @giminni  we haven’t tested or even tried to build yugabyteDB on ARM yet and this is not in our nearest roadmap. It might require non-trivial work to do in order to build all the dependencies and yugabyteDB itself on ARM.

**Comment by giminni** [comment]
@ddorian is there someone that can help on getting it compiled on ARM?

**Comment by mbautin** [comment]
Hi @giminni, even though compiling on ARM is something we have not explored ourselves, here's how you can supply a custom version of a third-party dependency for your YugabyteDB build. E.g. for crcutil there is a build file like this: https://github.com/yugabyte/yugabyte-db/blob/master/thirdparty/build_definitions/crcutil.py
You could fork the crcutil project on GitHub, push the changes that you need, and change the URL prefix in crcutil.py the way it's done in e.g. the llvm dependency: https://github.com/yugabyte/yugabyte-db/blob/master/thirdparty/build_definitions/llvm.py

**Comment by giminni** [comment]
Could successful find a way to compile `crcutil-440ba7babeff77ffad992df3a10c767f184e946e` by removing example and test builds by heavily tweaking autogen.sh

```bash
$ ls -las thirdparty/installed/uninstrumented/lib/libcrc* | awk '{print $10,$11,$12}'
thirdparty/installed/uninstrumented/lib/libcrcutil.a
thirdparty/installed/uninstrumented/lib/libcrcutil.la
thirdparty/installed/uninstrumented/lib/libcrcutil.so -> libcrcutil.so.0.0.0
thirdparty/installed/uninstrumented/lib/libcrcutil.so.0 -> libcrcutil.so.0.0.0
thirdparty/installed/uninstrumented/lib/libcrcutil.so.0.0.0
```

The linker is now stuck at `-- Could NOT find UNWIND (missing: UNWIND_SHARED_ARCH_LIB UNWIND_STATIC_ARCH_LIB)`

Has someone a hint for solving this?

**Comment by giminni** [comment]
Could successful find a way to proceed by 
- adding `aarch64` for LIBUNWIND_ARCH
- fixing two bugs by adding the corresponding dynamic and static lib suffixes .so and .a

Now next problem at 
```bash
-- The following ICU libraries were not found:
--   i18n (required)
--   uc (required)
```
How to fix this?

**Comment by giminni** [comment]
Solved by installing `libicu-dev`

Now I guess thirdparty libs are all compiled

Compilation is stuck now at
`FAILED: src/yb/gutil/CMakeFiles/gutil.dir/cpu.cc.o`

Guess the CMakeList.txt definitions must be adapted to aarch64, any idea on that?

**Comment by giminni** [comment]
Analyzed the above error lend to

```bash
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/yb/gutil/cpu.cc:288:4: error: #error unknown architecture
   #error unknown architecture
    ^~~~~
```

Looking deeper I found:

```bash
src/yb/gutil/atomicops.h:102:2: error: #error You need to implement atomic operations for this architecture
 #error You need to implement atomic operations for this architecture
  ^~~~~
```
That means I need to define atomic operations creating Atomic32, Atomic64 structs.

Without help I cannot continue, because I don't know how to build this structs

**Comment by mbautin** [comment]
Hi @giminni, `gutil/atomicops.h` is a legacy header containing Google's implementations of atomic operations that could be implemented using the C++ standard library atomic operations from the `<atomic>` header. I guess we could create a header `yb/gutil/atomicops-internals-std-atomic.h` that could use `std::atomic` to implement operations that were previously implemented using platform-specific assembly instructions:

```
inline Atomic32 NoBarrier_CompareAndSwap(volatile Atomic32* ptr,
                                         Atomic32 old_value,
                                         Atomic32 new_value) {
  reinterpret_cast<std::atomic<int32_t>*>(ptr)->compare_exchange_strong(
    old_value, new_value);
  return old_value;
}
```

Then we could include this header in case we don't find the matching architecture (although in theory it should also work for any architecture).

**Comment by giminni** [comment]
@mbautin thx for clarification.
1) I solved the missing aarch64 definition in cpu.h, cpu.cc and arm_instruction_set_select.h from a newer gperftools implementation
2) Added in atomicops.h a define __aarch64__ and let gcc handle the atomic operation with a new file called "yb/gutil/atomicops-internals-gcc.h"

```c
inline Atomic32 NoBarrier_CompareAndSwap(volatile Atomic32* ptr,
                                         Atomic32 old_value,
                                         Atomic32 new_value) {
  Atomic32 prev_value = old_value;
  __atomic_compare_exchange_n(ptr, &prev_value, new_value,
          0, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
  return prev_value;
}
``` 
3) Added cycleclock for ARMV8 in cycleclock-inl.h

```c
// ----------------------------------------------------------------
#elif defined(__aarch64__)
  // System timer of ARMv8 runs at a different frequency than the CPU's.
  // The frequency is fixed, typically in the range 1-50MHz.  It can be
  // read at CNTFRQ special register.  We assume the OS has set up
  // the virtual timer properly.
inline int64 CycleClock::Now() {
  int64 virtual_timer_value;

  asm volatile("mrs %0, cntvct_el0" : "=r"(virtual_timer_value));

  return virtual_timer_value;
}
```

Still a lot of errors next stop in spinlock_internal.cc

```c
In file included from src/yb/gutil/spinlock_internal.cc:67:0:
src/yb/gutil/spinlock_linux-inl.h: In constructor ‘{anonymous}::InitModule::InitModule()’:
src/yb/gutil/spinlock_linux-inl.h:77:9: error: ‘sys_futex’ was not declared in this scope
         sys_futex(&x, FUTEX_WAKE | futex_private_flag, 1, 0) < 0) {
         ^~~~~~~~~
src/yb/gutil/spinlock_linux-inl.h:77:9: note: suggested alternative: ‘have_futex’
         sys_futex(&x, FUTEX_WAKE | futex_private_flag, 1, 0) < 0) {
         ^~~~~~~~~
         have_futex
src/yb/gutil/spinlock_linux-inl.h: In function ‘void base::internal::SpinLockDelay(volatile Atomic32*, int32, int)’:
src/yb/gutil/spinlock_linux-inl.h:101:7: error: ‘sys_futex’ was not declared in this scope
       sys_futex(reinterpret_cast<int *>(const_cast<Atomic32 *>(w)),
       ^~~~~~~~~
src/yb/gutil/spinlock_linux-inl.h:101:7: note: suggested alternative: ‘have_futex’
       sys_futex(reinterpret_cast<int *>(const_cast<Atomic32 *>(w)),
       ^~~~~~~~~
       have_futex
src/yb/gutil/spinlock_linux-inl.h: In function ‘void base::internal::SpinLockWake(volatile Atomic32*, bool)’:
src/yb/gutil/spinlock_linux-inl.h:113:5: error: ‘sys_futex’ was not declared in this scope
     sys_futex(reinterpret_cast<int *>(const_cast<Atomic32 *>(w)),
     ^~~~~~~~~
src/yb/gutil/spinlock_linux-inl.h:113:5: note: suggested alternative: ‘have_futex’
     sys_futex(reinterpret_cast<int *>(const_cast<Atomic32 *>(w)),
     ^~~~~~~~~
     have_futex

```
... and spinlock.cc
```c
src/yb/gutil/spinlock.cc: In member function ‘Atomic32 base::SpinLock::SpinLoop(int64, Atomic32*)’:
src/yb/gutil/spinlock.cc:104:19: error: ‘PauseCPU’ is not a member of ‘base::subtle’
     base::subtle::PauseCPU();
                   ^~~~~~~~
```

**Comment by graffido** [comment]
hi, @giminni the ‘PauseCPU’ error could be resolved by ‘yield’ instruction on ARM, and the sys_futex is not supported by ARM, so reference the ARM macro branch.
Also the CRCutil problem cannot link if not building the ‘example/interface’ source， use CRC32c package instead.

**Comment by nfrush** [comment]
@graffido @giminni Did you all ever get an ARM64 build working?

**Comment by hwhh** [comment]
Also interested in this, @giminni did you manage to get it working?

**Comment by rkarthik007** [comment]
cc @svarnau - would you be able to take a look at this?

**Comment by pixie79** [comment]
With more vendors now supporting Arm, Apple Amazon etc it would be good to see Arm as a first class citizen and also multi Arch Docker hub builds to simplify Kubernetes deployments.

**Comment by doughadfield** [comment]
We would love to see an "official" arm64 build of YugabyteDB, so we can use lower cost hardware for training, testing, etc. Even a "cookbook" of how to compile locally, so we can build our own images with each release, would be great!

**Comment by mbautin** [comment]
The initial support for aarch64 (Graviton2) builds was added in #9154.
