### ISSUE TITLE
RocksDB Statistics considers flush as compaction

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#2520]
Jira Link: [DB-1898](https://yugabyte.atlassian.net/browse/DB-1898)
FlushJob is increasing COMPACT_WRITE_BYTES stats instead of FLUSH_WRITE_BYTES. There is a fix in RocksDB original repo for this (with a fix on top of fix): 
- https://github.com/facebook/rocksdb/commit/ae21d71e94ebe82689aea39359c1661776871d52#diff-f8dc8f7b1ea2cb77b0eb9b156bc434f2.
- https://github.com/facebook/rocksdb/commit/24110ce90c2b2d4adff59fbccab24648cc5e6f33#diff-f8dc8f7b1ea2cb77b0eb9b156bc434f2

**Comment by chinmay291** [comment]
In our code, we do not incorrectly increment COMPACT_WRITE_BYTES like in the original RocksDB code.
The method RecordFlushIOStats defined here(https://github.com/yugabyte/yugabyte-db/blob/3cf34b07972c2ae6e13ed0265d4514ec3b738899/src/yb/rocksdb/db/flush_job.cc#L132) correctly updates FLUSH_WRITE_BYTES when a flush happens.
The only place where COMPACT_WRITE_BYTES gets updated is in the method DBImpl::WriteLevel0TableForRecovery - https://github.com/yugabyte/yugabyte-db/blob/3cf34b07972c2ae6e13ed0265d4514ec3b738899/src/yb/rocksdb/db/db_impl.cc#L1946

**Comment by rthallamko3** [comment]
@chinmay291 , COMPACT_WRITE_BYTES should be updated even for the regular writes, not just for the ones that come from recovery. We might need additional logic to achieve that.

**Comment by chinmay291** [comment]
@rthallamko3 Thanks for pointing this out. I had missed this while going through the code previously. We do call COMPACT_WRITE_BYTES for regular writes.
https://github.com/yugabyte/yugabyte-db/blob/01e36c7e9b1cb965fe4208feadfda6dc1ffe6cbe/src/yb/rocksdb/db/compaction_job.cc#L962

**Comment by chinmay291** [comment]
As per the above investigation, we are counting compactions correctly during recovery and during writes which trigger compactions. We are also not incorrectly considering flushes as compactions.
