### ISSUE TITLE
[YCQL] TestAuthorizationEnforcement OutOfMemoryError

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2527]
Jira Link: [DB-4679](https://yugabyte.atlassian.net/browse/DB-4679)
```sh
./yb_build.sh release --java-test org.yb.cql.TestAuthorizationEnforcement
```

Here is the partial output log: https://gist.githubusercontent.com/jj-kim/d7712f5ae3ff86b8d7609c143fd37875/raw.  The prominent error is `java.lang.OutOfMemoryError: unable to create new native thread`.

This run was on commit c22d61b9925f0b9e7f1a9ac26bb2440b8cf05581, CentOS, release-gcc-dynamic-ninja.  I have not seen the same error on Jenkins, yet.

**Comment by m-iancu** [comment]
Test looks stable in latest builds: https://detective-gcp.dev.yugabyte.com/stability?num_commits=100 
Closing given this is an old issue.
