### ISSUE TITLE
[CDC] Clean up cdc_state rows for deleted streams

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2529]
When a CDC stream is deleted, corresponding rows for it from `cdc_state` table should be deleted.

**Comment by ajcaldera1** [comment]
I have an additional requirement for this task. We should clean up the metrics when a CDC stream is deleted as well, otherwise it is difficult to tell which stream is active from the metrics point of view, since there will be multiple copies of metrics for the same tablet.
