### ISSUE TITLE
Does yugabyte allow plv8 for stored procedures?

### ISSUE THREAD

**Issue by fire** [yugabyte/yugabyte-db#2532]
https://plv8.github.io/

Hi, was looking into yugabyte.

Does yugabyte allow using plv8?

**Comment by ndeodhar** [comment]
Hi @fire,
We haven't tried this extension ourselves. But since YugabyteDB uses the upper half of Postgres, most extensions should work. Can you try it out and let us know what you find?
If you run into issues, we'll be happy to help!

**Comment by fire** [comment]
Do you have any instructions?

My plan is to use Kubernetes, how will I add the plv8 extension there?

**Comment by ddorian** [comment]
@fire  can you try the instructions here https://docs.yugabyte.com/latest/api/ysql/extensions/

**Comment by fire** [comment]
Since plv8 is not distributed with Linux packaging, it was too risky to use. There are attempts to replace v8 with another JavaScript engine, but that work hasn't been in production.

**Comment by rkarthik007** [comment]
@fire - makes sense. In case you give it a go, please let us know, would love to document it for the future.

**Comment by anmolsahoo25** [comment]
It does not work. The plv8 plugin uses the `CREATE LANGUAGE` feature, which is not supported yet. Just reporting here for other users, not a feature wish or anything! :sweat_smile: 

```
ERROR:  CREATE LANGUAGE not supported yet
LINE 1: CREATE LANGUAGE plv8;
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
```
