### ISSUE TITLE
[docdb] Provide default port to server_broadcast_addresses flag if none specified

### ISSUE THREAD

**Issue by LuisManuel1983** [yugabyte/yugabyte-db#2540]
Hi, we got an error on the manual deployment process following this instructions:

https://docs.yugabyte.com/latest/deploy/manual-deployment/

The objective is to get a Development Server to test YB against a backend designed in DART (Aqueduct)

This is the master script we're using:

> ./yb-master \
--master_addresses 192.168.0.124:7100 \
--rpc_bind_addresses 192.168.0.124 \
--webserver_interface=192.168.0.124 \
--server_broadcast_addresses 192.168.0.124 \
--replication_factor 1 \
--enable_ysql \
--fs_data_dirs "/tmp/testing" \
& /tmp/testing/yb-master.out &

Server script:

> ./yb-tserver \
  --tserver_master_addrs 192.168.0.124:7100 \
  --rpc_bind_addresses 192.168.0.124 \
  --start_pgsql_proxy \
  --pgsql_proxy_bind_address=192.168.0.124:5433 \
  --cql_proxy_bind_address=192.168.0.124:9042 \
  --webserver_interface=192.168.0.124 \
  --fs_data_dirs "/tmp/testing" \
  >& /tmp/testing/yb-tserver.out &

But we couldn't connect, we get this error:

![image](https://user-images.githubusercontent.com/16975334/66497856-1f6b7300-ea8b-11e9-84a9-b3446af98a89.png)

Reviewing the postgre logs, we found this:

![image](https://user-images.githubusercontent.com/16975334/66498084-7f621980-ea8b-11e9-9272-49361243dba8.png)

So we removed the flag "--server_broadcast_addresses" completely from the master script, killed the process master and server process, cleaned up the testing folder and ran the scripts again and we were able to finally connect, even remotely:

![image](https://user-images.githubusercontent.com/16975334/66498454-13cc7c00-ea8c-11e9-9c5f-3a6669dc3e63.png)

So the point to this, is to report that issue with the flag "--server_broadcast_addresses"

Also, the documentation is not very clear about what are the instructions to install a local development server, not a local cluster only usable from that machine

**Comment by bmatican** [comment]
Seems like `server_broadcast_addresses` does not inherit the default port values, like `rpc_bind_addresses` does, in the main.cc files, when we initially parse the flags.

We should probably just default pick up the port from the `rpc_bind_addresses`, unless one is specified.

**Comment by ramsrivatsa** [comment]
Fixed this issue with with the following [commit](https://github.com/yugabyte/yugabyte-db/commit/8f906a215c2ee79650fdb108b75cc44e1eb625b5).
