### ISSUE TITLE
[docdb] Improve RPC handling of Raft heartbeats

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#256]
Jira Link: [DB-2455](https://yugabyte.atlassian.net/browse/DB-2455)
Reported by @bmatican.

We've seen this a couple of times already, where in a cluster under heavy load, as the RPC queues back up, we reach a point where the amount of time a certain request will be sitting in the queue becomes greater than the time it takes for Raft level heartbeats to be missed enough times to trigger elections.

At that time, the cluster will start experiencing election storms for tablets with leaders on the backlogged TS and the cluster state will just keep degrading.

One solution we've talked about at various times was to have a separate path for handling the Raft level leader checks. This could ensure that essentially, heartbeats have highest priority in all RPC traffic.

One alternative measure could be to have some form of more flexible adjustment of how many failed heartbeats can a TS be comfortable with before triggering an election. This could potentially be based on inspecting the average time an RPC spent in the queue. Downside to this approach would be that it could increase the time it takes to detect failures and basically be a non-uniform handling across TSs....

Assigning to @mbautin for now for further discussion. CC @spolitov, @amitanandaiyer, @kmuthukk, @rkarthik007

**Comment by bmatican** [comment]
Closing this out as we now have pre-elections, as well as a high pri handling of raft RPCs.
