### ISSUE TITLE
Add mechanism to detect long running queries

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#258]
Reported by @bbaddepudi.

If a statement is taking long (based on a gflag threshold), we should have mechanism which helps polling for its status, using a unique id, and potentially kill it.

This could be extrapolated to all DML statements...

**Comment by m-iancu** [comment]
This has been largely addressed in https://github.com/yugabyte/yugabyte-db/commit/47cbf5ae4ef5d41b3198a76f1197253b93121e81 with several follows-ups for YCQL and YSQL.
See also issue #569.
