### ISSUE TITLE
[docs] Update manual deployment page for 2.0/YSQL

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#2595]
Hi Dorian,

https://docs.yugabyte.com/latest/deploy/public-clouds/aws/#manual-deployment

Needs three updates:

1) In section << 3. Prepare YB-Master configuration files >>

We should add a 

echo --enable_ysql >> $CONFIG_FILE

to the three conf files (corresponding to three AZs) for yb-master 

2) Similarly for yb-tserver:

add the 

--enable_ysql
--pgsql_proxy_bind_address=$ip:5433

3) Before the << 8. Test Cassandra Compatible YCQL API >> section:

Can you add a simple section for Test Postgres Compatible YSQL API.

**Comment by ddorian** [comment]
moved: https://github.com/yugabyte/yugabyte-db/pull/2645
