### ISSUE TITLE
Support a JSON datatype

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#26]
Eventually extend this type to perform:
  - #153: to add jsonb datatype
  - #154: create tables and select rows with the jsonb datatype
  - #162: filtering
  - #163: fine-grained selects
  - aggregations
  - local indexes

Plan as summarized by @pritamdamania87:
- Use jsonb for the serialization format.
- The jsonb blob would be stored as a value in DocDB. Initially this implementation would incur a read-modify-write overhead for updates. Although, we would have an optional flags field in front of the serialized jsonb which could be used to perform incremental updates later on. The merge can then be performed on the read path to avoid performance issues.
- In terms of query language, we’d support the postgres syntax for the query language since we intend to have postgres support in the future and reuse some of this logic there.

**Comment by pritamdamania87** [comment]
Support added in https://github.com/YugaByte/yugabyte-db/commit/193cd4ca2127d235a4e53d384e5a948010211b39, https://github.com/YugaByte/yugabyte-db/commit/05d100cb257fa125a7a9a67010b26227f2ac8275, https://github.com/YugaByte/yugabyte-db/commit/be2d598a6ed00b2fbe8b72810b6b070788c2e0e1, https://github.com/YugaByte/yugabyte-db/commit/e640ac7ed5c057d8ee0e010cd6b7b3af3dbc36bf, https://github.com/YugaByte/yugabyte-db/commit/63363dfe2dda4c69f8a33587660e271ede662faa
