### ISSUE TITLE
TSADD command doesn't accept expire_at and expire_in options in lowercase

### ISSUE THREAD

**Issue by hectorgcr** [YugaByte/yugabyte-db#260]
127.0.0.1:6379> TSADD cpu_usage 70 "80" expire_at 1
(error) ERR TSADD: expire_at is not a valid number

127.0.0.1:6379> TSADD cpu_usage 70 "80" expire_in 1
(error) ERR TSADD: expire_in is not a valid number

**Comment by kmuthukk** [comment]
@hectorgcr : Can we close this issue out? Looks like the commit (https://github.com/YugaByte/yugabyte-db/commit/01ef49b2ad65b403ece2b702274d4f4af3b8fa26) has landed.
