### ISSUE TITLE
[YSQL] Network failure. Segmentation fault

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#2601]
Jira Link: [DB-4829](https://yugabyte.atlassian.net/browse/DB-4829)
This issue is reported by @nspiegelberg , but I haven't found the causes to assign to appropriate engineer.  The test PgLibPqTest is currently still failing intermittently during test runs.

To reproduce
```
ybd debug --cxx-test pgwrapper_pg_libpq-test --gtest_filter PgLibPqTest.SerializableReadWriteConflict -n 100
```
Error Log
```
2637 [ts-1] 2019-09-19 14:20:58.669 PDT [35847] LOG:  server process (PID 37825) was terminated by signal 11: Segmentation fault
2638 [ts-1] 2019-09-19 14:20:58.669 PDT [35847] LOG:  terminating any other active server processes
2639 ../../src/yb/yql/pgwrapper/pg_libpq-test.cc:195: Failure
2640 Failed
2641 Bad status: Network error (yb/yql/pgwrapper/libpq_test_base.cc:51): Connect failed: 1, passed: 60.952s
```

**Comment by m-iancu** [comment]
Closing as this is an old issue and that test looks stable now: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgLibPqTest&fail_tag=all&name=SerializableReadWriteConflict&platform=all
