### ISSUE TITLE
[yugabyte-db] yugabyte-db command failed to start with error 

### ISSUE THREAD

**Issue by vaibhavp** [yugabyte/yugabyte-db#2611]
Hi Team, 

I am trying to run yugabyte-db using command-line tool but getting the following error while running it. 

```
python yugabyte-db start
Did not meet recommended system resource limits.
Current max_user_processes: 4096. Recommended: 64000. Use 'ulimit -u 64000' to set.
Current open_files: 1024. Recommended: 64000. Use 'ulimit -n 64000' to set.
Note Yugabyte DB will still run, although it may fail for larger workloads. For more info, see https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/
Starting Yugabyte DB (this may take a couple minutes)...
Traceback (most recent call last):
  File "yugabyte-db", line 1594, in <module>
    YugabyteProcessManager().run()
  File "yugabyte-db", line 866, in run
    args.func()
  File "yugabyte-db", line 103, in start
    self.start_processes()
  File "yugabyte-db", line 387, in start_processes
    if not self.init_yw():
  File "yugabyte-db", line 489, in init_yw
    run_process(create_play_table)
  File "yugabyte-db", line 1589, in run_process
    proc = subprocess.Popen(cmd, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Shutting down...
Killed
```

Platform:- CentOS 7 
Yugabyte Version:- 
```
----------------------------------------------------------------------
|                        Yugabyte DB Version                         |
----------------------------------------------------------------------
| Version        : 2.0.1.0-b19                                       |
| Build Time     : 04 Oct 2019 22:26:27 UTC                          |
| Build Hash     : 6607435dcbd4e8a90b48c2efc37f7ec50fce995a          |
----------------------------------------------------------------------
```

**Comment by rkarthik007** [comment]
Hi @vp15591,

I think there is some issue with the packaging. @WesleyW can confirm. This should be fixed in the next release.

**Comment by WesleyW** [comment]
Hi @vp15591, yes this is a packaging problem. Past packages were missing the UI code, but releases from now on should have them. For now, one way you can bypass this error is to disable the UI: `yugabyte-db start --disable_ui`.
Note: when we release it officially, the file name will most likely be changed (probably `yugabytedb`).

**Comment by WesleyW** [comment]
As a quick overview of yugabytedb:

1. `yugabytedb start` to create database.
2. Access the main UI on `localhost:7200` for basic information like metrics. Ports 7000 and 9000 may be used to view the master and tserver UI.
3. In a new terminal, open a CLI to the database with:
    - `yugabytedb connect {ysql,ycql}` : opens specified API CLI in the default database
    - `./bin/cqlsh` or `./bin/ysqlsh` for more options
4. Creating a sample database (You will have to do this on a new terminal):
    - `yugabytedb demo create retail` - create `retail` database. Other options are `northwind`, `club`, and `sports`
    - `yugabytedb demo run retail` - Open a CLI connected to `retail` database
    - `yugabytedb demo destroy retail` - Destroys the `retail` database. Would have to be created again to connect to it.
5. `yugabytedb status` to print status of current process.
6. Stop the process with SIGTERM or SIGKILL or with `cmd + c`.
7. `yugabytedb version` for version info.

Flags for `yugabytedb start`:

- `--log_dir`: location to store log files
- `--ysql_port`: Port on which YSQL should listen
- `--ycql_port`: Port on which YCQL should listen
- `--master_port`: Port for `yb-master` RPC calls.
- `--tserver_port`: Port for `yb-tserver` RPC calls.
- `--webserver_port`: Port for YW to run on. This is default 7200.
- `--webserver_ip`: IP address that YW will run on. By default is 0.0.0.0.
- `--enable_ui` and `--disable_ui`: Start or stop YugaWare. Does not affect yb-master and yb-tserver UI.

**Comment by vp15591** [comment]
thanks @WesleyW
