### ISSUE TITLE
Error when running ybmaster command in the Admin Reference docs

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#263]
Running the command listed in https://docs.yugabyte.com/latest/admin/yb-master/ with 1.0.0.0 gives the following error:

15:34 $ ./bin/yb-master \
> --master_addresses 172.151.17.130:7100,172.151.17.220:7100,172.151.17.140:7100 \
> --fs_data_dirs "/home/centos/disk1,/home/centos/disk2" \
> --replication_factor=3 &
[2] 3824
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0430 15:34:57.283545 2756350848 log_util.cc:859] Flag --wal_dirs is empty.
Pritams-MacBook-Pro-2:~/yugabyte-1.0.0.0
15:34 $ F0430 15:34:57.301622 2756350848 path_util.cc:61] Check failed: !a.empty() empty first component:
*** Check failure stack trace: ***

**Comment by bmatican** [comment]
I believe we've since improved the failure messaging.
