### ISSUE TITLE
Creating tables with a lot of tablets might cause CQL table creation timeouts

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#265]
Potential solutions:
- Async table creation (but we moved from async to sync already)
- Speeding up tablet creation / bulk tablet creation

**Comment by bmatican** [comment]
Hey @rahuldesirazu can you maybe update this with your CreateTable optimization issue / numbers and close it out if we're in decent shape even for higher number of tablets?

**Comment by rahuldesirazu** [comment]
Create table optimization tracked in https://github.com/YugaByte/yugabyte-db/issues/911 and implemented in 6831eabf1be4caf5f167711de1bd2ffc894783ef.
