### ISSUE TITLE
what should be default DB for connections of new YSQL custom user without DB ?

### ISSUE THREAD

**Issue by verzlo** [yugabyte/yugabyte-db#2660]
I observed with enabling Authentication for YSQL API - that after I created new custom user with password - it does not allow this user to login unless I create a database with the matching name for it.
Example:
[root@klxcasst2 ~]# $YUGABYTE_HOME/bin/ysqlsh -h klxcasst1 -U casuser
Password for user casuser:
ysqlsh: FATAL:  database "casuser" does not exist
-- after creating database with this name, It allow to login.
I know that in postgres you have to connect to a specific database  - so which one we should use by default for any new custom users for those logins (I see there are multiple ones like postgres, yugabyte)?

**Comment by ddorian** [comment]
hi @verzlo 
I believe this is a duplicate of https://github.com/yugabyte/yugabyte-db/issues/2484
