### ISSUE TITLE
[docdb] Speedup CREATE DATABASE for YSQL

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2662]
Jira Link: [DB-2337](https://yugabyte.atlassian.net/browse/DB-2337)
Internally, `CREATE DATABASE` uses `CatalogManager::CreateNamespace` and the corresponding `CatalogManager::CopyPgsqlSysTables`.

Right now, this does several things which are slow, in the master context:
1) create tables one at a time, with the corresponding raft write for per-table metadata
We should be able to refactor the code to batch together the sys_catalog updates for these tables!

2) also per table, read data from one system table and write into the newly created table
Again, since this is also per-table, we are doing yet another raft write for each table!

In an RF3 setting, that's a lot of raft writes we need to happen, before we're done creating a database. This frequently takes tens of seconds, see #1384 or #2659 and also several user notes on slack.

cc @nspiegelberg as he's also looking at #2236

**Comment by ndeodhar** [comment]
@bmatican Zhongwei did a bunch of improvements for this. Is there more work left here or can we close this?

**Comment by ndeodhar** [comment]
Zhongwei's commit to address this partly: https://github.com/yugabyte/yugabyte-db/commit/b9a229f13427c51a7b60990b8abb528931f1b467
