### ISSUE TITLE
[docdb] Speedup Master Leader startup

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2663]
Currently, the master stores multiple types of data in the system catalog (tables, tablets, namespaces, permissions, etc.). When a master becomes the leader, it clears its internal caches and loads them back up, by reading the data on disk. This is done through a visitor pattern, where we establish a `Visitor` class, per item type, that is responsible for loading the data for that type, into our in-memory structures.

Currently, it seems that `SysCatalog::Visit` actually ends up reading the whole data from the catalog and then just discarding all the rows for unwanted types...

We should be able to turn this from a O(types x total_rows) cost, to about O(total_rows), by just reading only what we care about, since type should be the index! Probably a simple projection when creating the iterator would suffice.

While we're here, would also be great to add some metrics around this startup time, like per-visitor load time, and even total load time, even though we can easily sum it up in an external system.

cc @nspiegelberg @rajukumaryb @hectorgcr @rahuldesirazu

**Comment by ndeodhar** [comment]
Can we close this @bmatican ?
