### ISSUE TITLE
one of Masters crashed when we tried to delete YSQL database 

### ISSUE THREAD

**Issue by verzlo** [yugabyte/yugabyte-db#2665]
from INFO log:
I1021 00:20:10.927984  5779 catalog_manager.cc:3998] Servicing DeleteNamespace request from 172.26.65.57:42762: namespace { id: "0000406e000030008000000000000000" name: "cms" } database_type: YQL_DATABASE_PGSQL
I1021 00:20:10.932032  5779 catalog_manager_ent.cc:1356] Deleting CDC streams for tables:
F1021 00:20:10.964869  5779 catalog_manager.cc:4133] Check failed: FindPtrOrNull(namespace_names_map_, database->name()) == nullptr YSQL database name should not be included in namespace_names_map_. If included, its name must be removed from map here when dropping

from ERROR /FATAL log:
Log file created at: 2019/10/21 00:20:10
Running on machine: klxcasst2.kiev.cqg
Application fingerprint: version 2.0.1.0 build 19 revision 6607435dcbd4e8a90b48c2efc37f7ec50fce995a build_type RELEASE built at 04 Oct 2019 22:26:27 UTC
Running duration (h:mm:ss): 50:06:16
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1021 00:20:10.964869  5779 catalog_manager.cc:4133] Check failed: FindPtrOrNull(namespace_names_map_, database->name()) == nullptr YSQL database name should not be included in namespace_names_map_. If included, its name must be removed from map here when dropping

**Comment by ndeodhar** [comment]
@verzlo Quick question: Do you have a CQL keyspace with the same name?

**Comment by verzlo** [comment]
yes we we do have CQL keyspace with same name ..

**Comment by ndeodhar** [comment]
Thanks for confirming, @verzlo.

@nocaway This CHECK is incorrect: `CHECK(FindPtrOrNull(namespace_names_map_, database->name()) == nullptr)` since we can also have a CQL keyspace with the same name.
Also, as a general rule of thumb, lets avoid `CHECK` in master and use `DCHECK`.

**Comment by OlegLoginov** [comment]
Fixed by the commit above.
