### ISSUE TITLE
[YSQL] Truncating an index crashes yb-master

### ISSUE THREAD

**Issue by hectorgcr** [yugabyte/yugabyte-db#2666]
Truncating an index crashes yb-master in debug mode.

To replicate:
```
CREATE TABLE ITABLE ( ptest1 int, ptest2 int, ptest3 text);
CREATE UNIQUE INDEX ITABLE_IDX ON ITABLE(ptest1, ptest2);
TRUNCATE ITABLE CASCADE;
```

fails with this fatal:
```F1018 19:54:56.574093 12686 catalog_manager.cc:2591] Check failed: is_index == (l->data().pb.has_index_info() || !l->data().pb.indexed_table_id().empty()) ```

**Comment by OlegLoginov** [comment]
Closing it as a duplicate of  https://github.com/yugabyte/yugabyte-db/issues/1632
