### ISSUE TITLE
Check if there is a race condition between txn status lookup and applying provisional records

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#267]
@kmuthukk pointed out this possible scenario:
- A txn is committed but provisional records not applied yet
- A read request comes to one of participating tables and it sends a request to the txn status tablet to check the status.
- At the same time, the txn status tablet finishes getting acks from all participating tablets that they've replicated the APPLY message, replicates APPLIED in his Raft log, and removes the transaction from its data structures. If we treat missing transaction records as if the transaction is aborted, this could result in erroneously hiding committed data from the read request's result.

Cc @robertpang as well.

**Comment by rkarthik007** [comment]
I remember we had discussed this in the early days, and wanted to retain the txn status entries for a while after the txn had finished - expire them with a TTL after a week or two (configurable with min retention enforced). That is useful even for introspection later on. But we moved from the `system txn table` based design to the `txn status tablets` based design, so not sure if that is still applicable.

**Comment by spolitov** [comment]
This scenario was discussed during design of distributed txns.
It is handled in the following manner.
If txn status tablet returns that it does not know such transaction, i.e. returned status is ABORTED.
Then we recheck "local commit time".

The appropriate code could be found at the end of `TransactionStatusCache::DoGetCommitTime`.
