### ISSUE TITLE
[docdb] Investigate multiple compactions picking the same files

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2670]
Compactions starting
> I1020 16:33:07.210678 93631 event_logger.cc:67] T 46addd027e3448fdab8e4ed7c6407d59 P b0addda3dc85471dac7a9635e775a1b3 [R]: EVENT_LOG_v1 {"time_micros": 1571589187210656, "job": 666, "event": "compaction_started", "files_L0": [671, 670, 669, 667, 668, 662, 652, 633], "score": 1.6, "input_data_size": 3968553904}
> I1020 17:04:41.524274  5858 event_logger.cc:67] T 46addd027e3448fdab8e4ed7c6407d59 P b0addda3dc85471dac7a9635e775a1b3 [R]: EVENT_LOG_v1 {"time_micros": 1571591081524247, "job": 4, "event": "compaction_started", "files_L0": [698, 696, 691, 690, 688, 686, 685, 684, 683, 678, 672, 671, 670, 669, 667, 668, 654, 633, 601, 523, 518, 511, 507, 493, 465, 425, 354], "score": 5.4, "input_data_size": 26943139431}

Compaction finished for job 666
> I1020 16:55:50.086805 93631 event_logger.cc:77] T 46addd027e3448fdab8e4ed7c6407d59 P b0addda3dc85471dac7a9635e775a1b3 [R]: EVENT_LOG_v1 {"time_micros": 1571590550068273, "job": 666, "event": "compaction_finished", "compaction_time_micros": 1362826469, "output_level": 0, "num_output_files": 1, "total_output_size": 0, "num_input_records": 57875497, "num_output_records": 57875496, "num_subcompactions": 1, "lsm_state": [25]}

Notice how `671, 670, 669, 667, 668` appear in both the compactions. Moreover, job 666 finished before job 4?

Have asked @rajukumaryb to take a preliminary look at this.

cc @ttyusupov @spolitov @rao-vasireddy

**Comment by spolitov** [comment]
The order of logs is:
job 666 start, job 666 finish, job 4 start.
So I suppose it is different RocksDB instances. And it could be remotely bootstrapped in the middle.

**Comment by bmatican** [comment]
Closing as non issue.
