### ISSUE TITLE
ysqlsh and t-server crashed/aborted while running DDL in CLI tool to create tables

### ISSUE THREAD

**Issue by verzlo** [yugabyte/yugabyte-db#2675]
after recent rolling restarts - I created new YSQL database and start running simple DDL create table/index script and while doing it - client (and t-server) crashed/aborted,. See below screen output and FATAL log:

yugabyte=# \i '/root/Downloads/storage-br_CMSDBSelection/_10_CreateDB.postgresql.sql'
CREATE DATABASE
yugabyte=# \i '/root/Downloads/storage-br_CMSDBSelection/_20_CreateUsers.postgresql.sql'^C
yugabyte=# \i '/root/Downloads/storage-br_CMSDBSelection/_20_CreateUsers.postgresql.sql'
CREATE ROLE
yugabyte=# \c CMS
You are now connected to database "CMS" as user "yugabyte".
CMS=# \i '/root/Downloads/storage-br_CMSDBSelection/_22_CreateSchema.postgresql.sql'
CREATE TABLE
CREATE INDEX
GRANT
GRANT
CREATE TABLE
CREATE INDEX
GRANT
GRANT
GRANT
ysqlsh:/root/Downloads/storage-br_CMSDBSelection/_22_CreateSchema.postgresql.sql:50: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
ysqlsh:/root/Downloads/storage-br_CMSDBSelection/_22_CreateSchema.postgresql.sql:50: connection to server was lost
[2]+  Aborted                 (core dumped) nohup ./bin/yb-tserver --flagfile /var/lib/yugabyte-2.0.1.0/tserver.conf &>/var/lib/yugabyte-2.0.1.0/yb-tserver.out

from T-server log:
2019-10-22 16:27:03.363 UTC [9691] HINT:  Future log output will appear in directory "/var/lib/yugabyte/data01/yb-data/tserver/logs".
F1022 16:36:54.282769 10868 rpc.cc:316] Check failed: calls_.empty() Calls: [0x000000002f300c10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71" write_batch { write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!J\200" value: "$" } write_pairs { key: "G\252\211I\20
0\000\000\000\000\000\000\n!!K\201" value: "I\000\002\026\213.\207R\270" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\202" value: "STressa White" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\203" value: "Swhite.tressa@yahoo.com" } write_pairs {
key: "G\252\211I\200\000\000\000\000\000\000\n!!K\204" value: "S13081-13217 Main Street" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\205" value: "SUpper Sandusky" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\206" value: "SOH" } write_pairs { ke
y: "G\252\211I\200\000\000\000\000\000\000\n!!K\207" value: "S43351" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\210" value: "S1968-01-13" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\211" value: "D@Df|D\036=\002" } write_pairs { key: "G\252\21
1I\200\000\000\000\000\000\000\n!!K\212" value: "D\300T\322*kx\364\336" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\213" value: "S81052233-b32e-43cb-9505-700dbd8d3fca" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\214" value: "SGoogle" } } exter
nal_hybrid_time: 6436654948882030592, retrier: { task_id: -1 state: kFinished deadline: 11494812.651s }, 0x000000002f300c10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71" write_batch { write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!J\200" value: "$" } write
_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\201" value: "I\000\002\026\213.\207R\270" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\202" value: "STressa White" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\203" value: "Swhite.tressa
@yahoo.com" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\204" value: "S13081-13217 Main Street" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\205" value: "SUpper Sandusky" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\206" val
ue: "SOH" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\207" value: "S43351" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\210" value: "S1968-01-13" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\211" value: "D@Df|D\036=\002" }
write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\212" value: "D\300T\322*kx\364\336" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\213" value: "S81052233-b32e-43cb-9505-700dbd8d3fca" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\214
" value: "SGoogle" } } external_hybrid_time: 6436654948882030592, retrier: { task_id: -1 state: kFinished deadline: 11494812.651s }, 0x0000000042487b10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71" write_batch { write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\
335!!J\200" value: "$" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\201" value: "I\000\001\3439/R\3538" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\202" value: "SJerry Stracke" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\33
5!!K\203" value: "Sjerry.stracke@hotmail.com" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\204" value: "S9301-9351 South Rangeline Road" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\205" value: "SColumbia" } write_pairs { key: "G\243\202I\20
0\000\000\000\000\000\002\335!!K\206" value: "SMO" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\207" value: "S65201" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\210" value: "S1990-06-02" } write_pairs { key: "G\243\202I\200\000\000\000\000\
000\002\335!!K\211" value: "D@Cl\000,u\251\322" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\212" value: "D\300W\r\227\025Z\333\030" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\213" value: "Sd59fa15c-566c-48ca-ac35-f2cd9dc61d57" } write_pai
rs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\214" value: "SGoogle" } } external_hybrid_time: 6436654961642856448, retrier: { task_id: -1 state: kFinished deadline: 11494817.920s }]
Fatal failure details written to /var/lib/yugabyte/data01/yb-data/tserver/logs/yb-tserver.FATAL.details.2019-10-22T16_36_54.pid9689.txt
F20191022 16:36:54 ../../src/yb/rpc/rpc.cc:316] Check failed: calls_.empty() Calls: [0x000000002f300c10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71" write_batch { write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!J\200" value: "$" } write_pairs { key: "G\252
\211I\200\000\000\000\000\000\000\n!!K\201" value: "I\000\002\026\213.\207R\270" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\202" value: "STressa White" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\203" value: "Swhite.tressa@yahoo.com" } write_
pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\204" value: "S13081-13217 Main Street" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\205" value: "SUpper Sandusky" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\206" value: "SOH" } write_pa
irs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\207" value: "S43351" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\210" value: "S1968-01-13" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\211" value: "D@Df|D\036=\002" } write_pairs { key: "
G\252\211I\200\000\000\000\000\000\000\n!!K\212" value: "D\300T\322*kx\364\336" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\213" value: "S81052233-b32e-43cb-9505-700dbd8d3fca" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\214" value: "SGoogle" }
 } external_hybrid_time: 6436654948882030592, retrier: { task_id: -1 state: kFinished deadline: 11494812.651s }, 0x000000002f300c10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71" write_batch { write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!J\200" value: "$"
 } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\201" value: "I\000\002\026\213.\207R\270" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\202" value: "STressa White" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\203" value: "Swhit
e.tressa@yahoo.com" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\204" value: "S13081-13217 Main Street" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\205" value: "SUpper Sandusky" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\
206" value: "SOH" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\207" value: "S43351" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\210" value: "S1968-01-13" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\211" value: "D@Df|D\036=
\002" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\212" value: "D\300T\322*kx\364\336" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\n!!K\213" value: "S81052233-b32e-43cb-9505-700dbd8d3fca" } write_pairs { key: "G\252\211I\200\000\000\000\000\000\000\
n!!K\214" value: "SGoogle" } } external_hybrid_time: 6436654948882030592, retrier: { task_id: -1 state: kFinished deadline: 11494812.651s }, 0x0000000042487b10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71" write_batch { write_pairs { key: "G\243\202I\200\000\000\000\000\
000\002\335!!J\200" value: "$" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\201" value: "I\000\001\3439/R\3538" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\202" value: "SJerry Stracke" } write_pairs { key: "G\243\202I\200\000\000\000\000\00
0\002\335!!K\203" value: "Sjerry.stracke@hotmail.com" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\204" value: "S9301-9351 South Rangeline Road" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\205" value: "SColumbia" } write_pairs { key: "G\243
\202I\200\000\000\000\000\000\002\335!!K\206" value: "SMO" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\207" value: "S65201" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\210" value: "S1990-06-02" } write_pairs { key: "G\243\202I\200\000\000\
000\000\000\002\335!!K\211" value: "D@Cl\000,u\251\322" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\212" value: "D\300W\r\227\025Z\333\030" } write_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\213" value: "Sd59fa15c-566c-48ca-ac35-f2cd9dc61d57" } w
rite_pairs { key: "G\243\202I\200\000\000\000\000\000\002\335!!K\214" value: "SGoogle" } } external_hybrid_time: 6436654961642856448, retrier: { task_id: -1 state: kFinished deadline: 11494817.920s }]
    @     0x7f4f62b330c5  yb::LogFatalHandlerSink::send()
    @     0x7f4f61d3a616  google::LogMessage::SendToLog()
    @     0x7f4f61d37d0a  google::LogMessage::Flush()
    @     0x7f4f61d3ac39  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4f645aa630  yb::rpc::Rpcs::Shutdown()
    @     0x7f4f6a59098b  yb::tserver::enterprise::CDCPoller::~CDCPoller()
    @     0x7f4f6a586cf3  yb::tserver::enterprise::CDCConsumer::RemoveFromPollersMap()
    @     0x7f4f6a58fc85  yb::tserver::enterprise::CDCPoller::DoHandlePoll()
    @     0x7f4f62bc0764  yb::ThreadPool::DispatchThread()
    @     0x7f4f62bbba19  yb::Thread::SuperviseThread()
    @     0x7f4f5d6ba694  start_thread
    @     0x7f4f5cdf741d  __clone
    @              (nil)  (unknown)

*** Check failure stack trace: ***
    @     0x7f4f62b317fc  yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7f4f61d381bd  google::LogMessage::Fail()
    @     0x7f4f61d3a21d  google::LogMessage::SendToLog()
    @     0x7f4f61d37d0a  google::LogMessage::Flush()
    @     0x7f4f61d3ac39  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4f645aa630  yb::rpc::Rpcs::Shutdown()
    @     0x7f4f6a59098b  yb::tserver::enterprise::CDCPoller::~CDCPoller()
    @     0x7f4f6a586cf3  yb::tserver::enterprise::CDCConsumer::RemoveFromPollersMap()
    @     0x7f4f6a58fc85  yb::tserver::enterprise::CDCPoller::DoHandlePoll()
    @     0x7f4f62bc0764  yb::ThreadPool::DispatchThread()
    @     0x7f4f62bbba19  yb::Thread::SuperviseThread()
    @     0x7f4f5d6ba694  start_thread
    @     0x7f4f5cdf741d  __clone
    @              (nil)  (unknown)

**Comment by kmuthukk** [comment]
Looks like CDC was enabled as well, and could be CDC specific (that feature is still in beta as of 2.0) -- but thx for reporting this issue @verzlo . We'll look into this.

`F1022 16:36:54.282769 10868 rpc.cc:316] Check failed: calls_.empty() Calls: [0x000000002f300c10 -> CDCWriteRpc: tablet_id: "d979c91cbf044c8a87d51be10f32fc71"`

**Comment by verzlo** [comment]
Yes - I have CDC enabled for single table - but it is from totally different unrelated database ( I enabled it on yb_demo for users table only to validate the CDC 2DC process)..
Is there any dependencies here we not aware of which may trigger this (abort/crash is rather extreme way of conflict resolution ;-) ?

**Comment by verzlo** [comment]
FYI - no other node t-server crashed ( same error with different tablet-ID. I checked and both tablet IDs belong to same USERS table I setup replication for in yb_demo Database.

**Comment by verzlo** [comment]
I see. I tried to run your disabling command - but it looks like it is be default trying to connect to a loopback IP and not working:

[root@klxcasst5 yugabyte-2.0.1.0]# ./bin/yb-admin set_universe_replication_enabled a8057420-4cb5-4c6a-bf44-9a8ffed2e46e 0
I1022 17:08:32.165863 27820 mem_tracker.cc:250] MemTracker: hard memory limit is 13.182335 GB
I1022 17:08:32.166015 27820 mem_tracker.cc:252] MemTracker: soft memory limit is 11.204985 GB
W1022 17:08:32.169687 27822 dns_resolver.cc:149] Peer address 'localhost' resolves to [127.0.0.1, ::1] different addresses. Using 127.0.0.1
I1022 17:08:32.170392 27826 tcp_stream.cc:293] { local: 127.0.0.1:52168 remote: 127.0.0.1:7100 }:  Recv failed: Network error (yb/util/net/socket.cc:538): recvmsg error: Connection refused (system error 111)
I1022 17:08:33.564280 27828 tcp_stream.cc:293] { local: 127.0.0.1:52268 remote: 127.0.0.1:7100 }:  Recv failed: Network error (yb/util/net/socket.cc:538): recvmsg error: Connection refused (system error 111)
W1022 17:08:37.264005 27823 dns_resolver.cc:149] Peer address 'localhost' resolves to [127.0.0.1, ::1] different addresses. Using 127.0.0.1
I1022 17:08:37.467841 27826 tcp_stream.cc:293] { local: 127.0.0.1:52368 remote: 127.0.0.1:7100 }:  Recv failed: Network error (yb/util/net/socket.cc:538): recvmsg error: Connection refused (system error 111)
W1022 17:08:42.268460 27824 dns_resolver.cc:149] Peer address 'localhost' resolves to [127.0.0.1, ::1] different addresses. Using 127.0.0.1


what would be the syntax to direct it to proper IP ?

**Comment by ndeodhar** [comment]
You can use
`yb-admin -master_addresses IP1:7100,IP2:7100,IP3:7100 set_universe_replication_enabled a8057420-4cb5-4c6a-bf44-9a8ffed2e46e 0`

Please replace IP1, IP2, IP3 with IP addresses of your master nodes. Note that I'm assuming you have 3 master nodes. You'll need to specify all your master IPs in `-master_addresses`.

**Comment by verzlo** [comment]
thanks - I was able to disable it and now cluster seem to be stable for at least 30 min ( note that I had to specify MASTER IPs of the consumer cluster (similar to how initial CDC repl setup used for setup_universe_replication). Now my question is - when is it safe to turn it back or I have to remove/re-establish replication ?

**Comment by ndeodhar** [comment]
Great to hear that it worked. You can turn it back on once you're done running DDLs.

**Comment by verzlo** [comment]
FYI - I did reenable replication in both directions  and both commands returned success after I completed DDL execution and it looks stable so far, but I'm now seeing strange issue where replication seem to only work 1 way (update 1 row on that table working from Good cluster to the one which had crashes , but reverse updates to do not show up in the same table).
DO you know if there are any know issues with this after disable/reenable of where I can check/collect additional diag info?

**Comment by ndeodhar** [comment]
Can you check the tserver logs for errors?
Tserver logs will be available at `<yugabyte-data-dir>/disk-1/yb-data/tserver/logs/yb-tserver.INFO`.
You'll need to check logs on both clusters since it's not fully clear whether this is a problem on producer or consumer side.

**Comment by verzlo** [comment]
Thanks . I simulated it again and looked in the logs and see some CDC warnings/info  in both consumer and producer for the direction which is not working:

Producer cluster has following messages continuously in the tserver logs:
I1023 20:03:56.546880 12636 consensus_queue.cc:553] T b336218c0bba4f70adc4f12154755b5a P 49e075d0f96340c4b0dd3ac4f8d0dcb0 [LEADER]: The logs from index 0 have been garbage collected and cannot be read (Not found (yb/consensus/log_reader.cc:292): Failed to read ops 1..913: Segment 1 which contained index 1 has been GCed)
I1023 20:04:00.173596 12642 consensus_queue.cc:553] T 9b3b40d64d0840b1a6e8c913514d798a P 49e075d0f96340c4b0dd3ac4f8d0dcb0 [LEADER]: The logs from index 0 have been garbage collected and cannot be read (Not found (yb/consensus/log_reader.cc:292): Failed to read ops 1..943: Segment 1 which contained index 1 has been GCed)
I1023 20:04:00.914968 12635 consensus_queue.cc:553] T c1b90feba5f247778b406bb46c91a58f P 49e075d0f96340c4b0dd3ac4f8d0dcb0 [LEADER]: The logs from index 0 have been garbage collected and cannot be read (Not found (yb/consensus/log_reader.cc:292): Failed to read ops 1..976: Segment 1 which contained index 1 has been GCed)
I1023 20:04:08.915977 12633 consensus_queue.cc:553] T d979c91cbf044c8a87d51be10f32fc71 P 49e075d0f96340c4b0dd3ac4f8d0dcb0 [LEADER]: The logs from index 0 have been garbage collected and cannot be read (Not found (yb/consensus/log_reader.cc:292): Failed to read ops 1..1135: Segment 1 which contained index 1 has been GCed)


Consumer cluster has following WARN messages poping once in a while ( observed soon after simulation of update which did not propagate):
W1023 20:03:52.342927 22266 cdc_poller.cc:132] CDCPoller failure response: code: NOT_FOUND
message: "Failed to read ops 1..1042: Segment 1 which contained index 1 has been GCed"
source_file: "../../src/yb/consensus/log_reader.cc"
source_line: 292
errors: "\000"
W1023 20:03:52.343364 22267 cdc_poller.cc:132] CDCPoller failure response: code: NOT_FOUND
message: "Failed to read ops 1..1555: Segment 1 which contained index 1 has been GCed"
source_file: "../../src/yb/consensus/log_reader.cc"
source_line: 292
errors: "\000"
W1023 20:03:52.344545 22265 cdc_poller.cc:132] CDCPoller failure response: code: NOT_FOUND
message: "Failed to read ops 1..1233: Segment 1 which contained index 1 has been GCed"
source_file: "../../src/yb/consensus/log_reader.cc"
source_line: 292
errors: "\000"

**Comment by ndeodhar** [comment]
@verzlo Thanks for checking. Looks like it's related to this issue: https://github.com/yugabyte/yugabyte-db/issues/2522 which has been fixed and should be available in the next release in a few days.

Unfortunately, this means that your replication can't make progress since we've lost WALs. Note that we're also building bootstrapping for 2DC where we'll recover from such situations automatically. That will be available by end of Nov.

**Comment by verzlo** [comment]
I see.. thanks.. I'll drop/recreate replication for now and will wait for next release to upgrade and test.
Before we close this issue - are there any other "critical" CDC related fixes which will be included in the upcoming release (in my view critical is when CDC bug/issue causing crash/significant latency to whole cluster or has dependency on regular cluster operations like restart/DDL execution, etc) so we can try to simulate and validate those after next release?

**Comment by ndeodhar** [comment]
These are the important ones:
https://github.com/yugabyte/yugabyte-db/issues/2522
https://github.com/yugabyte/yugabyte-db/issues/2549
https://github.com/yugabyte/yugabyte-db/issues/2486 (causes high cpu and io load in multi-master mode, but not data loss).

**Comment by verzlo** [comment]
thanks.
