### ISSUE TITLE
Test yugabyte-db workflow as part of itest

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#2678]
Have a local itest that verifies 
- yugabyte-db start up
- ability to import the local rf=1 universe into yugaware

This would not only ensure yugabyte-db is being packaged properly but also test post_install.sh on centos because yugabyte-db runs it.

@bmatican @mbautin @WesleyW @ramkumarvs 

@rkarthik007 mentioned that a dockerized test would be a nice to have here.

**Comment by WesleyW** [comment]
@iSignal This would probably be beter as a Jenkins test I think. The tests should not require high workloads and be able to be completed decently quickly, so having it trigger for either YW or YB diffs would be good.

**Comment by iSignal** [comment]
Currently, we have a "local" itest at https://bitbucket.org/yugabyte/internal-services/src/65c58bd7fc78f7dcd8a626275508c516e4c13f27/itest/src/universe_tests/__init__.py#lines-102 that verifies yb-ctl out of a yugabyte tar.gz package. The plan is to add a yugabytedb launcher test to the same file.

I also tried adding a docker based test to start yugabyte db via something like 
```
docker run -p 5433:5433 yugabytedb/yugabyte ./yugabyte-db start --disable_ui
```
but that requires the underlying yb-tserver to bind to 0.0.0.0 first, so it doesn't work properly right now. Will track that as part of

**Comment by iSignal** [comment]
#2732 for the docker test
