### ISSUE TITLE
yugabyte-db process UI improvements

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#2684]
Command Improvements:
• Remove {start,status,version,connect,demo} from the help print
• Remove `Current max_user_processes: 2500. Recommended: 64000. Use ‘ulimit -u 64000’ to set.`
• Update Title on cmd line: “Yugabyte DB (UP)” should be “YugabyteDB”
• No need port in “bin/ysqlsh -p 5433”
• No need host and port in “bin/cqlsh 127.0.0.1 9042"
• Running --help on demo option should give a couple of examples. Otherwise it’s not intuitive what to do next
• Need time estimate: Initializing northwind demo database…
• Running the northwind demo fails with wrong error message: northwind demo has not been created.Run yugabyte-db demo create northwind. For more information, check the logs in /Users/karthik/yugabyte/yugabyte-2.0.2.0/yugabyte-logs

UI Improvements
• if I close the 7200 page tab without dismissing the popup, and then reopen it - the popup does not show. Would like this to happen after I hit dismiss.
• No links to master/tserver page from nodes page
• After login does not go to universe overview page
• connect popup shows YCQL by default, should be YSQL
• Nodes unreachable/error on nodes tab
• Landing page should be the universe details page not the universe page.
• Clicking the universe card, keeps redirecting to `http://localhost:7200/universes/universes`
• Tasks tab should be disabled, no point showing not available on `Yugabyte Platform`
• Run sample app command doesn't work (meaning cannot connect to the database from docker container), we need to do host network option, ex: `docker run -d --network host yugabytedb/yb-sample-apps --workload SqlInserts --nodes host.docker.internal:5433` again we need to validate if this works on linux environments
• We should have modal to show the command to load demo data.
• Landing page should be the universe details page not the universe page.
• Metrics that we have available should be shown consistently both on the metrics tab and overview tab.
• First time the UI loads, you briefly see the login page before the redirect.

Other issues
• Make the process run as no-hup and in the background by default
• Join us on slack and github should be buttons (at the footer) if possible

**Comment by iSignal** [comment]
Closing since we have captured most of this in existing tasks.
