### ISSUE TITLE
The doc about TTL to complete

### ISSUE THREAD

**Issue by Fulton-x** [yugabyte/yugabyte-db#2690]
Hello,
The doc about TTL seems not complete
https://docs.yugabyte.com/latest/develop/learn/ttl-data-expiry

Thanks

**Comment by ddorian** [comment]
fill from here: https://forum.yugabyte.com/t/hows-ttl-performance/546/3?u=dorian_yugabyte

**Comment by ddorian** [comment]
fixed in https://github.com/yugabyte/yugabyte-db/pull/3076
