### ISSUE TITLE
Increase defaults to rocksdb_compact_flush_rate_limit_bytes_per_sec and remote_bootstrap_rate_limit_bytes_per_sec

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2692]
I think we can increase rocksdb_compact_flush_rate_limit_bytes_per_sec  to 1GB and 
remote_bootstrap_rate_limit_bytes_per_sec to 384 or 512MB

**Comment by amitanandaiyer** [comment]
increasing rocksdb_compact_flush_rate_limit_bytes_per_sec should be fine. But as far as I can tell, we have not come close to hitting that limit during compactions.

**Comment by bmatican** [comment]
Based on recent observations:
- in most cases, we're not disk bound, so `rocksdb_compact_flush_rate_limit_bytes_per_sec` will likely not help, as @amitanandaiyer mentioned
- talked to @hectorgcr yesterday and he was worried about increasing `remote_bootstrap_rate_limit_bytes_per_sec`, as for lower bandwidth setups, it might affect foreground traffic too much...

Thoughts?

**Comment by rao-vasireddy** [comment]
Increasing the default RBS rate may not be good idea. If there is only 1 disk, its easy to hit its limit. Closing this out for now as no change is needed.
