### ISSUE TITLE
[Platform] yugabytedb script initial feedback

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#2700]
Collection of improvements to the command line user experience based on the last round of feedback:

- <del>Add stop, status commands</del>

- <del>Add help command</del>

- <del>Change demo to a load a single (smallest) database
-- yugabyted demo with no arguments
-- load the database 
-- launch a ysql shell
-- delete the database when ysql shell exits
-- Need time estimate: Initializing demo database… let's say a couple of minutes
</del>
- <del>Only display version info in yugabyte-db status (not build hash/time)</del>

- <del>Output help message if user some argparse errors, e.g. too few arguments</del>

- <del> Reduce current max_user_processes limit to  make sure we dont see the warning message for low ulimit in the common case </del>

- <del> Update Title on cmd line: “Yugabyte DB (UP)” should be “YugabyteDB” </del>

- <del> No need port in “bin/ysqlsh -p 5433” </del>
- <del> No need host and port in “bin/cqlsh 127.0.0.1 9042" </del>

- <del> Output a troubleshooting link in case of errors</del>
-- <del>Do not output a python error call stack</del>

- <del>Change JDBC connection string to use yugabyte database instead of postgres: jdbc:postgresql://127.0.0.1:5433/yugabyte</del>

- 

------------

- Remove {start,status,version,connect,demo} from the help print

**Comment by ramkumarvs** [comment]
https://github.com/yugabyte/yugabyte-db/issues/2684
