### ISSUE TITLE
Yugabyte for production

### ISSUE THREAD

**Issue by amit2103** [YugaByte/yugabyte-db#271]
is Yugabyte ready for production? Is the replication etc tested? Is it still in beta ?

**Comment by rkarthik007** [comment]
Hi @amit2103,

Yes! We are proud to announce that YugaByte DB is ready for production, and is being used to power some business critical use-cases in production. The replication along with many other features are tested. There are some beta features such as distributed secondary indexes and the JSON data type, these are clearly marked in our documentation.

If you are considering YugaByte DB for a production use-case, would love to hear more about it!

**Comment by schoudhury** [comment]
@amit2103 you can find more details in our 1.0 release announcement post from last week: https://blog.yugabyte.com/announcing-yugabyte-db-1-0-f6e543d3a92b

**Comment by amit2103** [comment]
So I ran Yugabyte in Ubuntu WIndows shell and it started correctly (I have already tested it does work on Ubuntu and done some tests). However it seems I need to ask it to bind to 0.0.0.0..is there any config fo rthat ?

**Comment by mbautin** [comment]
@amit2103: thank you for trying out YugaByte DB! We do test against Jepsen, please see this project: https://github.com/YugaByte/yugabyte-db/projects/11. So far we haven't found any major bugs, and we will be publishing the results of our Jepsen testing within a few weeks. In the meantime, are there any specific Jepsen-related questions you have? Cc @ttyusupov 

We haven't tested running YugaByte DB in Windows Subsystem for Linux, if that's what you are referring to. Currently the recommended way to run YugaByte DB on Windows is to use Docker or a Linux VM (e.g. VirtualBox). I've just tried starting a local cluster on Ubuntu in Windows Subsystem for Linux, and I have run into issues making sure NTP is available there, which is one of the basic requirements YugaByte DB has for the underlying system. Filed #272 to address this issue for test clusters. It sounds like you might have gotten past that issue. I'm assuming that you're trying to start a local cluster using the `yb-ctl` tool -- correct me if I'm wrong. `yb-ctl` launches three yb-master and three yb-tserver processes that bind to loopback IP addresses `127.0.0.{1,2,3}`. There should be no need to bind to `0.0.0.0`. Could you please share the logs found at `/tmp/yugabyte-local-cluster/node-*/disk-*/yb-data/*/logs/yb-*.*` on any other YugaByte DB logs you might have?

**Comment by rkarthik007** [comment]
@amit2103 - here is a compilation of perf results for our 1.0 version: https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md
Note that you can get much lower read latencies (200 microseconds) if the workload pattern is cached and the num ops/sec is a bit lower, here we are pushing nodes to more than 70% CPU usage. Also note that this is a 3 node, replication factor=3 setup benchmark, we have not done single node benchmarks. I have posted the summary from the report.

Summary:
3 node, 16 vCPUs. Each write is replicated 3 ways internally. Each key-value is around 64 bytes combined. See [setup details](https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md#setup) for more info.

* CassandraKeyValue (see [details](https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md#cassandrakeyvalue))
    * 85K writes/sec at 3ms latency
    * 190K reads/sec at 1.3ms latency
* CassandraBatchKeyValue (see [details](https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md#cassandrabatchkeyvalue))
    * 211K writes/sec at 11ms latency
* RedisKeyValue (see [details](https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md#rediskeyvalue))
    * 76K writes/sec at 3.4ms latency
    * 151K reads/sec at 1.7ms latency
* RedisPipelinedKeyValue (see [details](https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md#redispipelinedkeyvalue))
    * 537K writes/sec at 21ms
    * 468K reads/sec at 16ms

See [YCSB results](https://github.com/YugaByte/yugabyte-db/blob/master/docs/yb-perf-v1.0.0.md#ycsb-run-info).

**Comment by kmuthukk** [comment]
@amit2103 - closing this question/issue for now. Feel free to re-connect/open on any pending questions.

ps: If you want to discuss more about your use case, happy to. Let us know.
