### ISSUE TITLE
ysqlsh: FATAL:  Not found: Error loading table

### ISSUE THREAD

**Issue by likenamehaojie** [yugabyte/yugabyte-db#2710]
yugabytd 2.0.1

**Comment by kmuthukk** [comment]
hi @likenamehaojie --

could you provide a bit more context on the how you created the cluster, and the steps to reproduce the problem?

**Comment by likenamehaojie** [comment]
@kmuthukk
version  i use yugabyte 2.0.1 
doc:      Manual deployment deploy doc

my linux user is  like  and deploy yuga in /home/like/yuga


i use 3 master  and 3 tserver nodes 
master.conf 
--master_addresses=192.168.100.131:7100,192.168.100.132:7100,192.168.100.134:7100
--rpc_bind_addresses=192.168.100.131
--fs_data_dirs=/home/like/disk1,/home/like/disk2

tserver.conf
--tserver_master_addrs=192.168.100.131:7100,192.168.100.132:7100,192.168.100.134:7100
--rpc_bind_addresses=192.168.100.131
--pgsql_proxy_bind_address=192.168.100.131:5433
--cql_proxy_bind_address=192.168.100.131:9042
--enable_ysql=true
--fs_data_dirs=/home/like/disk1,/home/like/disk2
master and node start successful
by when i try connect  psql throw this error 

[like@ambariagent131 yuga]$ bin/psql -h 192.168.100.131
psql: FATAL:  Not found: Error loading table with oid 1260 in database with oid 1: The object does not exist: table_id: "000000010000300080000000000004ec"

**Comment by ndeodhar** [comment]
Hi @likenamehaojie, this is because YSQL has not been initialized on the cluster.
Can you please add —enable_ysql=true gflag also to your master.conf while creating cluster?

Looks like our docs here have that flag specified In the manual command but we’ve missed adding it to the flag file: https://docs.yugabyte.com/latest/deploy/manual-deployment/start-masters/

**Comment by likenamehaojie** [comment]
when i add add —enable_ysql=true gflag also to my master.conf  id cant vist 7000 webui

**Comment by likenamehaojie** [comment]
@ndeodhar i can connect psql but 
Why yugabyte is slow

i use navicat client but very slow

**Comment by likenamehaojie** [comment]
It took 14 seconds to create a table.
@ndeodhar @kmuthukk @yugabyte-ci 
![image](https://user-images.githubusercontent.com/9814110/67546486-19ce8800-f72f-11e9-9d3b-a4e9800d1bab.png)
It took 14 seconds to create a table.

**Comment by likenamehaojie** [comment]
@ndeodhar @kmuthukk 
when i try install epel-release ntp  
after install 
i found new error 
psql: FATAL:  Not found: Table 000030a90000300080000000000004eb not found in Raft group 0000000000000000000000000000000

**Comment by likenamehaojie** [comment]
every thing work well
