### ISSUE TITLE
[Platform] yb_backup script fails if it cannot find a specific line during create snapshot

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#2723]
yb_backup script seem to be looking for specific string, when it runs the create snapshot call, which fails if the command outputs more data. We need to fix the script to handle this better.

the script was expecting 
`Started snapshot creation: 6664a1b0b222494996682bfb763db783` in the output but when it got
`Started snapshot creation: 6664a1b0b222494996682bfb763db783
I1025 11:53:32.076886 28385 rpc.cc:294] Waiting calls: 1` that broke the script.

**Comment by bmatican** [comment]
@OlegLoginov Was this something we fixed? I recall you had some work for this, but maybe wasn't tagged to the issue?

**Comment by bmatican** [comment]
Confirmed offline with @oleg, this was fixed in c8b055939e98514d6eb0bd51dfb58726287926fc
