### ISSUE TITLE
[YCQL] Testing JSONB Index Feature

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#2731]
Jira Link: [DB-4691](https://yugabyte.atlassian.net/browse/DB-4691)
The JSONB INDEX feature has been added, but some of its tests haven't been landed.

For more information, please see issue #741 .

**Comment by m-iancu** [comment]
Closing this as we have since added a number of json index tests. For instance those in: https://github.com/yugabyte/yugabyte-db/blob/master/java/yb-cql/src/test/java/org/yb/cql/TestJsonIndex.java
