### ISSUE TITLE
NULL value for clustering PK column causes driver to keep retrying

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#2737]
Test Case:
   https://gist.github.com/kmuthukk/679fb30fd6e85a042a12a6f1801ec31e

Server side spews these logs:
```
E1026 05:48:01.662915 24239 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
INSERT INTO users (id, name, age, info) VALUES (?, ?, ?, ?)
       ^^^^
E1026 05:48:01.664660 24243 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
INSERT INTO users (id, name, age, info) VALUES (?, ?, ?, ?)
       ^^^^
E1026 05:48:01.666515 24210 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
INSERT INTO users (id, name, age, info) VALUES (?, ?, ?, ?)
       ^^^^
E1026 05:48:01.668241 24270 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
INSERT INTO users (id, name, age, info) VALUES (?, ?, ?, ?)
       ^^^^
E1026 05:48:01.670017 24224 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
INSERT INTO users (id, name, age, info) VALUES (?, ?, ?, ?)
       ^^^^
```

The retries seem to be coming from the client-driver, but I think the issue is on the server-side. We think the server-side is returning a retryable error code for this type of error when this error is not really retryable.

**Comment by kmuthukk** [comment]
Slack discussion:

@m-iancu wrote:

I think the null error is caught (as expected) in ColumnArgsToPB: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/yql/cql/ql/exec/eval_col.cc#L62

But then, for the insert case it ends up in: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/yql/cql/ql/exec/executor.cc#L1076


The latter seems to treat all statuses that are not kNotSupported are retryable.
I did not test but believe that could be the issue. (edited) 


@kmuthukk wrote:

I see. And so driver keeps retrying. I do see the python program is a lot busier CPU wise -- telling me that the loop is coming back from the driver and not internal on the yb-tserver.


@m-iancu wrote:

For the other places where ColumnArgsToPB is called (e.g. https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/yql/cql/ql/exec/executor.cc#L1198) it seems we always return INVALID_ARGUMENTS (retryable).
So perhaps that check in the insert case (to return invalid request for not supported errors) was a fix for one previous issues we hit like this, but that did not end up fixing all cases. (edited) 


@kmuthukk wrote:

The comment there says:
```
 // Note: INVALID_ARGUMENTS is retryable error code (due to mapping into STALE_METADATA),
 //       INVALID_REQUEST - non-retryable.
```
There are some that need to be retried once internally on the server itself... if for example the table definition had changed such that this was no longer even a PK column. But after 1 internal attempt, if it still failed, I think if we were to push this back to the client as non-retryable - that would be the right thing.

@m-iancu wrote:

Yes, I think we have a mechanism for retrying on the server itself at most once (I know @Amitanand Aiyer had recently looked at that in the context of the backfill work cause he hit that). But that’s mostly for the parser stage as far as I remember.

**Comment by OlegLoginov** [comment]
Similar issue:  https://github.com/yugabyte/yugabyte-db/issues/2116
Fix:  https://github.com/yugabyte/yugabyte-db/commit/7c765275b4328402bcea634a2e805949584596cb

**Comment by OlegLoginov** [comment]
Error point:
```
Status CQLMessage::QueryParameters::GetBindVariable(const std::string& name,
                                                    const int64_t pos,
                                                    const shared_ptr<QLType>& type,
                                                    QLValue* value) const {
  const Value* v = nullptr;
  if (!value_map.empty()) {
    const auto itr = value_map.find(name);
    if (itr == value_map.end()) {
      return STATUS_SUBSTITUTE(RuntimeError, "Bind variable \"$0\" not found", name);
    }
    v = &values.at(itr->second);
  } else {
.......
  switch (v->kind) {
    case Value::Kind::NOT_NULL: {
......
    case Value::Kind::NOT_SET:        <<<<<<<
      break;
  }
  return STATUS_SUBSTITUTE(
      RuntimeError, "Invalid bind variable kind $0", static_cast<int>(v->kind));        <<<<<<
}
```

**Comment by OlegLoginov** [comment]
Call stack:
```
F20191026 11:39:36 ../../src/yb/yql/cql/ql/ptree/process_context.cc:182] SQL Error: Null Argument for Primary Key
INSERT INTO users (id, name, age, info) VALUES (?, ?, ?, ?)
       ^^^^
    @        0x109f30500  google::LogDestination::LogToSinks()
    @        0x109f2f50b  google::LogMessage::SendToLog()
    @        0x109f2feb5  google::LogMessage::Flush()
    @        0x109f349bf  google::LogMessageFatal::~LogMessageFatal()
    @        0x109f30ea9  google::LogMessageFatal::~LogMessageFatal()
    @        0x105d6ed44  yb::ql::ProcessContextBase::Error()
    @        0x105d6f13c  yb::ql::ProcessContextBase::Error()
    @        0x105d6f1d6  yb::ql::ProcessContextBase::Error()
    @        0x1058d7fae  yb::ql::Executor::ColumnArgsToPB()
    @        0x1058f55fd  yb::ql::Executor::ExecPTNode()
    @        0x1058f1e6b  yb::ql::Executor::ExecTreeNode()
    @        0x1058f0b76  yb::ql::Executor::Execute()
    @        0x1058f0a06  yb::ql::Executor::ExecuteAsync()
    @        0x10586db3a  yb::ql::QLProcessor::ExecuteAsync()
    @        0x1058692af  yb::ql::Statement::ExecuteAsync()
    @        0x104da3a58  yb::cqlserver::CQLProcessor::ProcessRequest()
    @        0x104da2889  yb::cqlserver::CQLProcessor::ProcessCall()
    @        0x104dc468d  yb::cqlserver::CQLServiceImpl::Handle()
    @        0x108ba686c  yb::rpc::ServicePoolImpl::Handle()
    @        0x108b4ba76  yb::rpc::InboundCall::InboundCallTask::Run()
    @        0x108bb43a0  yb::rpc::(anonymous namespace)::Worker::Execute()
    @        0x1096f0e1e  yb::Thread::SuperviseThread()
    @     0x7fff6f403305  _pthread_body
```

**Comment by kmuthukk** [comment]
Uploading results from memory profile when we noticed memory growth due to these repeated retries when a NULL value is provided for a clustering column of the primary key.

 `~/tserver/bin/yb-prof.py --profile http://10.0.0.218:9000/pprof --output_file_prefix=/tmp/prof --seconds=20`

[memprof.zip](https://github.com/yugabyte/yugabyte-db/files/3792132/memprof.zip)

**Comment by OlegLoginov** [comment]
Fixed by the commit above.

**Comment by OlegLoginov** [comment]
I've closed the issue as the mentioned bug was fixed.
For the noticed memory growth (potential memory leak) I've created a separate issue: https://github.com/yugabyte/yugabyte-db/issues/2813
