### ISSUE TITLE
lower consensus_max_batch_size_bytes default further

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#2739]
When a TServer restarts (say after 1 minute) all tablets on that TServer try to catch up from their leaders. The UpdateConsensus RPCs with default 32MB from the leaders happening concurrently for 100s of tablets can cause unnecessary memory spikes, timeouts and wasteful retries.  Setting this to a more conservative value like 2MB should be good enough in practice, and help in the near-term till additional/better auto-throttling is put in.

**Comment by bmatican** [comment]
Default is now 4mb.
