### ISSUE TITLE
[YSQL] Support SKIP LOCKED locking option in SELECT ... FOR UPDATE statement

### ISSUE THREAD

**Issue by lhotari** [yugabyte/yugabyte-db#2742]
For implementing work queues with a database, it's important that the database supports "SKIP LOCKED" locking option in a SELECT .. FOR UPDATE statement. (Issue for SELECT .. FOR UPDATE is #1199)

PostgreSQL also supports  ["NOWAIT" and "SKIP LOCKED" options for "SELECT ... FOR UPDATE"](https://www.postgresql.org/docs/11/sql-select.html#SQL-FOR-UPDATE-SHARE) .

The utility of "SKIP LOCKED" is explained in this article: https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/

Besides PostgreSQL, "SKIP LOCKED" option is also supported in MySQL, MS SQL Server and Oracle. It will be hard to port applications relying on the "SKIP LOCKED" lock option to YugaByte when YB lacks this support.

**Comment by mme-private** [comment]
Is there any progress on SKIP LOCKED?
