### ISSUE TITLE
SET default_transaction_isolation handling incorrect within a session

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2746]
It looks like `SET default_transaction_isolation` handling is incorrect within a session.

To explain with an example:
In YB 2.0.1, foreign keys only work in serializable mode.

```
create table pk(a int primary key);
create table fk(a int primary key, b int references pk(a));

insert into pk values(1), (2);

yugabyte=# insert into fk values(3,1); 
ERROR:  Operation only supported in SERIALIZABLE isolation level  (....=> Expected)
HINT:  See https://github.com/YugaByte/yugabyte-db/issues/1199. Click '+' on the description to raise its priority
yugabyte=# set default_transaction_isolation='serializable';
SET
yugabyte=# insert into fk values(3,1); (.... => Expected because isolation is serializable)
INSERT 0 1
yugabyte=# set default_transaction_isolation='read committed';
SET
yugabyte=# show default_transaction_isolation;
 default_transaction_isolation 
-------------------------------
 read committed
(1 row)

yugabyte=# insert into fk values(4,1);
INSERT 0 1 (.... => Unexpected behavior. We should have seen the isolation error like above)
```

**Comment by d-uspenskiy** [comment]
`ERROR:  Operation only supported in SERIALIZABLE isolation level` is raised by the `IsYBForeignKeyConstraint` function. And this function is called when plan is being created.
As a result after first successful insert all further inserts will not raise the error (plan already exists and current isolation level is not checked)

**Comment by d-uspenskiy** [comment]
@ndeodhar 

Should not it be just closed? For now there is no check in query plan building process so we should not invalidate this plan. As it will be valid after changing transaction isolation level.

**Comment by m-iancu** [comment]
Closing since this works correctly now (in both serializable and repeatable read isolation levels).
