### ISSUE TITLE
YugaByte DB does not support Pgrepack extension

### ISSUE THREAD

**Issue by dodilp** [yugabyte/yugabyte-db#2777]
Pgrepack is used when you have a table where large amount of rows have been deleted. This leads to a lot of empty spaces within the table which might affect query execution. This extensions re-orgs and re-packs the table to avoid such issues.

YugaByte DB should consider supporting the Pgrepack extension.

**Comment by ndeodhar** [comment]
@dodilp Since we don't use postgres storage and use DocDB, this does not apply directly to us. DocDB has compactions which takes care of this.
