### ISSUE TITLE
Missing port 5433 config while creating YB cluster on GCP.

### ISSUE THREAD

**Issue by ankitsigroha** [yugabyte/yugabyte-db#2782]
The yb cluster when created following instructions from ```https://docs.yugabyte.com/v1.2/deploy/public-clouds/gcp/``` isn't accessible from outside the cluster as there's no configurations to connect to the cluster using port 5433 by the loadbalancer. 

eg: Trying to connect DBeaver to yb cluster in GKE.

**Comment by iSignal** [comment]
@ankitsigroha : you could use a kubernetes spec like 

https://gist.githubusercontent.com/iSignal/791e89a21e7ad28df0e1f828b0c061c1/raw/5e15c3e18df20c8ce1e82131eafcfc4b37f1ee17/yugabyte-statefulset-loadbalancer.yaml

which adds a LoadBalancer service to the latest yugabyte-statefulset.yaml file. That way, you could then point DBeaver at the EXTERNAL-IP (port 5433) generated for the load balancer yb-tserver-client (kubectl get services should show this). 

Let me know if this approach works.

cc: @Arnav15

**Comment by ankitsigroha** [comment]
> @ankitsigroha : you could use a kubernetes spec like
> 
> https://gist.githubusercontent.com/iSignal/791e89a21e7ad28df0e1f828b0c061c1/raw/5e15c3e18df20c8ce1e82131eafcfc4b37f1ee17/yugabyte-statefulset-loadbalancer.yaml
> 
> which adds a LoadBalancer service to the latest yugabyte-statefulset.yaml file. That way, you could then point DBeaver at the EXTERNAL-IP (port 5433) generated for the load balancer yb-tserver-client (kubectl get services should show this).
> 
> Let me know if this approach works.
> 
> cc: @Arnav15
@iSignal Thanks for the support. This worked in adding a load balancer yb-tserver-client as you said and now I'm able to connect with DBeaver.
