### ISSUE TITLE
After bi-directional CDC repl setup - can not query new records with "=" on consumer but can with like '%%'

### ISSUE THREAD

**Issue by verzlo** [yugabyte/yugabyte-db#2796]
testing new CDC 2DC bi-directional replication and observed odd behaviour on YSQL schema where after setting up replication both ways for a dozen of tables, tested and confirmed that replication is working ( see increase on row count on consumer table when inserting new rows on producer) but when trying to query that new record on consumer by PK column - getting no rows found, BUT can see it if I use like '%value%'..
Row can be queried on producer with = filter just fine..
No errors observed on the t-server logs.
```
Example:
Producer:
CMS=# select username from authlog where username='sf_lockout_trader001';
      username
----------------------
sf_lockout_trader001
(1 row)
Consumer:
CMS=# select username from authlog where username='sf_lockout_trader001';
username
----------
(0 rows)
BUT this shows this record:
CMS=# select username from authlog where username like '%sf_lockout_trader001%';
      username
----------------------
sf_lockout_trader001
(1 row)
```

**Comment by verzlo** [comment]
I went back to the table DDL - and want to update this ticket with a comment that this table did not have a PK defined - but have an index defined for username column.
Here is table DDL for simulation 
CREATE TABLE AuthLog (
   Username varchar(256),
   LoginDomain varchar(256),
   Created timestamp,
   Browser varchar(256),
   ClientAppType varchar(256),
   ClientVersion varchar(256),
   CountryRegion varchar(256),
   FailureDetails varchar(256),
   IPAddress varchar(256),
   Lockout boolean,
   LockoutExpiration timestamp,
   Model varchar(256),
   OperatingSystem varchar(256),
   PrivateLabel varchar(256),
   Result int,
   Suspicious boolean,
   Type int
);

CREATE INDEX AuthLog_Username_Idx ON AuthLog (Username);

CREATE INDEX AuthLog_Created_Idx ON AuthLog (Created);

**Comment by verzlo** [comment]
Also I tried to drop/re-create this index - but ran into this problem and now stuck..

CMS=# drop index Login_Username_Idx;
ERROR:  cache lookup failed for index 16392
CMS=# drop index Login_Username_Idx;
ERROR:  index "login_username_idx" does not exist
CMS=# CREATE INDEX Login_Username_Idx ON Login (Username);



ERROR:  duplicate key value violates unique constraint "login_username_idx"
CMS=#
CMS=#
CMS=#
CMS=# exit
[root@klxcasst1 ~]# $YUGABYTE_HOME/bin/ysqlsh -h klxcasst1 -U yugabyte -d yugabyte
Password for user yugabyte:
ysqlsh (11.2-YB-2.0.1.0-b0)
Type "help" for help.

yugabyte=# \c CMS
FATAL:  cache lookup failed for index 16443
Previous connection kept
yugabyte=# exit
[root@klxcasst1 ~]# $YUGABYTE_HOME/bin/ysqlsh -h klxcasst1 -U yugabyte -d yugabyte
Password for user yugabyte:
ysqlsh (11.2-YB-2.0.1.0-b0)
Type "help" for help.

yugabyte=# \c CMS
FATAL:  cache lookup failed for index 16443
Previous connection kept
yugabyte=#

**Comment by verzlo** [comment]
update - I also noticed the same issue on other tables ( where we can not select values via index - but could not it with like so I decided to drop/recreate index on one of the tables - but then got error and can no longer connect to that database . 
See example below. 
CMS=# drop index Login_Username_Idx;
ERROR:  cache lookup failed for index 16392
CMS=# drop index Login_Username_Idx;
ERROR:  index "login_username_idx" does not exist
CMS=# CREATE INDEX Login_Username_Idx ON Login (Username);
ERROR:  duplicate key value violates unique constraint "login_username_idx"
CMS=#
CMS=#
CMS=#
CMS=# exit
[root@klxcasst1 ~]# $YUGABYTE_HOME/bin/ysqlsh -h klxcasst1 -U yugabyte -d yugabyte
Password for user yugabyte:
ysqlsh (11.2-YB-2.0.1.0-b0)
Type "help" for help.
yugabyte=# \c CMS
FATAL:  cache lookup failed for index 16443
Previous connection kept

I also tried to restart all tservers - but that did not clear the cache error. Logs after restart attached for reference.
[yb-logs.zip](https://github.com/yugabyte/yugabyte-db/files/3798440/yb-logs.zip)

**Comment by ndeodhar** [comment]
@verzlo About the `like` vs `=` query: you're seeing the difference in behavior due to the secondary index. While setting up replication, you also need to specify the table ID of the index table being replicated. (We should call this out explicitly in our instructions cc: @stevebang).

If the secondary index is not replicated, it won't have the data needed to answer the query, resulting in an inconsistent state. The `like` query works because it does a seq scan on the base table which has the data. You can confirm this by using `explain` and checking the query plans for the two statements.

**Comment by verzlo** [comment]
Got it. thanks.
