### ISSUE TITLE
[docdb] Ensure master FlushManager access is protected by ScopedLeaderLock

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2797]
Technically, yb-admin finds the master leader before sending the request. However, in transition, you might still hit a follower and get this:

`F1028 21:21:08.009812 22723 flush_manager.cc:70] Check failed: ts_tablet_map.size() > 0 (0 vs. 0)`

Example flush command: `./bin/yb-admin -master_addresses 127.0.0.2:7100 flush_table ybdemo_keyspace cassandrakeyvalue`

cc @rajukumaryb

**Comment by ericaguthan** [comment]
Hello! I would like to work on this issue, is it still available? Thanks!

**Comment by bmatican** [comment]
hey @ericaguthan , thanks for the interest here, but seems like this issue might be already solved, so I'm closing this for now.
```
BOOST_PP_SEQ_FOR_EACH(
    MASTER_SERVICE_IMPL_ON_LEADER_WITH_LOCK, FlushManager,
    (FlushTables)
    (IsFlushTablesDone));
```
