### ISSUE TITLE
Enable tservers to look up master addresses from Kubernetes master service cname

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#28]
Currently we specify the actual pod names for the `tserver_master_addrs` parameter in tservers:
`--tserver_master_addrs=master-0.yb-masters.default.svc.cluster.local:7100,master-1.yb-masters.default.svc.cluster.local:7100,master-2.yb-masters.default.svc.cluster.local:7100`

We should let this be just the cname of the master service:
`yb-masters.default.svc.cluster.local`

**Comment by ttyusupov** [comment]
Server-side changes: https://phabricator.dev.yugabyte.com/D4012
Kubernetes config file changes: https://github.com/YugaByte/yb-deploy/pull/2
