### ISSUE TITLE
[docdb] Endpoint /threadz seems broken

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2800]
Most stacks seem to show as stuck in some form of PosixRWFile call
```
    @     0x7fa78419588f  (unknown)
    @     0x7fa784248f92  re_node_set_add_intersect
    @     0x7fa785797d47  (unknown)
    @     0x7fa78579a621  ev_sleep
    @     0x7fa786283838  (unknown)
    @     0x7fa785c73442  yb::(anonymous namespace)::PosixRWFile::Sync()
    @     0x7fa784349fc3  (unknown)
    @     0x7fa7842489bc  build_trtable
    @ 0xffffffffffffffff  (unknown)
```

Could the recent gcc8 changes have affected this?

**Comment by mbautin** [comment]
What build is this on? We should still be using GCC 5.5 for official release builds, although we've upgraded Linuxbrew to a more recent version. We have GCC 5.5 and GCC 8 both available in Linuxbrew now, with GCC 8 only being activated using a special "gcc8" compiler type.

**Comment by mbautin** [comment]
I still get reasonable stack traces in /threadz in my recent development build (fully rebased).
![image](https://user-images.githubusercontent.com/552936/67916883-7a592d00-fb54-11e9-9690-a274d060b94e.png)
