### ISSUE TITLE
add log options to reference pages yb-tserver yb-master

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#2803]
Add flag from: https://docs.yugabyte.com/latest/troubleshoot/nodes/check-logs/#logs-management

To: 
https://docs.yugabyte.com/latest/admin/yb-master/#logging-options
https://docs.yugabyte.com/latest/admin/yb-tserver/#logging-options

**Comment by stevebang** [comment]
See the community issue for more context: https://forum.yugabyte.com/t/yugabyte-log-rotation/523/2
