### ISSUE TITLE
Truncate fails after add_node, problem on bootstraping

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#2804]
Jira Link: [DB-1335](https://yugabyte.atlassian.net/browse/DB-1335)
Steps:
1. `./yb-ctl create`
2. `create keyspace oesophagus_test;`
3. execute go script several times, it works
4. `./yb-ctl add_node`
5. execute go script several times, fails

Logs attached.

[script.zip](https://github.com/yugabyte/yugabyte-db/files/3794471/script.zip)
[master-logs.zip](https://github.com/yugabyte/yugabyte-db/files/3794473/master-logs.zip)
[tserver1-logs.zip](https://github.com/yugabyte/yugabyte-db/files/3794474/tserver1-logs.zip)
[tserver2.zip](https://github.com/yugabyte/yugabyte-db/files/3794475/tserver2.zip)

**Comment by bmatican** [comment]
```
I1031 14:57:08.528684 15823 catalog_manager.cc:2563] Servicing TruncateTable request from 127.0.0.1:41407: table_ids: "d2a727d6616f4d10bf7483b4b3bcb884"
E1031 14:57:08.528761 15823 substitute.cc:56] strings::Substitute format string invalid: asked for "$1", but only 1 args were given.  Full format string was: "The object with id $1 does not exist".
```

This seems in the same ballpark as #1632. @OlegLoginov can you take a look at these? Why is the `CreateTable` not waiting for the table to be ready? Why can creating the index come in, but not have accurate base table data? Could this be similar to #2475 ?
