### ISSUE TITLE
[itest] Investigate sample apps output processing stall

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2806]
Seems like after some recent changes, the java apps don't get stopped properly and we don't end up parsing the (full?) output.

> 2019-10-31 05:31:11,900 perf_utils.py:119 INFO Checked 100 lines so far.

Should we just dump the full output to some temp files and inspect them after terminate/kill?

cc @Arnav15 @iSignal

**Comment by iSignal** [comment]
Fixed by reverting
