### ISSUE TITLE
During rolling upgrades, upgrade non-leader masters first

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2815]
@rao-vasireddy mentioned that during upgrades this reduces the number of master failovers.

**Comment by kmuthukk** [comment]
This was already implemented I believe by @daniel-yb .

**Comment by daniel-yb** [comment]
+1 to comment by @kmuthukk . https://github.com/yugabyte/yugabyte-db/issues/2168, https://github.com/yugabyte/yugabyte-db/issues/2322, and https://github.com/yugabyte/yugabyte-db/issues/2324 should have handled this.
