### ISSUE TITLE
[YSQL] Serializable isolation SELECT, INSERT, SELECT inconsistency

### ISSUE THREAD

**Issue by jj-kim** [yugabyte/yugabyte-db#2823]
A serializable isolation transaction may produce inconsistent results in face of intermediate `INSERT`s.

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int)` | |
| `BEGIN ISOLATION LEVEL SERIALIZABLE` | |
| \<stmt\> | |
| | `INSERT INTO t VALUES (1)` |
| \<stmt\> | |
| `COMMIT` | |

| \<stmt\> | PostgreSQL 11 | Yugabyte |
| --- | --- | --- |
| `SELECT * FROM t` | 0 rows; 0 rows | 0 rows; 1 row |
| `SELECT i FROM t WHERE i = 1` | 0 rows; 0 rows | 0 rows; 1 row |
| `SELECT i FROM t WHERE i > 0` | 0 rows; 0 rows | 0 rows; 1 row |
| `SELECT i FROM t` | 0 rows; 0 rows | 0 rows; 1 row |

Substituting the `INSERT` with `DELETE` or `UPDATE` causes serialization errors.  See related issue #2698.

**Comment by jj-kim** [comment]
Here is another case.

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int)` | |
| `INSERT INTO t VALUES (1)` | |
| `BEGIN ISOLATION LEVEL SERIALIZABLE` | |
| \<stmt\> | |
| | `INSERT INTO t VALUES (2)` |
| \<stmt\> | |
| `COMMIT` | |

| \<stmt\> | PostgreSQL 11 | Yugabyte |
| --- | --- | --- |
| `SELECT * FROM t` | 1 row; 1 row | 1 row; 2 rows |
| `SELECT i FROM t WHERE i = 1` | 1 row; 1 row | 1 row; 1 row |
| `SELECT i FROM t WHERE i = 2` | 0 rows; 0 rows | 0 rows; 1 row |
| `SELECT i FROM t WHERE i > 0` | 1 row; 1 row | 1 row; 2 rows |
| `SELECT i FROM t` | 1 row; 1 row | 1 row; 2 rows |

**Comment by kmuthukk** [comment]
Assigning to Sergei since he has a diff in progress to address this.

**Comment by jj-kim** [comment]
The phantom reads are gone, but our behavior does not match vanilla PostgreSQL.  Rather, for the most part, we fail on the second `SELECT`, and this is expected given our implementation of serializable isolation.  This outcome is similar to that of issue #2831.
