### ISSUE TITLE
yugabyte DB chart tag 2.0.2.0-b10 errImagePull

### ISSUE THREAD

**Issue by aegershman** [yugabyte/yugabyte-db#2825]
https://github.com/yugabyte/charts/blob/master/stable/yugabyte/values.yaml#L7

yugabyte chart 2.0.2 is configured to pull `2.0.2.0-b10` but that image isn't published on dockerhub https://hub.docker.com/r/yugabytedb/yugabyte/tags results in errImagePull

The latest images on dockerhub are `2.0.3.0-b7` and `2.0.1.0-b19` but no `2.0.2.0-b10`

mitigated by overriding image tag directly
```
Image:
  tag: 2.0.1.0-b19
```

**Comment by iSignal** [comment]
cba7760313f32ace07a29d6cbfbdf9a003d37d22 It is now fixed in yugabyte/charts

Thanks for pointing out the issue @aegershman!
