### ISSUE TITLE
Yugabyte fails to start in kubernetes

### ISSUE THREAD

**Issue by astrdark** [yugabyte/yugabyte-db#2828]
I have a bare metal Kubernetes installation on one node cluster with 8gb RAM and 2 core CPU. When i deploy Yugabyte via `yugabyte-statefulset-rf-1.yaml`, the pods run for a second then fail. No logs produced. No data created in mounted folders.
```
user@server:~$ kubectl get pod
NAME           READY   STATUS    RESTARTS   AGE
yb-master-0    0/1     Error     5          3m15s
yb-tserver-0   1/1     Running   5          3m19s
user@server:~$ kubectl get pod
NAME           READY   STATUS   RESTARTS   AGE
yb-master-0    0/1     Error    5          3m18s
yb-tserver-0   0/1     Error    5          3m22s
user@server:~$ kubectl get pod
NAME           READY   STATUS             RESTARTS   AGE
yb-master-0    0/1     CrashLoopBackOff   5          4m13s
yb-tserver-0   0/1     CrashLoopBackOff   5          4m17s
```

```
user@server:~$ kubectl logs pod/yb-tserver-0
user@server:~$ kubectl logs pod/yb-master-0
```

Cluster settings:
```
user@server:~$ kubectl get node
NAME     STATUS   ROLES    AGE   VERSION
server   Ready    master   39m   v1.16.2
user@server:~$ kubectl get pv
NAME     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS   REASON   AGE
pv-001   10Gi       RWO            Retain           Bound    default/datadir-yb-master-0    standard                21m
pv-002   10Gi       RWO            Retain           Bound    default/datadir-yb-tserver-0   standard                21m
user@server:~$ kubectl get pvc
NAME                   STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-yb-master-0    Bound    pv-001   10Gi       RWO            standard       21m
datadir-yb-tserver-0   Bound    pv-002   10Gi       RWO            standard       21m
user@server:~$ kubectl get statefulset
NAME         READY   AGE
yb-master    0/1     21m
yb-tserver   0/1     21m
```

**Comment by iSignal** [comment]
Hello @darkhpp , it appears that the yb-master and yb-tserver pods are in a crash loop. Could you please share logs from both these pods. You can use ```kubectl logs <podname> --previous``` if needed.

**Comment by darkhpp** [comment]
@iSignal Hello. Still nothing:
```
user@server:~$ kubectl logs yb-master-0 --previous
user@server:~$ kubectl logs yb-tserver-0 --previous
user@server:~$
```

**Comment by darkhpp** [comment]
Also found out the database doesn't work on docker via `yb-docker-ctl`:
```
user@server:~/yugabyte$ ./yb-docker-ctl create
WARNING: No swap limit support
docker run --name yb-master-n1 --hostname yb-master-n1 --privileged -p 7000:7000 --net yb-net --detach yugabytedb/yugabyte:latest /home/yugabyte/bin/yb-master --replication_factor=1 --master_addresses=yb-master-n1:7100 --rpc_bind_addresses=yb-master-n1:7100 --enable_ysql=true --fs_data_dirs=/mnt/disk0,/mnt/disk1 --yb_num_shards_per_tserver=2 --ysql_num_shards_per_tserver=2 --v=0
Adding node yb-master-n1
docker run --name yb-tserver-n1 --hostname yb-tserver-n1 --privileged -p 9000:9000 -p 9042:9042 -p 6379:6379 -p 5433:5433 --net yb-net --detach yugabytedb/yugabyte:latest /home/yugabyte/bin/yb-tserver --tserver_master_addrs=yb-master-n1:7100 --rpc_bind_addresses=yb-tserver-n1:9100 --memory_limit_hard_bytes=1073741824 --use_cassandra_authentication=false --enable_ysql=true --pgsql_proxy_bind_address yb-tserver-n1:5433 --fs_data_dirs=/mnt/disk0,/mnt/disk1 --yb_num_shards_per_tserver=2 --ysql_num_shards_per_tserver=2 --v=0
Adding node yb-tserver-n1
Error response from daemon: Container f7e5903cad6cde16b309478a1b5ff74c2c1981bb439e9da51a176df5fff30fda is not running
Error response from daemon: Container f7e5903cad6cde16b309478a1b5ff74c2c1981bb439e9da51a176df5fff30fda is not running
Error response from daemon: Container f7e5903cad6cde16b309478a1b5ff74c2c1981bb439e9da51a176df5fff30fda is not running
. . .
```

**Comment by ironsalsa** [comment]
Same here - the pods fail without giving enough time to capture logs from the StatefulSet pod. This happens in the operator, helm chart, and just applying the yaml from the repo.

**Comment by ironsalsa** [comment]
Dos anyone have a know good version to get this going? I really want to get another one deployed, but if it doesn't start anymore we don't have a path forward.

**Comment by ramkumarvs** [comment]
@ironsalsa @darkhpp do you guys want to connect with us on the community slack, so we can jump on a quick call and debug the issue? Might be faster that way. 

`https://yugabyte.com/slack`

**Comment by ramkumarvs** [comment]
@ironsalsa @darkhpp can you also share `kubectl describe pod/yb-master-0` and `kubectl describe pod/yb-tserver-0` outputs?.

**Comment by ironsalsa** [comment]
@ramkumarvs Sure - when I get more time to dig in I'll jump on Slack and we can talk. Here's what I have right now:
`helm search yugabytedb/yugabyte`
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                                 
yugabytedb/yugabyte     2.0.5           2.0.5.2-b3      YugaByte Database [...]

`helm install yugabytedb/yugabyte --namespace dbs --name yb2 -f values.yaml`
values.yaml:
```
resource.master:
    requests.cpu: 0.1
    requests.memory: 0.2Gi
resource.tserver:
    requests.cpu: 0.1

disableYsql: false
enableLoadBalancer: false

replicas:
    master: 3
    tserver: 3

partition:
    master: 0
    tserver: 0
storage:
    master:
        count: 1
        size: 10Gi
        storageClass: longhorn
    tserver:
        count: 1
        size: 10Gi
        storageClass: longhorn
```
After storage attaches, I get this event:

```
Warning | FailedPostStartHook | Exec lifecycle hook ([sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts; fi ]) for Container "yb-master" in Pod "yb-master-0_dbs(1b406210-1b88-11ea-a9c0-0022191d2683)" failed - error: command 'sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts; fi ' exited with 126: , message: "cannot exec in a stopped state: unknown\r\n"
-- | -- | --
```
Here's the full output of the commands you requested:
```
Name:           yb-master-0
Namespace:      dbs
Priority:       0
Node:           pearl/63.147.145.115
Start Time:     Tue, 10 Dec 2019 13:03:34 -0700
Labels:         app=yb-master
                chart=yugabyte
                component=yugabytedb
                controller-revision-hash=yb-master-5f6ffdc69
                heritage=Tiller
                release=ybx
                statefulset.kubernetes.io/pod-name=yb-master-0
Annotations:    cni.projectcalico.org/podIP: 10.42.0.216/32
Status:         Running
IP:             10.42.0.216
IPs:            <none>
Controlled By:  StatefulSet/yb-master
Init Containers:
  init-sysctl:
    Container ID:  docker://fdc3962d755e9ab09e0ec93db572a4cb6620f6a44f1ddd43c39f58a8f3da95bf
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:1828edd60c5efd34b2bf5dd3282ec0cc04d47b2ff9caa0b6d4f07a21d1c08084
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      sysctl -w vm.swappiness=0
      sysctl -w kernel.core_pattern="/home/yugabyte/cores/core_%e.%p"
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Dec 2019 13:04:50 -0700
      Finished:     Tue, 10 Dec 2019 13:04:50 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxhd2 (ro)
Containers:
  yb-master:
    Container ID:  docker://bdd0197ca790b042a573bc829a425aaaf8b1031e4e739983820ad5c07996e9c7
    Image:         yugabytedb/yugabyte:2.0.5.2-b3
    Image ID:      docker-pullable://yugabytedb/yugabyte@sha256:98ae680bc7e9d03f0d3b40304d137f239ddc1026aae14a2104a56971748d404e
    Ports:         7100/TCP, 7000/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /home/yugabyte/bin/yb-master
      --fs_data_dirs=/mnt/disk0
      --rpc_bind_addresses=$(HOSTNAME).yb-masters.$(NAMESPACE).svc.cluster.local
      --server_broadcast_addresses=$(HOSTNAME).yb-masters.$(NAMESPACE).svc.cluster.local:7100
      --master_addresses= yb-master-0.yb-masters.$(NAMESPACE).svc.cluster.local:7100,yb-master-1.yb-masters.$(NAMESPACE).svc.cluster.local:7100,yb-master-2.yb-masters.$(NAMESPACE).svc.cluster.local:7100
      --replication_factor=3
      --enable_ysql=true
      --metric_node_name=$(HOSTNAME)
      --memory_limit_hard_bytes=1824522240
      --stderrthreshold=0
      --num_cpus=2
      --undefok=num_cpus,enable_ysql
      --default_memory_limit_to_ram_ratio=0.85
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    132
      Started:      Tue, 10 Dec 2019 13:06:24 -0700
      Finished:     Tue, 10 Dec 2019 13:06:24 -0700
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:     2
      memory:  2Gi
    Environment:
      POD_IP:      (v1:status.podIP)
      HOSTNAME:   yb-master-0 (v1:metadata.name)
      NAMESPACE:  dbs (v1:metadata.namespace)
    Mounts:
      /mnt/disk0 from datadir0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxhd2 (ro)
  yb-cleanup:
    Container ID:  docker://c4e30cb346ed26d26aa398d75d515374bb1959db497c717e935db60592a2912e
    Image:         busybox:1.31
    Image ID:      docker-pullable://busybox@sha256:1303dbf110c57f3edf68d9f5a16c082ec06c4cf7604831669faf2c712260b5a0
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      mkdir /var/spool/cron; mkdir /var/spool/cron/crontabs; echo "0 0 * * * /home/yugabyte/scripts/log_cleanup.sh" | tee -a /var/spool/cron/crontabs/root; crond; while true; do
        sleep 86400;
      done
      
    State:          Running
      Started:      Tue, 10 Dec 2019 13:04:54 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      USER:  yugabyte
    Mounts:
      /home/yugabyte/ from datadir0 (rw,path="yb-data")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxhd2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir0:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir0-yb-master-0
    ReadOnly:   false
  default-token-wxhd2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wxhd2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        3m17s (x5 over 3m25s)  default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               3m8s                   default-scheduler        Successfully assigned dbs/yb-master-0 to pearl
  Warning  FailedAttachVolume      2m53s                  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1b3f75fa-1b88-11ea-a9c0-0022191d2683" : attachment timeout for volume pvc-1b3f75fa-1b88-11ea-a9c0-0022191d2683
  Warning  FailedAttachVolume      2m37s (x5 over 2m52s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1b3f75fa-1b88-11ea-a9c0-0022191d2683" : rpc error: code = Aborted desc = The volume pvc-1b3f75fa-1b88-11ea-a9c0-0022191d2683 is attaching
  Normal   SuccessfulAttachVolume  2m21s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-1b3f75fa-1b88-11ea-a9c0-0022191d2683"
  Normal   Pulling                 114s                   kubelet, pearl           Pulling image "busybox"
  Normal   Pulled                  113s                   kubelet, pearl           Successfully pulled image "busybox"
  Normal   Created                 113s                   kubelet, pearl           Created container init-sysctl
  Normal   Started                 112s                   kubelet, pearl           Started container init-sysctl
  Normal   Pulled                  109s                   kubelet, pearl           Container image "busybox:1.31" already present on machine
  Normal   Started                 108s                   kubelet, pearl           Started container yb-cleanup
  Normal   Created                 108s                   kubelet, pearl           Created container yb-cleanup
  Normal   Pulled                  90s (x3 over 111s)     kubelet, pearl           Container image "yugabytedb/yugabyte:2.0.5.2-b3" already present on machine
  Normal   Created                 89s (x3 over 111s)     kubelet, pearl           Created container yb-master
  Normal   Killing                 88s (x3 over 110s)     kubelet, pearl           FailedPostStartHook
  Warning  FailedPostStartHook     88s (x3 over 110s)     kubelet, pearl           Exec lifecycle hook ([sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
  cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
fi
]) for Container "yb-master" in Pod "yb-master-0_dbs(1b406210-1b88-11ea-a9c0-0022191d2683)" failed - error: command 'sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
  cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
fi
' exited with 126: , message: "cannot exec in a stopped state: unknown\r\n"
  Normal   Started  88s (x3 over 110s)  kubelet, pearl  Started container yb-master
  Warning  BackOff  87s (x3 over 106s)  kubelet, pearl  Back-off restarting failed container
```
Name:           yb-tserver-0
Namespace:      dbs
Priority:       0
Node:           pearl/63.147.145.115
Start Time:     Tue, 10 Dec 2019 13:03:27 -0700
Labels:         app=yb-tserver
                chart=yugabyte
                component=yugabytedb
                controller-revision-hash=yb-tserver-5c84f7cf99
                heritage=Tiller
                release=ybx
                statefulset.kubernetes.io/pod-name=yb-tserver-0
Annotations:    cni.projectcalico.org/podIP: 10.42.0.215/32
Status:         Running
IP:             10.42.0.215
IPs:            <none>
Controlled By:  StatefulSet/yb-tserver
Init Containers:
  init-sysctl:
    Container ID:  docker://bb7a35ecf28a260968524d8094d16c7c3b8aea9f46545653669d931cf4c7af9b
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:1828edd60c5efd34b2bf5dd3282ec0cc04d47b2ff9caa0b6d4f07a21d1c08084
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      sysctl -w vm.swappiness=0
      sysctl -w kernel.core_pattern="/home/yugabyte/cores/core_%e.%p"
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Dec 2019 13:04:38 -0700
      Finished:     Tue, 10 Dec 2019 13:04:38 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxhd2 (ro)
Containers:
  yb-tserver:
    Container ID:  docker://0aec827062f9ff186de2d3ec7d3379eafddab541949ecdc79e474a610e7ed2ec
    Image:         yugabytedb/yugabyte:2.0.5.2-b3
    Image ID:      docker-pullable://yugabytedb/yugabyte@sha256:98ae680bc7e9d03f0d3b40304d137f239ddc1026aae14a2104a56971748d404e
    Ports:         7100/TCP, 9000/TCP, 6379/TCP, 9042/TCP, 5433/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /home/yugabyte/bin/yb-tserver
      --fs_data_dirs=/mnt/disk0
      --server_broadcast_addresses=$(HOSTNAME).yb-tservers.$(NAMESPACE).svc.cluster.local:9100
      --rpc_bind_addresses=$(HOSTNAME).yb-tservers.$(NAMESPACE).svc.cluster.local
      --cql_proxy_bind_address=$(HOSTNAME).yb-tservers.$(NAMESPACE).svc.cluster.local
      --enable_ysql=true
      --pgsql_proxy_bind_address=$(POD_IP):5433
      --tserver_master_addrs= yb-master-0.yb-masters.$(NAMESPACE).svc.cluster.local:7100,yb-master-1.yb-masters.$(NAMESPACE).svc.cluster.local:7100,yb-master-2.yb-masters.$(NAMESPACE).svc.cluster.local:7100
      --metric_node_name=$(HOSTNAME)
      --memory_limit_hard_bytes=3649044480
      --stderrthreshold=0
      --num_cpus=2
      --undefok=num_cpus,enable_ysql
      --use_cassandra_authentication=false
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    132
      Started:      Tue, 10 Dec 2019 13:06:26 -0700
      Finished:     Tue, 10 Dec 2019 13:06:26 -0700
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:     2
      memory:  4Gi
    Environment:
      POD_IP:      (v1:status.podIP)
      HOSTNAME:   yb-tserver-0 (v1:metadata.name)
      NAMESPACE:  dbs (v1:metadata.namespace)
    Mounts:
      /mnt/disk0 from datadir0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxhd2 (ro)
  yb-cleanup:
    Container ID:  docker://47655b7987b6562e315c47507b7245f2c9aec45706395b51475065c3650d1e5e
    Image:         busybox:1.31
    Image ID:      docker-pullable://busybox@sha256:1303dbf110c57f3edf68d9f5a16c082ec06c4cf7604831669faf2c712260b5a0
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      mkdir /var/spool/cron; mkdir /var/spool/cron/crontabs; echo "0 0 * * * /home/yugabyte/scripts/log_cleanup.sh" | tee -a /var/spool/cron/crontabs/root; crond; while true; do
        sleep 86400;
      done
      
    State:          Running
      Started:      Tue, 10 Dec 2019 13:04:47 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      USER:  yugabyte
    Mounts:
      /home/yugabyte/ from datadir0 (rw,path="yb-data")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxhd2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir0:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir0-yb-tserver-0
    ReadOnly:   false
  default-token-wxhd2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wxhd2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        4m6s (x4 over 4m11s)   default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               4m1s                   default-scheduler        Successfully assigned dbs/yb-tserver-0 to pearl
  Warning  FailedAttachVolume      3m46s                  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1b4dd316-1b88-11ea-a9c0-0022191d2683" : attachment timeout for volume pvc-1b4dd316-1b88-11ea-a9c0-0022191d2683
  Warning  FailedAttachVolume      3m30s (x5 over 3m45s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1b4dd316-1b88-11ea-a9c0-0022191d2683" : rpc error: code = Aborted desc = The volume pvc-1b4dd316-1b88-11ea-a9c0-0022191d2683 is attaching
  Normal   SuccessfulAttachVolume  3m14s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-1b4dd316-1b88-11ea-a9c0-0022191d2683"
  Normal   Pulling                 2m52s                  kubelet, pearl           Pulling image "busybox"
  Normal   Pulled                  2m51s                  kubelet, pearl           Successfully pulled image "busybox"
  Normal   Created                 2m51s                  kubelet, pearl           Created container init-sysctl
  Normal   Started                 2m50s                  kubelet, pearl           Started container init-sysctl
  Normal   Pulled                  2m45s                  kubelet, pearl           Container image "busybox:1.31" already present on machine
  Normal   Created                 2m43s                  kubelet, pearl           Created container yb-cleanup
  Normal   Started                 2m41s                  kubelet, pearl           Started container yb-cleanup
  Warning  FailedPostStartHook     2m38s                  kubelet, pearl           Exec lifecycle hook ([sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
  cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
fi
]) for Container "yb-tserver" in Pod "yb-tserver-0_dbs(1b4e9500-1b88-11ea-a9c0-0022191d2683)" failed - error: command 'sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
  cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
fi
' exited with 126: , message: "cannot exec in a stopped state: unknown\r\n"
  Normal   Created              2m21s (x3 over 2m48s)  kubelet, pearl  Created container yb-tserver
  Warning  FailedPostStartHook  2m20s                  kubelet, pearl  Exec lifecycle hook ([sh -c mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
  cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
fi
]) for Container "yb-tserver" in Pod "yb-tserver-0_dbs(1b4e9500-1b88-11ea-a9c0-0022191d2683)" failed - error: rpc error: code = Unknown desc = container not running (yb-tserver), message: ""
  Normal   Started  2m20s (x3 over 2m46s)  kubelet, pearl  Started container yb-tserver
  Normal   Killing  2m20s (x2 over 2m38s)  kubelet, pearl  FailedPostStartHook
  Warning  BackOff  2m9s (x4 over 2m37s)   kubelet, pearl  Back-off restarting failed container
  Normal   Pulled   114s (x4 over 2m49s)   kubelet, pearl  Container image "yugabytedb/yugabyte:2.0.5.2-b3" already present on machine
```

**Comment by iSignal** [comment]
@ironsalsa : thanks for the detailed logs. We think this could be related to #3044. This issue was fixed with the docker image yugabytedb/yugabyte:2.0.8.0-b5 - could you please try it out and let us know if that fixes your problem?

**Comment by ddorian** [comment]
Closing as no report from user.
