### ISSUE TITLE
Clean up older postgres logs

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2835]
Based on YW log retention policy, we should clean up older postgres logs. These logs are in tserver/logs folder and have the format `postgresql-%Y-%m-%d_%H%M%S.log`

**Comment by stevebang** [comment]
Logs management (https://docs.yugabyte.com/latest/troubleshoot/nodes/check-logs/#logs-management) states:

"For YSQL, we also have the additional postgres*log files. These logs have daily and size-based log rotation, that is a new log file will be created each day or a log reaches 10 MB size."

Make sure I get notified of the changes.
