### ISSUE TITLE
[YSQL] Snapshot isolation DELETE, UPDATE lost delete

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2848]
Jira Link: [DB-1457](https://yugabyte.atlassian.net/browse/DB-1457)
In this situation, a `DELETE` can get lost.

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int PRIMARY KEY, j int)` | |
| `INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)` | |
| `BEGIN ISOLATION LEVEL REPEATABLE READ` | |
| `SELECT '(setting read point)'` | |
| | `DELETE FROM t WHERE i = 2` |
| `UPDATE t SET j = j + 1` | |
| `COMMIT` | |
| `SELECT * FROM t` | |

In vanilla PostgreSQL, the `UPDATE` causes an error

```
ERROR:  could not serialize access due to concurrent update
```

and the last `SELECT` gives two rows

```
 i | j
---+----
 1 | 10
 3 | 30
(2 rows)
```

In Yugabyte, there are **no errors**, and the last `SELECT` gives three rows

```
 i | j
---+----
 1 | 11
 2 | 21
 3 | 31
(3 rows)
```

The `SELECT '(setting read point)'` is a workaround for issue #2702.

**Comment by m-iancu** [comment]
Confirmed this still happens in latest.  A minimal repro is

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int PRIMARY KEY, j int)` | |
| `INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)` | |
| `BEGIN ISOLATION LEVEL REPEATABLE READ` | |
| | `DELETE FROM t WHERE i = 2` |
| `UPDATE t SET j = 21 WHERE i = 2` | |
| `COMMIT` | |
| `SELECT * FROM t` | |

Based on my local testing, the Session B operation must be a DELETE of that form, an UPDATE or another transaction (or insert) will not hit the issue.
cc @mbautin @spolitov

**Comment by sushantrmishra** [comment]
Not able to reproduce in 2.19.3 (master). 

localhost:5433 yugabyte@yugabyte=# select version();
                                                                                                                      version
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.2-YB-2.19.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.7 (/opt/yb-build/llvm/yb-llvm-v15.0.7-yb-1-1680596282-6b9d30d8-centos7-x86_64-build/src/llvm-project/clang 6b9d30d80f5cebc66c9fa46013d18f125ea8ec0e), 64-bit
(1 row)

**Final select output:** 
localhost:5433 yugabyte@yugabyte=# SELECT * FROM t ;
 i | j
---+----
 1 | 11
 3 | 31
(2 rows)
