### ISSUE TITLE
Fix TSAN failures in CppCassandraDriverTest

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2854]

**Comment by OlegLoginov** [comment]
Some details are here:  https://github.com/yugabyte/yugabyte-db/issues/4513
(Data race on the `session_` field in the LoadBalancingPolicy.)

**Comment by OlegLoginov** [comment]
A set of issues:
https://github.com/yugabyte/yugabyte-db/issues/1837
https://github.com/yugabyte/yugabyte-db/issues/5107
https://github.com/yugabyte/yugabyte-db/issues/5108

**Comment by OlegLoginov** [comment]
Closing as duplicate of  https://github.com/yugabyte/yugabyte-db/issues/5107.
