### ISSUE TITLE
[docdb] Add --certs_dir plumbing to yb-ts-cli 

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2877]
Currently, we support `--certs_dir` for the servers, to setup TLS.
We also support `--certs_dir_name` for `yb-admin`, to be able to send secure RPCs to the servers.

We need to add support for this to `yb-ts-cli`.

See https://github.com/yugabyte/yugabyte-db/commit/9739e4a682bcddfd0f4cc9c45f63ce819936071c

**Comment by bmatican** [comment]
@srivignessh Did you want to look into this? I can assign it to you. Let me know if you'd like some more pointers on where to get started. We document how to start clusters with TLS in our docs.

One simple command you can do is try to change flag values:
> ./build/latest/bin/yb-ts-cli --server_address=$ip:9100 set_flag -force follower_unavailable_considered_failed_sec 900

This should fail if TLS is enabled on the cluster you're targeting.

**Comment by srivignessh** [comment]
@bmatican Sure. Thanks, you can assign it to me. I will work on it.  
I am able to find TLS in docs.
https://docs.yugabyte.com/latest/secure/tls-encryption/server-to-server/

Can you point me to the docs for tablet server cli ?(yb-ts-cli).

**Comment by bmatican** [comment]
@srivignessh Oh, good question, I think we do not have docs yet for `yb-ts-cli`! cc @stevebang 

I think for the purposes of this task, any command you run from it should fail without certs plumbed through, as they will all try to send RPC requests to the servers. That's why I just referenced one example command above.

Also, a useful commit for reference might be https://github.com/yugabyte/yugabyte-db/commit/9739e4a682bcddfd0f4cc9c45f63ce819936071c, which added support for `yb-admin` to use certs!
