### ISSUE TITLE
Check failed: state_ == BatcherState::kTransactionReady (kComplete vs. kTransactionReady) 

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2879]
Happens in org.yb.cql.TestAuthorizationEnforcement#testDropIndexWithAlterTablePermission

https://gist.githubusercontent.com/mbautin/f16b1edf47f808d0a24947335920ac75/raw
Full log: https://gist.githubusercontent.com/mbautin/ef229d8b8a65e1e792fcecd32f90e1c3/raw

**Comment by ndeodhar** [comment]
Also saw this during 2DC testing on the producer cluster.

**Comment by kmuthukk** [comment]
We saw another instance of this in pf-3 cluster. Looks like something recent is triggering this.

**Comment by spolitov** [comment]
Fixed by 401e821a52840892b77fb1c7dd771454ff060e7a
