### ISSUE TITLE
[Platform] Login page should trigger login when doing carriage return

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#2882]
Right now in the login page if the user hits carriage return after entering the credentials, it doesn't trigger the login. 

<img width="813" alt="login-page" src="https://user-images.githubusercontent.com/5263706/68417115-a3784f80-014a-11ea-8b39-a67f86399821.png">

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-989

**Comment by stupendoussuperpowers** [comment]
I'd like to work on this
