### ISSUE TITLE
Connect Modal doesn't show entire JDBC string 

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#2885]
The JDBC string can get quite long with the length of the DNS name, which cuts it off with no way to expand.
<img width="611" alt="Screen Shot 2019-11-07 at 2 52 47 PM" src="https://user-images.githubusercontent.com/2791412/68434725-89e8ff00-016e-11ea-8e2b-9039d6cf3383.png">

**Comment by yb-andrew** [comment]
@WesleyW I added the ability to see the entire string by hovering over the string. Also, copying lines can get the entire string. Alternatively, we could add a tooltip on the string.
