### ISSUE TITLE
[YSQL] Pick transaction id such its transaction status record's leader is local to transaction coordinator 

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2889]
In case of
```
BEGIN;
INSERT ...
...
COMMIT;
```
pick a "transaction status id" that sits on a tablet on the yb-tserver that's on the same node as the PG proxy layer that's handling the client request. This will make sure the commit  step doesn't have an extra hop to a non-local leader.

**Comment by spolitov** [comment]
Implemented as a side effect of 877a3e0afb226c18de92496d9b7ac66c8c3de2b2
