### ISSUE TITLE
[YSQL] SELECT with OR/IN over primary key don't use the index

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#2898]
[issue_2898.zip](https://github.com/yugabyte/yugabyte-db/files/3826776/issue_2898.zip)
Tests done using single Node (RF=1) cluster (YB Version 2.0.3) running on my macBook (macOS Mojave Version 10.14.6 ).

Table created like this:
```
create table t(
  k int,
  v int,
  constraint t_pk primary key(k hash))
```
I spelled out `hash` as self-doc of the default. I also tried `asc` and `desc`. Same outcomes for the query plans. The table is populated like this:
```
insert into t(k, v)
select v, v*2 from (select generate_series(1, 100000) as v) as a
```
The index `t_pk` is used for this (as shown by "explain"):
```
select v from t where k = 500
```
and (as a sanity check) for this:
```
select v from t where k in(500);
```
It's used even for this:
```
select k, v from t where k = 500
union all
select k, v from t where k = 510;
```
However, the index is _NOT_ used for this:
```
select v from t where k = 500 or k = 510
```
or for this:
```
select v from t where k in(500, 510)
```
Rather, a table scan (`Foreign Scan on t`) is used. If you modify the `insert` statement to insert 1,000,000 rows and time the queries, you'll see the obvious dramatic effect on not using the `t_pk` index.

I repeated the test using vanilla PostgreSQL. There, I just used the default fort he PK index, thus:
```
create table t(
  k int,
  v int,
  constraint t_pk primary key(k))
```
There, the plan for every query showed that the index `t_pk` is used.

Testcase uploaded as `issue_2898.zip`. Unzip and then do this st the o/s prompt:
```
ysqlsh -f yb_run_testcase.sql > yb_run_testcase.txt
```
And for PostgreSQL, do this:
```
psql ... -f pg_run_testcase.sql > pg_run_testcase.txt
```
The uploaded zipfile includes my `yb_run_testcase.txt`and `pg_run_testcase.txt`.

**Comment by frozenspider** [comment]
Pushdown of OR/IN clauses doesn't work for two reasons:

1) For `WHERE k = 500 OR k = 510`-style queries, postgres tries to do a bitmap scan:
```
yugabyte=# EXPLAIN SELECT * FROM txt WHERE id = 1 OR id = 2;
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Bitmap Heap Scan on txt  (cost=0.21..4.23 rows=1000 width=36)
   Recheck Cond: ((id = 1) OR (id = 2))
   ->  BitmapOr  (cost=0.21..0.21 rows=1 width=0)
         ->  Bitmap Index Scan on txt_pkey  (cost=0.00..0.11 rows=1 width=0)
               Index Cond: (id = 1)
         ->  Bitmap Index Scan on txt_pkey  (cost=0.00..0.11 rows=1 width=0)
               Index Cond: (id = 2)
```
...while our FDW index interface does not implement them yet. Adding a dummy implementation makes `EXPLAIN` yield correct plan, so once we implement bitmap scans, we'll get the correct plan for free.

2) For `WHERE k IN (500, 510)`-style queries it's mostly the same, although there's an additional problem of us not being able to properly calculate it's cost.
In `ybcIndexCostEstimate` we have:
```
...
/* TODO: support array search condition */
if (IsA(clause, ScalarArrayOpExpr))
    continue;
...
```
This leads to bitmap index scan being too costly to replace full scan. Again, with a bit of a dummy implementation magic `EXPLAIN` starts yielding what vanilla postgres does:
```
yugabyte=# EXPLAIN SELECT * FROM txt WHERE id IN (1, 2);
                               QUERY PLAN
-------------------------------------------------------------------------
 Bitmap Heap Scan on txt  (cost=102.75..106.76 rows=1000 width=36)
   Recheck Cond: (id = ANY ('{1,2}'::integer[]))
   ->  Bitmap Index Scan on txt_pkey  (cost=0.00..102.50 rows=1 width=0)
         Index Cond: (id = ANY ('{1,2}'::integer[]))
```

**Comment by nocaway** [comment]
Hi @frozenspider : Postgres didn't have the "hash column" concept, so its planner and optimizer don't take logical conditions on hash-columns under consideration.  Slowly, we'll introduce this "hashing" concept to Postgres code.

My suggestion would be (for now) leaving the query plan as is but optimizing the execution by sending hash values to Yugabyte for optimization.

You can see that Robert abandoned query plan optimizations for hash columns in plancat.c.  Slowly, I'm turning on optimizations for hash columns.
```
if (IsYBRelation(relation) && (opt & INDOPTION_HASH) != 0)
{
	info->sortopfamily = NULL;
	info->reverse_sort = NULL;
	info->nulls_first = NULL;
	break;
}
```

**Comment by kmuthukk** [comment]
Note: UPDATE has the same issue.

Load some data:
```
create table t (i int primary key, j int);
insert into t select generate_series(1,10000), generate_series(10001, 20000);
```

Fulls scan take about 50ms:
```
yugabyte=# select count(*) from t;
 count
-------
 10000
(1 row)

Time: 46.522 ms
```

Simple PK based updates are fast:
```
yugabyte=# update t set j = 20 where i = 87;
UPDATE 1
Time: 2.812 ms
yugabyte=# update t set j = 20 where i IN (87);
UPDATE 1
Time: 2.619 ms
```

But with multiple items in IN list, this is much slower, we appears to do a full scan with filter:

```
yugabyte=# update t set j = 20 where i IN (87, 90);
UPDATE 2
Time: 53.025 ms
yugabyte=# explain update t set j = 20 where i IN (87, 90);
                           QUERY PLAN
-----------------------------------------------------------------
 Update on t  (cost=0.00..102.50 rows=1000 width=40)
   ->  Foreign Scan on t  (cost=0.00..102.50 rows=1000 width=40)
         Filter: (i = ANY ('{87,90}'::integer[]))
(3 rows)

```

**Comment by frozenspider** [comment]
After an internal discussion, we decided to try to teach postgres planner that our index scan can handle conditions like `(id = ANY ('{1,2}'::integer[])`

**Comment by bllewell** [comment]
Adding two more `select` tests. I ran them on the same table with the same rows as is described above. I'd expect they'd behave the same if they're re-cast as `insert` tests. They use the `unnest` built-in table function to allow an array of scalars to be used respectively (1) with `in (select... from unnest(array[...]))` and (2) in a re-formulation expressed as an inner join. Both show a good outcome: the YB `explain` output is the same as the PG `explain` output.

**in-list variant**
```
explain
select v from t where k in (
  select unnest as k
  from unnest(array[500, 510, 520, 530, 540, 550]::int[]));
```
Here's the PG output:
```
 Nested Loop  (cost=1.54..733.27 rows=100 width=4)
   ->  HashAggregate  (cost=1.25..2.25 rows=100 width=4)
         Group Key: unnest.unnest
         ->  Function Scan on unnest  (cost=0.00..1.00 rows=100 width=4)
   ->  Index Scan using t_pk on t  (cost=0.29..7.31 rows=1 width=8)
         Index Cond: (k = unnest.unnest)
```
The YB output is identical except that the cost estimates differ.

**inner join variant**
```
explain
select t.v as v
from
t inner join (
  select unnest as k
  from unnest(array[500, 510, 520, 530, 540, 550]::int[])) as u
using (k);
```
Here's the PG output:
```
 Nested Loop  (cost=0.29..732.00 rows=100 width=4)
   ->  Function Scan on unnest  (cost=0.00..1.00 rows=100 width=4)
   ->  Index Scan using t_pk on t  (cost=0.29..7.31 rows=1 width=8)
         Index Cond: (k = unnest.unnest)
```
Here, too, the YB output is identical except that the cost estimates differ.

**Comment by frozenspider** [comment]
Split this issue into #3130 (`IN`) and #3131 (`OR`)

**Comment by frozenspider** [comment]
Closing this issue as OR and IN pushdown is tracked separately now (see above)
