### ISSUE TITLE
[docdb] batcher.cc Check failed: 1 == ops_.erase(op) (1 vs. 0) Could not remove op

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2902]
Saw this in a cluster during batch workload experiments:
```
F20191107 18:30:26 ../../src/yb/client/batcher.cc:649] Check failed: 1 == ops_.erase(op) (1 vs. 0) Could not remove op op[state=kRequestSent, yb_op=QL_WRITE type: QL_STMT_INSERT client: YQL_CLIENT_CQL request_id: 23954092032 schema_version: 1 .......
```

Passing to @spolitov for now, as he'd fixed a different race in e3e542e650b27b861eb3444578cf9a5ff1401274.

We might not have enough info to debug this for now though.

**Comment by spolitov** [comment]
Fixed by 401e821a52840892b77fb1c7dd771454ff060e7a
