### ISSUE TITLE
Enhance demo commands in yugabyted

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#2905]
Currently, there are some problems with `yugabyted demo`:
- Only one session of `yugabyted demo` is allowed at a time. Running multiple commands concurrently will only start the first one.
- The demo is tied to the current database being initialized. It requires `yugabyted start` to be run beforehand.
- Users may run `\c yugabyte` or some other variant to change into a permanent database and write data there, which will persist.

Instead, `yugabyted demo` should be an idempotent command, where running it multiple times will always result in a new isolated temporary database. One way to do this is by having the `demo` command create a completely separate instance of yugabyte in a private data directory/ports every time it's run.

For instance:
```
$ yugabyted demo& # creates new data directory at /tmp/yugabyte-demo-1 on port 4285
$ yugabyted demo& # creates new data directory at /tmp/yugabyte-demo-2 on port 1424
$ killall "yugabyted demo" # /tmp/yugabyte-demo-1 and /tmp/yugabyte-demo-2 are destroyed
```

**Comment by iSignal** [comment]
428c13aeb9435c5a8c98d7086e9529a03791
510d3394d927c6
