### ISSUE TITLE
[YSQL] Lack of failures on rapid row lock queries

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2910]
Jira Link: [DB-2190](https://yugabyte.atlassian.net/browse/DB-2190)
When rapidly executing statements interleaved in transactions and related to row locking, there may be cases where failures don't happen when they should.  For instance, executing the following rapidly can work (ignoring issue #2857):

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int, j int PRIMARY KEY)` ||
| `INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)` ||
| `BEGIN ISOLATION LEVEL REPEATABLE READ` ||
| `SELECT '(setting read point)'` ||
|| `BEGIN ISOLATION LEVEL REPEATABLE READ` |
|| `SELECT '(setting read point)'` |
| `SELECT * FROM t FOR UPDATE` ||
|| `SELECT * FROM t FOR UPDATE` |
| `COMMIT` ||
|| `COMMIT` |

The test function `PgMiniTest::TestRowLockConflictMatrix` encounters this, so some time between queries is added as a workaround.

**Comment by pkj415** [comment]
I think the issue doesn't exist anymore since I don't see a sleep anymore between explicit row-locking statements in `TestRowLockConflictMatrix()`.
