### ISSUE TITLE
[docs] Update Yugabyte Platform backup docs

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2926]
We need to update the new workflows for scheduled backups as well as update any older workflows that changed or look different.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-974

**Comment by stevebang** [comment]
@Arnav15 Please review the latest docs, where scheduled backups were doc'ed. If anything needs to be added relevant to this, add to the comments. Otherwise, close this issue.

**Comment by rkarthik007** [comment]
This is now available at https://docs.yugabyte.com/latest/yugabyte-platform/back-up-restore-universes/
