### ISSUE TITLE
[docdb] Expose rocksdb max_write_buffer_number as a gflag

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2935]
By default, per tablet, we only allow a max of 2 mem tables, one active and at most one pending flush. If another flush gets scheduled, you end up with 2 immutable mem tables and rocksdb stops writes. We've seen this in a couple of write heavy scenarios, but as a pretty rare event (couple of times a day, across all tablets).

It's possible, if we have a slow down on disk write, or just perhaps randomness of events coming in, that even with multiple flush threads, we fill up another mem table for a tablet, before we wrap up flushing the first one.

Since this should be pretty rare, increasing this flag default from 2 to 3 should be safe.

cc @spolitov @ttyusupov @rajukumaryb

**Comment by robertsami** [comment]
Closing in favor of https://github.com/yugabyte/yugabyte-db/issues/5580 which captures the updated requirement to bump to 10
