### ISSUE TITLE
[YSQL] cache lookup failed for type 0

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#2938]
The following simple scenario causes `cache lookup failed` error

```
postgres=# CREATE TABLE t(k int, v int, junk int);
postgres=# ALTER TABLE t DROP COLUMN junk;
postgres=# DELETE FROM t RETURNING *;
ERROR:  cache lookup failed for type 0
```

https://github.com/yugabyte/yugabyte-db/issues/1969 can be used as a reference

**Comment by ndeodhar** [comment]
@Zhongweizhao This is similar to the bug that you'd fixed for `UPDATE`. Maybe we missed adding similar check for `DELETE`.
