### ISSUE TITLE
FOR KEY SHARE causes unexpected conflict with another FOR KEY SHARE

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2939]
`FOR KEY SHARE` is used by postgres while inserting data into a table that has a foreign key reference to another table.
So, if we have two tables:
```sql
CREATE TABLE base(a int PRIMARY KEY);
CREATE TABLE reference(a int PRIMARY KEY, b int REFERENCES base(a));
```
Now, while inserting a row into ref, postgres will generate a query like
```
SELECT 1 FROM ONLY "public"."base" x WHERE "a" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x
```
If we have two inserts that are reading the same base value, then we get either "Transaction Expired" or "Transaction conflicts" error.

Here is an easy way to reproduce:
In Session 1:
```sql
INSERT INTO base VALUES(1);
BEGIN;
SELECT 1 FROM ONLY "public"."base" x WHERE "a" OPERATOR(pg_catalog.=) 1 FOR KEY SHARE OF x;
```

In session 2:
```sql
BEGIN;
SELECT 1 FROM ONLY "public"."base" x WHERE "a" OPERATOR(pg_catalog.=) 1 FOR KEY SHARE OF x;
COMMIT; -- This will sometimes fail with conflicts with higher priority transaction.
```

Back to session 1:
```sql
COMMIT; -- If COMMIT in session 2 has succeeded, then this fails with "Operation expired: Transaction expired: 25P02"
```

Two KEY SHARE locks should not conflict. For more information on postgres definition of these locks: https://www.postgresql.org/docs/12/explicit-locking.html

**Comment by jj-kim** [comment]
I will close this as a duplicate to issue #2842.  I have an upcoming fix that I tested on the above situation, and it works.

**Comment by ndeodhar** [comment]
Awesome, thanks @jj-kim !

**Comment by kmuthukk** [comment]
thx @jj-kim !
