### ISSUE TITLE
Full move stuck waiting for data migration

### ISSUE THREAD

**Issue by rahuldesirazu** [YugaByte/yugabyte-db#294]
A full move operation with RF=3 from nodes {A, B, C} -> {D, E, F} gets stuck. At a high level, this is what is happening:

1. Spin up three new nodes each with a master and tserver process.
2. The tserver on D heartbeats to master leader on A and sees masters {A, B, C}.
3. Issue a changeConfig to add the master on D to the quorum.
4. Issue a changeConfig to step down the master on A.
5. Master on A steps down as leader, master on D becomes the new leader.
6. The tserver on D heartbeats to what it thinks is the master leader on A, A responds saying its no longer the master leader.
7. The tserver on D round robins trying all the masters it knows {A, B, C}, never finding a leader since D was never advertised.

Attached are relevant log files from the nodes.

[logs.tar.gz](https://github.com/YugaByte/yugabyte-db/files/2015744/logs.tar.gz)

To fix this issue, the current proposal is to add a code path for follower masters to heartbeat back to tservers with the master quorum. When D then heartbeats to A, A, instead of just saying not the master leader, will say its no longer the master leader, and then advertise the new quorum of {A, B, C, D}.

**Comment by kmuthukk** [comment]
nice work @rahuldesirazu debugging this hard to repro issue. Looks like the workaround of restarting the TServer worked fine. And the proposed fix sounds good.

**Comment by bbaddepudi** [comment]
Another aspect we discussed, is that tserver should ideally create a union of the HB response list with its current in-memory list. This would avoid cases that could override the config/file value, causing it to miss any masters that are in the conf file. And vice-versa, if union in-memory is superset of what is on disk (if conf file is used), then we should ideally persist it for next restart.

**Comment by kmuthukk** [comment]
@bbaddepudi : What's HB - heartbeat? Might be worth just spelling it out

**Comment by bbaddepudi** [comment]
Had discussed updating server conf file offline. And here are the some recent logs, with comments about master changes done externally. This shows the behavior of a client embedded in the tserver (YCQL) proxy and proposes changes at the end.

`
I0531 05:51:16.717581 20998 client-internal.cc:1159] New master addresses: 10.9.136.107:7100,10.9.203.122:7100,10.9.68.117:7100

// Removed master 10.9.68.117 via ChangeConfig and killed it.

I0531 06:04:42.362607 20757 tablet_server.cc:167] Got new list of 2 masters at index 4990 new masters=10.9.136.107:7100,10.9.203.122:7100

// ChangeConfig add master 10.9.87.220

I0531 06:13:07.007033 20757 tablet_server.cc:167] Got new list of 3 masters at index 5580 new masters=10.9.136.107:7100,10.9.203.122:7100,10.9.87.220:7100

// Just kill master process at 10.9.136.107, which was the master leader.

I0531 17:06:07.983470 20835 client-internal.cc:1148] Reinitialize master addresses from file: /home/yugabyte/tserver/conf/server.conf
I0531 17:06:07.983813 20835 client-internal.cc:1159] New master addresses: 10.9.136.107:7100,10.9.203.122:7100,10.9.68.117:7100
`

It starts off with 3 masters, one of them (10.9.68.117) is removed and replaced with a new master (10.9.87.220), both via ChangeConfig. The tserver/client get the in-memory update of new masters correctly, so far so good. Then the master leader is plain killed. So the client code defaults to reading the tserver log file and overwrites the new info in memory with stale info from config flag file.

This shows the need to update the server conf file also with superset of master ips from memory.
