### ISSUE TITLE
Error for pg_stat_statements

### ISSUE THREAD

**Issue by dodilp** [yugabyte/yugabyte-db#2944]
CREATE EXTENSION pg_stat_statements;
_The above statement executes without errors_ 

select * from pg_stat_statements;
_I get the following error_
_SQL Error [55000]: ERROR: pg_stat_statements must be loaded via shared_preload_libraries_

I edited ysql_pg.conf, to uncomment the following variables - 
#shared_preload_libraries = ''  # (change requires restart)

Restarting the cluster, overwrites this file. 
How do I get past the error? The docs are very unclear on this.

**Comment by ndeodhar** [comment]
@dodilp This doc page has information on setting YSQL options:
https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#ysql-options

`ysql_pg.conf` is an auto generated file (See the disclaimer at top of the file which says this)  it cannot be manually edited. You can pass pg options to yb-tserver using `ysql_pg_conf` gflag.

In this case, you can do:`--ysql_pg_conf=shared_preload_libraries='pg_stat_statements'`

If you're using yb-ctl local cluster, then you can pass tserver gflags like this:
`yb-ctl restart --tserver_flags ysql_pg_conf="shared_preload_libraries='pg_stat_statements'"`

**Comment by ndeodhar** [comment]
Unfortunately, I just remembered a limitation where we don't allow users to set shared_preload_libraries. You can set other PG options using the mechanism that I've described above. However, shared_preload_libraries option cannot be used for now.
I've filed this enhancement to remove that limitation: https://github.com/yugabyte/yugabyte-db/issues/2945

**Comment by ndeodhar** [comment]
Closing this. You can track the enhancement for shared preload libraries in #2945

**Comment by dodilp** [comment]
Thank you, @ndeodhar. Can you please provide example how to use https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#ysql-options to unblock, with yb-ctl?

**Comment by ndeodhar** [comment]
@stevebang We should add an example for `ysql_pg_conf` option.
