### ISSUE TITLE
[YSQL] Investigate count(*) slowness

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2946]
Jira Link: [DB-2017](https://yugabyte.atlassian.net/browse/DB-2017)
`Select count(*) from table` on tables that have > 100K rows is about 10 times slower than PG.
We should investigate and identify areas of improvement.

Comparison was done on a local yb-ctl deployment with 2 tablets for the table.

**Comment by ndeodhar** [comment]
One difference between postgres and YB is that postgres maintains some count metadata and does not require a full table scan. This makes count(*) type of queries in postgres much faster.
We should consider having similar metadata in YB per tablet - keeping track of row count , data size per tablet per table.

**Comment by sushantrmishra** [comment]
This is to be addressed by --

1. Scan performance improvement
2. PG parallelism can also help in some scenarios
