### ISSUE TITLE
Unclear error message if master/tserver starts and data dir does not exist

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#295]
Run the following command with the `/tmp/yugabyte-local-cluster/node-1/disk-1` directory not present on the system:
```
./bin/yb-master \
    --fs_data_dirs /tmp/yugabyte-local-cluster/node-1/disk-1 \
    --webserver_interface 127.0.0.1 \
    --rpc_bind_addresses 127.0.0.1 \
    --replication_factor=3 \
    --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100
```

Error message: 
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0516 21:54:44.248008 2561577920 path_util.cc:61] Check failed: !a.empty() empty first component:
*** Check failure stack trace: ***
```

Would be good to have a more intuitive error message saying:
```
Data directory /tmp/yugabyte-local-cluster does not exist
```

**Comment by georgeklees** [comment]
Are we sure that the issue still reproduces in the latest codebase? When I run the above command as specified, I get the following error message, which is fairly intuitive:

> Not found (yb/util/env_posix.cc:1104): Unable to create FS path component /tmp/yugabyte-local-cluster/node-1/disk-1: /tmp/yugabyte-local-cluster/node-1/disk-1: No such file or directory (error 2)
