### ISSUE TITLE
[YSQL] Slow pg_depend query if index is picked when query has ORDER BY but no WHERE clause

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2959]
[Note: This is one of the queries that `ysql_dump` triggers that we should optimize.]

For pg_depend table, consider the below 2 queries

```
yugabyte=# explain SELECT classid, objid, refclassid, refobjid, deptype FROM pg_depend WHERE deptype != 'p' AND deptype != 'e' ORDER BY classid, objid, objsubid;
                                           QUERY PLAN
------------------------------------------------------------------------------------------------
 Index Scan using pg_depend_depender_index on pg_depend  (cost=0.00..109.02 rows=1000 width=21)
   Filter: ((deptype <> 'p'::"char") AND (deptype <> 'e'::"char"))
(2 rows)

Time: 0.390 ms
yugabyte=# explain SELECT classid, objid, refclassid, refobjid, deptype FROM pg_depend WHERE deptype != 'p' AND deptype != 'e';
                            QUERY PLAN
-------------------------------------------------------------------
 Foreign Scan on pg_depend  (cost=0.00..105.00 rows=1000 width=17)
   Filter: ((deptype <> 'p'::"char") AND (deptype <> 'e'::"char"))
(2 rows)

Time: 0.417 ms
```

First query has an order by clause and we pick index scan during query plan. This causes the query to be very inefficient because we retrieve the rows from index and then query the base table once per row. We saw this query take ~8 sec on @kmuthukk 's setup.

Second query does not have an order by clause and so we do a base table scan, which is much fast and took about 85 ms.

This can benefit from cost based query optimization.

**Comment by ndeodhar** [comment]
Difference in speed between using the index and doing a sequence scan is significant.
With ORDER BY clause and index, it took 5.3 seconds.
Without ORDER BY clause and full scan, it took 79 ms. Note that this will increase some more with postgres doing the sort but the increase should be fairly small.

**Comment by nocaway** [comment]
This has been fixed.
