### ISSUE TITLE
[ycql] add support for system.size_estimates system table in YugaByte YCQL

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#296]
When running Presto against YugaByte, the following error is seen. This was reported [here](https://forum.yugabyte.com/t/presto-yugabyte-connector-cassandra-version-issue/157).

```
com.facebook.presto.spi.PrestoException: Cassandra versions prior to 2.1.5 are not supported
```

The presto cassandra connector relies on the `system.size_estimates` Cassandra system table to make decisions about the partitions of a user table and sizes of these partitions, and [when it doesn't find the size_estimates table](https://github.com/prestodb/presto/blob/c421c3efe4d32bf5823bc262be402825fe0937ec/presto-cassandra/src/main/java/com/facebook/presto/cassandra/NativeCassandraSession.java#L462) it assumes it is talking to an older version of Cassandra.

**Comment by m-iancu** [comment]
Closed by 828e1c0944fdea2aee3d3008582147a3bd86cc75.
