### ISSUE TITLE
Yugabyte uses the hostname for networking 

### ISSUE THREAD

**Issue by MarkArts** [yugabyte/yugabyte-db#2962]
I'm running into problems where it seems like yugabyte tries to communicate with other instances by hostname of a server which in our case wouldn't be possible, our hostnames aren't valid addresses and i would prefer getting it to work on public ip's for flexibility (and possible different subnets).

I will be sharing the relevant parts of our Ansible config but it's basically `docker run` with command flags.

I run the master and tablet servers in docker containers and the master seems to work as expected

This is how the master is started
```yaml
    docker_container:
      name: yb-master
      image: yugabytedb/yugabyte:latest
      command: "/home/yugabyte/bin/yb-master
        --logtostderr
        --fs_data_dirs=/mnt/disk0
        --master_addresses={{ master_adresses }}
        --replication_factor=3
        --rpc_bind_addresses=0.0.0.0:7100
        --webserver_interface=0.0.0.0
        --webserver_port=7000
        --server_broadcast_addresses={{ hostvars[inventory_hostname]['ec2_ip_address'] }}:7100
      "
      ports:
      - 7000:7000
      - 7100:7100
```

`{{ hostvars[inventory_hostname]['ec2_ip_address'] }}` is the public available ip of the server the docker image runs on.

I have the following setup for the tablet servers working in docker host mode, here we an bind to the private ip of the servers. (fyi: port 9100 is used by prometheus on the server so we use port 9101 for the rpc):
```yaml
    docker_container:
      name: yb-tserver
      image: yugabytedb/yugabyte:latest
      command: "/home/yugabyte/bin/yb-tserver
        --logtostderr
        --fs_data_dirs=/mnt/disk0
        --tserver_master_addrs={{ master_adresses }}
        --rpc_bind_addresses={{ hostvars[inventory_hostname]['ec2_private_ip_address'] }}:9101
        --webserver_interface=0.0.0.0
        --webserver_port=9000
        --server_broadcast_addresses={{ hostvars[inventory_hostname]['ec2_ip_address'] }}:9101"
      network_mode: host
```
`{{ hostvars[inventory_hostname]['ec2_private_ip_address'] }}` is the private ip address of the server the docker container runs on and reachable by other servers because it runs in host mode.

Now if i chance the rpc_bind_adresses to be `0.0.0.0:9101`:
```yaml
    docker_container:
      name: yb-tserver
      image: yugabytedb/yugabyte:latest
      pull: true
      command: "/home/yugabyte/bin/yb-tserver
        --logtostderr
        --fs_data_dirs=/mnt/disk0
        --tserver_master_addrs={{ master_adresses }}
        --rpc_bind_addresses=0.0.0.0:9101
        --webserver_interface=0.0.0.0
        --webserver_port=9000
        --server_broadcast_addresses={{ hostvars[inventory_hostname]['ec2_ip_address'] }}:9101"
      network_mode: host
```

I get the following error while connection to the casandra interface (with the yugabyte container `docker run -ti --rm yugabytedb/yugabyte ./bin/cqlsh pubic_ip_of_server`):
```
Connection error: ('Unable to connect to any servers', {'*pubic_ip_of_server*': <Error from server: code=0000 [Server error] message="Server Error. Resolve failed ota_oes_staging_yb_instance_0: Host not found (authoritative)
SELECT * FROM system.local WHERE key='local'
^^^^^^
 (ql error -2)">})
```

where `ota_oes_staging_yb_instance_0` is the hostname of the server. If i would run the docker container in the normal networking mode the `ota_oes_staging_yb_instance_0` will be replaced by a string id which docker assigns the container as hostname.

In both cases they correctly register to the masters.

My question is how i would configure the ts-server to not use the hostname for connections allowing me to run it in bridge, or other, networking modes (my guess this will also be a problem if i run it in different subnets across multiple regions but i haven't tried that yet).

As a side note i found another unexpected behavior related to host names where if i don't set the `--webserver_port` flag but the `--webserver_interface` to `0.0.0.0` i get the following error in the admin dashboard Error querying url http://db3407346794:7000/tables?raw  (or db3407346794 will be the hostname in the docker host network mode)

**Comment by rkarthik007** [comment]
@iSignal @Arnav15 @bmatican - could one of you please take a look? I know we have done some work in this area, and have a few more features we are planning.

**Comment by iSignal** [comment]
@MarkArts : If I understand this correctly, the issue is that we are attempting to resolve hostnames or connect by hostname even though you have specified `--server_broadcast_addresses` to be the public ip of the host. Please correct me if I am wrong.

I will attempt to reproduce this problem and dig into it a bit more on my end. 

In the meantime, it might also be helpful to get the logs of the tserver and master from the container. They should be under `/mnt/disk0` of the form `yb-master*INFO*` and `yb-tserver*INFO*` (`find /mnt/disk0 -name yb-tserver*INFO*` within the container). Also, if you add the argument `--v=3` to the yb-master and tserver command lines in the docker command line, it will generate highly verbose logging (please remember to turn off logging before running any significant workload) that will also help. If you don't wish to include full logs here, feel free to send them over Slack.

**Comment by iSignal** [comment]
@MarkArts : what is the value of master_addresses in your ansible file? I wonder if it is set to the docker container name?

**Comment by MarkArts** [comment]
> @MarkArts : what is the value of master_addresses in your ansible file? I wonder if it is set to the docker container name?

master_adresses here is a list of public ips for the servers that have the masters installed.

**Comment by iSignal** [comment]
@MarkArts : is the public ip something that only works outside the host or does it also work for addressing within the host from within the docker container?

The master and tserver need to be able to talk to each other. They do so via the address in rpc_bind_address is that is not 0.0.0.0. If rpc_bind is 0.0.0.0, they use the value in  server_broadcast_addresses to talk to each other. They also use the master_addresses flag to discover the masters. So all these addresses need to be routable between the master and tserver containers.
