### ISSUE TITLE
[YSQL] Push down arithmetic operators to docDB

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2969]
Jira Link: [DB-1582](https://yugabyte.atlassian.net/browse/DB-1582)
Push down simple arithmetic operators to docDB:
`update table set col = col + 1`
`select * from table where col / 100 < 20`

These should be done in docDB instead of PG layer.

**Comment by m-iancu** [comment]
The `SET`-clause case (for `UPDATE`) is mostly done by https://github.com/yugabyte/yugabyte-db/issues/3297 (for supported expressions).
The `WHERE` clause and select targets cases remain future work.

**Comment by andrei-mart** [comment]
The WHERE clause is done by 32007863a784e3d228a4e51709357f634ad12dc2
When and if we allow pushdown of target expression, the arithmetic operators won't make any special case, there's no need to keep this issue open.
