### ISSUE TITLE
[YSQL] Push down regex matching

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2971]
Jira Link: [DB-1549](https://yugabyte.atlassian.net/browse/DB-1549)
Postgres has SIMILAR TO and ~ operator for regex matching. We should push down handling these operators in docDB:
https://www.postgresql.org/docs/11/functions-matching.html has some examples for these.

**Comment by andrei-mart** [comment]
Regular expression match is already pushed down.
```
yugabyte=# explain select * from t1 where v ~ 'fo*';
                       QUERY PLAN                       
--------------------------------------------------------
 Seq Scan on t1  (cost=0.00..102.50 rows=1000 width=36)
   Remote Filter: (v ~ 'fo*'::text)
(2 rows)
```
