### ISSUE TITLE
[YSQL] enable client-to-server TLS encryption for postgres process in case use_client_to_server_encryption is set to true

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#2980]
Default configuration of TLS encryption for postgres client-to-server connection should be done automatically in case the `use_client_to_server_encryption` `t-server`'s gflag is true.
For this default configuration certificate which are used for node-to-node encryption should be reused.

**Comment by ndeodhar** [comment]
We should also ensure that `node_to_node_encryption` that works as expected for YSQL. It should create the `SecureContext` for communication between postgres process and YB processes but not require encryption for client communication.
