### ISSUE TITLE
yb master getting down frequently

### ISSUE THREAD

**Issue by sandeshh1** [YugaByte/yugabyte-db#299]
yb master is getting down with below error:

W0522 15:45:58.913365 927286 log_util.cc:209] Could not read footer for segment: /data/hdfs12/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-0000000
0000000000000000000000000.recovery/wal-000000003: Not found (yb/consensus/log_util.cc:445): Footer not found. Footer magic doesn't match
W0522 15:45:58.913518 927286 log_reader.cc:165] Log segment /data/hdfs12/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-0000000000000000000000000000
0000.recovery/wal-000000003 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0522 15:45:59.038285 927296 catalog_manager.cc:3969] CatalogManager is not yet initialized
E0522 15:46:10.239573 927415 catalog_manager.cc:5480] Long lock of catalog manager: 0.379s
    @     0x7f723ab12e64  yb::master::CatalogManager::ScopedLeaderSharedLock::Unlock() (yb/master/catalog_manager.cc:5481)
    @     0x7f723ab99d14  yb::master::MasterPathHandlers::RootHandler(yb::WebCallbackRegistry::WebRequest const&, std::basic_stringstream<char, std::char_tra
its<char>, std::allocator<char> >*) (yb/master/catalog_manager.h:681)
    @     0x7f72384f9ea5  std::function<void (yb::WebCallbackRegistry::WebRequest const&, std::basic_stringstream<char, std::char_traits<char>, std::allocato
r<char> >*)>::operator()(yb::WebCallbackRegistry::WebRequest const&, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) const (gc
c/5.5.0/include/c++/5.5.0/functional:2267)
    @     0x7f72384f9ea5  yb::Webserver::RunPathHandler(yb::Webserver::PathHandler const&, sq_connection*, sq_request_info*) (yb/server/webserver.cc:369)
    @     0x7f72384fa7ee  yb::Webserver::BeginRequestCallback(sq_connection*, sq_request_info*) (yb/server/webserver.cc:312)
    @     0x7f7238505c45
    @     0x7f72385087ed
    @     0x7f723050d693  start_thread (/tmp/glibc-20180316-12585-rgaxli/glibc-2.23/nptl/pthread_create.c:333)
    @     0x7f723024f3cc  (unknown) (../sysdeps/unix/sysv/linux/x86_64/clone.S:109)
    @ 0xffffffffffffffff

Please let me know, what will be the cause of this issue.

**Comment by kmuthukk** [comment]
hi @sandeshh1 : happy to help look at this.  Is the data disk full by any chance? did the cluster create go through the first time, and were you able to look at the master UI on port 7000 (or alternate port if you happened to customize it)?

**Comment by kmuthukk** [comment]
Perhaps you can check the output of this command for your WAL directory:

% df -kh /data/hdfs12/data2

I'll be available on our IRC[/gitter channel](https://gitter.im/YugaByte/Lobby) also for a little bit if you prefer.

**Comment by sandeshh1** [comment]
There is enough space in data directory.

Yes , It went fine for the first time after 8 hours it went down.

**Comment by sandeshh1** [comment]
Now I have started the yb master and it is working fine.

**Comment by kmuthukk** [comment]
@sandeshh1 : Thanks. Sounds good. 

Please also note that the 

```
E0522 15:46:10.239573 927415 catalog_manager.cc:5480] Long lock of catalog manager: 0.379s
@ 0x7f723ab12e64 yb::master::CatalogManager::ScopedLeaderSharedLock::Unlock() 

along with stack of where the lock took a long time
```

this error is just an informational message, and ideally we should report that at WARNING level rather than ERROR level.

Furthermore, this shouldn't cause the yb-master to go down. If there a FATAL log or core file from around that time, please share.

**Comment by sandeshh1** [comment]
hi Kannan,

There is no FATAL error logged at that time.
If it goes down again, I will share the logs.

Could you please let us know path/location for core file .I don't see any core file in logs directory.

Regards,
Sandesh

**Comment by kmuthukk** [comment]
hi @sandeshh1 

I think on Linux by default the core file name is 'core' and it goes to the same directory as the one where your process binary is located.

But the core file location is configurable. You can echo the contents of this file to see where the core file might be going.

```
% cat /proc/sys/kernel/core_pattern
```
For our YugaByte clusters we set the contents of this file to something like:
```
/home/yugabyte/cores/core_%e.%p
```
so that the cores go to a well know location and contain the process name as well as process id as well.

You should also check:
```
% ulimit -c
```
to make sure it is not 0.

**Comment by sandeshh1** [comment]
There is no core file generated in Yugabyte home directory.

Yes. Ulimit -c set to unlimited.

**Comment by kmuthukk** [comment]
hi @sandeshh1 

The /home/yugabyte/cores directory was just a example directory I gave. 

In your case, if you want the cores to go to that directory, you should create the directory and make sure the user you are running yb-tserver/yb-master process as has "rw" privs on that directory. 

Additionally, you must update the `/proc/sys/kernel/core_pattern` file to indicate where you want the core file to go to, and what you want the file name pattern to be:

For example, something like:

```
$> mkdir -p /home/yugabyte/cores
$> chmod a+rwx /home/yugabyte/cores
$> echo "/home/yugabyte/cores/core_%e.%p" > /proc/sys/kernel/core_pattern
```

**Comment by kmuthukk** [comment]
Sharing some of the other ulimit settings we use in some of our internal YugaByte clusters:

```
[centos@yb-15-reads-from-disk-n1 ~]$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 119934
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 12000
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

It'll be good to double check if these settings aren't too low in your environment.

**Comment by bbaddepudi** [comment]
Hi @sandeshh1 - Just to quickly add to the above, to make the core file pattern persistent across system reboots, the following line can be appended to “/etc/sysctl.conf“:
`kernel.core_pattern=/tmp/cores/core.%e.%p.%h.%t`

Please let us know if you notice any yb-master.FATAL file or if you run into similar master going down issue again. 

Thanks.

**Comment by sandeshh1** [comment]
Yesterday It went down without generating any FATAL error.even no error logs.

I could below in warning logs:

[root@NGPRD1BOO50D00 logs]# more yb-master.NGPRD1BOO50D00.root.log.WARNING.20180523-182135.93738
Log file created at: 2018/05/23 18:21:35
Running on machine: NGPRD1BOO50D00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0523 18:21:35.273502 93764 log_util.cc:209] Could not read footer for segment: /app/yugadb/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-000000000
00000000000000000000000.recovery/wal-000000005: Not found (yb/consensus/log_util.cc:445): Footer not found. Footer magic doesn't match
W0523 18:21:35.273591 93764 log_reader.cc:165] Log segment /app/yugadb/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-000000000000000000000000000000
00.recovery/wal-000000005 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0523 18:25:05.763849 93766 log.cc:663] Time spent Fsync log took a long time: real 0.139s      user 0.000s     sys 0.000s
W0523 18:25:40.050951 93766 log.cc:663] Time spent Fsync log took a long time: real 0.120s      user 0.000s     sys 0.000s
W0523 18:27:40.758231 93766 log.cc:663] Time spent Fsync log took a long time: real 0.208s      user 0.000s     sys 0.000s

INFO logs:

I0523 18:21:36.552194 93766 log.cc:524] Max segment size 16777216 reached. Starting new segment allocation.
I0523 18:21:36.902503 93766 env_posix.cc:593] Closing file /app/yugadb/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/.tmp.newsegmentvMmaAy with 1024 blocks
I0523 18:21:36.902577 93766 env_posix.cc:599] /app/yugadb/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/.tmp.newsegmentvMmaAy: Truncating file from size: 55898112 to size: 55894606. Preallocated size: 16777216
I0523 18:21:36.903517 93766 log.cc:441] Rolled over to a new segment: /app/yugadb/data2/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000006
W0523 18:25:05.763849 93766 log.cc:663] Time spent Fsync log took a long time: real 0.139s      user 0.000s     sys 0.000s
W0523 18:25:40.050951 93766 log.cc:663] Time spent Fsync log took a long time: real 0.120s      user 0.000s     sys 0.000s
W0523 18:27:40.758231 93766 log.cc:663] Time spent Fsync log took a long time: real 0.208s      user 0.000s     sys 0.000s

**Comment by kmuthukk** [comment]
hi @sandeshh1 : The "I" and "W" prefixed lines are likely just trailing indicators. We need to get to the initial symptoms (earliest log files). 

Question: are you running this on SSD disks or HDDs? We recommend SSDs. Also, what OS? how many core machines, and how much RAM?

(If it is helpful, we can try to help debug this with you over a conf-call where you can share your screen. You can message me at my <firstname> @ yugabyte.com email and we can have someone on the team help debug this further.)

regards,
Kannan

**Comment by kmuthukk** [comment]
@sandeshh1 : 
One more thought... how are you launching these processes? As a service? Or, are you doing a "nohup" to make sure the process doesn't exit when you logout for example.

**Comment by bbaddepudi** [comment]
Hoping that you have all the options to make progress @sandeshh1 . Closing out this issue for now. Keep us posted and feel free open this or file a new one for any further information/bugs. Thanks.
