### ISSUE TITLE
Is it stable ?

### ISSUE THREAD

**Issue by lakinmohapatra** [YugaByte/yugabyte-db#3]
Is it stable ?

**Comment by rkarthik007** [comment]
Yes, YugaByte is stable. We run a wide variety of tests before publishing our releases, including large cluster and stress tests. We are hoping to write a blog post soon on how rigorous our test coverage is.

However, note that we are a 0.9 beta release at the moment - and we have some customers running us over a long time period in a pre-production mode. We will be generally available in a few months time.

Please reach out to us (https://forum.yugabyte.com/) if you are considering us for a use-case. We would be very happy to help and give you more details relevant to your use-case.

**Comment by yingfeng** [comment]
Have you passed the jepsen test?

**Comment by amitanandaiyer** [comment]
@yingfeng We are currently working on using Jepsen to validate the YugaByte DB. Please follow the thread on https://forum.yugabyte.com to keep up with the updates regarding this.

**Comment by schoudhury** [comment]
closing this issue for now, pls open a new issue when needed
