### ISSUE TITLE
Tablet server getting down frequently

### ISSUE THREAD

**Issue by sadeshjayraj** [YugaByte/yugabyte-db#301]
Hi Kannan,

My tablet server getting down frequently due to following error,

 Failed to destroy RocksDB at: /app/yugadb/data2/yb-data/tserver/data/rocksdb/table-e5535e14492e44c393b8f38a65f906f9/tablet-7f1c9290292d4044b44b3967ffd89567: IO error (yb/rocksdb/util/io_posix.h:43): /app/yugadb/data2/yb-data/tserver/data/rocksdb/table-e5535e14492e44c393b8f38a65f906f9/tablet-7f1c9290292d4044b44b3967ffd89567/LOCK: No such file or directory
How we can resolve this issue ??

**Comment by kmuthukk** [comment]
Hi @sadeshjayraj 

These errors do not cause a tablet-server process to restart.

The log lines are typically prefixed with the severity level of the log. For example:

```
I (INFO)
W (WARNING)
E (ERROR)
F (FATAL)
```

The yb-tserver.INFO file contains everything logged at INFO and above.
The yb-tserver.WARNING file contains everything logged at WARNING and above.
...
and so on.
...

The logs with "E" level are simply an indication of some type of error - but it is an error that the system is generally able to recover from. For example, this might be a usage error logged to a file (such as using an incorrect option for an API) or an timeout or retry error. Some of those are things we should instead be logging at a WARNING level to avoid confusion.

In this case, if a tserver attempts to delete a tablet (shard of table) that has already been removed we report this line. But this should not cause a restart of the tserver.

Are you sure that the yb-tserver process died (e.g, by check the output of "ps auxww | grep yb-tserver")?

Do you see anything else (such a yb-tserver.FATAL file or an .err or .out file - the stderr or stdout of the process) that gives a clue as to why the restart might have happened?

regards,
Kannan

**Comment by kmuthukk** [comment]
hi @sadeshjayraj : closing the issue for now. But feel free to re-open if this is not yet resolved on your end.
