### ISSUE TITLE
one of the tserver went down

### ISSUE THREAD

**Issue by sandeshh1** [YugaByte/yugabyte-db#302]
Hi Peers,

One of our tserver failed with below error out of 9 tservers.

W0523 08:22:44.397490 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet cf63aaca47a940eca865ad29751b3417 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.401643 109745 consensus_peers.cc:354] T 81d707c679ce42358c919bcad437c704 P becaec012be94318a8ad7caba7a1692a -> Peer 224e25a4d011423d93a468396029b563 (10.147.165.41:9100): Unable to begin remote bootstrap on peer: error { code: UNKNOWN_ERROR status { code: ILLEGAL_STATE message: "State transition of tablet 81d707c679ce42358c919bcad437c704 already in progress: remote bootstrapping tablet from peer becaec012be94318a8ad7caba7a1692a" } }
W0523 08:22:44.423264 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ec47fc59c6ab45828bb8b3ddcdf8147b already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.456125 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ff71d433c6f54e08a33352d40dc5fedf already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.495414 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet c813579990b1440c9e14ff0c3f3c529d already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:44.498641 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fecf003b772b496682d70919423d6093 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.560015 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet bee290bb54f54c64ae69c3a00c48c0c0 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:44.597270 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 2c246e2ccb24431e8467ed03f9707f3b already in progress: remote bootstrapping tablet from peer 91a9136ad5894c68a1eb66364ff31482
W0523 08:22:44.673892 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 4703766c6a8749cba2cb6b850bc4c501 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:44.768208 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 80d21f99f00c44228dc46be3f23e9b3c already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:44.819609 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet d86f41c8985546a983d4251507ea47b3 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.833240 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet eb290c60b64840a8b6c9a0fa645046ea already in progress: remote bootstrapping tablet from peer ee57bf933ed048049efc027673bd76e3
W0523 08:22:44.856773 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fe152a0bd1f24a108cfccb8b4e2a6405 already in progress: remote bootstrapping tablet from peer ee57bf933ed048049efc027673bd76e3
W0523 08:22:44.893152 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet cf63aaca47a940eca865ad29751b3417 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.901820 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 7f1c9290292d4044b44b3967ffd89567 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.905571 109739 consensus_peers.cc:354] T 81d707c679ce42358c919bcad437c704 P becaec012be94318a8ad7caba7a1692a -> Peer 224e25a4d011423d93a468396029b563 (10.147.165.41:9100): Unable to begin remote bootstrap on peer: error { code: UNKNOWN_ERROR status { code: ILLEGAL_STATE message: "State transition of tablet 81d707c679ce42358c919bcad437c704 already in progress: remote bootstrapping tablet from peer becaec012be94318a8ad7caba7a1692a" } }
W0523 08:22:44.918936 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ec47fc59c6ab45828bb8b3ddcdf8147b already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.951745 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ff71d433c6f54e08a33352d40dc5fedf already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:44.996018 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet c813579990b1440c9e14ff0c3f3c529d already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.003295 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fecf003b772b496682d70919423d6093 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.057293 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet bee290bb54f54c64ae69c3a00c48c0c0 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.093273 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 2c246e2ccb24431e8467ed03f9707f3b already in progress: remote bootstrapping tablet from peer 91a9136ad5894c68a1eb66364ff31482
W0523 08:22:45.179252 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 4703766c6a8749cba2cb6b850bc4c501 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.273241 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 80d21f99f00c44228dc46be3f23e9b3c already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.315845 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet d86f41c8985546a983d4251507ea47b3 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.334993 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet eb290c60b64840a8b6c9a0fa645046ea already in progress: remote bootstrapping tablet from peer ee57bf933ed048049efc027673bd76e3
W0523 08:22:45.360046 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fe152a0bd1f24a108cfccb8b4e2a6405 already in progress: remote bootstrapping tablet from peer ee57bf933ed048049efc027673bd76e3
W0523 08:22:45.364524 120998 yb_rpc.cc:315] Call yb.consensus.ConsensusService.StartRemoteBootstrap *:52025 => *:9100 (request call id 245072) took 30337ms (client timeout 3000ms).
W0523 08:22:45.397750 120998 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 7f1c9290292d4044b44b3967ffd89567 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.397788 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet cf63aaca47a940eca865ad29751b3417 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.405357 109741 consensus_peers.cc:354] T 81d707c679ce42358c919bcad437c704 P becaec012be94318a8ad7caba7a1692a -> Peer 224e25a4d011423d93a468396029b563 (10.147.165.41:9100): Unable to begin remote bootstrap on peer: error { code: UNKNOWN_ERROR status { code: ILLEGAL_STATE message: "State transition of tablet 81d707c679ce42358c919bcad437c704 already in progress: remote bootstrapping tablet from peer becaec012be94318a8ad7caba7a1692a" } }
W0523 08:22:45.423071 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ec47fc59c6ab45828bb8b3ddcdf8147b already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.456472 120998 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ff71d433c6f54e08a33352d40dc5fedf already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.499191 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fecf003b772b496682d70919423d6093 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.501317 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet c813579990b1440c9e14ff0c3f3c529d already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.553246 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet bee290bb54f54c64ae69c3a00c48c0c0 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.594923 120998 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 2c246e2ccb24431e8467ed03f9707f3b already in progress: remote bootstrapping tablet from peer 91a9136ad5894c68a1eb66364ff31482
W0523 08:22:45.677363 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 4703766c6a8749cba2cb6b850bc4c501 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.771536 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 80d21f99f00c44228dc46be3f23e9b3c already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:45.811341 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet d86f41c8985546a983d4251507ea47b3 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.830629 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet eb290c60b64840a8b6c9a0fa645046ea already in progress: remote bootstrapping tablet from peer ee57bf933ed048049efc027673bd76e3
W0523 08:22:45.859184 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fe152a0bd1f24a108cfccb8b4e2a6405 already in progress: remote bootstrapping tablet from peer ee57bf933ed048049efc027673bd76e3
W0523 08:22:45.893239 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 7f1c9290292d4044b44b3967ffd89567 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.901728 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet cf63aaca47a940eca865ad29751b3417 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.901947 109743 consensus_peers.cc:354] T 81d707c679ce42358c919bcad437c704 P becaec012be94318a8ad7caba7a1692a -> Peer 224e25a4d011423d93a468396029b563 (10.147.165.41:9100): Unable to begin remote bootstrap on peer: error { code: UNKNOWN_ERROR status { code: ILLEGAL_STATE message: "State transition of tablet 81d707c679ce42358c919bcad437c704 already in progress: remote bootstrapping tablet from peer becaec012be94318a8ad7caba7a1692a" } }
W0523 08:22:45.927556 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ec47fc59c6ab45828bb8b3ddcdf8147b already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.961128 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet ff71d433c6f54e08a33352d40dc5fedf already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.994962 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet fecf003b772b496682d70919423d6093 already in progress: remote bootstrapping tablet from peer 5ea77fe2333046f39cd21282dff2dec1
W0523 08:22:45.999608 130937 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet c813579990b1440c9e14ff0c3f3c529d already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:46.054932 120998 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet bee290bb54f54c64ae69c3a00c48c0c0 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:46.093755 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 2c246e2ccb24431e8467ed03f9707f3b already in progress: remote bootstrapping tablet from peer 91a9136ad5894c68a1eb66364ff31482
W0523 08:22:46.120991 109738 consensus_peers.cc:363] T 81d707c679ce42358c919bcad437c704 P becaec012be94318a8ad7caba7a1692a -> Peer 224e25a4d011423d93a468396029b563 (10.147.165.41:9100): Couldn't send request to peer 224e25a4d011423d93a468396029b563 for tablet 81d707c679ce42358c919bcad437c704 Status: Illegal state (yb/common/wire_protocol.cc:159): Tablet not RUNNING: BOOTSTRAPPING. Retrying in the next heartbeat period. Already tried 1 times.
W0523 08:22:46.143443 109778 yb_rpc.cc:315] Call yb.consensus.ConsensusService.StartRemoteBootstrap *.*.*.*:52025 => *.*.*.*:9100 (request call id 244450) took 34114ms (client timeout 3000ms).
W0523 08:22:46.173094 109778 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 4703766c6a8749cba2cb6b850bc4c501 already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f
W0523 08:22:46.267416 130938 tablet_service.cc:1325] Start remote bootstrap failed: Illegal state (yb/tserver/ts_tablet_manager.cc:868): State transition of tablet 80d21f99f00c44228dc46be3f23e9b3c already in progress: remote bootstrapping tablet from peer a3a9d9a742e3402ab57abf05d099c12f

Please let us know what could be possible reason for failure.

Regards,
Sandesh

**Comment by rkarthik007** [comment]
Thanks for reporting @sandeshh1.

A few questions:

1. By << the tserver failed >> - could you please elaborate the observed symptom?

2. What version of yugabyte-db and OS are you running? (You can find the version by running `yb-tserver --version`).

3. Do you know of the sequence that lead to this? (was it a simple cluster start, were nodes added, was there a failure of a process, etc).

4. About these lines in the log snippet you posted (this in itself is not an error but just checking, the system should recover by itself):
> W0523 08:22:46.120991 109738 consensus_peers.cc:363] T 81d707c679ce42358c919bcad437c704 P becaec012be94318a8ad7caba7a1692a -> Peer 224e25a4d011423d93a468396029b563 (10.147.165.41:9100): Couldn't send request to peer 224e25a4d011423d93a468396029b563 for tablet 81d707c679ce42358c919bcad437c704 Status: Illegal state (yb/common/wire_protocol.cc:159): Tablet not RUNNING: BOOTSTRAPPING. Retrying in the next heartbeat period. Already tried 1 times.
> 
> W0523 08:22:46.143443 109778 yb_rpc.cc:315] Call yb.consensus.ConsensusService.StartRemoteBootstrap ...:52025 => ...:9100 (request call id 244450) took 34114ms (client timeout 3000ms).

Is that tablet server (10.147.165.41) running?

**Comment by kmuthukk** [comment]
hi @sandeshh1 - closing this issue for lack of sufficient/more info. But please feel free to re-open if this is still an issue.
