### ISSUE TITLE
[YSQL] Reverse-scanning for large table returns 0 rows

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#3021]
This bug is a spin-off from issue #2792 
When ORDER BY range-key and LIMIT value are pushed down, YugaByte returns 0 row for reverse or backward scanning large tables (10K rows).

Use the following scenarios to reproduce.
```
CREATE TABLE large_tab(hash_key int, range_key int, value int, primary key(hash_key, range_key));
COPY a large data-set;
SELECT * FROM large_tab WHERE hash_key = xxx ORDER BY range_key DESC LIMIT 1;
```
The above query will return 0 row.

**Comment by ndeodhar** [comment]
Can you add more details on the data set that you used? I'm not able to reproduce.
Here's what I tried:
```
create table test(a int, b int, primary key(a,b));
insert into test values(1, generate_series(1,20000)); // 20K rows inserted
select * from test where a=1 order by b desc limit 1;
 a |   b   
---+-------
 1 | 20000
(1 row)
```

**Comment by nocaway** [comment]
Not a bug.
Failure in private build only due to local changes.
