### ISSUE TITLE
[Tools] Enhance yb-ctl and yb-docker-ctl to support Python 3

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#3025]
Currently both yb-ctl and yb-docker-ctl work only with Python 2 and not with Python 3. Both these tools should be enhanced to support Python 3.

Note that Python 2 will be officially EOLed January 1, 2020 as noted here: https://www.python.org/doc/sunset-python-2/

**Comment by alexander-manley** [comment]
Is this ticket in reference to Python 3.6.3 as specified in issue #281?  

Proposed options for renaming this ticket could include using either Python 3.x or 3.6, or listing a supported range, for example, Python 3.6 - 3.8.

The current name of tools ticket #3025 does not specify the minimum version of Python 3 that will be supported by yb-ctl.  Assuming >3.6.3 and 3.7.x will be supported?

**Comment by Remigius2011** [comment]
Hi,

As python 2.x is now already EOL and using 2.x is strongly discouraged, I'd like to ask if there is already an ETA for the 3.x versions of the scripts?

Best regards, Remi.

**Comment by rkarthik007** [comment]
Hi @ramkumarvs @iSignal - do we know if `yb-ctl` already works with python 3.x?

**Comment by iSignal** [comment]
I verified that basic create/start/stop/status operations on yb-ctl work with python3 on my mac. 

yugabyted also works with python3.

The 2to3 migration tool reports changes that need to be made for python3 compatibility  - https://gist.github.com/iSignal/332c3417790686d6e5d0793e56e7111b. Of these, most of them are the tool being overly conservative - the one that stands out is the urllib2 usage which needs to be fixed if the auto download package functionality is to be supported.

**Comment by schoudhury** [comment]
Work is tracked in the PR by @iSignal https://github.com/yugabyte/yugabyte-installation/pull/27

**Comment by schoudhury** [comment]
This is resolved in the 2.1 release.
