### ISSUE TITLE
[Colocation] Create flow

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3033]
Support `CREATE DATABASE WITH colocation=true`. This should create 1 tablet for the entire DB. All tables created within that database should use the same tablet.

**Comment by ben-pr-p** [comment]
When would a Yugabyte DB user want to colocate versus distrubte a table?

**Comment by ndeodhar** [comment]
Hi @ben-pr-p , this page has information on when it'll be suitable to use colocated tables (Motivation section at the beginning): https://github.com/yugabyte/yugabyte-db/blob/master/architecture/design/ysql-colocated-tables.md

In a gist, it'll a good choice for following scenarios:
1. Your database size is small (<500 GB) and you need high availability and geographic distribution.
2. Your database has a large number of tables, of which most tables are small and only a few are large. In this case, you can colocate the small tables on a single tablet and distribute the large tables.
3. You want to scale the number of databases. For example, you have 1 database per user / tenant and you want to have large number of databases. In this case, you can colocate all tables in a database in one tablet.
