### ISSUE TITLE
[Colocation] Tables should use range keys by default

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3034]
Today, primary key of a table is `hash` by default. With tablet colocation, we should use `range` primary key by default since all data for the table will be in the same tablet.

**Comment by jj-kim** [comment]
Commit 6d332c9635edb474b66c5c3de6dba1afb76ef3c8 forces colocated tables to use range keys.  For example,

```sql
CREATE TABLE t (i int PRIMARY KEY) WITH (colocated = true);
```

fails.  This issue will remain open because the desired behavior is to allow the above statement to run successfully and make `i` a range key rather than a hash key.

**Comment by jj-kim** [comment]
Not specifying primary key should also be allowed and use range key on `ybctid`:

```sql
CREATE TABLE t (i int) WITH (colocated = true);
```
