### ISSUE TITLE
[Colocation] Drop flow

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3035]
In colocated tablet, drop table should delete the rows for the table being deleted. (This can be done by adding a delete marker for the cotableid).
Drop database should delete the table for the DB.

**Comment by jj-kim** [comment]
Commit 306f53b38b4683f94d340bd6070793890a92df11 adds basic support for the drop flow without handling data deletion and without supporting `TRUNCATE`.  Push the rest of the data deletion tasks into separate issues:

1. #3357
1. #3358
1. #3359
1. #3360

**Comment by frozenspider** [comment]
> Commit [306f53b](https://github.com/yugabyte/yugabyte-db/commit/306f53b38b4683f94d340bd6070793890a92df11) adds basic support for the drop flow without handling data deletion and without supporting `TRUNCATE`.

Possibly related: #10912
