### ISSUE TITLE
[platform] AWS Time Sync toggle missing chrony configuration

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3038]
According to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service, chrony should be explicitly configured to point to `169.254.169.123`, see step 3:
> server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4

Would also need to ensure we disable the other servers, so it never uses the default ntp ones.

**Comment by ramkumarvs** [comment]
4a2734dab6e2b1975a62310a8b97ac0ee5c1eb69 fixed this issue
