### ISSUE TITLE
Error executing: CREATE USER IF NOT EXISTS

### ISSUE THREAD

**Issue by dacrypt** [yugabyte/yugabyte-db#3045]
Jira Link: [DB-4725](https://yugabyte.atlassian.net/browse/DB-4725)
```
CREATE USER IF NOT EXISTS exampleuser;
LINE 1: CREATE USER IF NOT EXISTS exampleuser;
                       ^
```

**Comment by ndeodhar** [comment]
Hi @dacrypt , we don't support `IF NOT EXISTS` clause for `CREATE USER`.
Is this a new feature request that you'd like us to support?

**Comment by dacrypt** [comment]
not a priority, but I suppose you'd like to have that to be compatible with psql

**Comment by ndeodhar** [comment]
It is compatible with postgres - postgres doesn't support `IF NOT EXISTS` as well on `CREATE USER`: https://www.postgresql.org/docs/12/sql-createuser.html

**Comment by dacrypt** [comment]
Ohh .. I didn't know.. ok then.

**Comment by rthallamko3** [comment]
Closing this issue.
