### ISSUE TITLE
YCQL audit extension.

### ISSUE THREAD

**Issue by skanakakorn** [yugabyte/yugabyte-db#3056]
I have a use case where any YCQL transactions recorded successfully on Yugabyte need to be replicated to a system log in the order the transactions were executed. This would be used for debugging and auditing purpose. I'd love Yugabyte to support this.

**Comment by ddorian** [comment]
Can't you write in a transaction also to the `audit_log` table ?

**Comment by ddorian** [comment]
@skanakakorn does my suggestion above satisfy your needs ?

**Comment by ddorian** [comment]
@skanakakorn please reopen if you still have questions
