### ISSUE TITLE
support for SSL encryption for: node-to-node & client-to-node?

### ISSUE THREAD

**Issue by niektemme** [YugaByte/yugabyte-db#306]
My apologies if this question has been answered before or already document. I have searched however in both the documentation and on the get repo and so far was unable to find the answer.
 
The question is does YugabyteDB support SSL encryption in the case of:
1) Node-to-node encrypted communication,
2) Client-to-node encrypted communication?
 
If client-to-node-encryption is supported, is the configuration of cqlshrc similar to connecting using ssl to Cassandra?
 
Similar to Cassandra as documented in https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureSSLIntro.html

**Comment by niektemme** [comment]
Hi @rkarthik007,

Thank you for your answer. I will contact you over email regarding our use case.
Niek

**Comment by phamtien** [comment]
Hi @rkarthik007 How about the status of this feature? This is a must have feature of online payments processing system (PCI-DSS compliance)

**Comment by rkarthik007** [comment]
Hi @niektemme,

Always makes me super happy to deliver this news - we now have this feature available: https://docs.yugabyte.com/latest/secure/tls-encryption/

This is currently only available in the enterprise edition, but there might be changes there (no promises, and don't want to spoil the surprise 😉 so no details now). Fire away if you have any questions, or hit me up if you want to try this feature for now.

**Comment by rkarthik007** [comment]
Closing this out... please open a separate issue if you need anything!
