### ISSUE TITLE
[docdb] Add ability for transaction table to not respect leader affinity

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3077]
We already have a feature to bind leadership to certain localities. When your app is collocated with the leaders, the latency from app to YB becomes essentially 0, but you still incur the cost when the app is not collocated.

However, if your app is executing transactional queries, the cost from app to YB is higher, as we execute multiple round trips per request. Some of those round trips are towards the transaction table and we already have code to pick a transaction tablet that is local to the node executing the query. If we could guarantee that there is always a leader wherever the initial queries are processed, then we could cut the latency for queries to the txn tablet to 0!

One minor inconvenience with this is that it will make it a bit harder to reason, when looking at master stats, if the load is actually correctly balanced (since user tablets will respect leader locality, but txn table will not).

cc @kmuthukk @mbautin @spolitov @ndeodhar

**Comment by vvkgopalan** [comment]
Resolved in https://github.com/yugabyte/yugabyte-db/commit/51be987f2ee41e995b4e5672e74a31c2660ca53a.
