### ISSUE TITLE
[docdb] load balance the tablets at the global level also

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3079]
At the moment we load balance the tablets at the table level. If a table has uneven number of tablets that cannot be divided in a even way across all the available nodes, we load balance that table where some tservers may have 1 extra tablet for that table than the other tservers.

But, if multiple tables have uneven tablet counts then it is possible for some tservers to have significantly higher tablet counts than others.

In addition to load balancing at the table level, we should also load balance the total tablet counts on the tservers as much as possible without violating the table level rule.

**Comment by bmatican** [comment]
This is essentially the data counterpart to #3040

**Comment by bmatican** [comment]
Passing to @rahuldesirazu for now, together with the leader one as well.
