### ISSUE TITLE
The table does not exist: table_name: "redis"

### ISSUE THREAD

**Issue by rohitjoshi** [YugaByte/yugabyte-db#308]
```
docker exec -it yb-tserver-n1 /home/yugabyte/bin/redis-cli
127.0.0.1:6379> set abc 123
(error) ERR set: Could not open .redis table. Not found (yb/common/wire_protocol.cc:143): The table does not exist: table_name: "redis"
namespace {
  name: "system_redis"
}

127.0.0.1:6379> PING
(error) ERR PING: Could not open .redis table. Not found (yb/common/wire_protocol.cc:143): The table does not exist: table_name: "redis"
namespace {
  name: "system_redis"
}
```

**Comment by schoudhury** [comment]
Rohit,
The error means that system_redis is not setup yet. Assuming you are using `yb-docker-ctl` it should be automatic. How did you create the local cluster?

In any case, you can create the table manually by running the following.

`docker exec -it yb-master-n1 /home/yugabyte/bin/yb-admin --master_addresses yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 setup_redis_table`

Let us know if that solves the problem.

**Comment by rohitjoshi** [comment]
@schoudhury thanks.  I used `docker-compose` file from https://docs.yugabyte.com/latest/admin/docker-compose/#create-a-single-node-cluster

**Comment by rohitjoshi** [comment]
`docker exec -it yb-master-n1 /home/yugabyte/bin/yb-admin --master_addresses yb-master-n1:7100  setup_redis_table`  did work. 

Thank you
