### ISSUE TITLE
TSAN failure in MasterPartitionedTest.CauseMasterLeaderStepdownWithTasksInProgress

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3081]

**Comment by bmatican** [comment]
`Location is global 'fLI::FLAGS_slowdown_master_async_rpc_tasks_by_ms' of size 4 at 0x7f37cacafa84 (libmaster.so+0x000000548a84)`

Seems like we just need some Get/Set atomic for this test.

**Comment by bmatican** [comment]
Closing this as duplicate of #2647
