### ISSUE TITLE
Cqlsh fails for 1-node cluster

### ISSUE THREAD

**Issue by seybi87** [YugaByte/yugabyte-db#309]
Hi guys, 

I am trying to setup different performance benchmarks of YugaByte in the Cloud.
Therefore I'd like to start with a simple 1-node cluster before going large scale. 

Hence I created a 1-node cluster with a yb-master (replication factor 1) and  a yb-server with the following commands:
 
`./yb-master --master_addresses 192.168.100.14:7100  --fs_data_dirs "/opt/yugabyte/disk1,/opt/yugabyte/disk2" --replication_factor 1`

`./yb-tserver --tserver_master_addrs 192.168.100.14:7100 --fs_data_dirs "/opt/yugabyte/disk1,/opt/yugabyte/disk2" --cql_proxy_bind_address 192.168.100.14`

Yet, when I am trying to connect to YugaByte via cqlsh I get the following error message: 
`Connection error: ('Unable to connect to any servers', {'192.168.100.14': IndexError('list index out of range',)})`

Yet, if I create the 3-node test cluster via yb-ctl it works perfectly with cqlsh.

Thank you in advance for any kind of advises.
Cheers

**Comment by seybi87** [comment]
Hi @kmuthukk ,
thank you for your fast response. 
One problem might have been indeed that I did not wipe the data directories before each new start of the master and server.

I followed your steps and all processes are running (but they were also running in my first try) but the issues still persists with the same error message. 

In addition, there are no errors or warnings in the tserver.out and tmaster.out.
Yet, in the yb-master.WARNING I get the following warnings: 

`Log file created at: 2018/05/30 14:21:46
Running on machine: yugabyte-node-1
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0530 14:21:46.498281  4979 reactor.cc:355] Client call yb.consensus.ConsensusService.GetNodeInstance has no timeout set for connection id: { remote: 192.168.100.14:7100 idx: 0 }
W0530 14:21:46.517601  4990 catalog_manager.cc:606] Catalog manager background task thread going to sleep: Service unavailable (yb/master/catalog_manager.cc:5426): Catalog manager is not initialized. State: 1`

Here are also some more information about my system which is a VM on OpenStack. All commands are issued as ROOT and from inside the VM:
OS: Ubuntu 16.04 4.4.0-127-generic
Python:  Python 2.7.12

Thanks again for any further hints.

**Comment by rkarthik007** [comment]
Hi @seybi87,

One difference with `yb-ctl` and your approach might be the ip address the process is binding to. `yb-ctl` might be binding to `127.0.0.1` on three different ports, while here the process is binding to `192.168.100.14`. 

1. Could you please paste the output of `ifconfig` or `ip addr` so we can see the network interfaces?
2. Are you running everything from the VM itself? I mean the master, tserver and cqlsh.
3. If you replaced your ip address with `127.0.0.1`, I am curious if your system starts running. If so, it might give us a clue as to the issue (network address resolution or access).

**Comment by kmuthukk** [comment]
Thanks @seybi87. Glad to hear. 

[Note: For regular restarts, you don't need to wipe the data directories. But, for example, when changing identity of the master (in this case the IP), a wipe of the data directory would be needed. When the directory is empty, it triggers the first time cluster creation flows. Otherwise, it is deemed a simple restart.]
