### ISSUE TITLE
[docdb][ysql] Add CREATING and DELETING steps for YSQL databases in CatalogManager

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3097]
We are piggybacking on the Namespace objects in CatalogManager for databases in YSQL. When we only had YCQL, the Namespace object was super light because:
- On create, there's minimal metadata to prepare
- On delete, the namespace was required to be empty (no tables), so deleting it was also quick

However, for YSQL, currently:
- Creating a database needs to prepare a bunch of system tables and copy data into them from template0, which is not quick
- Dropping a database does a cascade drop of all tables underneath, which is also not quick

To improve fault tolerance for these, we should likely follow the model we've used for tables:
- On create, add a CREATING step, only switch to RUNNING when all prep work is done. All incoming queries will have to wait on this and so will the initial create. Need to be careful on concurrent creates too.
- On delete, add a DELETING step, only switch to DELETED when all wrap up work is done. Need a wait for this as well. Will have to be careful how we make this available to the upper level though, where a DELETING DB should not allow new tables to be created, but also not allow one with the same name to be created, if the metadata for it is tracked in postgres?

We should also think through the fault tolerance on the master side, where if we fail in the middle of an operation, stuck in CREATING/DELETING, we roll forward these operations to some terminal state.

cc @ndeodhar

**Comment by bmatican** [comment]
Have asked @rajukumaryb to start looking into this.

**Comment by ndeodhar** [comment]
@nspiegelberg Can we close this?
