### ISSUE TITLE
[YSQL] Improve index scan to batch select rows from base table

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3103]
Today, for index scans, we first scan the index table to get the rows of interest. Then for each row, we send 1 read query per row to tserver. We should batch these reads from tserver instead.

**Comment by nocaway** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/eeab192b79af1eaf11df717396293973d16312b3
