### ISSUE TITLE
Investigate slow data loading

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3111]
While loading data for TPCC benchmark, we see that the data loading starts off at ~1300 ops / sec and then drops to ~100 ops / sec within a few minutes and stays at that level. Total time to load data ends up being 2+ hours.

We should investigate what causes the throughput to drop 10x. I've attached a screenshot of data loading metrics.
<img width="877" alt="Screen Shot 2019-12-06 at 3 29 03 PM" src="https://user-images.githubusercontent.com/15746068/70378495-cb87d980-18d5-11ea-8a37-6a2ae36b8b69.png">

The first spike is when I tried loading data with 1 thread and the second spike is loading data with 4 threads. It's also interesting to note that there is no difference in speed while using 1 thread and 4 threads.

**Comment by spolitov** [comment]
During load, TPCC benchmark uses a fixed number of threads. It explains no difference between 1 or 4 threads.

**Comment by rkarthik007** [comment]
Hi folks, this has been resolved correct?

**Comment by ndeodhar** [comment]
Yes, it has been resolved.
