### ISSUE TITLE
Yedis very poor read performance for a sorted set with over a million items.

### ISSUE THREAD

**Issue by tarangill** [yugabyte/yugabyte-db#3112]
I have a sorted set in Yedis with about 45 million items. The read performance is very poor.

ZSCORE and ZCARD are very fast.

However, ZREVRANGE totally fails with error: 
`
(error) Deadline for query passed.
(2.50s)
`

ZRANGE queries only work for the first about 1,900,000 items. After that same error as above.

ZRANGE queries become progressively slower with increasing START number.

ZRANGEBYSCORE is very fast, when a score is provided. When using -inf and +inf, and a Limit offset number of over 2 million, it fails with the above error.

**Comment by amitanandaiyer** [comment]
@tarangill  Can you please elaborate upon the use case that you have?

Maintaining and accessing a sorted set on disk/ssd is going to be costlier to access than keeping it in memory with random access.

So some of these Z* commands are inefficient, and are meant to be used sparingly as they will involve a scan through all the sorted set data to answer the query.

Zcard/Zscore are pretty much point look ups. while the other commands seem to necessitate a scan over the data to return the answer.  

You could also consider using the TS data type (if you only need a 1 way mapping) it would be faster than the Z* type.
