### ISSUE TITLE
v2.0.7 fresh install won't run in Ubuntu

### ISSUE THREAD

**Issue by dacrypt** [yugabyte/yugabyte-db#3122]
1. Follow instruction from https://download.yugabyte.com/#linux
2. In ubuntu it won't start. The errors are:

The logs show:
`eveloper@pluriza-dev1:~/yugabyte-2.0.7.0$ tail ../yugabyte-data/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO
E1209 23:01:40.306277 26228 io_thread_pool.cc:63] Io service failed to stop
I1209 23:01:40.352941 26308 heartbeater.cc:301] P e3363b485b2845e6afba1e106641a007: Connected to a leader master server at 127.0.0.1:7100
I1209 23:01:40.353085 26308 heartbeater.cc:359] P e3363b485b2845e6afba1e106641a007: Registering TS with master...
I1209 23:01:40.353129 26308 server_base.cc:484] Using private ip address 127.0.0.1
I1209 23:01:40.353184 26308 heartbeater.cc:368] P e3363b485b2845e6afba1e106641a007: Sending a full tablet report to master...
W1209 23:01:40.371266 26228 subprocess.cc:185] Child process 26286(/home/developer/yugabyte-2.0.7.0/postgres/bin/postgres -D /home/developer/yugabyte-data/node-1/disk-1/pg_data -p 5433 -h 127.0.0.1 -k  -c logging_collector=on -c log_directory=/home/developer/yugabyte-data/node-1/disk-1/yb-data/tserver/logs -c shared_preload_libraries=yb_pg_metrics -c yb_pg_metrics.node_name=DEFAULT_NODE_NAME -c yb_pg_metrics.port=13000 -c config_file=/home/developer/yugabyte-data/node-1/disk-1/pg_data/ysql_pg.conf -c hba_file=/home/developer/yugabyte-data/node-1/disk-1/pg_data/ysql_hba.conf)  was orphaned. Sending SIGKILL...
W1209 23:01:40.383227 26287 pg_wrapper.cc:505] PostgreSQL server exited with code 9
I1209 23:01:40.383466 26287 pg_wrapper.cc:521] Restarting PostgreSQL server
W1209 23:01:40.386018 26228 subprocess.cc:190] Failed to Wait(): Runtime error (yb/util/subprocess.cc:405): Unable to wait on child: No child processes (system error 10)
I1209 23:01:40.405074 26287 pg_wrapper.cc:275] PostgreSQL server running as pid 26500
developer@pluriza-dev1:~/yugabyte-2.0.7.0$ `

**Comment by rkarthik007** [comment]
Hi @dacrypt,

Could you please send across your tserver and postgres process logs? It should be in the following directory:
```
/home/developer/yugabyte-data/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO
/home/developer/yugabyte-data/node-1/disk-1/yb-data/tserver/logs/postgresql.log
/home/developer/yugabyte-data/node-1/disk-1/tserver.err
```

@ddorian can help you in case you're not able to find it.

**Comment by ddorian** [comment]
Closed because of no response.
