### ISSUE TITLE
[DOCS][YCQL] Document "RETURNS STATUS AS ROW" clause

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#3125]
The main idea is that when executing a batch in (Y)CQL, the protocol just allows returning one error/return status.
So, if one statement fails with an error or, for conditional DMLs, some are not applied because of failing the IF condition, the driver/application cannot accurately identify the relevant statement(s), it will just receive one general error/return-status for the whole batch.
Therefore, it is not trivial/possible for an application to react to such failures appropriately (e.g. retry, abort, change some parameters, for either entire batch or just the relevant statements etc).

The `RETURNS STATUS AS ROW`  feature addresses this limitation.
If used, the (write) statement will return its status (whether applied, unapplied, or errored-out with a message) as a regular CQL row that the application can inspect and decide what to do.
In the case of a batch (which is its intended use-case), it is required that either none or all statements use `RETURNS STATUS AS ROW`.
This is so that when executing `n` statements in a batch with `RETURN STATUS AS ROW`  it will always return `n` rows (in the same order as the statements) and the app can easily inspect the result.
Similarly, it is required that `RETURN STATUS AS ROW` is used for batches containing conditional DMLs.
This is because, for conditional DMLs (which are normally not allowed in batches), any subset of them could fail due to their `IF` condition so only returning rows for them would make it impossible to identify which ones actually failed. 

To distinguish between the two not-applied cases (error vs condition is false) there is a (error) message column in the return row that will be null for not-applied and filled-in for errors.
Conversely, there will be one column for each table column which will be null for errors but filled-in for not-applied (justifying the decision to not apply)
For instance:
-  Set up a simple table
    ```
    cqlsh:sample> create table test(h int, r int, v list<int>, primary key(h,r));
    cqlsh:sample> insert into test(h,r,v) values (1,1,[1,2]);
    ```

- `IF` condition false.
    ```
    cqlsh:sample> update test set v[2] = 4 where h = 1 and r = 1 if v[1] = 3 returns status as row;
     [applied] | [message] | h | r | v
    -----------+-----------+---+---+--------
         False |      null | 1 | 1 | [1, 2]
    ```
- `IF` condition true but error.
    ```
    cqlsh:sample> update test set v[20] = 4 where h = 1 and r = 1 if v[1] = 2 returns status as row;
     [applied] | [message]                                                                              | h    | r    | v
    -----------+----------------------------------------------------------------------------------------+------+------+------
         False | Unable to replace items into list, expecting index 20, reached end of list with size 2 | null | null | null
    ```

- `IF` condition true (applied).
    ```
    cqlsh:sample> update test set v[0] = 4 where h = 1 and r = 1 if v[1] = 2 returns status as row;
     [applied] | [message] | h    | r    | v
    -----------+-----------+------+------+------
          True |      null | null | null | null
    ```
- Final result.
    ```
    cqlsh:sample> select * from test;
     h | r | v
    ---+---+--------
     1 | 1 | [4, 2]
    (1 rows)
    ```

**Comment by kmuthukk** [comment]
hi @ddorian - 

We need to add documentation for this -- for both single statement as well as batch operations.

A slack user recently asked:

https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1590346922230700

<< if i do a session.ExecuteBatch() to run something like insert into ...  if not exists returns status as row ... how do i get the return from the query? >>
