### ISSUE TITLE
DNS resolution failures in Raft when binding to hostnames

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#313]
As per later findings in #128, we discovered some issues in the Raft flow after adding better control over DNS resolution. In particular, Raft was failing to generate Peer objects, which would fail bookkeeping and ultimately break a part of the protocol. This is most easily visible when we remove a node and its DNS entry, such that internal DNS resolution breaks.

**Comment by spolitov** [comment]
Fixed
