### ISSUE TITLE
Add a checkbox to hide yugabytedb modal intro dialog permanently

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#3138]
On the first yugaware page load for a yugabyted imported universe, we show an intro modal dialog (https://github.com/yugabyte/yugabyte-db/blob/daf2e81a5700ff3dd62314a921328a5a4a24f28d/managed/ui/src/pages/AuthenticatedComponent.js#L120).

Right now, X-ing the dialog causes it to never show again. Could we make this behavior be triggered by a checkbox instead? ("Do not show this message in the future"). Right now, it is too easy to X it out by instinct and miss the messaging entirely.

@yb-andrew : How difficult is this to do? 

cc: @WesleyW

**Comment by yb-andrew** [comment]
This is easy to do. I can get a fix out tomorrow.
