### ISSUE TITLE
YSQL not support cluster connections?

### ISSUE THREAD

**Issue by sain801028** [yugabyte/yugabyte-db#3156]
Does YSQL not support cluster connections?
I can't find it in the official example
https://docs.yugabyte.com/latest/quick-start/build-apps/go/ysql-pq/#create-the-application

What if there is a problem with the connection?

Will YSQL give a new master?

I hope that when something goes wrong, YSQL can automatically return me new master

Please let me know if I have a wrong idea.

**Comment by ddorian** [comment]
hi @sain801028 

The YSQL driver is not cluster aware. 

For now, there are several ways:

1. haproxy http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#option%20pgsql-check providing the list of servers and using pgsql-check to see if servers are up
2. https://github.com/awslabs/pgbouncer-rr-patch
3. by providing a list of ips to tservers and using a routing function (example: returning a random server)
4. implementing on the client, keeping a connection pooler for each tserver and randomly using one on each session
5. https://github.com/yandex/odyssey as connection pooler
6. https://www.pgbouncer.org/

does that satisfy your question ?

**Comment by sain801028** [comment]
I have a question
I don't know who will be "master"

does it matter?

**Comment by ddorian** [comment]
> I have a question
> I don't know who will be "master"
> 
> does it matter?

All nodes will satisfy every query.

**Comment by rkarthik007** [comment]
Hi @sain801028 @ddorian -

We are working on a clustered driver here: https://github.com/yugabyte/jdbc-yugabytedb

Please let us know if this is of interest, we would love to work with you if you are up to testing it out.
