### ISSUE TITLE
Font weight is not respected on Chrome

### ISSUE THREAD

**Issue by Arnav15** [yugabyte/yugabyte-db#3158]
The UI on Safari shows the YW text differently due to the font weight. Chrome apparently does not care about it.

**Comment by yb-andrew** [comment]
Known issue: https://stackoverflow.com/questions/13114417/open-sans-google-web-fonts-rendering-in-chrome
I recommend changing the fonts to standard 500 or bold 700.

**Comment by yb-andrew** [comment]
I believe with the latest font changes and font-weight changes, the text in Safari should look the same as Chrome.
