### ISSUE TITLE
[YSQL] "ALTER TABLE t DROP CONSTRAINT t_pk" succeeds but should fail

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#3163]
YB, through Version 2.0.6, treats a table's PK constraint as immutable. If a table is created with no PK, then you cannot add one because it uses an internal row identifier that's inaccessible to the user. Specifically, following this:
```
create table t(k1 int, v varchar);
```
these fail:
```
alter table t add constraint t_pk primary key(k1);
```
and
```
alter table t add column k2 int constraint t_pk primary key;

```
And If a table is created with a PK, then you cannot (or, more carefully, _are supposed not to be able to_) change anything about its specification or any value in any column that the constraint spans. See Issue #1822. Specifically, following this:
```
create table t(
  k1 int,
  k2 varchar(10),
  v varchar,
  constraint t_pk primary key(k1, k2));
insert into t(k1, k2, v) values(1, 'x', 'dog');
```
these fail:
```
alter table t drop column k1;
```
and
```
update t set k1 = 2 where k1 = 1 and k2 = 'x';
```
This also fails:
```
alter table t alter column k1 type varchar(20);
```
but the failure message is the same when this change is attempted on a column that's not spanned by the PK.

However, this quietly succeeds:
```
alter table t drop constraint t_pk
```
**This is a bug.**

Now, following this starting state:
```
 k1 | k2 |  v  
----+----+-----
  1 | x  | dog
```
this `insert` attempt:
```
insert into t(k1, k2, v) values(1, 'x', 'cat');
```
causes this error:
```
ERROR:  duplicate key value violates unique constraint "t"
```
Yet `\d t` shows that table `t` has no constraints. In other words, you're left in an undefined—and incomprehensible—state.

**Comment by frozenspider** [comment]
Fixed in 4e823dd: attempting to drop a primary key constraint now results in
```
ERROR:  dropping a primary key constraint is not yet supported
```
