### ISSUE TITLE
Verify yb-master and yb-tserver started by yugabyted

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#3172]
We had a bug in the following scenario:

* yugabyted starts master and tserver
* There are existing master and tserver running in the bg. This will cause yugabyted started master and tserver to eventually fail
* yugabyted checks for master and tserver success by querying through yb-admin. yb-admin talks to existing older master and tservers and returns success.
* yugabyted will bring YW pointing to the existing master and tserver
* Eventually, yugabyted realises the error by looking at master/tserver log files and brings the whole setup down.

One solution to this is to explicitly bring up master and tserver with a specific cluster_uuid via master cmd line flags and verify via yb-admin that this is what we are talking to.

**Comment by WesleyW** [comment]
Added in 7724e09230
