### ISSUE TITLE
[YCQL] index not getting used on upgrade from 1.3 to 2.0.5

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#3175]
[EDIT: Issue applies to transactional indexes also.]

Consider a table with a non-transactional index create on 1.3.0.0
```
CREATE TABLE blocks (
    k int PRIMARY KEY,
    time int,
    height bigint
) WITH transactions = {'enabled': 'false'};

CREATE INDEX blocks_height ON blocks (height, k)
   WITH CLUSTERING ORDER BY (k ASC)
   AND transactions = {'enabled': 'false', 'consistency_level': 'user_enforced'};
```

The query plan is as one would expect:
```
cqlsh> explain select * from blocks where height = 1 limit 1;
 QUERY PLAN
----------------------------------------------
 Index Scan using k.blocks_height on k.blocks
   Key Conditions: (height = 1)
```

After upgrading the DB to a 2.0.5.2, the query plan is no longer using the index, but ends up doing a full scan:
```
cqlsh:k> explain select * from blocks where height = 1 limit 1;
 QUERY PLAN
------------------------------
 Limit
   ->  Seq Scan on k.blocks
         Filter: (height = 1)
```

However, if the table & index are created from the start on 2.0.5.2 -- then that case does not suffer from the issue. 

The issue seems specific to upgrade path.

**Comment by ndeodhar** [comment]
@nocaway Can we close this issue?

**Comment by kmuthukk** [comment]
Yes - this can be closed. Fixed in https://github.com/yugabyte/yugabyte-db/commit/dfb03085b3b1d1c47c37226bd219cc5feb403544.
