### ISSUE TITLE
[YCQL] 'kong migrations bootstrap' fails to create Indexes with Yugabyte.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#3178]
`kong migrations bootstrap --vv`
failed with the error from the YB Server:
```
HOST:EXEC CREATE INDEX IF NOT EXISTS services_name_idx ON services(name)
SEND body_bytes = '"�Invalid Table Definition. Transactions cannot be enabled in an index of a table without transactions enabled.
CREATE INDEX IF NOT EXISTS services_name_idx ON services(name)
^^^^^^
 (ql error -302)'
```

Original issue:  https://github.com/yugabyte/yugabyte-db/issues/2829

**Comment by OlegLoginov** [comment]
Log for Kong requests:
```
$ kong migrations bootstrap --vv
2019/11/27 21:23:23 [verbose] Kong: 1.4.0
2019/11/27 21:23:23 [debug] Lua: LuaJIT 2.1.0-beta3
2019/11/27 21:23:23 [debug] database = "cassandra"
HOST:EXEC         SELECT data_center,rpc_address,release_version FROM system.local
HOST:EXEC         SELECT peer,data_center,rpc_address,release_version FROM system.peers
HOST:EXEC SELECT * FROM system_schema.keyspaces
              WHERE keyspace_name = ?
HOST:EXEC SELECT * FROM system_schema.tables WHERE keyspace_name = ?
HOST:EXEC         SELECT COUNT(*) FROM system_schema.tables
         WHERE keyspace_name = ? AND table_name = ?
2019/11/27 21:23:23 [info] Bootstrapping database...
HOST:EXEC       CREATE KEYSPACE IF NOT EXISTS "kong"
      WITH REPLICATION =         {'class': 'SimpleStrategy', 'replication_factor': 1}
HOST:EXEC       CREATE TABLE IF NOT EXISTS schema_meta(
        key             text,
        subsystem       text,
        last_executed   text,
        executed        set<text>,
        pending         set<text>,
        PRIMARY KEY (key, subsystem)
      )
HOST:EXEC     CREATE TABLE IF NOT EXISTS locks(
      key text PRIMARY KEY,
      owner text
    ) WITH default_time_to_live = 60
HOST:EXEC     INSERT INTO locks(key, owner)
      VALUES(?, ?)
      IF NOT EXISTS
      USING TTL 60
2019/11/27 21:23:23 [debug] running migration: 000_base
HOST:EXEC CREATE TABLE IF NOT EXISTS cluster_events(
        channel text,
        at      timestamp,
        node_id uuid,
        id      uuid,
        data    text,
        nbf     timestamp,
        PRIMARY KEY (channel, at, node_id, id)
      ) WITH default_time_to_live = 86400
HOST:EXEC CREATE TABLE IF NOT EXISTS services(
        partition       text,
        id              uuid,
        created_at      timestamp,
        updated_at      timestamp,
        name            text,
        host            text,
        path            text,
        port            int,
        protocol        text,
        connect_timeout int,
        read_timeout    int,
        write_timeout   int,
        retries         int,
        PRIMARY KEY     (partition, id)
      )
HOST:EXEC CREATE INDEX IF NOT EXISTS services_name_idx ON services(name)
READ BODY: ERROR: 'Invalid Table Definition. Transactions cannot be enabled in an index of a table without transactions enabled.
CREATE INDEX IF NOT EXISTS services_name_idx ON services(name)
^^^^^^
 (ql error -302)'  '8704'
HOST:EXEC     DELETE FROM locks WHERE key = ? IF owner = ?
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:63: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:56: [Cassandra error] failed to run migration '000_base' up: [Invalid] Invalid Table Definition. Transactions cannot be enabled in an index of a table without transactions enabled.
CREATE INDEX IF NOT EXISTS services_name_idx ON services(name)
^^^^^^
 (ql error -302)
```
Kong is using Apache Cassandra's indexes as it's seen from the log.

**Comment by OlegLoginov** [comment]
Possible solution: to add an additional G-Flag to add transactions by default for all new tables.
`CREATE TABLE ... WITH transactions = {'enabled':true};`
(Or Kong code can be changed to add transactions.)

**Comment by ddorian** [comment]
From the log `Transactions cannot be enabled in an index of a table without transactions enabled.`.

**Comment by ddorian** [comment]
1. change defaults to transactional tables (transactions can't be enabled after the fact)
2. fix kong
3. add docs section for kong
4. add gflag

I would think 1. And making `transaction off` an optimization.

And I'd like 3. We have many integrations, but many are lacking some features that confuse users.

Example: hasura uses **listen/notify**. But it's not scalable even in single-server-postgresql. 

For scalability they use https://github.com/hasura/graphql-engine/blob/master/architecture/live-queries.md . And we support this. (still need to setup partitioning right!, so it's another gotcha)

We can keep a faq/section for different tools in cassandra/postgresql space of gotchas/recommendations.

**Comment by OlegLoginov** [comment]
Personally I prefer [4], just because [1] can affect performance for other products/users.

I like [3] as an idea to have all known integration problems in one place - per product.

**Comment by ddorian** [comment]
Working on migrations I see these fixes:

1. we don't support `CREATE INDEX ON acls(group);` `group` is probably a reserved keyword? it works with `CREATE INDEX ON acls(group);`. Should we fix this or in kong ?
2. When adding duplicate columns, we return a different error compared to cassandra. This is used in migrations and the errors are ignored. We should change to cassandra errors, correct ?
3. Kong has internal cache and doesn't use the db in the hot path (say every request). We can add a gflag that tables get created transactionally.

This way we fix cassandra compatibility, create index on reserved columns, add gflag.
The reason is to work with no changes on kong.

Alternative is to fix kong.

Middleground is to add gflag. And having 1&2 as pull request on kong.

@OlegLoginov does that make sense ?

**Comment by ddorian** [comment]
Kong also supports Postgresql, but it had much more errors:

1. alter index "rename"
2. alter table "rename constraint"
3. alter column type "json -> jsonb" using "column::JSONB"
4. gin index
5. ALTER TABLE IF EXISTS
6. ALTER TABLE  "plugins" ADD "cache_key" TEXT UNIQUE

**Comment by ddorian** [comment]
@OlegLoginov issues for kong:
https://github.com/yugabyte/yugabyte-db/issues/3315
https://github.com/yugabyte/yugabyte-db/issues/3314
https://github.com/yugabyte/yugabyte-db/issues/3313

**Comment by OlegLoginov** [comment]
To allow Kong creating indexes he following command line key must be used for the `yb-tserver` process:  `--cql_table_is_transactional_by_default`. (The gflag was added as a fix for #3313.)

**Comment by ddorian** [comment]
@OlegLoginov thank you
Compiling latest master to test kong again.

**Comment by ddorian** [comment]
@OlegLoginov confirm migrations work in versions 1.4 & 2.0 with only adding gflag `--cql_table_is_transactional_by_default`.
