### ISSUE TITLE
Java client system requirements listed in README are outdated 

### ISSUE THREAD

**Issue by eliahburns** [yugabyte/yugabyte-db#3180]
In the [README](https://github.com/yugabyte/yugabyte-db/blob/master/java/README.md) for the Java client declares system requirements of Java 7 and protobuf 2.6.1; however, the pom.xml file targets JDK 1.8 and uses a protobuf version of 3.5.1

**Comment by eliahburns** [comment]
I just submitted a PR of #3181, so I'll close this.

**Comment by rkarthik007** [comment]
Thanks for the fix @eliahburns, much appreciated! Let me know if you would like to get involved in other things.

Also, as a thank you, we would love to send you a tshirt (we're putting together a contributor program - still working on the webpage for this). Do you mind dropping me a note at karthik [at] yugabyte [dot] com and I can get this kicked off.
