### ISSUE TITLE
[yugabyted] yugabyted timeout when vanilla postgresql is running

### ISSUE THREAD

**Issue by Zhongweizhao** [yugabyte/yugabyte-db#3200]
I have vanilla postgresql installed and running. It prevents yugabyte from binding the port 5433. However yugabyted timeout without reporting any error information.

```
ssh zhongweizhao@zhaozw:~/yugabyte-2.0.8.0$ bin/yugabyted start
Starting YugabyteDB...
System checks ✅         
Timed out trying to start yugabyted daemon.
For more information, check the logs in /home/zhongweizhao/yugabyte-2.0.8.0/yugabyte-logs
ssh zhongweizhao@zhaozw:~/yugabyte-2.0.8.0$ 
```

[logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/3990475/logs.tar.gz)

**Comment by WesleyW** [comment]
Issue caused by port being in use.
