### ISSUE TITLE
[yugabyted] Esc key does not close popups

### ISSUE THREAD

**Issue by jj-kim** [yugabyte/yugabyte-db#3211]
In the `yugabyted` UI, it is not uncommon to encounter popup windows.  One would expect these windows to close by pressing the Escape key, but it currently does not.  Add that support.

**Comment by iSignal** [comment]
Jason, is this specific to the yugabyted pop up or have you encountered other pop ups in yugaware that do the same thing?

**Comment by jj-kim** [comment]
I have not encountered this in the general master or tserver UIs after having tried to for a bit.  I have just tried Yugaware, and I am getting this behavior with expanding the maps and "Restore Backup" button.
