### ISSUE TITLE
[docs] Extract tar archives as stream

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#3214]
Commands for downloading and running Yugabyte need not go through a two-step approach of downloading the tar and (decompressing and) extracting the tar.  They can be combined as in the following example:

```sh
  curl https://downloads.yugabyte.com/yugabyte-2.0.8.0-linux.tar.gz \
    | tar xzv \
  && cd yugabyte-2.0.8.0 \
  && ./bin/post_install.sh
```

Furthermore, this will not leave tar files behind.

This change should apply to various areas of documentation, such as

* https://docs.yugabyte.com/latest/quick-start/install
* https://download.yugabyte.com/local

**Comment by polarweasel** [comment]
I'd rather not encourage people to pipe the output of a random web download to a command...
