### ISSUE TITLE
[yugabyte] Compile error on MACOS at scanner.cc

### ISSUE THREAD

**Issue by graffido** [yugabyte/yugabyte-db#3218]
Hi,

I try to compile the YB on my MAC(macOS 10.15.2), and happen to the below compile error message. 

```
( cd "/Users/bingo/projects/yugabyte-db/build/debug-clang-dynamic/src/yb/yql/cql/ql/parser" && YB_THIRDPARTY_DIR=/Users/bingo/projects/yugabyte-db/thirdparty /usr/bin/clang++ -Dql_parser_EXPORTS -I/Users/bingo/projects/yugabyte-db/build/debug-clang-dynamic/src -I/Users/bingo/projects/yugabyte-db/ent/src -I/Users/bingo/projects/yugabyte-db/src -I/usr/local/opt/flex/include -isystem /usr/local/opt/openssl/include -isystem /Users/bingo/projects/yugabyte-db/thirdparty/installed/clang_uninstrumented/include -isystem /Users/bingo/projects/yugabyte-db/thirdparty/installed/common/include -isystem /usr/local/opt/icu4c/include -Werror -fno-strict-aliasing -msse4.2 -Wall -Wno-sign-compare -Wno-deprecated -Winvalid-pch -pthread -DBOOST_BIND_NO_PLACEHOLDERS -DROCKSDB_PLATFORM_POSIX -DROCKSDB_USING_THREAD_STATUS=0 -DBOOST_ERROR_CODE_HEADER_ONLY -DYB_COMPILER_TYPE=clang -DYB_COMPILER_VERSION=11.0 -DROCKSDB_LIB_IO_POSIX -DBZIP2 -DSNAPPY -DZLIB -D__STDC_FORMAT_MACROS -Wno-deprecated-declarations -DGFLAGS=gflags -Wnon-virtual-dtor -Werror=enum-compare -Werror=reorder -Werror=switch -Werror=return-type -Werror=non-virtual-dtor -Werror=string-plus-int -Werror=return-stack-address -Werror=implicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wthread-safety-analysis -DOS_MACOSX -D_GLIBCXX_USE_CXX11_ABI=0 -DYB_HEADERS_NO_STUBS=1 -ggdb -O1 -fno-omit-frame-pointer -Wno-ambiguous-member-template -Wimplicit-fallthrough -Qunused-arguments -fPIC -DTCMALLOC_ENABLED -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=gnu++14 -o CMakeFiles/ql_parser.dir/scanner.cc.o -c /Users/bingo/projects/yugabyte-db/src/yb/yql/cql/ql/parser/scanner.cc )  # Compiler exit code: 1.

/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/yb/yql/cql/ql/parser/scanner.cc:88:18: error: no member named 'token' in 'yb::ql::GramProcessor::symbol_type'
  if (lookahead_.token() != 0) {
      ~~~~~~~~~~ ^
src/yb/yql/cql/ql/parser/scanner.cc:98:21: error: no member named 'token' in 'yb::ql::GramProcessor::symbol_type'
  switch (cur_token.token()) {
          ~~~~~~~~~ ^
src/yb/yql/cql/ql/parser/scanner.cc:116:58: error: no member named 'token' in 'yb::ql::GramProcessor::symbol_type'
  GramProcessor::token_type next_token_type = lookahead_.token();
                                              ~~~~~~~~~~ ^
src/yb/yql/cql/ql/parser/scanner.cc:117:21: error: no member named 'token' in 'yb::ql::GramProcessor::symbol_type'
  switch (cur_token.token()) {
          ~~~~~~~~~ ^
4 errors generated.

Input files:
  src/yb/yql/cql/ql/parser/scanner.cc
Output file (from -o): CMakeFiles/ql_parser.dir/scanner.cc.o
```

The token function seems not being generate.

**Some build tools list below**
```
BenMac:yugabyte-db bingo$ flex --version
flex 2.6.4
BenMac:yugabyte-db bingo$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
BenMac:yugabyte-db bingo$ bison --version
bison (GNU Bison) 3.5
Written by Robert Corbett and Richard Stallman.
```

**Comment by psudheer21** [comment]
I am facing the same issue while compiling the code.
Did you figure out the issue here?

**Comment by mbautin** [comment]
Hi @graffido , @psudheer21, what version of flex and bison are you using? We usually install flex and bison using Homebrew on macOS. E.g. on my machine I have:

```
$ brew list flex
/usr/local/Cellar/flex/2.6.4_1/bin/flex
/usr/local/Cellar/flex/2.6.4_1/bin/flex++
/usr/local/Cellar/flex/2.6.4_1/include/FlexLexer.h
/usr/local/Cellar/flex/2.6.4_1/lib/libfl.2.dylib
/usr/local/Cellar/flex/2.6.4_1/lib/ (2 other files)
/usr/local/Cellar/flex/2.6.4_1/share/doc/ (5 files)
/usr/local/Cellar/flex/2.6.4_1/share/info/ (3 files)
/usr/local/Cellar/flex/2.6.4_1/share/locale/ (23 files)
/usr/local/Cellar/flex/2.6.4_1/share/man/man1/flex.1

$ brew list bison
/usr/local/Cellar/bison/3.4.1/bin/bison
/usr/local/Cellar/bison/3.4.1/bin/yacc
/usr/local/Cellar/bison/3.4.1/lib/liby.a
/usr/local/Cellar/bison/3.4.1/share/aclocal/bison-i18n.m4
/usr/local/Cellar/bison/3.4.1/share/bison/ (28 files)
/usr/local/Cellar/bison/3.4.1/share/doc/ (42 files)
/usr/local/Cellar/bison/3.4.1/share/info/bison.info
/usr/local/Cellar/bison/3.4.1/share/man/ (2 files)
```

**Comment by psudheer21** [comment]
I had used brew as well to install those:
The bison version I have is new though:

$ brew list flex
/usr/local/Cellar/flex/2.6.4_1/bin/flex
/usr/local/Cellar/flex/2.6.4_1/bin/flex++
/usr/local/Cellar/flex/2.6.4_1/include/FlexLexer.h
/usr/local/Cellar/flex/2.6.4_1/lib/libfl.2.dylib
/usr/local/Cellar/flex/2.6.4_1/lib/ (2 other files)
/usr/local/Cellar/flex/2.6.4_1/share/doc/ (5 files)
/usr/local/Cellar/flex/2.6.4_1/share/info/ (3 files)
/usr/local/Cellar/flex/2.6.4_1/share/locale/ (23 files)
/usr/local/Cellar/flex/2.6.4_1/share/man/man1/flex.1

$ brew list bison
/usr/local/Cellar/bison/3.5/bin/bison
/usr/local/Cellar/bison/3.5/bin/yacc
/usr/local/Cellar/bison/3.5/lib/liby.a
/usr/local/Cellar/bison/3.5/share/aclocal/bison-i18n.m4
/usr/local/Cellar/bison/3.5/share/bison/ (28 files)
/usr/local/Cellar/bison/3.5/share/doc/ (42 files)
/usr/local/Cellar/bison/3.5/share/info/bison.info
/usr/local/Cellar/bison/3.5/share/man/ (2 files)

**Comment by psudheer21** [comment]
Let me install the older version and give it a shot.
WIll post an update soon.

**Comment by psudheer21** [comment]
I reinstalled the older version and I am still getting the error.
So that doesn't seem to be the problem.

**Comment by mbautin** [comment]
@psudheer21 would you mind sharing the build log (including the CMake output)?

**Comment by psudheer21** [comment]
[CMake_error.txt](https://github.com/yugabyte/yugabyte-db/files/4017274/CMake_error.txt)
Hope this helps.

**Comment by mbautin** [comment]
@psudheer21 can you try to build with `./yb_build.sh --clean --save-log` and share the log? In the log above I don't see the CMake configuration part, it looks like it has already been done in a prior run.

**Comment by psudheer21** [comment]
The build again with a --clean option compiled the code properly.
Maybe there is some dependency issue that is pretty rarely hit.

**Comment by psudheer21** [comment]
Just realised, that after changing the bison version to the older one, I hadn't done a clean build. 
So the current code working can be because of the older version of bison is correctly interpreting the .y files.

I will still need to verify this though.

**Comment by graffido** [comment]
confirm @psudheer21, downgrade my bison from bison-3.5 to bison-3.4.2 fix this issue

**Comment by rkarthik007** [comment]
Nice catch @psudheer21, and thanks for confirming the bison version @graffido!

This would be good to add to the docs, somewhere here: https://docs.yugabyte.com/latest/contribute/core-database/build-from-src/

**Comment by psudheer21** [comment]
So instead of installing the bison using the regular 'brew install bison' what we need to do is install it using  'brew install https://github.com/Homebrew/homebrew-core/tree/ee89a1d59df03f495a85c15e253b60299082ab9d'
This command installs the 3.4.1 version of bison that works.

@rkarthik007 Who is the concerned person that can help me modify the docs?

**Comment by rkarthik007** [comment]
@psudheer21 - you should be able to get going based on the instructions here: https://github.com/yugabyte/yugabyte-db/tree/master/docs

Please holler if you run into any issues. cc @schoudhury @stevebang

**Comment by mbautin** [comment]
BTW we've added Bison to the third-party archive and standardized on using Bison 3.4.1 for now: https://github.com/yugabyte/yugabyte-db-thirdparty/blob/master/build_definitions/bison.py

Bison no longer needs to be installed globally on the build system.
