### ISSUE TITLE
Support unique secondary index

### ISSUE THREAD

**Issue by robertpang** [YugaByte/yugabyte-db#322]
Currently, YugaByte DB supports non-unique secondary index. In some use cases, the application may require the index to be unique.

For example, consider an `employee` table which has `id` as the primary key column, and another `email` column where the entries need to be unique. This could be achieved as follows:
```
CREATE TABLE employee(id text PRIMARY KEY, email text, name text);
CREATE UNIQUE INDEX ON employee(email) covering (name);
```
Insert statements would look as follows:
```
INSERT INTO employee(id, email, name) VALUES (...) IF NOT EXISTS;
```

**Comment by rohitjoshi** [comment]
For `redis` interface, `add` of two key-value pairs atomically would be helpful as well.  

e.g. 
```
 EVAL  {
    if SETNX( id, name) == 1 && SETNX(id, email) == 1 then
      return 1
   end
```
    
}

**Comment by kmuthukk** [comment]
hi @rohitjoshi : 

Currently, we don't support Lua scripting in our our Redis-compatible offering. For now, for multiple table ACID or multi-key ACID operations spanning shards- we suggest the using our Cassandra based interface with the extensions (YCQL). But we can look into adding this type of capability in the Redis interface in the future. 

In your specific example, did you mean for both keys to have the same `id` (where `name` & `email` are different fields of a redis hash map) or could they be two different keys that might fall on two different shards (and hence different servers).

regards,
Kannan

**Comment by rohitjoshi** [comment]
@kmuthukk thanks.  thanks correcting.  I am looking for `id => name ` and `name=>email`

which allows both way lookup.

**Comment by robertpang** [comment]
Unique secondary index for YCQL has been implemented in commit [3769c97](https://github.com/YugaByte/yugabyte-db/commit/3769c9731b21207d4217838682c151baf8ccbe56).

**Comment by rohitjoshi** [comment]
👍 looking forward to try this out.

**Comment by kmuthukk** [comment]
Thx @rohitjoshi . We'll get a update CE tar'ball with this change out soon.
