### ISSUE TITLE
Ysqlsh does not work when root directory renamed to other then yugabyte.

### ISSUE THREAD

**Issue by vp15591** [yugabyte/yugabyte-db#3228]
Tried running `ysqlsh` after renaming yugabyte directory to yugabyte-old its not working but before it was working. 

Yugabyte Version: - 2.0.8.0
```
----------------------------------------------------------------------
|                         YugabyteDB Version                         |
----------------------------------------------------------------------
| Version        : 2.0.8.0-b5                                        |
| Build Time     : 11 Dec 2019 05:31:02 UTC                          |
| Build Hash     : 5e371e4d2b023a92ea24d0bdbdfe393540c46d0a          |
----------------------------------------------------------------------

```

```
vaibhav@instance-3:/opt/yugabyte-old/postgres/bin$ ./ysqlsh
-bash: ./ysqlsh: No such file or directory
```
```
vaibhav@instance-3:/opt/yugabyte/postgres/bin$ ./ysqlsh
ysqlsh (11.2-YB-2.0.8.0-b0)
Type "help" for help.

yugabyte=#
```

**Comment by rkarthik007** [comment]
Hi @vp15591,

Renaming the directory would not work, because we add in some library paths into the binary. You would need to rerun the `post-install.sh` script after the directory is changed. But what's the reason you need to move the directory?

**Comment by vp15591** [comment]
Thanks @rkarthik007, it worked after running `post-install.sh` script.

**Comment by takwid** [comment]
Hi @vaibhavp Sorry for my question but am new to this. 

I succeeded with
```
wget https://downloads.yugabyte.com/releases/2.13.1.0/yugabyte-2.13.1.0-b112-linux-x86_64.tar.gz
tar xvfz yugabyte-2.13.1.0-b112-linux-x86_64.tar.gz && cd yugabyte-2.13.1.0/
./bin/post_install.sh
./bin/yugabyted start
```
On running the next command

`./bin/ysqlsh`

I get the following results..

`bash: ./bin/ysqlsh: No such file or directory`

Can you help? I will greatly appreciate it.
