### ISSUE TITLE
CustomerProfile form couldn't be submitted with an empty email field 

### ISSUE THREAD

**Issue by vitpankin** [yugabyte/yugabyte-db#3231]
After RBAC update UI doesn't receive the customer.email from Java and email field, which is required in the form, stays empty. Therefore form couldn't be submitted. 

Possibly it could be cut or marked as non-required in UI but CustomerRegisterFormData definition still has email as a required field.

**Comment by bmatican** [comment]
@Arnav15 is this still relevant? did this get fixed already? if yes, can we reference a commit and close it.

**Comment by Arnav15** [comment]
Fixed by: https://github.com/yugabyte/yugabyte-db/commit/78e2dcee40731db4cf010471993e5cccb7cc9592
