### ISSUE TITLE
[docs] Add YSQL support into Backup and restore section and Data migration section

### ISSUE THREAD

**Issue by jk-1** [yugabyte/yugabyte-db#3241]
These sections have only support for YCQL:

https://docs.yugabyte.com/latest/manage/backup-restore/

https://docs.yugabyte.com/latest/manage/data-migration/

Add YSQL support for backup / restore and bulk export / import.

In the reference guide there are tools ysql_dump and ysql_dumpall which can be used also for online backups. Restore is done by ysqlsh -f filename.

YSQL supports COPY command which can be used for export / import: https://docs.yugabyte.com/latest/api/ysql/commands/cmd_copy/

**Comment by stevebang** [comment]
@ddorian Review this and see what needs to be added. If nothing, then close this issue.
