### ISSUE TITLE
Deploying YugabyteDB on Openshift using helm chart fails.

### ISSUE THREAD

**Issue by samkulkarni20** [yugabyte/yugabyte-db#3250]
While using helm 3 to deploy YugabyteDB on openshift, the deployment fails with below error:
```create Pod yb-master-0 in StatefulSet yb-master failed error: pods "yb-master-0" is forbidden: unable to validate against any security context constraint: [spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]```

The current YugabyteDB chart contains an init container which specifically needs a Privileged service account. The default service account, which is used by helm 3 installs, does not have privileged access on openshift resulting in above error. 

Since there's no tiller with helm 3, we can't dictate which service account it should use for installs, leaving us with 2 options:
1. Make default service account privileged - meaning any and all helm 3 actions on the cluster will have Privileged access.
2. Update YugabyteDB helm chart to use a specific service account. Create a service account with that name & grant it Privileged access before installing YugabyteDB chart.

**Comment by rkarthik007** [comment]
I feel the right option is the second one, to create a service account.

@ramkumarvs - could you please add your thoughts as well?
