### ISSUE TITLE
[YSQL] Remove conflict b/w row lock and INSERT

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#3253]
Row locking statements with a condition on a table with a range key should not generate intents for the whole table but should rather generate intents on the rows specified by the condition.

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int, PRIMARY KEY(i ASC))` | |
| `INSERT INTO t VALUES (1), (2), (3)` | |
| `BEGIN ISOLATION LEVEL SERIALIZABLE` | |
| `SELECT * FROM t WHERE i = 1 FOR KEY SHARE` | |
| | `INSERT INTO t VALUES (4)` |
| `COMMIT` | |

Currently, the last commit errors out

```
ERROR:  Error during commit: Operation expired: Transaction expired or aborted by a conflict: 40001
```

In vanilla PostgreSQL, everything runs fine without waiting.

The cause seems to be from the row locking statement (`SELECT FOR`) adding an intent with a `DocPath` that is empty, signifying the full table.  This seems to be tied to how `DocPath`s on range keys are handled in general.

**Comment by kutayzorlu** [comment]
Error during commit: Operation expired: Transaction expired or aborted by a conflict: 40001

**Comment by kutayzorlu** [comment]
solved with :

:

hibernate.connection.isolation 2

Where

1: READ UNCOMMITTED
2: READ COMMITTED  ->  

do not use Serialized : 8 ! .. locking fully ..!

**Comment by pkj415** [comment]
The behaviour exists no more due to some changes in our explicit locking strategy.
