### ISSUE TITLE
[docs] [community] How does hardware (CPU, cores, ram, disk IOPS, etc) affect YB performance

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3259]
Explain how hardware choices affect YB performance...
- CPU
- number of cores
- RAM
- disk IOPS
- etc.

See: https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1576525583038400?thread_ts=1576469962.034700&cid=CG0KQF0GG

**Comment by ddorian** [comment]
I have put them here: https://github.com/yugabyte/yugabyte-db/pull/3222

**Comment by stevebang** [comment]
Closing -- duplicate of https://github.com/yugabyte/yugabyte-db/pull/3222
