### ISSUE TITLE
[docs] Add Crossplane, new Rook integration

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3265]
Document new Crossplane 0.4 release usage with Yugastore app.

See:

- https://blog.crossplane.io/crossplane-v0-4-new-rook-integration-supports-in-cluster-managed-database-alternatives-to-rds-cloudsql-and-azure-db/
- https://crossplane.io/docs/v0.4/stacks-guide-rook.html

**Comment by polarweasel** [comment]
@ymahajan Any reason to keep this ticket?

**Comment by lizayugabyte** [comment]
@aishwarya24 Are these integrations still on the table? If not, we should close this old ticket

**Comment by aishwarya24** [comment]
Confirmed with Yogesh and we can close it.
