### ISSUE TITLE
[docs] Discourage 2-region setups for RF=3

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3270]
Add to docs on deployments.

https://yugabyte.slack.com/archives/C58MY17GQ/p1576167294490400

Kannan Muthukkaruppan Dec 12th at 8:14 AM
We should discourage 2 region setups for RF=3 setup as they are not region disaster safe.
3 replies
Also sent to the channel

Dorian Hoxha  25 days ago
if RF=3 then 2 out of 3 regions need to be up ?
what if each region has 3 servers ? should be able to continue ?
so data won't be lost, but read/write won't work
Also sent to the channel ∙ Starred

Alan Caldera  25 days ago
In RF=3, and your failure domain is region (ie guarding against region failure) - then if 2 regions are up, you can make progress on writes. In the 2 region setup, even if you have an equal number of servers in each, YB will try to place 2 members of each raft group in 1 region and 1 in the other. If you lose the minority partner, everything is fine. But if the region with the majority partner (2 members) is lost, writes cannot continue.

Alan Caldera  25 days ago
@dorian ^^
:+1:

**Comment by lizayugabyte** [comment]
@polarweasel This is a very old ticket. Probably no longer relevant.
