### ISSUE TITLE
[docs] Review SPLIT INTO content for CDC/2DC docs

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3272]
Review content from Jimmy's blog about use of SPLIT INTO in 2DC deployments

See: https://docs.google.com/document/d/1eK4WtPqqm1F_kDobIU6YoX4zAaYyIiQ9DF3kiT05kzU/edit?usp=sharing

**Comment by lizayugabyte** [comment]
I don't think this review is still required.
@polarweasel Let me know if you think we should close this ticket.

**Comment by polarweasel** [comment]
Killing it now
