### ISSUE TITLE
[docs] Add glossary of terms

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3275]
Add *Glossary of terms* covering important terms and concepts..

For example:

- node
- replication factor (RF)
- server
- service
- tablet
- transaction
- transaction isolation level

**Comment by lizayugabyte** [comment]
I don't think this is necessary. What's your take, @polarweasel ? Should we close this ticket as "won't do"?

**Comment by polarweasel** [comment]
Yup, close it. We can revisit later, as it might be helpful as part of some dedicated tutorial material.
