### ISSUE TITLE
[YW] Navigating to the Edit Universe page does not load the AZSelectorTable

### ISSUE THREAD

**Issue by yb-andrew** [yugabyte/yugabyte-db#3290]
There's a rest API call to /universe_configure that is failing due to mismatched UUIDs between the cluster on the backend and the requested cluster UUID.

API call to universe_resources with the following payload:
> {"errorString":null,"deviceInfo":null,"universeUUID":"5dd8cca4-c467-40d9-9261-955dfc0d77c1","expectedUniverseVersion":-1,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":[{"nodeIdx":1,"nodeName":"yb-tserver-0_us-west1-b","nodeUuid":null,"cloudInfo":{"private_ip":"yb-tserver-0.yb-tservers.yb-dev-edit-test-us-west1-b.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"xsmall","subnet_id":null,"az":"us-west1-b","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","placementUuid":"9fe4ceb7-de06-41cd-9200-aa9adf6731f1","state":"Live","isMaster":false,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":true,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-master-0_us-west1-b","nodeUuid":null,"cloudInfo":{"private_ip":"yb-master-0.yb-masters.yb-dev-edit-test-us-west1-b.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"xsmall","subnet_id":null,"az":"us-west1-b","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","placementUuid":"9fe4ceb7-de06-41cd-9200-aa9adf6731f1","state":"Live","isMaster":true,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":false,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]}],"clusters":[{"uuid":"9fe4ceb7-de06-41cd-9200-aa9adf6731f1","clusterType":"PRIMARY","userIntent":{"universeName":"edit-test","provider":"db07118b-72ec-45c2-bdd8-719b2d392b53","providerType":"kubernetes","replicationFactor":1,"regionList":["fd75a358-00aa-4dfd-b670-5167989b44c6"],"preferredRegion":null,"instanceType":"xsmall","numNodes":1,"ybSoftwareVersion":"2.0.8.0-b5","accessKeyCode":"yugabyte-default","deviceInfo":{"volumeSize":100,"numVolumes":1,"diskIops":null,"storageClass":"standard","mountPoints":null,"storageType":null},"assignPublicIP":true,"useTimeSync":false,"enableYSQL":true,"enableNodeToNodeEncrypt":false,"enableClientToNodeEncrypt":false,"enableVolumeEncryption":false,"masterGFlags":{},"tserverGFlags":{},"instanceTags":{}},"placementInfo":{"cloudList":[{"uuid":"db07118b-72ec-45c2-bdd8-719b2d392b53","code":"kubernetes","regionList":[{"uuid":"fd75a358-00aa-4dfd-b670-5167989b44c6","code":"us-west","name":"US West","azList":[{"uuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","name":"us-west1-b","replicationFactor":1,"subnet":null,"numNodesInAZ":1,"isAffinitized":true}]}]}]},"index":0,"regions":[{"uuid":"fd75a358-00aa-4dfd-b670-5167989b44c6","code":"us-west","name":"US West","ybImage":null,"longitude":-121,"latitude":37,"zones":[{"uuid":"6df1ad95-9056-4a6d-9edd-f6117a5b8f6d","code":"us-west1-c","name":"us-west1-c","active":true,"subnet":null},{"uuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","code":"us-west1-b","name":"us-west1-b","active":true,"subnet":null},{"uuid":"10c213ab-9880-42ae-9478-fb6270781e24","code":"us-west1-a","name":"us-west1-a","active":true,"subnet":null}],"active":true,"details":null,"securityGroupId":null}]}],"nodePrefix":"yb-dev-edit-test","rootCA":null,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"nextClusterIndex":1,"allowInsecure":true,"importedState":"NONE","capability":"EDITS_ALLOWED"}

And a call to universe_configure with the following payload:
> {"errorString":null,"deviceInfo":null,"universeUUID":"5dd8cca4-c467-40d9-9261-955dfc0d77c1","expectedUniverseVersion":7,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":[{"nodeIdx":1,"nodeName":"yb-tserver-0_us-west1-b","nodeUuid":null,"cloudInfo":{"private_ip":"yb-tserver-0.yb-tservers.yb-dev-edit-test-us-west1-b.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"xsmall","subnet_id":null,"az":"us-west1-b","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","placementUuid":"9fe4ceb7-de06-41cd-9200-aa9adf6731f1","state":"Live","isMaster":false,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":true,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-master-0_us-west1-b","nodeUuid":null,"cloudInfo":{"private_ip":"yb-master-0.yb-masters.yb-dev-edit-test-us-west1-b.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"xsmall","subnet_id":null,"az":"us-west1-b","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","placementUuid":"9fe4ceb7-de06-41cd-9200-aa9adf6731f1","state":"Live","isMaster":true,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":false,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]}],"clusters":[{"uuid":"9fe4ceb7-de06-41cd-9200-aa9adf6731f1","clusterType":"PRIMARY","userIntent":{"universeName":"edit-test","provider":"db07118b-72ec-45c2-bdd8-719b2d392b53","regionList":["fd75a358-00aa-4dfd-b670-5167989b44c6"],"assignPublicIP":true,"useTimeSync":false,"enableYSQL":true,"enableNodeToNodeEncrypt":false,"enableClientToNodeEncrypt":false,"numNodes":2,"instanceType":"xsmall","ybSoftwareVersion":"2.0.8.0-b5","replicationFactor":1,"deviceInfo":{"volumeSize":100,"numVolumes":1,"mountPoints":null,"storageType":null,"diskIops":null},"accessKeyCode":"yugabyte-default","masterGFlags":[{}],"tserverGFlags":[{}],"providerType":"kubernetes"},"placementInfo":{"cloudList":[{"uuid":"db07118b-72ec-45c2-bdd8-719b2d392b53","code":"kubernetes","regionList":[{"uuid":"fd75a358-00aa-4dfd-b670-5167989b44c6","code":"us-west","name":"US West","azList":[{"uuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","name":"us-west1-b","replicationFactor":1,"subnet":null,"numNodesInAZ":1,"isAffinitized":true}]}]}]},"index":0,"regions":[{"uuid":"fd75a358-00aa-4dfd-b670-5167989b44c6","code":"us-west","name":"US West","ybImage":null,"longitude":-121,"latitude":37,"zones":[{"uuid":"6df1ad95-9056-4a6d-9edd-f6117a5b8f6d","code":"us-west1-c","name":"us-west1-c","active":true,"subnet":null},{"uuid":"8f6792cb-cea4-45bb-8d79-5e96995dcbb0","code":"us-west1-b","name":"us-west1-b","active":true,"subnet":null},{"uuid":"10c213ab-9880-42ae-9478-fb6270781e24","code":"us-west1-a","name":"us-west1-a","active":true,"subnet":null}],"active":true,"details":null,"securityGroupId":null}]}],"nodePrefix":"yb-dev-edit-test","rootCA":null,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"nextClusterIndex":1,"allowInsecure":true,"importedState":"NONE","capability":"EDITS_ALLOWED","currentClusterType":"PRIMARY","clusterOperation":"EDIT"}

In the current version, we have the call to universe_resources, with payload

> {"errorString":null,"deviceInfo":null,"universeUUID":"0a7cbf58-e81c-4065-8b91-b8779b615f0b","expectedUniverseVersion":-1,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":[{"nodeIdx":1,"nodeName":"yb-master-0_us-west1-c","nodeUuid":null,"cloudInfo":{"private_ip":"yb-master-0.yb-masters.yb-dev-yb-k8s-test-us-west1-c.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"small","subnet_id":null,"az":"us-west1-c","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"a6796904-0d9c-43b7-9cbe-53536ee1f659","placementUuid":"32660828-4da5-42b3-839f-686904e29c99","state":"Live","isMaster":true,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":false,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-master-0_us-west1-b","nodeUuid":null,"cloudInfo":{"private_ip":"yb-master-0.yb-masters.yb-dev-yb-k8s-test-us-west1-b.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"small","subnet_id":null,"az":"us-west1-b","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"4dd043c0-ceae-4b15-8f0f-1af1e96b6261","placementUuid":"32660828-4da5-42b3-839f-686904e29c99","state":"Live","isMaster":true,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":false,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-tserver-0_us-west1-c","nodeUuid":null,"cloudInfo":{"private_ip":"yb-tserver-0.yb-tservers.yb-dev-yb-k8s-test-us-west1-c.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"small","subnet_id":null,"az":"us-west1-c","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"a6796904-0d9c-43b7-9cbe-53536ee1f659","placementUuid":"32660828-4da5-42b3-839f-686904e29c99","state":"Live","isMaster":false,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":true,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-master-0_us-west1-a","nodeUuid":null,"cloudInfo":{"private_ip":"yb-master-0.yb-masters.yb-dev-yb-k8s-test-us-west1-a.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"small","subnet_id":null,"az":"us-west1-a","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"8d738202-fba6-409a-92c1-f31a6bc64824","placementUuid":"32660828-4da5-42b3-839f-686904e29c99","state":"Live","isMaster":true,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":false,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-tserver-0_us-west1-b","nodeUuid":null,"cloudInfo":{"private_ip":"yb-tserver-0.yb-tservers.yb-dev-yb-k8s-test-us-west1-b.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"small","subnet_id":null,"az":"us-west1-b","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"4dd043c0-ceae-4b15-8f0f-1af1e96b6261","placementUuid":"32660828-4da5-42b3-839f-686904e29c99","state":"Live","isMaster":false,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":true,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]},{"nodeIdx":1,"nodeName":"yb-tserver-0_us-west1-a","nodeUuid":null,"cloudInfo":{"private_ip":"yb-tserver-0.yb-tservers.yb-dev-yb-k8s-test-us-west1-a.svc.cluster.local","public_ip":null,"public_dns":null,"private_dns":null,"instance_type":"small","subnet_id":null,"az":"us-west1-a","region":"us-west","cloud":"kubernetes","assignPublicIP":true,"useTimeSync":false},"azUuid":"8d738202-fba6-409a-92c1-f31a6bc64824","placementUuid":"32660828-4da5-42b3-839f-686904e29c99","state":"Live","isMaster":false,"masterHttpPort":7000,"masterRpcPort":7100,"isTserver":true,"tserverHttpPort":9000,"tserverRpcPort":9100,"isRedisServer":true,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"isYqlServer":true,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"isYsqlServer":true,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"allowedActions":["REMOVE","STOP"]}],"clusters":[{"uuid":"32660828-4da5-42b3-839f-686904e29c99","clusterType":"PRIMARY","userIntent":{"universeName":"yb-k8s-test","provider":"ac1a3aa0-8251-4ce9-8d4a-c48f1618af35","providerType":"kubernetes","replicationFactor":3,"regionList":["54c93e2f-0074-413a-84e7-5c6b5673e572"],"preferredRegion":null,"instanceType":"small","numNodes":3,"ybSoftwareVersion":"2.0.10.0-b4","accessKeyCode":"yugabyte-default","deviceInfo":{"volumeSize":75,"numVolumes":2,"diskIops":null,"storageClass":"standard","mountPoints":null,"storageType":null},"assignPublicIP":true,"useTimeSync":false,"enableYSQL":true,"enableNodeToNodeEncrypt":true,"enableClientToNodeEncrypt":true,"enableVolumeEncryption":false,"masterGFlags":{},"tserverGFlags":{},"instanceTags":{}},"placementInfo":{"cloudList":[{"uuid":"ac1a3aa0-8251-4ce9-8d4a-c48f1618af35","code":"kubernetes","regionList":[{"uuid":"54c93e2f-0074-413a-84e7-5c6b5673e572","code":"us-west","name":"US West","azList":[{"uuid":"a6796904-0d9c-43b7-9cbe-53536ee1f659","name":"us-west1-c","replicationFactor":1,"subnet":null,"numNodesInAZ":1,"isAffinitized":true},{"uuid":"8d738202-fba6-409a-92c1-f31a6bc64824","name":"us-west1-a","replicationFactor":1,"subnet":null,"numNodesInAZ":1,"isAffinitized":true},{"uuid":"4dd043c0-ceae-4b15-8f0f-1af1e96b6261","name":"us-west1-b","replicationFactor":1,"subnet":null,"numNodesInAZ":1,"isAffinitized":true}]}]}]},"index":0,"regions":[{"uuid":"54c93e2f-0074-413a-84e7-5c6b5673e572","code":"us-west","name":"US West","ybImage":null,"longitude":-121,"latitude":37,"zones":[{"uuid":"a6796904-0d9c-43b7-9cbe-53536ee1f659","code":"us-west1-c","name":"us-west1-c","active":true,"subnet":null},{"uuid":"4dd043c0-ceae-4b15-8f0f-1af1e96b6261","code":"us-west1-b","name":"us-west1-b","active":true,"subnet":null},{"uuid":"8d738202-fba6-409a-92c1-f31a6bc64824","code":"us-west1-a","name":"us-west1-a","active":true,"subnet":null}],"active":true,"details":null,"securityGroupId":null}]}],"nodePrefix":"yb-dev-yb-k8s-test","rootCA":"0d69ddc3-fb35-4a89-8308-642a07a9f3a0","userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"nextClusterIndex":1,"allowInsecure":false,"importedState":"NONE","capability":"EDITS_ALLOWED"}

BUT, call to configure with the following payload:

> {"universeUUID":"0a7cbf58-e81c-4065-8b91-b8779b615f0b","expectedUniverseVersion":66,"currentClusterType":"PRIMARY","clusters":[{"clusterType":"PRIMARY","userIntent":{"universeName":"yb-k8s-test","provider":"ac1a3aa0-8251-4ce9-8d4a-c48f1618af35","regionList":["54c93e2f-0074-413a-84e7-5c6b5673e572"],"assignPublicIP":true,"useTimeSync":false,"enableYSQL":true,"enableNodeToNodeEncrypt":true,"enableClientToNodeEncrypt":true,"numNodes":3,"instanceType":"small","ybSoftwareVersion":"2.0.10.0-b4","replicationFactor":3,"deviceInfo":{"volumeSize":75,"numVolumes":2,"mountPoints":null,"storageType":null,"diskIops":null},"accessKeyCode":"yugabyte-default","masterGFlags":[{}],"tserverGFlags":[{}],"providerType":"kubernetes"}}],"clusterOperation":"EDIT","userAZSelected":false}

So it seems like the call to configure has gotten messed up

**Comment by ramkumarvs** [comment]
This issue is fixed.
