### ISSUE TITLE
[YW] Adding region to on-prem provider results in blank screen

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3303]
Using version 2.0.10.0 or 2.0.11.0 of YugaWare, if you attempt to modify an on-premise provider and add additional regions/zones, the region gets created but the zones do not and a blank screen appears on the UI. No errors thrown in the application.log file.

**Comment by yb-andrew** [comment]
Using the latest changes in UI with version 2.0.10.0 of Yugaware, this issue does not reproduce.
