### ISSUE TITLE
[2DC] Enable op ID based log retention while setting up replication

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3317]
Currently, op ID based log retention needs to be manually enabled while setting up 2DC replication.

We should change 2DC setup universe replication API to do this automatically. We can also get rid of the 4 hour retention and simply rely on op ID based retention.
Similarly, bootstrap producer API should enable op ID based retention.

**Comment by hectorgcr** [comment]
Currently log retention by op id is enabled as soon as the log cdc_min_replicated_index_ is set. This variable is set by a CDC background thread:

```
 for (const auto &elem : tablet_min_checkpoint_index) {
      auto tablet_id = elem.first;
      std::shared_ptr<tablet::TabletPeer> tablet_peer;

      Status s = tablet_manager_->GetTabletPeer(tablet_id, &tablet_peer);
      if (s.IsNotFound()) {
        VLOG(2) << "Did not found tablet peer for tablet " << tablet_id;
        continue;
      } else if (!IsTabletPeerLeader(tablet_peer)) {
        VLOG(2) << "Tablet peer " << tablet_peer->permanent_uuid()
                << " is not the leader for tablet " << tablet_id;
        continue;
      } else if (!s.ok()) {
        LOG(WARNING) << "Error getting tablet_peer for tablet " << tablet_id << ": " << s;
        continue;
      }

      auto min_index = elem.second;
      s = tablet_peer->set_cdc_min_replicated_index(min_index);
```

So as long as a cdc_state entry is created for each stream, log retention by op id is automatically enabled.

I will confirm later if this entries are being created when the replication is setup
