### ISSUE TITLE
[YSQL] Optimize UPDATE on table with indices 

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#3329]
In case of row update of table with multiple indexes postgres deletes all old indexes and creates new one even in case indexed columns has not been changed.
Reason is that in vanilla postgres updated row has new ctid.
But YB doesn't change ybctid in case of row update in this case indexes of unchanged columns may be preserved.

```
yugabyte=# create table t(k int, v1 int, v2 int);
yugabyte=# create unique index on t(v1);
yugabyte=# create unique index on t(v2);
yugabyte=# insert into t values(1, 10, 100);
yugabyte=# update t set v1=v1+9 where v2>0;
```

In the following scenario one row will be updated. Both v1 and v2 indexes will be changed (delete + insert write operation).
For v1 index value '10' will be delete and '19' will be inserted
For v2 index value '100' will be deleted and '100' will be inserted. Operation on v2 index are unnecessary as row's ybctid is not changed by UPDATE command

**Comment by ndeodhar** [comment]
Fixed as part of https://github.com/yugabyte/yugabyte-db/issues/3106

**Comment by ndeodhar** [comment]
Reopening this. Per @d-uspenskiy 
#3297 avoids index updates only in case no secondary indices is updated at all. In case at least one index is updated all other indices will be updated as well. So, we still need to do this optimization to avoid updating unnecessary indexes.

**Comment by ramsrivatsa** [comment]
Feature added with the following diff. 
https://phabricator.dev.yugabyte.com/D9967
