### ISSUE TITLE
Key pattern search and delete in Redis.

### ISSUE THREAD

**Issue by Jibin-Tomy-Narvar** [yugabyte/yugabyte-db#333]
Jira Link: [DB-4721](https://yugabyte.atlassian.net/browse/DB-4721)
Please add the ability to do key pattern search and delete.

ref: 
https://redis.io/commands/keys
https://redis.io/commands/del

**Comment by rahuldesirazu** [comment]
Hi @Jibin-Tomy-Narvar, thanks for your patience. YugaByte has support for KEYS command. Currently DEL is not supported.

https://docs.yugabyte.com/latest/yedis/api/keys/

**Comment by m-iancu** [comment]
Not planning to address this in the immediate roadmap so closing as a wontfix.
