### ISSUE TITLE
[docs] [community] Add topics for common cluster operations

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3333]
Currently, there is a topic called "Change cluster configuration" (https://docs.yugabyte.com/preview/manage/change-cluster-config/ ) that covers migrating an entire cluster to a completely different cluster". This is not as common a task as just adding a node, replacing a non-responsive node, or decommissioning a node. We should add topics for each of these more typical tasks.

Right now, we just have a “full move” clearly documented. Should we consider breaking that up into a couple of pages, more directly related to user expectations? Say at least:

- Expand cluster (start with 3 nodes, go to 6)
- Shrink cluster (start with 6 nodes, go to 3)
- Change instance types / AMIs (what we have now)
- Decommission a node, and potentially provision a new one (start with 6 nodes, replace 1)

Most of the steps / info is already in the doc page we have, but this should help users going straight to what they care about.

**Comment by lizayugabyte** [comment]
This ticket should, probably, be closed as "won't do"
