### ISSUE TITLE
[docs] How to add tables to be replicated (after 2DC is configured)

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3337]
Until fix in #2051 is available, document workaround for adding tables to be replicated *after* 2DC is configured.

Two potential workarounds (suggested by Gaurav Singh):

- If replication was recently setup, then you can delete the replication using yb-admin delete_universe_replication command and re-create it using `yb-admin setup_universe_replication` for all tables.
- Another (hacky) workaround is to create a new replication stream just for that new table. You can use <producer_uuid-ver2> as the name while setting up the stream. So, something like yb-admin setup_universe_replication <producer-uuid_ver2> <master_addresses> <new_table_id>

**Comment by lizayugabyte** [comment]
Since #2051 has been closed, this doc ticket is no longer needed
