### ISSUE TITLE
Segfault in tcmalloc::PageHeap::GrowHeap in CppCassandraDriverTest.Rejection

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3338]
Jira Link: [DB-2135](https://yugabyte.atlassian.net/browse/DB-2135)
https://gist.github.com/mbautin/0e9759e3f98d064d135a4e344b639e9b/raw

This is a release gcc build. Commit: e0b36fcf690ab7473bb2f7a2206a8cafd5377947

**Comment by mbautin** [comment]
Full log: https://gist.githubusercontent.com/mbautin/613c4117d2a0118185094e7b7b92bebf/raw

**Comment by rthallamko3** [comment]
Test seems to be succeeding off late as per - https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=CppCassandraDriverTest&fail_tag=all&name=Rejection&platform=linux
