### ISSUE TITLE
Support for Redis Expire, ExpireAt, TTL commands.

### ISSUE THREAD

**Issue by Jibin-Tomy-Narvar** [YugaByte/yugabyte-db#334]
Support for EXPIRE command. Which will let the user add TTL after a key was created or will update the current TTL if the key already has one.

Nice to have:
support for TTL command. Which will return the remaining TTL of a key. 

Ref:
https://redis.io/commands/expire
https://redis.io/commands/ttl

**Comment by kmuthukk** [comment]
Thanks @Jibin-Tomy-Narvar for this enhancement request. This is something we plan to implement in the near term. Will keep you posted.

**Comment by kmuthukk** [comment]
For completeness, as part of this, we should also support `EXPIREAT` and `PTTL`

https://redis.io/commands/expireat
https://redis.io/commands/pttl

**Comment by kmuthukk** [comment]
Implemented in https://github.com/YugaByte/yugabyte-db/commit/d997a76b2a431648482a59dd35f1d947c48ab383 and https://github.com/YugaByte/yugabyte-db/commit/d90232585c1b7df099b6a10070e28f7ab8964850
