### ISSUE TITLE
Add multi-table backup enable flag in UI.

### ISSUE THREAD

**Issue by Arnav15** [yugabyte/yugabyte-db#3341]
We have the ability to gracefully stop a multi-table backup by using a universe config flag. This flag, if turned on, will prevent a schedule from running or if a schedule is running, will stop the multi-table backup task immediately after the current table completes (and will not move forward with any other tables that might have been in the backup queue).
We need to add a button under the `more` panel to help enable/disable this button. It can be turned on or off using the following API:
```
curl --location --request PUT 'http://localhost:9000/api/v1/customers/f33e3c9b-75ab-4c30-80ad-cba85646ea39/universes/c4b9a472-79d4-4eb5-a938-0755bc47285b/update_backup_state?markActive=true' \
--header 'X-AUTH-TOKEN: 42c7439b-ac36-45bf-90e0-e2141447e07d' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```
We also want to ensure that the users are aware of the flag being turned off while creating a schedule. The response in the universe info now also includes a field called `universeConfig` that has the flag `takeBackups`. If it is equal to "true" (string), create the schedule, else show a warning asking the user to turn it on so that the schedule can run sucessfully.

**Comment by ramkumarvs** [comment]
This is implemented
