### ISSUE TITLE
Support for Redis Monitor Command

### ISSUE THREAD

**Issue by Jibin-Tomy-Narvar** [YugaByte/yugabyte-db#335]
Support for the Redis monitor command. It will be a helpful command for debugging and monitoring what is happening on the Redis server.

Ref:
https://redis.io/commands/monitor

**Comment by kmuthukk** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/2ba3003c8b733cbbd4e2319dc98cafa6ccc7c9b9

**Comment by Jibin-Tomy-Narvar** [comment]
Thank you guys.
