### ISSUE TITLE
[docs] Load data into YB using the COPY statement

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3355]
Jira Link: [DB-2247](https://yugabyte.atlassian.net/browse/DB-2247)
Document how to get data into YB: INSERT, COPY
Two parts to this issue
- Add topic on getting data into YB
- Add notes and examples to COPY statement 
- Add tips for faster data loading:
  - From @ndeodhar: For tables with foreign keys and secondary indexes, it's more performant to load the data first and then add indexes and foreign keys.

Related issues:

- YSQL - INSERT INTO SELECT Statement running slow (#3157)
- [YSQL] Batch writes (inserts / updates / deletes) (#2934)
- Doc improvement: Add YSQL support into Backup and restore section and Data migration section #3241

**Comment by sushantrmishra** [comment]
This is covered by various improvement for copy command..
