### ISSUE TITLE
[docdb] Enhance metrics to export resetting percentiles

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3362]
Right now, the histogram metrics that we use are not resetting, so they will show percentiles across all values used with the object (since the beginning of the metric). It would be useful to allow resetting such percentiles, such that when using Prometheus to pull metrics, we could at least get more fine grained stats on each individual scrape interval.

cc @amitanandaiyer

**Comment by kmuthukk** [comment]
Discussed with @bmatican , and increasing priority of this ask.
