### ISSUE TITLE
[Colocation] Balance storage correctly for colocated tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3367]
Today, we use `GetAndRegisterDataAndWalDir` to balance storage for tables (and tablets). Currently, we are skipping this colocated tables since the balancing logic is per-table / per-tablet which won't work correctly with colocated tables.

We should make `GetAndRegisterDataAndWalDir` aware of colocated tables and handle them appropriately.

**Comment by jaki** [comment]
Closing due to commit 7992a359cbf4e6336e13d0dcc521f7b2b70c9d88.  Disk balancing logic should use the primary table id, which is the colocated parent id.
