### ISSUE TITLE
[YSQL]Snapshot too old: Snapshot too old. Read point: { physical: 1579084094151981 }

### ISSUE THREAD

**Issue by MPaularBear** [yugabyte/yugabyte-db#3368]
Jira Link: [DB-2178](https://yugabyte.atlassian.net/browse/DB-2178)
the problem follows ：
#3350 
[YSQL] Catalog Version Mismatch: A DDL occurred while processing this query. Try Again #3350

i  manually create all tables (alternative to concurrently create tables which cause "Catalog Version Mismatch"  bug), then sysbench concurrently insert data into multiple tables. after about 8 hours, something went wrong:
`Snapshot too old: Snapshot too old. Read point: { physical: 1579084094151981 }, earliest read time allowed: { physical: 1579084094178508 logical: 1  }, delta (usec): 26527: kSnapshotTooOld
FATAL: failed query was : INSERT INTO sbtest2(k,c,pad) VALUES( blablabla.......)`

i find something similar: 
https://forum.yugabyte.com/t/issue-snapshot-too-old/556/2
in this post  the solution is :

> @harryboot Thank you for reporting this issue. How are you inserting the data in the Spark program? Does every task insert multiple rows in a long-running transaction? The “snapshot too old” error could appear for long-running transactions if a compaction happens in the middle. You could try to increase the **timestamp_history_retention_interval_sec** flag to a large value, e.g. 3600.

so can you explain this flag with more details? thx

**Comment by rthallamko3** [comment]
@MPaularBear , We have seen this error sometimes if the transaction has been running for over 15 minutes (history retention period) and the rows corresponding to that timestamp are no longer in the system, This causes the reads and writes (that lookup for duplicates etc) to fail. Let us know if this repros on the newer builds of Yugabyte and we will take a closer look. Closing this for now.
