### ISSUE TITLE
[docdb] Investigate why TSTabletManager per-disk tablet load balancing might not be working as expected

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3374]
Checked on a running cluster that we've ended up with a skew of 13 vs 7 tablets for a table. However, the UI did show something of the order of 70+ tablets in the `/tablets` endpoint, most of them being TOMBSTONED, so running theory is that TOMBSTONED tablets somehow get factored into the per-disk distribution and can thus lead to the RUNNING tablets not being evenly split.

cc @kmuthukk @mbautin @hectorgcr

**Comment by hectorgcr** [comment]
`UnregisterDataWalDir` (which together with `RegisterDataWalDir` to load balance the tablets) get used in the following methods:
1. `RemoteBootstrapClient::Start` when we fail to create a new metadata object for the tablet
2. `TSTabletManager::CreateNewTablet` when we fail to create a new metadata object
3. `TSTabletManager::DeleteTablet` but only when the tablet state is TABLET_DATA_DELETED

This could explain why `TOMBSTONED` tablets are still being load balanced

**Comment by bmatican** [comment]
Heh, I think https://github.com/yugabyte/yugabyte-db/issues/2817 was a also a good indicator of this.

@hectorgcr with your change, we still won't be removing tombstoned tablets from disk, right?

**Comment by hectorgcr** [comment]
That is correct. The only thing that this diff does is to ignore TOMBSTONED tablets when deciding how many tablets for a table each disk has.
