### ISSUE TITLE
[Platform] Yugaware does not support HTTPS connection in GCP

### ISSUE THREAD

**Issue by stevenarvar** [yugabyte/yugabyte-db#3389]
I followed the installation instruction from this link:

https://docs.yugabyte.com/latest/deploy/enterprise-edition/configure-admin-console/

The result Yugaware installation does not support HTTPS connection.  I don't think this is the case for AWS installation.

**Comment by ramkumarvs** [comment]
@stevenarvar can you please let us know what didn't work, because we do have a yugaware running with https on GCP internally. Did you open up the port 443 to yugaware?

**Comment by stevenarvar** [comment]
Hi Ram, it might be easier we discuss via slack.  Thanks.

**Comment by stevenarvar** [comment]
User error, the setting to enable HTTPS is in the replication page.
