### ISSUE TITLE
can't create database

### ISSUE THREAD

**Issue by robinbraemer** [yugabyte/yugabyte-db#3393]
I setup a fresh yb cluster using image `yugabytedb/yugabyte:2.0.10.0-b4` and can't create a database.

```
yugabyte=# create database test;
create database test;
ERROR:  Not found: The object does not exist: table_name: "transactions" namespace { name: "system" database_type: YQL_DATABASE_CQL }: . Errors from tablet servers: [Not found (yb/master/catalog_manager.cc:6100): The object does not exist: table_name: "transactions" namespace { name: "system" database_type: YQL_DATABASE_CQL }]
```

There are no errors in the master & tserver logs.

client:
`ysqlsh (11.2-YB-2.0.10.0-b0)`

**Comment by robinbraemer** [comment]
Using image `yugabytedb/yugabyte:2.0.11.0-b8` now works

**Comment by rkarthik007** [comment]
cc @m-iancu @OlegLoginov @nocaway

**Comment by ndeodhar** [comment]
@mbautin Looks like this is related to transaction DDL change (given that create database is expecting transactions table to be present): #3108 

@robinbraemer Do you have the master logs from 2.0.10 still available?

**Comment by robinbraemer** [comment]
Unfortunately I have no more logs but from what I can remember of there where some slow connection warnings, if that's any important.

**Comment by zukuzu** [comment]
I'm having the same error with 2.1.1.0 on linux. My master log [master log](https://gist.github.com/zukuzu/9bfbbb5d1eb5b1fc432a98e1eda4796a).

**Comment by rthallamko3** [comment]
Seems like this is no longer an issue. Closing this.
