### ISSUE TITLE
[YCQL] Create KEYSPACE Options Ignored

### ISSUE THREAD

**Issue by dmosruby** [yugabyte/yugabyte-db#3397]
When trying to setup Keyspace options for YCQL on create, they don't seem to persist.
The documentation on YCQL CREATE KEYSPACE and ALTER KEYSPACE both give an example of setting the following:
`CREATE KEYSPACE example WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': '3'} AND DURABLE_WRITES = true;`
and
`ALTER KEYSPACE example WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': '3'} AND DURABLE_WRITES = true;`
but when executed and the keyspace is described, it always forces the class to `SimpleStrategey`, Replication Factor to `1` and Durable Writes to `true`.

Attempted changing the options with valid inputs and the describe always returned the same settings:
```SQL
cassandra@cqlsh> CREATE KEYSPACE test WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': '3'} AND DURABLE_WRITES = true;
cassandra@cqlsh> DESCRIBE KEYSPACE test

CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

cassandra@cqlsh> DROP KEYSPACE test ;
cassandra@cqlsh> CREATE KEYSPACE test WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': '3'} AND DURABLE_WRITES = false;
cassandra@cqlsh> DESCRIBE KEYSPACE test

CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

cassandra@cqlsh> DROP KEYSPACE test ;
cassandra@cqlsh> CREATE KEYSPACE test WITH REPLICATION = {'class': 'NetworkTopologyStrategy'} AND DURABLE_WRITES = true;
cassandra@cqlsh> DESCRIBE KEYSPACE test

CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
```

The documentation for the YCQL should be updated if this is the only allowed configuration or should include similar documentation to Cassandra's - http://cassandra.apache.org/doc/latest/cql/ddl.html#create-keyspace

You should also specify if you support other replication classes (i.e. NetworkTopologyStrategy).

Our environment is running a single replica of Yugabyte in kubernetes.
Yugabyte version: 2.0.1.0-b19

**Comment by dmosruby** [comment]
When trying to create keyspace with a non-numeric option for replication (QUORUM) the following error occurs:
```SQL
cassandra@cqlsh> CREATE KEYSPACE test WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 'QUORUM'} AND DURABLE_WRITES = true;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid Table Property. QUORUM is not a valid number
CREATE KEYSPACE test WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 'QUORUM'} AND DURABLE_WRITES = true;
                           ^^^^^^^^^^^
 (ql error -210)"
```

**Comment by kmuthukk** [comment]
hi @dmosruby --

In YB, the preferred syntax is simply:

  CREATE KEYSPACE test;

Only the cluster level defaults apply (in terms of things like replication factor) today. Keyspace level or table level overrides of the cluster level settings are not yet supported.

As noted in the second bullet here in our documentation:
  https://docs.yugabyte.com/latest/api/ycql/ddl_create_keyspace/#semantics
the additional clauses (like WITH REPLICATION) are supported primarily for syntax compatibility with existing ecosystem of frameworks/drivers, but these options are ignored from a semantic point of view.

**Comment by dmosruby** [comment]
@kmuthukk I'm sorry, I completed missed that bullet! Thank you for the clarification! 😃
