### ISSUE TITLE
Add support for ZRANGE and ZREVRANGE for sorted sets through the Redis API

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#34]

**Comment by rahuldesirazu** [comment]
Support for ZREVRANGE in 3703e9007ea73cc77bee276560c4ebf5dbe0c9fa, ZRANGE to come.

**Comment by rahuldesirazu** [comment]
Support for ZRANGE in 8797e3936cac93cb9d299fefb2561859ed906c0f, closing.
