### ISSUE TITLE
with "read from followers", on a time out, further requests from same client permanently ignore this follower

### ISSUE THREAD

**Issue by hectorgcr** [YugaByte/yugabyte-db#340]
Currently, when using CONSISTENT_PREFIX for reads (which allows reads to be directed to a follower), if we time out on a follower replica, the client marks that replica as failed, and we don't use it again even if this time out was temporary and the tablet in the replica is in the RUNNING state.

We need a way to refresh the lookup cache periodically when this happens.

**Comment by kmuthukk** [comment]
hi @hectorgcr : I think the issue title/description is a bit too broad, and affects "reads from follower" mode only correct? 

Renaming title to reflect this more accurately.

**Comment by kmuthukk** [comment]
@hectorgcr : can we close this out given the fix has landed?
