### ISSUE TITLE
Please add feature to connect to yugabyte db using LibPQ in julia

### ISSUE THREAD

**Issue by arumugamav** [yugabyte/yugabyte-db#3410]
Please add feature to connect to yugabyte db using LibPQ in julia

**Comment by ddorian** [comment]
@arumugamav Do you mean this package  https://github.com/invenia/LibPQ.jl ?
If yes, that is just a wrapper (like most drivers) of libpq. 
Can you confirm that `./bin/ysqlsh` cli can connect and works ?

**Comment by arumugamav** [comment]
Sir/Madam,
Now, I could connect and execute queries using LibPQ in Julia.
Please it may be closer, as the feature already available.
Regards
Arumugam A V

**Comment by ddorian** [comment]
@arumugamav 
1. Install yugabytedb: https://download.yugabyte.com/
2. Install julia
3. install "LibQP" & "Tables" pkg 
4. create file
ava.jl
```
using LibPQ, Tables
conn = LibPQ.Connection("dbname=postgres port=5433 user=postgres host=0.0.0.0 password=")
result = execute(conn, "SELECT version();")
data = columntable(result)
print(data)
close(conn)
```
run
```
julia ava.jl
(version = Union{Missing, String}["PostgreSQL 11.2-YB-2.0.10.0-b0 on x86_64-pc-linux-gnu, compiled by gcc (Homebrew gcc 5.5.0_4) 5.5.0, 64-bit"],)
```
