### ISSUE TITLE
[YSQL] - ALTER TABLE IF EXISTS support

### ISSUE THREAD

**Issue by mathewwjones** [yugabyte/yugabyte-db#3417]
When attempting to run `ALTER TABLE IF EXISTS` it seems the following exception is thrown:
`Caused by: org.postgresql.util.PSQLException: ERROR: ALTER TABLE IF EXISTS not supported yet`

**Use Case**:
I'm building a simple service using [Micronaut](https://micronaut.io/) and using basic hibernate / jpa adapters.

Starting seems to be fine, but any modification to the schema to update crashes out.

The generated query its trying to run is:
` alter table if exists table1 add constraint FKn8dxe978hfgofl9tqpi0g2efq foreign key (foreignkey1) references table2`

**Comment by ndeodhar** [comment]
Thanks for reporting @mathewwjones. This should be fairly simple for us to do. We'll be able to have this ready in a couple of weeks.

**Comment by frozenspider** [comment]
Support was already there, but the grammar rule was disabled. Fixed in 8778cce
