### ISSUE TITLE
[docs] [YSQL] Add JSON data type to tutorial in "Learn app development" section

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3421]
Add documentation for JSON data type to [Data types](https://docs.yugabyte.com/latest/develop/learn/data-types/) tutorial in "Learn app development" section. There is a tutorial for YCQL, but not YSQL.

**Comment by bllewell** [comment]
Closing this as fixed by the content in the [JSON data types and functionality](https://docs.yugabyte.com/latest/api/ysql/datatypes/type_json/) major section. Not exactly a "tutorial". But it addresses everything that you need to know in this topic area.
