### ISSUE TITLE
Redis database support

### ISSUE THREAD

**Issue by Jibin-Tomy-Narvar** [YugaByte/yugabyte-db#343]
Add support for databases in a Redis cluster.

**Comment by kmuthukk** [comment]
Hi @Jibin-Tomy-Narvar 

So the ask is for namespacing (via the "select <db_index>" like operation that Redis supports), too allow for different namespaces to co-exist, and be created/dropped independent of each other, correct?

regards,
Kannan

**Comment by Jibin-Tomy-Narvar** [comment]
My expectation was to be able to create a database with a name and connect to it. After that all the subsequent operations should be performed with respect to that database.

**Comment by kmuthukk** [comment]
Makes sense. Thanks.

@amitanandaiyer : Assigning this one to you.
