### ISSUE TITLE
[YSQL] Remove the PostgreSQL doc source code

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3437]
Jira Link: [DB-2161](https://yugabyte.atlassian.net/browse/DB-2161)
Currently, we include the PostgreSQL documentation source code (src/postgres/doc) in the YugabyteDB source code. If we don't need it, let's remove it. For me, it showed up when I was searching our repo for something unrelated.

**Comment by ddorian** [comment]
This has already been removed.
