### ISSUE TITLE
[docdb] Cluster fails on macOS Sierra / Intel Core 2 Duo due to missing SSE4.2 instruction set

### ISSUE THREAD

**Issue by arulram** [yugabyte/yugabyte-db#344]
Jira Link: [DB-1798](https://yugabyte.atlassian.net/browse/DB-1798)
![screen shot 2018-06-21 at 11 22 14 pm](https://user-images.githubusercontent.com/7889763/41760945-7d24f360-75aa-11e8-9214-df20756fd195.png)

$ uname -v
Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64

$ ./bin/yb-ctl --num_shards_per_tserver 4 create

$ cat  /tmp/yugabyte-local-cluster/node-3/disk-1/tserver.err 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0621 19:39:16.525822 3893433280 main_util.cc:24] Not implemented (yb/util/init.cc:62): The CPU on this system (Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz) does not support the SSE4.2 instruction set which is required for running YB.

**Comment by mbautin** [comment]
Hi @arulram, thank you for giving YugaByte DB a try!
We will work on a build that works on non-SSE4.2 CPUs. In the meantime, would you mind testing on a machine that has a SSE4.2 capable CPU? On macOS you can check this like so:

```
sysctl -a | grep machdep.cpu.features
```
and look for a line like this:

machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 **SSE4.2** x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C

**Comment by mwright-pivotal** [comment]
![image](https://user-images.githubusercontent.com/5115931/50568120-6ae23b00-0d1b-11e9-9eec-baeb62186bcf.png)

I get the same error deploying to Kubernetes on some older Dell servers

**Comment by kmuthukk** [comment]
SSE4.2 is used for fast CRC calculations in the RocksDB code base and a few other third-party libraries (rapidjson & crcutil) that YugaByte DB uses.

We'll look into this to see what the best option might be.

**Comment by kmuthukk** [comment]
User input and feedback (on slack):
```
[dlee@dellpe1 yugabyte-data]$ cat */*/*
Not implemented (yb/util/init.cc:62): The CPU on this system (Intel(R) Xeon(R) CPU           X5365  @ 3.00GHz) does not support the SSE4.2 instruction set which is required for running YB.
Not implemented (yb/util/init.cc:62): The CPU on this system (Intel(R) Xeon(R) CPU           X5365  @ 3.00GHz) does not support the SSE4.2 instruction set which is required for running YB.
[dlee@dellpe1 yugabyte-data]$

[dlee@dellpe1 yugabyte-data]$ uname -a
Linux dellpe1.in.calldei.com 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux


[dlee@dellpe1 yugabyte-data]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 15
Model name:            Intel(R) Xeon(R) CPU           X5365  @ 3.00GHz
Stepping:              11
CPU MHz:               2000.000
CPU max MHz:           3000.0000
CPU min MHz:           2000.0000
BogoMIPS:              5985.34
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
```

Note: there is sse and sse2  and ssse3

Additionally, there wrote:

> Personal/professional advise (having worked for years as internal core developer for a major enterpirse DB  company)
> 
> This is important to support 'older' hardware
> 
> "In the Field' -- 'enterprise' hardware tends to be held for a long time -- its designed upfront (and costs $$) to last a long time,
> 
> The business model (for in-house datacentsrs) is designed for a very long  cycle (5+ years min) with heavy upfront costs expected to be amortized over a very long time.
> 
> Cost of change is high -- even 'its only a software update'  - still can take > year or more to get approved and applied
> 
> Swapping out 'perfectly good' but 'older' servers takes an act of god

**Comment by kmuthukk** [comment]
Looks like crc calculations in RocksDB can handle lack of SSE4.2 already:

https://github.com/YugaByte/yugabyte-db/blob/4b48e25b3a1fb01b0ea0067b1d59c9e0feae8c21/src/yb/rocksdb/util/crc32c.cc#L406

We should look into the other dependencies as well to see if we can relax them.

**Comment by mbautin** [comment]
We might be able to use a CPU emulator called Bochs to test running on older CPUs: https://www.linux.com/news/getting-started-bochs

**Comment by hectorgcr** [comment]
I was able to reproduce this issue by deploying a KVM instance and changing the CPU model to core2duo. I will try to find the parts of the code that require SSE4.2.

**Comment by hectorgcr** [comment]
Even getting rid of the check for SSE4.2 support doesn't help because we still call some SSE4.2 instructions directly. For example:
`all_zeros = _mm_testz_si128(zero_bytes, zero_bytes);`
calls a `ptest` instruction which is part of SSE4.2 (even though the comments for that code mention that it uses SSE2 instructions)

**Comment by oddjobz** [comment]
Hi, I spent some time today reading and watching Videos and thought I'd give Yugabyte a go .. ran into this problem .. turns out I don't actually have a machine with SSE4.2 support .. seems kinda restrictive for people who just want to try it out, maybe typically on spare / older kit?

**Comment by kmuthukk** [comment]
@oddjobz - Thanks for your feedback. This week we have started work on this (i.e. support for CPUs without SSE4.2) - hope to provide an update soon.

**Comment by oddjobz** [comment]
@kmuthukk tvm, I look forward to trying it out when done .. :)

**Comment by poblin-orange** [comment]
Hi guys. Any news on this issue (or a workaround ?)

**Comment by kmuthukk** [comment]
hi @poblin-orange --

We explored this a bit, and the work involved is a bit deeper than we had anticipated. So we haven't been able to staff the effort yet, given competing priorities.

We'll keep you posted once we are able staff this effort again.

Apologies.
