### ISSUE TITLE
YSQL - full text search 

### ISSUE THREAD

**Issue by keverw** [yugabyte/yugabyte-db#3446]
Jira Link: [DB-1947](https://yugabyte.atlassian.net/browse/DB-1947)
I was curious if full text search with the postgreSQL API was supported?

I know though some people recommend using a dedicated search solution but seems the built-in one might be useful when just starting out.

I asked on Slack and was told to create an issue here as that person wasn't sure, but sounded like if it's not implemented yet it might be in the future then.

Personally still poking around at things evaluating different databases, just reading the site, listening to some of the tech talks on YouTube and got my own little test cluster up after a few bumps on the road.

**Comment by ddorian** [comment]
Depends on gin/gist indexes https://github.com/yugabyte/yugabyte-db/issues/1337

**Comment by ndeodhar** [comment]
Hi @keverw , we don't support full text search yet. This has 2 dependencies:
1) GIN indexes (like @ddorian pointed out): #1337
2) Support for english (and other) language text search configurations: https://github.com/yugabyte/yugabyte-db/issues/1979

**Comment by naveennazimudeen** [comment]
Hi @ndeodhar, Is there a timeframe for both 1337 and 1979 to get YSQL full text search to work?

**Comment by sushantrmishra** [comment]
GIN index is now supported in Yugabyte https://docs.yugabyte.com/preview/explore/indexes-constraints/gin/  .

Support for english (and other) language text search configurations is also complete: https://github.com/yugabyte/yugabyte-db/issues/1979 

Please reopen the issue if this does not satisfy the requirement.
