### ISSUE TITLE
[docdb] QLStressTest.OldLeaderCatchUpAfterNetworkPartition flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3465]
https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator/23596/artifact/build/debug-clang-dynamic-ninja/yb-test-logs/tests-client__ql-stress-test/QLStressTest_OldLeaderCatchUpAfterNetworkPartition.log
 
```
src/yb/client/ql-stress-test.cc:673: Failure
1140 | Expected: pre_isolate_op_id.term
1141 | Which is: 2
1142 | To be equal to: 1
 ```

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-mac-master-clang-release/787/artifact/build/release-clang-dynamic-ninja/yb-test-logs/tests-client__ql-stress-test/QLStressTest_OldLeaderCatchUpAfterNetworkPartition.log

```
Expected: (pre_isolate_op_id.index) > (key), actual: 1050 vs 1050
```

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-mac-master-clang-debug/874/artifact/build/debug-clang-dynamic-ninja/yb-test-logs/tests-client__ql-stress-test/QLStressTest_OldLeaderCatchUpAfterNetworkPartition.log
```
Expected: (leader) != (nullptr), actual: NULL vs 8-byte object <00-00 00-00 00-00 00-00>
```

**Comment by bmatican** [comment]
Can confirm this is still a problem, seems like 11/25 commit failure rate.

**Comment by robertsami** [comment]
last 15 commits seem good for this test after 1274b42 -- closing for now
