### ISSUE TITLE
[ycql] provide mechanism for batch operations to return finer-grained errors

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#347]
In the current Apache Cassandra/CQL wire protocol, when an error occurs to a batch request, only a single error code can be returned. 

To avoid extending the wire protocol and the client drivers, we should allow errors to be returned as a result row like how a conditional DML does when the condition is not satisfied.

For example, one possible syntax to flag the return status (success/failure) of a statement in "row" format would be:

```
INSERT INTO t (k, c) VALUES (2, 2) RETURNS STATUS AS ROW;

 [applied] | [message]                                  | k | c
-----------+--------------------------------------------+---+---
     false | Duplicate value disallowed by unique index | 1 | 2 
           | k.t_unique_c                               |   |

```

That way, if there's a batch of 10 such INSERT statements, we will get back 10 result rows:
- for the successful ones [applied] column would be true and the other columns will be null; 
- for the failed ones the [applied] column would be false, and [message] provides the additional information on what the failure was due to (such as violation of a unique index constraint).

While this enhancement is primarily useful for batch operations, for symmetry, we should apply same logic for single statement (non-batch operations as well).

So, if an INSERT where going to cause an unique index violation, then an INSERT of the form:
```
  INSERT INTO t (k, c) VALUES (2, 2)
```
would raise an error:
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="SQL error: Execution Error. Duplicate value disallowed by unique index k.t_unique_c
```
whereas an INSERT of the form:
```
   INSERT INTO t (k, c) VALUES (2, 2) RETURNS STATUS AS ROW;
```
would return a row result back (like Cassandra already does when IF NOT EXISTS clause is used).
```
 [applied] | [message]                                  | k | c
-----------+--------------------------------------------+---+---
     false | Duplicate value disallowed by unique index | 1 | 2 
           | k.t_unique_c                               |   |
```

**Comment by kmuthukk** [comment]
Implemented in: https://github.com/YugaByte/yugabyte-db/commit/a38624ba387336fc5803f3b4c42bf2fee2cfb911

**Comment by frozenspider** [comment]
@kmuthukk , this feature seems to be un-documented
