### ISSUE TITLE
Ensure that yb docker containers have the right os settings

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#348]
We need to ensure that the following are set properly:
* ntp
* ulimits

Requirements documented here: https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/

**Comment by bmatican** [comment]
We've discussed about setting up init containers for the k8s deployments to at least setup sysctls. cc @ramkumarvs

**Comment by Arnav15** [comment]
Closed by https://github.com/yugabyte/charts/pull/40
