### ISSUE TITLE
[docs] How should I handle a single disk failure?

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3491]
Add an FAQ to the Operations FAQ on how to deal with a single disk failure.

See: https://stackoverflow.com/questions/59922082/how-does-yugabyte-handle-single-disk-failure/59936552#59936552

**Comment by ddorian** [comment]
Created https://github.com/yugabyte/yugabyte-db/pull/3496

**Comment by ddorian** [comment]
moved there
