### ISSUE TITLE
[docs] Change requirements from Python 2 to Python 3

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3492]
Change any mentions of Python 2/python2 to Python 3/python3.

- https://docs.yugabyte.com/latest/quick-start/install/#macos
- https://docs.yugabyte.com/latest/quick-start/install/#linux
- https://docs.yugabyte.com/latest/quick-start/install/#docker

Update when the following issue is closed: https://github.com/yugabyte/yugabyte-db/issues/3025

July 12, 2022 update: we still have python 2 mentioned in https://docs.yugabyte.com/preview/quick-start/ for MacOS and Linux install.

**Comment by batara666** [comment]
is this including change of "python" word to "python3" ?

**Comment by batara666** [comment]
for some folks who only have python3 and not "python" as path, you can install `python-is-python3` apt package
