### ISSUE TITLE
CREATE TABLE is 4-5 times slower under docker (mac)

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#3503]
All timings below are for rf1 yugabyte on SSD hosts

regular mac 
```
system_platform=# CREATE TABLE t1(id int primary key, a int, b int);
CREATE TABLE
Time: 266.830 ms
```
-------------------

docker mac ~4-5x regular mac

```
system_platform=# CREATE TABLE t12(id int primary key);
CREATE TABLE
Time: 1397.324 ms (00:01.397)
```

This makes yugabyted startup under docker very slow when yugaware's ORM is trying to create tables on first run.

----------

docker linux seems to be same as regular linux

docker linux
```
system_platform=# CREATE TABLE t1(id int primary key);
CREATE TABLE
Time: 544.457 ms
system_platform=# CREATE TABLE t2(id int primary key);
CREATE TABLE
Time: 399.582 ms
```

regular linux
```
system_platform=# \timing
Timing is on.
system_platform=# CREATE TABLE t4(id int primary key);
CREATE TABLE
Time: 546.721 ms
system_platform=# CREATE TABLE t5(id int primary key);
CREATE TABLE
Time: 410.246 ms
```

@WesleyW @m-iancu 

All tests against 2.0.11.0-b26. 

The issue is probably related to the virtualization of the file system under mac linux, but will update with more details.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-771

**Comment by ndeodhar** [comment]
@d-uspenskiy Based on initial analysis, it seems like cache invalidation is causing a lot of read RPCs to the master. We need to better understand postgres cache invalidation and whether we are invalidating more entries than needed.
You can use `vmodule=tablet_service=2` to log the master read and write RPCs during `CREATE TABLE` request.

**Comment by iSignal** [comment]
We've come a long way since Jan of this year (left, docker image tag 2.0.9) and now (latest docker image 2.3.0) and 

![Screen Shot 2020-09-08 at 11 07 38 AM](https://user-images.githubusercontent.com/8207010/92512844-48791400-f1c4-11ea-97e3-212cc2810283.png)
