### ISSUE TITLE
How can I import the project into CLion and index the definition of class?

### ISSUE THREAD

**Issue by shengyunyao** [yugabyte/yugabyte-db#3526]
I tried to import it directly into my CLion but I failed to index the definition of class. I think I need solve this problem with yb_build.sh. Can anybody help?

**Comment by ddorian** [comment]
Can you try instructions here: https://github.com/yugabyte/yugabyte-db/wiki/CLion-project-setup ?

**Comment by ddorian** [comment]
Just tested, works for me.
@shengyunyao please reopen the issue if it's not solved for you.

**Comment by shengyunyao** [comment]
Thank you @ddorian
