### ISSUE TITLE
configure: error: readline library not found

### ISSUE THREAD

**Issue by ananyaks** [YugaByte/yugabyte-db#354]
I did the following on CentOS 7 Linux from [instructions:](https://github.com/YugaByte/yugabyte-db#building-yugabyte-code)

- completed the [prerequisites](https://github.com/YugaByte/yugabyte-db#prerequisites-for-centos-7)
- cloned yugabyte-db from the github repository
- ran: ./yb_build.sh release --with-assembly

The build failed during psql(common) build. The attached file build-error.log is a copy and paste of the display output of yb_build.sh.  From the build-error.log:

`psql (common) If you have readline already installed, see config.log for details on the
psql (common) failure.  It is possible the compiler isn't looking in the proper directory.
psql (common) Use --without-readline to disable readline support.`

I have attached the console.log from yugabyte-db/thirdparty/build/common/postgresql-10.3
I installed 'readline-devel' with the following command:

`sudo yum install readline-devel`

I re-ran the yb_build.sh but got the same errors as before. I checked and found the readline.so in /usr/lib64 and a readline directory with .h files in /usr/include. The PATH is set to:

`[ananyaks@centhost include]$ echo $PATH
/home/ananyaks/tools/apache-maven/bin:/home/ananyaks/tools/apache-maven/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/ananyaks/.local/bin:/home/ananyaks/bin:/usr/lib64:/usr/include:/home/ananyaks/.local/bin:/home/ananyaks/bin:/usr/lib64:/usr/include`

Please let me know how to fix these errors to complete the build.
[build-error.log](https://github.com/YugaByte/yugabyte-db/files/2157487/build-error.log)
[config.log](https://github.com/YugaByte/yugabyte-db/files/2157488/config.log)

Thanks!

**Comment by kmuthukk** [comment]
thanks for reporting @ananyaks.

hi @mbautin - can you please take a initial look?

**Comment by ttyusupov** [comment]
Hi @ananyaks , can you run `~/.linuxbrew-yb-build/bin/brew install readline` and then try to rebuild?

**Comment by ananyaks** [comment]
Hi @ttyusupov, thank you for the additional instruction to run

`~/.linuxbrew-yb-build/bin/brew install readline openssl libuuid bzip2`
`./yb_build.sh release --with-assembly`

The build got much further but did not complete successfully. The file [build_output.log](https://github.com/YugaByte/yugabyte-db/files/2164486/build_output.log) is a copy and paste of the displayed end output of `./yb_build.sh release --with-assembly`. The error at the very end of build_output.log is

`[ERROR] Failed to execute goal on project interface-annotations: Could not resolve dependencies for project
org.yb:interface-annotations:jar:0.8.0-SNAPSHOT: Could not find artifact jdk.tools:jdk.tools:jar:1.8 at specified path
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64/jre/../lib/tools.jar -> [Help 1]`

From the [Building the code](https://github.com/YugaByte/yugabyte-db#building-the-code) documentation, the build does seem to have created a number of binaries in `build/release-gcc-dynamic-community`, and has also created the `build/latest` symlink. The file 
[binaries.txt](https://github.com/YugaByte/yugabyte-db/files/2164496/binaries.txt) lists the files created in `build/release-gcc-dynamic-community` and the file 
[bin.txt](https://github.com/YugaByte/yugabyte-db/files/2164498/bin.txt) lists the binaries created in `build/release-gcc-dynamic-community/bin`.

I want to be able to bring up yugabyte-db from my build and run Java applications. If the latest build error cannot be ignored, please let me know how to resolve it. Thanks!

**Comment by mbautin** [comment]
@ananyaks Thank you for your interest in building YugaByte DB from source. Looking at your build log, the C++ code was built successfully, so you can already start a local YugaByte DB cluster using the `bin/yb-ctl` command (`bin/yb-ctl create`). Please give it a try and let us know if there are any issues. The local cluster brought up that way should already be usable for app development with open-source Java drivers for Cassandra and Redis or the respective optimized YugaByte versions (see https://docs.yugabyte.com/latest/develop/client-drivers/ for more details). If you want to run YugaByte sample apps, you can do so using the yb-sample-apps.jar file found inside the pre-built tarball that you can download at https://docs.yugabyte.com/latest/quick-start/install/#linux . We will look into the Java build error shortly and you'll be able to build the sample apps from source as well.

**Comment by mbautin** [comment]
@ananyaks We have removed the dependency on tools.jar. Would you mind pulling the latest source and re-running the build?

**Comment by ananyaks** [comment]
Hi @mbautin I pulled the latest source and re-ran the build. The file [build_output_after_pull.log](https://github.com/YugaByte/yugabyte-db/files/2165201/build_output_after_pull.log) is a copy and paste of the output displayed of pulling the source and running the build.

Seeing the following new error in the build_output_after_pull.log

`[INFO] Changes detected - recompiling the module!`
`[INFO] Compiling 3 source files to
/home/ananyaks/Documents/my-projects/yugabyte-db/java/interface-annotations/target/classes`
`[ERROR] COMPILATION ERROR :`
`[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?`
`[INFO] 1 error`

Also seeing the following error as in the previous run

`[INFO] Reactor Summary:`
`[INFO] YugaByte 0.8.0-SNAPSHOT ............................ SUCCESS [  2.102 s]`
`[INFO] YB Annotations ..................................... FAILURE [  8.214 s]`
`[INFO] YB Java Client ..................................... SKIPPED`
`[INFO] YB commandline interface ........................... SKIPPED`
`[INFO] YB CQL Support ..................................... SKIPPED`
`[INFO] YB Load Tester ..................................... SKIPPED`
`[INFO] YB Jedis Tests 0.8.0-SNAPSHOT ...................... SKIPPED`
`[INFO] BUILD FAILURE`

Thanks!

**Comment by ttyusupov** [comment]
Hi @ananyaks , could you, please, share the output of the following commands?
```
ls -l ~/.linuxbrew-yb-build/bin/java
ls -l ~/.linuxbrew-yb-build/Cellar/jdk
java --version
which java
```

**Comment by ananyaks** [comment]
Hi @ttyusupov , the file [commands.txt](https://github.com/YugaByte/yugabyte-db/files/2167344/commands.txt) has the output. Thanks!

**Comment by ananyaks** [comment]
Hi @ttyusupov, @mbautin, Thanks! Your suggestions helped in completing the build successfully. The copy and paste of the build output is in [build_success.log](https://github.com/YugaByte/yugabyte-db/files/2169041/build_success.log), see if the output is what you expect?

Since the build was completed in pieces should I be concerned about the correctness of the build? Is it necessary to remove my local copy of yugabyte-db, do a fresh clone and build (this time skipping the prerequisite steps)?

Please take a look at [output.txt](https://github.com/YugaByte/yugabyte-db/files/2169046/output.txt), do they look ok? Do I need to set `JDK_HOME`, if yes, to what? 

I want to run Java tests that use YCQL API against my build. Are the following steps correct from [Quick Start](https://docs.yugabyte.com/latest/quick-start/) to try this? If not, what are the steps?

1. Skip the [Install YugaByte DB ](https://docs.yugabyte.com/latest/quick-start/install/) step since I will be using the binaries from the build. Is this ok?
2. Do [Create Local Cluster](https://docs.yugabyte.com/latest/quick-start/create-local-cluster/)  step.
3. Test [YCQL API](https://docs.yugabyte.com/latest/quick-start/test-cassandra/) step.
4. Run [Sample Apps](https://docs.yugabyte.com/latest/quick-start/run-sample-apps/)  using YCQL API.
   - Key-Value Workload using YCQL API

Thanks!!

**Comment by kmuthukk** [comment]
Hi @ananyaks 

The build log looks ok. For running YCQL unit tests or more generally the unit tests written in Java:

Building Java code alone & Running Java tests
```
cd ~/code/yugabyte/java
mvn clean install package -DskipTests
```

Running the Java tests:
```
mvn test

# Alternatively, to run just some tests, say YCQL tests:
mvn test -Dtest=org.yb.cql.*.java

# Or, a specific test in yb-cql, for example:
cd ~code/yugabyte/java/yb-cql; mvn test -Dtest=org.yb.cql.TestDescendingOrder

# To run a specific Java sub-test within a test file
# use the # syntax.
For example:
cd ~/code/yugabyte/java/yb-cql/
mvn test -Dtest=org.yb.cql.TestDescendingOrder#testTimestampDesc
```

Viewing log outputs of Java tests:
```
# Java output
$ ls -1 yb-cql/target/surefire-reports/
TEST-org.yb.cql.TestBasicStatements.xml
org.yb.cql.TestBasicStatements-output.txt
org.yb.cql.TestBasicStatements.txt
```
Note that the YB logs are contained in the output file.

**Comment by ananyaks** [comment]
Thanks @kmuthukk ! I will try it out.

**Comment by ananyaks** [comment]
Hi @kmuthukk, the `mvn clean install package -DskipTests` resulted in build failure captured in [java_build_error.log](https://github.com/YugaByte/yugabyte-db/files/2171044/java_build_error.log). How can I fix this?

The one change I had done was to add `$JAVA_HOME/bin` at the beginning of `PATH` so that java is picked up from this location instead of `/usr/bin/java`. 

`export JAVA_HOME=/home/ananyaks/.linuxbrew-yb-build/Cellar/jdk@8/1.8.0-151
PATH=$JAVA_HOME/bin:$PATH:$HOME/.local/bin:$HOME/bin:/usr/lib:/usr/lib64:/usr/include`

Thanks!

**Comment by ttyusupov** [comment]
Hi @ananyaks , we have a way to run tests from our build script.

Building Java code alone:
`./yb_build.sh --scb`

Running the Java tests
```
./yb_build.sh --scb --sj --java-tests
# To run java tests against release YB build:
./yb_build.sh release --scb --sj --java-tests
# Alternatively, to run specific test:
./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient
# To run a specific Java sub-test within a test file use the # syntax.
# For example:
./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient#testClientCreateDestroy
```

Viewing log outputs of Java tests
```
# Java output
$ ls -1 java/yb-client/target/surefire-reports/
TEST-org.yb.client.TestYBClient.xml
org.yb.client.TestYBClient-output.txt
org.yb.client.TestYBClient.testAffinitizedLeaders.stderr.txt
org.yb.client.TestYBClient.testAffinitizedLeaders.stdout.txt
…
org.yb.client.TestYBClient.testWaitForLoadBalance.stderr.txt
org.yb.client.TestYBClient.testWaitForLoadBalance.stdout.txt
org.yb.client.TestYBClient.txt
```

Note, that you have to pass `release` parameter to `yb_build.sh` if you want to run tests against a release YB build. By default it will try to run against a debug build and it should be already built (or you can skip `--scb --sj` and it will build it for you).

**Comment by kmuthukk** [comment]
@ananyaks : Updated notes are also posted here in our [README.md](https://github.com/YugaByte/yugabyte-db#running-the-java-tests).

**Comment by ananyaks** [comment]
Hi @kmuthukk, @ttyusupov, I tried to run a single test with 
`./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient#testClientCreateDestroy` but it resulted in error in [single_test.log](https://github.com/YugaByte/yugabyte-db/files/2173333/single_test.log). The error is:

`java.lang.RuntimeException: Directory that is supposed to contain YB C++ binaries not found in either of the  following locations: /home/ananyaks/Documents/my-projects/yugabyte-db/build/debug-gcc-dynamic-community/bin, /home/ananyaks/Documents/my-projects/yugabyte-db__build/latest/bin`

In my local repo there is no directory at:
`/home/ananyaks/Documents/my-projects/yugabyte-db/build/debug-gcc-dynamic-community/bin`
and no directory called:
`/home/ananyaks/Documents/my-projects/yugabyte-db_build/ `

There is `home/ananyaks/Documents/my-projects/yugabyte-db/build/latest/bin` and the files in it are listed in [directory.log](https://github.com/YugaByte/yugabyte-db/files/2173335/directory.log).

I tried passing `release` with `./yb_build.sh release --scb --sj --java-test org.yb.client.TestYBClient#testClientCreateDestroy` and it worked and the output is in [single_test_success.log](https://github.com/YugaByte/yugabyte-db/files/2173337/single_test_success.log)

Based on the instruction 
`By default it will try to run against a debug build and it should be already built (or you can skip --scb --sj and it will build it for you).`

I am now trying without specifying `release --scb and --sj` to see if the debug build will work. I see that the build has re-started.

Should I just use `./yb_build.sh release` for testing?

Thanks!

**Comment by ananyaks** [comment]
Continuing from my above comment.

The build started by `./yb_build.sh --java-test org.yb.client.TestYBClient#testClientCreateDestroy` completed successfully along with running the test. The build also created the bin directory at `/home/ananyaks/Documents/my-projects/yugabyte-db/build/debug-gcc-dynamic-community/bin` and the files in this directory are:
`bfpg_codegen  protoc-gen-insertions  yb-master
bfql_codegen  protoc-gen-yrpc        yb-tserver`

I again tried `./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient#testClientCreateDestroy` and this time it worked without any errors.

Thanks!

**Comment by kmuthukk** [comment]
Thanks @ananyaks for the trying this out and suggestions.

Hi @ttyusupov 

Sounds like most of the examples (in Build & Test sections) of README.md use "release" option. So maybe we should update these two examples also to pass "release" option.

```
Alternatively, to run specific test:

./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient
To run a specific Java sub-test within a test file use the # syntax, for example:

./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient#testClientCreateDestroy

```

regards,
Kannan

**Comment by ttyusupov** [comment]
I've updated README with commit mentioned above.
