### ISSUE TITLE
issues upon insertion of very large JSONB

### ISSUE THREAD

**Issue by jurjenvg** [yugabyte/yugabyte-db#3545]
L.s.

I'm evaluating YugaByteDB for a commercial platform. We have mixed relational and very dense tabular data that would well fit Parquet files. I'm looking at storing these dense data sections as JSONB in order for inserts to be fast enough. The table structure I'm using is the following:
  
`DROP TABLE IF EXISTS pvdata; CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE TABLE public.pvdata (key uuid PRIMARY KEY DEFAULT gen_random_uuid(), value JSONB);`

I tried using the [PreparedStatement.setCharacterStream](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#setCharacterStream(int,%20java.io.Reader)), but this gives me following errors:

- occasional remote EOF exceptions from the PostGreSQL driver for very large arrays. I'm trying to insert an array with 500K objects, each Object according to the following JSON schema:
```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "a": {
                "type": "number"
            },
            "b": {
                "type": "number"
            }
            ...
            "z": {
                "type": "number"
            }

        }
    }
}
```
-occasional duplicate key exceptions, despite using server-assigned UUIDs

What is the recommended max-size for JSONB documents?
What is the recommended approach for inserting these? 
Am I trying something YDB isn't built for?

Thanks for your help,

Jurjen

**Comment by ddorian** [comment]
@jurjenvg how many MB is the value ?

In strict terms, JSONB compared to TEXT would be slower since it has to do conversion & validation. 

Is the `parquet` format smaller ? 

I'm assuming you won't need to search/index on the jsonb column, correct ?

**Comment by jurjenvg** [comment]
yes parquet is smaller, but currently unsupported by the DB's I'm looking at.
Is there a maximum recommended size for JSONB documents in YDB?
Is there a way to stream the document into YDB (as opposed to creating a (large) string and just sending it)?

**Comment by ajcaldera1** [comment]
@jurjenvg - Our RPC calls only support rowsizes up to 32MB currently, so if you are expecting a larger value, you will need to carve it up further / add additional key columns to distinguish record types (if possible). We can internally handle larger messages, but the protobuf library is subject to security issues at the larger sizes, so we've internally set the limit smaller. Even if we relaxed the internal limit, the maximum would only be somewhere ~510MB.  
As far as sending it -- either the string method or using the JDBC object method is supported.

**Comment by ddorian** [comment]
@jurjenvg why type of processing are you looking to do on the values ? Or just retrieve ?

**Comment by ddorian** [comment]
We have a potential bug with big values: #3586

**Comment by ddorian** [comment]
Our maximum row-size is up to `64MB`, but for consistent latencies & performance columns shouldn't be usually more than `~4MB`. 

Closing as duplicate of blobl/large-object feature request: https://github.com/yugabyte/yugabyte-db/issues/3576
