### ISSUE TITLE
[colocation] Refactor encoding / decoding of table IDs

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3551]
For colocated tables, we use a pg table IDs for user YSQL tables and cotable IDs for system tables as docdb prefix. Currently, the code for encoding / decoding these is in docdb itself, which might make the code harder to manage in future.

We should refactor and add a higher level abstraction for encoding / decoding these table IDs.

**Comment by frozenspider** [comment]
Colocation no longer uses table OIDs since #7378
