### ISSUE TITLE
Update frozen collection in place

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#356]
Hi,

Checked the docs but wasn't available. Is it possible to update frozen collections just like you do with normal collection ? It'll be slower, to serialize/deserialize the whole thing, but is it doable ? (ofc when they're not part of primary-key)

Regards,
ddorian

**Comment by rkarthik007** [comment]
Hi @ddorian,

No, I don't believe this is supported if you want to add and remove fine-grained items (but you can update the entire list). That said I think we might be able to support this. Is the fine-grained add/remove what you were looking for?

@m-iancu - could you please weigh in / correct me if I am mistaken?

Here is an example:

```
cqlsh:example> CREATE TABLE groups(
    group_name TEXT PRIMARY KEY, members FROZEN<LIST<TEXT>>);
cqlsh:example> INSERT INTO groups('friends', ['John', 'Smith', 'Laura']);
cqlsh:example> SELECT * FROM groups;

 group_name | members
------------+----------------------------
    friends | ['John', 'Smith', 'Laura']
```

Now you can update the `friends` group as follows:
```
cqlsh:example> UPDATE groups SET members = ['John', 'Smith', 'Laura', 'Jack']
    WHERE group_name='friends';
cqlsh:example> SELECT * FROM groups;

 group_name | members
------------+------------------------------------
    friends | ['John', 'Smith', 'Laura', 'Jack']
```

But we currently do not support:
```
cqlsh:example> UPDATE groups SET members = ['Cynthia'] + members WHERE group_name='friends';
InvalidRequest: Error from server: code=2200 [Invalid query] message="SQL error: Invalid Function Call. Failed calling '+(list<unknown>,frozen<list<text>>)'. Not found: Signature mismatch in call to builtin function '+'
UPDATE groups SET members = ['Cynthia'] + members WHERE group_name='friends';
```

**Comment by kmuthukk** [comment]
Yes, that (@rkarthik007 's response) is my understanding too.

What we have right now is similar to Apache Cassandra. That is - with frozen types, currently, the entire value must be overwritten. 

But, as @rkarthik007 mentioned, this is something we can add support for. 

In other words, we can allow all the mutation operations on frozen types to work with native syntax such as:
 
```
 UPDATE ... SET col = ['new_entry'] + col
```

and so on. While the implementation will incur a deserialize/serialize overhead, YugaByte will take care of the atomic update on the server side (and this approach avoids the need for a client-controlled read-modify-write operation that also incurs an extra client-server RPC). 

As a note: all this is already possible with the non-frozen variant of collection types - but looks like you want to optimize for the storage overhead that non-frozen types for the case where updates are relatively rare?

In terms of priority, how important/urgent is this for you?

**Comment by ddorian** [comment]
Yes, fine grained updating. 

It's not too urgent for me.

**Comment by ddorian** [comment]
works as expected
updating single values can be done with `jsonb`
