### ISSUE TITLE
[docdb] change default compaction settings

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3561]
Please change the default compaction settings to

cores      compaction setting
4       --      2
8       --      3
16     --     6
32     --     12
48     --    18
64     --      24

**Comment by bmatican** [comment]
We ended up going with:
2 -- 1
4 -- 2
X>4 -- `floor(3.5 * X / 8)` (notably 16 cpu -> 7 compaction threads)
