### ISSUE TITLE
Change parallelism for backups and restore on large clusters

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3564]
Change how many parallel tasks we perform for backups and restore on clusters with large number of nodes to take advantage of the available resources and to speed up the tasks.

**Comment by bmatican** [comment]
Closing this for now, as we have a knob in YW to select parallelism and it goes nicely round robin across the respective TS.

However, we have some leftover follow up work
- do IO and CPU work in parallel (https://github.com/yugabyte/yugabyte-db/issues/3852)
- bump default parallelism depending on number of nodes (https://github.com/yugabyte/yugabyte-db/issues/7090)
