### ISSUE TITLE
[YSQL] Option to ignore duplicates in non-txn COPY

### ISSUE THREAD

**Issue by danielmh0** [yugabyte/yugabyte-db#3566]
Jira Link: [DB-2218](https://yugabyte.atlassian.net/browse/DB-2218)
Non-transactional COPY https://github.com/yugabyte/yugabyte-db/issues/1926 is useful for bulk loading data into a new database. If a large COPY has an error, it is natural to retry. However, the retry will return an extremely large error message with a concatenated "Duplicate key found in primary key or unique index" for every row that already exists. Clients need to scan this string, looking for any other error conditions potentially returned.

Returning the duplicate error was specifically requested in https://github.com/yugabyte/yugabyte-db/issues/2289. Can we have an option for disabling it? Maybe COPY TO...WITH IGNORE_DUPLICATES; ?

**Comment by kmuthukk** [comment]
Thx @danielmh0 for filing this enhancement request -- makes a lot of sense. 

Thx also for researching & linking to the relevant prior issues on this topic.

**Comment by sushantrmishra** [comment]
We have added `REPLACE` option in [copy](https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/cmd_copy/) command which can be  used to avoid duplicate key check.
