### ISSUE TITLE
What kind of security does YugaByte offer for distributed clusters and where is the documentation?

### ISSUE THREAD

**Issue by yjiangnan** [yugabyte/yugabyte-db#358]
Hi,

I am trying to setup a test YugaByte cluster using two local Mac computers at home and a remote Alibaba linux cloud server. I got it done with Rethinkdb and it works fine. However, I encounter two problems that I cannot find answers to with YugaByte. 

First, how can I let YugaByte on remote computers to know each other's existence to get the system running? In Rethinkdb, this is done by setting both the IP address/domain names that peers have and the IP address/domain name of a server itself known to others:

    ## Address that other rethinkdb instances will use to connect to this server.
    ## It can be specified multiple times
    canonical-address=47.52.15.xx

This would presumable avoid attacks from unknown sources. However, I cannot find such setting for YugaByte and not even ways to get this 3-remote-server system to work.

Second, how can I set up user access controls? What if a hacker get into one server of the cluster and decide to DROP all the tables or maliciously modify it?? Ideally, I only want the cluster to insert records into some tables (e.g., transaction sequence) so that things can be verified later in case of problem. Big changes of the tables should only be allowed by a user whose password is not saved on the server (and only the hash of the password is compared to during access). 

It seems that YugaByte has public/private key access control in your example of the Enterprise Edition. However, I cannot find it for manual setup anywhere. I am trying for a small startup so that I cannot pay for the Enterprise in the first couple of years. But my own code has to be written now. It does not seem logical if I have to re-write my code a couple of years later if I want to switch to the paid version in case of business success. It would be so much better if YugaByte just limit the maximum scalability (say <10 nodes) for the free version to allow small startups to survive and make the deployment more transparent for educational purposes. Limiting the usability is not a good way to draw new users into this community.

**Comment by rkarthik007** [comment]
Hi @yjiangnan,

> First, how can I let YugaByte on remote computers to know each other's existence to get the system running?

Please refer to the [manual deployment guide for YugaByte](https://docs.yugabyte.com/latest/deploy/manual-deployment/). We would love to get any feedback you have in case its not clear as we always try to improve our documentation.

To answer you question specifically, the masters are set up by running the following command on each of the master machines:
```
./bin/yb-master \
  --master_addresses <MACHINE1>, <MACHINE2>, <MACHINE3>
  ...
```
This is the way to inform one machine of the others. Does that help? BTW, would be happy to get on a hangouts or gitter chat session if that would be useful.

> Second, how can I set up user access controls?

This is being worked on actively, and should be out soon. Here are the set of tasks currently in progress:

[#360] Add username/password based authorization for YCQL
[#361] Add ALTER ROLE support to change default password
[#72] Add Cassandra ROLE support
[#73] Add Cassandra Permissions support

The master task is a handy placeholder for some of these: [#183]

> It seems that YugaByte has public/private key access control in your example of the Enterprise Edition. However, I cannot find it for manual setup anywhere.

I didnt understand this fully. Could you please point out to me what you are referring to so I can help out better?

> It does not seem logical if I have to re-write my code a couple of years later if I want to switch to the paid version in case of business success.

Completely agree with you! We have taken great pains to ensure all features you would have to write code to are all in the open.

**Comment by yjiangnan** [comment]
Hi @rkarthik007 

    ./bin/yb-master \
      --master_addresses <MACHINE1>, <MACHINE2>, <MACHINE3>
      ...
The problem with this is that each machine has different internal and external addresses and may also be located by domain names but the example only deals with a local cluster's local IP addresses. For example, my two home computers are known to each other as 192.168.1.2 and 192.168.1.5. They are behind a firewall and I have applied a domain name `myname.ddns.net` using No-IP since the ISP changes my external IP everyday. My cloud server has a public IP but it only knows its local address (it does not know its public IP address!). Then, how should the command look like? Is it the same on different  machines? Will it try to connect to itself through the public IP address and thus incur a cost on bandwidth? (Alicloud charges fees for external bandwidths and no fee for internal bandwidths within their data center.) 

Specifying only one IP address for a server also creates a security hole, since an attacker can fake its IP address and pretend to be one of the masters and send malicious command to them as soon as he figures out the address of two servers even without breaking into the servers.  I think this is why Rethinkdb requires one to setup its canonical-address (=='myname.ddns.net:port' for my home computers) that is known by others. If a server connecting to others cannot show its canonical address known by others, the connection will be refused. This just adds another layer of security.

This page uses ssh private and public keys to connect to servers:

https://docs.yugabyte.com/latest/manage/enterprise-edition/create-universe-multi-region/

However, it is unclear whether servers connecting to each other by the same way. Additionally, is the connection encrypted? 

> Completely agree with you! We have taken great pains to ensure all features you would have to write code to are all in the open.

The problem is that your documentation site has separate pages for Enterprise Edition and at the same time the documentation is missing for the community edition. By the way, I am in Germany so a chat might be difficult due to difficulty of coordination of working hours. But thanks for the invitation anyway. 

In terms of making better documentation or the database itself, I think you guys can still learn from Rethinkdb. Although they failed, but that is just because of their poor marketing skills instead of the project itself. For example, Rethinkdb docs put examples for different OS and programming languages and you can choose your favorite to show. Their query language is also clear, intuitive and safe. In your case, you only put examples in the very basic form inside cqlsh but that is not what a programmer should eventually use. Although you pointed out you support several database APIs, but there is a big assumption that the users already know those APIs but I know none of them (Yes, I do not have a formal server stuff education but you guys should expect some heterogeneity in your user population). Additionally, as you guys pointed out in our discussions, you still do not support all their APIs, making it really confusing of what actually can be used. Imagine the learning curve of your users. Do they have to learn all the three databases with documentations scattered on different sites, inconsistent styles and different programming languages to finally be able to comfortably use your database? I mean, your project is cool; but the documentation really deserves some serious improvements. Additionally, Rethinkdb supports change feeds to power real time applications. I have no idea whether YugaByte has this support or plan for support or not.

**Comment by rkarthik007** [comment]
Hi @yjiangnan,

We are currently actively working on the feature you ask - which is essentially a variant of public and private ip support so that it is easier to work with public clouds. This is something we are currently implementing and have been discussing. cc @pritamdamania87 @spolitov on this (please see the previous comment on using dns names as the broadcast address).

Wrt the public/private keys in the enterprise page - that is used for ssh into the machines to manage them. Our enterprise edition spins up nodes on you behalf, making it almost like a managed service in your own account.

Thanks for the candid feedback about our documentation. We will definitely take a look. We are building up our docs as fast as we can. Our quick start guide has the simple steps, we have slightly more details here:
https://docs.yugabyte.com/latest/develop/client-drivers/
https://docs.yugabyte.com/latest/develop/learn/
https://docs.yugabyte.com/latest/api/

> Additionally, Rethinkdb supports change feeds to power real time applications. I have no idea whether YugaByte has this support or plan for support or not.

Yes we have been asked for a "streams" feature where apps can subscribe to changes. This is in the roadmap.

**Comment by pritamdamania87** [comment]
Hi @yjiangnan 

> Specifying only one IP address for a server also creates a security hole, since an attacker can fake its IP address and pretend to be one of the masters and send malicious command to them as soon as he figures out the address of two servers even without breaking into the servers. I think this is why Rethinkdb requires one to setup its canonical-address (=='myname.ddns.net:port' for my home computers) that is known by others. If a server connecting to others cannot show its canonical address known by others, the connection will be refused. This just adds another layer of security.

I was trying to understand your comment above. Do you mean that each server would know the public/private IPs of every other server and then validate that incoming connections are only from those set of IPs? When you refer to Rethinkdb supporting dns names and a server connecting has to show its canonical address, how does this server show its canonical address? The only way a server can prove it owns a domain is through TLS and signed certificates (this is something we are working on as well).

In terms of broader support for your original deployment scenario, we are working on supporting public and private IPs for all YB nodes and also a way to configure a policy that these nodes should use when choosing whether to use a public/private IP to connect to.

**Comment by yjiangnan** [comment]
Hi @pritamdamania87 

I am not an internet expert but I can tell you my experience with Rethinkdb. 

Basically, before startup of Rethinkdb, you have to set up a config file, e.g. (I delete the irrelevant part):
```

#
# RethinkDB instance configuration sample
#
# - Give this file the extension .conf and put it in /etc/rethinkdb/instances.d in order to enable it.
# - See http://www.rethinkdb.com/docs/guides/startup/ for the complete documentation
# - Uncomment an option to change its value.
#

### Network options

## Address of local interfaces to listen on when accepting connections
## May be 'all' or an IP address, loopback addresses are enabled by default
## Default: all local addresses
bind=all

## Address that other rethinkdb instances will use to connect to this server.
## It can be specified multiple times
canonical-address=myname.ddns.net
canonical-address=192.168.1.5

## The host:port of a node that rethinkdb will connect to
## This option can be specified multiple times.
## Default: none
join=remote.server.com:29015
join=192.168.1.2:29014

server-name=home

## tls

## Path to tls key/cert for driver interface (Default: disabled)
## Default: disabled
# driver-tls-cert=cert.pem
# driver-tls-key=key.pem
```
This is a config file for my home computer with IP 192.168.1.5, other computers have slightly different contents because they have to point to each other. This file specifies its canonical-address for both local connections and public connections. It also specifies which addresses it should connect to. If I comment out the line `canonical-address=myname.ddns.net`, then my local computer with address 192.168.1.2 would still successfully connect, but the remote cloud server will refuse the connection and complain that the server myname.ddns.net:29015 (i.e. this computer) does not match the actual address (showing my home public IP address:29015). This mechanism is of course not as secure as certificate based mechanism, but an attacker would still need knowledge for the domain names to initiate the attack, since you do not have to tell people which domain names you have assigned to the servers and you can use some secret domain names only known by you and the your domain name provider.

**Comment by yjiangnan** [comment]
Hi @pritamdamania87 

Is there any progress on supporting both private and public addresses? When can I expect to get that release? I hope it would be as easy to use as in Rethinkdb. I am trying to setup Cassandra these days, but it seems like a torture, with incomplete documentation, complicated setups, and unexpected errors. 

Thanks!

**Comment by kmuthukk** [comment]
hi @yjiangnan 

This is the issue tracking this: https://github.com/YugaByte/yugabyte-db/issues/389

The main commit has landed: https://github.com/YugaByte/yugabyte-db/commit/e65b6ed72d1ee5a5c366df402a71cdaefae06803

Some doc updates remain to be done. We plan to do so soon.

CC: @spolitov , @bmatican - are there any other open issues in this area?

**Comment by rkarthik007** [comment]
A lot of the security documentation is done here now: https://docs.yugabyte.com/latest/secure/
Closing this issue out.
