### ISSUE TITLE
[Platform] Display table sizes in the Tables page of YW

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3581]
Table size info is already available in the prometheus metrics. We display it in the table level metrics page. 

It will be very useful to display this in the YW Tables page to see which tables are the biggest etc...

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-730

**Comment by rkarthik007** [comment]
We need a deeper discussion on this. cc @iSignal @bmatican @rao-vasireddy

**Comment by chirag-yb** [comment]
@sshev We also need to add sort capability on this page in case there are hundreds of tables and users want to sort by table size.

**Comment by iSignal** [comment]
Done and cherry picked into 2.2.2.1
