### ISSUE TITLE
[YCQL] Inserting 10+MB rows takes exponential time on unprepared statements

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#3586]
Notes: 

1. Max row-size is `67108864`
2. With prepared statement, 64MB takes 0.8s
3. With not prepared statement: 10MB takes 37s (cassandra 0.25s)
4. Postgresql is 0.9 - 1.4s for 64MB (unprepared)
script.py:
```python
from cassandra.cluster import Cluster
from time import time
import psycopg2

# Create the cluster connection.
cluster = Cluster(['127.0.0.1'])
session = cluster.connect()
# Create the keyspace.
session.execute(
    "CREATE KEYSPACE IF NOT EXISTS ybdemo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};")
# Create the table.
session.execute("drop table if exists ybdemo.employee;")
session.execute("CREATE TABLE IF NOT EXISTS ybdemo.employee (id int PRIMARY KEY, name text);")
print("Created table employee")
string_val = "x" * 64 * 1024 * 1024
print(f"string_val_len:{len(string_val)}")
prepared_s = session.prepare("INSERT INTO ybdemo.employee (id, name) VALUES (1, ?);")
# Insert a row.
start = time()
session.execute(prepared_s, (string_val,), timeout=60)
print(f"end:{time() - start}")

conn = psycopg2.connect("dbname='yugabyte' user='postgres' host=127.0.0.1 password='' port=5433")
conn.autocommit = True
cur = conn.cursor()
cur.execute("CREATE TABLE IF NOT EXISTS ybdemo(id BIGINT, name TEXT);")
sql_start = time()
cur.execute("INSERT INTO ybdemo(id,name) VALUES(1,%s) RETURNING *;", (string_val,))
print(f"sql_time: {time() - sql_start}")
cur.execute("SELECT count(*) FROM ybdemo;")
print(cur.fetchall())

```
output
```
reated table employee
string_val_len:67108864
end:0.8587119579315186
sql_time: 1.2377617359161377
done!
[(4,)]
```

**Comment by kmuthukk** [comment]
hi @ddorian --

Assigning back to you to triage a few things:

1) Compare your current "execute" approach with a "prepare" approach where you then execute the same prepared statement with binds of varying sizes. Let's try to figure out if it is "compile" vs. "run-time" issue.

2) Would be great to write a similar test in YSQL also; again this will confirm if it is a DocDB layer issue or issue specific to the upper-half (query layer).

----

Separately, mention the language your test script is in. Looks like Python (but why make the reader guess).

---

After above, we can reassign back appropriately. Thx!

**Comment by ddorian** [comment]
@kmuthukk only happens in unprepared-ycql statements.

**Comment by ouvai59** [comment]
PR to fix this issue is at https://github.com/yugabyte/yugabyte-db/pull/4397/files
