### ISSUE TITLE
Add `returning *` clause to update/delete

### ISSUE THREAD

**Issue by ddorian** [YugaByte/yugabyte-db#359]
Hi,

From docs it's not available, right ?
It will convert update/delete from non-reading to reading but better than doing 2 queries.

Regards,
ddorian

**Comment by kmuthukk** [comment]
Hi @ddorian 

Yes, will certainly look into adding RETURNING clause like in traditional databases to avoid need for a subsequent round-trip/query.

regards,
Kannan

**Comment by kmuthukk** [comment]
In terms of prioritization, is it a nice to have for you, or are you looking for this in the near term @ddorian ?

**Comment by ddorian** [comment]
I'm looking for this. It will be needed by https://github.com/YugaByte/yugabyte-db/issues/347 too I think, right ?

**Comment by ddorian** [comment]
Fixed in YSQL.
