### ISSUE TITLE
[Platform] Backup schedule should allow schedules for multiple tables

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3592]
Currently there are only 2 ways you can create backup schedules. 
1. Schedule for all the tables in the universe
2. Schedule for an individual tables.

We should also be able to create a schedule for multiple tables.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-724

**Comment by yb-andrew** [comment]
Fixed by adding keyspace/universe backups.
