### ISSUE TITLE
Add username/password based authorization for YCQL

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#360]
This feature will allow authentication of users that connect to a cluster.

* Every YugaByte node (tablet server) needs to be started with the following flag to enable authentication of users. The default value of this flag is `false`. Setting this flag to true will require a valid username and password to connect.
```
--use_cassandra_autherntication=true
```

* The default username/password is `cassandra`/`cassandra`. This can be changed by performing an `ALTER ROLE` command.

* When running `cqlsh` against a cluster with authentication enabled, you will need to run the following
```
cqlsh -u <USER> -p <PASSWORD>

# For example, you can do the following to connect with the default values.
cqlsh -u cassandra -p cassandra
```

* In order to use authentication with the Java client for example, call the following method in the Cluster object:
```
public Cluster.Builder withCredentials(String username, String password);
```

**Comment by hectorgcr** [comment]
The commit https://github.com/YugaByte/yugabyte-db/commit/16960cf537fe05733f4c72685e20dfdf31a46456 finishes this feature

**Comment by rohitjoshi** [comment]
Great 👍
