### ISSUE TITLE
Dose the distributed SQL in yugabyte-db can push conditions down to storage layer?

### ISSUE THREAD

**Issue by shengyunyao** [yugabyte/yugabyte-db#3605]
Dose the distributed SQL in yugabyte-db can push conditions down to storage layer, like Coprocessor oin TiDB.

**Comment by ddorian** [comment]
Yes we do pushdowns to storage layer. Currently some operations aren't there yet and many more will be added to version 2.1. Are you interested in any query/filter in particular ?

Note that compute+storage layer are on the same process and use less inter-process communication compared to tidb/tikv.

**Comment by shengyunyao** [comment]
Do both ysql and ycql push down the operations to storage layer?

**Comment by ddorian** [comment]
Yes. Both layers are implemented on top of [YQL](https://docs.yugabyte.com/latest/architecture/query-layer/overview/). All improvements in YQL are inherited in both layers.

**Comment by shengyunyao** [comment]
That is wonderful. Any docs or commits for me to dive into it?

**Comment by rkarthik007** [comment]
Hi @shengyunyao - I am wrapping up a detailed post about this, should be out this week or next. Please stay tuned!

**Comment by shengyunyao** [comment]
Thank you very much. Looking forward to your post to see how pgsql works in yugabyte.

**Comment by rkarthik007** [comment]
The blogpost is published here: https://blog.yugabyte.com/5-query-pushdowns-for-distributed-sql-and-how-they-differ-from-a-traditional-rdbms/
