### ISSUE TITLE
[YW] Backup script should be able to determine correct port for ssh for onprem environments

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3615]
The backup script needs to examine the connect as user and determine the correct port to ssh on to a machine managed by the on-premise flow. Currently it defaults to "centos" and attempts to "sudo -u yugabyte" (which may not always be permitted) via our default port of 54422 for SSH.

**Comment by ajcaldera1** [comment]
Bump

**Comment by rkarthik007** [comment]
@WesleyW - is this done? Can we please close this out if so?

**Comment by WesleyW** [comment]
Yes, done as of feb843c @rkarthik007
