### ISSUE TITLE
[YCQL] Support for CONTAINS expression from Cassandra for collections in SELECT

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#3620]
Jira Link: [DB-4682](https://yugabyte.atlassian.net/browse/DB-4682)
Cassandra support an expression CONTAINS which can check if an collection contain an element or not. Something like :

```
CREATE TABLE test.table_name(
    id text,
    ckk SET<INT>,
    PRIMARY KEY((id))
);

Select * FROM table_name WHERE id = 1 AND ckk CONTAINS 4;
```
it help categorizing rows and then fetch set of rows with a specific category (or maybe many other usage ).

[DB-4682]: https://yugabyte.atlassian.net/browse/DB-4682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by allesklarbeidir** [comment]
I'd say this feature is highly needed for many applications and is a basic feature in many NoSQL Databases (e.g. MongoDB, Cassandra, CouchDB). I support this feature request, it would help a lot!

Is there any recommended work-around for now?

**Comment by kmuthukk** [comment]
Hi @allesklarbeidir -

Thx - this is definitely a reasonable request. We'll take a look at scope of the work, and when we can prioritize this. Hope to get back to you with some update on this by next week.

**Comment by knicely87** [comment]
Fyi, while we wait for the CONATINS feature, as a work around in the field, below are two "work-arounds" we've thought of to help customers/prospects implement a CONTAINS-like feature in YCQL:

[SEARCH A LIST COLLECTION DATA TYPE IN YCQL](https://yugabytedb.tips/?p=2759)
[SEARCH A LIST COLLECTION DATA TYPE IN YCQL (BY USING A MAP INSTEAD)](https://yugabytedb.tips/?p=2778)

**Comment by Rahulbiju315-yb** [comment]
Related Issue (CONTAINS KEY support): https://github.com/yugabyte/yugabyte-db/issues/17676

**Comment by dr0pdb** [comment]
Reopening for backports
