### ISSUE TITLE
[YSQL] Parallelize aggregate queries like count(*)

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3624]
Today, simple aggregate queries like `select count(*)`, `select max(column)` etc. are pushed down to tablet servers. The push down, however, is sequential where we send an RPC to one tablet at a time.
We should parallelize this to make it more performant.

Things to think about:
1. How to parallelize across large number of tablets?
2. How to handle tablet RPCs that timeout?
3. How to handle tablet scans that take a long time?

**Comment by ddorian** [comment]
> How to parallelize across large number of tablets?

Group the tablets by yb-tserver. Each server does parallel on it's own tablets.
If there are a lot of servers, sort them by `number_of_leaders`, and pick bottom(x) to act as parallel children agg. Servers with few tablets will have lower load and extra capacity to serve as child aggregators. (or order by server_load if/when we keep track)

Have a config/flag that can be set per-query/transaction to control number of concurrency. This way clients can specify if they want fast/slow queries. `SET max_agg_workers=4` etc.

> How to handle tablet RPCs that timeout?
> How to handle tablet scans that take a long time?

Is there a way for the server to return `keep rpc alive, still computing` , which increases the timeout of the current request ?

> How to handle tablet scans that take a long time?

Assuming multiple simultaneous agg queries, implement scan-sharing.
