### ISSUE TITLE
[YSQL] Extend support for metrics percentiles to PG layer

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3630]
Jira Link: [DB-1324](https://yugabyte.atlassian.net/browse/DB-1324)
As a follow-up to #3362, we need to port the `Histogram` usage into `pgsql_webserver_wrapper`, so we can expose percentiles there too.

**Comment by bmatican** [comment]
cc @rahuldesirazu if you'd like to take a stab at this?

I think the crux of this is to validate that we can use the `metrics` in the YSQL webserver code, so we can replace the custom struct we have for accounting now, with an actual `Histogram`.

**Comment by bmatican** [comment]
Tried doing some preliminary investigation on this. Getting the code to build using histograms was not a problem, but the actual data sharing piece seems non trivial...

Spoke to @m-iancu and it seems we might end up having to re-implement the metrics/hdr_histogram to somehow be able to keep it in shared memory and have the backends modify it (with locking) and the webserver to read it.

**Comment by sushantrmishra** [comment]
Closing this as work to add histogram support is tracked in https://github.com/yugabyte/yugabyte-db/issues/14445
