### ISSUE TITLE
[YSQL] Provide ability to install ysqlsh command line tool independently of YugabyteDB

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3635]

**Comment by jj-kim** [comment]
Actually, reopening because the release archives aren't yet publicly available for download.

**Comment by iSignal** [comment]
#3770 for docs

**Comment by jj-kim** [comment]
Closing due to commit 7c0a905377edc271835f8cc64f7f1706e37bdb4d.  Deferring documentation to the issue number specified above.
