### ISSUE TITLE
[cdc] Ability to Delete & List CDC Streams for yb-admin

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#3638]
We currently have "yb-admin create_cdc_stream" but no corresponding commands to list the existing CDC streams or delete a CDC stream once we create it.  This will also give us a repair tool for dangling 2DC configurations on the Producer.

**Comment by bmatican** [comment]
@abigalekim can you confirm if this actually already works? if so, let's just close the issue
