### ISSUE TITLE
Transactional data load performance improvements

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#3656]
Jira Link: [DB-1672](https://yugabyte.atlassian.net/browse/DB-1672)
Investigate and improve data loading in YSQL when using transactional batches of 100, 1K and 10K  operations per batch.

**Comment by sushantrmishra** [comment]
This is covered by bulk loading improvements. We also set the rows_per_transaction to 20k based on the test results.  GH issue https://github.com/yugabyte/yugabyte-db/issues/12293
