### ISSUE TITLE
[docs] Set up for TLS in Kubernetes

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3660]
Document how to configure server-to-server encryption (using TLS) in Kubernetes.
- Create a secret
- Apply a secret
- Create volume and volumeMount in Helm Chart
- Update options for `yb-master` and `yb-tserver`

**Comment by lizayugabyte** [comment]
Our YB Anywhere TLS docs are up to date. Closing this old ticket.
