### ISSUE TITLE
[Phase 3][Colocation] Master UI shows incorrect number of tablets for colocated tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3674]
Jira Link: [[DB-394]](https://yugabyte.atlassian.net/browse/DB-394)
See the screenshot for a colocated DB containing 4 tables. Tablet Server page shows 4 tablets instead of 1.

![image](https://user-images.githubusercontent.com/15746068/74767479-c29f7680-523b-11ea-8dfb-ad280fec0d3b.png)

[DB-394]: https://yugabyte.atlassian.net/browse/DB-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ouvai59** [comment]
Submitted fix: https://github.com/yugabyte/yugabyte-db/pull/4699

Please review.

**Comment by ouvai59** [comment]
New PR - https://github.com/yugabyte/yugabyte-db/pull/4699/files

**Comment by tverona1** [comment]
This is already fixed with the above commits (verified)
