### ISSUE TITLE
[YW] Add ability to customize S3 target in backup configuration

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3684]
In the cases of large enterprises that have their own internal s3 implementations, we need to be able to target a host other than s3.amazonaws.com. This requires two additional lines in the s3cfg file:
```
host_base=s3.somecorp.com
host_bucket=%(bucket)s.s3.somecorp.com
```

**Comment by ajcaldera1** [comment]
Bump

**Comment by WesleyW** [comment]
Currently in review. Added the lines to the config file

**Comment by WesleyW** [comment]
Committed in fd9f5d2
