### ISSUE TITLE
Automatically update brew package on new yb release

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#3728]
https://github.com/yugabyte/homebrew-yugabytedb currently has the brew formula which manually encodes the version of yugabyte to download from. We need to automatically bump this when a new version is released.

**Comment by bhavin192** [comment]
https://github.com/yugabyte/homebrew-yugabytedb/pull/13 has been merged and version of yugabytedb package gets updated automatically. 
https://github.com/yugabyte/homebrew-yugabytedb/commit/949a9990264c76e19a3876e96cbb22b5819b2f7b
https://github.com/yugabyte/homebrew-yugabytedb/commit/6dda9b1846fb093caeede70242429069f752d6fc
