### ISSUE TITLE
Add a partition_hash builtin like token but using YB hash

### ISSUE THREAD

**Issue by pritamdamania87** [YugaByte/yugabyte-db#374]
CQL token() built-in assumes int64 hash whereas we use uint16 internally so we have to bucket-ize and lose some precision.

To use or own without creating incompatibility with CQL apps we should create our own builtin `partition_hash` that would take as input (and evaluate to) our uint16 hashes. Then we can migrate users/apps to our version over time.

Our fork of the Spark driver can be a good initial candidate for using partition_hash (instead of CQL token ).

**Comment by kmuthukk** [comment]
Implemented in https://github.com/YugaByte/yugabyte-db/commit/7eab0cba5860dd988af48db2cf652e264852b0bd
