### ISSUE TITLE
Excessive output from Maven dependency plugin during the build

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3740]
Produced by the combination of dependency:resolve dependency:resolve-plugin dependency:go-offline

https://gist.github.com/mbautin/b4fa3dc36f406fb2c38d3259cb6a4d49/raw

Maven dependency plugin documentation: https://maven.apache.org/plugins/maven-dependency-plugin/

**Comment by svarnau** [comment]
Duplicate of issue #4356?

**Comment by mbautin** [comment]
Yes, closing.
