### ISSUE TITLE
[docdb] Make global LogCache usage be a percentage of total memory

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3745]
Currently, the default max LogCache memory usage is 1GB, as opposed to a % based model, like the rocksdb block caches or memstores. We should add a percentage based mechanic to the LogCache as well, so it is more uniform where our memory goes.

**Comment by bmatican** [comment]
This could be a nice followup to the recent refactor of TSTabletManager components, including LogCache GC

**Comment by bmatican** [comment]
In `src/yb/consensus/log_cache.cc`, we already have memory limits
- per each tablet, default 128MB
- global, across all tablets, default 1024MB

For a more uniform way of accounting for memory, we should add a % of RAM based flag as well. We can start with something small, like 5%, for now.

We have a similar mechanism for rocksdb memstores, with more details in `src/yb/tserver/tablet_memory_manager.cc`. Individual memstores are capped by `memstore_size_mb`, default 128MB. But then we have 2 global limits: `global_memstore_size_mb_max`, default 2048 and `global_memstore_size_percentage`, default 10. We then just take the minimum of the respective values.

**Comment by SrivastavaAnubhav** [comment]
Fixed by #3745
