### ISSUE TITLE
"create unique index" appears to create the index when indexed column has dups

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#3762]
Try this first in vanilla PostgreSQL:
```
create table t(k int primary key generated always as identity, v varchar);
insert into t(v) values
  ('x'),
  ('x');

create unique index t_v on t(v);
select k, v from t order by k;
\d t
```
It causes this expected outcome:
```
ERROR:  could not create unique index "t_v"
DETAIL:  Key (v)=(x) is duplicated.
```
Following this, `\d t` shows this:
```
 k      | integer           |           | not null
 v      | character varying |           |
Indexes:
    "t_pkey" PRIMARY KEY, btree (k)
```
Now try the same in YugabyteDB v 2.0.11. It causes this outcome:
```
ERROR:  duplicate key value violates unique constraint "t_v"
```
But  `\d t` shows this:
```
 k      | integer           |           | not null
 v      | character varying |           |
Indexes:
    "t_pkey" PRIMARY KEY, lsm (k HASH)
    "t_v" UNIQUE, lsm (v HASH)
```
This is the bug. However, I can't tell if it's a just metatdata bug. But I'm guessing that it is, and that the index doesn't exists because this:
```
insert into t(v) values('y');
insert into t(v) values('x');
select k, v from t order by k;
```
Silently succeeds and we see that table `t` now has three duplicates of the value `'x'`.

**Comment by jj-kim** [comment]
I came across this as well.  With my similar steps, logs show

```
I0403 13:35:25.345330  6756 table_creator.cc:277] Created index yugabyte.a_i_idx of type PGSQL_TABLE_TYPE
```

and the indexes show up in the web UI localhost:7000.  Running the same `CREATE UNIQUE INDEX` multiple times continues to add the index, according to the web UI.

**Comment by jj-kim** [comment]
This appears to be a problem with the handler for lsm vs btree.  See `src/postgres/src/include/catalog/pg_am.dat` for why the handlers are `bthandler` and `ybcinhandler`.

Vanilla PostgreSQL btree:

```
index_create
  heap_create
  index_build
    bthandler
      btbuild
        _bt_spools_heapscan
          tuplesort_begin_index_btree
            comparetup_index_btree
              errmsg("could not create unique index \"%s\"",
```

Yugabyte lsm:

```
index_create
  heap_create
  YBCCreateIndex
  index_build
    ybcinhandler
      ybcinbuild
        IndexBuildHeapScan
          IndexBuildHeapRangeScan
            ybcinbuildCallback
              YBCExecuteInsertIndex
    index_update_stats
      ...
        yb::pggate::PgSession::HandleResponse
          Format("duplicate key value violates unique constraint \"$0\"", Slice(constraint_name)),
```

I haven't looked into how vanilla PostgreSQL cleans up failed index creations, but a comment claims to

```c
     /*                                                                         
     * create the index relation's relcache entry and, if necessary, the       
     * physical disk file. (If we fail further down, it's the smgr's           
     * responsibility to remove the disk file again, if any.)                  
     */
    indexRelation = heap_create(indexRelationName,
```

cc: @m-iancu

**Comment by ndeodhar** [comment]
This. was fixed as part of https://github.com/yugabyte/yugabyte-db/issues/3462

**Comment by jaki** [comment]
I'm confused how closing #3462 also fixes this because that was closed long before (January 31, 2020).  I'm also able to reproduce the issue, visible through the master UI as I explained previously.

**Comment by ndeodhar** [comment]
@jaki See this:
```
yugabyte=# create table t(k int primary key generated always as identity, v varchar);
CREATE TABLE
yugabyte=# insert into t(v) values
yugabyte-#   ('x'),
yugabyte-#   ('x');
INSERT 0 2
yugabyte=# 
yugabyte=# create unique index t_v on t(v);
ERROR:  duplicate key value violates unique constraint "t_v"
yugabyte=# select k, v from t order by k;
 k | v 
---+---
 1 | x
 2 | x
(2 rows)

yugabyte=# \d t
                                 Table "public.t"
 Column |       Type        | Collation | Nullable |           Default            
--------+-------------------+-----------+----------+------------------------------
 k      | integer           |           | not null | generated always as identity
 v      | character varying |           |          | 
Indexes:
    "t_pkey" PRIMARY KEY, lsm (k HASH)

```

As you can see,  there is no unique index on the table because index creation failed. (Compared to what. @bllewell reported earlier where YSQL still had `"t_v" UNIQUE, lsm (v HASH)` index).

However, you're right that the master UI shows the orphaned t_v index in docdb. That's because we don't have rollbacks yet between docdb and YSQL and will be fixed as part of the online schema migration work.
Note that having this lingering docdb index does not cause any functional or performance impact because that index will not be used for any reads/writes.
