### ISSUE TITLE
Website Usability

### ISSUE THREAD

**Issue by andymans** [yugabyte/yugabyte-db#3769]
Do something with your chat widget (preferably just remove it entirely) - you have managed to create a UX person's worst nightmare! Your abandonment rate must be off the scale :-)

**Comment by rkarthik007** [comment]
Thanks for the feedback @andymans - and totally agree with you. In fact, its been annoying me as well 😄 but realized that only after you pointed it out. We will fix this soon.

**Comment by andymans** [comment]
Great stuff! 🥇
