### ISSUE TITLE
[docs] Add docs for how to download and install ysqlsh/cqlsh

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#3770]

**Comment by iSignal** [comment]
Current methods:

* `docker run yugabytedb/yugabyte bin/ysqlsh -h <hostname> -p <port>`
* `wget -q -O - https://downloads.yugabyte.com/get_clients.sh | sh && yugabyte*/bin/ysqlsh`
* `brew install yugabyte-client`

**Comment by polarweasel** [comment]
Related to #1978
