### ISSUE TITLE
[docdb] Investigate enabling other compression algorithms

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3785]
Currently, we use snappy for rocksdb files by default. However, rocksdb has support for various compression algorithms.

@psudheer21 recommended considering `LZ4`:
> Compression is about 40% faster and decomprssion is 150% faster.

@ddorian also suggested looking at rocksdb dictionary compression: https://github.com/facebook/rocksdb/wiki/Dictionary-Compression

For all of these, we should be able to do some simple high-pass tests, like:
- create a local cluster
- load a fixed, large amount of data (say 1-10M rows)
- do a compaction to drop down to 1 file, for consistent test results
- time a `select *` or `select count(*)`, to force scanning all the data and going through decompression path

For the actual compression path, it only factors in at the flush/compaction level. Since that's background work, we could probably just use a rocksdb specific benchmark style unit test (if we don't already have one), to get some baseline numbers on speed of compression/decompression.

cc @mbautin @spolitov

**Comment by ddorian** [comment]
> We believe LZ4 is almost always better than Snappy. 

https://github.com/facebook/rocksdb/wiki/Compression
