### ISSUE TITLE
No ntp in repos on Centos 8

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#3798]
I'm trying to install YB manually on 3 Centos 8 server following Docs. But I'm facing with this error on yb-masters 

log from 192.168.10.211 yb-master.INFO :
```
W0301 20:03:04.478433 19626 consensus_peers.cc:600] Error getting permanent uuid from config peer [192.168.10.207:7100]: Network error (yb/util/net/socket.cc:538): recvmsg error: No route to host (system error 113)
I0301 20:03:14.484092 19626 consensus_peers.cc:613] Retrying to get permanent uuid for remote peer: [192.168.10.207:7100] attempt: 283
W0301 20:03:14.491116 19626 consensus_peers.cc:600] Error getting permanent uuid from config peer [192.168.10.207:7100]: Network error (yb/util/net/socket.cc:538): recvmsg error: No route to host (system error 113)
```
(other yb-masters have same error.)
Does it related to ntp missing since it replaced with chrony?

more info:
`./bin/yb-master --master_addresses 192.168.10.201:7100,192.168.10.207:7100,192.168.10.211:7100 --rpc_bind_addresses 192.168.10.211 --fs_data_dirs "/home/centos/disk1"  >& /home/centos/disk1/yb-master.out &`

**Comment by bmatican** [comment]
Hey @zeinali0 and thanks for trying out yugabyte.

Couple of quick questions, as it seems It seems the master on `192.168.10.211` cannot connect to the master on `192.168.10.207`
- Is the master on `192.168.10.207` up and running fine?
- Is your networking setup such that `192.168.10.207` accepts traffic from `192.168.10.211` on port 7100? (firewall / security group issues?)

The first time around when you start your cluster, all 3 masters need to be up and running within a small time window of each other (1 hour default). So you might see these errors on some masters until they're able to establish a connection to their peer masters.

**Comment by zeinali0** [comment]
problem fixed after opening ports on all 3 node. Thanks
