### ISSUE TITLE
Allow overriding the RPC communication port for masters/tservers in Platform

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3806]
When installing in environments where node_exporter is running on its default port of 9100, we run into conflicts when installing nodes from Yugaware since there is no way to pass in a "dynamic" host address in order to override the 9100 port specification for Tservers.

| Status | Subtask        | GitHub Issue |
| :--: | --------------- | ------------------  |
| ✅   | Update replicated nginx proxy_pass location to accept all ports |  #5360 |
| ✅   | Track communication ports at the universe level | #5353 |
| ✅   | Add ability to override communication port default values during universe creation | #5354 |
| ✅   | Add ability to turn on/off node_exporter installation for nodes | #5421 |
| ✅   | Create custom ports itest | #5375  |

**Comment by ajcaldera1** [comment]
If we could provide an override mechanism in YW to specify a different port for yb-master (7100) and yb-tserver (9100) this would help.

**Comment by daniel-yb** [comment]
**Sub Tasks**

- #5353
