### ISSUE TITLE
Query to drop sstables older than x timestamp

### ISSUE THREAD

**Issue by ddorian** [YugaByte/yugabyte-db#381]
Suppose you're keeping counters (ex: likes on articles).

And you also want to index these counters on an external db, like elasticsearch.

1 way would be to insert an `update` row on each `increment` in another table on the same `tablet`.
Then a process would exclusively read from this tablet and update the outside-index.
But deleting each row (like in normal message queue) is slow cause of overhead.
So 1 way would be to keep state (in yet another table) of where the cursor currently is.
And doing "delete sstable WHERE timestamp<x" which will just `rm` old files (no delete by insert).
The `delete` statement would go the tablet-follower and do the same thing there. The data may be inconsistent though, since I don't think they `commit sstables` together, but since we use a `cursor` we can skip rows.

Makes sense ?

**Comment by kmuthukk** [comment]
@ddorian -

When you say this:
```
DELETE sstable WHERE timestamp < x;
```

Do you actually mean something like:
```
DELETE FROM <user_table> WHERE writetime(column) < ?;
```

And seems like you want that to be efficient without having to go through writing delete markers for each matching row. 

But more importantly, not fully clear on the use case.  Can you please elaborate a bit more on the use case itself? And based on that, we can talk about possible alternatives (such as if a table level TTL would be enough to expire old data).

**Comment by ddorian** [comment]
The usecase is to update external index (like elasticsearch). The nicest way (from developer perspective) is to have a **transactional queue**, so you can `(increment like on article + insert queue msg to update article in elasticsearch)`in a transaction. 
Yes I meant something like your query with `writetime`. Assuming each sstable keeps a min/max of it.

There are basically (as far as I know) 2 types of queues:
1. Is the rabbitmq way, where multiple clients can read from a partition but you have to delete/ack each message.
2. The kafka way, where you have 1 client reading on each partition, but you can just drop old logs instead of ack/deleting each message and just keep a cursor. 

2 is supposed to be more efficient (sequential reading with small cursor updates, deleting by just dropping old sstables). 

Yes it can be made with TTL, but If `queue-processing-app` is down for TTL time, rows will expire, and then I have to reindex all the table cause I don't know what missed.

**Comment by kmuthukk** [comment]
I think what you might be looking for is a "change data capture" like feature that lets you be a consumer of all changes happening to the table. When you enable CDC on a table, you don't need to "write" to an additional queue- because the DB txn log (in YugaByte case, the Raft log, or some extension which optionally also keeps the "before" image of the change, not just the "after" image) can serve as the queue from which you can consume. This capability can be used to enable a variety of capabilities (such as timeline consistent secondary indexes, updating an external service - such as, in your case, a search index in Elastic, and so on).

**Comment by ddorian** [comment]
Yes mine looks like a poor man CDC. But should be much easier to develop compared to CDC.
And CDC is usually slapped to an enterprise version so..

**Comment by kmuthukk** [comment]
:)

The challenge with the:

```
DELETE FROM <user_table> WHERE writetime(column) < ?;
```
even with min/max writetime hints (which we do keep for columns), is that the implementation is not always as simple as dropping SSTable files which have older content. In the case where an SSTable file contains some values before the timestamp and some after, a strict implementation of the statement will still need to have some other way of suppressing only portion of the records in the SSTable and not all of it. On the other hand, if your thought is to treat the above statement as a hint or "do your best effort" - then that seems hacky; at that point a "conservative TTL" based scheme would probably be better.

**Comment by ddorian** [comment]
Yes I meant in `best effort` manner. 
Problem with high TTL may be disk storage, if TTL is too high.
Closing as `won't fix`.
