### ISSUE TITLE
Multi node C# driver don't work on 1 node failure

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#3824]
i'm  trying 3 node cluster with replication factor 3 in C#
i'm creating a singelton ISession like this : 
```
endpoints = "192.168.10.201,192.168.1.207,192.168.1.211";
ISession session = Cluster.Builder()
                .WithReconnectionPolicy(new ConstantReconnectionPolicy(1000))
                .AddContactPoints(endpoints.Split(","))
                .WithPoolingOptions(PoolingOptions.Create(ProtocolVersion.V3)
                        .SetHeartBeatInterval(1000).SetCoreConnectionsPerHost(HostDistance.Remote, 1))
                .WithTypeSerializers(typeSerializerDefinition)
                .Build()
                .Connect();
```

it work fine but when first node(192.168.10.201) fail i start facing with this error :
```
Cassandra.NoHostAvailableException: All hosts tried for query failed (tried 192.168.10.211:9042: OperationTimedOutException 'The host 192.168.10.211:9042 did not reply before timeout 12000ms'; 192.168.10.207:9042: OperationTimedOutException 'The host 192.168.10.207:9042 did not reply before timeout 12000ms')
   at Cassandra.Requests.PrepareHandler.GetNextConnection(IInternalSession session, Dictionary`2 triedHosts)
```
While i can connect and query both alive node with VS Code Cassandra Workbench.

**Comment by ddorian** [comment]
Were you running a DML query ? Did you retry after trying Cassandra Workbench ?

**Comment by zeinali0** [comment]
Yes i retry after Cassandra Workbench but i didn't restart application. i'm running DML queries on a reqeust Handler service something like Asp.net Controllers.
i'm using a single ISession between different threads which they are handling client requests.

**Comment by ddorian** [comment]
@zeinali0 can you contact me on our slack so we can debug this ?

**Comment by ddorian** [comment]
closed because no response from user
@zeinali0 please reopen if issue still persists
