### ISSUE TITLE
how to run CQL java tests?

### ISSUE THREAD

**Issue by ananyaks** [YugaByte/yugabyte-db#383]
Hi @kmuthukk, @ttyusupov, Running `./yb_build.sh release --scb --sj --java-tests` did not run any tests and the displayed output was [all-java-test.log](https://github.com/YugaByte/yugabyte-db/files/2195428/all-java-test.log) with no new files created in  `yugabyte-db/java/yb-client/target/surefire-reports `.

Running  ` ./yb_build.sh --scb --sj --java-test org.yb.client.TestYBClient` did run the tests and the displayed output was [client-all-test.log](https://github.com/YugaByte/yugabyte-db/files/2195431/client-all-test.log) and new files were created in `yugabyte-db/java/yb-client/target/surefire-reports` and the files were [client-all-surefire-reports.log](https://github.com/YugaByte/yugabyte-db/files/2195432/client-all-surefire-reports.log). There is one error at the end of _client-all-test.log_ that is due to `TimeOutException`.

I experimented on running CQL tests in `yugabyte-db/java/yb-cql/src/test/java/org/yb/cql` with following commands but they all failed

 `./yb_build.sh --scb --sj --java-test org.yb.cql.TestYBcql `

 `./yb_build.sh --scb --sj --java-test org.yb.cql.TestYBCQL `

 `./yb_build.sh --scb --sj --java-test org.yb.cql.Testybcql `

I finally ran 

 `./yb_build.sh --scb --sj --java-test org.yb.cql.BaseCQLTest ` and got the following output 
[BaseCQLTest.log](https://github.com/YugaByte/yugabyte-db/files/2195433/BaseCQLTest.log). It did not seem to have run any tests. 

How do I run cql tests? Thanks!

**Comment by kmuthukk** [comment]
cc: @robertpang or @rven1 : can you help on this issue?

**Comment by robertpang** [comment]
@ananyaks `BaseCQLTest` is the base class for YugaByte DB's CQL Java tests. which contains the setup and other utility methods for the tests but is not intended to be executed as a test. Per our convention, YugaByte DB's CQL Java tests are named with prefix "Test...". Here are our CQL tests:

```
 $ ls java/yb-cql/src/test/java/org/yb/cql/Test*
java/yb-cql/src/test/java/org/yb/cql/TestAlterTable.java
java/yb-cql/src/test/java/org/yb/cql/TestArith.java
java/yb-cql/src/test/java/org/yb/cql/TestAuthentication.java
java/yb-cql/src/test/java/org/yb/cql/TestBasicStatements.java
...
java/yb-cql/src/test/java/org/yb/cql/TestUsingTimestamp.java
java/yb-cql/src/test/java/org/yb/cql/TestVarIntDataType.java
java/yb-cql/src/test/java/org/yb/cql/TestWipeNode.java
```

You may run them individually like

`./yb_build.sh release --scb --sj --java-test org.yb.cql.TestBasicStatements`

There seems to an issue in our build script for run all Java tests when `--sj` (skip Java build) is also specified and we will look into it. To run all Java tests, please try without `--sj` instead.

`./yb_build.sh debug --scb --java-tests`

**Comment by ananyaks** [comment]
Thanks @robertpang, I successfully ran 
`./yb_build.sh release --scb --sj --java-test org.yb.cql.TestBasicStatements` 
and it resulted in: 

`[INFO] Running org.yb.cql.TestBasicStatements`
`[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.995 s - in org.yb.cql.TestBasicStatements`
`[INFO] Results:`
`[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0`

A suggestion, how about an option that runs all of `java/yb-cql/src/test/java/org/yb/cql/Test*` instead of running them individually?

Does `./yb_build.sh debug --scb --java-tests` run all java tests including those in 
`java/yb-client/src/test/java/org/yb/client/Test*`?

Thanks!

**Comment by rven1** [comment]
@ananyaks : You can run all the Java tests from 
code/yugabyte/java directory as follows:
mvn test
You can also run individual testsuite as follows:
mvn test -Dtest=org.yb.cql.TestInsert
Individual tests can be run as follows:
mvn test -Dtest=org.yb.cql.TestInsert#testLargeInsert

**Comment by kmuthukk** [comment]
@ananyaks 

Regarding:

> A suggestion, how about an option that runs all of java/yb-cql/src/test/java/org/yb/cql/Test* instead of running them individually?

To run the Java tests that are under the java/yb-cql directory, you can do the following:
```
% cd java/yb-cql
% mvn test
```
and you should something see something like this in the output:
```
INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.yb.cql.TestBasicStatements
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.375 s - in org.yb.cql.TestBasicStatements
[INFO] Running org.yb.cql.TestInsert
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 87.133 s - in org.yb.cql.TestInsert
[INFO] Running org.yb.cql.TestSelect
...
...
and so on..
```
