### ISSUE TITLE
[YCQL] Backing up table should back up its indexes

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3836]
Backing up a table should back up its indexes.

Flow should be:
1. `yb_backup` script should accept a set of tables. These should be user tables and not indexes.
2. When master's `CreateSnapshot` API is called for creating the snapshot metadata, master should identify the indexes for the table and create a backup of the table as well as the indexes.
3. Restore of a table should restore its indexes too.

cc: @bmatican 

Open questions:
Should we allow indexes to be backed up independently of tables? What about user enforced indexes - should we allow them to be backed up / restored independently?

**Comment by bmatican** [comment]
We've had some offline conversations on this, but if we can move all of the complexity of selecting all of the cql indexes for a table, down to the master, then ideally we always use that.

So at the `yb_backup` level, we provide the main table and then the master code backups up all the indices as well (user enforced or txn, for now can just do all of them..).

This way, the snapshot PB would contain the main table + the indices, but they all refer to the main table by UUID, so then rebuilding that on restore should be fine, as it can be an expansion on the current mapping OLD>NEW mechanic we have. Would that make sense, @OlegLoginov ?

**Comment by OlegLoginov** [comment]
A few additional points from the slack conversation:
- We don't have now 'table-only' mode to ignore indexes. (If the table has indexes - they will be backed up/restored automatically).
- Table renaming (on backup-restore phase) will be disabled if the table has an index.

**Comment by OlegLoginov** [comment]
Improved tests:  https://github.com/yugabyte/yugabyte-db/commit/9efaca9daf8e0e352672ac2c6074f0d2dd1f6ac5
