### ISSUE TITLE
The function name OperationDriver::ApplyAsync is confused

### ISSUE THREAD

**Issue by lorinlee** [YugaByte/yugabyte-db#384]
When reading the source code of yugabyte-db, I find that the function name [OperationDriver::ApplyAsync](https://github.com/YugaByte/yugabyte-db/blob/e39ec3fcc56fe1db6fa30f1ac80f1981f2af09c8/src/yb/tablet/operations/operation_driver.cc#L385) is confused, and [the comments of this function](https://github.com/YugaByte/yugabyte-db/blob/e39ec3fcc56fe1db6fa30f1ac80f1981f2af09c8/src/yb/tablet/operations/operation_driver.h#L96) is outdated. It said that "ApplyAsync() submits ApplyTask() to the apply_pool_", but in fact it is not true. [This comment](https://github.com/YugaByte/yugabyte-db/blob/e39ec3fcc56fe1db6fa30f1ac80f1981f2af09c8/src/yb/tablet/operations/operation_driver.cc#L403) and the [invoking](https://github.com/YugaByte/yugabyte-db/blob/e39ec3fcc56fe1db6fa30f1ac80f1981f2af09c8/src/yb/tablet/operations/operation_driver.cc#L405) means the procedure is synchronous. Furthermore, I think the apply_pool_ in OperationDriver and even TabletPeer should be removed, because I cannot find any usage of apply_pool_ in them.

**Comment by spolitov** [comment]
Hi @lorinlee,

You are right, the comment and function name were not updated after the behaviour of this function was changed during refactoring.
Good point to address this issue during one of upcoming refactorings.
