### ISSUE TITLE
Removing --fs_data_dirs directory will cause losing data

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#3853]
I was trying YB with -rf 3 on 3 node manually and I removed `--fs_data_dirs` directory with `rm -rf "/home/centos/disk1"` while yb-master (it was leader) and yb-tserver was running.
Unexpectedly both other 2 node wasn't able to work anymore while yb-master was running on both of them.
And even after re running yb-master and yb-tserver on first node all nodes was showing 0 tablet.
How should we recover system in such this accidental remove directory or part of it?

**Comment by bmatican** [comment]
@zeinali0 That sounds unexpected. Just to clarify though:
- You have 3 different nodes
- All 3 nodes are running both `yb-master` and `yb-tserver`
- All 3 nodes were started with `--fs_data_dirs=/home/centos/disk1`
- You only executed `rm -rf /home/centos/disk1` on 1 single node? (and this was on the node that was the master leader at the time.)
- You then recreated `/home/centos/disk1` and restarted the master and tserver processes on that node. How did you verify that this node then had 0 tablets?

Can you describe what you observed when you say `both other 2 node wasn't able to work anymore` ? Were you trying to execute some requests and they were failing? Were you accessing some internal UI and it was not responding?

**Comment by zeinali0** [comment]
Yes `both other 2 node wasn't able to work anymore`. i opened yb-master UI dashboard on one of 2 other node and on Tablet Servers tab the User Tablet-Peers / Leaders column was 0/0 for both node.

**Comment by ddorian** [comment]
@zeinali0 is this issue still persisting ? if yes, can you post on slack so we can quickly debug this ?

**Comment by zeinali0** [comment]
I should check it again with V2.1.2.0

**Comment by zeinali0** [comment]
The issue didn't happen again in V2.1.2.0.
