### ISSUE TITLE
Filesystem root $0 contains illegal whitespace

### ISSUE THREAD

**Issue by likenamehaojie** [yugabyte/yugabyte-db#3858]
when i create yb-master us m  

1920 GB
I0306 07:46:25.866631 211863 mem_tracker.cc:251] MemTracker: soft memory limit is 10.686132 GB
I0306 07:46:25.868930 211863 rpc_server.cc:86] yb::server::RpcServer created at 0x27b60b0
I0306 07:46:25.868965 211863 master.cc:143] yb::master::Master created at 0x7ffeb97275e0
I0306 07:46:25.868983 211863 master.cc:144] yb::master::TSManager created at 0x27c8770
I0306 07:46:25.868988 211863 master.cc:145] yb::master::CatalogManager created at 0x2b0c000
I0306 07:46:25.869057 211863 master_main.cc:114] Initializing master server...
E0306 07:46:25.869220 211863 main_util.cc:22] IO error (yb/fs/fs_manager.cc:183): Faile contains illegal whitespacetem root /opt/yuga/like/disk2
I0306 07:46:25.869421 211863 master.cc:294] Master (stopped) did not start, shutting down all that started...

**Comment by likenamehaojie** [comment]
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/centos_cn01-opt  330G   60G  271G  18% /opt
[root@BIGDATA-CN01 like]#

**Comment by ddorian** [comment]
What version are you using ? It says your filesystem root has whitespace in it. https://github.com/yugabyte/yugabyte-db/blob/2b88fa0b2dde4d54e4e728cd7f9b05aacacc2791/src/yb/fs/fs_manager.cc#L180

Can you send the parameters that you run master with ?

**Comment by bmatican** [comment]
Hey @likenamehaojie and thanks for trying out yugabyte.

Can you share the `--fs_data_dirs` flag that you used to start up your master process with?

**Comment by bmatican** [comment]
```
$ ./build/latest/bin/yb-master --fs_data_dirs="/tmp/foo "
F0606 20:48:27.764657  5788 master_main.cc:116] IO error (yb/fs/fs_manager.cc:185): Failed to load FS layout: Filesystem root /tmp/foo  contains illegal whitespace

$ ./build/latest/bin/yb-master --fs_data_dirs=" /tmp/foo"
Invalid argument (yb/util/init.cc:106): Cannot create directory for logging, please check the --fs_data_dirs parameter (Passed:  /tmp/foo). Path does not exist:  /tmp/foo
Details: Not found (yb/util/env_posix.cc:1014): Unable to create FS path component  /tmp/foo:  /tmp/foo: No such file or directory (system error 2)
```
