### ISSUE TITLE
Add status information regarding ALIVE/DEAD and last heartbeat to list_all_tablet_servers yb-admin subcommand

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3866]
Ask from a customer:

In order to do additional automation, it would be helpful if the `yb-admin ... list_all_tablet_servers` command had node status (as reported on the `tablet_servers` page on port 7000) as well as the last heartbeat time.

**Comment by iSignal** [comment]
After 7959fde66103ab72d74b8e74ee072b0e4f45447e yb-admin list_all_tablet_servers has the following output

```
Sankeths-MacBook-Pro:yugabyte-db sanketh$ time build/latest/bin/yb-admin --timeout_ms=10000 --init_master_addrs=127.0.0.1:7100 --exclude_dead list_all_tablet_servers 2> /dev/null
Tablet Server UUID               RPC Host/Port Heartbeat delay Status   Reads/s  Writes/s Uptime   SST total size  SST uncomp size SST #files      Memory
78693941247849fda82d4218ce368046 127.0.0.3:9100 0.02s           ALIVE    0        0        6003     0 B             0 B             0               34 MB
```
f107faee78bf45b4a4ff7bee869e621c 127.0.0.2:9100 0.02s           ALIVE    0        0        6003     0 B             0 B             0               34 MB
