### ISSUE TITLE
[2DC] yb-admin setup_universe_replication should accept FQDN instead of just IP

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3878]
When currently specifying the producer master addresses in the `setup_universe_replication`, ip addresses currently need to be specified. There are siutations like k8s and customers that need to use route53 names in the specification. The command should be enhanced to do DNS resolution.

**Comment by nspiegelberg** [comment]
The existing commands already support DNS resolution (although the help text says IP).  I tested via:

`
sudo echo 127.0.0.11      localhost11 >> /etc/hosts
sudo echo 127.0.0.22      localhost22 >> /etc/hosts
dscacheutil -flushcache
./build/latest/bin/yb-admin -master_addresses localhost22:7100 setup_universe_replication test localhost11:7100 000030a9000030008000000000004008
`

**Comment by bmatican** [comment]
Closing this as it should be working cc @ajcaldera1 in case we've tested this since then
