### ISSUE TITLE
[YCQL] Timestamp corruption issue when specifying a data format with cassandra unloader...

### ISSUE THREAD

**Issue by Vlad-Koretsky-Narvar** [yugabyte/yugabyte-db#3883]
Hello!
Question for you in regards to cassandra unloader options. I have a table which has a timestamp field in it - I want to export the data with cassandra unloader and then import programmatically. There are certain timestamp literals that are supported in YB (https://docs.yugabyte.com/latest/api/ycql/type_datetime/). The default timestamp format of the unloader is not one of them, so I wanted to specify my own. What I see is the timestamp value is corrupted with a date format parameter I need - what am I doing wrong?
Here’s an example:
```
select * from transactions where transaction_id = <uuid_here>;
Original value in DB: "2019-12-11 04:50:11.661000+0000"

./cassandra-unloader \
	-schema "payments.transactions(transaction_id,payment_reference_id,source_details,user_details,app_reference,amount,iso_currency,payments_detail,created_date)" \
	-host xx.xx.xx.xx \
  -user "xxx" \
  -pw "xxx" \
	-f "./python/payments.transactions";
Produces this value: "12/10/19 8:50 PM"

./cassandra-unloader \
	-schema "payments.transactions(transaction_id,payment_reference_id,source_details,user_details,app_reference,amount,iso_currency,payments_detail,created_date)" \
	-host xx.xx.xx.xx \
  -user "xxx" \
  -pw "xxx" \
	-f "./python/payments.transactions" \
	-dateFormat "yyyy-MM-DD'T'HH:mm:ss.SSS";
Produces this value: "2019-12-344T20:50:11.661"
```

**Comment by kmuthukk** [comment]
@Vlad-Koretsky-Narvar wrote later:

```
I think the issue may be with my input. 
I believe that the day should be lower-case ‘d’, not upper-case.
yyyy-MM-dd'T'HH:mm:ss.SSS
instead of:
yyyy-MM-DD'T'HH:mm:ss.SSS
```

Waiting for his confirmation on this.

**Comment by ddorian** [comment]
@Vlad-Koretsky-Narvar @kmuthukk 

Current fix: **Use `yyyy-MM-dd HH:mm:ss.SSSXXX`** on both load/unload which also has timezone inside otherwise it uses `local timezone`.

**Comment by Vlad-Koretsky-Narvar** [comment]
Yes, @kmuthukk and @ddorian, confirmed that this is, indeed, the way to resolve it...
My bad and thank you!

**Comment by ddorian** [comment]
I'm closing as fixed then. Please reopen if further questions @Vlad-Koretsky-Narvar
