### ISSUE TITLE
Support for public ip address, dns names and private ip address

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#389]
## Overview

In modern cloud-based deployments, servers could have public IP address or DNS names that they are not aware of. A cloud provider could provide public ip address functionality via port forwarding, for example. Also clouds such as GCP and AWS has different billing strategy when traffic goes through public IP vs private IP.

## Node Address Parameters

As a part of this change, the following node name / ip address parameters will be introduced.

### RPC Bind Addresses

RPC bind addresses are the list of interfaces that the YugaByte DB server processes will accept client connections on. This value can be `0.0.0.0` in which case all interfaces will be bound to.
**Note**: Currently using only one address is recommended. In the case there are multiple bind addresses, the server may choose a random address (for example, `127.0.0.1`) as its identity which is not ideal. Support for listen addresses is required to safely use multiple addresses here.

Note that these should typically be the private IP address in the case of public clouds (communication via private IP is typically free of charge, so when nodes should use private IPs for communication when possible over public IPs).

To specify these, pass the `rpc_bind_addresses` gflag with a comma separated list of IP addresses.

### Broadcast Addresses

Broadcast addresses should be specified externally, just because a server may not know about its DNS name or public IP address. This should default to the listen address (which in turn defaults to the RPC bind address if there is exactly one of those).

To specify these, pass the `server_broadcast_addresses` gflag a comma separated list of values.

### Listen Address

This is the address the server uses as its identity, for example to identify itself to the Raft groups. This defaults to the RPC bind address if there is exactly one RPC bind address specified. This is a future task.

## Intra-cluster communication policies

There should be a way to specify the address to use for inter-server communication based on a placement location. Each node already has a placement configuration in terms of the cloud, region and zone it is located in. There should be a flag that specifies which of the above addresses (rpc/broadcast) should be used to communicate between the servers based on their placement.

To specify the policy, pass the `use_private_ip` flag with one of the following values:
* never - Default value, always use broadcast addresses
* cloud - use rpc bind address if remote node is in the same cloud, broadcast otherwise
* region - use rpc bind address if remote node is in the same cloud and region, broadcast otherwise.
* zone - use rpc bind address if remote node is in the same cloud, region and zone, broadcast otherwise.

**Comment by spolitov** [comment]
Implemented by commit e65b6ed72d1ee5a5c366df402a71cdaefae06803

**Comment by spolitov** [comment]
@rkarthik007 yes, port could be specified using ":" as usual.

**Comment by rkarthik007** [comment]
@yjiangnan - I am trying this out and will be documenting this soon, please stay tuned.

**Comment by yjiangnan** [comment]
@rkarthik007 

Do you have an example code for deploying such a system? https://docs.yugabyte.com/latest/deploy/manual-deployment/start-tservers/ This does not say anything about the new implementation. Should I run the same command line options for all the nodes? Then how does a node know from the starting command which public address points to itself? Suppose I have two home computers (behind a NAT) and one remote cloud server instance. What does the command line look like for Masters and TServers if I want all of them to be able to communicate with each other and my home computers to communicate by private addresses?

**Comment by rkarthik007** [comment]
Hi @yjiangnan - really sorry, forgot to update this thread.

This post has all the details on how to use this feature: https://blog.yugabyte.com/yugabyte-db-1-1-new-feature-public-ips-to-simplify-multi-or-hybrid-cloud-database-deployments/

Essentially you can bring up a yb master and tserver with a broadcast address and port param (actually, its a comma separated list, so you can specify multiple):
```
--server_broadcast_addresses 52.12.222.212:7100
```

Please give it a try, and let us know how it goes!
