### ISSUE TITLE
[docs] change pagination at bottom to go to next weight instead of rotating through pages of same weight

### ISSUE THREAD

**Issue by grantcarthew** [yugabyte/yugabyte-db#3895]
On this page: https://docs.yugabyte.com/latest/develop/learn/data-modeling-ycql/

On the bottom of the page on the right-hand side is a button to go to the next topic. It links to itself.

**Comment by grantcarthew** [comment]
Same issue on the data types document (next one on). It links back to the yql document.

**Comment by grantcarthew** [comment]
Same on the aggregations document. Looks like this is a common issue on the parent navigation document.

**Comment by stevebang** [comment]
@grantcarthew Thanks for letting us know about this. I took a quick look and it is a second copy of the topic (one for YSQL and one for YCQL). So, when you clicked next it went to the other version of the same content. To fix this might require disabling the previous/next links at the bottom of the page —it looks like a side-effect of the way we have multiple buttons on a “page” (which is really two pages). I’ll take a closer look with others tomorrow and see how we might resolve this without having to remove the page bottom links.

**Comment by stevebang** [comment]
@yb-andrew This issue occurs when the navigation links at the bottom of the pages (previous and next) point to topics with multiple buttons (there's one page for each button). @schoudhury says we need to "change the pagination logic to move to the next higher weight instead of rotating within the same weight".
