### ISSUE TITLE
[YCQL] Cassandra Java driver fails with Guava >= 26

### ISSUE THREAD

**Issue by lhotari** [yugabyte/yugabyte-db#3897]
The current YB Cassandra Java driver, version 3.2.0-yb-19, isn't compatible with Guava >= 26. 

Issue in upstream: https://datastax-oss.atlassian.net/browse/JAVA-1928
Fix in upstream: https://github.com/datastax/java-driver/commit/05e3ee8ad90ba213098e15f37c52020eb907c40a
It was fixed in upstream driver version [3.6.0](https://github.com/datastax/java-driver/tree/4.x/changelog#360). The newest 3.x version is currently 3.8.0 .

**Comment by rkarthik007** [comment]
Quick update - @nchandrappa is going to start looking at this, we will post updates here.

**Comment by nchandrappa** [comment]
YugabyteDB CQL java driver `3.8.0-yb-4` is GA and is now available on maven central.
