### ISSUE TITLE
cassandra-loader not routing to optimal node even when built with YB java driver

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#392]
I rebuilt [cassandra-loader](https://github.com/brianmhess/cassandra-loader), with the YB java drivers for YugaByte (YCQL) by doing the following change:

```
09:57 $ git diff build.gradle
diff --git a/build.gradle b/build.gradle
index 4813e2b..5a23ba2 100644
--- a/build.gradle
+++ b/build.gradle
@@ -30,7 +30,7 @@ repositories {
 }

 dependencies {
-    compile 'com.datastax.cassandra:cassandra-driver-core:3.2.0'
+    compile 'com.yugabyte:cassandra-driver-core:3.2.0-yb-15'
     compile 'org.xerial.snappy:snappy-java:1.0.5'
     compile 'net.jpountz.lz4:lz4:1.2.0'
     compile 'ch.qos.logback:logback-classic:1.1.3'
```

Then built a new `cassandra-loader` jar via:
```
% gradle loader
```

Then created the sample schema & tried to load the data file in the "[sample](https://github.com/brianmhess/cassandra-loader/tree/master/sample)" directory.

The table schema is:

```
create keyspace titanic;

use titanic;

CREATE TABLE survivors (
 id varchar,
 survived boolean,
 passenger_class int,
 name varchar,
 sex varchar,
 age int,
 num_siblings_spouse int,
 num_parents_children int,
 ticket_id varchar,
 fare varchar,
 cabin varchar,
 port_of_embarkation varchar,
 primary key (id));
```

And the commands I tried after starting a local "3-node" cluster:

```
% cd sample
% ../build/cassandra-loader -f titanic.csv -host 127.0.0.1 -schema "titanic.survivors(id, survived, passenger_class, name, sex, age, num_siblings_spouse, num_parents_children, ticket_id, fare, cabin, port_of_embarkation)" -boolStyle 1_0 -numFutures 50 -rate 50 -progressRate 50 
```

But the routing was not optimal as seen from the exported metrics. 

On the three node cluster, only 1/3 of the insert (write) operations ended up on the correct node, and the other 2/3 had to be forwarded. This suggests that the custom YB load-balancing/routing policy is not kicking in by default, and that all requests are going to a random node (and 1/3 happen to be the correct node).

Ideally, when all nodes are alive, the `handler_latency_yb_client_write_remote` count should be 0 and all the ops should show up under the `handler_latency_yb_client_write_local` metric.

```
10:02 $ curl -s http://127.0.0.2:12000/metrics  | grep -A1 yb_client_write
                "name": "handler_latency_yb_client_write_remote",
                "total_count": 1850,
--
                "name": "handler_latency_yb_client_write_local",
                "total_count": 893,
```

**Comment by ddorian** [comment]
Related but not really, why are you using a modified driver ? Is it just cause of the uint64/16 change on the hash? Does it need to do the same for every driver ?

**Comment by kmuthukk** [comment]
In  Apache Cassandra, all tables of a keyspace are coerced into the same partition scheme -- exactly the same number of parts (shards) and the shard boundaries for all tables are identical.  When adding a node a shard's token range across *all* the tables must be copied over to new node before it can serve that range. So overall it is a less flexible model.

With YugaByte DB, each table can be partitioned and load-balanced independently. A table's number of splits and the split boundaries etc. are independent. Each shard is replicated via RAFT and independently makes decisions of who the leader is and so on. And so to route the request optimally, we need to make enhancements to the client-driver. 

There have been other features (such as JSON support) and some extensions coming down the road, such as support for non hash partitioned (range based sharding) tables that also necessitate some driver extensions anyway.

**Comment by kmuthukk** [comment]
@m-iancu debugged the issue. His finding was:

<<=== 

Looks like cassandra-loader explicitly sets the partition policy rather than using the default: 

```
Cluster.Builder clusterBuilder = Cluster.builder()
    .addContactPoint(host)
    .withPort(port)
    //.withCompression(ProtocolOptions.Compression.LZ4)
    .withPoolingOptions(pOpts)
    .withLoadBalancingPolicy(new TokenAwarePolicy( DCAwareRoundRobinPolicy.builder().build()))
;
```

I'll update this and test it out soon. Removing the 
```
 .withLoadBalancingPolicy(new TokenAwarePolicy( DCAwareRoundRobinPolicy.builder().build()))
```

and defaulting to YB driver's default policy should make the routing optimal for `cassandra-loader`.

===>>

We'll make a new version of the `cassandra-loader` available with this change.

**Comment by m-iancu** [comment]
Forked in https://github.com/YugaByte/cassandra-loader. 

The current release (with YugaByte-compatible routing) is available at https://github.com/YugaByte/cassandra-loader/releases/download/v0.0.27-yb-1/cassandra-loader.
See also https://github.com/YugaByte/cassandra-loader#getting-it which should always contain the latest version of release and documentation.

Note: The relevant commit is: YugaByte/cassandra-loader@43982af71851d3e79cd65ca3a93d875b7a4e8c32

**Comment by ddorian** [comment]
@kmuthukk Maybe you need a doc page that explains what needs to be done on a client to make it work efficiently with the db ? Like minimum changing the token aware load balancing policy, follower reads etc.
 
And listing clients that are already patched ? Example there's no mentions here: https://docs.yugabyte.com/latest/develop/client-drivers/python/

**Comment by kmuthukk** [comment]
@ddorian : 

Currently, only the Java driver has this enhancement for load balancing policy. We have started work on the C++ driver as well.

But agreed that we should update the document to cover this clearly.
