### ISSUE TITLE
[YSQL] Outbound response streams data slowly

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3926]
While inserting YSQL data using large batches, I noticed that tserver processes the write request fairly quickly but sending the response back from tserver to YSQL layer ends up taking a long time. I increased the single RPC call timeout to 30 seconds and a lot of times for large batches, we hit the 30 second limit while sending the response back even though tserver finished processing in 3-4 seconds.

After adding more logging, the bottleneck seems to be in tcp_stream, see these log messages:
```
I0311 10:27:48.126539 111255552 rpc_with_call_id.cc:83] QueueResponse for Call yb.tserver.TabletServerService.Write 127.0.0.1:56919 => 127.0.0.1:9100 (request call id 310)
I0311 10:27:48.128559 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 261676 . Status OK, sending_.size(): 1
I0311 10:27:48.129112 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 850304 . Status OK, sending_.size(): 1
I0311 10:27:48.129420 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 70788 . Status OK, sending_.size(): 1
I0311 10:27:48.129712 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 128 . Status OK, sending_.size(): 1
I0311 10:27:48.129993 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 128 . Status OK, sending_.size(): 1
I0311 10:27:48.130234 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 128 . Status OK, sending_.size(): 1
I0311 10:27:48.130437 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 128 . Status OK, sending_.size(): 1
I0311 10:27:48.130620 73158656 tcp_stream.cc:208] Queued writes 1982072 bytes. written 128 . Status OK, sending_.size(): 1
```

The setup used in the example is:
`yb-ctl create --tserver_flags ysql_session_max_batch_size=1000000,retryable_rpc_single_call_timeout_ms=5000`
(I've purposely changed ysql batch size limit to test large batches).

```
CREATE TABLE test(a int primary key);
INSERT INTO test SELECT generate_series(1,200000);
```
This will generate ~100K writes on each of the two tablets. Because of the way our write response is structured, this generates 1MB response (for example, we have 100K OK status, one for each row that was written). Writing this data ends up taking a couple of seconds but sending 1MB response back is slow due to 128 bytes being sent at a time.

**Comment by kmuthukk** [comment]
@ndeodhar -- just to be sure, are these numbers with "release" build or "debug" builds?

**Comment by ndeodhar** [comment]
With release build.

**Comment by bmatican** [comment]
@ndeodhar Quick follow up:
- is this rf1 or rf3? I'm assuming rf1, since you mentioned 2 tablets only.
- mac or centos? I assume on your mac...

I'm trying rf1 on my centos devserver with no extra TS flags and the query completes just fine in 5-6 seconds.

**Comment by ndeodhar** [comment]
This was on RF=1 on my dev-server. You need the extra TS flags that I gave above, otherwise postgres throttles the behavior. The motivation here to not remove the unnecessary throttling from postgres and check ingestion speed on docDB.

Here's what I did for setup:
rf=1, on centos dev-server.
Start cluster using `yb-ctl create --tserver_flags ysql_session_max_batch_size=1000000,retryable_rpc_single_call_timeout_ms=5000`

I added some logging to the code:
```
diff --git a/src/yb/rpc/rpc_with_call_id.cc b/src/yb/rpc/rpc_with_call_id.cc
index 58ade71..e7628bd 100644
--- a/src/yb/rpc/rpc_with_call_id.cc
+++ b/src/yb/rpc/rpc_with_call_id.cc
@@ -80,6 +80,7 @@ void ConnectionContextWithCallId::CallProcessed(InboundCall* call) {
 
 void ConnectionContextWithCallId::QueueResponse(const ConnectionPtr& conn,
                                                 InboundCallPtr call) {
+  LOG(INFO) << "QueueResponse for " << call->ToString();
   conn->QueueOutboundData(std::move(call));
 }
 
diff --git a/src/yb/rpc/tcp_stream.cc b/src/yb/rpc/tcp_stream.cc
index b76bc3c..393414b 100644
--- a/src/yb/rpc/tcp_stream.cc
+++ b/src/yb/rpc/tcp_stream.cc
@@ -203,7 +203,7 @@ Status TcpStream::DoWrite() {
     auto status = fill_result.len != 0
         ? socket_.Writev(iov, fill_result.len, &written)
         : Status::OK();
-    DVLOG_WITH_PREFIX(4) << "Queued writes " << queued_bytes_to_send_ << " bytes. written "
+    LOG_WITH_PREFIX(INFO) << "Queued writes " << queued_bytes_to_send_ << " bytes. written "
                          << written << " . Status " << status << ", sending_.size(): "
                          << sending_.size();
 
diff --git a/src/yb/tserver/tablet_service.cc b/src/yb/tserver/tablet_service.cc
index 4fc445d..c510448 100644
--- a/src/yb/tserver/tablet_service.cc
+++ b/src/yb/tserver/tablet_service.cc
@@ -1179,6 +1179,7 @@ void TabletServiceImpl::Write(const WriteRequestPB* req,
   TRACE_EVENT1("tserver", "TabletServiceImpl::Write",
                "tablet_id", req->tablet_id());
   DVLOG(3) << "Received Write RPC: " << req->DebugString();
+  LOG(INFO) << "Started TabletServiceImpl::Write for tablet " << req->tablet_id();
   UpdateClock(*req, server_->Clock());
 
   auto tablet = LookupLeaderTabletOrRespond(
@@ -1273,6 +1274,7 @@ void TabletServiceImpl::Write(const WriteRequestPB* req,
 
   tablet.peer->WriteAsync(
       std::move(operation_state), tablet.leader_term, context_ptr->GetClientDeadline());
+  LOG(INFO) << "Ended TabletServiceImpl::Write for tablet " << req->tablet_id();
 }
```

After starting cluster, I did:
```
create table test(a int primary key);
insert into test select generate_series(1,200000);
```
This will result in 100K writes on each tablet. The data size being written is small (just 1 int per row).

Now, notice these logs:
```
I0314 01:29:52.436025  4999 tablet_service.cc:1182] Started TabletServiceImpl::Write for tablet bea85470b12a4cd7a88489932f062ce9

I0314 01:29:53.859019  4999 tablet_service.cc:1277] Ended TabletServiceImpl::Write for tablet bea85470b12a4cd7a88489932f062ce9

I0314 01:29:54.708791  5494 rpc_with_call_id.cc:83] QueueResponse for Call yb.tserver.TabletServerService.Write 127.0.0.1:54822 => 127.0.0.1:9100 (request call id 624)
```
See that we finished doing the write in about 1.5 second. Then the response got queued 1 second later (what is causing the delay here?)

And now, here's some logs on what happens after that:
```
I0314 01:29:54.708807  4880 tcp_stream.cc:206] { local: 127.0.0.1:9100 remote: 127.0.0.1:54822 }: Queued writes 985432 bytes. written 128 . Status OK, sending_.size(): 1
I0314 01:29:54.708952  4880 tcp_stream.cc:206] { local: 127.0.0.1:9100 remote: 127.0.0.1:54822 }: Queued writes 985432 bytes. written 128 . Status OK, sending_.size(): 1
I0314 01:29:54.709111  4880 tcp_stream.cc:206] { local: 127.0.0.1:9100 remote: 127.0.0.1:54822 }: Queued writes 985432 bytes. written 128 . Status OK, sending_.size(): 1
I0314 01:29:54.709254  4880 tcp_stream.cc:206] { local: 127.0.0.1:9100 remote: 127.0.0.1:54822 }: Queued writes 985432 bytes. written 128 . Status OK, sending_.size(): 1
I0314 01:29:54.709393  4880 tcp_stream.cc:206] { local: 127.0.0.1:9100 remote: 127.0.0.1:54822 }: Queued writes 985432 bytes. written 128 . Status OK, sending_.size(): 1
I0314 01:29:54.709554  4880 tcp_stream.cc:206] { local: 127.0.0.1:9100 remote: 127.0.0.1:54822 }: Queued writes 985432 bytes. written 128 . Status OK, sending_.size(): 1
```

And that continues for a couple of seconds. What's causing the writes to be sent 128 bytes at a time? There's nothing else running on the system and this INSERT statement is the only query that I executed.

**Comment by ndeodhar** [comment]
Also, just as another data point, writing 200K rows should not take 5-6 seconds on RF=1.
As a comparison, postgres can write 1M rows in 3 seconds, whereas we take 16 seconds to write 1M rows.
This particular comparison was done on 2.1 release (without any of the local logging changes) and no extra tserver gflags.

**Comment by bmatican** [comment]
Asked @rajukumaryb to look into this, at least on the part of why, after the TS wraps up the work (1.5s), it still takes many seconds until YSQL gets back all the responses.
