### ISSUE TITLE
[yugabyte-client] changes to yugabyte-client tar.gzs

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#3928]
we recently started generating yugabyte client packages  - ysqlsh, cqlsh and redis-cli
```
https://downloads.yugabyte.com/yugabyte-client-2.1.1.0-linux.tar.gz
https://downloads.yugabyte.com/yugabyte-client-2.1.1.0-darwin.tar.gz
```
propose the following changes to the above packages:
1. tar.gz name should be `yugabyte-client-2.1-<os>.tar.gz` which will signify a single client package for all minor releases across a single major release.
2. after untar the directory name should be `yugabyte-client-2.1`. currently it has the same name as the server package `yugabyte-2.1.1.0`
3. change cqlsh in the bin directory to `ycqlsh` (tracked as per https://github.com/yugabyte/yugabyte-db/issues/3935)
4. remove `psql` as we intend to communicate to users only using `ysqlsh`

**Comment by iSignal** [comment]
https://downloads.yugabyte.com/yugabyte-client-2.1-linux.tar.gz
https://downloads.yugabyte.com/yugabyte-client-2.1-dawin.tar.gz
https://downloads.yugabyte.com/get_clients.sh now uses these packages.

psql is not in this package

The cqlsh -> ycqlsh change is more complicated, I have started working on it. Let's track that in the other task separately.

**Comment by rkarthik007** [comment]
Super progress!

**Comment by iSignal** [comment]
Closing this for now, all these items should be done. We need to remove cqlsh completely at some point but that's for a later point.
