### ISSUE TITLE
Crash when creating tables

### ISSUE THREAD

**Issue by z0mb1ek** [yugabyte/yugabyte-db#3934]
Hi. Starting creating tables from https://pastebin.com/N5JZfx7W (https://github.com/yugabyte/yugabyte-db/issues/3583) and get a crash. Use 2.1.2 release. In 2.1.1 there is no such crash

**Comment by ddorian** [comment]
hmm, for me it worked. 
Did you do `./bin/post_install.sh` ?
On which table/index does it crash ?

**Comment by kmuthukk** [comment]
hi @z0mb1ek --

Thx for reporting.

When you say "crash" -- is there a user error that you are getting back, or is it an abruptly terminated connection. If it is the latter, is there a *.FATAL file or core file that we can attached gdb to. If the latter, and you need some pointers in locating the relevant FATAL log or core files, @ddorian can perhaps work with you to further investigate the issue.

**Comment by z0mb1ek** [comment]
It seems like my network fail when running scripts, sorry
