### ISSUE TITLE
[yugabyte-client] rename cqlsh to ycqlsh 

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#3935]
we should rename cqlsh to ycqlsh similar to how we have done for ysqlsh.

**Comment by iSignal** [comment]
Here is the path this will take:

* Next build: We will have both cqlsh and ycqlsh in the release package
* Docs: We update docs to reference ycqlsh after that release
* Some build in the future: Remove cqlsh from the release package completely (this will take a while because we also use it quite extensively ourselves in our tests and repos)

**Comment by schoudhury** [comment]
@iSignal why not symlink cqlsh to ycqlsh rightaway instead of keeping the old cqlsh binary in the release package?

**Comment by iSignal** [comment]
Verified that the latest release package 2.1.6.0 has the following in the release package:

`bin/cqlsh`
`bin/ycqlsh`
which are bash scripts that load

`bin/ycqlsh.py`
@stevebang : let me know if you need anything from me for the docs updates or discover any issues.

**Comment by stevebang** [comment]
@iSignal A couple of questions:

1. Should "Download cqlsh" change to "Download ycqlsh"?
2.  Should the package download name change from `cqlsh-?` to `ycqlsh-*`?

**Comment by stevebang** [comment]
When using `ycqlsh -help`, it looks like help for Cassandra's CQL.  Is anything in this help supposed to change?

- CQL
- $CQLSH_HOST
- $CQLSH_PORT

So, should these be changed to YCQL, $YCQLSH_HOST, and $YCQLSH_PORT? 
Or should it be doc'ed as is?

**Comment by stevebang** [comment]
Noticed that the display when a cluster is created show `YCQL Shell  | : cqlsh`.  Is that changing?

```
➜  bin ./yb-ctl create
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : ysqlsh                                                                     |
| YCQL Shell          : cqlsh                                                                      |
| YEDIS Shell         : redis-cli                                                                  |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /Users/stevebang/yugabyte-data                                             |
----------------------------------------------------------------------------------------------------
```

**Comment by iSignal** [comment]
Yeah, the yb-ctl message isn't fixed, good catch! There are many references to cqlsh still in the code but I can take a shot at the user facing commands like yb-ctl and yugabyted.

For the environment variables, I didn't rename them in case they are already set up that way either for a prod use case or our own tests. The ideal route would be to read from both CQLSH_PORT and YCQLSH_PORT and use them in some priority order but that seems like too much complexity for the goal here.

https://github.com/yugabyte/cqlsh/commit/6374f27d6793b13a3e1551b4a7426b7e7849e7c5 has the string changes I actually made.

**Comment by stevebang** [comment]
Thanks, @iSignal — I'll take a look at the commit. 

Are any of our `kubectl` commands affected, like this one?

```
$ kubectl run cqlsh-shell -it --rm  --image yugabytedb/yugabyte-client --command -- cqlsh yb-tservers.yb-demo.svc.cluster.local 9042
ycqlsh> CREATE KEYSPACE demo;
ycqlsh> use demo;
ycqlsh:demo> CREATE TABLE t_demo(id INT PRIMARY KEY);
```

**Comment by iSignal** [comment]
Yeah, so both cqlsh and ycqlsh should be available in recent packages and the latest docs should advertise ycqlsh whenever possible.

I also checked in https://github.com/yugabyte/yugabyte-db/commit/642456d312186971d8349e210df8c0e304e1e2ad which will fix yb-ctl and other references to cqlsh in the next release.

**Comment by stevebang** [comment]
Thanks, @iSignal. I made all of the changes, including the ones for the status displays (it won't hurt if those minor changes are early. Just waiting for approval.  I tested the changes locally and reviewed every line of change in the PR myself.
