### ISSUE TITLE
[Tools] Add a script to bump version for helm, cloudformation, terraform etc 

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#3936]
We have quite a few ways to bring up Yugabyte, we need to update our internal script to bump the version on all these repos and cut a new release if needed. Some of the integrations include
- Rook Operator
- Yugabyte operator
- Helm chart
- Cloudformation
- Terraform
- Cloud deployment manager etc.

**Comment by iSignal** [comment]
WIP for helm and brew:
helm: https://github.com/yugabyte/charts/pull/63
brew: https://github.com/yugabyte/homebrew-yugabytedb/pull/13

@bhavin192 is also working on this process for the terraform repos and for the yugabyte-operator right now.

Other repos to look at: Cloudformation, rook operator, cloud deployment manager

@ramkumarvs : We would also need to update https://charts.yugabyte.com

@stevebang : We may also need to potentially update a Hugo variable that would be used on various docs pages to refer to the latest release.

**Comment by iSignal** [comment]
Helm charts repo
https://github.com/yugabyte/charts/commit/ed15fb7df73c9205bc48c4b36b567805e9e5e920

3 terraform repos

https://github.com/yugabyte/terraform-gcp-yugabyte/commit/6a8af4f2d4a0c4fc696eabc4ee9df0eff8ac30e2
https://github.com/yugabyte/terraform-aws-yugabyte/commit/2dfb41b69f7ad76d6f03197705fcf49e1081a71e
https://github.com/yugabyte/terraform-azure-yugabyte/commit/7f18e2ccaa8c95d81f8a2e323bb2b452896d1262

https://github.com/yugabyte/gcp-deployment-manager/commit/3f2c0c59a10ee3dec89990a509946b224524f805
https://github.com/yugabyte/aws-cloudformation/commit/d25ba41899ae8e27c1abf9e257b121299339b334
https://github.com/yugabyte/azure-resource-manager/commit/0b25beb6b8e40ef97dda4eebee6fe494f3030e46

brew yugabyte repo
https://github.com/yugabyte/homebrew-yugabytedb/commit/28c1f2c7d4e6315ba834a3eba9f64ca22035e2c6

@stevebang @rao-vasireddy : please note that the automatic update mechanism is now also available on all these repos.
