### ISSUE TITLE
[YSQL] Using Amazon DMS(Data Migration Service) to replicate RDS to YBDB gives error

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#3941]
Jira Link: [DB-2436](https://yugabyte.atlassian.net/browse/DB-2436)
A user tried to setup a replication from their RDS (postgres db) to YBDB and he saw this error when trying to do the replication.

Error_State: During startup error state is set to '1' and expiration time is already set. (odbc_endpoint_imp.c:5671)

**Comment by sushantrmishra** [comment]
@ramkumarvs Can you please share more information how did you try to replicate from RDS PostgreSQL to YugabyteDB ? 

We have launched [YugabyteDB Voyager](https://docs.yugabyte.com/preview/migrate/ )  which can be used to migrate from PostgreSQL installation to the YugabyteDB .

Please reopen this issue if you are still seeing the issues ?
