### ISSUE TITLE
[YSQL] Support renaming constraints in ALTER TABLE

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3943]
Jira Link: [DB-1574](https://yugabyte.atlassian.net/browse/DB-1574)
Add support for ALTER TABLE name RENAME CONSTRAINT

**Comment by hiepd** [comment]
@ndeodhar Would like to look at this issue if it's still open. From the master issue, it seems that this is done. Thanks!

**Comment by ndeodhar** [comment]
Hi @hiepd , thanks for your interest in contributing! This is still available (there was a mistake in the master issue, corrected it now). Please assign this to yourself if you plan to pick this up.

Would be great if you can enable these two flavors:
`ALTER TABLE tablename RENAME CONSTRAINT oldname TO newname`
`ALTER TABLE IF EXISTS tablename RENAME CONSTRAINT oldname TO newname`

**Comment by devabhishekpal** [comment]
Hey... I wanted to work on this issue if I could be pointed to which file I need to start digging into

**Comment by lukaseder** [comment]
Note that when trying to run this statement, this issue isn't referenced yet as for other not yet supported syntax. Instead, the error message suggests creating a new issue:

```
SQL Error [0A000]: ERROR: ALTER TABLE RENAME CONSTRAINT not supported yet
  Hint: Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
  Position: 1
```
