### ISSUE TITLE
Yugabyte Installation in GCE

### ISSUE THREAD

**Issue by sakthi87** [yugabyte/yugabyte-db#3950]
Hi Team,

We are trying to explore Yugabyte for our RDBMS use case which have similar features like cassandra  in-terms of scalability & replication. We just started with one node cluster with replication factor of 1.

I have installed Yugabyte in Google Compute Engine to start with. Followed the below steps for manual deployment,
https://docs.yugabyte.com/v1.3/deploy/manual-deployment/

YB-Master:
./bin/yb-master --master_addresses Private IP address:7100 --rpc_bind_addresses Private IP address --webserver_interface Private IP address --fs_data_dirs "/root/yugabyte-data/node-1/disk-1"  --placement_cloud=gcp --placement_region us-central1 --placement_zone us-central1-b --webserver_doc_root /opt/Yugabytev2.1/yugabyte-2.1.0.0/www --replication_factor=1 --yb_num_shards_per_tserver 2 --ysql_num_shards_per_tserver=2 --enable_ysql=true

YB-TServer:
./bin/yb-tserver --tserver_master_addrs Private IP address:7100 --rpc_bind_addresses Private IP address --webserver_interface Private IP address --fs_data_dirs /root/yugabyte-data/node-1/disk-1 --webserver_doc_root /opt/Yugabytev2.1/yugabyte-2.1.0.0/www --yb_num_shards_per_tserver 2 --redis_proxy_bind_address Private IP address:6379 --cql_proxy_bind_address Private IP address:9042 --local_ip_for_outbound_sockets Private IP address --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --enable_ysql=true --pgsql_proxy_bind_address <Private IP address>:5433

**Issue 1:**
cat yb-master.INFO -- Towards end of the Log, below error occurs,

I0312 06:15:11.916522 29930 reactor.cc:450] Master_R000: Timing out connection Connection (0x00000000019d7d50) server Private IP address:46125 => Private IP address:7100 - it has been idle for 65.0003s (delta: 65.0003, current time: 604077, last activity time: 604012)
I0312 06:15:21.917161 29931 reactor.cc:450] Master_R001: Timing out connection Connection (0x0000000002606c70) server Private IP address:39871 => Private IP address:7100 - it has been idle for 65.0003s (delta: 65.0003, current time: 604087, last activity time: 604022)

cat yb-tserver.INFO -- Towards end of the Log, below error occurs,

I0312 06:15:25.541637 30004 reactor.cc:450] TabletServer_R000: Timing out connection Connection (0x00000000011179f0) server Private IP address:53863 => Private IP address:9100 - it has been idle for 65.0003s (delta: 65.0003, current time: 604091, last activity time: 604026)
I0312 06:15:25.542471 30005 reactor.cc:450] TabletServer_R001: Timing out connection Connection (0x0000000001117b10) server Private IP address:47789 => Private IP address:9100 - it has been idle for 65.0013s (delta: 65.0013, current time: 604091, last activity time: 604026)

**Issue 2**
After the installation, I am not able to connect to yb-master admin web server and yb-tserver admin web server.

In the browser I have provided below addresses,

http://Private IP address:7000/
http://Private IP address:9000/

Inside the node, if I try with CURL above addresses it is displaying content. When I try it from my mac it is not able to connect.

Question:
What is advantages of having multiple YSQL, YCQL and Yedis?

**Comment by kmuthukk** [comment]
Hi @sakthi87 

1. Probably best to use the latest version of the docs. [Not saying that's the issue you are running into though.]

https://docs.yugabyte.com/latest/deploy/manual-deployment/
instead of:
https://docs.yugabyte.com/v1.3/deploy/manual-deployment/

2. The messages with prefix I in the log lines are INFO level logs, and not necessarily issues. So that's not an issue to worry about. However, we should probably avoid logging it if you think it is cause a very high volume of log spew. Log lines with start with E (ERROR) or F(FATAL)  are typically the ones to be more concerned about.

3. The fact that curl to http://ip:7000/ works seems to suggest the cluster has started up fine. Are you trying the curl request from the machine itself or from your Mac? Have you made sure that you can ping the ip from your Mac, and can you say "telnet ip 7000" from your Mac?

**Comment by sakthi87** [comment]
Hi Kannan,

Thanks for the quick response!! Sorry we are using the latest version yugabyte-2.1.0.0-linux.tar.gz. Mistakenly copy pasted the older link for reference. 

2. I thought these lines are related to some issues. Ok we will check for prefix with I for INFO and dont worry about it going forward.

3. I did the curl from the machine itself which was working fine. When I tried to perform telnet from the other machines within GCP - telnet Private IP Address:7000, its getting connected.
Just now I tried in my mac and its timeout. 
nc -vz Private IP address 7000
nc: connectx to Private IP Address port 7000 (tcp) failed: Operation timed out

**Comment by kmuthukk** [comment]
hi @sakthi87 --

You are welcome. So, to confirm -- does this indeed look like a connectivity issue between your mac and GCP node?

**Comment by ddorian** [comment]
@sakthi87 any update on the question above ?

**Comment by ddorian** [comment]
I'm closing the issue as inactive.
@sakthi87 please reopen if the issue still persists.
