### ISSUE TITLE
[docs] Docker-compose example in docs exposes unnecessary ports

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#3959]
Feedback from @desmap on #3951 

> The docker-compose.yml in your docs in wrong/strange/whatever because you expose ports which is not necessary; if people want to connect external clients to their db they open ports themselves (AND before they'll set a custom password)

We open the following ports to make the client examples in the docs work:
* 7000: master web ui
* 9000: tserver web ui
* 5433: tserver SQL port
* 9042: tserver CQL port
* 6379: tserver yedis (redis) port

The example here is not meant to be directly deployed on a prod service and is mostly targeted to developers who wish to quickly try out yugabyte on their laptops/workstations. 

@desmap : Given this context, 
1. which specific ports are you concerned about? 
2. Could you point me to other examples of locked down docker compose files which can be easily "opened up"?

cc: @schoudhury @stevebang

**Comment by polarweasel** [comment]
@iSignal has this been addressed? Wondering if we can close this one.

**Comment by iSignal** [comment]
@polarweasel : will close as we didn't get more specific feedback.
