### ISSUE TITLE
How should "--x_num_shards_per_tserver" match between masters and tservers?

### ISSUE THREAD

**Issue by aegershman** [yugabyte/yugabyte-db#3969]
https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#cluster-options

> Important
> 
> This value must match on all yb-master and yb-tserver configurations of a YugabyteDB cluster.

Does this mean that the values for `--yb_num_shards_per_tserver` and `--ysql_num_shards_per_tserver` must match across all the `master` nodes, and must match across all the `tserver` nodes, but they should be separate values? Or that the value must match across ALL nodes in the universe?

For example, could `--ysql_num_shards_per_tserver` be `4` on _all_ the masters, but be `8` on _all_ the tservers, or does it need to be `4` (or `8`) across all the masters AND tservers?

The reason I ask is because I was planning on running the `master` nodes on smaller VMs (2 cpus) separate from the tservers VMs (larger, 8+ cpus), so would I need to configure _all_ the master nodes and tserver nodes to have `--yb_num_shards_per_tserver=4` and `--ysql_num_shards_per_tserver=4` (to match lowest common denominator)?

Please let me know if this doesn't make sense or if I can clarify in any way. Thanks!

**Comment by ddorian** [comment]
> Or that the value must match across ALL nodes in the universe?

Yes. They must be the same on all yb-tserver and yb-master.

> running the master nodes on smaller VMs (2 cpus)

Note that the values don't affect yb-master.

You just size tablets for yb-tservers (8 in your case) and put them also on master-config.

**Comment by aegershman** [comment]
Gotcha, so the settings should be configured against yb-tserver, and the yb-masters should have the same settings as yb-tserver 👍 thank you

What happens if they're mismatched? Like for example, what if I do a rolling deployment to change my nodes config from 4 to 8 (because I'm scaling up the size of the VMs), and during a brief time the `--num_shards=X` is different for some of the components... Will that cause something to break? if someone can help me understand the impact of changing the param (maybe it's harmless) in uptime, and whether it's a problem to have them mismatch for just a bit during a rolling upgrade, then otherwise we can absolutely close this out. thanks again for your time and answering

**Comment by schoudhury** [comment]
Thanks for the comments @aegershman. Num shards cannot be changed on cluster/table after it has been created so that the scenario you are pointing out will essentially lead to an error where the rolling upgrade will be rejected. In other words, nothing will break. In fact, these are the scenarios that we intend to take care of first in the future before making num shards changeable on an existing cluster/table.

**Comment by aegershman** [comment]
What happens if the the flag is set to `-1` (automatic based on host cpu cores), and the instance type of the host changes to something larger? Does that mean it's not going to try to modify itself once the value has been set for the first time, even if the host changes?

I don't mean to obsess about it, I'm just curious because that'd affect what sizes of VMs are initially chosen for a cluster, because if the initial size of the cluster is set small enough that it auto-sets itself to something like `4`, and then scaled to be on larger hosts to where it auto-sets to `8` & breaks, then it's good to know so that the initial size of the cluster would always have tservers be larger (or at least not scale beyond what it's initially set with)

apologies for the rambling, and thanks for the time I really appreciate it

**Comment by schoudhury** [comment]
>Does that mean it's not going to try to modify itself once the value has been set for the first time, even if the host changes?

Yes it won't change after it is initially set irrespective of whatever changes are made to the host VM.

**Comment by aegershman** [comment]
👍 thanks a ton for your time and answering these questions, it might not ever come up again but hopefully if anyone has questions about this then they can search the issue tracker and find these comments which definitely helped me understand the consequences of the "starting size" of a universe
