### ISSUE TITLE
Long lock of catalog manager + High CPU for ever after postgresql schema import

### ISSUE THREAD

**Issue by vtzan** [yugabyte/yugabyte-db#3986]
Dear Team,

I was trying to use latest YB 2.1.2.0 as a postgresql server in a 3 node cluster in the same DC.
Nodes were 4 CPU / 16GB RAM

After importing this schema. (which was really fast BTW with this YB version. I remember previous versions needed x3 the time to import that script)
```
#!/bin/bash
OPENSIPS_VERSION=3.0
DB1="opensips_edge_v1";
DB2="opensips_b2bua_v1";
DB3="opensips_proxy_v1";


git clone https://github.com/OpenSIPS/opensips.git
git checkout $OPENSIPS_VERSION
cd opensips/scripts/postgres/

ysqlsh -h `hostname` -c "create database $DB1;"
ysqlsh -h `hostname` -c "create database $DB2;"
ysqlsh -h `hostname` -c "create database $DB3;"

ysqlsh -h `hostname` -f standard-create.sql $DB1;
ysqlsh -h `hostname` -f standard-create.sql $DB2;
ysqlsh -h `hostname` -f standard-create.sql $DB3;

for i in `ls *.sql`; do
    if [ "$i"!="standard-create.sql" ]; then
        ysqlsh -h `hostname` -f $i $DB1;
        ysqlsh -h `hostname` -f $i $DB2;
        ysqlsh -h `hostname` -f $i $DB3;
    fi
done;
```
I noticed HIGH CPU on all 3 nodes that went for ever and never stopped.

![yb-high-cpu](https://user-images.githubusercontent.com/1777931/76844211-a21c0980-6845-11ea-8322-e458b36dc8d3.png)

Here are the logs from one node: https://pastebin.com/VRxXdiDM

thank you in advance for your support
Vasilios Tzanoudakis

**Comment by ddorian** [comment]
@vtzan how many total tablets are on each yb-tserver ?

![image](https://user-images.githubusercontent.com/1592898/76859884-63447e80-685a-11ea-9ac8-03f5c405a515.png)

**Comment by ddorian** [comment]
This is related to https://github.com/yugabyte/yugabyte-db/issues/772 .
@vtzan fixed the issue by creating a lower number of tablets, since they're tables with very little data.

**Comment by kmuthukk** [comment]
Thx @ddorian
