### ISSUE TITLE
Failure running docker image

### ISSUE THREAD

**Issue by brianhks** [YugaByte/yugabyte-db#4]
Here is the command and the output:
docker run --name yb-master-n1 --net yb-net yugabytedb/yugabyte:latest /home/yugabyte/bin/yb-master --fs_data_dirs=/mnt/disk0,/mnt/disk1 --master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 --rpc_bind_addresses=yb-master-n1:7100
F1121 04:38:32.989648     1 master_main.cc:78] Check failed: _s.ok() Bad status: Service unavailable (yb/server/hybrid_clock.cc:156): Cannot initialize clock: Error reading clock. ntp_gettime() failed: Operation not permitted
*** Check failure stack trace: ***
    @     0x7fe8c1fc026b  DumpStackTraceAndExit (yb/util/logging.cc:146)
    @     0x7fe8c0f9804c  google::LogMessage::Fail() (src/logging.cc:1478)
    @     0x7fe8c0f99f7c  google::LogMessage::SendToLog() (src/logging.cc:1432)
    @     0x7fe8c0f97ba9  google::LogMessage::Flush() (src/logging.cc:1301)
    @     0x7fe8c0f9aa3e  google::LogMessageFatal::~LogMessageFatal() (src/logging.cc:2013)
    @           0x405652  MasterMain (yb/master/master_main.cc:81)

*** Aborted at 1511239113 (unix time) try "date -d @1511239113" if you are using GNU date ***
PC: @     0x7fe8bdeff832 __GI_abort
*** SIGSEGV (@0x0) received by PID 1 (TID 0x7fe8c8dc1a00) from PID 0; stack trace: ***
    @     0x7fe8be284110 (unknown)
    @     0x7fe8bdeff832 __GI_abort
    @     0x7fe8c1fc02bd yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7fe8c0f9804d google::LogMessage::Fail()
    @     0x7fe8c0f99f7d google::LogMessage::SendToLog()
    @     0x7fe8c0f97baa google::LogMessage::Flush()
    @     0x7fe8c0f9aa3f google::LogMessageFatal::~LogMessageFatal()
    @           0x405653 yb::master::MasterMain()
    @     0x7fe8bdeeaa85 __libc_start_main
    @           0x405153 (unknown)
    @                0x0 (unknown)

**Comment by ramkumarvs** [comment]
@brianhks Hey can you provide bit more details into what os you are running this and the version of docker

**Comment by brianhks** [comment]
>uname -a
Linux home-linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

>docker --version
Docker version 17.05.0-ce, build 89658be

**Comment by ramkumarvs** [comment]
@brianhks can update your docker run command with 
`docker_cmd = ['docker', 'run', '--name', container_name, '--privileged']`
in yb-docker-ctl

**Comment by ramkumarvs** [comment]
btw, i pushed that change you can download the latest 
https://downloads.yugabyte.com/yb-docker-ctl and try the create cluster with it. Let us know if that fixes the issue you were facing.

**Comment by brianhks** [comment]
That worked, my cluster is up and running, thanks
