### ISSUE TITLE
[YW][K8S] EditUniverse: change preferred region triggered data migration

### ISSUE THREAD

**Issue by ryli17** [yugabyte/yugabyte-db#4009]
Yugaware: 2.1.0.0-b18
Yugabyte: 2.1.0.0-b18

Cluster setup: 3-node, replicafactor=3. 1 node in sv, 1 node in dc, and 1 node in ny, all regions are preferred
Edit Universe: remove preferred in dc and ny, only keep preferred in sv

Symptom:
The Edit Universe operation takes long time. From task list, it shows data migration is triggered.

Expect behavior:
Edit preferred region should not trigger data migration

**Comment by ryli17** [comment]
[tenant-82386-yugaware-0.log.gz](https://github.com/yugabyte/yugabyte-db/files/4351029/tenant-82386-yugaware-0.log.gz)

**Comment by kmuthukk** [comment]
@Arnav15 & @yb-andrew are working on fixing this issue that's specific to k8s deployment of a universe under Yugabyte Platform.
