### ISSUE TITLE
[YSQL] Creating table with duplicate name results in multiple YB tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4013]
If we create a duplicate table, then YSQL returns an error saying that table already exists, but yb master creates the table. For example:
```
yugabyte=# create table test(a int primary key);
CREATE TABLE
yugabyte=# create table test(a int primary key);
ERROR:  relation "test" already exists
```
Now, if you go to master UI, you'll see two tables with the name `test`.

This issue will get fixed once we have background job in master to delete such inconsistencies (rather the window during which the extra tables will exist will reduce). However, we should check if we can reorder the table creation process in YSQL such that table is created on master *after* constraint and sanity checks are done in postgres.

**Comment by marcus-sa** [comment]
Weird, I'm still getting this error using the latest version.

**Comment by marcus-sa** [comment]
So, why is this still occurring?
