### ISSUE TITLE
Adding SERIAL column to existing table fails

### ISSUE THREAD

**Issue by stevecookform3** [yugabyte/yugabyte-db#4034]
Jira Link: [DB-2394](https://yugabyte.atlassian.net/browse/DB-2394)
version: (docker) yugabytedb/yugabyte:latest
yugabyted version        : 2.1.2.0-b10

To reproduce:
```
yugabyte=# CREATE DATABASE test;
CREATE DATABASE
yugabyte=# \c test 
You are now connected to database "test" as user "yugabyte".
test=# CREATE TABLE dog (cat SERIAL);      #works fine
CREATE TABLE
test=# CREATE TABLE elephant (name TEXT);
CREATE TABLE
test=# ALTER TABLE elephant ADD COLUMN cat SERIAL;     #fails
ERROR:  Not found: Error loading table with oid 16489 in database with oid 16476: The object does not exist: table_id: "0000405c000030008000000000004069"
test=# 
```

**Comment by ddorian** [comment]
Confirming the bug above:
```
yugabyte=# CREATE TABLE elephant (name TEXT);
CREATE TABLE
yugabyte=# ALTER TABLE elephant ADD COLUMN cat SERIAL;
ERROR:  Not found: Error loading table with oid 25036 in database with oid 12457: The object does not exist: table_id: "000030a90000300080000000000061cc"
yugabyte=# alter table elephant add column cat bigint default nextval('cat_seq');
ERROR:  Already present: The column already exists: cat
```


@stevecookform3 
I believe this is related to https://github.com/YugaByte/yugabyte-db/issues/1822. Are you trying to add a primary key after creating the table ? If yes, you have to specify the primary key when creating the table.

**Comment by ndeodhar** [comment]
Thanks for reporting this error @stevecookform3.

This is partly related to https://github.com/yugabyte/yugabyte-db/issues/3967.
In this case, when `ALTER TABLE` command fails, the column `cat` gets added to YB metadata but postgres system tables don't have the column. This can cause subsequent queries on the table to fail.

We still need to investigate and diagnose what causes the `Error loading table` failure in the first place.

**Comment by stevecookform3** [comment]
@ddorian not related to https://github.com/yugabyte/yugabyte-db/issues/1822 as far as i can see. SERIAL columns are auto-incrementing integer columns, but dont have to be primary keys.

**Comment by ndeodhar** [comment]
That's right @stevecookform3 . It's not related to PK.
