### ISSUE TITLE
[docdb] High memory growth when using a Redis workload

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4043]
Jira Link: [DB-2555](https://yugabyte.atlassian.net/browse/DB-2555)
Sample command:
```java -jar ./target/yb-sample-apps.jar --workload RedisYBClientKeyValue --nodes 172.151.28.193:6379,172.151.30.71:6379,172.151.31.205:6379 --num_threads_read 2 --num_threads_write 2 --nouuid --num_unique_keys 2000000000```

Observed behavior (from Slack, see https://yugabyte.slack.com/archives/C4K1838GL/p1584583553268600):

In the last 20minutes, `mem_tracker_Read_Buffer_Redis_Mandatory` grew to 350MB, then dropped to 0 and the allocations seemed to have moved to just `mem_tracker_Read_Buffer` and then slowly that drains, while the `Redis_Mandatory` one fills back up.
Previously, `Redis_Mandatory` had grown to 1.4GB, then flattened out (potentially hitting soft memory limit). Maybe we were trying to read a massive request and hit memory limit before we could finish it?

cc @amitanandaiyer

**Comment by spolitov** [comment]
I tried to run this workload locally. And it established 144 connections and still growing.
We could allocate up to 2mb per Redis connection.
So number of connections explains this memory usage.

**Comment by bmatican** [comment]
Thanks @spolitov ! Passing to @m-iancu for now, in case he knows where this behavior is coming from.
