### ISSUE TITLE
CREATE DATABASE lc_collate and lc_ctype options report default values as invalid

### ISSUE THREAD

**Issue by stevecookform3** [yugabyte/yugabyte-db#4044]
Trying to create a new database with the psql client:

```
postgres=# \l
                                   List of databases
      Name       |  Owner   | Encoding | Collate |    Ctype    |   Access privileges   
-----------------+----------+----------+---------+-------------+-----------------------
 postgres        | postgres | UTF8     | C       | en_US.UTF-8 | 
```

so i expect the default value of LC_COLLATE should be "C", but if you try to create a database with this option you still get an error:

```
postgres=# CREATE DATABASE dog LC_COLLATE = "C";
ERROR:  Value other than default for lc_collate option is not yet supported
LINE 1: CREATE DATABASE dog LC_COLLATE = "C";
                            ^
```

same thing happens with LC_CTYPE:

```
postgres=# CREATE DATABASE dog LC_CTYPE = "en_US.UTF-8";
ERROR:  Value other than default for lc_ctype option is not yet supported
LINE 1: CREATE DATABASE dog LC_CTYPE = "en_US.UTF-8";
                            ^
```

**Comment by stevecookform3** [comment]
maybe just my misunderstanding of what the error `Value other than default` means.. as this seems to work fine:

`CREATE DATABASE dog LC_COLLATE = DEFAULT`

**Comment by ddorian** [comment]
@stevecookform3 
We have an opened issue regarding this: https://github.com/yugabyte/yugabyte-db/issues/2444
Can we move the conversation there and close as duplicate ?
