### ISSUE TITLE
[Platform] Remove node on RF3 or RF5 shouldn't hang

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#4046]
Right now there is no wait for data move for a RF3 and RF5 universe when we try to remove a node on a 3 node or 5 node. We currently hang on the wait for data move, which doesn't apply.

**Comment by bmatican** [comment]
FYI this is a bit more complex. We have to not wait anytime when we have exactly the same number of nodes as RF in that zone. So even if you have a 4 node RF3 setup across 3 zones:
A: 2
B: 1
C: 1

If you try to decommission either the node from B or C, we should not wait, as it's impossible for the data to move anywhere else.

cc @Arnav15
