### ISSUE TITLE
Tserver lost tablet peers while it's alive

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#4055]
I ran a 3 node cluster with rf 3 manually but 1 of nodes lost it's tablet peers after a while (4 day or 1 day) while it's alive.

![0tablet](https://user-images.githubusercontent.com/28354390/77432295-80012900-6dfb-11ea-8bed-ebc74e9854e8.png)

Here is a part of the tserver log:

```
W0324 13:26:12.221416 22783 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.102:56931 => 192.168.250.101:9100 (request call id 671298411) took 106027ms (client timeout 2500ms).
W0324 13:26:12.221557 22783 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.102:46003 => 192.168.250.101:9100 (request call id 671298470) took 106001ms (client timeout 2500ms).
W0324 13:26:12.222172 22783 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.102:53035 => 192.168.250.101:9100 (request call id 671302659) took 104391ms (client timeout 2500ms).
W0324 13:26:35.905908 22784 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.100:60501 => 192.168.250.101:9100 (request call id 670330603) took 2600ms (client timeout 2500ms).
W0324 13:26:35.906324 22784 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.102:57097 => 192.168.250.101:9100 (request call id 671575086) took 23740ms (client timeout 2500ms).
W0324 13:26:35.906471 22784 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.102:59433 => 192.168.250.101:9100 (request call id 671575105) took 23734ms (client timeout 2500ms).
W0324 13:27:16.473021 22786 yb_rpc.cc:395] Call yb.tserver.TabletServerService.Read 192.168.250.102:56931 => 192.168.250.101:9100 (request call id 671736074) took 2600ms (client timeout 2500ms).
```

After restarting tserver everything work fine for while but it happen again.

i'm using `yugabyte 2.1.2.0`.
And this issue start happening after i drop all keyspace and tables and recreate them again i also `flushall` YEDIS

**Comment by zeinali0** [comment]
this is happening more repeatedly and for more nodes

**Comment by ddorian** [comment]
@zeinali0 

> After restarting tserver everything work fine for while but it happen again.

Looks like it lost all tablet-leaders. Can you paste the config that you used ?

> (request call id 671736074) took 2600ms (client timeout 2500ms).

Maybe you were running a high load that the server starting to timeout ?


What happens after the high load has finished, does the server automatically recover and spreads the tablet leaders ?

**Comment by ddorian** [comment]
> or changing number of shards per table to 20?

What are your server specs ? 
What is the cpu usage when a node is idle ?

**Comment by zeinali0** [comment]
I checked problem with help of @kmuthukk on slack about 5 month ago.
Any kind of high write load on this table was the root of problem (Batch insert or simple insert):
```
CREATE TABLE IF NOT EXISTS user_db.phone_book(
    clientId BIGINT,
    userId INT,
    firstName TEXT,
    lastName TEXT,
    phone TEXT,
    countryLessPhone TEXT,
    creationTime TIMESTAMP,
    PRIMARY KEY((userId), phone)
) WITH transactions = { 'enabled' : true };

CREATE UNIQUE INDEX IF NOT EXISTS user_phones ON user_db.phone_book(countryLessPhone);
```
While at that time i checked both DISK bandwidth and CPU load was low and there weren't any pressure on them.
The problem didn't appeared anymore as i removed transaction-enabled and index.
Also @kmuthukk confirmed that they could reproduce problem with Batch insert.
Now i just want to know does problem exist in version 2.3 or now we can use secondary-index on table like this which there is high write load on them?

**Comment by kmuthukk** [comment]
hi @zeinali0 -- which release of YugabyteDB were/are you using?

**Comment by zeinali0** [comment]
version `2.1.2.0`

**Comment by kmuthukk** [comment]
Yes -- there have been many improvements for multi-shard transactional (e.g., those involving indexing) related to stability under load. The 2.2.2 release would be a good version to move to. 

However, I should add that without knowing the exact nature of the issue you had in the past, it is hard to be sure. If issue happens again, can you upload the yb-master/yb-tserver INFO logs covering the timerange of the incident?

**Comment by zeinali0** [comment]
Yeah sure, i would upload logs if this happened again.
Thanks.

**Comment by rthallamko3** [comment]
Doesn't seem to be an issue anymore.
