### ISSUE TITLE
[docs] Link line (using underscore characters) display outside of the code back ticks and can be confusing

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#4059]
I saw `_` in the beginning and end of the command string, not sure if this is intentional 

<img width="349" alt="Screen Shot 2020-03-24 at 10 37 39 AM" src="https://user-images.githubusercontent.com/5263706/77458600-b0c16e00-6dbb-11ea-80d1-3a725acedd0a.png">

**Comment by stevebang** [comment]
@yb-andrew See the "See also" section at the bottom of this page to see what @ramkumarvs is reporting: https://docs.yugabyte.com/latest/api/ysql/commands/ddl_alter_sequence/.
- The underscore (`_`) that @ramkumarvs is seeing is actually the link line.  Not sure if this can be fixed, but can we make the links more visible when within the code back ticks?  This will be a common issue throughout the docs and it can also be difficult to see that many code terms include links to configuration settings, YSQL statements, etc.

**Comment by yb-andrew** [comment]
The codeblock is covering the link underline when using characters that normally extend below the line of text (such as 'y', 'g', 'q', 'p'). We can solve it by adding a pixel padding to push the code block up

**Comment by stevebang** [comment]
Closing -- fixed in https://github.com/yugabyte/yugabyte-db/commit/cdd76ef3f49e79847a2d79b667320e4aa6f4eee3
