### ISSUE TITLE
Add Minikube tunnel for local YB testing

### ISSUE THREAD

**Issue by ybnelson** [yugabyte/yugabyte-db#4065]
Add steps to leverage Minikube on localhost to test Kubernetes install of YugabyteDB.
https://docs.yugabyte.com/latest/quick-start/install/kubernetes/

Run this command in a separate command-line window:
```
minikube tunnel
```
Services exposed via load-balancer such as 'yb-tserver-service' should now get a local IP to connect to from YSQLSH:
```
kubectl get svc -n yb-demo
NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                        AGE
yb-master-ui         LoadBalancer   10.96.170.75   10.96.170.75   7000:31908/TCP                                 1m
yb-masters           ClusterIP      None           <none>         7100/TCP,7000/TCP                              1m
yb-tserver-service   LoadBalancer   10.96.89.217   10.96.89.217   6379:32627/TCP,9042:31180/TCP,5433:30865/TCP   1m
yb-tservers          ClusterIP      None           <none>         7100/TCP,9000/TCP,6379/TCP,9042/TCP,5433/TCP   1m
```
When you start the YSQLSH client, use the EXTERNAL-IP given for the service to connect:
```
bin/ysqlsh -h 10.96.170.75
```

**Comment by iSignal** [comment]
It is documented at https://docs.yugabyte.com/latest/deploy/kubernetes/clients/#connecting-externally-to-a-minikube-cluster
