### ISSUE TITLE
YSQL doc wrong at "APIs > YSQL > Expressions"

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#4074]
The first problem is that the page title (and side bar link) _"Expressions"_ is simply the wrong word. We see this by reading the first text on the page (my italics):

> YugabyteDB Structured Query Language (YSQL) supports all PostgreSQL-compatible built-in *functions and operators*. The following statements are the currently documented ones

The the page title and the link should be this:

> **Functions and operators**

The second problem is that the three function names in the table:

> `func_currva()`, `func_lastval()`, `func_nextval()`

are simply wrong. You see this by following the links. These are the names:

> `nextval()`, `currval()`, `lastval()`

B.t.w. See the tables on this page:

http://localhost:1313/latest/api/ysql/datatypes/type_json/functions-operators/

They link to about 35 JSON-specific functions and operators. We need to decide how to bring these onto the present page. One simply row in the table that cross-ref's to the JSON account is by far the easiest fix.

**Comment by schoudhury** [comment]
Fixed as part of https://github.com/yugabyte/yugabyte-db/pull/4079 .. changes will be available at the next rebuild of the docs site.
