### ISSUE TITLE
can be used on the mechanical hard disk?

### ISSUE THREAD

**Issue by lizhichao** [yugabyte/yugabyte-db#4104]
If there is no SSD, yugabyte-db can be used on the mechanical hard disk?

**Comment by kmuthukk** [comment]
hi @lizhichao - 

Unfortunately, no. YugabyteDB's design is not meant/optimized for hard disk environment. It requires SSDs.

**Comment by lizhichao** [comment]
Ok

**Comment by ddorian** [comment]
@lizhichao See: https://docs.yugabyte.com/latest/deploy/checklist/#disks
Optimizing for low latency and fast reads/inserts just can't work with HDD.
We have issues that will lower the overhead disk io: 
Wal multiplex https://github.com/yugabyte/yugabyte-db/issues/3549
Tablet splitting https://github.com/yugabyte/yugabyte-db/issues/1004

After those land and by combining them with colocation + low number of tablets per-table + raid0 of some hdd, I will do some tests to see if HDD may be viable. But it will not be official though.

**Comment by tobiasmuehl** [comment]
@ddorian Looking forward to your tests.

The design of [openIO](https://openio.io) (yes, I'm aware it's just a self-hosted S3 and not a full database) uses HDD for storage and requires a small SSD to be present for metadata that is accessed more frequently. Does Yugabyte have similar optimizations? Let's say we'd run each server with 4 HDDs and 1 SSD, would the SSD be used specifically for IO-intensive tasks or are all disks load-balanced equally?

**Comment by tobiasmuehl** [comment]
@ddorian From my understanding #1004 tablet splitting has landed. Do you think now is a "good enough" time to attempt using HDDs?

**Comment by ddorian** [comment]
> Do you think now is a "good enough" time to attempt using HDDs?

No, would need wal multiplexing too. That's more important than tablet splitting.

> The design of openIO (yes, I'm aware it's just a self-hosted S3 and not a full database) uses HDD for storage and requires a small SSD to be present for metadata that is accessed more frequently. Does Yugabyte have similar optimizations? Let's say we'd run each server with 4 HDDs and 1 SSD, would the SSD be used specifically for IO-intensive tasks or are all disks load-balanced equally?

It's a completely different workload. Think of it like this: you put the metadata of openIO INSIDE yugabytedb and put yugabytedb ON TOP OF ssd.  

metadata in openio ==(they are actually the same thing!)== yugabytedb-data. Putting yugabytedb in HDD is exactly like putting openIO.metadata in HDD.

**Comment by ddorian** [comment]
As an example, [seaweedfs](https://github.com/chrislusf/seaweedfs) is also an object store / s3, that is optimized for HDD. It's [metadata](https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores), can reside in yugabytedb.
