### ISSUE TITLE
'cassandra' Role password reset to default each time one of yb-master reset.

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#4105]
On a 3 rf universe each time i reset one of my yb-master proccess the 'cassandra' role password reset to default('cassandra').
i'm using Yugabyte V2.1.2.0.
Is it a bug or it designed like this on purposely for restoring forgotten password?

**Comment by kmuthukk** [comment]
when you say "reset" your yb-master process -- do you mean restart?
