### ISSUE TITLE
Some failure modes with multiple clients

### ISSUE THREAD

**Issue by therealnb** [YugaByte/yugabyte-db#411]
I have been using the test script here https://gist.github.com/therealnb/0e9f411f3b400eb43d082844f1f86b57
to create edges using a cluster of clients. This worked well with 12 clients but entered a failure mode with 24 which it didn't seem to recover from. Some of the results and exceptions are here
https://gist.github.com/therealnb/bbec5c3970dfe93347b6a56a0fe78b68

**Comment by therealnb** [comment]
I should point out that the initial report was with 3 masters and 3 tablet servers. The same happened with 6 tablet servers also.

**Comment by therealnb** [comment]
They are all running on their own containers. I didn't see a section in the yaml file to up the memory, so I guess I would have to wait for a new image for that.

**Comment by kmuthukk** [comment]
@therealnb 

What about the Num CPUs, RAM, etc. for those containers.  What's the best way we can help debug - either if you could share the logs, or if we can help debug over a conf-call/screen share?

regards,
Kannan

**Comment by therealnb** [comment]
The machines are n1-standard-4 (4 vCPUs, 15 GB memory), so they have 3.75GB per core. I have been allowing for a core per pod.

**Comment by therealnb** [comment]
I'll see if I can post some server logs here, after the current test I am running, and then someone can help me from there. Then we can have a screen share.

Once again, thanks for the quick response.

**Comment by kmuthukk** [comment]
So for all 3 yb-masters and the 3 to 6 yb-tservers (so 6-9 processes in total) they are running/sharing a total of 4-cpus? This won't be suited for any form of load-testing, or at least our defaults aren't tuned to run at these levels. 

Is it possible to give each of the pods at least 2-cpus and 8-gb of RAM for now? In any case, at this point this is only  a theory - and we need to double check if this is indeed the issue you are running into.

[CC: @bmatican , @ramkumarvs  - let's figure out best way forward on making our defaults better for the container based getting started flows and making the defaults settings more robust.]

**Comment by therealnb** [comment]
No, each machine has 4 CPUs. I gave each pod a CPU of its own, so 9 for yugabyte and one for each of my little clients.

I can try any configuration to investigate the problem, the only reason I was using that size was because that what what I was doing before.

**Comment by therealnb** [comment]
Here is another set of results showing the problem https://gist.github.com/therealnb/0f8c1c2221d4577a36b4e2bfcb9b2e60
Most of it is my script logs, but there are some of the server logs there as well.
I still have the cluster running, if anyone wants to join I'll leave https://meet.google.com/wrn-pjex-uub open for a while.

**Comment by therealnb** [comment]
Ok, well this could be a cause of trouble
`IO error (yb/util/env_posix.cc:498): Could not init Tablet Manager: Failed to write tablet metadata 1948fe9562ac45f08bdc6e0858772cd3: Failed to Append() header to file: /mnt/data0/yb-data/tserver/tablet-meta/1948fe9562ac45f08bdc6e0858772cd3.tmp.0p2LeJ: No space left on device`

**Comment by therealnb** [comment]
When I re-ran with 10x disk space, I didn't see the exceptions/timeouts.

It is hard to see what yugabyte could do in an out of disk space situation. 

This isn't a real problem.

**Comment by kmuthukk** [comment]
Good debugging @therealnb ! Thanks... glad it was just an insufficiently configured disk size issue.
