### ISSUE TITLE
[YW] On-premise nodes don't have the custom ssh port option enabled and so backups/ssh commands fail

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4110]
It appears that on-premise installations do not execute the flow reset the ssh_port to 54422 as it does in the cloud providers. We need to therefore not display `-p 54422` in the ssh connect string or default it in the yb_backup script from YW and allow the default to be port 22.

**Comment by rkarthik007** [comment]
@WesleyW @ramkumarvs - could we please update this issue and close out if its done?

**Comment by WesleyW** [comment]
Done in feb843c38831bcf0665d8dd5eed798c09e285a3a
