### ISSUE TITLE
[colocation] PgLibPqTest.TableColocation: CreateNamespace RPC timed out

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4116]
Jira Link: [DB-1599](https://yugabyte.atlassian.net/browse/DB-1599)
I'm seeing timeout errors on creating colocated database.

```
ERROR: Timed out: CreateNamespace timed out after deadline expired. Time elapsed: 60.000s, allowed: 60.000s: CreateNamespace RPC (request call id 108) to M-1_RPC_HOST_PORT timed out after 60.000s
```

Over 1000 runs on CentOS debug build, I got two failures both due to this same error.  They have also shown up on Jenkins `centos-clang-debug` build.  See the relevant log snippet at <https://gist.githubusercontent.com/jaki/42a281993243114934b1a7ece4fa01f4/raw/5485bffd5b7d3b0fc1b7508a728233c1d3b644a9/PgLibPqTest_TableColocation.log> and the full log (short-lived) at <https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator/29764/artifact/build/debug-clang-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_libpq-test/PgLibPqTest_TableColocation.log>.

**Comment by jaki** [comment]
Over several hundred more runs, I got a different log error

```
[ts-1] W0527 13:44:44.683719 26791 client-internal.cc:1257] GetTableSchemaRpc(table_identifier: table_id: "000000010000300080000000000004ec", num_attempts: 1) failed: Timed out (yb/rpc/outbound_call.cc:512): RPC timed out after deadline expired: GetTableSchema RPC (request call id 1) to 127.0.0.1:20726 timed out after 59.999s
[ts-1] 2020-05-27 13:44:44.684 PDT [25791] FATAL:  Not found: Error loading table with oid 1260 in database with oid 1: RPC timed out after deadline expired: GetTableSchema RPC (request call id 1) to 127.0.0.1:20726 timed out after 59.999s
../../src/yb/yql/pgwrapper/pg_libpq-test.cc:938: Failure
Failed
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:146): Connect failed: 1, passed: 60.061s
```

**Comment by jaki** [comment]
And several other errors:

- https://gist.github.com/jaki/ddaa12b123de23d7262d0c42c0e15968/raw
- https://gist.github.com/jaki/ec60b82ae1b6a72140c8b75bcae63785/raw
- https://gist.github.com/jaki/0e7a6378fbe30e83973ced96fd145a85/raw

I haven't seen the `CreateNamespace` error over the past 2000 runs.

**Comment by jasonyb** [comment]
Ran `./yb_build.sh fastdebug --gcc11 --cxx-test pgwrapper_pg_libpq-test --gtest_filter PgLibPqTest.TableColocation -n 1000` on alma8 on recent master commit b16653e05c0a625fd5771a8255dc9a7953a26f4b.  100% pass.  This issue may be outdated.  Internal detective stability page shows that most failures are on mac, so maybe it is just a slowness issue.
