### ISSUE TITLE
yb-ctl needs to set the right mem limits

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4139]
We need to set --default_memory_limit_to_ram_ratio=0.35 on master like in yugabyted

**Comment by iSignal** [comment]
@bmatican @schoudhury @m-iancu

**Comment by tweenietomatoes** [comment]
having issue with creating database using ysqlsh.

CREATE DATABASE db1;

ERROR:  Timed out: Timed out waiting for Namespace Creation

**Comment by tweenietomatoes** [comment]
--master_flags='default_memory_limit_to_ram_ratio=0.35'

worked.

**Comment by iSignal** [comment]
Fixed in https://github.com/yugabyte/yugabyte-installation/pull/31, fix should be available in 2.1.8.1
