### ISSUE TITLE
show uptime of TServer in /tablet-servers view of master

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#414]
It'll be nice for debug purposes to show the uptime (in human readable fmt) of each TServer in the master's /tablet-server view (http://<masters>:7000/tablet-servers)

**Comment by kmuthukk** [comment]
In the STATUS column (for "ALIVE" servers, we could just display the uptime right there as well say, ALIVE - 168 days 3 hrs 5 mins).

**Comment by rven1** [comment]
Updated the Status column title to Status & Uptime
Now shows:  Alive: 12:05 or Alive: 5days, 12:05
