### ISSUE TITLE
Create new database object with PostgreDatabaseManager

### ISSUE THREAD

**Issue by xyxiaoyou** [yugabyte/yugabyte-db#4141]
Edited for clarity:
```
SQL ERROR [0A000]: ERROR: Value other than default for tablespace option is not yet supported
  Hint: Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
  Position: 44
ERROR: Value other than default for tablespace option is not yet supported
  Hint: Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
  Position: 44
ERROR: Value other than default for tablespace option is not yet supported
  Hint: Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
  Position: 44
```
```
------------------------------------------
yugabyte=# CREATE DATABASE projectdb;
ERROR:  Already present: Keyspace 'projectdb' already exists
----------------------------------
yugabyte=# \list
                                   List of databases
      Name       |  Owner   | Encoding | Collate |    Ctype    |   Access privileges   
-----------------+----------+----------+---------+-------------+-----------------------
 postgres        | postgres | UTF8     | C       | en_US.UTF-8 | 
 resultdb        | yugabyte | UTF8     | C       | en_US.UTF-8 | 
 system_platform | postgres | UTF8     | C       | en_US.UTF-8 | 
 taskdb          | yugabyte | UTF8     | C       | en_US.UTF-8 | 
 template0       | postgres | UTF8     | C       | en_US.UTF-8 | =c/postgres          +
                 |          |          |         |             | postgres=CTc/postgres
 template1       | postgres | UTF8     | C       | en_US.UTF-8 | =c/postgres          +
                 |          |          |         |             | postgres=CTc/postgres
 yugabyte        | postgres | UTF8     | C       | en_US.UTF-8 | 
```

**Comment by ddorian** [comment]
hi @xyxiaoyou 
I edited your comment for clarity. 

Regarding your first error, we don't support yet setting custom tablespaces: https://github.com/yugabyte/yugabyte-db/issues/1153. Can you subscribe to this issue ?

On your second issue, the database `projectdb` already exists.

**Comment by xyxiaoyou** [comment]
> Hi @xyxiaoyou,
> 
> What application/tool is PostgreDatabaseManager? Wanted to understand what `TABLESPACE` is being used for there.
> 
> Also, wrt the `CREATE DATABASE` error, not sure what is going on. @ndeodhar @m-iancu - could you folks please weigh in?

Thanks. I used the DBeaver Client. I have now resolved the problem, but I have redeployed a yugabte suite using docker-compose.
Maybe this issue will reappear in the future and we will pay attention to it then.

**Comment by ddorian** [comment]
@xyxiaoyou 
By default DBeaver doesn't show all databases when you connect. I think you tried twice because it didn't show up.

There's an option on the connection settings to show all databases, making it easier to work with.

![image](https://user-images.githubusercontent.com/1592898/78774705-53b9e080-7995-11ea-8035-1ca65b57b78f.png)

**Comment by ddorian** [comment]
@xyxiaoyou 
My comment above should fix the issue. Please reopen if you have further questions.
