### ISSUE TITLE
TestRpc.TestConnectionKeepalive fails frequently on mac only

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4152]
Jira Link: [DB-1386](https://yugabyte.atlassian.net/browse/DB-1386)
https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-mac-master-clang-debug/lastCompletedBuild/testReport/junit/(root)/TestRpc/TestConnectionKeepalive/history/
on Mac

vs 

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-debug/lastCompletedBuild/testReport/junit/(root)/TestRpc/TestConnectionKeepalive/history/
on Centos

It failed in 80 / 100 commits as reported by detective-gcp.dev.yugabyte.com/stability?num_commits=100 and it appears all of them are on Mac.

Previous issue #1649 fixed by Timur @ttyusupov 

Ran this locally ybd debug --cxx-test rpc_rpc-test --gtest_filter TestRpc.TestConnectionKeepalive -n 1000 and it always succeeds.

**Comment by iSignal** [comment]
The errors logs from https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-mac-master-clang-debug/1055/artifact/build/debug-clang-dynamic-ninja/yb-test-logs/tests-rpc__rpc-test/TestRpc_TestConnectionKeepalive.log seem to indicate the heartbeats are not being sent as quickly as they should. 

Hearbeats should be sent every 50 ms according to the code (with a rpc conn timeout of 150ms) but we seem from the log lines below that heartbeats are delayed by 120ms. 
```
127.0.0.1:59625 => 127.0.0.1:59624: Sending heartbeat, now: 1294416.990s, deadline: 1294416.870s, last_write_time_: 1294416.820s, last_heartbeat_sending_time_: 0.000s
```

My theory is that the mac minis under load may not be able to schedule threads fast enough. I attempted to repro this kind of a scheduling lag but could only see a maximum lag of ~20ms.

@ttyusupov : do you think it would help to raise kGcTimeout to something higher like 2 seconds or so to avoid these issues?


Full log

```
I0407 14:20:05.808755 299488704 mem_tracker.cc:249] MemTracker: hard memory limit is 8.000000 GB
I0407 14:20:05.808885 299488704 mem_tracker.cc:251] MemTracker: soft memory limit is 6.800000 GB
I0407 14:20:05.816713 299488704 service_pool.cc:148] yb.rpc_test.CalculatorService: yb::rpc::ServicePoolImpl created at 0x108066480
I0407 14:20:05.817932 299488704 rpc-test.cc:329] Connecting to 127.0.0.1:59624
I0407 14:20:05.822764 147030016 yb_rpc.cc:278] Parsed YBInboundCall header: call_id: 1 remote_method { service_name: "yb.rpc_test.CalculatorService" method_name: "Add" } timeout_millis: 10000
I0407 14:20:05.823612 147030016 yb_rpc.cc:220] Connection (0x0000000108068fd8) server 127.0.0.1:59625 => 127.0.0.1:59624: Updated last_write_time_=1294416.820s
I0407 14:20:05.823637 150249472 yb_rpc.cc:566] 0x0000000108068eb8 -> Connection (0x0000000108068eb8) client 127.0.0.1:59625 => 127.0.0.1:59624: Updated last_read_time_=1294416.824s
I0407 14:20:05.824311 299488704 rpc-test.cc:336] Connections are up
I0407 14:20:05.982823 299488704 rpc-test.cc:340] Checking connections
I0407 14:20:05.984814 147030016 yb_rpc.cc:241] Connection (0x0000000108068fd8) server 127.0.0.1:59625 => 127.0.0.1:59624: Sending heartbeat, now: 1294416.990s, deadline: 1294416.870s, last_write_time_: 1294416.820s, last_heartbeat_sending_time_: 0.000s
I0407 14:20:05.985036 147030016 yb_rpc.cc:220] Connection (0x0000000108068fd8) server 127.0.0.1:59625 => 127.0.0.1:59624: Updated last_write_time_=1294416.990s
I0407 14:20:05.985451 150249472 yb_rpc.cc:572] 0x0000000108068eb8 -> Connection (0x0000000108068eb8) client 127.0.0.1:59625 => 127.0.0.1:59624: YBOutboundConnectionContext::HandleTimeout
I0407 14:20:05.985534 150249472 yb_rpc.cc:582] 0x0000000108068eb8 -> Connection (0x0000000108068eb8) client 127.0.0.1:59625 => 127.0.0.1:59624: YBOutboundConnectionContext::HandleTimeout last_read_time_: 1294416.824s, timeout: 0.150s
W0407 14:20:05.985630 150249472 yb_rpc.cc:590] Connection (0x0000000108068eb8) client 127.0.0.1:59625 => 127.0.0.1:59624: Network error (yb/rpc/yb_rpc.cc:589): Read timeout, passed: 0.166s, timeout: 0.150s, now: 1294416.990s, last_read_time_: 1294416.824s
I0407 14:20:05.986507 147030016 tcp_stream.cc:308] { local: 127.0.0.1:59624 remote: 127.0.0.1:59625 }:  Recv failed: Network error (yb/util/net/socket.cc:537): recvmsg error: Connection reset by peer (system error 54)
../../src/yb/rpc/rpc-test.cc:101: Failure
      Expected: metrics.num_client_connections_
      Which is: 0
To be equal to: num_connections
      Which is: 1
Client should have 1 client connection(s)
```

**Comment by rthallamko3** [comment]
[detective runs history](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TestRpc&fail_tag=all&name=TestConnectionKeepalive&platform=linux)
[Mac failure trends](https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=TestRpc&fail_tag=all&name=TestConnectionKeepalive&platform=linux)

**Comment by rthallamko3** [comment]
Passing to @ttyusupov , as it is a mac only failure, maybe a minor tweak of the test can get it to work in mac builds?
