### ISSUE TITLE
[docs] Explain liquibase migrations

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#4153]
https://github.com/yugabyte/yugabyte-db/issues/1713#issuecomment-608617436

https://yugabyte.slack.com/archives/C58MY17GQ/p1585925973107100

**Comment by lizayugabyte** [comment]
Liquibase is described here: https://docs.yugabyte.com/latest/integrations/liquibase/
I'm closing this ticket as done via https://github.com/yugabyte/yugabyte-db/issues/8964
