### ISSUE TITLE
[docs] allow override of og:description with description property of a page's front matter

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4166]
currently the following property sets the og:description for all pages of the docs site and is not overridable 
```
layouts/partials/head.html:    <meta property="og:description" content="The high-performance distributed SQL database for global, internet-scale apps.">
```
allow the above property to the overridable on a per-page basis by the `description` property in the page's frontmatter.

cc @stevebang

**Comment by stevebang** [comment]
@yb-andrew I ran a doc page (https://docs.yugabyte.com/latest/quick-start/install/macos/) [using the Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdocs.yugabyte.com%2Flatest%2Fquick-start%2Finstall%2Fmacos%2F). 

The debugger returned the following warning:
- Missing Properties: The following required properties are missing: `og:type`, `fb:app_id`

When you're creating the override for `og:description`, maybe you can fix this issue too.
