### ISSUE TITLE
[docs] Add CREATE EXTENSION statement to YSQL API

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#4176]
Add documentation for the `CREATE EXTENSION` statement to the YSQL API. 

- Limited support for PostgreSQL extensions was added 
- Initial documentation added by @m-iancu in https://github.com/yugabyte/yugabyte-db/pull/2330.
- Add links to `CREATE EXTENSION` page from [Extensions](https://docs.yugabyte.com/latest/api/ysql/extensions/).

**Comment by stevebang** [comment]
@ndeodhar It looks like the CREATE EXTENSION statement was missed (referred to in the Extensions topic). Need grammar and syntax diagrams.

**Comment by jaki** [comment]
Close: #4323
