### ISSUE TITLE
[platform] Add throughput metric for individual YSQL ops

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4182]
Jira Link: [DB-1731](https://yugabyte.atlassian.net/browse/DB-1731)
Currently, the ops/sec metric in YW platform for YSQL shows the number of batches/sec. It'll be useful to also have a metric that displays number of individual ops/sec.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-527

**Comment by iSignal** [comment]
@ndeodhar : does this need additional instrumentation on the postgres side or should we show a different metric compared to the rpc_latency_count that is described in https://github.com/yugabyte/yugabyte-db/blob/bfeb3a60ac03625c13f025310a0f6c43dd376c93/managed/src/main/resources/metrics.yml#L1539

**Comment by ndeodhar** [comment]
@iSignal This depends on https://github.com/yugabyte/yugabyte-db/issues/4600.
We can pick this up once #4600 is completed.

**Comment by sushantrmishra** [comment]
We have select/insert/update/delete supported in YB.
