### ISSUE TITLE
[Platform] Support keys with non-RSA headers for onprem providers

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#4189]
Currently, our onprem validations require that SSH keys have "-----BEGIN RSA PRIVATE KEY-----" in the header/ender. To allow other headers (like "-----BEGIN OPENSSH PRIVATE KEY-----"), we should update our paramiko library to a later version and also change the validation function from RSA-only to any keys accepted by paramiko.

Relevant github issue: https://github.com/paramiko/paramiko/issues/1015

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-525

**Comment by chirag-yb** [comment]
Tracked here - https://github.com/yugabyte/yugabyte-db/issues/5754
