### ISSUE TITLE
[Platform] Add ability to associate specific IAM role(s) with created instances

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4199]
There is a requirement that a specific IAM role get attached to every AWS instance created by Yugaware for running YugabyteDB nodes. The example given was AWS SSM. This should be similar to the interface used for instance tags. 

The information should be captured at the universe creation time.

**Comment by ramkumarvs** [comment]
We need to include this in the create_instances call.
IamInstanceProfile={
        'Arn': 'string',
        'Name': 'string'
    },

**Comment by ajcaldera1** [comment]
I would suggest that the "User Tags" dialog should have a drop down to indicate type whether it was a "Tag" or "Role".
