### ISSUE TITLE
system_redis.redis should not be counted as an user table

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#42]
system_redis.redis table is auto-created in most cases but in some cases it requires an explicit user action. Even in those cases, counting system_redis.redis table as a user table doesn't make sense since the functioning/use of that table is under the control of the `system` and the end user.

See attached.
![redis-table](https://user-images.githubusercontent.com/792573/35789058-438954de-09ee-11e8-8d1f-0fd18f387f0b.png)

**Comment by bbaddepudi** [comment]
Fixed in [750b60b](https://github.com/YugaByte/yugabyte-db/commit/750b60bf4d170205ed370ba8dec9c83e9bd4bf26)
