### ISSUE TITLE
[platform] support for fully transactional backups for YCQL

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4202]
now that https://github.com/yugabyte/yugabyte-db/issues/3836 is about to get addressed, yb-platform should add the ability to create fully transactional backups for YCQL tables (and the associated indexes).

**Comment by schoudhury** [comment]
this may be a testing exercise since the yugabytedb change is transparent to yb-platform/yb-cloud.

**Comment by bmatican** [comment]
Table + indexes is already complete.

https://github.com/yugabyte/yugabyte-db/issues/4540 is tracking multi-table selection.
