### ISSUE TITLE
[platform] Metric graphs are sometimes inconsistent / missing spikes intermittently

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4203]
Show correct values with every refresh for Expired Transactions and Conflicts in the Transactions metric shown in the DocDB section.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-521

**Comment by iSignal** [comment]
Will close this one. We may need to do something similar for our p99 metrics. Will fix a separate issue for it.
