### ISSUE TITLE
[platform] AWS backup provider config should support IAM role as well

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4204]
the main AWS cloud provider can be setup using either IAM Role or using Access Key/Secret. however, the AWS backup provider config is only for Access Key/Secret. we need to add support for IAM Role as another way to configure the AWS backup provider.

**Comment by ajcaldera1** [comment]
Duplicate of 4199.

**Comment by ajcaldera1** [comment]
Closed in error -- reopened.

**Comment by schoudhury** [comment]
this issue is dependent on https://github.com/yugabyte/yugabyte-db/issues/4199 since the data nodes need to be provisioned with the IAM role first.
