### ISSUE TITLE
2i index on lists

### ISSUE THREAD

**Issue by doublex** [YugaByte/yugabyte-db#421]
To migrate a database from "BerkeleyDB" to YugoByte:

Is there a chance to query a range request on lexicographical list values?
Simplied example using CQL (finds users from 'Marseille', 'Melbourne', 'Moscow', ...):
````
UPDATE users SET places = ['London', 'Madrid'] WHERE userid = 1;
SELECT userid FROM users WHERE places CONTAINS BETWEEN 'Ma' AND 'Mz';
````

* Cassandra supports indexing `lists` using the `CONTAINS` keyword.
* Redis supports lexicographical indexes using the `ZRANGEBYLEX` command.

Thanks a lot!

**Comment by kmuthukk** [comment]
Hi @doublex 

We don't support indexing collection (set, list, map) attributes yet. But that's something in our roadmap. 

On the Redis side, we support the basic operations on sorted sets, but not ZRANGEBYLEX yet. We can add support for that. 

[Note however that ZRANGEBYLEX is indexing the sorted set entries within a single key. Whereas, in your CQL example, you are looking for a global index across the entire table. Both are reasonable requests - but just wanted to pointed out that they are different in scope/use case.]

**Comment by rkarthik007** [comment]
Also, wanted to point out that for:
> Cassandra supports indexing lists using the CONTAINS keyword.

The equivalent functionality can be achieved by creating a clustering column with the contents of the list and creating a secondary index. This should allow looking up by the list value in O(1). Not sure if that would work for you though.

**Comment by doublex** [comment]
@rkarthik007 

Our usecase: A BerkeleyDB record could have N secondary keys (N is small, usually 1 to 5 secondary keys). Would a clustering column work with a generic number of keys?

Is there an way to access the "common core data platform" directly?

**Comment by rkarthik007** [comment]
Yes, a clustering column works for any number of keys. You can set a secondary index on the clustering column.

For example, you can try the following out by installing YugaByte database on your laptop:
```
cqlsh> CREATE KEYSPACE test;
cqlsh> CREATE TABLE test.users(
userid INT,
place TEXT,
value TEXT,
PRIMARY KEY ((userid), place));

cqlsh> INSERT INTO test.users(userid, place, value) VALUES (1, 'London', 'foo');
cqlsh> INSERT INTO test.users(userid, place, value) VALUES (1, 'Madrid', 'bar');

cqlsh> SELECT * FROM test.users;

 userid | place  | value
--------+--------+-------
      1 | London |   foo
      1 | Madrid |   bar

(2 rows)
```

Note that you would need a [secondary index](https://docs.yugabyte.com/latest/api/cassandra/ddl_create_index/) in order to query user ids by place. Also, currently we support only equality based indexes - we are working on range based indexes. cc @robertpang 

> Is there an way to access the "common core data platform" directly?

There is no convenient way to access the common core data platform directly. Our query layer is closely integrated with the "DocDB" layer and is aware of the data sharding and placement.

**Comment by dongdongwcpp** [comment]
> Hi @doublex
> 
> We don't support indexing collection (set, list, map) attributes yet. But that's something in our roadmap.
> 
> On the Redis side, we support the basic operations on sorted sets, but not ZRANGEBYLEX yet. We can add support for that.
> 
> [Note however that ZRANGEBYLEX is indexing the sorted set entries within a single key. Whereas, in your CQL example, you are looking for a global index across the entire table. Both are reasonable requests - but just wanted to pointed out that they are different in scope/use case.]

Do we have plan to support index for collection (list、set、map) after five years pasted?

**Comment by dongdongwcpp** [comment]
> Hi @doublex
> 
> We don't support indexing collection (set, list, map) attributes yet. But that's something in our roadmap.
> 
> On the Redis side, we support the basic operations on sorted sets, but not ZRANGEBYLEX yet. We can add support for that.
> 
> [Note however that ZRANGEBYLEX is indexing the sorted set entries within a single key. Whereas, in your CQL example, you are looking for a global index across the entire table. Both are reasonable requests - but just wanted to pointed out that they are different in scope/use case.]

Do we have a plan to support index for collection (list、set、map) after five years pasted?
