### ISSUE TITLE
[docdb] Major compactions not cleaning up (expired/TTLed) data correctly in 2.1

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4211]
Seems to trace back to 7c46f82e616a57ed2aa3db166422fb77be2cec69

```
bool TabletRetentionPolicy::ShouldRetainDeleteMarkersInMajorCompaction() const {
  // If the index table is in the process of being backfilled, then we
  // want to retain delete markers until the backfill process is complete.
  return !metadata_.schema().table_properties().IsBackfilling();
}
```

Expired data is replaced with a delete marker (in minor compactions); on major compactions, the delete markers should also be removed. But the latter part of the cleanup wasn't happening after 7c46f82e616a57ed2aa3db166422fb77be2cec69 commit (in 2.1).

**Comment by kmuthukk** [comment]
Fixed with https://github.com/yugabyte/yugabyte-db/commit/46a477d99e357850fa4533d5f935d3b812e2f90e
