### ISSUE TITLE
Test for failed_tablets is failing intermittently on Jenkins

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4213]
Here is an example of the failure in TestTserverHealthChecks:

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator/31529/artifact/java/yb-client/target/surefire-reports_org.yb.client.TestTserverHealthChecks__testTserverHealthChecks/org.yb.client.TestTserverHealthChecks-output.txt

The test has started to fail recently with on 3 commits in master. Even when it succeeds, I am not sure the test is working as intended because I don't see the log line from catalog_manager.cc - https://github.com/yugabyte/yugabyte-db/blob/a3c4ef1c3cd1ce55cfd2d34ca8b87f6d64a38393/src/yb/master/catalog_manager.cc#L4218 

The reason I noticed it was it failed quite a lot on my diff - https://detective-gcp.dev.yugabyte.com/D8275 - which shouldn't technically affect this diff at all.

@bmatican

**Comment by bmatican** [comment]
cc @hectorgcr as this might have broken because now we actually trigger a RBS of failed tablets automatically, so this might break intermittently now!
