### ISSUE TITLE
[docs] Broken rendering in architecture page

### ISSUE THREAD

**Issue by candlerb** [yugabyte/yugabyte-db#4218]
At https://docs.yugabyte.com/latest/architecture/

The "core-functions" and "query-layer" panels are showing as un-rendered (X)HTML.  Viewed using Chrome 80 under macOS 10.14.6:

![image](https://user-images.githubusercontent.com/44789/79199263-a596b680-7e2c-11ea-8d15-fc8513f94c43.png)

Inspecting the page source, these panels are nested in `<pre>` and `<code>` tags.

There are a few console warnings/errors too, but I don't know if these are related:

* Found 2 elements with non-unique id `#search-input`
* pageConfig is not defined ReferenceError: pageConfig is not defined at initAnchorsAndFeedback (`https://docs.yugabyte.com/latest/architecture/:3570:13`)
* `[BP]` Storage connect error.

**Comment by ddorian** [comment]
Thank you @candlerb for reporting the issue.
I've filed #4220 to fix this.
