### ISSUE TITLE
yugabyted multi-local node cluster master UI down after leader master is shutdown

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4232]
Start a multi local node yugabyted cluster

```pkill -f yugabyted; rm -rf /tmp/ybd*
bin/yugabyted start --base_dir=/tmp/ybd_1_test --bind_ip=127.0.0.1 --ui=false
bin/yugabyted start --base_dir=/tmp/ybd_2_test --bind_ip=127.0.0.2 --ui=false --join=127.0.0.1
bin/yugabyted start --base_dir=/tmp/ybd_3_test --bind_ip=127.0.0.3 --ui=false --join=127.0.0.1
```

Kill the first node using `bin/yugabyted stop --base_dir=/tmp/ybd_1_test`
Go to master UI for the other 2 nodes. One of them will fail to redirect to master and not render.

**Comment by sanketkedia** [comment]
Fixed in D8459. Commit info: https://github.com/yugabyte/yugabyte-db/commit/977b45986995a3b66060fcb06d00934b0ea1e5af
