### ISSUE TITLE
[docdb] Using yb-admin to remove a dead master from the quorum is broken

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4248]
Listing all masters:
```I0417 14:52:29.347506 25915 mem_tracker.cc:249] MemTracker: hard memory limit is 26.316509 GB
I0417 14:52:29.347636 25915 mem_tracker.cc:251] MemTracker: soft memory limit is 22.369032 GB
Master UUID                      	RPC Host/Port        	State 	Role
dd895d89df57496ba2f4fe6c3222d2e1 	IP1:PORT 	TIMED_OUT 	UNKNOWN
04bc7f105ed4494ca72e6bf5185be4f9 	IP2:PORT 	NETWORK_ERROR 	UNKNOWN
5dee76e9f4cd470390f9ffb7d3b76995 	IP3:PORT  	NETWORK_ERROR 	UNKNOWN
6456a23f81cf4f5db5635f5bd4dd2d1d 	IP4:PORT  	ALIVE    	FOLLOWER
06ebbbb98ea3404aa986a06a480a3770 	IP5:PORT 	ALIVE    	FOLLOWER
024d2bdefa35470bb85dab382dac91fb 	IP6:PORT   	ALIVE    	LEADER
```

Trying to remove any of the bad ones (1-3) leads to a 15s timeout due to connect errors, but with non useful logging, ie: no info about where the error is coming from (yb-admin vs server)

This seems like something that used to work, so I'm worried it might be a recent regression.

**Comment by bmatican** [comment]
Was able to validate this:
- create a 3 node cluster
- stop 1 master
- try to remove the dead master

listing masters
```
./master/bin/yb-admin --master_addresses 10.150.0.85:7100 list_all_masters
Master UUID                      	RPC Host/Port        	State 	Role
451cba18084c4673851320f06055679b 	10.150.0.80:7100     	ALIVE    	FOLLOWER
38ec3db7e9414d5fa73401b522bee004 	10.150.0.85:7100     	ALIVE    	LEADER
1a202318b55b490a90efb115db20add8 	10.150.0.87:7100     	NETWORK_ERROR 	UNKNOWN
```
Trying to remove the dead master
```
./master/bin/yb-admin --master_addresses 10.150.0.85:7100,10.150.0.80:7100 change_master_config REMOVE_SERVER 10.150.0.87 7100
I0418 00:00:21.046206 27399 tcp_stream.cc:308] { local: 10.150.0.87:60776 remote: 10.150.0.87:7100 }:  Recv failed: Network error (yb/util/net/socket.cc:537): recvmsg error: Connection refused (system error 111)
Error: Network error (yb/util/net/socket.cc:537): Unable to change master config: recvmsg error: Connection refused (system error 111)```

@iSignal You should look into the yb-admin side of this, as it seems like a regression, pretty sure this used to work.

**Comment by iSignal** [comment]
The right command intended to be used here is 

`yb-admin --master_addresses 10.150.0.85:7100,10.150.0.80:7100 change_master_config REMOVE_SERVER 10.150.0.87 7100 1` 

where the **1** at the end means to delete by host port. 

If we don't specify the trailing 1, it seems to actually call GetMasterRegistration on the host:port specified for deletion in order to get its UUID and then request deletion by that UUID (we could instead do the right thing here by just asking the leader master for the uuid to host:port mapping and then remove this option completely to avoid such confusion).

**Comment by iSignal** [comment]
This should now work without the extra `1` for `use_hostport` at the end:

`
yb-admin --master_addresses 10.150.0.85:7100,10.150.0.80:7100 change_master_config REMOVE_SERVER 10.150.0.87 7100
`
