### ISSUE TITLE
[docdb] Make load balancer automatically skip deleted tables

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4250]
Previously, the load balancer would try to add a replica to a tablet with 0 replicas, if a delete table had failed in the middle of the operation (master leader failover)

```W0418 00:32:32.950471 26641 catalog_manager.cc:5074] Failed to send AddServer of tserver 216a155004234be2b35584f0cc8dbb04 to tablet 02a58a1cbd574bfe9c675c5a447a4f78 (table timelineididx [id=3ef23aec6bc74690bddd57d44ee8b355]): Not found (yb/master/catalog_entity_info.cc:133): Failed to reset TS proxy: No leader found for tablet 02a58a1cbd574bfe9c675c5a447a4f78 (table timelineididx [id=3ef23aec6bc74690bddd57d44ee8b355]) with 0 replicas: [].
```
This was experienced on:
```
Version 2.0.5.5
Commit 5ad28e75212a41d0b8002db976cc244cadae1f7b
```

However, since d45058e0369310fa0920070d98d9da35e30d7bc9, we should be rolling forward such broken deletes, such that on the new master leader, these tables and their tablets are correctly marked as deleted.

For future proofing though, we could still enhance the LB code to make sure it does not even look over any tables that are not running, just in case we have some regressions!

**Comment by bmatican** [comment]
Asked @rahuldesirazu to look into this. We have a test flag to repro this `simulate_crash_after_table_marked_deleting`, so should be easy to setup a test for it.
