### ISSUE TITLE
num_tablet_servers_live metric does not reset when a master's status changes from leader to follower

### ISSUE THREAD

**Issue by pmb311** [yugabyte/yugabyte-db#4262]
Impact appears to be simply cosmetic...this can be reproduced by triggering a master leader that does not involve restarting the active leader's yb-master process. Observed in v2.1.3.0.

**Comment by lbai94** [comment]
Hi, I want to contribute o yugabyte-db. Does this issue still need help? May I work on it？

**Comment by rahuldesirazu** [comment]
Hi @lbai94, when we have a leadership change on the sys catalog tablet, we have a callback path that gets triggered on the new master leader- See `CatalogManager::ElectedAsLeaderCb` which is called from `SysCatalogTable::SysCatalogStateChanged`. We can register a new callback and call it from this function on the two followers that takes care of resetting this metric. And this will allow us to easily extend functionality to do more work when a peer becomes a follower. Let me know if that makes sense or if you have any questions.

**Comment by lbai94** [comment]
Thanks @rahuldesirazu. I will let you know if I have other questions.

**Comment by SGZW** [comment]
> Hi @lbai94, when we have a leadership change on the sys catalog tablet, we have a callback path that gets triggered on the new master leader- See `CatalogManager::ElectedAsLeaderCb` which is called from `SysCatalogTable::SysCatalogStateChanged`. We can register a new callback and call it from this function on the two followers that takes care of resetting this metric. And this will allow us to easily extend functionality to do more work when a peer becomes a follower. Let me know if that makes sense or if you have any questions.

when raft become leader, consensus module will emit StateChangeReason::NEW_LEADER_ELECTED so that callback will capture this and do some work.

But currently, consensus module have no event about become follower,  can i use StateChangeReason::FOLLOWER_NO_OP_COMPLETE for "become follower event"?

**Comment by rahuldesirazu** [comment]
@SGZW Ah good point, it actually might be easiest to take care of this in CatalogManagerBgTasks. We have a bunch of metrics/load balancer logic we execute when we're the leader, and we can set metrics to 0 when we're the follower.
