### ISSUE TITLE
INSERT ... ON CONFLICT UPDATE ... Conflicts with higher priority transaction

### ISSUE THREAD

**Issue by dobesv** [yugabyte/yugabyte-db#4270]
Somehow this insert INSERT ... ON CONFLICT UPDATE reports a conflict with a higher priority transaction.  I am not using BEGIN or COMMIT to delineate transactions.

```
Operation failed. Try again.: 254c9af7-c4c9-4003-850b-8f77935374d8 Conflicts with higher priority transaction: 40b9fb35-4dce-4a59-b646-5679f6be7b61
Query: INSERT INTO public.\"syncState\" ( _id,\"createdAt\",cursor,destination,source,\"updatedAt\" ) VALUES ( $1,$2,$3,$4,$5,$6 ) ON CONFLICT( _id ) DO UPDATE SET \"createdAt\" = excluded.\"createdAt\",cursor = excluded.cursor,destination = excluded.destination,source = excluded.source,\"updatedAt\" = excluded.\"updatedAt\" WHERE \"syncState\".\"updatedAt\" < excluded.\"updatedAt\"
Args: mongodb.answers->yb.answers,Wed Apr 22 2020 04:45:16 GMT+0000 (Coordinated Universal Time),{\"_id\":\"tfRQfkxqjNrR5X8Tp\",\"updatedAt\":\"2017-11-09T15:17:41.118Z\"},yb.answers,mongodb.answers,Wed Apr 22 2020 04:45:16 GMT+0000 (Coordinated Universal Time)
```

**Comment by ddorian** [comment]
hi @dobesv 
There is an implicit BEGIN/COMMIT when you don't specify one.
Every query happens in a transaction.
In this case the transaction is in conflict with another one with more priority, and you have to retry it.

**Comment by dobesv** [comment]
@ddorian Since the operation only affects one row, how can it deadlock?  Won't it just wait and then do the update when the other transaction finishes?

**Comment by ndeodhar** [comment]
@dobesv We don't wait for other conflicting transactions to finish. Every transaction in YB has a priority assigned to it. When trying to write a row, if it finds that the row being written to is already locked by an existing, uncommitted transaction, then we resolve the conflict by aborting the lower priority transaction.

Note that we do have some optimizations that we are looking into for single statement transactions (will be available in ~2 months) wherein YB will internally retry single statement transactions and avoid surfacing conflict errors for those.

**Comment by dobesv** [comment]
Oh, interesting.  I clearly have a lot to learn about handling concurrency in Yugabyte, I thought it was going to operate like PostgreSQL.

**Comment by ndeodhar** [comment]
Here's some documentation on how transactions are handled in Yugabyte, if you're interested: https://docs.yugabyte.com/latest/architecture/transactions/distributed-txns/

**Comment by rkarthik007** [comment]
Hi @dobesv,

I am in the process of adding more information in the architecture section above - should be out next week or so, so please stay tuned for that. Would love your feedback on what else you would like to see.

This simple way of concurrency handling among transactions lets us get away without deadlock detection for now. We expect that as we add transparent retries for more and more query scenarios, we will invest in these efforts.
