### ISSUE TITLE
Wrong link in YEDIS documentation

### ISSUE THREAD

**Issue by lokesh1197** [yugabyte/yugabyte-db#4271]
In [Build an application using NodeJS](https://docs.yugabyte.com/latest/yedis/develop/client-drivers/yedis/nodejs/) page, under Prerequisites, the Quick start link is wrong.

Current link: https://docs.yugabyte.com/latest/yedis/develop/quick-start/
Actual link: https://docs.yugabyte.com/latest/yedis/quick-start/

**Comment by ddorian** [comment]
Thank you @lokesh1197 for reporting.
I've filed a pull request to fix it.
