### ISSUE TITLE
Slow single tablet scan for select count(*)

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4277]
Jira Link: [DB-1408](https://yugabyte.atlassian.net/browse/DB-1408)
We should investigate why docDB takes a long time to scan rows.

The test described below was done on AWS 3-node cluster (each node 4 vCPU).
Test case:
Create single column and single tablet table and add 10M rows
```
CREATE TABLE test(a int PRIMARY KEY) SPLIT INTO 1 TABLETS;
INSERT INTO test SELECT generate_series(1,10000000);
```

This will end up writing 10M rows to a single tablet.

Now, do a select count(*) of the table
```
yugabyte=# select count(*) from test; 
count   
---------- 
10000000
(1 row)
Time: 26938.984 ms (00:26.939)
```
Since we use prefetch 1024, this resulted in 9766 tserver RPCs.

To drill down deeper into how long it takes docdb to scan, lets limit RPC to 1.
I changed gflags on the cluster to these:
ysql_prefetch_limit=20000000 (20M)
retryable_rpc_single_call_timeout_ms=480000

Then, I ran select count(*) again and confirmed that tserver only received 1 RPC:
```
yugabyte=# select count(*) from test; 
count   
---------- 
10000000
(1 row)
Time: 24631.922 ms (00:24.632)
```
As can be seen, most of the time is spent in docdb scan.

In contrast, vanilla postgres finishes the scan in 786 ms!
```
postgres=# select count(*) from test; 
count   
---------- 
10000000
(1 row)
Time: 786.238 ms
```

**Comment by ndeodhar** [comment]
Also note that this is a single column table and will be unaffected by packed column storage as well.

**Comment by spolitov** [comment]
Such a statement would generate a single big transaction, that we currently don't handle nicely:
`INSERT INTO test SELECT generate_series(1,10000000);`

If our goal is to test read performance, then it is not the best option.

**Comment by ndeodhar** [comment]
I confirmed that `yb-ts-cli count_intents` was 0 before running the `SELECT count(*)` query.

You can run the same and confirm. If we think that it's due to intents, then we should confirm that theory.

**Comment by spolitov** [comment]
Even when `count_intents` reports 0, they could present in DB. Just marked as deleted, until compaction happens.

**Comment by ndeodhar** [comment]
Porting over conversation from slack:
neha: I ran the same test again after compacting the table but didn't see any difference in results. This is what I got:
```
yugabyte=# select count(*) from test;
  count   
----------
 10000000
(1 row)
Time: 25167.270 ms (00:25.167)
```

**Comment by mbautin** [comment]
It would be interesting to support the equivalent of count_intents but counting deleted records.

**Comment by bmatican** [comment]
257daa4428dcaef4886d7dcae6ec163006ef95b9 also helped with this effort.

**Comment by rthallamko3** [comment]
Iterator V2 changes planned as part of https://github.com/yugabyte/yugabyte-db/issues/13718 should help with scan performance too. Closing this as this is a DUP.
