### ISSUE TITLE
Remote bootstrap of very large tablets could fail

### ISSUE THREAD

**Issue by hectorgcr** [YugaByte/yugabyte-db#428]
We noticed remote bootstraps of several very large tablets (~180G) failed.

When a peer is receiving a tablet (during a remote bootstrap), the leader keeps sending remote bootstrap requests, but the response from the peer (tablet bootstrap already in progress) gets ignored, and the time the leader last heard from the peer never gets updated. Eventually the leader thinks that the peer has become unresponsive and kicks it out of the config.

We need to handle remote bootstrap responses the same way we handle other responses: if the peer is still alive, we need to update the last time we received the response even if the response is an error.

**Comment by kmuthukk** [comment]
Nice work @hectorgcr
