### ISSUE TITLE
High CPU usage and slow performance with default settings

### ISSUE THREAD

**Issue by AugerC** [yugabyte/yugabyte-db#4281]
Hello, 

First of all, i'm sorry if this doesn't belong here. I'm unaware if a mailing list exists. 

We want to deploy an application (Zabbix https://www.zabbix.com/ ) using yugabyte since both can use Postgres as a query layer. The idea is that the zabbix backend can be scalable based on our needs. 

I've been trying to run this application for a few days without success. I can start the application but the performance is bad and the virtual machines where yugabyte is running are with high load averages. 

Our deployment: 

 - 1 Load balancer with HAProxy ( IP: 10.0.0.10 )

 - 3 YB nodes ( IP: 10.0.0.11, 10.0.0.12, 10.0.0.13 )

All VM are equal: 
> 4 CPU
8GB RAM
60GB disk (non-ssd but with cache, see performance tests below)
Running ubuntu 18.04

```
~# uname -a
Linux LAB_YGDB_node01 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

We followed the installation tutorial on https://docs.yugabyte.com/latest/deploy/manual-deployment/

The start commands (on all nodes are the same):
```
cd /opt/yugabyte-2.1.4.0/ && \
                ./bin/yb-master --master_addresses 10.0.0.11:7100,10.0.0.12:7100,10.0.0.13:7100 \
                        --rpc_bind_addresses 10.0.0.11 \
                        --fs_data_dirs "/mnt/yb" \
                        --replication_factor=3 &

cd /opt/yugabyte-2.1.4.0/ && \
                ./bin/yb-tserver --tserver_master_addrs 10.0.0.11:7100,10.0.0.12:7100,10.0.0.13:7100 \
                        --rpc_bind_addresses 10.0.0.11 \
                        --enable_ysql \
                        --ysql_timezone "CET" \
                        --ysql_log_statement all \
                        --fs_data_dirs "/mnt/yb" &
```

All nodes start correctly, a leader is set and we can see the admin webpages on 10.0.0.11:7000 and 10.0.0.11:9000. Load average and VM performance is fine at this point.

We create the database: 
```
create user zabbix with encrypted password 'PASSWORD';
create database zabbix with owner zabbix;
```

Now, when we start the application pointing to the load balancer (or to a node, the behavior is the same) it starts creating the tables needed (about 150 tables). During this process the load average of the VM jumps to almost 10 while the application works (i assume this is correct since creating a database in yugabyte takes 10 seconds normally and it would be normal to request to queue). 

Having the application started the solution works, but very slow, which is not expected since the tables are created but mostly empty. This is the status of the VM:
![imagen](https://user-images.githubusercontent.com/10826865/80090617-14c48700-8560-11ea-89c8-67e989a4de14.png)

> It is not present on the screenshot but the processes consuming CPU are the tserver (200-300%) and master (3-4%)

I don't think the only cause of this behavior is the disk (using dd i can see 355 MB/s speeds writes). Running iostat while the load average is high (disk is sdb):
![imagen](https://user-images.githubusercontent.com/10826865/80091860-1f801b80-8562-11ea-9c57-3d0441e61a4b.png)

Checking the log files, we just see ocasionally:
```
W0420 07:11:53.405629 20947 log.cc:709] Time spent Fsync log took a long time: real 0.385s      user 0.000s     sys 0.000s
W0420 07:11:54.562594 20947 log.cc:709] Time spent Fsync log took a long time: real 0.355s      user 0.000s     sys 0.000s
W0420 07:12:04.684113 20947 log.cc:709] Time spent Fsync log took a long time: real 0.055s      user 0.000s     sys 0.000s
```

Do you know how to address this? Where we can look to gather more info? We tested the same application vs a standalone postgresql and the performance is way better (without data), probably because of the high load average. 

If you need more data, please let me know.

Thanks a lot.

**Comment by ddorian** [comment]
hi @AugerC 

Can you paste a screenshot of `7000/tablet-servers` on any of the servers where a master resides ?

**Comment by ddorian** [comment]
Creating databases & tables is heavier in YugabyteDB because of the distributed nature. In postgresql everything happens in 1 process/server, while here it happens in 6 processes (3 yb-tserver & yb-master), and multiple tablets are created for each table, each one adding overhead and time.

>  60GB disk (non-ssd but with cache, see performance tests below)

SSD drives are required https://docs.yugabyte.com/latest/deploy/checklist/#disks. While you may have sequential io, what's your random iops ?

**Comment by AugerC** [comment]
Hi @ddorian 

About the delay on the table creation, i'm not very worried, since it is a one-time operation after all. It takes about half an hour to create the 150 tables needed with the default content.

About the disks, i understand that they are required, since a database has the most usage out of them. We may plan on move the cluster to SSD at some point but we wanted to test first how it works. Even if the disks are HDD, they are not very slow: 
```
# Write Speed
root@LAB_YGDB_lb01:~# dd if=/dev/zero of=/test1.img bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 3.02468 s, 355 MB/s


# Access latency
root@LAB_YGDB_lb01:~# dd if=/dev/zero of=/test2.img bs=512 count=1000 oflag=dsync
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 4.40695 s, 116 kB/s
```

This is the information you needed? 

The screenshots you requested:
![imagen](https://user-images.githubusercontent.com/10826865/80118615-f0c96b80-8588-11ea-8b70-d8d38728acdc.png)

This is the load of one of the nodes (the rest are the same) about 10-20 minutes after the bootstrap of the application finished. Nothing else apart from yugabyte runs on that vm's:
![imagen](https://user-images.githubusercontent.com/10826865/80118704-135b8480-8589-11ea-99d7-1031d9100322.png)


Thanks again.

Regards.

**Comment by ddorian** [comment]
@AugerC the problem is the big number of tablets. Each tablet has overhead and they add up in cpu usage.

There are some ways to fix this:

1. Use colocated tables https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_database/#colocated
2. Use `SPLIT INTO` https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_table/#split-into to specify 1 tablet when creating tables https://docs.yugabyte.com/latest/reference/configuration/yb-master/#ysql-flags
3. Set `--yb_num_shards_per_tserver` gflag in tserver 

Can you try with them and report back ?

**Comment by dobesv** [comment]
It's probably worth pointing out that although YugabyteDB is protocol compatible with PostgreSQL, it cannot simply be used "as if" it were PostgreSQL.  It is not "behavior compatible" in various ways, like locking for example.

**Comment by AugerC** [comment]
> @AugerC the problem is the big number of tablets.
> 
> Each table in YugabyteDB is split into tablets, and each of them is also replicated and distributed over the cluster. Thus when creating a large number of tables/indexes the number of tablets can become very large.
> And each tablet has overhead in cpu usage which adds up when there are 1000+ tablets.
> 
> There are some ways to lower the number of tablets per-table:
> 
>     1. Use colocated tables https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_database/#colocated
> 
>     2. Use `SPLIT INTO` https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_table/#split-into to specify 1 tablet when creating tables https://docs.yugabyte.com/latest/reference/configuration/yb-master/#ysql-flags
> 
>     3. Set `--yb_num_shards_per_tserver` gflag in tserver
> 
> 
> Can you try with them and report back ?

Hi,

I tried `--yb_num_shards_per_tserver` and that worked wonders, thanks!

It works much better now, we'll continue testing since what @dobesv says is right. 


I'm closing this now, thanks!

**Comment by ddorian** [comment]
@AugerC 
Wanted to correct a mistake. The right option is `--ysql_num_shards_per_tserver` and NOT `--yb_num_shards_per_tserver`. I've also updated my original answer above.
