### ISSUE TITLE
index backfill: fix SysTabletsEntryPB.backfilled_until for colocation

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4287]
`SysTabletsEntryPB.backfilled_until` checkpoints how far an index backfill has gone for a tablet.  This is a problem for colocated tables.  Here is a scenario:

1. `CREATE INDEX a`
1. `CREATE INDEX b`
1. both backfill at same time: `SysTabletsEntryPB.backfilled_until` is shared for both indexes

@amitanandaiyer suggests that `SysTabletsEntryPB.backfilled_until` can change type from `bytes` to `map<bytes, bytes>`, mapping table ids to encoded dockey.

**Comment by amitanandaiyer** [comment]
@jaki  Is this still relevant after https://github.com/yugabyte/yugabyte-db/commit/9ea4ccd39b1e3ba53b0f57face75442cb9a48799?

 If not, can you close this? Thanks.

**Comment by jaki** [comment]
This `backfilled_until` issue does look resolved.
