### ISSUE TITLE
[YSQL] Transparently restart single row write transactions

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4291]
Similar to read restarts, we should transparently restart single row writes (INSERTS / UPDATES) and avoid surfacing transaction conflict errors to user applications.

**Comment by Amandeepsinghghai** [comment]
Hi,
I assume the same would fix has to be done for DELETES as well? Got the following error when I tried to delete
``` 
2020/07/25 09:20:59 models: unable to delete from users: pq: Operation failed. Try again.: Multiple homogeneous errors: [Operation failed. Try again. (yb/docdb/conflict_resolution.cc:485): Value write after transaction start: { physical: 1595668859244924 } >= { physical: 1595668859237551 } (transaction error 3)]
```

**Comment by tchadwick** [comment]
With this issue closed, can anyone tell me which version/release the fix for this will be in?
