### ISSUE TITLE
FATAL when doing full scan in YSQL in parallel with SqlInserts workload using debug build

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#4297]
Jira Link: [DB-2505](https://yugabyte.atlassian.net/browse/DB-2505)
Steps to reproduce:
- Create local cluster and run workload: 
```
./bin/yb-ctl --rf=3 create --num_shards_per_tserver=1
java -jar ~/code/yb-sample-apps/target/yb-sample-apps.jar --workload SqlInserts --nodes 127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --num_threads_read 0 --num_threads_write 4 --nouuid --num_unique_keys 30000 --num_writes 30000
```

- Run in another term session:
```
./bin/psql -d postgres -c 'select count(*) from postgresqlkeyvalue;'
```

it will wait and then tservers will crash with:
```
F0422 14:32:56.271672 15733 docdb.cc:827] Check failed: key_data.same_transaction || iter->read_time().global_limit >= write_time.hybrid_time() Bad key: SubDocKey(DocKey(0x2d53, ["key:5335"], []), [SystemColumnId(0)]), global limit: { physical: 1587565976194734 }, write time: { physical: 1587565976245346 }
```

Only happens in debug build.

**Comment by bmatican** [comment]
Hey @spolitov , since you're actively looking at the read path and iterator improvements, do you think you can take a look at this? Seems like some DCHECK expectations are breaking.

**Comment by bmatican** [comment]
I believe we've since removed this code path, I can only find references to it on the redis read path.
