### ISSUE TITLE
Describe table should include if transaction is enabled for that table

### ISSUE THREAD

**Issue by rameshpoti** [YugaByte/yugabyte-db#430]
describe table does not show if transaction is enabled. A query has to be issued against system_schema.tables to find it. It will be useful if output of describe can include transaction is enabled for the table.

select keyspace_name, table_name, transactions from system_schema.tables
where keyspace_name='banking' AND table_name = 'accounts';

**Comment by robertpang** [comment]
Fixed in cqlsh commit [8f2b5af](https://github.com/YugaByte/cqlsh/commit/8f2b5aff31175879899685f8b26d9da8733fd377), release  [v3.10-yb-3](https://github.com/YugaByte/cqlsh/releases/tag/v3.10-yb-3).
