### ISSUE TITLE
[Platform] Onprem node add should just look for any available node

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#4321]
When we try to add a new node to the universe in which we had already removed a node and released node. Our add node workflow is trying to look for a node with similar name and fails, Instead we should basically pick a available node and update its node_details and proceed with provisioning that node.

**Comment by WesleyW** [comment]
Fixed related issue in #4320 . To add a node, user will still have to go through the edit universe form and increase the number of nodes.
