### ISSUE TITLE
[YSQL] remove physical files for drop temp table

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4332]
Jira Link: [DB-2371](https://yugabyte.atlassian.net/browse/DB-2371)
It seems that dropping temporary tables does not remove the physical files associated with them.

```sql
CREATE TEMP TABLE t (i int);
DROP TABLE t;
```

```sh
ls /path/to/cluster_data/node-1/disk-1/pg_data/base/<dboid>/
```

Exiting the psql session and using `DISCARD TEMP` don't help.  This may be related to code like the following:

```c
	/*
	 * Schedule physical removal of the files (if any)
	 * If YugaByte is enabled, there aren't any physical files to remove.
	 */
	if (!IsYugaByteEnabled() &&
		userIndexRelation->rd_rel->relkind != RELKIND_PARTITIONED_INDEX)
		RelationDropStorage(userIndexRelation);
```

`IsYBRelation` may be more appropriate than `IsYugaByteEnabled`.

**Comment by sidjha1** [comment]
Issue resolved by commit fd6b58d
