### ISSUE TITLE
[docs] Document how to upgrade Replicated

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4342]
Document how to upgrade Replicated in a YW install. Let's add this here -
https://docs.yugabyte.com/latest/manage/enterprise-edition/

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-484

**Comment by lizayugabyte** [comment]
The Aha! link requires login credentials that we don't have

**Comment by lizayugabyte** [comment]
@rao-vasireddy @ddhodge I believe this has been documented in https://docs.yugabyte.com/latest/yugabyte-platform/upgrade/upgrade-yp-replicated/

**Comment by lizayugabyte** [comment]
This is already documented here: https://docs.yugabyte.com/latest/yugabyte-platform/upgrade/upgrade-yp-replicated/
Closing the ticket as "done"
