### ISSUE TITLE
[docs] Update backup/restore docs with info on the new table+index restore mode

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4343]
We now support automatically backing up a table and its index and same for restoring it. We should probably update our docs about this.

Moreover, the yb-admin interface now features snapshot and restoration IDs and we should clarify what they are and what you should wait on.

**Comment by ddorian** [comment]
This is documented in https://docs.yugabyte.com/latest/manage/backup-restore/snapshot-ysql/
