### ISSUE TITLE
Add oids for tables/namespaces to catalog manager, allow to retrieve tables by both oids and databases/names

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#435]
PostgreSQL databases map to YB namespaces.
PostgreSQL tables map to YB tables.
Schemas don't have a corresponding entity in YB.

The reason for different treatment of postgres databases and schemas in YB is that we'll potentially need to support copying databases from template1 (or template 0) and that requires YB to have knowledge of databases (as namespaces). 

Therefore the proposal is to allow to use oids as keys in YB for tables and databases/namespaces, and still keep the names around internally.

There is a YBTableName class, currently (namespace_name, table_name).
This could become union { OID oid; struct { string namespace_name, string table_name } }
If OID is specified, it takes precedence (or namespace / table name can't even be specified together with oid).

Another thing to consider is we could store OIDs instead of UUIDs for these objects.
We could use some version / variant of the UUID according to https://en.wikipedia.org/wiki/Universally_unique_identifier to guarantee there are no collisions with randomly-generated UUIDs, and to allow YugaWare to use these UUIDs seamlessly.

From ENG-3510 (potentially outdated comment)

We might not have to worry about the schemas if PostgreSQL tables are identified by OIDs in YugaByte. Then the postgres layer will resolve the (schema, table_name) pair into an OID and give that to the YB layer, and the YB layer does not have to know anything about schemas at all.

One complication with the above is that we have maps from (database, table_name) in system catalog, and there could be ambiguity for PostgreSQL tables.

**Comment by m-iancu** [comment]
This was already addressed largely or fully in: efd44a194d887a47b91eca9a75ec55cda598227e.
