### ISSUE TITLE
[docdb] Add flag for yb-admin list_snapshots to not show fully RESTORED entries

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4351]
This list could grow large, if doing restore frequently.
```
No snapshots
Restoration UUID                        State
ada72c63-b760-4fea-8a8a-78ea24a424d7    RESTORED
```

**Comment by libingye816** [comment]
Hi @bmatican. I would like to solve this issue. However, how many items do you want if a full list is too big? In addition, I didn't find `list_snapshots` command in yb-admin_client.cc. Where is it?

**Comment by bmatican** [comment]
```
git grep list_snapshots | grep -v docs
15:ent/src/yb/tools/yb-admin_cli_ent.cc:      "list_snapshots", " [SHOW_DETAILS]",
16:managed/devops/bin/yb_backup.py:        yb_admin_args = ['list_snapshots']
17:src/yb/tools/yb-admin-test.cc:          "list_snapshots", "SHOW_DETAILS"),
```
See the `ent` directory. That directory is a relic of a previous era, and we're slowly trying to get rid of...

As for limits on number of items, I think at the moment, we do not limit the output. We can probably still preserve that behavior for now.

**Comment by libingye816** [comment]
Hi @bmatican, I have submitted PR.

**Comment by OlegLoginov** [comment]
Fixed by the commit above.
