### ISSUE TITLE
[docdb] Multi touch cache not being used for YSQL workloads.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#4379]
Noticed this issue with YCSB runs for larger workloads that the cache usage was constant with about ~3GB being used. This was independent of the data set size since we got the same results for 50 mil,450 mil or 1 Billion records.

![Screenshot from 2020-05-02 17-25-34](https://user-images.githubusercontent.com/7224861/81005605-19f8c000-8e03-11ea-89f6-a4b07436352f.png)

According to @kmuthukk, the caching logic is designed to be elastic and single touch needs to borrow space from the multi touch pool (if there is room) in this scenario.

This can be reproduced by doing a 50 mil run followed by running any workload. WorkloadC is a good choice.

**Comment by bmatican** [comment]
Traced some of this code yesterday with @psudheer21 and we noticed this in the cache Insert path:
```
    // Free the space following strict LRU policy until enough space
    // is freed or the lru list is empty.
    // Check if there is a single touch cache.
    SubCacheType subcache_type;
    if (FLAGS_cache_single_touch_ratio == 0) {
      e->query_id = kInMultiTouchId;
      subcache_type = MULTI_TOUCH;
    } else if (FLAGS_cache_single_touch_ratio == 1) {
      // If there is no multi touch cache, default to single cache.
      subcache_type = SINGLE_TOUCH;
    } else {
      subcache_type = table_.GetSubCacheTypeCandidate(e);
    }
    EvictFromLRU(charge, &last_reference_list, subcache_type);
```

Notice the `EvictFromLRU` call, which traces to:
```
void LRUCache::EvictFromLRU(size_t charge, LRUHandleDeleter* deleted,
                            SubCacheType subcache_type) {
  LRUSubCache* sub_cache = GetSubCache(subcache_type);
  while (sub_cache->Usage() + charge > sub_cache->Capacity() && !sub_cache->IsLRUEmpty()) {
```

Based on this, I'm not sure if this code is expected to allow the caches to take more space than their capacity.
cc some other folks that might know more @amitanandaiyer @spolitov @ttyusupov

**Comment by kmuthukk** [comment]
There are two issues here to figure out in this order of priority:

1) Why are index/bloom blocks etc. (which one would expect to get multiple touches) -- not getting promoted from single-touch to multi-touch pool?

2) Why does single-touch not grow to consume multi-touch memory if multi-touch pool is not using its full allotted space?

---

**Comment by psudheer21** [comment]
I think I have figured out the issue for YB not being able to use the multi touch cache.

With YSQL and hash I was noticing that the entry was not bumping up into  the multi touch even with multiple reads of the same row. It was still being retained in the single touch pool.

The cache promotes an entry into the multi touch pool only when the query id is a new one from when the entry was created to avoid the same query bumping the entry into multi-touch pool:
    if (FLAGS_cache_single_touch_ratio < 1 && e->GetSubCacheType() != MULTI_TOUCH &&
        e->query_id != query_id) {
........./* code to promote the entry*/
}

In the above code the query_id was always 0 and the above condition was never true and hence the entries were always in the single touch pool.
The query id for YSQL comes from the 'stmt_id' of 'PgsqlReadRequestPB' which was never populated in our code. 
For YCQL the query_id comes from 'query_id' field of 'QLReadRequestPB' and was populated properly when the proto is created in yb_op.cc.

The fix is to ensure that the stmt_id is populated for the YSQL code path.
