### ISSUE TITLE
[YSQL] Slower data loading for table with 2 column PK vs 1 column PK

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4381]
Jira Link: [DB-1327](https://yugabyte.atlassian.net/browse/DB-1327)
Observed this while loading TPCC dataset (yb-ctl RF=1, 1 warehouse):
Note that this is while loading data without any foreign key constraints.
```
14:26:25,428 (TPCCLoader.java:160) INFO  - Loading items
14:26:30,734 (TPCCLoader.java:212) INFO  - Loaded 100000 items
14:26:30,759 (TPCCLoader.java:269) INFO  - Loaded warehouse 1
14:26:30,760 (TPCCLoader.java:291) INFO  - Loading stock for warehouse 1
14:26:56,094 (TPCCLoader.java:347) INFO  - Loaded 100000 stock for warehouse 1
```

As seen above, loading 100K rows into `item` table took ~5 seconds while loading 100K rows into `stock` table took ~25 seconds.
Difference between the two tables:
1. item has 5 columns whereas stock has 17 columns.
2. item has a single column PK whereas stock has 2 column PK.

If we change stock table to use a single column PK : We can do this by removing warehouse ID from PK and loading data for 1 warehouse, then the time reduces from 25 sec to 16 seconds.

```
14:45:21,045 (TPCCLoader.java:160) INFO  - Loading items
14:45:26,498 (TPCCLoader.java:212) INFO  - Loaded 100000 items
14:45:26,525 (TPCCLoader.java:269) INFO  - Loaded warehouse 1
14:45:26,526 (TPCCLoader.java:291) INFO  - Loading stock for warehouse 1
14:45:42,370 (TPCCLoader.java:347) INFO  - Loaded 100000 stock for warehouse 1
```

pg_stat_statements view for the two cases:
For 2 column PK for stock:
```
tpcc=# select rows, calls, mean_time from pg_stat_statements where query ilike 'insert into stock%';
 rows  | calls |    mean_time     
-------+-------+------------------
    32 |     1 |         6.836469
 99968 |   781 | 26.7685045787452
(2 rows)

```

For 1 column PK for stock:
```
tpcc=# select rows, calls, mean_time from pg_stat_statements where query ilike 'insert into stock%';
 rows  | calls |    mean_time    
-------+-------+-----------------
 99968 |   781 | 14.571139028169
    32 |     1 |        3.893012
(2 rows)

```

**Comment by ndeodhar** [comment]
Actually, the comparison with stock using 1 column is not very valid because in the 1 column PK case, the writes will get distributed across 2 tablets, whereas in the original case, all writes for stock will go to a single tablet.

**Comment by rthallamko3** [comment]
Packed Row improvement should address this. It can be enabled by ysql_enabled_packed_row gflag.
