### ISSUE TITLE
Expose raw file sizes in UI.

### ISSUE THREAD

**Issue by vitsai** [YugaByte/yugabyte-db#439]
Today, we expose on the http://<tablet-server>:9000/metrics the rocksdb_total_sst_file_size metric for each tablet. This is the compressed size of the on-disk files.

This is then rolled up for each TS and also exposed via yb-master's http://yb-master:7000/tablet-servers under the "Total SST File Sizes" column.

It would be very useful to show the raw (uncompressed) size of the data as an additional column as this will be good indicator of the benefits of prefix compression + on-disk compression that the system does under the covers.

**Comment by kmuthukk** [comment]
Fixed via https://github.com/YugaByte/yugabyte-db/commit/5842ed619830c9216837a93eb33355d07f8e9ed4
