### ISSUE TITLE
Enhance tablet server display to sort by UUID

### ISSUE THREAD

**Issue by vitsai** [YugaByte/yugabyte-db#440]
In the master side /tablet-servers endpoint, we currently display all TS together, as well as some of their placement information (cloud, region, zone). However, each TS also currently has a flag called placement_uuid, which is normally set from YW, to dictate which group it belongs to, as far as LB is concerned. This is primarily used now to split between live vs async replica nodes, so we can have them in the same CLOUD.REGION.ZONE and not get the LB confused.

This flag is made available from the TSDescriptor interface and we could use the list of all TS descriptors to generate the mapping in the UI before display separate blocks of TS, each under its own placement_uuid group.

**Comment by kmuthukk** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/0186764056ed712c0623815064f94b17541247b2
