### ISSUE TITLE
Replace the deprecated flag `start_pgsql_proxy` in `tserver/conf/server.conf`

### ISSUE THREAD

**Issue by thinknirmal** [yugabyte/yugabyte-db#4403]
Jira Link: [DB-2538](https://yugabyte.atlassian.net/browse/DB-2538)
The `tserver/conf/server.conf` from the Cloudformation installation has the deprecated flag `--start_pgsql_proxy`. Should be replaced with `--enable_ysql`.

**Comment by schoudhury** [comment]
thanks for bringing this to our attention @thinknirmal. in fact, even the enable_ysql flag is no longer needed because ysql is default on starting the 2.1 release.

**Comment by thinknirmal** [comment]
Good to know @schoudhury. Thank you.
