### ISSUE TITLE
[YSQL] Support ALTER COLUMN type that does not require on-disk changes

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4424]
We don't support `ALTER COLUMN type` today. The main reason for this is that altering data type may require changing on-disk data for existing rows. However, there are some variants that don't require on-disk changes. For example, changing column type from `varchar(50)` to `varchar(255)`. We should add support for such changes.

**Comment by hulien22** [comment]
Closed by ac0eb93.
