### ISSUE TITLE
Fix the CREATE ROLE syntax on documentation

### ISSUE THREAD

**Issue by thinknirmal** [yugabyte/yugabyte-db#4435]
Documentation section:
https://docs.yugabyte.com/latest/secure/authentication/ysql-authentication/#create-a-user-with-superuser-status

Wrong Syntax:
`CREATE ROLE admin WITH LOGIN SUPERUSER PASSWORD = 'PasswdForAdmin';`
Correct Syntax:
`CREATE ROLE admin WITH LOGIN SUPERUSER PASSWORD 'PasswdForAdmin';`

**Comment by kmuthukk** [comment]
@ddorian -- could you please confirm above and update docs as appropriate.

**Comment by ddorian** [comment]
@thinknirmal thank you for the issue and yes the syntax is wrong. That syntax is used in YCQL.

On the same page there is the correct syntax: https://docs.yugabyte.com/latest/secure/authentication/ysql-authentication/#create-a-regular-user

Created pull request for this issue.
