### ISSUE TITLE
[docs] YSQL: Document window functions

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4447]
Document postgresql window functions that are supported in YSQL:
https://www.postgresql.org/docs/current/tutorial-window.html

**Comment by bllewell** [comment]
I documented window functions over a series of PRs and completed the work the with [PR #4864](https://github.com/yugabyte/yugabyte-db/pull/4864) on on 29-Jun-2020.

See the section [Window functions](https://docs.yugabyte.com/preview/api/ysql/exprs/window_functions/).

Sorry that I forgot to close this issue.
