### ISSUE TITLE
Does serial or sequence ensure the uniqueness of data?

### ISSUE THREAD

**Issue by DebadityaMondal** [yugabyte/yugabyte-db#4453]

**Comment by DebadityaMondal** [comment]
We want to migrate from mysql database. We found 2 alternatives in YugabyteDB (Postgres) for a mysql AUTO_INCREMENT ()
1. serial
2. sequence
For some reason we are not like to use UUID. In that case does serial or sequence ensure the uniqueness of data? (we have 6 nodes)

**Comment by ddorian** [comment]
Hi @DebadityaMondal 

Actually serial/bigserial create a sequence underneath and use that to generate unique ids.
Sequences do generate unique values even in distributed systems. 

You also need to use caching for better performance by lowering number of rpc to generate new values: https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_sequence/#cache

The uniqueness is enforced on the database side by a primary-key, unique-index, constraint. In this case it's also better for the `id` column to be the primary key. (unless your schema is more complex we can revisit).

So, use sequence with a big cache, and make the `id` a primary key.
