### ISSUE TITLE
Can not create database on local 1-node cluster

### ISSUE THREAD

**Issue by ricemaster** [yugabyte/yugabyte-db#4477]
Hi,
I'm trying to create a database `create database gtest;` in my VMWare virtual machine which is a 1-node cluster created through `./bin/yb-ctl create` followed the [3. Explore YSQL](https://docs.yugabyte.com/latest/quick-start/explore-ysql/#linux).

I'm using v2.1.6.0. 
This virtual server has 1 CPU, 2 Core and 4G RAM, higher than the [Minimum requirement](https://docs.yugabyte.com/latest/deploy/checklist/#hardware-requirements)

But I always got two errors below,
```
ERROR:  Timed out: Write(tablet: 00000000000000000000000000000000, num_ops: 1, num_attempts: 9, 
txn: 1b50e770-6e9a-4704-89a4-baa95cbdbddd) passed its deadline 271.062s (passed: 65.314s): 
Remote error (yb/rpc/outbound_call.cc:440): Service unavailable (yb/tserver/tablet_service.cc:331): 
Soft memory limit exceeded (at 97.42% of capacity), score: 0.00
```
or
```
ERROR:  Timed out: Timed out waiting for Namespace Creation
```
Is there anything I did it wrong?

**Comment by iSignal** [comment]
@ricemaster : thanks for reporting this issue! We are tracking a fix for this issue at https://github.com/yugabyte/yugabyte-db/issues/4139

In the meantime, please retry the yb-ctl create with the following cmd line:

`bin/yb-ctl destroy && bin/yb-ctl start --master_flags='default_memory_limit_to_ram_ratio=0.35'`

**Comment by ricemaster** [comment]
Hi @iSignal , it worked, thank you so much.

![1](https://user-images.githubusercontent.com/10449002/82103413-7930cb80-9745-11ea-95bf-93fbfe5c0623.png)

**Comment by tweenietomatoes** [comment]
Same issue.

ERROR:  Timed out: Timed out waiting for Namespace Creation
