### ISSUE TITLE
[YCQL] Add JSONB codec for DDL creation

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4481]
For DDL creation with Spring Data Cassandra, it looks like we'll need to add JSONB datatype and the required codec in the driver.

**Comment by ajcaldera1** [comment]
For DDL creation with Spring Data Cassandra, it looks like we'll need to add JSONB datatype and the required codec in the driver.

**Comment by nchandrappa** [comment]
Basically `Spring-Data-Cassandra` is generating the DDL based on the `DataType.JSON` value in the YCQL java driver. Driver specifies the enum value  as `JSON` and not `JSONB `, hence Spring App throws the following error.
```
Invocation of init method failed; nested exception is org.springframework.data.cassandra.CassandraQuerySyntaxException: Query; CQL [CREATE TABLE IF NOT EXISTS customer (address json, emailid text, id text, name text, PRIMARY KEY (id));]; Invalid SQL Statement. syntax error, unexpected JSON, expecting ')' or ','
CREATE TABLE IF NOT EXISTS customer (address json, emailid text, id text, name text, PRIMARY KEY (id));
                                             ^^^^
```
We'll need to fix the ENUM vaue in `DataType.java` to match the data type expected on the server side which is `JSONB`.

**Comment by nchandrappa** [comment]
`cassandra-java-driver:3.8.0-yb-5` released to fix JSONB column type creation using schema builder.
