### ISSUE TITLE
Remove the NFS-based shared third-party directory support on CentOS

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4484]
Now that we have a way to download third-party dependencies from releases at https://github.com/yugabyte/yugabyte-db-thirdparty, the NFS-based shared third-party directory approach should be disabled by default on CentOS.

**Comment by svarnau** [comment]
Looks like centos is already avoiding NFS-shared thirdparty dir by setting YB_DOWNLOAD_THIRDPARTY in build-support/jenkins/build-and-test.sh

We can't rip out the NFS-shared option altogether, since it is still being used for mac builds.
