### ISSUE TITLE
Issue error when creating a secondary index on a table with existing data

### ISSUE THREAD

**Issue by robertpang** [yugabyte/yugabyte-db#449]
Currently, when a secondary index is created on a table, it does not backfill the index for the existing data in the table. The user is required to ensure the table is empty before creating the index. We have a plan to support the backfilling of the index (https://github.com/YugaByte/yugabyte-db/issues/448). Until that is supported, YugaByte DB should issue error when an index is created on a table with existing data.

**Comment by amitanandaiyer** [comment]
Going down the route of implementing backfill #448 . Will not be getting to this.
