### ISSUE TITLE
[Platform] Provide method for expiring old backups

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4493]
On the YW platform, there is a desire to trim old backups from the Yugaware store as well as the backup from the storage location. This should be initially offered as an API so that customers can call it from an external source. Later the backup scheduler in YW can run a retention trimming script.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-426

**Comment by Arnav15** [comment]
Have completed the code change for both devops as well as platform. Need to add unit tests as well as do manual testing. Will push the diff review shortly after.

**Comment by rao-vasireddy** [comment]
We also need the UX flow for managing this.
