### ISSUE TITLE
[docdb] Allow overflow of single-touch cache if multi-touch cache is not consuming space.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#4495]
Currently single-touch cache is given a fixed allocation of the total cache(20%) and multi-touch uses the rest (80%).

However, we should allow the single touch to grow if multi touch cache is not using its allocated quota. This will allow us to use the cache for single touch entries until we have multiple accesses and the multi-touch cache grows. 

This overflow should be governed by a knob (GFLAG) allowing us to still have a hard limit on how much can the single touch cache can burst into the multi-touch allocated space.

**Comment by kmuthukk** [comment]
@psudheer21 --

<< we should allow the single touch to grow if multi touch cache is not present. >>

I don't think it is a 0 or 1 based on whether mutlti-touch is present or not. The intent should be that if multi-touch pool is not using its allotted quota, then single-touch pool is allowed to burst/use that.

Please note that this overall enhancement is nice to have, and not as hi-pri.
