### ISSUE TITLE
yb_build.sh build failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by nshigit** [yugabyte/yugabyte-db#4510]
```
YB_USE_COTIRE CMake/environment variable not set to '1', skipping cotire
Including '/home/nshi/workspace/yugabyte-db/ent/src/yb/server/CMakeLists-include.txt' into '/home/nshi/workspace/yugabyte-db/src/yb/server/CMakeLists.txt'
Including '/home/nshi/workspace/yugabyte-db/ent/src/yb/tserver/CMakeLists-include.txt' into '/home/nshi/workspace/yugabyte-db/src/yb/tserver/CMakeLists.txt'
Including '/home/nshi/workspace/yugabyte-db/ent/src/yb/master/CMakeLists-include.txt' into '/home/nshi/workspace/yugabyte-db/src/yb/master/CMakeLists.txt'
Including '/home/nshi/workspace/yugabyte-db/ent/src/yb/integration-tests/CMakeLists-include.txt' into '/home/nshi/workspace/yugabyte-db/src/yb/integration-tests/CMakeLists.txt'
Including '/home/nshi/workspace/yugabyte-db/ent/src/yb/tools/CMakeLists-include.txt' into '/home/nshi/workspace/yugabyte-db/src/yb/tools/CMakeLists.txt'
Added shared library dependency yb_pgbackend: /home/nshi/workspace/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/lib/libyb_pgbackend.so
-- Found BISON: /usr/bin/bison (found version "3.0.4")
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
Including '/home/nshi/workspace/yugabyte-db/ent/src/yb/cdc/CMakeLists-include.txt' into '/home/nshi/workspace/yugabyte-db/src/yb/cdc/CMakeLists.txt'
Total tests: 327, included: 327, excluded: 0
Total non-test executables: 28, included: 28, excluded: 0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nshi/workspace/yugabyte-db/build/release-gcc-dynamic-ninja
[2020-05-19T20:49:00 yb_build.sh:408 run_cxx_build] Running /usr/bin/ninja in /home/nshi/workspace/yugabyte-db/build/release-gcc-dynamic-ninja
+ /usr/bin/ninja -j32
ninja: error: 'postgres/lib/libyb_pgbackend.so', needed by 'lib/libyb_docdb.so', missing and no known rule to make it
```

**Comment by nshigit** [comment]
yb_build.sh --make release 

( cd "/home/nshi/workspace/yugabyte-db/build/release-gcc-dynamic/src/yb/util" && YB_THIRDPARTY_DIR=/home/nshi/workspace/yugabyte-db/thirdparty /usr/bin/g++ -Dyb_util_EX$
ORTS -I/home/nshi/workspace/yugabyte-db/build/release-gcc-dynamic/src -I/home/nshi/workspace/yugabyte-db/ent/src -I/home/nshi/workspace/yugabyte-db/src -isystem /home/n$
hi/workspace/yugabyte-db/thirdparty/installed/uninstrumented/include -isystem /home/nshi/workspace/yugabyte-db/thirdparty/installed/common/include -Werror -fno-strict-a$
iasing -msse4.2 -Wall -Wno-sign-compare -Wno-deprecated -Winvalid-pch -pthread -DBOOST_BIND_NO_PLACEHOLDERS -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DROCKSDB_PLATFORM_$
OSIX -DROCKSDB_USING_THREAD_STATUS=0 -DBOOST_ERROR_CODE_HEADER_ONLY -march=ivybridge -mcx16 -DYB_COMPILER_TYPE=gcc -DYB_COMPILER_VERSION=7.5.0 -DROCKSDB_LIB_IO_POSIX -D$
ZIP2 -DSNAPPY -DZLIB -mno-avx -mno-bmi -mno-bmi2 -mno-fma -D__STDC_FORMAT_MACROS -Wno-deprecated-declarations -DGFLAGS=gflags -Wnon-virtual-dtor -Werror=enum-compare -W$
rror=reorder -Werror=switch -Werror=return-type -Werror=non-virtual-dtor -DYB_HEADERS_NO_STUBS=1 -O3 -g -DNDEBUG -fno-omit-frame-pointer -mno-abm -mno-movbe -fPIC -DTCM$
LLOC_ENABLED -faligned-new -fPIC -std=gnu++14 -o CMakeFiles/yb_util.dir/encryption_util.cc.o -c /home/nshi/workspace/yugabyte-db/src/yb/util/encryption_util.cc )  # Com$
iler exit code: 1.                                  
                                                                                                   
/-------------------------------------------------------------------------------
| COMPILATION FAILED                   
|-------------------------------------------------------------------------------
src/yb/util/encryption_util.cc: In constructor ‘yb::enterprise::OpenSSLInitializer::OpenSSLInitializer()’:
src/yb/util/encryption_util.cc:201:44: error: statement has no effect [-Werror=unused-value]
     CRYPTO_THREADID_set_callback(&ThreadId);                
                                            ^
src/yb/util/encryption_util.cc: In destructor ‘yb::enterprise::OpenSSLInitializer::~OpenSSLInitializer()’:      
src/yb/util/encryption_util.cc:206:42: error: statement has no effect [-Werror=unused-value]                 
     CRYPTO_THREADID_set_callback(nullptr);                                                                
                                          ^
cc1plus: all warnings being treated as errors
                       
Input files:
  src/yb/util/encryption_util.cc
Output file (from -o): CMakeFiles/yb_util.dir/encryption_util.cc.o
\-------------------------------------------------------------------------------
src/yb/util/CMakeFiles/yb_util.dir/build.make:433: recipe for target 'src/yb/util/CMakeFiles/yb_util.dir/encryption_util.cc.o' failed                               
make[2]: *** [src/yb/util/CMakeFiles/yb_util.dir/encryption_util.cc.o] Error 1

**Comment by nshigit** [comment]
NAME="Ubuntu"                                                                                                                                                           
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by ddorian** [comment]
@nshigit  Can you try:
```
sudo apt-get install libssl1.0
./yb_build.sh --clean release
```

**Comment by nshigit** [comment]
dpkg --list | grep ssl                                                                                                                                                                                         
ii  libssl-dev:amd64                       1.1.1-1ubuntu2.1~18.04.5                        amd64        Secure Sockets Layer toolkit - development files                                                                                     
ii  libssl1.0.0:amd64                      1.0.2n-1ubuntu5.3                               amd64        Secure Sockets Layer toolkit - shared libraries                                                                                      
ii  libssl1.1:amd64                        1.1.1-1ubuntu2.1~18.04.5                        amd64        Secure Sockets Layer toolkit - shared libraries                                                                                      
ii  libxmlsec1-openssl:amd64               1.2.25-1build1                                  amd64        Openssl engine for the XML security library                                                                                          
ii  libzstd1:amd64                         1.3.3+dfsg-2ubuntu1.1                           amd64        fast lossless compression algorithm                                                                                                  
ii  openssl                                1.1.1-1ubuntu2.1~18.04.5                        amd64        Secure Sockets Layer toolkit - cryptographic utility                                                                                 
ii  python-backports.ssl-match-hostname    3.5.0.1-1                                       all          Backport of the Python 3.5 SSL hostname checking function                                                                            
ii  python3-openssl                        17.5.0-1ubuntu1                                 all          Python 3 wrapper around the OpenSSL library

**Comment by nshigit** [comment]
libssl1.0 already installed. 
The problem still exists.

**Comment by svarnau** [comment]
The first error seems to be same as https://github.com/yugabyte/yugabyte-db/issues/4474, which was resolved and you got past that. I'll spin up an ubuntu server to try to reproduce the issue.

**Comment by svarnau** [comment]
Using the latest version of yugabyte-db master code (commit c02ebe3), I built successfully on Ubuntu 18.04. 

I was able to reproduce the problem, however, by installing the libssl-dev package and building again.  So the problem seems to be that we are not specific enough in specifying the version we need to use, in this case the header files being used.

It is not clear if this version of SSL just introduced a compile warning that we are treating as an error, or if there is a real incompatibility.  Also not clear yet if this is Ubuntu specific.

If it is an option, a work-around would be to re-install the libssl1.0-dev package, to make it the default version. You don't need to uninstall the 1.1 version.  Doing that seems to work for me.

**Comment by svarnau** [comment]
Ah, I see the problem is that you can have multiple libssl packages on the system, but only one libssl*-dev package, since they both install the same /usr/include/openssl/ set of header files.  Looks like the centos equivalent packages work the same way.

Yugabyte-db code is dependent on the libssl1.0-dev package, and installing libssl-dev wipes it out. The issue does not seem to be in the yugabyte-db code base.

**Comment by bmatican** [comment]
https://docs.yugabyte.com/latest/contribute/core-database/build-from-src-ubuntu/

@nshigit Note that we explicitly mark this in the docs as needing to install `libssl1.0-dev` cc @svarnau
