### ISSUE TITLE
[Phase 2][Colocation] Handle colocated tables in YSQL distributed backup/restore

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4517]
Jira Link: [[DB-396]](https://yugabyte.atlassian.net/browse/DB-396)
Backup script should:
1. Include colocated/not colocated in metadata
2. Generate `CREATE TABLE` statements that include PG table OID.

Restore should:
1. Use PG table OID while creating the table.
2. Create colocated tables before creating non-colocated tables to avoid OID clashes.

[DB-396]: https://yugabyte.atlassian.net/browse/DB-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment]
Close this issue because instead of using table OID, we introduced a special colocation ID to solve backup of colocated tables. See commit 71d527c69554 for details.
