### ISSUE TITLE
[Question] Both YSQL and YEDIS interfaces on the same DB - is it possible?

### ISSUE THREAD

**Issue by sgjurano** [yugabyte/yugabyte-db#4518]
Hello!
Is it possible to use both interfaces on the same database?
Maybe on different tables?

I couldn't find answer for this question in the documentation.

**Comment by kmuthukk** [comment]
hi @sgjurano -- 

Yes - the same cluster (set of servers) that form an instance of YugabyteDB can be used for YSQL, YCQL (or YEDIS needs). However, the tables create/data written via say the YSQL must be accessed the same API (and cannot be accessed via say the YCQL API). 

Also note that YEDIS is not under active development. Please read the note here: https://docs.yugabyte.com/latest/yedis/.

**Comment by kmuthukk** [comment]
For future, please feel free to use forum.yugabyte.com or www.yugabyte.com/slack for such questions. I'll close this issue for now, but do not hesitate to reopen if you have a followup question.
