### ISSUE TITLE
Local host/port 0.0.0.0:7100 not present in master_addresses <ip>:7100

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#452]
Filing an issue reported by a user.

-----

Trying to create a RF=1 cluster, using YugaByte DB Community Edition, on a i3.4xlarge machine following the manual deploy instructions here:

https://docs.yugabyte.com/latest/deploy/manual-deployment/start-masters/

But getting this:

```
$ ~/master/bin/yb-master \
                   --master_addresses 172.151.22.102:7100 \
                   --fs_data_dirs "/mnt/d0,/mnt/d1" 
                   --replication_factor 1 >& /mnt/d0/yb-master.out &
[1] 18181

$ cat /mnt/d0/yb-master.out
Illegal state (yb/master/catalog_manager.cc:1249): Unable to initialize catalog manager: Failed to initialize sys tables async: Local host/port 0.0.0.0:7100 not present in master_addresses 172.151.22.102:7100.

```

***Temporary Workaround***

The workaround we have for now is to explicitly pass the private IP via gflags:

Workaround for yb-master, is to also additionally pass the `rpc_bind_addresses` argument where the IP is explicitly set:

```
--rpc_bind_addresses=<private-ip>:7100
```

And workaround for yb-tserver is to also pass these additional arguments where the IP is explicitly set:

```
--rpc_bind_addresses=<private-ip>:9100
--cql_proxy_bind_address=<private-ip>:9042
--redis_proxy_bind_address=<private-ip>:6379
```

**Comment by bbaddepudi** [comment]
Fixed in [a3d7a1a](https://github.com/YugaByte/yugabyte-db/commit/a3d7a1a1e0d8829e12bd0c360add07a4e4043b3a)
