### ISSUE TITLE
[YSQL] Error: Corruption: Expected first value type to be primitive or GroupEnd, got kLowest in 0021

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#4534]
Jira Link: [DB-2294](https://yugabyte.atlassian.net/browse/DB-2294)
Got this stack trace while implementing #4499 locally as a consequence of another query-layer issues.
Did not replicate this on latest/master branch, but it looks like the DocKey encode/decode functions might have some issues for the colocated case that we should investigate (confirm whether this is a real issue or not).

Here is the stack trace:
```
F20200513 05:38:02 ../../../../../src/yb/docdb/doc_key.cc:991] Check failed: _s.ok() Bad status: Corruption (yb/docdb/doc_key.cc:1112): Expected first value type to be primitive or GroupEnd, got kLowest in 0021
    @     0x7fd65116265c  yb::LogFatalHandlerSink::send()
    @     0x7fd6503492f6  google::LogMessage::SendToLog()
    @     0x7fd65034675a  google::LogMessage::Flush()
    @     0x7fd650349829  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd655911762  yb::docdb::(anonymous namespace)::HashedComponentsExtractor::Transform()
    @     0x7fd654e93b35  rocksdb::BlockBasedTable::GetFilterKeyFromUserKey()
    @     0x7fd654e9497d  rocksdb::BloomFilterAwareFileFilter::Filter()
    @     0x7fd654e52a08  rocksdb::Version::AddIterators()
    @     0x7fd654dbe92f  rocksdb::DBImpl::NewInternalIterator()
    @     0x7fd654dbea9d  rocksdb::DBImpl::NewIterator()
    @     0x7fd658b9cfe8  yb::docdb::BoundedRocksDbIterator::BoundedRocksDbIterator()
    @     0x7fd658c24a62  yb::docdb::IntentAwareIterator::IntentAwareIterator()
    @     0x7fd658be53e5  yb::docdb::CreateIntentAwareIterator()
    @     0x7fd658c0c2e5  yb::docdb::DocRowwiseIterator::DoInit<>()
    @     0x7fd658c08478  yb::docdb::DocRowwiseIterator::Init()
    @     0x7fd658c371c6  yb::docdb::QLRocksDBStorage::GetIterator()
    @     0x7fd658c2c6ff  yb::docdb::PgsqlReadOperation::Execute()
    @     0x7fd6596f1fbd  yb::tablet::AbstractTablet::HandlePgsqlReadRequest()
    @     0x7fd65970ea68  yb::tablet::Tablet::HandlePgsqlReadRequest()
    @     0x7fd65a021587  yb::tserver::TabletServiceImpl::DoRead()
    @     0x7fd65a02271f  yb::tserver::TabletServiceImpl::CompleteRead()
    @     0x7fd65a0241bb  yb::tserver::TabletServiceImpl::Read()
    @     0x7fd657280ba5  yb::tserver::TabletServerServiceIf::Handle()
    @     0x7fd6529aa579  yb::rpc::ServicePoolImpl::Handle()
    @     0x7fd65294ddd4  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7fd6529b61c8  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7fd6511f110f  yb::Thread::SuperviseThread()
    @     0x7fd64ba26694  start_thread
    @     0x7fd64b16341d  __clone
    @              (nil)  (unknown)
```

The relevant key (computed for a k = `null` query on a colocated table) is `0\x00\x00@\x07\x00!` -- (corresponding binary user key `30000040070021`).

_Note that the `00` corresponds to `kLowest` which was there because of a bug instead of the expected `kNull`. That bug though, _should_ have just meant slower query execution (and more in-memory filtering), but _should probably not_ have caused a tserver crash. That bug itself is fixed as part of #4499_

The problem seems to be that the `HashedComponentsExtractor` does not stop where it should for colocated (since those tables have no hash components anyway), and moves forward to try and parse the range components also (and that's where the `kLowest` range component is causing issues).
We should confirm if this is the intended behavior or not. 

For completeness here is how search keys look for other values:
1. Non-null value for colocated table key
```
- (k = `2`) `0\x00\x00@\x07H\x80\x00\x00\x03!` -- (corresponding binary user key 3000004007488000000321)
```
2. Hash+range key for regular table: 
```
- (h = 3 and r = 5) G\xfc\xa0H\x80\x00\x00\x03!H\x80\x00\x00\x05!
                                              ^                 ^
```
^ Note two group ends (end of hash group and end of range group)

**Comment by rthallamko3** [comment]
@karan-yb , Did your fix for Scan choices fix the colocated scenario as well?

**Comment by rthallamko3** [comment]
Assigning to @tanujnay112 , based on offline conversations about the fix being in the ScanSpec component.

**Comment by tanujnay112** [comment]
It appears that the correct value for null is passed down now after testing. This crash is also no longer reproducible on master. Closing for now.
