### ISSUE TITLE
Not able to connect with cql when specifying server_broadcast_addresses

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#454]
I am not able to connect to the tserver with cqlsh if I specify broadcast address. I did the following to create a cluster with just one node:

• Started the master:
```
./bin/yb-master \
      --master_addresses 172.151.22.109:7100 \
      --fs_data_dirs /mnt/data \
      --rpc_bind_addresses 172.151.22.109:7100 \
      --server_broadcast_addresses 52.12.222.212:7100 \
      &> yb-master.out &
```

• Started the tserver:
```
./bin/yb-tserver \
      --tserver_master_addrs 172.151.22.109:7100 \
      --fs_data_dirs /mnt/data \
      --rpc_bind_addresses 172.151.22.109:9100 \
      --server_broadcast_addresses 52.12.222.212:9100 \
      &> yb-tserver.out
```

Now cqlsh fails on private IP address from the same machine:
```
$ ./bin/cqlsh 172.151.22.109
Connection error: ('Unable to connect to any servers', {'172.151.22.109': 
OperationTimedOut('errors=None, last_host=None',)})
```

The above scenario works without the broadcast addresses flag passed to the master and tserver processes. I see a bunch of the following warning in the tserver logs, not sure if this is indicative of an issue:

> W0829 04:14:35.216796 10527 tablet_rpc.cc:304] Timed out (yb/rpc/rpc.cc:170): Failed Read(tablet: c4945693ce1546edb84fef1b1d7aee5c, num_ops: 1, num_attempts: 8) to tablet c4945693ce1546edb84fef1b1d7aee5c on tablet server { uuid: 2f1952c7368142f79313461560d41495 private: [host: "172.151.22.109" port: 7100] public: [host: "52.12.222.212" port: 7100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 8 attempt(s): Read(tablet: c4945693ce1546edb84fef1b1d7aee5c, num_ops: 1, num_attempts: 8) passed its deadline 2453.921s (now: 2453.970s): Network error (yb/rpc/connection.cc:175): Connect timeout, passed: 14.976s

**Comment by spolitov** [comment]
Not a bug.

**Comment by rkarthik007** [comment]
Verified that this works, see post here with details: https://blog.yugabyte.com/yugabyte-db-1-1-new-feature-public-ips-to-simplify-multi-or-hybrid-cloud-database-deployments/
