### ISSUE TITLE
Expose table_type (catalog, table, index, other) via yb-admin list_tables

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4546]
It would be helpful to have the table type of an object available via `yb-admin -master_addresses $MASTERS list_tables` so that external scripts can distinguish between catalog tables, user tables and user indexes.

**Comment by vvkgopalan** [comment]
Addressed in: https://github.com/yugabyte/yugabyte-db/commit/3e7b4137d2ed0e7599307a8bd5099e8ba3178377
