### ISSUE TITLE
[Platform] Add validation to the backups config for s3 bucket

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4547]
The s3 bucket URL specified for backups need to be of the form s3://<bucket details> . It's very common for customers to not specify s3:// . We should add validation or error message saying the expected format is s3://<bucket details>

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-409

**Comment by nishantSharma459** [comment]
I'll be resolving this as a part of the ticket mentioned below:

https://github.com/yugabyte/yugabyte-db/issues/7349
