### ISSUE TITLE
[docdb][test] RaftConsensusITest.TestLaggingFollowerRestart is flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4549]
week over week, this went from:
> 392 | RaftConsensusITest.TestLaggingFollowerRestart | 2 | 2

to

> 81 | RaftConsensusITest.TestLaggingFollowerRestart | 14 | 12

**Comment by rajukumaryb** [comment]
The failure rate for this test is now down to 2%. Closing this issue for now.

**Comment by rajukumaryb** [comment]
Failure stats:

455 | RaftConsensusITest.TestLaggingFollowerRestart | 0.6 | 2 | 2
-- | -- | -- | -- | --
