### ISSUE TITLE
Group by not taking into account in result set

### ISSUE THREAD

**Issue by Mauzer93** [yugabyte/yugabyte-db#4555]
I am struggling for some time with performing a group by.
After seeing all examples, I am still not able to perform a correct group by for some reason.
My table is created like this:
`
CREATE TABLE IF NOT EXISTS itvance.identityuserdata (
id TEXT,
 type TEXT,
tenantId TEXT,
 version INT,
data JSONB,
PRIMARY KEY((id, type, tenantId), version))
WITH transactions ={'enabled': true }`

![image](https://user-images.githubusercontent.com/14630741/82651211-257a2280-9c1c-11ea-9129-c5b120617280.png)

**Comment by ddorian** [comment]
Hi @Mauzer93 

In your create table, the syntax is for YCQL.
While in your query, the syntax is YSQL (`grouping sets` is only available in YSQL). 

Can you try this example: https://learn.yugabyte.com/fundamentals/grouping-sets in YSQL ?

**Comment by Mauzer93** [comment]
Hi @ddorian,

Thanks for your reply. That indeed makes sense. The screenshot comes from a visual studio cassandra plugin.

My goal is to only search in the latest versions and I am using the c# library for that with YCQL.

I saw a sample here https://github.com/yugabyte/yugabyte-db/issues/4440 which would do the trick.

This is the data I have:
![image](https://user-images.githubusercontent.com/14630741/82667077-66cbfb80-9c37-11ea-885c-bd88963556ea.png)

This is my c# code:
![image](https://user-images.githubusercontent.com/14630741/82667323-e8bc2480-9c37-11ea-883f-0684ed4ac5c1.png)

This is the error I am getting:
![image](https://user-images.githubusercontent.com/14630741/82667405-1739ff80-9c38-11ea-8149-0f9007ded942.png)

**Comment by ddorian** [comment]
> Is there a way how I can achieve this in YCQL?

No there is not, you have to use YSQL layer & clients.

**Comment by Mauzer93** [comment]
Found a solution. Because Yugabyte supports ACID transactions, I've added an active column. Every time I create a new version I set previous active to false with batch transactions.

**Comment by ddorian** [comment]
@Mauzer93 so on each update you will also update the previous active column ?
Have you thought about keeping history in another table and "active" in the current one ? 
If "active" is queried much more often it will have better cache hit-rate.

**Comment by Mauzer93** [comment]
@ddorian Sounds like a good idea. I will keep this in mind. Thank you.

**Comment by ddorian** [comment]
@Mauzer93 can you also update your thread on stackoverflow ?
