### ISSUE TITLE
[Platform] Support for installing epel-release in Amazon Linux

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4561]
Currently the platform ansible script tries to yum install epel-release on all "RedHat" platforms. We should update the ansible playbooks to check for the Amazon distribution: (ansible_distribution == "Amazon") and do the correct step of `sudo amazon-linux-extras install -y epel`. Then further commands like installing packages like s3cmd will proceed normally.

**Comment by rkarthik007** [comment]
Addressed as a part of #3572
