### ISSUE TITLE
[docdb][test] CppCassandraDriverTest.TestPauseAfterCreateIndexIssued flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4562]
#6 in 100commit stability report

**Comment by amitanandaiyer** [comment]
@bmatican we've fixed this test recently, and D8511 addresses some more known reasons why this may fail.

I wouldn't expect this to pass consistently until that is in as well.

**Comment by amitanandaiyer** [comment]
Did you mix up 2 tests?

This should have been MasterFailoverTest?

after my recent change, it looks like it is about 273 in the last based on the last 10 commits.

Not sure if 100 is going back too far.

272 | MasterFailoverTestIndexCreation/MasterFailoverTestIndexCreation.TestPauseAfterCreateIndexIssued/0 | 1 | 1
-- | -- | -- | --
273 | MasterFailoverTestIndexCreation/MasterFailoverTestIndexCreation.TestPauseAfterCreateIndexIssued/6 | 1 | 1

**Comment by amitanandaiyer** [comment]
no longer listed in https://detective-gcp.dev.yugabyte.com/stability/
