### ISSUE TITLE
[docdb][test] RemoteBootstrapITest.TestClientCrashesBeforeChangeRoleKeyValueTableType flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4565]
26th in stability, failing in 58/100 commits, likely mostly in 1 build type

**Comment by hectorgcr** [comment]
It hasn't been failing lately. But I checked the past failures, and it's failing with this:

```
TS 92c2bdf02eba476f8220cf20303e274b did not crash!
```

So it seems more like a timing issue. I'll try to reproduce it locally
