### ISSUE TITLE
[YSQL] Remove beta gflag for row level security and procedures/functions

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4567]
In `gram.y`, these features are guarded by the gflags `ysql_beta_features` and `ysql_beta_feature_<name>`. We should remove these gflags for row level security and functions/procedures and create/alter role type of statements (RBAC).

We'll also need to split `TestPgRegressBetaFeatures` into individual regress tests.

**Comment by emhna** [comment]
The beta flags have been removed from most of the statements that have completed its testing. Some statements (subcommands) still keep the beta flags such as `alter_table_cm`, `reloption_list`, and `SplitClause`. That is because they are still actively shared with "not-supported" statement types.
