### ISSUE TITLE
[docs] Troubleshooting for fixing 2/3 failed peers

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4576]
Need to document our approach for fixing clusters where 2 of 3 raft peers for a tablet have failed, for whatever reason. Currently we execute the equivalent of a remote bootstrap, manually. The steps for this, however, should go into some top-level docs for troubleshooting.

Assumptions:
- a given tablet with UUID `TABLET1`
- 3 tablet peers, 1 in good working order, referred to as `NODE_GOOD` and two broken peers, say `NODE_BAD1` and `NODE_BAD2` (we can document just for one of them below)
- we will be copying some tablet related data from the good peer to each of the bad peers

Steps to follow:
- stop the bad TS, say `NODE_BAD1`, as we will be changing file system data underneath
- on the `NODE_GOOD` TS, create an archive of the `wals` (raft data) and `rocksdb` (regular rocksdb) directories [note1]
- copy these archives over to `NODE_BAD1`, on the same drive that `TABLET1` currently has its raft and rocksdb data
- remove the old `wals` and `rocksdb` data for `TABLET1` from `NODE_BAD1`
- unpack the data we copied over from `NODE_GOOD` into the corresponding (now empty) directories on `NODE_BAD1`
- restart `NODE_BAD1`, so it can bootstrap `TABLET1` using this new data
- restart `NODE_GOOD` so it can properly observe the changed state and data on `NODE_BAD1` (TODO: make this step unnecessary)

Note1: Normally when we try to find tablet data, we use a find command across the `fs_data_dir` paths. In this example, assume that's set to `/mnt/d0` and our tablet UUID is `c08596d5820a4683a96893e092088c39`:
```
$ find /mnt/d0/ -name '*c08596d5820a4683a96893e092088c39*'
/mnt/d0/yb-data/tserver/wals/table-2fa481734909462385e005ba23664537/tablet-c08596d5820a4683a96893e092088c39
/mnt/d0/yb-data/tserver/tablet-meta/c08596d5820a4683a96893e092088c39
/mnt/d0/yb-data/tserver/consensus-meta/c08596d5820a4683a96893e092088c39
/mnt/d0/yb-data/tserver/data/rocksdb/table-2fa481734909462385e005ba23664537/tablet-c08596d5820a4683a96893e092088c39
/mnt/d0/yb-data/tserver/data/rocksdb/table-2fa481734909462385e005ba23664537/tablet-c08596d5820a4683a96893e092088c39.intents
/mnt/d0/yb-data/tserver/data/rocksdb/table-2fa481734909462385e005ba23664537/tablet-c08596d5820a4683a96893e092088c39.snapshots
```
The data we are interested in here is:
- For the raft wals: `/mnt/d0/yb-data/tserver/wals/table-2fa481734909462385e005ba23664537/tablet-c08596d5820a4683a96893e092088c39`
- For the rocksdb regular DB: `/mnt/d0/yb-data/tserver/data/rocksdb/table-2fa481734909462385e005ba23664537/tablet-c08596d5820a4683a96893e092088c39`

**Comment by ddorian** [comment]
@bmatican 
How can we find which tablets have only 1 peer ?

I know we can crawl http://127.0.0.1:9000/tablets but is there a better way ?

**Comment by bmatican** [comment]
@ddorian In this case, the problem is not that they're down to 1/1 peer, but rather 1/3 peers. so the raft groups would say 3 FOLLOWER nodes are present, but 2 are down and the third cannot become a leader, so a configuration change to the other ones cannot happen.

I think we do not have a good way to automatically detect this now, we probably need some master-level mechanics, to alert that a tablet has not had a leader for X amount of time. I filed https://github.com/yugabyte/yugabyte-db/issues/4836 for that

**Comment by ddorian** [comment]
@bmatican we can get a list of all tablets and on which nodes they reside.
Compare them to the yb-tservers that are down. 
And see which tablets have only 1 live yb-tserver ?

**Comment by ddorian** [comment]
@bmatican what about a manual way ? Would my comment above work ?

**Comment by bmatican** [comment]
@ddorian oh damn, missed your question, yeah, manually comparing quorums against the dead TS would definitely work, but is a bit tedious for now..
