### ISSUE TITLE
[docdb] provide a metric to track WAL files size for each node

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4580]

**Comment by triump2020** [comment]
@bmatican  could you  pls describe it more detail ?  or give me a  existing metric reference ?

**Comment by rahuldesirazu** [comment]
Hi @triump2020, I think this would make the most sense as a per tablet metric. We don't have to update the metric every time we write to a WAL file- instead we can simply update every time we close (increment) or GC (decrement) a file. Look at src/yb/consensus/log_metrics.cc for other log metrics. I think it makes the most sense to define a new metric here.

**Comment by triump2020** [comment]
@bmatican  thanks !

**Comment by triump2020** [comment]
@rahuldesirazu  thanks !

**Comment by triump2020** [comment]
@bmatican @rahuldesirazu   I  added some commits to this issue ,  but i 'm not sure  it is [the correct place](https://github.com/triump2020/yugabyte-db/blob/issue-4580/src/yb/consensus/log.cc#L1376) where call Increment() function. 
 Pls help me check  and review all commits,  thanks!

**Comment by triump2020** [comment]
@rahuldesirazu  @bmatican   pls check !  thanks again !
