### ISSUE TITLE
"create_initial_sys_catalog_snapshot" self-test error.

### ISSUE THREAD

**Issue by nshigit** [yugabyte/yugabyte-db#4592]
ubuntu 18.04

**Comment by nshigit** [comment]
Ubuntu 18.04
yugabyte 2.16
yb_build.sh error in create_initial_sys_catalog_snapshot self-test.

[create_initial_sys_catalog_snapshot.zip](https://github.com/yugabyte/yugabyte-db/files/4687818/create_initial_sys_catalog_snapshot.zip)

**Comment by ddorian** [comment]
Can you please list more about your setup, server specs and did you follow steps in https://docs.yugabyte.com/latest/contribute/core-database/build-from-src-ubuntu/ ?

**Comment by ddorian** [comment]
@nshigit please reopen the issue if the error is still occurring
