### ISSUE TITLE
[Platform] Purge tasks in the YW db periodically

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4618]
To help performance in the YW UI Tasks page, purge the tasks periodically and archive the older tasks.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-373

**Comment by rao-vasireddy** [comment]
If there are multiple universes in YW, we probably need to purge tasks by universe, ie: keep x number of tasks per universe maybe?

**Comment by rao-vasireddy** [comment]
At the minimum we should archive them to make sure the task queries from the UI are not affected due to a high number of tasks in the table.

**Comment by sb-yb** [comment]
[Design Doc](https://docs.google.com/document/d/18v_dpjRZ3b3Gn0kC7AiuRitvVcBf-KwrBOOmcT6UDTU/edit?usp=sharing)
@rao-vasireddy  Pl. take a look.
