### ISSUE TITLE
[Doc] Hugo site generator treats an external links with in a note wrongly

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#4623]
Look at this `.md` source text:
```
This property is marked by _"Y"_ in the column _"agg"_ in the following tables;
a blank in this column means that the entry has only a window function variant.

_&#91;not intended to be here!&#93;:_ Look for [Table 9.55. Hypothetical-Set Aggregate Functions](https://www.postgresql.org/docs/11/functions-aggregate.html#FUNCTIONS-HYPOTHETICAL-TABLE).

{{< note title="Functions with both a 'window' and an 'aggregate' variant" >}}
Describing the use, as an aggregate function, of a window function that has
such a variant is outside the scope of this major _"Window functions"_ section.
A future documentation effort will add an _"Aggregate functions"_ major section.
The topic will be covered there. Meanwhile, you can refer to the section
_"9.20. Aggregate Functions"_ in the PostgreSQL documentation.
Look for [Table 9.55. Hypothetical-Set Aggregate Functions](https://www.postgresql.org/docs/11/functions-aggregate.html#FUNCTIONS-HYPOTHETICAL-TABLE).
{{< /note >}}
```
And look at the screenshot `hugo-bad-external-link-in-note.png` in the attached `hugo-bad-external-link-in-note.zip`.

Notice that the link in the ordinary paragraph that starts with _"not intended to be here!"_ behaves as an external link is meant to. It's followed by the special gif; and clicking it opens the link in a new browser tab. And notice that the exact same link-defining `.md` source, when it occurs within a note, looks and behaves differently. It has a bold font, and the special gif is missing. Moreover, clicking it simply replaces the present content, in place in the present browser tab, with what the external link defines.

[hugo-bad-external-link-in-note.zip](https://github.com/yugabyte/yugabyte-db/files/4703903/hugo-bad-external-link-in-note.zip)

**Comment by yb-andrew** [comment]
@bllewell I don't think there is a straightforward way to render anchor tags in note blocks as external links. The easiest workaround is to use inline html in the markdown. The note tag you are using is a custom element rendered separately from the page rendering, meaning it does not run render hooks, which we use to generate the link html with the icon.
