### ISSUE TITLE
[docdb] Using the /threadz endpoint should more easily highlight the number of threads sharing the same stack

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#4625]
Currently the stack traces that are the same across threads are deduplicated. However, there is no way for us to know the count of threads that have the same stack trace.
Add the count as well to this view.

**Comment by bmatican** [comment]
Good point @psudheer21 !! The handful of times I've cared about seeing this, I usually inspect the page and see the `rowspan="X"` entry in the html. Would be great to more seamlessly bubble this up though!

**Comment by emhna** [comment]
Screenshot of changed UI on threads dashboard:
<img width="1344" alt="Screen Shot 2020-06-12 at 7 41 52 PM" src="https://user-images.githubusercontent.com/66644511/84554217-e99b2000-ace4-11ea-8ec0-1298597e05a5.png">
