### ISSUE TITLE
[Platform] Implement OAuth2 authentication

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4633]
Implement OAuth2/SSO authentication for Platform sign-in. Part of https://github.com/yugabyte/yugabyte-db/issues/4420.

### Proposed Solution:
Utilize the pac4j library to extend the current authentication functionality of the platform.
### End User Flow:
The end user flow will have the following step for each customer:
1) Create the customer using the register flow. This creates an admin user (superAdmin user if this is the first customer ever in the platform).
2) The admin/superAdmin user can dictate which OAuth method will be used for their customer’s user’s authentication. Once the OAuth is enabled, all users belonging to that particular customer will have to use the OAuth method. The native platform authentication will not work after that.
3) New users need to be added first by the admin users. They are not automatically granted access based on third party auth.
### Backend Design:
We create a new entry in the customerConfig that stores and handles the metadata for an OAuth client/authorizer. When the admin user selects the OAuth method, they populate the necessary fields for each kind of supported client and then we save that in the DB.
We will also expand the customer model with an additional field which will mark the preferred OAuth method with the corresponding customerConfig UUID. The default will be null, which will mean use the platform’s native token authentication.
We will then add new endpoints that will interact with the pac4j library functions to allow authentication using the requested OAuth method (clients will be created using the metadata of the associated customer). Once the authentication is successful, we’ll set the auth token (as we currently do as well), and then the user will have access to the platform.
### Future Work:
1) We will need to enable a method to allow automatic access to YW if the third party client can mark roles to user profiles giving them access to YW. This can essentially be achieved using the ROLES field in several OAuth clients.
2) To expand this to a multi-tenant YWs. One way to do this is to modify our login page, and have the user enter only their email. Once they enter their email, we can verify the customer associated with that email and then redirect the user to the appropriate login screen based on the customer’s settings.

NOTE: OAuth will only work in single-tenant platforms in V0.

**Comment by Arnav15** [comment]
Updated description with the intended design.

**Comment by Arnav15** [comment]
### Changes to Design in V0:
For V0, we have made the following changes to the above design:
Each platform will need to specify the preferred login OAuth method at at app start up using the app config. The app will then set up the app's authentication method based on the data provided in the app config, and the native login will be disabled. All login into the platform (after the SuperAdmin creation) will require the user to login using the OAuth method. If the customer wishes to update the login method, they will have to do an app restart after modifying the app config.
### Testing:
V0 was tested as follows:
1) We started an app by setting the necessary env vars for the config, which are as follows:
```
# If third party login is enabled
security.use_oauth = ${?USE_OAUTH}
# Kind of third party security enabled
security.type = ${?YB_SECURITY_TYPE}
# The details for the security client
security.clientID = ${?YB_OIDC_CLIENT_ID}
security.secret = ${?YB_OIDC_SECRET}
security.discoveryURI = ${?YB_OIDC_DISCOVERY_URI}
# The host running the platform
url = ${?YW_URL}
```
2) We register a new customer and then do a logout. We verify that for the login we only get the `USE SSO` option.
3) We login using the above option and verify that we are redirected to the client as expected, and that after login we are redirected back to the platform dashboard page. 
4) Verified that we can create providers, universes, and any tasks as expected.
5) Added new users (read-only and admin), and verified that when those users logged in, they had the right access control.
6) Checked that the logout for any user destroyed the session.
