### ISSUE TITLE
Bitmap scan support

### ISSUE THREAD

**Issue by rafal-hawrylak** [yugabyte/yugabyte-db#4634]
Jira Link: [DB-2547](https://yugabyte.atlassian.net/browse/DB-2547)
Some queries that are supposed to be using secondary indexes are ran with sequence scans which ends with very high times for even not big tables (2GB).

Including query plans.
[query_by_secondary_index.txt](https://github.com/yugabyte/yugabyte-db/files/4711348/query_by_secondary_index.txt)

[DB-2547]: https://yugabyte.atlassian.net/browse/DB-2547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
Hi @rafal-hawrylak 

Can you also paste the table schema that you used ?

**Comment by rafal-hawrylak** [comment]
Yes.

CREATE TABLE schema.a1 (
    id uuid NOT NULL,
    f_id_1 uuid NOT NULL,
    f_id_2 uuid NOT NULL,
    t integer NOT NULL,
    sequence integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX a1_f_id_1_idx ON schema.a1 (f_id_1);
CREATE INDEX a1_f_id_2_idx ON schema.a1 (f_id_2);

**Comment by sushantrmishra** [comment]
**PostgreSQL plan:**

postgres=#  EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM a1 WHERE f_id_1 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c' OR f_id_2 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c';
                                                              QUERY PLAN

--------------------------------------------------------------------------------------------------------------
------------------------
 Bitmap Heap Scan on a1  (cost=8.38..18.96 rows=10 width=56) (actual time=0.012..0.014 rows=0 loops=1)
   Recheck Cond: ((f_id_1 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c'::uuid) OR (f_id_2 = 'fc12ef23-27f3-43d9-8c8
5-30e50d694b1c'::uuid))
   Buffers: shared hit=2
   ->  BitmapOr  (cost=8.38..8.38 rows=10 width=0) (actual time=0.010..0.011 rows=0 loops=1)
         Buffers: shared hit=2
         ->  Bitmap Index Scan on a1_f_id_1_idx  (cost=0.00..4.19 rows=5 width=0) (actual time=0.006..0.007 ro
ws=0 loops=1)
               Index Cond: (f_id_1 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c'::uuid)
               Buffers: shared hit=1
         ->  Bitmap Index Scan on a1_f_id_2_idx  (cost=0.00..4.19 rows=5 width=0) (actual time=0.002..0.002 ro
ws=0 loops=1)
               Index Cond: (f_id_2 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c'::uuid)
               Buffers: shared hit=1
 Planning Time: 0.474 ms
 Execution Time: 0.147 ms
(13 rows)

**Comment by sushantrmishra** [comment]
**YB plan:**

  EXPLAIN (ANALYZE, dist) SELECT * FROM a1 WHERE f_id_1 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c' OR
f_id_2 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c';
                                                              QUERY PLAN

--------------------------------------------------------------------------------------------------------------
-------------------------
 Seq Scan on a1  (cost=0.00..0.00 rows=1 width=56) (actual time=0.497..0.497 rows=0 loops=1)
   Remote Filter: ((f_id_1 = 'fc12ef23-27f3-43d9-8c85-30e50d694b1c'::uuid) OR (f_id_2 = 'fc12ef23-27f3-43d9-8c
85-30e50d694b1c'::uuid))
   Storage Table Read Requests: 1
   Storage Table Execution Time: 1.000 ms
 Planning Time: 0.057 ms
 Execution Time: 0.549 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 1.000 ms
 Peak Memory Usage: 14 kB
(10 rows)

**Comment by sushantrmishra** [comment]
Repro with data in the table:

```
yugabyte=# create table bitmap_scan_test (h int primary key , r1 int, r2 int);
CREATE TABLE

yugabyte=# insert into bitmap_scan_test select  i, i%10, i%100  from generate_series(1, 1000000) i;
INSERT 0 1000000
Time: 6511.770 ms (00:06.512)
```

```
yugabyte=# explain (analyze, dist) select * from bitmap_scan_test where r1 = 10 and r2 = 50;
                                                  QUERY PLAN

--------------------------------------------------------------------------------------------------------------
-
 Seq Scan on bitmap_scan_test  (cost=0.00..0.00 rows=1 width=12) (actual time=691.823..691.823 rows=0 loops=1)
   Remote Filter: ((r1 = 10) AND (r2 = 50))
   Storage Table Read Requests: 1
   Storage Table Execution Time: 692.005 ms
 Planning Time: 2.006 ms
 Execution Time: 691.873 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 692.005 ms
 Peak Memory Usage: 14 kB
(10 rows)

Time: 695.738 ms
```


**After analyze**

yugabyte=# explain (analyze, dist) select * from bitmap_scan_test where r1 = 10 and r2 = 50;
                                                     QUERY PLAN

--------------------------------------------------------------------------------------------------------------
------
 Seq Scan on bitmap_scan_test  (cost=0.00..105000.00 rows=1 width=12) (actual time=637.028..637.029 rows=0 loo
ps=1)
   Remote Filter: ((r1 = 10) AND (r2 = 50))
   Storage Table Read Requests: 1
   Storage Table Execution Time: 637.005 ms
 Planning Time: 2.080 ms
 Execution Time: 637.074 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 637.005 ms
 Peak Memory Usage: 14 kB
(10 rows)

Time: 642.372 ms
yugabyte=#
