### ISSUE TITLE
[docs] add docs with full permissions necessary for a new VPC scenario

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4642]
currently yb-platform docs permissions are missing permissions like `createVpc` because they assume that the VPC is already existing. however, as a feature, we allow a net new VPC to be created which means the permissions list for that scenario is not documented.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-365

**Comment by WesleyW** [comment]
The following roles are a superset of roles required, as some more specific permissions may not be entirely necessary.

**For GCP:**
compute.disks.*
Compute.images.get
compute.instances.*
compute.machineTypes.get
compute.machineTypes.list
compute.globalOperations.get
compute.regionOperations.get
compute.zoneOperations.get
Compute.subnetworks.use
compute.subnetworks.useExternalIp (when `assignPublicIp` is toggled True)


**For AWS, the recommended role is AmazonEC2FullAccess.**
