### ISSUE TITLE
[platform] [docs] docs should state the mandatory NAT requirement when public IPs are disabled

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4643]
yb-platform universe subnet without public IPs / disable Public IP doesnt succeed since a NAT gateway is needed.

**Comment by yb-andrew** [comment]
Sent doc to Steve last week. He said he's going to get to adding it in this week.

**Comment by stevebang** [comment]
Closing -- added note in PR #5261
