### ISSUE TITLE
[Platform] Support editing cloud provider edit

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#4645]
We need to support couple of different edit capabilities

Cloud Providers
- Edit and enable more regions

@rkarthik007 can we fill in other options that we want to support?

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-363

**Comment by chirag-yb** [comment]
duplicate - https://github.com/yugabyte/yugabyte-db/issues/5296
