### ISSUE TITLE
SELECT with DISTINCT returns rows in wrong order

### ISSUE THREAD

**Issue by ananyaks** [YugaByte/yugabyte-db#466]
See the following [post ](https://github.com/YugaByte/yugabyte-db/pull/429#issuecomment-418178538)for details. The `testDistinct()` of `SimpleQueryTest.java` can be used to reproduce the below issue.
```
    createTable("CREATE TABLE %s (k text, t int, v text, PRIMARY KEY (k, t));");
    execute("INSERT INTO %s (k, t, v) values (?, ?, ?)", "key1", 1, "foo1");
    execute("INSERT INTO %s (k, t, v) values (?, ?, ?)", "key1", 2, "foo2");
    ....
```
The `testDistinct()` is failing because the **order of rows is switched**. The test is expecting:
```
    assertRows(execute("SELECT DISTINCT k FROM %s"),
      row("key1"),
      row("key2")
```
But yugabyte-db is returning
```
    assertRows(execute("SELECT DISTINCT k FROM %s"),
      row("key2"),
      row("key1")
```

**Comment by robertpang** [comment]
@ananyaks I had a closer look of the issue and this is actually not a bug. In this `SELECT` statement, there is no guaranteed order of the rows returned by `DISTINCT k` where column `k` is the partition (hash) key. In implementation, the rows will be returned in the order of the hashed value of `k` and YugaByte's hash algorithm is different from Apache Cassandra's and thus the different order.
