### ISSUE TITLE
Detective stack traces should link to github

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#4660]
Stack traces in detective/logs link to the bitbucket repo for the files. Since that repo is outdated, we should be linking to github instead.

**Comment by amitanandaiyer** [comment]
eg: https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F38857%2Fartifact%2Fbuild%2Fdebug-gcc-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cql-index-test%2FCqlIndexTest_MultipleIndex.log?max_lines=3000&start_line=126001

**Comment by svarnau** [comment]
D8801
