### ISSUE TITLE
Investigation of Reducing Rolling Upgrade Friction

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#4665]
Jira Link: [DB-1940](https://yugabyte.atlassian.net/browse/DB-1940)
Currently during a rolling upgrade, we see spikes of high p99 latency and low throughput at various points during the window. My hypothesis is that this is caused by stopping a node without moving the leaders off beforehand. This means that the other nodes must handle many leader elections at once, leading to spikes in resource usage (threads/CPU) and higher unavailability. The goal of this feature is to reduce the friction during rolling upgrade by gracefully moving leaders off of nodes before we restart them.

**Comment by bmatican** [comment]
Closing as we now have leader blacklisting in Platform
