### ISSUE TITLE
[Platform] YW to support universe level restore

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4695]
If a universe level backup is taken, then the user should be able to restore everything in that backup with one task.
Also, the user should be able to select one or many tables to restore from this universe level backup

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-335

**Comment by rkarthik007** [comment]
Note that only user tables are backed up in YCQL, not roles/permissions.

**Comment by rkarthik007** [comment]
@rao-vasireddy - universe level backups are supported now with the following semantics:

## Backup
* First the list of YSQL namespaces are backed up sequentially, the backup of each namespace is transactional.
* Next, the list of YCQL keyspaces are backed up sequentially, each of the tables (along with their indexes) are backed up sequentially
each keyspace is backed up transactionally 
    * If the transactional backups are selected for YCQL, this is done similar to YSQL 

## Restore
TODO: @yb-andrew to fill in the semantics here.

> Also, the user should be able to select one or many tables to restore from this universe level backup
This is not in the scope of this issue, and is not planned at the moment. Whatever is backed up gets restored.
