### ISSUE TITLE
[docs] Plans to continuously improve YugabyteDB documentaion

### ISSUE THREAD

**Issue by p-null** [yugabyte/yugabyte-db#4701]
Thanks for making this awesome product and beautiful documentation.

It would be great if YugabyteDB  has a plan to continuously improve the documentation.

Things would be great to have:

### **More explanation of each step in the documentation:**
What exactly does this step do under-the-hood?
What are the available parameters? 
What are the reasonable values for these parameters? 

### **Tips, Notice and reminders**
What are some good practices to follow?
What do you have to check before you do this operation? What should you know?
What are the consequences? What are the alternatives?

### **More background information for each step:**
For example, it answers questions such as 'in which situation you want to do this operation?'

These are just my thoughts. Welcome more inputs.

**Comment by stevebang** [comment]
@ameyb Review this for ideas and create separate issues -- this issue is too broad to say completed.

**Comment by lizayugabyte** [comment]
@polarweasel @ddhodge What do you think about this ticket?

**Comment by polarweasel** [comment]
Good thoughts, not something we need in a separate ticket.
