### ISSUE TITLE
Migrating from Aurora / RDS postgres to yugabtye

### ISSUE THREAD

**Issue by naveennazimudeen** [yugabyte/yugabyte-db#4702]
Jira Link: [DB-2295](https://yugabyte.atlassian.net/browse/DB-2295)
What is the best way to move data from Aurora / RDS postgres to yugabyte? 

To keep any downtime as short as possible, the ideal approach would be to setup some sort of replication between Aurora/RDS postgres and yugabyte. Once the data is in sync, then the app can switch over to yugabyte, with a short downtime if required.

Can AWS Database Migration Service be used?

**Comment by parthbapat** [comment]
Hello @naveennazimudeen, This is Parth from BlitzzIO. We have a solution for zero-downtime migration from PostgreSQL to YugaByteDB with capability to configure automatic cut over when the databases are in sync. Can you please send an email to **success [at] blitzz [dot] io**? Thank you.

**Comment by ddorian** [comment]
@naveennazimudeen Another alternative is to use CDC in Postgresql to stream changes to Yugabytedb.

This can be done using Debezium. It can listen for changes an [AWS RDS](https://debezium.io/documentation/reference/1.1/connectors/postgresql.html#postgresql-on-amazon-rds) db. Then you can also use Kafka JDBC connector to output to Postgresql https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/index.html#connect-jdbc-sink.

**Comment by sushantrmishra** [comment]
[YugabyteDB Voyager ](https://docs.yugabyte.com/preview/migrate/yb-voyager/) can be used to migrate database from RDS PostgreSQL and Aurora PostgreSQL to YugabyteDB .
