### ISSUE TITLE
Helm chart notes specify an incorrect kubectl command for the YSQL shell

### ISSUE THREAD

**Issue by danports** [yugabyte/yugabyte-db#4703]
```
5. Run YSQL shell from inside of a tablet server:
  kubectl exec --namespace yb-demo -it yb-tserver-0 /home/yugabyte/bin/ysqlsh -- -h yb-tserver-0.yb-tservers.yb-demo
```

This is bad `kubectl` syntax; the double dash is in the wrong place. The correct command is: `kubectl exec --namespace yb-demo -it yb-tserver-0 -- /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.yb-demo`

**Comment by iSignal** [comment]
Hello @danports, thanks for reporting this! 

https://github.com/yugabyte/charts/pull/6 should fix this.

**Comment by schoudhury** [comment]
PR that fixes the issue has been merged, will be available with the next release of the Helm chart
