### ISSUE TITLE
After i  changed config  tserver_webserver_port =9001，I restart docker  and get err （could not connect to server: Connection refused）

### ISSUE THREAD

**Issue by dahvlhldle** [yugabyte/yugabyte-db#4704]
tserver.err:
`2020-06-08 03:04:09.601 UTC [171] FATAL:  data directory "/home/yugabyte/var/data/pg_data" has invalid permissions
2020-06-08 03:04:09.601 UTC [171] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).`

**Comment by ddorian** [comment]
Hi @dahvlhldle 
Looks like somehow the data directory permissions were changed. Can you set `/home/yugabyte/var/data/pg_data` to `u=rwx (0700)` or `u=rwx,g=rx (0750)` ?

**Comment by dahvlhldle** [comment]
@

> Hi @dahvlhldle
> Looks like somehow the data directory permissions were changed. Can you set `/home/yugabyte/var/data/pg_data` to `u=rwx (

> Hi @dahvlhldle
> Looks like somehow the data directory permissions were changed. Can you set `/home/yugabyte/var/data/pg_data` to `u=rwx (0700)` or `u=rwx,g=rx (0750)` ?



> Hi @dahvlhldle
> Looks like somehow the data directory permissions were changed. Can you set `/home/yugabyte/var/data/pg_data` to `u=rwx (0700)` or `u=rwx,g=rx (0750)` ?

I use cmd `chmod -R 0 my-yucabytedb-storagelocation`  solve the problem. 
Thank you for your reply.
