### ISSUE TITLE
[docdb] Review the way we determine if load is balanced 

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4707]
Review the way we determine if load is balanced  and see if we need a more reliable way to do it and enhance yb-admin accordingly. At the moment, when we add a node or do a full move, other spinning master tasks (for example for snapshots) seem to affect this and the task keeps waiting.

**Comment by bmatican** [comment]
Discussed with @rahuldesirazu about this yesterday. An easy fix for this would be to augment our tasks to have an explicit bit w/e or not they were launched by the LB. This would allow us to filter by this when we check for recent tasks. In practice there's only 3 (?) types of tasks launched by the LB: AddServer, RemoveServer, LeaderStepdown and on very explicit paths in `cluster_balancer.cc`.

Then to actually test for this, we can just take a normal test checking for proper LB behavior and then after it goes idle, issue something like a create table, or a flush on an existing table, or even a backup, which would all still trigger async tasks, but not through the LB, so it should stay idle afterwards.

An alternative approach would be to disable the LB all together (we have a flag), after it goes idle, and then manually issue any task whatsoever and confirm that we still think the LB is idle!

**Comment by rao-vasireddy** [comment]
@bmatican , The suggested approach will not take leader movement into account, correct? I think it is a task inititated by the LB. Leader balance should not be considered to determine if load is balanced or not.

**Comment by bmatican** [comment]
@rao-vasireddy Why not? I would imagine we do want to wait for leaders to be balanced, before giving back control to the user in YW saying the task is done and they can move on to other work, or they can expect their iops to be back to normal?

**Comment by nspiegelberg** [comment]
Assigning to @vvkgopalan .  The main coding piece is to identify tasks explicitly triggered by the Load Balancer heuristic (versus Catalog Manager Operations) and only use those tasks to understand IsLoadBalancerIdle(), per @rahuldesirazu 's comments.

**Comment by vvkgopalan** [comment]
Resolved in https://github.com/yugabyte/yugabyte-db/commit/c722755b2639dcdb2e3a0b7f9be2d7eed05c6a42.
