### ISSUE TITLE
[Platform] Scheduled backups should be in YW local time instead of UTC

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4709]
Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-328

**Comment by iSignal** [comment]
I tried to create a simple CQL scheduled backup of a single table via a cron expression on portal and it didn't trigger at the right time, so there may be more immediate bugs here. Creating a single manual backup worked. @Arnav15 , can you give this scenario a try?

In general, the code itself doesn't assume a time zone, so it should all happen in the local time zone of the YW already. Once we have a scheduled backup, we can verify the original title of the bug.

**Comment by iSignal** [comment]
Looks like the UI uses the browser timezone while the host YW machine is on UTC in this case.

To fix this, we need to either :

(a) Use client browser timezone for times in the cron expression. This means we would persist the timezone of the browser where the cron expression was created in along with the cron expression itself.

(b) Use UTC as the standard timezone for all times mentioned in the cron spec. This means both UI and backend would have to convert to/from local/browser timezones when dealing with the "next scheduled backup time". 

(b) is technically more accurate to deal with corner cases like setting up a backup schedule from a client browser in India for a server in Pacific Time US. But it also means user has to calculate UTC <-> Pacific mapping themselves while entering the cron expression (if they get it wrong - the next scheduled backup time dialog will give them immediate feedback).

I would vote for (b).

**Comment by chirag-yb** [comment]
@yb-andrew @rao-vasireddy  This needs to be backported to 2.2.2.1
