### ISSUE TITLE
Add support for date and time types to YCQL

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#471]
We need to add support for DATE and TIME types as well as the standard function coverage for compatibility with CQL.

**Comment by robertpang** [comment]
Support for data and time columns, literals and secondary index completed in commit [512a592](https://github.com/YugaByte/yugabyte-db/commit/512a592a265c10ab16d6dfc2b5ba8950ae1407ab).

Support for data and time standard functions will follow next.

**Comment by robertpang** [comment]
Support for date and time standard functions is completed in [7fa8795](https://github.com/YugaByte/yugabyte-db/commit/7fa87956bfbfbe5010300d229ed9e1c1c33726a0).
