### ISSUE TITLE
[YSQL] Delete database even if corresponding namespace does not exist in docdb

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4710]
Because docdb and YSQL metadata is not yet consistent, it's possible to have a scenario where the database is created in postgres but not in docdb.
In such a situation, when we try to clean up the db via YSQL by running `drop database <dbname>`, we get a "namespace does not exist" error from docdb, preventing us from cleaning up the inconsistent. state even from YSQL.
We should change the error handling for `drop database` to ignore `not found` error from docdb and continue with deleting the database.

**Comment by IS-Josh** [comment]
Is there a workaround for this at the moment  - I have a database in ysql that i cannot remove.  YSQLSH returns ERROR:  Operation failed. Try again.: Namespace deletion not allowed when State = 5;

**Comment by bmatican** [comment]
@IS-Josh what version of YB are you using? With 2.2, these inconsistencies should be automatically addressed.

cc @nspiegelberg

**Comment by IS-Josh** [comment]
HI @bmatican  @nspiegelberg  I'm using version 2.2.

**Comment by nspiegelberg** [comment]
@IS-Josh : As a workaround, you should be able to restart the 'yb-master' leader (visible from the web UI :7100).  The new master should delete that database.  tservers handle the traffic data while master handles the tablet placement, so this shouldn't result in downtime with cached app server clients.

**Comment by IS-Josh** [comment]
@nspiegelberg 

Thanks for the suggestion, but unfortunately it didn't work for me and I still have an orphaned database that is presented to the client.

When I try to delete the db which i assume doesn't actually exist anymore i get the error:


ERROR: Not found: Keyspace identifier not found: 0000e200000030008000000000000000

SQL Error [XX000]: ERROR: Not found: Keyspace identifier not found: 0000e200000030008000000000000000
  ERROR: Not found: Keyspace identifier not found: 0000e200000030008000000000000000
  ERROR: Not found: Keyspace identifier not found: 0000e200000030008000000000000000

**Comment by IS-Josh** [comment]
@nspiegelberg i've upgraded to the latest version 2.2.2, i can confirm i can now drop the databases successfully. Thanks
