### ISSUE TITLE
[docdb] Add rate limiting on number of concurrent snapshots being issued by the master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4717]
Ideally, this should be some per-TS control, but that would have to account for tablet replica assignment. Perhaps an early version could be simply based on number of tablets.

**Comment by sanketkedia** [comment]
Fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/92add377671d51618fcb08d477990f19ededd625)
