### ISSUE TITLE
[docdb] Add a pre-flush step to snapshot operations

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4718]
Since the new transactional snapshots currently execute flushes and need to wait on them, it would be ideal that the amount of data being flushed in sync is minimal.

A pre-flush being triggered by the master, before the snapshot operation, should already help with this!

**Comment by OlegLoginov** [comment]
The fix must include 2 parts:
1. Return back `FlushTable` in `ClusterAdminClient::CreateSnapshot`. It was deleted in the diff:
https://phabricator.dev.yugabyte.com/D8308

2. The `FlushTable` must flush not only the main table but additionally flush all related indexes (if it's called from `CreateSnapshot` at least; or always).

**Comment by OlegLoginov** [comment]
Notes:
A. During [1] - you need return back (un-deprecate) flush timeout in CLI.
B. If [2] will be implementing via ListTables call in the `yb-admin` - similar code for indexes collecting can be taken from diff `D8620` - see `ClusterAdminClient::CreateKeyspaceSnapshot`.
