### ISSUE TITLE
Add support for boolean types in primary key definition

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#472]
Primary keys cannot be defined to contain boolean data type fields. Receive the following message: InvalidRequest: Error from server: code=2200 [Invalid query] message="SQL error: Invalid Primary Key Column Datatype"

**Comment by robertpang** [comment]
Resolved in commit [f8d9101](https://github.com/YugaByte/yugabyte-db/commit/f8d9101b2d7782783a93728c2c1eaac8d8b72886).
