### ISSUE TITLE
Update OpenSSL to 1.1.1

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4721]
There are some at-rest encryption related issues that come up in unit tests when upgrading to OpenSSL 1.1.1.

**Comment by graffido** [comment]
hi, @mbautin I think the encryption test issue is relate to openssl-1.1.1 would check the overlapping risk of input and output, [openssl-evp_enc.c](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/evp/evp_enc.c#L334), there is valiation on it in EncrytByBlock.

**Comment by mbautin** [comment]
@graffido: thank you for looking into this! It does seem to be related to EVP_EncryptUpdate.

```
./yb_build.sh  --cxx-test integration-tests_encryption-test --gtest_filter EncryptionTest.AddServer
```

Attaching a relevant snapshot of our internal test dashboard with a work-in-progress patch updating the OpenSSL version.

![image](https://user-images.githubusercontent.com/552936/85249246-1992a380-b408-11ea-8e85-0af882d13585.png)

The work-in-progress patch itself: https://gist.githubusercontent.com/mbautin/3eb53a254aa503fc7f8825e9aea7b23f/raw

We are planning to get back to this upgrade in the next couple of weeks.

Cc @rahuldesirazu @bmatican @svarnau

**Comment by mbautin** [comment]
@graffido -- and of course, we would gladly accept a pull request!

**Comment by graffido** [comment]
hi, @mbautin 
As I have proposed in [issue-3841](https://github.com/yugabyte/yugabyte-db/issues/3841), I use macro to support both under and above version of openssl-1.1.0, and the test issue is workaround by **new** a temp buffer for Decypt output. such as
```
+++ b/src/yb/rocksutil/rocksdb_encrypted_file_factory.cc
@@ -58,8 +58,8 @@ class EncryptedSequentialFile : public SequentialFileWrapper {
     if (!scratch) {
       return STATUS(InvalidArgument, "scratch argument is null.");
     }
-    uint8_t* buf = static_cast<uint8_t*>(EncryptionBuffer::Get()->GetBuffer(n));
-    RETURN_NOT_OK(SequentialFileWrapper::Read(n, result, buf));
+    auto buf = std::make_unique<uint8_t[]>(n);
+    RETURN_NOT_OK(SequentialFileWrapper::Read(n, result, buf.get()));
```
or you could redesign GetBuffer to avoid getting the same output buffer of encrypt/decrypt input buffer

**Comment by graffido** [comment]
also the openssl should use **perl** to execute configure other than **bash** in build_definition script

**Comment by bmatican** [comment]
@rahuldesirazu took care of the leftovers for this a while back
