### ISSUE TITLE
Add an endpoint /api/v1/cluster-config to the master

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4748]
The master service in yugabyte exposes HTTP endpoints that allow introspection of its current state. You can see a list of some of these endpoints at https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/master-path-handlers.cc.

It would be nice to have an endpoint at '/api/v1/cluster-config' that returns the current cluster config in JSON format. 

This would be similar to the current '/cluster-config' entry at https://github.com/yugabyte/yugabyte-db/blob/123f4d81829e98bd44e398658d795904ee1a15fe/src/yb/master/master-path-handlers.cc#L1467 but (a) return the SysClusterConfigEntryPB protobuf in JSON format and (b) not include the web HTML around it so that scripts can easily parse the result.

To get started with this issue, you will need to compile the C++ source code locally. Please see https://docs.yugabyte.com/latest/contribute/core-database/build-from-src-macos/ for some guidance on the build process.

Once you compile the source code, the yb-ctl code (documented at https://docs.yugabyte.com/latest/admin/yb-ctl/) can help you start up a local cluster that you can use to test the changes you've made (`/bin/yb-ctl destroy && bin/yb-ctl start --rf 1`)

**Comment by AbdallahKhaled93** [comment]
Hello,
Is this issue still of interest ? I would like to give it a try as my first contribution to the yugabyte-db

**Comment by bmatican** [comment]
@AbdallahKhaled93 Definitely! Happy to see you're interested in contributing to Yugabyte. Let us know if you need any more input! And in case you have not already, check out our docs on the How To for contributors: https://docs.yugabyte.com/latest/contribute/core-database/checklist/

Lastly, if you use slack, feel free to join our community slack (http://yugabyte-db.slack.com/) and hop on over to our #contributors channel, if you'd like some close-to-real-time help.

**Comment by AbdallahKhaled93** [comment]
Thank you for your reply.
I already compiled the code and read about the architecture and I have an idea where to impelement the code. I just need a way to verify it.

**Comment by iSignal** [comment]
@AbdallahKhaled93 : after compiling the code, you can use yb-ctl to bring up a local cluster as described in https://docs.yugabyte.com/latest/quick-start/create-local-cluster/macos/ listening on 127.0.0.1. Once this feature is implemented, browsing to http://127.0.0.1:7000/api/v1/cluster-config should help you verify it.

**Comment by AbdallahKhaled93** [comment]
![cluster-config-json](https://user-images.githubusercontent.com/42918383/85477632-fe1bca00-b5ba-11ea-91b3-ab30c39f69e6.png)

I attached a screenshot of the output. I cleared the string before adding appending the JSON but I cannot seem to remove the footer.
Your feedback is appreciated

**Comment by AbdallahKhaled93** [comment]
I am sorry for the following obvious question, I created a branch and I committed my changes but when I push I get access denied.
What did I miss ?

**Comment by bmatican** [comment]
@AbdallahKhaled93 I think you'd to submit a PR from a branch on your own fork.

Also, one note on the screenshot you shared, can you make sure the output does not include the footer info? You can follow any of the other /api/v1/xxx endpoints, which should just output the relevant JSON data

**Comment by AbdallahKhaled93** [comment]
Right now I am having an issue with the compilation as I am on ubuntu.
I am fixing and I will be back on track.
