### ISSUE TITLE
[docdb] Drop Table should delete snapshots dirs also for the deleted table.

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4756]

**Comment by bmatican** [comment]
Seems like we are not removing `snapshots` directories when deleting tables.

We should be able to repro this by:
- yb-ctl create
- create a table and write some data
- yb-admin create_snapshot
- drop the table
- check the fs_data_dirs (default yb-ctl path is `~/yugabyte-data`) and validate that the tablet snapshot dirs are still around

cc @OlegLoginov @hectorgcr on some code pointers for where the snapshots dir gets created and where the rocksdb data gets deleted

**Comment by rajukumaryb** [comment]
Snapshots are also being retained after `TRUNCATE`.

```
│               │           ├── [4.0K]  tablet-4861291fbe224dc58d76b5e9e65bbf67.snapshots
│               │           │   └── [4.0K]  b3d0b7eb-54b8-43d9-9b1e-b90dfa4668d8
│               │           │       ├── [127K]  000010.sst
│               │           │       ├── [121M]  000010.sst.sblock.0
│               │           │       ├── [128K]  000012.sst
│               │           │       ├── [121M]  000012.sst.sblock.0
│               │           │       ├── [106K]  000013.sst
│               │           │       ├── [ 72M]  000013.sst.sblock.0
│               │           │       ├── [  16]  CURRENT
│               │           │       └── [1.5K]  MANIFEST-000011
```
