### ISSUE TITLE
[docdb] Remove unreachable nodes from UI (/tablet-servers) after nodes are removed from the cluster

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4759]
At the moment a master leader change removes them from the master UI.

**Comment by bmatican** [comment]
We could combine this somehow with https://github.com/yugabyte/yugabyte-db/issues/2627

After some configurable amount of time, we can stop showing them in the /tablet-servers page all together (or move them to a separate section).

We also need to adjust the total node count displayed in a couple of sections, ie: the main master leader view of node count and the aggregate view per zone in /tablet-servers.
