### ISSUE TITLE
Document the webserver_interface parameter

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#476]
Need to document the need for the `--webserver_interface` parameter being set to the private ip address, and add an entry into the troubleshooting section in case we hit this issue. Ran into this issue in an AWS environment where the master follower was trying to reach the master leader using the hostname instead of the private ip address.

**Comment by bbaddepudi** [comment]
Live at https://docs.yugabyte.com/latest/admin/yb-master/ and yb-tserver
