### ISSUE TITLE
[Platform] Add host name also On Prem node properties

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4760]
At the moment we have node name (name of the node in the universe) and IP. Please add host name (entered by the user ) and display this in the YW Nodes page along with node name and IP.

**Comment by chirag-yb** [comment]
@daniel-yb There is a pending task to add the instance Id to the node list page. We need to do a UX review on this one

**Comment by daniel-yb** [comment]
@chirag-yb I'm going to track the remaining work under #5234 to avoid multiple commits referencing the same git issue.
