### ISSUE TITLE
[docdb] In the TS UI for /tables we should split the OnDisk size into WALs vs RocksDB data

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4767]
Currently we display the total data size. However, underneath, we just compute that as a sum up over:
- consensus metadata (tiny)
- raft wal files
- rocksdb sst files

For tables with very little data, generally the raft wals are the biggest factor, as we keep minimum of 2 files, up to 64MB each. Would be nice to be able to tell where the space is going per table.

We also display a similar metric in the /tablets endpoint, we can potentially do the same there!

**Comment by emhna** [comment]
<img width="1828" alt="tables" src="https://user-images.githubusercontent.com/66644511/84807097-b8686b80-afd4-11ea-84d4-61b9f0169201.png">
<img width="1853" alt="tablets" src="https://user-images.githubusercontent.com/66644511/84807102-bacac580-afd4-11ea-8783-34cfdaa05411.png">

**Comment by emhna** [comment]
<img width="1664" alt="Screen Shot 2020-06-16 at 3 05 25 PM" src="https://user-images.githubusercontent.com/66644511/84818934-451b2580-afe5-11ea-9198-fa89888d6172.png">
<img width="1838" alt="Screen Shot 2020-06-16 at 3 06 02 PM" src="https://user-images.githubusercontent.com/66644511/84818937-45b3bc00-afe5-11ea-912c-2a0ae151aaf7.png">

**Comment by emhna** [comment]
Updated UI:
<img width="1529" alt="Screen Shot 2020-06-17 at 11 55 41 AM" src="https://user-images.githubusercontent.com/66644511/84920994-e364c500-b091-11ea-8e80-ed88b9d4a850.png">
<img width="1548" alt="Screen Shot 2020-06-17 at 11 55 24 AM" src="https://user-images.githubusercontent.com/66644511/84921002-e65fb580-b091-11ea-9e0a-0b022311b538.png">

**Comment by emhna** [comment]
Closing the issue with the code review to address the issue (accepted): https://phabricator.dev.yugabyte.com/D8690#inline-94462
