### ISSUE TITLE
Enable --download-thirdparty on macOS

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4773]
The macOS workflow to download and extract the third-party tarball should become very similar to CentOS.

This work-in-progress patch might be helpful:
https://gist.githubusercontent.com/mbautin/230e75deed08f0ddb2f4f27a2da6971a/raw

This requires a working macOS third-party tarball, so this depends on #4771

**Comment by svarnau** [comment]
commit: 75dfb25
