### ISSUE TITLE
[YSQL] Increase default --yb_client_admin_operation_timeout_sec for DDL operations

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#4778]
Jira Link: [DB-638](https://yugabyte.atlassian.net/browse/DB-638)
Will fix DDL timeout in multi region clusters like in issue https://github.com/yugabyte/yugabyte-db/issues/4736.

**Comment by tlaguz** [comment]
This should be at least documented somewhere in these articles: https://docs.yugabyte.com/preview/deploy/multi-dc/

Moreover `--yb_client_admin_operation_timeout_sec` flag isn't documented even in https://docs.yugabyte.com/preview/reference/configuration/yb-tserver/ . Please check in google that the only places it exists are this two issues. 

A little description of my problem for google to index:
`ERROR:  Timed out: CreateDatabase RPC (request call id 47) to 10.10.1.100:9100 timed out after 120.000s` after `CREATE DATABASE test;` in multi-DC deployment. Ping between nodes is ~100ms. Setting `--yb_client_admin_operation_timeout_sec` to 180s resolved the issue. This flag should be set on `yb-tserver` which you are connected to while executing DDL.

**Comment by ddorian** [comment]
@tlaguz can you describe your cluster hardware (vcpu, memory, hdd/ssd) ?
