### ISSUE TITLE
[YSQL] wrong results when INSERT is followed by exception handler that isn't entered is present. 

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#4780]
This is YB-2.1.6.0 on MacOS Mojave Version 10.14.6. Single-node cluster. Self-contained testcase below.

**Problem:**

`select count(*)` (in a do block with an `assert`) following the error free completion of a call to a PL/pgSQL procedure that inserts 1,000 rows reports this:

```
ERROR:  count_rows(): assert failed: no. of inserted rows = 512
```

*DEGREES OF FREEDOM*

1. "no_assert_count_ok"

2. "exception_block"

For YB:
```
IF
  exception_block AND
  no_assert_count_ok
THEN
  bug
END IF;
```
In other words, if there's _NO_ exception block, or if you _do_ assert that the count is OK immediately after inserting the rows, then you _DON'T_ see the bug.

You see the bug even on the very first attempt after destroying and re-creating the cluster.

The bug NEVER occurs in PG.

The test case, as presented, has both degrees of freedom TRUE, so you _do_ see the bug.

The fact that simply doing `select count(*)`seems to be a Heisenberg effect.

We can see that the exception handler is never entered because the `raise info` output:
> generate_rows(): assert failed

isn't seen.
```
set client_min_messages = warning;
drop table if exists t cascade;
create table t(
  k serial primary key,
  v numeric not null);

create or replace procedure count_rows(no_of_rows in int)
  language plpgsql
as $body$
declare
  n constant int := (select count(*) from t);
begin
  assert
    n = no_of_rows,
  'count_rows(): assert failed: '||
    'no. of inserted rows = '||n;
end;
$body$;

create or replace procedure generate_rows(
  no_of_rows          in int,
  no_assert_count_ok  in boolean,
  exception_block     in boolean)
  language plpgsql
as $body$
declare
  agg numeric[] not null := '{0}';
begin
  insert into t(v)
    select generate_series(1, no_of_rows)::numeric;

  if NOT no_assert_count_ok then
    declare
      n constant int := (select count(*) from t);
    begin
      assert
        n = no_of_rows,
      'generate_rows(): assert failed: '||
        'no. of inserted rows = '||n;
    end;
  end if;

  if exception_block then
    begin
      execute 'create unique index t_v_unq on t(v)';
    exception when unique_violation then
      raise info 'generate_rows(): caught exception';
    end;
  else
    execute 'create unique index t_v_unq on t(v)';
  end if;
end;
$body$;

\set no_of_rows 1000
\echo :no_of_rows

call generate_rows(
  no_of_rows         => :no_of_rows,
  no_assert_count_ok => true,
  exception_block    => true);

call count_rows(:no_of_rows);
```

**Comment by mtakahar** [comment]
Verified again after landing the fix for #10303.
