### ISSUE TITLE
For on premise YB Platform Deployment - Provide an option to install backup utils

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#4783]
YB Platform packages custom backup utils for Public Cloud IaaS - Azure azcopy, AWS S3utils etc.... we should provide an option to install this during Universe deployment.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-295

**Comment by chirag-yb** [comment]
@WesleyW @streddy-yb We need a design review on this one. Simply adding an option on the universe creation won't work if it's an airgapped installation and for online installation packages may not exist in the local repos. We should explore the option if we can bundle s3cmd, azcopy, and gsutil as part of the build.

**Comment by daniel-yb** [comment]
Going to close this out since it is not relevant anymore.
