### ISSUE TITLE
After creating a new universe, it is missing from the Universes page

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4784]
The new universe that is being created only shows up after a page refresh.

**Comment by sshev** [comment]
UI part works fine - both `<Dashboard>` and `<ListUniverse>` components fetching up to date universes list when rendered
however corresponding endpoint `/api/customers/:uuid/universes` response sometimes doesn't contain newly created universe when called right after its creation
cc @Arnav15 @WesleyW

**Comment by sshev** [comment]
Redirect to universes list page happens before create universe API gives a response and thus newly created universe absent in the list. Fixed by waiting for API response and only then navigate to universes list page.
