### ISSUE TITLE
[docs] Add documentation for api/v1 master & tserver endpoints. 

### ISSUE THREAD

**Issue by vvkgopalan** [yugabyte/yugabyte-db#4787]
Would be helpful to have documentation for the master and tserver /api/v1 endpoints. Will write something up that comments on the format of the JSON object returned as well as the http response code in the event of error (in the scenario where there is no error payload and the response is a non-200 code).

The comment Bogdan had when I brought this up with him is that if these endpoints do get documented, we will need to maintain some notion of backwards compatibility in order to not break the flows of users that use them.
@schoudhury @stevebang

**Comment by polarweasel** [comment]
Closing this issue. The endpoint documentation, if we want to produce any, is a ways off yet.
