### ISSUE TITLE
Embed http proxy within yb platform to avoid need for deploying nginx

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4795]
Currently the yb platform software is deployed with an nginx container to allow redirects to the master/tserver web UI from within the platform UI. 

https://github.com/yugabyte/charts/blob/3dd4a6eafbbeb10992d9a6622900f04ed69eaed5/stable/yugaware/templates/service.yaml#L206

Writing a simple proxy endpoint or embedding a Java http proxy server library within the software would remove this install dependency. 

cc: @bmatican

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-288

**Comment by streddy-yb** [comment]
Verified that nginx no longer proxies master/t-server requests by checking /etc/nginx/conf.d/default.conf file. Also, verified all proxy requests are authenticated.
