### ISSUE TITLE
[dist-txns] logic to detect if an intent is potentially aborted is unnecessarily aggressive 

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#480]
We want to consider intents (provisional records) that are still sitting in the system beyond a threshold (60 seconds) to see if they correspond to aborted transactions that can now be cleaned up.

But the logic to check the threshold has a bug, and ends up being too aggressive in its decision on what intents to process. This doesn't affect correctness, but can cause the system to do wasteful work.

Here's the relevant snippet from: https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/docdb/docdb_compaction_filter_intents.cc#L93
```
    if (GetCurrentTimeMicros() - start_time.GetPhysicalValueMicros() >
	FLAGS_aborted_intent_cleanup_ms) {
      AddToSet(*result);
    }
```

Bug: LHS is in micros & RHS is in millisecs.

**Comment by rven1** [comment]
Fixed by rYB749601b6a9c6
