### ISSUE TITLE
[docdb] master UI make hash_split more readable

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4811]
The master UI table page shows tablets and their partitions.  If the table is default hash partitioned to two tablets, the partitions show as `hash_split: [<start>, 32767)` and `hash_split: [32767, <end>)`.  It's confusing at first glance, but `32767` maps to `0x7fff`, which is the middle hash code between `0x0000` and `0xffff`.  It would be more understandable if we used hex notation or the dockey string representation that is used for range partitioned tables (e.g. `range: [(<start>, DocKey([], [3])))`).  Do one of those changes to make this more readable.

**Comment by adzimzf** [comment]
Hi,
I interest to work on this, but since this is my first time, maybe it'll bit longer

**Comment by bmatican** [comment]
@adzimzf that would be perfectly fine! One suggestion, especially as this would be your first time contribution, might be useful to join our slack (http://yugabyte-db.slack.com/), as we could provide some more real time assistance in our #contributors channel.

**Comment by adzimzf** [comment]
Thank you @bmatican,
I'll try to read as much as I can first, if stuck I'll ask on the slack

**Comment by adzimzf** [comment]
Hi @bmatican I've created a PR for this issue,
please feel free to correct the PR, and sorry if there's a lot of mistakes :pray:

**Comment by jaki** [comment]
(From #6223) To clarify, this issue does not need to concern itself with YSQL tables which currently show no bounds for hash partitioning.  I can create a separate issue for that if none exists.
