### ISSUE TITLE
[YSQL] change PartitionSchemaPB.RangeSchemaPB.split_rows to bytes

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4825]
We might want to change `PartitionSchemaPB.RangeSchemaPB.split_rows` from `string` to `bytes`.  I believe this is fine (no backwards compatibility issues when we did something similar last time).

Very simple repro:

```sql
CREATE TABLE t (i int, PRIMARY KEY (i ASC)) SPLIT AT VALUES ((1));
```

Postgres logs:

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:629] String field 'yb.PartitionSchemaPB.RangeSchemaPB.split_rows' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

Despite the error, I don't notice any problems.  The tablets are created properly and contain the correct data according to split.

**Comment by jaki** [comment]
Some key words to help searchability (GH does not seem to split on period):

- PartitionSchemaPB
- RangeSchemaPB
- split_rows
- range partition

**Comment by Amargol** [comment]
Hello! I would like to work on this issue, is it still available? Thanks!

**Comment by jaki** [comment]
Hi, @Amargol!  It looks like this is outdated due to commit 78a726ab58a3f8d51f298c36336a2621a5b50598.  Thanks for bringing this to attention.
