### ISSUE TITLE
[dodcb] Enhance master health check API to detect quorums without leaders

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4836]
In the case of 2/3 TS failures for a tablet, the quorum would report 3 FOLLOWER nodes and would be unable to automatically exit this state without human intervention. However, we should have some higher level mechanism to detect this and potentially alert on this, if the tablet has been in this state for X amount of time.

**Comment by bmatican** [comment]
For starters, I'd say let's have a new debug page for Replication issues:
- we can start with something like this, as it's easy to trigger: just start an RF3 cluster, create a table, then stop 2 TS and check the table in `master_ip:7000/tables` -- should see 3 FOLLOWERs for all tablets
- we can then enhance it with other type of tablet issues, such as tablets that have different quorum configurations than they are supposed to, ie: num tablets != RF, or placement is different, etc. (can be a follow up task)

**Comment by robertsami** [comment]
changes to master admin page:
![image](https://user-images.githubusercontent.com/1457684/85635478-f5bf9f80-b64b-11ea-83d7-f04cc9e85dab.png)
![image](https://user-images.githubusercontent.com/1457684/85635494-fa845380-b64b-11ea-9c93-b06ab75c659e.png)
