### ISSUE TITLE
Create Index should only wait until the index is added to the main table

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#4841]
Currently the wait for create table waits until the indexed table is out of the altering state.

This can take a while, esp if there is backfill to be done and/or there are other unrelated changes being made to the main table.

We should clean this up. The create table should only wait until the current/fully_applied_schema begins to reflect the presence of the newly created index.

**Comment by amitanandaiyer** [comment]
If we need to wait for the backfill to be complete, that can be achieved by waiting in the client.h for WaitForIndexPermissionToBeAtleast.

**Comment by jaki** [comment]
Related issue #6234.

**Comment by jaki** [comment]
Several commits later, this is done for both YCQL and YSQL.  The last related commit I know of is 706397f7261c9852f4547f8c44efd46556c7e103.
