### ISSUE TITLE
[docdb] bad list of possible CPUs "3,7". Expected "0,n"

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#4845]
Jira Link: [DB-2520](https://yugabyte.atlassian.net/browse/DB-2520)

The error from the user 
![image](https://user-images.githubusercontent.com/1592898/85311766-34bbec80-b4b6-11ea-8c20-69106e91e585.png)

The cpus show correct when [queried by](https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1592148856055000) the user:
![image](https://user-images.githubusercontent.com/1592898/85312215-cdeb0300-b4b6-11ea-8f15-1c46bee4176b.png)

But error [when run on kubernetes](https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1592149192059300):

```
[root@node-1 jenkins]# kubectl logs yugadb-ybmasters-01
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0614 15:38:34.451272     1 sysinfo.cc:181] Check failed: 0 == memcmp(buf, "0-", 2) (0 vs. 1) bad list of possible CPUs: 1,5
*** Check failure stack trace: ***
```

Code path:
https://github.com/yugabyte/yugabyte-db/blob/25937adb6eadf7c7887814bf1e367fa1e9ad82d8/src/yb/gutil/sysinfo.cc#L171

**Comment by rthallamko3** [comment]
@ddorian , Do you know if this can be reproduced/is still an issue for the customer?

**Comment by ddorian** [comment]
I don't think so, it's very old.

**Comment by rthallamko3** [comment]
closing it as its quite old and doesn't seem relevant anymore.
