### ISSUE TITLE
[docdb] Investigate if TRUNCATE leaves behind rocksdb data

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4850]
A user noticed this in their testing, would be good to check if TRUNCATE correctly drops all SST files imediately.

The user report only included the data size on disk, so it's possible it might have actually been https://github.com/yugabyte/yugabyte-db/issues/4756

**Comment by rajukumaryb** [comment]
This does not appear to be a problem with 2.1.8 for a YCQL workload. 

Workload: `java -jar yb-sample-apps.jar --workload CassandraKeyValue --nodes 127.0.0.1:9042,127.0.0.2:9042,127.0.0.3:9042 --num_threads_read 0 --num_threads_write 4 --num_unique_keys 200000 --value_size 8192`

|| find ~/yugabyte-data/ -name "\*sst\*" -type f \| wc -l | du -sh ~/yugabyte-data/ |
|:--|:--:|:--:|
| Before Truncate | 110 | 16G |
| After Truncate | 2 | 9.2G |

**Comment by rajukumaryb** [comment]
Remainder of the disk space is used by wal and index files per tablet -

```
│                       ├── [4.0K]  tablet-796ab86c8ea543179fea0d7db1a7518c
│                       │   ├── [ 23M]  index.000000000
│                       │   ├── [1.0M]  wal-000000001
│                       │   ├── [2.0M]  wal-000000002
│                       │   ├── [4.0M]  wal-000000003
│                       │   ├── [8.0M]  wal-000000004
│                       │   ├── [ 16M]  wal-000000005
│                       │   ├── [ 32M]  wal-000000006
│                       │   ├── [ 64M]  wal-000000007
│                       │   ├── [ 64M]  wal-000000008
│                       │   ├── [ 64M]  wal-000000009
│                       │   ├── [ 64M]  wal-000000010
│                       │   ├── [ 64M]  wal-000000011
│                       │   ├── [ 64M]  wal-000000012
│                       │   ├── [ 64M]  wal-000000013
│                       │   ├── [ 64M]  wal-000000014
│                       │   ├── [ 64M]  wal-000000015
│                       │   └── [ 64M]  wal-000000016
```
