### ISSUE TITLE
[YSQL] Failed to SELECT after COPY high number of rows

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#4855]
Jira Link: [DB-2413](https://yugabyte.atlassian.net/browse/DB-2413)
After COPY a large file with many rows, SELECT would fail.
```
19248	[ts-1]	2020-06-23 15:25:24.549 UTC [9664] ERROR: Timed out: Read(tablet: TABLET5, num_ops: 1, num_attempts: 313, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 1976.435s (passed: 60.158s): Illegal state (yb/consensus/consensus.cc:150): Not the leader (tablet server error 15)
19249	[ts-1]	2020-06-23 15:25:24.549 UTC [9664] STATEMENT: SELECT * FROM airports WHERE type = 'closed' AND iso_region = 'US-CA';
```

**Error Log**
[ts1_log.txt](https://github.com/yugabyte/yugabyte-db/files/4820760/ts1_log.txt)

**Comment by ndeodhar** [comment]
Depends on
https://github.com/yugabyte/yugabyte-db/issues/1923
and https://github.com/yugabyte/yugabyte-db/issues/2855
