### ISSUE TITLE
YSQL, infra: Running unit tests against older existing databases

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#4856]
Currently unit-tests can only be run against the database that are constructed by the same build.
I'd like to be able run the unit tests against an older / existing databases.
Half of my bugs are compatibility issues, so it'd be a great help if we have the above support.

**Comment by mbautin** [comment]
We could pull initdb snapshots out of older release tar.gz archives and store them somewhere easily accessible (e.g. HTTP-enabled cloud bucket). Then unit tests could download and use an initdb snapshot from any older version.

**Comment by frozenspider** [comment]
Created a repo for storing initdb snapshots in releases: https://github.com/yugabyte/yugabyte-db-ysql-catalog-snapshots

**Comment by frozenspider** [comment]
FYI, using 2.0.9.0 snapshot for initdb with latest master in debug build casues it to crash with
```
F20210923 21:33:02 ../../src/yb/common/ql_value.h:123] Check failed: pb.BOOST_PP_CAT(has_, BOOST_PP_CAT(binary, _value))() Value: 
    @        0x1223a2ee3  google::LogDestination::LogToSinks()
    @        0x1223a214c  google::LogMessage::SendToLog()
    @        0x1223a2a45  google::LogMessage::Flush()
    @        0x1223a789f  google::LogMessageFatal::~LogMessageFatal()
    @        0x1223a3a59  google::LogMessageFatal::~LogMessageFatal()
    @        0x1100defbc  yb::QLValue::binary_value()
    @        0x1100d8d09  yb::QLValue::binary_value()
    @        0x1100d877a  yb::master::EnumerateSysCatalog()
    @        0x1100d775d  yb::master::EnumerateSysCatalog()
    @        0x1100710da  yb::master::SysCatalogTable::Visit()
    @        0x10fc1774e  yb::master::CatalogManager::Load<>()
    @        0x10fc16920  yb::master::CatalogManager::RunLoaders()
    @        0x110252abd  yb::master::enterprise::CatalogManager::RunLoaders()
    @        0x10fc104e0  yb::master::CatalogManager::VisitSysCatalog()
    @        0x10fc0ecc3  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @        0x10fd03769  yb::internal::RunnableAdapter<>::Run()
...
```
Release build works.

**Comment by frozenspider** [comment]
Implemented. Just 2.0.9.0 snapshot is available atm, and non-release builds won't work because of #10116
