### ISSUE TITLE
Set the default value of command line flag --metric_node_name to hostname or ip

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4859]
The command line flag `--metric_node_name` (defined at https://github.com/yugabyte/yugabyte-db/blob/b50f5b396f7b29ddd10ba0460f4c8b1682f5c7ba/src/yb/util/metrics.cc#L62) controls the host identification label that is used in Prometheus metrics (see https://github.com/yugabyte/yugabyte-db/blob/b50f5b396f7b29ddd10ba0460f4c8b1682f5c7ba/src/yb/util/metrics.cc#L326).

Currently, the default value of this gflag is "DEFAULT_NODE_NAME". It would be better if the default value was set as local host name + webserver_port, perhaps somewhere around https://github.com/yugabyte/yugabyte-db/blob/b50f5b396f7b29ddd10ba0460f4c8b1682f5c7ba/src/yb/master/master_main.cc#L71.

----------------
Note: To get started with this issue, you will need to compile the C++ source code locally. Please see https://docs.yugabyte.com/latest/contribute/core-database/build-from-src-macos/ for some guidance on the build process.

Once you compile the source code, the yb-ctl code (documented at https://docs.yugabyte.com/latest/admin/yb-ctl/) can help you start up a local cluster that you can use to test the changes you've made (/bin/yb-ctl destroy && bin/yb-ctl start --rf 1)

**Comment by vikramrajsitpal** [comment]
I would like to take this up. Is it still up for grabs? [but before I do, I just want to inform you that my Java code has not compiled (many errors) and the following C++ tests failed (on my CentOS VM):
	 47 - rocksdb_thread_list_test (Failed)
	139 - util_inetaddress-test (Failed)
	199 - consensus_log-test (Failed)
	222 - client_ql-transaction-test (Failed)
	263 - integration-tests_stepdown_under_load-test (Failed)
	286 - tools_yb-admin-test_ent (Failed)
	287 - tools_yb-backup-test_ent (Failed)
	305 - ql_ql-query-test (Failed)
	319 - cqlserver_cqlserver-test (Failed)
	320 - redisserver_redisserver-test (Failed)
	327 - pgwrapper_pg_wrapper-test (Failed)
	328 - pgwrapper_pg_libpq-test (Failed)
	330 - pgwrapper_pg_on_conflict-test (Failed)
	331 - pgwrapper_pg_mini-test (Failed)
]

**Comment by iSignal** [comment]
Hello @vikramrajsitpal, welcome! feel free to take this up and assign it to yourself. 

You should not need to touch the Java code for this fix. For the C++ test, a few of them have intermittent failures and that typically should not block this fix. You can go through the deployment checklist here - https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/ - to make sure the appropriate ulimits and other config are set.

**Comment by vikramrajsitpal** [comment]
Thanks! I did complete the checklist before my build completed. I mentioned a few C++ test failures, but if you say these won't affect this issue, I am gonna go ahead and check it out.
