### ISSUE TITLE
[YEDIS]  ZRANGEBYSCORE returns duplicate members

### ISSUE THREAD

**Issue by Ceyword** [yugabyte/yugabyte-db#4862]
Consider this:

YEDIS:0>LISTDB
 1)  "0"

YEDIS:0>ZADD abcd INCR 1.0  val1
"1"

YEDIS:0>ZADD abcd INCR 1.0  val2
"1"

YEDIS:0>ZADD abcd INCR 1.0  val3
"1"

YEDIS:0>ZADD abcd INCR 1.0  val1
"0"

YEDIS:0>ZADD abcd INCR 1.0  val2
"0"

YEDIS:0>ZADD abcd INCR 1.0  val3
"0"

YEDIS:0>ZSCORE abcd  val1
"2.000000"

**YEDIS:0>ZRANGEBYSCORE abcd -inf +inf  WITHSCORES
 1)  "val1"
 2)  "1.000000"
 3)  "val2"
 4)  "1.000000"
 5)  "val3"
 6)  "1.000000"
 7)  "val1"
 8)  "2.000000"
 9)  "val2"
 10)  "2.000000"
 11)  "val3"
 12)  "2.000000"

This result is confusing my Redis client library and forcing it to return, for ZRANGEBYSCORE 
 1)  "val1"
 2)  "1.000000"
 3)  "val2"
 4)  "1.000000"
 5)  "val3"
 6)  "1.000000"

when ZSCORE abcd  val 1(or val2 or val3) is not "1.000000"**

**Comment by rahuldesirazu** [comment]
@Ceyword Just landed the fix for this issue.
