### ISSUE TITLE
[Platform] Web-based vulnerability scan fixes 

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#4863]
Fix all issues at or above level 3 identified by a web-based vulnerability scan on Yugabyte Platform.

**Comment by rkarthik007** [comment]
All of the level 5 and most of the level 3 issues have been fixed. The rest of the work will be tracked under https://github.com/yugabyte/yugabyte-db/issues/4420

* There are a couple of outstanding issues - @daniel-yb is opening separate issues for these.
* There are some changes required to the nginx.conf in order to harden the setup. @daniel-yb will open separate issues to make these changes into the product.

**Comment by daniel-yb** [comment]
To fix Slow HTTP Post vulnerability, client_header_timeout and client_body_timeout should be set in the server location of nginx conf to as low of a value as reasonably possible depending on the network speed of network containing YW installation. For testing purposes, I set both of these values to 4s.
**Test Without Protection Enabled**
[Failure.pdf](https://github.com/yugabyte/yugabyte-db/files/4969448/Failure.pdf)
**Test With Protection Enabled**
[Success.pdf](https://github.com/yugabyte/yugabyte-db/files/4969449/Success.pdf)
