### ISSUE TITLE
[YSQL] Backup for colocated databases

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4874]
Add support to do a distributed back up for colocated databases.

Since a colocation tablet includes table ID in the row key, we need to preserve the table IDs during restore. This will require the following changes:
1. `ysql_dump` to add a `WITH TABLEID=xx` clause to `CREATE TABLE` statement.
2. YSQL should support `WITH TABLEID` clause to create a table with the specified OID if it does not already exist.

**Comment by frozenspider** [comment]
This has been implemented, and is currently being reworked to use `colocation_id` instead of `table_oid`: #7378
