### ISSUE TITLE
snapshot async tasks should have exponential backoff and max limit

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#4878]
Jira Link: [DB-1458](https://yugabyte.atlassian.net/browse/DB-1458)
In one instance we saw that yb-master kept retrying tablet snapshot operations indefinitely at 21ms intervals.

```
I0620 00:07:59.927392 27630 async_rpc_tasks.cc:303] 888688896d4f4a6186b6bfd7f9b49b90 (table afp [id=c065a66f28cf4f98b0356bf546cba297]) Tablet Snapshot Operation 1 RPC (task=0xf5be010, state=kWaiting): Scheduling retry with a delay of 21ms (attempt = 0)...
I0620 00:07:59.927434 27630 async_rpc_tasks.cc:303] 7de22a85ef934d7ba2211d67243736e7 (table afp [id=c065a66f28cf4f98b0356bf546cba297]) Tablet Snapshot Operation 1 RPC (task=0xf5be1b0, state=kWaiting): Scheduling retry with a delay of 21ms (attempt = 0)...
I0620 00:07:59.927448 27630 async_rpc_tasks.cc:303] d7caa7c429384626884dd944a1693bce (table afp [id=c065a66f28cf4f98b0356bf546cba297]) Tablet Snapshot Operation 1 RPC (task=0xf5be350, state=kWaiting): Scheduling retry with a delay of 21ms (attempt = 0)...
I0620 00:07:59.927459 27630 async_rpc_tasks.cc:303] 4e8767d6277b41ff9678fe8c3fea7978 (table afp [id=c065a66f28cf4f98b0356bf546cba297]) Tablet Snapshot Operation 1 RPC (task=0xf5be4f0, state=kWaiting): Scheduling retry with a delay of 21ms (attempt = 0)...
```

While the root cause of this has been fixed, it'll be good to add further safety net to make sure that:

* we have a max limit on number of times a job is retried
* we add some exponential backoff to the retry attempt.

**Comment by bmatican** [comment]
@kmuthukk It's possible this was the same issue as https://github.com/yugabyte/yugabyte-db/issues/4302, since a bunch of TS were not heartbeating, so some tablets might not have had a leader, in the master info.

The fix for that was just a 2 line change, so it was integrated into 449ba58e66b15f03cdd4300e638bec7b258e831e
