### ISSUE TITLE
Load init SQL script in docker-compose.

### ISSUE THREAD

**Issue by maksum14** [yugabyte/yugabyte-db#4880]
I'm interesting how to load init SQL script in docker-compose. We are using Postgres driver and before for postgres image our config :
 volumes:
      - ./src/main/resources/sql/10_initial_schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
      - ./src/test/resources/sql/10_test_users.sql:/docker-entrypoint-initdb.d/10_users.sql
how to achieve same thing in yugabytedb/yugabyte image?

**Comment by rkarthik007** [comment]
Hi @maksum14 - is your intention to run this init script after the DB is up and running in docker compose? I think you would need a init script that does the following:
* Wait for the DB to be "ready"
* Run your SQL schema script
* Load the data

Does that sound right?

**Comment by iSignal** [comment]
@rkarthik007 : there is an initialization script in the postgres docker container at https://hub.docker.com/_/postgres - search for "Initialization scripts". 

> After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service`

**Comment by maksum14** [comment]
@iSignal  yes that correct flow for postgres image, can yugabyte implement similar things for looking in sql directory and execute scripts in asc order ?

**Comment by iSignal** [comment]
@maksum14 : we will look into implementing this functionality soon. Thanks for the suggestion.

**Comment by baba230896** [comment]
@maksum14 
Now YugabyteDB docker image supports the initialization scripts. [From here,](https://github.com/yugabyte/yugabyte-db/pull/5793) you can take a look at the merged PR.
Please use the following command to explore this feature: 
```sh
docker run -d -v /home/ubuntu/initial-scripts:/tmp/initial-scripts yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false --ui=false --initial_scripts_dir=/tmp/initial-scripts/
```
For more, refer to this documentation: https://docs.yugabyte.com/latest/reference/configuration/yugabyted/

**Comment by baba230896** [comment]
@maksum14 
You can use this feature from the YB v2.3.3.0. I'm closing this issue for now.
