### ISSUE TITLE
[YCQL] With index created on column which is a prefix of another column, Select queries fail with 'Column doesn't exist'.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#4881]
When we create table with indexes where one column is a prefix of the other column, the select queries that use both the column fail with "Column doesn't exist" error.

Steps to reproduce:
```
ycqlsh:ybdemo_keyspace> create table benchmark_table_0405 (k text, v text, v1 text, primary key(k)) WITH transactions = { 'enabled' : true };
ycqlsh:ybdemo_keyspace> create index idx on benchmark_table_0405 (v);
ycqlsh:ybdemo_keyspace>  create index idx1 on benchmark_table_0405 (v1);
ycqlsh:ybdemo_keyspace>
ycqlsh:ybdemo_keyspace> select * from benchmark_table_0405 where v = 'def' and v1 = 'efg';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined Column. Column doesn't exist
select * from benchmark_table_0405 where v = 'def' and v1 = 'efg';
                                                       ^^
 (ql error -203)"
```

Note that without indexes the problem doesn't exist.
```
ycqlsh:ybdemo_keyspace> create table benchmark_table_0405 (k text, v text, v1 text, primary key(k)) WITH transactions = { 'enabled' : true };
ycqlsh:ybdemo_keyspace> insert into benchmark_table_0405 (k,v,v1) values ('abc', 'def', 'efg');
ycqlsh:ybdemo_keyspace> select * from benchmark_table_0405 where v = 'def' and v1 = 'efg';
 k   | v   | v1
-----+-----+-----
 abc | def | efg

```

Also this is a problem only when one column is a prefix of the other:
```
ycqlsh:ybdemo_keyspace> create table benchmark_table_0405 (k text, v2 text, v1 text, primary key(k)) WITH transactions = { 'enabled' : true };
ycqlsh:ybdemo_keyspace> create index idx1 on benchmark_table_0405 (v1);
ycqlsh:ybdemo_keyspace> create index idx2 on benchmark_table_0405 (v2);
ycqlsh:ybdemo_keyspace>  insert into benchmark_table_0405 (k,v1,v2) values ('abc', 'def', 'efg');
ycqlsh:ybdemo_keyspace> select * from benchmark_table_0405 where v1 = 'def' and v2 = 'efg';
 k   | v2  | v1
-----+-----+-----
 abc | efg | def
```

**Comment by rao-vasireddy** [comment]
Another fail case -

ycqlsh:foo> create table benchmark_table_0405 (k text, v text, v1 text, primary key(k)) WITH transactions = { 'enabled' : true };
ycqlsh:foo> create index idx1 on benchmark_table_0405 (v);
ycqlsh:foo> create index idx2 on benchmark_table_0405 (v1);
ycqlsh:foo> select * from benchmark_table_0405 where v1 = 'def' and v2 = 'efg';                      
InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined Column. Column doesn't exist
select * from benchmark_table_0405 where v1 = 'def' and v2 = 'efg';
                                                        ^^
 (ql error -203)"
ycqlsh:foo> select * from benchmark_table_0405 where v1 = 'def' order by v2;
NoHostAvailable:

FATAL - 

F20200627 11:29:11 ../../src/yb/yql/cql/ql/ptree/pt_expr.cc:118] Check failed: has_valid_internal_type() && has_valid_ql_type_id() 
    @        0x1090f7cf0  google::LogDestination::LogToSinks()
    @        0x1090f6d1a  google::LogMessage::SendToLog()
    @        0x1090f76c5  google::LogMessage::Flush()
    @        0x1090fc58f  google::LogMessageFatal::~LogMessageFatal()
    @        0x1090f8699  google::LogMessageFatal::~LogMessageFatal()
    @        0x105645a84  yb::ql::PTExpr::CheckExpectedTypeCompatibility()
    @        0x10563e535  yb::ql::PTExpr0<>::Analyze()
    @        0x105633bf1  yb::ql::PTOrderBy::Analyze()
    @        0x10562ef4e  yb::ql::PTSelectStmt::AnalyzeOrderByClause()
    @        0x10562d2ff  yb::ql::PTSelectStmt::Analyze()
    @        0x10562ea2f  yb::ql::PTSelectStmt::AnalyzeIndexes()
    @        0x10562d2ce  yb::ql::PTSelectStmt::Analyze()
    @        0x1055ed38f  yb::ql::ParseTree::Analyze()
    @        0x10533658d  yb::ql::Analyzer::Analyze()
    @        0x1053093dd  yb::ql::QLProcessor::Analyze()
    @        0x10530958a  yb::ql::QLProcessor::Prepare()
    @        0x10530cfea  yb::ql::QLProcessor::RunAsync()
    @        0x104b3737f  yb::cqlserver::CQLProcessor::ProcessRequest()
    @        0x104b35ace  yb::cqlserver::CQLProcessor::ProcessRequest()
    @        0x104b3576f  yb::cqlserver::CQLProcessor::ProcessCall()
    @        0x104b5ab37  yb::cqlserver::CQLServiceImpl::Handle()
    @        0x10842ed0c  yb::rpc::ServicePoolImpl::Handle()
    @        0x1083d4d93  yb::rpc::InboundCall::InboundCallTask::Run()
    @        0x10843da99  yb::rpc::(anonymous namespace)::Worker::Execute()
    @        0x108bfb513  yb::Thread::SuperviseThread()
    @     0x7fff6ffa4109  _pthread_start
    @     0x7fff6ff9fb8b  thread_start

**Comment by rao-vasireddy** [comment]
https://github.com/yugabyte/yugabyte-db/issues/4908 is for  a related issue.

**Comment by nocaway** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/72af174aaebbb85ef1cf40bed6979787b99c5c3b
A language extension to support INDEX by different expressions would require changes reported in #4932

**Comment by kmuthukk** [comment]
@nocaway -- can we close this issue now?

**Comment by nocaway** [comment]
This was fixed by https://github.com/yugabyte/yugabyte-db/commit/cce77ad087402d9fb8f43b33b89698b92e6dfc60
( ALL previous commits on code changes and tests for this issue had been reverted ).
