### ISSUE TITLE
[docdb] ycql rpcz URL is wrong when clicking the "YCQL Live Ops" link in the tserver utilities page

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4886]
tested with 2.2.0.0-b16

**Comment by bmatican** [comment]
For reference, I see this showing up in the URL that gets displayed: `[10.150.0.52:9042]:12000/rpcz`, so might be some of the recent ipv6 work that Sanketh did.

Interestingly enough, the TS Live Ops renders just fine!
