### ISSUE TITLE
CREATE OR REPLACE [TEMP] VIEW  in YSQL Not Working 

### ISSUE THREAD

**Issue by ngov17** [yugabyte/yugabyte-db#4888]
Jira Link: [DB-1478](https://yugabyte.atlassian.net/browse/DB-1478)
Whenever a view is created using `CREATE OR REPLACE [TEMP] VIEW` and another view of the same name is created subsequently, the following error arises: 
`ERROR:  Alter table is not yet supported`.

YSQL requires you to drop the view to update it even though  `CREATE OR REPLACE [TEMP] VIEW` is supposed to replace (update) a view if one of the same name already exists.

**Comment by tverona1** [comment]
This works as expected.
