### ISSUE TITLE
Merge-related log spew when running DBTest.PinnedDataIteratorRandomized

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4893]
Jira Link: [DB-1555](https://yugabyte.atlassian.net/browse/DB-1555)
W0625 22:55:35.187930 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.187988 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188117 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188186 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188243 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188438 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188477 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188556 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188597 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188817 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188887 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188925 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.188997 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189013 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189057 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189164 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189224 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189235 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189280 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189321 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189364 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189379 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189421 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189491 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):
W0625 22:55:35.189579 128925696 compaction_iterator.cc:385] Merge until failed: Merge in progress (yb/rocksdb/db/merge_helper.cc:262):

(Also I think we need to remove the merge feature from RocksDB because we are not using it nor do we anticipate that we would.)

**Comment by rthallamko3** [comment]
@yusong-yan , This one seems like a quick fix. Can you check with @jmeehan16 in case you have questions.
