### ISSUE TITLE
[YSQL] Backfill unique indexes

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4899]
Handle unique indexes for multi-stage backfill.  This is the YSQL counterpart of issue #3891.  Issue #4786 partially depends on this for `CREATE TABLE (UNIQUE)`.

**Comment by frozenspider** [comment]
@jaki : to not forget, please implement a test to check that on conflict (and on tserver crash), an index is deleted from YB, and YSQL sees it as `INVALID`.
