### ISSUE TITLE
Poor performance for queries which target multiple separate primary keys

### ISSUE THREAD

**Issue by nickhristov** [YugaByte/yugabyte-db#49]
Suppose we have the following table:

my_table
id_type, id_value, some_attribute

with primary key (id_type, id_value). There is no clustering column.

Queries of the form:

`SELECT * FROM my_table WHERE id_type = 'foo' AND id_value = 'bar'` and `SELECT * FROM my_table WHERE id_type IN ('foo') AND id_value IN ('bar')` seem to perform quite well.

However, with queries of the form `SELECT * FROM my_table WHERE id_type = 'foo' AND id_value IN ( 'bar', 'baz')` we run into performance problems. These queries tend to perform about 1000 times worse on our installation than single key queries.

My expectation is that these queries will perform at worst N times the single key query, where N is the number of expected primary keys to hit + some marginal overhead. This also assumes that these queries will execute serially to one another, which does not have to be the case.

Since I am querying against a table which has no clustering column, the  maximum number of records which I can get is going to be the equal to the number of expected primary keys (it's a permutation of the key columns specified in the select statement).

**Comment by kmuthukk** [comment]
@nickhristov : thanks for reporting the issue. 

One comment, with CQL's CREATE TABLE syntax:
    PRIMARY KEY (col_a, col_b)
is effectively same as:
    PRIMARY KEY ((col_a), col_b)
and both would result in col_a being hash/partition column, and col_b being a clustering column,

If you wanted both columns be part of the hash/partition columns in the PRIMARY KEY, then you'll need an extra set of parens as below:
   PRIMARY KEY ((col_a, col_b))

Nevertheless, in either case, looks like we do have an issue with the IN clause not being optimized to do an index lookup - and it might be that we are doing a scan here instead. We will get a fix out to you soon.

@m-iancu : Assigning this to you.
