### ISSUE TITLE
CMakeLists.txt should read the thirdparty_path.txt file from the build directory

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4905]
If YB_THIRDPARTY_DIR is not set (e.g. when building code from CLion), CMakeLists.txt should check the thirdparty_path.txt file from the build directory, so that builds from CLion and from console are consistent.

Requested by @spolitov 

Also we should probably do the same for YB_LINUXBREW_DIR (the corresponding file name in the build dir is linuxbrew_path.txt).

**Comment by frozenspider** [comment]
FYI, `YB_THIRDPARTY_DIR` env var can be set through CLion configuration manually:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2077017/86254798-cff84480-bbcf-11ea-9c55-ddcecb4ffe05.png">

**Comment by spolitov** [comment]
That would not work if 3rd party is downloaded since dir will be changed on each update.

**Comment by svarnau** [comment]
I'm not really a CLion user to properly test that use case.  But I think the change needed would be:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 29fa16631..25fd3ca72 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -439,7 +439,11 @@ message("YB_SRC_ROOT: ${YB_SRC_ROOT}")
 
 set(YB_THIRDPARTY_DIR "$ENV{YB_THIRDPARTY_DIR}")
 if("${YB_THIRDPARTY_DIR}" STREQUAL "")
-  set(YB_THIRDPARTY_DIR "${YB_SRC_ROOT}/thirdparty")
+  if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/thirdparty_path.txt")
+    file(READ "${CMAKE_CURRENT_BINARY_DIR}/thirdparty_path.txt" YB_THIRDPARTY_DIR)
+  else()
+    set(YB_THIRDPARTY_DIR "${YB_SRC_ROOT}/thirdparty")
+  endif()
 endif()
 message("YB_THIRDPARTY_DIR: ${YB_THIRDPARTY_DIR}")
 

```

**Comment by mbautin** [comment]
@svarnau -- this looks right. We should probably do the same for the Linuxbrew path.
@frozenspider would you be able to test @svarnau's patch(es) on this issue and verify it is working correctly for you in CLion?

**Comment by mbautin** [comment]
@svarnau and for YB_LINUXBREW_DIR, we should export it to the environment by setting `$ENV{YB_LINUXBREW_DIR}`, if there is a way to do that from CMakeLists.txt, so that if we end up invoking the thirdparty build from CMakeLists.txt, the linuxbrew dir would be set correctly.

**Comment by svarnau** [comment]
Two Issues identified with this fix:
1) Problem results if thirdparty_path.txt file has newline.
2) CMake will try to build thirdparty even if it is a downloaded directory.
