### ISSUE TITLE
Redis connection refused in latest docker image.

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#4907]
I just pulled latest yugabyte docker image 8 days ago and run it with this command:
`docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 -p6379:6379 -v yb_data2:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false --ui=false`

and then i initiate redis with this command:
`docker exec -it 46983846869b /home/yugabyte/bin/yb-admin --master_addresses 127.0.0.1:7100 setup_redis_table`
 but i'm unable to connect with redis api:

```
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

**Comment by schoudhury** [comment]
the yedis api is not a focus for all new work including yugabyted so we won't be able to debug this. pls let us know if you face issues with ysql or ycql apis.

**Comment by zeinali0** [comment]
Thank You.

**Comment by anjmao** [comment]
@zeinali0 Looks that your --master_addresses is not valid. Try using private ip of the nic on which master is running. Check with `netstat -tupan | grep 7100` and use that private IP instead of 127.0.0.1.
