### ISSUE TITLE
[docdb] Enhance sys_catalog write abstraction to atomically update items of different types

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4912]
Currently we have 3 simple abstractions for Add/Mutate/Delete, which work with single items or vectors of items. These are templated methods, so they support all types of items we would write to sys_catalog.

We should be able to enhance these to take in a vector of baseclass, so that we can atomically write different types of items at the same time and not risk having to worry about failure modes in between certain writes.

Moreover, since sys_catalog is implemented as a YCQL table, we might also be able to just get rid of the Add vs Mutate, which translate underneath to INSERT vs UPDATE operations, since I believe in YCQL, all writes are upserts.

**Comment by ttyusupov** [comment]
Resolved by https://github.com/yugabyte/yugabyte-db/commit/11feb327d5a4e23b6bb06c5c3900d81779e5873a
