### ISSUE TITLE
[docs] Need more detailed description about Metrics

### ISSUE THREAD

**Issue by ricemaster** [yugabyte/yugabyte-db#4922]
Hi guys,

I’m looking at the Metrics page(http://[ip]:7000/metrics) from Utilities. There are more than 400 items. So I’m wondering if there’s a manual including all the meanings or description of each item in metrics?

Thanks.

**Comment by iSignal** [comment]
There are two ways we could enhance the metrics descriptions:

1. Add the more detailed information we have in the [metric definition in the source code](https://github.com/yugabyte/yugabyte-db/blob/65cf9e40c21de5550648f8d42091c950d5049a68/src/yb/consensus/raft_consensus.cc#L145) to the metrics and prometheus-metrics endpoints. For ex: node exporter exports prometheus metrics with comments explaining the metrics like:
```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 3.8996e-05
go_gc_duration_seconds{quantile="0.25"} 4.5926e-05
# etc.
```

Prometheus also has a mechanism to query metadata through another endpoint to discover more detailed descriptions - https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata. This metadata also [flows to Grafana](https://grafana.com/blog/2020/06/15/how-we-made-working-with-prometheus-easier-with-metric-metadata-in-grafanas-explore-view/), so it would be useful to export this.

2. Add separate documentation for some key metrics to a separate docs page. This may go out of sync with the code so maybe only do this for really key metrics.

**Comment by polarweasel** [comment]
We're addressing this one in a separate effort. Closing this ticket.
