### ISSUE TITLE
Should we use HAProxy to load balance between YB-TServers?

### ISSUE THREAD

**Issue by ptq204** [yugabyte/yugabyte-db#4923]
Hi,
My deployment model 3 YB-TServers and 3 YB-Masters distributed on 3 nodes. Also we have 1 HAProxy on another node to perform load balance between YB-TServers so clients call requests to HAProxy instead of YB-TServers. Because we use sysbench to benchmark which takes only one host and port in the config file so we use the host and port of HAProxy. Does that model degrade YugabyteDB performance?

![model-deploy-yb](https://user-images.githubusercontent.com/27961917/86111916-876a5980-baf1-11ea-9719-0d66145c5de6.png)

Many thanks

**Comment by ddorian** [comment]
Hi @ptq204 
Which API are you using, YCQL or YSQL ?

In this case, Nginx/Haproxy will add latency because of extra network hops but the performance on yb-tserver process will not degrade.

cc @psudheer21 do we provide multiple hosts option in our fork ?

**Comment by psudheer21** [comment]
We don't yet provide the option to set multiple hosts in our fork.

**Comment by ddorian** [comment]
@ptq204 please reopen if you have further questions.
