### ISSUE TITLE
[Platform] All processes should be stopped when releasing an instance or deleting a universe in the on-prem flow

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4953]
Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-209

**Comment by WesleyW** [comment]
Still needs work. Release should basically send a kill signal to the master and tserver processes on the node

**Comment by WesleyW** [comment]
Currently in review, added the stopMaster and stopTserver tasks when doing a DestroyUniverse or ReleaseInstance operation
