### ISSUE TITLE
[YW] Allow downloading root certificate from YW for CQL client connectivity

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4957]
Steps to reproduce:
1) Create universe with SSL/TLS enabled for client-node and node-to-node enabled.
2) Download the certificate and key for user cassandra from the Certificates menu in Platform

```
$ export SSL_CERTFILE=~/Downloads/yugabytedb.crt
$ export SSL_KEYFILE=~/Downloads/yugabytedb.key
$ yugabyte-client-2.1/bin/cqlsh --ssl 172.152.57.154 -u cassandra -p cassandra
Connection error: ('Unable to connect to any servers', {'172.152.57.154': error(1, u"Tried connecting to [('172.152.57.154', 9042)]. Last error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)")})
```

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-206

**Comment by ajcaldera1** [comment]
@daniel-yb Gave me the workaround of setting SSL_VALIDATE=false to skip hostname validation. This is fine for development environments but not production.

**Comment by rkarthik007** [comment]
Summary of offline discussions: this needs to be a change in our documentation on how this feature works. The CQL authentication documentation is incorrect.

@iSignal @Arnav15 - can you please summarize?

**Comment by iSignal** [comment]
Summary of findings so far: 
1. Client side encryption in transit (TLS) is supported for both CQL and SQL.
2. Client authentication using a separate client key is supported only for SQL, not for CQL. This is however, supported in base Cassandra as documented at https://docs.datastax.com/en/developer/java-driver/3.0/manual/ssl/.

Todo actions:

1. Update docs at https://docs.yugabyte.com/latest/secure/tls-encryption/connect-to-cluster/ to remove references to SSL_USERCERT, SSL_USERKEY for CQL - they aren't respected and I don't see references to these env in our cqlsh repo. (@stevebang )


2. Add an option to download the root cert from YW so clients can use encryption in transit to securely connect to YW created clusters. (@Arnav15 )

**Comment by rkarthik007** [comment]
> Update docs at https://docs.yugabyte.com/latest/secure/tls-encryption/connect-to-cluster/ to remove references to SSL_USERCERT, SSL_USERKEY for CQL - they aren't respected and I don't see references to these env in our cqlsh repo. (@stevebang )

@iSignal - could you please create a separate task for this? We can track the progress separately.

**Comment by iSignal** [comment]
https://github.com/yugabyte/yugabyte-db/issues/5521 is the UI side of the download root cert.
