### ISSUE TITLE
[DocDB] Track memory consumed by retryable RPCs

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#4971]
Jira Link: [DB-1323](https://yugabyte.atlassian.net/browse/DB-1323)
We use retryable RPCs quite frequently. For instance, read and write could be retried.
Sometimes those RPCs could reside in the memory for a quite long time.
And memory consumed by those RPCs could be significant.
We should track the memory consumed by them.

[DB-1323]: https://yugabyte.atlassian.net/browse/DB-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@spolitov , Was this task intended to capture the memory associated with retryable requests or retryable RPCs? cc @Huqicheng , @chinmay291
