### ISSUE TITLE
Delete unused/failed checkpoints created for remote bootstrap

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#498]
Currently, checkpoints might be not deleted after remote bootstrap has failed.

**Comment by hectorgcr** [comment]
@ttyusupov I'm assuming you meant that we leave directories for tservers that crashed during the remote bootstrap. We do have code to delete the directory if the remote bootstrap finishes, regardless whether the remote bootstrap failed or succeeded. It is in `RemoteBootstrapSession::~RemoteBootstrapSession()`
