### ISSUE TITLE
[docdb] Backups from YW require better IO throttling

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4987]
This was on puppy-food-4.

We were doing a multi-table backup across 3 tables, transactionally. One of the table had some tablets >3GB in size.

After some investigation, turns out the problem is mostly by our backup tooling doing unthrottled IO:
- yb_backup uses sha256sum to compute hashes for the related files
- s3cmd sync also internally does md5 hash computations
- s3cmd and the related s3 config have no throttling enabled
- yb_backup has a parallelism setting (default 8), which dictates how many s3cmd commands will run in parallel
- yb_backup seems to go the required tablets somehow serially, per TS, which means it might bottleneck one TS at a time
cc @OlegLoginov @daniel-yb @WesleyW 

Moving the previous YB related notes as a comment.

**Comment by bmatican** [comment]
After some digging, turns our the main problem here is our yb_backup usage pattern between, between hashing (md5/sha256sum), rate limiting on the IO/network usage of the s3cmd commands themselves, as well as parallelism, both total number of outstanding calls and the fact that they're not well spread across TS to at least spread the IO problems

@WesleyW @Arnav15 might need your help to get some quick fixes in here cc @OlegLoginov

**Comment by bmatican** [comment]
Updated main issue content, moving previous YB related stack info as a comment, in case they're still relevant later.

Potentially relevant stacks on one of the TS, the others do not have these stacks:
```
    @     0x7f5704d0911f  (unknown)
    @     0x7f57056843b7  __pthread_cond_timedwait
    @     0x7f57130182a6  yb::log::Log::WaitForSafeOpIdToApply()
    @     0x7f57132e0ac7  yb::consensus::RaftConsensus::WaitForWrites()
    @     0x7f57132efba3  yb::consensus::RaftConsensus::Update()
    @     0x7f5713f589f0  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x7f5710833cb9  yb::consensus::ConsensusServiceIf::Handle()
    @     0x7f570c6201d8  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f570c5c3063  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f570c62bf27  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f570ae5bc6e  yb::Thread::SuperviseThread()
    @     0x7f570567f693  start_thread
    @     0x7f5704dbc41c  __clone
    @ 0xffffffffffffffff  (unknown)
Total number of threads: 4
```
and
```
    @     0x7f5704d0911f  (unknown)
    @     0x7f57056843b7  __pthread_cond_timedwait
    @     0x7f57130182a6  yb::log::Log::WaitForSafeOpIdToApply()
    @     0x7f57132d8d5a  yb::consensus::RaftConsensus::WaitForSafeOpIdToApply()
    @     0x7f571330199e  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @     0x7f57133025fe  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x7f5713302bce  yb::consensus::ReplicaState::UpdateMajorityReplicatedUnlocked()
    @     0x7f57132dbf5a  yb::consensus::RaftConsensus::UpdateMajorityReplicated()
    @     0x7f57132bea9d  yb::consensus::PeerMessageQueue::NotifyObserversOfMajorityReplOpChangeTask()
    @     0x7f570ae5f493  yb::ThreadPool::DispatchThread()
    @     0x7f570ae5bc6e  yb::Thread::SuperviseThread()
    @     0x7f570567f693  start_thread
    @     0x7f5704dbc41c  __clone
    @ 0xffffffffffffffff  (unknown)
Total number of threads: 3
```

**Comment by bmatican** [comment]
Example throttle suggestion from Google: https://cloud.google.com/storage/docs/gsutil/addlhelp/Throttlinggsutil
- Using `ionice`, I tried using the best effort class and 0 vs 7 between yb-tserver vs s3cmd/sha256sum (by making yb_backup explicitly call these with the correct ionice flags), but this did not seem to do much..
- Using `trickle` would require that we install it everywhere and I've also not tried it. Moreover, we'd have to figure out how to trickle an entire directory, as I think now we use `sync`, to move out an entire directory

**Comment by daniel-yb** [comment]
Going to followup the mostly yb_backup level changes made under this ticket with #5283 so that the platform can control the parallelism in the backup script.

**Comment by daniel-yb** [comment]
**Ops before and after changes (Same level of parallelism cluster-wide)**
<img width="500" alt="Screen Shot 2020-08-01 at 1 29 56 PM" src="https://user-images.githubusercontent.com/54864769/89326911-f16da580-d63f-11ea-8816-6bb58a888035.png">

**Single Node Metrics**
<img width="1521" alt="puppy-food-4-8-threads (new, old without checksum, old with checksum)" src="https://user-images.githubusercontent.com/54864769/89327592-03037d00-d641-11ea-9319-08c4ccf66c99.png">

**Cluster Wide Node Metrics**
<img width="1571" alt="Screen Shot 2020-08-01 at 1 27 39 PM" src="https://user-images.githubusercontent.com/54864769/89327824-58d82500-d641-11ea-860b-886625c7f9c9.png">
