### ISSUE TITLE
[YSQL] Use --serializable-deferrable by default for ysql_dump

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4990]
This will help ysql_dump work with concurrent writes on the database without any read restart errors.
This will also help YSQL distributed backups run more reliably.

**Comment by kmuthukk** [comment]
@OlegLoginov -- if this has been committed, can we close out the issue?

**Comment by ndeodhar** [comment]
@kmuthukk @OlegLoginov Let's not close this. We've changed yb_backup.py to use `--serializable-deferrable` to make backups reliable (and independent of what defaults we have for `ysql_dump`).

But this issue also tracks changing the default in `ysql_dump` itself too.

**Comment by OlegLoginov** [comment]
@ndeodhar I thought the issue means adding the argument ` --serializable-deferrabl` when the `ysql_dump` called from `yb_backup.py`. And it is fixed and the issue can be closed.

Do you mean that the `ysql_dump` source code should be changed to use this special mode by default - without the `--serializable-deferrabl` flag?

**Comment by OlegLoginov** [comment]
[Neha] Yes I meant ysql_dump should use serializable deferrable mode by default.
[Oleg] Should we do something to be able desabling the 'serializable deferrable' mode?
[Neha] Yes we could have an option for that

Created new issue for the request:   https://github.com/yugabyte/yugabyte-db/issues/5128

**Comment by stevebang** [comment]
@OlegLoginov I'm confused by the comments above. Is the `--serializable-deferrable` flag only being used in the `yb_backup.py` script or was it just enabled by default for `ysql_dump` and no need to add it to the Python script?
