### ISSUE TITLE
[YSQL] yb-admin create_database_snapshot should not require ysql prefix for database name

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4991]
Since we have split yb-admin snapshot commands for YCQL and YSQL into `create_keyspace_snapshot` and `create_database_snapshot`, we shouldn't need a `ysql.` prefix for `create_database_snapshot`.

Current behavior:
```
yb-admin -master_addresses 127.0.0.1:7100 create_database_snapshot test
Error: Invalid argument (yb/tools/yb-admin_cli_ent.cc:118): Wrong database type: YQL_DATABASE_CQL: 2 vs. 3
```

This should work and assume that test is of type YSQL instead of current assumption of YCQL.

**Comment by hulien22** [comment]
Closed in 4cb2cc2.
