### ISSUE TITLE
[YSQL] Restore from a distributed backup fails for tables that don't have primary key

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4993]
Consider a table created without a primary key. Restoring a backup containing such a table fails:
```
CREATE TABLE public.t2 (
    a integer,
    b text
)
SPLIT INTO 2 TABLETS;
ysqlsh:snapshot/ysql.snapshot:87: ERROR:  Cannot have SPLIT options in the absence of a primary key
```

We should enhance `SPLIT INTO` to work with tables that use YB's default `ybrowid` as PK.

**Comment by ramsrivatsa** [comment]
Here's the commit that introduced this feature -> [8e879ff](https://github.com/yugabyte/yugabyte-db/commit/8e879ff55e9ce0b660b768118bd5857335b51176)
