### ISSUE TITLE
YEDIS: Support for spop command

### ISSUE THREAD

**Issue by Jibin-Tomy-Narvar** [yugabyte/yugabyte-db#500]
Please add spop command support in YEDIS

ref: https://redis.io/commands/spop

**Comment by kmuthukk** [comment]
While working on this, we should also implement version [SRANDMEMBER](https://redis.io/commands/srandmember) (the read-only variant of SPOP).

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
