### ISSUE TITLE
Too many Network Connection - High Cpu load after update.

### ISSUE THREAD

**Issue by kutayzorlu** [yugabyte/yugabyte-db#5008]
Problem :  CPU load on Each T-SERVER, 
Reason : After Update to Last Version from Previous. 
NO - WARN message, 
NO - ERROR 
NO - FATAL continuesly. 

TCP Package content : Yugabyte consensus - Update . 

400 KiB  Bandwith each seconds between servers make cpu load. 

![conse_2](https://user-images.githubusercontent.com/1810107/86866269-e3744580-c0d0-11ea-8293-52a6c912e633.png)

**Comment by kutayzorlu** [comment]
Beaware That, 

No thing connected as Client to the System,.    **NO writes - No reads .**

**Comment by kutayzorlu** [comment]
INDEX CREATION ERROR  -   ALSO 

-----------------
=# CREATE INDEX ON f(amc);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
# exit

**Comment by kmuthukk** [comment]
@kutayzorlu --

How many cores on each node? Can you share the output of 'top'; what percentage is being consumed by yb-master, yb-tserver etc.?

**Comment by ddorian** [comment]
@kutayzorlu , can you also paste a screenshot of http://< yb-master-ip >:7000/tablet-servers ?
And the number of tables + indexes that you have ?

**Comment by kutayzorlu** [comment]
> @kutayzorlu --
> 
> How many cores on each node? Can you share the output of 'top'; what percentage is being consumed by yb-master, yb-tserver etc.?

4 cores,   . 1 core is everytime %70 minumum-.   15 Watt consumption.

**Comment by ddorian** [comment]
@kutayzorlu please answer this https://github.com/yugabyte/yugabyte-db/issues/5008#issuecomment-655317551

**Comment by ddorian** [comment]
@kutayzorlu please see [Hardware Recommendations](https://docs.yugabyte.com/latest/deploy/checklist/#hardware-requirements) in production. 

Please reopen the issue if you have further questions or to answer my question above.

**Comment by kutayzorlu** [comment]
I am too busy to write ,     Issue  continues

**Comment by kutayzorlu** [comment]
![del_me](https://user-images.githubusercontent.com/1810107/87968420-afc9f000-cac0-11ea-8f34-9676ca33cba2.png)

**Comment by kutayzorlu** [comment]
Test Server installed 2 weeks ago,  Has the same problem.

**Comment by ddorian** [comment]
hi @kutayzorlu 
Looks like your problem is related to this issue https://github.com/yugabyte/yugabyte-db/issues/772, which happens because of the big number of tablets. The cpu/network utilization increases linearly with number of tablets.

Can you create a colocated database, and put the tables/indexes that won't grow large into it ? https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_database/#colocated

Another way is to use [`SPLIT INTO`](https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_table/#split-into) to set a lower number of tablets for each table/index created.

**Comment by kutayzorlu** [comment]
Collocation is  for Y**SQL**  . Should i do the same for  YCQL also ?

**Comment by ddorian** [comment]
Colocation is only available in YSQL.

In YCQL you can specify the number of tablets in `CREATE TABLE` and `CREATE INDEX` like here: https://docs.yugabyte.com/latest/api/ycql/ddl_create_table/#create-a-table-specifying-the-number-of-tablets.

**Comment by kmuthukk** [comment]
@ddorian -- that's not a very large number of tablets per server (~354).

How many cores per node @kutayzorlu ?

**Comment by kutayzorlu** [comment]
4 Cores,  single  core %50 every time.  2.9 Ghz Xeon processor.

**Comment by kutayzorlu** [comment]
Can i change  number of tablets  after creation of the Table in YCQL ,

**Comment by ddorian** [comment]
> Can i change number of tablets after creation of the Table in YCQL ,

This is not possible currently.

**Comment by schoudhury** [comment]
@kutayzorlu 4 cores per node is not a recommended config for any meaningful application. we recommend at minimum of 16 cores for production https://docs.yugabyte.com/latest/deploy/checklist/#hardware-requirements

**Comment by kutayzorlu** [comment]
Thank you all, I will try to handle these are.

**Comment by ddorian** [comment]
@kutayzorlu please comment again if the issue still persists after following the recommendations.
