### ISSUE TITLE
Client can not connect yugabyte cluster three node,  after yb-tmaster leader down

### ISSUE THREAD

**Issue by bnducgiang90** [yugabyte/yugabyte-db#5011]
Hi team,
I have a problem :
I install Yugabyte on three node, three tmaster as blow:

 ./bin/yb-admin -master_addresses $MASTERS list_all_masters
I0707 06:34:59.091367 12198 mem_tracker.cc:249] MemTracker: hard memory limit is 13.092440 GB
I0707 06:34:59.091496 12198 mem_tracker.cc:251] MemTracker: soft memory limit is 11.128573 GB
I0707 06:34:59.093149 12198 thread_pool.cc:166] Starting thread pool { name: yb-admin queue_limit: 10000 max_workers: 1024 }
I0707 06:34:59.093987 12198 client-internal.cc:1947] New master addresses: [10.0.222.43:7100,10.0.222.44:7100,10.0.222.45:7100]
Master UUID                             RPC Host/Port           State           Role
4fbb0333833941239213f4e14338a1b3        10.0.222.43:7100        ALIVE           FOLLOWER
79c143e5dc614c7591b72c7908187549        10.0.222.44:7100        ALIVE           LEADER
af8a5d643f9249af941885627d4671a0        10.0.222.45:7100        ALIVE           FOLLOWER

 but after tmaster leader down then client can not connect .
Please help me resolve problem!

Thanks

**Comment by kmuthukk** [comment]
hi @bnducgiang90 --

<< but after tmaster leader down then client can not connect . >>

Can you describe what exact operation the client is trying to do? And what is the exact error it is getting?

**Comment by bnducgiang90** [comment]
Hi @kmuthukk 
<< but after tmaster leader down then client can not connect .>>
- Client connect using IP: 10.0.222.44 is tmaster leader
- machine 10.0.222.44  power outages
- Client connect to 10.0.222.44  => raise error : Connect timeout 
- Client change connect to 10.0.222.43 or 10.0.222.45 => Connected 

 here, my problem is yugatebye not auto fairover client connect from 10.0.222.44 to node other.
Please tell me solution for this case.

Thanks!

**Comment by kmuthukk** [comment]
What client are you using?

Is this psql (YSQL) or cqlsh CLI (YCQL) or is your client like a Java program?

And What "port" are you talking to?

**Comment by bnducgiang90** [comment]
Hi @kmuthukk 
Client using DBeaver connect yugabytedb as postgresql engine and Port using 5433
 <<With YSQL typically, you'll either need to put the IPs behind a load-balancer or a route53 like entry and connect / have retry logic to connect to a new IP (round-robin / random selection) if you get a connection failure.
>>
==> as above then we must using a Load - balancer (nginx, haproxy etc...)  forward to round - robin three IP yugabyte db ?

Thanks!

**Comment by ddorian** [comment]
@bnducgiang90 another solution is to [use multiple hosts](https://paquier.xyz/postgresql-2/postgres-10-multi-host-connstr/) in your connection string.

Please reopen the issue if you have any more questions.

**Comment by bnducgiang90** [comment]
I had resolved!
Thanks so much!
