### ISSUE TITLE
cqlsh python3 compatible

### ISSUE THREAD

**Issue by rcalosso** [yugabyte/yugabyte-db#5013]
With python 2 reaching eof 1/1/2020 we need a version of cqlsh that works with python3 for alpine os.

**Comment by stevebang** [comment]
Relevant: https://issues.apache.org/jira/browse/CASSANDRA-10190

**Comment by d-uspenskiy** [comment]
fixed by pull request

https://github.com/yugabyte/cqlsh/commit/13f231268f324f919c6086841b7935193bf25400
