### ISSUE TITLE
[docdb] Setup a global leader balance threshold while allowing progress to be made across tables

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5021]
Right now we only have `load_balancer_max_concurrent_moves` to control the total number of leader moves done in a LB run. However, since the LB runs per table, it's likely that all the moves are used on the first table and progress is slow.

An easy option to increase parallelism would be to add another set of flags, so we can have both a global limit and a per table limit, much like @hectorgcr did for remote bootstraps. This could allow, for example, for us to set the per table limit to 1, but the global limit to a really high number, to ensure that in every run, the LB will move 1 leader for each table, thus being able to finish the leader move part of a cluster operation in O(num tablets / table) rather than in O(total num tablets).

cc @rahuldesirazu @hectorgcr

**Comment by bmatican** [comment]
This is the diff that @hectorgcr previously did to add some global vs per table controls in the LB: https://phabricator.dev.yugabyte.com/D8330, which is a good start point for this issue too

**Comment by hulien22** [comment]
Closed in 6382fde.
