### ISSUE TITLE
tableplus integration: redis metadata commands should gracefully error for redis compatible yedis

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#503]
1. run a local yugabyte db cluster

2. download https://tableplus.io/

3. create a new "redis" connection to host 127.0.0.1 and port 6379

4. run redis commands from the query builder, they work fine.

5. however clicking on any of the items highlighted makes tableplus unresponsive.

![image](https://user-images.githubusercontent.com/792573/46781440-756dd500-ccd6-11e8-99ba-0270e3b30ac1.png)

6. since these metadata commands are not relevant to yugabyte db, the yugabyte db yedis service should gracefully error for these commands.

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
