### ISSUE TITLE
Operation failed. Try again.: Multiple homogeneous errors

### ISSUE THREAD

**Issue by shuyouZZ** [yugabyte/yugabyte-db#5032]
This problem occurs when I import 10 million lines of data in the database using the copy command

ysqlsh:/home/dump11:10000003: ERROR:  Operation failed. Try again.: Multiple homogeneous errors: [Operation failed. Try again. (yb/tablet/running_transaction.cc:385): Transaction aborted: a72f076b-59ab-4625-bac0-5785e459f413 (pgsql error 40001)]

This error occurs every time . How can I solve it?

**Comment by ddorian** [comment]
@schoudhury did you try this https://github.com/yugabyte/yugabyte-db/issues/5011#issuecomment-656447048 ?

**Comment by ddorian** [comment]
@shuyouZZ are you still having trouble ?
If yes, can you try with latest version https://download.yugabyte.com/ ?

**Comment by shuyouZZ** [comment]
> @shuyouZZ are you still having trouble ?
> If yes, can you try with latest version https://download.yugabyte.com/ ?

Thanks, I can try the latest version.

**Comment by ddorian** [comment]
@shuyouZZ is the issue still persisting after updating to the latest version ?
