### ISSUE TITLE
[DOCS] Database should not run as root for security

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#5038]
Add to checklist:

It is a security best practice to not run databases, webservers etc as root because they can get hacked and the hacker would be root. YugabyteDB does not require root for installing and running but this is not explicitly stated in the docs.

Also explain that root should set the ulimits.

**Comment by rkarthik007** [comment]
Hi @ddorian - this seems to be covered in our security checklist: https://docs.yugabyte.com/latest/secure/security-checklist/#run-as-a-dedicated-user

Perhaps we just need to mention this in our deploy step as well (since folks deploying may miss that).
