### ISSUE TITLE
[Platform] Add a health check for host RAM usage

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5041]
Whether we raise an alert or not on this metric, we should atleast report it in the health check similar to the disk usage metric we have.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-162

**Comment by daniel-yb** [comment]
IMO this should be added as an AlertDefinition template instead of to the healthcheck script using a node exporter metric.
