### ISSUE TITLE
[docdb] master log spew

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5047]
Please reduce the frequency of this logging

W0710 21:35:24.671041 50123 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46060 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 67 }, status = Network error (yb/rpc/secure_stream.cc:509): Insecure connection header: 5942)
W0710 21:35:24.671180 50123 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46060 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 67 }, status = Service unavailable (yb/rpc/reactor.cc:91): Shutdown connection (system error 108))
W0710 21:35:24.722259 50132 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46062 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 67 }, status = Network error (yb/rpc/secure_stream.cc:509): Insecure connection header: 5942)
W0710 21:35:24.722386 50132 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46062 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 67 }, status = Service unavailable (yb/rpc/reactor.cc:91): Shutdown connection (system error 108))
W0710 21:35:24.773694 50124 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46072 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 66 }, status = Network error (yb/rpc/secure_stream.cc:509): Insecure connection header: 5942)
W0710 21:35:24.773844 50124 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46072 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 66 }, status = Service unavailable (yb/rpc/reactor.cc:91): Shutdown connection (system error 108))
W0710 21:35:24.830107 50127 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46078 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 66 }, status = Network error (yb/rpc/secure_stream.cc:509): Insecure connection header: 5942)
W0710 21:35:24.830236 50127 tcp_stream.cc:130] { local: 10.88.16.55:7100 remote: 10.88.16.55:46078 }: Shutting down with pending inbound data ({ capacity: 1061488 pos: 0 size: 66 }, status = Service unavailable (yb/rpc/reactor.cc:91): Shutdown connection (system error 108))

**Comment by rao-vasireddy** [comment]
is it log spew or why is the error being generated?

**Comment by bmatican** [comment]
hey @iSignal have we seen this before on TLS enabled clusters? not sure why in this case there seems to be some regular insecure connections to the master

could this be something regular from YW? health checks, or maybe something security/KMS related? cc @rahuldesirazu @daniel-yb

**Comment by bmatican** [comment]
We finally traced this down in #5905
