### ISSUE TITLE
TestPgTransactions#testTransactionConflicts: A transactional read can get stuck if the peer stops being the leader

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#507]
Repro:

```
yb_build.sh --java-test TestPgTransactions#testTransactionConflicts -n 100 --extra-daemon-flags "-v=2" --tp 1
```

In a failure, look for "Cannot determine" in the log. You will find an error of this form:

ts1|pid111210|:30880|http://127.227.11.194:27304 W1017 21:40:49.781198 111562 intent_aware_iterator.cc:109] Failed to request transaction 511623f7-6caf-4269-86da-547a77691a38 status: Operation failed. Try again. (yb/tablet/transaction_participant.cc:595): Cannot determine transaction status with read_ht { physical: 1539812447404688 }, and global_limit_ht { physical: 1539812447454688 }, last known: PENDING at { physical: 1539812447389905 logical: 4095 }.

This is a read that is happening as part of checking that the primary key already exists (that is a requirement in PostgreSQL).

See a more complete log snippet here. https://gist.githubusercontent.com/mbautin/5bef703399777503692ce1ba52190f76/raw

(Note: these log snippets are instrumented with extra debug information.)

Then the read request just gets stuck because it cannot determine the transaction state at the read timestamp. And that is likely happening because we are assuming we are still the leader, and using a leader-only way to determine the hybrid time leader lease expiration time.

**Comment by m-iancu** [comment]
Should have been fixed by [db3b14a](https://github.com/yugabyte/yugabyte-db/commit/db3b14a99a98fc8ac9f81bee12a8f5a6a7e5e222).
