### ISSUE TITLE
[YSQL] Spurious "ERROR:  0A000: Alter table is not yet supported" from "create or replace view"

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#5071]
Using YB-2.1.8.2-b0. Testcase:
```
\set VERBOSITY verbose
set client_min_messages = warning;
drop view if exists v;

create or replace view v as select 17 as c1;
select * from v;

create or replace view v as select 42 as c1;
select * from v;
```
The first `create or replace view` silently succeeds. But the second one causes this error:
```
0A000: Alter table is not yet supported
```
However, the `select` that immediately follows this reports `42`. This shows that the view definition _is_ in fact replaced.

**So the error message is entirely spurious.**

**Comment by ramsrivatsa** [comment]
Issue fixed with commit [3cbee16](https://github.com/yugabyte/yugabyte-db/commit/3cbee160b81fa5a2dc1376abc2658c533e90ee4b).
