### ISSUE TITLE
[Platform][Azure Integration] Add correct pricing info to AZUInitializer

### ISSUE THREAD

**Issue by mchiddy** [yugabyte/yugabyte-db#5073]
Right now, the AZUInitializer hardcodes in a single instance type and pricing details. Add in metadata and ybcloud query support.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-147

**Comment by iSignal** [comment]
Related to #5281

**Comment by mchiddy** [comment]
Use Azure RateCard API (https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/usage-rate-card-overview)

**Comment by streddy-yb** [comment]
This is being tracked as part of #5624
