### ISSUE TITLE
Server tserver-1 is not running

### ISSUE THREAD

**Issue by WhiteTrashLord** [YugaByte/yugabyte-db#508]
I tested your database for the first time. I followed the instructions for Linux to create a local cluster.
I am using Ubuntu 16.04.1 LTS.
I got this message:

Successfully created a new cluster.

But then I saw this in the logs:

Server tserver-1 is not running

Everything else looks okay.
There is also nothing listening on port 9000.

Maybe this is a bug which you can fix.

Edit: I just found out that there is already running a Redis server. Maybe you don't check for it.

**Comment by WhiteTrashLord** [comment]
It was really caused because Redis was already using the port 6379.
Maybe you should choose a different port.

I created and destroyed a local cluster many times. One time I also had this error message:

yb-ctl setup_redis
2018-10-19 22:45:42,344 INFO: Waiting until we have 3 Tablet Servers
2018-10-19 22:45:43,727 INFO: Waiting until we have 3 Tablet Servers

Traceback (most recent call last):
  File "./bin/yb-ctl", line 923, in <module>
    ClusterControl().run()
  File "./bin/yb-ctl", line 486, in run
    self.args.func()
  File "./bin/yb-ctl", line 911, in setup_redis
    raise RuntimeError("Failed to Setup Redis.")
RuntimeError: Failed to Setup Redis.

During my tests I also saw several Redis database exceptions. So it seems that sometimes a local cluster was not properly created.

**Comment by kmuthukk** [comment]
Hi,

Before the `yb-ctl setup_redis` step, if you do a `yb-ctl status` step, what does that report?

The stderr/stdout logs for tserver & master are in the first disk of each node are typically in:

/tmp/yugabyte-local-cluster/node-?/disk-1/

and the glogs are in:

/tmp/yugabyte-local-cluster/node-?/disk-1/yb-data/master/logs/
/tmp/yugabyte-local-cluster/node-?/disk-1/yb-data/master/logs/


I would also suggest using a non-default DATA_DIR (/tmp/yugabyte-local-cluster is the default). But instead use something like $HOME/yb-data.

For example, to clean slate/wipe do the following. 


```
export DATA_DIR=$HOME/yb-data
pkill yb-tserver
pkill yb-master
rm -rf $DATA_DIR/ 
```

To start and setup redis table:
```
./bin/yb-ctl --data_dir $DATA_DIR --replication_factor 3 create

./bin/yb-ctl --data_dir $DATA_DIR --replication_factor 3 status

./bin/yb-ctl --data_dir $DATA_DIR --replication_factor 3 setup_redis
```

The logs if something unexpected happens should be in:
```
ls -lrt $DATA_DIR/node-?/disk-1/yb-data/master/logs/
ls -lrt $DATA_DIR/node-?/disk-1/yb-data/tserver/logs/
```
The stderr/stdout for the yb-master & yb-tserver process will be in:
```
ls -lrt $DATA_DIR/node-?/disk-1/master.{out,err}
ls -lrt $DATA_DIR/node-?/disk-1/tserver.{out,err}
```

**Comment by kmuthukk** [comment]
hi @WhiteTrashLord  - closing the issue for now. But please free to re-open if the above suggestions were not helpful in root causing the issue, and you are still running into issues.

**Comment by zinid** [comment]
Same issue here. I had both postgresql and redis running, and from the log it was impossible to understand what's going on (not to mention that the logs are barely readable and there are like tens of log files, very confusing).

**Comment by zinid** [comment]
Namely:
- master.err
- master.out
- tserver.err
- tserver.out

Then goes subdirectories with:
```
$ ls -l /tmp/yb/node-1/disk-1/yb-data/master/logs
total 268
lrwxrwxrwx 1 xram xram     49 Oct 21 21:07 yb-master.INFO -> yb-master.xram.xram.log.INFO.20191021-180714.6599
lrwxrwxrwx 1 xram xram     52 Oct 21 21:07 yb-master.WARNING -> yb-master.xram.xram.log.WARNING.20191021-180714.6599
-rw-r--r-- 1 xram xram 134407 Oct 21 21:04 yb-master.xram.xram.log.INFO.20191021-180407.6368
-rw-r--r-- 1 xram xram 122574 Oct 21 21:07 yb-master.xram.xram.log.INFO.20191021-180714.6599
-rw-r--r-- 1 xram xram    977 Oct 21 21:04 yb-master.xram.xram.log.WARNING.20191021-180407.6368
-rw-r--r-- 1 xram xram   1983 Oct 21 21:07 yb-master.xram.xram.log.WARNING.20191021-180714.6599
$ ls -l /tmp/yb/node-1/disk-1/yb-data/tserver/logs 
total 84
-rw------- 1 xram xram   521 Oct 21 21:04 postgresql-2019-10-21_180408.log
-rw------- 1 xram xram  1156 Oct 21 21:07 postgresql-2019-10-21_180714.log
lrwxrwxrwx 1 xram xram    51 Oct 21 21:04 yb-tserver.ERROR -> yb-tserver.xram.xram.log.ERROR.20191021-180408.6371
lrwxrwxrwx 1 xram xram    50 Oct 21 21:07 yb-tserver.INFO -> yb-tserver.xram.xram.log.INFO.20191021-180714.6603
lrwxrwxrwx 1 xram xram    53 Oct 21 21:07 yb-tserver.WARNING -> yb-tserver.xram.xram.log.WARNING.20191021-180714.6603
-rw-r--r-- 1 xram xram   568 Oct 21 21:04 yb-tserver.xram.xram.log.ERROR.20191021-180408.6371
-rw-r--r-- 1 xram xram 41088 Oct 21 21:04 yb-tserver.xram.xram.log.INFO.20191021-180407.6371
-rw-r--r-- 1 xram xram 10748 Oct 21 21:07 yb-tserver.xram.xram.log.INFO.20191021-180714.6603
-rw-r--r-- 1 xram xram  5531 Oct 21 21:04 yb-tserver.xram.xram.log.WARNING.20191021-180407.6371
-rw-r--r-- 1 xram xram  2745 Oct 21 21:07 yb-tserver.xram.xram.log.WARNING.20191021-180714.6603
```
What a mess...

**Comment by ndeodhar** [comment]
Thanks for your feedback on the log file structure @zinid . We'll look into simplifying it.

Meanwhile, to help you with your issue, can you please provide these details?
1. Output of `ps -ef | grep yb-tserver` and `ps -ef | grep yb-master`.
2. Did you use `yb-ctl` to create the local cluster?
3. Warning and error messages from `/tmp/yb/node-1/disk-1/yb-data/tserver/logs/yb-tserver.INFO`

**Comment by zinid** [comment]
@ndeodhar thank you for the quick response. Well I sorted out the issue already: just stopped Redis as suggested in this discussion (and yes, I used `yb-ctl create` to create a single machine cluster). Sorry, I cannot provide logs because I already did some benchmarking and they are several megabytes now:
```
$ du -hs /tmp/yb/node-1/disk-1/yb-data/*/logs
1.6M	/tmp/yb/node-1/disk-1/yb-data/master/logs
16M	/tmp/yb/node-1/disk-1/yb-data/tserver/logs
```
Especially this one:
```
$ du -hs /tmp/yb/node-1/disk-1/yb-data/tserver/logs/*
...
15M	/tmp/yb/node-1/disk-1/yb-data/tserver/logs/yb-tserver.xram.xram.log.INFO.20191021-180714.6603
...
```
I looked into it and it is anything but INFO: more likely some debug information only YB developers can understand. You see, I stress this because logs must be readable by admins, not only YB devs. You read my rant here because of badly written logs in the first place :)

Also, `yb-tserver.ERROR` is empty, `yb-master.WARNING` has no relevant info why the master didn't start and `yb-master.INFO` has, again, a bunch of debug info. Anyway, here is the contents of `yb-master.WARNING`:
```
Log file created at: 2019/10/21 18:07:14
Running on machine: xram
Application fingerprint: version 2.0.1.0 build 19 revision 6607435dcbd4e8a90b48c2efc37f7ec50fce995a build_type RELEASE built at 04 Oct 2019 22:26:27 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1021 18:07:14.574084  6669 log_util.cc:211] Could not read footer for segment: /tmp/yb/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001: Not found (yb/consensus/log_util.cc:446): Footer not found. Footer magic doesn't match
W1021 18:07:14.574214  6678 master_service.cc:102] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:5791): Node 1bb20d4f737c484c889201b7a84f4df7 peer not initialized.
W1021 18:07:14.574278  6669 log_reader.cc:153] T 00000000000000000000000000000000 P 1bb20d4f737c484c889201b7a84f4df7: Log segment /tmp/yb/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W1021 18:07:14.575490  6678 master_service.cc:102] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:5791): Node 1bb20d4f737c484c889201b7a84f4df7 peer not initialized.
W1021 18:07:14.585659  6669 log_util.cc:211] Could not read footer for segment: /tmp/yb/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001: Not found (yb/consensus/log_util.cc:446): Footer not found. Footer magic doesn't match
W1021 18:07:14.585685  6669 log_reader.cc:153] T 00000000000000000000000000000000 P 1bb20d4f737c484c889201b7a84f4df7: Log segment /tmp/yb/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
```
Maybe you see something about the port being acquired by Redis, but I don't :)

**Comment by zinid** [comment]
Oh, finally, found in `/tmp/yb/node-1/disk-1/yb-data/tserver/logs/yb-tserver.xram.xram.log.ERROR.20191021-180408.6371`:
```
E1021 18:04:08.233811  6371 main_util.cc:22] Network error (yb/util/net/socket.cc:334): Error binding socket to 127.0.0.1:6379: Address already in use (system error 98)
```
Whatever.
