### ISSUE TITLE
Kubernetes cname only tries the first ip address on GKE

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#51]
I created a new Kubernetes cluster on Google compute. Here are the pods:
```
$ kubectl get pods
NAME           READY     STATUS    RESTARTS   AGE
yb-master-0    1/1       Running   0          26m
yb-master-1    1/1       Running   0          26m
yb-master-2    1/1       Running   0          26m
yb-tserver-0   1/1       Running   0          26m
yb-tserver-1   1/1       Running   0          26m
yb-tserver-2   1/1       Running   0          26m
```

The master leader is `yb-master-1`. It only shows on live tserver. I found the following logs on the other tservers:

```
[root@yb-tserver-0 yugabyte]# tail -f /mnt/data0/yb-data/tserver/logs/yb-tserver.INFO
I0213 23:19:10.830147    25 heartbeater.cc:319] Connected to a leader master server at yb-masters.default.svc.cluster.local:7100
W0213 23:19:10.870188    25 heartbeater.cc:98] Master address 'yb-masters.default.svc.cluster.local:7100' resolves to 3 different addresses. Using 10.4.2.5:7100
I0213 23:19:10.870285    25 heartbeater.cc:370] Registering TS with master...
I0213 23:19:10.870371    25 heartbeater.cc:376] Sending a full tablet report to master...
W0213 23:19:10.870934    25 heartbeater.cc:561] Failed to heartbeat to yb-masters.default.svc.cluster.local:7100: Service unavailable (yb/tserver/heartbeater.cc:473): master is no longer the leader tries=1283, num=1, masters=yb-masters.default.svc.cluster.local:7100, code=Service unavailable
I0213 23:19:11.873162    25 heartbeater.cc:319] Connected to a leader master server at yb-masters.default.svc.cluster.local:7100
W0213 23:19:11.874910    25 heartbeater.cc:98] Master address 'yb-masters.default.svc.cluster.local:7100' resolves to 3 different addresses. Using 10.4.2.5:7100
I0213 23:19:11.874974    25 heartbeater.cc:370] Registering TS with master...
I0213 23:19:11.875042    25 heartbeater.cc:376] Sending a full tablet report to master...
W0213 23:19:11.875373    25 heartbeater.cc:561] Failed to heartbeat to yb-masters.default.svc.cluster.local:7100: Service unavailable (yb/tserver/heartbeater.cc:473): master
```

We only seem to be trying the first ip address `10.4.2.5`.

I get the following as the ips when I resolve the cnames:
```
[root@yb-tserver-0 yugabyte]# nslookup yb-masters.default.svc.cluster.local
Server:		10.7.240.10
Address:	10.7.240.10#53

Non-authoritative answer:
Name:	yb-masters.default.svc.cluster.local
Address: 10.4.2.5
Name:	yb-masters.default.svc.cluster.local
Address: 10.4.1.7
Name:	yb-masters.default.svc.cluster.local
Address: 10.4.0.7
```

**Comment by ttyusupov** [comment]
tserver should resolve `yb-masters.default.svc.cluster.local` to multiple IPs at previous steps and heartbeater should use already resolved addresses, but from what I see in logs - unresolved hostname was passed to heartbeater due to some reasons. I wasn't able to reproduce that locally with minikube.

@rkarthik007 , could you, please provide config file and step-by-step instruction describing how are you creating Kubernetes cluster on GCP?

**Comment by rkarthik007** [comment]
Sure here you go @ttyusupov:

1. Get an ubuntu 16.04 LTS GCP machine in us-west-1b zone

2. Download the Google Cloud SDK from https://cloud.google.com/sdk/downloads#versioned and install it using the instructions there.

3. Configure gcloud with:
```
gcloud components install kubectl
gcloud config set project yugabyte
gcloud config set compute/zone us-west-1b
```

4. Create a kubernetes cluster:
```
gcloud container clusters create yugabyte
```

5. Create a YB cluster with the latest yaml in github, this is now in yugabyte-db/cloud/kubernetes directory in the code:
```
kubectl create -f https://raw.githubusercontent.com/YugaByte/yugabyte-db/master/cloud/kubernetes/yugabyte-statefulset.yaml
```

Next I followed these instructions: https://docs.yugabyte.com/quick-start/create-local-cluster/#kubernetes
```
kubectl exec -it yb-master-0 /home/yugabyte/bin/yb-admin -- --master_addresses yb-master-0.yb-masters.default.svc.cluster.local:7100,yb-master-1.yb-masters.default.svc.cluster.local:7100,yb-master-2.yb-masters.default.svc.cluster.local:7100 setup_redis_table
```

At this point the redis table creation failed because it has only one live tserver but is configured for rf=3.

**Comment by ttyusupov** [comment]
The root cause is that `--tserver_master_replication_factor=3` was missed from tserver options in Kubernetes cluster config. This option tells master address resolution function to resolve master addresses on startup and use all IPs resolved instead of simply passing hostname further (default behaviour).
