### ISSUE TITLE
[YSQL] Prevent requests to YSQL DB while the DB is being restored from backup.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#5105]
When YSQL DB is being restored via `yb_backup.py .. restore` - any read/write operations can fail or can return incorrect result. To prevent this - any requests to the DB must be prohibited.

**Comment by ndeodhar** [comment]
@OlegLoginov Closing this as duplicate of https://github.com/yugabyte/yugabyte-db/issues/4885.
