### ISSUE TITLE
tablet server dead after numerous DDL statements

### ISSUE THREAD

**Issue by nikk0** [yugabyte/yugabyte-db#5119]
Hello.
For testing/validation purpose,I am trying to migrate an Oracle schema to a 3-node yugabyteDB cluster.
yugabyteDB version is 2.2.0.0
Each node has 4GB RAM and 4 cores.

I execute a script with DBeaver containing  numerous DDL commands.
After a while, the script execution freezes and  the following errors appears in the ybtserver log file on 1 node: 

`W0716 09:45:21.853219 23171 raft_consensus.cc:1788] T a6b4de580042488da59a9c415bfbeb18 P e430684f524e425eab646a625b9d026R]: StartReplicaOperationUnlocked failed: Service unavailable (yb/tablet/operations/operation_tracker.cc:162): Operation6b4de580042488da59a9c415bfbeb18 operation memory consumption (0) has exceeded its limit (1073741824) or the limit of an
W0716 09:45:21.853296 23171 raft_consensus.cc:1805] T a6b4de580042488da59a9c415bfbeb18 P e430684f524e425eab646a625b9d026R]: Could not prepare operation for op: 2.98. Suppressed 0 other warnings. Status for this op: Service unavailable (yb/toperation_tracker.cc:162): Operation failed, tablet a6b4de580042488da59a9c415bfbeb18 operation memory consumption (0) hamit (1073741824) or the limit of an ancestral tracker
`
and the gui shows one tserver dead :
 
![image](https://user-images.githubusercontent.com/8555147/87659288-a4dc2c00-c75d-11ea-81cd-f7f66c4b93a3.png)

How can I cope with this issue ?

Note : the tserver was executed with the following command:
`  ./bin/yb-tserver 
  --tserver_master_addrs  yuga1:7100,yuga2:7100,yuga3:7100 
  --rpc_bind_addresses $HOSTNAME:9100 
  --start_pgsql_proxy 
  --pgsql_proxy_bind_address $HOSTNAME:5433 
  --cql_proxy_bind_address $HOSTNAME:9042 
  --fs_data_dirs "/home/yuga/disk1,/home/yuga/disk2" 
  --placement_cloud iv 
  --placement_region europe 
  --placement_zone massy 
`

Regards
N.

**Comment by ddorian** [comment]
Hi @nikk0 

Looks like you ran out of memory. Can you try with bigger nodes like on our Hardware Recommendations: https://docs.yugabyte.com/latest/deploy/checklist/ ?

**Comment by nikk0** [comment]
hello
no pb to increase memory but what is the best amount for my testcase ? Do u have some sizing advisor ?
I simply executed ddl statements and  I think that 4GB/node will suit my needs. 
Your answer makes me scary because if i need more than 4GB for only DDL, what huge amount of memory will i need when I will start using DML ?.....
Lastly, I think that tserver should not crash and parks additionnal incoming statements inot a kind of waiting room until memory getting freed.
However, i will try to allocate more RAM.  
regards.
N.

**Comment by ddorian** [comment]
Ok I see another big problem.
Looks like you have a lot of tables/index. How many are there ?

These create a big number of tablets `4000+` in your cluster which will eat your cpu,network,ram.

Can you try with putting small tables + indexes in a colocated database https://docs.yugabyte.com/latest/explore/colocated-tables/linux/ ? This will reduce a lot the overhead.

And report back with another screenshot.

**Comment by ddorian** [comment]
@nikk0 
The issue is also explained in depth here https://blog.yugabyte.com/boosting-performance-for-small-distributed-sql-data-sets-with-colocated-tables/

**Comment by nikk0** [comment]
Hello ddorian
creating a colocated db solved the issue:
![image](https://user-images.githubusercontent.com/8555147/87670476-1329ea00-c770-11ea-914a-2286b917d051.png)

Thanks for your help.

**Comment by ddorian** [comment]
For tables that you expect to get big, you can create them outside of colocation so they can be distributed.

**Comment by ddorian** [comment]
Please reopen if the issue persists.

**Comment by ddorian** [comment]
Please reopen if the issue persists.
