### ISSUE TITLE
[Platform] Removing a node with master role on it in YW brings the cluster down to 2 masters

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5121]
At the moment, in the on-prem node operations in YW, a node with a master process on it can be released. As we remove the node from YW cluster config, the universe will only have 2 masters at  this point. We need to make sure a 3rd master is available in the region/AZ of the node being released.

Edit(sanketh): believe the same happens in cloud universes too.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-130

**Comment by iSignal** [comment]
From #5127 

Agree the user experience is not good at the very least.

Options:

(a) At the very least, warn users that this will be the result and that they should follow up this operation with an "Add Node" soon to maintain the intended master count.
(b) Place a new master if possible - however, this requires a placement calculation and an appropriate node may not be available. If no replacement node is available, we could fail the "remove node".

**Comment by tedyu** [comment]
```
we could fail the "remove node".
```
Is it possible that the new node for the 4th master (3rd after removal is done) is available prior to releasing existing master but unavailable after the existing master is released ?

**Comment by chirag-yb** [comment]
In v2.2.4 there is a new feature to manually promote a TServer only node to run Master and TServer process which solves the issue of under replicated master nodes.
