### ISSUE TITLE
[YSQL] Enable serializable-deferrable mode by default in the ysql_dump tool.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#5128]
This will help ysql_dump work with concurrent writes on the database without any read restart errors.

**Comment by OlegLoginov** [comment]
Fixed by the commit above.

**Comment by stevebang** [comment]
@OlegLoginov The separate issue here is a duplicate of #3127 -- is this now the default for ysql_dump?
