### ISSUE TITLE
partition aware routing support in C++ CQL driver

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#513]
partition aware routing support in C++ CQL driver

**Comment by OlegLoginov** [comment]
Fixed by the commits:
https://github.com/YugaByte/cassandra-cpp-driver/commit/2f64ab8e18f224f86077b184c2a113fa59b2aafb
https://github.com/YugaByte/cassandra-cpp-driver/commit/4243fe1a49d0390b1951617f03ceef66ee5ebb18
