### ISSUE TITLE
Implement SCHECK alternative that will behave like CHECK in debug

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#5130]
Jira Link: [DB-1641](https://yugabyte.atlassian.net/browse/DB-1641)
This should have the following behavior depending on build type:
- Release: Return status if the condition is not met (like `SCHECK`)
- Debug: Crash if the condition is not met (like `CHECK`)

**Comment by bmatican** [comment]
We now have RSTATUS_DCHECK
