### ISSUE TITLE
JSON support in C# CQL driver

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#514]
JSON support in C# CQL driver

**Comment by kmuthukk** [comment]
This support is now available via:

https://github.com/YugaByte/cassandra-csharp-driver

Sample examples/tests for JSON support in YCQL via YugaByte DB's Cassandra-compatible CSharp drive r here:

https://github.com/YugaByte/cassandra-csharp-driver/blob/8473d9c9c0f50fa71003c68839fdf93b6201341d/src/Cassandra.YugaByte.Tests/JsonTest.cs#L32
