### ISSUE TITLE
[Phase 2][colocation] ysql_dump validation for colocation

### ISSUE THREAD

**Issue by vvkgopalan** [yugabyte/yugabyte-db#5140]
Jira Link: [[DB-388]](https://yugabyte.atlassian.net/browse/DB-388)
To do once tablegroups are implemented.
As part of ysql_dump, dump queries related to tablegroup creation (by performing pg_tablegroup lookups) and perform pg_class lookups for reltablegroup to properly recreate CREATE TABLE ddl that used tablegroups.

[DB-388]: https://yugabyte.atlassian.net/browse/DB-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by frozenspider** [comment]
`ysql_dump` is expected to work with tablegroups, separate issues are tracked individually (e.g. #10194).

**Comment by frozenspider** [comment]
Reopening to do a comprehensive validation of `ysql_dump` with respect to tablegroups
