### ISSUE TITLE
[YSQL] Getting `Query error: Restart read required` when creating index during data load phase 

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5142]
Ran the YCSB YSQL workload on a local test cluster using instructions here: https://docs.yugabyte.com/latest/benchmark/ycsb-ysql/.

During the load phase (table had about 650K rows, but was still getting writes), an attempt to create an index on the table results in:

```
ycsb=# select count(*) from usertable;
 count
--------
 651365
(1 row)

ycsb=# create index field1_idx on usertable(field1);

ERROR:  Query error: Restart read required at: { read: { physical: 1595080413734987 }\
local_limit: { physical: 1595080414191779 logical: 4095 } \
global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```

**Comment by jaki** [comment]
According to https://yugabyte.slack.com/archives/C3SP5KNAC/p1595081468271800, this is with index backfill enabled for YSQL.

**Comment by jaki** [comment]
Actually, that message was misinterpreted.  This does not use index backfill.

**Comment by kmuthukk** [comment]
I was using default gflags for 2.2.

**Comment by kmuthukk** [comment]
I can confirm that when I enabled the online index refill feature for YSQL, I didn't run into this read-restart error:

`yb-ctl start --master_flags "ysql_disable_index_backfill=false" --tserver_flags "ysql_disable_index_backfill=false" --listen_ip=0.0.0.0`
