### ISSUE TITLE
[YSQL] OOM when creating index on existing table

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5143]
Setup: RF1 (2.2.0 release) on ~8GB machine.

Loaded 1MB rows into a YSQL table using YCSB tool (https://docs.yugabyte.com/latest/benchmark/ycsb-ysql/).  But likely any simple table loader utility will suffices. This YCSB created table has the following schema:

```
ycsb=# \d usertable;
                      Table "public.usertable"
  Column  |          Type          | Collation | Nullable | Default
----------+------------------------+-----------+----------+---------
 ycsb_key | character varying(255) |           | not null |
 field0   | text                   |           |          |
 field1   | text                   |           |          |
 field2   | text                   |           |          |
 field3   | text                   |           |          |
 field4   | text                   |           |          |
 field5   | text                   |           |          |
 field6   | text                   |           |          |
 field7   | text                   |           |          |
 field8   | text                   |           |          |
 field9   | text                   |           |          |
Indexes:
    "usertable_pkey" PRIMARY KEY, lsm (ycsb_key HASH)
```

Once 1M rows were loaded, an attempt create an index causes OOM:

```
ycsb=# select count(*) from usertable;
  count
---------
 1000000
(1 row)

ycsb=# create index field1_idx on usertable(field1);
```

Relevant rows from OOM report:
```
[root@ip-10-9-123-137 tmp]# grep -E "(oom|yb-master|yb-tserver|postgres|rss)" /tmp/oom.txt
Jul 18 14:29:09 ip-10-9-123-137 kernel: bgtasks-28323 invoked oom-killer: gfp_mask=0x800d0, order=0, oom_score_adj=0
Jul 18 14:29:09 ip-10-9-123-137 kernel: [<ffffffff81184cfe>] oom_kill_process+0x24e/0x3c0
Jul 18 14:29:09 ip-10-9-123-137 kernel: [<ffffffff8118479d>] ? oom_unkillable_task+0xcd/0x120
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Jul 18 14:29:09 ip-10-9-123-137 kernel: [24141]   999 24141    58690     2963      50        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [24192]   999 24192    58690      363      41        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [24193]   999 24193    58690      610      44        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [24194]   999 24194    58690      358      41        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [24195]   999 24195    58796      453      46        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [24196]   999 24196    22473      369      40        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [28802]  1000 28802    64121     3073     100        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [29233]  1000 29233   262974     6431     137        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [28259]  1000 28259   230639    29218     254        0             0 yb-master
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3544]  1000  3544   578563   245361     812        0             0 yb-tserver
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3629]  1000  3629   108194     6863     130        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3665]  1000  3665    68634     2106     101        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3667]  1000  3667   126739     2158     111        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3673]  1000  3673   108194     2130     105        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3674]  1000  3674    69164     2112     102        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: [ 3786]  1000  3786   919145   627123    1363        0             0 postgres
Jul 18 14:29:09 ip-10-9-123-137 kernel: Out of memory: Kill process 3786 (postgres) score 347 or sacrifice child
Jul 18 14:29:09 ip-10-9-123-137 kernel: Killed process 3786 (postgres) total-vm:3676580kB, anon-rss:2507756kB, file-rss:608kB, shmem-rss:128kB
```

The postgres backend process (with pid 3786) had an RSS of 627123 (* 4KB) == 2.4GB, which seems quite high. Looks like there's a memory leak we need to address.

**Comment by jaki** [comment]
I'm assuming this is with YSQL index backfill enabled.  @kmuthukk, please remove this from the Index backfill project if that's not the case.

**Comment by jaki** [comment]
Confirmed with @kmuthukk that this was not with backfill enabled (`--ysql_disable_index_backfill false`).

**Comment by jaki** [comment]
I'm getting memory to keep increasing even across workloads.  I tested with `--ysql_disable_index_backfill false` (even with #5031), but I feel that's a major factor because this issue was reported without backfill enabled.

I ended off workload E with resident memory usage of `yb-tserver` above 5000M.  When moving on to workload F (automatic using `run_ysql.sh` from YCSB), I didn't see a decrease in memory usage.  It printed `DROP TABLE`, and @psudheer21 said memory usage ideally shouldn't keep increasing.  However, that has been the trend so far: memory usage climbed from 3000M to 4000M to 5000M and now 5544M in the middle of workload F.

**Comment by kmuthukk** [comment]
@jaki --

yb-tserver memory increasing in and of itself is not an issue, if say it is going to block cache of the tserver process.

For context - can you share how much RAM is on your server? Block cache itself can use 0.5 * 0.85 * RAM.

**Comment by jaki** [comment]
@kmuthukk, I have 14.5G ram, no swap enabled.

Also, YCSB just ended at 2h0m41s.  `yb-tserver` is still hogging memory even when there are no YCSB tables or databases.

```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command                                                                                                                                                                                                                                                      
19753 user       20   0 9212M 5541M 18208 S  0.6 37.3  1h42:22 /path/to/yb-tserver
```

**Comment by kmuthukk** [comment]
@jaki --

That's ok -- block cache isn't "force" released. That memory will be used by new tables if necessary in future. This isn't a memory leak.

You can check the http://tserver:9000/mem-trackers to see where the memory is going to confirm much of it is in the block cache.

**Comment by kmuthukk** [comment]
The issue I saw was with the "postgres" process growing to 2G+ which wasn't expected. But I will rerun the experiment with "online index rebuild" enabled.

**Comment by kmuthukk** [comment]
I can confirm that when I tried with YSQL online index refill turned on:

`yb-ctl start --master_flags "ysql_disable_index_backfill=false" --tserver_flags "ysql_disable_index_backfill=false" --listen_ip=0.0.0.0`

the index was built successfully, and didn't notice the increase in memory consumption of the postgres process.
