### ISSUE TITLE
Too many Network Connection - High Cpu load after update

### ISSUE THREAD

**Issue by kutayzorlu** [yugabyte/yugabyte-db#5148]
Problem : CPU load on Each T-SERVER,
Reason : After Update to Last Version from Previous.
NO - WARN message,
NO - ERROR
NO - FATAL continuesly.

TCP Package content : Yugabyte consensus - Update .

400 KiB Bandwith each seconds between servers make cpu load.

![grafik](https://user-images.githubusercontent.com/1810107/87878813-fcd99380-c9e6-11ea-9b3a-4f8bcf9dcb6d.png)

Beaware That,

No thing connected as Client to the System,. NO writes - No reads .

THREADs "TabletServer_reactor" Has High CPU LOAD

    @     0x7f667f4f211f  (unknown)
    @     0x7f667f5a59f2  __GI_epoll_wait
    @     0x7f6684346cb7  epoll_poll
    @     0x7f6684349591  ev_run
    @     0x7f6686db767b  yb::rpc::Reactor::RunThread()
    @     0x7f6685631e2e  yb::Thread::SuperviseThread()
    @     0x7f667fe68693  start_thread
    @     0x7f667f5a541c  __clone
    @ 0xffffffffffffffff  (unknown)

 @     0x7f667f4f211e  (unknown)
    @     0x7f667fe6d6d4  __pthread_cond_signal
    @     0x7f668064e877  std::condition_variable::notify_one()
    @     0x7f6686dfaab5  yb::rpc::ThreadPool::Enqueue()
    @     0x7f6686da4359  yb::rpc::OutboundCall::InvokeCallback()
    @     0x7f6686da4fc6  yb::rpc::OutboundCall::SetResponse()
    @     0x7f6686d89ef7  yb::rpc::Connection::HandleCallResponse()
    @     0x7f6686e03338  yb::rpc::YBOutboundConnectionContext::HandleCall()
    @     0x7f6686d82e27  yb::rpc::BinaryCallParser::Parse()
    @     0x7f6686e03186  yb::rpc::YBOutboundConnectionContext::ProcessCalls()
    @     0x7f6686d88440  yb::rpc::Connection::ProcessReceived()
    @     0x7f6686df3b4a  yb::rpc::TcpStream::TryProcessReceived()
    @     0x7f6686df7824  yb::rpc::TcpStream::ReadHandler()
    @     0x7f6686df8384  yb::rpc::TcpStream::Handler()
    @     0x7f6684345b39  ev_invoke_pending
    @     0x7f6684349c48  ev_run

INDEX CREATION ERROR - ALSO

=# CREATE INDEX ON f(amc);
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

This is a LOOP , You write it everytime, giving the same error, You have to write different name for the index.

**Comment by ddorian** [comment]
@kutayzorlu Please paste a screenshot of http://127.0.0.1:7000/tablet-servers.

**Comment by ddorian** [comment]
Moving to our previous issue: https://github.com/yugabyte/yugabyte-db/issues/5148
