### ISSUE TITLE
[Platform] Provide download option for "root" certificate suitable for use with SSL and YCQL

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#5159]
The current "Download" option for TLS certificates in Yugaware in the "Certifcates" menu is designed for YSQL use-cases. We need to provide a method for supporting YCQL use-cases as well.

**Comment by rkarthik007** [comment]
This needs clarification.

**Comment by ajcaldera1** [comment]
If you create a cluster with node-to-node/client-to-node TLS enabled and select "Create new certificate" inside the platform, there is no method for retrieving the root certificate generated in order to secure connections to YCQL API. The download option for the certificate creates a user-certificate/key suitable for YSQL API only. It does not work with YCQL API.

**Comment by daniel-yb** [comment]
This issue is referenced in #4957

**Comment by iSignal** [comment]
All of this work is captured in https://github.com/yugabyte/yugabyte-db/issues/4957
