### ISSUE TITLE
[ysql] yugabyte-db binary ships with 2 versions of psql

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#516]
Currently, the yugabyte-db binary ships with 2 versions of psql.

$YB_HOME/bin/psql is 10.3 version

$YB_HOME/postgres/bin/psql is 10.4 version

Instead of shipping 2 different versions of psql, maybe the better approach is to have the first one simply symlink to the 2nd one.

**Comment by m-iancu** [comment]
Fixed by @mbautin in 3c884f0.
