### ISSUE TITLE
[YSQL] LIMIT and OFFSET does not work for null values when the executor is exercised 

### ISSUE THREAD

**Issue by ngov17** [yugabyte/yugabyte-db#5171]
Jira Link: [DB-1583](https://yugabyte.atlassian.net/browse/DB-1583)
First, create and populate table `null_test` as follows:
`create table null_test (i integer);`
`insert into null_test values (1), (2), (3);`

Normally to test LIMIT or OFFSET with null values as arguments, we do:
`select * from null_test limit (null);` or `select * from null_test offset(null);`

However, this null will be discarded during the parsing stage by design. To ensure that the executor is exercised, we run:
`select * from null_test limit (case when random() < 0.5 then null::bigint end);`
OR
`select * from null_test offset (case when random() < 0.5 then null::bigint end);`

When the query that runs the executor is written in YB, the following error occurs:
```
ERROR:  Timed out: Read(tablet: 94ed1b1237904f21acbb548c8b30eede, num_ops: 1, num_attempts: 277, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 91138.799s (passed: 60.139s): Network error 
(yb/util/net/socket.cc:535): recvmsg got EOF from remote (system error 58)
```

**Comment by sushantrmishra** [comment]
**Not reproducible anymore:** 

```
localhost:5433 yugabyte@yugabyte=# select * from null_test limit (case when random() < 0.5 then null::bigint end);
 i
---
 3
 2
 1
(3 rows)

Time: 147.176 ms
localhost:5433 yugabyte@yugabyte=#
localhost:5433 yugabyte@yugabyte=#
localhost:5433 yugabyte@yugabyte=# select * from null_test offset (case when random() < 0.5 then null::bigint end);
 i
---
 3
 2
 1
(3 rows)

Time: 9.790 ms
```
