### ISSUE TITLE
[Platform] Health check time is always in the Pacific timezone

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5172]
Repro steps:

Change timezone on client browser device. Health check timestamps do not change though other timestamps like metrics / backups do.

It seems to be hardcoded here - https://github.com/yugabyte/yugabyte-db/blob/1403b2b4d3986fbc401dd14ce9cbc956eaaf2938/managed/devops/bin/cluster_health.py#L620

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-107

**Comment by jaydeepkumara** [comment]
PR:- https://github.com/yugabyte/yugabyte-db/pull/6933
