### ISSUE TITLE
[YSQL] Restore table command with no keyspace flag causes unexpected behavior

### ISSUE THREAD

**Issue by yb-andrew** [yugabyte/yugabyte-db#5176]
Restoring a single table backup in YW with the intention to rename it, keeping the same keyspace, causes the yb_backup.py command to contain a `--table` flag but no `--keyspace` flag. As a result, the old table name is created in a keyspace with the name of the new table from the `--table` flag.

Example: 
1. Table `foo` in keyspace `public` is backed up.
2. Backup is restored from UI with the user specifying a table rename to `test`
3. Command that gets run with yb_backup.py contains `--table test` but no keyspace flag.
4. **Result**: Creates table `foo` in keyspace `test`

This behavior is unexpected and should instead error out if the number of `--table` flags is not equal to number of `--keyspace` flags.

**Comment by yb-andrew** [comment]
Duplicate issue: #5199

**Comment by OlegLoginov** [comment]
Closing it as duplicate of https://github.com/yugabyte/yugabyte-db/issues/5199.
