### ISSUE TITLE
[docdb] provide a compaction option to reclaim disk space faster 

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5183]
When a table has a TTL or a large number of rows have been deleted, it will be nice to reclaim the space faster. Even if we don't want to change the default behavior, we should at least provide a gflag to set a more aggressive method to reclaim the space.

**Comment by jmeehan16** [comment]
Closing this issue due to the "file expiration based on TTL" feature. Reference: https://github.com/yugabyte/yugabyte-db/issues/10683
