### ISSUE TITLE
Support "pgx" (Go driver) instead of "pq" (not actively developed)

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#5202]
Jira Link: [DB-1313](https://yugabyte.atlassian.net/browse/DB-1313)
Our [Build a Go application](https://docs.yugabyte.com/latest/quick-start/build-apps/go/ysql-pq/) tutorial uses the [`lib/pq`](https://github.com/lib/pq) driver. According to Status in the [`pq` README](https://github.com/lib/pq#status):

"This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using [pgx](https://github.com/jackc/pgx) which is actively maintained."

**Comment by ashetkar** [comment]
YugabyteDB now supports PGX driver and even has forked it as [YugabyteDB PGX Smart driver](https://docs.yugabyte.com/preview/drivers-orms/go/yb-pgx/).
Closing the ticket.
