### ISSUE TITLE
[Platform] Add graph for metric rpc_connections_alive in YW metrics

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5223]
Does this metric include data for all APIs or only for YCQL? If it is specific to YCQL then we we should add this to YCQL advanced section. Maybe modify the existing YCQL Inbound connections graph to use this. If it is common to all APIs then do we need to break this down by API and add it to all Advanced sections?

**Comment by bmatican** [comment]
@rao-vasireddy This seems to be actually per API, so we might want to make sure YW either specifically filters down to YCQL or we have a graph that just sums up across servers and splits by API.

<img width="1782" alt="Screen Shot 2020-07-27 at 9 57 10 AM" src="https://user-images.githubusercontent.com/395011/88569716-b213d900-cfef-11ea-8b0b-02d5600921d8.png">

**Comment by nmantrav2** [comment]
[QA] verified in 2.3 and 2.1 branches. Didn't see it in 2.2 branch 2.2.2 b7 build.
