### ISSUE TITLE
inconsistent transaction failure behavior

### ISSUE THREAD

**Issue by ronenbarakleverate** [yugabyte/yugabyte-db#5228]
Im using the standalone single instance ubuntu ver 2.2.0.0

I have created a simple competing transaction.
my expectation that it will always fail in the last tran.commit, but its fails some times in connection2.Execute(@"UPDATE ...; and some times in  tran.Commit(); with diffrent exception messages:

tran2.commit: Npgsql.PostgresException: '40001: Operation failed. Try again.: 005fbe86-c3db-4fc4-aa67-6d6d46e122ac Conflicts with higher priority transaction: 85477acc-0e67-4846-8fcb-e6c9ed57b423'

tran.commit : Npgsql.PostgresException: '40001: Operation expired: Transaction expired or aborted by a conflict: 40001'

i cannot see why this is the expected behavior, it might be a bug:

> using (Npgsql.NpgsqlConnection connection = new NpgsqlConnection("User ID=postgres;Host=192.168.166.213;Port=5433;Database=test01;Pooling=true;"))
{
	connection.Open();
	using (var tran = connection.BeginTransaction(IsolationLevel.Snapshot))
	{
	  connection.Execute(@"UPDATE public.table01 SET prop2=4	WHERE prop1=2", null, tran);
	  using (Npgsql.NpgsqlConnection connection2 = new NpgsqlConnection("User ID=postgres;Host=192.168.166.213;Port=5433;Database=test01;Pooling=true;"))
	  {
		connection2.Open();
		using (var tran2 = connection2.BeginTransaction(IsolationLevel.Snapshot))
		{
		  connection2.Execute(@"UPDATE public.table01 SET prop2=3 WHERE prop1=2", null, tran2);
		  tran2.Commit();
		}
	  }
	  tran.Commit();
	}
}

when i run this code in a loop than i get fails some times at tran.Commit(); and some times in connection2.Execute

**Comment by ddorian** [comment]
Hi @ronenbarakleverate 

YugabyteDB assigns a random priority to a transaction, and when 2 transaction conflict with each other (trying to update the same row etc) the lower priority transaction is aborted, and we return a `40001` postgresql error code. These error codes are safe to be retried from the client. So you can just retry the transaction that failed.

See architecture of distributed transactions https://docs.yugabyte.com/latest/architecture/transactions/explicit-locking/

**Comment by ronenbarakleverate** [comment]
Thanks for the quick reply,
Ok i understand and the issue can be closed.

But 

The problem with this behavior is that in some cases both transaction can fail.
And in the same scenario retry can fail too since the other transaction did not finished.

In by business scenario, i always do the same transaction twice(redundancy two location) and expect one to succeeded and the other to be aborted, in the case that they both can fail i cannot continue to use the same logic and need to do some thing completely different , since they will keep conflicting etch other(retry) and successful commits ratio will degrade.

I would expect priority will be base on the time i open the transaction(or first query) and not some random number.
or even better non conflict until commit and than one must successed and the other fail.

**Comment by ddorian** [comment]
>  And in the same scenario retry can fail too since the other transaction did not finished.

Only 1 transaction is aborted, why would both fail. By another third transaction ?

> In by business scenario, i always do the same transaction twice(redundancy two location) and expect one to succeeded and the other to be aborted,

Assuming you have 2 independent threads.
Each of them, should try a transaction, and retry if it gets error code `40001`. 
I don't see what's the problem ?

**Comment by ronenbarakleverate** [comment]
the failed transaction will retry and will try to do same thing all over again, but this time it might cancel the transaction that survived the first iteration, i will supply with a sample soon

**Comment by ddorian** [comment]
> the failed transaction will retry and will try to do same thing all over again, but this time it might cancel the transaction that survived the first iteration, i will supply with a sample soon

Ah you mean tx1 is canceled by tx2. but then tx2 is canceled by 2nd run of tx1 ?

**Comment by ronenbarakleverate** [comment]
> > the failed transaction will retry and will try to do same thing all over again, but this time it might cancel the transaction that survived the first iteration, i will supply with a sample soon
> 
> Ah you mean tx1 is canceled by tx2. but then tx2 is canceled by 2nd run of tx1 ?

yes

**Comment by ddorian** [comment]
Are these very long running transactions ?
You usually want to use a retry mechanism with exponential delay.

**Comment by ronenbarakleverate** [comment]
> Are these very long running transactions ?
> You usually want to use a retry mechanism with exponential delay.

I now understand the logic behind this, it will guarantee that a long running transaction will not stuck the application completely, and conflict at commit is not the design you have chosen.

This make sense, and exponential delay will solve the issue.

Thank.

**Comment by ddorian** [comment]
@ronenbarakleverate a good mechanism is "Random wait with exponentially widening window." explained here https://tenacity.readthedocs.io/en/latest/api.html#tenacity.wait.wait_random_exponential
