### ISSUE TITLE
[docdb][test] Several Rocks/TabletPeerTest tests are flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5231]
https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&class=Rocks%2FTabletPeerTest&name=TestDMSAnchorPreventsLogGC%2F0
https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&class=Rocks%2FTabletPeerTest&name=TestActiveOperationPreventsLogGC%2F0
https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&class=Rocks%2FTabletPeerTest&name=TestLogAnchorsAndGC%2F0

The recent flakiness seems to trace back to https://github.com/yugabyte/yugabyte-db/compare/c9b4a3ce64d437b248baa6a262af07bdce22bc2e~...c9b4a3ce64d437b248baa6a262af07bdce22bc2e

**Comment by robertsami** [comment]
is this a dupe of https://github.com/yugabyte/yugabyte-db/issues/2249?
