### ISSUE TITLE
[docdb][ysql] Provide follower reads through YSQL

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5232]
One option we were discussion, that might be cheap to do, would be to retrofit some isolation level, such as READ_COMMITTED to signal this.

**Comment by fastest963** [comment]
I also think it might be good to explore the use of connection string params like how azure does it: https://docs.microsoft.com/en-us/azure/azure-sql/database/read-scale-out

**Comment by RaidAndFade** [comment]
Just writing to note that this is something I am deeply interested in, hopefully it comes soon.

**Comment by m-iancu** [comment]
Fixed by 5ee5764.
