### ISSUE TITLE
[Platform] Master Metrics Section in Yugaware

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5233]
The proposal is to add a "Master" section in metrics below the "Tablet Server" section. We have been missing these during debugging cluster issues.
In this section, each chart could have separate lines for each yb-master (for RF=3 for example, there'll be just 3 lines in each chart). Keeping the lines separate makes it easy to tell which one was the master leader historically, and how frequently master switched, etc.

A) Proposed charts in this new section:

- Chart 1 Title: Overall RPC rate / sec
```
rate(rpc_inbound_calls_created{export_type="master_export",node_prefix="yb-demo-DNS-Test-3"}[1m])
```
- Chart 2 Title: GetTabletLocations / sec
```
rate(rpc_latency_count{export_type="master_export",service_type="MasterService",node_prefix="yb-demo-DNS-Test-3",service_method="GetTabletLocations"}[1m])
```
- Chart 3: Title: Master TSService Reads / sec
```
rate(rpc_latency_count{export_type="master_export",service_type="TabletServerService",node_prefix="yb-demo-DNS-Test-3",service_method="Read"}[1m])
```

- Chart 4: Title: Master TSService Writes / sec
```
rate(rpc_latency_count{export_type="master_export",service_type="TabletServerService",node_prefix="yb-demo-DNS-Test-3",service_method="Write"}[1m])
```

- Chart 5: Title: TSHeartbeat / sec
```
rate(rpc_latency_count{export_type="master_export",node_prefix="yb-demo-DNS-Test-3",service_type="MasterService",service_method="TSHeartbeat"}[1m])
```

- Chart 6: Title: UpdateConsensus / sec
```
rate(rpc_latency_count{export_type="master_export",node_prefix="yb-demo-DNS-Test-3",service_type="ConsensusService",service_method="UpdateConsensus"}[1m])
```
- Chart 7: Title: Create/Delete Table (note: this is not a rate chart; this chart could be two lines (one for CREATE one for delete), and it just a "SUM" across all 3 yb-masters). 
```
rpc_latency_count{export_type="master_export",node_prefix="yb-demo-DNS-Test-3",service_type="MasterService",service_method="CreateTable"}
rpc_latency_count{export_type="master_export",node_prefix="yb-demo-DNS-Test-3",service_type="MasterService",service_method="DeleteTable"}
```
- Chart 8 Title: CPU Util Secs per Sec (For yb-master, let's plot one line per master)
```
rate(cpu_utime{export_type="master_export",node_prefix="yb-demo-DNS-Test-3"}[1m])/1000
rate(cpu_stime{export_type="master_export",node_prefix="yb-demo-DNS-Test-3"}[1m])/1000
```
Note: cpu_utime and cpu_stime are measures of the "total user and system" CPU time of the process in millisecs (hence the /1000) that we are already exposing for both the processes.

While this number is not normalized for the number of cores on the machine (that part will need I think a simple division by number of cores) -- but for our purposes should be pretty good in terms of tracking trends.

B) Proposed additional chart in "Tablet Servers" section:

- Title: CPU Util Secs per Sec [For yb-tservers, we can do avg (so that we aggregate across all yb-tservers) by default instead of plotting a line per yb-tserver]. 
```
avg(rate(cpu_utime{export_type="tserver_export",node_prefix="yb-demo-DNS-Test-3"}[1m])/1000)
avg(rate(cpu_stime{export_type="tserver_export",node_prefix="yb-demo-DNS-Test-3"}[1m])/1000)
```

This is similar to section A chart 8, but for yb-tserver processes.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-74

**Comment by nmantrav2** [comment]
[QA] verified in 2.3 and 2.1 branches. Didn't find Master metrics section in 2.2 branch build b7.
