### ISSUE TITLE
Numeric Data Type Incorrect Description

### ISSUE THREAD

**Issue by ccavolt** [yugabyte/yugabyte-db#5258]
In the YSQL docs, Dec, Decimal and Numeric data types all have an incorrect description (the range of values they can describe).  Per @kmuthukk, DECIMAL/NUMERIC semantics match that of Postgres, which have a range of values "up to 131072 digits before the decimal point; up to 16383 digits after the decimal point", which is very significantly more than than the 20-digit range of a 64-bit number (what it's currently listed as).

Additionally, in the YCQL docs, the Decimal data type has a description of "exact fixed-point number" with a decimal precision of 99.  I believe this should be (not 100% sure) "arbitrary-precision number" with no upper-bound on decimal precision, based on the sentence "The Decimal class can represent decimal numbers (including fractions) of arbitrary length." in [this file](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/util/decimal.h).

Links to various documents:
[YSQL Numeric Docs](https://docs.yugabyte.com/latest/api/ysql/datatypes/type_numeric/)
[YCQL Numeric Docs](https://docs.yugabyte.com/latest/api/ycql/type_number/)
[Postgres 11 Numeric Docs](https://www.postgresql.org/docs/11/datatype-numeric.html)

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-57

**Comment by ccavolt** [comment]
Also, I was told this issue should have the 'area/docs' label on it, which I don't think I'm able to add myself.

**Comment by ndeodhar** [comment]
Thanks for reporting this issue, @ccavolt
