### ISSUE TITLE
Maximum columns per table? 

### ISSUE THREAD

**Issue by elgalu** [yugabyte/yugabyte-db#5280]
Hi, is it 1600 the supported maximum columns per table?

https://github.com/yugabyte/yugabyte-db/blob/60775ba6be6418ba62b12fff631aabff8823d743/src/postgres/src/bin/psql/crosstabview.h#L22

**Comment by ddorian** [comment]
@elgalu yes that is correct. Do you have a usecase where you need more than 1600 ?

**Comment by elgalu** [comment]
thanks! just doing some research comparing state-of-the-art DBs

**Comment by rkarthik007** [comment]
@elgalu - there is no limitation on the number of columns in YugabyteDB itself.

The snippet you posted above is the limit of how many columns max to display on the PostgreSQL command line shell tool `psql`.

cc @ddorian : ^^
