### ISSUE TITLE
[Platform] Adding Azure integration for Platform

### ISSUE THREAD

**Issue by mchiddy** [yugabyte/yugabyte-db#5281]
Fully supporting Microsoft Azure as a first class cloud provider in Yugabyte Platform.

| Status | Feature        | GitHub Issue |
| :--: | --------------- | ------------------  |
| ✅ | Use Existing Network Resources |  #5389 |
|  ✅ | Create Default Network Resources | #5388 |
| ✅ | ITest for Azure | #5333 |
|  ✅ | Add Pricing Info for Azure | #5073, #5624  |
| ✅  | Yugaware UI for Azure | #5378  |

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-51

**Comment by ajcaldera1** [comment]
All items complete. Closing this issue.
