### ISSUE TITLE
yb-sample-apps CassandraSecondaryIndex sending requests to random nodes

### ISSUE THREAD

**Issue by hectorgcr** [yugabyte/yugabyte-db#5282]
We expect our YCQL driver to be partition aware so requests are sent to the correct node (leader of the tablet). Currently we see that requests are sent randomly to any node. For example, for a 3-node cluster, only 1/3 of the requests are served locally, and the rest are forwarded.

*Note: This seems to be an issue for lookups by indexed column, and not for lookups by PRIMARY KEY.*

**Comment by kmuthukk** [comment]
Per @m-iancu , we have a unit test for this case:

This is the index locality test btw: https://github.com/yugabyte/yugabyte-db/blob/master/java/yb-cql/src/test/java/com/yugabyte/driver/core/policies/TestLoadBalancingPolicy.java#L383

maybe it is using a different version of the driver than the yb-sample-apps?

cc: @nmalladi

**Comment by nchandrappa** [comment]
@hectorgcr We have released newer versions of 3.x java driver, `3.8.0-yb-5` is currently used for our iTests. Looks like yb-sample-apps is on older version of the driver `3.2.0-yb-19`. Although I haven't updated any iTests in `TestLoadBalancingPolicy`, those tests were present even before the release of new versions of the driver. cc @m-iancu

**Comment by rao-vasireddy** [comment]
This issue is not reproducible with https://github.com/yugabyte/yb-sample-apps/releases/download/1.2.1/yb-sample-apps.jar . 
1.2.0 sample apps seems to not have the needed changes.

**Comment by kmuthukk** [comment]
Thx @hectorgcr & @m-iancu for looking into this.

@m-iancu pointed out that the 1.2.0 version of sample app was using the 3.2.0-yb-12 version of the YCQL java driver which did not have this optimization/commit:  https://github.com/yugabyte/cassandra-java-driver/commit/8dc8aa5f062f4808fe10b166e209ee45ae86f887

The 1.2.1 version of the sample application uses 3.2.0-yb-19 version of the YCQL java driver which has the optimization to do partition aware routing for index queries
