### ISSUE TITLE
[docs] Document how to set up SSO with OIDC

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5285]
Document how to set up [SSO with OIDC](https://github.com/yugabyte/yugabyte-db/issues/4633) 

- How to configure OpenID Connect
- Supported grant types
- How to test external identity
- Does SSO affect existing users which were created before the platform was federated? 
- Any known limitations

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-49

**Comment by ddhodge** [comment]
There is a docs page https://docs.yugabyte.com/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication/ closing this issue as completed
