### ISSUE TITLE
[YSQL][Colocation] DROP tablegroup / colocated database produces "Catalog Version Mismatch"

### ISSUE THREAD

**Issue by vvkgopalan** [yugabyte/yugabyte-db#5290]
I receive this "Catalog Version Mismatch" error in the following flow. This error **only** happens if there were indexes in the tablegroup. Creating many tables in the tablegroup, verifying that they are actually placed on the proper tablet, performing DMLs on them, dropping them all, and dropping the tablegroup works fine. If any of the tables had an index (I've verified that indexes placed on the parent tablet as well) the DROP TABLEGROUP breaks.

```
yugabyte=# CREATE TABLEGROUP t;
CREATE TABLEGROUP
yugabyte=# CREATE TABLE x(i text) TABLEGROUP t;
CREATE TABLE
yugabyte=# CREATE INDEX ON x(i);
CREATE INDEX
yugabyte=# DROP TABLE x;
DROP TABLE
yugabyte=# DROP TABLEGROUP t;
ERROR: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.
yugabyte=# DROP TABLEGROUP t;
DROP TABLEGROUP
yugabyte=#
```

When looking at the logs, WaitForDeleteTableToFinish is repeatedly calling IsDeleteTableDone  which appears to report that the parent table is in DELETING state until producing the above error. The parent tablet is successfully deleted. Retrying DELETE TABLEGROUP successfully deletes the table.

If I take a look at the stack trace:
```
0x109b393bc  YBPrepareCacheRefreshIfNeeded.cold.1
    @        0x1099553b7  YBPrepareCacheRefreshIfNeeded
    @        0x109954895  PostgresMain
    @        0x1098ddff8  BackendRun
    @        0x1098dd728  BackendStartup
    @        0x1098dcd42  ServerLoop
    @        0x1098da9ad  PostmasterMain
    @        0x1098465de  PostgresServerProcessMain
    @        0x109846912  main
    @     0x7fff6a8eecc9  start
    @               0x17  (unknown)
```
After taking a look at the actual version mismatch, there is a consistent off-by-one error where yb_catalog_cache_version is greater than catalog_master_version.

I have tried manually waiting in between dropping the table and dropping the tablegroup to make sure that there are no async tasks waiting for completion on the child table. Have validated that the table/index are actually deleted before dropping the tablegroup. Have also tried dropping the index first before the table.

There are instances of this error happening when deleting a colocated database. cc @ndeodhar

**Comment by frozenspider** [comment]
Should already be fixed
