### ISSUE TITLE
[docdb] master fatal - Check failed: state_->pending_remove_replica_tasks_[tablet->table()->id()].count(tablet->tablet_id()) == 0 (1 vs. 0)

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5292]
[yugabyte@ip-10-100-149-129 logs]$ cat yb-master.FATAL.details.2020-08-01T03_47_26.pid13350.txt
F20200801 03:47:26 ../../src/yb/master/cluster_balance.cc:1136] Check failed: state_->pending_remove_replica_tasks_[tablet->table()->id()].count(tablet->tablet_id()) == 0 (1 vs. 0)
    @     0x7fa0dccd577c  yb::LogFatalHandlerSink::send()
    @     0x7fa0dbebc346  google::LogMessage::SendToLog()
    @     0x7fa0dbeb97aa  google::LogMessage::Flush()
    @     0x7fa0dbebc879  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa0e71ee124  yb::master::ClusterLoadBalancer::SendReplicaChanges()
    @     0x7fa0e71e9e08  yb::master::ClusterLoadBalancer::MoveLeader()
    @     0x7fa0e71e9f5d  yb::master::ClusterLoadBalancer::HandleLeaderMoves()
    @     0x7fa0e72f8884  yb::master::enterprise::ClusterLoadBalancer::HandleLeaderMoves()
    @     0x7fa0e71efef0  yb::master::ClusterLoadBalancer::RunLoadBalancer()
    @     0x7fa0e72f995e  yb::master::enterprise::ClusterLoadBalancer::RunLoadBalancer()
    @     0x7fa0e71dee9b  yb::master::CatalogManagerBgTasks::Run()
    @     0x7fa0dcd6504f  yb::Thread::SuperviseThread()
    @     0x7fa0d84a4694  start_thread
    @     0x7fa0d7be141d  __clone
    @              (nil)  (unknown)

**Comment by bmatican** [comment]
Fixed as part of #5182
