### ISSUE TITLE
[Platform] Allow editing cloud provider config if no universe is associated with the provider

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5296]
Issue:
The current cloud config edit modal has limited capabilities which don't allow to edit access keys, network settings (vpc/port access, region mapping). The workaround is to delete the entire config for making any further edits. 

This issue relates to [#5260](https://github.com/yugabyte/yugabyte-db/issues/5260) 

Proposed Solution: 

1. Extend the edit modal to include editing of the network, IAM settings. 
2. These configs can only be changed if there is no active universe using that cloud provider.

**Comment by streddy-yb** [comment]
- It is important to figure out which parameters are truly editable before working on this issue. 
- This will also require provider specific rules

**Comment by nishantSharma459** [comment]
Still in discussion what needs to be edited.

**Comment by streddy-yb** [comment]
This fix only addresses the case where there is no universe associated with the provider. We also need to support editing a provider post creation.

**Comment by RP1807** [comment]
Validated this issue on 2.6 portal followed below steps 
1. Ensure the edit provider config is editable when there is no universe associated with the provider. 
2. Ensure the edit provider config is not editable when there are universes associated with the provider. 
3. Configure cloud provider and ensure it is editable as soon as the user creates it.
