### ISSUE TITLE
[docs] Improve documentation for K8s installation

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5298]
Current documentation for K8s based platform install is lacking context in certain areas

1. Add docs on how to change the release channels and 
2. How to upgrade Yugaware? This [page](https://docs.yugabyte.com/latest/yugabyte-platform/deploy/install-admin-console/kubernetes/#upgrade-yugabyte-platform-yugaware) needs to explain how to find the latest build version and images
3. How to find the public IP of Yugaware UI for registering a tenant? This [page](https://docs.yugabyte.com/latest/yugabyte-platform/deploy/configure-admin-console/) is missing K8s information.

**Comment by chirag-yb** [comment]
cc: @Arnav15

**Comment by lizayugabyte** [comment]
Kubernetes installation docs are up-to-date
