### ISSUE TITLE
[DocDB] Increase the timeout for table creation during restore

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5307]
In multi region deployments, sometimes the table creation can take more time. We need to increase the timeout before YW considers the task to have failed and then retries.

**Comment by bmatican** [comment]
I think having #5295 and increasing default to some 60s, might be good enough. It would be great if we didn't expose yet another config knob to the user, which would just complicate their understanding.

Closing as a duplicate for now
