### ISSUE TITLE
[docs] Update CQL client documentation for TLS clusters

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5312]
From #4957 

We should update docs at https://docs.yugabyte.com/latest/secure/tls-encryption/connect-to-cluster/ to remove references to SSL_USERCERT, SSL_USERKEY for CQL. @spolitov confirmed that we don't authenticate users based on their keys/certs, we only use the root certificate to encrypt data in transit.

**Comment by stevebang** [comment]
Removed mentions of SSL_USERCERT and SSL_USERKEY on the referenced page. Changes will appear in the 2.3.0.0-b176 release today.

**Comment by lizayugabyte** [comment]
Based on Steve's comment from sept 8, 2020, this ticked has been completed so I'm closing it.
