### ISSUE TITLE
[YSQL] Cannot update primary key if that would change partition

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#5319]
Updating primary keys (#659) and row-level partitioning (#5179) were developed concurrently, and do not play together perfectly.
Consider this example:
```sql
CREATE TABLE partition_t(id int PRIMARY KEY) PARTITION BY LIST(id);
CREATE TABLE partition_t_p1 PARTITION OF partition_t FOR VALUES IN (1, 2, 3);
CREATE TABLE partition_t_p2 PARTITION OF partition_t FOR VALUES IN (4, 5, 6);

INSERT INTO partition_t VALUES (1);

-- This works, as partition stays the same
UPDATE partition_t SET id = 2;

-- This is rejected in YSQL, but works in PostgreSQL v11
UPDATE partition_t SET id = 4;
```

Result of the second UPDATE:
```
yugabyte=# UPDATE partition_t SET id = 4;
ERROR:  new row for relation "partition_t_p1" violates partition constraint
DETAIL:  Failing row contains (4).
```

**Comment by ndeodhar** [comment]
@frozenspider When you say fails, can you add some details on what happens? Does the table have wrong data after the statement execution? What is the error shown to users?

**Comment by frozenspider** [comment]
No, this does not lead to an inconsistent state, this update is simply rejected. I've updated the issue details to make this clear.

**Comment by jaki** [comment]
I believe that this is a duplicate of the broader issue #5310: it doesn't have to be primary key.  @frozenspider, please close and mark as duplicate if you agree.

**Comment by frozenspider** [comment]
Thanks @jaki, I tested and confirmed that the symptoms (and the cause) is exactly the same and isn't related to UPDATE PK specifically. Closing this as duplicate.
