### ISSUE TITLE
[docdb] Default webserver_interface to rpc_bind_address IP/host component

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5320]
Currently, `rpc_bind_addresses` can be specified as an IP:port combination (or host instead of IP), while `webserver_interface` is just the IP (or host) component.

We should probably unify the behavior, since we already default the ysql/ycql/yedis bind addresses, based on `rpc_bind_addresses`.

**Comment by bmatican** [comment]
This will likely be similar to 1c8d73ff69418f25006165e83210b05d7434add0

Can check with @iSignal on a simple test for this

**Comment by ramsrivatsa** [comment]
Feature added with with the following commit ([1b4987b](https://github.com/yugabyte/yugabyte-db/commit/1b4987bf9a42fcc6018ab6ba3b3523941c3d414a)).
