### ISSUE TITLE
Show table namespace on TServer Admin UI

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5329]
When browsing on :9000/tablets, I noticed that the namespace for table is not shown.

It seems namespace should be shown on the Admin UI.

Note: I was looking at var/data/yb-data/tserver/logs/yb-tserver.WARNING :
```
W0805 17:40:36.230448 194441216 client-internal.cc:1332] GetTableSchemaRpc(table_identifier: table_name: "metrics" namespace { name: "system" database_type: YQL_DATABASE_CQL }, num_attempts: 1) failed: Not found (yb/master/catalog_manager.cc:3883): The object does not exist: table_name: "metrics" namespace { name: "system" database_type: YQL_DATABASE_CQL }
```
On Admin UI, I saw:
```
metrics | 2ea252081af042d1944545076c57d9a8 | afd1ed648bf248b98e8fd494faa4dcf4 | hash_split: [<start>, <end>) | RUNNING | 0 | Total: 1.01MConsensus Metadata: 9.2KWAL Files: 1.00MSST Files: 0BSST Files Uncompressed: 0B
-- | -- | -- | -- | -- | -- | --
```
but was not sure whether the metrics table is in system namespace.

By examining pg_catalog table, it seems the metrics table should be from system namespace (since there is no such table in yb_demo).

**Comment by bmatican** [comment]
This requires #3020, which @amitanandaiyer is actively working on. Could be an easy follow up afterwards.

**Comment by kmuthukk** [comment]
I think @amitanandaiyer 's changes for #3020 already covers this change also.
