### ISSUE TITLE
[Platform] Changing node count by AZ is doing a full move

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#5335]
Steps:

1. Edit universe
2. Reduce node counts by AZ
3. Save

will trigger a full move in 2.3.0.0 b59 build. This is a shrink universe operation and shouldn't trigger a full move.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-18

**Comment by streddy-yb** [comment]
@yb-andrew - can you back port this to 2.2?
