### ISSUE TITLE
a "KEYS" command for the yedis api

### ISSUE THREAD

**Issue by schlemihl** [YugaByte/yugabyte-db#534]
hi YugaByte team,

i wonder, why there is no "KEYS" command implemented for the yedis api.
i use it very often in redis world.
i also wonder, if a command/commands to query the lowest, the highest and maybe all times in a time series could be useful, couldn't it/they?

**Comment by rahuldesirazu** [comment]
Still have to update docs, but KEYS command is fully implemented in 59f2c32079a1746c2b5fe47ea33bac5643b242f4.
