### ISSUE TITLE
Yugabyte Client Docker Image Missing Python

### ISSUE THREAD

**Issue by sstubbs** [yugabyte/yugabyte-db#5342]
Hi,

Just tried to run https://hub.docker.com/r/yugabytedb/yugabyte-client to test it as I will be using this in a kubernetes job. ysqlsh seems to work fine but cqlsh and ycqlsh give the error `No appropriate python interpreter found` `apt install python` fixes this and I could create my own image that installs this but I assume that this should probably be fixed.

Thanks

**Comment by iSignal** [comment]
Thanks for the report @sstubbs, will fix.

**Comment by iSignal** [comment]
This should now be fixed in yugabytedb/yugabyte-client:latest - https://hub.docker.com/layers/yugabytedb/yugabyte-client/2.2.2/images/sha256-bde7b96f8f5655adec6bf9ff954eff8c2bcb85bc870e7222604ebfb954d0dc9f?context=explore
