### ISSUE TITLE
DumpReplayStateToStrings should handle too many entries scenario

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5345]
In DumpReplayStateToLog(), DumpReplayStateToStrings is called to gather the logs in ```vector<string>```.
Then we have:
```
      for (const string& line : state_dump) {
        LOG_WITH_PREFIX(INFO) << line;
        if (++i >= kMaxLinesToDump / 2) break;
      }
      LOG_WITH_PREFIX(INFO) << "(" << state_dump.size() - kMaxLinesToDump << " lines skipped)";
      for (i = state_dump.size() - kMaxLinesToDump / 2; i < state_dump.size(); ++i) {
```
The intention is to skip some lines so that only kMaxLinesToDump lines are logged.

```state_dump.size() <= kMaxLinesToDump``` above the block handles the case where there are not more than kMaxLinesToDump lines to log.

However, it seems we can trim replay state entries in DumpReplayStateToLog() (by checking OpIndexToEntryMap.size() against kMaxLinesToDump) since the entries beyond kMaxLinesToDump would not be logged. This way memory pressure is reduced by not collecting entries unnecessarily.

**Comment by tedyu** [comment]
[dump-replay-state.txt](https://github.com/yugabyte/yugabyte-db/files/5046766/dump-replay-state.txt)

The above patch moves limit handling from DumpReplayStateToLog to DumpReplayStateToStrings.

**Comment by ddorian** [comment]
@tedyu can you please create a pull request instead ?

**Comment by tedyu** [comment]
I created a brach, dump-replay-state, based on https://github.com/tedyu/yugabyte-db.git
However, I seem to face some issue pushing to the branch:
```
git push origin dump-replay-state
Username for 'https://github.com': tedyu
Password for 'https://tedyu@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/tedyu/yugabyte-db.git/'
```
I used the same password which allows me to log into github.com in browser.

**Comment by ddorian** [comment]
Maybe you set up 2 factor authentication ? 

https://medium.com/@ginnyfahs/github-error-authentication-failed-from-command-line-3a545bfd0ca8
https://stackoverflow.com/questions/17659206/git-push-results-in-authentication-failed

**Comment by tedyu** [comment]
Created #5357

**Comment by ddorian** [comment]
Thank you, I'm closing this issue and we'll track there.

**Comment by mbautin** [comment]
Usually we don't close issues until the corresponding pull request has been merged.

**Comment by mbautin** [comment]
@tedyu I was thinking that maybe we should simplify this a lot. How about we just print the number of pending replicates and their first/last OpId? WAL entries could contain user data and ideally we should not print them in the log altogether.

**Comment by tedyu** [comment]
Maybe we should get other people's input with regard to the simplified form of log.

Initially I expected some degree of detail from WAL entries dump which would facilitate troubleshooting.

**Comment by mbautin** [comment]
Here is an example of ReplicatePB fields, excluding the write batch. For the simplified form of log we could use the following fields:
- id
- hybrid_time
- op_type
- committed_op_id

BTW I should point out that these uncommitted entries ("pending replicates") at the end of tablet bootstrap are normally not a problem. They only become a problem when tablet bootstrap fails.

```
type: REPLICATE
replicate {
  id {
    term: 8
    index: 2401
  }
  hybrid_time: 6527228877876568064
  op_type: WRITE_OP
  write_request {
    tablet_id: "91bf626f5794471ba61db14f07aaca8f"
    write_batch {
    }
    client_id1: 16303715820282376196
    client_id2: 14161383940175931839
    request_id: 796
    min_running_request_id: 579
    batch_idx: 18446744073709551615
  }
  committed_op_id {
    term: 8
    index: 2107
  }
  monotonic_counter: 0
}
```

#5003 is an example of a relevant investigation that led to my recent fix / refactoring of tablet bootstrap, and the payload of write batches was definitely not needed during that investigation.

**Comment by mbautin** [comment]
BTW the logic to dump these entries to string with a limit should probably be super simple, parameterized by `half_limit` rather than `limit`.
- if n <= 2 * half_limit, dump all entries.
- if n > half_limit, dump first half_limit entries, then a message mentioning the number of skipped entries, then last half_limit entries.
