### ISSUE TITLE
DUPLICATE INDEX

### ISSUE THREAD

**Issue by ThanhPhiNgo** [yugabyte/yugabyte-db#5348]
Jira Link: [DB-1491](https://yugabyte.atlassian.net/browse/DB-1491)
![image](https://user-images.githubusercontent.com/35998028/89751103-fb3c5080-daf8-11ea-8abb-88f86f92a04d.png)
I create index using this syntax: `CREATE INDEX tdx_2 on usertable (FIELD2);`
The RPC response like above image. Then, I check the dashboard, I have seen that the index are already created. (I try this 3 times and got 3 indexes with the same name. Also, I can't drop these indexes) 
![image](https://user-images.githubusercontent.com/35998028/89751216-65ed8c00-daf9-11ea-87d8-c1b78c0506b3.png)

**Comment by ddorian** [comment]
Hi @ntphi 

Can you describe a little your setup ? 
What version, hardware, cluster setup ?

**Comment by ntphi** [comment]
I set up a cluster with 3 nodes, 
I'm using version 2.2, hardware: centos 7.x, core 32, memory 64GB.
I check that there a node in full swap condition, when i create an index in the above description.

**Comment by ddorian** [comment]
@ntphi I'm assuming this is YSQL & you had data in the table before creating the index, correct ?
So I can try to reproduce.

**Comment by ntphi** [comment]
That's right @ddorian

**Comment by ddorian** [comment]
@ntphi 
Is this a multi region scenario ?
Can you paste the schema of the table ? 
And the cardinality of values in the column ?
And how many rows were in the table ?

Can you also attach some logs from yb-tserver and yb-master ? ([how to get logs](https://docs.yugabyte.com/latest/troubleshoot/nodes/check-logs/)).

**Comment by kmuthukk** [comment]
@ntphi --

For YSQL index refill, you still need this recent fix:

1) https://github.com/yugabyte/yugabyte-db/commit/7f0f19adfa8045f4477b208c4e5489d96221e528 (#5031)

2) And you'll need to flip "ysql_disable_index_backfill" from true to false.

3) Currently, without #2 you are likely hitting a variant of a different issue --[YSQL] OOM when running ysql_dump 

A fix for this in the works.

In the interim, you can use yb-admin command to clear out the index from the system, and create the index up front before loading the data. We are hoping to put out a new 2.2.x release with these fixes soon.

cc: @jaki , @m-iancu

**Comment by ntphi** [comment]
@kmuthukk @ddorian, thank you for your support. :D

**Comment by jasonyb** [comment]
What probably happened is that the index got created in DocDB but the pg metadata for it was not created.  This old release probably did not have the rollback hook to delete the DocDB index.  You can delete the DocDB index using `yb-admin delete_index_by_id`.  cc: @deeps1991
