### ISSUE TITLE
TSRANGEBYTIME special bounds

### ISSUE THREAD

**Issue by schlemihl** [YugaByte/yugabyte-db#535]
hi YugaByte team,

what do you mean with

> Special bounds -inf and +inf are also supported to retrieve an entire range

how do i use this? my naive approach didn't work...
`127.0.0.1:6379> TSREVRANGEBYTIME ts -inf inf`

`(error) ERR TSREVRANGEBYTIME: inf is not a valid number`

maybe i am using a version that doesn't support it?
but i used  `yb-docker-ctl`to create it.
or maybe it is my version of redis-cli?

**Comment by rkarthik007** [comment]
cc @rahuldesirazu - could you please help answer this? Thanks!

**Comment by rahuldesirazu** [comment]
hi @schlemihl,

It looks like you should be using `+inf` instead of just `inf`. Hope that fixes your issue.

Sincerely,
Rahul Desirazu

**Comment by schlemihl** [comment]
yesss,
this works,

sorry & thanks
