### ISSUE TITLE
Small issues in recent tablegroup commits. 

### ISSUE THREAD

**Issue by vvkgopalan** [yugabyte/yugabyte-db#5351]
The following issues are present in the latest commits:

- newtup is not being properly deallocated in RenameTablegroup (src/postgres/src/backend/commands/tablegroup.c)
- DeleteTablegroup (src/yb/client/client.cc) has a block that does not properly return (lines 987-993)
- Comments / code formatting issues in AlterTablegroupOwner (src/postgres/src/backend/commands/tablegroup.c)

**Comment by tedyu** [comment]
The first two items were spotted during code review.

**Comment by vvkgopalan** [comment]
Thanks @tedyu !
