### ISSUE TITLE
[docs] Add instructions for installing platform on premise VM

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5356]
Extend [this page](https://docs.yugabyte.com/latest/yugabyte-platform/deploy/prepare-cloud-environment/aws/) to include  the prereqs for installing the replicated-based platform on an on-prem VM

Information to include:
YB Platform VM/Node config - Cores, Memory, and storage (including long term Prometheus data)
Minimum Docker version for YB Platform containers
Other s/w: Python version, JDK etc.

**Comment by chirag-yb** [comment]
Supported OS - Ubuntu 16+, Debian 9, Centos 7+
Machine configuration - 4 vCPU, 8 GiB memory
Open Ports -  22 (for SSH), 8800 and 80
Dependency  - Docker will be installed by Replicated

**Comment by chirag-yb** [comment]
@WesleyW can you also provide instructions on sudo user roles/permissions. Include the set of actions that a user needs to take

**Comment by ddhodge** [comment]
Looks done as part of work for #5369, which was noted as a duplicate; on prem setup documented [here](https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes/)
