### ISSUE TITLE
Enhance YB Platform docs for on-prem deployment

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#5369]
Add a new section to YB Platform Prepare Cloud section for on-prem install
https://docs.yugabyte.com/latest/yugabyte-platform/deploy/prepare-cloud-environment/aws/

Information to include:
YB Platform VM/Node config - Cores, Memory, and storage (including long term Prometheus data)
Minimum Docker version for YB Platform containers
Other s/w: Python version, JDK etc.

**Comment by chirag-yb** [comment]
Duplicate [5356](https://github.com/yugabyte/yugabyte-db/issues/5356)
