### ISSUE TITLE
One CQL call can lead to multiple writes to DocDB due to internal retries

### ISSUE THREAD

**Issue by ttyusupov** [YugaByte/yugabyte-db#537]
We can have one CQL call lead to multiple writes to DocDB with different timestamps due to retries inside TabletInvoker.
So, we can have a scenario when a sequence of two CQL calls: `write 4`, `cas 4->1` lead to having 3 values into DocDB:
```
SubDocKey(DocKey(0xba22, [0], []), [ColumnId(1); HT{ physical: 1540796350911062 w: 1 }]) -> 4
SubDocKey(DocKey(0xba22, [0], []), [ColumnId(1); HT{ physical: 1540796350842148 }]) -> 1
SubDocKey(DocKey(0xba22, [0], []), [ColumnId(1); HT{ physical: 1540796338616427 w: 1 }]) -> 4
```

And concurrent reader observes reading 4, 1, 4.
Which is treated by Jepsen as non-linearizable history and breaks the Single key ACID test.
This happens under kill-start-tserver nemesis when tservers are randomly killed and started during workload.

**Comment by kmuthukk** [comment]
Nice work @spolitov !

Fixed in https://github.com/YugaByte/yugabyte-db/commit/023c20ad6caf13e5228081ddec07d9f3cf904348
