### ISSUE TITLE
[docdb] Change default restore semantics to fail if tables already exist

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5372]
Jira Link: [DB-2449](https://yugabyte.atlassian.net/browse/DB-2449)
Currently, when we do a restore, we could restore into the same cluster, over the same tables, which would discard existing data, while importing the backed up data. The problem though is that we do not change any of the master metadata, in this mode. This would be a problem for tablet splitting though, where the metadata of what tablets were in the cluster when we created the backup, could be different from when we choose to do the restore.

Some notes from offline discussion
- by default, disable overwriting existing data, even if restoring in the same cluster / same table names and UUIDs
- fail restore if any tables with same name already exist
- add option to preserve above behavior, if desired
- optionally change implementation to explicitly drop the tables, if they exist, so we recreate the metadata on restore as well -- *deemed too dangerous so we'll not do this*

**Comment by OlegLoginov** [comment]
A few related questions:

1. Is it related to YCQL only? (Or somehow to YSQL too.)   << I guess it's for YCQL only at the moment.

[Bogdan] Do we even support this mode for YSQL, where you’d keep the database, but overwrite the table data? My understanding is that no, as there’s a lot more metadata to handle in YSQL (eg: ysql_dump, etc)

[Oleg] For YSQL - we apply ysql_dump tool dump file back via ysqlsh. CREATE TABLE can fail, and this is the case of table overwriting. Finally - yes, restoring back with table overwriting  is supported.


2. Do we need (in some form/way) an option to restore the table without deleting?  << NO, as far as I understand from the discussion.

[Bogdan] Actually, yes, we could preserve the current behavior, under some flag/pb bool, but make it not be the default.

[Oleg] OK


3. Do we want (A) workaround - to fail restore if the table exists   (B) automatically delete the table   (C) both A and B - controlled by a flag  ?   << (A)?

[Bogdan] Automatically deleting feels a bit dangerous, so at least failing upfront (before we start any restore) and telling the user which tables need to be deleted, would be great. cc @rao

[Oleg] Ok. Got it.

**Comment by lingamsandeep** [comment]
The recommendation is to drop the existing database before performing a restore. YBA already does this. Given this, resolving the issue.
