### ISSUE TITLE
[Platform] Add EULA in the install flow

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#5376]
We have recently published EULA on our [web page](https://www.yugabyte.com/eula/) which also needs to be published in the product installation. Users need to accept T&C to finish the installation setup. 

The proposal is to add EULA before the admin user registration so it can work consistently for all installation types - Replicated, Non- Replicated, and K8s.

**Comment by chirag-yb** [comment]
Mock available here - https://xd.adobe.com/view/372c7534-8dce-40d6-9768-e667241155dc-627f/
- Add a checkbox with EULA hyperlink
- Register button is enabled after the checkbox is enabled 
- For API based platform installation EULA is not enforced

**Comment by streddy-yb** [comment]
Let us prioritize this for next week.,
