### ISSUE TITLE
[YSQL] Send updated columns back to postgres 

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#5392]
Jira Link: [DB-4825](https://yugabyte.atlassian.net/browse/DB-4825)
For now UPDATE command with RETURNING clause can not be pushed down in all the casese

```
CREATE TABLE t(k INT PRIMARY KEY, v int);
INSERT t VALUES(1, 1);
UPDATE t SET v = v + 1 WHERE k = 1 RETURNING v;
```

Reason in case of push down `v = v + 1` is calculated on DocDB side and postgres doesn't have actual value.

**Comment by m-iancu** [comment]
This was addressed in https://github.com/yugabyte/yugabyte-db/issues/8162. Closing.
