### ISSUE TITLE
Replication factor defaults to 3

### ISSUE THREAD

**Issue by hengestone** [YugaByte/yugabyte-db#54]
Trying to create a keyspace with replication factor=1 seems to change the value to 3:
`cqlsh> CREATE KEYSPACE myapp WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = false;`

Then Describe gives:
`cqlsh> describe myapp;
CREATE KEYSPACE myapp WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'} AND durable_writes = true;`

Other CQL commands also seem to default to 3, e.g. on a cluster with rf=1, creating a table gives the error:
` Not enough live tablet servers to create table with the requested replication factor 3. 1 tablet servers are alive.`

**Comment by hengestone** [comment]
As per @bmatican creating the cluster with `./bin/yb-ctl --replication_factor 1` from the beginning solves this problem.

**Comment by bmatican** [comment]
Glad that helped @hengestone ! We have on our roadmap to integrate support for overrides at keyspace/table level (and we've had some previous interest in that too: #13), but for now, we just allow setting them at the level of the entire deployment...

**Comment by kmuthukk** [comment]
@bmatican - assigning this to you...  perhaps we can close this, but open a new issue to support keyspace level overrides for settings like replication factor.

**Comment by bmatican** [comment]
Closing this one, filed #149 for the override part.
