### ISSUE TITLE
[docdb] master log spew when TLS is enabled

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5404]
W0814 20:05:20.170982 4149 tcp_stream.cc:130] { local: 10.88.16.60:7100 remote: 10.89.16.18:40594 }: Shutting down with pending inbound data ({ capacity: 369280 pos: 0 size: 67 }, status = Service unavailable (yb/rpc/reactor.cc:91): Shutdown connection (system error 108))
W0814 20:05:20.216502 4150 tcp_stream.cc:130] { local: 10.88.16.60:7100 remote: 10.89.16.18:40596 }: Shutting down with pending inbound data ({ capacity: 369280 pos: 0 size: 67 }, status = Network error (yb/rpc/secure_stream.cc:509): Insecure connection header: 5942)
W0814 20:05:20.216645 4150 tcp_stream.cc:130] { local: 10.88.16.60:7100 remote: 10.89.16.18:40596 }: Shutting down with pending inbound data ({ capacity: 369280 pos: 0 size: 67 }, status = Service unavailable (yb/rpc/reactor.cc:91): Shutdown connection (system error 108))
W0814 20:05:20.264262 4150 tcp_stream.cc:130] { local: 10.88.16.60:7100 remote: 10.89.16.18:40604 }: Shutting down with pending inbound data ({ capacity: 369280 pos: 0 size: 67 }, status = Network error (yb/rpc/secure_stream.cc:509): Insecure connection header: 5942)

**Comment by bmatican** [comment]
Seems to trace to the ybclient inside the master, which does not have the secure context initialized correctly.

**Comment by bmatican** [comment]
Fixed in #5905
