### ISSUE TITLE
[docdb] Spark related tests flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5405]
Jira Link: [DB-1481](https://yugabyte.atlassian.net/browse/DB-1481)
https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&build_type=all&class=org.yb.loadtester.TestCassandraSparkWordCount&name=testDefaultRun&platform=centos

https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&build_type=all&class=org.yb.loadtester.TestSparkLocality&name=testDefaultRun&platform=centos

Seem to trace back to the YCQL system query cache diff: https://github.com/yugabyte/yugabyte-db/commit/fa39b56f6ecb07450c1dcaee698ecea6096819be

**Comment by tedyu** [comment]
WordCount test has been fixed.

TestSparkLocality is one of the top flaky tests.
```
2020-12-11 18:38:51,055 (Time-limited test) [INFO - org.yb.loadtester.TestSparkLocality.testDefaultRun(TestSparkLocality.java:118)] local writes 343 remote writes 657
```
Upon examining test output, I observed system query cache activities during the test. We should lengthen the cql_update_system_query_cache_msecs parameter to deflake the test.

Having run locality test 42 times locally without single test failure.
