### ISSUE TITLE
[docdb] AreLeadersOnPreferredOnly times out in Platform when setting preferred zones

### ISSUE THREAD

**Issue by vvkgopalan** [yugabyte/yugabyte-db#5406]
"With the change to allow transaction status table leaders to be in all regions (not just the preferred regions), an Edit Universe task to change the preferred regions ends up not completing (and eventually times out -- harmless, but leaves an error state in YW Universe view)."

May be cleaner to change the behavior of `AreLeadersOnPreferredOnly` in `catalog_manager_util` to incorporate some of the logic of `AreTransactionLeadersSpread` that was added here https://github.com/yugabyte/yugabyte-db/commit/51be987f2ee41e995b4e5672e74a31c2660ca53a and remove that RPC. That way, regardless of the value of the gflag for whether the transaction status tables respect preferred zones, we can issue a single RPC that (1) checks that all are in preferred zones if txn status tables are using pref zones or (2) checks that all other leaders are in preferred zones and that the txn status leaders are evenly spread (like the logic in `AreTransactionLeadersSpread`)

Some of the load balancer tests would also need to be modified.

cc @kmuthukk

**Comment by hulien22** [comment]
Closed by 513fc81
