### ISSUE TITLE
[YCQL] Correctly set release_version for system.peers queries

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#5407]
Currently the `release_version` column exists in the `system.peers` table and has the right type, but the value is not being set when producing the result for queries. Therefore its value is always returned as `null`.

#### Start a cluster locally with:
```
./bin/yb-ctl create --rf 3
```

#### Connect with ycqlsh
```
./bin/ycqlsh
```

#### Check release version in system.local (should be set correctly)
```
select key, broadcast_address, release_version from system.local ;
```
```
 key   | broadcast_address | release_version
-------+-------------------+-----------------
 local |         127.0.0.1 |    3.9-SNAPSHOT
```

#### Check release version in system.peers (will be null)
```
select peer, release_version from system.peers;
```
```
 peer      | release_version
-----------+-----------------
 127.0.0.3 |            null
 127.0.0.2 |            null
```

### Relevant code

The YCQL system tables are implemented as virtual tables, and the results for them are constructed in code.
Specifically for `system.local` the release version is set in [yql_local_vtable.cc:LocalVTable::RetrieveData](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/yql_local_vtable.cc#L117).
On the other hand for `system.peers` the column is indeed created in [yql_peers_vtable.cc:PeersVTable::CreateSchema](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/yql_peers_vtable.cc#L159).
But its value is not set in [yql_peers_vtable.cc:PeersVTable::RetrieveData](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/yql_peers_vtable.cc#L50).
Fix should be to set the value accordingly (also the value `"3.9-SNAPSHOT"` should probably become a const in a shared place like `yql_local_vtable` for code cleanliness).

### Testing
The main test for YCQL system tables is [TestSystemTables.java](https://github.com/yugabyte/yugabyte-db/blob/master/java/yb-cql/src/test/java/org/yb/cql/TestSystemTables.java) so we should add a test for this there (probably extend an existing test to check this value).
Note: the test can be ran using:
```
ybd --java-test org.yb.cql.TestSystemTables
```

**Comment by tedyu** [comment]
[release-ver.txt](https://github.com/yugabyte/yugabyte-db/files/5092471/release-ver.txt)

Came up with a patch.

Trying to compose a test next.
