### ISSUE TITLE
[YSQL] Add support for jsonb_path_query

### ISSUE THREAD

**Issue by ggilley** [yugabyte/yugabyte-db#5408]
You've added a lot of support for jsonb already. It would be great to support jsonb_path_query. This function greatly simplifies handling complex json queries.

[postgresql docs](https://www.postgresql.org/docs/12/functions-json.html)

**Comment by ddorian** [comment]
`jsonb_path_query` was added in PostgreSQL 12 ([release notes](https://www.postgresql.org/docs/12/release-12.html)), while we support PostgreSQL 11. [Blog post](https://www.depesz.com/2019/03/19/waiting-for-postgresql-12-partial-implementation-of-sql-json-path-language/) that explains it's introduced in 12.

**Comment by tedyu** [comment]
As of commit 8e51f2336821b2e73769cd7a49dbf407e10ed2c5, the jsonpath related commits from Postgres (apart from a few doc only patches) have been ported to Yugabyte DB 2.3
