### ISSUE TITLE
[ysql] Support copying all tables from a namespace to another

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#541]
Reported by @m-iancu.

Needed for PostgreSQL's `create database` which initializes the new database by copying from a source database (template1 by default, but could technically also be template0 or any user-declared database).

**Comment by robertpang** [comment]
Implemented in commit [efd44a1](https://github.com/YugaByte/yugabyte-db/commit/efd44a194d887a47b91eca9a75ec55cda598227e).
