### ISSUE TITLE
Add under-replicated tablet info to {master}:7000/tablet-replication page

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#5420]
We should _at least_ list tablet IDs and num replicas of any tablets which are under replicated in a separate table on this page

Note that we should eventually also expose this info in #1834

**Comment by bmatican** [comment]
We should be able to test this with
- `yb-ctl --rf 3 create --tserver_flags="follower_unavailable_considered_failed_sec=30"` to setup a 3 node local cluster
- `yb-ctl stop_node 3` to stop the 3rd TS
- after 30s (the flag we pass in), that TS will have all its tablets removed from all their raft groups, so they'll show up as under-replicated, which is when we should display them in this new UI

See 65b7f5de73781ad701b357b44ac41860552f297b as good sample prior work in this area and feel free to check with @robertsami

**Comment by sanketkedia** [comment]
<img width="1791" alt="Screen Shot 2020-11-19 at 3 15 27 PM" src="https://user-images.githubusercontent.com/14816236/99736087-a6ef2800-2a7a-11eb-888b-23b2c4a18ef9.png">
<img width="1780" alt="Screen Shot 2020-11-19 at 3 18 23 PM" src="https://user-images.githubusercontent.com/14816236/99736094-a9ea1880-2a7a-11eb-89b9-15726305cc51.png">

**Comment by sanketkedia** [comment]
![image](https://user-images.githubusercontent.com/14816236/102122441-53ae9200-3dfa-11eb-9df7-f3fd3984fda8.png)

**Comment by sanketkedia** [comment]
![image](https://user-images.githubusercontent.com/14816236/102122478-6032ea80-3dfa-11eb-89b3-ec08cad4a97e.png)
