### ISSUE TITLE
[docs] Add examples for COPY TO statement

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#5422]
@kmuthukk and I were talking about needing examples for the `COPY TO` statement -- we need three examples:

- using `table_name`
- using `column_name`
- using `query`
- outputting to CSV file

https://docs.yugabyte.com/latest/api/ysql/commands/cmd_copy/#copy-to

**Comment by rkarthik007** [comment]
Also an example on how to run a command to extract a subset of rows using `COPY TO`. Some examples here but we need a more exhaustive section: https://docs.yugabyte.com/latest/migrate/migrate-from-postgresql/export-data/
