### ISSUE TITLE
[Platform] Migrate Platform to python3

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#5425]
Migrate managed/devops code to be fully python3 compatible. Some things to watch out for:

-ipaddr.IPNetwork -> IPAdress.ip_network
-list.{iteritems, keys, values} etc. return not views not lists (needs typecsting if performingg list ops afterwards)
print -> print()
-Exception.message -> str(Exception)

Some functions will output bytes instead of str:
-subprocess.check_output
-urlopen
-Popen().communicate()
-CalledProcessError.output

[].sort(lambda f) -> needs to be sort(key= lambda f)

pycrypto needs to be pycryptodome

**Comment by bhavin192** [comment]
This fixed one of the issue from https://github.com/yugabyte/yugabyte-db/issues/6536
> Python 3.8 has deprecated platform.linux_distribution which is used in yb_release scripts.
