### ISSUE TITLE
[Platform] Improve the Replication graph to display the graph and metric names cleanly

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5429]
Right now the names of the metrics overlap with the graph itself. If necessary let's increase the size of the widget as this is the only graph on the page,

**Comment by streddy-yb** [comment]
@yb-andrew - As part of addressing this issue, can you also remove the _async replication lag_ metric in async replication lag metric in the top-level "YCQL Ops and Latency" Panel?
