### ISSUE TITLE
[YSQL] Allow multiple schemas in the same tablet (needed for PostgreSQL system tables)

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#544]
Log segment header stores the schema. Need to support multiple schemas there.

Update (11/8/2018): @robertpang looked at tablet bootstrap code and it does not seem like it is necessary to store the schema in the log segment header.

**Comment by robertpang** [comment]
This is implemented in commit [091b469](https://github.com/YugaByte/yugabyte-db/commit/091b469a7c1eeb80828d8ebb032931cab0d13011).
