### ISSUE TITLE
[YSQL] Allow a fully-functional tablet server interface in the master

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#545]
We need to be able to send tserver operations to the master.

**Comment by mbautin** [comment]
This depends on https://github.com/YugaByte/yugabyte-db/issues/544 (multiple schemas in the same tablet).

**Comment by robertpang** [comment]
This is implemented in commit [091b469](https://github.com/YugaByte/yugabyte-db/commit/091b469a7c1eeb80828d8ebb032931cab0d13011).
