### ISSUE TITLE
[ysql] Optimize PostgreSQL SELECT when hash and range components are all specified

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#546]

**Comment by nocaway** [comment]
This bug has been fixed by the following commit.

commit 89479240911d18929a972ed8cdc0756031757ecd
Author: Neil Le <neil@yugabyte.com>
Date:   Wed Oct 24 21:17:31 2018 -0700
    SELECT with fully-specified multi-column primary key
