### ISSUE TITLE
fix URL for GRANT statement documentation page

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5466]
In Docs

Reference > APIs >  YSQL > Grant 

The URL reference has a typo: (`dcl_grant` should be `ddl_grant`).

https://docs.yugabyte.com/latest/api/ysql/commands/dcl_grant/
-->
https://docs.yugabyte.com/latest/api/ysql/commands/ddl_grant/

**Comment by stevebang** [comment]
@kmuthukk  GRANT is a DCL statement, so that's correct. Is there a broken link?

**Comment by kmuthukk** [comment]
I see. Wasn't familiar with the DCL terminology. Fair enough.
