### ISSUE TITLE
Error starting yugabytedb 2.2.2.0 with python@3.8.5 in macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by yeongsheng-tan** [yugabyte/yugabyte-db#5469]
Downloaded latest yugabtye-2.2.2.0 and attempted to clean restart using `wipe_restart` for a 3 node setup and hit below error:
```zsh
~/Downloads/yugabyte-2.2.2.0 $ ./bin/yb-ctl --rf 3 wipe_restart
Destroying cluster.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1394, in stop_process
    os.kill(pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/yb-ctl", line 2021, in <module>
    control.run()
  File "./bin/yb-ctl", line 1998, in run
    self.args.func()
  File "./bin/yb-ctl", line 1822, in wipe_restart_cmd_impl
    self.destroy_cmd_impl()
  File "./bin/yb-ctl", line 1801, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "./bin/yb-ctl", line 1730, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "./bin/yb-ctl", line 1429, in stop_daemon
    self.stop_process(postgres_pid, "Postmaster for {}".format(daemon_id))
  File "./bin/yb-ctl", line 1396, in stop_process
    if e.errno == os.errno.ESRCH:
AttributeError: module 'os' has no attribute 'errno'
Viewing file /var/folders/11/btv6w5410yz8bcyrx0nn6gsw0000gn/T/tmp1pt950n_:
^^^ Encountered errors ^^^
2020-08-24 14:51:19,272 INFO: Server master-1 already stopped
2020-08-24 14:51:19,294 INFO: Server master-2 already stopped
2020-08-24 14:51:19,316 INFO: Server master-3 already stopped
2020-08-24 14:51:19,339 INFO: Server tserver-1 already stopped
2020-08-24 14:51:19,341 INFO: Stopping Postmaster for tserver-1 PID=23321
```

My macOS python info:
```zsh
~/Downloads/yugabyte-2.2.2.0 $ python --version
Python 3.8.5
~/Downloads/yugabyte-2.2.2.0 $ which python
/usr/local/opt/python@3.8/libexec/bin/python
```

My macOS info:
```zsh
~/Downloads/yugabyte-2.2.2.0 $ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G2021
```

**Comment by ddorian** [comment]
Hi @yeongsheng-tan 

For some reason the fix for this wasn't included on the release, checking internally.
In the meantime, can you do [this workaround](https://github.com/yugabyte/yugabyte-db/issues/5118#issuecomment-659413570) ?

**Comment by yeongsheng-tan** [comment]
> Hi @yeongsheng-tan
> 
> For some reason the fix for this wasn't included on the release, checking internally.
> In the meantime, can you do [this workaround](https://github.com/yugabyte/yugabyte-db/issues/5118#issuecomment-659413570) ?

Yup. I was surprised to hit the same issue as before.

As usual, the problem is fixed by changing bin/yb-ctl script file.

However, in the latest version of macOS Catalina OS patch that came last week, it now seems to prevent "internet downloaded" bin from being spawned.


I get these prompts on macOS and I would click 'Cancel' which then terminates each of the processes of `yb-master`, `ts-server` and `ts-admin`, and my server logs spits the following:
<img width="419" alt="Screenshot 2020-08-24 at 5 34 36 PM" src="https://user-images.githubusercontent.com/809030/91028700-6d9c4d00-e630-11ea-9035-451217140842.png">

<img width="416" alt="Screenshot 2020-08-24 at 5 34 46 PM" src="https://user-images.githubusercontent.com/809030/91028750-7c82ff80-e630-11ea-82ee-2eeed7ab6fe6.png">

<img width="417" alt="Screenshot 2020-08-24 at 5 34 54 PM" src="https://user-images.githubusercontent.com/809030/91028761-80168680-e630-11ea-8c13-213925904b67.png">

```zsh
2020-08-24 17:34:26,687 INFO: Waiting for master and tserver processes to come up.
2020-08-24 17:34:26,860 INFO: Waiting for master leader election and tablet server registration.
2020-08-24 17:34:57,920 INFO: PIDs found: {'master': [None, None, None], 'tserver': [None, None, None]}
2020-08-24 17:34:57,924 ERROR: At least one master or tserver process is down.
```

**Comment by ddorian** [comment]
There are several workarounds from a quick google search 

https://github.com/hashicorp/terraform/issues/23033#issuecomment-543507812
https://github.com/hashicorp/terraform/issues/23033#issuecomment-540262070
https://github.com/hashicorp/terraform/issues/23033#issuecomment-541895676
https://github.com/hashicorp/terraform/issues/23033#issuecomment-553431351

**Comment by yeongsheng-tan** [comment]
> There are several workarounds from a quick google search
> 
> [hashicorp/terraform#23033 (comment)](https://github.com/hashicorp/terraform/issues/23033#issuecomment-543507812)
> [hashicorp/terraform#23033 (comment)](https://github.com/hashicorp/terraform/issues/23033#issuecomment-540262070)
> [hashicorp/terraform#23033 (comment)](https://github.com/hashicorp/terraform/issues/23033#issuecomment-541895676)
> [hashicorp/terraform#23033 (comment)](https://github.com/hashicorp/terraform/issues/23033#issuecomment-553431351)

This worked for me. Thanks a million:
```zsh
xattr -r -d com.apple.quarantine <root path to downloaded yugabyte-db dir>
```
