### ISSUE TITLE
[docdb] Add tablet ID in the TS UI on /tablet-consensus-status

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5473]
When clicking through on a tablet, in a TS /tablets view, we can look at it's consensus status. In there, we do not display the tablet ID, we just have it in the endpoint, eg: 127.0.0.1:9000/tablet-consensus-status?id=02ea2f428dd44087a62fd0c9d07de97f

**Comment by idnaninitesh** [comment]
Hey @bmatican, I've raised a PR (#5969) to address the above functionality. Kindly review.
