### ISSUE TITLE
[DocDB] Tablet Write Aborts for Long Running Transaction

### ISSUE THREAD

**Issue by emhna** [yugabyte/yugabyte-db#5474]
While working on the YSQL `copy from` query, an error message was found which led the query to abort.
`copy from` query copies over rows from a file and inserts into a table.
Here is the related Github issue: https://github.com/yugabyte/yugabyte-db/issues/2855

This behaviour was seen while processing larger files that were greater than 1-2 gb in size.
Please have a look at the snapshot of the postgres logs below.

Prior to transaction abort, it is observed that many heartbeat failures occur during transaction update operation.
The abort happens while tablet performs write operation.
 
One approach to fix this was to increase `timestamp_history_retention_interval_sec` to a very high value (say several days) at both yb-master and yb-tserver level when creating the universe. However, the same error occurred and query aborted.

One fix that worked was to split single transaction commit into multiple commits, say in batches of 1000 rows at a time.
The query succeed on a file as large as 15gb.

It would help to understand what is happening in the docDB layer which causes large data processes to fail.

Postgres log snapshots:
<img width="1915" alt="15gb failed 1 1" src="https://user-images.githubusercontent.com/66644511/91095734-d385d600-e62a-11ea-8b78-2f0f05a13ec2.png">
<img width="1920" alt="15gb failed 1 2" src="https://user-images.githubusercontent.com/66644511/91095738-d54f9980-e62a-11ea-87e1-a13448f7ef1c.png">

**Comment by emhna** [comment]
With https://phabricator.dev.yugabyte.com/D8697 fix, I have retested `COPY FROM` queries on large files (1gb+).

The `transaction metadata missing` is no longer showing and query completes on larger files (such as 4gb) which it used to fail previously.
However, different type of failure occurred while processing 8gb+ files.

Note query was tested after setting high history retention interval on both master and tserver:
--master_flags="timestamp_history_retention_interval_sec=80000000" --tserver_flags="timestamp_history_retention_interval_sec=80000000"

From the logs, UpdateTransaction fails with a time out proceeded by LookupByIdPrc timeout.
<img width="1919" alt="15gb UpdateTransaction Fail log 1 1" src="https://user-images.githubusercontent.com/66644511/92786937-ac433e80-f376-11ea-885a-a93648e9e6ff.png">
<img width="1917" alt="15gb UpdateTransaction Fail log 1 2" src="https://user-images.githubusercontent.com/66644511/92786945-ae0d0200-f376-11ea-8ed7-f5708cce78f2.png">

**Comment by emhna** [comment]
Investigating the logs (above) and performance details on GCP (dev-server-ena), there were couple interesting stats.

Starting at 9:12 UTC (5:12 EST), UpdateTransaction failure started to appear in postgres logs.

In GPC, at 9:11 UTC (5:11 EST), incoming network packets spiked to 761 packets/sec.
Then at 9:12 UTC (5:12 EST), incoming network bytes spiked to 197 KB/sec.
No other outliers were present in CPU, Disk I/O (bytes, operations) at the time.

At 11:50 UTC (7:50 EST), UpdateTransaction failure started to occur again according to postgres logs.
After 4 such errors, the Write RPC timed out and aborted the query at 11:51 UTC (7:50 EST).

<img width="1617" alt="Network" src="https://user-images.githubusercontent.com/66644511/92810648-ba4f8a00-f38b-11ea-8ff0-4533765ac3ba.png">
<img width="1610" alt="CPU" src="https://user-images.githubusercontent.com/66644511/92810662-bcb1e400-f38b-11ea-88af-a1b46bcd2774.png">
<img width="1615" alt="Disk" src="https://user-images.githubusercontent.com/66644511/92810667-bde31100-f38b-11ea-9ca0-b44e43821640.png">

Additional information on the test run:
- The client, in this case the YSQL query process, was running on same VM as the DB (same devserver machine)
- RF was kept as default size of 1
- The universe was a local cluster (ie. not multi-zone)
- Both client and server were running on devserver centOS with the following specs:
    - 4 CPU cores
    - 15 GB physical memory 
    - 15 GB RAM
- Ran on 4 integer column table with primary key

**Comment by bmatican** [comment]
I've tested this in a similar setup, but with the most important distinction being that client and server were on different machines. Ran this multiple times and it completed successfully in ~5.5hrs every time, so I think the problem was that the server would hit 100% cpu and thus end up failing certain requests.

Closing for now.
