### ISSUE TITLE
[ysql] Disable unneeded PostgreSQL backend processes in YB mode

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#548]
Like autovacuum, WAL writer.

**Comment by NitronR** [comment]
@mbautin is this issue still open?

**Comment by m-iancu** [comment]
Closing as this should be done in latest. Most of the work was probably done in: https://github.com/yugabyte/yugabyte-db/commit/ca30a3ab5252858103cf6f3f92697821e9b718df. 
See the Misc section in the summary:
```
  - Un-needed Postgres background workers are now disabled (e.g. vacuum worker).
```
