### ISSUE TITLE
TLS Not Working

### ISSUE THREAD

**Issue by sstubbs** [yugabyte/yugabyte-db#5491]
I thought it was an issue with the way I was generating the certificate but the default certificate also doesn't work for me.

**Comment by rkarthik007** [comment]
Hi @iSignal @bhavin192 - could you folks please take a look at this?

**Comment by rkarthik007** [comment]
cc @Arnav15 as well

**Comment by iSignal** [comment]
@sstubbs : could you add more details about (a) the command line you used to deploy the helm chart, including the version and (b) the command line you used to connect from the client.

**Comment by sstubbs** [comment]
I've added how I installed it here https://github.com/yugabyte/yugabyte-db/issues/4682

**Comment by iSignal** [comment]
Let's track in #4682
