### ISSUE TITLE
[yb-admin] create_snapshot fatal for YCQL system tables

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#5492]
`yb-admin create_snapshot` doesn't seem to work for YCQL system tables and YSQL tables.

YCQL system tables:

```
./bin/yb-ctl create
./build/latest/bin/yb-admin --master_addresses 127.0.0.1 create_snapshot system peers
```

master logs show

```
F0825 15:01:34.036633   967 flush_manager.cc:68] Check failed: ts_tablet_map.size() > 0 (0 vs. 0)
```

YSQL tables:

```
./bin/yb-ctl create
./bin/ysqlsh -c "CREATE TABLE t (i int)"
./build/latest/bin/yb-admin --master_addresses 127.0.0.1 create_snapshot ysql.yugabyte t
```

stderr shows

```
Error: Invalid argument (yb/master/catalog_manager.cc:7990): Unable to create snapshot of tables: [yugabyte.t]: Getting indexes for YSQL table is not supported: 000030a9000030008000000000004000 (master error 20)
```

I believe YSQL table snapshots aren't supported yet, so the error message for that is probably good left as is.  However, the fatal for YCQL system tables is probably not what we want.

**Comment by ramsrivatsa** [comment]
Fixed this issue with this commit [d0cfbad](https://github.com/yugabyte/yugabyte-db/commit/d0cfbad8766ecd3bfeae8cba2db32214cf7431be).

**Comment by bmatican** [comment]
Re-opening this, as it mistakenly also captured the redis tables, @ramsrivatsa is reverting that

**Comment by bmatican** [comment]
@OlegLoginov do you think this should be done on the client (yb-admin) side, or on the server (catalog_manager) side?

I passed this to @es1024 who's recently joined DST, as a starter task to get a bit more familiar with our client side tooling and how to run it against an active cluster, etc.
