### ISSUE TITLE
Add a stop command to yb-ctl

### ISSUE THREAD

**Issue by hengestone** [YugaByte/yugabyte-db#55]
There is currently no way to stop a cluster created with `yb-ctl`. Only `destroy` which also deletes all data.

**Comment by ayushsengupta1991** [comment]
The issue has been resolved: https://github.com/YugaByte/yugabyte-db/commit/7f57b0c6a1a9c63ebb9137ff43bbb8144a4c5a56

At this point of time yb-ctl supports the following commands:

 **Creating a cluster with default settings**
 yb-ctl start (yb-ctl create)

**Creating a cluster with replication factor 5**
yb-ctl --rf 5 start

**Creating a cluster with placement_info**
 yb-ctl start --placement_info "cloud1.region1.zone1,cloud2.region2.zone2,cloud3.reg
 
**Creating a cluster with custom_flags**
 yb-ctl start --master_flags "flag1=value,flag2=value,flag3=value" --tserver_flags "flag1=value,flag2=value,flag3=value"

**Destroying a cluster**
yb-ctl destroy

**Restart the cluster**
yb-ctl restart

**Wipe restart**
yb-ctl wipe_restart

**Destroying your local cluster and its data**
 yb-ctl destroy

**Add node**
yb-ctl add_node (--placement_info "cloud1.region1.zone1")

**Stopping node #X from your cluster**
yb-ctl remove_node <node_id>

**Start node**
yb-ctl start_node <node_id> (--placement_info "cloud1.region1.zone1")

**Stop node**
yb-ctl stop_node <node_id>

**Restart node**
yb-ctl restart_node <node_id>

**Comment by hengestone** [comment]
Is there a way to stop the whole cluster? I.e. `yb-ctl restart` without the `start` ?

**Comment by ayushsengupta1991** [comment]
Yups, sorry missed that. You can stop the cluster using `yb-ctl stop`

**Comment by hengestone** [comment]
Thanks!
