### ISSUE TITLE
[ysql] Support unique OID allocation in YB master for PostgreSQL

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#550]
https://stackoverflow.com/questions/5625585/sql-postgres-oids-what-are-they-and-why-are-they-useful

Need to understand the scope of uniqueness of the OIDs (per table or global).

**Comment by m-iancu** [comment]
Fixed by @robertpang in efd44a1 as part of issue https://github.com/YugaByte/yugabyte-db/issues/541.
