### ISSUE TITLE
UI to show a "Download root cert" button under /certificates

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5521]
We need a "Download root cert" button similar to the "Download" button at http://portal.dev.yugabyte.com/certificates that allows us to download the root cert.

It would also be good to clarify in the UI that the existing "Download" refers to "Download YSQL certificate" and the new "Download" would be a "Download root cert" or a "Download YCQL certificate".

This will use the /customers/:cUUID/certificates/:rUUID/download API that was added by @Arnav15

**Comment by streddy-yb** [comment]
@yb-andrew - can you back port this to 2.2?
