### ISSUE TITLE
Installing postgres extensions with shared libraries fails to find dependent shlibs

### ISSUE THREAD

**Issue by svarnau** [yugabyte/yugabyte-db#5529]
Due to linuxbrew installation on linux platform, dependent shared libraries are not picked up correctly.
Doc: https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis

Attempting to follow documented instructions for installing postgis does not work on Centos or Ubuntu, resulting in error:

ERROR:  could not load library "/home/user/yugabyte-2.2.2.0/postgres/lib/postgis-3.so": libgeos_c.so.1: cannot open shared object file: No such file or directory

Work-around involves copy all dependent libs and modifying rpaths.

**Comment by svarnau** [comment]
Script to work-around the issue:

```
#/bin/bash
# 
# Tested on Ubuntu18.04, Yugabyte-2.2.2.0
#  Your mileage may vary

# Must be postgres 11
pg_config="/usr/lib/postgresql/11/bin/pg_config"

if [[ ! -d "$1" ]]; then
  echo "Usage: $0 <yugabyte-install-directory>"
  exit 1
fi

YB="$1"
yb_pg_config="$YB/postgres/bin/pg_config"

cp  "$($pg_config --pkglibdir)"/*postgis*.so "$($yb_pg_config --pkglibdir)"/
cp  "$($pg_config --sharedir)"/extension/*postgis*.sql "$($yb_pg_config --sharedir)"/extension/
cp  "$($pg_config --sharedir)"/extension/*postgis*.control "$($yb_pg_config --sharedir)"/extension/

plib="$($yb_pg_config --pkglibdir)"
newlibs="$(ls $plib/*postgis*so)"
for lib in $newlibs
do
  $YB/bin/patchelf --set-rpath "$YB/lib/yb:$YB/lib/yb-thirdparty:$YB/linuxbrew/lib" $lib
  ldd $lib | awk '/=>/ {print $1,$3}' | while read file loc; do
    if [[ -z $(ls $YB/linuxbrew/lib/$file $YB/lib/yb/$file $YB/lib/yb-thirdparty/$file 2>/dev/null) ]]; then
      echo "Copying $file"
      cp $loc $YB/linuxbrew/lib/
      $YB/bin/patchelf --set-rpath "$YB/lib/yb:$YB/lib/yb-thirdparty:$YB/linuxbrew/lib" $YB/linuxbrew/lib/$file
    fi
 done
done

$YB/bin/ysqlsh -c "CREATE EXTENSION postgis";
```

**Comment by mbautin** [comment]
One way to avoid this would be to build a native YugabyteDB package without Linuxbrew (e.g. for Ubuntu 18.04 and CentOS 7). 
Another way would be to build PostGIS itself using Linuxbrew.

Long term we should move away from Linuxbrew and start using crosstools-ng (with gcc8) to generate cross-distribution packages (i.e. those that would work on many different Linux distributions) that use a native version of glibc. And we'll need to build a PostGIS package in the same way.
