### ISSUE TITLE
Remove stale instance configs after cloud provider is deleted

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5535]
After an onprem cloud-config is deleted we still retain the instance type that can't be deleted. It's misleading when a user is trying to create a universe and this stale entry will be presented as an option to choose as an instance type. 

Environment details
Version: 2.2.0.0
Cloud provider: On-prem non replicated
Steps to reproduce

1. Create an on-prem cloud provider with a single node
2. Add an instance type in the cloud provider config
3. Delete the cloud provider 
4. Create a new cloud provider 
5. Goto instance types you will notice the instance type from point 2 shows up in the new cloud provider

**Comment by jaydeepkumara** [comment]
PR:- https://github.com/yugabyte/yugabyte-db/pull/6975

**Comment by jaydeepkumara** [comment]
Checked with arnav. 
Currently, we are mapping using provider code to an instance type. For multiple customers that will be an issue as if one customer deletes a provider it will delete an instance for the other. To fix an issue we found 2 things.
1. Delete instance type only if there is no other provider with the same provider code.
2. Make a change to UI to filter instance type created by that customer.

**Comment by jaydeepkumara** [comment]
MArk ticket to open again to make above chnages

**Comment by chirag-yb** [comment]
@jaydeepkumara @Arnav15 I am not sure I follow the update here - https://github.com/yugabyte/yugabyte-db/issues/5535#issuecomment-770729775

Are we suggesting that there is more work involved beyond your PR? Also, what do you mean by multiple customers?

**Comment by jaydeepkumara** [comment]
yes @chirag-yb.

The customer here means multiple logins.  currently, we are maping instance type with instance code. So 2 loin/customer can have shared instance type. in that case, it will create another problem. To avoid that he asked me to validate in the backend before deleting.  it will create another problem. and also need to implement a filter in the frontend to remove all instance types of the second customers. 
@Arnav15 can add details if required.

**Comment by nishantSharma459** [comment]
I think there's no need for front-end changes. I've already debugged this and the same has been communicated with @jaydeepkumara
