### ISSUE TITLE
[Platform] need a process for updating provision_instance.py in upgrades

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5539]
provision_instance.py is generated when the provider is configured. So, it may not be easy to update it during an upgrade. 

We need to do one of the following to make sure it has the correct content

1. Auto generate it in every upgrade
2. If auto generate is not possible, we need at least a manual way to generate it again without recreating the provider. But this will be difficult from a process perspective as it will be a manual task by the customer and we should avoid this only if #1 is not possible.

**Comment by streddy-yb** [comment]
Fixed it as part of #5929
