### ISSUE TITLE
[YSQL] initdb support for PostgreSQL -- create tables in YB

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#554]

**Comment by mbautin** [comment]
@m-iancu is creating a new script similar to `genbki.pl` that puts all index creation next to table creation so that all indexes are created before any of the data is inserted. Also adding some additional handling in the initdb code in YugaByte mode for this.

**Comment by mbautin** [comment]
For the initial version we are taking one of the unique indexes on system tables and using that as a primary key. Also ignoring non-unique indexes on system tables for now because that is a performance improvement only (will be handled later). Currently there are 12 non-unique indexes and 103 unique indexes (including primary keys) in PostgreSQL 10.4.

**Comment by m-iancu** [comment]
Closed by ca30a3a.
