### ISSUE TITLE
Universe disk usage is empty

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5548]
Environment 
On-premise non-replicated provider
Version: 2.2.2.1
Node exporter and Prometheus working fine with other node-level metrics
Data directory - /mnt/

Also, we seem to expect this mountpoint: "/mnt/.* in metrics.yml which is not guaranteed to be used by an onprem provider 

`  filters:
    saved_name: "node_filesystem_free|node_filesystem_size"
    mountpoint: "/mnt/.*
`

**Comment by streddy-yb** [comment]
Hi @daniel-yb - can you take a look at this one? Seems like this is broken on 2.3 as well. http://portal.dev.yugabyte.com/universes/ee6da918-1c6d-43a5-a32c-f1500ddd1e31.

**Comment by iSignal** [comment]
For onprem, the data dir could be on any partition / file system (in tje case above it was on the root volume itself), so the above query that Chirag pointed out does not work. 

I don't think there is an easy way to fix this. The most straightforward fix would be to export the disk usage percentage ourselves from the yb-tserver/yb-master processes using a [system call / utility like this]for the data directory (https://stackoverflow.com/questions/3992171/how-do-i-programmatically-get-the-free-disk-space-for-a-directory-in-linux).

A temporary fix could be to use the disk utilization output of the health check script. We could enhance the `df -h` query it performs to check for the data directory volume for onprem providers, and use the resulting query output per node to calculate the overall universe free % on YW, then export to Prometheus from YW at the universe level.

**Comment by iSignal** [comment]
@bmatican suggested that we query for all `node_filesystem_free|node_filesystem_size` metrics available for the node prefix and pick the one that is a longest prefix of the mount point specified in the onprem provider.

So if the mount point in the onprem provider is "/foo/bar" and we see a metric for "/foo", we pick that disk util metric, otherwise if the only prefix available is "/", we fall back to it.

**Comment by streddy-yb** [comment]
Hi @iSignal - can you backport to 2.2 branch?
