### ISSUE TITLE
Provisioning python script is missing for non passwordless sudo

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5550]
The onprem non-passwordless sudo installation is missing pre-provisioning python script for node provisioning

Steps to reproduce 
1. Add a new on-prem provider with passwordless sudo and air-gapped unchecked
2. Add a new instance 
At this point I should be getting a python script for provisioning a node 

It works fine if airgapped installation is checked.

**Comment by streddy-yb** [comment]
@WesleyW - can you back port this to 2.2?
