### ISSUE TITLE
Two node master-slave setup

### ISSUE THREAD

**Issue by rock59** [yugabyte/yugabyte-db#5555]
Is it possible and safe to combine RF=1 (used in single node setup) and 2DC options to deploy a classic two-node master-slave or master-master deployment similar to mysql master-slave in production ?

**Comment by kmuthukk** [comment]
This should be technically feasible.

And will source and target clusters remain single-node for ever, or you'll eventually need elasticity (to multiple nodes) on both sides. Without the need for scale, it is not clear if there's an advantage over just use traditional single-node RDBMS with async replication to another single-node RDBMS.

**Comment by rock59** [comment]
As YugabyteDB is a high-performance multi-model database server , a two-node master-slave deployment may be useful in situation which the load is not high and an admin needs to decrease costs by replacing multiple PostgreSQL and Cassandra and Redis servers with just two YBs

**Comment by ddorian** [comment]
This should be possible with xCluster & using `--durable_wal_write=true`
