### ISSUE TITLE
[Platform] Add alerts capability for backup tasks

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5556]
Add ability to configure alerts to be sent when backup tasks fail

**Comment by chirag-yb** [comment]
@daniel-yb Can you add a task link in the alert email template? It will make it easier to quickly navigate to the failed backup.

**Comment by tylarb** [comment]
@streddy-yb Can you please consider this issue for backport to 2.4.0? Thanks!
