### ISSUE TITLE
Set helm charts working dir to /mnt/disk0/cores

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5565]
In https://github.com/yugabyte/charts/commit/b49fb36a894ebfa753602fd11f2f4d2b1f2e4fe0, we changed the working dir of yb processes to /mnt/disk0. Let's set it to /mnt/disk0/cores instead.

Currently, the cores dir is created in a postStart hook, we need to change it to get created in an init container instead.

**Comment by bhavin192** [comment]
I have observed following behavior with Docker as container runtime in a Kubernetes cluster.
The directory specified in the workingDir field is created automatically, so we won't need initContainer in that case.

We should also test similar scenario with OpenShift once, as it uses different container runtime (CRI-O).
