### ISSUE TITLE
[Platform] provider created in airgap mode in older versions does not have the new airgap_mode flag set correctly on upgrade

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5566]
We added a new attribute in access_key config to say it is an airgap deployment. if you created the provider in an older version like 2.1.3, this will not be in the config. When we upgrade that yugaware to a later version we add this airgap_mode key with the value false to the config json in the access_key table. 

I doubt if anyone is still have providers created using airgap mode on older releases. This is not an issue if the provider is created using recent versions. 

Opening this ticket just for the record.

**Comment by streddy-yb** [comment]
This is only an issue for customers on 2.1.7 -or- older. No need to fix this for all practical purposes.
