### ISSUE TITLE
[ysql] dropping a database with existing tables raises error and leaves it in inconsistent state

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#557]
Reported by @ravimurthy.

Dropping a database with existing tables raises error (as expected). However it leaves the database in an inconsistent state, and no further operations are possible.

=======
$ ./bin/psql -p 5433 -U postgres

postgres=# create database foo;
CREATE DATABASE
postgres=# \c foo;
psql (10.3, server 10.4)
You are now connected to database "foo" as user "postgres".
foo=# create table bar (a int primary key);
CREATE TABLE

=======
$ ./bin/psql -p 5433 -U postgres

postgres=# drop database foo;
ERROR:  Invalid argument: Cannot delete namespace which has table: bar [id=2b5b9e78b1054b6da32a647206bcc8e1]: namespace {
  name: "foo"
}
database_type: YQL_DATABASE_PGSQL

postgres=# \c foo;
FATAL:  database "foo" does not exist
DETAIL:  The database subdirectory "base/24580" is missing.
Previous connection kept

**Comment by nocaway** [comment]
Duplicate with #717
