### ISSUE TITLE
[Platform] backup fails if --ysql_enable_auth is set to true

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#5571]
If you attempt to run a backup on a YSQL database, and `--ysql_enable_auth=true`, then the backup process will hang because a password is required for the ysql_dump command.

**Comment by tylarb** [comment]
One proposed solution:

We know the IP addresses of other nodes in universe. We should add these as auth trust in `pg_hba.conf` for connections from yugabyte user.

Something like

```
host   *     yugabyte     10.1.1.1/32   trust
host *    yugabyte     10.1.1.2/32   trust
host  *   yugabyte     10.1.1.3/32   trust
```

**Comment by tylarb** [comment]
should apply to entries in hostssl as well.

**Comment by chirag-yb** [comment]
@ajcaldera1 Could you capture your workaround in the feature description?

**Comment by ajcaldera1** [comment]
So ultimately we need to capture a user that has access to read/write/create/drop tables in a cluster running YSQL. This can be configured at the provider level in platform. We have two possible methods for authenticating this user against the database. 
Option 1:
Capture a user / password at the provider level for backup configuration in platform and copy this information to the database nodes during the backup / restore process similar to how we handle S3/GCS bucket credentials. This could be persisted as a `pgpass` format file that the utilities already understand. 
Option 2:
Capture a user (default yugabyte) at the provider level and create ysql_hba.conf entries in Platform that enable the captured user to be "trusted" to authenticate against the database to run utilities as that user only from the specific database nodes. So for each node in the universe, there should be 1-2 entries of the following type in the ysql_hba.conf file that gets created by passing `--ysql_hba_conf` GFlag:
```
host     ALL    backupuser     node-ip-addr/32      trust
hostssl ALL    backupuser    node-ip-addr/32      cert 
```
The second entry is necessary when SSL/TLS is enabled on that universe. This also means that the user-specfic certificate should be present in the user's home directory for authentication purposes. This option has the advantage of not needing to store / capture passwords.

**Comment by daniel-yb** [comment]
@ajcaldera1 I don't think option (2) will work based on:
`The first record with a matching connection type, client address, requested database, and user name is used to perform authentication. There is no "fall-through" or "backup": if one record is chosen and the authentication fails, subsequent records are not considered`
and the fact that the top two entries in the auto-generated hba file when ysql auth is enabled are:
`host all all 0.0.0.0/0 md5
host all all ::0/0 md5`

**Comment by ajcaldera1** [comment]
@daniel-yb - With `ysql_enable_auth` set to `true`, those entries will always appear at the top. @m-iancu has proposed moving the priority of these autogenerated entries to the bottom of the file rather than the beginning and allow `ysql_hba_conf` to supercede. If you turn off `ysql_enable_auth` and just use `ysql_hba_conf`, option (2) does succeed. IMHO, the more correct way to do this is with platform managing a "security profile" (read: hba_conf) for an instance and attaching it to a universe.

**Comment by ssung-yugabyte** [comment]
Never put "trust" in tcp/ip connection!   trust means "anyone from this tcp/ip connection" can connect without a password.  
If there is any bug that bufferoverflow to console. for example, httpd.   An intruder can do "psql -h 127.0.0.1 -U yugabyte" without password.

**Comment by ssung-yugabyte** [comment]
it is safe to add "local all all trust" as the first row in hba file. Local means local socket and only socket owner (yugabyte) can access it.

**Comment by VijiYB** [comment]
Followed the steps to verify

1. Created universe, ran ysql sample apps
2. Set the Gflags as mentioned in the doc:
ysql_enable_auth = true
ysql_hba_conf_csv= "local all all trust"
3. Created backup ==> worked fine
