### ISSUE TITLE
[docs] Test and document how to use channel binding and SCRAM-SHA-256-PLUS

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#5572]
Jira Link: [DB-1681](https://yugabyte.atlassian.net/browse/DB-1681)
Let's document how to use SCRAM-SHA-256-PLUS with "channel binding" — it appears to be supported in our postgres code (see https://github.com/yugabyte/yugabyte-db/search?q=SCRAM-SHA-256-PLUS&unscoped_q=SCRAM-SHA-256-PLUS). This method is preferred over the regular SCRAM-SHA-256 because it helps prevent man-in-the-middle (MITM) attacks. 

Let's test it and see if it works. Then let's document it. It should be a popular option.

Here are some sources of information:
- [Postgres 11 highlight - Channel Binding for SCRAM](https://paquier.xyz/postgresql-2/postgres-11-scram-channel-binding/) 
- See "channel_binding" section in the PostgreSQL 13 documentation on ["Database Connection Control Functions"](https://www.postgresql.org/docs/13/libpq-connect.html), where it states: "Channel binding is a method for the server to authenticate itself to the client. It is only **supported over SSL connections with PostgreSQL 11 or later** servers using the SCRAM authentication method."  Note that this is not documented in the PostgreSQL 11 docs! I did a search in our code for `channel_binding` and found it (see https://github.com/yugabyte/yugabyte-db/search?q=%22channel_binding%22&unscoped_q=%22channel_binding%22)

**Comment by ddorian** [comment]
Note that channel_binding is set from the client when connecting.
And if PostgreSQL supports it, then it's used.

**Comment by sushantrmishra** [comment]
**Scram authentication docs** 

https://docs.yugabyte.com/preview/secure/authentication/password-authentication/#scram-sha-256

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
