### ISSUE TITLE
Bump rocksdb_max_write_buffer_number default to 10

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#5580]
Jira Link: [DB-2080](https://yugabyte.atlassian.net/browse/DB-2080)
By default, this flag is set to 2, which means we only allow a max of 2 mem tables, one active and at most one pending flush. If another flush gets scheduled, you end up with 2 immutable mem tables and rocksdb stops writes. We've seen this in a couple of write heavy scenarios, but as a pretty rare event (couple of times a day, across all tablets)

Let's change the default to 10 in order to more aggressively avoid even rare stops to writes

**Comment by robertsami** [comment]
FYI @bmatican

**Comment by rthallamko3** [comment]
This has been addressed in https://github.com/yugabyte/yugabyte-db/issues/22571 by using total number of bytes pending flush as the mechanism to stall writes instead of fixed memtable count
