### ISSUE TITLE
[ysql] Secondary index support in PostgreSQL by following the CQL approach

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#559]
Indexes should be owned by YugaByte and not PostgreSQL.
We should generate alternative query plans using the indexes.

**Comment by robertpang** [comment]
Basic support for secondary index has been completed in commit [954a64b](https://github.com/YugaByte/yugabyte-db/commit/954a64b513f7a5713709c664093cb56848bb6369).
