### ISSUE TITLE
[Platform] Don't save YB_HOME_DIR as empty when creating onprem provider

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#5592]
1. Create an onprem provider from the UI without setting the home dir
2. Create a universe, creation should fail with an error similar to below during the instance configure step.

`
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Playbook with args ['ansible-playbook', '/home/sanketh/yugaware-src/devops/configure-cluster-server.yml', '--vault-password-file', '/opt/yugaware/keys/fe0edc20-9118-40ba-98ed-851dbb592a8f/sanketh-onprem-1-key.vault_password', '--private-key', '/opt/yugaware/keys/fe0edc20-9118-40ba-98ed-851dbb592a8f/sanketh-onprem-1-key.pem', '--user', 'yugabyte', '-i', u'10.150.0.92,', '-c', 'ssh', '--extra-vars', '{"master_rpc_port": "7100", "cql_proxy_rpc_port": "9042", "instance_search_pattern": "all", "public_ip": "10.150.0.92", "private_ip": "10.150.0.92", "yb_ansible_host": "10.150.0.92", "redis_proxy_rpc_port": "6379", "custom_ssh_port": "22", "cloud_type": "onprem", "encryption_key_dir": "yugabyte-encryption-files", "mount_points": "/opt/data", "master_http_port": "7000", "num_volumes": 9, "extra_gflags": {"undefok": "enable_ysql", "placement_uuid": "2c2053d8-1bf5-4842-b0a2-21f9436b110e", "callhome_collection_level": "medium", "metric_node_name": "yb-admin-sanketh-test-1-n1", "replication_factor": "1", "cluster_uuid": "f29226e5-0e7d-48bc-95b2-e7b6c7a224d8", "pgsql_proxy_bind_address": "10.150.0.92:5433", "enable_ysql": "true"}, "ssh_user": "yugabyte", "cloud_zone": "z3", "cert_valid_duration": 365, "disk_iops": 1000, "user_name": "yugabyte", "master_addresses_for_tserver": "10.150.0.92:7100", "org_name": "example.com", "server_type": "cluster-server", "ssd_size_gb": 100, "yb_home_dir": "", "tserver_http_port": "9000", "placement_cloud": "onprem", "placement_zone": "z3", "certs_node_dir": "yugabyte-tls-config", "vars_file": "/opt/yugaware/keys/fe0edc20-9118-40ba-98ed-851dbb592a8f/sanketh-onprem-1-key.vault", "ansible_port": 22, "placement_region": "us-west1", "package": "/opt/yugabyte/releases/2.2.1.0-b8/yugabyte-2.2.1.0-b8-centos-x86_64.tar.gz", "yb_server_ssh_user": "yugabyte", "instance_name": "yb-admin-sanketh-test-1-n1", "instance_type": "n2-gcp", "tserver_rpc_port": "9100", "master_addresses_for_master": "10.150.0.92:7100", "cloud_region": "us-west1"}'] failed with return code 2 and error fatal: [10.150.0.92] FAILED! => {"changed": false, "failed": true, "msg": "There was an issue creating /master as requested: [Errno 13] Permission denied: '/master'", "path": "/master/conf", "state": "absent"}
`

-------------
original:

When whitespace is entered into the `Desired Home Directory` field while creating an onprem provider, the UI will send an empty string to the API and set `YB_HOME_DIR=""`. There should be some checks in `managed/devops` and in the Java layer to prevent this from happening.

**Comment by iSignal** [comment]
I am able to repro this without any whitespace in the home dir field. It looks like this may have changed after 42cc19e4f7341e33cc0ee7e32c923c2717ff01ef when the UI started sending YB_HOME_DIR to empty. Setting YB_HOME_DIR to an empty string doesn't play with some of the downstream API code.

I have some fixes to the downstream API code but it would be good to also have the UI not send empty configs.

@daniel-yb @sshev
