### ISSUE TITLE
'COPY FROM' command doesn't work if the target attribute is of counter type...

### ISSUE THREAD

**Issue by praneeth-nimmagadda** [YugaByte/yugabyte-db#56]
![image](https://user-images.githubusercontent.com/8910583/36298109-672a34ee-131c-11e8-942f-8f049573f5f6.png)

So , COPY from command is not working in case the attributes in the table are of type 'counter'.
The same issue has been fixed in cassandra in the following link...

[CASSANDRA-9043](https://issues.apache.org/jira/browse/CASSANDRA-9043)

**Comment by praneeth-nimmagadda** [comment]
Team,

Can you please fix this as soon as possible, as we need this to be worked..

**Comment by robertpang** [comment]
@praneeth-nimmagadda Thank you for reporting this issue. There is an issue in our `system_schema.columns` system table where a counter column's datatype is reported as `bigint` instead of `counter`. A fix is under review and should be committed very soon.

**Comment by robertpang** [comment]
The fix has been committed as [9546e7e](https://github.com/YugaByte/yugabyte-db/commit/9546e7ec77d53cff8603b4de406d3b25f7d9f675).

**Comment by kmuthukk** [comment]
@praneeth-nimmagadda : The fix has landed. Will keep you posted when we have the new builds available to download. Were you needing a Mac or Linux build?

**Comment by kmuthukk** [comment]
Hi @praneeth-nimmagadda 

For Mac, you can now download 0.9.5:

```
$ wget https://downloads.yugabyte.com/yugabyte-ce-0.9.5.0-darwin.tar.gz
$ tar xvfz yugabyte-ce-0.9.5.0-darwin.tar.gz
$ cd yugabyte-0.9.5.0/
```

And rest of the steps to create local cluster are as usual. Just go to the macOS tab here:
https://docs.yugabyte.com/quick-start/create-local-cluster/

Sample table:
```
CREATE KEYSPACE IF NOT EXISTS app;
USE app;

drop table if exists counter_table;
create table counter_table (id int, counter1 counter, PRIMARY KEY (id));
```

Sample input file 'counter_data.txt':

```
id, counter1

1, 1

2, 2

3, 3
```

Load:

```
[cqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cqlsh> use app;
cqlsh:app> describe counter_table;

CREATE TABLE app.counter_table (
    id int PRIMARY KEY,
    counter1 counter
) WITH default_time_to_live = 0;

cqlsh:app> copy counter_table from '/Users/kannan/notes/counter_data.txt' with HEADER=TRUE;
Using 7 child processes

Starting copy of app.counter_table with columns [id, counter1].
Processed: 3 rows; Rate:       5 rows/s; Avg. rate:       7 rows/s
3 rows imported from 1 files in 0.413 seconds (0 skipped).
cqlsh:app> select * from counter_table;

 id | counter1
----+----------
  1 |        1
  2 |        2
  3 |        3
```

**Comment by praneeth-nimmagadda** [comment]
@robertpang  @kmuthukk

Thanks for the quick fix in MAC, but can we have this fixed in linux build as well, so that I need not worry about having that executed in a linux as well...

I might have my YB installed in a docker which is of linux...

**Comment by kmuthukk** [comment]
@praneeth-nimmagadda 

The linux 0.9.5 is also available via:

% wget https://downloads.yugabyte.com/yugabyte-ce-0.9.4.0-linux.tar.gz

And updated versions for docker have also been pushed.

**Comment by kmuthukk** [comment]
@praneeth-nimmagadda 

Please note that we still have one restriction that if the bulk imported file has duplicates for the same PRIMARY KEY, we don't support that in batch requests. Does your input CSV file have duplicate rows for the same primary key, and you expect the bulk load to increment the counters.

If we can a pre-aggregated CSV file where we group by the primary key and have the preaggregated sums, then the load will be much faster as well.

**Comment by nickhristov** [comment]
@kmuthukk this restriction is fine, we can aggregate things at the file level without a problem.

**Comment by kmuthukk** [comment]
Thanks @nickhristov .
