### ISSUE TITLE
[ysql] Handle INSERT of a duplicate row in PostgreSQL's specific DocOperation

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#561]
Also a failure of an INSERT that is part of a transaction should cause the transaction to fail.

**Comment by nocaway** [comment]
This has been fixed by @m-iancu . Reassign to him just in case he needs to comment on it.

**Comment by m-iancu** [comment]
Fixed in 1288bcf97568b302ba8a1eb187efd13f3ea095a1.
