### ISSUE TITLE
[docdb] org.yb.cql.TestYbBackup still failing on mac

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5610]
Jira Link: [DB-1545](https://yugabyte.atlassian.net/browse/DB-1545)

**Comment by bmatican** [comment]
I've temporarily disabled both the cpp and java ones, for mac

**Comment by OlegLoginov** [comment]
It's a duplicate of:  https://github.com/yugabyte/yugabyte-db/issues/4924

**Comment by OlegLoginov** [comment]
Closing as a duplicate of https://github.com/yugabyte/yugabyte-db/issues/4924
