### ISSUE TITLE
[Platform] backup script needs to preserve attributes on copy from prometheus snapshot

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#5612]
When copying the snapshot from the prometheus directory -- we should maintain file attributes (such as permissions/ownership). Add `-a` option to the cp command to do this.

**Comment by streddy-yb** [comment]
Change: 
sudo cp -R $PROMETHEUS_DATA_DIR/snapshots/$snapshot_dir $data_dir/prometheus_snapshot 
TO: 
sudo cp -aR $PROMETHEUS_DATA_DIR/snapshots/$snapshot_dir $data_dir/prometheus_snapshot
