### ISSUE TITLE
Consolidate xDC Metrics Graph into Per Cluster

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#5613]
Currently, we show one line per tserver on the xDC metrics graph in platform, which can make the graph unreadable if there are many tservers. Consolidate all the tservers into one per-cluster max.

**Comment by nspiegelberg** [comment]
For consolidation, I think you'll want a combination of avg+max to show both the general state of the cluster and the deviation from a misbehaving node.
