### ISSUE TITLE
[platform] [bare-metal] yb-platform-backup.sh fails if /opt/yugabyte/release directory does not exist

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5615]
platform.conf has a directory reference to /opt/yugabyte/release. yb-platform-backup.sh fails if this directory doesn't exist. The script should be changed to create this directory if it doesn't exist.

**Comment by chirag-yb** [comment]
@WesleyW We should also factor in the use case of deleting /opt/yugabyte directory between deployments, removing all subdirectories, and in that case, there is nothing forcing it to recreate the /opt/yugabyte/release directory.
