### ISSUE TITLE
[docs] incorrect grammar diagram for SET TRANSACTION

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5617]
https://docs.yugabyte.com/latest/api/ysql/commands/txn_set/

incorrectly shows the grammar for SET SESSION / SET LOCAL

<img width="950" alt="Screen Shot 2020-09-08 at 1 22 23 PM" src="https://user-images.githubusercontent.com/13615376/92524320-c2b29400-f1d6-11ea-9694-0639cc7251b8.png">

**Comment by stevebang** [comment]
We need a new page, including a separate page for the SET statement (which we have the grammar files for) and another one for SET TRANSACTION, which we need grammar files to be generated for.
