### ISSUE TITLE
[docs] incorrect usage of REPEATABLE_READ 

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5618]
Please double check this, but I think

1. REPEATABLE_READ on this page https://docs.yugabyte.com/latest/api/ysql/commands/txn_set/  should be REPEATABLE READ (no underscore).

Similarly:

2. READ_COMMITTED --> READ COMMITTED
3. READ_UNCOMMITTED -> READ UNCOMMITTED

Also, fix a few occurrences of:

4. REPEATABLE READS to REPEATABLE READ  (not plural).

5. Please also check page: https://docs.yugabyte.com/latest/api/ysql/commands/txn_begin/ for similar issues.

**Comment by stevebang** [comment]
Closing — fixed. Thanks for catching those — I fixed all occurrences that I could find last night. Searched all of the docs just in case.
