### ISSUE TITLE
[yugaware] [azure] Support regions with no availability zones

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5628]
In regions like "WestUS" where Azure does not have multiple AZs, we currently don't allow the creation of Yugabyte universes. We could introduce a dummy AZ "westus-0" in such cases to still allow the specification of vnet/subnet in such cases so that we can create a universe in the single AZ in this region.

#5623

**Comment by chirag-yb** [comment]
@jitendra-12113 Should this be closed?
