### ISSUE TITLE
[docdb] metrics and admin UI not consistent with respect to rocksdb_total_sst_file_size metric

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5640]
[Issue was reported by[ community slack channel](www.yugabyte.com/slack ).] 

> I have a question about the metric exposed as rocksdb_total_sst_file_size .  What is reported by this metric seems to be significantly less than if I sum the Total SST Files Size  column in that master admin UI.  The latter actually seems to be representative of disk usage.  Could someone tell me the difference between these two?

Upon further investigation there seems to be a metrics consistency issue. There is a discrepancy in what yb-master/yb-tserver UI shows in terms of SST sizes vs. what the `yb-tserver-ip:9000/metrics` handler shows.

I was able to see reported behavior on our internal test clusters too. This is how far I got:

1. For example, if you take tablets UI view in the yb-tserver UI view, the numbers look right.

http://yb-tserver-ip:9000/tablets

And look for tablets for this table: 000030a7000030008000000000004000 (sqlsecondaryindex), we can see that there are 24 tablets each with about 166MB size in compressed SSTables. 

For example, the entry for each of the 24 tablets of this table on this yb-tserver looks like. 

<img width="246" alt="Screen Shot 2020-09-09 at 8 01 19 PM" src="https://user-images.githubusercontent.com/13615376/92679621-c977fe80-f2dd-11ea-9985-542bf9932ca7.png">

So expected size is 24*160MB = 3.84GB

And that matches with the table level summary in this view for the same table (`sqlsecondaryindex`):
 http://yb-tserver:9000/tables  

<img width="216" alt="Screen Shot 2020-09-09 at 8 03 38 PM" src="https://user-images.githubusercontent.com/13615376/92679664-f2988f00-f2dd-11ea-85a4-b8e9b43ab43b.png">

2. However, if you look for that table metrics in `/prometheus-metrics` handler:

```
$ curl -s http://172.151.49.1:9000/prometheus-metrics | grep -i rocksdb_total_sst_file_size | grep -w sqlsecondaryindex
rocksdb_total_sst_file_size{exported_instance="yb-1-rao-test-223-n1",metric_type="tablet",table_name="sqlsecondaryindex",table_id="000030a7000030008000000000004000"} 1049324161 1599704547068
```

We see it is only reported as 1.04GB.

Since `/prometheus-metrics` handler rolls up all tablets at a per-table basis, if we instead look at the `/metrics` handler where we track at tablet level, most of the tablets show 0 and only some show something like 174940396 (which is ~166MB). And these do add up to the above 1.04GB or so.
```
$ curl -s http://172.151.49.1:9000/metrics | grep -i -E "(table_name|rocksdb_total_sst_file_size)" -A1 | grep -w sqlsecondaryindex -A4 | grep -E "(value)"
                "value": 174940396
                "value": 175205547
                "value": 66492
                "value": 0
                "value": 0
                "value": 0
                "value": 0
                "value": 0
                "value": 174932320
                "value": 0
                "value": 0
                "value": 175421215
                "value": 0
                "value": 0
                "value": 0
                "value": 174323387
                "value": 174368312
                "value": 0
                "value": 0
                "value": 0
                "value": 0
                "value": 0
                "value": 0
                "value": 66492
```

*So question is why does the metric for many tablets get reported as 0?*

**Comment by amitanandaiyer** [comment]
Both code paths eventually seem to call down to `GetCurrentVersionSstFilesSize` to calculate the size. 

/tablets page seems to call this on demand, whenever the page is requested.

/metrics picks up the value from the metric/key when the page is requested.

The metric value seems to be set in 
```
void DBImpl::SetSSTFileTickers() {
  if (stats_) {
    auto sst_files_size = GetCurrentVersionSstFilesSize();
    SetTickerCount(stats_, CURRENT_VERSION_SST_FILES_SIZE, sst_files_size);
    auto uncompressed_sst_files_size = GetCurrentVersionSstFilesUncompressedSize();
    SetTickerCount(
        stats_, CURRENT_VERSION_SST_FILES_UNCOMPRESSED_SIZE, uncompressed_sst_files_size);
    auto num_sst_files = GetCurrentVersionNumSSTFiles();
    SetTickerCount(stats_, CURRENT_VERSION_NUM_SST_FILES, num_sst_files);
  }
}
```
which gets called after a flush/compaction.


Initial comparion seems to suggest that non-zero values correspond to recently compacted tablets. And zero values correspond to flushed tablets. 

Trying to repro this with some added debug logs.

**Comment by amitanandaiyer** [comment]
Tablet::rocksdb_statistics_ seems to be used by both  the regular DB and the intentsDB.

When the regular DB sets CURRENT_VERSION_SST_FILES_SIZE, it seems to set the value correctly.
However intents DB sets the same metric to 0 because it is typically empty.

The /tablets page seems to compute the value directly based on the RegularDB so it is returning the correct value.

Ideally it seems like we may want to have different statistics objects for regular vs intents db. Surprised to see that this is coming up only now. Will look in to see if this is a  recent regression.

**Comment by kmuthukk** [comment]
good debugging @amitanandaiyer !

**Comment by amitanandaiyer** [comment]
Looks like we've had this forever.

Thanks to D8690 we are now able to detect that the metric exposed was inaccurate.

**Comment by bmatican** [comment]
Ha! That's awesome! Thanks @amitanandaiyer and by extension, also @emhna :)
