### ISSUE TITLE
YB looks for node.0.0.0.0.crt when TLS is enabled and rpc_bind_addresses is 0.0.0.0

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-db#5641]
In the Helm chart I'm setting the `--rpc_bind_addresses` to `0.0.0.0:7100` and the `--server_broadcast_addresses` is set to `yb-master-0.yb-masters.yb-chart.svc.cluster.local:7100` for yb-master pods.

When TLS is enabled it adds following flags as well,

```
--certs_dir=/opt/certs/yugabyte
--use_node_to_node_encryption=true
--allow_insecure_connections=false
--use_client_to_server_encryption=true"
--certs_for_client_dir=/opt/certs/yugabyte
```

The contents of `/opt/certs/yugabyte` are as follows, these files are generated by the chart and mounted in all the pods.

```
node.yb-master-0.yb-masters.yb-demo.svc.cluster.local.crt
node.yb-master-0.yb-masters.yb-demo.svc.cluster.local.key
node.yb-master-1.yb-masters.yb-demo.svc.cluster.local.crt
node.yb-master-1.yb-masters.yb-demo.svc.cluster.local.key
node.yb-master-2.yb-masters.yb-demo.svc.cluster.local.crt
node.yb-master-2.yb-masters.yb-demo.svc.cluster.local.key
ca.crt:                                                  
```

But the yb-master pods (yb-tserver as well) fail to start with errors similar to this,

```
F20200907 07:20:09 ../../src/yb/master/master_main.cc:116] 
Not found (yb/util/env_posix.cc:1469): 
/opt/certs/yugabyte/node.0.0.0.0.key: 
No such file or directory (system error 2)
```

I think it looks for the file names which has the IP / hostname given in `--rpc_bind_addresses`? I believe it should look for the files which have the `--server_broadcast_addresses` in their names. May be this can be a fallback lookup if files with `--rpc_bind_addresses` in their names are not present?

**Comment by bhavin192** [comment]
Similar issue happens with yb-tserver when we have `--cql_proxy_bind_address` set to `0.0.0.0:9042`. 
```
F20200911 13:07:16 ../../src/yb/tserver/tablet_server_main.cc:268] Not found (yb/util/env_posix.cc:1469): /opt/certs/yugabyte/node.0.0.0.0.key: No such file or directory (system error 2)
```
References: https://github.com/yugabyte/yugabyte-db/blob/34d2bc3f5cce3a305cf371f222877c6a02394ee5/src/yb/tserver/tablet_server_main.cc#L266
https://github.com/yugabyte/yugabyte-db/blob/34d2bc3f5cce3a305cf371f222877c6a02394ee5/ent/src/yb/tserver/factory.h#L54-L56

**Comment by iSignal** [comment]
Related: #3829 

Like mentioned in that issue, we should add gflags to customize the location of ca cert (`--ca_certs="/path1.crt,/path2.crt"`), node cert (`--node_cert=/path/to/node.crt`), node key(`--node_key=path/to/node.key`). Changing the default naming convention right now will likely break a bunch of things, so we should start by offering gflags.

**Comment by bmatican** [comment]
Discussed offline with Sergei, we can start with just 1 custom flag for the node ip portion of the filenames and have a hierarchy of what to put there, eg
- if this new flag is set, use it
- else if server broadcast address is set, use that
- else use the rpc bind address

cc @hulien22 @iSignal

**Comment by bmatican** [comment]
@hulien22 added `cert_node_filename` to be able to customize the IP section of the filename

@iSignal passing this back to you, for changing the respective helm chart

**Comment by bhavin192** [comment]
Thank you @bmatican (I can see this change is part of 2.3.3), will make changes to the Helm chart, we are tracking it here: https://github.com/yugabyte/yugabyte-db/issues/6125

**Comment by bhavin192** [comment]
Hey @hulien22 while making changes to Helm chart I'm getting the following error from yb-tserver.

```
2020-11-19 12:42:22.523 UTC [26671] FATAL:  could not load server certificate file "/tmp/certs/yugabyte/node.0.0.0.0.crt": No such file or directory
```

The flags passed to yb-tserver (2.3.3.0) in this case look like this (I have removed the unrelated flags from the output),

```
/home/yugabyte/bin/yb-tserver
 --rpc_bind_addresses=0.0.0.0:9100
 --server_broadcast_addresses=yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local:9100
 --cql_proxy_bind_address=0.0.0.0:9042
 --cql_proxy_broadcast_rpc_address=yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local:9042
 --webserver_interface=0.0.0.0
 --enable_ysql=true
 --pgsql_proxy_bind_address=0.0.0.0:5433
 --certs_dir=/opt/certs/yugabyte
 --cert_node_filename=yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local
 --use_node_to_node_encryption=true
 --allow_insecure_connections=false
 --use_client_to_server_encryption=true
 --certs_for_client_dir=/opt/certs/yugabyte
```

Tried playing around yb-tserver binary from 2.5.0.0,

```console
$ ./bin/yb-tserver \
  --fs_data_dirs=/tmp/test \
  --rpc_bind_addresses=0.0.0.0:9100 \
  --master_addresses=127.0.0.1:7100 \
  --certs_dir=/tmp/certs/yugabyte \
  --use_node_to_node_encryption=false \
  --allow_insecure_connections=false \
  --use_client_to_server_encryption=true \
  --certs_for_client_dir=/tmp/certs/yugabyte \
  --server_broadcast_addresses=127.0.0.2:9100 \
  --cert_node_filename=my_node \
  --enable_ysql=true

2020-11-19 12:42:21.546 UTC [26631] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2020-11-19 12:42:21.547 UTC [26631] FATAL:  could not load server certificate file "/tmp/certs/yugabyte/node.0.0.0.0.crt": No such file or directory
2020-11-19 12:42:21.548 UTC [26631] LOG:  database system is shut down
2020-11-19 12:42:21.633 UTC [26661] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2020-11-19 12:42:21.634 UTC [26661] FATAL:  could not load server certificate file "/tmp/certs/yugabyte/node.0.0.0.0.crt": No such file or directory
2020-11-19 12:42:21.634 UTC [26661] LOG:  database system is shut down
…
```

Actually the error should be `node.my_node.crt` file not found.

With `--enable_ysql=false` that error is not shown.

Grepping over the source code I found this section, <https://github.com/yugabyte/yugabyte-db/blob/4fab62e13239228eda1457f31ccc0c80692d0581/src/postgres/src/backend/libpq/be-secure-openssl.c#L143-L150> At least from the error message I guess that's where the error is coming from.

Also, should it be kClientToServer instead of kServerToServer here <https://github.com/yugabyte/yugabyte-db/blob/4fab62e13239228eda1457f31ccc0c80692d0581/ent/src/yb/tserver/factory.h#L60>

**Comment by hulien22** [comment]
> Also, should it be kClientToServer instead of kServerToServer here?

Ah @bhavin192 good catch, that is correct - I'll fix that
