### ISSUE TITLE
Online change replication factor

### ISSUE THREAD

**Issue by ricemaster** [yugabyte/yugabyte-db#5642]
Is that OK to make a online change for replication factor?

I'm looking at the command `yb-admin modify_placement_info <modify_placement_info> <replication_factor>`, and wondering if it's OK to change replication factor from 3 to 500.

Let's say I have a 6-node universe, 3 masters and 6 tservers, with replication factor `3`. 

- What's happening when I execute `yb-admin modify_placement_info <modify_placement_info> 500`?
- With which command, I can get a prove that the data have 500 replications?

Thanks.

**Comment by ddorian** [comment]
Hi @ricemaster 

Currently it's not possible to change the replication factor in an existing cluster.

> With which command, I can get a prove that the data have 500 replications?
It doesn't make sense to have more RF then the number of nodes.

**Comment by ricemaster** [comment]
Hi @ddorian , thank you for always answering so quickly.

I did executed this command `./bin/yb-admin -master_addresses 10.211.55.101:7100,10.211.55.102:7100,10.211.55.103:7100 modify_placement_info cloud1.datacenter1.rack1 500` to increase RF from 3 to 500, in a universe with 3 master and 7 tserver. 

And I found data size increased about 2.3 times.

It seems that even thought RF has been increased up to 500, the actual RF value maybe is 7 now, equals with the max number of tservers. But it'll always show `num_replicas: 500` as a result of executing `./bin/yb-admin get_universe_config`.

BEFORE:
<img width="1307" alt="截屏2020-09-10 19 43 29" src="https://user-images.githubusercontent.com/10449002/92725428-b9742380-f39e-11ea-9f2e-8e7f8b78cf1f.png">

AFTER:
<img width="1411" alt="截屏2020-09-10 19 43 59" src="https://user-images.githubusercontent.com/10449002/92725459-c6911280-f39e-11ea-846f-c693b41ce55b.png">
<img width="1299" alt="截屏2020-09-10 19 44 47" src="https://user-images.githubusercontent.com/10449002/92725596-f0e2d000-f39e-11ea-88a7-f38619184548.png">

So if it's not possible to change the replication factor in an existing cluster, why the data size increased?
And how can I know the real current RF value?

**Comment by ddorian** [comment]
Hi @ricemaster 

For now, changing the RF is possible, but it's not tested and thus not yet recommended.

Note that RF doesn't make sense to be larger than the total number of yb-tservers.

In your case, because total number is 7, the data increased by 2.3x. 
2.3x * 3x(previous RF) == 7x 

For RF 500, you'd need at minimum 500 nodes. 
Writing transactions would require writes on at least 251! nodes.
And it's not an odd number.

**Comment by ricemaster** [comment]
@ddorian So changing RF online will be one of the official features in yb someday, and the RF should always be an odd number and not larger than tserver. Understood.

Actually, I'm still wondering if the number of yb-master should be also changed to keep as same as RF when we change RF value. But I think I should put it aside for now and close this issue.

YugabyteDB is amazing, thanks for your help and patience.

**Comment by ddorian** [comment]
> Actually, I'm still wondering if the number of yb-master should be also changed to keep as same as RF when we change RF value.

Yes, number of yb-masters should be the same as RF: https://docs.yugabyte.com/latest/deploy/checklist/#replication

**Comment by ricemaster** [comment]
> > Actually, I'm still wondering if the number of yb-master should be also changed to keep as same as RF when we change RF value.
> 
> Yes, number of yb-masters should be the same as RF: https://docs.yugabyte.com/latest/deploy/checklist/#replication

If I added new masters into the universe (https://docs.yugabyte.com/latest/manage/change-cluster-config/#5-master-quorum-change), do I have to change RF as well?

**Comment by ddorian** [comment]
> If I added new masters into the universe (https://docs.yugabyte.com/latest/manage/change-cluster-config/#5-master-quorum-change), do I have to change RF as well?

It works in reverse. Only add a new master if you increase the RF.

**Comment by ddorian** [comment]
@ricemaster can you subscribe to https://github.com/yugabyte/yugabyte-db/issues/1191 to track support for changing the replication factor ?

**Comment by ricemaster** [comment]
> @ricemaster can you subscribe to #1191 to track support for changing the replication factor ?

Sure, subscribed. Sorry for the late reply...
