### ISSUE TITLE
[YSQL] UPDATE support in PostgreSQL

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#565]

**Comment by nocaway** [comment]
YugaByte's approach on UPDATE support.

Conceptually, PostgreSQL query plan breaks an UPDATE into the following steps.
UPDATE a_table SET a_col = a_new_value WHERE update_cond

Step 1- SELECT tuple_ID, non_updated_columns FROM a_table WHERE update_cond
Step 2- Modify selected tuple to construct
    a_new_tuple =
    { tuple_ID, selected_non_updated_columns, new_values_for_updated_columns }
Step 3- DELETE FROM a_table WHERE tuple_ID = ?
Step 4- INSERT a_new_tuple INTO a_table

To support the above query plan, we introduce a new system column in YugaByte, YBCTID.
- During step 1, YugaByte returns YBCTID
- During step 2, YugaByte appends new values for updated columns.
- Step 3 and 4 are combined into one operations. YugaByte would use YBCTIDs and new values of updated columns to operate on associated rows.

NOTE:
- As of 01/01/2019 Currently YugaByte does not allow updating PRIMARY KEY columns. See issue #659 
- YBCTID column is of datatype BYTEA (binary). Currently, it contains the KEY that identifies one row. For future consideration: We might optimize our UPDATE execution by returning a YBCTID key that identifies a SET of ROWS for multi-row BULK UPDATE.

**Comment by nocaway** [comment]
This issue has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/7daa262f02481d4801569e5955f5693dfa81cae5
