### ISSUE TITLE
[Platform] YW node is designating a node as master when restarting a non-master node if no master is available in that AZ

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5655]
Let's say we have a 9 node 3 AZ universe. If we stop processes on all 3 nodes in an AZ and then start a node that was only a tserver, YW tries to make that node a master node and it fails. If you then start processes on the node that was the master node previously, it makes that node only a tserver node.

Starting the node that had master previously first , it does the right thing.

**Comment by streddy-yb** [comment]
Hi @iSignal - can you do an initial triage of this issue?

**Comment by iSignal** [comment]
I assume this was an onprem universe? If so, it should be fixed after https://github.com/yugabyte/yugabyte-db/commit/fcb36074b559e048086f127ed0ae87267a0931be

**Comment by streddy-yb** [comment]
Dup of #5739

**Comment by streddy-yb** [comment]
With the above fix, starting a t-server node when master is down starts both t-server and master on that node successfully. If customer wants to pin master to a specific node within an AZ, then that is not possible with the current behavior. We don't allow this level of placement customization even during universe creation, so the new behavior is acceptable.
