### ISSUE TITLE
[docdb] potential tcmalloc issue noticed on a heavily loaded cluster

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5659]
Jira Link: [DB-4754](https://yugabyte.atlassian.net/browse/DB-4754)

W0910 09:36:20.936823 70299 long_operation_tracker.cc:112] UpdateReplica running for 1.001s:
    @     0x7f42a668f11e  (unknown)
    @     0x7f42b100b24b  base::internal::SpinLockDelay()
    @     0x7f42b100b154  SpinLock::SlowLock()
    @     0x7f42ac201ff6  tcmalloc::CentralFreeList::Populate()
    @     0x7f42ac2020f6  tcmalloc::CentralFreeList::FetchFromOneSpansSafe()
    @     0x7f42ac202187  tcmalloc::CentralFreeList::RemoveRange()
    @     0x7f42ac205ae5  tcmalloc::ThreadCache::FetchFromCentralCache()
    @     0x7f42aff548df  rocksdb::Arena::AllocateNewBlock()
    @     0x7f42aff54a33  rocksdb::Arena::AllocateFallback()
    @     0x7f42afea6d58  rocksdb::ConcurrentArena::AllocateAligned()
    @     0x7f42afef7e39  rocksdb::(anonymous namespace)::SkipListRep<>::Allocate()
    @     0x7f42afea1807  rocksdb::MemTable::Add()
    @     0x7f42afeeced0  rocksdb::(anonymous namespace)::MemTableInserter::PutCF()
    @     0x7f42afeeae06  rocksdb::WriteBatch::Iterate()
    @     0x7f42afeedf68  rocksdb::WriteBatchInternal::InsertInto()
    @     0x7f42afe5db5a  rocksdb::DBImpl::WriteImpl()
W0910 09:36:20.999792 70299 long_operation_tracker.cc:112] UpdateReplica running for 1.001s:
    @     0x7f42a668f11e  (unknown)
    @     0x7f42b100b24b  base::internal::SpinLockDelay()
    @     0x7f42b100b154  SpinLock::SlowLock()
    @     0x7f42ac201ff6  tcmalloc::CentralFreeList::Populate()
    @     0x7f42ac2020f6  tcmalloc::CentralFreeList::FetchFromOneSpansSafe()
    @     0x7f42ac202187  tcmalloc::CentralFreeList::RemoveRange()
    @     0x7f42ac205ae5  tcmalloc::ThreadCache::FetchFromCentralCache()
    @     0x7f42aff548df  rocksdb::Arena::AllocateNewBlock()
    @     0x7f42aff54a33  rocksdb::Arena::AllocateFallback()
    @     0x7f42afea6d58  rocksdb::ConcurrentArena::AllocateAligned()
    @     0x7f42afef7e39  rocksdb::(anonymous namespace)::SkipListRep<>::Allocate()
    @     0x7f42afea1807  rocksdb::MemTable::Add()
    @     0x7f42afeeced0  rocksdb::(anonymous namespace)::MemTableInserter::PutCF()
    @     0x7f42afeeae06  rocksdb::WriteBatch::Iterate()
    @     0x7f42afeedf68  rocksdb::WriteBatchInternal::InsertInto()
    @     0x7f42afe5db5a  rocksdb::DBImpl::WriteImpl()
W0910 09:36:21.055544 70299 long_operation_tracker.cc:112] UpdateReplica running for 1.055s:
    @     0x7f42a668f11e  (unknown)
    @     0x7f42b100b24b  base::internal::SpinLockDelay()
    @     0x7f42b100b154  SpinLock::SlowLock()
    @     0x7f42ac201ff6  tcmalloc::CentralFreeList::Populate()
    @     0x7f42ac2020f6  tcmalloc::CentralFreeList::FetchFromOneSpansSafe()
    @     0x7f42ac202187  tcmalloc::CentralFreeList::RemoveRange()
    @     0x7f42ac205ae5  tcmalloc::ThreadCache::FetchFromCentralCache()
    @     0x7f42aff548df  rocksdb::Arena::AllocateNewBlock()
    @     0x7f42aff54a33  rocksdb::Arena::AllocateFallback()
    @     0x7f42afea6d58  rocksdb::ConcurrentArena::AllocateAligned()
    @     0x7f42afef7e39  rocksdb::(anonymous namespace)::SkipListRep<>::Allocate()
    @     0x7f42afea1807  rocksdb::MemTable::Add()
    @     0x7f42afeeced0  rocksdb::(anonymous namespace)::MemTableInserter::PutCF()
    @     0x7f42afeeae06  rocksdb::WriteBatch::Iterate()
    @     0x7f42afeedf68  rocksdb::WriteBatchInternal::InsertInto()
    @     0x7f42afe5db5a  rocksdb::DBImpl::WriteImpl()

**Comment by rthallamko3** [comment]
@rao-vasireddy , This is an old issue, am not sure if it is relevant anymore. Closing this for now. Feel free to reopen, If there are concrete repro steps or it happens on an LRU.
