### ISSUE TITLE
Allow configuring initial username and password via Helm values

### ISSUE THREAD

**Issue by RabidFire** [yugabyte/yugabyte-db#5663]
It would be good if the initial username and password are configurable via the Yugabyte Helm Chart. Other databases do it, allowing you to either configure a `password` value directly, or pass an `existingPasswordSecret`:
- https://hub.helm.sh/charts/bitnami/postgresql
- https://hub.helm.sh/charts/adwerx/faktory

The default username & password in values.yaml can be 'yugabyte' / 'yugabyte' to ensure backward compatibility as well.

**Comment by iSignal** [comment]
@RabidFire : thanks for the pointer to the postgresql helm chart. We will look into this.

**Comment by bhavin192** [comment]
Initial support for this was added by https://github.com/yugabyte/charts/pull/42
