### ISSUE TITLE
is ycql or yedis support udf ?

### ISSUE THREAD

**Issue by aricy** [yugabyte/yugabyte-db#5668]
Jira Link: [DB-4648](https://yugabyte.atlassian.net/browse/DB-4648)
we want to use yugabyte on my production environment. but i can't find any udf support.
In general how can we mange yugabyte cluster ?

**Comment by ddorian** [comment]
Hi @aricy 

Currently user defined functions are only supported in YSQL.

> In general how can we mange yugabyte cluster ?

Check our docs:
https://docs.yugabyte.com/latest/manage/
https://docs.yugabyte.com/latest/secure/
https://docs.yugabyte.com/latest/deploy/
https://docs.yugabyte.com/latest/troubleshoot/

**Comment by aricy** [comment]
how can i get cluster health monitor like prometheus?
and where is the configurations in yugabyte like ycql\yedis\gsql ?

**Comment by ddorian** [comment]
> how can i get cluster health monitor like prometheus?

https://docs.yugabyte.com/latest/explore/observability/linux/

>  and where is the configurations in yugabyte like ycql\yedis\gsql ?

https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/
https://docs.yugabyte.com/latest/reference/configuration/yb-master/
