### ISSUE TITLE
Support GiST and GIN Index types.

### ISSUE THREAD

**Issue by markusgod** [yugabyte/yugabyte-db#5670]
Support https://www.postgresql.org/docs/8.3/textsearch-indexes.html for json/jsonb indexing and full text search.
Or pass-through them to https://docs.yugabyte.com/latest/api/ysql/datatypes/type_json/create-indexes-check-constraints/
for better PostgreSQL compatibility like it is done in cockroach https://www.cockroachlabs.com/docs/v20.1/inverted-indexes

**Comment by ddorian** [comment]
Hi @markusgod 
This is a duplicate of https://github.com/yugabyte/yugabyte-db/issues/1337.
Can you comment on that issue ?
Closing as duplicate.
