### ISSUE TITLE
[ycql] Optimize updating non-indexed columns within indexed tables

### ISSUE THREAD

**Issue by danielmh0** [yugabyte/yugabyte-db#5678]
Updating a single non-indexed column on a CQL table with many indexes is similar in CPU/latency (>50%) to writing a brand new row with values for all indexed columns. Removing the index makes the update far cheaper. YB should be able to optimize updates where the row already exists and no indexed columns are being updated, confining the transaction to a single tablet.

@kmuthukk created a reproduction here: https://gist.github.com/kmuthukk/49595e9020f9f3604faa68814f8b2117 on a RF=1 local setup:

```
$ python ~/notes/ycql_non_index_update.py
Running test with 0 index(es)
Dropped (if exists): users table
Time: 1119.62199211 ms
====================
Created 0 indexes on table
Num Indexes=0: Rows=2000; Inserts/sec: 1819.71; Avg Latency (ms): 0.55
====================
Now update a non-indexed column (age)...
Num Indexes=0: Rows=2000; Updates/sec: 1865.51; Avg Latency (ms): 0.54
====================
Running test with 5 index(es)
Dropped (if exists): users table
Time: 1083.28294754 ms
====================
Created 5 indexes on table
Num Indexes=5: Rows=2000; Inserts/sec: 574.92; Avg Latency (ms): 1.74
====================
Now update a non-indexed column (age)...
Num Indexes=5: Rows=2000; Updates/sec: 560.33; Avg Latency (ms): 1.78
====================
```

The last row, one would expect the latency to be closer to 0.55ms (instead of 1.78ms) since only a non-indexed column ('age') is getting UPDATEd.

In this example with 5 indexes RF=1, the writes are ~3-4x more expensive because of indexing. With 13 indexes/RF=3, we've observed them become >20x more expensive.

**Comment by danielmh0** [comment]
Another feature which could fit in the same code change--

It'd be really nice to optimize UPDATES that explicitly set an indexed column to its current value (leave it unmodified).

So instead of:
  * If row already exists (looking only at primary tablet) and no indexed columns are set, skip updating indexes.
Something like:
  * If row already exists and all indexed columns in the UPDATE already have the values given in the UPDATE (again only looking at the primary tablet), skip updating indexes.

Our use case involves rewriting millions of these heavily indexed rows, most of which are unchanging.

**Comment by kmuthukk** [comment]
@danielmh0 - I forked the above comment into a separate issue because it requires reading of the old data (rather than just examining the schema) - and therefore is in a different part of the code. We'll work on that as a separate commit.

**Comment by danielmh0** [comment]
@kmuthukk sounds good. Unless I'm missing something, it seems like both versions require reading the old data, to see if a row already exists or not. (If a row doesn't exist, indexes need to be updated for all indexed columns, even values are implicitly NULL.)

**Comment by kmuthukk** [comment]
@danielmh0 -- you are correct (I had made an incorrect observation earlier). This change also needs re-reading of the data. So, #5802 should be addressed as part of the same commit.

**Comment by OlegLoginov** [comment]
Fixed by the commit above.
