### ISSUE TITLE
Update "What Features Does YSQL Support?"

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#5689]
Jira Link: [DB-1953](https://yugabyte.atlassian.net/browse/DB-1953)
The ["What Features Does YSQL Support?"](https://github.com/yugabyte/yugabyte-db/blob/master/architecture/YSQL-Features-Supported.md) page (linked to from "What is YugabyteDB" in the README) needs updating.

In the PostgreSQL Feature Support section, it says:

> Here are the features currently supported as of YugabyteDB v2.0, Jan 15 2020. This list also indicates what is planned for YugabyteDB v2.1 coming out around the beginning of February.

**Comment by sushantrmishra** [comment]
YSQL docs are listed in https://docs.yugabyte.com/preview/api/ysql/
