### ISSUE TITLE
Implement RPC timeout at DocDB layer

### ISSUE THREAD

**Issue by rahuldesirazu** [YugaByte/yugabyte-db#569]
Commands timeout at proxy layer within a few seconds, so we should introduce this timeout to the DocDB layer to prevent stray queries from running past expiry. The timeout should be API-specific to match proxy behavior.

**Comment by kmuthukk** [comment]
Yup - we need this!

**Comment by rahuldesirazu** [comment]
Fixed in 47cbf5ae4ef5d41b3198a76f1197253b93121e81, closing.
