### ISSUE TITLE
AWS Cloudformation - Update to allow local SSD types - c5d.2xlarge, etc

### ISSUE THREAD

**Issue by robly** [yugabyte/yugabyte-db#5695]
The old i3 yml doesn't work. https://github.com/yugabyte/aws-cloudformation/blob/master/yugabyte_cloudformation_i3_example.yaml

We tried taking the mounting instructions from the i3 template and adding it to the more recent c5.xlarge template - https://github.com/yugabyte/aws-cloudformation/blob/master/yugabyte_cloudformation.yaml but that didn't work either.

Ideally we use c5d.xlarge (2xlarge, etc) since the local SSD is much more performant then the EBS.

Thanks

**Comment by bhavin192** [comment]
Hey @robly can you please try out this CloudFormation template, https://github.com/yugabyte/aws-cloudformation/blob/master/yugabyte_ephemeral_nvme_cloudformation.yaml ? This should work for your case.
