### ISSUE TITLE
document yb-admin set_preferred_zones command to set preferred AZ/region(s)

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#571]
In [this section](https://docs.yugabyte.com/latest/deploy/public-clouds/aws/#7-configure-az-region-aware-placement), we document the `yb-admin` command (`modify_placement_info`) for setting the desired replica placement. 

We should also document the `yb-admin` option (`set_preferred_zones`) for setting the "preferred" AZ/region.  

Note: We use this as hint to place tablet leaders. When the "preferred" AZ/region(s)" nodes are alive/healthy - the leaders of tablets are placed on nodes in those zones/regions. By default, all nodes are eligible to have tablet leaders.

**Comment by ddorian** [comment]
see https://github.com/yugabyte/yugabyte-db/pull/2658

**Comment by kmuthukk** [comment]
Let's close the issue only after PR is merged.

**Comment by stevebang** [comment]
@kmuthukk Your note has been added to the section on the `set_preferred_zones` command in the new `yb-admin` page.  See: https://docs.yugabyte.com/latest/admin/yb-admin/#set-preferred-zones

**Comment by ddorian** [comment]
merged https://github.com/yugabyte/yugabyte-db/pull/2658

**Comment by ddorian** [comment]
Latest commit from latest comments: 
https://github.com/yugabyte/yugabyte-db/pull/2844
https://github.com/yugabyte/yugabyte-db/pull/2844/commits/f079ca761cc6668dad974a9155b3a4ea7203cd69
