### ISSUE TITLE
Rename `In Use` Column  on the Manage Instances page

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5713]
Cloud provider: On-premise
Issue: The manage instances page shows the list of all on-prem nodes and when a node is "In Use" or not

<img width="1640" alt="Screen Shot 2020-09-17 at 1 14 12 PM" src="https://user-images.githubusercontent.com/68662034/93523285-b077da80-f8e7-11ea-8c2a-98bcc2c85b4d.png">

The column "In Use" needs to be renamed to "Universe Name" and if a node is not in use it should show "NOT USED"

**Comment by sshev** [comment]
Merged in `master` and backported to `2.2`
