### ISSUE TITLE
[YSQL] Foreign Data Wrapper - Multi-Database Queries 

### ISSUE THREAD

**Issue by pkpattabhiraman** [yugabyte/yugabyte-db#5714]
Does YugaByte support Foreign Data Wrapper enabling users to leverage federated tables in a YugaByte database that are proxies for some other data source.

**Comment by ddorian** [comment]
Hi @pkpattabhiraman 

We haven't really tested FDW into other databases. 
Can you try and report back ?

**Comment by rkarthik007** [comment]
> Hi @pkpattabhiraman
> 
> We haven't really tested FDW into other databases.
> Can you try and report back ?

Hi @ddorian - we do not support this feature yet, so this is a valid request. There is work needed to enable this.

**Comment by wumingyuan** [comment]
In traditional database applications, this is a very important function.

**Comment by m-iancu** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/pull/9650 -- should be included in the next release (`2.9.1`).
