### ISSUE TITLE
Improve defaults for rpc queues and threads 

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#572]
Add the following as the default values for gflags:
```
rpc_workers_limit 256
cql_service_queue_length 10000
rpc_queue_limit 10000
```

These settings improve how YugaByte DB handles concurrent requests, which are very useful for real-time analytic workloads such as Apache Spark and Presto.

**Comment by bbaddepudi** [comment]
Also increase default `max_create_tablets_per_ts` to 50.
