### ISSUE TITLE
[YW] [Custom certs] Add the ability to rotate node keys/certs 

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5727]
#5723 

Following up on #5724, add the ability to rotate the cert for a universe (via the Edit Universe workflow / universe/update API call) from custom cert A to custom cert B which share the same CA cert but can have differing node certs and keys.

We should verify that the CA cert is unchanged both at the YW level during the edit universe and also on the db node level during the instance configure step.

**Comment by sshev** [comment]
Linking UI ticket https://github.com/yugabyte/yugabyte-db/issues/6717

**Comment by streddy-yb** [comment]
Verified using 2.4.2.0-b35:
- Create an OnPrem provider with Custom Home Dir (/opt/yugabyte) [technically custom home dir is not needed]
- Prepare 3 on-prem nodes using the instructions from here: https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/
- Create a TLS certificate with custom-ca with the correct paths
- Create an onprem universe with these nodes
- Generate new custom certs and copy the certs to a new location on the db nodes
- Now create a new TLS certificate with custom-ca option and the new path
- Rotate the certificates (Edit Universe -> Security -> Encryption-in-transit) using the new custom-ca

**Comment by streddy-yb** [comment]
Found couple of minor issues #8159 and #8160 as part of testing this.
