### ISSUE TITLE
[Platform] Disable "stop process" and "remove node" for a single node universe

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5733]
Trying to stop the process on a single node universe doesn't do anything which is expected because you can't bring the universe down to zero RF. But we do log the correct message in the logs

`Hit error 400, message: {"error":"Cannot STOP yb-dev-on-prem-universe-n1 as it will under replicate the masters."`

This should be handled seamlessly in the UI and we shouldn't allow stopping the process or removing the node

**Comment by VijiYB** [comment]
@SergeyPotachev - I still see "Stop Processes" and "Remove Node" for a single node cluster. I checked on build 2.7.1.0-b184


<img width="1609" alt="Screen Shot 2021-05-19 at 10 04 46 PM" src="https://user-images.githubusercontent.com/78048211/118922446-f067e500-b8ee-11eb-9318-d894d3c7b94c.png">

**Comment by streddy-yb** [comment]
@ymahajan - please update the issue with the expected behavior.

**Comment by SergeyPotachev** [comment]
@streddy-yb We don't need this to be reopened. I think the fix should be recovered under #8540.
