### ISSUE TITLE
Display thread ids for distinct stack trace

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5738]
Currently the thread dump would display the number of threads with the same stack trace:
```
Total number of threads: 10
```
However, if we compare the thread dumps across a few snapshots, we would be interested to know whether certain threads are stuck in that state.

ThreadData already tracks the thread id. We can use a vector which records the thread ids for one instance of stack trace and output the thread ids (instead of showing just the count).

This would facilitate debugging.

**Comment by bmatican** [comment]
@tedyu I believe we already do this, we would have 10 lines printed (eg: lines like this `rpc_tp_TabletServer_870-31048`, where 31048 would be the thread ID), but the stack trace part grouped up.

**Comment by tedyu** [comment]
Looking at a thread dump:

```
CQLServer_reactor-15108 | 48.650s | 0.000s | 0.000s
RedisServer_reactor-15101 | 12.290s | 0.000s | 0.000s |  
```
the delineation between two groups of threads (where each group has identical stack trace) is not very clear.

Also, given a few thread dumps, it is not easy currently to write program extracting the common thread ids which appear in all of the thread dumps.

**Comment by tedyu** [comment]
The thread dump can be stored in a format which is easy for program to analyze.

User can request continued dumping of threads, e.g. 10 dumps over period of 1 minute.

This way, finding the stuck threads can be automated.
