### ISSUE TITLE
[YW] Starting a tserver node when another master is down causes issues

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5739]
Repro steps (repros both on cloud and onprem):

1. Create a universe with 6 nodes in 3 AZs z1, z2, z3
2. Stop a master+tserver node n1 in z1 from the Nodes page -> "Stop Processes"
3. Stop a tserver node n2 in z1 from the Nodes page -> "Stop Processes".
4. Start n2 back from the Nodes page -> "Start"

n2 now comes back with a down master and tserver. 

![Screen Shot 2020-09-18 at 8 05 37 PM](https://user-images.githubusercontent.com/8207010/93657801-590e6300-f9ea-11ea-83ca-f504bddb8e98.png)

@bmatican @rao-vasireddy @WesleyW @chirag-yb

**Comment by SergeyPotachev** [comment]
Found a scenario where the operation still fails. Need to adjust the fix.

**Comment by streddy-yb** [comment]
@SergeyPotachev  can you back port this to 2.2?

**Comment by SergeyPotachev** [comment]
@streddy-yb Yes.
