### ISSUE TITLE
[YSQL] Does it make sense to use random bigint as PK with Yugabyte?

### ISSUE THREAD

**Issue by AmreeshTyagi** [yugabyte/yugabyte-db#5744]
It is an old post, but not sure if this case is still valid in 2020 for consideration, when we have high computation & space available but every penny matters.
https://instagram-engineering.com/sharding-ids-at-instagram-1cf5a71e5a5c

Should I use bigint as PK for Postgres/Yugabyte or UUIDs are good enough?
Because UUIDs have two basic problems as per this post:

1. Generally requires more storage space (96 bits or higher) to make reasonable uniqueness guarantees
2. Some UUID types are completely random and have no natural sort

**Comment by ddorian** [comment]
Hi @AmreeshTyagi 

Yes it's BIGINTs are more efficient than UUIDs.

How will you generate the ids though ? If by using sequences, make sure to configure [sequence cache](https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_sequence/#cache).

**Comment by AmreeshTyagi** [comment]
I would be creating unique Id similar to this script as mentioned in Instagram tech blog or using [snowflake](https://github.com/bwmarrin/snowflake) for golang project.  
But I want to know some benchmark to support bigint because I don't see any blog or technical discussion where bigint is mentioned with production grade benchmarks.

``` sql
CREATE OR REPLACE FUNCTION insta5.next_id(OUT result bigint) AS $$
DECLARE
    our_epoch bigint := 1314220021721;
    seq_id bigint;
    now_millis bigint;
    shard_id int := 5;
BEGIN
    SELECT nextval('insta5.table_id_seq') %% 1024 INTO seq_id;
    SELECT FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000) INTO now_millis;
    result := (now_millis - our_epoch) << 23;
    result := result | (shard_id <<10);
    result := result | (seq_id);
END;
    $$ LANGUAGE PLPGSQL;
```

``` sql
CREATE TABLE insta5.our_table (
    "id" bigint NOT NULL DEFAULT insta5.next_id(),
    ...rest of table schema...
  )
```
>  If by using sequences, make sure to configure sequence cache.

Yes. Thanks for this hint.

**Comment by ddorian** [comment]
Using the golang module https://github.com/bwmarrin/snowflake will be better because you won't be relying on a single server to generate the sequences (even with caching).

**Comment by ddorian** [comment]
Closing as we already provide unique BIGINT ids using sequences https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_sequence/
