### ISSUE TITLE
[YCQL] Add more queries to the system query cache

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5753]
Jira Link: [DB-1917](https://yugabyte.atlassian.net/browse/DB-1917)
Here is one for Cassandra cpp driver:
```
"SELECT data_center, rack, release_version FROM system.local WHERE key='local'"
```

**Comment by danielmh0** [comment]
We want to add `SELECT_LOCAL`, `SELECT_LOCAL_TOKENS`, and `SELECT_PEERS_TOKENS` as defined here: https://github.com/yugabyte/cassandra-cpp-driver/blob/2.9.0-yb/src/control_connection.cpp#L38

(I believe `SELECT_PEERS` is already there.)
