### ISSUE TITLE
[docdb] Recent test is flaky CqlIndexTest.TxnCleanup

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5755]
Jira Link: [DB-2392](https://yugabyte.atlassian.net/browse/DB-2392)
https://detective-gcp.dev.yugabyte.com/stability/test?class=CqlIndexTest&name=TxnCleanup

**Comment by tedyu** [comment]
From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F56775%2Fartifact%2Fbuild%2Fdebug-gcc-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cql-index-test%2FCqlIndexTest_TxnCleanup.log?max_lines=3000&start_line=36001 

```
38132 |   | E | 20.987642 | 18197 | mini_cluster_utils.cc:76 | T TABLET64 P PEER_B: Transactions: 7
-- | -- | -- | -- | -- | -- | --
38133 |   | E | 20.987777 | 18197 | mini_cluster_utils.cc:76 | T TABLET64 P PEER_C: Transactions: 7
38134 |   | E | 20.987850 | 18197 | mini_cluster_utils.cc:76 | T TABLET64 P PEER_D: Transactions: 7
38135 | src/yb/integration-tests/mini_cluster_utils.cc:85: Failure
38136 | Value of: has_bad
38137 | Actual: true
38138 | Expected: false
```
