### ISSUE TITLE
Update the Platform container base image to Red Hat UBI Image

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#5758]
Yugaware container Image currently uses Alpine Linux base image, however, Alpine based containers aren't recommended when certifying for platforms like OpenShift and Tanzu Kubernetes Grid. Currently, for all the certification purposes we have to generate a Yugaware container based on the UBI base image.

It will be easier for us to maintain container images and have necessary security patches if we use the RH UBI image which is enterprise-ready and the license allows vendors to distribute the container image.

**Comment by hsiaosu-yb** [comment]
added as part of open shift support.
