### ISSUE TITLE
[docdb] Test BackupTxnTest.DeleteTableWithMastersRestart flaky in tsan runs

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5770]
Jira Link: [DB-2513](https://yugabyte.atlassian.net/browse/DB-2513)
Not sure if related to #5769

https://detective-gcp.dev.yugabyte.com/stability/test?buckets=50&class=BackupTxnTest&name=DeleteTableWithMastersRestart

```
Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang15-tsan/1007/artifact/build/tsan-clang15-dynamic-ninja/yb-test-logs/tests-client__backup-txn-test/BackupTxnTest_DeleteTableWithMastersRestart.log

../../src/yb/client/backup-txn-test.cc:525
Failed
Bad status: Timed out (yb/util/backoff_waiter.cc:75): Operation 'Waiting for master leader' didn't complete within 5000ms
```

[DB-2513]: https://yugabyte.atlassian.net/browse/DB-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tedyu** [comment]
This test showed up in failed tests of D10181 and D10186
