### ISSUE TITLE
[docs] Document how to setup new Universe with TLS enabled using YB Platform 

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#5771]
Yugabyte Platform provides the ability to enable node-to-node and node-to-client encryption at the time of universe creation. The platform provides the option to create a new self-signed certificate, upload a third party certificate from providers such as Venafi or DigiCert, or utilize an existing self-signed or third party certificate.

Document step by step instructions for these two options:
- Create new universe with TLS certificate
- Upload existing TLS certificate

Internal doc available at https://docs.google.com/document/d/1DzPof-LuCsjV7sWR5XedA3o1wKFMZMSAIuA48V_OhFU/edit#

Github master issue for TLS + Custom Certs at https://github.com/yugabyte/yugabyte-db/issues/5723

**Comment by lizayugabyte** [comment]
@ameyb @chirag-yb I believe this issues has already been addressed and the doc is available here: https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/ 
Please let me know if my understanding is correct, in which case I'll close this ticket as "done"

**Comment by lizayugabyte** [comment]
@ameyb @chirag-yb I believe this issues has already been addressed and the doc is available here: https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/
Please let me know if my understanding is correct, in which case I'll close this ticket as "done"

**Comment by lizayugabyte** [comment]
@ymahajan, I've just been told that this ticket falls under your domain now, so here it is: I believe this issues has already been addressed and the doc is available at https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/
Please let me know if my understanding is correct, in which case I'll close this ticket as "done"

**Comment by lizayugabyte** [comment]
Messaged @ymahajan via slack. Haven't heard back yet.

**Comment by lizayugabyte** [comment]
This is done ( https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/ ) and confirmed by Yogesh. Closing the ticket.
