### ISSUE TITLE
[docs] Enhance the documentation for Backup and Restore of YB Universe data using YB Platform

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#5774]
This enhancement will include the following
1. Adding new config options for Storage locations: Azure Storage, Google Cloud Storage
2. Documenting new workflows with Scheduled backups, Encryption, and Parallel Threads
3. Steps to Backup data in a single Table, Entire Keyspace, or All Keyspaces in a Universe
4. Steps to Restore data into an existing Universe
5. Steps to Restore data into a new Universe
6. Remove the section for the local backup option as it is applicable to a single node universe only.

Current Doc link: https://docs.yugabyte.com/latest/yugabyte-platform/manage/back-up-restore-data

This enhancement will also cover an older git issue 2926 https://github.com/yugabyte/yugabyte-db/issues/2926

**Comment by rkarthik007** [comment]
This is live in the documentation at https://docs.yugabyte.com/latest/yugabyte-platform/back-up-restore-universes/
Closing the issue out.
