### ISSUE TITLE
[docs] Document all the Metrics provided in YB Platform

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#5775]
YB Platform Metrics section renders '91 different metrics' for monitoring the Universe. 
Create a new documentation in YB Platform Manage section (https://docs.yugabyte.com/latest/yugabyte-platform/manage/) to provide information about each of the metrics and what the ideal values should be. This will be helpful for users to understand the current Universe performance and also troubleshoot any issues.

**Comment by tuxillo** [comment]
You can get some extra information if you ask for the schema in the metrics URL, like so:

`
http://localhost:9000/metrics?include_schema=true
`

Of course it does not give an explanation of each one but at least you can get a better idea of what the metric provide and the units used. 

Example output:

```
[
    {
        "type": "tablet",
        "id": "aaec98a6a44a418999f325d637f9e8cf",
        "attributes": {
            "partition": "hash_split: [0xBFFA, 0xDFF9)",
            "namespace_name": "mykeyspace",
            "table_name": "foo",
            "table_id": "63e3fee5f5f441eeb5a5071ebd64c232"
        },
        "metrics": [
            {
                "name": "mem_tracker_log_cache",
                "label": "Memory consumed by log_cache-aaec98a6a44a418999f325d637f9e8cf->log_cache->server->root",
                "type": "gauge",
                "unit": "bytes",
                "description": "Memory consumed by log_cache-aaec98a6a44a418999f325d637f9e8cf->log_cache->server->root",
                "level": "info",
                "value": 0
            },
            {
                "name": "mem_tracker_RegularDB_MemTable",
                "label": "Memory consumed by MemTable->RegularDB->tablet-aaec98a6a44a418999f325d637f9e8cf->Tablets->server->root",
                "type": "gauge",
                "unit": "bytes",
                "description": "Memory consumed by MemTable->RegularDB->tablet-aaec98a6a44a418999f325d637f9e8cf->Tablets->server->root",
                "level": "info",
                "value": 2048
            },
...
```

I also think that documeting the metrics is a good thing (specially for monitoring) but it might be a moving target so the docs might become outdated with regards to the source and then a mechanism to sync both would be desired.

**Comment by lizayugabyte** [comment]
This ticket is related to https://github.com/yugabyte/yugabyte-db/issues/8803 and its dup https://yugabyte.atlassian.net/browse/PLAT-500

**Comment by lizayugabyte** [comment]
@tuxillo Thank you very much for your input. I've incorporated it in the doc.
