### ISSUE TITLE
[docs] Enhance Health & Alerting docs in YB Platform

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#5776]
Enhance the docs and screenshots to include new features in Alerting Controls like "Call Home Level" and Custom SMTP Email configs.

[Alex edit: compare docs to implementation and document all new features on alerting]

**Comment by lizayugabyte** [comment]
I think this has been address by the recent work on alerts

**Comment by lizayugabyte** [comment]
Done for 2.8.0 platform release
