### ISSUE TITLE
[CDC] Improve Read ahead for pending transactions

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#5778]
Currently, if we see a transaction, we expect its commit to be within `consensus_max_batch_size_bytes` distance of that entry in the log.  This is also the window that we use to limit the size of the GetChanges payload.  We should change the code to resolve pending transactions instead by continuing a read in `consensus_max_batch_size_bytes` chunks until we finish consuming the WAL entries.  This will have nontrivial worst case performance implications, but not have O(size) implications and be trivial latency, in practice.

**Comment by bmatican** [comment]
@nspiegelberg I'm guessing we can scrap this, in favor of https://github.com/yugabyte/yugabyte-db/issues/5779, even for the short term, given we're hoping to push that through in the next couple of weeks, right?

**Comment by nspiegelberg** [comment]
Closed as fixed by #5779
