### ISSUE TITLE
[YW] Delete platform code related to dev/debug package installs and EPEL repo

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#5799]
For enterprise customers, platform deployment should be updated with respect to these goals:

- requirement to install 'epel-release' should be removed

- any packages requiring epel-release should be removed. In the ["redhat_packages" list](https://github.com/yugabyte/yugabyte-db/blob/0e80be229bc2c98cd031027b9b4396cee0ceba5b/managed/devops/roles/server_base/defaults/main.yml#L46) this appears to be just "mosh" and "atop" - everything else is from base or extras repo

- Ideally, the package list still gets run, as validation that the requisite packages are actually installed

**Comment by iSignal** [comment]
We only need to install libselinux-python for Azure, the rest should not be needed, now that we install s3cmd and other backup packages ourselves.
