### ISSUE TITLE
do not update index if the indexed column's value remains unchanged

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#5802]
Another feature which could fit in the same code change--

It'd be really nice to optimize UPDATES that explicitly set an indexed column to its current value (leave it unmodified).

So instead of:
>  If row already exists (looking only at primary tablet) and no indexed columns are set, skip updating indexes.

Something like:
>  If row already exists and all indexed columns in the UPDATE already have the values given in the UPDATE (again only looking at the primary tablet), skip updating indexes.

Our use case involves rewriting millions of these heavily indexed rows, most of which are unchanging.

_Originally posted by @danielmh0 in https://github.com/yugabyte/yugabyte-db/issues/5678#issuecomment-692741522_

**Comment by OlegLoginov** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/e45a13afea71088f58c39247f32e832e6141dca9
