### ISSUE TITLE
List all databases from RPC (using Java)

### ISSUE THREAD

**Issue by ricemaster** [yugabyte/yugabyte-db#5803]
Hi guys,

In YSQL, `Namespaces in YSQL are referred to as databases and are logically the same as in other RDBMS (such as PostgreSQL)`. So how can I get all namespaces (databases) from RPC when I use Java?
<img width="716" alt="截屏2020-09-24 19 36 10" src="https://user-images.githubusercontent.com/10449002/94140066-45a54100-fe9d-11ea-993e-b48637648ab9.png">

I found `ListNamespacesRequestPB` and `ListNamespacesResponsePB` in `client.cc`, so I assume that the C/C++ RPC client could list all databases. But in `org.yb.client.YBClient`, I couldn't find the methods to do the same things in Java.

Is there any way to list all databases from RPC when I'm using Java?

Thanks~

**Comment by ddorian** [comment]
@ricemaster which client are you using in Java ?

You can execute this query:
```
SELECT datname FROM pg_database WHERE datistemplate = false;
```

**Comment by ricemaster** [comment]
Hi @ddorian , I'm using `org.yb.yb-client-0.8.0-SNAPSHOT` as a library, along with other JARs.
<img width="367" alt="截屏2020-09-24 19 54 04" src="https://user-images.githubusercontent.com/10449002/94142302-a08c6780-fea0-11ea-8d30-c464d9b221df.png">


Then I could call RPC to `list all masters` through YBClient like this:
```Java
public static void main(String[] args) throws Exception {
    String masterAddresses = "10.211.55.101:7100,10.211.55.102:7100,10.211.55.103:7100";
    AsyncYBClient asyncClient = new AsyncYBClient.AsyncYBClientBuilder(masterAddresses).build();
    ybClient = new YBClient(asyncClient);
    listAllMasters(ybClient);
    ybClient.close();
}

private static void listAllMasters(YBClient ybClient) throws Exception {
    ListMastersResponse listMastersResponse = ybClient.listMasters();
    List<ServerInfo> serverInfos = listMastersResponse.getMasters();
    System.out.printf("%s:%s%26s\n", "Host", "Port", "Status");
    for (ServerInfo serverInfo : serverInfos) {
        System.out.printf("%s:%d%16s\n", serverInfo.getHost(), serverInfo.getPort(), serverInfo.getState());
    }
}
```

It is also possible to get other meta data using YBClient, So I'm wondering if I could list all databases in this same way.

**Comment by ddorian** [comment]
@ricemaster why are you using this driver ? 

Meaning, what's the end goal of your application ?

**Comment by ricemaster** [comment]
@ddorian Well, I want to list all databases and all tables in each database together with YB grafana dashboard to give a whole view of the universe. From node perspective and from database perspective, you know.

Now, I could get table info from `yb-admin list_tables` but I couldn't find any command parameters in `yb-admin` like list_databases. So I try to find another way to get database list, then I got `YBClient` in source code.

I even don't know if it's the right way to use it...

**Comment by ddorian** [comment]
@ricemaster can you use `./bin/yb-admin list_tables_with_db_types` ?

**Comment by iSignal** [comment]
To follow up on @ddorian 's line of thought, if your goal is to list all SQL databases and SQL tables within the database, that can be done through psql or JDBC itself. Are you also trying to cover CQL databases/namespaces? 

The other option here if you are looking for yugabyte specific info is to query the endpoint `http://master:7000/dump-entities` which returns a JSON list of namespaces and tables.

**Comment by ricemaster** [comment]
Hi @ddorian @iSignal Thanks so much for your kindly guidance.

Actually, I want to show the whole structure of Data, like database-table-column, just SQL part not covering any CQL keyspaces.

So if I use `yb-admin` no matter `list_tables` or `list_tables_with_db_types`, I got databases and tables, no column details.
And the `http://master:7000/dump-entities` is amazing, I didn't know this interface before. But still, it contains just database and tables.

And using `YBClient` RPC, I could get tables and columns, but no databases.

For architecture point of view, it may be better to get all metadata from just one same way, either using `yb-admin` or `YBClient`.

I don't know if SQL/JDBC is the best way to do this for now, but I just thought maybe I should use more higher-level interface of yugabytedb than sql in case the way of yb metadata storage changes.

**Comment by iSignal** [comment]
For SQL, the best way would be to do this through psql ("\dt; \d <table_name;") or a JDBC API. Internal YB RPCs could technically change, even if in minor ways.

**Comment by ddorian** [comment]
>  I got databases and tables, no column details.

@ricemaster  Here is how to get columns:
```
yugabyte=# SELECT COLUMN_NAME, DATA_TYPE
yugabyte-# FROM information_schema.COLUMNS WHERE TABLE_NAME = 'users';
 column_name | data_type 
-------------+-----------
 id          | bigint
 name        | text
(2 rows)
```

**Comment by ricemaster** [comment]
Thank you @iSignal @ddorian , I'll use JDBC to get these database meta data.
