### ISSUE TITLE
[YSQL] Support generated columns

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#5805]
Jira Link: [DB-1559](https://yugabyte.atlassian.net/browse/DB-1559)
Generated columns are available in PostgreSQL 12: https://www.postgresql.org/docs/12/ddl-generated-columns.html

From slack user: https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1599780766218200

**Comment by sushantrmishra** [comment]
This support will come as part of upgrade to Postgres 13. 
Issue tracking that task https://github.com/yugabyte/yugabyte-db/issues/9797
