### ISSUE TITLE
[Platform] Interrupted air-gap bundle uploads leaves Replicated in an inconsistent state

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5815]
Not sure how easily reproducible this issue is but if an airgapped bundle upload is interrupted (ex: by refreshing the page) for some reason, this results in cancelling the upload but leaves a stale entry in Replicated. Once this happens, installing the new version fails even after successfully uploading the airgap bundle again. This is likely an issue with Replicated.

**Comment by streddy-yb** [comment]
Daniel confirmed that this is an issue with the Replicated.

**Comment by streddy-yb** [comment]
Hi @stevebang - Can we document this limitation for now?

**Comment by chirag-yb** [comment]
@daniel-yb Need to document Replicated upgrade instructions in our docs.
