### ISSUE TITLE
Onprem nodes list shows wrong universe name

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5816]
Original issue : #4758

Repro steps:
1. Create a universe sanketh-u9 with 9 nodes
2. Release 3 nodes from the universe
3. Create a new universe sanketh-u7 with 3 nodes released
4. Look at instances in the onprem provider "Manage Instances" page.

![Screen Shot 2020-09-25 at 12 14 12 AM](https://user-images.githubusercontent.com/8207010/94238416-333efd80-fec5-11ea-9584-020b76fdca8b.png)
![Screen Shot 2020-09-25 at 12 16 05 AM](https://user-images.githubusercontent.com/8207010/94238421-36d28480-fec5-11ea-9f9f-bfefa30872bc.png)

**Comment by sshev** [comment]
`nodeUuid` is not set for nodes in `universeDetails.nodeDetailsSet` thus use `nodeName` as a temp workaround match nodes with the universe
