### ISSUE TITLE
[YSQL] add tablespace column to pg_tablegroup

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#5823]
tablegroups should be able to belong to a tablespace to determine placement.  Then, we should add some column like `grptablespace` to `pg_tablegroup`.  This would be a system table format change.

**Comment by jaki** [comment]
Currently, tablegroups are only used for colocation.  Tables in a tablegroup are colocated to the same tablet.  It does not make sense for the individual tables in these tablegroups to choose their own, differing tablespaces since they share the same tablet.  Only one tablespace should apply to the tablet.

Right now, I believe tables in tablegroups are prevented from being part of a tablespace (this should be fixed if not).  Then, this feature will allow tables created under the tablegroup to inherit the tablegroup's tablespace.

Any ALTERs can be supported later.

Since this is a system table change, an initdb upgrade path will need to be implemented.  cc: @frozenspider

**Comment by frozenspider** [comment]
This was done, along with moving the table content to `pg_yb_tablegroup`, in 48dc70a0775eed9d598a4c2a6ccd9ef3b965695d in the scope of #10190
