### ISSUE TITLE
Disable node exporter/override custom ports flag for K8s universe

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5824]
Disable node exporter/override custom ports flag for K8s universe

**Comment by chirag-yb** [comment]
@daniel-yb Was this issue fixed as part of 5926?

**Comment by daniel-yb** [comment]
@chirag-yb no it was fixed as part of https://github.com/yugabyte/yugabyte-db/commit/1ecd35f90d8264cd6bd5ece387ccb49b3d96eeea#diff-ae0f85836bed52361b65176cdbc03663f8a3e1c8c7fd80cb490d763251c18458
