### ISSUE TITLE
[YSQL] Add native gen_random_uuid() function

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#5827]
Jira Link: [DB-1392](https://yugabyte.atlassian.net/browse/DB-1392)
Added in PG-13:  https://www.postgresql.org/docs/current/functions-uuid.html
We should pick up that change after PG-12 features are rebased.

**Comment by sushantrmishra** [comment]
Currently we are working on upgrade to PostgreSQL 13. Tracking GH issue 
https://github.com/yugabyte/yugabyte-db/issues/9797   . We will get gen_random_uuid  as part of that effort.
