### ISSUE TITLE
Azure Integration - Region information is inconsistent with Azure network page

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5837]
Cloud Provider - Azure
Release - 2.3.x
Issue - 
Cloud Provider >> Network Info >> Region Info is inconsistent with Azure network

Yyugabyte Platform -
<img width="544" alt="Screen Shot 2020-09-27 at 5 06 57 PM" src="https://user-images.githubusercontent.com/68662034/94379231-db321200-00e3-11eb-903e-5785997e7cf2.png">

From Azure - 
<img width="430" alt="Screen Shot 2020-09-27 at 5 07 11 PM" src="https://user-images.githubusercontent.com/68662034/94379241-e422e380-00e3-11eb-80da-b49f51b500d6.png">

[#5623](https://github.com/yugabyte/yugabyte-db/issues/5623)

**Comment by chirag-yb** [comment]
@sshev Is there any pending work on this issue?

**Comment by sshev** [comment]
@chirag-yb yes, our region names are currently not aligned with Azure ones

**Comment by SergeyPotachev** [comment]
Closed by a mistake, reopened.

**Comment by SergeyPotachev** [comment]
Fixed by the commit from #5628:
https://github.com/yugabyte/yugabyte-db/commit/5faa5c01f06748740c317db23917920ff0d4d175

**Comment by chirag-yb** [comment]
@SergeyPotachev should this be closed?
