### ISSUE TITLE
Azure - Missing "Public IP Address" configuration for DB nodes

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5843]
By default, DB nodes are assigned a public IP address and user doesn't have any control over this setting. Similar to AWS user should be able to enable/disable public IP address and there needs to be a tool tip why its recommended to set public IP address. 

[#5623](https://github.com/yugabyte/yugabyte-db/issues/5623)

**Comment by chirag-yb** [comment]
@WesleyW verified feature exists but it needs testing

**Comment by SergeyPotachev** [comment]
@chirag-yb Just checked this issue once again - the toggle exists, works, affects the instance configuration. Updating the state.

**Comment by chirag-yb** [comment]
@SergeyPotachev should this be closed?
