### ISSUE TITLE
[Onprem] - Unable to create a new cloud provider due to incomplete state left behind from previous failures

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5844]
Steps to reproduce -

1. Onprem cloud provider set up failed due to [5836](https://github.com/yugabyte/yugabyte-db/issues/5836) 
2. Delete the provider and try recreating it. When clicking on "Save" button nothing happens and UI doesn't respond 
3. From YW logs show this error
`Hit error 400, message: {"error":"Duplicate provider code: onprem"}`
4. Workaround is to manually delete stale onprem cloud provider entry from the Postgres DB

**Comment by streddy-yb** [comment]
Marking as a dup of #5848 as the underlying fix is the same
