### ISSUE TITLE
[Platform UI] Create Backup action on a universe with "backups disabled" fails with "Unknown" reason

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#5858]
Steps:

1. On a Universe with some tables, go to "Tables" page and disable backups
2. On "Backups" page try to create backup
3. It fails with status "Unknown". 

YW should say backups have been disabled and Create backup etc. should not be enabled.

**Comment by chirag-yb** [comment]
Duplicate - https://github.com/yugabyte/yugabyte-db/issues/8139
