### ISSUE TITLE
[Platform UI] Backup modal dialogue of Tables page for YCQL table throws keyspace name must be entered error

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#5877]
Steps:
1. Go to Tables page of a Universe with YCQL table
2. Click Actions -> Create Backup for YCQL table
3. Modal dialogue shows tabs for both YCQL and YSQL. It should show only for YCQL as Create backup is selected for a YCQL table
4. For YCQL table modal dialogue has a keyspace field that can't be edited
5. Throws backup keyspace is required exception when pressed OK.
6. Sometimes we get a different dialogue with Tables to backup field.

<img width="644" alt="Screen Shot 2020-09-29 at 3 40 15 PM" src="https://user-images.githubusercontent.com/67607029/94625476-aeaa0180-026d-11eb-9e66-8433554e2cf4.png">
<img width="658" alt="Screen Shot 2020-09-29 at 3 40 50 PM" src="https://user-images.githubusercontent.com/67607029/94625495-b5387900-026d-11eb-99cc-28d3c133c429.png">
<img width="1792" alt="Screen Shot 2020-09-29 at 3 38 20 PM" src="https://user-images.githubusercontent.com/67607029/94625511-bbc6f080-026d-11eb-97cc-1fc9427f9d2d.png">

**Comment by yb-andrew** [comment]
Fixed by c5d21c47ffe188f51151b0cc3a252e81e0efe98f
