### ISSUE TITLE
[docs] Getting started with spark & YSQL

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#5878]
Initial steps: https://docs.google.com/document/d/1_AK9Au6ZCKO7RkCaR048aRb3jPi61aDdqSofGFduAv0/edit

@ameyb please add your additional links here.

**Comment by lizayugabyte** [comment]
There are / will be other tickets for Spark docs. This one should be linked with them.

**Comment by ddorian** [comment]
@lizayugabyte feel free to link this under the other spark docs

**Comment by lizayugabyte** [comment]
To document in https://docs.yugabyte.com/latest/develop/ecosystem-integrations/apache-spark/java/#root
Additional base doc: https://docs.google.com/document/d/1ejuSWVf3UjyT75Tyt8B7blfO8iqfoXOvLQynV1z79ds/edit

**Comment by lizayugabyte** [comment]
@ameyb Would you be able to provide a starter doc for this?

**Comment by lizayugabyte** [comment]
Asked @kneeraj via slack if anybody from his team can provide the starter

**Comment by lizayugabyte** [comment]
@tedyu Could you, please, let me know if a starter doc for Spark YSQL is ready? If so, could you provide a link?

**Comment by tedyu** [comment]
I have been busy with other tasks. No starter doc for Spark yet.

**Comment by lizayugabyte** [comment]
@tedyu Could you let me know when you are planning to create this doc?

**Comment by tedyu** [comment]
Here is a document on Spark support for JSONB :

https://docs.google.com/document/d/1cE2Hs5r26RUcodzJS8tPK5Mh-9ksrOn4O6h_V0nweWM/edit#heading=h.9aqiwl30g4d2

**Comment by lizayugabyte** [comment]
Working on JSONB Upsert

**Comment by lizayugabyte** [comment]
@tedyu I believe this is documented here: https://docs.yugabyte.com/latest/integrations/apache-spark/java/

This ticket is specifically asking to document Spark with YSQL (not YCQL, which we already have). Is there a source of information on YSQL ?

**Comment by tedyu** [comment]
I haven't encountered use case of Spark job accessing YSQL.

**Comment by lizayugabyte** [comment]
@tedyu So you mean what we currently have is sufficient? And we don't need documentation on Spark with YSQL ?

**Comment by tedyu** [comment]
I haven't seen Spark with YSQL use case.

**Comment by lizayugabyte** [comment]
I'm closing this ticket based on @tedyu 's comment
