### ISSUE TITLE
[Platform] Don't allow backups for a universe if one is already in progress.

### ISSUE THREAD

**Issue by Arnav15** [yugabyte/yugabyte-db#5883]
If a backup is queued while another one is progress, the backup task will fail. We need to make sure the user doesn't even get into this state.

**Comment by streddy-yb** [comment]
I think this is already addressed as part of #5888. Please confirm and close @Arnav15

**Comment by Arnav15** [comment]
Yes @streddy-yb, that is correct. Tested it out and closing the issue.
