### ISSUE TITLE
system_query_cache.cc calls remove_if and does not use its result

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#5889]
![image](https://user-images.githubusercontent.com/552936/94747278-116dcc80-0344-11eb-9584-fa27f75ab292.png)

**Comment by tedyu** [comment]
Fixed via D9513

**Comment by bmatican** [comment]
https://github.com/yugabyte/yugabyte-db/commit/f7d4f6d5f60fc7e9db10a11e38eb26f114b8e4c6
