### ISSUE TITLE
[YCQL] Upgrade to Bison 3.2

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#589]
We are currently (as of 11/14/2018) using Bison 3.1.
Compiling with Bison 3.2 (latest in Homebrew) results in compilation errors: https://gist.githubusercontent.com/mbautin/8ea425c104f28c30818a754f531bb106/raw

**Comment by nocaway** [comment]
BISON new release now uses rvalue references for their "symbol_type()" constructor.
symbol_type (token_type t, location_type&&);
symbol_type (token_type t, KeywordType&&, location_type&&);

YugaByte scanner is updated to pass rvalue for current location.

**Comment by nocaway** [comment]
This bug has been fixed by the following commit.
https://github.com/YugaByte/yugabyte-db/commit/c73c8850717cff7d4f1262473201257c670e3e5e
