### ISSUE TITLE
[cdc] Add TLS support for cleaning up cdc_state table

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#5905]
We ran into a cluster issue where the cdc_state table was not being properly GC'd after a stream was destroyed.  The cluster has TLS enabled.  The issue is that the connection that master uses to clean up this CQL table does not have TLS knowledge.  Need to do an audit and ensure that all CDC connections have TLS connection capability.

**Comment by bmatican** [comment]
See also #5404

**Comment by nspiegelberg** [comment]
Requires #5992 to proceed
