### ISSUE TITLE
Helm charts repo instructions at https://charts.yugabyte.com/ need to be updated for helm 3

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5909]
From @chirag-yb 

```
The commands for searching repos is incorrect here - https://charts.yugabyte.com/
it should be
 helm search repo yugabytedb/yugabyte -l
```

**Comment by jharveysmith** [comment]
I've updated the index.html in the bucket, and I see it when hitting `https://charts.yugabyte.com/index.html` but not when hitting `https://charts.yugabyte.com/`.  Tried incognito mode and forced refresh, not sure what is caching the old page.

**Comment by jharveysmith** [comment]
Just ran an explicit cloudfront invalidation of the file and still not seeing it as the default index...

**Comment by jharveysmith** [comment]
Helm charts page is now showing the updated index.html by default.
