### ISSUE TITLE
[Platform] change default storage option for AWS provider to 1x250GB

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5919]

**Comment by gaurav061** [comment]
Current Behaviour: Number of instance that is set as default is being determined by the length of volumeDetailsList, which is the subset of instance type list, for most of the instance type this length is 2, but for some of them it is 1(i3.large and i3.xlarge), So Should i make this as hard coded value 1 for all instance type?

**Comment by jitendra-12113** [comment]
Back end changes are done.  Can some please review this code? 
https://github.com/yugabyte/yugabyte-db/pull/6688

UI has to consume **volumeCount** field to show volumeCountInfo - TO DO
cc: @gaurav061

**Comment by jitendra-12113** [comment]
Setting up the volumeCount for aws provider to 1 whose instanceType starting with c5/c4.

**Comment by gaurav061** [comment]
Please find the PR for this ticket:
https://github.com/yugabyte/yugabyte-db/pull/6688

**Comment by jitendra-12113** [comment]
Raised another PR for this ticket. Unit tests are included. Please review.
https://github.com/yugabyte/yugabyte-db/pull/6742

**Comment by jitendra-12113** [comment]
@sb-yb  As discussed, made the necessary changes. Created another CR for the same.
https://github.com/yugabyte/yugabyte-db/pull/6792/
Please review! Thanks!
