### ISSUE TITLE
Disable "Create Backup" if backups are disabled

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5921]
Version: 2.2.x/2.3.x

Current behavior: 
If backups are disabled on the "Tables" page then any attempt to take a backup will fail with "Unknown" status which can't be manually deleted 

Expected behavior: Users shouldn't be able to create a backup with visual feedback that backups are disabled.

**Comment by streddy-yb** [comment]
Steps to reproduce:
- Goto "Tables" tab and click on "Disable Backup"; at this point, backups are disabled
- Goto "Backups" tab, you still see Backup actions show up as enabled but they should be able disabled

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6664
