### ISSUE TITLE
[Platform] Need to fix install node exporter flow for onprem airgapped/non passwordless sudo cases

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#5926]
If the onprem provider is airgapped or non-passwordless sudo, we ask the use to run universe provisioning before creating the universe. Therefore in this case, the install node_exporter toggle in the universe creation is useless.

The options here are:
- Shift the install node exporter option to the onprem provider level. This is the more complicated solution.
- Move installing node exporter from the provisioning step to the configuring step. This is the simpler solution.

**Comment by iSignal** [comment]
As part of this, the plan is also to make the prometheus user name (for node exporter installation) a configurable parameter in the provider.

**Comment by chirag-yb** [comment]
@daniel-yb We should fix https://github.com/yugabyte/yugabyte-db/issues/5824 as part of this issue
