### ISSUE TITLE
Auto refresh on the UI page

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#5941]
Auto-refresh on the UI page so that users do not have to manually refresh the page while a task is running

**Comment by nishantSharma459** [comment]
I've proposed a solution on the slack channel.

**Comment by chirag-yb** [comment]
-  Backups page tables don't show up immediately in the drop down after creation and I had to refresh the page
- Created a new backup with NFS and it prompted that backup progress can be seen in the task window but no entry is shown on the backup page unless you refresh it
- Backups status was in process and I had refresh it to see the latest status Completed or Failed
- Enable Encryption at rest after the universe creation doesn't refresh the page.
- Leading to the previous action if EnableEncryptionAtRest Universe action fails page doesn't automatically refresh
- Deleting read replica cluster

**Comment by nishantSharma459** [comment]
For now, I'm putting it on hold. If any customer asks comes up we will deal with it on cases by case basis.
