### ISSUE TITLE
[YB Platform] Release instance is not an option for a node should the install fail because of ssh access.

### ISSUE THREAD

**Issue by tsmull-21** [yugabyte/yugabyte-db#5942]
During the scale up of the cluster the new vm had not been properly provisioned for ssh access. When the install failed the row was created for the new node but you are unable to release the instance to redo the install. There needs to be an option should the install fail to release the instance.

**Comment by iSignal** [comment]
Some other scenarios to consider that are similar to the earlier scenario but involve different failure points.

1. Port config issue from Yw -> tserver port 9100. To simulate, run `iptables -A OUTPUT -p tcp --dport 9100 -j DROP` on the YW node before doing an add node. This should cause a failure after the node is provisioned/configured but before YW can connect to the node via RPC.

2. Network communication issue from YW -> master port 7100. To simulate, run `iptables -A OUTPUT -p tcp --dport 7100 -j DROP` on the YW node before doing an add node. This should cause a failure after the node is provisioned/configured but before YW can connect to the master to verify the tserver is registered with the master.

**Comment by chirag-yb** [comment]
@SergeyPotachev Which release version contains this fix?

**Comment by SergeyPotachev** [comment]
It was not back ported since the landing time (December, 4th, 2020). I don't see it in 2.4 (not even speaking about 2.2.x).

**Comment by chirag-yb** [comment]
@streddy-yb We should add this in 2.4.1

**Comment by tylarb** [comment]
@streddy-yb  do you know if the universe details json still requires an edit now that this issue is fixed? Or is the universe details (like, nodes available in the pool) still needing a manual update after the node is released?

**Comment by SergeyPotachev** [comment]
In most cases json doesn't require any edits. We can't guarantee that the fix covers all the possible cases because we have more than 15 different states for nodes each of them could be in several intermediate states. But if you was able to release the node and the release process finished without any issues than the universe json (part related to this node) is in the consistent state.

**Comment by tylarb** [comment]
ok. Thanks Sergey. I'll re-close
