### ISSUE TITLE
[platform] Check for clock sync issues when creating a new universe

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5946]
Check for clock sync issues both at universe creation time and universe expansion time. Also, add clock sync to the health check.

**Comment by iSignal** [comment]
One possibility is to run something like `ntpd -gq` or `sntp -S <ntpserver>` manually as a non-fatal step during provision. Currently, we do see clock skew of around 200 ms a while after the universe is created, possibly because ntpd is making adjustments slowly over time.
