### ISSUE TITLE
Unable to mass delete records

### ISSUE THREAD

**Issue by germanoeich** [yugabyte/yugabyte-db#5948]
Hello, I'm having issues with deleting records. The following exception is raised:
`SQL Error [40001]: ERROR: Operation expired: Transaction expired or aborted by a conflict: 40001`

When running this query
```sql
DELETE FROM automodlogs WHERE "user"->>'id' IS NULL;
```

The table has about 2 million records and this query would delete about 800k records. I had to change timestamp_history_retention_interval_sec to prevent 'Snapshot too old' errors. Currently it's set to 3600s. My deployment is a 3 node cluster, each node with 6 cores and 16GB of RAM, all backed by SSDs (one drive per node).

The user->>'id' field is indexed, here's the query plan generated by Yugabyte:
![image](https://user-images.githubusercontent.com/17045274/95218160-5e312780-07ca-11eb-9596-acc880e4860c.png)

I also tried using a transaction with READ COMMITED isolation level, the same error happens, here's what I tried:
```sql
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITED;
DELETE FROM automodlogs WHERE "user"->>'id' IS NULL;
COMMIT;
```

My main question is should I move this to a script and do smaller batches of deletes or is there a setting I can tweak to prevent the exception?

**Comment by germanoeich** [comment]
Please note that this table is insert/read only. We don't ever update records within it and there are no new records being added matching the "user"->>'id' is null condition, since this was a bug in our code that caused JSON to be malformated during a database import.

**Comment by ddorian** [comment]
> My main question is should I move this to a script and do smaller batches of deletes or is there a setting I can tweak to prevent the exception?

Smaller batches/transactions are always better. Especially in distributed environments & replication.

**Comment by germanoeich** [comment]
Just leaving the solution I ended up using here in case someone stumbles here. It's not the fastest but it worked for me:
```sql
delete from automodlogs where id in (select id from automodlogs a where "user"->>'id' is null limit 80000);
```

Executing this a few times did the job. Took around ~6m per call. 

As a note, there's a variation that uses `WHERE id = any (array(SELECT * [...] LIMIT 100))` that is recommended in postgres docs. When running this in Yuga I managed to starve the ram in the node I ran it against and it ultimately crashed. So yea, don't do that in production.

Thanks for the answer ddorian!

**Comment by ddorian** [comment]
@germanoeich 

Note that DELETE is actually an INSERT of a tombstone record. And records are deleted on disk when compactions happen.
```sql
delete from automodlogs where id in (select id from automodlogs a where "user"->>'id' is null limit 80000);
```
This query will read 800K rows on the first run, 1.6M on the 2nd run (unless a compaction has happened) etc.
