### ISSUE TITLE
Deprecate ysql_scan_timeout_multiplier

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5949]
Jira Link: [DB-4730](https://yugabyte.atlassian.net/browse/DB-4730)
In src/yb/docdb/pgsql_operation.cc:

DEFINE_double(ysql_scan_timeout_multiplier, 0.5,
              "YSQL read scan timeout multipler of retryable_rpc_single_call_timeout_ms.");

This def references a non-existent gflag (in master branch), retryable_rpc_single_call_timeout_ms.

We should provide better document for ysql_scan_timeout_multiplier which deprecates the flag.

**Comment by jasonyb** [comment]
Done by commit b37606197b2841324fbbeb389eb21dc95a99c93f
