### ISSUE TITLE
[DocDB] Provide secondary preferred zone as an option

### ISSUE THREAD

**Issue by gbnnithin** [yugabyte/yugabyte-db#5952]
As of now we have only option to specify the leaders to specific region. During failover if 1 leader goes down It will pick another leader from different region(it's random). We need an option to specify which node should be the leader during failover process.
We need a secondary option to choose.

**Comment by bmatican** [comment]
Passing this to @hari90, as meatier task. Feel free to lean on @rahuldesirazu and @hulien22 for LB and leader affinity info.

Currently, we only support a single set of zones, for leader affinity. We want to move to a model where we can support an ordered list, of sets of zones. This would allow us to support various configurations (eg: RF3 / RF5, across 1-5 regions, etc), with more predictable steady state perf, even in case of full loss of a failure domain.

There's some more details and examples in our internal slack thread here: https://yugabyte.slack.com/archives/C01DAEBMAFR/p1645663731437009. We should also do a functional review internally first, to agree on the behavior in a couple of examples + implications on the ClusterConfig PBs, yb-admin interface, RPC interface, etc.
