### ISSUE TITLE
Replication delay script is not working for both YSQL and YCQL. (./determine_replication_lag.sh: line 419: tablet_count[${current_tserver}]: unbound variable)

### ISSUE THREAD

**Issue by gbnnithin** [yugabyte/yugabyte-db#5953]
Jira Link: [DB-2565](https://yugabyte.atlassian.net/browse/DB-2565)
`[root@yb-db-europe-01 bin]#  ./determine_replication_lag.sh -m 10.128.0.44:7100,10.128.0.43:7100,10.128.0.42:7100 --all_tables

Replication Latency Report for: All tables
./determine_replication_lag.sh: line 419: tablet_count[${current_tserver}]: unbound variable`

**Comment by tedyu** [comment]
It seems there was no entry in tablet_count for $current_tserver

**Comment by gbnnithin** [comment]
@tedyu  tablet_count exists . I guess for YCQL also same error is coming, someone notifies
 that as well

**Comment by ddorian** [comment]
@hulien22 had some comments

**Comment by ddorian** [comment]
Closed as we’ve since added replication lag support in UIs natively.
