### ISSUE TITLE
[DOC] HAVING clause error in published YB 2.3.2 YSQL grammar diagrams

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#5961]
Look within the `SELECT` diagram, [HERE](https://docs.yugabyte.com/latest/api/ysql/syntax_resources/grammar_diagrams/#select).

The "grammar" form says this:

```
[ HAVING { condition [ , ... ] } ]
```

A simple test shows this to be wrong. Create and populate a test table:

```
drop table if exists t cascade;
create table t(
  k     int      primary key,
  class int      not null,
  v     numeric);

insert into t(k, class, v)
select
  (1 + s.v),
  case (s.v) < 5
    when true then 1
              else 2
  end,
  case (s.v) <> 4
    when true then (100.0 + s.v)::numeric
              else null
  end
from generate_series(0, 9) as s(v);
```

Simple positive test. Runs without error.

```
select class, count(v), avg(v)
from t
group by class
having class < 2 and count(v) < 10;
```

Simple test to show that the YB published doc is wrong:

```
select class, count(v), avg(v)
from t
group by class
having avg(v) > 105, count(v) < 10;
```

It causes this syntax error:

```
42601: syntax error at or near ","
```

Notice that `condition` is defined thus:

```
condition ::= expression
```

This is _both_ an unhelpful level of indirection _and_ misleading. Rather, the better notion is `boolean_expression`. This rule is already found in `ysql_grammar.ebnf` but (just as is the case for `expression`) is has no further explanation.

Notice that `boolean_expression` is found in the `fn_over_window` rule, thus:

```
...[ FILTER ( WHERE { boolean_expression [ , ... ] } ) ]...
```

This shows the same error as `HAVING`. You cannot have a comma-spratated list of `WHERE` predicates. I'll correct this too.

I will fix `HAVING` by changing the rule to this:

```
[ HAVING boolean_expression ]
```

At the same time, I will replace this:

```
'WHERE' condition
```

with this:

```
'WHERE` boolean_expression
```

globally—and replace all remaining straggling uses of `condition` to `boolean_expression`. This will mean that the text `condition` is no longer found in `ysql_grammar.ebnf`.

**Comment by jaki** [comment]
Note that `WHERE condition` comes from [postgresql docs][1].  The author probably got it from there.  (I'm not advocating for this or that.)

[1]: https://www.postgresql.org/docs/11/sql-select.html

**Comment by bllewell** [comment]
Yes, I know. They also say `HAVING condition [, ...] ]`. But my test shows that this is wrong. Do you agree?

IMHO, the term "condition" is vague and therefor unhelpful. But the term "boolean_expression" is specific and widely understood.

**Comment by bllewell** [comment]
Closed by this PR:

https://github.com/yugabyte/yugabyte-db/pull/4864
