### ISSUE TITLE
[docs] Add YCQL audit logging

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#5967]
Document the new YCQL audit logging functionality. See the internal document for details.

Related:
- "YugabyteDB activity monitoring and audit log support" #1331
- "[YCQL] Improve audit logging support" #5851

**Comment by stevebang** [comment]
What are the plans for adding this to the Yugabyte Platform UI?

**Comment by rkarthik007** [comment]
This is documented here: https://docs.yugabyte.com/latest/secure/audit-logging/audit-logging-ycql/

Closing this issue out in favor of tracking the Platform documentation separately.
