### ISSUE TITLE
TestOneOrTwoAdmins fails

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5968]
The test fails rather consistently.

Example: https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F58048%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestOneOrTwoAdmins__testOneOrTwoAdmins%2Forg.yb.pgsql.TestOneOrTwoAdmins-output.txt?class=org.yb.pgsql.TestOneOrTwoAdmins&name=testOneOrTwoAdmins

Details:
ERROR: Operation failed. Try again.: Unknown transaction, could be recently aborted: 590b5d41-f69d-4214-b44b-ed6189b11579

Stack trace:
org.postgresql.util.PSQLException: ERROR: Operation failed. Try again.: Unknown transaction, could be recently aborted: 590b5d41-f69d-4214-b44b-ed6189b11579

**Comment by tedyu** [comment]
Running the test with commit bbcf51d638b23024506dfc25d61f03d2b234a01b : it passed.

**Comment by tedyu** [comment]
With commit ff5d5282aaaced99200decd73424b77da9ef8c11, it fails.

**Comment by bmatican** [comment]
Thanks for the bisect @tedyu ! Indeed, if it's about txns being cleaned up, it's likely that diff from @spolitov
