### ISSUE TITLE
YEDIS: Support for RENAME command

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#597]
We need to add support for RENAME of keys in YEDIS

**RENAME key newkey**

Renames key to newkey. It returns an error when key does not exist. If newkey already exists it is overwritten, when this happens RENAME executes an implicit DEL operation, so if the deleted key contains a very big value it may cause high latency even if RENAME itself is usually a constant-time operation.

```
redis> SET mykey "Hello"
"OK"
redis> RENAME mykey myotherkey
"OK"
redis> GET myotherkey
"Hello"
redis> 
```

**Comment by amitanandaiyer** [comment]
The above diff implements the feature as a read from src, followed by write to dest; and sets the key level ttl. 

Subkey level ttl moves (for TS data type) will be implemented separately.
