### ISSUE TITLE
Release instance is not an option for a node should the install fail because of ssh access.

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#5976]
During the scale up of the cluster the new vm had not been properly provisioned for ssh access. When the install failed the row was created for the new node but you are unable to release the instance to redo the install. There needs to be an option should the install fail to release the instance.

**Comment by streddy-yb** [comment]
Closing this as we have another issue tracking the same: https://github.com/yugabyte/yugabyte-db/issues/5942
