### ISSUE TITLE
[YW] Text in "Primary Cluster" gets cut off when window is sized small

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5988]
Minor UI issue, see the "Primary Cluster" box in the pic below. This happens on all providers.

![Screen Shot 2020-10-08 at 11 15 21 AM](https://user-images.githubusercontent.com/8207010/95518600-3f709380-0978-11eb-9986-9f63ebf30afa.png)

**Comment by sshev** [comment]
CSS fixed
