### ISSUE TITLE
CQL Delete with just the partition key is not supported

### ISSUE THREAD

**Issue by brianhks** [YugaByte/yugabyte-db#6]
Here is my table schema:

`CREATE TABLE kairosdb.row_keys (
    metric text,
    row_time timestamp,
    data_type text,
    tags frozen<map<text, text>>,
    value text,
    PRIMARY KEY ((metric, row_time), data_type, tags)
)`

Here is the delete query:

`DELETE FROM row_keys WHERE metric = ? AND row_time = ?`

Here is the error I get:

> Error in custom provider, com.datastax.driver.core.exceptions.SyntaxError: SQL error (yb/ql/ptree/process_context.cc:52): Invalid CQL Statement. Missing condition on key columns in WHERE clause
DELETE FROM row_keys WHERE metric = ? AND row_time = ?

I should think this would be a supported feature.

**Comment by rkarthik007** [comment]
Hi @brianhks,

I have tried get kairosdb running on Cassandra, and hit this as well as a couple of other issues :). We (cc @m-iancu) are working on this issue actively, and should support this in a week or so. Will update once it is ready.

**Comment by brianhks** [comment]
For now I've commented out the delete queries and I'm able to get it running.  Heck who wants to delete data anyway ;)

**Comment by kmuthukk** [comment]
@brianhks : that's temporarily what @rkarthik007 had to do to move forward :). We noticed that the code was doing the "prepare" step upfront, but the actual "execute" for "delete" statements wouldn't be exercised in the common flows.

**Comment by rkarthik007** [comment]
@brianhks - I had hit a couple of other issues also.
One was the end time being MAX_LONG which we were not respecting (I tried a query without an end time, had to add that), and the other was support for compression. We're fixing/have fixed both, will be out with the next release.

**Comment by brianhks** [comment]
Yes I was going to mention the compression issue as well but forgot.  In my previous performance tests with C* compression makes a big difference.

**Comment by kmuthukk** [comment]
Yes indeed. Just to note, we added the client to server compression support recently:

https://github.com/YugaByte/yugabyte-db/commit/07f1dea26e4896b2cdad7d154096136e67e7e850

We'll make sure to cut a newer build, and make it available for download soon.

**Comment by kmuthukk** [comment]
@m-iancu : I think we can close this issue out, given your commit:

https://github.com/YugaByte/yugabyte-db/commit/466d88162e7e39eeb353d8e4002c96fb6644001c

Can you please confirm, and close out if so.

**Comment by m-iancu** [comment]
@kmuthukk, yes it's done and that commit is now included in the latest release (https://docs.yugabyte.com/quick-start/install/). Closing.
