### ISSUE TITLE
Need ability for platform to check for actual clock synchronization

### ISSUE THREAD

**Issue by mdenman-yuga** [yugabyte/yugabyte-db#6017]
YB docs indicate that ntp should be installed. RedHat deployments are now likely to be using chrony for click synchronization. On universe creation checks should be made to ensure the clock synchronization is actually synchronized rather than just a check for the existence of chrony or ntp. There may be times when DNS or other issues prevents chrony from actually communicating and therefore clocks are not synchronized. There should either be a hard check or documentation to verify that clock synchronization is working.

**Comment by SergeyPotachev** [comment]
Intersects with https://github.com/yugabyte/yugabyte-db/issues/5247

**Comment by SergeyPotachev** [comment]
Verified on 2.4.2.
