### ISSUE TITLE
[YW] [Azure] UI improvements to the provider page.

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6020]
![Screen Shot 2020-10-12 at 12 22 23 PM](https://user-images.githubusercontent.com/8207010/95782890-8a92eb00-0c85-11eb-9ad3-fc4f279626b1.png)

1. Add help text to the fields on the provider page.

2. Group the fields differently so that the fields are ordered as follows
```
----------
Subscription ID
Resource Group
----------
Tenant ID
Client ID
Client Secret
----------
Virtual Network Setup
Regions
```

3. Add full region names to the Regions list. We do show full region names in the universe create page but only show region ids here.

![Screen Shot 2020-10-12 at 12 23 54 PM](https://user-images.githubusercontent.com/8207010/95783025-d776c180-0c85-11eb-9056-16fd5f0aeb9c.png)

#5623

**Comment by chirag-yb** [comment]
@sshev Is there anything pending for this ticket?

**Comment by sshev** [comment]
@chirag-yb nothing pending for this ticket from my side
