### ISSUE TITLE
ERROR: syntax error at or near "SUPPORT"

### ISSUE THREAD

**Issue by snehalbhavsar916** [yugabyte/yugabyte-db#6027]
I  tried to install postgis on latest version (yugabyte-2.3.2.0) of yugabyte and facing this issue again:
ERROR: syntax error at or near "SUPPORT"

This time I removed and reinstalled everything (postgres, postgis and yugabyte)

Postgresql Version: postgresql-11
Postgis version : postgresql-11-postgis-3      3.0.2+dfsg-4.pgdg18.04+1
Yugabyte Version: yugabyte-2.3.2.0
Operating System: Ubuntu 18.04.5 LTS

I followed these steps to install postgis:

 sudo apt install postgis postgresql-11-postgis-3
 sudo apt-get --purge remove postgresql-11-postgis-3-scripts
 
 alias yb_pg_config=/root/yugabyte-2.3.2.0/postgres/bin/pg_config
 
 cp -v "$(pg_config --pkglibdir)"/*postgis*.so "$(yb_pg_config --pkglibdir)" && 
 cp -v "$(pg_config --sharedir)"/extension/*postgis*.sql "$(yb_pg_config --sharedir)"/extension && 
 cp -v "$(pg_config --sharedir)"/extension/*postgis*.control "$(yb_pg_config --sharedir)"/extension

 ./bin/post_install.sh -e 
 
 yugabyte=# CREATE EXTENSION postgis;
ERROR:  syntax error at or near "SUPPORT"

Here in docs https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis, it is mentioned that it is best compatible with libraries of 11.2. So is it necessary to have installed 11.2 version only of postgres or it will work with 11.9 as well? Because it is currently not working with 11.9 libraries, I guess.

**Comment by ddorian** [comment]
@snehalbhavsar916 

Please retry again by removing this step:

```
 sudo apt-get --purge remove postgresql-11-postgis-3-scripts
```

**Comment by snehalbhavsar916** [comment]
@ddorian thanks..!! This worked.

**Comment by ddorian** [comment]
The problem in this case what that @snehalbhavsar916 had also installed postgresql-13.
The default `pg_config` was using PostgreSQL 13. 
Removing PostgreSQL 13 or using the correct `pg_config` of PostgreSQL 11 fixed the issue.

**Comment by snehalbhavsar916** [comment]
It would be great if yugabyte can provide support and compatibles with latest PostgreSQL libraries as well.
