### ISSUE TITLE
[docdb] master leader unresponsive when cluster has a very high number of tablets.

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#6028]

**Comment by mbautin** [comment]
@rao-vasireddy very high number of tablets?

**Comment by bmatican** [comment]
We have done quite a bit of work to introduce caching for YCQL system.partition queries, which were otherwise extremely expensive on the master.

Most recently, we've enabled this caching by default in 7f65b9d7ce91519fe41f332a376c3e375af704c5
