### ISSUE TITLE
[Platform] YW logs you out when someone else logs in using the same login credentials

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#6036]
I believe if your session is less than 24 hours old, you are supposed to stay logged in even if someone else logs in using the same login credentials.

**Comment by streddy-yb** [comment]
@rao-vasireddy - I can't repro this. Is this with a particular type of user role (ex: readonly)?

**Comment by streddy-yb** [comment]
@rao-vasireddy - is this in an older version of the product? I can't repro it on main. Please reopen it if you're able to repro.
