### ISSUE TITLE
[docs] Update and enhance docs covering YCQL secondary indexes

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#6048]
Jira Link: [DB-2342](https://yugabyte.atlassian.net/browse/DB-2342)
Need:
-Add examples using secondary indexes in YCQL.
- Update YCQL [CREATE INDEX](https://docs.yugabyte.com/latest/api/ycql/ddl_create_index/) page to cover more about secondary indexes, add examples, and point to related topics.
- Update "Best practices page for YCQL, the [Covered indexes](https://docs.yugabyte.com/latest/develop/best-practices-ycql/#covered-indexes) section briefly mentions secondary indexes, but has no details or links to relevant content.
- Indexing in YCQL should probably be a separate topic.

A few sources of info and examples:
- [Secondary indexes](https://docs.yugabyte.com/latest/develop/learn/data-modeling-ycql/#secondary-indexes)
- https://blog.yugabyte.com/yugabyte-db-1-1-new-feature-speeding-up-queries-with-secondary-indexes/
- [YCQL SELECT](https://docs.yugabyte.com/latest/api/ycql/dml_select) page includes a brief mention of secondary indexes.

**Comment by ddorian** [comment]
This has already been documented. Closing as fixed.
