### ISSUE TITLE
[docs] Add a section explaining what "remote bootstrap" is and how it works

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#6058]
The phrase "remote bootstrap" is mentioned in the docs, but we never define what that means.  We need to add a section on "remote bootstrap" that includes:
- "remote bootstrapping" overview
- how to perform a manual "remote bootstrap" and when it's needed

Aggregated (and edited) response from @bmatican about what "remote bootstrap" means? 

In short, if a Raft peer falls behind (or is just added to a quorum, which is an edge case of falling behind, as it has no data), then it must ask the leader for the latest copy of the data. The leader will then snapshot its current state and ship a bunch of files to the said follower. This process is called _remote bootstrapping_. Once the files are on the follower, it must also start a process called _local bootstrapping_, to essentially process those files, load up w/e metadata in memory and start its corresponding components to become a full-blown Raft peer.

This is only tangentially related to tablet balancing, in the sense that the load balancer (LB) moves tablets around, and when a peer is added to a quorum as part of these moves, that peer must be remote bootstrapped from its corresponding leader.

> if a raft peer falls behind

Remember when I was saying that we have those 2 flags that should be in sync, WAL retention and follower unavailability:
If WAL retention is smaller then the unavailability window, then it could be possible for a follower to fall behind (was shut down or network partitioned), the leader to GC its logs, after the retention period, then when the follower comes back, the leader would not have logs to catch up the follower, so it would have to force it to go through remote bootstrap.

We have 2 types of data files:
- Raft WAL files
- RocksDB SST files

If for some reason, a follower falls behind a leader and the leader no longer has the WAL files necessary to serve updates to the follower, it has no other option but to force the follower to throw away all its data and use the leader’s data.

See also: [Adding New Node](https://github.com/yugabyte/yugabyte-db/blob/master/architecture/design/docdb-encryption-at-rest.md#adding-new-node) in the [Encryption At Rest in YugabyteDB](https://github.com/yugabyte/yugabyte-db/blob/master/architecture/design/docdb-encryption-at-rest.md) architecture document.

**Comment by stevebang** [comment]
@bmatican Should we also document how to perform a manual remote bootstrap?

**Comment by wumingyuan** [comment]
What's the w/e metadata?

**Comment by bmatican** [comment]
@stevebang I believe @ddorian is documenting that in one of the trouble shooting PRs, but we could unify that and then just reference it.

@wumingyuan there's several things that need to be loaded on tablet startup, some metadata (eg: potentially rebuild the index into the WAL files, consensus group information, rocksdb metadata files, etc), some data (eg: not all data in WALs might have made it into rocksdb, so we have to read all those WAL entries and apply them to rocksdb, before we can start serving)

**Comment by ddorian** [comment]
@stevebang @bmatican it's here https://github.com/yugabyte/yugabyte-db/pull/4852, waiting for reviews from your

**Comment by lizayugabyte** [comment]
@ddorian @bmatican #4852 has been closed. Should this ticket also be closed as "done"? Or is there anything else that needs to be documented?

**Comment by ddorian** [comment]
@lizayugabyte that issue only explains how to recover. But doesn't explain in full what remote bootstrap is like this issue requires to. I think this needs to stay opened.
