### ISSUE TITLE
2DC Txns: Replicate Intents and Apply Messages

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#6068]
In the current flow, a producer waits for a transaction to be applied before sending corresponding records to regular rocksdb. This can be an issue for long running transactions where we may end up waiting for hours for the txn to finish before continuing with replication. Change this by replicating intents to be applied to the consumer's intent db and applying these intents when the consumer gets the corresponding apply message.

**Comment by bmatican** [comment]
Related to #5779
