### ISSUE TITLE
Consider comments about Python script interrobang lines

### ISSUE THREAD

**Issue by aegershman** [YugaByte/yugabyte-db#607]
EDIT: realized I could give this feedback directly in the docs UI, so I did that instead. My bad, I hope this wasn't the wrong place for docs feedback.

As someone new to YugaByte whose [following along with the quickstart tutorial](https://docs.yugabyte.com/latest/quick-start/create-local-cluster/), it took me an embarrassingly long time to figure out why running `./yb-docker-ctl` was throwing this error:

```
➜  yugabyte git:(master) ✗ ./yb-docker-ctl create
env: python2: No such file or directory
```

It turns out it's because the interrobang line at the top of the script is calling `#!/usr/bin/env python2`, whereas my alias for python 2.7 is simply `python`. Also the quickstart doc makes it seem as though `python` is the alias that will be used:

<img width="969" alt="screen shot 2018-11-27 at 8 06 29 pm" src="https://user-images.githubusercontent.com/5619476/49123962-3395ef80-f280-11e8-80c6-39f7701b36ae.png">

There are other scripts which use different python aliases in the interrobang, such as [`yb-ctl
` using `python2.7`](https://github.com/YugaByte/yugabyte-db/blob/master/bin/yb-ctl#L1) and various other scripts in the `bin/` and `python/` folders.

Just a suggestion, it might be worth pointing out to people that the interrobang line could need to change depending on your environment. I imagine many people will be able to figure it out once it's pointed out.

**Comment by mbautin** [comment]
Hi @aegershman, thank you for reporting this issue! We will definitely fix the inconsistency in the docs and the shebang line for `yb-docker-ctl`. I think we will be using the `python2.7` shebang for all of our user-facing Python 2 scripts as it is most specific (e.g. `python` could be pointing to Python 3 in some environments) and is present in most Unix environments. Would you mind confirming if `python2.7` is also present on your system?

**Comment by aegershman** [comment]
Right on. I can confirm:

```sh
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2

➜  ~ which python2.7
/usr/bin/python2.7

➜  ~ python --version
Python 2.7.10

➜  ~ python2
zsh: command not found: python2
```

Thank you 👍
