### ISSUE TITLE
[docs] DROP TABLE account misses CASCADE/RESTRICT

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#6090]
Doc of `DROP TABLE` here:

> https://docs.yugabyte.com/latest/api/ysql/commands/ddl_drop_table/

is missing the `CASCADE` (or `RESTRICT`) option.

A quick scan shows that this is a one-off. But when fixing this bug, please check _every_ `DROP` statement.

**Comment by rkarthik007** [comment]
This issue seems to be addressed by your fix @bllewell - so closing out. Please reopen if something else needs to be done.

**Comment by bllewell** [comment]
Oops, sorry, rkarthik007. I forgot to close this when I fixed it as part of this PR:

> https://github.com/yugabyte/yugabyte-db/pull/6150
> commit 7fdfd0b6a406c427b335a5540a123bdd519f0c8f
> Date:   Mon Oct 26 10:35:57 2020 -0700
