### ISSUE TITLE
[YP] Clicking the "Encryption At Rest" tab in the Security tab causes the Backup tab to open.

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#6091]
To reproduce:
1. Click **Configs** and then click the **Security** tab.
2. Click **Encryption At Rest** tab.
Unexpectedly, the **Backup** tab displays. It should stay on the **Encryption At Rest** tab.

**Comment by streddy-yb** [comment]
Hi @stevebang - can you clarify what you mean by "unexpectedly"? I couldn't reproduce this behavior.

**Comment by streddy-yb** [comment]
Cannot reproduce this behavior.
