### ISSUE TITLE
[YP] Create New Config form (for Encryption At Rest) needs a Cancel button

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#6093]
One a user clicks **Create New Config**, the only way to cancel the configuration is to refresh the page.

To reproduce:

1. Open the Yugabyte Platform console and click **Configs**.
2. Click the **Security** tab and then click the **Encryption At Rest** tab. A list of configurations appears.
3. Click **Create New Config**. A new configuration form appears.
To cancel the form, you have to refresh the page.

**Comment by mjoshi0923** [comment]
This is already fixed in past.
