### ISSUE TITLE
[docdb] issues when doing a lot of splits for already existing big tablets  

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#6111]
Jira Link: [[DB-306]](https://yugabyte.atlassian.net/browse/DB-306)
We have been running YCQL benchmark CassandraBatchTimeseries with 50GB tablet split size for few days. After replacing flag to 5GB write ops have dropped significantly.

[DB-306]: https://yugabyte.atlassian.net/browse/DB-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ttyusupov** [comment]
1) I see it did a series of tablet splits between 1020 23:30:30 and 1020 23:31:07 resulted in 72 tablets and then it started to have issues.

2) Seeing a bunch of the following messages in tserver log:
```
I1020 23:43:30.695937 12458 tablet_service.cc:1147] T ebc39d69c5d644cf94b29b2c21a9f4c2 P 1e23843b89c849b9a1c71580205d67d9: Processing DeleteTablet with delete_type TABLET_DATA_DELETED (Replaced by 9b8a5518108a4823828c4a407bc5e22c at 2020-10-20 23:31:02 UTC) from 172.151.17.103:40692
```

Need to review #1 about how to handle split of big tablets (with high tablet size / split threshold ratio) better in order to not overload the system.

For #2 - need to fix slow tablet creation handling for post-split tablets.

**Comment by bmatican** [comment]
This is related to the issue we observed in https://github.com/yugabyte/yugabyte-db/issues/5390, where, because split tablets on the master are registered as CREATING, they could be picked up by the master background thread (`CatalogManagerBgTasks`), which would attempt to actually create tablet copies for them, eg: `catalog_manager_->ProcessPendingAssignments(to_process);` leading to `CatalogManager::HandleAssignCreatingTable`

What @ttyusupov and I had discussed before, is that a likely cheap way to prevent this, is to check if the CREATING tablets are at depth 0 or not, as a proxy for these being "brand new tablets" vs "split tablets".

We should also be able to simulate this in a unit test scenario, by adding a test-only gflag sleep, on the TS side, when receiving a split RPC. The value should be higher than that of the master background thread, (`catalog_manager_bg_task_wait_ms`), so that kicks in first.

**Comment by ttyusupov** [comment]
> For #2 - need to fix slow tablet creation handling for post-split tablets.
This was done as a part of https://github.com/yugabyte/yugabyte-db/commit/53c383f014bb426498368ff9ef1546b445fa23ba.

**Comment by ttyusupov** [comment]
> Need to review #1 about how to handle split of big tablets (with high tablet size / split threshold ratio) better in order to not overload the system.

This seems to be an issue because we trigger post-split tablets compaction and a lot of such compactions overload the system.
So, we can do the following (from hardest to easiest):
a. Optimize post-split tablet compaction to just throw out non-relevant data quickly instead of doing full compaction.
b. Copy data which we need and rebuild SST file indexes, avoid decoding-encoding DocDB data, this is slower than 1. but faster than full compaction.
c. Quick-term temp solution: add a limit on the number of tablets that are split, but not yet compacted we can have. This way we can reduce the load on the system caused by post-split tablets compaction.

**Comment by bmatican** [comment]
@ttyusupov @robertsami quick check, for a), was this fully handled in https://github.com/yugabyte/yugabyte-db/issues/5523 ?

I'll cut c) into a new task, not sure if we want to do b) anymore, given a) will now be done in the background, async, and the LB will wait for it.

**Comment by ttyusupov** [comment]
> @ttyusupov @robertsami quick check, for a), was this fully handled in #5523 ?

In #5523 implementation we still do compaction but it is optimized to skip non-relevant keys.
While a) is about not doing compaction at all and just throw out non-relevant data without even decoding/encoding of all relevant key-value pair.

**Comment by bmatican** [comment]
@ttyusupov Aaah ok, so that could be a strict speedup of compactions! Probably still worth doing, but not high pri.

**Comment by bmatican** [comment]
Would be good to recheck this scenario to see if we still observe large TPS drop.

My previous experiment was described here: https://github.com/yugabyte/yugabyte-db/issues/6104#issuecomment-931503580, however I was only looking at stability and I don't recall / did not save any TPS metrics.

**Comment by qvad** [comment]
Completed some testing in following scenario:
2xlarge AWS instances, 1 tablet per table in configuration, upload ~50GB data for 40 tables, splitting disabled
After upload is done there is 2 separate scenarios:
1. Just enable default tablet splitting
```
"master_gflags": {
    "enable_automatic_tablet_splitting": "true"
}
```
2. Enable intensive tablet splitting
```
"master_gflags": {
    "tablet_split_low_phase_size_threshold_bytes": "2097152",
    "tablet_split_limit_per_table": "8172",
    "enable_automatic_tablet_splitting": "true",
    "tablet_split_low_phase_shard_count_per_node": "134217728",
    "ysql_num_shards_per_tserver": "1",
},
"tserver_gflags": {
    "ysql_num_shards_per_tserver": "1",
    "memstore_size_mb": "1",
}
```

In case of default splitting there is no significant effect on performance, while in case of intensive splitting there might be performance drops to 0 when we ROLLING RESTART cluster with changed flags.

**Comment by qvad** [comment]
Not reproducible anymore for YSQL or YCQL scenarios.
Testing 1.3Tb table with 12 tablets per server for YCQL and 500GB tables for YSQL. No performance impact noticed that depends on tablet splitting flags.
