### ISSUE TITLE
[platform] Client Certificates are not valid on download due to incorrect validity time

### ISSUE THREAD

**Issue by Arnav15** [yugabyte/yugabyte-db#6118]
This occurs due to the UI sending the local time, but the backend interpreting it as UTC.

**Comment by streddy-yb** [comment]
I'm able to reproduce this bug in 2.2.4.0-b5. Steps to reproduce:
- Create a new universe (important to create a new brand new universe) with client tls enabled
- Download client crt/key files and connect, it will fail with "ysqlsh: SSL error: certificate verify failed" error

Approximate timestamp on the platform and the db nodes when I ran ysqlsh
```
$ date
Wed Oct 28 07:12:52 UTC 2020
```

Certificate validity timestamp is in the future (Oct 28 14:03:12 2020 GMT)

```
openssl x509 -in yugabytedb.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1603868918458 (0x1756e0982ba)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=yb-dev-u3, O=example.com
        Validity
            Not Before: Oct 28 14:03:12 2020 GMT
            Not After : Oct 28 14:03:12 2021 GMT
        Subject: CN=yugabyte

```

**Comment by streddy-yb** [comment]
Also, interestingly, I generated a pair of client certs on the same universe and I see the validity for these certs is same as the original one I generated right after creating the universe. So the certs have a validity date in past and have a hard coded "_Not Before_" date.

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1603900838460 (0x1756ff0923c)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=yb-dev-u3, O=example.com
        Validity
            Not Before: Oct 28 14:03:12 2020 GMT
            Not After : Oct 28 14:03:12 2021 GMT
        Subject: CN=yugabyte
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
```
@Arnav15
