### ISSUE TITLE
Claim helm charts entry at artifacthub.io

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6124]
https://artifacthub.io/packages/search?page=1&ts_query_web=yugabyte

Having a verified publisher entry will allow us to distinguish official from community charts.

**Comment by tegioz** [comment]
Hi @iSignal 

You may also be able to apply for the [official status](https://artifacthub.io/docs/topics/repositories/#official-status) if your repo and/or packages match the requirements 🙂 It has a different meaning than the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.

**Comment by bhavin192** [comment]
Thanks for reminding, I had that in my mind, and later missed it.
