### ISSUE TITLE
[YSQL] The object does not exist: table_id: "00000001000030008000000000001f4a"

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6132]
I keep seeing this in postgres logs whenever starting `ysqlsh`:

```
W1022 16:00:51.383910  8670 client-internal.cc:1402] GetTableSchemaRpc(table_identifier: table_id: "00000001000030008000000000001f4a", num_attempts: 1) failed: Not found (yb/master/catalog_manager.cc:4174): The object does not exist: table_id: "00000001000030008000000000001f4a"
```

That table 0x1f4a is pg_class oid 8010 is `YBCatalogVersionRelationId` (`src/postgres/src/include/catalog/pg_yb_catalog_version.h`) introduced by commit 3253827a315ac2ea5dc336ade8c76172fec5d9e3.

**Comment by m-iancu** [comment]
@jaki Have you run a reinitdb build recently?

**Comment by jaki** [comment]
Thanks.  That makes sense and fixes the issue.
