### ISSUE TITLE
`Using Client specified timeouts for rpcs` not merged to yugabyte 2.3

### ISSUE THREAD

**Issue by iswarezwp** [yugabyte/yugabyte-db#6136]
see this commit: https://github.com/yugabyte/yugabyte-db/commit/bba4ab7dace0436295b038e9fc2adc458197eec9

**Comment by ddorian** [comment]
@iswarezwp it is available on 2.3. look inside the commit 
![image](https://user-images.githubusercontent.com/1592898/97612088-40e12900-1a17-11eb-9ca9-9c7d57421b6e.png)

**Comment by iswarezwp** [comment]
@ddorian Sorry, I miss it. 2.3 use a deferent param `deadline` instead of `timeout`.
