### ISSUE TITLE
[YSQL] Fix TestPgRegressTablegroup

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6140]
`org.yb.pgsql.TestPgRegressTablegroup.testPgRegressTablegroup` postgres regress test is failing.  Failures started happening more from commit fb7ce2bd095280cadf2ce7a09ed4a57d569a1fb4 (bad) compared to commit 9518629e1c265d8d49677b476f50045226a09e3f (good).  Didn't look into why.

**Comment by tedyu** [comment]
```
 49  DROP TABLEGROUP owned_by1_created_by2;                                                                     62  DROP TABLEGROUP owned_by1_created_by2;
                                                                                                            >   63  WARNING:  unrecognized node type: 296
```
The failure was due to the unexpected node type.

**Comment by ramsrivatsa** [comment]
Hi @tedyu. Just curious to know if this test was failing even before pgAudit?
