### ISSUE TITLE
[docdb] load balancer is placing 2 replicas in one AZ in some uneven configs after node removal

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#6142]
Jira Link: [DB-4731](https://yugabyte.atlassian.net/browse/DB-4731)
RF-3, 3AZ, 4 nodes 
One AZ has 2 nodes and the other 2 have 1 node each.

Create a table in steady state with all 4 nodes online

Remove a node in one of the AZs that has only 1 node, then load balancer adds a second replica to the AZ that has 2 nodes.

We didn't do this before. We placed 1 replica per AZ even when we removed a node.

**Comment by kmuthukk** [comment]
@rao-vasireddy --

What was the `/cluster-config` before and after?

Could this new with #5426 ?

**Comment by bmatican** [comment]
I was also thinking that too @kmuthukk , but at least the current config is ok
```
  live_replicas {
    num_replicas: 3
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2a"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2c"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2b"
      }
      min_num_replicas: 1
    }
    placement_uuid: "e254a48e-668d-415e-9d1f-103a26ee691a"
  }

```

**Comment by rao-vasireddy** [comment]
Cluster config after the node was removed -

version: 12
replication_info {
  live_replicas {
    num_replicas: 3
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2a"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2c"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2b"
      }
      min_num_replicas: 1
    }
    placement_uuid: "e254a48e-668d-415e-9d1f-103a26ee691a"
  }
  affinitized_leaders {
    placement_cloud: "aws"
    placement_region: "us-west-2"
    placement_zone: "us-west-2a"
  }
  affinitized_leaders {
    placement_cloud: "aws"
    placement_region: "us-west-2"
    placement_zone: "us-west-2c"
  }
  affinitized_leaders {
    placement_cloud: "aws"
    placement_region: "us-west-2"
    placement_zone: "us-west-2b"
  }
}
server_blacklist {
  hosts {
    host: "172.151.27.89"
    port: 9100
  }
  initial_replica_load: 76
}
cluster_uuid: "c328d6f2-f9db-46b3-ae4b-00ded0a6aa91"

**Comment by daniel-yb** [comment]
> @rao-vasireddy --
> 
> What was the `/cluster-config` before and after?
> 
> Could this new with #5426 ?

Based on the cluster config provided above + the steps @rao-vasireddy took to remove the node from the cluster, I'm pretty confident that this is not related to #5426. The code path I modified will only be executed when going through the create/edit universe flows. Not through removing a node from the nodes tab of a universe (although maybe we should re-calculate the min_num_replicas in this flow too for consistency).

**Comment by rao-vasireddy** [comment]
@bmatican , Can you pls confirm if this is new behavior or we always did it this way?

**Comment by bmatican** [comment]
Anubhav, I was doing some backlog triage, could you check if this is related to the other issue you were working on, with peers not respecting cluster config?

**Comment by SrivastavaAnubhav** [comment]
@bmatican I haven't tested this, but I don't think this is related to the other issue (#14233).

The other issue was a result of not checking whether we were moving to a TS that matches some placement block (because we mistakenly did not pass in any placement info). In this issue, even if we have the placement info, the other TS would match a placement block so we would be able to move the tablet replica to the other TS.

Is this expected? Or should the load balancer avoid moving replicas off of a blacklisted node if doing so would make the tablet under-replicated in a zone?
