### ISSUE TITLE
yugabytedb on ubuntu - python interpreter not found

### ISSUE THREAD

**Issue by curx** [yugabyte/yugabyte-db#6143]
I've tested the [training prepare step](https://github.com/yugabyte/yugabyte-db/wiki/YugabyteDB-Fundamentals-Training-Preparation-and-FAQ) on a fresh Ubuntu 18.04 LTS VM

Since Ubuntu ships python version 3 there's no `python` but a `python3`

```bash=
root@yb0:/opt/yugabyte-2.3.0.0# ./bin/yugabyted 
/usr/bin/env: ‘python’: No such file or directory
```

**Comment by curx** [comment]
as a workaround/fix:

```bash=
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
```

**Comment by curx** [comment]
maybe worth for documentation, are there any hints for Ubuntu setups?

**Comment by ddorian** [comment]
@curx 

I'm extremely sure Ubuntu 18.04 **HAS** `python`. 
Actually, **the OS breaks if `python2.7` is removed**.
```
$ which python
/usr/bin/python
```
You probably have something broken. Try: 
```
/usr/bin/python --version
```

**Comment by ddorian** [comment]
@curx please reopen the issue if the problem persists.
Python is included by default in ubuntu 18.04, many important system utilities require it actually.

**Comment by SoumyaDY96** [comment]
You can edit the daemon file **bin/yugabyted** under the installation directory **yugabyte-2.21.0.0/**, and change the interpreter from **#!/usr/bin/env python** to **#!/usr/bin/python3**

**Comment by mraible** [comment]
> You can edit the daemon file bin/yugabyted under the installation directory yugabyte-2.21.0.0/, and change the interpreter from #!/usr/bin/env python to #!/usr/bin/python3

This fix works on macOS too.
