### ISSUE TITLE
[YSQL] Partitioned table primary key is not correctly inherited by partitions

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#6149]
#### Create a partitioned table with a defined primary key
Using an explicitly-declared multi-column hash key for a clearer example.

```
CREATE TABLE person (
    person_id         int not null,
    country           text,
    name  text,
    age int,
    PRIMARY KEY((person_id, country) HASH)) 
PARTITION BY LIST (country);
```

#### Now create a partition for it
```
CREATE TABLE person_americas 
    PARTITION OF person
    FOR VALUES IN ('United States', 'Brazil', 'Mexico', 'Columbia');
```

#### Check the YSQL schema of the partition
```
yugabyte=# \d person_americas;
            Table "public.person_americas"
  Column   |  Type   | Collation | Nullable | Default
-----------+---------+-----------+----------+---------
 person_id | integer |           | not null |
 country   | text    |           | not null |
 name      | text    |           |          |
 age       | integer |           |          |
Partition of: person FOR VALUES IN ('United States', 'Brazil', 'Mexico', 'Columbia')
Indexes:
    "person_americas_pkey" PRIMARY KEY, lsm (person_id HASH, country)
```
The primary key is `(person_id HASH, country)` instead of `(person_id, country) HASH))` -- the hash-partition choice was lost.

#### Check the DocDB schema for the partition's the associated table
![image](https://user-images.githubusercontent.com/4038003/97131467-8a710180-1701-11eb-87e9-b62caa41fd54.png)
As seen above, the DocDB table has a (auto-generated) rowid column. 
That only happens for tables without an explicitly-declared primary key.

### Workaround
The workaround (for now) is to not define a primary key on the main (partitioned) table.
Instead create the appropriate primary key on each of the partition tables.

#### Create the tables
```
CREATE TABLE person2 (
    person_id         int not null,
    country           text,
    name  text,
    age int) 
PARTITION BY LIST (country);


CREATE TABLE person_americas2 
    PARTITION OF person2 (person_id, country, name, age, 
                         primary key((person_id, country) HASH)) 
    FOR VALUES IN ('United States', 'Brazil', 'Mexico', 'Columbia');
```

#### Check the YSQL schema
```
yugabyte=# \d person_americas2;
           Table "public.person_americas2"
  Column   |  Type   | Collation | Nullable | Default
-----------+---------+-----------+----------+---------
 person_id | integer |           | not null |
 country   | text    |           | not null |
 name      | text    |           |          |
 age       | integer |           |          |
Partition of: person2 FOR VALUES IN ('United States', 'Brazil', 'Mexico', 'Columbia')
Indexes:
    "person_americas2_pkey" PRIMARY KEY, lsm ((person_id, country) HASH)
```

#### Check the DocDB schema

![image](https://user-images.githubusercontent.com/4038003/97131747-331f6100-1702-11eb-8d9f-aacd7eaf9671.png)

Now there is not rowid column and both country and person_id are correctly marked as partition keys.

**Comment by tedyu** [comment]
In DefineRelation of src/postgres/src/backend/commands/tablecmds.c, I attempted this 
```
	if (IsYugaByteEnabled())
	{
		CheckIsYBSupportedRelationByKind(relkind);
		bool parentHasPrimaryKey = false;
		if (stmt->partbound) {
			Oid parentId = linitial_oid(inheritOids);
			/* Already have strong enough lock on the parent */
			Relation parent = heap_open(parentId, NoLock);
			parentHasPrimaryKey = OidIsValid(parent->rd_pkindex);
			elog(LOG, "parent primary %d", parentHasPrimaryKey);
			heap_close(parent, NoLock);
		}
		YBCCreateTable(stmt, relkind, descriptor, relationId, namespaceId, tablegroupId, parentHasPrimaryKey);
	}
```
where I check whether the parent relation has primary key.
However, parentHasPrimaryKey in the log showed false (0).

**Comment by tedyu** [comment]
Later in DefineRelation():
```
	 * If we're creating a partition, create now all the indexes, triggers,
	 * FKs defined in the parent.
	 *
	 * We can't do it earlier, because DefineIndex wants to know the partition
	 * key which we just stored.
	 */
	if (stmt->partbound)
```
It seems we can move the call to YBCCreateTable() after the above if block so that the YBSchemaBuilder::Build() method can get primary key information from parent index.

**Comment by deeps1991** [comment]
There are two bugs above:
1. The DocDB table gets created without a primary key.
2. The (person id, country) HASH option was lost, and was converted to person_id HASH, country.

The fix for (1) is ongoing.
(2) is already fixed indirectly by https://github.com/yugabyte/yugabyte-db/issues/1104
