### ISSUE TITLE
[Phase 2][YSQL] Create method to identify colocated database in system catalog

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#6159]
Jira Link: [[DB-387]](https://yugabyte.atlassian.net/browse/DB-387)
As a database user, it would be helpful to be able to identify which databases might be colocated from the system catalog. 
Currently the best way is query the tablet-server ui and look for colocated in the tablet definition, but this is unaccessible to the catalog and could be difficult to discern when using curl to examine the raw html. 
I suggest creating an entry in `pg_catalog.pg_tablespace` that identifies a container for that database. You can use spcoptions in that table to distinguish a tablegroup if necessary. This way the oid from pg_tablespace could be referenced in `dattablespace` in pg_catalog.pg_database.

[DB-387]: https://yugabyte.atlassian.net/browse/DB-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaki** [comment]
I'm not sure whether "tablegroup" was mentioned intentionally or you meant something else.

A database can affiliate itself with a tablespace.  It is a default value for all tables in the database (more specifically, tables that don't specify tablespace use `InvalidOid` to point to say, "I'm using the database default tablespace").

While this may sound like what we want, tablespaces have other uses.  For example, what if we wanted databases A and B to belong to a tablespace configured to be located in the americas geo but database A is colocated?  We'd have to create two different tablespaces, one with some option saying its colocated, another without.

You could argue that we have this issue anyway when mixing other options like americas geo and high/low memory.  Fair, but we have decided that tablespaces will be more about placement configuration while **tablegroups** will be about data layout.  Colocation existed before tablegroups.  Tablegroups have a colocation option (the only option presently).  Tablegroups are a better choice and easier to get information out of from system catalog.

The ideal solution is to migrate out of colocation to tablegroups.  That could take a while, but I don't think it's a good idea to use tablespaces here.  One idea we discussed before is adding a column to `pg_database`, but that is a backwards incompatible change (wants initdb upgrade).  The more moderate idea is to add an option to `pg_database`(`datacl` column, I believe).

**Comment by bllewell** [comment]
I propose generalizing the statement of requirement to honor this principle:

> It must be possible to see the value of _every_ object property, _every_ property of the YugabyteDB system as a whole, and _every_ property of current sessions, where the property can be set by a suitably privileged user by executing a catalog query as a suitably privileged user.

There are respected precedents that govern who can change what and who can see what. For example (and stating this fairly loosely), if user _“u1”_ doesn’t have the privilege to alter a property of an object owned by user _“u2”_ (or at least to use that object), then _“u1”_ should not be able to see the value of that property.

**Comment by frozenspider** [comment]
Note that now we have `yb_is_database_colocated()` and `yb_table_properties(oid)` YSQL functions implemented in the scope of #9665 which can be used to determine a colocation status of current DB/given table, as well as the tablegroup OID.
I'm not closing the ticket though, since the original issue (colocation state of a _given_ DB) is NYI.

**Comment by tverona1** [comment]
As Alex describes above, this is already supported for both colocated databases (via `yb_is_database_colocated()`) as well as tablegroups (via `yb_table_properties(oid)`). Unless there's a specific customer request to add support for `yb_is_database_colocated(dboid)`, we're not planning to add support for this. Closing this issue as complete.
