### ISSUE TITLE
2DC Txns: Calculate Write Id for External Transactions at Apply Time

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#6169]
Currently, we use a increasing counter called write id to order writes on the same key within a given transaction. This is important for consistency, as all records in the same txn get assigned the same timestamp and we need to know which write came last. For local writes this is handled by a component called the transaction participant, but the p0 for 2dc txns will bypass the participant altogether. Therefore, we need to calculate write id at txn apply time when applying to regular rocksdb.

**Comment by bmatican** [comment]
Related to #5779
