### ISSUE TITLE
Master and Tablet servers should be run as services

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#6174]
Currently, we use cron jobs to start master and tserver processes. It would be better to use services, specifically systemd services where available. 

Systemd allows auto-restarts, starting with system start, and log management. We're using some of these features already, but it would put the control of services in the system-standard location.

**Comment by tylarb** [comment]
related issues.... #6556 #4123

**Comment by Tusheet10Goli** [comment]
The diff is our for review - https://phabricator.dev.yugabyte.com/D11869

**Comment by Tusheet10Goli** [comment]
The diff is out for review - https://phabricator.dev.yugabyte.com/D11869

**Comment by Tusheet10Goli** [comment]
Diff Landed - https://phabricator.dev.yugabyte.com/D12184

**Comment by Shekelme** [comment]
Sorry, but I can't open https://phabricator.dev.yugabyte.com/D12184
