### ISSUE TITLE
Document explore steps using yugabyted

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6187]
The current docs at https://docs.yugabyte.com/latest/explore/ use yb-ctl. The goal would be to generate equivalent commands for these yb-ctl commands using yugabyted instead. The blog post at https://blog.yugabyte.com/introducing-yugabyted-the-simplest-way-to-get-started-with-yugabytedb/ might be useful.

**Comment by lizayugabyte** [comment]
@iSignal @baba230896 Does PR https://github.com/yugabyte/yugabyte-db/pull/6485 provide fix for this issue? If so, perhaps the PR should be merged and the issue closed as "done" ?

**Comment by baba230896** [comment]
@lizayugabyte Yeah, the mentioned PR is a fix for this issue. I've resolved the merge conflicts & added you as a reviewer. Please take a look at it whenever you've time.

**Comment by bhavin192** [comment]
AFAIK Karthik was also working on something similar that's why we created that PR with whatever we had. cc @iSignal

**Comment by polarweasel** [comment]
This issue should remain open until both #6485 and #8678 are merged.

**Comment by polarweasel** [comment]
Reopening to catch the changes from #6485
