### ISSUE TITLE
[YW] Typing in Universe name in Create Universe errors on non-existent name

### ISSUE THREAD

**Issue by yb-andrew** [yugabyte/yugabyte-db#6200]
On a YW with no universes, navigate to the Create Universe page and try to type in a universe name. User states that it occurs intermittently. Hitting refresh on the page fixes the issue.

![image (2)](https://user-images.githubusercontent.com/50115930/97524094-0c129a80-1961-11eb-9023-7c8a848673a2.png)

**Comment by rajmaddy89** [comment]
Can you please assign this issue to me ?

**Comment by rajmaddy89** [comment]
@hsiaosu-yb or @yb-andrew : I have been trying various things but never able to reproduce this issue even interminietly

Also tried creating a universe and then deleting it.
Now again trying to create universe with same name. I tried couple of these scenarios, but never succeed in reproducing it, may be its not happening no longer.

**Comment by yb-andrew** [comment]
Sure, let's close this bug. We can re-open if it occurs again.
