### ISSUE TITLE
Postgresql missing features for Ruby on Rails apps

### ISSUE THREAD

**Issue by robly** [yugabyte/yugabyte-db#621]
Caused by:
PG::FeatureNotSupported: ERROR:  SET SESSION variable not supported yet
LINE 1: SET SESSION timezone TO 'UTC'
        ^
HINT:  Please contact YugaByte for its release schedule.

**Comment by mysticaltech** [comment]
Would be very much needed indeed.

**Comment by m-iancu** [comment]
This was done in commit https://github.com/yugabyte/yugabyte-db/commit/816d2e4e9907de69428dd9678437d9ddb7dc5fcb.
See also issue #699.
