### ISSUE TITLE
[platform]Poor visual feedback when processes are stopped/started in the Nodes page

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6213]
No visual feedback to the user when processes are in the being stopped -or- started.
- When processes are stopped,  t-server/master processes are still shown as "running" (green check mark); status should change to being stopped. Since there is no task created, user has no idea whether their request went through. In my case, I ended up selecting stop processes multiple times.
- Same for when you're starting processes, status should change to "starting" and not down

**Comment by mjoshi0923** [comment]
Here is the diff https://phabricator.dev.yugabyte.com/D10756
