### ISSUE TITLE
[Platform] Provide an option to retry creating a universe after it fails.

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#6229]
This way the user doesn't have to go thru the process of selecting and entering all the values again

**Comment by chirag-yb** [comment]
@streddy-yb Is this addressed by the "Retry Task" that was added as part of the pre-flight checks?

**Comment by chirag-yb** [comment]
This will be fixed with https://github.com/yugabyte/yugabyte-db/issues/6016
