### ISSUE TITLE
[Platform] Add tooltips to KMS Configuration UI

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#6230]
There are some fields in the UI (specifically for AWS KMS config) that could use some tooltips explaining what they mean/do since setting certain fields makes other fields redundant/change what creating the configuration will do.

**Comment by streddy-yb** [comment]
hi @chirag-yb - can you provide the content for the tooltips?

**Comment by streddy-yb** [comment]
hi @daniel-yb - can you also provide input on equinix provider specific tooltips?

**Comment by daniel-yb** [comment]
@streddy-yb the equinix tooltips should be pretty straight forward. Both fields here are required, the first field is API URL which has three options: api.amer.smartkey.io, api.eu.smartkey.io, api.uk.smartkey.io. You basically want to use whichever of these API endpoints you are physically closest to although it will still work whichever one a customer uses (source: https://developer.equinix.com/catalog/smartkeyv1). The second field is the API key for the smartkey account such that we can make API requests against their services.

We should focus on adding tooltips for AWS KMS though IMO, this is the KMS configuration that has a lot more nuances/options to it.

**Comment by daniel-yb** [comment]
Here is some notes on the AWS KMS Configuration options.

<img width="1001" alt="Screen Shot 2021-01-14 at 11 46 04 AM" src="https://user-images.githubusercontent.com/54864769/104641655-e98a4680-565e-11eb-81f2-13fc3b30c199.png">

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6916

**Comment by chirag-yb** [comment]
@daniel-yb @nishantSharma459 Tool tips - 

Configuration Name - The name of the KMS configuration (Required)
Use IAM Profile - Select to use an IAM profile attached to an EC2 instance running the platform 
Access Key Id - Enter your AWS access key ID
Secret Key Id - Enter your AWS access key secret
Region - Select the AWS region where the customer master key is located.
Customer Master Key ID  - Enter the identifier for the customer master key. If an identifier is not entered, a CMK ID will be auto-generated
