### ISSUE TITLE
AMI Rehydration with zero downtime and zero data loss

### ISSUE THREAD

**Issue by Ashish-Prasad-Gupta** [YugaByte/yugabyte-db#624]
We would like to verify the documented procedure of rehydrating a N node cluster running a version of AMI with another version of AMI with zero data loss yet high availability being guaranteed while the traffic is gradually moved from the nodes on the old cluster to the nodes on the new cluster. Also, assess the overall duration it take for complete rehydration.

**Comment by bbaddepudi** [comment]
Quick update that the steps have been internally documented and validated, will work on putting it up at https://docs.yugabyte.com/

**Comment by kmuthukk** [comment]
hi @Ashish-Prasad-Gupta 

Please see the documentation for an online full move to a new set of machines here: https://docs.yugabyte.com/latest/manage/full-move/.

There might be other options for AMI changes as well that are lighter weight than full move if the IP address/hostname of the machine is going to be the same after the change to the AMI. Perhaps that's another option to consider.
