### ISSUE TITLE
Zabbix installed with yugabyte not work well

### ISSUE THREAD

**Issue by iswarezwp** [yugabyte/yugabyte-db#6244]
Yugabyte tserver cannot start after a reboot， the error message：
```
F20201102 02:14:26 ../../src/yb/consensus/replica_state.cc:847] Check failed: pending_operations_.front()->id().index() == last_committed_op_id_.index + 1 (9 vs. 8)
    @     0x7f5e5f78cccc  yb::LogFatalHandlerSink::send()
    @     0x7f5e5e971376  google::LogMessage::SendToLog()
    @     0x7f5e5e96e7da  google::LogMessage::Flush()
    @     0x7f5e5e9718a9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5e67d3c95b  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x7f5e67d22b13  yb::consensus::RaftConsensus::EarlyCommitUnlocked()
    @     0x7f5e67d28144  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x7f5e67d29113  yb::consensus::RaftConsensus::Update()
    @     0x7f5e689ca731  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x7f5e651ff08a  yb::consensus::ConsensusServiceIf::Handle()
    @     0x7f5e60feb369  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f5e60f91de4  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f5e60ffd9d8  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f5e5f82442f  yb::Thread::SuperviseThread()
    @     0x7f5e5a044694  start_thread
    @     0x7f5e5978141d  __clone
    @              (nil)  (unknown)
```
The Yugabyte version is 2.3.3

**Comment by ddorian** [comment]
@iswarezwp and if you remove `zabbiz` and restart, does it work ?

**Comment by iswarezwp** [comment]
@ddorian I load the zabbix database into a fresh installed yugabyte cluster throw zabbix's `create-zabbix.sql` script，and then restart yugabyte, the problem remains.

**Comment by ddorian** [comment]
> ~20000 tablets over the 3 nodes

Yes. Can you try again with a [colocated database](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_database/#colocated) ?

**Comment by iswarezwp** [comment]
colocated database is ok.

**Comment by ddorian** [comment]
@iswarezwp closing as fixed ?

Another way is to use https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#yb-num-shards-per-tserver
Another one is to change the CREATE TABLE/INDEX statements by including the number of tablets https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_table/#split-into

**Comment by mbautin** [comment]
Hi @iswarezwp, is there any chance you might still have tablet server logs from around the time when this "Check failed" error happened? It would be useful for us to analyze.

**Comment by iswarezwp** [comment]
@mbautin Sorry for the late reply, the origin env is destroyed and re-installed with colocated database. I will create 3 new vms and try to reproduce it.
