### ISSUE TITLE
Master leader doesn't give up its role with expired lease or never acquires valid lease after role change

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#6248]
Jira Link: [DB-2338](https://yugabyte.atlassian.net/browse/DB-2338)
There seems to be a condition where a leader has a lease and then it expires, but it does not cede control to another peer.

Example:
```
yb-master-0:
I1029 11:14:31.899539    38 sys_catalog.cc:375] T 00000000000000000000000000000000 P 819d2b777ebf41f2a6deff3bfdee5e09 [sys.catalog]: This master's current role is: FOLLOWER
yb-master-1:
I1029 11:14:16.089485   740 sys_catalog.cc:375] T 00000000000000000000000000000000 P 96917a923dac4172b3d576159dacae2b [sys.catalog]: This master's current role is: LEADER
I1029 11:14:19.496482   744 replica_state.cc:1300] T 00000000000000000000000000000000 P 96917a923dac4172b3d576159dacae2b [term 15 LEADER]: Revoked old leader d9d0b751df44490f9542d2c7cff32769 ht lease: { physical: 1603970045789953 }
yb-master-2:
I1029 11:14:19.990581  3335 sys_catalog.cc:375] T 00000000000000000000000000000000 P d9d0b751df44490f9542d2c7cff32769 [sys.catalog]: This master's current role is: FOLLOWER
```
Messages seen on yb-master-1:
I1102 06:09:47.131229   615 master_service.cc:632] Patching role from leader to follower because of: Leader does not have a valid lease. (yb/consensus/consensus.cc:164): This leader has not yet acquired a lease. [suppressed 1 similar messages]

I see additional messages in yb-master-1 that indicate that a lease has not been acquired. This leads to problems later when system catalog entries are trying to acquired on 11/02.

**Comment by ajcaldera1** [comment]
Log files:
[yb-master-0.INFO.log.gz](https://github.com/yugabyte/yugabyte-db/files/5477570/yb-master-0.INFO.log.gz)
[yb-master-1.INFO.log.gz](https://github.com/yugabyte/yugabyte-db/files/5477571/yb-master-1.INFO.log.gz)
[yb-master-2.INFO.log.gz](https://github.com/yugabyte/yugabyte-db/files/5477573/yb-master-2.INFO.log.gz)

**Comment by bmatican** [comment]
Cleaning old issues. This was addressed by Sergei, with an added check on RPCs to downgrade the role returned.
