### ISSUE TITLE
[YCQL] Allow for create index to not wait for the backfill to complete

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#6253]
Jira Link: [DB-4658](https://yugabyte.atlassian.net/browse/DB-4658)
Create index, currently returns an error -- Timeout, if we are unable to backfill the index table within the client given timeout.

We should be returning success instead, because the CQL expectation is that backfill will be done asynchronously. https://cassandra.apache.org/doc/latest/cql/indexes.html

**Comment by rao-vasireddy** [comment]
Should we have a different message than Success? Success may imply the task has finished. If the task is still in progress, then we should just say succesfully started. Thoughts?

**Comment by amitanandaiyer** [comment]
We can return OK or non-OK. Non-OK messages are treated as a failure. 

So it would be better to add an option -- which, if set, we will not wait for the Backfill to complete and will return OK as soon as the index table is created, without waiting on the backfill.

CQL doesn't expect the backfill to complete so this should be ok. YSQL needs to wait for the backfill to complete -- that can be handled as is, as this change will not affect that path.
