### ISSUE TITLE
[YSQL] DROP EXTENSION Doesn't stop PGAudit

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#6255]
Jira Link: [DB-1602](https://yugabyte.atlassian.net/browse/DB-1602)
- Build # 2.3.3 # B121

Setup PGAudit in a YSQLSH session

CREATE EXTENSION IF NOT EXISTS pgaudit;
SET pgaudit.log='';
SET pgaudit.log='DDL';
SET pgaudit.log_level=notice;
SET pgaudit.log_statement_once=ON;
<Execute DDL-1>.
DROP EXTENSION  pgaudit;
<Execute DDL-2>.

DDL-2 should not be added to Audit log

**Comment by ramsrivatsa** [comment]
[Postgres Drop Extension link](https://github.com/pgaudit/pgaudit/blob/5096e75f1aa6635c3d0e203254c4ef7eae9d3087/expected/pgaudit.out#L1146)
If we observer following the `DROP extension pgaudit` on vanilla postgres's extension, DDLs are not logged but inserts and other statements are logged. This is vannila postgres' execution behavior and we are reproducing the same behavior in YB for audit logging.

**Comment by sushantrmishra** [comment]
Not reproducible in 2.15.3. 


```
select version();

        version

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
------------------------
 PostgreSQL 11.2-YB-2.15.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (/opt/yb-build/llvm/y
b-llvm-v13.0.1-yb-2-1659058819-0131d8e1-centos7-x86_64-build/src/llvm-project/clang 0131d8e1a20f72a0f374979985
db4c2871be71bc), 64-bit
(1 row)
```
When `pg_audit` was enabled following appeared in the logs `create table t2 ( a int);` .

```
I0905 18:26:43.603024  4814 ybccmds.c:491] Creating Table yugabyte.public.t2
2022-09-05 18:26:44.293 UTC [4814] LOG:  AUDIT: SESSION,1,1,DDL,CREATE TABLE,TABLE,public.t2,create table t2 (
 a int);,<not logged>
```


drop the extension and launch  a new session to create table . 

`I0905 18:27:39.227159  5097 ybccmds.c:491] Creating Table yugabyte.public.t6
`
