### ISSUE TITLE
undefined reference to ldap_init: Compilation error on centos

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6262]
From https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-phabricator/62725/consoleText :

Compiler exit code: 1.\n\x1b[0m\n\x1b[0;31m/-------------------------------------------------------------------------------\n| COMPILATION FAILED\n|-------------------------------------------------------------------------------\nbuild/debug-gcc-dynamic-ninja/postgres_build/src/interfaces/libpq/libpq.a(fe-connect.o): In function `ldapServiceLookup\':
/nfusr/centos-gcp-cloud/jenkins-worker-e71/jenkins/jenkins-github-yugabyte-db-phabricator-62725/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-connect.c:4278: undefined reference to `ldap_init\'
/nfusr/centos-gcp-cloud/jenkins-worker-e71/jenkins/jenkins-github-yugabyte-db-phabricator-62725/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-connect.c:4309: undefined reference to `ldap_set_option\'\n/nfusr/centos-gcp-cloud/jenkins-worker-e71/jenkins/jenkins-github-yugabyte-db-phabricator-62725/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-connect.c:4312: undefined reference to `ldap_unbind\'\n/nfusr/centos-gcp-cloud/jenkins-worker-e71/jenkins/jenkins-github-yugabyte-db-phabricator-62725/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-connect.c:4317: undefined reference to `ldap_simple_bind\'\n/nfusr/centos-gcp-cloud/jenkins-worker-e71/jenkins/jenkins-github-yugabyte-db-phabricator-62725/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-connect.c:4321: undefined reference to `ldap_unbind\'\n/nfusr/centos-gcp-cloud/jenkins-worker-e71/jenkins/jenkins-github-yugabyte-db-phabricator-62725/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-connect.c:4327: undefined reference to `ldap_result\'\n/

**Comment by jaki** [comment]
Looks ldap related.  Did you clean build?  `thirdparty` submodule was updated recently.

**Comment by tedyu** [comment]
The above was from Jenkins.

It seems the build script may need some change.

**Comment by svarnau** [comment]
All the other build flavors built okay. I suspect there might have been a glitch downloading the thirdparty dependencies to the build-server host. Updating the build-server image to have the latest thirdparty dependencies pre-installed should help.

**Comment by svarnau** [comment]
Build worker image has been updated.
