### ISSUE TITLE
[PLATFORM UI] Add node task failed on 2.5.0.0 - B1 build

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#6277]
Update universe for adding nodes by increasing counts in AZ nodes panel (right top corner) failed with "Failed to execute task java.util.concurrent.FutureTask@109e9a81, hit error java.lang.RuntimeException: WaitForLeadersOnPreferredOnly(7ae18705-8d3b-4a4a-af63-6ea2c87d5671) did not complete.." error (http://portal.dev.yugabyte.com/tasks/e01eec23-4a9e-4430-96b1-08af051b5b13) 
<img width="1792" alt="Screen Shot 2020-11-04 at 10 25 40 AM" src="https://user-images.githubusercontent.com/67607029/98153553-3c3dca00-1e88-11eb-9f3f-5f5123b50270.png">

**Comment by streddy-yb** [comment]
@nmantrav2 - Are you still seeing this issue? This scenario works fine in the latest builds.

**Comment by streddy-yb** [comment]
Closing this for now.
