### ISSUE TITLE
Allow using both --memory_limit_hard_bytes and --default_memory_limit_to_ram_ratio together

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#628]
Based on https://github.com/YugaByte/yugabyte-db/blob/efd44a194d887a47b91eca9a75ec55cda598227e/src/yb/util/mem_tracker.cc#L235

we should allow for a use case where we can specify total amount of memory allocated, as well as a hard  limit percentage, to be able to better cover issues such as #627.

**Comment by kmuthukk** [comment]
We can move the multiplication by FLAGS_default_memory_limit_to_ram_ratio to outside the `if` block.

That is, change the following from:
```
  int64_t limit = FLAGS_memory_limit_hard_bytes;
  if (limit == 0) {
    int64_t total_ram;
    CHECK_OK(Env::Default()->GetTotalRAMBytes(&total_ram));
    limit = total_ram * FLAGS_default_memory_limit_to_ram_ratio;
  }
```
to something like:
```
  int64_t limit = FLAGS_memory_limit_hard_bytes;
  if (limit == 0) {
    int64_t total_ram;
    CHECK_OK(Env::Default()->GetTotalRAMBytes(&total_ram));
    limit = total_ram;
  }
  limit = limit * FLAGS_default_memory_limit_to_ram_ratio;

```

**Comment by rahuldesirazu** [comment]
@bogdan @kmuthukk Is this still a relevant task?

**Comment by kmuthukk** [comment]
No - I think we decided to keep these gflags separate. 

If explicit value is provide, we just use it. Otherwise, it is computed as a ratio of RAM. Closing this task out (as I don't believe we are planning to do this change).
