### ISSUE TITLE
spark connector for yugabyte instance for local dev / testing

### ISSUE THREAD

**Issue by theincredibleguy** [YugaByte/yugabyte-db#63]
looking for connector that can spin up a local instance of yugabyte instance for testing and development purposes.

**Comment by kmuthukk** [comment]
Hi @theincredibleguy 

Can you try the following:

a) As one time steps, 

Install YugaByte software in a well known location, using the steps here:
    https://docs.yugabyte.com/quick-start/install/
For example, on Linux, to download the 0.9.5, versions you would do something like:

> % cd $HOME
> % wget https://downloads.yugabyte.com/yugabyte-ce-0.9.5.0-linux.tar.gz
> % tar xvfz yugabyte-ce-0.9.5.0-linux.tar.gz && cd yugabyte-0.9.5.0/
> %  $HOME/yugabyte-0.9.5.0/bin/post_install.sh


b) To launch the cluster with say replication factor of 1 (which me sufficient for unit test purposes):

> % $HOME/yugabyte-0.9.5.0/bin/yb-ctl --rf 1 create

c) At this point, you can check status of the cluster using:

> [centos@ip-10-9-123-137 yugabyte-0.9.5.0]$ $HOME/yugabyte-0.9.5.0/bin/yb-ctl status
> 2018-02-25 21:14:20,023 INFO: Server is running: type=master, node_id=1, PID=28035, admin service=http://127.0.0.1:7000
> 2018-02-25 21:14:20,029 INFO: Server is running: type=tserver, node_id=1, PID=28038, admin service=http://127.0.0.1:9000, cql service=127.0.0.1:9042, redis service=127.0.0.1:6379

d) As you can see above, the system is now listening for Cassandra/CQL requests at:

 127.0.0.1:9042

You should be able to use the above end point from the connector to test against this local YugaByte cluster.

d) To clean up/destroy any old state of the cluster, before starting a new test:

> % $HOME/yugabyte-0.9.5.0/bin/yb-ctl destroy

Let us know if the above works.

**Comment by rkarthik007** [comment]
The local cluster deployment that @kmuthukk talked about should be good for this, closing this issue out. Please reopen if you had any issues with the above.
