### ISSUE TITLE
[Platform] Create Universe does not validate encryption-at-rest configs exist

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#6320]
Users should not be able to create a universe if no certificate is selected after enabling encryption at rest. This can happen if users do not notice the dropdown or if the config itself doesn't exist.

**Comment by gaurav061** [comment]
PR:https://github.com/yugabyte/yugabyte-db/pull/6950

**Comment by chirag-yb** [comment]
Should this be closed?
