### ISSUE TITLE
Get record count timeout

### ISSUE THREAD

**Issue by VishalGupta04** [YugaByte/yugabyte-db#633]
Following query timeout when table has millions of records:
_SELECT COUNT(*) FROM <table_name>_

Is there a way to get records count for a table?

**Comment by kmuthukk** [comment]
Full table scans should be run with care on cluster. Normally, on massive tables, you would use [Spark](https://docs.yugabyte.com/latest/develop/ecosystem-integrations/apache-spark/) or [Presto](https://docs.yugabyte.com/latest/develop/ecosystem-integrations/presto/) on top of YugaByte DB if you want to do these queries that read a lot of data, but want to break it up into smaller/restartable units of work that are parallelizable.

@robertpang can help on:

a) how to adjust timeout...
b) also how to query a sample a subset of rows (based on the hash partition) and then extrapolate the results if approx count is sufficient.

**Comment by robertpang** [comment]
@VishalGupta04 For (a), by default cqlsh times out a request in 10 seconds. If you would like to execute a long query, you may specify a longer timeout when starting cqlsh from command-line like this before running the query in cqlsh:

```
> cqlsh --request-timeout <timeout-in-seconds>
```
Here is our documentation for your reference: https://docs.yugabyte.com/latest/develop/tools/cqlsh/#command-line-options

For (b), if an approximate count is sufficient, you may count just a subset of rows by the hash partition and extrapolate. For example, say you have a table with hash and clustering range columns like this:

```
cqlsh:k> create table t (h1 int, h2 int, r1 int, r2 int, v int, 
                         primary key ((h1, h2), r1, r2));
```

You may count a subset by a hash partition range (say 0 - 256):

```
cqlsh:k> select count(*) from t where partition_hash(h1, h2) >= 0 and
                                      partition_hash(h1, h2) < 256;
 count
-------
     ...
```

Given YugaByte DB's full hash partition value spans from 0 - 65535, the subset is only 1/256 of the total so you can multiply the sub-count by 256 to estimate the total count.

**Comment by ddorian** [comment]
You could run a per-partition query in parallel and sum the results .

**Comment by VishalGupta04** [comment]
Thanks @kmuthukk, @robertpang and @ddorian, I agree full table scan is not a good idea and intention here, I was running write tests so was just wanted to ensure that pushed data is actually inserted. I will try option (b) suggested by @robertpang as approximate count is what I am looking for right now. 
Out of curiosity, Yugabyte doesn't keep a count of records for user tables in some system table (like information_schema in MySQL).

**Comment by kmuthukk** [comment]
hi @VishalGupta04 

Most DBs do not keep a materialized count for the table.

For example:

1) https://www.percona.com/blog/2006/12/01/count-for-innodb-tables/ 

The older MyISAM storage engine of MySQL did, but the popular InnoDB engine for MySQL doesn't. As the article notes: <<< Innodb will however need to perform full table scan or full index scan because it does not have such counter, it also can’t be solved by simple singe counter for Innodb tables as different transactions may see different number of rows in the table. >>>

2) Here's a link on similar query for Oracle DB;

https://asktom.oracle.com/pls/apex/asktom.search?tag=select-count-on-a-billion-records-table

**Comment by VishalGupta04** [comment]
@kmuthukk Need to go through these links but we are using InnoDB engine and it keeps the count though it's not exact.

**Comment by kmuthukk** [comment]
Like MySQL/InnoDB or Oracle, YugaByte also doesn't keep a materialized count for the number of rows in the table. Primary reason is that it adds book-keeping overhead to the common code path. 

Additionally, upsert operations in YugaByte for example, often do not even need to perform a read. But if we had to maintain a materialized count of the number of rows in the table, we would need to know if the upsert operation ended up inserting a new row or updating an existing one. This in turn would incur a read penalty for a upsert operation.

**Comment by kmuthukk** [comment]
Ok.. for inexact count, I can imagine the YB doing some sample based count maintenance (like you have suggested that InnoDB might be doing). We are currently not doing that. But using the suggestion Robert had will work as an application level workaround...

**Comment by kmuthukk** [comment]
I will close the issue for now, but if the resolution is not satisfactory, feel free to reopen the issue with your thoughts.

**Comment by kmuthukk** [comment]
To increase server side defaults to handle longer requests:

The top level request timeout default is controlled by this yb-tserver gflag:

`--client_read_write_timeout_ms=60000`

but in addition, no single shard-level RPC should take more than this yb-tserver gflag:

`--retryable_rpc_single_call_timeout_ms=2500`

You can increase the above numbers to allow for requests to run longer.

**Comment by nvcnvn** [comment]
Hi team, can we do this inexact count in YSQL? seem *partition_hash* only available for YCQL?

**Comment by ddorian** [comment]
@nvcnvn this isn't currently available in YSQL.
