### ISSUE TITLE
[YSQL] Namespace missing in "YSQL All Ops" output

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6335]
_YSQL All Ops_ end point doesn't include table _namespace_ in the _statements_ output.

Example:
```
http://portal.dev.yugabyte.com/proxy/172.151.25.19:13000/statements

{
            "query": "SELECT k, v FROM sqlsecondaryindex WHERE v = $1",
            "calls": 19970733,
            "total_time": 83996802.88933613,
            "min_time": 0.7070460000000001,
            "max_time": 1896.2928510000002,
            "mean_time": 4.205994987230398,
            "stddev_time": 5.605967510591389,
            "rows": 19970733
        },
```

cc @m-iancu @yb-andrew @WesleyW

**Comment by m-iancu** [comment]
First, note that we use the DocDB term _namespace_ here to be API agnostic. For YSQL this corresponds to _database_ (in YCQL it would be keyspace).

The statements endpoint output is produced in `server/pgsql_webserver_wrapper.cc:DoWriteStatArrayElemToJson` using data read from `contrib/pg_stat_statements/pg_stat_statements.c:getYsqlStatementStats`.
I don't know if `getYsqlStatementStats` retrieves the results for all databases or just the current database.
First, we should verify that and then, depending on the answer we might need to either:
a. If we already have all databases check if identical queries from different dbs are kept separate. Then we need to figure out which db they belong to and add that field to the final output.
b. Else, iterate on (or inside) `getYsqlStatementStats` to get the stats for all databases and aggregate them (while adding the namespace/database field to the output)

**Comment by pkj415** [comment]
`getYsqlStatementStats` retrieves results for all databases. Also, for two identical queries on different databases, two separates stat entries are maintained.

So, we just have to populate the database's oid and name, which are already available (in the key to the hash table that stores the stats). I will raise a CR for this shortly after testing the change.

**Comment by pkj415** [comment]
Converged with @streddy-yb that we don't need this change. Platform uses pg_stat_statements view to get the db_id and later performs a join with pg_database to get the db_name. So, we need not populate this information on the /metrics page.

cc @m-iancu

**Comment by m-iancu** [comment]
Closing based on the comment above.
