### ISSUE TITLE
[YW] k8s universe upgrade does not wait for each pod to update before moving to the next

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6360]
itest identified an issue where pods were not updated properly after a k8s upgrade on a universe. The upgrade process is suppose to wait for each pod to update and come up properly before moving to the next - however this does not happen. In the happy path, it makes no difference but it can cause issues if there are any errors during the upgrade.

```
2020-11-12 00:31:04,403 test_upgrade.py:179 ERROR testupgrade-k8s-rf3 Wrong version in yb-tserver-0 at /home/yugabyte/master/version_metadata.json: found 2.0.9.0 but expected 2.5.0.0.
```

This is because 2 of the pods were still at an older version

```
Checking yb-tserver-0 version at /home/yugabyte/tserver/version_metadata.json
2020-11-12 00:29:29,665 test_upgrade.py:171 INFO testupgrade-k8s-rf3 Version data file content:
 {"build_id": "", "build_hostname": "scheduler.c.yugabyte.internal", "build_number": "13", "version_number": "2.0.9.0", "build_clean_repo": "true", "bui
ld_username": "centos", "build_timestamp": "23 Dec 2019 17:18:13 UTC", "git_hash": "4a2734dab6e2b1975a62310a8b97ac0ee5c1eb69", "build_type": "RELEASE"}
```

@Arnav15 identified this as a potential possibility when we removed the `--wait` flag from helm upgrade while moving to helm 3 in 346ad7aea08767cbbbfef78685485e73452dc3e8

**Comment by VijiYB** [comment]
Validated some flows like Upgrade k8s universe with increase in the num of nodes, instance type change(full move), upgradeGFlags
