### ISSUE TITLE
Core Dump Files Not Going to Correct Specified Home Dir

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#6367]
A customer has been running into some issues with core dump files not getting sent to the correct home dir which was set in the on prem provider. By default the home dir is set as /home/yugabyte but the customer changed it to /opt/yugabyte. However all the core files are still going to /home/yugabyte/cores and unfortunately they do not have a lot of space on disk for that dir. for now i’m going to use Bogdans suggestion of setting kernel.core_pattern to/opt/yugabyte/cores/core_%e.%p but ideally it would be great if the platform set this automatically.

**Comment by tsmull-11** [comment]
per @bmatican in the yb-server-ctl, we probably want to cd to ~/cores, in case the core_pattern was not set, that way when cores get generated in the PWD of the process, they show up in our cores dir.

**Comment by iSignal** [comment]
https://github.com/yugabyte/yugabyte-db/blob/0e80be229bc2c98cd031027b9b4396cee0ceba5b/managed/devops/roles/provision-cluster-server/tasks/main.yml#L65 is where we set the core pattern during the provision step when a VM is added to the universe.

**Comment by chirag-yb** [comment]
Not a bug. Missed setting the core file location while setting up the platform
