### ISSUE TITLE
Case sensitive column names not preserved in PK with ysql_dump

### ISSUE THREAD

**Issue by fitcs01** [yugabyte/yugabyte-db#6368]
CREATE TABLE table1 ( "UpperI" int, c char, PRIMARY KEY ("UpperI"));

table def in ysql_dump output:

--
-- Name: table1; Type: TABLE; Schema: public; Owner: yugabyte
--

CREATE TABLE public.table1 (
    "UpperI" integer NOT NULL,
    c character(1),
    PRIMARY KEY((UpperI) HASH)
);

table fails to create - any copy command then spews a load of errors ( if nulls then \N is sighted as the problem ) but this is due to table create failure.

**Comment by tedyu** [comment]
Have you seen #6061 ?

The column name would be correctly quoted for PRIMARY KEY with commit deae75833444d14ce4756814a9bae3bd9eced8ff

**Comment by ddorian** [comment]
Hi @fitcs01 

This issue has been fixed in 2.5.0.0.
Can you try that https://github.com/yugabyte/yugabyte-db/releases ?
