### ISSUE TITLE
[YW] Allow pausing universes

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#6373]
Ideally there would be a way to pause the instances associated with a universe. This would be particularly useful for clusters which have some data loaded for tpcc, where the data load is time consuming/expensive, but the cluster itself is only in use during periodic workload execution.

**Comment by nishantSharma459** [comment]
This has to be implemented from both sides(server and client).

**Comment by nishantSharma459** [comment]
This is under investigation. Will update the status ASAP.

**Comment by mahendranbhat** [comment]
We would be implementing the Pause universe same as deleting universe using DevOps code written in python.

**Comment by nishantSharma459** [comment]
Design discussion is pending from the front part of the application.

**Comment by nishantSharma459** [comment]
I've made the Front-end change and the code has been pushed to the respective branch where Back-end lies. I've asked the Back-end engineer to test the overall functionality. Once that is confirmed we'll perform Regression testing and then will raise a PR.

**Comment by mahendranbhat** [comment]
Making back end changes as discussed with @Arnav15 . Working of refactoring locking and unlocking of a task with the introduced new flag `universePaused`.

**Comment by mahendranbhat** [comment]
Working on the adding check to health check and scheduler API's when the universe is in a paused state.

**Comment by nishantSharma459** [comment]
Few more changes I would like to add from the front-end prespective:

1. Once Universe is paused, **all the related tasks like backups, alerts, etc** will be disabled until the Universe resumes.
2. Connect functionality will be disabled for the **Paused Universe.**
3. **Delete Universe** will stay as it is.

**Comment by mahendranbhat** [comment]
Currently, the delete functionality works for running instances 
need to update the yml file
```
filters:
      instance-state-name: "running"
      "tag:Name": "{{ instance_name }}"
```
