### ISSUE TITLE
Upgrade spark-cassandra-connector version to 2.4-yb-3

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6374]
2.4-yb-3 for spark-cassandra-connector has been released:
https://search.maven.org/artifact/com.yugabyte.spark/spark-cassandra-connector_2.11

This issue is to upgrade spark-cassandra-connector version to 2.4-yb-3

**Comment by m-iancu** [comment]
Fixed by 0b0230432c917575a21399e637481c659678c6cd.
