### ISSUE TITLE
[Platform] Add input path validation for backup target paths

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6382]

**Comment by SergeyPotachev** [comment]
Fixed API part. Needed additional fix on UI side. For minimum case - to hide the error message after it is appeared but later the storage type/tab is switched; for maximum case - to add the similar validations on UI for urls and for NFS path.

**Comment by streddy-yb** [comment]
- Verified that I cannot enter invalid paths in the UI `[example: tried entering  $(ping -c1 google.com >> /tmp/ping_log)tmp/some/nfs/dir as the NFS path`
- Also verified manually overriding NFS path to an invalid path and tried taking a backup
