### ISSUE TITLE
No visual feedback for cloud provider creation

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6392]
When a user adds a new AWS/GCP cloud provider there is a progress bar with certain steps related to region bootstrapping and creating access keys but it's not really indicative if a cloud provider was successfully created or failed. This information is available on the tasks page which can be easily missed.

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6948
