### ISSUE TITLE
"Use IAM role on instance" for creating an AWS cloud provider is not working

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6393]
Steps 

1. Create a platform instance (i3.xlarge) in AWS with an IAM role (make sure it has ec2 admin permissions)
2. Create a new AWS cloud provider and for credential type select - "Use IAM Role on instance."
3. For VPC, select "Create a new VPC" 
4. Add "US West 1" as a region and Save

Three issues observed in this workflow - 

1. For an IAM role without enough permission, it takes up to an hour for the tasks to fail. It seems we use error retries and exponential backoffs, which is delaying this task. 
2. For an appropriate IAM role task has been in progress for a few hours. It hasn't finished or timed out yet. Cloud provider configuration is running forever on the tasks page.
3. There is no visual feedback if a cloud provider was successfully added or failed [6392](https://github.com/yugabyte/yugabyte-db/issues/6392)

**Comment by iSignal** [comment]
To assume IAM credentials on the host, the botocore library makes the following request first to configure the Instance Metadata service.

```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/
```

The PUT request fails within the YW docker container but succeeds in the host outside.

Setting this config option for the instance metadata service 
```
aws ec2 modify-instance-metadata-options --instance-id i-NNNNNNN --http-put-response-hop-limit 3 --http-endpoint enabled --region us-west-2
```
allows this request to work as documented at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

We need to understand if we can make this work by default without the need for this manual config. https://stackoverflow.com/a/62326320/11875833 has some potential ideas.

**Comment by streddy-yb** [comment]
Additional info from Daniel:
```By default, the response to PUT requests has a response hop limit (time to live) of 1 at the IP protocol level. You can adjust the hop limit using the modify-instance-metadata-options command if you need to make it larger. For example, you might need a larger hop limit for backward compatibility with container services running on the instance```

**Comment by daniel-yb** [comment]
Amazon says they will support IMDSv1 indefinitely (this is the old instance metadata service that our code works with).

So it seems our two options here are:
1) Add documentation to tell customers to launch YW EC2 VMs using IMDSv1 + specify `metadata-options` when launching YB nodes to use IMDSv1.
2) Update our AWS SDKs to newer versions that support IMDSv2 (this should not require any other code changes says Amazon).

Summary of options from AWS here: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/configuring-instance-metadata-service.html#instance-metadata-transition-to-version-2

**Comment by streddy-yb** [comment]
hi @VijiYB @daniel-yb - can you provide the required documentation to Alex?

**Comment by lizayugabyte** [comment]
@streddy-yb Doesn't @daniel-yb 's comment from Jan 27 provide enough info? What are details are required?

**Comment by VijiYB** [comment]
@lizayugabyte 

Yes you can use whatever Daniel provided
1. Create IAM role with required access
2. You can attach IAM role for new EC2 instance on console
         On EC2 console => New Instance => Confirm Instance Details => Attach the IAM role and change Metadata hop limit as 3 as shown in the screenshot.
4. For existing platform instance, run 
          aws ec2 modify-instance-metadata-options --instance-id i-NNNNNNN --http-put-response-hop-limit 3 --http-endpoint enabled --region us-west-2
<img width="1005" alt="Screen Shot 2021-04-29 at 12 36 58 PM" src="https://user-images.githubusercontent.com/78048211/116609018-b8b9de80-a8e8-11eb-80ba-28070dc32f2e.png">

**Comment by lizayugabyte** [comment]
@chirag-yb Could you, please, let me know which doc contains these steps? (I searched our doc site, but didn't find anything)

**Comment by chirag-yb** [comment]
@lizayugabyte It will go here - https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws/#3-provision-an-instance-for-yugabyte-platform

Add an option step - If you are planning to use the IAM role for deploying the YugabyteDB universe in your AWS account then you need to attach an IAM role to the Yugabyte Platform VM in the EC2 tab. Follow these steps (include Viji's and Daniel's last comment)

Then add more information on this page - https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws/#credentials
> Attach an IAM role to the Yugabyte Platform VM in the EC2 tab.

Refer back to your new content as a pre-requisite
