### ISSUE TITLE
AWS Universe creation fails due to missing instance type

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6404]
Universe creation
Cloud provider - AWS
Regions - Oregon, Tokyo, N. Virginia
AZs automatically selected  - ap-northeast-1d, us-east-1e, us-west-2d

AWS universe creation failed with this error message

`Your requested instance type (c5.xlarge) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f.`

Expected outcome - 

Use the describe-instance-type-offerings AWS command and include filters for the Availability Zone and the instance type to confirm if an instance type is available for selected AZs. 

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-instance-type-not-supported-az-error/

This issue is not limited to AWS but also seen in GCP and Azure

**Comment by sb-yb** [comment]
@chirag-yb @streddy-yb 
Meta comment: *Expected outcome* suggests how to fix the issue and missing actual expected outcome all together. While that information valuable it should be in separate section and not shadow expected outcome :)

I can reverse engineer expected outcome here and have some more comments.  I think what you are looking for is early detection and present only allowed AZs once the instance is selected? Or Opposite present only instance types that are available in selected AZs? Or just disable submit button when there is such an impossible combination selected? Or accept the request but fail-fast without any UI treatment?

Finally based on my prior experience with similar feature, (do not recall which cloud provider aws or azure): In addition to unsupported instance type there are quota issues like it will run out of instances - unsupported vs unavailable. So suggested solution only goes half way AFAICT. This is especially true if you are looking for spot instance.

**Comment by streddy-yb** [comment]
Hi @sb-yb - Fair points. The scope of this issue is to only present instance types that are common across selected AZs.

**Comment by sb-yb** [comment]
@streddy-yb Got it - Ideally should be bidirectional - If I select instance type first then it should filers AZ list. Is that use case going to be less frequent? (i.e. people wanting certain instance type but do not care about az or even region in some cases)?

**Comment by sb-yb** [comment]
I think ideally we should be asking  for minimum number of AZ's you want - say **z**. 
And then present the instance types that satisfy this number of AZs.
once instance type is picked there should be list of specific AZs picked (At least **z**  and if possible **n** - where **n** is a replication factor)

**Comment by sb-yb** [comment]
Small design doc:
https://docs.google.com/document/d/1YXIjKHq_dQw2bfwfMm7f-8MUDXEXn9PNeYMtXy9ukeU/edit?usp=sharing

**Comment by chirag-yb** [comment]
Related UI ticket - https://github.com/yugabyte/yugabyte-db/issues/6708
