### ISSUE TITLE
[Platform] YW UI mixes configuration settings used for different types of backups

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#6409]
Scenario:
Take a clean configuration/database.

1. Fill NFS page with value "test". Save the configuration.
In database appears row with the next data:
 type   |      name      |    data
--------------------------------------------------------------- 
STORAGE  | NFS            | {"BACKUP_LOCATION":"test"}

2. Fill GCS settings with test values like:
GCS Bucket - test2 (notice that the initial value here was taken from the NFS backup page - test)
GCS Credentials - '{}'
Save the configuration.
In database appears row with the next data:
 type   |      name      |    data
--------------------------------------------------------------- 
STORAGE  | GCS            | {"BACKUP_LOCATION":"test2","GCS_CREDENTIALS_JSON":"{}"}

3. Fill Amazon S3 settings with test values like:
Access Key - 123
Access Secret - 456
S3 Bucket - test3 (notice that the initial value here was taken from the GCP backup page - test2)
S3 Bucket Host Base - www.google.com
Save the configuration.
In database appears row with the next data:
 type   |      name      |    data
--------------------------------------------------------------- 
STORAGE  | S3             | {"BACKUP_LOCATION":"test3","GCS_CREDENTIALS_JSON":"{}","AWS_ACCESS_KEY_ID":"123","AWS_SECRET_ACCESS_KEY":"456","AWS_HOST_BASE":"www.google.com"}

4. Delete the NFS configuration.
5. Add the NFS configuration with value "test4".
In database appears row with the next data:
 type   |      name      |    data
--------------------------------------------------------------- 
STORAGE  | NFS            | {"BACKUP_LOCATION":"test4","GCS_CREDENTIALS_JSON":"{}","AWS_ACCESS_KEY_ID":"123","AWS_SECRET_ACCESS_KEY":"456","AWS_HOST_BASE":"www.google.com"}

As we can see, settings are stacked into one JSON. GCS settings could appear for AWS configuration, AWS settings for NFS or Azure and vice versa.

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6796

**Comment by nishantSharma459** [comment]
@streddy-yb @SergeyPotachev @jaydeepkumara The component used for this ticket in the front-end is a **'Form Component'** because of that when we hit the **'Save Button'** regardless of any **'Active Tab'** we'll have all the **'Input value'** that we've filled.

To achieve the functionality as per this ticket we need to re-wamp the whole **'Component'**.
