### ISSUE TITLE
[Platform] Edit Universe fails silently in case when it has decommissioned node(s)

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#6421]
Steps to reproduce:
  1. Create universe with 4 nodes in 3 AZs and RF=3.
  2. Remove node with tserver only in zone with two nodes.
  3. Do 'Release Instance' for the same node.
      This node now is in the Decommissioned state.
  4. Start the Edit Universe procedure. Add node in another AZ (where is only one node exists).
  5. Press save.

Expected result: the update should start or it should show an error message.
Actual result: Nothing happens. There is only a message in YW logs:

_Hit error 400, message: {"error":"Cannot perform an edit operation on universe 72037945-837c-430d-93d0-a6705cbfd73b as it has nodes in one of [Removed, Stopped, Decommissioned] states."}_

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7078
Fix: Exact scenario wasn't reproduced however I handled the error by showing 
visual feedback in case of edit-universe submit.
