### ISSUE TITLE
[docdb] Unify tablet assignment into the load balancing code

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#6428]
Currently, we have code for tablet assignment in `CatalogManager` during the `CreateTable` code, which tries to cover for some of the expectations of the load balancer (eg: even out across nodes, respect placement, respect blacklist). But this is brittle and error prone in the future, as the LB complexity will increase. We should unify the code into the LB and maybe have it run instantly for newly created tables, to issue all the `CreateTablet` calls, like the `CatalogManager` does now inline.

Here's a bad example of what happens when a lot of tables get created in quick succession:
![image (7)](https://user-images.githubusercontent.com/395011/99736557-7065dd00-2a7b-11eb-8794-dd49ba116a86.png)

cc @rahuldesirazu @nspiegelberg

**Comment by sanketkedia** [comment]
Fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/c8e7c91e8321e40a1b1e5c11d5a31078f8c9eed6)
