### ISSUE TITLE
[docdb] Optimize GetTabletLocations calls for system.partitions query

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#6434]
We are doing this in a tight loop over tablets when handling system.partitions query in yb-master:

https://github.com/yugabyte/yugabyte-db/blob/48e926696abdf3e7c0500966b2044d97bcf1ae80/src/yb/master/yql_partitions_vtable.cc#L102

But each of those calls is pretty expensive, and does some things that are pretty wasteful. In particular this check to just print some warning every 100 times might not be needed in the case of system.partitions query:

https://github.com/yugabyte/yugabyte-db/blob/48e926696abdf3e7c0500966b2044d97bcf1ae80/src/yb/master/catalog_manager.cc#L7063

The GetReplicationFactorForTablet() in most cases, falls back to GetReplicationFactor for the cluster which doesn't even change for every tablet:

https://github.com/yugabyte/yugabyte-db/blob/48e926696abdf3e7c0500966b2044d97bcf1ae80/src/yb/master/catalog_manager.cc#L7484

But that function GetReplicationFactor() acquires a cluster_config_ read lock every time!
https://github.com/yugabyte/yugabyte-db/blob/48e926696abdf3e7c0500966b2044d97bcf1ae80/src/yb/master/catalog_manager.cc#L7469

My suggestion is that system.partitions loop call CatalogManager::GetTabletLocations with an extra argument like skip_replication_factor_check => true or something to simply by pass the RF check.

**Comment by bmatican** [comment]
Part of #6690
