### ISSUE TITLE
[YSQL] Query error: Given ybctid is not associated with any row in table

### ISSUE THREAD

**Issue by wumingyuan** [yugabyte/yugabyte-db#6435]
Version: 2.5.0.0, Repeat steps:
```sql
CREATE TABLE t(id INT, name CHARACTER(20), age INT, score INT, addr TEXT, des CHARACTER VARYING(100), phone CHARACTER VARYING(100), num INT, PRIMARY KEY (id ASC));
INSERT INTO t SELECT generate_series(1, 10000000), 'hi', random()*100::integer, random()*100::integer, 'Washington', 'name', '0001', random()*1010000::integer;
CREATE INDEX idx_age ON t(age);
```
```sql
SELECT * FROM t WHERE age = 20;
SELECT * FROM t WHERE age = 10;
SELECT * FROM t WHERE age = 5;
SELECT * FROM t WHERE age = 4;
SELECT * FROM t WHERE age = 2;   
SELECT * FROM t WHERE age = 1; 
```
At some values, the following error occurs, but not all values, so you need to try a few more sets of data, suggesting that some boundary handling may be problematic:
```
ERROR:  Query error: Given ybctid is not associated with any row in table.
```
No errors occurred when the number of data rows was less than 1 million.

**Comment by tedyu** [comment]
```
    if (!VERIFY_RESULT(table_iter_->HasNext())) {
      if (unknown_ybctid_allowed) {
        continue;
      } else {
        return STATUS(Corruption, "Given ybctid is not associated with any row in table");
```
Looking at DocRowwiseIterator::HasNext(), there are 10 places where false may be returned.
It would be helpful for debugging if more information is returned along with the bool.

**Comment by wumingyuan** [comment]
In my tests, I found that it had nothing to do with the second index on the AGE. Performing an exact query with some specific ID value will show no records, but with the index scan disabled, it can be queried.It's these ids that cause AGE errors, but it's not easy to find them.One approach is to find the ID that caused the AGE error, then use that ID to perform an index scan, and discover that the record is not found.
So, maybe there's something wrong with the docdb storage.

**Comment by jaki** [comment]
I built my cluster using `yb-ctl` `--tserver_flags "client_read_write_timeout_ms=900000"` because large selects would time out.  I got

```sql
SELECT * FROM t WHERE age = 20; -- ok
SELECT * FROM t WHERE age = 10; -- fail
SELECT * FROM t WHERE age = 5; -- fail
SELECT * FROM t WHERE age = 4; -- ok
SELECT * FROM t WHERE age = 2; -- fail
SELECT * FROM t WHERE age = 1; -- fail
```

Trying `with w as (select age from t order by age) select count(*) from w;`, I got the correct count `10000000`, so this suggests that the data is there and either

- the data is incorrectly referencing the wrong primary key (I don't think so since it says "ybctid")
- the query logic has a bug

**Comment by jaki** [comment]
Here's a smaller repro:

```sql
create table c (i int, j int, primary key (i asc));
create index on c (j);
insert into c values (generate_series(1, 1000000), generate_series(1, 1000000) % 100);
select * from c where j = 5;
```

Confirmed this at least 3 times.  Index backfill enabled/disabled doesn't matter.  `create index` before or after inserts doesn't matter.

**Comment by wumingyuan** [comment]
> Here's a smaller repro:
> 
> ```sql
> create table c (i int, j int, primary key (i asc));
> create index on c (j);
> insert into c values (generate_series(1, 1000000), generate_series(1, 1000000) % 100);
> select * from c where j = 5;
> ```
> 
> Confirmed this at least 3 times. Index backfill enabled/disabled doesn't matter. `create index` before or after inserts doesn't matter.

This is a good example. When J is a multiple of 5, an error is reported, but 55 is an exception.

**Comment by jaki** [comment]
IndexOnlyScan does not have issues (`select j from c where j = 5`).

Another smaller one:

```sql
create table h2 (i int, j int, primary key (i asc));
create index on h2 (j);
insert into h2 values (generate_series(1, 256 * 2048), generate_series(1, 256 * 2048) % 256);
select * from h2 where j = 29;
```

Running `select i from c where j = 5`:

```
W1124 17:57:50.794349 25741 pgsql_operation.cc:798] ExecuteBatchYbctid batch arg: order: 4918
ybctid {
  value {
    binary_value: "H\200\007\201\035!"
  }
}
```

Running `select i from h2 where j = 29`:

```
W1124 18:01:02.730479 25741 pgsql_operation.cc:798] ExecuteBatchYbctid batch arg: order: 1921
ybctid {
  value {
    binary_value: "H\200\007\201\035!"
  }
}
```

Running `select count(i) from h2 where j = 51`:

```
W1124 18:07:41.973961 25740 pgsql_operation.cc:798] ExecuteBatchYbctid batch arg: order: 1494
ybctid {
  value {
    binary_value: "H\200\005\3263!"
  }
}
```

`sst_dump` gave me

```
'472A57488000001D2153488005811D210000214A802380019F5997013190800FAB5EAD' @ 1125899907015947: 1 => 2380019F5998433506803E0B24
```

and

```
'47512248800000332153488005D633210000214A802380019F5997013190800FA6420D' @ 1125899907026416: 1 => 2380019F5998193545803C4B24
```

matching the last two.  I think the docdb data and request queries are okay.  The iterator is likely the issue.

**Comment by tedyu** [comment]
For j = 5 and j = 29, the binary_value of ybctid is the same.
Is this coincidence ?

**Comment by jaki** [comment]
Secondary indexes are not the core issue like @wumingyuan says.  Here are interesting finds:

- rocksdb seek on indexed table during index scan does not find the row:

  ```
  W1124 21:15:37.550549 15871 doc_rowwise_iterator.cc:552] DocKey Bounds DocKey([], [491805]), DocKey([], [491805, +Inf])
  W1124 21:15:37.550701 15871 docdb_rocksdb_util.cc:195] PerformRocksDBSeek at ../../src/yb/docdb/intent_aware_iterator.cc:335:
      Seek key:         DocKey([], [491805])
      Seek key (raw):   "H\x80\x07\x81\x1d!"
      Actual key:       N/A
      Actual key (raw): N/A
      Actual value:     N/A
      Next() calls:     0
      Seek() calls:     1
  ```

- however, the data is in the indexed table:

  ```
  '488007811D214A802380019F5997013190800E1FB8CD' @ 1125899907826242: 1 => 2380019F5997434A108038CB24
  '488007811D214B8B2380019F5997013190800E1FB8AD' @ 1125899907826243: 1 => 2380019F5997434A108038AB480000001D
  ```

- The secondary index is not needed to demonstrate the issue:

  ```sql
  create table h0 (i int, j int, primary key (i asc));
  insert into h0 values (generate_series(1, 256 * 2048), generate_series(1, 256 * 2048) % 256);
  select * from h0 where i = 491805; -- empty (that's bad)
  ```

- lots of data is needed to repro:

  ```sql
  create table t (i int, j int, primary key (i asc));
  insert into t values (491805, 491805 % 256);
  select * from t where i = 491805; -- returns row (good)
  ```

- loading doesn't have to strictly use insert + generate_series:

  ```sql
  copy h0 to '/dev/shm/copy.dat';
  create table shell (i int, j int, primary key (i asc));
  copy shell from '/dev/shm/copy.dat';
  select * from shell where i = 491805; -- empty (that's bad)
  ```

- deleting all the rows except this one still has issues:

  ```sql
  delete from shell where i < 491805;
  delete from shell where i > 491805;
  select * from shell where i = 491805; -- empty (bad)
  select * from shell; -- fetches the 491805 row
  ```

  Here are the rocksdb logs for query returning nothing:

  ```
    W1124 21:45:15.453886 18625 doc_rowwise_iterator.cc:552] DocKey Bounds DocKey([], [491805]), DocKey([], [491805, +Inf])
  W1124 21:45:15.454025 18625 docdb_rocksdb_util.cc:195] PerformRocksDBSeek at ../../src/yb/docdb/intent_aware_iterator.cc:335:
      Seek key:         DocKey([], [491805])
      Seek key (raw):   "H\x80\x07\x81\x1d!"
      Actual key:       N/A
      Actual key (raw): N/A
      Actual value:     N/A
      Next() calls:     0
      Seek() calls:     1
  ```

  Here are the rocksdb logs for the query returning row:

  ```
  W1124 21:48:10.626310 15872 docdb_rocksdb_util.cc:195] PerformRocksDBSeek at ../../src/yb/docdb/docdb_rocksdb_util.cc:131:
      Seek key:         SubDocKey(DocKey([], [491805]), [SystemColumnId(0)])+FF
      Seek key (raw):   "H\x80\x07\x81\x1d!J\x80\xff"
      Actual key:       SubDocKey(DocKey([], [491805]), [ColumnId(11); HT{ physical: 1606282445344726 w: 983609 }])
      Actual key (raw): "H\x80\x07\x81\x1d!K\x8b#\x80\x01\x9fV0\x99p)\x80\x0e\x1f\xb8\xad"
      Actual value:     "#\x80\x01\x9fV0\xd5\x11\xee\x80\x1f\xb8\xacH\x00\x00\x00\x1d"
      Next() calls:     1
      Seek() calls:     0
  W1124 21:48:10.626387 15872 docdb_rocksdb_util.cc:195] PerformRocksDBSeek at ../../src/yb/docdb/docdb_rocksdb_util.cc:131:
      Seek key:         SubDocKey(DocKey([], [491805]), [ColumnId(11)])+FF
      Seek key (raw):   "H\x80\x07\x81\x1d!K\x8b\xff"
      Actual key:       SubDocKey(DocKey([], [491806]), [HT{ physical: 1606282554986880 }])
      Actual key (raw): "H\x80\x07\x81\x1e!#\x80\x01\x9fV*\x10n\x7f\x80J"
      Actual value:     "#\x80\x01\x9fV*5\xdf\xfb\x80JX"
      Next() calls:     1
      Seek() calls:     0
  ```

**Comment by jaki** [comment]
Found the offending rows.  There's a clear pattern.

```sql
do $$
declare
  a int := 0;
begin
  for counter in 1..1000000 loop
    select count(*) from c where i = counter into a;
    if a = 0 then
      raise notice 'value: %', counter;
    end if;
  end loop;
end;
$$;
```

```
NOTICE:  value: 54645
NOTICE:  value: 109290
NOTICE:  value: 163935
NOTICE:  value: 218580
NOTICE:  value: 273225
NOTICE:  value: 327870
NOTICE:  value: 382515
NOTICE:  value: 437160
NOTICE:  value: 491805
NOTICE:  value: 546450
NOTICE:  value: 601095
NOTICE:  value: 655740
NOTICE:  value: 710385
NOTICE:  value: 765030
NOTICE:  value: 819675
NOTICE:  value: 874320
NOTICE:  value: 928965
NOTICE:  value: 983610
DO
```

They are multiples of 54645 (i.e. 0xD575, 3 * 5 * 3643).  The same results (except less rows) show for table `h2`.

**Comment by jaki** [comment]
Other things:

- the numbers themselves don't matter: `generate_series(2, 500000)` will be bad at `54646`, still the 54645th row
- couldn't reproduce on other data types like float and text
- hash partitioned tables are fine
- commits 78a726ab5 and 78a726ab5~ are bad (will look further back)
- very strange:

  ```sql
  create table over32 (i int, primary key (i asc));
  insert into over32 values (generate_series(1, 488300));
  select * from over32 where i = 54645;
  ```
  
  ```
     i
  -------
   54645
  (1 row)
  ```
  
  ```sql
  select * from over32 where i = 54645;
  ```
  
  ```
   i
  ---
  (0 rows)
  ```

  where I buffered the first select by typing it in while the insert was running.  The buffering is not even necessary.  After about 10-15 seconds, it switches to returning no rows, no matter how many queries you do.

**Comment by tedyu** [comment]
Thanks for digging, Jason.

```
commits 78a726a and 78a726a~ are bad
```
Same commit was mentioned. Maybe you intended to give another commit after the 'and' ?

**Comment by jaki** [comment]
That was intentional, meaning that commit and the one right before it.  Looked into it more and found commit f48649667 to be where the issue first starts.  cc: @spolitov

**Comment by ttyusupov** [comment]
This issue is caused by a bug in the bloom filter index generation which only affects range-partitioned tablets.

**Comment by nocaway** [comment]
There's an issue in the partition seeking routine.
- The row was found in the index.
- The table does have the data.
- The search routine was wrong as it looks for the row / data at a wrong distributed server while the row is located at another server.
