### ISSUE TITLE
[Platform] introduce "enableAuthentication" field into universe json

### ISSUE THREAD

**Issue by sshev** [yugabyte/yugabyte-db#6440]
Redesigned create/edit universe form has "Enable Authentication" toggle at the Security Config step. Need to introduce `enableAuthentication` field into universe json that will internally set corresponding gflags - similar to `enableYSQL` or `enableYEDIS` fields.
![image](https://user-images.githubusercontent.com/11736711/99835434-71e5e280-2b19-11eb-8e11-fd672c82e063.png)

**Comment by kv83821-yb** [comment]
Duplicate of #9131

**Comment by kv83821-yb** [comment]
Duplicate of #9131
