### ISSUE TITLE
[YSQL] Read restart for northwind sample queries

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#6446]
Jira Link: [DB-1849](https://yugabyte.atlassian.net/browse/DB-1849)
```
'/home/yugabyte/tserver/bin/ysqlsh -h yb-tserver-0 -p 5433 -f /tmp/northwind_verify.sql' returned error ysqlsh:/tmp/northwind_verify.sql:7
4: ERROR:  Query error: Restart read required at: { read: { physical: 1605627999926882 logical: 3 } local_limit: { physical: 1605627999885
425 logical: 1 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```

Might be related to https://github.com/yugabyte/yugabyte-db/commit/1c2e37de57d1905da8b2848073905d846334a1eb which changed the logic there recently.

**Comment by frozenspider** [comment]
```
2020-12-09 00:01:48.877 UTC [25109] LOG:  Restart isn't possible, is read?: 0, is dml? 0, is read restart error? 1, is conflict error? 0
2020-12-09 00:01:48.877 UTC [25109] STATEMENT:  call verify_data();
```
which makes sense - we can't restart arbitrary procedure call from PG side, as we don't know what it would be doing.

**Comment by frozenspider** [comment]
e47c4080f02f7d6b183629d77eea6891b964c140 added `yb_debug_log_internal_restarts` GUC option (can be enabled with e.g. `--ysql_pg_conf="yb_debug_log_internal_restarts=true"`) which makes it easier to debug restarts from YSQL side

**Comment by sushantrmishra** [comment]
No able to reproduce, Tried executing following SQL files in 2.19.3.

./sample/northwind_ddl.sql
./sample/northwind_data.sql
