### ISSUE TITLE
Show load balancer state in master web interface

### ISSUE THREAD

**Issue by spolitov** [YugaByte/yugabyte-db#646]
Periodically we face issue when tablet leaders are not well balanced between tservers.
That would be handy to show load balancer state in this case, so that could simplify issue investigation.

**Comment by bmatican** [comment]
Once we do #1336, we can also use the revamped API to highlight this somewhere in the master UI, perhaps on the /tablet-servers page, or even in the main page! cc @rajukumaryb @rahuldesirazu

**Comment by bmatican** [comment]
I think we can probably take care of this as part of #1834. 

@nspiegelberg maybe on top of just having this info in the report there, we can also just put one front and center green vs red note somewhere in the main master page?

**Comment by rahuldesirazu** [comment]
@nspiegelberg A lot of the load balancer state is tracked in cluster_balance.h

```
  // Circular buffer of load balancer activity.
  boost::circular_buffer<ActivityInfo> cbuf_activities_;

  // Summary of circular buffer of load balancer activity.
  int num_idle_runs_ = 0;
  std::atomic<bool> is_idle_ {true};
```

is_idle_ is the metric you probably want to expose as the green/red note in the master main page. For more detailed metrics, ActivityInfo is contains metadata about whether the pending task is a tserver, table, or master task. 

To actually expose the metrics, you can modify master-path-handlers.h/cc.

Hope this helps!

**Comment by nspiegelberg** [comment]
![image](https://user-images.githubusercontent.com/53198280/64302104-a9796680-cf36-11e9-9831-fd7ab780b8a8.png)
![image](https://user-images.githubusercontent.com/53198280/64302254-64a1ff80-cf37-11e9-95b9-5d25345adda1.png)

**Comment by nspiegelberg** [comment]
@yb-andrew : for observing my puny X and trying to make it big and red

**Comment by nspiegelberg** [comment]
![image](https://user-images.githubusercontent.com/53198280/64304342-5dcbba80-cf40-11e9-8599-24405044353e.png)

BIG RED X!!!  Success still looks boring
