### ISSUE TITLE
Preflight checks for cloud provider configuration

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6460]
Add pre-flight checks for cloud provider configuration
 -- ssh key
-- cloud credentials

In the case of validation failure, notify the user via the TASK window, and disable universe creation for that cloud provider.

**Comment by jitendra-12113** [comment]
@chirag-yb  Could you please provide us the steps to repro this issue?
I think, it should be applicable to all cloud provider configuration? 
Appreciate your help! Thanks!

cc: @streddy-yb

**Comment by chirag-yb** [comment]
@jitendra-12113 Yes this will apply to all cloud providers. This can be easily reproduced by 

- Use invalid cloud credentials (AWS access keys, GCP config JSON, Azure client Id/secret)  OR
- Use loud credentials without proper access control. User may not have enough roles/permissions in a cloud provider to create VMs/VPCs OR
- Provide an ssh key which is the incorrect format (AWS only)

Right now there is no validation and a user can continue to the universe creation which may fail due to lack of access control or invalid data provided. 

New proposed experience

1. During the cloud provider creation add a validation.
2. If validation fails, report the failure on the Tasks page
3. Cloud provider is not available for creating new universes

**Comment by jaydeepkumara** [comment]
For now, we will be fixing this for AWS.

**Comment by jitendra-12113** [comment]
Have handled only for AWS cloud provider. Please review. 
https://github.com/yugabyte/yugabyte-db/pull/6808

UI changes also need to be done accordingly.

Thanks!

**Comment by jitendra-12113** [comment]
Created another PR to track this change. Please review
https://github.com/yugabyte/yugabyte-db/pull/6948/

**Comment by chirag-yb** [comment]
@jitendra-12113 how are we tracking the UI change? 
Also, does your PR also cover the scenario when the cloud provider fails to create an ssh key?

`ybops.common.exceptions.YBOpsRuntimeError: Runtime error: KeyPair already exists yb-dev-aws-key
2021-02-10 05:16:41,866 [ERROR] from com.yugabyte.yw.commissioner.SubTaskGroup in TaskPool-0 - Failed to execute task java.util.concurrent.FutureTask@3498b47d, hit error java.lang.RuntimeException: YBCloud command access (add-key) failed to execute..
java.util.concurrent.ExecutionException: java.lang.RuntimeException: YBCloud command access (add-key) failed to execute
 `

**Comment by jitendra-12113** [comment]
@chirag-yb  UI just need to render the error message being thrown from the API that we can do as part of separate PR.

This PR just validates the AWS credentials whether they are valid one or not.

**Comment by chirag-yb** [comment]
@jitendra-12113 how do you validate the AWS credentials? Can you write a short design doc to ensure we are on the same page? 
Do you need a different AWS access control for credential validation?

**Comment by jitendra-12113** [comment]
@chirag-yb  Basically we execute dry run request using  ec2 client. If Dry run gets successful that means credentials are valid otherwise it would error out saying invalid credentials(Access Key or Secret Key)

DryRunResult<DescribeInstancesRequest> dryRunResult = ec2Client
        .dryRun(new DescribeInstancesRequest())
        
       I think we are good for now.

**Comment by streddy-yb** [comment]
We need to revert these changes from 2.7 branch as well.

**Comment by jitendra-12113** [comment]
Hi @streddy-yb, we verified manually on 2.7.0 branch, this changes is not there.
https://github.com/yugabyte/yugabyte-db/blob/2.7.0/managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java

Thanks!

**Comment by streddy-yb** [comment]
Thanks @jitendra-12113

**Comment by ymahajan** [comment]
@jitendra-12113 Going through this issue, Is this fixed only for AWS? how about other providers like GCP?

**Comment by jitendra-12113** [comment]
@ymahajan  Yes this is only for AWS now, we didn't had access of GCP and Azure. 

Will create separate PR  for them. Now we got access for GCP so will work on this. 
Thanks!
