### ISSUE TITLE
[YSQL] Fix TestPgRegressLargeTable java test timeouts

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6475]
Jira Link: [DB-2004](https://yugabyte.atlassian.net/browse/DB-2004)
`TestPgRegressLargeTable#testPgRegressLargeTable` times out very often on clang-debug build type.  They are on the `SELECT`s after running `pg_regress`.  See https://detective-gcp.dev.yugabyte.com/stability/test?build_type=clang-debug&class=org.yb.pgsql.TestPgRegressLargeTable&name=testPgRegressLargeTable.

**Comment by yifanguan** [comment]
Update the stability tests page for this issue: https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressLargeTable&fail_tag=all&name=testPgRegressLargeTable&platform=all

**Comment by yifanguan** [comment]
The actual issue for this ticket is mentioned in https://github.com/yugabyte/yugabyte-db/issues/14036.
