### ISSUE TITLE
Fix TestTransactionStatusTable Java test

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6478]
Jira Link: [DB-1423](https://yugabyte.atlassian.net/browse/DB-1423)
Java test `org.yb.pgsql.TestTransactionStatusTable#testCreation` fails often with messages like

```
org.postgresql.util.PSQLException: 
ERROR: Query error: Restart read required at: { read: { physical: 1606247532157036 } local_limit: { physical: 1606247532147282 logical: 4095 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
  Position: 22
```

This appears to have started from commit 1c2e37de57d1905da8b2848073905d846334a1eb, attested by https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&class=org.yb.pgsql.TestTransactionStatusTable&name=testCreation&num_commits=100 and [https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-gcc-release/lastCompletedBuild/testReport/junit/org.yb.pgsql/TestTransactionStatusTable/testCreation/history/?start=125 -> https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-gcc-release/1521/].

**Comment by spolitov** [comment]
This issue should be fixed in ysql layer.

**Comment by rjalan-yb** [comment]
This test is failing now with relation does not exist error (It could be t_0 or any other relation, not necessarily t_3):

```
com.yugabyte.util.PSQLException: 
ERROR: relation "t_3" does not exist
  Position: 22
```
https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release/1695/testReport/junit/org.yb.pgsql/TestTransactionStatusTable/testCreation/

**Comment by hari90** [comment]
Test is no longer failing
