### ISSUE TITLE
[k8s_deployment] Remove master_replication_factor gflag so that pods do not store resolved IP and allow the flag to be based on the number of master_addresses passed

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#648]
The master_replication_factor should be unset to allow the number of fully-qualified addresses to set it. If the flag is non-zero, it will resolve the addresses passed to a a specific set of IPs that will not survive pod restart.

**Comment by Arnav15** [comment]
Closed in PR https://github.com/YugaByte/yugabyte-db/pull/652
