### ISSUE TITLE
Table creation timed out, line yb/client/client-internal.cc:142

### ISSUE THREAD

**Issue by nodiex-cloud** [yugabyte/yugabyte-db#6484]
```
I1125 03:12:38.447193 52948 pggate.cc:149] Reset YSQL bind address to 10.138.15.199:5432
I1125 03:12:38.448676 52948 server_base_options.cc:137] Updating master addrs to {10.138.15.199:7100}
I1125 03:12:38.449636 52948 mem_tracker.cc:249] MemTracker: hard memory limit is 6.605480 GB
I1125 03:12:38.449654 52948 mem_tracker.cc:251] MemTracker: soft memory limit is 5.614658 GB
I1125 03:12:38.453930 52948 thread_pool.cc:171] Starting thread pool { name: pggate_ybclient queue_limit: 10000 max_workers: 1024 }
I1125 03:12:38.462558 52955 async_initializer.cc:82] Starting to init ybclient
I1125 03:12:38.463634 52955 client-internal.cc:2029] Reinitialize master addresses from file: /disk1/programs/yb/etc/tserver.conf
I1125 03:12:38.463946 52955 client-internal.cc:2058] New master addresses: [10.138.15.199:7100]
I1125 03:12:38.477859 52955 async_initializer.cc:86] Successfully built ybclient
I1125 03:13:14.564725 52948 thread_pool.cc:171] Starting thread pool { name: TransactionManager queue_limit: 150 max_workers: 50 }
2020-11-25 03:15:14.573 UTC [52948] ERROR:  Timed out: Timed out waiting for Table Creation: . Errors from tablet servers: [Timed out (yb/client/client-internal.cc:142): Timed out waiting for Table Creation]
```

create database test; 

Fails from psql. Times out from pg-admin. No useful output in yb-tserver.INFO.

This is on GCP e2-standard-2, Ubuntu. ulimits set as specified in docs. Running as root from as a service from /etc/init.d

**Comment by ddorian** [comment]
Hi @nodiex-admin 

Can you paste a screenshot of http://<yb-master-ip>:7000/tablet-servers ?
What type of disks are you using ?

**Comment by ddorian** [comment]
> No useful output in yb-tserver.INFO.

You can just zip & attach all logs here.

**Comment by nodiex-admin** [comment]
data folder is on an ext4 formatted, additional (not boot) Standard Persistent Disk.

ubuntu-2010-groovy-v20201111

I will get the logs later today. The tail of warning,info of tserver and master did not appear to have anything productive. If it's necessary to get productive logs, it might be useful to specify an elevated logging procedure.

**Comment by ddorian** [comment]
Hi @nodiex-admin 

According to docs, that is [backed by HDD](https://cloud.google.com/compute/docs/disks#disk-types).

Please check our requirements, because [HDD are NOT](https://docs.yugabyte.com/latest/deploy/checklist/#hardware-requirements) supported by YugabyteDB.

**Comment by nodiex-admin** [comment]
Thank you, appreciate the help!

**Comment by ddorian** [comment]
@nodiex-cloud please reopen the issue if the problem persists after moving to SSD.
