### ISSUE TITLE
Support Spark 3.0

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6488]
This issue covers the following aspects:

* upgrade of spark-cassandra-connector to b3.0 branch upstream and port over YB patches from 2.4.x releases
* create validation tests for spark-cassandra-connector within Yugabyte DB codebase

The above tasks would be done in tandem iteratively.

**Comment by tedyu** [comment]
[cql4-4.txt](https://github.com/yugabyte/yugabyte-db/files/5613407/cql4-4.txt)

**Comment by m-iancu** [comment]
Implemented in the Spark connector repo by: yugabyte/spark-cassandra-connector@837dbaf7847d4228dbde2c01b786c8fb27a77c70 and yugabyte/spark-cassandra-connector@857dd4eef7e43f205accb583e9e81710c1491796.
YB tests added in a650ec1.
