### ISSUE TITLE
Backport Postgres 'Add support for abstract Unix-domain sockets'

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6491]
Jira Link: [DB-2304](https://yugabyte.atlassian.net/browse/DB-2304)
    This is a variant of the normal Unix-domain sockets that don't use the
    file system but a separate "abstract" namespace.  At the user
    interface, such sockets are represented by names starting with "@".
    Supported on Linux and Windows right now.

Commit was c9f0624bc2f544baacafa38e3797d5323401d039

**Comment by jaki** [comment]
1. We currently don't even support using unix domain sockets for YSQL.  (We could support it in theory, and we might do so for index backfill issue #5324.)
1. Quoted from the commit message:

   > Supported on Linux and Windows right now.

   Probably means _not_ Mac.

1. Quoted from [the discussion][1]:

   > This feature is about easing the management part of the socket paths
   > while throwing away the security aspect of it.

I think it's better to hold off on this one for now.

[1]: https://www.postgresql.org/message-id/flat/6dee8574-b0ad-fc49-9c8c-2edc796f0033@2ndquadrant.com

**Comment by jaki** [comment]
I confirm that it doesn't work on Mac.  Tried [this patch](https://github.com/yugabyte/yugabyte-db/files/5738147/patch.txt) which contains postgres commits 6e5f8d489acccdc50a35a1b7db8e72b5ad579253 and c9f0624bc2f544baacafa38e3797d5323401d039 to support abstract unix-domain sockets.  It works on CentOS.
