### ISSUE TITLE
Import error with Postgres example database in cloud trial instance

### ISSUE THREAD

**Issue by zopyx** [yugabyte/yugabyte-db#6496]
Jira Link: [DB-1789](https://yugabyte.atlassian.net/browse/DB-1789)
Importing  one of these PG sample dumps

https://postgrespro.com/education/demodb

fails during import via `psql` with  after some time (importing against a Yugabyte Cloud trial cluster):

``` 
ALTER TABLE
COPY 9
COPY 104
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
no connection to the server
connection to server was lost

```

**Comment by sushantrmishra** [comment]
Need more info to for the use case. We have made various fixed and improvement to the copy command which are available in 2.14 onwards, so would be nice to try with that. Please reopen the issue if there is additional information is available and issue is still happening.

- actual DDL/DML  
- PostgreSQL and tserver logs
