### ISSUE TITLE
[YSQL] Prune the output of initdb in YugaByte mode to avoid a confusing message about starting the database server

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#651]
From @ravimurthy 

> Can we prune out most the terminal output from initdb execution? Currently, it outputs a bunch of stuff including these confusing lines at the end :
>
> `Success. You can now start the database server using:`
> `/home/yugabyte/postgres/bin/pg_ctl -D /tmp/yb_pg_initdb_tmp_data_dir -l logfile start`

**Comment by m-iancu** [comment]
Addressed in [c4b06f0](https://github.com/yugabyte/yugabyte-db/commit/c4b06f0a0fedba9d376eac2307e259ff377569bb).
