### ISSUE TITLE
Document how to analyze queries using EXPLAIN

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#6518]
It would be good to add a section here: https://docs.yugabyte.com/latest/develop/

The ask is to add the following:

* Location: Develop -> Query Performance ->  `EXPLAIN` query plans
* Content: Add information about `EXPLAIN` and `EXPLAIN ANALYZE` with functional examples
* Examples: 
  * https://www.postgresql.org/docs/11/using-explain.html
  * https://www.postgresqltutorial.com/postgresql-explain/

**Comment by adzimzf** [comment]
Hi, I'd like to work on this

**Comment by kmuthukk** [comment]
thx @adzimzf ! Please go ahead.

**Comment by adzimzf** [comment]
Hi @kmuthukk,
I've tried to create a [PR](https://github.com/yugabyte/yugabyte-db/pull/6775), but it's not completed yet because I'm not sure regarding the content.
Can I just copy-pasted the content from the example source or should I write completely my own words?

**Comment by lizayugabyte** [comment]
@rkarthik007 @kmuthukk  I already have this documented. Do you mind if I add the content? (as a test contribution)

**Comment by lizayugabyte** [comment]
@adzimzf  Are you still planning to document this issue?

**Comment by adzimzf** [comment]
Hi @lizayugabyte I've created a PR,
just waiting for the confirmation is it okay to copy-paste the content or not.
but if you have already the content feel free to create another PR, I'll close mine

**Comment by kmuthukk** [comment]
@adzimzf --

We reviewed internally, and our plan is to go with our own content here, that @lizayugabyte will be working on. 

Like you suggested/asked, we don't want to copy-paste the content here as it -- definitely want to customize it appropriately for YugabyteDB context. 

We do appreciate your efforts and time on this.

regards
Kannan

**Comment by adzimzf** [comment]
@kmuthukk 
that's totally okay, I'll close the PR
