### ISSUE TITLE
[YSQL] About high concurrency

### ISSUE THREAD

**Issue by wumingyuan** [yugabyte/yugabyte-db#6523]
Jira Link: [DB-4856](https://yugabyte.atlassian.net/browse/DB-4856)
In the current architecture, each connection creates a PG process and calls PGGate to complete the interaction with the storage layer, while PGGate creates multiple threads to complete the interaction with local and remote storage, for example, 16 reactors, which leads to the overflow of threads, especially when the number of connections exceeds 300, the performance is greatly affected. Is there any plan to adjust this architecture?For example, network interaction functions are unified in one process.

**Comment by m-iancu** [comment]
The thread overflow in PGGate was addressed as part of: https://github.com/yugabyte/yugabyte-db/issues/9936. Closing.
