### ISSUE TITLE
[docdb] Raise a warning when trying to blacklist an invalid tserver

### ISSUE THREAD

**Issue by pmb311** [yugabyte/yugabyte-db#6527]
Jira Link: [DB-2177](https://yugabyte.atlassian.net/browse/DB-2177)
This would be a nice UX improvement because currently one can blacklist a tserver server:port that say does not use the default port 9100 and it can be confusing why nothing happens.

Updating documentation [here](https://docs.yugabyte.com/latest/troubleshoot/cluster/replace_tserver/) to say something like "tserver port" or "tserver rpc_bind_address" rather than the default 9100 would also help.

**Comment by ericaguthan** [comment]
Hello! I would like to work on this issue, is it still available? Thanks!

**Comment by bmatican** [comment]
Hey @ericaguthan , sure, this is still up for grabs!

The client side code would be in `src/yb/tools/yb-admin_cli.cc` and `src/yb/tools/yb-admin_client.cc`.
The server side code, processing the blacklist change, would be on the master side, in `src/yb/master/master_service.cc` and `src/yb/master/catalog_manager.cc`.

Let me know if you need more pointers!

**Comment by ericaguthan** [comment]
Awesome, thanks!
