### ISSUE TITLE
[Platform][UI] Enforce better password strength requirements for platform users 

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6530]
Requires platform users to use passwords that meet the following complexity requirements:
- At least 8 characters—the more characters, the better.
- A mixture of both uppercase and lowercase letters.
- A mixture of letters and numbers.
- Inclusion of at least one special character, e.g., ! @ # ? ]

**Comment by mjoshi0923** [comment]
https://phabricator.dev.yugabyte.com/D10723

**Comment by mjoshi0923** [comment]
Diff is https://phabricator.dev.yugabyte.com/D10723
