### ISSUE TITLE
Docker tags are very confusing

### ISSUE THREAD

**Issue by walter-weinmann** [yugabyte/yugabyte-db#6534]
Today I got this email:

![image](https://user-images.githubusercontent.com/1956149/100957424-af377080-351a-11eb-854b-fdb64469d39d.png)

But in DockerHub there are also tags like `2.5.0.0-b2` or **2.3.3.0-b106** etc. and the `latest` is `2.5.0.0-b2` ? 

![image](https://user-images.githubusercontent.com/1956149/100957673-2b31b880-351b-11eb-897e-736e59cabd82.png)

**Comment by tylarb** [comment]
Hi @walter-weinmann 

I'm sorry for the confusion.

2.2.5 is a patch release on the 2.2 branch.

2.5 is the latest feature release - hence, it is in the latest branch.

You can see some documentation on our release versioning here:
https://docs.yugabyte.com/latest/releases/versioning/

**Comment by walter-weinmann** [comment]
Thanks for the clarification.
