### ISSUE TITLE
[Platform] Improve preflight checks usage

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#6546]
As an addition to: **[platform][onprem provider] Pre-flight checks for create universe / edit universe / add node operations #6016**

Using preflight checks some operations can fail without leaving a universe in the 'Error' state.
Example scenario:
1. There is an on-prem universe already created. 
2. The on-prem provider key file removed by a mistake or some other reasons.
3. Do `Edit universe` to add one node. Press 'Save'.
4. The preflight check detects the issue. The operation fails almost without a start.

Desired state:
  The universe is in the normal state (Ready). The additional node was not created.

Actual state:
  The universe is in state 'Error'. Also it has the new node linked to the on-prem instance but completely unconfigured.

**Comment by streddy-yb** [comment]
hi @WesleyW - don't you fail the operation if pre-flight check fails today?

**Comment by streddy-yb** [comment]
Verified using 2.4.2.0-b35:
- Create an OnPrem provider 
- Added a valid node to the provider
- Created a universe with the valid node
- Now added an invalid node to the provider
- EditUniverse operation failed but left the universe in Ready state with a warning
