### ISSUE TITLE
[YW] ReadOnlyClusterCreateTest is failing

### ISSUE THREAD

**Issue by yb-andrew** [yugabyte/yugabyte-db#6577]
Unit test is failing for com.yugabyte.yw.commissioner.tasks.ReadOnlyClusterCreateTest.testClusterCreateSuccess

Current code is checking for data fields that are no longer in the TaskInfo. Update the unit test to check for errors.

**Comment by Arnav15** [comment]
Closed by commit: https://github.com/yugabyte/yugabyte-db/commit/3ea7d241d278e87da5f4c458b754d9fcd96fae32
