### ISSUE TITLE
[Platform] Health Check should provide some alert if it isn't running

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#6581]
Currently, if the health check service fails for some reason, the user does not know except that health checks aren't incrementing in the yugaware UI. 

Ideally, and email will be sent on the failure of the health check service itself.

As an example, edit the "cluster_health.py" script, and add some line which causes python to fail, like

```
testing = not_a_variable
```

The health check will then fail silently.

Obviously, the above problem is an invalid python file, but the concern is that it seems that the health check could fail in several ways without triggering an email alert.

**Comment by streddy-yb** [comment]
A combination of email alert and indication in the UI there is some problem with HealthChecks would be ideal. cc @chirag-yb

**Comment by SergeyPotachev** [comment]
Verified on 2.4.2.
