### ISSUE TITLE
On prem UI instance configuration broken modal

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6583]
The instance configuration UI modal moves for an onprem cloud provider. Steps to reproduce

1. Create universe 
2. Select an onprem cloud provider 
3. Instance configuration columns move to the right
<img width="1691" alt="Screen Shot 2020-12-07 at 3 54 24 PM" src="https://user-images.githubusercontent.com/68662034/101529459-6ed65900-3945-11eb-9c21-a7aa3204073f.png">

4. If the AZ selector rows are present it will push the columns to the left as well

**Comment by ShobhitSamuelSingh** [comment]
Hey, I'm Shobhit, I am new to open source and contributing, and I would like to work on this issue, but don't know where to start,
I've cloned it in my local repository, but what to do next?
Can I work on it? I just need some guidance.

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7095
