### ISSUE TITLE
[YSQL] Support updating primary key columns

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#659]
Fix for issue #565 only support UPDATE attributes that are not PRIMARY KEY column.
In YugaByte, updating PRIMARY KEY columns needs special attention because they are currently used for two important purposes.
- Partitioning the table.
- Ordering rows within one table.

**Comment by nocaway** [comment]
Test case
1- Create a table.
    CREATE TABLE tab(id int primary key, name text);
2- Insert 100 rows into table.
    INSERT INTO tab VALUES(x, 'x');   where x = {1, 2, ..., 100 }
3- Update rows
    UPDATE tab SET id = id + 1000;
4- Turn OFF prefetch by change kPrefetchLimit to 1
    File pg_doc_op.h:  static const int64_t kPrefetchLimit = 1;
Also, it's a mistake to use INT32_MAX as default value for number of prefetched rows.  We should use "1024" instead.

**Comment by sergeyshaykhullin** [comment]
+1
