### ISSUE TITLE
Slightly uneven distribution of hash code among partitions

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#6597]
Jira Link: [DB-2459](https://yugabyte.atlassian.net/browse/DB-2459)
Here are the partition ranges for an 8 shard table (partition_key_end is exclusive):
```
I1207 22:21:03.725575 263929856 meta_cache.cc:936] partition: { partition_key_start:  partition_key_end: 1FFF hash_buckets: [] }
I1207 22:21:03.725616 263929856 meta_cache.cc:936] partition: { partition_key_start: 1FFF partition_key_end: 3FFE hash_buckets: [] }
I1207 22:21:03.725625 263929856 meta_cache.cc:936] partition: { partition_key_start: 3FFE partition_key_end: 5FFD hash_buckets: [] }
I1207 22:21:03.725631 263929856 meta_cache.cc:936] partition: { partition_key_start: 5FFD partition_key_end: 7FFC hash_buckets: [] }
I1207 22:21:03.725638 263929856 meta_cache.cc:936] partition: { partition_key_start: 7FFC partition_key_end: 9FFB hash_buckets: [] }
I1207 22:21:03.725644 263929856 meta_cache.cc:936] partition: { partition_key_start: 9FFB partition_key_end: BFFA hash_buckets: [] }
I1207 22:21:03.725651 263929856 meta_cache.cc:936] partition: { partition_key_start: BFFA partition_key_end: DFF9 hash_buckets: [] }
I1207 22:21:03.725656 263929856 meta_cache.cc:936] partition: { partition_key_start: DFF9 partition_key_end:  hash_buckets: [] } 
```

Each partition except the last one contains 8191 hash codes while the last one contains 8199. Should be 8192 hash codes per each partition. For big number of tablets, it could be even worse. For example, for 2437 tablets, first 2436 tablets have 26 hash codes each while the last tablet has 2200 hash codes. That leads to hot shard issue.

[DB-2459]: https://yugabyte.atlassian.net/browse/DB-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@ttyusupov , Weren't we considering backporting this after 2-3 weeks of bake time. If so, can I reactivate this?

**Comment by rthallamko3** [comment]
reactivating for 2.14 backport.
