### ISSUE TITLE
Make the number of reserved thread for the small compaction queue a flag

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#66]
The rocksdb `options.num_reserved_small_compaction_threads` is not exposed as a gflag. It allows splitting small vs large compactions.

Currently, this parameter defaults to -1, which gets re-interpret as reserving (N-1) threads for small compactions. leaving 1 thread for large compactions

```
  if (result.num_reserved_small_compaction_threads == -1 ||
        result.num_reserved_small_compaction_threads >= result.base_background_compactions) {
    result.num_reserved_small_compaction_threads = result.base_background_compactions - 1;
  }
```

**Comment by ayushsengupta1991** [comment]
Resolved with the commit: https://github.com/YugaByte/yugabyte-db/commit/c3ef44b9f92c28280bfdf60caca851d1b16838a2
