### ISSUE TITLE
[YW] Creating a TLS enabled universe with a custom home dir setting in onprem provider fails

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6602]
Reported by @tsmull-11 

1. Create an onprem provider with a custom home directory setting.
2. Create a universe with node to node encryption on (let YW generate the certs).

Fixing the TODO here - https://github.com/yugabyte/yugabyte-db/blob/ac7e8a19205ce982033cf8c1d59ebe7afd224adb/managed/src/main/java/com/yugabyte/yw/common/NodeManager.java#L328 - should do the trick.

**Comment by streddy-yb** [comment]
Verified using 2.4.2.0-b35:
- Create an OnPrem provider with Custom Home Dir (/opt/yugabyte)
- Added 3 nodes to this provider
- Created a new universe with TLS enabled
- Verify --use_node_to_node_encryption=true on the master/tserver nodes
- Connect to the DB using ysqlsh
- Delete the Universe
