### ISSUE TITLE
[Platform] [UI] Fix Sample app command for ycql when TLS enabled

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#6615]
When tls enabled on a cluster when you click on run sample apps for ycql and ysql:

![image](https://user-images.githubusercontent.com/73500297/101851901-50bd5400-3b11-11eb-9851-f30a2388a5b5.png)

The command that works is:
```
java -jar ~/downloads/yb-sample-apps.jar --workload CassandraKeyValue --nodes ip:port --ssl_cert /opt/yugaware/certs/REDACTED/REDACTED/ca.root.crt
```
Where path for the certs can be found under 

![image](https://user-images.githubusercontent.com/73500297/101852031-99750d00-3b11-11eb-8905-efde709e0e19.png)

Note that ysql sample app is broken for tls and there is PR in the works to fix it:
https://github.com/yugabyte/yb-sample-apps/pull/36/files

**Comment by gurushant-yb** [comment]
User need to download the certificate manually on the host and run following docker command(sample) with the substitution:

docker run -d   -v <path where crt is placed on host>:/home/root.crt:ro  yugabytedb/yb-sample-apps  --workload CassandraKeyValue --nodes 172.161.22.47:9042  --ssl_cert /home/root.crt

**Comment by gurushant-yb** [comment]
> User need to download the certificate manually on the host and run following docker command(sample) with the substitution for YCQL:
> 
> docker run -d -v [path where crt is placed on host]:/home/root.crt:ro yugabytedb/yb-sample-apps --workload CassandraKeyValue --nodes 172.161.22.47:9042 --ssl_cert /home/root.crt
> 
> Some where on the UI, we need to mention steps to download certificates, and form the command (by placing location of the downloaded crt)
> 
> @chirag-yb @streddy-yb : Please let @sunilsutarDCE know what (manual) steps needs to be added in the UI

YSQL -> SqlInserts App run is failing for the TLS enabled cluster.

**Comment by gurushant-yb** [comment]
Hi @streddy-yb , 
We can generate following command to run the docker command without manually downloading certificate file(in case tls is enabled),  User can copy this directly from the clipboard and run it on the terminal:
```
export FILE_NAME=~/root_cert.crt && echo -n "<root cert content>" > $FILE_NAME && docker run -d -v $FILE_NAME:/home/root.crt:ro gurushantj/yb-sample-apps:1.3.4-SNAPSHOT --workload CassandraKeyValue --nodes 172.161.61.251:9042 --ssl_cert /home/root.crt --num_reads 1000 --num_writes 1000 && rm -rf $FILE_NAME
```

**Comment by sunilsutarDCE** [comment]
Sample app command on ui shows the command with the required certificate content when TLS is enabled, earlier user needs to download certificate explicitly and form manifest/command for k8s/docker.
<img width="1081" alt="Screenshot 2021-04-12 at 1 11 35 PM" src="https://user-images.githubusercontent.com/39611171/117969590-3cda8000-b345-11eb-8a4e-3915aec69711.png">
