### ISSUE TITLE
Edit on-prem provider shows empty home directory

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6625]
Editing the on-prem cloud provider shows an empty home directory.

<img width="797" alt="Screen Shot 2020-12-11 at 12 31 42 PM" src="https://user-images.githubusercontent.com/68662034/101952020-d4784e80-3bac-11eb-8fb0-468daf5e2ca2.png">

Expected outcome - Show the actual directory set which can be either the system default or custom directory.

**Comment by gg-dev-05** [comment]
May I work on this issue?

**Comment by nishantSharma459** [comment]
I've cross-checked it and functionality is fine. I'm attaching a screenshot please take a look. And lemme  know if I'm doing something wrong.

![EditHomedirectory](https://user-images.githubusercontent.com/75416933/103342152-c6806400-4aae-11eb-95c9-202c9e22f191.png)
