### ISSUE TITLE
[YSQL] Support ALTER TABLE/INDEX <table/index> SET TABLESPACE <tablespace> API 

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#6639]
Jira Link: [DB-1445](https://yugabyte.atlassian.net/browse/DB-1445)
Currently if the user needs to change the placement policy associated with the table or index, there is no way to do so other than deleting and recreating the table.
To do this, support the following API

```
ALTER TABLE/INDEX <table/index> SET TABLESPACE <tablespace>
```

In Yugabyte clusters, a pg_shdepends entry is added to track dependencies between tablespaces and tables. This is because unlike PG, in YB clusters, we cannot use the directory location associated with the tablespace to figure out what tables belong in it.  This pg_shdepends entry must also be edited correspondingly when the table is altered.

Also note that additionally this command will be asynchronous - i.e. there is a periodic job in the YB-Master that scans the pg_tablespace and pg_class system tables to figure out the placement policy associated with every table.

Once this job kicks in and edits the YB-Master's in-memory state, the load balancer should see the change of placement policy for the altered table, and then move the tablets according to the new placement policy. This could potentially be a very long running operation and will happen in the background.

**Comment by tverona1** [comment]
Re-opening this issue to track backporting to 2.20.2

**Comment by tverona1** [comment]
Closing as done, as backport to 2.20 is compete.
