### ISSUE TITLE
[YCQL] Fail to insert JSONB data from csv files

### ISSUE THREAD

**Issue by linzhou094** [YugaByte/yugabyte-db#664]
We are having some issue with copying jsonb values to tables from csv.
The table we want to insert data into is 
`CREATE TABLE quinkeyspace.quin_combination (
    product text,
    retailer_moniker text,
    carrier_moniker text,
    country text,
    type text,
    category text,
    localization_json jsonb,
    PRIMARY KEY ((product, retailer_moniker), carrier_moniker, country, type, category)
) WITH CLUSTERING ORDER BY (carrier_moniker ASC, country ASC, type ASC, category ASC)
    AND default_time_to_live = 0
    AND transactions = {'enabled': 'false'};`
 
Our ./db/combinations.csv file contains the following data (csv file is not supported as attachment:( )
`product0,company0,ups,us,type0,category0,'{"text_buy": "quin_buy_sale"\, "text_order": "quin_order_free_shipping"}'`

The result is as shown in the screenshot attachment
![screen shot 2018-12-13 at 11 24 07 am](https://user-images.githubusercontent.com/44006315/49962269-ad0d1f00-fec9-11e8-9237-c0b29f500781.png)

For your information, when we use the INSERT command, it is working as expected.
![screen shot 2018-12-13 at 11 32 06 am](https://user-images.githubusercontent.com/44006315/49962691-c2367d80-feca-11e8-9f5d-40cad985753a.png)

**Comment by robertpang** [comment]
We set up the test table, tried uploading the .csv file using `cqlsh`'s COPY command and saw the same timeout. In yb-tserver's log file, it reports that the JSON text is invalid:

```
E1213 12:19:13.889235 70332416 process_context.cc:180] SQL Error: Invalid Arguments. Corruption: JSON text is corrupt: Invalid value.
INSERT INTO quinkeyspace.quin_combination (product, retailer_moniker, carrier_moniker, country, type, category, localization_json) VALUES (?, ?, ?, ?, ?, ?, ?)
       ^^^^
E1213 12:19:13.892740 69795840 process_context.cc:180] SQL Error: Invalid Arguments. Corruption: JSON text is corrupt: Invalid value.
INSERT INTO quinkeyspace.quin_combination (product, retailer_moniker, carrier_moniker, country, type, category, localization_json) VALUES (?, ?, ?, ?, ?, ?, ?)
       ^^^^
...
```

This happens because `cqlsh` includes the single quotes around the JSON text in the .csv file as part of the JSON text. After removing the single quotes, the .csv file is loaded successfully:

```
cqlsh:quinkeyspace> COPY quin_combination FROM 'combinations.csv';
Using 7 child processes

Starting copy of quinkeyspace.quin_combination with columns [product, retailer_moniker, carrier_moniker, country, type, category, localization_json].
Processed: 1 rows; Rate:       2 rows/s; Avg. rate:       2 rows/s
1 rows imported from 1 files in 0.420 seconds (0 skipped).
cqlsh:quinkeyspace> select * from quin_combination;

 product  | retailer_moniker | carrier_moniker | country | type  | category  | localization_json
----------+------------------+-----------------+---------+-------+-----------+----------------------------------------------------------------------
 product0 |         company0 |             ups |      us | type0 | category0 | {"text_buy":"quin_buy_sale","text_order":"quin_order_free_shipping"}

(1 rows)
cqlsh:quinkeyspace> select localization_json->>'text_buy' from quin_combination;

 expr
---------------
 quin_buy_sale

(1 rows)
```

**Comment by kmuthukk** [comment]
@robertpang -

perhaps you can give a sample row from the CSV file before and after, and close out the issue?

**Comment by robertpang** [comment]
The change required to the CSV file is to remove the single quotes around the string field as follows:

```
product0,company0,ups,us,type0,category0,'{"text_buy": "quin_buy_sale"\, "text_order": "quin_order_free_shipping"}'
```

to 

```
product0,company0,ups,us,type0,category0,{"text_buy": "quin_buy_sale"\, "text_order": "quin_order_free_shipping"}
```
