### ISSUE TITLE
Edit universe - missing availability zone configuration 

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6645]
Steps to reproduce 

1. Edit a universe 
2. Change the instance type to anything and then go back to the original instance type
3. Notice AZ section is not rendered
5. Behind the scene universe_configure API is failing with this error

> {"error":"Invalid operation: At least one field should be modified for editing the universe."}

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/8367
