### ISSUE TITLE
Edit universe - missing KMS configuration 

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6646]
Steps to reproduce
1. Create a universe with encryption at-rest enabled
2. Edit universe > Notice KMS config is currently displayed
3. Refresh the page > KMs config is cleared and shows "Select Configuration"

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6741

**Comment by nishantSharma459** [comment]
The new patch has been loaded. PTAL.
