### ISSUE TITLE
Load Balancer is not distributing the tablet leaders uniformly on a geo-partitioned cluster.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#6648]
Jira Link: [DB-1398](https://yugabyte.atlassian.net/browse/DB-1398)
Running TPCC on a geo-partitioned setup, with every table having a partitioned table that belongs to a particular zone, we noticed that the leaders were not distributed evenly across the nodes present in a zone.

<img width="2406" alt="Screen Shot 2020-12-11 at 1 16 11 PM" src="https://user-images.githubusercontent.com/7224861/102052549-136bf700-3d9b-11eb-88b0-5f6e79029f8a.png">
<img width="2408" alt="Screen Shot 2020-12-11 at 1 16 30 PM" src="https://user-images.githubusercontent.com/7224861/102052562-1535ba80-3d9b-11eb-9c9c-18326cdf2a2b.png">

While performing theses experiment the global placement info was deleted using the yb-admin command.

**Comment by bmatican** [comment]
@psudheer21 is working on reproducing this at a smaller scale. Might need some verbose logging or even a debug build, to investigate further, once we get it stuck again @rahuldesirazu

**Comment by lingamsandeep** [comment]
@Simonliuwaterloo For this one, we'll need to check if this is still an issue by creating multiple partitioned tables with several tablets and verifying that the leaders are spread out evenly. Lets see if we can add a unit test for this to ensure that we don't have an issue and are protected from future regressions.
