### ISSUE TITLE
[YSQL] Enable support for sequences 

### ISSUE THREAD

**Issue by ravimurthy** [YugaByte/yugabyte-db#665]
Add support for sequences
1. DDL commands -  CREATE SEQUENCE, DROP SEQUENCE and ALTER SEQUENCE
2. Sequence functions - https://www.postgresql.org/docs/9.1/functions-sequence.html
3. Creating tables with nextval(seq) as default value

**Comment by hectorgcr** [comment]
Closing this one. Tracking `ALTER SEQUENCE` in #1002 and `setval` in #1003
