### ISSUE TITLE
[yw] Enable AWS time sync by default on AWS universes

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6655]
We are able to set up Chrony to sync to AWS ntp servers at https://github.com/yugabyte/yugabyte-db/blob/e98203c9d4cd8180fb3c173c3f43cb78548979f8/managed/devops/roles/provision-cluster-server/tasks/main.yml#L56

But the default for this feature in JS is disabled. (presumably at https://github.com/yugabyte/yugabyte-db/blob/e98203c9d4cd8180fb3c173c3f43cb78548979f8/managed/ui/src/components/universes/UniverseForm/UniverseFormContainer.js#L301), so customers have to explicitly check it.

We should turn it on by default in 2.5.

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6883
