### ISSUE TITLE
[K8s] Support platform backup

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6668]
Add support for platform backup and restore

**Comment by jvigil-yugabyte** [comment]
https://github.com/yugabyte/yugabyte-db/commit/576ad85180371d0d211087056b235bad60c97b56

**Comment by jvigil-yugabyte** [comment]
Landed on `2.7.0` branch: https://github.com/yugabyte/yugabyte-db/commit/0d8e99340da33c05eed29047a3851f812197de5a

**Comment by jvigil-yugabyte** [comment]
Landed on 2.4:
* https://github.com/yugabyte/charts/commit/bd575512dc329cd3ca867dbc6af8ab8f72377af1
* https://github.com/yugabyte/yugabyte-db/commit/8cad2f90908d8739d1171bc396c44d5d91d1d783

**Comment by dotyjim-work** [comment]
Docs update => https://github.com/yugabyte/yugabyte-db/issues/7784
