### ISSUE TITLE
[DocDB] Investigate per tablet memory overhead

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#6676]
Jira Link: [DB-1919](https://yugabyte.atlassian.net/browse/DB-1919)
From manual testing, it seems to be between 500-1000kb. Tested with 10k tablets on a server.

Would be great to understand where that's coming from and what of this we can add to the mem-tracker framework, so we can better account for where the memory is going, even in high number of tablet cases!

One part I know of is the rocksdb arena, which we default at 128kb:
> src/yb/rocksdb/db/column_family.cc:DEFINE_int32(memstore_arena_size_kb, 128, "Size of each arena allocation for the memstore");

cc @spolitov @mbautin @amitanandaiyer 

[DB-1919]: https://yugabyte.atlassian.net/browse/DB-1919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Confirmed with @spolitov that indeed the arena would count twice per tablet, if we have an intentsdb, so that'd explain 256kb for all txn enabled tablets.

I think we should do 2 types of tests, say with 10000 tablets
- non-txn tables vs txn tables -- this should give us loosely the overhead of the extra intentsdb rocksdbs, and, assuming that is about the same for each rocksdb, we could use the diff to assume the non-rocksdb overhead too!
- directly after creating the data vs after restart, in case post-bootstrap we generate any new metadata or cleanup any existing metadata

**Comment by bmatican** [comment]
@kmuthukk ran some pprof and was able to find some more interesting overheads

Notable stacks are:
2 x 70k allocations / per tablet of this form:
```
rocksdb::WritableFileWriter::WritableFileWriter()
rocksdb::DB::Open()
rocksdb::DB::Open()
yb::tablet::Tablet::OpenKeyValueTablet()
yb::tablet::Tablet::Open()
yb::tablet::TabletBootstrap::OpenTablet()
yb::tablet::TabletBootstrap::Bootstrap()
yb::tablet::BootstrapTabletImpl()
yb::tablet::BootstrapTablet()
yb::tserver::TSTabletManager::OpenTablet()
yb::ThreadPool::DispatchThread()
yb::thread::SuperviseThread()
start_thread
```

11 x 20K allocations / per tablet of this form:
```
yb::HdrHistogram::Init()
yb::HdrHistogram::HdrHistogram()
yb::Histogram::Histogram()
yb::HistogramPrototype::Instantiate()
yb::tablet::TabletMetrics::TabletMetrics()
yb::tablet::Tablet::Tablet()
yb::tablet::TabletBootstrap::OpenTablet()
yb::tablet::TabletBootstrap::Bootstrap()
yb::tablet::BootstrapTabletImpl()
yb::tablet::BootstrapTablet()
yb::tserver::TSTabletManager::OpenTablet()
yb::ThreadPool::DispatchThread()
yb::thread::SuperviseThread()
start_thread
```

2 x 37K allocations / per tablet of this form:
```
rocksdb::CreateDBStatistics()
yb::tablet::Tablet::Tablet()
yb::tablet::TabletBootstrap::OpenTablet()
yb::tablet::TabletBootstrap::Bootstrap()
yb::tablet::BootstrapTabletImpl()
yb::tablet::BootstrapTablet()
yb::tserver::TSTabletManager::OpenTablet()
yb::ThreadPool::DispatchThread()
yb::thread::SuperviseThread()
start_thread
```

I will cut independent tasks for the 2 issues that came out of this, as part of discussions on Slack. cc @rahuldesirazu @amitanandaiyer

**Comment by rthallamko3** [comment]
https://github.com/yugabyte/yugabyte-db/issues/16196 added the per tablet memory tracking.

**Comment by bmatican** [comment]
@yusong-yan can you confirm that we still don't have support for the rocksdb arenas in MemTracker? If so, should we cut a dedicated issue for that, if we wanted to close this one out?

**Comment by rthallamko3** [comment]
@bmatican , Yusong is planning to create a separate GH for that. He added the comment in https://github.com/yugabyte/yugabyte-db/issues/16196
