### ISSUE TITLE
[YCQL]  TLS Connection fails with yw generated certs

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#6677]
**//repro notes**

   - Install 2.2.2.1 in gcp, followed [ycql docs](https://docs.yugabyte.com/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/)
    - Used Replicated to manually install older 2.2.2.1 platform
    - Followed steps in install docs for certs | https://docs.yugabyte.com/stable/yugabyte-platform/

**// results with cert downloaded from UI:**
charlottehamilton@charlotte-2221-test:~/yugabyte-2.2.2.0$ ./bin/ycqlsh 10.204.0.27 --ssl
Connection error: ('Unable to connect to any servers', {'10.204.0.27': error(1, u"Tried connecting to [('10.204.0.27', 9042)]. Last error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)")})

**Comment by streddy-yb** [comment]
hi @CharlotteRose - have you downloaded root.crt to ~/.yugabytedb folder as described in these steps?
https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/#connecting-to-the-ycql-endpoint-with-tls

**Comment by CharlotteRose** [comment]
Correct. The instructions were followed as documented, this was to reproduce a issue hit by a customer.

**Comment by chirag-yb** [comment]
@CharlotteRose I thought this issue was solved with the latest version. Please confirm if this still needs to be investigated.

**Comment by CharlotteRose** [comment]
@chirag-yb - ack, ty - noting this is resolved in 2.2.5
