### ISSUE TITLE
[PLATFORM UI] Unable to create a universe with same as one that was deleted

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#6698]
I had created nm-test-2dc-p universe on AWS portal - http://portal.dev.yugabyte.com/. I deleted this universe and now I am trying to create it with same name but I see alert that "Universe name already exists". It could be due to some metadata being stale perhaps or something unique to this portal.

**Comment by sb-yb** [comment]
1. Universe with that name still exist in the database.
2. There was no failed deletion attempt in the today's or yesterdays log.
3. Checked tasks in UI and found that the universe with that name was deleted on Nov 24th: 
![image](https://user-images.githubusercontent.com/73500297/102561254-13b10e80-4089-11eb-8795-96b8c5cf803e.png)
But the deletion attempt failed.
Next will see if we have logs that old. If not will check task details in DB.
On the side note there is UI bug when I click on "Details" link for failed universe. It attempts to show something and quickly turns to a blank page. Will file a separate bug with details.

**Comment by sb-yb** [comment]
```
DestroyEncryptionAtRest  | Success
 ManipulateDnsRecordTask  | Success
 AnsibleDestroyServer     | Success
 AnsibleDestroyServer     | Success
 SwamperTargetsFileUpdate | Created
 AnsibleDestroyServer     | Success
 RemoveUniverseEntry      | Failure
```

**Comment by sb-yb** [comment]
```
"Failed to execute task java.util.concurrent.
FutureTask@f5cb208, hit error io.ebean.DataIntegrityException: Error[ERROR: update or delete on table \"universe\" violates foreign key constraint \"f
k_universe_uuid\" on table \"alert_definition\"
```

So basically we need to make sure that any `alert_definitions` referring to this universe are removed before we can delete the universe itself.

**Comment by sb-yb** [comment]
So we will have to delete `alert` as well since it refers to `alert_definition` which refers to universe. 
Its easy to implement by just adding ` ON DELETE CASCADE` clauses on these fk definitions so universe deletes would trigger deletion of any dependent alerts. 
But real question is; is that what we want from products POV? Do we want customers to lose the alert setup because they deleted the universe? @streddy-yb @chirag-yb WDYT?
May be that's what we do for now to do a quick fix for this bug. But just pointing out for any thoughts from products side.

**Comment by chirag-yb** [comment]
@sb-yb What kind of alerts are these?

**Comment by sb-yb** [comment]
Not specific alert but any type of alert_definition has dependency on universe. This was introduced recently by @daniel-yb 
So he may know more if it makes sense to always delete it or if its worth preserving alert definitions.
Basically, deleting some elaborate customer config and making customer redo it may not be a good experience.

**Comment by daniel-yb** [comment]
@sb-yb it is fine to get rid of the alert definition when the universe is deleted. From a UI point of view we shouldn't assume that new universes with the same name as an older universe share any sort of config.

**Comment by sb-yb** [comment]
FWIW I have added cascade delete for now so that universe deletion does not fail. So closing this bug. We can take any additional UX discussion offline or on separate bug.

**Comment by sb-yb** [comment]
@streddy-yb This bug was "closed" but I worked against it to backport. Just tagging you to make sure this is not missed.
