### ISSUE TITLE
docs: use newer ysql_hba_conf_csv

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6710]
`ysql_hba_conf` tserver flag is deprecated.  Use `ysql_hba_conf_csv` instead in the documentation.  For example, change the page https://docs.yugabyte.com/latest/secure/authentication/password-authentication/.

**Comment by ddorian** [comment]
@jaki is the usage the same ? If it has changed, where can I learn about the new syntax ?

**Comment by jaki** [comment]
I'm actually not too sure about the new syntax.  It worked about the same when I had tried it.  I think @d-uspenskiy worked on the feature, so he can clarify.

**Comment by d-uspenskiy** [comment]
Hi @ddorian 

the rule is:
- in case filed has `,`  or `"` it should be quoted with `"`
- the `"` symbol in quoted field should be doubled (i.e. `""`)

Example. Suppose we have two fields:
`host all all127.0.0.1/0 password`
and
`host   all         all      0.0.0.0/0  ldap ldapserver=***** ldapsearchattribute=cn ldapport=3268 ldapbinddn=***** ldapbindpasswd="*****"`
Second field has `"` so we should quote this field and doubles the `"` symbol  in this field
result will be
`"host   all         all      0.0.0.0/0  ldap ldapserver=***** ldapsearchattribute=cn ldapport=3268 ldapbinddn=***** ldapbindpasswd=""*****"""`

now fields can be joined with the `,` symbol
`host all all127.0.0.1/0 password,"host   all         all      0.0.0.0/0  ldap ldapserver=***** ldapsearchattribute=cn ldapport=3268 ldapbinddn=***** ldapbindpasswd=""*****"""`
and the final result is the using of the `'` symbol to set the flag value
`--ysql_hba_conf_csv='host all all127.0.0.1/0 password,"host   all         all      0.0.0.0/0  ldap ldapserver=***** ldapsearchattribute=cn ldapport=3268 ldapbinddn=***** ldapbindpasswd=""*****"""'`
