### ISSUE TITLE
Yugabyte fails to start in kubernetes (Windows docker desktop)

### ISSUE THREAD

**Issue by BahramMoradi** [yugabyte/yugabyte-db#6714]
OS: Microsoft Windows 10 Pro
Docker Version: 20.10.0
Helm Version: 3.4.2
I have tried to follow the instructions from https://docs.yugabyte.com/latest/quick-start/create-local-cluster/kubernetes/
to start a single Yugabyte Cluster in windows desktop, but when i check the status of the pods, they remindes in pendig status.

I tried the instructions for docker. It works fine. 

Any help ?

**Comment by ddorian** [comment]
Hi @BahramMoradi 

What is the size of your server ?

Are you using minikube ? 

Are you using VM containers ? What's the ram/cpu/ssd/hdd size of the VMs ?

Can you paste any logs from the pods ?

**Comment by BahramMoradi** [comment]
Hi @ddorian 
I am not using mini kube. I am  using docker desktop for windows. It is single node cluster.
16 GB RAM
80 GB Harddisk
Intel Core i5-8365U, 4 Cores
The pods does not start, it is in the PENDING status so there is no logs. I gess it is because persistent claim.

**Comment by ddorian** [comment]
>  80 GB Harddisk

Please use SSD, HDD is **_NOT_** supported. See [hardware requirements](https://docs.yugabyte.com/latest/deploy/checklist/#hardware-requirements). 

> I am using docker desktop for windows.

Is docker desktop creating a linux-virtual-maxhine or using the linux-subsystem ? cc @bhavin192

**Comment by ddorian** [comment]
Closing as no response from user. Please reopen if issue still persists.
