### ISSUE TITLE
[Platform] Health check emails should include Yugaware Hostname

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#6718]
Currently, health check alert emails include the Universe Name and Universe Version

It would be great, for debugging cases where universes might be named the same, to include the Yugaware Hostname and/or IP in the health check alert email.

**Comment by jitendra-12113** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7337
Please review. Thanks!
