### ISSUE TITLE
YSQL tablet-splitting issues due to mutable table partitions 

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#6719]
From @nocaway :
Here's an example, but I anticipate more issues later on.
- Let's say the table is partitioned as `<p1, p2, p3>`, and from docdb, @jaki sent request with key `p1`, `p2`, and `p3`
- Suppose the table is splitted evenly, and cache is then changed to `<pp1 = p1, pp2, pp3 === p2, pp4, pp5 === p3, pp6>`
- When processing the request from docdb, the PgGate layer would then run the requests on 3 partitions `pp1`, `pp3`, and `pp5`.  That means we would miss the `pp2`, `pp4` , and `pp6` partitions.

The above example is just one scenarios.  SQL / PgGate layer would always have to deal with mutable tabledesc every time we touch tabledesc.
That would make our work more and more difficult as time goes on.
What I'd like the fix to be is the following.
- Keep the tabledesc immutable as it has been and use version number to invalidate requests that don't have up-to-date version.
- Change the cache version number the same way as ALTER TABLE and let the error check to do the rest.

**Comment by ramsrivatsa** [comment]
Added support for tablet splitting in YSQL with this commit -> [cb8d9c5](https://github.com/yugabyte/yugabyte-db/commit/cb8d9c59a8665ffbc9d5bd56d2eb7f6c2b3dd1fb)
