### ISSUE TITLE
Yugabyte integration with Istio Service mesh

### ISSUE THREAD

**Issue by johngebrial** [yugabyte/yugabyte-db#6730]
Hello everyone,
i'm facing a problem with YugabyteDB with ISTIO servicer mesh
[YB-DB.txt](https://github.com/yugabyte/yugabyte-db/files/5728857/YB-DB.txt)
![Capture](https://user-images.githubusercontent.com/75697591/102871322-f4c6c980-4446-11eb-91d4-81ebe2904ce4.PNG)

this is the log i found onto Kiali and Yugabyte logs

**Comment by streddy-yb** [comment]
hi @bhavin192 - can you take a look?

**Comment by johngebrial** [comment]
I add a service entry for all YB-DB namespaces and the remote peer error disappear, but i found another error which is like the below 
[YB_update.txt](https://github.com/yugabyte/yugabyte-db/files/5731415/YB_update.txt)

**Comment by johngebrial** [comment]
![Capture](https://user-images.githubusercontent.com/75697591/102920289-25cceb80-4493-11eb-9481-0337eebe1246.PNG)

**Comment by bhavin192** [comment]
Did you setup the things as mentioned here https://github.com/yugabyte/yugabyte-db/issues/2158#issuecomment-705389982 as well as in the blog post: https://blog.yugabyte.com/service-mesh-era-building-modern-apps-with-yugabytedb-and-istio/

The Helm flag (`istioCompatibility.enabled=true`) and DestinationRules are required to get it working.

**Comment by johngebrial** [comment]
Hello Bhavin192,
I deployed Yugabyte using the documentation onto Yugabyte https://docs.yugabyte.com/latest/deploy/kubernetes/multi-zone/eks/helm-chart/
with 6 workers onto 3 AZs , also I create a DestinationRules with DISABLE mode 
but how can i edit helm flag , should i write it into overrides files on master and tserver ?

**Comment by bhavin192** [comment]
To keep it simple, we can start with no DestinationRules and mTLS disabled first.

> should i edit the helm command and add istioCompatibility.enabled=true for each namespace?

Yes.

-   Create this in all three namespaces.
    
    ```yaml
    apiVersion: security.istio.io/v1beta1
    kind: PeerAuthentication
    metadata:
      name: mtls
    spec:
      mtls:
        mode: DISABLED
    ```
- Update Helm releases from all the three namespaces.

**Comment by johngebrial** [comment]
Hello Bhavin192,
thank you so mush its working now with PeerAuthentication : PERMISSIVE and DestinationRule: ISTIO_MUTUAL
I think everything is working normal now thank you dor your support
