### ISSUE TITLE
Add mTLS support to all YB clients.

### ISSUE THREAD

**Issue by Arnav15** [yugabyte/yugabyte-db#6740]
With the introduction of the mTLS support in the coreDB, we need to add the necessary protocols in YBClient for successful connections to the DB.
The same changes need to be made for yb-admin and yb-ts-cli.

**Comment by hkandala** [comment]
The change (4a17260c73b0edbaced139c65ef32e8b828dea4a) in ybase which adds support for `node_to_node_encryption_use_client_certificates` flag needs to be backported first, as mTLS change is dependent on it.
