### ISSUE TITLE
preferred leader zone setting selected in platform doesn't match the database setting

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#6743]
YugabyteDB version 2.2.5.0 (2fa951fa96f0d1ea7ec2b7ad228573430b4c20ff)
Platform version 2.4.0.0

*The preferred zone displayed is us-central1-f*

<img width="982" alt="Screen Shot 2020-12-23 at 7 18 14 PM" src="https://user-images.githubusercontent.com/13615376/103057191-b8cd5a80-4553-11eb-8dae-a98281d5d745.png">

*But preferred zone we are seeing in cluster configuration is: us-central1-b.*

For example: http://10.152.0.112:7000/cluster-config

<img width="445" alt="Screen Shot 2020-12-23 at 7 13 31 PM" src="https://user-images.githubusercontent.com/13615376/103057238-cd115780-4553-11eb-9e91-cc4d239cdb4e.png">

**Comment by SergeyPotachev** [comment]
From YW logs -

  {"cloudList":[{"uuid":"f8438937-bef6-4ed7-8304-2fad20f54946","code":"gcp","regionList":[{"uuid":"83c88ab7-4685-4de2-90d0-1326da69dd25","code":"us-central1","name":"Iowa","azList":
  
      [{"uuid":"25ada363-05a9-458c-93d5-b0500e1375fe","name":"us-central1-c","replicationFactor":1,"subnet":"subnet-us-central1","numNodesInAZ":3,"isAffinitized":true,"affinitized":true},
  
      {"uuid":"6d43912e-d1f0-4ef5-925b-26898aff7a13","name":"us-central1-f","replicationFactor":1,"subnet":"subnet-us-central1","numNodesInAZ":3,"isAffinitized":true,"affinitized":true},
  
      {"uuid":"c0bf6415-b73a-4f99-834b-7e1cf488c341","name":"us-central1-b","replicationFactor":1,"subnet":"subnet-us-central1","numNodesInAZ":3,"isAffinitized":true,"affinitized":true}]}]}]}

All three AZs are marked as affinitized.

**Comment by SergeyPotachev** [comment]
Also was able to reproduce the problem on own YW. Deselected two AZs from three, but in the HTTP request sent by the frontend I see two AZs marked as affinitized.

![Screenshot 2020-12-24 at 21 34 42](https://user-images.githubusercontent.com/70904578/103103033-09b28100-4630-11eb-9efc-32acb0ba78be.png)

**Comment by VijiYB** [comment]
isAffinitized=true shows up for the preferred zone and shows false for other AZ


","azList":[{"uuid":"d4e923ae-2f54-4363-9ad1-3f864bd1cdca","name":"us-west-2c","replicationFactor":1,"subnet":"subnet-1598fa4e","numNodesInAZ":1,"isAffinitized":false,"affinitized":false},{"uuid":"8e8e97cc-72d8-455a-b2f6-15a0f07a1b8a","name":"us-west-2b","replicationFactor":1,"subnet":"subnet-eb77a48d","numNodesInAZ":1,"isAffinitized":false,"affinitized":false},{"uuid":"1b9d4676-4d75-4128-b0b0-857809faac32","name":"us-west-2d","replicationFactor":1,"subnet":"subnet-05b0315804f92030c","numNodesInAZ":1,"isAffinitized":true,"affinitized":true}]}]}]},"index":0}],"preflight_checks":null,"nodePrefix":"yb-dev-viji-242-t6","rootCA":null,"userAZSelected":false,"resetAZConfig":false,"updateInProgres
