### ISSUE TITLE
[Platform] VPCs crosslink failed during creation of AWS provider

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#6748]
AWS Account - KaliYuga
AWS cloud metadata:
  instance-id: “i-09b42e182a0fdb36a”
  privateIp: “172.152.25.86"
  region: “us-east-1”
  vpc-id: “vpc-5622082d”

Function _cross_link_regions()_ [from aws/cloud/utils.py] does cross link of all VPCs received from _bootstrap_individual_region()_ with the addition of VPC received from the cloud metadata. If a set of VPCs returned by _bootstrap_individual_region()_ contains VPC from the metadata, the function fails (it tries to do the cross link of two VPCs with the same name, as we have two same items in the list of VPCs).

It is not a regression as this code exists for a long time. May be something is changed in the AWS account settings. But anyway, we should check such case in our code.

**Comment by skorobogatydmitry** [comment]
Patch draft: https://phabricator.dev.yugabyte.com/D10221

**Comment by skorobogatydmitry** [comment]
Checked, patch works.

**Comment by skorobogatydmitry** [comment]
Fixed in master and backported to 2.4.

**Comment by skorobogatydmitry** [comment]
Backport revision: https://phabricator.dev.yugabyte.com/D10345
