### ISSUE TITLE
Upgrade failed while using with kubernetes and helm 3

### ISSUE THREAD

**Issue by virtyos** [yugabyte/yugabyte-db#6753]
I'm trying to upgrade my yugabytedb cluster installed on microk8s:

`microk8s helm3 upgrade --set replicas.tserver=5 yb-demo yugabytedb/yugabyte --namespace yb-demo`

But getting this error:

`Error: UPGRADE FAILED: cannot patch "yb-tserver" with kind StatefulSet: StatefulSet.apps "yb-tserver" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && cannot patch "yb-master" with kind StatefulSet: StatefulSet.apps "yb-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

**Comment by bhavin192** [comment]
Let's continue the discussion on https://github.com/yugabyte/yugabyte-db/issues/6746
Duplicate https://github.com/yugabyte/yugabyte-db/issues/6746
