### ISSUE TITLE
[platform] Created date showing up as "Invalid date" in Universes/Dashboard pages

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6756]
For users accessing Universes Page -or- Dashboard page from IST timezone, the "Created" date is showing up as "Invalid date".

![image](https://user-images.githubusercontent.com/68868569/103263368-88732b00-495c-11eb-81f5-d201b8670e82.png)

**Comment by nishantSharma459** [comment]
I've cross-checked it and I found that the API is sending the data in some java formatted way which is causing the issue in the front for example if you look at the '/tasks' API, it's sending the 'date' in the epoch manner no conversion in that but if you look at the '/universes' API we have som java formatted date. So, it'll be good if there's no conversion from the back-end.

In this regard, assigning the ticket to a back-end engineer.
