### ISSUE TITLE
[platform] Unable to reuse On-premise instance incase previouse universe failed / deleted

### ISSUE THREAD

**Issue by jaydeepkumara** [yugabyte/yugabyte-db#6758]
Steps:-
1. Configure On-premise provider
2. Create the universe.
3. Delete the previously created universe.
4. Goto On-premise provider manage instance page, the previous instance will have the universe as n/a and it not allowed to delete.
5. Goto create Universe, The previous instance is not appearing while creating.

### Manage instance screenshot, after deleting universe, Delete is disabled for unattched intance
![Screenshot from 2020-12-29 20-24-00](https://user-images.githubusercontent.com/16913155/103292823-9c7a6380-4a14-11eb-89d3-933f9dc9af86.png)

### Availability zone is not appearing even if one instance is not attached to any universe.
![Screenshot from 2020-12-29 20-26-44](https://user-images.githubusercontent.com/16913155/103292906-cd5a9880-4a14-11eb-9cbd-3e5bde4d5f50.png)

**Comment by mahendranbhat** [comment]
https://github.com/yugabyte/yugabyte-db/pull/8263
2.4 backport PR

**Comment by mahendranbhat** [comment]
Backported to 2.4
