### ISSUE TITLE
[platform]Create universe is disabled if we try invalid then valid configuration

### ISSUE THREAD

**Issue by jaydeepkumara** [yugabyte/yugabyte-db#6759]
Steps:-
1. Setup AWS provider properly
2. Setup On-premise provider but don't attach any instance to this provider.
3. Got Universe page and click on create Universe.
4. Select provider as On-premise and select region, change node to 1, and Replication Factor as 1. Availability Zone will not appear and the create button is disabled (valid scenario)
5. Change provider to AWS and change the region, Now this is a valid configuration still create button is disabled.

### Image1
![Screenshot from 2020-12-29 20-41-19](https://user-images.githubusercontent.com/16913155/103293683-57573100-4a16-11eb-9580-b0edec6878a5.png)

### Image2
![Screenshot from 2020-12-29 20-41-56](https://user-images.githubusercontent.com/16913155/103293714-663de380-4a16-11eb-94aa-c2d948445680.png)

### Image3
![Screenshot from 2020-12-29 20-41-38](https://user-images.githubusercontent.com/16913155/103293700-5e7e3f00-4a16-11eb-9b93-b87c89921b58.png)

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/6815
