### ISSUE TITLE
[platform] Avaibility zone waring message and error message not reseting if changed provider.

### ISSUE THREAD

**Issue by jaydeepkumara** [yugabyte/yugabyte-db#6760]
Steps:-
1. Configure 2 providers.
2. Go and try to create the universe.
3. Try to get an error message/warning message for the Availability Zone.
4. Change Provider.
5. Error message or warning message is still showing without any Availability Zone.

### Warning message is still showing
![Screenshot from 2020-12-29 20-53-13](https://user-images.githubusercontent.com/16913155/103294564-1cee9380-4a18-11eb-9458-9d233a0f8274.png)

### Error message is still appearing 
![Screenshot from 2020-12-29 20-54-09](https://user-images.githubusercontent.com/16913155/103294633-3d1e5280-4a18-11eb-981f-19f7566508d1.png)

**Comment by nishantSharma459** [comment]
I'm putting this ticket on the ToDo list. I've figured there're lots of issues with the Availability Zone. I need to get deep into the code to debug the issue. So, in that regard will take it up next week.

**Comment by gaurav061** [comment]
PR:https://github.com/yugabyte/yugabyte-db/pull/6815
