### ISSUE TITLE
Kafka Connect YugabyteDB Sink Connector doesn't work on Kafka 2.6.0

### ISSUE THREAD

**Issue by aanyudha** [yugabyte/yugabyte-db#6770]
when run the Kafka Connect YugabyteDB Sink Connector in standalone mode, its always keep error and cannot send data to database.

always give error and kill the service automatically

**Comment by ddorian** [comment]
Hi @aanyudha 

Please explain your setup and paste all the errors that you're getting.

**Comment by ddorian** [comment]
Hi @aanyudha 
Closing this issue because of not responsive. 
Please comment if you're hitting it again by pasting the error message.
