### ISSUE TITLE
[Platform UI] Certificates UI improvements

### ISSUE THREAD

**Issue by sshev** [yugabyte/yugabyte-db#6773]
- [x] Move certificates configuration to the Security config
- [x] Add missing data in Certificate Details modal
- [x] Fix text labels/placeholders in Add Certificate modal
- [x] Fix edit universe bug with not showing the root certificate

**Comment by sshev** [comment]
Master issue https://github.com/yugabyte/yugabyte-db/issues/6584

**Comment by chirag-yb** [comment]
@sshev @streddy-yb This will need to backport to 2.4 alongside the entire TLS story for bringing custom CA certs.
