### ISSUE TITLE
ysql: use all rather than 0.0.0.0/0, ::0/0 in hba conf

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6784]
From https://www.postgresql.org/docs/11/auth-pg-hba-conf.html,

> 0.0.0.0/0 represents all IPv4 addresses, and ::0/0 represents all IPv6 addresses.

> You can also write all to match any IP address

"all" is simpler and only takes one line, so we should switch to that.  This involves the default HBA config in `src/yb/yql/pgwrapper/pg_wrapper.cc` `WritePgHbaConfig` and docs.  **Docs should be done separately** (maybe create a separate issue to track it).

**Comment by pratikSethi** [comment]
Hi @jaki, I would like to work on this. Can I take this up?

**Comment by jaki** [comment]
Hi, @pratikSethi.  Yes, you can.

**Comment by jaki** [comment]
Hi, @pratikSethi.  Have you made any progress on this or plan on doing so in the next few days?  If not, I'd like others to feel welcome picking this up.

**Comment by pratikSethi** [comment]
Hi @jaki, please give me time till Monday. I intend to work on it tomorrow or day after as I usually don't get time during the weekdays. If there is no update from me by then feel free to assign it to someone else. Thanks for your patience.

**Comment by m-iancu** [comment]
Fixed by 784f61b.
