### ISSUE TITLE
TestPgRegressTablespaces#testPgRegressPartitions fails

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6788]
On my dev server, running ybd --java-test 'org.yb.pgsql.TestPgRegressTablespaces#testPgRegressPartitions' gave me timeout error.

Over https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F71228%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgRegressTablespaces__testPgRegressPartitions%2Forg.yb.pgsql.TestPgRegressTablespaces-output.txt?class=org.yb.pgsql.TestPgRegressTablespaces&max_lines=3000&name=testPgRegressPartitions&start_line=3001 :

the output was different:
```
4334 | 36 pg_default \| postgres \| \| \| \| 608 bytes \| \| 36 pg_default \| postgres \| \| \| \| 541 bytes \|
-- | --
```

**Comment by deeps1991** [comment]
Fixed as part of  rYBDB39d7bfa4cd9a (Issue #6771)
