### ISSUE TITLE
[YW] Do not crash on clock skew becoming large in 2.4 for Platform universes

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6794]
Default behavior in 2.4 is to crash if the clock skew between nodes goes beyond 500 ms. The plan is to disable it for Platform universes until we know more about how often this happens on customer environments. We will still have a graph showing the max clock skew across a universe in 2.4

@bmatican @streddy-yb

**Comment by streddy-yb** [comment]
cc @SergeyPotachev
