### ISSUE TITLE
[Platform] Restore of large number of keyspaces/tables fails with '413 Request Entity Too Large'

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#6817]
The default value for `play.http.parser.maxMemoryBuffer` in the yugabyte server is too small to process a restore request of around 100 tables.

Reproduction Steps:

- Create a universe with 200 tables within YCQL keyspaces
- Create a YCQL backup of all keyspaces, with all tables in keyspaces
- Run a restore of the resulting `Universe backup`
- Observe the POST request to `api/v1/customers/<uuid>/universes/<uuid>/backups/restore` fails with `413 Request Entity Too Large`

The issue can be worked around by adding the `play.http.parser.maxMemoryBuffer` setting in `application.docker.conf`

```
play.http.parser.maxMemoryBuffer=300KiB 
```

**Comment by kmuthukk** [comment]
thx for reporting the issue here, @tvesely !

**Comment by daniel-yb** [comment]
@sb-yb I'm assigning this to you as part of the API interface for sending/receiving backups since this will most likely have to be bumped up higher than 300kb to receive backup files.

**Comment by sb-yb** [comment]
This one is actually unrelated to sending and receiving backups. Its not some big file but just a json node. So content type is `"application/json"` for such case  `play.http.parser.maxMemoryBuffer` should fix the issue.

For other issue I am using multipart/form-data and for that one needs to set  `play.http.parser.maxDiskBuffer`

So similar but not same issues and hence will fix in separate PRs.
