### ISSUE TITLE
[Platform] Preflight checks for manual provisioning do not match regular provisioning

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#6819]
When running the `provision_instance.py` script that's generated for manual provisioning, the preflight checks performed are different (shorter) than if platform performed it.

**Comment by VijiYB** [comment]
Validated. Preflight checks by manual provisioning 
Failed preflight checks!
{
  "(Prometheus) No Pre-existing Node Exporter Running": false, 
  "Internet Connection": true, 
  "SSH Connection": true, 
  "(Prometheus) /var/run/prometheus is writable": true, 
  "(Prometheus) /etc/prometheus is writable": true, 
  "Sudo Access to Python": true, 
  "(Mount Point) /data is writable": true, 
  "(Prometheus) /lib/systemd/system/node_exporter.service is writable": true, 
  "Yugabyte User in Yugabyte Group": true, 
  "(PAM Limits) /etc/security/limits.conf is writable": true, 
  "Try Ansible Command": true, 
  "(Prometheus) /opt/prometheus is writable": true, 
  "(Prometheus) /var/log/prometheus is writable": true, 
  "(Prometheus) /var/lib/prometheus is writable": true
}
