### ISSUE TITLE
Add tablet server readiness to yb-ts-cli

### ISSUE THREAD

**Issue by jameshartig** [yugabyte/yugabyte-db#6825]
Right now there's no way to determine if a tablet server has bootstrapped and is ready without calling the RPC method `IsTabletServerReady`. It would be useful if this was exposed in `yb-ts-cli` so we can determine when deploying if it's safe to continue the playbook and start running DDL commands and/or remove a leadership blacklist.

**Comment by bmatican** [comment]
This should be pretty straightforward to implement, as we already have the RPC work done.

We just need, in `yb-ts-cli`, to call the respective RPC method, on the TS proxy. For testing this, we should be able to do this locally with `yb-ctl`
- create a local cluster
- create a table on it
- restart a TS
- have a loop in the background using `yb-ts-cli` to catch the TS responding with an error, before ultimately responding success

We should be able to do the same in a unit test, with a simple flag to sleep and delay local bootstrapping.
