### ISSUE TITLE
Typo in https://download.yugabyte.com/#macos

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#6840]
DB SERVER > X64 > line 3 > yugabyted must be changed to yugabyte

**Comment by lizayugabyte** [comment]
Trying to find to this .md file. It's not under _docs_

**Comment by ddorian** [comment]
@lizayugabyte it's fine, it's referencing https://docs.yugabyte.com/latest/reference/configuration/yugabyted/ .
Example: https://docs.yugabyte.com/latest/quick-start/create-local-cluster/macos/

**Comment by lizayugabyte** [comment]
Thanks for checking. I misunderstood the command.
