### ISSUE TITLE
[DocDB] Display placement information for tables in the master UI

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#6841]
Today we display lots of useful information in the TserverIP:7000/table?id=<table_id>.
With Row Level Geo Partitioning, we now support setting placement per table using the yb-admin command line tool. In future, the decision for where a YSQL table should be placed in would come with Tablespaces.
With such features, we would also need an easy way to figure out the placement for a table, whether it was explicitly set using yb-admin tool or through YSQL tablespaces, or if its placement just defaults to the cluster config.

The function CatalogManager::ResolveReplicationInfo is used by the YB-Master to determine the placement for a table. This should also be used to show placement for a table on the Master UI.

**Comment by bmatican** [comment]
Note, @deeps1991 and @rahuldesirazu should be great points of contact for this.

**Comment by zhaoalex** [comment]
If there's no table level override, should we display the cluster level placement or just show nothing in the table UI?

**Comment by bmatican** [comment]
Good question @zhaoalex , I'd probably go with whatever the LB decides as well, which right now would be the cluster level settings, as the intention here would be to figure out where the tablets for this table *should be*
