### ISSUE TITLE
ysql: PgDocReadOp don't piggyback backfill on read time being set

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6854]
For upcoming fix for issue #6333, determining whether a pg read request is for backfill will be assumed off of whether read time is set.  Although that is safe for now since the only way it is set is when

1. exec params read time is set nontrivial
1. `read_time` is passed to `IndexBuildHeapRangeScanInternal`
1. we call `IndexBackfillHeapRangeScan`

, this can easily become an issue when read time becomes used by something other than backfill in the future.  Separate to perhaps another exec param stating that the request is for backfill.

**Comment by deeps1991** [comment]
This is indirectly fixed as part of #9436
