### ISSUE TITLE
[Platform] Preflight checks for S3 backup storage configuration

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6857]
- At the time of creating S3 backup configuration, do a pre-flight check whether the backup configuration is valid before saving the config.

- When user initiates a manual backup -or- a scheduled backup, check whether S3 bucket is still accessible. This check can be performed on the platform side.

**Comment by jitendra-12113** [comment]
Please review:
https://github.com/yugabyte/yugabyte-db/pull/7028

**Comment by jitendra-12113** [comment]
Created ticket: https://github.com/yugabyte/yugabyte-db/issues/8824(to address update config details)

**Comment by shashwat-yb** [comment]
Validated the S3 backup storage configuration by passing valid credentials, invalid credentials, created backups and verified the appropriate responses.

cc @VijiYB
