### ISSUE TITLE
Support upgrade testing in the Mini Cluster test framework (Java, C++)

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#686]
Jira Link: [DB-6066](https://yugabyte.atlassian.net/browse/DB-6066)
We need to be able to install binaries for a previous version of YugaByte from within tests, load some data, then upgrade to the current version being tested.

Over time we might test migrations from multiple old versions to the current version.

The test itself could be pretty generic, e.g. write some data in multiple formats, then restart with the new version and read that data and possibly also overwrite it.

[DB-6066]: https://yugabyte.atlassian.net/browse/DB-6066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mbautin** [comment]
Also rolling restarts under load need to be tested.

**Comment by rthallamko3** [comment]
Covered by Hari's work.
