### ISSUE TITLE
[Platform] Add env variable for specifying postgres username

### ISSUE THREAD

**Issue by awitten-yb** [yugabyte/yugabyte-db#6892]
It could be nice to be able to specify the postgres user name as an environment variable before running `sbt run`, similar to the DB_PASSWORD env variable.

**Comment by jaki** [comment]
https://www.postgresql.org/docs/11/libpq-envars.html says there's `PGUSER` and `PGPASSWORD`.  I'm not sure what `DB_PASSWORD` is, but I think it's also unnecessary.

```sh
./bin/yb-ctl create --tserver_flags "ysql_enable_auth=true"
PGUSER=yugabyte PGPASSWORD=yugabyte ./bin/ysqlsh
```

I'm not familiar with platform, so I could be wrong.

**Comment by daniel-yb** [comment]
@jaki this is for our internal platform connection string to our local postgres instances. Not something defined for YB/Postgres. (See: https://github.com/yugabyte/yugabyte-db/blob/master/managed/src/main/resources/reference.conf#L13)

**Comment by awitten-yb** [comment]
I think what makes this useful is that it allows us to run the platform locally without having postgres installed.  Postgres can just be running in a container and we can still specify a username and password.
