### ISSUE TITLE
[YW][Replicated]Allow platform to specify min TLS version for its own frontend

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6893]
nginx config for replicated and helm needs to include an optional directive like `ssl_protocols TLSv1.2;` based on configurable user input from replicated or helm values.

Related to #6671

**Comment by streddy-yb** [comment]
This issue is tracking Replicated flow specific changes and #7410 is tracking helm charts changes.

**Comment by streddy-yb** [comment]
Verified using 2.4.2.0-b35
