### ISSUE TITLE
Delete multiple keys gives error

### ISSUE THREAD

**Issue by rishabh-narvar** [YugaByte/yugabyte-db#692]
<img width="327" alt="screen shot 2018-12-31 at 4 49 18 pm" src="https://user-images.githubusercontent.com/45938774/50559365-3cb12b00-0d1c-11e9-99d2-df610ddc751d.png">

**Comment by ajcaldera1** [comment]
Line 447 of redis_parser.cc indicates:
```
// Note: deleting only one key is supported using one command as of now.
```

**Comment by acube123** [comment]
Hi Rishabh, 
  Our yedis proxy layer does not currently do cross shard operations. So, for now, we only support single-key delete operations.
  
Thanks,
-Amit
 
https://docs.yugabyte.com/latest/api/redis/del/

**Comment by amitanandaiyer** [comment]
Hi Rishabh,
Our yedis proxy layer does not currently do cross shard operations. So, for now, we only support single-key delete operations.

Thanks,
-Amit

https://docs.yugabyte.com/latest/api/redis/del/

**Comment by rishabh-narvar** [comment]
Need to update documentation for del (only supports single key delete operations)

**Comment by amitanandaiyer** [comment]
Done. The website should update the next time docs/ is pushed.

Thanks Rishabh.
