### ISSUE TITLE
Remove un-informative trace log in executor.cc

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6921]
From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F72815%2Fartifact%2Fbuild%2Ftsan-clang-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cassandra_cpp_driver-test%2FCppCassandraDriverTest_BatchWriteDuringSoftMemoryLimit.log?class=CppCassandraDriverTest&max_lines=3000&name=BatchWriteDuringSoftMemoryLimit&start_line=255001 :
```
242981 | [ts-1] | 0117 19:10:23.532269 (+ 353us) executor.cc:2185] Apply
-- | -- | --
242982 | [ts-1] | 0117 19:10:23.532592 (+ 323us) executor.cc:2185] Apply
242983 | [ts-1] | 0117 19:10:23.532928 (+ 336us) executor.cc:2185] Apply
```
Such log took up considerable portion of test output.

The log itself doesn't reveal what was being applied.

We can remove such trace log.

**Comment by bmatican** [comment]
@tedyu I think they're generally a useful proxy for how many items there were in a CQL batch (not sure if useful otherwise). cc @amitanandaiyer 

I'm not sure though why this test has tracing enabled? cc @spolitov

**Comment by amitanandaiyer** [comment]
src/yb/integration-tests/external_mini_cluster.cc seems to enable tracing. We should probably disable it, if we don't need it. Can always turn it on if desired from the commandline.

**Comment by amitanandaiyer** [comment]
I wouldn't necessarily consider this uninformative. For most the debugging, where I've relied on traces, the information that I'm looking for is the time spent number, from the previous line to this line, and to make a mental model of whether there is bottle-neck there or not. The message itself is typically not something that is meant to convey much.
