### ISSUE TITLE
Custom TLS Certificates Workflow Documentation starting YB 2.4.0

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#6923]
Yugabyte Platform provides the ability to enable node-to-node and node-to-client encryption at the time of universe creation.
In the 2.4.0.0 release, Yugabyte Platform provides a workflow to use your custom TLS certificates for node-to-node communication and client-to-node communication when you’re deploying a Yugabyte Universe on an On-premise Cloud Provider. Yugabyte Platform also provides a workflow to rotate your custom certificates. 

This docs enhancement will be added to YB Platform, Security section at : 
https://docs.yugabyte.com/latest/yugabyte-platform/security/enable-encryption-in-transit/

Internal draft of this doc is available at 
https://docs.google.com/document/d/192yWM7nTAvdcsh9vFUq_0043X8kFKTbqCTPtQHuhZlk/edit#heading=h.armbt5t3ovyu

**Comment by lizayugabyte** [comment]
The doc is ready and has been reviewed by Chirag as part of #6932. The only thing left is to publish it on a new 2.4 branch (that doesnt' exist yet).
