### ISSUE TITLE
[YSQL] Starting YB with single node and YSQL API server bound to eth0

### ISSUE THREAD

**Issue by hackintoshrao** [yugabyte/yugabyte-db#694]
- Need a way to start a single node, rf=1 cluster with YSQL API enabled and the rpc server bound to eth0.
- Need to add corresponding docs too.

**Comment by m-iancu** [comment]
I think this generally addressed by the `yugabyted` project.
See the docs here: https://docs.yugabyte.com/latest/reference/configuration/yugabyted/#root (including the `--listen bind-ip` option).
