### ISSUE TITLE
[docs] YSQL expression indexes (including json)

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#6944]
Explain some expression indexes in YSQL, including indexing json attributes.
Also from https://blog.yugabyte.com/sql-puzzle-partial-versus-expression-indexes/

**Comment by bllewell** [comment]
I recommend simply showing the classic example:

```
create table t(k serial primary key, last_name text not null);
...
create index t_last_name on t (lower(last_name));
```

with an example query. Include a note about the need to spell the expression in the query identically to how it's spelled in the `create index` statement.

Then add a link to [Create indexes and check constraints on JSON columns](https://docs.yugabyte.com/latest/api/ysql/datatypes/type_json/create-indexes-check-constraints/).

**Comment by datamgmt** [comment]
Brought up by a customer today that it was missing (they had referred to https://www.postgresql.org/docs/11/indexes-expressional.html) after seeing a Karthik presentation that said we supported expression indexes so +1 here
