### ISSUE TITLE
[Platform] [2.4] Limit tasks queried in API call by default to 2000

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6945]
We have proper task pagination and GC in 2.6. For 2.4, however, we could make the tasks UI more functional by adding a `LIMIT 2000` to our tasks db query at https://github.com/yugabyte/yugabyte-db/blob/e98203c9d4cd8180fb3c173c3f43cb78548979f8/managed/src/main/java/com/yugabyte/yw/controllers/CustomerTaskController.java#L69 so we don't end up with a spinning task UI for Platform instances that accumulate many tasks over time.

**Comment by mahendranbhat** [comment]
@VijiYB Please LMK once the testing is done, then will move to 2.6 and 2.4

**Comment by RP1807** [comment]
@mahendranbhat Validated it with the latest master as well as on Portal. Did sanity testing around task API and checked universe task tab and global task page. Working as expected.

**Comment by mahendranbhat** [comment]
2.6 PR https://github.com/yugabyte/yugabyte-db/pull/8624

**Comment by mahendranbhat** [comment]
2.6 backport is done, facing some issues in 2.4 backport. I will update the same once 2.4 backport is done.

**Comment by mahendranbhat** [comment]
2.4 backport is also done.
