### ISSUE TITLE
[docdb] Allow for leader balancing even when dealing with DEAD nodes

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#6947]
Currently the LB stops operating on a table, if it detects tablet peers on servers the master considers dead (60s without a successful heartbeat).

We should investigate how we can unblock that, as after a server dies, the master should still be able to balance leaders across the remaining N-1 servers.

This is also relevant in the context of enabling `enable_register_ts_from_raft` by default, which would mean now, on a master leader failover, the LB would stop working for any tablets still present on a dead node.

**Comment by rahuldesirazu** [comment]
These steps need some testing/verification, but I believe we can do the following:
1. Get all tservers intead of just all live tservers in call to GetAllReportedDescriptors ClusterLoadBalancer::ResetGlobalState.
2. Add some state for each entry in per_ts_meta_/per_tablet_meta_ to indicate a dead tserver or dead peer.
3. If a tablet has a dead peer, add logic to skip doing data move operations (but allow leader move ops).

A simple test will be to create an RF=3 cluster with a few tables, kill a tserver and failover the master leader, and then assert that no load move ops occurred, but leaders are completely balanced
