### ISSUE TITLE
[YCQL] Allow primary key column with DECIMAL type in Java partition-aware driver

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#6966]
Currently, since DECIMAL encoding is not implemented yet on the Java side, we cannot compute the proper hash code for one-hop query routing in the driver. Therefore we throw an unsupported error.
Instead, we should allow the type to be used, but only do the one-hop if possible.
If not (e.g. for DECIMAL type) we can default to using random or round-robin node selection (which can require two hops to re-route internally to the right node). 

The relevant code is: 
https://github.com/yugabyte/cassandra-java-driver/blob/3.8.0-yb-x/driver-core/src/main/java/com/yugabyte/driver/core/policies/PartitionAwarePolicy.java#L277
For instance, we could just write to channel the CQL decimal encoding as is, and worst case, where it differs from YB we'll just hit a suboptimal node.

**Comment by nchandrappa** [comment]
A new driver released to fix the issue.

```
<dependency>
  <groupId>com.yugabyte</groupId>
  <artifactId>cassandra-driver-core</artifactId>
  <version>3.8.0-yb-6</version>
</dependency>
```

**Comment by kmuthukk** [comment]
@nchandrappa -- could you put a link to the relevant driver side commit also here?

**Comment by nchandrappa** [comment]
Corresponding [commit](https://github.com/yugabyte/cassandra-java-driver/commit/b95006d94a29b2ab1dc2e39889e2ddf93e6f34c7) on YCQL Java driver repo.
