### ISSUE TITLE
Can't connect from EMS SQLManager for Postgres

### ISSUE THREAD

**Issue by juanfernandoe** [YugaByte/yugabyte-db#697]
Software version: EMS SQLManager for PostgreSQL version 5.9.4

Error:
SHOW variable not supported
LINE 1: SHOW search_path

HINT: Please contact yugabyte for its release schedule.

**Comment by ravimurthy** [comment]
SET and SHOW commands are currently not supported. But they should be available fairly soon in a few weeks as part of the next release.

**Comment by schoudhury** [comment]
@juanfernandoe want to draw your attention to our current integration with TablePlus as documented here: https://docs.yugabyte.com/latest/develop/tools/tableplus/
it certainly is not as rich as EMS SQLManager but hoping it is a good starting point while we add the additional commands to YSQL.

**Comment by m-iancu** [comment]
Closing as support for `SET` and `SHOW` was done in 816d2e4e9907de69428dd9678437d9ddb7dc5fcb. See also https://github.com/YugaByte/yugabyte-db/issues/699.
