### ISSUE TITLE
[YSQL] Support for "create table as select" 

### ISSUE THREAD

**Issue by ravimurthy** [YugaByte/yugabyte-db#698]
Enable support for "create table as select" command, add tests and documentation.

**Comment by nocaway** [comment]
CREATE TABLE AS SELECT statement is processed in 2 steps.
- Use tuple-descriptor to create the target table.
- Query data and insert it into the created table.

Note that YugaByte don't create TOAST table for oversize column.
We create one table, and let YugaByte storage layer (DocDB) handle oversize data.

**Comment by nocaway** [comment]
This issue has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/a82c32abe8cae3b01def94bcbd8147a31140eca5
