### ISSUE TITLE
[Platform] Script to create a universe from JSON config file

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7002]
Provide a script that creates a universe using these three command line arguments: Platform URL, API token, and path to the file containing the Universe config in JSON format.
cc @chirag-yb

**Comment by chirag-yb** [comment]
User should be able to dump a json payload from an existing universe and use that as an input for the script. 
Need to make sure this works for 2.2.3 and 2.4.0

**Comment by streddy-yb** [comment]
We need scripts for the following actions:
- Dump json payload for a given universe
- Create a universe
- Destroy an existing universe

**Comment by jaydeepkumara** [comment]
PR link :- https://github.com/yugabyte/yugabyte-db/pull/7302/files
