### ISSUE TITLE
 can we make the write of intents parallel with the write of txn record , and don't create the txn record until necessary for better performance ? 

### ISSUE THREAD

**Issue by triump2020** [yugabyte/yugabyte-db#7003]
Hi  ,  Team ! 
       From the view of  this[ write up](https://docs.yugabyte.com/latest/architecture/transactions/transactional-io-path/) ,  one complete transaction commit  cost at least three rounds of raft consensus .   

         can we make the write of intents parallel with the write of txn record ?  i  think we can do it by follwing steps .

          1. we can add a timestamp field which indicates the liveness of the txn into 
             the intent record and txn status record. A conflicting txn can proven the  txn's liveness
             through validating the timestamps of them whether within the timeout-period of transaction or not .

          2.  we can remove the **created** status in the txn status record, 
               namely we only need three types of status : **pending , committed, abort**

          3.  Based on the above , yql transaction manager can lazily write the txn status record , 
               until it found the transaction is nearly timeout; 

               in other words, we should make effort to make  the **pending status creation** of txn status record 
               parallel with the write of last batch of intents,  unless we encounter a big transaction. 
             

           Through the three stemps ,  we can reduce IO in cases of small transaction , more important , 
           we can pave the way for the implementaion of  **parallel commit**  which cockroach did and TIDB 5.0 would do

**Comment by tedyu** [comment]
Thanks for the idea.

bq. until it found the transaction is nearly timeout

How does transaction manager determine that the transaction is close to timing out ?
Does it check, e.g. 1 second prior to the actual timeout ?

**Comment by triump2020** [comment]
@tedyu  thanks for your response !    
 txn manager just need to create the txn record
 before the first write-intents's timestamp  getting too old--- lags behind the current timestamp 
 more than the transaction-timeout period. 
  
The issue comes up is to acheive  the goal of " Parallel Commit ". Yesterday, @mbautin  gived me a detailed response on the [slack channel!](https://yugabyte-db.slack.com/archives/CNVCKJGHK/p1611604230057700)
