### ISSUE TITLE
[Platform] [UI] Restore backup dialog allows universe name to be unselected

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#7007]
Repro steps
1. Create a backup (SQL namespace in this case but probably not relevant).
2. After the backup succeeds, click Restore Backup on the line item in the Backups page.
3. Change the db name to yugabyte1, do not select Universe name. Click OK.

<img width="452" alt="Screenshot 2021-01-27 121721" src="https://user-images.githubusercontent.com/8207010/106051349-2f9ecb80-609d-11eb-9c2b-420f941c2848.png">

Behavior:
The backup proceeds to restore into the same universe.

Expected:
Error since universe wasn't selected. Also hope UI is not able to choose a random univ as the target in this case.

**Comment by shashwat-yb** [comment]
Validated this issue on 2.6  b-57, Create Backup dialog doesn’t  have the "Universe" field to change it or unselect it.

cc @VijiYB
