### ISSUE TITLE
Segmentation fault on a fresh new install

### ISSUE THREAD

**Issue by chelbos** [yugabyte/yugabyte-db#7010]
anyone knows why this is happening?

/usr/local/src/yugabyte-2.5.1.0/bin/yb-admin --init_master_addrs 127.0.0.1:7100 list_all_masters
*** Aborted at 1611806672 (unix time) try "date -d @1611806672" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x200000001) received by PID 12225 (TID 0x7fba3be49280) from PID 1; stack trace: ***
    @     0x7fba2c4e0ba0 (unknown)
    @     0x7fba352cce66  yb::rpc::OutboundCall::InitHeader()
    @     0x7fba352d1111  yb::rpc::OutboundCall::SetRequestParam()
    @     0x7fba352d9f86  yb::rpc::Proxy::DoAsyncRequest()
    @     0x7fba352da9c8  yb::rpc::Proxy::SyncRequest()
    @     0x7fba3712b124  yb::master::MasterServiceProxy::ListMasters()
    @     0x7fba3b80ab8b  yb::tools::ClusterAdminClient::InvokeRpc<>()
    @     0x7fba3b7ef17f  yb::tools::ClusterAdminClient::DiscoverAllMasters()
    @     0x7fba3b7eff25  yb::tools::ClusterAdminClient::Init()
    @           0x416b7b  yb::tools::ClusterAdminCli::Run()
    @           0x40f9e1 main
    @     0x7fba2bb48825 __libc_start_main
    @           0x410339 _start
    @                0x0 (unknown)
Segmentation fault

**Comment by chelbos** [comment]
the server is Proxmox container and I have Unbuntu 20.04

**Comment by ddorian** [comment]
Hi @chelbos 
Can you tell more what steps did you use ? And what are the specs of your machine (ram,cpu,ssd,hdd)
Does `./bin/yugabyted start` work creating a cluster from quickstart https://docs.yugabyte.com/latest/quick-start/install/linux/ ?

**Comment by chelbos** [comment]
The machine is a fresh new installed Ubuntu 20.04 with 8 cores and 8GB of RAM (again this is a container in Proxmox, I've tried with a VM also and same issue) 
But it did work on a local VM created in VMWare on my machine and with a VM in Linode. I need it to work in the Proxmox container, since I have my own cloud. 

The steps are the ones described online for starting a local master 

wget https://downloads.yugabyte.com/yugabyte-2.5.1.0-linux.tar.gz
tar xvfz yugabyte-2.5.1.0-linux.tar.gz && cd yugabyte-2.5.1.0/
./bin/post_install.sh
./bin/yugabyted start

Then when I check /usr/local/src/yugabyte-2.5.1.0/var/logs/yugabyted.log I see the below:

[yugabyted start] 2021-01-28 14:12:32,455 INFO:  | 0.0s | master started running with PID 12488.
[yugabyted start] 2021-01-28 14:12:32,455 ERROR:  | 0.0s | Failed to create symlink from /usr/local/src/yugabyte-2.5.1.0/var/data/yb-data/master/logs to /usr/local/src/yugabyte-2.5.1.0/var/logs/master
[yugabyted start] 2021-01-28 14:12:32,455 INFO:  | 0.0s | Waiting for master
[yugabyted start] 2021-01-28 14:12:32,456 INFO:  | 0.0s | run_process: cmd: [u'/usr/local/src/yugabyte-2.5.1.0/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2021-01-28 14:12:32,680 INFO:  | 0.3s | run_process returned -11:
OUT >>

I suppose the issue is when running yb-admin and that's why I've started the post with that command

Thank you! I have big hopes in using yugabytedb in building grate new things :)

**Comment by ddorian** [comment]
@chelbos is there a core dump generated ? Can you upload it ?

**Comment by chelbos** [comment]
I don't see any core dump, where should I look for it?

You can see below master.err file

root@yugabytehasura:/usr/local/src/yugabyte-2.5.1.0# cat /usr/local/src/yugabyte-2.5.1.0/var/logs/master.err
*** Aborted at 1611806611 (unix time) try "date -d @1611806611" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 12166 (TID 0x7f64aab0c700) from PID 8; stack trace: ***
    @     0x7f64b84d8ba0 (unknown)
    @     0x7f64be5ace3d  yb::rpc::OutboundCall::InitHeader()
    @     0x7f64be5b1111  yb::rpc::OutboundCall::SetRequestParam()
    @     0x7f64be5b9f86  yb::rpc::Proxy::DoAsyncRequest()
    @     0x7f64be5ba8ea  yb::rpc::Proxy::AsyncRequest()
    @     0x7f64c1593396  yb::consensus::ConsensusServiceProxy::GetNodeInstanceAsync()
    @     0x7f64c4e0f7cb  yb::consensus::SetPermanentUuidForRemotePeer()
    @     0x7f64c7a67f3f  yb::master::SysCatalogTable::SetupConfig()
    @     0x7f64c7a6ce38  yb::master::SysCatalogTable::CreateNew()
    @     0x7f64c794d729  yb::master::CatalogManager::InitSysCatalogAsync()
    @     0x7f64c795c142  yb::master::CatalogManager::Init()
    @     0x7f64c7a192b6  yb::master::Master::InitCatalogManager()
    @     0x7f64c7a193c5  yb::master::Master::InitCatalogManagerTask()
    @     0x7f64bce16b43  yb::ThreadPool::DispatchThread()
    @     0x7f64bce1331e  yb::Thread::SuperviseThread()
    @     0x7f64b84d0694 start_thread
    @     0x7f64b7c0641d __clone
    @                0x0 (unknown)

**Comment by chelbos** [comment]
If you want to replicate, I am using Proxmox Virtual Environment 6.3-3

**Comment by ddorian** [comment]
Can you search for any ".core" files in the directory of yugabyte ? (where you extracted)

**Comment by ddorian** [comment]
Or where does ubunut 20.04 stores core files.

**Comment by chelbos** [comment]
root@yugabytehasura:/usr/local/src/yugabyte-2.5.1.0# find ./ -type f -name "*.core"

returns nothing 

Do you know if I can run gdb on yb-admin?
gdb -ex=r --args /usr/local/src/yugabyte-2.5.1.0/bin/yb-admin --init_master_addrs 127.0.0.1:7100 list_all_masters

I've try this but GDB says "A problem internal to GDB has been detected" and stops

**Comment by chelbos** [comment]
I've just started a new ubuntu 18.04 container with 4 cores, 8GB of RAM, 4 GB of SAWP and the same issue :(

/usr/local/src/yugabyte-2.5.0.0/bin/yb-admin --init_master_addrs 127.0.0.1:7100 list_all_masters
Network error (yb/util/net/socket.cc:537): Unable to establish connection to leader master at [localhost:7100]. Please verify the addresses.

: recvmsg error: Connection refused (system error 111)

**Comment by ddorian** [comment]
@chelbos this is a different error from previously.

Where did you find `--init_master_addrs` ? It should be `--master_addresses`.

**Comment by ddorian** [comment]
Can you also do `./bin/yugabyted collect_logs` and upload the zip file.

**Comment by CristianHuza** [comment]
I have encountered the exact same issue, I don't understand what can be, here is what happened:

1. Get Ubuntu ISO image
2. Install Ubuntu from ISO to vmware machine
3. Setup yugabyte as per your wiki
4. Start yugabyte
All is OK, start/stop work as expected.

Now I did the exact same thing, but on a KVM machine on Proxmox, the absolute exact steps, there are literally 4 commands, no way to mess this up, and the error comes up. Thinking that there must be something wrong somewhere, I did the following:

1. Stop VMware machine
2. Exported the vmdk to raw format
3. Copied the drive to proxmox 
4. Attached the 'drive' that worked on VMware 
5. Start VM and try to start yugabyte

Now it throws the exact same error as the initial kvm machine I set up on Proxmox which is very odd.

`root@yuga01:/usr/local/src/yugabyte-2.5.1.0# ./bin/yugabyted start 
Starting yugabyted...
Found files [u'yb-data', u'master-info'] in data dir /usr/local/src/yugabyte-2.5.1.0/var/data from possibly failed initialization. Removing...
/ Running system checks...Failed to setup master. Exception: Traceback (most recent call last):
  File "./bin/yugabyted", line 888, in setup_master
    if retry_op(self.wait_master, timeout):
  File "./bin/yugabyted", line 2540, in retry_op
    return func()
  File "./bin/yugabyted", line 845, in wait_master
    raise RuntimeError("process died unexpectedly.")
RuntimeError: process died unexpectedly.
`

**Comment by ddorian** [comment]
@CristianHuza can you do `./bin/yugabyted collect_logs` and upload the zip file here ?

**Comment by CristianHuza** [comment]
Hi, the collect_logs command fails, for the fact that it tries to look in a directory that does not exist, I have tried version 2.5.0 too, completely fresh install, and here is what happens. I mention that the post_install step finishes, but at start, this shows up.

` /usr/local/src/yugabyte-2.5.0.0/bin/patchelf --set-interpreter /usr/local/src/yugabyte-2.5.0.0/lib/ld.so vacuumlo
+ /usr/local/src/yugabyte-2.5.0.0/bin/patchelf --set-rpath /usr/local/src/yugabyte-2.5.0.0/lib/yb:/usr/local/src/yugabyte-2.5.0.0/lib/yb-thirdparty:/usr/local/src/yugabyte-2.5.0.0/linuxbrew/lib vacuumlo
root@yuga01:/usr/local/src/yugabyte-2.5.0.0# ./bin/yugabyted start
Starting yugabyted...
- Running system checks...Failed to setup master. Exception: Traceback (most recent call last):
  File "./bin/yugabyted", line 878, in setup_master
    if retry_op(self.wait_master, timeout):
  File "./bin/yugabyted", line 2518, in retry_op
    return func()
  File "./bin/yugabyted", line 835, in wait_master
    raise RuntimeError("process died unexpectedly.")
RuntimeError: process died unexpectedly.

For more information, check the logs in /usr/local/src/yugabyte-2.5.0.0/var/logs



^Croot@yuga01:/usr/local/src/yugabyte-2.5.0.0# ^C
root@yuga01:/usr/local/src/yugabyte-2.5.0.0# ^C
root@yuga01:/usr/local/src/yugabyte-2.5.0.0# ./bin/yugabyted collect_logs
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 1344, in run
    args.func()
  File "./bin/yugabyted", line 352, in collect_logs
    archive.add(logpath)
  File "/usr/lib/python2.7/tarfile.py", line 2034, in add
    recursive, exclude, filter)
  File "/usr/lib/python2.7/tarfile.py", line 2011, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1885, in gettarinfo
    statres = os.stat(name)
OSError: [Errno 2] No such file or directory: '/usr/local/src/yugabyte-2.5.0.0/var/logs/master'

For more information, check the logs in /usr/local/src/yugabyte-2.5.0.0/var/logs
root@yuga01:/usr/local/src/yugabyte-2.5.0.0# 
`
The missing directory is ./var/data/yb-data/master/logs
I have created the missing directory and then collect_logs command worked, so I checked the logs. It seems that the processor of this host does NOT have a required feature, here is the message:

`Not implemented (yb/util/init.cc:69): The CPU on this system (Common KVM processor) does not support the SSE4.2 instruction set which is required for running YB.
`

**Comment by CristianHuza** [comment]
Small update - it seems that changing in Proxmox the CPU type to host (native) fixed the issue, the daemon started properly, sorry for bothering you, I guess @chelbos can fix the problem in the exact same way.

**Comment by ddorian** [comment]
@CristianHuza 
Yes this is mentioned in our hardware checklist https://docs.yugabyte.com/latest/deploy/checklist/#verify-support-for-sse2

@chelbos is this the same error for you ?

**Comment by chelbos** [comment]
Yes, the issue has been fixed! Thank you!
