### ISSUE TITLE
[Platform] [2.4] AddNode operation fails with timeout

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#7019]
In 2.4, when doing an Add Node operation, platform does not bring up the tserver, so whole operation fails with timeout when waiting for the server to come up.

**Comment by chirag-yb** [comment]
@streddy-yb Seems like a critical issue. Shall this be included in 2.4.1?

**Comment by streddy-yb** [comment]
677c693cb [Backport 2.4][#7019] Platform: AddNode operation fails with timeout
