### ISSUE TITLE
when write stalls happen, heartbeats should still be allowed

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#703]
Seeing wasteful leader elections/ping-pongs under a stress test load where writes stalls/backpressure happens. 

[Note: Write stalls/backpressure can happen when write/ingest rate in the system is much more than ability of system to keep up. For example, default bandwidth allowed for compactions/flushes is controlled by this [gflag](https://github.com/YugaByte/yugabyte-db/blob/6f3bf298bb2914d1676cf37bc679b7fd53ed4eda/src/yb/docdb/docdb_rocksdb_util.cc#L52). If number of SSTable files builds up beyond a threshold because the ingest rate is higher and compactions aren't keeping up, then eventually, writes will stall till system can catch up.]

This was the sequence of events seen during the stress test. 

Earliest occurrence of stopping writes in this run happens on a tablet follower (172-152-27-218):
```
W0105 02:30:58.754338 24544 column_family.cc:598] T 2aac4c66c7b1428f83587c4717e02a56: [default] Stopping writes because we have 48 level-0 files
```
And earliest occurrence of "Couldn't send" an UpdateConsensus RPC from the tablet leader (172-152-22-141) to the above follower node (172-152-27-218) happens exactly 3 seconds later.
*Note: The tablet ID is the same*
```
W0105 02:31:01.800454 24443 consensus_peers.cc:428] T 2aac4c66c7b1428f83587c4717e02a56 P a6a5160efb38414ba0b919536c62f8c7 -> Peer c0c2356137994608adaefc7042f05ea6 ([host: "172.152.27.218" port: 9100], []): Couldn't send request.  Status: Timed out (yb/rpc/outbound_call.cc:435): UpdateConsensus RPC to 172.152.27.218:9100 timed out after 3.000s. Retrying in the next heartbeat period. Already tried 1 times. State: 2
```

This then prompts the follower of tablet 2aac4c66c7b1428f83587c4717e02a56 (172-152-27-218) to trigger a leader election:
```
I0105 02:31:17.683406 25883 raft_consensus.cc:463] T 2aac4c66c7b1428f83587c4717e02a56 P c0c2356137994608adaefc7042f05ea6 [term 1 FOLLOWER]: Fail of leader a6a5160efb38414ba0b919536c62f8c7 detected. Triggering leader election, mode=0
```
But is rejected by leader:
```
I0105 02:31:17.773084 25814 raft_consensus.cc:2363] T 2aac4c66c7b1428f83587c4717e02a56 P a6a5160efb38414ba0b919536c62f8c7 [term 1 LEADER]: Leader election vote request: Denying vote to candidate c0c2356137994608adaefc7042f05ea6 for term 2 because replica is either leader or believes a valid leader to be alive. Time left: 9223362694.741s
```

It appears that if a follower is stalling writes, it is also not getting heartbeats from the leader of the tablet - thus causing wasteful leader election attempts and ping-ponging (because likely the other follower ends up giving the vote to this follower).

We should look into cleanly separating back-pressure on writes from the failure detection/heartbeat mechanism to avoid leaders unnecessarily ping-ponging.

**Comment by bmatican** [comment]
Done as part of 3447339987be2e2f8f7923b04e27788b7bebe103 in #2750
