### ISSUE TITLE
[YSQL] System crash after re-creation of same db.

### ISSUE THREAD

**Issue by uwejan** [yugabyte/yugabyte-db#7037]
Jira Link: [DB-2462](https://yugabyte.atlassian.net/browse/DB-2462)
Hello guys, on my test environment, i have 3 nodes RF3 each 4 GB ram, 2 vcpu. i do create a db and remove it multiple times, till the nodes ram gets filled out, and become unresponsive and some nodes die. note: only create db, run schema, delete same db, create again same db ...etc.
version: 2.5.1.0.

**Comment by kmuthukk** [comment]
@ddorian -- can you help triage this initially -- see if you can repro it in RF=1 setting itself as a first step?

**Comment by uwejan** [comment]
Any update on this, i keep repreducing it.

**Comment by ddorian** [comment]
On a simple `./bin/yugabyted start` locally RF1:

```
create database d;
create table a(id bigserial);
drop database d;
``` 
After running 50 times, the yb-tserver stays under 500MB ram, yb-master ~300MB ram.

Tried the same thing with ~100 (tables+indexes) for 30 databases and same result.


@uwejan can you reproduce with `./bin/yugabyted start` and do `./bin/yugabyted collect_logs` and upload the zip ?

**Comment by ddorian** [comment]
@uwejan can you print a list of the processes that are running in the server when the error happens.
Run `ps ax |grep yugabyte` and paste the output.

**Comment by ddorian** [comment]
Closing as no response from the user.
