### ISSUE TITLE
typeorm support ?

### ISSUE THREAD

**Issue by AmreeshTyagi** [yugabyte/yugabyte-db#7044]
Any plan to support typeorm?
There is one open [issue](https://github.com/typeorm/typeorm/issues/5459) on typeorm as well.

**Comment by ddorian** [comment]
Hi @AmreeshTyagi 

Have you tried it ? It should work out of the box.

**Comment by AmreeshTyagi** [comment]
Thanks @ddorian . 
Sorry, not tried as of now. I was going through `typeorm` code base. They are also using `pg` driver internally, so ideally it should work with `yugabyte` as well. You can close this issue, if not priority on your road-map. 
Just wanted to know, if you guys have any plan to officially support it.
