### ISSUE TITLE
 Error loading on com.yugabyte.yw.models.AlertDefinition.universeUUID 

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#7059]
There is a bug introduced in a previous backport from 10/16/20
12a69e41b44233d6dc9ff4b02930ecd1b2dce849
https://phabricator.dev.yugabyte.com/D9726

We need to remove `columnDefinition = "Text"` from AlertDefinition.universeUUID

```
@Entity
public class AlertDefinition extends Model {
...
  @Constraints.Required
  @Column(nullable = false)
  public UUID universeUUID;
```

Looks like there was no test coverage for this until @SergeyPotachev added this test for his change.
Most likely this is a bug in prod as well.

**Comment by SergeyPotachev** [comment]
Fixed under #7118.
