### ISSUE TITLE
Update YCSB benchmark docs to include Automatic Tablet splitting

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7064]
Currently YCSB docs do not include automatic tablet splitting examples
https://docs.yugabyte.com/latest/benchmark/ycsb-jdbc/

The example content is available at https://docs.yugabyte.com/latest/architecture/docdb-sharding/tablet-splitting/#example-using-a-ycsb-workload-with-automatic-tablet-splitting and should be included in main YCSB benchmark pages as well

**Comment by lizayugabyte** [comment]
@ameyb Do you mind adding a label indicating priority for this ticket?
