### ISSUE TITLE
[DOCS] Connect Databricks Cluster to Yugabyte YSQL with Yugabyte Encryption In-Transit Enabled

### ISSUE THREAD

**Issue by dotyjim-work** [yugabyte/yugabyte-db#7066]
@jeffjewett put together this summary of connecting Databricks Cluster to Yugabyte YSQL with Yugabyte Encryption In-Transit Enabled

This will live in /latest/develop/ecosystem-integrations/

INTERNAL DRAFT: https://docs.google.com/document/d/1B0EPALMq0hIVC9OCPtvMFWoHXERU_XvPDCFOsvbaspY/edit

CC: @nmalladi

**Comment by dotyjim-work** [comment]
@jeffjewett - If I look at the commit https://github.com/yugabyte/tpcc/commit/5b22dd4c843eeef84298ba3ae7c059f8fa78c5b5 , do I read it that while your fix applies to the Databricks - its driven by the driver?

@polarweasel, and @nmalladi - perhaps the key formatting needs to be tied to the driver, and this content can still supplement the spark section.

**Comment by polarweasel** [comment]
@jeffjewett and I met today to talk about this one. He'll take another pass over the doc to add an introduction and make sure the steps are clear, then pass back to me for translation into Markdown.

**Comment by jeffjewett** [comment]
@polarweasel update in GD in the OP ☝️
