### ISSUE TITLE
[docdb] Allow reloading of the config file with 'ts-cli refresh_flags'

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7068]
Postgres allows certain configuration flags to be reloaded with SIGHUP.

Is there a possibility runtime configurable changes in Yugabyte using SIGHUP?

Yb-admin can make changes to some runtime flags but this request is different because putting them in configuration file is also persistent whereas yb-admin is runtime and not persistent after t-server restart.

**Comment by nspiegelberg** [comment]
The original task was to use SIGHUP.  We are trying to move away from using signal handlers for control plane logic, so we implemented this from the 'ts-cli' CLI, passing in the 'refresh_flags' option.

**Comment by nspiegelberg** [comment]
No parameters needed.  Example CLI command: `yb-ts-cli --server_address=127.0.0.1:7100 refresh_flags`
