### ISSUE TITLE
display query text for slow queries

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#707]
When queries take longer than [rpc_slow_query_threshold_ms](https://github.com/YugaByte/yugabyte-db/blob/7ef38921ed0126e65782e0b67cda69227100c57c/src/yb/rpc/inbound_call.cc#L74), the server INFO logs contain something like:

```
I1029 20:20:11.087247 16905 cql_rpc.cc:273] CQL Call from 10.0.1.158:40272 took 11834ms
```

This is nice, but it would be more useful to also show the text of the YCQL statement here as well (similar to how we show the statement text in the active RPCs page - http://host_ip:12000/rpcz).

**Comment by amitanandaiyer** [comment]
Adding the query details to ToString should make it appear here as well.

std::string CQLInboundCall::ToString() const {
  return Format("CQL Call from $0", connection()->remote());
}
