### ISSUE TITLE
[Docs] Document OpenShift cloud provider support

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7081]
- Pre-requisites
- Configure cloud provider

**Comment by lizayugabyte** [comment]
Slack comment by @chirag-yb :
Here is the plan for OpenShift documentation
We need to have two different sets of instructions: Operator based and Helm based (dev docs content pending)
Liza will publish the operator based content and send us a PR to review
She will put a placeholder on different pages for Helm content
Prepare the environment - similar to K8s helm instructions https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes/
Install the software - similar to K8s helm instructions https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes/
Configure Cloud Provider - https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes/
There may be a lot of overlapping between Helm and Operator installation, it's fine to duplicate the content but not lose any instructions.

Slack response by @sanketkedia 
The overall plan for Openshift sounds good.
Regarding general k8s docs improvements, the plan was to address the following
During platform install, show how to get the LB IP.
Be able to bring up internal LBs
We could add NodePort here too
In the k8s provider configuration page, explain how the new flow for specifying a k8s namespace works. This is common to k8s and openshift but kind of necessary in openshift
In the k8s provider configuration page, explain how the service account RBAC has to be set up (this is incomplete and on the wrong page now)
Some of these topics are covered in https://github.com/yugabyte/yugabyte-db/issues/7326
Agree that we need newer screenshots etc in some of these cases.

**Comment by lizayugabyte** [comment]
Linked issue: #7341

**Comment by lizayugabyte** [comment]
Google doc: https://docs.google.com/document/d/1r8V1PkZGNOcnJMsx-vz0jQvRPpVTx8AulMn7Pa1LpoM/edit?ts=602fce22#heading=h.8ck9632g2jwi

**Comment by lizayugabyte** [comment]
Comment by @ameyb in the linked ticket: 
This content should go under a new CLoud Provider - Redhat OpenShift
https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/

**Comment by lizayugabyte** [comment]
Google doc sect 1 and 2: latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/openshift/

**Comment by lizayugabyte** [comment]
Google doc sect 3 to 7: latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift/

**Comment by lizayugabyte** [comment]
Google doc sect 8: latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/openshift/

**Comment by lizayugabyte** [comment]
Google doc sect 9: latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift/
