### ISSUE TITLE
[Docs] Improvements for Kubernetes cloud provider

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7085]
- [ ] New features/improvements tracked here - https://github.com/yugabyte/yugabyte-db/issues/6669
- [ ] https://github.com/yugabyte/yugabyte-db/issues/7048

**Comment by lizayugabyte** [comment]
- Prerequisites
- Configure cloud provider
- Platform backup

To work after doing Platform install; Amey to setup handson session with SEs

**Comment by polarweasel** [comment]
@lizayugabyte can you check to make sure this is done?
