### ISSUE TITLE
[YSQL] Only rebuild PostgreSQL code if it has changed

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#709]
We include the PostgreSQL build as one CMake target in the overall YugaByte CMake project, and we still use `make` for  building PostgreSQL, even though we mostly use CMake + Ninja for the YugaByte build. Running `make` on the PostgreSQL tree where nothing has changed takes around 10 seconds. We should use a "stamp" mechanism (git sha1 + a checksum of git diff) to skip rebuilding PostgreSQL altogether if we think it should not have changed.

**Comment by m-iancu** [comment]
Addressed in [cc77232](https://github.com/yugabyte/yugabyte-db/commit/cc772323bb0516627db47a5b280ff42b2ab6f3d5).
