### ISSUE TITLE
Add user specifyable locations in the list to on-prem workflow on the platform - UI Visualization

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7100]
Add below list of locations in the on-prem workflow since they are not available today in the platform. 

EU West - Ireland or UK
EU East - Istanbul for Softech
EU Central - Frankfurt
EU North - Stockholm
EU South - Milan

Middle East - Bahrain
South Africa - Johannesburg for Obsidian

It would be good to allow users specify locations manually and add GPS coordinates with these manually specified data centers.

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7884
