### ISSUE TITLE
[RFE] Platform - Not able to create more than 1 bucket while creating backups

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7103]
The platform doesn't allow to create more than 1 bucket. 

When creating a cloud location for backups in the Config session users are restricted to creating one bucket location

Customers with multiple databases especially regional requirements will want to have the ability to define multiple and select them when creating a backup

**Comment by tylarb** [comment]
That is to say, one of NFS, one of S3, once of GCS.

Would be great to be able to create several S3 buckets, for example.

**Comment by streddy-yb** [comment]
Multiple config support is tracked as part of #7349
