### ISSUE TITLE
[Platform] Remove thirdparty-deps container from replicated/helm charts

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#7104]
The contents of the thirdparty-deps container are copied into /opt/third-party into the pod when YW is brought up through replicated or helm - https://github.com/yugabyte/charts/blob/7d98c6f9923117a4f2f4de839e263c6bc7611680/stable/yugaware/templates/service.yaml#L156

However, the YW Dockerfile already includes these contents now at /opt/third-party so this is redundant. It doesn't cause any problems but is good for code cleanup.

@daniel-yb

**Comment by daniel-yb** [comment]
This was accomplished in #5605
