### ISSUE TITLE
[YSQL] DataTypes Support

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#711]
This issue is listing all unsupported datatypes in YugaByte Database which can be split into smaller issues and assigned to appropriate developers.

Support for types marked as **~~strikethrough~~** has been added.

More detailed and up-to-date information about status of data type support and internal representation is available here:

https://docs.google.com/spreadsheets/d/1_xQfqakHetvBL1aHkU2ji00IYgv7WbXud4ZJpA2nOXg/edit#gid=0

1. Numeric Types - [~~NUMERIC/DECIMAL~~](https://github.com/YugaByte/yugabyte-db/commit/8924ba98e67b4cc4180885ec170431c91eed14f0), [~~MONEY~~](https://github.com/YugaByte/yugabyte-db/commit/1b013e71bedbde260f854b7eb12c0d964a685a52), SERIAL
2. DateTime Types - [~~DATE, TIME~~](https://github.com/YugaByte/yugabyte-db/commit/8f75a0381c745cd8766993396b2c391865151bb8), [~~INTERVAL~~](https://github.com/YugaByte/yugabyte-db/commit/bd64c967d6dcb3a67ee9676afae6ce4f67e1895c)
3. ENUM type
4. Geometric Types
5. Network Address Types - CIDR, INET, MACADDR, MACADDR8
6. Bit String Types
7. Text Search Types - TSVECTOR, TSQUERY
8. [~~UUID Type~~](807)
9. XML Type
10. Composite Types
11. JSON Types
12. Range Types
13. Domain Types
14. Object Identifier Types
15. pg_lsn Type
16. Pseudo-Types

**Comment by nocaway** [comment]
@frozenspider : Please update this issue as you add support for the datatypes.

**Comment by frozenspider** [comment]
DECIMAL/NUMERIC support has been added in b5464c90

**Comment by frozenspider** [comment]
MONEY support has been added in 1b013e7

**Comment by frozenspider** [comment]
DATE and TIME support added in 8f75a03

**Comment by d-uspenskiy** [comment]
INTERVAL support added in bd64c96

**Comment by nocaway** [comment]
Hi @d-uspenskiy , could you edit the date-time item in the bug description to add & cross `INTERVAL` type from the list the same way @frozenspider did for DATE & TIME datatypes?  Thank you.

**Comment by mbautin** [comment]
@nocaway : please add a Google Spreadsheet to track the data types and post a link here.

**Comment by nocaway** [comment]
Development status on datatypes.
https://docs.google.com/spreadsheets/d/1_xQfqakHetvBL1aHkU2ji00IYgv7WbXud4ZJpA2nOXg/edit#gid=0

**Comment by nocaway** [comment]
This issue has been fixed by https://github.com/YugaByte/yugabyte-db/commit/a322d95ec7531ca05323d3b869e17724f47b82b9

There are still two issues that are related to datatype support.
Issue 1 - Column of certain types cannot be indexed.
https://github.com/YugaByte/yugabyte-db/issues/1065

Issue 2 - DataType 'XML' is not yet working.
https://github.com/YugaByte/yugabyte-db/issues/1043
