### ISSUE TITLE
[docdb] How does compaction job guarantee the atomicity when replacing sst files? 

### ISSUE THREAD

**Issue by yingfeng** [yugabyte/yugabyte-db#7117]
Accoding to the design documents, the WAL within DocDB is disabled and replaced with Raft log. It's OK during raft consensus for disaster recovery. However, the compaction job happened asynchronously, when it's finished, it will replace old sst files with compacted ones. However, if a disaster happened at that time, how could the data consistency be guaranteed without a WAL ?  Cooresponding data could not be read from Raft log since there were GC happened previously.

**Comment by ddorian** [comment]
> Cooresponding data could not be read from Raft log since there were GC happened previously.

WAL is deleted after data is persisted in sst files. Old sst files are deleted ONLY after the new ones are written. In this case, a crash in mid compcation, you will still have the old sst files to read from.

**Comment by yingfeng** [comment]
What about the atomicity of meta data?
Suppose such a scenario:
The new sst files have already been generated. Then corresponding meta should be updated in a transaction: 
1. Mark those new sst files such that they could be accessed.
2. Mark the old sst files such that they would not be accessed.

How such transaction be guaranteed without WAL if a reboot just happen at that time?

**Comment by ddorian** [comment]
> How such transaction be guaranteed without WAL if a reboot just happen at that time?

You use the WAL to track compactions life too. Example from rocksdb: https://github.com/facebook/rocksdb/wiki/RocksDB-Basics#metadata-storage

**Comment by nnsgmsone** [comment]
How does batch guarantee atomicity in the case of closing wal? @ddorian

**Comment by nnsgmsone** [comment]
As I understand it, batch writing without wal is very difficult to ensure atomicity。 I'm curious how this is handled?

**Comment by ddorian** [comment]
> As I understand it, batch writing without wal is very difficult to ensure atomicity。 I'm curious how this is handled?

We do have WAL. Do you mean distributed transactions ? We have docs: https://docs.yugabyte.com/latest/architecture/transactions/

**Comment by nnsgmsone** [comment]
Then I misunderstood, I saw the article that you guys turned off wal to increase speed (it seems the article didn't understand the real implementation of yuga).... Because my perception to implement distributed transactions, at least such basic functionality as batch is needed, without wal, batch is very difficult to ensure atomicity.

**Comment by nnsgmsone** [comment]
I'm not talking about distributed transactions, I mean how a batch write guarantees atomicity when closing wal. For example:

1. b : =batch.New()
2. b.Set("a", "b")
3. b.Del("d")
4. b.Set("c", "x")
5. b.Get("e")
6. b.Commit()

**Comment by ddorian** [comment]
> I saw an article about yuga turning off wal, how does the above case ensure that writes are atomic when turning off wal?

Show me the link so I can see the context

**Comment by nnsgmsone** [comment]
https://blog.yugabyte.com/enhancing-rocksdb-for-speed-scale/. @ddorian

**Comment by yingfeng** [comment]
> > As I understand it, batch writing without wal is very difficult to ensure atomicity。 I'm curious how this is handled?
> 
> We do have WAL. Do you mean distributed transactions ? We have docs: https://docs.yugabyte.com/latest/architecture/transactions/

Do you mean WAL is acturally raft log instead?  After raft applying, the data has been written to DocDB, however, it does not mean that the data has been successfully written to disk. So what are the differences between Yuga raft log with other raft implementation such that the former one could also serve as WAL ?

**Comment by ddorian** [comment]
> Do you mean WAL is acturally raft log instead?

Yes.

> After raft applying, the data has been written to DocDB, however, it does not mean that the data has been successfully written to disk.

But the Raft log has been written to disk (functions like WAL).

> After raft applying, the data has been written to DocDB, however, it does not mean that the data has been successfully written to disk. So what are the differences between Yuga raft log with other raft implementation such that the former one could also serve as WAL ?

Depends on which exact scenario you compare it too. Some other open source databases were keeping Rocksdb WAL + Raft log, so duplicating work.

**Comment by yingfeng** [comment]
Thank you, I think I need to dive into the details to find out the mechanism, if there's no extra documents for further understanding.
