### ISSUE TITLE
PITR: Docs on how to use PITR, history retention, snapshot intervals

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7122]
After we have #7121, we should play around with it and prepare some BETA docs.

**Comment by nspiegelberg** [comment]
> yb-admin restore_snapshot <snapshot_id> [<timestamp> | minus <INTERVAL>]
> 
> - The timestamp argument is optional.  It allows a point-in-time restoration of the snapshot.  It supports the following formats:
> 
> 1. 16-digit INT.  HybridTime Physical Value.  Microseconds since the Unix Epoch.
> 2. STRING. Timestamp.  https://docs.yugabyte.com/latest/api/ycql/type_datetime/#timestamp
> 3. minus INTERVAL.  Relative time before Now.  Minus indicates that this must be negative.
>         INTERVAL format:
>         // 1. ISO 8601: '3d 4h 5m 6s'
>         // 2. Abbreviated Postgres: '3 d 4 hrs 5 mins 6 secs'
>         // 3. Traditional Postgres: '3 days 4 hours 5 minutes 6 seconds'
>         // 4. SQL Standard: 'D H:M:S'
>

**Comment by polarweasel** [comment]
Slack thread with some starting-point docs: https://yugabyte.slack.com/archives/CDQB8MEAU/p1614805204067600

**Comment by polarweasel** [comment]
**Limitations**

Currently, only _data_ gets rolled back. A point-in-time-restore _does not_ roll back transactions of the following types:

* CREATE
* ALTER
* TRUNCATE
* DROP

**Comment by bmatican** [comment]
FYI master task for tracking the PITR work: https://github.com/yugabyte/yugabyte-db/issues/7120
