### ISSUE TITLE
[YSQL] Wrong Error Message for CREATE TABLE of Serial Types

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#713]
Current reporting.
postgres=# CREATE TABLE intro_tab_smallserial(intro_col_8 smallserial);
ERROR:  could not open file "base/18373/0": No such file or directory

If not supported, the message should have been similar to the following error reporting.
postgres=# CREATE TABLE intro_tab_decimal(intro_col_7 numeric);
ERROR:  Type not yet supported in YugaByte: 1700 (NUMERIC)

**Comment by hectorgcr** [comment]
We now support these types. Done as part of issue #665 with commit c7310c1f23755552252f7ccf6307c148cc903aa0
