### ISSUE TITLE
Adding PostgreSQL Range Types [tstzrange, tsrange] to Documentation

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#7139]
Had a customer ask questions regarding Yugabyte support for PostgreSQL range types like 'tstzrange' since it was not called out in any documentation, but seemed to work with some quick tests. This is a request to add it to that range type to the docs. 

'tstzrange' and 'tsrange' are the only two regarding timestamp but there are a few others as well - https://www.postgresql.org/docs/9.3/rangetypes.html 

Assuming the doc changes would be made here - https://docs.yugabyte.com/latest/api/ysql/datatypes/

**Comment by polarweasel** [comment]
Thanks @mrajcevic01! Is there a reason you linked to the PG 9.3 docs, rather than 11, for this one? (https://www.postgresql.org/docs/11/rangetypes.html)

**Comment by polarweasel** [comment]
(And can you confirm we support all the types listed on [this page](https://www.postgresql.org/docs/11/rangetypes.html)?

**Comment by mrajcevic01** [comment]
Link to 9.3 was by accident...did not notice it was for an earlier version. Only confirmed support for tstzrange and tsrange via Mihnea so not sure on the rest. Customer also confirmed that he was able to work with tstzrange but wanted to make sure it would run well since it was not called out on docs. Main limitation for these types is that we do not allow them as part of the key.

**Comment by lizayugabyte** [comment]
@mrajcevic01 @rkarthik007  Just to make sure I understand correctly, we'll be claiming support for the following subtypes:
- int4range
- int8range
- numrange
- tsrange
- tstzrange
- daterange
