### ISSUE TITLE
[YW][K8S]Allow platform to specify min TLS version for its own frontend

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7140]
See #6893 for more details. This issue is tracking the helm charts changes for K8S.

**Comment by jvigil-yugabyte** [comment]
Done: https://github.com/yugabyte/charts/commit/0399e781b79dfadd19cd675a0455865a65091e95

**Comment by jvigil-yugabyte** [comment]
2.4 backport: https://github.com/yugabyte/charts/commit/650f57c8849022a1a928e9384632eb7062331015
2.2 backport: https://github.com/yugabyte/charts/commit/00e9c10f1c4b4ee367c6c2688cd778b108522881
