### ISSUE TITLE
Update Automatic Tablet Splitting section

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7144]
Make Automatic Tablet Splitting as BETA tag 
https://docs.yugabyte.com/latest/architecture/docdb-sharding/tablet-splitting/#automatic-tablet-splitting

Change the sub-title  "Current tablet splitting limitations" to "Current Limitations" and put the section in Note Box (blue)

Remove #2 "If tablet splitting occurs during an ongoing distributed transaction, it could be aborted and need to be retried."
Remove #3 : "Since splitting of tablets that are not completely compacted is not yet implemented, tablets created by tablet splitting might be split after they reach the specified size threshold."

**Comment by polarweasel** [comment]
@ameyb this section exists in latest, stable, and v2.2 docs. Should we update in all three, or only latest+stable?

**Comment by ameyb** [comment]
Yes this change should be in all the versions, once we GA the entire feature we can update only latest + stable.
