### ISSUE TITLE
[docdb] FATAL in MVCC

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#7145]
This tserver FATAL was seen a few times on clusters with high number of tablets per node. In this particular case, the tserver had 7800 tablets on this node

F20210205 10:14:02 ../../src/yb/tablet/mvcc.cc:398] T b35ce5a050a94c2184b6fa6df054ca06 P 02d50cd668004207af3edaa16e3d0b47: T b35ce5a050a94c2184b6fa6df054ca06 P 02d50cd668004207af3edaa16e3d0b47: Recent 32 MVCC operations:
1. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520025093373 } }
2. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520025496540 } }
3. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520025918673 } }
4. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520026411808 } }
5. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520026902359 } }
6. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520027386433 } }
7. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520027778560 } }
8. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520028305622 } }
9. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520028801629 } }
10. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520029365810 } }
11. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520029972961 } }
12. AddPending { provided_ht: { physical: 1612520030244754 } final_ht: { physical: 1612520030244754 } }
13. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520030244753 logical: 4095 } }
14. Replicated { ht: { physical: 1612520030244754 } }
15. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520030246400 } }
16. AddPending { provided_ht: { physical: 1612520030250672 } final_ht: { physical: 1612520030250672 } }
17. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520030250671 logical: 4095 } }
18. Replicated { ht: { physical: 1612520030250672 } }
19. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520030252150 } }
20. LastReplicatedHybridTime { last_replicated: { physical: 1612520030250672 } }
21. AddPending { provided_ht: { physical: 1612520030601303 } final_ht: { physical: 1612520030601303 } }
22. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520030601302 logical: 4095 } }
23. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520030601302 logical: 4095 } }
24. Replicated { ht: { physical: 1612520030601303 } }
25. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520038067934 } }
26. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1612520038067934 } source: kPropagated } }
27. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1612520038067934 } source: kPropagated } }
28. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1612520038067934 } source: kPropagated } }
29. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1612520038067934 } source: kPropagated } }
30. SetPropagatedSafeTimeOnFollower { ht: { physical: 1612520040358665 } }
31. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1612520040358665 } source: kPropagated } }
32. LastReplicatedHybridTime { last_replicated: { physical: 1612520030601303 } }
New operation's hybrid time too low: { physical: 1612520030608271 }
  max_safe_time_returned_with_lease_={ safe_time: <min> source: kUnknown }
  *ht < max_safe_time_returned_with_lease_.safe_time=0
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_with_lease_.safe_time.ToUint64())=6604882045371478016
  ht->PhysicalDiff(max_safe_time_returned_with_lease_.safe_time)=1612520030608271

  max_safe_time_returned_without_lease_={ safe_time: <min> source: kUnknown }
  *ht < max_safe_time_returned_without_lease_.safe_time=0
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_without_lease_.safe_time.ToUint64())=6604882045371478016
  ht->PhysicalDiff(max_safe_time_returned_without_lease_.safe_time)=1612520030608271

  max_safe_time_returned_for_follower_={ safe_time: { physical: 1612520040358665 } source: kPropagated }
  *ht < max_safe_time_returned_for_follower_.safe_time=1
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_for_follower_.safe_time.ToUint64())=-39937613824
  ht->PhysicalDiff(max_safe_time_returned_for_follower_.safe_time)=-9750394

  (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown})={ safe_time: { physical: 1612520030601303 } source: kUnknown }
  *ht < (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time=0
  static_cast<int64_t>(ht->ToUint64() - (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time.ToUint64())=28540928
  ht->PhysicalDiff((SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time)=6968

  (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown})={ safe_time: <min> source: kUnknown }
  *ht < (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time=0
  static_cast<int64_t>(ht->ToUint64() - (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time.ToUint64())=6604882045371478016
  ht->PhysicalDiff((SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time)=1612520030608271

  is_follower_side=1
  queue_.size()=0
  queue_=[]
  aborted=[]
    @     0x7f6e585160ac  yb::LogFatalHandlerSink::send()
    @     0x7f6e576eecae  google::LogMessage::SendToLog()
    @     0x7f6e576ebe3a  google::LogMessage::Flush()
    @     0x7f6e576ef529  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6e611fa8ae  yb::tablet::MvccManager::AddPending()
    @     0x7f6e6119b90b  yb::tablet::TabletPeer::StartReplicaOperation()
    @     0x7f6e60de4351  yb::consensus::RaftConsensus::StartReplicaOperationUnlocked()
    @     0x7f6e60de8e04  yb::consensus::RaftConsensus::EnqueuePreparesUnlocked()
    @     0x7f6e60df6d66  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x7f6e60df7ed4  yb::consensus::RaftConsensus::Update()
    @     0x7f6e61aa6a77  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x7f6e5e06221a  yb::consensus::ConsensusServiceIf::Handle()
    @     0x7f6e59d7b289  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f6e59d20084  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f6e59d8d158  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f6e585adb2f  yb::Thread::SuperviseThread()
    @     0x7f6e52db8694  start_thread
    @     0x7f6e524f541d  __clone
    @              (nil)  (unknown)

**Comment by mbautin** [comment]
Another potentially related occurrence in a 2.4.0.0 cluster:
```
Application fingerprint: version 2.4.0.0 build 60 revision 4a56a6497b3bbc559f995d30f20f3859debce629 build_type RELEASE built at 21 Jan 2021 02:12:34 UTC
Running duration (h:mm:ss): 0:00:14
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0506 23:46:06.158563  6407 mvcc.cc:398] T 5ed7c9ea73a54114aaa491f65906f52a P 48f807b0dd9946a68cab8406cc2ca87a: T 5ed7c9ea73a54114aaa491f65906f52a P 48f807b0dd9946a68cab8406cc2ca87a: Recent 32 MVCC operations:
1. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
2. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
3. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
4. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
5. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
6. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
7. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
8. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
9. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
10. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
11. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
12. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
13. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
14. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
15. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
16. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
17. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
18. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
19. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
20. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
21. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
22. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
23. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
24. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
25. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
26. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
27. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
28. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
29. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
30. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
31. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
32. LastReplicatedHybridTime { last_replicated: { physical: 1620344756799226 logical: 9 } }
New operation's hybrid time too low: { physical: 1620344756799226 logical: 10 }
  max_safe_time_returned_with_lease_={ safe_time: <min> source: kUnknown }
  *ht < max_safe_time_returned_with_lease_.safe_time=0
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_with_lease_.safe_time.ToUint64())=6636932123849629706
  ht->PhysicalDiff(max_safe_time_returned_with_lease_.safe_time)=1620344756799226
  
  max_safe_time_returned_without_lease_={ safe_time: <min> source: kUnknown }
  *ht < max_safe_time_returned_without_lease_.safe_time=0
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_without_lease_.safe_time.ToUint64())=6636932123849629706
  ht->PhysicalDiff(max_safe_time_returned_without_lease_.safe_time)=1620344756799226
  
  max_safe_time_returned_for_follower_={ safe_time: { physical: 1620344764948928 logical: 4095 } source: kPropagated }
  *ht < max_safe_time_returned_for_follower_.safe_time=1
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_for_follower_.safe_time.ToUint64())=-33381183477
  ht->PhysicalDiff(max_safe_time_returned_for_follower_.safe_time)=-8149702
  
  (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown})={ safe_time: { physical: 1620344756799226 logical: 9 } source: kUnknown }
  *ht < (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time=0
  static_cast<int64_t>(ht->ToUint64() - (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time.ToUint64())=1
  ht->PhysicalDiff((SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time)=0
  
  (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown})={ safe_time: <min> source: kUnknown }
  *ht < (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time=0
  static_cast<int64_t>(ht->ToUint64() - (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time.ToUint64())=6636932123849629706
  ht->PhysicalDiff((SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time)=1620344756799226
  
  is_follower_side=1
  queue_.size()=0
  queue_=[]
  aborted=[]
```
