### ISSUE TITLE
ysql: disallow tampering with postgres role

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#7151]
`ALTER ROLE postgres` can do several things that cause backfill to stop working.  I found two:

- `ALTER ROLE postgres CONNECTION LIMIT 0`
- `ALTER ROLE postgres RENAME TO grespost`

Any changes to privileges doesn't seem to break backfill since backfill is protected by authentication method, not by user privileges.  For example, these are fine:

- `ALTER ROLE postgres NOSUPERUSER` and
  - `REVOKE ALL ON somedb FROM postgres`
  - `REVOKE ALL ON someschema FROM postgres`
  - `REVOKE ALL ON sometable FROM postgres`

Unless there is a better way for index backfill's tserver-to-postgres communication to take place, the two breaking commands should be disallowed for the `postgres` role.

**Comment by tedyu** [comment]
With this change:
```
diff --git a/src/postgres/src/backend/commands/user.c b/src/postgres/src/backend/commands/user.c
index e258c576e..d0932fb25 100644
--- a/src/postgres/src/backend/commands/user.c
+++ b/src/postgres/src/backend/commands/user.c
@@ -605,6 +605,14 @@ AlterRole(AlterRoleStmt *stmt)
         }
         else if (strcmp(defel->defname, "connectionlimit") == 0)
         {
+            if (strcmp(stmt->role->rolename, "postgres") == 0) {
+                int limit = intVal(defel->arg);
+                if (limit == 0) {
+                    ereport(ERROR,
+                        (errcode(ERRCODE_SYNTAX_ERROR),
+                         errmsg("cannot set connection limit for postgres to 0")));
+                }
+            }
             if (dconnlimit)
                 ereport(ERROR,
                         (errcode(ERRCODE_SYNTAX_ERROR),
```
```
yugabyte=# ALTER ROLE postgres CONNECTION LIMIT 0
;
ERROR:  cannot set connection limit for postgres to 0
```

**Comment by jaki** [comment]
@tedyu, thanks for finding it.  However, it should just disallow any connection limit besides default `-1` because even `1` is bad.  For example, a default, 2-shard table will attempt two connections.

**Comment by tedyu** [comment]
Updated the snippet based on feedback.
