### ISSUE TITLE
[YSQL] Raise exceptions for unsupported options in CREATE DATABASE statement

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#716]
Some options in CREATE DATABASE are not yet supported. Subsequently, ALTER these options are also not supported. However, appropriate errors are not being raised.

```
CREATE DATABASE name
    [ [ WITH ] [ OWNER [=] user_name ]
           [ TEMPLATE [=] template ]
           [ ENCODING [=] encoding ]
           [ LC_COLLATE [=] lc_collate ]
           [ LC_CTYPE [=] lc_ctype ]
           [ TABLESPACE [=] tablespace ]
           [ CONNECTION LIMIT [=] connlimit ] ]
```

**Comment by m-iancu** [comment]
We should initially check which options (if any) are currently supported and throw a clean error or warning in the other cases. 
Note: See related issue #900.

**Comment by mbautin** [comment]
PostgreSQL page describing CREATE DATABASE options: https://www.postgresql.org/docs/11/sql-createdatabase.html

**Comment by mbautin** [comment]
List of these options and what they do:

> __name__
> The name of a database to create.

> __user_name__
> The role name of the user who will own the new database, or DEFAULT to use the default (namely, the user executing the command). To create a database owned by another role, you must be a direct or indirect member of that role, or be a superuser.

This requires permissions support (https://github.com/YugaByte/yugabyte-db/issues/869)

> __template__
> The name of the template from which to create the new database, or DEFAULT to use the default template (template1).

> __encoding__
> Character set encoding to use in the new database. Specify a string constant (e.g., 'SQL_ASCII'), or an integer encoding number, or DEFAULT to use the default encoding (namely, the encoding of the template database). The character sets supported by the PostgreSQL server are described in Section 23.3.1. See below for additional restrictions.

> __lc_collate__
> Collation order (LC_COLLATE) to use in the new database. This affects the sort order applied to strings, e.g. in queries with ORDER BY, as well as the order used in indexes on text columns. The default is to use the collation order of the template database. See below for additional restrictions.

> __lc_ctype__
> Character classification (LC_CTYPE) to use in the new database. This affects the categorization of characters, e.g. lower, upper and digit. The default is to use the character classification of the template database. See below for additional restrictions.

> __tablespace_name__
> The name of the tablespace that will be associated with the new database, or DEFAULT to use the template database's tablespace. This tablespace will be the default tablespace used for objects created in this database. See CREATE TABLESPACE for more information.

> __allowconn__
> If false then no one can connect to this database. The default is true, allowing connections (except as restricted by other mechanisms, such as GRANT/REVOKE CONNECT).

> __connlimit__
How many concurrent connections can be made to this database. -1 (the default) means no limit.

> __istemplate__
> If true, then this database can be cloned by any user with CREATEDB privileges; if false (the default), then only superusers or the owner of the database can clone it.

**Comment by mbautin** [comment]
From @m-iancu:

> Not sure if this was already settled but, to followup on the previous discussion, here is my general idea of how `CREATE DATABASE` options could be handled:
> - `OWNER`: Supported.
> - `TEMPLATE`: Supported only if source is `template1` or `template0`.
> - `ENCODING`: Only `DEFAULT` option supported.
> - `LC_COLLATE`: Not supported.
> - `LC_CTYPE`: Not supported.
> - `TABLESPACE`: Only `DEFAULT` option supported.
> - `ALLOW_CONNECTIONS`: Supported.
> - `CONNECTION LIMIT`: Supported.
> - `IS_TEMPLATE`: Support default option (`false`) only.
> I marked some stuff supported because I expect we would get them for (almost) free from Postgres, but I haven't looked too much into the code, so I may be wrong on some accounts.
> Note: Some of the unsupported stuff can be warning-only, but my intuition is that having a global flag for switching parser error checking off (to return warnings only) is a better option. (edited)
