### ISSUE TITLE
[Platform UI] Not able to change the default volume size during universe creation

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-db#7161]
### How to reproduce
- Create a Kubernetes provider
- Create a new universe with it, try to change the volume size to 200 instead of default value (100).
- Click somewhere else.
- It changes back to 100.

![animation](https://user-images.githubusercontent.com/5154532/107229138-71d3ef80-6a43-11eb-8837-3f9ef86956e1.gif)

### Expected behavior
- It should allow one to change the value during creation. 

Environment: OpenShift, build from https://github.com/yugabyte/yugabyte-db/commit/ab0adaad658dc68a837aa8e6d8322d084e056914

cc @iSignal

**Comment by bhavin192** [comment]
@sshev just FYI, if you are not already aware. I tried building from the commit: https://github.com/yugabyte/yugabyte-db/tree/eb0a733d039fae9cb517f7fe604e1d8108135035 The issue seems to be still there.

**Comment by bhavin192** [comment]
Working as expected with 2.5.3.0-b26. I think my build has some issue, I will try clean build and update this comment later.

**Comment by sshev** [comment]
@bhavin192 great, thanks for testing it
