### ISSUE TITLE
[Platform]LDAP integration for Yugabyte platform console

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7164]
The current LDAP solution does not scale to large implementations of Yugabyte.  If a system requires hundreds of users to access a Yugabyte database then the process is too manual and error prone.  It would be better to have the ability to centrally administer large amount of users.

**Comment by adilakram87** [comment]
Two specific requests:

    Better editing of ysql_hba.conf
    maybe some better ldap management to scale for users. API to edit hba.conf?

Can open separate github request if needed.

**Comment by adilakram87** [comment]
Created a separate issue for management of hba.conf under https://github.com/yugabyte/yugabyte-db/issues/7167

This issue is only for request to have UI functionality.

**Comment by tylarb** [comment]
I'll add to this request - in addition to UI management, an API to do the same work would be great.

**Comment by adil246** [comment]
@nbhatia-yb Can this request be closed since this is available in the 2.12 platform?
