### ISSUE TITLE
[YSQL] DROP DATABASE Not Supported

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#717]
DROP DATABASE requires a cascading operation that is dropping all objects of that dropped database.
YugaByte is not yet supporting CASCADE operator.

**Comment by mbautin** [comment]
Now that https://github.com/YugaByte/yugabyte-db/issues/969 is done, what is left to do to implement this?
Cc @nocaway @fizaaluthra

**Comment by fizaaluthra** [comment]
For a `DROP DATABASE` command, postgres removes all tablespace subdirectories that belong to the database (see `remove_dbtablespaces()` in `dbcommands.c`). The database objects (tables, indexes etc) aren't explicitly dropped. 
In YB mode we'll probably have to explicitly delete the database objects too.

**Comment by mbautin** [comment]
@fizaaluthra just to double-check, is that the behavior even with CASCADE enabled?

**Comment by fizaaluthra** [comment]
@mbautin yes, even with CASCADE enabled
