### ISSUE TITLE
[Platform UI] No visual feedback for certain universe creation failures

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-db#7172]
When a user creates a new universe, it is possible that the creation fails even before creating a new task. These are the cases where some pre-flight validation fails. These failures are not shown in the Tasks section. Usually the API returns 400 bad request along with an error message. The user has no clue about this failure. https://github.com/yugabyte/yugabyte-db/pull/7159 adds one such validation check. 

https://github.com/yugabyte/yugabyte-db/pull/7078 implements a toaster for such cases. It needs to be used at other places like these.

cc @chirag-yb @yb-andrew

**Comment by chirag-yb** [comment]
@bhavin192 7159 and 7078 are implemented. Is this still an issue?

**Comment by bhavin192** [comment]
@chirag-yb yes, I believe. 7078 implemented the feature required for this change, but it did not make any change to universe creation code, 

https://github.com/jaydeepkumara/yugabyte-db/blob/7071dad306fbaa2cd4b4b604d70658a828cb3870/managed/ui/src/components/universes/UniverseForm/UniverseFormContainer.js#L79-L86

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/8142
