### ISSUE TITLE
Document Expressions and Operators  in Explorer Section

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7176]
Create a page explaining Expressions and Operators in Explore Section

@rkarthik007  / @m-iancu to add starter doc for this section

**Comment by lizayugabyte** [comment]
@rkarthik007  @ameyb Is this ticket for conditional expressions and operators such as CASE, COALESCE, NULLIF, CAST  or 
CTEs ?  (this is already documented in Queries and Joins)

**Comment by lizayugabyte** [comment]
@rkarthik007 @ameyb Is this ticket for conditional expressions and operators such as CASE, COALESCE, NULLIF, CAST, or is it for CTEs ? (which is already documented in Queries and Joins)

**Comment by lizayugabyte** [comment]
It seems that this ticket is not about conditional expressions and operators. 
Instead, it should cover the basics: 
- Arithmetic operators
- Comparison operators
- Logical operators
- Bitwise operators
- Boolean Expressions
- Numeric Expression
- Date Expressions

**Comment by lizayugabyte** [comment]
Possibly, conditional expressions CASE, COALESCE, NULLIF, CAST should also be documented.
