### ISSUE TITLE
Document Stored Procedures in Explorer Section

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7179]
Create a page explaining Stored Procedures in Explore Section

@rkarthik007 / @m-iancu to add starter doc for this section

**Comment by bllewell** [comment]
You might find useful content in these YB blog posts:

[Using Stored Procedures in Distributed SQL Databases](https://blog.yugabyte.com/using-stored-procedures-in-distributed-sql-databases/)

[An Introduction to PostgreSQL Table Functions in YugabyteDB](https://blog.yugabyte.com/an-introduction-to-postgresql-table-functions-in-yugabytedb/)

[Implementing PostgreSQL User-Defined Table Functions in YugabyteDB](https://blog.yugabyte.com/implementing-postgresql-user-defined-table-functions-in-yugabytedb/)

[Four Compelling Use Cases for PostgreSQL Table Functions](https://blog.yugabyte.com/four-compelling-use-cases-for-postgresql-table-functions/)

[Polymorphism in SQL part one – anyelement and anyarray](https://blog.yugabyte.com/polymorphism-in-sql-anyelement-and-anyarray/)

[Polymorphism in SQL part two – variadic functions](https://blog.yugabyte.com/polymorphism-in-sql-variadic-functions/)
