### ISSUE TITLE
[docs] [API] add CREATE INDEX NONCONCURRENTLY grammar

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#7181]
Jira Link: [DB-2075](https://yugabyte.atlassian.net/browse/DB-2075)
Add `CREATE INDEX NONCONCURRENTLY` grammar rule to create index page.

**Comment by ddorian** [comment]
This is already done https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_index/#nonconcurrently
