### ISSUE TITLE
Platform UI - Sample apps ycql and ysql run issues 

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7193]
Issue: This issue occurs when we run sample apps directly from the platform UI.

The current USQL & YCQL apps run as docker containers.

YSQL stops after 1M records
YCQL writes 1M then carries on doing reads afterwards - without ever ending

This is inconsistent and the YSQL behaviour is preferable

There is a side affect of this - both apps write a log file

Read this, write that etc.

If the client leaves the Cassandra app running it will continue to write log entries

In my case after 3 days it filled 100Gb of the root disk, at which point the container failed
Platform then reported that the cluster was unreachable because platform couldn't write output to the underlying disk as it was full

We should also fix the underlying issues in the Platform and Sample app - no log file in platform should be allowed to run away without log rotation such that it brings the platform down

There are only two visible in 'Platform' via the top right hand side drop down 'Action' box
I believe they are:

CassandraKeyValue - this does not stop after 1M records
SqlInserts - this stops after 1M records

**Following changes should be implemented:**
**Existing behaviour** :
The default value for num_reads and num_writes is -1, which runs indefinitely, the docker container never gets exited, it keeps running (in background as docker container daemon), most of time it goes unnoticed.

**Proposed fix** :
Set the limit to num_reads to 1500000 and num_writes to 2000000 to avoid indefinite run(by default) . User can reproduce existing behaviour by setting -1 explicitly, If user would like to run either read indefinitely(by setting --num_reads -1) or write indefinitely(--num_writes -1) or both (by setting --num_reads -1 --num_writes -1).

**Comment by adilakram87** [comment]
@datamgmt Tagging

**Comment by chirag-yb** [comment]
@nmalladi @streddy-yb should this be tracked in ecosystem?

**Comment by streddy-yb** [comment]
hi @gurushant-yb - can you look into this? There are multiple issues reported as part of this.

**Comment by gurushant-yb** [comment]
Hi @adilakram87 ,
Could you please send me the command which you have used for the testing this behaviour?

**Comment by adilakram87** [comment]
@tylarb

**Comment by gurushant-yb** [comment]
> @tylarb

@adilakram87 please send me the “docker run” command which you have used to run the sample application, based upon which you have logged this issue

**Comment by adilakram87** [comment]
@gurushant-yb This is running from the platform UI, not from the OS. 
Adding David @datamgmt

**Comment by tylarb** [comment]
The command is that provided by the platform, under "actions" in the universe. Screenshot for reference:

![image](https://user-images.githubusercontent.com/20615828/110526606-fe75da00-80e3-11eb-9e72-c98f743f56e0.png)

![image](https://user-images.githubusercontent.com/20615828/110526668-10577d00-80e4-11eb-9349-5ff5e8d9ef20.png)

**Comment by tylarb** [comment]
Basically - we should make sure the sample apps which are this easy to access are safe, and don't cause runnaway logging problems, etc.

**Comment by nchandrappa** [comment]
The default behavior of yb-sample-apps when `--num_reads` flag is not specified, makes the read workload run indefinitely. the default value of `--num_reads` flag is `-1`.

There are two options to fix the issue where the user inadvertently gets affected by the default read workload behavior,

1. In platform UI, specify the flags `--num_reads` and `--num_writes` so that sample-apps stops once the workload is completed.

2. Make the `--num_reads` and `--num_writes` as required flags, when the flags aren't explicitly provided thrown an error saying they are required flags.  cc @gurushant-yb

**Comment by gurushant-yb** [comment]
> The default behavior of yb-sample-apps when `--num_reads` flag is not specified, makes the read workload run indefinitely. the default value of `--num_reads` flag is `-1`.
> 
> There are two options to fix the issue where the user inadvertently gets affected by the default read workload behavior,
> 
> 1. In platform UI, specify the flags `--num_reads` and `--num_writes` so that sample-apps stops once the workload is completed.
> 2. Make the `--num_reads` and `--num_writes` as required flags, when the flags aren't explicitly provided thrown an error saying they are required flags.  cc @gurushant-yb

Based upon my discussion with @nchandrappa , @streddy-yb : I do not think this is an issue , let me know your thoughts on this.

**Comment by streddy-yb** [comment]
hi @nchandrappa @gurushant-yb - I think I understand why the default options could be a problem. Few quick questions:
- Also, is `num_reads` and `num_writes` the number of reads/writes -or- the number of readers/writers?
- What happens if `num_writes` is set to -1 after `num_unique_keys` number of rows are inserted? Writers update the existing rows?
- What happens if `num_writes` is set to a positive value (say 100) after `num_unique_keys` number of rows are inserted? Writers update the existing rows?
- What happens when you set to num_reads to a positive value (say 100)?

**Comment by gurushant-yb** [comment]
> hi @nchandrappa @gurushant-yb - I think I understand why the default options could be a problem. Few quick questions:
> 
> * Also, is `num_reads` and `num_writes` the number of reads/writes -or- the number of readers/writers?
> * What happens if `num_writes` is set to -1 after `num_unique_keys` number of rows are inserted? Writers update the existing rows?
> * What happens if `num_writes` is set to a positive value (say 100) after `num_unique_keys` number of rows are inserted? Writers update the existing rows?
> * What happens when you set to num_reads to a positive value (say 100)?

Hi @streddy-yb , please go through my inline comments, @nchandrappa : Please correct me if i misunderstood :
> * Also, is `num_reads` and `num_writes` the number of reads/writes -or- the number of readers/writers?
> * > *  num_reads & num_writes are # no of  operations (read or write), you can set number of reader and writers by setting num_threads_read and num_threads_write params respectively.
> * What happens if `num_writes` is set to -1 after `num_unique_keys` number of rows are inserted? Writers update the existing rows?
> * > *  Yes, writer overwrites existing inserted records.
> * What happens if `num_writes` is set to a positive value (say 100) after `num_unique_keys` number of rows are inserted? Writers update the existing rows?
> * > * Each time, when sample app starts, it makes new entries with uuid into the db table,  If num_unique_keys < num_writes, then it updates the existing records and exits once it completes all write ops.
> * What happens when you set to num_reads to a positive value (say 100)?
> *> * Sample app exits once doing 100 read ops.

**Comment by gurushant-yb** [comment]
As discussed with @streddy-yb , i will be setting default value to read and writes as below:
--num_reads 1.5m
--num_writes 2m
