### ISSUE TITLE
[Platform] Health check fails if DB TLS version is set to 1.2

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7196]
If --ssl_protocols (see #6671) gflag is set to TLS1.2 -or- above, then the platform health checks fail because ycqlsh uses TLS1.0 (see #7071).

**Comment by tylarb** [comment]
A workaround to this is to set `SSL_VERSION=TLSv1_2` in yugabyte users `.bashrc` on all data nodes.
