### ISSUE TITLE
Display round trip time from each server in yb-master UI

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#7199]
Extending the work in https://github.com/yugabyte/yugabyte-db/issues/6772, it'll be helpful to also show in the http://yb-master:7000/tablet-server-clocks view, for each yb-tserver, the RTT time between the yb-tserver and yb-master leader.

This will give a quick indication of how geographically dispersed the nodes in the system are.

**Comment by VishnuK007** [comment]
I would like to contribute to this issue if that's okay.

**Comment by kmuthukk** [comment]
https://github.com/yugabyte/yugabyte-db/pull/7239  for review
