### ISSUE TITLE
Add Cassandra ROLE support

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#72]
See the following for a description of how the end user commands:
http://cassandra.apache.org/doc/latest/cql/security.html#create-role-statement

- First implement a simple command as follows:
```
CREATE ROLE example_role;
```

- Expand to the following minimal set of commands:
    - CREATE
    - DROP
    - LIST

- For completeness, add the following (lower pri):
    - ALTER (Once a role is created, this will be equivalent to an update statement)
    - GRANT / REVOKE

**Comment by hectorgcr** [comment]
ALTER role (https://github.com/YugaByte/yugabyte-db/commit/16960cf537fe05733f4c72685e20dfdf31a46456) is complete
