### ISSUE TITLE
[BUG]  backup fails with UTF-8 exception

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7202]
Jira Link: [DB-1339](https://yugabyte.atlassian.net/browse/DB-1339)
We have hit another issue with backup - there is one DB which causes backup to fail (both universe and namespace) with this error msg:
Failed to execute task java.util.concurrent.FutureTask@6a83b418, hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: 'utf8' codec can't decode byte 0x8e in position 1: invalid start byte"}.
I am able to dump the DB using pg dump from dbeaver

This would appear that they have invalid UTF-8 data in the database and that the PostgreSQL interface handles it but our backup utility that talks to DoCDB does not

Additional comments:

This is likely a Python error from the yb_backup.py script and not something encoded in the Yugabyte database itself.

If I had to hazard a guess - it is the result of a run_program() statement and the result has some kind of encoding issue

So this is occurring during: /home/yugabyte/master/bin/yb-admin --master_addresses 10.52.192.11:7100,10.52.192.12:7100,10.52.192.13:7100 list_snapshots SHOW_DETAILS

The output includes the transaction_ids while the snapshot is in progress and one of the transaction_ids contains the illegal character. The yb_backup script is rightly attempting to decode utf-8 output -- but it appears that somehow either the data is not encoded utf-8 on output from the yb-admin utility.

**Comment by adilakram87** [comment]
@datamgmt Tagging

**Comment by tylarb** [comment]
@iSignal  @daniel-yb  I think this may be a known issue?
