### ISSUE TITLE
[Docs] Overview of compactions in YB

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#7203]
Need to create a doc that goes over how compactions work within YB. I have the start of the doc [here](https://docs.google.com/document/d/1eVxys6U9bH8YfvTSavGP3J6e5PFLRRaZPhtjUkF5nSU/edit#heading=h.ago7hn87mcou)

**Comment by lizayugabyte** [comment]
As per Taylor (via Slack): 

- The doc should be in https://docs.yugabyte.com/latest/architecture/docdb/
- The google doc file is "a rough rough draft that still needs a lot of help from Eng to be ready"

**Comment by polarweasel** [comment]
There's another ticket open that's being worked on. Closing this one.
