### ISSUE TITLE
[Platform] Every time a backup is taken, a prometheus snapshot is taken, and these snapshots aren't removed

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#7204]
This is a bit different than the issue in #6175  - in that issue, the created backup folder isn't cleaned.

In this, the snapshot folder itself is not cleaned. This affects 2.4.0. 

A review of the code looks like this is resolved with an additional "rm" in master. Wondering if this fix might be in 2.4.1

https://github.com/yugabyte/yugabyte-db/blob/2395d18613fb660d8cc0251058254814d162fd59/managed/devops/bin/yb_platform_backup.sh#L181

```
if [[ "$exclude_prometheus" = false ]]; then
    echo "Creating prometheus snapshot..."
    set_prometheus_data_dir "${prometheus_host}" "${data_dir}"
    snapshot_dir=$(curl -X POST "http://${prometheus_host}:9090/api/v1/admin/tsdb/snapshot" |
      python -c "import sys, json; print(json.load(sys.stdin)['data']['name'])")
    mkdir -p "$data_dir/$PROMETHEUS_SNAPSHOT_DIR"
    run_sudo_cmd "cp -aR ${PROMETHEUS_DATA_DIR}/snapshots/${snapshot_dir} \
    ${data_dir}/${PROMETHEUS_SNAPSHOT_DIR}"
    run_sudo_cmd "rm -rf ${PROMETHEUS_DATA_DIR}/snapshots/${snapshot_dir}" <<< in master, added in commit 76799a325b12aa0aa711f5b3a2bb5f4e88e54bc3
  fi
```

Looking at 2.4: 
https://github.com/yugabyte/yugabyte-db/blob/a0a08173ef2ca27935c15b615152add5cd933709/managed/devops/bin/yb_platform_backup.sh#L61

```
  if [[ "$3" = false ]]; then
    echo "Creating prometheus snapshot"
    set_prometheus_data_dir
    snapshot_dir=$(curl -X POST http://localhost:9090/api/v1/admin/tsdb/snapshot |
      python -c "import sys, json; print(json.load(sys.stdin)['data']['name'])")
    mkdir -p "$data_dir/$PROMETHEUS_SNAPSHOT_DIR"
    sudo cp -aR "$PROMETHEUS_DATA_DIR/snapshots/$snapshot_dir" "$data_dir/$PROMETHEUS_SNAPSHOT_DIR"
  fi
```

**Comment by streddy-yb** [comment]
hi @tylarb - @WesleyW confirmed that fix for this issue is already in https://downloads.yugabyte.com/platform-support-packages-2.4.tar.gz

**Comment by streddy-yb** [comment]
Verified the fix by using the latest version of the platform-support-2.4.tar.gz and 2.4.2.0-b38 yugabundle build.
