### ISSUE TITLE
[docs] Documentation references missing AWS AMI

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#7207]
https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws/

The image (AMI) listed in the screen shot in the above page doesn't exist. 

Also, @tylarb suggested we use CentOS 7 instead of Ubuntu so that all VMs are using the same OS.

**Comment by polarweasel** [comment]
Oddly, [Amazon's docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html) show they support 16.04 LTS, but if we want to suggest CentOS everywhere instead, it's sort of a moot point. :)
