### ISSUE TITLE
Unexpected error log though master change config succeeded.

### ISSUE THREAD

**Issue by bbaddepudi** [YugaByte/yugabyte-db#721]
Noticed this output in one of the recent ops:
`$ ~/master/bin/yb-admin -master_addresses <ip1,ip2> change_master_config REMOVE_SERVER <old_ip> 7100 1
I0108 22:30:54.751463 17854 mem_tracker.cc:240] MemTracker: hard memory limit is 25.722462 GB
I0108 22:30:54.751554 17854 mem_tracker.cc:242] MemTracker: soft memory limit is 21.864092 GB
_E0108 22:30:56.275851 17854 client-internal.cc:1166]
Error: Invalid argument (yb/client/client-internal.cc:1167): Unable to change master config: master addresses cannot be empty_`

The master UI shows master quorum updated correctly to remove the `old_ip`. 

The log seems to be due to some kind of first try printing an error instead of a debug/warning, need to change that to not show up by default.

**Comment by viswanathreddy** [comment]
@bbaddepudi can  you please assign this issue to me?

**Comment by kmuthukk** [comment]
Thx @viswanathreddy for offering to look into this.

**Comment by viswanathreddy** [comment]
@bbaddepudi I am trying to reproduce the issue. I have cloned and build the codebase successfully. But i don't see yb-admin file in the yugabyte-db/bin folder. Am i missing something?

**Comment by ndeodhar** [comment]
@viswanathreddy It should be there in build/latest/bin folder.

**Comment by kmuthukk** [comment]
@viswanathreddy --

if you are looking at the source tree for the binary -- https://github.com/YugaByte/yugabyte-db/tree/master/bin, please note that this is an executable that's generated binary when you do a build of the source, and as @ndeodhar mentioned it'll land in build/latest/bin folder.

The starting point / source code for yb-admin is:

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/tools/yb-admin_cli.cc

**Comment by viswanathreddy** [comment]
@bbaddepudi Though UI doesn't show removed server, 'bin/yb-ctl status' command still shows removed server. Does it mean the server is not actually removed? Will have to check the inconsistency between UI results and yb-ctl status command results

**Comment by bmatican** [comment]
Hey @viswanathreddy , I think `yb-ctl status` is based off of directory structure on disk, as it is a local testing tool.

What part of the UI are you checking to confirm the server is correctly removed? Is it just the main master leader UI (say `localhost:7000/`) ? If the server you removed no longer shows up there, then the command did the right thing. You can also further validate by running the `yb-admin list_all_masters`, to see if the removed master shows up there or not.

**Comment by viswanathreddy** [comment]
@bmatican 
![remove_master_config](https://user-images.githubusercontent.com/1619498/64344878-f2035380-d00c-11e9-87ed-4e19d1b6019e.png)

**Comment by bmatican** [comment]
Thanks for your help @viswanathreddy !
