### ISSUE TITLE
[RFE] Platform UI - Ability to select, delete multiple backups on platform UI 

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7215]
Issue - Backup list on platform doesn't allow to select multiple backups and delete all at once. 

With lot of backups listed it's cumbersome to select each individually and delete. It would be nice to select multiple from the list and perform actions. 

See comments:

They want to manually delete backups and to this requires clicking into each one under the 'Action' button on the right hand side and deleting. They need a way to select multiple and delete all in one go

Workaround has been provided via an API to do multiple deletes by David

**Comment by adilakram87** [comment]
@datamgmt

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7824

**Comment by shashwat-yb** [comment]
Validated this feature on 2.6 b-57 by successfully  deleting multiple backups of a universe created with same and different backup providers.

cc @VijiYB
