### ISSUE TITLE
[Platform] Getting error on click of Universe that is in provisioning state

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7221]
In Master branch - While the provisioning of Universe is inprogress clicking on that universe throws error on UI. I think its related to slow query.
<img width="1585" alt="Screen Shot 2021-02-11 at 5 57 02 PM" src="https://user-images.githubusercontent.com/78048211/107723140-58c27d00-6c95-11eb-90ab-7dbae98afda5.png">

TypeError: Cannot read property 'sort' of null
QueryDisplayPanel
src/components/metrics/MetricsPanel/QueryDisplayPanel.js:18
  15 | }); 
  16 | 
  17 | // Get top 5 queries by total_time descending
> 18 | const topQueries = ysqlQueries.sort((a, b) => b.total_time - a.total_time).slice(0, 5);
     | ^  19 | 
  20 | // Iterate through the data and find the highest mean latency and highest max time
  21 | const highestExecTime = maxBy(topQueries, 'total_time')?.total_time;
View compiled
▶ 17 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by yb-andrew** [comment]
Fixed by 25c112ad3906316bd538c2751d0cd8c663710439
