### ISSUE TITLE
[Platform][UI] Show the associated universes for a certificate

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7223]
Currently there is no way for the user to know the list of universes for a certificate. Add a new action called "Show Universes" in the Actions menu and show the list of universes as a modal associated with the certificate. Make the universe names clickable to take the user to the universe page. The modal's title can be "Universe List" and show the list of universes and the current status. Make the list scrollable if the number of universes is more than 10.

If there are no universes found, say that "No universes associated with this certificate".

![image](https://user-images.githubusercontent.com/68868569/107729540-0fc6f480-6ca6-11eb-83ce-5982207d9bb1.png)

cc @chirag-yb

**Comment by chirag-yb** [comment]
@streddy-yb Let me work with Grishma on this issue.

**Comment by gaurav061** [comment]
https://github.com/yugabyte/yugabyte-db/pull/7377
