### ISSUE TITLE
[Platform][UI] Show the list of universes for a KMS config

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7224]
Currently there is no way for a user to see all the associated universes that are using a particular KMS config. 
- Add "Actions" dropdown list menu in the _Encryption at Rest_ page
- Add "Show Universes" as a sub action
- Also move the existing "Delete Configuration" as a sub action

See #7223 for the details on how the list of universes should be displayed.

![image](https://user-images.githubusercontent.com/68868569/107729880-e2c71180-6ca6-11eb-959a-e2dc8e912c6e.png)

**Comment by gaurav061** [comment]
PR:https://github.com/yugabyte/yugabyte-db/pull/7377
