### ISSUE TITLE
[platform] Update ui components to functional components

### ISSUE THREAD

**Issue by mjoshi0923** [yugabyte/yugabyte-db#7226]
Current version of UI implementation uses outdated class components + functional components (hybrid approach) that is not recommended by react community. at one point we will have to upgrade it to functional components.

TODO: 

- Migrate view components to functional component
- Migrate view + higher order components to functional components
- Migrate deprecated life cycle event to correct effects

**Comment by streddy-yb** [comment]
cc @yb-andrew @sshev

**Comment by kkg-yb** [comment]
Closing this as this is not being done as per @mjoshi0923
