### ISSUE TITLE
[YSQL] Get SQL style database dump

### ISSUE THREAD

**Issue by hackintoshrao** [yugabyte/yugabyte-db#724]
Need support for extracting the SQL style DB dump with following options, 

- Only schema

- Schema + Data

**Comment by m-iancu** [comment]
This is now supported in YSQL via `ysql_dump` taking the same options as `pg_dump`.  
See https://docs.yugabyte.com/latest/admin/ysql-dump/ and https://docs.yugabyte.com/latest/admin/ysql-dumpall/.
