### ISSUE TITLE
Update YB Platform installation and prereq docs 

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7253]
We need to update YB Platform docs to reflect the correct supported Docker version and also improve the steps for Platform pre-requisites

The draft is available at 
https://docs.google.com/document/d/1CC5BjwHEek1MqectVxkkhpN0l8urHQFh3tmARk0iMeA/edit?ts=602a11f3#

Current Doc: https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prerequisites/

**Comment by lizayugabyte** [comment]
I'm starting on it.
