### ISSUE TITLE
Kubernetes operator spins up master nodes that can't log anything

### ISSUE THREAD

**Issue by danports** [yugabyte/yugabyte-db#7259]
The issue is caused by a bad symlink (IIRC in `/home/yugabyte/master`):
![image](https://user-images.githubusercontent.com/8728855/108157534-f7dddf00-70b0-11eb-911e-b5efccd0c16d.png)

Here's what I see in `/mnt`:
![image](https://user-images.githubusercontent.com/8728855/108157571-0fb56300-70b1-11eb-8659-9355a6de12c8.png)

**Comment by ddorian** [comment]
@danports can you provide more context here ? Did you do anything customized ?

**Comment by dorian-stream** [comment]
This was fixed in slack. The issue was that the user had created 3K+ tablets on small servers that were being overwhelmed.
