### ISSUE TITLE
[Platform][UI] Not able to select any node for metrics

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7272]
In AWS portal - 2.5.x
Metrics (Left pane Generic one) -> After selecting the universe, unable to select any nodes. Shows "All" always. 

But its working fine when we go to the particular universe.

**Comment by sunilsutarDCE** [comment]
@VijiYB : This issue fixed while fixing this - https://github.com/yugabyte/yugabyte-db/issues/7107

**Comment by chirag-yb** [comment]
@sunilsutarDCE if this is duplicate please close the ticket.

**Comment by sunilsutarDCE** [comment]
This issue fixed . Closing it .
