### ISSUE TITLE
[Docs] Enforce TLS versions

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7277]
Content here - https://docs.google.com/document/d/1oZomXb3kDR-VvrsNUGUi0LczgvPjHxn7yW_f_BW2cq0/edit#

**Comment by lizayugabyte** [comment]
@chirag-yb Instead of the attached image, please provide a new image that shows correct TLS versions.

![application-config](https://user-images.githubusercontent.com/77016159/108533841-7308e600-72a7-11eb-8d2b-f5077c25ff62.png)
