### ISSUE TITLE
[Platform] Slow Queries - Filter by Query text doesnt show the list sometimes

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7278]
On slow queries, once you filter by something say "Count:>3" and click immediately on the search will not show the list unless you click somewhere.

**Comment by Arpit-yb** [comment]
**Validated**
**Steps followed**

1. Created a Universe
2. Ran Sample-apps
3. queries -> Slow queries -> Filter
4. Entered the filter 'Count:>1' and 'Rows:>100'
5. Results are visible instantly on clicking enter 

Checked with universes with tls on and off
