### ISSUE TITLE
[Platform] Slow Queries - Duplicate queries shows the details of the first duplicate query 

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7279]
If there are duplicate queries

Issue# 1-  selecting one query selects all the duplicates
Issue# 2- Shows the details of the first duplicate query even after filtering out to show second duplicate query. 

See the screenshots
1. Shows the duplicate queries - selecting the second query selects the first one as well
2. I included one more filter criteria to filter out the second duplicate query but you can it shows the first duplicate details. Check total time, std dev etc

**Comment by streddy-yb** [comment]
@VijiYB - Can you attach the screenshots again?

**Comment by yb-andrew** [comment]
This is fixed on latest master branch.
