### ISSUE TITLE
Allow region level placement_info setting that allows for any AZ inside the region to be chosen

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#728]
Jira Link: [DB-4714](https://yugabyte.atlassian.net/browse/DB-4714)
As documented in https://docs.yugabyte.com/latest/explore/planet-scale/global-distribution/, YugaByte DB's placement_info has to be fully qualified as shown below
`aws.us-west-2.us-west-2a,aws.us-east-1.us-east-1a,aws.ap-northeast-1.ap-northeast-1a`

When there is more than one AZ in a region, the above placement becomes restrictive since only one AZ can be explicitly specified. A better approach would be to support a region-level placement as shown below so that any AZ inside a given region can be chosen for data placement.
`aws.us-west-2.*,aws.us-east-1.*,aws.ap-northeast-1.*`

If random AZ picking is not advisable, using a round-robin algorithm would also work great.

**Comment by bmatican** [comment]
We now support LB placement annotations like `Cloud.Region` prefix notation to logically mean `Cloud.Region.*`
