### ISSUE TITLE
[Platform] Refactor gsutil installation

### ISSUE THREAD

**Issue by baba230896** [yugabyte/yugabyte-db#7280]
**To-Do:**

1. Add `gsutil.tar.gz` in the third-party dependency image to make the version consistent.
2. Refactor the `gsutil` installation in the YW docker image as per the new `gsutil.tar.gz` in third-party image.

The goal is to avoid pulling in the entire google cloud sdk .tar.gz and include just the gsutil package. @daniel-yb

**Comment by iSignal** [comment]
I verified that the itest testsimpleops-gcp-rf1-gcs is passing on master (2.7.2.0-b20) is passing after this refactoring.
