### ISSUE TITLE
Timeouts connecting to YSQL DB with npgsql

### ISSUE THREAD

**Issue by danports** [yugabyte/yugabyte-db#7286]
Jira Link: [DB-1436](https://yugabyte.atlassian.net/browse/DB-1436)
The npgsql .NET PostgreSQL driver runs a [lengthy query with many joins](https://github.com/npgsql/npgsql/blob/e780f902994e581efc541926038e691b8a3e0a54/src/Npgsql/PostgresDatabaseInfo.cs#L118) on the system tables when it connects to a database to fetch type info. This query has been timing out on my three node YugabyteDB cluster, though it has worked fine on a single node cluster. According to the [npgsql docs](http://www.npgsql.org/doc/connection-string-parameters.html#compatibility), the type query can be bypassed by adding `Server Compatibility Mode=NoTypeLoading` to the connection string, which is a good workaround, though I'm hesitant to leave that workaround in place for long since I don't fully understand the implications at present.

**Comment by ddorian** [comment]
> though I'm hesitant to leave that workaround in place for long since I don't fully understand the implications at present.

Based on this sentence:

> "NoTypeLoading", which will bypass the normal type loading mechanism from the PostgreSQL catalog tables and supports a hardcoded list of basic types .

You should be ok as long as you don't create your own types (like composite types, domains etc).

@danports can you run it and paste the raw generated query here ?
