### ISSUE TITLE
[Platform]New home dir is not being used for platform process when custom home dir is set

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#7294]
We discovered this issue when we tried to destroy a cluster but it failed. We looked on the nodes and /home/yugabyte was full because of core dumps. however the home dir specified on config creation was /opt/yugabyte so we should not be using the /home/yugabyte dir at all. It looks like the platform is using /home/yugabyte to run the ansible script so if the dir is full the scripts cannot run so the platform failed to delete the nodes.

Additional notes

Of the 15 nodes in the cluster only 5 were stopped the other 10 were still running.
All 10 had their /home/yugabyte dirs full.
When we looked at the platform the cluster was gone
But going to <master-ip>:7000 we saw the cluster was still active

**Comment by streddy-yb** [comment]
See #7296 for a related issue

**Comment by streddy-yb** [comment]
Verified the following using 2.4.2.0-b35:
- Create an OnPrem provider with Custom Home Dir (/opt/yugabyte)
- Added 3 nodes to this provider
- Created a new universe
- Verified that everything gets written /opt/yugabyte
- Deleting the universe deletes everything from /opt/yugabyte
