### ISSUE TITLE
[Platform]Core Dump Files Not Going to Correct DIr

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#7296]
A user has been running into some issues with core dump files not getting sent to the correct home dir which was set in the on prem provider. By default the home dir is set as /home/yugabyte but the user changed it to /opt/yugabyte. However all the core files are still going to /home/yugabyte/cores and unfortunately they do not have a lot of space on disk for that dir. I saw Bogdan has created a GH issue for this https://github.com/YugaByte/yugabyte-db/issues/1758. Do we know when this fix will go in? for now i’m going to use the workaround suggested by Eng of setting kernel.core_pattern to/opt/yugabyte/cores/core_%e.%p but ideally it would be great if the platform set this automatically.

**Comment by iSignal** [comment]
Don't think #1758 is relevant to platform. Also, is the ask here to be able to specify a setting in the onprem provider to override the core pattern sysctl that we usually set?

**Comment by tsmull-11** [comment]
yes right that would be the ask, so that we can make sure the core dumps are going to the right spot.

**Comment by streddy-yb** [comment]
Docs have been updated.
