### ISSUE TITLE
Add Cassandra PERMISSION support

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#73]
Basic permissions, the roles they operate on and the corresponding operations they can authorize:

| Permissions  | Resources      | Operations
| ------------- | ------------- | ------------- |
CREATE | ALL KEYSPACES | CREATE KEYSPACE and CREATE TABLE in any keyspace
CREATE | KEYSPACE | CREATE TABLE in specified keyspace
CREATE | ALL ROLES | CREATE ROLE
DROP | ALL KEYSPACES | DROP KEYSPACE and DROP TABLE in any keyspace
DROP | KEYSPACE | DROP TABLE in specified keyspace
DROP | TABLE | DROP TABLE
DROP | ALL ROLES | DROP ROLE on any role
DROP | ROLE | DROP ROLE
SELECT | ALL KEYSPACES | SELECT on any table
SELECT | KEYSPACE | SELECT on any table in specified keyspace
SELECT | TABLE | SELECT on specified table
MODIFY | ALL KEYSPACES | INSERT, UPDATE, DELETE and TRUNCATE on any table
MODIFY | KEYSPACE | INSERT, UPDATE, DELETE and TRUNCATE on any table in specified keyspace
MODIFY | TABLE | INSERT, UPDATE, DELETE and TRUNCATE on specified table

Extended set (lower pri):

| Permissions  | Resources      | Operations
| ------------- | ------------- | ------------- |
ALTER | ALL KEYSPACES | ALTER KEYSPACE and ALTER TABLE in any keyspace
ALTER | KEYSPACE | ALTER KEYSPACE and ALTER TABLE in specified keyspace
ALTER | TABLE | ALTER TABLE
ALTER | ALL ROLES | ALTER ROLE on any role
ALTER | ROLE | ALTER ROLE
AUTHORIZE | ALL KEYSPACES | GRANT PERMISSION and REVOKE PERMISSION on any table
AUTHORIZE | KEYSPACE | GRANT PERMISSION and REVOKE PERMISSION on any table in specified keyspace
AUTHORIZE | TABLE | GRANT PERMISSION and REVOKE PERMISSION on specified table
AUTHORIZE | ALL ROLES | GRANT ROLE and REVOKE ROLE on any role
AUTHORIZE | ROLES | GRANT ROLE and REVOKE ROLE on specified roles
DESCRIBE | ALL ROLES | LIST ROLES on all roles or only roles granted to another, specified role

See the following link for more details:
http://cassandra.apache.org/doc/latest/cql/security.html#cql-permissions

**Comment by bmatican** [comment]
Spun off the last remaining item, so we can close this.
