### ISSUE TITLE
[Platform][UI] - Sometimes page shows only loader after session expires

### ISSUE THREAD

**Issue by sunilsutarDCE** [yugabyte/yugabyte-db#7301]
Observed one issue on portal , when session expires its not redirecting to login page automatically and even after refresh .

Should redirect to login page when we get 403 forbidden from API . When I manually remove cookies from developer tool , it then redirects to login page .

<img width="1534" alt="Screenshot 2021-02-19 at 3 27 18 PM" src="https://user-images.githubusercontent.com/39611171/108490597-ea9b3d00-72c8-11eb-8fc8-0963191c7328.png">

**Comment by yb-andrew** [comment]
Issue is related to https://github.com/yugabyte/yugabyte-db/issues/7653

**Comment by sunilsutarDCE** [comment]
Closing. , as it looks fixed as part of fixing #7653 .
