### ISSUE TITLE
Boundary values installed during a compaction might override values installed into the version set by a concurrent flush

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#731]
VersionSet::LogAndApply releases the RocksDB mutex and there could be a flush that comes in and installs its own boundary values that were not taken into account in CompactionJob::Install when computing new boundary values as a result of the compaction.

**Comment by mbautin** [comment]
Here is the relevant logic from `compaction_job.cc` when processing key/value pairs from the file:
```
    sub_compact->builder->Add(key, value);
    auto boundaries = MakeFileBoundaryValues(db_options_.boundary_extractor.get(),
                                             key,
                                             value);
    if (!boundaries) {
      status = std::move(boundaries.status());
      break;
    }
    auto& boundary_values = *boundaries;
    sub_compact->current_output()->meta.UpdateBoundaries(std::move(boundary_values.key),
                                                         boundary_values);
```

Also in `OpenCompactionOutputFile` we have the following. This is copying boundary values from input files into the output file. We should probably remove this as removes the possibility of shrinking the value range for a particular file if some keys present in input files but overwritten at or before the history cutoff timestamp have been garbage-collected. Cc @spolitov -- we might have discussed this but it would be good if you can confirm.
```
  // Update sequence number boundaries for out.
  for (size_t level_idx = 0; level_idx < compact_->compaction->num_input_levels(); level_idx++) {
    for (FileMetaData *fmd : *compact_->compaction->inputs(level_idx) ) {
      out.meta.UpdateBoundariesExceptKey(fmd->smallest, UpdateBoundariesType::kSmallest);
      out.meta.UpdateBoundariesExceptKey(fmd->largest, UpdateBoundariesType::kLargest);
    }
  }
```

**Comment by mbautin** [comment]
Upon closer examination, it looks like we don't put boundary values into the VersionEdit and don't store them in the manifest, so this is a non-issue. Cc @spolitov -- could you please confirm?

**Comment by spolitov** [comment]
We put boundary values in VersionEdit and manifest, but not directly.
They are stored in metadata related to live files, so compaction does not override it, since it does not change data for remaining files.
