### ISSUE TITLE
Provider Configuration credentials and multiple configurations

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#7310]
Add a Provider Credential page so you can then reference the credentials when configuring a Provider. It needs a "validate" button to make sure it works and has the permissions needed by the Platform.

Add ability to have multiple configurations for a provider to support many use cases. You could have an AWS account for Dev/Test and another for Production. 

The referenced credentials could then be used to populate drop down boxes like VPC, Subnets, AMIs, Keypairs, etc. These parameters should be dependent too. For example, after you pick a VPC, you should only see Subnets that are in the chosen VPC.

There should be checking for the SecurityGroup too. It should make sure it has the correct open ports.

**Comment by streddy-yb** [comment]
Support for multiple configurations is tracked in #7474

**Comment by chirag-yb** [comment]
duplicate issue
