### ISSUE TITLE
Add warning for Ephemeral Storage 

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#7311]
If you stop a VM that uses ephemeral storage, the data is lost. There should be a warning to customers in Platform that they will lose data if they stop the VMs.

**Comment by chirag-yb** [comment]
@RunningJon Please add clear detailed steps to reproduce this issue.

**Comment by RunningJon** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html

"The data in an instance store persists only during the lifetime of its associated instance."

**Comment by RunningJon** [comment]
I created a universe using i3.xlarge nodes in AWS, stopped the VMs, and then started the VMs again. The ephemeral disks are no longer formatted and the data has been lost.

Here is the fstab:
```
cat /etc/fstab

#
# /etc/fstab
# Created by anaconda on Fri Feb 26 17:17:47 2021
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=7fbbcd03-11b0-4ebd-b733-96fbb576dcea	/	xfs	defaults	0 0
#/mnt/d0
/dev/nvme0n1 /mnt/d0 xfs defaults,noatime,nofail,allocsize=4m 0 2
```

And then looking at the directory:

```
ls -l /mnt/d0
total 0

```

Checking the mounts and /mnt/d0 is not listed.

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         15G     0   15G   0% /dev
tmpfs            15G     0   15G   0% /dev/shm
tmpfs            15G   17M   15G   1% /run
tmpfs            15G     0   15G   0% /sys/fs/cgroup
/dev/xvda1       40G  5.3G   35G  14% /
tmpfs           3.0G     0  3.0G   0% /run/user/1000
```

So the disk is not mounted so try to mount it:
```
mount -a
mount: wrong fs type, bad option, bad superblock on /dev/nvme0n1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

The dmesg is:

`[  507.800642] XFS (nvme0n1): Invalid superblock magic number`

This is expected behavior from ephemeral storage in the cloud (AWS, Azure, and GCP). We should warn customers that this will happen if they stop the VMs.

**Comment by streddy-yb** [comment]
Also disable Pause universe functionality for ephemeral storage use case.

**Comment by nishantSharma459** [comment]
@mjoshi0923 While you're working on the ephemeral storage for the Pause universe please remove the **pricing tag** from the Pause universe modal as well.

**Comment by mjoshi0923** [comment]
@VijiYB to test this feature, you will have to go to http://portal.dev.yugabyte.com/features and enable a feature that you want to test. let me know if you need any help to understand how to do it.

**Comment by VijiYB** [comment]
@streddy-yb - Can we stop the node from Nodes Tab for ephemeral storage as addressed in the issue initially? I created universes with i3 instances, still able to stop processes without any warning.  Or this issue is only for providing warning for Pause universe that has ephemeral storage?

**Comment by chirag-yb** [comment]
@mjoshi0923 Have you covered ephemeral instances for Azure and GCP as well?

**Comment by mjoshi0923** [comment]
@chirag-yb No right now it's not possible to do pause universe for GCP and Azure, so there is no need of warning right now. although once it's available from backend UI will be able to enable warning for other two as well. warning code is there in the UI.
