### ISSUE TITLE
Python 2.7 with pip requirement

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#7313]
Deployment executes python scripts as root which uses Python 2.7 in CentOS/Redhat 7. It doesn't use alternatives and I am uncertain if it supports newer versions of Python. It seems to require 2.7 but this needs to confirmed and also documented.

If pip is not installed, which it is not with a minimal install of the OS, the deployment will fail.

Platform should probably automatically install pip if not found. The version of Python required should also be documented.

**Comment by chirag-yb** [comment]
@RunningJon For any documentation improvements would you mind sending a direct PR and assign me as a reviewer?

**Comment by RunningJon** [comment]
It would be nice to include an update to the documentation but I don't think we document everything installed by replicated right now. The installer should handle this automatically just like it does with many other yum installs. 
I don't know what you mean with, "sending a direct PR and assign me as the reviewer". I'm not committing any code.
