### ISSUE TITLE
Java installed required

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#7314]
During a deployment of Platform in AWS using an AMI with the minimal install of the OS, the deployment failed. The resolution was to install java with yum. This needs to be documented and also automated with the other yum installs executed by Platform.

**Comment by chirag-yb** [comment]
@RunningJon For any documentation improvements please send direct documentation PRs and assign me as a reviewer.

**Comment by RunningJon** [comment]
I'm struggling with understanding the ask of me.

**Comment by polarweasel** [comment]
@chirag-yb still relevant, or can we close this ticket?

**Comment by polarweasel** [comment]
@ymahajan is this ticket still relevant, or can we close it?

**Comment by lizayugabyte** [comment]
@nbhatia-yb  is this ticket still relevant, or can we close it?

**Comment by lizayugabyte** [comment]
@nbhatia-yb is this ticket still relevant, or can we close it?

**Comment by lizayugabyte** [comment]
@nbhatia-yb is this ticket still relevant, or can we close it?

**Comment by nbhatia-yb** [comment]
@lizayugabyte closing this ticket. Please file a new JIRA (PLAT-) Yugabyte Anywhere ticket if this is still an issue. Thanks!
