### ISSUE TITLE
[Docs] add instructions for using k8s packages in an airgapped environment in YB Anywhere

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#7317]
@ssung-yugabyte to add details...

**Comment by ssung-yugabyte** [comment]
K8S security is getting more and more attention. Enterprise K8s admins mostly blocks the deployments from the public container registry for security reasons and turn to build internal container registries for example, harbor and nexus.  In such an environment, k8s users will need yugabyte deployment pulling images from a private registry. This doc shows how to pull and push yugabyte k8s artifacts to private container registries like harbor or nexus. 
https://docs.google.com/document/d/1-0sgOJgC88I9WA7FE_l5K-NzJ_XDmSQcp4PnqES1ou0/edit
