### ISSUE TITLE
[Platform] Release instance is not an option for a node should the install fail

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#7318]
This is an enhancement to Node Failure scenario where users should be able to delete(release) the Failed instance from UI.

Scenario: During the scale up of the cluster the new VM had not been properly provisioned for ssh access. 
When the install failed the row was created for the new node but the user is unable to release the instance to redo the install. There needs to be an option should the install fail to release the instance.

This also happened when a node failed to load data and then the node was unable to join. 

In both instances the json had to be edited to add the remove actions.

**Comment by chirag-yb** [comment]
@tsmull-11 which version are you using? We made a few enhancements in 2.4.1 https://github.com/yugabyte/yugabyte-db/issues/5942 so I want to ensure you are using the latest version. Can you confirm 2.4.1 fixes this issue?

**Comment by tsmull-11** [comment]
@chirag-yb this was tested on 2.4.0 so i'll have them upgrade to 2.4.1.

**Comment by SergeyPotachev** [comment]
Waiting for results of testing 2.4.1.

**Comment by streddy-yb** [comment]
Hi @tsmull-11 - This is fixed in 2.4.1.0.
