### ISSUE TITLE
YSQL: Enable concurrent transactions on ALTER TABLE DROP COLUMN & ADD COLUMN DDL Statement

### ISSUE THREAD

**Issue by emhna** [yugabyte/yugabyte-db#7327]
This issue is very similar to #7325.

When DDL transaction such as ALTER is performed at the same time as transaction block, the transaction will run into system catalog version mismatch.
To ensure this error message only appears when the transaction is operating on the same table, changes are made at Postgres and DocDB layer to abort only the transactions running on the tablet that's being altered.

This change will be applied on ALTER TABLE's DROP COLUMN and ADD COLUMN commands only.

**Comment by m-iancu** [comment]
Closed by c3bfef94eb2ed59836771ab419f3d5403fa888f5.
