### ISSUE TITLE
[Docs] Review "Yugabyte Platform on OpenShift" document

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#7341]
https://docs.google.com/document/d/1r8V1PkZGNOcnJMsx-vz0jQvRPpVTx8AulMn7Pa1LpoM/edit?ts=602fce22#heading=h.8ck9632g2jwi

**Comment by lizayugabyte** [comment]
Asked by Chirag

**Comment by rtsisyk** [comment]
I have OpenShift 4.x cluster and I can go through the document and check the technical side of things.

**Comment by lizayugabyte** [comment]
@rtsisyk Sure, thanks. Let me do a first run, and then feel free to take over.

**Comment by lizayugabyte** [comment]
@rtsisyk I'm done with the doc

**Comment by chirag-yb** [comment]
@lizayugabyte do you have a preview site for this change?

**Comment by lizayugabyte** [comment]
@chirag-yb No. I thought you asked to review the Google doc, which I did.

**Comment by rtsisyk** [comment]
The instructions are good and comprehensive. I have some questions regarding the product's UX, but this is a different story.

**Comment by ameyb** [comment]
This content should go under a new CLoud Provider - Redhat OpenShift

**Comment by lizayugabyte** [comment]
@chirag-yb @ameyb There are some unresolved technical comments in the google doc. Before I start converting the file to markdown, it would be great if these comments were addressed by someone with tech expertise in this area.

**Comment by chirag-yb** [comment]
@bhavin192 @iSignal Could you guys review the doc for unsolved comments?

**Comment by lizayugabyte** [comment]
Closing this ticket because the doc was published on the website a long time ago
