### ISSUE TITLE
[Platform] Support for multiple backup configs

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7349]
The following bugs are:

1. Currently platform does not support multiple backup configs for any of the backup config types (viz S3, NFS, GCS, Azure). Ability to provide different backup configs for different universes is important.

2. https://github.com/yugabyte/yugabyte-db/issues/4547

3. When a user is entering the backup location path for its respective provider then that will appear in the other cloud providers as well before submitting.

4. If you enable the IAM role and then change the tab for eg. NFS and if you come back then IAM is enabled along with the 'Access and the Secret Key' fields.

**Comment by chirag-yb** [comment]
Related ticket - https://github.com/yugabyte/yugabyte-db/issues/7103

**Comment by streddy-yb** [comment]
Required changes:
- Add a new attributed called "Name" to uniquely identify the configs
- Display the list of configs for each type as a table
- As part of selecting the backup config when taking a backup, allow the user to select the backup config based on the names; show the associated bucket name (or NFS path) as part of the selection.

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7668
