### ISSUE TITLE
[YSQL] Support adding primary key to a table with tablespace

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#7359]
Currently altering a table to add primary key fails with the following error, if the table is associated with a tablespace:

```
CREATE TABLE test(id int) TABLESPACE tblspace
ALTER TABLE testschema.test_tab ADD CONSTRAINT test_tab_pkey PRIMARY KEY (id);
ERROR:  adding primary key to a table with a tablespace is not yet implemented;
```
When a primary key is added to a table, this causes a whole table re-write as described in #1104 
Today this step errors out if the table has custom tablespace set, because at the time this was implemented, tablespaces were not enabled yet.
Now that tablespaces are enabled this no longer needs to error out. The new table that is created as part of the table rewrite should be associated with the same tablespace as that of the original table to which we are adding the primary key.

**Comment by m-iancu** [comment]
Fixed by ae0ede2.
