### ISSUE TITLE
[Platform] Health check reports healthy and ycql/ysql OK for stopped nodes

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#7360]
1. Create a 3 node VM universe
2. Stop one of the nodes
3. Wait for health checks (make sure the alerting email in the customer profile is filled out).

Observed:
The stopped node is specifically reported as healthy and as passing ycql/ysql checks (though the corresponding tserver is down).
Expected:
This node should not be included in the healthy node report or, at the least, not marked as OK for ycql/ysql client checks.

<img width="1806" alt="Screenshot 2021-02-23 231725" src="https://user-images.githubusercontent.com/8207010/108962581-d55a4180-762d-11eb-92f6-1144b2558b93.png">
<img width="1816" alt="Screenshot 2021-02-23 231658" src="https://user-images.githubusercontent.com/8207010/108962588-d7bc9b80-762d-11eb-8ea3-760359ecdb50.png">

In this case, the health check command we run looks like
```
 'bin/py_wrapper' 'bin/cluster_health.py' '--cluster_payload' '[{"identityFile":"/.... .pem","sshPort":
54422,"namespaceToConfig":{},"masterNodes":{"10.12.16.39":"yb-15-sanketh-test-1-n2","10.12.16.38":"yb-15-sanketh-test-1-n3"},"tserverNodes":{"10.12.16.39":"yb-15-sanketh-test-1-n2","10.12.16.38":"yb-15-sanketh-test-1-n3"},"ybSoftwareVersion":"2.5.2.0-b6","enableTlsClient":false,"sslProtocol":"","enableYSQL":true,"ysqlPort":5433,"ycqlPort":9042,"enableYEDIS":false,"redisPort":6379}]' '--start_time_ms' '1614148755269
```
which doesn't include the stopped node at all, so we don't really check it.

**Comment by rtsisyk** [comment]
Reproduced. Confirmed. 
The `bin/cluster_health.py` call doesn't include stopped nodes.

**Comment by iSignal** [comment]
My bad, it seems like we don't include stopped nodes in the health check, so this issue is not correct. I probably didn't wait long enough or didn't refresh properly. Sorry for the confusion.
