### ISSUE TITLE
docdb: Support Leader Affinity With Master Sys Catalog Tablet

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#7369]
Currently, the cluster config data placement options applies only to user tablets. However, we still want something like leader affinity to apply both to user tablets and the master sys catalog tablet. For a p0 implementation of such a feature, it should suffice to let master leader be elected at start time without constraints. Then have a background thread that checks this leader against the cluster config's affinity specification, and if it doesn't match, send a StepDown request with the new leader in an affinitized zone. In our current code, this op should fail if the new specified leader is down or not caught up, so worst case this will be a no-op and not result in any unavailability.

**Comment by bmatican** [comment]
Closing back, filed #7963 specifically for the disable
