### ISSUE TITLE
[YSQL-Dump] Ensure that ysql-dump creates hash partitions 

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#7381]
Jira Link: [DB-4070](https://yugabyte.atlassian.net/browse/DB-4070)
Any table that is dumped from any version of postgres should be automatically converted to use hash partitions in order to load with Yugabyte.

**Comment by tedyu** [comment]
@tylarb 
Can you add some details to this request ?

Thanks

**Comment by ssung-yugabyte** [comment]
The following schema is generated by "ysql_dump -h postgresql11-instance".  From this schema, you can see that primary key has "id asc". It will be great to change this to PRIMARY KEY(id HASH) as default. 

-- Name: remote_schemas; Type: TABLE; Schema: hdb_catalog; Owner: postgres
--

CREATE TABLE hdb_catalog.remote_schemas (
    id bigint NOT NULL,
    name text,
    definition json,
    comment text,
    PRIMARY KEY(id ASC)
);

**Comment by m-iancu** [comment]
Closing this as obsolete. We now support both ASC/DESC (range partitioning) in Yugabyte, and also tablet-splitting so we can handle scale for such tables.
@tylarb please reopen if there's any concerns with that in general or open new issues for any specific limitations.
