### ISSUE TITLE
[Platform] Missing package for s3cmd dependency for airgapped GCP VMs

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#7385]
Looks like installing s3cmd is failing to be installed on an airgapped GCP vm using the onprem flow due to setuptools_scm not being found. This needs to be added to thirdparty deps and installed explicitly alongside the other dependencies.

Since we do a "best try" approach to installing these backup utils for onprem providers that are airgapped, this won't fail the universe creation but is resulting in a huge increase in the amount of time creating new universes on 2.4+

**Comment by daniel-yb** [comment]
Also looks to be an issue for AWS airgapped

**Comment by jvigil-yugabyte** [comment]
Manual workaround (for now):
1. Install `setuptools_scm-1.17.0.tar.gz` (from https://pypi.org/simple/setuptools-scm/) on each universe node. Will have to manually copy this package to each node.
    ```bash
    tar -xvf setuptools_scm-1.17.0.tar.gz
    cd setuptools_scm-1.17.0
    python setup.py build
    sudo python setup.py install
    ```
2. Create universe. It should no longer "hang" while failing to download the `setuptools_scm` dependency.

**Comment by jvigil-yugabyte** [comment]
@daniel-yb can confirm that this is an issue w/ onprem+airgap provider (running on AWS) using the centos7 marketplace AMI (https://aws.amazon.com/marketplace/pp/B00O7WM7QW?ref=cns_srchrow).

**Comment by daniel-yb** [comment]
> @daniel-yb can confirm that this is an issue w/ onprem+airgap provider (running on AWS) using the centos7 marketplace AMI (https://aws.amazon.com/marketplace/pp/B00O7WM7QW?ref=cns_srchrow).

Yeah it is.
