### ISSUE TITLE
[platform] onprem-provider pre-flight check failing for non-passwordless ssh user

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7390]
How to reproduce:
- on an onprem-node, create a new user (ex:foo), make it "password required" sudo user; set up the authorized_keys etc for this user
- create an onprem provider, add foo as the ssh user, opt for "manually provision node"
- when you run the manual provisioning script with "-ask_password" option, you don't get prompted for password and the prechecks fail
```
/opt/yugabyte/yugaware/data/provision/6d1f31bd-e6c4-4759-a7dc-87e7ea39e3db/provision_instance.py --ip 10.9.77.182 --mount_points /storage --ask_password
Executing provision now for instance with IP 10.9.77.182...
Failed preflight checks!
{
  "(Mount Point) /storage is writable": false, 
  "(Prometheus) No Pre-existing Node Exporter Running": true, 
  "Internet Connection": true, 
  "SSH Connection": true, 
  "(Prometheus) /var/run/prometheus is writable": false, 
  "(Prometheus) /etc/prometheus is writable": false, 
  "Sudo Access to Python": false, 
  "(Prometheus) /lib/systemd/system/node_exporter.service is writable": false, 
  "Yugabyte User in Yugabyte Group": true, 
  "(PAM Limits) /etc/security/limits.conf is writable": false, 
  "Try Ansible Command": true, 
  "(Prometheus) /opt/prometheus is writable": false, 
  "(Prometheus) /var/log/prometheus is writable": false, 
  "(Prometheus) /var/lib/prometheus is writable": false
}
```
cc @VijiYB

**Comment by VijiYB** [comment]
tested this on 2.4.2 . 

Followed the steps mentioned - created user vijiyb and made that as "password required"

1.    on an onprem-node, create a new user (ex:foo), make it "password required" sudo user; set up the authorized_keys etc for this user
 2.   create an onprem provider, add foo as the ssh user, opt for "manually provision node"
  3.  when you run the manual provisioning script with "-ask_password" option, you don't get prompted for password and the prechecks fail

**Preflight check with wrong password:**
Sudo password: 
Password saved.
Performing preflight checks for instance with IP 10.9.......
Failed preflight checks!
{
  "(Prometheus) No Pre-existing Node Exporter Running": true, 
  "Internet Connection": true, 
  "SSH Connection": true, 
  "(Prometheus) /var/run/prometheus is writable": false, 
  "(Prometheus) /etc/prometheus is writable": false, 
  "Sudo Access to Python": false, 
  "(Mount Point) /data is writable": false, 
  "(Prometheus) /lib/systemd/system/node_exporter.service is writable": false, 
  "Yugabyte User in Yugabyte Group": true, 
  "(PAM Limits) /etc/security/limits.conf is writable": false, 
  "Try Ansible Command": true, 
  "(Prometheus) /opt/prometheus is writable": false, 
  "(Prometheus) /var/log/prometheus is writable": false, 
  "(Prometheus) /var/lib/prometheus is writable": false
}


**Preflight check with correct password:**
Sudo password: 
Password saved.
Performing preflight checks for instance with IP 10.9.......
Preflight checks passed!
Executing provision now for instance with IP ......
Provisioning successful!

**Comment by streddy-yb** [comment]
Thanks @VijiYB
