### ISSUE TITLE
[YSQL] Prevent drop of database when there is active connection to the DB

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#7400]
@RunningJon reported the following:

Session 1, connect to database foo.
Session 2, connect to yugabyte database and drop database foo.
Session 1, execute any query. The query will hang because session 2 dropped the database you are in.

In PostgreSQL, you can't drop a database when there is a session connected to it.

**Comment by tedyu** [comment]
The above scenario only involved one node (with two sessions).

If two or more nodes are involved, the solution would become complex since the connection needs to be persisted somewhere (possibly a DB table).

**Comment by RunningJon** [comment]
You could use pg_stat_activity which persists the connection information.

**Comment by tedyu** [comment]
Not sure if pg_stat_activity can serve as the source of truth (at least currently).
Session #1 connects to 127.0.0.1 and session #2 connects to 127.0.0.2 .
```
yugabyte=# select pid, query_start, state, client_addr from pg_stat_activity;
  pid   |          query_start          | state  | client_addr
--------+-------------------------------+--------+-------------
 858154 | 2021-02-26 21:16:44.155793+00 | active | 127.0.0.1
 849798 |
```
With both clients active (and both using yugabyte db), I performed the above query several times - there is not much information for session #2.

**Comment by tedyu** [comment]
I looked at src/postgres/src/backend/utils/adt/pgstatfuncs.c and src/postgres/src/backend/postmaster/pgstat.c w.r.t. pg_stat_get_activity()
The collection of stat activity seems to be local to the server - there is no table recording the connections.
