### ISSUE TITLE
[platform] Azure Beta - Force delete universe doesn't destroy vms in Azure

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#7403]
When deleting an error universe with "forced" option, the vms are not clean up. We have to delete them manually in azure portal

**Comment by chirag-yb** [comment]
@tylarb what was the universe state?  Failed/Ready?

**Comment by tylarb** [comment]
@ssung-yugabyte  do you know answer to above?

**Comment by ssung-yugabyte** [comment]
Universe state: failed.

**Comment by streddy-yb** [comment]
@Arnav15 - What are the scenarios under which Platform doesn't delete the underlying cloud VMs? Also, is this behavior Cloud specific?

**Comment by chirag-yb** [comment]
Seems like a duplicate - https://github.com/yugabyte/yugabyte-db/issues/7396
