### ISSUE TITLE
[YSQL] Partially enable CHECKPOINT command

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#7404]
We can enable it as a no-op (with a warning) similar to VACUUM and ANALYZE.
See also: https://github.com/yugabyte/yugabyte-db/issues/2217 and https://github.com/yugabyte/yugabyte-db/issues/7336.
cc @ddorian

**Comment by Ethan-DB** [comment]
I think that all the conditions should be added in `src/postgres/src/backend/postmaster/checkpointer.c`.  Do you agree with me? @tanujnay112  In my example about #7336, I almost mentioned everything in these conditions.

```c
void
RequestCheckpoint(int flags)
{
  if(!(flags & CHECKPOINT_CAUSE_XLOG & CHECKPOINT_IS_SHUTDOWN & CHECKPOINT_END_OF_RECOVERY & CHECKPOINT_IMMEDIATE & CHECKPOINT_FORCE & CHECKPOINT_WAIT))
  {
    ereport(WARNING,
            (errmsg("CHECKPOINT will be ignored")));
     return;
  }
```

**Comment by Ethan-DB** [comment]
In Postgres,

``sql
postgres=# checkpoint;
CHECKPOINT
postgres=# select pg_current_wal_insert_lsn();
 pg_current_wal_insert_lsn 
---------------------------
 0/8060DE0
(1 row)

postgres=# checkpoint;
CHECKPOINT
postgres=# select pg_current_wal_insert_lsn();
 pg_current_wal_insert_lsn 
---------------------------
 0/8060E90
(1 row)

postgres=# checkpoint;
CHECKPOINT
postgres=# select pg_current_wal_insert_lsn();
 pg_current_wal_insert_lsn 
---------------------------
 0/8060F78
(1 row)
```

And I think that it should be added in the command 'checkpoint' of YugabyteDB. In this case, maybe it shouldn’t simply be ignored. @tanujnay112 @m-iancu

**Comment by tanujnay112** [comment]
Cl

> In Postgres,
> 
> ```sql
> postgres=# checkpoint;
> CHECKPOINT
> postgres=# select pg_current_wal_insert_lsn();
>  pg_current_wal_insert_lsn 
> ---------------------------
>  0/8060DE0
> (1 row)
> 
> postgres=# checkpoint;
> CHECKPOINT
> postgres=# select pg_current_wal_insert_lsn();
>  pg_current_wal_insert_lsn 
> ---------------------------
>  0/8060E90
> (1 row)
> 
> postgres=# checkpoint;
> CHECKPOINT
> postgres=# select pg_current_wal_insert_lsn();
>  pg_current_wal_insert_lsn 
> ---------------------------
>  0/8060F78
> (1 row)
> ```
> 
> And I think that it should be added in the command `checkpoint` of YugabyteDB. In this case, maybe it shouldn’t simply be ignored. @tanujnay112 @m-iancu

@Ethan-DB Currently, the WAL does not exist at the Postgres layer but rather in the backend DocDB storage layer. So we made this a no-op for now. However, in the future I think we should support the Postgres-like behavior that you mentioned through the DocDB WAL.

**Comment by EthanDBer** [comment]
So will this feature be included in the future blueprint?  Can you remind me to focus on the implementation of this feature?  @tanujnay112 @m-iancu #7336
