### ISSUE TITLE
[RFE]  Insufficient user feedback in platform for Task Retry

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7408]
When creating a new config it occasionally fails. After fixing the problem you can got to the 'Tasks' (left hand side) and view the Task.
The task has an option to 'Retry Task' - if you click this nothing appears to happen

However if you go to the logs you get:

Hit error 400, message: {"error":"Invalid task type: CloudBootstrap. Only 'Create Universe' task retries are supported."}

So either the retry task should be disabled unless the task is of type 'Create Universe' or the interface should say this is unsupported when the task button is pressed

**Comment by adilakram87** [comment]
@datamgmt
