### ISSUE TITLE
[YCQL] support indexes on JSONB attributes

### ISSUE THREAD

**Issue by ravimurthy** [yugabyte/yugabyte-db#741]
Currently, secondary indexes are supported on regular columns in YCQL tables. This enhancement handles the support for secondary indexes on JSONB attributes stored in YCQL tables.

The first phase will be to index specific jsonb paths (not generalized indexes over entire json content). Example below.

```
CREATE TABLE entities (id int,
version int,
details jsonb,
PRIMARY KEY((id), version));
```
Create index on specific JSONB fields :-

```
CREATE INDEX by_exchange_name ON entities((details->>'exchange')::text);
CREATE INDEX by_index_name ON entities((details->>'company')::text);
CREATE INDEX by_person_name ON entities((details->>'name')::text);
```

```
INSERT INTO entities (id, version, details) 
  values (1, 1, '{"exchange": "nasdaq", "company": "fb", "name": "facebook"}');
```

Pick the index for matching queries like :-
```
SELECT id 
FROM entities
WHERE (details->>'exchange') = 'nasdaq';
```

**Comment by OlegLoginov** [comment]
**Status update:**
*DONE & TESTED:*
- the index creation
- inserting rows into the index (when the data is inserted into the original table)
- deleting rows from the index (when corresponding rows are deleted from the original table)
- selecting the index (when CQL makes a decision to scan the original table or an index)
- selecting data from the index (including index-only scan and index+table scan)
- support for json-attibutes in the covering columns
*DONE but needs bug-fixing:*
- index rows updating (when the data is updated in the original table) - needs bug-fixing on the DocDB level (in cql_operations)
- there is a crash if the json-attribute column is NULL (may be it's been already fixed - we had another issue for NULL values)
*NOT implemented:*
- CLUSTERING ORDER BY for the json-attribute column (in CREATE INDEX)
- DESCRIBE <table_name> must show the new index correctly
- may be some additional tests (unique index, conditional inserts, prepared statements, stress tests, etc.)

**Comment by nocaway** [comment]
This feature has been supported after commit https://github.com/yugabyte/yugabyte-db/commit/bb6ecba12940a9d6614e78fe0d747a7431ebfdc6
