### ISSUE TITLE
Translate Documentation into Chinese

### ISSUE THREAD

**Issue by Ethan-DB** [yugabyte/yugabyte-db#7411]
Hello, I want to participate in the open-source development of yugabyte as soon as possible to solve the issues. According to my idea, the first step should be to translate the English documentation into Chinese and submit the pull request. Do you agree to this?

**Comment by ddorian** [comment]
@Ethan-DB what about contributing in c++ https://docs.yugabyte.com/latest/contribute/ ?

**Comment by Ethan-DB** [comment]
> @Ethan-DB what about contributing in c++ https://docs.yugabyte.com/latest/contribute/ ?

Ok!
