### ISSUE TITLE
On-prem installation sets ssh port to 54422 causes some difficulties

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7416]
For some reason, the default port is set to 54422. The normal port is 22.
In demos, it disrupts the flow - why 54422?
It is possible to set it to 22.

**Comment by adilakram87** [comment]
@datamgmt

**Comment by streddy-yb** [comment]
hi @adilakram87 @tylarb - This is something user can override during the provider creation. You can always set the ssh port to 22. Are you referring to the case where you're not overriding the default value?
![image](https://user-images.githubusercontent.com/68868569/109540570-81a98700-7a77-11eb-9f8d-9bbb010706bd.png)

**Comment by adilakram87** [comment]
@streddy-yb It is possible we default to 22, and enable the option to override to any other port...instead of the other way around.

**Comment by tylarb** [comment]
@streddy-yb  specifically for on prem, since ssh is configured by end user (so make it easy - make it default)

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7599

**Comment by shashwat-yb** [comment]
Validated that the default SSH port is set to 22 for On-prem.

cc @VijiYB
