### ISSUE TITLE
[Platform] Enable encryption by default  Client-to-node/node-to-node

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7421]
Comments:

 ("Enable Client-to-node encryption") is off

This can be enabled by allowing encrypted connections

Similar issue: https://github.com/yugabyte/yugabyte-db/issues/6287

**Comment by adilakram87** [comment]
@datamgmt @tylarb

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7823
