### ISSUE TITLE
[CoreDB] Is this behavior correct in event of a disk failure?

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#7424]
Jira Link: [DB-1866](https://yugabyte.atlassian.net/browse/DB-1866)
Found some interesting behavior simulating a disk failure (deleting disk at PCI layer in /sys filesystem)

Scenario: no load on server, no sample app, etc. Idle.

At the start of logs here, disk was removed by `echo 1 > delete` in `/sys/devices/[pci path]` which is a pretty good proxy for a disk being unavailable (that is, lower than filesystem layer, etc)

Tserver still running (master as well)
```
[yugabyte@yb-dev-yb-test-diskfailure-n2 ~]$ ps aux | grep tserver
yugabyte 24150  0.0  0.0 112660   972 pts/1    S+   23:11   0:00 grep --color=auto tserver
yugabyte 25551  1.2  2.3 1444848 86840 pts/0   Sl   22:51   0:14 /home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/server.conf
yugabyte 25574  0.0  1.2 433352 45548 pts/0    S    22:51   0:00 /home/yugabyte/yb-software/yugabyte-2.2.6.0-b4-centos-x86_64/postgres/bin/postgres -D /mnt/d0/pg_data -p 5433 -h 10.128.0.11 -k  -c logging_collector=on -c log_directory=/mnt/d0/yb-data/tserver/logs -c shared_preload_libraries=pg_stat_statements,yb_pg_metrics -c yb_pg_metrics.node_name=yb-dev-yb-test-diskfailure-n2 -c yb_pg_metrics.port=13000 -c config_file=/mnt/d0/pg_data/ysql_pg.conf -c hba_file=/mnt/d0/pg_data/ysql_hba.conf
```

Can confirm that sdb - mount point /mnt/d0  - the PCI lane it lived on is removed, so it won't even show up as block device (again, different than disk present but filesystem unmounted)

```
[yugabyte@yb-dev-yb-test-diskfailure-n2 ~]$ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  40G  0 disk 
└─sda1   8:1    0  40G  0 part /
```

postgres comments that there's a problem as soon as we connect, but tserver doesn't fail until something written.

```
[yugabyte@yb-dev-yb-test-diskfailure-n2 ~]$ ./yb-software/yugabyte-2.2.6.0-b4-centos-x86_64/bin/ysqlsh  -h `hostname`
WARNING:  could not create relation-cache initialization file "global/pg_internal.init.31103": Input/output error
DETAIL:  Continuing anyway, but there's something wrong.
WARNING:  could not create relation-cache initialization file "12457_pg_internal.init.31103": Input/output error
DETAIL:  Continuing anyway, but there's something wrong.
ysqlsh (11.2-YB-2.2.6.0-b0)
Type "help" for help.

yugabyte=# create table mytable (i int);
FATAL:  terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
!> 
!> q
!> 
!> \q
You have new mail in /var/spool/mail/yugabyte
[yugabyte@yb-dev-yb-test-diskfailure-n2 ~]$ ps aux | grep tserver
yugabyte  3986  0.0  0.0 112660   972 pts/1    R+   23:11   0:00 grep --color=auto tserver
```

**Comment by bmatican** [comment]
@tylarb As discussed offline, currently, we would not be reading from disk in idle state. We have some plans to do that for background consistency checking, but even then, we would probably funnel that info towards some type of alerts, rather than crashing the cluster.

We do however have various crash mechanisms in place, if we hit such errors at runtime, say during data read or write, as we would not be able to continue making progress.

**Comment by tylarb** [comment]
@bmatican  fully understand not writing during idle state. and behavior was correct once write was attempted.

I am really interested in this however:

```
WARNING:  could not create relation-cache initialization file "global/pg_internal.init.31103": Input/output error
DETAIL:  Continuing anyway, but there's something wrong.
WARNING:  could not create relation-cache initialization file "12457_pg_internal.init.31103": Input/output error
DETAIL:  Continuing anyway, but there's something wrong.
```

Does postgres create this new cache file on connection? If so, should postgres crash here, or indicate to the tserver that something is incorrect?
