### ISSUE TITLE
[YSQL] Locking Querying Rows

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#743]
The following clause in SELECT for locking rows is not yet supported.
SELECT ...
  [ FOR
         { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE }
         [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...]
  ]

**Comment by m-iancu** [comment]
Duplicate of #1199 .
