### ISSUE TITLE
[Platform HA] Standby instances backup time not consistent after restoring active instance

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7433]
I brought down/up the Active instance, but the backup time of one of the standby instance its not showing correctly.

Active:http://10.9.8.91:9000
Standby1:http://10.9.1.117:9000
Standby2:http://10.9.1.143:9000/

1. I setup the replication time as 4m
2. Stop/started active 
3. Once the active node is up, the replication started in both the standbys but the standby1 shows the backup time of standby2 some old time, later it synced up but there is a lag. Whereas the standby2 shows the correct time. Seems to be some inconsistent between the standby time sync up.

eg:
http://10.9.1.117:9000 shows:  (117 instance shows the replication time as 5:21 for 143 but in 143, the replication time is 5:25)
Standby1:: Mar 1, 2021 5:25 PM
Standby2:: Mar 1, 2021 5:21 PM
Active : Mar 1, 2021 5:25 PM

http://10.9.1.143:9000 shows:
Active:http://10.9.8.91:9000 --> Mar 1, 2021 5:25 PM
Standby1:http://10.9.1.117:9000 --> Mar 1, 2021 5:25 PM
Standby2:http://10.9.1.143:9000/ --> Mar 1, 2021 5:25 PM

See the screenshots
<img width="2104" alt="Screen Shot 2021-03-01 at 5 25 31 PM" src="https://user-images.githubusercontent.com/78048211/109690681-7750c100-7b3b-11eb-998b-201c8e38cd12.png">
<img width="2141" alt="Screen Shot 2021-03-01 at 5 28 38 PM" src="https://user-images.githubusercontent.com/78048211/109690707-7c157500-7b3b-11eb-994d-7fccbb7cfccf.png">

**Comment by VijiYB** [comment]
<img width="2050" alt="Screen Shot 2021-03-02 at 9 42 45 AM" src="https://user-images.githubusercontent.com/78048211/109690911-b121c780-7b3b-11eb-9afc-ecfadacf6365.png">

**Comment by daniel-yb** [comment]
This is expected at the moment due to the ordering of how I sync data + send backups to each standby. The "fix" here is to modify the ordering such that instead of sending backups + syncing data per each follower at a time we instead:
1. Loop through each follower and send the latest backup
2. Loop through each follower and sync the HA config data
