### ISSUE TITLE
[Platform HA] Suggestion to show http:// while adding instances

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7436]
In the Instances configuration, while adding instances. it would be better to show http:// in the text box for the user to type the IP/hostname like how its grayed out in Replication Configuration page. We are throwing error if not a valid url, its better to show http:// 

<img width="633" alt="Screen Shot 2021-03-02 at 9 51 11 AM" src="https://user-images.githubusercontent.com/78048211/109692136-027e8680-7b3d-11eb-9b0f-a9650024533f.png">

**Comment by sshev** [comment]
Fixed in scope of https://github.com/yugabyte/yugabyte-db/issues/7342
