### ISSUE TITLE
[Platform] UI - In Edit Universe, able to edit User Tags but not save them

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7444]
If the User tags cannot be modified in Edit universe, then its better to disable the text fields and remove "add row". If they are editable, please enable "Save" button when there are changes to the User Tags.

**Comment by streddy-yb** [comment]
We should allow editing editing User Tags instead of disabling the text fields. Currently this is only supported for AWS provider based universes.
