### ISSUE TITLE
[Platform] UI - When universe creation is in progress, UI should disable other menus like "read replica", "edit universe" etc

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7447]
When Universe Creation is in progress, other operations which requires the Universe in "ready" state should be disabled like "Edit universe" , "Read replicas" , "Run sample apps" etc

**Comment by streddy-yb** [comment]
@sunilsutarDCE - please discuss the expected behavior with Arnav.

**Comment by chirag-yb** [comment]
Edit operation in read-only view should be allowed otherwise you will have to wait for the universe creation task to finish for checking the universe configuration
