### ISSUE TITLE
[Docs] `npm ci` step for YB Documentation fails and needs additional step for MacOS Catalina

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#7448]
Issue: `npm ci` step for YB Documentation fails and needs additional step for MacOS Catalina

When initially setting up Yugabyte Documentation locally on macOS Catalina, `npm ci` fails even after installing xcode and performing `xcode-select --install` with the same error 
```
No receipt for 'com.apple.pkg.DeveloperToolsCLI'
```
as mentioned in the documentation

**Note**: I have found the fix and I would like to include the additional detail in existing documentation.

**Comment by ddorian** [comment]
Hi @aishwarya24 

Would you like to make a pull request for the docs ?

**Comment by aishwarya24** [comment]
@ddorian : Hi, yes, I do want to make a Pull request, will do it in a day. Thanks for asking.
