### ISSUE TITLE
[YCQL] Index is not updated from transaction with cross-key statements.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#7455]
The bug can be faced for index updating from a transaction, if the transaction statements use the same PKey, so in the case the statements must be handled serially.
Java test-reproducer:
```
    session.execute("create table test_txn (k int primary key, v1 int, v2 int) " +
                    "with transactions = {'enabled' : true};");
    session.execute("create index i_by_v1 on test_txn(v1);");
    session.execute("create index i_by_v2 on test_txn(v2);");

    session.execute("begin transaction" +
                    "  insert into test_txn (k, v1) values (1, 101);" +
                    "  insert into test_txn (k, v2) values (1, 201);" +
                    "end transaction;");
    // Verify the rows.
    assertQuery("select * from test_txn;", "Row[1, 101, 201]");
    assertQuery("select * from i_by_v1;", "Row[1, 101]");   <<<<<<<< FAILED
    assertQuery("select * from i_by_v2;", "Row[1, 201]");
    // Verify rows can be selected by the index columns.
    assertQuery("select * from test_txn where v1 = 101;", "Row[1, 101, 201]");
    assertQuery("select * from test_txn where v2 = 201;", "Row[1, 101, 201]");
```
The index `i_by_v1` is not updated in the example.

**Comment by OlegLoginov** [comment]
The root cause: table-updating statement has a child statement for index updating. So, TNodeContext has a child TNodeContext, which returns 'child transaction result'. The result must be applied via Transaction API, but it's done for the last statement in the serial chain. Finally index-updating transaction is not applied for the first statement in the serial statement chain.
Currently Executor applies the child transaction results only in the end - when the ExecContext does not have pending operations. So, for the first statement the child transaction result is NOT applied (because ExecContext has pending op for the second statement) and the TNodeContext is deleted as totally handled.

**Comment by OlegLoginov** [comment]
Fix:
OPTION 1: Apply child transaction result even if the ExecContext has pending operations.
OPTION 2: Mark the operation as 'not applied' and wait for the last statement result (do not delete statement context while the child transaction result is not yet applied).

**Comment by mbautin** [comment]
Here is a relevant debug log: https://gist.githubusercontent.com/mbautin/a782a6551f827842255927ecebcda595/raw

For statement:
```sql
 begin transaction insert into test_txn (k, v1) values (123, 456); insert into test_txn (k, v2) values (123, 789); end transaction;
```

**Comment by OlegLoginov** [comment]
Fixed by the commit:  https://github.com/yugabyte/yugabyte-db/commit/75e7aecd87242b80708d4b17caff04e76e134602
