### ISSUE TITLE
Sample app instructions for K8s based Platform installation

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7459]
Missing instructions for K8s installation. Automatically change instructions based on the installation type - Docker, K8s

**Comment by mjoshi0923** [comment]
Installation instructions for k8s is there, following is the screenshot of the same, can you provide more info if I am missing something here? 

<img width="656" alt="Screenshot 2021-03-18 at 10 57 17 AM" src="https://user-images.githubusercontent.com/78336250/111577692-c869e180-87d8-11eb-8ce7-b8508b0e3bdf.png">
<img width="655" alt="Screenshot 2021-03-18 at 10 57 34 AM" src="https://user-images.githubusercontent.com/78336250/111577694-cb64d200-87d8-11eb-929b-6af8842a6633.png">

**Comment by streddy-yb** [comment]
Reopen this if it is still an issue
