### ISSUE TITLE
[Platform] Non-rolling upgrade should be disabled when the universe is in Pause state

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7472]
When the universe is paused, non-rolling upgrade should be disabled. When I try to upgrade with "rolling-upgrade" enabled, getting a warning that the nodes are not live but able to disable the "rolling upgrade" and go ahead with the upgrade. Though it fails as expected, it should not even allow.

**Comment by nishantSharma459** [comment]
![PauseUniverseBug](https://user-images.githubusercontent.com/75416933/109919581-def34180-7cde-11eb-817c-c2ac6dae2fdb.png)
 
Attaching a screenshot. 
PTAL.
@VijiYB  Can you please elaborate on this and add more info?

**Comment by VijiYB** [comment]
In the overview page, you can see the option to upgrade if any new build is available in that por
<img width="562" alt="Screen Shot 2021-03-04 at 8 00 59 AM" src="https://user-images.githubusercontent.com/78048211/109992335-0555b480-7cc0-11eb-9087-4b0cd9eca134.png">
tal.

**Comment by VijiYB** [comment]
<img width="1917" alt="Screen Shot 2021-03-04 at 8 12 16 AM" src="https://user-images.githubusercontent.com/78048211/109993692-69c54380-7cc1-11eb-9dc9-39f851b607a2.png">

On clicking the upgrade on the Overview Info, it opens this pop up to upgrade where by default Rolling-Upgrade is enabled. This actually doesnt allow to continue the upgrade but disable the "Rolling upgrade" its able to proceed and fails.

**Comment by nishantSharma459** [comment]
Here's PR: https://github.com/yugabyte/yugabyte-db/pull/7504
