### ISSUE TITLE
[Platform] Support for creating multiple instances of the same cloud provider type

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7474]
Currently Platform only allows creating one instance of each provider type (viz. AWS, GCP, Azure). There are several use cases that require multiple instances of the same provider type.

**Comment by chirag-yb** [comment]
@streddy-yb we should consider backporting this to 2.6. There is a known limitation for Azure - https://github.com/yugabyte/yugabyte-db/issues/6356 which will be solved with this feature

**Comment by chirag-yb** [comment]
@mjoshi0923 @vpatibandla-yb there is no unique constraint on the cloud provider name? 
![Screen Shot 2021-05-24 at 10 04 49 AM](https://user-images.githubusercontent.com/68662034/119382860-7c736700-bc77-11eb-8faf-4dc9ada8807e.png)


cc: @ymahajan

**Comment by mjoshi0923** [comment]
Nop, but there is already open ticket for this issue.

**Comment by mjoshi0923** [comment]
@vpatibandla-yb Backport has been completed for UI for 2.6

**Comment by vpatibandla-yb** [comment]
@streddy-yb @mjoshi0923 Completed the backport of the changes to the 2.6 branch
