### ISSUE TITLE
Max number of tables

### ISSUE THREAD

**Issue by sakopzon** [yugabyte/yugabyte-db#7478]
What is the maximal number of tables supported? and what causes the limitation?
What is the minimal table metadata size? What is the maximal?
Where is table metadata resides?

**Comment by ddorian** [comment]
Hi @sakopzon 

>  Where is table metadata resides?

On yb-master & yb-tservers.

> What is the maximal number of tables supported?

The unit of scaling is "tablet", not table. A table is spitted into 1+ tablets, and each of them replicated. See more on [sharding docs](https://docs.yugabyte.com/latest/architecture/docdb-sharding/). You can configure 100 tables to reside in 1 tablet. Or configure 1 table to be split in 100 tablets. And we have users with 100GB+ tablets.

>  and what causes the limitation?

Currently having 1000+ tablets per-server starts having cpu/bandwidth overhead. But tablets can grow very big and you usually don't need to create that many. 

Can you explain your app and workload ? Usually you shouldn't need to create hundreds of tables/databases to scale.

**Comment by ddorian** [comment]
Closing because user hasn't replied back.

**Comment by lokesh411** [comment]
I have a similar question, 
The context is we are building an usecase where users can completely customise their tables, so for each customer we might have one or more tables. The data inside the tables might not be very huge as well. But we would need to have one or more tables per customer
