### ISSUE TITLE
[Platform] -Universe Deletion is not clearing out Universe Backups

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#7482]
version :2.4

--context--
The customer tried to delete the backup object(AWS - S3 bucket)

--The customer follows the Following Step:--
1.Create universe
2. add backup job 
3.delete universe
4 .delete backup object Or backup config

--Issue--
Step 4 is not performed successfully (not allowed to delete the backup config)
"Storage Configuration is in use and cannot be deleted until associated resources are removed"

**Comment by streddy-yb** [comment]
Platform should support two different workflows:
- Provide the user an option [checkbox] to delete the backups as part of deleting the universe.
- If the user choses to keep the universe backups for later reuse, provide an alternate workflow to delete backups that are not associated with any universe.

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7864

**Comment by streddy-yb** [comment]
hi @mahendranbhat - Can you backport this to 2.6 branch?

**Comment by RP1807** [comment]
Validated this issue on the portal. Followed below steps 

1. Ensure Delete Universe pop-up supports delete associated backups checkbox via "Delete backup" checkbox (Default: False)
2. Ensure platform delete associated backup while deleting universe when "Delete backups" is checked. 
3. Ensure platform delete multiple backups created in the different cloud for a particular universe while deleting universe 
4. Ensure the platform doesn't delete backups associated with the universe when "Delete backups" is not checked.
5. Ensure the platform deletes backups configured in multiple clouds (S3, GCS & Azure) associated with the universe while deleting the universe. 
6. Ensure warning comes when a user tries to delete paused universe with associated backups. 
7. Ensure the platform deletes associated NFS backups when deleting the universe.

**Comment by mahendranbhat** [comment]
@streddy-yb backported to 2.6.
cc: @RP1807

**Comment by RP1807** [comment]
Validated this issue on 2.6. Working as expected.
