### ISSUE TITLE
[Docs] Certain steps are interchanged for asynchronous replication in YSQL and YCQL

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#7486]
Issue: Under section 2 (Create database tables) on this page:

https://docs.yugabyte.com/latest/explore/multi-region-deployments/asynchronous-replication-ysql/

The commands to create database tables are mentioned for `ycql` instead of `ysql` starting from this statement:
**Open ycqlsh specifying the host IP address of 127.0.0.1**

Most of the steps further refer to `ycql` instead of `ysql`. Likewise, for **asynchronous replication in YCQL** , the commands are interchanged similarly on this page:

https://docs.yugabyte.com/latest/explore/multi-region-deployments/asynchronous-replication-ycql/

Note: I would like to take up the issue.

**Comment by polarweasel** [comment]
@aishwarya24 thanks for your bug report, and offer to help! Please let me know if you need any help from us, and I look forward to your contributions!
