### ISSUE TITLE
[Docs] yugabyte db transaction isolation level default value

### ISSUE THREAD

**Issue by EthanDBer** [yugabyte/yugabyte-db#7503]
# Bug Report
## Summary

```sql
yugabyte=# show transaction isolation level;
 transaction_isolation 
-----------------------
 read committed
(1 row)

yugabyte=# show default_transaction_isolation;
 default_transaction_isolation 
-------------------------------
 read committed
(1 row)
```

But in [Doc](https://docs.yugabyte.com/latest/architecture/design-goals/#multi-row-acid-transactions) show `REPEATABLE READ (default) `.  Should this be modified?

```sql
yugabyte=# begin;
BEGIN
yugabyte=# set default_transaction_isolation='repeatable read';
SET
yugabyte=# show transaction isolation level;
 transaction_isolation 
-----------------------
 read committed
(1 row)

yugabyte=# show default_transaction_isolation;
 default_transaction_isolation 
-------------------------------
 repeatable read
(1 row)
```

**Comment by ddorian** [comment]
Hi @Ethan-DB 

See this table https://docs.yugabyte.com/latest/explore/transactions/isolation-levels/

Both `read committed` and `repeatable read` are mapped to `snapshot isolation`.

**Comment by Ethan-DB** [comment]
> Hi @Ethan-DB
> 
> See this table https://docs.yugabyte.com/latest/explore/transactions/isolation-levels/
> 
> Both `read committed` and `repeatable read` are mapped to `snapshot isolation`.


In fact, I think that the organization of the documentation is not very reasonable. Perhaps it should be explained here, especially for PostgreSQL users. This is easy to cause confusion.

**Comment by ddorian** [comment]
```sql
yugabyte=# show transaction isolation level;
 transaction_isolation 
-----------------------
 read committed -> Snapshot
(1 row)
```
This will probably break many applications & drivers that expect to work with those names and provide more confusion.

**Comment by Ethan-DB** [comment]
> ```sql
> yugabyte=# show transaction isolation level;
>  transaction_isolation 
> -----------------------
>  read committed -> Snapshot
> (1 row)
> ```
> 
> This will probably break many applications & drivers that expect to work with those names and provide more confusion.

Indeed. 
May I try to fix the bug in this documentation? If possible, please assign it to me, I will discuss it with @polarweasel  and fix this issue.

**Comment by Ethan-DB** [comment]
And, I think that the result of `default_transaction_isolation` is not appropriate.

```sql 
yugabyte=# show default_transaction_isolation;
 default_transaction_isolation 
-------------------------------
 read committed
(1 row)
```

**Comment by polarweasel** [comment]
@Ethan-DB thanks for your desire to help fix this! Happy to help you out here. Let me know if you've got any questions, or run into any problems.

**Comment by Ethan-DB** [comment]
@polarweasel Thanks.

**Comment by Ethan-DB** [comment]
PTAL @polarweasel
