### ISSUE TITLE
[Platform] UI - User's dropdown menu (right-upper corner) doesn't work on `Dashboard` and `Universes` pages

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#7507]
Logged in as itest user, just removed a failed universe. So no universes exist. Also there is only one provider (aws) in the configuration.
The dropdown menu doesn't work when I selected 'Dashboard' or 'Universes' page. On other pages it works. Full refresh doesn't help.

**Comment by streddy-yb** [comment]
hi @SergeyPotachev - what permissions does itest user have?

**Comment by sunilsutarDCE** [comment]
Hi @streddy-yb @SergeyPotachev ,
I think its not related to any user , due to some recent UI changes the User menu was not clickable , and this change was fixed  and merged . Still @SergeyPotachev - let me know user role , will check it .

**Comment by SergeyPotachev** [comment]
Fixed with https://github.com/yugabyte/yugabyte-db/commit/02e86dfb47b336972c528c925ff652254064e11e

**Comment by SergeyPotachev** [comment]
Verified.
