### ISSUE TITLE
[YSQL] DDL operations should cleanly handle failed Postgres syscatalog updates

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#753]
Jira Link: [DB-2529](https://yugabyte.atlassian.net/browse/DB-2529)
It can happen that Postgres system catalog updates related to a DDL operation fail after the YugaByte DDL operation is finished. 
Then the YSQL operation will fail as expected, but YugaByte's internal metadata may remain inconsistent (since the YugaByte operation succeeded): e.g. a failed `CREATE TABLE` command may leave around a YugaByte table in `DONE` state.
The YugaByte operation should not be considered done until the Postgres catalog updates have finished.

**Comment by deeps1991** [comment]
Tracked in https://github.com/yugabyte/yugabyte-db/issues/13358

**Comment by deeps1991** [comment]
Duplicated by https://github.com/yugabyte/yugabyte-db/issues/13358

**Comment by deeps1991** [comment]
Duplicated by https://github.com/yugabyte/yugabyte-db/issues/13358
