### ISSUE TITLE
[Platform] Universe alerts should be resolved when a universe is deleted

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#7537]
Whenever a given universe is deleted, we should set the state of all created or active alerts to resolved that have a target UUID matching the universe UUID of the universe being deleted.

We should NOT send a resolved email when resolving these alerts.

**Comment by streddy-yb** [comment]
hi @daniel-yb - Any particular reason to retain the alerts of a universe that is already deleted? For example, why mark the alerts as resolved as opposed to delete the alerts?

**Comment by daniel-yb** [comment]
@streddy-yb I was just thinking in terms of keeping old ones around for auditing purposes (similar to how we don't delete tasks related to a universe when it is deleted).

The API only lists active alerts, so this won't be a scaling problem in that regard. If we start seeing too many alerts in the DB causing other kinds of issues, we can add some GC'ing to them similar to GC'ing tasks.

If you feel there isn't value in keeping them around though, then there shouldn't be any issues with deleting them.

**Comment by streddy-yb** [comment]
@daniel-yb - thanks, makes sense.
