### ISSUE TITLE
[Platform] Add additional info to alerts page in UI

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#7538]
Some alerts that we currently trigger (mainly for health check errors) don't say which universe they are for. We should have this info in the UI somehow.

There are two ways that I can see for us to accomplish this (IMO implementing both of these will be useful):
1. For alerts that have a "UniverseType" target type, we should link active alerts to the universe overview page in the UI using the targetUUID value for that alert.
2. Add the universe name to the alert message (we already use this approach for non-health check alerts).

**Comment by sunilsutarDCE** [comment]
Closing this as Alerting will be improved as a part of this #8212
