### ISSUE TITLE
[docdb] Show ALIVE time for masters in the master home UI

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7543]
Basically in `master_ip:7000/`, next to the raft information, we can also show the uptime, like we do for the `/tablet-servers`

**Comment by triump2020** [comment]
@bmatican   i'd like to give it a shot !  assign me

**Comment by kmuthukk** [comment]
Thx @triump2020 !

**Comment by triump2020** [comment]
@bmatican   How dose  the leader-master  get the uptime information for the other follower-master  in a raft group ?    the master 
gets the uptime information for the **tserver**  through heartbeating by tserver   , but there seems not be a way  to get the uptime information for the follower-master ?

**Comment by bmatican** [comment]
Hey @triump2020, that's a great question! For TS>master communication, we actually add the uptime in a custom fashion, during the heartbeating code path. However, that won't work for masters, out of the box.

For the master UI, we essentially use the `ListMasters` RPC, which underneath has a list of `ServerEntryPB`, each of which has their corresponding `NodeInstancePB` of the respective masters. This means if the instance data has the startup time, we should be good!

So my suggestion then would be to augment `NodeInstancePB`. Eventually we could refactor the TS heartbeat codepath to also use this. This protobuf is generated at server startup, for both master and tserver, and contains a minimal amount of information:
```
// Uniquely identify a particular instance of a particular server in the
// cluster.
message NodeInstancePB {
  // Unique ID which is created when the server is first started
  // up. This is stored persistently on disk.
  required bytes permanent_uuid = 1;

  // Sequence number incremented on every start-up of the server.
  // This makes it easy to detect when an instance has restarted (and
  // thus can be assumed to have forgotten any soft state it had in
  // memory).
  //
  // On a freshly initialized server, the first sequence number
  // should be 0.
  required int64 instance_seqno = 2;
}
```
We could add a 3rd field above, as optional (so there's no backwards incompatibility issues), where we record the actual start time of the server.

The code that generates this is here:
```
void RpcAndWebServerBase::GenerateInstanceID() {
  instance_pb_.reset(new NodeInstancePB);
  instance_pb_->set_permanent_uuid(fs_manager_->uuid());
  // TODO: maybe actually bump a sequence number on local disk instead of
  // using time.
  instance_pb_->set_instance_seqno(Env::Default()->NowMicros());
}
```
Note, that even though technically, I think we could already use the `instance_seqno`, because it is implemented as the `NowMicros` of when the server starts up, that feels like an implementation detail that we should not rely on...

**Comment by triump2020** [comment]
@bmatican   Thanks for your detailed pointers ,   i 'll going on !

**Comment by triump2020** [comment]
@bmatican   Adding ` startup time` to `NodeInstancePB`  may be not enough ,  since leader-master needs to know the **time interval**  since  follower-master's startup until now.   It would be better to let the follower-master compute the uptime( time interval) itself ,  then response to the leader-master .

So  i  added a `uptime_seconds` in `GetMasterRegistrationResponsePB` and `ServerEntryPB`, but i 'm not sure that doing the right thing ?  

```protobuf
// GetMasterRegistrationRequest/Response: get the instance id and
// HTTP/RPC addresses for this Master server.
message GetMasterRegistrationRequestPB {
}

// TODO: Just use ServerRegistration here.
message GetMasterRegistrationResponsePB {
  // Node instance information is always set.
  required NodeInstancePB instance_id = 1;

  // These fields are optional, as they won't be set if there's an
  // error retrieving the host/port information.
  optional ServerRegistrationPB registration = 2;

  // This server's role in the consensus configuration.
  optional consensus.RaftPeerPB.Role role = 3;

  // Set if there an error retrieving the registration information.
  optional MasterErrorPB error = 4;
  
  // the time interval from master's starting up to now
   optional uint64 uptime_seconds = 5; 
  
}
```

```protobuf
wire_protocol.proto

message ServerEntryPB {
  // If there is an error communicating with the server (or retrieving
  // the server registration on the server itself), this field will be
  // set to contain the error.
  //
  // All subsequent fields are optional, as they may not be set if
  // an error is encountered communicating with the individual server.
  optional AppStatusPB error = 1;

  optional NodeInstancePB instance_id = 2;
  optional ServerRegistrationPB registration = 3;

  // If an error has occurred earlier in the RPC call, the role
  // may be not be set.
  optional consensus.RaftPeerPB.Role role = 4;
  
   // the time interval from master's starting up to now
   optional uint64 uptime_seconds = 5; 
}
```

**Comment by bmatican** [comment]
@triump2020 I don't think you need to add uptime, it's ok if we add start time and just do the `now - start_time` on the master leader side, for each of the followers.

**Comment by triump2020** [comment]
@bmatican  Yes !  it's my first idea.   But its correctness depends on which type of clock would be used, right ?   if  use **sysytem clock** ,  the two clocks may be not sync with each other;  if use **HLC** ,  it's no problem , but  affects performance , since  `HybridTime::Now() `  is a CAS operation .  

So  my idea  came from above considerations .

**Comment by triump2020** [comment]
@bmatican   Considering that it 's  more of a debug metric,  using **system clock**  should be fine !   @kmuthukk

**Comment by triump2020** [comment]
By the way , from the codebase, the **TServer** calculates  **uptime itself** , then reports to **master** through heartbeat.

TServer calculates uptime:
```c++
uint64_t TServerMetricsHeartbeatDataProvider::CalculateUptime() {

	MonoDelta delta = MonoTime::Now().GetDeltaSince(start_time_);

	uint64_t uptime_seconds = static_cast<uint64_t>(delta.ToSeconds());

	return uptime_seconds;

}
```
Tserver prepares hearbeat data :
```c++
TServerMetricsHeartbeatDataProvider::DoAddData(
    const master::TSHeartbeatResponsePB& last_resp, master::TSHeartbeatRequestPB* req) {
 ............
uint64_t uptime_seconds = CalculateUptime();
metrics->set_uptime_seconds(uptime_seconds);
 ............
}
```
So , if we calculate the uptime  for follower-master on leader-master side through `now() - start_time` , then the logic would be inconsistent .

**Comment by bmatican** [comment]
@triump2020 That's a good point!

However, I see two main differences, to justify leaving this up to the client:
- in the heartbeat case, each TS pushes data to the master, so that data is expected to be more dynamic already, hence the PBs we use have context that's expected to change frequently (metrics, tablet information, etc)
- in the `ListMasters` case, the information that flows is pretty static (master UUIDs, http/rpc addresses, etc) and changing some of the underlying functions (eg: GetMasterEntryForHosts, GetMasterRegistration) seems more involved, than just adding a new field in the PB and making most of the changes be on the caller side

As such, I feel that enhancing the node info / master registration info, to just have start time, and letting the uptime (ie: now - start time) be computed on the client side, is both simpler and matches the type of data being passed around.

**Comment by triump2020** [comment]
@bmatican   pls review ,thanks!   i have tested it on my local cluster.
