### ISSUE TITLE
[docdb] Make tcmalloc_max_total_thread_cache_bytes automatic based on machine memory

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7547]
In high memory machines, we've frequently had to bump this flag to a higher value. We should probably just make this default -1 and set it based on max available memory on the machine.

It currently defaults to 256MB.

Could aim for something like
- at or below 16GB memory -> 256MB value
- at or above 144GB memory -> 2GB value
- some form of sliding scale for values in between

cc @kmuthukk

**Comment by amitanandaiyer** [comment]
should probably be based on the amount of memory available to the tserver.

But, calculated accordingly to fit the same scale.
