### ISSUE TITLE
 CqlIndexTest.ConcurrentIndexUpdate can get stuck and produce 4 GB of logs

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#7581]
Jira Link: [DB-4569](https://yugabyte.atlassian.net/browse/DB-4569)
Log spew of this kind of message:

```
I0310 02:01:55.039978  3777 cql-index-test.cc:148] Insert failed: Service unavailable (yb/integration-tests/cql_test_util.cc:227): All connections on all I/O threads are busy
```

Finally fails like so:

https://gist.githubusercontent.com/mbautin/a2c880649bbf0d7a0623532eafa8aade/raw

**Comment by rthallamko3** [comment]
Per [report] (https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=CppCassandraDriverTest&name=ConcurrentIndexUpdate), the test is running clean, except for mac builds. Closing this for now.
