### ISSUE TITLE
[YCQL] Bulk load/unload for YugabyeDB

### ISSUE THREAD

**Issue by suranjan** [yugabyte/yugabyte-db#7585]
Jira Link: [DB-1388](https://yugabyte.atlassian.net/browse/DB-1388)
Support for bulk load and unload in YugabyteDB based on configurations.

**Comment by dorian-stream** [comment]
@suranjan can you be more clear on the description ?

**Comment by sushantrmishra** [comment]
bulk load can be achieved using [yb-voyager](https://docs.yugabyte.com/preview/migrate/ )
