### ISSUE TITLE
[Platform] cloud provider/backup config should have a test-connection button for access validation

### ISSUE THREAD

**Issue by ssung-yugabyte** [yugabyte/yugabyte-db#7590]
The cloud provider and backup config page lack a "test connection/preflight" button to validate the user input is good.
 For example,
In azure backup config page, SAS token should begin with ?sv.  and url should not contain the sas token.
In s3 backup config page, the buck name field should provide a hint for user to follow:  s3://bucket_name/folder 
Once the user fills the bucket and url, there should be a "test-connection" to validate the bucket is accessible.

**Comment by chirag-yb** [comment]
Duplicate - https://github.com/yugabyte/yugabyte-db/issues/6459 https://github.com/yugabyte/yugabyte-db/issues/6460
