### ISSUE TITLE
[Platform] Delete backup not listed on Task History of that universe

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7594]
When a backup is deleted, its not listed on the Task history of that universe but when you go to Task (from left side bar) which shows the Delete backup. The problem here is because the name of the "Delete backup" is not connected to the correct universe, it just says "Backup" unlike other tasks where the name should be the name of the universe (see the screenshot)

<img width="1181" alt="Screen Shot 2021-03-10 at 12 48 17 PM" src="https://user-images.githubusercontent.com/78048211/110695582-ec0ca680-819e-11eb-9239-94f6de3544a9.png">

**Comment by streddy-yb** [comment]
I think this is a dup of #5830
