### ISSUE TITLE
Basic PostgreSQL support

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#76]
Add support for a basic set of operations with Postgres:
- Create a simple key-value table
- Inserting rows
- Updating rows
- Deleting rows
- Dropping the table

**Comment by pouledodue** [comment]
If you need ideas what to prioritize after Basic Support, i have this query in my code:
```
update rooms set state='booked' where number = (select number
from rooms where state='available' order by random() limit 1 for
update skip locked) returning number;
```
