### ISSUE TITLE
[YSQL] support for SET TRANSACTION statement

### ISSUE THREAD

**Issue by ravimurthy** [yugabyte/yugabyte-db#760]
Support for SET TRANSACTION command.
https://www.postgresql.org/docs/11/sql-set-transaction.html

Currently fails with the following error :- 

sample=# begin;                                                                                                       
BEGIN
sample=# set transaction isolation level repeatable read;                                                             
ERROR:  SET TRANSACTION ISOLATION LEVEL must be called before any query

**Comment by jj-kim** [comment]
This works by now.
