### ISSUE TITLE
[Docs] cloud provider documentation has incorrect details to configure kubernetes cloud provider

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#7611]
YB platform [Kubernetes cloud provider docs](https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes/#prerequisites) mention the following 
```
If you plan to run YugabyteDB nodes on Kubernetes, all you need to provide in the Yugabyte Platform console is your cloud provider credentials. The Yugabyte Platform will use those credentials to automatically provision and de-provision instances that run Yugabyte. An 'instance' for YugabyteDB includes a compute instance as well as local or remote disk storage attached to the compute instance.
```
For Kubernetes, we don't need to provide cloud credentials, documentation is incorrect. Kubernetes cloud configurations need a `kubeconfig` file which was generated in the following [step]( https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes/#create-a-kubeconfig-file-for-a-kubernetes-cluster).

**Comment by polarweasel** [comment]
@nchandrappa please review the associated PR #7684 ...
