### ISSUE TITLE
[docdb] Record and display disk usage by drive

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7617]
On the TS side, we currently track disk usage
- split by consensus metadata // raft WAL files // rocksdb SST files (compressed and uncompressed)
- display it by tablet in the `TS_IP:9000/tablets` as `On-disk size`
- display it by table, in aggregate, in the `TS_IP:9000/tables` as `On-disk size`

Given that we also know, for each tablet, which of the `--fs_data_dirs` components it is associated with, we should be able to report this information to the master, so we build a cluster wide view.

This can be a stepping stone to #3375

**Comment by bmatican** [comment]
Let's split this task into two pieces:

**1) One for high level per drive disk usage**

We can think of this as exporting metrics from each TS, per drive, with disk used / total disk, so we can more easily alert if, say, any disk is getting over X% full.

We can start with this, and just keep this information on the TS first, maybe put it in some new debug UI + metrics, to be consumed by the Platform team.

**2) Fine grained per drive disk usage**

We can think of this as tracking the explicit per tablet usage that is mentioned in the summary (metadata, raft WALs, rocksdb SST). This would be useful for more granular decision making, like which tablet is the most loaded, on any disk, to consider for LB moves.

This can be an immediate followup and can also flow the information from 1) to the master as well, as the sum of all tablet data might not be the total disk used, in case the user drives have any non-YB data on them...

**Comment by mikhpolitov** [comment]
Screenshot of TServer
<img width="1658" alt="screenshot" src="https://user-images.githubusercontent.com/73105980/114835309-1a9f2200-9dda-11eb-9fd4-74c001ac84db.png">
Screenshot of Master
<img width="1658" alt="screenshot2" src="https://user-images.githubusercontent.com/73105980/114835337-22f75d00-9dda-11eb-8f48-f90f95bf40ab.png">
