### ISSUE TITLE
[Docs] VMware Tanzu cloud provider documentation 

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#7622]
Updated content for [VMware Tanzu cloud config docs.](https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/vmware-tanzu/).

[Here](https://docs.google.com/document/d/1iToyeK-fwacQObK7Ebup8hGFKSsdDWDYqySjUvnZ_LE/edit) is the google doc with updated content.

**Comment by lizayugabyte** [comment]
@nchandrappa Is this a new section for https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/vmware-tanzu/ ?
