### ISSUE TITLE
[docdb] New rocksdb metadata for unique rows to provide better table statistics for YSQL

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7623]
During generating rocksdb SST files, we could add some extra metadata for number of unique rows in a file. In aggregate, this can give us an estimate of number of rows in a tablet and with some bubbling up, in a table. That can be a "good enough" heuristic for query planning table statistics.

cc @robertsami @m-iancu

**Comment by robertsami** [comment]
cc @YintongMa who is taking a look at this

**Comment by robertsami** [comment]
superseded by https://github.com/yugabyte/yugabyte-db/issues/8756
