### ISSUE TITLE
[Platform] GCP universe creation fails when airgap setting is enabled in provider

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#7627]
1. Create a GCP provider in Platform with airgapped checkbox turned on.
2. Create a universe with "assign public IP" setting off.  (if there is no internet gateway, this should mean that VMs will not have internet access)

Universe creation fails.

With the [recent change](https://github.com/yugabyte/yugabyte-db/commit/5e38f6bcc2b35d042a41df2b9e9cd03d27d32c00) to use a newer version of centos, the provisioning step in Platform needs to install additional yum packages which aren't available in the default centos image (rsync, policycoreutils-python)

https://github.com/yugabyte/yugabyte-db/blob/2deb855883f315b75cf8129cda216b79d4c6afc8/managed/devops/use_custom_ssh_port.yml#L20
https://github.com/yugabyte/yugabyte-db/commit/41b69bc360bb2a7b8342b2c6cc3af435adf65a24

**Comment by tylarb** [comment]
Workaround is install 2.2, then upgrade to 2.4. Ideally a user could install 2.4 and create universes without this additional upgrade step.

**Comment by iSignal** [comment]
If we provide a "custom image" option for GCP like we do for AWS, we could allow use of an older centos image or a custom centos image that has this package installed already.

**Comment by tylarb** [comment]
Additional details in reference issue [1467](https://yugabyte.zendesk.com/agent/tickets/1467)

**Comment by hsiaosu-yb** [comment]
I'm leaning towards providing a "custom image" option for GCP -- this would allow us to test new images easier.

**Comment by hsiaosu-yb** [comment]
Will fix this regression by making sure that the default GCP image to have these packages installed.  For "custom image" option on GCP, we'll treat that as a separate enhancement.

**Comment by hsiaosu-yb** [comment]
Filed #9302 for tracking the "custom image" option.

**Comment by hsiaosu-yb** [comment]
@SergeyPotachev I think we have discussed this, and that it's ok to revert the change that @iSignal mentioned above:

https://github.com/yugabyte/yugabyte-db/commit/5e38f6bcc2b35d042a41df2b9e9cd03d27d32c00

**Comment by hsiaosu-yb** [comment]
Changed assignee to @iSignal .  We'll revert for 2.4

**Comment by iSignal** [comment]
The new image is reverted in the 2.4 branch.

**Comment by jatinbhowad** [comment]
Verified on Build #2.4.6.0-b10, Able to create universe successfully

Steps Performed:
1. Create GCP provider configuration with airgap ON
2. Create a universe with "Assign Public IP" setting OFF

Hence, closing this bug.
