### ISSUE TITLE
[Platform] backup with authentication on failed due to local socket is missing.

### ISSUE THREAD

**Issue by ssung-yugabyte** [yugabyte/yugabyte-db#7637]
After updated gflags  and rolling restart,

> ysql_enable_auth = true
> ysql_hba_conf_csv = local all all trust

The yugaware s3 backup failed with the following error:

> Failed to execute task java.util.concurrent.FutureTask@5895a3aa, hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/c55dc1b0-1737-4ff8-a48a-07094337455c/yb-cloud-midoin-key.pem', '-p', '54422', '-q', 'yugabyte@172.30.4.142', \"cd / &&  bash -c 'ls /tmp/.yb.*/.s.PGSQL.*'\"]' returned non-zero exit status 2"}.

In yb-node, /tmp/.yb.* dir is empty

> yb-node$ls /tmp/.yb.\*
> yb-node$

In yb-node, ysql_hba.conf looks good. 

> yb-node$ cat /mnt/d0/pg_data/ysql_hba.conf
> ##This is an autogenerated file, do not edit manually!
> host all all 0.0.0.0/0 md5
> host all all ::0/0 md5
> local all all trust

in yb-node, /mnt/d0/yb-data/tserver/logs/postgres log

> yb-node$ tail postgresql-2021-03-13_204347.log
> I0313 21:03:10.693692 24238 secure.cc:118] Certs directory: /home/yugabyte/yugabyte-tls-config, name:
> I0313 21:03:10.695814 24238 thread_pool.cc:171] Starting thread pool { name: pggate_ybclient queue_limit: 10000 max_workers: 1024 }
> I0313 21:03:10.696455 24245 async_initializer.cc:82] Starting to init ybclient
> I0313 21:03:10.696554 24245 client-internal.cc:2088] Reinitialize master addresses from file: /home/yugabyte/tserver/conf/server.conf
> I0313 21:03:10.696630 24245 client-internal.cc:2117] New master addresses: [172.30.4.102:7100,172.30.4.142:7100,172.30.4.59:7100]
> W0313 21:03:10.702131 24245 client-internal.cc:1137] Failed to get hostname: Network error (yb/util/net/net_util.cc:427): Unable to lookup FQDN (ip-172-30-4-102.eu-central-1.compute.internal), getaddrinfo returned -2 (EAI_NONAME): Success (system error 0)
> I0313 21:03:10.702196 24245 async_initializer.cc:86] Successfully built ybclient
> 2021-03-13 21:03:10.709 UTC [24238] FATAL:  password authentication failed for user "postgres"
> 2021-03-13 21:03:10.709 UTC [24238] DETAIL:  User "postgres" has no password assigned.
> 	Connection matched pg_hba.conf line 2: "host all all 0.0.0.0/0 md5"

**Comment by streddy-yb** [comment]
This is fixed in 2.4.1.0 version. I just verified it with a fresh install.
