### ISSUE TITLE
[YSQL] Unable to backspace in psql

### ISSUE THREAD

**Issue by harshithdepa** [yugabyte/yugabyte-db#764]
I ssh'd into one of my tservers on aws created through the yugaware ui, and I was unable to backspace in the psql shell. Backspace just pushed the cursor forward and finishing the erroneous query with a semicolon didn't work after either. There was no response at all from psql. I had to ctrl-Z and kill the process, and then i opened a new psql and had to type my query with no errors as the issue persisted.

**Comment by ddorian** [comment]
This broke again on `2.0.3`.

**Comment by ddorian** [comment]
Tested locally:
1. `./yb-ctl create`
2. `./ysqlsh`
3. write stuff and try to backspace

**Comment by knorpsiu** [comment]
I'm having the same issue; I use CTRL+L to refresh the display, but it is not always handy...

**Comment by m-iancu** [comment]
This should be working now as it hasn't be hit/reported in a long time. May have been related to: https://github.com/yugabyte/yugabyte-db/commit/d372e8877065dcb97333b460093c0a41ef48128d.
