### ISSUE TITLE
[docdb] Rocksdb num SST files info missing from TS /tablets view

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7647]
This is the header and a sample first row from a `TS_IP:9000/tablets`

<img width="1489" alt="Screen Shot 2021-03-15 at 11 48 28 AM" src="https://user-images.githubusercontent.com/395011/111181437-38733000-856b-11eb-90d7-48413290da53.png">

Note how the number of SST column is empty for some reason.

Funny enough, in the `/tables` view, where we aggregate across all relevant tablets, that is present, so the data must be easily accessible!

cc @robertsami @ttyusupov

**Comment by jmeehan16** [comment]
Fix incoming, pending review. Below is a screen capture post-fix:
![tserver-tablets-7647-fix](https://user-images.githubusercontent.com/2799714/111681213-61105980-87f9-11eb-89eb-2df4ae1de4ce.png)

**Comment by jmeehan16** [comment]
Commit 7413808 resolves this issue.
