### ISSUE TITLE
[YSQL] Always listen on UNIX domain socket

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#7651]
Right now YSQL only listens on the UNIX domain socket depending on the value of `ysql_disable_index_backfill` gflag. YW depends on YSQL always listening on this for taking YSQL backups when YSQL authentication is enabled.

The change needed is to always be listening on a UNIX domain socket regardless of the value of `ysql_disable_index_backfill`

**Comment by streddy-yb** [comment]
hi @daniel-yb - can you backport this to 2.4? thanks
