### ISSUE TITLE
[Platform] Make client cert optional in custom certs workflow

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#7655]
After the work related to https://github.com/yugabyte/yugabyte-db/issues/7153#issuecomment-780368608 we no longer need a client cert by default to connect to a TLS enabled universe. We need to simplify our custom certs flow to make the client cert part optional. When the user creates an onprem universe that points to a custom cert and checks "client to node encryption in transit", we should not fail the operation if the custom cert does not contain a client cert.

**Comment by sshev** [comment]
@hkandala the client cert field at Add Certificate modal is already optional in UI
let me know if there are any additional changes required on UI

**Comment by hkandala** [comment]
No changes are needed from backend too.
Verified the code flow and client certificates are considered optional everywhere.
Also verified by creating on-prem universe with client to node encryption enabled using custom certificates (without client cert). Was able to successfully create and connect to the universe.
