### ISSUE TITLE
[Platform] After manually provisioning an onprem node, create universe tries to use "centos" user, not "yugabyte"

### ISSUE THREAD

**Issue by jvigil-yugabyte** [yugabyte/yugabyte-db#7656]
Steps to reproduce:
1. Create an onprem provider config:
  * ssh user: centos
  * manually provisioning: enabled
2. Run script to manually pre-provision the node.
3. Attempt to create universe. Should see an error like:
```
Node jvigil-dev-onprem (10.10.1.161) failed preflight checks:
{
  "SSH Connection": true, 
  "(Home Directory) /home/yugabyte is writable": false, 
  "Try Ansible Command": true, 
  "Yugabyte User": true, 
  "Yugabyte Group": true
}
```

After some debugging w/ @WesleyW, this failed because it attempted to use the "centos" user to check if the `/home/yugabyte` directory is writeable, not the "yugabyte" user.

**Comment by streddy-yb** [comment]
Verified the following using 2.4.2.0-b35:
- Create an onprem provider config with ssh user as centos and manually provisioning: enabled
- Run script to manually pre-provision the node.
- Create a universe
- Connect using ysqlsh
- Delete universe
