### ISSUE TITLE
[Documentation] Update Required for page Explore Yugabyte SQL

### ISSUE THREAD

**Issue by kabeer27** [yugabyte/yugabyte-db#7663]
https://docs.yugabyte.com/latest/quick-start/explore/ysql/

On this page the .sql file commands
that are described to be in `share` folder, seem to have been moved to `sample` folder.

**Comment by polarweasel** [comment]
In my local 2.5.3.1 install, they're in `share`... What version/platform etc. are you using, @kabeer27?

**Comment by polarweasel** [comment]
I bet I know what's going on... you're looking in the git repository, not the actual install directory that you get when you follow the steps in the quick-start (steps for [macOS](https://docs.yugabyte.com/latest/quick-start/install/macos/) or [Linux](https://docs.yugabyte.com/latest/quick-start/install/linux/) or [Docker](https://docs.yugabyte.com/latest/quick-start/install/docker/) or [Kubernetes](https://docs.yugabyte.com/latest/quick-start/install/kubernetes/)).

These instructions are meant to be run from the database install directory.
