### ISSUE TITLE
[Platform] Revert python3 packaging changes

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#7679]
The following commits need to be reverted to fix python packaging:
620d2756922ad801ee32f65ead7ac299630e7195
d53f664cb94eb90d1900405d67a31ea77261a704
3a0af5510ad484d689e524365feefca73846adca
347fd541ad7c251f1e2d2c3f79647b065ef9ca1e
3a949c4db350d26cb872c5d2ddfef7d9024b18ee

**Comment by rtsisyk** [comment]
Please fix Python3 bugs instead of reverting to Python2.

**Comment by streddy-yb** [comment]
#7643 is tracking reenabling Python3 as the default option
