### ISSUE TITLE
[Docs] Improvements for K8s cloud provider

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7680]
Regarding general k8s docs improvements, the plan was to address the following
During platform install, show how to get the LB IP.
Be able to bring up internal LBs
We could add NodePort here too
How to overide pods size?
How to refer to alternate repositories?
In the k8s provider configuration page, explain how the new flow for specifying a k8s namespace works. This is common to k8s and openshift but kind of necessary in openshift
In the k8s provider configuration page, explain how the service account RBAC has to be set up (this is incomplete and on the wrong page now)
Some of these topics are covered in https://github.com/yugabyte/yugabyte-db/issues/7326
Agree that we need newer screenshots etc in some of these case

**Comment by chirag-yb** [comment]
Links to https://github.com/yugabyte/yugabyte-db/issues/7326

**Comment by lizayugabyte** [comment]
@bhavin192 @chirag-yb @iSignal @baba230896  With #7326 closed, is this ticket still relevant? 
If so, what exactly is missing?

**Comment by iSignal** [comment]
One issue that was mentioned in #7326 but not done yet is this part 
```
 Add a new section for creating a universe with K8s provider - deployment, connect pods, sample workload, Enable
IPv6 requirement, enable public network access 
```

The current docs at https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/ do not have k8s specific information. The plan is for @baba230896 to put together a Google Doc describing how the create universe flow works for kubernetes with focus on specific knobs like "enable ipv6", "enable public network access" that you could perhaps integrate into the existing flow (which is general for both VMs and kubernetes).

**Comment by lizayugabyte** [comment]
Kubernetes universe creation doc: https://docs.google.com/document/d/1coVLAOBlmO56bcyvSqdkLgy1uBpcGfUJ08HKBQZZoC8/edit#heading=h.l2hkcwny2dp

**Comment by lizayugabyte** [comment]
Linked to #8272
