### ISSUE TITLE
[Docs] Improvements for platform backup configs

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7681]
Source - https://docs.yugabyte.com/latest/yugabyte-platform/back-up-restore-universes/configure-backup-storage/

For all cloud providers add this information 
- Level of access control needed for an API Key, IAM role or any other credentials used 
- How to obtain credentials from a cloud provider: Link back to their docs or screenshot

**Comment by lizayugabyte** [comment]
@chirag-yb I added links for the 2nd ask.
WRT the 1st ask (Level of access control needed for an API Key, IAM role or any other credentials used) -- who would be able to provide this info?

**Comment by chirag-yb** [comment]
@VijiYB worked on Azure backup docs and testing all the components so she has a lot of expertise in this area to drive this initiative.

**Comment by lizayugabyte** [comment]
@VijiYB Could you, please, helm me with finding the following info:
_Level of access control needed for an API Key, IAM role or any other credentials used_

**Comment by VijiYB** [comment]
@lizayugabyte - Sure, will get back to you with more information

**Comment by lizayugabyte** [comment]
@VijiYB Hi Viji, could you, please, let me know when you are planning to look into this?

**Comment by VijiYB** [comment]
I have documented it here..
https://docs.google.com/document/d/1nixKZx2r_qk6KzT1Bw-G9GqJcbjYQ378QcP51vJ7xug/edit

**Comment by lizayugabyte** [comment]
Thanks, @VijiYB !
