### ISSUE TITLE
[Platform] Make SAS Token as optional while configuring Azure Backup

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7686]
If using SAS token for configuring azure backup, we can take backup only until the token is valid. The SAS token usually has a expiration date, so its better to make it optional (like toggle button). If the customer wants to use SAS token, they can still use it.

@WesleyW

**Comment by streddy-yb** [comment]
The right fix for this issue is to allow the user to update SAS token. See #7706 for more details.
