### ISSUE TITLE
[Platform] Custom SMTP Configuration API returns unmasked SMTP password

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#7698]
The value should be masked with asterisks.

**Comment by streddy-yb** [comment]
This might also require moving  _Custom SMTP Configuration_ into a separate tab in the UI to improve usability. cc @sshev

**Comment by VijiYB** [comment]
The password is not masked on 'Health Alerting UI". Able to clearly see the password on dev tools. @SergeyPotachev

**Comment by SergeyPotachev** [comment]
@VijiYB It was landed yesterday. Your build doesn't have the fix yet. Please wait for the next build.
