### ISSUE TITLE
[Platform] Ability to update expired SAS token without changing any backup config

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7706]
The platform does not allow editing the backup configuration. If the SAS token used to upload files to storage expires, the backup config has to be deleted and reconfigured. It would be useful to be able to edit the config without deleting it.

**Comment by adil246** [comment]
@tylarb

**Comment by adil246** [comment]
Another update: Besides updating the Azure backup configuration with the new SAS token, the user is also not able to delete the old backup configuration and add a new one.

**Comment by tylarb** [comment]
Second issue - delete old backup - can be resolved by adding multiple configurations. 

this specific issue is specifically - without changing any backup objects or locations, can we just update an expired SAS token.

**Comment by nishantSharma459** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/8050

**Comment by streddy-yb** [comment]
hi @nishantSharma459 - Can you back port this to both 2.4 and 2.6 branches asap? thanks
