### ISSUE TITLE
Document TABLESPACES in Explore Section

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7707]
Create a page explaining TABLESPACES feature in YSQL for Explore Section

@rkarthik007 / @m-iancu to add starter doc for this section

**Comment by m-iancu** [comment]
Started doc for YSQL tablespaces: https://docs.google.com/document/d/1l_1-Ugkxsfgb-flLwWExsxigVEiiLx97E5Z3eye2bK0/edit
