### ISSUE TITLE
[docdb] follower_lag_ms metric is aggregated for Prometheus as a SUM

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#7719]
The prometheus metric `follower_lag_ms` is an aggregate instead of an average -this means that high tserver count universes report a seemingly high replication lag, when they might be well within reason.

Metric comes from here:

```
./src/yb/consensus/raft_consensus.cc
 156 METRIC_DEFINE_lag(tablet, follower_lag_ms,
 157                   "Follower lag from leader",
 158                   "The amount of time since the last UpdateConsensus request from the "
 159                   "leader.");
 160 
...
 370       follower_last_update_time_ms_metric_(
 371           metric_entity->FindOrCreateAtomicMillisLag(&METRIC_follower_lag_ms)),
```

**Comment by tylarb** [comment]
@bmatican  which project / label should this be under?

**Comment by kmuthukk** [comment]
area/docdb

**Comment by bmatican** [comment]
@amitanandaiyer @nspiegelberg we currently have 2 modes in `src/yb/util/metrics.h`
- for `metric_type==cdc`, we do max (these are assumed to all be some lag type metrics)
- for all the rest, do sum

would it make sense to instead do some light refactor where we add a new attribute, next to `metric_type`, like `aggregation`, where, if not defined, we do the default sum, else, do w/e aggregation we support...and we can start with max for lag and tag all the CDC ones + this `follower_lag_ms` as such?

**Comment by bmatican** [comment]
I think we should be able to do something similar to e80ef644af805a9309029793d98fcea2440018d3
- introduce an enum for aggregation type (can start with the 2 ones we have already: SUM vs MAX)
- introduce a new field in metrics for tracking this agg type, default to SUM
- extend the macros for defining metrics to allow specifying an optional aggregation type

Then it should be pretty easy to tweak our current code & future proof:
- tweak the prometheus code to pick aggregation type based on the new field
- change existing CDC lag metrics to specify that they want MAX
- change this `follower_lag_ms` metric to also specify MAX

**Comment by tylarb** [comment]
May need 2.4 backport
