### ISSUE TITLE
K8s and Openshift cloud provider creation failing silently 

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7727]
Version - 2.7.1.0

Create a K8s or OpenShift Cloud provider without providing a kubeconfig for zones, click on save but nothing happens on the UI. From developer tools I can see {"error":"No Kubeconfig found for zone(s)"} with 400 status code. 

Need to improve the UX by providing visual feedback instead of failing it silently

**Comment by chirag-yb** [comment]
cc: @VijiYB could you verify?

**Comment by VijiYB** [comment]
Thats right, able to reproduce this. There should be mandatory fields, so the add region button enables only after all mandatory fields are entered, same way for the configuration page too.
