### ISSUE TITLE
Unable to delete OpenShift Cloud configuration

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7728]
Version 2.7.1.0

Unable to delete an OpenShift Cloud configuration which is not used at all. I noticed the Delete button is disabled when the cloud provider page is refreshed and enabled when I navigated from the universe to cloud config page.

**Comment by chirag-yb** [comment]
@bhavin192 can you check?

**Comment by VijiYB** [comment]
Thats right. If the cloud provider is refreshed "Delete configuration" got disabled and gets enabled when navigated from universe. Same behavior is observed in "Manage kubernetes service" tab too
