### ISSUE TITLE
Remove beta tag from Azure

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#7732]
For 2.7.x remove the beta tag for Azure cloud configuration

**Comment by chirag-yb** [comment]
This is for tracking only, no action item atm. Waiting for @VijiYB to confirm QA sign off before promoting to GA

**Comment by streddy-yb** [comment]
hi @sshev - Can you remove the Beta tag? thanks

**Comment by Arpit-yb** [comment]
**Tested in the following cases**

1. Edited the configuration(apart from provider UUID rest fields are editable)
2. Deleted the existing configuration
3. Created a new configuration
