### ISSUE TITLE
Promethues going down silently afer YW upgrade thru replicated

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7740]
Prometheus is going down after YW upgrade thru Replicated channel. Saw this in upgrade to 2.7.1 as well to 2.7.0
Hence I think backport to 2.7 is required @streddy-yb

**Comment by daniel-yb** [comment]
I updated the entrypoint from /bin/prometheus ... to /bin/sh -c <do something> && /bin/prometheus... for some HA stuff roughly a month ago. This results in the PID 1 being the shell and the prometheus process being a child process of the shell. Thus when replicated stops the prometheus container using a docker stop prometheus the prom process itself never receives the SIGTERM and after 10 seconds of waiting docker sends a SIGKILL to the container which results in prometheus not exiting cleanly and the lock file not being cleaned up.
