### ISSUE TITLE
PgAdmin DECLARE CURSOR

### ISSUE THREAD

**Issue by matrix2113** [yugabyte/yugabyte-db#7747]
Hey there, I'm trying to backup all our data from our kubernetes yugabyte cluster. I loaded up pgadmin and tried to backup the data and I'm running an issue with this here.

Any ideas?
```sql
pg_dump: error: query failed: ERROR:  DECLARE CURSOR not supported yet
LINE 1: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public...
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
pg_dump: error: query was: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public.data```

**Comment by ddorian** [comment]
@matrix2113 what version of YugabyteDB are you using ?

**Comment by matrix2113** [comment]
I'm using the v11.2

```bash
psql (PostgreSQL) 11.2-YB-2.1.6.0-b0
```

**Comment by ddorian** [comment]
Can you use https://docs.yugabyte.com/latest/manage/backup-restore/back-up-data/ or https://docs.yugabyte.com/latest/manage/backup-restore/snapshot-ysql/ for backups ?

We have fixed an issue with DECLARE CURSOR https://github.com/yugabyte/yugabyte-db/issues/3286 but it's not yet in a stable release.

**Comment by ddorian** [comment]
@matrix2113 also, you should upgrade the db because you're on a very old version.

**Comment by matrix2113** [comment]
Ah I see, thanks. I believe I've fixed the error.
