### ISSUE TITLE
[Docs/Explore] Add content for database CURSOR in YSQL

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7753]
Create a page explaining CURSOR support in YSQL for Explore Section.

The Yugabyte SQL (YSQL) API now supports the SQL CURSOR feature, which is a pointer with read-only access to the results of a SELECT statement. You can use this cursor to manage your results and process individual records as you traverse over the rows of a result set. The cursor allows applications to be more efficient by enabling retrieval of different rows from a result set at different times without the need to execute the query multiple times with various clauses such as OFFSET and LIMIT.

@m-iancu or @rkarthik007 can you provide an overview doc on this one

**Comment by m-iancu** [comment]
These are the relevant commits which have a good summary of what is supported:

1.Initial support:  https://github.com/yugabyte/yugabyte-db/commit/9d6639206510e9b6c0976f97a2289485b1a0fcb9
2.Extension to support FETCH NEXT/FORWARD:  https://github.com/yugabyte/yugabyte-db/commit/5f96f45dc21280bb2ab4c4551a899c77e11fc405
