### ISSUE TITLE
[docdb] Add a depth argument to the mem-trackers view

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7758]
Currently the MemTracker framwork allows us to track memory used across the database. It also allows for arbitrary depth of objects, as we flow the tracking deeper and deeper into various components.

We should add a simple http arg to the `/mem-trackers` UIs, to limit the rendering that we do, to strictly go down to the desired depth.

cc @kmuthukk

**Comment by yashrsharma44** [comment]
Hi @bmatican , I wanted to take this issue. Could you provide any pointers to get started with this? Or resources which I should refer before tackling this issue?
Thanks 😄

**Comment by bmatican** [comment]
Hey @yashrsharma44 , thanks for your interest in YB!

The UI for this utility will be on `IP:7000/mem-trackers` or `IP:9000/mem-trackers` (in the Utilities section of either the master or tserver UIs)

The code for that would be in `src/yb/server/default-path-handlers.cc`, in particular `MemTrackersHandler`. Note how we already have depth info, such as `data.depth`.

The easiest thing would be to add a URL param, which could describe max depth and not print anything beyond that. You can see examples of using url params even in the same file, such as `req.parsed_args.find("raw")`.

Hope that helps!
