### ISSUE TITLE
First draft of Django backend for YB 

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#7759]
Jira Link: [DB-1777](https://yugabyte.atlassian.net/browse/DB-1777)
Create a Django backend that can be used to run Django apps with YB as the database. Publish this backend to python repository so that it can be installed using `pip install `

**Comment by Sfurti-yb** [comment]
First draft of django backend for YB published. It can be installed from [here](https://github.com/yugabyte/yb-django). We will have to revert the savepoint changes made to the backend to account for the new savepoint support in YB version 2.9.0.
