### ISSUE TITLE
Django test suite issues with YB as backend

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#7760]
Jira Link: [DB-2557](https://yugabyte.atlassian.net/browse/DB-2557)
Currently Django test suite fails with YB as backend.  One of the issue that we encounter is because the way savepoints are implemented. The issues are reported here: 
https://code.djangoproject.com/ticket/28263
https://code.djangoproject.com/ticket/32527

However these issues are overcome by overriding the savepoint function in the Django backend for YB. 

The another issue is that the tests fail because the tests rely extensively on savepoints to do data validations. Django tests create savepoints before the start of test and do a rollback at the end. Since, savepoint is a no-op with YB backend, we see data mis match issues.  

Once savepoints are supported ( #4415) then we can start fixing the issues.

**Comment by kneeraj** [comment]
@Sfurti-yb please close the ticket as soon as we release the doc as we have tested the new savepoint feature does work with YugabyteDB

**Comment by Sfurti-yb** [comment]
On reverting the savepoint changes made to the Django backend for YB and re-running the test suite,  database shutdown issues were faced for some test modules. The issue is reported here:
