### ISSUE TITLE
Support type change from int to BigInt and numeric(m,n) to double precision

### ISSUE THREAD

**Issue by hbhanawat** [yugabyte/yugabyte-db#7762]
Jira Link: [DB-2109](https://yugabyte.atlassian.net/browse/DB-2109)
This type change is needed for Django DB migrations. For now, YB backend ignores these type changes. However, this may create an issue for the database and hence we need to fix this in YSQL layer.

**Comment by kneeraj** [comment]
@hbhanawat can you please elaborate this point more. Do you mean explicit cast does not work and it should work or something else?
