### ISSUE TITLE
Deleting duplicate instance from platform causes in use instance to also be removed

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#7769]
While doing tested i saw that if you have a duplicate row for the same ip in the managed instance pool (same ip, different instance type, region, or az). If you delete the row which shows the ip not being used it also removes the row which indicates the cluster where its being used. The only way to recover from this point is to completely wipe the cluster and re add the instances which were deleted into the pool. I see 2 options to fix this.

1. introduce a guardrail which does not allow the same ip to be used in multiple rows. Whether it be different instance type or different region/zone
2. Fix the delete path when removing instance types. This is where the actual bug is, which is that instead of just clearing the row for the duplicate instance its also removing the row which shows the node as in use.

**Comment by streddy-yb** [comment]
If we implement the ip uniqueness check (both in the UI and API), then we don't need to (2).

**Comment by VijiYB** [comment]
@yb-andrew @streddy-yb 
I'm able to add instance with duplicate IP, see the screenshot, I did not get any error.
<img width="2270" alt="Screen Shot 2021-04-23 at 10 10 52 AM" src="https://user-images.githubusercontent.com/78048211/115906612-97ef1600-a41c-11eb-9398-1220e2b7ec2c.png">

**Comment by streddy-yb** [comment]
Although the original issue is resolved (i.e, Deleting duplicate instance no longer deletes the original node), UI still allows adding new instances with duplicate IPs. Filed a new bug to track this issue.
