### ISSUE TITLE
[Docs] DBeaver Docs

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#7776]
[Content](https://docs.google.com/document/d/1kIH8X1QexOcbuW0uSndTaSvidJnNZbQqMQyYezeeVDY/edit#) for docs page.

[DBeaver docs page](https://docs.yugabyte.com/latest/tools/dbeaver/#configure-the-jdbc-driver).

**Comment by lizayugabyte** [comment]
@nchandrappa I'm not sure I understand the ask: 
Should this whole page https://docs.yugabyte.com/latest/tools/dbeaver/ be replaced with the content of the [Google doc](https://docs.google.com/document/d/1kIH8X1QexOcbuW0uSndTaSvidJnNZbQqMQyYezeeVDY/edit#) ?
