### ISSUE TITLE
[Platform] health check fails on k8s portal 

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7779]
Version - 2.7.1.0
Health check fails on k8s portal for all the universes on clock synchronization

FailedClock synchronization -  Error getting NTP state - incorrect answer format

**Comment by SergeyPotachev** [comment]
@streddy-yb 
There is no need to backport the fix to 2.7.0 as the initial issue #5946 was not backported to 2.7.0.
