### ISSUE TITLE
[YSQL] Feature Support  - CREATE STATISTICS statement

### ISSUE THREAD

**Issue by zjpedu** [yugabyte/yugabyte-db#7788]
Jira Link: [DB-2418](https://yugabyte.atlassian.net/browse/DB-2418)
# Feature Request
## Summary

In yugabyte,
```sql
yugabyte=# CREATE STATISTICS s1 (dependencies) ON a, b FROM t1;
ERROR:  CREATE STATISTICS not supported yet
LINE 1: CREATE STATISTICS s1 (dependencies) ON a, b FROM t1;
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
```

In postgres,

```sql
postgres=# CREATE STATISTICS s1 (dependencies) ON a, b FROM t1;
CREATE STATISTICS
```

**Comment by EthanDBer** [comment]
Has this issue been missed?

**Comment by ddorian** [comment]
@EthanDBer tracking, thanks

**Comment by ramsrivatsa** [comment]
CREATE STATISTICS command works with the following commit --> https://github.com/yugabyte/yugabyte-db/commit/05b70ff2a29d01c3976b8507ecefa2de1d5afe9c
