### ISSUE TITLE
Add option to forward rpcs from Pggate to the local Tserver.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#7794]
Each postgres process connects to all the Tservers in the cluster which
leads to a quadratic growth in the number of connections in the cluster.
To reduce the number of connections, we can forward all the rpcs to the
local Tserver which can then forward the rpc to the appropriate Tserver.

**Comment by psudheer21** [comment]
This change is useful for large clusters like our TPCC cluster with 60 nodes.
Each node in the cluster has about 200 connections inbound and given that it connects to all the 60 Tservers, the number of connections created in the system: 60 * 200 * 60 = 720k connections.

Instead of this if we have all the Postgres processes talk to the local Tserver and the Tserver forwarding the request to the proper Tserver we will have 60 * 200 * 1 = 12k connections.

**Comment by d-uspenskiy** [comment]
Local proxy to communicate with remote t-servers/masters was introduced in context of #9936
