### ISSUE TITLE
[Platform]- Platform support of GP3 (EBS) Disk

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#7799]
Description: 

 The customer required GP3  as an option for EBS in Yugaware UI during Cluster creation/update.
Version:2.1.11
Infrastructure: AWS
Running node:2

Problem solved:
GP3 is cheaper than GP2, so the customer would like to have that option in Yugaware UI, reducing the customer cost of AWS storage volume.

Reference ticket: 852

**Comment by anmalysh-yb** [comment]
@bmatican
Hi Bogdan.

As part of this ticket - I added support for AWS GP3 volumes during universe creation from Yugabyte Platfrom.
Currently we have disk size and IOPS configuration for GP3 drives, while throughput is not configurable - it's set to default value of 125MiB/sec.

According to this: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html

GP2 drives have throughput up to 250MiB/sec with the following dependency on disk size:

> The throughput limit is between 128 MiB/s and 250 MiB/s, depending on the volume size. Volumes smaller than or equal to 170 GiB deliver a maximum throughput of 128 MiB/s. Volumes larger than 170 GiB but smaller than 334 GiB deliver a maximum throughput of 250 MiB/s if burst credits are available. Volumes larger than or equal to 334 GiB deliver 250 MiB/s regardless of burst credits. 

GP3 drives have default throughput at 125 MiB/s with the ability to provision up to 1000 MiB/s, if drive has enough size and IOPS provisioned.

> General Purpose SSD (gp3) volumes offer cost-effective storage that is ideal for a broad range of workloads. These volumes deliver a consistent baseline rate of 3,000 IOPS and 125 MiB/s, included with the price of storage. You can provision additional IOPS (up to 16,000) and throughput (up to 1,000 MiB/s) for an additional cost.
The maximum ratio of provisioned IOPS to provisioned volume size is 500 IOPS per GiB. The maximum ratio of provisioned throughput to provisioned IOPS is .25 MiB/s per IOPS. The following volume configurations support provisioning either maximum IOPS or maximum throughput:
> 32 GiB or larger: 500 IOPS/GiB x 32 GiB = 16,000 IOPS
> 8 GiB or larger and 4,000 IOPS or higher: 4,000 IOPS x 0.25 MiB/s/IOPS = 1,000 MiB/s

Do you think, we should allow to provision additional throughput? I think we do, but wanted to understand, if it should be a separate field, which user can configure, or we can just calculate it ourselves based on configured IOPS (similar to what io1 volumes provide):

> Provisioned IOPS SSD volumes provisioned with up to 32,000 IOPS support a maximum I/O size of 256 KiB and yield as much as 500 MiB/s of throughput. With the I/O size at the maximum, peak throughput is reached at 2,000 IOPS. Volumes provisioned with more than 32,000 IOPS (up to the maximum of 64,000 IOPS) yield a linear increase in throughput at a rate of 16 KiB per provisioned IOPS. For example, a volume provisioned with 48,000 IOPS can support up to 750 MiB/s of throughput (16 KiB per provisioned IOPS x 48,000 provisioned IOPS = 750 MiB/s). To achieve the maximum throughput of 1,000 MiB/s, a volume must be provisioned with 64,000 IOPS (16 KiB per provisioned IOPS x 64,000 provisioned IOPS = 1,000 MiB/s).
