### ISSUE TITLE
[Platform] Health check emails not working with default SMTP configuration

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7810]
Seeing lot of alerts like below on 2.7.0 - ilegaArgumentException and SMTP alerts

1) Error running health check: java.lang.IllegalArgumentException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.ArrayList[0]->com.yugabyte.yw.common.HealthManager$ClusterInfo["tserverNodes"])

2) Error sending Health check email: Could not connect to SMTP host: email-smtp.us-west-2.amazonaws.com, port: 587

<img width="2543" alt="Screen Shot 2021-03-25 at 10 52 52 AM" src="https://user-images.githubusercontent.com/78048211/112520110-4fc6d000-8d58-11eb-9030-0e6b236150db.png">

**Comment by VijiYB** [comment]
Please note that I have not enabled SMTP on health alerts.

**Comment by SergeyPotachev** [comment]
Fixed under #7537.
