### ISSUE TITLE
[YSQL] YSQL dump should always include HASH/ASC/DESC modifier for indexes/pkey

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#7813]
Currently output assumes ASC is default but input assumes HASH is which can cause problems for backup restore.
I think the relevant code is here: https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/utils/adt/ruleutils.c#L1414

And also this might affect other output like `\d` too (which would be good so that we're consistent).

**Comment by OlegLoginov** [comment]
2 points:
1. Currently 'ASC' is a default property for the index column.
2. Currently a column without flags is a HASH-key column (current default),
```
yugabyte=# CREATE TABLE test(id int PRIMARY KEY, v int) SPLIT INTO 3 TABLETS;
yugabyte=# CREATE INDEX test_idx1 ON test (v HASH);
yugabyte=# CREATE INDEX test_idx2 ON test (v ASC);
yugabyte=# CREATE INDEX test_idx3 ON test (v DESC);
yugabyte=# CREATE INDEX test_idx4 ON test (v);

\yugabyte=# \d test
                Table "public.test"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 id     | integer |           | not null | 
 v      | integer |           |          | 
Indexes:
    "test_pkey" PRIMARY KEY, lsm (id HASH)
    "test_idx1" lsm (v HASH)
    "test_idx2" lsm (v)
    "test_idx3" lsm (v DESC)
    "test_idx4" lsm (v HASH)
```
