### ISSUE TITLE
[docdb] Add Clang thread safety annotations to catalog_entity_info

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7826]
Example we could protect pieces like `TableInfo::tablet_map_` with `GUARDED_BY(lock_)` and then annotate the respective read/write accessor methods like `TableInfo::AddTablet`

cc @mikhpolitov @rahuldesirazu

**Comment by jackstenglein** [comment]
Hello, I'd like to work on this issue, if it's still available?

**Comment by bmatican** [comment]
@jackstenglein definitely! this will be pretty similar to https://github.com/yugabyte/yugabyte-db/issues/7110#issuecomment-816306340, so note that you'd need to be able to build the code with TSAN (`yb_build.sh tsan`).

**Comment by jackstenglein** [comment]
@bmatican Hello, I submitted a pull request for this -- #8186. I'd really appreciate it if you could take a look. Thanks!
