### ISSUE TITLE
reduce memtable memory usage for environments with large number of tablets

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#783]
User reported issue:

**Background:** 

User was running a YugaByte 3-node dev cluster on machines with 8GB RAM. The cluster had about 30 tables and about 720 shards tablets per server. Once each table/tablet started having some data, they started seeing some errors of the form:

```
Rejecting consensus request: Soft memory limit exceeded (at 103.20% of capacity) [suppressed 384 similar messages]
```

The yb-tserver processes memory profile (obtained from `http://<ip>:9000/mem-trackers`) revealed that much of the memory was allocated to memtables.

The logical amount of data in each memtable wasn't necessary large, but the arena allocator was aggressively allocating large arena for each memtable.

**Current State:**

The total (global) logical amount of memory allocated to memtables is already controlled by two limits and when either of the two global limits is hit, we aggressively flush the memtables.
```
src/yb/tserver/ts_tablet_manager.cc:DEFINE_int64(global_memstore_size_percentage, 10,
src/yb/tserver/ts_tablet_manager.cc:DEFINE_int64(global_memstore_size_mb_max, 2048,
```

Also, there's also a per-memtable limit controlled by:
```
src/yb/rocksdb/util/options.cc:DEFINE_int32(memstore_size_mb, 128
```

However, the memory allocations for memtables are done using an arena allocator. And the size of each chunk in arena is calculated as `write_buffer_size/8`, where write_buffer_size = FLAGS_memstore_size_mb by default. So, for memstore_size_mb of 128, each arena is 16MB.

So even though on a 8GB machine, the logical amount of data in memtable doesn't get bigger than 800MB, when we have say 500 tablets, and even if each tablet has only one record in its memtable, we still end up using 500*16MB = 8GB, which is not ideal.

**Workaround**
For dev environments with large number of keyspaces/tables, on small memory machines, the memstore_size_mb can be set lower to 32 or 16mb.

**Possible Proposal for better defaults**

A simple short-term proposal would be to just have the arena size by a separate gflag (say `memstore_arena_size_kb`) defaulted to say 1024 (i.e. 1MB) coz there shouldn't be that much incremental advantage of allocating from arena in 16mb chunks vs. say 1MB chunks. So even for a node with 1000 very inactive tablets, the overhead will not exceed 1GB (1000 * 1MB)

**Testing Note**: Care should be exercised that we still support records that are larger than the arena size (e.g., we should make sure that a use case which is inserting/retrieving say a 4MB record is not affected).

**Comment by rahuldesirazu** [comment]
Fixed in 8da6b3f627bb5184d4f2e68a3427a6ca9ee2e681.
