### ISSUE TITLE
Settings for a 4 vCPU node

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#7842]
Jira Link: [DB-1925](https://yugabyte.atlassian.net/browse/DB-1925)
Here are some suggestions for setting defaults on `c5.xlarge` machines types (4 vCPU, 8GB RAM). 

### YB-Master
```
default_memory_limit_to_ram_ratio = 0.2
db_block_cache_size_percentage = 0.25
```

### YB-TServer
```
default_memory_limit_to_ram_ratio = 0.5
db_block_cache_size_percentage = 0.35
ysql_max_connections = 200
```

For reference, there was 1 EBS SSD disk of 250GB, workload was Hasura GraphQL. 

> **Note:** this takes into account the number of connections the app may need - and thus configures for 200 connections per node.

**Comment by chirag-yb** [comment]
Need similar tuning for a 2 vCPU node (AWS c5.large instances)
