### ISSUE TITLE
[doc]Document all pre-requisites for Replicated platform install

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7860]
A customer ran into multiple failure scenarios during the replicated installation of the Yugabyte platform on docker. It is necessary for the installation process to automatically check for hardware requirements, supported os versions, and other installation requirements before running the installation. Some of the checks are - Is it a supported OS and what version of the OS, is there sufficient space in the root file system and/or /var and /opt, etc? Replicated does some 'Pre-flight checks' after it has been installed but we need something before to  check the prereqs are met

Reference Ticket
Zendesk: https://yugabyte.zendesk.com/agent/tickets/986

**Comment by adil246** [comment]
@tylarb @datamgmt

**Comment by tylarb** [comment]
Let's convert this to a docs request - need to address these values (especially /opt and /var space, python requirement) as part of doc before we have a script even.

https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prerequisites/

**Comment by lizayugabyte** [comment]
@sridhar-yb Is there anyone in the Platform team who would be able to provide information on the additional platform installation prerequisites?

**Comment by lizayugabyte** [comment]
@tylarb Is there anyone who can provide this information to the doc team?

**Comment by tylarb** [comment]
@cigoldstein  @eugeneckim   @adil246   Can you help provide details here?

**Comment by lizayugabyte** [comment]
@cigoldstein @eugeneckim @adil246 Do you mind helping out with details?

**Comment by lizayugabyte** [comment]
@cigoldstein @eugeneckim @adil246 Do you mind helping out with details?

**Comment by lizayugabyte** [comment]
@tylarb @adil246 @cigoldstein @eugeneckim @nbhatia-yb  
It's been a year and a half since it was suggested to create a pre-flight check script for a Replicated YBA install. Has it been created? If not and the doc change is still required so the customers would know which steps to perform manually, please provide me the details.

**Comment by lizayugabyte** [comment]
CC: @polarweasel

**Comment by lizayugabyte** [comment]
@polarweasel The issue reporter is no longer here. Could you, please, decide what to do with this ticket?

**Comment by tylarb** [comment]
@lizayugabyte  ok to close this. We'll be moving towards replacing replicated all year.

Support team will handle this documentation and customer issues.
