### ISSUE TITLE
[docs] copy commands are broken in quick start

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#7865]
When doing Explore YSQL, if you tried to COPY each of the commands, its copying prompt prefix also in addition to the command like this

yugabyte=# CREATE DATABASE yb_demo;
yugabyte=# \c yb_demo;
yb_demo=# \i share/schema.sql;

yugabyte=# yugabyte=# CREATE DATABASE yb_demo;
ERROR:  syntax error at or near "yugabyte"
LINE 1: yugabyte=# CREATE DATABASE yb_demo;
        ^

https://docs.yugabyte.com/latest/quick-start/explore/ysql/

**Comment by zhaoalex** [comment]
Adding on to this, I'm pretty sure the schema .sql files in question have moved to `sample/` instead of `share/`

**Comment by rao-vasireddy** [comment]
It's not the file location. When you click copy, it is copying "yugabyte#" also, which is raising the error

**Comment by rao-vasireddy** [comment]
I see share dir in 2.4.1.1 and no sample dir.

**Comment by polarweasel** [comment]
> Adding on to this, I'm pretty sure the .sql files in question have moved to `sample/` instead of `share/`

@zhaoalex the actual build packages (i.e., what customers download from downloads.yugabyte.com when they're following the quick start) have a `share` directory.

**Comment by polarweasel** [comment]
Apparently this never got closed. Prompts haven't been copied in ages.
