### ISSUE TITLE
yb-admin list_snapshots payload size limited

### ISSUE THREAD

**Issue by pmb311** [yugabyte/yugabyte-db#7870]
Jira Link: [DB-2362](https://yugabyte.atlassian.net/browse/DB-2362)
There is a hardcoded limit that effectively gates rpc_max_message_size at the protobuf bytes limit.
  
`yb-admin -rpc_max_message_size 1500000000 list_snapshots`

`tcmalloc: large alloc 1256480768 bytes == 0x2bac000 @  0x7f8621f5c6d3 0x7f8621f7d09b 0x7f8629ae5e58 0x7f8629b63d28 0x7f8629aea522 0x7f8629b54cdc 0x7f8629b58a56 0x7f8629b595b6 0x7f8624d80b7b 0x7f8624d84c8a 0x7f8629b1587c 0x7f862639c3df 0x7f8620dcb694
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:193] A protocol message was rejected because it was too big (more than 535822336 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Error: IO error (yb/rpc/outbound_call.cc:423): Unable to list snapshots: Invalid response, missing fields`

**Comment by lingamsandeep** [comment]
After this commit - https://github.com/yugabyte/yugabyte-db/issues/13633, this issue should no longer happen.
