### ISSUE TITLE
Identify day of log messages

### ISSUE THREAD

**Issue by beatrausch** [yugabyte/yugabyte-db#7878]
Hi,
is there a change to get the unix timestamp or the day into log messages. Without its hard to identify logs from a certain day. 

Current:
````
I0330 11:40:32.225062    25 reactor.cc:450] Master_R003: DEBUG: Closing idle connection: Connection (0x0000000003b797b0) server 10.42.10.195:36622 => 10.42.10.195:7100 - it has been idle for 65.0001s
````

Expected:
````
I0330 07/07/2020 11:40:32.225062    25 reactor.cc:450] Master_R003: DEBUG: Closing idle connection: Connection (0x0000000003b797b0) server 10.42.10.195:36622 => 10.42.10.195:7100 - it has been idle for 65.0001s
````

**Comment by ddorian** [comment]
@beatrausch 

Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg 

The date + month is in there.

**Comment by beatrausch** [comment]
@ddorian 
Thx for clarification, it was not obvious to me. I guess [IWEF] stands for the related log level (info, warning, error, fatal)

**Comment by ddorian** [comment]
> I guess [IWEF] stands for the related log level (info, warning, error, fatal)

Yes.
