### ISSUE TITLE
Cluster aware driver for YSQL

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yugabyte-db#7880]
Jira Link: [DB-4871](https://yugabyte.atlassian.net/browse/DB-4871)
This issue tracks different tasks required for the Smart Driver for YSQL

| Done      | Task | Github Issue |
| ----------- | ----------- |----------- |
| ✅ | Connect to cluster in load balanced way  |https://github.com/yugabyte/yugabyte-db/issues/7879      |
| ⬜️ | Failover to another server on disconnect        |https://github.com/yugabyte/yugabyte-db/issues/7881      |
| ⬜️ | Data aware routing of sql statements        |https://github.com/yugabyte/yugabyte-db/issues/7882      |
| ⬜️ | Asynchronous execution for better scale        |https://github.com/yugabyte/yugabyte-db/issues/7883      |
 

 

[DB-4871]: https://yugabyte.atlassian.net/browse/DB-4871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ashetkar** [comment]
The three unchecked items will not be done.
Closing this ticket.
