### ISSUE TITLE
Backfill Index Throttling for YSQL

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#7889]

**Comment by jaki** [comment]
YCQL has

```cpp
  if (FLAGS_backfill_index_rate_rows_per_sec > 0) {
    auto duration_since_last_batch = MonoDelta(now - *last_flushed_at);
    auto expected_duration_ms = MonoDelta::FromMilliseconds(
        index_requests->size() * 1000 / FLAGS_backfill_index_rate_rows_per_sec);
    DVLOG(3) << "Duration since last batch " << duration_since_last_batch
             << " expected duration " << expected_duration_ms
             << " extra time so sleep: " << expected_duration_ms - duration_since_last_batch;
    if (duration_since_last_batch < expected_duration_ms) {
      SleepFor(expected_duration_ms - duration_since_last_batch);
    }
  }
```

This is not in the YSQL code path.  If YSQL wants throttling, either

- we push throttling logic down to postgres
- we wait for chunking support (issue #5326) and put throttling logic on tserver

Those are the two ideas that come to mind.

**Comment by tsmull-11** [comment]
Talking with Bogdan here are some examples of the cpu utilization of both the postgres and tserver processes. First picture is the cluster at steady state. 
![Screen Shot 2021-04-21 at 3 54 46 PM](https://user-images.githubusercontent.com/72473111/115639723-88fc4c80-a2d2-11eb-9175-76ca0a248731.png)

The second is the cluster doing an index backfill with num_concurrent_backfills_allowed set to 2.
![Screen Shot 2021-04-21 at 3 52 18 PM](https://user-images.githubusercontent.com/72473111/115639742-99acc280-a2d2-11eb-89ef-dacfef81f3ab.png)

The third is from when we ran the backfill with num_concurrent_backfills_allowed set to 1.
<img width="646" alt="Screen Shot 2021-04-21 at 5 57 15 PM" src="https://user-images.githubusercontent.com/72473111/115639798-bcd77200-a2d2-11eb-82db-d0e929bdebde.png">

The final screenshot is from the metrics page in YB platform of the 2 runs. Note the 2 runs were at 15:40 mark and 18:00 mark. The blip in the middle can be ignored. 
<img width="544" alt="Screen Shot 2021-04-21 at 6 59 31 PM" src="https://user-images.githubusercontent.com/72473111/115640329-ec3aae80-a2d3-11eb-8b57-5c11ef677729.png">
<img width="537" alt="Screen Shot 2021-04-21 at 6 59 40 PM" src="https://user-images.githubusercontent.com/72473111/115640335-ed6bdb80-a2d3-11eb-9845-6630d86733a2.png">
