### ISSUE TITLE
Is it possible to do geo partitioning like crdb? 

### ISSUE THREAD

**Issue by hiqbn** [yugabyte/yugabyte-db#790]
Possible to do geo partitioning like cockroachdb?
Geo-partitioning defined
Geo-partitioning grants developers row-level replication control. 
This allows you to keep customer data close to the user, which reduces the distance it needs to travel, thereby reducing latency and improving user experience. To geo-partition a table:

Define location-based partitions while creating a table.
Create location-specific zone configurations.
Apply the zone configurations to the corresponding partitions.

Is there a chat group for yugabyte online?

**Comment by kmuthukk** [comment]
hi @hiqbn :

This is the chat forum we are using:
https://gitter.im/YugaByte/Lobby

Obviously, we have to make finding this more easy to find.

I will respond in more detail on your main question soon.

**Comment by kmuthukk** [comment]
hi @hiqbn 

Currently, YugaByte DB doesn't have a row-level geo-replication feature where based on say the Primary Key of the row, you can pick a certain placement configuration. But this is on our roadmap, and we fully expect to add this at some point in the future.

regards,
Kannan

**Comment by tobiasmuehl** [comment]
Hi @hiqbn,

the chat moving over to Slack: https://yugabyte.com/slack

**Comment by azam** [comment]
@kmuthukk 
Hi,
This feature is the top reason for me to spend money on CRDB for my usage (a multitenant service platform). Would be glad to switch and to boast for YugaByte if you implement this as an OSS feature.

**Comment by gnanakeethan** [comment]
Is there any update on this?

**Comment by ndeodhar** [comment]
Hi @gnanakeethan This is on our roadmap and something that we plan to get to soon after our 2.0 release (which is in September).  It's likely that we'll start on this in the last quarter of this year. You can track progress here: https://github.com/YugaByte/yugabyte-db/issues/1958

**Comment by saulfrank** [comment]
Any update when we can expect to get this feature?

Would love to see this implemented. Closes a big gap between Mongodb geo sharding and Cockroach db geo partitioning... it also solves some pretty fundamental data compliance for GDPR purposes.

Cockroachdb implementation:
https://www.cockroachlabs.com/docs/v2.1/training/geo-partitioning.html

Mongodb implementation:
https://docs.mongodb.com/manual/tutorial/sharding-segmenting-data-by-location/

It is actually the only reason why I am interested in Yugabyte to use in our projects...

**Comment by rkarthik007** [comment]
Thanks for the information folks, we are starting to look at this feature - we are working on an initial design and figuring out timelines. Please stay tuned.

cc @ndeodhar @schoudhury

**Comment by rkarthik007** [comment]
Just an update that this feature is now available, please see here for more information:
* See the [blog post announcing geo-partitioning](https://blog.yugabyte.com/geo-partitioning-of-data-in-yugabytedb/)
* For how this works, see this [multi-region deployment comparison table](https://docs.yugabyte.com/latest/explore/multi-region-deployments/)
* More details [here](https://docs.yugabyte.com/latest/explore/multi-region-deployments/row-level-geo-partitioning/)

Please give it a go and let us know if you have any issues / feature requests (just open a new issue). Closing this one out for now.
