### ISSUE TITLE
[doc] Improvement: Add two diagrams to the Tablespaces document

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#7907]
Per Karthik, add two diagrams to tablespaces.md:
1. For single-zone tablespace creation -- use the diagram to explain how all copies are in one zone
2. For multi-zone tablespace creation -- use the diagram to explain how all copies are in 3 different zones with a diagram, along with how this can survive zone failures

**Comment by lizayugabyte** [comment]
Linked to https://github.com/yugabyte/yugabyte-db/issues/7962

**Comment by deeps1991** [comment]
Closing this as https://github.com/yugabyte/yugabyte-db/pull/8044 is merged now
