### ISSUE TITLE
Disable compactions until tablet bootstrap is done

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#792]

**Comment by kmuthukk** [comment]
@mbautin : Motivation? Guessing not needed for correctness, but as a best practice to bring back tablets online as quick as we can after a  process (yb-tserver) restart?

Let's tag the issue appropriately based on that (enhancement vs. bug for example).

**Comment by spolitov** [comment]
During compaction we are trying to cleanup intents, but until tablet bootstrap is done, we don't have all necessary environment for it.
I've added checks for this case, but it is possible that in future we will do some other things during compaction. Or those checks would not be full.
So it is better disable compactions to avoid such issues in future.
