### ISSUE TITLE
[Docs] Async Replication Deployment docs enhancements

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7947]
Rename this section to Async Replication in CoreDB > Deploy > Multi-DC Deployments > Async Replication
This page should have Yugabyte Core database instructions only and CLI commands to enable Unidirectional and BiDirectional replication.

https://docs.yugabyte.com/latest/deploy/multi-dc/2dc-deployment/

Move the Platform-specific instructions to the new section "Async Replication" in YB Platform docs under https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/ 

The content for this section will be starting from "If you're using Yugabyte Platform to manage universes" in https://docs.yugabyte.com/latest/deploy/multi-dc/2dc-deployment/#enable-universes-in-platform

**Comment by lizayugabyte** [comment]
@ameyb What priority is this ticket?
