### ISSUE TITLE
[Platform] EncryptionKeyModal is throwing error when fetch KMS configs fails

### ISSUE THREAD

**Issue by yb-andrew** [yugabyte/yugabyte-db#7950]
Navigating to a universe with KMS enabled will show this error due if something has been misconfigured. We should handle it gracefully.
```
EncryptionKeyModal.js:61 Uncaught (in promise) TypeError: Cannot read property 'map' of null
    at a.value (EncryptionKeyModal.js:61)
```

**Comment by sb-yb** [comment]
While we can fix it on server side to not fail on this; if we care to make UI resilient to such an error i found few more places in code where this happens. Will post details.

**Comment by sb-yb** [comment]
1. On Universe page 
### TypeError: Cannot read property 'length' of null
EncryptionKeyModal.componentDidMount
src/components/universes/SecurityModal/EncryptionKeyModal.js:14
```
  11 | export default class EncryptionKeyModal extends Component {
  12 |   componentDidMount() {
  13 |     const { configList, fetchKMSConfigList } = this.props;
> 14 |     if (!configList.data.length) {
  15 |       fetchKMSConfigList();
  16 |     }
  17 |   }
  ```
  
2.   On Universe -> Backups tab
###TypeError: Cannot read property 'map' of null
RestoreBackup.render
src/components/tables/RestoreBackup/RestoreBackup.js:115
```
  112 |   }
  113 | }
  114 | 
> 115 | const kmsConfigList = cloud.authConfig.data.map((config) => {
  116 |   const labelName = config.metadata.provider + ' - ' + config.metadata.name;
  117 |   return { value: config.metadata.configUUID, label: labelName };
  118 | });
  ```
