### ISSUE TITLE
[Platform] Disabling Node-to-Node TLS during universe creation causes universe creation to fail

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#7959]
Steps to reproduce:
1. Fill out create universe form
2. Disable Node to Node TLS
3. Submit the create request
4. Notice that universe creation fails with `Node-to-node TLS needs to be enabled for client-to-node TLS to be enabled` implying that although client to node TLS showed as disabled in the UI, the actual create universe payload request value was never updated to `false` for node to node TLS.
This bug seems to have been introduced in #7421

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7972
