### ISSUE TITLE
[doc] Add info on how to set up clusters to Explore > Tablespaces

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#7962]
Describe how to set up a cluster for single-zone and for multi-zone.

Also, slightly restructure this page so everything related to single-zone is in one subsection, and everything related to multi-zone is in another subsection

**Comment by lizayugabyte** [comment]
@deeps1991 Hi Deepthi, I was asked to describe how to set up a single-zone and multi-zone cluster. Since this information is not specific to Tablespaces, do you think we could just add links to relevant subsections in the following documents  (they all include info on how to create these clusters):

- https://docs.yugabyte.com/latest/deploy/kubernetes/single-zone/
- https://docs.yugabyte.com/latest/deploy/kubernetes/multi-zone/

In the meantime, I'll go ahead and restructure the doc according to Karthik's request.

**Comment by lizayugabyte** [comment]
@deeps1991 What should we do with this PR that hasn't been merged? https://github.com/yugabyte/yugabyte-db/pull/8001

**Comment by deeps1991** [comment]
Closing this as PR- 8044 is merged and has the information mentioned above.
