### ISSUE TITLE
[docdb] Report tablet disk usage to the master per drive

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7976]
As a stepping stone for #3167, we should first know how much data each tablet will bring, to assess if moving it to a new server would fill the disks or not.

**Comment by mikhpolitov** [comment]
https://github.com/yugabyte/yugabyte-db/commit/e03b7e227e102c36ed954a763b140d853ff829e4

**Comment by mikhpolitov** [comment]
Done as port of https://github.com/yugabyte/yugabyte-db/commit/e03b7e227e102c36ed954a763b140d853ff829e4
