### ISSUE TITLE
[YSQL] Transaction not commited after rollback

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#799]
In the following test case, YugaByte didn't report COMMIT and start a new transaction.
```
BEGIN;
    ROLLBACK;
END;
WARNING:  there is no transaction in progress
```
Correct behavior should be the following (Output from "psql" when running PosgreSQL).
```
BEGIN;
    ROLLBACK;
END;
WARNING:  there is no transaction in progress
COMMIT
```

**Comment by mbautin** [comment]
@nocaway were transactions enabled? (Currently controlled by the YB_PG_TRANSACTIONS_ENABLED environment variable, soon to be enabled by default.)

**Comment by nocaway** [comment]
@mbautin : Yes. 
YB_PG_TRANSACTIONS_ENABLED = 1

**Comment by ndeodhar** [comment]
This works correctly now.

```
yugabyte=# BEGIN;
BEGIN
yugabyte=#     ROLLBACK;
ROLLBACK
yugabyte=# END;
WARNING:  there is no transaction in progress
COMMIT
```
