### ISSUE TITLE
[docs] Troubleshooting page for per tablet overhead overheads in a YB cluster

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7997]
WIP

Memory
- `memstore_arena_size_kb` -- default 64kb, applies twice per tablet (regular vs intents rocksdb)
- `rocksdb_file_starting_buffer_size` -- default 8kb, applies twice per tablet (regular vs intents rocksdb)

CPU
- `raft_heartbeat_interval_ms` -- default 500ms

**Comment by ddorian** [comment]
Closing, this has been added in https://docs.yugabyte.com/preview/develop/best-practices-ysql/#tablets-per-server.
