### ISSUE TITLE
Implement CQL built in functions for uuid and timeuuid

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#80]
Support the following built-in functions:
- now(): generate a new unique timeuuid
- totimestamp(): convert a time uuid to the corresponding timestamp format
- tounixtimestamp(): convert time uuids and timestamps to a unix (epoch) time
- unixtimestampof(): convert time uuids to a unix timestamp which is equal to the number of milliseconds since epoch.

**Comment by ayushsengupta1991** [comment]
Committed as: https://github.com/YugaByte/yugabyte-db/commit/7fd621677ae55a21b6576e41e8f57f132cea371d
