### ISSUE TITLE
[YSQL] Create multiple test methods in TestPgRegress that run different subsets of yb_serial_schedule 

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#800]
TestPgRegress is too slow currently (more than 20 minutes). Tests in yb_serial_schedule can be naturally split by prefix. We need to create multiple test methods in TestPgRegress that call a common method that takes this test name prefix as a parameter and only runs test methods 

Separately, we need a safety net: we still need to check that every test name in yb_serial_schedule starts with one of the known test name prefixes, and if some of them don't, we fail the test. That will protect against silently not running tests that someone might add that don't have one of the known test prefixes.

**Comment by nocaway** [comment]
This work has been done by commit https://github.com/YugaByte/yugabyte-db/commit/b16f6baed6ee73a69c891d9a4040c27cc7d2d3ea
