### ISSUE TITLE
[Platform] Clean up `customer_task` table when tasks are completed

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#8014]
There can be leftover tasks in the `customer_tasks` table, where the corresponding entry in the `task_info` table has already completed with failure or success. These should be removed from the table, whether it be through taskGC or ensuring it is deleted when task completes.

**Comment by iSignal** [comment]
We thought this was behind the portal.dev hang but it turned out to be a different issue.
