### ISSUE TITLE
[Platform] Make `customer_task` lookup not load all subtask details

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#8016]
The `customer_task` table lookup needs to be more efficient. In `CustomerTaskController.fetchTasks`, we create an individual query on the `task_info` table for each entry in the `customer_task` table, but this should just be one query with a join:
```
    for (CustomerTask task : pendingTasks) {
      try {
        CustomerTaskFormData taskData = new CustomerTaskFormData();

        JsonNode taskProgress = commissioner.getStatus(task.getTaskUUID());
```

There may be other areas where this could be an issue as well, particularly with the `task_info` table.

The issue with loading all subtask details is that we are deserializing huge blobs of json (0.87 MB / task params for each subtask * number of subtasks). For large universes, this can cause us to run out of memory.

@sb-yb

**Comment by iSignal** [comment]
Additional bit of info: the reason we have task params that are 0.87 MB in size is that the entire Provider object is serialized as part of NodeTaskParams at https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/managed/src/main/java/com/yugabyte/yw/commissioner/tasks/params/NodeTaskParams.java#L46. This Provider db model object recently changed as part of https://github.com/yugabyte/yugabyte-db/commit/041b9e84d26c4909b97e2e7b1a1c75384e286b5d to include InstanceType data, which has a full list of all instance types and their prices, causing the task params to become 0.87 MB on disk. The deserialized JsonNode version of this in memory is likely much bigger - 10-25x.
