### ISSUE TITLE
Need better ways to handle when auth token got reset

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8020]
Got "Unable to authenticate user" when I clicked on Master/Tserver nodes on UI. After log out/in, able to go to the Master/Tserver nodes. When analyzed, Wesley found out that the auth token was reset when I was in the session which prevented me from logging to master/tserver nodes. Filing this issue to handle this situation in a proper way.

Wesley's comments: "Just that our auth token refresh needs to be smarter both in how it’s presented to the user (e.g. tell them the token has expired) and also in when it’s refreshed"

**Comment by adil246** [comment]
This issue is quite frequent when accessing Master/T-server UI. One another way to handle this is to redirect the user to sign in again.

**Comment by sshev** [comment]
UI app improvements have landed https://github.com/yugabyte/yugabyte-db/commit/7c7fe6b5957178bae01e54e2e46fbf891f8d1079 - added global interceptor to catch all 403-code responses and redirect to login page with a session expiration message in error toast. So when auth token expires background API calls won't fail silently anymore.

@daniel-yb pls fix proxy and logs download endpoints to redirect to `/login` when unauthorized as we discussed.
