### ISSUE TITLE
[docdb] Implement phased ramp-up of tablet splitting rate

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#8039]
The inherent tradeoff with number of shards per-table / per-node is roughly:
higher == better distribution of key-space
lower == less per-tablet overhead, fewer cross-shard transactions

During data-load of new tablets, we want to strike a particular balance between both ends of this trade-off using a phased ramp-up of the tablet splitting rate, roughly as follows (flag defaults are TBD):
1. If a table has less than `FLAGS_tablet_split_low_phase_shard_count_per_node` tablets, split any of its tablets that exceed `FLAGS_tablet_split_low_phase_size_threshold_bytes`
2. Else if a table has less than `FLAGS_tablet_split_high_phase_shard_count_per_node` tablets, split any of its tablets that exceed `FLAGS_tablet_split_high_phase_size_threshold_bytes`
3. Else, only split tablets whose size exceeds `FLAGS_tablet_force_split_threshold_bytes`

We should gate this behavior on `FLAGS_enable_automatic_tablet_splitting`, and we should now deprecate `FLAGS_tablet_split_limit_per_table` in favor of `FLAGS_tablet_split_high_phase_tablet_count_per_node`

**Comment by bmatican** [comment]
One other note I'd add @robertsami , is to also include a top-level switch to enable/disable automatic splitting completely, incase something goes wrong

that way we can
- play around with defaults internally, while only needing to flip the on/off switch
- easily disable it if things go wrong, by only tweaking one easy boolean flag (which we currently do by just setting the 1 threshold flag to 0)

**Comment by robertsami** [comment]
consider adding a `FLAGS_final_tablet_size_threshold` (e.g. = 30/50GB) to apply after the "final" phase
