### ISSUE TITLE
[Platform] Filter sensitive data from audit logs

### ISSUE THREAD

**Issue by skorobogatydmitry** [yugabyte/yugabyte-db#8051]

**Comment by skorobogatydmitry** [comment]
Now platform dumps audit events to `audit` table with payload that may contain sensitive data:
```
{api_call="/api/v1/customers/[REDACTED]/kms_configs/AWS", api_method="POST", customer_uuid="[REDACTED]", id="182", user_uuid="[REDACTED]"}  {"AWS_REGION":"us-west-2","AWS_ACCESS_KEY_ID":"[REDACTED - sensitive!]","AWS_SECRET_ACCESS_KEY":"[REDACTED - sensitive!]"}
```

It should remove this from the audit log payload using list of keyword keys like this: AWS_ACCESS*, AWS_SECRET*, GOOGLE_*. 

Related: #3790

**Comment by mahendranbhat** [comment]
@anmalysh-yb Please LMK once it checked in to master. Need to update `managed/src/main/java/com/yugabyte/yw/controllers/CustomerConfigController.java`

**Comment by anmalysh-yb** [comment]
@mahendranbhat Sure, will do. Also, if you merge first - just let me know and I'll update it in my diff as well.
Also, if your new audited request contains any sensitive data - let me know json path to it so I can add it to the list of redacted paths.

**Comment by anmalysh-yb** [comment]
@mahendranbhat Ticket is merged to master

**Comment by RP1807** [comment]
Validated this issue on the 2.6 portal. Verified that cloud secret, passwords are not exposed in audit log payload by connecting platform database. Verified this by configuring cloud providers, backup configs, etc, and checked that in the audit log no sensitive info exposed. 
cc @VijiYB
