### ISSUE TITLE
Add support for timezone

### ISSUE THREAD

**Issue by patrick-li** [YugaByte/yugabyte-db#806]
in `DateTime` types:
 `timezone_format ::= [ 'UTC' ] ( '+' | '-' ) digit [ digit ] ':' digit [ digit ]` ,  

can we add one more timezone `Z`? sth like `2019-01-26T00:03:16.059Z`. 
In Node js, date.toISOString() generates this format, which is ISO8601 supported/defined.

Thanks.

**Comment by kmuthukk** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/ea0ff795121ae5cb2edd07470b066a97577f62f8
