### ISSUE TITLE
Batching for multiple index backfills on the same table

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#8069]
Jira Link: [DB-5952](https://yugabyte.atlassian.net/browse/DB-5952)
pt 1: Based on a gflag.  Fail the whole batch upon failure of any index.
pt 2: failure handling on a per-index granularity.
pt 3: syntactic sugar to enable/disable this during create index for the specific table/indexes.

[DB-5952]: https://yugabyte.atlassian.net/browse/DB-5952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@amitanandaiyer , Any other follow ups for this task? If not, can we close this?

**Comment by amitanandaiyer** [comment]
This has landed for YCQL.
