### ISSUE TITLE
[YSQL] support uuid data type

### ISSUE THREAD

**Issue by unisqu** [YugaByte/yugabyte-db#807]
https://docs.yugabyte.com/latest/api/postgresql/#data-types

Data type is very limited compared with cockroachdb. It'll be a factor not converting.

Need UUID data type at least.

**Comment by hiqbn** [comment]
When will this be supported? Any roadmap on when? It's important and a show stopper if dont have uuid field type

**Comment by nocaway** [comment]
We are working on this issue, so the feature will be available when YugaByte release version 1.2 a few weeks from now.

Code on github should be available by end of this week.

**Comment by nocaway** [comment]
Support for UUID datatype has been added. by commit https://github.com/YugaByte/yugabyte-db/commit/835cc017161e9218a20670585a2cd0339fe316cf

**Comment by frozenspider** [comment]
Related issue: #711
