### ISSUE TITLE
[docdb] Master might skip deleting tablet data on tservers if the table was completely deleted

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8076]
Related to #8075, seems that if a table and all its tablets are in DELETED states, then if a TS wakes up and still has those tablets on disk, the master will not ask the TS to delete these tablets.

This could happen even in a normal cluster though
- create a table
- stop a tserver for more than the follower unavailability window (default 15m)
- after that, raft will kick out the peer from the quorum, but if it's shutdown, it won't delete them...
- the master might replicate the data back, if other tservers are available
- if we delete the table, we will send requests to all the good tservers to remove this tablet and ultimately update the  master state to DELETED
- now if we bring back this old tserver, it should report the now deleted tablets, but the master should hit this part of the heartbeat code, leading us to ignore instead of force delete these tablets!
> // 1a. Find the tablet, deleting/skipping it if it can't be found.

This should be easy enough to create a test for and validate.

**Comment by rahuldesirazu** [comment]
I tried these steps out and it looks like master logs is spewing `I0419 19:10:23.686399 124674048 cluster_balance.cc:286] Skipping load balancing for table foo as its placement information is not available yet` and the wal and sst data was never deleted on the down tserver.

**Comment by bmatican** [comment]
Oh interesting, this might be something new, related to the geo partitioning work?

Maybe when we refresh YSQL placement info, we don't filter down to only running tables? cc @deeps1991

**Comment by sanketkedia** [comment]
Few more observations:

1. After marking the table as DELETED and before the down TS is brought back again, the table seems to be still present in the table map but deleted from the tablet map. The load balancer keeps getting this table in the table map with the tablet count as 0.

> I0420 12:19:25.080554 159809536 catalog_manager.cc:3950] Successfully initiated deletion of table with table_id: "000030af000030008000000000004000"
> I0420 12:19:25.120874 164638720 catalog_manager.cc:4103] Marking table as DELETED: sanket_kv2 [id=000030af000030008000000000004000]
> I0420 12:19:25.143460 170541056 catalog_manager.cc:4184] Servicing IsDeleteTableDone request for table id 000030af000030008000000000004000: totally deleted
> 
> I0420 12:19:45.205394 161419264 cluster_balance.cc:276] (Sanket) table: 000030af000030008000000000004000, name: sanket_kv2

2. Consequently once the TS is brought up again, because the table is present in the table map the local state is updated.
```

      LOG(INFO) << "(Sanket) Found table and tablet for tablet id: " << tablet_id;
      // 1b. Found the tablet, update local state. If multiple tablets with the
      // same ID are in the report, all but the last one will be ignored.
      reports[tablet_id] = &report;
      tablet_infos[tablet_id] = tablet;
```

> I0420 12:23:10.959714 151224320 catalog_manager.cc:5155] (Sanket) Found table and tablet for tablet id: fbf7129a570b41f1828e7a305db1e201
> I0420 12:23:10.959738 151224320 catalog_manager.cc:5155] (Sanket) Found table and tablet for tablet id: 1eceb4dc89d24a38ab8174dfca109785

3. The CM sends delete tablet RPCs that error out with TABLET_NOT_RUNNING.

> I0420 12:23:10.961103 151224320 catalog_manager.cc:5232] Got report from deleted tablet 9b2bb51e2b304777a22008401ca3499b (table sanket_kv2 [id=000030af000030008000000000004000]) (Table deleted at 2021-04-20 12:19:25 PDT): Sending delete request for this tablet
> W0420 12:23:10.968603 163565568 async_rpc_tasks.cc:611] Delete Tablet RPC for 9b2bb51e2b304777a22008401ca3499b on TS=df66cd3fd35b456986a410531e44791a (task=0x11a595058, state=kRunning): TS df66cd3fd35b456986a410531e44791a: delete failed for tablet 9b2bb51e2b304777a22008401ca3499b with error code TABLET_NOT_RUNNING: Already present (yb/tserver/ts_tablet_manager.cc:1434): State transition of tablet 9b2bb51e2b304777a22008401ca3499b already in progress: {9b2bb51e2b304777a22008401ca3499b, opening tablet}

Because the table is present in the table map, LB keeps on spewing as Rahul observed even though practically it does nothing with the table as no tablets are found present for it. cc @bmatican @rahuldesirazu

**Comment by rahuldesirazu** [comment]
I remember I had some outstanding work from a year back that allowed a delete tablet RPC to take precedence over state transitions, but never got around to landing it... forget exactly why cc: @bmatican
