### ISSUE TITLE
[YSQL] Upgrade to PostgreSQL 11

### ISSUE THREAD

**Issue by robertpang** [YugaByte/yugabyte-db#808]
Currently, PostgreSQL support in YugaByte DB is based on PostgreSQL version 10.4. We want to upgrade YugaByte's codebase to [PostgreSQL 11](https://www.postgresql.org/about/news/1894/) to integrate exciting new features like:

- Transactions Supported in Stored Procedures
- Just-in-Time (JIT) Compilation for Expressions
- etc.

**Comment by robertpang** [comment]
Upgraded PostgreSQL code base to release 11.2 in commit [cb4bd4c](https://github.com/YugaByte/yugabyte-db/commit/cb4bd4c6490e7ed7921a6f241a4e2c6f841a4580).

**Comment by kmuthukk** [comment]
Excellent work @robertpang !

**Comment by rkarthik007** [comment]
This is awesome @robertpang!!
