### ISSUE TITLE
docdb: DROP TABLE with Dead Tserver Fails

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#8092]
When we try to drop a table when theres a dead tserver that has replicas for the table, drop table times out.  Repro:

1. Create an RF=3 cluster.
2. Create a table.
3. Stop one of the tservers.
4. Drop the table while the dead node is still in raft groups (<15 mins)

The observed error:

```
yugabyte=# drop table foo;
WARNING:  Timed out: Timed out waiting for Table Deletion
DROP TABLE
```

And when I try to drop the table again:

```
yugabyte=# drop table foo;
ERROR:  table "foo" does not exist
```

cc: @bmatican @nspiegelberg @sanketkedia

**Comment by sanketkedia** [comment]
Fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/46745199dfc718f0bdb6d100b4e56a624e003f0f)
