### ISSUE TITLE
[YSQL] Tablespaces must allow specifying leader affinity

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#8100]
Currently Tablespaces only allow creating placement info that allow specifying the number of replicas for a table and how these replicas should be distributed across cloud/region/zones. In addition to this, tablespaces must allow specifying leader affinity policies and read replica placement policies.

**Comment by bmatican** [comment]
Passing this to Hari as well. #11804 is one part of this, basically. We could follow-up then with read replica support as well.

**Comment by hari90** [comment]
Currently tablespaces inherit leader affinity from cluster config even if the placement policies are be different. Need to figure out what should be the expected behavior in such cases.

**Comment by hari90** [comment]
Split into two tasks https://github.com/yugabyte/yugabyte-db/issues/12180

**Comment by hari90** [comment]
#11804 is a dup
