### ISSUE TITLE
[Platform] Replicated install script fails on higher CentOS version

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#8113]
Yugaware docker based replicated install script fails when it doesn't find docker version _**19.03.8**_. This was observed on CentOS 8. The installation process works fine with the lower version of OS. 

It should skip the docker installation and continue with the replicated install if it finds a higher docker version installed but it doesn't. 

```
Metadata cache created.
INFO: Searching repository for VERSION '19.03.8'
INFO: yum list --showduplicates 'docker-ce' | grep '19.03.8.*el' | tail -1 | awk '{print $2}'

ERROR: '19.03.8' not found amongst yum list results

[centos@]$ docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
```

**Comment by tylarb** [comment]
Replicated doesn't support Centos/RHEL 8. So maybe an expected error. 

https://help.replicated.com/docs/native/customer-installations/supported-operating-systems/
