### ISSUE TITLE
[Docs] [API] add docs for split at values to CREATE INDEX

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#8125]
Update the reference docs for [CREATE INDEX](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_index/#grammar) to include SPLIT AT. This will be similar to what's available in [CREATE TABLE](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_table/#grammar).

**Comment by lizayugabyte** [comment]
SPLIT INTO is documented in https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_index/#split-into
