### ISSUE TITLE
[Jepsen] Clusters with replication-factor != master-replication-factor may work, but might also be illegal?

### ISSUE THREAD

**Issue by aphyr** [YugaByte/yugabyte-db#813]
When starting a cluster with 5 masters and the default replication factor of 3, all 5 masters will happily join one another, and cluster operations may proceed just fine. Sometimes, however, we see odd crashes and timeouts, and log messages like "catalog_manager.cc:6292] Expected replicas 3 but found 5 for tablet ...". We suspect that it may be illegal to start a cluster with a different number of master servers than the replication factor.

It's not entirely clear if this is intended to be illegal or not. @kmuthukk and @ttyusupov think this might be disallowed, and the documentation for cluster setup *does* say to run the same number of masters as --replication-factor.

On the other hand, `yb-master` has two CLI options for controlling the number of masters (and tserver masters, which I don't know about yet). They are:

```
    -master_replication_factor (Number of master replicas. By default it is
      detected based on master_addresses option, but could be specified
      explicitly together with passing one or more master service domain name
      and port through master_addresses for masters auto-discovery when running
      on Kubernetes.) type: uint64 default: 0
```

```
    -tserver_master_replication_factor (Number of master replicas. By default
      it is detected based on tserver_master_addrs option, but could be
      specified explicitly together with passing one or more master service
      domain name and port through tserver_master_addrs for masters
      auto-discovery when running on Kubernetes.) type: uint64 default: 0
```

This makes it look like maybe yb-master *does* support running with a different number of masters than --replication-factor. For that matter, --replication-factor's docs make it look like it's tunable on a per-table basis, which... I'm not sure. It's all sort of ambiguous.

If this state of affairs *is* illegal... YugaByte can detect this problem at CLI processing time: when the number of master server addresses is different than the replication factor, we can throw an error immediately.

**Comment by ttyusupov** [comment]
NOTE: We need also to look into the code logging this:
```
W0128 15:32:25.186554 16076 catalog_manager.cc:6292] Expected replicas 3 but found 5 for tablet 09cf3f6fedc24260b5f6af7e4b364758
```

**Comment by ndeodhar** [comment]
@aphyr Your configuration of 5 master nodes and 3-way replication for user data is valid and supported. Note that master_replication_factor in this case will be 5 while replication_factor will be 3.
The flags --master_replication_factor and --tserver_master_replication_factor were added for Kubernetes setup.

Regarding the errors that you are seeing:
1. Log error message is misleading (but harmless) - we'll fix that.
2. Regarding crashes and timeouts - we weren't able to reproduce that. It'll be helpful if you can provide more information on it: Were any nodes down when you saw the timeouts? Any stack trace available for the crash?
