### ISSUE TITLE
[Platform] Scheduled backups are running even when backups are disabled

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8140]
I scheduled some backups and I clicked on "disable backups" on Tables tab. But if you check the backups tab, you will still the scheduled backups are running but the status goes to unknown.

See in the screenshot: 
My scheduled backup ran on 5:32, I disabled the backup but still you can see there are 2 more backups ran with 5:42 and 5:52 which went to unknown state

**Comment by VijiYB** [comment]
<img width="2329" alt="Screen Shot 2021-04-22 at 5 58 50 PM" src="https://user-images.githubusercontent.com/78048211/115803014-d50fc580-a394-11eb-950a-4ca2d42c3ed5.png">
<img width="2341" alt="Screen Shot 2021-04-22 at 5 58 40 PM" src="https://user-images.githubusercontent.com/78048211/115803016-d7721f80-a394-11eb-832b-c459dedf3cbe.png">

**Comment by streddy-yb** [comment]
- Platform shouldn't schedule/run new backups when backups are disabled. This should be done asap.
- After #8296 is addressed, user should be given a choice to abort if a backup task is already in progress

**Comment by jaydeepkumara** [comment]
Looks like code changes are already there. No changes required.
