### ISSUE TITLE
[Platform] Backup & Table tabs improvement on backups

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8141]
@streddy-yb 

Since we are targeting on hardening backups, thought of listing down discrepancies that I see

1. Why do we have "Disable Backup" on Tables Tab. By disabling , it doesn't disable the backup rather when I tried to take a backup (from tables), it is going to "Unknown" status. But the Task shows successful. ==> #8139, #8140
2. If "Disable backup" is for scheduled backups, then in the backup tab , the scheduled backup should show that it is paused. 
3. May be we can change the name as "Disable scheduled backup"
4. Even though there are no scheduled backups, this button is enabled ==> for what? 
5. There is no correlation between backups tab and tables tab wrt backup. If there are scheduled backups running, then enable this "Disable backup" in tables or move this button to Backups tab

**Comment by chirag-yb** [comment]
Need a design doc before changing any functionality
