### ISSUE TITLE
Potential issue on crash after creating post-split tablets

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#8148]
Scenario:
1. TServer sends to leader master `split_key_1` + `tablet_id` to split.
2. `CatalogManager::DoSplitTablet` is called on master side
3. Child tablets are registered with partitions based on `split_key_1`.
4. Leader master crashes.
5. We have a new leader master.
6. TServer decides again that `tablet_id` requires split, but this time it calculates different `split_key_2` (it can happen if we have workload running and distribution of keys changes between step 1 and this step). 
7. `CatalogManager::DoSplitTablet` is called on master side with `split_key_2` + `tablet_id`.
8. `CatalogManager::DoSplitTablet` doesn't create new child tablets, because they are already created.
9. `CatalogManager::DoSplitTablet` still calls `SendSplitTabletRequest`, but passing encoded and partition keys for `split_key_2` instead of `split_key_1`.

Expected result: Child tablets partition key boundary should match the split key that is used by tserver to do the actual tablet split.
Actual result: Child tablets will have partition key boundary based on `split_key_1`, but tserver will do the actual split based on `split_key_2`.

**Comment by nimwijetunga** [comment]
Closed by commit: f9c8d2ff443c06d41074c7115b85d128779c4597
