### ISSUE TITLE
[YSQL] Support single-request optimization for UPDATE with RETURNING clause

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#8162]
Currently, in the general case, an UPDATE is executed internally as a read (to gather matching rows) plus some writes (update the appropriate rows).
Whenever possible, we push down the read+write to DocDB as one (UPDATE) request which targets the relevant row(s) (e.g. , a simple single-row update where the primary key is fully set in the where clause).
Currently a RETURNING clause disables this optimization as it requires an explicit read request -- but in principle the pushed-down update request can also return the read rows.
We should extend the current optimization to also handle the RETURNING clause.

**Comment by yifanguan** [comment]
Feature supported by the following commit -> 114641c.
