### ISSUE TITLE
[Platform] Ability to provide multiple backup locations for AWS provider

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#8166]
**Description**
Today, we can provide only a single S3 bucket location in AWS backup config provider. We want to be able to provide multiple backup locations for different backup scenarios, and preferably, the name of each backup if possible. Add ability to select different locations from the _**storage**_ drop down when using **_create backup_**.

**Ideas for implementation**
Some examples of the use-cases would be for different backup types such as Incremental, Full, etc created at different locations.

**Comment by tylarb** [comment]
related issue: #7706

**Comment by streddy-yb** [comment]
Dup of #7349, already planned for 2.7.x
