### ISSUE TITLE
[Platform] GCP universes are not having nproc set to 12000

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#8176]
When deploying universes in gcp we noticed that the max number of process was not getting set properly. The reason for this is that the platform is not updating the 20-nproc.conf file under /etc/security/limit.d which overrides anything in /etc/secruity/limits.conf. This will effect all universes deployed in GCP.

**Comment by ajcaldera1** [comment]
This is a DUP of #4985.

**Comment by ajcaldera1** [comment]
So I have learned that a `yum update` will make the /etc/security/limits.d/20-nproc.conf file reappear.

**Comment by RP1807** [comment]
Validated this issue on the 2.6 portal. Followed below steps 
1. Created single/multi-node cluster
2. SSH to node as centos user and checked `ulimit -u` should be 12000. 
3. changed user to yugabyte and ensure `ulimit -u` should be 12000. 
4. Rebooted one of the node and checked that ulimit still set to 12000. 

Tested this for GCP as well as AWS universes.
cc @VijiYB
