### ISSUE TITLE
follower_unavailable_considered_failed_sec not always honored

### ISSUE THREAD

**Issue by pmb311** [yugabyte/yugabyte-db#8177]
Jira Link: [DB-1484](https://yugabyte.atlassian.net/browse/DB-1484)
We observed a case where peer tservers expected a downed tserver to participate in elections long after follower_unavailable_considered_failed_sec had expired (we used the default value). For example here is a case where the tserver was down on the machine identified by UUID ca07911dc2b344e2a23d311658d4e9ed since ~22:10 UTC but another tserver still requested its vote.

    I0421 00:56:18.053745 23174 leader_election.cc:215] T 285745ddb058421c92881f42bb59dab3 P 
    164926ae138a40e28f0d83ea27dbb144 [CANDIDATE]: Term 454 pre-election: Requesting vote from peer ca07911dc2b344e2a23d311658d4e9ed
    I0421 00:56:18.053763 23174 leader_election.cc:215] T 285745ddb058421c92881f42bb59dab3 P 164926ae138a40e28f0d83ea27dbb144 [CANDIDATE]: Term 454 pre-election: Requesting vote from peer 132a178d80a64c32a8fcfb2eb7d29e16
    W0421 00:56:18.053916  9368 leader_election.cc:276] T 285745ddb058421c92881f42bb59dab3 P 164926ae138a40e28f0d83ea27dbb144 [CANDIDATE]: Term 454 pre-election: RPC error from VoteRequest() call to peer 
    ca07911dc2b344e2a23d311658d4e9ed: Network error (yb/util/net/socket.cc:537): recvmsg error: Connection refused (system error 111)

**Comment by rthallamko3** [comment]
@pmb311 , Is this issue still relevant?

**Comment by pmb311** [comment]
I'm not sure -- I changed jobs and have not worked on Yugabyte in ~1.5 years.

I'm sorry I could not be of more help.
