### ISSUE TITLE
Alerts failing because of Signature Version

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8180]
Seeing alerts for Signature Version as below. Need new set of credentials 

_Error sending Health check email: 535 Signature Version 2 is deprecated for use with SES from March 26, 2021. From that date on, we are progressively rejecting such requests. To resolve the issue, you must migrate to Signature Version 4. If you created your SMTP credentials in the SES Console, please create new credentials and replace the former ones. If you are deriving Signature Version 2 credentials from a IAM user, please start using the Signature Version 4 algorithm: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html_

**Comment by daniel-yb** [comment]
should take effect on all new builds regardless of branch as they're promoted through our release pipeline.
