### ISSUE TITLE
[Platform] Support timezone as a user preference

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#8208]
If a user logged in to the platform from a different time zone, other than UTC, they have to apply offset to understand the data such as logs/metrics. This could cause inconvenience and mistakes when viewing metrics.

**Comment by streddy-yb** [comment]
Platform already converts all timestamps to the Client (Browser) machine timezone. For example, if the user is in PST, then the timestamps are displayed in PST.  In other words, Platform is not displaying metrics in UTC. 

The main request is as follows: 
- Allow users to select the time zone when viewing metrics.
- Display/Label the timezone.

**Comment by dataindataout** [comment]
There is another user request for this feature on 2021-Sep-23.

**Comment by streddy-yb** [comment]
Display/Label the timezone support in available in 2.8.0.0 and 2.11.0.0 releases which are scheduled to go out soon. See 0c20e75d2 for more details. Allowing users to select a display timezone is targeted for 2.11.1.0. @SeanKimCC

**Comment by streddy-yb** [comment]
Ability for users to select timzone is implemented in 2.11.1.0 and has been backported to 2.8. 

3f00e8 | [PLAT-2295] Platform: Timezone Selector on user profile (Backend) 
1b1468 | [PLAT-2295] Platform: Timezone Selector on user profile (Backend) 
bb5747 | [PLAT-2296] Platform: Timezone Selector on user profile (UI) Summary: 

bce456 | [BACKPORT 2.8] [PLAT-2295] Platform: Timezone Selector on user profile (Backend) 
888b51 | [BACKPORT 2.8] [PLAT-2296] Platform: Timezone Selector on user profile (UI)
