### ISSUE TITLE
[Platform] Show full release version  in Platform UI and app_version API call

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#8219]
We show the full release version but not the build number. The full release version including the build number would be quite useful to understand which particular internal build is deployed on different portal servers.

There's two places the version is surfaced in Platform.

1. The footer of the Platform UI 
2. The API call /api/v1/app_version (which returns something like 2.4.1.0-b0 right now, with build number always 0)
![image](https://user-images.githubusercontent.com/8207010/116483514-15ab8b00-a83c-11eb-9ec3-1af250e24a81.png)

**Comment by iSignal** [comment]
Currently, db code uses a specific file called version_metadata.json to show the specific version. This file is maintained by the release process. See https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/src/yb/util/version_info.cc#L56

In Platform, the app_version API call uses a different file called version.txt https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/managed/src/main/resources/version.txt which is updated differently. We should switch this to use the same version_metadata.json file as above.

I'm not sure how the UI displays the version but it would ideally use that same app_version API call or version_metadata.json file.

**Comment by sunilsutarDCE** [comment]
UI use - "/api/v1/app_version" api to show version which returns - for e.g. {"version":"2.7.2.0-b0"} 
At UI skipping the part of version text after "-" , so the fix is from UI side .
