### ISSUE TITLE
Test : Tablet splitting fatal on TSTabletManager shutdown

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#8222]
Jira Link: [[DB-435]](https://yugabyte.atlassian.net/browse/DB-435)
```
F0428 18:54:38.743953  5772 operation_driver.cc:436] T d8c509be204e4c87bdf37a6ee217439a P a2acd554c2f64ce0b0abdd76bcdf4063 S RD-P Ts { days: 18745 time: 18:54:38.569793 } kSplit: Apply failed: Illegal state (yb/tserver/ts_tablet_manager.cc:932): Manager is not running: 2
```

`TSTabletManager::StartShutdown` switches it into `MANAGER_QUIESCING` state, but tablets are shut down later. So, if `SPLIT_OP` is being applying between these two events, `TSTabletManager::ApplyTabletSplit` will fail.

[DB-435]: https://yugabyte.atlassian.net/browse/DB-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
@ttyusupov good find, but note that this is a test only issue, as we don't use Shutdown in production yet

unless you think this would affect even tablet shutdowns? as those we might do as part of normal tablet deletion?

**Comment by rthallamko3** [comment]
Looks like a test only issue.

**Comment by rthallamko3** [comment]
@ttyusupov , Is this relevant even after [D19914](https://phabricator.dev.yugabyte.com/D19914) ?

**Comment by rthallamko3** [comment]
the scenario is unclear. We will open a new issue if we notice this.
