### ISSUE TITLE
[YSQL] Correctly handle table/index splits in backup-restore

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#8229]
When backing up a YSQL database we store both the (YSQL) metadata and the DocDB snapshots.
When restoring we re-create the YSQL objects, and then match the snapshots data for each to restore the actual data.
In that process we currently check that the number of splits of the YSQL objects (tables/indexes) re-created from the metadata match with those from the corresponding snapshot.
To avoid issues there, we added the `SPLIT INTO/AT` clause for ysql_dump which ensures the objects get re-created with the correct number of splits.
However that has a few exceptions. Known ones are:
-  unique constraints: represented as unique indexes which can be split into tablets, but does not have SPLIT clause syntax support.
- extensions: create extension can internally create objects (tables, indexes, unique constraints).

These can lead to mismatch between the tablet splits and therefore an error on restore. 

This can be fixed individually by adding splitting information to the YSQL dump (e.g. SPLIT INTO/AT syntax), or generically by inferring the number of splits from the snapshot itself.
For instance, when the number of splits does not match, we could re-create the objects with the _correct_ number of splits from the snapshot rather than erroring out.

**Comment by jaki** [comment]
Backed up a table with unique constraint.  Restored on a cluster with tserver flag `ysql_num_shards_per_tserver=1`, and got this error:

```
Error running import_snapshot: Invalid argument (yb/master/catalog_manager_ent.cc:1237): Unable to import snapshot meta file snapshot/test.snapshot: Found by id 000030af000030008000000000004003 PGSQL_TABLE_TYPE table 'abc_i_key' in namespace id 000030af000030008000000000000000 has number of tablets=1, expected=2: SNAPSHOT_FAILED (master error 23)
```

@OlegLoginov suggests not using syntax to solve this because it's not possible for CREATE EXTENSION (like, what if creating extension involves tables, some which have been dynamically split, some not?).

**Comment by jaki** [comment]
When trying to restore to a different database, I get a slightly different error:

```
Error running import_snapshot: Internal error (yb/master/catalog_manager_ent.cc:1370): Unable to import snapshot meta file snapshot/test.snapshot: Wrong number of tablets in created PGSQL_TABLE_TYPE table 'abc_i_key' in namespace id 00004005000030008000000000000000: 1 (expected 2): SNAPSHOT_FAILED (master error 23)
```

This is according to the two cases of `if (new_namespace_id == table_data->old_namespace_id)`.
