### ISSUE TITLE
Documentation bugs for Azure Backups

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#8244]
https://docs.yugabyte.com/latest/yugabyte-platform/back-up-restore-universes/configure-backup-storage/#microsoft-azure

Step 4 has two issues
1. "Navigate to the container > Shared access Signature." is incorrect. You should navigate to the Storage Account and then Shared Access Signature.
2. "Select 'Object' under 'Allowed Resource Types'." is incorrect. It should include both Object and Container.

With only Object, the backup will work but the restore fails. I found this explanation from MS:
https://docs.microsoft.com/en-us/answers/questions/105486/34azcopy-cp34-will-put-a-blob-but-34azcopy-list34.html

This is the error found in the application.log when only "Object" is used and a restore is performed:

===== RESPONSE ERROR (ServiceCode=AuthorizationResourceTypeMismatch) =====
Description=This request is not authorized to perform this operation using this resource type.
RequestId:cce74fe5-501e-003c-7e43-3d8130000000
Time:2021-04-29T22:02:20.9514627Z, Details:
Code: AuthorizationResourceTypeMismatch
GET -REDACTED-
User-Agent: [AzCopy/10.10.0 Azure-Storage/0.13 (go1.15; linux)]
X-Ms-Client-Request-Id: [e41bdec6-b3cb-46ee-5504-8f2cbb88e24c]
X-Ms-Version: [2019-12-12]

RESPONSE Status: 403 This request is not authorized to perform this operation using this resource type.
Content-Length: [284]
Content-Type: [application/xml]
Date: [Thu, 29 Apr 2021 22:02:20 GMT]
Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
X-Ms-Client-Request-Id: [e41bdec6-b3cb-46ee-5504-8f2cbb88e24c]
X-Ms-Error-Code: [AuthorizationResourceTypeMismatch]
X-Ms-Request-Id: [cce74fe5-501e-003c-7e43-3d8130000000]
X-Ms-Version: [2019-12-12]

Creating a SAS with both Container and Object resolved the issue.

**Comment by VijiYB** [comment]
Thanks Jon.

@polarweasel  Alex - Can you make these changes?
1. Navigate to the container > Shared access Signature." is incorrect. You should navigate to the Storage Account and then Shared Access Signature.
2. "Select 'Object' under 'Allowed Resource Types'." is incorrect. It should include both Object and Container.
3. Use this screenshot attached ==> which shows the selection of both Object and Container
<img width="1488" alt="Screen Shot 2021-05-10 at 1 54 19 PM" src="https://user-images.githubusercontent.com/78048211/117724017-03b0dd00-b198-11eb-9712-9768e1b9c822.png">
