### ISSUE TITLE
[Platform][API] Make consistent names for EncryptionAtRest request fields

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#8246]
This requires UI side changes.

So there is one place where we expect frontend to send field named "type" for encryption key type. And there is another place where we expect "key_type" ... same discrepancy  about "kmsConfigUUID" vs "configUUID". Not to mention that field names in java object do not match. I was hoping that at least UI would be consistent about these names.
UI is actually using different names for these fields at different places and hence in backend we are mapping these different names.

In UniverseController:
```
      if (config.get("configUUID") != null) {
        encryptionConfig.kmsConfigUUID = UUID.fromString(config.get("configUUID").asText());

        if (config.get("type") != null) {
          encryptionConfig.type = Enum.valueOf(KeyType.class, config.get("type").asText());
        }

        if (config.get("key_op") != null) {
          encryptionConfig.opType = Enum.valueOf(OpType.class, config.get("key_op").asText());
        }
```        

EncryptionAtRestKeyParams.java:
```
        if (formData.get("kmsConfigUUID") != null) {
            params.encryptionAtRestConfig.kmsConfigUUID =
                    UUID.fromString(formData.get("kmsConfigUUID").asText());
            if (formData.get("key_type") != null) {
                params.encryptionAtRestConfig.type =
                        Enum.valueOf(KeyType.class, formData.get("key_type").asText());
            }
            if (formData.get("key_op") != null) {
                params.encryptionAtRestConfig.opType =
                        opTypeFromString(formData.get("key_op").asText());
            }
```

Note "type" vs. "key_type" and "configUUID" vs "kmsConfigUUID"
Also note that "key_op" is differnt from the java field name opType.

End goal:
Make all these same and they should match the current Java POJO field names as used in EncryptionAtRestConfig.java

**Comment by kkg-yb** [comment]
Lower priority as there a fix being put in the backend by Mahendra
