### ISSUE TITLE
Creating Index in an invalid tablespace causes creation of all future valid tables/indexes to fail.

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#8251]
Jira Link: [DB-715](https://yugabyte.atlassian.net/browse/DB-715)
Steps to reproduce:

1. Create a tablespace specifying a placement policy that is invalid (ex: cloud/region/zone names misspelled)
2. Create a table
3. Create an index for the table and associate it with the tablespace created in Step (1). This essentially tells DocDB to place the tablets of the table in cloud.region.zone that doesn’t even exist in the cluster
4. This step times out after a really long time with the message “Invalid Table Definition”
At this point YB-Master gets stuck trying to place this invalid index. This causes creation of tables/indexes after this step to fail, because the task that tries to assign tablets to TServers aborts itself every time it encounters the tablets of the index created in (3) that it's not able to place.
This does not happen when tables are created in an invalid tablespace, because the DDL Transaction GC kicks in and deletes the table. This does not happen for indexes.

To reproduce using ./yb-ctl:
```
yugabyte=# CREATE TABLESPACE testtbs WITH (replica_placement='{"num_replicas": 1, "placement_blocks":[{"cloud":"aws","region":"us-east-1","zone":"us-east-1b","min_num_replicas":1}]}');
CREATE TABLESPACE
yugabyte=# CREATE TABLE testtable (id INTEGER);
CREATE TABLE
yugabyte=# CREATE INDEX idx ON testtable(id) TABLESPACE testtbs;   // Expected to fail
ERROR:  Invalid argument: Invalid table definition: Timed out waiting for Table Creation
yugabyte=# CREATE TABLE testtable2 (id INTEGER);                                // Not expected to fail!!
ERROR:  Invalid argument: Invalid table definition: Timed out waiting for Table Creation
```

**Comment by nspiegelberg** [comment]
When CREATE INDEX is issued, 
1. A new table 'idx' is created.
2. An Alter operation on 'testtable' is issued.

We do not currently employ transactional DDL in this use case because it does not handle ALTER operations.  Trying to understand why the stuck ALTER is causing new table requests to fail.  Setting `FLAGS_enable_transactional_ddl_gc=false` disables the GC feature but shows the same problem.
