### ISSUE TITLE
[Platform] Universe overview page not rendering after deleting read replica

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8253]
Universe overview page not rendering after deleting the read replicas that failed during configuration

Steps followed:
1. Create a universe
2. Add read replicas in such a way that the configuration fails (in this case the instance type selected c4.large) is not available in one of the AZs ==> so create read replica cluster failed
3. Delete the read replica

**Comment by VijiYB** [comment]
@yb-andrew 's initial investigation comments:

Looks like the node details set in the universe metadata is referencing the non-existant read-replica cluster that got deleted. The root cause seems to be DeleteClusterFromUniverse.java not deleting the nodes from the nodeDetailsSet. Please see this updater function:
public void run(Universe universe) {
  UniverseDefinitionTaskParams universeDetails = universe.getUniverseDetails();
  universeDetails.deleteCluster(taskParams().clusterUUID);
  universe.setUniverseDetails(universeDetails);
}

**Comment by RP1807** [comment]
Validated this issue on 2.6.0.0-b25. 

1. Create a universe with the read replica configured and verify that universe overview page is rendered properly. 
2. Add/Delete read replica in a universe and ensure the universe overview page is accessible. 
3. Add/Delete read replica in a universe such that read replica configuration fails. Ensure the universe overview page is accessible.
4. Create a universe with read replica such that universe creation fails. Delete read replica nodes and ensure the universe overview page is working fine. 

cc @VijiYB
