### ISSUE TITLE
[docdb] Splitting: Disable automatic splitting for YEDIS tables

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8255]
After we have #8234, it should be very easy to expand the set of constraints on what to enable/disable splitting on.

In particular, to minimize the testing surface, we should disable it for YEDIS tables completely.

**Comment by robertsami** [comment]
fixed by https://github.com/yugabyte/yugabyte-db/commit/de79792541491cd32994bc111b46b8dcd7eec447

(note that commit has wrong issue number tag)
