### ISSUE TITLE
PITR: Load balance for hidden dropped tables

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8267]
As a followup to #7133, we should ensure that the LB actually operates on hidden tables.

By default, the LB will ignore tables not in RUNNING state. So the new hidden mode for DELETED tables needs to be explicitly wired into the LB.

cc @sanketkedia

**Comment by sanketkedia** [comment]
Verified that the LB works on the dropped HIDDEN tables.
