### ISSUE TITLE
Ignore undefined Gflags 

### ISSUE THREAD

**Issue by WesleyW** [YugaByte/yugabyte-db#827]
Currently, passing in undefined gflags will cause problems when creating clusters. An --undefok flag should be set to ignore them.

**Comment by swayamraina** [comment]
Hi @WesleyW,
**gflags** has **--undefok** flag for suppressing the errors. Since we are falling back to the **google::HandleCommandLineHelpFlags() [flags.cc]**, using **undefok** should work without any change required.

**Comment by WesleyW** [comment]
Hey @swayamraina, you're right about the `undefok` flag. I believe the original intent was to automatically ignore gflags that are incorrect without having to pass in an additional gflag. This can obviously lead to undesirable outcomes, so I'm going to close this issue.
