### ISSUE TITLE
Consider using -bXXX formating for the release.

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#8270]
The builds in YW seem to be sorted alphebetically. So,  b2 sorts before b15. Consider using a fixed-width build number like 3-digits XXX or xxxx

**Comment by streddy-yb** [comment]
Hi @amitanandaiyer -  Trying to understand your use case. Are you referring to the sort order in `/releases` page in YW -or- in general?  Changing the version formatting for the existing branches will be hard.

**Comment by amitanandaiyer** [comment]
Looks like we already have a good ordering for default releases.

it seems more like a user error that we picked a custom build instead of the official build, which showed up lower.

**Comment by amitanandaiyer** [comment]
This was for the create universe flow.
