### ISSUE TITLE
[Docs] Document steps for creating a universe with K8s and OpenShfit Cloud Provider

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#8272]
Content - https://docs.google.com/document/d/1coVLAOBlmO56bcyvSqdkLgy1uBpcGfUJ08HKBQZZoC8/edit#heading=h.kjc0ftlw6cqr

The current https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/ documentation is VM specific which is missing steps, flags and configurations for K8s cloud provider

**Comment by lizayugabyte** [comment]
Linked to #7680 7680
