### ISSUE TITLE
[Platform] Ability to stop backup process via admin console

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#8296]
When running long backups which might take minutes to hours, it would be handy to be to able to stop backup processes via admin console. _yb_backup.py_ script has to be stopped by logging in to the platform server, if it process has to be stopped for some reason such as long running backup, conflicts with another process, high resource consumption, etc.

![InProcess](https://user-images.githubusercontent.com/78443978/117147216-a6bdbd00-ad7a-11eb-85f4-bab51ee1aebc.png)

**Problem solved**
Backups can be stopped from the console gracefully.

**Ideas for implementation**
Stop process could be enabled as a part of Action drop down.
Stop process gracefully when stopped using console. 
Update the backup state to '_stopped_' or '_deleted_' in platform yugaware database.
```
yugaware=# select state, update_time from backup;
    state    |       update_time       
-------------+-------------------------
 Deleted     | 2021-05-05 12:51:42.707
 Deleted     | 2021-05-05 12:52:05.092
```

**Comment by mahendranbhat** [comment]
https://docs.google.com/document/d/10R1B5zBWYbowlY7yxTtkL4bIwynTQEZoRF-aiJDkSu4/edit design doc
