### ISSUE TITLE
Fix the download url for Replicated airgap bundle in Platform docs

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#8311]
Change the replicated download URL in `https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped/#install-replicated` from  `https://downloads.yugabyte.com/replicated.tar.gz `to 
`https://s3.amazonaws.com/replicated-airgap-work/replicated.tar.gz`

**Comment by polarweasel** [comment]
Can we use one of Replicated's own URLs instead of pointing to their s3 bucket?

```sh
$ curl -I https://get.replicated.com/airgap
HTTP/2 302 
   [...]
location: https://s3.amazonaws.com/replicated-airgap-work/replicated.tar.gz
```

**Comment by ddhodge** [comment]
The download for Yugaware is https://downloads.yugabyte.com/yugaware-2.1.2.0-b10.airgap, should that also be updated?

**Comment by polarweasel** [comment]
This `wget` command will work to get past the redirect and naming problem. I can't get `curl` to do it right so far.

```sh
wget --trust-server-names https://get.replicated.com/airgap
```
