### ISSUE TITLE
[xCluster] Replication fails with 'Error: Network error (yb/util/net/socket.cc:535): Unable to alter replication for universe XXXXX: recvmsg got EOF from remote (system error 108)'

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8325]
Jira Link: [DB-2232](https://yugabyte.atlassian.net/browse/DB-2232)
**Issue**
When the `Master Leader` is on a node, that is not is the `masterAddrs` under the `producerMap`, any `alter_universe_replication` command failed with the following error message: 

```
[yugabyte@yb-dev-zd-1197-primary-n4 bin]$ ./yb-admin --master_addresses 10.204.0.7,10.204.0.8,10.204.0.9 alter_universe_replication fa98841d-6609-4e11-8d50-055befa9b535 add_table 5cfce69350ca4ae2a0f159634b472985
Error: Network error (yb/util/net/socket.cc:535): Unable to alter replication for universe fa98841d-6609-4e11-8d50-055befa9b535: recvmsg got EOF from remote (system error 108)
```

**Steps to reproduce** 
1. Setup xCluster replication 
2. From the Yugaware platform UI, stop all services on the `MasterLeader`/`Tserver` node 
3. Start the `Master` process on a `TServer` node
4. From the CLI - issue, change the master - where the new `masterLeader` is the node that was only a `tserver` prior. 
```
yb-admin -master_addresses <master-addresses> master_leader_stepdown [ <new_leader_id> ]
``` 
5. Attempt to add bidirectional-replication for a new table 
```
yb-admin master_addresses <master-addresses> alter_universe_replication <producer_universe_uuid> { set_master_addresses <producer_master_addresses> |  add_table <table_id>[, <table_id>...] | remove_table <table_id>[, <table_id>...] }
```

**Request**
Platform needs to update map when master leader changes 

Please see reference ticket: [1197](https://yugabyte.zendesk.com/agent/tickets/1197)

**Comment by CharlotteRose** [comment]
This is manifesting still in more frequent cases with customers - please see github issue [8722](https://github.com/yugabyte/yugabyte-db/issues/8772) for additional information and core dump

**Comment by hsiaosu-yb** [comment]
cc @daniel-yb @ymahajan

**Comment by daniel-yb** [comment]
@hsiaosu-yb un-assigning Atharva as this is more of a DB layer change. @rahuldesirazu do you know who would be best to tackle this?

**Comment by hsiaosu-yb** [comment]
For this one, we need to wait for the DB layer change to happen, the decide what needs to be done in platform's UI.

**Comment by polarweasel** [comment]
@daniel-yb have you gotten anywhere on this one? Wondering if we should close this ticket as the docs and UIs will get updated as xCluster work gets finished.

**Comment by rthallamko3** [comment]
@lingamsandeep, Can you tag the relevant xcluster items.
