### ISSUE TITLE
[YSQL] Insert fails with "Conflicts with higher priority transaction"

### ISSUE THREAD

**Issue by ravimurthy** [yugabyte/yugabyte-db#833]
With the following sequence of operations, the insert statement on session1 fails with "Conflicts with higher priority transaction" error. The error message should be simpler to indicate transaction conflict.

===
SETUP
postgres=# create table test (a int primary key, b int);
CREATE TABLE

===
SESSION1

postgres=# begin;
BEGIN

===
SESSION2

postgres=# begin;
BEGIN
postgres=# insert into test values (9, 11);
INSERT 0 1

====
SESSION1

postgres=# insert into test values (9, 12);
ERROR:  Operation failed. Try again.: Failed Write(tablet: 26299bee8d534500a3ac626c33f2c299, num_ops: 1, num_attempts: 1, txn: 4831c8e1-9f81-4dc1-9660-6ea6c18be86b) to tablet 26299bee8d534500a3ac626c33f2c299 on tablet server { uuid: 5415d898338c42438c238d2673054ee3 private: [host: "127.0.0.1" port: 9100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 1 attempt(s): Conflicts with higher priority transaction: 6d3de940-f19e-4cc6-a3b7-6d5ec80cdd3e

**Comment by m-iancu** [comment]
The error message has been simplified.
It is now more concise:
```
ERROR:  Operation failed. Try again.: 991a9f3c-0d72-4e25-9918-4ef18a026490 Conflicts with higher priority transaction: 4bdc2992-2a30-4799-bb4b-8950b5b368d7
```
The transaction-conflict error messages are documented in a separate issue: https://github.com/yugabyte/yugabyte-db/issues/3587
