### ISSUE TITLE
[docs] Document Spring Data YB in Ecosystem

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#8339]
Under Ecosystem > Dev frameworks
Base (contains architecture doc): https://github.com/yugabyte/yugabyte-db/issues/7956
Nikhil will provide starter doc

**Comment by lizayugabyte** [comment]
I messaged this to Nikhil: I've started documenting SDYB based on specs in https://github.com/yugabyte/yugabyte-db/issues/7956. I'm wondering if you are planning to create a doc with some usage scenarios and samples? Because I'm having a hard time extracting info that could be used in a customer-facing doc.
Nikhil response:
Yes, I’ll work on providing an example and doc for Spring Data YugabyteDB project. We’ll need to update the following Spring Data YugabyteDB doc page -https://docs.yugabyte.com/latest/integrations/spring/ . 
Also we’ll need to update this page -  https://docs.yugabyte.com/latest/reference/drivers/spring-data-yugabytedb/  or completely remove it since we will move the content under Integrations.
I’ll provide you the content this week or latest by next week.

**Comment by lizayugabyte** [comment]
Nikhil on July 19th:
Yes, I’ll work on providing an example and doc for Spring Data YugabyteDB project. We’ll need to update the following Spring Data YugabyteDB doc page -https://docs.yugabyte.com/latest/integrations/spring/. ALso we’ll need to update this page -  https://docs.yugabyte.com/latest/reference/drivers/spring-data-yugabytedb/  or completely remove it since we will move the content under Integrations. (edited) 
4:52
I’ll provide you the content this week or latest by next week.

**Comment by nchandrappa** [comment]
@lizayugabyte Content for [Spring Data YugabyteDB Docs](https://docs.google.com/document/d/1CX64aLjINDlYlhZO7RptLCX1NsGY6xEVQrhVgIbmPyk/edit#) page.
