### ISSUE TITLE
build: handle untracked files in postgres build

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#8352]
For postgres, we first rsync source files to `build/latest/postgres_build`, and then we run postgres make (see `python/yb/build_postgres.py`).  Building postgres is costly, so we use a "build stamp" to determine if source files have changed and, if not, don't build postgres.

The build stamp takes into account

- commit hash
- tracked files diff
- env vars

It misses untracked files.  I, and others, have come across this when working on regress tests.  Sometimes, one creates new regress test files and/or regress schedules.  If you don't commit the changes or track them (e.g. using `git add --intent-to-add`), changes to these files won't be noticed by the build process because the build stamp is unaffected.

This issue hasn't really surfaced for source files because they are usually accompanied by changes on tracked files (for example, adding an `#include "foo.h"` line or a `bar.o` Makefile item).

There are several ways around this.

1. Always run rsync and use build stamp to determine whether to run postgres build.  This will fix most cases, and it's likely a strict improvement since rsync doesn't take long.  Probably the only case this misses is an update to an untracked `.c` file that doesn't cause postgres build.
1. Always run rsync and, if there's any change detected through it, run postgres build.  This may run build unnecessarily because you might, say, have a `notes.txt` or `convenient_commands.sql` that you update frequently.
1. Do checks on untracked files matching certain patterns.  This is a best-effort approach and not meant to cover all cases, but it can be handy for common ones like `*_schedule`, `sql/*.sql`, `expected/*.out`, `*.c`, `*.h`.
1. Make information on how this works more easy to come by.  Perhaps add it to the `README` in `src/postgres/src/test/regress`.

I will likely go with the first approach unless there are other thoughts.

cc: @mbautin

**Comment by mbautin** [comment]
I am fine with going with the first approach.
