### ISSUE TITLE
[docdb] PITR: Reload deleted but hidden tables and tablets on master failover

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8362]
Currently, on master failover / restart, for tables and tablets that are moved into a DELETED state, the catalog loaders do not add them back to CatalogManager memory.

For PITR, we are piggybacking on DELETED state, but adding a `hidden` boolean metadata. We should factor that into the loading code.

**Comment by spolitov** [comment]
Fixed by c221319413b3b922abba5f0bb873fa712911e6f2
