### ISSUE TITLE
Document migrating MySQL migration to Yugabyte-db using Pgloader

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yugabyte-db#8373]
Jira Link: [DB-1726](https://yugabyte.atlassian.net/browse/DB-1726)
@suranjan we would release the documentation here in two phase.
Phase - 1 - Whatever works now i.e. without the modification of schema loading, modification as per Yugabyte-db ddl extension etc.
and then Phase - 2
When more control of schema and data migration is added.
Let's talk about how we want to document this.

**Comment by lizayugabyte** [comment]
@kneeraj @suranjan This is also P1 for the docs team. Could you, please, let us know when  you are planning to provide the starter doc?
