### ISSUE TITLE
Document yb_restore for dumps from PG11, PG12 and PG13

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yugabyte-db#8374]
Jira Link: [DB-2180](https://yugabyte.atlassian.net/browse/DB-2180)
Document the steps of

- schema restore
- schema modification to include Yugabyte-db extensions
- data restore
- caveats like no parallel ddl replay and others

**Comment by lizayugabyte** [comment]
@kneeraj @suranjan This is also P1 for the docs team. Could you, please, let us know when  you are planning to provide the starter doc?

**Comment by lizayugabyte** [comment]
@kneeraj @suranjan This is also P1 for the docs team. Could you, please, let us know when you are planning to provide the starter doc?

**Comment by sushantrmishra** [comment]
can this be done using yb-voyager ?
