### ISSUE TITLE
Find out and document about supported PG_Extensions in yugabyte-db

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yugabyte-db#8375]
Jira Link: [DB-2046](https://yugabyte.atlassian.net/browse/DB-2046)
Currently following are the available extensions:

yugabyte=# select * from pg_available_extensions;
        name        | default_version | installed_version |                                            comment                                            
--------------------+-----------------+-------------------+-----------------------------------------------------------------------------------------------
 refint             | 1.0             |                   | functions for implementing referential integrity (obsolete)
 unaccent           | 1.1             |                   | text search dictionary that removes accents
 btree_gin          | 1.3             |                   | support for indexing common datatypes in GIN
 orafce             | 3.14            |                   | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 ltree              | 1.1             |                   | data type for hierarchical tree-like structures
 tsm_system_rows    | 1.0             |                   | TABLESAMPLE method which accepts number of rows as a limit
 adminpack          | 2.0             |                   | administrative functions for PostgreSQL
 dict_xsyn          | 1.0             |                   | text search dictionary template for extended synonym processing
 hstore             | 1.5             |                   | data type for storing sets of (key, value) pairs
 pg_visibility      | 1.2             |                   | examine the visibility map (VM) and page-level visibility info
 cube               | 1.4             |                   | data type for multidimensional cubes
 seg                | 1.3             |                   | data type for representing line segments or floating-point intervals
 intagg             | 1.1             |                   | integer aggregator and enumerator (obsolete)
 tcn                | 1.0             |                   | Triggered change notifications
 isn                | 1.2             |                   | data types for international product numbering standards
 tsm_system_time    | 1.0             |                   | TABLESAMPLE method which accepts time in milliseconds as a limit
 lo                 | 1.1             |                   | Large Object maintenance
 pgrowlocks         | 1.2             |                   | show row-level locking information
 pg_hint_plan       | 1.3.7           |                   | 
 sslinfo            | 1.2             |                   | information about SSL certificates
 pgstattuple        | 1.5             |                   | show tuple-level statistics
 autoinc            | 1.0             |                   | functions for autoincrementing fields
 pg_freespacemap    | 1.2             |                   | examine the free space map (FSM)
 file_fdw           | 1.0             |                   | foreign-data wrapper for flat file access
 pg_buffercache     | 1.3             |                   | examine the shared buffer cache
 dblink             | 1.2             |                   | connect to other PostgreSQL databases from within a database
 pg_stat_statements | 1.6             | 1.6               | track execution statistics of all SQL statements executed
 insert_username    | 1.0             |                   | functions for tracking who changed a table
 pg_prewarm         | 1.2             |                   | prewarm relation data
 earthdistance      | 1.1             |                   | calculate great-circle distances on the surface of the Earth
 uuid-ossp          | 1.1             |                   | generate universally unique identifiers (UUIDs)
 intarray           | 1.2             |                   | functions, operators, and index support for 1-D arrays of integers
 pg_trgm            | 1.4             |                   | text similarity measurement and index searching based on trigrams
 dict_int           | 1.0             |                   | text search dictionary template for integers
 amcheck            | 1.1             |                   | functions for verifying relation integrity
 btree_gist         | 1.5             |                   | support for indexing common datatypes in GiST
 pageinspect        | 1.7             |                   | inspect the contents of database pages at a low level
 moddatetime        | 1.0             |                   | functions for tracking last modification time
 fuzzystrmatch      | 1.1             |                   | determine similarities and distance between strings
 pgcrypto           | 1.3             |                   | cryptographic functions
 timetravel         | 1.0             |                   | functions for implementing time travel
 tablefunc          | 1.0             |                   | functions that manipulate whole tables, including crosstab
 postgres_fdw       | 1.0             |                   | foreign-data wrapper for remote PostgreSQL servers
 bloom              | 1.0             |                   | bloom access method - signature file based index
 yb_pg_metrics      |                 |                   | track execution statistics of all YSQL statements executed
 citext             | 1.5             |                   | data type for case-insensitive character strings
 plpgsql            | 1.0             | 1.0               | PL/pgSQL procedural language
 pgaudit            | 1.3.2           |                   | provides auditing functionality
(48 rows)

**Comment by karolzlot** [comment]
Is it possible to install other extensions, for example [support for ULID](https://github.com/edoceo/pg-ulid)?

**Comment by sushantrmishra** [comment]
Supported extension are documented in : https://docs.yugabyte.com/preview/explore/ysql-language-features/pg-extensions/
