### ISSUE TITLE
[Jepsen][YSQL][v2.4] Inconsistency in counter test under partition

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#8391]
Jira Link: [DB-2350](https://yugabyte.atlassian.net/browse/DB-2350)
During our Jepsen on Jenkins runs, we found an issue for `yb yugabyte-2.4.3.0-b2-centos-x86_64.tar.gz counter nemesis partition`, which corresponds to YB @ 49799cc1d8d7fdbac8361f0dd7801e6bd5c1ed72 using yugabyte/jepsen@0433e32fec1dc805f2aa15c4f9601aa903b2b55e.
Logs are here: 
[2021-05-06_2.4_ysql_append_partition.zip](https://github.com/yugabyte/yugabyte-db/files/6458283/2021-05-06_2.4_ysql_append_partition.zip)

Likely to be related to v2.4 issues #8192 and/or #8085, possibly also #7787

**Comment by qvad** [comment]
Evaluated 400+ runs for 2.6 and current master version.
Issue in no longer reproducible
