### ISSUE TITLE
YSQL: Enable concurrent transactions on remaining ALTER TABLE DDL Statements

### ISSUE THREAD

**Issue by emhna** [yugabyte/yugabyte-db#8398]
Jira Link: [DB-1551](https://yugabyte.atlassian.net/browse/DB-1551)
This issue is extension to github issue #7327.

When DDL transaction such as ALTER TABLE is performed at the same time as transaction block, the transaction will run into system catalog version mismatch.
To ensure this error message only appears when the transaction is operating on the same table, changes are made at Postgres and DocDB layer to abort only the transactions running on the tablet that's being altered.

This change will be applied on other ALTER TABLE commands we currently support, aside from DROP COLUMN and ADD COLUMN.

Note, as a follow up, we will need to pass in the transaction ID when calling `StopActiveTxnsPriorTo()` to eliminate itself while aborting transactions. This feature is necessary to support ADD PRIMARY KEY.
This means transaction ID must also be passed when alter table gets triggered from `ProcessTabletReport()` due to TServer's heartbeat delay.

**Comment by jaki** [comment]
In short, change ALTER TABLE commands (besides DROP COLUMN and ADD COLUMN) to not cause catalog version mismatch affecting all tables and rather cause conflict on operations/transactions touching the table.
