### ISSUE TITLE
Adding expired keys with "NX" option

### ISSUE THREAD

**Issue by adarshash** [YugaByte/yugabyte-db#84]
Adding new keys to DB using "NX" option works fine. But once the key is expired I am unable to add the same key with "NX" option. Here is an example 

127.0.0.1:6379> set test 1 EX 5 NX
OK
127.0.0.1:6379> get test
"1"
127.0.0.1:6379> get test
"1"
127.0.0.1:6379> get test
(nil)
127.0.0.1:6379> set test 1 EX 5 NX
(error) Unknown error
127.0.0.1:6379> set test 1 EX 5 XX
OK

**Comment by kmuthukk** [comment]
hi @pritamdamania87 : assigning this to you.

**Comment by hectorgcr** [comment]
Closed by commit https://github.com/YugaByte/yugabyte-db/commit/a4498b4b344b7a04c64f09eaa30b7667040b3c8d
