### ISSUE TITLE
[DOC] yb_admin's list_tablets command syntax not documented online

### ISSUE THREAD

**Issue by sido420** [yugabyte/yugabyte-db#8401]
yb_admin's `list_tablets` command has another syntax below that is documented in CLI help:

```
 yb-admin | egrep -i list_tablets
 5. list_tablets <(<keyspace> <table_name>)|tableid.<table_id>> [max_tablets] (default 10, set 0 for max)
 ```
But, the syntax is not mentioned in online documentation page at https://docs.yugabyte.com/latest/admin/yb-admin/#list-tablets

**Comment by ddorian** [comment]
Fixed in https://github.com/yugabyte/yugabyte-db/pull/17183
