### ISSUE TITLE
Newly imported jedis tests are failing because of the package / directory mismatch

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#841]
E.g. we have redis.clients.jedis.tests.commands as the package for redis.clients.jedis.tests.commands.ObjectCommandsTest, but the file is located in a path that does not include the "redis" subdirectory. In general the package path needs to match the relative path from the source root.

**Comment by amitanandaiyer** [comment]
Fixed in e872386cf440c5037b468d21f1dc3b2c7b540070
