### ISSUE TITLE
[docs] Improvements to Migration Documentation

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#8410]
Jira Link: [DB-4632](https://yugabyte.atlassian.net/browse/DB-4632)
From Slack:

Marko Rajcevic Today at 10:47 AM
Hi team: @Chris Chang brought up a good point after a prospect call we had this morning. Our current migration docs talk about the technical work required for the migration process to YB, however do not call out YB specific topics that they will need to figure out such as the use of primary keys, sharding strategies, and replication factor (to name some). On the call the customer asked something along the lines of “what should we be aware of when migrating from PG to YB?” and I touched on some of the topics above. Although we have information about these concepts in their own respective sections of our documentation, would it be worthwhile to add a section to the “Migrate” section under YugabyteDB Core to call out some of the technical decisions they will have to make before building out the YB cluster? Thinking it would provide high level guidance and point to those other sections for deeper understanding as a part of the migration. 

Jimmy  1 hour ago
@Marko Rajcevic - I brought a similar topic with @karthik last week about data migrations. Note that this section: https://docs.yugabyte.com/latest/manage/data-migration/ is YCQL only. Some of the info from here: https://docs.yugabyte.com/latest/migrate/migrate-from-postgresql/ should be included or both sections should be consolidated

Nikhil  1 minute ago
Ecosystem team is working on ysql migration tools, specially pg_restore (soon to be renamed as ysql_restore) and pgloader. cc @Suranjan Kumar who is working on the docs for these tools.

**Comment by lizayugabyte** [comment]
pg_loader is documented here: https://docs.yugabyte.com/latest/integrations/ysql-loader.md (doc ticket https://github.com/yugabyte/yugabyte-db/issues/9402 )
pg_restore is tracked by https://github.com/yugabyte/yugabyte-db/issues/8374 (dev)

@nchandrappa @chrisckchang I suggest we close this ticket.

**Comment by polarweasel** [comment]
(No longer required, now that Voyager is out.)
