### ISSUE TITLE
[docdb] PITR: Implement delete_schedule and edit_schedule APIs

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8417]
Jira Link: [DB-2166](https://yugabyte.atlassian.net/browse/DB-2166)
For edit, it would be tricky to expose modifying the filter, as we might expand to capture tables not previously captured, for which we wouldn't have old snapshots. Given that, let's just have an ability to change `interval` and `retention`.

For delete, we need to confirm that all relevant GC work is done appropriately
- TS side snapshots are removed
- hidden tablets are removed, if needed

**Comment by sanketkedia** [comment]
This is a good intro task to get familiar with the basics like how to add a client-side interface, define protobufs for communication between client and server,  make RPC calls, understand the translation of table rows to rocksdb key-value pairs, perform a simple sys catalog write, etc. delete_schedule has already been implemented. For edit_schedule, typically the following changes are needed:

1. Define the format of the `edit_schedule` command and add it in yb-admin. The format should be such that it takes in the id of the snapshot schedule that the user wants to edit, allows for updating the `interval` and/or the `retention`. To add the command look at this similar [code](https://github.com/yugabyte/yugabyte-db/blob/master/ent/src/yb/tools/yb-admin_cli_ent.cc#L170)

2. Perform client-side validation checks such as the id should exist, the format should be valid, etc, and error out accordingly. For verifying if the snapshot schedule id is valid, you can invoke the `ListSnapshotSchedules` RPC. See [here](https://github.com/yugabyte/yugabyte-db/blob/master/ent/src/yb/tools/yb-admin_client_ent.cc#L464) for how to invoke the ListSnapshotSchedules RPC.

3. Define and Invoke the `EditSnapshotSchedule` RPC to send the request to the server (intercepted by the catalog manager of the master). You have to define this RPC as well as the corresponding request and response protobufs. For defining the protobufs look at this proto [file](https://github.com/yugabyte/yugabyte-db/blob/master/ent/src/yb/master/master_backup.proto#L151)

4. At the server-side, update the corresponding entry in the sys catalog to reflect the new `interval` and `retention`. Look at [this](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/master_snapshot_coordinator.cc#L463) code that performs a similar write to the sys catalog

5. Update the in-memory `schedules_` structure to reflect the new values. You can use [this](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/master_snapshot_coordinator.cc#L606) function to update by loading the new entry from the sys catalog

6. Write tests that validate that snapshots are getting created once every new `interval`. Also, old snapshots should get garbage collected every `retention` period. You can add a test [here](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tools/yb-admin-snapshot-schedule-test.cc)

cc @bmatican @spolitov

**Comment by jordans6** [comment]
Hey, @bmatican, if no one is working on this task currently I'd love to pick it up!

**Comment by bmatican** [comment]
@jordans6 Glad to hear you're excited to be contributing to YB. That sounds great, hopefully @sanketkedia 's message above helps as a starting point!

If you need anymore help, feel free to join our public slack and ask questions on the #contributors channel!

**Comment by jordans6** [comment]
Awesome, I'm looking forward to contributing!  Would you be able to send me a link to the slack channel?  The one in the readme gives me the following error message: 
"This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link."

**Comment by SrivastavaAnubhav** [comment]
Hi @jordans6, here's a link for the slack: https://communityinviter.com/apps/yugabyte-db/register
(I'll fix the README link in a bit.)

**Comment by jordans6** [comment]
Thanks, I've joined the slack now.

**Comment by druzac** [comment]
Is an interval of 0 or retention_duration of 0 valid? `create_snapshot_schedule` currently accepts both. I suppose the semantics for a 0 interval are as soon as possible, and the semantics of a 0 retention_duration are an infinite TTL?

**Comment by sanketkedia** [comment]
That's good point @druzac I would say we can just disallow 0 as the interval or retention instead of getting into the confusion and having to explain to users as to what means what?

**Comment by sanketkedia** [comment]
cc @vkulichenko
