### ISSUE TITLE
JSONB: Support for root primitives

### ISSUE THREAD

**Issue by tcf909** [YugaByte/yugabyte-db#842]
Per a discussion with @kmuthukk 

Opening up an issue for a discussion on allowing root primitives in column_type JSONB.

Technically string, numbers, and booleans are all valid JSONB types.

Should Yuga support for instance:
```
INSERT INTO k.t (id, json) VALUES (1, 'true');
```
We should track down what specifically is supported today, and what *should* be supported moving forward.

**Comment by kmuthukk** [comment]
@m-iancu - could you please confirm? Thanks a lot.

**Comment by m-iancu** [comment]
@tcf909 We do support JSONB primitive types: boolean, numeric (integer and non-integer), string and null. 
Example below.

_Note: Omitting the `cqlsh>` shell marker so this can be copy pasted. Also this uses YugaByte's fork of cqlsh (found here) which has the JSONB support enhancement._ 

```cql
create keyspace foo;
use foo;
create table foo(h int primary key, jb jsonb);
-- boolean
insert into foo(h, jb) values (1, 'true');
-- numeric (integer)
insert into foo(h, jb) values (2, '-12');
-- numeric (non-integer)
insert into foo(h, jb) values (3, '12.5');
-- null
insert into foo(h, jb) values (4, 'null');
-- string (note the double quote).
insert into foo(h, jb) values (5, '"foo"');
-- random text (unquoted string). Should fail.
insert into foo(h, jb) values (6, 'abc');
```
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Query error: Invalid Arguments. Corruption: JSON text is corrupt: Invalid value.
insert into foo(h, jb) values (4, 'abc');
       ^^^^
 (error -304)"
```
```
select * from foo;
```
```
 h | jb
---+-------
 5 | "foo"
 1 |  true
 4 |  null
 2 |   -12
 3 |  12.5

(5 rows)
```

Selecting a subfield will obviously always return `null` (for primitive values). 
```
select jb->'a' from foo;
```
```

 expr
------
 null
 null
 null
 null
 null

(5 rows)
```

**Comment by tcf909** [comment]
Related https://github.com/YugaByte/cassandra-nodejs-driver/pull/1

**Comment by tcf909** [comment]
Right now the node.js will not send a null value to the encoder class to encode We'd have to decide to change that.

Also the server sends null as a result when selecting a missing field. I guess these are similar, but null is a valid value to be stored and return (valid result).

Related #845 

My thought would be if there is a missing value, it should not be considered null, since null could be a real value.

**Comment by m-iancu** [comment]
@tcf909 It's important to distinguish between the JSON null (i.e. the JSON primitive value `'null'`) and the YCQL null (i.e. the missing value returned as `null`). In my answer above I was not clear, but meant to refer to YCQL null, which is equivalent to e.g. not inserting any value in the JSON column at all.

In any case, I think it's probably fine to not allow it for now to avoid this exact confusion.
