### ISSUE TITLE
Enabling auto_explain in Yugabyte for slow queries. 

### ISSUE THREAD

**Issue by ramsrivatsa** [yugabyte/yugabyte-db#8429]
The `auto_explain` module provides a means for logging execution plans of slow statements automatically, without having to run `EXPLAIN` by hand. This is especially helpful for tracking down un-optimized queries in large applications.

**Comment by sushantrmishra** [comment]
auto_explain is already enabled in YugabyteDB. Only caveat is that extension can not be loaded using the LOAD command as LOAD command is not supported in YugbyteDB.
