### ISSUE TITLE
[Platform][UI]Doing a page refresh in "Slow Queries" page results in logging out

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#8430]
How to reproduce:
- Login to Platform
- Goto a Universe
- Select Queries, select Slow Queries tab
- Refresh (Cmd-R)
- You'll be thrown back to login page saying "Your session has expired"
cc @sshev

**Comment by yb-andrew** [comment]
This change is a follow-up fix for commit 82bb1e73357cfd7a8444406cd0601e5171d3b5ed. Since that commit does not exist on 2.6, there's no need for the fix to be backported.
