### ISSUE TITLE
[Platform] Make proxy timeout configurable

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#8460]
Should be able to have an app conf value that allows us configuring the proxy timeout. Default value should be 60s.

This is needed for the cloud's metrics collection.

**Comment by RP1807** [comment]
Validated this issue on 2.6 portal. Followed below steps 
1. Create a universe 
2. Go to Universe Nodes -> Click on Master/tservers to make a proxy request 
3. Validate proxy requests are successful for each node of the universe. Check Dashboards, Tables, utility pages, etc. 
4. Disconnect from VPN and try to make a proxy request. It should get timed out after 1 min. 

cc @VijiYB
