### ISSUE TITLE
[Platform][UI] User not redirected to the original URL after signing in

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#8461]
Platform power user feedback: "_When I click on a platform url, but I have to sign in first, I’m then redirected to the home page, rather than to the URL I initially clicked. Any cheap way we can fix that with some referral magic?_"

**Comment by streddy-yb** [comment]
hi @gaurav061 - can you please back port this to 2.6? thanks

**Comment by gaurav061** [comment]
Done @streddy-yb. Thanks.
