### ISSUE TITLE
[YEDIS] scan and type commands for compatibility with UI

### ISSUE THREAD

**Issue by devthejo** [yugabyte/yugabyte-db#8467]
see https://github.com/patrikx3/redis-ui/issues/57#issuecomment-841519350

**Comment by ddorian** [comment]
@devthejo note that [YEDIS layer is deprecated](https://docs.yugabyte.com/latest/yedis/) and no new features are planned. The focus is on YSQL & YCQL. 

Closing as won't fix since it's a feature request.
