### ISSUE TITLE
[docdb] master FATAL ../../src/yb/util/ref_cnt_buffer.cc:34] Check failed: data_ != nullptr

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#8469]
Jira Link: [DB-4740](https://yugabyte.atlassian.net/browse/DB-4740)
0514 12:19:10.884758 23163 ref_cnt_buffer.cc:34] Check failed: data_ != nullptr
May 14 08:19:17 shayugabyte2 yb-master[3006]: Fatal failure details written to /usr/scratch/yugabyte/data0/yb-data/master/logs/yb-master.FATAL.details.2021-05-14T12_19_10.pid3006.txt
May 14 08:19:17 shayugabyte2 yb-master[3006]: F20210514 12:19:10 ../../src/yb/util/ref_cnt_buffer.cc:34] Check failed: data_ != nullptr
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5491b2abcc  yb::LogFatalHandlerSink::send()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5490d03cae  google::LogMessage::SendToLog()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5490d00e3a  google::LogMessage::Flush()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5490d04529  google::LogMessageFatal::~LogMessageFatal()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5491b9e85c  yb::RefCntBuffer::RefCntBuffer()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f54942d8923  yb::rpc::YBInboundCall::AllocateSidecarBuffer()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f54942d9b9a  yb::rpc::YBInboundCall::AddRpcSidecar()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f549bfb5e6f  yb::tserver::TabletServiceImpl::DoReadImpl()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f549bfb701c  yb::tserver::TabletServiceImpl::DoRead()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f549bfb7421  yb::tserver::TabletServiceImpl::CompleteRead()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f549bfb905a  yb::tserver::TabletServiceImpl::Read()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f54967c2d55  yb::tserver::TabletServerServiceIf::Handle()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f54942c31c9  yb::rpc::ServicePoolImpl::Handle()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5494268084  yb::rpc::InboundCall::InboundCallTask::Run()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f54942d5098  yb::rpc::(anonymous namespace)::Worker::Execute()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f5491bc255f  yb::Thread::SuperviseThread()
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f548d2de694  start_thread
May 14 08:19:17 shayugabyte2 yb-master[3006]:     @     0x7f548ca1b41d  __clone

**Comment by rthallamko3** [comment]
Seems like instrumentation was added to identify the requested memory size.
