### ISSUE TITLE
[docdb] PITR: Investigate and add support for other types of ALTER TABLE for YSQL

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8483]
After #7135, we should technically have ALTER working on including TS operations. However, RENAME might have some master-side pieces that, with changing table name map, which we should validate it works as expected!

**Comment by bmatican** [comment]
For YCQL, I tested rename column and that works fine. Rename table is only a concept in YSQL, so we can defer that to the YSQL work.

**Comment by sanketkedia** [comment]
For YSQL, ALTER TABLE ADD COLUMN, ALTER TABLE DROP COLUMN, ALTER TABLE RENAME COLUMN works.
