### ISSUE TITLE
Tasks page for Universe Overview never loads 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8487]
**Issue**
In a large environment we experience a failure to load when looking at the `Tasks` page that is supposed to reflect operations (ongoing, successful, failed) for all Universes managed by the platform. 

This is ineffective and does not allow for proper, comprehensive oversight. 

**Steps to Reproduce*
For the situation where we are seeing the 33 nodes total, across 5 Universes. 

**Additional Information**
This needs to be a working feature for large environments, and should preview with pagination. 

Please reference ticket: [1045](https://yugabyte.zendesk.com/agent/tickets/1045)

**Comment by streddy-yb** [comment]
hi @CharlotteRose -  What version are you seeing this issue in?  See #6945 and #4618 for related issues. I'll follow up to see if we're missing some scenarios.

**Comment by CharlotteRose** [comment]
@streddy-yb - @tvesely discovered that adding an index on the two most queried values provided a world of difference in performance.

The additions were:

`
create index on customer_task (task_uuid);
create index on task_info (parent_uuid);
`

**Comment by streddy-yb** [comment]
Thanks @tvesely

**Comment by CharlotteRose** [comment]
@streddy-yb - I will go ahead and make an KB on this issue from the Support side for now, can we confirm is this will be something that will be integrated into the code base in the future?
