### ISSUE TITLE
Root CA Certificate rotation or multiple enteries must be supported due to executive level changes to CA Chain 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8489]
**Issue**
Due to imposed changes in the secure environments, the existing CA chain has been changed and the rootCA for is being retired. There is a hard deadline for the end of summer that requires all systems in their environment use certificates signed by the new rootCA.

**Steps to Reproduce**
Secure Environments require Yugabyte be able to handle an intermediary CA from any of the 6 in their environment, as well as support at least 2 root CAs - OR - the ability to rotate a root CA.

**Additional Information**
Some changes are beyond the control of the YB operator and can be issued with a hard deadlines. Yugabyte admins cannot negotiate the timeline or changes imposed by security teams.

Please reference ticket: [1045](https://yugabyte.zendesk.com/agent/tickets/1262)

**Comment by streddy-yb** [comment]
cc @Arnav15 @iSignal

**Comment by hsiaosu-yb** [comment]
We'd also need to provide a manual way for 2.4.

**Comment by hkandala** [comment]
Status:

**Master:**
- Update /upgrade/certs API to support root cert rotation for all types of certs - Changes done (currently using restarts to reload certs, will be updated to RPC calls once changes are landed in ybase), testing in-progress

**2.6 Backport:**
- Backport certificate chaining support (930d10399136f6541d2f0180b2430958bd777032) - Landed
- Update CertsUpgrade to support root cert rotation for only custom certs - In progress

**2.4 Backport:**
- Backport mTLS changes (1e5639c78fabe8780d50f940020fd4ef90dd843f) - In review
- Backport certificate chaining support (930d10399136f6541d2f0180b2430958bd777032) and other dependencies (37cf98832c41459b7365c962d84ce3858b631ca5, af59aa8b2e55a60986e4c081d92bd4f67d867117) - Pending
