### ISSUE TITLE
YCQL: Updating JSON column array with invalid index shows cryptic error message

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#849]
Updating JSONB column array with invalid index shows cryptic error message. To reproduce:
CREATE TABLE store.books(id int PRIMARY KEY, details jsonb);
INSERT INTO store.books(id, details) VALUES(1, '{"editors" : ["John", "Elizabeth", "Jeff"]}');

UPDATE store.books SET details->'editors'->'1' = '"foo"' WHERE id = 5;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Query error: Execution Error. Corruption: Failed Write(tablet: ee5642d8c5f144379333c335b5abbc98, num_ops: 1, num_attempts: 1, txn: 00000000-0000-0000-0000-000000000000) to tablet ee5642d8c5f144379333c335b5abbc98 on tablet server { uuid: 4482b796587b4e2ea3fa863ab494c473 private: [host: "127.0.0.1" port: 9100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 1 attempt(s): Slice has size 0, to decode, expecting at least 1
update store.books set details->'editors'->'1' = '"foo"' where id = 1;
^^^^^^
 (error -300)"

This should be changed to a more intuitive message like Array Index invalid.

**Comment by m-iancu** [comment]
Closing, the error is now clearer:
```
ycqlsh> UPDATE store.books SET details->'editors'->'1' = '"foo"' WHERE id = 5;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Execution Error. JSON path depth should be 1 for upsert
UPDATE store.books SET details->'editors'->'1' = '"foo"' WHERE id = 5;
^^^^^^
 (ql error -300)"
ycqlsh>
```
See also #7632.
