### ISSUE TITLE
[YSQL] Make OOM killer prioritize PG backends with more memory

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8494]
Mihnea and I were talking that, until we figure out good ways to limit memory usage on the PG side, or lower the default memory usage of the TS, so we leave more room to PG, we could at least play around with something like `nice`, to make sure when the oom killer hits, it at least kills PG backends first.

**Comment by iSignal** [comment]
@fritshoogland-yugabyte suggested setting  /proc/<pid>/oom_adj for postgres based on a recent experiment where we saw the OOM killer take down the tserver when a postgres process increased RSS. 

We can either wait for systemd integration in Platform and set this via systemd (https://askubuntu.com/questions/60672/how-do-i-use-oom-score-adj) or modify postgres code to set this on itself based on a conf setting maybe.

**Comment by ramsrivatsa** [comment]
Feature added with the following commit [5738e0f](https://github.com/yugabyte/yugabyte-db/commit/5738e0fc73143989ec17fbe6095ba46a38a1d649)

**Comment by sushantrmishra** [comment]
Test comment
