### ISSUE TITLE
Minor documentation bugs in quick-start section

### ISSUE THREAD

**Issue by aravind-nallan-yb** [yugabyte/yugabyte-db#8497]
Quick Start -> Java -> YCQL 4.6 section
POM file section is missing Java source and target versions
Fix whitespace in dependencies section

Quick Start -> Java -> YSQL JDBC section
Maven command needs additional target: package

Quick Start -> Java -> YSQL Spring Data section
Fix path for source

**Comment by polarweasel** [comment]
PR #8500 is merged to fix this
