### ISSUE TITLE
Handle EX without NX|XX from Jedis client

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#85]
Setting an empty string for the `nxxx` parameter using the Jedis client is causing an error:
```
retVal = getRedisClient().set(key.asString(), value, “”, “EX”, 100);
```

It uses the following method in Jedis:
```
public void set(final String key, final String value, final String nxxx, 
      final String expx, final long time) {
```

**Comment by hectorgcr** [comment]
Closed by commit 20c198de2e77ffb39a845d9dfa435b5a91d4232b (https://github.com/YugaByte/jedis/commit/20c198de2e77ffb39a845d9dfa435b5a91d4232b)
