### ISSUE TITLE
[YEDIS] Support for new SortedSet commands

### ISSUE THREAD

**Issue by srikanthm-1** [yugabyte/yugabyte-db#850]
Hi,
Following up from #835, we need support for more sorted set commands. The commands which are missing for [akka-persistence-redis](https://github.com/hootsuite/akka-persistence-redis/blob/master/src/main/scala/com/hootsuite/akka/persistence/redis/snapshot/RedisSnapshotStore.scala) are
`zremrangebyscore`
`zrevrangebyscore`

Apart from that, I also see a lot of uses for `zrangebylex` and `zrevrangebylex` commands as well (Widely used for prefix matching scenarios). So if you could prioritize that too, that would be great.

Thanks

**Comment by srikanthm-1** [comment]
Hi,
Any update on this?

Thanks,

**Comment by ndeodhar** [comment]
Hi @srikanthm-1 , we are not actively working on new YEDIS features in the near term and instead focusing on YSQL and YCQL. Please see the note here for more details: https://docs.yugabyte.com/latest/yedis/

Happy to discuss more if needed!

**Comment by m-iancu** [comment]
Closing as `wontfix` since we have no plans to address this at the moment.
