### ISSUE TITLE
[docdb] Setup a metric for server uptime

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8501]
Would be nice to have an explicit gauge of how long a server has been up. This would be useful in case of server restarts.

Easiest would be to use our new Lag metric facility, eg: `MillisLag` and maybe even set it up at server registration, eg: `RpcAndWebServerBase::GenerateInstanceID`

**Comment by triump2020** [comment]
@bmatican    Can i pick it up ?  :smile:

**Comment by bmatican** [comment]
@triump2020 I think you already have 2 issues that you're working on, no? ie
https://github.com/yugabyte/yugabyte-db/issues/5446
https://github.com/yugabyte/yugabyte-db/issues/4954

are you still actively looking at those?

**Comment by triump2020** [comment]
@bmatican   About  #4954  ,  i  'm not very sure how to fix, needing you confirmation . 
![image](https://user-images.githubusercontent.com/63033222/118863036-0090bc00-b911-11eb-9264-4955c44cb198.png)

**Comment by triump2020** [comment]
About  #5446, i 'm working on this

**Comment by bmatican** [comment]
Maybe let's wrap these 2 up and then if you're still up for more, can take this on.

Let me get you some followup on #4954

**Comment by triump2020** [comment]
Gotcha!

**Comment by triump2020** [comment]
Gotcha!

**Comment by manavchawla98** [comment]
Hi @bmatican!  I am a new contributor and would like to help solve this issue. I was hoping you could help point me towards the code/tests that need to be updated for this metric to work.

**Comment by bmatican** [comment]
@manavchawla98 sure, go ahead! let me know if you need more info than in the summary.

**Comment by nimwijetunga** [comment]
Closed by: https://github.com/yugabyte/yugabyte-db/commit/d5d0dafa6ad6f79e7ae5e473704961ec45fa4ec8
