### ISSUE TITLE
Move GetSplitKey from TabletServerAdminService into TabletServerService

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#8508]
The reason why `SplitTablet` is in `TabletServerAdminService`, but not `TabletServerService` is that `SplitTablet` RPC depends on `tablet_manager`. And also it creates new tablets, not only does something with the target tablet.

While `GetSplitKey` seems to be more like standard tablet operations like we have in `TabletServerService` and we only need target tablet for that, no need for `tablet_manager` and other tablets.

**Comment by triump2020** [comment]
@ttyusupov   Hi, it looks like easy ,  can i pick it up ?
