### ISSUE TITLE
[Platform] "Show deleted backups" is broken

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8509]
I selected ( using checkbox) the successfully completed backup which enabled "Delete backup" button and I deleted the backup. When I toggled on the "Show deleted backups", the deleted backup doesn't show up.

**Comment by VijiYB** [comment]
Infact, "Show deleted backups" is broken I guess, not working for backups deleted thru Actions as well.

cc @kkg-yb

**Comment by streddy-yb** [comment]
This will be fixed as part of #7594
