### ISSUE TITLE
[YCQL] Slow CQL connection establishing due to not needed 'USE <keyspace>' requests.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#8512]
Jira Link: [DB-2095](https://yugabyte.atlassian.net/browse/DB-2095)
When a TS is added to the system (or just down & up) - the CQL driver created a set of connections to the CQL Proxy (a part of TS process). The driver sends all available prepared statements through the connections and it's correct, but together with them it send useless `USE <keyspace>` CQL query.
The driver side issue is described here: https://github.com/yugabyte/cassandra-cpp-driver/issues/11

Due to the issue the TS startup time can be longer because 'USE <ks>' processing goes to the Master (via RPC) to check the keyspace existence. This useless query only slows down the connections establishing and should be prevented.
(Note: the `USE` statement is still needed if prepared statement uses non-qualified table names.)

Currently the main idea is to fix it on the driver side.
The issue is created at least to track related test changes.

To test usage of `USE` statement a new metric will be added on TS side to track number & total time of 'USE' queries.

**Comment by m-iancu** [comment]
Assuming this is done by: 
https://github.com/yugabyte/cassandra-cpp-driver/commit/747c6e21d24ae030e0f583c9d720c828ce55dce0 and also [dff32f4](https://github.com/yugabyte/yugabyte-db/commit/dff32f46e529b1be42c0290fce30a9b8abc851f1).
