### ISSUE TITLE
[Platform] Adding an instance to the OnPrem provider for the respective region is throwing an error.

### ISSUE THREAD

**Issue by nishantSharma459** [yugabyte/yugabyte-db#8516]
Scenario:

1. Configure an `OnPrem` provider with multiple regions.
2. Add an instance for the OnPrem provider `only for 1 region`.
3. Hit the `Add` button.

You'll see it's not happening. It throws an error something like thing:

<img width="1440" alt="OnPremProviderError" src="https://user-images.githubusercontent.com/75416933/118758988-b0244a80-b88d-11eb-9a6b-b3bdc1f142e3.png">

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/8532

**Comment by gaurav061** [comment]
Fixed under https://github.com/yugabyte/yugabyte-db/issues/8503
