### ISSUE TITLE
avoid splitting of tablet that is currently being remote bootstrapped or over-replicated

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#8526]
Jira Link: [[DB-440]](https://yugabyte.atlassian.net/browse/DB-440)
What if the split is requested from a tablet leader that is remote-bootstrapping one of the nodes?

Options:
- Perhaps we could disallow tablet splitting in these cases.
- Allow tablet splitting during RBS, RBS will continue to work and tablets will be split on a destination node after RBS.

[DB-440]: https://yugabyte.atlassian.net/browse/DB-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Update 2022-07-12 by @Huqicheng :

At master side, before scheduling automatic tablet split request, check
1) if tablet peers are all in running state to avoid splitting tablet during RBS
2) if tablet is over-replicated (# of live replicas > replication factor) to avoid doing post-split compaction on the replica will go down anyway.

**Comment by ttyusupov** [comment]
GH issue for test: https://github.com/yugabyte/yugabyte-db/issues/8646

**Comment by Huqicheng** [comment]
@ttyusupov Does splitting of tablet which is currently being remote bootstrapped cause any issue?

**Comment by Huqicheng** [comment]
As discussed,
Don’t split on active RBS — prevents split on first part of quorum growth
Don’t split on over replication — prevents split on 4/3 copies

Potential benefit from it: prevent post-split compactions
