### ISSUE TITLE
YB-Master UI opens only on the leader master when using multi-cluster Istio setup

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-db#8533]
## Details about the setup
This is a multi-cluster Kubernetes setup where there are 3 clusters connected to each other — east, west, central. So there are three different Helm chart installation in three Kubernetes clusters. Each cluster has 1 YB-Master and 2 YB-TServers.

For each pod of the yb-master and yb-tserver I have a separate service which is accessible from other clusters. For example, `east-yugabyte-yb-master-0` pod from east cluster has a service: `east-yugabyte-yb-master-0.ybdb.svc.cluster.local`. This is due to a limitation in Istio, we cannot use headless services like we do usually.

But when the server starts it tries to figure out it's own address based on the full hostname, and complains that the local address is not in the master list. That's why we have to add both addresses — our special service mentioned above, and the service address based on headless service. Basically it is `{broadcasted_address,full_hostname}`.

East cluster's values have these master addresses: (added extra line breaks for readability)
```yaml
masterAddresses: "{east-yugabyte-yb-master-0.ybdb.svc.cluster.local,east-yugabyte-yb-master-0.east-yugabyte-yb-masters.ybdb.svc.cluster.local},
{west-yugabyte-yb-master-0.ybdb.svc.cluster.local},
{central-yugabyte-yb-master-0.ybdb.svc.cluster.local}"
```
The server_broadcast_address is set to following along with some other flags, as that's what is reachable from all the Kubernetes clusters:
```
# --server_broadcast_addresses=$(HOSTNAME).$(NAMESPACE).svc.cluster.local:7100
# which is 
--server_broadcast_addresses=east-yugabyte-yb-master-0.ybdb.svc.cluster.local:7100
--use_private_ip=never
```
## What is the behavior you see?
When I do the above setup and try to access the master UI from the LoadBalancer IP address, it shows following error. This is from east cluster and the current leader master is in west.
```
Error retrieving leader master URL: http://west-yugabyte-yb-master-0.west-yugabyte-yb-masters.ybdb.svc.cluster.local:7000/?raw
Error: Network error (yb/util/curl_util.cc:47): curl error: Couldn't resolve host name.
```
![image](https://user-images.githubusercontent.com/5154532/118934996-a0c5ff80-b968-11eb-81bb-1db48125bebd.png)

Only the leader master's UI works as expected. 

## What is expected?
The master UI should work from any of the masters. And it should use the `server_broadcast_addresses` of the master to retrieve the details, instead of using the private IP.

cc @iSignal

**Comment by iSignal** [comment]
Thanks for the detailed report, this is tracked by https://github.com/yugabyte/yugabyte-db/issues/7867 - will follow up on it.
