### ISSUE TITLE
No error toast should be shown in case of auth token expiry.

### ISSUE THREAD

**Issue by ymahajan** [yugabyte/yugabyte-db#8539]
This is happening on every login attempt, the error toast should not be shown, but upon expiry of auth token from browser cookies, the UI app should handle such response by redirecting to the login page without showing a toast about session expiration. 
<img width="1087" alt="Screen Shot 2021-05-07 at 10 50 09 AM" src="https://user-images.githubusercontent.com/11731162/119010201-a9a6d900-b948-11eb-91d8-1d7001ce5bce.png">

**Comment by sshev** [comment]
@streddy-yb session expiration toast functionality is not there in `2.6` cut so there's nothing to backport
