### ISSUE TITLE
[Platform] Size of table always shows 0 (even after sometime) until some operation like backup done

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8547]
Size of the table that was created by Sample apps always shows zero until some operation like backup is done.

After running sample apps for 10 mins, the size still shows 0

<img width="1586" alt="Screen Shot 2021-05-20 at 4 55 01 PM" src="https://user-images.githubusercontent.com/78048211/119062858-96b5f800-b98c-11eb-84a2-6bae86b7b626.png">

**Once I took a backup, it got updated and shows the size**

<img width="1575" alt="Screen Shot 2021-05-20 at 4 55 22 PM" src="https://user-images.githubusercontent.com/78048211/119062883-a1708d00-b98c-11eb-95bc-36cff6e59c0a.png">

<img width="1576" alt="Screen Shot 2021-05-20 at 4 55 45 PM" src="https://user-images.githubusercontent.com/78048211/119062891-a59caa80-b98c-11eb-85c5-0616daf67d67.png">

**Comment by sunilsutarDCE** [comment]
@VijiYB : Please refer #7563

**Comment by streddy-yb** [comment]
This is a dup of #7563
