### ISSUE TITLE
[docdb] Tool to execute a remote bootstrap on demand in case of majority raft peer failure

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8558]
Jira Link: [DB-1876](https://yugabyte.atlassian.net/browse/DB-1876)
Sometimes with majority peer failures, we still are able to recover the nodes, with the same IPs, but no data (eg: local SSDs wiped). In this case, we should be able to reuse the existing raft config from the minority peer(s), instead of using #8557 --  but we still need data.

Currently, we execute the equivalent of a remote bootstrap, manually, by taking the raft WALs, rocksdb regular and intent data and potentially snapshots, and moving it from one remaining peer, seeding an empty old peer. We should just have a tool to do that on demand, potentially triggering a remote bootstrap from a follower, onto a new node that is not serving this tablet.

Ideally we'd do it from the most up to date peer, as per #8556.

**Comment by es1024** [comment]
Added with dec0805
