### ISSUE TITLE
[Platform] Lint check for missing whitespace formatting for *.java files

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#8587]
After https://github.com/yugabyte/yugabyte-db/commit/eec613568e5e2f4fd5865aafb9d8fc3c40599cb0, we have a way to format java code and we've made this a convention for folks to run this before check-in. However, there is no check-in gate for this in case someone forgets to run this.
cc @sb-yb

**Comment by Arnav15** [comment]
@iSignal closing this since now there is a GH action, as well as an arc check.
