### ISSUE TITLE
alter table add column with not null throws error Already Present  when there are data in table.

### ISSUE THREAD

**Issue by ssung-yugabyte** [yugabyte/yugabyte-db#8595]
##test1: add column with not null to an empty table
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null |

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null |

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=#
yugabyte=# alter table test1 add column if not exists a boolean not null;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null |

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null |

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null |

##test2: add column with default not null to an empty table
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

##test3: add column with not nul to a table (with data)
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ERROR:  Already present: The column already exists: a
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ERROR:  Already present: The column already exists: a
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ERROR:  Already present: The column already exists: a
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

##test4: add column with not null default to a table (with data)
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ALTER TABLE
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | boolean |           | not null | true

##test5: add column with syntax error to a table (with data)
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ERROR:  Already present: The column already exists: a

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ERROR:  Already present: The column already exists: a

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ERROR:  Already present: The column already exists: a

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE

##test6: add column with syntax error to a table (with data)
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE
yugabyte=# \d test1
                  Table "public.test1"
 Column |  Type   | Collation | Nullable |   Default
--------+---------+-----------+----------+--------------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | text    |           | not null | 'test'::text

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE
yugabyte=# \d test1
                  Table "public.test1"
 Column |  Type   | Collation | Nullable |   Default
--------+---------+-----------+----------+--------------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | text    |           | not null | 'test'::text

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE
yugabyte=# \d test1
                  Table "public.test1"
 Column |  Type   | Collation | Nullable |   Default
--------+---------+-----------+----------+--------------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | text    |           | not null | 'test'::text

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE
yugabyte=# \d test1
                  Table "public.test1"
 Column |  Type   | Collation | Nullable |   Default
--------+---------+-----------+----------+--------------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | text    |           | not null | 'test'::text

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a test not null;
ERROR:  type "test" does not exist
LINE 1: alter table test1 add column if not exists a test not null;
                                                     ^
yugabyte=# alter table test1 add column if not exists a text not null default 'test';
ALTER TABLE
yugabyte=# \d test1
                  Table "public.test1"
 Column |  Type   | Collation | Nullable |   Default
--------+---------+-----------+----------+--------------
 k      | integer |           |          |
 v      | integer |           |          |
 a      | text    |           | not null | 'test'::text

##test7: add column (removen if not exists)
v2.4.2
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column a text not null;
ERROR:  column "a" contains null values
yugabyte=# \d test1
               Table "public.test1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 k      | integer |           |          |
 v      | integer |           |          |

yugabyte=# alter table test1 add column a text not null default 'test';
ERROR:  Already present: The column already exists: a

v2.4.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column a text not null default 'test';
ERROR:  Already present: The column already exists: a

v2.4.4
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column a text not null default 'test';
ERROR:  Already present: The column already exists: a

v2.5.3
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column a text not null;
ERROR:  column "a" contains null values
yugabyte=#  alter table test1 add column a text not null default 'test';
ALTER TABLE

v2.7.0
yugabyte=# create table test1(k int,v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,2),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column a text not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column a text not null default 'test';
ALTER TABLE

**Comment by ssung-yugabyte** [comment]
Not impacted version: 2.5.3.3
yugabyte=# create table test1 (k int, v int);
CREATE TABLE
yugabyte=# alter table test1 add column if not exists b boolean not null;
ALTER TABLE

**Comment by epratt-yb** [comment]
I tested further against all the versions again.  It seems to be related to a failed column add rather than "if not exits".  If you run the following against any version pre 2.7.0 we get the error:

```
yugabyte=# create table test1(k int, v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,1),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ERROR:  Already present: The column already exists: a
```

Further more if you keep trying different column values you can get the following error as well:

```
yugabyte=# create table test1(k int, v int);
CREATE TABLE
yugabyte=# insert into test1 values (1,1),(2,4);
INSERT 0 2
yugabyte=# alter table test1 add column if not exists a boolean not null;
ERROR:  column "a" contains null values
yugabyte=# alter table test1 add column if not exists a boolean not null default true;
ERROR:  Already present: The column already exists: a
yugabyte=#
yugabyte=# alter table test1 add column if not exists b boolean not null default true;
ALTER TABLE
yugabyte=# alter table test1 add column if not exists c boolean not null;
ERROR:  column "b" contains null values
```

**Comment by ssung-yugabyte** [comment]
When there are data in the table, if you "alter table add column c1 boolean **not null**",  ysqlsh responds column c1 contains null values.  This is expected behavior because ysql does not know how to handle the existing rows.  This error is legit and the add column command should be rollback. The next command "alter table add column c1 boolean **not null default true** " should add the column to the table.  But ERROR: Already present is returned.   
Impacted version: 2.4.x 
Not impacted version: 2.5.3 and 2.7.0

**Comment by deeps1991** [comment]
All of the above cases boil down to [#5543](https://github.com/yugabyte/yugabyte-db/issues/5543) which has been fixed as part of https://phabricator.dev.yugabyte.com/D10626 in 2.5.3 and 2.7. Since this was implemented after some refactoring done in the Alter table code path in 2.5* and after, the 2.4 cherry pick of this patch is not clean. So I'd choose not to cherry pick to 2.4 and leave it as it is. Please re-open and assign to me if its explicitly required in 2.4
