### ISSUE TITLE
Explain plan for YCQL

### ISSUE THREAD

**Issue by patrick-li** [YugaByte/yugabyte-db#861]
Explain plan seems for YSQL only.
We may use this ticket to track it.

**Comment by harshithdepa** [comment]
EXPLAIN SELECT where index is used

<img width="1011" alt="screen shot 2019-03-04 at 9 37 33 am" src="https://user-images.githubusercontent.com/22989932/53751645-9390c900-3e61-11e9-9143-2e0a824ca0a1.png">

EXPLAIN SELECT where index is not used

<img width="660" alt="screen shot 2019-03-04 at 9 42 44 am" src="https://user-images.githubusercontent.com/22989932/53751783-e8ccda80-3e61-11e9-9f06-251c03f8c0ad.png">

EXPLAIN INSERT 

<img width="420" alt="screen shot 2019-03-04 at 9 48 13 am" src="https://user-images.githubusercontent.com/22989932/53752356-444b9800-3e63-11e9-85e5-19d18ea937cb.png">

EXPLAIN UPDATE

<img width="638" alt="screen shot 2019-03-04 at 9 49 02 am" src="https://user-images.githubusercontent.com/22989932/53752294-1cf4cb00-3e63-11e9-8eff-cbd07eef25a1.png">

EXPLAIN DELETE

<img width="600" alt="screen shot 2019-03-04 at 9 49 34 am" src="https://user-images.githubusercontent.com/22989932/53752397-5b8a8580-3e63-11e9-80b1-46c7db249937.png">

**Comment by harshithdepa** [comment]
Added in 43f44dea707f94c47ac84e9ae2f399a4c5d76289
