### ISSUE TITLE
[Platform] Clicking "Edit Configuration" on one backup applies to all Backup tabs

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8611]
I clicked "Edit Configuration" on AWS but did not change anything, I navigated to another tab like GCS/Azure, and those storage are automatically went to "edit configuration" mode even though I did not click "Edit Configuration" explicitly.

Repro:
1. Backup -> AWS
2. Click "Edit Configuration"
3. Without canceling/update, click on Azure/GCS
4. You will see that Azure/GCS is in Edit Configuration mode even without me explicitly clicking "Edit configuration"

Expected - By default, the backup config should be in non-editable mode unless click on "Edit Configuration" on that specific tab

cc @nishantSharma459

**Comment by VijiYB** [comment]
Once we click on Edit and move to different menu and come back, the edit state is retained currently. Once we move out of the tab, the state of "edit" should not be retained.

**Comment by shashwat-yb** [comment]
Validated that Backup -> AWS -> Edit Configuration only allows the active tab to change and update values and edit mode for other tabs are disabled. Also verified that this holds correct for other tabs as well.
cc @VijiYB

**Comment by VijiYB** [comment]
@shaharuk-yb - Can you create a new issue for this? - _

> But in case we return back to the same tab it still remains in active edit mode which should me disabled as we moved out of that tab earlier

_
