### ISSUE TITLE
[Platform] Live/Slow query link not showing up in Actions for each Node

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8614]
In Nodes tab -> Actions -> Show Live Queries & Show Slow Queries shows up but this is missing in the recent builds. Some regression due to some fix. Please check.

**Comment by streddy-yb** [comment]
@VijiYB - Is this true for both TLS enabled and non-TLS enabled universes?

**Comment by VijiYB** [comment]
Yes. For both.
