### ISSUE TITLE
Audit tcmalloc configurations for smaller node sizes

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#8618]
We increasingly run cluster configurations with 3x c5d.xl nodes. These have significantly fewer cores (4 cores) and more importantly significantly less memory (8GB) than clusters we have run on in the past. We should make sure our tcmalloc configurations aren't subtly or obviously incorrect for these smaller machines.

**Comment by bmatican** [comment]
Closing after #11398 and #10243
