### ISSUE TITLE
Backfill Table Rpc should show index names instead of ids in master:7000/tasks

### ISSUE THREAD

**Issue by acube123** [yugabyte/yugabyte-db#8619]
![Screen Shot 2021-05-25 at 3 11 33 PM](https://user-images.githubusercontent.com/6658556/119581518-9300e780-bd77-11eb-9aab-3d8700b8091e.png)

Backfill Table Rpc should use index names instead of index ids. similar to GetSafeTime Api.

Also, will be good to have the index names/ids sorted in the order of creation.

**Comment by ConcurrencyPractitioner** [comment]
Hi @acube123 Do you mind if I try this issue as my first newbie task? I wanted to try my hand at some Yugabyte issues, and felt that this was a good one.

**Comment by amitanandaiyer** [comment]
Sure @ConcurrencyPractitioner

**Comment by amitanandaiyer** [comment]
Note that for internal accounting/rpc purposes we may still want to keep track of the ids. But the ToString functions and the BackfillJob (used for the UI rendering above) can be a more user-friendly if they show the index names instead. 

Feel free to ping me if you need any clarification.

**Comment by ConcurrencyPractitioner** [comment]
Cool, thanks for the opportunity! I've created a pull request. So, from my understanding, I thought that I should log both the index table name plus the associated table id (since I think you wanted to keep the table id in the log as well). Hope this is what you meant. :)
