### ISSUE TITLE
[Platform] Clicking cancel on 'Edit configuration' on backup shows the edited values 

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8620]
Backup -> Edit configuration. I edited something in AWS key but I clicked cancel, though the value is not saved, the values I edited are still showing up. Once I reload the page, the edited values are gone and original (saved) values are showed, which is correct. Its good to reload the original values if cancel clicked rather than showing the edited values.

cc @nishantSharma459

**Comment by shashwat-yb** [comment]
Tested the cancel button in Backup -> AWS -> Edit configuration by changing some values in the respective fields and then checking whether it restores the previous credentials when the cancel button is clicked.
The backup page was able to handle this scenario and the previous details were visible once the cancel button is clicked.
