### ISSUE TITLE
[Jepsen] Operations constaintly fail under kill,partition,pause

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#8636]
Nemesis `kill,partition,pause` does not give the cluster guaranteed recovery time, which leads to `:ok-count` being 0 in some cases.

Old text:
> During our Jepsen on Jenkins runs, we found an issue for `yb yugabyte-2.6.0.0-b28-centos-x86_64.tar.gz single-key-acid nemesis kill,partition,pause`, which corresponds to YB @ 87d1d5ce7cd6582b138d6c856b6a988f17f95e38 using yugabyte/jepsen@0433e32fec1dc805f2aa15c4f9601aa903b2b55e.

**Comment by frozenspider** [comment]
Turns out this is not a consistency violation, but a CAS operation never fully succeeding.
Recent log:
[2021-08-02_ysql_single-key-acid.zip](https://github.com/yugabyte/yugabyte-db/files/6923742/2021-08-02_ysql_single-key-acid.zip)

**Comment by frozenspider** [comment]
We need to adjust the nemeses to give a brief recovery period.

**Comment by frozenspider** [comment]
Apparently setting `--nemesis-long-recovery` to `true` by default didn't help, there are still periods with all nemeses active
![image](https://user-images.githubusercontent.com/2077017/134647797-2ba7fb6b-8374-4e81-9d4d-ba98d1b6f2bb.png)

**Comment by qvad** [comment]
Fixed in https://github.com/yugabyte/jepsen/pull/56
