### ISSUE TITLE
Test: split requested from tablet leader that is doing RBS

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#8646]
Jira Link: [DB-1308](https://yugabyte.atlassian.net/browse/DB-1308)
What if the split is requested from a tablet leader that is remote-bootstrapping one of the nodes?

Options:
- Perhaps we could disallow tablet splitting in these cases.
- Allow tablet splitting during RBS, RBS will continue to work and tablets will be split on a destination node after RBS.

**Comment by Huqicheng** [comment]
0afe6dc28931a0a37c8984efe4af1246e026e7e2

**Comment by rthallamko3** [comment]
DUP of https://github.com/yugabyte/yugabyte-db/issues/8526
