### ISSUE TITLE
[docdb] Tablet splitting thresholds should be determined based on number of nodes in a table's placement policy

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#8660]
With the completion of #8039, we will have tablet split threshold semantics based on the number of tablets per tserver in a cluster. We should make these semantics smarter in the case of tables with placement policies so that we choose the tablet splitting phase based on the number of valid candidate tservers in the cluster for the table's placement policy, which could be a subset of the total number of tservers in the cluster.

**Comment by nimwijetunga** [comment]
Closed by commit: `664cc5160406606111109d5ab45fff5f88e237eb`
