### ISSUE TITLE
[doc] Reorg current Follower reads content

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#8664]
This doc is only applicable to YCQL, so we need to:

- remove OS tabs (because the content in them is the same)
- create "YSQL" and "YCQL" tabs
- move the current content under YCQL tab

The YSQL tab will be filled when the feature is no longer in Beta (we'll have a separate ticket for that)

**Comment by polarweasel** [comment]
@lizayugabyte Have a look at [this slack thread](https://yugabyte.slack.com/archives/C017TTZ9EV7/p1621557085008600), and follow up with @aravind-nallan-yb for whatever details he can add. (May be outside the scope of this ticket, or may be very timely, I don't know!)

**Comment by lizayugabyte** [comment]
@polarweasel created #8715 (no relation to the current ticket)
