### ISSUE TITLE
[Platform][UI] Even if the nodes are unreachable UI shows some actions that I feel not possible.

### ISSUE THREAD

**Issue by mjoshi0923** [yugabyte/yugabyte-db#8670]
If we look at the node it's unreachable still we see **Connect** and we see **Stop Processes** Which seems not possible from my understanding.

<img width="1693" alt="Screenshot 2021-05-26 at 10 50 50 AM" src="https://user-images.githubusercontent.com/78336250/119772037-3408b300-bedc-11eb-87e7-09df61625b7d.png">

@streddy-yb Is this a correct view?

**Comment by SergeyPotachev** [comment]
'Unreachable' here is based on metrics collected by Prometheus. Very often it doesn't mean that nodes are actually unreachable. And the actions list is based on a real nodes states (like 'Live', 'Stopped', 'Decommissioned' etc).
So the view is correct, it is not an issue.

**Comment by mjoshi0923** [comment]
Closing the issue as it's not an issue.
