### ISSUE TITLE
[docdb] Fail GetSplitKey RPC if tablet has orphaned post-split data

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#8675]
If the tablet still has this data, then the middle key calculation we use currently will be incorrect.

Even after we implement #9782 even we still need this for safety in the case in future we rework something and no longer wait for all children to be compacted for some reason. In this case, we still want GetSplitKey RPC to return an error for not yet fully compacted child tablet rather than returning incorrectly calculated key.

Unit-test for this case should be implemented within the same diff.

**Comment by nimwijetunga** [comment]
Closed by: https://github.com/yugabyte/yugabyte-db/commit/fd361c7b4200ade26f8de57eadc9b2cd05ccc8d4
