### ISSUE TITLE
[YSQL] support for roles and permissions in YSQL

### ISSUE THREAD

**Issue by ravimurthy** [YugaByte/yugabyte-db#869]
Enable support for roles and permissions.

In particular, the following commands :- 
. CREATE/DROP/ALTER ROLE
. GRANT/REVOKE
. SET ROLE
. SET SESSION AUTHORIZATION

**Comment by mbautin** [comment]
We'll heavily utilize the PostgreSQL metadata cache on every node.
A point by @bmatican: for DML we probably want to do checks on the master side every time, while for DDL a cache check (with cache refreshed every N seconds, similarly to YCQL).

**Comment by srhickma** [comment]
Support for roles and permissions is added by https://github.com/YugaByte/yugabyte-db/commit/e89d75bc16af0e819a56edd75126ba0ccc42174d, which includes roles, permissions, and object ownership, but does not include RLS or a (better) method for configuring host-based authentication parameters. Currently, these parameters can only be modified by manually changing the `pg_hba.conf` on every node.

**Comment by kmuthukk** [comment]
Excellent work @srhickma !!!
