### ISSUE TITLE
[docs] Several pages refer to CAS as compare-and-swap instead of compare-and-set

### ISSUE THREAD

**Issue by aravind-nallan-yb** [yugabyte/yugabyte-db#8692]
For example:
https://docs.yugabyte.com/latest/comparisons/cassandra/
https://docs.yugabyte.com/latest/develop/best-practices-ycql/
https://docs.yugabyte.com/latest/faq/compatibility/

Here's the Datastax C* documentation for CAS (also known as LWT or lightweight transactions): https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useInsertLWT.html

**Comment by kmuthukk** [comment]
@aravind-nallan-yb -- 

https://en.wikipedia.org/wiki/Compare-and-swap

I think both options might be OK in practice.
