### ISSUE TITLE
[YSQL] accept and ignore "with storage parameters" for create table statements 

### ISSUE THREAD

**Issue by ravimurthy** [YugaByte/yugabyte-db#870]
The "with clause" is used in create table statements to specify storage parameters. These parameters aren't relevant to tables stored in YB. However some standard utilities such as pgbench submit DDL statements with this clause.
YB should accept and ignore the "with clause" options

Example:- 

```
15:34 $ ./pgbench -i -h localhost -p 5433 -U postgres postgres
NOTICE:  table "pgbench_history" does not exist, skipping
NOTICE:  table "pgbench_tellers" does not exist, skipping
ERROR:  WITH clause not supported yet
LINE 1: ...nt not null,bid int,tbalance int,filler char(84)) with (fill...
                                                             ^
HINT:  Please contact YugaByte for its release schedule.
```

The actual underlying table definition :- 

`create table pgbench_tellers(tid int not null,bid int,tbalance int,filler char(84)) with (fillfactor=100)
`

**Comment by WesleyW** [comment]
When integrating YW and YB, Play executes the following statement. It would be helpful to have a simplified `WITH` statement to handle this.
`CREATE TABLE "public"."schema_version" (
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP NOT NULL DEFAULT now(),
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
) WITH (
  OIDS=FALSE
)`
