### ISSUE TITLE
[YSQL] Add COPY option to not use distributed transactions 

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#8704]
Jira Link: [DB-1701](https://yugabyte.atlassian.net/browse/DB-1701)
This should improve data-ingest performance, but as a trade-off, in case of failure we need to manually truncate to clean up the data.

**Comment by sushantrmishra** [comment]
Users can set `yb_disable_transactional_writes`  to true  to avoid distributed transaction.
