### ISSUE TITLE
linux ysql client for ysql_dump

### ISSUE THREAD

**Issue by saul-gush** [yugabyte/yugabyte-db#8713]
We run our back up services in a separate Kubernetes pod, looking to move to Yugabyte but cant seem to find out how to install ysql client in say ubuntu or alpine, to connect to yugabyte and ysql_dump. 

This is how we currently do it for postgresql in alpine docker image: 
```
RUN apk add --no-cache postgresql-client
```

Go application: 
```
command := fmt.Sprintf("PGPASSWORD=%s PGSSLMODE=%s pg_dumpall -h %s -p %s -U %s -f %s",
dbConfig.Password, dbConfig.SSL, dbConfig.Host, dbConfig.Port, dbConfig.User, dumpFilename,)
```

Is there a apk or apt-get install for ysql_dump (yugabyte client)? Or how is best to achieve the same?

**Comment by ddorian** [comment]
What about using yugabyte-client docker container https://hub.docker.com/r/yugabytedb/yugabyte-client ?

**Comment by saul-gush** [comment]
Thats very useful thank you - the documentation should make reference to client tools for back up and such.
