### ISSUE TITLE
[doc] Improve Explore > Follower reads > YCQL page content

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#8715]
Jira Link: [DB-4634](https://yugabyte.atlassian.net/browse/DB-4634)
kannan  3 days ago
after 60 secs, I believe we cannot serve stale reads, and we try then to go to the leader. We can always adjust this TServer gflag if we are OK with app tolerating more staleness. something we should document about our follower reads capability. Perhaps @aravind-nallan-yb can help write this whole experiment in a blog, and we shoudl also document this gflag if it is not already.

Aravind Nallan  1 day ago
Is it true that max_stale_read_bound_time_ms applies only to follower reads and not observer reads? Is there a separate setting for that or is it unbounded?

amey  23 hours ago
I will check on max_stale_read_bound_time_msgflag as well...
cc @doc-team for adding this doc's content to Follower Reads enhancement ticket

**Comment by aravind-nallan-yb** [comment]
Blog done. Docs updated.
