### ISSUE TITLE
[YSQL]: Implement partition_hash from YCQL for YSQL

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#8718]
Cassandra and YCQL have the token (and partition_hash in YCQL) function to return the partition hash value for a partition key of a table.

In YSQL, we don't yet have any equivalent functionality to compute/retrieve the internally-generated partition hash value for a hash-partitioned table.

**Comment by tylarb** [comment]
Should be a duplicate of https://github.com/yugabyte/yugabyte-db/issues/3016

**Comment by tanujnay112** [comment]
Closed by 7d3f6895c8f8d0deb094e9a102d56a09d9fe0af1
