### ISSUE TITLE
[docdb] Several tests are flaky in our gcp infra

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8725]
Jira Link: [DB-4735](https://yugabyte.atlassian.net/browse/DB-4735)
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=TestUser&name=TestNonEmpty
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=RpcStubTest&name=TestDefaultCredentialsPropagated

Seem to trace back to some `GetLoggedInUser` function failing to find the local user. I'll add some debug logging to get at least the UID info.

**Comment by rthallamko3** [comment]
Both the tests are passing in recent builds. The test stability push might have resolved the underlying issue.
