### ISSUE TITLE
[docdb] Tool to trigger a flush or compaction on the sys_catalog tablet

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8730]
We already have a `yb-ts-cli compact_tablet`, but that works strictly on the TS side. We should be able to add a similar RPC on the master side, reusing the same logic of triggering the respective tablet/rocksdbs to flush, for sys_catalog.

**Comment by Tigojiang** [comment]
Hello! I am a first-time contributor, and may I pick up this task? Would you mind me pointing out the files that need changes and the files that I should refer to? Thank you!

**Comment by Tigojiang** [comment]
@bmatican Hello! I am a first-time contributor, and may I pick up this task? Would you mind me pointing out the files that need changes and the files that I should refer to? Thank you!

**Comment by sanketkedia** [comment]
@Tigojiang let's take it in the chat. cc @robertsami

**Comment by robertsami** [comment]
hey @Tigojiang ! wanted to lay out some pointers for you here:

1. you'll want to add a new command, e.g. "flush_sys_catalog", to yb-admin. see here for an example: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/tools/yb-admin_cli.cc#L540

2. you also need to define a new RPC endpoint at yb-master. this will entail creating new request/response protos and a new RPC def'n. see the following --

Proto def'n: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/master.proto#L1948
RPC def'n: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/master.proto#L2214

3. you then need to implement that RPC endpoint in the catalog manager.

see here for an example of how to connect the rpc endpoint to a catalog manager method: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/master_service.cc#L358

then declare the corresponding method in `CatalogManager`, and handle the request. you should trigger the flush with something like this:
```
sys_catalog()->tablet_peer()->shared_tablet()->Flush(tablet::FlushMode::kSync);
```
you will need to handle a potentially bad status as well and set up the response accordingly

@Tigojiang thats a lot of info to digest im sure, so please come back with any questions either in the comments here, or by pinging me on our slack

**Comment by Tigojiang** [comment]
Hi @robertsami @bmatican, I have submitted a pull request. For the code, I register flush_sys_catalog, define RPC and protos, forward the request from master to CatalogManager, and implement it there. I am trying to handle the requests and return the status. Hopefully, it works for all cases.
