### ISSUE TITLE
Upgrading 2.3.3 => 2.4.4 or 2.3.3 => 2.7.1 breaks YSQL

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#8731]
Steps to recreate.
1. Create 2.3.3 Platform
2. Deploy 2.3.3 YSQL enabled universe
3. Upgrade 2.3.3 Platform to 2.7.1 or 2.4.4 (possibly others but these are the only versions I tested)
4. Upgrade 2.3.3 YSQL enabled universe to 2.7.1
5. Connect with ysqlsh or any client causes core dump and immediate disconnect

**Comment by d-uspenskiy** [comment]
Problem relates to bloom filter on master, reassigning to ybase team.

**Comment by ttyusupov** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/226e882217130145d6b7693af78c43616d3acbf1
