### ISSUE TITLE
[docs] YCQL partial indexing

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#8734]
Jira Link: [DB-4631](https://yugabyte.atlassian.net/browse/DB-4631)
Piyush is the engineer doing this work... Mihnea is managing.

Tracking ticket is #7509

**Comment by m-iancu** [comment]
This is documented at: https://docs.yugabyte.com/preview/explore/indexes-constraints/partial-index-ycql/. (see also the API documentation in: https://docs.yugabyte.com/preview/api/ycql/ddl_create_index/#partial-index).
