### ISSUE TITLE
[YSQL] Dropping a primary key constraint is not supported

### ISSUE THREAD

**Issue by radekg** [yugabyte/yugabyte-db#8735]
Jira Link: [DB-1677](https://yugabyte.atlassian.net/browse/DB-1677)
Attempting dropping a primary key constraint results in an error:

```
Error: ERROR: dropping a primary key constraint is not yet supported [Failed SQL: ALTER TABLE public.TABLE_NAME DROP CONSTRAINT CONSTRAINT_2]
```

This is explicitly disabled in the code: https://github.com/yugabyte/yugabyte-db/blob/1a8f1611365a6c442d523483fd12e56f28009190/src/postgres/src/backend/commands/tablecmds.c#L10500.

From what I hear, the reason is that the primary key is tied to the table's storage layout and this is remotely related to `ALTER TABLE adding a primary key` https://github.com/yugabyte/yugabyte-db/issues/1104. This seems like a reversal of https://github.com/yugabyte/yugabyte-db/commit/fd257e7faaf701439cdaf1ff936cc46fc0f8927d.

**Comment by mskarbek** [comment]
+1 with [Boundary](https://www.boundaryproject.io/):
```
"error": "postgres.(Postgres).EnsureVersionTable: unknown, unknown: error #0: ERROR: dropping a primary key constraint is not yet supported (SQLSTATE 0A000)",
```

**Comment by amitsaxena** [comment]
Is there a workaround if I want to change the primary key of a table? Haven't been able to find anything in the docs:
https://docs.yugabyte.com/preview/explore/indexes-constraints/primary-key-ysql/

**Comment by frozenspider** [comment]
@amitsaxena While this isn't supported, you can do something like
```sql
CREATE TABLE t2 (...);
INSERT INTO t2 SELECT * FROM t;
DROP TABLE t;
ALTER TABLE t2 RENAME TO t;
```
This assumes you're just playing around and there are no real workloads using `t`

**Comment by radekg** [comment]
While this is a great insight, it’s not enough in many cases. This issue is still preventing installing keycloak on ybdb using default migrations.

**Comment by frozenspider** [comment]
@radekg of course, this is merely a workaround. This issue is on our radars though.

**Comment by arunk-r** [comment]
YugaByte DB Liquibase error for Keycloak.
Reason: liquibase.exception.DatabaseException: ERROR: dropping a primary key constraint is not yet supported [Failed SQL: (0) ALTER TABLE public.USER_REQUIRED_ACTION DROP CONSTRAINT CONSTRAINT_2]

**Comment by frozenspider** [comment]
This has been implemented.
Note that just like `ALTER ADD PK`, this is NOT an online operation, and is only expected to be used for a database setup. Concurrent DMLs to this table might be lost!
Making it online is tracked separately in #13274.
