### ISSUE TITLE
[Docs] Usage of platform-support-packages.tar.gz is not in Yugabyte Documentation 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8750]
**Issue:** Customer do not understand the use, purpose and release schedule for the  `platform-support-packages.tar.gz`. This item is not referred to in our documentation. 

**Request:** Need usage documentation for `platform-support-packages.tar.gz` for customer support. 

**Additional Information:** There is only one reference to this package in an older release notes section - https://docs.yugabyte.com/latest/releases/earlier-releases/v2.2.0/#yugabyte-platform-5

**Reference Ticket:** [1268](https://yugabyte.zendesk.com/agent/tickets/1268)

**Comment by polarweasel** [comment]
This was a 2.2-specific issue, as far as I can tell. Closing.
