### ISSUE TITLE
xCluster Replication: Make setting up replication synchronous

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#8757]
Right now, the API for setting up universe replication is asynchronous (i.e. the API returns success before replication is fully set up). This results in situations where the user thinks setup has succeeded, but has failed under the hood. Once we make this synchronous, the API will cleanly bubble up errors to the caller, which would make both yb-admin and platform (in the future) more usable.

**Comment by nspiegelberg** [comment]
1. See CatalogManager's CreateTable + IsCreateTableDone functions to understand how to use the existing SetupUniverseReplication async API to add IsSetupUniverseReplicationDone.
2. Probably want to add something like table->GetCreateTableErrorStatus() to UniverseReplicationInfo so we can return it from IsSetupUniverseReplicationDone on setup failure and display to the ClusterAdminClient.

**Comment by hulien22** [comment]
Closed by a9bb6e0
