### ISSUE TITLE
CSS cards (a.section-link) could be designed better

### ISSUE THREAD

**Issue by praveensvsrk** [yugabyte/yugabyte-db#8761]
Take the following doc page for example https://docs.yugabyte.com/latest/yugabyte-cloud/ 

The cards used on this page have few issues IMO:

1. The cards occupy too much space for 1 line of info
2. Font on the card is hard on the eyes 
![image](https://user-images.githubusercontent.com/10628197/120766517-efae9000-c537-11eb-9168-8346718df52b.png)
3. Redundant icons for all cards (on some pages) which doesn't say anything important.

I suggest either make the cards compact (such as in https://docs.confluent.io/home/connect/overview.html -> "Connectors general") or remove the cards altogether.

**Comment by polarweasel** [comment]
This will be addressed in a future redesign of the docs site. Agreed on the design needing improvement!
