### ISSUE TITLE
Remove 'Beta' tag from RedHat Openshift cloud provider

### ISSUE THREAD

**Issue by ymahajan** [yugabyte/yugabyte-db#8767]
We need to remove the 'Beta' tag from UI and docs, examples etc.

![Screen Shot 2021-06-04 at 9 51 12 AM](https://user-images.githubusercontent.com/11731162/120836838-df3bec80-c51a-11eb-8253-b7bbc9c5ecc0.png)

**Comment by VijiYB** [comment]
cc @streddy-yb @ymahajan - This is still not backported to 2.6

**Comment by VijiYB** [comment]
@yb-andrew Andrew, Can you backport to 2.6? cc @hsiaosu-yb @streddy-yb

**Comment by Arpit-yb** [comment]
**Beta tag removed**
