### ISSUE TITLE
Remove 'Beta' tag from Platform HA

### ISSUE THREAD

**Issue by ymahajan** [yugabyte/yugabyte-db#8775]
Need to remove 'Beta' tag from Platform HA. 
![Screen Shot 2021-06-04 at 3 54 59 PM](https://user-images.githubusercontent.com/11731162/120870233-42467700-c54d-11eb-88f0-eb42fbeeaec1.png)

**Comment by VijiYB** [comment]
cc @streddy-yb

**Comment by streddy-yb** [comment]
Thanks @sshev

**Comment by Arpit-yb** [comment]
**Validated**
Beta tag removed
