### ISSUE TITLE
[YCQL] cassandra function "uuid()" 

### ISSUE THREAD

**Issue by barum** [YugaByte/yugabyte-db#878]
Cassandra has a function uuid() that can be embedded into the Insert/update statements.

INSERT INTO schema_migrations (id, version) VALUES (uuid(), ?)

But YB does not have such function; hence, compatibility is an issue. 
Any plans to add uuid() function?

**Comment by bbaddepudi** [comment]
From Apache Cassandra docs
`The uuid() function takes no parameters and generates a random Type 4 UUID suitable for use in INSERT or UPDATE statements.`
Will be adding a compatible `uuid()` in YCQL.

**Comment by bbaddepudi** [comment]
Quick note, got the basic flow working
`cqlsh> create keyspace if not exists test;
cqlsh> use test;
cqlsh:test> create table if not exists tt(k int primary key, v uuid);
cqlsh:test> INSERT INTO tt (k, v) VALUES (1, uuid());
cqlsh:test> select * from tt;

 k | v
---+--------------------------------------
 1 | 6ad16d20-28fe-4204-a68e-002a83442408

(1 rows)
` 
Adding more tests now.

**Comment by bbaddepudi** [comment]
Fixed in [f7915da](https://github.com/YugaByte/yugabyte-db/commit/f7915da209deac75b9f4b1b277d71d770047b2b0)
