### ISSUE TITLE
Use CSS ::before selector for shell prompt symbols in the docs

### ISSUE THREAD

**Issue by praveensvsrk** [yugabyte/yugabyte-db#8782]
Refer to this page: https://docs.yugabyte.com/latest/quick-start/explore/ysql/#docker
The `ysqlsh` shell symbol 'yugabyte=#' used in the \<code\>\</code\> element has few issues 
1. It is selectable
![image](https://user-images.githubusercontent.com/10628197/120896738-6afb6900-c640-11eb-97eb-3f0241c29450.png)
2. It is visually not distinct from the actual command
![image](https://user-images.githubusercontent.com/10628197/120896819-cc233c80-c640-11eb-9a4a-07e056a2a57a.png)
3. Repeated across all code elements

We can utilize CSS `::before` selector, which I believe is a cleaner approach, avoids duplicate HTML code, can easily have separate styling and the generated text is not selectable.

Eg css:
`.ysqlsh::before {   
content: 'yugabute=#';    
color: gray;    
}`
After applying above css:
![image](https://user-images.githubusercontent.com/10628197/120896980-9d599600-c641-11eb-80be-ab65f13342aa.png)

**Comment by polarweasel** [comment]
Thanks for the feedback @praveensvsrk. I've added "make prompts visually distinct and non-selectable" to the list of ideas for a docs-site redesign.

For now, the copy button on each code or command snippet addresses the first issue.

Creating a pattern-matching CSS selector is probably not the right approach to solve the issue, as there are many more prompts than just `yugabyte=#` — note steps 3 and later on that page, for example. The source-highlighting plugin is already identifying prompts, and the copy buttons already know to ignore them, so between those two we'll certainly be able to style prompts differently in the future.

Closing this issue. If you'd like to try and adjust the CSS, feel free to reopen and submit a PR.
