### ISSUE TITLE
bad experience

### ISSUE THREAD

**Issue by carr123** [yugabyte/yugabyte-db#8790]
1. could not restart YB-Master
    first I start a yb-master process ,then kill it, then restart it

reporting error:
. ../../src/yb/master/master_main.cc:128] Already present (yb/fs/fs_manager.cc:344): Could not create new FS layout: FSManager root is not empty

2.  command line parameters is a messy
   $ ./bin/yb-master \
--master_addresses 172.151.17.130:7100,172.151.17.220:7100,172.151.17.140:7100 \
--rpc_bind_addresses 172.151.17.130 \
--fs_data_dirs "/home/centos/disk1,/home/centos/disk2" \
--replication_factor=3

above is the example from https://docs.yugabyte.com/

some times there is "=", sometimes not.   sometimes there is double quotation mark， sometimes not. 
i spend a lot of time to find correct parameters to get yb-master run.
still, i can't get a correct config file to run yb-master.

**Comment by ddorian** [comment]
Hi @carr123 

Please be more explicit on which page(s) was the wrong configuration of yb-master.
