### ISSUE TITLE
Add version numbers when upgrading yugabyteDB

### ISSUE THREAD

**Issue by hsiaosu-yb** [yugabyte/yugabyte-db#8798]
Specifically, we could add old -> new release numbers in the notes column.  Something like (2.4.3 -> 2.4.4)

<img width="1362" alt="Screen Shot 2021-06-02 at 8 43 27 PM" src="https://user-images.githubusercontent.com/82529763/121062253-b6656280-c779-11eb-8803-fab311241dd7.png">

**Comment by amhatre99** [comment]
Done
