### ISSUE TITLE
[DOCS] Need Guide for Metrics Page in Yugaware 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8803]
**Issue**
The Yugaware/Platform UI metrics page has no legend, and the documentation surrounding what the data is meant to communicate is sparse or non-existent. 

**Request**
We need comprehensive documentation and information around the metrics views available from the Yugaware UI.

Without any information, or documentation,customers cannot identify areas for improvement or properly understand areas of concern.

**Comment by RunningJon** [comment]
I have a customer asking for this as well.

**Comment by polarweasel** [comment]
@CharlotteRose thanks for bringing this up. The UI request is clear, but from the docs perspective, what would you like to see? Do we have any internal docs floating around that would help us create some docs for this?

**Comment by dataindataout** [comment]
I have been putting together a guide for these metrics for one of our customers. Would you like the information and/or would any of you be willing to give it an additional review?

**Comment by polarweasel** [comment]
@dataindataout yes please!

Also see https://docs.google.com/document/d/1x79W19ac3Z0fw7JrcYbgtxTFolMcKLWWsjDYyyRdM6Y/edit#heading=h.yjqgvhwfmvxn from @yb-andrew...

**Comment by dataindataout** [comment]
Great! Here is the link: https://docs.google.com/document/d/1gTILXZZKp9A377-gTccalnI97vZhQiiZYMyMZz9CFhY
