### ISSUE TITLE
[docdb] Add a limit on number of metrics for the prometheus metrics endpoint

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8807]
In cases with large numbers of tables, we can get to a point where we generate hundreds of MB of data on the `/prometheus-metrics` endpoint, which could be a problem both for the TS, but also for Prometheus and the Platform that is querying this.

We should add some form of http arg to limit the payload size, or max number of tables to query for, etc. cc @iSignal @kmuthukk

**Comment by tedyu** [comment]
I wonder if the following helps:

[#9090] Support gzipped responses in webserver

The compression ratio : 114864 bytes of /metrics output was compressed to 7KB

**Comment by bmatican** [comment]
that's a nice 20x compression there @tedyu :)

I think that'd be awesome, but probably still good to have a safety net here, in case we can't enable compression by default from Platform / for community users.

one thing I was discussing with Kannan was maybe a simple fix could be
- always show generic metrics, like `server` level ones
- for table (aggregated from tablets), put a limit on number of tables to show, but show all the metrics for these tables
- maybe we can default this limit in code / gflag, to something like 500, but allow an http param to set it to something else

**Comment by iSignal** [comment]
Makes sense @bmatican!

**Comment by iSignal** [comment]
One clarification @bmatican : we use the metric - rocksdb_current_version_sst_files_size - by table id to understand db size, so we would still want this metric to be prioritized if possible. If you don't want to complicate this logic, we can add a  regex query param for 'absolutely want to have' metrics and let caller decide this.

**Comment by amitanandaiyer** [comment]
@bmatican @iSignal I think prioritizing rocksdb_current_version_sst_files_size at this layer/diff is probably the wrong place to do it.

Can platform do 2 calls? one with `?metrics= rocksdb_current_version_sst_files_size` with no limit set; and one with `?num_tables=500` It seems odd to be hard-coding platform/prometheus policies into docdb/metrics code.
