### ISSUE TITLE
[platform]  requesting faster backups.

### ISSUE THREAD

**Issue by fsayedyb** [yugabyte/yugabyte-db#8811]
Jira Link: [DB-1674](https://yugabyte.atlassian.net/browse/DB-1674)
Description: requesting faster backups.

Infrastructure: All
Feature Request:  The gating factor on backup time is the SHA256 checksum, can this be adjusted to something more CPU friendly

**Comment by ymahajan** [comment]
- SHA256 takes a large part of the maintenance window and both backup and restore time is affected. 

- We should explore if CRC checksum (or any other approaches)could do the job here. 

- Also we should make checksumming optional so that customers who don't need it can simply disable it.

**Comment by hsiaosu-yb** [comment]
May be related to this one:

https://github.com/yugabyte/yugabyte-db/issues/8894
