### ISSUE TITLE
[platform] Added curly Bracket on the update command 

### ISSUE THREAD

**Issue by fsayedyb** [yugabyte/yugabyte-db#8812]
Description: added curly brackets

Infrastructure: AWS 

Documentation Bug: Added curly Bracket on the update command in page https://docs.yugabyte.com/latest/admin/yb-admin/#alter-universe-replication

instead of yb-admin -master_addresses <master-addresses> \
alter_universe_replication <producer_universe_uuid> \
{ \
set_master_addresses <producer_master_addresses> | \
add_table <table_id>[, <table_id>...] | \
remove_table <table_id>[, <table_id>...] \
}

it should be

instead of yb-admin -master_addresses <master-addresses> \
alter_universe_replication <producer_universe_uuid> \
set_master_addresses <producer_master_addresses> | \
add_table <table_id>[, <table_id>...] | \
remove_table <table_id>[, <table_id>...]

**Comment by polarweasel** [comment]
Linked to PLAT-498
