### ISSUE TITLE
Track number of rows backfilled as part of the backfill job

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#8817]
A common question from customers during long backfill is to find out how much of the data has been backfilled.

We have VLOG lines on a per-tablet/rpc basis that prints out the number of rows backfilled in the particular RPC. 

It will be good if this information is sent back to the master as part of the RPC response; and integrated into the backfiill-job tracking/mechanism so that the user can get an overall picture; seeing :7000/tasks without resorting to VLOGS.

**Comment by ConcurrencyPractitioner** [comment]
Hi Amit! I have done some investigations into this, and I wanted to ask if I can take over this issue.

**Comment by amitanandaiyer** [comment]
@ConcurrencyPractitioner Richard, that will be great.

You can look at this as a 2 part solution ...

1) part 1 can add the number of rows backfilled as a field to the RPC/response and allow the information to be collected/aggregated/printed/shown at the master.

2) can be persisting this information (similar to backfilled_until_ ) in the master's table/tablet-info pb, so that it is persisted across master failovers. 

Feel free to ping me if you have any questions or want to discuss any of the steps further.

**Comment by ConcurrencyPractitioner** [comment]
Landed a diff which fixed this issue:
https://phabricator.dev.yugabyte.com/D11972
