### ISSUE TITLE
[docs] Fault tolerance page needs to be updated

### ISSUE THREAD

**Issue by aravind-nallan-yb** [yugabyte/yugabyte-db#8818]
Fault tolerance implementation has changed and the [docs](https://docs.yugabyte.com/latest/architecture/docdb-replication/replication) need to be updated. Please see discussion in https://yugabyte.slack.com/archives/C4K1838GL/p1623109168332500

Key update: For RF=3, and a 3 zone deployment, when zone 3 fails, that replica is not rebalanced onto remaining zones.

Also, i think we need to clarify what part of the replication config the user specifies and what is automatic. Maybe some discussion of placement info and how it's set and what happens under various conditions will be useful.

**Comment by ddhodge** [comment]
Page subsequently rewritten closing this
