### ISSUE TITLE
[Docs] Inconsistency in xCluster replication docs

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#8829]
Marko Rajcevic  10:24 AM
Some confusion on the docs regarding Read Replicas and eventual consistency. The table below under multi-region deployments shows the consistency level for read replicas set to “eventual consistency” although within the read replica docs there is a section specifically calling out that read replicas (timeline-consistent) are different than eventual consistency. 

Believe i found an inconsistency in our xCluster replication docs. We call out transactional atomicity as a limitation and then go on to call out atomicity of transactions as a transactional guarantee. Seems contradictory. 

[https://docs.yugabyte.com/latest/architecture/docdb-replication/async-replication/#root](https://docs.yugabyte.com/latest/architecture/docdb-replication/async-replication/#root) 

alan: 1 hour ago
the guarantee is for single-shard only — not distributed transactions

**Comment by ddorian** [comment]
This has already been fixed in the docs.
