### ISSUE TITLE
[Platform] Do not reverse the logs

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#8836]
We attempt to print log in reverse with most recent log line first. The implementation however does not seem to discriminate between line-feed between log lines and the ones within log lines.

This leads to impossible to read stack traces. We already have java logs that contain java stack traces that contain python logs that contain python stack traces. Breaking this on new line and reversing it creates a situation where it is impossible to tell what's going on.  

![image](https://user-images.githubusercontent.com/73500297/121443966-61754800-c943-11eb-82dc-61fc842e67a4.png)

Python trying to be helpful with 
```
Traceback (most recent call last):
```
is interesting. Because not only did we reverse the stack trace; the stack trace precedes that line.

**Comment by sunilsutarDCE** [comment]
@sb-yb : Removed reversing logic from UI .
