### ISSUE TITLE
[Platform] Stop + release node action does not wait for tablets to be moved away from tserver

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#8838]
Repro steps:
1. Create a 4 node cluster across 3 AZs
2. Stop Node n1
3. Release Node n1
4. Check the leader master / tserver UI and see that tablets are still assigned to the released node

This will be fixed in 15 mins after the default timeout kicks in but in general, this behavior is inconsistent with Remove Node which waits for data to be moved off the node when possibble.

https://github.com/yugabyte/yugabyte-db/issues/4583 also describes another issue with this flow @Arnav15 @rao-vasireddy 

Maybe we should disallow Stop -> Release and instead always insist on Stop -> Remove -> Release? 

![Web capture_9-6-2021_20570_portal ubuntu dev yugabyte com](https://user-images.githubusercontent.com/8207010/121463186-65ff2800-c966-11eb-905b-a93cfe93222c.jpeg)
![Web capture_9-6-2021_205634_portal ubuntu dev yugabyte com](https://user-images.githubusercontent.com/8207010/121463189-67c8eb80-c966-11eb-9957-92f794c25384.jpeg)

**Comment by hsiaosu-yb** [comment]
Need discussion and PM input.  Please discuss with Yogesh.

**Comment by streddy-yb** [comment]
Addressed as part of https://github.com/yugabyte/yugabyte-db/commit/830d2863274988466b0ce90752c409ecdbefbbe9
