### ISSUE TITLE
[YSQL] Treatment of spaces for ORDER BY in CHAR table is platform-dependent

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#885]
Consider our `pg_regress` test `yb_char.sql`:
```sql
CREATE TABLE yb_charn_in_value(f1 char(4));
INSERT INTO yb_charn_in_value(f1) VALUES ('a');
INSERT INTO yb_charn_in_value(f1) VALUES ('ab');
INSERT INTO yb_charn_in_value(f1) VALUES ('abc');
INSERT INTO yb_charn_in_value(f1) VALUES ('abc ');
INSERT INTO yb_charn_in_value(f1) VALUES (' abc');
INSERT INTO yb_charn_in_value(f1) VALUES ('abcd');
INSERT INTO yb_charn_in_value(f1) VALUES ('abcde');
INSERT INTO yb_charn_in_value(f1) VALUES ('abcd    ');
SELECT * FROM yb_charn_in_value ORDER BY f1;
```
Output on Mac platform (Release build)
```
  f1
------
  abc
 a
 ab
 abc
 abc
 abcd
 abcd
(7 rows)
```
Output on CentOS platform (Release build) (produces expected output)
```
  f1
------
 a
 ab
 abc
 abc
  abc
 abcd
 abcd
(7 rows)
```
## UPD

This issue is reproducible with original PostgreSQL 11 itself - its behavior is platform-dependent and differs between macOS and CentOS

**Comment by kmuthukk** [comment]
Thanks for confirming/comparing to base behavior @frozenspider. So looks like we should customize the test to expect different results for these cases (in our CentOS & MacOS environments).

**Comment by m-iancu** [comment]
Should be fixed by https://github.com/yugabyte/yugabyte-db/commit/5841142116ec019bcc8923386a86c71038030513. See also #1559.
