### ISSUE TITLE
[Platform] yugaware.backup table metadata does not contain table name for full or single table backups

### ISSUE THREAD

**Issue by fsayedyb** [yugabyte/yugabyte-db#8857]
Description: yugaware.backup table metadata does not contain table name for full or single table backups

Infrastructure: ALL

Feature Request: request ability to identify table name in backup 
Two backups are shown below (performed by Platform) the first in the list is single table backup, the second was a full backup. It is impossible to tell what the backup contains...

yugaware=# select * from backup order by create_time desc;

2177ea8e-ae86-431d-a0bb-2fce458f836d | 1d794436-b6ec-42af-8077-050ba5418ea8 | {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"ae03046a-a01d-4771-a739-b44cec461da7","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":f
alse,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9
042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"yugabyte","tableName":null,"tableUUID":null,"sse":false,"storageConfigUUID":"7898ecb4-0622-4dda-ae2b-63cdec907bee","kmsConfigUUID":null,"sto
rageLocation":"s3://yugabytepoc/univ-ae03046a-a01d-4771-a739-b44cec461da7/backup-2021-06-08T11:41:24-1791296816/keyspace-yugabyte","actionType":"CREATE","backupType":"PGSQL_TABLE_TYPE","tableNameList":null,"tableUUIDList":null,"backupList":null,"schedulingFrequency":0,"cronExpression":null,"timeBe
foreDelete":0,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":8,"scheduleUUID":null} | Completed | 2021-06-08 11:41:24.239 | 2021-06-08 11:47:42.998 |

| |
e57cddae-bb78-4bf6-a4a5-b234fa3fb612 | 1d794436-b6ec-42af-8077-050ba5418ea8 | {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"ae03046a-a01d-4771-a739-b44cec461da7","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":f
alse,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9
042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"yugabyte","tableName":null,"tableUUID":null,"sse":false,"storageConfigUUID":"7898ecb4-0622-4dda-ae2b-63cdec907bee","kmsConfigUUID":null,"sto
rageLocation":"s3://yugabytepoc/univ-ae03046a-a01d-4771-a739-b44cec461da7/backup-2021-06-07T17:00:48-10392190/keyspace-yugabyte","actionType":"CREATE","backupType":"PGSQL_TABLE_TYPE","tableNameList":null,"tableUUIDList":null,"backupList":null,"schedulingFrequency":0,"cronExpression":null,"timeBefo
reDelete":0,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":8,"scheduleUUID":null} | Completed | 2021-06-07 17:00:48.412 | 2021-06-07 17:07:09.891 |

**Comment by hsiaosu-yb** [comment]
Raised by customers, need to fix this ASAP -- in 2.7 first and then backport to 2.6.

**Comment by vpatibandla-yb** [comment]
@fsayedyb @aayush-yb @hsiaosu-yb Based on the backup entry in the table, I see that the backup was requested on a YSQL DB. As we are aware that YSQL is a relational DB and a table in a relational DB can reference columns in another table. So, a single table backup is not allowed on a YSQL table to preserve the relations between entities. What we do instead is, we take a backup of the entire keyspace. This is something that we are aware of. This should be made more clear on the UI as it can be very misleading. One way to do this is to list the tables at a keyspace/namespace level and only support taking backups at a keyspace/namespace level in the case of YSQL DB.

Raised a new issue to fix this: #9564

**Comment by mheer9** [comment]
@fsayedyb the above explanation makes sense, the new fix #9564 should make things clearer.
This GHI 8857 can be closed
