### ISSUE TITLE
[Jepsen] Transient network partitions can disable the cluster indefinitely

### ISSUE THREAD

**Issue by aphyr** [YugaByte/yugabyte-db#886]
Splitting this out from #821, since it's a distinct issue from slow recovery: in 1.1.9.0 through 1.1.13.0-b2, network partitions can cause master nodes to get "stuck". If a stuck master is the leader, no node in the cluster can make progress, disabling the cluster. Healthy master nodes will not take over as leaders automatically, though they can be induced to take over through further network partitions. Given long enough, all master nodes can become stuck, and the cluster will not service another request until those nodes are rebooted.

For instance, in [this test](http://jepsen.io.s3.amazonaws.com/analyses/yugabyte-db-1.1.9/20190221T100947-stuck.zip), nodes n1 and n2 both got stuck trying to open the catalog table; n3 was healthy during the first recovery period, but declined to take over as leader. The second wave of partitions forced a leader election which made n3 the leader, and operations resumed.

![latency-raw 9](https://user-images.githubusercontent.com/3748/53213710-01462500-3618-11e9-85ef-9a4f1ca04d08.png)

**Comment by aphyr** [comment]
@amitanandaiyer has a patch in 1ae0df3 which he thinks should fix this; I'll confirm once a build is ready! :-)

**Comment by kmuthukk** [comment]
Thx @aphyr - will get a build which addresses the unavailability issues reported in #821, #886 as as well the occasional memory issue due to use of libbacktrace (#862)

**Comment by aphyr** [comment]
It's looking like this is fixed in 1.1.15-b16. :)
