### ISSUE TITLE
[YB-Docs] example on "create schema" page fails

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#8863]
Jira Link: [DB-2056](https://yugabyte.atlassian.net/browse/DB-2056)
Following example for "Create a schema and an object within that schema." section fails ([on this page](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_schema/#root))

```sql
postgres=# CREATE SCHEMA branch
postgres-#                CREATE TABLE dept(
postgres(#                    dept_id INT NOT NULL,
postgres(#                    dept_name TEXT NOT NULL,
postgres(#                    PRIMARY KEY (dept_id)
postgres(#                );
ERROR:  CREATE SCHEMA with elements not supported yet
LINE 2:                CREATE TABLE dept(
                       ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
```

**Additional problems...**

Step 1, "Create a schema" should be `IF NOT EXISTS` (not `EXIST`)

And, this step fails:

```sql
yugabyte=# CREATE SCHEMA branch AUTHORIZATION john;
ERROR:  schema "branch" already exists
```

**Comment by bllewell** [comment]
OK. The code block shown above is not the only one that causes an error. The very first (without that silly prompt) is spelled thus:

```
CREATE SCHEMA IF NOT EXIST branch;
```

Obviously this is wrong too. It should be `IF NOT EXISTS` with an `S`. I'll makse sure that _every_code block works.

**Comment by hsiaosu-yb** [comment]
This looks like a bug in Doc or DB, and definitely not a platform bug.

**Comment by polarweasel** [comment]
@hsiaosu-yb This is not (just) a doc bug, it's missing functionality in the database. But you're correct that it's definitely not a platform issue.

**Comment by bllewell** [comment]
See [Issue #10865](https://github.com/yugabyte/yugabyte-db/issues/10865) **«[YSQL] Support for CREATE SCHEMA with elements»**. It describes the same underlying product bug.
