### ISSUE TITLE
ysql: remove duplicate truncate request to indexes

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#8869]
In catalog manager `catalog_manager.cc`, truncate table recurses to the indexes.  Yet, in postgres `ybccmds.c`, truncate table recurses to the indexes as well.  This results in duplicate truncate requests for indexes, as seen in master and tserver logs.

Get rid of the index handling on postgres side.  However, when doing that, be aware of issue #8774: client `client-internal.cc` should make sure that truncate table is considered done when the indexes are done truncating as well, not just when the table is done truncating.

**Comment by tedyu** [comment]
For colocated tables , in ybccmds.c:
```
        /* Create table-level tombstone for colocated tables / tables in tablegroups */
        HandleYBStatus(YBCPgNewTruncateColocated(MyDatabaseId,
```
while in CatalogManager::TruncateTable():
```
  LOG_IF(WARNING, IsColocatedUserTable(*table)) << "cannot truncate a colocated table on master";
```

**Comment by jaki** [comment]
@tedyu, I wasn't referring to colocated tables, and I don't think it's a problem for colocated tables.  That check shouldn't get hit unless you're doing an upgrade from 2.0ish long time ago.  See `ybccmds.c` for how master RPC is avoided for colocated truncate.

This issue is for non-colocated tables.

**Comment by tedyu** [comment]
Ack on the scope for this issue.
