### ISSUE TITLE
[Docs] yugabyte.com not in results of google question "SST in Yugabyte?"

### ISSUE THREAD

**Issue by gautamsomani** [yugabyte/yugabyte-db#8876]
I [googled](https://www.google.com/search?client=firefox-b-d&q=SST+in+yugabyte) what are SST files in yugabyte, and I did not get a proper and full-fledged answer in the top 3 result links. Should we include micro articles in our blog/doc to answer such questions on the internet? Point is that such basic info should be searchable very very easily.

Another generic question: [What are SST files ](https://www.google.com/search?client=safari&rls=en&q=what+are+SST+files&ie=UTF-8&oe=UTF-8) shows results which are related to some certificate files in Microsoft Windows. We should have YugaByte related info on top here.

[what are SST files in yugabyte](https://www.google.com/search?q=what+are+SST+files+in+yugabyte) gives some hint on what are SST files, but not a link which explains in details.

**Comment by polarweasel** [comment]
Search results seem to be significantly improved since 2021. Closing.
