### ISSUE TITLE
Raft bug fix for fully-deduped requests after a leader change (port of KUDU-1469 fix)

### ISSUE THREAD

**Issue by jmeehan16** [yugabyte/yugabyte-db#8879]
Jira Link: [DB-8064](https://yugabyte.atlassian.net/browse/DB-8064)
Currently a leader and follower could get stuck in a tight RPC loop in which the leader would repeatedly send a batch of ops that the follower already had.  The follower would fully de-dupe them, and yet the leader would never advance to the next batch.  (apache/kudu issue KUDU-1469)

This bug has been fixed in the following kudu commit, which can be ported to complete this issue (complete with added integration tests): https://github.com/apache/kudu/commit/d685747426472d428b1d071df00d112d9f775117

[DB-8064]: https://yugabyte.atlassian.net/browse/DB-8064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@Huqicheng , can you check if this is needed anymore?

**Comment by Huqicheng** [comment]
#13723 has introduced the fix of this issue
