### ISSUE TITLE
[Docs] Add a new page under Yugabyte Cloud that explains how customers can use Hasura with Yugabyte Cloud

### ISSUE THREAD

**Issue by milagiri** [yugabyte/yugabyte-db#8881]
The page should cover the two different options on the Hasura side -- 1. download and install the software in location of your choice, or 2. use Hasura Cloud.

For the Yb Cloud + Hasura Cloud story, the page should talk about the new integration between the two services.

**Comment by milagiri** [comment]
Developers who want to use Hasura can either download and install the open source software themselves (in K8s clusters, in Heroku, etc.) or they can use Hasura Cloud to get started quickly with a fully hosted experience.

Similarly, folks who want to use YugabyteDB can download and install the software themselves, or use Yugabyte Cloud.

This page should cover the ways in which customers can use Yugabyte Cloud with 1. Hasura open source software, and 2. Hasura Cloud. We are building a new integration between Hasura Cloud and Yugabyte Cloud that will greatly simplify how customers connect these two services together. The design doc for this integration is here, for reference: https://docs.google.com/document/d/1uCQw_fel8jVyuUzMEAAxnfeVm9ZQJQp9fqAW72mMwoY/edit?usp=drive_web&ouid=105508474541045454372

**Comment by ddhodge** [comment]
https://github.com/yugabyte/yugabyte-db/pull/9043 partially addresses this. Once the integration is complete, I assume the instructions for connecting YB Cloud to Hasura Cloud will need to be updated, while the Realtime Poll application example will remain basically the same. Also need content for using YB Cloud with regular (not cloud) Hasura.

**Comment by polarweasel** [comment]
@ddhodge anything further we can do here?

**Comment by polarweasel** [comment]
Closing. @milagiri please reopen if we should take this up again.
