### ISSUE TITLE
[docdb] Speedup yb_backup when dealing with many tablets

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8892]
When dealing with lower CPU nodes and many tablets, we have seen a LOT of time spent on just ssh + yb-admin, rather than the actual work of taking snapshots / checksums / copying data out.

From slack: https://yugabyte.slack.com/archives/CSPBBNBA5/p1619813548446500?thread_ts=1619804663.438600&cid=CSPBBNBA5

```
The result of the application log analysis for yb_backup run today:
   5 min: PHASE 1: Create tables (via YSQLDump) + import snapshot
 12 min: PHASE 2: Generate list of TSes for every tablet
 19 min: PHASE 3: Find all table/tablet data dirs on all TSes
 20 min: PHASE 4: Data downloading (+checksum checking)
0.3 min: PHASE 5: Snapshot restoring + clean-up
TOTAL: ~57 min
So, phases 2 & 3 can be optimized via creating new command for yb-admin.
(To get info for replicas via one step. Not as now: 1 tablet = 1 yb-admin call.)
```

**Comment by bmatican** [comment]
Maybe one high level thing we should do here is also add timing information into the output of yb_backup, so we don't have to just parse logs to figure stuff out...

That way, as we optimize things, we can get a clear signal of how much time was spent where and how much have we saved.

**Comment by hulien22** [comment]
Thoughts for combining phase 2/3 together:
- We would need to introduce a new yb-admin command (eg `get_tablet_restore_info`) that supports taking a list of tablets. This yb-admin command would need to:
1. Get the list of current tservers where this tablet is active
2. Get the list of directories on these tservers where the tablet is
3. Print this info in an easily readable format (likely some json output would work)

- We can then replace `find_tablet_replicas` and `generate_snapshot_dirs` in `yb_backup.py` with this new yb-admin command
  - note that we may still want to do some batching here if there are a large number of tablets (in case we overload the master)?

**Comment by hulien22** [comment]
For phase 4:
There's a note here (https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.imap)

> `imap`(func, iterable[, chunksize])
> A lazier version of `map()`.
> The chunksize argument is the same as the one used by the `map()` method. For very long iterables using a large value for chunksize can make the job complete **much** faster than using the default value of `1`.

(emphasis is from the docs, so the "**much** faster" note seems intriguing) 
Might be worth trying this with `chunksize = number of tablets / parallelism` or something similar?

**Comment by bmatican** [comment]
@hulien22 should we maybe close this and file a new one just with the suggestions that are still relevant?

**Comment by hulien22** [comment]
Agreed, will close this and make a new issue for just focussing on improving the phase 2/3 steps as we should still improve that. (#11564)
