### ISSUE TITLE
[docdb] For yb_backup checksums change to xxh64 from sha256

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8893]
Jira Link: [DB-618](https://yugabyte.atlassian.net/browse/DB-618)
should be about 3x faster / less cpu intensive, just TBD if we have access to it by default, or we'd need Platform support to pre-package it somehow

cc @OlegLoginov

**Comment by jaki** [comment]
Also consider xxhash or other fast, collision-resistant checksums, like murmurhash, which we already use in the codebase.

**Comment by Vars-07** [comment]
Resolved as part of this commit https://github.com/yugabyte/yugabyte-db/commit/2b8d01c4023e279b98a7aee3349c2caf2e1f7d91
