### ISSUE TITLE
[ysql] Orafce compilation failed 'sqlparse.h' file not found

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#8897]
```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/postgres/third-party-extensions/orafce/plvlex.c:24:10: fatal error: 'sqlparse.h' file not found
#include "sqlparse.h"
         ^~~~~~~~~~~~
1 error generated.
Input files:
  build/debug-clang-dynamic-ninja/postgres_build/third-party-extensions/orafce/plvlex.c
Output file (from -o): plvlex.o
\------------------------------------------------------------------------------- cc 
```
@ramsrivatsa for more details

**Comment by frozenspider** [comment]
Shouldn't we simply add it to Git instead of .gitignoring them? Or does the content differ between architectures?
cc @ramsrivatsa @jaki

**Comment by jaki** [comment]
That's not good practice.  Just like how we don't check in binaries to git.  It's duplicate information and takes up disk space that's written to (pretty much) immutable history, so we can't get rid of the garbage in the future.  Only the source files should be checked in, and the build process should be responsible for generating the files.

See also issue #2316.

**Comment by ramsrivatsa** [comment]
@jaki 
1. ./yb_build.sh --clean (optional)
2. Bring in the old sqlparse.c and sqlscan.c to src/postgres/third-party-extensions/orafce (if they are not already present)
3. ./yb_build.sh --rebuild-postgres
Going to look into why those generated files were still in my src even after commit 78f55f44694ddc385786770a9424edc8f1edf3ba removes them.
The easy fix for people still with the problem: git clean -x src/postgres/third-party-extensions/orafce
