### ISSUE TITLE
[Platform] Asia Pacific (Mumbai) Region should now have 3 availability zones

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#8911]
Need to add availability zone **ap-south-1c** into the platform to make the region capable of sustaining HA within a region for a 3 node cluster. 

Was on a user call helping them set up a Platform Trial and they were able to launch nodes in ap-south-1a and ap-south-1b, however ap-south-1c was not available. They had to have 2 nodes in one of the availability zones.

**Comment by hsiaosu-yb** [comment]
@streddy-yb to follow up with @kkg-yb

**Comment by akjn-yb** [comment]
@mrajcevic01 `ap-south-1c` AZ was already added in this commit: fdb17e25b78b4b27f9fc79bc929d3e59e848b160

I also tried creating AWS Provider config with `ap-south1` as the region, both locally and on http://portal.dev.yugabyte.com. It is able to create the provider with all 3 AZ as expected:
![image](https://user-images.githubusercontent.com/83458721/122867138-b010e200-d346-11eb-8573-001bdee7ffc4.png)


I also tried creating a universe with the above config, and was able to create it successfully:

![image](https://user-images.githubusercontent.com/83458721/122869171-81e0d180-d349-11eb-970b-08a68b0fef5e.png)


This seems to be some version issue, can you please check once on that?

Cc: @kkg-yb @Arnav15

**Comment by mrajcevic01** [comment]
Hi @akjn-yb . I had tried both from the dev console you mentioned above as well as the Platform users console. Their console is v2.4.4 so it makes sense why they were not able to see it. Seems that this is only backported to v2.5.3. However our dev console is up to date v2.7.2. I am assuming we would need to re-create the configuration in order for the new AZ to be available? Seems that in your case you added a new config and that seemed to have the update. 

![image](https://user-images.githubusercontent.com/38478518/122934757-d0886e80-d33d-11eb-9d32-4c7e1fbb1ee0.png)

**Comment by akjn-yb** [comment]
@mrajcevic01 Yes, in my case, I added a new provider config which had the commit's changes and hence it worked fine for me. Re-creating the configuration should make `ap-south-1c` AZ available, provided the version that is being used has the above-mentioned commit's changes.

**Comment by akjn-yb** [comment]
@mrajcevic01 Closed by f4f3dfb8ab5bd47a914ebca9cd401b86e989d78a

**Comment by streddy-yb** [comment]
Dup of #7371
