### ISSUE TITLE
CompactionTest_CompactionWithSomeUserFrontiers is flaky

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#8916]
From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F96978%2Fartifact%2Fbuild%2Fasan-clang7-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__compaction-test%2FCompactionTest_CompactionWithSomeUserFrontiers.log?class=CompactionTest&name=CompactionWithSomeUserFrontiers :

```
E | 8.412929 | 25173 | tablet_peer.cc:238 | A memtable with no frontiers set found when deciding what memtables to flush! This should not happen. Stack trace:
-- | -- | -- | -- | --
1550 | @ 0x7f3e5d2aa69e operator() (src/yb/tablet/tablet_peer.cc:238)
```
This seems to be related to the test setting TEST_disable_adding_user_frontier_to_sst to true.

**Comment by tedyu** [comment]
cc @jmeehan16

**Comment by jmeehan16** [comment]
Thanks for the tag.  This is a dupe of existing issue [8890](https://github.com/yugabyte/yugabyte-db/issues/8890)

**Comment by tedyu** [comment]
hmm. #8890 says tsan - while the above failure was in asan.

I will close this once your fix is committed (hopefully silencing the asan as well).

**Comment by jmeehan16** [comment]
^^ Good point, the above issue is for asan rather than tsan.  The source of the problem was the same, commit [42d0b0d](https://github.com/yugabyte/yugabyte-db/commit/42d0b0d3b3fd6a48a26aa9ef720e2078cb7dc11c) resolves the issue.
