### ISSUE TITLE
[Platform] Allow ReadOnly and BackupAdmin roles to change their password. 

### ISSUE THREAD

**Issue by ymahajan** [yugabyte/yugabyte-db#8921]
Created users with readonly and backupadmin roles on YB platform and when the user login as readonly or backupadmin they can't change their passwords. Only Admin user can change their password on YB platform. All roles/users should be allowed to change their password.

**Comment by Arpit-yb** [comment]
**Steps followed to validate**

1. Created a ReadOnly user
2. Logged in as the readonly user
3. Profile -> change password 
4. Logged in with the new password(Success)
5. Log out and login as the superAdmin
6. Create a BackupAdmin
7. Followed steps 2-5 for BackupAdmin
