### ISSUE TITLE
Docs gap - Call out the need of reset universe version for any action taken outside the ui

### ISSUE THREAD

**Issue by ymahajan** [yugabyte/yugabyte-db#8923]
Any action taken outside of the ui, you need to reset the universe version. If you don't do this you get an error - "Universe version does not match cluster config version". 

We already covered this in the context of xReplication setup  - https://docs.yugabyte.com/latest/deploy/multi-dc/2dc-deployment/#enable-universes-in-platform
The API call mentioned in that doc is for resetting the universe version. We need to mention this in all the relevant places in our docs.

**Comment by polarweasel** [comment]
@ymahajan is this API call still necessary?

**Comment by polarweasel** [comment]
Related to #10678

**Comment by lizayugabyte** [comment]
@ymahajan is this API call still necessary?

**Comment by lizayugabyte** [comment]
@ymahajan Please let me know if this still needs to be documented.
Since the doc team hasn't been able to receive the answer for more than 3 months, we will assume that the problem no longer exists and the ticket will be closed.

**Comment by lizayugabyte** [comment]
Closing this issue, because there's no response from the reporter.
