### ISSUE TITLE
[YSQL] JDBC call getMetaData().getCatalogs() fails to return databases other than "postgres"

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#893]
When trying to get a list of databases from JDBC in YSQL (version 1.1.15.0-b1), typically applications will typically call the following code:
```

ResultSet rs = connection.getMetaData().getCatalogs();
String postgres_ybdemo_database = "ybdemo_database";
boolean ybdemo_exists = false;
while (rs.next()) {
      String catalogs = rs.getString(1);
      LOG.info(String.format("Found database name %s ...", catalogs));
      if (postgres_ybdemo_database.equals(catalogs)) {
         LOG.info(String.format("Database %s already exists", postgres_ybdemo_database));
         ybdemo_exists = true;
      }
    }
    if (!ybdemo_exists) {
        connection.createStatement().execute(String.format("CREATE DATABASE %s", postgres_ybdemo_database));
    }
```
When connecting to YSQL, it seems to only return "postgres" and thus if you are checking for the name of the target database, it will not be found and it will try to create that database. This code falls through and throws SQLException because it already does exist.

If I change the code to use a prepared statement:

```
PreparedStatement ps = connection.prepareStatement("SELECT datname FROM pg_database WHERE datistemplate = false;");
    rs = ps.executeQuery();
```
Everything works fine.

**Comment by mbautin** [comment]
@robertpang would you mind taking a look at this issue?

**Comment by robertpang** [comment]
The same happens to PostgreSQL also. This is the expected behavior of the `getCatalogs()` API. It always returns only the current database (catalog) because PostgreSQL does not support connecting to multiple databases from a single connection.

https://jdbc.postgresql.org/development/privateapi/org/postgresql/jdbc/PgDatabaseMetaData.html#getCatalogs--
