### ISSUE TITLE
[Jepsen] Read skew & data corruption in normal operation

### ISSUE THREAD

**Issue by aphyr** [YugaByte/yugabyte-db#894]
In YugaByte DB 1.1.9.0 CE, in healthy clusters without faults, reads routinely fail to observe snapshot isolation: transactions could observe part, but not all, of another transaction's effects. It appears that this is not limited to read-only transactions: update transactions could take information based on inconsistent reads and write it back to tables, causing logical corruption of state.

For instance, in [this Jepsen test](http://jepsen.io.s3.amazonaws.com/analyses/yugabyte-db-1.1.9/20190222T115901-read-skew.zip), a simulated system of bank accounts containing $100 fluctuated between $95 and $154 in what appears to be a random walk. These variations can occur quickly: we've observed values doubling in under 2 minutes.

You can reproduce this behavior with Jepsen d4cf55ada5764a7ddca2f296c708b6acec134586 by running something like:

```
lein run test -o debian --version 1.1.9.0 --concurrency 2n --time-limit 60 --test-count 1 -w bank
```

This problem was fixed by 90bc062080063b399525fb40663e0b24a8a84da5, which was released in 1.1.10; we have not observed read skew since.

**Comment by kmuthukk** [comment]
Fixed in 1.1.10 (https://github.com/YugaByte/yugabyte-db/commit/90bc062080063b399525fb40663e0b24a8a84da5)
