### ISSUE TITLE
[docdb] Master-side UI Display of Table Specific Data Size

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#8943]
Community Slack user had a question regarding how to find the exact size of any table ycqlsh shell or tserver-UI.

Context - https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1623851330364200

_Here is where we stand today_:

- No support for this through ycqlsh
- 2 types of support through the UI: (1) Per tablet server, which you can see on the tables tab of the tserver UI, but you’d have to aggregate this over all tablet servers. (2) Centrally, on the master, we only report full disk usage on a tserver, but not broken down per table.

_Where we want to be_:

@bmatican has brought up the point that we now report data sizes per tablet, from tserver > master. Thus giving us the ability to have some UI that reports data per table on this level. This issue is to keep track of building out this master-side display.

**Comment by bmatican** [comment]
We now flow the per tablet data sizes from the tserver to the master, via heartbeat. With this, we should be able to construct a debug UI where we show the size per table, in the cluster. We'd have to note that the data is N way replicated, depending on RF.

cc @mikhpolitov for some pointers on how we store this data on the master, in memory

**Comment by mikhpolitov** [comment]
Tablets data sizes are available under TabletReplica as drive_info. To get all replicas information call TabletInfo::GetReplicaLocations.

**Comment by mengchoontan** [comment]
Hi, I am a new contributor - can I attempt to help with this ?

**Comment by bmatican** [comment]
hey @mengchoontan , definitely!

the main code you'll likely want to change is in `src/yb/master/master-path-handlers.cc`, for the master UI

you can use the pointers that @mikhpolitov shared above, for where to get the size data from! let us know if you need any more input / help

**Comment by mengchoontan** [comment]
> hey @mengchoontan , definitely!
> 
> the main code you'll likely want to change is in `src/yb/master/master-path-handlers.cc`, for the master UI
> 
> you can use the pointers that @mikhpolitov shared above, for where to get the size data from! let us know if you need any more input / help

Hi @bmatican I had a stab at it and added code here : https://github.com/yugabyte/yugabyte-db/blob/7d4eebb02e0da853fe0086513b4f42b5f95a4dc9/src/yb/master/master-path-handlers.cc#L917
```

   // MC - define new var to store table size
    string table_size = "TABLE SIZE";

    LOG(INFO) << "MC TabletReplica info "; // MC

    TabletInfos tablets;
    table->GetAllTablets(&tablets);

    for (const auto& tablet : tablets) {

      auto locations = tablet->GetReplicaLocations();
      vector<TabletReplica> sorted_locations;
      AppendValuesFromMap(*locations, &sorted_locations);
      // std::sort(sorted_locations.begin(), sorted_locations.end(), &CompareByHost);
      
      for(std::vector<TabletReplica>::iterator it = sorted_locations.begin(); it != sorted_locations.end(); ++it) {
        
        std::ostringstream oss;
        //oss << ( it->drive_info.sst_files_size + it->drive_info.wal_files_size );
        oss << it->drive_info.wal_files_size;
        string drive_info_str = "";

        drive_info_str += oss.str();

        LOG(INFO) << "Size: " << drive_info_str;
        LOG(INFO) << "Path: " << it->drive_info.ts_path;
        LOG(INFO) << "it: " << it->ToString();
      }
```
I am under the impression that I will be able to get the **total_space_used** or ( **drive_info.sst_files_size + drive_info.wal_files_size** ) to determine the tablet size. 

However, the debug output shows the following, which suggest that both the **drive_info.wal_files_size** or **total_space_used** are all zero size? 

```
I0628 17:31:48.267112 82853888 master-path-handlers.cc:950] Size: 0
I0628 17:31:48.267143 82853888 master-path-handlers.cc:951] Path: /Users/admin/yugabyte-data/node-1/disk-1/yb-data/tserver/data
I0628 17:31:48.267169 82853888 master-path-handlers.cc:952] it: { ts_desc: bb0feac6de5a4c74bf00795b05d6c54e, state: RUNNING, role: FOLLOWER, member_type: VOTER, should_disable_lb_move: 0, total_space_used: 0, time since update: 777972ms }
I0628 17:31:48.267196 82853888 master-path-handlers.cc:950] Size: 0
I0628 17:31:48.267210 82853888 master-path-handlers.cc:951] Path: /Users/admin/yugabyte-data/node-3/disk-1/yb-data/tserver/data
I0628 17:31:48.267225 82853888 master-path-handlers.cc:952] it: { ts_desc: 01255a15ee3e48058fa9e98bc48915e9, state: RUNNING, role: LEADER, member_type: VOTER, should_disable_lb_move: 0, total_space_used: 0, time since update: 777975ms }
I0628 17:31:48.267242 82853888 master-path-handlers.cc:950] Size: 0
I0628 17:31:48.267256 82853888 master-path-handlers.cc:951] Path: /Users/admin/yugabyte-data/node-2/disk-1/yb-data/tserver/data
I0628 17:31:48.267271 82853888 master-path-handlers.cc:952] it: { ts_desc: fb89af96982d4a1f8401ad035f67e341, state: RUNNING, role: FOLLOWER, member_type: VOTER, should_disable_lb_move: 0, total_space_used: 0, time since update: 777972ms }
I0628 17:31:48.267289 82853888 master-path-handlers.cc:950] Size: 0
I0628 17:31:48.267303 82853888 master-path-handlers.cc:951] Path: /Users/admin/yugabyte-data/node-1/disk-1/yb-data/tserver/data
I0628 17:31:48.267316 82853888 master-path-handlers.cc:952] it: { ts_desc: bb0feac6de5a4c74bf00795b05d6c54e, state: RUNNING, role: FOLLOWER, member_type: VOTER, should_disable_lb_move: 0, total_space_used: 0, time since update: 782597ms }
```
Could you provide some pointers to me ?

**Comment by mikhpolitov** [comment]
Hi, @mengchoontan
> I am under the impression that I will be able to get the **total_space_used** or ( **drive_info.sst_files_size + drive_info.wal_files_size** ) to determine the tablet size.
> 
> However, the debug output shows the following, which suggest that both the **drive_info.wal_files_size** or **total_space_used** are all zero size?
Did you generate any data for table? otherwise it is looks normal.

You can check size on tserver page as: Tablets -> [Tablet Id] -> RocksDB.

**Comment by mengchoontan** [comment]
Hi @mikhpolitov ,
Yes I did generate some data - I can see that from here 
https://raw.githubusercontent.com/mengchoontan/public/375f897e1aa1ffe9751d29c1cfe62011513629ba/Snip20210630_1.png

However, when checking the tserver pages, it is shown as empty
[https://raw.githubusercontent.com/mengchoontan/public/375f897e1aa1ffe9751d29c1cfe62011513629ba/Snip20210630_2.png](https://raw.githubusercontent.com/mengchoontan/public/375f897e1aa1ffe9751d29c1cfe62011513629ba/Snip20210630_2.png)
[https://raw.githubusercontent.com/mengchoontan/public/375f897e1aa1ffe9751d29c1cfe62011513629ba/Snip20210630_3.png](https://raw.githubusercontent.com/mengchoontan/public/375f897e1aa1ffe9751d29c1cfe62011513629ba/Snip20210630_3.png)

Is this the normal behaviour ?

**Comment by mikhpolitov** [comment]
Hi, @mengchoontan 
Yes, it is normal. You need generate over 128MB data to have SST files.

**Comment by mengchoontan** [comment]
Thanks @mikhpolitov ! If the approach I did is correct, @bmatican how would you like me to show the data ? ie where on the master UI should I add/show this information ?

**Comment by bmatican** [comment]
@mengchoontan two things
- if you wrote data, but it was not flushed to disk yet in rocksdb, you can issue an explicit flush command, either via yb-admin (for a table), or via yb-ts-cli (for all the tablets on a server) -- this might help you see the mix of rocksdb SST files + raft WAL files
- for where to display this on the master side, maybe in the `/tables` endpoint, you can add a new column at the end, with size on disk and maybe display at least compressed vs uncompressed SST sizes there

**Comment by mengchoontan** [comment]
> @mengchoontan two things
> 
> * if you wrote data, but it was not flushed to disk yet in rocksdb, you can issue an explicit flush command, either via yb-admin (for a table), or via yb-ts-cli (for all the tablets on a server) -- this might help you see the mix of rocksdb SST files + raft WAL files
> * for where to display this on the master side, maybe in the `/tables` endpoint, you can add a new column at the end, with size on disk and maybe display at least compressed vs uncompressed SST sizes there

OK, let me do these 2 steps and I'll share again what I can come up with. Thanks for your feedback @bmatican

**Comment by bmatican** [comment]
@mengchoontan Are you still interested in this, or should we open it up for other OSS contributors?

**Comment by bmatican** [comment]
Passing this to Hari as a slightly more code starter task.

From the TS UIs, eg: `ip:9000/tablets`, you should see 3 types of data on disk being tracked, of which the last 2 are the bulk of the size on disk:
- consensus metadata (tiny file)
- consensus WAL files
- rocksdb SST files

We flow that as metadata from each tserver, to the master. Each table is split into tablets. Each tablet will have a replication factor, eg: RF=3, thus a copy of its data on each of some 3 servers. On the master, we'll need to do the aggregation for each table in the UI, eg: `ip:7000/tables` and sum up the data across each tablet, across all peers.

Feel free to reach out to either @sanketkedia or @mikhpolitov for this.
