### ISSUE TITLE
rate limit the warning "Consistency level 6 is not supported, defaulting to strong consistency"

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#895]
At the moment I believe this message is logged once per request. This needs to be rate limited to prevent log spew.

**Comment by robertpang** [comment]
Rate-limit added in commit [b63934a](https://github.com/YugaByte/yugabyte-db/commit/b63934abe8b7633e23b1f9edf76c53ff34d557f3).
