### ISSUE TITLE
[Platform] Use matching helm chart version to operate on db k8s pods

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#8950]
Currently, the platform uses whichever version of the helm chart it is bundled with (at the time of platform release) to manage all k8s universes. This behavior is bad because the platform can manage multiple versions of universes at the same time and the helm chart version used by the platform may not directly apply to the version of the universe that it is being used to manage.

This causes issues because:
1. Certain gflag settings do not apply to older universes (for ex: we want to set pgsql_proxy_bind_address to 0.0.0.0 but it causes issues in older db versrions).
2. This interacts with the way we do rolling upgrades to potentially cause unnecessary restarts during that process.

cc @bhavin192 @baba230896

**Comment by bhavin192** [comment]
https://github.com/yugabyte/yugabyte-db/commit/3fd07361dae0abab8254f39911039fa261a3c02b
