### ISSUE TITLE
[xCluster][Platform] Replication Lag sets to erroneous value when producer map is behind 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8951]
**Issue** 
This bug is related to bugs [8772](https://github.com/yugabyte/yugabyte-db/issues/8772), [7807](https://github.com/yugabyte/yugabyte-db/issues/7807) and [8325](https://github.com/yugabyte/yugabyte-db/issues/8325) 

When a customer finds themself in a situation where the producer/consumer map values are outdated, they can create an error that causes the reported replication lag to spike - stating replication is YEARS behind. 

- Yugabyte 2.4.4-b7 

**Steps to reproduce** 
1. Follow steps in github issue [8325](https://github.com/yugabyte/yugabyte-db/issues/8325)  to create the condition where cluster master addresses and replication map values are inconsistent. 
2. Ensure Replication already exists and is working for tables in a keyspace. 
3. Create new table in existing YCQL keyspace on both clusters 
4. Attempt to add the table to existing replication relationship 
```
[yugabyte@yb-dev-hamilton-prometheus-rca-timeskew-n4 bin]$ ./yb-admin -master_addresses 10.200.0.83,10.204.0.44,10.207.0.39 alter_universe_replication e3baaff6-d0cb-4543-89e6-2f502f5608b4 add_table 2001ecc2ecb848fdbf20305817c9f419 
Error: Network error (yb/util/net/socket.cc:535): Unable to alter replication for universe e3baaff6-d0cb-4543-89e6-2f502f5608b4: recvmsg got EOF from remote (system error 108)
```
5. Observe results in UI, viewing the producer/universe where the alter replication command was run 

![image](https://user-images.githubusercontent.com/8861478/122323924-e4734100-cef5-11eb-8318-c66b74fddb23.png)

**Request** 
As we work to address replication management, and provide more guardrails and tooling, we need to have the cluster ignore these types of actions, when the replication map is in an erred state. 

**Reference** 
Please see ticket [1442](https://yugabyte.zendesk.com/agent/tickets/1442)

**Comment by streddy-yb** [comment]
hi @atarw @daniel-yb - Can you check what the replication lag metric is set to when the replication configuration is broken? Once the root cause is known, let us consider backporting to 2.4 and 2.6 releases.

**Comment by CharlotteRose** [comment]
@streddy-yb - here is an update:

A customer took the following actions to remedy the situation: 

1. Removed all `null` entries reported in the `cdc_state` table, in an effort to ensure that we were not having the time skew affected by those rows

```
PRIMARY Cluster
cassandra@ycqlsh> select count(*) from system.cdc_state IF last_replication_time=null;
count
-------
0
cassandra@ycqlsh> select count(*) from system.cdc_state;
count
-------
8544
```

```
SECONDARY Cluster
cassandra@ycqlsh> select count(*) from system.cdc_state IF last_replication_time=null;
count
-------
0
cassandra@ycqlsh> select count(*) from system.cdc_state;
count
-------
8160
```

2. Once removed, the value had not adjusted and we still saw the incorrect reported lag. 
3. Still seeing erroneous lag values, we did a rolling restart, this did not address the issue. 
4. digging into things more we are seeing the following information: 

```
curl -s http://`hostname -i`:9000/prometheus-metrics | grep async_replication_sent_lag_micros 

async_replication_committed_lag_micros{export_type="tserver_export",exported_exported_instance="yb-dev-CAS-UAT-PVS-Primary-n1",exported_instance="yb-dev-CAS-UAT-PVS-Primary-n1",instance="10.89.16.37:9000",job="yugabyte",metric_type="cdc",node_prefix="yb-dev-CAS-UAT-PVS-Primary",saved_name="async_replication_committed_lag_micros",stream_id="0389cd7c397a49e093c2a68bbf813049",table_id="dbbe8f8f7a734ecd8186cccd3b6c16f8",table_name="DEFAULT_TABLE_NAME"} async_replication_committed_lag_micros{export_type="tserver_export",exported_exported_instance="yb-dev-CAS-UAT-PVS-Primary-n1",exported_instance="yb-dev-CAS-UAT-PVS-Primary-n1",instance="10.89.16.37:9000",job="yugabyte",metric_type="cdc",node_prefix="yb-dev-CAS-UAT-PVS-Primary",saved_name="async_replication_committed_lag_micros",stream_id="1a289ec076c8487a9b5602fc6f20af9e",table_id="DEFAULT_TABLE_ID",table_name="DEFAULT_TABLE_NAME"} 1624987586045080 async_replication_committed_lag_micros{export_type="tserver_export",exported_exported_instance="yb-dev-CAS-UAT-PVS- 
```


See the ticket [1442](https://yugabyte.zendesk.com/agent/tickets/1442) for uploaded information.

**Comment by nspiegelberg** [comment]
If I understand this task correctly, the replication config is incorrectly setup and that creates bogus metrics values.  While some of the replication is working, that doesn't initially seem illogical to return a bad overall value.

Are we able to unbreak this setup?  We should be able to run:
1. `alter_universe_replication <UUID> remove_table <new_table>` 
2. `alter_universe_replication <UUID> set_master_addresses <correct_addresses>`

and see the situation corrected.

**Comment by lingamsandeep** [comment]
Lot of the change that happened as part of https://github.com/yugabyte/yugabyte-db/issues/9685 addressed this, so we should no longer be seeing this issue.
