### ISSUE TITLE
[Docs] Docs (latest) for Backup Universe (YSQL) does not mention "Encrypt Backup" - Platform UI has option. 

### ISSUE THREAD

**Issue by fsayedyb** [yugabyte/yugabyte-db#8955]
missing option in documentation page  [https://docs.yugabyte.com/latest/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql/](url) Encrypt Bakup ,

Attached is screenshot from 2.7.1.1 (applies to 2.7.0 also).

![Encrypted_Backup](https://user-images.githubusercontent.com/51944662/122364164-70668680-cf51-11eb-9070-bdec22a2daa6.png)

**Comment by ddhodge** [comment]
UI has changed, closing
