### ISSUE TITLE
[Platform] Hosted Zone ID mandatory in Edit configuration for provider 

### ISSUE THREAD

**Issue by shashwat-yb** [yugabyte/yugabyte-db#8960]
Procedure to Test-
Config -> Edit Confiig -> without filling Hosted Zone ID field click Submit.

**Comment by hsiaosu-yb** [comment]
dup of edit provider ticket @streddy-yb

**Comment by streddy-yb** [comment]
https://github.com/yugabyte/yugabyte-db/issues/8570

**Comment by streddy-yb** [comment]
Let us address this as part of edit config provider support
