### ISSUE TITLE
[doc] Document Liquibase under Ecosystem Integrations

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#8964]
Neeraj is to provide a starter doc

**Comment by Sfurti-yb** [comment]
Here is [the link](https://docs.google.com/document/d/1uSi2AxydYZNN6OUvujIscMcgtCsFjuGDXe3-nqjtW4k/edit?usp=sharing) for the initial documentation on using Liquibase. Let me know in case of any questions.
