### ISSUE TITLE
[Platform]- Allow configure replication using cluster, schema and tablenames

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#8965]
Feature Request:

Description:

Currently, in Platform, if the User wants to Configure replication, they have to use "UUID." 

Suggested Solution:

Instead of "UUID," it will be easy to do it by active cluster, schema, or table name.

Reference Ticket:#1342

**Comment by ymahajan** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/8963
