### ISSUE TITLE
ysql: master fatal when row locking system table

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#8967]
Jira Link: [DB-1676](https://yugabyte.atlassian.net/browse/DB-1676)
Easily get master fatal when doing row lock select on a system table.

```sql
BEGIN;
SELECT * FROM pg_tablespace FOR SHARE;
```

output:

```
ERROR:  Not implemented: Read request with row mark types must be part of a transaction
```

master logs:

```
F0617 11:06:08.744676 21158 inbound_call.cc:163] 0x0000000004470b50 -> Call yb.tserver.TabletServerService.Read 127.0.0.11:58199 => 127.0.0.11:7100 (request call id 147): Already marked as completed
```

I tried row marks UPDATE and SHARE.  I tried tables pg_class and pg_tablespace.

keywords: row lock, FOR UPDATE, FOR SHARE, FOR NO KEY UPDATE, FOR KEY SHARE

**Comment by def-** [comment]
Also seen this with ther simple queries with a for share:
```
select  
  ref_0.collctype as c0
from 
  pg_catalog.pg_collation as ref_0
where ref_0.collcollate <> ref_0.collname
limit 138
 for share;
```

**Comment by bmatican** [comment]
I think these are all instances of #11066 probably
Sergei has an almost ready fix for that here: https://phabricator.dev.yugabyte.com/D14943

**Comment by sushantrmishra** [comment]
2.19.3 (latest master).  
I did not see FATAL in logs. 

localhost:5433 yugabyte@yugabyte=# BEGIN;
BEGIN
Time: 0.612 ms
localhost:5433 yugabyte@yugabyte=#* SELECT * FROM pg_tablespace FOR SHARE;
ERROR:  Read request with row mark types must be part of a transaction: OPERATION_NOT_SUPPORTED
Time: 16.896 ms
