### ISSUE TITLE
[Platform]- Allow to view Replication Using Table/Keyspace

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#8971]
Feature Request:

Description:

In the platform, we saw a tab "Replication" (show in the screenshot); it only shows lag, but it will be great if we have a drop-down on that page that allows us to view replication lag using a table or keyspace.
[replication_lag.pdf](https://github.com/yugabyte/yugabyte-db/files/6673069/replication_lag.pdf)

Reference Ticket:#1342

**Comment by hsiaosu-yb** [comment]
should be part of xCluster replication project.

**Comment by hsiaosu-yb** [comment]
duplicate with 8963
