### ISSUE TITLE
[docdb] Fix flakiness in AutomaticTabletSplitITest

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#8980]
We see a lot of timeouts when waiting for a split to occur in these tests, e.g.
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=AutomaticTabletSplitITest&name=AutomaticTabletSplittingMovesToNextPhase

**Comment by tedyu** [comment]
I added some log in the lambda.
The following was repeated till test failure:
```
I0619 15:43:16.978739 2498986 tablet-split-itest.cc:495] num_peers_running: 18
I0619 15:43:16.978777 2498986 tablet-split-itest.cc:496] num_peers_split: 0
I0619 15:43:16.978783 2498986 tablet-split-itest.cc:497] num_peers_leader_ready: 6
I0619 15:43:16.978794 2498986 tablet-split-itest.cc:498] num_replicas_online: 3
I0619 15:43:16.978799 2498986 tablet-split-itest.cc:499] expected_total_tablets: 7
I0619 15:43:16.978803 2498986 tablet-split-itest.cc:500] expected_split_tablets: 0
```
So this condition is not satisfied:
```
num_peers_running == num_replicas_online * expected_total_tablets
```
It seems the recent changes to tablet-split-itest.cc may not work well with phased ramp-up of tablet splitting rate
