### ISSUE TITLE
[ysql] Verify pid corresponds to postgres process before killing leftover postgres processes

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#9005]
In https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/src/yb/yql/pgwrapper/pg_wrapper.cc#L575 the tserver kills leftover postgres processes from a previous run if postmaster.pid file is still present. 

In the case where there is an unexpected shutdown of postgres/tserver, followed by a reboot of the VM or restart of the k8s pod, the postmater.pid file could have a PID but that PID no longer corresponds to a postgres process. In this case, the code ends up killing a potentially random process.

We should add a check to verify that the process name is one of the postgres binaries, for example, before killing it.

**Comment by tedyu** [comment]
https://stackoverflow.com/questions/15545341/process-name-from-its-pid-in-linux

Looks like one way is to check /proc/XX/cmdline
