### ISSUE TITLE
[YSQL] A read restart error is returned to the client for an INSERT statement of a non-existent key

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#902]
Error observed on the client:

org.postgresql.util.PSQLException: ERROR: Query error: Restart read required at: { read: { physical: 1550891414693209 } local_limit: { physical: 1550891414697601 logical: 1 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }

**Comment by mbautin** [comment]
@hectorgcr could you describe the repro steps for this issue?

**Comment by hectorgcr** [comment]
Ran the workload:
```
java -jar target/yb-sample-apps.jar --workload SqlInserts --nodes 172.151.23.73:5433,172.151.44.85:5433,172.151.60.17:5433 --num_threads_write 16 --num_threads_read 16
```

in a 3-node c4.2xlarge cluster running 1.1.14.0-b4. The workload was ran from one of the cluster nodes.
