### ISSUE TITLE
Write a Kafka Source Connector

### ISSUE THREAD

**Issue by suranjan** [yugabyte/yugabyte-db#9023]
We can use the API developed earlier to write a Kafka Source Connector for YB CDC. 
It should publish the CDCEvent in AVRO/JSON from Kafka Connect to Kafka Topics

**Comment by vaibhav-yb** [comment]
This Kafka Source Connector is the one Debezium is being referred to here. It has been implemented now. The fork of the same can be found here at https://github.com/yugabyte/debezium/tree/final-connector-ybdb
