### ISSUE TITLE
Define the metrics for CDC SDK

### ISSUE THREAD

**Issue by suranjan** [yugabyte/yugabyte-db#9026]
Jira Link: [DB-2930](https://yugabyte.atlassian.net/browse/DB-2930)
Metrics for showing the current state of cluster with respect to CDC  e.g.

- checkpoints
- WAL size
- intentdb size

**Comment by vrajat** [comment]
@suranjan is checkpoint required to track end to end lag? we are creating a metric for end to end lag based on physical time of write to commit.
