### ISSUE TITLE
[Docs] There should be delineation between the OSS docs and the Platform Commercial docs

### ISSUE THREAD

**Issue by rjw-41x** [yugabyte/yugabyte-db#9030]
There is confusion on our customers part when they google a topic and "land" in Yugabyte Core docs then look for the functionality in platform.  There needs to be a clearer delineation between the OSS docs and the Platform Commercial docs.

Have received feedback from several customers and seen in real time.  One example is encryption at rest.

**Comment by polarweasel** [comment]
This is a complex issue. There's not an immediately obvious way to tag features that are supported by core and not platform, for example, and the list is subject to frequent change. We've removed a certain number of descriptions from the core docs that described platform features, and I'm not sure there's much else to be done here. @rjw-41x any thoughts or suggestions? If not, let's close this one.

**Comment by rjw-41x** [comment]
go ahead an close.  I understand the complexity in the request.
