### ISSUE TITLE
[docdb] Master task tracking should point to the table it is operating on

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#9061]
For background LB tasks, we seem to print out the tablet info, but not the table info.

We currently do not have an easy way to go from tablet -> table, so it would be useful to either have a dedicated way to do that or at the very least, have the `/tasks` endpoint also print out the table ID, so we can then reference against the `/tables` endpoint.

**Comment by bmatican** [comment]
This should be a pretty small pointer into the master background/async task framework. Can check with @amitanandaiyer for an example of one task we can trigger on demand, like an index backfill.

**Comment by es1024** [comment]
Added table information to /tasks endpoint in commit f240839; a mapping between tablet and table name/UUID is already exposed via the appropriate tablet server's /tablets endpoint.
