### ISSUE TITLE
Set better default for `rpc_default_keepalive_time_ms`

### ISSUE THREAD

**Issue by ttyusupov** [YugaByte/yugabyte-db#907]
One of the issues causing https://github.com/YugaByte/yugabyte-db/issues/821 was that requests which were sent to socket after the network is healed only were starting to appear at the destination node socket after about 10-20 seconds. This could be avoided by making a tserver to use newly created connections after the network is healed. Setting `--rpc_default_keepalive_time_ms 5000` causes tserver to drop connections which are idle for more than 5 seconds and create new ones after network partition is over, making recovery faster.

The goal of this ticket is to find and set a reasonable default value for `rpc_default_keepalive_time_ms` and do related testing.

**Comment by mbautin** [comment]
@ttyusupov: based on your recent testing, is this still relevant and do you have guesses to what the reasonable value range of `rpc_default_keepalive_time_ms` should be?

**Comment by ttyusupov** [comment]
RPC heartbeats and keepalive implemented in the scope of #950 will fix this issue as well and we can keep `rpc_default_keepalive_time_ms` as is. `rpc_default_keepalive_time_ms` controls `Reactor::ScanIdleConnections` which is responsible for garbage collection of idle inbound connections. While RPC heartbeats and keepalive from #950 is controlled by `rpc_connection_timeout_ms` and responsible for dropping connections which are stuck due to network partitions/errors.

**Comment by ttyusupov** [comment]
I think we should close #821 after #950 is landed.
