### ISSUE TITLE
[Docs] update for XCluster removed information on updating Universe version - needs to be added back

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#9074]
We had documentation that covered this issue:
https://github.com/yugabyte/yugabyte-db/issues/7540

It was removed with this PR:
https://github.com/yugabyte/yugabyte-db/pull/8136

We need to restore the documentation that covers updating the Platform Universe version after setting up XCluster Replication.

**Comment by polarweasel** [comment]
This may have been an inadvertent removal of the xCluster parts. Double-check, and adjust accordingly

**Comment by lizayugabyte** [comment]
I believe this ticket can be closed, since xcluster in Platform has been completely redesigned (see https://yugabyte.atlassian.net/browse/PLAT-1978 )
