### ISSUE TITLE
[Platform] Add the ability to add arbitrary application.conf settings through values.yaml

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#9077]
To allow application.conf entries to be set through the helm chart, currently, we create values.yaml settings corresponding to each applicaiton.conf entry. Instead we should expose a general YAML dictionary/map in values.yaml whose entries are automatically populated into YW application.conf.

```
yugaware:
   application_conf_overrides:
        foo: abc
```
should translate to `foo = "abc"` in the application.conf file. We can separate string and boolean/int settings into different dictionaries because they translate to `foo = true`  or `foo = 1` without the quotes.

This feature should be backported to the 2.6 branch of charts repo.

cc @ajcaldera1 who felt the need for this recently

cc @kkg-yb

**Comment by bhavin192** [comment]
I think this was implemented in https://github.com/yugabyte/charts/commit/96ffc6d62a8ffb16101f579719e572c9687f3df8
