### ISSUE TITLE
[Docs] More context is needed on options for yb-admin replication options. 

### ISSUE THREAD

**Issue by fsayedyb** [yugabyte/yugabyte-db#9079]
Description: 
here https://docs.yugabyte.com/latest/admin/yb-admin/#alter-universe-replication and here https://docs.yugabyte.com/latest/admin/yb-admin/#set-universe-replication-enabled
It's not clear if "-master_addresses <master-addresses>" is the Consumer or the Producer.

Infrastructure: ALL

Feature Request:
We need to be more explicit when listing addresses to be clear if they are the producer or the consumer. e.g.
https://docs.yugabyte.com/latest/admin/yb-admin/#setup-universe-replication
"-master_addresses <master-addresses>"

A workaround:
 by a process of elimination we can tell that it's the Consumer's master-addresses

**Comment by ddorian** [comment]
This has already been fixed with `<target_master_addresses>` and `<source_master_addresses>`
