### ISSUE TITLE
YEDIS: Support for geospatial queries

### ISSUE THREAD

**Issue by kevbaker** [yugabyte/yugabyte-db#909]
I am looking into using YugaByte for a project that would require geospatial queries.

I see that YugaByte does not currently support this feature.

I would be hoping for an implementation somewhat along the lines of [REDIS geospatial patterns](https://redislabs.com/redis-best-practices/indexing-patterns/geospatial/) or [MongoDB's geospatial query support](https://docs.mongodb.com/manual/geospatial-queries/).

**Comment by m-iancu** [comment]
@kevbaker we are actively working on geospatial support on our YSQL API (via PostGIS, tracked in #910). We currently have no plans to support geospatial queries for our YEDIS api.

**Comment by m-iancu** [comment]
Closing as `wontfix` as per message above.
