### ISSUE TITLE
[docdb] Support gzipped responses in webserver

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#9090]
Metrics can be pretty large in certain scenarios and we sometimes scrape them every 10s. Returning gzipped responses when the http client specifies `Accept-Encoding: gzip` would help make the prometheus scrape consume less network b/w.

https://github.com/apache/kudu/commit/8f525829dcfc49edea9fadbe7514db2ea64f2087 might be useful.

**Comment by tedyu** [comment]
Here is unfinished patch:
[yb-websvr-comp-2.txt](https://github.com/yugabyte/yugabyte-db/files/6712677/yb-websvr-comp-2.txt)
