### ISSUE TITLE
[docdb] please review command line help for  yb-admin create_snapshot_schedule

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#9092]
We currently list this

47. create_snapshot_schedule <snapshot_interval_in_minutes> <snapshot_retention_in_minutes> <table> [<table>]...

It appears to be wrong and looks like we need to give it ycql prefix also similar to 

 51. create_keyspace_snapshot [ycql.]<keyspace_name>
 52. create_database_snapshot [ysql.]<database_name>

**Comment by sanketkedia** [comment]
See https://docs.yugabyte.com/latest/admin/yb-admin/#create-snapshot-schedule. We do use a prefix as part of the filter that we specify.
