### ISSUE TITLE
centos/clang11 compiler generated code under -O0 optimization level that crashed with SEGV

### ISSUE THREAD

**Issue by myang2021** [yugabyte/yugabyte-db#9093]
I was debugging create_initial_sys_catalog_snapshot failure under centos/clang11
build when postgres is configured with ICU is enabled (postgres config option
--with-icu).

I used gdb to debug postgres code but found certain local variables were not
printable because the compiler optimized them away under -O1 optimization level.
I made a temporary CMakeLists.txt update to change -O1 to -O0:

```
-set(CXX_FLAGS_DEBUG "-ggdb -O1 -fno-omit-frame-pointer")
+set(CXX_FLAGS_DEBUG "-ggdb -O0 -fno-omit-frame-pointer")
```

After this change, I was able to see those variables inside gdb and made
progress to find the work around of create_initial_sys_catalog_snapshot
failure.

An incidental finding is that sometimes yb-master crashed with SEGV. After
debugging, I found that it is caused by memory mis-alignment and it appears
specific to clang compiler (I tested with g++ and it went fine). In fact
there is a unit test that this can be reproduced:

```
./yb_build.sh --clang11 lockfree-test
```

Once built, the SEGV can be reproduced repeatedly faster via:

```
./build/latest/tests-util/lockfree-test --gtest_filter=LockfreeTest.Stack
Note: Google Test filter = LockfreeTest.Stack
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from LockfreeTest
[ RUN      ] LockfreeTest.Stack
*** Aborted at 1624580308 (unix time) try "date -d @1624580308" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 21986 (TID 0x7f155f593700) from PID 0; stack trace: ***
    @     0x7f1561496630 (unknown)
    @           0x410838 yb::LockFreeStack<>::Pop()
    @           0x412bd7 yb::LockfreeTest_Stack_Test::TestBody()::$_1::operator()()
    @           0x412a3d _ZNSt3__18__invokeIZN2yb23LockfreeTest_Stack_Test8TestBodyEvE3$_1JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOS4_DpOS5_
    @           0x4129e5 _ZNSt3__116__thread_executeINS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN2yb23LockfreeTest_Stack_Test8TestBodyEvE3$_1JEJEEEvRNS_5tupleIJT_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE
    @           0x412756 std::__1::__thread_proxy<>()
    @     0x7f156148eea5 start_thread
    @     0x7f15611b79fd __clone
Segmentation fault (core dumped)
```

Debugging the above unit test, I found that under -O0 mode centos/clang11
generated instruction:

```
=> 0x0000000000410838 <+1576>:  movaps (%rax),%xmm0
(gdb) p $rax
$1 = 140737283613176
(gdb) p 140737283613176/16.0
$2 = 8796080225823.5
```

According to https://c9x.me/x86/html/file_module_x86_id_180.html, the operand
must be aligned on a 16-byte boundary. Because 140737283613176 is not, hence
the SEGV.

This instruction matches source code

```
128           if (head_.compare_exchange_weak(old_head, new_head, boost::memory_order_acq_rel)) {
```

Neither old_head nor new_head is 16-byte aligned:
```
(gdb) p &old_head
$3 = (yb::LockFreeStack<Entry>::Head *) 0x7ffff3cbe1f8
(gdb) p &new_head
$4 = (yb::LockFreeStack<Entry>::Head *) 0x7ffff3cbe1e8
```

Not sure whether I can say this is a clang compiler bug. A simple work around
is to make the struct 16-byte aligned:
```
  struct Head {
    T* pointer;
    size_t version;
  }
```

**Comment by mbautin** [comment]
This seems related: https://lists.llvm.org/pipermail/llvm-bugs/2010-July/013741.html

**Comment by mbautin** [comment]
That particular old occurrence of a similar bug seems to have been fixed here: https://lists.llvm.org/pipermail/llvm-bugs/2010-July/013745.html

**Comment by myang2021** [comment]
Thanks for the update @mbautin , looks like exactly the bug but not sure why I saw it again.

**Comment by mbautin** [comment]
It probably makes sense to open a bug in LLVM and provide a minimal code example reproducing it. I might try that later.
