### ISSUE TITLE
[docs] ysql hba auth methods missing

### ISSUE THREAD

**Issue by ssung-yugabyte** [yugabyte/yugabyte-db#9095]
https://docs.yugabyte.com/latest/secure/authentication/host-based-authentication/
1. In the auth method section, md5, ldap, cert, gss, scram-sha256 are missing.  
2. ‘check user permissions’ is not relevant to this section.
3. The example is not secure. In the last example,
--ysql_hba_conf=“host all yugabyte 0.0.0.0/0 trust,host all all 0.0.0.0/0 md5,host all yugabyte ::0/0 trust,host all all ::0/0 md5”. This basically creates a security vulnerability.  Everyone from everywhere can login as yugabyte without a password, because it is in the first line of the hba file.  The rest of the rules will be ignore.
4. 'trust' should not be used at all, not even local.  'local' should use peer.

**Comment by ddhodge** [comment]
Additional commentary on HBA here https://yugabyte.slack.com/archives/CAR5BCH29/p1624907438189900
