### ISSUE TITLE
Postgres API: Support for geospatial queries

### ISSUE THREAD

**Issue by kevbaker** [yugabyte/yugabyte-db#910]
I am looking into using YugaByte for a project that would require geospatial queries.

I see that YugaByte does not currently support this feature. 

Postgres seems like a natural fit given possible PostGIS integration.

I would be hoping for an implementation somewhat along the lines of the standard [PostGIS integration](https://postgis.net/).

**Comment by kmuthukk** [comment]
@kevbaker - Thanks for your question. This is something that is certainly on our roadmap - but not something that we have scoped out yet. We will look into this and keep you posted.

**Comment by ndeodhar** [comment]
Hi @kevbaker, thanks for reporting this issue. We've started to look into PostGIS integration for YB and we'll keep you posted as we make progress on this.

**Comment by contra** [comment]
I believe this can be closed, yugabyte 2 shipped with PostGIS support - https://github.com/yugabyte/yugabyte-db/blob/3c8635a14948f21a22ab74aadf87c96e8b9a8854/docs/content/latest/api/ysql/extensions.md#postgis
