### ISSUE TITLE
[xCluster] yb-admin incorrectly reporting success of replication changes 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#9104]
**Issue**
When working in an xCluster environment, with bi-directional replication, `yb-admin` command may incorrectly return `Replication setup successfully`

**Version**
- Yugabyte 2.4.4-b7 

**Steps to reproduce** 
1. Follow steps to [setup xCluster Replication](https://docs.yugabyte.com/latest/admin/yb-admin/#setup-universe-replication)
     NOTE: values used are
```
yb-dev-hamilton-prometheus-rca-timeskew-n3
    clusterUuid: e3baaff6-d0cb-4543-89e6-2f502f5608b4
masterAddrs:  
    10.204.0.28, 10.207.0.36, 10.204.0.29
Tables: 
    test_crash:      2001ecc2-ecb8-48fd-bf20-305817c9f419, 
    cassandratransactionalkeyvalue:     26fa7337-fa3a-48c7-a269-b5ce11b54f02
    cassandrauserid:     53e78b20-2974-42b5-af38-a7b94995a37b

```
```
yb-dev-hamilton-cdc-stream-test-n1
    clusterUuid: 83d126b1-3b3a-42ff-a5ce-29dde55fa104
masterAddrs:  
   10.207.0.39, 10.204.0.44, 10.200.0.83          
Tables:
    test_crash:     5ebeec56-8640-4e37-ba80-a997fbc46790
    cassandratransactionalkeyvalue:     a0fbaaf0-d7ed-486d-bfbb-0813b1270f4b
    cassandrauserid:     6cc31b79-cee1-47c7-b520-f442bd0d1ae9
```
2. Attempt `setup_universe_replication` with incorrect values (cassandratransactionalkeyvalue table ID is missing the 'a')

```
[yugabyte@yb-dev-hamilton-prometheus-rca-timeskew-n3 bin]$ ./yb-admin -master_addresses 10.204.0.28,10.207.0.36,10.204.0.29 setup_universe_replication 83d126b1-3b3a-42ff-a5ce-29dde55fa104 10.200.0.83,10.204.0.44,10.207.0.39 0fb0afcdfe4a422abe919a0968a9566c, 6cc31b79cee147c7b520f442bd0d1ae9, 5ebeec5686404e37ba80a997fbc46790
Replication setup successfully
```
5. Verify with `get_universe_config`, if consumer registry is correct 
```
[yugabyte@yb-dev-hamilton-prometheus-rca-timeskew-n3 bin]$ ./yb-admin -master_addresses 10.207.0.36,10.204.0.29,10.204.0.28 get_universe_config | python -m json.tool
{
    "clusterUuid": "e3baaff6-d0cb-4543-89e6-2f502f5608b4",
    "consumerRegistry": {},
    "replicationInfo": {
------- <snip> -------
```
6. Notice that the `consumerRegistry` is empty

**Request/Expected Behavior** 
The `yb-admin` command should error out when the operation fails, failure in this instance is exhibited by 1: Consumer registry is unaltered 2. The UUID of the table provided was inaccurate - this should have terminated the task 
The command should not return status of "successfully" in such circumstances 
There needs to be logic around verifying correct setup or alteration of Replication.  

7. NOTE - The same message is correctly given when replication does succeed
```
[yugabyte@yb-dev-hamilton-cdc-stream-test-n1 bin]$ ./yb-admin -master_addresses 10.200.0.83,10.204.0.44,10.207.0.39 setup_universe_replication e3baaff6-d0cb-4543-89e6-2f502f5608b4 10.204.0.28,10.207.0.36,10.204.0.29 26fa7337fa3a48c7a269b5ce11b54f02,53e78b20297442b5af38a7b94995a37b,2001ecc2ecb848fdbf20305817c9f419
Replication setup successfully

[yugabyte@yb-dev-hamilton-cdc-stream-test-n1 bin]$ ./yb-admin -master_addresses 10.207.0.39,10.204.0.44,10.200.0.83  get_universe_config | python -m json.tool
{
    "clusterUuid": "83d126b1-3b3a-42ff-a5ce-29dde55fa104",
    "consumerRegistry": {
        "producerMap": {
            "e3baaff6-d0cb-4543-89e6-2f502f5608b4": {
------- <snip> -------
```
**Reference** 
Please see ticket [1505](https://yugabyte.zendesk.com/agent/tickets/1505)

**Comment by CharlotteRose** [comment]
THis seems to be similar to Git hub Issue [8757](https://github.com/yugabyte/yugabyte-db/issues/8757)

**Comment by dotyjim-work** [comment]
This should be fixed by https://github.com/yugabyte/yugabyte-db/issues/8757
