### ISSUE TITLE
[YB-YSQL] YSQL app running against a universe where table doesn't exists leads to exhaustion and  ysqlsh connectivity failure alerts.

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#9121]
1. Started SqlInserts sample app on a universe with 2.6.0.0-b59 build and deleted the table used by App. 
2. App continued to run but finally leads to exhausting YSQL connections and causing  YSQL connectivity health alerts.

**Comment by rao-vasireddy** [comment]
This appears to be an application issue where it is issuing initiating a new connection on every table not found error without closing the previous connection

**Comment by tedyu** [comment]
Fixed by https://github.com/yugabyte/yb-sample-apps/pull/66
