### ISSUE TITLE
[YCQL] describe on partial index does not show the predicate information.

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#9135]
Jira Link: [DB-2341](https://yugabyte.atlassian.net/browse/DB-2341)
This is on 2.6(b59) cluster.

Steps : 
ycqlsh> create index partIndex1 on yb_pitr_test.employees(newCol) where newCol=true;
ycqlsh> describe yb_pitr_test.partInex1;

CREATE INDEX partindex1 ON yb_pitr_test.employees (newcol, employee_no)
    WITH transactions = {'enabled': 'true'};

**Comment by Arjun-yb** [comment]
Validated with **2.9.0.0-b4** and observed same issue.

**Comment by pkj415** [comment]
Describing a partial secondary index doesn't show the predicate information, but describing the table shows the predicate information on the partial secondary indices.
```
ycqlsh:temp> create table test (k int primary key, v int) WITH transactions = { 'enabled' : true };
ycqlsh:temp> create index idx on test(v) where v>5;
ycqlsh:temp> describe idx;

CREATE INDEX idx ON temp.test (v, k) WHERE v > 5
    WITH transactions = {'enabled': 'true'};

ycqlsh:temp> describe test;

CREATE TABLE temp.test (
    k int PRIMARY KEY,
    v int
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'true'};
CREATE INDEX idx ON temp.test (v, k) WHERE v > 5
    WITH CLUSTERING ORDER BY (k ASC)
    AND transactions = {'enabled': 'true'};
```

So, as a workaround, use describe on the table to see any predicates.

Also, to also show the predicate information in the `describe` output for partial secondary indices, a change in the cassandra python driver is required similar to as done here - https://github.com/yugabyte/cassandra-python-driver/commit/71d59fbd64b8441805146561878a9f1ce1f3ad8c

This change was part of a 3 change series to address #9762 with the first change being 1513483c2d98ea92fb82576342ce556b8667915f
