### ISSUE TITLE
[docs] Describe the process for using xCluster replication with TLS

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#9160]
These Scenarios should be documented publicly

1. Setting up xCluster with both Producer & Consumer using the same TLS cert
2. Setting up xCluster with Producer & Consumer using different TLS certs
3. Setting up xCluster with Producer using TLS cert but not Consumer
4. Setting up xCluster with Consumer using TLS cert but not Producer

We support #1 & #2 for sure.  Steps are listed below.  #3 & #4 need some investigation to verify that they are supported use cases.

cc @nspiegelberg @rahuldesirazu

**Comment by nspiegelberg** [comment]
I know that we have FLAGS_certs_for_cdc_dir  to handle a situation where the producer and consumer have different certificates.  I don’t think we’ve tested this lately or mixed mode.  This above flag also requires FLAGS_use_node_to_node_encryption, which tells me we were only coding for both on / both off situations.
