### ISSUE TITLE
[DOC]yb-admin replication cli commands need to relfect similar verbage to Async Details page 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#9172]
**Issue** 
When following instructions to setup/alter universe replication via the `yb-admin` [1](https://docs.yugabyte.com/latest/admin/yb-admin/#setup-universe-replication) [2](https://docs.yugabyte.com/latest/admin/yb-admin/#alter-universe-replication) the `table_UUID` is not clearly stated to be that of the producer, as we see in the Asynchronous Replication documentation [3](https://docs.yugabyte.com/latest/explore/multi-region-deployments/asynchronous-replication-ycql/#3-configure-unidirectional-replication)

**Steps to Reproduce** 
- View the links above 
- Follow the information from the `yb-admin` cli command and notice that the cli will report success - when in fact it has failed (this is addressed in GHI [9104](https://github.com/yugabyte/yugabyte-db/issues/9104)
- Get the table_UUID from the consumer 
```
[yugabyte@yb-dev-hamilton-zd1453-schwab-1-n1 bin]$ ./yb-admin -master_addresses `hostname` list_tables include_table_id | grep ybdemo
ybdemo_keyspace.cassandrauserid 1b7befb524f44067acab90c8ef6a3715
```
- Initiate the setup of replication 
```
[yugabyte@yb-dev-hamilton-zd1453-schwab-1-n1 bin]$ ./yb-admin -master_addresses 10.204.0.15,10.207.0.44,10.207.0.45 alter_universe_replication 7ea1f6c9-f20e-4107-b052-285546ba88ba add_table 1b7befb5-24f4-4067-acab-90c8ef6a3715
Replication altered successfully
```
- Notice that the consumer registry does not reflect any changes
```
[yugabyte@yb-dev-hamilton-zd1453-schwab-1-n1 bin]$ ./yb-admin -master_addresses 10.204.0.15,10.207.0.44,10.207.0.45 get_universe_config | python -m json.tool 
{
    "clusterUuid": "bf9958e0-d2ac-45aa-8b51-67637a6960f5",
    "consumerRegistry": {},
    "replicationInfo": {
        "affinitizedLeaders": [
            {
```

**Additional Information** 
As noted above, the issues of invalid response indicating replication was setup/altered successfully is being addressed by engineering - but in the interim, I expect a minor modification to the documentation can help customers avoid any potential issues.

**Comment by polarweasel** [comment]
Related ticket is #9079

**Comment by ddorian** [comment]
This has already been fixed, it's clearly stated who the source/target universe is and where is the table_id located.
