### ISSUE TITLE
[docs] Document new LZ4 compression type option

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#9174]
We added this option in 38f306da873663b44d136b593212cab9e0e01afc

some points:
- `--compression_type` can be "Snappy", "LZ4", or "NoCompression"
- by default, this flag is set to "Snappy"
- if an invalid option is selected, the cluster will not come up
- if this flag is changed, it will not take effect until nodes are restarted
- changing this flag on an existing database is supported -- a tablet can validly have SSTs with different compression types. overtime, compaction will remove the old compression type files

**Comment by polarweasel** [comment]
@robertsami Where do we supply these flags? And what version(s) of YugabyteDB is this option available in?

**Comment by polarweasel** [comment]
We should also add zlib to this one.
