### ISSUE TITLE
[Feature Request] YugabyteDB as Grafana datasource

### ISSUE THREAD

**Issue by arun11299** [yugabyte/yugabyte-db#9175]
Hello Folks,
I was not able to find much information about using YugabyteDB as Grafana datasource. Also, not sure if I should be asking this question here or in the Grafana repo.
Anyways, I am planning to use Yugabytedb for analytics use and wanted to know if there is a way to provide visualiazation for the data from the database. 
I know that one can create new data sources as Grafana plugins, but just wanted to know if there is some work someone has already done.

Seems like a great product! Thanks for making it open source :)

**Comment by FranckPachot** [comment]
Hi, as YugabyteDB is wire compatible with PostgreSQL, you can just use the PostgreSQL datasource. Don't forget the port in the hostname (eg hostname:5433) as it is not the postgres default one. TLS disabled if you didn't enable it in YugabyteDB. And optionally set Version to 11 as this is the current compatibility level for functions.

**Comment by arun11299** [comment]
@FranckPachot Thanks, that's what I thought as well after I posted the question :).
