### ISSUE TITLE
Could not find a third-party release archive to download for OS type 'ubuntu20.04' and compiler type 'gcc'

### ISSUE THREAD

**Issue by kcolbert1** [yugabyte/yugabyte-db#9184]
Upon executing the command "./yb_build.sh release" the build failed with the following message:
ValueError: Could not find a third-party release archive to download for OS type 'ubuntu20.04' and compiler type 'gcc'. Please see the list of available thirdparty archives above.

A similar issue was reported by https://github.com/ttyusupov for Centos 7 and clang about a month ago:
ybd: asan/tsan build type failure #8763

PC information is as follows:
Linux Distribution: Ubuntu 20.04
Linux Kernel: 5.8.0-59-generic
GCC version: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Please see the attached file for full details.
[log_file.txt](https://github.com/yugabyte/yugabyte-db/files/6766262/log_file.txt)

**Comment by svarnau** [comment]
On Ubuntu20, gcc9 is supported, but not gcc7  (which is the default gcc in yb_build.sh).
So, use:
  yb_build.sh  --gcc9 release

**Comment by kcolbert1** [comment]
Thank you svarnau, I am able to get passed the error message by executing: "yb_build.sh --gcc9 release"
