### ISSUE TITLE
Call home alerts missing documentation

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#9187]
https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-alerts-health-check/#configure-alerts-and-health-checking

What do the various levels of call home mean?
What metrics are part of the alerts?
What components are in and out of scope for the alerts?
They need more details on our alerting.

**Comment by anmalysh-yb** [comment]
Quick look at the code shows that:
In case callhome level is "NONE" - we're not collecting any diagnostic data and passing callhome_enabled = false gflag to DB nodes.
We're always passing callhome_collection_level gflag on universe upgrade.
Not sure what exacltly is collected on nodes based on callhome collection level - need help from someone familiar with core DB.
Also, In case level is higher than NONE - we're collecting some diagnostic information related to customer and sending it to callhome URL each hour

**Comment by polarweasel** [comment]
Hey @RunningJon is this issue still valid, or can we close? It seems from the slack thread that this ticket was based on erroneous assumptions.

**Comment by RunningJon** [comment]
The assumptions were made because it isn't documented.
