### ISSUE TITLE
Document how to upgrade Platform in Kubernetes

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#9203]
We have documentation on how to install software - but we don't have documentation on how to _upgrade_ your software, or manage your software, via replicated and k8s. 

https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/install-software/default/

**Comment by ddhodge** [comment]
See also #4342

**Comment by lizayugabyte** [comment]
@tylarb @ddhodge Upgrade via replicated is documented here: @ddhodge I believe this has been documented in https://docs.yugabyte.com/latest/yugabyte-platform/upgrade/upgrade-yp-replicated/

**Comment by lizayugabyte** [comment]
@sridhar-yb We need to document how to upgrade platform s/w using Kubernetes. Who would be able to help with the steps?

**Comment by lizayugabyte** [comment]
@tylarb Upgrade via replicated is documented here: https://docs.yugabyte.com/latest/yugabyte-platform/upgrade/upgrade-yp-replicated/
Is the doc on upgrade via kubernetes still necessary?

**Comment by tylarb** [comment]
@lizayugabyte  yes please! 

It should just be a helm apply ? cc @iSignal

**Comment by lizayugabyte** [comment]
@iSignal Would you be able to provide the instructions for this?

**Comment by lizayugabyte** [comment]
@iSignal Would the users just need to run helm apply? If so, could you provide a full example, please?

**Comment by iSignal** [comment]
It would be a helm apply but with a reuse-values in case the user has applied any overrides earlier. 

The example would look like 

`helm upgrade yw-test yugabytedb/yugaware --version 2.13.0 -n yb-platform --reuse-values --wait` 

similar to the example on https://docs.yugabyte.com/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes/

cc @bhavin192 @baba230896
