### ISSUE TITLE
[Platform][UI_minor]Leading or trailing spaces are not removed from username field on login console

### ISSUE THREAD

**Issue by sridhar-yb** [yugabyte/yugabyte-db#9213]
Leading or trailing spaces are not removed from username field on login console
I/P: 
Observed we are sending payload without trimming.

```
{email: “demo@yugabyte.com “, password: “password”}
email: “demo@yugabyte.com ”
password: “password”
```

As the trailing spaces are not removed user login got failed. 
Attached the screenshot for reference

<img width="1792" alt="Screenshot 2021-07-08 at 1 05 55 PM" src="https://user-images.githubusercontent.com/85868962/124881667-3edf5900-dfed-11eb-8b6e-2ab19c37be28.png">

**Comment by christinjohn-yb** [comment]
Landed the changes under https://phabricator.dev.yugabyte.com/D12585
