### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by rizalgowandy** [yugabyte/yugabyte-db#9214]
Currently using https://github.com/jackc/pgx.
Seeing intermittent error `unexpected EOF` returning from Query, QueryRow, and Exec.

Current schema:
Go -> HAProxy -> YugaybteDB

Where Go:
4 instances 2 core 4 GB

YugabyteDB:
3 instances 16 core 32 GB

Go code:
```go
// Parse configuration.
dbConfig, err := pgxpool.ParseConfig(config.DB.Master)
if err != nil {
	return err
}
if !env.IsProduction() {
	dbConfig.ConnConfig.Logger = logger.NewPGX()
}
dbConfig.MaxConns = config.DB.MaxConnection
dbConfig.MinConns = config.DB.MinConnection
dbConfig.MaxConnLifetime = func() time.Duration {
	ttl := config.DB.MaxConnectionLifetime
	return time.Duration(ttl) * time.Second
}()
dbConfig.MaxConnIdleTime = func() time.Duration {
	ttl := config.DB.MaxConnectionIdleTime
	return time.Duration(ttl) * time.Second
}()

// Create database connection.
conn, err := pgxpool.ConnectConfig(ctx, dbConfig)
if err != nil {
	return err
}
```

Configuration:
- MinConnection: 0
- MaxConnection: 8
- MaxConnectionLifetime: 180 seconds = 3 mins
- MaxConnectionIdleTime: 60 seconds = 1 mins

I've also tested different configuration:
- MinConnection: 1,4,0,0,10
- MaxConnection: 8,8,16,64,64
- MaxConnectionLifetime: 3 mins, 10 mins, 30 mins, 60 mins
- MaxConnectionIdleTime: 1 mins, 5 mins, 10 mins, 30 mins

Feeling desperate, this error never occurs when I was using PostgreSQL.
Really confused, read all the other user problems, the error persists.

Also, tested with schema:
Go -> HAProxy -> PGBouncer -> YugabyteDB
Where PGBouncer connection is set to 200, max 1024.
Error still persists.

YugabyteDB Configuration:
https://gist.github.com/wardana/7f11e34ee599343e1391ceaa694ecb9f

Am I missing something here?

**Comment by ddorian** [comment]
@rizalgowandy can you remove the haproxy and try connecting directly to yugabytedb ?
Also can you put a full script to verify ?

**Comment by rizalgowandy** [comment]
https://github.com/jackc/pgx/issues/1039
