### ISSUE TITLE
[Platform] DB migrations issue

### ISSUE THREAD

**Issue by anmalysh-yb** [yugabyte/yugabyte-db#9215]
We got an issue with our DB migrations in 2.7.x releases.
There is a migration R__Extend_RuntimeConfigEntry_For_Large_Values.sql - which was for some reason made repeatable.
It was submitted to master at June, 10 and changes the value column type in runtime_config_entry table.
And there is later migration V93__Fill_Alert_Definition_Group_Table.sql - which is dependent on this column type. It was submitted at July, 2 (but had a bug initially and was fixed at July, 6).
The issue with these 2 is that they pass successfully in case repeatable migration runs before versioned one. Which is the case when you upgrade from previous builds. But it will fail in case of fresh Platform install - as repeatable migration runs last.
We need to fix this, but there is no fix, which is transparent to user. Basically we need to make repeatable migration to be versioned and run before V93 migration.
The only “acceptable” way to fix it I see is to do the following:
Move code from the repeatable migration to V93 migration.
Remove code from repeatable migration so that it’s no-op (can’t just remove as flyway will throw error on missing migration)
The only issue with this approach is that Platform upgrade will fail from any build, older than July, 6. But I guess it shouldn’t be a common case and we can fix this issue manually on such systems.

**Comment by iSignal** [comment]
The original diff which hit the conflict was https://github.com/yugabyte/yugabyte-db/commit/3ddbdd61454be2dbdc3b3354ca3c331d9b5cf72c (2.7.2.0-b166) and the fix was https://github.com/yugabyte/yugabyte-db/commit/c14e16117ee089af3578c47d9ae51320b6926670 (2.7.2.0-b178). For upgrades that avoid these versions, there should be no issues.

cc @VijiYB
