### ISSUE TITLE
Need fix on itest for the backup diff [#9113] [#9114]

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#9221]
[Platform][#9113] [#9114]Populate the task id field in the backup table needs changes in the itest as the itest failed when this diff landed.

Explanation from Vineeth, why itest failed :

> The reason for failure in the itest is not due to the backup changes that have been done but rather because of the way in which we fetch the backup_uuid.
To explain it further, I made the changes on the Platform to persist the task_id responsible for creating the new MultiTableBackup task. So, basically the task_id is now persisted in the backup table.
Now, in the current implementation of itests, the backup_id is fetched in this particular code snippet.
```
def get_backup_for_task(self, task_uuid, universe_uuid):
        for backup in self.get_all_backups(universe_uuid):
            if backup['taskUUID'] == task_uuid:
                return backup['backupUUID']
        return None
```

> Here, the arguments being passed to this method are task_uuid=None and the universe_id corresponding to the backups that we are dealing with. If you look at the above code logic, the backup_uuid is returned accurately assuming that the task_uuid=None. But the changes that I made populates this field in the backend thereby returning None. Now, the subsequent calls are made with None as the backup_uuid instead of the actual one thereby resulting in the backup itests failing.

**Comment by vpatibandla-yb** [comment]
The changes have been made and merged. After the merge, the itests started running as expected.
The PR for this is here: https://phabricator.dev.yugabyte.com/D12211
