### ISSUE TITLE
[Platform][UI] Default to GP3 as the default EBS volume type

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#9238]
Currently Platform UI defaults to GP2. GP3 volumes are most efficient and guarantee 3000 iops baseline performance.

**Comment by amhatre99** [comment]
Resolved

**Comment by VijiYB** [comment]
Now that GP3 is loaded by default, Provisioned IOPS/throughput are not populated. Only if reselect GP3, those values. are populated. Logged a separate bug for this - #9451
