### ISSUE TITLE
[PLATFORM]: Unable to download a logs from node on a platform UI.

### ISSUE THREAD

**Issue by jatinbhowad** [yugabyte/yugabyte-db#9262]
Downloads logs feature from Nodes is broken.

*Steps to Reproduce*
1. Go to the nodes
2.  Try to download logs by clicking on a Node's action button and download logs

**Comment by VijiYB** [comment]
@sb-yb - I'm assigning this to you as you said you will take a look first, please reassign if needed. 

We need this feature for 2.7.2 release @hsiaosu-yb

**Comment by streddy-yb** [comment]
This was addressed as part of #9209
