### ISSUE TITLE
[PLATFORM]: Node status shows as 'Unreachable', after restarting a node process

### ISSUE THREAD

**Issue by jatinbhowad** [yugabyte/yugabyte-db#9263]
After restarting(stop/start) the node process, on UI shows node status as a "Unreachable". But you can connect to that node using ysqlsh. Verified on AWS as well as Azure provider.

*Steps to Reproduce*
1. Create Universe
2. Try to stop the process on any node
3.  start the process again and check the status of that node

*Additional Info*
Is it an expected behavior, in 3 node universe after stopping process for 1 node it does not show stop process option for other 2 nodes?

**Comment by VijiYB** [comment]
@hsiaosu-yb - Can you please assign this to someone, seems to be a blocker for 2.7.2 release. Able to connect thru ysqlsh but on the UI it shows as unreachable when you stop and start the processes.

**Comment by iSignal** [comment]
Most likely as a result of 9260d374dd1910a0d0c4b41b182e536b43f3250
