### ISSUE TITLE
[Platform] Cloud Provider Configuration for Kubernetes Calls out ECS Instead of EKS

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#9278]
Cloud Provider Configuration for Kubernetes calls out Elastic Container Service (ECS) instead of Elastic Kubernetes Service (EKS). The latter is the correct one. Both exist as services within AWS however EKS if for managed Kubernetes whereas ECS is for a managed version of Amazons proprietary container software. Image below. 

![image](https://user-images.githubusercontent.com/38478518/125505566-43e2682b-d508-4b7b-8611-15dbc8727cc7.png)

**Comment by hsiaosu-yb** [comment]
The same issue is present for Azure.  We call out ACS instead of AKS -- we should make the same label change for Azure as well.

**Comment by sb-yb** [comment]
Same for Google Kubernetes Engine GKE. There was a rename:
https://cloud.google.com/blog/products/gcp/introducing-certified-kubernetes-and-google-kubernetes-engine
