### ISSUE TITLE
Can't install with docker. Not sure how to get it work on docker.

### ISSUE THREAD

**Issue by hiqbn** [YugaByte/yugabyte-db#929]
How do I do docker installation on multi node setup? I can't even seem to get the first docker up. Can anyone provide the tutorial for setting up a 3 or 5 nodes yugabyte instance?

**Comment by schoudhury** [comment]
There are 2 approaches of running YugaByte DB on Docker containers.
1. The Local Cluster Approach - here we simulate a multi-node DB cluster on a single physical machine. Documentation available here: https://docs.yugabyte.com/latest/quick-start/install/#docker

2. The Multi-Machine Approach - here we run a multi-node DB cluster on multiple physical machines. Usually this approach requires you to run a container orchestration/scheduling layer on top of Docker. The de-facto standard here is Kubernetes and de-facto approach for deploying a workload onto Kubernetes is Helm Chart. Documentation available here: https://docs.yugabyte.com/latest/deploy/kubernetes/helm-chart/

Note that in 2 above, the prerequisite is that you have a Kubernetes cluster up and running on any number of physical nodes you desire. By default, both the approaches start with 3 node DB clusters with Replication Factor 3. For a 5 node DB cluster with RF3, you can use the Helm Chart option with tserver replica count set to 5 (and the master replica count unchanged).

Let us know if this answers your question.

**Comment by hiqbn** [comment]
2. must have kubernetes installed?

Can you provide the optimum config and installation instructions for kubernetes setup for yugabyte?
also, can you also provide the information on how to secure the transport layer for interconnected yugabyte nodes. thx

**Comment by rkarthik007** [comment]
Hi @hiqbn,

### k8s version
As for version of k8s, `v1.10+` is what we expect. The requirements for k8s are documented on this page:
https://docs.yugabyte.com/latest/deploy/kubernetes/helm-chart/#prerequisites

Here is what you for a minimal k8s cluster:
```
Kubernetes nodes where a total of 12 CPU cores and 45 GB RAM can be allocated 
to YugaByte DB. This can be 3 nodes with 4 CPU core and 15 GB RAM allocated to 
YugaByte DB.
```

For workloads that have a decent number of ops/sec (or production), we typically recommend 8 cores on the tservers. For the masters - 2 cores are sufficient.

### k8s cluster installation
It is probably simplest to get started with a managed k8s service, but not sure if that is what you are looking for. Here are the detailed instructions to setup k8s:
https://kubernetes.io/docs/setup/

### TLS encryption
TLS encryption is an enterprise feature. If you are interested in this, could you please reach out to us at https://www.yugabyte.com/contact-sales/ and we can get you started with a trial edition.

**Comment by rkarthik007** [comment]
Hi @hiqbn - hope you were able to get past this issue - I am closing this for now. Please feel free to reach out on our Slack chat or reopen this issue if you need help.
