### ISSUE TITLE
Allow custom names for yugabyte helm deploys

### ISSUE THREAD

**Issue by 86label** [yugabyte/yugabyte-db#9290]
Currently it is not possible to use the helm charts to deploy multiple yugabyte clusters in the same namespace.
At least not without extensive changes in _helpers.tpl, service.yaml and the values.yaml file.

All resources created seems to have been hardcoded to certain values, fx:
statefulset.apps/yb-master
statefulset.apps/yb-tserver
service/yb-master-ui
service/yb-masters
service/yb-tserver-service

For example, with cockroachdb helm charts installed with release name "myname" they default to:
statefulset.apps/cockroachdb-myname
service/cockroachdb-myname

This makes it very easy to deploy and manage multiple clusters in a single namespace.

**Comment by 86label** [comment]
Misunderstood the oldNamingStyle value. This is not a problem when oldNamingStyle=false.

**Comment by iSignal** [comment]
@86label : glad you were able to get it to work.

cc @jvigil-yugabyte
