### ISSUE TITLE
Create issue templates with pre-populated suggestions.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#9304]
Currently , while creating new issues , there needs to be a template helping users across the community to sort the issue by its type at the time of creation.
Issue types to be included:
1.docs
2.core (ycql, ysql, docdb)
3.platform
4.UI

**Comment by polarweasel** [comment]
To clarify: we'll need to create several issue templates, one per issue type.

**Comment by aishwarya24** [comment]
Reference PR: https://github.com/yugabyte/yugabyte-db/pull/9346
