### ISSUE TITLE
[docs] Update the Deployment checklist on public clouds.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#9306]
1. Include a checklist for Microsoft Azure on this page : https://docs.yugabyte.com/latest/deploy/checklist/#running-on-public-clouds
2. The AWS and GCP sections also need to be updated where necessary. For instance, if smaller instance types are supported, that needs to be included.

**Comment by ddhodge** [comment]
There is an Azure section now. Any needed updates can go in a new issue.
