### ISSUE TITLE
Possible endless loop when reloading a relcache entry

### ISSUE THREAD

**Issue by andrei-mart** [yugabyte/yugabyte-db#9323]
The function

```
static HeapTuple
ScanPgRelation(Oid targetRelId, bool indexOK, bool force_non_historic)

```
if invoked with targetRelId=ClassOidIndexId which is 
```
DECLARE_UNIQUE_INDEX(pg_class_oid_index, 2662, on pg_class using btree(oid oid_ops));
#define ClassOidIndexId  2662
```
may start endless loop from the line 
https://github.com/yugabyte/yugabyte-db/blob/70758b2746d4d04e212d1404a18af1de707d8a6b/src/postgres/src/backend/utils/cache/relcache.c#L400
->
https://github.com/yugabyte/yugabyte-db/blob/70758b2746d4d04e212d1404a18af1de707d8a6b/src/postgres/src/backend/access/index/genam.c#L345
->
https://github.com/yugabyte/yugabyte-db/blob/70758b2746d4d04e212d1404a18af1de707d8a6b/src/postgres/src/backend/access/ybc/ybcam.c#L1312
->
https://github.com/yugabyte/yugabyte-db/blob/70758b2746d4d04e212d1404a18af1de707d8a6b/src/postgres/src/backend/utils/cache/relcache.c#L2690
->
https://github.com/yugabyte/yugabyte-db/blob/70758b2746d4d04e212d1404a18af1de707d8a6b/src/postgres/src/backend/utils/cache/relcache.c#L1814

where ScanPgRelation is called again with targetRelId=ClassOidIndexId

**Comment by nocaway** [comment]
@nocaway : Original Postgres does not have this bug.  The actual Yugabyte code that causes this bug is not yet located.  When the offending Yugabyte code is found, that piece of code should be fixed such that original Postgres code can be kept the same.
