### ISSUE TITLE
[PLATFORM]: Backup is failing on IAM-enabled  backup configuration

### ISSUE THREAD

**Issue by jatinbhowad** [yugabyte/yugabyte-db#9341]
Backup is failing for IAM-enabled backup configuration

*STEPS TO REPRODUCE*
1. Create IAM-enabled platform
2. Create IAM-enabled backup configuration
3. Try to take backup

*Additional Info*
Backup getting successful with non-IAM  backup config

**Comment by jatinbhowad** [comment]
Following is the error showed on UI :


`Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"9a0e0300-422a-41a8-a3d0-f80b44d2eb0c","expectedUniverseVersion":null,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":120..., hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/d6515e92-66bb-491b-872a-20b585d6868c/yb-demo-jatin-iam-enabled_d6515e92-66bb-491b-872a-20b585d6868c-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.27.208', \"cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_wlwbctfphbzudtwr/cloud_cfg put /tmp/yb_backup_wlwbctfphbzudtwr/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal/univ-9a0e0300-422a-41a8-a3d0-f80b44d2eb0c/backup-2021-07-19T13:41:59-1064997004/keyspace-postgres/SnapshotInfoPB.sha256'\"]' returned non-zero exit status 77."}.`

**Comment by streddy-yb** [comment]
@vpatibandla-yb - Has anything changed w.r.t IAM role based backups? Can you try this out?

**Comment by vpatibandla-yb** [comment]
@sridhar-yb @hsiaosu-yb @jatinbhowad 

The folder specified**(s3://backups.yugabyte.com/portal)** to take the backup has certain permissions set up on them. If you look at the permissions setup for the **backups.yugabyte.com** bucket, you will notice that for the put call on this folder to succeed, the AWS user should be **aws-portal**. Can you please verify that this is the AWS user that has been used.

I would suggest to use a location different from the folders mentioned below to test your changes:

1. s3://backups.yugabyte.com/portal/
2. s3://backups.yugabyte.com/gcp-portal/
3. s3://backups.yugabyte.com/portal-2/
4. s3://backups.yugabyte.com/k8s-portal/

If the backup call succeeds, then the backups are succeeding with IAM enabled. 

According to my understanding, you have deployed the platform by using the creds of a user other than the **aws-user**. 
For detailed analysis of this issue, please refer to the GH issue: https://github.com/yugabyte/yugabyte-db/issues/7704

**Comment by kkg-yb** [comment]
Adding @jatinbhowad as assignee so that he can test this as per comments by @vpatibandla-yb

**Comment by jatinbhowad** [comment]
I able to create backup with the folder which don't have a listed custom permissions.

**Comment by jatinbhowad** [comment]
Closing this issue as it's not a bug.
