### ISSUE TITLE
[YSQL] Enable transaction pool for PostgreSQL

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#935]
@robertpang said that even in YCQL we use multiple YBClient instances, so if we are benefiting from the transaction pool in YCQL, we might also benefit from it in PostgreSQL, especially if there is a limited number of connections.

**Comment by ndeodhar** [comment]
@mbautin @spolitov , this has already been done, right? Can we close this?

**Comment by m-iancu** [comment]
Should have been done in https://github.com/yugabyte/yugabyte-db/commit/877a3e0afb226c18de92496d9b7ac66c8c3de2b2. See also issue #2909.
