### ISSUE TITLE
Provide support to read the Snapshot of the tablet while reading the OpIds range from the WAL.

### ISSUE THREAD

**Issue by suranjan** [yugabyte/yugabyte-db#9353]
In some cases,  we need to provide the existing rows and then stream the changes as part fo CDC.

To support this, we need to provide a way to take a snapshot of the tablet and read using an iterator on the tablet. After the table has been streamed, we need to read from the snapshotted OpId and stream the changes.

**Comment by vaibhav-yb** [comment]
Currently we have implemented this feature, so closing this issue now.
