### ISSUE TITLE
Incorrect bind-mount path config in documentation

### ISSUE THREAD

**Issue by achselschweisz** [yugabyte/yugabyte-db#9358]
Hi,
in the "Create a local cluster" configuration section (found here: https://docs.yugabyte.com/latest/quick-start/create-local-cluster/docker/#1-create-a-local-cluster) you posted the following command to bind-mount the yugabyte data/conf/log files to the host:

```sh
docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042\
 -v ~/yb_data:/home/yugabyte/var\
 yugabytedb/yugabyte:latest bin/yugabyted start\
 --daemon=false 
```

In fact, the data inside the container can be found in under `/root/var`, hence the correct command would be:

```sh
docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042\
 -v ~/yb_data:/root/var\
 yugabytedb/yugabyte:latest bin/yugabyted start\
 --daemon=false 
```

EDIT: this concerns the image tagged yugabytedb/yugabyte:2.7.1.1-b1

**Comment by CiiDyR** [comment]
Experiencing the same issue. I think this should be fixed rather quickly as it's a pretty big put-off for newcomers like me.
After a single reboot of my laptop it just wouldn't start again. Either updating the docs to `/root/var` (which feels hacky) or adding a user called `yugabyte` which is actually used to run yugabyte instead of root would be an easy fix for this.

Currently it's not a good experience when people like me try yugabyte for the first time.

**Comment by polarweasel** [comment]
Docker image has been updated.

One change required in the docs: add a step before step 1, along the lines of:

> On your local machine, verify that a `~/yb_data` directory exists, and is owned by your user. If not, create it (or change its ownership):

```sh
$ mkdir ~/yb_data
```

**Comment by iSignal** [comment]
@CiiDyR @achselschweisz : thanks for reporting this issue. We will work on fixing the docs soon.

You can use the docker cmd `bin/yugabyted start --base_dir=/home/yugabyte` instead if mounting to `/root/var` doesn't feel clean.

**Comment by polarweasel** [comment]
Two changes required in the docs:

1. Add a step before step 1, along the lines of:

    > On your local machine, verify that a `~/yb_data` directory exists, and is owned by your user. If not, create it (or change its ownership):

    ```sh
    # create the directory
    $ mkdir ~/yb_data
    ```

    ```sh
    # OR, adjust an existing directory's ownership and permissions
    $ sudo chown -R <yourUsername> ~/yb_data
    ```

1. Adjust the Docker command to be the following:

    ```sh
    $ docker run -d --name yugabyte \
             -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 \
             -v ~/yb_data:/home/yugabyte/yb_data \
             yugabytedb/yugabyte:latest bin/yugabyted start \
             --base_dir=/home/yugabyte/yb_data --daemon=false
    ```

**Comment by achselschweisz** [comment]
Cheers guys!
