### ISSUE TITLE
[DST] Flag to allow compression of RPC calls to reduce network b/w

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#9370]
In areas where network b/w is at a premium (cross-AZ network costs, say), having network-level compression, at the RPC layer, would allow us to tradeoff CPU to reduce networking costs. 

Ideally, this would work similar to HTTP Accept-Encoding, where the [request RPC header flags](https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/src/yb/rpc/rpc_header.proto#L57) would specify a bitmask of compression types it prefers and the response would carry equivalent flags to indicate compression.

**Comment by bmatican** [comment]
oops, seems I duplicated some GH issues, will close https://github.com/yugabyte/yugabyte-db/issues/9378

**Comment by iSignal** [comment]
OpenSSL has some support for compression in-built https://www.openssl.org/docs/manmaster/man3/SSL_COMP_add_compression_method.html though there is some discussion on whether it is a good idea.

**Comment by spolitov** [comment]
It seems deprecated.
