### ISSUE TITLE
[DST] Metrics for network bandwidth by RPC call

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#9372]
The following metrics could make it easier to understand network b/w usage.

handler_bytes_in/out avg/p99 by (rpc call name, table)
Also aggregated as
handler_bytes_in/out avg/p99 by (rpc call name)

**Comment by bmatican** [comment]
seems I had duplicated the GH issue, so I closed https://github.com/yugabyte/yugabyte-db/issues/9380
