### ISSUE TITLE
[docs] Documentation request, behaviour of index creation has changed since v2.0

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#9376]
**[Alex edit to add: needs refinement before we can work on this. See comments.]**

The behaviour of index creation has changed since the initial release in v 2.0 and this has not been updated in the docs

Docs team to update the documentation with regard to this feature as per ticket https://github.com/yugabyte/yugabyte-db/issues/448

We no longer have the concurrent index add issue. Now indexes are built asynchronously, in a distributed and online manner, with the DB switching to the index transparently once built.

Here is the design doc for this: https://github.com/yugabyte/yugabyte-db/blob/master/architecture/design/online-index-backfill.md

**Comment by mheer9** [comment]
Link to feature ticket https://github.com/yugabyte/yugabyte-db/issues/448

**Comment by lizayugabyte** [comment]
@mheer9 Could you, please, provide a link to the outdated documentation?

**Comment by mheer9** [comment]
Hi @lizayugabyte 
Here is the link to the documentation
https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_index/

To give more context

Cockroach are posting this about Yugabyte
"adding an index performs a scan on the PostgreSQL frontend of the existing rows in the table and for each row adding an entry to the index. The addition of each row is performed via an RPC to Yugabyte’s DocDB. In Yugabyte, schema changes need to be coordinated by the application. Concurrent addition of an index on one node and modifications to a table on another node can result in an inconsistent index"

Karthik has commented on this (see below), and requested an update to the docs
"We have fixed all of the above. Here's how things work:
* We no longer have the concurrent index add issue. Now indexes are built asynchronously, in a distributed and online manner, with the DB switching to the index transparently once built.
* The "issue" really was the fact that we're so PG compatible, that PG's own rebuild on each node would work with DocDB storage. We should have disallowed index rebuilding in the first place back then.

Here is the design doc for this: https://github.com/yugabyte/yugabyte-db/blob/master/architecture/design/online-index-backfill.md
And the github issue: https://github.com/yugabyte/yugabyte-db/issues/448

And this thread means we haven't documented this, which is bad. I will fix that. Could you pls open a github against the docs team?"

**Comment by lizayugabyte** [comment]
@m-iancu Just to make sure I understand correctly: The outdated content is in API docs, right? And this ticket is not applicable to our indexes doc in Explore here https://docs.yugabyte.com/latest/explore/indexes-constraints/indexes-1/ ?

**Comment by mheer9** [comment]
@m-iancu Let me check and I will come back to you

**Comment by mheer9** [comment]
Hi @m-iancu, the information regarding how the indexes are now built should go in the API docs, as that describes what happens when an index is created. This needs to updated with an explanation of how indexes are built asynchronously, in a distributed and online manner, with the DB switching to the index transparently once built.

**Comment by polarweasel** [comment]
@mheer9 is this API-documentation change something you can help out with, or can you suggest someone else who can?

**Comment by mheer9** [comment]
Hi @polarweasel 
I think the explanation about indexes are built asynchronously and distributed in an online manner etc..

Should go in the docs below which describe index builds
https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_index/

I was asked to raise this issue by Karthik Ranganathan, so he may provide further info

**Comment by ddorian** [comment]
This issue is pretty old. All issues raised have been implemented in the create index page.
