### ISSUE TITLE
[docs] Document Django in Integrations

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#9382]
CC: @kneeraj

**Comment by lizayugabyte** [comment]
This might be the Django starter doc, but I don't have access to it (requested a week ago; no luck so far)
https://docs.google.com/document/d/1A78-_ycF57JtrE8InaxJEzr6Li8vk812U9ur7SkGkcw/edit#

**Comment by lizayugabyte** [comment]
I was going to start working on the Django integration doc, but then realized that the doc provided by dev was last edited in March and contains only internal implementation details. I've reached out to Hemant.

**Comment by polarweasel** [comment]
@Sfurti-yb any updates here?

**Comment by Sfurti-yb** [comment]
Documentation for the [integrations tab](https://docs.yugabyte.com/latest/integrations/) : https://docs.google.com/document/d/1VWqXc9ZVEWFF0yAW7EvhIX1tUidlRbbaudfzp84f6U8/edit?usp=sharing
Documentation for the [quick start tab](https://docs.yugabyte.com/latest/quick-start/build-apps/python/ysql-psycopg2/) :
https://docs.google.com/document/d/1yVtkHS5FAd7oNOnjC95DpjOTK5LykH6p7kWEyRp4MGo/edit?usp=sharing
In case of any queries, please let me know. Thanks.
