### ISSUE TITLE
[docs] Document Sequelize in Integrations

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#9383]
CC: @kneeraj

**Comment by sanyamsinghal** [comment]
Here is the [link to the initial doc](https://docs.google.com/document/d/1Isoz7xAny_BxN3eRFw9YEIO9YUlwI5n5TV7HoUzWvGE/edit#heading=h.8xg47pxmzr9h)  for using Sequelize with YugabyteDB. Please let me know in case of any questions. Thanks!!

**Comment by lizayugabyte** [comment]
Done and closed by PR #9744
