### ISSUE TITLE
ysql: insert after create table errors "does not exist"

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#9389]
Jira Link: [DB-2214](https://yugabyte.atlassian.net/browse/DB-2214)
According to a recent test run, an insert to a table right after `CREATE TABLE` errors, saying that the table does not exist, but later inserts to the same table succeed.

```
CREATE TABLE TIME_TBL (f1 time(2));
INSERT INTO TIME_TBL VALUES ('00:00');
ERROR:  relation "time_tbl" does not exist
LINE 1: INSERT INTO TIME_TBL VALUES ('00:00');
                    ^
INSERT INTO TIME_TBL VALUES ('01:00');
```

Logs show that the DDL transaction for the CreateTable, whose transaction_id starts with `0ecdbc` (hex), was PENDING while the first insert happened, and then it became ABORTED.

```
m1|pid24106|:24915 I0720 11:12:06.755780 25678 ysql_transaction_ddl.cc:47] Verifying Transaction { transaction_id: 0ecdbcf5-2240-4cdf-8020-496a29d17513 isolation: SNAPSHOT_ISOLATION status_tablet: 36b9a8e1168842e695e35d22d44c79e9 priority: 13448860560753938585 start_time: { physical: 1626779521793467 } }
ts1|pid24713|:23135 2021-07-20 11:12:06.758 UTC [25638] ERROR:  relation "time_tbl" does not exist at character 13
ts1|pid24713|:23135 2021-07-20 11:12:06.758 UTC [25638] STATEMENT:  INSERT INTO TIME_TBL VALUES ('00:00');
m1|pid24106|:24915 I0720 11:12:06.767680 24256 ysql_transaction_ddl.cc:84] TransactionReceived: OK : status: ABORTED
m1|pid24106|:24915 status_hybrid_time: 18446744073709551615
m1|pid24106|:24915 propagated_hybrid_time: 6663288941634809856
m1|pid24106|:24915 coordinator_safe_time: 6663288941634686976
m1|pid24106|:24915 I0720 11:12:06.767750 24256 ysql_transaction_ddl.cc:105] Got Response for { transaction_id: 0ecdbcf5-2240-4cdf-8020-496a29d17513 isolation: SNAPSHOT_ISOLATION status_tablet: 36b9a8e1168842e695e35d22d44c79e9 priority: 13448860560753938585 start_time: { physical: 1626779521793467 } }: status: ABORTED
```

The test failure was on centos-clang11-debug, `./yb_build.sh --java-test TestPgRegressTypesMisc`.  The full log is temporarily available at https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-phabricator/104350/artifact/java/yb-pgsql/target/surefire-reports_org.yb.pgsql.TestPgRegressTypesMisc__testPgRegressTypes/org.yb.pgsql.TestPgRegressTypesMisc-output.txt.gz.  The relevant snippets are available at https://gist.github.com/jaki/a0fc18ec09fbb204c1213c96175757b2/raw/9729a98c0b6db6c9bc1c00718632fd7962512510/F104350.log.

**Comment by m-iancu** [comment]
Closing this as it's an old issue and the referenced tests reliably succeeds on centos (on Mac there is an unrelated issue with the expected result for inet).

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressTypesMisc&fail_tag=all&name=testPgRegressTypes&platform=all
