### ISSUE TITLE
[YSQL] retryable_rpc_single_call_timeout_ms should be set higher for debug builds in Java PostgreSQL tests

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#941]
This is because there are some long-running RPC calls to the master happening as part of initdb.

**Comment by kutayzorlu** [comment]
retryable_rpc_single_call_timeout_ms   nNOT FOUND  FLAG !! ERROR

**Comment by m-iancu** [comment]
Addressed in [4385ad2](https://github.com/yugabyte/yugabyte-db/commit/4385ad213d6fcc0f955f44b9c0f89b7bbcbf7285).
