### ISSUE TITLE
[Platform] Ability to update backup config storage location when the location is in use by old existing backups

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#9411]
We only support changing SAS token and not the storage location Container URL in a backup config for Azure provider on the platform. The feature to update storage location will help in using multiple locations. 

![Screenshot from 2021-07-21 11-46-20](https://user-images.githubusercontent.com/78443978/126527364-bdf06c27-8f04-458a-a74e-ad2ce3278878.png)

**Comment by kkg-yb** [comment]
From what I have understood the requirement is that we should be able to modify the storage location. But if we modified the storage location existing backups would not be available anymore. And the main purpose of the storage location is to point where backups are to be stored.

So is it ok to not be able to access existing backups?

**Comment by hsiaosu-yb** [comment]
Looks like this is already covered by:

https://github.com/yugabyte/yugabyte-db/issues/7349

If so, maybe we could mark this as a dup of 7349?

**Comment by adil246** [comment]
@hsiaosu-yb GH Issue #9411 covers updating backup configurations. We can close this as a dup if #7349 also covers editing existing configuration. If editing exsiting config is not suggested workflow or not a priority at the moment, then we can either move this to backlog for review or close.

**Comment by hsiaosu-yb** [comment]
Ok, I'll let @kkg-yb decide whether this should be marked as a dup of #7349

**Comment by kkg-yb** [comment]
Closing as duplicte
