### ISSUE TITLE
[xCluster]: Change xCluster Metrics Collection Interval from 1s to 15s

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#9417]
We currently set `--update_metrics_interval_ms = 1000`, which means we collect metrics every 1s. This operation opens the cdc_state table and loops through all tablets under-replication, which can be an expensive operation. Since we don't need such fine-grained metrics, we can change this to 15000 to collect every 15s.

**Comment by sanketkedia** [comment]
Taking this up.
