### ISSUE TITLE
[xCluster] Disallow DROP or TRUNCATE of Tables Under Replication

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#9421]
A user should first disable replication before dropping or truncating a table, but we currently put the onus on the user to make sure they do this. We can harden/error-proof the system by doing that check on our end.

**Comment by hulien22** [comment]
@SGZW If you're looking for another issue to contribute on, this task seems pretty good as well!
See some of the work I did in 031e012, specifically `CatalogManager::IsCdcEnabled`. Should be able to verify this in `CatalogManager::DeleteTable` and then add a new gflag in to gate this check.

If you need any more help, feel free to ask me here or on slack!

**Comment by SGZW** [comment]
> @SGZW If you're looking for another issue to contribute on, this task seems pretty good as well!
> See some of the work I did in [031e012](https://github.com/yugabyte/yugabyte-db/commit/031e012a6a13f3688a33e07d1e36a2d864bd790e), specifically `CatalogManager::IsCdcEnabled`. Should be able to verify this in `CatalogManager::DeleteTable` and then add a new gflag in to gate this check.
> 
> If you need any more help, feel free to ask me here or on slack!

thanks, i will try to solve this issue, please assign to me

**Comment by nspiegelberg** [comment]
A prototype of this was implemented in https://phabricator.dev.yugabyte.com/D13838 for reference.

**Comment by nspiegelberg** [comment]
Task Breakdown:
1. Add code to not allow DROP or TRUNCATE operations to occur on a Table with CDC Enabled (Replication)
2. Add a runtime GFLAG to override this check, in case there's some use case we don't anticipate.
3. Add a CLI-level Unit Test to verify this change.

FUTURE: We need to add the ability to flow the TRUNCATE operation over to the consumer, when the GFLAG override is enabled.
