### ISSUE TITLE
yb-ts-cli should return success message on compact_all_tablets 

### ISSUE THREAD

**Issue by shaharuk-yb** [yugabyte/yugabyte-db#9430]
currently, yb-ts-cli does not return any success message on the the completion of compaction.

```
 ./yb-ts-cli --server_address=<ip>:9100 compact_all_tablets
```
It would be nice addition if a user friendly message is added.

**Comment by SGZW** [comment]
I'm a first-time contributor, and can i pick this issue?

**Comment by bmatican** [comment]
@SGZW Another OSS contributor already took care of this! Maybe we can find you some other starter task instead? cc @hulien22

**Comment by hulien22** [comment]
@SGZW left you a comment on https://github.com/yugabyte/yugabyte-db/issues/9421#issuecomment-889290241
