### ISSUE TITLE
[docs] Restructure Explore Part 2

### ISSUE THREAD

**Issue by lizayugabyte** [yugabyte/yugabyte-db#9434]
3: Add Distributed SQL just below Postgres vs YSQL.
4: Move Follow reads, Smart driver, Tablespaces, Tablegroups (when we have them) to under Distributed SQL.
5: Rename Postgres vs YSQL to RDBMS or something like that.
7: Split CDC into two and leave CDC Kafka where it is now under Integrations and move Generic under Explore > Distributed SQL.

Done:
1: Place Cluster Management just below Indexes and Constraints -- #9447
2: Postgres vs YSQL _index.md: Delete See also; Extend link to all of the Tablespaces entry (at the bottom of the page); Link 1st column header to Sharding (table at the bottom of the page)  -- #9447
6: Rename Explore features to Explore -- #9447

**Comment by lizayugabyte** [comment]
1. Done
2. Done

**Comment by polarweasel** [comment]
#9447 addresses items 1, 2, and 6. I'll get the others.
