### ISSUE TITLE
[Platform] Add Instance Type for Graviton support on AWS

### ISSUE THREAD

**Issue by hsiaosu-yb** [yugabyte/yugabyte-db#9442]
Need to add m6g as supported instance types on AWS on this screen:

![image](https://user-images.githubusercontent.com/82529763/126734898-f29bd9a9-0def-41a7-896b-46f068a3fa5f.png)

**Comment by iSignal** [comment]
Other than the instance type changes, which can be gated by an application.conf setting, a few other considerations here:

1. Do our existing ansible flows run properly on ARM instances? For ex, those AMIs may have different base tools in their images.
2. We copy backup utils related python packages from YW to db nodes. Need to verify there's no x86 specific stuff there.
3. We copy node exporter to db nodes, need to verify it is not x86 specific (likely is)
4. The db release package needs to be named with x86 in the name. Longer term we should accept both x86 and aarch64 releases for the same release version but temporarily we can just rename an aarch64 release as x86 for portal testing purposes.
