### ISSUE TITLE
[Platform] Provisioned IOPS/throughput are not populated on load for GP3

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#9451]
GP3 is made as default (#9238) for EBS volume type, but the Provisioned IOPS/Throughput are not getting populated on load. If we reselect GP3, those values are populated. 

<img width="1477" alt="Screen Shot 2021-07-23 at 3 30 31 PM" src="https://user-images.githubusercontent.com/78048211/126847391-705da40e-2a21-4b20-818d-1dac3ce44ee3.png">

**Comment by VijiYB** [comment]
cc @hsiaosu-yb

**Comment by amhatre99** [comment]
Resolved
