### ISSUE TITLE
Temporal Integration with YugabyteDB

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#9459]
This issue tracks all the work related to Temporal Integration with YugabyteDB.

# Tasks
|Done|Name|Notes|GitHub Issue|
| - | - | - | - |
|✅| Test Temporal's sample examples with YSQL |  Works fine out-of-the-box|[Done for Go and Java](https://docs.google.com/document/d/1qfvRZbDWH6ygGeISNQmuGc8jDVZAn1LKUbunG_5j1xI/edit#heading=h.qy2eqtsfsfx)|
|✅| Test Temporal's sample examples with YCQL |  |[Issues documented here](https://docs.google.com/document/d/1qfvRZbDWH6ygGeISNQmuGc8jDVZAn1LKUbunG_5j1xI/edit#heading=h.tfk6k99qs8fd)|
| | Run Temporal test suite | | |
| | Provide YugabyteDB-specific extension/plugin/etc. | | |
| | Add test cases | | |
| | Documentation on Yugabyte site | | |
| | Blog on Yugabyte site | | |
| | Documentation hosted on Temporal site | | |
| | Blog hosted on Temoral site | | |

**Comment by ashetkar** [comment]
The Temporal was validated successfully to work with YSQL API and we do not want to pursue YCQL API connectivity as of now. Closing the ticket.

**Comment by kneeraj** [comment]
Let's keep this open and try to complete it end to end as per the template. @ashetkar

**Comment by HarshDaryani896** [comment]
Issues filled for this Integration : #15101  #15367
