### ISSUE TITLE
READ COMMITTED required for Camunda

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#9464]
I have a customer wanting to use Camunda with Yugabyte and is able to connect but found this in the Camunda documentation.

_The required isolation level to run Camunda with is READ COMMITTED, which may have a different name according to your database system. Setting the level to REPEATABLE READS is known to cause deadlocks, so one needs to be careful, when changing the isolation level._

https://docs.camunda.org/manual/7.12/user-guide/process-engine/database/#isolation-level-configuration

The customer is asking us to support READ COMMITTED so they can reliably use Camunda.

**Comment by pkj415** [comment]
READ COMMITTED is in progress as part of #9468. However - a point to note is that deadlocks are possible even in READ COMMITTED isolation level. An example to prove that -

`piyushjain=# start transaction isolation level read committed;
START TRANSACTION
					piyushjain=# start transaction isolation level read committed;
					START TRANSACTION

piyushjain=*# update test set v1=3 where k=3;
UPDATE 1
					piyushjain=*# update test set v1=3 where k=4;
UPDATE 1
piyushjain=*# update test set v1=3 where k=4;
					piyushjain=*# update test set v1=3 where k=3;
					UPDATE 1
ERROR:  deadlock detected
DETAIL:  Process 3693 waits for ShareLock on transaction 46458; blocked by process 3698.
Process 3698 waits for ShareLock on transaction 46457; blocked by process 3693.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (0,40) in relation "test"
`

**Comment by ddorian** [comment]
Read committed has been added https://docs.yugabyte.com/preview/architecture/transactions/read-committed/. 
Please re-open if any issue arises.
