### ISSUE TITLE
Yugabyte Platform Multi-Zone universe document is out of date

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yugabyte-db#9499]
There are several sections of the [Yugabyte Platform Multi-Zone universe doc](https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/) that are out of date.

In the [Connect to a database node](https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/#connect-to-a-database-node) section, the dialog that the Connect button brings up has changed (new name, different info). The SSH info for connecting to the database nodes has moved from this dialog to the "Actions" dropdown for each node.

In the [Run workloads](https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/#run-workloads) section, most of the info can be replaced with details on how to find the instructions for the Sample Apps. The Sample Apps instructions are now in Universes => More => Run Sample Apps. The Metrics tab steps should remain.

The Sample Apps are now in Docker containers. There are notes like "You should stop the load tester." and "You should stop the sample application." in these sections and it would be helpful to include instructions on how to stop them.

Find container:
```
user@yugaware-1:~$ sudo docker container ls | grep "yugabytedb/yb-sample-apps"
ac144a49d57d        yugabytedb/yb-sample-apps                                        "/usr/bin/java -jar …"   17 seconds ago      Up 16 seconds                                                                                                            jovial_morse
```

Stop container:

```
user@yugaware-1:~$ sudo docker container stop ac144a49d57d
ac144a49d57d
```

Several of the other screenshots are out of date and should be reviewed / refreshed.

**Comment by ddhodge** [comment]
See also #9400
