### ISSUE TITLE
Support the TS data type in the nodejs driver

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#95]
Support for the following commands in nodejs driver:
- [`TSADD`](https://docs.yugabyte.com/api/redis/tsadd/)
- [`TSGET`](https://docs.yugabyte.com/api/redis/tsget/)
- [`TSRANGEBYTIME`](https://docs.yugabyte.com/api/redis/tsrangebytime/)
- [`TSREM`](https://docs.yugabyte.com/api/redis/tsrem/)

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
