### ISSUE TITLE
Improve recovery delay after  network partitions

### ISSUE THREAD

**Issue by ttyusupov** [YugaByte/yugabyte-db#950]
As originally mentioned in https://github.com/YugaByte/yugabyte-db/issues/821#issuecomment-468483028 - recovery times after network partitions could be up to 25 seconds.

We've found that introducing network partitions with `iptables` drop input packet rules causes TCP connections which were opened and had traffic before partition start to have an additional delay in acknowledging and transmitting packets even after network partition is over.
For example, in experiments with 30-seconds partitions and using `netcat` to communicate between hosts we’ve observed 23 seconds delay after network partition is over.

**Comment by ttyusupov** [comment]
Some logs from experiments with `netcat`:
```
n2 netcat output: local time and time sent by n1
Fri Mar  1 14:20:07 UTC 2019: Fri Mar  1 14:20:07 UTC 2019
Fri Mar  1 14:20:08 UTC 2019: Fri Mar  1 14:20:08 UTC 2019
Fri Mar  1 14:20:09 UTC 2019: Fri Mar  1 14:20:09 UTC 2019
Fri Mar  1 14:20:10 UTC 2019: Fri Mar  1 14:20:10 UTC 2019
INFO [2019-03-01 14:20:11,626] jepsen nemesis - jepsen.util :nemesis    :info   :start-partition        [:isolated {"n2" #{"n5" "n1" "n4"}, "n3" #{"n5" "n1" "n4"}, "n5" #{"n2" "n3"}, "n1" #{"n2" "n3"}, "n4" #{"n2" "n3"}}]
...
INFO [2019-03-01 14:20:41,725] jepsen nemesis - jepsen.util :nemesis    :info   :stop-partition :network-healed
....
n2 netcat output:
Fri Mar  1 14:21:04 UTC 2019: Fri Mar  1 14:20:11 UTC 2019
Fri Mar  1 14:21:04 UTC 2019: Fri Mar  1 14:20:12 UTC 2019
Fri Mar  1 14:21:04 UTC 2019: Fri Mar  1 14:20:13 UTC 2019
Fri Mar  1 14:21:04 UTC 2019: Fri Mar  1 14:20:14 UTC 2019
Fri Mar  1 14:21:04 UTC 2019: Fri Mar  1 14:20:15 UTC 2019
```

**Comment by ttyusupov** [comment]
The reason why reducing `FLAGS_rpc_default_keepalive_time_ms` doesn't help and sometimes even can make things worse is that `Reactor::ScanIdleConnections` only drops server (inbound) connections, but not client (outbound) connections. So, during partition, the server (TServer) is dropping timed out connections, but client (CQLProxy) is not. And after network partition, the client (CQLProxy) is still trying to send Read/Write RPC requests to the server (TServer), but only get an error that connection is shutdown after up to 30+ seconds and during that period requests are simply being sent “nowhere” and Java client requests are timed out.

**Comment by ttyusupov** [comment]
So, the solution to deal with stuck connections seems to be right - drop connections on timeout and create new connections (and other systems like `etcd` are doing it), but the functionality which is implementing it and handling `rpc_default_keepalive_time_ms` should be improved.

And `FLAGS_rpc_connection_timeout_ms` is also not actually controlling stuck connections timeout, because these lines:
```
RETURN_NOT_OK(socket_.SetSendTimeout(FLAGS_rpc_connection_timeout_ms * 1ms));
RETURN_NOT_OK(socket_.SetRecvTimeout(FLAGS_rpc_connection_timeout_ms * 1ms));
```
are only affects `sendmsg/recvmsg` functions on blocking sockets, but we are using non-blocking sockets, so these lines are only confusing readers (developers) that it is expected to do something with connection timeout.

**Comment by ttyusupov** [comment]
Another thing I've observed is that `Reactor::AssignOutboundCall` does `FindOrStartConnection`, creates a new connection which is not yet connected, but outbound call is being put to its queue. Then this connection is used for next outbound calls even if it is not yet connected and this can cause delays even when the network is healed in case connection is created before network partition is over.

**Comment by spolitov** [comment]
I think it is weird to have connection timeout (rpc_connection_timeout_ms) 15 seconds by default, when Raft failure timeout is just 3 seconds.

Also we should add heartbeat mechanism for RPC connection:
  1) If we did not receive anything from it within rpc_connection_timeout_ms - just drop such connection.
  2) When we did not send anything to connection within rpc_connection_timeout_ms/3 - send special heartbeat packet

**Comment by ttyusupov** [comment]
Recovery after 30 seconds network partition has been improved from:
![image](https://user-images.githubusercontent.com/903044/57387512-28e06e80-71bf-11e9-98f1-7db6ba1f70f0.png)

to:

![image](https://user-images.githubusercontent.com/903044/57390618-79f36100-71c5-11e9-8a90-b5c51b46a119.png)
![image](https://user-images.githubusercontent.com/903044/57390649-88417d00-71c5-11e9-9e5a-08d16a3a67e9.png)

Which is up to about 5 seconds instead of 25 and we can tune `rpc_connection_timeout_ms` to lower values (default is 15 seconds) to have a faster recovery. Also, we can do more investigation and look into other improvements if needed.

**Comment by aphyr** [comment]
Just a heads-up that there may be more work to do here: I've observed occasional ~100-second recovery times for a partition isolating a single node. For instance: [20190805T185957.000-0400.zip](https://github.com/YugaByte/yugabyte-db/files/3472420/20190805T185957.000-0400.zip).

![latency-raw (32)](https://user-images.githubusercontent.com/3748/62542929-d13bb880-b82a-11e9-829c-d7a70c11c10f.png)

**Comment by frozenspider** [comment]
@aphyr , this seems to be another issue (as the recovery starts *during* the partition, not *after* it as per this ticket's description).
Moved that to #1992
