### ISSUE TITLE
yb-admin: Add producer_bootstrap_ids to alter_replication UI

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#9512]
A lot of customers have 1 replication entry with multiple tables.  In the case of broken replication/DR/etc on a single table, we currently need to create a new replication entry every time because new OpIDs are created.  Add producer_bootstrap_ids support to alter_replication so we can stay consolidated.

**Comment by nspiegelberg** [comment]
1. `yb-admin_cli_ent.cc` has the `alter_universe_replication` command.  We want to add and optional additional parameter to `add_table <comma_separated_list_of_table_ids> [comma_separated_list_of_producer_bootstrap_ids]`.  This allows us to pass in some producer bootstrap ids.  It will require very similar code to `setup_universe_replication`.  
2. Please ensure we have some sanity checks to ensure that we either have matching bootstrap & table counts or no bootstrap entries.  
3. We will need a unit test for this.  See `yb-admin-test_ent.cc`

**Comment by dotyjim-work** [comment]
Landed in [`v2.6.7.0-b12`](http://release.dev.yugabyte.com/changes?version=2.6.7.0), and we released version [`v2.6.7.0-b10`](https://docs.yugabyte.com/latest/releases/earlier-releases/v2.6/#v2-6-7-0-dec-3-2021) - this will be available int `v2.6.8.0`
