### ISSUE TITLE
Update YugabyteDB Fork of the DataStax Csharp Driver

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#9516]
Community User brought up concern with using the [Yugabyte C# Driver for Yugabyte DB's Cassandra-compatible YCQL API](https://github.com/yugabyte/cassandra-csharp-driver). 

Link to Community Slack discussion   - https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1627402082203600

Issue - The driver appears to be >500 commits behind the original. Does not feel comfortable using it for production use. 

Remedy - Update the C# driver to a more recent version

**Comment by ddorian** [comment]
cc @kneeraj  @m-iancu

**Comment by stefandevo** [comment]
Hi; do you have an idea when this will be done, timeline-wise?

**Comment by kneeraj** [comment]
Hi Stefan ... I will update you with exact date early next week. Thank you for your patience. I have slacked you the details about some more information on the progress. We will update this ticket with more concrete information on the timeline erly next week. Thanks.

**Comment by Sfurti-yb** [comment]
The latest C# driver has been released on NuGet. It can be downloaded from [here](https://www.nuget.org/packages/YugaByteCassandraCSharpDriver/3.16.3).
