### ISSUE TITLE
[Platform] UI Bug When Selecting GP3 Storage on AWS

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#9575]
When you are creating a cluster on AWS using Platform and select **GP3 Storage** , provisioned IOPS and provisioned throughput are not pre-populated. However if you then select GP2 and come back to GP3 it does populate. 

![image](https://user-images.githubusercontent.com/38478518/128080176-4ef52dd2-853a-4834-a2a7-090d96fbfb6a.png)

**Comment by amhatre99** [comment]
https://github.com/yugabyte/yugabyte-db/issues/9451

Resolved and default EBS volume type as GP3 backported to 2.6
