### ISSUE TITLE
YSQL: log failed DocDB requests on client side

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#9583]
Not all error responses are self descriptive.

Example:

```
ERROR: Query error: Given ybctid is not associated with any row in table (SQLSTATE XX000)
```

It will be good to have information what exact DocDB request caused the error. Information from request will help to determine tablet, destination server etc.

**Comment by tylarb** [comment]
Backport to 2.4 would be preferred
