### ISSUE TITLE
[PITR-YCQL] OperationTimedOut error on selecting from restored table

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#9584]
on https://portal.gcp-stable.dev.yugabyte.com/universes/e9a418cb-c44a-4df7-843e-0c34c9869e9b/nodes which has build 2.6.1.0-b12, 
Steps:
Created a keyspace and bunch of tables,
Added some data in tables
Took a snapshot 
Deleted one of the tables
Restored from the snapshot 
Selecting from the table throws following error, 
When we do  **DESCRIBE COLUMNFAMILIES** we are able to see the table.

```
ycqlsh:pitr> select * from t1;
OperationTimedOut: errors={'172.151.31.96': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=172.151.31.96
```

**Comment by bmatican** [comment]
@Arjun-yb can you clarify a couple of things
- how many are `bunch of tables`, ie: <10 vs 100+ ?
- how much data is `some data`, ie: 10s of rows vs million of rows?
- when you say took and restored a snapshot, can you confirm you used the snapshot schedule API that is specific to PITR?

**Comment by Arjun-yb** [comment]
@bmatican 

- There were 4 tables
-  Added < 10 rows
- used below yb-admin commands  
- To create a snapshot - bin/yb-admin create_snapshot_schedule <interval> <retention> ycql.<keyspace> -master_addresses <comma separated node IPs>
- To restore a snapshot - bin/yb-admin restore_snapshot_schedule <schedule_id> minus <relative time> -master_addresses <comma separated node IPs>

**Comment by bmatican** [comment]
```
Arjun-pitr-3
[PITR-YCQL] OperationTimedOut: 
Steps:
1. Create keyspace and table insert some data into table
2. Create a snapshot schedule - bin/yb-admin -master_addresses 172.151.52.166,172.151.23.5172.151.46.247 create_snapshot_schedule 2 6 ycql.pitr
3. Insert some data into same table again restore back to 1 min - restore works fine
4. Create another table and get the absolute time
5. Insert some data to second table and delete first table
6. Wait for sometime(4min) Restore back to 20min - displays proper message
7. Then restore back to 5 min(with relative time), again restore back with absolute time (which is collected at step4)
8. Then restoration status will stuck into RESTORING and if you select data from second table, it errors out with OperationTimedOut
```

Looking into the cluster, I see the following logs
> I0818 19:51:20.397611 18912 async_rpc_tasks.cc:144] cde5cb78f2834cc1a746bbd8a6e0b420 (table t1 [id=00fee513d9d2484ea3119862b5d12fd4]) Tablet Snapshot Operation DELETE_ON_TABLET RPC 86aca166-4ea1-4a2d-bcd0-b5d47fa982ce (task=0x6479d50, state=kWaiting): Not found (yb/master/catalog_entity_info.cc:157): Failed to reset TS proxy: No leader found for tablet cde5cb78f2834cc1a746bbd8a6e0b420 (table t1 [id=00fee513d9d2484ea3119862b5d12fd4]) with 0 replicas: [].
> I0818 19:51:22.792565 18913 async_rpc_tasks.cc:144] 1593b5723d8c4652b1b2f50c96762904 (table t1 [id=00fee513d9d2484ea3119862b5d12fd4]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 1b6b6250-bad8-4e65-8fc9-2679b03597e2 (task=0x3a9f450, state=kWaiting): Not found (yb/master/catalog_entity_info.cc:157): Failed to reset TS proxy: No leader found for tablet 1593b5723d8c4652b1b2f50c96762904 (table t1 [id=00fee513d9d2484ea3119862b5d12fd4]) with 0 replicas: [].

So somehow, we're trying to create / delete snapshots, for tablets that maybe are no longer running?

**Comment by sanketkedia** [comment]
Fixed by this [commit](https://github.com/yugabyte/yugabyte-db/commit/b4fbfe2647820fb9c81c0a2e0342e6079f00bdd5)
