### ISSUE TITLE
[YSQL] Implement wait queue infrastructure for improved pessimistic locking

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#9589]
Jira Link: [DB-2174](https://yugabyte.atlassian.net/browse/DB-2174)

Implement wait queue infrastructure on transaction participants as a first step towards achieving generic pessimistic locking semantics (#5680).

Design doc - https://docs.google.com/document/u/1/d/1DCg4FjGlYZNBBIPcADk7z2B2TGznNHWtr8hU-0dUXyo/edit?usp=drive_web&ouid=114844179723166767268

This will be converted to a .md file and places on github once the implementation is done.

**Comment by robertsami** [comment]
re-opening to track completion of single-tablet txn support

**Comment by robertsami** [comment]
tracking remainder for single-tablet support here: https://github.com/yugabyte/yugabyte-db/issues/14014
