### ISSUE TITLE
[YCQL] SELECT count(*) may return paginated results on a large cluster. 

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#960]
Jira Link: [DB-4695](https://yugabyte.atlassian.net/browse/DB-4695)
@rao-vasireddy noticed that on a large cluster (`51` nodes) `count (*)` returns results in two pages (of one row each) in `cqlsh`. This may be because we wrongly compute the number results before the aggregation step so that we only get results from `page_size` number of tablets in each page. 
So if the table has more tablets than `page_size` we would end up with a paginated result.
This likely affects the other aggregation functions too.

When comparing with the `page_size` limit should take into account the number of results actually returned to the user, which for aggregates would be one. cc @robertpang

**Comment by bbaddepudi** [comment]
One manual way to repro this is to set `default_page_size = 1` in `cqlsh.py`, which is used by cqlsh locally. And running the following on a RF-1 `yb-ctl` based script will show pagination on the last `select count(*) ..` query.

`CREATE KEYSPACE IF NOT EXISTS Test;
CREATE TABLE IF NOT EXISTS Test.mytable (vehicleId int, routeId text, PRIMARY KEY (vehicleId));
insert into Test.mytable (vehicleId, routeId) values(1, 'r');
insert into Test.mytable (vehicleId, routeId) values(2, 'r');
insert into Test.mytable (vehicleId, routeId) values(2, 'r');
insert into Test.mytable (vehicleId, routeId) values(3, 'r');
insert into Test.mytable (vehicleId, routeId) values(4, 'r');
insert into Test.mytable (vehicleId, routeId) values(5, 'r');
select count(*) from Test.mytable;
`

**Comment by m-iancu** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/13295 which was recently fixed (pending backports).
