### ISSUE TITLE
[Platform] Create backup fails in 2.4.6.0-b10 Yugabundle

### ISSUE THREAD

**Issue by shashwat-yb** [yugabyte/yugabyte-db#9607]
Create backup is failing on 2.4.6.0-b10 Yugabundle because s3cmd is not getting installed on db-nodes.
Issue related to files present in `/opt/yugabyte/third-party/prometheus-dependencies/* `. To create backup successfully it is required to move all the files from `/opt/yugabyte/third-party/prometheus-dependencies/* ` to `/opt/yugabyte/third-party/`.

cc @VijiYB

**Comment by VijiYB** [comment]
Doc is updated to move all the /opt/yugabyte/third-party/prometheus-dependencies/* to /opt/yugabyte/third-party/.
