### ISSUE TITLE
TestPgRegressTrigger#testPgRegressTrigger fails in master branch

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#9625]
From recent Jenkins runs, it seems TestPgRegressTrigger#testPgRegressTrigger fails in master branch.

e.g.
https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F108446%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgRegressTrigger__testPgRegressTrigger%2Forg.yb.pgsql.TestPgRegressTrigger-output.txt?class=org.yb.pgsql.TestPgRegressTrigger&max_lines=3000&name=testPgRegressTrigger&start_line=144001

Still trying to find out the cause and reproduce the test failure locally.

**Comment by jaki** [comment]
1. Next time, please include a snippet of the failure.
2. This isn't very recent because it was fixed over 24 hours ago: commit fc3b0f97ffa28278dfb30ad020e573511cf9a941.
