### ISSUE TITLE
Performance degradation in YCQL reads operations

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#9630]
Jira Link: [DB-2545](https://yugabyte.atlassian.net/browse/DB-2545)
The CassandraKeyValue workload with 0 writers and 256 readers on a 3-node setup is in the 130ops/sec. 
From the logs of Aug/2/2021, read throughput  is 130182.45 ops/sec.

These numbers used to be in 175-200K range earlier.
We have few numbers from the two runs in last Oct/2020 (one on k8s and one on GCP).
On Oct/1/2020,in k8s 
Read throughput, ops/sec    | 201978.54
Oct/4/2020 - GCP
Read throughput, ops/sec     | 174807.90

The issue may have been introduced around 18th-20th December last year, numbers from the past runs are:
Read throughput, ops/sec: 179182.69 
Read throughput, ops/sec: 142968.19

**Comment by shaharuk-yb** [comment]
landed the diff with the discussed fix. Assigned it to @sonalsagarwal for test

**Comment by mbautin** [comment]
@shaharuk-yb It would be good to add a link to the commit you mentioned.

**Comment by shaharuk-yb** [comment]
the fix was done to the **internal-services** repository. 

**Landed Diff:** https://phabricator.dev.yugabyte.com/D12626
**commit:** https://bitbucket.org/yugabyte/internal-services/commits/042f689a2ca937ead977f51d15b452de86f93025
