### ISSUE TITLE
[k8s]Multi-word hba conf gflag parameter without quotes causes containers to fail on restart

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#9632]
**Issue**
When Universe is configured with a multi-word _ysql_hba_conf_csv_  parameter without quotes,  _yugabyte_ server process fails to start leaving containers in _CrashLoopBackoff_ state.

Incorrect
```
--ysql_hba_conf_csv=local all all trust,host all all 0.0.0.0/0 md5, host all all ::0/0 md5
```
Correct
```
--ysql_hba_conf_csv="local all all trust,host all all 0.0.0.0/0 md5, host all all ::0/0 md5"
```

**Fix**
Modify helm chart and add quotes around _gflag_. This issue was fixed in the master branch, but the fix was not correctly
backported to the 2.6 release branch.

See: https://github.com/yugabyte/charts/commit/92a7e354be3209f693724da6ebb3ecf60cceff14

**Cause**
This _gflag_ override, when rendered into a Kubernetes manifest by the helm chart template engine, produced an incorrectly formatted invocation of the _yb-tserver_ binary. Parameter values without double quotes caused the server binary to interpret the space-separated parameter values as invalid command-line flags.

**Reference Ticket**
[1569](https://yugabyte.zendesk.com/agent/tickets/1569)

**Comment by jvigil-yugabyte** [comment]
fixed in: https://github.com/yugabyte/charts/commit/8bce07336077a3904cdd89ee1e155641317106e3
