### ISSUE TITLE
[YCQL] DESC TABLE is not directly match the "CREATE TABLE" command for static column.

### ISSUE THREAD

**Issue by Tasneem9879** [yugabyte/yugabyte-db#9657]
When we add a static column while creating the table and later do DESC TABLE, the table does not show the column as static.

Also the tablet count information is not displayed.

Below is the behavior:

```
ycqlsh:test> CREATE TABLE user_actions( user_id INT,id int ,ts TIMESTAMP,action TEXT,staticol int static, PRIMARY KEY((user_id,id), ts)) WITH CLUSTERING ORDER BY (ts DESC) AND default_time_to_live = 0 AND transactions = {'enabled': 'true'} and tablets = 10;

ycqlsh:test> DESC TABLE user_actions ;

CREATE TABLE test.user_actions (
user_id int,
id int,
ts timestamp,
action text,
staticol int,
PRIMARY KEY ((user_id, id), ts)
) WITH CLUSTERING ORDER BY (ts DESC)
AND default_time_to_live = 0
AND transactions = {'enabled': 'true'};

```

**Comment by tylarb** [comment]
We have faced this issue with static column and for tablets number per table as well - if a table is created with a different tablet count, the num tablets doesn't show up in the describe either.

**Comment by m-iancu** [comment]
For the `static` issue, it looks like a DB-side issue.
The virtual table `system_schema.columns` has a `kind` column that should be set to `static` for static columns.
`ycqlsh/cqlsh` then uses the info from that table to produce the `DESC` result -- hence showing the wrong output.

Example from vanilla Cassandra:
```
cqlsh:sample> select * from system_schema.columns where table_name='user_actions' allow filtering;

 keyspace_name | table_name   | column_name | clustering_order | column_name_bytes  | kind          | position | type
---------------+--------------+-------------+------------------+--------------------+---------------+----------+-----------
        sample | user_actions |      action |             none |     0x616374696f6e |       regular |       -1 |      text
        sample | user_actions |          id |             none |             0x6964 | partition_key |        1 |       int
        sample | user_actions |    staticol |             none | 0x7374617469636f6c |        static |       -1 |       int
        sample | user_actions |          ts |             desc |             0x7473 |    clustering |        0 | timestamp
        sample | user_actions |     user_id |             none |   0x757365725f6964 | partition_key |        0 |       int
```
Equivalent in YCQL:
```
ycqlsh:foo> select * from system_schema.columns where table_name='user_actions';

 keyspace_name | table_name   | column_name | clustering_order | column_name_bytes | kind          | position | type
---------------+--------------+-------------+------------------+-------------------+---------------+----------+-----------
           foo | user_actions |      action |             none |              null |       regular |       -1 |      text
           foo | user_actions |          id |             none |              null | partition_key |        1 |       int
           foo | user_actions |    staticol |             none |              null |       regular |       -1 |       int
           foo | user_actions |          ts |             desc |              null |    clustering |        0 | timestamp
           foo | user_actions |     user_id |             none |              null | partition_key |        0 |       int
```
Note that for `staticcol` we show `regular`, but it should be `static`.
The problem code is: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/yql_columns_vtable.cc#L92
where we assume all non-key columns are regular columns. We should instead check for and handle static columns there.

The num tablets part might be more difficult, we need to make sure that info is in `system_schema.tables`, and then maybe teach `ycqlsh` to process that. If so that might need a `ycqlsh` change and can be addressed in a follow-up diff.

**Comment by tedyu** [comment]
Static column fix has gone into 2.6 branch.

The tablet count part is outstanding.

**Comment by OlegLoginov** [comment]
Created a new issue for not printed the tablet count:  https://github.com/yugabyte/yugabyte-db/issues/9933

**Comment by OlegLoginov** [comment]
Closing the issue as the problem with static columns is fixed, and the tablet count is covered by another issue: https://github.com/yugabyte/yugabyte-db/issues/9933
