### ISSUE TITLE
[Platform] "/opt/yugaware/test" fails as a custom home directory path for onprem on 2.4.6.0

### ISSUE THREAD

**Issue by shashwat-yb** [yugabyte/yugabyte-db#9664]
Onprem Universe creation fails on 2.4.6.0 portal with onprem provider config with `/opt/yugaware/test`  or `/home/yugabyte/test` as custom home directory unlike 2.6 and 2.7 portals.

Test Plan-
1) Create a onprem provider with custom home directory as `/opt/yugaware/test` or `/home/yugabyte/test`.
2) Create Universe.

cc @VijiYB

**Comment by hsiaosu-yb** [comment]
@shashwat-yb Could you attach the error that you get when creating an universe in this issue?  It'll help us with debugging.

**Comment by hsiaosu-yb** [comment]
Most likely, we need some info on this before proceeding.

**Comment by shashwat-yb** [comment]
Validated this issue on 2.4.6.0 and able to create universe successfully with the above provider configurations successfully.
