### ISSUE TITLE
[Platform] k8s PodDistruptionBudget policy/v1beta1 is deprecated k8s 1.17

### ISSUE THREAD

**Issue by ssung-yugabyte** [yugabyte/yugabyte-db#9681]
In the platform (ybware) helm charts template, pdb.yaml, the apiVersion policy/v1beta1 is deprecated in 1.17. 
Please change it to policy/v1

**Comment by streddy-yb** [comment]
This was addressed as part of https://github.com/yugabyte/yugabyte-db/issues/10597
