### ISSUE TITLE
Cassandra client (ycqlsh) cache not updating on SCHEMA CHANGE event

### ISSUE THREAD

**Issue by gautamsomani** [yugabyte/yugabyte-db#9683]
A user opens 2 sessions to same Cassandra setup using ycqlsh client and connects to same schema/keyspace in both the sessions. In 1st session, the client creates a new table, and drops an existing one. In 2nd session, which was opened before this create and drop was issued, when the client does a desc <keyspace>, the change is not reflected, meaning they cannot see the newly created table and can STILL see the dropped table (though they cannot query it). This should not happen. 

As per Cassandra protocol, when ever there is a change in schema, the client should get a SCHEMA CHANGE event which should force it to update its cache with the latest schema.

Kindly refer point 4.2.6 in https://git-wip-us.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=doc/native_protocol_v4.spec

**Comment by OlegLoginov** [comment]
In the current implementation:
1. SchemaChangeEventResponse - never used.  (Used only TopologyChangeEventResponse to send Node list via TOPOLOGY_CHANGE event.)

2. SchemaChangeResultResponse - used as a part of DDL request response.
See the test:  `TestCQLService::TestSchemaChangeEvent()`

E.g. for request:
```
CREATE KEYSPACE IF NOT EXISTS "kong" WITH REPLICATION =         {'class': 'SimpleStrategy', 'replication_factor': 1}
```
As result the client is expecting 2 CQL messages as the result: CQL RESULT (opcode=8) + CQL EVENT (opcode=0x0c):
```
      BINARY_STRING("\x84\x00\x00\x00\x08" "\x00\x00\x00\x1d" "\x00\x00\x00\x05"
                                "\x00\x07" "CREATED"
                                "\x00\x08" "KEYSPACE"
                                "\x00\x04" "kong");
        BINARY_STRING("\x84\x00\xff\xff\x0c" "\x00\x00\x00\x28"
                                  "\x00\x0d" "SCHEMA_CHANGE"
                                  "\x00\x07" "CREATED"
                                  "\x00\x08" "KEYSPACE"
                                  "\x00\x04" "kong");
```

**Comment by OlegLoginov** [comment]
Note: registration for SCHEMA_EVENT is implemented. See:
```
unique_ptr<CQLResponse> CQLProcessor::ProcessRequest(const RegisterRequest& req) {
  CQLConnectionContext& context =
      static_cast<CQLConnectionContext&>(call_->connection()->context());
  context.add_registered_events(req.events());      <<<<<<<<<<<<<<< Context knows the subscription
  return make_unique<ReadyResponse>(req);
}
```

**Comment by OlegLoginov** [comment]
TODO:
1. Send SchemaChangeEventResponse (see TopologyChangeEventResponse as an example) - via all available connections if the connection has a SCHEMA_CHANGE subscription.
2. Request all TSes to repeat this CQL Event request via there own connections.

**Comment by OlegLoginov** [comment]
Investigating a way to refresh automatically the internal metadata cache in YCQLSH tool.
It's more simple way than to send CHANGE_SCHEMA event from the CQL server through the Cassandra python driver.

**Comment by OlegLoginov** [comment]
Fixed by the commit:  https://github.com/yugabyte/cqlsh/commit/4e0084836b50943de0725a7690a95ded8c36023e

Created release `v3.10-yb-10` in the `yugabyte/cqlsh` repo: https://github.com/yugabyte/cqlsh/releases/tag/v3.10-yb-10
