### ISSUE TITLE
[platform] provisioned IOPS and throughput are not populated for GP3 in the read replica page

### ISSUE THREAD

**Issue by hsiaosu-yb** [yugabyte/yugabyte-db#9692]
To reproduce, use 2.7.x:
Go to any universe, use the action menu on the top right, click on "Add Read Replica".
Select an AWS provider

Note that the default EBS Type would be GP3, but the provisioned IOPS and Throughput are not populated:

![image](https://user-images.githubusercontent.com/82529763/129110204-ebd535e9-622b-4cb3-938d-b8aae890f340.png)

**Comment by hsiaosu-yb** [comment]
Most likely, we can use the same fix in #9451.  But apply it to a different UI page.

**Comment by hsiaosu-yb** [comment]
Note that user would have to manually enter some numbers into these input boxes in order for the read replica task to start.  Without entering these numbers, "create read replica" will silently fail.

**Comment by amhatre99** [comment]
fixed
