### ISSUE TITLE
[YCQL] Ruby(2.5) Cassandra driver(<=2.4)  connection error

### ISSUE THREAD

**Issue by patrick-li** [YugaByte/yugabyte-db#970]
with Ruby v2.5 + Cassandra driver(<=2.4)  to YugaByte DB,  the error is:
```
$ irb

2.5.1 :001 > require 'cassandra'

 => true 

2.5.1 :002 > cluster = Cassandra.cluster(

2.5.1 :003 >             username: '${username}',

2.5.1 :004 >             password: '${password}',

2.5.1 :005 >             hosts: ['10.240.67.126']

2.5.1 :006?>       )
```
Traceback (most recent call last):

       16: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:752:in `call_listener'

       15: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:835:in `block (2 levels) in initialize'

       14: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:790:in `resolve'

       13: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:790:in `each'

       12: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:791:in `block in resolve'

       11: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:752:in `call_listener'

       10: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/ione-1.2.4/lib/ione/future.rb:391:in `block in map'

        9: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:49:in `block in fetch'

        8: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:49:in `map'

        7: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:52:in `block (2 levels) in fetch'

        6: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1296:in `create_keyspace'

        5: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1296:in `each_with_object'

        4: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1296:in `each'

        3: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1298:in `block in create_keyspace'

        2: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1428:in `create_table'

        1: from /Users/hxue/.rvm/gems/ruby-2.5.1/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1328:in `create_compaction_strategy'

NoMethodError (undefined method `delete' for nil:NilClass)

**Comment by kmuthukk** [comment]
@patrick-li reported this stack when running with Ruby 2.4:

```
$ irb
2.4.5 :001 > require 'cassandra'
 => true 
2.4.5 :002 > cluster = Cassandra.cluster(username: '',password: '',hosts: ['10.240.67.126'])
NoMethodError: undefined method `delete' for nil:NilClass
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1328:in `create_compaction_strategy'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1428:in `create_table'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1298:in `block in create_keyspace'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1296:in `each'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1296:in `each_with_object'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:1296:in `create_keyspace'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:52:in `block (2 levels) in fetch'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:49:in `map'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/cluster/schema/fetchers.rb:49:in `block in fetch'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:391:in `block in map'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:752:in `call_listener'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:791:in `block in resolve'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:790:in `each'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:790:in `resolve'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:835:in `block (2 levels) in initialize'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:752:in `call_listener'
... 4 levels...
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:752:in `call_listener'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:791:in `block in resolve'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:790:in `each'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:790:in `resolve'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/future.rb:30:in `fulfill'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/protocol/cql_protocol_handler.rb:305:in `fulfill'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/protocol/cql_protocol_handler.rb:248:in `complete_request'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/protocol/v4.rb:220:in `actual_decode'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/protocol/v4.rb:141:in `decode_body'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/protocol/v4.rb:78:in `<<'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/cassandra-driver-3.2.3/lib/cassandra/protocol/cql_protocol_handler.rb:331:in `receive_data'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/io/base_connection.rb:174:in `read'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/io/io_reactor.rb:518:in `block in tick'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/io/io_reactor.rb:518:in `each'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/io/io_reactor.rb:518:in `tick'
    from /Users/hxue/.rvm/gems/ruby-2.4.5/gems/ione-1.2.4/lib/ione/io/io_reactor.rb:160:in `block in start'
2.4.5 :003 > 
```

**Comment by ttyusupov** [comment]
We’ve found that CQL Ruby Driver requires that `SELECT * FROM system_schema.tables` returns non-null `compaction` and `compression` table options. Currently, these CQL options are not yet supported by YugaByte at a per-table or per-keyspace level (only at cluster level) and YugaByte returns `null` for these columns, which the Ruby driver doesn’t seem to be happy about. However, looks like CQL Ruby Driver only needs them to parse and store, so driver users have the ability to use `to_cql` function for inspecting metadata.
We will provide an updated fork of CQL Ruby Driver with the fix.

**Comment by ttyusupov** [comment]
Commit: https://github.com/YugaByte/cassandra-ruby-driver/commit/bab427ae3c2e7395fec5dd1151a31ed7943482c6

**Comment by ttyusupov** [comment]
You can try our updated fork of CQL Ruby driver - https://rubygems.org/gems/yugabyte-ycql-driver. You can install it with `gem install yugabyte-ycql-driver` and then use `require 'ycq'` instead of `require 'cassandra'` in Ruby scripts.
