### ISSUE TITLE
[Platform] Adjust behaviour in AnsibleConfigureServers.java to handle universes with systemd instead of cron jobs

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#9703]
In the AnsibleConfigureServers.java we are counting nodes without CRON jobs enabled, publishing this metric and generating alert if the count of such nodes is >0.
For universes with systemd this code should be adjusted.

**Comment by Tusheet10Goli** [comment]
Diff out for review - https://phabricator.dev.yugabyte.com/D12574

**Comment by Tusheet10Goli** [comment]
Landed diff - https://phabricator.dev.yugabyte.com/D12574
