### ISSUE TITLE
[platform] stop showing warnings about missing cron job on systemd enabled universes

### ISSUE THREAD

**Issue by hsiaosu-yb** [yugabyte/yugabyte-db#9704]
On universes where systemd is enabled, we show this alert on the health check page.  We should hide this instead.

![image](https://user-images.githubusercontent.com/82529763/129229039-bde91d63-3198-441f-b818-93591279e9c2.png)

**Comment by Tusheet10Goli** [comment]
Diff Landed - https://phabricator.dev.yugabyte.com/D12570
