### ISSUE TITLE
[YBASE RPC Compression] Setting RPC compression with gflags only on master side causes timeouts for create table

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#9706]
Jira Link: [DB-4630](https://yugabyte.atlassian.net/browse/DB-4630)
Steps:

1. On a universe with 2.7.3.0-b53 or higher and set "enable_stream_compression=true" and "stream_compression_algo=1" gflags only on Master side.
2. Creating YSQL or YCQL table throws timeout
3. postgres=# CREATE TABLE SqlSecondaryIndex (k text PRIMARY KEY, v text);
ERROR:  Timed out: Timed out waiting for Table Creation: . Errors from tablet servers: [Timed out (yb/client/client-internal.cc:144): Timed out waiting for Table Creation]
4. ycqlsh> CREATE KEYSPACE ybdemo_keyspace;
ycqlsh> use ybdemo_keyspace;
ycqlsh:ybdemo_keyspace> CREATE TABLE CassandraSecondaryIndex (k varchar, v varchar, primary key (k));
OperationTimedOut: errors={'172.151.46.108': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=172.151.46.108

**Comment by bmatican** [comment]
@nmantrav2 confirmed that this happened on freshly created universes both on b53 (first compression diff) and b57 (second compression diff)

**Comment by rthallamko3** [comment]
@nmantrav2 , Do you know if this is still an issue on master?

**Comment by kripasreenivasan** [comment]
This is no longer an issue.
