### ISSUE TITLE
[YCQL] add Ruby client driver instructions to docs

### ISSUE THREAD

**Issue by patrick-li** [YugaByte/yugabyte-db#971]
https://docs.yugabyte.com/latest/develop/client-drivers/ruby/

**Comment by kmuthukk** [comment]
Thx for reporting @patrick-li.

We should add notes on driver to use for YCQL in the above section.

**Comment by kmuthukk** [comment]
Also see related issue #970.

**Comment by kmuthukk** [comment]
hi @ttyusupov :

Could you please update https://docs.yugabyte.com/latest/develop/client-drivers/ruby/ section as well to add a section for YCQL.

**Comment by ttyusupov** [comment]
Commit: https://github.com/YugaByte/docs/commit/875fad0a58e9afffa2b8a2c05af9ba476fd85e74
