### ISSUE TITLE
[Platform][Alert][UI]: Display Alert Destination name instead of UUID while deleting default Alert Destination

### ISSUE THREAD

**Issue by sridhar-yb** [yugabyte/yugabyte-db#9714]
UI displays warning with UUID when we trying to delete default alert destination 
**"Unable to delete default alert route 77ba224e-9766-4b5c-8f8c-d6b84cd0c9f4, make another route default at first."** 
It would be readable if we display Alert Destination name instead of UUID.
<img width="1792" alt="Screenshot 2021-08-13 at 12 47 39 PM" src="https://user-images.githubusercontent.com/85868962/129321616-19d76906-9353-4f49-b194-9f02f99ec32f.png">

**Comment by SergeyPotachev** [comment]
The issue is on the API side - UI simply shows the error message.
