### ISSUE TITLE
Health and Alerting tab missing in Profile on 2.7.3.0

### ISSUE THREAD

**Issue by pavithra-yb** [yugabyte/yugabyte-db#9722]
Steps:
Goto dev poral

Expected:
Health and Alerting tab should be displayed next to General tab

Actual:
Health and Alerting tab is missing

<img width="1792" alt="Screenshot 2021-08-13 at 4 05 00 PM" src="https://user-images.githubusercontent.com/72492500/129344906-8db1666a-c0b5-47ee-baf3-483563fbcd1d.png">

CC: @VijiYB

**Comment by VijiYB** [comment]
Its because the Health tab moved to Admin -> Alerts. Please enable feature flag to see the Health tab 
cc @hsiaosu-yb @sunilsutarDCE

**Comment by VijiYB** [comment]
https://github.com/yugabyte/yugabyte-db/issues/9722 addressing this issue to bring back Health tab in both places.
