### ISSUE TITLE
[PLATFORM][ALERT]: Support for list alert group with default route

### ISSUE THREAD

**Issue by jatinbhowad** [yugabyte/yugabyte-db#9726]
Currently, alert group with default route get stores with "routeUUID: null". But in listAlertGroup api, routeUUID: "null" returns all (default/ non-default routes) the available alert groups. If route uuid of default route passed for listAlertGroup api, then it returns empty list. Therefore, there is no way to list alert groups with only default route.

**Comment by jatinbhowad** [comment]
Cc: @VijiYB , @sridhar-yb

**Comment by SergeyPotachev** [comment]
Fixed here - https://github.com/yugabyte/yugabyte-db/commit/497c93e782da4b31c5ca4803b065139b211814f0
