### ISSUE TITLE
One TServer crashes forever, doesn't pick up tablets upon restart

### ISSUE THREAD

**Issue by tobiasmuehl** [YugaByte/yugabyte-db#973]
In the middle of a low impact workload one of the TServers went down and did not come up again. Other 2 TServers started dying randomly, eventually (after hours) did recover after manually restarting. Master servers stayed online and functional throughout. 

Number of servers: 3
Replication factor: 3
Clients used: Yedis & YSQL
CPU: Intel(R) Xeon(R) CPU E31245 8x 3.30GHz 
RAM: 16 GB
HDD: 2x 3 TB spindle, XFS, ~140 MB/s

Trying to restart the dead TServer a day after it had died was successful (i.e. it stayed online), but did not load tablets. Leader Count (Num Tablets) stayed at 0 permanently. Yedis seemed to work ok on that TServer after restarting. YSQL did not work on that server (`psql: FATAL:  the database system is shutting down`)

```
./yb-tserver --version
version 1.1.15.0 build 24 revision c886b86fc6624309c065e20bb4a3e70880dc121d build_type RELEASE built at 01 Mar 2019 02:11:00 UTC
```

Comparing the file sizes of the attached disks shows that the dying TServer does not have nearly as much data as the other 2 alive TServers:

yb1 - ok
```
/dev/sda4       2.8T  6.6G  2.8T   1% /home
/dev/sdb        2.8T   37M  2.8T   1% /home2
```

yb2 - dead
```
/dev/sda4       2.8T   30G  2.7T   2% /home
/dev/sdb        2.8T   20G  2.8T   1% /home2
```

yb3 - ok
```
/dev/sda4       2.8T   26G  2.7T   1% /home
/dev/sdb        2.8T   19G  2.8T   1% /home2
```

Log files (it's a lot) https://mega.nz/#!HyhURarD!-cIxRatVP-CimdbUf3rY6IucUtpCNkwov2ttd781oDg

**Comment by kmuthukk** [comment]
Just noting the initial observations here:

There a lot of occurrences of lines of this form, likely because you are running on nodes with HDD (as you mentioned) instead of SSD.
```
$ grep "Time spent Fsync log" yb-tserver.yb2.root.log.INFO.20190309-043637.8862 | wc -l
   49905
```
The lines look like:
```
23:46 $ grep "Time spent Fsync log" yb-tserver.yb2.root.log.INFO.20190309-043637.8862 | head -20
W0309 04:36:37.167191 24926 log.cc:679] Time spent Fsync log took a long time: real 0.115s	user 0.000s	sys 0.000s
W0309 04:36:37.237701 24949 log.cc:679] Time spent Fsync log took a long time: real 0.176s	user 0.000s	sys 0.000s
W0309 04:36:37.261088 24939 log.cc:679] Time spent Fsync log took a long time: real 0.097s	user 0.000s	sys 0.000s
W0309 04:36:37.261090 24946 log.cc:679] Time spent Fsync log took a long time: real 0.127s	user 0.000s	sys 0.000s
W0309 04:36:37.363533 24930 log.cc:679] Time spent Fsync log took a long time: real 0.076s	user 0.000s	sys 0.000s
W0309 04:36:37.472280 24936 log.cc:679] Time spent Fsync log took a long time: real 0.050s	user 0.000s	sys 0.000s
W0309 04:36:37.554839 24941 log.cc:679] Time spent Fsync log took a long time: real 0.053s	user 0.000s	sys 0.000s
W0309 04:36:37.591857 24947 log.cc:679] Time spent Fsync log took a long time: real 0.076s	user 0.000s	sys 0.000s
W0309 04:36:37.727506 24945 log.cc:679] Time spent Fsync log took a long time: real 0.078s	user 0.000s	sys 0.000s
W0309 04:36:37.769883 24929 log.cc:679] Time spent Fsync log took a long time: real 0.110s	user 0.000s	sys 0.000s
W0309 04:36:37.827438 24931 log.cc:679] Time spent Fsync log took a long time: real 0.053s	user 0.000s	sys 0.000s
W0309 04:36:37.971990 24933 log.cc:679] Time spent Fsync log took a long time: real 0.054s	user 0.000s	sys 0.000s
W0309 04:36:38.314584 24926 log.cc:679] Time spent Fsync log took a long time: real 0.054s	user 0.000s	sys 0.000s
W0309 04:36:38.476490 24946 log.cc:679] Time spent Fsync log took a long time: real 0.084s	user 0.000s	sys 0.000s
W0309 04:36:38.529522 24939 log.cc:679] Time spent Fsync log took a long time: real 0.111s	user 0.000s	sys 0.000s
W0309 04:36:38.529522 24949 log.cc:679] Time spent Fsync log took a long time: real 0.135s	user 0.000s	sys 0.000s
W0309 04:36:38.529526 24930 log.cc:679] Time spent Fsync log took a long time: real 0.132s	user 0.000s	sys 0.000s
W0309 04:36:38.629745 24941 log.cc:679] Time spent Fsync log took a long time: real 0.056s	user 0.000s	sys 0.000s
W0309 04:36:38.720510 24947 log.cc:679] Time spent Fsync log took a long time: real 0.050s	user 0.000s	sys 0.000s
W0309 04:36:38.810911 24945 log.cc:679] Time spent Fsync log took a long time: real 0.068s	user 0.000s	sys 0.000s
```

And because of HDDs, I think the flushes aren't able to keep up either, and so writes are getting stalled as well.

```
23:53 $ grep "Stopping writes" yb-tserver.yb2.root.log.INFO.20190307-084225.8862 | wc -l
 2149922
Kannans-MacBook-Pro.local:~/Downloads/yb-logs (1)/yb2-dead
23:54 $ grep "Stopping writes" yb-tserver.yb2.root.log.INFO.20190309-043637.8862 | wc -l
 1466920
Kannans-MacBook-Pro.local:~/Downloads/yb-logs (1)/yb2-dead
23:54 $ grep "Stopping writes" yb-tserver.yb2.root.log.INFO.20190309-043637.8862 | head -10
W0309 04:36:37.064932  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 185 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065090  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 186 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065169  8906 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 186 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065214  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 187 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065320  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 188 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065397  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 189 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065479  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 190 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065609  8906 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 190 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065655  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 191 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
W0309 04:36:37.065773  8896 column_family.cc:590] T 88200ff3f42c41469c1f79cd701cce97: [default] Stopping writes because we have 192 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
```


And there's one later symptom in the logs of these messages about PosgresSQL server exiting with error code 256 in a loop; not sure if that's just a downstream effect of above issues. CC: @mbautin 

```
W0312 04:07:41.524776 28060 pg_wrapper.cc:283] PostgreSQL server exited with code 256
I0312 04:07:41.525002 28060 pg_wrapper.cc:299] Restarting PostgreSQL server
I0312 04:07:41.540904 28060 pg_wrapper.cc:106] PostgreSQL server running as pid 3719
W0312 04:07:41.622445 28060 pg_wrapper.cc:283] PostgreSQL server exited with code 256
I0312 04:07:41.622665 28060 pg_wrapper.cc:299] Restarting PostgreSQL server
I0312 04:07:41.639369 28060 pg_wrapper.cc:106] PostgreSQL server running as pid 3720
W0312 04:07:41.703761 28060 pg_wrapper.cc:283] PostgreSQL server exited with code 256
I0312 04:07:41.703979 28060 pg_wrapper.cc:299] Restarting PostgreSQL server
I0312 04:07:41.720511 28060 pg_wrapper.cc:106] PostgreSQL server running as pid 3721
W0312 04:07:41.779331 28060 pg_wrapper.cc:283] PostgreSQL server exited with code 256
```

@tobiasmuehl - 

a) Are you able to test this on nodes with SSD instead? We are not really able to support HDD based setups effectively as the design is not optimized for HDDs (See https://docs.yugabyte.com/latest/deploy/checklist/#disks)

b) For the YSQL errors, please note that YSQL is still in early beta, and we are doing a lot of stability and scalability improvements on that front. Until then it might be better to keep the YEDIS workload on a separate cluster (without the YSQL initdb step), and the YSQL workload on a separate cluster.

**Comment by tobiasmuehl** [comment]
We could potentially switch to SSDs in the future but really prefer HDDs for the cost benefit. For the workloads we're using HDDs have been fine, all queries resolving within milliseconds. What worries me most is that the crashing TServer is now online again, but didn't "re-integrate" into the cluster - a day after the restart it still doesn't have any tablets (SST file size 0B)

**Comment by mbautin** [comment]
@tobiasmuehl : the FATAL details file seems to indicate that the server ran out of memory -- perhaps that could be an effect of the stalled writes and the accumulation of a large number of memtables.

```
Log file created at: 2019/03/12 03:03:29
Running on machine: yb2
Application fingerprint: version 1.1.15.0 build 24 revision c886b86fc6624309c065e20bb4a3e70880dc121d build_type RELEASE built at 01 Mar 2019 02:11:00 UTC
Running duration (h:mm:ss): 114:21:02
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0312 03:03:29.583220  8885 thread_pool.cc:60] Check failed: _s.ok() Bad status: Runtime error (yb/util/thread.cc:529): Could not create thread: Resource temporarily unavailable (error 11)
F20190312 03:03:29 ../../src/yb/rpc/thread_pool.cc:60] Check failed: _s.ok() Bad status: Runtime error (yb/util/thread.cc:529): Could not create thread: Resource temporarily unavailable (error 11)
    @     0x7f5e3f444c02  yb::LogFatalHandlerSink::send()
    @     0x7f5e3ce5c666  google::LogMessage::SendToLog()
    @     0x7f5e3ce59d5a  google::LogMessage::Flush()
    @     0x7f5e3ce5cc89  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5e414a3572  yb::rpc::ThreadPool::Impl::Enqueue()
    @     0x7f5e4149994a  yb::rpc::ServicePool::QueueInboundCall()
    @     0x7f5e41458019  yb::rpc::Messenger::QueueInboundCall()
    @     0x7f5e414a80b2  yb::rpc::YBInboundConnectionContext::HandleCall()
    @     0x7f5e414410fe  yb::rpc::BinaryCallParser::Parse()
    @     0x7f5e414a6892  yb::rpc::YBInboundConnectionContext::ProcessCalls()
    @     0x7f5e41443da9  yb::rpc::Connection::ProcessReceived()
    @     0x7f5e4149c7c1  yb::rpc::TcpStream::TryProcessReceived()
    @     0x7f5e4149efc6  yb::rpc::TcpStream::ReadHandler()
    @     0x7f5e4149f6dd  yb::rpc::TcpStream::Handler()
    @     0x7f5e40f9f9ab  ev_invoke_pending
    @     0x7f5e40fa2ffa  ev_run
    @     0x7f5e41471979  yb::rpc::Reactor::RunThread()
    @     0x7f5e3f4af916  yb::Thread::SuperviseThread()
    @     0x7f5e47fa6694  start_thread
    @     0x7f5e3aef341d  __clone
    @              (nil)  (unknown)
```

My guess is that this resource shortage caused PostgreSQL's `pg_data` directory to get corrupted (this directory holds no actual data in YugaByte DB, just some configuration files). Would you mind sharing the contents of that directory from the failed server? Also one more thing to try would be to delete that directory from that tserver and restart it -- it will be recreated automatically.

**Comment by tobiasmuehl** [comment]
@mbautin 
[pg_data.tar.gz](https://github.com/YugaByte/yugabyte-db/files/2959946/pg_data.tar.gz)

**Comment by tobiasmuehl** [comment]
> seems to indicate that the server ran out of memory -- perhaps that could be an effect of the stalled writes and the accumulation of a large number of memtables.

At the time of the crash we didn't write more than a handful of records per second, I doubt that too many inserts are the problem. Just deleted the `pg_data` directory and restarted the TServer, server did not pick up tablets.

**Comment by kmuthukk** [comment]
hi @tobiasmuehl --

1) As the logs indicated, I suspect the crashing TServer had too much accumulation of memtables (and flushes and compactions couldn't keep up). Upon restart, in that case, it'll still try to replay those memtables, but likely running into same issue. 

2) If the other two nodes are running fine, I would suggest wiping out the 3rd (dead) yb-tserver's data directory/directories. Suppose the `--fs_data_dirs` gflag for the yb-tserver is `dir1,dir2` then try wiping out `dir1/yb-data/tserver/*` and `dir2/yb-data/tserver/*`. And restart the dead yb-tserver. It should join the cluster and pick up tablets again.

3) For now, run the YSQL (initdb) enabled setup/testing in a separate environment. That is in beta and undergoing rapid development/fixes as we work towards GA. If the Redis workload is more production facing/long running - best to keep that in a separate clean slate environment.

4) A few TServer flags are worth looking into. Can you go to:

http://<any-tserver-ip>:9000/varz

and check for the values of these flags:
```
--memstore_size_mb
--global_memstore_size_mb_max
--rocksdb_compact_flush_rate_limit_bytes_per_sec
--rocksdb_universal_compaction_min_merge_width
--rocksdb_max_background_compactions
--rocksdb_max_background_flushes
```

**Comment by tobiasmuehl** [comment]
Thanks for the suggestions @kmuthukk 

2. That seems to work. Upon wipe and restart the TServer is picking up tablets again. The SST Files Size is still fairly low (writing this a few minutes after restart), but it's not 0 anymore. The node accepts postgres queries and responds correctly.
3. Yes, that makes sense, we will separate the Yedis cluster from the YSQL cluster for the time being.
4. All those are untouched, check below:

```
--memstore_size_mb=128
--global_memstore_size_mb_max=2048
--rocksdb_compact_flush_rate_limit_bytes_per_sec=104857600
--rocksdb_universal_compaction_min_merge_width=4
--rocksdb_max_background_compactions=2
--rocksdb_max_background_flushes=2
```

**Comment by kmuthukk** [comment]
Great to hear @tobiasmuehl .

If you still see `Stopping writes` in your yb-tserver logs then that's a clue that some tuning might be needed. If compactions aren't able to keep up speed, you can try to increase:

`--rocksdb_compact_flush_rate_limit_bytes_per_sec=104857600`

from 100MB to say 200MB.

And also, 
```
--rocksdb_max_background_compactions=2
--rocksdb_max_background_flushes=2
```
to 3 each (given that you have a 16-cpu setup).

Again, SSDs would be best :). But if you find a sweet spot with HDDs, where for your IO pattern that this works fine, then you are fine.

**Comment by tobiasmuehl** [comment]
I cleared the data folders, changed the parameters as suggested and ran more tests, this time only using Yedis. After a few hours of stable and smooth operation 2 of the 3 servers died. Both servers came back online briefly after a manual restart but didn't rebalance data. About an hour after restarting the the crash the third server which originally survived, also crashed. Another hour later all servers crashed. 
The writers (ioredis client in NodeJs) give some hints

```
(node:30040) UnhandledPromiseRejectionWarning: ReplyError: Write(tablet: 28596edc45ef45d7a16b18dfc0b68a04, num_ops: 1, num_attempts: 76, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 1035662.086s (now: 1035662.104s): Illegal state (yb/consensus/consensus.cc:133): Not the leader (error 15)
    at parseError (/root/crappyappy/api/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/crappyappy/api/node_modules/redis-parser/lib/parser.js:302:14)
(node:30040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 49)
(node:30040) UnhandledPromiseRejectionWarning: ReplyError: Write(tablet: 31d3b4b2a882493ab31ce43b3d556f7f, num_ops: 1, num_attempts: 76, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 1035665.205s (now: 1035665.261s): Leader does not have a valid lease. (yb/consensus/consensus.cc:145): This leader has not yet acquired a lease. (error 15)
    at parseError (/root/crappyappy/api/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/crappyappy/api/node_modules/redis-parser/lib/parser.js:302:14)
(node:30040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
```

![Screenshot from 2019-03-18 16-25-34](https://user-images.githubusercontent.com/3341826/54520132-911e8b00-499a-11e9-9690-78979ca0541a.png)


After the crash the write performance was greatly reduced, although not at 0, almost unusable. 

The log files are becoming bigger and bigger. I've only uploaded the most recent files of the log rotation this time: https://mega.nz/#!jiQjyQIL!JHZDIfv4yZQ75jMT-TIT345RMfrXd4Udp8qZsDeDruQ

**Comment by tobiasmuehl** [comment]
Few hours after the TServer had successfully rebalanced data

**Comment by kmuthukk** [comment]
Before the TServer stall, did you see any occurrences of  messages of the form "Stopping writes" e.g.

`[default] Stopping writes because we have 185 immutable memtables (waiting for flush), max_write_buffer_number is set to 2`

in the yb-tserver.INFO files?

**Comment by kmuthukk** [comment]
@tobiasmuehl -- 

1) Still seeing write stalls in the logs you uploaded. Likely because of HDD (instead of SSD). If you run something like iostat -mx 4, you can probably confirm that disk is pretty pegged. So at some point system cannot keep up:

```
Kannans-MacBook-Pro.local:~/Downloads/yb-symlinked-logs
07:40 $ grep "Stalling writes" yb1-tserver.INFO  | wc -l
    1443
Kannans-MacBook-Pro.local:~/Downloads/yb-symlinked-logs
07:40 $ grep "Stalling writes" yb1-tserver.INFO  | head -3
W0317 23:09:49.804651 16836 column_family.cc:643] T 3742e31aeda14b0c8cec0fbacf72102d: [default] Stalling writes because we have 29 level-0 files rate 2097152
W0317 23:09:51.275892 16717 column_family.cc:643] T 28596edc45ef45d7a16b18dfc0b68a04: [default] Stalling writes because we have 28 level-0 files rate 2097152
W0317 23:09:51.627717 16834 column_family.cc:643] T 28596edc45ef45d7a16b18dfc0b68a04: [default] Stalling writes because we have 29 level-0 files rate 2097152
```

2) In such a situation, if a node is deemed dead because it hasn't been able to communicate with its peers in a while, then it'll be dead dead. This later increases load on the system even further because it'll try to bootstrap data from the peers (making the disk IO bottleneck only worse). Maybe you can increase the time window within which a peer is considered dead. 

You can consider increasing this tserver gflag:

`--follower_unavailable_considered_failed_sec` from default 300 (5 mins) to say 600 (10 mins)


3) When things get unstable, we also see a bunch of leader election storms:
```
I0318 10:07:17.514173 30480 raft_consensus.cc:801] T be4283f576444466a18ac56bf153c394 P 3a6f4ba810a14ee6a8374196d3f4a751 [term 4 LEARNER]: ReportFailDetected: Starting NORMAL_ELECTION...
I0318 10:07:17.514190 30480 raft_consensus.cc:443] T be4283f576444466a18ac56bf153c394 P 3a6f4ba810a14ee6a8374196d3f4a751 [term 4 LEARNER]: Not starting pre-election -- role is 2, pending = 0, active_role=2
I0318 10:07:17.772918 30480 raft_consensus.cc:801] T 57b1488889484ef59123a951b28d6145 P 3a6f4ba810a14ee6a8374196d3f4a751 [term 2 LEARNER]: ReportFailDetected: Starting NORMAL_ELECTION...
I0318 10:07:17.772943 30480 raft_consensus.cc:443] T 57b1488889484ef59123a951b28d6145 P 3a6f4ba810a14ee6a8374196d3f4a751 [term 2 LEARNER]: Not starting pre-election -- role is 2, pending = 1, active_role=2
I0318 10:07:18.080301 30480 raft_consensus.cc:801] T 3742e31aeda14b0c8cec0fbacf72102d P 3a6f4ba810a14ee6a8374196d3f4a751 [term 5 FOLLOWER]: ReportFailDetected: Starting NORMAL_ELECTION...
I0318 10:07:18.080327 30480 raft_consensus.cc:483] T 3742e31aeda14b0c8cec0fbacf72102d P 3a6f4ba810a14ee6a8374196d3f4a751 [term 5 FOLLOWER]: Triggering leader pre-election, mode=NORMAL_ELECTION
I0318 10:07:18.080348 30480 raft_consensus.cc:2843] T 3742e31aeda14b0c8cec0fbacf72102d P 3a6f4ba810a14ee6a8374196d3f4a751 [term 5 FOLLOWER]: Snoozing failure detection for 3.499s
```

I see that you are using 1.1.15. This problem should be better with 1.2.x version because of this fix: #604 . You can try `https://downloads.yugabyte.com/yugabyte-ce-1.2.0.1-linux.tar.gz` instead.

But real problem seems to be the HDD disk bottleneck for this workload.

**Comment by ttyusupov** [comment]
@tobiasmuehl , were you able to recheck with the latest version?

**Comment by tobiasmuehl** [comment]
@ttyusupov Sadly not, the whole project was since abandoned
