### ISSUE TITLE
Failed to automatically split tablets while online by setting --tablet_split_size_threshold_bytes <bytes>

### ISSUE THREAD

**Issue by gordfly163** [yugabyte/yugabyte-db#9732]
I failed to set the Gflags of --tablet_split_size_threshold_bytes <bytes> following on below comands:
https://docs.yugabyte.com/latest/reference/configuration/yb-master/#sharding-flags
yb-admin --master_addresses <master-addresses> --tablet_split_size_threshold_bytes <bytes>

ERROR: unknown command line flag 'tablet_split_size_threshold_bytes'

is there anyone met the similar error and have some hit about how to solve it? Thanks.

**Comment by ddorian** [comment]
> ERROR: unknown command line flag 'tablet_split_size_threshold_bytes'

Seems like this is an unknown flag on `yb-admin`. 

You should set that flag on `yb-master` binary.

Can you try that and comment if it still doesn't work ?
