### ISSUE TITLE
[Docs] Modify the download section for all the sample datasets page.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yugabyte-db#9737]
Currently , this section: https://docs.yugabyte.com/latest/sample-data/chinook/#1-download-the-sql-scripts directs the users to download the database from the repo : https://github.com/yugabyte/yugabyte-db/tree/master/sample .
However, it is not necessary to download the scripts since it is already available under the "share" directory. 

To-do: Modify all 4 pages accessed from Sample Datasets https://docs.yugabyte.com/latest/sample-data/  by mentioning the scripts as a reference and not necessary to download it for the exercise.

**Comment by ddhodge** [comment]
All 4 datasets accessed from Sample Datasets https://docs.yugabyte.com/latest/sample-data/ need to be updated as described.

The Retail Analytics Develop page (https://docs.yugabyte.com/latest/develop/realworld-apps/retail-analytics/) needs to be similarly updated as the dataset also does not need to be downloaded.

As Retail Analytics, which is used both in Quick Start (https://docs.yugabyte.com/latest/quick-start/explore/ysql/) and Develop is also included in share/ directory of YB installation, it should be added to the Sample Datasets page with the other 4.
