### ISSUE TITLE
[Docs] verify pages tagged as beta

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#9741]
## Beta tags to be removed

The following pages **have beta tags, but shouldn't**:

- [Preparing Azure environment](https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure)
- Platform HA in [latest](https://docs.yugabyte.com/latest/yugabyte-platform/manage-deployments/high-availability) and [stable](https://docs.yugabyte.com/stable/yugabyte-platform/manage-deployments/high-availability)

## Beta list for latest (v2.7)

Please confirm that the following pages still require beta tags:

- [CDC](https://docs.yugabyte.com/latest/architecture/docdb-replication/change-data-capture)
- [PITR](https://docs.yugabyte.com/latest/explore/cluster-management/point-in-time-recovery-ysql)
- [CDC generic](https://docs.yugabyte.com/latest/integrations/change-data-capture/cdc-generic)
- [CDC kafka](https://docs.yugabyte.com/latest/integrations/change-data-capture/cdc-kafka)
- ~~[Spring data YB](https://docs.yugabyte.com/latest/reference/drivers/spring-data-yugabytedb)~~ (delete per Nikhil)
- [Platform HA](https://docs.yugabyte.com/latest/yugabyte-platform/manage-deployments/high-availability)

- Cloud:
  - [landing page](https://docs.yugabyte.com/latest/yugabyte-cloud/)
  - [connect to clusters](https://docs.yugabyte.com/latest/yugabyte-cloud/connect-to-clusters)
  - [create clusters](https://docs.yugabyte.com/latest/yugabyte-cloud/create-clusters)
  - [create DBs](https://docs.yugabyte.com/latest/yugabyte-cloud/create-databases)
  - [free tier](https://docs.yugabyte.com/latest/yugabyte-cloud/free-tier)
  - [manage access](https://docs.yugabyte.com/latest/yugabyte-cloud/manage-access)
  - [monitor clusters](https://docs.yugabyte.com/latest/yugabyte-cloud/monitor-clusters)

## Beta list for stable (v2.6)

Please confirm that the following pages still require beta tags:

- [PITR](https://docs.yugabyte.com/stable/explore/backup-restore/point-in-time-recovery-ysql)
- [CDC](https://docs.yugabyte.com/stable/architecture/docdb-replication/change-data-capture)
- [CDC generic](https://docs.yugabyte.com/stable/integrations/change-data-capture/cdc-generic)
- [CDC Kafka](https://docs.yugabyte.com/stable/integrations/change-data-capture/cdc-kafka)
- ~~[Spring data YB](https://docs.yugabyte.com/stable/reference/drivers/spring-data-yugabytedb)~~ (delete per Nikhil)

- Cloud:
  - [landing page](https://docs.yugabyte.com/stable/yugabyte-cloud/)
  - [connect to clusters](https://docs.yugabyte.com/stable/yugabyte-cloud/connect-to-clusters)
  - [create clusters](https://docs.yugabyte.com/stable/yugabyte-cloud/create-clusters)
  - [create DBs](https://docs.yugabyte.com/stable/yugabyte-cloud/create-databases)
  - [free tier](https://docs.yugabyte.com/stable/yugabyte-cloud/free-tier)
  - [manage access](https://docs.yugabyte.com/stable/yugabyte-cloud/manage-access)
  - [monitor clusters](https://docs.yugabyte.com/stable/yugabyte-cloud/monitor-clusters)

**Comment by bmatican** [comment]
CDC pages for sure! cc @kneeraj 

For PITR, do you think we could split between YCQL and YSQL and tag the latter as Beta?

**Comment by polarweasel** [comment]
> For PITR, do you think we could split between YCQL and YSQL and tag the latter as Beta?

@bmatican that's possible, yes. Let me know if you want to do that, but isn't YSQL nearly at feature parity at this point?
