### ISSUE TITLE
[platform] reset config should also restore the number of nodes

### ISSUE THREAD

**Issue by hsiaosu-yb** [yugabyte/yugabyte-db#9743]
To reproduce, use any universe and go to "edit universe".  Increase the number of nodes in the UI, say from 3->6.  Notice that the number of nodes in the AZ on the right hand side also increase.  Now click on the red "Reset Config" link on the top right.  The number of nodes in the AZ goes back to its original count (1, 1, 1).  But the number of nodes on the left still shows 6 instead of 3.

![image](https://user-images.githubusercontent.com/82529763/129631947-f98487a8-b5d9-4ace-8c5f-5637e638483d.png)

**Comment by hsiaosu-yb** [comment]
Workaround is to hit the browser's refresh button.

**Comment by rajmaddy89** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/9863
