### ISSUE TITLE
[Docs] update TPC-C benchmark section

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#9745]
Update the [Benchmark > TPC-C section](https://docs.yugabyte.com/latest/benchmark/tpcc-ysql/) with the information in [this Google doc](https://docs.google.com/spreadsheets/d/1gPPrML-R0CvDr-AVeK-tx3gMlDaGczpwIpgBGnMs4LA/edit#gid=1608563644).

In particular, the _Optimizations_, _Published Results_, and _Cluster Configuration_ tabs are what we're looking for. If we need more information on the results, use the _Phase 3_ tab.

ALSO...take a careful read over each of the tabs in step 3 ("3. Run the TPC-C benchmark") to make sure the machine types are all up to date. The 10,000 tab has a mismatch, so check that and all the others.

(@ameyb and @dcomingore will be reviewers.)

**Comment by dcomingore** [comment]
I have this - have npm running locally now. Just need to make doc changes and submit PR.
