### ISSUE TITLE
[YSQL] --ysql_pg_conf_csv does not work as it should

### ISSUE THREAD

**Issue by radekg** [yugabyte/yugabyte-db#9767]
I have the following following configuration I want to pass to my YugabyteDB:

```
shared_preload_libraries = extensions1,extension2
```

I am using the `--ysql_pg_conf_csv` configuration setting. Using either of:

- `--ysql_pg_conf_csv='shared_preload_libraries=extensions1,extension2'`
- `--ysql_pg_conf_csv='shared_preload_libraries="extensions1,extension2"'`
- `--ysql_pg_conf_csv='shared_preload_libraries=""extensions1,extension2""'`

Results in the invalid config being written as:

```
# Add settings for extensions here
shared_preload_libraries=extension1
extension2
```

The only way to keep the values in a single line is to write the config option as: `--ysql_pg_conf_csv='"shared_preload_libraries=""extensions1,extension2""'"`, however - this causes a FATAL error in Postgres because Postgres does not support double quoted values in this config file.

```
2021-08-18 13:13:18.326 GMT [292] LOG:  syntax error in file "/mnt/data/tserver/pg_data/ysql_pg.conf" line 699, near token """
2021-08-18 13:13:18.326 GMT [292] FATAL:  configuration file "/mnt/data/tserver/pg_data/ysql_pg.conf" contains errors
```

I also would like to question the decision to write the settings configured via that flag to the file anyway, especially the ones already picked up for the `-c` switches in the `PgWrapper::Start()`. The `WritePostgresConfig(const PgProcessConf& conf)` should either use the settings already discovered in `PgWrapper::Start()` and do not parse the config values using `ReadCSVValues` / `ReadCommaSeparatedValues` again OR skip the values configured previously with the `-c` switches in `PgWrapper::Start()`.

Regardless, it's fair to say the CSV parser for the `ysql_pg.conf` is not working today and is probably not a good idea at all.

**Comment by radekg** [comment]
The actual parser should allow taking a string and splitting by comma ONLY when the comma is outside of single quotes. Neither `ReadCSVValues` nor `ReadCommaSeparatedValues` does this today.

**Comment by ajcaldera1** [comment]
So the parser for the flags `ysql_pg_conf_csv` and `ysql_hba_conf_csv` have the following rules: The comma delimiter indicates a new-line, thus a different entry in those files. So if the entry being passed to either of those fields contains a comma, then it must be enclosed in double-quotes. Thus your entry for multiple `shared_preload_libraries` should look like this:
```
--ysql_pg_conf_csv='"shared_preload_libraries=extension1,extension2"'
```
Subsequent values passed on this line that do not contain the comma delimiter would look like this:
```
--ysql_pg_conf_csv='log_connections=on,"shared_preload_libraries=extension1,extension2",log_disconnections=on,log_duration=on'
```
If your entry has a double-quote in it -- such as entries that pass in parameters for ldap in `ysql_pg_hba_conf_csv`, then you would "escape" the double-quotes with a containing set of double-quotes.  See example at: https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#ysql-hba-conf-csv

**Comment by radekg** [comment]
The solution above works as expected. Thank you.
