### ISSUE TITLE
[YSQL] Key not found error in some yb sample apps

### ISSUE THREAD

**Issue by m-iancu** [YugaByte/yugabyte-db#977]
Running the sample apps locally (with some unrelated local modifications): 
```
java -jar ./target/yb-sample-apps.jar --workload SqlSnapshotTxns --nodes 127.0.0.1:5433
```
and saw a couple of keys not found errors. No other (different) errors were reported. 
```
283365 [Thread-3] FATAL com.yugabyte.sample.apps.SqlSnapshotTxns  - Read key: 14a419e0-fcb0-4f61-9ac5-16c1b9c68b07:103227 expected 1 row in result, got 0
```

To replicate, get the latest sample apps from https://github.com/YugaByte/yb-sample-apps

Build with
```
mvn clean package -DskipTests -DskipDockerBuild
```

Start a (ysql enabled) cluster --  `rf 1` below should not be required, also in latest master ysql should be enabled by default otherwise use `enable_ysql` flag.
```
./bin/yb-ctl destroy; ./bin/yb-ctl --rf 1 create
```

Run the the SqlSnapshotTxns app: 
```
java -jar ./target/yb-sample-apps.jar --workload SqlSnapshotTxns --nodes 127.0.0.1:5433
```
Should (rarely) see the error mentioned above. Also, the missing key will be found when queried a moment later.

**Comment by robertpang** [comment]
This also happens to SqlInsert sample app:

```
$ java -jar target/yb-sample-apps.jar --workload SqlInserts --nodes 127.0.0.1:5433 --nouuid --num_unique_keys 50000000 --num_writes 50000000 --num_threads_write 2 --num_threads_read 2
...
10656 [Thread-5] ERROR com.yugabyte.sample.apps.SqlInserts  - Read key: key:3121 expected 1 row in result, got 0
```

**Comment by robertpang** [comment]
Tested the same with CassandraKeyValue sample app with the table pre-created with transactions enabled. The missing key issue did not happen.

**Comment by mbautin** [comment]
Tried to remove the multithreaded use of a single PreparedStatement (which is anyway the right thing to do in JDBC apps, as far as I know) -- https://github.com/YugaByte/yb-sample-apps/pull/13/files, but still got errors in 5 runs out of 8: https://gist.githubusercontent.com/mbautin/6e3a2c8c2540e4a34d2b9c6f56265f08/raw

**Comment by mbautin** [comment]
Also tried to create a cluster with `--tserver_flags pg_transactions_enabled=false` flag to `yb-ctl` and repeat the test. The issue does not occur in this case in 9 runs of the sample app: https://gist.githubusercontent.com/mbautin/6b3a1fdf8d36704bd413b8da3c28ad67/raw
