### ISSUE TITLE
[docs] bad link on AWS Cloudformation page

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#9770]
On page https://docs.yugabyte.com/latest/deploy/public-clouds/aws/cloudformation/ the link in "Here is an example using https://github.com/yugabyte/aws-cloudformation/blob/master/yugabyte_cloudformation_i3_example.yaml" points to a non-existent URL.

**Comment by lizayugabyte** [comment]
@bhavin192 @baba230896 , this [doc](https://docs.yugabyte.com/latest/deploy/public-clouds/aws/cloudformation/#prerequisites) has a link to yugabyte_cloudformation_i3_example.yaml file that no longer exists. Is there a different example that we can reference here?

**Comment by bhavin192** [comment]
We can reference https://github.com/yugabyte/aws-cloudformation/blob/master/yugabyte_ephemeral_nvme_cloudformation.yaml instead of the i3 one. Both are similar, the newer one is generic and supports a couple of more instance types than i3.
