### ISSUE TITLE
[docdb] Tablet Splitting: Wait for all peers to finish compacting during throttling

### ISSUE THREAD

**Issue by hulien22** [yugabyte/yugabyte-db#9782]
Tablet splitting throttling was added in #6667, however we currently consider a tablet split done once any peer from each child tablet has marked itself compacted. This should be changed to wait until all peers are fully compacted.

Will likely need to change the `processing_tablets_to_split_children_` map to keep track of all the peers, or have some new check that all peers are done compacting.  

Just to clarify, the goal is:
1. Don’t split the (child) tablet until all its replicas are fully compacted.
2. Treat the parent tablet as still being split until all its children's tablets replicas are fully compacted for throttling purposes.

**Comment by ttyusupov** [comment]
>> That means we will not split the tablet if one replica is offline until it comes back online and got split and fully compacted?
> IMO, yes, but we should also enhance the split scheduling logic
this feels similar to the constraints we have on the LB already, where if a TS is down, but was serving some tablets, then during the 0-15m unavaiability window, we’ll have to wait.

**Comment by nimwijetunga** [comment]
Closed by commit: https://github.com/yugabyte/yugabyte-db/commit/fdd50e9bddcd629267fbda20767d1e73ef7a690c
