### ISSUE TITLE
Universe Actions-> Add Read Replica  is failing on 2.6.1.0-b23

### ISSUE THREAD

**Issue by christinjohn-yb** [yugabyte/yugabyte-db#9786]
When we try to add read replica to a universe post creation it fails with the below error.
![Screenshot 2021-08-20 at 3 34 20 PM](https://user-images.githubusercontent.com/87365762/130217349-795730cd-4c6b-4e89-9dae-3673f3d2a62c.png)
The above issue is seen in version 2.6.1.0-b23

**Comment by christinjohn-yb** [comment]
Changes landed by https://phabricator.dev.yugabyte.com/D12714

**Comment by hsiaosu-yb** [comment]
Change is on master
