### ISSUE TITLE
[PITR] PITR collapses and goes out of action.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#9790]
Version: 2.6.1.0-b24
In http://portal.aws-stable.dev.yugabyte.com/universes/ec67b75c-215e-4dd9-8ed5-0de18f320412
Steps:
1. Create a keyspace and table(lets say table-1), insert some rows.
2. Create a snapshot schedule and get absolute time, lets say [abs-time]
3. Again insert some data into table and restore back to [abs-time] - works fine
4. Create one more table(lets say table-2) and insert some data and delete previous table(table-1)
5. Restore back to [abs-time] - works fine (means now you have table-1)
6. Rename column and restore back with relative time(lets say minus 2m)
7. Observe the list_snapshots output data -  
Restoration snapshot goes to RESTORING state, after sometime(~4min) it goes to FAILED state and one of the SNAPSHOT UUID’s state goes to CREATING state and after that it stops to create snapshots.
       
In other universe(http://portal.aws-stable.dev.yugabyte.com/universes/99726092-9b17-4ed4-b982-db9615b25a25/nodes) with same steps it lost restoration snapshots and forgets retention period and all upcoming snapshots goes to CREATING state.

**Comment by bmatican** [comment]
@Arjun-yb can you confirm if maybe the time at 6) but minus 2 minutes, could have taken you before the first restore at 5) ? we don't support multiple restores like that

@spolitov do we have or need some safeguard maybe, that we're not asked to restore, to before some previous restore?

**Comment by Arjun-yb** [comment]
@bmatican I collected absolute time(at step-2) only once which is after creating a snapshot schedule. I used same time at step-3 and step-5. But at step-6 I used relative time which is the time after the absolute time(at step-2). If the relative time is before the absolute time(at step-2), it would have thrown an error.

**Comment by sanketkedia** [comment]
This was fixed by [commit](https://github.com/yugabyte/yugabyte-db/commit/fd15c4eee179b0d4996392e1a25f31d41b2074b5) to actually allow for forward restores of the above type.
