### ISSUE TITLE
Update to latest Node.js driver for YSQL

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#9834]
# Tasks
|Done ✅|Name|Notes|Link|
| - | - | - | - |
|✅ | Verify with SSL on YB Cloud | Self Singed certs is not supported  |  |
| ✅| Update documentation |  [github issue](https://github.com/yugabyte/yugabyte-db/issues/10011) |  |

|Driver version |YB version|
| - | - |
| ^8.7.1 |  2.7.2 and older |
|  |  |

**Comment by nchandrappa** [comment]
SSL Mode | Client Driver Behavior
-- | --
disable | Supported
allow | Not supported
prefer | Not supported
require (Default) | Supported
verify-ca | Supported. Self Signed Certificates are not supported
verify-full | Supported
