### ISSUE TITLE
Update to the latest C# driver for YSQL

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#9839]
# Tasks
|Done ✅|Name|Notes|Link|
| - | - | - | - |
| ✅ | Verify with SSL on YB Cloud | Self Singed certs is not supported  |  |
| ✅ | Update documentation |  | [GH Issue](https://github.com/yugabyte/yugabyte-db/issues/10073) |

|Driver version |YB version|
| - | - |
| 5.0.7 | 2.7.2 and older |
|  |  |

**Comment by Sfurti-yb** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9d2834c3-7fff-9796-88f8-54810d608c0f"><div dir="ltr" style="margin-left:0.75pt;" align="left">

SSL Mode | Client Driver Behavior
-- | --
disable | Supported
allow | Not Supported
prefer | Supported
require | Supported
verify-ca | Supported*. Self Signed Certificates are not supported
verify-full | Supported*. Self Signed Certificates are not supported

</div><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">*Note</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> - Npgsql driver does not support the strings verify-ca and verify-full when specifying SSL mode. </span><span style="font-size:12pt;font-family:Arial;color:#152849;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.NET Npgsql driver validates certificates differently from other PostgreSQL drivers. When SSL mode &lsquo;require&rsquo; is specified, it verifies the certificate by default (working like verify-ca or verify-full), and fails for self signed certificates, unless overridden(by specifying Trust Server Certificate=true) in which case it bypasses walking the certificate chain to validate trust and hence works like other drivers&rsquo; &lsquo;require&rsquo; mode. In this case Root-CA certificate is not required to be configured.</span></p></b><br class="Apple-interchange-newline">
