### ISSUE TITLE
[YW] Provide method to set imagePullPolicy for postgres, nginx, prometheus 

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#9848]
While working with a customer, the security policy of their kubernetes cluster mandated that images must be `Always` pulled instead of the default of `IfNotPresent`. 

As a workaround I added the following line under each container image specification:
```
imagePullPolicy: {{ .Values.image.pullPolicy }}
```

**Comment by streddy-yb** [comment]
Addressed as part of https://github.com/yugabyte/charts/commit/9ba25ba41545217019dd7973f8cfe000bd3e6411
