### ISSUE TITLE
[Platform][UI] Suggested Paths for Node Cert Path and Key are reversed in Cert creation wizard

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#9850]
When creating a new CA signed certificate, the suggested paths for Node Cert and Node Key are reversed. Currently, for `Database Node Certificate Path`, the suggested path is `/opt/yugabyte/keys/cert1/node.key `but it should be `/opt/yugabyte/keys/cert1/node.crt`. And, for Database Node Certificate Private Key,  the suggested path is `/opt/yugabyte/keys/cert1/node.crt` but it should be `/opt/yugabyte/keys/cert1/node.key`. 

How to repro:
- Go to Configs->Security->Encryption-in-Transit->Add Certificate
- Select "CA Signed" 

![image](https://user-images.githubusercontent.com/68868569/131165793-7852b5b3-1861-408e-866c-d55cdf8e1389.png)

**Comment by rajmaddy89** [comment]
https://github.com/yugabyte/yugabyte-db/pull/9864
