### ISSUE TITLE
[docs] find and fix all double-slash links

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#9858]
We have quite a few links of the form `..//path/to/file` and that double slash is suddenly causing problems with the sitewide link checker. Even though most browsers will deal with them, they're incorrect, and it should be a relatively painless task to find and fix them all...

For example: [line 372 of any-all.md](https://github.com/polarweasel/yugabyte-db/blob/102581dc5476f92aca5f95bd3d53528e430c5539/docs/content/latest/api/ysql/datatypes/type_array/functions-operators/any-all.md?plain=1#L372)

**Comment by jaki** [comment]
This is a nice change, but I'm curious whether they're really "incorrect".  I have a feeling that, in addition to browsers, the HTTP standard doesn't care about double slashes.

I looked in https://datatracker.ietf.org/doc/html/rfc2616#section-5.1.2 and found nothing about double slashes.

**Comment by polarweasel** [comment]
@jaki be that as it may (and I do think that a server probably _should_ play nicely with repeated slashes in a path), the unexpected slashes are messing with the tool, and it's an easy fix.

**Comment by polarweasel** [comment]
(RFC 2396 is the actual standard we're looking for, and it specifies a single slash as path separator. https://datatracker.ietf.org/doc/html/rfc2396#section-3.3)

**Comment by jaki** [comment]
Is this done by pull #9879?

**Comment by bllewell** [comment]
Not yet. PR #9879 looked only in "latest". When it was too late to add to the scope of that PR, @polarweasel asked me to do the same for "stable". My next PR wil do that. Should be merged by '2021-08-31 04:00 UDT'::timestaptz.

**Comment by bllewell** [comment]
Fixed in "latest" by [PR #9879](https://github.com/yugabyte/yugabyte-db/pull/9879) and in "stable" by [PR #9882](https://github.com/yugabyte/yugabyte-db/pull/9882) but _only_ in the YSQL doc subtrees. The `\\` formal problem might persist outside of these subtrees.

**Comment by polarweasel** [comment]
And I can't find anything outside of those in latest and stable, so I'm going to close this issue. Thank you for the fixes, @bllewell!
