### ISSUE TITLE
ysql: fix miscalculation of limit using offset

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#9859]
Jira Link: [DB-1956](https://yugabyte.atlassian.net/browse/DB-1956)
Postgres sends an RPC to a tserver to retrieve rows.  It sets a limit in the PgsqlReadRequestPB to indicate the max number of rows it wants in the response.  The number shouldn't be too low or else there would be overhead from many RPCs; the number shouldn't be too high or else timeouts or memory may become issues.  Therefore, the flag for this limit, `ysql_prefetch_limit`, is, by default, set to a moderate number 1024.

However, if the user specifies LIMIT or OFFSET in the query, there is a further optimization to use that number as the limit if it is smaller.  But the math was not done well because it just adds user-limit and user-offset together.

The questionable part is offset.  It sort of makes sense if both LIMIT and OFFSET are specified because we can then retrieve everything in one RPC call (provided the sum was less than the `ysql_prefetch_limit`); on the other hand, it does not make sense if only OFFSET is specified since limit is unbounded, so it should act more like a full scan.  The worst case is when OFFSET is set to 1 because limit in the PB request is set to 1, meaning one RPC call for each row (minus one because the offset omits the first row).

Here, I show that the timing gets really bad with OFFSET 1:

```
yugabyte=# create table t (i int);
CREATE TABLE
yugabyte=# insert into t values (generate_series(1, 10000));
INSERT 0 10000
yugabyte=# \timing on
Timing is on.
yugabyte=# select from t;
--
(10000 rows)

Time: 125.623 ms
yugabyte=# select from t offset 1;
--
(9999 rows)

Time: 13738.745 ms (00:13.739)
```

Copy-paste version:

```sql
create table t (i int);
insert into t values (generate_series(1, 10000));
\timing on
select from t;
select from t offset 1;
```

You can `set yb_debug_log_docdb_requests = on` to see the read requests in postgres logs.

One idea to fix this is to remove offset from the calculation and just use user-specified LIMIT, ignoring user-specified OFFSET.  However, that has a similar problem when LIMIT is 1 and OFFSET is very high.  Therefore, the solution will likely have to be more in-depth.  One idea is to first request user-offset, then request min(user-limit, ysql_prefetch_limit) until completion.  Further optimization on top of that could be

- don't return rows on the offset request (and mark the offset read request so that tserver knows it's an offset request)
- send the offset request and limit request in the same first read RPC

**Comment by sushantrmishra** [comment]
**Roundtrips in both scenarion are the same :** 

```
yugabyte=# explain (analyze, dist) select from t;
                                             QUERY PLAN
-----------------------------------------------------------------------------------------------------
 Seq Scan on t  (cost=0.00..100.00 rows=1000 width=0) (actual time=2.144..17.797 rows=10000 loops=1)
   Storage Table Read Requests: 12
   Storage Table Execution Time: 17.000 ms
 Planning Time: 0.035 ms
 Execution Time: 18.703 ms
 Storage Read Requests: 12
 Storage Write Requests: 0
 Storage Execution Time: 17.000 ms
 Peak Memory Usage: 0 kB
(9 rows)

Time: 19.435 ms
yugabyte=#
```


```
yugabyte=# explain (analyze, dist) select from t offset 1;
                                                QUERY PLAN
-----------------------------------------------------------------------------------------------------------
 Limit  (cost=0.10..100.00 rows=999 width=0) (actual time=2.170..17.538 rows=9999 loops=1)
   ->  Seq Scan on t  (cost=0.00..100.00 rows=1000 width=0) (actual time=2.167..15.916 rows=10000 loops=1)
         Storage Table Read Requests: 12
         Storage Table Execution Time: 13.000 ms
 Planning Time: 0.035 ms
 Execution Time: 18.348 ms
 Storage Read Requests: 12
 Storage Write Requests: 0
 Storage Execution Time: 13.000 ms
 Peak Memory Usage: 0 kB
(10 rows)

Time: 19.048 ms
```
