### ISSUE TITLE
Remove all unnecessary files created by per-tserver local initdb

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#986]

**Comment by ndeodhar** [comment]
Background:
We run initdb on each tserver when tserver is started up. This initdb creates the postgres directory structure in disk-1/pg_data. Since we don't actually write data here, we don't need all these files to be created.

There are couple of things that we need to do here:
1. Ensure that locale is set correctly for postgres and initdb. We should set these environment variables before starting both:
LANG=C
LC_COLLATE=C
LC_CTYPE=C
LC_MESSAGES=C
LC_MONETARY=C
LC_NUMERIC=C
LC_TIME=C
This can be done in PgWrapper::SetCommonEnv()

2. We can clean up pg_data and only create the files that are needed. This will need more investigation - we may only need pg config files and files needed for creating temporary tables.

**Comment by d-uspenskiy** [comment]
`initdb` calls `postgres` internally with `--boot` flag:

```
"/home/duspensky/code/yugabyte/build/debug-gcc-dynamic-enterprise-ninja/postgres/bin/postgres" --boot -x1 -X 16777216  -F
``` 

and sends long list of queries (about 13349 lines) to stdin like:

```
# PostgreSQL 11
create pg_proc 1255 bootstrap rowtype_oid 81
 (
 proname = name ,
 pronamespace = oid ,
 proowner = oid ,
 prolang = oid ,
 procost = float4 ,
 prorows = float4 ,
 provariadic = oid ,
 protransform = regproc ,
 prokind = char ,
...
declare unique index pg_subscription_subname_index 6115 on pg_subscription using btree(subdbid oid_ops, subname name_ops)
declare primary index pg_subscription_rel_srrelid_srsubid_index 6117 on pg_subscription_rel using btree(srrelid oid_ops, srsubid oid_ops)
build indices
```

this command creates data files in `node-1/disk-1/pg_data/` subdirectories like:
```
./node-1/disk-1/pg_data/base/1/3598
./node-1/disk-1/pg_data/base/1/2832_vm
./node-1/disk-1/pg_data/base/1/2612_fsm
./node-1/disk-1/pg_data/base/1/2617_vm
...
./node-1/disk-1/pg_data/global
./node-1/disk-1/pg_data/global/2676
./node-1/disk-1/pg_data/global/1260_vm
...
```

So it looks like `postgres` code will be altered in addition to `initdb`

**Comment by mbautin** [comment]
Adding @m-iancu's notes here:

Similar to vanilla PostgreSQL we use the initdb script to initialize the YSQL database.
However, due to the distributed nature of YSQL we need to modify and use initdb differently.
In vanilla PostgreSQL initdb creates a local folder for postgres data and initializes it with the following
1. data folders/files storing postgres system databases/tables 
    - initialize template1 database
    - copy template1 folder to initialize template0 and postgres database
2. configuration folders/files
   - e.g. pg_hba.conf or postgresql.conf
In YugaByte's case we have to distinguish these two cases:
1. Initialize system databases/tables once per cluster (we informally call this the "master initdb")
2. Initialize configuration files once for each tserver (we informally call this the "tserver initdbs") 

The current state of the implementation is as follows:
1. The master initdb is run separately (currently moving from yb-ctl into yugabyte code) and runs initdb with yugabyte enabled.
This causes all the DDL/DML/DCL statements to run against yugabyte and will create and load up the relevant tables (which should actually 
be system tables stored on the master nodes -- not on the tservers).
2. The initdb is run by each tserver (see pg_wrapper.cc) as a regular (vanilla postgres) initdb call (with no yugabyte enabled) which ends up creating both data and configuration folders/files. But, once we start postgres with yb-enabled mode the data files will not be used at all, only the config files.
