### ISSUE TITLE
Fix flaky test PgIndexBackfillTest.ColocatedRetainDeleteMarkers

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#9868]
```
revision | pass/fail/started | pass%
ad6a74a | 20/0/20 | 100%
23d3f40 | 0/20/20 | 0%
```
Looks like https://github.com/yugabyte/yugabyte-db/commit/23d3f404c394cae41a2535a59a9ca25ecdfd5c12 commit is the reason for this flaky case

**Comment by tedyu** [comment]
I already sent out D12768 Friday which should fix the test.
