### ISSUE TITLE
[xCluster] : Fix CDC Stream Deletion Race Condition

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#9877]
Currently, there is a race condition on the Producer between CatalogManager::DeleteCDCStream & CDCServiceImpl::UpdateCheckpoint.  The 'cdc_state' table entries are dynamically inserted by UpdateCheckpoint & the CDC stream is only validated on first access.  This means that, when DeleteCDCStream runs and removes all entries from the 'cdc_state' table, a subsequent GetChanges request by the Consumer can recreate those entries even though the stream has been deleted on the Producer's Master.  This race condition, in addition to leaving dangling entries, also ends up affecting the lag metrics, retention policy, and YW UI display.  This was seen in a customer setup when the replication fell too far behind and we needed to recreate the setup.

**Comment by nspiegelberg** [comment]
Talking with @rahuldesirazu , we sketched together 2 possible design solutions:

1. Refactor CreateCDCStream to insert all the 'cdc_state' entries up front.  We will also need a hook so tablet splitting also inserts a new entry.  The UpdateCheckpoint entry would be updated to only insert IF_EXISTS, so it would error out on delete CDC stream.
2. DeleteCDCStream uses RetryingTSRpcTask or TSHeartbeatResponsePB to update all TServers with the new state of the CDC Stream.  Only delete 'cdc_state' & move the SysCatalog CDC entry from DELETING=>DELETED after this occurs.

Upon further inspection, we also need to handle cleanup of the in-memory state of CDC Metrics on the Tablet, update the CDCService cache, and Reset the cdc_min_replicated_index.  #2 would make that easier.

**Comment by nspiegelberg** [comment]
This race condition is referenced in a comment within #9685

**Comment by hulien22** [comment]
> Upon further inspection, we also need to handle cleanup of the in-memory state of CDC Metrics on the Tablet, update the CDCService cache, and Reset the cdc_min_replicated_index. 2 would make that easier.

Encountered this issue of not handling cleanup of in-memory state on the tservers. This happened as part of a customer interaction where there was a delete_cdc_stream on a live replication setup, which then led to dangling entries in system.cdc_state and then high lag metrics. After deleting the dangling entries, the high lag metric sticks around, and is only reset upon a tserver restart.
