### ISSUE TITLE
[YCQL] add support for toJSON(), fromJSON() built-ins

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#992]
Hi, I'm getting the following error when I try to access ybdb cassandra API with Jetbrains DataGrip tool. It is able to connect but not get any data.

```
SQL error: Invalid Function Call. Failed calling 'tojson(map&lt;text, text&gt;)'. Not found: Function 'tojson' does not exist
SELECT keyspace_name, durable_writes, toJson(replication) as replication
                                      ^^^^^^
FROM system_schema.keyspaces
 (error -214).
```
Could this be related ?

_Originally posted by @hreidar in https://github.com/YugaByte/yugabyte-db/issues/778#issuecomment-456349999_

**Comment by kmuthukk** [comment]
For examples:

See http://cassandra.apache.org/doc/4.0/cql/json.html#the-tojson-function
See https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useQueryJSON.html

As reported by @hreidar - the DataGrip tool seems to rely on the toJSON() in the SELECT clause. It would be nice for us to add this support and allow folks to access YCQL via DataGrip.

**Comment by kmuthukk** [comment]
Another user reported:

<<.. I’ve been trying to use the IntelliJ Cassandra DB Explorer against YB but I’m getting the following error when it tries to read the schema.
```Invalid Function Call. Failed calling 'tojson(map&lt;text, text&gt;)'. Function 'tojson' does not exist
SELECT keyspace_name, durable_writes, toJson(replication) as replication
                                      ^^^^^^
FROM system_schema.keyspaces
 (error -214).```
Is this a known issue?

>>

**Comment by m-iancu** [comment]
`toJson` is done in [541055c](https://github.com/yugabyte/yugabyte-db/commit/541055cd72931aa579d6fec1a99c8c6808ff3402). Closing as `fromJson` is not the roadmap and if added later will be tracked separately.
