### ISSUE TITLE
[Jepsen][YСQL][v2.6] Inconsistency in bank test under kill-master

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#9925]
Jira Link: [DB-1382](https://yugabyte.atlassian.net/browse/DB-1382)
During our Jepsen on Jenkins runs, we found an issue for ` yb yugabyte-2.4.7.0-b7-centos-x86_64.tar.gz bank nemesis kill-master`, which corresponds to YB @ 54c9461c9b79b5164f4aeded1d327e4f9f5000d2 using yugabyte/jepsen@59499015cd04c9c7e351d8edfedf5c2380d8e1f6.
Grand total goes from 100 to 105:
![bank](https://user-images.githubusercontent.com/2077017/132092198-2b35e7eb-c4eb-4171-97f3-9c7534844f4c.png)
Logs: [2021-08-31_ycql_bank_kill-master.zip](https://github.com/yugabyte/yugabyte-db/files/7109628/2021-08-31_ycql_bank_kill-master.zip)

Same kind of failure is observed for `partition` nemesis: #8714

**Comment by frozenspider** [comment]
Also works with `pause-master`:
![bank](https://user-images.githubusercontent.com/2077017/132485462-2e0b7063-fe7a-4657-b327-466d30e5e0f8.png)
[2021-09-07_2.4_ycql_bank_pause-master.zip](https://github.com/yugabyte/yugabyte-db/files/7127743/2021-09-07_2.4_ycql_bank_pause-master.zip)

**Comment by qvad** [comment]
Not reproducible in current stable 2.8 version
