### ISSUE TITLE
[docs] Typo in README

### ISSUE THREAD

**Issue by yz1509** [yugabyte/yugabyte-db#9930]
node3 has two tablet3 = =

![](https://raw.githubusercontent.com/yugabyte/yugabyte-db/master/architecture/images/yb-architecture.jpg)

**Comment by polarweasel** [comment]
The second "tablet3" in node3 should be tablet4. We'll get it adjusted.

**Comment by lizayugabyte** [comment]
@ddhodge @polarweasel @aishwarya24 Does anybody know which readme this is? I don't think we have this image anymore

**Comment by polarweasel** [comment]
Update: it's the README at the root of this repo.
