### ISSUE TITLE
[YSQL] Simplify initdb: we should not have to run it separately from every deployment workflow

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#994]
Figure out an approach to avoid running initdb (to setup YSQL cluster) explicitly from yb-ctl, yb-docker-ctl etc.

**Comment by mbautin** [comment]
From @kmuthukk : I agree. One general question: if we do that, we also need to make sure existing scripts (e.g. `yb-ctl`, `yb-docker-ctl`, helm charts, etc) no longer explicitly call (the master) `initdb`. So users would need to update both scripts and code at the same time (for `yb-ctl` this is currently easy cause it's packaged with YB), but do we already have a system for the others?

**Comment by mbautin** [comment]
Also from @kmuthukk:

> Plus - can we first make a second run of initdb become a no-op if it notices that initdb has effectively been done already. (edited)

**Comment by ndeodhar** [comment]
We should follow a 3-step approach for this:
1. Make successive runs of initdb no-op if initdb has already been run on the cluster (https://github.com/YugaByte/yugabyte-db/issues/1157)
2. Run initdb as part of master raft group initialization (this GitHub issue)
3. Remove initdb runs from yb-ctl, yb-docket-ctl, helm, KB docs(https://github.com/YugaByte/yugabyte-db/issues/1158)

**Comment by m-iancu** [comment]
This is addressed in https://github.com/yugabyte/yugabyte-db/commit/bdec7bdc2b48301c6b097cf7f54e5bb425bdc2e3. See also issue #1411.
