### ISSUE TITLE
[xCluster] 2.6 Test Plan

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#9946]
### Setup/Happy Case ###

1. Create two clusters (2.4) with a 50 tables and 50 indexes of matching schemas on both sides, TLS enabled, and a two region, 3 dc setup 4 nodes each where the two dcs in the same region are preferred.
2. Setup bidirectional replication on these tables, 10 tables at a time. Do this by using a different producer_uuid for each of the batches. This can be any string like "batch_1", "batch_2", ... After each batch wait a few minutes and make sure that the cluster is in a stable state before starting the next batch.
3. Start workloads on just one cluster.
4. After some time, upgrade both clusters to 2.6.
5. Wait a few hours and confirm the lag metric looks reasonable. Stop the workload and confirm the metric becomes 0.

@tvesely Can help with automating these steps.

### Altering Config ###

1. Add 10 tables to the replication stream and ensure that the clusters can handle it. We may need to use a new producer_uuid for this operation.
2. Disable replication, then drop replication, and delete these 10 tables and make sure lag doesn't become extremely large.

### Outages/Unexpected Failures ###

1. Stop a node on the source side and confirm lag is reasonable and we don't see any huge spike in resource utilization on other nodes.
2. Stop a node on the sink side and confirm the same.
3. Repeat this with rolling restarts on both the clusters.

### Backup/Restore (Lower Pri) ### 

1. Drop all tables on the sink side
2. Setup replication via backup/restore outlined in #6870.
3. Make sure the cluster was able to handle concurrent B/R and that lag doesn't look too high.

**Comment by bmatican** [comment]
@Arjun-yb @rahuldesirazu ok to close this out, or do we still need the issue open for some reason?

**Comment by rahuldesirazu** [comment]
Closing this issue since this an old test plan.
