### ISSUE TITLE
[YSQL] Add support for TRUNCATE .. RESTART IDENTITY and CONTINUE IDENTITY clauses

### ISSUE THREAD

**Issue by lukaseder** [yugabyte/yugabyte-db#9950]
It seems the following syntaxes are parsed but rejected:

```sql
create table t (i int generated by default as identity);
truncate table t continue identity;
truncate table t restart identity;
```

The error message is misleading. It says:

> SQL Error [0A000]: ERROR: sequences not supported yet
>  Hint: Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
>  Position: 18

But sequences are supported, so the error should be about this particular `CONTINUE IDENTITY` and `RESTART IDENTITY` syntax not being supported (yet)

**Comment by yifanguan** [comment]
Feature supported by the commit -> f2bb921
