### ISSUE TITLE
[YSQL] copy/paste error in PgValueFromPB

### ISSUE THREAD

**Issue by andrei-mart** [yugabyte/yugabyte-db#9965]
https://github.com/yugabyte/yugabyte-db/blob/4ae9e7dd0275d6b76c19f2905f281499a67f514f/src/yb/yql/pggate/pg_value.cc#L109

It should be ql_value.**binary**_value().size(), if ql_value holds a binary, ql_value.string_value().size() is always 0 and function produces incorrect datum as a result and weird errors:

```
yugabyte=# create table jtest(id int primary key, value jsonb);
CREATE TABLE
yugabyte=# insert into jtest values (1, '["a", "b"]'::jsonb);
INSERT 0 1
yugabyte=# select * from jtest;
 id |   value    
----+------------
  1 | ["a", "b"]
(1 row)

yugabyte=# update jtest set value = value || '["c", "d"]'::jsonb where id = 1;
ERROR:  Query error: unknown type of jsonb container
```

**Comment by m-iancu** [comment]
Fixed by 90392f18120e26e221e8604ea31e59a95f50c834.
