### ISSUE TITLE
[YSQL] CREATE TABLE optional constraints

### ISSUE THREAD

**Issue by robertpang** [yugabyte/yugabyte-db#997]
The following constraints are not yet supported for CREATE TABLE statement.

1. UNIQUE
2. FOREIGN KEY
3. EXCLUDE

**Comment by frozenspider** [comment]
UNIQUE constraints are tracked in #1022

**Comment by m-iancu** [comment]
Closing as UNIQUE and FOREIGN KEY constraints are now supported, while EXCLUDE constraints are tracked in https://github.com/yugabyte/yugabyte-db/issues/3944.
