### ISSUE TITLE
NoNodeAvailableException with YCQL Java 4.6 driver when using withLocalDatacenter 

### ISSUE THREAD

**Issue by randersenYB** [yugabyte/yugabyte-db#9975]
Jira Link: [DB-1563](https://yugabyte.atlassian.net/browse/DB-1563)
During development of a openjdk V16 application to model an issue with a customer, I tripped upon an issue where a node (172.17.0.4) when executing a select statement starting throwing a "NoNodeAvailableException". I had the driver tracing enabled (https://docs.datastax.com/en/developer/java-driver/4.6/manual/core/logging/) and noticed that the driver believed that none of the nodes in my one DC cluster (datacenter1) belonged in this DC.  This issue seemed to only isolated when I connected to 172.17.0.4 contact point (was able to connect using 172.17.0.12 with same app without issue). The failure was consistent with this node for at least 30 mins (could have been longer) before it just started working again. I did not restart the cluster. Also I tried basically the same app logic using the YCQL Java 3.8 driver using the 172.17.0.4 contact point when the 4.6 app was failing (one at a time, ran 4.6 app failed, ran 3.8 app successful, ran 4.6 app failed). 

Frankly, I don't know what triggered the issue or what fixed the issue. 

I have added additional comments imbedded in the driver trace logs. I have attached the application driver trace logs for both the 4.6 and 3.8 versions of the test applications, the actual application projects, server logs, and screen shot of the node IP addresses.

YugabyteDB Version: 2.7.1.1
RF 3
Nodes: 6
AZs: 1
Cloud: cloud1
DCs: 1 (datacenter1)
Racks: 1 (rack1)
OS: CentOS Linux release 7.9.2009 (core)

[webserver_dump.tar.gz](https://github.com/yugabyte/yugabyte-db/files/7146796/webserver_dump.tar.gz)
![NodeIPAddresses](https://user-images.githubusercontent.com/85318816/132925691-b5bfbc62-d3e7-41e9-857f-e78614165d2a.png)
[ApplicationDriverTraceLogs.zip](https://github.com/yugabyte/yugabyte-db/files/7146797/ApplicationDriverTraceLogs.zip)
[ybTestApps.zip](https://github.com/yugabyte/yugabyte-db/files/7146798/ybTestApps.zip)

**Comment by aravind-nallan-yb** [comment]
Did you ever collection the combination of 
select * from system.local
and
select * from system.peers

from this node? Did they have the datacenter value set?

**Comment by randersenYB** [comment]
I am added some additional context around this ticket from a thread:

I believe there are multiple issues we are discussing. My observations, "digging" around, and the application info from our customer with the 4.6 Java drivers may indicate there are some type of issues with the Partition and/or DC aware policy. When they were using prepared CQL statements in their production applications they were receiving thousands of "No Node Available" exceptions plus they were also see 50% of their writes as remote.  When these "No Node Available" exceptions started, it seemed to correspond to TServer leader election but I believe it may also occurred during Master elections. When our customer removed the prepare statements they did not receive any "No Node Available" exception re-running the same application with the same production data. This indicates an issue(s) around the Partition and/or DC aware policies. This spurred me to start an investigation where I "tripped" upon  this issue (9975). I don't fully understand how this was triggered but it took hundreds of runs of my test application which is included in this ticket that resulted in the issue. In the ticket it is clear from the driver traces that the driver is "confused" regarding the current DC. I only had one DC but it "thought" that none of my nodes belonged to this DC plus the DC name seemed to be blank. In terms of the "local" and "peer" tables they seemed to be correct but this is impossible  conclude if there is some type of "timing" issue(s). For example, when I looked they were fine. If it is some type of "timing" issue this may explain why the other application (e.g., 3.8 driver version) worked when testing when the 4.6 test app was failing. During my observations of these test runs with driver trace enabled, I also notices "strange" behavior like prepares being re-prepared by the driver (which I assumed was somehow invalided by the server) for no obvious reasons (e.g., change in the table schema, etc.). When I re-run my test application without prepares, I don't see or "tripped" upon any of these issues. This doesn't mean they don't exists, but I haven't been able to prove or disprove anything. The only "solid" evidence of an issues is again the git hub issue https://github.com/yugabyte/yugabyte-db/issues/9975. I do not believe that issue https://github.com/yugabyte/cassandra-java-driver/pull/13 "plays" into my git hub ticket. Is it possible it is contributing to the issues at our customer, yes it is possible and we can't rule it out. IMO, I believe we are "facing" multiple issues where one "seems" to be timing related. The C* Java 4.x driver is a complex driver that is far more "advance" compared to the 3.x driver. The 4.x driver is based on Apache C* behavior and complete metadata from Apache C* nodes. Our product does not behavior the same and based on my observation, we are not providing all the meta data as in a Apache C* DC/Cluster.

**Comment by randersenYB** [comment]
FYI we have another large customer who is also inserting thousands of records and they haven't "tripped" upon this issue. They are using partition batches (this customer is not) and they are setting the CL on each transaction. They were originally "seeing" high remote writes until they change the CL setting on the session to the individual insert statement.

**Comment by ashetkar** [comment]
Not enough info to repro and last comment suggests it's not an issue. Please reopen in case seen again.
