### ISSUE TITLE
[docs] Docs update for GO (lib/pq) +SSL for YSQL

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#9986]
The documentation content is available here: https://docs.google.com/document/d/1Hm5XUE4ycjy48Ipmzs6z9c1Bh_FjlG2AtlDt54UAeYs/edit?usp=sharing

**Comment by ddorian** [comment]
Can you do a pull request ?

**Comment by ashetkar** [comment]
I'll give it a try. (not sure how I can embed an image in a md file)

**Comment by ddorian** [comment]
>  (not sure how I can embed an image in a md file)

Check how it's done on existing docs (example https://github.com/yugabyte/yugabyte-db/blob/780dfe7b67749cbd01944041d5be8774c6e05143/docs/content/latest/architecture/transactions/_index.md#L40)

**Comment by ashetkar** [comment]
Thanks @ddorian. But I was actually looking for a way to place an image inline with the text like the one in the docs linked above.

On a second thought, I'd let docs team decide on the layout/formatting as discussed with them earlier last week.

I've now changed the permissions on the Google doc to allow comments, in case you want to review.
